### PR TITLE
VideoPlayer: bump framebuffer object to 16 bit

### PR DESCRIPTION
**Pull request by FernetMenta**
@laurimyllari please have a look at this
Can we move yuv2rgb conversion back to pass #1 with this?

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by laurimyllari** [comment]
I tested this both with and without the 16bit bump using the NTSC Digital Video Essentials. The 16bit FBO fixes banding in full range output with advanced scaling.

Looks good to me.

**Comment by FernetMenta** [comment]
@laurimyllari does this mean limited/full range conversion can be moved to colour conversion matrix?

**Comment by laurimyllari** [comment]
Yes, I think it can be moved. I would like to have an override for the 3dlut case though, but I can work on that.

**Comment by FernetMenta** [comment]
@laurimyllari I would just set a flag like for the single pass method: https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGL.cpp#L909
3dlut can of course handle it differently

**Comment by laurimyllari** [comment]
That looks convenient

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
jenkins build this please

**Pull request merged**
