### PR TITLE
fixed: File cache logic for reading from source

### PR DESCRIPTION
**Pull request by arnova**
This fixes the issue discovered with NFS + filecache by @MilhouseVH

### CODE REVIEW

**Comment by arnova** [comment]
@MilhouseVH : Can you test this once again since it's slightly modified from the initial patch I gave you? And can you include it in your builds?

**Comment by MilhouseVH** [comment]
Tested all buffermodes (0-4) on Ubuntu (x86_64) and LibreELEC (x86_64, RPi2) and working perfectly - no seek or resume issues with `nfs://` (or `smb://`). Will include this PR in nightly builds and report any issues - many thanks!

**Comment by arnova** [comment]
@MilhouseVH : Any reports about this?

**Comment by MilhouseVH** [comment]
Sorry for the late reply, just catching up on email - no negative reports so far, fix looks good to me! Thanks.

**Pull request merged**
