### PR TITLE
Fixed using 'label2Mask' for folders

### PR DESCRIPTION
**Pull request by vlmaksime**
## Description
Fixed using 'label2Mask' for folders
Add ability use 'label2Mask' parameter for plugin folders

## Motivation and Context
Fixes problem described in the forum: [How to use Label2 for TV Shows?](https://forum.kodi.tv/showthread.php?tid=347646)

## How Has This Been Tested?
Compiled, tested with few video addons.

## Screenshots (if appropriate):
Add-on directory with TV Shows before changes:
screenshot00001
Add-on directory with TV Shows after changes:
screenshot00000

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by vlmaksime** [comment]
Can you merge this RP?

**Comment by dagwieers** [comment]
Would be nice to fix this. What is the status?

**Comment by vlmaksime** [comment]
Done

**Comment by vlmaksime** [comment]
Is there any chance to include this PR to Matrix?

**Review by enen92 — APPROVED** [review]

**Comment by enen92** [comment]
@vlmaksime sorry for the time taken to look into this.

**Comment by vlmaksime** [comment]
@enen92, thanks

**Pull request merged**
