### PR TITLE
Ticket #16385 fixed

### PR DESCRIPTION
**Pull request by Pedrock**
Fixed http://trac.kodi.tv/ticket/16385 by increasing buffer max limit from 4Gb to 17179869184 Gb.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
imo we shouldn't enable users putting in idiotic numbers

**Comment by fritsch** [comment]
From a first glance the code is fine - thanks much.
Use case: Caching upto a full bluray in memory?

@MartijnKaijser use cases might differ - I also do not really see when we should need to cache more than 4gb in memory - but one never knows what users do.

We have two possibilites:
a) check the original code's size_t value for overflow (easy) and clamp to the max value we can compute with it. Even easier - we can change the maximum in the xml parsing to a value that is sane (one loC commit)
b) We are in a 64 bit world today.

**Comment by Pedrock** [comment]
@fritsch I like your c) possibility. I can work on it if you want.
Basically it involves using size_t and checking if the xml value does not cause overflow.

**Comment by fritsch** [comment]
What about:
```
diff --git a/xbmc/settings/AdvancedSettings.cpp b/xbmc/settings/AdvancedSettings.cpp
index 4e27b39..1346de6 100644
--- a/xbmc/settings/AdvancedSettings.cpp
+++ b/xbmc/settings/AdvancedSettings.cpp
@@ -736,7 +736,8 @@ void CAdvancedSettings::ParseSettingsFile(const std::string &file)
     XMLUtils::GetInt(pElement, "curllowspeedtime", m_curllowspeedtime, 1, 1000);
     XMLUtils::GetInt(pElement, "curlretries", m_curlretries, 0, 10);
     XMLUtils::GetBoolean(pElement,"disableipv6", m_curlDisableIPV6);
-    XMLUtils::GetUInt(pElement, "cachemembuffersize", m_cacheMemBufferSize);
+    XMLUtils::GetUInt(pElement, "cachemembuffersize", m_cacheMemBufferSize, 0, UINT_MAX - 1);
+
     XMLUtils::GetUInt(pElement, "buffermode", m_networkBufferMode, 0, 3);
     XMLUtils::GetFloat(pElement, "readbufferfactor", m_readBufferFactor);
   }
```

**Comment by fritsch** [comment]
Considering the really, really limited usecase for caching more than 4gb of data - I think keeping the GetUint, but adding: 
```
XMLUtils::GetUInt(pElement, "cachemembuffersize", m_cacheMemBufferSize, 0, UINT32_MAX - 1);
```
and (!) fixing the ```atol``` that this GetUInt method uses.

**Comment by MartijnKaijser** [comment]
@arnova your thoughts on this?

**Comment by arnova** [comment]
I'm with @fritsch : I think the scenarios where one want this are rather limited. Keep in mind that setting this to 4GB, already uses 12GB of RAM (without OS and the rest of Kodi etc.). Furthermore I think if this limit is increased we really need some sanity check to compare against the setting against the amount of available (free) memory.

**Comment by MartijnKaijser** [comment]
Let's close this for now.

**Comment by arnova** [comment]
ps. Note that my remark regarding memory usage was wrong. It's only valid when using CacheMemBuffer, but since we switched to CircularCache ages ago, that's no longer an issue (note-to-self: Get rid of unused CacheMemBuffer class).

**Pull request closed without merging**
