### PR TITLE
Added: set the correct proxy for FFMPEG to pick up if HttpProxy was p…

### PR DESCRIPTION
**Pull request by basrieter**
This PR fixes the issue I reported at http://trac.kodi.tv/ticket/16336 and http://forum.kodi.tv/showthread.php?tid=248440.

It sets the proxy value (passed in via the HttpProxy url parameter) to the environment variables HTTP_PROXY and HTTPS_PROXY. If a proxy was already configured, the original value is stored and restored again during the Dispose of the DVDDemuxFFmpeg.

### CODE REVIEW

**Comment by fritsch** [comment]
@FernetMenta ping - I am not sure if this the right place where to handle this ... I asked the ffmpeg people about the proxy and they told: We use the environment ... Is the demuxer the right place?

**Comment by FernetMenta** [comment]
First of all the behaviour is faulty. You can easily see that even if the environment is not set, it gets unset on dispose.
Hiding this function in a method called GetFFMpegOptionsFromURL that returns AVDictionary is no-go.

Isn't this something which affects other protocols too, that are not handled by ffmpeg input stream?

**Comment by fritsch** [comment]
Whenever curl is used that one has a special "httpproxy" handling working quite similar as this implementation. In my eyes both approaches suck - as people think that |httpproxy=lala|myspecialoption=hurz|andsoon=25 would be a special standard ... which it is not, but something only _we_ do since years in kodi.

Some even say: it would be a security issue as every non parsed option will be send as headers ...

You are right with the faulty behaviour.

**Comment by fritsch** [comment]
For the way curl does it: https://github.com/xbmc/xbmc/blob/master/xbmc/filesystem/CurlFile.cpp#L809 (fully hidden in ParseAndCorrectUrl

**Comment by basrieter** [comment]
I agree with GetFFMpegOptionsFromURL not being the right place. However, my knowledge on the Kodi code internals is not good enough to pinpoint a better location. 

So what would would be a better location for setting and unsetting? 

Regarding the unsetting in the dipose: it will either restore the original variable or unset it. That way you will end up with the same situation as you had before: with a set one or none.... Or am I missing something?

**Comment by fritsch** [comment]
Problem: http_proxy _and_ https_proxy are _unset_ always even if the URL did not have httpproxy specified. Therefore user ends without his global http_proxy / https_proxy

You see that?

**Comment by basrieter** [comment]
No,  I check whether there was an proxy set before and only if that was not the case,  I unset,  otherwise it restores the original. Or is the "if" in the dipose not working?

**Comment by fritsch** [comment]
https://github.com/basrieter/xbmc/commit/dd90ffd414dbade5138d7b5985fb4e1c51503b0e#diff-773d209edc21ee1fe8fa09e7a1a1d59dR528 <- else case

and you back it up only if http_proxy was in the URL https://github.com/basrieter/xbmc/commit/dd90ffd414dbade5138d7b5985fb4e1c51503b0e#diff-773d209edc21ee1fe8fa09e7a1a1d59dR648

But you always remove it on dispose.

**Comment by basrieter** [comment]
Duh. I will make some changes tonight. Thanks for all the input.

**Comment by FernetMenta** [comment]
> as people think that |httpproxy=lala|myspecialoption=hurz|andsoon=25 would be a special standard ... which it is not, but something only we do since years in kodi.

if this is not a standard but an ugly hack -> drop that crap and look for something better.

**Comment by fritsch** [comment]
The problem is: There is not necessarily something better - as there is no standard :-(

I am also not sure if adding an "ffmpeg_proxy" should be considered or if we should set the env via the kodi set proxy always?

Some of those "streams" want to tunnel themselves via some localhost proxies ... I really have no idea ...

**Comment by FernetMenta** [comment]
as far as I can tell https://github.com/xbmc/xbmc/pull/3682 was a quick hack for addons passing a proxy to kodi, right?

**Comment by FernetMenta** [comment]
now it turns out this is approach has flaws and doing another hack to cope this this is wrong. back to square one, revert #3682 and do it better.

**Comment by fritsch** [comment]
@FernetMenta: Yes it looks like it. I would immplement this PR way better  and then we can decide where to move it.

I am not into that "stream urls" business at all - perhaps @wsnipex knows more about that and howto cope with it in a general way.

For now the above approach should be implemented more nicely:
- bool m_proxyNeedsRestoring (set to false on init and to true when httpproxy was set and overwritten)
- implement a struct that holds http / https_ / socks proxy
- Implement SetStreamingProxy(bool restore): Save the environment into a local struct if restore = false and restore the local struct when restore = true;

**Comment by fritsch** [comment]
> now it turns out this is approach has flaws and doing another hack to cope this this is wrong. back to square one, revert #3682 and do it better

Nope - it's a matter of decision. That "other hack" was a decision and implemented for CURL only ... now we can decide if we also want to have an additional httpproxy parameter for urls that are done with ffmpeg.

Or in other words: Support httpproxy for urls processed by ffmpeg directly

**Comment by FernetMenta** [comment]
I consider that other decision as wrong and dead end. It should be tagged depreciated and a better solution should be implemented.

**Comment by fritsch** [comment]
Okay - what would be your first shot, if you were forced to implement: Per stream proxy?

**Comment by wsnipex** [comment]
There are reasons to allow overriding the proxy per stream, so the curl approach is ok imho. There is no other way to do that if we need/want to support plains URLs.
Adding the same for ffmpeg based streams makes sense, if properly implemented as per fritschs suggestion.
Maybe make 2 methods, SetStreamProxy and ClearStreamProxy.

**Comment by FernetMenta** [comment]
for reference (1.5): http://forum.kodi.tv/showthread.php?tid=154805&pid=1323627#pid1323627

This is a security issue itself. A plugin/addon has no knowledge about what kodi does with the URL. It my just pass it along (like in this case). We may add further streams in the future and this will break again. Passing account information this way is insane. Considering this again I'd vote for immediate revert of this.

Let an addon set proxy on a list item like we did with content lookup.

**Comment by fritsch** [comment]
> Let an addon set proxy on a list item like we did with content lookup.

That sounds good yes. But that way it won't be available for simple .m3u lists - which is also a problem the m3u people have with the content lookup

**Comment by FernetMenta** [comment]
Sure it will or it least it can be done easily. The first step is that an addon needs to tell kodi how it want's an url or any other list item handled. Once this is in place, Kodi can take proper actions. 
The main problem here is that people are too lazy in implementing this API. Instead those kind of hacks pop up or assumptions are make that do not hold when implementations change.

**Comment by fritsch** [comment]
The reason I asked is:

Writing an m3u file: easy
Writing an extra addon for a specific addon is hard. iptv simple was an example.

And this API would mean: everyone that needs a custom proxy per m3u entry needs to write an addon - if we remove the curl adjustments - even for that content - would you also stop parsing user and password in such urls?

**Comment by FernetMenta** [comment]
As mentioned, passing account information this way is insane and has to be stopped because it is a security issue:

```
li = ListItem(path="http://foo.com/video.flv?foo=bar|proxy=http://user:pass@proxyserver.com")
return xbmcplugin.setResolvedUrl(li) 
```

You don't know on what type of URLs addon devs my set this proxy info, do you? There are more code paths where this info is just passed on.

**Comment by fritsch** [comment]
I am just asking :-)

I am fully no friend of all this custom hacks at all - that's why I brought it up! So on my oppinion we should remove all this non standard parsing completely. If users need to tell kodi something - they should write and addon for their content.

Removing custom parameter handling will break all applications that used it ... just wanted to ask one more time - but I think you are aware of this.

**Comment by wsnipex** [comment]
removing this in general will break plain playlists in m3u and strm files.

**Comment by basrieter** [comment]
I understand that there are a lot better ways of doing this, but for now, is it OK if I will update the PR with the suggested changes:

**Comment by FernetMenta** [comment]
this won't make it into Jarvis or any other future version. not sure if we revert #3682 even for 16.0 but for 17.0 at the latest.

**Comment by fritsch** [comment]
Nope :-) - we need a solution here. Adding new code - that we don't want for longterm - will decay the architecture.

**Comment by fritsch** [comment]
I will send a PR now - that also declares the other "CurlFile" hacks as obsolete.

**Comment by basrieter** [comment]
Ok, but as it was mentioned by @wsnipex, there are reasons for a single stream to allow a different proxy than the default Kodi one. So I really hope that for now the curl 'hack' will remain working until a better solution is found?

**Comment by FernetMenta** [comment]
> there are reasons for a single stream to allow a different proxy than the default Kodi one

nobody denies this. but it has to be done properly

>  So I really hope that for now the curl 'hack' will remain working until a better solution is found?

need to discuss with some security experts what we can do for 16.0. as soon as we branch off 16, I will drop the hack for 17.0. plenty of time for those how want this feature to work on a better solution. I will be happy to assist.

**Comment by fritsch** [comment]
@FernetMenta when looking into the way those strings are handled in core :-) security experts will hate us anyways. Btw. a specially crafted URL could redirect complete kodi traffic to a special proxy "outside" the world. As it runs in same process - I even think all other process will use the in between proxy while the video stream is running :-)

Addon Updater - some library scanning scripts and so on ... 

Lol - I still have to laugh about "security experts" in combination with our crude link parsing strategies ...

**Comment by fritsch** [comment]
```
http://www.lalala.org/stuff.m3u8|proxy=http://mypersonalproxythatwilleatyourdata:8080
```

^^ this would cause that all kodi traffic - if libcurl is http_proxy aware will be redirected via that proxy ... so - everything you need to do is spread some m3us arround and you get every www traffic by all kodi users using your m3u

**Comment by basrieter** [comment]
So, for now, is it OK if I change this PR to only prevent DVDDemuxFFmpeg from adding the HttpProxy as a HTTP header? Then at least that would solve a username/password from being send as a HTTP header?

**Comment by FernetMenta** [comment]
I am sorry, fix the root cause please. Spoiling more code as a result of #3682 is wrong.

**Comment by basrieter** [comment]
@FernetMenta I know it needs a proper fix, but your PR will cause all add-ons or other files that use HttpProxy to now send sensitive proxy information over the internet as HTTP header. That makes no sense. Your PR is not only reverting a feature that was in Kodi for over 2 years (and was requested by many users), it is actually making the initial issue I posted worse: now even more usernames/passwords are being sent. 

I am not saying to implement or encourage this, but instead of making it an HTTP header, just to just filter the HttpProxy header so it wont be used by curl of ffmpeg. Or better, log a warning to indicate it was deprecated. So instead of

```else if (name == "httpproxy")
        SetStreamProxy(value, PROXY_HTTP);```

do 

```else if (name == "httpproxy")
        CLog::Log(LOGWARNING, <some message>);```

And the same in the DVDDemuxFFmpeg? Would that not be the safest and most user friendly way for now?

**Comment by FernetMenta** [comment]
the problem is that an addon does not know what input stream or demuxer will pick up a list item. hence you do hard in filtering it.

> it is actually making the initial issue I posted worse: now even more usernames/passwords are being sent

not form a Kodi POV. now it is an addon issue because Kodi does not encourage an addon sending this data.

better solutions are welcome. I know that this feature was desired and things may break but that don't change the fact that the current implementation has a big flaw.

**Comment by basrieter** [comment]
Great, make it an add-on issue, without notifying all authors. I understand your point of view, seriously, but give all add-on makers a break and filter them in these 2 situations.

**Comment by Rutix** [comment]
@FernetMenta actually removing the feature without deprecating it first or log a warning or whatever does also make it worse from a Kodi POV. If you support something for years you can't just remove it and then point fingers to the addons. I think it's in the best interest to do it in phases, instead of just reverting it. I think we can all agree that the current situation is not favorable but throwing people into a security hell is really not the solution.

**Comment by FernetMenta** [comment]
I did say that I am open for better solutions but I haven't seen any so for. ffmpeg demuxer code certainly won't be touched as a result of this issue.

**Comment by FernetMenta** [comment]
can anybody point me to place where this "feature" is documented?

**Comment by basrieter** [comment]
The initial PR is here: https://github.com/xbmc/xbmc/pull/3682

Just to be clear on this: I (not speaking for all the other users that use proxies) don't mind disabling all of this this for now until a better solution comes up. All I am asking is to filter out the HttpProxy to make sure it does not get send as a HTTP header by either ffmpeg or curl. 

And I am willing to see what options there are for a better solution.

**Comment by FernetMenta** [comment]
see my post on #8434

**Comment by jhol** [comment]
I have an alternative approach in #8680 since I patched FFmpeg.

**Pull request closed without merging**
