### PR TITLE
Various cppcheck perf fixes

### PR DESCRIPTION
**Pull request by tobbi**
Another round of cppcheck perf fixes throughout various files.

I picked issues at random and fixed them.

### CODE REVIEW

**Comment by ksooo** [comment]
Looking good.

**Comment by mkortstiege** [comment]
Please compile and run-time test your changes ;) This breaks build: `class ‘CGUIDialogSubtitles’ does not have any field named ‘m_loadType’`

**Comment by Montellese** [comment]
@mkortstiege: It does have an `m_loadType` field but it is inherited from `CGUIWindow` so it can't be set in the initialization list.

**Comment by mkortstiege** [comment]
@Montellese sure. Just pasted the error output.

**Comment by fritsch** [comment]
Basically I don't like the ```new``` calling in the initializer list ... http://stackoverflow.com/questions/14681714/using-new-in-a-member-initializer-list-of-constructor <- might become harmful

**Comment by Paxxi** [comment]
Agree with @fritsch , it's unlikely but best avoid a bad habit.

**Comment by ksooo** [comment]
+1 to what @fritsch said. new in initlist might lead to resource leaks (due to std::bad_alloc), overlooked this in the frist place, sorry.

**Comment by ksooo** [comment]
To solve the "new in initializer list may lead to resource leak" problem I suggest to change the type of  m_subtitles and m_serviceItems to std::auto_ptr<CFileItemList>. 

Then, new in init list is no harmful any more. If first new (m_subtitles) in initlist fails, no memory gets allocated on the heap, thus no resource leak. If first new succeeds and second new (m_serviceItems) fails, dtor of (the already fully constructed) std::auto_ptr m_subtitles will be called, which frees the heap memory alocated with the first new.

**Comment by Paxxi** [comment]
Well not auto_ptr that's deprecated, unique_ptr or shared_ptr depending on ownership

**Comment by ksooo** [comment]
@paxxi sure. thx for the headsup.

**Comment by MartijnKaijser** [comment]
care to update and rebase? thx

**Comment by tobbi** [comment]
I'm in the middle of my Bachelor's thesis. I will put it on my list to do when I have got time :)

**Comment by tobbi** [comment]
I rebased the contents of this PR against latest master... Note that cppcheck found other things  but I didn't include them in this PR yet. I might do another PR in the future that takes care of the things found in the meantime.

**Comment by tobbi** [comment]
Oh, wait, before we hit any issues, I will compile-check it.

**Comment by hudokkow** [comment]
jenkins build this please

**Comment by tobbi** [comment]
Please try to build again (I moved the m_loadType initialization back to the c'tor body)

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by tobbi** [comment]
Can you please trigger another build? I will probably set up a VM just for building Kodi, because it's just tiresome on OS X and doesn't work.

**Comment by mkortstiege** [comment]
jenkins build this please

**Comment by tobbi** [comment]
win32 build failure seems unrelated! Please merge!

**Comment by MartijnKaijser** [comment]
@mkortstiege merge for 15.0 or delay till next?

**Comment by mkortstiege** [comment]
No need for those in v15. Could go in once branched.

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Pull request merged**
