### PR TITLE
[docs] onAVStarted and onAVChanged were missing from v18 changelog

### PR DESCRIPTION
**Pull request by enen92**
## Description
`onAVStarted` and `onAVChanged` exposed to python in https://github.com/xbmc/xbmc/commit/fb50ae8c042ad52a22003ec71ecc35cc725bbd6d#diff-c403255a1a8de83c38dd7edf4f8d7a47 were not tagged with `@python_v18 New function added.` and thus were missing from the changelog. `updateInfoTag ()` was showing a massive font in Python v18 changelog due to the fact of being in-between a block. This PR fixes both issues.

Noted in (cross-reference): https://github.com/xbmc/xbmc/issues/14574

## Motivation and Context
Proper docs for Leia. Changelog.

## How Has This Been Tested?

compiled docs and checked the output

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [x] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Too soon. Still needed some changes

**Comment by enen92** [comment]
I'll add a commit for it on the PR I'm finishing

**Comment by Razzeee** [comment]
Please use the WIP label if you know that something needs more work.

**Comment by MartijnKaijser** [comment]
Really? Sorry but that I disagree with and will not support. I mentioned something that was missing that was just a minor adjustment.

**Comment by Razzeee** [comment]
Then don't :)
But you can't expect everybody to always be up to date on slack.

**Comment by MartijnKaijser** [comment]
You can't also expect others toerge a PR only been up some hours to be merged before you can give your approval which was asked

**Pull request merged**
