### PR TITLE
[TexturePacker][gif] The Graphic Control Extension is optional.

### PR DESCRIPTION
**Pull request by MartijnKaijser**
Backport of
https://github.com/xbmc/xbmc/pull/8971

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@ace20022 could you check if correct?

**Comment by ace20022** [comment]
@MartijnKaijser looks good. Sorry I thought I had more time, since it should be for 16.1.

**Comment by MartijnKaijser** [comment]
Oh don't worry about it :) Was doing backports anyway. 
jenkins build and merge

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
