### PR TITLE
VideoPlayer: fix subsequent seeks

### PR DESCRIPTION
**Pull request by FernetMenta**
skip seeks if processing of last seek is still in process

Actual change is 64c6ce2 and 8134a7e
The rest is cosmetics.

There is still a bit work left for getting smooth video when holding down key for StepForward/Backward

### CODE REVIEW

**Comment by popcornmix** [comment]
A quick test of this PR didn't show any problems with MMAL or OMXPlayer.

When disabling all skip steps except -30s,30s and holding down left or right I don't see picture updating (video continues to play normally), but seek bar updates and video resumes when the key is released.
I don't really mind that behaviour compared to the previous rather sporadic seeking.

**Comment by FernetMenta** [comment]
@popcornmix yes, this is the remaining issue I mentioned in the comment. I want to fix this in the next round.

**Comment by popcornmix** [comment]
No objections here.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
