### PR TITLE
[ios] - removed, atv2 support. time to make way for something new. hi…

### PR DESCRIPTION
**Pull request by Memphiz**
…nt, hint :) - backport from mrmc fork

### CODE REVIEW

**Comment by Memphiz** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
would like to merge this in the next 2 days if no objections... (bin addon failure seems unrelated to this PR)

**Comment by MartijnKaijser** [comment]
Why would anyone object? ;)

**Comment by mkortstiege** [comment]
Do it.

**Pull request merged**
