### PR TITLE
Fixed the bug that ::isalnum's assertion failed

### PR DESCRIPTION
**Pull request by vidonme-developer**
Fixed the bug that ::isalnum's assertion failed when added subtitle's filename's flag-section include chinese

### CODE REVIEW

**Comment by anaconda** [comment]
Please use two spaces for indentation.

**Comment by vidonme-developer** [comment]
@anaconda   I was used two spaces for indentation in my VS IDE.   TOOLS->Options->Text Editor->C/C++->Tabs. both Tab size and Indent size are 2.

**Comment by vidonme-developer** [comment]
My screenshot







developer@vidon.me
 
From: menakite
Date: 2015-12-15 11:38
To: xbmc/xbmc
CC: developer
Subject: Re: [xbmc] Fixed the bug that ::isalnum's assertion failed (#8594)
Please use two spaces for indentation.

**Comment by vidonme-developer** [comment]
Thanks. I got it. I checked Keep tabs. I will fix it and pull request again!

**Pull request closed without merging**
