### PR TITLE
[utils] CLog: add Log and LogFunction function with additional component parameter

### PR DESCRIPTION
**Pull request by Rechi**
## Description
Add additional `Log` and `LogFunction` functions to the `CLog` class which take a component parameter. The Functions check if component logging for that component is enabled and log in that case otherwise they do nothing.

## Motivation and Context
make component logging easier

## How Has This Been Tested?
compiled for windows

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by Montellese** [comment]
Makes sense IMO but right now it only compiles on windows.

**Comment by popcornmix** [comment]
Makes sense to me too.
One issue I have with LogF is ``__FUNCTION__`` is not very informative. A lot of times this gives an ambiguous name like Create, Open, Close with no clues as to which component actually generated the message.

Most of the code I write uses:
```CLog::Log(LOGDEBUG, "%s::%s Destroying pool", CLASSNAME, __FUNCTION__);```
and I have to manually define ``CLASSNAME`` as it doesn't seem to be available from compiler.
This is a lot more useful information. I wonder if we could provide a standard way of achieving this?

It looks like gcc provides ``__PRETTY_FUNCTION__`` (with msvc ``__FUNCSIG__`` may be interesting, but I haven't investigated).

But  ``__PRETTY_FUNCTION__`` evaluates to something like:
``MMAL::CMMALPool::CMMALPool(const char*, bool, uint32_t, uint32_t, uint32_t, MMAL::MMALState)``
which is too verbose for logging, but truncating the string at the ``(`` might give something useful.

**Comment by Rechi** [comment]
now it compiles on all platforms

**Review by afedchin — APPROVED** [review]

**Review by FernetMenta — APPROVED** [review]

**Comment by MartijnKaijser** [comment]
@Rechi https://forum.kodi.tv/showthread.php?tid=298462&pid=2633192#pid2633192

**Pull request merged**
