### PR TITLE
Add android API PT + FLOAT

### PR DESCRIPTION
**Pull request by koying**
Experimental for Jarvis

### CODE REVIEW

**Comment by koying** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
You don't intent to merge this into Jarvis, do you? Apart from the fact that we don't add new features in that late stages this also requires an api version bump for audio decoders and dsp.

**Comment by koying** [comment]
Well, it's been deemed important enough for the RM to push for it, actually. As we are branched, now, it shouldn't be an issue for you (unless it break something, obviously).

I'd be very, very upset to have done all of this for one week for nothing...

What is the api bump you're speaking about?

**Comment by FernetMenta** [comment]
xbmc/cores/AudioEngine/Utils/AEChannelData.h is used by binary addons

**Comment by koying** [comment]
Ok.
Is the AEChannelData.h used in binary addons copied from master or is it a separate copy?

**Comment by FernetMenta** [comment]
copied from master by cmake during build setup: https://github.com/xbmc/xbmc/blob/f42c66f130805765b0c30d947980d5f2af847cde/project/cmake/scripts/common/prepare-env.cmake#L29

why does this matter?

**Comment by koying** [comment]
Just for information. I find it strange that something from "utils" is used in an API, so I wondered how I could have known that fact.
Deserves a big fat warning, imo ;)

**Comment by FernetMenta** [comment]
> Deserves a big fat warning, imo ;)

I agree, there is a whole bunch of such headers: https://github.com/xbmc/xbmc/blob/32af4975182bdb9e07559862731810067c020bf0/xbmc/addons/addon-bindings.mk

**Comment by fritsch** [comment]
Looking through the code, there are several things I don't like. The new AE_IS_RAW_RAW and the special casing in DVDPlayer's Audio is just ugly.

The new Passthrough class is used first for all platforms and only backuped by the settings constants.

A bigger problem is, when old infrastructure is called with AE_FMT_*_RAW as those only check AE_IS_RAW and then assume (!) a decodable PCM format.

So they report to engine: AE_FMT_FLOAT and engine needs to cope with AE_FMT_*_RAW - not sure that works correctly.

**Comment by FernetMenta** [comment]
This quick hack was rejected from being merged to master and as such it can't be backported. As @fritsch mentioned there are a couple of issues that can break things on other platforms.

**Comment by MartijnKaijser** [comment]
@FernetMenta ok so let's get those resolved to not touch the rest of the platforms. In remote case we could always have this living as separate branch from where we will build. I'll handle backporting fixes from normal Jarvis if needed. The not being able to backport was a known problem.

**Comment by koying** [comment]
@FernetMenta There was never a mention or intention to backport to master.
This is just a workaround for 16.

17 stays at is, and will benefit from the sink fixes done for this

**Comment by FernetMenta** [comment]
I meant it can't be backported to Jarvis because it was rejected on master.

**Comment by FernetMenta** [comment]
now that koying as left, I close it.

**Comment by fritsch** [comment]
Let's keep it open, please. Currently an internal discussion is going on on howto cope with such PRs that are against our current way of taking care of crossplatform code, features per platform and so on.

**Pull request closed without merging**
