### PR TITLE
CPUInfoLinux: Support cpu_thermal hwmon temperature module

### PR DESCRIPTION
**Pull request by popcornmix**
## Description
On most ARM platforms, including Raspberry Pi the hwmon is named cpu_thermal:
  LibreELEC:~ # cat /sys/class/hwmon/hwmon1/name
  cpu_thermal
  LibreELEC:~ # cat /sys/class/hwmon/hwmon1/temp1_input
  42450

Also support that name.

## Motivation and context
CPU temperature in system info display does not work on RPiOS

## How has this been tested?
LibreELEC build on Raspberry Pi 4, with there current workaround of using a cputempcommand disabled

## What is the effect on users?
Working CPU temperature display with kodi on other distributions

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by popcornmix** [comment]
See https://forum.kodi.tv/showthread.php?tid=374240

**Comment by graysky2** [comment]
@popcornmix - building your gbm_nexus branch with this PR, I get the CPU temp under `System info>Hardware` but I do not get the GPU temp under `System info>Video` ... is that expected?

**Comment by popcornmix** [comment]
Yes, we don't have a separate temperature sensor for the GPU.

**Comment by graysky2** [comment]
Would you consider adding to your PR the work-around LE is using to simply mirror the CPU temp?  It is linked in the forum thread.

**Comment by popcornmix** [comment]
No, that doesn't belong in kodi's tree.

It relies on an external script cputemp.
And the information is provides is not genuine (just a copy of cpu temperature).

Showing "GPU temperature: Not available" is the correct answer.

If a distribution wants to provide different information, they are free to do so with a custom command in advancedsettings.xml.

**Pull request merged**
