### PR TITLE
[Fix] VideoPlayer: Don't close any subtitle stream when switching audio tracks.

### PR DESCRIPTION
**Pull request by ace20022**
Reported by @koying some time ago. Does this fix it?

### CODE REVIEW

**Comment by ace20022** [comment]
@koying ping

**Comment by koying** [comment]
I'll test this WE. Thanks

**Comment by MartijnKaijser** [comment]
Ping :)

**Review by koying — APPROVED** [review]
Does fix the issue I reported.

That being said, iirc, just removing the "|| !GetSubtitleVisible()" did it for me, so I'll trust ace regarding the other changes ;)

**Comment by ace20022** [comment]
@koying thanks!

**Pull request merged**
