### PR TITLE
FIX: [audiotrack] proper detection of supported sample rates

### PR DESCRIPTION
**Pull request by koying**
/cc @anssih

### CODE REVIEW

**Comment by anssih** [comment]
Note that getMinBufferSize() doesn't (as of Android 5.1) actually check if the sample rate / channelconfig / encoding are actually supported by the HW, but it just checks if Android recognizes them as valid (so it will always succeed with 4..96kHz on 5.1, and probably other values on other Android versions).

However, since Android will just resample the audio anyway, I guess that check is enough for us (for sample rates anyway). So OK from me (though maybe the above caveat should be documented in the code).

I don't think, however, that this is a "fix", so I don't think it is eligible for merging during the current freeze (unless I'm missing something). I don't think it is a high-risk change, though, so if other people insist merging this now, I'm not going mind too much.

**Comment by koying** [comment]
Yeah, it's a workaround, but I don't see another way to at least give the devices a chance to provide us higher sample rates.

**Comment by MartijnKaijser** [comment]
since we have to delay next beta anyway (and need another one after that) i'm tempted to get this in.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
