### PR TITLE
[Krypton] libdvd: fix setting compiler when cross-compiling, backport 11185

### PR DESCRIPTION
**Pull request by bkuhls**
backport of https://github.com/xbmc/xbmc/pull/11185

### CODE REVIEW

**Comment by wsnipex** [comment]
I prefer backporting https://github.com/xbmc/xbmc/commit/e9d6d921e8adb37d3262b5640bcfa4800765d47b 
please test if this fixes your issue.

**Comment by bkuhls** [comment]
@wsnipex: Thanks, backporting 11185 also fixes the problem, I updated this PR accordingly.

**Review by wsnipex — APPROVED** [review]
thanks, ltgm

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
