### PR TITLE
addons: fix death spiral of recursion

### PR DESCRIPTION
**Pull request by FernetMenta**
fix crash on startup if load of addon fails. having status handler operate on the class instead of the object was wrong.

credits to @mapfau for tracking this down

@MartijnKaijser this may also cure the crash you observed on Android

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
will test

**Comment by MartijnKaijser** [comment]
Still closes Kodi on start.
#9759 reverted and this one on top and including both inputstream addons.

http://pastebin.com/xpxcp7EL

**Comment by FernetMenta** [comment]
ERROR: AddOnLog: ARGUS TV client: Ping failed... No connection to Argus TV.

please disable all PVR addons and try again. you can lease VNSI enable, for this I take responsibility :)

**Comment by MartijnKaijser** [comment]
There's no way to disable those as they are all default enabled on a fresh install. See my comment here https://github.com/xbmc/xbmc/pull/9706#issuecomment-217126520

I have already build it previously without **any** PVR addons and the result was exactly the same.

**Comment by FernetMenta** [comment]
looking into the log and taking into account the time it started to fail, my guess is this:
https://github.com/kodi-pvr/pvr.argustv/pull/51/files

that's why I always suggest to let unmaintained components die. argustv is one of those.

**Comment by FernetMenta** [comment]
> There's no way to disable those as they are all default enabled on a fresh install

who did change this. PVR addons and decoders MUST be disabled by default

**Comment by MartijnKaijser** [comment]
They are disabled by default if i do a fresh windows install but they are not on a fresh android install. No idea at what point that became borked. Installing a master build nothing crashes and although the PVR addons do complain Kodi keeps running

**Comment by FernetMenta** [comment]
@MartijnKaijser this should finally fix it

**Comment by MartijnKaijser** [comment]
rebuilding now including all binary addons

**Comment by MartijnKaijser** [comment]
new logcat
http://pastebin.com/amzzzE5c

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
Needs rebase

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by tamland** [comment]
Please don't use shared_from_this. Needing that is a major code smell making it even harder to get rid of the shared_ptr coupling in this code

**Comment by FernetMenta** [comment]
without shared_from_this we have to trash AddonStatusHandler. for this kind od async operation a shared pointer is required.

**Comment by tamland** [comment]
Well, shared_from_this requires an external shared_ptr to exist which tightly couple the implementations together with users of it. Any other use will result in a runtime exception. Which is why i think the whole `enable_shared_from_this` is clusterfuck and should be avoided. Using it in interfaces such as `IAddon` and `AddonDll` ties the entire interface to shared_ptr because one implementation requires it.

**Comment by FernetMenta** [comment]
I agree, it's ugly. I'll have a look into AddonStatusHandler, maybe it can solved differently.

**Pull request closed without merging**
