### PR TITLE
[GUI] Improve text rendering by adding support for GPOS

### LINKED ISSUE #17076: Wrong placment for the diacritical marks in the Arabic subtitles
### Describe the bug

The diacritical marks in the Arabic subtitles not in its correct placement above the letters, Kodi moves them one letter to the right. I'm using the Arial font that comes with Kodi.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The diacritical marks should be above the letters that are used with them

## Actual Behavior

Kodi moves them one letter to the right 

### To Reproduce

1. Play any video using Kodi with this Arabic subtitle that contains diacritical marks.
2. Play any video with the same Arabic subtitle in another media player like media player classic.
3. Compare the placement of the diacritical marks.

[Rick.and.Morty.S04E02.The.Old.Man.And.The.Seat.720p.AMZN.WEB-DL.DD+5.1.H.264-CtrlHD.zip](https://github.com/xbmc/xbmc/files/4000787/Rick.and.Morty.S04E02.The.Old.Man.And.The.Seat.720p.AMZN.WEB-DL.DD%2B5.1.H.264-CtrlHD.zip)

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

This how it looks

This how it should look

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: Kodi 19 Alpha (the same problem in Kodi 18.5)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by sammahafza**
## Description
This PR is an improvment on #19765 which was a harfbuzz support, but that PR doesn't support glyph positioning, thus it doesn't fully fix #17076 .

## Motivation and context
fixes #17076 and any language that needs glyph positioning to render text correctly.

## How has this been tested?
I build it and tested it on Windows 10 64-bit system using diffrent subtitles and fonts.

## What is the effect on users?
The PR adds support to complex script that uses GPOS tables in fonts like Arabic, Hebrew, Vitnamese, etc.

## Screenshots (if appropriate):
Fixes the diacritical marks in arabic (see red lines).

image 1
image 2

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [X] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
Thanks for the PR but why didn't you PR to the branch of the other PR? You are including their commits here which is a bit confusing.

We can either wait until the other PR is merged then you can rebase this, or you can work with the other author to include your changes in their PR.

**Comment by enen92** [comment]
Ping @naseef

**Comment by sammahafza** [comment]
sorry for disturbing, but i'm new to the git workflow as this is my first PR ever. I'll make PR on their repo.

**Comment by naseef** [comment]
@enen92 and @lrusak . How do you think this is to be incorporated, in my PR #19765 or as a new PR. My PR currently only handles glyph substitution and this PR handles glyph positioning ( not yet tested by me).

**Comment by sammahafza** [comment]
The code has been merged with the original branch. I will close this PR.

**Pull request closed without merging**
