### PR TITLE
skin: remove all use of hyphen as none value

### PR DESCRIPTION
**Pull request by tamland**
Follow-up on #10376. Appears to work fine..

### CODE REVIEW

**Comment by BigNoid** [comment]
Maybe nitpicking, but would be better to format like ```<texturenofocus />``` imo

**Comment by tamland** [comment]
Nothing against that, but too much work;) This is just a find and replace on `>-<`.

**Comment by ronie** [comment]
let's get it in and see if any issues pop up...

**Comment by ksooo** [comment]
I have noticed that now all parent folder list items have an "unread" overlay. Before, they had now overlay.

screenshot005

**Pull request merged**
