### PR TITLE
[python] removed long depricated xbmcgui.lock() and xbmcgui.unlock()

### PR DESCRIPTION
**Pull request by MartijnKaijser**

### CODE REVIEW

**Comment by jimfcarroll** [comment]
+1

**Comment by MartijnKaijser** [comment]
do you get some alert when some one touches that code? :P

**Comment by jimfcarroll** [comment]
Like Smaug, I've been waiting for years for someone to touch the Arkenstone ;-)

**Comment by xhaggi** [comment]
typo in commit message `deprecated`

**Comment by mkortstiege** [comment]
+1

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Comment by mkortstiege** [comment]
Build error is unrelated.

**Pull request merged**
