### PR TITLE
[cmake] FFMPEG fix cmake multiple generation failure after #21047

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Essentially, when cmake creates its list from PC_FFMPEG_STATIC_LDFLAGS and it contains
something like -framework OpenGL, on second+ runs of cmake regeneration, this list will be
passed through to set_target_properties for INTERFACE_LINK_LIBRARIES. This then will convert
the list (eg. -framework;OpenGL;) to (-framework;-lOpenGL). I believe this is due to
it expecting to have every entry with a - specifier (eg -l/-L-W, etc), and in the case
of the framework, as its not parsed as "-framework OpenGL" and instead splits it, we end
up with the bad list causing build failures for apple platforms.

Prior to #21047, the foreach loop for static libary search was not actually executed
because FFMPEG_LIBRARIES was empty, as it was set AFTER the foreach loop. in #21047 i
"fixed" this, by putting the set FFMPEG_LIBRARIES before the foreach, at which point the
loop actually did something now causing the list failure described above.

## Motivation and context
Was told about some failures from macos based devs (@ksooo @phunkyfish ), and i finally came across it myself for a second time, which allowed me to work out a repro case for it. The simplified case was running cmake generation twice. First run, the build succeeds, but on second, and subsequent, generations, it causes build failures with messages like 

```
Framework not found -lOpenGL
```

As i see it, we have a couple options to handle this. 

1. First, prior to #21047 the foreach was never actually executed. We can just simply remove the foreach loop and call it a day.
2. This PR, i dont believe its incorrect to run the foreach loop, as we can then define the IMPORTED target as STATIC correctly, however we just dont deal with the pkg-config returned LDFLAGS. This has no downsides from what i can see, all the correct flags are still already populated for my test cases (Android, Apple, Linux CI)
3. Correctly parse PC_FFMPEG_STATIC_LDFLAGS before setting FFMPEG_LDFLAGS. this would be extensive, and potentially error prone. this error is obvious with framework items, but there may be other flags that potentially have a similar fate, but no ones just stumbled across it. The short case would be to search for -framework and its following item, drop them concatenate into a single list item and move on. Im not sure the cmake code required is worth the effort.

Ive obviously gone with the second option, but let me know if theres a preference.

## How has this been tested?
Locally. can run cmake generation multiple times and still get the correct LDFLAGS

## What is the effect on users?
N/A

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
Jenkins build this please

**Review by ksooo — APPROVED** [review]
Thank you!

**Comment by ksooo** [comment]
@fuzzard tested, confirming working. Good job.

**Review by phunkyfish — APPROVED** [review]
👍

**Pull request merged**
