### PR TITLE
exit GIL when calling into GUI

### PR DESCRIPTION
**Pull request by FernetMenta**
GIL was never unlocked because the addon class clears tls

### CODE REVIEW

**Comment by FernetMenta** [comment]
@marcelveldt confirmed that this fixes deadlock issues he was observing with spotify addon.

**Comment by MartijnKaijser** [comment]
@FernetMenta not sure backporting this one is easy as i had a lot of conflict when i tried.

**Comment by FernetMenta** [comment]
@MartijnKaijser conflics are because of LOCKGUIIF, right? Resovling this should be straightforward. @marcelveldt wanted to backport this, iirc

**Comment by MartijnKaijser** [comment]
@marcelveldt could you please make a PR soon so we can get 17.4 RC out the door?

**Comment by marcelveldt** [comment]
@MartijnKaijser seems to be pretty straightforward indeed, I'll submit the PR later today.

**Comment by marcelveldt** [comment]
@MartijnKaijser @FernetMenta 
https://github.com/xbmc/xbmc/pull/12555

**Pull request merged**
