### PR TITLE
[backport][pvr][fix] users are trapped in the splash screen while start into a pvr window + no connection to backend

### PR DESCRIPTION
**Pull request by xhaggi**
backport of #7664

### CODE REVIEW

**Comment by xhaggi** [comment]
is blocked by #7693

**Comment by mkortstiege** [comment]
jenkins build this please

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by xhaggi** [comment]
jenkins build this please, again

**Comment by xhaggi** [comment]
jenkins build this please, again again

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
