### PR TITLE
AML: Fix AMLCodec video size on M8, M8B and M8M2

### PR DESCRIPTION
**Pull request by Stane1983**
This patch is not finished yet, zoom option does not work for now (it is always set to stretch).

Patch is based on parsing /sys/class/graphics/fb0/window_axis sysfs node on M8 devices to properly display video when using amcodec as HW accelerator.

Fix is tested as is on S802, S805 and S812 and works properly, except zoom option. On that I'm still working.

### CODE REVIEW

**Comment by koying** [comment]
@Stane1983 When complete, and assuming this is compatible with "old" SDK's, would you mind backporting a PR to Isengard, please.
What you found out might explain the numerous reports of the symptoms you describe, while we thought it was a plain permission issue.

When the 15 PR is done, I'll create a test build to get feedback.

Thanks

**Comment by Stane1983** [comment]
@koying Current state is compatible with old and new SDKs, tested on S812 with stock firmware from November last year. On that fw zoom works normally too, on new ones I can't still figure it out why it doesn't work. It works when I set it when using MoviePlayer (aml native player) but not in Kodi.

**Comment by koying** [comment]
Have you already tried removing https://github.com/xbmc/xbmc/blob/master/xbmc/android/activity/XBMCApp.cpp#L137 and https://github.com/xbmc/xbmc/blob/master/xbmc/android/activity/XBMCApp.cpp#L185 ?

Might be that those intents are still processed but buggy on newer SDK's?

**Comment by Stane1983** [comment]
Good tip, no :)

**Comment by koying** [comment]
@Stane1983 Am I wrong or amlGetWindowAxis() alway return the HDMI resolution?
If so, CDisplaySettings::Get().GetCurrentResolutionInfo().iScreenWidth/Height already has it, at least on android, due to using CEGLNativeTypeAmlAndroid.

Assuming this, what your changes do:
- you ignore /sys/class/ppmgr/ppscaler
- you ignore the dest rect set by Kodi (probably the source of your zoom issue)
- you force gui size = hdmi size rather gui = fb size, while current code base this decision on the ppscaler

**Comment by Stane1983** [comment]
@koying 
- amlGetWindowAxis().iWidth/iHeight represents real values of visible fb area including screen position setings in android options (eg. on 802 and 812 box, fb size is 1080p, but when on 720p, display area is 1280x720, while fb size remains 1920x1080)
- amlGetWindowAxis().iX/iY are X and Y values when screen position is set

therefore on 1920x1080:
screen width = amlGetWindowAxis().iWidth + amlGetWindowAxis().iX + 1 = 1920
screen height = amlGetWindowAxis().iHeight + amlGetWindowAxis().iY + 1 = 1080

- /sys/class/ppmgr/ppscaler returns disabled in all cases, does not matter which resolution is set, so check if ppscaler is enabled is not working (on newer SDK releases).

I figured that I have issues with dest_rect but as I said on forum, did not had time to work on this. Next week I will have some spare time to pay more attention to it.

Also, as I said, this solution works on all M8 SDK variants, except for zoom. Patch is also tested by sw engineer of one chinese company (no marketing :smile: ) who had exact same problem as me.

**Comment by koying** [comment]
@Stane1983 Yes, thats what CEGLNativeTypeAmlAndroid is doing, too ;)
For each RESOLUTION_INFO, iWidth/iHeight is the fb size, while iScreenWidth/iScreenHeight is the "hdmi" size.

amlGetWindowAxis() probably also take system calibration into account, but that's out-of-scope of this issue.

OTOH, I now notice that CEGLNativeTypeAmlAndroid::CheckCompatibility() is too restrictive (you only need RW on /sys/class/display/mode for framerate switching).
Could it be that you don't have RW on /sys/class/display/mode and thus that CEGLNativeTypeAmlAndroid is not used for you? If so, could you try by removing the RW check?

**Comment by Stane1983** [comment]
That's correct, I didn't have RW permissions to /sys/class/display/mode. I
added it now, but will test later and will post results.

**Comment by Stane1983** [comment]
It doesn't work - same behaviour. As I said, wrong display area calculation. Tested on S805 which does have fb set to 1280x720 and when display is 1080p, UI is upscaled to that resolution (fb size is always 1280x720) and video is sized 1280x720 in upper left corner.

values:
/sys/class/graphics/fb0/free_scale_axis -> 0 0 1279 719
/sys/class/video/axis -> 0 0 1919 1079
/sys/class/graphics/fb0/window_axis -> 0 0 1919 1079

**Comment by koying** [comment]
Really strange... Mind sharing the log of your test, please. Thanks

**Comment by Stane1983** [comment]
I was wrong. I modified sepolicy for /sys/class/display/mode, but it still wasn't rw (while all other sysfs nodes were, also selinux policy). Now retested after I manually changed mode to 666. After that Amlogic EGL worked w/o issues. Basically, when using Android egl issue exists. If Aml egl is used it works.

**Comment by koying** [comment]
Cool. I'll make a PR for adjusting the bogus request for RW in AML egl.
Thanks lot

**Comment by koying** [comment]
https://github.com/xbmc/xbmc/pull/7898

**Comment by MartijnKaijser** [comment]
thanks for looking into this. The other PR got merged so this can be closed

**Pull request closed without merging**
