### PR TITLE
[droid] lower obb package detection size as Kodi is getting smaller

### PR DESCRIPTION
**Pull request by MartijnKaijser**
/cc @koying

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Not sure this is the correct way however last nightlies Kodi dropped to 50mb APK size. If you now try to install it states "OBB file is missing"

**Comment by koying** [comment]
The fix is ok, although having an obb with a package < 50Mb doesn't make sense in the first place ;)

**Comment by MartijnKaijser** [comment]
True we don't need an OBB :)
However our nightlies don't compile OBB packages by default and it still was expecting the OBB on install. Maybe some other way of detecting that we actually need an OBB package?

**Comment by koying** [comment]
I probably forgot to PR the fix for that ;)
Will do...

**Comment by koying** [comment]
Superseded by #6727

**Pull request closed without merging**
