### PR TITLE
Rescrape season art when new season are added

### PR DESCRIPTION
**Pull request by jmarshallnz**
This adds a GetArt() function to the scraper, allowing to (re)fetch the art URLs for a particular item.  Currently supports tvshows, though it should work for movies well enough.  It's currently not ideal for shows, as it requires an additional XML fetch atm (banners.xml) as we don't have the language used for initial scrape when we re-fetch art.

Requires a unique ID to be set in the appropriate field in the video database.  Ideally anything else required to get a direct hit (e.g. language) would be added by scrapers initially.

This fixes a bug (season art not available for new seasons) as well as assisting to support in the future refetching of art URLs whenever the user goes to "Get Art" in the UI.  i.e. no need to store URLs that will almost certainly expire at some point: Instead we have an id that can be used to (re)generate new art.  Also means art doesn't become stale (scan when movie first comes out -> limited art, scan a year later -> more art).

ATM hooked up only for regenerating season art when we hit a season not previously discovered.  Will look at extending to make sure we have the framework in place at the scraper level to do what we want to in future.

Scraper devs, please comment on what else you might need to be able to pull this off properly, particularly for scraper sites outside the big two (tvdb, themoviedb).

### CODE REVIEW

**Comment by jester-xbmc** [comment]
And here is my comment:
There is a fix by MilhouseVH in its proper state, the issue has been open for 1.5 years, which btw has been tested and validated by many users (per the nightly builds of various makers) no issues with scrapers are found, so maybe MilhouseVH can do a re-base into a separate seasons art fix PR and this gets fixed for Helix 14.2 :)

**Comment by MartijnKaijser** [comment]
the fix was redone by @popcornmix iirc. I wont consider adding it to 14.2 before it is added to master branch

**Comment by jester-xbmc** [comment]
@popcornmix Can we kindly entice you to do a PR for this fix to master ? pretty please ? Thx for the heads up Martijn.

**Comment by popcornmix** [comment]
I could submit a version of this code rebased to current master (the commits are in my newclock4 branch).
However this is code I'm completely unfamiliar with, so if there are follow up questions or changes suggested, I won't be of much use.
If there is some consensus that it can be accepted as is, I'll PR it, but I wonder if there isn't someone else better qualified to "own it". @mkortstiege?

**Comment by Montellese** [comment]
I planned on taking a look at this once I'm done with all the other PRs I'm currently working on but those keep dragging on so I never got around to it.

**Comment by jester-xbmc** [comment]
So, if @popcornmix can do the PR, then @Montellese and/or @mkortstiege can be the "owner" for changes/questions.

**Comment by mkortstiege** [comment]
I'll pick the rebased commit from newclock4 to see what's missing (if any).

**Comment by popcornmix** [comment]
These are commits:
https://github.com/popcornmix/xbmc/compare/4895e05...popcornmix:a0c2d48

**Comment by Panocha** [comment]
Since they never fix bugs, and the user community has figured it out, is there a way I can patch mine to make it work?
This is very annoying, and I hate having to go through several terabytes of shows and update them one at a time.
I am using it on Ubuntu, so if I can modify or replace a file to get it to work, please let me know how.
thanks

**Comment by lrusak** [comment]
@Panocha Github is used for development discussion only, please take your questions to the forum.

**Comment by mkortstiege** [comment]
@Panocha all you need is there to fix the annoying issue you hate that much. Since we never fix bug I am sure you will also figure out how to apply patches and workaround your issue. Happy patching.

**Pull request closed without merging**
