### PR TITLE
[ESTUARY] Fix DD+ icon

### PR DESCRIPTION
**Pull request by Hitcher**
## Description

Change the eac3 audio codec to display 'DOLBY D+' instead of just 'DOLBY'
## Motivation and context

Reported on the forum: https://forum.kodi.tv/showthread.php?tid=378281&pid=3204867#pid3204867
## How has this been tested?

Tested locally.
## Screenshots (if appropriate):
Before:
screenshot00001

After:
screenshot00002

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by jurialmunkey — APPROVED** [review]

**Review by sarbes — CHANGES_REQUESTED** [review]
The grayscale channel contains black patches, which will lead to gray fringes. It will also prevent it to be stored as an alpha only texture.

And please, use a sensible resolution when re-engineering textures. This element renders at 115x52 on a 1080p screen. Compared to a properly sized texture, it requires more than five times the amount of resources on the GPU, while having worse visual quality, and possibly stalling the GPU. It also consumes more storage on disk and when distributing. It is even too large for 4k screens.

**Comment by Roardom** [comment]
I'm just a user, but it would be nice if the logo followed the official branding, so either `Dolby Digital Plus` (probably too long), or rather `DD+`.

Generally Dolby always spells it out fully, however in their specifications you will see they use the term `DD+` when it is abbreviated. See page 24 of the following for example: https://web.archive.org/web/20210925182332/https://developer.dolby.com/globalassets/professional/documents/smptetimecodedolbybitstreams.pdf

**Comment by Hitcher** [comment]
> The grayscale channel contains black patches, which will lead to gray fringes. It will also prevent it to be stored as an alpha only texture.
> 
> And please, use a sensible resolution when re-engineering textures. This element renders at 115x52 on a 1080p screen. Compared to a properly sized texture, it requires more than five times the amount of resources on the GPU, while having worse visual quality, and possibly stalling the GPU. It also consumes more storage on disk and when distributing. It is even too large for 4k screens.

All I did was edit the original texture - if there is a problem with it then all the other flags are wrong as well.

**Comment by Hitcher** [comment]
> I'm just a user, but it would be nice if the logo followed the official branding, so either `Dolby Digital Plus` (probably too long), or rather `DD+`.

I used the same formatting found here:

screenshot00003

**Comment by sarbes** [comment]
> All I did was edit the original texture - if there is a problem with it then all the other flags are wrong as well.
Yes, the flags have the wrong resolution. I don't expect you to change all of them, all I'm saying is that it would be highly preferable to adjust the resolution if we update them.

But still, the previous iteration had a uniformly colored surface (white), while your version premultiplies alpha to it.

**Comment by Roardom** [comment]
> > I'm just a user, but it would be nice if the logo followed the official branding, so either `Dolby Digital Plus` (probably too long), or rather `DD+`.
> 
> I used the same formatting found here:
> 
> screenshot00003

Since the image is being changed, can the correct logo be used? Considering the Dolby Vision logo in your screenshot is also inconsistent, it'd be better to do it correctly. Two wrongs don't make a right so to speak.

**Review by jjd-uk — APPROVED** [review]

**Comment by jjd-uk** [comment]
FYI I plan to completely remove all these specific codec flags in favour of a more flexible system.

**Comment by Hitcher** [comment]
> FYI I plan to completely remove all these specific codec flags in favour of a more flexible system.

OK, thanks for letting me know.

**Comment by jjd-uk** [comment]
> Since the image is being changed, can the correct logo be used? Considering the Dolby Vision logo in your screenshot is also inconsistent, it'd be better to do it correctly. Two wrongs don't make a right so to speak.

Official logo's in Estuary are a no go due to being the default skin hosted in the main code repo, so I'm not sure how that Dolby Vision one snuck in as it shouldn't have been allowed. As being the default skin we don't want to risk any copyright issues with using official logos, although we might be covered by fair use. If a copyright claim were to be made, it could result in Github being approached claimant to get the entire repo taken offline, so it's a risk we don't particularly want to take in this age of people engaging laywers for all sorts of frivolous claims.

**Comment by Roardom** [comment]
> > Since the image is being changed, can the correct logo be used? Considering the Dolby Vision logo in your screenshot is also inconsistent, it'd be better to do it correctly. Two wrongs don't make a right so to speak.
> 
> Official logo's in Estuary are a no go due to being the default skin hosted in the main code repo, so I'm not sure how that Dolby Vision one snuck in as it shouldn't have been allowed. As being the default skin we don't want to risk any copyright issues with using official logos, although we might be covered by fair use. If a copyright claim were to be made, it could result in Github being approached by the claimant to get the entire repo taken offline, so it's a risk we don't particularly want to take in this age of people engaging lawyers for all sorts of frivolous claims.

Logo was a poor choice of words on my part. I simply meant to show the text `DD+` rather than `Dolby D+`, since the former is the proper abbreviation for it while the latter was made up. For Dolby Vision, generally the abbreviation shown on AVR user interfaces and other official UIs use `DV`. However, some Dolby Vision specifications use the abbreviation `dovi`. I strongly agree that the official logo (i.e. the one shown here: https://en.wikipedia.org/wiki/Dolby_Digital_Plus#/media/File:Dolby-Digital-Plus.svg) or the double d should not be used to respect copyright/trademarks. However, there should be no issue labeling the media using a text description of the encoding format it's created with - you wouldn't be able to label the video as H.265 either otherwise.

**Comment by jjd-uk** [comment]
The new system I am working will move these flags to being populated by text strings within a skin xml file similar to this https://github.com/xbmc/xbmc/blob/master/addons/skin.estuary/xml/Variables.xml#L745-L780

The main motivation is to allow easy additions, but it also means they will become easily adjustable if what we include by default is not to your liking so you can change them whatever you want.

**Pull request closed without merging**
