### PR TITLE
[tools/depends] Python 3.8.5

### LINKED ISSUE #16560: feature_python3 - not compatible with Python 3.8
### Describe the bug
Here is a clear and concise description of what the problem is:

xbmc/interfaces/python/PythonInvoker.cpp

There are a three references in the file above to the private interfaces of PyInterpreterState.

Example:

    s = state->interp->tstate_head;

Python 3.8 has finally removed the public interfaces to PyInterpreterState. The C documentation has always stated that there were never any public interfaces but projects such as Kodi used them anyway.

Announcement:
https://mail.python.org/pipermail/python-dev/2019-February/156344.html

Bug tracker to request a public interface:
https://bugs.python.org/issue35886

## Possible Fix
Work with upstream to create a real public interface.

Workaround:

Adding the following to the top of PythonInvoker.cpp will expose the structs again.

    #if PY_VERSION_HEX >= 0x03080000
    # define Py_BUILD_CORE
    # undef HAVE_STD_ATOMIC
    /* for access to the fields of PyInterpreterState */
    #  include "internal/pycore_pystate.h"
    # undef Py_BUILD_CORE
    # define HAVE_STD_ATOMIC
    #endif

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.4 / 19.x

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Python patches updated for target platforms
native python updated to 3.8.5 to accomodate change in pgen
references to python3.7 updated to python3.8
updated pythonmodules builds to build against 3.8
Use official APIs for accessing interpreter list (PyInterpreterState_ThreadHead, PyThreadState_Next)

## Motivation and Context
Update python interpreter to latest release version for Apple/Android (linux ppa?), Windows (Thanks Paxxi)

## How Has This Been Tested?
runtime tested on osx.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Paxxi** [comment]
I'll try and get it done sometime in the coming week. There's some new modules and header files reorganization so build system needs an update but shouldn't be too bad

**Comment by fuzzard** [comment]
Thanks, greatly appreciated

**Comment by Paxxi** [comment]
@fuzzard pushed the packages now.

**Comment by fuzzard** [comment]
Thanks Paxxi. I'll try get Jenkins all green (having repeated issues around package (automake for iOS in particular) downloads in other PRs unfortunately). Then I'll kick off some test builds and make a call out for python Devs to test

Jenkins build this please

**Comment by fuzzard** [comment]
Testbuilds have been triggered and they will go into http://mirrors.kodi.tv/test-builds/ for winx64, win-uwp64, android arm7/8, osx. They should start appearing in the next hour or so and will have PR18240-merge in the name of the build. All binary addons are being built (ie inputstream will be available for android)

Any testing/feedback would be greatly appreciated.

**Comment by Paxxi** [comment]
Would be great if @Razzeee or @KarellenX could try these and see if they fix the datetime issue. I doubt it but one can always hope 😀

If anyone is curious, here's the windows patches https://github.com/Paxxi/cpython/tree/kodi/3.8

**Comment by Razzeee** [comment]
I'm actually not getting the issue so @KarellenX or @sarbes could test

**Comment by CastagnaIT** [comment]
I have tested NF add-on with relative dependencies with an installation from scratch
and seem works well as usual

**Comment by KarellenX** [comment]
@Paxxi 

I haven't had the issue for a while now, after Razzeee updated the scraper.

It was definitely TVDB Python scraper related.

**Comment by puenktchen** [comment]
I've got an error with the test build and the video addon (EmbyCon) i'm using. I know the addon isn't in the official repo anymore.
```
INFO <general>: initializing python engine.
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
               Error Type: <class 'ModuleNotFoundError'>
               Error Contents: No module named '_lsprof'
               Traceback (most recent call last):
                 File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.embycon/default.py", line 6, in <module>
                   from resources.lib.functions import main_entry_point
                 File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.embycon/resources/lib/functions.py", line 9, in <module>
                   import cProfile
                 File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/cProfile.py", line 9, in <module>
                   import _lsprof
               ModuleNotFoundError: No module named '_lsprof'
               -->End of Python script error report<--
INFO <general>: Python interpreter stopped
```
I can provide a debug log later if it's really needed.
Beside this little error, this pull request is a great addition and really needed for Android devices.
With Python 3.7 all is very slow on my Nvidia Shield. Addons and also Skins that rely on Python based script addons.
Until this pull request https://github.com/xbmc/xbmc/pull/18092 Matrix was completely unusable, but even after this it makes not really fun.
For example if i browse a library with the EmbyCon video addon, before that said pull request it was up to 4 times slower than Leia. With the current nightly it's still at least 2 times or more slower than Leia. But with this Python 3.8 build it's back to Leia speed.
So really great work @fuzzard!
Hope to see this get merged soon.

**Comment by fuzzard** [comment]
Thanks for the feedback.
I'll look into the lsprof module. At a glance, it should be being built for android, but i'll have a closer look.

**Comment by fuzzard** [comment]
Have added a commit for the _lsprof module. The default distibution setup file has changed a bit, and was no longer in it for 3.8. Not an issue to add, let me know if you come across any other modules.

Jenkins should have some android artifacts once built for the next 3 days if @puenktchen would like to do any further testing.

**Comment by puenktchen** [comment]
@fuzzard i think i've found the PR on Jenkins, but there's nothing to download. Was it already deleted by Jenkins?

**Comment by fuzzard** [comment]
Yeah, a PR build only gets stored for 3 days. I've got to rebase anyway, I'll get that done today/tomorrow when I get this other pillow PR fixup merged

**Comment by puenktchen** [comment]
I will hurry up next time but someone should check Jenkins' clock ;-) It was already gone 2 and a half day after the build process finished.
Thanks again for your afforts.

**Comment by fuzzard** [comment]
jenkins build this please

**Comment by fuzzard** [comment]
@puenktchen OSX build is available here currently https://jenkins.kodi.tv/job/OSX-64/19170/artifact/tools/darwin/packaging/osx/kodi-20200815-d1680bc3-PR18240-merge-x86_64.dmg

**Comment by CiNcH83** [comment]
This PR seems to cause an exception in the Backup add-on on Android:

```
2020-08-19 17:07:30.563 T:31293   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'splitattr' from 'urllib.request' (/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py)
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/service.py", line 1, in <module>
                                                       from resources.lib.scheduler import BackupScheduler
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/scheduler.py", line 8, in <module>
                                                       from resources.lib.backup import XbmcBackup
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 10, in <module>
                                                       from . vfs import XBMCFileSystem, DropboxFileSystem, ZipFileSystem
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/vfs.py", line 11, in <module>
                                                       from . authorizers import DropboxAuthorizer
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/authorizers.py", line 4, in <module>
                                                       import resources.lib.tinyurl as tinyurl
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/tinyurl.py", line 3, in <module>
                                                       from future.moves.urllib.request import urlopen
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.future/libs/future/moves/urllib/request.py", line 9, in <module>
                                                       from urllib.request import (getproxies,
                                                   ImportError: cannot import name 'splitattr' from 'urllib.request' (/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/urllib/request.py)
                                                   -->End of Python script error report<--
```

**Comment by CastagnaIT** [comment]
Has been moved under "parse" module and is deprecated
see: https://github.com/python/cpython/blob/3.8/Lib/urllib/parse.py#L1141

**Comment by phunkyfish** [comment]
This runs my setup ok on OSX.

**Review by lrusak — APPROVED** [review]

**Comment by lrusak** [comment]
Do we need more test builds or is this good to go?

**Comment by Maven85** [comment]
I've had this PR on my android private builds for over 2 weeks. I didn't see any problems.

**Comment by Paxxi** [comment]
Based on the comments I'd say this is good enough to merge to get the most possible time in alpha builds

**Comment by thexai** [comment]
Is this already working for Windows too?

Shouldn't "python-3.8.5" be up to date at https://github.com/xbmc/xbmc/blob/master/project/BuildDependencies/scripts/0_package.target-x64.list ???

**Comment by fuzzard** [comment]
Looks like it lost paxxis commit during a rebase.
Feel free to PR the changes, I believe Paxxi uploaded all the relevant binaries for windows platforms already

**Pull request merged**
