### PR TITLE
[WIP] Backport Videoplayer changes from kodi-agile

### PR DESCRIPTION
**Pull request by koying**
Attempt to backport VideoPlayer / ffmpeg changes from kodi-agile to master.

Status:
**22/02**: Initial dumb rebase from kodi-agile + removal of addons / dsp commits that should be subject of other PR's

### CODE REVIEW

**Comment by koying** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
I'd better do this myself. Makes no sense to keep the commits of my repo.

**Comment by FernetMenta** [comment]
@peak3d is working on Android and once he submitted this work I will factor out the first round of changes.

**Comment by peak3d** [comment]
@FernetMenta the only missing part for android is a special case (MultiChannel-Audio encrypted)
The general Android case should work as expected, so IMO there is no need to hold anything back because of this missing feature.

**Comment by FernetMenta** [comment]
ok, I will start work on this next weekend.

**Pull request closed without merging**
