### PR TITLE
[repos] add error handling for repo xml parsing and checksum/addons.xml fetching

### PR DESCRIPTION
**Pull request by tamland**
Should fix ticked #15744 (ping @MartijnKaijser) and various issues with repos getting stuck in a bad/empty state when repo metadata is unavailable.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
thx. will run some tests. 
i'll leave code review to others. maybe @mkortstiege as he knows maybe some of this code from way back

**Comment by MartijnKaijser** [comment]
seems to work fine during quick testing

**Comment by mkortstiege** [comment]
Looks good otherwise.

**Comment by tamland** [comment]
Thanks @mkortstiege. updated

**Comment by mkortstiege** [comment]
jenkins build this please

**Pull request merged**
