### PR TITLE
[seek] fix: reset seek size after seeking

### PR DESCRIPTION
**Pull request by xhaggi**
This fix the issue that if you use adaptive seek and then doing up/down bigstep seek, it shows the last used adaptive seek size instead of bigstep seek size.

@mkortstiege mind taking a look
@MartijnKaijser ping

### CODE REVIEW

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by mkortstiege** [comment]
Looks good to me. Thanks.

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by xhaggi** [comment]
OSX32 build error is unrelated. @MartijnKaijser your button.

**Pull request merged**
