### PR TITLE
[Windows] Fix: crash if WS-Discovery receives partial or malformed list of properties from network devices

### PR DESCRIPTION
**Pull request by thexai**
## Description
Backport of https://github.com/xbmc/xbmc/pull/19801 and https://github.com/xbmc/xbmc/pull/19660

The second is need because because WS-Discovery code on master branch is already patched to remove c++ warnings so in this way is same code master/Matrix now.

## What is the effect on users?
Fixes startup crash if WS-Discovery receives partial or malformed list of properties from network devices.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ksooo** [comment]
Why are you merging PRs without approval of at least one developer?

**Comment by ksooo** [comment]
> The second is need because because WS-Discovery code on master branch is already patched to remove c++ warnings so in this way is same code master/Matrix now.

 I thought we have rules and merging stuff for Matrix that does not fix anything just for convenience is imo wrong.

**Comment by thexai** [comment]
> Why are you merging PRs without approval of at least one developer?

And you why?  ==> https://github.com/xbmc/xbmc/pull/19806

**Comment by ksooo** [comment]
I had verbal approval from our former Android lead. Currently there is no active team member with the required Android should. This is different for three stuff you are working on !

**Comment by thexai** [comment]
I will not discuss anything with you

**Comment by ksooo** [comment]
I don't want to discuss, I ask you to obey our team rules.

**Comment by lrusak** [comment]
For backports I would advise you to leave the backport unmerged until the release manager either merges it themselves or says it's ok for you to merge. There is really no reason to merge backports ASAP as the next release may not be for a while yet.

**Comment by thexai** [comment]
> There is really no reason to merge backports ASAP

I disagree, in this case at least, for two reasons:

1) People were waiting for this fix in Matrix branch, especially after this post: https://forum.kodi.tv/showthread.php?tid=362788&pid=3039299#pid3039299

2) master branch is broken for Windows (or was it a few days ago).

I understand that there are rules and surely they are written somewhere but sometimes things are not black or white... it is very subjective what is a fix or an improvement or if a lack of functionality is an error. Or if we need to implement a new feature to fix an error. Or if a code refactor that not changes the behavior is an improvement? ....

**Comment by lrusak** [comment]
> I understand that there are rules and surely they are written somewhere but sometimes things are not black or white...

If you are unsure it's best left up to the release manager.

**Comment by phunkyfish** [comment]
The rules are quite clear. In order to merge a PR you need one approval if it’s from the maintainer or two if not. We all follow these rules even if it means having to wait quite some time to get something merged.

**Comment by thexai** [comment]
Same for the backports when equivalent PR in master branch is already approved?    (ping same person two times to review same code)

**Comment by phunkyfish** [comment]
> Same for the backports when equivalent PR in master branch is already approved? (ping same person two times to review same code)

Yes. Always

**Comment by thexai** [comment]
OK

**Comment by phunkyfish** [comment]
> OK

Thank you

**Pull request merged**
