### PR TITLE
[Windows][Xbox] Python improvements

### PR DESCRIPTION
**Pull request by thexai**
## Description
[Windows][Xbox] Python improvements

## Motivation and context
This is an attempt to fix recent Xbox Python issues (https://forum.kodi.tv/showthread.php?tid=369438).

The main difficulty is that the issue is only present in Retail mode (not in Developer mode) and tests are only possible in Developer mode then can't know for sure if it will fix the problem. In any case is a general improvement also for Windows desktop.

There are ~two~ one commits:

**Use API Py_SetPath instead of env var PYTHONPATH** 

This common for Windows and Xbox. Make use of `Py_SetPath` API as seems a better method to set Python path:

> Set the default module search path. If this function is called before [Py_Initialize()](https://docs.python.org/3/c-api/init.html#c.Py_Initialize), then [Py_GetPath()](https://docs.python.org/3/c-api/init.html#c.Py_GetPath) won’t attempt to compute a default search path but uses the one provided instead. This is useful if Python is embedded by an application that has full knowledge of the location of all modules.

https://docs.python.org/3/c-api/init.html#c.Py_SetPath

My hypothesis is that Xbox don't like Python try to access folders/paths that are not exists and this may cause slowdown.

Before:
```
debug <general>: CPythonInvoker(1): default python path:
debug <general>: CPythonInvoker(1):   C:\Program Files\Kodi\system\python\Lib
debug <general>: CPythonInvoker(1):   C:\Program Files\Kodi\python3.8.zip
debug <general>: CPythonInvoker(1):   C:\Program Files\Kodi\system\python\DLLs
debug <general>: CPythonInvoker(1):   C:\Program Files\Kodi
debug <general>: CPythonInvoker(1):   C:\Program Files\Kodi\system\python
debug <general>: CPythonInvoker(1):   C:\Program Files\Kodi\system\python\lib\site-packages
```

After:
```
debug <general>: CPythonInvoker(1): default python path:
debug <general>: CPythonInvoker(1):   C:\Program Files\Kodi\system\python\DLLs
debug <general>: CPythonInvoker(1):   C:\Program Files\Kodi\system\python\Lib
debug <general>: CPythonInvoker(1):   C:\Program Files\Kodi\system\python\Lib\site-packages
```

i.e  ~`C:\Program Files\Kodi\system\python\lib\site-packages` and~  `C:\Program Files\Kodi\python3.8.zip` does not exist and `C:\Program Files\Kodi\system\python` is empty (is mount point of `Lib` and `DLLs` but don't need to access it).

~**Setup environment variables from Python process**~

~This is Xbox only commit and is and is necessary to ensure that environment variables are visible to all processes. That is, setting an environment variable from Kodi.exe does not ensure that it will be visible in a child process launched from Kodi (as is Python) then the environment variables are set from Python itself. This is due security restrictions on UWP / Xbox only and does not affect Windows desktop. The same thing happened before here: https://github.com/xbmc/xbmc/pull/19973~

~All this may not be enough to fix the problems on Xbox. On a safer bet I would include:~

~- A backport of https://github.com/xbmc/xbmc/pull/21704~
- Bump Python version to 3.8.15 (it is the same branch as the current 3.8.5 but it includes much more than security fixes i.e. https://docs.python.org/release/3.8.14/whatsnew/changelog.html#id21)

In any case Windows cannot stay forever in Python 3.8.5

## How has this been tested?
Runtime tested Windows x64 and Xbox Series S (in Developer mode only)

## What is the effect on users?
Nothing

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by afedchin** [comment]
1. `lib\site-packages` must be there it's required for packages which may be included in default Kodi instalation.
2. UWP app cannot start any new process because it is restricted by UWP system. So the assumption that env vars isn't passed to child process is wrong by itself. seems there is an issue somewhere in python lib which causes loose of env for child **scripts**.  as I know the latest uwp runtime allows usage of `SetEnvironmentVariable` and `GetEnvironmentVariable` methods and need to check that Kodi and python lib are using the same approach to operate enviromnet variables. this is right and for SSL sert issue

**Comment by thexai** [comment]
> `lib\site-packages` must be there it's required for packages which may be included in default Kodi instalation.

on Xbox you can't add anything (there is only what includes msix intstaller) and currently there is no such folder. So if it doesn't exist (and can't be added) Python don't need to access it.

> seems there is an issue somewhere in python lib which causes loose of env for child scripts.

Call it what you want but currently this is the way to fix the problem. Environment variables set from kodi don't seem to have any effect for Python (SSL certs issue demonstrates it).

**Comment by afedchin** [comment]
> Call it what you want but currently this is the way to fix the problem. 

you don't fix the issue but hide it

**Comment by thexai** [comment]
You're right:  `Lib\site-packages` are needed. Tested with Netflix addon.

Updated

**Comment by thexai** [comment]
Finally Xbox fix is in Python code (bump Python to 3.8.15 + Kodi patches)
---> See https://github.com/thexai/cpython/commits/kodi/3.8

Even that, this still a general improvement: make use of Python API instead of use environment variables (that have always been problematic on Xbox).

Dropped second commit.

**Review by afedchin — APPROVED** [review]

**Pull request merged**
