### PR TITLE
Port dialog: Fix controller selection

### PR DESCRIPTION
**Pull request by garbear**
## Description

Somehow, merging https://github.com/xbmc/xbmc/pull/20505, logic got inverted and broke controller selection. Selecting any controller would disable the port, and it wasn't possible to re-enable. I traced the bug to a logic condition that was inverted. No idea how this happened or how it defeated testing.

## Motivation and context

Fixes bug left over in https://github.com/xbmc/xbmc/pull/20505

## How has this been tested?

Tested by selecting controllers. Multitaps properly expand for additional controllers:

Screenshot from 2022-01-07 14-47-56

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Review by fuzzard — APPROVED** [review]

**Comment by KOPRajs** [comment]
Great to see this one fixed! Is there a test build?

Please consider fixing the second bug as well. It should be trivial and possibly it could be fixed together with this one in one PR.

The bug is: After clicking the "Reset" button the port settings should be saved to the persistent XML. Currently it is not saved.

**Comment by garbear** [comment]
@KOPRajs I pushed a fix for the reset issue. Test builds will be up soon.

**Review by fuzzard — APPROVED** [review]

**Comment by garbear** [comment]
@KOPRajs test builds for ya: https://github.com/garbear/xbmc/releases/tag/retroplayer-19.3-20220110

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by KOPRajs** [comment]
Tested, everything seems good. Great work!

Now lets get all the great stuff (savestates, shaders, ...) from retroplayer branch to master ;-)

**Comment by garbear** [comment]
Sweet, let's get this baby in!

**Pull request merged**
