### PR TITLE
FIX: passthrough volume warning no longer showed (fixes #15925)

### PR DESCRIPTION
**Pull request by koying**
ping @fritsch

### CODE REVIEW

**Comment by fritsch** [comment]
Thx much. without that no "passthrough" indicator would have been shown in passthrough mode.

**Comment by uNiversaI** [comment]
> Thx much. without that no "passthrough" indicator would have been shown in passthrough mode.

@koying  And still doesn't, this did not fix it.

**Comment by fritsch** [comment]
Works for me.
Am 20.04.2015 00:22 schrieb "uNiversaI" <notifications@github.com>:

**Comment by fritsch** [comment]
@koying: https://github.com/koying/xbmc/blob/815e388a73b8e5ba121228d359eeb0bba1fee7f8/xbmc/Application.cpp#L2432 needs to go one down, directly in front of the return true;

I did not see the difference to my diff at first, but that way it's not handled as it's in the !passthrough block only.

**Pull request merged**
