### PR TITLE
[settings] Fixed CGUIControlButtonSetting::Update handling for CSettingAction

### PR DESCRIPTION
**Pull request by ksooo**
@Montellese you suggested to include this fix for Isengard. Here wo go...

### CODE REVIEW

**Comment by ksooo** [comment]
jenkins build this please

**Comment by Montellese** [comment]
Thanks. I just had another look and now I'm confused. Why does an action setting use label2? It doesn't even have a value so what is it supposed to display?

**Comment by ksooo** [comment]
The CSettingAction is assigned to a button, which has label and label 2.

https://github.com/ksooo/xbmc/commit/6cd10a0d80b3632570ac5adf701d8eef637504b8#diff-81ee6b50ffdcedb2e947a807469bf195R242
+
https://github.com/ksooo/xbmc/commit/6cd10a0d80b3632570ac5adf701d8eef637504b8#diff-81ee6b50ffdcedb2e947a807469bf195R396

**Comment by ksooo** [comment]
@Montellese Makes sense now?

**Comment by ksooo** [comment]
@Montellese Mind if I merge this?

**Comment by Montellese** [comment]
I'm not sure I understand. Do you use a `CSettingAction` to get access to a button control which then shows the value of another setting?

**Comment by ksooo** [comment]
I'm just using an existing member function of class CGUIDialogSettingsManualBase to add a button to a settings dialog container, no magic, no new stuff: 

https://github.com/xbmc/xbmc/blob/master/xbmc/settings/dialogs/GUIDialogSettingsManualBase.h#L74
=> CSettingAction* AddButton(CSettingGroup *group, const std::string &id, int label, int level, bool del...);

So, obviously, the code behind this combines a button (which has a label2) with a CSettingAction (by creating a CGUIControlButtonSetting). And the code that updates label2,

https://github.com/xbmc/xbmc/blob/master/xbmc/settings/windows/GUIControlSettings.cpp#L589

 just overwrote any existing label2 value with an empty string (strText initialized to "") in case control was of type "button" and neither setting type string nor control type slider. My fix changes this so the label2 gets not overwritten anymore by an empty string.

Long story, but hopefully understandable now?

**Comment by Montellese** [comment]
Yes I understood that much but those controls are not meant to be messed with outside of the settings system's logic exactly because they are automatically updated after specific events/actions.

That's why I'm asking what exactly you are trying to accomplish that you have to manually set label2.

**Comment by ksooo** [comment]
Oh hell! ;-) 

I just copied existing code from https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/dialogs/GUIDialogPVRTimerSettings.cpp#L298 and https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/dialogs/GUIDialogPVRTimerSettings.cpp#L158 and https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/dialogs/GUIDialogPVRTimerSettings.cpp#L438, thought the code was okay. Seems this is not the case, so I would appreciate a hint how to do this right. ;-)

**Comment by ksooo** [comment]
Ooops, forgot to write what I actually want to achieve.

I need a time selector for choosing start and end time of planned recordings. Time here is in format HH:MM from 00:00 to 23:59 (or whatever this is according to the user's locale) with steps of 1 min.

**Comment by ksooo** [comment]
Thought about all this a little more. You might be right that setting control label from outside is not intended and I will be happy to improve my code, but the fix I made hare is completely unrelated to this.

1. use AddButton, supply a label, never again touch it
2. Add a condition that shows/hides that setting according to some others settings value
3. If the condition gets re evaluated, due to value change of the controlling setting, Update() gets called for the "button" setting
4. Update() unconditionally overwrites label2 of the button with an empty string.

Point taken?

**Comment by Montellese** [comment]
A button representing a `CSettingAction` never has a label2 set unless the user manually sets it (for which it is not intended) because a `CSettingAction` doesn't have a value but only a label which is displayed as label and not label2.

**Comment by ksooo** [comment]
Okay. Understood. I was wrong re label2. Point taken.

What I'm missing in this discussion is the constructive part. Please, don't just say "this is wrong" and "that is not intended". I several times ask for your support on how to do it right. Got no reaction on this so far... :-(

**Comment by Montellese** [comment]
The main problem for me to give constructive feedback is that I never used the dialog so I have no idea what it should do. Back when I re-wrote all the settings dialogs I had to do the PVR ones blindly and it's a miracle that they are actually working.

I'm not sure in what format you want the value of the setting but either way you should use a `CSettingString` (if it should be `HH:MM`) or a `CSettingInt` (if it should be in minutes/seconds) and then use a "button" control with `format` set to `action` and `hidevalue` disabled. Then you can open whatever dialog you need in the `OnSettingAction()` and change the value of the setting after the dialog has been closed.
I'm not 100% but I don't think that this exact use case is already covered by `CSettingControlButton` and `CGUIControlButtonSetting` so it might require some changes in there to show the setting's value (similar to the one in this PR but not limited to `CSettingAction`) and to properly handle button activation (which is currently only forwarded to `OnSettingAction()` for `CSettingAction` settings).

**Comment by Montellese** [comment]
Actually thinking about this the cleanest approach of all would be to add a new `format` to either the `button` or the `edit` control which would support time values.
But obviously that's quite a bit more work (but might be useful in other places as well).

IMO if the current code already works this way right now I'm fine with this (as it's part of the GUI integration code and not the settings library itself) if it makes it easier for you.

**Comment by ksooo** [comment]
@Montellese Thanks so much for the constructive feedback. I'm with you that the best approach is to have support for time values in <code>button</code> or <code>edit</code> control and that would be useful in other places. But as you said this woul be more work (esp. as I have no deeper guilib/settings insights atm) and my code works just fine with the little fix done in this PR.

I will check whether your hints re >code>hidevalue</code> etc. can be used to improve things with little effort. If not, as you gave me your +1 for this PR, I will merge it as is tonight.

**Comment by Montellese** [comment]
In case you merge this as is please add a comment that it should not be needed anymore once all settings use a proper control & format combination.

**Pull request merged**
