### PR TITLE
[addons] fix control enable conditions

### PR DESCRIPTION
**Pull request by tamland**
Fixes some edge cases. See individual commits.

### CODE REVIEW

**Comment by tamland** [comment]
jenkins build this please

**Comment by fritsch** [comment]
@tamland http://sprunge.us/gUWZ <- does this target these edge cases?

**Comment by tamland** [comment]
No, this is just gui stuff. How did you manage to make that happen?:)

**Comment by tamland** [comment]
I think you somehow managed to make it disabled in the db..

**Pull request merged**
