### PR TITLE
[docs] add changelog tags for skinning

### PR DESCRIPTION
**Pull request by MartijnKaijser**
## Description
Start listing the changes done to the skinning engine. Currently it's WIP to get some feedback if this is the way to get changes listed.
Example: https://codedocs.xyz/MartijnKaijser/xbmc/skinning_v18.html

## Motivation and Context
Make it easier to keep track of changes

### CODE REVIEW

**Comment by enen92** [comment]
By the way, @MartijnKaijser could you please also reorder the links you introduced in https://github.com/xbmc/xbmc/pull/14521? People who read the documentation are interested in the top most recent versions first. It looks odd to have to visually scroll through the list of versions (from v12) to find what changed in v18 :) You can easily get what I mean by visiting https://codedocs.xyz/xbmc/xbmc/skinning_revisions.html .
List of versions should be something like:
```
- 
- Skinning engine v18
- Skinning engine v17
- Skinning engine v16
- Skinning engine v15
...
```
And not as it is right now. Natural eye movement follows a  "Z pattern" so the top most important links should come first.

**Comment by MartijnKaijser** [comment]
That's how Python was done as well (oldest -> newest). Also for skinning you need to go through all changes from lowest version to highest else you will be in in trouble. So it depends on how you look at it. Personally i don't care

**Comment by MartijnKaijser** [comment]
Added link to the wiki at top of the template saying they should read it first.
We can always expand the template if we see users can't handle it.

**Comment by garbear** [comment]
I wrote a comprehensive documentation and guide for games in v18: https://forum.kodi.tv/showthread.php?tid=336876

Can this be incorporated into the changelog?

**Comment by bridlepath224** [comment]
I'm trying to get this ongoing log,mem,andcpu off my screen. Also I would like to know why every movie I'm trying to watch has no stream  even the ones that I've already watched

**Comment by kib** [comment]
@bridlepath224 Please do not post unrelated comments to pull requests. The forum is for user questions - not the discussion part of code review. I have blocked you from participating in our repository on github for a period of 30 days because of this spam.

**Comment by phunkyfish** [comment]
@MartijnKaijser will be progressing this or should it be closed?

**Pull request closed without merging**
