### PR TITLE
Fix VAAPI post-processing of PAFF video

### PR DESCRIPTION
**Pull request by yol**
Fix PAFF video deinterlacing by not automatically switching the post-processor to the `NONE` method when an interlaced frame has been encountered before.

@yasij Please test

Commits for dead code removal and more useful error messages included but separate.

### CODE REVIEW

**Comment by yasij** [comment]
I tested with both iHD and i965. It's working well. Thanks.

**Review by fritsch — COMMENTED** [review]
Fine with me

**Review by fritsch — APPROVED** [review]

**Comment by pkerling** [comment]
@FernetMenta any comments before I merge?

**Comment by fritsch** [comment]
I am pushing now - as we all want to have feedback in upcoming 18.2-RC1. Bugs, design flaws can still be fixed.

**Pull request merged**
