### PR TITLE
Remove throw() specifications since they're not used anymore in C++11

### PR DESCRIPTION
**Pull request by Paxxi**
Get rid of about 1500 warnings on win32.

### CODE REVIEW

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by ace20022** [comment]
Nice, thanks!

**Comment by MartijnKaijser** [comment]
unrelated OSX64 failure.
jenkins build this please to be sure

**Comment by mkortstiege** [comment]
Awesome. Thanks for working on it. This will make new ones way easier to spot.

**Comment by Paxxi** [comment]
@Montellese and @opdenkamp can you check if it's causing any issues in your areas? You're the closest I think that's active in the addons/interfaces code.

**Comment by Montellese** [comment]
I looked into this as well and it looks like only VS/win32 doesn't properly interprete this? Or has this been dropped completely with C++11? I tried to do it with a platform-specific macro but that just resulted in other warnings. So this should be fine.

**Comment by Paxxi** [comment]
@montellese it got removed and replaced with noexcept to specify a function cannot throw.

**Pull request merged**
