### PR TITLE
[addons] add callback to check setting is default and improve setting call performance

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description

Commit 1:
------------------------------
**[addons] add callback to check setting is default**

This add the function "bool kodi::IsSettingDefault(const std::string& settingName)"
to check by addon that the current settings value is only the default and not
edited by used.

Commit 2:
------------------------------
**[addons] use HasSettings instead of ReloadSettings**

The "HasSettings" to confirm available and loaded by this call.
On other before was the whole xml loaded on every call where needed
more work and has produced also problems if a settings value was
asked by a loop on addon.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by ksooo — APPROVED** [review]
Looks good to me. Thanks.

**Comment by ksooo** [comment]
@phunkyfish would you as native English speaker name the new method `IsSettingDefault` or do you have a suggestion for another name?

**Comment by phunkyfish** [comment]
`IsSettingUsingDefault`

**Comment by ksooo** [comment]
I like that.

**Comment by AlwinEsch** [comment]
Is updated and with `IsSettingUsingDefaul` now.

**Review by phunkyfish — APPROVED** [review]
LGTM

**Pull request merged**
