### PR TITLE
ADD: Implement ZeroConf via Android API

### PR DESCRIPTION
**Pull request by koying**
Service Registration is functional and fixes current issues with mDNS.
Deprecates mDNSresponder.
Service Discovery is WIP

All-in-all, not perfect but better than nothing.

TODO:
1) Discover API only allows a limited number of instances/Services: To be mitigated
2) Bug in API < N where TXT records are unavailable (https://code.google.com/p/android/issues/detail?id=136099)

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
isn't mdnsresponder makefile still used on other platforms?

**Comment by koying** [comment]
No. mdnsresponder was android-only, so can be removed after this PR

**Comment by MartijnKaijser** [comment]
Tested and works

**Comment by MartijnKaijser** [comment]
Jenkins build this please

**Review by MartijnKaijser — APPROVED** [review]

**Comment by MartijnKaijser** [comment]
No objections?

**Comment by wsnipex** [comment]
no objection from me, but I'm not in a position to properly review this.

**Pull request merged**
