### PR TITLE
[xbmc][cvariant] Rework the move constructor a bit to make it safe and proper. Not run…

### PR DESCRIPTION
**Pull request by Paxxi**
…time tested yet because of other issue.
 maybe hold off on this until we can test it properly?

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Excellent - this seems to have fixed the segfault-at-startup issue with Ubuntu... now just need a fix for #7359 and we might have a working system again! :)

**Comment by fritsch** [comment]
jenkins build this please

**Comment by MilhouseVH** [comment]
I've tested this on a Pi2 (OpenELEC) and Ubuntu x64, both with #7359 reverted, and I've not found any other problems so far (played a couple each of movies, tvshows and songs from the respective MySQL libraries).

**Comment by fritsch** [comment]
@Paxxi You are happy with that fix or want to add something else?

**Comment by Paxxi** [comment]
Thanks for testing @MilhouseVH . This is my planned fix @fritsch and how it should've been from the start

**Comment by uNiversaI** [comment]
> Excellent - this seems to have fixed the segfault-at-startup issue with Ubuntu... now just need a fix for #7359 and we might have a working system again! :)

Excellent 1 down one to go.... #7359 is still a problem so Ill create a revert manually to compile ontop of this master so I can test this without risking a unusable system.

**Pull request merged**
