### PR TITLE
WIP - [confluence][core] add DefaultBluray icon [Split from #6829]

### PR DESCRIPTION
**Pull request by un1versal**
Split from #6829
### THIS WILL NOT WORK AS IS, ACE2002 SAID HE WILL TAKE THIS AND DO WHATEVER ELSE TO IT

@ace2002 [said it](https://github.com/xbmc/xbmc/pull/6829#issuecomment-92444280) and I agree this portion needs more time and more expertise.

The idea here is  when you insert a Bluray disk in the optical drive and disk gets mounted (irrespective if you can play it or not due to protection) A Bluray icon will show instead of the gastly DefaultFolder or some other irrelevant icon.

Also who knows, one day Bluray disks can be played like current DVDs can in Linux (vlc already can)

This could be extended at some stage to other Bluray types, I can provide icons for it easily (if Im still alive and able), e.g. For Bluray iso files or Folders.

Just needs the code to load such files.

@ace2002 was looking into this and was decided to split.

### CODE REVIEW

**Comment by Jalle19** [comment]
Looks reasonable, any objections?

**Comment by mkortstiege** [comment]
No objections.

**Comment by ace20022** [comment]
As I said it does not work, I'll pr against that branch in the future.

**Comment by uNiversaI** [comment]
@mkortstiege yes wont work as is, hence it was split, this is here for ace2002

@ace20022 
Thanks let me know when you want me to rebase that against master, else I'll have issues dealing with any possible conflicts.

:+1:

**Comment by MartijnKaijser** [comment]
@ronie was this ok for you?

**Comment by ronie** [comment]
yup.

**Comment by uNiversaI** [comment]
Again this doesnt work yet, @ace20022 was going to look into it.

**Comment by un1versal** [comment]
@ace20022 Ill leave this open for you, but I wont be doing anything else here. you're welcome to pick it or redo it or close it whenever you have time to do this or whatever.

**Comment by ace20022** [comment]
Okay, thx, I'll take it over.

**Comment by MartijnKaijser** [comment]
Let me close it for now. New PR can be opened if wanted/needed and is rebased on current master branch.

**Pull request closed without merging**
