### PR TITLE
[depends] sqlite 3140200

### PR DESCRIPTION
**Pull request by MartijnKaijser**
## Motivation and Context

keep it updated
## How Has This Been Tested?

runtime

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
We seem keep shipping two patches. Does it make sense that some one tries to send these upstream?

**Comment by Paxxi** [comment]
Are the patches even needed?

**Comment by MartijnKaijser** [comment]
@koying added one of them. The other is from  @bavison

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
