### PR TITLE
gfx: fix toggle fullscreen when playing video

### PR DESCRIPTION
**Pull request by FernetMenta**
@afedchin does this fix the issue?

### CODE REVIEW

**Comment by afedchin** [comment]
@fernetmenta will check today later

**Comment by afedchin** [comment]
@FernetMenta I can confirm this fixes issue.

**Comment by FernetMenta** [comment]
@afedchin thanks!
jenkins build this please

**Comment by FernetMenta** [comment]
ios build error unrelated

**Pull request merged**
