### PR TITLE
[jenkins] - ensure to export DEVELOPER_DIR to override used Xcode version

### PR DESCRIPTION
**Pull request by Memphiz**
fixes binary addon build - credits to Rechi for this one.

Fixes regression introduced in #16218

Once this is in we can remove the DEVELOPER_DIR=init in the jenkins jobs for kodi ios/tvos/macos ...

### CODE REVIEW

**Comment by Memphiz** [comment]
@ksooo fyi

**Comment by ksooo** [comment]
Thanks.

**Review by Rechi — APPROVED** [review]

**Comment by Memphiz** [comment]
Will adapt the jenkins jobs now

**Comment by Memphiz** [comment]
Done

**Pull request merged**
