### PR TITLE
CMake: fixes dependencies of iso9660++

### PR DESCRIPTION
**Pull request by Karlson2k**
`libiso9660++` requires `libiso9660` and `libcdio` binaries.
Currently `libcdio` is added by separate `FindCdio' CMake module after `FindIso9660pp` module and the combination works fine, but if order of included CMake modules is touched or CMake files are changed in some other way, linker will fail.

This PR fixes fragile CMake combination and added required binaries in the correct order, so CMake configuration becomes stable.

### CODE REVIEW

**Review by afedchin — APPROVED** [review]

**Review by wsnipex — CHANGES_REQUESTED** [review]
instead of repeating myself: https://github.com/xbmc/xbmc/pull/19230#issuecomment-779207383

**Comment by DaveTBlake** [comment]
@Karlson2k @wsnipex thank you both for re-engaging with this,  I remain hopeful a consensus can be reached. Patience all round please.

**Comment by yol** [comment]
Thank you @Karlson2k for reopening the PR with minimal changes only, which should ease the review and discussion. However, I do not like that you did not invite @wsnipex for review. I don't want to assume whether that was intentional or not, but let me be clear that @wsnipex is a major contributor to the CMake-based build system with a lot of knowledge and expertise in this area and this discussion will not happen without him.

I know that the situation is quite heated and a lot has happened already, but I would like both sides to consider whether showing their interest in an amicable solution wouldn't also be in their own best interest. @wsnipex Since the changes are minimal and, as far as I am aware, there is no disagreement that they fix one particular problem, maybe you could reconsider your position regarding this PR only, for now? I am aware there is still a lot of work ahead of us...

**Comment by Karlson2k** [comment]
> Thank you @Karlson2k for reopening the PR with minimal changes only, which should ease the review and discussion. However, I do not like that you did not invite @wsnipex for review. I don't want to assume whether that was intentional or not, but let me be clear that @wsnipex is a major contributor to the CMake-based build system with a lot of knowledge and expertise in this area and this discussion will not happen without him.

@yol It was intentional, but in positive way. First of all, wsnipex asked me to not ping him anymore. Secondly, it was the way to give others options to "just ignore" instead of publicly change position.

**Comment by Karlson2k** [comment]
> instead of repeating myself: [#19230 (comment)](https://github.com/xbmc/xbmc/pull/19230#issuecomment-779207383)

I could write, that instead of repeating my self, I would better to refer my existing comments, which are left without any response:
https://github.com/xbmc/xbmc/pull/19230#issuecomment-779212450, https://github.com/xbmc/xbmc/pull/19230#issuecomment-779234807, https://github.com/xbmc/xbmc/pull/19230#issuecomment-783173881, https://github.com/xbmc/xbmc/pull/19234#issuecomment-779183806, https://github.com/xbmc/xbmc/pull/19234#issuecomment-784020469, but I will not do like this.

Instead, to simplify the discussion, I'd like to understand your position about the next questions:
1. Does `FindIso9660pp` CMake module require fixing of lib binaries order?
2. Does this PR fixes `libiso9660++` order of binaries?
3. Does this PR introduce any regression or cause any harm?

I do hope that we can find the way how to move forward with a such minor fix.

**Comment by wsnipex** [comment]
instead of arguing over the same things again, let me propose https://github.com/wsnipex/xbmc/commit/19ce30fb194bbf0eb1c7bf9ef2eec66208e0f1c6 on top of this PR.
This fixes the missing bits by properly checking for and requiring cdio++ headers when iso9660pp support was _not disabled_.
It should still allow building with cdio (non ++) only when iso9660pp is disabled. although I didn't test that.

**Comment by Karlson2k** [comment]
@wsnipex Thanks for your proposal, it really gives ability to build Kodi without `cdio++`. I was warried about losing this ability.
I'll integrate your commit with some additional changes/enhancements for you review.

**Comment by Karlson2k** [comment]
@wsnipex, I've integrated your commit.
The purpose of additional commits:
1. First `#include` in `cdio++` headers is standard `cdio` headers (without `.hpp`), so let's add libcdio includes directory as well. Actually this commit can be excluded for now, as currently `cdio` is mandatory, but if something is changed it would be simpler to maintain.
2. Try to match version even harder and warn user about version mismatch. Version variable is optional for `find_package_handle_standard_args`, with this change `libcdio++` will not be used if version is different.
3. If only old libcdio library is present (like version 1.0 or 2.0), but no `libcdio++` is present, `libcdio` still can be used. If `libcdio++` is present, require minimal version 2.1 and don't use anything older. Works with previous commit.

Please check the additions. I hope you will find them useful.

**Review by wsnipex — APPROVED** [review]
works for me

**Comment by Karlson2k** [comment]
Superb, thanks!

**Comment by Karlson2k** [comment]
Jenkins build this please

**Comment by DaveTBlake** [comment]
Thank you for making progress with this :) 
Possibly worth squashing the commits before merge, looks simple enough in the end to be one commit (unless there is a good reason to keep them or some subset, of course).

**Comment by Karlson2k** [comment]
@DaveTBlake, I'll squash into three commits to keep contribution from two authors.

**Comment by wsnipex** [comment]
you can also squash into 1 commit, no problem

**Comment by DaveTBlake** [comment]
You get to create the backport PR against Matrix now @Karlson2k

**Pull request merged**
