### PR TITLE
VideoPlayer: Reset stale stream times after a flush

### LINKED ISSUE #24745: Seeking can stall for a long time
### Describe the bug

This has been present in VideoPlayer for a long time.

The problem is no video/audio playback after some seeks.
Symptom is no video updates, and elapsed time just continuing.
If you wait a long time (minutes) then playback may resume.
Seeking again may be more successful.

It affects seeking on certain streams. For me these are typically online streams. Youtube is a good example.
Some seeks are instant. Others take a number of seconds. Occasionally the stall may be minutes.

## Expected Behavior
After seek video should start playing promptly. 

## Actual Behavior
Video can stall for seconds or minutes afer a seek

### To Reproduce

Play a youtube stream. Seek around.
Many seeks are instant. Some take a number of seconds. Occasionally several minutes.

### Debuglog

The debuglog can be found here:

Start of log:
http://sprunge.us/83UTAF

log where failure occurs:
http://sprunge.us/mRus3Y

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 21.0-BETA2

### PR DESCRIPTION
**Pull request by popcornmix**
## Description

The stale starttime can be used and cause a long video stall. 
Reset it, as its no longer valid.

## Motivation and context

See: https://github.com/xbmc/xbmc/issues/24745

## How has this been tested?

Pi4 and seeked a youtube video

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by FernetMenta** [comment]
I though I commented on this already. Only touch the sync case or it will break other scenarios.

**Comment by popcornmix** [comment]
Updated

**Comment by FernetMenta** [comment]
> so not subs?

I don't think starttime is used for subs, is it? IMO setting it would just imply the opposite. The classes could have a better hierachy with members only for the objects which use them. But there are many things in Kondi, which are not ideal.

Regarding lastdts. I am just saying that I don't remember the code good enough to know for sure that resetting it here won't cause any negative impact. If you are sure, go ahead.

**Comment by popcornmix** [comment]
I agree, starttime is not used for subs.

I've removed all but the necessary changes for the bug fix to minimise risks.

**Comment by popcornmix** [comment]
We've got a thumbs up from @FernetMenta 
Any objections to merging? Okay for milestone of Omega?

**Comment by ksooo** [comment]
@popcornmix next time please merge only if checks are green:

image

**Pull request merged**
