### PR TITLE
Blacklist problematic Sony TV remote

### PR DESCRIPTION
**Pull request by garbear**
See discussion: http://forum.kodi.tv/showthread.php?tid=298891

Alternative to #11065 to avoid introducing a setting.

## Screenshots (if appropriate):
Before fix:
Device removed
New device configured

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by garbear** [comment]
untested - @Montellese does this look right?

**Comment by MartijnKaijser** [comment]
maybe some other way to extend the blacklist in case there will be more like these in the future?

**Comment by NedScott** [comment]
There will be an endless and nearly impossible to maintain list when you consider all of the possible input devices this could include. I can already reproduce the issue with a generic bluetooth mouse. IMO, if you have to choose between maintaining a a blacklist and adding a setting, go with the setting.

**Comment by CiNcH83** [comment]
I support what @NedScott just wrote. I also have a Rapoo wireless keyboard which I connect to may Android TV from time to time for better debugging, and it also often gives me the connect/disconnect messages.

**Comment by MartijnKaijser** [comment]
I guess we close this one as specifying single remotes won't work

**Pull request closed without merging**
