### PR TITLE
[guilib] Resolution::FindClosestResolution: don't switch between scre…

### PR DESCRIPTION
**Pull request by afedchin**
…ens.

In some cases FindClosestResolution may select resolution on different display.

@FernetMenta @fritsch ping

### CODE REVIEW

**Comment by FernetMenta** [comment]
Ok. You could also consider to eliminate the screen parameter and load only resolutions for the monitor in use. This way it is done on X11. When Kodi is moved to a different monitor you get an event anyway and can load those resolutions.

**Comment by fritsch** [comment]
@afedchin thx much.

**Comment by afedchin** [comment]
@FernetMenta it will be a sub-task for future WinSystemWin32 re-work

**Comment by FernetMenta** [comment]
ok, thanks

**Pull request merged**
