### PR TITLE
ffmpeg: thread specific logging level

### PR DESCRIPTION
**Pull request by FernetMenta**
this reduces lot of ffmpeg logspam

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by afedchin** [comment]
@FernetMenta this makes ffmpeg log spamming if debugging log is enabled even if ffmpeg logging is disabled.
perhaps the following code makes more sense
```c
  if ((level > AV_LOG_WARNING &&
     !g_advancedSettings.CanLogComponent(LOGFFMPEG)) ||
     CFFmpegLog::GetLogLevel() < 0)
    return;
```

**Comment by FernetMenta** [comment]
With you code other threads won't be able to enable any logging beyond WARNING because only VideoPlayer has CFFmpegLog::GetLogLevel() > 0
What ffmpeg logs do you consider spam?

**Comment by afedchin** [comment]
I have a video file which causes a huge amount of ffmpeg messages like the following
```
Debug Print: ffmpeg[4BA0]: [mov,mp4,m4a,3gp,3g2,mj2] count=1, duration=0
Debug Print: ffmpeg[4BA0]: [mov,mp4,m4a,3gp,3g2,mj2] count=1, duration=5005
Debug Print: ffmpeg[4BA0]: [mov,mp4,m4a,3gp,3g2,mj2] count=1, duration=2002
```
in that case Kodi is unable to play it bacuse spends all cpu time for logging.

**Comment by afedchin** [comment]
level of this messages is AV_LOG_TRACE

**Comment by FernetMenta** [comment]
ahh, I see what's wrong now.. I will submit a fix.

**Comment by afedchin** [comment]
thanks a lot

**Pull request merged**
