### PR TITLE
[OSX] - fix videosync by making graphicsContext the only source of truth

### PR DESCRIPTION
**Pull request by Memphiz**
Easy version of #6455 as backport for helix

thx @jingai for figuring it out.

This is not yet build and runtime tested - i kicked a jenkins build and hope @jingai can test once its done (will post the link here then).

### CODE REVIEW

**Comment by jingai** [comment]
I'll check your build when it's done, but I've already tested these back-ported to Helix.

**Comment by Memphiz** [comment]
ok great :) thx - really cool to have an osx dev around finally :)

**Comment by MartijnKaijser** [comment]
Merge when ready :)

**Comment by Memphiz** [comment]
@jingai http://mirrors.xbmc.org/test-builds/osx/x86_64/kodi-20150215-dff9b3c-fixvideosyncbp-x86_64.dmg

**Comment by jingai** [comment]
Working here.  Good to go IMHO :)

**Comment by Memphiz** [comment]
just waiting on the ios compilation here http://jenkins.kodi.tv/job/IOS-ATV2-Helix/3/ - will merge when its fine

**Pull request merged**
