### PR TITLE
fixed: used av_free when av_freep was intended in f5f9b8d and aadfc21d

### PR DESCRIPTION
**Pull request by notspiff**
proxying for @fritsch

### CODE REVIEW

**Comment by notspiff** [comment]
hold al ittle i'm seeing issues again

**Comment by hudokkow** [comment]
Ping when ready!

**Comment by fritsch** [comment]
Thx much. Please plain revert the Pic commit,please. These buffers are freed elsewhere. Need to track down when back.

Thanks again for helping out.

**Comment by notspiff** [comment]
there we go.

**Comment by hudokkow** [comment]
@fritsch, which is it? plain revert or spiff's work?

**Comment by hudokkow** [comment]
Okido. Thx spiff.
jenkins build and merge

**Comment by phate89** [comment]
we found that this image crashes kodi after your and fritsch prs
ocvgljcyqmav5djymnrwnthvj2m

**Comment by fritsch** [comment]
Will fix after I am back. Btw does add a 1px border to the right fix it?

Am 06.11.2016 5:14 nachm. schrieb "phate89" <notifications@github.com>:

**Comment by phate89** [comment]
yes works with resolution
256x255
1969x2349

but crashes with
1968x2349

**Comment by fritsch** [comment]
You sure the last two are right?

I'd say 1968 works but 1969 (original image) not. Right?

Am 08.11.2016 1:14 nachm. schrieb "phate89" <notifications@github.com>:

**Comment by phate89** [comment]
No the original image is 1968 and crashes..you asked to add a pixel to the right and it works (1969)

**Pull request merged**
