### PR TITLE
[cleanup] remove ifdefs for old lib, os & compiler versions

### PR DESCRIPTION
**Pull request by Rechi**
## Motivation and Context
No need to keep ifdefs around, where it is questionable if other parts of the code work with such old versions.

## How Has This Been Tested?
compiled for Windows and Linux

## Types of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Review by wsnipex — APPROVED** [review]
nice housekeeping :)

**Comment by Rechi** [comment]
OSX-64 test suite failure is unrelated

**Comment by wsnipex** [comment]
sadly this broke ubuntu 16.04:
>/<<BUILDDIR>>/kodi-18.0+git20180228.0202-a705857/xbmc/music/tags/MusicInfoTagLoaderCDDA.cpp: In member function ‘virtual bool MUSIC_INFO::CMusicInfoTagLoaderCDDA::Load(const string&, MUSIC_INFO::CMusicInfoTag&, EmbeddedArt*)’:
/<<BUILDDIR>>/kodi-18.0+git20180228.0202-a705857/xbmc/music/tags/MusicInfoTagLoaderCDDA.cpp:116:40: error: ‘CDTEXT_FIELD_TITLE’ was not declared in this scope
       std::string strTitle = ti.cdtext[CDTEXT_FIELD_TITLE];
                                        ^
/<<BUILDDIR>>/kodi-18.0+git20180228.0202-a705857/xbmc/music/tags/MusicInfoTagLoaderCDDA.cpp:129:43: error: ‘CDTEXT_FIELD_PERFORMER’ was not declared in this scope
         std::string strArtist = ti.cdtext[CDTEXT_FIELD_PERFORMER];
                                           ^
/<<BUILDDIR>>/kodi-18.0+git20180228.0202-a705857/xbmc/music/tags/MusicInfoTagLoaderCDDA.cpp:140:42: error: ‘CDTEXT_FIELD_GENRE’ was not declared in this scope
         std::string strGenre = ti.cdtext[CDTEXT_FIELD_GENRE];
                                          ^
build/music/tags/CMakeFiles/music_tags.dir/build.make:89: recipe for target 'build/music/tags/CMakeFiles/music_tags.dir/MusicInfoTagLoaderCDDA.cpp.o' failed
make[4]: *** [build/music/tags/CMakeFiles/music_tags.dir/MusicInfoTagLoaderCDDA.cpp.o] Error 1

libcdio13 amd64 0.83-4.2ubuntu1

**Comment by Rechi** [comment]
stupid me mixing strictly greater and greater equal

**Pull request merged**
