### PR TITLE
[Estuary] Fix player controls

### LINKED ISSUE #24514: Changing of player controls when pausing a video is counterintuitive
### Describe the bug
Here is a clear and concise description of what the problem is:

**Player controls change when pausing a video:** 
Due to hiding the _rewind_ and _forward_ buttons, the _stop_ button moves to the position where the _pause_ button was at before pausing. This is really counterintuitive, especially when using mouse or touch input, as clicking/touching the _same spot_ now **stops** the video instead of resuming it.

If there is a configuration option that changes this behavior, please let me know - I could not find any.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Either the _rewind_ and _forward_ buttons should stay visible when pausing a video or they should be 'greyed out', i.e. made unusable. Personally, I'd prefer if they simply stayed visible, I don't see any reason to hide them.

## Actual Behavior

See 'Describe the bug'.

## Possible Fix

See 'Expected behavior'.

### To Reproduce

1. Start playback of a video
2. Pause the video
3. Notice player controls changing

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

Video playing:
kodi_1

Video paused:
kodi_2

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by Hitcher**
## Description

Changes the `visible` conditions to `enable` conditions so as to keep all the buttons in the same positions to ease the use of mouse and touch controls.
## Motivation and context

Currently when pausing video or music the button positions in the OSD change making mouse/touch controls awkward.
Fixes issue https://github.com/xbmc/xbmc/issues/24514
## How has this been tested?

Tested locally.
## What is the effect on users?

OSD buttons keep their positions and unusable buttons simply get disabled instead of hidden.
## Screenshots (if appropriate):

Video OSD - playing
screenshot00000

Video OSD - paused
screenshot00001

Video OSD - paused with fix
screenshot00002

Music OSD - playing
screenshot00003

Music OSD - paused
screenshot00004

Music OSD - paused with fix
screenshot00005

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by jjd-uk — APPROVED** [review]
Think I introduced some of those Visible conditions so buttons that wouldn't do anything would not be shown. But this makes sense to make them enable conditions rather than visable, so they are still shown but disabled.

**Review by DaveTBlake — APPROVED** [review]
Makes good UI sense, thanks Hitcher

**Comment by jurialmunkey** [comment]
Why are the buttons disabled? And how do you enable them?

If these two questions aren't obvious to the user, it's widely considered to be a ux design anti-pattern to have disabled buttons.

https://uxdworld.com/2024/01/29/disabled-buttons-ux/
https://www.smashingmagazine.com/2021/08/frustrating-design-patterns-disabled-buttons/

IMHO The bigger question to ask is why are the FF/RW buttons hidden at all when paused in the first place? Why is the user not allowed to use those buttons from a paused state?

**Comment by jurialmunkey** [comment]
To me a better fix is to leave visibility conditions intact but remove the `!Player.Paused` on FF/RW

Then you can solve the FF/RW only possible from playing state with
```
<onclick condition="Player.Paused">PlayerControl(Play)</onclick>
<onclick>PlayerControl(Forward)</onclick>
```

Or you could even make it a two clicker from pause: once to unpause and a second click to start FF/RW
```

```
<onclick condition="Player.Paused">PlayerControl(Play)</onclick>
<onclick condition="!Player.Paused">PlayerControl(Forward)</onclick>
```

**Comment by jjd-uk** [comment]
> IMHO The bigger question to ask is why are the FF/RW buttons hidden at all when paused in the first place? Why is the user not allowed to use those buttons from a paused state?

Because they do nothing when in a paused state.

**Comment by jjd-uk** [comment]
> Or you could even make it a two clicker from pause: once to unpause and a second click to start FF/RW. This kind of goes well with how the FF/RW function with each successive click stepping up the speed. So from pause you go 1x 2x 4x 8x 16x
> 
> ```
> <onclick condition="Player.Paused">PlayerControl(Play)</onclick>
> <onclick condition="!Player.Paused">PlayerControl(Forward)</onclick>
> ```

That's a good alternative which hadn't crossed my mind.

**Comment by Hitcher** [comment]
> Or you could even make it a two clicker from pause: once to unpause and a second click to start FF/RW. This kind of goes well with how the FF/RW function with each successive click stepping up the speed. So from pause you go 1x 2x 4x 8x 16x
> 
> ```
> <onclick condition="Player.Paused">PlayerControl(Play)</onclick>
> <onclick condition="!Player.Paused">PlayerControl(Forward)</onclick>
> ```

Updated use this solution.

**Review by the-black-eagle — APPROVED** [review]
Thanks!

**Review by jurialmunkey — APPROVED** [review]
Approved from me.

One thought I had but for after this PR - possibly might feel more natural for rewind to start immediately since it goes the other way from play. But need to try both approaches out for a bit to get a feel for which feels better. 

Definitely a thought for another day. Don't want to hold-up this one going in as either approach imho is much improved compared to the buttons hiding or being disabled when paused.

**Comment by jjd-uk** [comment]
Sorry just realised I didn't do a squash & merge.

**Pull request merged**
