### PR TITLE
[binary addons] bump audio decoders

### PR DESCRIPTION
**Pull request by un1versal**
Similar to https://github.com/xbmc/xbmc/pull/7221 for same reasons Ive made PRs and they been merged there.

@wsnipex 

Only pvr ones left?

You may like to glance over the includes changed just in case, though looks OK from here. Jenkins should know.

### CODE REVIEW

**Comment by hudokkow** [comment]
thanks, will you take care of pvr?

jenkins build addons please

**Comment by uNiversaI** [comment]
Well that failed miserably !

re: pvr addons not all of them, I can take care of some if that helps.

**Comment by hudokkow** [comment]
Not miserably... jenkins couldn't download https://github.com/notspiff/audiodecoder.sidplay/archive/5ae7349.tar.gz because that commit doesn't exist (it belongs to audiodecoder.modplug)

https://github.com/notspiff/audiodecoder.sidplay/commit/27b2c0582878857bfe03195471fa7ffa4bcc40f0 is the correct one

Correct your commit, please.

**Comment by uNiversaI** [comment]
good catch, should be fixed now.

**Comment by hudokkow** [comment]
jenkins build addons please

**Comment by hudokkow** [comment]
audioencoder.wav failed on all platforms

**Comment by wsnipex** [comment]
now it should work.
jenkins build addons please

**Comment by uNiversaI** [comment]
@hudokkow Ive PR'ed the includes changes for pvr addons (I think all of them)

Ill leave the rest to you now, once they merged you or someone else can handle the bump PR.

Thats should help you some.

What I found strange is some #includes <some/header.h> and some are  #includes "some/header.h" why mic < and " no idea.

**Comment by MartijnKaijser** [comment]
can this one go in @wsnipex ?

**Pull request merged**
