### PR TITLE
[advancedsettings] cleanup pvr related leftovers after videoplayer merge

### PR DESCRIPTION
**Pull request by stefansaraev**
^^

### CODE REVIEW

**Comment by FernetMenta** [comment]
thanks.
@MartijnKaijser this should not go to wiki before release of 17. how is this managed?

**Comment by MartijnKaijser** [comment]
That's why I added the wiki label so we don't forget to clean it up afterwards

**Comment by NedScott** [comment]
The wiki contains notes about both current and future versions once changes are merged. Future notes are supposed to be clearly marked. For example, see http://kodi.wiki/view/Template:Future_box

**Comment by MarcoWue** [comment]
There is still no hint in the wiki regarding removed support of min cache level settings.
Moreover, will there be a setting to influence pvr cache levels again?

**Comment by NedScott** [comment]
Wiki updated.

**Pull request merged**
