### PR TITLE
added: flag for vfs add-ons with encoded hostnames in urls

### PR DESCRIPTION
**Pull request by notspiff**
So we can remove hardcoded things from core. If this is accepted for v18, I'll update the add-ons.

### CODE REVIEW

**Comment by notspiff** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
Ok to merge?

**Comment by notspiff** [comment]
afaik

**Comment by oCanna** [comment]
@notspiff 
This breaks rar archive support. I am unable to play/open rar archives using the vfs.rar addon anymore.

`05:01:27.355 T:140157360674560   ERROR: GetDirectory - Error getting
05:01:28.517 T:140156862461696   ERROR: Previous line repeats 6 times.
05:01:28.517 T:140156862461696   ERROR: Unable to lookup host: '%2Fhome%2Fvdr%2FVideos%2FYoung.Sheldon.S02E06.720p.HDTV.x264-AVS%2Fyoung.sheldon.s02e06.720p.hdtv.x264-avs.rar'
05:01:28.517 T:140156862461696   ERROR: InputStream: Error opening, rar://%2Fhome%2Fvdr%2FVideos%2FYoung.Sheldon.S02E06.720p.HDTV.x264-AVS%2Fyoung.sheldon.s02e06.720p.hdtv.x264-avs.rar/Young.Sheldon.S02E06.720p.HDTV.x264-AVS.mkv?flags=8
05:01:31.364 T:140157911835584  NOTICE: VideoPlayer::OpenFile: rar://%2Fhome%2Fvdr%2FVideos%2FYoung.Sheldon.S02E06.720p.HDTV.x264-AVS%2Fyoung.sheldon.s02e06.720p.hdtv.x264-avs.rar/Young.Sheldon.S02E06.720p.HDTV.x264-AVS.mkv
05:01:31.366 T:140156661135104  NOTICE: Creating InputStream
05:01:31.368 T:140156661135104   ERROR: AddOnLog: RAR archive support: GetDirectory: rar lib returned no files in archive , likely corrupt
05:01:31.368 T:140156661135104   ERROR: GetDirectory - Error getting rar://
05:01:31.368 T:140156661135104   ERROR: AddOnLog: RAR archive support: GetDirectory: rar lib returned no files in archive , likely corrupt
05:01:31.368 T:140156661135104   ERROR: GetDirectory - Error getting rar://
05:01:31.368 T:140156661135104   ERROR: CVideoPlayer::OpenInputStream - error opening [rar://%2Fhome%2Fvdr%2FVideos%2FYoung.Sheldon.S02E06.720p.HDTV.x264-AVS%2Fyoung.sheldon.s02e06.720p.hdtv.x264-avs.rar/Young.Sheldon.S02E06.720p.HDTV.x264-AVS.mkv]
05:01:31.368 T:140156661135104  NOTICE: CVideoPlayer::OnExit()`

**Pull request merged**
