### PR TITLE
Add Manifesto

### PR DESCRIPTION
**Pull request by yol**
Copy of https://kodi.wiki/view/Team_Kodi_manifesto so it can be archived and live here in the repository

### CODE REVIEW

**Review by Darren-Hill — APPROVED** [review]
Looks fine to me

**Comment by yol** [comment]
@KarellenX wiki page can be removed

**Comment by KarellenX** [comment]
Thanks @yol It has been Archived.

**Comment by ccope** [comment]
Maybe split this into CONTRIBUTING.md and CODE_OF_CONDUCT.md and put them in the top level? People will be more likely to see those (IIRC github prompts users to open the contributing guidelines when making their first PR to a project)

https://docs.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project
https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

**Comment by yol** [comment]
@ccope I don't think most of the content is appropriate for either documents. The "Team-Kodi members should always strive to" has some content relevant for CoC, but I think most of it is already in there anyway. @Darren-Hill what do you think, should we move some of the points to CONTRIBUTING.md?

**Comment by Darren-Hill** [comment]
I think it's better as its own document, as it doesn't really fit into either of the other two.

**Pull request merged**
