### PR TITLE
[network] fix CID 1364572 - ensure we're not leaking the ipv6 test socket

### PR DESCRIPTION
**Pull request by mkortstiege**

### CODE REVIEW

**Review by ace20022 — APPROVED** [review]

**Comment by wsnipex** [comment]
Since the class is called CPosixUDPSocket, shouldn't we be using close instead of the windows function closesocket?

**Comment by ace20022** [comment]
> Since the class is called CPosixUDPSocket, shouldn't we be using close instead of the windows function closesocket?

Might be better. This is quite messy. At line 34 there's
```
#ifdef WINSOCK_VERSION
#define close closesocket
#endif
```

and in \xbmc\linux\PlatformDefs.h there's

```
#ifdef TARGET_POSIX
....

#define closesocket(s)  close(s)
...
```

**Comment by mkortstiege** [comment]
IMO we should merge this one and do a cleanup and rename of this class in another PR. The name is misleading as it's not Posix exclusive.

**Comment by Paxxi** [comment]
Agree with @mkortstiege, whole networking implementation needs a cleanup and proper abstraction layer to avoid all of this

**Pull request merged**
