### PR TITLE
TagLoaderTagLib: Avoid potential crash when exception is thrown

### PR DESCRIPTION
**Pull request by philipturnbull**
## Description

The `file` object is first deleted. If `new Ogg::Vorbis::File(stream)` throws an exception then `file` is not reinitialized and will still point to a deleted object:

https://github.com/xbmc/xbmc/blob/1de048630cec0cb9f190fb3e1e9d3c90c669b1bf/xbmc/music/tags/TagLoaderTagLib.cpp#L1281-L1283

The exception is caught and logged, but then the deleted `file` object is used to check if the file was opened successfully:

https://github.com/xbmc/xbmc/blob/1de048630cec0cb9f190fb3e1e9d3c90c669b1bf/xbmc/music/tags/TagLoaderTagLib.cpp#L1287-L1293

## Motivation and context

Avoid a potential crash.

## How has this been tested?

Only compile tested.

## What is the effect on users?

No crash if creating a new Ogg vorbis stream fails.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by the-black-eagle — APPROVED** [review]
Looks sane.

**Review by fritsch — APPROVED** [review]
Thanks very much!

**Comment by fuzzard** [comment]
Jenkins build and merge

**Comment by the-black-eagle** [comment]
Thanks for your contribution!

**Pull request merged**
