### PR TITLE
depends/libmicrohttpd: bump to the new version

### PR DESCRIPTION
**Pull request by Karlson2k**
Updated libmicrohttpd to the latest version.

Not sure whether I have access to upload the tarball to Kodi mirrors.

### CODE REVIEW

**Comment by fuzzard** [comment]
Tarball on mirrors.

Jenkins build this please

**Comment by fuzzard** [comment]
Need to drop this line applying the patch

https://github.com/xbmc/xbmc/blob/a585fefb9c27df014a5f21d1ef65fbdc55334448/tools/depends/target/libmicrohttpd/Makefile#L32

**Comment by Karlson2k** [comment]
> Need to drop this line applying the patch
> 
> https://github.com/xbmc/xbmc/blob/a585fefb9c27df014a5f21d1ef65fbdc55334448/tools/depends/target/libmicrohttpd/Makefile#L32

Sorry, missed it

**Comment by fuzzard** [comment]
Jenkins build and merge

**Pull request merged**
