### PR TITLE
[PVR][JSON-RPC] Expose EPG tag's series number as 'seasonnum' property.

### PR DESCRIPTION
**Pull request by ksooo**
For details see https://github.com/xbmc/xbmc/issues/19999#issuecomment-888046530 

@phunkyfish when you find some time for a code review...
@DaveTBlake is the JSON-RPC change okay?

BTW, I wouldlike to backport this as I consider it a fix.

@louisbraun fyi

### CODE REVIEW

**Comment by DaveTBlake** [comment]
@ksooo this is a non-breaking interface change so bump JSON minor version e.g. 12.4.0

It is best practice (results can be parsed positionally?) as a non-breaking change that the added field needs to go at the end of the type definition and field enum rather than inserted (in the obvious place ) as you have done.

Yes to backporting this as a fixm since we still have v19 and v20 inline with each other.

**Comment by ksooo** [comment]
@DaveTBlake thanks, requested changes are now in.

**Review by DaveTBlake — APPROVED** [review]
LGTM

**Review by phunkyfish — APPROVED** [review]
👍

**Comment by louisbraun** [comment]
Great, thx @ksooo 

If you provide a current windows build, i'm ready to test it.

But just for my interest: what exactly episodepart is intended for? Is there an equivalent info label for that?

**Comment by ksooo** [comment]
Honestly, I have no idea what episodepart is good for. It was introduced before my Kodi time.

**Pull request merged**
