### PR TITLE
[win32] DXVA: Added support of hevc main10 decoding.

### PR DESCRIPTION
**Pull request by afedchin**
Aslo this adds a possibility to play any 10b content like h10i with DXVA renderer on win8/8.1/10

### CODE REVIEW

**Comment by fritsch** [comment]
The ultra hd sample with 10 bit segfaults kodi: http://pastebin.com/xnztUg6e the ARTE sample plays with 7 fps using DXVA2 :-)

Hardware: Broadwell with gpu assisted decoding ... we need @AchimTuran to test with his SKL I think

**Comment by fritsch** [comment]
Just seen: http://forum.kodi.tv/showthread.php?tid=248239&pid=2169025#pid2169025 nice - technically I don't see anything that speaks against it.

If @FernetMenta acks it should go in as soon as possible

**Comment by FernetMenta** [comment]
what is this? https://github.com/xbmc/FFmpeg/releases/tag/2.8.2-Jarvis-beta2-hevc10b
where do the commits come from?

note that feature time for Jarvis is up

**Comment by afedchin** [comment]
ffmpeg changes were come from http://git.1f0.de/gitweb?p=ffmpeg.git;a=summary

**Comment by fritsch** [comment]
We could ask @Nevcairiel if he plans to push those towards upstream ffmpeg as that is the place where those belong. Then keeping "synced" patches that will automatically get in when rebasing later is easier.

**Comment by FernetMenta** [comment]
i invested a lot of work in cleanup of our ffmpeg fork. pushing commits that are not in ffmpeg repo without discusion with me is no-go.

**Comment by fritsch** [comment]
@FernetMenta obviously clear and obviously known. Everything can be reverted and as this is a force push repo it can be force pushed out at any time.

If we can - on the other hand - help and provide feedback to code of a key contributor of ffmpeg - that Hendrik is - to help that this code can also go into upstream in parallel - then this is a method of helping and working with upstream in case of new features.

**Comment by FernetMenta** [comment]
We are 10 days away from RC1 and I really can't understand why our most important library gets this kind of change in that phase.

**Comment by fritsch** [comment]
As you emphasize on "this kind of change" - you clearly and fully see that this code only and really only affects DXVA _only_ in combination with HEVC 10 bit capable accelerators to playback files - that would not run _at all_ without that code ...

But - yes - it is 10 days to to RC1 - this PR can stay open until then - if it does not come in - ffmpeg won't be bumped, too ...

**Comment by FernetMenta** [comment]
> As you emphasize on "this kind of change"

This goal was to finally use stock ffmpeg without our patches and this has not changed. With "this kind of change" I mean primarily a change that is not in ffmpeg repo.

**Comment by fritsch** [comment]
You are right and I share this policy. First I must admit - that I looked into the wrong tree when acking the change I thought it was picked from official ffmpeg repository.

But as I know that the author is a key contributor for upstream ffmpeg I am quite sure that this patch will end in ffmpeg upstream - without that patch no dxva hevc main10 decoding including format conversion after that.

Let's keep it open until the patches are accepted upstream - then we can repick and are in sync again.

**Comment by FernetMenta** [comment]
Nevertheless, our ffmpeg fork should not include those commits, if not in ffmpeg branch 2.8. For 16.0 release we need to create a final release tag on this branch.

**Comment by fritsch** [comment]
Jo - the day we create the final tar.gz I will rebase on 2.8 branch a final time and drop those patches away ...

**Comment by afedchin** [comment]
just close this till the future

**Pull request closed without merging**
