### PR TITLE
Reset playlist on new file playback

### PR DESCRIPTION
**Pull request by a1rwulf**
Suggested fix from @FernetMenta for https://github.com/xbmc/xbmc/issues/16690
@arnova could you test this, I have no PVR setup and have some trouble to trigger your issue.
Thx.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by arnova** [comment]
Yup, fixes the issue. Could you please create a backport PR for Leia as well?

**Comment by arnova** [comment]
@a1rwolf : Could you add a comment why this is required? Same for backport. Tia!

**Comment by a1rwulf** [comment]
@arnova Comment added in code and issue mentioned in commit message.

**Comment by arnova** [comment]
@a1rwulf : Thanks!

**Comment by arnova** [comment]
UWP build error unrelated

**Pull request merged**
