### PR TITLE
Pictures: fix video in slideshow

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

### CODE REVIEW

**Comment by Rechi** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
Should we backport or just leave it and ask to upgrade to v18?

**Comment by FernetMenta** [comment]
> Should we backport or just leave it and ask to upgrade to v18?

Not sure. I know it was working for bfore we released v17. Means I have no clue what it broke for v17 or v18. Just wondering why it worked at all.
Also, I did not reproduce this issue with v17 nor try to apply this change to v17.

**Comment by the-dreamer** [comment]
it was broken during development for kodi 17 and then it was fixed. But since Kodi beta (V 5 or 6) it was broken again and until now not fixed. Thanks FernetMenta.

For reference: https://forum.kodi.tv/showthread.php?tid=285842

**Comment by FernetMenta** [comment]
@the-dreamer thanks. hopefully this time it won't break again soon

**Comment by the-dreamer** [comment]
@FernetMenta, unfortunately video in slide is still not working for me. I have build kodi with commit id "28db1a8" from 15 Nov on my intel x86-64 system. Video is playbacked only with a still picture (thumbnail?). Sound is playing. 
On a other system (Rpi3) with a build from 18. Nov. the same but with only blackscreen, there is no thumbnail so i assume it is also showing only the (black/empty) thumbnail.

**Comment by FernetMenta** [comment]
Works for me on OSX and Linux X11. Was also confimed working here: https://forum.kodi.tv/showthread.php?tid=305053&pid=2667390#pid2667390

**Comment by the-dreamer** [comment]
Strange, could it help you to provide more information? Debug log for example? I have two systems where it is not working. The video itself is playbacked without issue when it is start directly. I hope it is absolute not related to LE, but here @MilhouseVH could help because on Rpi3 i am using the build from him.

**Comment by bpmarinho** [comment]
Can this fix also be applied to raspberry pi3.
I just upgrade libreelec to latest Kodi 18 and slide show on folder with videos gets me audio and black screen. Back button will show UI and video paying on the bottom.

**Comment by popcornmix** [comment]
Please us the forum for support issues. This PR is in kodi master so will be present in nightly Pi3 builds.

**Comment by bpmarinho** [comment]
Tried that version and it's not working.
Ok, will go to the forum to this issue.

**Comment by the-dreamer** [comment]
@FernetMenta , sorry for writing in this PR again: I can confirm slideshow is working, when using mp4 file format. But it is still broken for mts file format (AVCHD), which is used by sony dsc.

**Comment by Esokrates** [comment]
@FernetMenta Could you have a look at this issue again? For me it's not working on Android TV with mts as @the-dreamer observed. I have not yet tested mp4 files.
See also https://github.com/xbmc/xbmc/issues/14643.

**Pull request merged**
