### PR TITLE
CLog: optimize logs performance, avoids formatting if line is not being logged

### PR DESCRIPTION
**Pull request by thexai**
## Description
CLog: optimize logs performance, avoids string formatting and search/replace if line is not being logged

## Motivation and context
Currently all log lines (even if are not logged due log level is lower that current log level) are processed by:

https://github.com/xbmc/xbmc/blob/1d0dc77d43b4730f3b8708a84d931ce3c161d2d0/xbmc/utils/log.h#L129-L132

I want to get rid of this because, even if the performance impact is minimal, it is useless work.

The logs (like everything else) must be optimized to the maximum. With even more reason, the logs because if they have a minimal influence on performance, it is possible that some issues vary or stop being reproduced when the logs are enabled/disabled.

`StringUtils::Replace` only is used in case of multi-line logs. Those are very specific cases and it does not make sense to include that overhead in everything.

I have basically separated the multi-line log function into a new method `LogMultiline` and standard `Log`, `LogF`, `LogFC` are now performance optimized but without multi-line support.

I have opened this PR to know the opinion of others and see if doing this is viable/possible.

I also need ideas/feedback to know in which places we are using multi-line and therefore the new function should be replaced to not break anything.

Further analysis reveals that `\n` is not used anywhere else (quite safely). Then no other changes need to be made and it could be applied as is.

~So far I have Only~ replaced it in ~3~ 43 places:

AdvancedSettings:
```c++
  printer.SetLineBreak("\n");
  printer.SetIndent("  ");
  advancedXMLCopy.Accept(&printer);
  // redact User/pass in URLs
  std::regex redactRe("(\\w+://)\\S+:\\S+@");
  CLog::LogMultiline(LOGINFO, "Contents of {} are...\n{}", file,
            std::regex_replace(printer.CStr(), redactRe, "$1USERNAME:PASSWORD@"));
```

WS-Discovery:
```c++
  std::string list;

  for (const auto& ip : GetServersIPs())
    list.append('\n' + FromW(ip));

  CLog::LogMultiline(LOGDEBUG,
                     "[WS-Discovery]: The initial servers search has completed successfully with "
                     "{} server(s) found:{}",
                     m_serversIPs.size(), list);
```

WHITELIST:
```c++
  if (!indexList.empty())
  {
    for (const auto& mode : indexList)
    {
      auto i = CDisplaySettings::GetInstance().GetResFromString(mode.asString());
      const RESOLUTION_INFO info = CServiceBroker::GetWinSystem()->GetGfxContext().GetResInfo(i);
      modeStr.append('\n' + info.strMode);
    }

    CLog::LogMultiline(LOGDEBUG, "[WHITELIST] whitelisted modes:{}", modeStr);
  }
```

## How has this been tested?
Windows x64

## What is the effect on users?
Saves some CPU cycles 😄

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by thexai** [comment]
Output on logs not changes from current:

```
2022-01-08 13:32:41.842 T:10860   DEBUG <general>: [WHITELIST] whitelisted modes:
                                                   Generic PnP Monitor #1: 1920x1200 @ 60.00Hz
                                                   Generic PnP Monitor #1: 1920x1200 @ 59.94Hz
                                                   Generic PnP Monitor #1: 1920x1080 @ 60.00Hz
                                                   Generic PnP Monitor #1: 1920x1080 @ 59.94Hz
                                                   Generic PnP Monitor #1: 1920x1080 @ 50.00Hz
                                                   Generic PnP Monitor #1: 1680x1050 @ 60.00Hz
```

**Comment by wsnipex** [comment]
I like it.

**Comment by fuzzard** [comment]
We good to go with this?

I believe there was a query raised somewhere about multiline logging and it possibly not being desired at all (was that you @lrusak ?), but in the interim this seems like a good first step

**Comment by lrusak** [comment]
> We good to go with this?
> 
> 
> 
> I believe there was a query raised somewhere about multiline logging and it possibly not being desired at all (was that you @lrusak ?), but in the interim this seems like a good first step

Meh, there really isn't much value (IMO) in adding this. We should really work out a logging guideline (like I mentioned at devcon). I think we should just get rid of multiline logging all together. Or if we decide it's valid we should figure out the best way to handle multiline logging.

In terms of this PR it is missing quite a few multiline logging calls that exist in EGLImage.cpp, EGLUtils.cpp, DRMUtils.cpp, etc

**Comment by thexai** [comment]
I'm not particularly interested in multiline logging but I am against to has a performance penalty (even if it's small) because of it.

That is, for me anything that get rid of `StringUtils::Replace` pre-processing it will be OK 😃

> In terms of this PR it is missing quite a few multiline logging calls that exist in EGLImage.cpp, EGLUtils.cpp, DRMUtils.cpp, etc

I can add the missing calls to progress this PR.

**Comment by thexai** [comment]
Updated log calls I found in EGLImage.cpp, EGLUtils.cpp and DRMUtils.cpp

Missing any more?

**Comment by thexai** [comment]
Added some more... 

At least with this commit it is now easy to know where multiline log is used (in case we want to remove it in the future).

**Comment by thexai** [comment]
Jenkins build this please

**Pull request closed without merging**
