### PR TITLE
VideoPlayer: move part of the GUI messages to a GUI handler via annou…

### PR DESCRIPTION
**Pull request by enen92**
…cements

## Description
This is similar to https://github.com/xbmc/xbmc/pull/25831 but for videoplayer. Doesn't remove all dependencies but it's a step forward.

## Motivation and context
Remove GUI coupling

## How has this been tested?
Runtime tested with EDL and player process info. Other use-cases should also work.

## What is the effect on users?
None, internal refactor

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Comment by notspiff** [comment]
Two aspects to consider
1) no established division of work, sometimes caller formats data, sometimes receiver formats data.
2) how relevant and/or wanted is it to introduce a lot of one-shot announcements? this bus is exposed to json, addons, ...

**Review by ksooo — APPROVED** [review]

**Comment by enen92** [comment]
> Two aspects to consider
> 
> 1. no established division of work, sometimes caller formats data, sometimes receiver formats data.
> 2. how relevant and/or wanted is it to introduce a lot of one-shot announcements? this bus is exposed to json, addons, ...

Been busy sorry, your points are pretty valid and I also have similar concerns. I think the approach/pattern to decouple components from the GUI is pretty well identified as components must be event-driven. The announcement interface is something we can reuse with a similar pattern although when it was introduced the goal was certainly not this one (exactly because it is exposed to addons and jsonrpc; CVariant is probably only relevant to jsonrpc too).

I agree it is not the perfect nor the ultimate solution for the problem but serves as a vehicle to put us closer to the goal slowly reducing the dependencies. I'd say that whenever we get some level of consistency it'll be much easier to then migrate part of the announcements to a new interface (or improve this one) than making it a roadblock at this moment. Maybe we could have well typed Announcements that are then converted to json/CVariant only in JsonRPC.

To avoid the massive broadcast of announcements I've done https://github.com/xbmc/xbmc/pull/25874. IMHO it helps us to continue building on top of it

**Comment by enen92** [comment]
Force pushed to account for the filtering added in https://github.com/xbmc/xbmc/pull/25874

**Review by ksooo — APPROVED** [review]
Looks sane.

**Comment by fkoemep** [comment]
Would this change help with #21554?

**Comment by enen92** [comment]
@fkoemep nop, different areas

**Pull request merged**
