### PR TITLE
[Fix]Sorting by (music) Artist and JSON GetAlbums broken by PR8158

### PR DESCRIPTION
**Pull request by DaveTBlake**
Unfortunately the removeal of artist vector from CSong and CAlbum in #8158 has broken the sortbyartist and sortbyartistthenyear sorts because FieldArtist is not being populated. It also impacted AudioLibrary.GetAlbums resulting in no artists being returned.

(Please note that the sort problem is nothing to do with the recent format changes in #8267)

Functionality is restored by building a vector of artist names by splitting the artist description string, whenever song or album artist credits has not been populated. 

However since we now process the ARTISTS tag it is possible that the splitting the string may not give the same artists as held in the song_artist or album_artist tables, so could lead to discrepencies. In particular in the json rpc using GetAlbums the array of artists for an album may not match the array of artistIds.  AudioLibrary::GetAlbums needs to query album_artist table for both artists and artistIds.

@evilhamster this is the best fix in the short term, I think we will want to query the song_artist and album_artist tables most places in the furture anyway.
@jjd-uk you may want to retest the sort displays after both this and #8267 are merged. 
@Montellese I know that JSON needs a better fix, at least this gets us back where we were. 
Tidy-up is never easy is it @Razzeee !

### CODE REVIEW

**Comment by Razzeee** [comment]
jenkins build this please

**Comment by Razzeee** [comment]
Btw something I learned the hard way. Please remove #8158 from the headline, as it will close ticket #8158 in trac, when this get merged.

**Comment by Tolriq** [comment]
@DaveTBlake What sort of differences can it leads to between artists and ids for JSON ?

If there can be differences in count between both fields or other major changes, and no proper fix is planned for release, maybe there should be some notes in JSON RPC and a bump of the API version so one know the problem ?

**Comment by DaveTBlake** [comment]
>What sort of differences can it leads to between artists and ids for JSON ?

Yes there can be differences in count, but it is not frequent. An example may help. Say a song is tagged with ARTIST = "AAA & BBB feat. CCC" but also has 3 MBID - "MBIDA, "MBIDB", "MBIDC" (that happens), Picard would also tag it with ARTISTS = "AAA", ARTISTS = "BBB", ARTISTS = "CCC" tags to match up with the MBIDs.

Because users still want to see "AAA & BBB feat. CCC" when the track plays, but we want all 3 separate artists in the library, it is held as the CSong.ArtistDesc field and in the song table as the strArtist. The individual artists go into CSong.artistcredits and artist and song_artist tables. All well and good. Similar for album artists correspondingly.

GetAlbums effectitely retrieves the array of artists for each album from the string. In the example that would have 1 element. But it then gets artistids from the album_artist table using a separate query, so would get 3 values, none of them is the ID for "AAA & BBB feat. CCC" because that is not an artist in the library.

> no proper fix is planned for release,

Does Kodi ever have that kind of planning? All I can say is that I am aware of the issue, and that SetSongDetails has even worse longstanding  issues, and that in the end I want to use JSON using apps to control my music playing so I will eventually look at fixing it (unless someone else gets there first).

>maybe there should be some notes in JSON RPC and a bump of the API version so one know the problem ?

No idea how to do that. Really it is not much worse than it has been for a while, does it deserve a bump?

**Comment by MartijnKaijser** [comment]
nope it doesn't deserve a bump. Anyway since last stable Kodi 15 there already has been a JSON bump so that should be enough as officially anything between "stable" builds is not supported by us.

**Comment by Tolriq** [comment]
@MartijnKaijser Then why bother on the great numbering scheme @Montellese have put in place for JSON API version and all the hard work to have something useful for remote makers and addons and well every body ?

Or maybe you have not understood what the scheme offers to remote makers and why your answer is completely out of context phrased like that ?

You may want to not bump for any reason even if I will not agree since count can differ, but saying "Anyway since last stable Kodi 15 there already has been a JSON bump so that should be enough as officially anything between "stable" builds is not supported by us." is the opposite of the purpose of JSON API version scheme ....

**Comment by MartijnKaijser** [comment]
i perfectly understand!

**Comment by Tolriq** [comment]
Well so you understand but don't gives a shit about it.

I knew that when @MartijnKaijser jumps in there's no need to continue, but maybe the Star Wars trailer gave me some false hope ....

/me is no more here

**Comment by MartijnKaijser** [comment]
@DaveTBlake our planning is to go for beta stage next month in which we still allow some fixes (depending on size and impact). Do you have any idea on the amount of work it needs to be fixed? Just do a guestimate as we all know music section isn't in the best state and we just accept how it is on each release and try to improve in between.

**Comment by DaveTBlake** [comment]
>Do you have any idea on the amount of work it needs to be fixed

Rewrite GetAlbums to use albumartistview as well, so its own query rather that GetAlbumsByWhere. A goods days work, initially. Some one to do the testing, doing your own stuff never finds the issues.  Tidy up etc. all depends on how many rebuilds I have to do fixing comments and white space etc.and how long I get to wait before something gets built or merged. But also how much actual free time I have.

**Comment by MartijnKaijser** [comment]
ok thx was just curious. It's certainly not something we need to rush and personal life takes prio to everything. We'll see how it goes and decide from there.

**Comment by Montellese** [comment]
I don't have any time to look at this right now but if anything changes behaviour in JSON-RPC it requires a version bump independent of when in the release cycle this happens. Depending on the type of change it requires a major, minor or bugfix version bump.

**Comment by DaveTBlake** [comment]
@Montellese thanks for clarifyng. Irrespective of this fix, or the change that it follows up, the behaviour in json has changed. Since ARTISTS tag processing was added the artists array returned by GetAlbums can have a different count to the array of artistIds. So a bump is needed.

I am happy to work on a fix to make GetAlbums return artist, ID and MusicbrainzId consistently, but it would  benefit from dev team support.

**Comment by Montellese** [comment]
Getting JSON-RPC back into a consistent state like it was before all these changes would be very much appreciated. Unfortunately I won't be able to help out myself because I'm swamped with work and I'm gonna be on vacation soon for a whole month.

**Comment by Razzeee** [comment]
I think we should merge this as is and then fix GetAlbums in another PR.

**Comment by Tolriq** [comment]
@Razzeee we all know fix can never comes depending on many factor.

There's just need to change 30 to 31 in https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/version.txt
No need for major bug as it's not really incompatible change the field is still there with same data that can just be a little different.
The PR description will do the jobs for devs that encounter the problem.

Anyway I had forget but AudioLibrary.GetAlbums supports filtering by artists name.
If this make the search on the new field then some remotes could be broken.
There was problems in previous XBMC version with artists / artistsid, so some basic remotes  have chances to filter albums by artists name and not the ids.

So  some artists search will not return any albums while they are here.

**Comment by Razzeee** [comment]
Sure, but if you let me choose between no data and almost the correct data, I will probably choose the second one.

I don't really get why we're talking about a json bump, as it's broken and working as it's in master with the old version number. So a dev can't be sure it's down to that due to the version number.
Btw I think there is a bump already planned in another PR.

**Comment by Tolriq** [comment]
I never said do not merge I said bump version.

The search info, is just to increase the level of need of proper fix and not related to this being merged at all.

The bump is not only to know when it was broken, but more to know starting when it does work for sure in a new way ....

Another bump for another reason is not a valid argument as per @Montellese version scheme guidance each and every change needs a bump.

There was many conflicts in the past with multiple changes in JSON at the same time, it was never decided (for good reason) that other changes to version should be dropped when merged since there was another bump.... each time there was rebase after one merge and increase of the version as this is the proper way to handle those ;)

**Comment by Razzeee** [comment]
Well, then let's wait for @DaveTBlake to do a bump.
Might take some days, but we're not really in a hurry.

**Comment by DaveTBlake** [comment]
A bit confused if you want me to bump JSON with this PR - this only gets JSON back to returning possibly inconsistent artists rather than none. Or do I do it with the PR that corrects the inconsistent artists/ids ? And what do I change?

Also I would like to get this fix mereged soonest so that artist sorting works again. But I am still away, so could this be merged as is, with my promise to deal with bump and GetAlbums soon as I am back.

**Comment by Tolriq** [comment]
@DaveTBlake 

There's just need to change 30 to 31 in https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/version.txt

And it should be for this PR also since there's a change, version is mandatory indicator for JSON consumers how something works at a specific version.

If you do not change then remote maker have API 6.30 and it can be either empty or different values than ids, this is not correct as no proper way to handle that.

If you ever find time to fix fields so they return correct values, then another bump will be needed so JSON consumers can adapt.

**Comment by DaveTBlake** [comment]
@Tolriq JSON version duly bumped.

@Razzeee, or come to that anyone else in the dev team, could you possibly get this merged. Thanks.

**Comment by Razzeee** [comment]
Thank you @DaveTBlake

**Pull request merged**
