### PR TITLE
RetroPlayer: Zero-copy support

### PR DESCRIPTION
**Pull request by garbear**
Zero-copy support was added to the Game API in https://github.com/xbmc/xbmc/pull/13976 and to the libretro wrapper in https://github.com/kodi-game/game.libretro/pull/43. This extends zero-copy support to RetroPlayer.

Zero-copy allows the core to render directly into video memory, avoiding the extra bandwidth cost incurred by an additional memory copy on the CPU.

## Description
Zero-copy support is opt-in for the core by calling the [`RETRO_ENVIRONMENT_GET_CURRENT_SOFTWARE_FRAMEBUFFER`](https://github.com/kodi-game/game.libretro/blob/82039bb/src/libretro/libretro.h#L924) libretro environment command each frame. This command returns a preallocated framebuffer that the core can use to write video memory.

## Motivation and Context
Needed to fully enable zero-copy after GBM rendering was added in https://github.com/xbmc/xbmc/pull/14079.

## How Has This Been Tested?
Tested with https://github.com/kodi-game/game.libretro.vram-test, a sample add-on that renders a checkerboard pattern to a zero-copy buffer.

## Screenshots (if appropriate):
VRAM Test add-on:

vram-test-addon

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Cosmetic change (non-breaking change that doesn't touch code)
- [ ] None of the above (please explain below)

## TODO
- [x] Fix strict aliasing warnings

### CODE REVIEW

**Comment by Rechi** [comment]
wrong revision was build
jenkins build this please

**Comment by garbear** [comment]
MMAL renderer needs some non-trivial changes to work with this change. As it's currently dead code I intend to remove it before final, so I'm accelerating https://github.com/xbmc/xbmc/pull/13727 to get this PR in.

**Comment by garbear** [comment]
Merged https://github.com/xbmc/xbmc/pull/13727. jenkins build this please

**Comment by lrusak** [comment]
Tested and working with GBM! Thanks so much!

**Comment by garbear** [comment]
jenkins build this please

**Pull request merged**
