### PR TITLE
[pvr] bump addons

### PR DESCRIPTION
**Pull request by Jalle19**

### CODE REVIEW

**Comment by Jalle19** [comment]
jenkins build addons please

**Comment by xhaggi** [comment]
all the rest addons were not changed?

**Comment by Jalle19** [comment]
They were already bumped

**Comment by xhaggi** [comment]
ok ;)

**Comment by ksooo** [comment]
pvr.vbox bombs on WIN32

<pre>
[  5%] Building CXX object CMakeFiles/pvr.vbox.dir/src/client.cpp.obj
client.cpp
c:\jenkins\slave\workspace\binary-addons\platform_label\win32\project\cmake\addons\build\pvr.vbox\src\compat.h(87) : error C3861: 'setenv': identifier not found
c:\jenkins\slave\workspace\binary-addons\platform_label\win32\project\cmake\addons\build\pvr.vbox\src\compat.h(91) : error C3861: 'setenv': identifier not found
c:\jenkins\slave\workspace\binary-addons\platform_label\win32\project\cmake\addons\build\pvr.vbox\src\compat.h(93) : error C3861: 'unsetenv': identifier not found
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1.0\VC\bin\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
</pre>

**Comment by Jalle19** [comment]
jenkins build addons please

**Pull request merged**
