### PR TITLE
Closed Caption fixes

### PR DESCRIPTION
**Pull request by FernetMenta**
I got more samples and fixed cc accordingly

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
@Memphiz thanks for testing. I have fixed the remaining issues. Mind testing again?

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
@FernetMenta tested successfully - external subtitles don't conflict with cc subs anymore here :) - great work!

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
jenkins build and merge

**Comment by FernetMenta** [comment]
build errors not related

**Pull request merged**
