### PR TITLE
return value for EnableStream(AtPTS)

### PR DESCRIPTION
**Pull request by ghost**
Inputstream.mpd / inputstream.smoothstream want to tell kodi in a return value, that the stream wich was initially choosen (without knowledge of the display res) is now a different one.

The way I do it currently is not optimal, I pass as first packet an DMX_SPECIALID_STREAMCHANGE in this case. But this means, that kodi has to create / destroy / create the video codec, wich leads to longer startup times (and leads to sync times because audio is already running.

This PR simply extents EnableStream(AtPTS) with a return value, nothing more. I'll continue if this one goes its way into master.

### CODE REVIEW

**Comment by FernetMenta** [comment]
It won't get into master as dead code. I want to see how this is supposed to be used by player.

**Comment by mapfau** [comment]
I'll push the other commit later if its tested

**Comment by mapfau** [comment]
prepared for the shitstorm :-)

**Comment by FernetMenta** [comment]
I don't see how this is supposed to work. Player enables a particular stream, then the addon changes this stream without notification of player? Example:
Player opens a 720p stream. Addon changes the stream to 1080. And then?

**Comment by mapfau** [comment]
We are curently in VideoPlayer OpenStream. Stream is not playing.

From VideoPlayer pov its this:

```
stream = m_pDemuxer->GetStream(demuxerId, iStream);
    if(!stream || stream->disabled)
      return false;

    if (!m_pDemuxer->SupportsEnableAtPTS(demuxerId))
      m_pDemuxer->EnableStream(demuxerId, iStream, true);
    else
      m_pDemuxer->EnableStreamAtPTS(demuxerId, iStream, DVD_MSEC_TO_TIME(GetTime()));
```

- first line: stream returned is on adress 0x123 (pointer to list of streams from DVDDemuxClient)
- EnableStream(AtPTS) is fired and returns DMX_ES_STREAMCHANGE
- DVDDemuxClient updates the stream on adress 0x123.
- video is opened with the new settings.
- tested and works fine.

**Comment by FernetMenta** [comment]
This does not work for all cases. I don't see selectionStream updated. Further I don't see the benefit. Video decoders are supposed to get configured when stream starts to deliver demux packets. Before that you can deliver a thousand stream change events. That's cheap operations that should not harm.

**Comment by mapfau** [comment]
No Idea about selectionStreams, but in the video menu display it's right (is it selectionStreams??).
Nevertheless, It's a kind of view, if I can save a complete decoder initialization with just returning some information, I would do it. It's the sum of components where it is said: "it's only a little" but wich make a lot overall. It's on you, I don't fight for it as I watch not very often videos :-)

**Comment by mapfau** [comment]
This is the sequence whan starting a video without this modification:

The wrong video is started at first line of the snipped.
The correct video:
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: EnableStreamAtPTS(1, 7000

Means for me: Doing a time seek operation (not trivial)
Means for the user (depending on the stream codec) missing some frames.

This could be avoided with this simple fix.

B.t.w.: The delete[] of m_vExtradata in CInputStream seems to be missing for the case, the stream codec hasn't changed, undependigly of the other changes I did here, 

```
17:31:49 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: EnableStreamAtPTS(1, 0
17:31:49 T:8180   DEBUG: CurlFile::Open(153CF738) http://a39avoddashs3eu-a.akamaihd.net/d/1$AOAGZA014O5RE,574EE4B5/videoquality$1080p/ondemand/935a/8345/c769/41e1-bca2-11c4da13f6c4/1b508ee3-9592-43a4-8366-560b57cc59ed_video_12.mp4/range/0-1588
17:31:49 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: Download http://a39avoddashs3eu-a.akamaihd.net/d/1$AOAGZA014O5RE,574EE4B5/videoquality$1080p/ondemand/935a/8345/c769/41e1-bca2-11c4da13f6c4/1b508ee3-9592-43a4-8366-560b57cc59ed_video_12.mp4/range/0-1588 finished, average download speed: 1786881.7555
17:31:49 T:8180   DEBUG: CurlFile::Open(153CDF28) http://a39avoddashs3eu-a.akamaihd.net/d/1$AOAGZA014O5RE,574EE4B5/videoquality$1080p/ondemand/935a/8345/c769/41e1-bca2-11c4da13f6c4/1b508ee3-9592-43a4-8366-560b57cc59ed_video_12.mp4/range/45925-2081968
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: Download http://a39avoddashs3eu-a.akamaihd.net/d/1$AOAGZA014O5RE,574EE4B5/videoquality$1080p/ondemand/935a/8345/c769/41e1-bca2-11c4da13f6c4/1b508ee3-9592-43a4-8366-560b57cc59ed_video_12.mp4/range/45925-2081968 finished, average download speed: 3257670.0000
17:31:50 T:8180  NOTICE: Creating video codec with codec id: 28
17:31:50 T:8180   DEBUG: FactoryCodec - Video:  - Opening
17:31:50 T:8180  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
17:31:50 T:8180   DEBUG: CDVDVideoCodecFFmpeg - Updated codec: ff-h264
17:31:50 T:8180   DEBUG: FactoryCodec - Video: ff-h264 - Opened
17:31:50 T:8180   DEBUG: CVideoPlayerVideo::OpenStream - open stream with codec id: 28
17:31:50 T:8180  NOTICE: Creating video thread
17:31:50 T:8180  NOTICE: Opening stream: 4 source: 256
17:31:50 T:3664   DEBUG: Thread VideoPlayerVideo start, auto delete: false
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: EnableStreamAtPTS(4, 0
17:31:50 T:3664  NOTICE: running thread: video_thread
17:31:50 T:8180   DEBUG: CurlFile::Open(153CE3F8) http://a39avoddashs3eu-a.akamaihd.net/d/1$AOAGZA014O5RE,574EE4B5/videoquality$1080p/ondemand/935a/8345/c769/41e1-bca2-11c4da13f6c4/1b508ee3-9592-43a4-8366-560b57cc59ed_audio_8.mp4/range/0-1461
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: Download http://a39avoddashs3eu-a.akamaihd.net/d/1$AOAGZA014O5RE,574EE4B5/videoquality$1080p/ondemand/935a/8345/c769/41e1-bca2-11c4da13f6c4/1b508ee3-9592-43a4-8366-560b57cc59ed_audio_8.mp4/range/0-1461 finished, average download speed: 3253255.3240
17:31:50 T:8180   DEBUG: CurlFile::Open(153D0810) http://a39avoddashs3eu-a.akamaihd.net/d/1$AOAGZA014O5RE,574EE4B5/videoquality$1080p/ondemand/935a/8345/c769/41e1-bca2-11c4da13f6c4/1b508ee3-9592-43a4-8366-560b57cc59ed_audio_8.mp4/range/45846-111022
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: Download http://a39avoddashs3eu-a.akamaihd.net/d/1$AOAGZA014O5RE,574EE4B5/videoquality$1080p/ondemand/935a/8345/c769/41e1-bca2-11c4da13f6c4/1b508ee3-9592-43a4-8366-560b57cc59ed_audio_8.mp4/range/45846-111022 finished, average download speed: 3116383.3304
17:31:50 T:8180  NOTICE: Finding audio codec for: 86057
17:31:50 T:8180   DEBUG: FactoryCodec - Audio: FFmpeg - Opening
17:31:50 T:8180   DEBUG: FactoryCodec - Audio: FFmpeg - Opened
17:31:50 T:8180  NOTICE: Creating audio thread
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: EnableStreamAtPTS(2, 18446744073709551615
17:31:50 T:7632   DEBUG: Thread VideoPlayerAudio start, auto delete: false
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: EnableStreamAtPTS(3, 18446744073709551615
17:31:50 T:7632  NOTICE: running thread: CVideoPlayerAudio::Process()
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: EnableStreamAtPTS(5, 18446744073709551615
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: EnableStreamAtPTS(6, 18446744073709551615
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: EnableStreamAtPTS(7, 18446744073709551615
17:31:50 T:8180   DEBUG: CApplication::OnPlayBackStarted: play state was 1, starting 1
17:31:50 T:8180   DEBUG: CVideoPlayer::SetCaching - caching state 2
17:31:50 T:7632   DEBUG: CDVDAudio::Pause - pausing audio stream
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: DMX_SPECIALID_STREAMCHANGE
17:31:50 T:5836   DEBUG: CApplication::PlayFile: OpenFile succeed, play state 2
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: GetStreamIds()
17:31:50 T:5836   DEBUG: CApplication::OnPlayBackStarted: play state was 2, starting 0
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: GetStream(1)
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: GetStream(2)
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: GetStream(3)
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: GetStream(4)
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: GetStream(5)
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: GetStream(6)
17:31:50 T:5836   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x0000, modifier: 0x0
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: GetStream(7)
17:31:50 T:8180   DEBUG: CDVDDemuxClient::RequestStreams(): added/updated stream 1 with codec_id 28
17:31:50 T:8180   DEBUG: CDVDDemuxClient::RequestStreams(): added/updated stream 2 with codec_id 86018
17:31:50 T:8180   DEBUG: CDVDDemuxClient::RequestStreams(): added/updated stream 3 with codec_id 86018
17:31:50 T:8180   DEBUG: CDVDDemuxClient::RequestStreams(): added/updated stream 4 with codec_id 86057
17:31:50 T:8180   DEBUG: CDVDDemuxClient::RequestStreams(): added/updated stream 5 with codec_id 86057
17:31:50 T:8180   DEBUG: CDVDDemuxClient::RequestStreams(): added/updated stream 6 with codec_id 86018
17:31:50 T:8180   DEBUG: CDVDDemuxClient::RequestStreams(): added/updated stream 7 with codec_id 86018
17:31:50 T:8180    INFO: AddOnLog: InputStream MPEG DASH: SetVideoResolution (1916 x 1008)
17:31:50 T:8180  NOTICE: Opening stream: 1 source: 256
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: EnableStreamAtPTS(1, 7000
17:31:50 T:8180  NOTICE: Creating video codec with codec id: 28
17:31:50 T:8180   DEBUG: FactoryCodec - Video:  - Opening
17:31:50 T:8180  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
17:31:50 T:8180   DEBUG: CDVDVideoCodecFFmpeg - Updated codec: ff-h264
17:31:50 T:8180   DEBUG: FactoryCodec - Video: ff-h264 - Opened
17:31:50 T:3664   DEBUG: CVideoPlayerVideo::OpenStream - open stream with codec id: 28
17:31:50 T:8180  NOTICE: Opening stream: 4 source: 256
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: EnableStreamAtPTS(4, 9000
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: EnableStreamAtPTS(2, 18446744073709551615
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: EnableStreamAtPTS(3, 18446744073709551615
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: EnableStreamAtPTS(5, 18446744073709551615
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: EnableStreamAtPTS(6, 18446744073709551615
17:31:50 T:8180   DEBUG: AddOnLog: InputStream MPEG DASH: EnableStreamAtPTS(7, 18446744073709551615
17:31:50 T:3664    INFO: CVideoPlayerVideo - Stillframe left, switching to normal playback
17:31:50 T:3664  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1920x1080)
17:31:50 T:3664   DEBUG: DXVA - open decoder
```

**Comment by FernetMenta** [comment]
I agree that things can be optimized but I don't agree to this change. Updating a stream this way is not a good idea.

**Comment by mapfau** [comment]
OK, we'll search for an other solution :-)

**Pull request closed without merging**
