### PR TITLE
FIX: [droid] app name parametrization

### PR DESCRIPTION
**Pull request by koying**
This actually allows to build droid with a different app name

/cc @wsnipex

### CODE REVIEW

**Comment by wsnipex** [comment]
why do you remove the parametrization from configure and makefiles?
Its there for a good reason. We do not want to have our binaries/wrapper scripts named kodi* if the app name was changed.
Please drop that commit.

**Comment by koying** [comment]
I don't. Those files have hardcoded names in our tree: https://github.com/xbmc/xbmc/tree/master/tools/Linux

They are renamed at installation time, e.g. ```@install tools/Linux/kodi.sh $(DESTDIR)$(bindir)/@APP_NAME_LC@```

**Comment by wsnipex** [comment]
right, seems I'm still asleep, sorry.
Its actually on oversight though. My play back then was to also rename the *.in files before or during configure. Not sure whats whats better.

**Comment by koying** [comment]
Seems to me rename at install is better/leaner than fiddling with copying .in (when/how would you do that, btw? Must be before autoconf...)
I actually don't care for android, but building fails otherwise.

**Comment by wsnipex** [comment]
the renaming would be easy, in bootstrap or configure itself.
But I'm ok with keeping it as is.

jenkins build this please

**Comment by guidosarducci** [comment]
@koying Thanks so much for putting this in mainline.  In order to test Jarvis and Isengard side-by-side on my solitary AFTV box, I had to do the same thing by borrowing your previous changes from SPMC to build a 'Kodi_Jarvis' app.

Could you please apply these changes to Jarvis too, since they work fine (just checked) and will ease testing going forward for some folks like me?

**Comment by koying** [comment]
> which was also to not parametrize the Kodi log file name
@wsnipex An opinion on hardcoding the log filename? Seems to make sense, as I don't see a risk of conflict (userdata dirs are different) and indeed would allow the log uploader to work.

**Comment by wsnipex** [comment]
I don't like it as it facilitates forks using our infrastructure even more.
Peeps using rebranding for testing should really be able to get the log via adb.

**Comment by koying** [comment]
Good point. That's a no, then.

**Comment by koying** [comment]
@wsnipex Your button if you're ok

**Comment by guidosarducci** [comment]
@koying  I'd asked earlier if you might backport these changes for Jarvis too, since they apply cleanly and ease testing for some like me. Is that something you could do?

I also noticed a problem with the current changes: building binary addons fails because some include directories are parametrized by appname and cause problems for several addons.

For example (while using 'kodi_beta' instead of 'kodi' as appname):
```
In file included from /home/kodidev/kodi-android/tools/depends/target/binary-add
ons/arm-linux-androideabi-android-17/build/pvr.hts/src/AutoRecordings.cpp:22:0:
/home/kodidev/kodi-android/tools/depends/target/binary-addons/arm-linux-androide
abi-android-17/build/pvr.hts/src/AutoRecordings.h:32:30: fatal error: kodi/libXB
MC_pvr.h: No such file or directory
 #include "kodi/libXBMC_pvr.h"
                              ^
compilation terminated.
```
The file was *actually* located under a `include/kodi_beta` directory in this case.

Appreciate if you could look into this when you have a chance. As a reference, I tried to un-parametrize the include directories in this branch, and can compile binary addons, but am not sure if if broke other things: [custom-appname branch] (https://github.com/guidosarducci/xbmc/commits/custom-appname)

Happy holidays and best in the new year!

**Comment by wsnipex** [comment]
the correct fix for the addon breakage is to fix the addons. They should not include "kodi/something" but just "something"

**Pull request merged**
