### PR TITLE
  [EPG] Some EPG window cleanup

### PR DESCRIPTION
**Pull request by ksooo**
Followup for #7509

@xhaggi mind taking a look

### CODE REVIEW

**Comment by xhaggi** [comment]
https://github.com/ksooo/xbmc/blob/epg-window-fixes-2/xbmc/epg/GUIEPGGridContainer.cpp#L1411 cast could be removed?

**Comment by ksooo** [comment]
>https://github.com/ksooo/xbmc/blob/epg-window-fixes-2/xbmc/epg/GUIEPGGridContainer.cpp#L1411 cast could be removed?

Thx. Overlooked this one. Changed.

**Comment by xhaggi** [comment]
looking good so far

**Comment by ksooo** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by ksooo** [comment]
Jenkins build errors are not related to this PR.

As "usual" addon build errors on the Pi, and since integration of the AudioDSP stuff errors with adsp.* addons.

**Comment by xhaggi** [comment]
shove it in

**Pull request merged**
