### PR TITLE
Build an Android App Bundle (AAB) for each ABI

### PR DESCRIPTION
**Pull request by joseluismarti**
## Description
"Android App Bundle" (AAB) is the format for publishing apps on Google Play which is replacing APKs.

This proposal adds the build in AAB format.

Both package formats are now available.

## How to install the .aab file
We need to download [Bundletool](https://github.com/google/bundletool/releases) to manipulate the app bundle.

Extract a single `.apk` file from the `.aab` file:
```
java -jar bundletool-all-1.13.1.jar build-apks --bundle=kodiapp-armeabi-v7a-debug.aab --output=kodiapp.apks --mode=universal
```
Extract the `.apk`:
```
unzip -p kodiapp.apks universal.apk > kodiapp-armeabi-v7a-debug.apk
```

## How has this been tested?
I install the .aab file on Android TV 9 and it works fine.

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Tolriq** [comment]
@fuzzard Google recent changes https://android-developers.googleblog.com/2022/11/app-bundles-for-google-tv-and-android-tv.html will require AAB for Android TV very soon.

**Comment by joseluismarti** [comment]
The builder doesn't need anything else, the aab file is built correctly.

We should provide both formats. The apk file can be distributed and installed as usual. The aab file is the new format that will be required to upload apps to Google Play.

**Comment by lrusak** [comment]
> The builder doesn't need anything else, the aab file is built correctly.
> 
> 
> 
> We should provide both formats. The apk file can be distributed and installed as usual. The aab file is the new format that will be required to upload apps to Google Play.

Great, can you look into adjusting the buildsteps for all three android builds so that the aab file gets prepared correctly for upload.

Ref: https://github.com/xbmc/xbmc/blob/692da7507b95f4a37c76b7ba779f306054d1be3f/tools/buildsteps/android-arm64-v8a/package#L18

**Comment by lrusak** [comment]
@joseluismarti Thanks for doing that. I updated the jenkins jobs so that if the aab is available it will be uploaded.

https://mirrors.kodi.tv/test-builds/android/arm/kodi-20221129-2bfc254c-PR22183-27308-armeabi-v7a.aab
https://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20221129-2bfc254c-PR22183-25051-arm64-v8a.aab
https://mirrors.kodi.tv/test-builds/android/x86/kodi-20221129-2bfc254c-PR22183-17998-x86.aab

**Comment by Tolriq** [comment]
You can only upload 1 aab per app, the app does contains the different targets and the split is done by Google. You won't be able to upload those 3 and Google requires x64 support in aab since 2019.

**Comment by lrusak** [comment]
> You can only upload 1 aab per app, the app does contains the different targets and the split is done by Google. You won't be able to upload those 3 and Google requires x64 support in aab since 2019.

Jenkins doesn't upload to the play store. This is purely for archival purposes.

**Comment by Tolriq** [comment]
What I mean is that there should only be 1 aab that have all the architecture in it, that what you'll need to be able to upload to Google Jenkins or not.
Can't access those aab to check, but building 4 aab is a lot of ressources and storage loss for no benefits.

**Comment by lrusak** [comment]
> What I mean is that there should only be 1 aab that have all the architecture in it, that what you'll need to be able to upload to Google Jenkins or not. Can't access those aab to check, but building 4 aab is a lot of ressources and storage loss for no benefits.

I agree. We should probably reevaluate what we are actually trying to acomplish here. If an aab can just be built from 4 apks it's likely we can just do that in a separate job or the person who uploads to the play store can do that before hand. If there is no value in having individual aab files then we can just close this PR.

**Comment by Tolriq** [comment]
No it's the opposite actually. You generate the unique aab that is uploaded to Play Store.
And you can generate the different APK from the aab if wanted (or to actually test the aab)

**Comment by joseluismarti** [comment]
If currently the requirement is a single aab per app with all targets and if we can **confirm this** and that **there is no possibility or exception** to continue uploading one file per arch. as at present (now in aab format), we can discard this change and start preparing a new one with all of them together.

Before we make a decision, can anyone with access to the store confirm it?

**Comment by Tolriq** [comment]
Stupid question but what's the point of trying to workaround what aab are meant for and expected to be used? More server work, more storage, probable issues in the future, ... 
All the build tools are here's it's probably a one line change to fix and ensure less problems.

**Comment by joseluismarti** [comment]
Of course, what nonsense, I invite @Tolriq to change a line and we don't waste any more time.

**Comment by Tolriq** [comment]
12 years contributing to Kodi and still the same nice feeling :)

ANDROID_HOME=$(SDKROOT) ./gradlew bundle$(BUILD_TYPE)

Remove $(BUILD_TYPE) and done ....

**Comment by joseluismarti** [comment]
That would work if all targets are built at the same time and the Java code is compiled and packaged with a single `gradlew`.

As you know, currently each target is built independently and generates one apk per target.

**Comment by Tolriq** [comment]
Of course I over simplify and you need to create a new target the compile and put the .so at the right place. Just to point that a little time passed now is a ton of time gained later and that all the parts are already here. AAB is meant to be for Play Store upload, Play Store is a master in not being happy and blocking on stupid things, 10 years publishing there and they still impress me with their changes.

Having made the effort to negotiate the permission exception to be able to stay on Play Store is probably worth the little effort to please them on the easy things.

Only question would be `@echo "native_arch=$(CPU)" > xbmc/res/raw/xbmc.properties` no idea what's it's used for and could maybe be the only reason it's an issue.

**Comment by joseluismarti** [comment]
I close it as Jenkins is currently building both types of packages:
```
/home/jenkins/jenkins-root/workspace/android-arm-docker@2/kodiapp-armeabi-v7a-release.apk
/home/jenkins/jenkins-root/workspace/android-arm-docker@2/kodiapp-armeabi-v7a-release.aab
```

**Pull request closed without merging**
