### PR TITLE
Maintain the selection position after end of playback / watched status change

### LINKED ISSUE #16873: Marking item as watched while filter is "Unwatched" resets position to first item
### Describe the bug
Here is a clear and concise description of what the problem is:

If you are viewing a playlist that has been filtered to only show "Unwatched" and you mark an item as watched (e.g. by clicking W on the keyboard) the position is reset to the start of the playlist, not to the preceding item.

For e.g. I display my "Japanese Movies" playlist, it has the items:
[..]
Akira
Bakudan
Jinja
Kamera Taimu
Kyoto Koukou
Michiko
Shinjuku no Baka
Tokyo Dame

I select "Shinjuku no Baka" and click W. "Shinjuku no Baka" disappears and position is reset to [..]. It should select the previous item, "Michiko". At present it makes it very frustrating to review your unwatched items and update their status.

Note: [..] refers to the "Folder Up" icon, which takes you to the parent

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When you mark an item as watched it should select the preceding item

## Actual Behavior

The first item in the playlist is selected ("Folder Up")

## Possible Fix

Remember position when refreshing content and select item at preceding position

### To Reproduce

1. Go to movies
2. Open a playlist where filter is "Unwatched"
3. Browse to a movie
4. Click W
-> Movie disappears and selected item is now the first one in the playlist ("Folder Up")

### Debuglog

https://paste.kodi.tv/reqowativo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 latest update
 - Kodi version: 18.4, Compiled 2019-09-01

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CrystalP**
## Description

Extended the navigation history to track the line number of the  selected item so that it can be restored when the item disappears from the list, instead of resetting the selection to the top of the list (usually the ..)

* Added member to CHistoryItem and new accessor GetSelectedItemIndex. 

* Modified CGUIMediaWindow so that it uses the last known selected line when the last selected item is not available anymore due to a refresh, filter, watch status change, ...

* A couple other screens use the same history mechanism (CGUIWindowFileManager, CGUIDialogFileBrowser, GUIWindowMusicPlaylist ) but I made minimal changes only, they either don't attempt to restore the selected item or it didn't look like they could lose the selection and benefit.

* Second commit to remove unused member m_strDirectory - was probably created at a time when the history was not stored as a map.

I tried other ways to do this, but ended up going down deep rabbit holes and that was the best / easiest solution.

## Motivation and context

With the "unwatched" filter active in Movies / TV Shows library, losing your place after playback ends or when marking a movie/show/season/ep watched is pretty annoying and the more pages of movies/etc there are, the worse it gets.
You have to scroll down back to the same place, and repeat many times if there is more than one item to play / mark watched / ... This is a pointless scrolling and loss of time.

It looks like I'm not alone https://forum.kodi.tv/showthread.php?tid=373160

## How has this been tested?
The change is for all platforms, but tested on Windows 10.

Unwatched filter turned on for Movies and TV Shows. Navigate to first / last / middle item, play. After playback ends, position hasn't changed (instead of resetting to the top)

Navigated through Movies, Movie Sets, TV Shows (Series, Seasons, Episodes List), Photos, Videos and toggled watched status of items > OK

Changed watched status of last item in a list > no out of bounds problem

For Photos and Videos, navigated in a hierarchy of folders backwards and forwards to verify there was no change
Jumped to Settings while navigating media, moved/deleted folders or items, returned to media navigation > OK new selection is made. Selection doesn't change if no change to folders/items is made while in Settings, as expected.

## What is the effect on users?
Better experience when marking items watched or unwatched, with the selection remaining in the same place instead of resetting to the top of the list.
## Screenshots (if appropriate):
Example with a small number of items

Initial state:
image

Before PR, after changing item status to Watched (context menu or by playing the movie), the selection is reset to the top of the list:
image

After PR, after changing item status to Watched (context menu or play the movie) the selection remains at the same position:
image

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CrystalP** [comment]
@enen92, @CastagnaIT would you please take a look if you have a chance.

**Review by thexai — APPROVED** [review]
Runtime tested and works as expected. This part of the code is not familiar to me but I don't see anything wrong.

This is a major usability improvement.

**Comment by ksooo** [comment]
@CrystalP sorry being late to the party, was not aware of this PR... Although I like the changed behavior, I think I remember users once reported an issue exactly because selection was not (!) set automatically to the next item on toggling watched/unwatched as they want to quickly mark a bunch of items watched for example by simple hitting the respective key on the keyboard multiple times. Now, they would need to do watched, down, watched, down, ... instead of just watched, watched, watched, ...

**Comment by CrystalP** [comment]
@ksooo It's a different way of saying the same thing :-) The position remains the same but there is one less item > the next item is selected. So you can go w w w w w w w w
I didn't know about queues but that should be different logic / different code. I'll try.

**Comment by CrystalP** [comment]
@ksooo gave it a go and when queuing the selection still moves to the next item, same as v20

Found two odd behaviors though:
1/ when playback is stopped after letting a few items play automatically, the selection is restored to the first item you started playing (instead of the last played item or the next)

2/ when one item is in the list multiple times, sometimes the selection is restored to the wrong one after returning from playback / removing an item. Steps to make it happen not clear.

Those problems existed in v20 and were not created by the PR so I'll leave things as they are.

**Pull request merged**
