### PR TITLE
Revert "Revert "Reusepython""

### PR DESCRIPTION
**Pull request by jimfcarroll**
## Description

Revert "Revert "Reusepython"" (a.k.a. restore Reusepython)

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by peak3d** [comment]
@jimfcarroll there are currently issues with filecaching not related to this PR, I want to wait until they are solved before giving green light. In general everything looks fine so far.

**Review by Rechi — CHANGES_REQUESTED** [review]
You are not following the [code guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

**Review by peak3d — CHANGES_REQUESTED** [review]
As @Rechi  mentioned, pls. run git clang-format on the added, but not committed changes, then commit,
PR works as expected. Thx for that!

**Comment by jimfcarroll** [comment]
I'll take a look at this later today but all of the changes here are a result of an automatic revert, except in PythonInvoker.cpp where MOST are. IMO it's actually wrong to correct the style of the reverted code if in fact that's where any of the style issues are. 

We should have a single commit with a complete automated restyling of the codebase and then add a githook that automatically reformats all merges.

**Comment by fuzzard** [comment]
https://github.com/fuzzard/xbmc/commit/c8fb6b09dff4de435e37411696fb3130f2aeb734

Ran clang format over your commit Jim. Not sure if you want to cherry-pick into your branch for that PR, or what is easiest.

On a side note, There is some visually ugly formatting of a couple of the CLog:LOG lines, but i'll stick with it as it satisfies clang-format.

**Comment by jimfcarroll** [comment]
Hi @fuzzard , Maybe I'm missing something but it seems there's more than formatting changes on that commit you linked to.

**Comment by fuzzard** [comment]
Nope. Was just clang-format off tip of master. I'll have a look through again, but a lot of the original changes in your commit was formatting, so changes affected more as far as I could see.

**Comment by fuzzard** [comment]
Have just manually compared everything Jim, definitely no functional changes. All purely cosmetic.

Was there something in particular that you flagged? The oddest formatting change is in relation to the CLog::Log messages that are very long. clang-format splits the string onto multiple lines with the following as an example

```
      CLog::Log(LOGWARNING,
                "CPythonInvoker(%d, %s): the python script \"%s\" has left several "
                "classes in memory that we couldn't clean up. The classes include: %s",
                GetId(), m_sourceFile.c_str(), m_sourceFile.c_str(),
                getListOfAddonClassesAsString(m_languageHook).c_str());
```

Still all valid. https://stackoverflow.com/questions/1135841/c-multiline-string-literal can explain better than i could really.

**Comment by jimfcarroll** [comment]
I think I misinterpreted what you did. I assumed your commit was on top of mine but instead it looks like it replaces mine. When I clicked on it and noticed all the code changes I assumed something was wrong rather than taking a closer look. Sorry for wasting your time. I'll pull it in.

**Comment by peak3d** [comment]
jenkins build this please

**Comment by peak3d** [comment]
uwp64 unrelated, because broken, @jimfcarroll ready to merge? I retested, and all fine.

**Comment by Rechi** [comment]
> You are not following the [code guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

Still not fixed yet.

**Comment by jimfcarroll** [comment]
First, I will not change reverted code for formatting. That's simply wrong and will make it more difficult to decipher history. A separate commit can be done for that and you're welcome to do it after this goes in.
That leaves PythonInvoker where I changed code in order to fix the revert. Where exactly is the problem there?

**Comment by jimfcarroll** [comment]
Compromise. Separate commit with clang-format run. Thanks @peak3d

**Review by peak3d — APPROVED** [review]

**Comment by peak3d** [comment]
@rechi can you pls. approve?

**Comment by peak3d** [comment]
No reaction from @Rechi will merge tonight.

**Comment by jimfcarroll** [comment]
:clap:

**Pull request merged**
