### PR TITLE
[CMake] Allow overriding local tarball URL hashsums

### PR DESCRIPTION
**Pull request by basilgello**
## Description

The local tarballs specified via custom MODULE_URL can be different from what is pinned in 'tools/depends/target/*/*-VERSION' files.
This manifested during preparation of 20.0 Alpha 2 build in Debian where libdvd* tarballs are custom.

## Motivation and context

Don't complicate life on ditro maintainers ;)

## How has this been tested?

Built 20.0 Alpha 2 in Debian

## What is the effect on users?

None

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
What's the justification for using a different tarball than what is listed?

**Comment by basilgello** [comment]
> What's the justification for using a different tarball than what is listed?

In Debian, for example, we download the original libdvd tars from VideoLAN and apply the Debian packaging patches to the unpacked source then re-pack the tarball and point it as local tarball for internal build of libdvd*.

**Comment by wsnipex** [comment]
it also ensures that the tarball is what the devs or packager tested with.
We also rely on the hash check in our ubuntu PPA packaging, where the tarball is actually downloaded by jenkins.

The hash should be override able, but should default to our checksum when no override is set.

**Comment by basilgello** [comment]
@wsnipex Updated as we discussed.

**Comment by wsnipex** [comment]
looks good to me,  jenkins build this please

**Review by wsnipex — APPROVED** [review]

**Pull request merged**
