### PR TITLE
[videolibrary] fix sort by episodes (closes #15945)

### LINKED ISSUE #15945: musepack sv7 files miss first 0.8 s when played
### Describe the bug
When playing audio files in the Musepack SV7 format (file ending ".mpc") the first 0.8 s are never played.

## Expected Behavior
The first 0.8 s of Musepack SV7 files should be played as well.

## Actual Behavior
Currently the playback in Kodi is always skipping the first 32 frames (0.8 s) of each Musepack SV7 file. This happens since Kodi 15.x and is present in all versions since then. I also verfiied this issue in Leia 18.1 and 18.2 RC1.
Reason is that the function "mpc7_decode_flush" must only be called after a seek to a frame position > 32. When this function is called the next 32 frames are muted. In Leia 18.2 this function is called twice at the beginning of each track. In consequence the first 32 frames of each track are missing.

## Possible Fix
As a fix it is possible to check if the flush function is called for the first decoded frame or not. If so, the flush-processing must be skipped. The code is located in the ffmpeg source code under libavcodec/mpc7.c: https://pastebin.com/xzG3Am43

### To Reproduce
The bug can be best reproduced with tracks that contain significant audio signal in  the first second. Example: https://www.sendspace.com/file/xju086. 
When playing this track the initial breathing-in of the singer should be audible. Using Kodi this breath is not present, using other programs (e.g. ffmpeg, foobar2000) the file is properly playbed back.

### Debuglog
You will not see the issue from the logs. I needed to add new log messages to be able to debug this.

### Screenshots 
Not needed.

## Additional context or screenshots (if appropriate)
Please also see the conversion on kodi.tv: https://forum.kodi.tv/showthread.php?tid=330109

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux Mint 19.1
 - Kodi version: 18.2 RC1

### PR DESCRIPTION
**Pull request by mkortstiege**
This fixes incorrect sorting of tvshows (regardless of watched filter). Issue reported in ticket http://trac.kodi.tv/ticket/15945.

@Montellese for review please.

### CODE REVIEW

**Comment by mkortstiege** [comment]
Could someone please review this one?

**Comment by Montellese** [comment]
Looks good. Thanks for taking care of it.

**Comment by Montellese** [comment]
jenkins build and merge

**Comment by Montellese** [comment]
Did you forget to backport this or did I miss it?

**Comment by mkortstiege** [comment]
I think you missed it. https://github.com/xbmc/xbmc/commit/4b339058ad21169fd2ce8d165a1c75126add8c83

Any reason you ask?

**Comment by Montellese** [comment]
Right. Because it's still on the list of known issues.

**Pull request merged**
