### PR TITLE
Simple fold5

### PR DESCRIPTION
**Pull request by fbacher**
## Description
Adds FoldCase API, tests and several uses of the API.

Keeping commit small and focused on FoldCase itself. Followup commits will change numerous uses of ToLower (and similar code, all in StringUtils) to use FoldCase.

## Motivation and context
This change improves on patch for Turkish-I problem (19883). The Turkish-I problem caused Kodi to be non-functional due to ToLower not treating ASCII i/I and Turkish "I" characters in a "normal" manner. This caused all sorts of problems when the keys to lookup tables, etc. were normalized to lower case (or upper case).

Most of Kodi's use of ToLower is for 'normalizing' a key to a table. The vast majority of these cases use ASCII key values. But not universally. I have seen eight instances where something like "keyboard" was translated into the current language and then used as a key value. I have also seen where keywords are looked for in arbitrary text. These frequently work okay even with an inferior single-byte C++ tolower, but it is flirting with trouble.

This implementation uses Unicode case folding data from Unicode.org to perform "simple" casefolding. Simple case folding handles all cases where there is a 1-1 codepoint (Unicode "character") conversion between a codepoint and the folded version of the codepoint. It can't handle the few situations where a single codepoint (like German sharfes-S, which when folded becomes: 'ss' or where some context in the word or sentence makes a difference. For Kodi these situations should only exist if some quite poor programming practice is used for key values. Even if these do exist, implementing FoldCase would make the problem easier to fix since it separates general 'ToLower' (for the user to see) usage from 'FoldCase' (internal key) usage.
## How has this been tested?
For the first commit, the tests are only with the improved TestStringUtils.cpp. This is due to this commit being the API itself. The second and subsequent commits to use FoldCase will modify existing code but not additional tests. Additional tests will be added as additional APIs are added/modified (CompareNoCase, EqualsNoCase, etc.). I have worked on this problem for months, it has gone through multiple iterations and implementations. I have run all automated tests. I have run Kodi using English, German, Russian, Ukranian, Turkish and Japanese. I have downloaded several thousand movie titles from TMDb in a combination of the above languages and created dummy movies out of them so that I can search and play them. I have a Random Trailers plugin which runs in the background and plays the fake movies and displaying the Movie Info.

I have done the basic, easy things to do with the UI. I have navigated to numerous screens, etc. without failure. I have displayed our 25,000 (English) audio library.

That being said, it is very difficult to test more than a tiny amount of Kodi by hand. There are many features that I am not that familiar with. The problem is particularly difficult for me using non-English.

More testing that I have done:

    Sorting by title, date, etc.
    Search by actor, genre, date
    Drill down Movie Info -> Actor -> Titles (that the actor is in)

Testing on Ubuntu 24.04 with 6/12 CPU Intel with 32G ram. Usually running with debug builds, but also -O2 and with memory debugging from time to time.

## What is the effect on users?
Will prevent Turkish black-screen
As a side-effect the 'accuracy' of FoldCase, ToLower/ToUpper, and string comparisons should be improved for multi-byte languages since the current implementation mostly relies on C++ tolower/toupper, which ONLY works properly for single byte characters. This implementation of FoldCase is Unicode (4-bytes) ToLower/ToUpper will go at least to 2-bytes and probably 4-bytes (I'm looking at more character tables for ToLower/ToUpper from Unicode.org that have essentially the same format as for FoldCase).

Downside: Performance. Preliminary tests show that converting from utf-8 to utf32 and back can increase FoldCase string by 3x over current. However, this says nothing about real world. When I am finished converting all of the code over I will instrument the code to capture much more realistic data. There are also some things that I am doing which will help mitigate the problem, including the use of string_view instead of string.

## Types of change

- [x ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ x] I have added tests to cover my change
- [x ] All new and existing tests passed

### CODE REVIEW

**Comment by fbacher** [comment]
(I thought a branch rename would not break this PR. Sorry)

I added the second commit which converts all of the appropriate uses of ToLower to be FoldCase in xbmc/utils. I hope that it is a reasonable size code change.

**Comment by basilgello** [comment]
@fbacher Thanks for the continued work on this!

Can you please rebase the branch again, applying each diff jenkins4kodi provides to the appropriate commit then do a force-push?

**Comment by fbacher** [comment]
All commits related to FoldCase API added. Will incorporate Jenkins formatting changes when available.

**Comment by fbacher** [comment]
Something is messed up that I need to resolve. There are some recent changes from master that are in the log, but yet the changes are missing (and no log showing them removed). If I can't resolve it soon, I'll have to re-bake this thing.

**Comment by basilgello** [comment]
@fbacher look at git reflog, you will find previous states before rebase.

**Comment by fbacher** [comment]
Resolved issues. Applied patches. All tests pass

Now to add commits for *NoCase* functions (a much smaller number of changes, but the API changes are comparable to the FoldCase API change).

**Comment by fbacher** [comment]
Ugh, these diffs to specific commits are not easy. Probably because they are hitting files common to most commits (StringUtils and TestStringUtils). I think the 3-way merge is trying to include changes after offending commit. 
Also, if xxx-0001-*.diff gets applied to the first commit of xxx, then what does xxx.diff get applied to? At first I thought it was the aggregate commit, but it has fewer lines. I am busy tomorrow. It will take a couple of day to comprehend and slog through these.

Also, If I had submitted this as a proposed PR (or whatever it is called) would Jenkins still do these checks so I could quietly get everything in shape without having everyone realize how stupid I am?

**Comment by fbacher** [comment]
I think I figured out how to apply the diffs properly. (Also reminds me to build/test each and every commit before publish). 

Remaining:

- Complete review/testing of functions that depend upon FoldCase (ex. CompareNoCase, etc.)
- Update ToUpper/ToLower to take optional locale-ctype argument. Most useful for situations where only ASCII is used and where upper-case is preferred (no FoldCaseUpper). Forcing Ctype to "C" when using ASCII forces tolower/toupper to behave in 'normal' ASCII way (no Turkish I surprises).
- Change relatively few remaining ToUpper/ToLower calls to use StringView. 
- Open another PR to change ToUpper/ToLower to use 32-bit codepoint tables for better accuracy and consistency between FoldCase, utf8 (string), wstring (either 32-bit or 16-bit, depending upon platform).

**Comment by fbacher** [comment]
Closing. Superseded by another draft PR.

**Pull request closed without merging**
