### PR TITLE
Allow number

### PR DESCRIPTION
**Pull request by notspiff**
## Description
Fix old format add-on settings

## Motivation and Context
As the new setting format has some issues, i reverted projectm to the old format. this bug then surfaced.

### CODE REVIEW

**Comment by Razzeee** [comment]
I'm not convinced by this. Why do numbers end up in int?

If that's supposed to happen can it happen the other way around and does https://github.com/xbmc/xbmc/blob/8c4bec7e55b3840b4ab77f3a4cf8255431e5340f/xbmc/addons/binary-addons/AddonDll.cpp#L709 also need those guards?

**Comment by notspiff** [comment]
it's due to how the old rangeofnum settings are translated to the new code. for floats, this should work fine already, the float type steppers are of type float. it's just this one slipped.

**Comment by garbear** [comment]
Does this need a cast to not add a warning on windows?

**Comment by notspiff** [comment]
cast added.

**Pull request merged**
