### PR TITLE
[clang] fix Disabling Formatting on a Piece of Code

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description

Found during other request cleanup that it has not worked.

Before was them used as "clang format" without dash.
In accordance with https://clang.llvm.org/docs/ClangFormatStyleOptions.html it must contain the dash.

@ksooo you are added only to inform, as discussed on slack before.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by DaveTBlake — APPROVED** [review]
So has to be `clang-format off` and `clang-format on`. I'm sure I am responsible for most of these without the hyphen, works fine on Windows. Sorry about that, thanks for clean up @AlwinEsch

**Comment by AlwinEsch** [comment]
NP :smile:, was by me on Linux only confused before that, a `git diff -U0 --no-color HEAD^ | clang-format-diff -i -p1` (where I mostly use) always has changed my parts again. With this it has worked right :+1: .

**Review by ksooo — APPROVED** [review]
lgtm

**Comment by AlwinEsch** [comment]
@Rechi you are the chief of clang, is it OK?

**Pull request merged**
