### PR TITLE
[peripherals] replace peripherals manager with dialogselect

### PR DESCRIPTION
**Pull request by mkortstiege**
This nukes the peripherals manager dialog and uses generic dialog select instead.
- New dialog uses a simple list with just the device name.
- The peripheral settings dialog header now shows the actual device name rather than just `Settings`.
- Peripheral properties (vendor, product, bus, location, class and version) are passed to the settings dialog and can be used as window properties if the skin authors want to show more detailed information.

Before:
screenshot from 2015-08-23 17 57 40

After:
screenshot from 2015-08-23 18 00 16

/cc @Montellese, @phil65, @ronie

### CODE REVIEW

**Comment by mkortstiege** [comment]
jenkins build this please.

**Comment by ronie** [comment]
ping @opdenkamp as it's his baby.

**Comment by phil65** [comment]
+1. If we also achieve to get rid of PeripheralsSettings.xml in the longer term then all skins would provide peripherals support out-of-the-box.

**Comment by ronie** [comment]
@mkortstiege would it be possible to use the textbox in the select dialog to display those device properties?

**Comment by opdenkamp** [comment]
Can't review right now, on my phone and still busy with building the house. The description in the title looks good ;)


-------- Oorspronkelijk bericht --------
Van: Philipp Temminghoff <notifications@github.com> 
Datum:23-08-2015  12:49  (GMT+01:00) 
Aan: xbmc/xbmc <xbmc@noreply.github.com> 
Cc: Lars Op den Kamp <opdenkamp@gmail.com> 
Onderwerp: Re: [xbmc] [peripherals] replace peripherals manager with
  dialogselect (#7872) 

+1. If we also achieve to get rid of PeripheralsSettings.xml in the longer term then all skins would provide peripherals support out-of-the-box.

**Comment by mkortstiege** [comment]
> @mkortstiege would it be possible to use the textbox in the select dialog to display those device properties?

Yes, that's possible when using the detailed view, but i think those information are pretty useless and just clutter the list. Not sure if it's worth tbh.

**Comment by mkortstiege** [comment]
Added before/after screenshots to the PR description.

**Comment by ronie** [comment]
> i think those information are pretty useless

yeah, it probably is.

**Comment by MartijnKaijser** [comment]
only @opdenkamp know i guess :) I'm sure those things are also logged?

**Comment by opdenkamp** [comment]
Hmm the version should not be removed. The rest is optional I guess, but the version is important

**Comment by mkortstiege** [comment]
> Hmm the version should not be removed. The rest is optional I guess, but the version is important

You're ok with "Devicename (version)" ?

**Comment by HitcherUK** [comment]
Version as label2 ;)

**Comment by opdenkamp** [comment]
> You're ok with "Devicename (version)" ?
no sorry, the version string is a bit too long for that. e.g. for CEC it's currently "libCEC 3.0.1 - firmware v5 (2015-01-27)" as version string and I don't want that kind of information to be removed

**Comment by Paxxi** [comment]
What use does a regular user have for the version information?

**Comment by opdenkamp** [comment]
this is especially for regular users who you don't want to ask to look up these version numbers in a debug log.

**Comment by opdenkamp** [comment]
long term plan is to turn the implementations for these peripherals into proper (binary) add-ons btw, so if you want to re-use existing dialogs, then you can probably use the ones that we use for add-ons, which have a version number and description etc.

**Comment by mkortstiege** [comment]
Latest commit adds the detailed list layout.

screenshot from 2015-08-24 13 43 45

**Comment by opdenkamp** [comment]
that looks ok, perhaps omit the unknown versions. guess this is with mouse support disabled and that's why the icons in the top are missing to close the dialog?

**Comment by mkortstiege** [comment]
> that looks ok, perhaps omit the unknown versions.

Tested and that is just looking wrong.
> guess this is with mouse support disabled and that's why the icons in the top are missing to close the dialog?

Jep.

**Comment by MartijnKaijser** [comment]
dialog with CEC plugged in
https://db.tt/4o3veDkp

**Comment by mkortstiege** [comment]
> dialog with CEC plugged in
https://db.tt/4o3veDkp

Thanks for testing. Looks like it should.

**Comment by MilhouseVH** [comment]
Testing the latest version of this PR and a disabled CEC adapter (presumably, any disabled input device) will show "Version: Unknown"

screenshot-disabled

Would it be better to indicate that the device is disabled, eg. "Status: Disabled", rather than show "Version: Unknown" (or even, though perhaps a little confusing, "Version: Disabled")?

**Comment by mkortstiege** [comment]
How were disabled devices handled before this PR?

**Comment by MilhouseVH** [comment]
Enabled:
enabled

Disabled:
disabled

So no change in terms of behaviour, but with version now being the only label it's more obvious than before. It's just cosmetic, really.

**Comment by mkortstiege** [comment]
@MilhouseVH just pushed another commit. Mind testing again?

**Comment by MilhouseVH** [comment]
Looks good!

Enabled:
enabled

Disabled:
disabled

**Comment by mkortstiege** [comment]
Great. Thanks for testing.

**Comment by MilhouseVH** [comment]
The only remaining comment/observation I have is that once you enable CEC, the Peripheral list continues to show "Status: Disabled" until Kodi is restarted - not sure if this is a peculiarity of CEC or all input devices behave this way. It's the same when disabling CEC - it will continue to show the version information for CEC until you restart Kodi. This behaviour is not new, just more obvious now with this PR.

**Comment by mkortstiege** [comment]
Unfortunately i can't find my CEC Adapter right now. Will search for it again and test it.

**Comment by mkortstiege** [comment]
What's the status here? I'd prefer to merge as is. The remaining issues pointed out by @MilhouseVH are out of scope of this PR and should be handled separately.

**Comment by mkortstiege** [comment]
jenkins build this please.

**Pull request merged**
