### PR TITLE
[PVR] Remove dead code

### PR DESCRIPTION
**Pull request by ksooo**
Just two pieces of (logically) dead code to be removed here...

@phunkyfish should be a no-brainer.

### CODE REVIEW

**Review by phunkyfish — APPROVED** [review]

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
Giving up on Jenkins now. Tried 7 times, at least one of the builders failed to build this very simple PR.

**Pull request merged**
