### PR TITLE
utils/Variant: use std::to_string() instead of std::ostringstream

### PR DESCRIPTION
**Pull request by MaxKellermann**
Reduce unnecessary bloat by an order of magnitude.

### CODE REVIEW

**Comment by fritsch** [comment]
Thx very much - looks fine to me!

**Comment by phate89** [comment]
Probably not a big difference overall but since we have it we might use fmt to do it since it seems it's faster and we already have it:
http://www.zverovich.net/2013/09/07/integer-to-string-conversion-in-cplusplus.html

**Comment by fritsch** [comment]
On the pro-side it is between 10 times and 3 times faster than std::string and therefore most likely a lot faster than what we currently have.

On the cons-side: it would push direct dependencies into more than the logging base library which is an issue the very moment we want to get rid of it.

The big question is: what is a low cost win here. I am in favor of using std::tostring, basically we did not yet run into real-world issues with the current code, therefore there is no real challenging issue we want to solve.

Let's wait for other's comments: @Rechi @Paxxi what do you think?

**Comment by Paxxi** [comment]
Looks good to me. Using fmt instead shouldn't be an issue as it would be contained in the cpp file so it wouldn't really leak into the whole code base

**Comment by Rechi** [comment]
Haven't seen any reports about performance issues for `CVariant::asString`, so I would keep `std::to_string` (instead of replacing it with fmt).

**Comment by MaxKellermann** [comment]
I didn't observe any performance issues with the current code either; I only bothered to make this change because the current code is not only unnecessarily bloated, but also much more complicated than just using `std::to_string()`. My patch improves both performance and readability, without a disadvantage.
I also don't think it's worth it adding another dependency; using the "fmt" library would not improve readability further, and the performance gain would be negligible.

**Comment by a1rwulf** [comment]
Seems like everyone is on the same page.

**Pull request merged**
