### PR TITLE
[pvr] fix epg retrieval which should be by database ID

### PR DESCRIPTION
**Pull request by phunkyfish**
## Description

Fix for https://github.com/xbmc/xbmc/issues/18944. The JSON API has also been bumped as a fix is required.

## How Has This Been Tested?

On OSX

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by phunkyfish** [comment]
Jenkins build this please

**Review by ksooo — APPROVED** [review]
LGTM, thx.

**Review by DaveTBlake — APPROVED** [review]
Good to catch this while still in beta

**Comment by ksooo** [comment]
jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Comment by phunkyfish** [comment]
Jenkins build this please

**Comment by ksooo** [comment]
Jenkins state is actually "Finished: SUCCESS". No idea why github does not pick it up.

**Pull request merged**
