### PR TITLE
[video][Estuary] Separate video versions from video extras at GUI level

### LINKED ISSUE #24294: Naming of version-related buttons in context menu
### Describe the bug

In context menu Manage, for a movie that doesn't have versions:
image

In context menu Manage, for a movie that has versions:
image

The circled text doesn't look like good english to me.

In addition it also seems that using a variable for "movie" in messages make things difficult for translation because it would need different translations in the different context where "movie" appears (#translations-external Slack channel)

## Possible Fix

Proposal:

"Convert {0:s} version" > "Convert to version"
"Manage {0:s} version" > "Manage versions"

It seems to me that the context menu is opened in the context of the movie library, "movie" doesn't need to be repeated and we don't have any other type of versions.
Even in the future if TV shows or episode versions are added, the word "show" or "episode won't be needed in the context menu button.

Q: can the existing messages id 40001and 40021 be changed, or are new ids needed?

I can do the PR.

### To Reproduce

1. Open movie libraray
2. Open context menu on a movie > Manage

### Debuglog

The debuglog can be found here:
Not relevant, here to make the bot happy: https://paste.kodi.tv/iyocugivig.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: current master after v21 beta 2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
Implement changes requested by several testers, to separate video versions from video extras at the GUI.

1) Introduce separate manage dialogs, one for versions, one for extras. 
* A manage dialog now contains one list instead of two before, containing either versions or extras.
* Remove the two buttons to switch between versions and extras from the skin xml.
* Add a "Extras" button to the video info dialog, next to the "Versions" button. Extras opens the manage extras dialog, versions the manage versions dialog

For skinners:
* Renamed DialogVideoVersion.xml to **DialogVideoManager.xml**
* New window "videoextra" for manage extras, to be skinned in DialogVideoManager.xml
* Window "videoversion" like before, to be skinned in DialogVideoManager.xml
* Control ids stay the same. List with id 51 no longer available. List with id 50 contains the versions/extras
* Both windows are quite similar wrt. skinning, see changes in this PR

2) Remove the button to switch between versions and extras from the select dialog.

For skinners:
* No changes in control ids etc.

3) When setting "Show video with multiple versions as folder" is active, in the content of the movie node only list versions, not extras.

4) Add translatable strings 'Add version', 'Add extra' and 'Set default', changed manage dialog to use them. Removed obsolete strings from Estuary strings.po

5) Video Info dialog: New icon for video versions and video extras (thanks Sam Fisher). 
image

6) Cleanup some translatable strings. Fixes #24294 

**Important: Despite from the separation of versions and extras at GUI level, this PR should not introduce any other changes in behaviour, especially no bug fixes.**

Runtime-tested on macOS, latest Kodi master.

@enen92 would be nice if you can review the code.

### CODE REVIEW

**Comment by CrystalP** [comment]
Runtime tested, the split worked mostly OK, noticed two things.

* Occasional weird art problem (art displayed in Manage dialog and in Choose Art dialog), haven't been able to really put a finger on it, maybe pre-existing, maybe regression.

* For the removal of Extras from the play select version dialog to work well, further changes to the logic of FileItem.HasVideoVersions are needed, I could do the PR.
HasVideoVersions is currently true when a movie has versions and/or extras. Should be changed to "true only when there are multiple movie versions". A separate HasVideoExtras may be nice for skinning, but maybe not since you're trying to hide the extras.

Without that logic change, for a movie with single version and some extras, in the library list:
- it has the "versions" icon to the left of the name
- playing it opens the version selection dialog with just the single version instead of just playing it.
- same thing happens in "versions as folders"  mode.

**Comment by ksooo** [comment]
@CrystalP thanks for the feedback. In this PR I can take care of all things you mentioned, except the artwork issue. This needs further investigations and I would postpone it to a follow up PR dealing with artwork issues as there are also others reported.

**Comment by CrystalP** [comment]
patch to change the HasVideoVersions as mentioned above (Jenkins wants the massive realignment, only 2 lines changes)  94e71ef68cbf9df1ace6c3c36062872a8c1ca28f

**Comment by scott967** [comment]
Looks good for me, but is there some reason skins have to localize "Add version" and "Add extras"?  Seems like it could be cone in core strings.po in the 40000 block for versions.

**Comment by ksooo** [comment]
> is there some reason skins have to localize "Add version" and "Add extras"? Seems like it could be done in core strings.po in the 40000 block for versions.

Reason is that skinners started to "hack" around missing core functionality instead of requesting core features. ;-) Those two strings you mentioned should now be obsolete, btw. No more need to hack buttons into the manage dialog with this PR.

**Review by enen92 — APPROVED** [review]
Can't really comment on the functionality but code looks ok.skinners have to implement 2 new windows though

**Comment by ksooo** [comment]
> skinners have to implement 2 new windows though

Not really, as there is only 1 xml file for both manage dialogs. And compared to initial approach, the xml gets even simpler.

**Comment by ksooo** [comment]
Heads-up: I will do another round of adjusting names, including internal stuff like naming of classes etc, but also (one last) renaming of the window names. Current are inconsistent and sometimes not even hitting the point. Also the name of the xml file for the skin will change. We need to do all this once right before first release.

**Comment by ksooo** [comment]
> Heads-up: I will do another round of adjusting names, including internal stuff like naming of classes etc, but also (one last) renaming of the window names.

Done with latest force-push.

**Comment by ksooo** [comment]
@CrystalP with latest force-push, the problems you reported for movies without versions, but with extras should be fixed. Thanks for the patch.

**Comment by CrystalP** [comment]
Works well for me. Just a few nitpicks:
I think that indicating versions or extras in the title bar of the manage dialog would be helpful.
For example. "Manage <movie name> versions" and "Manage <movie name> extras" instead of always "Manage <movie name>"

The new message 40024 "Add Extras" should probably use the singular form, ie "Add Extra" for consistency with manage versions and because the addition screen only lets you add one at a time.

The Manage dialog seems to remember the last focus/active button between invocations, including when going to manage extras then versions for example. Not a big deal, but focus when opening should probably be in the list if it has items, and the Add button otherwise.

**Comment by HitcherUK** [comment]
One thing I just noticed, but has probably been there awhile, there's a space before the colon in the select version dialog.

`Versions : Alien` should be `Versions: Alien`

**Comment by ksooo** [comment]
Thanks for the feedback. I will change what you requested, in this PR, except the focus/select fix which will be in a follow up PR which I already have prepared but not yet opened.

**Comment by ksooo** [comment]
> "Manage <movie name> versions"

Putting the extras/versions at the end to the string can easily lead to not being rcognized/visible if yo have along movie names.

Lets go with like we do it for the select dialog:
Versions: <movie name>
Extras: <movie name>

The fact that we manage something here should be obvious from the functionality the dialog proves.

**Pull request merged**
