### PR TITLE
[depends][Windows] msys2 fixes and update to 20231026

### PR DESCRIPTION
**Pull request by CrystalP**
## Description

* Update msys2 to version 20231026 and fix a number of issues found during testing of the new version.

Support for 32bit hosts was dropped in 2020 and the package updates stopped in July 2021.
It means that going forward Kodi will have to be built on 64bit hosts, but they can cross-compile win32 and uwp without issue (same as with current msys2 environment)

Until packages of new version are uploaded to the mirrors, the script will fail (set mirror=no in the script to bypass and test building with updated msys2)

* If the bump is a problem, the fixes still apply (all commits except the last one). Uploading to Kodi mirrors the missing files while they're still available will secure the ability to build v21. Should probably be done even if the version bump is done. The fixes could be backported to v20 as it's using the same msys2 as v21 so far and will suffer the same problem of package availability.

## Motivation and context

This started as a version update since the msys2 environment had not been updated for 2 years, but turned into fixes as well because of a number of problems noticed while testing, some very serious.

The packages of current msys2 environment are old and not available anymore on most msys2 mirrors > will lead to build problems when not available at all
Kodi's mirrors are not used and they don't have a full set of files
still using http for mirrors instead of https
wrong upstream url for base package

## How has this been tested?

With clean clone of Kodi repo, run normal steps download dependencies, msys2, make mingw, build Kodi
observed msys2 first use and setup for errors
Done for win32, x64 and UWP., the resulting Kodi works, ffmpeg is functional (not in depth testing, just played a couple videos)

## What is the effect on users?

none

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by thexai** [comment]
@fuzzard 
Can you upload `msys2-base-x86_64-20231026.tar.xz` from https://repo.msys2.org/distrib/x86_64/ to our mirrors (https://mirrors.kodi.tv/build-deps/win32/msys2/)

**Comment by CrystalP** [comment]
I think we should either mirror all packages (the msys2-base-... PLUS the packages that it downloads as part of our script) or none at all and point to their mirrors.
I can provide a list.
Current situation with 20210725 is in between and now msys deps are disappearing from their mirrors.

**Comment by garbear** [comment]
We should probably upload all the packages to our mirrors so that the disappearing package problem doesn't bite us again. The only downside is that sometimes our mirrors can fail, though that applies to the msys mirrors as well.

**Comment by CrystalP** [comment]
For current msys 20210725, to be able to rebuild earlier v21 and v20 in the future. 64bit versions:
https://mirrors.piconets.webwerks.in/msys2-mirror/msys/x86_64/binutils-2.36.1-4-x86_64.pkg.tar.zst
https://mirrors.piconets.webwerks.in/msys2-mirror/msys/x86_64/gcc-10.2.0-1-x86_64.pkg.tar.zst
https://mirrors.piconets.webwerks.in/msys2-mirror/msys/x86_64/isl-0.22.1-1-x86_64.pkg.tar.xz
https://mirrors.piconets.webwerks.in/msys2-mirror/msys/x86_64/make-4.3-1-x86_64.pkg.tar.xz
https://mirrors.piconets.webwerks.in/msys2-mirror/msys/x86_64/mpc-1.2.1-1-x86_64.pkg.tar.zst
https://mirrors.piconets.webwerks.in/msys2-mirror/msys/x86_64/msys2-runtime-devel-3.2.0-14-x86_64.pkg.tar.zst
https://mirrors.piconets.webwerks.in/msys2-mirror/msys/x86_64/msys2-w32api-headers-9.0.0.6158.1c773877-1-x86_64.pkg.tar.zst
https://mirrors.piconets.webwerks.in/msys2-mirror/msys/x86_64/msys2-w32api-runtime-9.0.0.6158.1c773877-1-x86_64.pkg.tar.zst
https://mirrors.piconets.webwerks.in/msys2-mirror/msys/x86_64/patch-2.7.6-1-x86_64.pkg.tar.xz
https://mirrors.piconets.webwerks.in/msys2-mirror/msys/x86_64/perl-5.32.1-1-x86_64.pkg.tar.zst
https://mirrors.piconets.webwerks.in/msys2-mirror/msys/x86_64/tar-1.34-1-x86_64.pkg.tar.zst
to be placed in https://mirrors.kodi.tv/build-deps/win32/msys2/repos/msys2/x86_64/

for 32 bit versions, replace x86_64 with i686 everywhere in paths and filenames.

We also need the matching .sig files for each package (append .sig to the file name)


The following 3 are already on Kodi's mirrors
https://mirrors.piconets.webwerks.in/msys2-mirror/msys/x86_64/diffutils-3.7-1-x86_64.pkg.tar.xz
https://mirrors.piconets.webwerks.in/msys2-mirror/msys/x86_64/windows-default-manifest-6.4-1-x86_64.pkg.tar.xz
https://mirrors.piconets.webwerks.in/msys2-mirror/msys/x86_64/yasm-1.3.0-2-x86_64.pkg.tar.xz

**Comment by CrystalP** [comment]
For updated msys 20231026, retrieve packages from https://repo.msys2.org/msys/x86_64/:
binutils-2.41-3-x86_64.pkg.tar.zst
diffutils-3.10-1-x86_64.pkg.tar.zst
gcc-13.2.0-2-x86_64.pkg.tar.zst
isl-0.26-1-x86_64.pkg.tar.zst
make-4.4.1-1-x86_64.pkg.tar.zst
mpc-1.3.1-1-x86_64.pkg.tar.zst
msys2-runtime-devel-3.4.9-2-x86_64.pkg.tar.zst
msys2-w32api-headers-11.0.1.r0.gc3e587c06-1-x86_64.pkg.tar.zst
msys2-w32api-runtime-11.0.1.r0.gc3e587c06-1-x86_64.pkg.tar.zst
patch-2.7.6-2-x86_64.pkg.tar.zst
perl-5.36.1-2-x86_64.pkg.tar.zst
tar-1.35-2-x86_64.pkg.tar.zst
yasm-1.3.0-3-x86_64.pkg.tar.zst
to upload to https://mirrors.kodi.tv/build-deps/win32/msys2/repos/msys2/x86_64/
There are no 32bit versions.

The following is already on Kodi's mirrors:
windows-default-manifest-6.4-1-x86_64.pkg.tar.zst

We also need the matching .sig files for each package (append .sig to the file name)

**Comment by garbear** [comment]
Have the packages been uploaded to the mirrors yet? I'll update https://github.com/kodi-game/kodi-game-scripting/pull/118 when they are.

**Comment by garbear** [comment]
Have all packages been uploaded? I tried with the upstream URL:

```patch
--- a/templates/addon/depends/windows/mingw/CMakeLists.txt.j2
+++ b/templates/addon/depends/windows/mingw/CMakeLists.txt.j2
@@ -2,14 +2,13 @@
 cmake_minimum_required(VERSION 3.5)
 project(mingw)
 
-# TODO: Upload msys2 packages to mirrors
-#foreach(repo msys mingw32 mingw64)
-#  if(${repo} STREQUAL msys)
-#    file(WRITE ${CMAKE_CURRENT_SOURCE_DIR}/etc/pacman.d/mirrorlist.${repo} "Server = http://mirrors.kodi.tv/build-deps/win32/msys2/repos/${repo}2/$arch\n")
-#  else()
-#    file(WRITE ${CMAKE_CURRENT_SOURCE_DIR}/etc/pacman.d/mirrorlist.${repo} "Server = http://mirrors.kodi.tv/build-deps/win32/msys2/repos/${repo}\n")
-#  endif()
-#endforeach()
+foreach(repo msys mingw32 mingw64)
+  if(${repo} STREQUAL msys)
+    file(WRITE ${CMAKE_CURRENT_SOURCE_DIR}/etc/pacman.d/mirrorlist.${repo} "Server = http://mirrors.kodi.tv/build-deps/win32/msys2/repos/${repo}2/$arch\n")
+  else()
+    file(WRITE ${CMAKE_CURRENT_SOURCE_DIR}/etc/pacman.d/mirrorlist.${repo} "Server = http://mirrors.kodi.tv/build-deps/win32/msys2/repos/${repo}\n")
+  endif()
+endforeach()
```

And get the error:

```
Packages (16) mingw-w64-x86_64-binutils-2.41-2  mingw-w64-x86_64-crt-git-11.0.0.r239.g037ba0184-1  mingw-w64-x86_64-gcc-libs-13.2.0-2  mingw-w64-x86_64-gmp-6.3.0-2  mingw-w64-x86_64-headers-git-11.0.0.r239.g037ba0184-1  mingw-w64-x86_64-isl-0.26-1  mingw-w64-x86_64-libiconv-1.17-3  mingw-w64-x86_64-libwinpthread-git-11.0.0.r239.g037ba0184-1  mingw-w64-x86_64-mpc-1.3.1-2  mingw-w64-x86_64-mpfr-4.2.1-2  mingw-w64-x86_64-windows-default-manifest-6.4-4  mingw-w64-x86_64-winpthreads-git-11.0.0.r239.g037ba0184-1  mingw-w64-x86_64-zlib-1.3-1  mingw-w64-x86_64-zstd-1.5.5-1  make-4.4.1-1  mingw-w64-x86_64-gcc-13.2.0-2

Total Download Size:    49.87 MiB
Total Installed Size:  420.15 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0    10    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404
warning: failed to retrieve some files
```

**Comment by CrystalP** [comment]
Doesn't look like they were (listed in my 2 previous posts above).
The PR fixed the override of the msys mirrors and the script tries to get them from Kodi mirrors first now but should fallback to msys mirrors with a bunch of warnings.
How do you reproduce that error, I don't get a screen that looks like that, and the package names/versions are different?

**Comment by garbear** [comment]
I tested by building the latest master of Yabause: https://github.com/kodi-game/game.libretro.yabause

**Pull request merged**
