### PR TITLE
[docs/README.macOS] Update location of Kodi source directory

### PR DESCRIPTION
**Pull request by pteeson**
Generating Xcode project for both 64bit and 32bit cases:
'In the readme it says “cmake -blah blah ../Kodi” which is wrong -
  last parameter has to be “..” without the /Kodi'

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Sorry to be nagging but i still don't like the commit message. The per email part is not something we care about at all. Just what the commit changes

**Comment by garbear** [comment]
Also we prefer that you do a "force-push" and update the existing PR. If this is too difficult, when you open a new PR make sure you link to the previous one: https://github.com/xbmc/xbmc/pull/14532

**Comment by pteeson** [comment]
Is it any better now? It looks OK on origin. 
But in the world I come from we always gave credit to the person who found the bug. In this case Memphiz.
Is that not the case for Kodi?

**Comment by garbear** [comment]
It looks great. Good job!

@Rechi @Memphiz it looks like this line needs to be updated:

> Create an out-of-source build directory

So that it uses in-source builds, like all the other readmes. Yes?

**Review by Rechi — CHANGES_REQUESTED** [review]
If you read the whole instructions you'll see that source code is at `$HOME/kodi`, you are in `$HOME/kodi-build` so `../kodi` (`$HOME/kodi-build/../kodi`) is correct.

**Comment by Memphiz** [comment]
Damn wtf ... I didn't see that. Since when are we building out of tree then? I was so used to having it in tree that I was 100% sure that ../kodi can't be right. Well no clue what is a good approach here now but I would feel really bad about the work pteeson did here because I think he really lost a lot of hairs about this git stuff ...

**Comment by garbear** [comment]
True, but a good learning experience I guess? IMO we should make it in-tree throughout for consistency and it simplifies things.

**Comment by Razzeee** [comment]
Quiet confused by the idea to make it in tree, as I would like to see the reasoning for that. 
Foot note: Windows has been out of tree, at least as long as we have cmake.

**Comment by pteeson** [comment]
I am most grateful for the opportunity to learn about a communal github environment. Previously I only used git for my own selfish stuff.
So I really am happy for the experience…. newbies always lose hair if they are truly learning. 
(This is the voice of experience speaking — I’m 81 years young and started programming on IBM Unit record equipment followed by assembly code on System 360
followed by C,C++,APL and a myriad other langs.)

So thank you for being so kind and generous in your help.

**Comment by pteeson** [comment]
So what is the resolution? Should I put it back to what it used to be?

**Comment by Memphiz** [comment]
@Razzeee well i am confused why we would ever consider out-of-tree building.
my src directory has like 20 projects. if every project would want me to build outside their tree then:
1. the number of directories in my src dir woulf be doubled (dir polution)
2. this taints the ability to efficiently use tab completion in bash
3. i have 3 xbmc clones (osx,ios,tvos) - it would be chaotic
4. going into the repo of interest, creating a build dir, entering it and do cmake .. is most natural to me - i don‘t need to know the name of the clone dir - „..“ is always right
5. no windows dev would put the solution, project files and binaries outside of the project dir.

So all in all i wonder why this change was sneaked into the readme.
jenkins builds in tree too if course.

**Comment by notspiff** [comment]
Build systems writing to source tree are broken by design and leads to abominations like novel size .gitignore files. Using a subfolder like that is an out of tree build. I think there is a confusion around the meaning of the term here.

**Comment by hudokkow** [comment]
^^ That.

@Memphiz, I'm confused. Why would you feel obligated to change your workflow?
I wrote these instructions with a clear intent: they are for newcomers, not for the seasoned Kodi dev that builds 10 different branches 20 times per day. I'm pretty sure that a dev that does that has a completely different workflow. I know I do.

@pteeson, wow! 81 and still willing to put up with us and our shenanigans. :+1:
On a more serious note, unless I'm missing something, the instructions are correct. That said, I thank you for your efforts but I vote no for this change unless there is a valid technical reason.

As a final note, I wrote these guides with at least two clear goals in mind:
- clear and concise step-by-step instructions
- clear separation of source tree and build dir (a completely different concept of out-of-tree build like notspiff mentioned above) to avoid accidents and unnecessary confusion (`git clean -xffd` nuking build dir, where can I find Kodi's blob questions, etc.)

**Comment by Memphiz** [comment]
yes - out of tree is „in its own folder“. Of course i will not change my work flow. I just imaginated when other projects that i compile (as a non-team member but drive by contributor) would have that layout in their building manual. Its not said that my workflow would work with those projects so to prevent any hazzle i tend to follow the readme of those projects. 
So even if i can do as i want in Kodi because build directory can be freely choosen due to our sane build system i normally just follow the readme for other projects because i have no time to fight any possible issues with their build system.

I just wanted to clear up that Kodi is special in that way and is not what i normally see as default on other projects.

I have no hard feelings about it and an grateful for the redone readme.

So i guess this PR has to be closed...

**Comment by garbear** [comment]
> to avoid accidents and unnecessary confusion

I think this is a strong argument, but there's value in using an in-tree build directory (which is still an out-of-tree build as @notspiff explained). It brings consistency on all platforms, and when a user f*ks up and destroys their build directory it's a good learning experience :) It follows cmake tradition, which is what directions from many other projects will use.

The in-tree vs out-of-tree thing is confusing, so I think we should omit these terms and just describe a flow that uses the traditional in-folder build directory. It leads to better code organization when there's many projects in the workspace because there's 2x less folders and it avoids the unclarity of trying to match build directories with source directories.

**Comment by pteeson** [comment]
Did housekeeping:
Deleted branch macOS-README-6.1-fix
In origin master fetched upstream
In local master fetched origin
Examined local docs/README.macOS.md - it’s been restored to before the shenanigans.

I assume that this fish is now cooked, eaten, digested, and excreted - correct?

Because I want to resume my long game on a different topic.
Am I correct that the proper place to proceed is in the forum?

**Comment by Memphiz** [comment]
yep - we are done here from my POV.
thx for your patience

**Pull request closed without merging**
