### PR TITLE
Drop internal HDHomeRun support

### PR DESCRIPTION
**Pull request by hudokkow**
Based on @notspiff's work, this drops our internal HDHomeRun implementation in favour of the new official add-on.
Already build tested it - http://jenkins.kodi.tv/job/BuildMulti-All/749/ - but needs review as I may have missed something.

According to wiki, SD's official add-on doesn't support HDHR3-US / HDHR3-DT models so we might get some angry users.

Next, slingbox. Based on forum comments, it seems utterly broken.

### CODE REVIEW

**Comment by stefansaraev** [comment]
can be removed: 

https://github.com/hudokkow/xbmc/blob/drop_hdhomerun/xbmc/dialogs/GUIDialogMediaSource.cpp#L233

**Comment by hudokkow** [comment]
Thanks. Keep it coming and I'll correct.
I had it removed - and the corresponding strings.po string - but wasn't 100% sure and I ran out of grep time and patience.

**Comment by stefansaraev** [comment]
string 33040 is used in mediamanager (upnp)

**Comment by uNiversaI** [comment]
> string 33040 is used in mediamanager (upnp)

More specifically there https://github.com/xbmc/xbmc/blob/c096e7eed321a0c90073d73d35cec463cefc5a0e/xbmc/storage/MediaManager.cpp#L216-L217

**Comment by Memphiz** [comment]
Just fyi - we have at least one angry user because of dropping htsp support in favour of the PVR addon. His use case is made of multiple tvheadend backends he connected to by just adding a source for each of the tvheadend servers. This is not possible by using the PVR addon (which only allows 1 backend server). As said - just fyi - cause removing HDHomeRun support might lead to the same regression (for a use case i personally find rather stupid though ...)

**Comment by MartijnKaijser** [comment]
they are free to stay at version 15.x :)

**Comment by ksooo** [comment]
Full ACK.

**Comment by Paxxi** [comment]
Is the lack if multiple backends a limitation in our pvr addon api or in the addon? If it's the former we may want to look at adding it? If its the latter we can punt to addon authours

**Comment by MartijnKaijser** [comment]
That solves it partially https://github.com/xbmc/xbmc/pull/7020

**Comment by uNiversaI** [comment]
Well something multiple clients already being added in https://github.com/xbmc/xbmc/pull/7020

**Comment by Memphiz** [comment]
i thought this is only when using different backends/addons at the same time ... but whatever - i was just mentioning it ;)

**Comment by ksooo** [comment]
I think this is not a limitation of the PVR  add-on API. It should be possible for an add-on to support multiple backends.

 Cannot speak for other add-ons, but pvr.hts currently does only support one backend and I have not on my list to extend it to support multiple backends. And I'm not aware of other pvr.hts devs working on this.

**Comment by Jalle19** [comment]
It's more of an issue with the addon manager, there can only be one pvr.hts addon. You can run two or more if you modify addon.xml and rename the individual instances.

**Comment by NedScott** [comment]
Please note that the HDHomeRun add-on does not work for the older HDHomeRun products, which are still in use by a lot of people. Only their newer tuners support the HTTP and UPnP servers that make the add-on possible. I wouldn't bother with removing HDHomeRun support unless it's actually "in the way", but I don't feel strongly about it.

**Comment by ksooo** [comment]
@Jalle19 sure, but the method with patching addon.xml is somehow a hack, nothing for the normal user. Do you think of extending the PVR manager to support multiple installations of the same add-on in parallel to solve the problem?

**Comment by uNiversaI** [comment]
Its seems obvious then this should become a binary addon :)

**Comment by MartijnKaijser** [comment]
@uNiversaI please keep out of these dev discussions

**Comment by Jalle19** [comment]
It seems that in contrary to most other obscure shit we support, this actually has users and a use case (supporting older HDHR products) so I guess we can hold off on removing it until (hopefully) the HDHR addon has matured a bit.

**Comment by MartijnKaijser** [comment]
@Jalle19 
They old devices simply won't be supported by the add-on. 
It could indeed be moved as VFS addon once that support is in place and get the code updated to the newer version (i think there's at least a newer lib available)

**Comment by da-anda** [comment]
sorry for jumping on the OT talk about PVR add-on handling, but IMO PVR add-ons need do be handled way different. The add-ons should be treated like drivers for which "connections" can be created and configured. These connections would then hold the configuration that is currently bound to the add-on itself. That way each backend driver could be used multiple times if needed. Also management and configuration could finally be done in PVR settings and not hidden in add-on manager. So a bit similar to the UPNP media import stuff. Doing it like that would also work well for the case that we move all the creation and management of media shares (video, music, pictures) from the related file views to a central management section in settings, that way PVR would just be another kind of "share"/"source".

**Comment by MartijnKaijser** [comment]
@hudokkow care to rebase?

**Comment by hudokkow** [comment]
Done. Lets see if I didn't frak up.
jenkins build this please

**Comment by NedScott** [comment]
Why was this merged? I thought we were holding off as there are still a lot of users who need this that are not covered by the add-on.

**Comment by MartijnKaijser** [comment]
They have 15.x to use for the next year(s)  or when file system addons are available

**Comment by NedScott** [comment]
That's not really a valid reason. The only reason to drop support is if the feature isn't used or we already have something better to replace it. Neither condition is met. There's no pressing need to drop it, so why drop it now? We just talked about this in this PR, and the consensus was that this feature is still used. I'm sorry this got overlooked, but it's not hard at all to revert this pull, so what's the issue?

**Comment by da-anda** [comment]
@NedScott see it as challenge to push the integration of VFS add-ons, which IMO should be a goal for JasselHoff :)

**Comment by NedScott** [comment]
That's bullshit. I don't believe in any "pending" feature that isn't already merged. If we had VFS add-ons then, and only then, would there be a valid reason to remove HDHomerun support. This PR was only valid if the feature wasn't being used or had been replaced. It was not, and yet it was pushed anyways. There is not a single valid reason for this, or to not say "oops, a mistake" and revert this. 

You don't give a shit because it is a feature you don't use. How many god damn times does this have to happen before no one gives a shit about the program? What happens when it is a feature that you use?

**Comment by da-anda** [comment]
If it would be a feature that I use, I'd try to fix and if I can't I'd have to stick with the latest Kodi version that's supporting it, or like in this case help to get VFS add-ons in ASAP and hope for the best. I agree that the removal seems a bit premature while a possible "solution" is in sight, but we dropped support for so many other old things (Win XP, Android 2.x/4.0, older GPUs ...) already which also have still been used by many users. Whatever you remove, it's never the right time and somebody will be complaining. 

Cool down a bit Ned and let's push VFS add-ons forward. Feature might be gone in nightlies now, but chances are not too bad to have it back in for JasselHoff release

**Comment by NedScott** [comment]
We dropped those things because we had a reason to. They stood in the way of other fixes or improvements. That's not the case here. I could understand this if there was at least one tiny valid reason for this removal, but there isn't. It's insane to see all of you pretend like there is some valid reason. This isn't cleaning out unused code or cruft. This is removing an active feature that is being used by users right now with modern equipment, for no reason except that it was believed to be outdated, which we found out was incorrect. 

@hudokkow 's reasons for dropping this are black and white. The reason isn't valid. I don't know why he can't even respond here himself about this. It's like all of you have gone crazy, or are just unwilling to admit you made a really basic mistake.

**Comment by natethomas** [comment]
It was certainly a bit early to remove, but there are undeniably better ways to integrate older HDHRs already. Most specifically, by using a backend like TVH. This was an ugly feature implemented back when PVR addons didn't exist, and if they had existed, it likely would have never been developed. Removing this feature doesn't make older devices unusable. It just forces users to use a different, better method to integrate them. I wouldn't oppose the feature being added back in with VFS, but I think its existence is holding back the shift to better methods.

Also, it sounds like you've already calmed down from the "bullshit" line, but I found this gif and I hate not to use it now.

gif-hulk2

**Comment by NedScott** [comment]
I think you are confusing the tvheadend protocol with the hdhomerun protocol.

As someone who's used TVHeadend and had to relearn how to set it up more than once, no, I completely disagree that it is a "better" method. hdhomerun support was not a hack back in the days when we didn't have PVR. hdhomerun support is a live streaming protocol, unrelated to recording.

Even with my newer hardware, I do not have a DVR/PVR backend set up. It is a pain in the ass, and I don't need recording features. That's why we made such a huge deal out of the HDHomeRun add-on, because everyone knows it's a PITA to set up PVR. You can't do it on Android without a separate server, and setting it on on OS X is a huge task (OS X is not pretty for PVR).

Technically, that had nothing to do with the add-on. The add-on just added a guide and some nice UI elements. The newer hardware simply supports UPnP and HTTP streaming. By the same logic that the hdhomerun protocol was a "hack" and holding back the "better method", you could say the same about UPnP and HTTP streaming from the newer hardware.

Believe me, this is not holding back anything. If this was anything like BCHD, or tvheadend's protocol, or XP, or any of the other things we've dropped (and had users bitch about) then I would be with you, and totally agree to cutting this off. This is not the case. Please don't pretend like it is.

**Comment by Paxxi** [comment]
I'm uneasy about vfs addons and really don't like the idea of rushing it to get this back in.

Our vfs is mildly put a mess, it needs cleaning, possibly redesign and we need to take our time to spec out a proper plugin interface for it so it's stable and won't get redesigned every release

**Comment by Paxxi** [comment]
Forgot to add, since it's a big job there will be lots of discussions and people will throw around the term bike shedding, whoever does the work need to be prepared to defend his design and possibly alter it along the way without getting his feelings hurt by design discussions.

**Comment by hudokkow** [comment]
@NedScott, read my OP. It clearly states that
> According to [the] wiki, SD's official add-on doesn't support HDHR3-US / HDHR3-DT models so we might get some angry users.

That's it, that's all. I was fully aware of the implications. I don't have a problem with this code or any code, for that matter. I submitted a PR, some devs liked the idea and gave their OK, some didn't.
If it turns out to be a HUGE mistake, I can always revert.

> I don't know why he can't even respond here himself about this. It's like all of you have gone crazy, or are just unwilling to admit you made a really basic mistake.

I'm not even going to comment on that. There's a gazillion ways to communicate with me.

**Comment by NedScott** [comment]
Last message from me on this. Sorry for the message spam. I just want to apologize for getting worked up on this, and sorry to @hudokkow for implying any negative motivation with this PR or his behavior. I don't even care that much about this particular feature. What upsets me isn't the feature being removed, but the responses that followed, and being told it is for reasons that don't make sense. 

That being said, @hudokkow, yes, removing features because we are incorrect about how many people are still using that hardware, that is a mistake. It can always be applied later, when we have something better to replace it or when that hardware is actually outdated (rather than just being "older"). If you don't want to, that's fine.

Like I said, it's not the feature that upsets me, but it's that this is an example of a repeating pattern in our group. We sometimes rush to do things, but almost never revert something. Instead, people defend the action blindly, regardless of the merits of that situation.

**Comment by hudokkow** [comment]
No problem, Ned ;)
Emergency button -> https://github.com/hudokkow/xbmc/commit/3d5df0c9ec6a94ed9de4c564ed6beb4ab2e9c0dc

**Comment by Jalle19** [comment]
You can look at it this way; as long as we keep functionality like this, the longer it takes for alternative better approaches to take hold. Ideally Silicondust should develop a dedicated PVR addon, but already there's pvr.iptvsimple and tvheadend that can be used as alternatives. We don't really need four different ways to use a single device.

**Comment by JonnyGators** [comment]
HDHomeRun and the garbage collection industry thank you for your commitment to furthering the cause of forced obsolescence.  You can all feel good knowing you have resulted in the untimely discarding of many HDHR3 tuners that were perfectly fine and could still be running today, but no, you had to go and break Kodi for all of those devices.

In the future, please rethink decisions like this.  Changes to your product should be an improvement, not a downgrade.  This change made Kodi worse, it removed functionality that many were using.  I see no good reason to downgrade your product like this!

**Comment by Jalle19** [comment]
Thanks for chiming in after 9 years

**Comment by malard** [comment]
We haven't gone back in time and removed all copies of Kodi from existence, my assumption here is that the build 9 years ago of Kodi works absolutely fine, there is nothing forcing you to keep updating the software. I've got PCs which need to use a java applet for an internal work process, i've air gapped them and kept them on an old Firefox build.

**Comment by natethomas** [comment]
I'm confused. There's an HDHomerum addon that works really well last I knew. Why not just use that?

**Comment by JonnyGators** [comment]
I'm confused as well, as any method or add-on I tried didn't recognize my tuner, and my understanding has been because everything pulled support on it.

I had to setup a backend to work with it (NextPVR), which was a pain in the neck, and a whole big waste of my time that I wouldn't have to deal with if Kodi simply left well enough alone, and didn't rip out functionality.

**Comment by malard** [comment]
this was 9 years ago, why is this even relevant now?

**Comment by JonnyGators** [comment]
This is still relevant because people still own and use the HDHR3-US tuner, it is still a perfectly fine and operational unit that is not in need of replacing, and this decision to remove functionality that allowed easy use of this device 9 years ago has resulted in a poor user experience that I am bringing to your attention.

I really fail to understand this mentality of working equipment that still performs it's task perfectly fine being irrelevant.  The fact that 9 years later this choice is still negatively impacting users shows the long lasting effects of decisions like this to remove functionality for no good reason!

**Comment by chewitt** [comment]
> this was 9 years ago, why is this even relevant now?

It's not relevant at all this far down the line, but @JonnyGators appears to have recently discovered that GitHub provides a direct line to developers. Unfortunately he hasn't realised yet that going all blowhard on the people best able to help you generally results in avoidance not assistance.

@JonnyGators the forum is here: https://forum.kodi.tv .. act calm, be nice to people, and ask for ideas on how to resurrect an old but still working tuner for use with Kodi. Hint: you need to put something that speaks HDHR between the tuner box and Kodi.

**Comment by JonnyGators** [comment]
For your information, I've already setup a working solution.

I'm not trying to go all blowhard here.  I would expect that developers
should be interested in having direct knowledge of the experience of the
users of their products, and the effects of their choices.  I stand by my
statement that this decision has had long lasting negative impacts on end
users, and has made for a poor user experience, just as intentionally
adding barriers to enable use of hardware functionality (audio output) also
contributes to poor user experience.

It is noted that you do not care about the end user experience.

**Pull request merged**
