### PR TITLE
[GUI]Fix MusicPlayer.Contributors and MusicPlayer.ContributorAndRole info lables 

### PR DESCRIPTION
**Pull request by DaveTBlake**
Add "contributors" and "contributorandrole" to musicplayer infomap, accidentally ommited when these infolables were originally implemented by https://github.com/xbmc/xbmc/pull/8015

@scott967 thanks for noticing MusicPlayer.Contributors and MusicPlayer.ContributorAndRole info lables were not working.

### CODE REVIEW

**Review by enen92 — CHANGES_REQUESTED** [review]
Can you please add the doxygen comments above the map? Thanks

**Comment by DaveTBlake** [comment]
@enen92 the Doxygen comments already exist, these are in the comments but left out the actual code

**Review by enen92 — APPROVED** [review]
Nvm

**Comment by Rechi** [comment]
jenkins build this please

**Pull request merged**
