### PR TITLE
Fix dar

### PR DESCRIPTION
**Pull request by koying**
## Description

- Initialize DAR
- Implement DAR for AMC

## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by FernetMenta** [comment]
init in processInfo is ok, thanks
using hints for DAR is not really correct. hints are just hints when playback is started. DAR may change mid stream.

**Comment by koying** [comment]
Yeah, but as we have vid dimensions, DAR is duplicate info for amc, as we don't get the info back from decoder.
I'd rather know what the demuxer sent me

**Comment by FernetMenta** [comment]
Sure, better than nothing. I just wanted to spread the info again, just in case ..

**Comment by koying** [comment]
jenkins build this please

**Pull request merged**
