### PR TITLE
[Android] Adjust buffer size/duration for TrueHD IEC

### PR DESCRIPTION
**Pull request by thexai**
## Description
[Android] Adjust buffer size/duration for TrueHD IEC

## Motivation and context
A few days ago I've been investigating the problems of TrueHD dropouts (in Shield), which still have a small percentage of users. Finally, after many tests, I have discovered interesting things:

The initial idea was to increase the buffer because it seems intuitive but it has been a failure (in master branch). The current buffer used is 160 ms, and any higher value performs worse. But this has given me clues of the way forward...

Tried all possible lower values:

160ms
128ms
96ms
64ms

96 and 64 are the ones that work best and at this point I didn't know which one to choose. But then, thinking about the possible backport to Matrix I have discovered something unexpected: Matrix already uses a value of 64 ms. I was aware that the Matrix code was different but at the time I did tests and I don't know why I came to the conclusion that for TrueHD the parameters were the same. I never got around to looking at this again.

From people's feedback it is known that changing some audio settings in Shield can reduce, even completely eliminate dropouts. Specific:

Audio video sync = 0 ms (default is 50 ms)

I have been testing Matrix with the default Shield settings and it works much worse than master in those same conditions BUT with the optimized Shield settings Matrix works better than master.

Bottom line: Matrix is ​​more sensitive to setting changes in Shield.

Then I have repeated the test in master branch but with 
Audio video sync = 50 ms (default)

160 ms <--- current master
128 ms
96 ms <---- best
64 ms <---- Matrix

The conclusion is clear 96 ms is the best buffer value (by far) when using the default Shield settings.

The idea is to change this in master only and wait for more feedback. In my setup it is clear that it works better but in other setups it may be different and therefore I consider it quite risky to make changes in Matrix at this point.

If with Alpha2 the consensus is reached that TrueHD works better than Matrix then the backport could be considered.

## How has this been tested?
Runtime tested Shield Pro 2019 - FW 9.0.2 (Android 11) / Denon AVR-X1600H

**Matrix 19.4  - 64 ms**
```
DEBUG <general>: Minimum size we need for stream: 98432
DEBUG <general>: Created Audiotrackbuffer with playing time of 64.083333 ms min buffer size: 196864 bytes
INFO <general>: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 192000 format: AE_FMT_S16LE (AE) method: IEC (PT) stream-type: STREAM_TYPE_TRUEHD min_buffer_size: 196864 m_frames: 6152 m_frameSize: 16 channels: 8
```

**current master - 160 ms (0.15)**
```
DEBUG <general>: Minimum size we need for stream: 98432
DEBUG <general>: Created Audiotrackbuffer with playing time of 160.208333 ms min buffer size: 492160 bytes
INFO <general>: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 192000 format: AE_FMT_S16LE (AE) method: IEC (PT) stream-type: STREAM_TYPE_TRUEHD min_buffer_size: 492160 m_frames: 6152 m_frameSize: 16 channels: 8
```

**PR - 96 ms (0.08)**
```
DEBUG <general>: Minimum size we need for stream: 98432
DEBUG <general>: Audiotrack buffer params are: period time = 32.042 ms, period size = 98432 bytes, num periods = 3
DEBUG <general>: Created Audiotrackbuffer with playing time of 96.125000 ms min buffer size: 295296 bytes
INFO <general>: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 192000 format: AE_FMT_S16LE (AE) method: IEC (PT) stream-type: STREAM_TYPE_TRUEHD min_buffer_size: 295296 m_frames: 6152 m_frameSize: 16 channels: 8
```

## What is the effect on users?
Reduce/eliminate completely TrueHD dropouts. Even without using optimal Shield settings can be achieved TrueHD without dropouts.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fritsch** [comment]
@thexai Are you sure the root-cause is understood?

The old code basically distinguished between buffer (can be very large) and periods. What your code actually changes with the reduced buffer is the "ratio" towards the periods, so the periods get smaller.

Does it also work, if you plain double the amount of periods by e.g. reducing their size in half?

Old: [P1 P2 P3 P4 P5 P6 P7 P8] 180 ms
New: [P1' P1'' P2' P2'' P3' P3'' ... P8' P8''] 180 ms

with Pn' being Pn/2?

The periods is the crucial thing as that relates directly into the "amount" the sink needs to  be filled with data -> CPU is used to come back with data, while buffer basically only means to cover underruns properly. In ideal world the pseudo periods would also match the underlaying Android ALSA periods, same as buffer.

Though  giving the shear amount of data of an 8 channel IEC format ... It's perfectly fine to reduce the buffer time, as the size is quite fat :-)

So - both would be fine with me - given that we really understand what the issue is.

**Comment by fritsch** [comment]
In code (my wall of text):
Instead of:
```
c++
```

Just use:
```
c +=2;
```

in case of TrueHD and DTS-HD, which has exactly the same issue in IEC format.

**Comment by thexai** [comment]
Sorry, I don't quite understand your comments.

In Matrix:
32ms + 32ms = ~64ms     (two periods)
in bytes:
98432 + 98432  = 196864 bytes

PR :
32 + 32 + 32 = ~96 ms   (3 periods)
98432 + 98432 + 98432 = 295296 bytes

current master:
32 + 32 + 32 + 32 + 32 = ~160 ms   (5 periods)
98432 * 5 =  492160 bytes

basic "period" time or bytes never has changed, is 32ms and 98432 bytes


`c +=2;`  ??

current master is `c++` and PR does not change that:
https://github.com/xbmc/xbmc/blob/126c8500e157c3d81da1d56a11e18fd1280c99a1/xbmc/cores/AudioEngine/Sinks/AESinkAUDIOTRACK.cpp#L513


> Though giving the shear amount of data of an 8 channel IEC format ... It's perfectly fine to reduce the buffer time, as the size is quite fat :-)

We both agree on that  😀

**Comment by fritsch** [comment]
If all periods stay the same then we have another issue below, namely: out get delay method is not accurate enough and videoplayer auto corrects that.

As Android API for really accurate sync is still a pain until today, please go ahead. I would do it for DTS hd also if possible.

**Comment by thexai** [comment]
> I would do it for DTS hd also if possible.

Honestly with DTS-HD there are absolutely no complaints/issues and I haven't noticed anything either. It just works fine as it is now. In this PR I prefer not to touch anything else.

**Comment by fritsch** [comment]
Okay! Please go ahead.

**Review by fritsch — APPROVED** [review]

**Comment by DecalicatanDecalicatan** [comment]
Hi, 

With the Nexus alpha 2 that incluses this commit,  using a Shield pro 2019 and an avr (Marantz NR 1711), should the Audio video sync setting of the Shield left at 50 ms (default) or the 0ms value is still the "best"  to prevent dropouts ?
Sorry if it's not the place for this kind of question. Delete my message if necessary

**Comment by thexai** [comment]
0 ms is still the "best" but 50 ms works better than before (for 90% of people that stuck at defaults)

**Pull request merged**
