### PR TITLE
[CORE] settings refactor

### PR DESCRIPTION
**Pull request by mad-max**
Hey guys,
as mentioned and discussed in the forums ( http://forum.kodi.tv/showthread.php?tid=189031 ), I have refactored the settings to a new layout.

I left the old settings windows in the code for backwards compatibility, but still this needs some updates in other skin, as the old windows can be opened but are empty.
 I hope this is fine.

ToDo:
- [x] created new settings windows for media and playback
- [x] rearranged the order for general settings.xml
- [x] rearranged platform specific xmls
- [x] updated strings and skin
- [ ] find a final structure for all settings (this is only c&p from here on)
- [ ] update comments in strings.po to point to new settings location (can be done if there is a final structure)

Here we go with a little preview:

screenshot000

screenshot001

screenshot002

Win32 Testbuild can be found here: https://www.dropbox.com/s/ofak23j4h13jalo/KodiSetup-20150309-3487f9f-settings_refactor.exe?dl=0

Any opinions? There is a need for a final structure ;)
Shall the commits be squashed into one?

@Montellese Thanks for your help!

cheers,
mad-max

### CODE REVIEW

**Comment by mad-max** [comment]
@MartijnKaijser  Saw this also, came from auto conversion in visual studio
Had a fix whitspace grinch commit, so should be fine...
I guess it will be squashed later on anyway

**Comment by zag2me** [comment]
That "Media Management" section sticks out a bit due to being 2 words and everything else being 1. Isn't "Media" Enough?

**Comment by mad-max** [comment]
Media Management was the term that came up in the forum discussion.
Of course this can be changed. I created the PR as a base for a discussion on the terms and where to put which setting

**Comment by fritsch** [comment]
/me takes Popcorn and opens the bikeshedding pandora:

Media might be confusing with actual Content. What about Media Settings - as those are "settings" after all?

**Comment by mad-max** [comment]
Again 2 words ;)

**Comment by fritsch** [comment]
What about: Content?

**Comment by mad-max** [comment]
To be honest, I like "Media Management", although it is a two word term

**Comment by mkortstiege** [comment]
Nah, that´s not `Content`. It´s more `Behavior` than anything else. IMO the items have to be re-assigned entirely. Should we open a new forum thread dedicated to this instead of spamming everyone? ;)

**Comment by mad-max** [comment]
@mkortstiege There is a forum thread. See first post of this PR

**Comment by mkortstiege** [comment]
Sorry, puzzled it with another one.

**Comment by jjd-uk** [comment]
Part of the reason for the name Media Management was that as a next step a central "sources" management section for all media types could be added in here, which would probably fit well with Montellese's media import work.

**Comment by zag2me** [comment]
Yep its fine as is, was just commenting that the 1st screenshot looked slightly out of line. Maybe I'm just too obsessed with labels looking similar. I'll bikeshed in the forum thread in future ;)

**Comment by MartijnKaijser** [comment]
@zag2me it might look totally different in other languages.

**Comment by FernetMenta** [comment]
is is less clicks on the remote to get to karaoke than to video settings. not ideal :(

**Comment by mad-max** [comment]
@FernetMenta 
I already thought about rearranging these sections.
What would be the correct layout? At first videos, then music and then other stuff?

**Comment by FernetMenta** [comment]
putting video first makes my life easier :)

BTW: that's the point, I always use expert level

**Comment by mad-max** [comment]
Yeah, guess video goes first...
I'll wait until we have a final structure and then make the appropriate changes

**Comment by mad-max** [comment]
BTW: win32 testbuild online: https://www.dropbox.com/s/ofak23j4h13jalo/KodiSetup-20150309-3487f9f-settings_refactor.exe?dl=0

**Comment by da-anda** [comment]
IMO reshuffling settings categories only makes sense when we rebuild the entire settings tree, so also regroup settings to new categories etc. I also think we might need a third level because it doesn't make much sense to have "Video library", "Video filelist", "Music library" and "Music filelist" in the media section. I would make more sense and also be cleaner if library and filelist would be grouped in a Video and Music node with the possibility to split up the settings into more subgroups.
So I think we should ignore our current technical limitations and rather think about what structure makes most sense.
Also we should already take upcoming features like retroplayer/games and ADSP into acount and find a nice place for them in the structure. And while reshuffling stuff maybe we should add the ability for addons to extend the settings in the same step (or at least prepare everything for it) so that skinners don't have to redo the settings section over and over again (in case we want addons to inject their settings into the main settings, which might make sense when I think of moving core stuff into addons, like airplay maybe).

**Comment by MartijnKaijser** [comment]
we're working in something so this is kinda obsolete

**Pull request closed without merging**
