### PR TITLE
Fix enum formatting for libfmt 6 [backport]

### PR DESCRIPTION
**Pull request by Paxxi**
Backport of #17351
This attempt removes the enums from fmt altogether, fmt never sees an enum,
only ints.

## How Has This Been Tested?

Unit tests pass

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by wsnipex** [comment]
thanks, works for me

**Comment by DaveTBlake** [comment]
But what about  `enable_if_t` being C++14 and not C++11?

**Comment by Paxxi** [comment]
it's defined by us at line 54, it's basically just a shorthand for enable
`template< bool B, class T = void >
using enable_if_t = typename std::enable_if<B,T>::type;`

**Comment by DaveTBlake** [comment]
Failure was FreeBSD
jenkins build this please

**Pull request merged**
