### PR TITLE
fixed: Compile warnings

### PR DESCRIPTION
**Pull request by arnova**

### CODE REVIEW

**Comment by arnova** [comment]
@FernetMenta : Your button

jenkins build this please

**Comment by fritsch** [comment]
@arnova size_t would be correct for the comparison with deque's size() right?

**Comment by arnova** [comment]
@fritsch: Yes didn't realise that. Can change it if you like but all it will ever become is either 1 or 5 so it didn't seem that important.

**Comment by fritsch** [comment]
@arnova if you are already touch it - please do if you can.

**Comment by arnova** [comment]
@fritsch : Updated

**Comment by fritsch** [comment]
Thanks much. Push at will :-)

**Comment by arnova** [comment]
jenkins build and merge

**Pull request merged**
