### PR TITLE
fix font setting reset on skin change 

### PR DESCRIPTION
**Pull request by tamland**
Typo from #7843. No idea how this worked..

Also simplified it a bit by making m_skinReloadSettingIgnore a bool. As everything here should be synchronous there is no need to track which setting is being changed.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@Montellese ping
Jenkins build this please

**Comment by scott967** [comment]
Is this why when I have Estuary font set to non-default (Arial based) and switch skins, the new skin doesn't load, instead Estuary reloads with font set to default.  Then I can switch skins.  I though maybe it was some bug in my skin?

**Comment by Montellese** [comment]
Thanks for the fix. It will probably work with the boolean. IIRC my initial approach was a vector of all setting IDs to be ignored but then realized it's not necessary and I only used the affected setting ID.

Have you tried the cases where changing a setting (e.g. the skin itself) will change the value of several other settings that would all cause a skin reload?

**Comment by tamland** [comment]
^yeah. no issues with that.

**Review by Montellese — APPROVED** [review]

**Review by Paxxi — APPROVED** [review]

**Pull request merged**
