### PR TITLE
[smbdirectory] mark dot files and folders hidden - helix

### PR DESCRIPTION
**Pull request by mkortstiege**
Backport of https://github.com/xbmc/xbmc/pull/6529

### CODE REVIEW

**Comment by topfs2** [comment]
Awesome, as soon as you merge on master please merge this too.

**Comment by topfs2** [comment]
@MartijnKaijser how do you think we should handle this, schedule for 14.3 if it comes or push into 14.2?

**Comment by MartijnKaijser** [comment]
i want to make 14.2 the last one. Merge and Kick a beta2 out with the pending/upcoming fixes and then go for RC.

**Comment by MartijnKaijser** [comment]
Jenkins build this please

**Pull request merged**
