### PR TITLE
[estouchy] exit button should execute the selected shutdown function

### PR DESCRIPTION
**Pull request by ronie**
quit may not be applicable on some platforms, use the selected shutdown function instead.

http://forum.kodi.tv/showthread.php?tid=262145&pid=2418740#pid2418740

### CODE REVIEW

**Comment by ksooo** [comment]
Didn't we have an agreement only to include fixes for Krypton after beta2?

**Comment by ronie** [comment]
perhaps i should've tagged it fix, i dunno..
it fixes the problem, but it's also a behaviour change.

will tag it for v18, np.

**Comment by ksooo** [comment]
Reading what it does, it sounds like a fix to me. We should actually label it "fix" and shove into Krypton i guess. ;-)

**Comment by ronie** [comment]
you mean we should actually read stuff before we comment? ;-)

**Comment by ksooo** [comment]
I mean we should use correct PR labels in the first place. :-)

**Pull request merged**
