### PR TITLE
GUI sounds: hide 'skin default' if skin doesn't come with sounds

### PR DESCRIPTION
**Pull request by tamland**
Fixes http://trac.kodi.tv/ticket/15965

Also changes the name of the option to "Skin built-in", which I think is more accurate description of what it is.

### CODE REVIEW

**Comment by Montellese** [comment]
This is missing proper handling of falling back to a proper value when the setting's value is `SKINDEFAULT` and the user switches from a skin with sound to a skin without sound in which case the `SKINDEFAULT` option isn't part of the list of available options anymore.

I'm not sure how to handle this best as the new skin doesn't have a default sound. Should we just fall back to `OFF` to not enable some arbitrary sound that the user might not like? Or should we fall back to the setting's default value (`resource.uisounds.confluence`)?

**Comment by uNiversaI** [comment]
My 2c here would be to fallback to ```resource.uisounds.confluence```

**Comment by tamland** [comment]
>This is missing proper handling of falling back to a proper value when the setting's value is SKINDEFAULT and the user switches from a skin with sound to a skin without sound in which case the SKINDEFAULT option isn't part of the list of available options anymore.
>
>I'm not sure how to handle this best as the new skin doesn't have a default sound. Should we just fall back to OFF to not enable some arbitrary sound that the user might not like? Or should we fall back to the setting's default value (resource.uisounds.confluence)?

It is handled. If the active have no sounds and `SKINDEFAULT` is selected there will simply be no sounds, same as off. This is how the skin default setting has always worked if the skin does not provide sounds. If we start changing the setting we break what the user has previously chosen. E.g if user changes back to a skin with sounds. 

I don't know any other way of doing this, so I suggest keeping it like it is (fall back to off and simply hidden from settings list) and rather drop the `SKINDEFAULT` feature in J*. The setting is too messy.

**Comment by Montellese** [comment]
And what will the user see in the settings window as a value for that setting?

**Comment by tamland** [comment]
It's blank ofc. Is that what you meant wasn't handled properly?

**Comment by Montellese** [comment]
Yes. Showing a blank (i.e. invalid value) doesn't sound user friendly to me. Quite a few settings change their value when you change to another skin and changing back will not necessarily restore the previously chosen value.

**Comment by tamland** [comment]
Not to me either really. Changed it to reset to default. I think that's better than `off` as user have already made a decision not to have them off at this point. It's more consistent with the other skin settings which resets to default too when you change skin.

**Comment by Montellese** [comment]
But isn't the default value `SKINDEFAULT` which is invalid in those situations?

**Comment by tamland** [comment]
@Montellese I'm not sure I understood you there.. All ok from your side? We should get this in already.

**Comment by Montellese** [comment]
You said you changed the logic to fall back to the default value if the skin doesn't provide any sounds. But isn't the default value `SKINDEFAULT` which doesn't make any sense because the skin doesn't provide any sounds?

**Comment by Montellese** [comment]
Ah sorry the default is `resource.uisounds.confluence`. I'll take another look at the changes (instead of theoretical talk).

**Comment by Montellese** [comment]
Should be good.

**Comment by tamland** [comment]
ok:)

**Comment by tamland** [comment]
jenkins build this plase

**Comment by tamland** [comment]
jenkins build this please

**Pull request merged**
