### PR TITLE
[VideoPlayerAudio] fix audio codec info

### PR DESCRIPTION
**Pull request by afl1**
I removed ResetAudioInfo() to avoid wash out already set audio codec info.

### CODE REVIEW

**Comment by Rechi** [comment]
Please explain what issue you try to fix.

**Comment by afl1** [comment]
In overlay 'Player process info' during playback is 'Audio stream'  shown as "unknown". Removing  this command fix this issue.

**Comment by Rechi** [comment]
I think the correct fix is to add `ResetAudioCodecInfo()` at
https://github.com/xbmc/xbmc/blob/f5314b1211d8dfb9243dee9e2c35ed5576076577/xbmc/cores/VideoPlayer/Process/ProcessInfo.cpp#L55-L64
@FernetMenta correct?

**Comment by FernetMenta** [comment]
nope, decoder needs to set name not in open but after decoder of first frame

**Comment by Rechi** [comment]
@afl1 will you update this with the correct solution?

**Comment by afl1** [comment]
I don't understand. @FernetMenta  told only your suggestion is wrong. But my solution is working. I am using it in my builds.

**Comment by notspiff** [comment]
- do not set name in open
- instead set when first frame is decoded. that is when you know what codec is in actually in use.

As stated above. Seems reasonable no? I am sure fernet has some corner case in mind where codec is not avail/trustworthy from probe.

**Comment by FernetMenta** [comment]
There's two options why I reset codec info at this time:

- I am stupid
- There's a good reason

In case you give the latter a chance, git blame is a good tool:
https://github.com/xbmc/xbmc/pull/12491/commits/fb650f22d4a48d255324be4e12b0b917a3572cba

**Comment by MartijnKaijser** [comment]
Does this need some rework or can we close it?

**Comment by FernetMenta** [comment]
situation is unchanged. this code is wrong has not been updated according to the comments.

**Comment by Rechi** [comment]
superseded with #13900

**Pull request closed without merging**
