### PR TITLE
[cmake] gen_skin_pack move to add_custom_command

### LINKED ISSUE #23778: [cmake][win] TexturePacker executed for every Kodi build
### Describe the bug

Since the merge of PR #22112, every build of Kodi under Visual Studio or from command prompt executes the texture packer even when the skin resources haven't changed and Textures.xbt is already up to date.

This is most noticeable / annoying when starting Kodi for debug: even with everything built and up to date, the texture packer is executed again before Kodi is started.

Looks like the texture packer is launched by the project gen_skin_pack.

Same thing for x64 and UWP, Debug, Release.

### Expected Behavior

Textures.xbt is rebuilt only when a dependency changes.

### To Reproduce

Visual Studio:
- "Build Solution" => texture packer is run unconditionnally
- "Start Debugging" => texture packer is executed another time before Kodi is launched

or

Developer command prompt in kodi build  directory:
cmake --build . --config "Debug" 
cmake --build . --config "Debug" 

The second invocation should not have to build anything but you can see the log of texture packer going through all the images.

### Debuglog

Visual Studio build log: https://paste.kodi.tv/cigewihara.kodi

### Your Environment
Used Operating system:
 - [X] Windows
 - [X] Windows UWP

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Move gen_skin_pack to add_custom_command and generate a "timestamp" file for dependency tracking. This allows the custom command to only be run once, rather than every build. clean in VS also removes timestamp file, allowing for a full clean and full rebuild including running the custom command.

## Motivation and context
Fixes #23778

## How has this been tested?
Win x64 VS full build executes packing, build again doesnt. clean solution and packing is run again as expected after a clean
macos aarch64 makefile. as above with VS solution

## What is the effect on users?
N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by wsnipex — APPROVED** [review]

**Comment by CrystalP** [comment]
It packages only once now but doesn't re-package after skin image updates. Maybe it never did, I don't know.

**Comment by fuzzard** [comment]
The target now has dependencies on theme files and will retrigger a regeneration when they are updated.

**Comment by CrystalP** [comment]
Yes that works great!

Just curious, is there a reason for the gen_skin.timestamp file instead of using the timestamp of the generated Textures.xbt of each skin?
I don't know cmake and whether that makes sense.

**Comment by fuzzard** [comment]
for multi config generators, the actual location of the generated xbt files is unknown at configure time. cmake doesnt know what build type is used (Debug, RelWithDebInfo, Release, etc). Just use a timestamp file in a known location as an indicator so we dont have a target dependency loop. (ie Gen-skins relies on kodi.bin (TARGET output location) which relies on gen-skins)

**Pull request merged**
