### PR TITLE
tools/depends: improve download retry logic and add download target

### PR DESCRIPTION
**Pull request by lrusak**
#22695 (again) 🤷‍♂️ 

I've added a fixup (for squashing) for use with dash shell. I've tested this with `dash`, `bash`, `sh`, and `zsh`.

I used shellcheck and I also used the makefile variable `SHELL = '/usr/bin/dash'`

### CODE REVIEW

**Comment by wsnipex** [comment]
Regression: missing tarballs are not detected / downloaded anymore.
```
wuff@elitebook:~/src/xbmc/tools/depends/target/libdvdnav$ ll
total 16
drwxrwxr-x  2 wuff wuff 4096 Feb 14 06:33 ./
drwxrwxr-x 85 wuff wuff 4096 Feb 14 06:26 ../
-rw-rw-r--  1 wuff wuff  365 Feb 14 06:26 LIBDVDNAV-VERSION
-rw-rw-r--  1 wuff wuff 1884 Feb 14 06:26 Makefile
wuff@elitebook:~/src/xbmc/tools/depends/target/libdvdnav$ make download 
download libdvdnav-6.1.1-Next-Nexus-Alpha2-2.tar.gz attempt 1
wuff@elitebook:~/src/xbmc/tools/depends/target/libdvdnav$ ll
total 148
drwxrwxr-x  2 wuff wuff   4096 Feb 14 06:33 ./
drwxrwxr-x 85 wuff wuff   4096 Feb 14 06:26 ../
-rw-rw-r--  1 wuff wuff 128547 Feb 14 06:33 libdvdnav-6.1.1-Next-Nexus-Alpha2-2.tar.gz
-rw-rw-r--  1 wuff wuff    173 Feb 14 06:33 libdvdnav-6.1.1-Next-Nexus-Alpha2-2.tar.gz.sha512
-rw-rw-r--  1 wuff wuff    365 Feb 14 06:26 LIBDVDNAV-VERSION
-rw-rw-r--  1 wuff wuff   1884 Feb 14 06:26 Makefile
wuff@elitebook:~/src/xbmc/tools/depends/target/libdvdnav$ make download 
make: Nothing to be done for 'download'.
wuff@elitebook:~/src/xbmc/tools/depends/target/libdvdnav$ rm libdvdnav-6.1.1-Next-Nexus-Alpha2-2.tar.gz
wuff@elitebook:~/src/xbmc/tools/depends/target/libdvdnav$ ll
total 20
drwxrwxr-x  2 wuff wuff 4096 Feb 14 06:33 ./
drwxrwxr-x 85 wuff wuff 4096 Feb 14 06:26 ../
-rw-rw-r--  1 wuff wuff  173 Feb 14 06:33 libdvdnav-6.1.1-Next-Nexus-Alpha2-2.tar.gz.sha512
-rw-rw-r--  1 wuff wuff  365 Feb 14 06:26 LIBDVDNAV-VERSION
-rw-rw-r--  1 wuff wuff 1884 Feb 14 06:26 Makefile
wuff@elitebook:~/src/xbmc/tools/depends/target/libdvdnav$ make download 
make: Nothing to be done for 'download'.
wuff@elitebook:~/src/xbmc/tools/depends/target/libdvdnav$ ll
total 20
drwxrwxr-x  2 wuff wuff 4096 Feb 14 06:33 ./
drwxrwxr-x 85 wuff wuff 4096 Feb 14 06:26 ../
-rw-rw-r--  1 wuff wuff  173 Feb 14 06:33 libdvdnav-6.1.1-Next-Nexus-Alpha2-2.tar.gz.sha512
-rw-rw-r--  1 wuff wuff  365 Feb 14 06:26 LIBDVDNAV-VERSION
-rw-rw-r--  1 wuff wuff 1884 Feb 14 06:26 Makefile
wuff@elitebook:~/src/xbmc/tools/depends/target/libdvdnav$ make
rm -rf native; mkdir -p native
cd native; tar /home/wuff/src/xbmc/tools/depends/target/libdvdnav/libdvdnav-6.1.1-Next-Nexus-Alpha2-2.tar.gz
tar: Old option 'f' requires an argument.
Try 'tar --help' or 'tar --usage' for more information.
make: *** [Makefile:41: native] Error 2
```

**Comment by lrusak** [comment]
The last error is legit and is due to our inconsistent use of `RETRIEVE_TOOL_FLAGS`.

Why would you have the hash and not the tarball?

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
@wsnipex can you please have a look again?

**Comment by wsnipex** [comment]
the regression is still there.  Why don't you do something like https://github.com/wsnipex/xbmc/commit/72f14eb71b44167c37ae70480f0e28bcb304821f which achieves the same kind of logging you seem to be after?

**Comment by lrusak** [comment]
> wsnipex@72f14eb

Please explain your use-case. Why would the hash file exist without the tarball? We should only have a hash file when the downloaded file is known to be good.

**Comment by wsnipex** [comment]
the use case is simple: your change breaks the fundamental reason for the hash sums.
Changed tarballs are not even detected anymore:
```

wuff@elitebook:~/src/xbmc/tools/depends/target/libdvdnav$ sha512sum -c libdvdnav-6.1.1-Next-Nexus-Alpha2-2.tar.gz.sha512 
libdvdnav-6.1.1-Next-Nexus-Alpha2-2.tar.gz: FAILED
sha512sum: WARNING: 1 computed checksum did NOT match
wuff@elitebook:~/src/xbmc/tools/depends/target/libdvdnav$ make download
make: Nothing to be done for 'download'.

```

**Comment by lrusak** [comment]
> the use case is simple: your change breaks the fundamental reason for the hash sums.
> 
> Changed tarballs are not even detected anymore:
> 
> ```
> 
> 
> 
> wuff@elitebook:~/src/xbmc/tools/depends/target/libdvdnav$ sha512sum -c libdvdnav-6.1.1-Next-Nexus-Alpha2-2.tar.gz.sha512 
> 
> libdvdnav-6.1.1-Next-Nexus-Alpha2-2.tar.gz: FAILED
> 
> sha512sum: WARNING: 1 computed checksum did NOT match
> 
> wuff@elitebook:~/src/xbmc/tools/depends/target/libdvdnav$ make download
> 
> make: Nothing to be done for 'download'.
> 
> 
> 
> ``` 

I'm not sure I follow. Why would the hash exist if the tarball was bad? Why would the tarball change?

**Review by wsnipex — CHANGES_REQUESTED** [review]
the main purpose of the hashing is to verify the tarball has not been modified **at time of unpacking/building**, not only at download time.
You could have downloaded the tarball a while ago and it could have changed on disk because of filesystem/disk corruption or malicious activity.

**Comment by lrusak** [comment]
> the main purpose of the hashing is to verify the tarball has not been modified **at time of unpacking/building**, not only at download time.
> 
> You could have downloaded the tarball a while ago and it could have changed on disk because of filesystem/disk corruption or malicious activity.

Updated.

**Comment by wsnipex** [comment]
looks much better. please pick https://github.com/wsnipex/xbmc/commit/fcb8153466d6e41b8e62f99eac567846b9d11ccf

**Comment by lrusak** [comment]
> looks much better. please pick [wsnipex@fcb8153](https://github.com/wsnipex/xbmc/commit/fcb8153466d6e41b8e62f99eac567846b9d11ccf) and [wsnipex@89abb78](https://github.com/wsnipex/xbmc/commit/89abb78a584905d5337af2a7459554eaef5ac0e7)

Picked and squashed. Thanks!

**Review by wsnipex — APPROVED** [review]

**Pull request merged**
