### PR TITLE
CHG: [imx] extend RENDER_BYPASS and cleanup rendering

### PR DESCRIPTION
**Pull request by koying**
/cc @smallint @wolfgar @fritsch 

This cleans up the imx rendering by extending the RENDER_BYPASS mechanism.
No change in functionality

### CODE REVIEW

**Comment by koying** [comment]
jenkins build this please

**Comment by koying** [comment]
@FernetMenta Let's try to be constructive.
1) What is specifically what is bothering you with extending the callback mechanism which exists for a long time ?
Needless to say, having a global pointer to the codec inside the VideoRenderer, as is the case now, is not acceptable
2) If I understand correctly, you want a specific "BYPASS" renderer, right?
I find it hardly feasible for the following reasons:
- The VideoRenderer is a singleton created platform-wise (based on ifdef's) before creating the codecs, and thus not at all based upon the render format returned by the codec
- All platforms, including those using the BYPASS format, fall backs to a standard ffmpeg+YUV420P rendering path
- The BYPASS format is device-specific (e.g. imx, amlogic) but cross-platform (android + linux)

Considering this, please outline in details the architecture you'd like to be put in place for codecs which render directly to hardware in a non-generic fashion.

**Comment by FernetMenta** [comment]
Those callbacks may have existed for quite some while but that does not mean that they were implemented correctly. They are a specialization, hence having those in BaseRenderer is wrong.
Currently RenderManager is global but this will change because it is bad design as well. Then a codec can't register for callback anymore.

The problem is already solved, no need to reinvent the wheel. Have a look at DXVA, VDPAU, or VAAPI. They pass a refcounted object to renderer which can be used instead of the callbacks. Those objects are no global pointers.

**Comment by FernetMenta** [comment]
Another reason for the callbacks being wrong is that there can be multiple decoders at the same time.

**Comment by koying** [comment]
Am I correct understanding that you prefer a bunch of ifdefs and non-generic code in the renderer (plus the need to alter the video renderer for each added needing codec, plus dependency of the renderer on the codecs) rather than a generic callback interface?
I wouldn't quite agree with you on this.

Re multiple decoders, in which code path? 
AFAIK, 1 player = 1 video codec = 1 renderer, and we don't support multiple players per design (see CApplicationPlayer).

**Comment by FernetMenta** [comment]
> Am I correct understanding that you prefer a bunch of ifdefs and non-generic code in the renderer

absolutely not. the ifdefs should go away in favour of a hierarchy with specialization at the right level.

> Re multiple decoders, in which code path?

one example is when switching pvr channels. dvdplayer opens a new decoder while render still processes frames of the last channel. another example is a change is sps mid stream which may require to open a new decoder.

**Comment by koying** [comment]
Ok, so I see a lot of "should" and "will" to a pretty big overhaul of the rendering part ;)
Any concrete plans or is it only an architectural wish-list so far?

**Comment by koying** [comment]
BTW, the "switching pvr channe" = multiple decoders" is a player issue rather than a feature. You cannot assume an h/w decoder supports multiple instances, especially on embedded.
It's a recurring issue with the amlogic codec specifically.

**Comment by FernetMenta** [comment]
> BTW, the "switching pvr channel = multiple decoders" is a player issue rather than a feature.

it is not. this design was there before the ports to the embedded platforms. the problems is that many things went wrong with those ports because platform devs did not fully understand the architecture.

If you took a look into DXVA, you would have seen that it does cope with the limitation of having just a single instance of a hw decoder.

**Comment by koying** [comment]
DXVA supports multiple decoder instances and our codec maintains a refcounted list of them, isn't it?
On embedded, you must assume 1 max instance of the h/w decoder (not the Kodi one).

Anyway, back to the real question: Is there a plan?
If so, I'd just create a new PR for the dead code.

**Comment by FernetMenta** [comment]
> DXVA supports multiple decoder instances and our codec maintains a refcounted list of them, isn't it?

not sure if I understand correctly but I think this is correct. in other words: the key is that player can instantiate as many DXVA decoders as it wants to, the DXVA class maintains a hw decoder context which keeps track of the actual hw decoder. means the limitation (or specialisation) in encapsulated in this class.

> Anyway, back to the real question: Is there a plan?

Depends on the definition of plan. Regarding the callbacks which are topic here: yes, as already mentioned, they'll go away from the platform independent code. There is a mechanism in place for communication from renderer in direction of codec.

**Comment by fritsch** [comment]
@FernetMenta What you suggest needs major rework on all platforms. Do you see a "middle step" on that way, where we can get the code @koying is doing in?

It improves and arranges especially IMX stuff in a nice way - so I would not like to loose that work, for some vague point in the future?

**Comment by FernetMenta** [comment]
> What you suggest needs major rework on all platforms

that is not correct. what rework? I don't see anything which needs to be done on the platforms I listed including RPi.

**Comment by koying** [comment]
jenkins build this please

**Comment by koying** [comment]
FWIW, if https://github.com/xbmc/xbmc/commit/d5353436383332c293ed4cfdf6326a9a233d4c93 is ok just for rpi, all this BaseRenderer drama is just BS, imo.
Something personal, I suspect...

**Comment by koying** [comment]
jenkins build this please

**Comment by koying** [comment]
jenkins build this please

**Comment by fritsch** [comment]
@smallint @wolfgar please have a look. This generalizes RENDER_BYPASS  and brings IMX in line. I consider this as an intermediate step in our "to be defined" vision of the codec / rendering.

**Comment by wolfgar** [comment]
Sorry I did not dare to comment given the first exchanges...
To me, it is useful for any platforms that don't use opengl(es) for video rendering (and a bunch of linux embedded targets that use v4l2 or direct/custom fb writing can find their place in it)
It is cleaner as it enables to have all specific stuff (decoding and rendering) in a dedicated place (same file here) instead of spreading some specific code with preprocessor guards in a generic file.
And to be honest, 2 years ago when I coded the first port for iMX6, I began trying to use RENDER_BYPASS  but realized available hooks were not enough and moved to adding specific code in LinuxRendererGLES by looking at the way some other platforms were implemented...

I only have one minor question that I have just stated in the commit ...

Regards

**Comment by fritsch** [comment]
I actually tried that code and yeah for now everything I get is a blackscreen. I tried on latest OpenELEC with this PR included. Basically all hw accelerated files just display as completely black, you can see player controls, but that's it.

It works for you @wolfgar and @koying on IMX?

**Comment by koying** [comment]
@wolfgar Time permitting would you mind confirming it fails for you, too, to discard an OE specific issue?
Thanks

**Comment by smallint** [comment]
In general I like the changes and first of all getting rid of the IMX specific path. I haven't tested it yet and I will not be able to test it until Thursday next week. Will do it then ...

**Comment by wolfgar** [comment]
Hi @koying : sorry I was out for the pentecost WE, just back home , have tested your current branch and works fine...

**Comment by fritsch** [comment]
@wolfgar This PR was given no chance for including. The callback architecture was called "outdated way of doing things" and "remanent of the past". 

According to some not written down plan, all hw decoders (that don't fit) should be rewritten and work like MMal decoder. Everything that does not fit this design has no chance to reach kodi's base.

This we were told on IRC.

**Comment by FernetMenta** [comment]
This is not entirely the truth. You know this so please refrain from posting such comments in this space.

**Comment by fritsch** [comment]
Would be nice to get an update of _the_ truth, cause actually that's what I
got of the discussion. Happy for an update to adust my pov.

Thx much in advance.
Am 25.05.2015 11:30 vorm. schrieb "Rainer Hochecker" <
notifications@github.com>:

**Comment by FernetMenta** [comment]
Transforming an architecture into something which can cope with current and future requirements can't be done in a single day. As it turned out that this is not wanted I gave up this endeavour on this branch. So feel free to go this way.

**Comment by fritsch** [comment]
We all want to be capable of future requirements. And we asked several
times to draw us the vision, so that we can follow this step by step while
constantly improving given code.

Nothing wrong with a vision, but we need more communications.
Am 25.05.2015 12:02 nachm. schrieb "Rainer Hochecker" <
notifications@github.com>:

**Comment by koying** [comment]
jenkins build this please

**Pull request closed without merging**
