### PR TITLE
add CODEOWNERS file to help selecting reviewers

### PR DESCRIPTION
**Pull request by lrusak**
As discussed at devcon this adds the CODEOWNERS file. I encourage all core devs to add their relevant sections. There will be a lot of code that is missing maintainers.

this fixes https://github.com/xbmc/board/issues/114

### CODE REVIEW

**Review by yol — APPROVED** [review]
I will add myself to Wayland afterwards

**Comment by ksooo** [comment]
@lrusak could you please add:

```
/xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamPVR*.* @ksooo
/xbmc/interfaces/builtins/PVR*.* @ksooo
/xbmc/interfaces/json-rpc/PVR*.* @ksooo
/xbmc/guilib/GUIRangesControl.* @ksooo
/xbmc/guilib/guiinfo/GUIInfoProvider.h @ksooo
/xbmc/guilib/guiinfo/GUIInfoProviders.* @ksooo
/xbmc/guilib/guiinfo/IGUIInfoProvider.h @ksooo
/xbmc/pvr/** @ksooo
/xbmc/settings/SettingsComponent.* @ksooo 
```

**Comment by DaveTBlake** [comment]
What is the best way to handle the initial creation of this file - each do our own PR of this file to add ownership, or post here and @lrusak will do it??

**Comment by garbear** [comment]
I'll cover
```
/xbmc/cores/RetroPlayer/** @garbear
/xbmc/games/** @garbear
/xbmc/input/** @garbear
/xbmc/peripherals/** @garbear
```

**Comment by lrusak** [comment]
I don't really want to add everyone myself 😝 I've added some commits for the requested people but I'd rather merge this and have others create their own PR's 😸

**Comment by garbear** [comment]
```
/.github/CODEOWNERS @lrusak
```

**Comment by yol** [comment]
GitHub docs say we don't need `/**`, so I'm going to remove that part to make it a bit easier on the eyes

**Comment by yol** [comment]
Let's see what happens... ;-)

**Pull request merged**
