### PR TITLE
[IMX] CodecIMX updates (Krypton)

### PR DESCRIPTION
**Pull request by mk01**
## Description

fixes / updates / Krypton changes - since the previous commit.

## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by FernetMenta** [comment]
please PR to master first

**Comment by mk01** [comment]
@FernetMenta 
https://github.com/xbmc/xbmc/pull/11299

**Comment by fritsch** [comment]
@mk01 do you feel the stuff is squashed that way so that you could savely bisect (if there are errors)?

**Comment by mk01** [comment]
@fritsch 

it is now, yes.

**Comment by fritsch** [comment]
Thx much. If you say yes on the on the other PR - we will push it.

**Comment by fritsch** [comment]
fine with @FernetMenta and me. @MartijnKaijser your button. Even as we don't have an imx jenkins we should build and merge to see if it does not break anything else.

**Pull request merged**
