### PR TITLE
Enable gzip support

### PR DESCRIPTION
**Pull request by zixelmike**
Enable gzip support, some users need gzip support for getting playlists.

## Description

Enable gzip support

## Motivation and Context

This change need for Superpomoyka users to request playlists

## How Has This Been Tested?
I compile on debian, it`s work perfect! =)

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by afedchin** [comment]
> Если ваш плеер не поддерживает gzip, уберите ".tag" из пути к плейлисту, и все заработает.
 
if your player doesn't support gzip, just remove ".tag" from the playlist url and all will work.

**Comment by bol-van** [comment]
EPG will not work with untagged playlist.
There's chance that "pomoyka" will enforce gzip compression on everything.

**Comment by candrews** [comment]
I don't think accept encoding should be set to "gzip" - it would be better to tell curl to accept all encodings it supports. See https://curl.haxx.se/libcurl/c/CURLOPT_ACCEPT_ENCODING.html

**Comment by bol-van** [comment]
> I don't think accept encoding should be set to "gzip" - it would be better to tell curl to accept all encodings it supports. See https://curl.haxx.se/libcurl/c/CURLOPT_ACCEPT_ENCODING.html

> To aid applications not having to bother about what specific algorithms this particular libcurl build supports, libcurl allows a zero-length string to be set ("") to ask for an Accept-Encoding: header to be used that contains all built-in supported encodings. 

```
  if (m_acceptencoding.length() > 0)
    g_curlInterface.easy_setopt(h, CURLOPT_ACCEPT_ENCODING, m_acceptencoding.c_str());

```

We cant just add empty string. Further code will not set the option at all.
If we explicitly specify the list  there's change libcurl does not support something

**Comment by bol-van** [comment]
Or we need to remove this line :
` if (m_acceptencoding.length() > 0)
`

**Comment by zixelmike** [comment]
Updated....

**Comment by pkerling** [comment]
Is there any reason not to accept all supported encodings all the time? @rechi @wsnipex?

**Comment by wsnipex** [comment]
Having all supported encodings as default makes sense, but I suspect there are reasons to specifically set a single encoding to accept. Scrapers and addon repo do that, but I didn't read up on why. @notspiff maybe?

**Comment by bol-van** [comment]
Another solution was discovered.
https://kodi.wiki/view/HTTP

its possible to add options to the url.
like : "http://something/something|encoding=gzip"

**Comment by bol-van** [comment]
I guess using encoding can break byte ranges and make file not seakable.
I dont know if CurlFile is used for http streaming. 
Even if so  most of the servers will not encode media data because its useless. But who knows there may be exceptions

**Comment by candrews** [comment]
> I guess using encoding can break byte ranges and make file not seakable.

Nope. For range requests, the server ignores the `Accept-Encoding` request header. The range is specified based on uncompressed response bytes (no compressed aka encoded ones). To indicate to the server that a byte range request should get a compressed response, the request shiuod 

I dont know if CurlFile is used for http streaming.
Even if so most of the servers will not encode media data because its useless. But who knows there may be exceptions

**Comment by bol-van** [comment]
Then it should be safe to enable all encodings by default.
But if we just remove "if" it won't be possible to disable encodings.
May be its reasonable to do something like this :

```
CCurlFile::CCurlFile
{
.....
m_acceptencoding = "all";
}

if (m_acceptencoding.length() > 0)
    g_curlInterface.easy_setopt(h, CURLOPT_ACCEPT_ENCODING, m_acceptencoding=="all" ? "" : m_acceptencoding.c_str());

```

"all" will be reserved word . to remove encoding caller can SetAcceptEncoding("")
or may be add another bool member to indicate "default all" state

**Pull request closed without merging**
