### PR TITLE
fix to use the selected player after PR 8525

### PR DESCRIPTION
**Pull request by wiromare**
this should solve two issues after PR 8525
- the player selected in the contextmenu "Play using..." it's never used
- the default player set with <defaultplayer> in advancedsettings.xml it's ignored

@FernetMenta

### CODE REVIEW

**Comment by FernetMenta** [comment]
thanks!
jenkins build this please

**Comment by wiromare** [comment]
ouch, sorry for the mistake

thx @notspiff

**Comment by FernetMenta** [comment]
@wiromare what did change? force push seems to have stopped jenkins

**Comment by wiromare** [comment]
i pushed this commit 
https://github.com/wiromare/xbmc/commit/c5ea6cb503d2f8835e85ed40a4090b515be32c0c

then i squashed the commits since jenkins was already stopped

**Comment by FernetMenta** [comment]
jenkins build this please

**Pull request merged**
