### PR TITLE
[infomanager] add System.HasHiddenInput info bool

### PR DESCRIPTION
**Pull request by mkortstiege**
Adds `System.HasHiddenInput` info bool. Returns true in case the active keyboard or numeric dialog requested a pin/password input.

/cc @phil65, @ronie

### CODE REVIEW

**Comment by ronie** [comment]
whats's the use case for this one?

**Comment by mkortstiege** [comment]
> whats's the use case for this one?

@phil65 requested it. Not sure about the actual use-case ;)

**Comment by ronie** [comment]
ah, you're just the code monkey ;-p

**Comment by akva2** [comment]
wrong what with HasHiddenInput ?

**Comment by mkortstiege** [comment]
> wrong what with HasHiddenInput ?

Not sure i totally get this comment ;) but i assume you mean the terminology. Will change in case.

**Comment by Paxxi** [comment]
Maybe IsInputHidden or IsInputVisible ?

**Comment by mkortstiege** [comment]
> Maybe IsInputHidden or IsInputVisible ?

Already changed it to `HasHiddenInput` for now.

**Comment by Paxxi** [comment]
okidoki :)

**Comment by phil65** [comment]
Use-case is to hide autocompletion for hidden input. (script feature, see https://www.youtube.com/watch?v=G1o-mmt4RBg )

**Comment by ronie** [comment]
cool. thx for the info!

**Comment by phil65** [comment]
just tested, seems to work fine. Thx!

**Pull request merged**
