### PR TITLE
Add static analysis tests

### PR DESCRIPTION
**Pull request by notspiff**
I did this for work and I figured I might as well offer it up here as well.

This adds static analysis tests using clang-check and cppcheck to the buildsystem.
You can execute these using ctest -C cppcheck|clang-check|analyze

To have informative pass/failure states shell scripts need to sit between the invocation and the testing tool. This sadly makes it tied to linux or osx.

Integration on kodi side is very quick so I expect refinements need to be done. But first let's see if there is interest..

### CODE REVIEW

**Comment by Paxxi** [comment]
Looks like a good idea to me. Visual Studio has similar passing by /analyze so we can probably add it on windows that way and they might catch different issues

**Comment by notspiff** [comment]
yup.

**Comment by Rechi** [comment]
@notspiff bluray build commit has to be dropped

**Comment by notspiff** [comment]
would have been autor.dropped on pull, but anyways, rebased.

**Comment by wsnipex** [comment]
nice! Mind adding it to https://github.com/xbmc/xbmc/blob/master/tools/buildsteps/linux64/run-tests and  https://github.com/xbmc/xbmc/blob/master/tools/buildsteps/osx64/run-tests ?

**Comment by notspiff** [comment]
i do not think that is a good idea. it easily takes 4h to execute.

**Comment by wsnipex** [comment]
heh, I kinda underestimated that :)

**Comment by MartijnKaijser** [comment]
If we could dump the results somewhere we can run it once a week during the night

**Comment by notspiff** [comment]
uploading the ctest results to jenkins rather than 'dumping them somewhere' sounds like a better idea to me ;)

**Comment by wsnipex** [comment]
good to go?

**Pull request merged**
