### PR TITLE
Add settings to control notification rumble duration and strength

### PR DESCRIPTION
**Pull request by garbear**
I've added some fun settings that let you control the notification rumble. A forum user requested a "classier" rumble feel, so this lets people experiment with different rumble behaviours.

It might not be desirable to include these extra settings in the final build. However, I would like feedback from several people before hard-coding these values. Maybe @MilhouseVH can put out a couple builds with this patch?

rumble settings

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Sure, I'll add it in the next few builds. I added your latest updates in the most recent #0830 build, hopefully they're working as intended (no controllers here).

**Comment by MilhouseVH** [comment]
Ok this doesn't apply cleanly on top of #10364 (along with https://github.com/kodi-game/peripheral.joystick/pull/50) that I included in #0830 so I'll drop those in order that this can be tested.

**Comment by garbear** [comment]
@MilhouseVH I fixed the conflict and updated the PR. Also, I split the joystick fixes PR (#10364) into two, the second being the unrelated improvements (#10371). All three open joystick PRs should apply cleanly without conflicts.

**Comment by MilhouseVH** [comment]
Thanks - 10364+10370+10371+PR50 all apply cleanly now. I'll try a test build and post again if there are any snags, otherwise this will all be in the next build.

**Comment by garbear** [comment]
thanks for being awesome

**Comment by AfzalivE** [comment]
Any chance this will be merged into the next beta? I can help if there's something that's needed since I have interest in this PR.

**Comment by garbear** [comment]
No, I think I'm going to hardcode these values at 50% weak motor for 250ms. The settings are merged in my RetroPlayer builds if you want to experiment

**Comment by AfzalivE** [comment]
Sweet! So hopefully this gets merged to master before final Kodi 17. Thanks @garbear!! Appreciate your work.

**Comment by garbear** [comment]
Superseded by #10929

**Pull request closed without merging**
