### PR TITLE
[video] Add TV show artwork to episodes/seasons with their own "fanart".

### PR DESCRIPTION
**Pull request by rmrector**
This block of code adds artwork from the parent TV show to episodes and seasons, and `item.HasArt("fanart")` seems intended to run it only if the TV show artwork hasn't yet been added. But these days, episodes and seasons can have their own artwork, "fanart" included, so this check isn't quite accurate.

For skins this means it's difficult to get TV show artwork from episodes or seasons that have their own fanart, as this prevents _ListItem.Art(tvshow.*)_ and _Player.Art(tvshow.*)_ from being populated.

This change updates it to check against the full "tvshow.fanart", restoring the intended behavior.

### CODE REVIEW

**Comment by Montellese** [comment]
I don't fully know how the thumbloader and the artwork cache etc. works but this should be ok AFAICT.

**Comment by MilhouseVH** [comment]
This fix looks good, although I'm having trouble understanding what the code is actually doing, so maybe an example will help clarify.

Atrwork for an episode without episode fanart (with or without this PR):
```
            "art": {
              "season.poster": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/TVShows/Brass Eye/season01-poster.jpg/",
              "thumb": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/TVShows/Brass Eye/Season 1/Brass Eye S01E06-thumb.jpg/",
              "tvshow.banner": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/TVShows/Brass Eye/banner.jpg/",
              "tvshow.clearart": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/TVShows/Brass Eye/clearart.png/",
              "tvshow.clearlogo": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/TVShows/Brass Eye/logo.png/",
              "tvshow.fanart": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/TVShows/Brass Eye/fanart.jpg/",
              "tvshow.landscape": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/TVShows/Brass Eye/landscape.jpg/",
              "tvshow.poster": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/TVShows/Brass Eye/poster.jpg/"
            },

```
Once episode fanart is added, without this PR the other `tvshow` artwork types disappear:
```
            "art": {
              "fanart": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/TVShows/Brass Eye/Season 1/Brass Eye S01E06-fanart.jpg/",
              "season.poster": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/TVShows/Brass Eye/season01-poster.jpg/",
              "thumb": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/TVShows/Brass Eye/Season 1/Brass Eye S01E06-thumb.jpg/"
            },
```
However with this PR, all artwork is present as expected:
```
            "art": {
              "fanart": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/TVShows/Brass Eye/Season 1/Brass Eye S01E06-fanart.jpg/",
              "season.poster": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/TVShows/Brass Eye/season01-poster.jpg/",
              "thumb": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/TVShows/Brass Eye/Season 1/Brass Eye S01E06-thumb.jpg/",
              "tvshow.banner": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/TVShows/Brass Eye/banner.jpg/",
              "tvshow.clearart": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/TVShows/Brass Eye/clearart.png/",
              "tvshow.clearlogo": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/TVShows/Brass Eye/logo.png/",
              "tvshow.fanart": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/TVShows/Brass Eye/fanart.jpg/",
              "tvshow.landscape": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/TVShows/Brass Eye/landscape.jpg/",
              "tvshow.poster": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/TVShows/Brass Eye/poster.jpg/"
            },
```

**Comment by MilhouseVH** [comment]
Kind of wondering if this also merits a JSON API bump (minor) - even though it's not touching any JSON code it is changing (for the better) the JSON results.

**Comment by Razzeee** [comment]
+1 on the json api bump

**Comment by rmrector** [comment]
Took a stab at writing a better description. Milhouse's example is perfect, and skin access behaves the same with *ListItem.Art()*.

**Comment by rmrector** [comment]
Whoops, I had assumed the API version bump would be done when this was merged in, but looking through other PRs that's generally not the case.

Rewrote history to bump JSON API minor version.

**Comment by hudokkow** [comment]
jenkins build this please

**Comment by rmrector** [comment]
Jenkins failed on Linux 64bit only; I took a look at the log but didn't see any error message other than the failed status. I came to take another look at it but now it's gone.

Is there anything I need to do for this?

**Comment by rmrector** [comment]
Can this be merged in?

**Comment by rmrector** [comment]
Could someone merge this in, please?

I understand this is a small, obscure bug, but a bug nonetheless and should be fixed, especially since that fix is right here just waiting for someone to merge it in, and no one has expressed any concerns with it.

If this won't be merged in, or at least not for Krypton, could you tell me why? I am a new contributor to this community and would appreciate any help from veterans or Team Kodi members on what I may be missing.

**Comment by phil65** [comment]
+1 for merge. I think this can get labelled as a fix, from a skinner´s perspective the current behaviour doesnt make sense.

**Comment by rmrector** [comment]
Great, thanks guys!

**Pull request merged**
