### PR TITLE
Various CMatrixGL optimizations

### PR DESCRIPTION
**Pull request by MaxKellermann**

### CODE REVIEW

**Comment by MaxKellermann** [comment]
@FernetMenta sure, added a commit.

**Comment by FernetMenta** [comment]
@MaxKellermann can you move it too? The class belongs to rendering, not guilib

**Comment by MaxKellermann** [comment]
Yes. Do you want it in `rendering/` or `rendering/gl/`? The latter sounds better to me, but then `rendering/gles/CMakeLists.txt` needs to refer to `../gl/MatrixGL.cpp`, which looks strange. But the former is strange as well, because `rendering/*.cpp` should be agnostic to the rendering backend.
In general, I don't like the strict distinction between OpenGL and GLES in the Kodi code base. These are just different flavors of the same thing with not-so-big differences. There's so much duplicated code in Kodi, which is unnecessary and fragile, and that has led to bugs in the past.
(I had a discussion with you about merging OpenGL and GLES code a while ago (https://github.com/xbmc/xbmc/pull/9390#issuecomment-198717638) and you disagreed strongly that merging duplicate OpenGL/GLES code should be done. Just in case you changed your mind meanwhile: I'd be glad to help with the cleanup.)

**Comment by FernetMenta** [comment]
In order not to complicate this PR I'd say move it to rendering/ for now.
The other discussion would just unnecessarily delay this PR.

**Comment by MaxKellermann** [comment]
Jenkins failure on WIN-64 ("PDB API call failed") not related to this PR - this PR doesn't even affect Windows.
@FernetMenta my latest force-push moves the source to `rendering/` as requested.

**Comment by FernetMenta** [comment]
Thanks! build error unrelated

**Comment by gelotus** [comment]
@MaxKellermann (https://trac.kodi.tv/ticket/17919)

**Comment by FernetMenta** [comment]
@MaxKellermann you can log on to trac with your forum account. not sure if you have one

**Comment by MaxKellermann** [comment]
Thanks, that works.

**Pull request merged**
