### PR TITLE
[android] simplify versioning

### PR DESCRIPTION
**Pull request by Rechi**
## Description
Make version bumps for android less error prone.
Also automatically increment versionCode on android for aarch64 by one. This is needed that aarch64 devices download the aarch64 version from the play store.

## Motivation and Context
@MartijnKaijser you will know
For the others, he accidentally increased versionCode for 17.5 to a greater number then the versionCode for master.

## How Has This Been Tested?
checked versionCode for arm and aarch64

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
The addon api is completely meant to be unrelated to the version code for Android or the version number in the core code however since then it has been abused for whatever. We shouldn't build on that any further

**Comment by Rechi** [comment]
It's abused the same way for AppxManifest.xml on windows.
Possible improvement would be changing VERSION_CODE to a version in format major.minor.patch and use that one for android and windows package versioning.

**Comment by MartijnKaijser** [comment]
Sounds good

**Comment by MartijnKaijser** [comment]
@Rechi would be nice if we would also get this in Krypton to prevent further fuck ups

**Comment by Rechi** [comment]
updated
will do the windows packaging changes later

**Comment by Rechi** [comment]
@MartijnKaijser IMO this is ready (and easy for backporting), windows part will come in a separate PR.

**Comment by MartijnKaijser** [comment]
Would be good for backporting yes.

**Pull request merged**
