### PR TITLE
added: also hide thumbs for unwatched episodes if option to show plot is off

### PR DESCRIPTION
**Pull request by notspiff**
requested in forums at some point. ref @da-anda

### CODE REVIEW

**Comment by Montellese** [comment]
I don't use the setting so I won't comment on it.

But if we change the behaviour we should probably also change the setting's label and description (and maybe even its identifier).

**Comment by notspiff** [comment]
absolutely. i just did the intial code so you guys can choose whether to bundle or use another setting.

**Comment by da-anda** [comment]
thanks, will test over the weekend. I had bookmarked the commit in your branch but never got to it (just like basic MKA support with the ffmpeg based tagreader).

Might be a good candidate to be tested for side effects on a bigger audience (aside from the settings implementation/naming etc). @MilhouseVH, something for your builds?

**Comment by MartijnKaijser** [comment]
bundled with current setting for hide plot makes most sense. thx :)

**Comment by da-anda** [comment]
Thanks @MilhouseVH for adding it to your PI builds. Just tested it and even tough it's working in general, it's not working correctly. In case a TV-show has no watched Episode (or probably also some unwatched episodes) NO artwork for this TV-show will show up anywhere in the skin. No TV-show poster/fanart, no season poster/fanart etc, nothing. So I think there needs to be an explicit check if the current fileItem is a single episode and neither a TV-show or season.

@uNiversaI yep, will be needed, no idea how it should look like (needs to be symbolic and don't contain text)

**Comment by uNiversaI** [comment]
I was looking for a better image like one person whispering to another, but so far couldnt find a decent image in public domain... But the Idea would be simalr to this. Blur that image and overlay a couple of things over. Like:

defaultepisodehidden

The image I used there is from a episode of Dexter taken from tvdb.

Just a rough thought.

**Comment by jjd-uk** [comment]
Rather than spam here, let's discuss what **DefaultEpisodeHidden.png** should be at http://forum.kodi.tv/showthread.php?tid=130587&page=7

**Comment by uNiversaI** [comment]
Fine with me.

**Comment by HitcherUK** [comment]
> bundled with current setting for hide plot makes most sense. thx :)

Not if you want to see plots for movies but hide thumbs for episodes though.

IMO it should be a separate option altogether.

**Comment by NedScott** [comment]
Any change we can merge this as-is for v16? It apparently still works in the @MilhouseVH Pi/OE test builds.

**Comment by uNiversaI** [comment]
> Any change we can merge this as-is for v16? It apparently still works in the @MilhouseVH Pi/OE test builds.

The code here is completely different (thx to @mkortstiege)  and Milhouse already said it works but fanart is broken which this PR should fix also.

**Comment by uNiversaI** [comment]
> Any change we can merge this as-is for v16? It apparently still works in the @MilhouseVH Pi/OE test builds.

Its doesn't work very well as it breaks fanart, see #7462 for proper implementation, thx to mkortstiege

**Pull request closed without merging**
