### PR TITLE
use $(MAKE) to recursively call make

### PR DESCRIPTION
**Pull request by atupone**
Another istance :)

### CODE REVIEW

**Comment by Memphiz** [comment]
This commit message sounds missleading to me

**Comment by atupone** [comment]
When you call make from a makefile you should use $(MAKE) normally

**Comment by Memphiz** [comment]
Yes the recursively is what i stumble over ... a simple change of the commit message which makes it less scary when i read it in a year would be something like "use $(MAKE) for generating compile info instead of hardcoded make" - or something like that

**Comment by uNiversaI** [comment]
@Memphiz  I wondered what happened to https://github.com/xbmc/xbmc/pull/5157

**Comment by Memphiz** [comment]
@FneuFneu a word?

**Comment by atupone** [comment]
Referencing make with $(MAKE) is almost a requirement in a Makefile.
In a shell there is not such a requirement,you do only for your comfort :)

**Comment by Fneufneu** [comment]
Sorry, yes we should use $(MAKE) on every makefile.

**Comment by Memphiz** [comment]
jenkins build and merge

**Comment by Memphiz** [comment]
jenkins is dead for now

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
