### PR TITLE
[filesystem] - remove afp

### PR DESCRIPTION
**Pull request by Memphiz**
As the title said. Jenkins seems fine with it (some users might not):

http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-All/643/

I have split it into 2 commits in case we want to keep the afp related logic (in case afp will return at one point in form of a vfs addon or similar). Any opinions in keeping the logic? (like IsAFP and thelike).

### CODE REVIEW

**Comment by notspiff** [comment]
my .02c; if you move to vfs addons there shouldn't be a need for these functions. we'd need to switch to a feature/property based check rather than a type-based check. as in
```
if(IsAfp())
  turnOnThing();
```
to
```
if(vfsaddon.supports(thething))
  turnOnThing()
```

**Comment by topfs2** [comment]
Yeah I proposed the same thing :) didn't you do vfs addons @notspiff?
Wonder if we can pick a bit from you again :)

**Comment by notspiff** [comment]
i started on it but it's far from finished. interfaces are mostly done, and i have some working addons (rar, sacd isos), some almost working addons (ssh), some not working at all addons (smb) and lots of untested things (sling, afp, hdhomerun, ..)

**Comment by Memphiz** [comment]
don't waste your time on afp if it is based afpfs-ng. The lib is crap. I take it this Pr could be merged (either squashed or not)...

**Comment by MartijnKaijser** [comment]
bury it with the atv2 :)

**Comment by Memphiz** [comment]
rebased jenkins build and merge

**Comment by MartijnKaijser** [comment]
Screenshot

**Pull request merged**
