### PR TITLE
[crossguid] all: also check for installed location

### PR DESCRIPTION
**Pull request by un1versal**
@wsnipex as per IRC convo.

Thanks for time and tips.

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by uNiversaI** [comment]
@wsnipex build failed http://jenkins.kodi.tv/job/BuildMulti-PR/3461/ no idea if its related.

I snuk in a readme fix also

**Comment by wsnipex** [comment]
the previous build failure is directly related to the PR. Its a bit tricky to get all use cases right.
You can try http://paste.ubuntu.com/12125093/
If this doesn't work, I doubt that its worth it.

**Comment by uNiversaI** [comment]
That works. Ive updated PR as well so you can fondle Jenkins again.

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by uNiversaI** [comment]
\o/

**Pull request merged**
