### PR TITLE
Add support for a checkerboard stereoscopic 3D mode for OpenGL

### PR DESCRIPTION
**Pull request by prof-membrane**
This patch adds support for a checkerboard 3D mode on OpenGL systems. 

It is basically a clone of the interlaced mode, just with a different stipple pattern. I have changed the name of the interlaced pattern to "stipple_interlaced" to avoid confusion. The rest of the patch should explain itself.

I don't know if the patch is complete as I don't have the possibility to test it right now. I suspect the 3D mode has to be enabled for the GUI to select it, but I couldn't find any clue.

### CODE REVIEW

**Comment by agibson-fl** [comment]
+1

**Comment by da-anda** [comment]
@prof-membrane could you please rebase this PR?

**Comment by prof-membrane** [comment]
I don't have much time right now to tackle this. I'll close this commit for now. There have been a lot of changes in the video renderer in the last few months, so I have to rewrite the patch. 

I'll be back.

**Comment by agibson-fl** [comment]
I had these changes rebased on top of develop locally over the holiday. But I had troubles getting a build to test.

**Pull request closed without merging**
