### PR TITLE
[contextmenu] refactor addon loading/initialization

### PR DESCRIPTION
**Pull request by tamland**
Due to some recent refactoring every info bool for addons in the repository are registered when reading the repository index (whoops!). This should fix that and that initialization issues encountered in #10335.

### CODE REVIEW

**Comment by tamland** [comment]
jenkins build this please

**Comment by tamland** [comment]
@MartijnKaijser Want to include in beta 2? 
Looks like it's been causing crashes way back: http://forum.kodi.tv/showthread.php?tid=267877&pid=2402415#pid2402415

**Comment by MartijnKaijser** [comment]
up to you :)
wanna build it tomorrow morning to release in afternoon.

**Comment by tamland** [comment]
Lets go for it then. Still early;)

**Comment by MartijnKaijser** [comment]
Not sure if related but on a fresh install i'm getting this in the log file

> 22:13:14 T:18446744073034275104   ERROR: ContextMenuManager: failed to load addons.

**Pull request merged**
