### PR TITLE
[Estuary] Some performance optimizations

### PR DESCRIPTION
**Pull request by ksooo**
Some small things I spotted while debugging certain core stuff:

1) DialogSeekBar: Reorder the window global logically AND-ed 'visible' statements from cheap to expensive wrt. evaluation time. Now, none of the logically OR-ed labels/bools are checked if neither fullscreen video nor music visualisation window is active, for example. Before, in the worst they were checked all, just to determine that the overall visible state is false, because of the currently active window.

2) Put evaluation of 'PVR.ChannelNumberInput' at the end of the logivally OR-ed 'visible' conditions, as it is rather expensive. In case one of the conditions before 'PVR.ChannelNumberInput' evaluates to true, 'PVR.ChannelNumberInput' will not even be checked.

### CODE REVIEW

**Comment by wyrm65** [comment]
ksoooo, sorry mate, while I understand what you are trying to achieve, 99.95% certain this will achieve nothing.

Skin engine does not stop evaluating visible conditions until the end of the tag. So while logically there is no point continuing after the result is true, each condition is still checked. 

Now if you are looking for a project you could take a look at the visible tag and provide the code to stop evaluating on or’s and true and on and’s and false. Then your changes would probably have some effect.

**Comment by ksooo** [comment]
I’m pretty sure I decided this and saw the expected result. Can you prove (show me the code) what you are saying.

**Comment by ksooo** [comment]
This is the code that evaluates the expressions:
 
https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/info/InfoExpression.cpp#L95-L116

@wyrm65  It seems that you are partially right. 

Evaluation is ended once the first and-ed term that evaluates to false is found. So, my reordering the three visible lines commit has the desired effect. ;-)

But evaluation of or-ed terms is actually not stopped once the first term evaluating to true is found. Thus, my commit to put the expensive "PVR.ChannelNumberInput" term at the end of the or-ed terms has no effect.

**Comment by ksooo** [comment]
> But evaluation of or-ed terms is actually not stopped once the first term evaluating to true is found. Thus, my commit to put the expensive "PVR.ChannelNumberInput" term at the end of the or-ed terms has no effect.

Nope, misread the code. Evaluation stops as soon as the first or-ed term evaluates to true.

To conclude: My changes are correct and work as expected.

**Comment by wyrm65** [comment]
ksooo, my apologies, this was the case back in the time that Jonathan was running the show. This was one of the optimisations he mentioned could be made to the skin engine. I guess I missed the PR where this was changed. 

Time to hit my skin and reorder some visible tags.

BTW, you might want to cast your eye over $INFO evaluation. There are a lot of them that only change when moving to a new library item. If the evaluation of these items are moved to a separate list and only checked when the library item changes there would be a pretty good time saving to be had.

Would do this myself, but c++ is beyond my pay grade

**Comment by ksooo** [comment]
@jjd-uk ronie seems to be very busy these days. Maybe you can help out and do the review?

**Review by enen92 — APPROVED** [review]
Same logical behaviour as before, just some bools reordered

**Pull request merged**
