### PR TITLE
[osx/windowing] - fix regression after removing deprecated video mode enumeration API

### PR DESCRIPTION
**Pull request by Memphiz**
This PR is meant to fix the regression introduced by changed behavior of the new Screen mode enumeration API of Apple which was added due to deprecation in PR #12064.

@ksooo can you give this a shot and confirm that it fixes your macbook retina issue?

### CODE REVIEW

**Comment by ksooo** [comment]
@Memphiz Confirming the fix. 👍

**Comment by Memphiz** [comment]
Thx - Jenkins build and merge

**Comment by Memphiz** [comment]
Jenkins build this please - @MartijnKaijser that Build and merge trigger was not working again yet right?

**Comment by MartijnKaijser** [comment]
It works but Windows has me failing test so it doesn't merge.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
Is it case sensitive now or is there still a problem with the github oull request builder trigger?

**Comment by MartijnKaijser** [comment]
I can't really find a pattern

**Pull request merged**
