### PR TITLE
[configure] fix sse4 typo

### PR DESCRIPTION
**Pull request by mkortstiege**
Fixes typo Introduced with b13d84764883aed9805d2670b21211dde6bdc826

@wsnipex your button.

### CODE REVIEW

**Comment by mkortstiege** [comment]
Note, this is completely untested but i suspect it's the root cause of weird startup crashes reported on IRC. Still waiting for feedback.

**Comment by wsnipex** [comment]
otoh, this whole block should probably just go. Its a remnant of old AE days and doesn't seem to be used anywhere now. Note that the only place sse4 is really used is in vaapi/libsse, which has its own Makefile that passes the flag.

@uNiversaI, how did your tests go?

**Comment by uNiversaI** [comment]
http://forum.kodi.tv/showthread.php?tid=218734&pid=1930863#pid1930863

I tested this https://github.com/uNiversaI/kodi/commit/ab1a852e54fe9051dd5a1e855a6ffd35ee293cfe
That patch worked, but of course many cpu including mine done support sse4.1 mine max only sse2

Ill compile with this ontop and give you feedback in about an hour or so.

**Comment by uNiversaI** [comment]
@mkortstiege this doesnt work at all it still crashing repeatedly.

I'll try to remove the whole block now and see how that goes as pre wsnipex suggestion.

**Comment by mkortstiege** [comment]
@uNiversaI you applied that on top of your changes?

**Comment by uNiversaI** [comment]
this works https://github.com/uNiversaI/kodi/commit/a2ce8953f6a9d97eaee164778a37ebeaae80d6cf
Includes yours ontop.

Since you made this PR to master and not mine then I assumed this was not to be applied ontop of mine.

So Shall I PR https://github.com/uNiversaI/kodi/commit/a2ce8953f6a9d97eaee164778a37ebeaae80d6cf :question:

**Comment by mkortstiege** [comment]
@uNiversaI i think we could just nuke he entire block as @wsnipex suggested.

**Comment by wsnipex** [comment]
@uNiversaI could you test with the whole block removed? http://paste.ubuntu.com/10291240/

**Comment by uNiversaI** [comment]
I was already compiling https://github.com/uNiversaI/kodi/commit/a6bf072664f4bb3a69cb96723c08f5e0b3b74eb7

So what happens to sse2 here and elsewhere? I know sse4 wsnipex said its on its own make file etc. Just trying to understand why this causing so much grief lol aside from fact some cpus cant handle sse4.1

**Comment by uNiversaI** [comment]
ok https://github.com/uNiversaI/kodi/commit/a6bf072664f4bb3a69cb96723c08f5e0b3b74eb7 also doesnt crash.

Shall I PR that :question:

**Comment by wsnipex** [comment]
thanks for the test. as said on IRC, I'll still have to verify on i386 with gcc 4.9

**Comment by wsnipex** [comment]
see https://github.com/xbmc/xbmc/pull/6487 
better ideas most welcome

**Pull request closed without merging**
