### PR TITLE
[OverlayRendererDX] Fix rendering overlays in TAB/SBS modes.

### PR DESCRIPTION
**Pull request by afedchin**
see title.

### CODE REVIEW

**Comment by afedchin** [comment]
jenkins build this please

**Comment by itachihm** [comment]
Hi, just to note that didn't work with me. I was with v16 and disabling DXVA fixed the problem.

I updated my Kodi to v17b7, the problem persists..

Now i updated to v17rc2 and i can confirm that not work. Disabling DXVA2 make subtitles work. Enabling make subtitles went to half left screen

**Comment by afedchin** [comment]
image
with dxva. the latest build.

**Comment by afedchin** [comment]
issue occurs for text subtitles only. here is fix #11341

**Comment by itachihm** [comment]
Tested right now the nighly (KodiSetup-20170102-ab7f182-Krypton.exe), worked as expected, with DXVA enabled.

Thanks a lot for this!

**Pull request merged**
