### PR TITLE
Update Kodi Icon for Linux packaging

### PR DESCRIPTION
**Pull request by razzeee**
## Description

This was redone from scratch by @samfishermike as I requested a version without a drop shadow

## Motivation and context

There are guidelines recommending having no drop shadow

## How has this been tested?

No, but it should work as is

## What is the effect on users?

Hopefully nicer icons, as they don't get double drop shadows

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [x] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by neo1973 — APPROVED** [review]

**Comment by sarbes** [comment]
The icons have "invalid" coloring in the transparent regions. You can see the regions if you disable the alpha channel:
icon256x256_without_alpha

The blue areas will bleed through if sampled at a different resolution (for example 200x200).

**Comment by razzeee** [comment]
@sarbes got a v2 from @samfishermike hopefully they are better?

**Comment by garbear** [comment]
Should these png files be minimized?

**Comment by razzeee** [comment]
> Should these png files be minimized?

Sorry, what?

**Comment by garbear** [comment]
There a tool called pngcrush that will reduce the size of a png file. You can call it like `pngcrush -brute -ow icon128x128.png` and it should make the file smaller.

**Review by yol — APPROVED** [review]

**Review by garbear — APPROVED** [review]

**Pull request merged**
