### PR TITLE
French Regex added on m_videoCleanStringRegExps function

### PR DESCRIPTION
**Pull request by Machou**
## Description
I added 2 terms to clean up the name of the releases in French.

### CODE REVIEW

**Comment by lrusak** [comment]
Why close?

**Comment by Machou** [comment]
> Why close?

Wasn't the proposal rejected?

**Comment by fuzzard** [comment]
Wasn't even looked at by anyone.

**Comment by lrusak** [comment]
Jenkins just suggested the clang-format output. No reason to close the PR.

**Pull request closed without merging**
