### PR TITLE
[IMX] Parse screen dimensions from Detailed timing section first.

### PR DESCRIPTION
**Pull request by mk01**
This section (should) contain WxH in [mm].

(if not defined, revert back to standard info [cm], then as before
 revert to 1.0f)

### CODE REVIEW

**Comment by mk01** [comment]
https://github.com/xbmc/xbmc/pull/6922

**Comment by mk01** [comment]
@fritsch 

something for @smallint to test. Detailed timing info is in [mm] what enhances it's resolution by 10x.
smallint should then get 1.0001250 and get rid of the rounding problem.

- there is also an option to use that value for matching against the "usual" screen ratios - 16:10, 16:9, 5:4, 4:3 - but I don't like that much.

**Comment by MartijnKaijser** [comment]
Nudge

**Comment by Rechi** [comment]
@mk01 this needs a rebase

**Comment by Rechi** [comment]
obsolete as IMX specific code was removed at #12990

**Pull request closed without merging**
