### PR TITLE
[interfaces] Fix PVR channel playback from remote app 'favourites'

### PR DESCRIPTION
**Pull request by ksooo**
Take 2 to fix a problem reported in the Forum: https://forum.kodi.tv/showthread.php?tid=374760&pid=3169494#pid3169494

First attempt was to "invasive", caused problems elsewhere, for example resume of pvr folders no longer working. So, let's fix the problem at it's root, the json-rpc call. Now we handle pvr channels and recording like already done there with slide shows.

No regression, something that according to my code analysis never worked for pvr add-ons providing playback parameters using GetChannelStreamProperties resp. GetRecordingStreamPropertiesAPI call.

Runtime-tested on macOS, latest Kodi master + latest (Testflight) "Kodi Remote" app on iPhone.

@phunkyfish something for you to review.

### CODE REVIEW

**Comment by the-black-eagle** [comment]
json-rpc schema version needs bumping to 13.3.1 ;)

**Comment by ksooo** [comment]
> json-rpc schema version needs bumping to 13.3.1 ;)

Why?

**Comment by ksooo** [comment]
@the-black-eagle nvm, I just did the bump. You will know why this is needed.

**Comment by enen92** [comment]
> > json-rpc schema version needs bumping to 13.3.1 ;)
> 
> Why?

Changes to internal logic even if don't change the signatures/api usually require a minor version bump. It has been always like this :)

**Comment by the-black-eagle** [comment]
>  You will know why this is needed.

In my defence, @DaveTBlake drilled this into me, it tells you in the schema when and what to bump. 

https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/methods.json#L21-L34

The amount of times I forgot or bumped the wrong bit and had Dave correcting me!  And even now, I can still get it wrong.

**Review by phunkyfish — APPROVED** [review]

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins errors are unrelated

**Pull request merged**
