### PR TITLE
Bring up a minimal amount of services in test environment

### PR DESCRIPTION
**Pull request by notspiff**
This limits the services in the test environment to

- settings and network (used in various spots)
- addon manager - used in a couple of TestAddonFactory tests

### CODE REVIEW

**Comment by notspiff** [comment]
jenkins build this please

**Comment by notspiff** [comment]
i will need help with figuring out the what, and why, osx needs more stuff.

**Comment by hudokkow** [comment]
ping @Memphiz?

**Comment by Memphiz** [comment]
Is there somewhere output for the OS X tests on Jenkins?

**Comment by notspiff** [comment]
Rechi gave me req info and all is green ;)

**Comment by Memphiz** [comment]
nice - thx :)

**Comment by notspiff** [comment]
got a thumbs up, no protests in slack, all is green. i'm merging.

**Pull request merged**
