### PR TITLE
Move all log entries from addons to a component log

### PR DESCRIPTION
**Pull request by razzeee**
Will completely remove addons logging to the logfile without the component logging for addons enabled. If you enable it, it should be similiar to before.

In order to not break the api, I've left the parameter for the loglevel in the definition and maked it as deprecated.

This relies on https://github.com/xbmc/xbmc/pull/8562
specifically https://github.com/mk01/xbmc/commit/2e7d7943b284a62ae19847cd2da9d3025bafdecb
being merged.

Not sure if I like the wording/naming, so please let me know.

### CODE REVIEW

**Comment by ronie** [comment]
1. why remove the ability to specify different log levels for addons?

2. it's hard enough as-is for addon devs to get a proper debuglog from users,
putting python addon behind yet another switch will only make it more complex.

**Comment by Razzeee** [comment]
Just remembered some of you guys saying, addons shouldn't log by default,  because core devs are annoyed by it. Could have sworn it was you or @martijnKaijser . That's why I got a setting in script.trakt you need to enable additionally to debug logging to get any logs at all. 

I can try to find that forum post tomorrow again.

**Comment by ronie** [comment]
no need to look for that conversation, i remember it :-)

some of my addons also have a setting to enable logging but it is a total nightmare.
the instructions to enable it are in the first post of the addon support thread, but no one ever reads it.

i admit having a global setting (with proper instructions on the debuglog wiki page) is better than adding such a setting to each individual addon....


would like to hear some opinions from other addon devs as well.

**Comment by Montellese** [comment]
I think that we shouldn't remove the different log levels. THAT will make it really hard to see which log message is of importance and which one isn't. I don't really have a strong opinion about showing/hiding addon log messages in our log. I'm not even sure what the current state is but IMO there are three options:

1. keep everything as it is and log everything into our log file
2. only log info, warning and errors into our log file and provide a global switch for debug logging
3. don't log anything into our log file and provide a global switch to enable all addon logging

**Comment by Razzeee** [comment]
4. Create multiple logfile for each component like OpenELEC does. I'm not sure about the consequences, but I liked the idea.

**Comment by Razzeee** [comment]
Btw at the current state of the pr only fatal from addons will be logged. For everything else you need to enable debug logging

**Comment by Tolriq** [comment]
> Create multiple logfile for each component like OpenELEC does. I'm not sure about the consequences, but I liked the idea.

Love this idea :) Currently it's horrible when a user sends a 10 MB Kodi logs for support.

**Comment by Montellese** [comment]
That would be pretty easy if we could finally decide to move to a proper logging framework / library and to which one.

**Comment by MartijnKaijser** [comment]
So how would splitting it actually work when i have python addon using json-rpc as interface. Need to check both logs?

If python is moved to component logging it should be default ON. Also loosing the loglevels is not wanted.
Having a special setting per addons is still highly wanted cause multiple addons spamming the log is pretty much useless. So if you want extra debugging for your addon you need to have a switch and it should not be spamming by default as that makes the log useless for others

**Comment by Tolriq** [comment]
> So how would splitting it actually work when i have python addon using json-rpc as interface. Need to check both logs?

I don't know what those addons would log, but from my experience, JSON RPC logs are spammed by tons of addons / remotes. So having the split you can have a better addon log to find the problem, then if the error indicate a JSON problem you have the timestamp to easily find your JSON RPC call hidden in the middle of all other calls.

**Comment by ronie** [comment]
splitting up logs will be horrible. addon issues can be caused be a lot of other things besides the python code itself. corrupt databases, failed internet connection, whatever.

when i ask users with problems for a log file, i want a full logfile, with every single bit of info included.

**Comment by wsnipex** [comment]
removing addon logs from the debug log will make it nearly impossible to see if an addon causes general issues in kodi.

**Comment by Tolriq** [comment]
Yes  for addons sounds like more complicated :( 

Maybe then change a little the format of the log file so that it can be easily parsed with tools ?

Does not miss a lot, removing of carriage return, and force a component value like default or none for lines without one ? 

This would allow a simple regexp parsing and filtering for more efficiency no ?

**Comment by Razzeee** [comment]
@tolriq can you name any tools that do this?

**Comment by Tolriq** [comment]
Well would be custom tool ;) But parsing a file with a more or less fixed format with a regexp is a 4 line script in most OS.

For the logs to be compatible with most tools it would need much more change and move to a well known format.

**Comment by MilhouseVH** [comment]
If logging is split into different files, asking a user with a problem to "post their debug log" is going to become even more of a challenge than it already is.

**Pull request closed without merging**
