### PR TITLE
bump librtmp

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

### CODE REVIEW

**Comment by popcornmix** [comment]
Seems to be a dos line endings problem with this (unified build with Ubuntu host and raspberry pi target) 
```
cd arm-linux-gnueabihf; patch -p0 < ../prefix.patch
(Stripping trailing CRs from patch; use --binary to disable.)
patching file librtmp/Makefile
Hunk #1 FAILED at 1 (different line endings).
1 out of 1 hunk FAILED -- saving rejects to file librtmp/Makefile.rej
make: *** [arm-linux-gnueabihf] Error 1
```
This got it building for me:
```
find arm-linux-gnueabihf/ -type f -exec busybox dos2unix {} \;
```

**Comment by FernetMenta** [comment]
we have uploaded a new version of the sources
jenkins build this please

**Comment by stefansaraev** [comment]
soname changed.
https://github.com/xbmc/xbmc/blob/master/lib/librtmp/darwin_package_librtmp.sh#L3
not sure if this is still in use (and how) but you may want to change it

**Comment by FernetMenta** [comment]
@Memphiz do we need to change this?
Shouldn't this go into tools/darwin/packaging?

**Comment by Memphiz** [comment]
@FernetMenta grep darwin_package_librtmp.sh * -r doesn't find any reference ... i guess its not used (anymore?)

**Comment by davilla** [comment]
pre-depends build debris, last touched Aug 2, 2010. nuke away.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
@FernetMenta the windows update doesn' t work as you need to repackage it in a different way.
See http://mirrors.kodi.tv/build-deps/win32/librtmp-20110723-git-b627335-win32-1.7z

**Comment by FernetMenta** [comment]
can someone upload the new archive to the mirrors
https://dl.dropboxusercontent.com/u/47522966/librtmp-20150114-git-a107ce-win32.7z

**Comment by Memphiz** [comment]
@FernetMenta done

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
@Memphiz does the build machine cache the archives? build failed and it shows still the old one.

**Comment by FernetMenta** [comment]
same seems to be happen for the source archive use for Android builds. they still fail applying a patch which should be corrected by the updated archive.

**Comment by Memphiz** [comment]
well normally we don't overwrite archives but give them another name - at least when the archive was in the wild for a while. There is no mechanism for the buildsystem to detect a changed archive when its named the same (so it will use the cached version).I will login to the builders and remove the archive so it gets refetched - gimme a min...

**Comment by Memphiz** [comment]
done

**Comment by FernetMenta** [comment]
thanks
jenkins build this please

**Comment by FernetMenta** [comment]
what is the problem with the Android builds?

**Comment by Memphiz** [comment]
@FernetMenta - in the depends Makefile you are still refering to librtmp.so.0 - its so.1 now as of the jenkins los...

**Comment by FernetMenta** [comment]
@Memphiz thanks. test build on Android succeeded
jenkins build this please

**Pull request merged**
