### PR TITLE
[Music]Make MySQL native sorting functions more robust

### PR DESCRIPTION
**Pull request by DaveTBlake**
Make music database MySQL native functions (that perform natural number sorting) more robust to unusual names and titles.

Had a user fire some really unexpected album titles at these functions which cuased them to fail. The user experience was that the Top 100 Albums node showed empty, it is one of the places the GUI uses databse side sorting, but he also tracked it down to being a problem in MySQL. 

Example problem string:
"Complete Beethoven Edition Vol 15 - Wind Music - CD2 - Sextett op 71, 3 Equale WoO 30,
Märsche WoO 29, 18, Polonanise WoO 21, Ecossaise WoO 22, Marsch-trio WoO 20, Märsche WoO 19, 24"

This is both unusually long and has multiple separate digits. The natural number native functions did not have any checks to ensure that the string processing didn't overflow the variable sizes. 

It is only a  issue on client/server setups using MySQL/MariaDB. As titles like this (with track data in the album title), are is not something users would normally have, I think this issue is exceptionally rare. Hence a db bump, and associated migration (which for SQLite would just make a copy of the database, and would make it necessary to update all client versions in a client/server set-up) is unnecessary.

I have tested on MySQL with both ordinary music data and some crazy strings too.

### CODE REVIEW

**Comment by DaveTBlake** [comment]
Discussed in detail on the forum https://forum.kodi.tv/showthread.php?tid=361905

@the-black-eagle perhaps you could check this over with your MySQL set-up?

**Comment by fuzzard** [comment]
Only question I would have, and keep in mind it may not be feasible for whatever reasons, would it be better to set a list of defines for the magic numbers?

**Comment by DaveTBlake** [comment]
I understand why you would ask that @fuzzard, but I don't really see a feasible way to do that when building native functions as a string to execute within MySQL. It ain't pretty code, but when the functions are viewed from within a MySQL tool like Workbench they look much clearer.

jenkins build this please

**Comment by the-black-eagle** [comment]
Tested against MariaDB with strings of over 255 chars, containing multiple numbers, punctuation etc.  All worked fine.  Did my best to break it and couldn't.  :)

**Comment by DaveTBlake** [comment]
Turns out Clang on Android or OSX found I had dropped escaping `\` correctly, well done Clang check. Just wish that Clang on Windows was as clever.

It needs escaping just once for C++ to add `\` to a SQL comment, but MySQL also needs it escaped when in a function parameter. Hence as a parameter two levels of escape `\\\\` is needed in the C++.

**Comment by DaveTBlake** [comment]
Test build availlable:
 http://mirrors.kodi.tv/test-builds/osx/x86_64/kodi-20210426-57d615ab-PR19635-merge-x86_64.dmg 
and 
http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20210426-57d615ab-PR19635-merge-x64.pdb

**Comment by DaveTBlake** [comment]
User testing confirms fix https://forum.kodi.tv/showthread.php?tid=361905&pid=3033078#pid3033078

**Pull request merged**
