### PR TITLE
[addons] Remove not needed parts

### PR DESCRIPTION
**Pull request by AlwinEsch**
Remove no more needed parts since #12029

## Description
This remove the old version check functions who was defined before on some types. This becomes now done by one fixed function for all addon types and no more needed to change on addon itself (is done automatic during compile)

## Motivation and Context
Next step from kodi-agile

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by ksooo — APPROVED** [review]
Very nice. Please don't forget to provide the PRs for the affected addons, including addon version bump and changelog update. Thx.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
Ignore Windows fail

**Comment by AlwinEsch** [comment]
Thanks @MartijnKaijser!

**Comment by hudokkow** [comment]
I'm sorry to spam everyone but, yeah... it's in order.

@AlwinEsch, :clap: :clap: :clap: :tophat:

**Pull request merged**
