### PR TITLE
cppcheck performance fixes in video/

### PR DESCRIPTION
**Pull request by tobbi**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by kib** [comment]
Error occurred before build was attempted, seems github buggered out. 

jenkins build this please

**Comment by tobbi** [comment]
Can this just be merged or re-built? Only build failed (Win 32) and I doubt it's due to the content of this PR.

**Comment by kib** [comment]
Jenkins build this please

**Comment by kib** [comment]
jenkins build this please

**Comment by tobbi** [comment]
Looks good to me. Merge please.

**Pull request merged**
