### PR TITLE
Player.Process info label changes

### PR DESCRIPTION
**Pull request by FernetMenta**

### CODE REVIEW

**Comment by sualfred** [comment]
I've tested Hitcher's triggered test build:

What works:
- Video FPS
- Video AR
- Pixel format
- Video decoder

Doesn't work:
- Deinterlace method always unkown
- Audio channels always unkown
- Audio decoder always unkown
- Video height/width/sample rate/bits per sample are completely empty without "unkown"
- HW decoder bool is false even if DXVA is used
- Info labels won't be cleared if playback is stopped

**Comment by FernetMenta** [comment]
> Video height/width/sample rate/bits per sample are completely empty without "unkown"

You know that those are integer?

> HW decoder bool is false even if DXVA is used

not set by DXVA. platform devs need to set this info in their codecs

**Comment by FernetMenta** [comment]
I see the issue why audio related info is empty. Will fix soon.

**Comment by stefansaraev** [comment]
> You know that those are integer?

sadly (or not), skins seems not to care.

> not set by DXVA. platform devs need to set this info in their codecs

once, kodi was multi platform application, and feature PRs were supposed to be "complete", especialy when they were supposed to re-add a functionality dropped by intention.

did you runtime test this, @FernetMenta ?

**Comment by sualfred** [comment]
Ah okay.
Since the values are static, doesn't it make more sense to output them as string? These Integers cannot be used to fill a label. Or do you had a different purpose for it?

**Comment by FernetMenta** [comment]
@sualfred bear with me, my skinning skills are limited. If you want strings, you get strings :)

**Comment by FernetMenta** [comment]
@stefansaraev what you are saying makes no sense. I progress this in iterations. No need to have AML implemented for this testing here. Why should we block skinning work waiting for all platforms to catch up.

**Comment by stefansaraev** [comment]
did I say something about aml. @FernetMenta ?

**Comment by sualfred** [comment]
@FernetMenta 
That's why I was asking, my coding skills are very limited ;)
I think strings would be better in this case.

@HitcherUK @phil65 Are you fine with strings?

**Comment by stefansaraev** [comment]
@FernetMenta 

it makes perfect sense, and it is obvious that you never runtime tested this.

first you broke it, without even knowing the potential colateral damages you are doing, calling others code (that worked for years) "crap" (several times), then you shoot down everyone that makes valid points (yea, pvr signal info is completely unrelated here, of course)

we have been repeating this "catch up" thing for 2 releases now, enough is enough.

-1 to this PR til its fully working for all codecs we have in tree, including skin support, and everything we had in the old codecinfo screen works as before (or better).

**Comment by FernetMenta** [comment]
@stefansaraev your -1 does not count here. I won't implement for all codecs and we don't have an Android dev. Following your advice is silly because we would never get this new functions.

**Comment by stefansaraev** [comment]
of course it does not count (I did not expect a benevolent dictator for life would count it)

**Comment by stefansaraev** [comment]
feel free to completely drop the android port, btw. I am leaving now.

**Comment by FernetMenta** [comment]
I only ignore your comments on this thread. This is a dev space, you should know. I don't consider you as  a skilled developer in this domain, hence I don't consider your vote.

**Comment by MartijnKaijser** [comment]
@fernetmenta I warn you  and show some respect towards others! You are going to far again.

**Comment by FernetMenta** [comment]
direct this warning to seo as well. you were around a couple of days ago when he was bitching at me on slack. it is hard giving respect to someone hahaving like this.

**Comment by FernetMenta** [comment]
@sualfred I change width, height, samplerate, bitpersample to string
isHw should work now too. audio related info gets updated.

Do you want me to kick off a test build for Windows?

**Comment by sualfred** [comment]
@FernetMenta 
Yep, please trigger one.

**Comment by sualfred** [comment]
@FernetMenta 
Tested. Everything works well except the deinterlace method. This value stays at "unkown".

Couldn't test PVR and DASH sources, because I'm in the office.

**Comment by HitcherUK** [comment]
That should be 'Unknown' by the way ;)

**Comment by FernetMenta** [comment]
hehe, the only "unkown" I was able to find is in SFPTFile: https://github.com/xbmc/xbmc/search?utf8=%E2%9C%93&q=unkown

@sualfred are you sure it reads "unkown"?

**Comment by amet** [comment]
https://github.com/xbmc/xbmc/blob/master/addons/resource.language.en_gb/resources/strings.po#L5944

g_localizeStrings.Get(13205) disagrees :)

**Comment by sualfred** [comment]
@FernetMenta 
Yep. Tested it with my media here and with a interlaced sample video. It stays at unkown even if deinterlacing is forced by default.

**Comment by FernetMenta** [comment]
@sualfred yes, that is not implemented yet. The question was if it says "unknown" or "unkown" :)

**Comment by sualfred** [comment]
@FernetMenta 
Sry, too blind to read my own typo ;) It's "unknown".

**Comment by HitcherUK** [comment]
q3epejw

Saved me from coding it, thanks.

**Comment by sualfred** [comment]
Always at your service :)

**Comment by FernetMenta** [comment]
jenkins build this please

**Pull request merged**
