### PR TITLE
DRMAtomic: Use nonblocking buffer commit

### PR DESCRIPTION
**Pull request by neo1973**
## Description
Use nonblocking buffer commits to eliminate some waiting in the render thread.

## Motivation and context
I noticed that my Kodi debug build was running smoother when running on Wayland than GBM. With a release build I couldn't notice a difference but with a debug build the difference could be up to 30 fps vs 60 fps depending on the scene on a Ryzen 5700u.

When investigating I found out that using nonblocking buffer commits eliminates the performance difference. I hope that this has a positive effect on slower ARM devices as well.

## How has this been tested?
Runs without graphical artefacts, performance seems improved.

## What is the effect on users?
Hopefully more FPS on weak devices.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
Not too sure about this. When I looked into using non blocking commits I figured we would need to use egl fencing also. See, https://github.com/lrusak/xbmc/commit/cad412eb928dd56d9df92030d0af3ccbc85e4413

**Comment by popcornmix** [comment]
On a quick check this looks very promising.

There are two cases that don't currently work well with gbm:
-   sync playback to display (e.g. to allow 24fps video to play smoothly on 50Hz display with 4% speedup)
-   video with higher fps than display (e.g. 60fps video on 50Hz display mode)
 
This seems to fix both of these issues.

The other potential side effect of blocking less is high cpu, and I'm not seeing that.

Let me add it to my home build and see if any issue shows up.
I'll also see if I can spot any fps changes in gui displays.

**Comment by popcornmix** [comment]
I've tested with this reverted and I'm still not seeing the two issues identified in last post,
so maybe it needs more specific files to show the issue, or some other change has mitigates it.
I'll continue to test.

**Comment by smp79** [comment]
The performance increase seem to me identical to #22012

**Comment by howie-f** [comment]
although this patch is for master i‘ve tested with LE11/Nexus. had hope this could fix the known a/v sync issues. https://github.com/xbmc/xbmc/issues/22625

unfortunately it doesnt work. when starting a video i don‘t get a picture, only audio playing, when i stop the video kodi stalls completely. 🙁 fyi

**Comment by neo1973** [comment]
@howie-f: Debug log please 😃

**Comment by howie-f** [comment]
eh, call me weird... now i get a picture and no more stall/hang on video stop. but the a/v sync issue is still there (regardless of player setting `sync playback to display` being on or off. anyway a debuglog from the last test https://paste.kodi.tv/quqobekiqe.kodi

if i can get it to happen again i'll submit that debuglog also

**Comment by popcornmix** [comment]
My result matches @smp79 
With 4k gui and scrolling plot in movie the debug overlay shows:
current kodi: 20fps
kodi + this PR: 24fps
kodi + https://github.com/xbmc/xbmc/pull/22012: 24fps


So both this PR and the "front of queue" PR give a worthwhile performance benefit.

**Comment by lrusak** [comment]
> I'm by no means an expert but I don't think this changes the behaviour. This still blocks until the last buffer is flipped before submitting the next one and because the buffers are locket with `gbm_surface_lock_front_buffer` they shouldn't be touchable by anyone else, right?
> 
> 
> 
> https://gitlab.freedesktop.org/mesa/kmscube uses fences but I believe they are only required there because they have the surfaceless case where no `gbm_surface_(un)lock_front_buffer` is performed.

The fences pre-date the surfaceless stuff https://gitlab.freedesktop.org/mesa/kmscube/-/commit/497ab787e5ab56c630014a20b43bfab16e3b43aa

**Comment by popcornmix** [comment]
I've been running this over weekend and it does cause an issue.

It occasionally goes into a mode where visible glitches appear on the screen (most likely parts of a future frame appear on screen).

This seems to come and go a bit. Once it is glitching every frame has corruption. A pause/unpause seems to get it back into a good state. 

This does look to me like @lrusak's concern is happening - the frame on screen is being returned to decoder, and potentially overwritten.

**Comment by lrusak** [comment]
It's worth looking into egl fencing again because at the time we were worried about support from non-mesa drivers but that concern isn't valid anymore really.

In my patch we also check for support of the async capability as some kernel drivers didn't support it at the time (I'm not sure if any don't support async, maybe etnaviv?).

I'm not sure if it will actually help with anything though as I haven't tested it in a long time.

**Comment by jernejsk** [comment]
@popcornmix do you use DRM plane rendering? fences won't help in this case, right?

**Comment by neo1973** [comment]
I'm beyond confused now. I did some more testing with **master** (e0b42ee7cd099aff3c7fa9514e3a54c4cd901954) and I'm getting scrambled images on GBM with GL once I disable VAAPI acceleration and start playing a video. Once the effect started it stays:
IMG_20230925_015524

With GLES the problem is there immediately after start, no need to play a video.

I have only ever tested GBM with GL and VAAPI so far so I don't know if this has worked in the past for my machine (Laptop Ryzen 5700u). I don't see the effect on Wayland with either GL or GLES.

I also cherry-picked https://github.com/lrusak/xbmc/commit/cad412eb928dd56d9df92030d0af3ccbc85e4413 and the GLES problem persists. GL isn't implemented in that commit, right?

**Comment by smp79** [comment]
> I'm getting scrambled images on GBM

I see the same corruption on AMD RX6600. This is unrelated to this PR.

**Comment by neo1973** [comment]
`mesa_glthread=false` indeed fixes the issue. Still, I wonder if there isn't a subtile synchronization issue in kodi that gets triggered  when doing more stuff in parallel, either through mesa (as suggested [here](https://gitlab.freedesktop.org/mesa/mesa/-/issues/9115#note_2030523)) or this PR :confused: Especially since Wayland doesn't seem to have an issue with threaded GL.

**Comment by smp79** [comment]
> Especially since Wayland doesn't seem to have an issue with threaded GL

There are no such issues with Intel + GBM.

> It occasionally goes into a mode where visible glitches appear on the screen

I've been running this for almost 4 days, no glitches here.

**Comment by neo1973** [comment]
Regarding the mesa_glthread issue: I think I found a clue and can also reproduce the issue with kmscube. I reported a bug with mesa: https://gitlab.freedesktop.org/mesa/mesa/-/issues/9885

**Comment by ninja-** [comment]
I would be curious to test that on my Rpi4, GBM, Libreelec setup at some point. Any doubts on this PR aside from AMD-specific glitches?

**Comment by neo1973** [comment]
On a RPi you'll probably gonna run in the same problem popcornmix describes. I'm still trying to wrap my head around it but my current guess is that the additional video plane used with DRM PRIME is the cause for the glitches. On my machine, and probably smp79's as well, PRIME isn't used and that's why we don't experience the glitches. I still don't understand nearly enough of this matter to come up with a solution but I have a feeling this would involve the fences lrusak mentioned :wink:

**Comment by neo1973** [comment]
I think #23921 is the way the go, therefore I'm closing this PR.

**Pull request closed without merging**
