### PR TITLE
[log] Reduce log spam from ScanArchiveForSubtitles.

### PR DESCRIPTION
**Pull request by ace20022**

### CODE REVIEW

**Comment by ace20022** [comment]
@mkortstiege Could you please have a look?

**Comment by mkortstiege** [comment]
No objections but I quick grepped my log file and found just a few `Found file` entries. Those were no dupes actually.

**Comment by ace20022** [comment]
Try to open a folder with videos and some huge archives ;)

**Comment by mkortstiege** [comment]
Ah, OK. jenkins build and merge.

**Pull request merged**
