### PR TITLE
RetroPlayer: Remove MMAL renderer on RPi

### PR DESCRIPTION
**Pull request by garbear**
MMAL (Multi-Media Abstraction Layer) is a framework for video decoding on the PRi, and doesn't make sense for RetroPlayer until we get support for game streaming (e.g. NVidia GameStream).

## Motivation and Context
Hopping on the bandtrain after #13723.

## How Has This Been Tested?
Compiles fine for RPi. Code was dead before so no runtime tests.

### CODE REVIEW

**Comment by popcornmix** [comment]
MMAL is still the best way of getting pixels (of arbitrary format) onto display with zero copy.
The mmal renderer doesn't require video to be from a decoder, and handles various RGB pixel formats directly.
I'd prefer to get this working as desired. Let me try to get RetroPlayer running and see what is needed.

**Comment by garbear** [comment]
Cool. At ELC in portland we did lunch with Eric and he said if it's just RGB data, uploading directly into a GPU buffer might be most efficient. It looks like the goal is to get the pixels into a GPU buffer, so if we could do that from the Game thread that'd be awesome.

**Comment by lrusak** [comment]
Yes, why not just access VCSM directly instead of using MMAL at all?

**Comment by garbear** [comment]
jenkins build this please

**Comment by garbear** [comment]
@popcornmix if you want to work on this I'll make you a branch that has this code restored and rebased on master

**Pull request merged**
