### PR TITLE
[PVR] prevent crash on .. when recordings list empty

### PR DESCRIPTION
**Pull request by metaron-uk**
Currently when the pvr.mythtv client starts up it returns an empty recordings list until backend sync is complete. If you enter the recordings list during this time, you end up with only .. present.
If you select .., Kodi crashes.
screenshot043

With commit 1 you get taken back to the home screen instead, which is what I expected would happen.

Commit 2 contains some 'robustness' additions I made while debugging.
It seems kodi tries to exit when it can't follow the .. path. These changes let it carry on trying to exit for a little longer, which makes it easier to work out what's happening from the log.
Happy to drop this commit if it isn't seen as useful.

pings @ksooo @janbar

### CODE REVIEW

**Comment by xhaggi** [comment]
@ksoodo why do we show the parent item in case there are no recordings? not sure but does something changed here? something related with the recording path + viewstate changes? so many questions :)

**Comment by Jalle19** [comment]
This fix looks wrong. Why does it crash in the first place?

**Comment by ksoo** [comment]
Wasn't me.  You might want to try @ksooo instead.

**Comment by metaron-uk** [comment]
> @ksooo why do we show the parent item in case there are no recordings?

I believe this was so that people with simple remotes (left/right/up/down/select) can still get back from the recordings view. Seems strange however as it only appears if the recordings list is empty.
>  something related with the recording path + viewstate changes?

Something did change in Krypton development when pvr:// changed to pvr://recordings/active/ as a virtual path. Maybe this is why the .. stopped doing what it did before (or maybe the crash has always been there?).

> This fix looks wrong. Why does it crash in the first place?

I can see what you're getting at, but there are other places which use a similar approach (see https://github.com/metaron-uk/xbmc/blob/pvr-rec-crash/xbmc/pvr/windows/GUIWindowPVRRecordings.cpp#L197 ), so this change may just be compounding an existing problem; not that that makes it right.

It crashes because kodi tries to exit uncleanly, calling all sorts of destructor methods.
I'm not sure why calling ```GoParentFolder()``` from pvr://recordings/active/ causes kodi to try and shut down, but displaying pvr://recordings/ didn't seem to be correct behaviour either so I figured a special case for the recordings list is what was called for.
Pressing .. in the videos list view takes you from  pvr://recordings/active/ to videos://active so I guess this must have had a special case coded in somewhere as well (I didn't check where the videos: special case is coded yet).

I'm open to suggestions...

**Comment by xhaggi** [comment]
https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/windows/GUIViewStatePVR.cpp#L69

I'm right we hide the parent folder item in case we are at the root of the recordings path. something is broken if it won't work.

**Comment by metaron-uk** [comment]
Makes sense. I'll take a look and see if I can work out why .. still appears in this case.

**Comment by metaron-uk** [comment]
@xhaggi - that bit of code you refer to is working fine (https://github.com/xbmc/xbmc/blob/master/xbmc/windows/GUIMediaWindow.cpp#L689). It isn't responsible for adding the '..' entry in this case.
 
The problem is that kodi won't tolerate a completely empty directory and adds a '..' entry to it later on in order to give something for the window to focus on: https://github.com/xbmc/xbmc/blob/master/xbmc/windows/GUIMediaWindow.cpp#L1819

I commented this code out and ended up with an empty list. This would obviously fix the crash, but would cause the original problem it fixed to come back.

The code was introduced during Gotham rc_1 (https://github.com/xbmc/xbmc/commit/c9062743c48bc83f4786297c9aa42855c25273d6) by Jonathan Marshall to fix the missing .. indication in filtered lists. I'm not enough of a github expert to find the PR this came from which might help explain the rationale a bit more :-(.

I've added another commit which doesn't add a '..' entry if the directory has an empty parent (the case for ```pvr://recordings/active```) which seems to work.

Do you think this is OK as a solution?

**Comment by xhaggi** [comment]
> Do you think this is OK as a solution?

No we should not adjust `CGUIMediaWindow` in case the error is only related to our PVR section.
As the comment describes at `CGUIMediaWindow`
> The idea here is to ensure we have something to focus if our file list is empty.

So as we are at the root of our PVR recordings path and we don't want to show the parent dir item which would be wrong because there is no parent directory we can jump to, we should think about adding an item which can be focused and let the user know what's up here. An item like "No recordings found".

It would be really nice if you could adjust your PR and drop everything else.

**Comment by xhaggi** [comment]
please add the item in case the list is empty at https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/windows/GUIWindowPVRRecordings.cpp#L223 before the return.

**Comment by metaron-uk** [comment]
Ok - will see what I can come up with. Thanks for the pointers.

**Comment by xhaggi** [comment]
Thank you :+1:

**Comment by hudokkow** [comment]
@metaron-uk,

For reference, click on any commit link and you'll find the associated PR number - if any - mentioned on the top left (#2007 in this case):
screenshot from 2016-03-13 17-50-05

**Comment by metaron-uk** [comment]
Thanks @hudokkow :-)

**Comment by metaron-uk** [comment]
@xhaggi - I'm afraid it's beaten me for now

1) CGUIWindowPVRRecordings::Update runs CGUIWindowPVRBase::Update which already adds a '..' entry
2) I can rename this '..' entry, but it still keeps its m_bIsParentFolder property (private), so still crashes kodi.
3) Attempts to delete it and replace it with a new entry have so far been unsuccessful...

I will try again when I have more time, but it will be at least 3 weeks.
If someone else with more skill wants to take it on, please feel free.

**Comment by xhaggi** [comment]
if I found some time to look at it I will do the necessary changes

**Comment by metaron-uk** [comment]
The '..' entry is added to stop filtering the list from returning an empty list when the filter excludes all files.
Personally I think this is a bit of a hack and ought to be changed, but unatil a better way is found to indicate 'no filtered results' and this bit oc code re-written the code which does filtering will keep adding '..' back in.
I can confirm that since https://github.com/xbmc/xbmc/pull/10374 was merged my frontend doesn't crash when I select '..' in the recordings listso I'm closing this PR.

**Pull request closed without merging**
