### PR TITLE
Video player recording labels

### PR DESCRIPTION
**Pull request by joethepartylion**
This something that has been asked about on the forums (http://forum.kodi.tv/archive/index.php?thread-219946.html) and be me so I have tried to see if I could code it myself. I have no prior C++ experience so it may be a load of codswallop but here goes.

### CODE REVIEW

**Comment by joethepartylion** [comment]
sorry, no idea about all those additional commits, please forgive my mistake, I'll try again when I know what I am doing.

**Comment by joethepartylion** [comment]
OK, I'm an idiot, wrong branch, maybe I should have added no git experience to my original comment too.

**Comment by MartijnKaijser** [comment]
do not we only accept pull requests against master branch ;)

**Comment by joethepartylion** [comment]
yes, that was what I meant to do but I got all confused, just re-branching and will try again but will check the commit list before I click 'Go', sorry for messing you around, thanks for understanding though :-)

**Pull request closed without merging**
