### PR TITLE
Revert "Fix potential SQL constraint integrity violation in the PVR database"

### PR DESCRIPTION
**Pull request by FernetMenta**
Reverts xbmc/xbmc#10507

see discussion on #10507 
things tuned out to be more complicated and need more testing. we are close to rc

### CODE REVIEW

**Comment by FernetMenta** [comment]
thanks @mention-bot for letting me know

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by fritsch** [comment]
thanks @FernetMenta for this additional email :-)

**Comment by FernetMenta** [comment]
osx build failed on test cases.

**Pull request merged**
