### PR TITLE
[backport][pvr] - fix selecting a channel by id via json-rpc

### PR DESCRIPTION
**Pull request by xhaggi**
backport of #8660 

@FernetMenta mind taking a quick look.

### CODE REVIEW

**Comment by FernetMenta** [comment]
looks good to me. would be great if also @joethefox can confirm. then we could close http://trac.kodi.tv/ticket/16440

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by joethefox** [comment]
just tested and I can confirm that the fix is working as expected!

**Comment by xhaggi** [comment]
@joethefox thanks

**Comment by xhaggi** [comment]
@MartijnKaijser ping

**Comment by MartijnKaijser** [comment]
up to you to merge ;)

**Comment by xhaggi** [comment]
okay thanks ;)

**Pull request merged**
