### PR TITLE
[win32] introduce `TARGET_WIN10` define

### PR DESCRIPTION
**Pull request by afedchin**
this the second phase/wave in preparation to uwp

this introduce `TARGET_WIN10` define. It's used commonly in conjunction with `TARGET_WINDOWS` but there're a lot of places where they are used apart

### CODE REVIEW

**Comment by afedchin** [comment]
jenkins build this please

**Comment by afedchin** [comment]
jenkins build with addons

**Comment by afedchin** [comment]
jenkins build this with addons please

**Comment by afedchin** [comment]
addons failures are unrelated

**Comment by MartijnKaijser** [comment]
looks straightforward

**Comment by Voyager1** [comment]
I find this a bit ugly tbh. Isn't there a way to have TARGET_WINDOWS for all Windows platforms combined and TARGET_WIN10 only the Windows 10 UWP things? E.g. Windows but not UWP would be : defined(TARGET_WINDOWS) && !defined (TARGET_WIN10). Windows UWP-specific would be : defined (TARGET_WINDOWS) && defined (TARGET_WIN10)...

**Comment by MartijnKaijser** [comment]
@Voyager1 yep. Same was also suggested by @Rechi on slack

**Comment by afedchin** [comment]
as was suggested in the slack we will use `TARGET_WINDOWS` for both platforms and `TARGET_WINDOWS_DESKTOP` and `TARGET_WINDOWS_STORE` for desktop and store apps respectively, so I close this as unneded

**Comment by Voyager1** [comment]
Thanks @MartijnKaijser and @afedchin - the new one looks a lot better :-)

**Pull request closed without merging**
