### PR TITLE
Remove home screen info mapping from remote.xml

### PR DESCRIPTION
**Pull request by ghost**
As in Krypton dynamically filled lists support the info action to display the relevant info dialog (e.g. info on a dynamically filled list of movies will show the details of the selected item in DialogVideoInfo.xml) this removes the override in remotes.xml that remaps info to displaying the System Information dialog, so that - by default - pressing info on a remote on the home screen displays the relevant media information dialog.

### CODE REVIEW

**Comment by NedScott** [comment]
Seems logical to me.

**Comment by un1versal** [comment]
This PR removed the possibility to access system information screen (screen below)  from home menu directly, now its only possible by many navigational clicks.

screenshot023

reverting this PR restores that desired functionality.

A perfect example of fixing what isnt broken. @Ignoble61

**Comment by Ignoble61** [comment]
You read the OP as to what this PR fixed that was broken, right? Anyway, not something I feel strongly enough about to argue over, I'll happily go back to my custom keymap and not try to contribute again :)

**Comment by hudokkow** [comment]
No need for you guys to get aggravated. If it's wrong it will be fixed.

**Comment by ace20022** [comment]
@Ignoble61 keep in mind that @un1versal isn't a team member. Ofc you are welcomed to contribute in the future. And @un1versal stop bashing!

**Comment by phil65** [comment]
It´s just noise, @Ignoble61 :) Dont pay attention to it, all fine with this PR.

**Comment by Ignoble61** [comment]
Sorry, I badly wrote that and it came across more negatively than the humorous tone I had in my head (it's amazing how often I miss that tone!) I'm very happy to attempt to contribute again if ever I find something small like this that I can do

**Comment by un1versal** [comment]
> And @un1versal stop bashing!

You all will get your wish and I doubt I will be alive by 2017, in fact I doubt Iwill see the new years, so good ridens. One less undesired

**Comment by da-anda** [comment]
If one is pressing "info" on a media item on home screen, then the info dialog should appear, just like in media windows. So consistency is desired here. System info otoh is not anything that's frequently used by regular users, so having to do a couple extra clicks (or a custom keymap) seems fine to me.

@un1versal omg, that's sad news. Get well, if possible, and thanks much for your contributions!

**Pull request merged**
