### PR TITLE
[tools/depends] Bump rust 1.79 and add Cargo.lock files

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Update rust to 1.79. Add Cargo.lock files for cargo-c, libdovi to hopefully avoid the reason for this PR in the future.

## Motivation and context
```
Error: CliError { error: Some(package `bitstream-io v2.4.1` cannot be built because it requires rustc 1.79 or newer, while the currently active rustc version is 1.78.0
Either upgrade to rustc 1.79 or newer, or use
cargo update bitstream-io@2.4.1 --precise ver
where `ver` is the latest version of `bitstream-io` supporting rustc 1.78.0), exit_code: 101 }
```

No idea if the usage of --locked everywhere is correct/needed. Tested by changing a dependency to an older version/hash, and then running cargo-c build, and it correctly downloaded the older version and compiled it, so seems to work.

## How has this been tested?
Shit builds

## What is the effect on users?
N/A

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by quietvoid** [comment]
I think only the `dolby_vision-Cargo.lock` file is necessary? We are just building the library.

**Comment by fuzzard** [comment]
I've no idea. Anything that had a lock file generated I copied, I don't want to deal with this shit again unless someone intentionally updates it.

If you can confirm some other random thing isn't going to update and break builds, I'm happy to remove whatever isn't necessary, I just don't know what is, or isn't required

**Comment by quietvoid** [comment]
Ok I tested build on the branch and building the library doesn't have an effect on the other lockfile.

It's only generated and updated in the parent folder because `cargo fetch` is done in that folder.
But its dependencies and versions don't affect the lib build anyways.

So it should be safe to delete `libdovi-Cargo.lock` and just fix the fetch command:
```diff
diff --git a/tools/depends/target/libdovi/Makefile b/tools/depends/target/libdovi/Makefile
index 15d6e32574..920b0fd4c8 100644
--- a/tools/depends/target/libdovi/Makefile
+++ b/tools/depends/target/libdovi/Makefile
@@ -1,6 +1,5 @@
 include ../../Makefile.include LIBDOVI-VERSION ../../download-files.include
 DEPS = ../../Makefile.include Makefile LIBDOVI-VERSION ../../download-files.include \
-                                       libdovi-Cargo.lock \
                                        dolby_vision-Cargo.lock
 
 LIBDYLIB=$(PLATFORM)/target/$(HOST)/release/$(BYPRODUCT)
@@ -9,6 +8,7 @@ CARGO_ENV_VARS = RUSTUP_HOME=$(NATIVEPREFIX)/.rustup \
 	               CARGO_HOME=$(NATIVEPREFIX)/.cargo
 CARGO = $(CARGO_ENV_VARS) $(NATIVEPREFIX)/bin/cargo
 
+CARGO_BASE_OPTS = --manifest-path $(PLATFORM)/dolby_vision/Cargo.toml
 ifeq ($(CROSS_COMPILING),yes)
   ifeq ($(TARGET_PLATFORM),webos)
     RUST_TARGET = armv7-unknown-linux-gnueabi
@@ -20,7 +20,6 @@ ifeq ($(CROSS_COMPILING),yes)
 endif
 
 CARGO_BUILD_OPTS = --locked \
-	--manifest-path $(PLATFORM)/dolby_vision/Cargo.toml \
 	--library-type staticlib \
 	--profile release \
 	--prefix $(PREFIX) \
@@ -31,9 +30,8 @@ all: .installed-$(PLATFORM)
 $(PLATFORM): $(DEPS) | $(TARBALLS_LOCATION)/$(ARCHIVE).$(HASH_TYPE)
 	rm -rf $(PLATFORM)/*; mkdir -p $(PLATFORM)
 	cd $(PLATFORM); $(ARCHIVE_TOOL) $(ARCHIVE_TOOL_FLAGS) $(TARBALLS_LOCATION)/$(ARCHIVE)
-	cp libdovi-Cargo.lock $(PLATFORM)/Cargo.lock
 	cp dolby_vision-Cargo.lock $(PLATFORM)/dolby_vision/Cargo.lock
-	cd $(PLATFORM); $(CARGO) fetch $(CARGO_BASE_OPTS) --locked
+	$(CARGO) fetch $(CARGO_BASE_OPTS)
 
 $(LIBDYLIB): $(PLATFORM)
 	$(CARGO) cbuild $(CARGO_BUILD_OPTS)
```

What do you think? Sorry you have to deal with this.

**Comment by fuzzard** [comment]
The two lock files have wildly different content though. Why would we not use lock files for both? We don't want random upstream package changes for both levels don't we?

The intent is we need to lock down all rust usage to explicit lib versions so we don't have to wake up to Jenkins breaking anytime some random package that gets pulled in requires newest rust (or whatever else)

**Comment by quietvoid** [comment]
> The two lock files have wildly different content though. Why would we not use lock files for both? We don't want random upstream package changes for both levels don't we?

We only build the `dolby_vision` folder lib, whatever is in the parent does not matter and has no impact.
The subfolder lib is independent and I tested that the parent lock file makes no difference.

**Comment by fuzzard** [comment]
All good. Just wanting to make sure I don't have to revisit this again. Thanks for the input 

Test failure in Linux is unrelated. Merging to get CI back in order

**Pull request merged**
