### PR TITLE
[cmake] fix lowercase x11

### PR DESCRIPTION
**Pull request by lrusak**
@hauihau thanks for pointing this out.

### CODE REVIEW

**Comment by hudokkow** [comment]
jenkins build this please

**Comment by pkerling** [comment]
What about when the user specifies `X11` (uppercase) by accident? Shouldn't we just always lowercase `CORE_PLATFORM_NAME`?

**Comment by hudokkow** [comment]
Yep, you're right.
Code needs some refactoring. I'll do it later if no one beats me to it.

**Comment by wsnipex** [comment]
we already use lower case: https://github.com/xbmc/xbmc/blob/master/CMakeLists.txt#L107-L111
So this PR shouldn't fix anything

**Comment by pkerling** [comment]
@wsnipex this only applies to `CORE_PLATFORM_NAME_LC` which is only available in the toplevel `CMakeLists.txt` and only used for the `include`. `CORE_PLATFORM_NAME` can still have uppercase characters.

**Comment by hauihau** [comment]
From my understanding, thats not correct: you're saving the lowercase value of **CORE_PLATFORM_NAME** in **CORE_PLATFORM_NAME_LC**.

FindVAAPI.cmake uses **CORE_PLATFORM_NAME** in a STREQUAL check against lowercase x11 while **CORE_PLATFORM_NAME** contains uppercase X11. Also cmake output says uppercase X11:

```
-- #---- CONFIGURATION ----#
-- -- PATH config --
-- Prefix: /usr
-- Libdir: /usr/lib64
-- Bindir: /usr/bin
-- Includedir: /usr/include
-- Datarootdir: /usr/share
-- Datadir: /usr/share
-- Docdir: /usr/share/doc/kodi-9999
-- Platform: X11
[snip]
```

**Comment by hudokkow** [comment]
That ^^

**Comment by wsnipex** [comment]
ok, then everything that currently uses CORE_PLATFORM_NAME as condition should be changed to use CORE_PLATFORM_NAME_LC instead

**Comment by hudokkow** [comment]
I'll refactor the code and fix the logic. Meanwhile this can go in.

**Comment by hudokkow** [comment]
Okido!

**Pull request closed without merging**
