### PR TITLE
[guilib] oninfo for controls

### PR DESCRIPTION
**Pull request by mkortstiege**
This adds "oninfo" for controls. /cc @BigNoid, @phil65, @ronie

P.S: Messed up the original branch and pr (https://github.com/xbmc/xbmc/pull/7453) for some reason. Thanks @xhaggi for pushing this to a separate branch!

### CODE REVIEW

**Comment by phil65** [comment]
Now you only need to kill toggle behaviour and this is good to go. :P

**Comment by HitcherUK** [comment]
Does this also fix the crash when using `<oninfo>Info</oninfo>`?

**Comment by ronie** [comment]
> Does this also fix the crash when using <oninfo>Info</oninfo>

nope, still crashes.

other than that, it seems to be working ok.

**Comment by mkortstiege** [comment]
Will have a look at it within the next days again.

**Comment by ronie** [comment]
looks like it breaks 'info' in the fullscreen video window in Confluence.

it still works for skins who use the DialogVideoInfo.xml, but Confluence uses the method to toggle this info in VideoFullScreen.xml

**Comment by ronie** [comment]
could someone enlighten me what the problem with the info toggle is?
i know there was some discussion about it, but i probably didn't pay much attention to it.
i promise this time i will :-)

**Comment by phil65** [comment]
if we decide to allow oninfo inside dialogs then this would lead to unpredictable behaviour because, depending on which control is focused, either another dialog opens (--> Actor info for example) or the actual dialog closes. That is very weird in terms of UX and shouldnt be done. So either we disallow oninfo inside dialogs or we remove the toggle. I'm fine with both.

**Comment by ronie** [comment]
the problem with removing the info toggle is that we create another ux inconsistency,
namely that 'c' *does* toggle the context menu, 'm' *does* toggle the osd menu, 'o' *does* toggle the onscreen codec info.. and so on.
over the years we've put great effort in it to make sure each button will both open and close it's dialog.

**Comment by phil65** [comment]
well, "great effort" equals to adjusting some few lines in keymaps ;) But I admit, you´re also right, I didnt really take that into account. Perhaps a sane solution would be to disallow <oninfo> inside infodialogs?

**Comment by HitcherUK** [comment]
Or keep the same logic for the official skin but let others do what they want - that way the only complaints will be in the skins specific thread and not our own (or at least we can redirect them to the specific skin thread).

**Comment by mkortstiege** [comment]
> Or keep the same logic for the official skin but let others do what they want

I think this will be pretty weird for the average users. The more i think about it, the more i think we should keep the toggling. With the upcoming `onclick` override we don't need `oninfo` in the various info dialogs.

**Comment by BigNoid** [comment]
> With the upcoming onclick override we don't need oninfo in the various info dialogs.

Yeah that wont work for the actor list for example, but keeping the toggle is indeed better in terms of consistency. @ronie has a valid point, everywhere else the button that opens the dialog can also close it, so we should keep that.

**Comment by phil65** [comment]
Yeah, the onclick override could make oninfo in info dialogs superfluous to some extent.

imo we should still disallow silly stuff like makin oninfo starting a script when actor list has focus and closing the actual dialog when sth else is focused. Behaviour could be completely different across different skins which would become very weird in terms of UX. It would be much better to just rely on onback to close modal dialogs.

Anyways, before we cannot find an agreement, merge in whatever you want, then look at the fallout for next release and adjust if needed then.

**Comment by mkortstiege** [comment]
Rebased and removed the toggle nuke commit for now.

**Comment by ronie** [comment]
tested, the issue with 'info' in the fullscreen video window in Confluence is fixed now.

**Comment by Razzeee** [comment]
jenkins build this please

**Comment by mkortstiege** [comment]
Build error is unrelated. How to proceed with this one?

**Comment by ronie** [comment]
ok to merge as far as i'm concerned.

@BigNoid, @phil65, @HitcherUK your thoughts?

**Comment by BigNoid** [comment]
Good to go imo

**Comment by HitcherUK** [comment]
Go for it.

**Comment by MilhouseVH** [comment]
Hi, was it intentional that this PR would ignore the default action when clicking OK/Enter on videos while navigating in Files?

If you set `Settings` > `Video` > `File lists` > `Default select action` to `Show Information`, then navigate to a video in `Video` > `Files`:

* With this PR: clicking OK on the video doesn't open the Info panel, instead it starts playback
* Without this PR: clicking OK shows the Info panel (as configured)

Reported on the [forum](http://forum.kodi.tv/showthread.php?tid=238393&pid=2139378#pid2139378).

**Comment by anaconda** [comment]
https://github.com/xbmc/xbmc/pull/8169/files#diff-a4b7db2cbfe04fea9817e8014e79fe25R676 -> `OnItemInfo`

**Comment by mkortstiege** [comment]
https://github.com/xbmc/xbmc/pull/8273 should take care of it. Thanks again @anaconda.

**Pull request merged**
