### PR TITLE
Fix for devinput driver in newer version of lirc

### PR DESCRIPTION
**Pull request by Zlopez**
## Description
This fix will add two new sections to Lircmap.xml

## How Has This Been Tested?
Tested on Fedora 25 using IR controller for [Beebox](http://www.asrock.com/Microsite/Beebox/).
Installed version of lirc 0.9.4 and kernel 4.8.8-300.

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

Newer version of lirc is creating two section in /etc/lirc/lircd.conf.d/devinput.lircd.conf devinput-32 and devinput-64.
This fix should prevent the remote controller to stop working when updating lircd.

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Any news? Will this pull request be merged?

**Comment by LipkeGu** [comment]
can we fix the mceusb remotes also?

**Comment by Zlopez** [comment]
I don't have mceusb remote, so I'm unable to reproduce the problem.

**Comment by Paxxi** [comment]
I think it's waiting for testing, not forgotten about

**Comment by LipkeGu** [comment]
@Zlopez Kodi cant handle the keys: only a few keys are working. here is the keymap for the mce remote: https://github.com/piBMC/linux/blob/rpi-4.4.y/drivers/media/rc/keymaps/rc-rc6-mce.c

**Comment by Zlopez** [comment]
@LipkeGu Maybe submit a new [bug](http://kodi.wiki/view/how-to:submit_a_bug_report). As I said before, I don't have the mceusb remote, so I can't test if my fix will work.

**Comment by AsciiWolf** [comment]
Is this pull request still relevant?

**Comment by Paxxi** [comment]
@MilhouseVH @wsnipex thoughts on this? Anyone able to test it?

**Comment by stefansaraev** [comment]
this PR looks good. just push it.

**Pull request merged**
