### PR TITLE
Kodi-20.0-Nexus alpha1/alpha2/alpha3/Master crash on start-up on  Android 5.1.1

### PR DESCRIPTION
**Pull request by Micromax56**
**Description**

Kodi-20.0-Nexus alpha1/alpha2/alpha3/Master crash on start-up on  Android 5.1.1.

Ref :https://github.com/xbmc/xbmc/issues/22069

**Motivation and context**

As reported in the issue #22069, the reason of the crash is due to a FATAL EXCEPTION detected by Android   5.1.1. during the loading of libass.so Shared Library.

--------- beginning of crash
E/AndroidRuntime( 8096): FATAL EXCEPTION: main
E/AndroidRuntime( 8096): Process: org.xbmc.kodi, PID: 8096
E/AndroidRuntime( 8096): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__gxx_personality_v0" referenced by "libass.so"...

Since the issue happens already with alpha1, I have git cloned Kodi till alpha1 tag and via multiple different git checkout, building and testing every time the .apk,  I have identified that the pull causing the problem is:

[tools/depends][target] fontconfig bump 2.14.0 #21310 

After several tests, using also the latest official  version 2.14.1, my conclusion is that the issue is caused by usage of the Meson Build system. Building fontconfig  with  the "old" autoconf system the problem disappear.

 **How has this been tested?**

Tested on:

**Amazon Fire TV Basic Edition**:
   Model : AFTT
  Hardware : mt8127
  SW : Fire OS 5.2.9.2 (681771820)  (based on Android 5.1.1)

**Samsung Galaxy Grand Prime smartphone** with Android version 5.1.1

Tested also  on other Android versions:

Zidoo X10                                        :  Android 6.0.1 
Fire TV Stick 4K Max                        :  Android TV 9.0.0 
NVIDIA SHIELD Android TV Pro      :  Android TV 11.0.0

 **What is the effect on users**?

Kodi 20 not usable on Android 5.1.1

 **Types of change**

- [X ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Comment by Micromax56** [comment]
I have no  idea why the build fails on IOS-ARM64 and TVOS.  

Probably something related to this old commit

https://github.com/xbmc/xbmc/commit/4d39eaee96fffaec1108c85aceaaa33603baeec9

is missing. 

I  don’t have experience on these 2 platforms and time to investigate.

I leave the “Kodi Dream Team”  to further analyze what should be added,  if there is interest in the PR. 

For me it is working on my own Android Kodi fork and that is enough.
Bye

**Comment by fuzzard** [comment]
Thanks for the PR, however at the moment we think we will leave it as is.

Android 5 is a bit long in the tooth, we have no active core android devs as is, so we'll probably just change our min sdk to android 6.

Ideally we'd like whatever needs to be fixed by the fontconfig lib build differences to be handled upstream. We are wanting to move most deps to high level build systems where available (eg meson/cmake) to more easily accommodate true cross platform (eg including windows) more easily than our current system allows.

If i have time i'll try and have a look at the PC files output from meson/autoconf to see if theres a difference. im guessing theres a linker flag missing on the meson generated version or something to that effect.

**Comment by da-anda** [comment]
great job at tracking down the root cause of this issue @Micromax56. We really appreciate the time and effort you put into this, but as fuzzard already pointed out, it would be better if the bug could be fixed upstream.

**Comment by Micromax56** [comment]
On https://www.freedesktop.org/wiki/Software/fontconfig/ it is  stated that:

****Fontconfig does not:**

render the fonts themselves (this is left to [FreeType](https://www.freedesktop.org/wiki/Software/FreeType/) or other rendering mechanisms)**

So I think that any issue building using FreeType / FreeType with harfbuzz  or other rendering mechanisms should not be solved by the upstream and should be addressed outside fontconfig build

See #22165

**Pull request closed without merging**
