### PR TITLE
Add support for Matroska DolbyVision

### PR DESCRIPTION
**Pull request by Stanzilla**
This is a rebase of https://github.com/xbmc/xbmc/pull/18965

## Description

This commit adds support to Dolby Vision combined layer present on mkv files.
Matroska recently added a AdditionBlockMapping to support Dolby Vision or other private metadata.

## Motivation and context

This commit is important to bring support to the ever growing format of Dolby Vision in mkv files.

## How has this been tested?

This has been tested exclusively with the Nvidia Shield TV Pro (2019).
Dolby Vision pass through is only possible with Apple TV and a few android boxes like the Nvidia Shield, or the Fire Stick.

## What is the effect on users?

DolbyVision is now usable on Nvidia Shield devices

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by thexai** [comment]
This is a bad implemented hack for one specific device. Is not acceptable.

**Comment by Stanzilla** [comment]
@thexai are there any plans for an official implementation then?

**Comment by thexai** [comment]
There are some related work in progress here:

https://github.com/xbmc/xbmc/pull/19099
https://github.com/xbmc/xbmc/pull/20422

although no ETA

**Comment by quietvoid** [comment]
the ongoing plan is getting the patches in ffmpeg, to be able to get the side data like you're doing here.

**Pull request closed without merging**
