### PR TITLE
Revert "CGUIMediaWindow: properly save item position"

### PR DESCRIPTION
**Pull request by xhaggi**
This reverts commit f45340e84961dddb7b98d7ea7d14fa7aba816128 from PR #8873 

@Razzeee ping

### CODE REVIEW

**Comment by xhaggi** [comment]
jenkins build and merge

**Comment by Paxxi** [comment]
after some discussion +1

**Comment by wiromare** [comment]
Ok

but before my changes it wasn't working like it should, do you also have a plan to fix in a different manner? 

anyway i'm glad if i have pointed you on a strange behavior

**Comment by Razzeee** [comment]
@xhaggi 
thank you

**Comment by xhaggi** [comment]
@wiromare thanks anyway for pointing out this issue. I'm sure we'll find a proper solution.

**Pull request merged**
