### PR TITLE
Macro cleanup

### PR DESCRIPTION
**Pull request by lrusak**
most of this was done with sed commands but I took a look at the diff after and had to fixup some stuff but there might be some minor formatting issues.

I did a build and run test on linux but it seems that this touches a lot of windows stuff.

### CODE REVIEW

**Comment by afedchin** [comment]
what's wrong with these macros? I against removing them

**Comment by lrusak** [comment]
I guess I never wrote _why_ these should be removed:

 1. They are antiquated and obfuscate the code.
 2. They are used sporadically through the code which causes confusion.
 2. The term `SAFE` is a misnomer as other references may not be dereferenced
 3. Many cases would be better using smart pointers in the cases where we need to keep resetting and reusing the pointer.

There may be other reasons but that's what I can think of.

**Comment by Paxxi** [comment]
I agree that we should probably get rid of these macros but I don't think expanding them is useful. They should be replaced by smart pointers, CScopeGuard or for com I guess CComPtr and until then the macros might as well stay

**Comment by lrusak** [comment]
@Paxxi I only do what I am able to. I can look into replacing some with smart pointers but I am not able to build or test on windows at all so I will need help there. So for me simply expanding the macros is all that I can do for windows as I cannot just rely on Jenkins.

So please consider this PR a WIP even if it's just to start a discussion about what to do.

**Comment by Paxxi** [comment]
If you do a pr with the changes I'll add the windows bits to it 😀

**Comment by lrusak** [comment]
Did a bunch of stuff here https://github.com/xbmc/xbmc/compare/master...lrusak:macro-cleanup-test
@FernetMenta please take a look

**Comment by FernetMenta** [comment]
@lrusak passing the object a unique_ptr points to as plain pointer to other objects abuses the concept of smart pointers. I don't see an improvement here.

**Comment by Paxxi** [comment]
You're wrong there @fernetmenta. Unique_ptr is used for ownership to avoid leaking memory. If other parts do require access then a plain pointer is the correct choice. The idea being a plain pointer is always non owning and should never be deleted.

See https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Sure source for more details and reasoning

**Comment by FernetMenta** [comment]
According to my guidelines it is wrong (or at least not ideal)
What we got now with https://github.com/xbmc/xbmc/pull/13295 is much better than this first attempt.

**Comment by lrusak** [comment]
Even if this isn't going to be merged directly it can be used as a guide to see what can be cleaned up

**Comment by lrusak** [comment]
This is looking much better! Thanks guys!

**Pull request closed without merging**
