### PR TITLE
[binary addons] make sure CORE_SYSTEM_NAME is set

### PR DESCRIPTION
**Pull request by stefansaraev**
after #7570 PLATFORM may be undefined for standalone builds. credits to @wsnipex 

//cc @Montellese

### CODE REVIEW

**Comment by Montellese** [comment]
I don't know how binary addons are built in standalone mode but this doesn't look like the right fix. A few addons depend on CORE_SYSTEM_NAME being properly set so if it isn't properly set at this point other things might go wrong as well. Why can't CORE_SYSTEM_NAME be properly set for standalone builds?

**Comment by wsnipex** [comment]
before the auto-set library change, CORE_SYSTEM_NAME was not needed in any addon for standalone builds.

**Comment by Montellese** [comment]
You're right our current addons don't use `CORE_SYSTEM_NAME` but (almost) all retroplayer binary addons do so in the long run having it set will be a must (unless we want to use a different approach to determine the build target).

**Comment by wsnipex** [comment]
well, on native (standalone) builds, CORE_SYSTEM_NAME = CMAKE_SYSTEM_NAME

**Comment by Montellese** [comment]
I have no idea how you build for standalone (i.e. how you call `cmake`) but it seems that `CORE_SYSTEM_NAME` is not properly set which is usually taken care of by either manually passing it to `cmake` or by the fallback to the lower-cased `CMAKE_SYSTEM_NAME` in `project/cmake/addons/CMakeLists.txt`. Having binary addon buildsystems check `CORE_SYSTEM_NAME` and `CMAKE_SYSTEM_NAME` sounds odd to me especially since `CORE_SYSTEM_NAME` is expected to be `linux` while `CMAKE_SYSTEM_NAME` is `Linux`.

**Comment by wsnipex** [comment]
yes, its lower case CMAKE_SYSTEM_NAME, just like this PR does. We could set CORE_SYSTEM_NAME in kodi-config.cmake as well, but it doesn't make a difference.

**Comment by Montellese** [comment]
For the retroplayer addons it's not enough to properly set `PLATFORM` in `addon-helpers.cmake` because they string compare `CORE_SYSTEM_NAME` to `linux`, `windows`, `android` and so on. And that won't work for standalone in the current setup from what I can tell due to this PR.

Obviously we can decide to ignore those binary addons that aren't part of the official addons yet but I'm just pointing out that this will need a different fix as soon as those addons need to be supported.

**Comment by wsnipex** [comment]
ok, then we'll have to add it to kodi-config.cmake. There is no other central place in the standalone case.

**Comment by garbear** [comment]
@wsnipex here's the steps I use to build my game add-on: https://github.com/kineticgar/game.netplay/blob/master/Readme.md (section `Building stand-alone (development)`)

Something weird I noticed (at least in 15 beta 2) is that CORE_SYSTEM_NAME isn't defined in linux, leading to this hacky ducktape fix: https://github.com/kineticgar/game.netplay/commit/0e4c3f3. On osx, 
CORE_SYSTEM_NAME resolves to "darwin" as it should

**Comment by Montellese** [comment]
@garbear: This is exactly what I'm talking about. Addon buildsystems shouldn't have to make these kind of hacks because they should be able to rely on `CORE_SYSTEM_NAME` to be defined. On non-standalone builds we pass it to `cmake` or use the fallback in `project/cmake/addons/CMakeLists.txt` and from there pass it on to the binary addons being built.

**Comment by stefansaraev** [comment]
```
diff --git a/project/cmake/kodi-config.cmake.in b/project/cmake/kodi-config.cmake.in
index 76626ec..ac08226 100644
--- a/project/cmake/kodi-config.cmake.in
+++ b/project/cmake/kodi-config.cmake.in
@@ -12,4 +12,8 @@ ENDIF()
 LIST(APPEND CMAKE_MODULE_PATH @APP_LIB_DIR@)
 ADD_DEFINITIONS(@ARCH_DEFINES@ -DBUILD_KODI_ADDON)
 
+if(NOT CORE_SYSTEM_NAME)
+  string(TOLOWER ${CMAKE_SYSTEM_NAME} CORE_SYSTEM_NAME)
+endif()
+
 include(addon-helpers)
```

should I replace this PR with the patch above, @wsnipex ?

**Comment by wsnipex** [comment]
@stefansaraev yes, that should work

**Comment by Montellese** [comment]
Yes that's a better approach IMO.

**Comment by stefansaraev** [comment]
thanks @wsnipex @Montellese 

jenkins build addons please

**Comment by Montellese** [comment]
Fine with me, thanks. @wsnipex your button.

**Comment by garbear** [comment]
I can confirm this fixes ${CORE_SYSTEM_NAME} not being set for standalone linux builds. thanks guys! this was blocking an OpenELEC RetroPlayer, so i'll get back on that endeavor

**Pull request merged**
