### PR TITLE
Fix several settings that broke after the last few ServiceManager refactorings

### PR DESCRIPTION
**Pull request by garbear**
This fixes several settings that have broke over the last few weeks:

* Enable/disable mouse
* Peripherals dialog
* Peripheral drivers dialog
* Controller configuration
* Test rumble
* CEC language locale
* Add-on autoupdates

## How Has This Been Tested?
Enable/disable mouse and controller configuration guaranteed to be working. Haven't tested the add-on autoupdates setting.

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by Montellese — APPROVED** [review]
This looks good and is finally moving in the direction that I planned from the beginning. We could even go as far as passing the `CSettings` instance as a paramter to `CRepositoryUpdater`, `CInputManager` and `CPeripherals` to reduce the dependency on `CServiceBroker`.

**Review by lrusak — APPROVED** [review]

**Comment by garbear** [comment]
> We could even go as far as passing the `CSettings` instance as a paramter to `CRepositoryUpdater`, `CInputManager` and `CPeripherals` to reduce the dependency on `CServiceBroker`.

I thought of this, but settings are brought up *really* early so there's very little in our codebase that can interact with settings before it's ready.

Everything depends on settings, so I can see passing it as a parameter going down a deep rabbit hole.

**Comment by garbear** [comment]
jenkins build this please

**Comment by da-anda** [comment]
the CEC settings dialog still has not settings labels. Is this something you could look into as well please? I tested this PR as part of latest Milhouse build.

**Comment by garbear** [comment]
@da-anda like this?

peripheral settings

That is caused by the error fixed in #12518. The current version of the PR doesn't fix this, but a previous version did that was modified per some suggestions. You can bring up this issue over there if you want.

**Comment by garbear** [comment]
jenkins build this please

**Pull request merged**
