### PR TITLE
Dvd autoplay during active player

### PR DESCRIPTION
**Pull request by Falcosc**
## Description
enable unused code to be able to autorun optical disk during listening video or audio

## Motivation and Context
https://forum.kodi.tv/showthread.php?tid=324604
It does take a while until the optical disk is recognized. It's nice to be able to listen musik or tv during the optical drive is searching for content.

## How Has This Been Tested?
Does work with my host on Windows 10 64Bit on Apollo Lake with PVR Client and Movie Playback from SMB without any issues. External and internal player does work very well.

## Types of change
- not a Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves existing functionality)
- not a New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
http://kodi.wiki/view/Settings/Videos
http://kodi.wiki/view/Settings/Player/Discs
- [x] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

I did ask for needed settings because this is a breaking change. But it's may not needed to make this configureable.

### CODE REVIEW

**Comment by notspiff** [comment]
11 days, no response, done as requested in forums. i'm taking action.

**Comment by notspiff** [comment]
jenkins build this please

**Comment by Voyager1** [comment]
Apologies - didn't see the request. I'll review.

**Comment by notspiff** [comment]
no reason to apologize. i wasn't sulking, just explaining my actions :)

**Review by Voyager1 — APPROVED** [review]

**Comment by Falcosc** [comment]
Wiki change is done

**Comment by Falcosc** [comment]
There is maybe a problem with that.
I did share the current build with my friends and one of them did get an autoresume of the optical disc during optical disc playback.

I don't know in which usecase these events get fired, I couldn't reproduce it. But he told me that it did happen once during DVD playback. I would guess that something like this could happen because we don't access the drive all the time.
Unfortunantly I don't spend any time on dvd playback inside kodi, I use an external player for bluray drm handling, at least there a no autoresume issues with powerdvd.

An check for active optical disk playback should fix this.

**Pull request merged**
