### PR TITLE
[osx/ios] - add support for compiling with Xcode7 MacOSX SDK 10.11 and iOS SDK 9.0

### PR DESCRIPTION
**Pull request by Memphiz**
As the topic says. Xcode7 went final today iirc. Thx to amet and davilla who did the grunt work on this.

### CODE REVIEW

**Comment by Memphiz** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
*whistles*

**Comment by EmbeddedFiedel** [comment]
With the change made in commit [cffd39f](https://github.com/Memphiz/xbmc/commit/cffd39fe8cb7d47c1d43a350af5936dfb1dea9a2) binary extensions are not signed when a code_sign_identity is used.

Either [ "${CODE_SIGN_IDENTITY}" != "iPhone Developer" ] should be deleted or changed back to [ "${CODE_SIGN_IDENTITY}" == "iPhone Developer" ].

**Comment by Memphiz** [comment]
Let me point me to the readme which makes this consistent again:

https://github.com/xbmc/xbmc/blob/master/docs/README.ios#L181

From now on you need to select the iOS Developer profile (i know there is a typo here in the readme). I know that this might be tricky if you have multiple signing identites. But you already spotted the needed change in that case.

**Pull request merged**
