### PR TITLE
Curl improvements

### PR DESCRIPTION
**Pull request by arnova**
This PR syncs our select/sleep handling for Curl with upstream. Apparently this never worked properly on at least Windows. Furthermore I added a change where we Sleep between Curl retries as this may increase the chances of a successful recovery in several scenarios (I'm still looking for an optimum here, in case other people have a better idea, please speak up :-)).

### CODE REVIEW

**Comment by arnova** [comment]
@paxxi: Please review. jenkins build this please

**Comment by arnova** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
@arnova Have you seen an issue this fixes? I havent noticed any trouble with this piece of code during testing.

**Comment by arnova** [comment]
@Paxxi : Well I haven't seen the select() issue since it mostly concerns Windows but I came from upstream Curl. The issue with no delay for (successive) retries is an issue I've seen several times with certain temporary issues (e.g. WiFi failing momentarely).

**Comment by arnova** [comment]
Any objections against this?

**Comment by Paxxi** [comment]
No objections from me

**Comment by arnova** [comment]
jenkins build this please

**Pull request merged**
