### PR TITLE
[davfile] use PROPFIND for Stat() and Exists()

### PR DESCRIPTION
**Pull request by mkortstiege**
See title. @arnova for review and testing please.

### CODE REVIEW

**Comment by arnova** [comment]
Will test tonight. Are we sure the stat using propfind always works (we don't need a fallback) ?

**Comment by mkortstiege** [comment]
Not entirely sure, just noticed the HEAD requests and that we're doing this for the directory part as well.

**Comment by arnova** [comment]
Seems to work fine here :)

**Comment by arnova** [comment]
jenkins build this please

**Comment by mkortstiege** [comment]
Thanks for testing. Should we merge this one and see if there's any fallout?

**Comment by arnova** [comment]
Sure, I'm fine with it.

**Comment by Montellese** [comment]
Is it possible that this broke WebDAV file existance checks? See http://trac.kodi.tv/ticket/15958 for an issue with currently nightlies.

**Pull request merged**
