### PR TITLE
[Estuary] some delicate touches to the channelgroup selector

### PR DESCRIPTION
**Pull request by ronie**
ping:
- @ksooo 
- @xhaggi 
- @da-anda 
- @jjd-uk 

ch-nf

ch-fo

### CODE REVIEW

**Review by ksooo — APPROVED** [review]
No doubt, that's an improvement. Thank you.

**Comment by xhaggi** [comment]
+1

**Comment by da-anda** [comment]
❤️ thanks ronie, and also thanks for the hidden easter eggs in the screenshots, made me laugh 😉

**Comment by ksooo** [comment]
@ronie unfortunately, after your changes the channelgroup seelctor cannot be used with a mouse anymore. Just try and you will see what I mean. Could you please take a look and maybe come up with a fix? 

What would be really nice would be to be able to click on the arrows you introduced to scroll the channel selector bar...

**Comment by ronie** [comment]
works fine for me?
just focus the first item and use the scrollwheel.

**Comment by ksooo** [comment]
Scroll wheel (== vertical spin) to move left/right? Not very intuitive if you ask me. At least that came not to my mind. And without a scroll wheel you are lost.

**Comment by ronie** [comment]
nope, scroll-wheel != vertical spin.
scroll-wheel scrolls in the direction defined by the `<orientation>` tag of a container.

**Comment by ksooo** [comment]
Physically it's always vertical spin. The hardware layout does not change according to the orientation tag. ;-) That's what I mean. But really no big deal; Personally I never use a mouse to control Kodi.

**Pull request merged**
