### PR TITLE
Ffmpeg bump 27 master

### PR DESCRIPTION
**Pull request by fritsch**
This needs rebasing (after) 2.6 branch version is in master and backported to v15.

Then we can bump master to 2.7.

### CODE REVIEW

**Comment by fritsch** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
same story here. using a branch instead of a version is wrong

**Comment by fritsch** [comment]
Yeah - our "version" tagging scheme is wrong btw. We tag 2.6.3 for example but have rebased on the 2.6 stable branch ...

**Comment by fritsch** [comment]
Updated - will rebase once we have decided what we want to do with master and 2.6.3

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
Fails on osx. Maybe @Memphiz can take a look on possible adjustments

**Comment by Memphiz** [comment]
Mhhh kicked some manual builds on jenkins - looks like this is one of "those" PRs where it acts up.

I tried to compile this locally on my rig.

@fritsch where are those ssl symbols supposed to come from?

http://pastebin.com/CKjLLrzp

Seems i miss some dep?

**Comment by Memphiz** [comment]
@fritsch looks like this patch in ffmpeg:

https://ffmpeg.org/pipermail/ffmpeg-devel/2015-May/172663.html

Do i need to add --disable-securetransport now? (the comment for this flag sounds a bit miss leading to me ... i mean ... i don't get what it does ;) ).

**Comment by stefansaraev** [comment]
@Memphiz 

> Do i need to add --disable-securetransport now

if openssl or gnutls is not compiled / enabled on osx, yes - disable it.

it's apple specific thing. http://opensource.apple.com/tarballs/libsecurity_ssl/

**Comment by fritsch** [comment]
```
+  --disable-securetransport disable Secure Transport, needed for TLS support
+                           on OSX if openssl and gnutls are not used [autodetect]
```

As we use one of those others I think you can disable it.

**Comment by Memphiz** [comment]
haha 2 opposite opinions here ... yes we use gnutls for osx ... what @stefansaraev said makes sense somehow ... do we need to bump gnutls to get those securetransport features?

**Comment by Memphiz** [comment]
args ... so we need to add libsecurity_ssl to depends?

**Comment by Memphiz** [comment]
man how damn stupid can one word a comment *Grr* ... new try. We need to disable it because its covered by our gnutls ... right? ^^

**Comment by stefansaraev** [comment]
> haha 2 opposite opinions here ... yes we use gnutls for osx ... what @stefansaraev said makes sense somehow ... do we need to bump gnutls to get those securetransport features?

ouch. gnutls pain. well god knows, you either have to bump it or it's a bug in the buildsystem

> args ... so we need to add libsecurity_ssl to depends?

no.

are you sure gnutls is compiled and picked by ffmpeg ? jenkins logs are gone. meh ;)

**Comment by Memphiz** [comment]
imo the autodetection for this stupid secure transport thingy is broken ... i know that gnutls works because we can open https urls ;)

**Comment by fritsch** [comment]
I read it like: disable secure support, which would be needed though, but if you have openssl or gnutls, disable it, cause those can achieve what you want :-)

**Comment by stefansaraev** [comment]
disable it, check jenkins log if you see "https" in transports, check if https:// still works :)

**Comment by Memphiz** [comment]
and i read it in a similar way - but in addition it should autodetect that gnutls is there and so it should not even try to link with this securelib thingy

**Comment by Memphiz** [comment]
PR sent to fritsch ... verified that https is still working with disabled libsecurity_ssl

**Comment by MartijnKaijser** [comment]
Good for merge or do you want to squash commits?

**Comment by fritsch** [comment]
jenkins build this please

**Pull request merged**
