### PR TITLE
[videoplayer] - Correctly save streamdetails for DVD/Bluray iso etc

### PR DESCRIPTION
**Pull request by the-black-eagle**
## Description
Backport of #19510 and fix  #19645 - Saves the stream details of the currently playing DVD/Blu-ray ISO to the database.  These details include video and audio codecs, aspect ratio, subtitles etc.

## Motivation and context
This functionality was present in Kodi Krypton but has been missing since.

## How has this been tested?
Tested locally with bluray and dvd iso's and video_ts/bdmv directory structures.  Also tested by several forum members.

## What is the effect on users?
Restores Kodi's ability to save the stream details from a DVD/Blu-ray ISO or video_ts/bdmv directory to the database when the ISO etc is played.  These details include video and audio codecs, aspect ratio, subtitles etc. The details will only be saved for items that don't already have details.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by arnova — APPROVED** [review]

**Comment by arnova** [comment]
@the-black-eagle : Please backport my crash fix to this as well.

**Comment by the-black-eagle** [comment]
@arnova Sure.  Branch is ready and waiting with the fix in it, just really awaiting confirmation it doesn't cause another issue before I push it.

**Comment by arnova** [comment]
> @arnova Sure. Branch is ready and waiting with the fix in it, just really awaiting confirmation it doesn't cause another issue before I push it.

Of course. I just wanted to make sure it wouldn't get forgotten....

**Comment by DaveTBlake** [comment]
Awaiting inclusion of backport of related crash fix https://github.com/xbmc/xbmc/pull/19645 before merge

**Comment by the-black-eagle** [comment]
[**@DaveTBlake**](https://github.com/DaveTBlake) commented on [1 May 2021, 16:46 BST](https://github.com/xbmc/xbmc/pull/19625#issuecomment-830652406 "2021-05-01T15:46:48Z - Replied by Github Reply Comments"):
> Awaiting inclusion of backport of related crash fix https://github.com/xbmc/xbmc/pull/19645 before merge

@DaveTBlake Done.

**Pull request merged**
