### PR TITLE
[settings/cosmetic] Replace "computer" by "device" in setting help text

### PR DESCRIPTION
**Pull request by sy6sy2**
## Description
As proposed by @fuzzard in https://github.com/SylvainCecchetto/xbmc/issues/70, the word "device" seems to be better and more generic that "computer" (because we have devices like iPhone, Apple TV, etc...).

## Motivation and Context
Just a little cosmetic fix.

## How Has This Been Tested?
Not tested because not really a code modification.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [X] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by notspiff — APPROVED** [review]

**Comment by jjd-uk** [comment]
There a good chance I did that label and if so it most likely a copy and paste from the wiki. Agreed that "device" is a better fit considering all the platforms we support.

**Comment by da-anda** [comment]
there is another reference to `computer` in the PO file, mind changing that as well? It's just in a contextual help string, but still might be good to change it there as well.

**Comment by SylvainCecchetto** [comment]
Should be ok now?

**Comment by da-anda** [comment]
thanks

**Pull request merged**
