### PR TITLE
binary addons: bring win32 in line with how the "kodi" dependency is prepared/provided

### PR DESCRIPTION
**Pull request by Montellese**
This brings win32 in line with all the other platforms on how the "kodi" dependency (which is just a bunch of headers and `kodi-config.cmake`) is prepared and provided by the binary addons cmake buildsystem. I don't remember why I didn't do this back when `prepare-env.cmake` was introduced but it was probably because we were still using all the prebuilt dependencies on win32.

This also safes us some code duplication and moves all the different platforms closer together in the cmake build system.

### CODE REVIEW

**Comment by Montellese** [comment]
jenkins build this please

**Comment by Montellese** [comment]
That's funny. All individual builds succeeded but the whole build failed (see http://jenkins.kodi.tv/job/BuildMulti-PR/2149/)?!?!

**Comment by Memphiz** [comment]
yep - network issue when jenkins wanted to notify github that it went successfull ... seldom as it seems - but just a matter of time that network issues hit this short spot hehe.

**Comment by wsnipex** [comment]
in case it matters: +1 :)

**Pull request merged**
