### PR TITLE
[droid] fix crashing on addon installation

### PR DESCRIPTION
**Pull request by wsnipex**
Crossguid uses a jni based implementation on droid that is crashing all over and corrupting the stack.
This PR switches droid to use libuuid instead, just like linux.
Since our libuuid in depends doesn't cross compile on droid, we switch to an easier one from e2fsprogs.
Only tested on droid..

@Montellese, @koying ping

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by Montellese** [comment]
Do we have any clue why it's crashing? Is something wrong with the JNI calls that could be patched / sent upstream?

**Comment by wsnipex** [comment]
no idea, it crashes inside system libs(don't remember the exact file atm) and gdb doesn't catch it either.

**Comment by MrMC** [comment]
jni issues will typically show up in the android log file. You have to back track from there, gdb will be useless as android pops the world out from under it.

**Comment by Montellese** [comment]
Yup would be nice to get the adb log about the JNI issue. I took a quick look at the implementation and although I haven't done any JNI in a while it looks ok to me. But there are a lot of things that one can mess up with JNI.

**Comment by koying** [comment]
We got 2 different minidumps (via breakpad) and both showed stack corruption after the "newguid" call. 
I don't see anything wrong with the jni either, but the crash is very random for me (if iI ever got it). 

Am i correct that uuids are actually created quite continuously? Looks like it only happens when installing addons...

**Comment by koying** [comment]
I''ll try with reimplementing crossguid code with our own jni lib this weekend, just in case...

**Comment by wsnipex** [comment]
Isn't it nicer to use a native implementation instead of going through java anyway? Seems >= api 21 even ships a uuid.h now.

**Comment by Montellese** [comment]
@koying: UUIDs are generated by the event log mechanism so everytime a new event is generated a UUID is generated. An event is generated on startup, when installing/uninstalling/enabling/disabling addons etc. But if it would crash on every call it should never make it past startup.

**Comment by wsnipex** [comment]
@MrMC there is absolutely zero in the logcat, no trace at all.
anyway, it crashes here: https://github.com/graeme-hill/crossguid/blob/master/guid.cpp#L246

**Comment by wsnipex** [comment]
sorry for the spam. this is the correct line: https://github.com/graeme-hill/crossguid/blob/master/guid.cpp#L254

**Comment by MartijnKaijser** [comment]
What I noticed is that it didn't happen on the nvidia shield which is 64bit and did happen on my phone which is 32bit. Maybe it's a small detail that could give some indication

**Comment by Montellese** [comment]
Might be a compatibility issue with Java's `long` data type then.
@wsnipex: Can you try http://android-developers.blogspot.ch/2011/07/debugging-android-jni-with-checkjni.html and see if you still don't get any JNI related errors in adb logcat?

**Comment by wsnipex** [comment]
It happens on shield as well. this one is from the shield with checkjni on:
http://pastebin.com/w9LAnaUa

**Comment by koying** [comment]
> Isn't it nicer to use a native implementation instead of going through java anyway? Seems >= api 21 even ships a uuid.h now.

Ah misread the PR. Yeah, if libuuid is the same for all platforms, I'm definitely +1 on using a native implementation rather than a jni one.

**Comment by koying** [comment]
ping @Memphiz and @popcornmix because it affects depend

**Comment by Memphiz** [comment]
Looks good to me in general. Maybe a comment in that Makefile why we download the e2fsprog tarball when we want to build libuuid for clearing this up a bit.

**Comment by MrMC** [comment]
An explicit comment in the makefile that it only installs libuuid would be nice for some future coder that wonders why e2fsprogs was in depends. It sort of hints to that now. But then I tend to comment the hell out of things like this where something special is being done.

Also, any reason for the change in depends Makefile code convention ?

cd $(PLATFORM)/lib/uuid ; $(MAKE) -j1

vs

$(MAKE) -j1 -C $(PLATFORM)/lib/uuid

**Comment by wsnipex** [comment]
yeah, it makes it work

**Comment by popcornmix** [comment]
Doesn't seem to break my build on Pi so no objections here.

**Comment by wsnipex** [comment]
jenkins build this please.

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
good to go?

**Pull request merged**
