### PR TITLE
[xbmc] Add missing include of <utility>

### PR DESCRIPTION
**Pull request by Paxxi**
This is a bit oppinionated, moved system includes to the bottom to try and avoid masking missing includes.

### CODE REVIEW

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
ok test again without cstdlib changes
jenkins build this please

**Comment by Montellese** [comment]
I always keep system includes at the top trying to follow the C++ Google Coding Guidelines.

**Comment by Paxxi** [comment]
@Montellese I did that as well until recently. The issue with it that I can see is that it hides missing includes in the headers

*Lib.h*
```
std::string a;
```

*Lib.cpp*
```
#include <string>
#include "Lib.h"

a = "yada"; //builds fine
```

*User.cpp*
```
#include "Lib.h"

a = "yada"; //build error
```

**Comment by Paxxi** [comment]
Seems like the google guidelines sticks them somewhat in the middle
https://google-styleguide.googlecode.com/svn/trunk/cppguide.html#Names_and_Order_of_Includes

**Comment by Montellese** [comment]
Yeah they put the include of the header belonging to the source file at the very top followed by C system includes, C++ system includes and then local includes.

**Comment by Paxxi** [comment]
That style is fine by me, I'll update this

**Comment by Paxxi** [comment]
so updated to google style include, broke pvr by reordering includes so there's some forward declarations and new includes added.
jenkins build and merge please

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
jenkins build and merge this please

**Comment by Paxxi** [comment]
jenkins build and merge this please

**Comment by FernetMenta** [comment]
you would do me favour if you refrained from doing cosmetics in core. it is really painful rebasing VideoPlayer on this.

**Comment by Paxxi** [comment]
sorry about that @FernetMenta I'm done with these major clean-ups now for a while so should hopefully not cause you any more pain.

**Pull request merged**
