### PR TITLE
Include cleanup

### PR DESCRIPTION
**Pull request by MaxKellermann**
Reduce header dependencies to speed up the build, and to make the code more correct. A lot of important includes were missing which was no problem because other headers had too many includes.

### CODE REVIEW

**Comment by lrusak** [comment]
Something broke

```
/home/jenkins/workspace/LINUX-64/xbmc/threads/test/TestSharedSection.cpp:33:23: error: invalid use of incomplete type ‘class IRunnable’
 class locker : public IRunnable
                       ^
In file included from /home/jenkins/workspace/LINUX-64/xbmc/threads/test/TestHelpers.h:25:0,
                 from /home/jenkins/workspace/LINUX-64/xbmc/threads/test/TestSharedSection.cpp:24:
/home/jenkins/workspace/LINUX-64/xbmc/threads/Thread.h:37:7: note: forward declaration of ‘class IRunnable’
 class IRunnable;
       ^
/home/jenkins/workspace/LINUX-64/xbmc/threads/test/TestSharedSection.cpp: In instantiation of ‘class locker<CExclusiveLock>’:
/home/jenkins/workspace/LINUX-64/xbmc/threads/test/TestSharedSection.cpp:86:29:   required from here
/home/jenkins/workspace/LINUX-64/xbmc/threads/test/TestSharedSection.cpp:49:8: error: ‘void locker<L>::Run() [with L = CExclusiveLock]’ marked ‘override’, but does not override
   void Run() override
        ^
```

**Comment by MaxKellermann** [comment]
Damn, I should have fixed those unit tests; I couldn't yet figure out how to use them. Stand by, I'll fix those problems very soon.

**Comment by notspiff** [comment]
make kodi-test && make test

dash possibly not there.

**Comment by MaxKellermann** [comment]
@notspiff last time I checked, all tests failed, but it worked now, thanks.

Anyway, I amended the broken commit and pushed. Let's see if that works.

**Comment by notspiff** [comment]
Sounds like you just ran make test. Sadly the test target in cmake is not
extendable, so you need a separate target if you do not want to build tests
by default.

**Comment by MaxKellermann** [comment]
No, when I previously forgot the `kodi-test` target, I wondered why this was not a dependency, and why I needed to explicitly build it. But last time, all tests failed (and not a failure to invoke `kodi-test`).

**Comment by MaxKellermann** [comment]
Jenkins build was successful with my new PR revision. Can this be merged now?

**Comment by ksooo** [comment]
https://github.com/xbmc/xbmc/pull/13914/commits/41d0aa975700eb406b84d736722aa55bd5d31b44 is was already contributed as separate PP (#13916) and should be dropped from this PR.

**Comment by ksooo** [comment]
Same for https://github.com/xbmc/xbmc/pull/13914/commits/1d1bf7c8ecc75df4ca27b7d7603e8fd64c8283e2

**Comment by MaxKellermann** [comment]
Oops, those commits slipped in during a rebase. Pushed again, duplicate commits removed.

**Comment by FernetMenta** [comment]
jenkins build this please

**Pull request merged**
