### PR TITLE
[PVR][VideoPlayer] Rework and simplify DVDInputStreamPVRManager.

### PR DESCRIPTION
**Pull request by ksooo**
- Simplified interface between PVR inputstream implementation (`CDVDInputStreamPVRManager`) and PVR component. Removed lots of `CPVRClients`boilerplate code. `CPVRClients` no longer has any knowledge about playing clients.
- Splitted `CDVDInputStreamPVRManager` into `CInputStreamPVRBase` (abstract base class), `CInputStreamPVRChannel` and `CInputStreamPVRRecording`. Much cleaner design now, separation of concerns.
- No functional changes. Basically a big refactoring plus optimizations.

BTW: No idea why git marks DVDInputStreamPVRManager.cpp as deleted. In fact I renamed that file to InputStreamPVRBase.cpp. Most of the code of the original file is actually untouched.

### CODE REVIEW

**Comment by ksooo** [comment]
@MilhouseVH could you please include the PR in your builds and ask testers for reporting back on PVR regressions. I don't think there will be any, but just to be sure.

**Review by FernetMenta — APPROVED** [review]
The changes seem sound to me.
For the record: CDVDInputStreamPVR* will be disappear. All streaming functions will be moved to InputStreamAddon (v19)

**Comment by MilhouseVH** [comment]
@ksooo sorry bit behind on emails so this missed tonight's build but it will be in #0612 tomorrow.

**Comment by FernetMenta** [comment]
@ksooo this most likely killed playing recordings via JSON-RPC. The old code got the recordings tag via CPVRRecordings::GetByPath, the new code assumes that the file item must have a recordings tag, which is not the case if triggers via i.e. Kodi iOS remote app.

**Pull request merged**
