### PR TITLE
Keyboard layout: Czech QWERTZ

### PR DESCRIPTION
**Pull request by SkyCrawl**
Hello,

I've added a keyboard layout for Czech language which, I believe, makes the best effort (or is very close to) at allocating keys. There are many ways to do this because:
- Some of the special czech characters share keys with other characters (SK)
- Some of the special czech characters are typed using a combination of keys (CK).

I devised several layouts but eventually, I only decided for one that:
- Tries to position characters just as they would appear on a genuine mainstream czech keyboard (or as close to the positions as possible).
- Tries to position CK characters close to their base letters.
- Has a specially formed layout with the `symbol` modifier because of numbers.

Preview:

| 01 | 02 | 03 | 04 | 05 | 06 | 07 | 08 | 09 | 10 | 11 | 12 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Ť | Ě | Š | Č | Ř | Ž | Ý | Á | Í | É | Ó | ( |
| Q | W | E | R | T | Z | U | I | O | P | Ú | ) |
| A | S | D | F | G | H | J | K | L | Ů | Ď | _ |
| / | Y | X | C | V | B | N | M | Ň | : | . | - |

Notes:
- Successfully tested with `Kodi v15.1 “Isengard”` on Mac OS X.

### CODE REVIEW

**Comment by Montellese** [comment]
I'm not Czech so I don't really have any idea what is better or worse. Could you provide screenshots of the different keyboards so people that are/known Czech can easier imagine how it will look like?

What is the reason for adding the English QWERTZ layout? Could you put that into a separate commit?

**Comment by SkyCrawl** [comment]
> * Could you provide screenshots of the different keyboards?
* Could you put that into a separate commit?

I will :).

> What is the reason for adding the English QWERTZ layout?

See:

> Czech keyboards are effectively a combination of English X and Czech X keyboards, where the latter contains special czech characters. As such, it felt best to mimic this with the layouts as well - making a single layout that doesn't depend on another (English) is, of course, possible but then we would have to face the problem of where to put numbers.

Czech keyboards are somewhat ambiguous (the double layout of an English and Czech keyboard) and because `E-C-Z` (see above) is the most common layout and English QWERTZ was still missing, I added it.

**Comment by SkyCrawl** [comment]
Maybe it's best to pick out a particular layout before I get around to the commits though. Let me propose several solutions then.

The most problematic characters are `Ť - Ď - Ň - Ó` because they don't have fixed positions of their own (they are typed with a combination of keys). Also, note that:
* Most likely, the count of their apperances in Czech language is exactly in this order.
* They are rarely used in Czech language so it's probably best to put them somewhere "in-the-corner".

The best layouts I could come up with (while trying to keep character positions fixed according to the Czech QWERTZ keyboard) are:

**THE TOP-BOTTOM LAYOUT**

| 01 | 02 | 03 | 04 | 05 | 06 | 07 | 08 | 09 | 10 | 11 | 12 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Ť | Ě | Š | Č | Ř | Ž | Ý | Á | Í | É | Ď | Ň |
| Q | W | E | R | T | Z | U | I | O | P | Ú | Ó |
| A | S | D | F | G | H | J | K | L | Ů | &#x25CF; | &#x25CF; |
| / | Y | X | C | V | B | N | M | , | . | - | _ |

* The problematic characters are put into the top row (except for `Ô` which gets to be at the end of the second row).

**THE TOP-SIDE LAYOUT:**

| 01 | 02 | 03 | 04 | 05 | 06 | 07 | 08 | 09 | 10 | 11 | 12 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| _ | Ě | Š | Č | Ř | Ž | Ý | Á | Í | É | - | Ť |
| Q | W | E | R | T | Z | U | I | O | P | Ú | Ó |
| A | S | D | F | G | H | J | K | L | Ů | Ď | &#x25CF; |
| / | Y | X | C | V | B | N | M | Ň | , | . | &#x25CF; |

* The problematic characters are mostly put into the row where their base character is (except for `Ť` which is disregarded and goes into the top row).

**THE BOTTOM-SIDE LAYOUT:**

| 01 | 02 | 03 | 04 | 05 | 06 | 07 | 08 | 09 | 10 | 11 | 12 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Ť | Ě | Š | Č | Ř | Ž | Ý | Á | Í | É | Ó | &#x25CF; |
| Q | W | E | R | T | Z | U | I | O | P | Ú | &#x25CF; |
| A | S | D | F | G | H | J | K | L | Ů | Ď | - |
| / | Y | X | C | V | B | N | M | Ň | , | . | _ |

* Same as top-side but doesn't disregard `Ť` and focuses symbols into the bottom-side corner.

---

If I should compare the layouts a little:
* Top-bottom is a very simple and "clean" layout but disregards the problematic characters maybe too much.
* Compared to top-bottom, top-side is probably more "logical" or "best-effort" and should ensure less time spent typing. But it differs from QWERTZ more and disregards `Ť`.
* Bottom-side can really be thought of as something in between top-bottom and top-side.

My personal favourite is top-side but the best may be bottom-side after all. Who knows though... other people may have other preferences :).

**Comment by MartijnKaijser** [comment]
could you split the commits?

**Comment by SkyCrawl** [comment]
> could you split the commits?

I will, once we agree on the layouts to include in Kodi :). Three is really a bit much so we should probably pick at most 2. If you want me to do it, just say the word.

**Comment by MartijnKaijser** [comment]
well since none of us is Czech we can't decide. Personally i won't have objections just including them

**Comment by SkyCrawl** [comment]
@Montellese @MartijnKaijser 

I've edited my original post and PR title, and retracted the English QWERTZ layout in favour of a single Czech layout. With this, the PR can, hopefully, be merged :).

**Comment by un1versal** [comment]
Sorry for noise I know its late now to adjust this PR.

These layouts are not supposed to be 1:1 and its a lot easier to have characters like @ / . : to make it easier/faster to input web addresses

maybe something like:

|   01 	|02 	|03 	|04 	|05 	|06 	|07 	|08 	|09 	|10 	|11 	|12
--- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
Ť |	Ě |	Š |	Č |	Ř |	Ž |	Ý |	Á |	Í |	É |	Ó |	@
Q |	W |	E |	R |	T |	Z |	U |	I |	O |	P |	Ú |	)
A |	S |	D |	F |	G |	H |	J |	K |	L |	Ů |	Ď |	_
Y |	X |	C |	V |	B |	N |	M |	Ň |	/ |	 : |	.  |	-

up to you.

**Comment by SkyCrawl** [comment]
Well, it depends on the use? Some people may enter playlist names the most. Some web addresses, some emails... We can't optimize the layout for everything :). Mine is (hopefully) optimized for names and file-system paths.

**Pull request merged**
