### PR TITLE
Fix whitelistable resolutions on some platforms

### PR DESCRIPTION
**Pull request by lrusak**
after #13899 RES_DESKTOP won't show up in the whitelist selection on some platforms. This fixes it.

basically we were taking out the preferred resolution from the list of custom resolutions.

### CODE REVIEW

**Comment by FernetMenta** [comment]
> basically we were taking out the preferred resolution from the list of custom resolutions.

if this is the case, there is still someting wrong. the preferred res, that one the UI uses, is stored in guisettings and can be queried with CDisplaySettings::GetInstance().GetCurrentResolution()

**Comment by lrusak** [comment]
good to go?

**Review by FernetMenta — APPROVED** [review]

**Comment by lrusak** [comment]
jenkins build and merge

**Comment by wrxtasy** [comment]
Android ARM nightly #dba439f5 anomalies 23.98 and 60Hz are selectable in Refresh Rate, but 1080p 60Hz has gone missing in Whitelist.
http://paste.kodi.tv/tiqimosewu

Nightly #05a868b3 , 23.98 is missing in both refresh rate & Whitelist resolutions. 1080p 60Hz shows up this time:
http://paste.kodi.tv/tipiwiwafa

All these Fractional refresh rates were working perfectly before this Whitelist business was introduced.
I'm questioning the sanity of what has been now been introduced particularly for Kodi support members downstream fielding questions and clueless users.

Whatever happened to the KISS method - keep it simple stupid ?
This is what I use in combo with @Koying's previous Krypton resolution switching PR to prevent unnecessary SD <<-->> HD switching res. when watching OTA TV:

paste.kodi.tv/oxozekahuy.php

W.

**Comment by FernetMenta** [comment]
this is a dev space. you can complain in the forum. here you are supposed to talk about code. if you don't, don't post here.

**Pull request merged**
