### PR TITLE
Various out-of-tree build fixes

### PR DESCRIPTION
**Pull request by MaxKellermann**

### CODE REVIEW

**Comment by BMc08GT** [comment]
Code review wise, this looks good. Haven't tested out of tree build tho

**Comment by MaxKellermann** [comment]
Out-of-tree build still doesn't work, there are so many other problems left. For now, I gave up, but decided to share what I had until now.

**Comment by MaxKellermann** [comment]
Rebased on current master. Please reconsider merging.
Currently fails at XB_CONFIG_MODULE, which needs additional fixes. I'll pick this up once these basic patches are merged.

**Comment by FernetMenta** [comment]
autotools is dead end because we want to do the switch to cmake.

**Comment by MaxKellermann** [comment]
What does that mean? Will you refuse to merge such fixes until that hypothetical switch to cmake is finished? If so, I'll stop spending time on the build system.

**Comment by stefansaraev** [comment]
well. all this ../../../../../../ ... thing should be in fact abs_top_builddir. no ?

**Comment by FernetMenta** [comment]
> Will you refuse to merge such fixes until that hypothetical switch to cmake is finished?

That is much more than hypothetical. If you want to contribute, submit cmake patches to my repo:
https://github.com/FernetMenta/xbmc

**Comment by MaxKellermann** [comment]
Closing this PR because Paxxi told me I'm not welcome at the Kodi project, see https://github.com/xbmc/xbmc/pull/8868

**Pull request closed without merging**
