### PR TITLE
[VideoInfoScanner] Load filestream details while scanning

### PR DESCRIPTION
**Pull request by alexiri**
## Description

This small change loads the full filestream details while adding new files during scanning.

## Motivation and context

When new episodes are added to the video library, their duration, codec, etc. is not known. This information won't be loaded by Kodi until the episode is played or certain playlist views are opened. With this change, the filestream details are loaded when a new video is being added to the library so all the details are available from the very beginning.

## How has this been tested?

I tried adding several episodes and movies and the stream details show up right after scanning.

## What is the effect on users?

Users will see the full details of their videos from the beginning.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by howie-f** [comment]
> When new episodes are added to the video library, their duration, codec, etc. is not known.

just checked, i have lots of episodes i've never played but can see all tags (even with Leia)

screenshot000

**Comment by alexiri** [comment]
@howie-f, yes, the metadata may also be loaded in certain cases after the scanning, such as when you open a smart playlist that the episode is a part of. I think it also gets loaded if you open the series view, but I didn't check in detail. The fact remains that it doesn't get loaded while scanning, which you can see easily by looking at the newly-added episodes through the web interface or the API.

**Comment by howie-f** [comment]
> that it doesn't get loaded while scanning

you‘re right 👍

**Review by garbear — APPROVED** [review]
A sensible improvement, thanks

**Comment by nbarrientos** [comment]
Any chance this could be considered a bug fix and merged into v19 too?

**Review by howie-f — APPROVED** [review]
> Any chance this could be considered a bug fix and merged into v19 too?

i don't think this would be a problem. 
just wondering if it makes sense to move this piece of code a bit downwards.. right before the call to `m_database.Close();`. what do you think @alexiri ?

**Comment by enen92** [comment]
I wonder if this won't slow down the scrapping process / addition to the library too much specially with big libraries on remote locations (this requires ffmpeg to probe the file isn't it?). I'd be great to have a few measurements with nfs/smb etc.
I think it's a missing feature. Although, I am not sure if it should be enabled by default (maybe it makes sense to be configurable?).

**Comment by howie-f** [comment]
thanks for testing @alexiri , was just a thought...

good catch @enen92 
i see we already have a setting for this, but it defaults to **ON*
screenshot00000

also this setting isn't checked when getting the file stream details in VideoThumbLoader, e.g. when you open the episodes view. mhm, what to do? i could do a scraping speed comparison for my local library but no nfs/smb

**Comment by alexiri** [comment]
You're right, @enen92, some slowdown is to be expected. I went ahead and did some benchmarks[*] in order to quantify it. I tested it by loading 103 movies from an NFS share over a LAN and it took 64 seconds with this change and 55.99 seconds without it, so you could say this change adds 77ms per file to the scrape time. I think that's an acceptable performance hit. In any case, Kodi will read the stream metadata sooner or later, so we're just talking about _when_ we take the hit, not _if_.

[*] Not super scientific, mind you. Sample size of one, only movies, etc.

**Comment by notspiff** [comment]
For slower devices I think you should consider making a IJob for this and
let it run in a separate thread. The perceived impact will be lessened.

ons. 6. okt. 2021, 20:47 skrev Alex Iribarren ***@***.***>:

**Comment by alexiri** [comment]
Thanks for merging, @howie-f! Can I get this backported to v19? Should I do another PR for that to the `Matrix` branch?

**Comment by thexai** [comment]
I fully agree with @arnova. This is a **great improvement** especially if is taken into consideration modified files by date and updated stream details, etc. Also probably needs two new settings to control this new (optional) behavior:

e.g.:

- Extract stream details of new added items during library scanning.
- Update stream details of existent items if media file has changed.

However all this is new feature (not bugfix) and should not be backported to Matrix.

**Comment by FLskydiver** [comment]
> Haven't seen any comments from users, so I just wanted to give feedback on this. I backported the change myself and compiled it with 19.2. It compiles successfully and appears to work as expected without issues. I'll update if I notice any problems.
> 
How did you do that? I'm on 19.4 and can't locate the "VideoInfoScanner.cpp" to insert the changes to?

**Comment by arnova** [comment]
> > Haven't seen any comments from users, so I just wanted to give feedback on this. I backported the change myself and compiled it with 19.2. It compiles successfully and appears to work as expected without issues. I'll update if I notice any problems.
> 
> How did you do that? I'm on 19.4 and can't locate the "VideoInfoScanner.cpp" to insert the changes to?

You need to obtain the sourcecode, add the change, and compile a new version yourself.

**Comment by FLskydiver** [comment]
> > > Haven't seen any comments from users, so I just wanted to give feedback on this. I backported the change myself and compiled it with 19.2. It compiles successfully and appears to work as expected without issues. I'll update if I notice any problems.
> > 
> > 
> > How did you do that? I'm on 19.4 and can't locate the "VideoInfoScanner.cpp" to insert the changes to?
> 
> You need to obtain the sourcecode, add the change, and compile a new version yourself.

I started to try to figure out how to do that (using the instructions here) when I was told [there was an option B](https://forum.kodi.tv/showthread.php?tid=364693&pid=3110214#pid3110214) by @Karellen at Kodi Community Forum: 
Turns out this change is incorporated in Nexus (20.0) Alpha 2.  

I've further combined Alpha 2 with the [latest version](https://github.com/xbmc/metadata.tvshows.themoviedb.org.python) of the "TMDb TV Shows" scraper, which @pkscout was super incredible to update for me when I [encountered an issue](https://forum.kodi.tv/showthread.php?tid=357232&pid=3109074#pid3109074) with it, and now have the pair humming along re-scraping my entire TV library, working together exactly how I believe Kodi scraping should work.  

Rescraping is taking forever, but once it's done, I should be set for quite some time —  my .nfos will already have the file details included on scraping (so I won't need to manually open up each show to provoke Kodi to acquire that info), and the season cast will now be listed before the episode's guests stars and credited extras, while series regulars who are no longer on the show will be plugged in last (apparently this is forced by Kodi and can't be fixed by the updating the scraper — though pkscout's new implementation minimizes this inconvenience and serves my needs quite well).  I'm a happy boy now.  

Thank you all!

**Comment by FLskydiver** [comment]
> I wonder if this won't slow down the scrapping process / addition to the library too much specially with big libraries

I'm currently rescraping my entire television library (11.2 TB, 372 series, 12,000+ episodes). It's kind of a leave it to process overnight kind of deal; but I don't believe it's taking any longer than it did last night when I did this on 19.4 without the benefit of simultaneously gather <fileinfo> stream details.  Scanning individual shows with maybe a few dozen episodes (instead of my entire library) while testing if I implemented this change, (and the one mentioned above) correctly took a negligible amount of time.

Granted, I'm scraping and analyzing files on my local NAS, connected to my laptop via my router over ethernet.  I imagine any delays compared to what I'm experiencing will be most entirely a result of connection speeds.  

Also might be worth noting I've got 40TB worth of drives in a Synology box utilizing SHR for a total of 28.7 TB of storage ... and I only have 64.5 GB of free space remaining — or 2/10th of 1% of total formatted capacity.  (Yikes, right?) So my disc access speeds are probably a bit lower than they otherwise would be!

**Comment by KarellenX** [comment]
I think this PR has caused a regression.

In v18.9 and earlier with the setting _Extract video information from files_ Enabled...
1. if nfo files contained `<streamdetails>` data, this data was read into the database. 
2. If no nfo files, or nfo file does not contain the `<streamdetails>` then the streamdetails came from the video file.

The issue now in v19, v20 and v21...
1. If nfo files contain `<streamdetails>`  and the setting _Extract video information from files_ is enabled, then the nfo file details are ignored and forces every video file to be read unnecessarily
2. To force the nfo details to be used the setting _Extract video information from files_ needs to be disabled. But doing this prevents any video without a nfo file from having their streamdetails read. Essentially, there is no fallback.

So a user trying to get this to work will need to be constantly enabling and disabling the setting _Extract video information from files_.

I have seen mention of this on the forum with users complaining about the HDR tag not being read from nfo files (whether the video file is or is not HDR is another argument).

Like all other nfo processes, the streamdetails in the nfo file needs to have priority.

**Pull request merged**
