### PR TITLE
Mark some classes non-copyable + add default constructors

### PR DESCRIPTION
**Pull request by notspiff**
Correctness + cppcheck shut-up.

### CODE REVIEW

**Comment by garbear** [comment]
There's a lot of places where non-copyableness is achieved by declaring protected constructors without a definition, e.g. `protected: Foo();` instead of `protected: Foo() = delete;`. Is there a way to detect and fix these? is the captain up to the challenge???

**Comment by notspiff** [comment]
i've done the shit found by
```bash
#!/bin/bash

for file in `find . -name "*h"`
do
  lines1=`grep -z "private:.*operator=" $file | grep -v delete | wc -l`
  lines2=`grep -z "protected:.*operator=" $file | wc -l`

  if test $lines1 -gt 0
  then
    echo $file >> files-priv
  fi
  if test $lines2 -gt 0
  then
    echo $file >> files-prot
  fi
done

cat files-priv | sort > files-priv-s
cat files-prot| sort > files-prot-s

comm files-priv-s files-prot-s -3
rm -f files-priv files-priv-s
rm -f files-prot files-prot-s
```
that's the extent i will entertain your challenge. ie i will not hunt down stuff using private through no qualifier.

i had to resort to old-style default constructor for the Player class due to code generation (should fix build on jenkins).

**Comment by notspiff** [comment]
i did spot some funkyness, disabling move constructors, prototyping and implementing through = default in the cpp file and even a place where shit was made private, then given a = default implementation in the cpp file. i chose not to touch these.

**Review by garbear — APPROVED** [review]

**Comment by notspiff** [comment]
stpuid code generator :/ not worth the hassle, we can simply live with one more suppression in the cppcheck script.

**Comment by notspiff** [comment]
kick the servant please

**Comment by garbear** [comment]
jenkins build this please

**Comment by notspiff** [comment]
all platforms has passed at some point, but please kick the bastard once more.

**Comment by garbear** [comment]
jenkins build this please you loveable hunk of 1s and 0s

**Comment by MartijnKaijser** [comment]
http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-All/848/

**Comment by Montellese** [comment]
IMO a constructor marked with `= delete` should always be `public` because you basically want to tell everyone that this object can't be constructed / copied i.e. it's part of the classes interface. Obviously before C++11 this could only be achieved by making the constructor(s) `protected` or `private`.

But this PR is fine with me either way, thanks for doing the monkey work.

**Comment by MartijnKaijser** [comment]
Manual build succeeded

**Comment by MartijnKaijser** [comment]
No objections and we can merge this?

**Comment by Razzeee** [comment]
Building again for convinience

jenkins build this please

**Comment by Razzeee** [comment]
Build fine and so far nobody objected to martijn, so I'm merging this now.

**Pull request merged**
