### PR TITLE
[addons] Add addon helper library to bring OpenGL shader

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description
This adds an interface to use OpenGL or OpenGLES shader and matrix handling via Kodi's Integrated System on the addon.

It is needed now on all addon's who make OpenGL access, without a library
every addon must include the same byself.

This change contains several new interfaces to handle OpenGL with Kodi. This are:
1. Addon class "CPresentShader"
    - It allow addon to use Kodi's basic predefined shaders from CRenderSystemGL or CRenderSystemGLES
    - This is then the most easiest way for a addon to get shader. Tested on asteroids screensaver and works good
2. Addon class "CShader" and "CShaderProgram"
    - This allow the use of more complex shaders where load becomes handled from Kodi. This makes it on addon side more easy to handle differences between different OS's and GL Versions.
    - Before was for more complex OpenGL shading a extra code on addons needed to handle this load.
    - This support the load of Kodi's own shaders or own from addon where it give his folder to Kodi
    - Test of them works good.
3. Addon class "CMatrix"
    - It has now a interface for the Matrix Processing on OpenGL
    - This allow the for performance optimized code to use on addon
4. Addon class "CMatrixStack"
    - This is a special stack handler, over static functions there can the addon use the Matrix Stack's from Kodi for him.
    - Further can it create the class by self new who make a own stack on addon.
    - This code is currently not tested.

**Just as an example of an idea, not sure if it's acceptable. Actually, I want to have all the Kodi related integrated into the dev-kit.**

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by FernetMenta** [comment]
I won't add the shader code to the dev-kit. why don't you add the shader functions to the interface of the CGUIVisualisationControl and GUIRenderingControl. This way kodi can also expose current projection matrix, etc.

**Comment by AlwinEsch** [comment]
Good idea, thought on begin to let the code from Kodi away, but to have in the interface is better and prevent this external build.

**Comment by FernetMenta** [comment]
> to let the code from Kodi away

there is no need for the additional shader code. core has shaders in RenderSystem: https://github.com/xbmc/xbmc/blob/master/xbmc/rendering/gl/RenderSystemGL.h#L72
Just make this available to addons:

**Comment by AlwinEsch** [comment]
Have updated the code, still not finished (but sleeping time :-1: ) )

With the given link I do not quite understand, it refers to CRenderSystemGL, but do not think that from there what addons would be.

**Comment by Rechi** [comment]
wrong revision was build
jenkins build this please

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by AlwinEsch** [comment]
Seen "[glm](https://github.com/g-truc/glm)" makes more sence to use on addons and is easier. Also becomes the CShader added in other request.

Maybe if Kodi's Matrix is needed in future, addon interface becomes a Function added to get the 16 Float values of Projection or Model Matrix

**Pull request closed without merging**
