### PR TITLE
Prevent deadlock when calling SetWindowPos from another thread

### PR DESCRIPTION
**Pull request by popy2k14**
flag SWP_ASYNCWINDOWPOS, see https://msdn.microsoft.com/en-us/library/windows/desktop/ms633545%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

## Description
When SetWindowPos is called from another thread with the main gui HWND, kodi freezes!
This was the case on ExternalPlayer.cpp, see ticket: https://trac.kodi.tv/ticket/17988
My PR adds the SWP_ASYNCWINDOWPOS flag on all SetWindowPos.
So the risk of ever running into the same problem, when calling ->Show() is low.

## Motivation and Context
Kodi freezes when external player is active and STOP is pressed on keyboard or received, json, remote...

## How Has This Been Tested?
On my dev machine, the issue is reproduce able like described in the ticket.
After the PR, issue is gone for me.

## Types of change

- [X ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by afedchin — CHANGES_REQUESTED** [review]
please drop changes that I commented, because Kodi expects old behavior in these places. I think it will not cause an issue, but I don't want to risk at this stage of development v18.

**Comment by FernetMenta** [comment]
Right, SetWindowPos is Windows API function and must only be called by windowing component.

> So in my opinion acceptable solution is sending a message/event to the main thread to change window

I am not sure if this is Windows only or something generic.

**Comment by popy2k14** [comment]
You are right but if anybody uses SetWindowPos from another thread again!?
This could happen also when this issue is solved with an event to the main thread.

**Comment by FernetMenta** [comment]
> You are right but if anybody uses SetWindowPos from another thread again!?

won't happen if g_hWnd gets eliminated.

**Comment by afedchin** [comment]
> You are right but if anybody uses SetWindowPos from another thread again!?

nobody except windowing shouldn't use SetWindowPos. Using SetWindowPos from ExternalPlayer is bad. Fernet is right `g_hWnd` must be eliminated.

> This could happen also when this issue is solved with an event to the main thread.

application events are processed from main thread only.

**Comment by FernetMenta** [comment]
I never do such quick hacks but I leave the decision to @afedchin

**Comment by fritsch** [comment]
If it is not fixed properly now, nobody will care afterwards. We have
enough tickets open already.

popy2k14 <notifications@github.com> schrieb am Sa., 18. Aug. 2018, 13:18:

**Comment by popy2k14** [comment]
Yeah. but eliminating the variable will not be that easy.
I'ts used in several other components where windows api is needing an hwnd.
Here are the references where they are used:

\xbmc\xbmc\cores\AudioEngine\Sinks\AESinkDirectSound.cpp(163):  HWND tmp_hWnd = g_hWnd == nullptr ? GetDesktopWindow() : g_hWnd;
\xbmc\xbmc\cores\ExternalPlayer\ExternalPlayer.cpp(349):    SetForegroundWindow(g_hWnd);
\xbmc\xbmc\network\mdns\ZeroconfBrowserMDNS.cpp(27):extern HWND g_hWnd;
\xbmc\xbmc\network\mdns\ZeroconfMDNS.cpp(204):    WSAAsyncSelect( (SOCKET) DNSServiceRefSockFD( m_service ), g_hWnd, BONJOUR_EVENT, 0 );
\xbmc\xbmc\platform\win32\WIN32Util.cpp(254):  ShowWindow(g_hWnd,SW_MINIMIZE);
\xbmc\xbmc\platform\win32\WindowHelper.cpp(49):  SetForegroundWindow(g_hWnd);
\xbmc\xbmc\powermanagement\PowerManager.cpp(202):    SetForegroundWindow(g_hWnd);
\xbmc\xbmc\windowing\windows\WinEventsWin32.cpp(263):    g_hWnd = nullptr;

As an example in the ZeroconfBrowserMDNS.cpp the WSAAsyncSelect needs an hwnd where the event gets passed after select is ok, so there the correct hwnd is needed for this to work.
Did'nt look a the other files, but i assume the same.
So elliminating the global hwnd is not the right way.

**Comment by afedchin** [comment]
> Please, whats your decision? Would be nice if you merge this because some of use using ExternalPlayer currently :-)

If current fix resolves the issue, I can aprove it.

> So elliminating the global hwnd is not the right way.

It's right way, you just doesn't see how to resolve it.

**Comment by popy2k14** [comment]
The current fix resolves the main issue, please aprove it.
Should ill create a ticket regarding the global hwnd?

**Review by afedchin — APPROVED** [review]

**Comment by afedchin** [comment]
> Should ill create a ticket regarding the global hwnd?

no need. I've added this to my todo list

**Comment by afedchin** [comment]
thanks. merged

**Pull request merged**
