### PR TITLE
Bump python to 2.7.10

### PR DESCRIPTION
**Pull request by wsnipex**
this bumps unified depends platforms python to the latest 2,7 release 2.7.10

I'd appreciate testing.

fixes (#15883)

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
Let me know and I'll do some droid runtime

**Comment by wsnipex** [comment]
@MartijnKaijser: yes please. 
@Memphiz I need help with IOS. can't for the life of me get PIL to build

**Comment by Paxxi** [comment]
We've been running 2.7 on windows for ages do hopefully it shouldn't be any issues. You want me to bump win32 as well so we're 2.7.10 across the board?

**Comment by wsnipex** [comment]
@Paxxi python is by far the worst nightmare depend we have to cross-compile, so proper testing is warranted. Bumping windows as well would probably make sense, if you have time for it.

**Comment by zag2me** [comment]
Sorry for the question, but does this mean Python will be the same version on all platforms? 

I'm writing a tutorial on python scripting and a couple of users commented that you couldn't rely on some functions working on some platforms.

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
@zag2me part from platform specific differences, it should be the same, yes. But this is only valid for unified depends platforms. Standard linux uses system python and win32 has its own build as well.

jenkins build this please

**Comment by wsnipex** [comment]
got IOS to build. OSX32 build error unrelated
Can someone please runtime test?

**Comment by wsnipex** [comment]
test builds:
droid arm: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20151015-f71dcbb--armeabi-v7a.apk
droid x86: http://mirrors.kodi.tv/test-builds/android/x86/kodi-20151015-f71dcbb--x86.apk
ios: http://mirrors.kodi.tv/test-builds/darwin/ios/kodi-20151015-f71dcbb--ios.deb
osx64: http://mirrors.kodi.tv/test-builds/osx/x86_64/kodi-20151015-f71dcbb--x86_64.dmg

**Comment by MartijnKaijser** [comment]
doing some initial testing on Android ARM doesn't show any problems

**Comment by MartijnKaijser** [comment]
@wsnipex not sure if related?
http://xbmclogs.com/pjxwb5khf#line-5958

**Comment by Rondom** [comment]
@wsnipex Tested this for two hours on Android-ARM. So far no problems for me.

@MartijnKaijser The SSL-Issue you are pointing to might indeed be related. Python's SSL-stack got an update some time in the 2.7-cycle which amongst others enables by-default certificate verification.
This is something addon authors have to consider. On Desktop Linux Kodi is running with the system python, i.e. any problems caused by stricter checks occur there even with old versions of Kodi without this pull request.
Disclaimer: I have not had a look at the specific request and the specific addon. This is just what I can see from the error message. So debugging this specific HTTPS-Request is something left to do to confirm what I said above.

@wsnipex Therefore it might be worthwhile to put some small note regarding this into the documentation for addon authors.

**Comment by MartijnKaijser** [comment]
@Rondom on win32 we already run 2.7.9 which doesn't have this problem.

**Comment by Rondom** [comment]
@MartijnKaijser You are right, this is some other problem.
@wsnipex As far as I can see any HTTPS-Request using urllib such as for example `urllib.urlopen('https://kodi.tv')` does not work

**Comment by Paxxi** [comment]
Could this be the reason for the ssl issue?
https://github.com/wsnipex/xbmc/blob/bump-python/tools/depends/target/python27/modules.setup#L214 Maybe somethings changed in the build system so we need to do what the comment says.

**Comment by wsnipex** [comment]
https should be fixed: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20151020-12399e7-bump-python-armeabi-v7a.apk

**Comment by Rondom** [comment]
Not sure if this is the right place to bring this up: Do we really want to disable SSL-cert validation by default?
If an addon breaks because it connects to "broken" HTTPS-sites, addon authors can make an informed decision and manually switch off validation on a case-by-base basis.

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by tamland** [comment]
Wondering about that as well. Just patching out the default doesn't seem like a fix. If SSL is broken then everything not relying on the default behavior would still be broken.

**Comment by wsnipex** [comment]
@tamland any idea how we'd best pass a cacert to python on droid?

**Comment by wsnipex** [comment]
I've added a ca-cert and pass it to python. Seems to work from a quick test. Please verify.

**Comment by tamland** [comment]
@wsnipex Can you make a test build?

**Comment by fritsch** [comment]
Some discussion about this topic was also on OE's github: https://github.com/OpenELEC/OpenELEC.tv/pull/4279 which resulted in: https://github.com/OpenELEC/OpenELEC.tv/pull/4284

sqlite was problematic when I remember correctly.

**Comment by wsnipex** [comment]
I've just triggered a test build. should show up in http://mirrors.xbmc.org/test-builds/ with PR8207 in the name in ~1,5hrs

**Comment by MartijnKaijser** [comment]
Android is confirmed working (including PIL to PILLOW module change)
@Memphiz @mkortstiege maybe you give a try on osx/ios whenever you have time

**Comment by Rondom** [comment]
@wsnipex The last build I can find at the link is from 20th October.

**Comment by wsnipex** [comment]
droid: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20151026-4806890-pillow-armeabi-v7a.apk
osx: http://mirrors.kodi.tv/test-builds/osx/x86_64/kodi-20151026-4806890-pillow-x86_64.dmg
ios: http://mirrors.kodi.tv/test-builds/darwin/ios/kodi-20151026-4806890-pillow-ios.deb

**Comment by mkortstiege** [comment]
Sure, can run some test later today.

**Comment by jpoppe** [comment]
I have been testing kodi-20151026-4806890-pillow-armeabi-v7a.apk on Android 5.1 with my plugin (not public yet), which uses Python 2.7 syntax. Libraries like: xbmcswift2, sqlalchemy (with sqlite as backend). Could not find any issues. Awesome work, thanks!

**Comment by Memphiz** [comment]
tested on ios - works fine - great work :)

**Comment by wsnipex** [comment]
thanks for testing everyone! Did someone verfiy OSX as well?
@Memphiz does IOS need a special handling for SSL certs(like droid) as well or is there a system wide cert bundle that openssl with magically find?

**Comment by wsnipex** [comment]
@Memphiz pillow and the old pil bombs on OSX.
@mkortstiege and me have been mucking around with it, but no dice. Could you please take a look?

**Comment by Memphiz** [comment]
Already wondered why this transition should be so smooth ;) ... i try to do so on the weekend but not sure if i can get some time for it :/

**Comment by Memphiz** [comment]
How can i even Test pillow - pretty sure it should bomb out too on ios - hat's to believe something works on ios and doesn't on osx - how to Test that ssl cacert stuff you asked for?

**Comment by mkortstiege** [comment]
> How can i even Test pillow - pretty sure it should bomb out too on ios - hat's to believe something works on ios and doesn't on osx - how to Test that ssl cacert stuff you asked for?

Easiest is to test with openweathermap. This is using PIL for the forecast images and will instantly crash on osx right now. Let's see what ios does :)

**Comment by MartijnKaijser** [comment]
Testing SSL is simply trying to use the YouTube Addon and play something

**Comment by Memphiz** [comment]
there are script error toast dialogs popping up (can't check the log atm) - but no crash and burn

https://www.dropbox.com/s/whw7lyawz1cv0fe/Foto%2030.10.15%2019%2033%2055.png?dl=0

youtube also works - so really an osx only problem this time as it seems?

**Comment by Memphiz** [comment]
@wsnipex whats the difference from your bump-python branch and your pillow branch?

**Comment by wsnipex** [comment]
only that last 2 commits from here that add setuptools, needed to build pillow.
That the pillow branch without setuptools worked before is "by accident", cause it seems to find setuptools from system or python26 leftovers in depends.

**Comment by Memphiz** [comment]
Mhhh just wondering - why do we need setuptools for target? Till now we have it only built for native:

https://github.com/xbmc/xbmc/tree/master/tools/depends/native/distribute-native

or https://github.com/xbmc/xbmc/tree/master/tools/depends/native/distutilscross-native

One of those has the setuptools for native ...

I think i found the reason why pillow bombs out on osx ... it links the *.so against the system python framework instead of our static python27.a from depends ... still trying to figure out how to correct this ...

**Comment by Memphiz** [comment]
@wsnipex i found it ... one thing that is unclear to me ... the old pil extracted the egg during installation - see:

https://github.com/xbmc/xbmc/blob/master/tools/depends/target/pythonmodule-pil/Makefile#L47

Any reason you dropped that? I have no clue of the internas but i think it was done because of performance penalties when the egg file would be extracted on the fly before? @davilla any insight on extracting the egg or not extracting the egg? ^^

**Comment by Memphiz** [comment]
@wsnipex can't do a PR to your repo:

pick https://github.com/Memphiz/xbmc/commit/d7f677b6f47c1a3e5835f1abce1e62342449cf14

**Comment by wsnipex** [comment]
thanks! I was pretty sure something with cflags was wrong.
re setuptools: its probably necessary cause I set PYTHONPATH, cause pillow will complain without it.
We can probably try to include the native-python-distutils path instead of having cross-setuptools.
otoh, it might can in handy for something in the future.

jenkins build this please

**Comment by wsnipex** [comment]
I initially dropped extracting the egg in the old PIL, cause setuptools wasn't found, so I changed it to work without. I simply didn't change that back to the old behavior after switching to pillow.
But I really can't imagine a noticable performance penalty because of it.

**Comment by Memphiz** [comment]
fine with me then :)

**Comment by Memphiz** [comment]
@wsnipex in current github pull request builder plugin for jenkins i have this options:

Mark unstable builds as:
- error
- failed
- success

It was set to "failed" ... i now changed it to "error" but i doubt this will bring anything better to us ;) - or did you mean to change it to "success"?

**Comment by wsnipex** [comment]
I'd set it to success for normal PR builds and error for addon builds

**Comment by MartijnKaijser** [comment]
But what when normal PR breaks addons? You wouldn't know if it's marked success

**Comment by Memphiz** [comment]
@wsnipex i can only set this globally sadly ... at least with current version of the plugin

**Comment by wsnipex** [comment]
guess you have to fix the ghpr-builder plugin ;)

**Comment by Memphiz** [comment]
i don't think that fixing the plugin is all about it - see @MartijnKaijser 's argument ...

**Comment by wsnipex** [comment]
it is. ideally the result code should reflect that kodi built fine, but (some) addons failed. Just like the yellow in jenkins.

**Comment by Memphiz** [comment]
It might be a limitation of github to do so ... well no time to look into this yet ...

**Comment by andrewleech** [comment]
I see today Kodi 16's hit beta, it there any chance of getting this into 16.0 release? If so what will it take to make this happen?

A newer python would solve a _lot_ of SSL issues I have with my add-on. 
Cheers!

**Comment by MartijnKaijser** [comment]
No

**Comment by Razzeee** [comment]
This might fix this trac ticket? http://trac.kodi.tv/ticket/15883
Can you put the ticket number into the title if I'm correct?

**Comment by wsnipex** [comment]
@Paxxi do you have time to bump windows as well?

**Comment by MartijnKaijser** [comment]
i could take a try this weekend. Shouldn't be too difficult. PIL still has to be changed to Pillow on win32?

**Comment by Paxxi** [comment]
Correct @martijn we build pillow as pil is mostly dead? It's not hard to build python but a bit annoying with the depends it has, afaik Berkley dB took me some time last try. 
@wsnipex unfortunately I won't have any time this week or the next but lack of win32 build isn't an issue, we're already on 2.7.9 afaik,  it's mostly because it's nice to keep them in sync.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
@Paxxi python bump for windows is done (it is just downloading the .msi and repackaging) https://github.com/xbmc/xbmc/pull/8491. The pillow change still needs to be done.

**Comment by FernetMenta** [comment]
@wsnipex @Memphiz I get this error on OSX. related?

  URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
                                           -->End of Python script error report<--

**Comment by popcornmix** [comment]
@FernetMenta to get SSL working with python on Pi I needed to:
``cp tools/depends/target/openssl/cacert.pem /opt/xbmc-dbg2/arm-linux-gnueabihf/cert.pem``
Something missing in install scripts?

**Comment by wsnipex** [comment]
I've simply assumed that every platform besides android already has a trust cert provided by the OS.
If not, you'll have to copy tools/depends/target/openssl/cacert.pem to the proper location for openssl to find it.

**Comment by FernetMenta** [comment]
Where is this location on systems that don't have OpenSSL?

**Comment by popcornmix** [comment]
I ran strace on the python in my kodi install directory and tried to open "https://amazon.co.uk" with urllib. The grepped the strace output for cert.pem to find out where it expected it. Kodi seemed happy with the same path as python called directly.

**Comment by wsnipex** [comment]
after reading https://hynek.me/articles/apple-openssl-verification-surprises/ I think we might need the same hack for OSX as for android.

**Comment by wsnipex** [comment]
openssl version -d  should print the default path. Take care to use our depends openssl binary

**Comment by FernetMenta** [comment]
depends does not build a openssl binary, just a lib

**Comment by wsnipex** [comment]
https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/python/XBPython.cpp#L599-L601 should work for OSX as well

**Comment by popcornmix** [comment]
@wsnipex I'm running on Pi using unified build, so python, openssl, curl etc are built from kodi tree which installs no cert.pem and doesn't look for it on system paths (it looks in kodi install tree but fails to find it).

Would it make sense to install the certificate in kodi's install tree (and set SSL_CERT_FILE if necessary) by default when building with unified build system?

**Comment by FernetMenta** [comment]
works on OSX after having copied the cert to system/cert

**Comment by wsnipex** [comment]
@popcornmix yeah, I guess we should do that, but also take care to not override it on platforms/installations where certs are available.

btw, another method to find default paths is:
strings /usr/lib/x86_64-linux-gnu/libcrypto.a | grep -E "/cert|SSL_CERT"
/usr/lib/ssl/certs
/usr/lib/ssl/cert.pem
SSL_CERT_DIR
SSL_CERT_FILE

**Pull request merged**
