### PR TITLE
Bump to SQLite 3090200 (aka 3.9.2)

### PR DESCRIPTION
**Pull request by razzeee**
Pretty much untested from me.
Someone needs to upload it to our severs I guess.

And also for K****\* I would think.

### CODE REVIEW

**Comment by Paxxi** [comment]
Have you built the package for someone to upload? Some or most of our packages include a readme for building it but it can be a bit of work to get it right 😊
What's the reason for the bump? Staying current or is there a feature or fix we want? Both answers are correct, I just like to know the reason

**Comment by Razzeee** [comment]
Haven't build it. 

Staying current some performance optimization and the option for full text indices. Might come in handy for an idea I have.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by Razzeee** [comment]
Rebased the windows build from noon failed on me for two times when trying to open the tv show library, but is now running stable.
A little weird, but might be down to my dev pc.

**Comment by Razzeee** [comment]
Wasn't using the default skin, seems to be fine with confluence

**Pull request merged**
