### PR TITLE
AESinkAudioTrack: Use min_buffer periods

### PR DESCRIPTION
**Pull request by fritsch**
This is a backport of #20127

Was tested by some 100 people already. I would like to have it in Matrix, so that nightlies after the 19.3 release have "all in" if possible. Furthermore I don't have to maintain two different version between 20 and 19.

All the changes are fixes.

### CODE REVIEW

**Comment by thexai** [comment]
According to what was reported in the forum thread (https://forum.kodi.tv/showthread.php?tid=365127), this patch solves all the micro stuttering problems except when the audio is TrueHD but it is due to the modifications introduced almost at the same time by https://github.com/xbmc/xbmc/pull/20339:

So I think the best is to merge as soon as possible since another user has also found the solution for TrueHD. Then another PR will be applied after this one to finish solving all the issues on Android.

**Review by thexai — APPROVED** [review]

**Comment by thexai** [comment]
Milestone 19.3 is not closed yet so is prudent wait to merge this.

**Comment by fritsch** [comment]
If 19.3 is not yet closed RM should decide. Last minute fixes ... most of the time break something else on top, just to keep it in mind.

**Comment by thexai** [comment]
I agree. In any case this PR is for 19.4

**Comment by thexai** [comment]
Merged as it seems we just forgot to close Milestone 19.3

**Pull request merged**
