### PR TITLE
X11 fixes

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

### CODE REVIEW

**Comment by fritsch** [comment]
Thanks much. Sadly intel is not yet that far:
```
1 GLX Visuals
    visual  x   bf lv rg d st  colorbuffer  sr ax dp st accumbuffer  ms  cav
  id dep cl sp  sz l  ci b ro  r  g  b  a F gb bf th cl  r  g  b  a ns b eat
----------------------------------------------------------------------------
0x0cd 32 tc  0  32  0 r  y .   8  8  8  8 .  .  0 24  8  0  0  0  0  0 0 None
```
Only 24 bit visuals even when forcing X11 to 30 bit depth

@lrusak did you try > 8 bit visuals on DRM yet - does it work?

**Comment by fritsch** [comment]
But work is upcoming: https://lists.freedesktop.org/archives/mesa-dev/2017-September/168492.html

**Comment by lrusak** [comment]
@fritsch I haven't tried yet. I don't know if I have a TV/monitor that supports it but I'll check

**Comment by fritsch** [comment]
The display driver will "dither it down / up" - the same way it does it already right now. Would just be interesting to see what visuals are supported that way.

**Pull request merged**
