### PR TITLE
VideoPlayer: write state of clocksync to ProcessInfo, make FinishPipeline dependent on this

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

fix for http://trac.kodi.tv/ticket/16818

### CODE REVIEW

**Comment by Jalle19** [comment]
Why a lock instead of atomics since it's just one boolean?

**Comment by FernetMenta** [comment]
> Why a lock instead of atomics since it's just one boolean?

the boolean is supposed to get some company.

**Comment by fritsch** [comment]
Once upon a time there was a boolean feeling so alone...

Am 03.08.2016 7:15 nachm. schrieb "Rainer Hochecker" <
notifications@github.com>:

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
Android build errors unrelated

**Pull request merged**
