### PR TITLE
[pvr] fixed crash when multiple add-on instances get registered

### PR DESCRIPTION
**Pull request by opdenkamp**
...  for the same add-on.

@stefansaraev can you test if this fixes your crash

### CODE REVIEW

**Comment by opdenkamp** [comment]
jenkins build this please

**Comment by stefansaraev** [comment]
unfortunately nope. http://sprunge.us/FYKY

now I dont see RegisterClient logged multiple times but still crash, fyi next boot after the crash I dont see RegisterClient in the log at all. http://sprunge.us/KEJJ no idea if thats intended behaviour

hope that helps.

**Comment by opdenkamp** [comment]
ok will check

**Comment by stefansaraev** [comment]
@opdenkamp thats what I meant today by "pvrmanager should NEVER touch addondb": http://sprunge.us/bLDU quick and dirty

dealing with Addon*.db should really be addonmanager job. not pvrmanager job.

this is probably wrong and you wont like it. but
- no more crashes after starting kodi with empty (removed) Addon*.db.
- when a client is already installed (but not known (yet) in addobdb) its not started at all.. user is free to restart if we (manualy) clears addondb.
- on api bump, no headache with forced-disabled addons that user has to re-enable.. those are all enabled but not loaded/workig. enabled addon doesnt mean "working/ready-to-use addon". hint service/program/etc addons
- no more dups in addondb

//cc @xhaggi you wanted pvr client addons having same behaviur as other addon types.

**Comment by opdenkamp** [comment]
lol... guess what the original pr was doing: moving the add-on logic from pvr to addonmgr. It's disabled add-ons like this for years without you noticing it. Yes there are things that can be improved or fixed and this was just a start.

-------- Oorspronkelijk bericht --------
Van: Stefan Saraev <notifications@github.com> 
Datum:18-03-2015  22:35  (GMT+01:00) 
Aan: xbmc/xbmc <xbmc@noreply.github.com> 
Cc: Lars Op den Kamp <opdenkamp@gmail.com> 
Onderwerp: Re: [xbmc] [pvr] fixed crash when multiple add-on instances get
  registered (#6732) 

@opdenkamp thats what I meant today by "pvrmanager should NEVER touch addondb": http://sprunge.us/bLDU quick and dirty

dealing with Addon*.db should really be addonmanager job. not pvrmanager job.

this is probably wrong and you wont like it. but

no more crashes after starting kodi with empty (removed) Addon*.db.
when a client is already installed (but not known (yet) in addobdb) its not started at all.. user is free to restart if we (manualy) clears addondb.
on api bump, no headache with forced-disabled addons that user has to re-enable.. those are all enabled but not loaded/workig. enabled addon doesnt mean "working/ready-to-use addon". hint service/program/etc addons
no more dups in addondb
//cc @xhaggi you wanted pvr client addons having same behaviur as other addon types.

**Comment by stefansaraev** [comment]
> guess what the original pr was doing...

yep I know that. very well.

> It's disabled add-ons like this for years without you noticing it

I did. long time ago. and I remember the pain started by t-nelson while he tried to fix some "addons cant be disabled" bug. that broke "reset pvr database". still broken in "stables". every time one touches that code, something gets miserably broken (please dont say "but it works for me(tm)").

it was bad behaviour since forever. now as OpenELEC is moving pvr clients to addon repos, it becomes more and more visible.

I think you didnt get my point. installing / uninstalling / disabling / enabling addons is user choice. you cant just force-disable something. if you do, you should somehow keep track WHY you did, and try re-enable addons when that "WHY" reason for disabling is no more valid. btw what happens with "disabled" addons? do they ever auto update? 

however, I am fine with ANY solution that works for everyone and is NO PAIN. I am not going to argue on the design. I just feel it's broken. sorry for the noise.

**Comment by xhaggi** [comment]
@stefansaraev thanks for the diff i'll add this to my PVR addon improvement PR ;)

**Comment by stefansaraev** [comment]
@xhaggi you'd better not. as it is now, it will cause other issues! it was just an example..

**Comment by stefansaraev** [comment]
news on this? http://sprunge.us/JAIK

@opdenkamp  FYI, sometimes, configured and WORKING pvr client addons get auto-disabled when they are updated from repos.. (not related to this PR, but it's about "well lets force disable stuff nbecause it's cool")

**Comment by opdenkamp** [comment]
We have always disabled add-ons because it's cool. And I'm out camping ;)


-------- Oorspronkelijk bericht --------
Van: Stefan Saraev <notifications@github.com> 
Datum:17-05-2015  12:36  (GMT+01:00) 
Aan: xbmc/xbmc <xbmc@noreply.github.com> 
Cc: Lars Op den Kamp <opdenkamp@gmail.com> 
Onderwerp: Re: [xbmc] [pvr] fixed crash when multiple add-on instances get
  registered (#6732) 

news on this? http://sprunge.us/JAIK

@opdenkamp FYI, sometimes, configured and WORKING pvr client addons get auto-disabled when they are updated from repos.. (not related to this PR, but it's about "well lets force disable stuff nbecause it's cool")

**Comment by stefansaraev** [comment]
fyi, after #7239 I cant reproduce anymore.

**Comment by mkortstiege** [comment]
What's the status here?

**Comment by MartijnKaijser** [comment]
Closing this. Please resubmit for comments when it's rebased

**Pull request closed without merging**
