### PR TITLE
[Builtins/Cec] add missing registrations

### PR DESCRIPTION
**Pull request by mk01**
after commit https://github.com/xbmc/xbmc/commit/f0ac2a8a015100e2472501c560d26f073b9a33c7

### CODE REVIEW

**Comment by akva2** [comment]
Woops. This was an error on my behalf..

**Comment by stefansaraev** [comment]
jenkins build this please.

@akva2 fyi lirc.stop() and lirc.start() were also broken last time I checked (months or two ago), but not sure if it is related to your builtins rework

**Comment by akva2** [comment]
Could very well be. it looks like i put off the conditional registration for later then forgot. I had a plan to avoid ifdefs..

**Comment by mk01** [comment]
@akva2 
what you had in mind?

check peripheral bus for presence of CEC feature ?

**Comment by akva2** [comment]
Put it in a separate file and do the conditional in the build system

-------- Opprinnelig melding --------
Fra: Matus Kral <notifications@github.com>
Dato: 04.04.2016 21:10 (GMT+01:00)
Til: xbmc/xbmc <xbmc@noreply.github.com>
Ko: Arne Morten Kvarving <Arne.Morten.Kvarving@sintef.no>
Emne: Re: [xbmc/xbmc] [Builtins/Cec] add missing registrations (#9535)


@akva2<https://github.com/akva2>
what you had in mind?

check peripheral bus for presence of CEC feature ?

**Comment by akva2** [comment]
which made sense in my fork where there's a single build system but as long as there are 6 or whatever we are at now in mainline it doesn't so ifdefery is the cleanest.

**Comment by akva2** [comment]
@stefansaraev please pick/test https://github.com/notspiff/xbmc/commit/d9238dfdf6ef4f95b0e1acb3c9b20582748ced66

**Comment by stefansaraev** [comment]
nah. g_RemoteControl is mo more. seems lirc stuff is moved to https://github.com/xbmc/xbmc/blob/master/xbmc/input/InputManager.cpp#L612

**Comment by akva2** [comment]
right.

**Comment by pejobo** [comment]
Is this defect also present in Jarvis? I've got the same problem as described in http://forum.kodi.tv/showthread.php?tid=265743

**Pull request merged**
