### PR TITLE
[PythonInvoker] Remove deprecated python c api calls, clang-format

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
**1st commit:**

- Python 3.9 b1 has introduced a change that has inadvertently caused a deprecated (since 3.2) function (PyEval_ReleaseLock) to cause segfaults.
This update changes to use the non deprecated calls around GIL acquire/release. This prepares us for the planned removal of these deprecated features in Python 4 as well.

- In addition to this change, have gone through and removed some old comments that are no longer current

- XBPython::Finalize() codepath also does not appear to be executed in any way on current master. Have removed this just to clean up the code. My concern here is we no longer execute Py_Finalize, however as far as i can prove so far, we havent done this at least since the py3 change, with no apparent side effects. 
As we have 1 main interpreter that is init on first call of XBPython::OnScriptInitialized, we dont uninit the interpreter at all again as m_iDllScriptCounter never goes to 0 until system shutdown, at which the 10s timer never becomes valid. If anyone can see a requirement for us to call Py_Finalize(), we could look to call it on shutdown somewhere, but wasnt something i could implement without spending more time on it, and im still not even sure what benefit it would bring as all existing threads/scripts are being shutdown/managed already.

**2/3 commits:**

- Just running clang-format

## Motivation and Context
https://forum.kodi.tv/showthread.php?tid=356701

## How Has This Been Tested?
OSX Python 3.8.5
@ronie has confirmed Python 3.8 and 3.9RC1, and another confirmation from @asavah 

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ronie** [comment]
let's try to summon @jimfcarroll for a code review

**Comment by MastaG** [comment]
I can confirm this fixes the segfault when using Python 3.9 (Fedora 33 - arm 32bit).
```
 #0  0x00000000b6573b18 PyEval_ReleaseLock (libpython3.9.so.1.0 + 0x3db18)
```
Thanks

**Comment by jimfcarroll** [comment]
This looks great. Much better than the previous state. I have 1 question. The `savestate` variable in XBPython was part of a hack to obtain the GIL without using the deprecated PyEval_AcquireLock. You're now doing it correctly so i think the variable can be removed from XBPython. It was set there to be referenced in the hack in PythonInvoker and for no other reason (at least that's the way it now appears).

**Comment by fuzzard** [comment]
Thanks @jimfcarroll Ive removed the savestate as suggested. Indeed it does look like it was only used to handle the finalize state.

Just to mention for the record, i believe removing the use of Py_Finalize reads as ok via the python docs. As we do not (currently at least) completely shutdown the interpreter until the end of life of the app, it doesnt seem to be required. There are also caveat notes about multiple Py_Initialize and Py_Finalize cycles that currently cause issues (not all memory objects being released) due to the old style module importing. Supposedly this should clear up when all modules are changed to multi-phase init

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
@jimfcarroll Ive pushed another commit that removes some other methods, that as far as i can see are no longer used.
You wouldnt happen to be able to rack your brain for any context around their past usage when you have time?

**Pull request merged**
