### PR TITLE
[tools/depends][target] Bump libass 0.17.1

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Bump Libass 0.17.0

## Motivation and context
Dep Bump. fair few fixes.

@CastagnaIT  this will be a question for you

`
Add ASS_FEATURE_WRAP_UNICODE to allow automatic linebreaks in accordance with the Unicode line breaking algorithm instead of ASS' much stricter breaking rules. For the feature to be available at runtime, libass must be linked against the new optional dependency [libunibreak](https://github.com/adah1972/libunibreak).
`

Ive added a commit that allows us to build libunibreak if the above is of any use. libunibreak is quite small, and a very simple build system, so its quite simple, however if the above isnt useful in any manner, let me know and i'll drop that commit.

@wsnipex i had a look at ubuntu PPA's and looks like libunibreak is readily available in there, so shouldnt add any hassle on that front if @CastagnaIT wishes to use it.

## How has this been tested?
Build osx-arm

## What is the effect on users?
N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CastagnaIT** [comment]
thank you
this new version bring many changes i will have to check other libass changes as well

what worries me most are the Windows builds
this build update allows the library to be built also for Windows from original libass repo?

i think we can try to drop our custom build for windows
of relevant only contains the fix to reading unicode filenames
which theoretically they should have fixed in some way, but ofc need to be verified

**Comment by CastagnaIT** [comment]
for ASS_FEATURE_WRAP_UNICODE feature
imo it could be useful since we adopt libass to rendering other format types of subtitles, from their commit:
```
This is useful for non-ASS renderers utilising libass, especially for
languages typically not using ASCII-spaces to separate words, but
also to correctly break on punctuation even in languages that do.
```

i am not expert of build system, now i use Windows only to develop i think i cannot test this change
i lost really too hours to try building kodi/addons on linux/android
also VM dont collaborate sometime crashes in the middle of compiling
so i abandoned working on linux/android world

imo we should try keep libass versions consistent having v0.15 on windows and v0.17 on other platforms there are a bit of changes under the hood

maybe @enen92 can say its idea

**Comment by CastagnaIT** [comment]
we have to skip 0.17.0 that bring some bug crashes, so we have to move foward to 0.17.1
for now i will test 17.1 on windows, then i will see if im able to do a test on linux

**Comment by fritsch** [comment]
```
03-07 21:57:18.773  9397  9397 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "libunibreak.so" not found
03-07 21:57:18.773  9397  9397 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
03-07 21:57:18.773  9397  9397 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1669)
03-07 21:57:18.773  9397  9397 E AndroidRuntime: 	at org.xbmc.kodi.Main.onCreate(Main.java:120)
03-07 21:57:18.773  9397  9397 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7169)
03-07 21:57:18.773  9397  9397 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7159)
03-07 21:57:18.773  9397  9397 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
03-07 21:57:18.773  9397  9397 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2933)
03-07 21:57:18.773  9397  9397 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3094)
03-07 21:57:18.773  9397  9397 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
03-07 21:57:18.773  9397  9397 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
03-07 21:57:18.773  9397  9397 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
03-07 21:57:18.773  9397  9397 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
03-07 21:57:18.773  9397  9397 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-07 21:57:18.773  9397  9397 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:211)
03-07 21:57:18.773  9397  9397 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6769)
03-07 21:57:18.773  9397  9397 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-07 21:57:18.773  9397  9397 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-07 21:57:18.773  9397  9397 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
03-07 21:57:18.775   424  1431 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen org.xbmc.kodi#0
03-07 21:57:18.775   424  1431 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen org.xbmc.kodi#0
03-07 21:57:18.775   582   801 I AmazonPowerManagerVendorCallback: Wakelock released UID:1000 PID:582 Tag:WindowManager
```

Does not look too good on Android 32 bit. Does it work for you?

**Pull request merged**
