### PR TITLE
add ListItem.IsParentFolder infobool

### PR DESCRIPTION
**Pull request by ronie**
provide skins with an easy way to check if the focused item is the parent folder item.

currently skins have to use workarounds like:
`StringCompare(ListItem.Label,..)`

### CODE REVIEW

**Comment by Razzeee** [comment]
We might want to add 
    if (item->IsFileItem())  
before that?

**Comment by ronie** [comment]
thx! updated.

**Comment by Razzeee** [comment]
Can you rebase?

**Comment by ronie** [comment]
rebased.

**Comment by Razzeee** [comment]
jenkins build and merge

**Pull request merged**
