### PR TITLE
restore compatibility with sqlite3 v3.8

### PR DESCRIPTION
**Pull request by olafhering**
Wrap defines from new sqlite3 versions:
SQLITE_IOERR_VNODE was introduced in v3.9.1
SQLITE_IOERR_AUTH was introduced in v3.10.0

Fixes commit 2e54c809387fc0ced6d26602f42a14b0797552dc

Signed-off-by: Olaf Hering <olaf@aepfle.de>

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by olafhering** [comment]
As an alternative, adjust `cmake/modules/FindSqlite3.cmake`, add `sqlite3>=3.10.0`.

**Comment by Rechi** [comment]
sqlite3 3.10.0 was released 6th January 2016, that's more then 3 years ago.
I do not see a need to support something even older.

**Comment by olafhering** [comment]
Well, if "was released N years ago" was ever a valid argument, one could jump straight to newer toolchains or whatever else seems appropriate. Is think there are users out there who do not want, and even need, to upgrade parts of their system.

Was there any substantial work in `xbmc/dbwrappers/sqlitedataset.cpp` that warrants an updated pkgconfig check? To me it does not look like that, but I do know nothing about sqlite3.

**Comment by fritsch** [comment]
https://www.cvedetails.com/vulnerability-list/vendor_id-9237/Sqlite.html <- I'd highly suggest you to upgrade immedietaly - especially for 3.8

**Comment by olafhering** [comment]
Not an argument either, CVEs are fixed by `zypper patch`.

**Comment by notspiff** [comment]
it's 2 lines, additions to an enum already riddled with tons of ifdefs, and helps a whole distro. i really don't think this is worth holding back.

**Comment by fritsch** [comment]
> Not an argument either, CVEs are fixed by `zypper patch`.

Don't think only inside your distro silo box.

But I agree with @notspiff

**Comment by pkerling** [comment]
We usually keep support if it helps a distro and is not too much work, and in this case I think the latter part is quite clear. To be honest, I mainly look at Debian stable and Ubuntu LTS when making such decisions. Can you tell us for what specific distro/release this is for future reference?

> Well, if "was released N years ago" was ever a valid argument, one could jump straight to newer toolchains or whatever else seems appropriate. Is think there are users out there who do not want, and even need, to upgrade parts of their system.

Of course there are, but the quesiton is whether we want to/can support that. There are always "users out there" doing XY or wanting to do Z, especially with Kodi :-) You also have to consider that Kodi is a very end-user-centric application that does not typically run on server distros and the like (and is not really intended to anyway). We need to have at least up-to-date kernel and mesa for a good multimedia experience.

**Review by yol — APPROVED** [review]

**Comment by olafhering** [comment]
This is for Leap 42.3.

Regarding the security argument: if one would go that route, only the "very latest" would be allowed which means consumers of Kodi must compile their own copy, despite the fact that `zypper patch` just fixed it without bumping the library version.

**Comment by pkerling** [comment]
> Regarding the security argument: if one would go that route, only the "very latest" would be allowed

You're taking this far too extreme

**Pull request merged**
