### PR TITLE
[Estuary][PVR] Timers homescreen widget

### PR DESCRIPTION
**Pull request by ksooo**
The existing "Now recording" and "Next recording" widgets are kind of style breakers as generally Estuary organizes Home screen information of any kind in "lists", not with static widgets periodically switching content.

This PR removes those old widgets and replaces them with a Timers widgets looking and functioning like Recently watched channels, Recent Recordings, Channel groups widgets.

screenshot00001

@ronie do the skin changes look okay for you?
@phunkyfish  are the code changes good?

### CODE REVIEW

**Review by phunkyfish — APPROVED** [review]
Looks good from the C++ side.

**Review by ronie — APPROVED** [review]
nice improvement, skin code looks fine to me.

**Comment by ksooo** [comment]
> when it‘s opened for a recent recording

unrelated to this PR.

**Comment by ksooo** [comment]
??? what resolution are you running? Plenty of free space here. However, iirc, a contextmenu should get scrollers in case not all items fit to screen. 

screenshot00001

**Pull request merged**
