### PR TITLE
[Krypton] Fix crash on startup when peripheral.joystick is disabled

### PR DESCRIPTION
**Pull request by garbear**
Backport of #12951

### CODE REVIEW

**Comment by garbear** [comment]
Tested on Shield TV

**Comment by garbear** [comment]
jenkins build and merge

**Comment by garbear** [comment]
jenkins build and merge

**Comment by garbear** [comment]
jenkins build and merge

**Comment by Rechi** [comment]
build and merge doesn't work for Krypton, as it doesn't exclude windows x64, linux wayland and ios64

jenkins build this please

**Pull request merged**
