### PR TITLE
Fix missing DVD menu indicators when using DRM PRIME decoder

### LINKED ISSUE #18898: RPi4 - kodi 19.0 b1 - Dvd menu highlighting not working with some dvd's
### Describe the bug
Here is a clear and concise description of what the problem is:

When navigating a dvd menu no menu item highlight is visible, the selecting sound is hearable but no visible hightlight change is occurring. When pressing the remote, the selected menu item is carried out.  
Also when selecting a non working dvd when kodi just started no menu is visible at all (black screen), when pressing the remote in the blind the movie starts playing and the screen will appear. Selecting the movie for the second will show the dvd menu without highlighted menu items.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Visible highlight change in the dvd menu

## Actual Behavior

No highlight visible at all

### To Reproduce

1. select a non working dvd 
2.
3.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/taquwawuwi.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP
-  [X] Libreelec 9.8

 - Operating system version/name:
 - Kodi version:
19.0 beta 1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #21553: Menu navigation marks don't appear on some DVD .ISO image files on Kodi 19 and 20
### Describe the bug
Here is a clear and concise description of what the problem is:

Menu navigation marks don't appear on some DVD .ISO image files on Kodi 19 and 20, these worked fine on Kodi 18 and earlier.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Marks showing what is being selected in the menu should show up.

## Actual Behavior

Navigation marks don't show on some .ISO files.  Screen shots below give examples

### To Reproduce

1. Navigation marks don't show on 2 Broke Girls season sets
2.Navigation marks don't show on Allo Allo  season sets
3.

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/8896111/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

2BrokeGirls18-Edit

2BrokeGirls1920-Edit

AlloAllo18-Edit

AlloAllo1920-Edit

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: [LibreELEC]
 - Kodi version: 19 and 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by popcornmix**
## Description
Fix for missing DVD menu indicators when using DRM PRIME decoder.

## Motivation and context
Fix for https://github.com/xbmc/xbmc/issues/21553 https://github.com/xbmc/xbmc/issues/18898

## How has this been tested?
Tested on an RPi3 with "Allow hardware acceleration with DRM PRIME" enabled, and an RPi4 with that setting disabled.

## What is the effect on users?
Working DVD menu indicators

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by popcornmix** [comment]
This is a draft PR for testing, and for suggestions.
The reason for missing DVD indicators is "timeout waiting for buffer" in `VideoPlayerVideo` resulting in `ProcessOverlays` path not being taken.

Debugging involved rewriting DVDVideoCodecDRMPRIME to match DVDVideoCodecFFMPEG closely enough that menus indicators started working, then backing out all changes that weren't required. Both changes here were required.

**Comment by popcornmix** [comment]
There is a test LibreELEC (20.0a1-Nexus) build for Pi4 with this patch [here](https://drive.google.com/uc?id=194-QfdBMqYP0etCZKm16uCRFjhWgXh7z&export=download) if anyone can test.

**Comment by xoocoon** [comment]
Hi there, thanks for working on this issue. I have the same problem on the OSMC 2022-03 on Raspberry Pi 4B. Could you provide a set of patched files that need to be replaced in OSMC's Kodi installation?
This way I could test the patch without having to set up LibreELEC. Thanks.

**Comment by popcornmix** [comment]
The source file patches are in this PR. They would need to be built for osmc, but that's not something I can do.

**Comment by enen92** [comment]
maybe @samnazarko can help (no idea what test build infra osmc uses)

**Comment by samnazarko** [comment]
If this is being backported to v19 then we can make it available shortly, otherwise it will need to be made available in v20.

**Review by lrusak — APPROVED** [review]
LGTM if it fixes the issue

**Comment by A1RF0RCE1** [comment]
I run a couple of tests on LibreELEC (20.0a1-Nexus) build for Pi4, all the DVD navigation marks are working properly. It looks like this fixes the non working DVD highlights.. Thanks!!!

**Comment by popcornmix** [comment]
@samnazarko Top two commits of https://github.com/popcornmix/xbmc/commits/gbm_matrix_dvd is a matrix version.

**Comment by samnazarko** [comment]
Thanks! I’ll check this out.

**Comment by xoocoon** [comment]
I can confirm that DVD menus work on the Pi 4B with the LE patch by @popcornmix. Thanks for the good and agile work!
I am looking forward to seeing this improvement in OSMC.

**Comment by dkadioglu** [comment]
I can also confirm, that this fixes the DVD menu highlighting and navigation. At least for the two DVDs I tested and only by disabling the deinterlacing as it is currently patched into by the Libreelec Devs in current master of Libreelec..
I had to adapt the patch for this fix slightly, as it fails otherwise. I hope, I did nothing wrong. Following is the modified patch, which applies fine now after the deinterlacing patch has been applied (https://github.com/LibreELEC/LibreELEC.tv/blob/master/projects/RPi/patches/kodi/kodi-001-deinterlace.patch):
```
From 3efd04afc715fda4c119eaf68769b5d08f65301e Mon Sep 17 00:00:00 2001
From: Dom Cobley <popcornmix@gmail.com>
Date: Thu, 7 Jul 2022 15:41:58 +0100
Subject: [PATCH 1/2] CDVDVideoCodecDRMPRIME: Move picture release after
 avcodec_receive_frame

This matches the code order of DVDVideoCodecFFMPEG and is required
for working DVD menus
---
 .../DVDCodecs/Video/DVDVideoCodecDRMPRIME.cpp        | 12 ++++++------
 1 file changed, 6 insertions(+), 6 deletions(-)

diff --git a/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecDRMPRIME.cpp b/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecDRMPRIME.cpp
index ec2016cc060ff..dd4b4a9968663 100644
--- a/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecDRMPRIME.cpp
+++ b/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecDRMPRIME.cpp
@@ -875,12 +875,6 @@ CDVDVideoCodec::VCReturn CDVDVideoCodecDRMPRIME::GetPicture(VideoPicture* pVideo
   if (m_codecControlFlags & DVD_CODEC_CTRL_DRAIN)
     Drain();
 
-  if (pVideoPicture->videoBuffer)
-  {
-    pVideoPicture->videoBuffer->Release();
-    pVideoPicture->videoBuffer = nullptr;
-  }
-
   if (m_pFilterGraph)
   {
     auto ret = ProcessFilterOut();
@@ -910,6 +904,12 @@ CDVDVideoCodec::VCReturn CDVDVideoCodecDRMPRIME::GetPicture(VideoPicture* pVideo
     return VC_ERROR;
   }
 
+  if (pVideoPicture->videoBuffer)
+  {
+    pVideoPicture->videoBuffer->Release();
+    pVideoPicture->videoBuffer = nullptr;
+  }
+
   if (!m_processInfo.GetVideoInterlaced() && m_pFrame->interlaced_frame)
     m_processInfo.SetVideoInterlaced(true);

From 761cde1977fa090e205085dba76451c139257d0c Mon Sep 17 00:00:00 2001
From: Dom Cobley <popcornmix@gmail.com>
Date: Thu, 7 Jul 2022 12:31:12 +0100
Subject: [PATCH 2/2] RendererDRMPRIME: Remove NeedBuffer check for valid fd

This check breaks DVD menus. All calls return true which prevents
new pictures being released, stalling DVD menus
---
 .../VideoRenderers/HwDecRender/RendererDRMPRIME.cpp           | 4 ----
 1 file changed, 4 deletions(-)

diff --git a/xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/RendererDRMPRIME.cpp b/xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/RendererDRMPRIME.cpp
index e304d601d2755..f2ea9d246c81b 100644
--- a/xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/RendererDRMPRIME.cpp
+++ b/xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/RendererDRMPRIME.cpp
@@ -179,10 +179,6 @@ bool CRendererDRMPRIME::NeedBuffer(int index)
   if (m_iLastRenderBuffer == index)
     return true;
 
-  CVideoBufferDRMPRIME* buffer = dynamic_cast<CVideoBufferDRMPRIME*>(m_buffers[index].videoBuffer);
-  if (buffer && buffer->m_fb_id)
-    return true;
-
   return false;
 }
```
I have one issue though. As I mentioned above, this fix only works, when I disable deinterlacing. If deinterlacing is enabled, only one of the DVDs works. The other one gives me just a black screen. However, still stopable. Watching Live TV (TVHeadend) also doesn't work with this fix applied and enabled deinterlacing - the first frame just hangs and Kodi has to be restarted by systemctl. When deinterlacing is disabled, watching Live TV works as it should. However, without this fix for the DVD menus, deinterlacing works with Live TV but occasionally I have the same problem with the hanging first frame, which can be fixed by just stopping and restarting the channel as Kodi is still reacting. It also seems, that this mostly happens with SD channels and not with HD channels.

Sorry for that long description, I hope it is understandable. If not, please ask. If the deinterlacing part shouldn't have been mentioned here, please give me a hint, where I should describe this issue.

Finally, a big thank you for fixing the DVD menus!!!

**Comment by popcornmix** [comment]
@dkadioglu I also applied the patch to a (master) tree with deinterlacing patches in place.
Try the top two commits from See https://github.com/popcornmix/xbmc/tree/gbm

**Comment by A1RF0RCE1** [comment]
Some dvd’s won’t open at all, giving a dvdnav error. will post a debug log..

**Comment by enen92** [comment]
@A1RF0RCE1 can you check with alpha 2 which actually bumps the library versions? https://github.com/LibreELEC/LibreELEC.tv/pull/6673

**Comment by popcornmix** [comment]
@A1RF0RCE1 if the issue existed before this PR, then it's best to keep discussion on an separate kodi issue.
dvdnav is not something this PR interacts with (the fixes are in DRM PRIME decoder).

**Comment by A1RF0RCE1** [comment]
Ok I will open a new issue! @enen92  also the latest alpha 2 is not working.

**Review by jernejsk — APPROVED** [review]

**Comment by jernejsk** [comment]
This works nicely on Allwinner H6 and it fixes bug when discarded frames were not actually discarded. Nice work!

**Comment by dkadioglu** [comment]
> @dkadioglu I also applied the patch to a (master) tree with deinterlacing patches in place. Try the top two commits from See https://github.com/popcornmix/xbmc/tree/gbm

Thanks @popcornmix I tried your mentioned commits and with them it works now! :-)

**Pull request merged**
