### PR TITLE
binary addons: add audiodecoders

### PR DESCRIPTION
**Pull request by Montellese**
This PR will add some of the audiodecoers that @notspiff has prepared and that will be replacing functionality that is currently in PAPlayer and will be removed with #6131.

TODOs:
- [x] audiodecoder.nosefart
- [x] audiodecoder.timidity
- [x] audiodecoder.sidplay
- [x] audiodecoder.stsound
- [x] audiodecoder.snesapu
- [x] audiodecoder.vgmstream
- [x] audiodecoder.modplug

### CODE REVIEW

**Comment by topfs2** [comment]
So much awesome :)

**Comment by Montellese** [comment]
Just wanna see how other platforms look: jenkins build addons please

**Comment by Montellese** [comment]
Actually it probably only works on win32 until it is added to depends :-/

**Comment by Memphiz** [comment]
Maybe we should have a catch all Target in depends instead of having xbmc-pvr-addons and so on?

**Comment by Montellese** [comment]
@Memphiz: I have no idea why we have separate depends targets for the binary addons probably because at first PVR addons weren't binary addons but audioencoders were. And it might be more convenient for developers who only want to build a certain type of binary addons.

@notspiff: Timidity is gonna be tricky on win32 because we build that one with mingw right now.

**Comment by Montellese** [comment]
jenkins build addons please

**Comment by notspiff** [comment]
@montellese in principle you just have to call the mingw env through externalproject no ? that's probably something we are going to have to establish at some point. maybe a prebuilt is easier for now though.

**Comment by Montellese** [comment]
That's why I said it's gonna be tricky ;-)

**Comment by notspiff** [comment]
maybe another path then.

audiodecoder.fluidsynth is a much better, more modern, less crappy midi softsynth engine. it does everything timidity do (for us anyways) and more.

**Comment by Montellese** [comment]
Looks like our buildsystem isn't that bad anymore. nosefart, snesapu and vgmstream built fine on all platforms (but obviously untested).

@notspiff: I didn't say we shouldn't integrate a (prebuilt) MinGW build environment. All I wanted to say is that it's gonna take more time.

**Comment by FernetMenta** [comment]
are you saying that timidity does not build with nmake vs?

**Comment by notspiff** [comment]
montellese, got that. but i'll be buggering for fluidsynth later at some point so we can in theory skip timidity was my point ;)

**Comment by Montellese** [comment]
@FernetMenta: correct, see https://github.com/xbmc/xbmc/blob/master/tools/buildsteps/win32/make-mingwlibs.sh#L103 for how we build timidity in core right now.

**Comment by Montellese** [comment]
@notspiff: Sure whatever works better. I have no clue about these decoders and their feature sets. Once again I'm only the buildsystem monkey :-)

**Comment by notspiff** [comment]
heh, as always it's not an entirely easy question to answer.

fluidsynth pro's:
- more modern and is an active project, 
- more features
- has an upstream cmake based build system with support for osx, linux, windows (visual studio).

fluidsynth con's:
- it does not support '.pat' files (a gravis ultrasound legacy - an old sound card from the days when sound cards matter ;)) - which is a one file per midi instrument standard, it only supports the 'soundfont' standard (creative labs).
- higher cpu usage due to more advanced filters and mixing
- pulls in some somewhat nasty dependencies - above all the glib abomination :/

timidity pro's:
- supports both soundfonts and .pat files (timidity.cfg)
- quite contained - no dependencies

timidity con's:
- dead project, not maintained
- old code
- port to windows seems to be a pita

**Comment by FernetMenta** [comment]
@Montellese the old timidity dll will be history after this change. how does it interfere?

**Comment by notspiff** [comment]
since timidity is from the late 90s / early 2000's it is not hard to imagine that it is full of gnuisms and such. c++ was an utter mess back then..

**Comment by Montellese** [comment]
@FernetMenta: It still needs to be built (as a static library) for the binary addon so we still need the proper buildsystem for that.
I have no idea why it's built with MinGW but I'm assuming that it has only been written for autotools + gcc.

**Comment by Montellese** [comment]
I added some logic to `prepare-env.cmake` for win32 which checks if cmake can find a `patch` (or `patch.exe`) executable and if not downloads an archive from our mirrors, extracts it and copies `patch.exe` into the `bin` dir of the output path.

I got `audiodecoder.modplug` compiling on win32 with a few patches I took from `lib/libmodplug`. PR has already been sent to @notspiff.

**Comment by Montellese** [comment]
I managed to get `audiodecoder.sidplay` and`audiodecoder.stsound` working as well. Now the only one left is `audiodecoder.timidity` but as already mentioned that one's a little tricky.

**Comment by FernetMenta** [comment]
great! I suggest that we merge this now, then #6131 . while this can be tested we can still think about a solution for MIDI

**Comment by wsnipex** [comment]
The addons need debian packaging stuff before merging.

**Comment by Montellese** [comment]
@FernetMenta: Would it be possible to adjust #6131 to not remove timidity until we have it as an audiodecoder addon?

**Comment by FernetMenta** [comment]
@Montellese I don't think timidity is that important and worth the effort on a development branch. I doubt there is a single person interested in a 20 year old discontinued component. If we have no substitute at the time we branch for release, we can think about a re-add. OK?

**Comment by notspiff** [comment]
can't a !windows be added to platforms.txt ?

**Comment by FernetMenta** [comment]
sounds like a good idea

**Comment by notspiff** [comment]
@wsnipex added (untested).

**Comment by Montellese** [comment]
I added `audiodecoder.timidity` with `!windows` in `platforms.txt` and bumped all addons to the latest revision in @notspiff repositories.
jenkins build addons please

**Comment by notspiff** [comment]
added library names for timidity.

**Comment by Montellese** [comment]
@notspiff: timidity is also missing the `kodi-platform` dependency handling.

**Comment by notspiff** [comment]
kodiplatform added.

**Comment by Montellese** [comment]
jenkins build addons please

**Comment by Montellese** [comment]
@Memphiz: something doesn't seem to work yet with the binary addon jenkins hook.

**Comment by Memphiz** [comment]
jenkins build addons please

**Comment by Memphiz** [comment]
jenkins build addons please - platform matrix projects seem to behave different then normal freerun jobs *grrr*

**Comment by Memphiz** [comment]
trying the old approach again (have the feeling that it was ok in the first place *narf*) jenkins build addons please

**Comment by Memphiz** [comment]
@Montellese i think i just had a brainfart yesterday - as of the looks the former approach (which i have put in place again) did in deed built the merged PR as intended. The only thing that doesn't work is marking the commit from the PR  that is currently built, failed building or was ok building. Beside that it should work. (and did all the time). Maybe we should add an obvious error to this PR for double checking if we see that error in the logs then.

Nevertheless - those buildlogs show alot of errors and are still marked as green - i really need to figure out why that groovy script doesn't correctly does the file.exists() :(

**Comment by Memphiz** [comment]
finally @Montellese @opdenkamp @FernetMenta 

http://jenkins.kodi.tv/job/OSX-32/3644/

Thats how it will look when binary addons failed - there is still the todo to mark failing addons via cmake somehow for making this generic (and working for win32 too then).

**Comment by Montellese** [comment]
jenkins build addons please

**Comment by Montellese** [comment]
Updated and rebased. jenkins build addons please

**Comment by Montellese** [comment]
Had to fix the `patch` support on win32. @wsnipex: Could you take a look at the changes to `handle-depends.cmake` in 41332536e3d0e68601471a9e8e2f1469e9885cb1 and see if that's ok for linux too?
jenkins build addons please

**Comment by Montellese** [comment]
`audiodecoder.sidplay` seems to fail on all non-win32 platforms with
```
/bin/sh ../../libtool --tag=CXX   --mode=compile /usr/bin/x86_64-linux-gnu-g++ -DHAVE_CONFIG_H    -fPIC -DPIC     -fPIC -DPIC -g -O2 -std=gnu++11   -DHAVE_UNIX -I../../include -I../../include/sidplay -MT mos6510.lo -MD -MP -MF .deps/mos6510.Tpo -c -o mos6510.lo mos6510.cpp
../../libtool: line 662: X--tag=CXX: command not found
../../libtool: line 695: libtool: ignoring unknown tag : command not found
../../libtool: line 662: X--mode=compile: command not found
../../libtool: line 812: *** Warning: inferring the mode of operation is deprecated.: command not found
../../libtool: line 813: *** Future versions of Libtool will require -mode=MODE be specified.: command not found
../../libtool: line 956: X/usr/bin/x86_64-linux-gnu-g++: No such file or directory
../../libtool: line 956: X-DHAVE_CONFIG_H: command not found
../../libtool: line 956: X-fPIC: command not found
../../libtool: line 956: X-DPIC: command not found
../../libtool: line 956: X-fPIC: command not found
../../libtool: line 956: X-DPIC: command not found
../../libtool: line 956: X-g: command not found
../../libtool: line 956: X-O2: command not found
../../libtool: line 956: X-std=gnu++11: command not found
../../libtool: line 956: X-DHAVE_UNIX: command not found
../../libtool: line 956: X-I../../include: No such file or directory
../../libtool: line 956: X-I../../include/sidplay: No such file or directory
../../libtool: line 956: X-MT: command not found
../../libtool: line 956: Xmos6510.lo: command not found
../../libtool: line 956: X-MD: command not found
../../libtool: line 956: X-MP: command not found
../../libtool: line 956: X-MF: command not found
../../libtool: line 956: X.deps/mos6510.Tpo: No such file or directory
../../libtool: line 956: X-c: command not found
../../libtool: line 1004: Xmos6510.lo: command not found
../../libtool: line 1009: libtool: compile: cannot determine name of library object from `': command not found
make[11]: *** [mos6510.lo] Error 1
```

`audiodecoder.stsound` fails on android with
```
CMakeFiles/audiodecoder.stsound.dir/lib/stsound/StSoundLibrary/LZH/LzhLib.cpp.o -c /home/jenkins/workspace/BINARY-ADDONS/platform_label/android/tools/depends/target/binary-addons/arm-linux-androideabi-android-17/build/audiodecoder.stsound/lib/stsound/StSoundLibrary/LZH/LzhLib.cpp
/home/jenkins/workspace/BINARY-ADDONS/platform_label/android/tools/depends/target/binary-addons/arm-linux-androideabi-android-17/build/audiodecoder.stsound/lib/stsound/StSoundLibrary/LZH/LzhLib.cpp: In member function 'int CLzhDepacker::DataIn(void*, int)':
/home/jenkins/workspace/BINARY-ADDONS/platform_label/android/tools/depends/target/binary-addons/arm-linux-androideabi-android-17/build/audiodecoder.stsound/lib/stsound/StSoundLibrary/LZH/LzhLib.cpp:49:27: error: 'memcpy' was not declared in this scope
   memcpy(pBuffer,m_pSrc,np);
                           ^
/home/jenkins/workspace/BINARY-ADDONS/platform_label/android/tools/depends/target/binary-addons/arm-linux-androideabi-android-17/build/audiodecoder.stsound/lib/stsound/StSoundLibrary/LZH/LzhLib.cpp: In member function 'int CLzhDepacker::DataOut(void*, int)':
/home/jenkins/workspace/BINARY-ADDONS/platform_label/android/tools/depends/target/binary-addons/arm-linux-androideabi-android-17/build/audiodecoder.stsound/lib/stsound/StSoundLibrary/LZH/LzhLib.cpp:61:27: error: 'memcpy' was not declared in this scope
   memcpy(m_pDst,pBuffer,np);
                           ^
make[7]: *** [CMakeFiles/audiodecoder.stsound.dir/lib/stsound/StSoundLibrary/LZH/LzhLib.cpp.o] Error 1
```
so looks like it's missing an include for `<string.h>`.

**Comment by wsnipex** [comment]
the patch stuff looks fine, shouldn't cause issues on linux, but I didn't actually try it myself. Since jenkins is fine with it, we're most probably good.

**Comment by Memphiz** [comment]
mhh somehow the setting in jenkins which marks unstable builds on github as "OK" was reset - i set it back so that unstable builds are marked as success ... @MartijnKaijser did you reset that setting maybe?

**Comment by MartijnKaijser** [comment]
@Memphiz i have no idea where i would change that. Haven't touched jenkins config in a long while

**Comment by Memphiz** [comment]
you ok - just checking ;) - then it was a hickup during restarts or what not ...

**Comment by notspiff** [comment]
sidplay should, at he very least, be better now. builds locally after some more patching of the autotools build + regeneration through calling autoconf in all subdirs.

**Comment by notspiff** [comment]
and stsound has the include now.

**Comment by Montellese** [comment]
@notspiff: Thanks.
I somehow must have messed up my branch since the last build test because some changes were missing and the addons weren't pointingto the proper commits.
jenkins build addons please

**Comment by Montellese** [comment]
Great, now only `audiodecoder.sidplay` fails on IOS and OSX with
```
libtool: compile:  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -DHAVE_CONFIG_H -fheinous-gnu-extensions -no-cpp-precomp -mcpu=cortex-a8 -mfpu=neon -ftree-vectorize -mfloat-abi=softfp -pipe -Wno-trigraphs -fpascal-strings -O3 -Wreturn-type -Wunused-variable -fmessage-length=0 -gdwarf-2 -arch armv7 -miphoneos-version-min=5.1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk -no-cpp-precomp -mcpu=cortex-a8 -mfpu=neon -ftree-vectorize -mfloat-abi=softfp -pipe -Wno-trigraphs -fpascal-strings -O3 -Wreturn-type -Wunused-variable -fmessage-length=0 -gdwarf-2 -arch armv7 -miphoneos-version-min=5.1 -std=c++11 -stdlib=libc++ -g -O2 -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk -no-cpp-precomp -mcpu=cortex-a8 -mfpu=neon -ftree-vectorize -mfloat-abi=softfp -pipe -Wno-trigraphs -fpascal-strings -O3 -Wreturn-type -Wunused-variable -fmessage-length=0 -gdwarf-2 -arch armv7 -miphoneos-version-min=5.1 -std=c++11 -stdlib=libc++ -g -O2 -std=gnu++11 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk -DHAVE_UNIX -I../../include -I../../include/sidplay/utils -I/Users/Shared/jenkins/workspace/BINARY-ADDONS/platform_label/ios/tools/depends/target/binary-addons/iphoneos8.1_armv7-target/build/sidplay2/src/sidplay2/libsidplay/include -DHAVE_UNIX -MT ini.lo -MD -MP -MF .deps/ini.Tpo -c ini.cpp  -fno-common -DPIC -o ini.o
ini.cpp:103:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^
1 error generated.
make[11]: *** [ini.lo] Error 1
```

**Comment by notspiff** [comment]
try now.
14. mar. 2015 09.14 skrev "Sascha Montellese" <notifications@github.com>:

**Comment by Montellese** [comment]
@notspiff: Thanks. I just noticed that on WIN32 we don't build `libsidutils` but it still compiles (didn't runtime test)?
jenkins build addons please

**Comment by notspiff** [comment]
not really a problem. hardsid, libsidutils, hardsid-builder is unused but built due to a monotonic build system i cba to rip more to pieces.

**Comment by Memphiz** [comment]
On that ios Snippet it has

-std=c++11 -stdlib=libc++ -g -O2 -std=gnu++11

std=c++11 is from us and correct - std=gnu++11 doesn't match how kodi is compiled and might give Problems maybe - where does it come from? It needs to go!

**Comment by notspiff** [comment]
i don't think it matter? abi is the same for those, it's just some extra gnu extensions which get enabled and since they are unused.

that being said, we should of course kill it. the flag is picked up by autoconf for some reason, it certainly isn't in the build system itself (code is from late 90s). so it's passed externally, i can't really tell how..

**Comment by Montellese** [comment]
@notspiff: Great, all addons built fine.

**Comment by notspiff** [comment]
cool. now it would be nice if peeps could try them on various platforms. see https://github.com/xbmc/xbmc/pull/6463#issuecomment-77006696 for sample links

**Comment by Montellese** [comment]
Tested a few files on win32 with every audiodecoder addon (except for timidity) and made sure that it was loaded with the proper audiodecoder and all sounded fine (at least the Super Mario themes sounded exactly the way I remember).

**Comment by FernetMenta** [comment]
> at least the Super Mario themes sounded exactly the way I remember

hehe, I noticed that too

**Comment by FernetMenta** [comment]
green button time?

**Comment by notspiff** [comment]
depends on which pr will take care of extension and depends pruning.
15. mar. 2015 19.11 skrev "Rainer Hochecker" <notifications@github.com>:

**Comment by FernetMenta** [comment]
I added this https://github.com/FernetMenta/xbmc/commit/e3bb71994c9c476ebd2a75ec71fa82fff5b83cb0
to #6131 
is that what you mean?

**Comment by notspiff** [comment]
extensions yes (see comment). there is also several depends for windows, unified and readme.ubuntu updates. e.g. gdc fp-compiler and possibly nasm.

**Comment by Montellese** [comment]
Should we merge the two PRs or split it up in changes that affect the working system (i.e. putting e3bb71994c9c476ebd2a75ec71fa82fff5b83cb0 and maybe 754d18a352163ee0f96ef66957d2bc352f6ae5ca into this PR) and removing everything that isn't needed anymore (basically f6d58d48d4896a3b1fcf92da47bb6df41c2df70d and maybe some more cleanup)?

**Comment by FernetMenta** [comment]
if I am not mistaken this pr is already complete. it enables addons without breaking existing stuff. imo this should go in as is

**Comment by Montellese** [comment]
Final test before I'm going to merge this. jenkins build addons please

**Comment by Memphiz** [comment]
The growing lists of addons on jenkins are really looking impressive already - nice work!

**Comment by Montellese** [comment]
Thanks everyone involved for the work.

**Pull request merged**
