### PR TITLE
Test file cache changes revert

### PR DESCRIPTION
**Pull request by phunkyfish**
## Description

Testing reverting the following PRs to fix root cause for https://github.com/kodi-pvr/pvr.mediaportal.tvserver/issues/200. We need a win64 test build for users to try:

- https://github.com/xbmc/xbmc/pull/24504
- https://github.com/xbmc/xbmc/pull/24582
- https://github.com/xbmc/xbmc/pull/24640
- https://github.com/xbmc/xbmc/pull/24733

@thexai and @fuzzard FYI

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [x] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by thexai** [comment]
Bug reporter says has tried all cache settings, even cache disabled for all sources:

> I also tried Release 21.0 with all Video Cache Settings from 0-4 and none of those values made any difference, no go.

So why revert `CFileCache` changes if with Cache disabled `CFileCache` code is not used/load at all?

We can be repeat this test with only revert `CFileStreamBuffer` changes?

https://github.com/xbmc/xbmc/pull/24733
https://github.com/xbmc/xbmc/pull/24504

Even if this works why the solution is revert and not investigate this add-on? (all others add-ons works)

Example: 
If all skins are working on Omega but not Amber skin, the solution is fix this skin or revert all core changes until amber works again....

P.S. Is not necessary create a PR for test random reversion code changes.... you can build in Jenkins any cloned kodi repo/branch from other repo that contains any modification.

**Comment by phunkyfish** [comment]
I’m not proposing any revert. Just simply trying to whittle down the number of commits that might be causing the problem. The PR doesn’t build anyway, due to some ffmpeg build issue which is unrelated. I tried to build the branch from my repo on Jenkins first but did not work, so I tried this.

IMHO, we should only be fixing this forward. If we are to fix the addon we would need to figure out what that fix should be. I don’t know where to start on that, so will need some of your help.

**Comment by thexai** [comment]
Can you test this diff in the add-on instead?

```diff
diff --git a/src/lib/tsreader/FileReader.cpp b/src/lib/tsreader/FileReader.cpp
index 358b05f..0d87bea 100644
--- a/src/lib/tsreader/FileReader.cpp
+++ b/src/lib/tsreader/FileReader.cpp
@@ -125,7 +125,7 @@ namespace MPTV
         do
         {
             kodi::Log(ADDON_LOG_INFO, "FileReader::OpenFile() %s.", m_fileName.c_str());
-            if (m_hFile.OpenFile(m_fileName, READ_CHUNKED))
+            if (m_hFile.OpenFile(m_fileName, READ_NO_CACHE))
             {
                 break;
             }
```

**Comment by phunkyfish** [comment]
> If this works, I think the final version should contain more flags:
> 
> `READ_NO_CACHE | READ_TRUNCATED | READ_BITRATE`

Thanks so much! 

I've build the original suggestion here: https://github.com/kodi-pvr/pvr.mediaportal.tvserver/pull/206. Will ask users to test, and if it works will update it to this.

**Comment by phunkyfish** [comment]
The first one didn’t work. But we’ll try the second one anyway.

**Comment by thexai** [comment]
Closing as the fix is in the add-on itself https://github.com/kodi-pvr/pvr.mediaportal.tvserver/pull/206

**Pull request closed without merging**
