### PR TITLE
[tools/depends][target] Bump libmicrohttpd 0.9.75

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Bump latest libmicrohttpd

## Motivation and context
Dep Bump

## How has this been tested?
Build macos arm

## What is the effect on users?
N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by garbear — APPROVED** [review]
I like that this moves the depend to the VERSION format.

**Comment by fuzzard** [comment]
@Karlson2k Have you got any pointers as to why we are tripping over this assert

https://github.com/Karlson2k/libmicrohttpd/blob/9a18a4f83d707c908746474277e85e493555a759/src/microhttpd/connection.c#L1023

We hit it in any test doing an exists checks

eg

https://github.com/xbmc/xbmc/blob/47bc3246eaef7aa8f07cf7fc86f09beb3b68fc95/xbmc/network/test/TestWebServer.cpp#L539-L543

https://github.com/xbmc/xbmc/blob/6c2ceb1db1e2fab1f26586b4734b594cae3f4a10/xbmc/filesystem/test/TestHTTPDirectory.cpp#L224

https://github.com/xbmc/xbmc/blob/6c2ceb1db1e2fab1f26586b4734b594cae3f4a10/xbmc/filesystem/test/TestHTTPDirectory.cpp#L255

Stack of kodi-test threads at assert

```
MHD-connection (5)#0	0x000000018c7a6d98 in __pthread_kill ()
#1	0x0000000112732e84 in pthread_kill ()
#2	0x000000018c716340 in abort ()
#3	0x000000018c715754 in __assert_rtn ()
#4	0x0000000102fcb4a8 in try_ready_normal_body at /Users/brent/Dev/macos/tools/depends/target/libmicrohttpd/macosx12.3_arm64-target-debug/src/microhttpd/connection.c:1027
#5	0x0000000102fcc344 in MHD_connection_handle_idle at /Users/brent/Dev/macos/tools/depends/target/libmicrohttpd/macosx12.3_arm64-target-debug/src/microhttpd/connection.c:4750
#6	0x0000000102fdf774 in call_handlers at /Users/brent/Dev/macos/tools/depends/target/libmicrohttpd/macosx12.3_arm64-target-debug/src/microhttpd/daemon.c:1266
#7	0x0000000102fdf1e0 in thread_main_handle_connection at /Users/brent/Dev/macos/tools/depends/target/libmicrohttpd/macosx12.3_arm64-target-debug/src/microhttpd/daemon.c:2141
#8	0x0000000102fed77c in named_thread_starter at /Users/brent/Dev/macos/tools/depends/target/libmicrohttpd/macosx12.3_arm64-target-debug/src/microhttpd/mhd_threads.c:281
#9	0x0000000112731890 in _pthread_start ()

Thread 1 Queue : com.apple.main-thread (serial)
#0	0x00000001010459c4 in CURLcode XCURL::DllLibCurl::easy_getinfo<double*>(void*, CURLINFO, double*) at /Users/brent/Dev/macos/xbmc/filesystem/DllLibCurl.h:45
#1	0x000000010104df60 in XFILE::CCurlFile::Stat(CURL const&, stat*) at /Users/brent/Dev/macos/xbmc/filesystem/CurlFile.cpp:1581
#2	0x00000001010c68d4 in XFILE::CHTTPDirectory::Exists(CURL const&) at /Users/brent/Dev/macos/xbmc/filesystem/HTTPDirectory.cpp:309
#3	0x0000000100085aa8 in TestHTTPDirectory_BasicMultilineIndex_Test::TestBody() at /Users/brent/Dev/macos/xbmc/filesystem/test/TestHTTPDirectory.cpp:265
#4	0x000000010057a420 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) at /Users/brent/Dev/macos/tools/depends/target/gtest/macosx12.3_arm64-target-debug/googletest/src/gtest.cc:2607
#5	0x000000010053f144 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) at /Users/brent/Dev/macos/tools/depends/target/gtest/macosx12.3_arm64-target-debug/googletest/src/gtest.cc:2643
#6	0x000000010053f094 in testing::Test::Run() at /Users/brent/Dev/macos/tools/depends/target/gtest/macosx12.3_arm64-target-debug/googletest/src/gtest.cc:2682
#7	0x0000000100540074 in testing::TestInfo::Run() at /Users/brent/Dev/macos/tools/depends/target/gtest/macosx12.3_arm64-target-debug/googletest/src/gtest.cc:2861
#8	0x0000000100541170 in testing::TestSuite::Run() at /Users/brent/Dev/macos/tools/depends/target/gtest/macosx12.3_arm64-target-debug/googletest/src/gtest.cc:3015
#9	0x000000010054eaf4 in testing::internal::UnitTestImpl::RunAllTests() at /Users/brent/Dev/macos/tools/depends/target/gtest/macosx12.3_arm64-target-debug/googletest/src/gtest.cc:5855
#10	0x000000010057f518 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) at /Users/brent/Dev/macos/tools/depends/target/gtest/macosx12.3_arm64-target-debug/googletest/src/gtest.cc:2607
#11	0x000000010054e4ec in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) at /Users/brent/Dev/macos/tools/depends/target/gtest/macosx12.3_arm64-target-debug/googletest/src/gtest.cc:2643
#12	0x000000010054e3dc in testing::UnitTest::Run() at /Users/brent/Dev/macos/tools/depends/target/gtest/macosx12.3_arm64-target-debug/googletest/src/gtest.cc:5438
#13	0x000000010017e11c in RUN_ALL_TESTS() at /Users/Shared/xbmc-depends/macosx12.3_arm64-target-debug/include/gtest/gtest.h:2490
#14	0x000000010017e0c8 in main at /Users/brent/Dev/macos/xbmc/test/xbmc-test.cpp:29
#15	0x000000011257d08c in start ()
```

**Comment by Karlson2k** [comment]
@fuzzard Interesting. I'll check it.

**Comment by Karlson2k** [comment]
Looks like the internal flow logic has not been updated.
The simplest fix is just assert removal as this situation is handled by https://github.com/Karlson2k/libmicrohttpd/blob/9a18a4f83d707c908746474277e85e493555a759/src/microhttpd/connection.c#L1027 below.
The better fix would be the fix of the logic and I'm working on it.
Seems that nobody is using libmicrohttpd with asserts enabled and with heads requests.
The proper test will be added to MHD test-suite.

**Comment by Karlson2k** [comment]
In short: the trigger of the assert is harmless as situation is handled correctly by MHD, however it reveals the missing optimisation of the internal logic.

**Comment by fuzzard** [comment]
No worries then. Thanks for looking into it.

I'll just patch the assert out for now on our end

**Comment by fuzzard** [comment]
Thanks @Karlson2k I'll just leave as is. You're pretty good on tagging releases, so I'll no doubt do another bump in the not too distant future

**Pull request merged**
