### PR TITLE
Add userratings to seasons

### PR DESCRIPTION
**Pull request by razzeee**
Adds a new database column for userratings to the seasons table and enables json rpc to set and receive them. Should also show up fine in skins if they support it. 

There is one todo in there as I stumbled upon a comment that seems incorrect.

### CODE REVIEW

**Comment by Tolriq** [comment]
Since I forget to ask for previous PR, but what was the final decision about those ratings ?

Is 0 the absence of rating and valid rating 1..10 or is it 0..10 and then what is the value for no rating set ?

**Comment by Razzeee** [comment]
It's 1-10 and 0 is absence. At least for the json-rpc, it's stored as null in our database if you unset it.

**Comment by Razzeee** [comment]
jenkins build and merge

**Comment by KarellenX** [comment]
Hi @Razzeee 

Looking at the Wiki:Needed tags with the intent of updating wiki pages.

I can see the rating column in the seasons table of the db

I cannot see anyway to enter a season rating using Estuary and three other skins I tried.
If I manually enter the rating in the database, the rating is not displayed anywhere.
If I export to nfo files, I cannot see the season rating in any of the nfo files.

Can you explain how this is meant to work. I know, it looks simple, but I cannot see the effects anywhere.

**Comment by Razzeee** [comment]
I would need to try, but I think it works via jsonRPC. So addons only I guess?

**Pull request merged**
