### PR TITLE
[modernize] Prefer 'default' for declarations

### PR DESCRIPTION
**Pull request by hudokkow**
## Description
Prefer `= default;`over `{}` for declarations

## Motivation and Context
Modernize

## How Has This Been Tested?
Build and brief run under 17.04

### CODE REVIEW

**Comment by hudokkow** [comment]
I'll separate VP, games and input/joysticks after everything is OK and if it's accepted.

**Comment by FernetMenta** [comment]
+1 no need to separate VP. I don't expect any conflics with those changes

**Comment by hudokkow** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
One annoying thing with this clang-tidy check is that it doesn't move the default into the header file.

**Review by Paxxi — APPROVED** [review]

**Review by AlwinEsch — APPROVED** [review]

**Comment by MartijnKaijser** [comment]
@hudokkow can you rebase and merge?

**Comment by garbear** [comment]
> One annoying thing with this clang-tidy check is that it doesn't move the default into the header file.

The reason for this is that if the destructor is only defined in the header, the `delete` operator doesn't know the size of the object. This is a problem for `std::unique_ptr` because the deletion occurs in the header (`std::shared_ptr` still works).

**Comment by hudokkow** [comment]
ffs, jenkins build this please

**Comment by Paxxi** [comment]
@garbear that doesn't sound right for the general case I'm complaining about. The destructor is still generated by the compiler for the translation unit, where the =default is specified should not be relevant to this. 
I'm more thinking that clang-tidy works on the file it's given, it doesn't go find the header and make changes to it as that wasn't specified

**Comment by hudokkow** [comment]
jenkins build this please

**Comment by hudokkow** [comment]
jenkins build this please

**Comment by hudokkow** [comment]
Finally! Win64 failure unrelated.

**Pull request merged**
