### PR TITLE
[PVR] CPVRGUIActions*: Reduce usage of 'const shared_ptr<CFileItem>&' parameters.

### PR DESCRIPTION
**Pull request by ksooo**
CPVRGUIActions*: Reduce usage of `const shared_ptr<CFileItem>&` parameters. Use `const CFileItem&` instead.

Runtime-tested on macOS and Android, latest Kodi master.

@phunkyfish , @garbear best reviewed commit by commit.

### CODE REVIEW

**Comment by ksooo** [comment]
jenkins build this please

**Review by phunkyfish — COMMENTED** [review]
So why make this change? Is there a performance boost or is this just cleaner code?

**Comment by garbear** [comment]
@phunkyfish Probably a response to my comment here - https://github.com/xbmc/xbmc/pull/22001#pullrequestreview-1135370644

**Review by garbear — APPROVED** [review]
I went through commit by commit (except the clang-format ones, thanks for separating those). Looks like all replacements were done correctly. Like the improvement!

**Review by phunkyfish — APPROVED** [review]

**Comment by ksooo** [comment]
Yes, @garbear‘s in the other PR was the trigger for me for this PR.

**Pull request merged**
