### PR TITLE
[addons] fix zip install

### PR DESCRIPTION
**Pull request by tamland**
Bad refactoring in 61121d731

@mkortstiege

### CODE REVIEW

**Comment by mkortstiege** [comment]
jenkins build this please.

**Comment by mkortstiege** [comment]
build error is unrelated.

**Comment by popcornmix** [comment]
This seems to only be a partial fix. A repo that was broken is now installing. The skin @mkortstiege had trouble with is still failing. I've reverted this commit and https://github.com/xbmc/xbmc/commit/61121d731de2e0684a980e5af3c30a54cc63755a and it installs again.

**Comment by tamland** [comment]
I just realized uninstall broke as well (holy crap I must have been asleep when I wrote this!). But I'm not able to reproduce any other issues currently @popcornmix. What isn't working? And what do you mean by "A repo that was broken is now installing."?

**Pull request merged**
