### PR TITLE
Check for .nomedia file inside tv show folders

### PR DESCRIPTION
**Pull request by ThiefMaster**
https://github.com/xbmc/xbmc/pull/8586#issuecomment-186559406

### CODE REVIEW

**Comment by Razzeee** [comment]
jenkins build and merge

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by tamland** [comment]
This doesn't compile. I have reverted it in master. Please fix and resubmit

**Comment by ThiefMaster** [comment]
It did work when I wrote it...

**Pull request merged**
