### PR TITLE
[tools/depends][target] bump libbluray libudfread

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Dependency bumps. no change in core code to use the mouse events introduced in 1.2 or the change in separate keyevents in same version.
libbluray added a change to use external libudfread in 1.2.1, however it looks for the pkg-config name libudfread. Our current version of libudfread used a different pkg-config name (udfread) that was changed in libudfread 1.1.1, hence the bump of both packages in this PR

## Motivation and context
Dependency bumps.
ping @da-anda . Not sure if you want to try and revive your work for the windows depends. Maybe rope paxxi into bumping to 1.3.0 if he has time.

## How has this been tested?
Build aarch64 android, macos m1

## What is the effect on users?
N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
I remember there being some API change in the new version of libbluray but maybe it's something we should be doing rather than are required to do. I'll do some more research.

**Comment by fuzzard** [comment]
as far as i have read, its all additional API's. Absolutely we should integrate the input changes, but its not a requirement at this stage for a dependency bump

**Comment by da-anda** [comment]
I am not at all a linux guy, but wouldn't it probably make sense to dynamically build the newly added `BASE_URL` by using the `VERSION` variable, so that the version number only needs to be bumped in one place? Or are you concerned that the GIT tags might differ from the version number at some point?

as for the API changes, at least 1.2.1 only had introduced additional methods that would be "nice to use" in KODI, but not required.

**Comment by fuzzard** [comment]
BASE_URL is only used as a temporary commit until tarballs are on mirrors

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
We ok to bring this in?

**Comment by da-anda** [comment]
I have tested Windows, and it also seems to work fine with 1.3. So if you want, you could add the windows bump as well. Paxxi already built the dependencies, but somebody has to put them on our mirrors (see windows channel in Slack for the binaries)

**Comment by enen92** [comment]
I've been using both versions on Linux for a while, so +1 from me.
I can runtime test android later tonight

**Review by enen92 — APPROVED** [review]
Tested on android, all good

**Pull request merged**
