### PR TITLE
Windowing: GBM - fix guiplane selection

### PR DESCRIPTION
**Pull request by a1rwulf**
At the moment we require AR24 and XR24 as
plane formats for our gui plane.
However there are systems that support only XR24
and they can still show overlays.

We now ask for AR24 or XR24.

## Motivation and Context
Fixes not working gbm on @wsnipex i3-3225.

## How Has This Been Tested?
Tested if kodi still starts on my system.

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Cosmetic change (non-breaking change that doesn't touch code)
- [ ] None of the above (please explain below)

@lrusak @Kwiboo Can you judge if there are systems that have primary/overlay planes that support AR24/XR24 exclusively.
Like:
```
plane 31: AR24
plane 32: XR24
```
If so, we need to go a bit further.
On all my systems I have planes like:
```
plane 31: AR24 XR24
plane 32: XR24
```
So every plane that supports AR24 also supports XR24 (except cursor planes, but we don't use them).
Especially @fritsch said IMX6 needs ARGB.
@wsnipex maybe you can also runtime test this.

### CODE REVIEW

**Comment by fritsch** [comment]
IMX internally does ARGB for everything, whatever you feed into it is "somehow" done in that format.

**Comment by wsnipex** [comment]
On a related note: We shouldn't segfault when not all needed planes were found.

**Comment by notspiff** [comment]
whenever i try to have some innocent segfault fun, some party pooper always has to pop up and tell me what i'm doing is wrong :(

**Comment by a1rwulf** [comment]
@wsnipex agreed - our startup code is a little bit prone to segfaults when crucial things go wrong.
This should be addressed in a separate PR.

**Comment by a1rwulf** [comment]
@lrusak @Kwiboo thx for your explanation, I've updated to your suggestion.

**Review by lrusak — APPROVED** [review]

**Comment by wsnipex** [comment]
current version doesn't work for me:
>18:00:54.306 T:139741685298880   DEBUG: CDRMUtils::FindConnector - found connector: 72
18:00:54.306 T:139741685298880   DEBUG: CDRMUtils::OpenDrm - opened device: /dev/dri/card0 using module: i915
18:00:54.335 T:139741685298880   DEBUG: CDRMUtils::FindConnector - found connector: 72
18:00:54.335 T:139741685298880   DEBUG: CDRMUtils::FindEncoder - found encoder: 71
18:00:54.335 T:139741685298880   DEBUG: CDRMUtils::FindCrtc - found crtc: 39
18:00:54.335 T:139741685298880   DEBUG: CDRMUtils::FindPlane - found video plane 31
18:00:54.335 T:139741685298880 WARNING: CDRMUtils::FindPlane - could not find plane

**Comment by Kwiboo** [comment]
Maybe add a fallback that clears video plane when no gui plane is found and retry gui plane probe, or adding an option to control when to probe for video plane, or just add an option to control when to probe for video plane?

**Comment by a1rwulf** [comment]
@Kwiboo on the mentioned i3-3225 the found videoplane is actually an overlay plane - is this normal?

**Comment by a1rwulf** [comment]
See below for reference:
```
Planes:
id	crtc	fb	CRTC x,y	x,y	gamma size	possible crtcs
28	37	81	0,0		0,0	0       	0x00000001
  formats: C8   RG16 XR24 XB24 XR30 XB30
  props:
	7 type:
		flags: immutable enum
		enums: Overlay=0 Primary=1 Cursor=2
		value: 1
	27 IN_FORMATS:
		flags: immutable blob
		blobs:

		value:
			01000000000000000600000018000000
			02000000300000004338202052473136
			58523234584232345852333058423330
			3f000000000000000000000000000000
			01000000000000013f00000000000000
			00000000000000000000000000000000
		in_formats blob decoded:
			 C8  :  X_TILED LINEAR
			 RG16:  X_TILED LINEAR
			 XR24:  X_TILED LINEAR
			 XB24:  X_TILED LINEAR
			 XR30:  X_TILED LINEAR
			 XB30:  X_TILED LINEAR
	30 rotation:
		flags: bitmask
		values: rotate-0=0x1 rotate-180=0x4
		value: 1
31	0	0	0,0		0,0	0       	0x00000001
  formats: XB24 XR24 YUYV YVYU UYVY VYUY
  props:
	7 type:
		flags: immutable enum
		enums: Overlay=0 Primary=1 Cursor=2
		value: 0
	27 IN_FORMATS:
		flags: immutable blob
		blobs:

		value:
			01000000000000000600000018000000
			02000000300000005842323458523234
			59555956595659555559565956595559
			3f000000000000000000000000000000
			01000000000000013f00000000000000
			00000000000000000000000000000000
		in_formats blob decoded:
			 XB24:  X_TILED LINEAR
			 XR24:  X_TILED LINEAR
			 YUYV:  X_TILED LINEAR
			 YVYU:  X_TILED LINEAR
			 UYVY:  X_TILED LINEAR
			 VYUY:  X_TILED LINEAR
	33 rotation:
		flags: bitmask
		values: rotate-0=0x1 rotate-180=0x4
		value: 1
34	0	0	0,0		0,0	0       	0x00000001
  formats: AR24
  props:
	7 type:
		flags: immutable enum
		enums: Overlay=0 Primary=1 Cursor=2
		value: 2
	27 IN_FORMATS:
		flags: immutable blob
		blobs:

		value:
			01000000000000000100000018000000
			01000000200000004152323400000000
			01000000000000000000000000000000
			0000000000000000
		in_formats blob decoded:
			 AR24:  LINEAR
	36 rotation:
		flags: bitmask
		values: rotate-0=0x1 rotate-180=0x4
		value: 1
38	0	0	0,0		0,0	0       	0x00000002
  formats: C8   RG16 XR24 XB24 XR30 XB30
  props:
	7 type:
		flags: immutable enum
		enums: Overlay=0 Primary=1 Cursor=2
		value: 1
	27 IN_FORMATS:
		flags: immutable blob
		blobs:

		value:
			01000000000000000600000018000000
			02000000300000004338202052473136
			58523234584232345852333058423330
			3f000000000000000000000000000000
			01000000000000013f00000000000000
			00000000000000000000000000000000
		in_formats blob decoded:
			 C8  :  X_TILED LINEAR
			 RG16:  X_TILED LINEAR
			 XR24:  X_TILED LINEAR
			 XB24:  X_TILED LINEAR
			 XR30:  X_TILED LINEAR
			 XB30:  X_TILED LINEAR
	40 rotation:
		flags: bitmask
		values: rotate-0=0x1 rotate-180=0x4
		value: 1
41	0	0	0,0		0,0	0       	0x00000002
  formats: XB24 XR24 YUYV YVYU UYVY VYUY
  props:
	7 type:
		flags: immutable enum
		enums: Overlay=0 Primary=1 Cursor=2
		value: 0
	27 IN_FORMATS:
		flags: immutable blob
		blobs:

		value:
			01000000000000000600000018000000
			02000000300000005842323458523234
			59555956595659555559565956595559
			3f000000000000000000000000000000
			01000000000000013f00000000000000
			00000000000000000000000000000000
		in_formats blob decoded:
			 XB24:  X_TILED LINEAR
			 XR24:  X_TILED LINEAR
			 YUYV:  X_TILED LINEAR
			 YVYU:  X_TILED LINEAR
			 UYVY:  X_TILED LINEAR
			 VYUY:  X_TILED LINEAR
	43 rotation:
		flags: bitmask
		values: rotate-0=0x1 rotate-180=0x4
		value: 1
44	0	0	0,0		0,0	0       	0x00000002
  formats: AR24
  props:
	7 type:
		flags: immutable enum
		enums: Overlay=0 Primary=1 Cursor=2
		value: 2
	27 IN_FORMATS:
		flags: immutable blob
		blobs:

		value:
			01000000000000000100000018000000
			01000000200000004152323400000000
			01000000000000000000000000000000
			0000000000000000
		in_formats blob decoded:
			 AR24:  LINEAR
	46 rotation:
		flags: bitmask
		values: rotate-0=0x1 rotate-180=0x4
		value: 1
48	0	0	0,0		0,0	0       	0x00000004
  formats: C8   RG16 XR24 XB24 XR30 XB30
  props:
	7 type:
		flags: immutable enum
		enums: Overlay=0 Primary=1 Cursor=2
		value: 1
	27 IN_FORMATS:
		flags: immutable blob
		blobs:

		value:
			01000000000000000600000018000000
			02000000300000004338202052473136
			58523234584232345852333058423330
			3f000000000000000000000000000000
			01000000000000013f00000000000000
			00000000000000000000000000000000
		in_formats blob decoded:
			 C8  :  X_TILED LINEAR
			 RG16:  X_TILED LINEAR
			 XR24:  X_TILED LINEAR
			 XB24:  X_TILED LINEAR
			 XR30:  X_TILED LINEAR
			 XB30:  X_TILED LINEAR
	50 rotation:
		flags: bitmask
		values: rotate-0=0x1 rotate-180=0x4
		value: 1
51	0	0	0,0		0,0	0       	0x00000004
  formats: XB24 XR24 YUYV YVYU UYVY VYUY
  props:
	7 type:
		flags: immutable enum
		enums: Overlay=0 Primary=1 Cursor=2
		value: 0
	27 IN_FORMATS:
		flags: immutable blob
		blobs:

		value:
			01000000000000000600000018000000
			02000000300000005842323458523234
			59555956595659555559565956595559
			3f000000000000000000000000000000
			01000000000000013f00000000000000
			00000000000000000000000000000000
		in_formats blob decoded:
			 XB24:  X_TILED LINEAR
			 XR24:  X_TILED LINEAR
			 YUYV:  X_TILED LINEAR
			 YVYU:  X_TILED LINEAR
			 UYVY:  X_TILED LINEAR
			 VYUY:  X_TILED LINEAR
	53 rotation:
		flags: bitmask
		values: rotate-0=0x1 rotate-180=0x4
		value: 1
54	0	0	0,0		0,0	0       	0x00000004
  formats: AR24
  props:
	7 type:
		flags: immutable enum
		enums: Overlay=0 Primary=1 Cursor=2
		value: 2
	27 IN_FORMATS:
		flags: immutable blob
		blobs:

		value:
			01000000000000000100000018000000
			01000000200000004152323400000000
			01000000000000000000000000000000
			0000000000000000
		in_formats blob decoded:
			 AR24:  LINEAR
	56 rotation:
		flags: bitmask
		values: rotate-0=0x1 rotate-180=0x4
		value: 1
```

**Comment by lrusak** [comment]
You can remove the YUYV check, I don't need that anymore for I.MX6

**Comment by a1rwulf** [comment]
> You can remove the YUYV check, I don't need that anymore for I.MX6

Yeah that would fix it as well - it shouldn't find any video plane then.

**Comment by Rechi** [comment]
wrong revision was build
jenkins build this please

**Comment by wsnipex** [comment]
current version works for me :)

**Pull request merged**
