### PR TITLE
[PVR] Fix crash in CPVRManager::UpdateItem

### PR DESCRIPTION
**Pull request by ksooo**
Crash reported in the forum: http://forum.kodi.tv/showthread.php?tid=298461&pid=2513928#pid2513928 => http://sprunge.us/cRSg

@Jalle19 for review?

### CODE REVIEW

**Review by Jalle19 — COMMENTED** [review]
Can you have the reporter test this fix?

**Comment by ksooo** [comment]
I experienced this crash as well and I have runtime-tested the fix. It's very hard to reproduce. So I doubt the submitter is able to reproduce it.

But I have this patch applied on my private build for 3 weeks now and since than the crash did not occur any more.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by Jalle19** [comment]
@ksooo great, merge away in that case!

**Pull request merged**
