### PR TITLE
CGUIListContainer: reset scroller position too on GUI_MSG_LABEL_RESET.

### PR DESCRIPTION
**Pull request by ghost**
See:
- http://trac.kodi.tv/ticket/16406
- http://forum.kodi.tv/showthread.php?tid=258463

@Montellese (as this was broken by 25cbccd14c9969b707b8604aa4e9782031ec5baf)

**Needs backport.**

### CODE REVIEW

**Comment by Montellese** [comment]
Thanks for looking into it. I don't have time to test it myself and my understanding of this part of the code is very basic. Maybe @mkortstiege (with whom I had discussed and developped the commit causing this issue) can provide more insight?

**Comment by mkortstiege** [comment]
Change looks good to me. For some reason i always thought `SetCursor` is handling the scroller.

**Comment by Montellese** [comment]
Same here.

**Comment by Razzeee** [comment]
Might be worth looking into it, if there is a good reason it doesn't?
Else change it?

**Comment by MartijnKaijser** [comment]
ok to merge and backport (or wait with backport)?

**Comment by MilhouseVH** [comment]
This fixes trac 16406 for me - thanks @anaconda!

**Comment by ronie** [comment]
tested and works fine for me as well.

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Comment by anaconda** [comment]
Add-ons failed on win32.

**Pull request merged**
