### PR TITLE
[Estuary] Fixup Topbar consistency

### PR DESCRIPTION
**Pull request by jjd-uk**
## Description
Follow up to https://github.com/xbmc/xbmc/pull/17976 as this introduced some inconsistencies in the Topbar info.

At the time of PR17976  I did not have any clearlogos for any of my library items so this part was left untouched, I have now setup a test library with clearlogos so I've now been able align the Topbar info that is displayed whether these clearlogo's are present or not, and therefore to make the displayed info consistent across all scenarios.

**TV Shows**

Before PR with no clearlogo and no chapters

image

Compared to a TV Show which does has chapters

image

In PR17976 the text label "Episode" was introduced to match the "Chapter" label, however I forgot to add this "Episode" label for the case where there is no chapter. 

After PR changes with no clearlogo and no chapters

image

What follows are other test cases I have now used to ensure consistency.

Before PR with clearlogo and no chapters

image

After PR change with clearlogo and no chapters

image

Before PR with clearlogo and with chapters

image

After PR change with clearlogo and with chapters

image

Also tested to ensure consistency (no changes were required for any of these cases)

File item without chapters

image

File item with chapters

image

**Movies**

With no clearlogo and with chapters

image

Before PR with clearlogo  with chapters

image

After PR changes with clearlogo  with chapters

image

With no clearlogo and without chapters

image

Before PR with clearlogo  without chapters

image

After PR changes with clearlogo  with chapters

image

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by jjd-uk** [comment]
I believe I now have all scenarios covered with this PR. If anyone is able to think of any I haven't covered then please let me know.

@howie-f If you can check this as you brought to my attention one of the scenarios I hadn't covered in PR17976.

**Review by howie-f — APPROVED** [review]
shots look nice and so does my livetest. thanks a lot for cleaning 🎉

**Review by ronie — APPROVED** [review]
thanx for another improvement!

**Comment by jjd-uk** [comment]
Rebased onto Master and retested to ensure no there issues following merger of https://github.com/xbmc/xbmc/pull/18160

Confirmed everything is still as it should be.

**Review by ronie — APPROVED** [review]
looks good to me, thx!

**Pull request merged**
