### PR TITLE
[smartplaylist] add 2160p resolution filter

### PR DESCRIPTION
**Pull request by RedsGT**
Fix for https://trac.kodi.tv/ticket/17666

## Description
Fix for trac 17666. 

## Motivation and Context
https://forum.kodi.tv/showthread.php?tid=297816
https://trac.kodi.tv/ticket/17666

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by notspiff** [comment]
New buckets please. It uses buckets due to cropping, macroblock sizes etc making hings slightly deviate up/down from 720/1080 etc.

**Comment by MartijnKaijser** [comment]
@RedsGT can you adjust the PR and also change the commit message to reflect what it does and not reference a ticket

**Comment by Rechi** [comment]
@notspiff ping

**Review by notspiff — APPROVED** [review]
Thx. All good

**Comment by locki-cz** [comment]
works for movies but not for tv series ... :( can somebody fixed it?

**Comment by RedsGT** [comment]
> works for movies but not for tv series ... :( can somebody fixed it?

This issue/fix was for individual video file metadata and would have nothing to do with collection metadata like TV Show series.  If there is a detailed discussion about a similar issue either on the Kodi forum or the Kodi bugtracker let me know where it is and I will chime in there.

**Comment by HitcherUK** [comment]
@RedsGT Want to add 8K to that seeing it's sorted?

https://github.com/xbmc/xbmc/pull/14742/files

**Comment by RedsGT** [comment]
> @RedsGT Want to add 8K to that seeing it's supported?
> 
> https://github.com/xbmc/xbmc/pull/14742/files

Will add to my to do list.  Honestly, the paperwork takes longer than the fix. :D

**Pull request merged**
