### PR TITLE
[python] Add setContentLookup method

### PR DESCRIPTION
**Pull request by tamland**
Allows plugins to control whether HEAD request can be sent

### CODE REVIEW

**Comment by hudokkow** [comment]
jenkins build this please

**Comment by tamland** [comment]
@FernetMenta & @fritsch Please Ack this is what you want

**Comment by fritsch** [comment]
@tamland People told me they needed / wanted / could not live without it. Therefore I did it.

If it's technically okay with @FernetMenta - good to go in.

**Comment by FernetMenta** [comment]
looks ok to me

**Comment by fritsch** [comment]
jenkins build this please

**Comment by fritsch** [comment]
ATV issue not related.

**Comment by saqebakhter** [comment]
Can this be used with PVR addons ? if so - how ?

**Pull request merged**
