### PR TITLE
VideoPlayer: make sure first frame of a new stream is displayed witho…

### PR DESCRIPTION
**Pull request by FernetMenta**
make sure first frame of a new stream is displayed without delay
signal started when frame is picked for render

this makes continuous seek steps look smooth

### CODE REVIEW

**Comment by FernetMenta** [comment]
@popcornmix anything to adapt for omxplayer?

**Comment by popcornmix** [comment]
Simple compile fix for omxplayer:
https://github.com/popcornmix/xbmc/commit/d1c1e64f47c75529d182128427fa2ba42b803af1
Not sure we can do much better with a bypass renderer.

**Comment by FernetMenta** [comment]
thanks @popcornmix 

jenkins build this please

**Comment by stefansaraev** [comment]
fyi, this also fixed my gles render crash/deadlock we discussed few months ago in slack. thanks!

**Comment by FernetMenta** [comment]
thanks for feedback. actually I had hoped to fix this earlier by some other changes. good to hear that it is fixed finally.

**Pull request merged**
