### PR TITLE
VideoPlayer + win32: fix video stuttering

### PR DESCRIPTION
**Pull request by MartijnKaijser**
backport of https://github.com/xbmc/xbmc/pull/11301

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@FernetMenta @afedchin for check

**Comment by FernetMenta** [comment]
looks good. there was a little merge conflict with retroplayer, right?

**Comment by MartijnKaijser** [comment]
correct, just had to remove the file.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Review by afedchin — APPROVED** [review]

**Pull request merged**
