### PR TITLE
[lang/settings] Add own lists for audio, subtitle and sub download languages

### PR DESCRIPTION
**Pull request by ace20022**
@MartijnKaijser could you please check the lists?
@Montellese could you please have a look?

### CODE REVIEW

**Comment by Montellese** [comment]
The settings changes look fine. I lost the overview over all the different language codes/lists though.

**Comment by MartijnKaijser** [comment]
will check. thx

**Comment by MartijnKaijser** [comment]
@Montellese problem was that audio language list now had "closed caption" and "none" added which makes no sense. "closed caption" also doesn't work in download subtitle as it doesn't define a language. This should split it up a bit that you don't have "weird" options.

**Comment by MartijnKaijser** [comment]
listing looks ok from quick test
jenkins build this please

**Pull request merged**
