### PR TITLE
[backport][splash] handle splash as regular window

### PR DESCRIPTION
**Pull request by xhaggi**
backport of #7650 except that this use `CAspectRatio::AR_CENTER` instead of `CAspectRatio::AR_SCALE` to stay compatible with the current splash images.

@mkortstiege mind taking a look

### CODE REVIEW

**Comment by mkortstiege** [comment]
Looks good. Needs testing ofc.

**Comment by xhaggi** [comment]
Started a test-build for all platforms http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-All/889/

Builds should be on mirror with name containing *isengard-splash*

**Comment by MartijnKaijser** [comment]
i'm sure @da-anda can make a proper splash ;)

**Comment by xhaggi** [comment]
if so we could use AR_SCALE sure, but this is 100% safe for the current splash size.

**Comment by MartijnKaijser** [comment]
+1 Tested on Windows

**Comment by xhaggi** [comment]
tested on osx, no issues.

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Pull request merged**
