### PR TITLE
spelling: acquire

### PR DESCRIPTION
**Pull request by jsoref**
## Description

Fix spelling of acquire

## How Has This Been Tested?
- [x] Travis
- [x] AppVeyor

## Types of change
- [x] Spelling

## Checklist:
- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document

### CODE REVIEW

**Comment by jsoref** [comment]
Split from #11346 ; @AlwinEsch: if you want, I can fix the whitespace for this set...

**Review by Jalle19 — APPROVED** [review]

**Comment by Jalle19** [comment]
jenkins build this please

**Comment by jsoref** [comment]
@Jalle19: I can't understand jenkin's os x output; it mentions a segfault, but there are no details, and my change shouldn't trigger that...

**Comment by Jalle19** [comment]
It should be unrelated. jenkins build this please

**Comment by Jalle19** [comment]
@Paxxi do you know if this misspelling is intentional to not clash with some existing name?

**Comment by Paxxi** [comment]
These method names should match the curl names so if curl misspelled it then we should too. On phone so can't really check

**Comment by jsoref** [comment]
This doesn't appear to correlate with any curl method...

**Pull request merged**
