### PR TITLE
Fix of the lookup texture for Spline/Lanczos3 (backport)

### PR DESCRIPTION
**Pull request by sarbes**
## Description
See https://github.com/xbmc/xbmc/pull/19269.

This patch sets the right texture mapping for Spline36/Lanczos3 scaling.

## Motivation and Context
On OpenGL platforms, scaling with Spline 36 or Lanczos 3 (optimized) results in artifacts in some situations, notably scaling exactly three times (e.g. 1280x720 to 3840x2140). Because the texture mapping of the kernel is set to GL_REPEAT, a wrong weight is being sampled in the regions next to 0. and 1..

Setting the texture to GL_CLAMP_TO_EDGE solves this.

## How Has This Been Tested?
Ugly scaling before, good scaling after the patch.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by sarbes** [comment]
Ah, dang it. Gimme a sec to fix this.

**Comment by DaveTBlake** [comment]
@sarbes the backport needs to be raised using a local branch of Matrix. Here you have used the same branch in your repo as for master so all the commits to master since v19 release have come with it.

**Comment by sarbes** [comment]
Yeah, it dawned to me as the page refreshed. Sorry.

**Comment by lrusak** [comment]
Why don't you just rebase instead of opening a new PR?

**Comment by DaveTBlake** [comment]
@lrusak the PR used the wrong local branch that was beimg used by the PR against master, hence I don't see he had a choice but to close.

**Comment by howie-f** [comment]
he could have rebased on upstream/Matrix and push, wanted to write but he was too fast 🙂

**Comment by lrusak** [comment]
> he could have rebased on upstream/Matrix and push, wanted to write but he was too fast 🙂

This

**Comment by DaveTBlake** [comment]
I don't see that, look at the branch.  https://github.com/sarbes/xbmc/tree/master-scalinglookupfix could not be rebased without changing #19269 as well, and that needed to be based on master

**Comment by howie-f** [comment]
arf, didn't look at the branch name, you're right, Dave

**Pull request closed without merging**
