### PR TITLE
[confluence] add missing video codec flags

### PR DESCRIPTION
**Pull request by un1versal**
@da-anda @ronie this is isengard safe.

Klojum at IRC mentioned (yesterday) that hev1 didnt have a codec flag, someone else from my generation had mentioned also that windows media video files also dont have codec flags,
This should cure both and has been tested.

### CODE REVIEW

**Comment by da-anda** [comment]
HEV1? I only know h265 as HEVC and a quick google search also didn't give much info about HEV1. So is HEV1 correct?

**Comment by phil65** [comment]
yes, seems to exist, but I dont think we have to show that term to the user. Just using the default H265 would be nicer imo.

**Comment by uNiversaI** [comment]
Mentions hev1 https://ffmpeg.org/pipermail/ffmpeg-cvslog/2014-March/074993.html

**Comment by da-anda** [comment]
I leave it up to the codec guys if they think we have to differ between HEVC and HEV1. To me it doesn't add any value and I also believe the media flags should not go into too much details, so also using the HEVC icon whould be fine for me.

**Comment by uNiversaI** [comment]
Yes I agree, its HEVC, HEV1, HVC1 so I think the default copy is best.

**Comment by MartijnKaijser** [comment]
ok for me. objections?

**Comment by da-anda** [comment]
nope

**Pull request merged**
