### PR TITLE
Support Rockchip's RK3368 chip video hardware decoding and audio passthrough

### PR DESCRIPTION
**Pull request by vidonme-developer**

### CODE REVIEW

**Comment by vidonme-developer** [comment]
Sorry. There are conflicts. I am going to resolve them. Then pull request again.

**Comment by MartijnKaijser** [comment]
Sorry but we are in beta stage and these changes will not be accepted anymore. Also we'll not do any special casing anymore.
@koying correct me if I'm wrong

**Comment by FernetMenta** [comment]
cluttering the main branch with hw specific code in upper layers results in an unmaintainable mess. further our build system does not take care for those variants. those type of things either break or slow down development on the main branch.

**Comment by vidonme-developer** [comment]
@MartijnKaijser How long is this beta stage gonna take?

**Comment by MartijnKaijser** [comment]
About two months till release. After that libstagefright will be completely ripped out and we will only use MediaCodec on Android platform. Also take in account what @FernetMenta told that current PR is not acceptable.

**Comment by vidonme-developer** [comment]
@MartijnKaijser  Ok, we will improve our code and file pull request again after that release.

**Comment by vidonme-developer** [comment]
@FernetMenta  Thanks for your comment. And I can not very understand what you meant. Can you help me figure it out. Please!

**Comment by fritsch** [comment]
The code you add - adds an #ifdeffery all over the place - making generic code suffer cause of single hw implementations and workarounds. Making the code maintainable impossible over time.

After kodi 16 is out - a new videoplayer rewrite is merged, which changes the way that stuff works: https://github.com/FernetMenta/xbmc/commits/master - all majore platforms already have been ported.

**Comment by fritsch** [comment]
Reading through your commits: 

The code is written well. It will be easy for you to adapt to the new architecture, but the cluttering of  DVDPlayerAudio.cpp, Application needs to be changed. We don't want to have #ifdeffed code in those generic parts of the code.

Thank you very much in advance. Also thank you - that you are contributing!

**Comment by fritsch** [comment]
Reading again, you should be aware of: https://github.com/FernetMenta/xbmc/commit/e78541fbffcd6ab25e93de49481a61385eda4985

In the future kodi will only support Mediacodec

**Comment by Hedda** [comment]
@vidonme-developer and all please excuse me butting in but what they are saying above is that your company need to make an overall architecual change in your firmware to add full support for Google's MediaCodec API for Android. Meaning you should put your focus on improving your firmware use of the Google's MediaCodec API instead of only relying on using libstagefright:

http://developer.android.com/reference/android/media/MediaCodec.html

Google's MediaCodec API is the new default in the whole Android world and the use of libstagefright should be considered decrepitated and obsolete for most media player appliations. More importantly here, no libstagefright implementations will be supported at all in any future versions of Kodi, all and any support for it will be completly removed, which is why patches for adding additional libstagefright implementations will not ever be acceppted. 

This change means that you as a manufacturer should really ask Rockchip to force them provide an SDK + reference firmware with codecs and libraries which makes full use of Google's MediaCodec API for Android. You need to pressure Rockchip to improve their support of Google's MediaCodec API for all their chipsets, current and future.

**Comment by MartijnKaijser** [comment]
i mailed Rockchip last week telling them libstagefright is dead and they should move to MediaCodec. Failing to do so will get them to fall behind of the rest.

**Comment by koying** [comment]
Just my $0.02:

In the early days of the Android and Kodi story (let' say, up to Android 4.2), it made sense to implement SoC specific code, or hacks like libstagefright just because the android API's weren't not there or not mature enough. This is surely not true anymore since at least lollipop/Android TV.

This code is rk3368-only, and, unless I'm wrong, rk3368 comes with a lollipop SDK, so it doesn't make sense at all to implement this.
That RK has fallen behind in properly support Android is a pity, but Kodi will surely not take the burden of the lack of vision by incorporating this kind of workarounds anymore.

**Comment by vidonme-developer** [comment]
@fritsch and all. I got it now. Thanks you all very very much. We will continue contributing after that release.

**Comment by koying** [comment]
@vidonme-developer Unrelated, but if you're committing to open-source, the community would be very grateful if you agreed to open-source you 3D bluray code ;)

**Comment by MartijnKaijser** [comment]
I would also like to mention that releasing a special Kodi build using this code by any company is not allowed as the name is trademarked. A full rebrand would be the only way and following the GPL license.

As koying mentioned any code following the MediaCodec API and bluray playback changes would of course be welcomed. It may need some adjustments as it needs to fit our design philosophy.

**Pull request closed without merging**
