### PR TITLE
[Confluence] add close button to numeric dialog - fixes #16244

### PR DESCRIPTION
**Pull request by ronie**
fix for http://trac.kodi.tv/ticket/16244

redesign the numeric dialog in order to add a close button.
it also adds more space for the header label as well.

@phil65 @BigNoid 

before:
before
after:
after

### CODE REVIEW

**Comment by BigNoid** [comment]
Cosmetic changes look good. Could you update the navigation also to work with the new layout?

**Comment by phil65** [comment]
Close button is good and a wider header label is also good, I'm not a big fan of the new look in general though since this doesnt look like a numpad anymore. Probably a matter of taste though so go ahead.

**Comment by fernandog** [comment]
@ronie do you think someone will change the code to do nothing when 'done' is pressed and the field is empty? With rpi users dont use mouse but CEC

**Comment by ronie** [comment]
@phil65 what about this:
numpad

@BigNoid thanx for the reminder, completely forgot about that.

**Comment by phil65** [comment]
@ronie: much better. Thx!

**Comment by ronie** [comment]
updated to last design & navigation fixed.

**Pull request merged**
