### PR TITLE
add another overload for begin()/end()

### PR DESCRIPTION
**Pull request by notspiff**
msvc needs this one as well

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@Montellese ping
jenkins build this please

**Comment by Paxxi** [comment]
Are the two lines above this change actually needed? Seems like this should replace those

**Comment by Montellese** [comment]
@Paxxi: in #11003 @notspiff stated that the compiler didn't pick up on them the other way around. But I haven't tested that myself.

**Comment by Paxxi** [comment]
Oh OK. Didn't mean for notspiff to change it but mostly wondering why, no objections from me on merging.

**Comment by notspiff** [comment]
For reasons that probably makes sense if you investigate details it does
not consider const begin/end in a mutable context. Gcc considers
cbegin/cend for const context but it seems msvc does not. We could perhaps
get away without cbegin/cend but we need const and nonconst begin/end
explicitly

21. jan. 2017 22:45 skrev "Pär Björklund" <notifications@github.com>:

**Comment by Montellese** [comment]
Gave it a quick test with MSVC++ and works fine with this. jenkins build and merge

**Pull request merged**
