### PR TITLE
[dvdread] update to current next version

### PR DESCRIPTION
**Pull request by enen92**
## Description
Similar to https://github.com/xbmc/xbmc/pull/21493 this PR updates our version of dvdread and drops a few headers that are no longer needed.
The headers still have a few patches when compared to upstream but that affects mostly windows (aka not really a problem as we will always bundle the dlls anyway).

### CODE REVIEW

**Comment by enen92** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by enen92** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by enen92** [comment]
Tested with https://github.com/xbmc/xbmc/pull/21529 on linux, windows and android. isos, optical discs and dvd backups (folder structures on disc) work just like before. Going ahead and merging this.

**Pull request merged**
