### PR TITLE
[depends] libass 0.13.4

### PR DESCRIPTION
**Pull request by MartijnKaijser**

### CODE REVIEW

**Comment by FernetMenta** [comment]
this needs testing with a selection of samples including anime

**Comment by MartijnKaijser** [comment]
paxxi told me we already use this version on Windows in v17. I do have some anime but not sure if they have ASS subtitles. I think i only have one

**Comment by Paxxi** [comment]
This won't suffer from the issues seen on windows as that is using a new backend. With that said there is a good sample on the ftp that taxigps provided for testing the windows version

**Comment by FernetMenta** [comment]
There's also some testfiles on our ftp server: /samples/SSA-test

**Comment by MartijnKaijser** [comment]
Pulling the entire folder now :)

**Comment by FernetMenta** [comment]
you'd better get you beer before watching those :)

**Comment by MartijnKaijser** [comment]
I've seen worse things :)
All works, jenkins build this please

**Pull request merged**
