### PR TITLE
[Windows] 3dlut support + dithering

### PR DESCRIPTION
**Pull request by afedchin**
see title.

### CODE REVIEW

**Comment by afedchin** [comment]
jenkins build this please

**Comment by afedchin** [comment]
@laurimyllari please review changes in `ColorManager`.

**Comment by afedchin** [comment]
jenkins build this please

**Comment by afedchin** [comment]
jenkins build this please

**Comment by afedchin** [comment]
jenkins build this please

**Comment by Rechi** [comment]
@afedchin this needs a rebase and add lcms2 also to x64 dependencies

**Comment by afedchin** [comment]
yes, I know, this is obsolete to be honest

**Comment by AchimTuran** [comment]
@afedchin
Thank you for the initial work. 
With obsolete you meant the entire implementation​ or only lcms2?
Deinterlacing and 3dLUT files are nice features for Windows. Can't wait to use them.

**Comment by afedchin** [comment]
I meant this PR is obsolete. I'll prepare a new one then vpupdates will go in.

**Pull request closed without merging**
