### PR TITLE
[cmake] add defines for alsa and pulseaudio

### PR DESCRIPTION
**Pull request by lrusak**
~~HAS_ALSA and HAS_PULSEAUDIO are always undefined without this.~~

~~I'm not sure if this is the best solution but it is one.~~

I found a better solution

### CODE REVIEW

**Comment by lrusak** [comment]
jenkins build this please

**Review by FernetMenta — APPROVED** [review]
great, some day we should kill crappy system.h completely

**Comment by fritsch** [comment]
Wayland and Win32 failure is not related. I will push that as it fixes issues spreading on the forum.

@Rechi you analyzed the "float" issue yesterday - what was the outcome?

**Comment by Rechi** [comment]
> Rechi you analyzed the "float" issue yesterday - what was the outcome?

No I didn't, as I can't reproduce it.

**Comment by notspiff** [comment]
I am fairly certain my pr fixes it. When one thread stomps the stack of
another all sorts of fun happens

13. des. 2017 10:07 skrev "Rechi" <notifications@github.com>:

**Pull request merged**
