### PR TITLE
[Artwork] Update Nexus Alpha splashscreen

### PR DESCRIPTION
**Pull request by enen92**
## Description
This updates our Nexus splashscreen with fresh goodness provided by our artwork god @samfishermike :)

## Motivation and context
Nexus name was chosen and artwork is now available

## How has this been tested?
Compile and check

## What is the effect on users?
They'll gonna be delighted :)

users

## Screenshots (if appropriate):

Nexus is around the corner

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Review by lrusak — APPROVED** [review]

**Comment by lrusak** [comment]
Looks great!

**Comment by da-anda** [comment]
really nice 👍 , but over 500kB for the splash seems a little excessive to me. Would you mind adding at least a little compression to get it down to maybe half the size? I did a quick test locally and it should still look good, even the fine details. Compressed version should get created from the source, to avoid intensifying artifacts, so likely would have to be done by @samfishermike

**Review by da-anda — APPROVED** [review]

**Comment by da-anda** [comment]
thanks for shrinking the file and saving the environment ;) (200 kB * millions of downloads = lots of saved bandwidth and electricity, so good for the planet, isn't it :) )

**Comment by enen92** [comment]
yes

**Review by howie-f — APPROVED** [review]
very cute ♥️

**Comment by enen92** [comment]
jenkins build and merge

**Pull request merged**
