### PR TITLE
[Cmake] Move effects11 library to external library usage

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Remove code that is not team kodi code, and use as any other lib

## Motivation and context
Remove code that isnt ours from tree. Source lib from upstream and treat as any other external lib

## How has this been tested?
Build win x64

## What is the effect on users?
N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by garbear — APPROVED** [review]
Straightforward and removes 20K SLOC. What's not to love?

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
Linux failure unrelated (05:39:48 [  FAILED  ] TestHTTPDirectory.IsStarted)

**Pull request merged**
