### PR TITLE
FIXUP: fix python PIL after #5218

### PR DESCRIPTION
**Pull request by koying**
@Memphiz Could you confirm this solves the OSX issue, please.

### CODE REVIEW

**Comment by Memphiz** [comment]
thx looks good :)

**Comment by koying** [comment]
If possible, I'd prefer that you actually give it a shot, to be sure ;)

**Comment by Memphiz** [comment]
Ahh codewise i mean - can't confirm until wednesday next week - but i did test this same thing yesterday so i am pretty sure it solves it.

**Comment by Memphiz** [comment]
@mkortstiege if you have time before next week - without this patch the openweathermap addons should fail on osx (doesn't findmodule pil). With this patch and after doing "make -C tools/depends/target/pythonmodule-pil/ distclean && make -C tools/depends/target/pythonmodule-pil/" and another compile the addon should work again...

**Comment by mkortstiege** [comment]
Sure. Will check later today and report back.

**Comment by mkortstiege** [comment]
@Memphiz i am not sure how to reproduce the issue with todays master. OpenWeatherMap works fine here. All Forecast data and the map images are loaded. Is there anything special i need to do?

**Comment by mkortstiege** [comment]
Will clean and test again.

**Comment by Memphiz** [comment]
you need to clean the right files in /User/Shared/blah - wtf - i know this is correct - koying please pr against helix aswell

jenkins build and merge

**Comment by koying** [comment]
Ok, np.
If you are OK with it, I'll just merge.

**Comment by koying** [comment]
BTW, (when back from skiing), we might "sit together" on how to get pil out
of the building tree into a   proper binary addon.

**Comment by MartijnKaijser** [comment]
better move to the replacement of PIL which is compatible an still maintained

**Pull request merged**
