### PR TITLE
enable online scraping for music by default

### PR DESCRIPTION
**Pull request by ronie**
no idea why we shouldn't really.

from a skinners pov, it's not possible to create a nice view for artists / albums
if we don't have any additional info to show.

### CODE REVIEW

**Comment by DaveTBlake** [comment]
I see your point, but not convinced this is a good idea.

For scraping to be really effective we are dependant on having MBIDs, or at least well tagged music files. First we need to get users to tag their data and use the library. Scraping onto messey tags makes an even bigger mess,. Well tagged music files will also contain cover art, so you will have something pretty to display for albums at least before scraping.

The other reason is speed. Add a large music source for the first time, remember to scan it to library which is slow enough, and then wonder what on earth Kodi is doing while it scrapes additional info off the net.

Eventually we need to streamline this process, but I don't think just changing this setting, with everything else as it is, is the way to go. It is not as trivial a change as you may at first have thought.

**Comment by zag2me** [comment]
Nice improvement in my opinion. This may finally convince people to move away from their beloved file mode ;)

I would say we should be promoting this as we are an HTPC app at the end of the day, and Artwork and Metadata should always be encouraged!

I've moved TADB to cloudflare now so hopefully we the metadata sites can handle the traffic! Only one way to find out... :)

**Comment by Razzeee** [comment]
So has anyone checked what exactly happens if there is no Internet access?

**Comment by ronie** [comment]
it will scrape metadata from the tags only.

**Comment by Tolriq** [comment]
I guess all the very long previous discussions are already forgotten.

Information should really be maintained and condensed so that everyone have access to it.

Scrapers by default overwrite data from users, if most users do not activate library mode it's by choice not because they did not find the option.
I know my bla bla from users feedback have no weight but this + https://github.com/xbmc/xbmc/pull/8395 in Jarvis will generate a high level of problems and support with current music handling.

At least I've done my part by warning multiple times.

**Comment by Razzeee** [comment]
Yes, we're very aware of what we're doing here. And that's in parts due to you, thank you for that!

But moving things along and improving things is not a bad thing. We're trying to improve the handling for the average joes, we're trying to deliver the best possible out of the box settings. Every power user will know, that he needs to turn that setting of, if he really wants his own tags only.
We just need to mention that in our blogs so @MartijnKaijser might keep that in mind, if this goes in.

**Comment by Tolriq** [comment]
The problem is not about improving ;) We all want that.

The problem is the impact on average Joe that do not understand things, and certainly does not read a Changelog ;)

To improve for Jarvis a non intrusive way as discussed a lot would be : Scan content like your PR that would only scan tags in library. This is OK since it's user job to have correct tags.

But default direct online scanning with a default scraper (in English so not good for many) that will override data from users without he knowing and having control about what is overridden that is not the way to go after.

For Jarvis it should be as proposed by some of the other Team member a popup scrape with online data ? Yes / No and with a warning text saying that it can override some of the user TAGS.

This would at least reduce a lot support as the warning will be visible before the guy click ok and not hidden in a 150 line changelog on a web page.

**Comment by da-anda** [comment]
I don't seen an issue with this, besides of probably speed concerns. The setting to override tags is not enabled by default ("prefer onlne information") - so scraping by default should only fill missing meta-data, right? I understand the concern by @Tolriq, but from what I see it doesn't apply here.

**Comment by DaveTBlake** [comment]
Although scraping by default _should_ only fill in missing data I'm afraid there are bugs which means it sometimes overwrites artists obtained from tag data etc. This is more likely if the files are not consistently tagged.

In the longer term we want this all to be better, fix those bugs, make scraper configuration accessible at the point of adding a source, do the scrape in background etc. But right now we are not there. So I think we should wait until we have those things sorted before we make scraping the default.

Not happy that we have locked this, and not sure why.

**Comment by MartijnKaijser** [comment]
I have to agree with @DaveTBlake that having this enabled by default is not something our tag reading and scraping is not ready for yet. Once we have a release iteration where we at least ask user for scanning in the music to library using the way they have tagged and receiving feedback on it gives a clearer view.
Speed is certainly a big problem as scanning my library would take several days having this enabled by default compared to maybe some hours. During the online content scraping i can't start using my library at all.

**Comment by zag2me** [comment]
Yep guess this one can be put down as "nice to have" but not quite ready yet.

**Comment by DaveTBlake** [comment]
I must repeat that until Kodi handles all the kinds of tagging mistakes users commonly makes, automatically scraping just leads to even more library chaos and user dissatisfaction.  For an example of common user problems read http://forum.kodi.tv/showthread.php?tid=262708

I know we want it all invisible and automatic in the long run, but can we delay this until we are confident that  Kodi is more robust and flexible with respect to tags. I am working on it, but IMO just turning on scraping by default now is premature and will not help,

**Comment by MartijnKaijser** [comment]
@DaveTBlake is working on fixing it properly and python scrapers will help a lot as well. Closing this for now

**Pull request closed without merging**
