### PR TITLE
[addons] Switch to Nexus repository

### PR DESCRIPTION
**Pull request by ronie**
## Description

I've created an addon repository for Kodi Nexus (https://mirrors.kodi.tv/addons/nexus/) 
and i'm now setting up Nexus branches on our github repos: 
- [x]  repo-plugins
- [X]  repo-resources
- [X]  repo-scrapers
- [x]  repo-scripts
- [X]  repo-skins
- [X]  repo-webinterfaces

once that's completed, this PR can be merged

- [X]  wiki updated:
https://kodi.wiki/view/Submitting_Add-ons

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [X] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ronie** [comment]
@enen92 / @basrieter i've created a nexus branch in repo-scripts / repo-plugins
please check if any additional setup is needed for the workflows / dashboard you're using.

**Comment by enen92** [comment]
Thanks ronie for taking the time to do it. The only thing we need in the new branches is the .github folder with the addon-checker.yml action definition. The one in matrix can be used for the nexus branch as it grabs the branch name from the event

**Comment by ronie** [comment]
thanx, looks like i did it correctly then.

**Comment by matthuisman** [comment]
Any changes needed for binary add-ons? 
Eg. Inputstream adaptive?

**Comment by fuzzard** [comment]
Binary addons arent related to these changes.

precursor commit for them was done by @AlwinEsch a month ago - https://github.com/xbmc/xbmc/commit/f40bee71142c91c8f53b5eb06fc39d5591ff64fa
Essentially just a copy of matrix setup was moved to nexus repo. Nexus branches will need to be created on each addon, and then the repo needs to be updated - ie https://github.com/xbmc/repo-binary-addons/blob/Nexus/inputstream.adaptive/inputstream.adaptive.txt change matrix to nexus

Its a long process due to the sheer number, so no timeline right now.

**Pull request merged**
