### PR TITLE
[cmake] fix FindWaylandpp

### PR DESCRIPTION
**Pull request by wsnipex**
fix the issue raised in https://forum.kodi.tv/showthread.php?tid=331005

## Description

Properly check for each libs and normalize to full path for all libraries.

## How Has This Been Tested?

compiled on ubuntu 18.04

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by pkerling** [comment]
Why do we want to work around pkg-config?

**Comment by wsnipex** [comment]
because otherwise we get those spurious issues. We never want to pollute our linker flags with random include paths, which can lead to all kinds of random problems.
This module never was implemented according our standards, which is:
1. never rely on pkg-config alone
2. always use full path for linked libs

**Comment by pkerling** [comment]
> because otherwise we get those spurious issues.

The issue was that a LFS user had a broken system. I'm sure people with broken systems will also find ways to break it when using `find_library` ;-)

> This module never was implemented according our standards

For the record, I brought this up in Slack back then and there was no strong opposition to letting pkg-config do its job. You won't be able to meaningfully build without having pkg-config anyway (on the platforms this touches), so requiring it is not a problem. When using `find_library`, we lose all link flags that are not `-l`.

Anyway, I'd suggest at least keeping pkg-config required here. I can't see a reason to completely sidestep it and search for waylandpp libs on our own. That only encourages having broken systems and will cause more issues.

**Comment by wsnipex** [comment]
what you call a "broken system" on the user side was a totally valid .pc file. There was nothing broken.
The same problem would happend with any other -L path that holds random libs.
If there are any issues with missing -l libs, I'll fix it.

We still use pkg-config, we just don't trust it blindly.

**Review by Rechi — APPROVED** [review]

**Comment by pkerling** [comment]
> what you call a "broken system" on the user side was a totally valid .pc file.

The .pc file viewed in isolation is valid, of course. But the system is still broken. The user meant to install waylandpp to a system standard linker directory but did not do so (I'm not sure whether gcc would search by default in `/usr/lib64` in the case of that specific system, but I'm guessing it would).

> We still use pkg-config, we just don't trust it blindly.

If I'm not mistaken, this will now continue to search for the libraries and such by name even when the pkg-config packages are not found. That's not using pkg-config.

**Pull request merged**
