### PR TITLE
[CURL] Dont log url in ParseAndCorrectUrl

### PR DESCRIPTION
**Pull request by matthuisman**
## Description

20s of playback = 2MB of file size

It also logs the headers as part of the url (url|headers) - so shows the authorization header. oops
Log attached showing the issue

The url gets logged straight after the headers - so I don't think we need it logged every header being added.
[kodi.log](https://github.com/xbmc/xbmc/files/9692153/kodi.log)
(i replaced the real bearer token with a random string of same length)

The extra logging was brought in on this commit:
https://github.com/xbmc/xbmc/commit/ef3159dab43aa3a5bfedf5ecc4b517d4025f79b1

## Motivation and context

Reduce log size

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by glennguy** [comment]
+1 from me. I usually have word wrapping on when scrolling through logs and it's unreadable with long urls with heaps of params. It's pretty obvious which headers belong to which request without printing the url on each line.

**Comment by lrusak** [comment]
Multiple curl calls can happen at a time so maybe it makes sense to have a unique identifier (the url) with the logging call. 

Would it be better to either:
 - use a different unique identifier
 - shorten the url to just the domain name
 - add the logging call to curl component logging so that it is disabled normally

**Comment by matthuisman** [comment]
Component level would be ok IMO.

**Comment by fuzzard** [comment]
You can look at the following for an example how to log to a component log

https://github.com/xbmc/xbmc/blob/9f699af44bde1b8b3448c3d4162fbb089974d38e/xbmc/pvr/PVRCachedImages.cpp#L31

Essentially find the component you want at 

https://github.com/xbmc/xbmc/blob/973c5a584c3696a5e61e399325540cd7abecdc56/xbmc/commons/ilog.h#L29-L46

And the second argument is that componenet (eg LOGCURL)

LogFC is just a macro to call LogFunction

https://github.com/xbmc/xbmc/blob/973c5a584c3696a5e61e399325540cd7abecdc56/xbmc/utils/log.h#L144-L145

Just means it will put in the Function name in the log line, and you dont have to manually do the whole "CCurlFile::{}" __FUNCTION__ stuff.

just do as an example.

```
      CLog::LogFC(LOGDEBUG, LOGCURL, "Using proxy {}, type {}", m_proxyhost,
                proxyType2CUrlProxyType[m_proxytype]);
```

**Comment by matthuisman** [comment]
perfect. thank you :) ill get the PR updated.

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by matthuisman** [comment]
are you happy with approach?
Seems a bit "off" to me having some logging in this file going to component and some to debug.
Also, if the user enables curl component then they may well get the "log spam" still?

what would you think about changing CURL::GetWithoutUserDetails to not include the | headers?
https://github.com/xbmc/xbmc/blob/68bf07ee4fab9f844a9bef3ddeeb443be45d9453/xbmc/URL.cpp#L550

**Comment by fuzzard** [comment]
I'll ping @arnova for that. I dont know the context around the logging

**Comment by arnova** [comment]
> are you happy with approach? Seems a bit "off" to me having some logging in this file going to component and some to debug. Also, if the user enables curl component then they may well get the "log spam" still?
> 
> what would you think about changing CURL::GetWithoutUserDetails to not include the | headers?
> 
> https://github.com/xbmc/xbmc/blob/68bf07ee4fab9f844a9bef3ddeeb443be45d9453/xbmc/URL.cpp#L550

Well in principle we also want stuff to end up as debug-logging but IMO the component logging is for all the extra stuff, especially if it has the potential of generating log spam (like can happen with eg. PVR). So splitting it up sounds good to me, but we shouldn't make everything in there Curl-component-logged. 

Could you perhaps elaborate how not logging the headers is an improvement? Isn't that exactly what you also want to see/know when debugging issues? Maybe I'm just misunderstanding you or I'm not seeing the big picture?

**Comment by arnova** [comment]
> Multiple curl calls can happen at a time so maybe it makes sense to have a unique identifier (the url) with the logging call.
> 
> Would it be better to either:
> 
> * use a different unique identifier
> * shorten the url to just the domain name
> * add the logging call to curl component logging so that it is disabled normally

**Comment by matthuisman** [comment]
thanks for the feedback :) 
I'm happy for this to stay as-is then as it's better than currently :)

**Review by wsnipex — APPROVED** [review]

**Review by arnova — APPROVED** [review]

**Pull request merged**
