### PR TITLE
[xbmc][guilib] Rewrite kaitoast to behave like a regular dialog

### PR DESCRIPTION
**Pull request by Paxxi**
This should allow proper animation of the toast window and should hopefully fix the issues described in http://forum.kodi.tv/showthread.php?tid=237110&pid=2097274#pid2097274 . I've tested this a bit and it seems to work fine, more testing will be needed.

### CODE REVIEW

**Comment by Razzeee** [comment]
Just a quick question out of curiosity, what does "Kai" stand for?

**Comment by Paxxi** [comment]
I don't really know but I think it dates back to the xbox days and some software named xlink kai. I may be entirely wrong about this though :)

**Comment by phil65** [comment]
you are completely correct. It is a relict from xbox days.

**Comment by Paxxi** [comment]
@phil65 This is quick and dirty now and need input from skinners
here's a video showing it in action for the kai toast
https://www.youtube.com/watch?v=q4TzWijPEzs

**Comment by Hedda** [comment]
XBMC previously had a XLink Kai front-end integrated to control that a XLink Kai client (Xbox Live online-gaming alternative), but the actual XLink Kai client has been removed, the pop-up dialogs originally made for "Kai" notification remains for other notifications in Kodi.  

https://en.wikipedia.org/wiki/XLink_Kai

There used to be a more extended player lobby front-end GUI for gamers in XBMC, which via XLink Kai handled your gaming community and friends connections, including online chat and such, similar to example Xbox Live.

http://kodi.tv/xbmc-and-xlink-kai-updated/

Off-topic; might be interesting to put a front-end GUI like that back into Kodi for RetroPlayer, similar in concept as Ignition, the social retro gaming OS by Alex Stubbs, which will also have XBMC/Kodi integration:

https://www.kickstarter.com/projects/1717505434/ignition-a-social-retro-gaming-os-for-the-raspberr/description

**Comment by Paxxi** [comment]
I've thought more about this and I'm not sure it's a good idea, closing PR.

**Pull request closed without merging**
