### PR TITLE
[gui] remove 'get more' node from vfs

### PR DESCRIPTION
**Pull request by tamland**
Allows addons://sources/ paths to be properly used in content lists. 

Needs confluence adjustments if we still want this shortcut from the media windows.

cc @phil65

### CODE REVIEW

**Comment by HitcherUK** [comment]
@tamland Skin changes PR -

https://github.com/xbmc/xbmc/pull/8719

**Comment by tamland** [comment]
jenkins build this please

**Comment by Razzeee** [comment]
Only the addon pvr.hdhomerun failed on windows, the builds were fine.

**Comment by Rechi** [comment]
If I want to go to addon in a category where no addons are installed I get only the main directory of this category displayed and so cannot install an addon.

**Comment by ronie** [comment]
hmm yeah, all the addon nodes are now hidden if they're empty.

the only exception is video addons, but i get the annoying 'couldn't connect to network server' when i try to enter it.

**Comment by tamland** [comment]
See #8850

**Pull request merged**
