### PR TITLE
[gui] remove eventual context menu items for the "go to parent" item

### PR DESCRIPTION
**Pull request by Jalle19**
Fixes  #15732

@xhaggi should be pretty straight-forward

### CODE REVIEW

**Comment by notspiff** [comment]
This pops up all over. Can you investigate if it can be solved on the mediawindow level ? (on phone so bit hard for me..)

**Comment by xhaggi** [comment]
+1 for what @notspiff said

**Comment by opdenkamp** [comment]
ditto. but not worth backporting as it's not fixing a crash or anything like it

**Comment by Jalle19** [comment]
@opdenkamp according to the bug report you can accidentally delete all your recordings if you "delete" the "go to parent" item. I haven't dared try.

**Comment by Jalle19** [comment]
@notspiff in this particular case it can be fixed in `CGUIMediaWindow`, but not all derived classes call the base implementation last (some call it first, some never call it) so it can't be relied on in all cases. I'll update the PR and change the title.

**Comment by opdenkamp** [comment]
@Jalle19 ok fine in that case

**Comment by Jalle19** [comment]
I still think we should backport this, there's no harm in doing it.

**Comment by opdenkamp** [comment]
If it's actually deleting all recordings, sure. If not, then it's 
something for the next release. We can't keep backporting every fix in 
the tree.

**Comment by Jalle19** [comment]
@opdenkamp like I said I haven't tried, I don't want to accidentally lose all my recordings. Anyway, it's not like backporting is a big deal, it's me who'd do it anyway.

**Comment by Jalle19** [comment]
@notspiff I had to push another fix, apparently the item could still be deleted when pressing the delete button. If anyone knows of a smarter way to fix this let me know.

**Comment by notspiff** [comment]
Since that is processed where it is.. an alternative would be to check inside the function.

**Comment by opdenkamp** [comment]
it's not about who does it, it's about only fixing what really needs to 
be fixed in a stable release. backporting nice-to-have commits risks 
introducing new bugs and should always wait until the next stable.

**Comment by Jalle19** [comment]
@notspiff moved the check
@opdenkamp fine

jenkins build this please

**Comment by Jalle19** [comment]
@opdenkamp your button

**Comment by Jalle19** [comment]
@xhaggi took care of your comments

jenkins build this please

**Comment by opdenkamp** [comment]
no longer making 0 sense? ;-)

**Comment by Jalle19** [comment]
@opdenkamp it still doesn't, but you shouldn't add comments about obvious things ;-)

**Comment by Jalle19** [comment]
@opdenkamp is this good to go?

**Comment by opdenkamp** [comment]
+1, jenkins build and merge

**Comment by Jalle19** [comment]
Apparently we forgot to backport this, someone recently almost nuked his recording library (http://trac.kodi.tv/ticket/15908#comment:1).

**Comment by xhaggi** [comment]
too late

**Pull request merged**
