### PR TITLE
Fix testsuite after rating changes

### PR DESCRIPTION
**Pull request by phate89**
I took the @hudokkow commit and finish the fixed related to my rating changes.
There is still a failed test (TestCharsetConverter.wToUTF8) and a crash (in CriticalSection.h) that are not related to my changes  and I don't know how to fix

### CODE REVIEW

**Comment by Razzeee** [comment]
TestCharsetConverter.wToUTF8 on windows is around for a long time. I think nobody knows how to properly fix it :(

**Comment by Razzeee** [comment]
Hrm, no clue why that CriticalSection crash is there (I also get it)
Maybe @FernetMenta knows something as he was doing stuff with locks lately?

**Comment by FernetMenta** [comment]
would you have a bt for the crash?

**Comment by Razzeee** [comment]
Doesn't seem to create a crashlog, heres what's in the call stack in visual studio.

http://pastebin.com/yxPrvMdY

**Comment by Razzeee** [comment]
The critical section thing is out of scope for this PR.
I've tried the testsuite with build 4f9bb7757eaae21ec02fdcceb6566cd7129c6b27 and it's also happening there. Not sure when it was introduced.

**Comment by Razzeee** [comment]
jenkins build and merge

**Comment by hudokkow** [comment]
Thanks for taking care of it! :+1:

**Pull request merged**
