### PR TITLE
[Estuary] Make weather-condition label scrollable

### PR DESCRIPTION
**Pull request by DaVukovic**
## Description

If the label for the weather condition is too long it will be truncated in some languages. 
See: #19089 

## Motivation and Context

Weather label could be make visible completely although it will scroll only 3 times and then only after the skin has been reloaded. At least it won't destroy the rest of the layout given in this section.

## How Has This Been Tested?

Tested on Kodi 19 master.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by basilgello** [comment]
I dared to go ahead & managed to achieve this:

IMG_20210121_100644

with the following patch:

```diff
diff --git a/addons/skin.estuary/xml/Home.xml b/addons/skin.estuary/xml/Home.xml
index 36b3e34524..9a9f0093bd 100644
--- a/addons/skin.estuary/xml/Home.xml
+++ b/addons/skin.estuary/xml/Home.xml
@@ -593,7 +593,7 @@
                                                        <left>68</left>
                                                        <right>70</right>
                                                        <top>102</top>
-                                                       <height>300</height>
+                                                       <height>360</height>
                                                        <visible>!String.IsEmpty(Weather.plugin)</visible>
                                                        <control type="image">
                                                                <bottom>90</bottom>
@@ -618,10 +618,20 @@
                                                                <right>60</right>
                                                                <align>right</align>
                                                                <font>font14</font>
-                                                               <label>$INFO[Weather.Conditions,, ∙ ]$INFO[Weather.Temperature]</label>
+                                                               <label>$INFO[Weather.Conditions]</label>
+                                                       </control>
+                                                       <control type="label">
+                                                               <left>840</left>
+                                                               <top>180</top>
+                                                               <aligny>center</aligny>
+                                                               <height>24</height>
+                                                               <right>60</right>
+                                                               <align>right</align>
+                                                               <font>font14</font>
+                                                               <label>$INFO[Weather.Temperature]</label>
                                                        </control>
                                                        <control type="grouplist">
-                                                               <top>50</top>
+                                                               <top>80</top>
                                                                <left>50</left>
                                                                <right>20</right>
                                                                <orientation>horizontal</orientation>
@@ -1067,6 +1077,14 @@
                                                <param name="visible" value="Player.HasMedia" />
                                        </include>
                                </control>
+                               <control type="image">
+                                 <left>140</left>
+                                 <top>71</top>
+                                 <width>250</width>
+                                 <height>56</height>
+                                 <aspectratio>keep</aspectratio>
+                                 <texture>from-debian-logo.png</texture>
+                               </control>
                        </control>
                        <include>BottomBar</include>
                        <control type="group">
```

**Comment by basilgello** [comment]
@ronie @DaVukovic what do you think of my suggestion? How cool (or not cool) is it UX-wise? Should I also make spaces before and after `Forecast` and `Hourly` labels (`Прогноз` and `Щогодини` on my screenshot, respectively) slightly smaller?

**Comment by basilgello** [comment]
As for scrollable label, my family considers it useless with the following reason: "We usually turn Kodi on and wait until PVR updates not sitting and staring on the screen. The weather scrolls three times and then gets back to previous state by the time we enter the living room to check it".

**Comment by ksooo** [comment]
TBH, I do not really like the approach. To much space waisted left too the location/condition/temperature area.

I would go with a completely different approach and make the long string causing the Grobler here that short that it fits the current design.

**Comment by basilgello** [comment]
> TBH, I do not really like the approach. To much space waisted left to the location/condition/temperature area. And all this just for a real the case.
> 
> I would go with a completely different approach and make the long string causing the trouble here that short that it fits the current design.

Makes sense but this requires considerable amount of localization genii... Some words like `Breezy` are expressed in the long manner in some languages. Can not we just add a pictogram showing weather conditions? It has not to be detailed - it has to be contrast and fit a single 'cell' to exactly show the condition just like precipitation, sunset and other stuff.

**Comment by DaVukovic** [comment]
TBH, I don't care too much if it's 2 lines, 3 lines, pictograms or a changed wording. 

I simply saw that issue which I presented a fix for. A scrolling text doesn't harm anyone and won't even destroy the given layout (2 to 3 lines). 

Changing the stuff to "climacons" means there's way more work needed on the skin and way more files to ship. I'm not against that, but I won't do it. Also probably think of an explanation of what each icons stands for. 

Im regard of changing the text. My native language is not Ukraine. So I can't do anything in that regard. `Mostly cloudy` would probably be "Überwiegend wolkig" in german which wouldn't fit as well, I guess. Anyway...I guess we can't do it correct for everyone or any wording in every available language. 

@ronie not sure what might be best to present first. I'm mostly interested in the temperature but I like the layout that the temperature comes last. So as long as it's visible I'm fine. Presenting the temperature first would ensure that it's always visible but would destroy the layout. So if you, as our skin-expert, think it would be better to mention the temperature first, then I'll change that. No pobs.

**Comment by ronie** [comment]
looking at the possible conditions (https://developer.yahoo.com/weather/documentation.html#codes) some are too long to fit the current label, even in english. so i'm not opposed to a 3-line approach.

@basilgello your code changes look ok to me, apart from the debian logo ofc ;-)

**Comment by DaVukovic** [comment]
If we decide for a 3-lines approach, then @basilgello please feel free to create a PR and I will close this one.

**Comment by ksooo** [comment]
I'm not a designer, but honestly, the 3 lines approach looks rather ugly to me. Pretty crouded on the right, much empty space elsewhere.

**Comment by basilgello** [comment]
> @basilgello your code changes look ok to me, apart from the debian logo ofc ;-)

Yeah, it was just a snippet from my live system I experimented with :) Will adapt it properly.

> I'm not a designer, but honestly, the 3 lines approach looks rather ugly to me. Pretty crouded on the right, much empty space elsewhere.

I can try slightly different approach for 19.0 bugfix:

++++++++++++++++++++++++++++++++++++++++++
+ |       Kharkiv             |       Mostly cloudy          |  18C +
+   Iconbox 1  |  Iconbox 2  |  Iconbox 3  |  Iconbox 4 +
++++++++++++++++++++++++++++++++++++++++++

The "+" and "|" signs show virtual borders. The labels get centered and form one line fitting the whole box width, but it is not one label but 3 different ones.

**Comment by ksooo** [comment]
If we really want to go with the 3-lines solution, please at least reduce the space between the lines.

**Comment by ksooo** [comment]
I would try to align the top of the weather icons on the left with the top of the first line, and the bottom of the text below the icons aligned with the bottom of the third line.

**Comment by howie-f** [comment]
how about displaying temp. beside the city and stick with 2 lines... would it fit then?

**Comment by ksooo** [comment]
> how about displaying temp. beside the city and stick with 2 lines... would it fit then?

 We never can do it right. There are always chances that the location wont fit. I for myself do live in "Llanfairpwllgwyngyllgogerychwyrndrobwllllanty". Just kidding, but the problem is real.

**Comment by DaVukovic** [comment]
Would probably require another group as the font for the city is different compared to the line below and showing the temperature in such a bold text looks ugly as well

**Comment by ksooo** [comment]
http://www.bbc.com/travel/story/20120320-worldwide-weird-the-uks-longest-named-village

**Comment by basilgello** [comment]
> I'm not a designer, but honestly, the 3 lines approach looks rather ugly to me. Pretty crouded on the right, much empty space elsewhere.

Trying to craft Markdown-based mockup for my idea :)

**Comment by ksooo** [comment]
@basilgello I would try to align the top of the weather icons on the left with the top of the first line, and the bottom of the text below the icons aligned with the bottom of the third line.

**Comment by basilgello** [comment]
> @basilgello I would try to align the top of the weather icons on the left with the top of the first line, and the bottom of the text below the icons aligned with the bottom of the third line.

I can do that, I hope.

**Comment by DaVukovic** [comment]
@basilgello so you are going to open your own PR?

**Comment by basilgello** [comment]
> @basilgello so you are going to open your own PR?

Yes. Let me prepare it shortly!

**Pull request closed without merging**
