### PR TITLE
[addons] don't use event load/unload in conjunction with async events

### PR DESCRIPTION
**Pull request by xhaggi**
Follow-up after #12843 

@tamland ping

### CODE REVIEW

**Review by AlwinEsch — COMMENTED** [review]
Problem is always that there the parts becomes informed after the addon is changed.

Currently do PVR another way, but want also to have all addon types standardized in the way how changes are handled. For PVR most critical.

But related to every addon who does work at this moment (Python or Binary). It's mostly true that a addon file is cached by system, but Kodi does never know what a addon do.

As long a addon is a in Kodi included code and not a independent exe, can it bring always a crash during change of a running one!

**Comment by AlwinEsch** [comment]
I see no alternative for minimum one blocked call for something (disable or like now for unload)

Currently with @tamland's thing becomes a blocked call used on unload and load.
During test seen calls:
Disable addon: Calls AddonEvents::Disabled only
Uninstall addon: Calls AddonEvents::Unload only (no Disabled)
Enable addon: Calls AddonEvents::Enabled only
Install addon: Calls AddonEvents::Load only (no Enabled)

The for me very bad thing is that with `OnEvent(const ADDON::AddonEvent& event)` every registered place becomes informed, e.g. by a Python script or Skin addon change also the VFS binary addon.

In case of 20 registered OnEvent parts and 100 changed addons is this horrible.

**Comment by Rechi** [comment]
@xhaggi this needs a rebase

**Comment by tamland** [comment]
jenkins build this pleas

**Comment by tamland** [comment]
jenkins build this please

**Pull request merged**
