### PR TITLE
[gitignore] still keep old dvdplayer files in gitignore for one release

### PR DESCRIPTION
**Pull request by MartijnKaijser**

### CODE REVIEW

**Comment by FernetMenta** [comment]
IMO we should stop doing those kind of changes to gitignore. why do you bother about untracked changes in your local tree? Instead of wasting time with this, we should invest the energy into cmake and move away from in-tree building. first set of changes will come soon

**Comment by MartijnKaijser** [comment]
Because switching branches between master and Jarvis adds all the junk files.

**Comment by MartijnKaijser** [comment]
fyi this took me 30 seconds so hardly any time loss so not wasted any time.

**Comment by FernetMenta** [comment]
I am sure it will waste some processor cycles on every git command executed in the future :)
git clean -xfd xbmc/cores/blabla is imo the better approach when switching those branches

**Pull request merged**
