### PR TITLE
[Estuary] add seek slider to the new seekbar

### PR DESCRIPTION
**Pull request by ronie**
## Description
on the new (minimal) seekbar, the seek slider nib was missing during a seek operation.

@enen92 

## Screenshots (if appropriate):
before:
before

after:
after

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by ksooo — CHANGES_REQUESTED** [review]
We should add the nib also for live tv.

**Review by enen92 — APPROVED** [review]
That was fast. Thanks ronie!

**Comment by ronie** [comment]
@ksooo i've been looking into it, but i'm going to need someone to lecture me...

1. there are two hardcoded sliders for pvr in the seekbar dialog:
https://github.com/xbmc/xbmc/blob/08ce76c30e2660ba871d8b8211f3abe624c57cdd/xbmc/dialogs/GUIDialogSeekBar.cpp#L20-L21
could you explain what the difference is between them?

2. why is 402 (POPUP_SEEK_EPG_EVENT_PROGRESS) not implemented in Estuary?
(if it's an accidental omission i might as well fix it while i'm at it)

**Comment by ksooo** [comment]
@ronie 

402 was introduced with https://github.com/xbmc/xbmc/pull/13642 and 403 came in with https://github.com/xbmc/xbmc/pull/14316

403 replaced 402 in Estuary. I cannot say for sure that 402 meanwhile is not used by other skins.

**Comment by ronie** [comment]
@ksooo i've added the slider for PVR, but it depends on https://github.com/xbmc/xbmc/pull/18541

**Comment by ksooo** [comment]
@ronie why can't 403 be used?

**Review by ksooo — APPROVED** [review]
Works now as expected. Thanks.

**Comment by ronie** [comment]
sure, i'll look into it later today.

**Pull request merged**
