### PR TITLE
[tools/depends][target] Bump gnutls 3.7.8

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Bump gnutls 3.7.8

## Motivation and context
Samba 4.17 requires gnutls 3.7.2 as a minimum.
Bump this separately for easier testing

## How has this been tested?
Build run macos apple silicon. Accessing https resource, playback media via IA based addon

## What is the effect on users?
Hopefully nothing

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by garbear — APPROVED** [review]
Looks like a standard dependency bump, and I even see some improvements by moving gnutls-specific config to its Makefile.

**Comment by joseluismarti** [comment]
If we change DEFAULT_NDK_API=23 we are raising the minimum compatibility to devices with API level 23

**Comment by fuzzard** [comment]
I'm fully aware. Im just confirming on Jenkins the issue with < API 23 isn't tied to ndk.

This will be shelved, as well as other bumps relying on gnutls 3.7+ (at least samba 3.17) until we raise minimum SDK api

**Comment by joseluismarti** [comment]
Sorry, I didn't see that it was a test to confirm that API level 23 solved a compilation issue (in src/gl/fpending.c)

**Comment by joseluismarti** [comment]
A proposal, if we change line 44 in `src/gl/fpending.c` to
```c
  return fp_->_p - fp_->_bf._base;
```
Now compiles

**Comment by fuzzard** [comment]
@joseluismarti are you able to runtime and check this is ok for your testing now?

**Comment by joseluismarti** [comment]
> @joseluismarti are you able to runtime and check this is ok for your testing now?

Seems to work perfectly on x86 playing a SSL stream with ffmpeg

**Pull request merged**
