### PR TITLE
Playlist creation modded into a threading model v3

### PR DESCRIPTION
**Pull request by quickmic**
## Description
https://1drv.ms/u/s!AsC6yIANTPi5e36jJfGLy6x5z3o

previous approach:
https://github.com/xbmc/xbmc/pull/15541

## Motivation and Context
Poor performance on large playlists/libraries

## How Has This Been Tested?
amd64 Linux Mint

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by quickmic** [comment]
Any chance that this patch will be released?

**Comment by zag2me** [comment]
@DaveTBlake

**Comment by quickmic** [comment]
Maybe this approach is something for 19? I know it's quite a bit step.

**Comment by quickmic** [comment]
closed, seems there is no interest in fixing basic design flaws.

**Comment by HeresJonny** [comment]
@notspiff

**Comment by tobybear** [comment]
Is there really no interest from the Kodi dev team to implement this patch? Kodi still has major performance issues with large database/playlists!

**Comment by HeresJonny** [comment]
@DaveBlake has implemented extensive changes / fixes for playlists in the meantime... not sure if this here approach still applies.

**Pull request closed without merging**
