### PR TITLE
[VideoPlayer] Remove unused code

### PR DESCRIPTION
**Pull request by thexai**
## Description
[VideoPlayer] Remove unused code after https://github.com/xbmc/xbmc/pull/24117

## Motivation and context
Removes almost unused code:

- Intermediate variables related to old cache level method (calculated but not used).
- "Cache delay" variable is calculated and only used on debug OSD when video is paused. Is supposed informative only and anyway related to old cache level algorithm "estimated time to cache reaches estimated level". I'm not sure if many people have fully understood this at some point :)

## How has this been tested?
Videos still playing

## What is the effect on users?
none

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [X] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by ksooo — APPROVED** [review]
+1

**Review by garbear — APPROVED** [review]
Main commit is 15 lines removed, 0 lines added, seems safe enough if there are no side effects.

**Comment by enen92** [comment]
Jenkins build this please

**Comment by garbear** [comment]
I added "after https://github.com/xbmc/xbmc/pull/24117" to the description because it's good to link PRs, please edit if incorrect.

**Comment by ksooo** [comment]
@thexai Merged with open clang-format issues? Don’t we have agreement to solve those issues before merge? Or is GitHub tricking me?

**Comment by thexai** [comment]
The issues are solved with the second commit and are in a separate commit because the first commit is code removal only.

Technically it is not correct that Jenkins suggests format changes in code removal only commit and on lines not touched.

**Comment by ksooo** [comment]
> The issues are solved with the second commit

@thexai ah, overlooked this on the phone, sorry for the noise.

**Pull request merged**
