### PR TITLE
Update README.raspberrypi

### PR DESCRIPTION
**Pull request by hawkeyexp**
Correct commandlines to make it more failsave to read and prevent build errors

### CODE REVIEW

**Review by razzeee — APPROVED** [review]

**Comment by Razzeee** [comment]
Thank you!

**Comment by MartijnKaijser** [comment]
why was this merged?

**Comment by Razzeee** [comment]
Because it fixes some oversights in the raspberry PI documentation?

**Comment by MartijnKaijser** [comment]
then it should have been merged to master branch.

**Comment by Razzeee** [comment]
crap, didn't expect anybody PRing against anything other than master :(

**Pull request merged**
