### PR TITLE
Update/mesa 23.0.1

### PR DESCRIPTION
**Pull request by cscd98**
## Description
Updates Mesa to v23.0.1

## Motivation and context
Tools/depends builds would benefit from upgraded Mesa drivers.

libdrm and wayland have been updated as these are pre-requisite versions for mesa 23.

## How has this been tested?
Compiled wayland, libdrm and mesa. Linked kodi. Uploaded to target arm device. Video output observed.

Links to files for upload to kodi mirrors:
https://wayland.freedesktop.org/releases/wayland-1.18.0.tar.xz
https://dri.freedesktop.org/libdrm/libdrm-2.4.115.tar.xz
https://archive.mesa3d.org/mesa-23.0.1.tar.xz
https://wayland.freedesktop.org/releases/wayland-protocols-1.24.tar.xz

## What is the effect on users?
None

## Types of change
- [x] **Improvement** (non-breaking change which improves existing functionality)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document

### CODE REVIEW

**Comment by fuzzard** [comment]
```
00:45:35 Dependency wayland-protocols found: NO found 1.20 but need: '>= 1.24'
00:45:35 Run-time dependency wayland-protocols found: NO 
00:45:35 
00:45:35 meson.build:2127:2: ERROR: Dependency lookup for wayland-protocols with method 'pkgconfig' failed: Invalid version, need 'wayland-protocols' ['>= 1.24'] found '1.20'.
00:45:35 
00:45:35 A full log can be found at /home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/target/mesa/aarch64-linux-gnu-debug/build/meson-logs/meson-log.txt
00:45:35 WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
00:45:35 yes
00:45:35 make[2]: *** [Makefile:81: aarch64-linux-gnu-debug] Error 1
00:45:35 make[2]: Leaving directory '/home/jenkins/workspace/LINUX-AARCH64-GLES/tools/depends/target/mesa'
00:45:35 make[1]: *** [Makefile:173: mesa] Error 2
```

Guess you'll need to bump wayland-protocols as well. Fine to do in this same PR, just a separate commit is best

**Comment by craigcarnell** [comment]
@fuzzard Done. Weird how mine never complained!!

**Comment by fuzzard** [comment]
They joys of CI, haha

**Comment by craigcarnell** [comment]
Jenkins build this please

**Comment by craigcarnell** [comment]
Created an issue with mesa, had no reply yet.

https://gitlab.freedesktop.org/mesa/mesa/-/issues/8476

**Comment by craigcarnell** [comment]
@fuzzard 

Do we need x11 for linux 64-bit build? -Ddri3=enabled needs to be enabled in this case.

https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/meson.build#L300

```meson
_platforms = get_option('platforms')
if _platforms.contains('auto')
  if system_has_kms_drm
    _platforms = ['x11', 'wayland']
  elif ['darwin', 'cygwin'].contains(host_machine.system())
    _platforms = ['x11']
  elif ['haiku'].contains(host_machine.system())
    _platforms = ['haiku']
  elif host_machine.system() == 'windows'
    _platforms = ['windows']
  else
    error('Unknown OS @0@. Please pass -Dplatforms to set platforms. Patches gladly accepted to fix this.'.format(
          host_machine.system()))
  endif
endif
```

**Comment by fuzzard** [comment]
Its used for CI coverage, so yes, it's required.

**Comment by craigcarnell** [comment]
@lrusak Does this change see logical to you:

https://github.com/xbmc/xbmc/pull/22885/commits/993b97c05e6af05eb3a2db2500529a7ea4e5a8dc

Not sure why [android-arm64-docker (android-arm64-docker)](https://jenkins.kodi.tv/job/android-arm64-docker/1405/) fails as I don't see any references to mesa.

**Comment by fuzzard** [comment]
@craigcarnell tarballs are uploaded to mirrors now. Safe to drop the base_url commit. could you also squash the mesa 23.0.1 commit into the first commit. As we wont have 23.0.0 on mirrors, it would break bisect, so better to just squash.

**Comment by craigcarnell** [comment]
@fuzzard Done

**Comment by wsnipex** [comment]
the commit message of the last commit is misleading: Build wayland only for gles which also covers arm 
how about: "[depends] mesa: build with wayland support only for GLES"?

**Comment by craigcarnell** [comment]
@fuzzard @wsnipex updated description of last commit

**Pull request merged**
