### PR TITLE
[guiinfo] Fix support for ListItem.NextDuration

### PR DESCRIPTION
**Pull request by ksooo**
Bug reported in the forum: https://forum.kodi.tv/showthread.php?tid=337739&pid=2794437#pid2794437 ff

@Jalle19 I hope you've got time for a quick review?

### CODE REVIEW

**Review by Jalle19 — APPROVED** [review]
Not sure why epgeventicon was moved but I trust you

**Comment by ksooo** [comment]
Because it does not belong in the special table for the labels taking a "time format" as parameter. I overlooked this glitch when I was approving  the PR that introduced this label.

**Comment by ksooo** [comment]
@ronie fyi, this introduces a new guiinfo label.

**Comment by ronie** [comment]
thx!

**Pull request merged**
