### PR TITLE
[JSON-RPC] Do not limit the time to 24 hours

### LINKED ISSUE #17907: [JSON-RPC] Global.Time: do not limit the time to 24 hours
### Describe the bug
Here is a clear and concise description of what the problem is:

In JSON-RPC API, the types [`Global.Time`](https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/types.json#L26) and [`Player.Position.Time`](https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/types.json#L181) don't accept a duration greater than *23:59:59.999*. A duration should not be limited to one day. Videos or music can last more than 24 hours ([example](https://www.twitch.tv/videos/558585800)).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should accept a duration greater than *23:59:59.999*.

```json
{
  "jsonrpc": "2.0",
  "method": "Player.Seek",
  "params": {
    "playerid": 1,
    "value": {
      "time": { "hours": 24 }
    }
  },
  "id": 1
}
```

## Actual Behavior

Kodi returns an error.
```json
{
  "error": {
    "code": -32602,
    "data": {
      "method": "Player.Seek",
      "stack": {
        "message": "Received value does not match any of the union type definitions",
        "name": "value",
        "type": ["string", "number", "object"]
      }
    },
    "message": "Invalid params."
  },
  "id": 1,
  "jsonrpc": "2.0"
}
```

## Possible Fix

Remove the `"maximum"` property of `"hours"` in [`Global.Time`](https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/types.json#L26) and [`Player.Position.Time`](https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/types.json#L181).

```json
{
  "Global.Time": {
    "type": "object",
    "properties": {
      "hours": { "type": "integer", "required": true, "minimum": 0 },
      "minutes": { "type": "integer", "required": true, "minimum": 0, "maximum": 59 },
      "seconds": { "type": "integer", "required": true, "minimum": 0, "maximum": 59 },
      "milliseconds": { "type": "integer", "required": true, "minimum": 0, "maximum": 999 }
    },
    "additionalProperties": false
  },
  "Player.Position.Time": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "hours": { "type": "integer", "minimum": 0, "default": 0 },
      "minutes": { "type": "integer", "minimum": 0, "maximum": 59, "default": 0 },
      "seconds": { "type": "integer", "minimum": 0, "maximum": 59, "default": 0 },
      "milliseconds": { "type": "integer", "minimum": 0, "maximum": 999, "default": 0 }
    }
  }
}
```

### To Reproduce

1. In Kodi, *Allow remote control via HTTP* (*Settings* / *Services* / *Control*).
2. Play a video.
3. Execute (by changing the IP address) : `curl -d '{ "jsonrpc": "2.0", "method": "Player.Seek", "params": { "playerid": 1, "value": { "time": { "hours": 25 } } }, "id": 1 }' -H 'Content-type: application/json' -X POST 192.168.1.2:8080/jsonrpc`
4. Kodi returns an error: *Invalid params.*

### Debuglog

The debuglog can be found here:

Kodi log nothing.

### Screenshots 
Here are some links or screenshots to help explain the problem:

NA

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

NA

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSMC 2020.03-1
 - Kodi version: 18.6

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by regseb**
## Description

In JSON-RPC API, the types [`Global.Time`](https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/types.json#L26) and [`Player.Position.Time`](https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/types.json#L181) don't accept a duration greater than *23:59:59.999*. A duration should not be limited to one day. Videos or music can last more than 24 hours ([example](https://www.twitch.tv/videos/714783117)).

## Motivation and Context

Pull request to fix #17907.

## How Has This Been Tested?

1. In Kodi, *Allow remote control via HTTP* (*Settings* / *Services* / *Control*).
2. Play a long video. For example (need [*Twitch video plugin*](https://kodi.tv/addon/plugins-video-add-ons/twitch)) : `curl -d '{ "jsonrpc": "2.0", "method": "Player.Open", "params": { "item": { "file": "plugin://plugin.video.twitch/?mode=play&video_id=714783117" } }, "id": 1 }' -H 'Content-type: application/json' -X POST 127.0.0.1:8080/jsonrpc`
3. Execute : `curl -d '{ "jsonrpc": "2.0", "method": "Player.Seek", "params": { "playerid": 1, "value": { "time": { "hours": 25 } } }, "id": 1 }' -H 'Content-type: application/json' -X POST 127.0.0.1:8080/jsonrpc`
4. Video seeks to 25 hours.

## Screenshots (if appropriate):
NA

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by enen92** [comment]
As suggested by @Tolriq in https://github.com/xbmc/xbmc/issues/17907 the proper fix for this issue is the addition of another param "days" instead of removing the 23 hour max value...

**Comment by regseb** [comment]
@enen92 I answered in the issue that Kodi didn't use days for durations longer than 24 hours. Removing the maximum of hours is simple solution that is consistent with other parts of Kodi.

I can add the `days`. But this will add breaking change in JSON-RPC API, for the `totaltime` property of `Player.GetProperties`:

- Currently: `{"totaltime":{"hours":46, "milliseconds":0, "minutes":10, "seconds":40}`
- With `days`: `{"totaltime":{"days": 1, "hours":22, "milliseconds":0, "minutes":10, "seconds":40}`

What is the maximum limit for the `days`?

**Comment by enen92** [comment]
You might be right and this is probably better than adding days, at least it is consistent with the information displayed in the player OSD (which doesn't impose a limit on the hours).

**Review by enen92 — APPROVED** [review]

**Comment by Tolriq** [comment]
Not my call, but fix by the lower is not always the proper solution for long term. What is wanted and easier to understand for the user? What does other apps display for those case? When something might be broken aligning the proper thing to the broken one is often the simplest choice but rarely the correct one.

Removing the limit will make any future change an even more breaking change with more impacts.

**Review by DaveTBlake — CHANGES_REQUESTED** [review]
I think the fundamental problem his is that these are called times in the schema, and it is resaonable to expect a "time" to mean clock time and always be less than 24 hours. Moreover it has been defined that way for a long time so consumers could be relying on it.  As ever the original schema is overly and unhelpfully restrictive, but we are often stuck with it. 

>  A duration should not be limited to one day. 

That may well be true, although I do wonder how much media actualy has such a long duration (not taking the odd twitch example as mainstream use). 

However on careful examination since:
a)  the "times" from a player are actually a position or a duration and not a clock time, and
b) `Global.Time` is only returned by calls to `Player.GetProperties` and `Player.Seek`

I would accept this as a breaking change, however with the following 
a) Descriptions added to both modified types to say that they are a position or duration and not a clock time. That way if some future addition to the API wanted a clock time value it would be obvious not to use `Global.Time` type. 
b) This is an actual schema change and so needs a bump to the minor version not the patch. 
c) Make it clear in the commit message that the hour values returned by `Player.GetProperties` and `Player.Seek` can exceed now 24 hours.

**Review by DaveTBlake — APPROVED** [review]

**Pull request merged**
