### PR TITLE
[docs] Update the build dependencies for Ubuntu

### PR DESCRIPTION
**Pull request by joseluismarti**
## Description

Keep up to date the guide with the package dependencies needed to build Kodi in Ubuntu.

Changed the package `flatbuffers-dev` with `libflatbuffers-dev`.

Added the packages:

* `libdrm-dev`
* `libunistring-dev`

## Motivation and Context

Build errors; some libraries not found.

## How Has This Been Tested?

Ubuntu Desktop 20.10 clean install.

apt install the three packages.

Build Kodi!

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [x] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by wsnipex — CHANGES_REQUESTED** [review]
please add the missing deps for ubuntu 20.10 in an extra line, like is done for ubuntu 18.04 a few lines down.

**Comment by codywalker77** [comment]
Ty

**Comment by bugwelle** [comment]
Oh, why was this closed? :(

**Comment by joseluismarti** [comment]
Sorry a git commit confusion :( 
I'll create a clean PR and link it to this one.

**Pull request closed without merging**
