### PR TITLE
rename weather icon type

### PR DESCRIPTION
**Pull request by ronie**
as there will be both 'weather icon' and 'weather fanart' resource addons, i'd like to rename the resource type to weathericons for this one.

the name change in addon.xml is to allow for proper sorting (by type) in the gui.

@Montellese objections?

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
fine for me. btw it seems that the original included license went missing for these icons. Could you include it back?

**Comment by ronie** [comment]
license file added.

**Comment by Montellese** [comment]
I don't really care how the addon is called.

**Comment by ronie** [comment]
jenkins build this please

**Comment by uNiversaI** [comment]
@ronie @Montellese 
```<description lang="en">Default set of Weather Icons shipped with Kodi</description>``` 
should be 
```<description lang="en">Default set of Weather icons shipped with Kodi</description>```
But OK not a huge deal.

What is not OK is:

##### This does not remove old addon **Default Weather Icons** version 1.1.7 ID ```resource.images.weather.default ```already installed, since 1.1.8 its a different ID and addon name now, - so the bump to 1.1.8 is meaningless.

Having both installed causes mayhem: There is no way to remove old **Default Weather Icons** version 1.1.7 ID ```resource.images.weather.default ```  but manually cant be uninstalled or disabled via Kodi.

**Issues:** WIth Openwetahrmap and this PR
1) Dont ask me why - but LIRC is blocked completely and no more communicating with Kodi at all so no more MCE remote.
2) OpenWeatherMap Extended no longer has any images, period.

Solution for 1), disable weather addon, immediately remote works. Then go into the guts of system to find **resource.images.weather.default** and delete it manually, **since you cant uninstall or disable this and **there's 0 cleanup for old stuff anywhere**

Solution for 2) add this as a dependency for weathermap extended? Nope that doesnt work either.
Looking around everything feels incomplete when comparing to the UI sounds extension.
compare addon.xml for ui sounds and the images and you see no 
```  
  <requires>
    <import addon="kodi.resource" version="1.0.0"/>
  </requires>
```

openwetharemap needs an update to say the least. the rest I barely understand and cant get it to work.

**Comment by MartijnKaijser** [comment]
all works for me.
don't use lirc
old image pack is removed.

**Comment by ronie** [comment]
complete and utter bollocks, as usual.

next!

**Comment by uNiversaI** [comment]
... How offensive and rude and of course its not "bollocks" as its a genuine issue

**Comment by Montellese** [comment]
IMO the issue with the renaming of the addon id and the old addon not being deleted doesn't really need any attention because it's only an issue for people who have installed the few nightly builds where the old addon id has been used. Those people can easily delete the addon manually. Everyone else (especially people only installing monthlies, betas, RCs and stable releases) won't have any issues at all.
I have also "fixed" the `addon.xml`, see 5cd5c028fd33370c0ddb26400d466748cc4bdb09 but it doesn't have any influence on the behaviour.

Not sure what else is incomplete.

**Comment by uNiversaI** [comment]
@Montellese thank you for a decent and honest reply forst of all. :)
> Those people can easily delete the addon manually. Everyone else (especially people only installing monthlies, betas, RCs and stable releases) won't have any issues at all.
> I have also "fixed" the addon.xml, see 5cd5c02 but it doesn't have any influence on the behaviour.

Sure but you still have to do it manually. there was no need to bump since ID was different and when it was Im wondering if it was a genuine oversight, but clearly by the response the error was mine in even bringing the issue up.

> I have also "fixed" the addon.xml, see 5cd5c02 but it doesn't have any influence on the behaviour.

Thank you, I thought something looked off.

> Not sure what else is incomplete.
Im not sure either I was comparing 
https://github.com/xbmc/xbmc/blob/master/addons/kodi.resource/uisounds.xsd
and
https://github.com/xbmc/xbmc/blob/master/addons/kodi.resource/images.xsd

specifically the   ```<xs:complexType> </xs:complexType>```

And seems to be a some difference in how this was implemented.

I still have no images in openweathermap at this time.

**Comment by Montellese** [comment]
The `images.xsd` is fine. I'm not even sure why `uisounds.xsd` and `languages.xsd` have the `id` attribute defined.

Concerning images I can see all images of OpenWeatherMap just fine but I'm not 100% sure if they might be cached or not.

**Comment by uNiversaI** [comment]
No Idea, @Montellese  Ill try cleaning the cache using texturecache.py maybe it needs to after https://github.com/xbmc/xbmc/pull/7519

**Pull request merged**
