### PR TITLE
[tools/depends[native] Bump Rustup and rust version

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Bump rustup script to 1.27.0 and rust target toolchain to 1.78.0

## Motivation and context
Started getting the following build failures on jenkins

```
checking that generated files are newer than configure... done
error: package `cargo-credential-libsecret v0.4.4` cannot be built because it requires rustc 1.76.0 or newer, while the currently active rustc version is 1.75.0
Either upgrade to rustc 1.76.0 or newer, or use
cargo update cargo-credential-libsecret@0.4.4 --precise ver
where `ver` is the latest version of `cargo-credential-libsecret` supporting rustc 1.75.0
```

No idea if this is going to have to be backported.

## How has this been tested?
Rustup and cargo-c built ok on macos host

## What is the effect on users?
N/A

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by quietvoid** [comment]
This was probably caused by the bump of `cargo-c`, it requires Rust 1.75 since `v0.9.31.

**Comment by fuzzard** [comment]
knowing nothing about rust, and a 2 minute google, it looks like dependency pinning isnt easily solved at our level for rust crates. The failing crate that started this is https://crates.io/crates/cargo-credential-libsecret and it was updated a day ago, coinciding with our failures. From what i gather, if crates dont "pin" their dependency versions in their toml file, rust will just get latest version, bringing on this situation. I really dont know how to solve that for us as a dependency of a dependency of a crate is deep enough that it seems stupid for us to try and patch our way out of it. normally this is why we put our dependencies on our mirrors to have "pinned" versions always available.
Essentially im expecting Omega to fail (it'll run a nightly in the next few hours, first since the above crate was updated). Which long term leads to branches potentially becoming uncompilable (eg if the rust stuff was in Nexus, we dont backport to nexus any longer, but it would now fail to build).

Maybe someone in the rust world can give some insight into these sort of issues.

**Comment by garbear** [comment]
Dependencies of dependencies can be locked with a Cargo.lock file. Can we ship a Cargo.lock file in depends?

**Comment by fuzzard** [comment]
No idea, someone figure it out and do it i guess

**Comment by fuzzard** [comment]
Android failure wasnta. build failure. the old clang warning failure that pops up from time to time

```
[Clang] [-ERROR-] Can't create fingerprints for some files:
[Clang] [-ERROR-] - '/home/jenkins/jenkins-root/workspace/android-arm64-docker@2/tools/depends/target/dummy-libxbmc/checking for stdlib.h... checking for attr_get... configure.ac' file not found
[Clang] [-ERROR-] - '/home/jenkins/jenkins-root/workspace/android-arm64-docker@2/tools/depends/target/dummy-libxbmc/configure.ac' file not found
```

**Comment by garbear** [comment]
I've found that updating rustc usually fixes most depends of depends problems. I think if we update rust early and often in both latest release and master then headaches will be rare.

**Pull request merged**
