### PR TITLE
Added category D framebuffer modes

### PR DESCRIPTION
**Pull request by chr-b**
Framebuffer modes of category "D" are not ignored anymore.

### CODE REVIEW

**Comment by chr-b** [comment]
For some background information on this pull request, please check http://forum.kodi.tv/showthread.php?tid=267290

**Comment by fritsch** [comment]
@mk01 your customer :-)

**Comment by mk01** [comment]
@fritsch 
aehm - good to go :)

**Comment by mk01** [comment]
@chr-b 
can you add something like "[EGLIMX]" to commit msg to ease log history reading ?

**Comment by chr-b** [comment]
Created a new pull request.
Modifying already pushed commit message is not a good thing...

**Comment by popcornmix** [comment]
> Modifying already pushed commit message is not a good thing...

It is fine. This is only modifying your PR branch which no else will be cloning.
Edit / force push is the correct thing to do for PRs. Opening a new PR is not.

**Pull request closed without merging**
