### PR TITLE
Add System.Platform.WebOS conditional

### PR DESCRIPTION
**Pull request by matthuisman**
## Description
Adding a new conditional  Platform.System.WebOS

Note: The linux check also returnes True for WebOs (like it does for Android)
So scripts should check WebOS before Linux

## Motivation and context
Allow addons / skins to detect WebOS

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by matthuisman** [comment]
would be nice if this was backported to v21 which was the first version with WebOS

**Comment by matthuisman** [comment]
i do not have a webos to test on unfortunately. hoping someone else can compile and try on webos to confirm the conditional works

**Comment by sundermann** [comment]
The change works fine. Can't really say much about the guilib changes as I'm not familiar with that part of the code but the changes look reasonable.

**Review by ksooo — APPROVED** [review]
The code change looks good to me.

**Comment by matthuisman** [comment]
no change of backport to 21?

Just would allow detecing webos on all the versions that are built for webos :P
Otherwise i'll need this check / fallback to something else

**Review by enen92 — APPROVED** [review]

**Comment by wsnipex** [comment]
Imho a Backport would be fine

**Comment by matthuisman** [comment]
backport done: https://github.com/xbmc/xbmc/pull/25074

**Pull request merged**
