### PR TITLE
[droid;packaging] Bump targetSdkVersion to match current API level

### PR DESCRIPTION
**Pull request by bmc08gt**
5.1 is API 22

### CODE REVIEW

**Comment by BMc08GT** [comment]
@koying

**Comment by koying** [comment]
From the docs: 
```This attribute informs the system that you have tested against the target version and the system should not enable any compatibility behaviors to maintain your app's forward-compatibility with the target version.```

I don't have any 5.1 devices, yet, so premature as far as I'm concerned.
On which 5.1 device did you test?

**Comment by BMc08GT** [comment]
Nexus player after latest ota

**Comment by BMc08GT** [comment]
Any tests that should be run on the device to test compatibilty?

**Comment by MartijnKaijser** [comment]
@BMc08GT 
care to rebase?

**Comment by BMc08GT** [comment]
Sure thing :)

**Comment by koying** [comment]
+1 from me ;)

**Comment by MartijnKaijser** [comment]
added in
https://github.com/xbmc/xbmc/pull/7189

**Pull request closed without merging**
