### PR TITLE
ProcessInfo: Move AllowDTSHDDecode into Processinfo

### PR DESCRIPTION
**Pull request by popcornmix**
Removes a platform specific ifdef from common code

### CODE REVIEW

**Comment by popcornmix** [comment]
Ping @FernetMenta

**Comment by FernetMenta** [comment]
+1 thanks

**Comment by popcornmix** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
it seems this breaks gtests.

**Comment by wsnipex** [comment]
disregard the above comment. Its probably https://github.com/xbmc/xbmc/commit/c56e9ded30f84717fb6d99ffa1bc47a5bd482fc7 which broke gtests

**Pull request merged**
