### PR TITLE
[Playlists] Rename song methods to generic item index

### PR DESCRIPTION
**Pull request by enen92**
## Description
PlaylistPlayer methods incorrectly use `Song` when they actually refer to an item index (which can be of any type). I've the goal of rewritting the slideshow player to use the PlaylistPlayer and a new player implementation for pictures trying to fit it into our current abstractions.
Thus, this PR simply renames a few methods from "song" to generic item.

### CODE REVIEW

**Comment by DaveTBlake** [comment]
I have nothing to quibble about renaming.

Question about your overall goal:  will the new player implementation for pictures cover the currently well used facility to play a slide show while also playing music? Would be sad to lose that functionality, which may or may not have been accidental feature rather than explicit design originally, but is a used feature.

**Comment by enen92** [comment]
> I have nothing to quibble about renaming.
> 
> Question about your overall goal: will the new player implementation for pictures cover the currently well used facility to play a slide show while also playing music? Would be sad to lose that functionality, which may or may not have been accidental feature rather than explicit design originally, but is a used feature.

Honestly I don't have yet a clear picture of this but my goal is not to remove functionality, but thanks for bringing this up though!
I may even give up in the meanwhile as this usually means opening a can of worms :)
Regardless, this change is still good even without a clear goal.

**Comment by enen92** [comment]
jenkins build this please

**Review by garbear — APPROVED** [review]
From a code standpoint it looks like the rename was done correctly.

**Review by DaveTBlake — APPROVED** [review]

**Pull request merged**
