### PR TITLE
Bump version to 21.0.1 to allow Android install on top of Play Store version

### PR DESCRIPTION
**Pull request by thexai**
## Motivation and context

Android users has trouble installing nightly builds because Play Store version is `21.0.1` and nightly `21.0.0`

Is even worse because install may fail silently (without error) and user thinks app is updated but not.

This change is only relevant for Android.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by garbear — APPROVED** [review]
If 21.0.1 was "published" (read: hacked around some play store quirks) then we should bump here too.

**Comment by garbear** [comment]
Mergeable shows another place the version needs to be bumped, so this affects more than android.

**Comment by thexai** [comment]
That happened other time in https://github.com/xbmc/xbmc/pull/24581 and fuzzard was able to merge it anyway. Let's let him take care of it.

**Review by ksooo — APPROVED** [review]
I have exactly this patch applied to my private build for some time.;-)

**Pull request merged**
