### PR TITLE
[Ext. Subtitles][Redux] Add subtitles language and name extraction from filename and VideoPlayer.SubtitlesLanguage infolabel

### PR DESCRIPTION
**Pull request by ace20022**
With @pieh's blessing I took over his PR#1365. I rebased it but haven't touched the commits' author info.
It would be nice if the feature could make it into the next merge window.

I have also worked on an solution to store these info in the db: https://github.com/ace20022/xbmc/commit/48388e8f47e68725d59298d7c000e5b3f4040380, but that only works upon play or when the thumbnail extractor runs.
@jmarshallnz are there any plans to update the db automatically? While idle or from time to time or something like that?
Storing the info in the db can be useful, e.g., for language flags: http://forum.xbmc.org/showthread.php?tid=155693.

### CODE REVIEW

**Comment by Paxxi** [comment]
This code is correct as is. The parsing done is to try and find a two/three letter iso language code and those are only english letters, trying to make this any better we would have to have tables for all possible language names in all languages and that's not feasible today.
I say leave this as is.

**Comment by ace20022** [comment]
thanks @Paxxi for your help!

> those are only english letters

Sure, I had the hope to at least "parse" the name. But maybe I should change it to
```C++
 if (result != toParse.end()) // if we have anything to parse
 {...}
else
{
  name = toParse;
}
```
Not sure if this yields nice results. @taxigps do you think this helps in manually finding the right sub?

**Comment by taxigps** [comment]
@ace20022 need trim delimiters at left of toParse like "."
@Paxxi users need some message to find right sub, so show the string we can't parse better then show nothing.

**Comment by ace20022** [comment]
@taxigps That's what I was trying to do with isalnum. I could add a hardcoded trim of ```.' '-``` in the else case.

**Pull request merged**
