### PR TITLE
[pvr] bump pvr.vbox to v2.0.1

### PR DESCRIPTION
**Pull request by Jalle19**

### CODE REVIEW

**Comment by Jalle19** [comment]
jenkins build addons please

**Comment by Jalle19** [comment]
jenkins build addons please

**Comment by Jalle19** [comment]
Jenkins doesn't seem to like something:

```
CMake Error at /home/jenkins/workspace/BINARY-ADDONS/platform_label/androidx86/tools/depends/target/binary-addons/i686-linux-android-android-17/build/depends/lib/kodi/addon-helpers.cmake:85 (message):
  CMAKE_INSTALL_PREFIX
  /home/jenkins/workspace/BINARY-ADDONS/platform_label/androidx86/tools/depends/target/binary-addons/i686-linux-android-android-17/.install
  differs from Kodi prefix
  /home/jenkins/workspace/BINARY-ADDONS/platform_label/androidx86/tools/depends/xbmc-depends/i686-linux-android-android-17.
  Please pass -DOVERRIDE_PATHS=1 to skip this check
```

@koying @Memphiz have you seen this kind of error before?

**Comment by hudokkow** [comment]
I've seen it a few days ago with a pvr PR. Also on androidx86

**Comment by Jalle19** [comment]
Can we still merge this?

**Pull request merged**
