### PR TITLE
[confluence] [PVR] small adjustments

### PR DESCRIPTION
**Pull request by Glenn-1990**
Some small fixes as in commit messages.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Thanks, this fixes the errors reported in #9012.

**Comment by Razzeee** [comment]
@HitcherUK @phil65 @ronie

**Comment by phil65** [comment]
Code looks fine to me now.

**Comment by HitcherUK** [comment]
Cant test PVR but by the looks of the code you're trying to shift the position of a label if an icon is visible but you haven't included conditions for all the icons available (ie PVR-HasTimerScheduleError.png).

**Comment by Glenn-1990** [comment]
@HitcherUK 
ListItem.HasTimer returns true for all kind of timers, including ones with an error.

**Comment by HitcherUK** [comment]
@Glenn-1990 
Tested with PVR demo and the icon overlaps the start time label if you use a 12h clock.
Might be easier to drop the conditional labels and stick with the shorter of the 2 while shifting the icon more to the right like this -
```
<control type="image">
	<left>110</left>
	<top>7</top>
	<width>16</width>
	<height>16</height>
	<texture>$VAR[PVRTimerIcon]</texture>
</control>
<control type="label">
	<left>150</left>
	<top>0</top>
	<width>250</width>
	<height>30</height>
	<font>font12</font>
	<textcolor>grey2</textcolor>
	<selectedcolor>selected</selectedcolor>
	<align>right</align>
	<aligny>center</aligny>
	<label>$INFO[ListItem.Label]</label>
</control>
```

**Comment by Glenn-1990** [comment]
@HitcherUK I didn't introduced this shift (only changed the textures) and I'm unable to test this atm. But I'll see what I can do about it.

**Comment by HitcherUK** [comment]
Maybe @ronie or @phil65 have some thoughts?

**Comment by ronie** [comment]
@HitcherUK your suggestion looks good to me.

**Comment by Glenn-1990** [comment]
@HitcherUK Can you test now? I did not use your approach as it does not look nice when not using the 12h clock (the icon seems a bit lost then).

**Comment by HitcherUK** [comment]
Yeah, that works as well.

PS Shouldn't that be -`<visible>![ListItem.HasTimer + ListItem.HasRecording + ListItem.IsRecording]</visible>`

**Comment by ronie** [comment]
closing since confluence has been removed.
feel free to resubmit your changes here:
https://github.com/xbmc/skin.confluence

**Pull request closed without merging**
