### PR TITLE
[windows] enable libdav1d in the ffmpeg build

### PR DESCRIPTION
**Pull request by lrusak**
no idea if this works or not, we'll see what jenkins says if this is all I have to do or not.

### CODE REVIEW

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
clearly not
```
13:04:59 ERROR: dav1d >= 0.2.1 not found using pkg-config
```

**Comment by wsnipex** [comment]
sorry, fat fingered..

**Comment by Paxxi** [comment]
Could it be that it needs a patch like for openssl https://github.com/xbmc/xbmc/blob/master/tools/buildsteps/windows/patches/0001-ffmpeg-detect-openssl.patch ?

**Comment by wsnipex** [comment]
the windows binaries do not include pkg-config files, but a dav1d-config.cmake file.
The find modules should use this, e.g. by using find_package(dav1d) on windows platforms.

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
@Paxxi what's the best way to handle the windows error? I tried to fix it but it seems we need to link libdav1d into kodi as well as ffmpeg

**Comment by Paxxi** [comment]
Completely forgot about this. Since we build ffmpeg as static dav1d need to be added as a required dependency to core for the linker to figure it out.

I guess it should work like any other dependecy

**Comment by lrusak** [comment]
jenkins build this please

**Pull request merged**
