### PR TITLE
[Confluence][PVR] EPG data area in  PVR timer window.

### PR DESCRIPTION
**Pull request by ksooo**
Add EPG data area to  PVR timer window. PVR timers having a link to EPG data now get this data displayed in a new area in the PVR timer window - very similar to EPG window timeline view. This is very useful to look up what actually shall be recorded (for instance by a series recording rule):

screenshot003
screenshot004

@ronie, @Jalle19, @xhaggi  mind taking a look

### CODE REVIEW

**Comment by ronie** [comment]
looks ok to me.

**Comment by Jalle19** [comment]
Definitely an improvement!

**Comment by MikeB2013** [comment]
Nice work  - checked against mythtv backend 0.28pre with pvr.mythtv addon 3.2.0 on Ubuntu 15.04

**Comment by xhaggi** [comment]
looks good apart from the skin integration, because it would be nice to have the same layout for all windows (channels, recordings, timers) where we want to display additional informations. I've done this for the Xperience1080 skin.

screenshot001

screenshot002

screenshot000

**Comment by ksooo** [comment]
> looks good apart from the skin integration

 Well, I tend to disagre here. The fact that your favourite skin uses another layout (show epg data on the right) is IMO not an indicator for "bad" or "good" skin integration for Confluence.

> it would be nice to have the same layout for all windows (channels, recordings, timers)

Agreed. Inner-skin consistency is important. And we did one step ahead into this direction with this PR. Timer window (now) does it exactly like the Guide timeline window. Recording window is different, but this is not related to this PR, I guess...

**Comment by xhaggi** [comment]
As I don't use confluence you can leave it as it is, because @ronie has to decide ;) I only want to show you an alternative way to display the additional infos and to be consistent between the list views (channels, recordings, timers)

**Comment by ksooo** [comment]
@xhaggi Thanks.

**Comment by ksooo** [comment]
As all stakeholders gave me their +1 for this, I'm going to merge this August 1.

**Pull request merged**
