### PR TITLE
[Music]Fix album duration determination

### PR DESCRIPTION
**Pull request by DaveTBlake**
Fix the way album duration is determined (before being stored) to allow for music files for an album split over separate folder trees.

Since https://github.com/xbmc/xbmc/pull/18257 album duration is stored data (so can be used in smart playlists etc.). Helping a user with a more unusual folder layout revealed that the approach of calculating this was too simplistic, and a SQL approach be used instead. 

Say music files for an album were in folder layout like this:
```
folderAlbum
--->folderA
--->--->folderAX
--->--->--->folderAXX
--->--->--->--->song1.flac
--->--->--->--->song2.flac
etc.
--->folderB
--->--->folderBX
--->--->--->folderBXX
--->--->--->--->song3.flac
--->--->--->--->song4.flac
etc.
```
The scanning process drills down tree branch at a time and processes the album in separate parts. Hence AddAlbum gets called multiple times, the first adds the album for the first time, subsequent calls adding songs to it. Just looping through the songs as they are added will not get a true album duration.

Solution is to use SQL to fetch the sum of the duration of all songs on the album.

Tested with both complex tree and more stanard music folder layouts

### CODE REVIEW

**Comment by DaveTBlake** [comment]
jenkins build this please

**Comment by DaveTBlake** [comment]
jenkins build this please

**Comment by HeresJonny** [comment]
Does this take into account the wrongly reported durations for WAVPACK/DSD?

**Comment by DaveTBlake** [comment]
>Does this take into account the wrongly reported durations for WAVPACK/DSD?

No, not at all. IIRC that is a ffmpeg issue returning wrong data, and nothing Kodi can do about it.

**Pull request merged**
