### PR TITLE
[gitignore] - remove outdated paths

### PR DESCRIPTION
**Pull request by phil65**
@afedchin for quick libdvd check
@ronie those confluence paths are also outdated, right?

### CODE REVIEW

**Comment by ronie** [comment]
yup, there's no /skin folder anymore.

**Comment by MartijnKaijser** [comment]
Also remove line 544 and onwards

**Comment by afedchin** [comment]
looks good for me

**Comment by phil65** [comment]
@MartijnKaijser : updated.

**Pull request merged**
