### PR TITLE
[PVR] Ensure that newly added channel groups are persisted, fixes trac 16365

### PR DESCRIPTION
**Pull request by ksooo**
Regression introduced by #6092

Trac: http://trac.kodi.tv/ticket/16365

@Jalle19 Good to go?

### CODE REVIEW

**Comment by Jalle19** [comment]
@ksooo I guess

**Comment by ksooo** [comment]
@Jalle19 I'm the submitter of this PR, so reviewing myself wont work. ;-) I thought as you introduced the regression you should have some knowledge/opinion...

**Comment by Jalle19** [comment]
I tried to fix a performance issue when I introduced the regression, can't really remember more than that though. If your change doesn't have any obvious side effects it should be good to go.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by Razzeee** [comment]
Does this also fix this?
http://trac.kodi.tv/ticket/16305

**Comment by ksooo** [comment]
@Razeee Yep, 16365 is a duplicate of 16305.

**Pull request merged**
