### PR TITLE
fix plugin context menus

### PR DESCRIPTION
**Pull request by tamland**
Fixes the ordering of context items from plugins which got messed up in recent refactoring.

I have also removed the broken 'replaceItems' option as I don't why plugins should be allowed to destroy menus coming from core and other addons, or what this would be useful for.

### CODE REVIEW

**Comment by phil65** [comment]
Not sure about the removal of that parameter, need to think about that first.

For listitems added via WindowXML.addItem() we definitely need some way to disable / replace the core/addon context menu entries though because for those listitems script calls to self shouldnt be done async. Using onAction() makes much more sense here.

**Comment by tamland** [comment]
@phil65 No idea what you're talking about tbh.. This is about the addContextMenuItems method which allows plugins replace the context menu in their own directory...

**Comment by phil65** [comment]
The issue I mentioned is not really related to this PR, but related to the contextmenu rework in general. At the moment the core context menu gets displayed for listitems added to WindowXML instances. That should get disabled because it leads to some issues. (the one i mentioned, and also that the core context menu calls Container.Update() which breaks the WindowXML.)
If you need further details on how to test etc, drop me a message on slack.

**Comment by tamland** [comment]
So, ok to remove then?

**Comment by phil65** [comment]
I will take a look at the existing plugins tomorrow to see how big the fallout would be (this is definitely a far bigger API breaker than removing redundant params for .setInfo() ;) ) and comment then.

**Comment by tamland** [comment]
Except that API compatibility is kept. It doesn't break anything, it merely ignores the replace request..

**Comment by phil65** [comment]
...exactly the same as the change i did.  It didnt break anything,  setInfo()  ignores not - used values. ;-)

**Comment by tamland** [comment]
lets agree to disagree and get back on topic shall we

**Comment by phil65** [comment]
Sure sure, just wanted to make sure that we use the same yardsticks. Both changes make Kodi simply ignore the request, there´s no real difference.

I git-grepped some of our plugin branches, my impression is that we should keep that replaceItems option for now. Quite a handful of plugins use it, and I could also imagine some edge-cases where it would make sense to have a custom context menu. @ronie, what´s your opinion?

**Comment by ronie** [comment]
the 'replaceItems' option was added years ago when xbmc did show a lot of non suitable context menu items for plugins.
a lot has changed since then and afaik the only context menu items kodi currently adds in plugin containers are 'add to favourites' and 'play from here'.

i can't think of a usecase why those need to be removed by a plugin, so imo 'replaceItems' has served it's purpose and is no longer needed.

**Comment by tamland** [comment]
^ that was the actual question here; not if it's used, but if there are any real use cases for it. From what I can see in the addons in the repo, it's all api misuse/abuse and not done for any purpose.

Also, @phil65: the difference is that removing an info label setter will cause addons using that label to no longer set it, and it turn no longer show it in the gui. Here, since there are no real reason to request them hidden, there is altering of any functionality provided by the plugin.

**Comment by phil65** [comment]
> lets agree to disagree

Well, the question is more whether we want some grace period for those API-abusing plug-ins to fix their shit. Since I never was opposed to some breakage, feel free to press the green button. ;)

**Comment by tamland** [comment]
As I said, API is backwards compatible. No need for any grace period or to 'fix' anything. They will _just work_. 
So jenkins build this please

**Comment by phil65** [comment]
I guess you are not aware what plug-in authors are doin nowadays :)
Stuff like this here: https://github.com/liberty-developer/plugin.video.prime_instant/blob/master/default.py#L1087-L1091
will lead to double entries for example.

**Comment by tamland** [comment]
How? None of those menus exist in core. Actually, this pr _fixes_ that plugin as it breaks core functionality for no reason.

**Comment by phil65** [comment]
see updated link. Anyways, no need to discuss this further. Merge it, no complaints here.

**Comment by tamland** [comment]
New link pass replaceItems=False. Already a duplicate lol.

Fin.

**Comment by phil65** [comment]
I am very confident that you understood the message. ;)

**Comment by ronie** [comment]
i noticed some regression...

movies / tv shows / etc... libraries
the 'manage..' option is missing


videos > files
a lot of context menu options are missing

before:
before

after:
after

**Comment by tamland** [comment]
@ronie 83f959f8c15b3c8bd0331bb2f3b0dd0f648945ce Pay attention guys:p

**Comment by spoyser** [comment]
capture

The final 4 have need added due to the replaceItems being ignored.

A simple example I know.

I guess the biggest issue is that it also adds context menu addon extensions. I'm currently adding functionality to SF to allow various options too be added to the standard menu (athough broke in Krypton - see here http://trac.kodi.tv/ticket/16697) and these will certainly not be required whilst in the SF addon. I guess I'll need to add code to disable them when in SF.

Just seems pointless removing it.

**Comment by ronie** [comment]
**if** kodi adds the 'Play' and 'Marked as watched' options on non-playable items, it's something that needs to be fixed in core imo.

'Add to favourites' doesn't seem to be a problem, you could simply drop the duplicate one your addon adds.

the 'Super Favourites Menu' one is added by a context menu addon i guess?
visibility of those can be controlled through the `<visible>` tag.

**Comment by spoyser** [comment]
The play and mark as watched are correctly added in the example, although it doesn't feel right them being at the bottom.

Add to favourites - yes I can remove the one I add, again the position isn't great. 

And yes the visibility of the 'Super Favourites menu' can be controlled (as it already is to be switched on via a configurable setting), I guess I can somehow detect the title of the current container?

A lot of effort, for little gain. 

My gripe is that useful functionality, ie the ability for an addon to fully customise it's own context menu has now been removed - and I cannot see any legitimate reason for this, if the functionality had never been there and I was asking for it to be added fair enough - but removing it???

**Comment by spoyser** [comment]
Also, if I start Super Favourites from the Music menu (as a side note please can that be renamed Audio someday), I get this context menu for this item:

ActivateWindow(10502,&quot;addons://sources/audio/&quot;,return)

music

**Queue item, Play and Make default are all incorrect.**

Secondly Super Favourites allows you to have the displayed items numerically prefixed, ie

01 | Item A 
02 | Item B
03 | Item C
04 | Item D

Before being added to Kodi favourites, these require the prefix to be removed. Again the "built-in" Add to favourites doesn't do this. Again a showstopper IMHO. 

Shall I carry on?

**Comment by spoyser** [comment]
menu

This is the menu you get on a Super Folder item within SF (when SF is started from the music menu), the Play, Mark as watched, Queue item, Play using... and Make default are all erroneous and make no sense.

Is that enough use cases yet?

**Comment by Montellese** [comment]
IMO it is a bug in Kodi that these context menu items are added where they shouldn't (which needs to be fixed).

**Comment by tamland** [comment]
@spoyser If you haven't notices there have a lot of refactoring of the context menu lately to make it global and unified. That means broken code and useless "features" goes. All you are doing is post images of random context menu claiming it's 'incorrect' and 'making no sense', not presenting any use cases. If some context menu is shown where it shouldn't, _that_ should be fixed. Not pile on more workarounds.

**Comment by spoyser** [comment]
@tamland - apologies for bringing bugs to your attention - would you rather I didn't bother.

**Use Case - The builtin "Add to favourites" may not work under certain circumstance.**

Example 1
In the Super Favourites addon (in the official org repo) the "built-in" Add to favourites does not work correctly for many items; there is a method in Super Favourites for handling the adding to Kodi favourites as some items need modifying to work correctly (addToXBMC in default.py if you fancy taking a look).

Example 2
In the Super Favourites addon (in the official org repo) the user has the option to display items numerically prefixed, ie

01 | Item A 
02 | Item B
03 | Item C
04 | Item D

Before being added to Kodi favourites, these require the prefix to be removed. The "built-in" Add to favourites doesn't do this.

Obviously, these 2 use cases both relate to the Super Favourites, but I'm sure there will be others with similar problems that I'm not familiar with.

**Comment by tamland** [comment]
Menus like play and queue are showing because you are incorrectly setting playable attributes on non-playable items. 

What's broken here is the utter mess that is super favourites. If you actually expect anything in that addon to work from revision to revision, I cant help you... Instead of complaining that one of your many hacks and workarounds broke, you should try finding proper solutions to you problems.

"Add to favourites" being available for things it won't work for, I can agree with, but this is global issue with that feature affecting all plugins, not related to this pr.

**Comment by spoyser** [comment]
**WOW - JUST FREAKING WOW **

And you wonder why the majority of users have very low opinions of Team Kodi. I'll bookmark this page as a reference for next time a holier than thou Kodi dev posts in the forum claiming how friendly and helpful you all are.

I'm really not sure what your beef is with SF, maybe it should be removed from the official repo if it is such a mess then - can you point to one hack or work-around?

Anyhow, before you start throwing accusations around simply because I'm trying to help, I have checked and I can confirm that I am setting the parameters correctly

A non-playable folder:
14:03:54 T:4368   DEBUG: *********** SF DEBUG OUTPUT ***************
14:03:54 T:4368   DEBUG: label		Non-Playable Super Folder
14:03:54 T:4368   DEBUG: isFolder parameter	True
14:03:54 T:4368   DEBUG: isPlayable parameter	False

Gives this menu:
non-playable


And a playable folder:
14:05:19 T:5072   DEBUG: *********** SF DEBUG OUTPUT ***************
14:05:19 T:5072   DEBUG: label			Playable Super Folder
14:05:19 T:5072   DEBUG: isFolder parameter	False
14:05:19 T:5072   DEBUG: isPlayable parameter	True

Gives this menu:
playable

They are obviously different so must be being treated differently in code (Play compared to  Play using...) but the first one is incorrectly showing the Play item (etc)

"Instead of complaining that one of your many hacks and workarounds broke, you should try finding proper solutions to you problems." - I am, that's why I'm  posting here.

Anyway, it is obvious from your replies that your not bothered about this issue and really you are just interested in arguing, so I'm signing-off from this thread, 

I won't expect an apology for your false accusation - that would clearly be far too much to ask.

**Comment by phil65** [comment]
/me has seen this coming, but only got bashed for mentioning it. :)

**Comment by wjturner1978** [comment]
jeez..... someone has been drinking too much of their own coolaid... sf is one of the best coded plugins kodi has keep up the good work spoyser

**Comment by tamland** [comment]
spoyser you're taking this way too personal. It's not:\

/me notes to self: just leave half-broken things to slowly die on their own next time. not worth the hassle..

**Comment by DixieDean** [comment]
tamland, you actually think some of your comments above are OK?
As someone looking in and reading from the outside, they are down right insulting.

You need to wind your neck in and show some respect. In my humble opinion.
Your arrogance is astounding.

**Comment by phil65** [comment]
guys, this is no place for stuff like that. I think both sides have their arguments, but that would a discussion for the forum... Also remember that this is still pre-alpha, no need to go through the roof.

**Comment by phil65** [comment]
For reference: http://forum.kodi.tv/showthread.php?tid=270648

**Pull request merged**
