### PR TITLE
[Fix][cximage] Fix read after free crashes

### PR DESCRIPTION
**Pull request by ace20022**
This fixes http://trac.kodi.tv/ticket/16588

No guarantee that this doesn't introduce regressions.

### CODE REVIEW

**Comment by fritsch** [comment]
jenkins build this please

Thanks much!

**Comment by teeedubb** [comment]
Thanks ace. Can anyone please post a link to this build? I cant find it on the jenkins build page or the kodi mirrors page. Thanks

**Comment by MartijnKaijser** [comment]
If you want a windows test build http://mirrors.kodi.tv/test-builds/win32/KodiSetup-20160217-04b01df-JarvisPNG.exe

**Comment by teeedubb** [comment]
Thanks Martijn

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
