### PR TITLE
Cleanup kai toast icons

### PR DESCRIPTION
**Pull request by tamland**
@mkortstiege while we're at it, I don't see why this has to be so complicated.

This replaces control 403, 404 and 405 with the predefined names `DefaultIconError.png`, `DefaultIconWarning.png` and `DefaultIconInfo.png` as we already do with other images.

Is there any reason these controls exist other than for skins to define the image name?

### CODE REVIEW

**Comment by mkortstiege** [comment]
I can't imagine a reason. @BigNoid, @ronie objections?

**Comment by BigNoid** [comment]
Afaik everybody uses this to load those default icons, so this is much better. Also nice that DefaultIconInfo.png is now loaded as image if there's no icon.

**Comment by ronie** [comment]
nice, +1 from me.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
