### PR TITLE
Fix parse of filter rules for boolean fields  into SQL query

### PR DESCRIPTION
**Pull request by DaveTBlake**
Fix how filter rules for **boolean fields**, as given in smart playlist files (.xsp), custom node files(.xml) and JSON API data requests,  are converted into SQL queries.  In particular correctly handle "is", "isnot", "contains" and "doesnotcontain" operators with value true or false. 
____
It is far from intuitive how filter rules for boolean fields should be entered. Of course operators "true" and "false" naturally work with boolean fields e.g.  
a) in xml (for smartplaylists and custom nodes) 
         `<rule field="compilation" operator="true">`
         `<rule field="compilation" operator="false">`

b) in JSON 
       `"filter": { "field": "compilation", "operator": "true",  "value": "any dummy value here"} `
       `"filter": { "field": "compilation", "operator": "false",  "value": "any dummy value here"} `

Notice that the JSON schema forces all filter rules to have a "value" property regardless of operator hence `"filter": { "field": "compilation", "operator": "true"} ` is invalid.

However it is reasonable to expect to be able to use
`<rule field="compilation" operator="is"> <value>true</value> </rule>`
or
`"filter": { "field": "compilation", "operator": "is",  "value": "true"}`

These are valid rule input formats, but an incorrect SQL query is formed as a consequence and the data is not filtered in the way the user expects.

This PR ensures that for boolean fields the SQL created with operators "is" or "contains" and value "true", or operators  "isnot" or "doesnotcontain" and value "false" will result in the same SQL as `operator="true"`. Likewise that created with operators "is" or "contains" and value "false", or operators  "isnot" or "doesnotcontain" and value "true" will be the same as with `operator="false"`

An example test smart playlist is follows (you need a music library with some albums flagged as compilations
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<smartplaylist type="albums">
    <name></name>
    <match>all</match>
    <rule field="compilation" operator="is">
        <value>true</value>
    </rule>
</smartplaylist>
```
Equilvalent JSON request 
```
{"jsonrpc": "2.0", "id": 1, "method": "AudioLibrary.GetAlbums", "params": { 
"limits": { "start" : 0, "end": 60 }, 
"filter": {"field": "compilation", "operator": "is", "value": "true"} } }
```

Bump patch version of JSON API as change to internal implementation but not to the API definition.

### CODE REVIEW

**Comment by DaveTBlake** [comment]
jenkins build this please

**Comment by DaveTBlake** [comment]
jenkins has been "pending" for 2 days now?
Anyway BuildMulti PR-Manualy  gives greens https://jenkins.kodi.tv/view/Helpers/job/BuildMulti-PR-Manually/308/

**Comment by Rechi** [comment]
The build you linked hasn't build all platforms a PR build would build.

**Comment by DaveTBlake** [comment]
Yes, I know that @Rechi but what would be the point in adding UWP or Win32 which fail for everything

**Comment by Rechi** [comment]
Those aren't the only ones missing. Android-X86, FreeBSD, IOS, LINUX-64, LINUX-64-GBM, LINUX-64-Wayland, LINUX-AML, LINUX-RBPI and TVOS are missing too.

Also building the known failing platforms still has a point. You can see if a change causes an earlier build failure.

**Comment by DaveTBlake** [comment]
Yes I know that there are other platforms too @Rechi 
What would be really useful is if you could press the magic button and get this jenkin PR build unstuck

**Comment by DaveTBlake** [comment]
jenkins build this please

**Comment by DaveTBlake** [comment]
jenkins build this please

**Comment by DaveTBlake** [comment]
jenkins build this please

**Comment by DaveTBlake** [comment]
jenkins build this please

**Comment by DaveTBlake** [comment]
jenkins build this please

**Comment by DaveTBlake** [comment]
jenkins build this please

**Comment by DaveTBlake** [comment]
Build errors are UWP/Python3 related, nothing to do with this PR

**Pull request merged**
