### PR TITLE
[confluence] texture updates.

### PR DESCRIPTION
**Pull request by un1versal**
I decided to retry re-submitting these improvements for two reasons,
**_1)**_ Much has evolved since original PR and since you cannot easily make a theme installer for default skin as it resides in system paths and not userdata that also requires some coding beyond my skills

**_2)**_ Since **_1)**_ is more time consuming and unlikely to happen as easily. Confluence can <b>alternatively</b> by default ship with a **_second theme**_ if so, This could easily be re-submitted as a secondary theme to be included by default. That probably require a different PR though.
### Testing

https://github.com/uNiversaI/revamped.themes/archive/2.3.5.zip by following instructions and selecting Revamp-osf theme (note the background used in theme not included in this PR)

**dropped 6cd3169**
`The only addition new graphics currently unused is commit  6cd3169 [confluence] Add NEW Default HDD icons  …  which probably requires xml or maybe sourcecode changes which are atm beyond my ability.
That adds 3 new types DefaultBDFull/Empty.png and DefaultUSB textures. which I thought would be nice to include. But will require assistance from a skinner to make them usable.`

I tried to separate each change into separate commits to maybe make this reviewing simpler (if that's at all possible)

I will be happy try to accommodate any requests improvements

@ronie or whoever is responsible for deciding, please decide, if not wanted just close the PR.

Note all current psd sources can be found at https://github.com/uNiversaI/revamp-confluence-psds

### CODE REVIEW

**Comment by uNiversaI** [comment]
All the same to me, Im using it and I like it obviously. 

Feel free to close or do whatever use or not use. All is opensource and everything is available in fully editable psd for you UI guys to fix and tweak to your liking.

Personally I dislike having to push this against such hardened resistance and I dont have time to waste in work  that probably will never please some people and be rejected in the end..

**Comment by Memphiz** [comment]
work is not wasted ... using this an all my boxes and also installed it on the rbpi of my girl ... thx ;)

**Comment by MartijnKaijser** [comment]
I also like it more than what we have  now

**Comment by da-anda** [comment]
I'm not holding anything back - I only mentioned that the blue feels a bit too saturated for the otherwise dark and dimmed skin

**Comment by uNiversaI** [comment]
Added the DefaulVideoDeleted.png for PVR stuff

https://github.com/uNiversaI/revamped.themes/archive/2.3.2.zip

**Comment by uNiversaI** [comment]
@Montellese added https://github.com/uNiversaI/kodi/commit/bb727f718b551aa31a8d9644e35da3a0f9661b55 for your commit now available on https://github.com/uNiversaI/revamped.themes/archive/2.3.5.zip for testing/usage.

**Comment by MartijnKaijser** [comment]
our GUI guys think the blue is to saturated so this will never get merged.

**Comment by uNiversaI** [comment]
thx for closing if I knew it was a massive waste of my time.

**Comment by MartijnKaijser** [comment]
you were told many times the blue is too saturated.

**Comment by uNiversaI** [comment]
Forget it. branch deleted

**Comment by uNiversaI** [comment]
@da-anda @ronie @topfs2 @Memphiz 

I addressed all comments about color saturation and before I was given a chance to update this PR, someone closed it. (a feel out of frustration related to some other PR kinda evil IMO sadly.)

To test download https://github.com/uNiversaI/revamped.themes/archive/3.1.1.zip

Apply ***Revamped-osf*** theme

Still todo: new Wallpaper

:warning: This PR, Would need be updated and reopened if desired. ***Its too much work to separate all the images by groups like this does*** and Im not going to bother just so someone has the pleasure of closing it to slap me across the face.

Else, the work is there anyone can go and grab it as it is GPL

Comments welcome.

**Comment by Memphiz** [comment]
@uNiversaI i like that one too (revamped-osf it is)

**Comment by uNiversaI** [comment]
Yes peding a minor twek or other its not saturated at all, so lets see what gives form the others.

**Comment by uNiversaI** [comment]
@Memphiz Thanks for that comment.

Im really looking for feedback on whether this PR can be re-opened and ill update it then with those changes becuase its a huge deal of work Im not willing to waste if no one really wants these changes anyway.

**Comment by uNiversaI** [comment]
@Memphiz @ronie @da-anda @phil65 @BigNoid 

I already spend many hours addressing all saturation issues and am very happy with results in https://github.com/uNiversaI/revamped.themes/archive/4.0.1.zip and revamped-osf that should satisfy the requirements and comments above mentioned.

**I'm really looking for feedback on whether this PR can be re-opened and ill update it then with those changes** because its a huge deal of work for PR alone, Im not willing to waste time if no one really wants these changes anyway.

one last try for  before the breech as isengard beta1 nears.

**Comment by da-anda** [comment]
@uNiversaI just tried your theme. The colors of the OSD icons and folders look good to me now (the DefaultXXX icons/thumbs), but I still feel some colors don't match well yet. For example the button hover texture and the one used for focused file items in lists. They might have the same blue colour, but the visual impression is different. So when the color is used on a larger area it probably could be dimmed a bit.
I also  noticed that the list item hover texture doesn't fade out nicely on the edges - so one is able to see a edge in the area that's supposed to be 100% transparent already.

And please don't get me wrong - I appreciate that the blue has less saturation, but it's now a little to desaturated because you also chaged the color of the blue itself (not in majority of the images, but the text in the home menu f.e.). But keep it like that for now.

What I really don't like is the background, but that can be changed independently.

@ronie what do you think?

**Comment by uNiversaI** [comment]
@da-anda thank you, could you provide a couple of screenshots indicating the problems you mentioned? That would help greatly (my old tired eyes) may need the visual queue to notice some things.

**Comment by phil65** [comment]
Now that we have SamFisher on board I definitely want him to design our new UI textures (or at least all the DefaultIcon stuff). The stuff he did for AudioDSP is just too amazing to leave him out for any skin rework.

**Comment by da-anda** [comment]
@phil65 your suggestion is something for a new skin IMO

@uNiversaI will prepare a screenshot

**Comment by uNiversaI** [comment]
@da-anda 

I think I know what you meant by the some of the comments above

>I also noticed that the list item hover texture doesn't fade out nicely on the edges - so one is able to see a edge in the area that's supposed to be 100% transparent already.

that above fixed

I dimmed down the submenu focus textures a bit wasnt sure what other textures need dimming

Until I see your screenshot cant really address things Im not sure which ones you mean or what exactly.

see https://github.com/uNiversaI/revamped.themes/archive/4.02.zip

Idle like to get this ready for isengard beta if you guys want it at all.

**Pull request closed without merging**
