### PR TITLE
[screensaver.xbmc.builtin.dim] reduce dim minimum threshold to zero

### PR DESCRIPTION
**Pull request by Hitcher**
## Description

Dim can now be set to zero because screensaver.xbmc.builtin.black doesn't work when a dialog is open.
## Motivation and Context

Requested for plasma users.
## How Has This Been Tested?

Yes
## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ronie** [comment]
lgtm.

kinda makes screensaver.xbmc.builtin.black redundant i guess?

**Review by ronie — APPROVED** [review]

**Comment by da-anda** [comment]
shouldn't the black screensaver be fixed instead? I don't mind either way, just wondering.

**Comment by HitcherUK** [comment]
> shouldn't the black screensaver be fixed instead? I don't mind either way, just wondering.

I don't think there's a problem with the black screensaver it's just that core will use fade instead of any screensaver when a dialog is open because all screensavers (apart from black) open a window.

**Review by DaVukovic — APPROVED** [review]
thanks

**Comment by ksooo** [comment]
@DaVukovic PR is flagged as an "improvement". Usually we only do backport issues flagged as "bug". What's the point for making an exception here?

**Comment by DaVukovic** [comment]
Sorry, my bad then. I'll remove that flag. As said in the backport PR, fine with me if we decide against such a backport.

I can't tell another reason as I already did for an potential exception. If that's not enough, then I won't argue against that ;)

**Comment by HitcherUK** [comment]
It's sort of a fix for https://github.com/xbmc/xbmc/issues/16123

**Comment by DaveTBlake** [comment]
Its a fix, it can and has  (even should) been backported. Just needed correctly lables :)

**Comment by ksooo** [comment]
@DaveTBlake  Please tell me what exactly gets fixed by this PR.

**Comment by ksooo** [comment]
This all makes not much sense for me:

> Dim can now be set to zero because screensaver.xbmc.builtin.black doesn't work when a dialog is open.

plus 

> I don't think there's a problem with the black screensaver it's just that core will use fade instead of any screensaver when a dialog is open because all screensavers (apart from black) open a window.

 If a modal dialog is open no window can be opened. All modal dialogs must be closed first. 

 So, every screen saver that opens a window cannot be activated while a dialog is open (in case of paused video this will be CGUIDialogVideoOSD I guess). If core invokes no screen saver in this situation, how can a change in dim screensaver fix something here?

**Comment by HitcherUK** [comment]
> If core invokes no screen saver in this situation, how can a change in dim screensaver fix something here?

Core will invoke the dim screensaver but this didn't help users who were using black as dim couldn't be set to zero.

**Comment by ksooo** [comment]
=> https://github.com/xbmc/xbmc/issues/16123#issuecomment-532344858

**Comment by ksooo** [comment]
Fix for #16123 is here: https://github.com/xbmc/xbmc/pull/16636

**Comment by DaveTBlake** [comment]
If fix for #16123 is elsewhere, is this change still required or should it be reverted?

**Comment by HitcherUK** [comment]
Could still be useful imo.

**Comment by ksooo** [comment]
> Could still be useful imo.

 Yep. We should keep it.

**Pull request merged**
