### PR TITLE
[Music]Display "Various artists" in the artists list when albumArtistsOnly set

### PR DESCRIPTION
**Pull request by DaveTBlake**
Before Gotham the "Various artists" entry would appear in the artists list  (when "include artists who appear only on compilations" is disabled). On the forum users have requested this is reinstated. See http://forum.kodi.tv/showthread.php?tid=223454 and  http://forum.kodi.tv/showthread.php?tid=200797

It also seems inconsistent to exclude it as an album artist in this one view, since it does appear when listing the artists for a specific genre.

Looked back in the Git I have not be able to find a good reason to exclude it - in fact it simplifies the query. Anyone see a problem?  A nice simple change, a good place to start my first PR.

### CODE REVIEW

**Comment by evilhamster** [comment]
Well there are some albums that are from one artist but still have the compilation flag set (for example http://musicbrainz.org/release-group/9189fd8d-d5b0-3a9d-98d6-dc3a68576d17), after this change that artist will be visible but it wasn't before (if you only had album like that from that artist). I prefer the behavior after this pr :)

Did some testing and it seems to work fine!

Not really related, but maybe the filtering a few lines down for various artists when albumArtistsOnly is false could be removed?

**Comment by DaveTBlake** [comment]
@evilhamster 
Thanks for checking this out. Yes this change does reveal some previously hidden (lost?) artists. That possibly elevates it to being a bug fix!! 

If you have albums with album artist(s) but also Musicbrainz tags including compilation flag set, then unless these artists appear on some other album then they are excluded from the artists  list. That is not good behaviour.

When albumArtistsOnly is false then it is valid to exclude the fake (album) artist "Various artists" from the artists list because you are listing the song artists. So no change there.

**Comment by Razzeee** [comment]
Not sure, but it seems like both commits here should have been seperated in a PR each?
Be sure to create a new branch for each feature your adding.

**Comment by DaveTBlake** [comment]
Oh poop! Yes that second commit was not intended to be in this PR. So I need a new branch for every PR? Git nubie causing havoc. Most importantly how do I get the 2nd commit out of here?

**Comment by phil65** [comment]
Yes, new branch for every PR. you can remove the wrong commit with interactive rebase. (rebase -i)

**Comment by DaveTBlake** [comment]
Made a mess with Git, all for 1 line of code!!
Going to close this PR and start again. So sorry for any trouble caused.

**Pull request closed without merging**
