### PR TITLE
have ServiceBroker return a pointer for WinSystem

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

@peak3d this destroys WinSystem properly

### CODE REVIEW

**Comment by garbear** [comment]
Thumbs up. Does this mean WinSystem is optional like GUI?

**Comment by FernetMenta** [comment]
@garbear still a long way to go until GUI or Winsystem can be considered as optional. There is a lot of code that depend on i.e. GUI. Next steps should be moving GUI parts away from lower layers like filesystem. GetDirectory for example shows the busy dialog.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
does anybody want to runtime test this before merge?

**Comment by bacon-cheeseburger** [comment]
I read that #13748 also broke LIRC, is this true?

**Comment by fritsch** [comment]
@bacon-cheeseburger Continue reading: https://github.com/xbmc/xbmc/pull/13761

**Pull request merged**
