### PR TITLE
VideoPlayer: drop remaining rfpsscale hack

### PR DESCRIPTION
**Pull request by FernetMenta**
I missed this on my previous PR.

### CODE REVIEW

**Comment by FernetMenta** [comment]
if original fps is wrong for what reason ever it should be fixed. no dirty hacks for a particular codec. 

jenkins build this please

**Comment by stefansaraev** [comment]
jenkins does not build this code path

```
AMLCodec.cpp: In member function 'bool CAMLCodec::OpenDecoder(CDVDStreamInfo&)':
AMLCodec.cpp:1545:42: error: 'class CDVDStreamInfo' has no member named 'rfpsrate'; did you mean 'fpsrate'?
     hints.fpsrate, hints.fpsscale, hints.rfpsrate, hints.rfpsscale, am_private->video_rate);
                                          ^~~~~~~~
AMLCodec.cpp:1545:58: error: 'class CDVDStreamInfo' has no member named 'rfpsscale'; did you mean 'fpsscale'?
     hints.fpsrate, hints.fpsscale, hints.rfpsrate, hints.rfpsscale, am_private->video_rate);
                                                          ^~~~~~~~~
```

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by stefansaraev** [comment]
as I said, jenkins will not even try compile this. if you want to build test it, revert https://github.com/xbmc/xbmc/pull/9688

**Comment by FernetMenta** [comment]
ahh, now I got it.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
Should we re-enable AMC again on Android or should it be added for Linux?

**Comment by stefansaraev** [comment]
@MartijnKaijser no. it should not be added on linux. up to you if you want to enable it on android after @codesnake's avsync PR is in.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
test build succeeded. I'll drop the "revert" commit and merge.

**Pull request merged**
