### PR TITLE
Allows choosing compiler during build of libsquish

### PR DESCRIPTION
**Pull request by atupone**

### CODE REVIEW

**Comment by Memphiz** [comment]
Which Problem do you have - how does it Manifest

**Comment by atupone** [comment]
Without the change the compiler to build libsquish is g++.
I want to use, on my raspberry-pi with gentoo, to use armv6j-hardfloat-linux-gnueabi-g++ (the default compiler for emerging package here) that then goes with distcc on my x86-64 pc that cross-compile it

**Comment by Memphiz** [comment]
Well if squish wouldn't honor the cc env it would fail on our cross compiles as well - so we really should try to find out what the real issue is here imo - @wsnipex or what is your opinion?

**Comment by wsnipex** [comment]
cross compile with our depends works fine, since we set CXX correctly. I think his use case is "native" build, but via distcc. In this case $CXX is probably not passed on to squish. Its not a common usecase, but I have no problem with this PR.

jenkins build this please

**Comment by Memphiz** [comment]
Now i got the context

**Pull request merged**
