### PR TITLE
VideoPlayer + AE fixes

### PR DESCRIPTION
**Pull request by FernetMenta**
I got this wrong with https://github.com/xbmc/xbmc/pull/8954

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by popcornmix** [comment]
This causes severe audio glitches when sync playback to display is disabled:
http://paste.ubuntu.com/14695897/

**Comment by fritsch** [comment]
@popcornmix are you sure you have the new version of this patch? @FernetMenta force-pushed yesterday and I heavily ran into the very same issue.

**Comment by fritsch** [comment]
This is the good version: https://github.com/FernetMenta/xbmc/commit/05f81ef0a635b42f623186abb9829d129eac8d88 - see the "slight" difference. audio branch is not uptodate

**Comment by popcornmix** [comment]
I had the latest version of this PR.
I've just switched to version from fernet's master branch and that is working okay.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by fritsch** [comment]
My issues are with those commits, but with: edae16b8 - it seems it's a locking issue.

**Comment by FernetMenta** [comment]
updated with a couple of fixes
jenkins build this please

**Pull request merged**
