### PR TITLE
[Estuary] OSD Button Improvements + Additions

### PR DESCRIPTION
**Pull request by jjd-uk**
## Description
Aim is to make OSD more useful for those with limited button remotes and expose better some of the available features to the users.

### New - Add Fast Forward & Rewind buttons

image

image

### Align Progress Bar nib function between Video & Music

Video had the action left & right with nib selected mapped to Step Back & Step Forward however the help test read that this would be Rewind & Fast Forward.

**_Incorrect help text:_**
image

Music did have left & right with nib selected mapped to Rewind & Fast Forward.

With addition of Rewind & Fast Forward buttons the left & right with nib action was changed for music to align with video to provide Step Back & Step Forward and help text corrected to reflect this.

**_Corrected help text:_**
image

### New - Add Frame Advance to Progress Bar

It's been possible since Leia to advance by a set number of frames when video is paused. To expose this to users I've added a new action for the seekbar nib so that when paused pressing right will advance video by 1 frame. Core function added in https://github.com/xbmc/xbmc/pull/12808

image

### New - Add buttons to access playlist

~~The icon used is an open source icon from Google obtained from https://github.com/google/material-design-icons/blob/master/av/drawable-xxxhdpi/ic_playlist_play_white_36dp.png and resized to 128x128 to match other buttons.~~

~~License info at https://github.com/google/material-design-icons#license
and actual License https://github.com/google/material-design-icons/blob/master/LICENSE~~ Changed

DefaultPlaylist.png copied and resized.

**Video playlist - updated**
image

**Music playlist - updated**
image

### New - Add buttons for tempo to control playback speed

This was requested by FernetMenta when he added the feature but has never been action, see https://github.com/xbmc/xbmc/pull/10216#issuecomment-237154003 and it's also been one of the more common requests on the forum https://forum.kodi.tv/showthread.php?tid=10023

**CHANGED AS A RESULT OF DISCUSSIONS** see below

~~As I am no good at graphics I search for appropriate open source icons but couldn't find any I thought fitted. At the moment~~

~~osd\fullscreen\buttons\speed-down.png~~
~~osd\fullscreen\buttons\speed-up.png~~

~~are being used as they seemed to be the best fit amongst the existing icons.~~

**_How controls currently look_**
https://user-images.githubusercontent.com/5781142/87032354-6504ca00-c1dc-11ea-92ad-066589269812.png

https://user-images.githubusercontent.com/5781142/87032367-6c2bd800-c1dc-11ea-85e3-0fed7fa57a94.png

~~Both buttons were added to the right of the Play button as they control the forward speed, so even when you decrease speed it's never below x0.8 in the forward direction.~~

~~To keep Stop button adjacent to Play it was moved to the left of the Play button.~~

~~As an alternative for the tempo buttons, I also experimented with rotating the rewind/fast forward style icons for up & down tempo controls~~

~~osd\fullscreen\buttons\speed-down.png~~
~~osd\fullscreen\buttons\speed-up.png~~

~~However these didn't seem as good a fit so presently they are unused.~~

~~@ronie would like your guidance on whether to stick with arrow-light-down.png and arrow-light-up.png in which case I'll remove speed-down.png and speed-up.png or perhaps you can come up with something better.~~

### Change - Help text

The displayed help text was consolidated into one VAR **OSDHelpTextVar** allowing the separate **VideoOSDHelpTextVar** and **MusicOSDHelpTextVar** to be removed. As I wanted help text available for the tempo controls I decided to add help text for all buttons, keeping separate VAR's would have thus necessitated some duplication.

~~In addition the text was change to button_focus colour to match the colour of the focus texture when a button is in focus.~~ Removed

Seen in this image (the other screenshots were taken before I added this change to the help text colour)

image

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x ] **Improvement** (non-breaking change which improves existing functionality)
- [x ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by jjd-uk** [comment]
Note- If anyone wants to test the tempo controls you **MUST** have **sync to display** enabled so Kodi can resample audio when playback speed is changed.

**Comment by HitcherUK** [comment]
Just my tuppence worth but I think the itemgap needs to be reduced between the buttons now as they get to close to the runtime/length.

**Comment by jjd-uk** [comment]
@HitcherUK Thanks for taking a look

> Just my tuppence worth but I think the itemgap needs to be reduced between the buttons now as they get to close to the runtime/length.

Changing itemgap from 20 to 10 gives

image

which indeed looks better I think. Will push the change later.

**Comment by jjd-uk** [comment]
Itemgap change from 20 to 10 pushed

**Comment by ksooo** [comment]
@jjd-uk  May I ask whether you've tested this changes with Live TV OSD?

**Comment by jjd-uk** [comment]
@ksooo I checked it with PVRDemo? do you have a particular concern?

**Comment by ksooo** [comment]
@jjd-uk I wanted to ensure the 'record' button got not lost. ;-)

**Comment by jjd-uk** [comment]
@ksooo Tempo controls have a Player.TempoEnabled check and are only shown if true, so I did check to make sure record wasn't lost or encroached on runtime/length labels. So I assumed because Player.TempoEnabled check fails tempo control is not valid for PVR, unless pvr.demo is not able to simulate a circumstance which does enable them.

**Comment by jjd-uk** [comment]
I stupidly forgot we already have a DefaultPlaylist.png icon that could be used for the OSD playlist button, so will copy to that one to media\osd\fullscreen and resize it to 128x128 to fit with the other OSD icons.

**Comment by ronie** [comment]
> In addition the text was change to button_focus colour to match the colour of the focus texture when a button is in focus.

could you please change it back to white?
the combination of white text + black shadow color offers the best contrast against both light and dark backgrounds.


> would like your guidance on whether to stick with arrow-light-down.png and arrow-light-up.png

could you turn them into 128x128px textures and move them to the same folder as the other osd buttons?
please pay attention as the current up / down arrows aren't properly centered.


> With addition of Rewind & Fast Forward buttons

i think those need a visible condition as well. afaik at least forward is not always possible with LiveTV.
@ksooo should be able to confirm

i'm also not sure if we can ever run into this with PVR:

pvr

@ksooo again


personally i'm not really sold on displaying the up / down tempo buttons... but i'm interested to hear what others think.

**Comment by jjd-uk** [comment]
For FF & RW perhaps if you're time shifting, so behind live stream then I assume you can do both within the buffer. Perhaps Player.SeekEnabled can check for that?

As for tempo controls I don't believe those are valid for PVR so I'll add an !VideoPlayer.Content(LiveTV) to make sure they don't appear to be on the safe side.

If you're not sure about the arrows, I'm open to ideas for doing it another way? or are you not sure about exposing tempo controls at all? An alternative I had considered was changing the function of the progress bar nib left/right from the step actions to tempo actions.

**Comment by ronie** [comment]
> Perhaps Player.SeekEnabled can check for that?

yup, that should be ok to use.

> If you're not sure about the arrows, I'm open to ideas for doing it another way? or are you not sure about exposing tempo controls at all?

i'm not sure if it's such a widely used function that justifies to have dedicated buttons in the osd for it.
i see confluence uses a different implementation, but i have never used it, so can't tell if it would be something to consider. 
but, as said, i'm hoping to hear some options from others...

**Comment by jjd-uk** [comment]
## Changes

- `button_focus` colour removed from `OSDHelpTextVar` so it goes back to being white.
- FF & RW buttons have `<visible>Player.SeekEnabled</visible>` added in both VideoOSD & MusicOSD guard against them being available when seeking is not possible.
- Tempo Up & Down how have `<visible>Player.TempoEnabled + !VideoPlayer.Content(LiveTV)</visible>` to explicitly disable them for Live TV.
- Playlist icon change to be the same as DefaultPlaylist.png & been resized to 128x128.
- Tempo icons added to OSD folder and resizes to 128x128. Not centred yet as I'm not sure if my graphic skills are up to that, so leaving until it's decided what is to be done with tempo controls.
- New tempo control method added (see below).

## Additional Tempo Control Method

@ronie 

I've added the alternative implementation I had in mind while keeping the arrow controls present, this so the 2 methods can be easily compared. If either method is acceptable then I'll obviously only keep the one agreed upon and remove the other.

The new implementation makes use of the progress bar nib, so progress bar now has the following behaviour:

- `Player.TempoEnabled` is false then Left/Right does step back & step forward (disable sync to playback and enable passthrough to test)

- `Player.TempoEnabled` is true then Left/Right changes playback speed (enable sync to playback to test tempo controls)

- `Player.Paused` is true then Right does frame advance

This hides the tempo controls from the majority of users.

I did look the the Confluence implementation but personally I'm not a fan of the RW/FF buttons having a dual purpose as done in Confluence.

**Comment by da-anda** [comment]
While I welcome the overall improvements, I am not a fan of the button overkill now. For starters, I would get rid of the ffwd/frwd buttons and instead provide this feature when focusing the progress bar (by pressing "UP" when the OSD menu is open). Currently, when the progress bar is focused, it does small step forward and back which is already the default behavior in fullscreen video mode without menu, so IMO not really required there.,Doing FFWD and FRWD instead might make more sense here, along with showing the speed of the FFWD and FRWD (2x, 3x, 4x, 8x, 16x or whatever the steps are).
And adjusting the playback speed is IMO not a that common feature that it would justify two buttons in the menu. How about having one button that toggles through something like 4 or 5 speed presets? (like 1.1x, 1.2x, 1.3x, 1.5x, 2x)?

**Comment by ksooo** [comment]
>  am not a fan of the button overkill now.

 Same here.

**Comment by ksooo** [comment]
> personally i'm not really sold on displaying the up / down tempo buttons... but i'm interested to hear what others think.

 I don't think anybody needs those buttons.

**Comment by ksooo** [comment]
>> With addition of Rewind & Fast Forward buttons

> i think those need a visible condition as well. afaik at least forward is not always possible with LiveTV.

 For TV back, forward, pause buttons are always optional. There are addons not supporting timeshifting at all, and when you are watching "live" there is obviously no way to go forward.

**Comment by jjd-uk** [comment]
> For starters, I would get rid of the ffwd/frwd buttons and instead provide this feature when focusing the progress bar (by pressing "UP" when the OSD menu is open). 

FF/RW are common buttons on any OSD and shouldn't be hidden away in my opinion.

> > personally i'm not really sold on displaying the up / down tempo buttons... but i'm interested to hear what others think.
> 
> I don't think anybody needs those buttons.

There is a need for tempo controls somewhere I think as it's one of the more common requests I see on the forum.

**Comment by Dnkhatri** [comment]
I would prefer the tempo buttons as very hard to use that option currently need to use a separate app like yatse or attach a keyboard to the device. With a lot of people using  new devices that have very buttons on the hardware controllers these buttons need to be on the kodi osd. Maybe an advance settings on<>off switch could be introduced  for different buttons so can be enabled for people that want the buttons and hide  them for those that don't.

**Comment by da-anda** [comment]
@jjd-uk did you read my suggestion regarding the playback speed buttons in my edited comment above? Might not have been part of the mail notification you got from Github (in case you have only read that)

**Comment by jjd-uk** [comment]
> @jjd-uk did you read my suggestion regarding the playback speed buttons in my edited comment above? Might not have been part of the mail notification you got from Github (in case you have only read that)

I don't believe the cycle option is possible with the way it's implemented in core. Having a single playback speed icon then using up/down when focused should be possible.

**Comment by ronie** [comment]
> Just done a quick test and indeed a single Playback Speed icon then using up/down on remote/keyboard would also work.

if we want to add tempo support to the osd, i'd prefer that solution over dedicated buttons or the progress bar.
personally i still feel it's a niche future and people who would like to use it should figure out a way using custom keymapping.

**Comment by Dnkhatri** [comment]
> > Just done a quick test and indeed a single Playback Speed icon then using up/down on remote/keyboard would also work.
> 
> if we want to add tempo support to the osd, i'd prefer that solution over dedicated buttons or the progress bar.
> personally i still feel it's a niche future and people who would like to use it should figure out a way using custom keymapping.

No buttons available to custom keymap to a setting to hide or show the buttons in settings would be the better option, Some people do not like the forward rewind button either so ability to toggle on off would be better.

**Comment by da-anda** [comment]
> > Just done a quick test and indeed a single Playback Speed icon then using up/down on remote/keyboard would also work.
> 
> if we want to add tempo support to the osd, i'd prefer that solution over dedicated buttons or the progress bar.
> personally i still feel it's a niche future and people who would like to use it should figure out a way using custom keymapping.

How about just adding this up/down feature to the play/pause button itself and if active, show a little overlay/indicator on the button that a custom speed is applied.

**Comment by jjd-uk** [comment]
> > > Just done a quick test and indeed a single Playback Speed icon then using up/down on remote/keyboard would also work.
> > 
> > 
> > if we want to add tempo support to the osd, i'd prefer that solution over dedicated buttons or the progress bar.
> > personally i still feel it's a niche future and people who would like to use it should figure out a way using custom keymapping.
> 
> How about just adding this up/down feature to the play/pause button itself and if active, show a little overlay/indicator on the button that a custom speed is applied.

That should also work. The OSD already show the custom speed if tempo controls are in use, that's the `Play speed ` shown in my screenshots, not sure if you mean something additional to this when you mention overlay/indicator.

**Comment by jjd-uk** [comment]
Posted this on our internal Slack channel, but to make it public here also, here is a demo of a new implementation based on @da-anda comments.

When Play/Pause button is focused then up & down will change the playback speed, and the onclick action to play/pause remains unchanged.

https://youtu.be/GJzprV98muk

**Comment by ksooo** [comment]
So, do I understand this right, up/down will do always the same for every OSD button, except the play button? Who will understand this inconsistency in behavior?

**Comment by jjd-uk** [comment]
> So, do I understand this right, up/down will do always the same for every OSD button, except the play button? Who will understand this inconsistency in behaviour?

If `Player.TempoEnabled` is True then yes **Up** can't be used to select the progress bar nib so that will be different from any other button, however if `Player.TempoEnabled` is False (for example is **sync playback to display** is disabled) then it's exactly the same as it is currently. The difference in behaviour is why the button label help message will display **[B]Press[/B] to Pause or [B]Up[/B] and [B]Down[/B] to change playback speed**.

**Comment by ksooo** [comment]
Sorry, I don't want to be PITA, but up/down for the same button behaving different is imo a no go. I'm pretty sure nobody will notice the different help text.

I'm with @ronie saying this is an edge case users can use a custom key map for.

**Comment by jjd-uk** [comment]
Well Youtube probably wouldn't agree with you or the many people who've asked for this on the forum.

image

I have a custom mapping myself but then I've got a remote with loads of buttons, I wanted to introduce something for other users that is accessible for people with limited button remotes.

However if it's a completely no go due to design constraints with the Estuary OSD then I'll drop it as won't affect me at all.

**Comment by jjd-uk** [comment]
I'll maybe take a further look at what can be done with the default remote.xml as my personal custom mapping uses keyboard.xml as it's a Harmony set up to emulate a keyboard.

**Comment by ksooo** [comment]
Longpress on Play/Pause button to popup a context menu with some predefined speeds + tempo+ as first, tempo- as last entry?

A single tempo button popping up above mentioned menu?

Something like that?

**Comment by jjd-uk** [comment]
Just remembered why I never pursued the remote.xml path. At present long press actions are not supported in remote.xml, see https://github.com/xbmc/xbmc/pull/10186 but there is a PR to add them https://github.com/xbmc/xbmc/pull/16740 just @phunkyfish to get it done and merged.

**Comment by jjd-uk** [comment]
> Longpress on Play/Pause button to popup a context menu with some predefined speeds + tempo+ as first, tempo- as last entry?
> 
> A single tempo button popping up above mentioned menu?
> 
> Something like that?

@ksooo  From a quick hack around in the code, this is possible

image

image

If something along those line is worth pursuing then I'll drop tempo from this PR and raise a new PR if doing that way works out.   At first glance some things to work out like why the video in the background dims (this hack used Custom_1101_SettingsList.xml to generate the dialog with the settings).

**Comment by Dnkhatri** [comment]
@jjd-uk  even if it is not implemented in the default skin please dont abandon this  and release it as a mod at least.

**Comment by HitcherUK** [comment]
How about adding it to the settings dialog and then have that open the slider dialog similar to how audio/subtitle offset is handled?

**Comment by jjd-uk** [comment]
> How about adding it to the settings dialog and then have that open the slider dialog similar to how audio/subtitle offset is handled?

Slider is not possible I believe, I was thinking a spincontrolex, but those type of controls are defined by Core I believe. All I've got to work with is PlayerControl(TempoUp) and PlayerControl(TempoDown) for the speed control.  Still learning this skin stuff so perhaps I've missed something,.

**Comment by ronie** [comment]
tested and working ok, using https://github.com/xbmc/xbmc/pull/18182

realtest

**Comment by jjd-uk** [comment]
I've revisited the tempo controls following the feedback and I've new implementation that doesn't require https://github.com/xbmc/xbmc/pull/18182 and as such is not quite what was discussed.

See screenshots below.

Changes:

- New Play speed item on OSD Settings menu, pressing open a new Play speed menu which show a label for the Current speed and 2 controls to increase and decrease the play speed. Having just the 2 controls makes for a more compact and discrete menu than the style ronie tested out using the changes he did for https://github.com/xbmc/xbmc/pull/18182. The other benefit is that the standard range is **x08** to **x1.5** and the range **x1.5** to **x2.1** are only available if the Advanced Setting **maxtempo** is specified.  Using PlayerControl(tempo(n)) for discrete speed button would require further visibility conditions based on Advanced Setting **maxtempo**.

- These menu have been moved to the right hand side so they appear above the Settings button and when in the Play speed menu it mean the video can still easily be view.

- Opacity of black overlay in DialogBackgroundCommons applied over the top of video when a dialog is opened has been reduced from 76% (C2) to 50% (80). I'm not 100% we actually need the overlay at all to provide contrast but I've left it and just changed the opacity to increase visibility of the playing video. My thinking for this was when changing the Play speed user may wish to see the effect it has while either increasing or decreasing play speed.

Video of it in action https://youtu.be/vesI5V1h_O4

image

image

**Comment by jjd-uk** [comment]
I've also added a new setting "Hide button labels" to allow those of us who know what the button do to hide the help labels from the variable **OSDHelpTextVar** .

**Comment by ronie** [comment]
> The **Settings** menu and the new **Play speed** menu are to the right hand side. I did this as I wanted the **Play speed** menu to right as it obscures less important areas of the video for when users are making adjusts to the speed and wish to see effect.

there's no need to re-invent the wheel here ;-)
have a look at the subtitles offset dialog (DialogSlider.xml), and use a similar style/layout for the tempo controls.

something like this:
tempo

**Comment by jjd-uk** [comment]
Will do, wasn't familiar with that control.

**Comment by jjd-uk** [comment]
@ronie I've take a look and I'm not clear what you asking to be done.

Looking at DialogSlider.xml and that only provides for where to place the labels and textures, there's nothing defined for any specific settings. From strings.po I see "Subtitle offset" is id 22006 and doing a search of 22006 reveals it exists only in:

https://github.com/xbmc/xbmc/blob/master/xbmc/video/dialogs/GUIDialogSubtitleSettings.cpp#L271
https://github.com/xbmc/xbmc/blob/master/xbmc/video/PlayerController.cpp#L133

This id does not appear in any of the skin xml files.

So are the settings that make use of slider only defined in C++? or am I missing something fundamental in how skins do this?

**Comment by ronie** [comment]
apologies if my previous reply wasn't clear...

i was suggesting to adopt the style/layout of DialogSlider.xml in your Custom_1110_TempoControl.xml file.

as a starting point, you could use this quick & dirty test code which i used to create the screenshot:
https://github.com/ronie/xbmc/blob/tempo-test/addons/skin.estuary/xml/Custom_1110_TempoControl.xml

**Comment by jjd-uk** [comment]
@ronie Ah right, so not too dissimilar to what I did then, as I based Custom_1110_TempoControl.xml on Custom_1101_SettingsList.xml as that is where it was called from. I'd assumed you were asking for Custom_1110_TempoControl.xml to be removed and to use something in the existing xml's. Thanks for the clarification and your code sample.

**Comment by jjd-uk** [comment]
Latest version pushed.

For tempo control what I've ended up with is how I wanted to do it from the beginning, but had assumed it wasn't possible due to not seeing a way to use dialogslider directly. Thanks to the revelation from @ronie that it was as simple as copying the code into a custom window.

How it looks now

image

image

I've position it to the top to stay out of the way as much as possible to what's occurring in the video.

For consistency I've also adjusted dialogslider to match, what this does for subtitle offset for example

**Before**

image

**After**

image

**Comment by jjd-uk** [comment]
Also some more adjustments for the help labels via **OSDHelpTextVar**

Player control labels removed, e.g. label for Stop icon, as these where introduced when I original had tempo controls among these.

As can be seen in https://github.com/xbmc/xbmc/pull/18155#issuecomment-663866409 I experimented with a setting to disable the labels altogether. My thinking was experienced users do not require the labels, however I've decided it's probably overkill so have removed the setting. I can easily add it back again if others would like it.

**Review by ronie — CHANGES_REQUESTED** [review]
thx, apart from a few minor corrections, this looks good to me.

**Comment by jjd-uk** [comment]
@ronie updated in line with your comments. What's left is the question I pinged you about on Slack regarding the PVR buttons and their use of   `Dialog.Close` and whether they should also be using `Dialog.Close(all, true)`. As I making changes here it's no bother to also change those if wanted, unless they use `Dialog.Close(MusicOSD)` and `Dialog.Close(VideoOSD)` for a specific reason.

**Review by ronie — APPROVED** [review]

**Comment by ronie** [comment]
thx!

**Comment by phunkyfish** [comment]
@jjd-uk I now have these new buttons appears in a catchup TV stream like this in iptvsimple.

Screenshot 2020-08-12 at 09 19 59

But those buttons really clutter the UI and are not so useful as there is a cost to seeking a live catchup stream (as essentially each seek is looking up a new URL). There is also a bug in that when using forward or backward tempo the pause button does not change to a play button which is unintuitive.

Is there a way to disable these buttons for streams where they are not appropriate?

**Comment by jjd-uk** [comment]
@phunkyfish I did wonder about ip catchup services, but there doesn't seem to be any infobool available at skin level to identify those, unless you can point me to something I've missed. As of this PR I was using `Player.SeekEnabled` however it was already identified for normal Live TV that this wasn't good enough so I have a followup PR in progress see https://github.com/xbmc/xbmc/pull/18261 where I propose using `PVR.IsTimeShif` so perhaps you could tell what happens for iptv when using that.

I will take a look at the other things you mention as well and see if there's any changes that can be made and if so I'll also roll them in PR18261.

**Comment by phunkyfish** [comment]
There is no info on catchup iptv as it’s a very select feature. I’m not sure exposing it would make sense as it’s only used on a single addon as a timeshift. Other use cases do not use it for timeshift, instead for playback of pre-recorded shows where tempo makes sense. I’m not sure there is an easy way to tell the skin to display those buttons or not.

**Comment by jjd-uk** [comment]
@phunkyfish sorry but I can't make sense out of what you're trying to say in that last comment. Does or does not using `PVR.IsTimeShift` make any difference???

**Comment by jjd-uk** [comment]
I could of course just hide the rw/ff buttons for Live TV completely, but have been trying to leave them there for cases where they make sense, for example timeshifting so behind live so they can be used to go back & forward in buffer.

**Comment by phunkyfish** [comment]
> @phunkyfish sorry but I can't make sense out of what you're trying to say in that last comment. Does or does not using `PVR.IsTimeShift` make any difference???

No, `PVR.IsTimeShift` would not make a difference.

**Comment by phunkyfish** [comment]
> I could of course just hide the rw/ff buttons for Live TV completely, but have been trying to leave them there for cases where they make sense, for example timeshifting so behind live so they can be used to go back & forward in buffer.

I’m trying to think of use cases where is is useful. I’m just not sure it makes sense for live TV, and if it’s extra buttons on the screen that don’t really work I’m not sure they would add value. Forward tempo makes no sense if the stream is currently live. What I don’t know is which addons might benefit for the tempo buttons where they would work as expected.

**Comment by jjd-uk** [comment]
My thinking was if you were timeshifting then ff could be used during commercials, and rw could be for a sporting event for example to rewatch a goal or other key action. However if we can't be certain of behaviour because of lack of info available to skin then yes hiding might be best.

**Comment by phunkyfish** [comment]
I think users generally just skip back/forward 3, 5, 10 seconds which is quicker with either a remote or keyboard.

**Pull request merged**
