### PR TITLE
[android] Enable DisplayMode API on all devices with Nougat

### PR DESCRIPTION
**Pull request by MartijnKaijser**
It works :)

### CODE REVIEW

**Comment by CiNcH83** [comment]
Display mode API has been added with Marshmallow though.

**Comment by MartijnKaijser** [comment]
Have you actually read the code?

**Comment by koying** [comment]
+1. 
Maybe just remove the whole block for Leia, as we can assume all Shield's will be N by then

**Comment by MartijnKaijser** [comment]
That was certainly my intention in several months :)

**Comment by CiNcH83** [comment]
> Have you actually read the code?

OK, got it. Rule only applies to SHIELD...

**Pull request merged**
