### PR TITLE
[PVR] Guide window: Goto 'now' on system resume from sleep.

### PR DESCRIPTION
**Pull request by ksooo**
This feature was requested several times in the forum.

Runtime-tested on latest Kodi master, macOS.

@Jalle19 @phunkyfish Got time for a quick code review?

Please note that this currently will not work on Android, due to incomplete power management implementation: https://github.com/xbmc/xbmc/blob/master/xbmc/platform/android/powermanagement/AndroidPowerSyscall.cpp#L30 is missing support to signal suspend/resume/... to the provided callback instance. Maybe @peak3d can take a look?

### CODE REVIEW

**Comment by phunkyfish** [comment]
I noticed this myself, although not on suspend/resume just when the TV is switched on (I don’t ever suspend my devices), it just takes the display out of dimming.

**Comment by ksooo** [comment]
> not on suspend/resume just when the TV is switched on

 I don't think power manager provides something for this case:

```c++
class IPowerEventsCallback
{
public:
  virtual ~IPowerEventsCallback() = default;

  virtual void OnSleep() = 0;
  virtual void OnWake() = 0;

  virtual void OnLowBattery() = 0;
};
```

**Comment by phunkyfish** [comment]
Ya, I would need to soak test it. Unless CRC mimics a wake. Not to hard to test for.

**Review by phunkyfish — APPROVED** [review]
Looks good

**Comment by ksooo** [comment]
Jenkins WIN-UWP-64 error is unrelated.

**Comment by phunkyfish** [comment]
It looks like CEC can call wake when deactivating the screen saver so this will most likely work for my use case too 😉

Nice

**Pull request merged**
