### PR TITLE
Add sort by last played for movies

### PR DESCRIPTION
**Pull request by razzeee**
## Description

Seems like you can't sort tvshows by ratings. Not sure why that's absent.

## Motivation and context

https://forum.kodi.tv/showthread.php?tid=363975&pid=3056647

## How has this been tested?

I've done an android build an tested sorting by it on my main kodi machine. Seemed to work fine.

## What is the effect on users?

They can sort by average ratings.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by razzeee** [comment]
Started a jenkins build, should show up shortly

**Comment by KarellenX** [comment]
Thanks @razzeee 

There were two builds, 1 hour apart so I tested the latest one... KodiSetup-20210827-38a8ee62-sortmethods-x64.exe

Using default Estuary, I tested both Last Played in Movies, and Ratings in TV Shows.

Scanned half my library into Kodi and flicked between views, sort methods, asc/desc. When changing sort methods, views correctly displayed the Last Played date or Rating value in the list.

I can see no issue with this PR.

**Comment by ksooo** [comment]
Isn't this PR a duplicate to #19193 ?

**Comment by razzeee** [comment]
Good catch, the first commit is

**Pull request merged**
