### PR TITLE
Updated gitignore

### PR DESCRIPTION
**Pull request by razzeee**
Not sure what to write in the commit.
If someone can put better words to it, just let me know.
- The new .vs folder thats probably a VS2015 thing.

### CODE REVIEW

**Comment by Montellese** [comment]
All the visualization DLLs and the HD HomeRun DLL shouldn't be in `.gitignore` AFAIK because we completely removed them from the code. You can delete them from your local git directory.

**Comment by Razzeee** [comment]
Updated

**Comment by mkortstiege** [comment]
Could you update the actual commit message so it's easier to search for later on?

**Comment by Paxxi** [comment]
I'd rather see the visualizations still being ignored as they'll pop up when switching to an older branch and back

**Comment by MartijnKaijser** [comment]
@Paxxi maybe we should put them at the end of the file as "obsolete, remove later" because if we let them stay in bewteen the rest we will forget to clean it up

**Comment by Paxxi** [comment]
Sounds good

**Comment by Razzeee** [comment]
Like this?

**Comment by Paxxi** [comment]
Exactly @razzeee, thanks

**Pull request merged**
