### PR TITLE
spelling: AptdaemonHandler

### PR DESCRIPTION
**Pull request by jsoref**
## Description

Fix spelling for AptdaemonHandler

## How Has This Been Tested?
- [x] Travis
- [x] AppVeyor

## Types of change
- [x] Spelling

## Checklist:
- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
See
https://github.com/XBMC-Addons/service.xbmc.versioncheck

**Comment by jsoref** [comment]
Ok, so, to do this correctly would require adding the replacement code first and removing the bad code second, and possibly starting in that other repository...

Anyway, I can understand not wanting to do this.

**Comment by MartijnKaijser** [comment]
We also ways use that as upstream and occasionally push to kodi master branch

**Comment by jsoref** [comment]
https://github.com/XBMC-Addons/service.xbmc.versioncheck/pull/8

**Pull request closed without merging**
