### PR TITLE
[fix][win32][depends] Patch taglib to fix regression causing hangs

### PR DESCRIPTION
**Pull request by Paxxi**
should fix #11530 without any complications

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by arnova** [comment]
Are you sure this is a 100% fix? I believe I previously reproduced the issue on Linux with 1.11.1

**Comment by MartijnKaijser** [comment]
It's a patched version with the fix on top

**Comment by Paxxi** [comment]
Yep, that's why the weird name to mean it's 11.1 with that extra commit

**Comment by arnova** [comment]
@Paxxi : Ok, missed that, see it now :)

**Comment by DaveTBlake** [comment]
@Paxxi after testing I can confirm this patch fixes regerssion http://trac.kodi.tv/ticket/17210, and tag scanning of ordinary mp3 files generally seems to be fine as before. Thanks.

**Comment by Rechi** [comment]
shouldn't this also be applied to master?

**Comment by DaveTBlake** [comment]
Pending #11522 (win32 to 1.11.1) could be amended to do that

**Comment by MartijnKaijser** [comment]
Please do so (or create new one)

**Pull request merged**
