### PR TITLE
Clarify choices in Step 5 Build binary add-ons

### PR DESCRIPTION
**Pull request by pteeson**
## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by a1rwulf** [comment]
I think this makes the readme look weird.
While I think it is quite obvious that those are examples and you can choose between them (especially if you actually read the commands), I'd suggest that you add a more verbose explanation before listing them.

**Comment by Memphiz** [comment]
I agree. I would rather start with something:

There are multiple possibilities to choose which addons are built. The following 3 examples will give an idea. 

Or something in that direction

**Comment by Memphiz** [comment]
Crystal clear now. Do you have energy for one last exercise before we merge this? @pteeson 

For keeping the git history clean it is good practice to squash commits into a single commit were applicable.
This can be done like so:
In your working directory:
git rebase HEAD~2 -i
Then the vi editor opens - hit “i” to enable edit mode
Then go to the second line and replace the word “pick” with an “f” (for fixup)
Hit esc then “:wq” and enter.

If you look at “git log” you should see only one commit left.

for updating the PR do
git push -f

**Comment by pteeson** [comment]
All done. Thank you so much for guiding me.

**Comment by Memphiz** [comment]
Thx for going through this so properly and patient :)

**Comment by Memphiz** [comment]
If you want to harden your newly achieved knowledge - there are errors in hat read me in regard to the cmake command.
In the readme it says “cmake -blah blah ../Kodi” which is wrong - last parameter has to be “..” without the “/Kodi” ;)

**Comment by Memphiz** [comment]
And a shortcut to that:
git checkout -b newbranch
git fetch upstream
git reset —hard upstream/master

**Comment by a1rwulf** [comment]
And for completeness, if you ask yourself what we mean by upstream.
Check the remote repos of your working repo:
git remote -v
And if upstream is missing:
git remote add upstream git@github.com:xbmc/xbmc.git

**Comment by pteeson** [comment]
Gandalf:~ pteeson$ cd /Volumes/Data-b/kodi
Gandalf:kodi pteeson$ git remote -v
origin	git@github.com:pteeson/xbmc.git (fetch)
origin	git@github.com:pteeson/xbmc.git (push)
upstream	https://github.com/xbmc/xbmc.git (fetch)
upstream	https://github.com/xbmc/xbmc.git (push)

**Comment by pteeson** [comment]
Pull request is in upstream…..
per email from Memphis re step 6.1 generate Xcode project
#14532 opened 2 minutes ago by pteeson  

Thanks for the guidance… now back to reading the manual.

>

**Pull request merged**
