### PR TITLE
Honor "ignorethewhensorting"

### PR DESCRIPTION
**Pull request by phate89**
I noticed adding a tag that "ignorethewhensorting" wasn't honored on the tv shows list so I searched for other places where the check was missing. 
I'm not sure about json-rpc/AudioLibrary.cpp check because I rarely use music so I don't know if we should check that or not

### CODE REVIEW

**Comment by Montellese** [comment]
Should be good. It might make sense to have a method somewhere that returns the proper `SortAttribute` value depending on the setting instead of having to do it the same way in lots of different places. But that shouldn't block this PR.

**Comment by phate89** [comment]
I actually thought to add a "SortAttributeDefaultArticle" attribute or a specific method to get the right value but since we're close to release this version has more chance to get in Isengard.
I can improve it in this pr if with one of these 2 methods in this pr if you want

**Comment by Tolriq** [comment]
@Montellese 

JSON RPC have a specific list.sort   "ignorearticle": { "type": "boolean", "default": false }

The sorting should not be based on the Kodi settings as it's a big change in API to not have the default to false.

**Comment by Montellese** [comment]
@Tolriq: I haven't tested it explicitly but this change shouldn't affect the output of JSON-RPC. The changes to `AudioLibrary.cpp` only affect the order of the items when e.g. playing all songs of an artist or genre.

Or where (which specific request) do you see a possible issue?

**Comment by Tolriq** [comment]
@Montellese 
It has been a long time since I touch JSON code part :(

Seems I mixed FillFileItemList and HandleFileItemList in my head (Quite similar names :p) if this does not impact basic listing then no problem.

**Comment by Montellese** [comment]
@phate89: I'd leave it like that for now and postpone any improvements to after Isengard has been released (you can obviously already work on it now if you wish).

@MartijnKaijser: This should be good to go for Isengard.

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Pull request merged**
