### PR TITLE
DVDVideoCodecDRMPRIME: update process info in get format callback

### PR DESCRIPTION
**Pull request by Kwiboo**
## Description
This PR adds support for using ~~threads when decoding~~, changes to update process info in get format callback and fixes a potential issue in case v4l2 request api hwaccel fails to init and sw pix fmt is used.

## Motivation and Context
Fixes wrong info in process info dialog (pix fmt, hw/sw) in some cases and prepares for sw decode fallback in case hwaccel fails to init.

## How Has This Been Tested?
Tested on Allwinner and Rockchip devices using LibreELEC and mainline kernel.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Kwiboo** [comment]
Dropped the threaded decoding commit, it caused issues with 4K on Allwinner devices, something to improve in future.

**Comment by lrusak** [comment]
@Kwiboo was the issue with threaded decoding with a hw decoder or sw decoder?

**Comment by Kwiboo** [comment]
I think the issue was memory constraints for hw decoder, with 4k, multiple threads and each thread allocating extra buffers it was too much on the board @jernejsk tested.
Means we probably need to have configuration or algo to determine thread usage.

**Comment by jernejsk** [comment]
@lrusak issue is that too much CMA memory is requested when decoding 4K videos. It seems that ffmpeg makes multiple instances of v4l2_request codec.

**Comment by lrusak** [comment]
> I think the issue was memory constraints for hw decoder, with 4k, multiple threads and each thread allocating extra buffers it was too much on the board @jernejsk tested.
> Means we probably need to have configuration or algo to determine thread usage.

Ah, makes sense. Are we going to be able to set the threading if we are using SW decoding?

> @lrusak issue is that too much CMA memory is requested when decoding 4K videos. It seems that ffmpeg makes multiple instances of v4l2_request codec.

Are you able to decrease the buffer pool size? How much CMA are you currently allocating?

**Comment by jernejsk** [comment]
> Are you able to decrease the buffer pool size? How much CMA are you currently allocating?
ffmpeg already allocates only on-demand, but @Kwiboo might correct me on that one. Currently I set 256 MiB for CMA, but I don't want to increase that. Older AW SoCs are not even capable of using more or even that amount of memory for VPU.

**Comment by lrusak** [comment]
> > Are you able to decrease the buffer pool size? How much CMA are you currently allocating?
> 
> ffmpeg already allocates only on-demand, but @Kwiboo might correct me on that one. Currently I set 256 MiB for CMA, but I don't want to increase that. Older AW SoCs are not even capable of using more or even that amount of memory for VPU.

256MiB should be plenty no? `(256 * 1,000,000) / (3840 * 2160) = ~30` or am I out to lunch?

**Comment by jernejsk** [comment]
You forgot to divide by 1.5 - NV12 has 12 bpp, but that's still 20, which should be enough for all videos. Worst case would be 16 images in DPB and 1 decoding. That still leaves 3 for buffering purposes, if needed. However, I haven't seen video yet which would use 16 reference frames...

**Comment by Kwiboo** [comment]
V4l2 request api hwaccel also allocates 2 mb bitstream buffer for each frame buffer so it adds up, though it was easier to leave threading to a dedicated PR in near future

**Comment by lrusak** [comment]
> You forgot to divide by 1.5 - NV12 has 12 bpp, but that's still 20, which should be enough for all videos. Worst case would be 16 images in DPB and 1 decoding. That still leaves 3 for buffering purposes, if needed. However, I haven't seen video yet which would use 16 reference frames...

Right 😸 



> V4l2 request api hwaccel also allocates 2 mb bitstream buffer for each frame buffer so it adds up, though it was easier to leave threading to a dedicated PR in near future

No problem, just thought I would ask 👍

**Comment by jernejsk** [comment]
ah, true and we must not forget other users of CMA. For example, fbcon also allocates one frame to show console. Some other drivers use it too, but I'm not sure how much.

**Pull request merged**
