### PR TITLE
[video] Modify versions/extras related texts

### LINKED ISSUE #24549: [video] Separate video versions and extras items: not yet fully achieved
## Bug report

As mentioned [here](https://github.com/xbmc/xbmc/pull/24340#issuecomment-1897952095), the dialog heading as well as buttons when choosing to rename or add an extra are still referring to "versions" although the rest of the extra management dialog is already showing the correct localizes.

## Expected Behavior

Extras related dialogs should always use wording referring to "extras", not "versions".

## Actual Behavior

When adding or renaming a movie extra the heading as well as buttons still refer to "versions".

### To Reproduce

Open the extras management dialog, add an extra and rename it.

### Debuglog

Clearly not needed here as this is easily reproducible. Used version of Kodi, etc., see below.

### Screenshots 

297660136-f6605429-5cd6-435d-aacc-ebbeb03278bb

297660492-9e8382c6-ab0f-4fc5-87fa-bfd5fbfb5432

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 22H2, 64-bit
 - Kodi version: 21.0-BETA2 (20.90.821), 20240116-b22539947c

### LINKED ISSUE #24616: Select dialogs for versions/extras no longer have the movie name
### Describe the bug
Header for the version and extra selection dialogs no longer has the movie name.

image

image

## Expected Behavior
Header for the version and extra selection dialogs should have the movie name similar to the manage dialogs.

image

image

We orignally did have this but it got lost in the switch over to dialog select I think.

## Actual Behavior

The movie name in the dialog header was lost when version/extra selection was moved to dialog select.

## Possible Fix
Align with the Manage dialogs and restore movie name.

### To Reproduce
Select movie library item that has versions added.
Select movie library item that has extras added.

### Debuglog
The debuglog can be found here: not relevant [paste.kodi.tv/irrelevant.kodi](https://paste.kodi.tv/irrelevant.kodi)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CrystalP**
## Description

* Changed dialog titles and button captions in the dialog triggered by the Rename action of Versions Manager / Extras Manager to distinguish versions and extras.

* Version or extra renaming: provide the current name as default value for the onscreen keyboard entry when the user presses the "New" button.

* Renamed the Rename button of Versions Manager to Choose type

* Brought back the movie name in the title of the Choose version/extra dialog

## Motivation and context

Fix #24549. Some strings still inappropriately shared between versions and extras.

Also it's annoying to enter names from scratch when the current one is close to what the new entry is going to be. It's easier to delete the unwanted default value than to enter from scratch.

Fix #24616, movie title disappeared in the code restructure of the Choose dialog to use select dialogs

## Screenshots

**Rename dialogs**

Before, both versions and extras show:

image

image

After, rename version:

image

image

After, rename extra:

image

image

**Versions Manager dialog**

Changed text of the button "Rename":
image

**Choose dialog**

Movie title in the dialog title:
image

image

## How has this been tested?

Manage versions and extras, rename to other predefined/already entered name, rename to new name, cancel half-way.

Play movie with versions and extra to check the movie title in title bar

## What is the effect on users?

More consistent experience.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CrystalP** [comment]
@jjd-uk there are text changes you may be interested in

**Comment by KarellenX** [comment]
Terminology looks good to me. Thanks @CrystalP

**Comment by jjd-uk** [comment]
I am wondering if Rename should perhaps be changed to `Choose type` or `Version type`

image

**Comment by jjd-uk** [comment]
Issue created for what I spoke about on Slack https://github.com/xbmc/xbmc/issues/24616 not sure if you might want to address that here or separately.

**Comment by CrystalP** [comment]
Yes I don't like "Rename" either for versions. "Choose type" would do.
For extras since the type is treated like a name today, "Rename" is still fine I think.

**Comment by CrystalP** [comment]
Changed the "Rename" button for versions to "Choose type" - new button id created because with 2 buttons of same id and different visibility, keyboard navigation gets stuck on enabled but invisible button. Core could be changed to skip such buttons but didn't want to risk it in beta.
Fixed #24616 with suggested text, the code was already in place.

**Comment by MikeSiLVO** [comment]
I don't get Rename --> Choose type / Version type or to be blunt "anything" type.

Rename Version/Extra --> I get.
Choose type --> I don't get... Type of what?

Type is now a brand new thing.

I'm not sure introducing a new nomenclature like type makes sense.

Shouldn't the term type be used somewhere else?

**Play type...
Add type...
Choose art for type...
Rename type...
Remove type...
Set as default type...**

The wording seems a tad odd to me...

**Comment by jjd-uk** [comment]
@MikeSiLVO Rename opens the Choose Version Type dialog, which is where you set the name for the version type e.g. Directors Cut. So it now more closely matches the name of dialog, not exactly as Choose Version Type would be a long string for the button. I didn't like rename as what are you renaming? for me it didn't fit purpose of dialog you are opening.

I'm open to hearing anything better we can call dialog and the button to open it.

**Comment by CrystalP** [comment]
I think @MikeSiLVO is referring to the change in this PR from "Choose version" / "New version..." on the "Rename" dialog to "Choose version type" / "New type..." (see before/after screenshots)

Essentially I proposed a change because while "Choose version" as dialog title could work (although not great), "New version..." was weird as the dialog does not create versions.

I proposed adding "type" because the version types/names/whatever are expected to be reused across movies and are not expected to be unique names. I'm not attached to it and am fine switching to "Choose version name" / "New name..." depending on feedback.

For extras there was no question we're talking about a name.

**Review by jjd-uk — APPROVED** [review]
This is a definite improvement IMHO so approving. I'd like to see more feedback before changing the current state here, and best way for that is probably to merge.

**Pull request merged**
