### PR TITLE
do not enable remote control on initialize, respect app params

### PR DESCRIPTION
**Pull request by FernetMenta**
see title, we have to respect app params

### CODE REVIEW

**Comment by Paxxi** [comment]
I left this as the --no-lirc option seemed to be scheduled for removal with the app parser rework. No objections to changing it back though.

**Comment by FernetMenta** [comment]
who said this? it should go the other way round because lirc gets less important over time. most remotes are recognized as keyboards.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
Nobody said it, based it on the work in #6436

**Pull request merged**
