### PR TITLE
[cmake] Spring cleanup aka OCD

### PR DESCRIPTION
**Pull request by hudokkow**
## Description
Spring cleanup, mostly cosmetics

## Motivation and Context
Why not?

## How Has This Been Tested?
Build tested, brief runtime test.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Cleanup

### CODE REVIEW

**Comment by hudokkow** [comment]
jenkins build this with addons please

**Comment by hudokkow** [comment]
jenkins build this with addons please

**Comment by MartijnKaijser** [comment]
needs a rebase

**Comment by hudokkow** [comment]
jenkins build this with addons please

**Comment by hudokkow** [comment]
jenkins build this with addons please

**Pull request merged**
