### PR TITLE
Fix coverity uninit warnings in dialogs and dvdplayer

### PR DESCRIPTION
**Pull request by Paxxi**

### CODE REVIEW

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
ignore osx32 error

**Comment by Paxxi** [comment]
@fritsch can you check that the audio related defaults makes sense?

**Comment by FernetMenta** [comment]
regarding a/v it's initializing members for the sake of making coverity happy. that's ok but I think we should place a comment mentioning that those defaults have no influence on behavior.

**Comment by Paxxi** [comment]
Sure, I'll add some comment for them

**Comment by Paxxi** [comment]
jenkins build and merge

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Comment by MartijnKaijser** [comment]
stubborn jenkins. 
jenkins build this please

**Pull request merged**
