### PR TITLE
Bump Android NDK 25c

### PR DESCRIPTION
**Pull request by joseluismarti**
## Description

Kodi uses a custom build system and set the minimum API level with ANDROID_API macro.

When I build with NDK 25, get the following warning each time the macro is redefined:
```
warning: '__ANDROID_API__' macro redefined [-Wmacro-redefined]
```
We can remove `__ANDROID_API__`  macro as Clang automatically defines the API level based on the Triple (e.g. aarch64-linux-android) and `minSdkVersion`.

In openssl target I propose to disable these warnings with the `-Wno-macro-redefined` flag and next adjust the Makefile.

Other changes:

* Remove the swab patch in samba target. The `swab` function was introduced in Android 28 and NDK 25 adds a backport.

* Update the Android build guide.

## How has this been tested?
arm build tested on Android TV 9 and
aarch64 build tested on an Android 12 phone.

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by joseluismarti** [comment]
This PR requires NDK 25b to be installed in Jenkins

**Comment by lrusak** [comment]
There is an upstream patch for gnutls https://gitlab.com/gnutls/gnutls/-/commit/62f66dfa3343172aad41701e9cc3e1cddd06c2f3

**Comment by lrusak** [comment]
jenkins build this please

**Comment by joseluismarti** [comment]
Thanks, when merge https://github.com/xbmc/xbmc/pull/22304, the proposed gnutls patch will no longer be needed

**Comment by wsnipex** [comment]
don't mind the 2 failed docker builds, they don't use build steps, so built with ndk 21

**Comment by joseluismarti** [comment]
> don't mind the 2 failed docker builds, they don't use build steps, so built with ndk 21

Ok, thanks

**Comment by wsnipex** [comment]
android builds with ndk 25: 
https://jenkins.kodi.tv/view/Android/job/android-arm-docker/675/ 
https://jenkins.kodi.tv/view/Android/job/android-arm64-docker/735/

**Comment by Rechi** [comment]
Android NDK r25c was released about 2 weeks ago.

**Comment by joseluismarti** [comment]
Updated to version 25c, no changes are needed compared to 25b. I've checked that all target triples build fine. Tested on Android TV 9 (armv7a) and works as usual

**Comment by joseluismarti** [comment]
Reopen again since the compilation errors (use of undeclared identifier `ftello`) have been fixed with the latest upstream changes in CMake macros. 

Compiles again and works fine.

**Pull request closed without merging**
