### PR TITLE
[Backport] Harfbuzz rendering support

### PR DESCRIPTION
**Pull request by naseef**
## Description
Backport of #19765

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
I don't think this is a good candidate for a backport, but the final call is up to @DaveTBlake

**Comment by naseef** [comment]
For complex language users( like Indic languages, arabic etc ), this is actually not a *new feature* but a **bugfix**. So IMHO this should be backported

**Comment by thexai** [comment]
I found something is wrong in this code:

https://github.com/xbmc/xbmc/blob/master/xbmc/guilib/GUIFontTTF.cpp#L802-L811

Sometimes `ch` has a value out of bounds of `m_charquick` (array of 2048 elements) 

See:

Captura de pantalla 2021-07-25 173108

I think this is the reason for some random crashes that I am experiencing in master branch recently.

To trigger condition seems help playback a video with SRT subtitles or enable debug info OSD (Ctrl+Shift+O).

Possible "fix" is check for `ch < LOOKUPTABLE_SIZE` although this may hide true root cause.

```c++
  for(int i=0;i<m_numChars;i++)
  {
    if (m_char[i].letter < 255)
    {
      character_t ch = ((m_char[i].glyphAndStyle & 0xffff0000) >> 8) | (m_char[i].glyphIndex);
      if (ch < LOOKUPTABLE_SIZE)
        m_charquick[ch] = m_char+i;
    }
  }
```

or maybe replace

`character_t ch = ((m_char[i].glyphAndStyle & 0xffff0000) >> 8) | (m_char[i].glyphIndex);`

with

`character_t ch = ((m_char[i].glyphAndStyle & 0xffff0000) >> 8) | (m_char[i].glyphIndex & 0xff);`

Thoughts?

**Comment by naseef** [comment]
@thexai Could you please share the font file you are using.?

**Comment by thexai** [comment]
I use Windows 10 and Kodi with default skin in English. No subtitles are needed to reproduce the problem, just play any video and press Ctrl+Shift+O (debug info OSD).

**Comment by naseef** [comment]
There is some issue with the font file in your build. As seen from the screenshothe `glyphIndex` of the letter `f` is returning as 33436 which is a bit odd.  I had changed the logic of caching ascii chars ( letter<255)  with their letter  value instead of the glyph index in this patch 146dcd69ba3bd2af52d7e232708bce91038bd86a . Could you please test whether this patch fixes the issue?

Meanwhile it will be helpful if you can provide the fontfile used in your system  as I cant reproduce the issue in windows 10 64bit build. and if you got time could you please check changing the font and issue persists?

**Comment by thexai** [comment]
Patch replacing `glyphIndex` by `letter` seems fix the issue (I will try it for a longer time).

> Meanwhile it will be helpful if you can provide the fontfile used in your system as I cant reproduce the issue in windows 10 64bit

I don't know which font file Kodi uses, I'm using Kodi with estuary skin and default font/skin settings and Windows 10 x64 in Spanish with default Windows 10 fonts.

**Comment by naseef** [comment]
> I don't know which font file Kodi uses, 

adding
`    CLog::Log(LOGDEBUG, "Successfully loaded fontfile {}({})",  strFontName, strPath);` 
on line 159  (just before `m_vecFontFiles.push_back(pFontFile);` ) of [GUIFontManager.cpp](https://github.com/xbmc/xbmc/blob/master/xbmc/guilib/GUIFontManager.cpp) might help

**Comment by thexai** [comment]
```
INFO <general>:   load skin from: T:\KODI\kodi-build\addons\skin.estuary\ (version: 3.0.9)
INFO <general>:   load fonts for skin...
INFO <general>: Loading skin includes from T:\KODI\kodi-build\addons\skin.estuary\xml\includes.xml
INFO <general>: Loading fonts from T:\KODI\kodi-build\addons\skin.estuary\xml\Font.xml
INFO <general>: Successfully loaded fontfile font10(T:\KODI\kodi-build\addons\skin.estuary\fonts\notosans-regular.ttf)
INFO <general>: Successfully loaded fontfile font12(T:\KODI\kodi-build\addons\skin.estuary\fonts\notosans-regular.ttf)
INFO <general>: Successfully loaded fontfile font13(T:\KODI\kodi-build\addons\skin.estuary\fonts\notosans-regular.ttf)
INFO <general>: Successfully loaded fontfile font14(T:\KODI\kodi-build\addons\skin.estuary\fonts\notosans-regular.ttf)
INFO <general>: Successfully loaded fontfile font27(T:\KODI\kodi-build\addons\skin.estuary\fonts\notosans-regular.ttf)
INFO <general>: Successfully loaded fontfile font37(T:\KODI\kodi-build\addons\skin.estuary\fonts\notosans-regular.ttf)
INFO <general>: Successfully loaded fontfile font45(T:\KODI\kodi-build\addons\skin.estuary\fonts\notosans-regular.ttf)
INFO <general>: Successfully loaded fontfile font60(T:\KODI\kodi-build\addons\skin.estuary\fonts\notosans-regular.ttf)
INFO <general>: Successfully loaded fontfile font_clock(T:\KODI\kodi-build\addons\skin.estuary\fonts\roboto-thin.ttf)
INFO <general>: Successfully loaded fontfile font_flag(T:\KODI\kodi-build\addons\skin.estuary\fonts\notosans-regular.ttf)
INFO <general>: Successfully loaded fontfile font20_title(T:\KODI\kodi-build\addons\skin.estuary\fonts\notosans-regular.ttf)
INFO <general>: Successfully loaded fontfile font32_title(T:\KODI\kodi-build\addons\skin.estuary\fonts\notosans-regular.ttf)
INFO <general>: Successfully loaded fontfile font36_title(T:\KODI\kodi-build\addons\skin.estuary\fonts\notosans-regular.ttf)
INFO <general>: Successfully loaded fontfile font52_title(T:\KODI\kodi-build\addons\skin.estuary\fonts\notosans-regular.ttf)
INFO <general>: Successfully loaded fontfile WeatherTemp(T:\KODI\kodi-build\addons\skin.estuary\fonts\notosans-regular.ttf)
INFO <general>: Successfully loaded fontfile Mono26(T:\KODI\kodi-build\addons\skin.estuary\fonts\notomono-regular.ttf)
INFO <general>:   load new skin...
INFO <general>: Loading custom window XMLs from skin path T:\KODI\kodi-build\addons\skin.estuary\xml
INFO <general>:   initialize new skin...

```

**Comment by naseef** [comment]
I still can't reproduce the issue. Anyway this 146dcd69ba3bd2af52d7e232708bce91038bd86a will fix the issue. I will create a PR

**Pull request closed without merging**
