### PR TITLE
Update the default web interface to fetch manifest.json with credentials

### PR DESCRIPTION
**Pull request by bramp**
## Description

Update the default web interface to fetch manifest.json with credentials

Since Chrome 88, manifests.json are fetched without http credentials. Since Kodi encourages the use of a password, the manifest.json ends up returning a HTTP 401 error.

Add `crossorigin="use-credentials"` will enable chrome to successfully fetch this file.

## Motivation and context

Without it the manifest.json file fails to be fetched.

Screenshot 2024-04-13 at 11 35 32 AM

## How has this been tested?

On my local deployment, I just edited the index.html and tested with my browser.

## What is the effect on users?

Fixes a error in the Chrome console.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by enen92** [comment]
Thanks for the patch but please send this upstream to https://github.com/xbmc/chorus2

**Comment by bramp** [comment]
doh, sure! For future reference, did I miss some instructions that pointed me upstream? Or some way to avoid this confusion in future?

**Comment by enen92** [comment]
If contributing to addons that we actually bundle with Kodi please always check the source tag in the addon.xml (manifest) of the addon: https://github.com/bramp/xbmc/blob/7c4d93821dcf99147a90a2acd5085b884a2b4f62/addons/webinterface.default/addon.xml#L13

**Comment by bramp** [comment]
This is my first contribution, so thanks for the pointer.

**Pull request closed without merging**
