### PR TITLE
[musicdb] enable the library via xml

### PR DESCRIPTION
**Pull request by mkortstiege**
This enables the the music library nodes to be defined via xml just as we're already doing for the video library.

@Montellese for review please. Btw, I could need some smart playlist help so we can group by first letter. It's not really related to this PR but would come handy to have something like a flat and full blown library to choose from ;)

### CODE REVIEW

**Comment by mkortstiege** [comment]
jenkins build this please.

**Comment by SpaceAgeHero** [comment]
Is there any documentation on how this could be used?
Can own branches be created from (custom) tags?

**Comment by mkortstiege** [comment]
@SpaceAgeHero correct, this will allow you to create custom (smartplaylist-based) nodes. See http://kodi.wiki/view/Video_nodes for more information. Please create a forum thread in case you have more questions.

**Comment by Montellese** [comment]
Looks good AFAICT. Now we only need the unification of library and files view for music and it should be much closer to the video library ;-)

**Comment by mkortstiege** [comment]
> Looks good AFAICT. Now we only need the unification of library and files view for music and it should be much closer to the video library ;-)

Hehe, one at a time. I still wonder myself that i touched the music library ;p

**Comment by mkortstiege** [comment]
@MilhouseVH mind adding this to your builds so we get some pre-testing before merging?

**Comment by MilhouseVH** [comment]
Sure no problem, will be in the next build.

**Comment by zag2me** [comment]
Brilliant, been waiting for this... Tested and everything works as before with music. Tested top 100, singles, mvids ect. Also tested copying the year node and works as it should. Had some trouble with this test node, maybe user error though:

<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<node order="6" type="filter">
<label>Test Node</label>
<content>music</content>
<match>all</match>
<rule field="artist" operator="contains"><value>Faithless</value></rule>
</node>

screenshot000

**Comment by Montellese** [comment]
@zag: the `<content>` tag needs to contain `artist` (or `artists` I'm never sure).
The error message is very stupid and we use it in a lot of places ;-) Maybe we should fix that (in a separate PR).

**Comment by zag2me** [comment]
Sweet! Yeh ```<content>artists</content> works.

Thanks working nicely!

**Comment by zag2me** [comment]
@mkortstiege regarding the first letter filter, I think we would need sub nodes for that to be useful. Not sure if that is possible yet? So it would be: Artists >> A >> Artist list beginning with "A"

**Comment by mkortstiege** [comment]
@zag2me possible but i'd like to have it dynamic instead of creating a to z nodes ;)

**Comment by Montellese** [comment]
You can group nodes into directories as we already do it for the video library. But right now having these alphabetically grouped nodes would require an XML per character so not very easy to handle.

That reminds me: Doesn't top 100 contain two sub-nodes? Why aren't they represented with XML files? IMO we should provide an XML file for every "virtual" node.

Another thing that I wanted to try for a while now is use a single root smartplaylist which contains the sub-nodes as virtual folders (which in turn are smartplaylists again). That way we could provide a set of default smartplaylists which reference each other to build the library structure. That way users could edit any of these sub-nodes using the smartplaylist editor and adjust it to their liking. But obviously that's something for another day/week/month. It e.g. doesn't support icons or normal paths like "special://musicplaylists/".

**Comment by mkortstiege** [comment]
Jep, that's what i meant with i'd like to have it dynamic. Will check `Top 100`  and `Music Vidoes` as this one is lacking the sub nodes as well.

**Comment by mkortstiege** [comment]
Updated. `Top 100` and `Music videos` are now xml based as well.

**Comment by Montellese** [comment]
Yup looks better now.

**Comment by mkortstiege** [comment]
Updated. Added `HasContent(Music)` checks in preparation of `Library Mode` removal and nuked the extra search node in favor of the regular search function from the (side) menu.

**Comment by mkortstiege** [comment]
Files node needs to be removed if we decide to get this in before removing the library/files toggle (which i would prefer).

**Comment by MilhouseVH** [comment]
This needs a small rebase after https://github.com/xbmc/xbmc/commit/abc968a44ac9e8c999a807d26be23a27ab64e1c4

**Comment by mkortstiege** [comment]
Updated and rebased. I've removed the `Files` node for now as this required more work that's not directly related to replacing the current nodes with the xml ones.

**Comment by zag2me** [comment]
Just tested latest build and seems to work as expected

**Comment by mkortstiege** [comment]
Moved it inside the loop and rebased.

**Comment by xhaggi** [comment]
thanks now everything look good IMO.

**Comment by mkortstiege** [comment]
Updated.

**Comment by mkortstiege** [comment]
jenkins build this please

**Comment by mkortstiege** [comment]
If no one objects I will merge this one the other day.

**Comment by zag2me** [comment]
+1 from me.

Working well and a pretty huge feature for us with larger music collections.

**Comment by mkortstiege** [comment]
Rebased. jenkins build and merge.

**Pull request merged**
