### PR TITLE
Update ArchSetup.cmake for Raspberry Pi4

### PR DESCRIPTION
**Pull request by drwulsen**
## Description
Added Cortex-A72 to initially support Raspberry Pi4
Specifying -DCPU=cortex-a72 to CMake will result in cortex-a7 being used for CFLAGS;
regardless of this modification being in place or not.
elseif(CPU MATCHES "cortex-a7") will be true on the cortex-a72;
so it has to come after the if(CPU STREQUAL "cortex-a72")<br>
On my Raspberry Pi4 this leads to the correct CFLAGS below being added to CFLAGS:
-mtls-dialect=gnu -fPIC -mcpu=cortex-a72 -mfloat-abi=hard -mfpu=neon-vfpv4 -mvectorize-with-neon-quad -D_ARMEL -DTARGET_RASPBERRY_PI -Wall

## Motivation and Context
I just got my Raspberry Pi4 4GB today and first thing after checking the proper -mcpu and -mfpu is to have kodi running at full speed on the Cortex-A72

## How Has This Been Tested?
By compiling directly on the Raspberry Pi4 and running Kodi on it as well.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
As far as I understand you cannot use RPi platform in Kodi for the RPi4. Maybe @popcornmix can chime in.

**Comment by drwulsen** [comment]
> As far as I understand you cannot use RPi platform in Kodi for the RPi4. Maybe @popcornmix can chime in.

Hi Irusak, with the patch you can do that.
I am happy, as everything works as it should, my kodi is optimized for the Cortex-A72 and all that was needed was a change to ArchSetup.cmake.

So this change was intended to be reviewed by some kodi authority (like popcornmix, that'd be an honour) and then either be merged or implemented in some other way.

The change I made allows to specify -DCPU=cortex-a72 to be detected and used correctly; whilst not breaking anything for -DCPU=cortex-a7

Hope I could clarify my intent here.

**Comment by popcornmix** [comment]
Can you explain what commands you entered to build kodi?
The default rpi platform will use windowing/rpi using dispmanx for GL window surfaces which won't work on Pi4.
See: https://github.com/xbmc/xbmc/pull/16324

**Comment by drwulsen** [comment]
> 
> 
> Can you explain what commands you entered to build kodi?
> The default rpi platform will use windowing/rpi using dispmanx for GL window surfaces which won't work on Pi4.
> See: #16324

cmake -C /var/tmp/portage/media-tv/kodi-18.3-r1/work/kodi-18.3_build/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -Ddocdir=/usr/share/doc/kodi-18.3-r1 -DENABLE_LDGOLD=OFF -DENABLE_ALSA=yes -DENABLE_AIRTUNES=no -DENABLE_AVAHI=no -DENABLE_BLUETOOTH=no -DENABLE_BLURAY=no -DENABLE_CCACHE=OFF -DENABLE_CEC=yes -DENABLE_DBUS=no -DENABLE_DVDCSS=no -DENABLE_INTERNAL_CROSSGUID=OFF -DENABLE_INTERNAL_FFMPEG=no -DENABLE_INTERNAL_FSTRCMP=OFF -DENABLE_CAP=no -DENABLE_LCMS2=no -DENABLE_LIRCCLIENT=no -DENABLE_MARIADBCLIENT=yes -DENABLE_MYSQLCLIENT=no -DENABLE_MICROHTTPD=yes -DENABLE_MYSQLCLIENT=no -DENABLE_NFS=yes -DENABLE_OPENGLES=yes -DENABLE_OPENGL=no -DENABLE_OPTICAL=no -DENABLE_PLIST=no -DENABLE_PULSEAUDIO=no -DENABLE_SMBCLIENT=no -DENABLE_UDEV=yes -DENABLE_UPNP=no -DENABLE_VDPAU=no -DENABLE_XSLT=no -Dlibdvdread_URL=/var/tmp/portage/media-tv/kodi-18.3-r1/distdir/libdvdread-6.0.0-Leia-Alpha-3.tar.gz -Dlibdvdnav_URL=/var/tmp/portage/media-tv/kodi-18.3-r1/distdir/libdvdnav-6.0.0-Leia-Alpha-3.tar.gz -DWITH_FFMPEG=yes -DCORE_PLATFORM_NAME=rbpi -DPLATFORM=raspberry-pi -DWITH_CPU=cortex-a72 -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/media-tv/kodi-18.3-r1/work/kodi-18.3_build/gentoo_toolchain.cmake  /var/tmp/portage/media-tv/kodi-18.3-r1/work/xbmc-18.3-Leia

It did build fine, however the real test needs to be done in a day or three, once my micro-hdmi cable arrives. the pi would not start kodi (even the pi3) without anything plugged into the hdmi at boot time.
So I'll come back once the GUI could be tested.

**Comment by wsnipex** [comment]
that might run, but no hardware decoding.

**Comment by popcornmix** [comment]
> How Has This Been Tested?
By compiling directly on the Raspberry Pi4 and running Kodi on it as well.

> It did build fine, however the real test needs to be done in a day or three, once my micro-hdmi cable arrives. 

So it's not been tested...

**Comment by drwulsen** [comment]
it's been tested to start, but not the gui yet....
sorry, there was much euphoria about the pi4.

i'll come back in a day or three to let you know about the gui.

popcornmix <notifications@github.com> schrieb am Do., 4. Juli 2019, 16:52:

**Comment by lrusak** [comment]
> it's been tested to start, but not the gui yet.... sorry, there was much euphoria about the pi4. i'll come back in a day or three to let you know about the gui.

We already stated that using `-DCORE_PLATFORM_NAME=rbpi` won't work for the RPi4.

**Comment by drwulsen** [comment]
please close this if you wish, as i just sold all my pis and migrated to a nuc - so i won't be able to tinker on it.

**Pull request closed without merging**
