### PR TITLE
[platform] - refactor platform code location

### PR DESCRIPTION
**Pull request by Memphiz**
This refactors all platform related stuff into a platforms subdirectory. This also gets rid of the "main" dir in favor of that platform dir.

All in all it is a redone backport of what mrmc did. Its needed in preparation for having at least a chance to backport platform support (f.e. atv4) to kodi.

I hope we can get this in without to much of rebase trouble on my side.

I need an ack from a @afedchin or @Paxxi for windows, @koying for android, @popcornmix for rbpi, @wsnipex for linux.

Especially all those windows project changes were done with a text editor and someone needs to ensure that the platform dir is hooked up properly and the main dir is gone from the project.

I also payed some attention to not break unit tests. Will do a manual jenkins run for this once the platform devs ack'ed the general approach. Basically its a "simple" filesystem reshuffle.

### CODE REVIEW

**Comment by wsnipex** [comment]
looks ok

**Comment by afedchin** [comment]
I'll check this in morning.

**Comment by koying** [comment]
> All in all it is a redone backport of what mrmc did. Its needed in preparation for having at least a chance to backport platform support (f.e. atv4) to kodi.

If it can make your life easier, fine by me, although I'd surely have challenged the usefulness otherwise ;)

jenkins build this please

**Comment by Memphiz** [comment]
Some headage from the videoplayer PR - i think i did some conflict resolving wrong ... back to the drawing board...

**Comment by Memphiz** [comment]
jenkins build this please - there where some old includes of darwinutils on hwdecrendererIMX and AML i removed ... (not sure where they came from - maybe C&P during the videorenderer PR)

**Comment by Memphiz** [comment]
looks much better - kicked a build with built unit tests here:

http://jenkins.kodi.tv/view/Helpers/job/TestMulti-All/438/

**Comment by Memphiz** [comment]
@FernetMenta building the test-suite is broken since your big PR ...

**Comment by Memphiz** [comment]
at least for linux and osx

**Comment by Memphiz** [comment]
For this PR - unit tests compile and work now for osx and win32:

http://jenkins.kodi.tv/job/OSX-64/6520/

http://jenkins.kodi.tv/job/WIN-32/6950/

The compile issue of the test suite for linux seems unrelated to my PR. The non working unit tests for osx are related to a former ae refactor - needs to be fixed in seperate PR.

**Comment by Memphiz** [comment]
a word from the windows devs if that project file looks sane?

**Comment by Razzeee** [comment]
Should those align perfectly or is it okay, if stuff is missing in the plarform folder?

image

**Comment by Memphiz** [comment]
this looks very perfect - thx for confirmation - will merge after rebase...

**Comment by Memphiz** [comment]
jenkins build and merge

**Pull request merged**
