### PR TITLE
[skins] allow vendors to supply their own logo

### PR DESCRIPTION
**Pull request by ronie**
load vendor specific artwork from special://xbmc/media/ instead of including it in our skins.
this will make it easier for third parties to rebrand kodi.

ref: https://github.com/xbmc/devcon/issues/44

@keithah @samnazarko

### CODE REVIEW

**Comment by Rechi** [comment]
jenkins build this please

**Comment by Rechi** [comment]
@ronie please always set the milestone before or right after merging a PR.

**Comment by ronie** [comment]
ok, will try to remember

**Comment by ksooo** [comment]
:-)

**Pull request merged**
