### PR TITLE
[Android][cmake] adjust macros according to the API we are targeting

### PR DESCRIPTION
**Pull request by joseluismarti**
## Description
As we're targeting API level 21:

Requires the `_LARGEFILE_SOURCE` macro to be used to make `fseeko` and `ftello` available. It would not be necessary from API level 24 onwards.

Does not require the `_LARGEFILE64_SOURCE` macro to be used to make `off64_t` and corresponding functions available. These functions are available in the NDK at the current API level.

Also does not require the `_FILE_OFFSET_BITS=64`, these counterpart functions have been progressively incorporated into the NDK.

The `__USE_FILE_OFFSET64` macro is the internal flag that should never be set by user code.

## How has this been tested?
I've tested it on Fire TV (32 bits) and it works as usual, it plays files larger than 2GiB correctly.

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [X] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by joseluismarti** [comment]
I've tried reverting the commit locally and there is no difference in seeking performance when playing a video via SMB. Tested on Android armv7.

I don't think this is the cause, we will have to do more tests or wait for more feedback.

**Comment by neo1973** [comment]
@joseluismarti: Could you upload your local build somewhere so @MishaIsay could try it on their setup? Just to make sure this isn't the issue.

**Comment by joseluismarti** [comment]
A [test apk](https://drive.google.com/file/d/1fp0n7M5wP2rGtvJlCJ2YU6Obp5r_LSJe/view?usp=sharing) with the revert of this commit in case anyone needs to do some testing.

As the signature is different you must uninstall Kodi first. If necessary make a backup since uninstalling deletes everything.

**Comment by MishaIsay** [comment]
Seeking in that build works correctly.

**Pull request merged**
