### PR TITLE
Add section about end-user impact to PR template

### PR DESCRIPTION
**Pull request by yol**
As discussed on the team meeting, let's try to add a section about end-user impact to the PR template so we have something to base blog posts (and, possibly, changelog/release notes in the Wiki) on. Comments welcome.

### CODE REVIEW

**Review by garbear — APPROVED** [review]
I like the verbaige of the new section, and the unrelated grammar changes are welcome.

**Review by enen92 — APPROVED** [review]

**Review by lrusak — APPROVED** [review]
LGTM

**Review by KarellenX — APPROVED** [review]

**Comment by yol** [comment]
I think it has been sitting long enough, thanks for the reminder!

**Comment by KarellenX** [comment]
Thanks @yol 

What are your thoughts on an _**End-User**_ label.

When the **What is the effect on users?** section is filled, the label is also applied. It will make it easier to find all those PR's for the write-ups.

**Comment by yol** [comment]
We could try that, but would people remember to actually apply it? Or would we want the bot to auto-apply it?

**Comment by KarellenX** [comment]
auto-apply sounds more reliable

**Pull request merged**
