### PR TITLE
Backport _ADDITIONAL_BINARY

### PR DESCRIPTION
**Pull request by peak3d**
## Description
backport functionality from K18 to allow additional binary-addon-file to be installed

## Motivation and Context
ssd_wv.dll is currently not installed in kodi17 builds

## How Has This Been Tested?
untested

## Types of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by hudokkow** [comment]
Just so I can keep track, original commit being backported is https://github.com/xbmc/xbmc/commit/d43f637e9c4dbd8c7fb19ec11222601bcda507f7

@peak3d, what am I missing? Why is this needed now, 3 point releases after Krypton?

**Comment by peak3d** [comment]
I spend some tme (~3 days) in backporting my master things from inputstream.adaptive to the Krypton branch and we spend now some time to get it compiled / running for krypton.

I would be very happy if this time of some of us was not for nothing, Understandable?

**Comment by Rechi** [comment]
@peak3d If this should be a backport of d43f637, you have to explain why the logic was added 3 times in the original commit and it is only needed once in the backported version.

**Comment by Rechi** [comment]
backports #12423

**Review by Rechi — APPROVED** [review]

**Comment by hudokkow** [comment]
@peak3d I guess it's OK if it's needed. Thanks for the explanation about the why.

**Pull request merged**
