### PR TITLE
Bump depends

### PR DESCRIPTION
**Pull request by wsnipex**
first iteration to bump important libs to current versions.

needs sanity checks, proper testing and possibly some platform love.

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by koying** [comment]
Using it daily. No issues but I guess I should do specific tests, notably ssh/nfs

**Comment by Memphiz** [comment]
trying that osx64 testbuild you linked - can you think of anything that could have broken PIL with this PR? Or is that testbuild outdated?

File "/Users/memphis/Library/Application Support/Kodi/addons/weather.openweathermap.extended/default.py", line 9, in <module>
                                                from PIL import Image
                                            ImportError: No module named PIL

**Comment by wsnipex** [comment]
that build is a little outdated, but I see no reason why PIL would be broken. I didn't touch python yet ;)

**Comment by wsnipex** [comment]
rebased and removed a comment, jenkins build this please

**Comment by Memphiz** [comment]
@wsnipex aborted the build (just in time) ... there is something to do for ios (even if it compiles with current jenkins slave - it does not for me with current toolchain which is a blocker :D).

**Comment by Memphiz** [comment]
@wsnipex can't do a pr to your repo - please cherry-pick + squash top commit from:

https://github.com/Memphiz/xbmc/commits/bump-deps

**Comment by Memphiz** [comment]
quick test on osx and ios was ok - fine by me once you pulled my compile fix in :)

**Comment by wsnipex** [comment]
Danke :) added and squashed. Jenkins build this please

**Comment by Memphiz** [comment]
case sensitive jenkins build this please

**Comment by wsnipex** [comment]
meh, another unrelated win32 error. jenkins build this please

**Comment by Memphiz** [comment]
this is not a unrelated error! - it has something to do that the slave caches the downloaded packages maybe ...

**Comment by Memphiz** [comment]
i have wiped out the workspace and triggered a windows only build for this pr:

http://jenkins.kodi.tv/job/WIN-32/3116/

**Comment by Memphiz** [comment]
its green on windows now

**Comment by wsnipex** [comment]
will merge this in 12h

**Pull request merged**
