### PR TITLE
VideoPlayer: ffmpeg, ignore pics before first key frame

### PR DESCRIPTION
**Pull request by FernetMenta**
fix for http://trac.kodi.tv/ticket/16803

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by MilhouseVH** [comment]
Looks good, thanks.

**Comment by axbmcuser** [comment]
Tested 15+ files which were affected before - 0 problems now. All thumbnails and chapter images are clean.

**Comment by FernetMenta** [comment]
thanks for feedback. jenkins had issues but travis is good enough for this simple changes.

**Pull request merged**
