### PR TITLE
[Alpha1] bump version code and addon api for v20 alpha1

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Version bump for Alpha 1 release

## Motivation and context
Release Alpha 1

## What is the effect on users?
Release

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by garbear** [comment]
You're off-by-one in the title (I so dearly hope)

**Comment by garbear** [comment]
Should this step have occurred as part of https://github.com/xbmc/xbmc/pull/19256? Or is this separate PR desirable?

**Comment by fuzzard** [comment]
our "standard" practice for alpha versioning os x.90.701 with the info provided, and the github history. This brings us back to that for an actual release

**Comment by garbear** [comment]
Right, so I'm saying that the v21 version of https://github.com/xbmc/xbmc/pull/19256 should do what you did here (use 7 instead of 1)

**Comment by fuzzard** [comment]
Sure, thats an option. i dont think it matters too much. We can consider 101 as pre-alpha, and as we move into alpha we do the bump to 701. Its not a complicated PR when it comes down to it, and gives a clear distinction. But i dont really care either way to be honest.

We've got a few months for the peanut gallery to pipe up with their opinions, so can deal with that then ;)

**Comment by basilgello** [comment]
Will there be 20.0a1 tag?

**Comment by DaveTBlake** [comment]
Not sure why you did this @fuzzard since we already had the version bump to alpha in https://github.com/xbmc/xbmc/pull/19256 and 19.90.101.  It is the Git tag that marks the release not the version bump.

For future there: is nothing magic about "701". What matters is there is space for Matrix backports, and that alpha2 increments by more than 2 for the Android builds.

Also although it looked like we always bump ADDON_API same as VERSION_CODE, this is not the case. Check with @AlwinEsch

**Pull request merged**
