### PR TITLE
Minors from RetroPlayer branch

### PR DESCRIPTION
**Pull request by garbear**
I mentioned at DevCon that I've been carrying a handful of minor fixes and improvements. These are the ones that are ready to be merged (pending review)

Not included is 3413c15 and 66e8acd (already pushed those two to master)

### CODE REVIEW

**Comment by mkortstiege** [comment]
What @Montellese said. I'd remove the currently unused functions and handle them in the actual PR that is adding this functionality.

**Comment by Tolriq** [comment]
@garbear since you start merging things I suppose needs are clear, any luck to describe what would be missing from Event Server to be supported as a RetroPlayer controler ? ( you mentionned some thing when asked in thread but maybe a complete list / design could help)

Custom layout controllers on phones could be great :)

**Comment by garbear** [comment]
@Tolriq Event Server just needs a "button unpressed" event IIRC. It sends "button down" but no "button up"

**Comment by Tolriq** [comment]
@garbear Well it does support it as there's flags for down and up (down by default but clients can send both)

I'm in the middle of moving to a new home so can't really test further before a large month, but I'll ping you back on retroplayer forum to see if it's a bug in EventServer or not, as I've played with it long time ago to fix support for Unicode it should not be hard to fix this too.

**Comment by garbear** [comment]
OK. The proper way forward may be to implement this as a binary add-on

**Comment by garbear** [comment]
Dropped the three "add" commits

**Comment by mkortstiege** [comment]
jenkins build this please.

**Comment by hudokkow** [comment]
All is fine. <code>screensaver.matrixtrails</code> continues acting up

**Comment by garbear** [comment]
Note: The commit [addons] f32483d could break any binary add-ons that rebase on this (VFS addons, content binary add-ons, anything else?) I've taken care of this for peripheral add-ons and game add-ons, obviously. Just something for other binary add-ons authors to be aware of

**Comment by hudokkow** [comment]
Unless I'm missing something, jenkins seems happy. Which addons could be affected by this?

**Comment by MartijnKaijser** [comment]
good for merge?

**Comment by garbear** [comment]
yup. The people I were referring to earlier are @notspiff and @opdenkamp and possibly others. 619ad9d and f32483d are changes you have to take into account on your next rebase. just a heads up

**Pull request merged**
