### PR TITLE
[Infomanager + Confluence] add IsCollection infolabel + related skin changes for list views

### PR DESCRIPTION
**Pull request by phil65**
Credits to @mkortstiege for the core changes.

### CODE REVIEW

**Comment by ronie** [comment]
nice, looks ok to me.

**Comment by phil65** [comment]
ok. Squash?

**Comment by ronie** [comment]
yeah, would be nice.

**Comment by mkortstiege** [comment]
Please pick mine :)

**Comment by phil65** [comment]
@ronie, @mkortstiege 
done.

**Comment by phil65** [comment]
do we want those icons  for moviesets node? ( = Container.Content(sets) ? ) They would all have the same icon, not sure which approach to take. Either consistency or removing redundant information.

**Comment by phil65** [comment]
@da-anda what would you prefer?

**Comment by uNiversaI** [comment]
Fantastic, speechless :)

**Comment by mkortstiege** [comment]
I wonder if there's need for media type based conditions. If so, we could make it `Listitem.IsMediaType(<type>)` based on media types found at https://github.com/xbmc/xbmc/blob/master/xbmc/media/MediaType.h#L28-L39.

**Comment by da-anda** [comment]
@phil65 what do you mean with "do we want those icons for moviesets node"? You mean instead of the thumbnail?

**Comment by phil65** [comment]
do you want to have that small icon displayed for every single movie set while in videodb://movies/sets ?

**Comment by da-anda** [comment]
if they show up ATM because of the current change, fine with me. If not, also fine with me :) I really have no preference here - there a pros and cons for both cases.

**Comment by phil65** [comment]
ok, then this PR should be good to go.

**Comment by MartijnKaijser** [comment]
jenkins build this please
@ronie please merge when you're happy with it

**Pull request merged**
