### PR TITLE
[Music]Automatically fetch any art type for artists and albums

### PR DESCRIPTION
**Pull request by DaveTBlake**
This extends the way thumbs and fanart (artists only) are currently handled to apply to _any_ music art type. It makes fetching additional art, from local files or scraper results, configurable rather than hard coded. This means showing additional art, such as "clearlogo" or "discart" or anything else people may dream up in the future, will just be a matter of either putting the image file in an appropriate place, or the scraper returning the URL for it ,  and then editing the skin.

It applies to:

1. Manual album and artist art selection (from the album/artist information dialog)
 When browsing for images for an art type the user will be offered related local images and scraper results.

2. Library update and refreshing additonal information 
Both scanning music files and scraping additional artist or album information will check for local art or failing that try to use srcaper results to fill any art that is missing.

This is both a logical continuation of recent music art enhancements, and something requested by users and skinners. 

I will put up a test build, and instructions for using/testing this feature will follow shortly. I appreciate anyone with an extensive collection of music and local artwork, especially additional types of art that would previously need addons such as CDart, Artwork Beef or Skin Helper Service, trying this out.

### CODE REVIEW

**Comment by rmrector** [comment]
Wonderful!

Can these be configured as regex to match several files without listing each one? One particular usage would be for for multi-disc albums stored _without_ subfolders with artwork names like 'discart1.png' and 'discart2.png' and so on, which would be named to match the same disc number that this would assign. Another is fanart, I've been stuffing a bunch in the library as 'fanart1' and 'fanart2' and so on for a slideshow like 'extrafanart' in the video library.

**Comment by zag2me** [comment]
Will this scrape local artwork that perhaps isn't wanted? Things such as proof jpegs and booklet images?

**Comment by DaveTBlake** [comment]
>Can these be configured as regex to match several files without listing each one?

With this initial implementation no. Being able to map a wide variety of filenames to an art type - as we can with both thumbs and fanart (in music) - seemed an unncessary complexity. Also the way the filename for thumbs or fanart is configured, having to add every case and file extension variation, is cumbersome. No wish to replicate that.

> One particular usage would be for for multi-disc albums stored without subfolders with artwork names like 'discart1.png' and 'discart2.png' and so on, which would be named to match the same disc number that this would assign. 

The current implementation automatically handles art in disc subfolders called <art type>.png (or any other image ext) . However it can  be configured to pick up "discart1", "discart2" etc. from the album folder by simply adding those as art types to the advancedsettings.xml

>Another is fanart, I've been stuffing a bunch in the library as 'fanart1' and 'fanart2' and so on for a slideshow like 'extrafanart' in the video library.

Likewise, add "fanart1" and "fanart2" etc. to the advancedsettings.xml
The joys of configurable art types :)

That is to make it clear for everyone that the current implementation can handle those situations. You are asking for adding that kind of configuration to be made less tedious by using regex, and that is something that could be added later sure. But again not sure full regex is want, just a number at the end.
I would consider more complex mapping of filename to arttype

**Comment by DaveTBlake** [comment]
>Will this scrape local artwork that perhaps isn't wanted? Things such as proof jpegs and booklet images?

No, that is the point of the whitelist, what image files get used is limited and randon junk cluttering your music files or Artist Information Folder will not be picked up.

**Comment by DaveTBlake** [comment]
This has received some user testing and all positve feedback so far. I plan to merge on Sunday unless there are any objections.

**Pull request merged**
