### PR TITLE
Fix formatting of class enums

### PR DESCRIPTION
**Pull request by Paxxi**
## Description

Fixes the issue reported by Montellese and adds
some tests for it.

Also cleans up a define that was missed for UWP

## Motivation and Context

formatting was broken

## How Has This Been Tested?

Manual verification that unit tests behave as intended

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Review by Montellese — APPROVED** [review]
That's a pretty clever solution. Maybe you should post it in https://github.com/fmtlib/fmt/issues/391 as well.

**Comment by Paxxi** [comment]
not a bad idea, I'll go and do that 😄

**Comment by Montellese** [comment]
Hm unfortunately this doesn't seem to fix the problem we are having in `CDatabaseUtils`. I debugged the code `StringUtils::Format("movie_view.c%02d", VIDEODB_ID_TITLE)` and your `operator<<()` is properly called for e.g. `VIDEODB_ID_TITLE` but the result still is `"movie_view.c0"` instead of `"movie_view.c00"`.

**Comment by Paxxi** [comment]
Does it work if you change it to `StringUtils::Format("movie_view.c{:02d}", VIDEODB_ID_TITLE)`?

Curious if it's an issue with the sprintf stuff in fmt

**Comment by Montellese** [comment]
Then I get a `fmt::v6::format_error` exception. You can easily reproduce the issue by using the Global Search add-on. It will try to retrieve all movies, tvshows, episodes and music videos by title and all of these will result in invalid formatting and therefore invalid SQL queries.

**Comment by Paxxi** [comment]
Thanks for testing, I'll try and dig into it tomorrow 😀

**Comment by Paxxi** [comment]
Ok so this is what I've found. fmt classifies the parameters in categories, integral, arithmetic and so on. When it parses the width specifier it checks if the type is arithmetic at https://github.com/fmtlib/fmt/blob/1f1b50707c8f56095481e29594b0da24431f82d5/include/fmt/printf.h#L491 and if it isn't then it ignores the width. Enums are classified as `custom_type` and fails the check for `is_arithmetic_type`.

That appears to be the reason for the behaviour you're seeing, now to figure out a fix for it other than changing the enum to `constexpr int` 😄

**Comment by Montellese** [comment]
Maybe implement a fmt::basic_formatter for enums? No idea how involved that is though...

**Comment by MilhouseVH** [comment]
>  but the result still is "movie_view.c0" instead of "movie_view.c00".

Is there a fix for this? It's affecting the JSON-RPC query `GetMovies`, where the db query is now mangled ie:
```
{"jsonrpc": "2.0", "params": {"sort": {"order": "ascending", "method": "title"}, "filter": {"operator": "contains", "field": "title", "value": "zombieland"}, "properties": ["title", "art", "file"], "limits": {"start": 0, "end": 400}}, "method": "VideoLibrary.GetMovies", "id": "libMovies"}
```
which results in the following database query:
```
2020-03-01 14:12:43.002 T:1283   ERROR: SQL: [MyVideos116] Undefined MySQL error: Code (1054)
                                            Query: select * from movie_view  WHERE ((movie_view.c0 LIKE '5mbieland%'))
2020-03-01 14:12:43.002 T:1283   ERROR: GetMoviesByWhere failed
```
(similar issue with SQLite)

I can't reproduce this issue with the latest Kodi master on Ubuntu 19.10 - presumably because the system `libfmt` is 3.0.1.

However I can reproduce this query mangling issue with LibreELEC since `[#0129](https://forum.kodi.tv/showthread.php?tid=343069&pid=2920286#pid2920286)` which is when we switched to using `libfmt-6.1.2` (in PR:4160) - so it seems that `libfmt-6.1.2` may be one trigger for this issue.

I can also reproduce the query mangling issue when using `libfmt-5.3.0` once this PR merged on 5 Feb so the mangling issue is not exclusive to the new `libfmt-6.1.2` package, it occurs with 5.3.0 too after this PR.

**Comment by Paxxi** [comment]
yes, this fix didn't work as intended, another fix that seem to work is available at #17351 but hasn't been merged yet.

**Comment by MilhouseVH** [comment]
Thanks, I'll give it a test!

**Comment by MilhouseVH** [comment]
Thanks, #17351 fixes the JSON-RPC issue!

**Pull request merged**
