### PR TITLE
CHG: Extract SysfsUtils from the AML utils

### PR DESCRIPTION
**Pull request by koying**
We are fiddling with sysfs on more than aml, now.
Let's make it an util class.

/cc @fritsch

### CODE REVIEW

**Comment by fritsch** [comment]
jenkins build this please

**Comment by koying** [comment]
jenkins build and merge

**Comment by koying** [comment]
jenkins build and merge

**Comment by koying** [comment]
jenkins build and merge

**Comment by anaconda** [comment]
Just a nitpick - `aml_get_sysfs_str` failed silently, but `SysfsUtils::GetString` prints an error. You get this on e.g. a Raspberry Pi:
`02:01:28 348991.562500 T:3039297536   ERROR: GetString: error reading /sys/class/graphics/fb0/device/modalias`
from https://github.com/xbmc/xbmc/blob/master/xbmc/windowing/egl/EGLNativeTypeAmlogic.cpp#L54-L56

**Comment by popcornmix** [comment]
Why is that code even running on R-Pi?

**Comment by koying** [comment]
I guess it dates from the time somebody decided #ifdef's were not welcome anymore...

**Comment by popcornmix** [comment]
Yes, here: https://github.com/xbmc/xbmc/blob/master/xbmc/windowing/egl/EGLWrapper.cpp#L82
Most of the CheckCompatibility functions have the ifdefs inside. The two that don't look to be reliable. E.g. does existence of /sys/class/graphics/fb0/device/modalias really guarantee we are an AML platform?
I'd vote for ifdefs - seems to be pulling in a load of unwanted classes (and potential for platform specific changes causing issues on other platforms).

**Comment by koying** [comment]
You can ifdef it out for rpi, if you can, but besides that CEGLNativeTypeAmlogic is a linux implem for amlogic on the same level as rpi, so no way to ifdef it out, afaict.

**Comment by smallint** [comment]
Sorry, I pushed that assign button by accident ...

**Comment by popcornmix** [comment]
I had a clear assignee option in the assign list.

**Comment by smallint** [comment]
Thanks

**Comment by koying** [comment]
All: If the Log entry is actually an hindrance, you can use ```SysfsUtils::Has()``` to test the presence of a sysfs entry, which does not produce a log.

**Pull request merged**
