### PR TITLE
[pvr][settings] Define a senseful default value for advanced settings 'updateemptytagsinterval'

### PR DESCRIPTION
**Pull request by ksooo**
Discussed here: https://forum.kodi.tv/showthread.php?tid=340357

This PR implements the quick fix discussed in above mentioned forum thread. Everything else is subject for v19+ (because regression risk is far too high).

Second commit improves documentation for the epg advanced settings value. I already updated the wiki and this commit aligns the documentation again.

@Jalle19 basic idea is to dramatically increase the interval for checking for new epg data for channels not (yet) having EPG data from 1 minute to 120 minutes (aligning it with the interval used for channels with EPG data) for the reasons given in the forum thread. The whole epg update code with many different update intervals etc. is imo highly over engineered and should be dramatically simplified, but this is nothing for v18.

### CODE REVIEW

**Comment by ksooo** [comment]
@Jalle19 ping

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
Jenkins build this please

**Pull request merged**
