### PR TITLE
Don't delete/overwrite fileitem on Player.GetItem.Fixes trac #15416

### PR DESCRIPTION
**Pull request by razzeee**
This is one of those fixes, that feel awkward but seem to work fine. So let's see if we can find anything wrong with this.
This fixes http://trac.kodi.tv/ticket/15416

@Montellese because of json-rpc

### CODE REVIEW

**Comment by Tolriq** [comment]
This PR is quite strange :)

The original code says : If you can't fill data from library at least read the TAGS so that JSON consumers have the correct data when user does not use library.

And your fix is load from library and if it fails then do nothing.

This just remove the TAG data from un scanned file to library without solving anything.

If there's a bug with FillFileItem that loads data but returns false for addons, this is this function that should be solved, this fix just break TAGs for JSON for out of library files.

And about the trac issue, this is a well known problem that Montellese have never found a solution for.

Addons can fill data via GUI functions that will be usable from Players, but that JSON can not access.

This is true for any type of content (video / images / music) and depends on some internals path taken or not.

**Comment by Razzeee** [comment]
Well doesn't sound like you tested it. If you setup a debugger you would see easily that this fixes out of library files. As the fileitem is already correct when it reaches this code path.

**Comment by Razzeee** [comment]
Should I create a build? What's your platform? :)

**Comment by Tolriq** [comment]
Well : https://github.com/Razzeee/xbmc/commit/d1e3333b5781a2d9b06aee628f9ed179e1350bcd and https://github.com/Razzeee/xbmc/commit/db911a5f88ef054840b3dc3b98bf342845361506

Those where related to bug I reported and where fixed by those patches.

+ The Track issue is a well known problem since 6 years I do direct support for users and talked a few time with Montellese and touch much more than music but any addon started from JSON and not from GUI.

So maybe things where broken by other PR later, but I'm sure this fix will not fix the underlying problem of addons not filling the data when started from JSON.
And I do not know what you did test before / after this patch but I know for sure there will be impacts.

I may not be from the team but I'm here doing end user support and being high JSON consumer and following Xbmc / Kodi source code since a very very long time so know most of the problems and history.

**Comment by Razzeee** [comment]
Yep,  there might be impacts. But that's why we'll wait for montellese and maybe you can do some regression testing?

**Comment by Razzeee** [comment]
Btw I couldn't reproduce the problem for videos.

**Comment by Razzeee** [comment]
Btw "addons not filling the data when started from JSON" sounds a little like another problem I didn't test against. I just tried fixing the art fields when Player.GetItem is called.

**Comment by Tolriq** [comment]
Well seeing recent events I have no time to find back the reasons and reproduce test case. But I can't retain for warning that you introduce again a bug that was fixed before.

But since Video code have the exact same behavior that you do not change and that the fix for the path / label to be filled at 100% is removed, there's no need to do regression tests to be sure that there is a regression :)

Since I know some little things about Kodi : 

Proper fix is to implement CFileItem::SetFromMusicInfoTag (that is quite simple code See constructor and video one) 

And replace
```
fileItem = CFileItemPtr(new CFileItem(*currentMusicTag));
```
with
```
 fileItem->SetFromMusicInfoTag(*currentMusicTag);
```

This avoid the reset of the previously filled data while keeping the code correct.

Removing a whole block of code that is known to fix things is not good, understanding the problem and fixing is better ;)

**Comment by da-anda** [comment]
from what I recall when reporting that ticket is that it doesn't matter if the music add-on is started via JSON or not. I only know that covers show up for video add-ons but not for music, and that's a bug.

Also, the removed code block is IMO only a hack for a broken behavior, so IMO removing that block is the correct thing to do and then fix the issue on it's root and not on every place the items are used. But the entire fileitem handling is a utter mess in general and needs refactoring.

**Comment by Tolriq** [comment]
Read the part for video just above : https://github.com/xbmc/xbmc/pull/8440/files#diff-9c2a40e0c0359d72671c8181d11db75dR175

This is not a hack this is the correct way to handle items out of library that could have tags not loaded depending on how they are played + certitude to have label set up. (Tons of things depends on label being present)
The bug is ```fileItem = CFileItemPtr(new CFileItem(*currentMusicTag));``` than can erase some addons stuff in some cases, but certainly not the whole block !

The removal of the block without the global fix and leaving the exact same code in video is a hack and will introduce back an important bug that was fixed.

The proper fix to avoid major problems in short terms is described in my previous post. But please do not merge this like that and let's hope Montellese get back and explains the reasons and is listened :)

**Comment by da-anda** [comment]
my point was that the missing tag data loading should not have to be done here in first place - the fileitem itself should take care of it

**Comment by Tolriq** [comment]
From my understanding about that (@Montellese to confirm) this is caused by the same problem that generate the JSON missing data from addons.

GUI can gather data and fill things that can be pushed to players and skins, but the data is not returned after to JSON, if after 6 years and multiple asks it's still not fixed by @Montellese I suppose this is very complicated to fix and as such those things in JSON to try to gather the data are necessary for remote to works until the root issue is fixed.

Unfortunately even if I understand all JSON / EventServer things and a few others, the Player part is out of my competence.

**Comment by DaveTBlake** [comment]
>So let's see if we can find anything wrong with this.

Sorry @Razzeee but @Tolriq was right this change does break things :(
I guess not a big surprize, since you were removing a chunk of code that we didn't know what it did, when similar code exists for video and does not cause a problem.

Took me a while to fine the use case, but if you initiate playing from JSON of a song that is not in the library and then try to GetItem it does not have MusicInfoTag data to return.

Please do not say this is an "edge case" and we can ignore it or I will get upset! Solving one thing by breaking something else is not progress.  Another solution to ticket 15416 needs to be found, but that's OK we are intelligent people so just need to think a bit harder.

**Comment by Razzeee** [comment]
Why would I say that? It's good that we found the case, I really want to know why fileItem is empty then. Will do some research and report back. 
Thanks so far.

**Comment by Tolriq** [comment]
This is tied to the problem explained here 2 times already ;)

Starting things from GUI does loads things that will be made available later, starting them from JSON does not :)

If you find the root cause of this, this would solve a 6 years old problem impacting a lot users and addons, and not found by JSON expert Montellese ;) So lot's of chance to be out of scope of this as impacting the whole GUI / JSON process. This would also solve not pre filled playlist data (but surely at the cost of speed problems, since this part is already awfully slow). And would certainly not impact just music.

If you want a fix to this simpler problem for Jarvis, merging tags instead override sounds like a better idea even if I know nothing (Why would such a merge function exist for video if it was such a bad idea ;) )

6 years knowledge of every single JSON problems so sorry but I can't refrain for trying to avoid future major problems when I see them.

**Comment by Razzeee** [comment]
So here's a fix that prevent's us to loose the data and removes the overhead. In all cases where we don't need it. If somebody really starts a file which is not in a music library, via json and tries to Player.GetItem, we fill in the data that we have.

**Comment by Razzeee** [comment]
Better would be to fix the fileitem or do as @Tolriq suggests. But thats nothing for a bugfix, as it will need big code changes to fileItem.

**Comment by DaveTBlake** [comment]
I would like to give this some testing, but can't do that until Monday (on the road for now). 

Can someone tell me how the bug this set out to fix can be produced (in older versions of course), not sure I saw that.

**Comment by Razzeee** [comment]
If you call this method for audio, the two art fields (fanart, can't remember the other) will both always be empty. Even if it is available.

**Comment by DaveTBlake** [comment]
>If you call this method for audio, the two art fields (fanart, can't remember the other) will both always be empty. Even if it is available. 

Sorry but missing art is still an issue sometimes, so I am unclear on which situations are fixed by this?
At least this updated version of the code change does not make things worse! That is as far as I can tell so far :)

My interpretation of ticket 15416 is that when playing music is started by JSON on subsequently calling GetItem the fanart and thumbnail (cover) art is not returned. This still seems to be the case. The path through GetItem varies depending on what has been done in Kodi recently making checking this extra tricky. But am I misunderstanding what this fix is intending to do?

**Comment by Tolriq** [comment]
The PR is supposed to fix the very specific case reported by @da-anda :
- Starting an audio addon from the GUI will fill thumb / fanart but getItem will not return them.

Starting it from JSON will never work with this fix it needs a complete analysis of the other mentioned way larger problem (Start from GUI != Start from JSON) (I've seen some message from @Montellese maybe he his back and can give advice on where to look for this GUI / JSON start problem)

To reproduce start any radio from Radio addon from GUI (official repo quick install no setup ;) )

New proposed fix can have side effects if in one fileitem creation path empty tags are added or temporary tags , then the full tag loader will not run.

Video have a merge tags solution that works so the unsure check for tags before the call should maybe not added at least for video to avoid new side effects on something that currently works perfectly. 

Same for audio but well then there's no more fix :)

**Comment by DaveTBlake** [comment]
Ah I had missed that this fix was specific to starting play from an addon, thanks for clarifying @Tolriq 

>New proposed fix can have side effects if in one fileitem creation path empty tags are added or temporary tags , then the full tag loader will not run.

Not sure I understand what you are saying, could you clarify. I have had odd results when calling GetItem from JSON when play started from File view, but that could be down to a setcontent change I am also testing.

**Comment by Tolriq** [comment]
New version of the fix use : ```!fileItem->HasMusicInfoTag())``` and ```!fileItem->HasVideoInfoTag()```

But due to the differences between GUI / JSON things, I'm near sure that in some case there's "false" or "temporary" or whatever you call them tags added to fileitem to fill some data that are not the real tags. So the test will say there's tags do not load the real tags.

**Comment by Razzeee** [comment]
Yes, that video part, is probably nothing for Jarvis. But my point is, that we hit that code way to often without it doing anything. We should do my proposed change with the next alpha and see what/if it breaks. So that we can fix it on the root, as this class shouldn't be doing things like this. This is coming from a clean code perspective and is not meant to offend anyone.

**Comment by Tolriq** [comment]
I'd be more than glad if you find the root cause that last since JSON introduction and cause major problems to remotes ;)

But breaking things just to see if it breaks and wait for users to report back sounds not so good from my point of view. 

I'll get all the support for something is identified from the start.

If I do check most PR for regression it's to keep Kodi safe but also to avoid all users knocking at my door for Kodi problems.

So yes find root cause and fix it as it's the correct solution of course and all users will thank you. But touch things that works on a code part that you say want to remove sounds not logical. Why creating problems that in the end will need to root fix, why not just fix root instead of creating intermediary problems ? If you can't find root cause, then why breaking something that works then ? Since this code will still be there.

**Comment by Razzeee** [comment]
The problem is, we (including you) are not even sure it this will break something. You suspect it, but as said, we're hitting that code path on pretty much every call to that method. Without it actually doing something, just taking resources and cluttering up the code.

**Comment by Tolriq** [comment]
Well I was right with previous fix, and if I had time I could demonstrate this one.

But not sure to understand your comment at all.

This code part is only used for items not in database, so clearly not all code path. 
And it obviously does something it fix a JSON problem by filling necessary data.

If you are talking about taking resources we should better discuss about why querying database each time them ? Because this is way way way slower and resource consuming than getting the tags.

So, no offense, but I maintain what I say about the fix for video that should not be here as it have 0 advantages but creating problems.

And for audio well since I do not master all path and have no time / willing to do all the debug part I also maintain this may not be the proper fix. 
But there's also a chance that the number of path fixed are superior to the number of newly broken path so it could worth the try.

Only need to validate the 4 main path for audio regression : Play song from library from GUI / from JSON. Play song not in library from GUI / from JSON.

**Comment by DaveTBlake** [comment]
First the good news...
I have tested the 4 JSON combinations suggested by @Tolriq, and playing music from an addon. I have not tested video at all. Using `!fileItem->HasMusicInfoTag())` seems to have fixed the specific music addon case, and has not made JSON any worse.

However, I find the approach of this change very odd. Changes to code that we don't fully understand are tricky, and we need to be circumspect.   Just as deleting a chunk of code was not wise, so is adding to video code that has not been reported as having any issues. I understand a desire to keep video and music in line, but this change does not do that. Video merges tag data, music makes a new fileitem. The latter is the cause of the addon missing art issue.

I also don't see how  "just taking resources and cluttering up the code" applies.  And I am totally against the "we don't know, so lets' see if the users break it" approach. It may be the Microsoft approach,  but IMO it is just lazy and low quality work.

Given the circumstances it seems to me that a better fix for Jarvis (of the specific addon missing art issue) would be to make music match the video by adding a `CFileItem::SetFromMusicInfoTag` function. I have  version with those changes, and it tests fine.

On the way I think I understand the long standing problem, not addressed by this PR, with art missing from GetItem when music is played by JSON. Fixing that would be good wouldn't it

**Comment by Razzeee** [comment]
As I already said above, if you have a working branch with CFileItem::SetFromMusicInfoTag. Please PR it. Looked into it and realized I don't have the time for such a change atm.

**Comment by Razzeee** [comment]
Closed in favor of #8465

**Pull request closed without merging**
