### PR TITLE
fix build without bluray

### PR DESCRIPTION
**Pull request by notspiff**
No BlurayDirectory for you!

### CODE REVIEW

**Comment by ace20022** [comment]
@FernetMenta this should be enough, right?

**Comment by FernetMenta** [comment]
I can't test this on OSX. Have no Linux system here atm

**Comment by ace20022** [comment]
@garbear could you test it please?

**Review by Rechi — APPROVED** [review]
compiled for osx and windows with disabled (and enabled) bluray support

**Pull request merged**
