### PR TITLE
Fix 4k content crashing on series consoles

### LINKED ISSUE #19044: Crash on Xbox Series X when trying to play any 4k video
### Describe the bug

When trying to play any 4k video on Xbox Series X, it will crash and return to dashboard screen. There are multiple people reporting the same problem on forum here https://forum.kodi.tv/showthread.php?tid=358338.

## Expected Behavior

4k video plays as any other video without crashing the application

## Actual Behavior

When running 4k video, does not have to be HDR it will crash.

## Possible Fix

Not sure, tried to fiddle with settings like adjust refresh rate to always, trying different rendering methods, disabling hardware acceleration without any effect. It always crashed.
Same 4k video works fine in VLC on same system. 

### To Reproduce

1.  Start Kodi on Xbox Series X
2.  Play any 4k video

### Debuglog

The debuglog can be found here:

Here is debug log from the forum https://paste.kodi.tv/awicunilev.kodi, I can provide additional one if needed.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [X] Windows UWP

 - Operating system version/name: Xbox Series X
 - Kodi version: 18.9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by tunip3**
## Description
Fix 4k content crashing on series consoles due to them running out of ram. 
The fix is to add the expanded resources rescap, this enables the app to access more ram and a generally greater level of performance

More info can be found [here](https://docs.microsoft.com/en-us/windows/win32/api/expandedresources/) and [here](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#restricted-capabilities)

## Motivation and Context

This is a fix to #19044 

## How Has This Been Tested?

This was tested on an Xbox series X by installing the game as an app and loading 4k content

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by spydermahn1234** [comment]
Have tested this fix -

used this file on usb2.0 plugged into series x

https://jell.yfish.us/media/jellyfish-200-mbps-4k-uhd-hevc-10bit.mkv

On retail mode with Kodi 18.9 - file makes kodi crash to desktop.

On Dev mode with Kodi 19.0 with expanded resources fix - kodi launched as app (rather than game which allows extra ram by default) and the file plays perfectly.

can provide additional logs if needs be

**Comment by afedchin** [comment]
https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#restricted-capabilities

> If your app declares any restricted capabilities, you must provide info during the app submission process in order to be approved to publish the app to the Microsoft Store. You provide this info on the Submission options page of your submission, explaining how your app uses each restricted capability that it declares.

> Restricted capabilities are intended for very specific scenarios. The use of these capabilities is highly restricted and subject to additional Store onboarding policy and review. Note that you can sideload apps that declare restricted capabilities without needing to receive any approval. Approval is only required when submitting these apps to the Store.

and more by the link.


In other words: This will causes an issue with Store approve at least. Very long review and etc. 
I have no reason to aprove this.

**Comment by tunip3** [comment]
> https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#restricted-capabilities
> 
> > If your app declares any restricted capabilities, you must provide info during the app submission process in order to be approved to publish the app to the Microsoft Store. You provide this info on the Submission options page of your submission, explaining how your app uses each restricted capability that it declares.
> 
> > Restricted capabilities are intended for very specific scenarios. The use of these capabilities is highly restricted and subject to additional Store onboarding policy and review. Note that you can sideload apps that declare restricted capabilities without needing to receive any approval. Approval is only required when submitting these apps to the Store.
> 
> and more by the link.
> 
> In other words: This will causes an issue with Store approve at least. Very long review and etc.
> I have no reason to aprove this.

In my experience whilst it does cause the review process to take a longer period of time it is not drastically longer. I do feel that it is worth the longer wait time in order to get 4k working on series consoles, though if you feel that you can implement sufficient memory optimizations so that you don't need the increased amount of memory this affords that would be a more ideal solution.

**Comment by TreeBranches** [comment]
> https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#restricted-capabilities
> 
> > If your app declares any restricted capabilities, you must provide info during the app submission process in order to be approved to publish the app to the Microsoft Store. You provide this info on the Submission options page of your submission, explaining how your app uses each restricted capability that it declares.
> 
> > Restricted capabilities are intended for very specific scenarios. The use of these capabilities is highly restricted and subject to additional Store onboarding policy and review. Note that you can sideload apps that declare restricted capabilities without needing to receive any approval. Approval is only required when submitting these apps to the Store.
> 
> and more by the link.
> 
> In other words: This will causes an issue with Store approve at least. Very long review and etc.
> I have no reason to aprove this.

Considering the new consoles and the industry as a whole is moving towards 4k content, I beg you to reconsider in order to prevent complaints in future.

**Comment by thexai** [comment]
I noticed that VLC uses "hevcPlayback" capability for the same reason:

https://github.com/videolan/vlc-winrt/blob/3c8edcc0315085be6f9be058179a4557241a8479/app/VLC.Universal/Package.appxmanifest#L121

https://github.com/videolan/vlc-winrt/commit/dbbc78f5c3189e02890b1d18772fc183e561f63e#diff-2a9d66c1721b949cf47f4457028a65895b7e73aaddf5682ceccaea76d2c127b6

This option seems (public) undocumented by Microsoft, however VLC is using it. Maybe is less problematic obtain approval with this since seems less generic capability (only for HEVC playback).

I upload a test build with this option for some one with Xbox can sideload and test it if works for Kodi:
http://www.mediafire.com/file/bzdxax38aofa41v/Kodi-20210227-5b64c1e1-Matrix-x64.rar/file

In case this option also works, one of the two options is need to pick. I don't think it is possible to fix this in any other way as it is impossible to decode 4K without using some more memory.

**Comment by afedchin** [comment]
iirc we have some troubles on store approval with `hevcPlayback` option, perhaps something was changed

**Comment by spydermahn1234** [comment]
> I noticed that VLC uses "hevcPlayback" capability for the same reason:
> 
> https://github.com/videolan/vlc-winrt/blob/3c8edcc0315085be6f9be058179a4557241a8479/app/VLC.Universal/Package.appxmanifest#L121
> 
> [videolan/vlc-winrt@dbbc78f#diff-2a9d66c1721b949cf47f4457028a65895b7e73aaddf5682ceccaea76d2c127b6](https://github.com/videolan/vlc-winrt/commit/dbbc78f5c3189e02890b1d18772fc183e561f63e#diff-2a9d66c1721b949cf47f4457028a65895b7e73aaddf5682ceccaea76d2c127b6)
> 
> This option seems (public) undocumented by Microsoft, however VLC is using it. Maybe is less problematic obtain approval with this since seems less generic capability (only for HEVC playback).
> 
> I upload a test build with this option for some one with Xbox can sideload and test it if works for Kodi:
> http://www.mediafire.com/file/bzdxax38aofa41v/Kodi-20210227-5b64c1e1-Matrix-x64.rar/file
> 
> In case this option also works, one of the two options is need to pick. I don't think it is possible to fix this in any other way as it is impossible to decode 4K without using some more memory.

I will give this build a test this afternoon - however the last matrix build I tried had issues with net connectivity and most of my 4k is stored on my cloud server.... Will try and get a file to usb.

**Comment by gedeagas** [comment]
@thexai I tried the build but I can't seem to navigate the app with the default Xbox controller :(. Did I miss something?

**Comment by thexai** [comment]
> I tried the build but I can't seem to navigate the app with the default Xbox controller :(. Did I miss something?

Ooh! Probably `peripheral.joystick` (build-in addon) is missing in my compilation. 

It should be possible to add it by copying the files manually but I don't know if it can be done on Xbox. In any case, it seems that the option `hevcPlayback` is not viable either.

**Comment by zeruth** [comment]
> https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#restricted-capabilities
> 
> > If your app declares any restricted capabilities, you must provide info during the app submission process in order to be approved to publish the app to the Microsoft Store. You provide this info on the Submission options page of your submission, explaining how your app uses each restricted capability that it declares.
> 
> > Restricted capabilities are intended for very specific scenarios. The use of these capabilities is highly restricted and subject to additional Store onboarding policy and review. Note that you can sideload apps that declare restricted capabilities without needing to receive any approval. Approval is only required when submitting these apps to the Store.
> 
> and more by the link.
> 
> In other words: This will causes an issue with Store approve at least. Very long review and etc.
> I have no reason to aprove this.

No it will simply take slightly longer to approve, There are plenty of apps that use this cap and get approved, ie: retroarch.

This should have been merged almost immediately.

**Comment by DaveTBlake** [comment]
> This should have been merged almost immediately.

Thank you for your opinions @zeruth and @varGeneric. We currently do not have a maintainer for Kodi on Xbox, so things are delayed. You can help out by volunteering and providing validated information, testing etc.

**Review by thexai — APPROVED** [review]
I approved the PR because according to my criteria it is correct and it is the only way to go. It is just a way of expressing my opinion.

It will not be merged without the support of others Team members.

**Comment by thexai** [comment]
Also created a test build here:
https://github.com/thexai/xbmc/releases/tag/19.1-Preview

And open a thread in the forum to try to collect some feedback:
https://forum.kodi.tv/showthread.php?tid=362315

**Comment by thexai** [comment]
I'd really like to merge this PR: besides 4K HEVC crash fix, in conjunction with https://github.com/xbmc/xbmc/pull/19790 great improves GUI and fonts render quality with 4K resolution. Version 18.9 or v19 without this PR never renders GUI with 4K resolution but 1080 upscaled to 4K. 

It is difficult to show in a photo but it is very noticeable with the naked eye that the fonts are much sharper.

Before:
PXL_20210704_182252679_ MP

After:
PXL_20210704_182759658_ MP

For all this it's a very important improvement for Xbox.

If nobody says anything against the intention is to merge this PR and the backport in two or three days... The worst that could happen is that v19 cannot be published in Xbox Store but this is not a worse situation than the current one.

@afedchin, @fuzzard, @DaveTBlake something to comment?

**Review by afedchin — APPROVED** [review]

**Pull request merged**
