### PR TITLE
[settings] Remove DTS-HD from general settings

### PR DESCRIPTION
**Pull request by popcornmix**
Changes to enabled by default with explicit platforms excluded.
See discussion here: https://github.com/xbmc/xbmc/pull/8486

### CODE REVIEW

**Comment by popcornmix** [comment]
Ping @FernetMenta

**Comment by FernetMenta** [comment]
thanks. I would like to have the decision what audio codec options are used in a central place. That is VideoPlayerAudio. It already decides whether passthrough should be used or not. This way you also avoid creating a dependency from the codec to a global class. We have DVDCodecOptions for passing options to a codec. This can be used for this purpose.
Please also consider what @koying mentioned. AudioPlayer could ask AE for e.g. HasHDAudioChannelCount(). Only use dcadec if that is true.

**Comment by popcornmix** [comment]
DTS-HD does provide both the extra 2 channels and an upgrade from lossy to lossless, so a platform with only "2.0" channels may argue they want to use the lossless data to produce that stereo output. Whether a user can hear the difference is debatable, but I could imagine it being requested.

**Comment by FernetMenta** [comment]
ok, lossless is an argument for having it for 2.0 as well.

**Comment by popcornmix** [comment]
@FernetMenta I've pushed a new version that makes the decision in VideoPlayerAudio.

**Comment by FernetMenta** [comment]
thanks
jenkins build and merge

**Pull request merged**
