### PR TITLE
osx: fix high cpu usage when obscured

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

### CODE REVIEW

**Comment by Memphiz** [comment]
Oha ... didn't expect this sort of workaround from you tbh - but am totally fine with is. But it could need a comment on why we sleep there ...

**Comment by FernetMenta** [comment]
this is no workaround at all. the architecture delegates throteling of the render/main loop to windowing. if, for what reason ever, swapBuffers does not block, windowing has to take action.

**Comment by Rechi** [comment]
Is this worth a backport (applies cleanly) or is it to risky?

**Comment by FernetMenta** [comment]
I don't think it is risky.

**Comment by FernetMenta** [comment]
comment added

**Comment by Memphiz** [comment]
Thx - sorry somehow i was confused because the last time we had this cpu usage problem it was in the dirty regions area of things. Guess this throttle not working is something in the osx gl implementation then (were swapbuffers is a nop or something when kodi is offscreen maybe).

**Comment by FernetMenta** [comment]
@Memphiz the method IsObscured was actually implemented for this purpose: https://github.com/xbmc/xbmc/commit/de396863c328ddf9fa66e8eb548c1d541acfc338

It got lost because the old code violated a basic OO principle: information hiding. OSX promoted its private function to CApplication.

**Comment by Memphiz** [comment]
Yes i know that method very well - i had to add exceptions for all those full screen alpha translucent apps that are meant to decrease brightness (which resulted in frame limiter kicking in). So in case people are reporting stuttering ui rendering - we need to have those apps in mind aswell... ;)

**Comment by Rechi** [comment]
jenkins build this please

**Comment by Rechi** [comment]
WIN-UWP-ARM failure is unrelated

**Comment by FernetMenta** [comment]
build error unrelated

**Comment by MartijnKaijser** [comment]
@Memphiz you want this backported or risk too high?

**Comment by Memphiz** [comment]
No risk immo @fernetmenta what do you think?

**Comment by FernetMenta** [comment]
I think risk is low. Note that I did not test it on v17

**Pull request merged**
