### PR TITLE
[network] Fix CZeroconfBrowserAvahi dtor avahi thread termination.

### PR DESCRIPTION
**Pull request by ksooo**
This fixes a SIGABRT when exiting Kodi. Only occurs after #9194, before, Kodi never got that far. ;-)

Thx @fritsch for the support. Good to go?

@MartijnKaijser definitely needs backport.

### CODE REVIEW

**Comment by ksooo** [comment]
jenkins build this please

**Comment by fritsch** [comment]
+1

Let's ping @Memphiz as I don't know who is the maintainer. Let's wait until start of next week.

**Comment by ksooo** [comment]
@Memphiz any opinions on this?

**Comment by Memphiz** [comment]
looks good as long as we mention somewhere that at least avahi 0.6.24 is needed for this to work (or maybe that version is so old that we simply assume that this version is used at least ...)

**Comment by ksooo** [comment]
The ticket (www.avahi.org/ticket/251) was closed 7 years ago. I think we can assume that 0.6.24+ is available on every platform of interest. 0.6.25 was in Ubuntu 10.04 (Lucid)

**Comment by ksooo** [comment]
WIN-32 jenkins error is unrelated

**Pull request merged**
