### PR TITLE
[Win10] a set of fixes and improvements for uwp

### PR DESCRIPTION
**Pull request by afedchin**
see title

also added basic support of XAudio2 (requires improvements).

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves existing functionality)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by koying** [comment]
So that you know, `GetDiskFreeSpaceEx` is actually supported on WindowsStore (https://msdn.microsoft.com/en-us/library/windows/desktop/aa364937(v=vs.85).aspx).
I was looking into the exception as well. Works fine on PC, didn't test yet on XBOX

**Comment by afedchin** [comment]
jenkins build this please

**Comment by afedchin** [comment]
jenkins build this please

**Comment by afedchin** [comment]
jenkins build this please

**Comment by koying** [comment]
I confirm GetDiskFreeSpaceEx (so basically standard Windows) work as well.
Might be worth considering to avoid the `Wait()`

```
From fd330a9f5df6adf27c69349622ea166322e13571 Mon Sep 17 00:00:00 2001
From: "Chris \"Koying\" Browet" <cbro@semperpax.com>
Date: Sat, 11 Nov 2017 10:05:09 +0100
Subject: FIX: [win10] GetDiskFreeSpaceEx is ok


diff --git a/xbmc/platform/win32/WIN32Util.cpp b/xbmc/platform/win32/WIN32Util.cpp
index 6b0bc0b..b202a36 100644
--- a/xbmc/platform/win32/WIN32Util.cpp
+++ b/xbmc/platform/win32/WIN32Util.cpp
@@ -381,20 +381,20 @@ bool CWIN32Util::XBMCShellExecute(const std::string &strPath, bool bWaitForScrip
 std::vector<std::string> CWIN32Util::GetDiskUsage()
 {
   std::vector<std::string> result;
+  ULARGE_INTEGER ULTotal = { { 0 } };
+  ULARGE_INTEGER ULTotalFree = { { 0 } };
+
 #ifdef TARGET_WINDOWS_STORE
-  auto propertyKeys = ref new Platform::Collections::Vector<Platform::String^>();
-  propertyKeys->Append("System.FreeSpace");
-
-  // gets free space for drive where app is installed
-  StorageFolder^ localFolder = ApplicationData::Current->LocalFolder;
-  auto retrivied = Wait(localFolder->Properties->RetrievePropertiesAsync(propertyKeys));
-  auto freeSpace = (uint64_t)retrivied->Lookup("System.FreeSpace");
-  auto strRet = KODI::PLATFORM::WINDOWS::FromW(StringUtils::Format(L"%d MB %s", int(freeSpace / (1024 * 1024)), g_localizeStrings.Get(160).c_str()));
+  std::string strRet;
+
+  Platform::String^ localfolder = Windows::Storage::ApplicationData::Current->LocalFolder->Path;
+  std::wstring folderNameW(localfolder->Begin());
+
+  GetDiskFreeSpaceEx(folderNameW.c_str(), nullptr, &ULTotal, &ULTotalFree);
+  strRet = KODI::PLATFORM::WINDOWS::FromW(StringUtils::Format(L"%d MB %s", (ULTotalFree.QuadPart / (1024 * 1024)), g_localizeStrings.Get(160).c_str()));
   result.push_back(strRet);
-#else
-  ULARGE_INTEGER ULTotal= { { 0 } };
-  ULARGE_INTEGER ULTotalFree= { { 0 } };
 
+#else
   std::unique_ptr<wchar_t> pcBuffer;
   DWORD dwStrLength= GetLogicalDriveStrings( 0, pcBuffer.get() );
   if( dwStrLength != 0 )
```

**Comment by afedchin** [comment]
thanks, will apply

**Comment by afedchin** [comment]
jenkins build this please

**Pull request merged**
