### PR TITLE
[test] add test for XbmcThreads::EndTime class

### PR DESCRIPTION
**Pull request by lrusak**
This adds a test using for the `XbmcThreads::EndTime` class. I wrote this while I was converting this class to use std::chrono. That code is available here: https://github.com/lrusak/xbmc/tree/systemtime-chrono however I don't think that will make it in for V19 so I wanted to PR these tests for inclusion.

I found a bug in the `XbmcThreads::ThreadSleep` function so I removed that method completely. The problem was that the millisecond value was being treated as microseconds.
```
std::this_thread::sleep_for(std::chrono::microseconds(millis));
```
This didn't really effect much though as only one place used this method (other than in tests).

Should be safe for inclusion into V19

### CODE REVIEW

**Review by DaveTBlake — COMMENTED** [review]
> The problem was that the millisecond value was being treated as microseconds.

Confused by this compared to experience. The main use in CMusicScanner is to avoid exceeding the Musicbrainz rate limit (1 query per sec) otherwise requests from the IP address get rejected. Really surprized if only a 1 millisec wait was happening, because we would have had lots of 503 errors and scraping would have been much faster.

**Review by DaveTBlake — APPROVED** [review]
Ha, got it, the important 1 second delay is done using `CEvent.WaitMSec()` and not the faulty `XbmcThreads::ThreadSleep`. 

Perhaps you could avoid the white space extra line changes in MusicInfoScanner.cpp, it clutters the git blame. I intend to do a big whitespace clean-up/ clang format of music library related code early in v20.

**Review by garbear — APPROVED** [review]
Additional test cases are always welcome, thanks!

**Comment by lrusak** [comment]
> Ha, got it, the important 1 second delay is done using `CEvent.WaitMSec()` and not the faulty `XbmcThreads::ThreadSleep`.

I was actually looking at that. I would think the `CEvent` should be a class member so it can be set from outside in case of cancellation? Not really relevant to this PR though.

> Perhaps you could avoid the white space extra line changes in MusicInfoScanner.cpp, it clutters the git blame. I intend to do a big whitespace clean-up/ clang format of music library related code early in v20.

removed.

**Comment by lrusak** [comment]
jenkins build this please

**Pull request merged**
