### PR TITLE
[Dependency] Move kissfft library to external lib

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Lets remove the contrib source and use upstream (https://github.com/mborgerding/kissfft)

## Motivation and context
Move out of tree. Allow systems to provide kissfft (ie linux - eg Debian Bullseye has the package https://packages.debian.org/bullseye/libkissfft-dev)

Of note: 988a666504092deb6b9ce92ab68b1413c33cc364 is included as a commit for this. This will be removed once #23807 is approved/merged

kissfft defaults to float. This is the same as we currently build from contrib source, and debian packages the float variant as well. As it stands, i dont think its worth dealing with the variants (double, float (default), int16_t, int32_t, simd) for now.

## How has this been tested?
Build/run Makefile aarch64 macos
Build/run VS win64

## What is the effect on users?
N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by mkreisl** [comment]
There is something wrong:

```
CMake Error at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find KissFFT (missing: KISSFFT_LIBRARY) (found version "131.1.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindKissFFT.cmake:95 (find_package_handle_standard_args)
  cmake/scripts/common/Macros.cmake:386 (find_package)
  cmake/scripts/common/Macros.cmake:400 (find_package_with_ver)
  CMakeLists.txt:236 (core_require_dep)
```

Build for Raspberry Pi / Debian Bookworm

That sounds somehow familiar to me

**Comment by fuzzard** [comment]
Cheers, I'll look into it later next week

**Comment by mkreisl** [comment]
> Cheers, I'll look into it later next week

Work now, thanks

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by mkreisl** [comment]
Hi, unfortunately changed to broken again:

```
-- Found HarfBuzz: /usr/lib/arm-linux-gnueabihf/libharfbuzz.so (found version "6.0.0") 
-- Looking for iconv
-- Looking for iconv - found
-- Found Iconv: /usr/arm-linux-gnueabihf/lib/libc.so  
-- MODULE: KISSFFT
-- kissfft_LIB_TYPE: target
-- DEP_LOCATION: /home/xbian/xbian-package-xbmc/build/rpi4-p/working/tools/depends/raspberry-pi2-debug
-- PROJECTSOURCE: /home/xbian/xbian-package-xbmc/build/rpi4-p/working
-- KISSFFT_URL: https://mirrors.kodi.tv/build-deps/sources/131.1.0.tar.gz
CMake Error at /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find KissFFT (missing: KISSFFT_LIBRARY KISSFFT_INCLUDE_DIR)
  (found version "")
Call Stack (most recent call first):
  /usr/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindKissFFT.cmake:111 (find_package_handle_standard_args)
  cmake/scripts/common/Macros.cmake:403 (find_package)
  cmake/scripts/common/Macros.cmake:417 (find_package_with_ver)
  CMakeLists.txt:262 (core_require_dep)
```
So far the build has always worked, these libraries are installed:
```
dpkg -l | grep kiss
ii  libkissfft-dev:arm64                  131.1.0-3                           arm64        Mixed-radix Fast Fourier Transform library (development tools)
ii  libkissfft-dev:armhf                  131.1.0-3                           armhf        Mixed-radix Fast Fourier Transform library (development tools)
ii  libkissfft-float131:arm64             131.1.0-3                           arm64        Mixed-radix Fast Fourier Transform library
ii  libkissfft-float131:armhf             131.1.0-3                           armhf        Mixed-radix Fast Fourier Transform library
(amd64bookworm)root@vps01:/home/xbian/xbian-package-xbmc# 
```

BTW,  -DENABLE_INTERNAL_KISSFFT=ON is **not** set

**Comment by mkreisl** [comment]
Working again

**Comment by fuzzard** [comment]
Anyone have any opinion on this? Any improvements to the wording of the docs for linux platforms would be appreciated as well.

**Comment by neo1973** [comment]
Where is kissfft even used? The only place I can find is https://github.com/xbmc/xbmc/blob/master/xbmc/utils/rfft.h and `RFFT` itself doesn't seem to be used anywhere (besides its own unit test)?

**Comment by fuzzard** [comment]
Even better. Looks like once upon a time was used for vis addons - https://github.com/xbmc/xbmc/pull/7116
Maybe @notspiff can remember if it was all pulled out into just actual vis addons themselves, making this dead code

**Comment by fuzzard** [comment]
Heres a commit primed to remove it completely https://github.com/fuzzard/xbmc/commit/dd5be7f951d3c69beddd19649677773581372aaf

**Pull request closed without merging**
