### PR TITLE
[airplay] - restore ios 9 music streaming capability

### PR DESCRIPTION
**Pull request by Memphiz**
This 
1. Removes the ios8 compat setting and makes ios8 compat behavior the default one
2. Adds a setting which allows the user to disable video/pictures airplay capabilities which defaults to on
3. By disabling the new setting from 2. and in combination with the bumped libshairplay from this PR all ios9 users can restore at least music streaming features.

Though ios9 users will loose any sort of metadata when streaming music (no progress/duration info, no album thumb, no artist, no album, no title). Thats as far as we can get atm for ios9 clients.

@MartijnKaijser is it a problem to reuse those language ids? I guess until the language addons are synced users would get the old text for this setting - right?

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@Memphiz correct observation. Up to you if that's acceptable or not. Changing to another ID would fix it.

**Comment by Memphiz** [comment]
No biggy imo because the next transifex sync would return it into english for all languages right?

**Comment by MartijnKaijser** [comment]
yep (TM)

**Comment by Memphiz** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
can't think of anything in this PR that would affect bin addon building. I consider the build good. @un1versal your chance for nitpicks on the english texts of the settings if you don't mind ;)

**Comment by Memphiz** [comment]
@wsnipex sorry i think i forgot to pong you about that - can you update it in the kodibuntu repo please?

**Comment by Memphiz** [comment]
i mean the bumped libshairplay

**Comment by un1versal** [comment]
I never got a notification for mention PR shortly.

**Comment by wsnipex** [comment]
@Memphiz updated in nightly and unstable.
If there are no issues I'll push it to stable with the next beta - if I remember ;)

**Pull request merged**
