### PR TITLE
[binary addons] a few cmake fixes

### PR DESCRIPTION
**Pull request by Montellese**
Based on the comments in 068aafc23253ebe9c76abb2615599d9bbbcb69fa I tried the binary addons buildsystem again and found some oddities. The first two commits are actual fixes and the other two are cosmetics.

I've only tested this on win32.

### CODE REVIEW

**Comment by FernetMenta** [comment]
Thanks! Tested on Linux and I was able to build two addons after having cleared cmake/addons/addons.
If this folder already has some content from previous builds, cmake fails silently. Means it just ignored the additional or different addons. Scenario:
I work on pvr.vdr.vnsi and built this addon. This folder was created: cmake/addons/addons/pvr.vdr.vnsi. Now I switch to inputstream.mpd and build this. the folder inputstream.mpd won't get created as long addons/addons is not empty. There is no error on the output of cmake.

**Comment by wsnipex** [comment]
Did you bootstrap the addon repo? I am pretty sure it has to do with that as it worked fine before when we still had the addon definitions in kodi src

**Comment by Montellese** [comment]
@wsnipex: This is a case that never worked (at least for me). The problem is that we run cmake to generate the buildsystem on the `addons` directory and after the buildsystem has been generated you change the content of the `addons` directory. But cmake sees that the buildsystem has already been generated and doesn't care about the changes that have been made to the `addons` directory.

The case where there are multiple addon definitions available but you only build one and then later on another one should still work (and works fine for me on win32).

**Comment by FernetMenta** [comment]
@Montellese can we merge this?

**Comment by Montellese** [comment]
jenkins build and merge

**Pull request merged**
