### PR TITLE
[PVR] gui info: Fix 'PVR.IsTimeshift' (PVR_IS_TIMESHIFTING)

### PR DESCRIPTION
**Pull request by ksooo**
@FernetMenta fyi (and review).

### CODE REVIEW

**Comment by FernetMenta** [comment]
thanks! seems I did not resolve the merge conflict with new GUiInfoLabel.h correctly.

**Comment by ksooo** [comment]
@FernetMenta  BTW: Now, after extending pvr.hts and fixing the related kodi glitches I have the new timeshift stuff working (incl. your Confluence patch). Works just fine. UI could be improved (as we all know), but at least finally this is a start. Thx again.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
Jenkins errors are not related to this PR (adsp.* addon build failures).

**Comment by phil65** [comment]
@ksooo is there any confluence work already done for this? I could scratch that from my to-do list then. :)

**Comment by hudokkow** [comment]
@phil65 AFAIK, https://github.com/FernetMenta/xbmc/commit/5c95881d5c2e5d40b2559ca19caec928f5a49bdc is the only one

**Comment by phil65** [comment]
oh thanks, Fernet already showed that one to me but I assumed it was Nox because BigNoid was the committer. Will read properly next time :)

**Comment by ksooo** [comment]
@phil65 the commit from @FernetMenta you are referring to is not a PR and fernet has no plans to make it one as people in the forum did not accept the idea of having two progress bars on the OSD. To my knowledge nobody has done any Confluence work on this (with the goal to PR it).
 It would be great if you could keep this on your to-do list.

**Pull request merged**
