### PR TITLE
Fix: HAVE_LIBSSH Redefinition Warnings on Windows

### PR DESCRIPTION
**Pull request by wiromare**
@Paxxi

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
see
https://github.com/xbmc/xbmc/pull/10242

**Comment by garbear** [comment]
lol welcome to the party: https://github.com/garbear/xbmc/commit/f66344f

**Comment by wiromare** [comment]
ahahahaha :)

**Comment by MartijnKaijser** [comment]
fix is merged now :)

**Pull request closed without merging**
