### PR TITLE
addon fix status handler

### PR DESCRIPTION
**Pull request by FernetMenta**
alternative to https://github.com/xbmc/xbmc/pull/9761

@MartijnKaijser could you test this please?

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@FernetMenta it doesn't "crash"  anymore though i now get the OK dialog for each inputstream addon 3 times.
Entering add-on browser Kodi just locks up.

**Comment by MartijnKaijser** [comment]
hereś the logcat http://xbmclogs.com/p3m034qir

**Comment by FernetMenta** [comment]
@MartijnKaijser updated. could you try again?

**Comment by MartijnKaijser** [comment]
No crashes or lockups with this build. Also i do not get any OK dialog (if that was supposed to happen) about non working inputstream addons. Doesn't matter if they are disabled or enabled.
[logcat.txt](https://github.com/xbmc/xbmc/files/253503/logcat.txt)

**Comment by FernetMenta** [comment]
this works as expected. AddonManager is started before WindowManager and as a result the first error window is not displayed.

jenkins build this please

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
Great. Thanks.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by da-anda** [comment]
was just wondering if a kaitoast + eventlog wouldn't be a better approach to the OK dialogs. Opinions?

**Comment by FernetMenta** [comment]
IMO a kai toast is completely useless. we already have the same crap on installation of addons. if you miss to read it during that short while displayed, you won't know that installation has failed.

**Comment by da-anda** [comment]
for that we have the event log now, but I agree that this is a bit too hidden atm and we would need some more prominent notification center.

**Comment by FernetMenta** [comment]
event log is not appropriate here. you can't expect a user to browse the event log after every task. while working with addons it happened quite often to me that I was wondering that an addon was not available after install because the crappy kaitoast only displays the error for a very short time.
there is zero reason for an asynchronous user feedback. you won't watch a movie while waiting for the addon install to be finished, right?

**Comment by ksooo** [comment]
I see this exactly like @FernetMenta does.

**Comment by Montellese** [comment]
You can still put it into the event log so that when the user goes there he can see that something went wrong after it happened.
From what I understand right now there's no user feedback at all because the ok dialog gets eaten by the fact the the window manager isn't initialized yet when the error happens.

**Comment by FernetMenta** [comment]
@Montellese that's correct for startup. For addon installation we should drop kaitoast in favour of DialogOK.

**Comment by MartijnKaijser** [comment]
I would agree that when installing an add-on manually an ok dialog would fit better regarding feedback.

**Pull request merged**
