### PR TITLE
[confluence] get rid of iCCP warnings from libpng

### PR DESCRIPTION
**Pull request by mkortstiege**
Removed junk added by image tools (Photoshop most likely) to get rid of sRGB profile warnings ..

> libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

### CODE REVIEW

**Comment by mkortstiege** [comment]
Ping @ronie and @BigNoid

**Comment by topfs2** [comment]
Could this not be done during bake instead? I.e. when making the xbt we add
a strip of metadata before store?

**Comment by mkortstiege** [comment]
> Could this not be done during bake instead? I.e. when making the xbt we add
a strip of metadata before store?

Not sure if this is happening for images in xbt as well, will check.

**Comment by topfs2** [comment]
Oh wait no that's true it won't, we decode them before baking and then
compress the xbt iirc.

**Comment by mkortstiege** [comment]
Yep, that's what i thought as well. So i think best is to do it once now.

**Comment by ronie** [comment]
if texturepacker doesn't choke on the changes, i'm fine with it

**Comment by mkortstiege** [comment]
> if texturepacker doesn't choke on the changes, i'm fine with it

Could you give it a try please?

**Comment by ronie** [comment]
builds and runs fine on linux.

**Comment by mkortstiege** [comment]
Great, thanks for testing.

**Pull request merged**
