### PR TITLE
[omxplayer] Skip packet concatenation for WMAV2 files

### PR DESCRIPTION
**Pull request by popcornmix**
See: http://forum.kodi.tv/showthread.php?tid=212552

### CODE REVIEW

**Comment by FernetMenta** [comment]
+1

**Comment by popcornmix** [comment]
jenkins build and merge

**Comment by MartijnKaijser** [comment]
@popcornmix please login to jenkins.kodi.tv one time and made yourself public member XBMC

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
