### PR TITLE
VideoPlayer: passthrough improvements

### PR DESCRIPTION
**Pull request by FernetMenta**
this improves sync of passthrough audio
- passthrough decoder handles pts itself, makes error prone PTSInput queue obsolete
- AE sync by using IEC pause bursts

### CODE REVIEW

**Comment by popcornmix** [comment]
This kills playback with passthrough for me:
```kodi.bin: Utils/AEChannelInfo.cpp:215: CAEChannelInfo& CAEChannelInfo::operator+=(const AEChannel&): Assertion `m_channelCount < AE_CH_MAX' failed.```
http://paste.ubuntu.com/14591011/

**Comment by FernetMenta** [comment]
are you sure you tested exactly this version?

**Comment by popcornmix** [comment]
Yes, deleted previous version and grabbed this PR. My PLL code is not present.

**Comment by popcornmix** [comment]
Just the first commit played for a bit then stalled.
First and second commit gives assert.
Just the third and fourth commit are okay.

**Comment by FernetMenta** [comment]
can you debug into this and send a fix. I can't reproduce here

**Comment by FernetMenta** [comment]
@popcornmix the correct version is still here, I forgot to force push ...
will do in a minute

**Comment by popcornmix** [comment]
Working better now.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by popcornmix** [comment]
Tested some more last night and DTS and AC3 passthrough, as well as non-passthrough seemed good on Pi. This was in last night's Milhouse build without any immediate complaints.

**Comment by FernetMenta** [comment]
@popcornmix @fritsch updated

**Comment by popcornmix** [comment]
Latest version causes Yamaha receiver to switch from DTS or Dolby Digital to PCM when paused (and briefly when seeking). I also get a squawk when resuming form pause, so I think something is still not right.

**Comment by FernetMenta** [comment]
an IEC pause burst is not codec branded. does it just continue was it was before the pause? what exactly do you send in OMX?

**Comment by FernetMenta** [comment]
I try to set all the stuffing bits to zero

**Comment by popcornmix** [comment]
Long ago we used to handle outputting silence (for pausing or sync) by outputting a pre-canned encoded (as DTS or AC3) silence packet. That worked for most users but a few reports noise or losing sync with receiver.
This is presumably down to differences in the encoding parameters of the real audio stream and the faked silence stream (e.g. codec header bytes being different).
Now, we just overwrite the header with the pause burst header (i.e. set Pc to 3) but still use the normal frame sizing. The payload is set to zeros.

That resolved the noise/sync reports. The Yamaha receiver continues to show DTS or AC3 (although the "cinema dsp" light does go off) when paused.

It doesn't make use of arbitrarily sized packets - the pause bursts are always the normal frame size. I don't see a reason for that to be a problem, although very long bursts may be an issue ("repetition period") - I'm not sure what the maximum duration of a pause burst can be with this PR.

**Comment by FernetMenta** [comment]
@popcornmix @fritsch 
I pushed an update. Repetition period of a pause burst is only 3-4 frames depending on the encoded format.
My amp does not fall to pcm during pause. The stuttering after resume should be fixes as well.

**Comment by fritsch** [comment]
Thx much. Do you want to add the "stop pause packages" to the interface? If you think this is the way to go then let's do it, before I waste more time into AT's silence handling :-)

**Comment by fritsch** [comment]
Tested on Marantz NR1402 with dolby digital. The AVR is keeping the signal, even when paused, display still says: Dolby Digital

AC3: fine, is kept, resumes correctly
DTS: fine, is kept, resumes correctly
DTS-HD: fine, is kept, resumes correctly
TrueHD: fine at first, short stutter after resume -> then segfault: http://paste.ubuntu.com/14608028/
EAC3 (DDD+): fine, is kept, resumes correctly

**Comment by popcornmix** [comment]
I've tested on my Onkyo receiver at home and that continues to display DTS or Dolby when paused even with the earlier version of this PR that the Yamaha receiver dropped back to PCM with.
I won't be able to test with Yamaha until back at work on Monday.

I can say that with the latest PR the Onkyo seems to be happy.

There were a couple of [reports](http://forum.kodi.tv/showthread.php?tid=250817&pid=2223394#pid2223394) from last night's version of this PR about passthrough not working. We can see if that improves with today's version of the PR in tonight's build.

**Comment by FernetMenta** [comment]
@fritsch your segfault is unrelated to this change. did you look into the bt? it crashed in ffmpeg image loader

**Comment by fritsch** [comment]
That's memory that gets corrupted. Just play a truehd sample, press pause, wait a bit, resume - it starts to play, crackles a bit and then this happens :-)

**Comment by fritsch** [comment]
I can reproduce the "crackle" and also the segfault, but the segfault is not related
>18:56:08 T:140235355420416  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: SMPTE VC-1
18:56:08 T:140235355420416   ERROR: ffmpeg[7F8B168B7700]: [IMGUTILS] Picture size 0x1080 is invalid
18:56:08 T:140235355420416   DEBUG: ffmpeg[7F8B168B7700]: [vc1] Ignoring invalid width/height values
18:56:08 T:140235355420416   ERROR: ffmpeg[7F8B168B7700]: [IMGUTILS] Picture size 0x0 is invalid
18:56:08 T:140235355420416   DEBUG: CDVDVideoCodecFFmpeg::Open() Unable to open codec
18:56:08 T:140235355420416   DEBUG: FactoryCodec - Video:  - Failed
18:56:08 T:140235355420416   ERROR: Unsupported video codec

That's an issue with one of my samples of course.

**Comment by FernetMenta** [comment]
can you try again with updated PR?

**Comment by FernetMenta** [comment]
@fritsch 
>  Do you want to add the "stop sending pause packages in non IEC raw mode" to the code?

I need to think more about this. Let's do this separately to this PR.

**Comment by fritsch** [comment]
Thanks much, yes.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by fritsch** [comment]
Concerning the TrueHD test. Sadly it does not fix it yet. It stutters a bit and AVR looses Sync in a pulsing fashion with TrueHD.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
ignore build error

**Pull request merged**
