### PR TITLE
[pvr] fixed regression in CGUIInfoManager::GetItemLabel, LISTITEM_NEXT_*

### PR DESCRIPTION
**Pull request by ksooo**
regression introduced by https://github.com/xbmc/xbmc/commit/bcef4b1279d4321a276a47bf7ad20f2460af4374 

Stupid copy/paste error. Thx @xhaggi for digging this one out.

@xhaggi your button.

### CODE REVIEW

**Comment by ksooo** [comment]
jenkins build this please

**Comment by xhaggi** [comment]
thanks looks better now :)

**Comment by ksooo** [comment]
@xhaggi okay. Are you going to merge this or shall I?

**Comment by ksooo** [comment]
Wow. Do you ever sleep?

**Comment by xhaggi** [comment]
no ;)

**Pull request merged**
