### PR TITLE
[WIP] WinSystem: pass RESOLUTION_INFO as const reference where applicable

### PR DESCRIPTION
**Pull request by MaxKellermann**
These methods are not supposed to edit the object.

NOTE: I did not build many of the modified WinSystems; Jenkins may find build failures, and I'll fix them. Don't merge just yet until Jenkins is green.

### CODE REVIEW

**Review by FernetMenta — APPROVED** [review]

**Comment by MaxKellermann** [comment]
Hm, apparently on Windows (both Win32 and Win10), `SetFullScreen()` edits the parameter.
```
// entering to stereo mode, limit resolution to 1080p@23.976
if (stereoChange && !IsStereoEnabled() && res.iWidth > 1280)
{
  res = CDisplaySettings::GetInstance().GetResolutionInfo(CResolutionUtils::ChooseBestResolution(24.f / 1.001f, 1920, true));
}
```
So this PR may be a bad idea after all.

**Comment by afedchin** [comment]
@MaxKellermann you can try this https://gist.github.com/afedchin/bdeb07b8da669795de312d0b21afaf05 to fix windows build and similar for uwp

**Comment by pkerling** [comment]
Thanks for the PR. Note: The whole `RESOLUTION` and `RESOLUTION_INFO` area is very ugly and will probably be redone entirely in the long run. So you might want to focus your attention at other things in the meantime :-)

> Don't merge just yet until Jenkins is green.

As a general rule, we don't merge unless Jenkins is green or the failures are clearly unrelated.

**Review by garbear — APPROVED** [review]
> So this PR may be a bad idea after all.

Or this is the correct approach and the original code should be fixed :)

**Comment by MaxKellermann** [comment]
Rebased, but Windows build failures not yet fixed. No candidate for merging yet.

**Comment by Rechi** [comment]
@MaxKellermann have you applied the patch afedchin posted?

**Comment by MaxKellermann** [comment]
No, this patch looks seriously broken:
```
+ RESOLUTION_INFO& resolution = { 0 };
```
I didn't try, but I bet this doesn't even compile. You can't initialize a reference that way.

I suppose this wasn't meant to be a reference, but a regular variable. So this is a local copy of the parameter, and its modified value is discard at the end of the method. This means that the caller doesn't see the modifications. And this means that it changes the behavior. I'm not sure if that is intended/correct. Who can tell?
(When I refactor code, I try not to change behavior, and this patch rang a big alarm bell for me.)

**Comment by garbear** [comment]
Just factor out the mutable part: https://github.com/garbear/xbmc/commit/resinfo_mutable

Whether it changes behavior should be analyzed, but not much (any?) state is modified before the refactored lines, so we should be good.

**Comment by phunkyfish** [comment]
@MaxKellermann do you want to progress this PR?

**Comment by MaxKellermann** [comment]
Oh, this was still open? No, I grew tired of hacking Kodi long ago.

**Pull request closed without merging**
