### PR TITLE
CProfileManager: do not wait for bool uiInitializationFinished

### PR DESCRIPTION
**Pull request by samnazarko**
## Description

Following on from #16840, we need one more change to ensure that skins are reloaded properly when profiles are used.

## Motivation and Context

The bool will cause a race which will prevent the skin from being reloaded properly. After discussing with @garbear in Slack, it's evident that the state is used in several places. I'm not sure what this bool is meant to guard in CProfileManager. After removing, skin reloads are handled properly with profile changes. 

## How Has This Been Tested?

This change has been active on OSMC for several months without reports of ill effect. As we are still pre-alpha, it would be good to test this or explore how to fix this long standing issue. If the fix is appropriate then a backport is also needed.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by garbear** [comment]
This bool is part of a rudimentary, asynchronous (non-finite) state machine, with control and state spread through out the code.

The goal is to manage the state of three parts: GUI logic, profiles, and application logic. Logic for these is allowed to proceed in parallel, hence the race conditions.

Synchronization initially happens around the `GUI_MSG_UI_READY` message. Think of the components as threads, and `GUI_MSG_UI_READY` as the `.join()` function. The components need to agree to send this message exactly once between the three of them. You can see where control changes threads in each component, and where it ends up, by [searching this message](https://github.com/xbmc/xbmc/search?q=GUI_MSG_UI_READY&unscoped_q=GUI_MSG_UI_READY). If you trace control backwards from the message, you'll see how much branching is done to determine whether to send this message. This is all asynchronous, so state is constantly changing in random and unpredictable ways.

To solve this, we really need to make the state machine synchronous. Encapsulate state, add a monitor, and make control go through the FSM. Otherwise touching state anywhere will break the delicate balance of the current code. Did you test with the startup animation window enabled? It looks like we branch on this in all three components, so logic will need to change in all three.

**Comment by phunkyfish** [comment]
@samnazarko any feedback on @garbear's comment?

**Comment by samnazarko** [comment]
It makes sense, but I think the changes needed are too large for v18. We could look at fixing it for v19 though.

I didn't experience a problem with the startup video enabled.

**Comment by phunkyfish** [comment]
So you would propose this fix for Leia and doing it properly for Matrix?

**Comment by samnazarko** [comment]
Possibly -- it fixes the issue on Leia and we've had this in OSMC builds for a long time without complaints.  The fix for Matrix also depends on whether we keep profiles.

**Comment by phunkyfish** [comment]
@DaveTBlake @garbear would you like this in Leia for 18.7?

**Comment by garbear** [comment]
I'm split - it fixes a valid problem for multiple people, but we're pulling on a string that could have repercussions elsewhere. I would say merge and backport, then list some edge cases and see what testers uncover.

**Comment by garbear** [comment]
@samnazarko with this change, our delicate juggling to make sure GUI_MSG_UI_READY is only sent once. With this change, under some unknown edge conditions, it might be sent more than once. Do you see any issues if the handler [here](https://github.com/xbmc/xbmc/blob/5200daeb6ace6b32752ecb6d53bd205f4f81d92d/xbmc/Application.cpp#L3759) is called more than once?

**Comment by samnazarko** [comment]
No -- I don't see a problem with multiple sends. I'd say we have a reasonable guard presently however. 

I've never seen a regression from pumping additional UI_READY events. Current timing may be luck. 

Should we chuck it in v19 and see if we get any problematic reports? We're not even a1 yet, so can easily revert if necessary. 

I suppose it needs to go in to v19 as well as v18 or we could have another profile fix/improvement that regresses.

**Comment by garbear** [comment]
OK, I'll merge and we can backport to 18 if we don't hear of any problems

**Comment by garbear** [comment]
jenkins build this please

**Comment by DaVukovic** [comment]
Great. This works like a charm. @samnazarko do you plan to backport that to Kodi 18? As this is really annoying and we could drop the workaround with `autoexec.py` amd `reloadskin()` at our wiki

**Comment by samnazarko** [comment]
I've backported this for v18.

**Pull request merged**
