### PR TITLE
add support for external PGS/.sup subtitles

### PR DESCRIPTION
**Pull request by taxigps**
use `CDVDDemuxFFmpeg` to demux PGS subtitle in .sup file.

### CODE REVIEW

**Comment by FernetMenta** [comment]
please get in touch with @ace20022 . the strategy for this is using a multi-source demuxer.

**Comment by FernetMenta** [comment]
I think this is his current branch for this work https://github.com/ace20022/xbmc/tree/roundrobin

**Comment by ace20022** [comment]
It's branch ext3a, plus some local changes, and the pr is https://github.com/xbmc/xbmc/pull/7171. I wait for @FernetMenta dvdplayer rewrite and I maybe want to rewrite demuxers first. Or is the dvdplayer rewrite independent?

**Comment by taxigps** [comment]
@ace20022 so wait after your pr get in. or you will do this with external audio support as well?

**Comment by ace20022** [comment]
@taxigps why did you close it?

**Comment by taxigps** [comment]
It'll easy to support this by multi-source demuxer you working for now. so I think may be not need this pr any more.

**Comment by ace20022** [comment]
Okay, I feared that you lost interest ;)

**Comment by taxigps** [comment]
any way to reopen this?

**Comment by hudokkow** [comment]
Apparently not which is weird because de branch exists in your repo.

**Pull request closed without merging**
