### PR TITLE
AEEncoderFFmpeg: Make bitrate platform replacable

### PR DESCRIPTION
**Pull request by fritsch**
Use cmake / autotools to generate the define for us depending on which platform we run.

384000 on Android, 64000 on the rest

### CODE REVIEW

**Comment by fritsch** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
behavior must not be hidden in the build system. it has to be clear what parts of the app are overridden for platforms. you could define the variable in an separate file in a subfolder

**Comment by fritsch** [comment]
Thanks for that feedback. Looking forward when your remove the build system behaviour of your alternative overrides approach.

**Comment by wsnipex** [comment]
>behavior must not be hidden in the build system. it has to be clear what parts of the app are overridden for platforms. you could define the variable in an separate file in a subfolder

you are aware that tons of defines come from the build system? also the override crap depends on the build system...

**Comment by MrMC** [comment]
hahahahha :)

**Comment by FernetMenta** [comment]
@fetzerch and I are working on a solution

**Pull request closed without merging**
