### PR TITLE
Added Russian translation to the shortcut comment

### PR DESCRIPTION
**Pull request by TotalCaesar659**
## Description

This PR adds Russian translation to the shortcut comment.

## Motivation and Context

It updates multilinguality of Kodi for non-English speakers.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by hudokkow** [comment]
@wsnipex?

**Comment by wsnipex** [comment]
are you asking me to verify the text or if the change is ok? ;)
We should probably add a lot more languages here

**Comment by hudokkow** [comment]
Heheh, if change is OK! Unless you speak Russian.

**Comment by codesnake** [comment]
I speak Russian. And the translation looks good for me.

**Comment by wsnipex** [comment]
the change is ok, but as said, we should add a lot more languages once we start...

**Comment by TotalCaesar659** [comment]
>the change is ok, but as said, we should add a lot more languages once we start...
This is strange. Why don't you add existing translation for waiting another ones? After some tome, this PR will be on last pages, where nobody looks. And everyone'll forget about it.

**Pull request merged**
