### PR TITLE
VideoLibrary: check boolean option values

### LINKED ISSUE #16761: VideoLibrary.Export ignores option values (kodi 18.4-5~buster)
### Describe the bug

I've updated to 18.4 and jsonrpc method I used to save `.nfo` files aside each movie/tv seems to ignore `options` passed to it. In fact, the behavior is like it has all three options "enabled"! :(

The request I make:
```json
{
    "jsonrpc":"2.0",
    "method":"VideoLibrary.Export",
    "params":{
        "options": {
            "overwrite": false,
            "actorthumbs": false,
            "images": false
        }
    },
    "id":1
}
```

It's based on documentation from:
- https://kodi.wiki/view/JSON-RPC_API/v6#VideoLibrary.Export

This worked as expected with the previous version I had installed (17.x)

Now it does exactly the opposite of what I want:
1. do not overwrite `.nfo` files -> it overwrites all `.nfo` files
2. do not create .actors folder -> it creates .actors folder
3. do not create images -> it creates fanart, poster, etc images

### To Reproduce
1. enable JSON RPC interface
2. send the JSON RPC to the Kodi 18.4 
2. inspect the behavior

### Your Environment
Used Operating system:

 - [x] Linux
 - [x] Raspberry-Pi
   - Operating system version/name: Raspbian GNU/Linux 10 (buster)
   - Kodi version: 2:18.4-5~buster

### PR DESCRIPTION
**Pull request by glensc**
The previous implementation of `VideoLibrary.Export` checked the existence of option keys, instead of their boolean values.

- [x] VideoLibrary: check boolean option values
- [x] AudioLibrary: check boolean option values
- [x] Bump JSONRPC_VERSION to 10.6.1 due internal changes of C*Library::Export()

Fixes https://github.com/xbmc/xbmc/issues/16761

### CODE REVIEW

**Comment by glensc** [comment]
I'm not aware of the internals, should the `isMember` check be kept as well, or `asBoolean` already covers that check?

**Comment by a1rwulf** [comment]
> I'm not aware of the internals, should the `isMember` check be kept as well, or `asBoolean` already covers that check?

If you don't specify the option in the request and it doesn't crash, everything is fine ;-)

**Comment by DaveTBlake** [comment]
As a change to the way a JSON call is impemenented internally this also needs a patch bump to the JSON version

**Comment by glensc** [comment]
Alright then, I made the suggested and requested changes.

I see that CI failed on initial changes:
- https://jenkins.kodi.tv/job/BuildMulti-PR/13489/

Can I download the build result and execute on my machine to easily test out if mu changes crash or not?

**Comment by glensc** [comment]
Oh, the build in https://github.com/milaq/kodi-headless docker took ages (3 hours based on my previous note post date?), as it built dependencies also from scratch, So I ended up building rpm for PLD Linux (https://github.com/pld-linux/kodi) and putting that to docker container instead.

... and then figured the jsonrpc command does nothing if library is empty. Nothing got logged, absolutely nothing. But at least it did not crash! :)

Will continue later by adding something to the library...

**Comment by glensc** [comment]
I'm pretty sure the win build failures are not related to this PR.

**Comment by glensc** [comment]
@jenkins4kodi rebased. when this gets merged? I would rather not rebase again.

**Comment by rmrector** [comment]
jenkins build this please

**Comment by rmrector** [comment]
Thanks for the PR, sorry the merge was delayed.

**Pull request merged**
