### PR TITLE
[tvOS] Fix wrong PVR addons path when comming from home TV/Radio tab

### PR DESCRIPTION
**Pull request by sy6sy2**
## Description

On tvOS, PVR add-ons are compiled and embedded with the deb file, so when the user want to enable a PVR add-on he needs to go in `Add-ons --> My add-ons --> PVR clients` and NOT IN `Add-ons --> Install from repository --> PVR clients`.

When you start from a fresh install and if you go in `Home --> TV`, Kodi will tell you that you need to set up a PVR add-on, then you have a button to directly go in PVR add-on section.
But this button points to `Add-ons --> Install from repository --> PVR clients` instead of `Add-ons --> My add-ons --> PVR clients`. So currently, when the user click on this button he can't see anything and he thinks that there is no PVR add-on on tvOS.

## Motivation and context

Solve the issue described above and also remove user confusion like this one https://github.com/kodi-pvr/pvr.iptvsimple/issues/525.

## How has this been tested?

On tvOS.

## What is the effect on users?

No more empty directory when user want to enable a PVR add-on from the TV home view.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
can't comment on the code change, but I think this should be done for iOS as well because it uses the same approach

**Comment by sy6sy2** [comment]
Yes I will also try on iOS if the bug is also present with estouchy skin.
Just want to be sure that the code change is correct first, I never modify skin stuff.

**Comment by ksooo** [comment]
Instead of fixing this in (various) skins in a platform dependent way, how about introducing a "variable" in the core code that points to the path where to look for addons to install?

**Review by ksooo — COMMENTED** [review]
Although this would be more work, I think it would be cleaner to fix this in the core and to keep the skins OS-independent here.

**Comment by howie-f** [comment]
> fix this in the core

agreed, i suspect it is a problem for UWP also

**Comment by sy6sy2** [comment]
Agree with the idea of setting a variable in core, but I have absolutely no idea how to expose the variable from core to skins 😕

**Comment by ksooo** [comment]
> but I have absolutely no idea how to expose the variable from core to skins

 Maybe I can help with this, but I'm very busy with real life atm. So it can take some time.

**Comment by howie-f** [comment]
well, let me try to help.
first we store the correct path per platform, either `addons://all/` or `addons://user/` in a member `m_PVRAddonsPath` defined in AddonManager (like it is similarly done here for count of available addon updates -> https://github.com/xbmc/xbmc/pull/18591). Maybe set this member in `CAddonMgr.Init()` by a call to the platform specific methods.

after that expose to the gui via InfoManager like in this example https://github.com/xbmc/xbmc/pull/18546/commits/72ae2802f425f257c6e3f5f623894e6eaec0dc45. hope it's the correct approach, that's how i would try it ;)

**Comment by ksooo** [comment]
> first we store the correct path per platform

yep.

> after that expose to the gui via InfoManager 

I would choose a different approach. 
The skin code could contain something like "ActivateWindow(addonbrowser,addons://default_addons_package_location/kodi.pvrclient,return)"
The Addon browser window resolves this URL (well, the default_addons_package_location part) in a platform specific way and opens the resolved URL.

**Comment by ksooo** [comment]
Can somebody shed some light on the restrictions on TVOS (and UWP), please? Is it that users cannot install add-ons by themself from zip/repository? Can they only enable/disable what has been pre-bundled with the kodi installation package? Is it just binary add-ons or all kind of add-ons?

**Comment by howie-f** [comment]
@ksooo 
yes, for TVOS/UWP at least this is the case. no binary add-ons can be installed from repositories. all pvr.* are bundled on this platform and you need to enable the one you want. this was the reason for disabling the "auto-enable and configure at startup" feature. ref https://github.com/xbmc/xbmc/pull/19091.
python add-ons can be installed normally though

**Comment by ksooo** [comment]
> for TVOS/UWP

 Also iOS ?

**Comment by sy6sy2** [comment]
> > for TVOS/UWP
> 
> Also iOS ?

**Comment by sy6sy2** [comment]
> > for TVOS/UWP
> 
> Also iOS ?

Yes also iOS.
> 
> > no binary add-ons can be installed from repositories.
> 
> Only from repos? Or also not from zip files?

If I'm correct, the problem is not the install method, but the problem is that binaries need to be signed to work, this why they are bundled with the package.
But you can install Python add-ons from ZIP and/or repo.


BTW, thank guys for the help, I will try to apply your ideas soon.

**Comment by ksooo** [comment]
> I will try to apply your ideas soon.

I'm already working on it. PR will be ready soon.

**Comment by sy6sy2** [comment]
Oh, thank you 🙏🏻

**Comment by ksooo** [comment]
> all pvr.* are bundled

What about other binary add-ons, like vizualizations, screen savers, game add-ons, ...? Are they all bundled?

**Comment by sy6sy2** [comment]
I never pay much attention about these add-ons, but based on what I see on my iPhone I can say yes. (8 visualizations add-on, 3 screen savers and 2048 game)

**Comment by ksooo** [comment]
Can binary-addons installed from zip files on those platforms?

**Comment by sy6sy2** [comment]
I can only speak for iOS and tvOS.
I guess that if your device is not jailbroken it will be really hard (maybe impossible?) @kambala-decapitator can confirm.
Concerning jailbroken devices, I never tried but I would say yes because you can fake-sign the binary directly from the device.
But I am not sure this something end users want to do. Only for dev purpose maybe... but it's not something easy and "normal".

**Comment by howie-f** [comment]
sorry don‘t have an uwp install at hand at the moment, i know only about the pvr‘s

**Comment by kambala-decapitator** [comment]
> If I'm correct, the problem is not the install method, but the problem is that binaries need to be signed to work, this why they are bundled with the package.

yes, that's the reason on iOS/tvOS

**Comment by ksooo** [comment]
> problem is that binaries need to be signed to work

Maybe a dumb question: Is it not possible to sign the binaries contained in the addons package?

**Comment by kambala-decapitator** [comment]
> > problem is that binaries need to be signed to work
> 
> Maybe a dumb question: Is it not possible to sign the binaries contained in the addons package?

it's not possible to perform on-device signing afaik (macOS is needed). And we (Kodi) can't sign them beforehand because every user signs apps with his own private key, that's why iOS/tvOS builds are distributed unsigned as well.

**Comment by ksooo** [comment]
Thanks for the explanation.

**Comment by ksooo** [comment]
@sy6sy2 #19928 is merged. I think we can close this PR, no?

**Comment by sy6sy2** [comment]
> @sy6sy2 #19928 is merged. I think we can close this PR, no?

Yes of course, thank you for the PR!

**Pull request closed without merging**
