### PR TITLE
[Fix] Attempts to fix random Jenkins errors building FFmpeg Windows libs

### PR DESCRIPTION
**Pull request by thexai**
## Description
Backport of https://github.com/xbmc/xbmc/pull/20767

## Motivation and context

There have been no Jenkins glitches since https://github.com/xbmc/xbmc/pull/20767 was merged. Although because the Matrix builds keep reinstalling MSYS2 every time, it is likely that it will fail sooner or later. It will be difficult to draw conclusions because the failure may be caused by the old script in Matrix or that the new one does not solve 100% all cases.

Better to have the same Jenkins script in Matrix / master to keep things simple. In addition, the new one speeds up the compilation of all Windows variants by several minutes.

## What is the effect on users?
N/A

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by thexai** [comment]
In case of Matrix branch since has different FFmpeg version that master `ffmpeg-4.3.2-Matrix-19.2` is rebuild:

(only when previous Jenkins build in that slot was master branch)

But MSYS2 full reinstallation steep is skipped. 

```
10:30:08 f:\builds\workspace\WIN-64>f:\builds\workspace\WIN-64\tools\buildsteps\windows\x64\download-msys2.bat sh 
10:30:08 -------------------------------------------------------------------------------
10:30:08  Downloading will be performed from mirror http://mirrors.kodi.tv
10:30:08 -------------------------------------------------------------------------------
10:30:08 -------------------------------------------------------------------------------
10:30:08 update pacman mirrors
10:30:08 -------------------------------------------------------------------------------
10:30:08 -------------------------------------------------------------------------------
10:30:08 create local win32 folders
10:30:08 -------------------------------------------------------------------------------
10:30:08 -------------------------------------------------------------------------------
10:30:08 create local x64 folders
10:30:08 -------------------------------------------------------------------------------
10:30:08 -------------------------------------------------------------------------------
10:30:08 - write profile for 32 bit compiling
10:30:08 -------------------------------------------------------------------------------
10:30:08 -------------------------------------------------------------------------------
10:30:08 - write profile for 64 bit compiling
10:30:08 -------------------------------------------------------------------------------
10:30:08 -------------------------------------------------------------------------------
10:30:08 install msys2 system done
10:30:08 -------------------------------------------------------------------------------
10:30:08 
10:30:08 f:\builds\workspace\WIN-64\project\BuildDependencies>POPD
10:30:09 [WIN-64] $ cmd /c call C:\WINDOWS\TEMP\jenkins2423716291439924295.bat
10:30:09 
10:30:09 f:\builds\workspace\WIN-64>f:\builds\workspace\WIN-64\tools\buildsteps\windows\x64\make-mingwlibs.bat noprompt noclean sh 
10:30:09 **********************************************************************
10:30:09 ** Visual Studio 2017 Developer Command Prompt v15.9.38
10:30:09 ** Copyright (c) 2017 Microsoft Corporation
10:30:09 **********************************************************************
10:30:10 [vcvarsall.bat] Environment initialized for: 'x64'
10:30:10 starting sh shell
10:30:10 sh: cannot set terminal process group (-1): Inappropriate ioctl for device
10:30:10 sh: no job control in this shell
10:30:12 -------------------------------------------------------------------------------
10:30:12  compiling mingw libs x64
10:30:12 
10:30:12  NOPROMPT  = 1
10:30:12  MAKECLEAN = noclean
10:30:12  WORKSPACE = f:\builds\workspace\WIN-64
10:30:12 
10:30:12 -------------------------------------------------------------------------------
10:30:12 ]0;building FFmpeg x64-------------------------------------------------
10:30:12  building FFmpeg x64
10:30:12 -------------------------------------------------
10:30:14 [1mffmpeg-4.3.2-Matrix-19.2(B[m ...................................... [[34mExtracting(B[m]
10:30:18 Applying patch /xbmc/tools/buildsteps/windows/patches/0001-ffmpeg-detect-openssl.patch
10:30:18 (Stripping trailing CRs from patch; use --binary to disable.)
10:30:18 patching file configure
10:30:18 Applying patch /xbmc/tools/buildsteps/windows/patches/0002-ffmpeg-zlib-config-conflict.patch
10:30:18 (Stripping trailing CRs from patch; use --binary to disable.)
10:30:18 patching file configure
10:30:18 Hunk #1 succeeded at 7555 (offset 2 lines).
10:30:18 Applying patch /xbmc/tools/buildsteps/windows/patches/0003-ffmpeg-static.patch
10:30:18 (Stripping trailing CRs from patch; use --binary to disable.)
10:30:18 patching file configure
10:30:18 Applying patch /xbmc/tools/buildsteps/windows/patches/0005-ffmpeg-detect-dav1d.patch
10:30:18 (Stripping trailing CRs from patch; use --binary to disable.)
10:30:18 patching file configure
10:30:18 Hunk #1 succeeded at 6299 (offset 4 lines).
10:30:18 [1mffmpeg-4.3.2-Matrix-19.2 (x64)(B[m ............................... [[34mConfiguring(B[m]
10:32:24 install prefix            /xbmc/project/BuildDependencies/mingwlibs/x64
10:32:24 source path               /build/src/ffmpeg-bdc2f5920e
10:32:24 C compiler                cl.exe
10:32:24 C library                 msvcrt
10:32:24 ARCH                      x86 (generic)
10:32:24 big-endian                no
10:32:24 runtime cpu detection     yes
10:32:24 standalone assembly       yes
. . . 
```

**Review by wsnipex — APPROVED** [review]
maybe consider refreshing the ffmpeg patches, not a blocker though

**Comment by thexai** [comment]
These patches are applied every time that ffmpeg is compiled. I'm not sure what you mean with refreshing patches. Patches itself changes when ffmpeg version is bumped only (AFAIK).

e.g.:
https://github.com/xbmc/xbmc/commits/Matrix/tools/buildsteps/windows/patches/0001-ffmpeg-detect-openssl.patch

**Comment by wsnipex** [comment]
with refresh patches I mean, making sure they apply cleanly:

> 10:30:18 patching file configure
> 10:30:18 Hunk #1 succeeded at 6299 (offset 4 lines).

**Comment by thexai** [comment]
Well, this will surely be fixed by someone when the ffmpeg version are increased or if one day it stops working...  😏

**Pull request merged**
