### PR TITLE
[Android] CFileAndroidApp::ReadIcon: Add support for icons provided a…

### PR DESCRIPTION
**Pull request by ksooo**
…s android.graphics.drawable.AdaptiveIconDrawable.

Fixes missing icons for Android Apps - for example in the listing of Android Apps under Estuary Home -> Add-ons -> Android Apps. In fact affected apps all had the Kodi standard folder icon.

This PR adds support by adding support for creating a bitmap from an android.graphics.drawable.AdaptiveIconDrawable instance.

This PR depends on https://github.com/xbmc/libandroidjni/pull/35.

Not sure who could review this, maybe @joseluismarti or @thexai?

### CODE REVIEW

**Comment by joseluismarti** [comment]
Hi @ksooo

Before: 5 out of 15 apps don't show their icon.

After: only one, Screensaver app. In system settings does show the icon.

**Comment by fuzzard** [comment]
Did you build with the appropriate libandroidjni ? IE don't use the artifact here, you need to build libandroidjni with the pr mentioned, then build Kodi against that.

**Comment by ksooo** [comment]
> After: only one, Screensaver app. In system settings does show the icon.

@joseluismarti wait, you mean it does not work for you at all? Less icons than before? I tested on my shield and all (!) app icons appear. Before there were at least 5 missing. 

Are you sure you tested a clean build, just the libandroidjni bump plus this Kodi PR ontop of master?

Any chance yo can debug the this, put in some debug logs, etc so we get an idea what goes wrong on your end?

**Comment by joseluismarti** [comment]
After: only 1 out of 15 don't show the icon, works fine :)

**Comment by ksooo** [comment]
> After: only 1 out of 15 don't show the icon, works fine :)

 Alright. I completely misunderstood your first comment, then.

**Comment by ksooo** [comment]
@joseluismarti  could you debug what goes wrong with the 1 app not showing an icon? 

Look at CFileAndroidApp::ReadIcon: Do we get a Drawable out of res.getDrawableForDensity? If yes, is it something different from android.graphics.drawable.AdaptiveIconDrawable or android.graphics.drawable.BitmapDrawable? If yes, what?

**Comment by ksooo** [comment]
@joseluismarti could you provide a screenshot showing the last missing icon in Kodi?

**Comment by matthuisman** [comment]
Nice work!. This has bugged me for awhile but never enough to open an issue haha.

Are you the new Kodi android dev? Hehe

**Comment by ksooo** [comment]
> Or is that just temporary so it builds and will be changed once other pr merged?

It's just temporary. Will be changed before merge.

**Comment by ksooo** [comment]
WIN-64 Jenkins error is unrelated.

```
07:29:20 [  FAILED  ] 26 tests, listed below:
07:29:20 [  FAILED  ] TestWebServer.IsStarted
07:29:20 [  FAILED  ] TestWebServer.CanGetJsonRpcApiDescriptionWithHttpGet
07:29:20 [  FAILED  ] TestWebServer.CanReadDataOverJsonRpcWithHttpGet
07:29:20 [  FAILED  ] TestWebServer.CannotModifyOverJsonRpcWithHttpGet
07:29:20 [  FAILED  ] TestWebServer.CanReadDataOverJsonRpcWithHttpPost
07:29:20 [  FAILED  ] TestWebServer.CanModifyOverJsonRpcWithHttpPost
07:29:20 [  FAILED  ] TestWebServer.CanHeadFile
07:29:20 [  FAILED  ] TestWebServer.CanGetFile
07:29:20 [  FAILED  ] TestWebServer.CanGetFileForcingNoCache
07:29:20 [  FAILED  ] TestWebServer.CanGetCachedFileWithOlderIfModifiedSince
07:29:20 [  FAILED  ] TestWebServer.CanGetCachedFileWithExactIfModifiedSince
07:29:20 [  FAILED  ] TestWebServer.CanGetCachedFileWithNewerIfModifiedSince
07:29:20 [  FAILED  ] TestWebServer.CanGetCachedFileWithNewerIfModifiedSinceForcingNoCache
07:29:20 [  FAILED  ] TestWebServer.CanGetCachedFileWithExactIfUnmodifiedSince
07:29:20 [  FAILED  ] TestWebServer.CanGetCachedFileWithNewerIfUnmodifiedSince
07:29:20 [  FAILED  ] TestWebServer.CanGetRangedFileRange0_
07:29:20 [  FAILED  ] TestWebServer.CanGetRangedFileRange0_End
07:29:20 [  FAILED  ] TestWebServer.CanGetRangedFileRange0_2xEnd
07:29:20 [  FAILED  ] TestWebServer.CanGetRangedFileRange0_First
07:29:20 [  FAILED  ] TestWebServer.CanGetRangedFileRangeFirst_Second
07:29:20 [  FAILED  ] TestWebServer.CanGetRangedFileRange_Last
07:29:20 [  FAILED  ] TestWebServer.CanGetRangedFileRangeFirstSecond
07:29:20 [  FAILED  ] TestWebServer.CanGetRangedFileRangeFirstSecondLast
07:29:20 [  FAILED  ] TestWebServer.CanGetCachedRangedFileWithOlderIfRange
07:29:20 [  FAILED  ] TestWebServer.CanGetCachedRangedFileWithExactIfRange
07:29:20 [  FAILED  ] TestWebServer.CanGetCachedRangedFileWithNewerIfRange
07:29:20 
07:29:20 26 FAILED TESTS
07:29:20   YOU HAVE 5 DISABLED TESTS
```

**Pull request merged**
