### PR TITLE
[depends] libjpeg-turbo 1.4.2

### PR DESCRIPTION
**Pull request by MartijnKaijser**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MrMC** [comment]
version 1.5 looks much more interesting for arm64 neon support.

**Comment by MartijnKaijser** [comment]
No official release yet.

**Comment by stefansaraev** [comment]
libjpeg is not used in core at all. like libpng, it's just for texturepacker / PIL

**Comment by MrMC** [comment]
Oh yea, that's right, v17 moved to ffmpeg for jpeg support. Never mind then :)

**Pull request merged**
