### PR TITLE
add support for external PGS/.sup subtitles

### PR DESCRIPTION
**Pull request by taxigps**
use multi-source stream to load external PGS/.sup subtitles.
issue: times of external .sup subtitle stream not sync with video/audio stream, need set the subtitle time delay 4 second.

### CODE REVIEW

**Comment by taxigps** [comment]
@ace20022 Is this the right way to support .sup? any advice?

**Comment by ace20022** [comment]
Nice!

> issue: times of external .sup subtitle stream not sync with video/audio stream, need set the subtitle time delay 4 second.

Is this a new issue, or was it the same with your old approach?

 I have not started to migrate the rest (.sub) because I had no time to think about how the "add subs on the fly/manually" should work.

**Comment by taxigps** [comment]
old pr #8150 also have this issue on kodi 17. no problem on kodi 16. may be some diference with videoplayer and dvdplayer make this.

think about open .sup manual, may be open any video as multi stream, and add new stream to the multi stream when need?

**Comment by ace20022** [comment]
> may be open any video as multi stream

I think so too. But it requires more work I guess, like adoption of the selection streams and auto selection stuff, because the source mask changes then.

jenkins build this please

**Comment by ace20022** [comment]
@FernetMenta fyi

> old pr #8150 also have this issue on kodi 17. no problem on kodi 16. may be some diference with videoplayer and dvdplayer make this.

**Comment by FernetMenta** [comment]
what is the issue?

**Comment by ace20022** [comment]
>issue: times of external .sup subtitle stream not sync with video/audio stream, need set the subtitle time delay 4 second.

I briefly tested sintel, there the subs where completely wrong (some minutes). But I have no experience in sup extraction, maybe I've done it wrong.

**Comment by FernetMenta** [comment]
ffmpeg demuxer subtracts start_time from pts: https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp#L693

This is to make videos start at 0 secs. If you only have a single subtitle stream with first subtitle to be displayed at 4.0 and start_time is subtracted, you'll get pts 0 for fist sub.

I would log pts and start_time for the external subs.

**Comment by taxigps** [comment]
test again, this issue also on kodi 16. may be some bug in ffmpeg?

**Comment by taxigps** [comment]
@ace20022 @FernetMenta find the reason of external .sup subtitle stream not sync issue.
example:
video mkv info:
```
09:32:38 T:9680    INFO: ffmpeg[25D0]: Input #0, matroska,webm, E:\电影\Mad.Max.Fury.Road.2015.720p.WEB-DL.suptest.mk':
09:32:38 T:9680    INFO: ffmpeg[25D0]:   Metadata:
09:32:38 T:9680    INFO: ffmpeg[25D0]:     title           : EVO
09:32:38 T:9680    INFO: ffmpeg[25D0]:     encoder         : libebml v1.3.1 + libmatroska v1.4.2
09:32:38 T:9680    INFO: ffmpeg[25D0]:     creation_time   : 2016-01-01 02:27:27
09:32:38 T:9680    INFO: ffmpeg[25D0]:   Duration: 02:00:21.18, start: 0.000000, bitrate: 3203 kb/s
```
subtitle sup info:
```
09:37:14 T:6080    INFO: ffmpeg[17C0]: Input #0, sup, E:\电影\Mad.Max.Fury.Road.2015.720p.WEB-DL.X264.AC3-EVO.zh.su':
09:37:14 T:6080    INFO: ffmpeg[17C0]:   Duration: N/A, start: 4.212544, bitrate: N/A
09:37:14 T:6080    INFO: ffmpeg[17C0]:     Stream #0:0: Subtitle: hdmv_pgs_subtitle, 1920x1080
```
problem is video file start time is 0.0 and subtitle file start time is 4.2 not 0.0. try to set subtitle delay to 4.2 when play video let it sync. have tested several movie and sup file, this method works.

how to fix this in our code?

**Comment by FernetMenta** [comment]
does this scenario use multiple demuxers?

**Comment by ace20022** [comment]
Yes, I had a really brief look today, but could not find a fix.

**Comment by taxigps** [comment]
@ace20022 any chance to fix this?

**Comment by ace20022** [comment]
@taxigps Could you please test if this is the right direction? https://github.com/ace20022/xbmc/pull/7

**Pull request merged**
