### PR TITLE
X11: make make on vblank in SwapBuffers an advanced setting

### PR DESCRIPTION
**Pull request by FernetMenta**
Waiting on vblank in SwapBuffers turned out to be an issue on older hardware. This change disables it by default and allows enable via advanced settings. 
Not blocking in SwapBuffers is not ideal because then we don't know on what gl operation the app  will block instead. But this is better than stuttering video.

### CODE REVIEW

**Comment by DaVukovic** [comment]
Confirming that this fixes the problem we talked about at slack which could also be related to:
#14939 

I'll update the wiki with the new advancedsetting-section once this is merged

Thx much :+1:

**Comment by fritsch** [comment]
@MartijnKaijser please consider for rc4 - it fixes a showstopper.

**Comment by Memphiz** [comment]
The VTB stuttering can‘t have a similar cause can it?

**Comment by FernetMenta** [comment]
@Memphiz I already told you what I think is the reason for VTB stuttering. Maybe your patch needs some meek tweaking to get it right.

**Comment by DaVukovic** [comment]
@FernetMenta 

I just want to let you know that my logs on LibreELEC and also on my Ubuntu machine here are now filled with thousands of those lines:

14:06:34.319 T:140042564830144   DEBUG: CGLContextEGL::SwapBuffers: sync interval: 16663

Here is a full log for example: http://ix.io/1xyN

That shows Kodi running for about 12 Minutes simply doing nothing. I know that this is LE, but the same behaviour is seen on my Ubuntu 18.04 machine here. Not sure if that's expected.

**Comment by FernetMenta** [comment]
Just comment out those two logs

**Pull request merged**
