### PR TITLE
Minor cleanup to match naming convention in video database

### PR DESCRIPTION
**Pull request by xconverge**
To complement [xbmc][library] Fix export library #8152

### CODE REVIEW

**Comment by mkortstiege** [comment]
@Paxxi your button ;)

**Comment by xconverge** [comment]
This export still has some issues. The separate files export doesn't seem to work correctly to the folder you choose, I was looking at it a bit more

**Comment by Paxxi** [comment]
This will break as singlefiles means one file per thing and singlefile means everything in one file so the checks need to be reversed. E.g if(singlefiles) becomes if(!singlefile) and so on, if you can update it we can merge it

**Comment by xconverge** [comment]
You are completely right, I will make the changes

**Comment by xconverge** [comment]
Updated @Paxxi feel free to let me know if anything is still broken.

**Comment by mkortstiege** [comment]
Looks good to me. @Paxxi please merge when you're happy with it.

**Comment by Paxxi** [comment]
Haven't had time to test it but changes look good

**Pull request merged**
