### PR TITLE
[cosmetics] CFileItem[List] cleanup

### PR DESCRIPTION
**Pull request by ksooo**
A bunch of random (mostly) cosmetics changes for CFileItem and CFileItemList.

### CODE REVIEW

**Comment by ksooo** [comment]
jenkins build this please

**Comment by mkortstiege** [comment]
@ksooo looks like you´re not yet allowed to trigger it. You have to login to jenkins once and grant permission. Your profile has to be somewhat public as well. @MartijnKaijser or @Memphiz can describe it better :)

**Comment by ksooo** [comment]
@mkortstiege I logged in to jenkins already and granted access. But it seems that something went wrong. :-/

**Comment by mkortstiege** [comment]
@ksooo do you see the green merge button?

**Comment by ksooo** [comment]
@mkortstiege Yes. It's labeled "Merge pull request".

**Comment by Memphiz** [comment]
@ksooo read http://kodi.wiki/view/Jenkins#Jenkins_-_Github_Integration (expand the box) and make your profile public to the org ...

**Comment by ksooo** [comment]
@Memphiz thx. Let's see...

jenkins build this please.

**Comment by ksooo** [comment]
Yeah.

**Comment by ksooo** [comment]
Looking for a reviewer... anybody willing?

**Comment by notspiff** [comment]
looks exactly as useless as a cosmetics-only commit should be.

**Comment by notspiff** [comment]
note that not all parties will like your rvalue <> rvalue changes. they use rvalue == lvalue by habit so incidential assignments cannot happen..

**Comment by ksooo** [comment]
@notspiff 
+ re rvalue == lvalue : I aligned this with the majority of usage in this source file, for consistency.
+ useless means okay for you, I guess. ;-)

**Comment by notspiff** [comment]
Heh yes read as 'no functional changes detected'.

**Pull request merged**
