### PR TITLE
spelling: comments

### PR DESCRIPTION
**Pull request by jsoref**
Spelling fixes for comments

## Description
Semi-automated spelling review of codebase

## Motivation and Context
I have a toolchain which I've been evolving for a while, and I like to test it on projects, especially as a way to give a little in appreciation of projects that I may be using/have used/plan to use.

## How Has This Been Tested?
- [x] AppVeyor and Travis built this code

## Types of change
- [x] Comments

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document

### CODE REVIEW

**Comment by jsoref** [comment]
(First portion of #11346)

**Review by Paxxi — APPROVED** [review]

**Comment by FernetMenta** [comment]
I did not approve the changes in my section.

**Comment by Paxxi** [comment]
I did it for you

**Comment by FernetMenta** [comment]
I just created additional work and changes get lost when i.e. ADSP changes get merged back to master. In order to save time I just dropped the changes in that part of the code. I would be much easier if contributors PR changes to the working branch.

**Comment by Paxxi** [comment]
this is the working branch that almost everyone works against except you.

**Comment by stefansaraev** [comment]
if master conflicts with your fork, I suggest you start rebasing and PRing back here asap, following your own (past and current) rules - small pieces for easier review, no merge commits and so on. you can not block PRs to master because they conflict with your fork, neither you can force people to PR to your fork because that's somehow easier for you.

**Comment by MartijnKaijser** [comment]
I fully agree. If there's a PR made against master by some one and it makes sense to merge it it will get merged. I will not allow something to be blocked cause there is some work being done some where and every has to first go check if it even remotely touches the changes. The code is "owned" by the team and individual developers and not just a single one. Rebase conflicts are a fact of life and every one has to deal with it and so will you.

**Pull request merged**
