### PR TITLE
[Backport] new TrueHD MAT packer code + move TrueHD packing to CDVDAudioCodecPassthrough

### PR DESCRIPTION
**Pull request by thexai**
## Description
This PR is the backport of: 
https://github.com/xbmc/xbmc/pull/24984 and https://github.com/xbmc/xbmc/pull/25256

Also other minor PR's that depend on the main ones:
https://github.com/xbmc/xbmc/pull/25149, https://github.com/xbmc/xbmc/pull/25208, https://github.com/xbmc/xbmc/pull/25282, https://github.com/xbmc/xbmc/pull/25306, https://github.com/xbmc/xbmc/pull/25264

They have been squashed because the changes are cleaner and there are less lines changed than with separate commits (some intermediate commits partial reverts some changes).

## Motivation and context
The reason the new MAT code was implemented was audio dropouts on some TrueHD sources e.g. Cars (2006) although it was later seen that there were also random dropouts but that they did not affect all setups the same. This has already been fixed in master and Omega but there are still dropouts with these sources.

More research has been done to determine exactly what role the new MAT code plays in this: That is, the old MAT code moved to CDVDAudioCodecPassthrough has also been tested along with the rest of the improvements. 

See: https://github.com/thexai/xbmc/commit/7426e69b0d8d34839cb0d1474c9d2e993d10707c

The result is that it improves a lot but does not completely eliminate all dropouts in Cars. So, the conclusion is that the old MAT code has limitations and is not capable of handling all TrueHD sources (although it works fine in 99.9% of the cases). This would affect all setups and all platforms since it does not depend on timings or performance things but on the MAT code itself.

Then the new MAT code is necessary to fix this completely.

## How has this been tested?
Tested several weeks in forum thread: https://forum.kodi.tv/showthread.php?tid=377117

## What is the effect on users?
Eliminates completely all (known) TrueHD related audio dropouts: even in the most problematic sources and in the most problematic setups (users who have reported dropouts only present in their setup and not reproducible in others).

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by fritsch — APPROVED** [review]
Review has happend with the original code. This was additionally extensively tested in the forum by many, even "problematic setup" parties.

**Comment by fritsch** [comment]
jenkins build this please

**Comment by thexai** [comment]
jenkins build this please

**Comment by thexai** [comment]
Merge as Jenkins is essentially broken these days...

**Pull request merged**
