### PR TITLE
VideoPlayer: init ffmpeg threads like LAVFilters does

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

### CODE REVIEW

**Comment by afedchin** [comment]
is this related to http://forum.kodi.tv/showthread.php?tid=277724?

**Comment by fritsch** [comment]
@afedchin yes - that should allow up to 16 threads, while av_cpu_count returns the number of logical cores. E.g. 8 on a i7 quad core. 

The *3 / 2 most likely was found by cpuload testing as it seems the decoder does not fully use the cpu cores. So running 50% more most likely has increased performance.

**Comment by afedchin** [comment]
@fritsch thanks for clarification.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by MrMC** [comment]
can remove 

#if defined(TARGET_POSIX) || defined(TARGET_WINDOWS)
#include "utils/CPUInfo.h"
#endif

**Comment by MrMC** [comment]
fixed for android
https://github.com/MrMC/mrmc/commit/602d6d90a07682ff6233bb573ead3523db084770

**Comment by fritsch** [comment]
@MrMC av_cpu_count <- does not work correctly or does it ignore sleeping CPUs which are not usable afterwards anyways?

**Comment by MrMC** [comment]
av_cpu_count only counts active cpus. With the change, sleeping cpus will be woken and used. Tested under a quad.

**Comment by stefansaraev** [comment]
that means, not quite working on linux if hotplug cpu scaling governor is used, too :)

**Comment by MrMC** [comment]
depends on if sched_getaffinity is present on linux and others.

**Comment by stefansaraev** [comment]
uh. it is available of course, but it wont count "inactive" cpus (hotplug, as said..) ;)

however. I dont think it will be a big deal

**Comment by MrMC** [comment]
It can be a big deal depending on cpus active at time of call. Leads to unpredictable behavior for sw decoding that depends now on how many cpus are active at the time of the call. If you have all spun up, then can handle resource hungry formats, if only one then same media will max decode and fall behind.

**Comment by stefansaraev** [comment]
ookay. then I guess hotplug will not be good choice anymore, I'll advice people switch back to ondemand.

btw, I just tested it. while /proc/cpuingo says "4 cpus", sched_getaffinity sees 3 right now (most of the time  it sees 1, if kodi is idle) :)

**Comment by FernetMenta** [comment]
let's switch back to g_cpuInfo.getCPUCount() and multiply with 3 / 2

**Comment by stefansaraev** [comment]
@FernetMenta most linux hw/distributions do not use hotplug, it's just wetek (and maybe some chineses) who do afaik. hotplug is not even available on mainline kernels. so up to you :)

**Pull request merged**
