### PR TITLE
[GUIMediaWindow] Let the context menu action propagate through window

### LINKED ISSUE #20285: Core context menu bug
### Describe the bug
In my Library View I have my main Library container and also a secondary container with other related content. The problem is that for items in the main library view I can press 'c' and the context menu pops up fine, however the context menu wont appear for items in the secondary container when pressing 'c'

The problem gets stranger when I highlight an item in the secondary container using a mouse and then press the right mouse button and the context menu for that item pops up fine.

So the issue isn't that the context menu doesn't work/exist for the secondary container but that you can't access it using the 'c' key or any context menu button on a remote.... but you can access it using a right mouse click.

## Expected Behavior
Context menu should be available in any container when pressing 'c' or the context menu button of a remote control, not just with a right click of a mouse

## Actual Behavior
For non library containers context menu can only be accessed using a mouse and not with a keyboard/remote

### To Reproduce
This problem can be easily demoed using the Amber skin:-

1. Set your TV Show view to 'Triple' then highlight any tv show item in the first column using a keyboard/remote and press 'c' to correctly bring up the content menu.
2. Now move over to either the season or episode column using the remote/keyboard and press 'c' the context menu wont appear.
3. Now using a mouse highlight an item from either seasons or episodes and right click and the context menu appears perfectly fine.

### Debuglog

The debuglog can be found here:
https://pastebin.com/gcAeMd2p

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP
 - [ ] -CoreElec

 - Operating system version/name:
 - Kodi version: 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by enen92**
## Description
Currently GUIMediaWindow is explicitly dropping the context menu action (see -1)  if not in the default container not allowing it to propagate through the window to the respective control. This is most likely obsolete code that still dates back from when the repo was imported from svn (also, looks like a hack). I have no idea what this block of code does and I assume it was there for a reason...not sure if it's valid anymore.
In fact, the right mouse click forwards a different path and ends up propagating the event throughout the chain...showing the context menu.

Since I suppose we don't have anyone familiar with this code, I'd suggest to merge this and see what issues pop up. Hopefully none. 

## Motivation and context
Fix https://github.com/xbmc/xbmc/issues/20285

## How has this been tested?
See the instructions on the issue thread, using amber skin.
@roidy (the issue reporter) also tested this in several windows and didn't find any regressions

## What is the effect on users?
Context menu should work in multicontainer views

## Screenshots (if appropriate):
image

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Review by howie-f — APPROVED** [review]
i‘ve runtime tested and seen no regression so far

**Comment by roidy** [comment]
@enen92 Did this ever get backported to Matrix?

**Comment by enen92** [comment]
Nop, can you cherry-pick and do the backport @roidy ?

**Comment by roidy** [comment]
Sorry my git knowledge is limited, I have no idea how to do that ☹️

**Comment by enen92** [comment]
np, done in the PR above.

**Comment by roidy** [comment]
Thanks 👍

**Pull request merged**
