### PR TITLE
[pvr] remove not used GUI message

### PR DESCRIPTION
**Pull request by AlwinEsch**
This remove a not used GUI message. This was thought from me years ago to use for PayTV's, but not needed and was never removed ;)

### CODE REVIEW

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by ksooo** [comment]
Looks like a no-brainer. +1

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
travis-ci error is unrelated.

**Comment by AlwinEsch** [comment]
Thanks a lot @ksooo ! Was a bit confused with jenkins and thought to wait a bit for next try :)

**Pull request merged**
