### PR TITLE
Revert "[depends] Updates MSYS2 to 20210725"

### PR DESCRIPTION
**Pull request by AlwinEsch**
Reverts #20726

To check ffmpeg builds on Jenkins. This the most related part to them.

If from them, then strange that not visible before.

Now via my fork, as can not update the branch inside Kodi.
Thought that only master and other releases are locked about upload and not all.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by thexai** [comment]
The trouble in Jenkins have started ~14 hours ago and the update of MSYS is two days ago. Why do you think it is related?

**Comment by AlwinEsch** [comment]
ffmpeg does mostly his works via MSYS2, possible that maybe it was a switching interact, between new and old (if someone has no rebased branch) and it bring something wrong on our server.

**Comment by AlwinEsch** [comment]
Now seems it works again here https://github.com/xbmc/xbmc/pull/20743

**Comment by AlwinEsch** [comment]
Could it also be possible that something is set in server environment variables from the old one and is lost when it is restarted?

**Comment by thexai** [comment]
For me build Kodi Windows x64 in my side is working fine. Only not works build binary addon `peripheral.joystick`

```
[ 82%] Performing forcebuild step for 'peripheral.joystick'
Force build of peripheral.joystick
[ 88%] Performing build step for 'peripheral.joystick'

Microsoft (R) Program Maintenance Utility Version 14.30.30706.0
Copyright (C) Microsoft Corporation.  All rights reserved.

[  2%] Building CXX object CMakeFiles/peripheral.joystick.dir/src/addon.cpp.obj
cl : Command line warning D9002 : ignoring unknown option '/arch:SSE2'
addon.cpp
T:\KODI\kodi\cmake\addons\build\peripheral.joystick\src\addon.h(30): error C2039: 'CSettingValue': is not a member of 'kodi'
T:\KODI\kodi\cmake\addons\output\include\kodi/addon-instance/Peripheral.h(15): note: see declaration of 'kodi'
T:\KODI\kodi\cmake\addons\build\peripheral.joystick\src\addon.h(30): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
T:\KODI\kodi\cmake\addons\build\peripheral.joystick\src\addon.h(30): error C2143: syntax error: missing ',' before '&'
T:\KODI\kodi\cmake\addons\build\peripheral.joystick\src\addon.h(29): error C3668: 'CPeripheralJoystick::GetStatus': method with override specifier 'override' did not override any base class methods
T:\KODI\kodi\cmake\addons\build\peripheral.joystick\src\addon.h(30): error C3668: 'CPeripheralJoystick::SetSetting': method with override specifier 'override' did not override any base class methods
T:\KODI\kodi\cmake\addons\build\peripheral.joystick\src\settings/Settings.h(27): error C2039: 'CSettingValue': is not a member of 'kodi'
T:\KODI\kodi\cmake\addons\output\include\kodi/General.h(38): note: see declaration of 'kodi'
T:\KODI\kodi\cmake\addons\build\peripheral.joystick\src\settings/Settings.h(27): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
T:\KODI\kodi\cmake\addons\build\peripheral.joystick\src\settings/Settings.h(27): error C2143: syntax error: missing ',' before '&'
T:\KODI\kodi\cmake\addons\build\peripheral.joystick\src\addon.cpp(50): error C2039: 'CSettingValue': is not a member of 'kodi'
T:\KODI\kodi\cmake\addons\build\peripheral.joystick\src\storage/StorageManager.h(22): note: see declaration of 'kodi'
T:\KODI\kodi\cmake\addons\build\peripheral.joystick\src\addon.cpp(50): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
T:\KODI\kodi\cmake\addons\build\peripheral.joystick\src\addon.cpp(50): error C2143: syntax error: missing ',' before '&'
T:\KODI\kodi\cmake\addons\build\peripheral.joystick\src\addon.cpp(52): error C2065: 'settingValue': undeclared identifier
NMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
```
Maybe related to https://github.com/xbmc/xbmc/pull/20710

**Comment by AlwinEsch** [comment]
Yes, about addons relates to it, because of the Jenkins error, it was not yet possible to bring in the other requests and then update the add-ons.

**Pull request closed without merging**
