### PR TITLE
AESinkAudiotrack: Don't enforce audio - we are no camera system sound

### PR DESCRIPTION
**Pull request by fritsch**
Fixes volume after the ctor change.

For reference: https://forum.kodi.tv/showthread.php?tid=333160
Thx @koying for showing the right direction.

### CODE REVIEW

**Comment by peak3d** [comment]
This flag was set in old API by default.
If you remove the flag, only device (TV box for example) caps are checked, but not HDMI.

This means, that if you have a PT capable TV Box, but no capable TV, you'll now be able to activate PT (what is wrong)

From what I read and figured out this flag forces a caps check to the real enpoint.

**Comment by fritsch** [comment]
I don't think so reading: https://source.android.com/devices/audio/attributes

**Comment by peak3d** [comment]
Do you trust logcat? Simply use new / old c'tor, the flags value is printed on most devices.
Its "1" for old ctor, and its now "1" for new ctor.

For my test device (Wetek HUB on Monitor without speaker) I have PT caps in settings without the flag.
For old ctor / with the flag I have no PT enabled.

Yes, I read the attribute description, sounds fine for me. I think one should not focus on the example case.

I'm quite sure, that one of the other 1000 options for audio is the reason, but not this flag.

**Comment by fritsch** [comment]
Okay.

**Comment by fritsch** [comment]
For the record:
image

**Comment by peak3d** [comment]
I'll provide some test apk's to the user soon

**Pull request closed without merging**
