### PR TITLE
[win32] binary addons: add support for MSYS/MinGW

### PR DESCRIPTION
**Pull request by Montellese**
These commits add basic support for downloading and installing the MSYS/MinGW environment (which we already use as part of our normal build system) to the binary addons buildsystem. The result is a toolchain file which can be used as part of the win32 binary addon buildsystem to build dependencies with the MinGW tools.
I have tested this with the `audiodecoder.timidity` addon which can currently not be built for win32 due to the fact that `timidity` needs to be built with MinGW.

This work is largly based on the work of @notspiff so most of the credit goes to him.

In an additional step we may have to look into supporting building binary addon dependencies in the MSYS/MinGW environment (not with a toolchain file) which would support using autotools buildsystems.

### CODE REVIEW

**Comment by Paxxi** [comment]
Except for timidity which is a horrible mess, do we have something we can't currently build on win32?
I'm not a fan of relying on mingw, if we have to sure but I'd rather avoid it. My biggest reason is the lack of debug info in minidumps

**Comment by Montellese** [comment]
AFAIK (almost) all game emulators for retroplayer currently rely on MinGW for win32. I haven't taken a close look at them but with this I was able to build game.libretro.nestopia without any changes or extra hacking which might introduce its own issues.

**Comment by Paxxi** [comment]
Ok, haven't looked at the retroplayer stuff yet, need to look into it before commenting further

**Comment by garbear** [comment]
CC me. I'll give this a try when the windows build is no longer crashing on me

**Comment by Montellese** [comment]
@garbear: As mentioned (also in one of the win32 related RetroPlayer threads in the forum) I have this working in https://github.com/Montellese/xbmc/tree/retroplayer-15alpha2 (might not be uptodate) and tested it with an adjusted version of `game.libretro.nestopia` (see https://github.com/Montellese/game.libretro.nestopia/commits/win32_mingw).

**Comment by garbear** [comment]
thanks, i'll check out your changes. got back from a month long backpacking trip last night, still got a lot of github and forum stuff to catch up on :)

is beta 2 out soon? I won't have much internet over the next week so i'd like to do some squashing and rebasing

**Comment by Montellese** [comment]
After some work on RetroPlayer (which now makes use of the commits in this PR) I've made a minor modification which installs a `mingw-config.cmake` script with the MinGW dependency which makes it easier for addons to depend on MinGW by simply using
`find_package(MinGW REQUIRED)` instead of having to provide their own `FindMinGW.cmake` script. It also makes it possible/easier to depend on MinGW in addon dependencies.

**Comment by garbear** [comment]
After rebasing this PR on 17 alpha 2, the patch command stopped working on Jenkins/Win32:

```
-- Processing C:/jenkins/slave/workspace/WIN-32/project/cmake/addons/build/game.libretro.bsnes-mercury-accuracy/depends/common/bsnes-mercury-accuracy/bsnes-mercury-accuracy.txt
-- bsnes-mercury-accuracy url: https://github.com/libretro/bsnes-mercury
-- bsnes-mercury-accuracy extraflags: -DBSNES_PROFILE=accuracy

CMake Error at C:/jenkins/sworkspace/WIN-32/project/cmake/scripts/common/HandleDepends.cmake:124 (message):
  Missing patch command (we looked in
  C:/jenkins/slave/workspace/WIN-32/project/cmake/addons/output;c:/jenkins/slave/workspace/WIN-32/project/Win32BuildSetup/BUILD_WIN32/addons)
Call Stack (most recent call first):
  CMakeLists.txt:384 (add_addon_depends)

-- Configuring incomplete, errors occurred!
```

My local workstation doesn't have any problems finding patch.exe, so this might be a problem with Jenkins.

I've been carrying this PR in my RetroPlayer branch, and it is now based on 17 alpha 2: https://github.com/garbear/xbmc/compare/f3ca4ea...a02dae4

One of the commits moves the patch.exe logic into a new script. Did something change between alpha 1 and alpha 2 that could affect this on Jenkins?

Jenkins console log: http://jenkins.kodi.tv/job/WIN-32/9364/console

**Comment by garbear** [comment]
The error could also be in PR 56, which I [commented on](https://github.com/garbear/xbmc/pull/56#issuecomment-231871145).

**Comment by fetzerch** [comment]
@garbear: It's caused by https://github.com/xbmc/xbmc/commit/b31815db251cf0b54bd2d78a41c5c2605882939b (you'd have to replace APP_ROOT by CORE_SOURCE_DIR)

**Comment by fetzerch** [comment]
Ok, PR sent for retroplayer.

@Montellese: If you rebase this PR, you'd have to cherry-pick https://github.com/garbear/xbmc/pull/61/commits/c2fd7ffb1d948974f7fe52abf947a81e08beb20c.

**Comment by garbear** [comment]
@Montellese I've taken the care of rebasing #7133 on 17 alpha 2: https://github.com/garbear/xbmc/compare/f3ca4ea...a02dae4. there were several merge conflicts and I did my best to combine the changes, but I haven't had any problems yet (until the missing patch on windows). You can cherry-pick these if you want.

**Comment by garbear** [comment]
@Montellese could you rebase on master? I've carried the patch in my retroplayer branch, so i've done the work rebasing on alpha 3: https://github.com/garbear/xbmc/compare/7133-rebased~11...7133-rebased

**Comment by Paxxi** [comment]
I really really don't want this to go in for several reasons.
1. Our build system is hard enough to maintain as is, this will up the complexity significantly and likely require tricks to cut down build/download times like we do today.
2. Once it's in, it's going to be a pain to yank it out again
3. It can't be that much work to just write CMakeLists.txt for the libretro stuff
4. timidity is an abomination and that it compiles on any platform is probably by pure luck

I'm perfectly willing to take on number 3 just to avoid merging this as I've already done it for all our depends. I won't have time this release cycle though.

**Comment by Paxxi** [comment]
I don't want to just shut this down so I'm curious, which of the emulators are most popular @garbear @a1rwulf? Can try and start with porting those to get things going

**Comment by garbear** [comment]
The most popular emulators are the ones with the most popular platform. So nes/snes if you grew up in the US, saturn/dreamcast if you grew up wherever those were popular

**Comment by Montellese** [comment]
I won't have time for rebasing because my wedding's on Saturday so I'm caught up in preparations. And after that I'll be on vacation.

@Paxxi: It's probably not just a question of buildsystem i.e. Makefiles vs. CMake but also about platforms. Last I looked into some libretro cores (obviously not all) they were completely written for unix/linux so you can't just use MSVC because you need all the linux libraries provided by MinGW.

**Comment by a1rwulf** [comment]
I don't know a lot about working on windows. Regarding platforms I feel
that nes/snes will be good starters imho. I'm very busy with my house over
the next few weeks, won't be able to do a lot here...

**Comment by Paxxi** [comment]
No worries, wasn't looking for help with the work, just pointers as to what is popular as I don't game myself :) have looked at bsnes-mercury and so far so good, other than the rather weird use of header files

**Comment by fetzerch** [comment]
@Montellese: I had a discussion with @Paxxi on Slack about this. Would it be an option to use the mingw/msys system of core instead? I know that in general we don't want to have the addons to tightly coupled with core, but I don't think it's a good idea to maintain 2 mingw/msys versions.

I'm asking this because I think it would be really good to get the PR in shape for inclusion. That would reduce yours and @garbear's rebasing workload. And @hudokkow and me have spent quite a few hours finding subtile issues that could have been avoided if this is included in master.

Additionally I think some libretro cores would be fixed by updating to a newer gcc (which we have in core).

Just for reference: I don't think it's feasible to rewrite and maintain CMake files for the libretro cores. Because of the pure amount, because some are quite complex (mame, scummvm) and because libretro does a great job maintaining Makefiles that work with msys/mingw and we don't need to duplicate that work.

**Comment by da-anda** [comment]
is this PR still valid? Looking at #10964 I think this one can be closed

**Comment by hudokkow** [comment]
Can be closed, IMO. We can always revisit later if needed. See fetzerch comments in https://github.com/xbmc/xbmc/pull/10964

**Pull request closed without merging**
