### PR TITLE
Playlist creation modded into a threading model

### PR DESCRIPTION
**Pull request by quickmic**
## Description
Playlist creation is now designed in a seperat thread

## Motivation and Context
Poor performance on music playlists

## How Has This Been Tested?
Tested with playlists (music and video) up to 10000+

## Types of change
- [ ] Bug fix** (non-breaking change which fixes an issue)
- [ ] Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] Improvement** (non-breaking change which improves existing functionality)
- [ ] New feature** (non-breaking change which adds functionality)
- [ ] Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] None of the above** (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines]
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by quickmic** [comment]
Why merged with pull request #1?

**Comment by quickmic** [comment]
Anything else needed fro review?

**Comment by notspiff** [comment]
gut reactions, i have no time for detailed review now, sorry;

1) indent is off in quite some places
2) you rely on sleep all over. that is big red flag for broken code.
3) while std::thread is tempting, we use a different mechanism for this all over, it is not quite ready to be used on all our platforms - see utils/Job.h
4) PR contains a merge.

**Comment by quickmic** [comment]
Thx for responding :)
2, 3. I will review that
4. Yes, I saw that as well, I'll try to fix it. Seems that happened when I merged the xbmc updates to my fork.

**Comment by notspiff** [comment]
Do

1) git fetch xbmc
2) git rebase xbmc/master
3) git push -f  origin master

assuming origin is your remote and xbmc the upstream.

**Comment by quickmic** [comment]
I think I messed up my fork. I will delete it and fork again.
For the moment I close this PR and start rewriting the code using utils/Job.h.
Actually this approach looks promising, especially adjusting thread priority. 
I assume I can get rid of the sleep commands using that function.

**Comment by quickmic** [comment]
Thx for review, I will come back soon with modified version

**Pull request closed without merging**
