### PR TITLE
[libUPnP] update Neptune & Platinum

### PR DESCRIPTION
**Pull request by Rechi**
## Description
- update Neptune to 1.2.3 (https://github.com/plutinosoft/Neptune)
- update Platinum to 1.2.0 (https://github.com/plutinosoft/Platinum)
- refresh patches

## How Has This Been Tested?
- compiled for windows (desktop, uwp), linux, osx, ios and android.
short runtime test on Windows

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by wsnipex** [comment]
I remember there was a reason for not moving this to depends in the past, does anyone know? Or could we move them now?

**Comment by Rechi** [comment]
Moving it to depends will complicate things for windows and linux builds without our depends, but maybe that wasn't the reason you are talking about.

**Comment by Rechi** [comment]
@Montellese ping

**Review by Montellese — APPROVED** [review]
The changes to the patch files etc. look good. Obviously I can't review the changes to Neptune or Platinum.

**Pull request merged**
