### PR TITLE
add library.inputstream to CMakeLists.txt

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by mapfau** [comment]
jenkins build this please

**Comment by mapfau** [comment]
Just a question, is it possible to rename the "XBMC for Windows.sln" file to a name without blanks in it?

**Comment by afedchin** [comment]
whats wrong with blanks?

**Comment by mapfau** [comment]
its so annoying to add the file under git in cygwin -> need to slash always

**Comment by afedchin** [comment]
git add project/VS2010Express/*.sln

**Comment by mapfau** [comment]
Thanx for this tipp! But I must say that I was never ever in my live happy with filenames containing blanks. There will be always situations where it is unhandy. I bet that I'm not the only one who came across this situation... But OK, was just an idea....

**Comment by afedchin** [comment]
I think with cmake it doesn't matter. just be patient and it will gone.

**Comment by wsnipex** [comment]
Xcode doesn't needs this?

**Comment by mapfau** [comment]
I bet it will, but this is something I never did before.

**Comment by mapfau** [comment]
There is one more issue wich is new: compiling the kodi_addons.sln file shows following:

4>    -- Up-to-date: C:/Dev/xbmc/addons/.//inputstream.mpd/resources/settings.xml
4>    -- Installing: C:/Dev/xbmc/addons/inputstream.mpd/inputstream.mpd.dll
4>    CMake Error at cmake_install.cmake:47 (file):
4>      file INSTALL cannot find "//inputstream.mpd.pdb".

Unfortunately debugging in win is gone with this

**Comment by FernetMenta** [comment]
on OSX those libs are built with "make xcode_depends"

**Comment by mapfau** [comment]
regarding to my last post here: I dont think the install error is important. looking with hex editor into the dll then there is found the full absolute path to ...../inputstream.mpd-build\Debug folder.

Nevertheless I didn't get breakpoints set in for example MainDash.cpp. This was working al the days before. I wouold really appreciate if somebody with win running can confirm it. I already started my computer, rebuild all applications - without luck.

**Comment by mapfau** [comment]
should all be fixed with:

https://github.com/xbmc/xbmc/pull/9353
and
https://github.com/mapfau/inputstream.mpd/commit/0f76a0fa981f531eed17cc402ed2c42b3bb2891b

**Pull request merged**
