### PR TITLE
[stringutils] fix sizestring alignment

### PR DESCRIPTION
**Pull request by mkortstiege**
This removes unwanted spaces so size strings get properly aligned.
Reported @ http://forum.kodi.tv/showthread.php?tid=222067

### CODE REVIEW

**Comment by mkortstiege** [comment]
@BigNoid, @Montellese, @ronie objections?

**Comment by ronie** [comment]
alignment is ok, but my filesizes suddenly increased by a factor of 1000.

wrong

**Comment by mkortstiege** [comment]
Updated. @ronie please try again.

**Comment by ronie** [comment]
better, much better ;-)

**Comment by mkortstiege** [comment]
Great. jenkins build and merge.

**Pull request merged**
