### PR TITLE
[videodb][videoversion] Fix Leaks on Movie / Asset Removal

### PR DESCRIPTION
**Pull request by CrystalP**
## Description

Modify version/extra addition and removal to be symmetrical and to follow the add/delete patterns used elsewhere in Kodi video db. Add is an upsert.
Sub-resources of a video asset that have to be created / removed/invalidated:
- art
- stream details
- path

This code works around a couple problems that would need some significant refactors
- have to be careful not to use the same dataset at multiple levels of the call stack, they are like global variables.
- transaction nesting

The last commit adds a table delete trigger to take care of asset art and stream details removal, to follow the pattern of the other tables.
My understanding is that the db version cannot be bumped for stable releases so that commit is not eligible for backport to v21. The other commits can be backported.

There are conflicts with #25022 in CVideoDatabase::DeleteMovie(). This PR is more important, I will adapt the other PR later.

## Motivation and context

Noticed inconsistencies in data cleanup after removing movie additional versions or extras, sometimes a library update wouldn't notice the files of the remove versions or extras.
Some data remained in the database after removing versions or extras.

## How has this been tested?

sqlite and mariadb
Remove movie from library, remove version from movie, remove extra from movie, followed by update libray or scan for new content.

## What is the effect on users?

Versions/extras scanned more consistently, remove leaks in the database.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CrystalP** [comment]
Jenkins build this please

**Comment by CrystalP** [comment]
I'll merge at the end of the week if there are no objections.

**Comment by thexai** [comment]
Merged with no approval?

Backport needed, including video DB version schema change?

The database has never been changed in a minor update... (21.0 --> 21.1) AFAIK

@fuzzard @ksooo ?

**Comment by CrystalP** [comment]
I wasn't planning on backporting the db change/bump, it's a separate commit on purpose. That was in the description and in the commit message, though it's not very noticeable.

> > Some data remained in the database after removing versions or extras.
> 
> This is not critical bug.

Not critical but it causes problems with the library scans.

Not cleaning up the path hashes causes the scanner to skip the directories containing versions or extras of a movie removed from the library and they are not added to the library again.
It was noticed and some user wondered why he had to change a file name to get it scanned again and it didn't help with @KarellenX trouble reported in Slack.

**Comment by thexai** [comment]
> I wasn't planning on backporting the db change/bump, it's a separate commit on purpose.

All good then, I hadn't seen it.

**Pull request merged**
