### PR TITLE
[tools/depends][native] texturepacker update and use cmake to build

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Update and use cmake to build TexturePacker. Requires #23395 so those commits are currently included here for jenkins build testing

## Motivation and context
Easier to build in core tree using cmake native build

## How has this been tested?
Build osx-arm

## What is the effect on users?
N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CrystalP** [comment]
Is this related to #23409? How?

**Comment by fuzzard** [comment]
Tangentially, yes  this PR has no direct effect on windows, however a combination of this PR, the other one, and more work coming ties into windows building texture packer

**Comment by lrusak** [comment]
was the point of this PR to only use CMake for the texture packer build? If so did you forget to remove the autotools stuff?

**Comment by fuzzard** [comment]
No reason to remove it. If someone somewhere is based on that (some package maintainer from wherever that would come out of the woodworks), they can continue to use it. It still functions exactly as it did prior to this PR at this point in time, we just use the cmake build now.

**Comment by lrusak** [comment]
> No reason to remove it. If someone somewhere is based on that (some package maintainer from wherever that would come out of the woodworks), they can continue to use it. It still functions exactly as it did prior to this PR at this point in time, we just use the cmake build now.

I would just remove it if we aren't using it internally anymore. It's just going to get broken and unmaintained.

**Comment by fuzzard** [comment]
I had no intention of altering texturepacker itself for the purpose of this. Feel free to remove it as/when you alter texturepacker itself in those other PR's if having a second build system is a maintenance burden.

**Comment by Rechi** [comment]
You missed to replace automake with cmake in the requirements for TexturePacker.
https://github.com/xbmc/xbmc/blob/0a8e90d9e018a4605bb23247088184e154b6d7c4/tools/depends/native/Makefile#L82

**Comment by fuzzard** [comment]
I'll pr a fixup on the weekend

**Pull request merged**
