### PR TITLE
[GUIInfoManager] Use cache for current stream's language retrieval.

### PR DESCRIPTION
**Pull request by ace20022**

### CODE REVIEW

**Comment by ace20022** [comment]
@FernetMenta for ack

**Comment by FernetMenta** [comment]
nice. did we miss this at the time we did the cache or was this added later?

**Comment by ace20022** [comment]
Quite funny: I added it some months later and you are the last one that change this line ;)

**Comment by FernetMenta** [comment]
hehe :) push the button

**Pull request merged**
