### PR TITLE
Remove article from summary

### PR DESCRIPTION
**Pull request by razzeee**
This removes the article from the summary as recommended in https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines/#dont-start-with-an-article

I would also like to backport this

### CODE REVIEW

**Review by garbear — APPROVED** [review]
PR follows advice from the hyperlink: "Don't start with an article"

Good for a backport IMO.

**Comment by garbear** [comment]
Good to merge?

**Comment by razzeee** [comment]
Yes

**Comment by enen92** [comment]
jenkins build and merge

**Pull request merged**
