### PR TITLE
[pvr] usability optimizations

### PR DESCRIPTION
**Pull request by palsch**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@xhaggi @ronie

**Comment by xhaggi** [comment]
@palsch IMO we don't need to show the channel group name as a part of the channel button label for the following reasons:
* we show the channel group name in the breadcrumb of the window
* we show the channel group name as a part of the "groups" button label
* you are able to cycle the groups with a click on the channels & guide button. This feature was not dropped after we've introduced the "groups" button because some users want an easy way (less clicks) to cycle the groups without moving to the groups button every time.

**Comment by xhaggi** [comment]
@ronie for the first commit. do we have something like that for video/music window too?
@MartijnKaijser both are improvements, nothing for 15.x

**Comment by palsch** [comment]
@xhaggi I know what you mean, we have already two places where we can see the current active channel group.
But:
* the breadclumb isn't visible if the sidebar is opened
* "groups" button is already showing the current channel group, but its not really user friendly if you click to a button on the top of the window and have to check the result  after each click on the bottom of the window. Its much better to see the result in the near of the element the user is interacting with

Me and my family using PVR feature of Kodi 15 almost every day, and these two improvements were the most two that were really annoying not to have :)

What do you mean "nothing for 15.x"? Don't you want to integrate that pull request to kodi 15 after acceptance?

**Comment by ronie** [comment]
> @ronie for the first commit. do we have something like that for video/music window too?

nope, there's a 'Fullscreen" button in the side menu people can use.

i kinda aree with you on the second commit, displaying the channel group name in three places is overkill.

**Comment by MartijnKaijser** [comment]
@ksooo ping for checking

**Comment by xhaggi** [comment]
@MartijnKaijser if he'll drop the second commit then it's something we could merge and I'm not sure why @ksooo should take a look at it too.

**Pull request closed without merging**
