### PR TITLE
[PVR] Inconsistencies in Guide/Channel/Recordings Info Dialogs

### PR DESCRIPTION
**Pull request by linknetx**
## Description

Resolve inconsistencies in PVR Guide/Channel and Recordings Info Dialogs, particularly between Estuary and Estouchy Skins.

## Motivation and Context

Creates a more consistent interface.
## How Has This Been Tested?

Tested both in Estuary and Estouchy Skins.

These are the proposed changes to the Estouchy and Estuary Skins for Recordings Info:

1 recordings info

These are the proposed changes to the Estouchy and Estuary Skins for Guide/Channel Info:

2 guide info

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Rechi** [comment]
wrong revision was build
jenkins build this please

**Comment by ronie** [comment]
skin changes look ok to me.

**Comment by linknetx** [comment]
> skin changes look ok to me.

So it's not possible to include in 18.xx ?

**Comment by ronie** [comment]
you would need to split the PR in two then.

the re-ordining of the existing buttons in the skin is fine for v18.

but adding a new one (core changes / new functionality) is something for v19.

**Comment by linknetx** [comment]
OK, it's not worth splitting, so please leave for v19.

**Comment by linknetx** [comment]
@ronie
Just revisiting this. I can see that any breaking change would need to be included in the next version but as far as I can see this isn't a breaking change. Adding the "Find similar" option, which already exists elsewhere, to the PVRRecordingInfo dialog means it will only be available to the updated skins provided with this change. Any previous skins, or skins based on previous skins, just will not reference the new option and will still work perfectly.

**Comment by ronie** [comment]
sorry, but the only thing that qualifies to go into v18 are bugfixes.

**Comment by ksooo** [comment]
jenkins build this please

**Review by ksooo — APPROVED** [review]
Thx.

**Comment by ksooo** [comment]
@ronie are the skin changes good to go?

**Comment by ksooo** [comment]
> skin changes look ok to me.

 ah, you already "approved" that.

**Pull request merged**
