### PR TITLE
Update README.Android.md

### PR DESCRIPTION
**Pull request by AndrewChqng**
## Description

Fix ffmpeg compilation as referenced in 
https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

## Motivation and context

Compilation error of missing dav1d
## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
This isn't actually correct as libdav1d is compiled as part of the depends build for android.

**Comment by garbear** [comment]
Out of curiosity did you need [this](https://github.com/garbear/xbmc/commit/modernize-android) to compile?

**Comment by AndrewChqng** [comment]
Sorry, still new to this and trying to crash course myself on the terminology and everything, I'm trying to compile for x86_64 android which I know isn't maintained but figured I might be able to work it out hopefully and learn on the way.
But since the error is while building tools and dependancies I'm not sure what the issue is

I've clean installed Debian wsl to see if it was my setup but keep getting this error on master and on matrix branch (just with different required version numbers). I can't seem to figure out what the problem is:
```
ERROR: dav1d >= 0.4.0 not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
make[2]: *** [Makefile:81: x86_64-linux-android-21-debug] Error 1
make[2]: Leaving directory '/home/andrew/kodi/tools/depends/target/ffmpeg'
make[1]: *** [Makefile:134: ffmpeg] Error 2
make[1]: Leaving directory '/home/andrew/kodi/tools/depends/target'
make: *** [Makefile:11: target/.installed-x86_64-linux-android-21-debug] Error 2
```
Full file
[config.log](https://github.com/xbmc/xbmc/files/7087303/config.log)

> Out of curiosity did you need [this](https://github.com/garbear/xbmc/commit/modernize-android) to compile?

Yep did manage to figure it out eventually

> Thanks for the PR but this isn't actually correct as libdav1d is compiled as part of the depends build for android.
> 
> Is there something that can be clarified though?

Many thanks, it's greatly appreciated

**Comment by lrusak** [comment]
Did you still want to pursue this or should it be closed?

**Comment by AndrewChqng** [comment]
Oh yes sorry, I couldn't figure out what's going wrong in the end but probably something stupid I've done on my end. I'll try to close it but yes please if it's done from your end...

**Pull request closed without merging**
