### PR TITLE
fixed: We must exact match addon extensions/mimetypes/protocols (fixes #16652)

### LINKED ISSUE #16652: Audio stream does not play in pvr.iptvsimple if audio decoder addons installed
### Describe the bug
Here is a clear and concise description of what the problem is:

By default kodi installs the AAC and WMA decoders. If any additional decoder addons are installed, audio streams will not play in pvr.iptvsimple.

This appears to have been an issue wince kodi 18 release so probably also exists in master.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

With any additional decoder addons installed, audio streams should play in pvr.iptvsimple.

Forum post: https://forum.kodi.tv/showthread.php?tid=347437
Older pvr.iptvsimple issue: https://github.com/kodi-pvr/pvr.iptvsimple/issues/212

## Actual Behavior

By default kodi installs the AAC and WMA decoders. If any additional decoder addons are installed, audio streams will not play in pvr.iptvsimple.

## Possible Fix

Really not sure. Afraid I don't understand how the audio decoders work.

### To Reproduce

1. Install any additional audio decode addon
2. Use the M3U file below in pvr.iptvsimple
3. Play radio channel, it will fail to play

```
#EXTM3U
#EXTINF:-1 radio=true tvg-logo="JB-Radio2.png",JukeBox2
http://cristina.torontocast.com:8007/mp3-320
```

### Debuglog

The debuglog can be found here:

With only the default WMA and AAC decoders installed it's works: https://pastebin.com/u2NSPyeg

With additional decoders installed it does not work: https://pastebin.com/BmeGqc8d

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [X] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSX/Ubuntu 18.04.2 LTS
 - Kodi version: 18.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by arnova**
Same problem as we had with our VFS addons. Note that this also fixes matching against empty extensions (like in #16652)

### CODE REVIEW

**Comment by AlwinEsch** [comment]
With the `StringUtils::Split` is much better, it prevent a problem where e.g. `.abc` is searched and another place have `.abcd` :smile: 

Thanks a lot!

**Review by AlwinEsch — APPROVED** [review]

**Comment by arnova** [comment]
> With the `StringUtils::Split` is much better, it prevent a problem where e.g. `.abc` is searched and another place have `.abcd` 
> 
> Thanks a lot!

You're welcome :-)

**Comment by AlwinEsch** [comment]
Yet another question, do you have any idea how best to manage it if multiple addons or addon and kodi support the same file extensions?

I thought the filing extensions to a special class deposit each returns the associated processing site.
And that is checked with addon installation / activation whether already supported and asks the user whether previous is replaced with it.

Am just not sure how the different processing paths can be easily managed by a body.

**Comment by arnova** [comment]
> Yet another question, do you have any idea how best to manage it if multiple addons or addon and kodi support the same file extensions?
> 
> I thought the filing extensions to a special class deposit each returns the associated processing site.
> And that is checked with addon installation / activation whether already supported and asks the user whether previous is replaced with it.
> 
> Am just not sure how the different processing paths can be easily managed by a body.

I think handling this is not trivial. We need to add "something" to our addon system to allow enabling/disabling of specific addon protocols/extensions/mimetypes/etc. And we need some way to allow the user to enable/disable them. Especially the latter is not particularly easy

**Comment by phunkyfish** [comment]
Nice 👍 

Will close other PR

**Comment by phunkyfish** [comment]
Tested and working. Thanks!

**Comment by MilhouseVH** [comment]
A test user has reported issues which may be the result of this PR: [forum post](https://forum.kodi.tv/showthread.php?tid=343068&pid=2888546#pid2888546)

**Comment by phunkyfish** [comment]
I think this is the wrong PR for that forum post. I think you want: 

https://github.com/xbmc/xbmc/pull/16593

**Comment by MilhouseVH** [comment]
LOL so sorry - I just went off the info in the forum post and didn't pay enough attention (trying to do 3 things at once!)

**Comment by Rechi** [comment]
This broke listing files supported by vfs add-ons, https://forum.kodi.tv/showthread.php?tid=348448&pid=2898398#pid2898398.

**Comment by arnova** [comment]
@Rechi : Fix here 

> This broke listing files supported by vfs add-ons, https://forum.kodi.tv/showthread.php?tid=348448&pid=2898398#pid2898398.

Fix here: #16892

**Pull request merged**
