### PR TITLE
[cmake] ENABLE_EVENTCLIENTS requires PythonInterp

### PR DESCRIPTION
**Pull request by olafhering**
Currently lib/gtest/cmake/internal_utils.cmake checks for PythonInterp,
and cmake/scripts/linux/Install.cmake works more or less by accident.

Add the check also in this code path because gtest is (supposed to be)
an optional part of the build.

Signed-off-by: Olaf Hering <olaf@aepfle.de>

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by wsnipex** [comment]
the WiiRemote eventlclient is C++ and doesn't need python

**Comment by olafhering** [comment]
I have updated `ExtraTargets.cmake` to match `install.cmake`.

**Comment by wsnipex** [comment]
Part from the missing "(", it still doesn't make any sense. Please explain why you think this is needed.

**Comment by olafhering** [comment]
> Part from the missing "(", it still doesn't make any sense. Please explain why you think this is needed.

Why do you think it is not needed? How and where is `PYTHON_EXECUTABLE` supposed to be set?

**Comment by olafhering** [comment]
And if the answer is `FindPython.cmake`, is that actually the correct answer? A plain `python` might be 2 or 3, and may not do what it is expected to do. This commit should probably wipe the check from there as well.

**Comment by wsnipex** [comment]
I'll repeat: the wii eventclient is C++, it does not need python.
And yes, python is searched for in FindPython.cmake. Python 2.7 that is, not python 3.

**Comment by olafhering** [comment]
Others pointed me to [https://www.python.org/dev/peps/pep-0394/](https://www.python.org/dev/peps/pep-0394/), paragraph 3 proves my point I made regarding plain `python`.

**Comment by Rechi** [comment]
Same question again, where do you see a python reference at `tools/EventClients/Clients/WiiRemote`?

**Comment by olafhering** [comment]
> Same question again, where do you see a python reference at `tools/EventClients/Clients/WiiRemote`?

Why would that matter? It changes the ENABLE_EVENTCLIENTS code path.

**Comment by Rechi** [comment]
https://github.com/xbmc/xbmc/blob/master/tools/EventClients/Clients/WiiRemote/CMakeLists.txt does not need Python (neither the interpreter or the lib). That's the only thing done in the block commented as `# WiiRemote`. So there is no reason to search for PythonInterp if it is not used.

**Comment by wsnipex** [comment]
I'm going to close this

**Pull request closed without merging**
