### PR TITLE
drop obsolete libmpeg2

### PR DESCRIPTION
**Pull request by FernetMenta**

### CODE REVIEW

**Comment by MrMC** [comment]
History says, libmpeg2 was kept around because of one reason. It handed still frames in DVDs that would barf under FFMpeg. Has something changed ?

**Comment by FernetMenta** [comment]
yes indeed: https://github.com/xbmc/xbmc/pull/8686
VideoPlayer does now drain ffmpeg

**Comment by Paxxi** [comment]
Happy times, one less library that requires mingw

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
Windows addon build failure unrelated.

**Pull request merged**
