### PR TITLE
guiinfo: grab gfx lock when registering GUIInfoProviders

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

### CODE REVIEW

**Comment by FernetMenta** [comment]
@ace20022 @ksooo /fyi

**Comment by ksooo** [comment]
Not sure what this is supposed to fix.

The crash ace reported is (most probably- he did not provide stack traces that prove this hypothesis) due to concurrent call to guiproviders::register and guiinfoproviders:: getlabel. So, this change does at least not fix this crash.

**Comment by ace20022** [comment]
The last call stack list at https://github.com/xbmc/xbmc/pull/14147#issuecomment-402550609
shows that behaviour for thread 1 and tread 37. Albeit it's not the exact moment of the crash. It's the moment the breakpoint at the register is reached.

**Comment by ksooo** [comment]
@ace20022 okay, then.

But still, I cannot see how this PR could help to fix this crash.

**Comment by FernetMenta** [comment]
all manipulation of gui variables, this includes GetLabel, has to be done in FrameMove. FrameMove grabs the gfx lock too

**Comment by ace20022** [comment]
This fixes my issue. Thx!

**Comment by ksooo** [comment]
No doubt that this change is correct, but @ace20022 if this fixes your issues, it is by pure luck due to changed timings as it does not fix the root cause of the crash you reported.

**Comment by FernetMenta** [comment]
this change does address the root cause shown by @ace20022 bt

**Comment by ksooo** [comment]
Why? I don't get it.

**Comment by FernetMenta** [comment]
did you see my post above? https://github.com/xbmc/xbmc/pull/14152#issuecomment-402772352

GUiInfo is protected by the gfx lock

**Comment by ksooo** [comment]
If guiinfo is protected by gfx lock, how is this guaranteed if none of the public guiinfomanager methods is directly protected by this lock?  Is mutex protection implicit because done earlier by other methods, before calling guiinfomanager (thus not failsafe)?

I would prefer a more explicit approach where all public guiinfomanager methods have a call to assure the gfx mutex. This makes things much more clear (to me).

**Pull request merged**
