### PR TITLE
[adsp] fix seg fault if DSP becomes enabled

### PR DESCRIPTION
**Pull request by AlwinEsch**
The following changes are urgent for me, it fix the seg fault on first enable of DSP system in Kodi.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
jenkins build this please.

**Comment by AchimTuran** [comment]
Sorry Alwin this patches doesn't solve the issues on windows with a fresh install. It crashes and it has problems to enable addons.

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by AlwinEsch** [comment]
jenkins build this please again

**Comment by AlwinEsch** [comment]
jenkins build this please again, sorry crazy Alvin Chipmunk day.

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by AlwinEsch** [comment]
OK for the others to merge in?

**Comment by FernetMenta** [comment]
I think so :)

**Pull request merged**
