### PR TITLE
[Win32BuildSetup] add Version to add/remove programs entry

### PR DESCRIPTION
**Pull request by vjadid**
## Description

Adds "Version" to add/remove programs entry of kodi

## Motivation and Context

Instead of showing blank, the version entry will now show the installed kodi version

## How Has This Been Tested?

Built and installed kodi 

## Screenshots (if appropriate):
image

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [x] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by vjadid** [comment]
@fritsch Do I need to change anything for passing checks?

**Comment by fritsch** [comment]
Thanks much. I added some labels. From semantic pov I added a reviewer with more glue than me for Windows Stuff :-)

**Comment by phunkyfish** [comment]
@Paxxi maybe you could review if you have some spare time?

**Comment by Paxxi** [comment]
Thank you @vjadid , I apologize for it taking so long.

**Pull request merged**
