### PR TITLE
[guilib] GUISliderControl - don't scale if dimensions are zero

### LINKED ISSUE #15255: Kodi crashes while using touch mode in Estuary
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi crashes instantly while trying to adjust the volume while using the "touch mode" in Estuary. I tried several fresh compiled builds on different machines and some are working and some not. The only difference I could see is, that the machine it crashes on, uses a NVidia GPU.

If I start Kodi from command line. I get: 
```
kodi-x11: /home/davu/gits/xbmc/xbmc/utils/MathUtils.h:61: int MathUtils::round_int(double): Assertion `x > static_cast<double>((int) (INT_MIN / 2)) - 1.0' failed.
Aborted (core dumped)
```

This the gdb output after Kodi freezes (it freezes while using gdb and does not crash) with `thread apply all bt full`
https://paste.ubuntu.com/p/VvqcNFGQfJ/

This is the matching crashlog:
[kodi_crashlog-20190114_184520.log](https://github.com/xbmc/xbmc/files/2756374/kodi_crashlog-20190114_184520.log)

Let me know if you need something else

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi shouldn't crash while using the touch mode

## Actual Behavior

It crashes

### To Reproduce

1. start kodi
2. activate touch mode
3. try to adjust the volume with the mouse

### Debuglog

The debuglog can be found here:
http://paste.ubuntu.com/p/pnsFVr5GYy/

### Screenshots 
Here are some links or screenshots to help explain the problem:

If I try to adjust the volume and click on that section, kodi freezes while using gdb and crashes if started normally.
touch

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 16.04
 - Kodi version: latest Kodi master `Kodi (18.0-RC5 Git:20190114-5e4f807)`

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by enen92**
## Description
This PR fixes https://github.com/xbmc/xbmc/issues/15255. The slidercontrol in estuary (using touchmode) does not define any textures for both `texturesliderbar` and `textureslidernib`. As the slidercontrol is tied to `Player.Volume`, when its value is updated Kodi will attempt to scale all control textures. The scaling factor is calculated using the width or height of the texture in a division. As the value is 0, the scalling factor will lead to +inf. Kodi will crash in rendering when attempting to round the values (assert in mathutils). The PR assumes a default scaling factor of 1 and only scales if the values of the divisor is not 0.
It also includes some changes to the estuary dialog (mostly provided by @ronie). Only additional change is the removal of the `textureslidernibfocus` as it will be rendered in between the background and the progress control (when the goal is to hide it).

Not sure who to ping for the cpp part, random.org assigned @fritsch :)

## Motivation and Context
Fix issues for Leia Final.

## How Has This Been Tested?
Compile and tested all estuary sliders

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Review by ronie — APPROVED** [review]
skin changes are ok

**Comment by Rechi** [comment]
jenkins build this please

**Comment by fritsch** [comment]
@notspiff @ksooo I think you two are better suited for review here.

**Review by fritsch — APPROVED** [review]

**Comment by notspiff** [comment]
all good, sane div by zero guards.

**Pull request merged**
