### PR TITLE
[win10] temporary controller workaround until proper joystick support

### PR DESCRIPTION
**Pull request by koying**
Temporary workaround for gamepad on xbox based upon @afedchin & @Paxxi suggestions

For reference, unless we want to put this in until @garbear has time

### CODE REVIEW

**Review by Paxxi — APPROVED** [review]
Looks good to me for now. The whole thing will need a rewrite in the future anyway

**Comment by koying** [comment]
For the record, I tried afedchin's solution and I had issues with plain keyboard mappings as well.
As far as I could read, OnCharacterReceived is the only way to properly get the unicode of a keypress

**Comment by afedchin** [comment]
what's wrong with https://github.com/afedchin/xbmc/commit/d64a84e76f84a17e7fe57c40da118ece74756774 ?

**Comment by afedchin** [comment]
did you try with fixed peripherals.joystick?

**Comment by koying** [comment]
> what's wrong with afedchin/xbmc@d64a84e ?

When using keyboard on PC, some of the alphanum were showing numbers, on the left of my azerty keyboard, a bit like if they were translated to numpad.

Didn't try with addon, by my droid philosophy is that when the gamepad is the primary input method, it should always work, joystick addon or not ;)
Addons are... addons. There shouldn't be such thing as a "required" addon.

**Comment by Montellese** [comment]
@koying that understanding sounds incompatible with what @garbear has done with the `peripheral.joysticks` add-on. AFAIK no controller (like Xbox 360, Xbox One, ...) works without that add-on on other platform (unless they act like a keyboard) and the add-on has to be part of the kodi installation (just like the default skin add-on or the english language add-on etc.)

**Comment by koying** [comment]
@Montellese Well, pretty sure it works w/o the addon on droid (at least as far as I remember; I even remember some discussions with garbear to get it to work that way), and, indeed, it's due to the fact that they basically act as keyboards (or are emulated as such) by the OS.

It's exactly the same situation on UWP.

Anyway, see https://github.com/xbmc/xbmc/pull/13008/files?w=1 for the actual diff w/o eol issue.
Controller working is just a side effect, really. 

The 
```
-  if (!args->KeyStatus.IsExtendedKey)
-  {
-    // fix F1-F24 keys
-    if (args->VirtualKey < VirtualKey::F1 || args->VirtualKey > VirtualKey::F24)
-    {
```
seems pretty bogus, as discussed

**Comment by afedchin** [comment]
> When using keyboard on PC, some of the alphanum were showing numbers, on the left of my azerty keyboard, a bit like if they were translated to numpad.

dont' understand what's difference. the same events handled by one method instead of three, and as I can understand CoreDispatcher event are little more low level

**Comment by koying** [comment]
I think the difference is that `OnAcceleratorKeyActivated` only deals with keycodes, while the current implem actually get unicode chars in `OnCharacterReceived`

**Comment by afedchin** [comment]
I've tested with my russian keyboard and all work perfect.

**Comment by afedchin** [comment]
I've tested Kodi on XB1 with peripheral.joystik and gamepad is working well. no need to extra support it inside keyevents.

**Comment by koying** [comment]
Superseded by https://github.com/xbmc/xbmc/pull/13024

**Pull request closed without merging**
