### PR TITLE
[Estuary] Also start timer (with reset) on seeks

### PR DESCRIPTION
**Pull request by enen92**
## Description
Another one, this time found by @CrystalP. It seems Kodi does not unload the custom window (and load it again) when we perform seeks since it depends on dialog seekbar visibility. Since the timer is only started on window load, we might get to a situation where the control group is visible again (with the window already loaded) but the timer is not running. Hence, this make sure we start the timer (with reset) on the same condition we already do for reset (seeks, rewind, etc).

Ref: https://github.com/xbmc/xbmc/pull/23380#issuecomment-1589821366

### CODE REVIEW

**Comment by enen92** [comment]
just noticed the timer should be called `1109_topbaroverlay` reference to the custom window id and not really 1110 :)
Since it doesn't affect functionality (it's just a string) I'll make the correction later.

**Review by CrystalP — APPROVED** [review]

**Comment by enen92** [comment]
> Thanks! Is it on purpose that the bar remains visible while forwarding / rewinding more than 5 sec? Just curious, some probably like it like that.

I think this is by design, its not a regression but rather how it has worked before. We can change that behaviour but my feeling is that it will just lead to bikeshedding (some will like the previous behaviour, others the new...).

I've looked a bit more into this and found that the parsing of the xml for the reset condition of the timer on start was wrong (was being obtained from the main node and not from the `<start>` child element. While at it also renamed the timer and added the condition to stop the timer when the player is playing (otherwise we need to wait a couple of seconds for the timer to stop...for no reason). Dialog is closed but the timer is left running on the background for a couple of seconds for no reason.

@CrystalP mind taking another look? I'd like to have this into alpha 2 since it's a regression

**Comment by CrystalP** [comment]
@enen92 Don't know how to check the timer stops when it's meant to, but still works well in GUI as a user!

**Comment by enen92** [comment]
Usually I just manually add onstart and onstop builtins on the timer definition:

```
<timer>
...
<onstart>Notification(timer, started, 1000)</onstart>
<onstop>Notification(timer, stopped, 1000)</onstot>
</timer>
```

**Pull request merged**
