### PR TITLE
[seek] fix crash if no seek steps are found for the selected direction

### PR DESCRIPTION
**Pull request by xhaggi**
As the title said this fix a possible crash if no seek steps are configured for the selected direction.

EDIT: It also reduces some code duplication in the method `GetSeekSeconds()`.

@mkortstiege mind taking a look

### CODE REVIEW

**Comment by xhaggi** [comment]
@da-anda forgot to ping you too ;)

**Comment by mkortstiege** [comment]
Looks good to me.

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by da-anda** [comment]
untested and only had a brief look, but looks good. But I was wondering if in addition to this change we probably should also try to prevent users from misconfiguring in first place? So when processing the "onSettingsChanged" (or the signal fired off before that allows to prevent the new value to apply or be changed) we make sure that at least one step size for each direction is being set.

**Comment by MilhouseVH** [comment]
Tested in OpenELEC. When no seek steps are configured there is no left/right seeking at all, which is perfect. Many thanks.

**Comment by da-anda** [comment]
why would we want no left/right seek to happen when seeking left/right?

**Comment by jjd-uk** [comment]
If no seek steps are configured then not doing any seek at all upon a left/right key press is exactly what I'd expect to see.

**Comment by MilhouseVH** [comment]
> why would we want no left/right seek to happen when seeking left/right?

No seek steps configured, so no step seeking (you can still do the 2x/4x/8x/etc). Seems reasonable to me. What else should it do?

**Comment by da-anda** [comment]
we should not allow to have no seek step for a direction in first place. IMO if one triggers the "STEP_FORWARD" action it should always do a step forward. If one doesn't, then he should change the keymap not to call this action but NOOP or whatever. So the second the seek steps are changed in the settings we should make sure at least 1 is selected for each direction

**Comment by jjd-uk** [comment]
@da-anda 

Take the case where you have one seek step, let's say -7s for if you miss a word,  so the left key carries out the -7s seek, but would you want the right key to do anything? I think not in case the right key is accidentally pressed. Therefore if no negative seek step is configured then no action by left key, and if no positive seek step configured then no action on right key press, thus behaviour is fully under user control.

**Comment by da-anda** [comment]
ok, if you think this is fine, then fine with  me.

**Comment by MilhouseVH** [comment]
I suspect requiring a minimum of one in each direction is likely to prove tricky.

However this solution affords more flexibility, potentially allowing an ordinary user to disable forward, backward, or both seek directions, and without digging into keymaps.

**Comment by jjd-uk** [comment]
I can see what you're saying, yes the keymap can be changed if you don't want to seek in a particular direction, or not at all in both directions.

I'm however trying to see this from a average user point of view, for whom adjusting a GUI setting is a lot easier than editing an xml.

**Comment by xhaggi** [comment]
thanks for the review, tests and discussion ;)

**Pull request merged**
