### PR TITLE
[webOS] Signal Dolby Vision with AV1 codec

### PR DESCRIPTION
**Pull request by quietvoid**
## Description
Adds the Dolby Vision payload metadata on playback of detected Dolby Vision AV1 files.

## Motivation and context
Allows playing AV1 Dolby Vision files on supported webOS devices.

## How has this been tested?
Runtime tested on LG OLED C2.

## What is the effect on users?
Plays AV1 Dolby Vision correctly for sets that support it.

Up until now, I think it has mostly been assumed to be LG TVs, most of which support Dolby Vision.
I'm not sure if this has any negative impact on devices that don't, and there doesn't seem to be a way to detect Dolby Vision capabilities currently.

And those that don't support AV1, well I assume it falls back to software decoding but I have no way to test.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by sundermann** [comment]
Do you have a sample AV1 DoVi file for me to test?

**Comment by quietvoid** [comment]
@sundermann Here's one I have on hand: https://0x0.st/HOP7.mkv
It's a bit broken since it's concatenated to add up to 2min+, and the 2nd half doesn't play.

There's a bug with playback on webOS where files under ~1min30 fail playing at all.

**Review by sundermann — APPROVED** [review]
Sorry for the delay. Finally got around to testing this and it triggers DoVi on the AV1 testfile provided.

**Comment by sundermann** [comment]
I was just wondering if the check for profile version 10 specifically is really needed

**Comment by quietvoid** [comment]
> I was just wondering if the check for profile version 10 specifically is really needed

Probably not, but any other profile isn't valid for AV1.

**Pull request merged**
