### PR TITLE
[WinRenderer] Fix HQ scallers, to avoid unnecessary scaling at Stage1…

### PR DESCRIPTION
**Pull request by afedchin**
… (with DXVA processor and color shader). This also fixes HQ scallers for TAB/SBS modes.

@da-anda ping

### CODE REVIEW

**Comment by afedchin** [comment]
jenkins build this please

**Comment by afedchin** [comment]
build error in unrelated.

**Comment by da-anda** [comment]
I tried to reproduce the users issue and it seems partly fixed with this. HQ scalers are behaving correctly now. When switching form HQ scales to bicubic I noticed some shifting of the video in the rect of the right eye in SBS mode - the video itself didn't exceed the mask though - it only seems to be aligned differently within the mask than on HQ scalers.

However, using "Render method: Software", DXVA2 HW accell and "Video scaling method: DXVA" (in VideoOSD) is still having the clipping issue of the right eye.

**Comment by afedchin** [comment]
there is a difference between DXVA scaling and others and the difference is not 3D related. A little clipping/shifting (about half of pixel) occurs also on normal videos and stereo movies for *both* eyes. This issue exists in dx9 version also. I don't know exactly why it occurs.

**Comment by fritsch** [comment]
Pixelratio not 1.0? If that's the case - 1920 width will be scaled whenever 1920 * pixelratio < 1919 :-)

**Comment by da-anda** [comment]
here a short screen capture of the issue with DXVA scaling vs HQ-scaler (every other scaler works like lanzcos3) https://youtu.be/HG3gNy2ToaE

**Comment by fritsch** [comment]
I'd prefer a debuglog ...

**Comment by afedchin** [comment]
@da-anda I have no issue with dxva https://youtu.be/VsIdnVYCRe0 I think @fritsch is right debuglog would be helpfull

**Comment by da-anda** [comment]
@afedchin have you zoomed the video? (can't read russian)
here is a debuglog with component debugging of video component turned on - but I don't think it's of any help as it only shows the shaders loaded when I cycled through them http://xbmclogs.com/podh2jozc

**Comment by afedchin** [comment]
@da-anda of course, before test I have setted zoom to 1.52 instead of normal 1.0
updated. check this again please

**Comment by da-anda** [comment]
@afedchin just tested - still having that issue. Maybe related to my old AMD GPU?

**Comment by afedchin** [comment]
I've noticed that you tested with sbs file. I always tested with tab file. I need to do some testing with sbs file.

**Comment by afedchin** [comment]
I've tested with SBS file and still no issue. Perhaps your driver ignores scissor on some stage. I've added a temporary commit which perhaps solves the issue, but with no warranty. @da-anda test it please. thanks.

**Comment by afedchin** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
ignore droid failures

**Comment by afedchin** [comment]
got positive feedback from user. this can be merged before a4 is released.

**Pull request merged**
