### PR TITLE
Fix event server unable to send raw key strikes

### PR DESCRIPTION
**Pull request by Tolriq**
Broken after https://github.com/xbmc/xbmc/pull/17806

@phunkyfish @garbear @DaveTBlake 

## Description

Part of EventServer is broken

Since the bug was backported a backport of the fix would be nice.

The fix does fix the bug but does not impact the intent of the initial PR, that part of the change was unnecessary and unwanted.

## Motivation and Context

Fix Event Server

## How Has This Been Tested?

Sending EventServer unicode keys

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by phunkyfish** [comment]
A backport won't be possible as 18.8 is the final release.

**Comment by DaveTBlake** [comment]
I think it is worth labelling this as "backport needed" to flag that the regression is in 18.8 and could be picked up. At this point it is the 2nd fix in this situiation. While I do not expect us to do any more point releases for Leia, it does no harm to use the flag to keep track of such things.

**Review by DaveTBlake — APPROVED** [review]
Thanks for this @Tolriq

**Comment by a1rwulf** [comment]
@Tolriq I'm not 100% fit in the area, but I recently debuggt an issue as well.
Is it possible to have longpress mappings for those keycodes?
If so, did you test to trigger a key that has a longpress mapping?

**Comment by Tolriq** [comment]
Not really, this is a special case to send raw unicode keys to fill input texts.
In all cases setting SetFromService is completely wrong as this is for special cases and is handled as special cases later in the code generating all kind of issues.
If there's need for a special case, then a new flag must be created and used.

For the record I wrote this part in my first PR for Kodi 8 years ago :) (https://github.com/xbmc/xbmc/pull/1612)

**Comment by a1rwulf** [comment]
All fine, I just know that `OnKey` doesn't work if keys have a longpress mapping, unless that key has `SetFromService = true`.
I'm trying to fix this for buttons that come from json: https://github.com/xbmc/xbmc/pull/18302

**Comment by Tolriq** [comment]
Yes there's also some missing parts to EventServer too but last time I tried to help to have working solution for Retroplayer I was banned for unknown reasons :)
So I'll avoid architectural discussions for now. 

But happy to test regressions and give input on anything decided.

**Pull request merged**
