### PR TITLE
[cleanup] remove unused fields, variables and enum

### PR DESCRIPTION
**Pull request by Rechi**
## Description
Remove unused fields, variables and enum.

## Motivation and Context
silent compiler warnings

## How Has This Been Tested?
compiled for windows and osx

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by Rechi** [comment]
jenkins build this please

**Comment by Rechi** [comment]
any objections?

**Review by peak3d — APPROVED** [review]
looks fine for me

**Comment by peak3d** [comment]
Modifiing in AMLCodec will most probably lead to issues merging / rebasing vpupdates branch.

**Comment by garbear** [comment]
I rebased the latest vpupdates branch on this and there were no merge conflicts.

**Comment by garbear** [comment]
should we wait until vpupdates is merged? I see some calls to jenkins, does this mean that the merge will happen within the next couple days?

**Comment by peak3d** [comment]
thanx for the info @garbear

**Comment by Rechi** [comment]
@peak3d that's only a single line removed in `AMLCodec.h` so should be easy to rebase if there is a conflict.

jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
