### PR TITLE
[videodb] Never clean empty TV shows if the path still exists.

### PR DESCRIPTION
**Pull request by ghost**
Split from #6024.

If I've reread the various comments there correctly, we agreed that TV shows with no episodes should never be removed from the database if the path still exists (and a specific setting is superfluous too).

@Montellese

### CODE REVIEW

**Comment by HitcherUK** [comment]
Thanks.

**Comment by Montellese** [comment]
Yeah should be good.

**Comment by hudokkow** [comment]
jenkins build this please

**Comment by vbat99** [comment]
Thank you.  it has been annoying to see series removed during a clean, to re-appear again on Library Updates.

**Comment by uNiversaI** [comment]
I removed a TV show from my NAS directory completely, then cleaned library and the whole content was removed as expected except for the TVshow Library entry in List view.

Up until this commit whenever I did this the lot was removed as expected, with this, the entry is left festering behind when it doesnt exist anywhere and no advancedsettings or anything else is being used here.

Only solution was to delete entry manually.

**Comment by anaconda** [comment]
@uNiversaI I've tried to reproduce this.
When cleaning TV shows:
* we delete episodes that no longer exist;
* we delete paths that no longer exist;
* we delete the TV show if it has no paths associated.

Here:
* a first library clean only deleted episodes and paths;
* a second clean finally deleted the TV show.

Can you confirm this?
In that case, something here isn't working properly:
https://github.com/xbmc/xbmc/blob/master/xbmc/video/VideoDatabase.cpp#L7878-L7894

**Comment by uNiversaI** [comment]
second clean dindt change anything I had to finally delete the empty entry manually.

**Pull request merged**
