### PR TITLE
[cmake] remove _LINUX define

### PR DESCRIPTION
**Pull request by lrusak**
We don't need both `TARGET_LINUX` and `_LINUX` defines, Let's simplify things.

### CODE REVIEW

**Comment by lrusak** [comment]
jenkins build this please

**Review by Rechi — COMMENTED** [review]
To be consistent, https://github.com/xbmc/xbmc/blob/master/tools/depends/m4/xbmc_arch.m4 should be adjusted too.

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
@Rechi ping for second round review

**Comment by lrusak** [comment]
jenkins build this please

**Review by Rechi — APPROVED** [review]

**Pull request merged**
