### PR TITLE
Cleanup dll loader / posix win32 emulation functions.

### PR DESCRIPTION
**Pull request by notspiff**
This is a contribution towards cleaning up the mess that is xbmc/linux and (parts of) xbmc/cores/DllLoader.
- remove hresult style code from generic code (also removes mixing of errno and hresult codes).
- remove unused utilities from the win32 emu code
- remove the includes of these from platformincludes. this makes it much easier to track where these things are actually used, and reduces compilation unit sizes (latter probably only of academic interest).

due to the header changes, i fully expect this to (trivially) break on osx and droid. jenkins will light the way.

### CODE REVIEW

**Comment by fritsch** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
Highly approved

**Comment by MartijnKaijser** [comment]
Could you rebase? Thx

**Comment by notspiff** [comment]
done.

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
seems only win32 is happy

**Comment by notspiff** [comment]
try now.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by notspiff** [comment]
one more round. travis doesn't catch it all it seems.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by akva2** [comment]
two failures; the osx one is trivial, can someone on osx replace with PosixFile/Directory usage ?

the rbpi one i asked @popcornmix for some help/info on but he hasn't gotten back to me on it yet.

**Comment by popcornmix** [comment]
@akva2 I did comment on IRC but I suspect you missed it.
Can we just move the WAVEFORMATEXTENSIBLE structure into OMXAudio.h?

**Comment by notspiff** [comment]
right. yeah, that's the fallback solution. will do so.

**Comment by akva2** [comment]
somebody kick off jenkins please.

@memphiz could you please look at the osx thingie? logs are gone now but it's pretty trivial. somewhere in the osx specific code CreateFile / WriteFile is used. this pr removes those wrapper functions so we need to use CPosixFile instead.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
somebody handled it already?

**Comment by akva2** [comment]
No it was to get you the logs plus check the rbp part

-------- Opprinnelig melding --------
Fra: Memphiz <notifications@github.com>
Dato: 02.04.2016 12:24 (GMT+01:00)
Til: xbmc/xbmc <xbmc@noreply.github.com>
Ko: Arne Morten Kvarving <Arne.Morten.Kvarving@sintef.no>
Emne: Re: [xbmc/xbmc] Cleanup dll loader / posix win32 emulation functions. (#8798)


somebody handled it already?

**Comment by popcornmix** [comment]
@akva2 https://github.com/popcornmix/xbmc/commit/b2eaa436248128e1916c7a86ad02a6e250daa019 fixes build of OMXAudio.cpp

**Comment by Memphiz** [comment]
well this is what i found : https://github.com/Memphiz/xbmc/commit/b9059554ea556b3a9ab271bf67626ef8122c24a3 i can't compile any further because it can't find _aligned_free in CBaseTexture (something which was added in the ffmpeg3 bump - maybe some include is missing now with your cleanup?)

**Comment by popcornmix** [comment]
I added https://github.com/popcornmix/xbmc/commit/f17e84ddbe497a117979df2e1811bc98ef28c70b for the Texture.cpp failure.

**Comment by akva2** [comment]
Yes you need linux/XMemUtils.h explicitly now, instead of pulling it into all compilation units.

-------- Opprinnelig melding --------
Fra: Memphiz <notifications@github.com>
Dato: 02.04.2016 14:16 (GMT+01:00)
Til: xbmc/xbmc <xbmc@noreply.github.com>
Ko: Arne Morten Kvarving <Arne.Morten.Kvarving@sintef.no>
Emne: Re: [xbmc/xbmc] Cleanup dll loader / posix win32 emulation functions. (#8798)


well this is what i found : Memphiz@b905955<https://github.com/Memphiz/xbmc/commit/b9059554ea556b3a9ab271bf67626ef8122c24a3> i can't compile any further because it can't find _aligned_free in CBaseTexture (something which was added in the ffmpeg3 bump - maybe some include is missing now with your cleanup?)

**Comment by fritsch** [comment]
@popcornmix that one is correct - please submit it anyways.

**Comment by popcornmix** [comment]
@akva2 feel free to cherry-pick/squash my commits.

**Comment by akva2** [comment]
Thanks i will but i am out of the house for a few hours..

-------- Opprinnelig melding --------
Fra: popcornmix <notifications@github.com>
Dato: 02.04.2016 14:23 (GMT+01:00)
Til: xbmc/xbmc <xbmc@noreply.github.com>
Ko: Arne Morten Kvarving <Arne.Morten.Kvarving@sintef.no>
Emne: Re: [xbmc/xbmc] Cleanup dll loader / posix win32 emulation functions. (#8798)


@akva2<https://github.com/akva2> feel free to cherry-pick/squash my commits.

**Comment by Memphiz** [comment]
all in all in addition to the missing include in cbasetexture from popcornmix this is what you need for osx:

https://github.com/Memphiz/xbmc/commits/prune_emu (top 3 commits) - not sure if i have enough time to check ios aswell ...

**Comment by Memphiz** [comment]
updated https://github.com/Memphiz/xbmc/commits/prune_emu - first 5 will cover osx and ios

**Comment by akva2** [comment]
sorry for the delay and thanks for your help. should be fine now (everything is squashed up to avoid broken revisions).

**Comment by FernetMenta** [comment]
thanks
jenkins build this please

**Comment by akva2** [comment]
XTimeUtils.h added to droid file as well.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
ready to go or do we need to wait for something here?

**Comment by akva2** [comment]
ready to go as far as i am concerned.

**Comment by FernetMenta** [comment]
thanks!

**Pull request merged**
