### PR TITLE
FIX: [gles;font] do not clip rotated text

### PR DESCRIPTION
**Pull request by koying**
@bavison This seems to fix a bad clipping issue with rotated font.
Check the Eminence skin for examples of the issue, in Settings, on the right.

### CODE REVIEW

**Comment by afedchin** [comment]
This seems fix only static rotated font. If rotated font has also a scroll attribute then this causes going beyond label area like at screenshot.
screenshot011

 I have same issue with dx11 implementation.

**Comment by afedchin** [comment]
Never mind. My previous comment is related only for dx11 implementation.

**Comment by MilhouseVH** [comment]
Excellent, thanks - this fixes the clipping issue I mentioned in #6873.

**Comment by koying** [comment]
jenkins build and merge

**Comment by da-anda** [comment]
I noticed issues with rotated text in Eminence skin but always forgot to report it - will test if these are also fixed by this change and report back if not

**Comment by koying** [comment]
Surely fixed by me ;)
Now, as @afedchin reported, there can very well be still an issue with rotated scrolling text, but that's above my competence, as the font rewrite specifically exclude rotated text from clipping.

**Comment by afedchin** [comment]
Don't pay attention to my comment, there was an issue in dx implementation which I already fixed.

-----Original Message-----

**Pull request merged**
