### PR TITLE
[Xbox] Fix crash on close App

### PR DESCRIPTION
**Pull request by thexai**
## Description
[Xbox] Fix crash on close App

## Motivation and context
Found while debugging in Xbox. 

Consistent crash on exit due is tried to log an event when logging component is already destroyed.

crash1

crash2

crash3

## How has this been tested?
Runtime / Debug tested

## What is the effect on users?
Exit clean on Xbox although is hard to notice due only was crashing at exit anyway.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by garbear — APPROVED** [review]
Fix makes sense, a less-important debug level line should be skipped in a situation outside of when logging is expected to be up. Races could be an issue but I don't _think_ they are here.

Can you rebase on master after merging https://github.com/xbmc/xbmc/pull/24089? That should fix the Jenkins errors.

**Comment by thexai** [comment]
Jenkins build this please

**Comment by CrystalP** [comment]
That fix helps with one code path but feels like a band aid for an object that's not properly guarded

Would this in ```FormatAndLogInternal``` help?
```
if (m_defaultLogger)
  m_defaultLogger->log(level, message);
```

**Comment by lrusak** [comment]
Should windowing be outliving logging?

**Comment by thexai** [comment]
> Would this in FormatAndLogInternal help?

Seems rare but crash in `if (m_defaultLogger)` then:

crash4

**Comment by thexai** [comment]
> Should windowing be outliving logging?

Seems isolated issue due delayed event received when last window is destroyed. Probably window destroyed when logging it is active but event is received a bit latter... It doesn't seem worth changing other major things (the unload components sequence) which may end up causing more side effects in the end.

**Comment by lrusak** [comment]
> > Should windowing be outliving logging?
> 
> 
> 
> Seems isolated issue due delayed event received when last window is destroyed. Probably window destroyed when logging it is active but event is received a bit latter... It doesn't seem worth changing other major things (the unload components sequence) which may end up causing more/worse side effects in the end.

Should the event handlers be detached as part of the DestroyWindowSystem ?

**Comment by thexai** [comment]
The PR is green and it is not productive to spend more time on this when there are much more important things to do.

**Comment by garbear** [comment]
Indeed, we fix things properly instead of bandaiding now. Yoloing a PR when other team members have raised concerns destroys the culture we fought hard to build.

I don't think PR color and (to self-deprecate) "garbear says ok" is enough confirmation to merge.

@thexai As maintainer of the xbox you prioritize where your productivity goes, but you should consider respecting the culture we've built together and, as lrusak says, fix it properly.

Reverting this PR in the meantime would show this respect, but so would continuing discussion here.

**Comment by garbear** [comment]
I have fault too, I learned my lesson in being too quick to approve a PR with too little of a disclaimer.

**Comment by thexai** [comment]
It is not necessary revert a commit which fixes a crash and does not cause any side effect. Me (or anyone interested) can continue working on this in the background and propose a better solution. Meanwhile no more crash.

**Comment by garbear** [comment]
Agreed don't revert.

But should windowing be outliving logging?

**Comment by thexai** [comment]
I don't know, to answer I would need to look carefully at the code and I haven't.

**Pull request merged**
