### PR TITLE
[profiles] restore saving lock preferences

### LINKED ISSUE #17412: Leia not saving lock preferences
### Describe the bug
lock preferences (master lock, lock video windows, etc.) apply on the running instance, but never get saved to profiles.xml

They're lost on exit and restart.

## Expected Behavior
Preferences should be saved

## Possible Fix
partial revert of PR #16988 that is already merged
the fix for leia is pending in PR #17413 

### To Reproduce
1. Set up lock-preferences in Leia (see screenshot below)
2. Exit or restart Kodi
3. The preferences are lost

### Debuglog
https://paste.kodi.tv/idirebosoq.kodi

### Screenshots 

screenshot003

### Your Environment
Used Operating system:
 - [X] Linux

 - Operating system version/name: Debian Stretch 9
 - Kodi version: 18.5 / 18.6 Leia

### PR DESCRIPTION
**Pull request by howie-f**
## Description
restores functionality removed in PR #16988
fixes #17412

## How Has This Been Tested?
tested locally

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document

@fritsch @rechi for review

### CODE REVIEW

**Comment by fuzzard** [comment]
Havent forgotten this @howie-f 
Just chasing up info internally about why the offending change was done. The only reason its not in master is the backport PR was merged first, and the master PR is still pending.

**Comment by howie-f** [comment]
all fine @fuzzard, thanks a lot :)

**Comment by DaveTBlake** [comment]
Clarify the tangle of profile changes please.  Is this a backport (or partial one), and which PR on master? Add that link and adjust labels.

**Comment by fuzzard** [comment]
Open Master PR - https://github.com/xbmc/xbmc/pull/17031
Merged Leia PR - https://github.com/xbmc/xbmc/pull/16988

This is a partial revert of the merged Leia PR. Open Master PR needs to be assessed before merging due to this reported issue https://github.com/xbmc/xbmc/issues/17412

**Comment by fuzzard** [comment]
Thanks for the contribution @howie-f

**Pull request merged**
