### PR TITLE
Tests: Fix up TestTextureUtils.cpp after 932b0d2cec13970bf1f1e78cb6642e3890ce9d68

### PR DESCRIPTION
**Pull request by fritsch**
Fix up tests after: 932b0d2cec13970bf1f1e78cb6642e3890ce9d68

Wait a moment, will look for the PVR one, too.

### CODE REVIEW

**Comment by fritsch** [comment]
@stefansaraev mind adding a valid PVR path via 4feb9346efbe5f5e06c3e89810741365fba1604a to ./utils/test/TestURIUtils.cpp please?

**Comment by fritsch** [comment]
@stefansaraev added something - the IsLiveTV test is "funny" ...

jenkins build this please

**Comment by fritsch** [comment]
jenkins test this please

**Comment by stefansaraev** [comment]
@Memphiz is this ok ?

**Comment by Memphiz** [comment]
Looks ok to me - thx fritsch

**Pull request merged**
