### PR TITLE
[CMAKE] update Findpython module

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Update Findpython cmake module to utilise cmake 3.12's FindPython3 module. This allows us to not have to update version numbers as is required currently.

Implement the following 2 cmake vars

USE_PYTHON_DIR - provide system dir for the search of the python libs/includes
default behaviour without this will search for any "common" locations for the platform
```
-DUSE_PYTHON_DIR=/path/to/python
```

USE_PYTHON_VER - forces an exact version to search for. Will fail if it does not find the specified version
default behaviour without this is to return highest version found
```
-DUSE_PYTHON_VER=3.8
```

## Motivation and context
minimise the constant updating of version numbers when cpython releases new versions
Also had a "what if" question regarding the ability to set a particular version to be used by the build system

## How has this been tested?
osx

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by garbear — APPROVED** [review]
Looks like a good change. I read the CMake and nothing looked out of place.

**Review by wsnipex — APPROVED** [review]
Definitely a good improvement.
Personally, I'd name the new vars more in line with https://github.com/xbmc/xbmc/blob/Matrix/cmake/modules/FindFFMPEG.cmake#L12-L18, not a blocker though.

**Comment by fuzzard** [comment]
No worries happy to change var names. I'll add doc info about them as well while I'm at it

**Comment by bkuhls** [comment]
Kodi 19 fails to build with python-3.10.
What is the preferred solution: backport this patch (and 20058 & 20171) or add 3.10 like in the past: https://github.com/xbmc/xbmc/commit/0c59dae5cfb626ba92c749a90d1e61db8109dad0 ?

**Pull request merged**
