### PR TITLE
Fix two unit test build failures

### PR DESCRIPTION
**Pull request by MaxKellermann**

### CODE REVIEW

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
Travis-ci build error fixed, but still bombs on test execution, but this is unrelated to this PR.
<pre>
Program terminated with signal SIGSEGV, Segmentation fault.
#0  CServiceManager::GetPVRManager (this=0x0) at ServiceManager.cpp:84
84	  return *m_PVRManager;

Thread 1 (Thread 0x7fa9ca1f4800 (LWP 8983)):
#0  CServiceManager::GetPVRManager (this=0x0) at ServiceManager.cpp:84
#1  0x0000000001c3ffb7 in CServiceBroker::GetPVRManager () at ServiceBroker.cpp:46
#2  0x0000000001af84b5 in PVR::CPVRManager::GetInstance () at PVRManager.cpp:144
#3  0x0000000000a26cf0 in CSettings::InitializeISettingCallbacks (this=this@entry=0x2a0a5e0 <CSettings::GetInstance()::sSettings>) at Settings.cpp:1159
#4  0x0000000000a271f9 in CSettings::Initialize (this=0x2a0a5e0 <CSettings::GetInstance()::sSettings>) at Settings.cpp:459
#5  0x0000000001f4d673 in TestBasicEnvironment::SetUp (this=0x3424f20) at TestBasicEnvironment.cpp:65
#6  0x0000000001d85a05 in SetUpEnvironment (env=<optimized out>) at ./src/gtest.cc:4210
#7  for_each<__gnu_cxx::__normal_iterator<testing::Environment* const*, std::vector<testing::Environment*> >, void (*)(testing::Environment*)> (__f=<optimized out>, __last=..., __first=) at /usr/include/c++/4.8/bits/stl_algo.h:4417
#8  ForEach<std::vector<testing::Environment*>, void (*)(testing::Environment*)> (functor=<optimized out>, c=std::vector of length 1, capacity 1 = {...}) at ./src/gtest-internal-inl.h:296
#9  testing::internal::UnitTestImpl::RunAllTests (this=0x33e94b0) at ./src/gtest.cc:4307
#10 0x0000000001d85d14 in HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (location=<optimized out>, method=<optimized out>, object=<optimized out>) at ./src/gtest.cc:2078
#11 HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (location=0x22d1b20 "auxiliary test code (environments or event listeners)", method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x1d85820 <testing::internal::UnitTestImpl::RunAllTests()>, object=0x33e94b0) at ./src/gtest.cc:2114
#12 testing::UnitTest::Run (this=<optimized out>) at ./src/gtest.cc:3929
#13 0x000000000090758a in RUN_ALL_TESTS () at ../../lib/gtest/include/gtest/gtest.h:2288
#14 main (argc=1, argv=<optimized out>) at xbmc-test.cpp:42
</pre>

**Comment by fetzerch** [comment]
Could you move line 65: `CSettings::GetInstance().Initialize();` below the initialization of `CServiceManager`? That should fix the crash.

**Comment by ksooo** [comment]
Travis-CI still not happy, but unrelated to the fixes done in this PR.

<pre>
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000018a1324 in CScriptInvocationManager::Process (this=this@entry=0x3013a00 <CScriptInvocationManager::GetInstance()::s_instance>) at ScriptInvocationManager.cpp:82
82	    it->second->Process();

Thread 1 (Thread 0x7f0a12a66800 (LWP 8954)):
#0  0x00000000018a1324 in CScriptInvocationManager::Process (this=this@entry=0x3013a00 <CScriptInvocationManager::GetInstance()::s_instance>) at ScriptInvocationManager.cpp:82
#1  0x00000000018a1828 in CScriptInvocationManager::Uninitialize (this=this@entry=0x3013a00 <CScriptInvocationManager::GetInstance()::s_instance>) at ScriptInvocationManager.cpp:90
#2  0x00000000018a1dc7 in CScriptInvocationManager::~CScriptInvocationManager (this=0x3013a00 <CScriptInvocationManager::GetInstance()::s_instance>, __in_chrg=<optimized out>) at ScriptInvocationManager.cpp:44
#3  0x00007f0a0ac27259 in __run_exit_handlers (status=0, listp=0x7f0a0afa96c8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#4  0x00007f0a0ac272a5 in __GI_exit (status=<optimized out>) at exit.c:104
#5  0x00007f0a0ac0cecc in __libc_start_main (main=0x907520 <main(int, char**)>, argc=1, argv=0x7fffba650ba8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffba650b98) at libc-start.c:321
#6  0x0000000000907679 in _start ()
</pre>

**Comment by ksooo** [comment]
jenkins build this please

**Comment by MaxKellermann** [comment]
Looks like everything went well, only the WIN32 build is "unstable" because:

    error: downloading
      'http://mirrors.kodi.tv/build-deps/sources/platform-1.0.9.tar.gz' failed

Yet another unrelated build failure.

**Pull request merged**
