### PR TITLE
[lang] Remove line breaks used in dialogs

### PR DESCRIPTION
**Pull request by MartijnKaijser**

### CODE REVIEW

**Comment by uNiversaI** [comment]
As long as it doesn't wrap its fine else its awry

**Comment by da-anda** [comment]
fine with me

**Comment by Montellese** [comment]
In some cases (e.g. the first one with the "Warning:" string it makes sense to have them on a separate line to make it easier to spot. Having a "Warning:" at the beginning of a new line is much more obvious than having it somewhere on the same line with other text.

**Comment by MartijnKaijser** [comment]
My reasoning for removing the line breaks is that the translated text could already be two lines before the break (translations can be quite long). After could be another two which would cause scrolling text on most skins

**Comment by Montellese** [comment]
Yes but we do not force the line break on translators. If the translation is long they can simply omit the line break. In English removing the line break IMO makes the warning much less obvious than it should be.

**Comment by MartijnKaijser** [comment]
Actually I think we do force the line break as @alanwww1 runs it through his script and it's marked as an issue. Could be wrong 
I'm OK to drop it for noe to get the rest done. I have preference on how the warning is presented

**Comment by MartijnKaijser** [comment]
kept the line break for the warning and updated the PR

**Pull request merged**
