### PR TITLE
[windows] BuildSetup.bat: use a platform-specific kodi-build directory

### PR DESCRIPTION
**Pull request by Montellese**
## Motivation and Context
While setting up the windows build slave I'm hosting I noticed that running `BuildSetup.bat` for different platforms (I wanted to test them all) always builds in `kodi-build` which is a bit frustrating because it doesn't allow us to build for multiple platforms in parallel.

## Description
Therefore I've added the `TARGET_PLATFORM` variable to `BuildSetup.bat` which is appended to the `kodi-build` directory resulting in
* `kodi-build.win32`
* `kodi-build.x64`
* `kodi-build.win32-uwp`
* `kodi-build.x64-uwp`
* `kodi-build.arm-uwp`

I'm not sure if this requires any changes to Jenkins and hope that I found all usages of `kodi-build` in the windows buildsystem.

## How Has This Been Tested?
Manually on the new windows build slave.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Review by Paxxi — APPROVED** [review]
looks good to me. I don't really know anything about how Jenkins is set up so can't comment on that

**Comment by Montellese** [comment]
Maybe @lrusak can answer whether this has an impact on Jenkins build instructions or not?

**Comment by lrusak** [comment]
I don't see it being an issue as each platform is build in it's own workspace in jenkins anyways. I would just let it run and see what jenkins says.

**Comment by Montellese** [comment]
jenkins build this please

**Comment by Montellese** [comment]
Hm that doesn't seem to have worked. jenkins build this please

**Pull request merged**
