### PR TITLE
[pvr] code cleanup

### PR DESCRIPTION
**Pull request by AlwinEsch**
The changes on this request are not problematic, are was done from me during binary add-on class combination and now added as separate request.

I cleaned up the code and brings it one step more near to ADSP add-on structure.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
you know that we just moved to beta and those kind of changes have to wait for 17.0?

**Comment by AlwinEsch** [comment]
From my side to beta, no special work flow or code change.

**Comment by ksooo** [comment]
I agree with @FernetMenta. Merge window for Alpha4 closed yesterday and no such code changes in beta phase.

**Comment by AlwinEsch** [comment]
OK no problem. Has forgot the date limit from yesterday, sorry.

**Comment by ksooo** [comment]
Cool. Thanks, Alwin.

**Comment by Jalle19** [comment]
I thought beta for us meant "API freeze", not a total freeze.

**Comment by ksooo** [comment]
Not sure. In the projects I was involved so far beta basically ment avoid all code changes that are not really necessary, with the goal to reduce regression risk. ... No new features, no more just cleanups, only bug fixes ... and this model worked out quite well to hold timelines for releases.

**Comment by MartijnKaijser** [comment]
@ksooo is correct. We should limit code changes to fixes only for beta or at least near zero regression chance. In rc even be more stringent.

**Comment by Jalle19** [comment]
The problem with that is it tends to create unrebaseable ghost PRs of PRs like this.

**Comment by ksooo** [comment]
Well, I would just not come up with this kind of PR in this phase of the release cycle and put such things on my todo list for times where master is open again.

**Comment by AlwinEsch** [comment]
Is updated now and currently running a recheck here.

**Comment by AlwinEsch** [comment]
Jenkins build this please

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by AlwinEsch** [comment]
OK to merge in?

**Comment by ksooo** [comment]
Well, no. See my comments above. I still think beta phase is not okay to merge stuff like this

**Pull request closed without merging**
