### PR TITLE
app: move first access of CPlaylistPlayer after init

### PR DESCRIPTION
**Pull request by FernetMenta**
fix for http://trac.kodi.tv/ticket/16969

### CODE REVIEW

**Comment by FernetMenta** [comment]
@MartijnKaijser @fritsch does this fix your issues?

**Comment by fritsch** [comment]
Thanks very much. This is one of the ugliest dependencies we have when bringing up kodi ... all those globals and ways of correctly initializing them in the correct order :-(

**Comment by fritsch** [comment]
jenkins build this please (was told android would not work, let's see)

**Comment by fritsch** [comment]
Might be needed on Android: https://github.com/fritsch/xbmc/commit/cfc58c8d20d1793d97c3d47bf3f17d5520c2b3e8 (let's find out)

**Comment by MartijnKaijser** [comment]
@FernetMenta iOS also need a fix and test-suite as well. See jenkins logs

**Comment by FernetMenta** [comment]
ok, will fix

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
Confirmed fixed

**Comment by FernetMenta** [comment]
jenkins build this please

**Pull request merged**
