### PR TITLE
[cleanup][libUPnP] remove platinum prebuild darwin frameworks

### PR DESCRIPTION
**Pull request by Rechi**
## Description
remove unused prebuild darwin frameworks

## Motivation and Context
reduces size of a shallow clone or zip/tar.gz download by about 15 MB

## How Has This Been Tested?
compiled for OSX and iOS

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Montellese** [comment]
Should be ok. Did you check if these prebuilt files also come with the source tarball provided by Platinum? If so we should add a patch file for this commit as well like we do for all other changes to the libUPnP directory.

**Comment by Rechi** [comment]
@Montellese is https://github.com/plutinosoft/Platinum/releases upstream?
In the source code packages these prebuilt files are not present.

**Comment by Montellese** [comment]
Back in the days I downloaded it from https://sourceforge.net/projects/platinum/files/platinum/. Maybe they've moved over to github by now but we are currently on version 1.0.5.13 which is only available on sourceforge and not on github.

**Comment by MartijnKaijser** [comment]
So do we want to update libplatinum or move to the other one you worked on?

**Comment by Montellese** [comment]
If someone wants to take a shot at it, updating libplatinum is the prefered approach right now because I don't have time to work on the ohnet based UPnP implementation. With all our patches to libplatinum in neat patch files it shouldn't be too hard to update.

**Comment by Rechi** [comment]
superseded by 13244

**Pull request closed without merging**
