### PR TITLE
Add window InGameSaves

### PR DESCRIPTION
**Pull request by scott967**
## Description

Add windows GameSaves/InGameSaves/GamePorts/GameAgents to guilib/WindowIds.dox 

## Motivation and context

missing in doxygen documentation Separately logged as issue for tracking
https://github.com/xbmc/xbmc/issues/24033

## How has this been tested?

not tested

## What is the effect on users?

No user impact / developer only

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [X] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by garbear** [comment]
Are we missing any of these?

https://github.com/xbmc/xbmc/blob/master/xbmc/guilib/WindowIDs.h#L147-L158

**Comment by scott967** [comment]
OK did further review and force pushed updated commit.  Not sure how the changes should be documented, but these are the applicable PRs:

https://github.com/xbmc/xbmc/pull/20505 GamePorts v20
https://github.com/xbmc/xbmc/pull/20913 GameSaves/InGameSaves v20
https://github.com/xbmc/xbmc/pull/23548 GameAgents v21

I added these windows in WindowID order.  Not sure how to annotate the  PRs/impacted versions

**Comment by garbear** [comment]
@scott967 Thanks for bringing up in slack that some other game doxy was missing too. I'll send a PR and take care of these window IDs, as well as the new controls and features added in both v20 and v21.

**Comment by garbear** [comment]
Done: https://github.com/xbmc/xbmc/issues/24033

**Comment by scott967** [comment]
Superseded by https://github.com/xbmc/xbmc/pull/24055

**Pull request closed without merging**
