### PR TITLE
Silence a few warnings

### PR DESCRIPTION
**Pull request by hudokkow**

### CODE REVIEW

**Comment by hudokkow** [comment]
Arne's comments addressed (https://github.com/hudokkow/xbmc/commit/96e8e08160291f8483a6ab1ae3ab6db8534978c4 for reference).

Please review.

**Comment by hudokkow** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
Oké to go?

**Comment by hudokkow** [comment]
I think so. Your button.

**Pull request merged**
