### PR TITLE
[gui] fix window activation

### PR DESCRIPTION
**Pull request by xhaggi**
This introduces a new method `ForceActivateWindow()` in our window manager which could be used to force open a window because it skips the check for active modals. Furthermore I've used this method in different cases where we want to force activate a window e.g. fullscreen, screen calibration window (see commits)

This will fix #7022 and http://trac.kodi.tv/ticket/15960#comment:9

@Montellese @mkortstiege mind taking a look.

### CODE REVIEW

**Comment by afedchin** [comment]
this doesn't fix issue with stereo mode selection dialog. After video playback starts,  TMSG_SWITCHTOFULLSCREEN msg occurs which switchs to full screen without force flag.

**Comment by afedchin** [comment]
If I understand correctly here https://github.com/xhaggi/xbmc/blob/master/xbmc/ApplicationMessenger.cpp#L537 SwitchToFullScreen should be called with true.

**Comment by xhaggi** [comment]
@afedchin The call to `SwitchToFullScreen()` at https://github.com/xhaggi/xbmc/blob/fix-window-activation/xbmc/Application.cpp#L3226 in `CApplication::PlayFile()` will do the switch. There I added the force flag.

**Comment by xhaggi** [comment]
@afedchin you are right, if the player manage to switch to fullscreen the force flag should be added in app messenger as you pointed out. I've added a fixup for that.

**Comment by piejanssens** [comment]
@xhaggi Does this fix the live tv audio only issue? http://forum.kodi.tv/showthread.php?tid=226750

**Comment by afedchin** [comment]
@piejanssens I don think so.

**Comment by afedchin** [comment]
@xhaggi thanks. Now it works like a charm.

**Comment by Jalle19** [comment]
@xhaggi is this final? If so I think it's fine to merge.

**Comment by xhaggi** [comment]
fine for beta2. i will create a new PR to fix the rest of the issues related to the modal check.

build and merge

**Comment by xhaggi** [comment]
jenkins build and merge

**Comment by MartijnKaijser** [comment]
unrelated failure

**Pull request merged**
