### PR TITLE
[Vizualization] Fixed Vortex vizualization crash during window resize.

### PR DESCRIPTION
**Pull request by afedchin**
see title

@da-anda please check this.

### CODE REVIEW

**Comment by afedchin** [comment]
jenkins build this please

**Comment by da-anda** [comment]
do you already have a test build up somewhere? If not I'll ask jenkins later

**Comment by afedchin** [comment]
just ask jenkins for this

**Comment by afedchin** [comment]
jenkins build this please

**Comment by da-anda** [comment]
tested it and Kodi no longer crashes with Vortex. I noticed though that on every window resize the viz is being reset. Also some of the Vortex presets don't seem to work correctly. Looks like they don't get any audio data for processing (amplitudes are just flat lines). But those are different issues, unrelated to this bugfix.

**Comment by mkortstiege** [comment]
@Paxxi, @Montellese i guess this one is good to go? Would like to have it in next snapshot.

**Comment by Montellese** [comment]
A lot of odd / mismatching indentation throughout the changes but looking at the current state it's not much better.

**Comment by afedchin** [comment]
this is obsolete after #5329

**Comment by kfarhat** [comment]
Please stop emailing me

**Comment by da-anda** [comment]
@kfarhat - one last time. YOU (!!!!) created a github account and somehow subscribed to the XBMC repository. Because of that github(!!!!!) is sending you instant email notifications about the development that's going on in this repository. If you don't want to be notified by github about stuff that happens in the repositories you subscribed to, then a) either unsubscribe by visiting the github page of according repository and click the "unsubscribe" button in the right column or b) change the notification settings in your github account to your liking. And now STOP spamming us, because every useless comment/reply from you to the github notifications is spamming tons of devs that actually do care for these notifications, but only development related notifications and not your inability to disable mail notifications of github.
As this is your github account only YOU can disable these notifications, we can't!

**Pull request closed without merging**
