### PR TITLE
[texturepacker] Updated texturepacker to vs2015 and all libs with it, remove dependen…

### PR DESCRIPTION
**Pull request by Paxxi**
…cy on lzo in lib folder
This is the work needed for win32 for #9789

@stefansaraev @ace20022 @Montellese for review? Not entirely sure who's mostly responsible for texturepacker

### CODE REVIEW

**Comment by stefansaraev** [comment]
thanks much. I sent a PR to your branch. 

if kodi builds and can load a skin built with this new texturepacker win32 binary - all should be good.

**Comment by stefansaraev** [comment]
ping @Paxxi you said you forgot something ?

**Comment by Paxxi** [comment]
Yeah need to build a version of lzo for Kodi as well because of different build settings. Will try to get it done tonight

**Comment by Paxxi** [comment]
@stefansaraev uploaded new packages and triggered a testbuild so we should know later tonight if this works

**Comment by Paxxi** [comment]
test build here http://mirrors.kodi.tv/test-builds/win32/KodiSetup-20160530-8bf5868-texturepacker.exe
Seems to work fine in my short testing so things seem to be working

**Comment by stefansaraev** [comment]
all good then. push it when next merge window opens if jenkins is happy! :)

jenkins build this please

**Pull request merged**
