### PR TITLE
[win32] fix unit test environment

### PR DESCRIPTION
**Pull request by Montellese**
This fixes the unit test environment for win32. Right now it crashes on startup because it can't find `libmysql.dll` which is fixed in the first commit. Then it silently crashes because it can't resolve `special://temp/` because through `CServiceManager::Init2()` we try to load `cpluff.dll` before properly initializing `CSpecialProtocol`.

### CODE REVIEW

**Comment by Montellese** [comment]
@Paxxi: could you take a look at the changes to the VS project file?
@FernetMenta: anything speaking against moving the call to `CServiceManager::Init2()` further down? (PS: any chance we can find better names than `Init1`, `Init2` and `Init3`?)

**Comment by FernetMenta** [comment]
@Montellese those names are intermediate until all statics are trashed and we have control over the init process. If you could do this for settings, we would be one step closer to getting rid of those split init methods.

**Comment by FernetMenta** [comment]
> anything speaking against moving the call to CServiceManager::Init2() further down? 

not 100% sure. give it a try

**Comment by Montellese** [comment]
I tried and it works on win32 and the only code in between is ifdef'ed for win32 so other platforms shouldn't be affected anyway.

**Comment by FernetMenta** [comment]
> and the only code in between is ifdef'ed for win32

ahh, this answers the question why I didn't noticed this during my tests.

**Comment by Paxxi** [comment]
looks good :+1:

**Comment by Montellese** [comment]
jenkins build and merge

**Pull request merged**
