### PR TITLE
Implement ignore url options in CFileItemList

### PR DESCRIPTION
**Pull request by arnova**
- use in our directory-cache. There are other places that also use lookups for cfileitemlists which may also need to be updated (not sure though).

### CODE REVIEW

**Comment by arnova** [comment]
@ronie / @DaveTBlake / @MilhouseVH : Please test

jenkins build this please

**Comment by MilhouseVH** [comment]
Doesn't build.

```
FileItem.cpp: In member function 'bool CFileItem::IsPath(const string&) const':
FileItem.cpp:1542:55: error: 'm_ignoreURLOptions' was not declared in this scope
   return URIUtils::PathEquals(m_strPath, path, false, m_ignoreURLOptions);
                                                       ^
FileItem.cpp: In member function 'void CFileItemList::Remove(int)':
FileItem.cpp:1812:100: error: expected ':' before ')' token
       m_map.erase(m_ignoreURLOptions ? CURL(pItem->GetPath()).GetWithoutOptions(), pItem->GetPath());
                                                                                                    ^
FileItem.cpp:1812:100: error: expected primary-expression before ')' token
/home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi.arm-7.0-devel/kodi-17.0-alpha1-7ca3fea/Makefile.include:97: recipe for target 'FileItem.o' failed
make[2]: *** [FileItem.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by arnova** [comment]
@ronie / @DaveTBlake / @MilhouseVH : Sorry forgot to completely push all the changes. Please test (again).

jenkins build this please

**Comment by ronie** [comment]
works ok at my end.

**Comment by MilhouseVH** [comment]
Seems OK here with videos, music, YouTube. I'll include it in the next build, if you've got any concerns maybe wait a couple of days?

**Comment by DaveTBlake** [comment]
Looks OK with music so far, but Millhouse's suggestion of a pause for some more testing is a good one.

**Comment by arnova** [comment]
Yes sounds good since we're fiddling in a sensitive area.

**Comment by MilhouseVH** [comment]
I've had this in for the last 6-7 weeks weeks with no reported issues - is this ready to merge?

**Comment by DaveTBlake** [comment]
+1 here

**Pull request merged**
