### PR TITLE
Fixed typo in CCurlFile (acceptencoding)

### PR DESCRIPTION
**Pull request by liberty-developer**

### CODE REVIEW

**Comment by tamland** [comment]
this is a reimplementation of `SetContentEncoding`:) please rename it to SetAcceptEncoding instead

**Comment by FernetMenta** [comment]
@tamland do you seen any issue left?

**Comment by tamland** [comment]
..what I mean is, the `SetAcceptEncoding` that was added in #9234 already exist and the method is called `SetContentEncoding`. The implementation that was added also appears to be incomplete (see how m_contentencoding is used). Therefore, `SetAcceptEncoding` should be removed and the old `SetContentEncoding` renamed to something less confusing. The same confusion just popped up in #9237 as well.

**Comment by FernetMenta** [comment]
CURLOPT_ENCODING != CURLOPT_ACCEPT_ENCODING

**Comment by tamland** [comment]
afaik it's the same. check curl doc (cant post link atm)

**Comment by FernetMenta** [comment]
@you are right. CURLOPT_ACCEPT_ENCODING was called CURLOPT_ENCODING before 7.21.6:
https://curl.haxx.se/libcurl/c/CURLOPT_ACCEPT_ENCODING.html

**Comment by mapfau** [comment]
7.21.6 seems to be from year 2000 - I think we can:

- remove AcceptEncoding
- rename ContentEncoding -> AcceptEncoding
- keep "encoding" in protocolOptions  alive for backwards compatibility???

**Comment by mapfau** [comment]
Refactored in https://github.com/xbmc/xbmc/pull/9243

**Comment by FernetMenta** [comment]
thanks

**Pull request closed without merging**
