### PR TITLE
update SSL CA trust store

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Update bundled CA pem

## Motivation and context
Been ~ 10 months since the last. Has been a high profile expiration, so lets update.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by thexai** [comment]
This may be worth to backport as certificates are susceptible to expire in Matrix (in a one or two year) same as is happen now on Leia. At least needs to be updated in last 19.x version.

**Review by wsnipex — APPROVED** [review]

**Comment by wsnipex** [comment]
agreed, should be backported

**Comment by fuzzard** [comment]
Jenkins build and merge

**Comment by jjd-uk** [comment]
Just wondering, is it hoped that this may resolve the Lets Encrpyt certifcate expiry issue on the Xbox preventing connection to the addon repo? or is this totally unrelated???

**Comment by bkuhls** [comment]
> is it hoped that this may resolve the Lets Encrpyt certifcate expiry issue
I guess yes: https://github.com/xbmc/xbmc/pull/20230/files#diff-413cf44b16866191e3e078942fc44c7c8ff6adad0b66e1a0aced2be001e91f08L517

**Comment by thexai** [comment]
Yes, it is related, but this only updates the certificate in Matrix that has not yet expired.

Leia has a different certificate on another path (~3 years old now).

Backport, this only prevents the same from happening in the future, although it is not necessary right now, as the Matrix works fine on Xbox in dev. mode and I guess it will have the same behavior when it is published in the store (as it is now without touching).

**Comment by thexai** [comment]
Theoretically it should work but it has not been tested... there is some possibility that some other old component (I think OpenSSL) continues to give problems or is not fully compatible with the new certificates.

**Comment by fuzzard** [comment]
https://github.com/xbmc/xbmc/blob/0655c2c71821567e4c21c1c5a508a39ab72f0ef1/project/BuildDependencies/scripts/0_package.target-win10-x64.list#L32

The use of openssl 1.0.2 would be a problem

**Pull request merged**
