### PR TITLE
guilib: only update container after condition changed

### PR DESCRIPTION
**Pull request by FernetMenta**
fixes high CPU load caused by ever dirty controls

@Memphiz ping

### CODE REVIEW

**Comment by Memphiz** [comment]
Thx - isn't this worth to blackport to krypton? I could do that ...

**Comment by Memphiz** [comment]
I tested it and it's good to go - not sure but this is a bugfix and can go in right now with Jenkins approving?

**Comment by FernetMenta** [comment]
it is good to go for master. no idea about v17

**Comment by fritsch** [comment]
jenkins build and merge

**Pull request merged**
