### PR TITLE
Add support for ppc64le in ArchSetup.cmake

### PR DESCRIPTION
**Pull request by fitzsim**
## Description

This small patch is all that is needed for Kodi to be buildable and useable on GNU/Linux ppc64le.

## Motivation and context

The Kodi codebase is sufficiently portable that building on ppc64le just works, provided the CMake configury is aware of the architecture, so I think it makes sense to add it.

## How has this been tested?

I tested this change on Debian sid ppc64le, with the GCC toolchain version (Debian 11.2.0-16) 11.2.0.
I ran CMake like this:
cmake ../xbmc -DCORE_PLATFORM_NAME=x11 -DAPP_RENDER_SYSTEM=gl
Kodi built and ran fine.

## What is the effect on users?

Fewer debugging/hacking steps for people trying to build Kodi on ppc64le.

## Screenshots (if appropriate):

N/A

## Types of change

- [X] **Improvement** (non-breaking change which improves existing functionality)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 

- [X] My change requires a change to the documentation, either Doxygen or wiki

If this patch is accepted it probably makes sense to update this Wiki page:
https://kodi.wiki/view/Linux#Linux_distributions
and add a section "3.3 Debian ppc64le".

I didn't see a list of architectures to update in the official documentation, which makes sense given Kodi's portability.

- [X] I have updated the documentation accordingly

I guess for Wiki changes it makes sense to wait until the patch is accepted.

- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document

- [X] I have added tests to cover my change

I checked the Jenkins page and it seems like full CI coverage is not required for an architecture to be in ArchSetup.cmake (cf. riscv64).

- [X] All new and existing tests passed

I ran "make -j64 check" and got a 99% pass rate:

99% tests passed, 2 tests failed out of 601

Total Test time (real) = 185.91 sec

The following tests FAILED:
	573 - TestConvertMatrix.YUV2RGB (Failed)
	574 - TestConvertMatrix.ColorSpaceConversion (Failed)
Errors while running CTest

### CODE REVIEW

**Review by wsnipex — APPROVED** [review]
@basilgello are there any other patches for pp64le in debian?

**Comment by basilgello** [comment]
@wsnipex let me refresh my list for 19.4 :)

**Comment by wsnipex** [comment]
@fitzsim did you try to build for wayland and gbm as well? i.e. don't set CORE_PLATFORM_NAME

**Comment by fitzsim** [comment]
I just tried it.  Kodi built successfully when I don't specify CORE_PLATFORM_NAME, after I installed all the required dependencies from the Debian sid repositories.  I don't have a Wayland setup to try running it on right now.

I get the same "make check" result:

```
99% tests passed, 2 tests failed out of 601

Total Test time (real) = 194.06 sec

The following tests FAILED:
	573 - TestConvertMatrix.YUV2RGB (Failed)
	574 - TestConvertMatrix.ColorSpaceConversion (Failed)
Errors while running CTest
```

**Comment by wsnipex** [comment]
those 2 tests failing are a strong indicator that this needs more work

**Comment by basilgello** [comment]
These failing tests have nothing to do with this PR. See my related issue with @lrusak

**Comment by fitzsim** [comment]
Oh, this issue, interesting: "Failing color matrix conversion tests on Debian bookworm i686" #20250

**Review by basilgello — APPROVED** [review]

**Comment by fitzsim** [comment]
Thanks @wsnipex and @basilgello.  I don't have a kodi.wiki account yet; should I create one to update https://kodi.wiki/view/Linux#Requirements to mention ppc64le in the table (the GPU parts of the table apply equally to ppc64le as to x86-64, IME), and https://kodi.wiki/view/Linux#Linux_distributions to add Debian ppc64le?

**Comment by basilgello** [comment]
@fitzsim You can add the second page for sure, but for first I am in doubt. Kodi from Debian supports 7 architectures officially (amd64, arm64, armel, armhf, i386, ppc64le, s390x) also riscv64 and x32. I think Debian installation page I maintain currently covers the generic installation on Debian.

Can you also make a Matrix backport PR, too?

**Comment by fitzsim** [comment]
Done, #21268.  I hadn't seen the Debian kodi.wiki page; it covers everything already, so I won't make any wiki changes.

**Pull request merged**
