### PR TITLE
[music] added mood for songs

### PR DESCRIPTION
**Pull request by mkortstiege**
Quick hack job that extends the tagloader to read the mood field from ID3v2 and ASF tags. Testers wanted.

### CODE REVIEW

**Comment by zag2me** [comment]
Can someone trigger a windows build so I can test?

Mood should be a single field from a quick look at my music collection

**Comment by MartijnKaijser** [comment]
http://jenkins.kodi.tv/job/WIN-32/4269/

**Comment by zag2me** [comment]
Just to update our chat on IRC, this is now working nicely for MP3 extended tag "Mood" which I believe uses the TXXX:MOOD tag. Test song here:

http://www.theaudiodb.com/mpthreetest.mp3

**Comment by Montellese** [comment]
Can this somehow be combined with the moods we scrape for albums (not sure if also for artists?)?

**Comment by zag2me** [comment]
Not sure that is a good idea as Tracks may have a separate Mood to an album. Album moods are now single items on TADB so should be scraped successfully if you choose that as your scraper source. This PR is more about individual tracks.

**Comment by mkortstiege** [comment]
What @zag2me wrote. Combining those is not easy and will most likely create playlists that feel like "random" tracks.

**Comment by mkortstiege** [comment]
Rebased. jenkins build this please.

**Comment by mkortstiege** [comment]
Any objections?

**Comment by zag2me** [comment]
Fine for me +1

**Comment by mkortstiege** [comment]
@Montellese do you have an idea how to sync artist, album and song mood(s) without creating false positives?

**Comment by Montellese** [comment]
That was just a stupid idea of mine. I have no idea if the mood(s) of an album is/are the collection of the moods of the songs or only a subset etc. but from your comments it's certainly not an easy mapping.

Furthermore we currently store album and artist moods as a single concatenated string in the respective SQL tables. That's also one of the reasons why we can't really filter by moods because they are not properly implemented in the database using a `mood` and a `mood_link` table.

**Comment by mkortstiege** [comment]
I have no idea about mood(s) tagging as well. Just figured it would generate weird playlists due to the nature of album vs artist vs song. Not sure if a mapping would make it better or just adds another layer of complexity ;) Will check how other player software is handling it.

**Comment by mkortstiege** [comment]
Just checked banshee, rhytmbox and amarok. None of em is actually handling moods. I'd say merge as is.

**Comment by mkortstiege** [comment]
Will merge this after the easter weekend if no one objects.

**Pull request merged**
