### PR TITLE
add Samsung exynos to DRMUtils.cpp

### PR DESCRIPTION
**Pull request by chewitt**
## Description
Add Samsung `exynos` to the list of usable mesa DRM sources, and sort the list.

## Motivation and Context
Experiments with Panfrost as an alternative to closed-source Mali blobs on devices like the Odroid XU4 with an Exynos 5442 SoC. 

## How Has This Been Tested?
Tested with some experimental (partially working) mainline LE images for the XU4.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
The reason I didn't alphabetise this originally is because it was taken from here -> https://gitlab.freedesktop.org/mesa/drm/-/blob/master/tests/util/kms.c#L126-149

really we should just copy that entirely and leave it be so it can be compared easier.

**Comment by chewitt** [comment]
Rebased after #17935 and sorted as-per the upstream file with `vboxvideo` (which is not in the upstream file) appended to the end. I added `mediatek` in addition to `exynos` since their SoCs are media oriented. Others in the upstream list are embedded chips where AFAIK Kodi isn't going to be used, but if you'd prefer I simply copy the upstream list in its entirety let me know.

**Comment by kaidokert** [comment]
Hey, i asked in the other thread, but wouldn't it be better to do `drmGetDevices2()` ( or `drmGetDevices()` ) overall and then just open the card device with `open()` on the returned `drmDevicePtr->nodes` array ?

Then this list of pre-baked drivers wouldn't need maintenance.

**Comment by lrusak** [comment]
> Hey, i asked in the other thread, but wouldn't it be better to do `drmGetDevices2()` ( or `drmGetDevices()` ) overall and then just open the card device with `open()` on the returned `drmDevicePtr->nodes` array ?
> 
> Then this list of pre-baked drivers wouldn't need maintenance.

Yes this is probably the correct solution. I imagine at the time when I first implemented this all these methods weren't available in the libdrm that we required. They should be available in the libdrm version that we need now. I can implement using that later though.

**Review by lrusak — APPROVED** [review]

**Pull request merged**
