### PR TITLE
DVDVideoCodecAmlogic: remove pts-based frame rate tracking

### PR DESCRIPTION
**Pull request by kszaq**
In most cases frame tracking based on pts provided by amcodec is wrong, causing unnecessary frame rate switch. We can simply rely on frame rate provided by ffmpeg.

## How Has This Been Tested?
LibreELEC community builds with Kodi Krypton and Kodi master branch.
The incorrect behaviour without the patch applied can be reproduced with first samples from Kodi Wiki: http://kodi.wiki/view/Samples#Codecs.2C_Framerates_and_Subtitles

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by peak3d** [comment]
@kszaq first thanks for providing PR's to mainline, I'm surprised tbh. :-)

2 questions:

1.) How is framerate change detected inbetween a running stream.
2.) inputstream.adaptive is not relying on ffmpeg, but has sometimes wrong / no fps. How is this handled?

Is there a frame-rate tracker in kodi VP, @FernetMenta? If so, we can skip this AML implementation for sure....

**Comment by FernetMenta** [comment]
@peak3d VPV calculates framerate at the beginning of playback for a while.

**Comment by kszaq** [comment]
@peak3d Perhaps I am wrong about ffmpeg, the stream framerate is set based on hints: https://github.com/kszaq/xbmc/blob/b94ff22a00012a470e7e4ee3190b90ee49c30709/xbmc/cores/VideoPlayer/DVDCodecs/Video/AMLCodec.cpp#L1413-L1417
Inputstream.adaptive is working fine with this patch as reported by users. The only case that does not work are some PVR streams without framerate hint, in that case setting a fallback framerate for PVR in Kodi settings is needed.

**Comment by kszaq** [comment]
@peak3d Any suggestions about this PR? It has been included for some time in community Krypton and Leia builds and there have been no complaints so far - except that it fixes issue with some samples.

**Pull request closed without merging**
