### PR TITLE
spelling: member variables

### PR DESCRIPTION
**Pull request by jsoref**
## Description

Fix spelling for member variables

## How Has This Been Tested?
- [ ] Travis
- [ ] AppVeyor

## Types of change
- [x] Spelling

## Checklist:
- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document

### CODE REVIEW

**Review by Paxxi — CHANGES_REQUESTED** [review]
The enum definition in SlideShowPicture.h isn't renamed so this won't work

**Comment by jsoref** [comment]
Sigh, it's hard to try to parallelize a series. This will just have to wait for #11373 -- once that's in, I'll submit a version closer to the one in the original series.

**Comment by Paxxi** [comment]
#11373 is merged

**Comment by jsoref** [comment]
split #11465 out to cover what got lost between all the interdependencies

**Comment by jsoref** [comment]
@Paxxi: ping

**Comment by MartijnKaijser** [comment]
Jenkins build this please

**Comment by FernetMenta** [comment]
those kind of cosmetics should be split into multiple commits

**Comment by Paxxi** [comment]
Osx failure seem unrelated but let's try again 
jenkins build this please

**Comment by MartijnKaijser** [comment]
To go further with this is the request one commit per variable change?

**Comment by FernetMenta** [comment]
one per maintained component

**Comment by jsoref** [comment]
@FernetMenta: As someone who has done this for a number of projects (probably dozens), you should keep in mind that you're probably asking too much of contributors. Especially if it's non-trivial to identify "maintained components". Thus, the only reasonable way to get what you want would be for someone from your organization to take the responsibility of splitting such PRs appropriately upon receipt.

For an example of this, see the work by @violetagg for apache/tomcat#37 and
https://github.com/apache/tomcat/commits/7d4d318b9d19e11136c2337cd2574d9a1551d92c.

It might be worth considering that the tomcat PR was of similar scale to the xmbc PR. They handled the whole thing in about a day. They didn't even force me to deal w/ the deprecation, they just dropped those bits and took what they wanted. They did make it clear that a PR for deprecation would be taken, and I made one, and they took it.

Compare that w/ #11346 and following, which is now approaching a month. Now, as it happened, I did specify that I'd split it as long as someone specified a split. But, you really only get one chance. Telling me to resplit it is not a good strategy.

Given a choice of contributing to tomcat vs. xbmc, I'd be much more inclined to contribute to tomcat.

Note: I sometimes revisit projects (e.g. I sent spelling round 2 to letsencrypt/certbot recently, because they grew new spelling errors since my original fixes were accepted). But, projects that make it painful for me to contribute are much less likely to receive return business.

**Comment by Paxxi** [comment]
Agreed, we can't expect first time/drive by contributors to follow some pretty standard that we haven't even documented. @jsoref was asked to split his initial PR which he did, asking for even more arbitrary work is a surefire way to scare people away. 

@jsoref reason I've been quiet is that I haven't made sure the build error is unrelated to the changes here, want the contributions but wouldn't want to break the build 😀

**Comment by Paxxi** [comment]
Well jenkins seems happy, good enough for me

**Pull request merged**
