### PR TITLE
[Cmake] fix dav1d ENABLE_INTERNAL build

### LINKED ISSUE #23743: CMake, Build: -DENABLE_INTERNAL_DAV1D=ON causes configuration error
### Describe the bug

Here is a clear and concise description of what the problem is:
When configuring kodi with the argument -DENABLE_INTERNAL_DAV1D=ON, errors occur.

I suspect that the target "dav1d" is defined twice. Once by "cmake/scripts/common/Macros.cmake:376 (find_package)" and once by "cmake/modules/FindFFMPEG.cmake:34 (find_package)". I have output two messages in the "FindDav1d.cmake", one contains a trace message-type.

The log can be seen in the following.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should build with internal libdav1d

## Actual Behavior

it is not possible to build with -DENABLE_INTERNAL_DAV1D=ON.

### To Reproduce

1.  I used following command:
 ```
$cmake ../xbmc/ -DCMAKE_INSTALL_PREFIX=/usr/local -DCORE_PLATFORM_NAME=gbm -DAPP_RENDER_SYSTEM=gles -DENABLE_INTERNAL_FFMPEG=ON -DENABLE_INTERNAL_DAV1D=ON
``` 
3.
4.

### Debuglog

The debuglog can be found here:
[cmake-dav1d-error.txt](https://github.com/xbmc/xbmc/files/12567955/cmake-dav1d-error.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: current alpha3 and master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Fixes building with internal dav1d
Fixes building for ffmpeg using < cmake 3.19

## Motivation and context
Fixes #23743
Fixes building for ffmpeg using < cmake 3.19

## What is the effect on users?
Building

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by howie-f** [comment]
> @howie-f your issue should be fixed in https://github.com/xbmc/xbmc/pull/23746

unfortunately this happens :(
https://paste.kodi.tv/bipemugahu

**Comment by howie-f** [comment]
though with CMake Version: 3.25.1 this pr is fine

**Comment by fuzzard** [comment]
Have updated again. The reason it works in 3.25 is that the whitelist on INTERFACE isnt enforced in cmake 3.19+. The folder property is only a visual thing in IDE's, so ive just removed it from all the INTERFACE based targets now.

**Comment by howie-f** [comment]
i'll try, ty

**Comment by howie-f** [comment]
ffmpeg issue resolved with cmake version 3.18.4
cmake version 3.25.1 still fails on install, please see the updated comment above
```
-- Installing: /home/fhw/.tmp/.kodi-root21/opt/omega/share/kodi/cmake/CheckTargetPlatform.cmake
CMake Error at cmake_install.cmake:25061 (file):
  file INSTALL cannot find
  "/home/fhw/xbmc/cmake/scripts/common/GenerateVersionedFiles.cmake": No such
  file or directory.


```

**Comment by howie-f** [comment]
> cmake version 3.25.1 still fails on install

fixed by https://github.com/fuzzard/xbmc/commit/3b5abdbea5fdd731b6a0f82da59b7ab58b1c4d39

**Review by wsnipex — APPROVED** [review]

**Pull request merged**
