### PR TITLE
[wayland] Support xdg_shell stable

### PR DESCRIPTION
**Pull request by yol**
## Description
Besides wl_shell and zxdg_unstable_v6, also support xdg_wm_base, which is the new recommended desktop shell extension for Wayland

## Motivation and Context
wl_shell is effectively deprecated now and zxdg_unstable_v6 was always unstable, as the name indicates. xdg_shell has been stabilized as xdg_wm_base, so we should use it if possible

## How Has This Been Tested?
Fallback to old behavior verified with mutter. xdg_wm_base itself could not be checked due to missing compositor support at the moment, but as code and behavior are equivalent to xdg_shell unstable v6 there should be no major problems.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by pkerling** [comment]
@wsnipex Can you check whether you agree with ef10c7b? Rest here should be rather uninteresting.

**Review by wsnipex — APPROVED** [review]

**Review by Rechi — DISMISSED** [review]
waylandpp has to be bumped in depends

**Comment by pkerling** [comment]
@rechi thx should be fixed

**Comment by pkerling** [comment]
Build error pending on NilsBrause/waylandpp#43

**Comment by pkerling** [comment]
😢 NilsBrause/waylandpp#44

**Comment by pkerling** [comment]
@Rechi failures unrelated. good to merge?

**Review by Rechi — COMMENTED** [review]
Yes, depends versions are now updated

**Comment by NilsBrause** [comment]
@pkerling Why are you using xdg-shell from wayland-protocols? Waylandpp comes with xdg-shell, too and has important enumeration fixes included.

**Comment by pkerling** [comment]
> Why are you using xdg-shell from wayland-protocols? Waylandpp comes with xdg-shell, too and has important enumeration fixes included.

I disagree about making `xdg_toplevel_resize_edge` a bitfield since only part of the combinations make sense (which are explicitly spelt out). Also, it's not relevant for the code here anyway since we're casting from `wl_shell_surface_resize`.

**Comment by NilsBrause** [comment]
> I disagree about making xdg_toplevel_resize_edge a bitfield since only part of the combinations make sense (which are explicitly spelt out).
The only property of a bitfield is that every single bit hat a distinct meaning, which is the case here (bit 0 = top, bit 1 = bottom, bit 2 = left, bit 3 = right). It is not necessary that all combinations are useful. A common misunderstanding. :)

**Comment by pkerling** [comment]
I know. To clarify: I'm worried about the mix of bits that have distinct meaning (left, top, ...) and the values that are already combinations (top_left etc.) which makes it seem unnatural to me to label it as bitfield here, notwithstanding the forbidden combinations. Without knowing the details I'd wonder whether `top_left` is a distinct bit or not. I'd say either make it an enum (which it is in wayland-protocols) or throw out the values that are combinations. Personally I just don't see a strong reason to digress from the "official" protocol here. The two `enum` additions to requests are fine of course.
Tbh when I wrote this there was no xdg-shell in waylandpp and to me there's absolutely no benefit in changing to it now. If you want you can make a PR, I won't object.

**Pull request merged**
