### PR TITLE
[addons] add thumb support for info provider group

### PR DESCRIPTION
**Pull request by tamland**

### CODE REVIEW

**Comment by tamland** [comment]
@uNiversaI Thanks. I didn't think of that one. I've renamed `DefaultAddonInfoLibrary.png` (alternatively we could reuse the name instead). We could probably remove the other hidden ones too, if they aren't used for anything else.

**Comment by uNiversaI** [comment]
Makes sense, if aren't seen, may as well delete the unused files and remove the unused entries.
Idk if additionally makes any sense to make a note on the ones that aren't visible.

:smile:

**Comment by ronie** [comment]
nice, i was missing that one indeed.

**Comment by tamland** [comment]
jenkins build and merge

**Pull request merged**
