### PR TITLE
remove unused private fields

### PR DESCRIPTION
**Pull request by tamland**
silence some compiler warnings

### CODE REVIEW

**Comment by tamland** [comment]
jenkins build this please

**Comment by fritsch** [comment]
@AchimTuran please have a look

**Comment by tamland** [comment]
I'm pretty sure it's just copy-paste leftovers, but nudge @AchimTuran

**Comment by AchimTuran** [comment]
@fritsch @tamland 
I don't know why, but I missed your pings sorry.

**Pull request merged**
