### PR TITLE
[macOS] fall back to legacy OpenGL profile on NSOpenGLContext creation error

### LINKED ISSUE #24811: [macOS][regression] Omega crashes on old iGPU
### Describe the bug
Omega crashes on start on an old MBP with iGPU active, Nexus works fine.

## Expected Behavior
No crash

## Actual Behavior
Crash on start

## Possible Fix
As I see, in Nexus we use different set of OpenGL attributes: https://github.com/xbmc/xbmc/blob/Nexus/xbmc/windowing/osx/SDL/WinSystemOSXSDL.mm#L1250 vs https://github.com/xbmc/xbmc/blob/master/xbmc/windowing/osx/OpenGL/OSXGLView.mm#L36

### To Reproduce
Run Omega on an old iGPU

### Debuglog
OpenGL info from Nexus debuglog:

```
2024-03-06 17:13:31.356 T:79605    info <general>: CRenderSystemGL::InitRenderSystem - Version: 2.1 INTEL-10.4.14, Major: 2, Minor: 1
2024-03-06 17:13:31.356 T:79605    info <general>: GL_VENDOR = Intel Inc.
2024-03-06 17:13:31.356 T:79605    info <general>: GL_RENDERER = Intel HD Graphics OpenGL Engine
2024-03-06 17:13:31.357 T:79605    info <general>: GL_VERSION = 2.1 INTEL-10.4.14
2024-03-06 17:13:31.357 T:79605    info <general>: GL_SHADING_LANGUAGE_VERSION = 1.20
2024-03-06 17:13:31.357 T:79605    info <general>: GL_EXTENSIONS = GL_ARB_color_buffer_float GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_elements_base_vertex GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_shader_objects GL_ARB_shading_language_100 GL_ARB_shadow GL_ARB_sync GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_mirrored_repeat GL_ARB_texture_non_power_of_two GL_ARB_texture_rectangle GL_ARB_transpose_matrix GL_ARB_vertex_array_bgra GL_ARB_vertex_blend GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_window_pos GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_clip_volume_hint GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_draw_buffers2 GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_EXT_texture_rectangle GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_APPLE_aux_depth_stencil GL_APPLE_client_storage GL_APPLE_element_array GL_APPLE_fence GL_APPLE_float_pixels GL_APPLE_flush_buffer_range GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_packed_pixels GL_APPLE_pixel_buffer GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_specular_vector GL_APPLE_texture_range GL_APPLE_transform_hint GL_APPLE_vertex_array_object GL_APPLE_vertex_array_range GL_APPLE_vertex_point_size GL_APPLE_vertex_program_evaluators GL_APPLE_ycbcr_422 GL_ATI_separate_stencil GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_IBM_rasterpos_clip GL_NV_blend_square GL_NV_conditional_render GL_NV_depth_clamp GL_NV_fog_distance GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_barrier GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod 
2024-03-06 17:13:31.373 T:79605   error <general>: CYUVShaderGLSL::CYUVShaderGLSL - failed to open file gl_shader_frag_texture_lim.glsl
2024-03-06 17:13:31.376 T:79605    info <general>: GL: No pixel shader, fixed pipeline in use
2024-03-06 17:13:32.231 T:79605   error <general>: CYUVShaderGLSL::CYUVShaderGLSL - failed to open file gl_shader_frag_texture_lim.glsl
2024-03-06 17:13:32.233 T:79605    info <general>: GL: No pixel shader, fixed pipeline in use
2024-03-06 17:13:32.254 T:79605    info <general>: GL: Maximum texture width: 8192
2024-03-06 17:13:32.295 T:79605   error <general>: CYUVShaderGLSL::CYUVShaderGLSL - failed to open file gl_shader_frag_texture_lim.glsl
2024-03-06 17:13:32.297 T:79605    info <general>: GL: No pixel shader, fixed pipeline in use
2024-03-06 17:13:32.319 T:79605    info <general>: GL: Maximum texture width: 8192
2024-03-06 17:13:32.472 T:79605    info <general>: GL: Enabling VSYNC
```

### Screenshots 
Video info of my MBP from Nexus: 

Screenshot 2024-03-06 at 17 14 20

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS Ventura via OCLP
 - Kodi version: Omega nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by kambala-decapitator**
## Description

adjusts one attribute when creating `NSOpenGLContext`

## Motivation and context

fixes #24811 - now post-Nexus is usable on old iGPUs again

## How has this been tested?

launched Kodi on my MBP 2010 that's driven by iGPU running Ventura via OCLP

## What is the effect on users?

users with ancient Macs on iGPU can use post-Nexus

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by enen92 — APPROVED** [review]
Thank you! Btw I assume for the GPU the temperatures are also wrong right? Might need to add that to smctemp too

**Comment by kambala-decapitator** [comment]
> btw I assume for the GPU the temperatures are also wrong right?

yeah

**Comment by enen92** [comment]
Note for the future: Please do not merge stuff without jenkins finishing the build

**Comment by kambala-decapitator** [comment]
> Note for the future: Please do not merge stuff without jenkins finishing the build

hmm, but it was green already? https://jenkins.kodi.tv/job/BuildMulti-PR/29551/

**Comment by enen92** [comment]
Maybe some issue with GitHub, for some reason it was still showing as running. Disregard

**Pull request merged**
