### PR TITLE
Add alpha release

### PR DESCRIPTION
**Pull request by razzeee**
## Description

Added the alpha release, with correct tags

## Motivation and context

I think this would be good for the workflow and this will also allow me to test some things on the new flathub website.

## How has this been tested?

Hasn't been, but is according to spec.

## What is the effect on users?

Correct version numbers in some tools.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by DaveTBlake** [comment]
Can you clarify how 19.5 should be added to this: are entries in date order, version order or does it not matter?

**Comment by razzeee** [comment]
Latest to oldest according to the spec https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-releases

**Comment by fuzzard** [comment]
out of curiosity, long term, do we want to be putting in stable version (eg Matrix currently) release info into master branch?
or essentially, what happens when the next 19 point release occurs, does it get added to master, or only matrix, and if it goes into master, does it get placed before/after the Nexus entries?

**Comment by DaveTBlake** [comment]
> or essentially, what happens when the next 19 point release occurs,

That is what I asked already :)

**Comment by razzeee** [comment]
I think, whatever your releasing should be the top most entry at release
time.

Dave Blake ***@***.***> schrieb am So., 22. Mai 2022, 08:57:

**Pull request merged**
