### PR TITLE
[EPG] Timeline view: Fix 'GoToNow' to select the currently active epg event of selected channel

### PR DESCRIPTION
**Pull request by ksooo**
Reported by @kib and @MartijnKaijser.

@Jalle19 @xhaggi mind taking a look.
@MartijnKaijser backport needed?

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Not necessarily for me as we should keep backporting to minimum. Open for good arguments of course :)
jenkins build this please

**Comment by ksooo** [comment]
Not having this in Jarvis is fine by me. It's more a glitch than a bug, imo.

**Comment by puithove** [comment]
I saw this commit and believe it fixes an annoyance I've been seeing, and my wife has been "bug"ging me about.  The grid being displayed at a random timeslot on random channel instead of current time.  In that way I'd call it a "bug" :)  It would be nice to have this in the Jarvis branch if not for initial release, at least for .1

**Comment by puithove** [comment]
Any reason why this couldn't be added to 16.1?

**Pull request merged**
