### PR TITLE
Bump libnfs to version 1.10.0

### PR DESCRIPTION
**Pull request by razzeee**
Tries to bump libnfs to the latest version ~~1.9.8.~~ 1.10.0

The new file for windows still needs to be uploaded to our mirrors.
But compiles fine in my tests, I couldn't test nfs itself as my network doesn't seem to do that. So we will need massive tests on all plattforms for this.

I have no clue what else is needed for linux, but @stefansaraev might know
I'm also not sure how sane that is for raspberry pi toolchain @popcornmix might know

In any case, waiting for guidance of @Memphiz (and @MartijnKaijser to upload the 7zip)

### CODE REVIEW

**Comment by MilhouseVH** [comment]
libnfs 1.10.0 just got released in the last few minutes... I've been using what is now 1.10.0 in my OpenELEC builds for a while now (as I always build with the latest libnfs master).

**Comment by Razzeee** [comment]
It's not tagged on github, but I see the commit :/

**Comment by Razzeee** [comment]
Small but important detail the windows version is built with vs2015 thanks to @paxxi work

**Comment by Memphiz** [comment]
thx - i think tools/rbp/depends is nowhere used is it? @popcornmix 

Also i can upload stuff to the platformdeps this evening - just need the links ;)

**Comment by Memphiz** [comment]
till now i was compiling libnfs for windows from my repo which had the vs solution (which is not there in upstream because nobody would maintain it) - how did you do it @Razzeee ?

**Comment by Razzeee** [comment]
Check the fork @paxxi did. I checked out the 1.9.8 tag and cherry picked paxxis commit from his master.

**Comment by Razzeee** [comment]
@Memphiz https://www.dropbox.com/s/3pdxqitvapz9t45/libnfs-1.9.8-win32.7z?dl=0

**Comment by Paxxi** [comment]
@memphiz your project files are accepted in upstream, just cloned it and made some minor changes to have it build

**Comment by popcornmix** [comment]
I believe tools/rbp/depends is not used. I (and Jenkins) build with unified build system which doesn't  use that.

**Comment by MartijnKaijser** [comment]
file uploaded to mirror

**Comment by Razzeee** [comment]
Should that folder go then or is there another usecase? @popcornmix @Memphiz

**Comment by Memphiz** [comment]
Folder can be nuked imo ...

sorry - didn't realise sahlberg had vs support in its tree now - fine then :) - @Razzeee i think the source tarball needs still to be uploaded to the mirrors right?

**Comment by Memphiz** [comment]
source tarball uploaded ... needs to sync a bit i guess...

**Comment by Memphiz** [comment]
won't compile on osx btw ... 

http://pastebin.com/nXYvfNXp

already asked sahlberg where that m4 directory comes from ...

**Comment by stefansaraev** [comment]
it's not uncommon for packages to have autoreconf broken.

this is what I did for openelec as an "universal" fix. just do it before ./bootstrap

```
touch NEWS AUTHORS ChangeLog
mkdir -p m4
```

**Comment by Memphiz** [comment]
nfs-cp doesn't compile either on osx ... and the option to compile utils optionally doesn't seem to be in 1.9.8 ...

**Comment by Memphiz** [comment]
Well this nfs version doesn't fly ... i have posted 2 issues to upstream github ... we can circumvent the m4 issue - but for the nfs-cp issue we really should update to a more recent tarball which has the -disable-utils configure option ...

**Comment by Razzeee** [comment]
So it's there hope that 1.10 solves that? If it has been tagged yet.

**Comment by stefansaraev** [comment]
http://sprunge.us/JPdE this is all kodi needs..

**Comment by Razzeee** [comment]
Just to be clear, ```xbmc\tools\rbp``` can go completely?

**Comment by popcornmix** [comment]
tools/rbp is not something I use.
If no one speaks up and says they care, then I don't mind it being removed.

**Comment by Memphiz** [comment]
noone from us will speak up because noone even recognized it was there *hehe*- @Razzeee go for it if you have the mood and time ;)

**Comment by wsnipex** [comment]
xbmc\tools\rbp is the original buildroot way to build kodi on rpi. It might be used by some embedded distros out there... no idea if we still should support that, since we never test it.

**Comment by Razzeee** [comment]
1.10.0 has been tagged, will update this ASAP

**Comment by Razzeee** [comment]
Here's the 7z, would be nice if someone could upload that. I will then update this PR. But we might have to wait for the next version anyway, if this doesn't fix the osx problems.
Would also be nice to get #9029 merged first.
https://www.dropbox.com/s/n01xe1tuqkdy1z6/libnfs-1.10.0-win32.7z?dl=0

**Comment by Memphiz** [comment]
7z uploaded ... will try 1.10 on osx in a min ...

**Comment by Memphiz** [comment]
1.10.0 compiles fine on osx without further modification ... - but it looks like android was broken for a long time.

Please pick this:

https://github.com/Memphiz/xbmc/commit/64abf1c482fdc57b9f0c0135db8ea7c4ea022e6c

I can't do a PR to your repo ...

**Comment by Razzeee** [comment]
Rebased and picked your commit @Memphiz 
Also updated windows to 1.10.0

Do you have any clue why you can't PR to my repo?

Let's see if it flies.
jenkins build this please

**Comment by Memphiz** [comment]
no idea - your repo simply isn't in the list of possible targets for pull requests...

**Comment by Razzeee** [comment]
@Memphiz 
only the IOS build failed, can you have a look?

**Comment by Memphiz** [comment]
looks like a download error - kicked another testbuild only for ios

**Comment by Razzeee** [comment]
Seems like the build was fine.
So what are we going to do? Merge it, do some more tests or include it in testbuilds?

**Comment by Memphiz** [comment]
Do we have some testing done via openelec with those recent libnfs versions?

**Comment by popcornmix** [comment]
Milhouse builds always use latest libnfs, which recently will have matched 1.10.0.

**Comment by Memphiz** [comment]
thx @Razzeee

**Pull request merged**
