### PR TITLE
maybe fix android crash after #10335

### PR DESCRIPTION
**Pull request by tamland**
untested..

### CODE REVIEW

**Comment by bkuhls** [comment]
Thanks! I can confirm that this patch applied on top of e36734747739f52df6c9efe012253484ff163de0 fixes the segfault I reported in https://github.com/xbmc/xbmc/pull/10335#issuecomment-247637674

**Comment by MartijnKaijser** [comment]
will test on android
jenkins build this please

**Comment by koying** [comment]
@tamland You could keep it static and load on first ctor only if empty...
That'll avoid the member var.

**Comment by tamland** [comment]
But I have no need to avoid it.. Having it as member is fine; and I get constness. I was just being lazy with the original code

**Comment by MartijnKaijser** [comment]
@tamland tested on Android and works

**Comment by mazeyx** [comment]
awesome thanks guys. :)

**Comment by MartijnKaijser** [comment]
objections?

**Pull request merged**
