### PR TITLE
redact AV.xml contents in logfile (fixes #18974)

### LINKED ISSUE #18974: Path Substitution is not filtered in advancedsettings.xml
### Describe the bug
Path Substution in advancedsettings.xml is not filtered. So if you transfer a log or debuglog the password will be visible.

## Expected Behavior
- User and Password is filtered and shown as ****

## Actual Behavior
- User and Password is visible.

## Possible Fix
your part :)

### To Reproduce
Just add an smb pathsubstitution to advancedsettings.xml with user and password

### Debuglog
The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/5733446/kodi.log)

### Screenshots
Here are some links or screenshots to help explain the problem:
-nothing to see here -

## Additional context or screenshots (if appropriate)
-none-

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 - 20H2 
 - Kodi version: (19.0-BETA2 (18.9.821) Git:20201215-30abc954c7) (but is same on all versions i know before)

### PR DESCRIPTION
**Pull request by wsnipex**
## Description

Contents in advancedsettings.xml is not redacted in kodi.log

## Motivation and Context

https://github.com/xbmc/xbmc/issues/18974

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by codywalker77 — APPROVED** [review]

**Comment by wsnipex** [comment]
windows errror unrelated, looks like a jenkins issue with creating the installer, but it built fine

**Comment by joseluismarti** [comment]
It works when parses the AV.xml

```
2021-01-10 21:44:27.377 T:9262     INFO <general>: Contents of special://profile/advancedsettings.xml are...
                                                   <to>smb://USERNAME:PASSWORD@192.168.1.2/kodi_thumbs/</to>
```

But prints a DEBUG message with the original URL when configures the path substitution.

```
2021-01-10 21:44:27.377 T:9262    DEBUG <general>:   Registering substitution pair:
2021-01-10 21:44:27.377 T:9262    DEBUG <general>:     From: [/home/user/.kodi/userdata/Thumbnails/]
2021-01-10 21:44:27.377 T:9262    DEBUG <general>:     To:   [smb://user:pass@192.168.1.2/kodi_thumbs/]
```

Problem: Kodi starts in log level DEBUG and always will show this messages. See the next log messages:

```
2021-01-10 21:44:27.377 T:9262     INFO <general>: Disabled debug logging due to GUI setting. Level 0.
2021-01-10 21:44:27.377 T:9262     INFO <general>: Log level changed to "INFO"
```

I propose changing the log level from LOGDEBUG to LOGINFO in AdvancedSettings.cpp (4 calls) and apply the regex when configures the path substitution.

**Comment by wsnipex** [comment]
updated to redact the substitution pairs as well

**Comment by joseluismarti** [comment]
It works fine

**Pull request merged**
