### PR TITLE
[pvr] fix segfault when changing channels via json-rpc

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
@MartijnKaijser you may want to backport this to Helix

**Comment by MartijnKaijser** [comment]
14.1 was the last Helix version

**Comment by Jalle19** [comment]
There's also a bug reporr saying that playback just stops when this is used with non-demuxing addons.

**Comment by mkortstiege** [comment]
jenkins error is unrelated.

**Comment by FernetMenta** [comment]
instead of reverting the old change I changed it to use correct method

**Comment by FernetMenta** [comment]
jenkins build this please

**Pull request merged**
