### PR TITLE
[Regex] Make first char before ep optional for single episodes

### LINKED ISSUE #18505: Files with names starting with "epXX" not recognized as episodes.
### Describe the bug

Default `m_tvshowEnumRegExps` does not match episodes starting with `ep01 [...]`.

https://kodi.wiki/view/Naming_video_files/TV_shows#Single_Episodes suggests that this is NOT intended.

code: https://github.com/xbmc/xbmc/blob/ddcbadf2c0f631cddd58ea36d926beebc27dc363/xbmc/settings/AdvancedSettings.cpp#L235

## Expected Behavior

It should match.

## Actual Behavior

It doesn't match.

## Possible Fix

1. Make the first character class an optional.
2. Have the first character class match beginning-of-string as well.

### To Reproduce

1. Name an episode `ep01 - title.mkv` => doesn't match.
2. Name an episode ` ep01 - title.mkv` (ASCII space before the `e`) =>  matches.

### PR DESCRIPTION
**Pull request by enen92**
## Description
The wiki states for the regex for single episodes (https://kodi.wiki/view/Naming_video_files/TV_shows#Single_Episodes):

Spaces, periods, or underscores **may be used to separate words in the folder and file names** although the regex makes the space, period or underscore at the start of the filename mandatory. This means:

Name an episode "ep01 - title.mkv" => doesn't match.
Name an episode " ep01 - title.mkv" (ASCII space before the e) => matches.

This PR makes the first character optional so that both entries match.

@eduarrrd please test to confirm it's working now.

## Motivation and Context
Fix https://github.com/xbmc/xbmc/issues/18505

## How Has This Been Tested?
Untested in runtime. Used https://regex101.com/ to confirm the regex works in both cases

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by KarellenX** [comment]
If you kick off a build I can quickly test this.

**Comment by DaveTBlake** [comment]
Win64 test build here http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20201007-d22999b4-PR18513-merge-x64.exe @KarellenX

**Comment by KarellenX** [comment]
Thanks. Got it.

**Comment by KarellenX** [comment]
This build crashes on second start.

```
2020-10-08 20:01:06.097 T:11360   DEBUG <general>: CDatabaseManager::Initialize, updating databases...
2020-10-08 20:01:06.103 T:11360    INFO <general>: Running database version Addons33
2020-10-08 20:01:06.104 T:11360    INFO <general>: Running database version ViewModes6
2020-10-08 20:01:06.104 T:11360    INFO <general>: Running database version Textures13
2020-10-08 20:01:06.106 T:11360    INFO <general>: Running database version MyMusic81
2020-10-08 20:01:06.107 T:11360    INFO <general>: Running database version MyVideos119
2020-10-08 20:01:06.108 T:11360   ERROR <general>: SQL: [TV37.db] SQLite error SQLITE_ERROR (no such table: version)
                                                   Query: SELECT idVersion FROM version
```

**Comment by popcornmix** [comment]
@KarellenX See https://github.com/xbmc/xbmc/pull/18542

**Comment by KarellenX** [comment]
Thanks @popcornmix

**Comment by enen92** [comment]
Jenkins build this please

**Comment by enen92** [comment]
@KarellenX @DaVukovic can you find some time to review or test this?

**Comment by KarellenX** [comment]
Yep, just waiting for a new test build. The previous one crashed Kodi.

**Comment by enen92** [comment]
Building here: https://jenkins.kodi.tv/view/Automation/job/BuildMulti-PR-Manually/390/

**Review by KarellenX — COMMENTED** [review]
@enen92 Thanks I have tested the build.

I named my files as follows...

```
ep05 The Boys (2019)
ep06.The.Boys.(2019)
ep7 The Boys (2019)
ep08 - The Boys (2019)
The Boys (2019) - ep04
The Boys (2019) ep01
The Boys (2019) ep2
The.Boys.(2019).ep03
```

All were successfully scraped. Line 1170 onwards... https://paste.kodi.tv/suliviboho.kodi

On another note, this build is buggy and kept hanging. No clean exits, scrapers hung requiring killing Kodi, but nothing revealing in the log.

The above log hung on exit for approx 8 minutes. Don't know if you can pick something out of it.

**Review by KarellenX — APPROVED** [review]

**Pull request merged**
