### PR TITLE
[fix][Take II] Nuke 'libpng warning: iCCP: known incorrect sRGB profile' warnings and optimize images

### PR DESCRIPTION
**Pull request by hudokkow**
Take II of https://github.com/xbmc/xbmc/pull/12200 (see comments)

ping @ksooo, @Montellese, @Memphiz, @MilhouseVH to test PVR. I can't test atm.

@phil65, @ronie, do you want the changes here (assuming everything is OK) or in estuary/estouchy repos?

### CODE REVIEW

**Comment by MilhouseVH** [comment]
I've only done a quick test with the "error" icon and that is now red, as it should be, so that's a good sign. I'll include this PR in tonight's test build (RPi/x86).

**Comment by hudokkow** [comment]
Thx!

**Comment by ronie** [comment]
i'm fine with merging to master. thx!

**Comment by hudokkow** [comment]
Thx! I'll wait for @MilhouseVH's report/test drive.

**Comment by MartijnKaijser** [comment]
good to merge. Should it be squashed or left as it?

**Comment by hudokkow** [comment]
As it is please. If any problems arise I/we can always revert/rework the offending commit without reverting everything.

**Pull request merged**
