### PR TITLE
[guilib] fadelabel not reading scroll tag

### PR DESCRIPTION
**Pull request by mkortstiege**
Make fadelabels read the scroll tag. Report @ http://forum.kodi.tv/showthread.php?tid=224545

### CODE REVIEW

**Comment by mkortstiege** [comment]
jenkins build this please.

**Comment by ronie** [comment]
please no more skin changes, this was labelled J*.

**Comment by ronie** [comment]
@MartijnKaijser please revert.

1) this breaks all fadelabels in current skins (they stopped scrolling).
2) this is an api change (it introduces a new ```<scroll>``` tag)

**Comment by tamland** [comment]
Also adds new python method. api version should be bumped.

**Pull request merged**
