### PR TITLE
native resolution ( disable upscaling ) 

### PR DESCRIPTION
**Pull request by ghost**
http://forum.kodi.tv/showthread.php?tid=64139

X-dark had upgraded the code to Kodi and I have changed it to support the different configurations in GUI.

Thanks to adam-aph and X-dark

### CODE REVIEW

**Comment by FernetMenta** [comment]
Allowing internal and external scaling makes no sense. If there is no resolution matching the source, there will be internal scaling. That conflicts with the title of this PR.

**Comment by sony2** [comment]
That’ s not completely accurate: if the content you have doesn’t comply with the video standards and your target device is, for example, a TV, indeed the upscaling is partly internal and partly external. On the other hand, if you use content which follows standards (576i, 720P, 1080P, …) and the target device is an image processor, the upscaling is only external.

Anyway, the same concept applies to the sound, depending on the target device, the sound is processed internally (if your target device doesn’t support DTS, DTS-HD…) or externally (if it’s an AVR).

**Comment by FernetMenta** [comment]
Audio is either decoded by Kodi or passed through but not a little decoded and then passed through.

**Comment by phate89** [comment]
What's the advantage in a partial upscaling from kodi and then another upscaling? It make sense to disable upscale only when the video resolution matches a resolution available.

**Comment by ciukacz** [comment]
after looking at the code i guess the intent is to use the closest resolution while minimizing the amount of scaling performed by kodi.

1. for standard (most) video resolutions this will effectively disable scaling by kodi.
2. for non-standard video resolutions kodi will scale just the minimum amount to bring the video to closest standard resolution and then external scaler will take over from there.

the user can choose which mode gives better visual results with his hardware.

**Comment by FernetMenta** [comment]
This PR won't have a chance with 2)

**Comment by popcornmix** [comment]
Agreed 2 is wrong. Resizing twice will always look worse than resizing once.
Resizing by a few percent with a low quality resizer will blur your image just as much as a bigger resize factor.
2. needs to skip resizing in kodi (i.e. do actual size) if difference is small enough (so introducing some black bars), and if difference is too great then stick with native resolution of display, and kodi should resize to that (with the hope that display is using a 1:1 pixel mode and so won't harm the image further).

**Comment by Madelaide** [comment]
I disagree with the counter assertion that "resizing twice will always look worse" - give the user, with the user's specific equipment the _choice_ to decide. Padding (black bars) sounds like a good additional choice too, but given the good work **eternius, sony2 et al** have done I would love to see this added to the master. 

I joined github today just so I could comment as this lack of functionality has dismayed me since I moved to xbmc/kodi as my media player two years ago.

**Comment by FernetMenta** [comment]
@github is a dev space. please use forum for those kind of statements

**Comment by sony2** [comment]
I'm testing the modified version.

**Comment by Madelaide** [comment]
Okay, so I've patched these changes into my copy of Kodi (OpenELEC actually) master and built the binaries; does this classify me as a "Dev" now?

If so, then my comments follow:

I have built, installed and started testing this. It mostly works quite well; however, some resolutions are not selected properly and trigger PAL resolutions or UHD (3840x2160p). I will continue testing and tweaking the code until the 50, 25 Hz, and PAL resolutions are passed through properly.

**Comment by sony2** [comment]
Hello Madelaine

I have a question, are you testing the first version (with 4 options in gui) or the last one (you can only enable or disable native resolution)?

The code search for the native resolution in the resolutions supported (edid) that the target device (TV, video processor, AVR) send to kodi. So, do you know if the resolution that is not working in your test is in the edid resolution list?

**Comment by Madelaide** [comment]
Hi Sony2
I used the delta from "files changed" and manually updated the appropriate files in the OpenELEC build.

It has several options, FPS, FPS Stretched, Passthrough, disabled.

It seems a little inconsistent and a reboot sometimes yields a different resolution match. I will run some systematic test cases. Here is my xrandr; if that's any use to you?! If there is a newer patch version could you please point me to it?

Screen 0: minimum 320 x 200, current 3840 x 2160, maximum 32767 x 32767
HDMI1 connected 3840x2160+0+0 (normal left inverted right x axis y axis) 1439mm x 809mm
   1920x1080     60.00 +  50.00    59.94    30.00    24.00    29.97    23.98  
   4096x2160     24.00    23.98  
   3840x2160     30.00    25.00    24.00    23.98*   29.97  
   1920x1080i    60.00    50.00    59.94  
   1680x1050     59.88  
   1600x900      59.98  
   1280x1024     60.02  
   1152x864      75.00  
   1280x720      60.00    50.00    30.00    59.94    29.97    24.00    23.98  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x576i      50.00  
   720x480       60.00    59.94  
   720x480i      60.00    59.94  
   640x480       60.00    59.94  
DP1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)

Cheers

Madelaide

**Comment by X-dark** [comment]
Unmatched resolutions are exactly why I did not sent a pull request with my changes. I have not tried this pull request to see if it is any different.

**Comment by Madelaide** [comment]
I have been modifying and testing my changes on this for the last month. I am now very happy with the results and it passes through native resolution of the input media to my processing devices.

The only issue I have is the skin(s) don't really support the lower resolutions and so the "info" screen, and "codec info" overlays can look a little pixelated. To me this is a less important than the  quality of the video image.

I have limited the acceptable FPS to multiples of the original, however, performing some final tests on FPS which will require pull-down by the external processor.

I will look at posting a binary soon if anyone is interested; I have not worked out (yet) how to post my changes back or fork a branch (I've patched my changes into a copy the OpenElec.tv repo).

Cheers, 
Madelaide

**Comment by sony2** [comment]
I use openelec too, and I´m interested in testing your code. Could you share the source code?
Thanks,
Sony2

**Comment by Madelaide** [comment]
Sure Sony2, I'm not proficient with github so are the patchfiles okay? If so, what's the best way to post them?

Madelaide

**Comment by FernetMenta** [comment]
the best way it to move your discussion to the forum

**Comment by sony2** [comment]
Hi Madelaide

You can post the patch in https://gist.github.com/ and we can move the discussion to the forum (http://forum.kodi.tv/showthread.php?tid=64139)

Sony2

**Comment by sony2** [comment]
Please, close it. It needs more work.

**Comment by hudokkow** [comment]
@eternius, you can submit a new PR when ready.

**Pull request closed without merging**
