### PR TITLE
Provide hide watched status to plugins and sync change.

### PR DESCRIPTION
**Pull request by dbrobins**

### CODE REVIEW

**Comment by Montellese** [comment]
What exactly are you trying to achieve? Why do you need to know the watched state in your plugin? Kodi already has the functionality to hide all items that have a specific playcount and that should also work for plugin items.

**Comment by dbrobins** [comment]
Kodi built-in hiding works for individual items but not for (virtual) folders created by plugins.

**Comment by tamland** [comment]
`Refresh` is expensive. You should do it the other way around: plugins sets the flag for folders (If that doesn't already work. You can set playcount on folders at least)

**Comment by dbrobins** [comment]
Earlier I created a [thread in the forum](http://forum.kodi.tv/showthread.php?tid=218523) asking about handling virtual folders. I just searched specifically for setting playcount and couldn't find a way to do it (except modifying the database directly which I understand is frowned upon for add-ons). If you can help, could you provide information on the thread?

**Comment by MartijnKaijser** [comment]
Let me close it for now. New PR can be opened if wanted/needed and is rebased on current master branch.

**Pull request closed without merging**
