### PR TITLE
[depends] Update libmicrohttpd to SVN 35533

### PR DESCRIPTION
**Pull request by Karlson2k**
This PR should resolve WebServer shutdown issue.

### CODE REVIEW

**Comment by Karlson2k** [comment]
@Montellese @Memphiz Could you check that issue is fixed for you?

**Comment by Karlson2k** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
issue remains for me on windows, call stack
callstack

**Comment by Karlson2k** [comment]
iOS fail is unrelated/

@Memphiz Did you try it on Linux?

**Comment by Memphiz** [comment]
confirmed on jenkins - http://jenkins.kodi.tv/job/WIN-32/4342/ - needs 120secs to shutdown as of the console output - 1hour 46 min overall

**Comment by Memphiz** [comment]
linus only showed the problem once as far as i can tell - so its not reproducable on linux

**Comment by Karlson2k** [comment]
@Paxxi @Memphiz Thanks for reports!

**Comment by Karlson2k** [comment]
@Montellese @Memphiz @Paxxi New version. Tested locally. Does it fix problem for you?

jenkins build this please

**Comment by Paxxi** [comment]
webserver test cases passes and no hangs. +1 from me

**Comment by Memphiz** [comment]
yep looks good:

http://jenkins.kodi.tv/job/TestMulti-All/192/

@Karlson2k please cherry-pick https://github.com/Memphiz/xbmc/commit/64bfb63e9535bbe7d11da3eb854aeeb220ed9943 

after that - feel free to merge.

**Comment by Karlson2k** [comment]
jenkins build and merge

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Comment by Jalle19** [comment]
@Karlson2k can you please comment on http://trac.kodi.tv/ticket/15921?

**Pull request merged**
