### PR TITLE
[Estuary] Add video version name to playlist + Add 3D info + Cleanup

### LINKED ISSUE #24646: Ambiguous name for versions in playlists and favorites
### Describe the bug
The movie name is the only text that appears in the Playlist and Favourite screens to identify what was queued/favorited.
This is confusing and ambiguous for movies that have multiple versions, see below different versions of the same movie queued up:

image

It can be unclear even if only one version of a movie is queued / favorited.

@jjd-uk @Hitcher, as mentioned in Slack, a skin change would be nice.

## Expected Behavior

The version is appended to the movie name, for movies that have multiple versions.

### Debuglog

The debuglog can be found here: not relevant https://paste.kodi.tv/irrelevant.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 21 current master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by jjd-uk**
## Description
Add video version name to video playlist
Add 3D to version media info

## Motivation and context
If you have multiple versions queued in playlist you could not tell them apart from name along

Before 

image

After
image

Took the opportunity to a bit more of a tidy up of the code and add 3D as requested by @CrystalP 

## How has this been tested?
Tested locally on Windows.

@CrystalP I don't have any 3D videos so can you check this displays ok.

## What is the effect on users?
Allow users to distinguish the different versions if they have multiple versions of thew same movie queued.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by jjd-uk** [comment]
Sorry @CrystalP it's not possible to do anything for favourites as `ListItem.HasVideoVersions` is not exposed to the skin within the Favourites window.

**Comment by ksooo** [comment]
> is not exposed to the skin within the Favourites window.

Correct. And there is also the Favourites Home Screen widget, facing the same problem.

Regarding the PR: Using a dash as separator could be problematic as I know many movie titles including a dash itself, so how can one distinguish movie title from version in this cases? That's why I came up with braces around the version name in one of my former PRs, because I think movie titles inclusion braces are much more uncommon than those containing dashes.

**Comment by jjd-uk** [comment]
@ksooo good point I hadn't considered.

I could italicise the version name

image

I think that looks better than

image

**Comment by DecalicatanDecalicatan** [comment]
Just my 2 cents, italicize looks better (I don't remember if it is used elsewhere in estuary, wrt consistency) but with this case I don't think a separator like the dash is needed.
What could be used is italic + different font (but does it meet estuary skin "rules") or italic+ same font but slightly smaller (enough to show it's not the title but not too much to keep it readable of course)
Please discard my comments if not relevant at all

**Comment by CrystalP** [comment]
italics look good. I don't know if it's been used elsewhere but seems appropriate for secondary information.

there is a 3D sample in Kodi samples collection. I'll runtime test anyway.

**Comment by jjd-uk** [comment]
I've gone with

image

**Comment by jjd-uk** [comment]
Yes italics is used in other places for secondary info, for example in PVR channels list and guide for episode details, and as the plot tagline for movies.

**Review by CrystalP — APPROVED** [review]
Runtime tested, version name and 3D indicator appear as needed.

**Review by Hitcher — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
