### PR TITLE
[readme] cleanup deprecated dependencies

### PR DESCRIPTION
**Pull request by un1versal**
Removed libmad0-dev at https://github.com/xbmc/xbmc/pull/4499 just not updated in readmes.

@wsnipex 
anything else jump at you?

### CODE REVIEW

**Comment by wsnipex** [comment]
why did you remove the version requirement from tinyxml?

**Comment by uNiversaI** [comment]
No idea what happened there, maybe the alphabetizer taking liberties.

thx for noticing.

**Comment by wsnipex** [comment]
thanks.
ah, we still have libpostproc in there, that should go as well.

**Comment by uNiversaI** [comment]
sure about that? https://github.com/xbmc/xbmc/search?utf8=%E2%9C%93&q=libpostproc

**Comment by wsnipex** [comment]
yes, we use our ffmpeg internal one.

**Comment by uNiversaI** [comment]
ok done.

**Comment by wsnipex** [comment]
meh, I'm sorry, I should have looked at this thorougher. Mind also removing libavcodec-dev,
libavfilter-dev, libavformat-dev, libavutil-dev, libswscale-dev. Those are all ffmpeg as well..

**Comment by uNiversaI** [comment]
hehe its ok :) Thats what its for.

anymore for anymore?

**Comment by wsnipex** [comment]
thank you, good to go from my side.

**Pull request merged**
