### PR TITLE
 [Music Videos] Align sort methods with music

### PR DESCRIPTION
**Pull request by jjd-uk**
## Description

This fixes music video sort methods so they are more consistent with music. This done by adding more sort methods to music videos and ensuring all sort methods display artist info.

## Motivation and Context

Music Videos are missing some of the available music sort methods, in addition many of them do not show the artist label.

That Music Videos was missing sort methods available in music was brought to my attention by https://forum.kodi.tv/showthread.php?tid=358565

The missing artist labels for the exiting sort methods was brought to my attention by https://forum.kodi.tv/showthread.php?tid=358511

**New**
Artist/Year
Duration
My rating

**Changed by addition of artist label**
Name
Album
Year
Date Added
Play Count
MPAA

### NEW

**Artist/Year**
image

**Duration**
image

**My rating**
image

### CHANGED

**Name before**
image

**Name after**
image

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by ronie — APPROVED** [review]
looks good to me

**Comment by jjd-uk** [comment]
@the-black-eagle can you confirm that everything looks ok to you? as you've done some work with music videos I'm assuming you've got a collection you can test with.

**Comment by scott967** [comment]
Tested on Winx64 test /build and it worked as expected.  I do note in Estuary UI that if you navigate musicvideos/album the UI shows sort by name but if you navigate music/musicvideos/album the UI shows sort by playlist.  There's no other sort options on a music video album node (it's alpha by album title) but album node has always been a weak point for music videos.  (I guess in some use cases with concert videos "album" has no significance).

**Comment by jjd-uk** [comment]
@scott967 I see what you mean. Just for clarity for anyone else reading, this behaviour is the exact same as with Master. The purpose of this PR is to be as lightweight as possible fulfilling the user requests as we are now in Beta to prevent regression or UI oddities being introduced. Perhaps a more in depth looked needs to be taken for v20 as I did wonder if node specific sorting could be done like for other sections, for example create a section for `NODE_TYPE_ALBUM_MUSICVIDEOS` for music video album specific sorting.

**Comment by scott967** [comment]
@jd-uk understood and no problem with PR as written.  More a testing observation for reference.

**Review by DaveTBlake — APPROVED** [review]
Seems harmless enough for v19, although I suspect we want to do more for v20.

**Comment by jjd-uk** [comment]
Ok merging then, if any issues are found then then it's an easy revert. @the-black-eagle could you test a nightly with this in at your earliest opportunity as you've a wider music video library than I have access to.

**Pull request merged**
