### PR TITLE
CGUIDialogSelect: cleanup Add/SetItems. pass const reference

### PR DESCRIPTION
**Pull request by tamland**
No idea what this is about. It's always copied internally anyway. Probably leftovers of something old..

### CODE REVIEW

**Comment by mkortstiege** [comment]
Looks good to me.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by mkortstiege** [comment]
@Montellese objections?

**Comment by kfarhat** [comment]
Stop emailing me I am NOT interested it's annoying to keep emailing me

**Comment by fritsch** [comment]
@kfarhat press the unsubscribe button - you subscribed yourself ... but we will ban you now. So you don't come back by accident.

**Comment by opdenkamp** [comment]
@fritsch stop emailing me! I'm not interested in your buttons!

**Comment by fritsch** [comment]
@opdenkamp Yeah - I know - only interested in my tralala ...

**Comment by opdenkamp** [comment]
@fritsch yeah your dingdingdong

**Comment by tamland** [comment]
Ok you two. Stop emailing *me*. Not interested in your dong conversation

**Pull request merged**
