### PR TITLE
add support for RPi4

### PR DESCRIPTION
**Pull request by graysky2**
## Description
Support Raspberry Pi 4 (RPi4) with Cortex-A72 processor.

## Motivation and Context
Allow for the generation of hardware-specific optimized code through gcc supported hardware-specific flags. See https://github.com/xbmc/xbmc/pull/13638

## How Has This Been Tested?
Minimal testing on my part so far. Builds but unable to test until hardware arrives. 

Will need to be backported into the Leia branch if accepted.

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by wsnipex — APPROVED** [review]

**Comment by popcornmix** [comment]
@graysky2 have you run time tested this? Did the GUI appear? Did HW decode work?

I believe this needs a more substantial change.

Unless I'm missing something it looks like this treats the Pi4 the same as other earlier Pi's and so will try to use the firmware GL libs (in /opt/vc/lib) and headers (in /opt/vc/include) which won't work on the Pi4 (GL hardware is only supported by MESA libs).

windowing/rpi uses dispmanx for GL window surfaces which won't work on Pi4. GBM (or possible X11) needs to be used to get the GUI working on Pi4.

**Comment by graysky2** [comment]
> @graysky2 have you run time tested this? Did the GUI appear? Did HW decode work?
> 
> I believe this needs a more substantial change.
> 
> Unless I'm missing something it looks like this treats the Pi4 the same as other earlier Pi's and so will try to use the firmware GL libs (in /opt/vc/lib) and headers (in /opt/vc/include) which won't work on the Pi4 (GL hardware is only supported by MESA libs).
> 
> windowing/rpi uses dispmanx for GL window surfaces which won't work on Pi4. GBM (or possible X11) needs to be used to get the GUI working on Pi4.

Sorry, there was a paste error in my original PR, awaiting hardware arrival to test.  Should have said builds fine but unable to test on hardware.  Edited.

Will look into the GBM or X11 options you recommended/push/rebase.

**Comment by popcornmix** [comment]
I believe kodi can be built for Pi4 fairly easily. I used:
```cmake ../kodi_gbm -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr/local -DCORE_PLATFORM_NAME=gbm -DGBM_RENDER_SYSTEM=gles -DENABLE_VAAPI=OFF -DENABLE_VDPAU=OFF```
followed by make and kodi can be run from raspbian (note: should be launched without X running or from X after switching to a different VT).

But this will be software decode only. LibreELEC have patches in place to re-enable MMAL in the gbm world, but that is intended as a temporary step.

Work is ongoing to get V4L2 decode working in upstream kodi which is where we are hoping to be for Kodi 19.

**Comment by graysky2** [comment]
@popcornmix - Understood.  If it's a gbm build perhaps my simple PR here is not needed?

**Comment by lrusak** [comment]
> @popcornmix - Understood. If it's a gbm build perhaps my simple PR here is not needed?

correct

**Comment by graysky2** [comment]
@popcornmix -  You mentioned this:

> But this will be software decode only. LibreELEC have patches in place to re-enable MMAL in the gbm world, but that is intended as a temporary step.

Can you point me to these patches?  I would like to experiment with a RPi4 build on Arch ARM.  Thank you!

**Comment by lrusak** [comment]
> @popcornmix - You mentioned this:
> 
> > But this will be software decode only. LibreELEC have patches in place to re-enable MMAL in the gbm world, but that is intended as a temporary step.
> 
> Can you point me to these patches? I would like to experiment with a RPi4 build on Arch ARM. Thank you!

These patches will not make it into Kodi master so IMO it's not worth trying

**Comment by graysky2** [comment]
@lrusak - I was thinking more for my own experimentation with v18.

**Comment by popcornmix** [comment]
@graysky2 https://github.com/popcornmix/xbmc/commits/leia_pi4
(but note this is a dead-end tree. Kodi 19 will not be using mmal but ffmpeg+v4l2).

**Comment by graysky2** [comment]
@popcornmix - I tried building but ran into some errors, log: https://gist.github.com/graysky2/e829e8af90f0439edbacfd752918c14c

**Comment by popcornmix** [comment]
I supect you are picking up wrong header files. 
You need to be using ``/usr/include/EGL/eglext.h`` from mesa and not the firmware ones from ``/opt/vc/include/EGL/``
You shoudn't be referencing ``/opt/vc`` in cmake line.
Renaming ``/opt/vc`` before building would rule out that being found.

**Comment by graysky2** [comment]
@popcornmix - Thank you for the info.  Since my issues are not directly related to this PR, let's continue the discussion in [this thread](https://forum.kodi.tv/showthread.php?tid=345481&pid=2869640).

**Pull request closed without merging**
