### PR TITLE
FIX: [droid] fix joystick after #5624

### PR DESCRIPTION
**Pull request by koying**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@zzattack @topfs2 @wsnipex ping

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
so far all works on the ADT1
jenkins build this please

**Comment by koying** [comment]
That I had confidence in.
I'd feel better if some linux/win joystick users confirm it's still ok on their side, though ;)

**Comment by koying** [comment]
Nobody seems to care, so:
jenkins build and merge

**Comment by MartijnKaijser** [comment]
@koying it failed to build now

**Comment by koying** [comment]
"fatal: Unable to create '/home/jenkins/xbmc-tarballs/xbmc-pvr-addons.git/index.lock'"
Concurrent builds issue? /cc @Memphiz 

jenkins build and merge

**Comment by Memphiz** [comment]
@koying https://github.com/Memphiz/xbmc/commit/711a65258ba49d16afc9862c9d80ed5f72c88ec6 <- fixes it ... or we merge that whole PR #6429  - not sure as the feedback was not clear yet.

**Comment by MartijnKaijser** [comment]
build manually again it's fine

**Pull request merged**
