### PR TITLE
[pictures][guiinfo][Estuary] Slideshow fixes

### LINKED ISSUE #14643: Black screen if you start video after picture
### Describe the bug
Here is a clear and concise description of what the problem is:

Black screen instead of video if video is loaded right after picture in the same directory. 
I hear sound stream of video, but no video

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Video have to be on screen, not a black screen

### To Reproduce

1. Go to pictures and open directory where you have image and video files 
2. Open image
3. Go to next picture. If next file is not picture but video than you see black screen

### Debuglog

The debuglog can be found here:
https://pastebin.com/aw93QPAK

### Your Environment
Used Operating system:

 - [X] Android
 - [X]  Linux with AMLogic
 - [ ] iOS
 - [ ] Linux 
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android, Libreelec
 - Kodi version: Leia last nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
Fixes #14643 and some other picture/video slideshow issues I spotted along the line.

@FernetMenta are you okay with the "black screen" fix, especially with the solution to solve it for "systems that do render video to a video layer" (like Shield).

### CODE REVIEW

**Comment by FernetMenta** [comment]
This change is not correct. By adding the videocontrol to slideshow, systems like OSX render the video twice.
Why don't you treat the different issues separately in different PRs? The changes in PicturesGUIInfo.cpp  are straightforward and not directly related to the others.

**Comment by ksooo** [comment]
> This change is not correct. By adding the videocontrol to slideshow, systems like OSX render the video twice.

 Okay. What would be correct?

**Comment by FernetMenta** [comment]
Adding the video control is wrong.

**Comment by ksooo** [comment]
> Adding the video control is wrong.

 I got what is wrong and why. But what is right? ;-)

**Comment by FernetMenta** [comment]
> But what is right? 

I told you already: fix CGUIWindowSlideShow::Render, so that it lets the video shine through

**Comment by ksooo** [comment]
> I told you already: fix CGUIWindowSlideShow::Render, so that it lets the video shine through

 I would need a bit more of assistence for this.  I'm not at all an expert in this area.

**Comment by ksooo** [comment]
@FernetMenta like this (untested and not really knowing what I'm doing here):

```
diff --git a/xbmc/pictures/GUIWindowSlideShow.cpp b/xbmc/pictures/GUIWindowSlideShow.cpp
index 7797ba8b7e..f5f5358376 100644
--- a/xbmc/pictures/GUIWindowSlideShow.cpp
+++ b/xbmc/pictures/GUIWindowSlideShow.cpp
@@ -630,14 +630,30 @@ void CGUIWindowSlideShow::Render()
   if (m_slides.empty())
     return;
 
-  CServiceBroker::GetWinSystem()->GetGfxContext().Clear(0xff000000);
+  CGraphicContext& gfxCtx = CServiceBroker::GetWinSystem()->GetGfxContext();
+  gfxCtx.Clear(0xff000000);
 
   if (m_slides.at(m_iCurrentSlide)->IsVideo())
   {
-    CServiceBroker::GetWinSystem()->GetGfxContext().SetViewWindow(0, 0, m_coordsRes.iWidth, m_coordsRes.iHeight);
-    CServiceBroker::GetWinSystem()->GetGfxContext().SetRenderingResolution(CServiceBroker::GetWinSystem()->GetGfxContext().GetVideoResolution(), false);
-    g_application.GetAppPlayer().Render(true, 255);
-    CServiceBroker::GetWinSystem()->GetGfxContext().SetRenderingResolution(m_coordsRes, m_needsScaling);
+    gfxCtx.SetViewWindow(0, 0, m_coordsRes.iWidth, m_coordsRes.iHeight);
+    gfxCtx.SetRenderingResolution(gfxCtx.GetVideoResolution(), false);
+
+    UTILS::Color alpha = gfxCtx.MergeAlpha(0xFF000000) >> 24;
+    if (g_application.GetAppPlayer().IsRenderingVideoLayer())
+    {
+      CRect old = gfxCtx.GetScissors();
+      CRect region = GetRenderRegion();
+      region.Intersect(old);
+      gfxCtx.SetScissors(region);
+      gfxCtx.Clear(0);
+      gfxCtx.SetScissors(old);
+    }
+    else
+    {
+      g_application.GetAppPlayer().Render(false, alpha);
+    }
+
+    gfxCtx.SetRenderingResolution(m_coordsRes, m_needsScaling);
   }
   else
   {
```

**Comment by ksooo** [comment]
@FernetMenta updated with my suggested fix for `CGUIWindowSlideShow::Render`. Better now?

**Comment by FernetMenta** [comment]
You forgot to render the video layer, RenderEx(). 

> I runtime tested this on my Shield and it seems to work just fine now.

Rendering the video layer is essential, i.e. for exact timings. The fact that video on Android works without it (somehow) is an indicator how bad video rendering on Android is implemented.

**Comment by ksooo** [comment]
&FernetMenta Okay. What needs to be done in  RenderEx? Same as in CGUIVideoControl::RenderEx?

**Comment by ksooo** [comment]
@FernetMenta how does this look like (now with renderEx)? https://github.com/xbmc/xbmc/pull/16484/commits/851a5ddbe1b876a8d4bf6ee8704cc8110082308d

**Comment by FernetMenta** [comment]
Lgtm

**Comment by ksooo** [comment]
jenkins build this please

**Pull request merged**
