### PR TITLE
dvdplayer: avoid ffmpeg hw decoder reset on recoverable error

### PR DESCRIPTION
**Pull request by FernetMenta**
should fix TRAC #15741
faulty material my require more decoder buffers than max_refs for h264. if ffmpeg requests a buffer and we have none available this error is recoverable without resetting the decoder.

### CODE REVIEW

**Comment by fritsch** [comment]
Looks quite good.

The title is a bit misleading, cause it only changes the implementation of one codec (ffmpeg) and not the player behaviour. Should that also be extended beyond ffmpeg for other codecs?

**Comment by FernetMenta** [comment]
@fritsch I updated the title and changed implementation to use existing check method
jenkins build this please

**Comment by fritsch** [comment]
That looks good. The only problem I see is, that we get somehow stuck, e.g. in VAAPI - if surfaces are not coming back into the free pool, stuck in render or something. Field tests will show if something additionally like error ins a row counting is needed.

**Comment by FernetMenta** [comment]
never fight symptoms but root causes. if surfaces don't flow back from renderer something went wrong and needs to be fixed there.

**Comment by fritsch** [comment]
Yeah - if we are the issue, then you are right. But most of the time some
shitty driver is the problem and we need to workaround in order to stop
whining, sadness and suckery :-)

2015-02-01 9:53 GMT+01:00 Rainer Hochecker <notifications@github.com>:

> never fight symptoms but root causes. if surfaces don't flow back from
> renderer something went wrong and needs to be fixed there.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/xbmc/pull/6311#issuecomment-72356886>.
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Pull request merged**
