### PR TITLE
[mythtv] remove internal mythtv support

### PR DESCRIPTION
**Pull request by mkortstiege**
This removes the internal mythtv (cmyth) support.

### CODE REVIEW

**Comment by FernetMenta** [comment]
+1

**Comment by Memphiz** [comment]
nah +16,-21282 ... :D

**Comment by Paxxi** [comment]
Yay, this will remove a few warnings on win32, big thumbs up :)

**Comment by ksooo** [comment]
@mkortstiege Cool. I volunteer for doing the same with internal htsp support. Any objections?

**Comment by ksooo** [comment]
https://github.com/xbmc/xbmc/blob/master/CONTRIBUTORS#L2 => filemyth ?

**Comment by ksooo** [comment]
https://github.com/xbmc/xbmc/blob/master/project/VS2010Express/XBMC%20for%20Windows.sln#L18 => libcmyth_dll ?

**Comment by xhaggi** [comment]
+1 and @ksooo +1 for drop htsp too.

**Comment by mkortstiege** [comment]
@ksooo sure ;) Any objections to completely remove the CONTRIBUTORS file? Since it´s not complete i see no reason to keep it. Will also remove the leftover in the windows project file.

**Comment by ksooo** [comment]
Okay, will come up with a htsp removal pr soon.

Re removal of CONTRIBUTORS: +1 (could do this in the htsp pr)

**Comment by mkortstiege** [comment]
@ksooo sweet. Btw, the removal of CONTRIBUTORS is in here already. Just need to squash.

**Comment by MartijnKaijser** [comment]
Go for it

**Comment by mkortstiege** [comment]
Squashed and rebased. jenkins build this please.

**Comment by opdenkamp** [comment]
nice.

re htps: @elupus said he was using htsp vfs still at devcon 2 years ago. not sure if that's still the case, but since it's very much outdated and has no maintainers, it should go too unless someone wants to keep it and take ownership

**Comment by mkortstiege** [comment]
Same applies to VTP but i see no reason to maintain it when there's a a PVR client for the backend.

**Pull request merged**
