### PR TITLE
[cmake] Fix libdvd*

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Broke all sorts of stuff here, my bad.

## Motivation and context
Fix libdvd build/compilation/usage for all platforms.

First issue is libdvdnav.dll not being bundled with windows. This was fallout from https://github.com/xbmc/xbmc/pull/25228 and dependency tracking was broken for shared libs and the file export for packaging step. First commit fixes this

Second commit just insures dependency ordering is correct.

Third commit is a streamlined of the FindLibDvd* modules. Cleanup code, remove superfluous checks/tests. Strip what is now unrequired  FHPSA matching. It also removes the inadvertent static linking of the libdvd libraries on unix platforms. This isnt currently desired, but will hopefully change in the future with work @enen92  has PR'd upstream (maybe one day it'll get merged)

Fourth commit fixes target variables not actually working in core_link_library functions, and actual correct wrapper compilation for libdvd for unix based platforms.

## How has this been tested?
Macos x86_64, Win x64

## What is the effect on users?
Working dvd

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
Testbuilds

Windows x64: https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20240709-a149f8a5-PR25466-merge-x64.exe
Windows x32: https://mirrors.kodi.tv/test-builds/windows/win32/KodiSetup-20240709-a149f8a5-PR25466-merge-x86.exe

@KarellenX this is in relation to some forum post you mentioned on slack. If you could have the user test

**Comment by KarellenX** [comment]
Thanks @fuzzard 
I'll ask the member to test.

**Comment by enen92** [comment]
Tested android and dvds work fine now (both isos and folders stored on a nas)

**Comment by KarellenX** [comment]
@fuzzard The member on the forum confirms the fix works...
https://forum.kodi.tv/showthread.php?tid=378132

**Pull request merged**
