### PR TITLE
changed: Have filecache retry instead of abort with fatal errors (fix…

### PR DESCRIPTION
**Pull request by arnova**
Backport of #19486

### CODE REVIEW

**Review by wsnipex — APPROVED** [review]

**Comment by jjd-uk** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by rainman74** [comment]
@wsnipex Unfortunately, this problem now occurs again in the current nightly!
kodi-20210427-425b32e0-Matrix-armeabi-v7a.apk

Is it possible that the fix was accidentally thrown out or there was a compile error?

Here it still worked: kodi-20210420-f19624ac-Matrix-armeabi-v7a.apk

**Comment by arnova** [comment]
> @wsnipex Unfortunately, this problem now occurs again in the current nightly!
> kodi-20210427-425b32e0-Matrix-armeabi-v7a.apk
> 
> Is it possible that the fix was accidentally thrown out or there was a compile error?
> 
> Here it still worked: kodi-20210420-f19624ac-Matrix-armeabi-v7a.apk

Unlikely. Please provide a new debug log for inspection.

**Comment by rainman74** [comment]
> > @wsnipex Unfortunately, this problem now occurs again in the current nightly!
> > kodi-20210427-425b32e0-Matrix-armeabi-v7a.apk
> > Is it possible that the fix was accidentally thrown out or there was a compile error?
> > Here it still worked: kodi-20210420-f19624ac-Matrix-armeabi-v7a.apk
> 
> Unlikely. Please provide a new debug log for inspection.

ok I do, but the error has not occurred again until now. I had already panicked when in one day was stopped 3 times. But since then everything is running again.

**Comment by mauromol** [comment]
> ok I do, but the error has not occurred again until now. I had already panicked when in one day was stopped 3 times. But since then everything is running again.

What I personally see is that... it depends. It seems to be fixed, but then the next day the problem happens again randomly. It's much better than before, but sometimes reading from the NAS still hangs. I understand that this patch alone cannot do miracles. I still believe there's some lower level problem in Kodi that causes these read errors. However, given the tiny number of users with these Sony TVs using a cable connection, I fear we won't get a fix any time soon.

**Pull request merged**
