### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by notspiff**
- fix fallout from #9966 (my bad - i assumed CI executed tests)
- fix fallout from #9977 (bad bad @MartijnKaijser pushing untested changes into mainline git!)
- fix the long-broken RarFile test

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
I didn't ran jenkins with gtest, only regular :)

**Comment by MartijnKaijser** [comment]
http://jenkins.kodi.tv/job/BuildMulti-PR/5152/
Travis is already happy so lets wait for Jenkins+gtest enabled

**Comment by MartijnKaijser** [comment]
Travis reports all OK on linux and jenkins gives failures on test
http://jenkins.kodi.tv/job/LINUX-64/8142/console
http://jenkins.kodi.tv/job/OSX-64/8533/console

**Comment by notspiff** [comment]
I have seen those before but cannot reproduce locally now. i think it's compiler version related.

**Comment by MartijnKaijser** [comment]
Forgot to mention that same failure is on OSX so for sure must be something in common.

**Pull request merged**
