### PR TITLE
[Videodb] Fix of previous data migration and refactors

### LINKED ISSUE #24368: Old unused extra names appear in Movie version type selection
### Describe the bug

Problem related to the db migration to v127 of PR #24340, but root cause is a flaw in the original data model.

When using "Rename version" in Manage versions dialog:
image

extra1 and extra1v2 were not versions, they were extra names I used at some point, then I removed or deleted the extras referencing those names before the data migration to v127.

There is a gap in the data migration code: the custom extra names not linked from videoversion anymore were not migrated and received the default itemType 0 (=movie) instead of itemType 1 at the end. But it couldn't have done much better because of a flaw in the initial data model, where unused videoversiontype records do not have a "movie" or "extra" type.

As a consequence the old unused extra names now look like custom version names in the db, and show up as such in the list of version types for "Rename version"

## Expected Behavior

Old unused extra names don't show as version types. There should be a way to remove custom versions or extra names from the list.

## Possible Fix

I don't think the problem can be undone by a query.
From a db perspective the best I can think of is another db bump with a migration query to remove all unused videoversiontypes with owner = 2 and itemType = 0
However it will also kill unused custom version names the user may have created.

The safe way would be to add a way in the GUI to delete unused custom version / extra types. If not for this particular problem, that will be needed anyway at some point for users to maintain their version types list and delete past mistakes in the naming for example.

### To Reproduce

1. start with older Kodi from before videodb v127 (haven't tried beta2, but it should trigger the issue)
2. assign a custom name to an extra through Manage extras > rename > New
3. remove the extra, or rename it to something else
4. run current Kodi
5. the db is migrated to v127
6. Manage versions > Rename > the old extra names show at the bottom of the list.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: current master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CrystalP**
## Description

3 changes in one to minimize the db version bumps.

- fix incorrect type format specifier in movie_view creation. 
- rename videoversion.mediaType to media_type for consistency with all the other tables and make joins more readable
- fix a gap in the migration code to db v127 for unused user-defined version types.
  - as discussed in the issue, it means removing the unused user-defined movie version types as it's not possible to say if they're really movie versions or possibly extras. That will mean a small loss for users of v21 beta 2. The used user-defined types are not affected.
  - the better fix of providing a GUI to manage the version types won't happen until v22

## Motivation and context

Fix #24368 and more cosmetic issues.

## How has this been tested?

Sqlite and MariaDB migration from v127 and creation of new database.

## What is the effect on users?

Usability of video versions feature.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [X] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CrystalP** [comment]
Added 1 commit just for the formatting cosmetics, otherwise the 3 line change is lost in the 60 lines reformat.

**Review by the-black-eagle — APPROVED** [review]
LGTM

**Review by ksooo — APPROVED** [review]
LGTM.

**Comment by ksooo** [comment]
Jenkins build this please

**Comment by ksooo** [comment]
Jenkins android-x86-docker error is unrelated and build was blue in previous attempts (where Windows acted up). So, all in all, green.

**Pull request merged**
