### PR TITLE
[guilib] add defaulticons for addonmanager root

### PR DESCRIPTION
**Pull request by phil65**
this adds listitem.icon to the listitems in addonmanager root. Naming of the defaultimages is up for discussion.

@tamland 

Would also need confluence adjustments. @ronie , @HitcherUK , opinions?

EDIT: actually, confluence also doesnt look too bad without adjustments.

### CODE REVIEW

**Comment by ronie** [comment]
yeah, would be nice.

perhaps use this naming scheme?
- DefaultAddonsInstalled.png
- DefaultAddonsUpdates.png
- DefaultAddonsRepo.png
- DefaultAddonsZip.png
- DefaultAddonsSearch.png

**Comment by phil65** [comment]
Also fine for me. Updated to match your suggestions.

**Comment by phil65** [comment]
ping @tamland 
Is it fine to write to those members directly or should I use a setter?

**Comment by tamland** [comment]
No that's fine. Merge away if you're ready

**Comment by phil65** [comment]
ok, thx.

**Comment by HitcherUK** [comment]
New icons for Confluence would need to be done by someone with better graphical skills than me.

**Comment by phil65** [comment]
As said, it doesnt look too bad the way it is now the last time i checked.

**Pull request merged**
