### PR TITLE
VideoPlayer - cleanup

### PR DESCRIPTION
**Pull request by FernetMenta**
Round1 cherry picks from #9442

### CODE REVIEW

**Comment by FernetMenta** [comment]
thanks to @MaxKellermann 
I will pick more but need to finish some other work before

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
@MaxKellermann any idea why build failed on every platform but Linux?

**Comment by MaxKellermann** [comment]
No - http://jenkins.kodi.tv/job/BuildMulti-PR/4745/ gives me "404 Not Found".

**Comment by anaconda** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
oops :)

**Comment by MaxKellermann** [comment]
/Applications/Xcode6.1.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstdlib:98:9: error: no member named 'div_t' in the global namespace; did you mean 'dev_t'?

This very much looks like broken libc++ headers. My include cleanup patch may have exposed this  bug. Does the build server use the latest libc++ version?

**Comment by FernetMenta** [comment]
I don't know but it fails on my Mac too. That has latest XCode installed.

**Comment by MaxKellermann** [comment]
Same problem on Android, with an outdated NDK. Broken system headers.

**Comment by FernetMenta** [comment]
jenkins build this please

**Pull request merged**
