### PR TITLE
[groovy] Update groovy to 2.4.4 and move to tools/codegenerator/

### PR DESCRIPTION
**Pull request by hudokkow**
@jimfcarroll, @rbalint, mind having a look?

Builds fine on Vivid x86_64. Other platforms need testing.

EDIT: Is tools/depends/ a more appropriate location?

### CODE REVIEW

**Comment by rbalint** [comment]
I'm OK with the change. I have to patch embedded groovy out from the Debian source package no matter where it resides in the tree.

**Comment by rbalint** [comment]
BTW Latest Kodi package has been built with groovy 2.4.3 already in Debian.

**Comment by Paxxi** [comment]
I don't think it should be in contrib as it's not code that we depend on as such. what's wrong with sticking it in tools/codegenerator as that's what it is and is used for?

**Comment by rbalint** [comment]
I prefer keeping the original location, too, since I don't have to change packaging in this case. :-)

**Comment by hudokkow** [comment]
Moved to tools/codegenerator/

@rbalint, where trying to get rid of lib/ folder ;-)
jenkins build this please

**Comment by MartijnKaijser** [comment]
Where not trying to get rid of it. Where trying to get it more logical.

**Comment by hudokkow** [comment]
I stand corrected...

**Comment by rbalint** [comment]
I welcome the fewer number of dependencies shipped in lib but I understand that removing them is not easy because they may be missing on other systems.
To help moving forward I have recently packaged cpluff separately:
https://packages.qa.debian.org/c/cpluff.html

**Comment by hudokkow** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
I forgot to ask, why are we updating groovy? Does it solve a problem or just trying to stay current?
I'm not opposed to it either way, just curious.

**Comment by hudokkow** [comment]
Just trying to stay current. There's quite a few outdated depends.

**Comment by MartijnKaijser** [comment]
+1 for staying current when it was safe/proofed it has no negative side effects. If there are some investigation is needed.

**Comment by jimfcarroll** [comment]
Fine by me. I've been using the latest personally and I haven't run across any issues. As long as things still build it should be fine.

**Pull request merged**
