### PR TITLE
PlayListPlayer: New function the ensure items are played with a playlist

### PR DESCRIPTION
**Pull request by dgam1**
There are cases where playback of files doesn't create a playlist. @Montellese made a comment about that here: https://github.com/xbmc/xbmc/pull/5958#issuecomment-67295177

One of those cases is when you start playback of an item over JSON like this:
`{"params": {"item": {"file": "/videos/video.mp4"}}, "jsonrpc": "2.0", "id": 1, "method": "Player.Open"}`
(Or, more generally, every time TMSG_MEDIA_PLAY gets sent with a single item attached)

Another is where you start playback of a file over the Kodi file manager. What's worse here is that the old playlist doesn't get deleted before playback.

To take care of that I added a new overloaded function Play() to the PlayListPlayer that takes an item as argument, creates a new playlist for it and starts the playback.

For the second commit I found two instances that can use the new function:
1) In CGUIWindowVideoBase::PlayMovie(), when opening a file from the video browser
2) In CGUIWindowMusicBase::OnPlayMedia(), when opening a file from the music browser while the setting to automatically queue the next item is disabled

## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by rmrector** [comment]
Nice. [This block](https://github.com/xbmc/xbmc/blob/a077d7b954189dc506231eca504baf9cbc8f810a/xbmc/interfaces/builtins/PlayerBuiltins.cpp#L474) currently plays a single video without a playlist, can you rig the new function up here as well? This is the built-in PlayMedia action, and it's also used for skin containers not on a media window, like Home widgets.

**Comment by dgam1** [comment]
This ought to do it.

**Comment by dgam1** [comment]
Rebased. As of PR #10857 there is another use case for the new function.

**Comment by Razzeee** [comment]
jenkins build this please

**Comment by Razzeee** [comment]
Reads fine to me and also builds fine.

I would like to merge this in the coming days.

**Comment by Razzeee** [comment]
Thanks @dgam1 

jenkins build and merge

**Comment by ksooo** [comment]
@dgam1 , @Razzeee This PR breaks PVR. Example: Open Channel window, select a channel, open its context menu. Select "switch to channel" from context menu. Nothing happens. 

functionality is triggered from here: https://github.com/xbmc/xbmc/blob/master/xbmc/video/ContextMenus.cpp#L168

**Comment by dgam1** [comment]
Ah, I don't have PVR hardware and so hadn't tested that. Should have mentioned it.

If FileItem's IsVideo returns false for LiveTV, does IsAudio also return false for PVR radio?

**Comment by ksooo** [comment]
IsAudio() returns true for PVR radio.

**Comment by dgam1** [comment]
Thanks. Now I have to assume that if you open a LiveTV channel over a home widget, it will not create a playlist for that item, right?

If my assumption is correct, this commit should fix that (short of having IsVideo return true for LiveTV): https://github.com/dgam1/xbmc/commit/e982422d1e416dec2443ef91981164256dd53cb0

Would you mind testing that?

**Comment by ksooo** [comment]
@dgam1 have you seen #11981 ? Or are you trying to fix something else with the above mentioned commit?

**Comment by dgam1** [comment]
@ksooo Yes, I have have seen it and based on it I assume this PR missed another case where playback of an item doesn't create a playlist. That case being when you open a LiveTV item over a home widget. So my new commit not only checks IsAudio and IsVideo but also IsLiveTV, which can now be handled thanks to your PR.

**Comment by ksooo** [comment]
Okay, now I got it. Yes, your changes, in addition to #11981 do fix the home screen widget in the sense that now a playlist for Live TV gets created.

But, does it actually make sense to create a playlist for Live TV? I know this has been the case before, but ... I suddenly feel like this could be nonsense. ;-)

**Comment by ksooo** [comment]
Maybe we should try to play Live TV without creating a playlist?

**Comment by ksooo** [comment]
I think this is the right way to do it: https://github.com/ksooo/xbmc/commit/dac2902c7d7b0a8ee0ec54a79ec0599b4c0d5f5e

**Comment by ksooo** [comment]
^^^ The actual bug was to create a playlist for Live TV in <code>static void SetPathAndPlay(CFileItem& item)</code> ... which at the end led to the confusion (on my end).

**Comment by dgam1** [comment]
It seems to me that "everything that is being played is in a playlist" is the overall easier route to go but it appears like that's something on which you devs haven't fully come to an agreement yet :)

Regarding the commit you just posted: Should an already existing playlist be cleared before starting LiveTV? Is radio another case that requires special handling? And for that matter, what about internet live streams in general, do they belong in a playlist?

**Comment by ksooo** [comment]
> It seems to me that "everything that is being played is in a playlist" is the overall easier route to go

 I generally agree with you. It seems to be quite a mess currently. But I have to admit that I'm not very deep inside the playlist stuff. 

 Why is a playlist not just a list containing arbitrary playable items, for example a mix of two videos, a Live TV channel, then two songs. Why is there a separation between music and video? But I guess this is something we should discuss in the Kodi forum.

 For now, I would be happy to have it consistent - no playlist for Live TV.

**Pull request merged**
