### PR TITLE
Support pasting X-selection on Linux

### PR DESCRIPTION
**Pull request by amirgon**

### CODE REVIEW

**Comment by wsnipex** [comment]
Nice!

please rebase out that merge commit.
And Xsel should not be incorporated into kodi core, it should go to depends.
@mkortstiege ping

**Comment by FernetMenta** [comment]
Calling functions like XNextEvent or CreateWindow in this locations is not acceptable.

**Comment by amirgon** [comment]
@wsnipex Should I move Xsel's one source file under `tools/depends`? Then build a library and link it? This feels like an overkill. Also it seems that `depends` is about external dependencies. While Xsel class is based on the xsel tool source, I had to omit many parts, change some stuff and add a C++ class wrapper, so it is no longer an "external" tool, although I kept the origianl copyright notice of xsel.  

@FernetMenta My goal was to stick as much as possible to the original xsel sources.  `xsel` is a robust old timer utility that was used on many platforms and is proven to work well. Making changes, or re-writing this functionality could introduce bugs or not work on all platforms. Take into account that working with X selection is not a trivial task as it may seem, and the original xsel author took the trouble to study the specs and write it in a compliant way.  
I tried, for example, not to call `CreateWindow` but pass an existing Kodi window instead (I think I tried to pass `m_mainWindow` from `CWinSystemX11 `) and it didn't work. I didn't try to debug why, but even if it did work on my system, it might not have worked on others.

**Comment by wsnipex** [comment]
ok, it can stay if its not the original xsel file

**Comment by FernetMenta** [comment]
> My goal was to stick as much as possible to the original xsel sources.

My goal is to keep Kodi's design clean and make it more robust. This code contradicts with this. There must only be a single location where events are dispatched. Having multiple sources for creating windows is error prone. It is obvious that this code won't work on multi-monitor setups. etc.

**Comment by amirgon** [comment]
@FernetMenta I don't think there would be any issue with multi-monitor setups, as this window is only needed for the x-selection and not for displaying anything.  
I understand you want to keep Kodi's design clean and robust, and I respect this. If you have a concrete suggestion how to change this code in order to allow it into Kodi (without re-writing it) I'm willing to hear about it.
Otherwise, I will close this pull request.

**Comment by FernetMenta** [comment]
I have not looked into the details but I am pretty sure this can be done without creating an additional window. XSel is actually a cmd line tool that accesses the X clipboard. That's a different story.

**Comment by amirgon** [comment]
@FernetMenta Suppose I did not create an additional window. You say I can't even call `XNextEvent`, how would you suggest waiting for `PropertyNotify`?

**Comment by FernetMenta** [comment]
@amirgon check out https://github.com/xbmc/xbmc/blob/master/xbmc/windowing/WinEventsX11.cpp#L326
That's where Kodi listens for all X11 events

**Comment by amirgon** [comment]
Closing this request since xsel sources would not be accepted into Kodi without major changes.

**Comment by Paxxi** [comment]
There's plenty of issues with code 
1. It overloads c library methods for no real reason
2. It will create a window, go into several? Event loops and then destroy the window on every paste operation
3. It uses it's own print_debug rather than CLog. 
4. It calls exit on errors which is never ever acceptable in "library"  code

**Pull request closed without merging**
