### PR TITLE
OS X Kodi.app script target transformed into a real app bundle target

### PR DESCRIPTION
**Pull request by HofiOne**
The goal was to create a bundled target that can be started and
debugged from Xcode just like the standalone Kodi binary.

Kept all of the 4 original build script steps, so the build process
itself does not changed at all, only the following changes made:
- Kodi.app target now become native app bundle target
- XBMC_DEPENDS added to App-OSX.xcconfig common config file instead of
  defining per target
- otool -L calls replaced by otool -LX to eliminate the first summary
  line from the output result, that could cause the parsing of the result
  fail

### CODE REVIEW

**Comment by Memphiz** [comment]
also for the future please prefix your commits with [osx] (or whatever subsystem you are altering).

**Comment by Memphiz** [comment]
jenkins build and merge (just in case anyone asks himself wtf is memphiz doing here in beta phase - this is a nop when it comes to our release ...)

**Comment by HofiOne** [comment]
ok, thanks for the patience :)
(what if common code modified, no prefix i guess)

**Comment by Memphiz** [comment]
there is always a way to find a prefix - just have a look at https://github.com/xbmc/xbmc/commits/master and you'll get the idea (the merge commits are done by github and are to be ignored ...

**Comment by Memphiz** [comment]
scratch that - you won't get the idea because a lot of devs do it different. well we darwin devs use the bracketed prefix ;)

**Comment by HofiOne** [comment]
looks like our commit list at workplace, there is a rule, but no one keeps
ok, [osx] will be used

**Comment by Memphiz** [comment]
it looked better at some point but new members entering the team - old vanishing - no-one writes the "rules" down ;) - well lets stop it here on github now - one important information - each comment on something in our repo spams all the team devs ... so keep it low - use the forum or irc for chatting ;)

**Comment by HofiOne** [comment]
ok, last one, which irc channel to use? #kodi-osx is now almost empty

**Comment by Memphiz** [comment]
#kodi-dev iirc

**Pull request merged**
