### PR TITLE
[Skins] Fixed VP8/VP9 codec name in mediaflags

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

Show right codec name for VP8/VP9 video codec

## Motivation and context

Previously was shown VP8/VP9 video codec as `webm`
but webm is a container type used for audio/video codecs not a codec itself
these codecs can be used on more type of containers

The images has been done with PhotoShop to match as best the originals:
Font characters config:
Lato font: https://fonts.google.com/specimen/Lato?preview.text=1.37:1%201.66:1%202.55:1&preview.text_type=custom
Lato font regular, 44pt, Chars spacing 0, Bold style -simulated-, Text edge to "Sharp"
Layered sample: [MediaFlagMaster.zip](https://github.com/xbmc/xbmc/files/9034590/MediaFlagMaster.zip)

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by enen92** [comment]
All textures have a ~140% increase in size, maybe they are not compressed?

**Comment by CastagnaIT** [comment]
I have tried changing the way to save file but saved only few bytes
there is no compression settings in photoshop or maybe last update has broken something
i will try update photoshop

**Comment by CastagnaIT** [comment]
Updated with tiny PNG sizes

**Review by enen92 — APPROVED** [review]

**Review by howie-f — APPROVED** [review]
👍

**Comment by sarbes** [comment]
Please, fix the texture dimensions if you touch them. In Estuary, they are way larger than they have to be, even for 4k! This is very bad for the texture cache/rendering performance and for the image quality.

As far as I see, here they are defined:
```
	<include name="MediaFlag">
		<param name="width">115</param>
		<param name="height">60</param>
		<param name="visible">true</param>
		<definition>
			<control type="image">
				<width>$PARAM[width]</width>
				<height>$PARAM[height]</height>
				<fadetime>0</fadetime>
				<aspectratio align="center" aligny="center">keep</aspectratio>
				<texture>$PARAM[texture]</texture>
				<visible>$PARAM[visible]</visible>
			</control>
		</definition>
	</include>
```

If you would cut the whites space around them, they would only be 107x34 in size. That's only 11% compared to this version.

Here is a appropriately sized texture, usable with our current spacing:
->vp8<-

And here you can see the texture rendered at 1080p:
estuary_flags
 
The rectangle is sharper and more defined, with the same frame thickness. The font will be sharper too if rendered at this size (in my mockup, I've simply scaled the letters). There is no aliasing anymore.

**Comment by CastagnaIT** [comment]
I will take a look, i think it would be more correct to change the xml/image width size to an even value so 116x60
and IMO it would be better to do this with a separate PR
otherwise change only one png we will have inocerence in the display

redo all images (are more 100) from scratch will clean also all the frankenstein images created by hand and with mixed fonts

**Pull request merged**
