### PR TITLE
[xbmc] Fix includes of CVariant and some improvements

### PR DESCRIPTION
**Pull request by Paxxi**
Added Move constructors for a few types for CVariant and added
move versions to push_back and append.
Added plenty of include directives as they were missing.
Made many conversions to CVariant explicit to make it clear what happens and that the include is needed.

### CODE REVIEW

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
I don't like the changes done to the dialogs. Please explain why this is done

**Comment by Paxxi** [comment]
The reason I changed the method signatures is because in most cases this version should perform better. Almost every call to these methods use a temporary CVariant created on the spot, with these changes it'll be move constructed and no copying will ever be done. If I remember correctly there's maybe 5-10, probably less places where we actually use a CVariant and in those cases there will be a copy operation.

The rules have changed somewhat with the introduction of C++11, pass by const ref isn't necessarily the best and most performant way anymore. I don't intend to run around changing everything but after seeing how these methods are used it felt like a reasonable thing to do.

There's plenty of resources that explains it better than I do, e.g
http://blogs.msdn.com/b/xiangfan/archive/2012/02/03/c-98-gt-c-11-pass-by-value-or-pass-by-reference.aspx
https://web.archive.org/web/20140205194657/http://cpp-next.com/archive/2009/08/want-speed-pass-by-value/

**Comment by Paxxi** [comment]
Fixed the build error, missing include that surfaced with the changes.

**Comment by topfs2** [comment]
With these it is pass by copy so you will create a variant before
invocation, then it will copy and send that to the executing method. Before
we had pass by reference, I.e it creates one on invocation and pass
reference, not copy, to the execution. In short on less memory allocation.
And some variants are very large and copy them takes a bit.

We have in our code guidelines to pass by const reference for this reason,
its faster and easier to optimize for the compiler.

**Comment by topfs2** [comment]
Sorry missed the links will read them through. However variant doesn't use
STD::move so not sure if the compiler can optimize like in the examples.

**Comment by Paxxi** [comment]
@topfs2 I implemented a move constructor and move assignment for CVariant in the first commit so that's covered.
I do agree that they're not called much and maybe not worth the bother to change it, let's see what @MartijnKaijser says and if I'm in the minority I'll drop the second commit with the dialog changes.

**Comment by topfs2** [comment]
Oh hahaha, thats what I get for looking through this big commit on my phone :P Then I have nothing against it!

Man teaching an old dog new tricks here, I need to revisit other projects with std::move now I think :)

**Comment by MartijnKaijser** [comment]
If it benefits the code I won't argue. I'll let more knowledgeable people decide. 
Side note is that I'll have to throw away my cleanup branch regarding strings in progress dialogs :( It's one big merge conflict now.

**Comment by Paxxi** [comment]
@MartijnKaijser let's get your in first then, I don't mind rebasing :)

**Comment by MartijnKaijser** [comment]
It's not finished yet and it touches all the same spots do its not as easy as as simple rebase.

**Comment by topfs2** [comment]
BTW that there is some things left to discuss regarding the move change.
Basically the api is changed, before when we pass by const reference the
api promised that it would not alter the variant, the variant is immutable
here. In the change that promise is no longer there, the variant may be
changed and any caller which do not want that have to copy before
invocation.

Unless I misunderstood something more with the new stuff?

**Comment by Paxxi** [comment]
@topfs2 as they're not references anymore it still holds true that anything you pass won't be messed with.

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
all formatting should be fixed.
jenkins build and merge please

**Comment by MilhouseVH** [comment]
This PR is causing a problem - kodi.bin for Ubuntu x64 will now segfault at startup (empty kodi folder): http://sprunge.us/ISef when this PR is included (when HEAD is 2efc4456b8, kodi.bin will not segfault).

In case there is some related problem with #7359, I tried reverting #7359 and kodi.bin continues to segfault (the crash log above is without #7359), so it doesn't appear that #7359 is the direct cause of the segfault.

OpenELEC on RPi also fails at startup: http://sprunge.us/bGbX however this build includes #7359, which is also causing problems at startup.

**Comment by Paxxi** [comment]
Will look into it tonight

**Comment by Paxxi** [comment]
@fritsch yup it's the same

**Comment by popcornmix** [comment]
Backtrace on a Pi: http://pastebin.com/qJGtzZKg

**Comment by afedchin** [comment]
Same on windows in same place. segfault in CVariant destructor after PLAYLIST::CPlayListPlayer::SetRepeat

**Comment by xhaggi** [comment]
same on osx

**Comment by topfs2** [comment]
It could be double deletes due to the move, but it wasn't supposed to be
triggered here as it was a pass by value?

Honestly I still feel that it's something odd with the change. If it moves
here it feels very bad api and if it doesn't then we introduce copies which
are slower then the old pass by reference.

Might be valid to revert it if that's the issue?

**Comment by topfs2** [comment]
The design of cvariant is that every copy of variant holds its own data.
Data is never "shared" much how other types works.

**Comment by fritsch** [comment]
What can happen is, as the ctor is not thread safe at all ... two threads
try to delete a CVariant. and second delete is started before the type is
set to NULL type.

Or what @topfs says: Someone copies it without doing a deep copy and the
.data is deleted twice.

Both would suck :-)

2015-07-09 16:03 GMT+02:00 Tobias Arrskog <notifications@github.com>:

> The design of cvariant is that every copy of variant holds its own data.
> Data is never "shared" much how other types works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/xbmc/pull/7287#issuecomment-119988341>.
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by fritsch** [comment]
Workaround:
- Don't flat copy (111!!)
- Set .data to NULL (<- only lazy fix and no fix at all).

2015-07-09 16:09 GMT+02:00 Peter Frühberger <peter.fruehberger@gmail.com>:

> What can happen is, as the ctor is not thread safe at all ... two threads
> try to delete a CVariant. and second delete is started before the type is
> set to NULL type.
>
> Or what @topfs says: Someone copies it without doing a deep copy and the
> .data is deleted twice.
>
> Both would suck :-)
>
> 2015-07-09 16:03 GMT+02:00 Tobias Arrskog <notifications@github.com>:
>
>> The design of cvariant is that every copy of variant holds its own data.
>> Data is never "shared" much how other types works.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/xbmc/xbmc/pull/7287#issuecomment-119988341>.
>>
>
>
>
> --
>                    Key-ID:     0x1A995A9B
>                    keyserver: pgp.mit.edu
> ==============================================================
> Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by Paxxi** [comment]
It's just an oversight not setting the.data to nullptr after move, should be quick fix but not home yet

**Comment by topfs2** [comment]
Well CVariant was never intended to be threadsafe. Much as std::vector is not. Thats why it never shares data, so between threads its perfectly fine to do pass by copy, in same thread you could use pass by reference. And I reckon with c++11x it could be safe to do pass by move (if this is the name) in the same thread. Between threads it _needs_ to do copy.

If we can't control if it moves or copy then we probably should remove the move constructor? I'm not fluent enough in C++11x to say how this works and what works :p

From my googleing the intent of std::move is that the old object should get a proper, uninitialized state.
so
CVariant a("foo");
vector<CVariant> v;
v.push_back(std::move(a));

then a should be null, and a.isNull() == true.
v[0] should be a

I somewhat guess this is not what is happening with the old and that it simply still is the same, and destruction is triggered twice.

**Comment by Paxxi** [comment]
There are no deep copies, that's the whole point, we steal the pointer and no data is copied, that's what makes it cheap.

It's the same design as used in the STL, only difference is that I screwed it up.

**Comment by topfs2** [comment]
Yeah I understand that part, my point was that the moved from needs to have a proper state too. So I guess in the move constructor just set rhs.m_type = VariantTypeNull, and possibly zero m_data, would fix it?

**Comment by topfs2** [comment]
But what I don't understand however is why move is triggered? Did you add a std::move(variant) somewhere, I mostly checked the code from phone so possibly missed it

**Comment by Paxxi** [comment]
The move is triggered because we always call the methods with rvalues temporary objects and rvalues use the move constructor to avoid copying them

**Comment by topfs2** [comment]
Ah OK so a compiler optimisation? Cool cool.

**Comment by Paxxi** [comment]
Ok I'm home and starting to calm down. Been sitting at work seeing the mails come in and the shame has been rising as it's such a stupid mistake.
Sorry to everyone about the tone, especially @topfs2 .

```
CVariant DoStuff(CVariant test)
{
...//does stuff and returns by value
}
std::string str="bla";
CVariant stuff{12};
CVariant result = DoStuff(stuff);
CVariant result2 = DoStuff(CVariant{std::move(str)});
```

Imagine that this is using our CVariant and we'll go through what happens

the first call to DoStuff is called with an lvalue(a named object) and thus the old rules apply, it will create a copy of stuff and pass that into the method. The compiler will then move the resulting object into result when the method returns, it will in most cases avoid the copy as it knows the object will not be used anymore.

First std::move, this method doesn't actually do anything to the variable, what it does is that it changes an lvalue into an rvalue(unnamed object) allowing it to be sent to the move constructor.

What happens in the second call DoStuff is that we first change str to an rvalue(template magic so compile time cost) it gets passed to the move constructor of CVariant that takes a string. Once this is done we have a CVariant that is an rvalue because it's not bound to anything, this will get sent to the move constructor of CVariant that takes a CVariant moving the string pointer. The method then proceeds as in the first one.

Might not be the best at explaining this stuff but hope everyone gets the gist of how it works and why it's efficient to pass around big objects in this manner providing the use case suits it.

**Comment by topfs2** [comment]
Thanks for the explanation, I need to simmer on it a bit I think to fully
understand it all, still new to c++11 :)

BTW to make it clear I did not intend to stress you out, sorry if that
happened. I honestly was only curious on how it worked and had a small idea
of what might have been the cause to the crash. :)

Its alpha software, it needs to break at times otherwise its boring :p

**Comment by Paxxi** [comment]
I can highly recommend effective modern c++ if you like reading books about it, the author has a nice style of explaining things.

**Comment by ksooo** [comment]
@paxxi for me, latest kodi master crashes on every startup! I'm afraid the crash is related to this PR. Crash log: http://paste.ubuntu.com/11850025/

**Comment by MilhouseVH** [comment]
#7464 has fixed the crash for me on Ubuntu.

**Comment by fritsch** [comment]
@ksooo: You are much too late for the party ...

**Pull request merged**
