### PR TITLE
[settings] specifies constants for every setting id

### PR DESCRIPTION
**Pull request by xhaggi**
This will adds a constant for each setting id (currently 312) and use it instead of the hard-coded strings.

@Montellese mind taking a look

### CODE REVIEW

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by xhaggi** [comment]
@Montellese done, and addressed your other comments.

jenkins build this please

**Comment by xhaggi** [comment]
As jenkins is a bit sick I've asked @Paxxi (win) and @mkortstiege (linux) for a compile test
and I've done the compile test on osx. All looks good.

But let's jenkins do another round. 

jenkins build this please.

@Montellese any objections or good to go?

**Comment by Montellese** [comment]
I haven't checked every replacement but should be good. Maybe squash all commits together?

**Comment by xhaggi** [comment]
@Montellese i would say no to squash, because we are able to revert the whole PR or parts of the PR then.

**Comment by Montellese** [comment]
I hightly doubt that you will have to revert something from such a "cosmetic" PR. Maybe you have to fix some bad search & replace but not revert. And I don't see how splitting commits based on the filesystem layout makes reverting a specific issue easier.
But I don't really have a strong opinion on the matter.

**Comment by xhaggi** [comment]
I don't have a strong opinion too, will squash after jenkins finished or not :smile:

**Comment by xhaggi** [comment]
btw i'm a bit lazy after that mass search/replace monkey task.

**Pull request merged**
