### PR TITLE
Add keymap for Nexus Player contextual menu

### PR DESCRIPTION
**Pull request by dhacker29**
There is no menu button on the remote so we use the play/pause button.

### CODE REVIEW

**Comment by dhacker29** [comment]
I pushed this to userdata/keymap and it works as intended. I built a new apk and it is in system/keymap, but I am not sure if that will get installed or not. I need to back up my setting and wipe all data and reinstall the test apk.  But any feedback on what is necessary to have this included is appreciated.

**Comment by mkortstiege** [comment]
While this works, this is modifying the key mapping for all keyboards. Not sure how to do it properly right now though. @opdenkamp should this be handled via peripherals?

**Comment by opdenkamp** [comment]
you can use peripherals to automatically set this keymap if it's got a usb vid/pid that can be detected. if it's not a usb device itself, but if that nexus has some usb device that's only used on the nexus, then you could abuse that device's pid/vid to do this mapping. see https://github.com/xbmc/xbmc/blob/master/system/peripherals.xml#L42 for an example

**Comment by dhacker29** [comment]
It is a bluetooth remote.
04-15 22:12:10.229: W/bt-btif(1223): bta_hh_co_send_hid_info: vendor_id = 0x18d1, product_id = 0x2c42, version= 0x0100,ctry_code=0x00
04-15 22:12:10.229: W/bt-btif(1223): bta_hh_co_send_hid_info: fd = 57, name = [Nexus Remote], dscp_len = 174
Still trying to figure out the whole setup for using peripherals.xml. It seems it needs it's own case defined in Peripherals.cpp and a custom file in devices/peripherals?

**Comment by dhacker29** [comment]
Also the device has no default usb peripherals.  You have to use a USB OTG cable to even connect any usb peripherals.  On the other hand would this affect other devices?  When I connect a keyboard the "c" key still activates contextmenu as expected, but I don't have a multimedia keyboard with a play/pause button.  Still if it works the same as the remote the play/pause should work when actually playing but work as contextmenu when navigating the video menus.

**Comment by opdenkamp** [comment]
looks like it's already got it's own xml file that won't be loaded by default? the only thing peripherals.xml allows you to do is to automatically load this xml.

**Comment by dhacker29** [comment]
I think the concern was that by adding this file it would apply to all keyboards. Can peripherals.xml work for Bluetooth as well as USB?

**Comment by opdenkamp** [comment]
afaik it won't unless the keymap is loaded, but i haven't looked at this code for a long time, so i may be wrong.

there's no detection code for bt. the only way to do this with the current code is to use a usb device that's nexus-only and abuse it's vendor id and product id.

**Comment by mkortstiege** [comment]
I gave it a try and my regular keyboard was remapped. Hence the question how to properly handle it.

**Comment by da-anda** [comment]
@mkortstiege is correct, this also happens on my WETEK device. I tried to fix their implementation by providing the according changes in peripherals.xml and moved the keymap file into the according subfolder. While the keymap was loaded form there as expected, the changes applied for ALL HID devices and not that particular one. Unfortunately our ButtonTranslator is currently not able to differ between device IDs (the device info is not forwarded to it).

**Comment by MartijnKaijser** [comment]
@koying this is obsolete now right?

**Pull request closed without merging**
