### PR TITLE
[pvr] removed two unused dialogs

### PR DESCRIPTION
**Pull request by Jalle19**
Found these two dialogs that aren't used anywhere, it seems like they've never even been implemented.

@opdenkamp for you
@Memphiz can you update the XCode project?

### CODE REVIEW

**Comment by Jalle19** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
All team kodi devs with a macbook pro now shout out loud please. Really - on last devcon where i was attending i saw alot of macbooks ... everyone of you running windows on it or what? :p

**Comment by Memphiz** [comment]
@Jalle19 removing files from xcode is straight forward - just use a text editor and remove the occurences ... you only need me when something has to be added ...

**Comment by Memphiz** [comment]
@Jalle19 also please don't trigger jenkins when you know that there is a pending xcode sync ... its wasted resources imo.

**Comment by Jalle19** [comment]
@Memphiz sorry, you were the first one that came to mind. I'll edit the files myself.

**Comment by ronie** [comment]
wiki updated: http://kodi.wiki/view/TexturePacker

**Comment by Jalle19** [comment]
Started some builds manually

**Comment by Jalle19** [comment]
jenkins build this please

**Comment by opdenkamp** [comment]
jenkins seems to be failing completely now, can't find the job id. one more try: jenkins build this please

**Pull request merged**
