### PR TITLE
[cmake] get_filename_component(... PATH) is deprecated. Use DIRECTORY instead

### PR DESCRIPTION
**Pull request by hudokkow**
## Description

Something I found looking at other stuff.
## Motivation and Context

Modernize get_filename_component() usage.
## How Has This Been Tested?

Not tested at all.
## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

None of the above. ^^
- [X] Code cleanup. Functionality is maintained.
## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by hudokkow** [comment]
jenkins build this please

**Review by fetzerch — APPROVED** [review]
might be a good idea to have a small script in the future that checks the integrity of the buildsystem.

**Comment by hudokkow** [comment]
Yeap! Forgot to check build with addons.
jenkins build this with addons please

**Comment by hudokkow** [comment]
The usual suspects failed on several builds.

**Pull request merged**
