### PR TITLE
fix overlapping subtitles

### PR DESCRIPTION
**Pull request by FernetMenta**
fix trac: http://trac.kodi.tv/ticket/15981

### CODE REVIEW

**Comment by stefansaraev** [comment]
thanks! I could reproduce the bug in livetv (vdr + vnsi) and this fixes it.

jenkins build this please

**Comment by Jalle19** [comment]
Noticed this yesterday as well, I thought it was the broadcasters fault.

+1

**Comment by stefansaraev** [comment]
should this be backported ?

**Comment by FernetMenta** [comment]
I am not 100% certain that it does not break anything. On the other hand it fixes a bug. At least it should be tested properly, whatever this means :) I did sone quick tests with SSA, DVB, and text based subs.

**Pull request merged**
