### PR TITLE
[pvr] some more cleanup and a few minor changes

### PR DESCRIPTION
**Pull request by Jalle19**
@xhaggi @opdenkamp if you could take a look?

If you want to I could separate d7813fd

### CODE REVIEW

**Comment by Jalle19** [comment]
Build failure unrelated.

**Comment by Jalle19** [comment]
jenkins build this please

**Comment by Jalle19** [comment]
@opdenkamp friendly reminder to merge this so I don't have to bother with it anymore

**Comment by opdenkamp** [comment]
@Jalle19 rebase and merge away

**Pull request merged**
