### PR TITLE
[PVR] setting 'Switch to full screen' now supports channel types.

### PR DESCRIPTION
**Pull request by ksooo**
A small improvement that has been requested in the forum: https://forum.kodi.tv/showthread.php?tid=352660

screenshot000
screenshot001

Runtime-tested on macOS, latest master.

@phunkyfish for review?

### CODE REVIEW

**Review by phunkyfish — APPROVED** [review]
Nice 👍 

Assuming Jenkins is happy of course.

**Comment by ksooo** [comment]
Should the settings default value be "TV and radio channels" or "TV channels"?

**Comment by phunkyfish** [comment]
Hmm. I started with thinking as it is now, TV and Radio.

It could be TV and Radio if they have a visualisation enabled and just TV otherwise. But I don’t think that’s possible in settings so would need to add another option.

**Comment by ksooo** [comment]
Okay, let's stick with "TV and radio channels".

**Review by AlwinEsch — APPROVED** [review]

**Pull request merged**
