### PR TITLE
[PVR][json-rpc] Re-introduce broadcast properties 'hastimer', 'hastim…

### PR DESCRIPTION
**Pull request by ksooo**
…errule', 'hasrecording', 'recording' and channel attribute 'isrecording'.

Proper support for these properties got 'lost' during a larger refactoring for Leia. This PR fixes that by reintroducing a proper implementation for:

Broadcast: hastimer, hastimerrule, hasrecording, recording
Channel: isrecording

Runtime-tested on macOS, latest Kodi master, using curl.

This not an API change, just a fix so that correct values for the abovementioned properties will be returned again.
 
@Tolriq fyi
@DaveTBlake fyi, as discussed internally I'd like to backport this to Matrix
@phunkyfish when you find some time for a code review

### CODE REVIEW

**Comment by Tolriq** [comment]
Thanks that explains things I did not understood with isPlayable during my tests.

Does GetBroadcastIsPlayable also works when there's recording or should I also still handle hasrecording and play the recording and not the broadcastid?

**Comment by DaveTBlake** [comment]
> as discussed internally I'd like to backport this to Matrix

Yes, please do backport this internal implementation change (hence patch bump). While we are able to keep the JSON API the same in Matrix and master, making non-breaking changes to both, we will be able to apply any fixes we may need down the road. Once master has gone ahead of Matrix, for a breaking change is made,  we can not.

**Comment by ksooo** [comment]
I added a second commit which introduces the new property 'hasreminder' for 'PVR.Fields.Broadcast' and 'PVR.Details.Broadcast' as requested by @Tolriq . I hope this is acceptable for v19, @DaveTBlake ?

**Comment by phunkyfish** [comment]
jenkins build this please

**Comment by phunkyfish** [comment]
> Thanks that explains things I did not understood with isPlayable during my tests.
> 
> Does GetBroadcastIsPlayable also works when there's recording or should I also still handle hasrecording and play the recording and not the broadcastid?

GetBroadcastIsPlayable is only for archive/catchup so is not related in hasrecordig in any way.

**Comment by ksooo** [comment]
Free BSD Jenkins error is unrelated.

```
17:39:05 ld: error: build/video/jobs/video_jobs.a(VideoLibraryCleaningJob.cpp.o): section header table goes past the end of the file
17:39:06 c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ksooo** [comment]
@DaveTBlake see my previous comment - would the second commit also be acceptable for v19?

**Comment by DaveTBlake** [comment]
>  would the second commit also be acceptable for v19?

Yes I think so, it is a non-breaking change. A little bit more than a fix, but the benifits of keeping the API the same in Matrix makes it worthwhile.

**Review by phunkyfish — APPROVED** [review]
LGTM

**Comment by phunkyfish** [comment]
Jenkins build this please

**Pull request merged**
