### PR TITLE
FIX: [renderer] hide meaningless skips from users

### PR DESCRIPTION
**Pull request by stefansaraev**
skips mean nothing on aml/linux

@FernetMenta is this acceptable?

### CODE REVIEW

**Comment by FernetMenta** [comment]
no, I don't want extra handling for specific codecs in there. if users are scared, block the entire codec screen.

**Comment by FernetMenta** [comment]
btw: why do you think they are meaningless?

**Comment by war59312** [comment]
Is this about fast forwarding and rewinding and showing skips while that occurs?

**Comment by fritsch** [comment]
No it's not.

**Pull request closed without merging**
