### PR TITLE
[PVR] Season/Episode/Year/EpisodeName for Recordings (Scraper+Sort Order improvements)

### PR DESCRIPTION
**Pull request by metaron-uk**
A PVR client can now provide Title, Episode Name, Season, Episode & Year of first airing to PVR core as individual fields. This allows:
1. 'By File' now sorts in episode order. (Very useful if a series was recorded out of sequence)
2. ttvdb scraper now able to match TV Shows directly from the 'Recordings' source
3. Skins can decide where and how EpisodeName / Season / Episode / Year is displayed

**Skin Changes Required**
As 'EpisodeName' is now separate, the recordings list for TV shows makes little sense until it is added back in. Proposed confluence changes are included.

**PVR Client Changes Requried**
No changes to clients are essential other than the include file. Existing behaviour is unaffected.
To see benefits, EpisodeName/season/episode/year information must use the new variables.

**Context**
This PR relies on the changes in PR #7626 which groups several API changes forming API 3.0.0.
This PR should not be merged unless PR #7626 has also been merged.
The necessary supporting API change is contained in commit '[PVR] Add Recording scraper support to API'. If this change is withdrawn from PR #7626 this PR will be closed.

**Known Issues**
Currently IMDB scraper doesn't seem to match 'Year' correctly from the filename for some reason.
Skins will need to be updated for EpisodeName to be displayed.

**Comments**
Please make comments regarding the scraper support/sort order change itself here.
For comments regarding any of the other 3.0.0 API changes, please use #7626
This PR may eventually be subsumed into #7626 for final merge.

### CODE REVIEW

**Comment by metaron-uk** [comment]
@ronie - probably something you need to see as skins are affected
@ksooo , @ryangribble - here's the 'scraper' change I talked about
@Jalle19 @opdenkamp @xhaggi any comments?

**Comment by ksooo** [comment]
Is this just a theoretical use case or is there at least one PVR back-end that can implement this API? For pvr.hts, this will not be possible now as tvheadend does not provide the data.

**Comment by ryangribble** [comment]
In theory wmc does have fields for some of this data although in my country it is never populated. 

I'm not sure if I see the benefit of this simply because I see pvr as a record/watch TV shows for light usage rather than trying to have large collections of series/episodes stored (that's what downloading shows and using the video library in Kodi is for!). But again in my country we have only 20 channels and not good Epg data so I'm not a great example. 

If this does get implemented I can populate whatever fields wmc provides so that any of our users that do get this Epg data from WMC could use this feature

**Comment by metaron-uk** [comment]
Works well here in the UK using tv_grab_uk_rt xmltv feed, with some simple mysql to convert 'syndicatedepisodenumber' into season/episode on my mythtv backend.

I understand mythtv 0.28 (alpha) can also extract season/episode from the EIT over-the air guide in the UK, although I haven't tried it myself yet. I suspect anyone using the schedules direct feed in the US will also get reliable season/episode/year data.

imdb scraping of movies works pretty much out of the box at the moment just using 'title' (although it often picks up the wrong version as 'year' isn't available), but without season/episode in the filename ttvdb can't cope.

I've been running a hack which squeezes this info into 'title' for some time (see http://forum.kodi.tv/showthread.php?tid=228316 ) and using it to build up a library of box sets and movies.

No dubious downloading of copy-protected content required ;-)

Example sorted by 'filename' in recordings:
screenshot015

Example illustrating successful ttvdb scrape of star trek seasons1-3 (for the wife you understand... :-)
screenshot010

**Comment by metaron-uk** [comment]
If anyone with a mythtv backend wants to try this (or any of the other #7626 changes), they can checkout my 'working hack' API3.0.0 branch of the pvr.mythtv addon. 
NB: This PR will need to be re-based against #7626 before compilation as the 'working hack' includes all the upcoming API changes, not just this one.

**Comment by MikeB2013** [comment]
@metaron-uk 
Just confirming season/episode data for UK Freesat DVB-S/S2 (over 200 TV and Radio channels) is extracted from eit (OTA) into program table on mythtv backend 0.28pre. The HD (hdtv) flag is also set where appropriate.

Mike

**Pull request closed without merging**
