### PR TITLE
Only use surface rendering for content > 1080p

### PR DESCRIPTION
**Pull request by razzeee**
This changes behavior for android codec handling.
For content smaller than 800 in width we will use software decoding.

And use surface rendering for anything HD, if wanted by the user.
It builds fine on each platform, http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-All/1259/

Thanks to @fritsch for showing me the ropes.

@mazeyx please test http://mirrors.kodi.tv/test-builds/android/arm/kodi-20160319-24736ff-android-surface-rendering-armeabi-v7a.apk and let us know if it fixes your problem.

### CODE REVIEW

**Comment by Razzeee** [comment]
@FernetMenta

**Comment by mazeyx** [comment]
@Razzeee thanks so much, installing it now will report back soon..

**Comment by mazeyx** [comment]
@Razzeee its fixed zoom but now surface rendering is not working at all for 720 hd content from what i can tell.

**Comment by Razzeee** [comment]
@mazeyx I probably need a log or the size (width x height) of your test files at least

**Comment by mazeyx** [comment]
testing hd is standard 1920x1080 and 1280x720 its as if surface rendering is off even when enabled.

for sd content 720x480 surface rendering is off and working as intended (zoom working properly)

**Comment by Razzeee** [comment]
Well that's by design. As we only use surface for content that is larger than fullHd, can't really tell what's the right thing to do. Will have to wait for someone from the video rendering department to help, I'm out of my comfort zone.

**Comment by mazeyx** [comment]
with koying's build it would use surface rendering for anything HD, all SD would turn off surface rendering. basically anything under height 800 would turn surface rendering off, i think you set it to width.

**Comment by mazeyx** [comment]
maybe @koying can help, his build was definetly using surface rendering for my 720/1080p content i can tell instantly it uses 1/2 the cpu and is alot clearer.

**Comment by mazeyx** [comment]
@Razzeee yeah sorry i just double checked his is doing the same, its basically surface rendering off for anything 1080p or less. so yours is working correctly compared to @koying build, maybe we could turn surface rendering off only for SD stuff and on for HD content that would be better imo, i need koying's opinion on it though. its basically the old SD 4:3 content which you need to zoom, its very rare to get HD 4:3 content.

**Comment by mazeyx** [comment]
@Razzeee please hold of on merging this as without mediacodec (surface) for 720p/1080p HD content the quality is worse using the software decoder (this is why id turn it on/off all the time i was hoping this would illuminate all the switching i been doing as i jump from 4:3 SD (so i can use zoom properly) to 16:9 720p/1080p) if we could get it adjusted so 720/1080p also uses mediacodec (surface) then it would be great, if not id rather leave it as is. i appreciate all your effort and sorry its my bad for not understanding the code properly. :) if it allowed 720p/1080p also then this code is very valuable and fixes all the issues.

**Comment by FernetMenta** [comment]
@Razzeee looks good, thanks

**Comment by da-anda** [comment]
@mazeyx for 1080p/720p hw acceleration is still used, just not surface rendering.

Btw - wasn't there once a limitation on Android that the frame buffer of the UI is only 720p? What happens with 1080p movies rendered in a 720p framebuffer without surface rendering? I assume it's downscaled to 720p as well? Please forgive me if I'm talking nonsense, I only remember something with 720p GUI framebuffer limitations, but I could mix things up.

**Comment by fritsch** [comment]
@mazeyx What you describe does not follow a sane argumentation, e.g. you don't know yourself what you want to have / use.

So in order to not continue into nirvana, do the following:

Post the mediainfo of the files you have problems when used with surface rendering and describe your issue in clear words, which "Does not look as good" is no argument as one does not know the content you are playing.

**Comment by mazeyx** [comment]
@fritsch Im only having issues with 4:3 content as i like to zoom it to fill the screen but for some reason (bravia/android tv limitation i guess) it wont let the image zoom out of the available screen size. causing the image to be squashed. turning off media codec (surface) fixes it. here is a media info of a standard file which has problems.

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 8 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 45mn 50s
Bit rate                                 : 1 228 Kbps
Width                                    : 720 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 4:3
Frame rate mode                          : Constant
Frame rate                               : 23.976 fps
Standard                                 : NTSC
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.148
Stream size                              : 392 MiB (71%)
Writing library                          : x264 core 107
Encoding settings                        : cabac=1 / ref=9 / deblock=1:0:0 / analyse=0x3:0x133 / me=umh / subme=10 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=0 / me_range=64 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=12 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / constrained_intra=0 / bframes=16 / b_pyramid=1 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=240 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=2pass / mbtree=1 / bitrate=1228 / ratetol=1.0 / qcomp=0.60 / qpmin=10 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / aq=1:1.00
Language                                 : English
Default                                  : Yes
Forced                                   : No
Color primaries                          : BT.601 NTSC
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.601
Color range                              : Limited

**Comment by fritsch** [comment]
@mazeyx this problem for sure is solved with the code given here.

The sane approach to @Razzeee fix the aspect ratio thing, if not possible -> disable surface rendering _only_ if the aspect ratio does not match.

**Comment by mazeyx** [comment]
@da-anda i know some hardware rendering is taking place my cpu is around 45% with it, if i disable all hw rendering it jumps to 90%, with media codec surface on aswell it jumps as low as 20%, im not really worried about the cpu load, its more of a quality issue the image looks a lot better with media codec surface on and most the files i watch are 16:9 HD, the problem is i occasionally watch 4:3 content it and it must be off or i cant zoom i got to watch with black sides i hate that :(

**Comment by mazeyx** [comment]
@fritsch yes this code makes it all possible im just hoping we can fine tune it now, ideally aspect ratio would be best 4:3 surface off, everything else surface on, or just set it 720x576 or below surface off, instead of 1920x1080 or below surface off.

**Comment by koying** [comment]
@Razzeee Might be the intent, but this completely disallows surface for anything but 4K, which was not the spirit of the original commit...

**Comment by mazeyx** [comment]
@koying do you think its possible to just disable surface for 4:3 content? you have a bravia dont you? you seen the problems im facing with zoom?

**Comment by fritsch** [comment]
This is not about insane, stupid hacks to fit exactly one usecase ....

```
 if (hints.aspect > 1.32 && hints.aspect < 1.34)
 {
   CLog::Log(LOGINFO, "MediaCodec (Surface) Video Decoder disabled cause of aspect ratio %f...", hints.aspect);
   m_render_surface = false;
 }
```

^^ I don't want to see code like that in Kodi. The HwDecRender if not able to properly implement the features should reconfigure on the fly like e.g. VDPAU / VAAPI /DXVA can do.

**Comment by Razzeee** [comment]
What is the usecase for non surface rendering anyway? Me being a noob in this department asking, don't get emotional :)

I guess the reason 4:3 isn't working for surface, is that the surface isn't "clamped" right. See:
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp#L489 which is not changed at all vs https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp#L1397

**Comment by mazeyx** [comment]
im sorry this has been such a pain for all involved if you just wanna drop this whole idea and run like hell i would totally understand, i basically just don't want things to become worse. surface and 720/1080p 16:9 looks great and works perfect alot better then with it off. i can just continue to do the switch on/off thing when im going to watch 4:3 its all good :(

**Comment by koying** [comment]
4:3 is working on surface, just not on some devices that do not allow the surface to have negative margins, which is how "pseudo-zoom" is done on surface.

Non-surface also has to be used if you want to be able to have a paused video on background. The rendering surface (in surface mode) is destroyed when Kodi loses the focus, so the codec must be destroyed as well => full video stop.

That's notably the case when the system screensaver (daydream) kicks in

**Comment by mazeyx** [comment]
@Razzeee i guess since it only affects some devices unlucky me we should probably close this and leave things as is, unless someone can do that HwDecRender fritsch has suggested. there is also a slight possibility a firmware update to bravia might fix it or even a update from 5.1.1 android to 6.0 marshmallow which should be out some time this year might fix it also since it seems to be device related as koying has suggested.

**Comment by fritsch** [comment]
I am still in favor of getting this fixed once and for all :-) So cudos to
@razzeee for looking into it. Check the negative margins and transform
width / height hints instead - at least try that.

2016-03-20 12:08 GMT+01:00 mazeyx <notifications@github.com>:

> @Razzeee <https://github.com/Razzeee> i guess since it only affects some
> devices unlucky me we should probably close this and leave things as is,
> unless someone can do that HwDecRender fritsch has suggested. there is also
> a slight possibility a firmware update to bravia might fix it or even a
> update from 5.1.1 android to 6.0 marshmallow which should be out some time
> this year might fix it also since it seems to be device related as koying
> has suggested.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/xbmc/pull/9400#issuecomment-198898417>
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by Razzeee** [comment]
Rebased. Add another cleanup commit, that wasn't in this before.

**Comment by Razzeee** [comment]
Is this still needed? Or should I close this PR?

**Comment by NedScott** [comment]
IMO, MC Surface rendering should be off for > 1080 by default (but still using MC-non-surface, which makes it a sane default for most users), but with the option of allowing the user to always enable MC Surface. If I understand correctly, that is how SPMC handles it?

I believe that would address the issues with Surface, while still allowing it to be used in the less-common situations where Surface is better than mediacodec alone.

**Comment by mazeyx** [comment]
the problem with this as it stands is even if you have MC Surface rendering enabled it disables it with no way to have it enabled (i love to use surface rendering for 720p and 1080p, its faster uses less cpu and looks better). imo if there was a option to enable this function which will turn Surface rendering off for content greater then > 1080p this would be alot better. i would then be able to disable that function, i dont really think this is needed tbh anymore. it seems to cause more problems then it solves for me atleast.

btw ive noticed with surface disabled and just using MC non surface is very buggy text seems to jitter and the whole screen gives me a headache i need to have both disabled.

**Comment by MartijnKaijser** [comment]
@mazeyx yeah i noticed it to that's there's a one or two pixel vertical shift frame stutter in non surface MediaCodec.

**Comment by mazeyx** [comment]
@MartijnKaijser it also freezes randomly. not sure when it broke it used to be fine a month or two ago i was messing around the other day after a firmware update and noticed it. these days i just leave surface on and don't zoom 4:3 content and it all works fine.

**Comment by koying** [comment]
The major issues with Surface are:
- You cannot pause a vid and minimize Kodi. The video will be stopped due to Surface constraints. That's also the case with a system screensaver.
- You have zero control on scaling, so forget about HQ scalers
- You basically have zero control on anything, actually ;)

So, for me, the only actual useful use case for Surface is to play 4K with 4K HDMI and 1080p GUI, which is basically how SPMC implemented it...

**Comment by MartijnKaijser** [comment]
@koying i agree with you :)

**Comment by mazeyx** [comment]
well you have the option to disable it completely if you prefer, i kind of like it one of those issues actually fixed another issue i had, i like to use the sleep timer on my tv before the tv would go into standby and video would keep playing until morning when i woke up. now it stops playing which is good :)

**Pull request closed without merging**
