### PR TITLE
renderer: drop frames if there is no consumer

### PR DESCRIPTION
**Pull request by FernetMenta**
fix jam of video frames when i.e. leaving fullscreen with no background video playing

@MartijnKaijser this should fix the issue.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
thx that was quick :)

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
now when i switch to background playback OE crashes
http://sprunge.us/UPSc
Not sure if related but it only happens with situation as described initially with no background playback

**Comment by FernetMenta** [comment]
could you please try with a stropped down version without addons like boblight. ideally not OE because I have no clue what code went in there.

**Comment by MartijnKaijser** [comment]
I could disable boblight. the OE version is build by seo and has very few patches (just bare minimum). I'll see if i get the same on windows though crashlogs there are useless

**Comment by FernetMenta** [comment]
I am at CeBIT and all I have with me is a Windows laptop. If I could reproduce on Windows would be best.

**Comment by FernetMenta** [comment]
ok, I see the problem. will fix it later when I get back

**Pull request merged**
