### PR TITLE
IMX: Several fixes screenshot, deint of progressive, minors

### LINKED ISSUE #4063: Scaler broken in 5.0.7
OpenElec 5.0.7
Cubox i 4pro

Playing anamorphic dvd (720x480) with 16x9 PAR produces ugly shear scaling on 5.0.7. Works correctly on 5.0.6

### PR DESCRIPTION
**Pull request by fritsch**
This should fix: https://github.com/OpenELEC/OpenELEC.tv/issues/4063 the var was used in Config() without proper initialization. With bad luck we would enable Deinterlacing by default.

### CODE REVIEW

**Comment by fritsch** [comment]
@smallint @wolfgar  as the flag handling has grown a bit wild (RenderGLES, IMXVideo and so on) - thx much

**Comment by smallint** [comment]
The member initialization should not be necessary since it is set explicitly in https://github.com/fritsch/xbmc/blob/imx-fixes/xbmc/cores/VideoRenderers/LinuxRendererGLES.cpp#L616 before the BlitAsync call. So the rendering must not rely on preset or constructed values. If it does it is a bug. Another issue could be a wrong positive when checking for interlaced content. Haven't checked the sample though ...

**Comment by fritsch** [comment]
It's read before it is set, here: https://github.com/fritsch/xbmc/blob/imx-fixes/xbmc/cores/dvdplayer/DVDCodecs/Video/DVDVideoCodecIMX.cpp#L1515

**Comment by wolfgar** [comment]
Hi, I am unsure it is really the root cause of the issue.
I agree that it is conceptually better to initialize the attribute but anyway at the end, It is supposed to be properly set before rendering first picture.
It is true that it was tested while uninitialized but even in this case, I fear that both paths ended with good configuration: I mean if initial value (random as non uninitialized value ) was
-  the same as the one we try to set then configure will be called properly by BlitAsync call (which calls PrepareTask which calls Configure for the first time with correct  deinterlacing value, at least the same one which was passed as parameter to  SetDeInterlacing)
- not the same as the one we try to set then configure will be immediately called (before first call to BlitAsync) but it seems just fine too
At the end, whatever path we take, Configure which configures the framebuffer is called with the parameter passed to SetDeInterlacing
I fully agree that the issue seems related to deinterlacing being automatically set while it should not but I fear the issue is likely that we pass wrong parameter when we call  SetDeInterlacing...
Let me investigate a few minutes about it...

**Comment by wolfgar** [comment]
I have digged the issue
So I confirm again the issue with the flag value (and/or our use) passed to the CLinuxRendererGLES::RenderUpdateVideo
With the sample which exhibits the issue, flags always has value 0x2 (which is RENDER_FLAG_TOP set) and we consider that is RENDER_FLAG_TOP or RENDER_FLAG_BOT is set then we have an interlaced stream hence the issue..

**Comment by smallint** [comment]
Thanks @wolfgar. To summarize: the video is probed as interlaced because m_initInfo.nInterlace != 0, correct? There should be a debug log containing "VPU Init Stream Info :" which also logs the detected interlaced state.

**Comment by fritsch** [comment]
@smallint @wolfgar I might still be tired, but please have a look in GetPicture Method of IMX code. there is code to do, e.g.
```
  pDvdVideoPicture->iFlags = DVP_FLAG_ALLOCATED;
  if (m_dropState)
    pDvdVideoPicture->iFlags |= DVP_FLAG_DROPPED;
  else
    pDvdVideoPicture->iFlags &= ~DVP_FLAG_DROPPED;

  if (m_initInfo.nInterlace)
    pDvdVideoPicture->iFlags |= DVP_FLAG_INTERLACED;
  else
    pDvdVideoPicture->iFlags &= ~DVP_FLAG_INTERLACED;

  if (m_currentBuffer->GetFieldType() != VPU_FIELD_BOTTOM && m_currentBuffer->GetFieldType() != VPU_FIELD_BT)
    pDvdVideoPicture->iFlags |= DVP_FLAG_TOP_FIELD_FIRST;
  else
    pDvdVideoPicture->iFlags &= ~DVP_FLAG_TOP_FIELD_FIRST;
```

Especially the "else" cases are fully wrong in my eyes. That will negate _all_ the bits and then and it on our flags, which will do something not useful. Additionally DVP_FLAG_TOP_FIELD_FIRST is set, no matter of: DVP_FLAG_INTERLACED

**Comment by fritsch** [comment]
Good, one coffee later :-) the else cases are fine, I think our problem is, that we set DVP_FLAG_TOP_FIELD_FIRST everytime, when we don't receive a FIELD_BOTTOM and no FIELD_BT, but progressive should be VPU_FIELD_NONE or something -> therefore the player always gets DVP_FLAG_TOP_FIELD_FIRST set.

This should help:
```
From 6ac9c00574643247760b7d08d55f6268a6f09ba5 Mon Sep 17 00:00:00 2001
From: fritsch <Peter.Fruehberger@gmail.com>
Date: Mon, 6 Apr 2015 09:08:36 +0200
Subject: [PATCH] IMX: squash me

---
 xbmc/cores/dvdplayer/DVDCodecs/Video/DVDVideoCodecIMX.cpp | 7 +++++--
 1 file changed, 5 insertions(+), 2 deletions(-)

diff --git a/xbmc/cores/dvdplayer/DVDCodecs/Video/DVDVideoCodecIMX.cpp b/xbmc/cores/dvdplayer/DVDCodecs/Video/DVDVideoCodecIMX.cpp
index 73cd25a..6b44de0 100644
--- a/xbmc/cores/dvdplayer/DVDCodecs/Video/DVDVideoCodecIMX.cpp
+++ b/xbmc/cores/dvdplayer/DVDCodecs/Video/DVDVideoCodecIMX.cpp
@@ -1078,8 +1078,11 @@ bool CDVDVideoCodecIMX::GetPicture(DVDVideoPicture* pDvdVideoPicture)
   else
     pDvdVideoPicture->iFlags &= ~DVP_FLAG_INTERLACED;
 
-  if (m_currentBuffer->GetFieldType() != VPU_FIELD_BOTTOM && m_currentBuffer->GetFieldType() != VPU_FIELD_BT)
-    pDvdVideoPicture->iFlags |= DVP_FLAG_TOP_FIELD_FIRST;
+  if (m_initInfo.nInterlace)
+  {
+    if (m_currentBuffer->GetFieldType() != VPU_FIELD_BOTTOM && m_currentBuffer->GetFieldType() != VPU_FIELD_BT)
+      pDvdVideoPicture->iFlags |= DVP_FLAG_TOP_FIELD_FIRST;
+  }
   else
     pDvdVideoPicture->iFlags &= ~DVP_FLAG_TOP_FIELD_FIRST;
 
-- 
1.9.1
```

Cause, the player would "mark this frame" as FS_TOP if DVP_FLAG_TOP_FIELD_FIRST is set

**Comment by fritsch** [comment]
After second coffee, @smallint is right:
```
07:33:56 T:1698690080   DEBUG: Decode - VPU Init Stream Info : 720x480 (interlaced : 1 - Minframe : 4) - Align : 1 bytes - crop : 0 0 720 480 - Q16Ratio : 12f68
```

Player detects it the same:
```
ReadEditDecisionLists - Assuming NTSC or 60i interlaced content. Adjusted frames per second from 59.940 (~59.940 fps) to 29.970
```

so - yeah, broken file?

**Comment by smallint** [comment]
Good question, I also had one of those files. Probably you can apply some heuristics to detect those but is that stable and maintainable? Are you sure that there won't be 720x480 interlaced content? The player writes "assuming", are information missing to base decisions on?

**Comment by fritsch** [comment]
Sadly no ... see: http://en.wikipedia.org/wiki/Standard-definition_television there is such content.

Perhaps we should decode the first picture and see if it's neither TOP or Bottom but field none and then disable deinterlacing?

**Comment by fritsch** [comment]
The only idea I really have, is checking if we get some VPU_FIELD_NONE and don't deinterlace if we find that.

**Comment by smallint** [comment]
I found during testing that the field type is quite unstable. Since we have always two fields in one picture it seems that the field type is somehow broken. The only "reliable" source was nDeinterlace. You can try it, though. IIRC Sky streams behave similar.

**Comment by fritsch** [comment]
Next I would just check for frame in render and call SetDeinterlace false
... But if not reliable... we have a problem never the less.

Will push when train is home.
Am 06.04.2015 11:24 schrieb "smallint" <notifications@github.com>:

**Comment by fritsch** [comment]
Added another bit for screenshot. @smallint overlays are not shown, but the screenshot stops looking distorted. I did not understand why the non RGB buffer would be memcpyied, this did not make much sense, typo?

**Comment by fritsch** [comment]
@smallint @wolfgar please have a look at Screenshot v3 also - we expect BGRA, the non RGB path was correct already before, but the simple memcpy needs a byte swap.

The comparison was also a typo I think.

**Comment by wolfgar** [comment]
hi peter,
yes of course, you are definitively right for screenshot, sorry for it it is likely my mistake...

**Comment by fritsch** [comment]
@wolfgar nothing to sorry - we are a team :-) I failed to review properly.

What do you two think of the interlacing changes? We want to wait for the user's feedback?

**Comment by wolfgar** [comment]
I think your patch makes perfect sense but, like smallint, I remember that in the past we concluded that the field type was not so reliable. So even if conceptually just fine, I fear we are not done with this automatic (de)interlacing status...

**Comment by smallint** [comment]
> What do you two think of the interlacing changes?

Conceptually I don't like to push VPU field checks to the Renderer. Shouldn't that be done in the decoder which should use the available enums and populate the correct fields? Can't that be done in GetPicture?

If the provided sample works and does not break others then the fix itself is fine, my comment is just about conceptual things. The i.MX code is already complicated enough ;)

**Comment by smallint** [comment]
I noticed that I said the exact opposite of wolfgar ;) I agree with him on the weak value of the field type reported by the VPU wrapper.

**Comment by wolfgar** [comment]
@smallint : I don't think we really disagree. My though was only that I fully understand the additional check spirit.
I have not stated I prefer this check in the renderer or in GetPicture : I simply had not though enough about it. Your remark makes sense : moving this additional check in GetPicture is likely a little better as it is the place where we know you have all our imx tweaks but not a big deal for me it it remains as it is ;)
My main worry is clearly that it may just introduce more issues than it solves because the field type has proven to be often wrong if our memories are good...

**Comment by fritsch** [comment]
Yes, fully the same oppinion. But the concept is already flawed as the buffer and its fields are already checked in render. The SetDeinterlacing is also directly called from there on the imx context.

@smallint: Force pushed and now doing the sanity check in Codec

**Comment by wolfgar** [comment]
@fritsch that's very true and that's why I have not said we should not do this but that I fully agree with the spirit of the patch ;) (I clearly hope this combination will be good enough but  I wanted to mean that I am not 100% sure...)

**Comment by fritsch** [comment]
Do we want a m_warnOnce warning in the Decoder and print a Warning, so that user can be suggested to Force Deinterlacing for this kind of "broken" videos?

**Comment by smallint** [comment]
A warning in the log is very helpful since users may not have debug enabled when posting logs. Is it possible to popup a window in the GUI once? Another question: this particular issue is not i.MX6 related, is it? It should affect all other codecs that support deinterlacing = auto?!

**Comment by fritsch** [comment]
On my VAAPI system it is detected correctly. I think it's the vpu-wrapper that detects this file in a wrong and afterwards sets deinterlace to true where we rely on. AUTO ist btw. default on all systems.

Concerning GUI message: I would not do that - normal users should not be bothered. Btw. those that realize could enable Deinterlace to On, if they actually see it.

LOGWARNING is printed in every logfile. Let me add a member and we print if that happens.

**Comment by smallint** [comment]
Hmm, then either VPU wrapper or the VPU itself produces the issue. As a side note: I was thinking of using the VPU lib directly without libvpuwrapper which is more or less an abstraction layer to workaround i.MX specific issues/bugs. Bypassing it means more control but probably also more work initially. If you have ever checked the libvpuwrapper source you understand what I am talking about. ;) Just to keep in mind that we still have options ...

**Comment by fritsch** [comment]
@smallint I know exactly what you mean :-) I looked into that during easter to spot a bug or two - not nice at all, hacky is a nice word.

I added a log.

Btw. I see two options:

a) I remove that "auto disabling" and only print that warning? That way user can see the issue and disable Deinterlacing for that file?
b) We keep it in

You two decide. I am open for every

**Comment by wolfgar** [comment]
Hi Guys,
I would vote for b. option
But I would also vote for dropping libvpuwrapper : we also have one or two hacks left only because of this additional and not so nice layer. (and several times only way to fully understand a strange issue was to check what libvpu outputs were...)
I would consider using https://github.com/Freescale/libimxvpuapi : in fact I wanted to give it a try a few months ago but it was exactly the moment when I issued the PR to upstream imx6 support so it was not the best time to change a sensitive piece and deal with a few regressions...

**Comment by fritsch** [comment]
@wolfgar thx for that feedback. I will try to help when we go the libimxvpuapi road. Will wait for @smallint's response. In the meantime, let's see if we have broken other platforms:

jenkins build this please

**Comment by smallint** [comment]
If "We keep it in" means that you just log the problem and keep deinterlacing active I vote for a). Not to disagree with @wolfgar but for usability reasons (my opinion): if a progressive stream is rendered with deinterlacing it is hard for a user to realize that the deinterlacing settings are wrong. The image is just blurry and they complain about bad rendering. But if an interlaced stream is rendered progressive, users will notice that and forcing deinterlacing is an option that users can handle more easily.

**Comment by wolfgar** [comment]
@smallint:
Sorry but I don't have the same understanding of the options as you
To me b option is  : we automatically disable and we don't only issue a warning (which is a option)
you seem to propose another way which is we default to no deinterlacing instead of automatic, is it your proposal ?

**Comment by fritsch** [comment]
@smallint: I slightly disagree, while you are right with 
> if a progressive stream is rendered with deinterlacing it is hard for a user to realize that the deinterlacing settings are wrong.

-> this would be "fixed" with b) as it is not deinterlaced anymore

>But if an interlaced stream is rendered progressive, users will notice that and forcing deinterlacing is an option that users can handle more easily.

-> same oppinion, that would also be fixed in b)

Now I am a bit confued :-) I understand them inverted.

**Comment by fritsch** [comment]
@wolfgar yeah, as you think it - I intended it :-)

**Comment by smallint** [comment]
Cool, then b) Sorry for confusion then ...

**Comment by fritsch** [comment]
@FernetMenta @MartijnKaijser we'd like to have those changes in v15 please.

**Comment by smallint** [comment]
@fritsch The fix breaks automatic deinterlacing on ServusTV. You can check it with your mbaff sample. Since Kodi saves the settings per channel (right?) you will have to switch back to auto if progressive content is played (for whatever reason) on the same channel. Another +1 for testing with libimxvpuapi.

**Comment by fritsch** [comment]
@smallint: so let's go only for warning users? I will adjust the patch. One moment.

**Comment by fritsch** [comment]
Servus TV mixes the content, which btw. Pro7 also does sometimes ... so yeah, let's only warn. If you are okay, I squash that onto the other.

**Comment by smallint** [comment]
@fritsch Warning users is in any case very helpful and I think breaking an active broadcast stream is worse than some example sample.

**Comment by smallint** [comment]
> If you are okay, I squash that onto the other.

I am.

**Comment by fritsch** [comment]
jenkins build this please (let's see if we broke something)

**Comment by fritsch** [comment]
I added another patch, back to: 50c9823 which blacklisted all profiles. There are quite a lot samples out there with profile 31 that work just fine. 

Here is the old non working sample: https://dl.dropboxusercontent.com/u/55728161/sample.mp4
Another sample, same 578 but level 31: https://dl.dropboxusercontent.com/u/55728161/avc1.mp4 which would not work on the CPU alone.

**Comment by fritsch** [comment]
Added another commit to not open > 1920 in width, as of: http://hands.com/~lkcl/eoma/iMX6/VPU_API_RM_L3.0.35_1.1.0.pdf

**Pull request merged**
