### PR TITLE
[GUI] remove "Add source" from MyPrograms section

### PR DESCRIPTION
**Pull request by phil65**
This removes the "Add source" list entry for MyPrograms root.
I dont think that it is of any use atm. Or can it be used to somehow launch APKs on Android, @koying ?

@mkortstiege for review.

### CODE REVIEW

**Comment by koying** [comment]
Well, it's even displayed, afaict.
So this does some cleanup, but I don't think it has any practical effect...

**Comment by ronie** [comment]
afaik it's only ever been used for xbox apps/games.
http://kodi.wiki/index.php?title=Archive:Programs_xBox&oldid=4290

**Comment by koying** [comment]
Ah, worth asking @garbear if he intents to re-use this, then...

**Comment by phil65** [comment]
> Well, it's not even displayed, afaict.

It gets displayed, but not all skins have a shortcut to MyPrograms root. So this also has a "practical" effect.

**Comment by koying** [comment]
Ah, right, had to go 1 level above.
You probably should also remove ```m_vecItems->IsPath("sources://programs/")```, don't you?

**Comment by phil65** [comment]
Right, thanks. Removed that line and updated PR.

**Comment by garbear** [comment]
no conflict here

**Comment by MartijnKaijser** [comment]
ok for me as well

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
