### PR TITLE
dvdplayer: reduce time for initial audio sync

### PR DESCRIPTION
**Pull request by FernetMenta**
after recent improvements for audio sync it should be possible to reduce time for initial sync.

feedback appreciated. does anyone have any sample which brakes?

### CODE REVIEW

**Comment by Jalle19** [comment]
a) there's still a comment that says 500ms, can't make a line comment since I'm on a phone

b) looks like using a constant would make more sense since the same value is used in multiple places.

**Comment by FernetMenta** [comment]
thanks for feedback. 
I hesitated to create a constant in this phase because it still might be useful to have different values for the different stages. for the time being I have chosen the same value for all but it might work better with optimized ones. a constant would imply that it has the same impact for all stages (startup, unstable, stable), right?

**Comment by Jalle19** [comment]
Maybe you're right. There's also the possibility to use an enum with custom int values, but I don't know if that's any better.

**Comment by ace20022** [comment]
I try to test with bd discs over the weekend, there are massive problems with current master. It would be great if you could help me with that.

**Comment by FernetMenta** [comment]
let me know when I can help

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
no negative feedback. in order to get more testers I merge it now

**Pull request merged**
