### PR TITLE
[tvOS][lifecycle] Fix random stuck in busy spinner screen

### LINKED ISSUE #18685: [tvOS] Randomly stuck in busy spinner screen when putting Kodi on foreground
### Describe the bug
Here is a clear and concise description of what the problem is:

Randomly, when you put Kodi on foreground state, Kodi is just stuck on the busy spinner screen. You can't do anything except killing Kodi from tvOS multitask.

This bug happens in multiple situations, this is some cases where I was able to reproduce the bug in a few attempt:
* Put the Apple TV to sleep while watching a Live TV channel on Kodi, wake up the Apple TV --> Stuck on busy spinner screen
* Open Kodi, switch to another app via multitask screen, switch back to Kodi via multitask screen -->  Stuck on busy spinner screen
* Open Kodi, go back to springboard, open Kodi --> Stuck on busy spinner screen

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When putting Kodi on foreground, Kodi should open last played media if any, or just be ready to work.

## Actual Behavior

Randomly, Kodi is just stuck on the busy spinner screen.

## Possible Fix

Don't know yet, need to reproduce the bug while monitoring Kodi with Xcode to understand what causing this race condition issue.

### To Reproduce

1. Open Kodi from the Apple TV springboard
2. Go back to springboard
3. Repeat step 1 and 2 until the bug appear (I can reproduce it with less than 10 attempts)

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

Screen Shot 2020-10-31 at 08 05 16

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: tvOS 13
 - Kodi version: Kodi 19 alpha 2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by sy6sy2**
## Description

It seems that this PR fix #18685 issue.
I am not very sure why. Maybe because I start/stop network in a different order?

@fuzzard and @kambala-decapitator, can you check that I do not break anything here?
I use this version on my daily TV now and I did not notice any problem since.

## Motivation and Context

Fix the random "stuck in busy spinner screen" issue on Apple TV

## How Has This Been Tested?

Daily usage on Apple TV.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by sy6sy2** [comment]
I'm using it since this PR is open. I didn't notice any problem.

**Comment by fuzzard** [comment]
My understanding is you can enable multiple background tasks. This was one of the concepts of returning the backgroundtaskidentifier as a return value (and passing as a message for the endbackgroundtask). Although it wasnt fully fleshed out, i think this is a backwards step in that regard. Tightly binding it to a single task

**Comment by sy6sy2** [comment]
I think to understand what you mean and you are right, in this state my code only allow to start ONE background task at a time.
But as you said, the previous code was in an "hybrid" state where only one background task can be started, this why I modify it in order to dedicate the background take function to the "go to background" lifecycle task.

**Comment by DaveTBlake** [comment]
>  i think this is a backwards step in that regard. 

So where are we with this @sy6sy2 @fuzzard , going to be sorted for Beta 1?

**Comment by sy6sy2** [comment]
I personally want it to be in Kodi 19 because it fix an issue.
I still can apply changes if @fuzzard or @kambala-decapitator want 😉

**Comment by sy6sy2** [comment]
@DaveTBlake this PR can be merged when you want. Fuzzard approved it on Slack.

**Comment by kambala-decapitator** [comment]
I'll have a look tomorrow

**Comment by DaveTBlake** [comment]
@kambala-decapitator any comments, or happy to merge for Beta 1?

**Pull request merged**
