### PR TITLE
[webinterface.default] Update to 21.x-1.0.1

### PR DESCRIPTION
**Pull request by enen92**
## Description
Updates chorus2 for release. The webinterface project got a lot of assorted fixes mainly from @malard.

Runtime tested.

### CODE REVIEW

**Review by neo1973 — APPROVED** [review]

**Comment by enen92** [comment]
@malard found a bug introduced in one of the PRs (see #webinterface on slack). So please refrain from merging yet.

**Comment by malard** [comment]
commit has been made into chorus repo to continue.

**Comment by enen92** [comment]
@malard done in the last release, thanks. It'd be great if you could give it a spin.

**Comment by malard** [comment]
thanks, looks good for me also, i am working on more bug fixes, if someone can handle the release side of this we can smash out a bunch of improvements.

**Comment by enen92** [comment]
We can add the addon to https://github.com/xbmc/repo-webinterfaces and push updates just like any other add-on.

**Comment by malard** [comment]
If we can please make that happen then I can drive through updates on a more frequent basis!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
