### PR TITLE
dvdplayer: do not signal started until output of first frame

### PR DESCRIPTION
**Pull request by FernetMenta**
fix SeekPercent when player is paused, that is seeking by clicking into the progress bar.

@ace20022 @afedchin that should fix the reported issue

### CODE REVIEW

**Comment by ace20022** [comment]
thanks, it seems to work for "normal" files! It doesn't work for blurays (only tested with sintel.iso).
Seeking in paused mode doesn't work at all with (at least one) dvds, i.e., not even the time gets updated and playback resumes at the paused time.

**Comment by ace20022** [comment]
forgot: @Voyager1 is this known for dvds?

**Comment by FernetMenta** [comment]
sintel.iso works nicely here

**Comment by ace20022** [comment]
strange, found another bug with skip steps btw ;)

**Comment by ace20022** [comment]
@Voyager1 ping again

**Comment by Voyager1** [comment]
sorry - didn't see this one - please let me test this and I'll report back.

**Comment by Voyager1** [comment]
The seek from paused state works fine as is with DVDs. How I tested - I used the June 3rd nightly, played an ISO dvd file, enable mouse input, pause playback somewhere. Then click in the progress bar. A seek "amount" (+/-) appears but nothing happens. When I hit pause again, the playback starts from the position I have chosen when clicking in the progress bar.
The fix here is not included in the build, should I test with it?

**Comment by ace20022** [comment]
Yes, please, I can't remember if I tested it with this pr or without.

**Comment by Voyager1** [comment]
@ace20022 - I have now tested, with and without this PR, a few DVD (ISOs) and it seems to work fine, just like I described above.

**Comment by ace20022** [comment]
@Voyager1 thanks
@FernetMenta 
> A seek "amount" (+/-) appears but nothing happens.

Okay, that's the same behaviour I have with blurays and also with dvds. I don't have the one sample (dvd) at hand that didn't work at all.

I vote for merge.

**Comment by MartijnKaijser** [comment]
jenkins build this please
merge if you guys are ok with it

**Comment by ace20022** [comment]
jenkins build this please

**Pull request merged**
