### PR TITLE
fixed: context menu manager mess with profiles

### PR DESCRIPTION
**Pull request by notspiff**
killed e.g. 'mark as watched'.
ref http://forum.kodi.tv/showthread.php?tid=290858

### CODE REVIEW

**Comment by phil65** [comment]
Thx for the fix! this was bugging me too.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by fergalmoran** [comment]
Do we really have to wait until v18 before we see this fix? It's a SERIOUSLY frustrating bug.

**Comment by stefansaraev** [comment]
no need to be angry, it was backported to Krypton branch few hours ago. but you are on github so you should know that already.

**Comment by MartijnKaijser** [comment]
@fergalmoran I would even revert the fix just because of your response!

**Comment by fergalmoran** [comment]
@stefansaraev I'm not angry, I'm just expressing how frustrating the bug is. I hadn't noticed it was backported when I responded.

@MartijnKaijser If you think that's proportionate, fair enough.

**Pull request merged**
