### PR TITLE
fix a few warnings

### PR DESCRIPTION
**Pull request by Montellese**
These 4 commits each fix a warning and the first and last commit probably even a bug.

### CODE REVIEW

**Comment by mkortstiege** [comment]
jenkins build this please.

**Comment by Montellese** [comment]
@AlwinEsch: Could you comment on 3b13248d014b726ae4c86850477264022cff4af4 since you added it in 316dc9f1a6e549fdfc2e971ae03f9c54b7db02bf?
And the same for a6376d3427f9095885f64b92020716ef64937f5d since you added it in 0187ae41afdcde1e28707f0158951950d9595fc0?

**Comment by ksooo** [comment]
This PR breaks #6404. Would be cool if #6404 could be merged first. Much less effort to fix this small PR compared to (huge) #6404. ;-)

**Comment by Montellese** [comment]
You call #6404 huge? I'm waiting for feedback anyway so if you get #6404 in shape and ready soon enough I'll rebase this one.

**Comment by ksooo** [comment]
@Montellese nitpicker. ;-) Replace "huge" with "is rather old, waited for reviewers feedback a long time, had to be rebased again and again and needed to be adapted because of conflicts caused by younger and smaller PRs that got integrated before."

**Comment by Montellese** [comment]
The last commit has been removed as #6404 has been merged which implicitly fixed the same issue.
jenkins build and merge

**Pull request merged**
