### PR TITLE
[xbmc][nfo] Fix garbage in being added in streamdetails

### LINKED ISSUE #16040: Arabic letters not connected when using virtual keyboard
### Describe the bug
Here is a clear and concise description of what the problem is:

There is an issue in the virtual keyboard in kodi when writing in Arabic, Arabic is a compound form language(the letters are connected rather than separated like in Latin), the problem is that the virtual keyboard doesn't connect the letters and instead they are written as isolated letters, the problem doesn't appear when writing using the physical keyboard.
This issue is very old and has been around since Kodi 16 I think  and still no fix
link to old thread that mentions the bug with screenshots:https://forum.kodi.tv/showthread.php?tid=246853
link to trac ticket: https://trac.kodi.tv/ticket/17703

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The letters should be written connected to each other

## Actual Behavior

Arabic letters are isolated

## Possible Fix

This quote from the forum thread linked above may help to find a fix:
> I think the problem here, is that the Arabic keyboard is using the wrong Arabic Unicode block. Instead of using [Arabic Presentation Forms-B](https://en.wikipedia.org/wiki/Arabic_Presentation_Forms-B), it should use the [standard Arabic block](https://en.wikipedia.org/wiki/Arabic_(Unicode_block)).

### To Reproduce

1. open kodi and go to the interface settings and add the Arabic QWERTY keyboard layout
2. go back to the home kodi page and click on the search icon and choose any type of search
3. change the layout to Arabic in the virtual keyboard and try writing an arabic word like "اللغه العربيه"

### Debuglog

The debuglog can be found here:
not applicable since the problem doesn't produce any debug log entries

### Screenshots 
Here are some links or screenshots to help explain the problem:

- This is what it looks like when writing "اللغه العربيه" using virtual keyboard (signifies the problem):
https://i.imgur.com/xUJxlgLl.png
- This is what it looks when writing the same words using the physical keyboard(this is the correct form): 
https://i.imgur.com/XzIDAell.png

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by Paxxi**
make sure that we don't set values when there was no node, we have no idea what will be in value if that happens. closes #16040

### CODE REVIEW

**Comment by xhaggi** [comment]
meh my mistake but this will also introduces issues in all cases where value is re-used without a clear before.

https://github.com/Paxxi/xbmc/blob/stereomode/xbmc/video/VideoInfoTag.cpp#L573

if the element doesn't exists, we re-use the value from the previous element.

**Comment by xhaggi** [comment]
should we introduce the convenience method you had in mind `std::string XMLUtils::GetString(const TiXmlNode* pRootNode, const char* strTag);` and return an empty string if element does not exists?

**Comment by Paxxi** [comment]
@xhaggi I think that would be a good idea, otherwise we would probably need to wrap every call in an if statement

**Comment by xhaggi** [comment]
looks good, squash everything together and we are ready to go

**Comment by xhaggi** [comment]
@MartijnKaijser this should be go in beta2

**Comment by arnova** [comment]
Changing XMLUtils like this is really dangerous. This broke stuff before in the past since it's used in so many places. Can't this be fixed so that we're sure other places act the same as before? Perhaps with an additional default argument?

**Comment by xhaggi** [comment]
you are right if the passed value should not be cleared if the element won't exists e.g. set a default, pass the value in and if element does not exists use the default.   As you said we should add a new method with a default parameter and call this method with the value parameter. in our change we pass an empty string as default.

**Comment by arnova** [comment]
Right: so either just check the return value of getstring in places where it matters or pass a default value in case it doesn't not exit (which defaults to "" obviously, but that would require checking/changing ALL uses all over the place). I think for now the first option would be the easiest and safest.

**Comment by xhaggi** [comment]
we should use something like this http://pastebin.com/05R6LnYF

**Comment by Paxxi** [comment]
jenkins build and merge please

**Comment by Paxxi** [comment]
ok this should fix the issue that popped up where titles and many other fields being set to blank during library scanning. Left the convenience GetString in there but it's not used.

jenkins build this please

**Comment by Paxxi** [comment]
@xhaggi when you have time, have a look at this :)

**Comment by arnova** [comment]
I'm fine with the proposed new overload function, although I still prefer just checking the return value of getstring. It returns bool for a reason: it allows the caller to check whether it actually did something, so it should be fairly simply to use that to fix the original issue ;-) But again, if the majority supports the overload function, I can live with that. Preventing regressions is the most important thing...

**Comment by Paxxi** [comment]
@arnova the overload isn't used, the original one is used checking return values for every call. I left the overload in there as it might be useful and I already documented it :)

**Comment by xhaggi** [comment]
@Paxxi looks good thanks

**Comment by arnova** [comment]
@paxxi: Excellent, then it's exactly what I had in mind. thanks a bunch :-)

**Comment by justinkb** [comment]
Leaving copy of comment I placed at closed issue #7231 here, in case they might have been overlooked otherwise:

> Think this broke tvdb scraping (well, not the actual scraping but the processing of the xml data?) in some way... Getting blank titles on refreshing show information. Kind of a showstopping bug. I'd suggest reverting this for now at least...

> Looking at @Forage comment and link this seems to be a similar, if not completely identical, issue as his

Long story short, this mucking around in XMLUtils and VideoDatabase seems to have broken some important stuff

**Comment by MartijnKaijser** [comment]
@justinkb use the forum!
"it's broken" is an unacceptable bug report.

**Comment by justinkb** [comment]
@MartijnKaijser You didn't get past the third word of the quote? "Getting blank titles on refreshing show information" seems to be perfectly valid bug report in order to be reproducable

**Comment by MartijnKaijser** [comment]
no it's not. what are you using? NFO, normal scrapers, what version, what platform?
All info is missing that makes it useful.

**Comment by justinkb** [comment]
> TVDB Scraper 1.8.1
> Kodi (15.0-BETA2 Git:2015-06-13-ddebe6d-dirty) <- note that revision
> Platform: Linux x86 64-bit

Specific scraper seems to be inconsequential, however, since it also happens with themoviedb scraper as @Forage reported in the forum post referred to in my quote

**Comment by MartijnKaijser** [comment]
@justinkb i said FORUM not github!

**Comment by justinkb** [comment]
This is tiresome and not worth my time. I'll fix it myself if it comes to it. Cheers

**Pull request merged**
