### PR TITLE
[Fix] Reworked TrueHD MAT packer to support high bitrate Atmos streams (fix audio dropouts)

### PR DESCRIPTION
**Pull request by thexai**
## Description
Backport of https://github.com/xbmc/xbmc/pull/20339

## What is the effect on users?
Fixes audio dropouts playing high bitrate TrueHD Atmos streams on all platforms.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by fritsch — APPROVED** [review]
We make progress here. Let's not stop it. If anyone disagrees: Git has a revert option, no offense.

**Comment by KarellenX** [comment]
@thexai 

Do you think that a similar fix is required for DTS-MA
https://paste.kodi.tv/etebecohav.kodi

**Comment by thexai** [comment]
I do not see that it can have any relationship. This is exclusive to TrueHD.

DTS-MA works fine as is.

Or do you mean the crash is from this PR is merged only?

**Comment by KarellenX** [comment]
What I am saying is that DTS-MA also has problems which, to me as a noob, sounds similar to the problem described in this PR for TrueHD.

In my log you can see all the errors, so I was asking if a similar fix should also be made to DTS-MA. 
I have no issue with this PR and fix, just wanted to highlight that DTS-MA may have similar problems

**Comment by thexai** [comment]
> What I am saying is that DTS-MA also has problems which, to me as a noob, sounds similar to the problem described in this PR

This PR fixes audio dropouts only.

DTS-MA has also dropouts?
Is generic and affects all platforms?
Is there an issue open for 3 years too?

If the responses are NO then is not the same/similar problem 😀

**Comment by KarellenX** [comment]
>Is there an issue open for 3 years too?

Not its own issue report, but I piggy backed onto an existing issue
https://github.com/xbmc/xbmc/issues/16096#issuecomment-500176001

Did you look at my above log and see all the errors?

**Comment by thexai** [comment]
Surely it has nothing to do with it. What you comment looks like a crash in driver. I'm sorry but I can't help you on this right now.

It's probably worth opening a specific issue with more complete information. Also log posted seems cutted/edited (missing important HW info).

**Pull request merged**
