### PR TITLE
[addons][Estuary][cores][guilib][PVR] PVR Add-on API 9.2.0 (multiple concurrent recording streams, title extra information)

### PR DESCRIPTION
**Pull request by ksooo**
This PR adds new features to the PVR Add-on API, implements the needed changes in Kodi and Estuary.

1) Allow multiple concurrent recording streams and use this feature to automatically extract thumbnails for PVR recordings.

Screenshot_2024-10-22_at_08_03_46

2) Add support for extra information text supplied by many EPG providers to give more details for programme entries.

Screenshot 2024-10-22 at 08 08 20

**New GUI labels:** ListItem.TitleExtraInfo, VideoPlayer.TitleExtraInfo

And being an incompatible API bump, PR cleans up code that ensured compatibility with former API versions 9.0.1 and 9.1.0. 

Reference implementation will be made available for pvr.hts very soon as well as PRs to update all other PVR add-ons which are available in Kodi Add.on Repo.

Carefully runtime-tested on macOS, latest kodi master with different combinations of pvr add-ons.

@phunkyfish code changes are best reviewed commit by commit. I tried to logically separate them.
@jjd-uk could you please check the skin changes?

### CODE REVIEW

**Review by Jalle19 — APPROVED** [review]

**Review by phunkyfish — APPROVED** [review]

**Comment by ksooo** [comment]
Headsup: As I will be short on Kodi time from next week on I want to merge this PR this weekend. Two devs already approved the code changes. Skin changes are trivial. So, if anybody has some feedback, now this would be the right time.

**Comment by ksooo** [comment]
> would it be possible to not request thumbnail extraction when the recording sizeinBytes is zero.

This would be something best to be implemented by @rmrector I guess. Nothing for this PR, as more a general request, not something special for recordings.

**Comment by ksooo** [comment]
Any video file regardless of the form it is represented in Kodi can be empty. How often this actually happens is not of real interest. So this case should be handled for all video files at the generic stream layer we have in Kodi, which is used for thumb extraction.

**Comment by emveepee** [comment]
I have implemented multistream so that part is working as expected.  In pvr.nextpvr failed recordings get placed in a separate directory structure,  users know what to expect, thumbnails are ignorant of the fact the file might not exist if the backend was offline (not even zero bytes).  The null case is definitely not what you expect in a filesystem.

**Comment by ksooo** [comment]
If you say so...

**Review by jjd-uk — APPROVED** [review]
LGTM

**Pull request merged**
