### PR TITLE
[depends] bump libandroidjni for CJNIDisplayManager::unregisterDisplayManager fix.

### PR DESCRIPTION
**Pull request by ksooo**
See https://github.com/xbmc/libandroidjni/pull/29 - already merged by @fuzzard

### CODE REVIEW

**Comment by fuzzard** [comment]
I'll ping @glennguy because this also brings in https://github.com/xbmc/libandroidjni/pull/28 for him.

**Review by fuzzard — APPROVED** [review]

**Comment by CastagnaIT** [comment]
it would be opportune if we could also combine with #20915 PR that is still i awaiting

**Comment by fuzzard** [comment]
no need to combine. Once this merges, the libandroidjni lib will have the commits for that PR. Rebase it and then review/test is all you would need.

**Comment by glennguy** [comment]
Sorry I've been dragging my feet on that one, just need to co-ordinate the other binary add-ons for a release after merge

**Comment by ksooo** [comment]
I don't get it. Are there any blockers for this PR. If yes, which?

**Comment by fuzzard** [comment]
No there is not, merge when you are ready

**Review by garbear — APPROVED** [review]

**Pull request merged**
