### PR TITLE
Allow internetstream video sources in a LAN to look for exernal subtitle files.

### PR DESCRIPTION
**Pull request by snaunton**
## Description

internetstream video sources (http, ftp etc) do not automatically look for subtitle files. This fix allows for internetstream video sources which are on a local LAN to look for subtitle files automatically. This is particularly important for forced external subtitle files.

internetstream video sources (http, ftp etc) do not automatically look for subtitle files. This fix allows for internetstream video sources which are on a local LAN to look for subtitle files automatically. This is particularly important for forced external subtitle files.

## Motivation and Context

Allows for internetstream video sources which are on a local LAN to look for subtitle files automatically

## How Has This Been Tested?

Recompiled with changed code. Version with changed code finds subtitle files for videos as per wiki - https://kodi.wiki/view/Subtitles#Manually_downloaded_external_subtitle_files.
Standard version without changed code does not.

Arch linux.
Version with changed code finds subtitle files for videos as per wiki - https://kodi.wiki/view/Subtitles#Manually_downloaded_external_subtitle_files.
Standard version without changed code does not.

It does not appear to.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [X ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by arnova** [comment]
Looks good to me. Please remove the merge commit from this PR.

**Comment by snaunton** [comment]
Have removed merge commit.

**Comment by lrusak** [comment]
jenkins build this please

**Comment by arnova** [comment]
jenkins build this please

**Pull request merged**
