### PR TITLE
[jenkins] unify linux buildsteps

### PR DESCRIPTION
**Pull request by lrusak**
I've been playing with the idea of having a single parameterized build job for linux builds in jenkins.

after #18655 we are able to have one job for both gl and gles x86_64 builds. I would like to go a step further and make it configurable for the arch as well. This reduces the maintenance of jobs from (possibly) 6 jobs (x86, arm, aarch64, gles and gl for both) down to just 1.

This is a good time to make this change as it's unlikely that Leia will have any more updates and this PR will break leia builds for linux (without changes). This PR will also break jenkins without changes but at least I won't have to ifdef them.

I'm not sure what the downsides are to doing this or why it wasn't done like this in the first place. Thoughts?

Here is what the proposed changes look like:

### CODE REVIEW

**Review by wsnipex — APPROVED** [review]
looks good to me

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Pull request merged**
