### PR TITLE
CSMBDirectory: fix return value for smbc_getxattr 

### LINKED ISSUE #22684: Strange error messages for remote directories via Samba
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm running LibreELEC master which builds Kodi with Samba 4.17.5  since a couple days ago.
I noticed strange errors in kodi.log when accessing files from my NAS via Samba:
```
2023-02-02 18:22:41.039 T:1091    error <general>: Getting extended attributes for the share: 'smb://nas/videos/TV%20Shows/Doctor%20Who'
                                                   unix_err:'5f' error: 'Operation not supported' return: 0
2023-02-02 18:22:41.044 T:1091    error <general>: Getting extended attributes for the share: 'smb://nas/videos/TV%20Shows/Frieden%20(2020)'
                                                   unix_err:'4b' error: 'Value too large for defined data type' return: 0
2023-02-02 18:22:41.048 T:1091    error <general>: Getting extended attributes for the share: 'smb://nas/videos/TV%20Shows/Mum'
                                                   unix_err:'4b' error: 'Value too large for defined data type' return: 0
2023-02-02 18:22:41.053 T:1091    error <general>: Getting extended attributes for the share: 'smb://nas/videos/TV%20Shows/Borgen'
                                                   unix_err:'4b' error: 'Value too large for defined data type' return: 0
```
The NAS is running recent Linux and Samba, there is nothing suspicious for these directories.

## Expected Behavior
No such messages :)

## Possible Fix
These messages originate from https://github.com/xbmc/xbmc/blob/1b98faae545f30433bd3c4f07ba87a056821c416/xbmc/platform/posix/filesystem/SMBDirectory.cpp#L172-L184
There, the return value from smbc_getxattr is supposed to be > 0 if successful (contrary to the documentation: 0 on success and -1 on failure). I tweaked the error message to show the actual return value, shown above as `return:....`: it's always 0.

But in latest Samba (4.17.5), the return value was fixed to align with the documentation, see https://www.samba.org/samba/history/samba-4.17.5.html and https://bugzilla.samba.org/show_bug.cgi?id=14808

Possible fix: change the condition
```
if (smbc_getxattr(strFullName.c_str(), "system.dos_attr.mode", value, sizeof(value)) > 0)
```
to  `... == 0`,  though `... >= 0` should be OK and work for older versions of Samba, too.

### To Reproduce
1. Videos -> Media sources 
2. Browse some sources residing on smb://nas/...

### Debuglog
The debuglog can be found here: http://ix.io/4mZh

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 11 beta1
 - Kodi version: Nexus rc1

### PR DESCRIPTION
**Pull request by rschupp**
## Description

Accommodate both old erroneous and correct return values from  smbc_getxattr.

Previously the return value from `smbc_getxattr` is supposed to be > 0 if successful (contrary to the documentation: 0 on success and -1 on failure). But in Samba 4.17.5, the return value was fixed to align with the documentation, see https://www.samba.org/samba/history/samba-4.17.5.html and https://bugzilla.samba.org/show_bug.cgi?id=14808

## Motivation and context
With Kodi built with Samba 4.17.5 browsing Samba directories results in strange error messages, see #22684

## How has this been tested?
Tested on LibreELEC master on RPi4.

## What is the effect on users?
The change makes the erroneous messages disappear.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
Can you please update the PR title and the commit message to something more relevant.

**Comment by CastagnaIT** [comment]
just a fast read on PR guidelines https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md#pull-request-guidelines
avoid links on PR and commit title

**Comment by howie-f** [comment]
@rschupp can you do the requested changes so we can merge this upstream, please?

**Comment by lrusak** [comment]
I've updated the PR title and the commit message.

this fixes #22684

**Review by howie-f — APPROVED** [review]

**Pull request merged**
