### PR TITLE
jsonrpc: fix SetEpisodeDetails expecting a datetime instead of a date value for "firstaired"

### PR DESCRIPTION
**Pull request by Montellese**
A user reported that he wasn't able to change the `firstaired` property of epidoes through JSON-RPC using `VideoLibrary.SetEpisodeDetails`. To be absolutely sure he took the value returned for another episode and it still didn't work. Turns out we return `firstaired` as a date value (which is correct) but expect it to be set as a datetime value (which silently fails if it's a date value). This fixes it by expecting a date value like we provide ourselves.

### CODE REVIEW

**Comment by mkortstiege** [comment]
Makes sense.

**Comment by mkortstiege** [comment]
jenkins build and merge

**Comment by MartijnKaijser** [comment]
backport?

**Comment by Tolriq** [comment]
@MartijnKaijser @Montellese 
If I may leave a comment I'm against backport since it will be impossible to follow JSON API between versions.

Most people will base the available API on major XBMC builds, or assume that the JSON API version number covers all.

In that case since Helix will miss the backport of https://github.com/xbmc/xbmc/commit/295297d177171c02f903844032bcf3aec813b056 it will lead to either a same API version number but with function provided by 6.22.0 not being available in some builds.

Or change the API version number but then a total mess to know what API version covers what.

So IMO JSON backport should not happens unless major fix and in that case include all the other PR that impact the global API.

**Comment by MartijnKaijser** [comment]
i meant backport the fix and not the version number.

**Comment by Montellese** [comment]
@MartijnKaijser: That will result in errors for remotes that (unintentionally) work around this bug by sending a datetime formatted string and they have no way of knowing which API version expects which format.

**Comment by MartijnKaijser** [comment]
could still bump the JSON version code a digit on Helix branch. Not that i mind not fixing it for Helix. It was just a suggestion.

**Comment by Tolriq** [comment]
But then how does a remote know ?

Remotes can't have an if version > 6.21.3 since 6.22.0 does not have the fix.

They would need hacks like if version = 6.21.3 or version >= 6.22.1. but imagine the future if this happens again, totally unmanageable as it would also need a proper documentation as not all remotes makers follow git carefully against problems and regressions.

**Comment by MartijnKaijser** [comment]
that's how it is. 
Helix would be 6.21.3 and I** would be 6.22.1  Fixes happen and with us going to do more rapid development this could likely happen more.

**Comment by Tolriq** [comment]
Yes higher version are handled by simple cases if version > XX that break my thing then apply new way.
Same for about every API in fact if google api is version 2 then apply code that apply to api 2.

This is how it has always worked.

Now if the test becomes if XBMC is 14.2 and api is XX then apply fix or if XBMC is version > Y and api is > Z then apply the fix it's impossible to handle things correctly.

The base deal for the API was retrocompatibility, backport in those cases with different API number will generate remote makers a nightmare to handle.

For introspect this is not a solution, introspect is the documentation of the API for a specific API version number.

Remote makers would need an introspect for every possible JSON API number (150) then manually find what breaks what in each of those 3 MB files. 
Not possible at all.

And again this is not a FIX this is an API change. 

A fix is something that is documented to work in way A does not work, but the doc and everything is already correctly documented as it work like A.

For this case for example the API works like A it's just documentation and usage that are not "correct" so there's a decision that the API should work like B and then API change bump version and no backport.

A backport would be API function A should make this happens but it does not work. This is fixed and there's no API change it's a fix so can be backported without any problem.

**Comment by topfs2** [comment]
I think if documentation said it was a date then it might be valid to backport. As then the function didn't work with the proper parameters. Ifbthe documentation is fuzzy we shouldn't back port. I don't have the schema in front of me now so can't say how clear it is :)

**Comment by topfs2** [comment]
Any particular reason we don't silently skip the date part if date time is provided?

**Comment by topfs2** [comment]
Time part I mean :)

**Comment by Tolriq** [comment]
I guess my English is really that bad :(

Either people do use the function and use it with the time hack so backport will have 0 effect.
Or people do not use it and having 2 different API version would be a total mess.

Allowing backport and divergence in API version numbering is opening the door to devil and tons of kitties will die after that.

Anyway introspect just says String, so it's API change so it's API version increase, so it's no backport.

I really wonder what I could say to open eyes about API version divergence impact on API usage.

And not even talking about API version numbering which is just pure simple logic, having API break during a .X release is also bad for all people that use the API.

There's no reason that remotes are broken by users updating to a point release, as all problems will goes to remotes makers that can't guess that someone have made a breaking change.
Changelog never talk about those details, release is out users update day 1, then cry and insult remote maker because remote does no more work.
Than then needs to find the culprit and fix all in hurry.


In this case the impact is minimal very few users use those advanced API for the moment as there's still no way to upload / add images. But for other things it could be terrible. 
And as soon as API allows uploading of images, such functions will be way more used.

**Comment by topfs2** [comment]
Yeah I'm in general against API backports, here Im mostly questioning if its a bug or not. I do see your point on that if they use it they use with a workaround to the bug, or they don't use it. That seems rather possible and might be enough reason to skip backporting almost.

I guess you use it with the workaround?

**Comment by topfs2** [comment]
Looking at the schema
{ "name": "firstaired", "$ref": "Optional.String" },

It seems valid not to backport, if it had been clearly stated it was a date and not datetime I would have perhaps argued it could be backported

Everyone agrees?

**Comment by topfs2** [comment]
Oh and Montellese merge this away on master :)

**Comment by Tolriq** [comment]
No I do not use this API, but 50% of my code is for hacks and workaround so I well know the problem ;)

But as usual when I do insist a lot I do not fight for my own cause but for a better and greater Kodi.
I do follow JSON pulls carefully, I have the architecture to handle workaround for most cases (since well 50% of my code is around strangeness of the API and changes between version since I do support until now up to Eden) so I would not really be impacted a lot unless I miss some PRs.

But vast majority of others would be and it's bad for Kodi future.

**Pull request merged**
