### PR TITLE
Library.kodi.interfaces

### PR DESCRIPTION
**Pull request by AchimTuran**
@Paxxi @fritsch @FernetMenta @jimfcarroll 
This new helper library adds python support to the binary add-ons. You can ignore the functions that directly tries to access our Python interpreter. In the final commit I will remove them, because I don't need them. It was only for a test.

### CODE REVIEW

**Comment by Montellese** [comment]
Haven't done a full review yet and only had a quick glance and there are quite a few `TODO` comments and a lot of coding style issues.

**Comment by Paxxi** [comment]
Only glanced through it, so only some nitpicks, strdup doesn't get cleaned up, using fprintf for error reporting.
I probably won't have time for a proper review until sunday.

**Comment by AchimTuran** [comment]
> Haven't done a full review yet and only had a quick glance and there are quite a few TODO comments and a lot of coding style issues.

This is the first version and I know that there are a lot of issues. It was the last stuff I worked on and I wanted to hear the opinions from the team.
So you can see this PR as a WIP.

**Comment by Montellese** [comment]
@AchimTuran: OK please next time add `WIP` to the title of the PR and/or add the `WIP` label to the PR so that it's obvious. Otherwise I consider PRs as "ready".

**Comment by AchimTuran** [comment]
@Montellese 
> @AchimTuran: OK please next time add WIP to the title of the PR and/or add the WIP label to the PR so that it's obvious. Otherwise I consider PRs as "ready".

You're right, sorry I didn't see the label stuff. Thanks for looking into it and you found a lot of issues.

**Comment by garbear** [comment]
@AchimTuran I'm investigating your work here to see if it can be used in my game library project. would you be interested in help and feedback on this patch?

**Comment by AchimTuran** [comment]
@garbear feel free to ask your questions about my GSoC work. If you want we can do a conversion on slack next week.

**Comment by Rechi** [comment]
@AchimTuran this needs a rebase

**Comment by AchimTuran** [comment]
@Rechi
Thanks for the notification. This PR is quite old and would need a complete rework as the binary addon API has changed. Because of that I will close this PR.

**Pull request closed without merging**
