### PR TITLE
[addons][network] "C" ABI cleanups and clang cleanups

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description

This change nothing in addon API!

Commit 1
----------------------------
**[addons][filesystem] "C" ABI cleanups**

This add a `extern "C"` and the `#ifdef` to separate between C and C++. In API change this nothing, only done to confirm correct "C" and allow "C" only in future.

Commit 2
----------------------------
**[addons][network] clang cleanups**

This cleanup his code to match the clang, nothing changed in API.

Commit 3
------------------------
**[addons][network] add "using namespace ::kodi::addon;" to reduce size**

This to reduce line size and have code more clean.

## Motivation and Context

To cleanup and match "C" ABI related to issue https://github.com/xbmc/xbmc/issues/17514

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by AlwinEsch** [comment]
jenkins build this please

**Review by garbear — APPROVED** [review]

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by AlwinEsch** [comment]
jenkins build this please

**Pull request closed without merging**
