### PR TITLE
[depends] gnutils 3.4.9

### PR DESCRIPTION
**Pull request by MartijnKaijser**
Not sure if patch can be dropped

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@wsnipex ping

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by stefansaraev** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
@MartijnKaijser https://github.com/wsnipex/xbmc/commit/9cff40b01e0ddbefc10c92a2b39621ba5fbb6c39

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
@wsnipex only droid fails now

**Comment by wsnipex** [comment]
yes, but the error seems strange. Apparently ffmpeg fails to find it via pkgconfig

**Comment by mrdominuzq** [comment]
i think this is causing the problem
https://gitlab.com/gnutls/gnutls/commit/28e0716146530ff5e9b2041c52f78a9ecc7f63b5

**Comment by MartijnKaijser** [comment]
@wsnipex probably best to leave this in your hands should you have time in the future

**Pull request closed without merging**
