### PR TITLE
enable Nfs autoreconnect

### PR DESCRIPTION
**Pull request by wsnipex**
## Description

enables autoreconnect in libnfs.
Defaults to unlimited retries, just like standard NFS clients

configurable through AV.xml:

```
  <network>
    <nfsretries>10</nfsretries> <!-- 0 to disable, default: -1 (unlimited) -->
  </network>

```

quote from libnfs.h
```
* autoreconnect=<-1|0|>=1>
 *                   : Control the auto-reconnect behaviour to the NFS session.
 *                    -1 : Try to reconnect forever on session failures.
 *                         Just like normal NFS clients do.
 *                     0 : Disable auto-reconnect completely and immediately
 *                         return a failure to the application.
 *                   >=1 : Retry to connect back to the server this many
 *                         times before failing and returing an error back
 *                         to the application.
```

## Motivation and Context

NFS should behave like smb and retry intermittent connection failures

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by arnova** [comment]
Shouldn't we implement an <nfs> tag that contains all the nfs options, like we did for curl?

**Comment by wsnipex** [comment]
is it worth it for just 2 options?

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by arnova** [comment]
> is it worth it for just 2 options?

Perhaps not yet, if it's for only 2 options atm. But let's keep it in mind for the future when more stuff gets added...

**Review by arnova — APPROVED** [review]

**Comment by arnova** [comment]
@wsnipex : Forgot to mention that it may be wise to disable autoreconnect when caching is enabled, like we do in smb/curl. Else the fs may hang for a longer time than desirable from a user's perspective. See https://github.com/arnova/xbmc/blob/f44fdfbf675f30c01e7639177a34544e6a6b9dad/xbmc/platform/posix/filesystem/SMBFile.cpp#L708-L712

**Pull request merged**
