### PR TITLE
changed: build the exif code in main library

### PR DESCRIPTION
**Pull request by stefansaraev**
the work is done by notspiff, all credits to him.

## Motivation and Context

I wanted to get rid of the wrapped libexif.so

## How Has This Been Tested?

build tested on linux. I am not sure how to runtime test this, as with or without "show exif information" kodi shows exactly same info: http://i.imgur.com/8hPJcgP.jpg - same before this PR. auto rotation does not work either (it didn't work before, is it supposed to work at all?)

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build this please.
@fritsch ping
not sure who else cares about pictures

**Comment by fritsch** [comment]
@wsnipex fine when you are fine. It does not change functionality. If it makes things easier - fine with me. Thanks much.

**Comment by stefansaraev** [comment]
squashed

**Comment by wsnipex** [comment]
jenkins build and merge

**Pull request merged**
