### PR TITLE
[addons][inputstream][videocodec] Fix wrong flags bit shift

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

The PR https://github.com/xbmc/xbmc/pull/17438 has introduced a wrong bit shift that cause impossibility to set audio streams properties
@AlwinEsch
@peak3d i think need new ISA build (but this is not related to the problem of playback start)

## Motivation and Context

The modified enum should be translatable with:
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/Interface/StreamInfo.h#L18-L30

## How Has This Been Tested?

Tested with NF addon related to Issue: https://github.com/peak3d/inputstream.adaptive/issues/548

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by AlwinEsch — APPROVED** [review]
Thanks very much to see my fault and to bring a fix!

Think we need a version increase in API and on addons to have it on our addon mirrors correct for update.

**Comment by AlwinEsch** [comment]
Or to prevent it on PVR to make only one version increase on inputstream.adaptive and inputstream.ffmpegdirect itself (inputstream.rtmp not use it).

**Comment by CastagnaIT** [comment]
try to see if increased in the exact way

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
@AlwinEsch this good to go in?

**Comment by ksooo** [comment]
@AlwinEsch ping

**Comment by AlwinEsch** [comment]
Can be in from my side, only need then using PVR addons a version increase.

I'm only the next two days not at home go create requests there.

**Comment by ksooo** [comment]
@AlwinEsch PVR? You mean iinputstream, right?

**Comment by AlwinEsch** [comment]
No, also used on PVR where have Demux inside, look your pvr addon.xml.

**Comment by ksooo** [comment]
@AlwinEsch hate to say that, but please. If you introduced the bug, please take care that all addons get the necessary PRs in a timely manner.

**Comment by AlwinEsch** [comment]
Ping @peak3d inputstream.adaptive need one new release with version increase to have this fix and working with API!

On all addons (except inputstream.adaptive) are update requests opened where use the inputstream API.

**Pull request merged**
