### PR TITLE
[IMX] fix - fb reconfiguration on resolution change while video playback

### PR DESCRIPTION
**Pull request by mk01**
otherwise resolution change kills videoplayback

### CODE REVIEW

**Comment by fritsch** [comment]
@smallint and @wolfgar: Could you please have a look?

**Comment by fritsch** [comment]
@koying: Could you look into: https://github.com/mk01/xbmc/commit/f828b63368f251747365804b3f043dca3c7d77bb

**Comment by fritsch** [comment]
@mk01 could you introduce a proper CleanUp Method?

@wolfgar thanks very much.

**Comment by mk01** [comment]
@fritsch 

I reverted that shortcut to fb reconfig for now (in case of deinterlacing is changed).

In parallel I prepared second PR doing cleanup and fb reconf on the fly. But currently It would conflict with  with @koying 's https://github.com/xbmc/xbmc/pull/7689 .

I can wait until that one goes in. Then I will rebase.

**Comment by fritsch** [comment]
jenkins build this please (to see if nothing got broken)

**Comment by mk01** [comment]
@fritsch 

why would be WIN-32 and OSX had HAS_IMXVPU in config.h  ?

**Comment by fritsch** [comment]
@mk01 ever missed an ifdef? It's a sanity check nothing more.

**Comment by mk01** [comment]
ok

**Comment by mhueske** [comment]
@mk01 Any updates regarding this topic? Did you already setup a second PR - I couldn't find it until now. Thanks :-)

**Comment by mk01** [comment]
will update this one later today. to contain the 2nd part as well

**Comment by MartijnKaijser** [comment]
Now videoplayer has been merged some of you PRs need some updating.

**Comment by mk01** [comment]
@mhueske 

was it you reporting decoder crash on content changing ratio/other parameters ?
if so, can you provide sample for testing ?

**Comment by FernetMenta** [comment]
jenkins build this please

is this ready to go? objections?

**Comment by wolfgar** [comment]
Hi All

fb reconfiguration looks fine to me

I only have a little concern about another change in the same commit which is not related to fb reconfiguration at all.

That is the decoder configuration to skip frames (VPU_DEC_CONF_SKIPMODE) implemented in SetSkipMode.
If you look at the imx support history (both before and after merge in mainstream) , you will find that we added and then removed this skipmode configuration several times
Each time, we ended by witnessing that the drawback (much significant visible artifacts) is worse than the benefit (ability to be faster while in  skipmode).
I added a comment in SetDropState that states it as memory of these tests and switches (By the way the comment is invalidated by the proposed commit so it should be removed if this change is kept)

Have you well identified use cases and/or stream instances that show this move has a positive balance now ?

**Comment by fritsch** [comment]
@mk01 anything you want to add? We are ready to finally push this :-)

**Comment by wolfgar** [comment]
any answer t my remark ?
So my first review was deleted and my second is ignored ?

**Comment by fritsch** [comment]
It was not deleted it was rebased and therefore it is gone.

**Comment by wolfgar** [comment]
So may its soul rest in peace ;-) (i speak about the gone review of course)

More seriously, this commit holds the additional change regarding skipmode. If you remember we already switched this configuration. Do you think it is better to re-enable it regarding some new testing you would be aware of ?

**Comment by fritsch** [comment]
Yes - it worked kind of bad ... artifacts all over the place. But also consider: droppping is the very, very last resort that we have, when user play e.g. 1080p60 / whatever content.

Looking at the code it looks more advanced than what we shortly hacked together last time we looked at it. Basically I am totally no sure which dev still actually runs IMX6 hardware? You are still using it?

**Comment by wolfgar** [comment]
Yes I run kodi on 2 iMX6 devices on regular  basis (one for liveTV, another one streaming from my NAS) and I have to say I am pretty happy with them...
The contents I (and most users I guess) generally play is not so prone to dropping so I would not be hurt too hard I think. But I only wanted to point this configuration was already tried and given up in the past and wanted to be sure we have some weighted benefits to re-enable it in its current shape. If so I am perfectly fine with it for sure...

**Comment by fritsch** [comment]
Can you easily do a runtime test? With the famous 1080p50 sample we used "back in time"? - I don't hav e imx6 hardware anymore with kodi - therefore I cannot test.

**Comment by wolfgar** [comment]
Sure,I should still have the sample you mention : I will build with this commit applied and report you back...

**Comment by fritsch** [comment]
thx much!

**Comment by mhueske** [comment]
Do you still need additional material for testing - as @mk01 asked for? I am sorry I was on holiday so I had no chance to read your message

**Comment by fritsch** [comment]
Back in time we tested with: http://solidrun.maltegrosse.de/~fritsch/1080p50_h264.mkv just play it, press backspace to get the menu a bit on top of it ... slowly see the singer going out of sync. With the dropping you should see artifacts.

**Comment by mhueske** [comment]
Currently I have problems with my building environment, I need to examine this further. But I uploaded my sample video file here: https://owncloud.hueske.eu/index.php/s/4eiKlttEKBvQYt1
Some seconds after starting the file video will stop while audio continues.

**Comment by mhueske** [comment]
Today I succesfully built OpenELEC from master (as base). I replaced Kodi package with Kodi 17 alpha 1 and applied this PR.
Sadly this didn't change anything. Your sample still gets out of sync even though I can't see any artifacts.
My sample still stops video playback while audio continues.

**Comment by mk01** [comment]
@mhueske 
your sample problem is due missing reconfiguration on decoder side. Now with your sample I will implement it.

regarding going out of sync, with reference clock all the videos from fritsch's test pool play in sync.

**Comment by mk01** [comment]
@mhueske 

your kind of issue is fixed by last commit

**Comment by mhueske** [comment]
Great work. I can confirm the issue is fixed :-)

**Comment by fritsch** [comment]
@smallint @wolfgar please have a look especially at the double rate deinterlacing fixe - I want to get this code into kodi, so please have a look again.

**Comment by smallint** [comment]
As @wolfgar said, the skipping has never been a success story and introduces more visual impact than it helps. I agree that under some circumstances it is the last chance we might have. If it triggers too often then you don't know whether the problem is your receiver, the cable, the usb or the VPU. A user would never think of the last. I spent a long time figuring out why I am having artefacts on livetv and it turned out that it was related to a usb hub. I personally don't like the hardware dropping implemented in the VPU. The very best would be an option to enable hardware dropping or not.

The double rate fix is something I cannot check right now. The Kodi internals have changed and I cannot follow the fix right now. As I understood you want to compensate the oscillation of the two interlaced frames. @wolfgar implemented a small kernel patch at IPU level which is running on my box and it helps although it does not perfectly remove the oscillation. I will try to compile the latest dev with that branch.

**Comment by wolfgar** [comment]
Hi 
Issue with this PR is that at each update it adds (rather silently) something new which is unrelated to its title and that could prevent/delay to merge commits which have been pretty fine for everyone for a long time like the fb reconfiguration...
Regarding the double deinterlacing, at first sight, it seems fine an makes good sense (regarding the artifact). I have not tried it yet...
Regarding frames drops, I tested it and to me results are the same than previously : more harm than it helps. I have not updated the PR as, because of personal constraints, it took a long time to run test and the thread was already on another topic without feedback from the author regarding the rationale and testing about the dropping question.
At the end as I think most of these changes should be merged, let's go for it even if the price to pay seems to be : apply the whole thing without constructive exchange...

**Comment by fritsch** [comment]
Thanks for yoru feedback.

@mk01 please remove the dropping patch so it can be PRd and discussed separately. Then we can merge the other patches.

**Comment by fritsch** [comment]
Thanks @mk01 

Please open a new PR with the decoder dropping. The current implementation, even if there are no artifacts, just ignores VideoPlayer. Audio / Video goes horroful out of sync and high fps content is unwatchable. But let's discuss that in a separate PR.

jenkins build and merge

**Comment by mk01** [comment]
@fritsch 
sure, later today with my comment as well.

**Comment by mk01** [comment]
@wolfgar @smallint 
thanks for participation on this too.

**Comment by fritsch** [comment]
Windows build failure not related.

**Pull request merged**
