### PR TITLE
fix rating scale for music in mediafilter

### PR DESCRIPTION
**Pull request by ronie**
ratings for albums/songs are now on a 0-10 scale

@Razzeee

### CODE REVIEW

**Comment by ronie** [comment]
apparently not. brainfart.

**Comment by Razzeee** [comment]
Well it's not invalid. The backport is.
I'm not sure when this is called? Haven't hit a wrong behavior so far, can you elaborate? We might also need a logic for Userratings.

In fact the one you changed should be for userratings and we need one for ratings that can handle floats/decimals.

**Comment by ronie** [comment]
updated the code to handle floats.

> I'm not sure when this is called?

hit the 'filter' button in the side menu in the musiclibrary

filter

**Comment by Razzeee** [comment]
That code is correct, have you runtime tested it?

Jenkins build this please

**Comment by ronie** [comment]
not yet. needs more work.

**Comment by ronie** [comment]
tested & should be good to go now.
@Razzeee mind having another look at the diff?

Jenkins build this please

**Comment by MartijnKaijser** [comment]
it's jenkins build this please

**Comment by Razzeee** [comment]
Seems good @ronie 
We might want to add this for user rating too and probably backport the user rating part for videos?
Not sure.

**Comment by ronie** [comment]
i'm not a big fan of backporting new code this close to the release date.

as for adding userratings, will do that as a separate PR.

**Comment by Razzeee** [comment]
Sorry, I thought there might be a bug, but that's nonsense, as the user ratings are new for video.
Too much combinations ;)

**Pull request merged**
