### PR TITLE
[ios] change to darwin_embedded from ios for CORE_SYSTEM_NAME + platform defines

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
This provides all the changes from CORE_SYSTEM_NAME == ios to darwin_embedded. Split into 2 commits, 1 for all build/cmake changes, and the second is all xbmc specific code changes for the actual kodi app.

## Motivation and Context
This is being done to generalise the apple embedded platforms to accommodate upcoming tvOS and existing IOS platforms. A lot of code will be common on the two platforms, but there is some differences that are needed that this will allow.
This touches a lot of files, due to the ifdeffery used, so not sure if you want to push this in early in this dev cycle, or wait. It doesnt change/touch any existing functionality

This will require updates to most, if not all addon build systems. Im happy to do the legwork on that, but before i start PR'ing to all the repo's, just be good to see if this will be merged or not.

One change that may need to be changed will depend on the outcome of Rechi's existing PR https://github.com/xbmc/xbmc/pull/16020
If/when that is merged, i can adapt the corresponding code to mirror the merged change

## How Has This Been Tested?
Full builds (depends + program)

Have NOT built all addons. Most, if not all, will require build changes (CORE_SYSTEM_NAME STREQUAL ios -> darwin_embedded in Findxxx.cmake files most commonly). actual code changes that use ifdef(TARGET_DARWIN_IOS) will continue to work without requiring changes

Compiled and tested on jailbroken ipads by 2 individuals
Test done:
• Install Youtube addon --> Ok
• Watch youtube vidéo (sound + video) --> Ok

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by Memphiz — COMMENTED** [review]
I am ok with that approach though the needed changes to all binary addons is a great pita. My respect to you for taking this up :).
The only thing I wonder is how to distinguish tvOS and iOS on code preprocessor level. There is only TARGET_DARWIN_EMBEDDED there now. Or do you think there will be no need to distinguish that way and all can be done on build system level in the end?

**Comment by fuzzard** [comment]
Might not have been clear because of the mass renaming, however there is still preprocessor defines for ios. Used how it currently is in master. The ones that have been changed to darwin_embedded are all code paths we use on tvos as well. For anything targeting just ios, behaviour stays the same (TARGET_DARWIN_IOS)

I'll start the PR's for addons this weekend. Was looking earlier in the week, and most visualizer addons will need changes, but a lot of the others (pvr, adsp) wont from a cursory glance. Ill trawl through all the addons that ship with kodi and verify though. Only affects build related files.
Anything that relies on preprocessor defines, as mentioned above wont need to be changed unless/until we merge in any ATV stuff and its common to the platforms.

**Comment by keithah** [comment]
I added @pkerling and @ksooo since this is a change with all binary addons to get their opinion.

**Comment by phunkyfish** [comment]
I’m not sure this will effect that many of the addons. Only those that do something platform specific for iOS using CORE_SYSTEM_NAME.

**Comment by fuzzard** [comment]
Yes

**Comment by phunkyfish** [comment]
@Rechi would be great to get your review on this. Once the approach is agreed we'll be able to progress the rest of the tvOS work.

**Comment by fuzzard** [comment]
I believe that's all the addons with relevant PR's. Ill rebase this tomorrow

**Comment by fuzzard** [comment]
any chance on a jenkins build of this, and a review?

**Comment by pkerling** [comment]
I'm fine with the change, but I think @rechi would be most competent to review it. Jenkins often fails with force pushes, so let's retry.

**Comment by pkerling** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
@Rechi @ksooo @pkerling if you are fine with this please approve so @fuzzard can go on with the needed binary addon changes. @fuzzard once this is merged binary addons will be broken for a short period of time then I guess?

**Review by wsnipex — APPROVED** [review]
looks sane

**Review by yol — APPROVED** [review]

**Comment by fuzzard** [comment]
@Rechi Have updated PR's to branches requested for the addons. Let me know if there are any further requirements regarding active branches or other issues.

**Comment by Memphiz** [comment]
I decide this will get merged as soon as it is rebased and @fuzzard handled out a coordination with the adding pull requests. Thx for all involved in advance.

**Comment by fuzzard** [comment]
Did a rebase, not sure why the rebase tag wasnt removed. 

The failure is an osx jenkins build failure, not code related. May want to give it one more kick

**Comment by jjd-uk** [comment]
jenkins build this please

**Comment by phunkyfish** [comment]
Post a rebase and merge here is the list of PRs that will also require a merge:

- https://github.com/xbmc/kodi-platform/pull/29
- https://github.com/kodi-game/game.libretro.2048/pull/9
- https://github.com/kodi-game/game.libretro.mrboom/pull/7
- https://github.com/xbmc/visualization.waveform/pull/20
- https://github.com/xbmc/repo-binary-addons/pull/123
- https://github.com/xbmc/repo-binary-addons/pull/124
- https://github.com/fetzerch/kodi-game-scripting/pull/64
- https://github.com/xbmc/vfs.sftp/pull/28
- https://github.com/xbmc/vfs.libarchive/pull/30 
- https://github.com/xbmc/visualization.spectrum/pull/27

@Fuzzard: - https://github.com/kodi-game/game.libretro.2048/pull/9 - Will need a proper local repo rebase. The github webpage cannot do this.

**Comment by fuzzard** [comment]
The osx failure seems to be an automake download failure, can that test be kicked again?

**Comment by phunkyfish** [comment]
This also needs a kick: https://github.com/kodi-game/game.libretro.2048/pull/9

**Comment by Memphiz** [comment]
Jenkins build this please

**Comment by phunkyfish** [comment]
Looks like this is good to go. Who can do the honours and merge it?

FYI: libretro.2048 PR good. It didn’t pass CI due to a git checkout error.

**Comment by Memphiz** [comment]
@lrusak could you push those buttons please?

**Review by lrusak — APPROVED** [review]

**Comment by phunkyfish** [comment]
@lrusak all these addons needs to merged too after this PR: https://github.com/xbmc/xbmc/pull/16039#issuecomment-512219278

**Comment by phunkyfish** [comment]
Of the addons that need to be merged two of them need a rebuild. For kodi-game-scripting I'm not sure what causes the failure.

@lrusak can we merge the addons without build failures?

xbmc/kodi-platform#29
kodi-game/game.libretro.2048#9 (needs a rebuild, fails on retrieveing ming tarball)
kodi-game/game.libretro.mrboom#7 (needs a rebuild, fails on retrieveing ming tarball)
xbmc/visualization.waveform#20
xbmc/repo-binary-addons#123
fetzerch/kodi-game-scripting#64 (not sure where this fails)
xbmc/vfs.sftp#28
xbmc/vfs.libarchive#30
xbmc/visualization.spectrum#27

**Comment by Rechi** [comment]
@lrusak please always set the milestone before or right after merging a PR.

**Comment by AlwinEsch** [comment]
By this request, the Jenkins construction of Binary addons does not work on **ios**!

Hangs largely together herewith https://github.com/xbmc/pipeline-library/blob/master/vars/buildPlugin.groovy#L13-L14

Think this also needs to be changed and probably get a separate branch for "Matrix" or "Leia" or a special way of being able to distinguish the versions.

**Comment by Rechi** [comment]
No the Jenkins piple doesn't need to be adjusted.
The zip files should still use `ios` as platform name instead of `darwin_embedded`, so one can distinguish them from add-ons compiled for tvOS.

**Pull request merged**
