### PR TITLE
OSX: only load resolution of current display

### PR DESCRIPTION
**Pull request by FernetMenta**
- loads only resolutuion of current display
- use setting monitor
- display mode only for fullscreen and windowed mode

### CODE REVIEW

**Comment by FernetMenta** [comment]
@afedchin this makes resolution parameter iScreen obsolete for OSX. Windows is last platform using iScreen and should follow. This will fix broken multi-monitor setups

**Comment by Kwiboo** [comment]
https://github.com/xbmc/xbmc/pull/13903/files#diff-4369faba7782d026ff979f7092132690L180 should probably be changed to include complete resolutions list now that desktop has been excluded

**Comment by FernetMenta** [comment]
@Kwiboo updated

**Review by Memphiz — APPROVED** [review]
Looks good now - thx. Only thing left might be the issue when having 2 identical displays connected  which might not be distinguishable by name - I guess we will wait until someone comes up with issues on that constellation and fix it then.

**Comment by FernetMenta** [comment]
jenkins build this please

**Pull request merged**
