### PR TITLE
[Estuary][PVR] PVRInfoPanel: Incorrect fallback icon

### PR DESCRIPTION
**Pull request by linknetx**
## Description

Changed PVRInfoPanel fallback icon from DefaultVideo.png to DefaultTVShows.png

## Motivation and Context

Now shows correct fallback icon in PVRInfoPanel when no thumbnail is available.

## How Has This Been Tested?

Compiled and tested - correct icon now visible when no thumbnail available.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [X] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ksooo** [comment]
Though the change might be semantically correct I'm not sure the used DefaultTVShows.png is technically (dimensions, alpha, what not) okay. @ronie what do you think?

**Comment by linknetx** [comment]
> Though the change might be semantically correct

Sorry, but I don't understand that, but it does fix this:

**Before:**
1 before

**After:**
2 after

**Comment by MartijnKaijser** [comment]
But you are now putting a TV show icon on what might also be a movie which is not correct

**Comment by ksooo** [comment]
> But you are now putting a TV show icon on what might also be a movie which is not correct

I agree.

**Comment by linknetx** [comment]
OK, so how to fix, the home screen gets it correct without any modification:

home

**Comment by ronie** [comment]
well what we currently have is inconsistent indeed.

as we don't have a specific DefaultPVRRecording.png icon, we'll either have to pick the TVShow or the Movie/Video (they are the same) one.


perhaps for v19 we can add some PVR specific icons (DefaultPVRChannel / DefaultPVRRecording).

**Comment by linknetx** [comment]
Currently all the rest of the TV screens use the DefaultTVShows.png

So why not apply this to the PVRInfoPanel as well for consistency?

tv_channels
tv_search
tv_timer_rules
tv_timers

**Comment by ronie** [comment]
no preference either way, but even with your proposed change, the icon for deleted recordings will be inconsistent.

https://github.com/xbmc/xbmc/blob/7ef37db5bad5d5830427db3f8dc2c7a9654841db/xbmc/FileItem.cpp#L1315-L1324

**Comment by linknetx** [comment]
> no preference either way, but even with your proposed change, the icon for deleted recordings will be inconsistent.

So should this be changed as well, is there a deleted TV Show icon ?

**Comment by ronie** [comment]
nope there's none. but the current one can be modified if there's consensus to go for the tvshow icon to depict tv recordings.

**Comment by linknetx** [comment]
> nope there's none. but the current one can be modified if there's consensus to go for the tvshow icon to depict tv recordings.

Something like this?

[defaultdeletedtvshows.zip](https://github.com/xbmc/xbmc/files/2849222/defaultdeletedtvshows.zip)

**Comment by ronie** [comment]
yup that's what i had in mind.
but just keep the DefaultVideoDeleted.png name.

**Comment by linknetx** [comment]
> yup that's what i had in mind.
> but just keep the DefaultVideoDeleted.png name.

That was a quick effort, I'll submit a cleaner one.

**Comment by linknetx** [comment]
OK, replaced DefaultVideoDeleted.png with this:

[defaultvideodeleted.zip](https://github.com/xbmc/xbmc/files/2849279/defaultvideodeleted.zip)

**Comment by ksooo** [comment]
Please ad a comment explaining the asymmetric naming of png files for deleted / non-deleted recordings right where it is used. Reason is skin compatibility as those file names are part of the skinning "API" and must not just be renamed

**Comment by ksooo** [comment]
@ronie I still do not like the asymmetric naming. What do you think? Should we merge this anyway?

**Comment by ksooo** [comment]
I think this does not really work, even if we keep the file names and live with the asymmetric names.

 If we now set DefaultTVShows.png for recordings in the core (!), every skin must change visual appereance of the image for DefaultVideoDeleted.png to match DefaultTVShows.png - like we did in this PR. Unfortunately, this is a must as othwerwise we will and up with another (visual) inconstency.

**Comment by linknetx** [comment]
Shouldn't we have just added a new file: DefaultTVShowsDeleted.png rather then changing the DefaultVideoDeleted.png image?

**Comment by ksooo** [comment]
> Shouldn't we have just added a new file: DefaultTVShowsDeleted.png rather then changing the DefaultVideoDeleted.png image?

 Every skin must be adapted then to suppy the new DefaultTVShowsDeleted.png - otherwise there would be no visual default presentation for deleted recordings anymore.

**Comment by ronie** [comment]
@ksooo i'll have to agree making core changes in a stable release should be avoided.

so i suggest to drop the core change and fix/workaround the problem in the estuary skin instead.

as far as i can tell, this would be all that's needed:
```
diff --git a/addons/skin.estuary/xml/Variables.xml b/addons/skin.estuary/xml/Variables.xml
index 4b1ed63956..6e38449d04 100644
--- a/addons/skin.estuary/xml/Variables.xml
+++ b/addons/skin.estuary/xml/Variables.xml
@@ -450,6 +450,7 @@
        </variable>
        <variable name="ChannelListEPGIconVar">
                <value condition="!String.IsEmpty(Listitem.EpgEventIcon)">$INFO[ListItem.EpgEventIcon]</value>
+               <value condition="[Window.IsActive(tvrecordings) | Window.IsActive(radiorecordings)]">DefaultTVShows.png</value>
                <value>$INFO[ListItem.Icon]</value>
        </variable>
 </includes>

```

**Comment by linknetx** [comment]
> so i suggest to drop the core change and fix/workaround the problem in the estuary skin instead.

Just tried that and all the thumbnails are missing and all recordings have the DefaultTVShows.png

**Comment by linknetx** [comment]
This can be done in the skin by providing a specific icon:
```
  <variable name="ChannelListEPGIconVar">
      <value condition="String.IsEqual(ListItem.Icon,DefaultVideo.png)">DefaultTVShows.png</value>
      <value>$INFO[ListItem.Icon]</value>
  </variable>
````
Or by not providing an icon and letting it default to the icon specified in the skin:

```
  <variable name="ChannelListEPGIconVar">
      <value condition="String.IsEqual(ListItem.Icon,DefaultVideo.png)"></value>
      <value>$INFO[ListItem.Icon]</value>
  </variable>
```

**Comment by ronie** [comment]
thanx for testing it and your suggestions :-)
i had another look at it as well and swapping ListItem.Icon with ListItem.Thumb should do the trick:

```
	<variable name="ChannelListEPGIconVar">
		<value condition="!String.IsEmpty(Listitem.EpgEventIcon)">$INFO[ListItem.EpgEventIcon]</value>
		<value>$INFO[ListItem.Thumb]</value>
	</variable>
```


ListItem.Thumb does not fallback to the default icon defined by core, but uses the fallback defined by the skin:
https://github.com/xbmc/xbmc/blob/5e82ff9595c50b44d26451a56024bf0d9de335ab/addons/skin.estuary/xml/Includes_PVR.xml#L200

**Comment by linknetx** [comment]
@ronie 

Thanks for that suggestion, it works fine, but now knowing that ListItem.Thumb does not fallback to the default icon defined by the core why not scrap the "ChannelListEPGIconVar" altogether and use this:

`In includes_PVR.xml line 200:`

```
<control type="image">
	<top>135</top>
	<left>590</left>
	<width>240</width>
	<height>135</height>
	<aspectratio align="right" aligny="top">keep</aspectratio>
	<texture fallback="DefaultTVShows.png">$INFO[ListItem.Thumb]</texture>
	<fadetime>200</fadetime>
</control>
```
I've tested this and it works :-)

**Comment by ksooo** [comment]
What I don't understand about all this,is that I never see that default icon for my recordings. For me, it's either a thumbnail image or the channel icon... 

Another "problem" caused by your beloved pvr client addon? Just guessing... Not saying the  addon is beloved bravely nessacerily buggy, but it does some things  guessing...  ;-)

**Comment by linknetx** [comment]
> What I don't understand about all this, is that I never see that default icon for my recordings.

It is only visible immediately after a recording  has started if my "beloved pvr client addon" :-) hasn't yet had time to create the thumbnail. Once the thumbnail has been created the default icon is never seen again.

**Comment by ksooo** [comment]
Whatever comes out of this PR, I cannot afford more time for this, sorry.

I definitely suggest to carefully test your changes to not break other addons. This is obviously a sensitive playground with some potential to break stuff.

**Comment by ksooo** [comment]
@linknetx it's cool that you seem to have plenty of time for Kodi development, but  currently I'm unable to keep up with your speed - real live, job, family, you know...

**Comment by linknetx** [comment]
> @linknetx it's cool that you seem to have plenty of time for Kodi development, but currently I'm unable to keep up with your speed - real live, job, family, you know...

I'm not quite sure which way to take that ;-) but I've had all of those things and have now taken early retirement :-)

**Comment by ksooo** [comment]
Just want to say that I always feel bad when I'm unable to timely assist people caring about Kodi. 😀

**Comment by linknetx** [comment]
@ksooo 

OK, changed this to an estuary skin change only, no controversial renaming of core files. 

I've tested this several times and it works perfectly, so now hoping it can get the go ahead ?

**Comment by ksooo** [comment]
> I've tested this several times and it works perfectly, so now hoping it can get the go ahead ?

 Well, I'm afraid that your change will break something else. The var you've eliminted was introduced for a reason. => https://github.com/xbmc/xbmc/pull/14376

So, no go atm, sorry. Please check that the cases implemented with abovementioned PR still work after your change.

**Comment by linknetx** [comment]
> Well, I'm afraid that your change will break something else. The var you've eliminted was introduced for a reason. => #14376 

Well found!

The var that I've eliminated was introduced to correct the very same line in includes_PVR.xml line 200 which I have modified. So by not requiring in that line it is now redundant.

A search, which was done before eliminating the var, also shows that the var doesn't exist anywhere else in the estuary skin.

**Comment by ksooo** [comment]
> The var that I've eliminated was introduced to correct the very same line in includes_PVR.xml line 200 which I have modified. So by not requiring it in that line it is now redundant.

I'm still not convinced that replacing the var with just ListItem.Thumb will not break something else. Have you actually runtime tested that the use cases mentioned in #14376 still work after your change?

**Comment by ksooo** [comment]
@lightglitch in case you are around, can you confirm that the code change proposed in this PR does NOT break what you have implemented in #14376 ?

**Comment by linknetx** [comment]
> I'm still not convinced that replacing the var with just ListItem.Thumb will not break something else. Have you actually runtime tested that the use cases mentioned in #14376 still work after your change?

Not all of the changes that were proposed in #14376 were actually implemented. I have runtime tested (again just to make absolutely certain) all of the changes that were implemented and all still test fine. The var concerned only relates to the PVR Info Panel and absolutely nowhere else.

**Comment by ksooo** [comment]
Let's wait what @lightglitch has to report on this.

**Comment by ksooo** [comment]
Unfortunately I cannot test this myself.

**Comment by linknetx** [comment]
> Let's wait what @lightglitch has to report on this.

Good idea, but in the meantime there is another incorrect fallback icon in DialogPVRInfo.xml which I've added to the PR.

I'm coming back to my original thought that this should be fixed in the core, because now it will only default to DefaultTVShows.png and would never default to DefaultTVShowsDeleted.png for a deleted recording.

**Comment by ksooo** [comment]
> I'm coming back to my original thought that this should be fixed in the core

 Maybe, but this has to wait for v19, because it is an incompatible change for skins. And now I'm out of this discussion. This is by far too time-consuming (for me).

 Final statement: Replacing the var (and other) by Listitem.Art("thumb") feels wrong.

**Comment by linknetx** [comment]
>This is by far too time-consuming (for me).

For me also, what at first appeared simple opened up a whole can of worms.

So should I close this PR ?

**Comment by lightglitch** [comment]
Just did a little test and with these changes the EPG Image stop showing. On the left the current version, on the right the changes by this commit.

Dialog PVR:
dialogpvrinfo

Includes PVR:
includes_pvr

**Comment by ksooo** [comment]
Thanks, @lightglitch, that's what I thought from looking at the related core code.

**Comment by linknetx** [comment]
@lightglitch 

I wonder if you be kind enough to test again with the new proposed code.

**Comment by ksooo** [comment]
Even if this would work, I will not approve this wild hackery, sorry.

**Comment by linknetx** [comment]
OK, I'll close the PR unless there's any reason to leave it open.

**Comment by linknetx** [comment]
Byeee :-)

**Pull request closed without merging**
