### PR TITLE
[binary addons] fix addon.xml generation if addon.xml.in contains sem…

### PR DESCRIPTION
**Pull request by wsnipex**
…icolons

@hudo: should fix your issue.
fix is just as @Montellese suggested

### CODE REVIEW

**Comment by stefansaraev** [comment]
confirmed. thanks

@hudokkow I see you testing OE. OE needs a bit more work (PLATFORM= passed to cmake in package.mk, at least). fyi

jenkins jenkins build addons please

**Comment by wsnipex** [comment]
thanks, for good measure: jenkins build addons please

**Comment by stefansaraev** [comment]
offtopic: @Montellese what about using TARGET_LINKER_FILE_NAME not TARGET_FILE_NAME ?

**Comment by hudokkow** [comment]
thanks @wsnipex you're pinging the wrong hudo ;-)

**Comment by Montellese** [comment]
@stefansaraev: What would be the difference? @wsnipex thanks for putting together the PR.

**Comment by hudokkow** [comment]
All green, thanks! Now for https://github.com/xbmc/xbmc/pull/7725

**Comment by stefansaraev** [comment]
@Montellese 
https://github.com/xbmc/xbmc/blob/master/project/cmake/scripts/common/addon-helpers.cmake#L49

before #7570 for pvr.wmc:
in addon.xml: library_linux="pvr.wmc.so"

after #7570 and https://github.com/kodi-pvr/pvr.wmc/pull/20 for pvr.wmc:
in addon.xml (generated) library_linux="pvr.wmc.so.0.6.3"

no idea if it's an intended change. if so, pls ignore me, if not - I'll send a PR.

**Comment by Montellese** [comment]
@stefansaraev: Ah right! Obviously I didn't see that because on WIN32 there's no version numbers in TARGET_FILE_NAME. Feel free to create a PR and I will check if it also works on WIN32.

**Pull request merged**
