### PR TITLE
paplayer: wait for eof if no crossfading or cue sheet

### PR DESCRIPTION
**Pull request by FernetMenta**
fix for http://trac.kodi.tv/ticket/16278

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by trustin** [comment]
I wonder if this PR also would be merged into Isengard, since it seems like it has the same problem.

**Comment by MartijnKaijser** [comment]
No. Isengard is closed and forgotten

**Comment by trustin** [comment]
Oh, OK. I was just wondering if there's any chance because Jarvis is still at alpha. Is it usual to close the old branch even if the new branch is still not at beta or RC?

**Comment by FernetMenta** [comment]
Jarvis is beta already.

**Comment by fritsch** [comment]
You can pick it yourself, of course - and rebuild Isengard - it applies without issues ... and easy to do for personal usage.

**Comment by trustin** [comment]
Ahh, didn't realize it's beta since the latest tag was 16.0a4. No worries - I have rebuilt Isengard and all is well. Thank you for your patience, folks.

**Pull request merged**
