### PR TITLE
[depends] update taglib to 1.10

### PR DESCRIPTION
**Pull request by stefansaraev**
linux (ubuntu) uses 1.9.1 already, most recent distros - too. it is already bumped for windows.

I dont know what to do with lib/taglib/ (darwin specific, is it still used ? //cc @Memphiz) - if you want me update it - someone should upload 1.9.1 tarball to build-deps/darwin-libs/

### CODE REVIEW

**Comment by Memphiz** [comment]
lob/taglib is neither used by osx nor by ios ... we use what is in depends...

**Comment by MrMC** [comment]
like god intended :)

**Comment by Razzeee** [comment]
Might solve http://trac.kodi.tv/ticket/15669

**Comment by stefansaraev** [comment]
ok. as this will be K**** and new upstream taglib release is available, let's give it a try.

**Comment by wsnipex** [comment]
can you kill lib/taglib while at it?

**Comment by stefansaraev** [comment]
I did.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by DaveTBlake** [comment]
TagLib 1.10 seems to be returning empty ID3 v2.3 tags differently from earlier versions. Kodi's attempts to trim them and test for empty string etc. no longer work. This results in singles being taken as albums - the odd library behaviour @MartijnKaijser  has reported - and probably other oddities.

Not saying we need to revert, but I would like to know more about TagLib 1.10 returns for empty tags and how to detect that and/or trim them correctly.

**Comment by Razzeee** [comment]
Well there is a beta2 thats been out for months for the new version. Just waiting for the final, but we might want to check if it's fixed by that eventually.

**Comment by MartijnKaijser** [comment]
Final is tagged 3days ago

**Pull request merged**
