### PR TITLE
add info dialog support for directory providers

### PR DESCRIPTION
**Pull request by tamland**
Similar to context menus, this allow info dialogs to be opened on the home screen.

### CODE REVIEW

**Comment by Razzeee** [comment]
PVR Info is missing by design, correct?

**Comment by phil65** [comment]
Just gave it a quick shot, the rest seems to work as intended. 
Nice work again! :)

**Comment by tamland** [comment]
Thanks!
@Razzeee not _by design_, I just don't really use or know pvr so I'm hoping someone else who knows it better will. If nobody will I can give it a go..

**Comment by Razzeee** [comment]
Then let's ping some of them :) 
@ksooo @negge

**Comment by Jalle19** [comment]
@Razzeee what do you mean by "PVR Info"? Is the idea that something should happen if you press the Info button while the "TV" home screen item is selected? I think neither info nor context menu makes any sense in that case.

**Comment by tamland** [comment]
@Jalle19 This is about making the info dialogs that already in other windows work globally on the same items outside of those windows. Eg. when skins use directory providers. It works when you press 'info' on channels in the pvr window, so it should work on the same channels on the home screen.

**Comment by Jalle19** [comment]
Okay, I've never had any channels on my home screen. @xhaggi is more likely the person you need to talk too, I'm not very familiar with this GUI stuff.

**Comment by xhaggi** [comment]
Not if I found the time to do it for the pvr items but you only need the pvr demo addon to test if you want to try it by yourself. if you need help let me know.

**Comment by tamland** [comment]
@xhaggi  I do have a question:) Why is there so many ways to get the epg info: https://github.com/xbmc/xbmc/blob/8218d994fb3aa3826606517559d0af2bfb63a052/xbmc/pvr/windows/GUIWindowPVRBase.cpp#L769 What I need is basically an easy way to determine whether an info dialog can be shown or not, and obtain the necessary data for it.

**Comment by xhaggi** [comment]
this is necessary because you have different item types e. g. channel, timer etc which hold the association to the epg data. you could refactor the logic to the dialog's ShowFor() method and call it if the item is of type 'pvr'. same like you did for the other dialogs.

**Comment by MartijnKaijser** [comment]
Anything holding this up for merging?

**Comment by tamland** [comment]
merge windows?

**Comment by MartijnKaijser** [comment]
Alpha1 is next month (unless some one else really wants to push it) as code was so much in flux past weeks it didn't feel right to push it out for public.

**Comment by tamland** [comment]
Then I'll go ahead. The pvr dialogs can be tackled later.
jenkins build this please

**Comment by MartijnKaijser** [comment]
@tamland it seems default select action is not respected http://forum.kodi.tv/showthread.php?pid=2305421#pid2305421

**Comment by Razzeee** [comment]
That's (unfortunately) unrelated as far as I know. 

I ventured down that rabbit hole some time ago and if I remember correctly the home screen is basically calling a builtin. It constructs a string and calls a the play builtin.

**Pull request merged**
