### PR TITLE
MMAL: Update to new video buffers scheme 

### PR DESCRIPTION
**Pull request by popcornmix**
## Description
MMAL: Update to new video buffers scheme 

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by popcornmix** [comment]
Note, the GLES changes are not necessarily used by MMAL but are required to make it compile.
I've made changes that seemed appropriate but a platform dev that actually uses GLES for video rendering will need to test/fix.

**Comment by FernetMenta** [comment]
@popcornmix I just rebased vpupdates, could you please rebase too. there is an addition change in vpupdates: platforms need to register their codecs into CDVDFactoryCodec

**Comment by popcornmix** [comment]
@FernetMenta By calling RegisterHWVideoCodec?
Can you point at an example of where that should be called from?

**Comment by FernetMenta** [comment]
@popcornmix check out vdpau: https://github.com/xbmc/xbmc/commit/e6504982aff45628ce28ca25e2e5ec4bd2305419

The platform (windowing) calls Register on the decoder. This functions checks additional capabilities and if the decoder would work in gerneral. If it works, it gets registered into the factory.
https://github.com/xbmc/xbmc/commit/51f4cac4f64d2aa3de49776053a706ecea9c4554

**Comment by FernetMenta** [comment]
this example was for hwaccel. HWVideoCodec works very similar

**Comment by popcornmix** [comment]
@FernetMenta updated to new registering scheme.

**Comment by FernetMenta** [comment]
@popcornmix thanks!

**Pull request merged**
