### PR TITLE
[pvr] fix missing epg observable message handling in pvr windows

### PR DESCRIPTION
**Pull request by xhaggi**
This will adds some missing epg observable messages to the switch/case in PVR window's OnMessage() to solve the stale epg info issue which was mentioned by @FernetMenta some while ago.

I ran into this issue while I'm working on the pvr startup window PR and noticed that the EPG info was not updated while staying in the channel window. And as we link recordings + timers to an EPG info tag it make sense to add the same to these windows too. 

The messages will tigger a `SetInvalid()` which will refresh the listed items on the screen.

@opdenkamp or @Jalle19 mind taking a look.

### CODE REVIEW

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by xhaggi** [comment]
@FernetMenta may certainly give it a try?

**Comment by ksooo** [comment]
Cannot reproduce this. Works just fine for me without your PR. 

Opened channel window, epg info was updated automatically, both on the left side (channel list) and on the right side (selected channel). Tested over 30 mins, using Confluence on latest 15.1

Could it be the case that it works under normal circumstances, but not in some special context? 

Could you please give me step by step instructions on how to reproduce.

**Comment by Jalle19** [comment]
I'll maybe have time to test during the weekend. The idea looks good, I'm mostly concerned whether the channel list will flicker a lot of e.g. tvheadend's asynchronous updates are enabled (which may trigger a lot of EPG updates).

**Comment by ksooo** [comment]
> I'm mostly concerned whether the channel list will flicker a lot of e.g. tvheadend's asynchronous updates are enabled (which may trigger a lot of EPG updates).

We definitely need to keep an eye on this. Runtime-testing is mandatory here.

**Comment by xhaggi** [comment]
> Could it be the case that it works under normal circumstances, but not in some special context?
> 
> Could you please give me step by step instructions on how to reproduce.

sure, you need this PR https://github.com/xbmc/xbmc/pull/7664 and set the startup window to TV in the settings. Restart Kodi and wait until the PVR manager is ready. You will end-up in the TV channel window and the EPG info/progress bar is empty. Important: don't move your mouse which will cause the list to refresh.

**Comment by xhaggi** [comment]
> I'm mostly concerned whether the channel list will flicker a lot of e.g. tvheadend's asynchronous updates are enabled (which may trigger a lot of EPG updates).

@Jalle19 if this is really an issue we could trigger the refresh only after a period of time, like @ksooo did for the EPG grid.

**Comment by xhaggi** [comment]
Therefore I would prefer to add it to `CGUIWindowPVRBase::SetInvalid();`, really easy ;)

**Comment by xhaggi** [comment]
Before we ran into this issue, I've limited the refresh amount to max one per 2 seconds.

**Comment by xhaggi** [comment]
I've pushed another commit which register the channel osd as observer for the epg container to obtain messages about changes to the epg items. This does the same as we do for PVR windows, it will refresh the item list once per 2 seconds. This will fix the stale epg info if you stay at the channel osd.

**Comment by xhaggi** [comment]
@Jalle19 it would be nice if you could test/debug this a bit on the weekend.

**Comment by FernetMenta** [comment]
nice! will test this evening and report back

**Comment by xhaggi** [comment]
perfect, let me know if it works.

**Comment by xhaggi** [comment]
@FernetMenta does a test run and reported it back in #6937
> very nice and thank you very much! Now epg gets visible right after vnsiserver requests an update.

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by xhaggi** [comment]
@Jalle19 did you found time to give it a try

**Comment by xhaggi** [comment]
runtime tested and works as it should.
jenkins build and merge

**Comment by xhaggi** [comment]
build error unrelated

**Pull request merged**
