### PR TITLE
Bump libcec to 4.0.4

### LINKED ISSUE #15073: Mac os X Mojave does not detect Pulse Eight libcec correctly
## Bug report
MacOS Mojave have broken the support for Pulse-Eight CEC
### Describe the bug
Here is a clear and concise description of what the problem is:
Pulse-Eight CEC is detected differently in Mojave than in previous versions of the and does therefore not work in Kodi. 
For more information about this issue, have a look here: https://github.com/plexinc/plex-media-player/issues/800

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

when I connect the pulse-eight libcec box to the PC I expect that it will be detected automatically

## Actual Behavior

It does not show up under the peripherals in the settings

## Possible Fix

update libcec to version 4.0.3 as done here: https://github.com/plexinc/plex-media-player/issues/800

### To Reproduce

1. connect pulse-eight cec adapter to the pc
2. go to Setting -> System -> Input -> Peripherals
3. the libcec device is not listed

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: MacOS Mojave 
 - Kodi version:
Leia RC2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by yol**
Apparently fixes an important issue with USB detection on
Mac OS X Mojave (Pulse-Eight/libcec#432)

Fixes #15073

@MartijnKaijser Also strong candidate for v18 if it fixes the issue

### CODE REVIEW

**Comment by MilhouseVH** [comment]
You should take https://github.com/Pulse-Eight/libcec/commit/f7593243377687c84c27b4e0342b00bb2ef2efbc as well unless you want problems with Samsung TVs.

**Comment by pkerling** [comment]
Then we should probably wait for 4.0.4

**Comment by MilhouseVH** [comment]
We've had https://github.com/Pulse-Eight/libcec/commit/f7593243377687c84c27b4e0342b00bb2ef2efbc in LibreELEC test builds for a few weeks now and no further problems. Personally I'd go with 4.0.3 plus a patch for the Samsung TV issue, as there's no saying when 4.0.4 will be released (or what other issues 4.0.4 will have).

**Comment by pkerling** [comment]
So far there's only the commit you mentioned and @opdenkamp has said that he wants to tag 4.0.4 soon-ish, so I'd say wait for a few days more.

**Comment by pkerling** [comment]
jenkins build this please

**Comment by pkerling** [comment]
jenkins build this please

**Review by Rechi — APPROVED** [review]

**Comment by opdenkamp** [comment]
> So far there's only the commit you mentioned and @opdenkamp has said that he wants to tag 4.0.4 soon-ish, so I'd say wait for a few days more.

so why aren't you waiting :)

**Comment by opdenkamp** [comment]
fyi, https://github.com/Pulse-Eight/libcec/commit/f7593243377687c84c27b4e0342b00bb2ef2efbc is required or users with a Samsung TV and an amp will run into trouble.
there's also an issue with 16 byte tx messages that I was looking at earlier this week, but that's 99% sure firmware. if not, then that would need another (small) change in code.
that's also the reason why it's been tagged, but not merged into the release branch

**Comment by opdenkamp** [comment]
oh and another fyi, it does fix the mac mojave issue, so if you want to not get shit from mac users, you need to pull this once it's done ;)

**Comment by pkerling** [comment]
> so why aren't you waiting :)

I am, did you see this getting merged?

**Comment by opdenkamp** [comment]
not you personally, but:
>  Rechi approved these changes 3 hours ago 

which is a bit too soon, it shouldn't be approved like this

**Comment by pkerling** [comment]
I think you're reading too much into that :-) It just means "I'm okay with this change in principle", not "it must be merged immediately". I've added tags for clarity though.

**Comment by Rechi** [comment]
There is nothing wrong with bumping it to 4.0.3 yet and updating it again once 4.0.4  is released. Or is there a know bug in 4.0.3, which isn't in 4.0.1?

**Comment by opdenkamp** [comment]
> I think you're reading too much into that :-) It just means "I'm okay with this change in principle", not "it must be merged immediately". I've added tags for clarity though.

it used to mean "ready to press the nice green button" ;)


> There is nothing wrong with bumping it to 4.0.3 yet and updating it again once 4.0.4 is released. Or is there a know bug in 4.0.3, which isn't in 4.0.1?

there is, see https://github.com/xbmc/xbmc/pull/15095#issuecomment-449369844
I'll probably tag 4.0.4 tonight

**Comment by pkerling** [comment]
> There is nothing wrong with bumping it to 4.0.3 yet and updating it again once 4.0.4 is released.

In principle, yes. But at RC4 stage I want to avoid bumping deps more often than necessary. It complicates bug analysis for people on nightlies.

**Comment by opdenkamp** [comment]
introducing a regression when you're at RC stage is indeed not a good idea ;)

**Comment by opdenkamp** [comment]
didn't have time to debug today, so I've pushed the 4.0.4 tag without a fix for 16 byte tx. that won't cause trouble in practice and isn't new. I'll push that to the release branch as soon as it's built and checked, but that will probably be after xmas

feel free to pull this

**Comment by pkerling** [comment]
Jenkins is happy, let's go for it

@opdenkamp Thanks for your work and the timely release

**Pull request merged**
