### PR TITLE
[cleanup] Cleanup system.h unused defines

### PR DESCRIPTION
**Pull request by hudokkow**
See title.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
From my side OK and good to remove the no more needed parts.

**Review by FernetMenta — APPROVED** [review]

**Review by AlwinEsch — APPROVED** [review]

**Comment by MartijnKaijser** [comment]
@hudokkow please rebase

**Comment by hudokkow** [comment]
Done.

**Comment by hudokkow** [comment]
jenkins build and merge

**Pull request merged**
