### PR TITLE
[cmake] implement URL_HASH + FindLibDvd update

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Use URL_HASH for "internal" cmake dependencies. This has no effect on tools/depends builds of the same dependencies
change ARCHIVE introduced in #20811 to be a targeted var name (eg FFMPEG_ARCHIVE)

@wsnipex i put in the findlibdvd cmake_exe_linker_flags change. if youd prefer not to do that at this time, happy to drop from here, just let me know.

Ive also just added hash to our github hosted repo release (libdvd*, ffmpeg), as discussed, can remove the hash checks for them. I figure maybe just put them in for now, and i'll get the tarballs setup on mirrors upload to migrate to serving from there in the not too distant future.

## Motivation and context
Cleaning up and working on some baseline stuff for cmake full dependency builds

## How has this been tested?
testing outputs/functions for windows/unix/apple without KODI_DEPENDS path

## What is the effect on users?
N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
Just an FYI I tried to do this a couple years ago but it was shutdown because it was deemed that all the depends should have their checksums check not just the cmake depends, ref: https://github.com/xbmc/xbmc/pull/17510

**Comment by fuzzard** [comment]
Id forgotten about that, and i even had a comment in it, haha.

With that said, im of the opinion that we should move forward with this anyway. No one stepped up with a PR to do hash checking in tools/depends, so it must not be that vital. Lets do the low hanging fruits of cmake that supports hash checking, and move on.

Just as a side note, i appreciate all the stuff you've done that has never been merged. Thank you for the time you put into the project over the years @lrusak

**Comment by lrusak** [comment]
> Id forgotten about that, and i even had a comment in it, haha.
> 
> With that said, im of the opinion that we should move forward with this anyway. No one stepped up with a PR to do hash checking in tools/depends, so it must not be that vital. Lets do the low hanging fruits of cmake that supports hash checking, and move on.

I'm fine with getting this change in also as I think it's a great improvement.

> Just as a side note, i appreciate all the stuff you've done that has never been merged. Thank you for the time you put into the project over the years @lrusak

Cheers, it means a lot 👍

**Review by wsnipex — APPROVED** [review]
Looks good!

since I promised to add hashing for depends: https://github.com/wsnipex/xbmc/commits/depends_hash_checking

**Comment by fuzzard** [comment]
I'll look to merge this as is for now @wsnipex after jenkins is happy.

Have left a couple comments on your branch about some apple specific stuff and a small copy pasta i saw. Let me know if the apple stuff wasnt clear

**Comment by lrusak** [comment]
jenkins build this please

**Comment by howie-f** [comment]
looks like i get garbage downloaded now for the fmt-source.
```
-- Downloading... done
-- extracting...
     src='/home/fhw/.tmp/.kodi-build20/build/download/archive.tar'
     dst='/home/fhw/.tmp/.kodi-build20/build/fmt/src/fmt'
-- extracting... [tar xf]
CMake Error: Problem with archive_read_open_file(): Unrecognized archive format
```

```
-rw-r--r--  1 fhw fhw    91787 Jan 25 12:03 archive.tar
-rw-r--r--  1 fhw fhw    45652 Jan 25 11:51 crossguid-8f399e8bd4.tar.gz
-rw-r--r--  1 fhw fhw 13717391 Jan 25 11:51 ffmpeg-4.4-N-Alpha1.tar.gz
-rw-r--r--  1 fhw fhw  1538022 Jan 25 11:51 flatbuffers-2.0.0.tar.gz
-rw-r--r--  1 fhw fhw   101068 Jan 25 11:51 libdvdcss-1.4.2-Leia-Beta-5.tar.gz
-rw-r--r--  1 fhw fhw   137942 Jan 25 11:57 libdvdnav-6.0.0-Leia-Alpha-3.tar.gz
-rw-r--r--  1 fhw fhw   130649 Jan 25 11:53 libdvdread-6.0.0-Leia-Alpha-3.tar.gz
fhw@xbmc-build:~/.tmp/.kodi-build20/build/download () $ tar xf archive.tar 
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

**Pull request merged**
