### PR TITLE
StackHelper increase part times precision to msec and bugfix

### PR DESCRIPTION
**Pull request by Voyager1**
see title
## Description

following PR #13235 some CApplicationStackHelper internals are modified to increase times precision to double (instead of int). Also, CFileItem's startOffset & endOffset are now properly used as seconds multiplied by 75. It was incorrectly used by CApplicationStackHelper in #13235, but not really an issue as long as the startOffset & endOffset were not used by anything else. Now this is in line and shouldn't be an issue with the rest of the code.

## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Voyager1** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
why floating point?

**Comment by Voyager1** [comment]
> why floating point?

because stack parts are usually not exactly multiples of whole seconds long. The example I was testing for the previous PR had a two parts: first part 3808.099 s, the total 7737.736 s. The problem is that while it works reasonably well with integer seconds, you can run into the following issue: let's say you seek to a timestamp that is within 1s of the end or the beginning of a stack part. Because with integer, the start/end times of the part will be in whole seconds (truncated from the real start/end) the code may think to open part N+1 instead of part N. 

Also the start/end offsets in FileItem are in 1/75ths of a second (or 0.013 s). So in order to precisely set these values, you need to multiply the timestamp x 75 and this can lead to an error of up to 75 if not using a floating point timestamp.

**Comment by FernetMenta** [comment]
Units of player related times should milliseconds not seconds. Fractions of ms make no sense in this context.
If an integer is too small for the max value, you should migrate to int64_t with units being ms.

**Comment by Voyager1** [comment]
> Units of player related times should milliseconds not seconds. Fractions of ms make no sense in this context

hey, I'm not talking about fractions of ms! Current stacking code is in **seconds**... I hope you agree that this is not fine grained enough?!

**Comment by Voyager1** [comment]
I can certainly convert it to milliseconds if you prefer that? In that case I'll have to use int64_t indeed...
Just another thought. Folks who have stacks in their videodatabase will have an issue because the column "TIMES" in the table "STACKTIMES" stores everything in seconds. Unless we can clear that table once after this, we run the risk of loading stack times that are way off.

**Comment by FernetMenta** [comment]
Currently we have different units which is error prone. I think we should take the chance and switch to ms whenever we touch code that uses seconds.
For the db issue: either keep seconds in the db and convert to (and from) ms inside the db wrapper or increase db version and add a convert statement.

**Comment by Voyager1** [comment]
@FernetMenta - as discussed. Everything in milliseconds.
For legacy, still need to convert *75/1000 for the FileItem m_Start/EndOffsets, and the VideoDB still stores in seconds using floating point notation. Should be good now.

**Comment by Voyager1** [comment]
jenkins build this please

**Comment by ace20022** [comment]
At least add a check where you cast to int, imo. Btw I've started something similar but with int64 since ffmpeg uses that https://github.com/ace20022/xbmc/commits/int64

**Comment by Voyager1** [comment]
> At least add a check where you cast to int

are you referring to the 4 instances where the uint64_t needs to be converted to an int? There's plenty of other places where this happens. Yes we could check against numeric_limits<int>::max() but what do you suggest if it doesn't fit and the cast is impossible? throw an exception? Realistically we never hit that condition anyway, because the positive range of a 32 bit int goes to 2147483648. If that's an amount in ms, then we can manage 2.1 million seconds or 596.5 hours. Again realistically we won't ever have materials that have a runtime of that long... I agree in theory but instead of writing checking code all over the place, I would actively start hunting down those int members and convert them to int64_t like you started. Agree?

**Review by FernetMenta — APPROVED** [review]

**Comment by Voyager1** [comment]
Jenkins Win64 failure related to random Test execution fail. Merging.

**Comment by Voyager1** [comment]
@ace20022 in case you're interested - I've made a good attempt at uplifting CFileItem::m_lStartOffset and m_lEndOffset to int64_t, here:  https://github.com/Voyager1/xbmc/commit/33f71c446700b6cfa94a067db1d48573e6f931ad

**Pull request merged**
