### PR TITLE
[Backport][CurlFile] Disable CURLOPT_AUTOREFERER (default value)

### PR DESCRIPTION
**Pull request by smf007**
## Description
Backport of Pull #17826.  In master since 2020 July 3.

## Motivation and Context
Resolves redirect issues with Inputstream.adaptive.  See https://github.com/peak3d/inputstream.adaptive/issues/184
Downstream impact on add-ons like CBC, https://github.com/micahg/plugin.video.cbc/issues/8

## How Has This Been Tested?
Tested on master, Win10 64bit.  Will test again with Leia after Jenkins builds it.

## Screenshots (if appropriate):
N/A

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by smf007** [comment]
Still seems to be a problem, so closing this.

**Comment by lrusak** [comment]
Why close?

**Comment by smf007** [comment]
@Irusak turns out it didn't fix the problem as stated in the description above.  As such, I'm not sure on the reason to backport.

**Comment by lrusak** [comment]
So did you PR it just so Jenkins would build it for you?

**Comment by smf007** [comment]
Error in my testing.  I didn't run the test long enough to confirm.  After doing the pull, my test eventually failed.

**Pull request closed without merging**
