### PR TITLE
[cleanup] Remove HAS_VIDEO_PLAYBACK nonsense.

### PR DESCRIPTION
**Pull request by hudokkow**
See title.

ping @FernetMenta

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
was this something that was intended to be used in some way in case we did headless?

**Comment by hudokkow** [comment]
Don't know. I can see in some places (of xbmc-antiquated) that it is code with 9+ years. After that, someone messed with it but I can't recall now.

**Comment by hudokkow** [comment]
@smallint was the last one that touched some of that code and commented
> // TODO: remove this crap: HAS_VIDEO_PLAYBACK
// instantiateing a vidio control having no playback is complete nonsense

See https://github.com/xbmc/xbmc/commit/9c5cfb9640f0019ddd63e139179424a59abc5468 and https://github.com/xbmc/xbmc/commit/9c5cfb9640f0019ddd63e139179424a59abc5468#diff-d193d0b8dc3f80a40033e74f450c17cfR90

After that you updated doxy.

**Comment by notspiff** [comment]
This was added when the initial ports from xbox was in progress.

**Review by FernetMenta — APPROVED** [review]

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Pull request merged**
