### PR TITLE
cmake: refactor/cleanup addon dependency buildsystem

### PR DESCRIPTION
**Pull request by Montellese**
I just realized that the `add_addon_depends` cmake function introduced by @wsnipex to handle dependencies defined by binary addons is basically an extended version of what I initially wrote for dependencies defined as part of the binary addon buildsystem. As the new logic handles more cases and because code duplication sucks I changed the implementation of the cmake addon dependency buildsystem to simply call `add_addon_depends` with the proper path (and keep the addition to call a platform-specific CMakeLists.txt as available for WIN32).

### CODE REVIEW

**Comment by Montellese** [comment]
jenkins build this please

**Comment by Montellese** [comment]
jenkins build this please

**Comment by Montellese** [comment]
@wsnipex: Are you ok with this? It doesn't really affect anything else than WIN32 right now anyway.

**Comment by wsnipex** [comment]
sure, de-duplication is always good.

**Pull request merged**
