### PR TITLE
Remove fallback definition of FILE

### PR DESCRIPTION
**Pull request by coypoop**
the typedef provided is wrong on most platforms, so they have chosen to use -D_FILE_DEFINED.
rather than do this, don't provide a fallback definition. standard C promises that FILE is defined in stdio.h

build tested only on a currently unsupported platform (NetBSD) - I haven't succeeded in running it yet.

### CODE REVIEW

**Comment by coypoop** [comment]
that failure is due to hitting a time limit on the tests, not a build issue

**Comment by notspiff** [comment]
the xbox pretty much ignored all such standards. this should be all good to kill.

**Comment by Rechi** [comment]
maybe @Paxxi knows something about it

**Comment by notspiff** [comment]
this codes originates from xbplayer i believe, back on the original xbox in 2002. nobody around except me should anything about this ;) we basically had to hook a homegrown posix io right into the kernel, and this definition was part of that effort. it was then put under an ifdef when the initial linux/windows ports happened instead of simply removed. i believe that struct is compatible with what mingw had back then (so we could load mplayer.dll).

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by Rechi** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
@coypoop thanks for your contribution

**Pull request merged**
