### PR TITLE
CMake: fixed correct minimal CMake version for Win32

### PR DESCRIPTION
**Pull request by Karlson2k**
Backport of https://github.com/xbmc/xbmc/pull/19253

### CODE REVIEW

**Review by afedchin — APPROVED** [review]

**Comment by DaveTBlake** [comment]
I'll believe you that  3.15 is sufficient, but I do wonder why the docs https://github.com/xbmc/xbmc/blob/master/docs/README.Windows.md says

**WARNING:** Is required CMake version >= 3.8.

**Comment by Karlson2k** [comment]
@DaveTBlake May worth to be updated. Where to start? Matrix directly or `master` and then backport.

**Comment by DaveTBlake** [comment]
Even with doc updates it is master first then backport. 
But honestly I'm not that concerned that the documentation suggests people have a higher version than is absolutely necessary. I was more interested in _why_ it says `3.8`. I even vaguely remember having to install a new version some time, but that could be something else. Wonder what the docs say for the other platforms?

**Comment by DaveTBlake** [comment]
Ha, Git knows everything - CMake v3.8 is needed for VS2019 compatibility

**Comment by Karlson2k** [comment]
Yep, v3.8 is required for VS2019.
v3.15 is required for `list PREPEND`. However, for Matix it could be replaces with `list INSERT 0` which is available with previous CMake versions.

**Comment by thexai** [comment]
> I'll believe you that 3.15 is sufficient, but I do wonder why the docs

Hey I want clarificate that 3.15 is greater than 3.8 in CMake versioning schema:
https://cmake.org/cmake/help/latest/release/index.html

so VS2019 elevates required ver to 3.8 (that is very old).

and this PR elevates more to 3.15

Maybe is sufficient upgrade all docs with 3.15 at same time this gets merged

**Review by garbear — APPROVED** [review]

**Pull request merged**
