### PR TITLE
VideoPlayer: simplify locking in renderer

### PR DESCRIPTION
**Pull request by FernetMenta**
cleanup old work arounds. if you need a "RetakeLock" or a shared section, something has gone wrong elsewhere.

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by fritsch** [comment]
When I see it right, it might deadlock between Configure and FrameMove

**Comment by fritsch** [comment]
@stefansaraev can you post a backtrace here, please?

**Comment by stefansaraev** [comment]
fyi. this deadlocks for me on linux/aml. after ~ 20 seconds while watching tv. sadly backtrace is not useful http://sprunge.us/gXGe

**Comment by FernetMenta** [comment]
looks like a AML issue to me. CRendererAML::RenderUpdateVideoHook calls back into codec and codec back into gfx context. that needs some cleanup.

**Comment by FernetMenta** [comment]
all parameters needed for render MUST be set before call to render. that scenario I mentioned before is no-go.

**Comment by fritsch** [comment]
Looks like IMX, LinuxRenderGLES, MediaCodec and Android need change if I see it right.

**Comment by FernetMenta** [comment]
why LinuxRenderGLES?

**Comment by fritsch** [comment]
That not - sorry. Was too fast while grepping. Yeah - the other three. IMX accesses its global :-(

**Comment by FernetMenta** [comment]
regarding IMX I only see an issue for stereo modes

**Comment by fritsch** [comment]
Btw. returning true in AMLogic's UpdateRenderHook also causes a deadlock - so something else also introduces a circular dependency

**Comment by FernetMenta** [comment]
would you have a bt and log for this

**Comment by fritsch** [comment]
@stefansaraev can provide one - I still don't have an amlogic box up and running.

**Comment by stefansaraev** [comment]
I could not catch an useful backtrace. it's all corrupt stack ;(

every time it deadlocked (with or without returning true in UpdateRenderHook), it was always at the same millisecond this was logged.
```
22:31:30 T:2797786032  NOTICE: CDVDMessageQueue::GetLevel() - can't determine level
````

**Comment by FernetMenta** [comment]
CDVDMessageQueue::GetLevel() - can't determine level is an indicator that buffers ran dry. means no data coming from demuxer. can you reproduce with a different source?

**Comment by stefansaraev** [comment]
also with
```
bool CRendererAML::RenderUpdateVideoHook(bool clear, DWORD flags, DWORD alpha)
{
  ManageDisplay();
  return true;
}
```
besides the complete black screen and only audio played. still fsckd up backtrace http://sprunge.us/NbdG and again dead at CDVDMessageQueue::GetLevel() http://sprunge.us/bAVP :(

> can you reproduce with a different source

yes. same thing with media played from nas.

**Comment by FernetMenta** [comment]
please post debug log and bt if available when playing something that does not use file cache.

**Comment by stefansaraev** [comment]
same thing: http://sprunge.us/WRbJ

shall we move the discussion to slack or irc to not spam everyone ?

**Comment by popcornmix** [comment]
This PR deadlocks on Pi with subs. Unfortunately gdb is not happy so can only see backtrace of main thread
http://paste.ubuntu.com/14439591/

**Comment by fritsch** [comment]
See: https://github.com/FernetMenta/xbmc/commit/3f411bf96f6cb0241a5e4d74635f9d621425cd8d

**Comment by popcornmix** [comment]
That works for me.

**Comment by fritsch** [comment]
Thought so :-)

**Pull request merged**
