### PR TITLE
issues: changes to bug_report and issues templates

### PR DESCRIPTION
**Pull request by chewitt**
## Description
This PR makes some changes to the GitHub issues template:

a) Switch from markdown to yaml which allows us to use elements like textbox, input, drop-lists, etc. to make the form easier to follow, and to enforce some mandatory items
b) Simplify the form to combine the description and context items
c) Remove the confusing "team only" roadmap item form (which nobody appears to use)
d) Add forum links for Help and Support and Feature Requests to redirect those items

## Motivation and context
Encourage better reporting of bugs/issues and discourage feature-request issues from being opened here.

## How has this been tested?
Changes can be seen in my GitHub fork here: https://github.com/chewitt/xbmc/issues/new/choose

## What is the effect on users?
Users are forced to follow the form more directly, it's no longer possible to select-all/delete and avoid items

## Screenshots (if appropriate):
See https://github.com/chewitt/xbmc/issues/new/choose

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
Thumbs up from me.

Minor comments would be:

1. Platforms we will need webOS as a platform as well
2. For debug log line, we may want to add a URL link as an eg (eg: https://paste.kodi.tv) so those users who might not be familiar with paste sites can be directed to our hastebin site

Otherwise looks good to me at a glance

**Comment by chewitt** [comment]
I've added WebOS to the drop-list and tweaked the log text with a link to https://paste.kodi.tv/

**Comment by CastagnaIT** [comment]
yeah i like yml i have already used it from last year on my repo,
some my considerations

imo "possible-fix" id area should not forced as required, most of the time are users with no competence in developing
also "expected" id area imo should be optional, oftlen the bug description provided is already sufficient, but glad to have other opinions

for me there is a problem with the debuglog id area, it can happen, not rarely, that log text can be big size and pastebin cannot be used, then you have to attach the file or directly on text area, or use external sharing services, that usually are not good accepted from our rules.
I can try suggest some solutions, that can be discussed:
- convert the log field from "input" to "textarea" so that a log or more that one logs, can be attached directly, but the text area will become (visually) more large
- in the log field description, specify that the log files can be attached also directly in the bug description text area, so without use pastebin, but i point out that the log field is currently set as required, then if you attach log to the bug description you are forced to write something also in to this field to be able to publish the bug issue

**Comment by chewitt** [comment]
UWP typo fixed. I've added a separate log snippet/file textarea and labelled the existing URL as "preferred" .. hopefully we can encourage people to use paste URLs, and both are optional (not mandatory).

**Comment by CastagnaIT** [comment]
I am not very convinced about having two differents log fields,
i would like have more opinions by others before make new changes to PR,
also the description:

> "Provide a log snippet or log file that demonstrates the problem."

in my experiences often users tend not to follow the rules and paste thousands of log lines as text directly in the issue resulting in a very long and unmanageable issue
writing "Provide a log snippet..." seems to encourage this way, where instead should be something like
"Provide a debug log by drag-n-drop the file in the field or if the file is too large provide a link on where to download it"

**Comment by garbear** [comment]
I like the new format. The only change I would make is to turn "Debug Log URL (Preferred)" into "Debug Log URL (Required in most cases)"

I don't think we should require users to chop a debug log. Nothing in there is meant to be intelligible to them. We certainly don't want log spam in the issue, so we should have log uploading ability in this format.

**Comment by MartijnKaijser** [comment]
Except for the paintbucket about de debuglog go for it. Further tweaking can be done later.

**Comment by chewitt** [comment]
I tweaked the log upload textarea again. If you remove shell rendering it allows file upload. I added some placeholder text for the Kodi paste service to suggest/hint it, and revised the wording.

**Review by garbear — APPROVED** [review]

**Review by CastagnaIT — COMMENTED** [review]
imo these id fields:
expected, possible-fix, repro
should be optionals, so not mandatory

EDIT: at least for: expected, possible-fix

**Pull request closed without merging**
