### PR TITLE
Revert "DVDVideoCodecFFmpeg: Consistency fixes (buildsys rework in progress)"

### PR DESCRIPTION
**Pull request by fritsch**
Reverts xbmc/xbmc#12090

This is not how the game works. PRs are there for review.

### CODE REVIEW

**Comment by FernetMenta** [comment]
building ffmpeg on linux (not pi) already requires wrapper libs for vdpau + vaapi to be present. in this state it does not harm if this is also required for building kodi.
note that this has nothing to do with behavior, just building. in regard to behavior it does not matter if you build with those libs available at build time.

it would be nice if build system supports options bound to windowing target. once this is in place, the factore can be cleaned up. for now it does not really matter if this pr gets reverted or not. it won't change anything but some error logs during building, if a wrapper is not present.

**Comment by wsnipex** [comment]
it DOES matter as in the current state vaapi or vdpau silents get ignored if the other option is disabled.
This is a bug and a bigger one then before.

**Comment by candrews** [comment]
Since this PR was merged, I'm unable to build on Linux. The error is:
```
/var/tmp/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp: In member function ‘IHardwareDecoder* CDVDVideoCodecFFmpeg::CreateVideoDecoderHW(AVPixelFormat, 
CProcessInfo&)’:
/var/tmp/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp:1194:6: error: ‘VDPAU’ has not been declared
   if(VDPAU::CDecoder::IsVDPAUFormat(pixfmt) && CServiceBroker::GetSettings().GetBool(CSettings::SETTING_VIDEOPLAYER_USEVDPAU))
      ^~~~~
/var/tmp/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp:1195:16: error: ‘VDPAU’ does not name a type
     return new VDPAU::CDecoder(m_processInfo);
                ^~~~~
/var/tmp/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp:1195:21: error: expected ‘;’ before ‘::’ token
     return new VDPAU::CDecoder(m_processInfo);
                     ^~
/var/tmp/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp:1195:23: error: ‘::CDecoder’ has not been declared
     return new VDPAU::CDecoder(m_processInfo);
                       ^~~~~~~~
/var/tmp/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp:1195:23: note: suggested alternative:
In file included from /var/tmp/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp:1182:0:
/var/tmp/portage/media-tv/kodi-9999/work/kodi-9999/xbmc/cores/VideoPlayer/DVDCodecs/Video/VAAPI.h:410:7: note:   ‘VAAPI::CDecoder’
 class CDecoder
       ^~~~~~~~
```

I'm happy to provide additional details.

**Comment by FernetMenta** [comment]
install libvdpau-dev

**Comment by wsnipex** [comment]
this PR is not the cause.
The issue is that you need to enable both vaapi and vdpau if you want one of those.

**Comment by herrnst** [comment]
@candrews fix was right around the corner at https://github.com/xbmc/xbmc/pull/12089

**Comment by candrews** [comment]
> install libvdpau-dev

But I don't want vdpau; I want vaapi.

> this PR is not the cause.
> The issue is that you need to enable both vaapi and vdpau if you want one of those.

So if I want vaapi, I also need vdpau? (If that's the intended change, fine - I have no judgment, I just want to understand so I can update the Gentoo ebuild appropriately)

Also, If that is true, I feel like https://github.com/xbmc/xbmc/blob/master/CMakeLists.txt should check and error out if vaapi^vdpau, instead of waiting for a compilation error later?

**Comment by hauihau** [comment]
@FernetMenta why does one have to enable VDPAU and VAAPI in order to use one of them? Just ifdef them as before, or whats the problem with two ifdefs?

**Comment by FernetMenta** [comment]
the switch does not enable anything, it never did. if a system has no vdpau it won't get used at runtime, no matter if the switch was set during build.

**Comment by FernetMenta** [comment]
more verbose. I already have a working solution that det cts vaapi at startup and chacks capabilities. that can be used to hide settings if not available. you can always build with vdpau and vaapi. ffmeg gets build the same way.

**Comment by hauihau** [comment]
> the switch does not enable anything, it never did. if a system has no vdpau it won't get used at runtime, no matter if the switch was set during build.

Would you then please mind explaining me, what the purpose of https://github.com/xbmc/xbmc/blob/master/CMakeLists.txt#L142-L143 is? https://github.com/xbmc/xbmc/blob/master/cmake/modules/FindVAAPI.cmake#L50 enables HAVE_LIBVA which leads to the build error (analog to FindVDPAU setting HAVE_LIBVDPAU) as there is no more differentiation because you've changed the file in #11946 in a way that now, both VAAPI and VDPAU devel headers must be available in order to successfully compile kodi even when only one of them are requested. So the system sure now must to have VDPAU. I don't get the point what is wrong with #12089. The two ifdefs doesn't make the code hard to read or hard to maintain.

> more verbose. I already have a working solution that detects vaapi at startup and chacks capabilities. that can be used to hide settings if not available. you can always build with vdpau and vaapi. ffmeg gets build the same way.

"You can" is obviously wrong, as already said, VDPAU must be installed, otherwise you get the compiler errors from #12089.

Detecting what is available at startup should have nothing to do with this issue. We're talking about a build time issue and not runtime. No VDPAU installed => no successful compiler run. I consider this a breakage.

**Comment by herrnst** [comment]
Additional note: FFmpeg always builds perfectly with or without vdpau or vaapi libs/headers installed, be it the system package or the embedded one. FFmpeg never complained about missing libva stuff on me in both cases.

**Pull request merged**
