### PR TITLE
[json-rpc] Addons.SetAddonEnabled: add optional parameter disabledReason

### PR DESCRIPTION
**Pull request by Portisch**
## Description

By the optional parameter it is possible to use user defined disable reason.

## Motivation and Context

A while ago the possibility to set a disable reason was added: https://github.com/xbmc/xbmc/commit/8c028fe255491a5c340cf50e134511f865867c30
Since merge of PR #19033 a pop up happen if a addon is getting disabled by `jsonrpc`.
I just think the optional parameter got missed by https://github.com/xbmc/xbmc/commit/8c028fe255491a5c340cf50e134511f865867c30

When disabledReason is not set (0) it get automatic set to AddonDisabledReason::NONE and you will get a pop up on next Kodi start. If disabledReason is set to AddonDisabledReason::USER on disable by `jsonrpc` there is no pop up.

## How Has This Been Tested?

On last master HEAD.

**Enable by not using param disabledReason**
```text
./json.sh '{"jsonrpc":"2.0","method":"Addons.SetAddonEnabled","params":{"addonid":"driver.dvb.crazycat","enabled":true},"id":1}'

---------------------------------------------------
Request: {
    "jsonrpc": "2.0",
    "method": "Addons.SetAddonEnabled",
    "params": {
        "addonid": "driver.dvb.crazycat",
        "enabled": true
    },
    "id": 1
}
---------------------------------------------------
Response: {
    "id": 1,
    "jsonrpc": "2.0",
    "result": "OK"
}
```
**Disable by using param disabledReason**
```text
./json.sh '{"jsonrpc":"2.0","method":"Addons.SetAddonEnabled","params":{"addonid":"driver.dvb.crazycat","enabled":false,"disabledReason":1},"id":1}'

---------------------------------------------------
Request: {
    "jsonrpc": "2.0",
    "method": "Addons.SetAddonEnabled",
    "params": {
        "addonid": "driver.dvb.crazycat",
        "enabled": false,
        "disabledReason": 1
    },
    "id": 1
}
---------------------------------------------------
Response: {
    "id": 1,
    "jsonrpc": "2.0",
    "result": "OK"
}
```
**Disable by not using param disabledReason**
```text
./json.sh '{"jsonrpc":"2.0","method":"Addons.SetAddonEnabled","params":{"addonid":"driver.dvb.crazycat","enabled":false},"id":1}'

---------------------------------------------------
Request: {
    "jsonrpc": "2.0",
    "method": "Addons.SetAddonEnabled",
    "params": {
        "addonid": "driver.dvb.crazycat",
        "enabled": false
    },
    "id": 1
}
---------------------------------------------------
Response: {
    "id": 1,
    "jsonrpc": "2.0",
    "result": "OK"
}
```

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by howie-f** [comment]
thanks for looking into it @Portisch 
imo the correct fix is not changing the JSON-RPC interface, but to make sure to set `disabledReason::USER` not `NONE` when an add-on gets disabled by this json-rpc call. so most likely the fix needs to go here:
https://github.com/xbmc/xbmc/blob/8c761c47089e49a0c11b03c14c65d7dc8f8b1108/xbmc/interfaces/json-rpc/AddonsOperations.cpp#L144
perhaps @phunkyfish / @DaveTBlake can confirm

**Review by DaveTBlake — CHANGES_REQUESTED** [review]
Changes to JSON API at this stage of the release cycle are to be avoided when possible. Non-breaking changes can be made as essential fixes, but need careful consideration. 

For future reference, changes to JSON methods require an appropriate bump in schema version too - this code would be a non-breaking change hence v12.1.0

> imo the correct fix is not changing the JSON-RPC interface

If there is another approach then that is preferable by far.

**Comment by Portisch** [comment]
> imo the correct fix is not changing the JSON-RPC interface, but to make sure to set `disabledReason::USER` not `NONE`

When do this you remove the possibility to set `disabledReason` got introduced by https://github.com/xbmc/xbmc/commit/8c028fe255491a5c340cf50e134511f865867c30 and force a new default value USER.

Default was before NONE and should be after this PR also NONE to remain backward compatible. If needed the the user can adapt his jsonprc call like this: https://github.com/CoreELEC/script.program.driverselect/commit/6a5dc7385b19428eddba93bc051f3b829cfd994b

**Comment by Tolriq** [comment]
The value is an enum, the enum should be properly defined in the JSON API too, do not expose private internal values that could change and without any control so that user could put currently unused values in too with unknown side effects now and in the future when they are used.

If it's added as a setter it should be added as a getter too so returned from GetAddons/GetAddonsDetails with again proper enum value and not raw internal private ints.

**Comment by Portisch** [comment]
This sounds the implementation of https://github.com/xbmc/xbmc/commit/8c028fe255491a5c340cf50e134511f865867c30 is faulty in general. Please feel free to fix it properly and close this PR by a new one, thank you. I am not a JSON expert.

**Comment by howie-f** [comment]
> This sounds the implementation of [8c028fe](https://github.com/xbmc/xbmc/commit/8c028fe255491a5c340cf50e134511f865867c30) is faulty

that's what i feel too. that's why i pointed to the codeblock above. at least an existing issue discovered, thanks

**Comment by howie-f** [comment]
superseded by https://github.com/xbmc/xbmc/pull/19097

**Pull request closed without merging**
