### PR TITLE
Add new mergable rule for release

### PR DESCRIPTION
**Pull request by razzeee**
This should prevent both files getting out of sync

### CODE REVIEW

**Comment by yol** [comment]
I don't really know, also haven't found anything in the docs

**Comment by basilgello** [comment]
@razzeee I suggest playing on a fork of xbmc repo. Can you set the mergeable on your forked repo and try editing version.txt in master?

**Comment by DaveTBlake** [comment]
As far as I'm concerned, as Release Manager and person that bumps version.txt, this is **unnecessary**. The RM just needed to know it is part of the release protocol, and I now do and have added it to my notes. 

There are plenty of other aspects of releasing that are not covered by jenkins etc., an example very similar is tying the update of splash.jpg to version.txt changes. It is also  possible version.txt could be edited without changing version number and need to change anything else.

Finally doesn't a point release mean both Matrix (or whatever the current release) and master branches will need a change to `tools/Linux/kodi.metainfo.xml.in`  and thus separate PRs?

**Review by DaveTBlake — CHANGES_REQUESTED** [review]
As far as I'm concerned, as Release Manager and person that bumps version.txt, this is unnecessary. The RM just needed to know it is part of the release protocol, and I now do and have added it to my notes.

There are plenty of other aspects of releasing that are not covered by jenkins etc., an example very similar is tying the update of splash.jpg to version.txt changes. It is also possible version.txt could be edited without changing version number and need to change anything else.

Finally doesn't a point release mean both Matrix (or whatever the current release) and master branches will need a change to `tools/Linux/kodi.metainfo.xml.in` and thus separate PRs?

**Comment by razzeee** [comment]
> Finally doesn't a point release mean both Matrix (or whatever the current release) and master branches will need a change to tools/Linux/kodi.metainfo.xml.in and thus separate PRs?

Yes, but that shouldn't affect this logic in any negative way. You might in fact be able to skip the master changes for the time being and only do them whenever a release is planned.

But in general, I would agree with you. Do we have any documentation on relesing?
I normally go with at least a markdown file (for e.g. https://github.com/trakt/script.trakt/blob/main/HOW_TO_RELEASE.md). So I'm asking if I can add that instruction there / if we should create such a file.

**Comment by DaveTBlake** [comment]
>  Do we have any documentation on releasing?
>  So I'm asking if I can add that instruction there / if we should create such a file.

@razzeee all I have are my draft notes that I have collected while stumbling through doing the later Leia point releases and onwards (maybe I have even been doing it wrong!). I also delegate a number of the tasks so unaware of fine details just co-ordinate that they happen.

The intention was a document of some kind some where, but I have not found time (or motivation TBH) to create it  yet. I promise to leave the team my notes in the event of my untimely demise!!

**Comment by razzeee** [comment]
> The intention was a document of some kind some where, but I have not found time (or motivation TBH) to create it yet. I promise to leave the team my notes in the event of my untimely demise!!

Let's hope that will never happen :)

Still, I would even appreciate a MR with your draft notes, even if wrong. At least we could talk about it then/have others help out.

**Pull request closed without merging**
