### PR TITLE
[fix][libexif] Various fixes for exif processing

### PR DESCRIPTION
**Pull request by ace20022**

### CODE REVIEW

**Comment by ace20022** [comment]
jenkins build this please

**Comment by ace20022** [comment]
any objections?

**Comment by mkortstiege** [comment]
String seems to be unused, other than that no objections.

**Comment by ace20022** [comment]
The id is calculated using an offset, or which string do you mean?

**Comment by mkortstiege** [comment]
I mean the strings.po addition in https://github.com/ace20022/xbmc/commit/6791014a69035053f9ccf9d93b17c646a1c0e677

**Comment by MartijnKaijser** [comment]
@mkortstiege it's as said a string using an offset.

**Pull request merged**
