### PR TITLE
[configure] fix warning during compile configure.in  is deprecated

### PR DESCRIPTION
**Pull request by un1versal**
This renames configure.in to configure.ac both in main project and in sub-project goom and updates bootstrap.mk accordingly.

@wsnipex to review since this must be here still for some reason even though warnings seem to go away.

Cant be this simple can it?
Same as https://github.com/xbmc/xbmc/pull/6723 cause the guy clearly must not be used to using git.

### CODE REVIEW

**Comment by wsnipex** [comment]
find . -name configure.in
./configure.in
./xbmc/visualizations/Goom/goom2k4-0/configure.in
./xbmc/visualizations/Goom/goom2k4-0/gtk-gui-devel/configure.in
./tools/depends/configure.in
./lib/timidity/configure.in
./lib/libmodplug/configure.in

even though goom, timidity and modplug will be moved to addons soon, lets do it everywhere.

This PR is only the top of the iceberg to get rid of autotools/automake depecated stuff. We'd have to go through main and depends configures and replace a lot of deprecated macros with their successors. Since this is considerably more work then just the renaming nobody has done it yet.

**Comment by uNiversaI** [comment]
Thx for that, I was going to rename those and thers considerably more hits here https://github.com/xbmc/xbmc/search?utf8=%E2%9C%93&q=configure.in&type=Code
Am unsure if those are also good to go or if you need to redo the patches so on after.

In any case, this bit seems ok for now and I wish I could help replacng the macros but ah, yes, thats a little above my paygrade, though if I knew what I was doing I would do it a little at a time in more manageable blocks than one PR to rule them all sort of thing.

**Comment by wsnipex** [comment]
it really should only be the files listed above. Lots of hits in your search are patches or some readme.

jenkins build this please

**Comment by atupone** [comment]
What this failure means ? Has something to do with this patch ?

**Comment by Memphiz** [comment]
jenkins error is unrelated

**Comment by atupone** [comment]
As the other request (removing deprecated macro) what is minimal automake/autoconf version acceptable ?

**Comment by Memphiz** [comment]
unified depends uses autoconf 2.68

**Comment by uNiversaI** [comment]
@atupone I think it wasn't removing deprecated macro but replacing deprecated by new ones, right?

**Comment by wsnipex** [comment]
save yourself the hassle and don't go trying to upgrade the macros. By the time this would be really needed, we hopefully have migrated to cmake :)

**Comment by atupone** [comment]
Please don't do it :( It's a mess mantaining ebuild (gentoo) with cmake

**Comment by wsnipex** [comment]
good to go for me
@Memphiz?

**Comment by Memphiz** [comment]
fine - thx @atupone

**Comment by uNiversaI** [comment]
> Please don't do it :( It's a mess mantaining ebuild (gentoo) with cmake
@atupone 
You best start looking for a solution for that, sharpish, cmake is going to take over on here, you cant stop it and its already started happening with binary addons and there is already a fork running Linux only cmake build system where I presume a great deal will be ported from when time comes.

See https://github.com/notspiff/kodi-cmake

**Pull request merged**
