### PR TITLE
[swig] Use std::type_index instead of a homegrown implementation.

### PR DESCRIPTION
**Pull request by ace20022**

### CODE REVIEW

**Comment by ace20022** [comment]
jenkins build this please

**Comment by Montellese** [comment]
Makes sense.

**Comment by Montellese** [comment]
We could also try to use the `std::tuple` implementation of C++11 as a replacement for our own version.

**Comment by ace20022** [comment]
I'll try (https://github.com/ace20022/xbmc/tree/std_tuple)

**Comment by ace20022** [comment]
good?

@Montellese the std::tuple thing is harder than initially thought because of the swig type mapping. I guess we need an expert for that.

**Comment by Montellese** [comment]
Sure.

**Pull request merged**
