### PR TITLE
VideoPlayer: fix wmapro, some codecs do not consume entire packet

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by fritsch** [comment]
@da-anda please test - this was your file :-)

Thanks much @FernetMenta

**Comment by FernetMenta** [comment]
only the usual suspects failed to build

**Comment by fritsch** [comment]
To add: Verified and works for me. I see it as generic enhancement for similar files.

**Comment by MartijnKaijser** [comment]
something for a point release or leave it like it is?

**Comment by FernetMenta** [comment]
I don't think v16 is broken in regard to this.

**Comment by da-anda** [comment]
tested and works fine now, thanks. Also tested on Jarvis B3 and everything is fine there as well, so no need to backport.

**Comment by MrMC** [comment]
Try again :)

Works for some, does not work for others, in fact most of my test cases for wmapro are still broke and they all worked without issue under Jarvis.

**Comment by MrMC** [comment]
https://www.dropbox.com/s/bj4vgxgcluk648y/Sample%20%28WMAPro%20Audio%29.wmv?dl=0

**Comment by FernetMenta** [comment]
thanks, I see the issue and will think about a proper solution.
(audio for this sample starts after a couple of secs)

**Comment by MrMC** [comment]
also check seeks, some are fine, some result in same behavior as start.

**Pull request merged**
