### PR TITLE
[addons] remove pvr from addoncache and improve addon manager addon check

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description

On first commit is a change to addon manager added.
Before was by `HasAddons(...)` (the enabled ones) and `HasInstalledAddon(...)` the whole addon class of all asked types created and then on end checked that his list is empty or not.
Since cpluff is removed is it more easy as a list is stored in manager.
This checks now this list and on first found addon it returns (instead of loop for all).

The second commit use then this changed functions on PVR to ask about available.
There was before the only place where the Binary addon cache was used about PVR and now removed as it is no more needed.

Have them taken from https://github.com/xbmc/xbmc/pull/18057 to have there smaller.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by ksooo — COMMENTED** [review]
Havn't I seen this commit in your other PR?

**Comment by AlwinEsch** [comment]
The last two on https://github.com/xbmc/xbmc/pull/18057

**Comment by ksooo** [comment]
Confused, why are there two PRs with the same commits? In which one of two shall I do a review and comment? On both? Nope.

**Comment by AlwinEsch** [comment]
They are kicked out from other after them here is in.

**Pull request merged**
