### PR TITLE
[webOS] Appstore submission media fixes

### PR DESCRIPTION
**Pull request by sundermann**
## Description

The webOS app store requires the splash screen to be a PNG file. Even though a jpg splashscreen seems to work fine, it is out of the official specification: [appinfo.json metadata](https://webostv.developer.lge.com/develop/references/appinfo-json)

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by sundermann** [comment]
Seems Android isn't too happy with a jpg and png splashscreen file

**Comment by garbear** [comment]
Is the png file minimized? This can be done with `pngcrush -brute -ow <png>`.

**Comment by sundermann** [comment]
@garbear it wasn't, applied `pngcrush` and it saved some bytes 👍

**Comment by sundermann** [comment]
The first submission was rejected because the used logo had a gradient as a background. I have added new converted 80x80 and 130x130 logos that do not have a gradient background. The smaller icon was changed because it was the black background version. Both files have been size optimized using `pngcrush`

**Review by garbear — APPROVED** [review]
It looks like the specification requiring a png is satisfied. And the gradient is removed from the two icons, which should fix the submission rejection.

I also think with this change, all webOS-specific pngs are now minimized, which is good.

While we're at it, are there any other pngs used by webOS that the mighty pngcrusher can attack? I don't see any used by the manifest or packaging script but it can't hurt to ask.

**Comment by sundermann** [comment]
For webOS specifically, we only need those 3 image files so those should be alright now 👍

**Pull request merged**
