### PR TITLE
[cmake] FindNFS module to build internal

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Build nfs during cmake project
update NFS on windows platforms

## Motivation and context
More depends

## How has this been tested?
Runtime win64, macos x86_64

## What is the effect on users?
N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by thexai** [comment]
Tested Windows x64 and found a strange behavior: 

First time (when no previous `nfs.lib` exist) build fine, although cmake message suggest that `nfs.lib` already exists. This seems only cosmetic issue:

`-- Found NFS: T:/KODI/kodi/project/BuildDependencies/x64/lib/nfs.lib (found version "5.0.1")`

`-- NFS enabled: Yes`

But all subsequent builds fails (kodi build without NFS support):

`-- Could NOT find NFS (missing: NFS_LIBRARY NFS_INCLUDE_DIR)`

`-- NFS enabled: No`

At that moment, `nfs.lib` does exist in the mentioned location as is installed in the "first" build:

```
  Performing install step for 'libnfs'
  Microsoft (R) Build Engine versión 17.2.1+52cd2da31 para .NET Framework
  Copyright (C) Microsoft Corporation. Todos los derechos reservados.

    nfs_mount.vcxproj -> T:\KODI\kodi\kodi-build.x64\build\libnfs\src\libnfs-build\mount\nfs_mount.dir\Release\nfs_mount.lib
    nfs_nfs.vcxproj -> T:\KODI\kodi\kodi-build.x64\build\libnfs\src\libnfs-build\nfs\nfs_nfs.dir\Release\nfs_nfs.lib
    nfs_nfs4.vcxproj -> T:\KODI\kodi\kodi-build.x64\build\libnfs\src\libnfs-build\nfs4\nfs_nfs4.dir\Release\nfs_nfs4.lib
    nfs_nlm.vcxproj -> T:\KODI\kodi\kodi-build.x64\build\libnfs\src\libnfs-build\nlm\nfs_nlm.dir\Release\nfs_nlm.lib
    nfs_nsm.vcxproj -> T:\KODI\kodi\kodi-build.x64\build\libnfs\src\libnfs-build\nsm\nfs_nsm.dir\Release\nfs_nsm.lib
    nfs_portmap.vcxproj -> T:\KODI\kodi\kodi-build.x64\build\libnfs\src\libnfs-build\portmap\nfs_portmap.dir\Release\nfs_portmap.lib
    nfs_rquota.vcxproj -> T:\KODI\kodi\kodi-build.x64\build\libnfs\src\libnfs-build\rquota\nfs_rquota.dir\Release\nfs_rquota.lib
    nfs_win32.vcxproj -> T:\KODI\kodi\kodi-build.x64\build\libnfs\src\libnfs-build\win32\nfs_win32.dir\Release\nfs_win32.lib
    nfs.vcxproj -> T:\KODI\kodi\kodi-build.x64\build\libnfs\src\libnfs-build\lib\Release\nfs.lib
    -- Install configuration: "Release"
    -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/lib/cmake/libnfs/libnfs-config.cmake
    -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/lib/cmake/libnfs/libnfs-config-release.cmake
    -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/lib/cmake/libnfs/FindNFS.cmake
    -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/lib/cmake/libnfs/libnfs-config-version.cmake
    -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/lib/pkgconfig/libnfs.pc
    -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/nfsc
    -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/nfsc/libnfs-raw.h
    -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/nfsc/libnfs-zdr.h
    -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/nfsc/libnfs.h
    -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/nfsc/libnfs-raw-mount.h
    -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/nfsc/libnfs-raw-nfs.h
    -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/nfsc/libnfs-raw-nfs4.h
    -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/nfsc/libnfs-raw-nlm.h
    -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/nfsc/libnfs-raw-nsm.h
    -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/nfsc/libnfs-raw-portmap.h
    -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/nfsc/libnfs-raw-rquota.h
    -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/lib/nfs.lib
  Completed 'libnfs'
```

I guess the desired behavior is to only build `nfs.lib` the first time when it doesn't exist and on subsequent builds use what's in `.../project/BuildDependencies/x64/lib` and `.../project/BuildDependencies/x64/include` since it is preserved between builds.

Other than issues mentioned, I runtime tested a build made with NFS 5.0.1 support and all worked fine using NFS video sources on Windows x64 (videos shared from Synology NAS).

**Comment by fuzzard** [comment]
Thanks for testing @thexai I'll look into why the subsequent builds aren't working

**Comment by fuzzard** [comment]
@thexai should be good to go now. If youd like to test to confirm, thatd be great

**Review by thexai — APPROVED** [review]
Tested on Intel NUC (Windows x64) where I habitually already use sources with NFS.

Also confirmed that the build issues are already resolved.

**Comment by thexai** [comment]
@fuzzard, I congratulate you for the good work done. I think this is a good example to follow of how dependencies should be managed in Windows. 

For me it is the best of both worlds: it compiles directly from source in a transparent way and at the same time it saves compilation time when the dependency already exists (just like with precompiled dependencies).

Maybe future dependency updates should be like this or even modify the recently updated ones (`taglib`, `rapidjson`, `crossguid`, ...) to have this behavior as well.

Note that in Jenkins they will continue to compile every time because previous compilations are expressly removed each time (entire `.../project/BuildDependencies/x64` folder deleted), although this could easily be changed later if it seems interesting and safe.

**Comment by fuzzard** [comment]
Yeah, thats the eventual goal. baby steps ;)

**Pull request merged**
