### PR TITLE
[addons] Remove unneeded includes from 'addons' header files …

### PR DESCRIPTION
**Pull request by ksooo**
…(forward-declare as much as possible, include headers actually needed for used types instead of something 'global', outline code, ...), add missing standard includes.

Should (significantly) reduce compile times.

@notspiff @AlwinEsch good to go in?

### CODE REVIEW

**Comment by ksooo** [comment]
jenkins build this please

**Review by garbear — APPROVED** [review]
Games and peripherals changes look good

**Comment by ksooo** [comment]
FreeBSD Jenkins error is definitely unrelated.

**Comment by ksooo** [comment]
jenkins build this please

**Review by AlwinEsch — APPROVED** [review]
Looks good to me and can in. Thanks a lot!

**Pull request merged**
