### PR TITLE
Add option to call TMDB scraper from an addon

### PR DESCRIPTION
**Pull request by robwebset**
There is occasionally a need for addons to find out things like the ID of a movie on a particular site, the addon can't just read the ID used within Kodi as it will not know which scraper was used to create that Id. So I thought, could a module be added to existing scrapers that did a simple select when given the "name" and "year" of a movie.

So to call it you would just put the dependency in your addon.xml as usual, then do something like:
Code:

```
from tmdb import TMDB
tmdb = TMDB()
details = tmdb.get_by_name(title, year)
```

This actually returns a json response for you to do whatever you like with. (So if there is more information in the response than normally scraped, the addon can make use of it)

If people think this is OK, I can add something similar for the other scrapers.

### CODE REVIEW

**Comment by Razzeee** [comment]
I think you would need to push it against https://github.com/xbmc/repo-scrapers as this are only the scrapers that get pushed on release. And usually Martijn pulls them from the repo into here before we release.

That being said, I'm not sure about this as it might cause a lot of calls and adds python to the scraper itself. I would prefere to store multiple ids in the database, in a similar fashion, how it's handled for ratings or artwork.

**Comment by tamland** [comment]
Not happening. We wont maintain any python modules in core. There is plenty of tmdb modules available. Use one of those instead of reinventing the wheel.

**Comment by robwebset** [comment]
Hi @tamland 

I was hoping to use one that was already done, but the one that did things like this was script.module.metahandler but that is no longer available.

http://forum.kodi.tv/showthread.php?tid=263372

I'm not aware of "plenty" available in the official repository, please can you let me know which you refer to? Then I'd gladly use them

Thanks

Rob

**Comment by tamland** [comment]
http://pypi.python.org If there's none available in the addon repo feel free to create an addon package for one and submit our addon repo. The part that's no-go here is including anything like that in the scraper library or as part of core.

**Comment by robwebset** [comment]
So not in the addon repo (So no use to existing addons) - based on previous discussions here:

http://forum.kodi.tv/showthread.php?tid=181896

Creating a module to do this is a pointless exercise at we already had one - and it was told that it was being removed!

**Comment by MartijnKaijser** [comment]
@robwebset the reason for the removal was that there wasn't as single addon in our repo actually using that module at that time. I left it in all that time because all the complaining and the "promise"  it would be used by plugins in repo as well. That the module now has died for whatever reason (i can certainly think of one) i separate from that. Make a module that needs the plugins/script to pass along it's own API key, add it to repo and start using it.

**Pull request closed without merging**
