### PR TITLE
[pvr] - fix epg search

### PR DESCRIPTION
**Pull request by FernetMenta**
fixes http://forum.kodi.tv/showthread.php?tid=268449

### CODE REVIEW

**Comment by FernetMenta** [comment]
@opdenkamp is this correct?

**Comment by opdenkamp** [comment]
+1

**Comment by nkvoronov** [comment]
16.1 - fix epg search NOT WORK (Ubuntu)

**Comment by fritsch** [comment]
@nkvoronov the fix was for krypton - 16.1 is not maintained anymore and won't receive further patches.

**Pull request merged**
