### PR TITLE
webserver: add support for JSONP for JSON-RPC requests

### PR DESCRIPTION
**Pull request by Montellese**
This adds JSONP (JSON with Padding, see http://en.wikipedia.org/wiki/JSONP) support to our JSON-RPC API. Only HTTP GET is supported and the request path must be `/jsonrpc-p`. It is possible to either use `callback` or `jsonp` as a GET argument to specify the name of the callback function used in the response and the default value is `parseResponse`.
All this does is change the JSON-RPC API response from

```
{ "jsonrpc": "2.0", ... }
```

to

```
<callback>({ "jsonrpc": "2.0", ... });
```

Since JSONP can be a security risk (same as our current JSON-RPC implementation) I've added a setting (advanced level) to be able to turn it off.

### CODE REVIEW

**Comment by kib** [comment]
I am just being the devil's advocate, but if this can be a security risk, why is it a feature to add it ?
It feels to me like adding DDLv3 to an existing TLS 1.0 setup.

**Comment by topfs2** [comment]
Well honestly I don't see the security risk. Its a very common feature our
on the big servers. Almost all rest APIs I've dealt with support it.

Besides kodi should be used behind a firewall, safe from most attackers.

And this adds tremendous value for web apps
Den 6 feb 2015 00:36 skrev "Kib" <notifications@github.com>:

**Comment by topfs2** [comment]
Another option is to have this under the same jsonrpc/ path but if callback
param is added we padd.
Den 6 feb 2015 07:06 skrev "Tobias Arrskog" <topfs2@kodi.tv>:

**Comment by Montellese** [comment]
Well obviously it's subject to CSRF attacks but that's also the case for our normal JSON-RPC API,

**Comment by Montellese** [comment]
@topfs2: We could do that as well BUT from what I understood JSONP only supports HTTP GET and for JSON-RPC we currently support GET and POST.

**Comment by topfs2** [comment]
Really unsure of the GET/POST thing but usually in web frameworks you have just jsonp, so I guess GET is the only one which is valid.

http://api.jquery.com/jquery.getjson/
https://docs.angularjs.org/api/ng/service/$http (via $http.jsonp)

Ah the CSRF I didn't think of, but yeah as you said jsonp isn't more vulnerable against that our regular json.

**Comment by Montellese** [comment]
I probably should add that I have not tested this with any existing framework since I don't really know them so would be nice if someone who is familiar with a framework that uses JSONP to test this. Let me know if you need a test build (and for which platform).

**Comment by Tolriq** [comment]
Jsonp only support get in most implementation but it's only a limitation on the client side on how to make the query.
The fact that the end point also support post is not blocking at all.

I'd say like topfs2 use the same endpoint and api and add a callback parameter for this as it's more logical and in the end will reduce support on your side :)

For security, there's no difference between current implementation and jsonp as the checks are only client side so not really secure by itself.
For CSRF it would only be true if the API would support auth token or anything, since right now TCP is unprotected and and http only via basic auth needed in all queries this does not change anything.

And since there's no header added in this patch for cors or anything there's no security change either.

So in the end the settings is useless, it would only make sense if you add cors support and the settings should only cover the cors header since it's the only thing that modify security.
JSONP is not security related by itself.

**Comment by topfs2** [comment]
I tried it very quickly but got this
```
webserver: request received for /jsonrpc-p/?callback=jQuery110204923517405986786_1423236927560&request=%7B%22jsonrpc%22%3A%222.0%22%2C%22method%22%3A%22JSONRPC.Introspect%22%2C%22id%22%3A0%7D&_=1423236927561
```
and nothing else.

I might have done the request wrong though :)
```
  var kodiAPI = "http://localhost:8080/jsonrpc-p/?callback=?";
  $.getJSON( kodiAPI, {
    request: JSON.stringify({
        "jsonrpc": "2.0",
        "method": "JSONRPC.Introspect",
        "id": 0
      })
    })
    .done(function( data ) {
        console.log(data);
    });
```

**Comment by topfs2** [comment]
Nvm, I was stupid.

```
  var kodiAPI = "http://localhost:8080/jsonrpc-p?callback=?";
  $.getJSON( kodiAPI, {
    request: JSON.stringify({
        "jsonrpc": "2.0",
        "method": "JSONRPC.Introspect",
        "id": 0
      })
    })
    .done(function( data ) {
        console.log(data);
    });
```

Worked fine (did the request to jsonrpc-p/ instead of jsonrpc-p :) )

**Comment by Montellese** [comment]
I have removed the setting and the URL is now `/jsonrpc` as well and JSONP is activated by either providing the `callback` or `jsonp` GET argument.

**Comment by Montellese** [comment]
jenkins build this please

**Comment by Montellese** [comment]
@topfs2: Care to try again with your test script?

**Comment by Montellese** [comment]
Ok tested it myself and it is still working. Will merge in the next merge window.

**Pull request merged**
