### PR TITLE
[fix] Nuke 'libpng warning: iCCP: known incorrect sRGB profile' warnings

### PR DESCRIPTION
**Pull request by hudokkow**
## Description
Get rid of (very) annoying 200+ 'libpng warning: iCCP: known incorrect sRGB profile' warnings.

## Motivation and Context
Nuke build log pollution. 

## How Has This Been Tested?
No more pollution during build.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Something else

**WARNING:** Do **NOT** open the file diff unless your machine has the stamina to deal with it.

I took the hammer approach. Many images didn't needed the treatment but they got it anyway.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@phil65 @ronie ping

**Comment by ronie** [comment]
sure, go ahead

**Comment by ksooo** [comment]
@hudokkow on my end (macOS Sierra), this change leads to a funny effect: png that should be red are now blue. If I revert this commit, everything goes back to normal. Don't know whether this is platform specific.

Examples:
screenshot002
screenshot003
screenshot001
screenshot000

**Comment by Montellese** [comment]
Same on windows but I thought it was on purpose but I was wondering why the error icon was blue instead of red.

**Comment by ksooo** [comment]
@Memphiz by any chance, is this a platform specific bug?

**Comment by ksooo** [comment]
hehe (and I thought it was platform specific).

**Comment by Memphiz** [comment]
RGB vs BGR then somewhere ...

**Comment by MilhouseVH** [comment]
Yes, same blue-instead-of-red icon when building LibreELEC with latest Kodi master on Ubuntu 16.04 for RPi2 and x86_64.

s1

**Comment by ksooo** [comment]
> RGB vs BGR then somewhere ...

 Sounds like you could have a clue where to start looking for the bug in kodi code? Or did something went wrong with @hudokkow's png voodoo?

**Comment by Memphiz** [comment]
Not really but thats a common problem - if blue and red is mixed the color order is either wrong in png metadata or wrong during rendering (i doubt the latter) - @hudokkow what exactly did you do to fix the error in those pngs?

**Comment by phil65** [comment]
fyi estuary files were already fixed some time ago, see https://github.com/phil65/skin.estuary/commit/df47e07361292176c58ae7af4e798f69987ad135
I used `find . -type f -iname '*.png' -exec pngcrush -ow -rem allb -reduce {} \;`

**Comment by hudokkow** [comment]
I used mogrify. Can't remember the exact options passed/used. Maybe revert and go with @phil65's approach and see if warnings go away?
I'll have a look later today.

**Comment by Memphiz** [comment]
Maybe try it out with that Icon from ksoo's example to begin with.

**Pull request merged**
