### PR TITLE
[tools/depends/target][python3] enable _multiprocessing module

### LINKED ISSUE #19458: Android 7 : ModuleNotFoundError: No module named '_multiprocessing'
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi running on Amazon AFTMM with Android 7.1.2 API level 25, kernel: Linux ARM 32-bit version 4.4.120+ fails to load the required module for python3.8 multiprocessing with: "ModuleNotFoundError: No module named '_multiprocessing'"

Relevant log snippet:
2021-03-21 23:11:55.831 T:17693   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'ModuleNotFoundError'>
Error Contents: No module named '_multiprocessing'
Traceback (most recent call last):
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.liveleak/default.py", line 490, in <module>
    if url: index(url)
    File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.liveleak/default.py", line 380, in index
    pool = Pool(os.cpu_count() * 2)
    File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/dummy/__init__.py", line 123, in Pool
    from ..pool import ThreadPool
    File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/pool.py", line 30, in <module>
    from .connection import wait
    File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/multiprocessing/connection.py", line 21, in <module>
    import _multiprocessing
ModuleNotFoundError: No module named '_multiprocessing'
-->End of Python script error report<--
                                                   
2021-03-21 23:11:55.831 T:17693   DEBUG <general>: onExecutionDone(2, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.liveleak/default.py)

Full debug log link provided below.

Note: This info is from a user of the plugin.video.liveleak (v2.0.0) for Kodi 19 as reported here:
https://github.com/Botster/plugin.video.liveleak/issues/6#issuecomment-803678896

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It is expected that the Python 3 built-in module should be able to load all of its dependencies.

## Actual Behavior

The required module is not found.

## Possible Fix

A possible fix depends upon whether this is an Android-specific Kodi compile issue, or an upstream issue with Android 7 itself.

### To Reproduce

1. Launch Kodi 19 on Android 7.1.2
2. Launch the LIveleak plugin v2.0.0 (plugin.video.liveleak)
3. Select a category to fetch any relevant videos from the target site

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/unozanidud.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #20031: concurrent.futures import error
### Describe the bug
Here is a clear and concise description of what the problem is:

I'm attempting to use the standard python library [concurrent.futures](https://docs.python.org/3/library/concurrent.futures.html) (standard since py 3.2)

In my addon, I include the standard import call:
```
from concurrent.futures import ThreadPoolExecutor
```
which works as expected.  When I include the import call:
```
from concurrent.futures import ProcessPoolExecutor
```

The addon errors out and the debug log shows:
```
Error Type: <class 'ModuleNotFoundError'>
Error Contents: No module named '_multiprocessing'
...
File "/Applications/Kodi.app/Contents/Libraries/lib/python3.8/multiprocessing/connection.py", line 21, in <module>
import _multiprocessing
ModuleNotFoundError: No module named '_multiprocessing'
->End of Python script error report<--
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

```from concurrent.futures import ProcessPoolExecutor``` does not fail

## Actual Behavior

```from concurrent.futures import ProcessPoolExecutor``` fails

## Possible Fix

According to Fuzzard, likely a build issue.

Edit:  After some additional testing, I also tried the following import:
```
from multiprocessing import Pool
```
and get the following error:
```
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770
```

Which points to [this issue](https://bugs.python.org/issue3770).  So possibly there's an issue with HAVE_SEM_OPEN

### To Reproduce

1.  Include the line  ```from concurrent.futures import ProcessPoolExecutor```  in a test addon.py file

Edit:
Here's a test addon to reproduce:
[plugin.program.concurrent_futures.zip](https://github.com/xbmc/xbmc/files/6977877/plugin.program.concurrent_futures.zip)

### Debuglog

The debuglog can be found here:
```
INFO <general>: Starting Kodi (19.0 (19.0.0) Git:20210218-f44fdfbf67). Platform: OS X x86 64-bit
INFO <general>: Using Release Kodi x64
INFO <general>: Kodi compiled 2021-02-18 by Clang 10.0.1 (clang-1001.0.46.4) for OS X x86 64-bit version 10.13 (101300)
INFO <general>: Running on Apple Inc. MacBookPro12,1 with OS X 10.14.6, kernel: Darwin x86 64-bit version 18.7.0

...

Error Type: <class 'ModuleNotFoundError'>
Error Contents: No module named '_multiprocessing'
...
File "/Applications/Kodi.app/Contents/Libraries/lib/python3.8/multiprocessing/connection.py", line 21, in <module>
import _multiprocessing
ModuleNotFoundError: No module named '_multiprocessing'
->End of Python script error report<--
```

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

[Forum post](https://forum.kodi.tv/showthread.php?tid=363941&pid=3053991#pid3053991)
I'll note that I only tested this on OSX, not other Operating Systems, so I'm unsure if this failure is specific to OSX, or if the error occurs in other OS's

I'll also note that both of these import calls just in the python 3 installation on my computer (outside of Kodi) does not result in the errors and the import works, so I doubt it's an issue with the OS type.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [X] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:  OS X x86 64-bit version 10.13 
 - Kodi version: 19.0.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Builds _multiprocessing and _posixshmem modules for tools/depends platforms.
Have flagged as a bugfix due to it being considered a "standard library" for python. Therefore ive flagged as backport needed. I'll raise that PR, and the powers that be can decide if they want to accept it as a backport.

https://github.com/xbmc/xbmc/pull/20034/commits/7b2d6fa8075f40432d69bf8e31add326492737b1 fixes a race condition for depends builds where xz may be built before gettext, although gettext is a dependecy of xz. Was brought to light in this PR by the 2 linux x86_64 jenkins builds repeatedly failing to link xz to libintl_gettext

## Motivation and context
fixes #20031
fixes #19458 

## How has this been tested?
OSX using test plugin provided by @zach-morris
Android aarch64 same test plugin

## What is the effect on users?
allows use of _multiprocessing module backed python modules (eg. concurrent.futures)

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
@wsnipex need a review from you regarding the -lrt DEPLIBS change. wasnt sure how/where to put this.

Its only relevant to a KODI_DEPENDSBUILD build of kodi on linux, as librt becomes a link requirement for the libpython3.8.a archive due to the _posixshmem module that is now in the static build.

kodi.bin requires the -lrt flag. wasnt sure if there was a more nuanced way so it doesnt get tacked onto all usage of DEPLIBS

My other thought was just to not build the _multiprocessing/_posixshmem modules for linux depends builds, as my understanding is its not really a build type anyone actually uses on linux.

thoughts?

**Comment by wsnipex** [comment]
librt should probably be added here: https://github.com/xbmc/xbmc/blob/master/cmake/modules/FindPython.cmake#L23

**Comment by fuzzard** [comment]
Cheers, i'll give that a try

**Review by wsnipex — APPROVED** [review]

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by quietvoid** [comment]
This seems to bring issues with Android not supporting `sem_open`.
For example, PlexKodiConnect uses `multiprocessing` and this commit makes the multiprocessig module import work, but not the actual `ThreadPool`.

See here: https://github.com/croneter/PlexKodiConnect/issues/1641

**Pull request merged**
