### PR TITLE
[guilib][GUIFadeLabelControl] Fix text right alignment

### LINKED ISSUE #24246: Label alignment: right align doesn't work as expected
### Describe the bug
Here is a clear and concise description of what the problem is:

The x axis label alignment tag is not interpreted as expected anymore - this used to work just fine with Nexus v20.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

- when adding e.g. an `<align>right</align>` tag to any label control, it's expected to then render the label text according to this tag (as it worked up until Nexus v20)

## Actual Behavior

- the align tag is not ignored, but interpreted in a weird way: with an `<align>right</align>` tag in a fade label control the text is rendered close to the right edge of the control expanding to the right, not aligned to the right expanding to the left - see screenshots

### To Reproduce

1. Create a fade label control (label controls supposedly show the same issue as per @manfeed)
2. Add a `<align>right</align>` tag to the control, something like this (used for the top text in the video info dialog list in the attached screenshots):

```xml
<control type="fadelabel">
   <width>200</width>
   <height>36</height>
   <align>right</align>
   <font>Font36</font>
   <label>557</label>
   <textcolor>$VAR[TextColorNF]</textcolor>
</control>
```

3. Look at the result

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/azizunagaf.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

Expected behaviour (Nexus v20):
Jpyia5Y

Actual behaviour (Omega v21 Beta 2):
XyIRlUc

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 22H2
 - Kodi version: Omega v21, Beta 2

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

Fix the text right alignment, changes are similar as done in GUITextBox.cpp by PR #22691

## Motivation and context

fix #24246
## How has this been tested?

something similar to following in a custom xml window
```
<control type="fadelabel">
   <posy>110</posy>
   <posx>65</posx>
   <top>110</top>
   <left>65</left>
   <width>500</width>
   <align>right</align>
   <font>font12</font>
   <label>This is a test</label>
</control>
```

## What is the effect on users?

see text on the right position

## Screenshots (if appropriate):
before:
immagine

now:
immagine

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by sarbes — APPROVED** [review]
LGTM.

**Comment by enen92** [comment]
jenkins build this please

**Comment by psp2111-ADSLGATE** [comment]
Thank you so much @CastagnaIT 

Do you think this merge will fix this bug? 
https://github.com/xbmc/xbmc/issues/22547#issuecomment-1399471161

**Comment by CastagnaIT** [comment]
no, this PR is specific for fadelabel control, mentioned Issue talk about textbox control
but that problem may exists on all controls with text, its a different type of bug

**Pull request merged**
