### PR TITLE
[Confluence] cleanup

### PR DESCRIPTION
**Pull request by ronie**
these tags are now obsolete as we've removed the music and video overlays.

@phil65 @BigNoid @HitcherUK

### CODE REVIEW

**Comment by phil65** [comment]
@xhaggi: Could we remove that "allowoverlay" tag from core, too? Wiki says it only applies for video and music overlay. Or does it apply for all modeless dialogs?

**Comment by xhaggi** [comment]
i need to take a look at our core if it's used somewhere else, never touched that before.

**Comment by phil65** [comment]
Cool, take your time. Thx for lookin into it.

**Comment by xhaggi** [comment]
@ronie as we dropped it from the core you can shove this in now ;)

**Comment by ronie** [comment]
k, there she goes...

**Pull request merged**
