### PR TITLE
[webOS] Set required memory

### PR DESCRIPTION
**Pull request by sundermann**
## Description

Add the required memory attribute.

## Motivation and context

Try to fix and understand why kodi is being restarted as reported by some users in the forum. Maybe the absence of the required memory attribute causes memchute (the memory manager daemon, that kills and restarts processes) to think that by restarting kodi a lot of memory can be freed.

## How has this been tested?

OLED77C28LB / webOS7/22

Testing very much appreciated by the affected users on the forum

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by sundermann** [comment]
The value of 150mb is certainly very high but I want to hear feedback first from the affected users on the forums if it fixes the seen issue

**Comment by quietvoid** [comment]
FWIW I ran into this when doing the initial setup of the Jellyfin for Kodi addon, and it happened when first loading the libraries where there are many items.

**Comment by wsnipex** [comment]
150MB Ram definitely is not enough to run Kodi. Some years back we struggled to make it work on the 512MB raspberry pi, with nothing else running on it.

**Comment by sundermann** [comment]
Alright, let's try with a higher value to see if it changes anything. Citing from the webOS docs, this is the minimum required memory though: ```This property is optional and the Number type. Set the minimum amount of memory in megabytes required to run your app. This value does not need to be the same as the maximum memory usage consumed by your app.```

Additionally reverting #23558 for testing because it seems that we are seeing memory exhaustion especially with python addons and there is a reported leak in #23786 which suggests that it was introduced with this change.

**Review by wsnipex — APPROVED** [review]

**Comment by sundermann** [comment]
Been running this the last couple of weeks without problems and it does indeed free up more memory on startup.

**Pull request merged**
