### PR TITLE
[addons] fix: always set a repos origin to itself

### PR DESCRIPTION
**Pull request by matthuisman**
## Description
@howie-f 
This just flips the origin logic so the check for repo is first.
Therefore, a repo add-on's origin is always set to itself.

## Motivation and Context
Currently installing a repo from another repo - the 2nd repos origin is set to the 1st repo.
This means it can't update itself without a "change of origin" warning.

It also means that 1st repo could "turn bad" and update the 2nd repo to point elsewhere.
That would then make all the add-ons installed from 2nd repo also able to be hijacked.

A repo just always be responsible for updating itself.

## How Has This Been Tested?
Confirmed by installing a repo from a repo.
Noted the 2nd repos origin is set to the 1st repo in addons.db
Also noted it can't update itself.

After this PR, its origin is correctly set to itself.
And it can then update itself freely.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by matthuisman** [comment]
I notice with this PR, that now trying to install the repo from the 1st repo, it will give the origin warning.

We can actually remove that warning when installing any repos as we know that repo will have it's origin set to itself.
Also, it doesn't show as installed when browsing the 1st repo.
I'll see if I can fix these two things

**Comment by phunkyfish** [comment]
Should you be able to install a repo from a repo?

**Comment by matthuisman** [comment]
yeh, it's quite valid.

I use it to allow Slyguy repo users to install Inputstream Adaptive Testing repo.
Basically just a "shortcut". Stops them needing to download a zip, transfer to android, then install etc.
Or from typing in other urls etc.

But at moment, when doing this, that repos origin gets set to slyguy id.
so slyguy repo becomes responsible for updating it.

**Comment by phunkyfish** [comment]
Cool. Makes sense.

**Review by howie-f — APPROVED** [review]
no objections

**Review by phunkyfish — APPROVED** [review]
Cool

**Pull request merged**
