### PR TITLE
New clothes for Kodi

### PR DESCRIPTION
**Pull request by phil65**
So here it is.....Estuary.

Estuary

Not sure if some of the build files need further changes to support multiple themes ?
Also, the language file could need some cleanup, but that could be done afterwards I guess.

Thanks to all involved! :)

### CODE REVIEW

**Comment by FernetMenta** [comment]
Congratulations to all involved making this happen. Great job! This is one of the most important milestones for Kodi for a long time.

**Comment by ronie** [comment]
thanx a billion @phil65 (and everyone else involved) for your dedication on this project!

**Comment by afedchin** [comment]
can we keep Confluence in repo?

**Comment by phil65** [comment]
yup, @HitcherUK 	will take care of it.

**Comment by BigNoid** [comment]
Thx @phil65 for the many hours spent creating this skin.

**Comment by SLiX69** [comment]
Thanks to all involved, looks awesome!

**Comment by koying** [comment]
Congrats to all involved in this huge endeavor :)

**Comment by pietheinstrengholt** [comment]
Worth a post on the frontpage! Congrats!!

**Comment by Razzeee** [comment]
+1 
Finally, let's merge this!
Thanks, @phil65, @vonH and everybody involved.

**Comment by vonH** [comment]
Nice to see this ready.

**Comment by ronie** [comment]
> Also, the language file could need some cleanup, but that could be done afterwards I guess.

you can cherry-pick https://github.com/ronie/xbmc/commit/38c0cd70f78bf7f9ddd7788589a5beb4a7b51907

or just pull the full file https://github.com/ronie/xbmc/blob/estuary-lang/addons/resource.language.en_gb/resources/strings.po

**Comment by phil65** [comment]
Done.

**Comment by MilhouseVH** [comment]
How difficult would it be to move the "[Confluence] - bye bye Confluence." commit to a separate PR which could be merged a week or two after this is merged? I might even be able to include this PR in test builds where it not dropping Confluence. I just think this approach might give bleeding edge testers the opportunity to dip their toe into Estuary waters before the hammer comes down...

**Comment by phil65** [comment]
The idea is to move Confluence to the skin repository and bump its version number. That way all people get that update and have a copy of confluence in userdata_folder so they wont experience the hammer you mentioned.

**Comment by MilhouseVH** [comment]
Of course - thanks.

**Comment by mazeyx** [comment]
im guessing we wont be able to try this out on jarvis?

**Comment by phil65** [comment]
Nope. :)

**Comment by mazeyx** [comment]
ok thx anyway im waiting till feature freeze to go to v17

**Comment by vonH** [comment]
It does work on Jarvis, mostly.

**Comment by Razzeee** [comment]
But the home screen is basically unusable in Jarvis as we changed a bunch of stuff.

**Comment by fritsch** [comment]
Hurray, really. Looking forward to a fantastic v17. Already rebased my stuff on your branch and it's primetime in my living room. Quite funny, if you were used to "navigate endless times" and now stuff is just there where one expects it.

Thanks to all involved.

**Comment by zag2me** [comment]
Stuff like this makes me proud to be part of this awesome team.
Obvious +1 on the inclusion!

**Comment by ronie** [comment]
confluence is now available in the addon repo for krypton.
https://github.com/xbmc/repo-skins/pull/2

**Comment by stefansaraev** [comment]
https://github.com/phil65/xbmc/blob/65307696051e372335ac3f7f371154c98f09038b/addons/skin.estuary/media/Makefile.in#L11 is nope. you meant ifeq (@ARCH@,arm) ?

also, -use_none has changed to "-disable_dxt -disable_lzo" in Krypton, but there is not much difference in speed / compression ratio with dxt disabled, you should obviously not diasble lzo. so you may remove this arm check.

**Comment by phil65** [comment]
>It does work on Jarvis, mostly

Nope,  it doesn't work properly at all on Jarvis.

**Comment by da-anda** [comment]
I haven't tested the 3D depths since my initial work on that. I'm sure that some stuff that got added later needs some tweaking, but there is plenty of time to fix that part (don't have the time for it atm anyways)

**Comment by phil65** [comment]
@stefansaraev done, thx.

**Comment by a1rwulf** [comment]
Awesome!
Thx guys for your great work, looking forward to v17 as well.

**Comment by phil65** [comment]
Squashed all fixups.

**Comment by wsnipex** [comment]
great stuff :+1:

**Comment by phil65** [comment]
@ronie changed and squashed.
jenkins build this please

**Comment by mazeyx** [comment]
just a suggestion,
when a video has started and you bring up the play/pause/seek bar for the part that shows media info/plot, plot is the default instead of media info maybe have a option to select media info as default instead of plot, or even bring the media info to the seek bar area like with confluence it was nice seeing it. now it requires 3-4 clicks to see it.

also, for some reason i cant select different types of views i do not use library, i just use "Videos" i used to use big list which would hide the thumbnails and plot info. now it says no information available for every file heh. big list would hide that atleast since i dont need it.

**Comment by MartijnKaijser** [comment]
@mazeyx ask on the forum

**Comment by robinrossow** [comment]
♥

**Pull request merged**
