### PR TITLE
[Estuary] Rework PVR seekbar + Fix PVR info dialog.

### PR DESCRIPTION
**Pull request by ksooo**
1. Rework seekbar for Live TV.

* Remove special handling for PVR audio and video stream info. Move it to lower right, where it resides for all (?) other media.
* Rearrange channel number and next event info for more readability.

before:
screenshot001

after:
screenshot000

2. Seekbar for PVR radio now is aligned with PVR Live TV, not 'normal' music anymore.

before:
screenshot001

after:
screenshot000

3. PVR info dialog: Fix sesaon/episode/episodetitle string composition. Fixes https://github.com/phil65/skin.estuary/issues/246

### CODE REVIEW

**Comment by fuzzard** [comment]
just a confirmation Season/ep/eptitle all working properly now. Cheers

**Comment by da-anda** [comment]
from a pure visual standpoint it IMO would look a bit better if the channel number would be next to the channel icon, especially when somebody might not have channel icons. But no hard feelings TBH.

**Comment by ksooo** [comment]
@da-anda 

> if the channel number would be next to the channel icon

 do you have a mockup?

**Comment by ksooo** [comment]
@da-anda something like this?
screenshot000

**Comment by da-anda** [comment]
no, hang on, I'll prepare a mockup

Am 10.12.2017 10:09 nachm. schrieb "Kai Sommerfeld" <
notifications@github.com>:

**Comment by zag2me** [comment]
Something like this maybe for the channel number
infobar

**Comment by ksooo** [comment]
> no, hang on, I'll prepare a mockup

> Something like this maybe for the channel number, and make the OSD thinner

 everything else than "move existing content" from A to B, plus adjusting sizes is far beyond my skinning capabilities

**Comment by ksooo** [comment]
My final offer: ;-)

* channel number is back at its old place
* audio/video flags moved to lower right corner
* 'now' info added

screenshot002

**Comment by da-anda** [comment]
well, the "now: " part is now redundant and the alignment of the icon is off. I'd just drop this info, as it's visible on the very top (which is in line with all other media). Now if this info is well placed up there or not is a different story (I never look there or find the info up there, even though I know it's there). Let me play around with the XML a bit, or if you don't want to wait anymore, drop the "now" part and merge.

**Comment by ksooo** [comment]
Okay, here we go. Almost back to where we originally came from...

* removed 'now' (was not present before this PR)
* channel number is back at its old place (where it was before this PR)
* reduced height of the info area again (now it is like it was before #13155)
* only change that survived: audio/video flags moved to lower right corner, left shift of 'next'

Boy, I guess I will concentrate again more on C++, not GUI. This is really exhausting. ;-)

screenshot000

**Review by ronie — COMMENTED** [review]
xml changes look ok to me.

**Pull request merged**
