### PR TITLE
[windows] proper handling of adapter changing.

### PR DESCRIPTION
**Pull request by afedchin**
proper fix for #13464

### CODE REVIEW

**Comment by afedchin** [comment]
@gelotus please check this

**Comment by afedchin** [comment]
`Android-ARM` failure is not related

**Comment by gelotus** [comment]
HandleDeviceLost()... An afternoon spent to track down the init calls.. That was 3 definitions before.. Well, build and go for testing

**Comment by gelotus** [comment]
I'm sorry but pOutput was nullptr..
[https://s18.postimg.org/hauwjih61/crash.jpg](url)

**Comment by gelotus** [comment]
What do you think if we create an array of all outputs enumerated and if is the case init all and consequently create more than one d3d11device?

**Comment by afedchin** [comment]
@gelotus please try updated version

**Comment by gelotus** [comment]
Compile error for trying to convert IDXGIOutput to IDXGIOutput1, changing declaration to IDXGIOutput and compiles fine. No more crash after switching screen and playback, but the renderer remains the old one, like my patch.

**Comment by afedchin** [comment]
> but the renderer remains the old one

what do you call renderer?

what the debug log contain?

**Comment by gelotus** [comment]
`...
12:11:27.787 T:980  NOTICE: Found screen: Generic PnP Monitor on AMD Radeon R9 200 Series, adapter 0.
12:11:27.792 T:980  NOTICE: Found screen: Generic Non-PnP Monitor on Intel(R) HD Graphics, adapter 16.
...
12:11:48.763 T:980   DEBUG: DX::DeviceResources::SetMonitor: selected Intel(R) HD Graphics adapter.
...
12:12:37.894 T:980   DEBUG: CWinSystemWin32DX::InitHooks: Hooking into UserModeDriver on device \Registry\Machine\System\CurrentControlSet\Control\Video\{31D0E52E-FD16-11E7-8D0A-DE218AED1B46}\0000.
12:12:38.962 T:980   DEBUG: CWinSystemWin32DX::InitHooks: D3D11 hook installed and activated.
12:12:45.480 T:980   DEBUG: DX::DeviceResources::CreateDeviceResources: creating DirectX 11 device.
...
12:12:46.199 T:980   DEBUG: DX::DeviceResources::CreateDeviceResources: device is created on adapter 'Intel(R) HD Graphics' with feature level b000.
...
12:12:46.246 T:980   DEBUG: CWinSystemWin32::SetFullScreen (windowed fullscreen) on screen 1 with size 1920x1080, refresh 32.000000i
...
`
Start playback
`...
12:13:56.393 T:10724   DEBUG: DXVA: supports 'VC-1 variable-length decoder 2 (Intel)'.
12:13:56.393 T:10724   DEBUG: DXVA: supports 'VC-1 variable-length decoder (Intel)'.
...`
Switch screen to amd
`...
12:14:11.202 T:980   DEBUG: CWinSystemWin32::SetFullScreen (windowed) on screen 0 with size 720x480, refresh 0.000000
12:14:11.202 T:980   DEBUG: DX::DeviceResources::ReleaseBackBuffer: release buffers.
12:14:11.202 T:980   DEBUG: CWinSystemWin32::RestoreDesktopResolution: restoring desktop resolution for screen 1,
12:14:11.202 T:980   DEBUG: DX::DeviceResources::SetFullScreen: switching to/from fullscreen (1920.000000 x 1080.000000)
12:14:11.202 T:980   DEBUG: DX::DeviceResources::SetFullScreen: switching done.
12:14:11.202 T:980   DEBUG: CWinSystemWin32::RestoreDesktopResolution: restoring desktop resolution for screen 0,
12:14:11.202 T:980   DEBUG: CWinSystemWin32::AdjustWindow: adjusting window if required.
12:14:11.204 T:980   DEBUG: CWinSystemWin32::AdjustWindow - resizing due to size change (1920,0,3840,1080 fullscreen)->(2512,269,3248,788)
12:14:11.205 T:980   DEBUG: CWinEventsWin32::WndProc: window move event
12:14:11.206 T:980   DEBUG: CWinEventsWin32::WndProc: window resize event 720 x 480
12:14:11.206 T:980   DEBUG: DX::DeviceResources::SetLogicalSize: receive changing logical size to 720.000000 x 480.000000
12:14:11.206 T:980   DEBUG: DX::DeviceResources::SetLogicalSize: change logical size to 720.000000 x 480.000000
12:14:11.206 T:980   DEBUG: DX::DeviceResources::ResizeBuffers: resize buffers.
12:14:11.207 T:980   DEBUG: DX::DeviceResources::CreateBackBuffer: create buffers.
...
12:14:18.979 T:980   DEBUG: CWinSystemWin32::SetFullScreen (windowed fullscreen) on screen 0 with size 1920x1080, refresh 59.940056
12:14:18.979 T:980   DEBUG: DX::DeviceResources::ReleaseBackBuffer: release buffers.
12:14:18.979 T:980   DEBUG: CWinSystemWin32::AdjustWindow: adjusting window if required.
12:14:18.979 T:980   DEBUG: CWinSystemWin32::AdjustWindow - resizing due to size change (2512,269,3248,788)->(0,0,1920,1080 fullscreen)
12:14:18.981 T:980   DEBUG: CWinEventsWin32::WndProc: window move event
12:14:18.981 T:980   DEBUG: CWinEventsWin32::WndProc: window resize event 1920 x 1080
12:14:18.981 T:980   DEBUG: DX::DeviceResources::SetLogicalSize: receive changing logical size to 1920.000000 x 1080.000000
12:14:18.981 T:980   DEBUG: DX::DeviceResources::SetLogicalSize: change logical size to 1920.000000 x 1080.000000
12:14:18.981 T:980   DEBUG: DX::DeviceResources::ResizeBuffers: resize buffers.
12:14:18.983 T:980   DEBUG: DX::DeviceResources::CreateBackBuffer: create buffers.
...`
Restart playback
`...
12:14:44.157 T:5460   DEBUG: DXVA: supports 'VC-1 variable-length decoder 2 (Intel)'.
12:14:44.157 T:5460   DEBUG: DXVA: supports 'VC-1 variable-length decoder (Intel)'.
...`
I have breakpoints on CreateDeviceResources() and InitHook() and after switching was not called at all

**Comment by gelotus** [comment]
for renderer i mean ID3D11Device

**Comment by afedchin** [comment]
@gelotus please try updated fix

**Comment by gelotus** [comment]
Already tried, same results
[Log extract](https://pastebin.com/Bku6A3Ch)

**Comment by gelotus** [comment]
In CWinSystemWin32::AdjustWindow check if the new screen position have the same adapter, if not call SetMonitor() and CreateDeviceResources(). What do you think?

**Comment by gelotus** [comment]
Or more simply trigger a restart on changing screen

**Comment by afedchin** [comment]
@gelotus once again please

**Comment by gelotus** [comment]
Black screen but no crash
[Log](https://pastebin.com/pKLdyaWK)

**Comment by afedchin** [comment]
oh.. my fault, c&p'ed wrong method.
@gelotus and once again please

**Comment by gelotus** [comment]
There be a progress, inithook was called for both adapter, but in the end hooks on last, there is an uninithook call inside, maybe erase the first hook?
[Log](https://pastebin.com/uBg48gt9)

**Comment by afedchin** [comment]
It happens because the window is created on a display connected to Intel GPU (because Kodi creates windows with 0,0-1920,1080 coordinates and this corresponds to your first display) then it's moved to second display which is connected to AMD GPU because of Kodi settings. The behavior looks ok. I'll think how we can improve this.

There can be only one hook. before creating second hook the previous is destroyed.

**Comment by afedchin** [comment]
jenkins build this please

**Comment by afedchin** [comment]
jenkins build this please

**Comment by afedchin** [comment]
@gelotus now it shouldn't initialize device twice

**Comment by afedchin** [comment]
jenkins build this please

**Comment by gelotus** [comment]
> It happens because the window is created on a display connected to Intel GPU
Look that display 0 is AMD and display 1 is INTEL.
In the afternoon I will try your last commit and send you feedback

**Comment by gelotus** [comment]
What a change! 
For clarity let me try to explain the log conf;
Primary adapter is AMD on display 0, secondary adapter is INTEL on display 1 (windows settings), on secondary is plugged a crt projector (1080i@32hz). In kodi settings is selected secondary adapter as default. Start the application, start playback, stopping, switching to primary adapter, start playback, stop & close a
art the application, start playback, stopping, switching to primary adapter, start playback, stop & close app. Here's the log of last commit;
[Log](https://pastebin.com/mAiSfpwt)
As previous, after a switching the d3d11device remain the old one

**Comment by afedchin** [comment]
it should work as expected now.

**Comment by afedchin** [comment]
jenkins build this please

**Comment by afedchin** [comment]
jenkins build this please

**Comment by gelotus** [comment]
Got it! Bravo!
[Log](https://pastebin.com/enmxjmgJ)
Only one thing, look at refresh rate, remains the same as previous after change.

**Comment by afedchin** [comment]
actually it doesn't matter for windowed mode (in your case) but I've added fix for this

**Comment by afedchin** [comment]
jenkins build this please

**Comment by gelotus** [comment]
That's works very well, but during switching to fullscreen windowed to fullscreen, the screen lost sync, seems that have something to do to interlaced vs progressive signal, look at the log:
```
19:36:07.910 T:4628   DEBUG: CWinSystemWin32DX::FixRefreshRateIfNecessary: refreshRate: 63.9856, desired: 32.0000, deviation: 0.49989, fixRequired: true
19:36:07.910 T:4628   DEBUG: CWinSystemWin32DX::FixRefreshRateIfNecessary: refreshRate fix applied -> 32.000
19:36:07.911 T:4628   DEBUG: CWinSystemWin32DX::FixRefreshRateIfNecessary: refreshRate: 32.0000, desired: 32.0000, deviation: 0.00000, fixRequired: false
```
Primary display is progressive:
```
19:38:22.780 T:4628   DEBUG: CWinSystemWin32DX::FixRefreshRateIfNecessary: refreshRate: 59.9401, desired: 59.9401, deviation: 0.00000, fixRequired: false
```

63.9856 is the real refresh rate of secondary adapter, interlaced ~64/2=32
In windowed mode it's working perfect, also in fullscreen windowed.

**Comment by afedchin** [comment]
jenkins build this please

**Comment by afedchin** [comment]
looks like this bug was here a long time. @gelotus can you check that it's fixed by the latest changes.

**Comment by afedchin** [comment]
jenkins build this please

**Comment by gelotus** [comment]
> looks like this bug was here a long time

Interesting, infact  I can't switch to fullscreen also on v17. Compiling now, will see

**Comment by gelotus** [comment]
Nothing, same sync lost on fullscreen on interlaced display.
Are the screen timings that kodi uses the same that windows uses?
I have noticed this, if the app is off focus display correct, when gain focus start to going off sync
[Log](https://pastebin.com/aSLDcbGA)

**Comment by afedchin** [comment]
Unfortunately you have to live with this. Kodi isn't designed to work in interlaced mode. Currently interlaced mode can work properly only in full screen windowed mode only.
I've added a try to fix interlaced true fullscreen mode, but on my test env it works not well.

>Are the screen timings that kodi uses the same that windows uses?

Kodi doesn't use any timings. DirectX does all background work in true fullscreen mode.

**Comment by afedchin** [comment]
jenkins build and merge

**Comment by gelotus** [comment]
Seems that try convert to progressive in fullscreen. But in effects not a big problem, using windowed and voila'.
Great work

**Pull request merged**
