### PR TITLE
[depends] Bump samba-gplv3 to version 4.1.23

### PR DESCRIPTION
**Pull request by Rechi**
## Description
Build samba 4.1.23 by reverting the autotools removal.

## Motivation and Context
Samba 4.1.0 was the first version which supported SMB2/3 protocol for libsmbclient.
This doesn't increase `client max protocol`, its still NT1.
The reasons for not patching this, are
- https://lists.samba.org/archive/samba-technical/2016-November/117005.html
- for some reason showing workgroups only works with NT1

## How Has This Been Tested?
tested on osx and ios
@wsnipex tested it on android

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by wsnipex** [comment]
great, thanks. jenkins build this please

**Comment by Rechi** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
All fine :)

**Comment by Rechi** [comment]
uploaded source code to the mirrors and removed the temporary commit

**Comment by Rechi** [comment]
can this go in, after another jenkins run to be on the save side?

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
