### PR TITLE
[infomanager] add listitem.endtime support for video items

### PR DESCRIPTION
**Pull request by tamland**
Same as Player.FinishTime but for list items.

### CODE REVIEW

**Comment by mkortstiege** [comment]
What about using `LISTITEM_ENDTIME` instead?

**Comment by tamland** [comment]
Looked at that, but I think it's used for the end time of epg entries or something. Not sure about the double meaning. There's also `VIDEOPLAYER_ENDTIME` which is something different again.

**Comment by mkortstiege** [comment]
I think `LISTITEM_ENDTIME` is what it describes best. @Montellese and @xhaggi comments?

Unrelated to this, but IMO we need to cleanup the mess (pvr vs regular item) and sync as much as possible for v16.

**Comment by xhaggi** [comment]
Agree we should use `LISTITEM_ENDTIME` and `VIDEOPLAYER_ENDTIME`

**Comment by tamland** [comment]
Ok. Changed to reuse endtime.

**Comment by mkortstiege** [comment]
Looks good to me now.

**Comment by tamland** [comment]
jenkins build and merge

**Pull request merged**
