### PR TITLE
[videoinfodialog] cleanup obsolete and dupe code

### PR DESCRIPTION
**Pull request by mkortstiege**
This cleans up dupe and obsolete code within the video info dialog. Needs testing.

/cc @BigNoid, @HitcherUK, @Montellese

### CODE REVIEW

**Comment by BigNoid** [comment]
I am missing ListItem.Art(season.poster) on episodes level. Rest seems okay.

**Comment by mkortstiege** [comment]
> I am missing ListItem.Art(season.poster) on episodes level. Rest seems okay.

Jep, season.poster is handled in https://github.com/xbmc/xbmc/pull/7943

**Comment by BigNoid** [comment]
Not in video info, that was always working (and is on master branch)

**Comment by mkortstiege** [comment]
Could you please pull both branches and check if it's working as intended?

**Comment by BigNoid** [comment]
Ah that was what you meant :) 
yep then it works.

**Comment by mkortstiege** [comment]
Sorry. Should have made it clearer. Thanks for testing!

**Comment by mkortstiege** [comment]
Has to go in after https://github.com/xbmc/xbmc/pull/7943.

**Comment by mkortstiege** [comment]
Rebased after #7943 went in. @Montellese mind checking?

**Comment by Montellese** [comment]
Does this still work for non-library items i.e. in files view? I'm not 100% sure how `CVideoInfoTag::m_type` is set there and where the tvshow stuff is populated when not by `CVideoDatabase`.

**Comment by mkortstiege** [comment]
> Does this still work for non-library items i.e. in files view? I'm not 100% sure how CVideoInfoTag::m_type is set there and where the tvshow stuff is populated when not by CVideoDatabase.

Not really sure how to test. Do you know an addon that is using the dialog?

**Comment by mkortstiege** [comment]
Ran some brief tests with various addons. There's no difference with master vs this PR when opening the video info dialog.

**Pull request merged**
