### PR TITLE
[addons][binary] fix few "C" ABI build errors where now possible

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description

There was on few "C" headers a needed include missing to have correct on this language.

Also was in the C++ AddonBase.h no #ifdef __cplusplus to have safe within "C"

There are still some parts where need fixed about "C" but inside "kodi/c-api" they are except PVR now OK.

About PVR and "C" problem comes by his used inputstream where still use C++ classes and data there (about them a different request present)

Here his current error list about: https://paste.kodi.tv/oluyezemiy.kodi

The second commit add include guards to his headers

On the "C" headers inside dev kit was before only the "#pragma once" used.
Them is nice and from most compilers supported, but it's not a standard.

This adds also the old and everywhere supported guard macros to this headers. Thought for cases that this code is taken for other languages, where have a own compiler about and not support the wanted "pragma".

See description here https://en.wikipedia.org/wiki/Pragma_once

## User related:

Not user relevant

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by AlwinEsch** [comment]
jenkins build this please

**Review by garbear — APPROVED** [review]
No problems jump out at me

**Comment by AlwinEsch** [comment]
jenkins build this please with addons please

**Comment by AlwinEsch** [comment]
jenkins build this with addons please

**Review by phunkyfish — APPROVED** [review]
LGTM

**Pull request merged**
