### PR TITLE
Added 1440p/i support

### PR DESCRIPTION
**Pull request by krishiv8190**
## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by krishiv8190** [comment]
#Hacktoberfest

**Comment by garbear** [comment]
Thanks for participating to improve Kodi. You'll notice that the PR template has detailed instructions in comments which you seem to have missed. Further, have you tested this change, or did you just edit on GitHub and hope that it would work?

**Comment by krishiv8190** [comment]
> Thanks for participating to improve Kodi. You'll notice that the PR template has detailed instructions in comments which you seem to have missed. Further, have you tested this change, or did you just edit on GitHub and hope that it would work?

Basically, I have edited on GitHub and hope that it would work!

**Comment by asavah** [comment]
This guy is just trying to get a tshirt ... https://blog.domenic.me/hacktoberfest/

**Comment by garbear** [comment]
@asavah _I'm_ trying to get a shirt :) Could it be that a desire to game the system could accidentally turn into a learning experience about how to be a good open source contributor?

@krishiv8190 In order to respect the time of developers who are invested in this project, there is a process that should be followed. It starts by minimally reading the instructions in the PR template.

Who do you think should have responsibility for testing your change? What if we had merged your PR, only to discover that _you didn't even write correct xml_? (look closely.) You accidentally deleted the end XML tag, which has been a cause of _immediate crash on startup_, really the worst thing that could happen.

However, looking at this change, you clearly have an idea of how to locate source code, make a beneficial change, and expose your improvement to others. I think that this PR can be redeemed.

Please follow the instructions in the PR template and, most importantly, _test your change_. If this process is not respected, then I'll have to invalidate this PR as hacktoberfest participation.

**Pull request closed without merging**
