### PR TITLE
XML nodes - cleanup

### PR DESCRIPTION
**Pull request by ronie**
OCD got the best of me (again)..

@phil65 @DaveTBlake

### CODE REVIEW

**Comment by DaveTBlake** [comment]
Well if it makes you feel better ronie :)

From my perspective I wish these simple little files would format readably for read/edit in Notepad instead of one long line. Could anything be done about that?

**Comment by akva2** [comment]
configure your git properly (checkout windows eol, checkin unix eol). should be in the windows howto on the wiki i believe? 'core.autocrlf' or thereabout.

**Comment by ronie** [comment]
> configure your git properly (checkout windows eol, checkin unix eol). should be in the windows howto on the wiki i believe? 'core.autocrlf' or thereabout.

hmm... i have:
```
[core]
	excludesfile = /home/ronie/.gitignore
	autocrlf = input
```

which should be the correct setting according to the github docs?
https://help.github.com/articles/dealing-with-line-endings/

**Comment by ronie** [comment]
ah, your comment was likely aimed @DaveTBlake

**Comment by akva2** [comment]
^^

**Comment by Montellese** [comment]
@DaveTBlake: for starters use a proper editor ;-)
And on windows you should use `core.autocrlf = true`.

**Comment by DaveTBlake** [comment]
Message received guys. Sorry for the clutter on your PR @ronie

**Comment by ronie** [comment]
no problem, and no matter which editor you decide to use, pick one with syntax highlighting.
those usually know the difference between `&` and `&amp;`    ;-p

**Pull request merged**
