### PR TITLE
[doc] README.Ubuntu: Add missing package libdrm-dev

### PR DESCRIPTION
**Pull request by bugwelle**
## Description

As far as I can see, `libdrm-dev` is required for building Kodi on KUbuntu 20.04 (Focal Fossa). Not tested on Ubuntu 20.04.

I get the following error otherwise:

```
cd kodi
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=$(pwd)/installed_kodi -DCORE_PLATFORM_NAME=x11 -DAPP_RENDER_SYSTEM=gl -DCMAKE_BUILD_TYPE=Debug -GNinja
```

```
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find LibDRM (missing: LIBDRM_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindLibDRM.cmake:30 (find_package_handle_standard_args)
  cmake/scripts/common/Macros.cmake:354 (find_package)
  cmake/scripts/common/Macros.cmake:368 (find_package_with_ver)
  CMakeLists.txt:179 (core_require_dep)
```

## Motivation and Context

It is rather difficult to get Kodi to successfully compile. I struggle with certain dependencies.
I therefore want to update the documentation so that it becomes easier to understand.

## How Has This Been Tested?

Installed `libdrm-dev` and run cmake.

```
sudo apt install libdrm-dev
cmake .. -DCMAKE_INSTALL_PREFIX=$(pwd)/installed_kodi -DCORE_PLATFORM_NAME=x11 -DAPP_RENDER_SYSTEM=gl -DCMAKE_BUILD_TYPE=Debug -GNinja
```

```
...
-- Build files have been written to: /home/andre/Projects/Private/kodi/build
```

Also, the package seems to be available on all Ubuntu platforms:  
https://packages.ubuntu.com/xenial/libdrm-dev

## Screenshots (if appropriate):

N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [x] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

---------------

Please let me know if I forgot anything. :smile: 

Btw: On my system I also needed `libunistring-dev` even though `libunistring2` was installed. Is this expected?

### CODE REVIEW

**Comment by bugwelle** [comment]
Hi Team Kodi,

could someone comment on this PR? 😄 
If I need to do something (e.g. provide detailed installation/build log), please let me know. :)

**Comment by a1rwulf** [comment]
LGTM.

> Btw: On my system I also needed libunistring-dev even though libunistring2 was installed. Is this expected?

Cannot comment on this, though.

**Comment by wsnipex** [comment]
libunistring is a dependency of gnutls

**Review by wsnipex — APPROVED** [review]

**Comment by bugwelle** [comment]
> libunistring is a dependency of gnutls

Thanks. :)

**Pull request merged**
