### PR TITLE
[coverity] fixes for missing breaks and falling-through statements

### PR DESCRIPTION
**Pull request by tobbi**

### CODE REVIEW

**Comment by tobbi** [comment]
This fixes #1262426 Missing break in switch and #1262427

**Comment by Jalle19** [comment]
ping @FernetMenta

**Comment by FernetMenta** [comment]
fall through in case statements is a common pattern. I don't understand why coverity does not like it.

**Comment by tobbi** [comment]
I don't think it works the way you expect. For 0x25 it would first set dec->rollup_rows to 2, then to 3 and then to 4, because it falls through until 0x27.

**Comment by FernetMenta** [comment]
you are right. shame on me and thanks to you
jenkins build and merge

**Pull request merged**
