### PR TITLE
[cleanup] Remove strings.xml support

### PR DESCRIPTION
**Pull request by enen92**
## Description
With the migration to python 3 and its inherent API breakage/addon mandatory updates, it's time to start dropping deprecated API methods and remove redundant functionality that has been deprecated for too long.
Gettext format (strings.po) has been available in Kodi since (at least) Frodo and developers have been requested to update the language files from (at least) Isengard. I haven't seen an addon being submitted to the repo that still includes the strings.xml format. If such addons exist, it is a clear sign they are not being maintained anyway.

## Motivation and Context
Cleanup. Remove redundant functionality.

## How Has This Been Tested?
Compiled and runtime tested. Run test battery.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Review by ronie — APPROVED** [review]
great, it's indeed to say goodbye to this relic

**Comment by Razzeee** [comment]
A quick search on github for `"strings.xml"` shows more occurrences, that should be changed. Mostly docs.

**Comment by enen92** [comment]
@Razzeee thanks for the heads up. Looks like xcode does not index dox files. Should be all good now.

**Review by razzeee — APPROVED** [review]

**Comment by alanwww1** [comment]
Great ! Thanks !

**Pull request merged**
