### PR TITLE
[json-rpc] respect set_videodb_details for tvshows, episodes and musicvideos

### PR DESCRIPTION
**Pull request by enen92**
This is exactly the same as https://github.com/xbmc/xbmc/pull/21289 but added to all the missing nodes (tvshows, episodes and musicvideos) - previous PR only implemented this approach for movies.

@Lunatixz please test and see if any of the nodes is still missing.

### CODE REVIEW

**Review by howie-f — APPROVED** [review]
looks good.

**Comment by DaveTBlake** [comment]
Someone remind me that this data is already part of the API spec, just has not previously been being correctly returned.

**Comment by enen92** [comment]
@DaveTBlake yep, it's in the properties array (the affected method is `Files.GetDirectory`:

https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/methods.json#L658
https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/types.json#L1614-L1633

properties like `cast` or `unique_id` are not being returned even if specified (see https://github.com/xbmc/xbmc/issues/21287)

**Comment by Lunatixz** [comment]
@enen92 working great! THX!!

**Pull request merged**
