### PR TITLE
[Confluence] fix long filenames in subtitles search&download dialog header

### PR DESCRIPTION
**Pull request by fape**
- [before](http://i.imgur.com/eVRhdR7.png)
- [after](http://i.imgur.com/kTDzt4Y.png)

### CODE REVIEW

**Comment by BigNoid** [comment]
The label is set to left 330 because the service logo can have a 250 width. I am fine with this change, but code it so that the service logo and filename label cannot overlap in any case.

**Comment by fape** [comment]
@BigNoid Thanks! Updated.

**Comment by phil65** [comment]
Perhaps adding
```
<haspath>true</haspath>
```
to the label control would be more appropriate?

**Comment by MartijnKaijser** [comment]
@ronie ping

**Pull request merged**
