### PR TITLE
[depends] bump libbluray to 1.1.2

### PR DESCRIPTION
**Pull request by Rechi**
## Description
- bump libbluray to version 1.1.2
- build static
- enable metadata support (libxml2)
- enable font support (freetype2)
- add fontconfig dependency

## How Has This Been Tested?
compiled libbluray and it's dependencies for Android (aarch64, arm, i686), iOS (aarch64, arm), Linux, macOS and tvOS
compiled Kodi for iOS (aarch64, arm) and macOS

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by da-anda** [comment]
does this one need runtime testing? IIRC a forum user mentioned that we might need some core changes to be compatible with a new/changed API for BDJ menus

**Comment by MilhouseVH** [comment]
@da-anda I believe that was with libbluray 1.2: https://github.com/xbmc/xbmc/issues/16331

**Comment by da-anda** [comment]
right, my bad.

**Comment by fandangos** [comment]
I really want to proper implement this on Windows with java enabled. I see that the android version uses the source and cmake compiles it. 
Windows version 1.0.2 has the includes, lib and bin files in a package. 

What is the correct way of updating the windows libbluray? Just compiling dll, the lib and adding the includes? What else needs to be changed? 
Or how different from this would be bumping windows to libbluray 1.1.2?

**Comment by Rechi** [comment]
@wsnipex ping

**Review by wsnipex — APPROVED** [review]

**Pull request merged**
