### PR TITLE
[GPL] Cleanup/uniformize/update license notice in files

### PR DESCRIPTION
**Pull request by hudokkow**
## Description
Cleanup/uniformize/update license notice in files.

* [copyright] commits do not touch code, hopefully. I tried really hard to reduce fuzzy matching to the minimum. Similarly, I tried not to touch others' copyright lines but something might have slipped.
* [links] commit touches `tools/depends`
* [license] commit touches CMake and `tools/buildsteps/windows/` and nukes copying.txt. afaik LICENSE.GPL is enough but I may be wrong. GPL expertise is welcome.

## Motivation and Context
* GPL's notice in files is a brilliant mess. All sorts of variations, typos, wrong FSF address, missing notice lines, etc.
* Copyright line is another mess. All possible variations of Team XBMC, Team Kodi, files created yesterday with `Copyright (C) 2005-2013 XBMC`, etc.

This aims to end it and make grepping the source a little bit less painful by nuking most variations/combinations we currently have of XBMC or Kodi. For instance, only remaining references to `XBMC` are now part of code (class names, namespaces, etc.).

## How Has This Been Tested?
Built on Ubuntu. Needs building/testing on other platforms.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Cleanup

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by MrMC** [comment]
Substituting the revisions years by the word 'present' is not proper copyright notation. Stating the revisions years serves an important function which relates to the length of time the material holds its copyright status. "Present" means nothing in terms of Copyright. Please revert.

**Comment by garbear** [comment]
I recommend leaving Kodi as "the Program" (capitalized). Our headers should be an example for other projects. Frequently I start a new project by using the header from Kodi. Also the license text itself might be copyrighted and disallow modifications.

**Comment by hudokkow** [comment]
Thanks for the input guys.

@MrMC, although `Copyright (C) YEAR-present FooBar` seems to have widespread usage, I can't find a satisfactory answer about its use, either allowing or disallowing, so I tend to agree with you.

Anyway, after spending the better part of my morning reading about GPL and related stuff, these are my findings:

Taken from [Copyright Notices](https://www.gnu.org/prep/maintain/html_node/Copyright-Notices.html) (see section **6.5 Copyright Notices** - bolds are mine):

> To update the list of year numbers, **add each year in which you have made nontrivial changes to the package**. (Here we assume you’re using a publicly accessible revision control server, so that every revision installed is also immediately and automatically published.) When you add the new year, **it is not required to keep track of which files have seen significant changes** in the new year and which have not. **It is recommended and simpler to add the new year to all files in the package**, and be done with it for the rest of the year.

This seems to suggest that `Copyright (C) 2005-2018 Team Kodi` is OK if we think of Kodi as **the package** and assume significant changes were made every year since 2005 (or any other initial release year).

> You can use a range (‘2008-2010’) instead of listing individual years (‘2008, 2009, 2010’) if and only if: 1) every year in the range, inclusive, really is a “copyrightable” year that would be listed individually; and 2) you make an explicit statement in a README file about this usage.

About point `1)`: what constitutes a **copyrightable year**? A year with public releases or any year where significant changes were made? Or both?
I found a similar question on [stackexchange](https://softwareengineering.stackexchange.com/questions/210472/is-renewal-of-mit-license-needed-on-github-at-the-beginning-of-each-year/210491) with the first answer stating

> It is not clear from the FSF guidance whether uploading incomplete, in-progress work to a public repository counts as "finishing a release". My guess is yes, if the work was deliberately made available for public download, but I'm not a lawyer.

> So, to summarize:

> * if you made changes that year, do include the year in a comma-separated list in your copyright notice.
> * if did not make copyrightable changes that year, do not include that year in your copyright notice.

About point `2)`: what does it mean an `explicit statement in a README file about this usage`? Something like
> Kodi is under constant development and keeping track of all the changed files is very hard. For that reason, we decided that it is easier to maintain Kodi's copyright line in the `Copyright (C) INITIAL_YEAR-PRESENT_YEAR Team Kodi` format in all files, e.g. `Copyright (C) 2005-2018 Team Kodi`


@garbear

Taken from [GPL How-To](https://www.gnu.org/licenses/gpl-howto.html) (see section **The license notices**)

> For programs that are more than one file, it is better to replace “this program” with the name of the program, and begin the statement with a line saying “This file is part of NAME”

    This file is part of Foobar.

    Foobar is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Foobar is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Foobar.  If not, see <http://www.gnu.org/licenses/>.

Don't think the notice itself is copyrighted but can't find much information about that.

Opinions are welcome.

Resources:
* [XBMC/Kodi releases](https://kodi.wiki/view/Releases)
* [GPL How-To](https://www.gnu.org/licenses/gpl-howto.html)
* [Copyright Notices](https://www.gnu.org/prep/maintain/html_node/Copyright-Notices.html)
* [License Quick Start](https://producingoss.com/en/license-quickstart.html)
* [COPYING vs LICENSE](https://stackoverflow.com/questions/5678462/should-i-provide-a-license-txt-or-copying-txt-file-in-my-project)

**Comment by garbear** [comment]
Good point, let's move to Kodi.

> About point 1): what constitutes a copyrightable year? A year with public releases or any year where significant changes were made? Or both?

All years the project has been written are a copyrightable year. Copyright is assigned on creation. I don't know what would exclude something from eligibility for copyright, but it's probably not something we've done.

**Comment by MrMC** [comment]
The copyright year assignment really belongs to the author(s) of said code. Make lots of changes, bump the year. Non-authors of code have no business messing with the assigned years.

**Comment by garbear** [comment]
The author only explicitly claims copyright when they place their name in the copyright notice. If they don't, copyright is assigned to Team Kodi (the author retains their copyright too). We have full copyright for all files with `Copyright <year> Team Kodi` in the header.

I don't think it's fair to ask all contributors to update the year of every file they touch. This is too much overhead. Better would be to replace hudo's batteries every once in a while and have him do the updates for all contributors. However, from above,

```
It is not required to keep track of which files have seen significant changes in the new year and which have not. It is recommended and simpler to add the new year to all files in the package, and be done with it for the rest of the year.
```

It seems updating every file is recommended and, more importantly, probably much less work for hudo.

**Comment by chewitt** [comment]
If you're going to touch all files in the repo it might be an idea to convert Kodi to the SPDX format for license expression and copyright marking. Have a look at how the Linux kernel uses it.

**Comment by hudokkow** [comment]
@garbear, sounds good. Thanks for the input and insight. :+1:

@chewitt, that's an excellent idea. I wasn't aware of such an effort from the Linux Foundation. I think it's the way forward. After all, if it's good for Linus "I'm a bastard" Torvalds, it should be good for us.

Interesting links:
* https://www.kernel.org/doc/html/v4.16/process/license-rules.html
* https://lkml.org/lkml/2017/11/12/110
* https://lkml.org/lkml/2017/11/2/590

Specially interesting because it refers to GPLv2 license changes over the years:
* https://github.com/torvalds/linux/commit/255247c2770ada6edace04173b35307869b47d99
* https://github.com/pombredanne/gpl-history/commits/master/COPYING


@MrMC, I know you're a stake holder. We all are. That said, this is not the first time something like this is done. We didn't got into trouble then, we should be OK now.
* https://github.com/xbmc/xbmc/commit/27001ae91df3583aa2c1a6e7586b65dc44387668#diff-379da99f9a6781a1126b08019b47b839
* https://github.com/xbmc/xbmc/commit/b0fa5b3d3209a55c4f7742026d8fc51df8fc8b93#diff-379da99f9a6781a1126b08019b47b839

I ran [scancode](https://github.com/nexB/scancode-toolkit/) today on our codebase and the result can be seen [here](http://kodi-licenses-scancode.bitballoon.com/).

**Comment by pkerling** [comment]
I'm not sure you are even able to assign the copyright to "Team Kodi" as it is neither a person nor a legal entity. Theoretically speaking, either the authors would have to add their name and copyright year to the header if they make nontrivial changes (common practice in many open source projects) or we would have to assign everything to the XBMC Foundation with authors waiving their copyright claims (with or without CLA).

**Comment by pkerling** [comment]
Sidenote: As far as I am aware there is also the option to nuke all the detailed copyright headers in the files and just say "This file is part of Kodi. See the file LICENSE in the top level folder for copyright information."

**Comment by pkerling** [comment]
http://softwarefreedom.org/resources/2012/ManagingCopyrightInformation.html

**Comment by MartijnKaijser** [comment]
From my previous endeavour with the copyright header is that changing the year is quite pointless. See past PRs regarding this over the many years.
The header dates back when source code was still kind of printed on paper or no decent revision tracking system was in place. With git that all is taken care of and the author of the changes is part of the git rev system. Team Kodi / Team XBMC / whatever else is there can't own any code as it never got any copyright transfer agreements. The copyright remains with the person(s) who wrote it.
Also copyright will remain valid for about 25 years iirc from day of change.

**Comment by hudokkow** [comment]
Closing this one. It will eventually be replace by https://github.com/hudokkow/xbmc/pull/4, when I find the time.

**Pull request closed without merging**
