### PR TITLE
[addons] dont call normal enable hooks when checking system addons

### PR DESCRIPTION
**Pull request by tamland**
EnableAddon have have side effects that shouldn't be included when simply 'correcting' any bad state.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Yes, that fixes the issue - many thanks!

Of course it would still be nice to be able to automatically enable _some_ system installed addons, hopefully that will be possible somehow.

**Comment by tamland** [comment]
jenkins build this please

**Comment by tamland** [comment]
@MilhouseVH Request noted, but I want to see what the outcome of #9374 is first

**Comment by MilhouseVH** [comment]
I'm seeing a mixture of results following this PR. Some users still have the 5 minutes delay, then all PVR addons enabled (which is clearly not ideal). If all Addons*.db files are deleted, there is no delay but no addons are enabled, including those installed by the user, which again isn't ideal. Some users though still seem to have the 5 minute delay, so I've no idea what's going on, really.

Feedback is here: http://forum.kodi.tv/showthread.php?tid=250817&pid=2291442#pid2291442

**Comment by tamland** [comment]
@MilhouseVH Can you try https://github.com/tamland/xbmc/commits/fix_system_addon_enabling_alt
Sounds odd that the db access would case *that much* slowdown though. (I'll probably use this alternative solution anyway as its much cleaner)

**Comment by MilhouseVH** [comment]
I've tried https://github.com/tamland/xbmc/commits/fix_system_addon_enabling_alt (ie. these [commits](https://github.com/xbmc/xbmc/compare/xbmc:00a92f8de46e40ff1d0d58f6d4810c797e079135...tamland:0edad3072578aa4ec0eee58e14adf1644159a228)), and will include it in tonight's #0325 build but didn't personally notice any significant improvement.

Should all Addons*.db be deleted first, or should users upgrade from Addons21.db? Or will this fix an existing Addons22.db?

I've tried deleting all Addons*.db => No startup delay, all system installed addons are disabled (ie. pvr addons etc.), but self-installed third-party addons are also disabled (ie. Amazon Prime and associated dependencies eg. `script.module.mechanize` so Amazon Prime can't be re-enabled from the GUI without first re-enabling all dependencies).

Upgrading from Addons21.db => No startup delay, while some (but not all) PVR addons were re-enabled . Looking at Addons21.db I have:
```
sqlite> select * from installed where addonId like 'pvr.%';
6|pvr.vbox|0|2016-02-11 18:46:57||
14|pvr.argustv|0|2016-02-11 18:46:57||
15|pvr.vdr.vnsi|0|2016-02-11 18:46:57||
21|pvr.mediaportal.tvserver|0|2016-02-11 18:46:57||
31|pvr.wmc|0|2016-02-11 18:46:57||
35|pvr.hdhomerun|0|2016-02-11 18:46:57||
48|pvr.mythtv|0|2016-02-11 18:46:57||
55|pvr.demo|0|2016-02-11 18:46:57||
57|pvr.pctv|0|2016-02-11 18:46:57||
58|pvr.iptvsimple|0|2016-02-11 18:46:57||
63|pvr.njoy|0|2016-02-11 18:46:57||
65|pvr.nextpvr|0|2016-02-11 18:46:57||
79|pvr.stalker|0|2016-02-11 18:46:57||
97|pvr.filmon|0|2016-02-11 18:46:57||
98|pvr.hts|0|2016-02-11 18:46:57||
118|pvr.vuplus|1|2016-02-18 13:42:09||
120|pvr.dvblink|1|2016-02-27 13:27:04||
121|pvr.dvbviewer|1|2016-02-27 13:27:04||
```
yet I don't use PVR so not entirely sure how those three PVR addons were marked "enabled" in `installed`. Maybe some hangover from a previous time.

Currently the behaviour with add-ons is now very different from how it used to be - in the past you could safely delete Addons*.db without any major ill effect, but now the installation is left mostly disabled, and it's very difficult to re-enable user-installed add-ons if they have dependencies on other disabled scripts/modules etc.

**Comment by MilhouseVH** [comment]
Another (related?) problem:
```
03:55:49 T:139906206627968   DEBUG: ------ Window Deinit (FileBrowser.xml) ------
03:55:49 T:139906206627968   DEBUG: CAddonInstaller: installing from zip '/freenas/data/repository.zachmorris-1.0.0.zip'
03:55:49 T:139906206627968   DEBUG: Keyboard: scancode: 0x24, sym: 0x000d, unicode: 0x0000, modifier: 0x0
03:55:49 T:139904977716992   DEBUG: ADDON: cpluff: 'Unknown plug-in repository.zachmorris could not be uninstalled.'
03:55:49 T:139904977716992   DEBUG: ADDON: cpluff: 'Plug-in repository.zachmorris has been installed.'
03:55:49 T:139904977716992   DEBUG: ADDON: cpluff: 'Not all directories were successfully scanned.'
03:55:49 T:139904977716992   DEBUG: CAddonDatabase: repository.zachmorris has been installed.
03:55:49 T:139904977716992   ERROR: SQL: [Addons22.db] Abort due to constraint violation
                                            Query: INSERT INTO installed(addonID, enabled, installDate) VALUES('audioencoder.xbmc.builtin.aac', '1', '2016-03-26 03:55:18')
03:55:49 T:139904977716992   ERROR: ExecuteQuery - failed to execute query 'INSERT INTO installed(addonID, enabled, installDate) VALUES('audioencoder.xbmc.builtin.aac', '1', '2016-03-26 03:55:18')'
03:55:49 T:139904398915328   DEBUG: Thread Timer 139904398915328 terminating
03:55:49 T:139904977716992   DEBUG: CRepositoryUpdater: previous update at 26/03/2016 3:55:22, next at 27/03/2016 3:55:22
```
Complete log: http://sprunge.us/NZGB

##### Steps to reproduce (tested on Ubuntu x86_64 and latest OE test build, #0325):

1) Delete all `Addons*.db`

2) Start Kodi (latest master 00a92f8de46e40ff1d0d58f6d4810c797e079135, with these additional [commits](https://github.com/xbmc/xbmc/compare/xbmc:00a92f8de46e40ff1d0d58f6d4810c797e079135...tamland:0edad3072578aa4ec0eee58e14adf1644159a228), creating `Addons22.db`

3) Install a repository from zip, eg. [Internet Archive ROM Launcher](http://forum.kodi.tv/showthread.php?tid=231339): https://github.com/zach-morris/repository.zachmorris/releases/download/1.0.0/repository.zachmorris-1.0.0.zip

4) Repository fails to install due to above database error.

**Comment by tamland** [comment]
Seems like yet another bug in database code!:\  See #9458. I've updated this PR and tested it as much as I can. (it's not required to include #9458). Thanks for bearing with me!

**Comment by MilhouseVH** [comment]
Thanks, 9458 seems to fix the SQL error.

With this updated PR, migrating from Addons21.db is still the best solution to a healthy system - a freshly created Addons22.db still leaves user-installed addons (and dependencies) disabled.

**Comment by tamland** [comment]
jenkins build this please

**Comment by tamland** [comment]
@MilhouseVH I see people are still reporting issues in the forums but I fail to see how the 'delay' or any other issue is related to this PR. Can we please take one issue at a time and report them at the appropriate places?

**Comment by MilhouseVH** [comment]
Not sure what you mean by the appropriate places - if you mean trac, few people can log in to that right now, I certainly can't. Feel free to directly engage with the users reporting problems on the forum, maybe you can extract the relevant information from them that might explain the different add-on related problems now present in master. I've done what I can to explain what I'm seeing.

I'm taking a short break from test builds but if you have anything you want tested let me know.

**Comment by tamland** [comment]
Will do. I only meant to say you are talking about a whole bunch of different issues at the same time here. This fix was only meant to be for the deadlocking issue that you reported in #9110.

**Pull request merged**
