### PR TITLE
peripheral: Add backward compatability for older settings files

### PR DESCRIPTION
**Pull request by MilhouseVH**
See discussion: https://github.com/xbmc/xbmc/pull/10309/files#r77446924

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@garbear ping

**Comment by garbear** [comment]
looks good. button belongs to someone who isn't about to disappear in the wilderness for 6 days

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by hudokkow** [comment]
win32 failure unrelated. [New run](http://jenkins.kodi.tv/job/WIN-32/9879/) shows everything is OK.

**Pull request merged**
