### PR TITLE
ADD: [droid] standard refreshrate switcher (>= api 21)

### PR DESCRIPTION
**Pull request by koying**
All credit to @anssih
It's basically a cleanup on his great work

/cc @MartijnKaijser

### CODE REVIEW

**Comment by koying** [comment]
jenkins build this please

**Comment by anssih** [comment]
Thanks for finishing this :) have been a bit too busy with other stuff this year myself...

I don't see much (or any?) new code here, though - back when I was working on this it was still buggy, i.e. there was UI corruption unless skin was reloaded, which in turn caused other issues, and sometimes audio vanished on refresh rate switch until reboot, etc...

Did you fix those issues separately, or did they magically get fixed (by a new Android version maybe)?

Unfortunately can't test myself right now.

**Comment by MartijnKaijser** [comment]
I think it's combination of Android fixes, magical disappearance and Kodi fixes.
It works well on the ADT1, Nexus Player and NVIDIA Shield

**Comment by koying** [comment]
Seems the issues vanished by themselves (or were solved independently) really.
Did not noticed any of the issues you mention on shield.

**Comment by koying** [comment]
@anssih BTW, could you point to the hacking you tried for having "droid-like" AC3, i.e. non-encapsulated one.
Seems they will add DTS and even DTS-MA this way

**Comment by anssih** [comment]
OK. I guess Android (or HW driver) fixes are the likely cause then.

Again this isn't really a bugfix, but I'm not opposed to pulling it in. I think auto refresh rate switching is disabled by default anyway? which makes this a rather safe thing to have (even if some people still have affected Android versions).

The code looks OK (though it is mostly my code so I'm not in a good position to review it :p).

**Comment by MartijnKaijser** [comment]
it's indeed default off so it safe from default users. It's also been in several testbuilds which a bunch of users had good results with.

**Comment by koying** [comment]
> The code looks OK (though it is mostly my code so I'm not in a good position to review it :p).

Hehe... Absolutely. I don't think I actually did anything else than cleaning your code :)

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
