### PR TITLE
[BACKPORT]Install KodiConfig.cmake to arch-specific path

### PR DESCRIPTION
**Pull request by basilgello**
Backport of #20506

### CODE REVIEW

**Review by garbear — APPROVED** [review]
I don't remember reviewing the original PR but the change itself looks good.

**Comment by DaveTBlake** [comment]
> I don't remember reviewing the original PR but the change itself looks good.

That is because you have not reviewed it yet @garbear, so over you go. :) 

Please no one hit merge on this before it is in master first!!

**Comment by DaveTBlake** [comment]
Bumping to 19.5 since this is not in master

**Comment by basilgello** [comment]
Now it is in master :)

**Comment by wsnipex** [comment]
the idea was to have it in master for a while before backporting...

**Pull request merged**
