### PR TITLE
spelling: [API] GetMininumGameAPIVersion

### PR DESCRIPTION
**Pull request by jsoref**
Spelling fixes

## Description
Semi-automated spelling review of codebase (includes comments, code, public apis, documentation, etc)

## Motivation and Context
I have a toolchain which I've been evolving for a while, and I like to test it on projects, especially as a way to give a little in appreciation of projects that I may be using/have used/plan to use.

## How Has This Been Tested?
- [x] This has not been tested.

## Types of change
- [x] Breaking change
- - [x] Public APIs - I'm pretty sure I've renamed some public APIs. I'm happy to split such items out (either including backwards compat or dropping them entirely), but I'd rather have a conversation about which those things are before I eagerly split.

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by garbear** [comment]
Thanks, I appreciate the time these things can take. I've mode the corresponding game.libretro changes: https://github.com/kodi-game/game.libretro/pull/12. Can you bump the Game API version to v1.0.30?

**Comment by garbear** [comment]
Also needed is an update to game.moonlight. I'll take care of it this weekend unless you get to it first

**Comment by Razzeee** [comment]
@jsoref Would you be so kind and rebase this PR?

**Comment by AlwinEsch** [comment]
You must also update the version here if changed in versions.h: https://github.com/jsoref/xbmc/blob/8656c0a840e0d38a6818e98c19b0323a6a891828/addons/kodi.game/addon.xml#L3

**Comment by jsoref** [comment]
Done

**Comment by Razzeee** [comment]
jenkins build this please

**Comment by Razzeee** [comment]
jenkins build this please

**Pull request merged**
