### PR TITLE
Fix cmake failing on systems with older cmake

### PR DESCRIPTION
**Pull request by a1rwulf**
CMake 3.20 appears to be  the minimum requirement for multi-config generator expressions in general, not only on windows.

Building on Ubuntu 20.04 for example fails with following error: CMake Error at CMakeLists.txt:437 (add_custom_command):
  add_custom_command called with OUTPUT containing a "<".  This character is
  not allowed.

This error happens with at least 3.16-3.19 and is fixed when switching to 3.20.

## How has this been tested?
Tested on my Ubuntu 20.04 build machine.

## What is the effect on users?
Require minimum version instead of failing with a weird error.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by howie-f** [comment]
tested with debian bullseye `cmake 3.18.4`
it appears that `86baa0ad30 Merge pull request #23779 from fuzzard/cmake_gen_skin_pack` https://github.com/xbmc/xbmc/pull/23779 introduced this error.
maybe look for a glitch there instead of bumping cmake minimum requirement

**Comment by a1rwulf** [comment]
So it works for you with 3.18.4?

**Comment by howie-f** [comment]
@a1rwulf please try to build https://github.com/xbmc/xbmc/pull/23782 since this  is the merge commit before the 1st failing one

**Review by fuzzard — APPROVED** [review]
for reference down the line
from https://cmake.org/cmake/help/latest/command/add_custom_command.html
> New in version 3.20: Arguments to OUTPUT may use a restricted set of [generator expressions](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#manual:cmake-generator-expressions(7)). [Target-dependent expressions](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#target-dependent-queries) are not permitted.

I could probably remove the genex from the output. Its not really required, as its a timestamp file only anyway.

@wsnipex whats your opinion on the bump? try to stay lower than 3.20?

The reasoning was to keep config variant data together, so you dont have a timestamp from a debug when you go and build release. It may not be required to handle it like that, but that was the reasoning i went with at the time :/

**Comment by fuzzard** [comment]
Actually ive got another solution instead of this. Just testing it works as intended

**Comment by a1rwulf** [comment]
Tested your solution and seems to work with cmake 3.16.3 as well.
Let's not bump the version then.

**Pull request closed without merging**
