### PR TITLE
[cmake] move ifdef conditions to cmake

### PR DESCRIPTION
**Pull request by Rechi**
## Description
Move condition checking to cmake if the whole `*.cpp` file is enclosed into one `#if ...` .

## Motivation and Context
No need to compile empty files.
This also silences output like `.../usr/bin/ranlib: file: xbmc.a(Autorun.cpp.o) has no symbols` on osx.

## How Has This Been Tested?
compiled

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Review by hudokkow — APPROVED** [review]
Nice!
Very quick browse but everything looks good to me.

**Comment by hudokkow** [comment]
jenkins build this please

**Review by fetzerch — APPROVED** [review]
Looks good, thx.

Just wanted to mention the optional treedata structure again (example: https://github.com/xbmc/xbmc/blob/master/cmake/treedata/optional/common/webserver.txt). Maybe for avahi it could make sense to use.

**Comment by Rechi** [comment]
@fetzerch sorry seen your comment to late, github hasn't auto pushed it

**Pull request merged**
