### PR TITLE
[depends] gnutls 3.4.14 and nettle 3.2

### PR DESCRIPTION
**Pull request by mrdominuzq**
another try on #9958

it compiles now on android i686.
i'm not sure if the --extra-libs needs to be moved to a if android

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@wsnipex ping
jenkins build this please

**Comment by MartijnKaijser** [comment]
it helps that the file is on the server
jenkins build this please

**Comment by mrdominuzq** [comment]
it seems i forgot to add it to the cmake file and FFMPEG-VERSION file.

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by mrdominuzq** [comment]
Perfect :+1:

**Comment by MartijnKaijser** [comment]
Perfect? It fails on Linux and raspberrypi

**Comment by mrdominuzq** [comment]
i get the same error when rebuilding and the ffmpeg directory is not empty.
can you trigger a new build :)?

**Comment by mrdominuzq** [comment]
whoops it seems i forgot that rpi and linux doesn't build libiconv and that's why it breaks :)

**Pull request closed without merging**
