### PR TITLE
[binary-addons] Rename DEPENDS_PATH to ADDON_DEPENDS_PATH

### PR DESCRIPTION
**Pull request by fetzerch**
## Description
A variable called DEPENDS_PATH is used twice in the build system:
- In the core build system: It's set to the system depends path (via toolchain file)
- In the binary-addon build system it's used to point to the place where addon dependencies should be built and can be found.

This change renames the variable for binary-addons to ADDON_DEPENDS_PATH. Alternative would be to rename the variable in the toolchain file. While this would be less effort, I think it's cleaner if DEPENDS_PATH is used for core depends, not addon depends.

Possible impact:
If addon devs set this var in their custom scripts, they'll have to adapt it. (@AchimTuran was doing that afaik)

Ping: @wsnipex, @notspiff, @hudokkow.

## Motivation and Context
This can cause very hard to debug issues. I've ran into it while trying to compile a binary addon with our normal Toolchain file. The toolchain file accidentally tells the addon build system to compile addon depends into the system depends and even worse: to pick up depends from there.

## How Has This Been Tested?
Locally on Linux and osx.

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by wsnipex** [comment]
I agree in principle, lets just hope not too many addons use DEPENDS_PATH

**Comment by hudokkow** [comment]
lgtm
I have a feeling this is going to kill win32 retroplayer builds. :wink:
jenkins build this with addons please

**Comment by hudokkow** [comment]
jenkins build this with addons please

**Comment by hudokkow** [comment]
Working as expected, except for the usual suspects failing.

The only add-on I could find using DEPENDS_PATH on my (somewhat outdated) add-ons build env is [screensavers.rsxs](https://github.com/notspiff/screensavers.rsxs/blob/master/CMakeLists.txt#L42-L49).

@garbear, you might want to cherry-pick https://github.com/hudokkow/xbmc/commit/af5326dfffb89035b4eaea8cfdee54949415da13 **before** rebasing for beta6/RC if this goes in. Should make your life easier. :sweat_smile: 

jenkins retroplayer-17beta5 build with this PR + missing bits: http://jenkins.kodi.tv/view/Windows/job/WIN-32/10567/

**Comment by fetzerch** [comment]
Thanks much @hudokkow (especially for thinking about retroplayer ;))
Any objections getting this in?

**Comment by hudokkow** [comment]
Not from me.

**Comment by wsnipex** [comment]
fine for me

**Comment by fetzerch** [comment]
@garbear: please see @hudokkow's [comment](https://github.com/xbmc/xbmc/pull/10865#issuecomment-258653183) now that this is merged

**Comment by fetzerch** [comment]
@garbear, @hudokkow: a few places got forgotten in the retroplayer patch, please pick https://github.com/fetzerch/xbmc/commit/690379e19906b6de3f42885141194a23f4daead1

**Pull request merged**
