### PR TITLE
[ExecString] combine SplitParameters with identical function of CUtil

### PR DESCRIPTION
**Pull request by CrystalP**
## Description

Fixed in CUtil::SplitParams() the issue corrected in CExecString::SplitParams() by #24821

`parameter.erase(quotaPos);` => `parameter.erase(quotaPos, 1);`

Since both versions of the function were identical, share the code rather than duplicate it.

## Motivation and context

Issue found in CUtil::SplitParams() while checking the history of the changes that led to the bug and fix in CExecString::SplitParams() by #24821. Then I noticed that the code in both classes was identical.

Not sure why an identical copy was created by #22118. @ksoo it looks like you wrote that PR, any idea?

Before that, #3507 converted a now deleted class CStdString, with a member  `Delete(int nIdx, int nCount=1)` to `std::string::erase()`.
Unfortunately the default value of the second parameter was not copied to all conversions to `erase()`, creating the bug in `CUtil::SplitParams()`, later copied to `CExecString::SplitParams()`.
I checked the other changes of #3507 and that was the only one that required a fix. because the other Delete() calls had an explicit parameter value and were converted correctly, or removed the last character of a string, which doesn't need a count parameter for erase() to do the same thing.

## How has this been tested?

no runtime change noticed.

## What is the effect on users?

None

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [X] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [X] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by CrystalP** [comment]
@ksooo @garbear @neo1973 FYI since you commented/approved the similar #24821

**Review by garbear — APPROVED** [review]
Would you want to write some tests for this?

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by CrystalP** [comment]
Pushed a bunch of tests.

**Comment by CrystalP** [comment]
Thanks for suggesting R"( @notspiff, it made things easier and I added a few more tests.
I wrote down a few things that didn't seem aligned with the "spirit" of the existing SplitParams logic or that are pathological situations, with no real impact.
Good job predecessors, the code is older than the linux port, I didn't track down the history any further.

**Pull request merged**
