### PR TITLE
[Leia] [backport] Bump mariadb connector version from 3.0.3 -> 3.1.9

### PR DESCRIPTION
**Pull request by bkuhls**
Cherry-picked from https://github.com/xbmc/xbmc/pull/16275 and https://github.com/xbmc/xbmc/pull/18137

Bump MariaDB connector version from 3.0.3 to latest released 3.1.9

For Android 3.0.3 does not work properly with server versions 10.5.4, field types in result sets are not returned correctly therefore users see only "0" for all string fields.

### CODE REVIEW

**Comment by enen92** [comment]
jenkins build this please

**Comment by sopparus** [comment]
I tested this and it does solve the problem when server is mariadb 10.5. also tested with 10.4 and it was fine

**Comment by Montellese** [comment]
I aborted the FreeBSD build on jenkins after it was stuck for more than 20 hours on running a unit test. jenkins build this please

**Comment by M2k80** [comment]
would be nice, if that could be merged soon, my nas just updated the mariadb package and my library is not working anymore.
i tested this PR build, its working, but it does not have some binary addons included like inpustream adaptiv.

thx

**Comment by M2k80** [comment]
or could be maybe someone make a test-build please

**Comment by phunkyfish** [comment]
Jenkins build this please

**Comment by DaveTBlake** [comment]
Jenkins build this please

**Comment by M2k80** [comment]
anybody knows why this, and only this build has missing this? looked trough other builds it was always included
Task :xbmc:mergeDebugUnsignedNativeLibs
/out/lib/arm64-v8a/libinputstream.adaptive.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
jenkins build this pr now 3x in the last days, but inputstream is always missing...

hopefully the new nightly will have it again..

@DaveTBlake thx for merging

**Comment by fuzzard** [comment]
PRs don't build.with addons

**Comment by M2k80** [comment]
inputstream adaptive is shipped always on android!

**Comment by fuzzard** [comment]
And it's a binary add-on that is not built for PRs

**Comment by M2k80** [comment]
ok sorry then for the trouble

**Pull request merged**
