### PR TITLE
[settings.xml] -  changed several spinners to lists

### PR DESCRIPTION
**Pull request by phil65**
like discussed some weeks ago, this changes several spinners to lists in settings.
Basically I left out:
- spinners dealing with numbers and fixed step size
- some settings which caused a delay until DialogSelect appears

@Montellese for review.

### CODE REVIEW

**Comment by Montellese** [comment]
I don't really have a strong opinion on this. The changes are trivial.
There are a few settings which basically represent a tri-state (e.g. `videolibrary.flattentvshows`) which might work as a spinner as well. But like I said I'm not very good with UI/UX so I leave it to the people who know better.

**Comment by phil65** [comment]
yeah it ´s more about an opinion than a review, that´s correct.
I will pick @ronie, @BigNoid, @da-anda  as UI people then. :)

**Comment by BigNoid** [comment]
+1, this is an improvement on usability. Are videoplayer.stereoscopicplaybackmode and videoscreen.screen too slow to convert to spinners or did you miss those?

**Comment by ronie** [comment]
+1 for the exact same reason as @BigNoid 
this drastically improves usability.

**Comment by phil65** [comment]
@BigNoid : yes, I think both were too slow. Perhaps you can try out if it is the same on your machine.

**Comment by da-anda** [comment]
will check/review once I'm fully recovered from vacation - but in general +1 on anything that improves UX

**Comment by tamland** [comment]
Any plans merging this? The spinners are so annoying..

**Pull request merged**
