### PR TITLE
Add Favourites to the list of startup windows

### PR DESCRIPTION
**Pull request by dagwieers**
## Description
This adds Favourites to the list of possible start-up windows.

## Motivation and Context
Having the Favourites dialog in the possible startup window targets is
very convenient as this is where all the important stuff (from different
add-ons live together).

Also nice would be if we could go into the add-on view as well.

Even better would be to add add-on's or register add-on paths to this
list so we could offer a more complete experience.

## How Has This Been Tested?
This has not been tested.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by notspiff** [comment]
i don't think WINDOW_ADDON_BROWSER is what you think - it's the install / configure / show what is installed window. why anyone would want to start there escapes me.

**Comment by HitcherUK** [comment]
Also favourites is a dialog not a eindow

**Comment by dagwieers** [comment]
@notspiff I removed it.

@HitcherUK That's deliberate. It's the only thing we can do at the moment.

Feel free to contribute a better implementation if you know how.

**Comment by HitcherUK** [comment]
But that causes 2 problems. 
1. The start window is normally blank so the dialog will look odd
2. When you close the dialog you’ll be stuck on the start window with no way to leave it

**Comment by dagwieers** [comment]
@HitcherUK Feel free to propose a better implementation, as I do not see it.

The Addon Launcher and Favourites are the 2 most important startup windows if you use Kodi for online streaming (rather than local media files).

**Comment by DaVukovic** [comment]
I just runtime tested it under Ubuntu 18.04 and using Estuary. 

grafik

This is what shows up after selecting "Favourites" as the startup window. As you can see, there's no Kodi home screen visible behind. By cancelling this dialog you will end up like that: 

grafik

The only way to get back to the Kodi homescreen for me was to send "ActivateWindow(Home)". Otherwise you won't reach the Kodi home screen at all which currently breaks existing functionality. 

As I somehow understand the reason for this PR, it can't be added in this way unfortunately.

**Comment by DaVukovic** [comment]
As I saw those requests from time to time already I solved them by suggesting to use an `autoexec.py` and fill it with:

```
import xbmc

xbmc.executebuiltin('ActivateWindow(Favourites)')
```

That will be loaded after Kodi has been started with at least any kind of window instead of using a Dialog as a startup window where no other window will be loaded before. 

By using that autoexec.py you will end up like that: 

grafik

no matter what kind of startup window you have selected (instead of Favourites ;) ).

**Comment by dagwieers** [comment]
@DaVukovic That is a workaround and yes, that is what we are now telling people to do, but you can't really expect people to have to log on to a device and edit files on it. This functionality really should be part of the settings.

**Comment by DaVukovic** [comment]
I'm not saying that I'm against it. I'm just saying that it can't be implemented in the way you PRd it ;). I'm not a dev so I don't have any other suggestion. 

You should at least test your PRs yourself. Then you might have seen it that it's a no-go currently. This PR here, as it is in its current state, can't be merged IMO. Feel free to add/change something else to make this work. 

What I could imagine (what does not mean that it will be accepted by the core devs) is an additional setting like "Startup dialog" which will be loaded after a window has been loaded. But I leave it up to you and what you have in mind.

**Comment by dagwieers** [comment]
@DaVukovic There are various reasons why I couldn't test this myself, one is the need to compile for ARM. That said, the fact people have proposed this before and it still isn't here should ring a bell. 

Regardless of the fact that jumping within the Home-screen is skin-dependent, or whatever other reason this wasn't already added. I have seen add-ons that have an option to add itself to autoexec, which IMO is a no-go.

**Comment by HitcherUK** [comment]
If you don’t have a solution I suggest closing this PR and make a request on the forum instead.

**Comment by jjd-uk** [comment]
I guess the solution would be to resurrect the proposal to make Favourites a window, however some had objections before see https://github.com/xbmc/xbmc/pull/8982

**Comment by DaVukovic** [comment]
>  I have seen add-ons that have an option to add itself to autoexec, which IMO is a no-go

True. I agree. Hence I would highly doubt that ANY of the add-ons shipped by the Kodi repo will do that. And if those add-ons do come from whatever 3rd party repo you might have added, then it's also up to you as you need to trust the repos and add-ons which are shipped by them. Nothing we can do about that and we don't even care

**Pull request closed without merging**
