### PR TITLE
[cpluff] link with cpluff instead of loading it dynamic

### PR DESCRIPTION
**Pull request by Rechi**
## Description
Don't load cpluff dynamic, but link against it (shared/static).

## Motivation and Context
As Kodi calls cpluff functions on startup there is no reason to lazy load the lib.

## How Has This Been Tested?
compiled and runtime tested for windows and linux

## Types of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Review by notspiff — APPROVED** [review]
looks all good

**Comment by MilhouseVH** [comment]
Any ideas? http://ix.io/10zf

**Comment by FernetMenta** [comment]
I get dupe symbols on OSX:

```
duplicate symbol _hash_insert in:
    /Users/DE213022/progs/src/xbmc/build/build/cpluff/lib/libcpluff.a(hash.o)
    /Users/Shared/xbmc-depends/macosx10.13_x86_64-target-debug/lib/mariadb/libmariadbclient.a(ma_hash.c.o)
duplicate symbol _hash_delete in:
    /Users/DE213022/progs/src/xbmc/build/build/cpluff/lib/libcpluff.a(hash.o)
    /Users/Shared/xbmc-depends/macosx10.13_x86_64-target-debug/lib/mariadb/libmariadbclient.a(ma_hash.c.o)
duplicate symbol _hash_free in:
    /Users/DE213022/progs/src/xbmc/build/build/cpluff/lib/libcpluff.a(hash.o)
    /Users/Shared/xbmc-depends/macosx10.13_x86_64-target-debug/lib/mariadb/libmariadbclient.a(ma_hash.c.o)
duplicate symbol _list_delete in:
    /Users/DE213022/progs/src/xbmc/build/build/cpluff/lib/libcpluff.a(list.o)
    /Users/Shared/xbmc-depends/macosx10.13_x86_64-target-debug/lib/mariadb/libmariadbclient.a(ma_list.c.o)
ld: 4 duplicate symbols for architecture x86_64
```

**Comment by Rechi** [comment]
force a rebuild of libcpluff
https://github.com/xbmc/xbmc/blob/02ae31b0b7ebb85bd4e7d01ff1608a33a664d3ae/lib/cpluff/libcpluff/Makefile.am#L13-L14

**Comment by FernetMenta** [comment]
worked, thanks
shouldn't this be triggered automatically?

**Comment by Rechi** [comment]
No as the files at lib/cpluff are not added as dependency to the cmake libcpluff target.

**Pull request merged**
