### PR TITLE
[Fix][subs] Don't try to read a vob sub file without a corresponding …

### PR DESCRIPTION
**Pull request by ace20022**
…idx file.

@anssih  @Voyager1 for review. 

Edit: fixes the issue described there: http://forum.kodi.tv/showthread.php?tid=227734

### CODE REVIEW

**Comment by mkortstiege** [comment]
Makes sense. Thanks.

**Comment by ace20022** [comment]
Will merge it tomorrow if there are no objections till then.

jenkins build this please

**Comment by Voyager1** [comment]
makes complete sense to me as well... +1

**Comment by petriposio** [comment]
This PR seems to break MicroDVD subtitles since they use .sub filename extension too.

Revert and try to find a better way to fix the mentioned issue?

**Comment by ace20022** [comment]
My first attempt was to check the header: https://github.com/ace20022/xbmc/commit/a08aad4d75da6dabbe1363b1b30b9c211fc98544

@mkortstiege @Voyager1 @anssih thoughts?

**Comment by Voyager1** [comment]
haven't checked in great detail, but it doesn't seem right. What problem are we trying to solve? If the MicroDVD subtitles need to be read, is the header then also the same? And how is this code preventing a sub file to be read without the idx file being there?

**Comment by arnova** [comment]
@Voyager1 : I think his fix is valid. The .sub that comes with an .idx is binary, a standalone .sub is text, that's what he's trying to distinguish here.

**Comment by ace20022** [comment]
Exactly, the problem showed up because kodi needs a really long time to read a 300mb sub file which it can't use afterwards.

**Comment by Voyager1** [comment]
So, checking my understanding: originally the code checked for an idx file, and if that existed, it would add the sub file. Apparently there was an issue (don't know what) so you 'fixed' that by adding the else clause returning -1 (which is now reverted). The 'new' fix is to check the header of the sub file, that it is a genuine vobsub. I think that is certainly a good thing to have, but I still fail to see how the new change replaces the other... It seems like you want to avoid the "opposite", i.e. an invalid sub that has an existing idx, as opposed to the original issue which was about a missing idx... Please enlighten me.

**Comment by ace20022** [comment]
> Apparently there was an issue (don't know what) so you 'fixed' that by adding the else clause returning -1 (which is now reverted).

I have linked the forum post and I described the problem here.

I could be wrong, but again:
A vob sub is useless without a idx file. Therefore it makes no sense to treat it like a text sub and read it completely into a string and do conversions just to throw it away afterwards.

A MicroDVD sub also has the extension ".sub" but no idx file. But it is a text file that can be handled.

**Comment by Voyager1** [comment]
I think I finally got it - I didn't see the recursion within DVDPlayer::AddSubtitleFile. Assuming that CDVDSubtitleStream is for text-base (like srt, MicroDVD sub) I think the new fix is correct!

**Pull request merged**
