### PR TITLE
[cmake] FindGtest.cmake: properly support debug and release builds

### PR DESCRIPTION
**Pull request by Montellese**
## Description
This fixes linking `kodi-test` for debug builds on Windows. Since the extraction of gtest it was broken.

## How Has This Been Tested?
Manually on my Windows 10 dev machine.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by Montellese** [comment]
How do we find / use gtest on non-depends builds (FreeBSD and Linux)? Maybe @wsnipex knows? Because those fail now due to https://github.com/xbmc/xbmc/pull/17956/files#diff-25d0c391bec193a0e7eefc757785f531R48.

**Comment by wsnipex** [comment]
it works just like with every other lib, we use what is available on the system.
The Jenkins build errors are not due to this though, since they are depends builds.

**Comment by wsnipex** [comment]
I just checked gtest on ubuntu 20.04 and there is no gtestConfig.cmake, only pkg-config files

**Comment by Montellese** [comment]
> I just checked gtest on ubuntu 20.04 and there is no gtestConfig.cmake, only pkg-config files

Ah ok so I'll remove the `find_package()` line again since it wasn't there before either.

**Review by Paxxi — APPROVED** [review]
Tested and builds fine and tests run on both Debug and RelWithDebInfo

**Pull request merged**
