### PR TITLE
json-rpc: fix playing URLs with options

### PR DESCRIPTION
**Pull request by FernetMenta**
fix https://trac.kodi.tv/ticket/17914

If item was already played and stored in DB (without options), JSON-RPC created a playlist with 2 items. First without options, 2nd with options. This behaviour does not make much sense. 
Now full url is added as dynPath.

### CODE REVIEW

**Comment by FernetMenta** [comment]
IMO this entire fileItem logic is JSON-RPC should go away. JSON-RPC is an interface and should not do any magic to the passed parameters

**Comment by DaveTBlake** [comment]
Thanks for this @FernetMenta. Sorry for failing to spot the issue was inside the JSON call not the player, it is an unexpected place for it.

Small thing, but as this fixes an internal JSON issue could you also do a patch bump to the API version https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/version.txt
to 9.4.1

**Comment by DaveTBlake** [comment]
PR raised to do the version bump https://github.com/FernetMenta/xbmc/pull/477
No idea if that is what you meant, or how it gets to join this PR, but a right faff anyway

**Comment by FernetMenta** [comment]
> or how it gets to join this PR

it joins at the moment it is merged to the branch

**Pull request merged**
