### PR TITLE
[skin] Remove estouchy from core

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Remove unmaintained skin from default packaging.

## Motivation and context
There have been a number of changes to skins, and estouchy has not been kept up to date. At this point no one has shown interest to update it, so remove it for now.

PRing now in case any interested parties wish to step up and create all the new dialogs/etc for estouchy, or for anyone to spot anything further that needs to be removed.

## How has this been tested?
N/A

## What is the effect on users?
Estouchy will no longer be available from default install

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [x] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by enen92 — APPROVED** [review]
Honestly, I am quite glad to see it going. Estouchy has been a pain in the ass for any skinning changes as we have to made them to estuary and also to estouchy.

**Review by jjd-uk — APPROVED** [review]
While I'm happy to help out in keeping Estuary updated, I have zero interest in doing anything to maintain Estouchy

I will extract out the code for Estouchy then push it to my repo, then if this is merged the ownership of that can be transferred to the xbmc org, so code is there if anyone wants to resurrect it to the skins repo as an installable skin.

**Comment by sarbes** [comment]
RIP.

Do we have an repository where it is archived? It would be useful just for keeping the textures. And who knows, maybe someone wants to resurrect it one day.

**Comment by Hitcher** [comment]
Just tested this by selecting Estouchy, exiting Kodi, installing this build, starting Kodi. As expected it switching to using Estuary.

**Comment by jjd-uk** [comment]
Code separated to https://github.com/jjd-uk/skin.estouchy will request it be moved to the xbmc organisation once this merged.

**Comment by fuzzard** [comment]
Jenkins build and merge

**Comment by christianhaitian** [comment]
I just built Kodi 21.0 and upon completion of the build, when I attempted to start Kodi, I kept getting an error that the Kodi application failed to be created.  Upon checking the kodi.log file, it kept exiting because skin.estouchy was not available.  Once I went to the repo and copied the last version of estouch to the appropriate folder, Kodi started right up.  I didn't have skin.estouchy as the default skin either.  Any ideas why this would have occurred?  I even tried deleting the profile.xml file first and it still didn't resolve the issue.

**Comment by garbear** [comment]
Kodi can fail to start if skin.estouchy is missing but still specified in addon-manifest.xml: https://github.com/xbmc/xbmc/blob/master/system/addon-manifest.xml

However, you can see in the file's history that the line was removed.

Can you check your local addon-manifest.xml to see if the skin is still there?

**Comment by christianhaitian** [comment]
Ahh, it indeed was still specified in that file.  Thank you for that tip.

**Pull request merged**
