### PR TITLE
VideoPlayer: fix seeking while paused

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by axbmcuser** [comment]
Maybe related to this PR: Just noticed that latest nightly build (tested both Windows and Linux/LibreELEC test systems) show the following pause-behaviour:

- Playing 1080p mkv h264 content
- Pause video 
- (Seekbar doesn't show "PAUSED" as it did before, but often "SEEKING" - also it's clearly paused)
- Resume playing via Play-Button
- Seekbar shows "REWIND" indicator and text for very few milliseconds
- Video continues playing after that

Do you need a debug log with or without ffmpeg-logging?

**Comment by FernetMenta** [comment]
This is a skin issue. @HitcherUK @ronie @phil65 

```
	<variable name="SeekLabel">
		<value condition="[Player.Paused + !Player.Caching] + !Player.Seeking + !Player.DisplayAfterSeek">$LOCALIZE[112]</value>
		<value condition="!String.IsEmpty(Player.SeekStepSize) + ![player.forwarding | player.rewinding]">$LOCALIZE[773][COLOR=grey] $INFO[Player.SeekStepSize][/COLOR]</value>
		<value condition="Player.DisplayAfterSeek + ![player.forwarding | player.rewinding]">$LOCALIZE[773][COLOR=grey] $INFO[Player.SeekOffset][/COLOR]</value>
		<value condition="!Player.DisplayAfterSeek + Player.Seeking">$LOCALIZE[773]</value>
		<value condition="Player.Forwarding">$LOCALIZE[31039] $VAR[VideoPlayerForwardRewindVar]</value>
		<value condition="Player.Rewinding">$LOCALIZE[31038] $VAR[VideoPlayerForwardRewindVar]</value>
	</variable>
```

DisplayAfterSeek must not alter SeekLabel. DisplayAfterSeek controls if the SeekBar should be shown or not.

**Comment by axbmcuser** [comment]
Thanks for clarifying.

Is it correct then, that after resuming a paused video, "Player.Rewinding" seems to be "true" for some milliseconds? This results in the _visual_ rewinding-indicator being shown for a small amount of time after a pause-resume situation. (Not all skins use such a indicator, but some do and they now of course show this usability-wise irritating behaviour)

**Comment by FernetMenta** [comment]
> "Player.Rewinding" seems to be "true" for some milliseconds?

I can't reproduce. I set a breakpoint on this condition and Rewinding never got true.

**Comment by axbmcuser** [comment]
Can be reproduced with Confluence or any other skin containing a image-control like:
`[...]
<texture>OSDSeekRewind.png</texture>
<visible>Player.Rewinding</visible>
[...]`
Tested with http://mirrors.kodi.tv/nightlies/win32/KodiSetup-20160714-aa0f7ea-master.exe
Pause common 1080p h264 mkv content for some seconds, resume playback, indicator is shown for a moment.

**Comment by ronie** [comment]
proposed fix for estuary: https://github.com/xbmc/skin.estuary/pull/171/commits/bf502666615b7fd4dc3f72d17665c7dc86317345

i can confirm the issue with Player.Rewinding returning true after un-pausing a video.

**Comment by axbmcuser** [comment]
I think
https://github.com/xbmc/xbmc/pull/10115
tries to fix the "Player.Rewinding true after resume" problem.

I just tried it and it seems work - thanks - however now another irritating behaviour got introduced with PR 10115:
-Playing common 1080p h264 mkv content
- Pause video 
- Seekbar shows, but with a delay of about 1,5 seconds - which feels very wrong regarding usability. This strange delay hasn't been there before. I suspect after hitting the Pause button "Player.Paused" is not instantly set to true, but with such a delay.

**Comment by axbmcuser** [comment]
@ronie 
- Can you confirm the issue i described?
- ...and please point me to the proposed estuary change. (url doesn't work (yet)?) Thanks!

**Comment by ronie** [comment]
i haven't tested PR10115 so can't confirm.

the Estuary changes are just cosmetic stuff, removing Player.DisplayAfterSeek from the visible conditions.

**Comment by axbmcuser** [comment]
Allright. PR10115 got merged in the meantime - did a clean compile. Looks like the described delayed showing of the seekbar seems to be gone. Great.

**Pull request merged**
