### PR TITLE
VideoPlayer: flush renderManager when hiding video

### PR DESCRIPTION
**Pull request by FernetMenta**
makes sure we have free buffers when video starts

### CODE REVIEW

**Comment by Rechi** [comment]
@FernetMenta with latest changes it fixes https://trac.kodi.tv/ticket/17862

**Comment by FernetMenta** [comment]
cool. I triggered a testbuild and wanted smp1 to test but seems obsolted now. thanks!

**Comment by FernetMenta** [comment]
build errors unrelated

**Comment by MilhouseVH** [comment]
Nvidia loses video when seeking - playback continues with audio and a black screen (GUI is visible).

After the final seek, video is lost: http://ix.io/19xR

**Comment by FernetMenta** [comment]
not related to this change but a couple of other vdpau bugs that need to be fixed.

**Comment by FernetMenta** [comment]
probably. first vdpau needs same fix as vaapi for videopictue: https://github.com/xbmc/xbmc/pull/13693

**Pull request merged**
