### PR TITLE
[rbp] Disable fast_memcpy which is slower than memcpy

### PR DESCRIPTION
**Pull request by popcornmix**
[utils] Disable fast_memcpy which is slower than memcpy

The default glibc memcpy is likely to be better tuned than this code
which hasn't been touched for four years.

In a test with software video decode on Pi2 the skipped frames went
from 189 to 172 when fast_memcpy was disabled.

### CODE REVIEW

**Comment by popcornmix** [comment]
jenkins build this please

**Comment by fritsch** [comment]
@popcornmix what will happen for users that build on "normal" distribution arch, debian whatever? How much slower is the default memcpy vs the fast memcpy?

Btw. when I looked last time, fast memcpy was just fowarded to normal memcpy - at least in ffmpeg.

**Comment by FernetMenta** [comment]
this function should be removed completely. originally it was borrowed from MPlayer but is long obsolete. if I am not mistaken it was kicked out from ffmpeg too.

**Comment by fritsch** [comment]
Yes, exactly.

**Comment by popcornmix** [comment]
Raspbian, OpenELEC and OSMC all preload this library: https://github.com/bavison/arm-mem
I suspect Arch and other do too (or could easily as it will improve the performance of other memcpy calls).

With software decode all decoded pictures get a "fast_memcpy". For 1080p24 that is 75MB/s of memcpy bandwidth which is significant. See: [here](https://github.com/xbmc/xbmc/blob/master/xbmc/cores/dvdplayer/DVDCodecs/DVDCodecUtils.cpp#L126).

If there really exists a generic arm memcpy routine that is better than the one in glibc, you'd imagine glibc would include it. Feels wrong for every app to provide their own efficient memcpy routine...

**Comment by popcornmix** [comment]
So remove for all platforms? (I believe that is the best solution).

**Comment by fritsch** [comment]
@popcornmix yes, please.

**Comment by popcornmix** [comment]
Okay removed for all platforms. jenkins build this please

**Comment by popcornmix** [comment]
Removed from xcode and VS projects. jenkins build this please

**Comment by popcornmix** [comment]
Rpi failure to build addons looks unrelated to PR.

**Comment by MartijnKaijser** [comment]
is this something you guys think should be in 15.0 ?
jenkins build this please (hope i fixed the builder)

**Comment by fritsch** [comment]
As this code was removed from ffmpeg, and those guys know what they are doing, I think the "usual" memcpy algorithms provided by kernel / libc have improved that much, that we don't need it anymore.

@FernetMenta what's your say on this? Normally we would need to benchmark this, copying small chunks, large chunks and so on.

**Comment by MartijnKaijser** [comment]
should we merge this for 15.0 or delay? @FernetMenta

**Comment by FernetMenta** [comment]
at least on RPi it is an improvement. I consider the risk that anything breaks low.

**Pull request merged**
