### PR TITLE
[PVR] Fix empty videoplayer.plot infolabel when playing recorded TV and add …

### PR DESCRIPTION
**Pull request by joethepartylion**
…new videoplayer.recordeddate label.

This something that has been asked about on the forums (http://forum.kodi.tv/archive/index.php?thread-219946.html) and by me so I have tried to see if I could code it myself. I have no prior C++ experience so it may be a load of codswallop but here goes (hopefully I've done it right this time not like #7737)

### CODE REVIEW

**Comment by mkortstiege** [comment]
@xhaggi mind checking?

**Comment by xhaggi** [comment]
makes sense but we need to take care of other pvr related info like genre etc.

**Comment by xhaggi** [comment]
I did only a quick look at this. I'm off for vacation until 14th of September. @ksoo mind taking a look too?

**Comment by joethepartylion** [comment]
I'm happy to update the commit with the additional fields if someone can point me to what fields are available from GetPVRRecordingInfoTag as I don't know how to work this out myself. I just took those used in the mypvrrecordings.xml window.

**Comment by ksooo** [comment]
May I suggest not to mix up different things in one PR. The original request in the forum was to fix a bug with "Videoplayer.Plot". The other stuff in this PR is new functionality. I'd like to see two different PRs here - one for the fix, one for the functional enhancements.

Rational: The fix for "VideoPlayer.Plot" is already implemented right imo, straight forward and can be merged in almost no time. The enhancements need a bit more 'love'. I'm not sure why you picked just some of the CPVRRecording data fields and not all, for instance. Escpecially I would be glad to see a concrete PR that actually uses the enhancemants. Otherwise I fear to extend guiinfo more and more with stuff that nobody uses at the end.

**Comment by joethepartylion** [comment]
Yes I thought that after i submitted it, sorry. @ksooo, I can submit just the "VideoPlayer.Plot" separately, Do you want me to remove all the other data fields i.e. plotoutline, title etc or just the new recordeddate one?

The reason I haven't covered all of the data fields is that I don't know where to find what is available as I don't have a lot of programming experience, I was just copying the ones referenced in the PVRRecording window list to get started. If you can give me any points in the right direction then i will have a go at it.

**Comment by ksooo** [comment]
> I can submit just the "VideoPlayer.Plot" separately, 

 Cool.

> Do you want me to remove all the other data fields i.e. plotoutline, title etc or just the new recordeddate one?

 Yes, please leave just the fix for VideoPlayer.Plot in this PR, create a new PR for all the rest (the functional enhancements), please.

**Comment by joethepartylion** [comment]
Hi @ksooo, I've updated the commits but can't squash them until i get home, once I've done that I will let you know.

**Comment by joethepartylion** [comment]
OK, looks like I've completely messed up the commits and not sure how to get it back, will close this pull request and try again. 3rd time luck, at least I'm understanding git a bit more now :-)

**Pull request closed without merging**
