### PR TITLE
[binary addons] bump audio encoders

### PR DESCRIPTION
**Pull request by wsnipex**

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build addons please

**Comment by uNiversaI** [comment]
build log for audioecoders http://pastebin.com/raw.php?i=8B1auBA6

flac is failing with ***fatal error***

Rest seem to be ok.

**Comment by wsnipex** [comment]
thats cause it finds and uses your system flac:
Found FLAC: /usr/include/FLAC;/usr/include

**Comment by uNiversaI** [comment]
apt-cache policy libflac-dev
libflac-dev:
  Installed: (none)
  Candidate: 1.3.0-2ubuntu0.14.04.1

**Comment by wsnipex** [comment]
ls -l /usr/include/FLAC

works fine for me btw.

**Comment by uNiversaI** [comment]
ls -l /usr/include/FLAC
ls: cannot access /usr/include/FLAC: No such file or directory

**Comment by wsnipex** [comment]
hmz...
/usr/bin/pkg-config --cflags --libs flac

**Comment by uNiversaI** [comment]
kodi@mimc:/home/setup$ /usr/bin/pkg-config --cflags --libs flac
-I/usr/include/FLAC  -lFLAC -lm

**Comment by wsnipex** [comment]
there you have it. Fix your packages...

**Comment by uNiversaI** [comment]
ls /usr/lib/pkgconfig/
cwiid.pc  libcdio.pc     libmodplug.pc  ogg.pc       vorbisenc.pc   vorbis.pc   xorg-wacom.pc
flac.pc   libiso9660.pc  libnfs.pc      platform.pc  vorbisfile.pc  xkbcomp.pc

No idea how they got inthere, never had this before.

**Pull request merged**
