### PR TITLE
[addons] improve performance of GetAvailableUpdates

### PR DESCRIPTION
**Pull request by tamland**
Should reduce the number of db queries executed when checking for available updates. @MilhouseVH please test.

### CODE REVIEW

**Comment by tamland** [comment]
jenkins build this please

**Comment by stefansaraev** [comment]
thanks

21:07:41 T:3069571632   DEBUG: CAddonMgr::GetAvailableUpdates took 20 ms

it is instant here now. I dont have exact numbers before this PR. but it was like 2-3 seconds with kodi repo + my own repo with ~ 20 addons

**Comment by MilhouseVH** [comment]
Excellent, very quick now!

On the RPi1 system:

Entering `Add-ons` the first time:
```
00:15:44 1416.762817 T:1963598720   DEBUG: CAddonMgr::GetAvailableUpdates took 390 ms
00:15:45 1417.195801 T:1963598720   DEBUG: CAddonMgr::GetAvailableUpdates took 395 ms
00:15:45 1417.639893 T:1963598720   DEBUG: CAddonMgr::GetAvailableUpdates took 411 ms
```

Entering `Install from repository` > `All repositories`:
```
00:16:20 1452.407593 T:1742730144   DEBUG: CAddonDatabase::GetAddons took 4337 ms
```

Back to `Add-ons`:
```
00:16:41 1473.477539 T:1963598720   DEBUG: CAddonMgr::GetAvailableUpdates took 393 ms
```

Entering `Available Updates`:
```
00:16:55 1487.889893 T:1761362848   DEBUG: CAddonMgr::GetAvailableUpdates took 406 ms
00:16:56 1488.428467 T:1761362848   DEBUG: CAddonMgr::GetAvailableUpdates took 536 ms
```

So a very significant improvement - many thanks.

**Comment by tamland** [comment]
jenkins build this please

**Comment by tamland** [comment]
Thanks for testing!

**Pull request merged**
