### PR TITLE
[FontTTF] Fixed a blurry font  which is happening sometimes in some cases.

### PR DESCRIPTION
**Pull request by afedchin**
see title

The caching font data mechanics allows have vertices with negative X coordinate. Here is an example of real vertices data for the same character:

**Char is not blurry**:

```
#float3(x,y,z),float4(r,g,b,a),float2(tu,tv)
"{+72, +124, +0}","{+0.89803928, +0.89803928, +0.89803928, +1}","{+0.13085938, +0.30000001}"
"{+77, +124, +0}","{+0.89803928, +0.89803928, +0.89803928, +1}","{+0.13574219, +0.30000001}"
"{+77, +138, +0}","{+0.89803928, +0.89803928, +0.89803928, +1}","{+0.13574219, +0.76666671}"
"{+72, +138, +0}","{+0.89803928, +0.89803928, +0.89803928, +1}","{+0.13085938, +0.76666671}"
```

**Char is blurry**:

```
#float3(x,y,z),float4(r,g,b,a),float2(tu,tv)
"{-159, +124, +0}","{+0.89803928, +0.89803928, +0.89803928, +1}","{+0.13085938, +0.30000001}"
"{-153, +124, +0}","{+0.89803928, +0.89803928, +0.89803928, +1}","{+0.13574219, +0.30000001}"
"{-153, +138, +0}","{+0.89803928, +0.89803928, +0.89803928, +1}","{+0.13574219, +0.76666671}"
"{-159, +138, +0}","{+0.89803928, +0.89803928, +0.89803928, +1}","{+0.13085938, +0.76666671}"
```

As can you see if vertex data has negative value of X coordinate the dimension of char is greater at 1 pixel - 6x14 instead of 5x14.

It would be helpful if some one can test this on linux

### CODE REVIEW

**Comment by mkortstiege** [comment]
Runtime tested on Linux without an issue.

**Comment by MartijnKaijser** [comment]
no problems so far on win32

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
can we merge this?

**Comment by afedchin** [comment]
@MartijnKaijser I think so. should the first commit be backported?

**Comment by MartijnKaijser** [comment]
don't know. Not sure if i've seen it on 15.x as well.

**Pull request merged**
