### PR TITLE
[clang-tidy] apply and enable performance-* checks

### PR DESCRIPTION
**Pull request by Rechi**
## Description
apply and enable performance-* (except performance-inefficient-string-concatenation) clang-tidy checks

## How Has This Been Tested?
run clang-tidy and compiled for Android (aarch64), iOS, Linux (gl and gles), macOS and tvOS

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Review by garbear — APPROVED** [review]
All 10 tidy commits look good. I learned:

* performance-inefficient-algorithm - std::find is O(N) lookup on std::sets (I assumed logN), because unlike std::set::find() it doesn't take advantage of element ordering
* performance-move-const-arg - std::move with a const argument just makes a copy
* performance-noexcept-move-constructor  - I guess it's good to mark all move constructors `noexcept`?

Thanks for the work, I got to learn something.

**Review by DaveTBlake — APPROVED** [review]
Timimg of this broad impact change (with alpha3 release tomorrow) made my heart sink a little at first, but I guess best now than any other time.

**Review by phunkyfish — APPROVED** [review]
Nice, thanks @Rechi

**Review by yol — APPROVED** [review]
Hope clang-tidy knows what it's doing :D seems to work OK :+1:

**Comment by DaveTBlake** [comment]
@ksooo @lrusak any comment?
This would have been best merged at the _beginning_ of an alpha step than just before a release, but better now hours before alpha 3 than even early in Beta. Are we go?

**Review by lrusak — APPROVED** [review]
I thought we weren't doing global clang-tidy changes but I guess this doesn't count? :blush:

**Comment by yol** [comment]
I thought the previous discussions were about clang-format?

**Comment by DaveTBlake** [comment]
> I thought the previous discussions were about clang-format?
Same here.

Ready to merge @Rechi ? If yes then push that button.
I would be very happy for that to happen before the nightly build, and come back to a tiny open PR list ready to tag and release tomorrow :)

**Comment by CvH** [comment]
@Rechi compiling kodi with that pr results in a not starting kodi at LE
not sure what happens - likely it kills some update mechanism (can't see something at the logs)?
a empty profile just works fine, my recent one (using since ~X13) results in a crashing kodi
http://ix.io/2CAr

going back to `0039f432ed09cbfc146f10f818cdcb5745c42fc4` and everything works again

**Comment by DaveTBlake** [comment]
@CvH we are also investigting cashing on OSX with ba15b9fcc3  [clang-tidy] performance-unnecessary-value-param the first problem commit. 
Yet Win64, Androd and x11 (Ubuntu20.04) behaving OK.

**Comment by phunkyfish** [comment]
@CvH can you test with `xbmc/interfaces/legacy/Monitor.h` and `xbmc/interfaces/python/PythonSwig.cpp.template` reverted from https://github.com/xbmc/xbmc/commit/ba15b9fcc30f5921cd469a5cf2662fa5eb3b08bc?

**Pull request merged**
