### PR TITLE
[depends] update libtool to 2.4.6

### PR DESCRIPTION
**Pull request by mrdominuzq**
libtool now has android support http://git.savannah.gnu.org/cgit/libtool.git/commit/?id=8eeeb00daef8c4f720c9b79a0cdb89225d9909b6 
and this should be a step closer to get rid of rpl method
currently breaks libmodplug - mysql - libshairplay - libbluray - libnfs
only tested on android i686

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by mrdominuzq** [comment]
do you want it squashed :)?

**Comment by MrMC** [comment]
this PR is required if using Xcode 7.3+, your 1st hint is target/sqlite will fail to autoreconf.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
I wonder how this should work, given that nobody uploaded the new version to our mirrors....

**Comment by FernetMenta** [comment]
I requested the upload on slack

**Comment by wsnipex** [comment]
well, its not there and therefore this PR was never tested.

**Comment by FernetMenta** [comment]
I have tested it on OSX Xcode 7.3 that requires it

**Comment by Memphiz** [comment]
i would have been abel to upload it right now but someone beat me by 45 minutes ;)

**Comment by MrMC** [comment]
missed a few 'compile fixes', search this repo for READELF and you will find them

**Pull request merged**
