### PR TITLE
ADD: [droid] surface rendering mediacodec

### PR DESCRIPTION
**Pull request by koying**
This creates a virtual codec from mediacodec, where only the rendering path changes.
The "Surface" way implement zero-copy, hw codec to android surface rendering.

Besides the fact that it's the android "by-the-book" way, it also enables 4K video playing on 720p/1080p framebuffer, composition being left to the FW.
This should also work on all FW's, ideally, as the FW is completely in charge from decoding to rendering.

At the same time, this also de-activate libstagefright.

Initially, I planned to implement this in videoplayer only, but I'd rather have a smoother transition in 16, rather than a big-bang in 17. Furthermore, more 4K devices (TV's, AFTV2) are coming, and waiting till 17 will make us quite behind.

@FernetMenta Hope you don't mind. I've limited the impact to the maximum (no cleanup whatsoever) to limit the rebasing issues on videplayer. If you still have some, I suggest to plainly revert 76c4415 in your branch, and I'll re-implement in videoplayer.

@MartijnKaijser Hope it's not too late for 16?

### CODE REVIEW

**Comment by FernetMenta** [comment]
ok, recently git showed that it is quite clever on renamed files. should not result in too much pain.

**Comment by MartijnKaijser** [comment]
If @FernetMenta is OK with it I'm OK with it. 
Although it looks more like a feature it fixes something that has been biting us for a while on android. Should be merged as soon as we can

**Comment by koying** [comment]
jenkins build this please

**Comment by koying** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
Build errors are only for Addons

**Comment by koying** [comment]
Yep. Just noticed an issue with 3d (same as imx) that I'll fixup tomorrow.

Le jeu. 22 oct. 2015 21:08, Martijn Kaijser <notifications@github.com> a
écrit :

**Pull request merged**
