### PR TITLE
[cmake] add URL_HASH for external projects to avoid redownloading

### PR DESCRIPTION
**Pull request by lrusak**
This allow cmake to skip downloading an external project file if it already is downloaded and matches the specific sha256 hash.

```
[  8%] Performing download step (download, verify and extract) for 'ffmpeg'
-- verifying file...
       file='/home/lukas/Documents/git/xbmc/build/build/download/ffmpeg-4.2.2-Matrix-Alpha1.tar.gz'
-- File already exists and hash match (skip download):
  file='/home/lukas/Documents/git/xbmc/build/build/download/ffmpeg-4.2.2-Matrix-Alpha1.tar.gz'
  SHA256='0dba571f9809588cfbdc29d6a551dab4cd5736701653d9263847c9ac67bcde86'
```

This will only occur if you don't blow out your entire build dir though. we could look at changing the download dir to be outside the build dir in the future (like how it is with the full depends build)

### CODE REVIEW

**Review by Rechi — CHANGES_REQUESTED** [review]
Having download path (used version of the library) and the hash of the tarball at different locations is wrong.

**Comment by lrusak** [comment]
> Having download path (used version of the library) and the hash of the tarball at different locations is wrong.

@Rechi I actually have no idea what you mean. Please clarify.

**Comment by AlwinEsch** [comment]
Think he means to have defined in here https://github.com/xbmc/xbmc/pull/17510/files#diff-6035b19674eae93e45554bd0a69ded21R10-R14 to have URL and SHA256 together, it would also have to be overridden if the user declared one.

```cmake
  if(CROSSGUID_URL)
    get_filename_component(CROSSGUID_URL "${CROSSGUID_URL}" ABSOLUTE)
  else()
    set(CROSSGUID_URL http://mirrors.kodi.tv/build-deps/sources/crossguid-${CGUID_VER}.tar.gz)
    set(CROSSGUID_SHA256 3d77d09a5df0de510aeeb940df4cb534787ddff3bb1828779753f5dfa1229d10)
  endif()
...
  externalproject_add(crossguid
                      URL ${CROSSGUID_URL}
                      URL_HASH SHA256=${CROSSGUID_SHA256}
```
or if with empty `CROSSGUID_SHA256` not work:
```cmake
  if(CROSSGUID_URL)
    get_filename_component(CROSSGUID_URL "${CROSSGUID_URL}" ABSOLUTE)
  else()
    set(CROSSGUID_URL http://mirrors.kodi.tv/build-deps/sources/crossguid-${CGUID_VER}.tar.gz)
    set(CROSSGUID_SHA256 "URL_HASH SHA256=3d77d09a5df0de510aeeb940df4cb534787ddff3bb1828779753f5dfa1229d10")
  endif()
...
  externalproject_add(crossguid
                      URL ${CROSSGUID_URL}
                      ${CROSSGUID_SHA256}
```

> Both not tested from me, only just thought like that

**Comment by AlwinEsch** [comment]
Maybe even there https://github.com/xbmc/xbmc/blob/master/tools/depends/target/crossguid/Makefile#L7 because the version is declared there. There is no way of knowing exactly what he really means.

But this brings back how valuable it would be at GSOC to do this **"Replacing depends with a CMake-based system"** (https://kodi.wiki/view/Google_Summer_of_Code/2020).

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by Rechi** [comment]
This is already better, because the hash is stored in the same file as the version. But depends have to check for the hash too otherwise one might still forget to update the hash, as depends are still building fine.

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
> This is already better, because the hash is stored in the same file as the version. But depends have to check for the hash too otherwise one might still forget to update the hash, as depends are still building fine.

outside the scope of this PR

**Review by wsnipex — CHANGES_REQUESTED** [review]
Depends need to check the hash as well

**Comment by lrusak** [comment]
> Depends need to check the hash as well

can you do it please?

**Comment by lrusak** [comment]
> > Depends need to check the hash as well
> 
> can you do it please?

@wsnipex is that a no?

**Comment by wsnipex** [comment]
no, not a no. @fuzzard  has already worked on it, but we are both swamped with real work atm.
Patience please.

**Comment by fuzzard** [comment]
https://github.com/fuzzard/xbmc/commits/cmake-url-hash

if you want to eyeball what i came up with, with the help of @wsnipex 
Separate commits for each dependency you have added a sha256 for. Other depends can be added/updated as they are

**Pull request closed without merging**
