### PR TITLE
[pvr/videoplayer] fix commercial skip (EDL's) from recordings and library…

### PR DESCRIPTION
**Pull request by phunkyfish**
… sources

## Description

Backport of fix for commercial skips orginally raised in Kodi 18.4 released.

Currently WIP to allow testing.

## Motivation and Context

Backport of: https://github.com/xbmc/xbmc/pull/16584 that resolves https://github.com/xbmc/xbmc/issues/16564

## How Has This Been Tested?

On OSX, on latest Kodi Leia.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by phunkyfish** [comment]
@emveepee you can use this to test on Leia.

**Comment by phunkyfish** [comment]
So EDL or Comskip files that use time or include framerate for TS files should work. Those that do not should error. That will be expected behaviour if you want to test on nextpvr.

**Comment by emveepee** [comment]
I can only test time based

> 
> 
> So EDL or Comskip files that use time or include framerate for TS files should work. Those that do not should error. That will be expected behaviour if you want to test on nextpvr.

NextPVR only uses time-based EDL.  I tested the PR with EDL and Comskip and it worked ok.  I don't have any framerate based EDL files, however it looks like this PR just logs an error rather then working as it should in 18.3 (going back to xbmc)

**Comment by phunkyfish** [comment]
Yes, that’s expected. So using frame numbers with TS EDL files should no longer work. The theory is this is no longer a required use case.

**Comment by phunkyfish** [comment]
Thanks for testing.

**Comment by emveepee** [comment]
O

> 
> 
> Yes, that’s expected. So using frame numbers with TS EDL files should no longer work. The theory is this is no longer a required use case.

Ok I thought the comment was the old comskip txt file with no framerate in the header was obsolete.  I don't know of anyone using framerate style EDL either so I can't comment on that.

**Comment by phunkyfish** [comment]
Both the old comskip file with no frame rate and an EDL using frame numbers. Both require a frame rate for the TS file to work.

**Comment by phunkyfish** [comment]
@ksooo would you care to review as it's kinda PVR related?

Code is identical to Matrix PR.

**Comment by ksooo** [comment]
VideoPlayer is really not my plyground. If you got approval from @FernetMenta for the Matrix PR and if this PR is code-wise identical to that PR, go ahead and merge, I'd say.

**Comment by phunkyfish** [comment]
Cool

**Pull request merged**
