### PR TITLE
[tools/codesign][iOS/tvOS] Fix black screen for iPadOS 14 jailbroken iPads

### PR DESCRIPTION
**Pull request by sy6sy2**
## Description

It seems that PR #18785 fixed the black screen issue only for iOS 14 jailbroken iPhone users but not for iPadOS 14 jailbroken iPad users.
Unfortunately I haven't a jailbroken iPad to try the PR #18785 before submit it so I wasn't able to notice this issue...

As you can see in https://forum.kodi.tv/showthread.php?tid=358449 and https://forum.kodi.tv/showthread.php?tid=357282 threads jailbroken iPad Kodi users noticed the issue and they was able to help me finding the correct fix for us!

Thank you to Huuduc1kk2 and pixelrogue for the tests you did! 

## Motivation and Context

Fix black screen issue for jailbroken iPadOS 14 users.

## How Has This Been Tested?

* Jailbroken Apple TV 4K on tvOS 13 (sy6sy2): Ok with Jenkins artifact
* Jailbroken iPhone 7 on iOS 14.2 (sy6sy2): Ok with Jenkins artifact
* Non-jailbroken iPhone 7 on iOS 14.2, install by sideload with self-signing cert (sy6sy2): Ok with Jenkins artifact
* Jailbroken iPad Mini 4 on iPadOS 14.2 (pixelrogue): Ok with Kodi 18.9 and this commit
* Jailbroken iPad air 2 WiFi on iPadOS 14.2 (Huuduc1kk2): Ok with Kodi 18.9 and this commit

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by sy6sy2** [comment]
WIN-64 failed, not related I guess.

**Comment by sy6sy2** [comment]
Jenkins build this please

**Comment by DaveTBlake** [comment]
@fuzzard @kambala-decapitator happy with this?

**Review by kambala-decapitator — APPROVED** [review]
@DaveTBlake yep

**Review by fuzzard — APPROVED** [review]
If it works, all good

**Pull request merged**
