### PR TITLE
Remove lib/enca/

### PR DESCRIPTION
**Pull request by bkuhls**
Second try ( https://github.com/xbmc/xbmc/pull/6784 ) to remove lib/enca/, let´s test whether
project/VS2010Express/XBMC for Windows.sln really needs libenca ;)

Forum thread for discussion
http://forum.kodi.tv/showthread.php?tid=221837

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by Montellese** [comment]
Just tested deleting the libecna VS project from our VS solution and it still compiled fine.

**Comment by Paxxi** [comment]
I didn't find any references to enca.h in our code files so we seem to have built this and not used it all this time :)

**Comment by wsoltys** [comment]
We used it for building libass intree: https://github.com/xbmc/xbmc/blob/9b3ff6654e94394a4a5ddef356e6ffbdb63548d6/lib/libass/xbmc/libass_win32/config.h#L10

**Comment by MartijnKaijser** [comment]
So it's obsolete as we don't build in tree anymore for windows?

**Comment by wsoltys** [comment]
yes

**Comment by Montellese** [comment]
We still built it but we didn't use it. Someone didn't do a proper cleanup in the past ;-)

**Comment by mkortstiege** [comment]
Nice. Assigning to next merge window.

**Pull request merged**
