### PR TITLE
drop some unneeded ifdefs related to ffmpeg

### PR DESCRIPTION
**Pull request by FernetMenta**
drop some ugly ifdeffery
logging ffmpeg version info is good enough for determining the source.

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by ksooo** [comment]
Didn't we have an agreement only to include fixes for Krypton after beta2?

**Comment by FernetMenta** [comment]
I consider this as a fix :)

**Comment by FernetMenta** [comment]
@ksooo it makes some commit on our ffmpeg fork obsolete. We need to bump our ffmpeg fork again for final.

**Comment by ksooo** [comment]
> I consider this as a fix :)
 
 In this case we should put the "fix" label on it.

**Pull request merged**
