### PR TITLE
Cleanup taglibtagloader a bit and fix null padded tags

### PR DESCRIPTION
**Pull request by Paxxi**
Hide taglib includes from rest of Kodi code and move some helper methods into cpp file

### CODE REVIEW

**Comment by Paxxi** [comment]
@Razzeee @DaveTBlake review, maybe not the cleanest changeset but changes should be good

**Comment by DaveTBlake** [comment]
Thanks @Paxxi, I've been off-line a couple of days and won't be able to check this fully until Friday. It is odd how the null padding issue related to our string handler didn't show up in 15 or 16. Do you understand why that was?

**Comment by Razzeee** [comment]
Can you split the fix from the cleanup - commit wise

**Comment by DaveTBlake** [comment]
As I understand it the fix to nul padded ID3v1 tags problem is the removeal of TagStringHandler, a separate commit would make that clearer. :)

But what I don't understand is why exactly the same TagStringHandler code works in Jarvis. What else changed with 17 that made this an issue? The Taglib guys think our code would have had the same issue with 1.9.1, so the change to 1.10 is not the cause. Was it the VS2015 change? I guess I would need to compile Taglib 1.9.1 in VS2015 to know. @Paxxi do you understand it?

**Comment by Paxxi** [comment]
I'll make a separate commit. No I haven't dug that deep into it but there's not any reason to use our string handling as taglib does conversions itself so I just dropped it

**Comment by DaveTBlake** [comment]
No need to dig @Paxxi I found my explanation and can be at peace. There was a change in taglib 1.10 to the way tstring.cpp String::copyFromUFT8 worked, hence how the nul padding issue appeared.

Good to drop the unnecessary and broken string handling, and thanks for the tidy-up. I will give it a bit more testing tomorrow (managed to break my dev setup).

**Comment by DaveTBlake** [comment]
Thanks for splitting the commits.
The latter fixes the singles (music files with ID3v1 tags and not album title) appearing as albums issue reported in http://trac.kodi.tv/ticket/16454 caused by those nul padded strings.

**Comment by DaveTBlake** [comment]
jenkins build this please

**Comment by DaveTBlake** [comment]
@Paxxi nice crop of errors on all platforms except Win32, care to fix them please.

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by DaveTBlake** [comment]
@Paxxi jenkins finally attempted this build, but still fails on multiple platforms.

**Comment by Paxxi** [comment]
jenkins build this please
I don't think it picked up the changes judging by the errors

**Comment by Paxxi** [comment]
@DaveTBlake there we go, all good

**Comment by DaveTBlake** [comment]
Thanks @Paxxi. Tests fine for me too, do you want to hit the button or shall I?

**Pull request merged**
