### PR TITLE
Fix for font corruption

### PR DESCRIPTION
**Pull request by bavison**
CGUIFontTTFBase::DrawTextInternal iterates along the characters in the string.
For each one, it typically calls CGUIFontTTFBase::GetCharacter to (amongst
other things) locate the rasterised glyph for that character/style combination
(where style means bold/italic) within the GPU texture associated with that
font. If the texture doesn't already contain that glyph, it calls
CGUIFontTTFBase::CacheCharacter to rasterise it and add it to the texture.

The texture is made up of constant-height cells, one per glyph, and once the
texture has filled one row's worth of glyphs it wraps onto the next row; if the
texture isn't tall enough to accommodate another row then it reallocates it.

The problem is that between each CGUIFontTTFBase::GetCharacter call there is a
CGUIFontTTFBase::RenderCharacter which constructs vertices whose u/v
coordinates are the coordinates within the texture, normalised to the range
0..1. So if the texture is enlarged mid-string, then the vertices for the
earlier characters are incorrect.

I believe the reason why this wasn't detected before is that in the absence of
cacheing, the multiple re-plots of the string recalculated everything anyway,
so it was only a transient effect.

### CODE REVIEW

**Comment by arnova** [comment]
Nice find.

**Comment by MilhouseVH** [comment]
I've repeated my [testing](https://github.com/xbmc/xbmc/pull/4143#issuecomment-105855934) with the addition of this PR and it does appear to have resolved the issue - many thanks @bavison.

**Comment by afedchin** [comment]
seems this also fixed RSS font corruption on window resize.

**Comment by FernetMenta** [comment]
confirmed fixed on trac ticket

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
guess good for merge?

**Comment by popcornmix** [comment]
I think so.

**Comment by arnova** [comment]
+1 from me.

**Comment by fritsch** [comment]
@MartijnKaijser press the button, please

**Comment by MartijnKaijser** [comment]
hey, you guys may hit it as well if you all agree ;)

**Comment by uNiversaI** [comment]
RSS Still not fixed - lonely K scrolling

screenshot061

**Comment by popcornmix** [comment]
@uNiversaI did this issue start with #4143 ?

**Comment by uNiversaI** [comment]
I cant say for sure, as its random, but the time frame seems plausible.

**Comment by pike2k** [comment]
Sometimes the black shadow behind white subtitle text is missing now, hard to repro, seems random and doesn't happen too often...

**Comment by uNiversaI** [comment]
Bug report http://trac.kodi.tv/ticket/16132

**Pull request merged**
