### PR TITLE
[backport] [cmake] Fixes cpack support and WiiRemote packaging for rpi 

### PR DESCRIPTION
**Pull request by nsenica**
ref PR: #11321

### CODE REVIEW

**Comment by nsenica** [comment]
I'm not sure why this failed in travis.. It seems to be unrelated with this commit. Can anyone check and confirm ?

**Comment by fetzerch** [comment]
That's 'just' an unstable test. Unrelated to your change here.

**Comment by nsenica** [comment]
@hudokkow Any chance that this gets merged with the others as well :) Thanks.

**Comment by hudokkow** [comment]
;)

**Comment by nsenica** [comment]
There's a problem with this backport, can you please revert this ? I'll submit a proper backport in a minute.

**Pull request merged**
