### PR TITLE
[PVR] Add 'Find similar' for epg-based timer rules

### PR DESCRIPTION
**Pull request by linknetx**
## Description

Add 'Find similar' to timer rules context menu to allow searching for similar items for epg-based timer rules. 

Allows searching from 'Record Series' and 'Repeating Keyword' timers for similar epg listings based on either Title or EPG Search String.
## Motivation and Context

Adds a useful feature to the timer rules.
## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [X] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ksooo** [comment]
This PR mixes up two different things with one commit and title does not even reflect this. Please fix this.

**Comment by ksooo** [comment]
And before you invest more time in it: Both approaches are wrong. I cannot accept this, sorry.

**Comment by linknetx** [comment]
> And before you invest more time in it: Both approaches are wrong. I cannot accept this, sorry.

@ksooo 

I created this for my own use so my time wasn't wasted, the fact that it's usefulness won't benefit anyone else is a shame.

Time and time again I create a timer rule which for one reason or another expires with no further items scheduled, the programme may have been switched to a different channel, renamed slightly or the broadcast time changed. At present I have to carry out a laborious search using the remote to enter the search string. With this option all it takes is to use find similar from the expired timer rule context menu to find any programmes that the rule has missed. Then create a new rule based on any findings.

If there already is a simple way to do this then please let me know.

**Comment by ksooo** [comment]
What you want to achieve from user's perspective is good. Your implementation is not.

Basically, your idea is to use timer rules's search strings with the local epg search engine. The problem with this is, that the search string is backend specific. For instance pvr.hts (tvheadend) can work with regular expressions, other backends can't, local epg search engine can't. So, you might pass search terms to the local search engine which it does not handle correctly. And currently there is no programmatic way to determine the search capabilities of the backend - and honestly, I see no need to bloat the PVR Addon API further just for this feature.

If it works for you, fine. Unfortunately, the implementation does not meet expectations for a generic core for different addons for different backends, sorry.

**Comment by linknetx** [comment]
Thanks for the detailed explanation, so presumably the regular expressions can be entered into any of the timer types that support manually entering a search string.

How does that apply to the epg generated timers, I was under the impression that the search string for these was intended to be fixed and not editable.

The PR was already restricted to not searching manually based timer rules, but can easily be restricted to only searching timer rules which require an epg tag on creation. This would eliminate the problem of not being able to handle special search terms and would work for the Record Series timer which probably accounts for the majority of user generated timer rules.

If the answers still no, that's fair enough, but there's nothing to lose by asking this final question.

**Comment by ksooo** [comment]
> How does that apply to the epg generated timers, I was under the impression that the search string for these was intended to be fixed and not editable.

 Wrong assumption. :-) 

When creating a rule from epg, the epg tag is ment to be kind of a template to prefill timer settings with data the user can adjust, including the search string.

**Comment by linknetx** [comment]
OK, I admit defeat :-)

**Pull request closed without merging**
