### PR TITLE
Bump minimum libbluray version to 0.7.0 in configure.ac.

### PR DESCRIPTION
**Pull request by ace20022**

### CODE REVIEW

**Comment by ace20022** [comment]
@wsnipex like that?

**Comment by wsnipex** [comment]
no, it doesn't build with 0.7.0. That is what ubuntu 15.04 provides and it still fails....

**Comment by ace20022** [comment]
strange, can you post the error message?

**Comment by wsnipex** [comment]
ok, you're right, it only failed on trusty, which has an older libbluray. So 0.7.0 should be ok.
sorry

**Comment by wsnipex** [comment]
please also update README.linux/ubuntu to reflect the required min version

**Comment by ace20022** [comment]
@wsnipex done, ok to merge?

**Comment by wsnipex** [comment]
thanks
jenkins build and merge

**Pull request merged**
