### PR TITLE
DVDOverlayCodecFFmpeg: Do not decode eia_608 subtitles

### PR DESCRIPTION
**Pull request by fritsch**
See https://github.com/OpenELEC/OpenELEC.tv/issues/4943

Don't merge until user has tested. I did not have a sample yet.

### CODE REVIEW

**Comment by FernetMenta** [comment]
+1

**Comment by fritsch** [comment]
jenkins build this please

Fixes the problem. I got a sample to verify.

**Comment by fritsch** [comment]
What's up with jenkins? Error seems totally unrelated.

**Comment by FernetMenta** [comment]
as you say, not related.

**Pull request merged**
