### PR TITLE
Move keywords and change them up

### PR DESCRIPTION
**Pull request by razzeee**
## Description
Moves where we declare our keywords

## Motivation and context
Keywords in the `.desktop` file are not translatable, so move these to the metainfo file, just in case we want to translate in the future.

## How has this been tested?
Hasn't been tested

## What is the effect on users?
Should only improve searches in stores like KDE Discover and Gnome Software. But only really improves, when we start to translate the file.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by razzeee** [comment]
I don't think it will get shows, afaik it doesn't get shown in any software center that I know of.

But we could test, if the `.desktop` file still works. (which I assume)

**Comment by fuzzard** [comment]
any benefit in this @razzeee ?
again its effectively a doc change, so if you consider it of benefit, merge at your leisure

**Comment by razzeee** [comment]
I don't think I can figure out their bug tracker, without investing a significant amount of time :/

**Comment by basilgello** [comment]
I can start the discussion there, only thing you'll do is reply to email :)

**Pull request merged**
