### PR TITLE
[VideoInfoScanner] Fix #25662 - save all tv show and episode actor images in tv show .actors folder.

### LINKED ISSUE #25662: Local Actor Images Ignored
## Bug report
This issue only affects **episodes**. Movies and TV Shows are unaffected

The .actors folder is created by Kodi when using the _Export to separate files_ function. It creates the following .actors folder
1. Kodi creates the .actors folder in the root of each particular tv show - `\My TV Shows\3 Body Problem\.actors\`
2. Kodi creates the .actors folder in **each** Season folder - `\My TV Shows\3 Body Problem\Season 1\.actors\`

I had noticed in my own main library that some actor images were different to what I expected, and other actors had no image even though a local image was available. It was this that made me curious why that was happening.

When using local data --nfo files, local images, .actors folder-- Kodi seems to ignore local actor images and instead downloads the image if a valid `<thumb></thumb>` URL is available. If no valid URL is available, then no image is displayed.

The first test I ran was removing the `<thumb></thumb>` tag from all the nfo files and then scanned the show. Checking the library after the scan, the TV Show actors used the local images, but episode specific actors were left blank, even though a local image was available.

On a second test on a fresh install, I left the `<thumb></thumb>` tags in place, but replaced all actors images with the same generic image. The TV Show used the generic image, but episode specific actors had correct actor images downloaded. See log below.

Third test - I moved the generic episode actor images from the `...\Season 1\.actors\` folder into the `\TV show\.actors\ `folder. After scanning, the episode actors displayed the generic image.

The problem seems to be that the Seasons .actors folder is ignored.

## Expected Behavior
Use local images.

## Actual Behavior
Local actor images for episodes are ignored. 
If a URL is available, the image is downloaded. 
If no URL is available, no image is displayed.

## Possible Fix
--

### To Reproduce
1. Requires a TV show with nfo files and local .actors folder
4. In the nfo file, delete all the `<thumb></thumb>` tags for the actors
5. Scan the show to the library. Check episodes for missing images.
6. Probably best to ensure the TV show has not previously been scanned into the same library to avoid image cache issues.

### Debuglog
The debuglog can be found here: https://paste.kodi.tv/sagikoxiro.kodi
From line 3070 actor images for episodes are downloaded.
(In this particular show, there are only episode specific actors for the first episode.)

### Screenshots 
Not required

## Additional context or screenshots (if appropriate)
Nil

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] **Windows**
 - [ ] Windows UWP

 - Operating system version/name: **Running on Windows 10 22H2, kernel: Windows NT x86 64-bit version 10.0.19045.4780**
 - Kodi version: **Kodi (21.1 (21.1.0) Git:20240817-183eb85f10). Platform: Windows NT x86 64-bit**

### PR DESCRIPTION
**Pull request by 78andyp**
Second attempt at fixing #25662 based on feedback in #25785.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by KarellenX** [comment]
@78andyp 
Sorry, I don't speak C++. What method are you using for this new PR? Do you need testing?
Is this doing away with all Seasons .actors folders?

**Comment by 78andyp** [comment]
> @78andyp Sorry, I don't speak C++. What method are you using for this new PR? Do you need testing? Is this doing away with all Seasons .actors folders?

Apologies, I should have made it clearer. This simply uses one .actors folder in the tvshow directory and does away with the individual seasons .actors folder - for both export and import.

Yes please for testing, thanks :)

**Comment by KarellenX** [comment]
Win64 test build here... https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20241222-00550595-actors2-x64.exe

I have tested this on a couple of tv shows.
Actor images in the season .actors folder are ignored.
All actor images in the tv show .actors folder are found for both the tv show and episodes.

No issues found.

**Comment by 78andyp** [comment]
> Win64 test build here... https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20241222-00550595-actors2-x64.exe
> 
> I have tested this on a couple of tv shows. Actor images in the season .actors folder are ignored. All actor images in the tv show .actors folder are found for both the tv show and episodes.
> 
> No issues found.

Thank you.

**Comment by KarellenX** [comment]
@rmrector 
Is this ok to be merged?
Should it be backported to v21?

**Comment by rmrector** [comment]
Looks good.

Backporting makes sense. @78andyp you can submit a backport MR for this by creating a new branch off of Omega and applying the same code changes.

**Review by rmrector — APPROVED** [review]

**Comment by 78andyp** [comment]
> Looks good.
> 
> Backporting makes sense. @78andyp you can submit a backport MR for this by creating a new branch off of Omega and applying the same code changes.

Hi. Thanks for merging. I've just uploaded the backport.

**Pull request merged**
