### PR TITLE
[ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by SoffiMeower**
<details>
<summary>
Details
</summary>

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /xbmc/platform/darwin/ios/LaunchImage-700-Portrait@2x~ipad.png | 8.87kb | 0.62kb | 93.07% |
| /xbmc/platform/darwin/ios/LaunchImage-1200-Landscape-2388h@2x.png | 3.90kb | 0.72kb | 81.65% |
| /xbmc/platform/darwin/ios/LaunchImage-1200-Portrait-2388h@2x.png | 3.89kb | 0.72kb | 81.56% |
| /xbmc/platform/darwin/ios/LaunchImage-1200-Landscape-2224h@2x.png | 3.64kb | 0.68kb | 81.29% |
| /xbmc/platform/darwin/ios/LaunchImage-1200-Portrait-2224h@2x.png | 3.63kb | 0.68kb | 81.16% |
| /xbmc/platform/darwin/ios/LaunchImage-1200-Landscape-2688h@3x.png | 3.29kb | 0.64kb | 80.62% |
| /xbmc/platform/darwin/ios/LaunchImage-1200-Portrait-2688h@3x.png | 3.29kb | 0.64kb | 80.51% |
| /xbmc/platform/darwin/ios/LaunchImage-700-Landscape@2x~ipad.png | 3.11kb | 0.62kb | 80.21% |
| /xbmc/platform/darwin/ios/LaunchImage-Landscape@2x~ipad.png | 3.11kb | 0.62kb | 80.21% |
| /xbmc/platform/darwin/ios/LaunchImage-Portrait@2x~ipad.png | 3.11kb | 0.62kb | 80.21% |
| /xbmc/platform/darwin/ios/LaunchImage-800-Landscape-736h@3x.png | 2.67kb | 0.55kb | 79.54% |
| /xbmc/platform/darwin/ios/LaunchImage-800-Portrait-736h@3x.png | 2.73kb | 0.57kb | 79.09% |
| /xbmc/platform/darwin/ios/LaunchImage-1100-Landscape-2436h@3x.png | 2.71kb | 0.57kb | 79.07% |
| /xbmc/platform/darwin/ios/LaunchImage-1100-Portrait-2436h@3x.png | 2.71kb | 0.57kb | 79.01% |
| /xbmc/platform/darwin/ios/LaunchImage-1200-Landscape-1792h@2x.png | 1.54kb | 0.42kb | 72.77% |
| /xbmc/platform/darwin/ios/LaunchImage-1200-Portrait-1792h@2x.png | 1.53kb | 0.42kb | 72.63% |
| /xbmc/platform/darwin/ios/LaunchImage-800-667h@2x.png | 1.03kb | 0.34kb | 66.67% |
| /addons/webinterface.default/themes/base/images/row-pause.png | 0.97kb | 0.33kb | 66.20% |
| /addons/skin.estuary/media/flags/rds/rds.png | 2.87kb | 1.12kb | 60.98% |
| /xbmc/platform/darwin/ios/LaunchImage-568h@2x.png | 0.77kb | 0.31kb | 59.75% |
| /xbmc/platform/darwin/ios/LaunchImage-700-568h@2x.png | 0.77kb | 0.31kb | 59.75% |
| /xbmc/platform/darwin/ios/LaunchImage@2x.png | 0.71kb | 0.32kb | 55.75% |
| /xbmc/platform/darwin/ios/LaunchImage-700@2x.png | 0.71kb | 0.32kb | 55.75% |
| /addons/webinterface.default/favicon.png | 1.20kb | 0.56kb | 53.34% |
| /addons/resource.language.en_gb/icon.png | 1.89kb | 1.05kb | 44.53% |
| /addons/skin.estuary/media/OverlaySpoiler.png | 4.70kb | 2.63kb | 44.14% |
| /addons/metadata.tvshows.themoviedb.org/icon.png | 8.19kb | 4.99kb | 39.08% |
| /addons/script.module.pycryptodome/icon.png | 7.07kb | 4.40kb | 37.76% |
| /addons/script.module.pil/icon.png | 7.07kb | 4.40kb | 37.76% |
| /addons/webinterface.default/icon-128.png | 1.83kb | 1.19kb | 34.78% |
| /addons/metadata.common.imdb.com/icon.png | 3.75kb | 2.51kb | 33.06% |
| /addons/webinterface.default/icon-152.png | 1.98kb | 1.34kb | 32.07% |
| /addons/webinterface.default/icon-192.png | 2.27kb | 1.55kb | 31.90% |
| /addons/skin.estouchy/media/DefaultUser.png | 2.35kb | 1.65kb | 29.75% |
| /addons/audioencoder.kodi.builtin.wma/icon.png | 3.98kb | 2.85kb | 28.43% |
| /addons/skin.estouchy/background/primary.jpg | 126.87kb | 92.43kb | 27.15% |
| /addons/screensaver.xbmc.builtin.dim/icon.png | 4.42kb | 3.25kb | 26.54% |
| /addons/webinterface.default/icon-144.png | 2.69kb | 1.98kb | 26.37% |
| /addons/webinterface.default/icon.png | 2.69kb | 1.98kb | 26.37% |
| /addons/screensaver.xbmc.builtin.black/icon.png | 4.28kb | 3.17kb | 26.11% |
| /addons/metadata.common.musicbrainz.org/icon.png | 6.51kb | 4.85kb | 25.53% |
| /addons/kodi.binary.instance.pvr/icon.png | 4.65kb | 3.46kb | 25.48% |
| /addons/metadata.local/icon.png | 3.56kb | 2.65kb | 25.45% |
| /addons/metadata.album.universal/icon.png | 6.41kb | 4.88kb | 23.87% |
| /addons/audioencoder.kodi.builtin.aac/icon.png | 6.09kb | 4.67kb | 23.41% |
| /addons/skin.estuary/media/DefaultAddonFont.png | 4.59kb | 3.52kb | 23.31% |
| /addons/xbmc.python/icon.png | 5.64kb | 4.34kb | 23.09% |
| /addons/metadata.common.theaudiodb.com/icon.png | 7.22kb | 5.59kb | 22.56% |
| /addons/metadata.common.allmusic.com/icon.png | 6.05kb | 4.70kb | 22.40% |
| /addons/metadata.themoviedb.org/icon.png | 6.35kb | 4.96kb | 21.94% |
| /addons/metadata.common.themoviedb.org/icon.png | 6.40kb | 5.00kb | 21.94% |
| /addons/skin.estuary/media/DefaultUser.png | 2.78kb | 2.21kb | 20.70% |
| /addons/metadata.common.fanart.tv/icon.png | 5.74kb | 4.58kb | 20.18% |
| /addons/skin.estuary/media/osd/fullscreen/buttons/rds.png | 3.70kb | 2.97kb | 19.52% |
| /addons/skin.estuary/media/flags/videoresolution/8K.png | 1.25kb | 1.03kb | 17.62% |
| /lib/libUPnP/Neptune/Build/Targets/x86-microsoft-winrt-vs2011/TestShell/Assets/SplashScreen.png | 2.10kb | 1.77kb | 15.52% |
| /addons/skin.estuary/media/DefaultBluray.png | 4.03kb | 3.49kb | 13.43% |
| /addons/skin.estuary/themes/curial/lists/panel.png | 161.86kb | 140.61kb | 13.13% |
| /addons/skin.estuary/media/DefaultMusicTop100Albums.png | 2.16kb | 1.89kb | 12.77% |
| /addons/skin.estuary/media/DefaultMusicAlbums.png | 2.16kb | 1.89kb | 12.77% |
| /addons/skin.estuary/media/DefaultAlbumCover.png | 2.16kb | 1.89kb | 12.77% |
| /addons/webinterface.default/images/splash_hi.png | 10.49kb | 9.20kb | 12.35% |
| /media/icon80x80.png | 1.76kb | 1.55kb | 11.62% |
| /addons/skin.estuary/media/flags/audiocodec/dtshd_hra.png | 1.51kb | 1.35kb | 10.65% |
| /addons/skin.estouchy/media/flagging/audio/dtshd_hra.png | 1.51kb | 1.35kb | 10.65% |
| /addons/skin.estuary/media/DefaultDVDEmpty.png | 1.85kb | 1.66kb | 10.55% |
| /tools/android/packaging/xbmc/res/drawable/ic_recommendation_80dp.png | 2.19kb | 1.96kb | 10.50% |
| /addons/skin.estuary/media/DefaultAddonAlbumInfo.png | 2.57kb | 2.31kb | 10.33% |
| /tools/windows/packaging/uwp/media/icon50x50.png | 2.73kb | 2.45kb | 10.31% |
| /addons/skin.estuary/media/flags/videocodec/mp4v.png | 1.43kb | 1.29kb | 10.02% |
| /addons/skin.estuary/media/flags/videocodec/mpeg4.png | 1.43kb | 1.29kb | 10.02% |
| /addons/skin.estouchy/media/DefaultAddonFont.png | 1.53kb | 1.38kb | 9.83% |
| /addons/skin.estuary/media/DefaultIconError.png | 1.65kb | 1.50kb | 9.14% |
| /addons/skin.estuary/media/flags/audiocodec/truehd.png | 1.60kb | 1.45kb | 9.00% |
| /addons/skin.estouchy/media/icon_settings_media.png | 2.06kb | 1.88kb | 8.83% |
| /addons/skin.estuary/media/DefaultAddonVfs.png | 3.51kb | 3.20kb | 8.77% |
| /addons/skin.estuary/media/DefaultInProgressShows.png | 1.91kb | 1.75kb | 8.41% |
| /addons/skin.estuary/media/DefaultAddonsZip.png | 2.02kb | 1.85kb | 8.38% |
| /addons/skin.estouchy/media/DefaultVideoCover.png | 2.08kb | 1.91kb | 8.13% |
| /addons/skin.estouchy/media/DefaultVideo.png | 2.08kb | 1.91kb | 8.13% |
| /addons/skin.estouchy/media/flagging/video/bluray.png | 1.28kb | 1.18kb | 8.00% |
| /addons/skin.estuary/media/flags/videocodec/bluray.png | 1.28kb | 1.18kb | 8.00% |
| /addons/skin.estouchy/media/flagging/video/hdmv.png | 1.28kb | 1.18kb | 8.00% |
| /addons/skin.estuary/media/flags/videocodec/hdmv.png | 1.28kb | 1.18kb | 8.00% |
| /addons/skin.estuary/media/DefaultAddonImages.png | 1.86kb | 1.72kb | 7.30% |
| /addons/skin.estuary/media/DefaultPicture.png | 1.86kb | 1.72kb | 7.30% |
| /addons/skin.estuary/media/flags/audiocodec/flac.png | 1.09kb | 1.02kb | 7.23% |
| /addons/skin.estuary/extras/backgrounds/pattern5.jpg | 213.61kb | 198.43kb | 7.11% |
| /addons/skin.estuary/media/DefaultMusicRecentlyPlayed.png | 1.54kb | 1.44kb | 6.90% |
| /addons/skin.estuary/extras/backgrounds/pattern3.jpg | 152.79kb | 142.30kb | 6.87% |
| /tools/windows/packaging/uwp/media/icon150x150.png | 9.82kb | 9.16kb | 6.79% |
| /addons/webinterface.default/screenshots/settings.jpg | 84.45kb | 78.75kb | 6.75% |
| /addons/skin.estuary/media/DefaultAddonTvInfo.png | 1.59kb | 1.49kb | 6.50% |
| /addons/webinterface.default/screenshots/addons.jpg | 125.55kb | 117.41kb | 6.48% |
| /addons/skin.estuary/media/flags/audiocodec/vorbis.png | 1.65kb | 1.55kb | 6.44% |
| /addons/skin.estouchy/media/flagging/audio/vorbis.png | 1.65kb | 1.55kb | 6.44% |
| /addons/skin.estuary/media/icons/pvr/recording.png | 1.77kb | 1.66kb | 6.44% |
| /addons/skin.estuary/media/DefaultAddonImageDecoder.png | 2.14kb | 2.00kb | 6.34% |
| /addons/skin.estuary/media/DefaultRecentlyAddedMusicVideos.png | 1.53kb | 1.44kb | 6.24% |
| /addons/skin.estuary/media/DefaultRecentlyAddedMovies.png | 1.53kb | 1.44kb | 6.24% |
| /addons/skin.estuary/media/DefaultRecentlyAddedEpisodes.png | 1.53kb | 1.44kb | 6.24% |
| /addons/skin.estuary/media/DefaultMovieTitle.png | 2.25kb | 2.11kb | 6.20% |
| /addons/skin.estuary/media/DefaultMusicVideoTitle.png | 2.25kb | 2.11kb | 6.20% |
| /addons/skin.estuary/media/DefaultTVShowTitle.png | 2.25kb | 2.11kb | 6.20% |
| /addons/skin.estouchy/media/DefaultAddonImageDecoder.png | 1.60kb | 1.50kb | 6.05% |
| /addons/skin.estuary/media/flags/audiocodec/wavpack.png | 1.45kb | 1.36kb | 5.81% |
| /addons/skin.estouchy/media/flagging/audio/wavpack.png | 1.45kb | 1.36kb | 5.81% |
| /addons/skin.estuary/media/DefaultStudios.png | 2.42kb | 2.28kb | 5.76% |
| /addons/skin.estouchy/media/flagging/video/hvc1.png | 1.23kb | 1.16kb | 5.71% |
| /addons/skin.estouchy/media/flagging/video/hev1.png | 1.23kb | 1.16kb | 5.71% |
| /addons/skin.estuary/media/flags/videocodec/hev1.png | 1.23kb | 1.16kb | 5.71% |
| /addons/skin.estuary/media/flags/videocodec/hvc1.png | 1.23kb | 1.16kb | 5.71% |
| /addons/skin.estouchy/media/flagging/video/hevc.png | 1.23kb | 1.16kb | 5.71% |
| /addons/skin.estuary/media/flags/videocodec/hevc.png | 1.23kb | 1.16kb | 5.71% |
| /addons/webinterface.default/screenshots/artist.jpg | 156.86kb | 147.91kb | 5.71% |
| /addons/skin.estuary/media/flags/audiocodec/dolbydigital.png | 1.35kb | 1.27kb | 5.64% |
| /addons/skin.estouchy/media/flagging/audio/dolbydigital.png | 1.35kb | 1.27kb | 5.64% |
| /addons/skin.estuary/media/flags/audiocodec/ac3.png | 1.35kb | 1.27kb | 5.64% |
| /addons/skin.estuary/media/flags/audiocodec/eac3.png | 1.35kb | 1.27kb | 5.64% |
| /addons/skin.estouchy/media/flagging/audio/ac3.png | 1.35kb | 1.27kb | 5.64% |
| /addons/skin.estouchy/media/flagging/audio/eac3.png | 1.35kb | 1.27kb | 5.64% |
| /addons/skin.estouchy/media/flagging/audio/truehd.png | 1.35kb | 1.27kb | 5.64% |
| /lib/libUPnP/Platinum/Extras/platinum-120x120.png | 25.95kb | 24.50kb | 5.59% |
| /addons/skin.estouchy/media/flagging/video/mpeg1video.png | 1.26kb | 1.20kb | 5.41% |
| /addons/skin.estuary/media/flags/videocodec/mpeg1video.png | 1.26kb | 1.20kb | 5.41% |
| /addons/skin.estuary/media/flags/videocodec/mpeg1.png | 1.26kb | 1.20kb | 5.41% |
| /addons/skin.estuary/media/flags/aspectratio/2.35.png | 1.25kb | 1.19kb | 5.30% |
| /addons/skin.estouchy/media/flagging/aspectratio/2.35.png | 1.25kb | 1.19kb | 5.30% |
| /addons/skin.estuary/media/DefaultGenre.png | 3.10kb | 2.94kb | 5.29% |
| /addons/skin.estouchy/media/flagging/video/mpeg2video.png | 1.40kb | 1.32kb | 5.25% |
| /addons/skin.estuary/media/flags/videocodec/mpeg2video.png | 1.40kb | 1.32kb | 5.25% |
| /addons/skin.estouchy/media/flagging/video/h262.png | 1.40kb | 1.32kb | 5.25% |
| /addons/skin.estuary/media/flags/videocodec/mpeg2.png | 1.40kb | 1.32kb | 5.25% |
| /addons/skin.estouchy/media/flagging/video/720.png | 1.29kb | 1.22kb | 5.24% |
| /addons/skin.estuary/media/flags/videoresolution/720.png | 1.29kb | 1.22kb | 5.24% |
| /addons/webinterface.default/screenshots/movie.jpg | 168.60kb | 159.78kb | 5.24% |
| /addons/skin.estuary/media/flags/audiocodec/opus.png | 1.32kb | 1.25kb | 5.18% |
| /addons/skin.estouchy/media/flagging/audio/opus.png | 1.32kb | 1.25kb | 5.18% |
| /addons/skin.estuary/media/DefaultMusicVideos.png | 2.00kb | 1.90kb | 4.97% |
| /addons/skin.estuary/media/flags/audiocodec/pcm_s24le.png | 1.16kb | 1.10kb | 4.89% |
| /addons/skin.estuary/media/flags/audiocodec/pcm_s16le.png | 1.16kb | 1.10kb | 4.89% |
| /addons/skin.estuary/media/flags/audiocodec/pcm.png | 1.16kb | 1.10kb | 4.89% |
| /addons/skin.estuary/media/flags/audiocodec/pcm_bluray.png | 1.16kb | 1.10kb | 4.89% |
| /addons/skin.estuary/media/flags/audiocodec/dtsma.png | 1.49kb | 1.42kb | 4.86% |
| /addons/skin.estouchy/media/flagging/audio/dtsma.png | 1.49kb | 1.42kb | 4.86% |
| /addons/skin.estuary/media/flags/audiocodec/dtshd_ma.png | 1.49kb | 1.42kb | 4.86% |
| /addons/skin.estouchy/media/flagging/audio/dtshd_ma.png | 1.49kb | 1.42kb | 4.86% |
| /addons/skin.estuary/media/DefaultMovies.png | 1.55kb | 1.47kb | 4.85% |
| /addons/skin.estouchy/media/flagging/video/540.png | 1.50kb | 1.43kb | 4.67% |
| /addons/skin.estuary/media/flags/videoresolution/540.png | 1.50kb | 1.43kb | 4.67% |
| /addons/skin.estuary/media/flags/videoresolution/480.png | 1.56kb | 1.48kb | 4.64% |
| /addons/skin.estouchy/media/flagging/video/480.png | 1.56kb | 1.48kb | 4.64% |
| /addons/skin.estuary/media/icons/settings/player.png | 1.30kb | 1.24kb | 4.58% |
| /addons/skin.estuary/media/flags/aspectratio/1.85.png | 1.20kb | 1.14kb | 4.56% |
| /addons/skin.estouchy/media/flagging/aspectratio/1.85.png | 1.20kb | 1.14kb | 4.56% |
| /media/splash.jpg | 54.64kb | 52.27kb | 4.33% |
| /addons/skin.estouchy/media/flagging/audio/flac.png | 1.06kb | 1.01kb | 4.24% |
| /addons/webinterface.default/screenshots/artists.jpg | 166.70kb | 159.68kb | 4.21% |
| /addons/skin.estouchy/media/flagging/video/576.png | 1.42kb | 1.36kb | 4.14% |
| /addons/skin.estuary/media/flags/videoresolution/576.png | 1.42kb | 1.36kb | 4.14% |
| /addons/webinterface.default/screenshots/search.jpg | 157.61kb | 151.11kb | 4.12% |
| /addons/webinterface.default/screenshots/tv.jpg | 213.58kb | 204.87kb | 4.08% |
| /addons/webinterface.default/screenshots/now-playing.jpg | 227.26kb | 218.13kb | 4.02% |
| /addons/skin.estuary/resources/screenshot-08.jpg | 118.91kb | 114.22kb | 3.95% |
| /addons/skin.estuary/extras/backgrounds/pattern7.jpg | 153.47kb | 147.50kb | 3.89% |
| /addons/skin.estuary/extras/backgrounds/pattern2.jpg | 117.84kb | 113.26kb | 3.88% |
| /addons/skin.estouchy/media/flagging/video/divx.png | 1.18kb | 1.14kb | 3.87% |
| /addons/skin.estuary/media/flags/videocodec/dx50.png | 1.18kb | 1.14kb | 3.87% |
| /addons/skin.estuary/media/flags/videocodec/divx.png | 1.18kb | 1.14kb | 3.87% |
| /addons/skin.estuary/media/flags/videocodec/div3.png | 1.18kb | 1.14kb | 3.87% |
| /addons/skin.estuary/media/flags/audiocodec/ape.png | 0.97kb | 0.93kb | 3.84% |
| /addons/skin.estuary/media/flags/aspectratio/2.40.png | 1.22kb | 1.18kb | 3.83% |
| /addons/skin.estouchy/media/flagging/aspectratio/2.40.png | 1.22kb | 1.18kb | 3.83% |
| /addons/skin.estouchy/media/flagging/audio/pcm_bluray.png | 1.14kb | 1.09kb | 3.78% |
| /addons/skin.estouchy/media/flagging/audio/pcm_s24le.png | 1.14kb | 1.09kb | 3.78% |
| /addons/skin.estouchy/media/flagging/audio/pcm_s16le.png | 1.14kb | 1.09kb | 3.78% |
| /addons/skin.estouchy/media/flagging/audio/pcm.png | 1.14kb | 1.09kb | 3.78% |
| /addons/skin.estuary/media/flags/videocodec/vhs.png | 1.07kb | 1.03kb | 3.65% |
| /addons/skin.estouchy/media/flagging/video/vhs.png | 1.07kb | 1.03kb | 3.65% |
| /addons/skin.estouchy/media/flagging/video/avc1.png | 1.23kb | 1.19kb | 3.65% |
| /addons/skin.estuary/media/flags/videocodec/avc1.png | 1.23kb | 1.19kb | 3.65% |
| /addons/skin.estuary/media/DefaultAddonLanguage.png | 1.43kb | 1.37kb | 3.63% |
| /addons/skin.estouchy/media/flagging/video/1080.png | 1.41kb | 1.36kb | 3.54% |
| /addons/skin.estuary/media/flags/videoresolution/1080.png | 1.41kb | 1.36kb | 3.54% |
| /lib/libUPnP/Platinum/Extras/platinum-120x120.jpg | 15.72kb | 15.17kb | 3.49% |
| /addons/skin.estouchy/media/icon_settings_systeminfo.png | 2.77kb | 2.68kb | 3.45% |
| /addons/skin.estuary/extras/backgrounds/pattern4.jpg | 94.07kb | 90.93kb | 3.34% |
| /addons/skin.estuary/media/DefaultAddonsInstalled.png | 2.08kb | 2.02kb | 3.33% |
| /addons/skin.estouchy/media/flagging/audio/wav.png | 1.29kb | 1.25kb | 3.18% |
| /addons/skin.estuary/media/flags/audiocodec/wav.png | 1.29kb | 1.25kb | 3.18% |
| /addons/skin.estuary/resources/screenshot-01.jpg | 166.70kb | 161.41kb | 3.17% |
| /addons/skin.estuary/resources/screenshot-03.jpg | 153.36kb | 148.51kb | 3.16% |
| /addons/skin.estuary/media/flags/audiocodec/alac.png | 1.03kb | 1.00kb | 3.13% |
| /addons/skin.estuary/resources/screenshot-04.jpg | 150.34kb | 145.67kb | 3.11% |
| /addons/skin.estuary/resources/screenshot-05.jpg | 148.74kb | 144.19kb | 3.06% |
| /addons/skin.estuary/media/DefaultMusicSources.png | 10.03kb | 9.73kb | 3.04% |
| /addons/skin.estuary/media/icons/settings/sysinfo.png | 2.61kb | 2.53kb | 2.99% |
| /lib/libUPnP/Platinum/Extras/platinum-48x48.png | 4.57kb | 4.44kb | 2.93% |
| /addons/skin.estuary/media/flags/aspectratio/2.76.png | 1.17kb | 1.13kb | 2.77% |
| /addons/skin.estouchy/media/flagging/aspectratio/2.76.png | 1.17kb | 1.13kb | 2.77% |
| /addons/skin.estuary/extras/backgrounds/pattern1.jpg | 91.61kb | 89.20kb | 2.64% |
| /addons/skin.estuary/media/flags/aspectratio/1.78.png | 1.13kb | 1.10kb | 2.60% |
| /addons/skin.estouchy/media/flagging/aspectratio/1.78.png | 1.13kb | 1.10kb | 2.60% |
| /addons/skin.estuary/media/flags/audiocodec/avc.png | 1.13kb | 1.10kb | 2.59% |
| /addons/skin.estouchy/media/flagging/audio/avc.png | 1.13kb | 1.10kb | 2.59% |
| /addons/skin.estuary/extras/backgrounds/primary.jpg | 306.75kb | 298.88kb | 2.57% |
| /addons/webinterface.default/images/fanart_default/tweeter.jpg | 55.05kb | 53.64kb | 2.56% |
| /addons/skin.estuary/media/flags/audiocodec/aifc.png | 1.05kb | 1.03kb | 2.42% |
| /addons/skin.estouchy/media/flagging/audio/aifc.png | 1.05kb | 1.03kb | 2.42% |
| /addons/skin.estouchy/media/flagging/video/h264.png | 1.13kb | 1.11kb | 2.41% |
| /addons/skin.estuary/media/flags/videocodec/h264.png | 1.13kb | 1.11kb | 2.41% |
| /addons/skin.estuary/media/flags/aspectratio/1.37.png | 1.09kb | 1.06kb | 2.33% |
| /addons/skin.estouchy/media/flagging/aspectratio/1.37.png | 1.09kb | 1.06kb | 2.33% |
| /addons/skin.estuary/resources/screenshot-02.jpg | 72.15kb | 70.48kb | 2.32% |
| /addons/webinterface.default/screenshots/edit-media.jpg | 152.94kb | 149.64kb | 2.16% |
| /addons/skin.estouchy/media/icon_menu_games.png | 1.59kb | 1.56kb | 2.08% |
| /addons/skin.estuary/resources/screenshot-07.jpg | 124.09kb | 121.69kb | 1.94% |
| /tools/windows/packaging/uwp/media/banner310x150.png | 12.69kb | 12.47kb | 1.78% |
| /addons/skin.estuary/extras/home-images/music.jpg | 180.02kb | 176.82kb | 1.78% |
| /addons/skin.estouchy/media/flagging/video/vp9.png | 1.34kb | 1.31kb | 1.75% |
| /addons/skin.estouchy/media/flagging/video/vp8.png | 1.34kb | 1.31kb | 1.75% |
| /addons/skin.estuary/media/flags/videocodec/vp8.png | 1.34kb | 1.31kb | 1.75% |
| /addons/skin.estuary/media/flags/videocodec/vp9.png | 1.34kb | 1.31kb | 1.75% |
| /addons/skin.estuary/resources/screenshot-06.jpg | 88.11kb | 86.59kb | 1.72% |
| /addons/skin.estuary/media/icons/settings/media.png | 2.02kb | 1.98kb | 1.69% |
| /addons/skin.estuary/extras/home-images/movie.jpg | 196.80kb | 193.48kb | 1.69% |
| /addons/skin.estuary/media/DefaultMusicYears.png | 1.76kb | 1.74kb | 1.50% |
| /addons/skin.estuary/media/DefaultYear.png | 1.76kb | 1.74kb | 1.50% |
| /addons/skin.estouchy/media/flagging/video/xvid.png | 1.17kb | 1.15kb | 1.42% |
| /addons/skin.estuary/media/flags/videocodec/xvid.png | 1.17kb | 1.15kb | 1.42% |
| /addons/skin.estouchy/media/flagging/audio/ape.png | 0.93kb | 0.92kb | 1.36% |
| /addons/webinterface.default/images/fanart_default/speaker.jpg | 96.94kb | 95.71kb | 1.27% |
| /addons/skin.estuary/media/flags/aspectratio/2.55.png | 1.10kb | 1.09kb | 1.24% |
| /addons/skin.estouchy/media/flagging/aspectratio/2.55.png | 1.10kb | 1.09kb | 1.24% |
| /addons/skin.estuary/media/flags/aspectratio/2.20.png | 1.12kb | 1.10kb | 1.14% |
| /addons/skin.estouchy/media/flagging/aspectratio/2.20.png | 1.12kb | 1.10kb | 1.14% |
| /addons/skin.estouchy/media/flagging/audio/alac.png | 1.00kb | 0.99kb | 1.08% |
| /addons/skin.estouchy/background/tv.jpg | 26.68kb | 26.40kb | 1.04% |
| /addons/skin.estuary/media/flags/audiocodec/mp3float.png | 1.11kb | 1.10kb | 0.97% |
| /addons/skin.estuary/media/flags/audiocodec/mp3.png | 1.11kb | 1.10kb | 0.97% |
| /addons/skin.estouchy/media/flagging/audio/mp3.png | 1.11kb | 1.10kb | 0.97% |
| /addons/skin.estuary/media/flags/audiocodec/aac.png | 1.02kb | 1.01kb | 0.96% |
| /addons/skin.estuary/media/flags/audiocodec/aac_latm.png | 1.02kb | 1.01kb | 0.96% |
| /addons/skin.estouchy/media/flagging/audio/aac.png | 1.02kb | 1.01kb | 0.96% |
| /addons/skin.estouchy/media/DefaultAlbumCover.png | 6.41kb | 6.35kb | 0.94% |
| /addons/skin.estuary/extras/backgrounds/pattern6.jpg | 52.38kb | 51.88kb | 0.94% |
| /lib/libUPnP/Platinum/Source/Platform/Android/samples/sample-upnp/res/drawable-xhdpi/ic_launcher.png | 14.05kb | 13.92kb | 0.91% |
| /lib/libUPnP/Platinum/Source/Platform/Android/module/platinum/res/drawable-xhdpi/ic_launcher.png | 14.05kb | 13.92kb | 0.91% |
| /addons/webinterface.default/images/fanart_default/amp.jpg | 80.98kb | 80.42kb | 0.68% |
| /addons/skin.estouchy/media/DefaultAudio.png | 1.76kb | 1.75kb | 0.66% |
| /addons/skin.estuary/resources/fanart.jpg | 47.99kb | 47.67kb | 0.66% |
| /addons/skin.estouchy/media/icon_settings_player.png | 1.34kb | 1.34kb | 0.51% |
| /addons/skin.estouchy/media/icon_button_filtered.png | 0.96kb | 0.96kb | 0.41% |
| /addons/skin.estuary/media/flags/audiocodec/mp2.png | 1.08kb | 1.08kb | 0.36% |
| /addons/skin.estouchy/media/flagging/audio/mp2.png | 1.08kb | 1.08kb | 0.36% |
| /addons/skin.estuary/media/DefaultDirector.png | 2.04kb | 2.03kb | 0.34% |
| /addons/webinterface.default/images/fanart_default/cans.jpg | 103.32kb | 103.04kb | 0.27% |
| /lib/libUPnP/Platinum/Source/Platform/Android/samples/sample-upnp/res/drawable-hdpi/ic_launcher.png | 9.18kb | 9.16kb | 0.20% |
| /lib/libUPnP/Platinum/Source/Platform/Android/module/platinum/res/drawable-hdpi/ic_launcher.png | 9.18kb | 9.16kb | 0.20% |
| /addons/webinterface.default/images/fanart_default/concert.jpg | 104.57kb | 104.41kb | 0.15% |
| /addons/webinterface.default/images/fanart_default/turntable.jpg | 44.15kb | 44.11kb | 0.10% |
| /addons/webinterface.default/images/fanart_default/guitar.jpg | 88.87kb | 88.86kb | 0.01% |
| /addons/skin.estouchy/resources/fanart.jpg | 57.80kb | 57.79kb | 0.01% |
| | | | |
| **Total :** | **5,659.30kb** | **5,339.24kb** | **5.66%** |
</details>

### CODE REVIEW

**Comment by da-anda** [comment]
Hi. Thanks for you pull request. Can you tell what kind of optimizations has been done to the JPGs in this PR? Have they been re-encoded with a lower quality setting to get the filesize down or were these lossless optimizations?

**Comment by ghostslayer989** [comment]
Lossless, hence the small size change. I saw a stale repo for this and thought I might as well just finish the job lol.

**Comment by ghostslayer989** [comment]
Will do!

**Comment by da-anda** [comment]
rebased version is at #16716

**Pull request closed without merging**
