### PR TITLE
[cmake] copy_files_from_filelist_to_buildtree: add KEEP_DIR_STRUCTURE option

### PR DESCRIPTION
**Pull request by Rechi**
## Description
directory structure is kept if KEEP_DIR_STRUCTURE is specified as 2nd (but not last) field

## Motivation and Context
This allows to add `project/BuildDependencies/${ARCH}/bin/Python KEEP_DIR_STRUCTURE system` and the directory structure will be kept.

## How Has This Been Tested?
Tested with the above given example.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by hudokkow — APPROVED** [review]

**Comment by hudokkow** [comment]
Just a matter of style:

- No space between command and opening parentheses
- Commands in lowercase

**Comment by Rechi** [comment]
@hudokkow updated style, now correct?
Is `/*` as identifier for keeping directory structure okay? It can also be changed to `/`.

**Comment by wsnipex** [comment]
I'd prefer adding a new function instead. E.g. copy_dirs_from_filelist_to_buildtree

**Comment by Rechi** [comment]
@wsnipex but with a new function I can't just simply add `project/BuildDependencies/${ARCH}/bin/Python/* system/python/*` to `cmake/installdata/windows/python.txt`

**Comment by wsnipex** [comment]
I'd like to understand why this is needed. Are you trying to misuse this to install dependencies from within kodi?

**Comment by Rechi** [comment]
For win32 python files get extracted to system/python and the whole folder gets copied by cmake (https://github.com/xbmc/xbmc/blob/a18701e/cmake/installdata/windows/python.txt) to `<BUILD-DIR>/system/python` while directory structure is kept.

For windows x64 the python files are stored at project/BuildDependencies/x64/bin/Python and they need also be copied to `<BUILD-DIR>/system/python` and the directory structure must be kept.

My first try in just adding `project/BuildDependencies/${ARCH}/bin/Python/* system/python` at `cmake/installdata/windows/python.txt` didn't worked because the directory structure got lost.

I hope you can understand what I'm trying to archive.

**Comment by Rechi** [comment]
@hudokkow @wsnipex updated
please have a look again

**Comment by Rechi** [comment]
jenkins build this please

**Comment by Rechi** [comment]
jenkins error, so jenkins build this please again

**Comment by Rechi** [comment]
signed of by @hudokkow and @wsnipex

**Pull request merged**
