### PR TITLE
Revert "[gui] Show a dvd/bluray icon for dvd/bluray folders."

### PR DESCRIPTION
**Pull request by ace20022**
Reason: https://github.com/xbmc/xbmc/pull/14418/files#r219587203

### CODE REVIEW

**Review by ksooo — APPROVED** [review]
See https://github.com/xbmc/xbmc/pull/14418/files#r219587203

**Comment by MartijnKaijser** [comment]
I guess there's no cached data we can use to see if it's a Blu-ray or DVD instead of checking disk each time?

**Comment by ace20022** [comment]
> I guess there's no cached data we can use to see if it's a Blu-ray or DVD instead of checking disk each time?

Currently not, at least I'm not aware of any.

**Comment by MartijnKaijser** [comment]
Maybe something from the database or we should add perhaps.
Anyway merge when ready

**Pull request merged**
