### PR TITLE
videorefclock: fix deadlock in glx method

### PR DESCRIPTION
**Pull request by FernetMenta**
fix http://trac.kodi.tv/ticket/15919
deadlock in video ref clock

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by miigotu** [comment]
@FernetMenta 
From the diff this doesn't change anything, it just adds erroneous brackets around the code.

**Comment by afedchin** [comment]
@miigotu this change lock scope.

**Comment by FernetMenta** [comment]
correct. the graphicsContext lock must be left before calling unregister

**Comment by fritsch** [comment]
@miigotu 

Try:
```
{
int x = 5;
}
printf(x);
```

You won't get it compiled, right? That's cause of the scope. We use those {} to automatically leave the lock without calling .Leave() and the like all the time, furthermore the object can be cleaned up automatically.

**Comment by miigotu** [comment]
I stand corrected. I should have known I was missing something there lol.

**Pull request merged**
