### PR TITLE
[xcode8] - xcode 8 and iOS SDK 10 support

### PR DESCRIPTION
**Pull request by Memphiz**
This adds support for xcode8 and building against iOS SDK 10 for our ios builds.

This also bumps the deployment target (minimum supported iOS version) to 6.0 (xcode8 doesn't work with lower targets). Thats why this has to be merged AFTER krypton was branched.

This is based on the other Xcode8 PR - so the number of commits is way less in reality.

### CODE REVIEW

**Comment by MrMC** [comment]
might need this for hdhomerun
https://github.com/MrMC/pvr.hdhomerun/commit/405f0b8cc9075aca09850020bc4a44f326fa5576

**Comment by Memphiz** [comment]
rebased @fetzerch 
@FernetMenta a comment on the needed ffmpeg change? Where should this ideally go?

**Comment by Memphiz** [comment]
@FernetMenta does this PR work for you?

**Comment by FernetMenta** [comment]
@Memphiz depends do build, cmake runs, but build in xcode fails immediately
http://pastebin.com/VdpcjjYS

**Comment by Memphiz** [comment]
any answer on my question from dec 23th above? because this PR should go into master then...

**Comment by FernetMenta** [comment]
I was able to build and run on my ipad. Regarding your question, I think the ffmpeg change should do for now.

**Comment by Memphiz** [comment]
jenkins build and merge

**Comment by Memphiz** [comment]
Jenkins Build and merge

**Comment by wang-bin** [comment]
What error to target ios5.1? Maybe I can help

**Comment by Memphiz** [comment]
@wang-bin well i doubt that you can do anything about it - but if you have some spare time you are welcome to give it a shot ;)

**Comment by wang-bin** [comment]
What build errors? I wrote a video player in c++11.  it can be build with latest xcode and run on my ios5 device. I hope i can still use kodi on my ios5 device

**Comment by Memphiz** [comment]
Simply try to compile your video player with deployment target iOS 5.1 on Xcode8.x 
Kodi needs iOS 6.0 anyway as of version 17 because we use VTB Decoder in ffmpeg now which needs the VideoToolBox Framework which can't be used when targeting lower ios targets. So you are out of luck with your iPad1 (which i suppose you use when you want to have iOS5).

**Comment by wang-bin** [comment]
I use ffmpeg vtb too. But I disable it on ios<8.0 at runtime and use software decoding. It works fine except cpu load is high. I use xcode8.2.1 and target is ios5.0.
BTW, how does kodi<17 use hardware accelerated decoding?

**Comment by Memphiz** [comment]
By directly loading the dylib during runtime - even from the private framework path. Well whatever - what exactly do you need from me to have a look? I can't remember the error messages i got and have nit much spare time atm.

**Comment by wang-bin** [comment]
How to build kodi for ios? I can have a try.

**Comment by Memphiz** [comment]
https://github.com/xbmc/xbmc/blob/master/docs/README.ios.md

You need to revert https://github.com/xbmc/xbmc/commit/9aa0d9e17a4b8bb9ff4122204c5f1aac8a1cc3df

**Pull request merged**
