### PR TITLE
cmake: add platform directory and parsing of platform specific definitions

### PR DESCRIPTION
**Pull request by Montellese**
These two commits are taken from #6227 and add support for platform-specific defines specified in `project/cmake/platform/<platform>/defines.txt` which are then stored in `ARCH_DEFINES` and passed to all addons and their dependencies being built.
The defines added here are taken from https://github.com/xbmc/xbmc/blob/master/m4/xbmc_arch.m4.

### CODE REVIEW

**Comment by Montellese** [comment]
Let's check @Memphiz's jenkins skills: jenkins build addons please

**Comment by FernetMenta** [comment]
this is really cool!

**Comment by Montellese** [comment]
@wsnipex: Since this is your idea I'm guessing you're ok with it?

**Comment by wsnipex** [comment]
obviously :)

**Pull request merged**
