### PR TITLE
[jenkins] buildsteps update

### PR DESCRIPTION
**Pull request by Memphiz**
As we discussed in the internal forum.

This PR:
- removes unused linux32 buildsteps
- removes osx32 buildsteps (i removed the osx32 jenkins job too)
- adds evaluation of the new jenkins env var BUILD_BINARY_ADDONS (jobs updated accordingly).

Before we merge this i will do some trigger tests with this PR...

### CODE REVIEW

**Comment by Memphiz** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
jenkins build this please with addons

**Comment by wsnipex** [comment]
great :)

**Comment by Memphiz** [comment]
Looked good ... merging ... (from now on the nightly builds should have the current addons in it again ...)

**Pull request merged**
