### PR TITLE
[Omega] Beta1

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Omega Beta 1 Release

## Motivation and context
Omega Beta 1 Release

## What is the effect on users?
Omega Beta 1 Release

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by basilgello** [comment]
```
[ RUN      ] TestHTTPDirectory.ApacheHtmlIndex
C:\jenkins-workspace\workspace\WIN-32\xbmc\filesystem\test\TestHTTPDirectory.cpp(245): error: Value of: m_httpDirectory.Exists(CURL(GetUrlOfTestFile(TEST_FILE_APACHE_HTML)))
  Actual: false
Expected: true
[  FAILED  ] TestHTTPDirectory.ApacheHtmlIndex (20077 ms)
```

Flake?

**Comment by fuzzard** [comment]
Yeah

**Comment by garbear** [comment]
Intentional to replace 4k with 1080p splash/media? One of those images also got significantly larger.

**Comment by fuzzard** [comment]
Yes, it's all we actually have from sam. The 4k one was an early draft that I used before he was able to do all the media.
As for the website size thing, something needs to be sorted with handling a separate image for webos. All we have re media is jpg, I had to convert to png (gave like an almost 5mb png) then compress. So if someone has a better workflow, and ideally a way to not have to have two separate images, please come forward

**Comment by sundermann** [comment]
Unfortunately we need a png image. The last time I used `pngcrush -brute -ow` to reduce the image size. Alternatively we could automatically convert the png image (is imagemagick still a thing?) from the normal splash screen (or the other way round because png is lossless)

**Comment by fuzzard** [comment]
I would definitely be keen on a packaging step to handle it.

**Comment by enen92** [comment]
I am wondering if we can't simply switch to a splash.png for all platforms instead of having the two versions. A quick look at the code seems to point we already look for both extensions anyway: 
https://github.com/xbmc/xbmc/blob/90b8fcf797e578f1d0cbbbfd7898e7ba1839c16b/xbmc/Util.cpp#L517

Or am I missing something?

**Comment by fuzzard** [comment]
I'll leave that for someone to test not on the day I'm trying to get a release done ;)

**Comment by sundermann** [comment]
Is Android the only other platform that needs a splash image?

**Comment by enen92** [comment]
> I'll leave that for someone to test not on the day I'm trying to get a release done ;)

what about yolo? :)
(it was just a curious question, something to take a look later)

**Comment by fuzzard** [comment]
There's already a very large yolo that's going to happen with Android for this, ill save my sanity for that over an image file

**Pull request merged**
