### PR TITLE
Refactor of CFileCache

### PR DESCRIPTION
**Pull request by thebrid**
## Description
Remove a couple of functions which are never called

## Motivation and Context
Small code simplification.

## How Has This Been Tested?
TBD - will be running locally on x84_64 Ubuntu 18.04.

## Screenshots (if appropriate):
N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by arnova — APPROVED** [review]

**Comment by arnova** [comment]
Nice catch, strange that I never noticed that stuff was unused.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
This can be even more simplified. As now there is no more possiblility to set m_pCache from outside, the instance is always the owner of m_pCache and `m_bDeleteCache` is alwas true, which means, this member can be removed and there is no need to `reset()` m_pCache in dtor.

**Review by ksooo — CHANGES_REQUESTED** [review]
Needs a bit more love. ;-)

**Comment by thebrid** [comment]
Good shout @ksooo! I've updated with the changes you requested.

**Review by ksooo — APPROVED** [review]
Thanks.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Pull request merged**
