### PR TITLE
[android] Show all cpus in debug overlay

### PR DESCRIPTION
**Pull request by razzeee**
Not exactly my favorite fix. But everything else would lead to redoing the whole method.

Might break if there are different cores with different specifications?

@koying @MartijnKaijser @a4840639

### CODE REVIEW

**Comment by koying** [comment]
The problem is that not all CPU's are identified, right?
And this PR "force" them, leading to proper # of cpus and proper stats in "O", also right?

If so, +1. One less whining topic from users ;)

**Comment by Razzeee** [comment]
Well number of cpus was fixed by https://github.com/xbmc/xbmc/pull/9119
But the cores we're not configured. So this assumes that all missing processors have the same core/settings as  number 0.

**Comment by koying** [comment]
Assumption seems fine. 
No risk of crash in the special cases where core are not the same?

**Comment by Razzeee** [comment]
Not sure what will happen then. I think I don't have a device to test that.

**Pull request merged**
