### PR TITLE
[dvdread] fix warning 'gcc_struct' attribute directive ignored

### PR DESCRIPTION
**Pull request by vpeter4**
## Description

fix warning
```
[1223/1666] Building CXX object build/utils/CMakeFiles/utils.dir/DiscsUtils.cpp.o
In file included from ../xbmc/cores/VideoPlayer/DVDInputStreams/dvdnav/nav_types.h:19,
                 from ../xbmc/cores/VideoPlayer/DVDInputStreams/dvdnav/dvdnav.h:35,
                 from ../xbmc/cores/VideoPlayer/DVDInputStreams/DllDvdNav.h:15,
                 from ../xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamNavigator.h:17,
                 from ../xbmc/utils/DiscsUtils.cpp:14:
../xbmc/cores/VideoPlayer/DVDInputStreams/dvdnav/ifo_types.h:33:60: warning: 'gcc_struct' attribute directive ignored [-Wattributes]
   33 | #define ATTRIBUTE_PACKED __attribute__((packed, gcc_struct))
      |                                                            ^
../xbmc/cores/VideoPlayer/DVDInputStreams/dvdnav/ifo_types.h:66:3: note: in expansion of macro 'ATTRIBUTE_PACKED'
   66 | } ATTRIBUTE_PACKED dvd_time_t;
      |   ^~~~~~~~~~~~~~~~
```
this is because 'gcc_struct' being undefined for arm

same warning comes also from libdvdread sources: https://github.com/xbmc/libdvdread/blob/329ec88257ecaf64a3144644a423289bb3da8ef6/src/dvdread/ifo_types.h#L33
I can send PR there too if this one will be accepted.

## Motivation and context

cleaner compile output to easily spot other real warnings and errors

## How has this been tested?

Compile and runtime on CoreELEC.

## What is the effect on users?

N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by vpeter4** [comment]
To where? Here https://code.videolan.org/videolan/libdvdread ?
File ifo_types.h in kodi is get from libdvdread?

**Comment by vpeter4** [comment]
Looks like already openened issue without much attention: https://code.videolan.org/videolan/libdvdread/-/issues/19
Will pass on this then (would be waste of more time).

**Comment by fuzzard** [comment]
@enen92 I'm looking to merge this as this is intermittently being flagged and causing warning threshold failures for ci jobs (webos, arm Linux)

**Comment by enen92** [comment]
Yeah no issues and I am no authority here :)

**Review by fuzzard — APPROVED** [review]
Merging this to remove warning causing CI threshold failures currently. As mentioned, ideally this needs to be upstreamed to videolan repo, and not the XBMC fork you mentioned.

Libdvd stuff doesn't change that much currently, so I think we just take this as is for now

**Comment by vpeter4** [comment]
Send MR to upstream: https://code.videolan.org/videolan/libdvdread/-/merge_requests/45

**Comment by fuzzard** [comment]
Appreciated

**Pull request merged**
