### PR TITLE
Fix Thumbnails of Rotated Pictures

### PR DESCRIPTION
**Pull request by CrystalP**
## Description

When saving a thumbnail, the function Orientate() switches width and height for the 90, 270, Transpose and TransposeOffAxis transformations and the stride needs to be adjusted to the new width.

commit 1 reverts a part of commit fa93cb0 that introduced dimension alignment to 16 bytes.

commit 2 fixes additional stride and alignment related issues and finishes the change started by fa93cb0:
When the width of the picture is not a multiple of 16, padding is added, which needs to be added to the width of the picture in all orientation algorithms. Otherwise the image looks corrupted. Stride is also recalculated in the transformations that swap width and height.

The two commits could be combined into one. I split in two commits because the first is very small and could be backported without issue, the second one is more complex and most pictures have aligned dimensions, avoiding the issue. Could still be backported IMO.

## Motivation and context

Noticed corruption in the Pictures and saw it reported recently in the forums (https://forum.kodi.tv/showthread.php?tid=371435)

While fixing the rotation problem I noticed flaws in the code for non-aligned dimensions. Testing confirmed the problem and a corruption similar to the original issue.

## How has this been tested?

Windows 10 x64
Applied all rotation algorithms to a picture, with dimension aligned to 16 and non-aligned.

Unfortunately, already generated thumbnails remain corrupted and the user has to delete them to get them recreated.

The fix probably also applies to thumbs generated from rotated videos but I don't have examples to check.

## What is the effect on users?

Correct thumbnails for rotated pictures (pictures taken in portrait mode for example) and pictures with dimensions that are not divisible by 16.

Existing thumbnails have to be deleted in order to be recreated correctly.

## Screenshots (if appropriate):
Example of corrupted picture thumbnail:

image

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by enen92** [comment]
jenkins build this please

**Comment by enen92** [comment]
@CrystalP probably worth to backport to nexus?

**Comment by CrystalP** [comment]
@enen92 Thanks for the labels. Yes the problem appeared in Nexus and at least the first commit should be backported (common situation with very simple fix).
Commit 2 is nothing crazy but changes a lot more for a less frequent issue so it's up to you and the team whether to backport it or not.

**Comment by enen92** [comment]
Historically kodi was always against tools that remove cache files or mess with the user data files. I guess the best we can do is to warn about the issue on the blog post or something. I'll have a similar issue with the resolutions to be honest.

For the backport maybe let it land for a bit on nightlies and then backport

**Comment by CrystalP** [comment]
@enen92 sure there is no rush for a backport. Does it look OK to merge?

**Review by enen92 — APPROVED** [review]
Can't spot anything wrong in the code although I am not the best one to review this.
I'd say get it in and see who screams :)

**Pull request merged**
