### PR TITLE
[cleanup] wayland

### PR DESCRIPTION
**Pull request by stefansaraev**
wayland support is unmaintained, and heavily depends on boost.

fyi @FernetMenta

### CODE REVIEW

**Comment by FernetMenta** [comment]
+1
jenkins build this please

**Comment by a1rwulf** [comment]
Maybe dump question:
Will Wayland still replace X in the future?

**Comment by fritsch** [comment]
@a1rwulf yes it will. Remember "revert" is always an option. If someone wants to work on wayland he can exactly start with this code.

**Comment by a1rwulf** [comment]
+1 then :)

**Comment by FernetMenta** [comment]
http://wayland.freedesktop.org/faq.html#heading_toc_j_4

nobody knows when and how. I don't think OpenGL will be dropped in favour of GLES. Means this code needs to support OpenGL too. I don't think "revert" of the drop will ever be an option but github don't forget this code and snippets can be reused.

**Comment by MaxKellermann** [comment]
FYI: I will revert this (undocumented!) commit in my Kodi fork, because I was about to switch my Kodi box to Wayland. Then I will fix all occurring issues. Just in case somebody's interested in my code, you know where to find it.

**Comment by FernetMenta** [comment]
thanks. good to know.are you going to drop boost from this code?

**Comment by MaxKellermann** [comment]
From a first glance, it looks like Kodi's Wayland code uses only Boost libraries that were obsoleted by C++11. With some time (and confidence that you're going to merge it), I'll replace that, but that's a minor priority. My goal is to make it work and make it stable, and removing Boost doesn't help with that goal.

**Comment by FernetMenta** [comment]
I would redesign this from scratch, maybe reuse some code. Under windowing Wayland needs to be at the level of X11, OSX, Windows, not in the mess of egl. It should be ready to support OpenGL and GLES. The current limitation of GLES only makes it pretty useless for most systems because neither VAAPI nor VDPAU work.

**Comment by fritsch** [comment]
VAAPI can be made working, nvidia can't even without X11 dependencies.

2016-01-30 9:52 GMT+01:00 Rainer Hochecker <notifications@github.com>:

> I would redesign this from scratch, maybe reuse some code. Under windowing
> Wayland needs to be at the level of X11, OSX, Windows, not in the mess of
> egl. It should be ready to support OpenGL and GLES. The current limitation
> of GLES only makes it pretty useless for most systems because neither VAAPI
> nor VDPAU work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/xbmc/pull/8980#issuecomment-177107588>.
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by FernetMenta** [comment]
> VAAPI can be made working

theoretically. in our code VAAPI rendering is bound to OpenGL. do you want to move this to GLES? have fun :)

**Comment by fritsch** [comment]
Nope - I just have the fun of my life with the current project ...

**Comment by MaxKellermann** [comment]
How is EGL a mess? EGL is a perfectly fine way to initialize OpenGL or GLES on Wayland. Actually, it is THE ONE way to do it. See http://wayland.freedesktop.org/faq.html

Does anybody here believe that Wayland is limited to GLES, and cannot use OpenGL? That would not be true.

There's a lot of wrong and overly complicated in Kodi's EGL initialization code, yes. It's a fragile and bloated mess of spaghetti code. But there's nothing wrong with EGL itself.

**Comment by MaxKellermann** [comment]
I can now run Kodi on Wayland + EGL + GLES2. Fixes are in my fork's master branch (https://github.com/MaxKellermann/xbmc).

**Comment by lrusak** [comment]
@MaxKellermann thanks for updating wayland in your branch. I maintain an OpenELEC version that is using wayland. see https://github.com/lrusak/OpenELEC.tv/tree/wayland

Using your branch I was able to get Kodi built with VAAPI support on wayland. However I don't have any intel graphics so I am unable to test. If anyone would like to test the build is available at https://openelec.freestylephenoms.com/wayland/

Hopefully we can work at getting Wayland support back into Kodi ;)

**Comment by MaxKellermann** [comment]
I run Kodi on a NUC with an Intel GPU. I havn't tested Wayland+VAAPI yet, but I will soon. If it doesn't work, I'll fix it.

**Comment by lrusak** [comment]
@MaxKellermann I had another OpenELEC team member test your wayland build with my OpenELEC build. The results are good and not so good.

https://github.com/lrusak/OpenELEC.tv/issues/1

Let's take the conversation over there to avoid spamming everyone here.

**Comment by MaxKellermann** [comment]
Upon @FernetMenta's request, I removed Boost from the Wayland code, replacing with standard C++11 - except for boost::scope_exit and boost::tokenizer.

**Comment by MaxKellermann** [comment]
After fixing @lrusak's problem (https://github.com/MaxKellermann/xbmc/commit/f693ebc4), video playback works very well with Wayland/EGL+GLES2+VAAPI on my NUC with Intel GPU. My fix is not specific to Wayland, but was an incomplete shader implementation that affects all GLES2 platforms, but was never visible, because apparently only VAAPI uses that YUV encoding. You're welcome to cherry-pick that bugfix (or cherry-pick many more of my commits).

**Comment by FernetMenta** [comment]
I consider this more a feature than a fix because I implemented NV12_RRG for vaapi only and vaapi is only available for OpenGL (in master)
If anybody wants to re-submit wayland, it has to comply to the architecture. That is no components under the folder windowing/egl, no boost.

**Comment by MaxKellermann** [comment]
Let's get this project started by merging my VAAPI+GLES2 and VAAPI-without-X11 patches. These are not specific to Wayland - they may be used as well by a (future) DRM windowing implementation. I'll write one, which is useful for appliances which do nothing but run Kodi full-screen. No X11, and no Wayland. Just Kodi on an accelerated frame buffer.

**Comment by FernetMenta** [comment]
> Let's get this project started by merging my VAAPI+GLES2 and VAAPI-without-X11 patches

Without the changes that trigger this path it would be dead code. I am not sure how many lines of code I had to clean up because of code implemented for future use. I even have an active PR of that category: https://github.com/xbmc/xbmc/pull/9035/files
Neither the return value nor the parameter of PresentRender were ever used. I hope you understand this.

**Comment by MaxKellermann** [comment]
Would you merge the VAAPI improvements when accompanied with a new KMS/DRM windowing patch?

**Comment by FernetMenta** [comment]
If it fits into architecture and is implemented correctly, there is no reason to reject it.

**Comment by MaxKellermann** [comment]
Is there documentation on the architecture?

**Comment by MaxKellermann** [comment]
I'm curious about Wayland: you said it's wrong to have "components under the folder windowing/egl". But there are many specific sources in windowing/egl, for:
- Android
- Raspberry Pi (= VideoCore)
- Amlogic
- IMX
Why do these sources live under windowing/egl? I tried to find some logic behind this, but can't seem to, without explanation/documentation.

**Comment by MaxKellermann** [comment]
Would this suffice to make Wayland architecture-compliant? https://github.com/MaxKellermann/xbmc/commit/fa5deed59fd4

If yes, I'll replace boost::tokener and boost::scope_exit quickly, and let you merge it.

**Comment by FernetMenta** [comment]
All the platforms you mentioned need a change in this area. EGL is not a windowing system. This is probably most obvious when you look at X11 that can use glx and egl.
Windows, X11, OSX do it correctly. iOS, @Memphiz , should really not be located under a folder named osx. 

> Would this suffice to make Wayland architecture-compliant? MaxKellermann@fa5deed

No. Consider everything located under windowing/egl as dead.

**Comment by FernetMenta** [comment]
@MaxKellermann it should look like this:

class CWinSystemWayland : public CWinSystemBase, public CRenderSystemGLES

**Comment by MaxKellermann** [comment]
Let me summarize what I understood:
- Wayland was removed because it's unmaintained and violates the Kodi architecture
- the majority of windowing systems violate the Kodi architecture (4 broken, 3 correct)
- so far, nobody fixed the majority of windowing systems => they are unmaintained
- nobody removed those broken windowing systems
- Wayland can't be readded because it is just as bad as the majority of windowing systems, the ones which are still there

I'm not sure how this situation can be resolved. Going without the existing EGL code means an acceptable Wayland implementation would need to duplicate all of the existing EGL code, just in a cleaner way. IMHO, that would be a very bad choice. It would bring Kodi EGL development to a halt (which happened already, obviously), because no new code will be accepted.

I would prefer merging Wayland as it is -- just as bad as most of the existing code! -- and then incrementally improve the EGL situation.

If you don't merge Wayland, I will not be available for EGL improvements in upstream Kodi. With the "bad" architecture, Wayland works well enough for me and my fork. The bad architecture is really your problem. I can live with that. If someday somebody fixes (upstream) Kodi, my fork will be rebased on this new solution.

**Comment by Memphiz** [comment]
@FernetMenta you are right - it should be either osx and ios or darwin/osx and darwin/ios (like in the platform folder) - i can clean this up - other then that i don't think ios breaks architecture by its implementation...

**Comment by MaxKellermann** [comment]
I eliminated the two remaining Boost uses from the Wayland code. Is that enough for getting Wayland back in upstream Kodi?

**Comment by FernetMenta** [comment]
I won't accept any dependencies of Wayland to existing windowing/egl. Did you change this as well?

**Comment by MaxKellermann** [comment]
No. This kind of code refactoring should be done after Wayland is back. It makes no (long-term) sense to refactor only the Wayland code and keep all the others broken as they are. The easiest way to fix them all is incrementally refactor the code to a clean state - all of it.

**Comment by FernetMenta** [comment]
I don't debate on this. It's is easier to refactor the existing egl code if Wayland is not part of it.

**Comment by MaxKellermann** [comment]
It is only easier because it's just 4 broken targets instead of 5. Duh!

And of course it's easier for me to fix just Wayland, because that's just 1 broken target instead of 5. But that misses the point I tried to make. Because the latter would mean 4 broken targets remain.

I'm a bit dazzled why you prefer me to fix only Wayland, and leave the rest broken.

**Comment by FernetMenta** [comment]
The rest is not broken, it's just a bad design. You could first rework the design of egl and then adapt Wayland to it, fine.

**Comment by MaxKellermann** [comment]
I agree that it's badly designed. The Wayland code isn't worse than the rest - it is just as bad as the majority of existing Kodi windowing targets.

Looks like we really have a heavy and unresolvable disagreement on how this should be done. I won't do it your way, and you refuse to accept/merge my way. I tried hard, but fail to grasp your descisionmaking.

I give up. I'll stop trying to convince you. Sorry for dragging you into another debate.

**Comment by da-anda** [comment]
@MaxKellermann please don't get it wrong. Your contribution is welcome in general, but we, and especially FernetMenta, are currently fighting with the codebase and try to untangle the mess. Every new PR therefor should not be based on code that is seen as obsolete, because it will it make even harder to untangle and fix things. And as mostly only FernetMenta is doing this unthankful job atm, we respect his decisions. This has nothing to do with you not being a team member, this applies to all PRs, regardless who does them.

Is this frustrating for contributors of new features in affected areas? Very likely. But the current architectur became unmaintable with all the stuff added over time and we have to draw a line at some point. And this point has been reached. So please try understand FernetMentas position. If nobody steps up, he will be the one to fix all that stuff, and in order to ever finish this endevor, some welcome new features have to be postponed unless they meet the new architectural design/goal.

If you volunteer to rework the EGL stuff, I'm pretty sure FernetMenta is willing to help you in any way.

**Comment by MaxKellermann** [comment]
@da-anda I understand your worries. Kodi is a giant mess, and is in need of a major rewrite. I understand that going a step backwards appears like the wrong direction. Your worries are ostensibly reasonable.

In this specific case, I tried to explain how I planned to get EGL right, and why this is better to get the old code back first, before doing the actual cleanup. You disagreed. I explained why it's important for me to do it that way. You rejected this. That was your decision.

I won't change my mind about this - I'll just leave the EGL mess up to you, and care for my other projects, no big deal. Just in case you change your minds, just tell me.

**Comment by smspillaz** [comment]
Hey, as the original author of this code (or mess), just wanted to drop a thanks to @MaxKellermann for maintaining it.

I agree that most of the boost stuff can be dropped if C++11 is the new build target.

I'm also happy to offer my help if its needed.

**Comment by MaxKellermann** [comment]
@smspillaz already done. In my repository, I have replaced all Boost dependencies with their C++11 counterparts. No Boost required for Wayland.

**Comment by smspillaz** [comment]
@FernetMenta I might be able to volunteer to clean up the EGL stuff. I remember I was going to look at it some time ago and then life happened.

Back when I worked on this backend, I actually implemented it as a separate window system. I was told that it needed to go into egl/, so I put it into egl/.

I think the architecture that makes more sense is to consider the stuff in `egl/` as a "support" library for the rest of the backends. That's how its meant to work anyway. You create a native window on the windowing system and then use a platform native API to get an EGL surface from that. Then you call into EGL and create a context.

Ideally, all the stuff in `WinEvents` needs to be merged back into their constituent windowing backends too. Its a bit of an artificial separation.

Let me know if you wanted to discuss more over IRC as to how it should be done.

**Comment by FernetMenta** [comment]
@smspillaz  good to hear from you again. Would be great if you could work on this. What timezone are you currently staying? Did you join our Slack channel already?

**Comment by smspillaz** [comment]
@FernetMenta Likewise! I haven't joined the slack channel yet, though I'm in the IRC channel. I'm currently GMT+8

**Comment by FernetMenta** [comment]
Update: Wayland does support OpenGL. This makes it even more clear that it makes no sense having it under the crappy EGL tree that is tied to GLES.
It is likely that Wayland will be back in v18.

**Comment by MaxKellermann** [comment]
So, what's your plan for bringing Wayland back? And what with the other existing ports still using the crappy EGL tree?

**Comment by FernetMenta** [comment]
> So, what's your plan for bringing Wayland back?

The plan for the architecture has not changed. Wayland needs to be implemented as its own windowing system like X11, OSX, or Windows. Further it needs to support OpenGL in the first iteration.

> And what with the other existing ports still using the crappy EGL tree?

That is a different story and not related to Wayland. Common code related to EGL can be factored out later.

**Comment by MaxKellermann** [comment]
My past suggestion was to re-add the old Wayland code and then incrementally refactor all of the existing EGL code, in order to make them all conform to your (yet-to-be-defined) architecture. You rejected that approach back then. Is that still your opinion, or did you change your mind meanwhile?
(I'd like to help, but I will not help with starting from scratch, throwing away all of the existing (working) code for 5 windowing systems. I think that's an unnecessary waste of time.)

**Comment by MaxKellermann** [comment]
That does answer my question. Your plan describes only the final goal, not how you achieve it.
But I take this as "you didn't change your mind, and you don't want me to help". Ok.
Anyway, Wayland support in vanilla Kodi is good news. I'm looking forward to see your new code.

**Pull request merged**
