### PR TITLE
[texturepacker] bump version after last fixes

### PR DESCRIPTION
**Pull request by un1versal**
@Montellese 

After https://github.com/xbmc/xbmc/pull/7694 and https://github.com/xbmc/xbmc/pull/7810 texturepacker was rebuilt/fixed and updated to 1.0.3 but win32 project was never bumped accordingly.

I wanted to test actually compiling it myself but it seems compiling on Windows is a task for the ages.

Ideally we would merge this, recompile the 1.0.3 with correct version and upload it to mirrors.

### CODE REVIEW

**Comment by uNiversaI** [comment]
PING @Montellese compiling of texture packer on windows fails with winres.h not found after https://github.com/xbmc/xbmc/commit/a177113bd44cdce1836dbab7e67bf38a57a42945

**Comment by Montellese** [comment]
@uNiversaI: Without that commit my system can't find `winres.h` in VS 2013. Furthermore an additional include path (I added one, not removed one) shouldn't change the headers found by your system because it would still look into all the other places as well.

**Comment by uNiversaI** [comment]
@Montellese well here it fails completely, I must admit Im very inexperienced with windows compiles, I opened the solution it loads, I clicked the batch files to install the dependencies and setup accordingly to instructions and it fails with error that ***cant open winres.h***

**Comment by Montellese** [comment]
Did you verify that it works without a177113? Are you building debug or release? I think I forgot to adjust the debug build and only updated the release build.
I just verified that without that commit I have the same issue on another machine as well so at least on the machines where I have VS installed it seems to be needed.

**Comment by uNiversaI** [comment]
Release only and no I haven't verified it, I dont think I will be able to test that as soon as I would like though.

Its half the job if you can duplicate it at least.

**Comment by Montellese** [comment]
Release build is working fine for me with a177113 and fails without it. Debug build works neither with nor without a177113 because I only adjusted the release build in that commit.

In case you get time to test it again you could also give https://github.com/Montellese/xbmc/commit/5be269af8af92d5eb1836476e0de556ff0c3490b on top of a177113 a try (this covers both debug and release build).

I'd like to wait with bumping the version number until this has been resolved. Furthermore there seems to be another issue with some images that didn't exist before.

**Comment by uNiversaI** [comment]
Of course, soon as I can I will test and get back to you with feedback. Thanx for reply and test fix.

**Comment by uNiversaI** [comment]
@Montellese with https://github.com/Montellese/xbmc/commit/5be269af8af92d5eb1836476e0de556ff0c3490b ontop of https://github.com/xbmc/xbmc/commit/a177113bd44cdce1836dbab7e67bf38a57a42945

```Error	5	error LNK1181: cannot open input file '..\..\..\..\..\..\project\VS2010Express\libs\squish\Release\squish.lib'	C:\Kodi\tools\depends\native\TexturePacker\src\Win32\LINK	TexturePacker```

For both Debug/win32

**Comment by uNiversaI** [comment]
replaced by #7961

**Pull request closed without merging**
