### PR TITLE
[pvr.hts] bump to https://github.com/kodi-pvr/pvr.hts/commit/f11a84f6deb8609fa47a39b49c2b729d50a9b5b0

### PR DESCRIPTION
**Pull request by opdenkamp**
instead of building from a commit while in development, until branched off

### CODE REVIEW

**Comment by Montellese** [comment]
This doesn't work with the current buildsystem because we cache the downloaded sources based on their branch/revision name and since "master" is always the same we never re-download the code.

**Comment by opdenkamp** [comment]
meh :)

**Comment by opdenkamp** [comment]
changed to just bump the add-on, so it builds after the API changes

**Comment by opdenkamp** [comment]
and since add-on builds can no longer fail jenkins and this already fails to build now, merging

**Comment by opdenkamp** [comment]
heh too trigger happy, it built, but i never installed the new version, and it's missing symbols after guilib changed

**Comment by Montellese** [comment]
I'm not sure if using a branch name would be the best idea because there'd be no way of knowing which revision made it into which build. The only clue you'd have is the addon's version but if you have multiple commits between versions there's no way to really know.

**Comment by FernetMenta** [comment]
We need to distinguish between development on master and a release branch. assume an addon dev wants to fix an issue reported in the forum. if the reporter con't build himself, he needs to try nightlies and report back. this feedback loop should not have obstakels like bumping versions and send pull requests.

**Comment by Montellese** [comment]
How is this any different than it was before? Before PVR addons were integrated into the binary addons buildsystem we also always built the PVR addons from a specific revision of the `xbmc-pvr-addons` repository. That seems to have worked fine for years.

**Comment by opdenkamp** [comment]
It's the same as it used to be indeed, though @FernetMenta and I talked about this, and thought that it would be nice if we could point to a master branch during development, and only switch to using revisions when branching.

**Pull request merged**
