### PR TITLE
[json-rpc] add "withsound" arg to GUI.ShowNotification, change min ti…

### PR DESCRIPTION
**Pull request by lameventanas**
json-rpc:
- add "withsound" argument to GUI.ShowNotification
- change minimum display time to 1 second

### CODE REVIEW

**Comment by Montellese** [comment]
The `"withsound"` parameter is ok but changing the implementation of `GUIDialogKaiToast` will affect the duration of every notification that is being shown within Kodi which is mostly unrelated to JSON-RPC and IMO an unnecessary change in behaviour.
Either way you need to bump the minor number of the JSON-RPC API version in `xbmc/interfaces/json-rpc/schema/version.txt`.

**Comment by MartijnKaijser** [comment]
Python API should also be changed to reflect same option

**Comment by alan-ml** [comment]
Thanks for the pointer, I increased the minor version number of the json-rpc api.

**Comment by alan-ml** [comment]
@MartijnKaijser the [Python API](http://mirrors.kodi.tv/docs/python-docs/16.x-jarvis/xbmcgui.html#Dialog-notification) already has this option.

**Comment by Razzeee** [comment]
@lameventanas are you still interested in this?

**Comment by lameventanas** [comment]
I am interested, and I think the APIs should be consistent.

**Comment by Razzeee** [comment]
can you drop the change to the notification length?

and rebase?

**Comment by lameventanas** [comment]
Sure, but I'll need a couple of weeks, since I'm on a trip now.

**Comment by Razzeee** [comment]
Sure, take your time :)

**Comment by Rechi** [comment]
@lameventanas this needs a rebase

**Comment by MartijnKaijser** [comment]
I will close this PR. If there's interest please open a new one (with required changes if needed).

**Pull request closed without merging**
