### PR TITLE
Add tests to windows, that weren't added to the test project

### PR DESCRIPTION
**Pull request by razzeee**
This tries to get improve the number of tests run on windows. Keep in mind that not every test is for each platform so differences in test numbers aren't that bad.

OSX Tests
`Running 594 tests from 90 test cases.`

Linux Tests
`Running 579 tests from 89 test cases.`

Windows Tests before this PR
`Running 472 tests from 63 test cases.`

Windows Tests after this PR
`Running 571 tests from 87 test cases.`

I also removed the dedicated xbmcThread-Test project, as I moved those tests to the main application. Not sure why they were seperate. @jimfcarroll might know.

### CODE REVIEW

**Comment by Montellese** [comment]
I guess the thread tests are in a separate project because the thread implementation is in a separate project.

**Comment by Razzeee** [comment]
Well but it's probably imported to the main project. So the tests run fine? Also they are just separated for windows correct?

**Comment by Razzeee** [comment]
So is removing the thread-test project something we want? Or should we just make sure it's executed, when the testsuit runs? (not sure how to do that)
If we choose to leave it in, it's weird as it's different for all other platforms.

**Comment by jimfcarroll** [comment]
@Razzeee they were separate because they were first. I guess you could ask why everything else was separate :-)

**Comment by Razzeee** [comment]
So do we want to merge this? Effectively getting rid of the dedicated thread test project and moving the tests into the big testsuite we have. This affects windows only, as all other platforms already handle it that way, if I don't missunderstood jenkins.

**Comment by jimfcarroll** [comment]
Yeah sorry. I'm all for organizing it better.

**Comment by Razzeee** [comment]
jenkins build this please

**Comment by Razzeee** [comment]
jenkins build was fine, I just triggered a test build http://jenkins.kodi.tv/view/Helpers/job/TestMulti-All/508/

**Comment by Razzeee** [comment]
Tests also built fine

**Pull request merged**
