### PR TITLE
[addons] change db version 21 update to set system addons to disable

### PR DESCRIPTION
**Pull request by tamland**
This fixes an issue with the 21 update done in #9051 as discussed in http://trac.kodi.tv/ticket/16658.
Since it's not possible to differentiate between enabled addons in version 20 and addon part of the new install, there is no way to know if it should be enabled or disabled.

As discussed, enabling something user didn't enable seems like the worse case. To ensure that doesn't happen (and doesn't happen again in the future) the best solution is to set all addons that comes from the system directory to disabled in this migration.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
So now all system addons get disabled by default?

**Comment by MilhouseVH** [comment]
> the best solution is to set all addons that comes from the system directory to disabled in this migration.

That doesn't sound right - disabling everything in `/usr/share/kodi/addons` would probably result in a non-starting Kodi as it fails due to addons-manifest.xml problems.

Ultimately the problem is that PVR addons can be enabled in v20 but inactive because LiveTV is disabled. Once LiveTV is done away with (with v21, or was it v22?), all those previously inactive PVR addons suddenly cause mayhem. Special casing PVR (and possibly audioencoder?) addons during the v20 -> v21 migration would solve this problem - not ideal, but better than disabling everything.

**Comment by tamland** [comment]
It wont affect any of the required addons that are in the manifest. 

>Special casing PVR (and possibly audioencoder?) addons during the v20 -> v21 migration would solve this problem - not ideal, but better than disabling everything.

And in a year or so when someone adds another similar 'problematic' addon type, this update will be to be fixed again. That's why it's better to disable all.

**Comment by MilhouseVH** [comment]
If you say it's not going to cause a problem, OK...

**Comment by tamland** [comment]
By 'all' I meant 'all except those in the manifest' sorry;) The required addons will just be initialized to disabled and will be corrected after the database update once it's known which those are.

**Comment by da-anda** [comment]
stupid question, can't we read out all enabled addons prior to the update, then perform the update and restore the old state? Or will this also become subject of abuse (reverting DB version by wizards to force the upgrade path)

**Comment by tamland** [comment]
jenkins build this please

**Comment by tamland** [comment]
@da-anda I think you misunderstood what this is. There is no record of enabled addons int the old database. This is about a best-effort solution that tries to migrate from that to the new database which does. Not sure what 'wizards' have to do with anything..

**Comment by da-anda** [comment]
@tamland, but there has to be some record of currently enabled add-ons somewhere, as installed != enabled. But yeah, I probably got that wrong.

**Comment by tamland** [comment]
Only which were explicitly disabled.

**Pull request merged**
