### PR TITLE
paplayer: fix gapless playback

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

http://forum.kodi.tv/showthread.php?tid=250744

### CODE REVIEW

**Comment by fritsch** [comment]
That thingy gets more ugly over time with every commit. The special casing in all its places makes it kind of unmaintainable. 

Rewrite for v18? :-)

**Comment by FernetMenta** [comment]
I won't hold you back if you like to do so.

**Comment by FernetMenta** [comment]
I won't hold you back from looking into this either :)

**Comment by arnova** [comment]
I've been using videoplayer (previously dvdplayer) for music playback since the Xbox age. For me it's the only way to get guaranteed stutter-free playback (and I don't care for gapless/crossfade). So +1 from me.

**Comment by fritsch** [comment]
The stutter should be fixed, btw since 1.5 years now. Mind retrying?

Am 05.10.2016 12:35 nachm. schrieb "arnova" <notifications@github.com>:

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by fritsch** [comment]
Background: the stutter was a combined softae misconception and in thread next song queing issue by paplayer.

**Comment by popcornmix** [comment]
Stutter is very common with audio when using paplayer with a slow network, like wifi.
This is because paplayer has no buffering unless you set buffermode=1.
VideoPlayer avoids this as it has substantial internal buffering.

**Comment by arnova** [comment]
@fritsch : I'll give it another try. @popcornmix : I'm aware of that, but in this case it concerned local (hdd) playback. And like I said it dates back to the Xbox age, so I'm not 100% it's a SoftAE issue but rather a design flaw.

**Pull request merged**
