### PR TITLE
[addons][tools][build] don't use _WINSOCKAPI_ and fix addon thread stop call

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description

Commit 1:
-------------------------
**[build][windows] remove -D_WINSOCKAPI_ as can in conflict**

This brings problems by e.g. https://think-async.com/Asio/ as this need to define byself.

Commit 2:
-------------------------
**[addons][tools] fix stop freeze if used thread was not started**

Before was during call of Stop() at CThread checked that thread is in start to wait until it is done.

But it has also called the wait if them not started and wait forever as it not becomes signaled.

Commit 3:
-------------------------
**[addons][tools] increase tool version to 1.0.4**

Min version stays at 1.0.0.

Also becomes missing header file names added to versions.h to have for version check.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by AlwinEsch** [comment]
About `_WINSOCKAPI_` was come in on 17 July 2014 by https://github.com/xbmc/xbmc/pull/5055

**Review by ksooo — APPROVED** [review]
lgtm

**Review by phunkyfish — APPROVED** [review]
Nice

**Comment by AlwinEsch** [comment]
jenkins build this with addons please

**Pull request merged**
