### PR TITLE
[Isengard] fix Window.IsMedia infobool

### PR DESCRIPTION
**Pull request by hudokkow**
Backport of https://github.com/xbmc/xbmc/pull/7761

### CODE REVIEW

**Comment by hudokkow** [comment]
jenkins build and merge

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by mkortstiege** [comment]
@hudokkow please don't merge this one yet. See comments in the master PR.

**Comment by MartijnKaijser** [comment]
@ronie up to you if you want this merged or not

**Comment by ronie** [comment]
jenkins build this please

**Pull request merged**
