### PR TITLE
[addons] fix library path building

### PR DESCRIPTION
**Pull request by tamland**
Bad refactoring in f32483d60

Fixes http://trac.kodi.tv/ticket/16361

cc @garbear @ronie

### CODE REVIEW

**Comment by mkortstiege** [comment]
Looks good to me. Is there a reason it's only handled for just a few types?

**Comment by ronie** [comment]
tested and fixes the issue, thx!

**Comment by tamland** [comment]
@mkortstiege probably not, but it's how it was before the refactor (logically). And platform specific libraries doesn't really make sense for any of the other types.

**Comment by garbear** [comment]
looks good

**Pull request merged**
