### PR TITLE
[ffmpeg] Remove #ifdefs due to version bump

### PR DESCRIPTION
**Pull request by sundermann**
## Description

Since the ffmpeg version is now bumped we can safely remove any ffmpeg 6.0 ifdefs.

## Motivation and context

Less ifdefs

## How has this been tested?

macOS / ffmpeg 7.1

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
I would be wary. It is not required to run ffmpeg 7. ie linux distros do what they do

**Comment by sundermann** [comment]
The version requirement had been bumped to 7.0 during the ffmpeg update.

**Comment by fuzzard** [comment]
WITH_FFMPEG bypasses those requirements. its not a requirement for all build cases.

**Comment by sundermann** [comment]
Alright, let's hold off then for now.

**Pull request closed without merging**
