### PR TITLE
Bump gtest to 1.7.0

### PR DESCRIPTION
**Pull request by razzeee**
Updates our googletest lib from 1.6.0 to 1.7.0

Mostly for the sake of keeping it up to date. Tests still work fine on windows.

### CODE REVIEW

**Comment by akva2** [comment]
it also has a functional reason - 1.6.0 fails to build using clang 3.7 in c+11 mode.

**Comment by Razzeee** [comment]
You ment to say 1.7.0?

**Comment by akva2** [comment]
no, 1.6.0 fails to build, 1.7.0 will build.

**Comment by Razzeee** [comment]
Oh, sorry thought you we're trying to warn us to not update ;)

**Comment by wsnipex** [comment]
I'm wondering if we can move gtests to depends, where it belongs. One step closer to getting rid of /lib
Not a blocker for this PR though.

**Comment by akva2** [comment]
you will have to fight google to some extent. there is no installation target for gtest, so you'd have to either patch that in depends, or use gtest straight out of the depends folder somehow.

**Comment by Razzeee** [comment]
jenkins build this please

**Comment by Razzeee** [comment]
Builds are already gone :(

jenkins build this please

**Comment by Paxxi** [comment]
+1 keeping up to date makes it so much less painful to update the libs, except maybe for @wsnipex that gets stuck with packaging. 

Ideally we should probably start every alpha1 with lib updates much like we do with ffmpeg

**Comment by Razzeee** [comment]
Triggered a test build here:
http://jenkins.kodi.tv/job/BuildMulti-All/1147/

Only Linux-64 failed, but I that is broken since some time already. So this seems fine.

Sidenote: Android doesn't seem to run tests.

**Comment by Razzeee** [comment]
Got a jenkins build pending for this here http://jenkins.kodi.tv/view/Helpers/job/TestMulti-All/

**Comment by Razzeee** [comment]
Seems to build fine on osx and win. http://jenkins.kodi.tv/view/Helpers/job/TestMulti-All/497/
Linux died, maybe because of network problems, started another build to see if it's working now.

**Comment by Razzeee** [comment]
Builds were fine now. http://jenkins.kodi.tv/view/Helpers/job/TestMulti-All/499/
I will merge this for now, if anyone needs an bump to master for this dependency. Let me know.

**Comment by tamland** [comment]
Go for merge. Definitely would be nice to have something more recent though. I don't know their plan is, or if they even do 'releases' anymore, but there's been [plenty](https://github.com/google/googletest/commits/master) of fixes since v1.7.0 from 2013.

**Comment by Razzeee** [comment]
Well it seems like they will tag at one point.
https://github.com/google/googletest/issues/586

**Pull request merged**
