### PR TITLE
Fix state not saved after #5842 if playing from "Recently added".

### PR DESCRIPTION
**Pull request by ghost**
See:
- http://forum.kodi.tv/showthread.php?tid=210479
- https://github.com/xbmc/xbmc/pull/5842#issuecomment-67107411
- http://trac.kodi.tv/ticket/15603
- http://trac.kodi.tv/ticket/15660
## 

Playing something from "Recently added" creates a play list with a single item.  Oops.
## 

**Needs backport to Helix**

### CODE REVIEW

**Comment by piejanssens** [comment]
Saw this issue popping up in the following threads too:
http://forum.xda-developers.com/fire-tv/general/kodi-resume-playback-starts-form-t2972613
http://forum.kodi.tv/showthread.php?tid=210480

People that don't know how to compile with this fix are running the nightly's to cope with this issue atm. Moving towards 14.1 and no sign of progress in fixing this seems strange.

If I'm not mistaken this PR fixes the regression for current state of confluence recently added homescreen items or third party skin widget items, while not breaking the way-to-go method of creating a playlist for any video played even if it's a single item.

So why don't you merge this already and ping ronie to create playlists for items played from the home screen?

**Comment by MartijnKaijser** [comment]
@piejanssens it was not (yet) merged because it could cause other regressions. This needs to be pretty damn sure before it gets merged to 14.1

**Comment by piejanssens** [comment]
Who can vouch for this? @Montellese maybe?
Otherwise put it in for 14.1 RC and go for another round.

**Comment by anaconda** [comment]
> it was not (yet) merged because it could cause other regressions. This needs to be pretty damn sure before it gets merged to 14.1

What about giving this a try (this is for master) and only backport to Helix if no issues are reported. However, this has been in Milhouse builds for 3 weeks now.

**Comment by peteakalad** [comment]
Another few mentions of this bug highlighting scale of users being affected by this in support threads.  
http://forum.kodi.tv/showthread.php?tid=214157
http://forum.kodi.tv/showthread.php?tid=213265

I'm not sure the scale of this issue has been properly realised.  Starting videos from home shelf is commonplace, and this bug effectively breaks resume points for those users.  Resume points are a key feature.  

This fix missed 14.0 and it looks like its going to miss 14.1 too? :(

**Comment by Tolriq** [comment]
Did not see this PR.

But @Montellese I got hundred of reports that resume point does no more work on Kodi.
Seems starting media from JSON api have the same behavior and no resume point will be set on stop and not a problem with stop as reported in JSON thread.

This is a major break as really a lot of people does use JSON to start medias.

If I can test or validate things, please tell but this and Webserver crashses on Kodi have made lot's of users unhappy :(

**Comment by piejanssens** [comment]
Can anyone provide a windows build of the latest Helix branch with this commit patched onto it?
I tried for several hours but gave up. The wiki' win build instructions are not very good.

**Comment by NedScott** [comment]
@piejanssens if I did this right, one will be available on http://mirrors.xbmc.org/test-builds/win32/ as "Helix-fix-5842-testing" within an hour.

**Comment by NedScott** [comment]
There are builds for all platforms if other people want to test with Win, OS X, Android, or iOS. Just look for "Helix-fix-5842-testing" in the respective OS folder for http://mirrors.xbmc.org/test-builds/

**Comment by piejanssens** [comment]
I'll test Win, OS X and iOS. 

STATUS - watched status for widgets
STATUS - watched status for recently added
STATUS - watched status for movies or tv show via main library view
STATUS - resume for widgets
STATUS - resume for recently added
STATUS - resume for movies or tv show via main library view
STATUS - resume song playback
STATUS - resume album playback
STATUS - resume playlist playback

Anything missing or irrelevant for testing?

**Comment by NedScott** [comment]
Per Tolriq, also test playing back something using a smartphone/tablet remote, which should use the JSON-RPC api. In other words, use the a remote (such as Yatse) and launch the video file from the remote, rather than navigating to it on Kodi's GUI.

Since this is having a big impact on users right now, I've thrown up the Helix+Recentlyadded-fix builds in the v14.1 testing thread: http://forum.kodi.tv/showthread.php?tid=213108

If desired, I can also start a thread with v15/master+Recentlyadded-fix and ask users to test that as well.

**Comment by Tolriq** [comment]
Return from holidays for me and tons of things to catch up but will also make some testing next week.

**Comment by Tolriq** [comment]
After some testing (Only JSON) I can confirm that the build Helix-fix-5842-testing does fix the JSON related problems about resume point not being set when using Player.Open.

Would love this fix in 14.1 to avoid tons of mails per week :)

**Comment by MartijnKaijser** [comment]
Seems enough people have tested this. Time for merge and backports? @Montellese @mkortstiege

**Comment by Montellese** [comment]
Finally had the time to look at this. I don't think that this is the best fix but I don't have any better ideas either right now so I'm ok with this. Maybe add a remark to the comment that this needs to be re-visited.

**Comment by anaconda** [comment]
> Finally had the time to look at this. I don't think that this is the best fix but I don't have any better ideas either right now so I'm ok with this. Maybe add a remark to the comment that this needs to be re-visited.
Thanks.  TODO added.=

**Comment by Montellese** [comment]
Thanks.

**Comment by gentoo-root** [comment]
This patch leads to regression. Assume you have a folder with two videos, default zoom is 1.0 for both.

1. Start playing the second video, set zoom=0.5, stop playing.
2. Start playing the first video, its zoom is 1.0 by default.
3. Press [X] in the corner, so that you get into menu, but video is played in backgroupd.
4. Start playing the second video (without stopping first one). Its zoom=0.5.
5. Stop playing the second video and start playing the first one. Its zoom will be 0.5, but should be 1.0.

When one video is played, and I start the next one without stopping the first one, settings of first video get overwritten by settings of second video.

**Comment by anaconda** [comment]
Did you git bisect to determine this?
This sound similar to the issue #5842 solved (for playlists) and I think it's caused by https://github.com/xbmc/xbmc/blob/master/xbmc/Application.cpp#L3845

**Comment by gentoo-root** [comment]
At first, https://github.com/xbmc/xbmc/blob/master/xbmc/Application.cpp#L3845 is not a culprit. This line does correct saving of settings for previous video. But then https://github.com/xbmc/xbmc/blob/master/xbmc/Application.cpp#L4399 does incorrect saving of settings because this time https://github.com/xbmc/xbmc/blob/master/xbmc/utils/SaveFileStateJob.cpp#L129 leads to applying next video settings to previous video (progressTrackingFile is still previous video). So settings for previous video are rewritten by settings of next video. This is what issue #5842 about.

I put my comment here, because this PR leads to regression.

If the line https://github.com/xbmc/xbmc/blob/master/xbmc/Application.cpp#L4398 looks like `if (!m_progressTrackingItem->IsPVRChannel() && !(playlist == PLAYLIST_VIDEO && g_playlistPlayer.GetPlaylist(playlist).size() > 1))` then issue #5842 is fixed for playlists of two or more videos, but is not fixed for the case when I manually start next video without stopping previous one.

If that line looks like before: `if (!m_progressTrackingItem->IsPVRChannel() && g_playlistPlayer.GetCurrentPlaylist() == PLAYLIST_NONE)` then issue #5842 is fixed both for playlists of many videos and for manually started videos, but is not fixed for playing from "Recently added", as @anaconda says.

**Comment by anaconda** [comment]
Thanks. I'll try to look into this - unfortunately I'm pretty busy right now (and I will be for a while).
Best way to fix both playlists and the issue you're experiencing would be to move the logic to the players (addressing the comments added by this PR).

**Pull request merged**
