### PR TITLE
[jenkins] don't die if binary add-ons fail to build

### PR DESCRIPTION
**Pull request by opdenkamp**
e.g. after an API change

@Memphiz this is just your commit and c+p of it to other platforms. haven't looked at the groovy find file thing

### CODE REVIEW

**Comment by opdenkamp** [comment]
jenkins build this please

**Comment by opdenkamp** [comment]
pulling tonight unless there are any objections, so the API changing PRs can go in

**Comment by Montellese** [comment]
This doesn't cover win32 right?

**Comment by opdenkamp** [comment]
weren't add-ons removed from there already, right? didn't see the windows build from jenkins fail

**Comment by Memphiz** [comment]
@opdenkamp that nails 100% - thx

**Comment by Memphiz** [comment]
For windows it would need to tag the failed build in the filesystem here - https://github.com/xbmc/xbmc/blob/master/tools/buildsteps/win32/make-addons.bat#L108

and delete the tagfile somwhere at the start of this file. Exitcode should be 0 so that jenkins doesn't fail. But if @opdenkamp had no issues with it on windows - does it mean the addons built fine with the api change? Or does it mean jenkins doesn't evaluate the exit code correctly for windows?

**Comment by Montellese** [comment]
I haven't looked into how this partial success handling works but on win32 `make-addons.bat` fails if any of the addons fail and the build stops immediately if any of the addons fails so there's no logic to continue building any other addons if one has failed.
I have seen cases (on jenkins) where `BuildSetup.bat` continues to run even though `make-addons.bat` failed but I was never able to reproduce that myself so far.

**Comment by opdenkamp** [comment]
I think that we can pull in this one for now, and take a look at windows separately then. Jenkins was only complaining about the android one

**Comment by Memphiz** [comment]
Now that i thought about it a bit more we will need a different approach in the future @Montellese. As you said - the current cmake project doesn't support to continue building if one of the addons failed. This also stands true for all other platforms beside win32. In this PR we just ensure to build all depends wrappers for binary addons. If for example pvr addons failed - we still try to build audio decoders and encoders and so on.

A real solution imo would be if cmake could build all addons and keep track of the failed ones in a file inside the buildtree (which jenkins can evaluate/show). The file would need to contain the addons which failed to build and should be removed prior building binary addons. For this we would also need to remove the multiple depends wrappers and replace them with a catch all wrapper (maybe xbmc-binary-addons).

**Pull request merged**
