### PR TITLE
cppcheck performance fixes

### PR DESCRIPTION
**Pull request by tobbi**
I just ran through the list of cppcheck performance fixes and found a few (most of them pertaining to passing strings as const ref).

This is work in progress as I'm still going through the list.

### CODE REVIEW

**Comment by fuzzard** [comment]
Can i suggest before you continue further. Make the commits logically together, and give each a meaningful commit message. ie for each type of cppcheck, group them, and have the commit message say something like 
```
implements xxx performance check 
<copy of the cppcheck message for reference>
```

I would even suggest to target a PR for a single performance check. At this point already, you are 105 files in, with unknown grouped changes, with almost useless commit messages. It makes it nigh on impossible to review, and when PRs get hard to review, they tend to sit and rot.

**Comment by tobbi** [comment]
I know what you mean, but I'm not sure I agree...

The fixes here are rather reduced to the relative source files with no interactions with the other parts of the code. Most of the changes are in .h file + .cpp file, which means those can be read from top to bottom usually.

I could split this up but would have to think about how to do this the best way.

**Comment by lrusak** [comment]
> I know what you mean, but I'm not sure I agree...
> 
> 
> 
> The fixes here are rather reduced to the relative source files with no interactions with the other parts of the code. Most of the changes are in .h file + .cpp file, which means those can be read from top to bottom usually.
> 
> 
> 
> I could split this up but would have to think about how to do this the best way.

Commits should be made from logical groupings of changes. The commit description should contain a useful summary of the change and possibly why you changed it.

The less changes the easier the review. If you add more changes it then takes more reviewer time and this may take longer to merge. It may be better to make smaller changes of the same type and PR them one at a time. I would also check that it builds before making a PR 😉

**Comment by tobbi** [comment]
I will close this PR in favour of cppcheck performance PRs grouped by top or "near-top" level source directories.

**Comment by garbear** [comment]
@tobbi Thanks for splitting the PR, and welcome back to Kodi contribution.

I see you split the commit as you did in the past, with one PR for each subfolder. And I appreciate the alphabetization. However, our goal is reviewability, and 20 disparate PRs requiring 20 separate approvals is a bit burdensome for us. A single PR like this is preferable (you can even re-open this to force-push).

To optimize reviewability, we prefer a single PR, with separate commits per cppcheck warning, not subfolder. This is because for review, we compare the commit diff with the commit description, and verify that the diff actually solves a problem.

Also, if you do happen to open multiple related PRs in the future, or send a follup PR for an existing PR, you should cross-link the PRs. Cross-linking happens when a PR is mentioned in another's description or conversation. It aids reviewability because I can quickly navigate to my next review job instead of having to search and organize my review jobs manually.

**Comment by tobbi** [comment]
I will try to get to it. Unfortunately I'm currently focused on my masters thesis so my time is unfortunately limited. But if I don't forget and the weather isn't too good, I will tackle it on the weekend.

**Pull request closed without merging**
