### PR TITLE
Migrate from PCRE to PCRE2

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Migrate to PCRE2
This brings in the patch from Yavor Doganov that is used by Debian  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1000113 (@basilgello can confirm one way or another).

## Motivation and context
There was discussion in https://github.com/xbmc/xbmc/pull/24128 about migrating completely to std::regex usage, but as far as im aware, theres been no further progress on that front.

As this patch is done, tests were improved, and tests all pass, i think moving from PCRE1 to PCRE2 is a good interim solution. Along with that patch, we remove PCRE completely, we have the ability to build PCRE2 from source for all platforms

Also removed "unused" methods as mentioned in https://github.com/xbmc/xbmc/pull/24128#issuecomment-1824201196 by @rschupp 

## How has this been tested?
Build ios/macos/android
runtime macos
kodi-tests on macos aarch64 all pass

## What is the effect on users?
N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by basilgello** [comment]
I have ported that one for v21: https://salsa.debian.org/multimedia-team/kodi-media-center/kodi/-/blob/debian/experimental/debian/patches/workarounds/0003-pcre2.patch?ref_type=heads

**Comment by basilgello** [comment]
I havent yet reviewed your patchset @fuzzard but you can add my port of `FTPParse.cpp` from the link above. Or we could drop ancient system support at all and leave only tnose actually found in 2024 :)

**Comment by basilgello** [comment]
I diffed the HEAD of this PR branch with my patch applied and it appears that the most affected files have mostly formatting differences:

```
xbmc/utils/RegExp.* xbmc/utils/StringUtils.h xbmc/utils/test/TestRegExp.cpp
```

Apart from removed unused methods that I did not remove in Debian upload and the FTPParse thing I added, the only difference is in FindPCRE vs FindPCRE2 cmake module, but it is expected.

**Comment by fuzzard** [comment]
No changes are required for ftpparse. It's use of pcre was removed in #24128

**Comment by basilgello** [comment]
I decided not to mix std::regex and PCRE2 on purpose.

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by basilgello** [comment]
@fuzzard So do you still want to mix pcre2 and std::regex or you will apply the patch I adapted for this matter?

**Comment by fuzzard** [comment]
I see absolutely no reason to add that patch. The code in question was independently moved to std::regex months ago

**Comment by basilgello** [comment]
My research before working on that patch shows std::regex lacks Unicode pattern matching: https://stackoverflow.com/questions/11254232/do-c11-regular-expressions-work-with-utf-8-strings

**Comment by fuzzard** [comment]
if you want to migrate that back to pcre2, feel free, but its not needed to do in this PR. the migration to std::regex for that code has occured, there is zero need to touch it in this PR that is aiming to remove pcre.

**Comment by basilgello** [comment]
Thanks for clarification. Makes sense as we really should not mix all at once. Plus I will probably spin up container FTP server with various unicode file names and check they are displayed properly. If they do with regex, let it be. If not, I will make a follow-up PR to migrate CFTPParse to pcre2

**Pull request merged**
