### PR TITLE
Allow named groups on m_videoCleanDateTimeRegExp (rebased)

### PR DESCRIPTION
**Pull request by clashlab**
This is the rebase of #5499

### CODE REVIEW

**Comment by Paxxi** [comment]
Why is the old single regexp left in there? Can't we just remove it and during loading we stick it first in the list of regexps used?

**Comment by clashlab** [comment]
The old regexp is kept to still be able to process files where title is before year.

**Comment by Paxxi** [comment]
yes keep the old regexp but store it in the vector along with the rest of the regexps, no need to have two separate options for the same thing.

**Comment by clashlab** [comment]
You are right, ```m_videoCleanDateTimeRegExp``` is not used any more.
I updated the regexp vector as I missed it before

**Comment by mkortstiege** [comment]
@clashlab some of the commits in there are looking like a rebase issue. Care to rebase once again?

**Comment by clashlab** [comment]
I managed to perform the rebase, but on the original branch, see #5499
Sorry for the mess

**Pull request closed without merging**
