### PR TITLE
[Fix][subs] Don't try to read vob sub files (without a corresponding …

### PR DESCRIPTION
**Pull request by ace20022**
…idx file) like text based sub files.

This is a replacement for https://github.com/xbmc/xbmc/pull/7190

### CODE REVIEW

**Comment by Voyager1** [comment]
+1 (already reviewed)

**Comment by ace20022** [comment]
@MartijnKaijser okay?

**Comment by MartijnKaijser** [comment]
It's a bugfix and reviewed :)

**Comment by ace20022** [comment]
Just to be sure, because it's really a minor issue.

jenkins build this please

**Comment by MartijnKaijser** [comment]
the other platforms show compile errors

**Comment by ace20022** [comment]
jenkins build this please

**Comment by arnova** [comment]
Shouldn't you include <cstring> for std::memcmp ?

**Comment by ace20022** [comment]
jenkins build this please

**Comment by mkortstiege** [comment]
+1. @MartijnKaijser your button.

**Pull request merged**
