### PR TITLE
[keymaps] change show shutdownmenu to poweroff action

### PR DESCRIPTION
**Pull request by DaVukovic**
## Description

As suggested here: https://github.com/xbmc/xbmc/pull/23806#issuecomment-1898948297

I would suggest that we revert that for the time being as well. 

This breaks user-setups for those who are using Harmony remotes ending up in their devices running all night as they expect their devices being turned off instead of showing the shutdownmenu which they don't see anymore because their TV has already been switched of or the AVR input channel changes. 

The expected behavior of a power button on a remote is a device being turned off. 

We could for sure improve that probably for RPi users by adding an option to the shutown-options at our settings to show the shutdown-menu instead of turning the device off, but as long as we don't have that we shouldn't break user setups and force them to modify xml files or adding addons they weren't in need of before we included this change. 

## Motivation and context

Users with Harmony remotes are now in need of modifying XML files or fiddle around with addons to get the expected behavior (pressing power -> device turned off) back, as PR #23806 broke their setups. 

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by DaVukovic** [comment]
Please don't merge this. I might have something better which will satisfy us all

**Comment by DaVukovic** [comment]
#24545 might be the better solution.

**Comment by DaVukovic** [comment]
I just now removed the "don't merge" label because I'm totally fine merging this PR instead of #24545 if one might this the other PR breaks the shutdown-timer function.

**Comment by HiassofT** [comment]
Note that this change will bring back the inconsistent behavior between keyboards (or remotes that show up as keyboards in Linux) and remotes which was the issue #23806 originally addressed.

Feel free to merge this though if you think inconsistent behaviour in default settings results in better user experience.

**Comment by fuzzard** [comment]
@HiassofT ive gone with the revert. The other PR is half baked (ie the comments around timer shutdowns not functioning), and i just need something in for beta3.

**Pull request merged**
