### PR TITLE
[tools/depends][native] bump m4 autoconf

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Start the long slog of dependency bumps. See how far i get.

## Motivation and context
Version bumps

@wsnipex can you throw tarballs on mirrors when time allows

## How has this been tested?
osx

## What is the effect on users?
N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by garbear — APPROVED** [review]
Good to see we remove more patches than we take on.

**Comment by fuzzard** [comment]
Don't say that too early, there's more to come, haha

**Comment by fuzzard** [comment]
So a question regarding best practice. The last 3 commits are fixing up other depends after autoconf 2.70+.
Should these be merged into the autoconf bump commit?
Each of the commits currently has info about where/what they are required for, as well as when they may be removed (future version numbers etc). Im worried that info may get lost/difficult to see (super long commit msg) getting merged in the autoconf bump commit, but without being in the autoconf bump, the whole buildable at each commit is not possible.

Which way do i need to go here?

**Comment by fuzzard** [comment]
Thats good enough for me. Have squashed them into the one commit. Massive commit message, but meh, no one will ever look at it again anyway, haha.

**Pull request merged**
