### PR TITLE
[Estuary] Home screen: Fix context menu y position

### PR DESCRIPTION
**Pull request by ksooo**
…  so that the menu fits completely on 16:9 screen even if it has more than 12 items.

IMG_5896

@howie-f fyi

@ronie have some time for yet another code review?

### CODE REVIEW

**Comment by ksooo** [comment]
@ronie do you have an idea how to position the menu in the middle of the screen? Currently it works with a fixed y position, which is okay-ish, but dynamic positioning based on actual height of the menu (number of items) would be better.

**Comment by ronie** [comment]
the positioning of the context menu is handled by core, and it should be centered within the dimensions of the container.

i'm not sure why Estuary is overriding this behavior on the home screen.
could you try if removing this line https://github.com/xbmc/xbmc/blob/08b7599d63e063545e34a24bb17fc3738cd4dde7/addons/skin.estuary/xml/DialogContextMenu.xml#L8 works for a 12 item menu?

if so, that would be my preferred solution.

**Comment by ksooo** [comment]
@ronie I tried removing that line in the first place and visual result was rather unsatisfying:

11 menu items:

screenshot00003

**Comment by ronie** [comment]
in addition to removing that line, can you change this line 
https://github.com/xbmc/xbmc/blob/b7d8cf54aaa5195cd48ea583613c1ec329cf126c/addons/skin.estuary/xml/DialogContextMenu.xml#L30
to
`<animation effect="slide" end="0,175" time="0" condition="Window.IsActive(home)">conditional</animation>`

that seems to work reasonably ok for me

**Comment by ksooo** [comment]
@ronie tested your suggestion on both 16:9 and 16:10 screens. Looking good now. Thanks for your help. PR adjusted.

**Review by ronie — APPROVED** [review]
thx!

**Comment by howie-f** [comment]
awesome! can we please have this in matrix also?

**Pull request merged**
