### PR TITLE
 [PVR] Fix crashes on pvr manager deinit/reinit - part 2

### PR DESCRIPTION
**Pull request by ksooo**
Backport of #11225 

@Jalle19 do i have your go?

@janbar fyi

### CODE REVIEW

**Comment by janbar** [comment]
I am out of home for a week. Seems the code is right for me. Please merge it and I will try when I will come back.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
@Jalle19 no problem that @janbar is not available for runtime testing on Krypton. I did - for a couple of days now. No problems found.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
Jenkins error (rar file something) is not related to this PR.

**Comment by popy2k14** [comment]
Not fixed, at least for me: http://forum.kodi.tv/showthread.php?tid=300054&pid=2485933#pid2485933

**Comment by ksooo** [comment]
Keep out if this developer discussions, please. The problems you experience are unrelated to this bug fix.

**Pull request merged**
