### PR TITLE
[ios] add setting to extend UI under the notch

### PR DESCRIPTION
**Pull request by kambala-decapitator**
## Description
Adds a new setting to devices that have "notch" (iPhone X and similar) to control UI size. The setting takes effect only after restarting the app because I couldn't achieve resizing `CAEAGLLayer` on the fly without bugs.

## Motivation and Context
Originally requested at https://forum.kodi.tv/showthread.php?tid=348671, builds on top of #16719 to control new behavior via Settings.

## How Has This Been Tested?
Tested on iPhone XR (has notch) and iPhone 6+ (no notch).

## Screenshots (if appropriate):
Screen Shot 2020-01-06 at 19 18 09_framed

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ksooo** [comment]
I hope this seeing is only available/visible on platforms that actually serve notched devises? I don't want to see it on macOS or Windows, for example.

**Comment by kambala-decapitator** [comment]
yes, currently this setting is in `darwin_ios.xml`, so it's available only on iOS. Even if it's moved to the common `settings.xml`, there's still a `requirement` that currently is implemented only for iOS.

**Comment by ksooo** [comment]
Isn't it possible to detect the presence of a notch and to adjust UI size automatically? I doubt any user will ever want a croppef UI on a notched device.

**Comment by ksooo** [comment]
>  I doubt any user will ever want a cropped UI on a notched device.

 I guess this is misleading. What I wanted to say is that nobody wants UI that is partially hidden by the notch. Who will set this setting value to "loose" some party of the UI?

**Comment by kambala-decapitator** [comment]
The reasoning was given in the linked forum thread: previously user adjusted UI manually with Zoom option so that it's not obscured by the notch, but video plays fully fullscreen (notch doesn't really affect it, so it's ok that some parts of video go under it).

> Isn't it possible to detect the presence of a notch and to adjust UI size automatically?

now thinking of your words I think it should be possible to find the "right" level of zoom automatically, so user doesn't have to play with it manually. I've been trying to resize native iOS view that renders OpenGL content (and it was buggy, so I left a TODO), but I guess just applying "zoom" to Kodi UI would be easier.

**Comment by ksooo** [comment]
That would be cool.

**Comment by kambala-decapitator** [comment]
closing in favour of #17234

**Pull request closed without merging**
