### PR TITLE
[Jenkins] bump Android NDK to ndk21e

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Bump Android NDK version used by Jenkins to r21e.
Update docs to note the minimum NDK is r20b, but our CI/CD pipeline now builds with r21e, and therefore recommended to use that for any users wishing to build Kodi.

## Motivation and context
Taglib 1.12 causes Jenkins android builds to fail due to the following failure

```
17:48:33 In file included from /home/jenkins/workspace/Android-ARM64/tools/depends/target/taglib/aarch64-linux-android-21-debug/taglib/toolkit/tbytevector.cpp:29:
17:48:33 /home/jenkins/android-tools//android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/cmath:622:68: error: too many arguments provided to function-like macro invocation
17:48:33   static_assert(is_same<_FloatT, float>::value || is_same<_FloatT, double>::value
17:48:33                                                                    ^
17:48:33 /home/jenkins/android-tools//android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/__config:861:13: note: macro 'static_assert' defined here
17:48:33 #    define static_assert(__b, __m) _Static_assert(__b, __m)
17:48:33             ^
```

This is actually caused by a preprocessor failure in the NDK header include. Using r20b locally, the failure does not occur, but the current 20 on jenkins fails.

## How has this been tested?
Jenkins builds run. Aarch64 android runtime tested ok
Built jenkins android aarch64 platform with updated taglib 1.12 and succeeds.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by garbear** [comment]
A while back I made [this](https://github.com/garbear/xbmc/commit/modernize-android), something you can use?

**Comment by fuzzard** [comment]
Any objections to this?

**Comment by garbear** [comment]
Did you notice some paths in the current instructions were bad? I rebased the commit I linked above, but haven't verified I got all the paths.

**Comment by fuzzard** [comment]
been a long time since i setup my linux vm, but looking through its folders for the sdk/ndk stuff, the version of command line tools i installed still used tools/bin.
If my download folder wasnt cleared out, it looks like i used commandlinetools-linux-6514223_latest.zip at the time of my setup, so maybe the 7 version did more folder structure changes.

I think everything is accurate to how i setup, so i dont want to necessarily change docs i cant confirm.

**Pull request merged**
