### PR TITLE
Proposal to increase A/V demux queues slightly

### PR DESCRIPTION
**Pull request by dagwieers**
## Description
This proposal is based on a change already implemented by @davilla for MrMC which also fixes known issues with specific HLS streams.

Whereas @davilla's changes for MrMC go a lot further than we need to fix the known issues increasing the `SetMaxTimeSize` of Audio *and* Video demux queues from a value of 8 seconds to 10 seconds is sufficient. @peak3d proposed 12 seconds for both.

## Motivation and Context
While these streams have issues, we are in no position to fix those streams. Other tools (ffplay, THEOplayer, Shakaplayer, OMXplayer) behave perfectly fine on these streams as well and with this small fix the streams behave well in Kodi as well.

For Matrix we are looking into a more extensive fix in the player, but while we do not expect large changes in the VideoPlayer in Leia to be accepted and we like to see this fixed in the next release of Leia we are proposing this here.

Relates to:
- MrMC: [fix: bump up max demux time and data limits for hdr/atmos](https://github.com/MrMC/mrmc/commit/8ebf9052618d911adb72511cf4b11f7dd8659181)
- [Fix from @peak3d](https://github.com/peak3d/xbmc/commit/9b633ec87be189edb4413a5a60aeebf7868e228c)
- Retrospect: [Skipping frames for Vier.be](https://github.com/retrospect-addon/plugin.video.retrospect/issues/1089)
- VIER-VIJF-ZES: [Playback issues (skips in the video) of some streams](https://github.com/add-ons/plugin.video.viervijfzes/issues/4)
- Kodi: [Automatic rewind when streaming online content](https://github.com/xbmc/xbmc/issues/16003)

## How Has This Been Tested?
This has been tested by various people over the past 2 years which have suffered from the existing streaming issues and has proven to overcome those.

And this is the default `setMaxTimeSize` setting for MrMC.

## Types of change
- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
Can you change the PR target to master? We try to only backport and not forward port. Thanks!

**Comment by dagwieers** [comment]
@lrusak I don't think you can change the target of a PR, so I made a new PR against the master branch: #17646

**Comment by lrusak** [comment]
> @lrusak I don't think you can change the target of a PR, so I made a new PR against the master branch: #17646


If you edit the title of the PR you should see a dropdown option to change the branch, but possibly only maintainers can do so.

**Comment by dagwieers** [comment]
@lrusak I have never seen that :+1: Learn something new every day!

**Comment by DaveTBlake** [comment]
Closing backport as Leia point cycle now frozen, and PR against master has not been approved or merged. Looks like this got lost in limbo.

I can't comment on technical merits of this, @dagwieers please pursue in #17646 if still relevent.

**Pull request closed without merging**
