### PR TITLE
[guiinfo] Fixed LISTITEM_ISRECORDING for epg event items ...

### PR DESCRIPTION
**Pull request by ksooo**
... in case there is an aborted recording for the selected epg event.

Problem reported here: http://forum.kodi.tv/showthread.php?tid=227026&pid=2143017#pid2143017

@Jalle19 or @xhaggi mind taking a look.

### CODE REVIEW

**Comment by Jalle19** [comment]
Sounds vert reasonable, assuming IsRecording() works correctly.

**Comment by ksooo** [comment]
It does. 

Jenkins build this please.

**Comment by MartijnKaijser** [comment]
jenkins build this please (in lowercase ;) )

**Comment by ksooo** [comment]
Jenkins error not related to this PR (pvr.hts breaking on WIN-32).

**Pull request merged**
