### PR TITLE
[PVR, json-rpc] Fix Input.Select for PVR fullscreen windows

### PR DESCRIPTION
**Pull request by ksooo**
Jarvis backport needed.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
@Montellese you want an JSON fix bump for this?

**Comment by Montellese** [comment]
I don't think that's necessary. This feature is pretty new and the fix isn't really JSON-RPC related.

**Comment by ksooo** [comment]
Fix confirmed team-internally.

**Pull request merged**
