### PR TITLE
[addons][language] fix crash if selected language addon no more present 

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description

Found the crash while playing with addons and occurred after I deleted `~/.kodi/addons/resource.language.de_de`.

This fixes the problem.

Commit 1:
------------------------------
**[addons][language] fix crash if selected language addon no more present**

Previously, if the language addon was deleted for any reason, Kodi crashed on startup.

This adds a check that the add-on is actually there.

Here the backtrace about crash before:
```
#0  CLangInfo::SetLanguage (this=0x55555ad37eb0, language="resource.language.de_de", reloadServices=false) at /home/alwin/Development/Kodi/kodi-Matrix/xbmc/LangInfo.cpp:670
#1  0x0000555557ad51eb in CApplication::LoadLanguage (this=0x55555ad34c20, reload=false) at /home/alwin/Development/Kodi/kodi-Matrix/xbmc/Application.cpp:4915
#2  0x0000555557abdbd0 in CApplication::Initialize (this=0x55555ad34c20) at /home/alwin/Development/Kodi/kodi-Matrix/xbmc/Application.cpp:737
#3  0x0000555557635500 in XBMC_Run (renderGUI=true, params=...) at /home/alwin/Development/Kodi/kodi-Matrix/xbmc/platform/xbmc.cpp:46
#4  0x0000555556e0b08c in main (argc=1, argv=0x7fffffffdf38) at /home/alwin/Development/Kodi/kodi-Matrix/xbmc/platform/posix/main.cpp:77
```

Commit 2:
------------------------------
**[addons][language] don't use CAddon class if GetAddon returned false**

Before has it after failed `GetAddon` call used the `CAddon` class to get his ID and to use on other calls.

As we never know exact why `GetAddon` failed can we never sure that related class is really created.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by AlwinEsch** [comment]
There is currently also a big bug where when updating from `Addons28.db` to` Addons32.db` all language addons are lost, if the database is re-created from scratch, the languages are available.
But don't know exactly what caused it.

Bildschirmfoto von 2020-09-15 23-01-05

**Review by phunkyfish — APPROVED** [review]
LGTM

**Review by howie-f — APPROVED** [review]
looks fine, thanks

**Comment by phunkyfish** [comment]
> There is currently also a big bug where when updating from `Addons28.db` (Kodi Matrix Alpha 1) to` Addons32.db` all language addons are lost, if the database is re-created from scratch, the languages are available.
> But don't know exactly what caused it.
> 
> With the Bug only the installed ones are listed:
> Bildschirmfoto von 2020-09-15 23-01-05
> 
> Will start to compare which db version produced it.

Any idea what might cause this @howie-f ?

**Comment by howie-f** [comment]
> Any idea what might cause this @howie-f ?

no idea yet, but will try to reproduce this afternoon. @AlwinEsch is this only happening when upgrading from `Addon28` to current? i can just test upgrade from `28` and from `31`. wiped other versions unfortunately

**Comment by AlwinEsch** [comment]
Will look this evening what happens there in database. Now first comes the big update round about binary addons (related to the two requests from yesterday) :sweat_smile:

**Pull request merged**
