### PR TITLE
FindDav1d.cmake: fix internal david build download / parse DAV1D-VERSION file

### PR DESCRIPTION
**Pull request by mglae**
## Description

Fix archive extension in cmake downloader when building internal dav1d

## Motivation and context

With #20585 archive extension was changed but .tar.gz is still hard coded in dav1d cmake downloader.

Now using DAV1D-VERSION file to create archive name.

## How has this been tested?

Local Linux build.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by the-black-eagle — APPROVED** [review]
Works for me on Ubuntu 20.04.3

**Review by howie-f — APPROVED** [review]
also works on bullseye

**Comment by fuzzard** [comment]
Dont merge this yet. Its a great start, but i think its worthwhile moving this to a function we can use for all internal modules to get the correct archive. Im working on something now, so give me a day or two.

**Comment by fuzzard** [comment]
@mglae @howie-f @the-black-eagle 

Would you mind give the following a run, just double check i havent missed anything

https://github.com/xbmc/xbmc/pull/20811

**Comment by mglae** [comment]
Superseded by #20811

**Pull request closed without merging**
