### PR TITLE
Revert "[Cleanup] Moved playlist type defines to playlist.h"

### PR DESCRIPTION
**Pull request by thexai**
This reverts commit 06d37e5f00051dc59704607d40681df9a96e81c6.

Although Jenkins breakage has been solved by increasing the paging file, this is a sign that this cleanup commit increases the compilation difficulty and increases the RAM consumption (at compile).

See Slack #servers for more context.

In fact the commit reversion is a "cleanup" since is 19 additions and **30** deletions. 

Removes 11 headers `#include "playlists/PlayList.h"` in files where they had never been

The reversion of `constexpr` to previous `defines` it is not necessary but anyway I understand that it was only an intermediate step because it has to end up being an enum class and preferably with the scope limited to the code that needs it.

### CODE REVIEW

**Comment by CastagnaIT** [comment]
@fuzzard has already fixed the problem on azure
so this revert is not needed

**Comment by CastagnaIT** [comment]
FYI @enen92 moving playlist types to playlist.h required to add new includes on others files
how should i proceed with the cleanup?
Does this problem really limit our development?

**Comment by thexai** [comment]
constexpr, enum or defines changes are irrelevant for compilation issues that have been.

What complicates the compilation (eats more RAM) is the changes in headers.

Why are these changes needed if it still compiles the same with the reverted commit?

**Comment by CastagnaIT** [comment]
IMO if we are already at the limit of available RAM it also means that in the next PRs that will be pushed will cause the same problem

**Comment by thexai** [comment]
i wonder because of this future clean-ups will be impossible?

You can create new enum class on new .h file and add this thin file where needed.

You NOT need #include entire big class everywhere just because you need a constsexp that's there.

**Comment by enen92** [comment]
I asked for this because of the inclusion of playlistplayer header in some new component (can't remember exactly which) - which doesn't make sense and deteriorates the architecture. Maybe playlist.h is already huge and not the place for playlist types.
I'd prefer to evaluate a move of the types to a new header (e.g. playlisttypes.h) first then to go with the simple revert.

**Comment by CastagnaIT** [comment]
its not a problem for me add a new file like PlaylistHelper.h or so...
but i want know also more opinion on this problem, not only for this case
how we should handle this problem in the future since i suspect that can happen again, you cannot always revert if someone is working on new implementations

**Review by CastagnaIT — APPROVED** [review]

**Comment by CastagnaIT** [comment]
its ok i am in the middle to finish the cleanup refactor of playlistid's
if you can want wait 1 or 2 days before merge this revert PR
i can push full refactor cleanup PR (that already include this revert)

**Comment by thexai** [comment]
This will allow to eliminate not only `#include "playlists/PlayList.h"` but also `#include "PlayListPlayer.h"` from many files (I guess)

**Pull request closed without merging**
