### PR TITLE
Support building with ninja

### PR DESCRIPTION
**Pull request by wsnipex**
Support building with ninja
replaces #12903

## How Has This Been Tested?
tested building with Ninja generator on linux

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by wsnipex** [comment]
@lrusak does this work for you?

**Comment by lrusak** [comment]
Sorry I missed this. I will test tomorrow and report back.

**Comment by lrusak** [comment]
Yes this seems to work. I'm not really sure why but it does. Thanks.

**Comment by MilhouseVH** [comment]
I think this PR might be responsible for `xbmc.json/addon.xml` being generated with `version=""`:
```
<?xml version="1.0" encoding="UTF-8"?>
<addon id="xbmc.json" version="" provider-name="Team XBMC">
  <backwards-compatibility abi="6.0.0"/>
  <requires>
    <import addon="xbmc.core" version="0.1.0"/>
  </requires>
</addon>
```

See: https://forum.kodi.tv/showthread.php?tid=298462&pid=2656529#pid2656529

Issue confirmed when building latest Kodi master for Ubuntu.

**Comment by wsnipex** [comment]
meh. I've had a quick look at it and the code generation for json is quirky.
Let's revert this for now until I have time to look for a proper fix.

**Pull request merged**
