### PR TITLE
[guiinfo] content type fix for addon browser

### PR DESCRIPTION
**Pull request by phil65**
Backport from https://github.com/xbmc/xbmc/pull/8852
@tamland

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Are you sure this will not screw other things up in any way

**Comment by phil65** [comment]
yup, quite trivial. @tamland has last call ofc.

**Comment by tamland** [comment]
Agree, quite trivial. the content types here should only be used by skins;)

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Pull request merged**
