### PR TITLE
Disable NEON on ARMv6 CPUs

### PR DESCRIPTION
**Pull request by MichaIng**
## Description
The Raspberry Pi 1 and Zero models ship with a hard-float capable ARMv6 CPU, which does not support the NEON instruction set. For reference: https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications

This commit hence checks for the `uname -m` reported `armv6l` CPU architecture and in case sets the NEON flag to false.

## Motivation and context
I'm currently compiling Kodi for Raspberry Pi and noticed the information that NEON is enabled, despite I set `-DWITH_CPU=armv6l` explicitly to have an ARMv6 compatible build.

## How has this been tested?
That ARMv6 does not support NEON is a fact. I'm in the middle of compiling, dealing with dependencies and carefully watching the outputs. When done with this, I'd be able to compile two instances, one with and one without the change and test both on Raspberry Pi Zero W.

## What is the effect on users?
ARMv6-compatible Kodi binaries when compiled on RPi 1/Zero or with explicitly setting `-DWITH_CPU=armv6l`.

## Screenshots (if appropriate):
```
-- CPU: armv6l, ARCH: arm
...
-- NEON optimization enabled
```

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
I think you should be using the `arm1176jzf-s` option for the RPi1. This was moved from the RPi specific build a while ago.

See, https://github.com/xbmc/xbmc/commit/fae5a5a963927f6bbd75b6df7e1bcaae39f47a4b

**Comment by MichaIng** [comment]
Thanks for the hind, I have overseen this target. Okay, while this is the right choice for RPi, first I'm not sure how many will know this, and second there may be other armv6l platforms which all do not support NEON either.

If there are no other armv6l platforms than RPi, then I suggest to led `armv6l` trigger the same flags as `arm1176jzf-s` does, so even without defining `USE_CPU`, on RPi 1 and Zero you'll get a functional binary.

If there are other armv6l platforms (I don't know any), then I suggest to merge this PR as is, to cover the minimum known required flags for those, and have it as a fallback for RPi 1/Zero, if `arm1176jzf-s` is not defined explicitly.

**Comment by lrusak** [comment]
In that case you can just use `-DWITH_ARCH=arm` which should leave neon disabled.

**Comment by MichaIng** [comment]
Well, it is not about what can be set and what not, but about how someone which did not read this does it and if the build scripts sets flag based on info it gathers correctly or not 😉. Usually when I call it on an RPi 1 I would expect it to build correctly for RPi 1, at least that it sets the minimum necessary flags known to be required for the architecture `armv6l` that is estimates already. It is great to know that there is a specific RPi1/Zero target, but I read through quite a few forum threads and never saw this being used, which might or might not be the reason for the problems users report as a result. So if there is something we can do to have the build script do better decisions when no CPU/ARCH was passed, IMHO we should do it?

Btw, is the `WITH_CPU` used anywhere else or only here to define ARCH and in case some other flags?

**Comment by lrusak** [comment]
Listing every arm cpu isn't ideal (I think we do too much already). You should also be able to use `-DENABLE_NEON=OFF`.

**Comment by MichaIng** [comment]
See my first edit above, I'm compiling on another RPi model but set only `armv6l` explicitly after seeing that `armv7l` was derived from `uname -m`.

Yes I agree that it does not make too much sense to list all CPUs. But the few known outputs from `uname -m`, which is used when no input given, should be IMHO to make users life easier. All of those are listed and handled correctly, but only `armv6l` is missing. As said, if there is no other known `armv6l` hardware where Kodi would ever make sense running on, then probably easiest is to use it as alias for `arm1176jzf-s` build flags, similarly like `aarch64` and `arm64` are treated the same?

**Comment by MichaIng** [comment]
Cleanup. Probably does not make much sense since Kodi nowadays doesn't run well on RPi 1 and Zero (1) anyway. Else RPi devs are probably the better source for RPi related commits.

**Comment by garbear** [comment]
From what I observed working on the Steam Link (about the performance of RPi 1) is that Kodi gets heavier each release as more features are added. Lots of optimizations go in too but feature creep seems to slightly outspeed optimization.

**Comment by MichaIng** [comment]
Since hardware in average is also getting stronger, this can be even seen okay. But yeah, Kodi has become quite huge. It is btw. the exact same with Chromium and some other GUI software: Was working well in the past, unusable on RPi 1/Zero nowadays.

**Pull request closed without merging**
