### PR TITLE
[cmake] linux: install cmake files in arch independent dir

### PR DESCRIPTION
**Pull request by wsnipex**
fixes KodiConfig.cmake not being found when building on a different cpu architecture
e.g. on the PPA, when building binary addons on i386, while kodi-addon-dev was created on amd64

@fetzerch @hudokkow ping

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build this with addons please

**Comment by hudokkow** [comment]
Looks good!

**Comment by akva2** [comment]
No arch paths in that file sounds like something is wrong.

**Comment by wsnipex** [comment]
@akva2 Sorry, I don't follow. Can you elaborate please?

**Comment by akva2** [comment]
Typically /usr/lib/<arch> end up in such config files. But it was a knee jerk, thinking a bit further i guess it might very well be fine here since there are no binaries involves.

**Comment by wsnipex** [comment]
yes, we had /usr/lib there, which became /usr/lib/x86_64-linux-gnu/kodi after multi-arch went in, because on the PPA kodi-addon-dev is built by amd64.
If you now build addons on i386 against those headers, which include KodiConfig.cmake, cmake doesn't find it, because it looks in /usr/lib/i686-linux-gnu/kodi.
Furthermore, cmake files are arch independent and therefore should go to /usr/share out of principle.

**Comment by akva2** [comment]
Cmake files in general yes, but config files are comparabke to .pc files. You write explicit paths to linked libs and such and that makes them arch dependent. But there are no libs on KodiCondig so this pr is fine.

**Pull request merged**
