### PR TITLE
Add support for a checkerboard stereoscopic 3D mode for OpenGL

### PR DESCRIPTION
**Pull request by agibson-fl**
Original work done by @prof-membrane.
Original pull request: https://github.com/xbmc/xbmc/pull/4903

This patch adds support for a checkerboard 3D mode on OpenGL systems.  

I figured I'd rebase @prof-membrane's changes onto the current master branch since I had a bunch of time over the holidays.  A few of his changes were no longer necessary because of the DirectX11 work in https://github.com/xbmc/xbmc/pull/6987.

I was able to build and test this on Ubuntu 15.04 and it worked reasonably well.  However, it did hurt my eyes quite a bit more than when I use Bino.  I had my wife verify this and she said it doesn't look nearly as good as Bino.  I'm not sure what's up with that.  Perhaps something is not quite right with the stipple pattern.  Hopefully someone else has some input or suggestions on that point.

### CODE REVIEW

**Comment by FernetMenta** [comment]
don't you ride a dead horse? isn't checkerboard even more dead than the interlaced mode? btw: glPolygonStripple was dropped from OpenGL standard.

**Comment by da-anda** [comment]
AFAIK some projectors need it and we already support it on Windows. Also, we already use stipple for interlaced, so why not also for checkerboard? Or is there some alternative we can use?

**Comment by FernetMenta** [comment]
> Also, we already use stipple for interlaced, so why not also for checkerboard?

because there will be another feature to break soon. as mentioned glPolygonStripple is depreciated and must not be used anymore. in particular not for new features.

**Comment by da-anda** [comment]
Deprecated doesn't mean it's not around for some more time. So you suggest instead of having the feature for as long as that function is still in OpenGL, don't have it at all and hope that someone finds a different solution for GL? I would be with you if this would be new and we didn't already make use of it, but that's not the case. This PR really doesn't add anything different or extra overhead and does not harm at all.

If you strictly veto on adding this and have users enjoy it as long as it may last, then the logical consequence would be to rip out the interlaced one as well (just as anything else deprecated we might use somewhere).

**Comment by afedchin** [comment]
may be someone can implement interlaced/checkerboard with same way as the directx does through shaders. in any case builtins changes still required because I've missed them in dx11.

**Comment by fritsch** [comment]
It means, that drivers supporting 3.3 of the spec won't necesarily
implement this glPolygonStripple which was introduced in OpenGL 1.0? It's
also not part of GLES, therefore it would be nice if we could find
something that works there, too.

I sadly did not find a drop in replacement. But it can be easily workaround
with:
glTexParameterf( GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT );
glTexParameterf( GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT );

E.G. load a texture and let it repeat in the different directions.

2016-01-11 12:55 GMT+01:00 da-anda <notifications@github.com>:

> Deprecated doesn't mean it's not around for some more time. So you suggest
> instead of having the feature for as long as that function is still in
> OpenGL, don't have it at all and hope that someone finds a different
> solution for GL? I would be with you if this would be new and we didn't
> already make use of it, but that's not the case. This PR really doesn't add
> anything different or extra overhead and does not harm at all.
>
> If you strictly veto on adding this and have users enjoy it as long as it
> may last, then the logical consequence would be to rip out the interlaced
> one as well (just as anything else deprecated we might use somewhere).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/xbmc/pull/8836#issuecomment-170519438>.
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by da-anda** [comment]
@afedchin yes, the interface changes need to go in anyways.
@fritsch from my limited research the "replacement" would be shaders, but there you also might have to fight with different shader support levels. Maybe this answer is of use for someone http://stackoverflow.com/questions/6017176/gllinestipple-deprecated-in-opengl-3-1

**Comment by fritsch** [comment]
@da-anda if it's really only for generating a checkerboard, then one can load a texture and just let it repeat in both directions, e.g. think of a 
```
B W
W B
```
texture, that is then repeate in both directions when rendering.

**Comment by da-anda** [comment]
@fritsch checkerboard and line-interlaced (alternating lines for each eye). Then there is also a row interlaced mode we could support and what not.

**Comment by fritsch** [comment]
@da-anda: line stippling can be done the same way.

**Comment by fritsch** [comment]
But if there is a shader - that can be done, too of course - perhaps "the math" is a even a bit cleaner, less hacky and more generic (not having said that the inital polygonstipple was a hack), but my texture repeating stuff would be.

**Comment by FernetMenta** [comment]
> may be someone can implement interlaced/checkerboard with same way as the directx does through shaders

this is the way to go

@da-anda only because a ugly hack is already around does not mean it should be extended.

**Comment by fritsch** [comment]
If we really go the shader way - then it should be done with "something in mind" that needs it and that we also want to support in the future. For this checkerboard approach for old systems - the GL_REPEAT and WRAP stuff should be good enough, easy to implement.

**Comment by da-anda** [comment]
at which level would the shaders have to be applied? GUI rendering or some level later in the chain? If on GUI level, there are for sure plenty of usecases for shaders (color fading, greyscale, blur, ...)

**Comment by afedchin** [comment]
I don't know how it works on OGL but in DX I'm using just one intermediate texture for right eye which will be is alpha blended with backbuffer (which contains left eye data) on the Output-Merger stage. the shader just receives the right eye texture and just sets alpha=0 or alpha=1 for each pixel depending on pixel position.

**Comment by afedchin** [comment]
intelaced method https://github.com/xbmc/xbmc/blob/master/system/shaders/guishader_common.hlsl#L62
checkerboard https://github.com/xbmc/xbmc/blob/master/system/shaders/guishader_common.hlsl#L73

**Comment by agibson-fl** [comment]
Bino does this using Shaders plus some extra logic for filtering, etc.
http://git.savannah.gnu.org/cgit/bino.git/tree/src/video_output_render.fs.glsl

I found this thread too where one of the Bino devs drops in... 
http://forum.kodi.tv/showthread.php?tid=196827

Shaders seem to be the way to go since Bino looks much, much better.  I don't think I have the experience to make this change very quickly.  I see how they're doing it, but I don't see how easily that fits into the kodi code.  If there was another example to follow, I could more easily add it in.

To be fair, I just rebased the same changes from https://github.com/xbmc/xbmc/pull/4903 and that PR was being pushed through.

**Comment by FernetMenta** [comment]
bzw: GL_POLYGON_STIPPLE is already dead for 17 because it is not supported on OSX when GL is bumped to 3.2.

**Comment by fritsch** [comment]
From the link:
* Why not use polygon stipple?
     *  - Because we want to filter, to account for masked out features
     *  - Because polygon stippling may not be hardware accelerated and is currently broken with many free drivers

**Comment by devernay** [comment]
Why not use libgls, which is simply the stereo display code extracted from Bino?
It is very simple, and you don't have to recode anything since it's MIT/X11.
http://libgls.sourceforge.net/
What we have is a single shader that we recompile each time one of the 3D display parameters changes:
http://sourceforge.net/p/libgls/libgls/ci/master/tree/gls/gls.glsl
That was, the GLSL shader has no branches (ifs) and is always optimized for the current display mode.

For tuning the ghostbusting parameter, on should display the calibration grids and follow the procedure at http://bino3d.org/doc/bino.html#Crosstalk-Ghostbusting
(gamma has to be calibrated first)

**Comment by FernetMenta** [comment]
> Why not use libgls

this lib looks rather dead. last update more than 2 years ago. it requires GLEW that we just kicked out.

**Comment by da-anda** [comment]
are we going to give this a new attempt or should we close it?

**Comment by phunkyfish** [comment]
PR closed as it appears to be obsolete.

If the author would like it kept open please just request so on the PR.

**Pull request closed without merging**
