### PR TITLE
[music] Set rating and user rating correctly in SetSong().

### PR DESCRIPTION
**Pull request by ace20022**

### CODE REVIEW

**Comment by ace20022** [comment]
@Razzeee for review, found this by chance, since rating is float and userrating is int ;)

**Comment by Razzeee** [comment]
Thanks! 

jenkins build and merge

**Comment by Razzeee** [comment]
Getting the old rating to userrating correctly was a mess :)
Can you backport please?

**Comment by ace20022** [comment]
It  was introduced by https://github.com/xbmc/xbmc/pull/8405 with is not backported, is it?

**Comment by Razzeee** [comment]
your right, sorry for the noise.

**Pull request merged**
