### PR TITLE
allow Texturepacker to build with giblib4 and fix a configure bug

### PR DESCRIPTION
**Pull request by wsnipex**
thanks to @notspiff for the giblib4 patch
@Memphiz ping

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
@wsnipex thx - That configure fix - is it what fixes the Trouble with texturepacker that @fernetmenta pointed out? (Sorry only on mobile - can't look into it in Detail)

If jenkins is happy just merge away

**Comment by wsnipex** [comment]
no idea, I can't find the issue @FernetMenta pointed out.

**Comment by FernetMenta** [comment]
yesterday after the merge of texturepacker all builds started to fail on Android and atv2

**Comment by Memphiz** [comment]
I am unable to Open those big Outputs on my phone - can look whats going on sunday evening earliest if wsnipex doesn't Beat me to it

**Comment by wsnipex** [comment]
seems https://github.com/xbmc/xbmc/commit/145112899a48560df8146376542adfddd3adf79f doesn't work in some cases, don't know why yet.
Best would be to adjust the re-touched Makefile. @ronie ping

**Comment by ronie** [comment]
ack. will take care of it this afternoon.

**Pull request merged**
