### PR TITLE
Make MusicPlayer.Year infolabel width 100 for Arial

### PR DESCRIPTION
**Pull request by scott967**
## Description

Increase the width of music visualization window MusicPlayer.Year info label from 90 to 100 when Skin.Font is Arial based.   The width is unchanged when the default font is used.  This is accomplished by creating a new label control with visibility controlled by testing the Skin.Font and adding the visibility test to the existing control.

## Motivation and Context

Current label control truncates the year display when arial font is used.  As a result eg 2020 displays as 20... 
## How Has This Been Tested?

Updated the xml file and observed the visualization window with both default and arial based fonts in use.  I did not attempt to determine worse-case width for the label.

## Screenshots (if appropriate):
Default font:
screenshot00001
Arial based font (current):
screenshot00003
Arial based font (with commit):
screenshot00002

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by jjd-uk** [comment]
I'm not sure we should be adding Visibility conditions based on font as we don't do this anywhere else in Estuary. I took a brief look at this and a width of `95` would seem to be enough to display the year with Arial from a brief test here, and this would be close to the current width of 90 to not change spacing too much with the default font. Could you try `<width>95</width>` with no change to Visibility condition to see if that's enough to resolve it for you?

**Review by jjd-uk — COMMENTED** [review]
I'm not sure we should be adding Visibility conditions based on font as we don't do this anywhere else in Estuary. I took a brief look at this and a width of `95` would seem to be enough to display the year with Arial from a brief test here, and this would be close to the current width of 90 to not change spacing too much with the default font. Could you try `<width>95</width>` with no change to Visibility condition to see if that's enough to resolve it for you?

**Review by ronie — CHANGES_REQUESTED** [review]
as @jjd-uk suggested, changing the width of the current label would be preferred.

**Comment by scott967** [comment]
OK removed the extra font-dependent control and doing some testing with different widths, it seems like 96 is the minimum that displays years, at least in the range of 1931 - 2000 that I have been testing (again, I don't know the worse-case width for 4 digits).  So before updating this PR would like confirmation of what width is preferred.

**Comment by ronie** [comment]
it doesn't have to be pixel perfect :-)
i'd say it's ok to keep a small margin, so 100 is fine with me.

**Comment by jjd-uk** [comment]
100 is fine with me also.

**Review by ronie — APPROVED** [review]

**Comment by scott967** [comment]
Changes made and squashed.

**Review by jjd-uk — APPROVED** [review]

**Pull request merged**
