### PR TITLE
[Infomanager] Move itemlabel formatting to it's own class

### PR DESCRIPTION
**Pull request by Paxxi**
First commit is some minor cleanup unifying the access to the infomap containers and some style fixups along the way.

Second commit moves most of the GetItemLabel formatting out to it's own helper class.
Also some style cleanup
Sorted header files.

### CODE REVIEW

**Comment by Paxxi** [comment]
@mkortstiege review please :)

**Comment by mkortstiege** [comment]
Not that easy to review for breakage. Needs runtime testing for sure ..
As wrote on chat, i will do the xcode sync later today unless someone beats me to it.

Thanks for touching the mess!

**Comment by Paxxi** [comment]
updated it and moved getLabel to the top of FileItemInfoProvider.cpp to sort of match how it looks in the .h
also got rid of the leftover code/comment

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
rebase :)

**Comment by Paxxi** [comment]
@mkortstiege I need new xcode project as I went and added separate RDS formatting as well.
@MartijnKaijser DO NOT MERGE! :)
@Montellese I reconsidered and change to const ref instead of the shared_ptr

**Comment by Montellese** [comment]
Looks good in general apart from a few minors. The first commit is a bit messy because it does a lot of different things (include reordering, introduce a helper template, improve some other stuff). I agree with @jmarshallnz on putting this into the existing `xbmc/interfaces/info/` location.

**Comment by mkortstiege** [comment]
@Paxxi, pick https://github.com/mkortstiege/xbmc/commit/529697271379ffbf74857b4bce15423768c1941a for the xcode sync.

**Comment by Razzeee** [comment]
ping @Paxxi

**Comment by Razzeee** [comment]
ping again :)

**Comment by Rechi** [comment]
@Paxxi this needs a rebase

**Comment by garbear** [comment]
Reason for close? This seems like a worthy improvement to the code.

**Comment by Razzeee** [comment]
It is, it's also quite out of date and hard to rebase. Plus paxxi likely doesn't have any time anytime soon.

**Pull request closed without merging**
