### PR TITLE
[PVR][json-rpc] Added field PVR.Fields.Channel.isrecording

### PR DESCRIPTION
**Pull request by ksooo**
As discussed on internal slack.

@joethefox can you test this, please?

### CODE REVIEW

**Comment by joethefox** [comment]
Tested and working like a charm. Thank you!

**Comment by Tolriq** [comment]
API change 7.20 please :(

**Comment by ksooo** [comment]
@MartijnKaijser is it okay to include this in alpha 3? It's a non breaking change (only a field added) with almost no regression potential.

**Comment by ksooo** [comment]
@Tolriq why the "bad" emoji? I can't remember to have any personal issues with you? Do you want to keep it like this? Then, avoid to transform your overall mood to uninvolved persons, please.

Will correct the version number, ofc.

**Comment by Tolriq** [comment]
It's not a bad emoji it's a sad emoji and it's unrelated to you at all :)

It's more about the fact that I missed @Montellese as previously all my remark to keep JSON API in line with his choices always ended up in arguments. If all is fine, all is fine no need to seek issue where there's not ;) (And you may not have noticed but I have the bad habit to put smileys everywhere)

**Comment by ksooo** [comment]
Version number now is 7.20.0, as requested.

**Comment by ksooo** [comment]
jenkins build this please

**Pull request merged**
