### PR TITLE
[buildsteps] android update to jenkins docker info

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Buildsteps are still used for addon CI jobs. we need this data to match the pipeline CI (and therefore the actual docker path structure) to succed

## Motivation and context
Addons fail for Piers.

```
configure: error: "/home/jenkins/android-tools//android-ndk-r26c is not an NDK directory"
script returned exit code 1
```

Old path structure isnt used with new docker CI. Update to match following path structure

```
-- Found assembler: /home/jenkins/android-tools/android-sdk-linux/ndk/26.2.11394342/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang
```

## How has this been tested?
N/A

## What is the effect on users?
N/A

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CastagnaIT** [comment]
can be merged or there is other under the hood?

**Comment by fuzzard** [comment]
Other server things pending. No ETA currently.

**Comment by CastagnaIT** [comment]
i have to temporary stop addon releases at least on piers? so this affect releases?

**Comment by fuzzard** [comment]
Android can not be built currently for master/Piers. take of that what you will.

**Comment by CastagnaIT** [comment]
ok just to make sure i answer users in the right way

**Comment by wsnipex** [comment]
Are you sure this is valid for the binary add-ons builder? It's not the same as the kodi core android builders and the paths differ iirc. Can't really check atm

**Comment by fuzzard** [comment]
The path is technically valid. A previous NDK exists that path structure, but symlinked to match ``android-ndk-rXX`` structure of the current 21 NDK
It would give consistency (buildstep for addons, pipeline for core have same paths), so imo its the way to go at this stage

```
15:57:52 SDK_PATH:
15:57:52 + ls -al /home/jenkins/android-tools/android-sdk-linux/ndk
15:57:52 total 12
15:57:52 drwxr-xr-x  3 jenkins jenkins 4096 Nov 10  2023 .
15:57:52 drwxrwxr-x  1 jenkins jenkins 4096 Nov 10  2023 ..
15:57:52 drwxr-xr-x 13 jenkins jenkins 4096 Nov 10  2023 20.0.5594570
```

```
15:56:00 + ls -al /home/jenkins/android-tools/
15:56:00 total 24
15:56:00 drwxrwxr-x 1 jenkins jenkins 4096 Nov 10  2023 .
15:56:00 drwxr-x--- 1 jenkins jenkins 4096 Jun  9 18:51 ..
15:56:00 lrwxrwxrwx 1 jenkins jenkins   62 Nov 10  2023 android-ndk-r20 -> /home/jenkins/android-tools/android-sdk-linux/ndk/20.0.5594570
15:56:00 drwxr-xr-x 1 jenkins jenkins 4096 Jan 11  2021 android-ndk-r21e
15:56:00 drwxrwxr-x 1 jenkins jenkins 4096 Nov 10  2023 android-sdk-linux
```

**Review by wsnipex — APPROVED** [review]

**Comment by fuzzard** [comment]
@lrusak has installed the newer ndk, and its in the path structure that this PR reflects

```
13:16:31 drwxr-xr-x  4 jenkins jenkins 4096 Jul 29 02:26 .
13:16:31 drwxrwxr-x  1 jenkins jenkins 4096 Nov 10  2023 ..
13:16:31 drwxr-xr-x 13 jenkins jenkins 4096 Nov 10  2023 20.0.5594570
13:16:31 drwxr-xr-x 11 jenkins jenkins 4096 Jul 29 02:26 26.2.11394342
```

**Pull request merged**
