### PR TITLE
Fix image panning using a joystick

### PR DESCRIPTION
**Pull request by kempniu**
This PR enables slide show images to be panned in all directions using a joystick with analog sticks.

## Description
When an image is viewed in a full screen slide show, it can be zoomed in/out and panned.  Since the move to the new peripheral architecture, this feature has been working incorrectly when using a joystick with analog sticks for panning.  Specifically, it has only been possible to pan the image right and down, no matter in which direction the analog sticks were tilted.

The issue is caused by the analog motion handlers only being called with positive magnitudes (at least this is my understanding, judging from `std::fabs()` calls inside `CKeymapHandler::OnAnalogStickMotion()`).  This PR attempts to fix the issue by adding additional action IDs:
  * `ANALOG_MOVE_X` is split into `ANALOG_MOVE_X_LEFT` and `ANALOG_MOVE_X_RIGHT`,
  * `ANALOG_MOVE_Y` is split into `ANALOG_MOVE_Y_UP` and `ANALOG_MOVE_Y_DOWN`.

## Motivation and Context
Image panning using a joystick is not fully functional.

## How Has This Been Tested?
Using a Logitech Cordless RumblePad 2, with current master built from source on Arch Linux.

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Razzeee** [comment]
Gentle reminder for @garbear :)

**Comment by garbear** [comment]
Tested on Linux and the problem is fixed. jenkins build this please

**Comment by Razzeee** [comment]
Thx for your contribution @kempniu

**Comment by kempniu** [comment]
Glad I could help!

**Pull request merged**
