### PR TITLE
[cleanup] removes unused actions

### PR DESCRIPTION
**Pull request by xhaggi**
This PR will removes some unused actions from our `Key.h` and `ButtonTranslator`.

@Montellese mind taking a look

### CODE REVIEW

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by xhaggi** [comment]
@NedScott after this went in we could safely remove the actions from our wiki page http://kodi.wiki/view/Action_IDs

**Comment by mkortstiege** [comment]
Looks good.

**Comment by Montellese** [comment]
Yeah no objections as they aren't usable anymore anyway.

**Comment by xhaggi** [comment]
Thanks ;)

**Comment by xhaggi** [comment]
@NedScott I've just removed them from the wiki page.

**Pull request merged**
