### PR TITLE
FFmpeg: Bump to 4.3-Matrix-Alpha1

### PR DESCRIPTION
**Pull request by lrusak**
FFmpeg 4.3 changelog: https://git.ffmpeg.org/gitweb/ffmpeg.git/shortlog/n4.3

4.3-kodi branch here: https://github.com/xbmc/FFmpeg/commits/release/4.3-kodi

~~@Paxxi for the windows libs please~~ 😃 (ffmpeg is built from scratch for windows).

~~TODO: make a release for 4.3-Matrix-Alpha1 based on the final commit used before merging this PR~~

I'll update this PR with test builds for various platforms as Jenkins builds them.

builds:

[android arm64](https://jenkins.kodi.tv/job/Android-ARM64/15158/artifact/kodi-20200617-af1c8e59-PR18071-merge-arm64-v8a.apk)
[android arm](https://jenkins.kodi.tv/job/Android-ARM/18481/artifact/kodi-20200617-af1c8e59-PR18071-merge-armeabi-v7a.apk)
[osx](https://jenkins.kodi.tv/job/OSX-64/18676/artifact/tools/darwin/packaging/osx/kodi-20200617-af1c8e59-PR18071-merge-x86_64.dmg)
[ios](https://jenkins.kodi.tv/job/IOS-ARM64/12670/artifact/tools/darwin/packaging/ios/kodi-20200617-af1c8e59-PR18071-merge-ios64.deb)

### CODE REVIEW

**Comment by lrusak** [comment]
@phunkyfish I've dropped the win32pthreads patch as it seems that it made it upstream, please confirm 😄

**Comment by lrusak** [comment]
jenkins build this please

**Comment by phunkyfish** [comment]
Yes, I think all my patches are upstream now.

**Comment by phunkyfish** [comment]
I think there was also an rtsp sources patch that can be dropped.

**Comment by lrusak** [comment]
> I think there was also an rtsp sources patch that can be dropped.
> 
> EDIT, this is it and it should be dropped:
> 
> [xbmc/FFmpeg@dc1490b](https://github.com/xbmc/FFmpeg/commit/dc1490bc032d16cfdb475bef8d1b41d9e45d4ff9)

@phunkyfish thanks, I've dropped the commit and updated the sha1 hash here. 👍

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
OP updated with builds for android, osx, and ios! Please test!!

**Comment by Paxxi** [comment]
Looks like mfplat.lib https://docs.microsoft.com/en-us/windows/win32/api/mfapi/nf-mfapi-mfcreatealignedmemorybuffer

Microsoft docs are usually good at listing compatibility and required libraries for every api fortunately

**Comment by phunkyfish** [comment]
Appears to also need `Mfuuid.lib`

**Comment by lrusak** [comment]
> Looks like mfplat.lib https://docs.microsoft.com/en-us/windows/win32/api/mfapi/nf-mfapi-mfcreatealignedmemorybuffer
> 
> Microsoft docs are usually good at listing compatibility and required libraries for every api fortunately



> Appears to also need `Mfuuid.lib`

So is this a problem with ffmpeg itself or the way we link it? Can we list other libraries for the windows linking?

**Comment by phunkyfish** [comment]
For Windows there should be a list of libraries which are linked. These extra libraries also need to be added there.

I’m actually checking these on ffmpegdirect builds as it’s quicker. Will have a look at where in kodi source shortly.

Also needs `Strmiids.lib` I think.

**Comment by fuzzard** [comment]
https://github.com/xbmc/xbmc/blob/de0a96056cc301f21b06ef9c76525b16ed62ffb6/tools/buildsteps/windows/buildffmpeg.sh#L105

Just add them onto that line possibly?

**Comment by phunkyfish** [comment]
Here is my ffmpegdirect test pr for reference: https://github.com/xbmc/inputstream.ffmpegdirect/pull/52

**Comment by Paxxi** [comment]
Pushed a fix now

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
@Paxxi thanks! the build succeeded :+1:

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
would be nice to have more testers but @da-anda said it was all good :wink: I'll leave it open for another day or so unless someone merges it before me :smile_cat:

**Comment by da-anda** [comment]
I see what you did there @lrusak - nice try, nice try :P

**Comment by oCanna** [comment]
Any chance on adding vdpau_vp9 support after this has been merged?

**Comment by lrusak** [comment]
> Any chance on adding vdpau_vp9 support after this has been merged?

I have zero interest in supporting vdpau but if someone else wants to PR the changes that is always encouraged 😀

**Comment by oCanna** [comment]
> I have zero interest in supporting vdpau 

Same here, but I'm stuck with my current hardware and just want to get the most of it until the first Intel discrete GPUs are available or AMD gets their shit together.
 > but if someone else wants to PR the changes that is always encouraged 😀

Will look into it and and will spend some time and try to make this work.

Damn, I just want to watch YT 4K/50p 4k/60p content without stuttering/framedrops.

**Comment by fritsch** [comment]
Are you talking about profile2? E.g. 10 bit? Forget it cause of the 8 bit interop.

Old VP9 should already work.

**Comment by oCanna** [comment]
> Are you talking about profile2? E.g. 10 bit? Forget it cause of the 8 bit interop.

No, just profile_0.
> Old VP9 should already work.

Yes, but only soft-decode and at higher resolution and framerate my cpu can't keep up and I'm getting massive framedrops.

**Comment by fritsch** [comment]
Try: https://paste.ubuntu.com/p/RBxx5TZKdw/

**Comment by fritsch** [comment]
@oCanna: does the patch on top of master work?

**Comment by wsnipex** [comment]
this breaks PPA build on i386. e.g. https://launchpadlibrarian.net/485478080/buildlog_ubuntu-bionic-i386.kodi_2%3A19.0+git20200623.0307-c984753002-0bionic_BUILDING.txt.gz

**Comment by oCanna** [comment]
> 
> 
> @oCanna: does the patch on top of master work?

Sorry for the late response. 
Yes, your patch is working, but I had to fix a small copy&paste mistake.

There might also be a small modification of the CDecoder::ReadFormatOf needed to make sure, that it is really FF_PROFILE_VP9_0 like you did in CDecoder::ConfigVDPAU.
And according to libvdpau, the decoder description should be "VP9_PROFILE_0" instead of "VP9_P0", but should't make any difference.

**Comment by fritsch** [comment]
Cool. Feel free to send a PullRequest.

**Comment by HeresJonny** [comment]
A backport for Leia would be great! Technically, it wouldn't be an introduction of new features but a fix to an existing problem, namely broken Wavpack/DSD.

**Comment by lrusak** [comment]
> A backport for Leia would be great! Technically, it wouldn't be an introduction of new features but a fix to an existing problem, namely broken Wavpack/DSD.

This PR won't be backported, sorry. You are free to try and build Leia with this PR (and the 4.2 bump PR).

**Comment by fritsch** [comment]
And don't forget the changes that were needed for 4.2.x or it won't work.

**Comment by HeresJonny** [comment]
Yep, yep I get it, programming skills 10, social skills 1.

**Comment by fritsch** [comment]
Don't be sad. You can work on the 1. Things can change.

**Comment by HeresJonny** [comment]
Peterchens Mund-fart.

**Comment by fritsch** [comment]
> Peterchens Mund-fart.

QED

**Pull request merged**
