### PR TITLE
[backport][cmake][addons] set CMAKE_SYSTEM_PROCESSOR by Windows UWP builds

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description

This is needed by some addon depends.

By this change only related to addons, to make complete becomes it much more. 

Backport of https://github.com/xbmc/xbmc/pull/17416

## Motivation and Context
As small change to bring this. To have complete need the new CMake Standard `CMAKE_GENERATOR_PLATFORM` (new cmd line `-a ...` value) support added to all places.

But related to backport only hold small as possible.

With `if(CMAKE_GENERATOR_PLATFORM MATCHES ARM64)` needed for the already done test build on addons for `ARM64`. Also if not supported now by Kodi itself.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by DaveTBlake** [comment]
We have nice green ticks on addon builds for Leia 18.6 and this has failed, so bump until 18.7

**Comment by AlwinEsch** [comment]
No problem, :smile:, only confused by our Jenkins, that it bring by Leia so often `java.lang.NullPointerException: Cannot get property 'channel' on null object` but by master mostly never :thinking:

**Comment by phunkyfish** [comment]
How's this going @AlwinEsch ?

**Comment by AlwinEsch** [comment]
There must something done, as the `CMAKE_SYSTEM_PROCESSOR` is normally a mandatory value.

However, it will be too much for me and hope that with GSOC and **"Replacing depends with a CMake-based system"** it will be fixed.

At the moment this is only necessary with libjpeg-turbo, all other dependencies used have a fallback of this value. Since libjpeg-turbo are now in our mirror as binary I could use the `libjpeg-turbo-2.0.3-*-v141-20200105.7z` files for the UWP.

**Pull request closed without merging**
