### PR TITLE
Update rsxs to version 1.0

### PR DESCRIPTION
**Pull request by tobbi**
This updates rsxs to v1.0.
Problem is that this is licensed under GPLv3. Would it be possible to add "or any later version" to Kodi?

### CODE REVIEW

**Comment by Montellese** [comment]
Concerning rsxs you might wanna look at #5329 which will remove rsxs completely from our tree and turn it into a binary addon.

**Comment by tobbi** [comment]
Okay, I believe that's even better. Shall I close this for the time being?

**Comment by notspiff** [comment]
can i have the original source link please.

**Comment by tobbi** [comment]
You can get it from here: http://sourceforge.net/projects/rssavers/

**Comment by MartijnKaijser** [comment]
i don' t think we should include a GPLv3 in our tree anymore. once it' s separate compiled add-on it might be different.

**Comment by notspiff** [comment]
i have updated the addon to use rsxs 1.0. https://github.com/notspiff/screensavers.rsxs/commits/master

note there is still some cleanup to be done, i'll get to it eventually..

tobbi; don't read take this the wrong way, but blindly updating a library is not good enough. it needs to have been tested. see the top 5 commits..

**Comment by tobbi** [comment]
No offense taken. I will close the issue now, since this lib is likely to be removed anyway and this has been taken care of. Thanks Arne.

**Pull request closed without merging**
