### PR TITLE
[tools/depends] Bump swig 4.2.0

### LINKED ISSUE #24385: Compile with swig 4.2.0 fails
### Describe the bug
Here is a clear and concise description of what the problem is:

Updating from swig 4.1.1 to swig 4.2.0 fails the compile. There is nothing obvious in the swig release notes - https://www.swig.org/release.html (swig 4.1.1 builds correctly)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Successful compile

## Actual Behavior

Compile fail - as per log below

### To Reproduce

1. Compile with swig 4.2.0 fails on AddonModuleXbmcaddon.i.cpp
2. compile with swig 4.1.1 works correctly
3.

### Debuglog

The debuglog can be found here:

```
FAILED: build/swig/CMakeFiles/python_binding.dir/AddonModuleXbmcaddon.i.cpp.o 
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-g++ -DFFMPEG_VER_SHA=6.0.0 -DFMT_SHARED -DHAS_AIRPLAY=1 -DHAS_AIRTUNES=1 -DHAS_ALSA=1 -DHAS_AVAHI=1 -DHAS_DBUS=1 -DHAS_EGL=1 -DHAS_FILESYSTEM_NFS -DHAS_GBM_BO_MAP=1 -DHAS_GBM_MODIFIERS=1 -DHAS_GLES=3 -DHAS_LIRC=1 -DHAS_MARIADB=1 -DHAS_NFS_MOUNT_GETEXPORTS_TIMEOUT -DHAS_NFS_SET_TIMEOUT -DHAS_PULSEAUDIO=1 -DHAS_UDFREAD=1 -DHAS_ZEROCONF=1 -DHAVE_DRM_MODIFIER_NAME=1 -DHAVE_EGLEXTANGLE=1 -DHAVE_GBM=1 -DHAVE_HDR_OUTPUT_METADATA=1 -DHAVE_LIBBLUETOOTH=1 -DHAVE_LIBCAP=1 -DHAVE_LIBCEC=1 -DHAVE_LIBUDEV=1 -DHAVE_LIBXSLT=1 -DHAVE_NEW_CROSSGUID -DSPDLOG_COMPILED_LIB -DSPDLOG_DEBUG_ON -DSPDLOG_FMT_EXTERNAL -DSPDLOG_NO_ATOMIC_LEVELS -DSPDLOG_SHARED_LIB -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/kodi-87d2d6f84799224f5fe63a6bba3e973e84e18fef -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/kodi-87d2d6f84799224f5fe63a6bba3e973e84e18fef/lib -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/kodi-87d2d6f84799224f5fe63a6bba3e973e84e18fef/xbmc -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/kodi-87d2d6f84799224f5fe63a6bba3e973e84e18fef/xbmc/platform/linux -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/kodi-87d2d6f84799224f5fe63a6bba3e973e84e18fef/xbmc/cores/VideoPlayer -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/kodi-87d2d6f84799224f5fe63a6bba3e973e84e18fef/.x86_64-libreelec-linux-gnu/build -I/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/kodi-87d2d6f84799224f5fe63a6bba3e973e84e18fef/xbmc/platform/posix -isystem /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/kodi-87d2d6f84799224f5fe63a6bba3e973e84e18fef/.x86_64-libreelec-linux-gnu/build/include -isystem /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/python3.11 -isystem /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/samba-4.0 -isystem /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/fribidi -isystem /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/kodi-87d2d6f84799224f5fe63a6bba3e973e84e18fef/xbmc/contrib -isystem /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/lzo -isystem /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/dbus-1.0 -isystem /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/dbus-1.0/include -isystem /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/libxml2 -isystem /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/harfbuzz -isystem /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/glib-2.0 -isystem /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/glib-2.0/include -isystem /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/freetype2 -isystem /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/kodi-87d2d6f84799224f5fe63a6bba3e973e84e18fef/.x86_64-libreelec-linux-gnu/build/cores/RetroPlayer/messages -isystem /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/libdrm -march=x86-64-v3 -Wall -pipe  -O3 -fomit-frame-pointer -DNDEBUG -Wdouble-promotion -Wmissing-field-initializers -Wsign-compare -Wextra -Wno-unused-parameter -Wnon-virtual-dtor  -s -std=c++17 -flto=16 -fno-fat-lto-objects -fPIC -Wno-cast-function-type -DTARGET_POSIX -DTARGET_LINUX -D_GNU_SOURCE -DHAVE_LINUX_UDMABUF=1 -DHAVE_LINUX_DMA_HEAP=1 -DHAVE_LINUX_DMA_BUF=1 -DHAVE_MKOSTEMP=1 -DHAVE_LINUX_MEMFD=1 -DHAVE_STATX=1 -DHAVE_SSE=1 -DHAVE_SSE2=1 -DHAVE_SSE3=1 -DHAVE_SSSE3=1 -DHAVE_SSE4_1=1 -D__STDC_CONSTANT_MACROS -D_FILE_OFFSET_BITS=64 -DHAS_POSIX_NETWORK -DHAS_LINUX_NETWORK -DHAS_BUILTIN_SYNC_ADD_AND_FETCH=1 -DHAS_BUILTIN_SYNC_SUB_AND_FETCH=1 -DHAS_BUILTIN_SYNC_VAL_COMPARE_AND_SWAP=1 -DHAVE_INOTIFY=1 -DHAVE_POSIX_FADVISE=1 -DHAVE_LOCALTIME_R=1 -DHAVE_GMTIME_R=1 -DHAVE_INTTYPES_H=1 -DHAVE_LIBBLURAY=1 -DHAVE_LIBBLURAY_BDJ=1 -DHAS_ISO9660PP=1 -DHAS_WEB_SERVER=1 -DHAS_WEB_INTERFACE=1 -DHAS_PYTHON=1 -DHAS_FILESYSTEM_SMB=1 -DHAVE_LIBVA=1 -DHAS_UPNP=1 -DHAS_OPTICAL_DRIVE -DHAS_CDDA_RIPPER -DBIN_INSTALL_PATH=\"/usr/lib/kodi\" -DINSTALL_PATH=\"/usr/share/kodi\" -MD -MT build/swig/CMakeFiles/python_binding.dir/AddonModuleXbmcaddon.i.cpp.o -MF build/swig/CMakeFiles/python_binding.dir/AddonModuleXbmcaddon.i.cpp.o.d -o build/swig/CMakeFiles/python_binding.dir/AddonModuleXbmcaddon.i.cpp.o -c /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-devel/build/kodi-87d2d6f84799224f5fe63a6bba3e973e84e18fef/.x86_64-libreelec-linux-gnu/build/swig/AddonModuleXbmcaddon.i.cpp
build/swig/AddonModuleXbmcaddon.i.cpp: In function 'PyObject* PythonBindings::xbmcaddon_XBMCAddon_xbmcaddon_Settings_New(PyTypeObject*, PyObject*, PyObject*)':
build/swig/AddonModuleXbmcaddon.i.cpp:1751:52: error: no matching function for call to 'XBMCAddon::xbmcaddon::Settings::Settings()'
 1751 |     apiResult = new XBMCAddon::xbmcaddon::Settings();
      |                                                    ^
In file included from ../xbmc/interfaces/legacy/Addon.h:14,
                 from build/swig/AddonModuleXbmcaddon.i.cpp:30:
../xbmc/interfaces/legacy/Settings.h:58:3: note: candidate: 'XBMCAddon::xbmcaddon::Settings::Settings(std::shared_ptr<CSettingsBase>)'
   58 |   Settings(std::shared_ptr<CSettingsBase> settings);
      |   ^~~~~~~~
../xbmc/interfaces/legacy/Settings.h:58:3: note:   candidate expects 1 argument, 0 provided
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 12.0 Master
 - Kodi version: 87d2d6f84799224f5fe63a6bba3e973e84e18fef

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Bump swig to 4.2.0 and fix building with swig 4.2.0

## Motivation and context
Fixes #24385
More information can be seen in that issue regarding the end result of the swig compilation

## How has this been tested?
@heitbaum 

## What is the effect on users?
N/A

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by sundermann** [comment]
Compiles on my machine for webOS. Maybe the webOS build failure was just a fluke

**Comment by sundermann** [comment]
Jenkins build this please

**Comment by sundermann** [comment]
Apparently, the issue seems to arise from this part in `Toolchain-Native.cmake` that appends the target sysroot:

```
if(NOT "/home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot" STREQUAL "")
  list(APPEND CMAKE_FIND_ROOT_PATH /home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot /home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/arm-webos-linux-gnueabi /home/stephan.linux/arm-webos-linux-gn>
  set(CMAKE_LIBRARY_PATH "${CMAKE_LIBRARY_PATH}:/home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/usr/lib/arm-webos-linux-gnueabi:/home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/lib/arm-webos-lin>
endif()
```

If this part is present the build will i.e. resolve bzip2 from the target sysroot: 

```
-- Found BZip2: /home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/arm-webos-linux-gnueabi/sysroot/usr/lib/libbz2.so (found version "1.0.8")
```

Causing a lot of redefinition warnings:

```
In file included from /home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/arm-webos-linux-gnueabi/sysroot/usr/include/ctype.h:27,
                 from /home/stephan.linux/xbmc/tools/depends/native/pcre2/aarch64-linux-native/src/pcre2_internal.h:56,
                 from /home/stephan.linux/xbmc/tools/depends/native/pcre2/aarch64-linux-native/src/pcre2_tables.c:51:
/home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/arm-webos-linux-gnueabi/sysroot/usr/include/features.h:326: warning: "__STDC_ISO_10646__" redefined
  326 | #define __STDC_ISO_10646__              200009L
```

With that part commented in `Toolchain-Native.cmake` does not resolve the wrong libraries and compiles without warnings:

```
-- Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
```

It's also possible that the root cause for this is that `use_host='arm-webos-linux-gnueabi'` which seems wrong

**Comment by sundermann** [comment]
The bzip was just an example for why it was failing. There's more libraries being pulled in (at least libreadline for pcre2). But there may be more.

Why are target sysroot even included in `CMAKE_LIBRARY_PATH ` and `CMAKE_FIND_ROOT_PATH `? The native stuff builds fine for me with that commented

**Comment by fuzzard** [comment]
On other platforms, they do not point to target locations. they are host locations. The comment is incorrect. So im guessing the webos stuff isnt differentiating somewhere?

```
# where is the target environment
set(CMAKE_FIND_ROOT_PATH /Users/Shared/xbmc-depends/arm-darwin23.1.0-native)
set(CMAKE_LIBRARY_PATH /Users/Shared/xbmc-depends/arm-darwin23.1.0-native/lib)
```

Target toolchain is
```
set(CMAKE_FIND_ROOT_PATH /Users/Shared/xbmc-depends/macosx14.2_arm64-target-debug)
set(CMAKE_LIBRARY_PATH /Users/Shared/xbmc-depends/macosx14.2_arm64-target-debug/lib)
```

**Comment by sundermann** [comment]
Parts from the webOS cmake config:

Native:

```
# where is the target environment
set(CMAKE_FIND_ROOT_PATH /home/stephan.linux/kodi-deps/aarch64-linux-gnu-native)
set(CMAKE_LIBRARY_PATH /home/stephan.linux/kodi-deps/aarch64-linux-gnu-native/lib)
if(NOT "/home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot" STREQUAL "")
  list(APPEND CMAKE_FIND_ROOT_PATH /home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot /home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/arm-webos-linux-gnueabi /home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/arm-webos-linux-gnueabi/sysroot /home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/arm-webos-linux-gnueabi/sysroot/usr /home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/arm-webos-linux-gnueabi/libc /home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/lib/arm-webos-linux-gnueabi/sysroot /home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/usr /home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/sysroot/usr)
  set(CMAKE_LIBRARY_PATH "${CMAKE_LIBRARY_PATH}:/home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/usr/lib/arm-webos-linux-gnueabi:/home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/lib/arm-webos-linux-gnueabi")
endif()
```

Target:

```
# where is the target environment
set(CMAKE_FIND_ROOT_PATH /home/stephan.linux/kodi-deps/arm-webos-linux-gnueabi-release)
set(CMAKE_LIBRARY_PATH /home/stephan.linux/kodi-deps/arm-webos-linux-gnueabi-release/lib)
if(NOT "" STREQUAL "")
  list(APPEND CMAKE_FIND_ROOT_PATH  /usr)
endif()
# Currently this is only set to reject android by default
if(NOT "/home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot" STREQUAL "")
  list(APPEND CMAKE_FIND_ROOT_PATH /home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/arm-webos-linux-gnueabi /home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/arm-webos-linux-gnueabi/sysroot /home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/arm-webos-linux-gnueabi/sysroot/usr /home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/arm-webos-linux-gnueabi/libc /home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/lib/arm-webos-linux-gnueabi/sysroot /home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/usr /home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/sysroot/usr)
  # Explicitly set this as last. This potentially is /usr which can then cause linux
  # cross compilation to search paths that are not relevant to target arch (eg host libs)
  # x86/x86_64 jenkins CI jobs require /usr for libs like iconv
  list(APPEND CMAKE_FIND_ROOT_PATH /home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot)
  set(CMAKE_LIBRARY_PATH "${CMAKE_LIBRARY_PATH}:/home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/usr/lib/arm-webos-linux-gnueabi:/home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/lib/arm-webos-linux-gnueabi")
endif()
```

It's not the first two lines that are the problem. The problem is inside the if condition where stuff is appended to `CMAKE_FIND_ROOT_PATH` and `CMAKE_LIBRARY_PATH`.

**Comment by fuzzard** [comment]
The if condition is a catch all for every platform that uses it. What path explicitly is a target lib being found in the native list?

I cant build webos locally on a mac (at least last time i tried), so really have no way to test/look at this.

**Comment by sundermann** [comment]
`-- Found BZip2: /home/stephan.linux/arm-webos-linux-gnueabi_sdk-buildroot/arm-webos-linux-gnueabi/sysroot/usr/lib/libbz2.so (found version "1.0.8")`

Basically anything inside `$TOOLCHAIN/arm-webos-linux-gnueabi` should be considered target and should not be included in the native toolchain file. So any paths resolving a (sub)path of `@use_toolchain@/@use_host@` are problematic.

I'm building for webOS on a mac inside a aarch64 ubuntu-22.04 vm btw.

**Comment by fuzzard** [comment]
Can you PR whatever change you think is relevant and we'll see what breaks/fallout i guess. Whatever the change ends up being isnt exactly relevant to this PR, and should be resolved regardless i imagine.

**Review by sundermann — APPROVED** [review]

**Pull request merged**
