### PR TITLE
[JSON]GetAlbums and GetSongs with limits returning too few records

### PR DESCRIPTION
**Pull request by DaveTBlake**
When some albums have multiple artists `AudioLibrary.GetAlbums` with limits, whether sorted or not, can result in too few albums being returned.

Similarly when some songs have multiple artists `AudioLibrary.GetSongs` with limits and a sort order, and when returning artist data (such as "artist", "artistid", or "musicbrainzartistid"), can result in too few songs being returned.

This issue was introduced in Jarvis when #8306 corrected the return of inconsistent artist data by querying with a join to the artist table. The limits issue was noticed but not fully resolved for GetSongs by subsequent fixes such as #8993 to #9081 etc., while the prolbems with limits in GetAlbums was overlooked.

@Tolriq I will get a build going if you would kindly test this out. @Razzeee for a sanity check perhaps.
@Montellese have bumped JSON minor rest is all `musicdatabase.cpp`

### CODE REVIEW

**Comment by DaveTBlake** [comment]
@MilhouseVH given previous experience could you (or someone) possibly checkout the changed query in GetAlbums **with limit but not sort order** on a MySQL database?

**Comment by MilhouseVH** [comment]
Seems to be working as expected...
```
08:45:09 T:140304061667072   DEBUG: GetAlbumsByWhere query: SELECT av.*, albumartistview.* FROM (SELECT albumview.* FROM albumview  WHERE albumview.strReleaseType = 'album' LIMIT 400) AS av JOIN albumartistview ON albumartistview.idalbum = av.idalbum
08:45:10 T:140304061667072   DEBUG: GetAlbumsByWhere - query took 187 ms
```

:+1:

**Comment by DaveTBlake** [comment]
Thanks @MilhouseVH good to know

@Tolriq for testing a build is here http://mirrors.kodi.tv/test-builds/win32/KodiSetup-20160519-0753949-HEAD.exe

**Comment by Tolriq** [comment]
Will test tomorrow. I hope performance is not too much degraded.

**Comment by DaveTBlake** [comment]
>Will test tomorrow. I hope performance is not too much degraded.

Should be OK. Obviously requesting the 2000th song out of 32k of songs when sorted by artist name and including its artist data, is not going to be the quickest activity. But then it never has been. I suspect that most times when getting songs or albums in batches there is no sorting so the slowest case is avoided anyway.

I was a little surprized that the GetAlbums with limit issue had been overlooked, both by myself and in use. The broader problem was spotted in GetSongs, and somehow I didn't extend the thinking to albums.

**Comment by Tolriq** [comment]
Well there's http://trac.kodi.tv/ticket/15735 and the same for albums for mysql (I asked user to report with logs but well they do not really care about bug being fixed)

So while I did refuse to add a sort in Yatse to fix this Kodi bug that would slow down sync for 99% of other users for no reason, there's a high chance that others do add a sort order to bypass this problem.

About the problem, it's a little more complicated it seems, as Yatse does have a smarter way to sync data, it seems requesting data in batch will still returns all the data, the problem is more that when requesting 20 albums only 15 could be returned needing to do more queries. So some that do not count correctly or handle the limits values could end up without having all the data.

**Comment by DaveTBlake** [comment]
I have to admit that all of Kodi's queries without ORDER BY statements have bugged me, didn't know they lead to an actual bug on MySQL. Is it MySQL specific, as seems Ok in the testing I have done on SQLite? Bug reports are so easily overlooked on Trac, and too many open and ancient to browse.

Anyway it sounds like I need to test more of the batched/paginated approach (based on using LIMIT in SQL) to reading songs, albums and artists on MySQL.

**Comment by Tolriq** [comment]
Yes all the report I have about that problem are MySQL only.

**Comment by Tolriq** [comment]
Ok so tested from inside Yatse, always get the same number of albums (but was not affected by the problem). So no regression :)

No sorting = 4.7 secs, sorting on title or artist = 6.5 secs. For 4365 albums.

**Comment by DaveTBlake** [comment]
Thanks @Tolriq, no regression is good.

Yatse obviously works around it, but I'm a bit bothered that no one else seems to have noticed that the albums weren't returning properly.  I don't know if someone can use some direct JSON calls onto say Jarvis and compare with this this patched version (same music loaded into both databases) just to repeat the issue and see the fix works (on SQLite at least).

With the issue of LIMIT clauses in MySQL seeming to need an ORDER BY statement to produce sequential/consistent results, I have to wonder if it is still a problem or has MySQL changed? Yet to set up MySQL and test myself.

**Comment by DaveTBlake** [comment]
Rebased for JSON version bump.

I have tested the order issue with MySQL and limits  reported 16 months ago in  http://trac.kodi.tv/ticket/15735 and I can't reproduce it. Possibly MySQL version dependent? I see no reason to add an ORDER BY statement to the query, especially if it impacts speed.

The implication is that consumers fetching data in batches may be using a sort paramater as well as limit in the JSON call just to avoid the limit being applied in the SQL query (and thus any MySQL issue). When sorting too the limit is applied to the resulting dataset.  I can not see that as necessary with the lastest version of MySQL, but if they are then sorting will be more common used and this PR is even more important.

But I have been unable to find out if other JSON consumers use GetAlbums or GetSongs with a sort order or not, and still not had anyone confirm experiencing the problem that this PR fixes. Maybe everyone does something clever to ensure they get all the albums or songs?

Regardless this fix still needs to be applied.

**Comment by Tolriq** [comment]
Well there's not a lot of people that follow dev and try to report / fix bugs :)

Let's see if that user do answer, it's the only one I had made accept to report problem with logs since he was able to reproduce and seemed tech compliant :)

**Comment by DaveTBlake** [comment]
>Well there's not a lot of people that follow dev and try to report / fix bugs :)

True, lack of motivation for that all round, except us of course.
Meanwhile it seems reasonable to merge this PR, OK with you?

**Comment by Tolriq** [comment]
Yep if you have tested with Mysql fix does not harm Sqlite. so should be merged.

**Comment by DaveTBlake** [comment]
jenkins build this please.

**Pull request merged**
