### PR TITLE
Peripherals: Fix list not refreshing in peripherals dialog

### PR DESCRIPTION
**Pull request by garbear**
Currently, the list of peripherals shown from Settings -> System -> Input -> Peripherals is static and does not update when a device is plugged/unplugged. This PR fixes that.

## Motivation and Context
Users expect peripherals to show up when plugged in.

## How Has This Been Tested?
Tested on OSX with various controllers.

## Screenshots (if appropriate):
peripherals dialog

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by Rechi** [comment]
wrong revision was build
jenkins build this please

**Comment by garbear** [comment]
Currently, the Cancel button is always focused on dialog open. I'll try to change to focus the peripherals list instead.

**Comment by garbear** [comment]
K, peripherals list is now focused on dialog open. jenkins build this please

**Comment by garbear** [comment]
WIN-UWP-ARM failures are unrelated

**Pull request merged**
