### PR TITLE
[discs] Rename HAS_DVD_DRIVE to HAS_OPTICAL_DRIVE

### PR DESCRIPTION
**Pull request by enen92**
## Description
`HAS_DVD_DRIVE` define is set if `ENABLE_OPTICAL` is defined. The name doesn't make much sense since it refers to a specific type of drive when we actual want to guard against optical support. I guess this comes from a legacy time where everything was called DVD everywhere (just like dvdplayer vs videoplayer).
No functional changes, just a simple rename. By the amount of platform ifdefs it's pretty much implicit how the optical component needs a complete rewrite though... :')

### CODE REVIEW

**Review by fuzzard — APPROVED** [review]

**Comment by enen92** [comment]
Jenkins build this please

**Comment by chewitt** [comment]
S/PDIF audio is also optical and supportable, so I'd suggest `HAS_OPTICAL_DRIVE` as more precise wording (but since I don't touch the code it's only a suggestion, so feel free to ignore!).

**Comment by enen92** [comment]
Has_optical_drive_support?

**Comment by enen92** [comment]
Changed to `HAS_OPTICAL_DRIVE` per @chewitt suggestion. Merging when jenkins is green.

**Pull request merged**
