### PR TITLE
Build fixes and musl configuration

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by bkuhls** [comment]
We already have https://github.com/xbmc/xbmc/pull/9672 to add musl support, according to travis it needs some work to also make cmake happy.

**Comment by Rechi** [comment]
@kraj this needs a rebase

**Comment by kraj** [comment]
@Rechi true, although now I see autoconf build system is gone in master, so I have to redo some patches in Cmake way.

**Comment by kraj** [comment]
I think this pull is obsolete since autotools are dropped and the fix for RssReader is already available upstream now.

**Pull request closed without merging**
