### PR TITLE
KeymapAction Overloading fix

### PR DESCRIPTION
**Pull request by bjsvedin**
Modified KeymapActionGroup actions to be a multiset. This allows for hotkey overrides with the same hold durations. Updated joystick.xml comments to showcase new behavior.

## Description

The KeymapActionGroup action property used a std::set. I modified it to use a std::multiset.

The std::set was used for automatic sorting, and that was based on the action's holdTimeMs as provided by the action's < operator. The std::set also enforced uniqueness based on that comparison operator. If you attempted to add another action with the same duration, regardless of the hotkeys, it would be discarded by the set. The std::multiset will still sort by the provided comparison operator, but will not enforce uniqueness in the set. 

This will not cause problems elsewhere because in MapAction.cpp line 28, we are already doing a unique check with the combination of holdTimeMs and hotkeys.

## Motivation and context

I was customizing my joystick.xml file when I learned about overriding, but was disappointed when learning overloading was so limited. With proper overloading I could double the amount of actions available to me with quick access on just the controller, allowing less need for system navigation. I wanted this fix.

## How has this been tested?

I built Kodi with my change, and modified my joystick.xml by adding multiple variations of hotkey and hold duration overloads to a button, along with repeated overloads, and tested that each of them was available/not available to me. All overloads I expected to be available were, I had no overload conflicts, and a when repeated overloads with different actions were declared, the last one declared was the action that was used.

Though i could find no evidence keyboards would be affected, I also tested keyboard actions in FullscreenVideo with existing overloaded keys, and i added more variations to confirm they still work as expected.

I built and installed on Windows 11 machines. They are vanilla windows environments, no modificaitons. I built on one machine, and installed on a second for my tests. I used an xbox series controller and a standard keyboard in my tests.

The folder structure makes it look like this will affect ALL sources of input, because the KeymapAction file is in the keymap folder, not in joysticks, but from my searches ONLY joystick uses the holdDurationMs value and ONLY joysticks uses CWindowKeymap::MapAction. Keyboards use the mod "longpress", which is imported and handled by different classes. I did not dive into remote and touch, but the searches didn't bring up any code from there.

## What is the effect on users?

This will not have immediate affects on any users. I didn't modify existing functionality, only allowed for greater functionality through end user customization. Though I would like to see increased default functionality in joystick keymaps in the future.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
       I do not know where to add a test. Will accept advice
- [ ] All new and existing tests passed 
       I have not found how to run tests. Will accept advice

### CODE REVIEW

**Comment by garbear** [comment]
I'm entertained that you've pushed the keymapper so far. The fix looks correct, and better yet is a single line. I like the improved documentation in joystick.xml.

> but from my searches ONLY joystick uses the holdDurationMs value and ONLY joysticks uses CWindowKeymap::MapAction. Keyboards use the mod "longpress", which is imported and handled by different classes

Correct, keyboard handling is historic and joystick handling was fully redone in v17, which is where it picked up these features that would allow for more functionality when playing games.

> I did not dive into remote and touch, but the searches didn't bring up any code from there.

Touch is handled entirely separately. Remote can be handled in several ways, including by the keyboard and joystick handlers among others. In general, each of the keymaps in `system/keymaps` may be a different handler.

> Though I would like to see increased default functionality in joystick keymaps in the future.

The current functionality is what I had to freeze to merge in v17, as the new joystick system became incredibly huge. Any development forward, including an increase in default functionality, would be welcome.

**Comment by bjsvedin** [comment]
Thank you for the quick feedback! Let me know if I have to do anything more for this PR.

**Comment by garbear** [comment]
It looks like our release manager just bumped this to v22, but that's not too far off - we're planning to branch for v22 in the next week or two, so I'll get this in then.

I'd like to test this out before merge, and I'm interested to see what your joystick.xml looks like. Can you paste what you're using the expanded overloading for?

**Comment by bjsvedin** [comment]
> I'd like to test this out before merge, and I'm interested to see what your joystick.xml looks like. Can you paste what you're using the expanded overloading for?

Sure, these are the overrides I have put together today. Initial tests are very promising, and I expect this to hold up over time. Most of the overloads are simply a hotkey without duration which is what I couldn't do before, but I have one that has multiple. 

`<?xml version="1.0" encoding="UTF-8"?>
<keymap>
  <global>
    <joystick profile="game.controller.default">
      <a>Select</a>
      <a holdtime="1000" hotkey="back">UpdateLibrary(video)</a>
      <b>Back</b>
      <b hotkey="back">ActivateWindow(Home)</b>
      <b holdtime="1000" hotkey="back">CleanLibrary(video)</b>
      <x>ContextMenu</x>
      <x hotkey="back">ToggleWatched</x>
      <y>FullScreen</y>
      <y hotkey="back">ActivateScreensaver</y>
      <start>ActivateWindow(ShutdownMenu)</start>
      <back>noop</back>
      <guide>ActivateWindow(Home)</guide>
      <up>Up</up>
      <down>Down</down>
      <right>Right</right>
      <left>Left</left>
      <leftthumb>noop</leftthumb>
      <rightthumb>noop</rightthumb>
      <lefttrigger>ScrollUp</lefttrigger>
      <righttrigger>ScrollDown</righttrigger>
      <leftbumper>PageUp</leftbumper>
      <leftbumper hotkey="back">Menu</leftbumper>
      <rightbumper>PageDown</rightbumper>
      <leftstick direction="left">Left</leftstick>
      <leftstick direction="right">Right</leftstick>
      <leftstick direction="up">Up</leftstick>
      <leftstick direction="down">Down</leftstick>
      <rightstick direction="left">VolumeDown</rightstick>
      <rightstick direction="right">VolumeUp</rightstick>
      <rightstick direction="up">VolumeUp</rightstick>
      <rightstick direction="down">VolumeDown</rightstick>
    </joystick>
  </global>
  <Home>
    <joystick profile="game.controller.default">
      <b>Back</b>
      <b hotkey="back">ActivateWindow(Home)</b>
      <b holdtime="1000" hotkey="back">CleanLibrary(video)</b>
    </joystick>
  </Home>
  <FullscreenVideo>
    <joystick profile="game.controller.default">
      <a>Pause</a>
      <b>Stop</b>
      <x>OSD</x>
      <y>FullScreen</y>
      <start>Info</start>
      <start hotkey="back">ShowTime</start>
      <back>noop</back>
      <guide>noop</guide>
      <up>ShowSubtitles</up>
      <down>NextSubtitle</down>
      
      
      <right>ChapterOrBigStepForward</right>
      <left>ChapterOrBigStepBack</left>
      <leftthumb>noop</leftthumb>
      <rightthumb>noop</rightthumb>
      <lefttrigger>AnalogRewind</lefttrigger>
      <righttrigger>AnalogFastForward</righttrigger>
      <leftbumper>Seek(-10)</leftbumper>
      <leftbumper hotkey="back">Seek(-20)</leftbumper>
      <rightbumper>Seek(20)</rightbumper>
      <rightbumper hotkey="back">Seek(40)</rightbumper>
      <leftstick direction="left">AnalogSeekBack</leftstick>
      <leftstick direction="right">AnalogSeekForward</leftstick>
      <leftstick direction="up">noop</leftstick>
      <leftstick direction="down">noop</leftstick>
    </joystick>
  </FullscreenVideo>
  <FullscreenInfo>
    <joystick profile="game.controller.default">
      <b>Close</b>
      <x>OSD</x>
      <start>Close</start>
      <leftbumper>Seek(-10)</leftbumper>
      <leftbumper hotkey="back">Seek(-20)</leftbumper>
      <rightbumper>Seek(20)</rightbumper>
      <rightbumper hotkey="back">Seek(40)</rightbumper>
      <lefttrigger>AnalogRewind</lefttrigger>
      <righttrigger>AnalogFastForward</righttrigger>
    </joystick>
  </FullscreenInfo>
  <VideoOSD>
    <joystick profile="game.controller.default">
      <b>Close</b>
      <x>Close</x>
      <leftbumper>Seek(-10)</leftbumper>
      <leftbumper hotkey="back">Seek(-20)</leftbumper>
      <rightbumper>Seek(20)</rightbumper>
      <rightbumper hotkey="back">Seek(40)</rightbumper>
      <lefttrigger>AnalogRewind</lefttrigger>
      <righttrigger>AnalogFastForward</righttrigger>
    </joystick>
  </VideoOSD>
  <VideoMenu>
    <joystick profile="game.controller.default">
      <b>Stop</b>
      <x>OSD</x>
      <leftbumper hotkey="back">AspectRatio</leftbumper>
      <start>Info</start>
    </joystick>
  </VideoMenu>
  <OSDVideoSettings>
    <joystick profile="game.controller.default">
      <leftbumper hotkey="back">AspectRatio</leftbumper>
      <x>Close</x>
    </joystick>
  </OSDVideoSettings>
  <OSDAudioSettings>
    <joystick profile="game.controller.default">
      <leftbumper hotkey="back">AspectRatio</leftbumper>
      <x>Close</x>
    </joystick>
  </OSDAudioSettings>
</keymap>`

**Comment by garbear** [comment]
jenkins build this please

**Review by garbear — APPROVED** [review]

**Comment by garbear** [comment]
@bjsvedin I had a look at your XML. I saved it in a branch so that I could experiment later.

Haven't runtime tested, but I'll get this in my v21 builds for broader testing.

**Comment by garbear** [comment]
@bjsvedin Two feedbacks:

#### Commit message formatting

In git log your commit message looks like:

```
Modified KeymapActionGroup actions to be a multiset. This allows for hotkey overrides with the same hold durations. Updated joystick.xml comments to showcase new behavior.
```

You can format it better, search around for how to make git commit messages really shine:

```
Modified KeymapActionGroup actions to be a multiset

This allows for hotkey overrides with the same hold durations. Updated
joystick.xml comments to showcase new behavior.
```

#### joystick.xml formatting

There's an extra newline and some misalignment in joystick.xml. Can you apply the following patch?

```patch
diff --git a/system/keymaps/joystick.xml b/system/keymaps/joystick.xml
index 12535ebe0d..fc4ef3515f 100644
--- a/system/keymaps/joystick.xml
+++ b/system/keymaps/joystick.xml
@@ -28,7 +28,6 @@
 <!--     <a holdtime="500">ContextMenu</a>                                   -->
 <!--   </joystick>                                                           -->
 <!--                                                                         -->
-<!--                                                                         -->
 <!-- Buttons can be overloaded with hotkeys:                                 -->
 <!--   <joystick profile="game.controller.default">                          -->
 <!--     <a>Select</a>                                                       -->
@@ -49,10 +48,9 @@
 <!--     <b holdtime="500">Stop</b>                                          -->
 <!--   </joystick>                                                           -->
 <!--                                                                         -->
-<!-- holdtime                                                                -->
-<!--   A limitation is that if a single press is mapped in a section, a      -->
-<!--   global "holdtime" overload will be ignored. The workaround is to      -->
-<!--   duplicate the holdtime overload in the section.                       -->
+<!-- A limitation is that if a single press is mapped in a section, a global -->
+<!-- "holdtime" overload will be ignored. The workaround is to duplicate the -->
+<!-- holdtime overload in the section.                                       -->
 <!--                                                                         -->
 <!-- More documentation on keymaps can be found on                           -->
 <!-- http://kodi.wiki/view/keymaps                                           -->
```

**Comment by bjsvedin** [comment]
@garbear I have applied the patch you suggested. 

I also updated my git commit message formatting and message to better reflect guidelines. I have not seen those before, I will start using those elsewhere as well.

**Comment by garbear** [comment]
Looks great! Will merge when Jenkins goes green.

**Comment by garbear** [comment]
jenkins build and merge

**Pull request merged**
