### PR TITLE
[skin][estuary]Three-line weather right column

### LINKED ISSUE #19089: [skin][estuary]Weather information scrambled on some localizations
### Describe the bug

On some locales (like Ukrainian), weather forecast (cloudy, windy etc) is too long to display temperature (see screenshot)

## Expected Behavior

Temperature should not overlap with weather state

## Actual Behavior

See screenshot

## Possible Fix

Move temperature to next row

### To Reproduce

1. Install Ukrainian language pack
2. Configure weather provider of choice
3. Explore the screwed output

### Screenshots 
Here are some links or screenshots to help explain the problem:

IMG_20210119_183450

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian GNU/Linux 10 buster
 - Kodi version: 19.0~rc1

### PR DESCRIPTION
**Pull request by basilgello**
## Description

Supersedes #19093 

## Motivation and Context

Fixes #19089

## How Has This Been Tested?

Running Kodi with Estuary skin

## Screenshots (if appropriate):

IMG_20210123_210309

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by basilgello** [comment]
@DaVukovic @ronie @ksooo

**Comment by DaVukovic** [comment]
Fine by me

**Comment by jjd-uk** [comment]
I've kept quiet on this until I had something that maybe better.

At the risk of creating more bikeshedding here is my alternative in which I've tried to address all the points raised in the previous PR.

image

image

**Comment by ksooo** [comment]
@basilgello I like your approach.

@jjd-uk Not a big fan of your approach, tbh. It waists a lot of space and making the location a "label" is inconsistent design. I had to look twice to find the location in your screen shots. ;-)

**Comment by jjd-uk** [comment]
> @jjd-uk Not a big fan of your approach, tbh. It waists a lot of space and making the location a "label" is inconsistent design. I had to look twice to find the location in your screen shots. ;-)

Weather within Kodi is not something I ever use so I'm completely fine with basilgello's approach.  There just seemed to be some unaddressed points raised in previous PR so just thought I'd offer something different.

**Comment by basilgello** [comment]
Placing 'Coventry' there is certainly a good find! I actually wanted to keep city name within that background box like:

Coventry:
Icon | Icon | Icon | Icon | Icon | Weather-condition-Icon | TEMP-Bold C

But this looks better! And really, do we need __that detail__ of weather condition? "Cloudy", "Merely Cloudy" or "Mostly Cloudy" fit perfectly into Climacons icon we can use in place. The user should have an overview of weather, not super-duper-detailed weather-maniac-pleasant description I guess.

**Comment by ksooo** [comment]
> Placing 'Coventry' there is certainly a good find! 

I disagree, sorry.

**Comment by ksooo** [comment]
@basilgello I'd go with the approach exactly like you have it now in this PR.

**Comment by basilgello** [comment]
> @basilgello I like your approach

Then let's stick to my PR and if during v20 alpha cycle we decide to do climacons or whatever else, we can always fix it!

**Comment by basilgello** [comment]
> @basilgello I'd go with the approach exactly like you have it now in this PR

Brilliant! Then I am just waiting for approvals :)

**Comment by jjd-uk** [comment]
> @basilgello I like your approach
> Then let's stick to my PR and if during v20 alpha cycle we decide to do climacons or whatever else, we can always fix it!

Fine with me. As Weather not something I normally only just noticed that the Hourly icons only go 11 hrs, that should really be a full 24hrs IMHO, a simple change but I guess that would also be something for v20 now.

**Review by jjd-uk — APPROVED** [review]

**Comment by ksooo** [comment]
This needs a bit more love as it destroys the layout of the weather dialog (appearing after pressing enter while the weather home screen entry is selected).

screenshot00000

**Review by ksooo — CHANGES_REQUESTED** [review]
Layout of the weather dialog needs to be fixed.

**Comment by basilgello** [comment]
It is because of Include'd WeatherIcon. I see two options here:

* Declare a second set of WeatherIcon include (say, under 'WeatherIconMain' name)
* Try to make spacing between texture and label configurable per-item

I will go with the first approach because configuring every single weather icon is an overkill.

**Comment by basilgello** [comment]
@ksooo should work as expected now!

**Review by ksooo — APPROVED** [review]

**Pull request merged**
