### PR TITLE
[tools/depends/target] bump dependencies

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
[tools/depends] bump libxslt 1.1.34
[tools/depends] bump libplist 2.2.0
~~[tools/depends] bump libgpg-error 1.38~~ Will revisit this later
[tools/depends] bump libass 0.14.0
[tools/depends] bump fribidi 1.0.10
[tools/depends] bump freetype2 2.10.2
[tools/depends] bump gmp 6.2.0

## Motivation and Context
More dependency updates

## How Has This Been Tested?
Buildtime for osx. jenkins will provide info for android/linux

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
@wsnipex can you look at the fribidi bump. The "excess fluff" for non cross compiling. Im still not sure where thats needed/wanted for the linux side of things. If its ok from your end, i'll look to remove/rebase and merge in the next day or two

**Comment by wsnipex** [comment]
we only need the "excess fluff" for libs that are kodi dependencies and not available in most Linux distros.
Unless Icm missing something, I don't see that for fribidi.

**Comment by fuzzard** [comment]
No worries, I'll strip it out, thanks for clarifying

**Comment by fuzzard** [comment]
jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Pull request merged**
