### PR TITLE
[backport] [Win32] D3DResource improvements.

### PR DESCRIPTION
**Pull request by afedchin**
backport of #11550

### CODE REVIEW

**Comment by afedchin** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
Jenkins build this please

**Comment by MartijnKaijser** [comment]
Jenkins build this please

**Comment by FernetMenta** [comment]
seems to have broke DVD menus:
http://forum.kodi.tv/showthread.php?tid=305255&pid=2511255#pid2511255

**Pull request merged**
