### PR TITLE
[cmake] split glu dependency into it's own module

### PR DESCRIPTION
**Pull request by lrusak**
libGLU seems to only be used by the wiiremote example code (that I could see). Let's make it optional for a regular build.

There is a few other references to libGLU in the depends, I think they can be removed also.

I'm not sure what impact this will have on add-ons so ping @AlwinEsch for help there.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
There are no addons where use it. Also should a change on this places here not touch the addon builds.
From my side OK.

About addons becomes this used for GL: https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-dev-kit/include/kodi/gui/gl/GL.h

**Comment by lrusak** [comment]
> There are no addons where use it. Also should a change on this places here not touch the addon builds. From my side OK.
> 
> About addons becomes this used for GL: https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-dev-kit/include/kodi/gui/gl/GL.h

Perfect, thanks!

**Review by wsnipex — APPROVED** [review]
looks sane

**Comment by fuzzard** [comment]
We use a few defines that appear to be deprecated/removed in Opengl3+ (GL_BGRA_EXT, GL_CLAMP, GL_TEXTURE_BORDER, GL_POLYGON_STIPPLE, GL_LUMINANCE16, GL_LUMINANCE and glColor4f()). I stopped at that point looking for their replacements, so just go with the inclusion of <OpenGL/gl.h>

**Review by garbear — APPROVED** [review]

**Review by fuzzard — APPROVED** [review]

**Pull request merged**
