### PR TITLE
[CEC] Added actions on CEC TV standby (Pause playback, Stop playback)

### PR DESCRIPTION
**Pull request by filimonic**
New actions when CEC TV goes standby: Pause playback, Stop playback

### CODE REVIEW

**Comment by Jalle19** [comment]
You should add the required libcec changes upstream instead of hacking around it here.

Also see https://github.com/Pulse-Eight/libcec/issues/98

**Comment by filimonic** [comment]
@opdenkamp said it is bettet to not use libcec settings， and use application scope.

**Comment by opdenkamp** [comment]
instead of re-using libCEC's configuration struct and trying to keep it synced, you should read/write the settings directly. all device classes in /xbmc/peripherals inherit from CPeripheral, with these methods to read/write settings: https://github.com/xbmc/xbmc/blob/master/xbmc/peripherals/devices/Peripheral.h#L139

**Comment by fluxtendu** [comment]
Any news about this pull?

**Pull request closed without merging**
