### PR TITLE
[PVR] Bump PVR addon API to version 2.0.0, bump addons

### PR DESCRIPTION
**Pull request by ksooo**

### CODE REVIEW

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
@opdenkamp your button

**Comment by ksooo** [comment]
Noticed that this one is still not merged. I understood that it is very really important to fix the API version immediately and therefore rushed on Saturday to create all 18 PRs needed for this. I think I have to calm down a little when it comes to "high priority" Kodi tasks? 

Sorry being so rude, but this is the kind of thing I hardly can live with.

**Comment by opdenkamp** [comment]
wasn't at home in a state in which i could look at PRs without seeing the text twice...
yes, it was important to get fixed right away. let's see if it was late if something gets bumped in the release branch

**Pull request merged**
