### PR TITLE
Avoid breaking skins comparing System.StereoscopicMode after 6345.

### PR DESCRIPTION
**Pull request by ghost**
See http://forum.kodi.tv/showthread.php?tid=211501&pid=1956983#pid1956983
## 

We may just fix Confluence, but there might be other skins which use the same logic out there.

### CODE REVIEW

**Comment by da-anda** [comment]
this will fuck up the order of stereomodes in various dialogs as the list is created by iterating over this enum. So the better fix might be to allow skins to do string comparisons I guess

**Comment by da-anda** [comment]
so how do we want to fix this? IMO we should provide the string representation of a stereomode via GUIinfomanger to skins and use that instead of the ENUM which is not a fixed value at all

**Comment by ronie** [comment]
sounds good to me.

for now, i'll fix confluence until a proper method is implemented.

**Comment by anaconda** [comment]
> so how do we want to fix this? IMO we should provide the string representation of a stereomode via GUIinfomanger to skins and use that instead of the ENUM which is not a fixed value at all
This would be nice, yes.
My goal - as the PR title says - was to avoid breaking every skin using the same logic (pretty certain a number of skinners takes a look at Confluence), but this sounds complicated.
I will add the infolabel later this week.

**Comment by anaconda** [comment]
@da-anda @ronie what about:
https://github.com/anaconda/xbmc/commit/22e5d850c14bef7ba4469bbd312fcc5d484a1196
(untested)

**Comment by ronie** [comment]
since this broke confluence yet again (https://github.com/xbmc/xbmc/pull/8275), i'm in favour of using a string representation.
@da-anda thoughts?

**Comment by da-anda** [comment]
the string fix/approach looks good to me. I wonder though if we need both, integer and string representation in infomanager - only string should do I guess.

**Comment by anaconda** [comment]
Updated to use the string method in my previous comment.
@da-anda please ACK the fixup commit.

Oh, and I still haven't tested this at all yet (hence why it still has debug logging). @MilhouseVH mind including in next build, if da-anda is okay?

**Comment by da-anda** [comment]
as mentioned in the commit - I think we could just have the existing infolabel return the string instead of adding a new one, besides of that it looks sane. Can't say if the static cast is needed or not as I'm not good with C++. Will test.

**Comment by MilhouseVH** [comment]
Yep, I'll include whatever is committed on this PR when the build starts at 9pm UK time.

**Comment by anaconda** [comment]
I do not have a real opinion on this, but the change you're proposing would break this use of `System.StereoscopicMode`:
```xml
./1080i/VideoOSD.xml:485:	 <selected>IntegerGreaterThan(System.StereoscopicMode,0)</selected>
```
That's the only use of `System.StereoscopicMode` in the Amber skin (i.e. it's not comparing the actual mode).

**Comment by da-anda** [comment]
@anaconda yes, it's a breaking change, but other skins suffer the same issue than Confluence does and we're not backwards compatible skin wise anyways. @ronie - what do you think?

**Comment by da-anda** [comment]
for some reason `<selected>!StringCompare(System.StereoscopicMode,off)</selected>`does not evaluate for me (went the way with replacing current int with the string label). `<selected>StringCompare(System.StereoscopicMode,monoscopic)</selected>` does work though. No idea what's wrong, the info label has the correct value "off" though (I had it show up as control label). Any ideas? @mkortstiege maybe?

**Comment by ronie** [comment]
> @ronie - what do you think?

this is stuff for Kodi K*

**Comment by mkortstiege** [comment]
@da-anda i have no idea why there's special treatment for the `SYSTEM_ALWAYS_FALSE` / `SYSTEM_ALWAYS_TRUE`. But i bet weird things will happen when removed ;)

**Comment by MartijnKaijser** [comment]
@ronie we're breaking the backwards ABI anyway right?

**Comment by da-anda** [comment]
@mkortstiege oh, the conversion to boolean values is in general fine, but it should not be done within a function called `StringCompare()`, as that one is supposed to compare strings and nothing else. From that background, I don't understand why this function is comparing integer values at first - looks like some hack.

**Comment by ronie** [comment]
> @ronie we're breaking the backwards ABI anyway right?

yup, we are.

**Comment by ronie** [comment]
> here is the issue https://github.com/xbmc/xbmc/blob/master/xbmc/GUIInfoManager.cpp#L934

@da-anda i don't think cat.name on/off/yes/no are ever used by skins, they probably can be removed safely.

> i have no idea why there's special treatment for the SYSTEM_ALWAYS_FALSE / SYSTEM_ALWAYS_TRUE.

@mkortstiege probably for conditions like  `<visible>false</visible>`

it's a known bug that skins can't use 'true' or 'false' inside a stringcompare.
pieh mentioned it needed fixing years go, but apparently never got to it:
http://forum.kodi.tv/showthread.php?tid=162948&pid=1402461#pid1402461

**Comment by ronie** [comment]
would this be a proper fix?
https://github.com/ronie/xbmc/commit/69fb20fcbcc5b8d9b9f0abd0b4776dfedbeeab90

**Comment by da-anda** [comment]
@ronie - how do we know that the second param of stringcompare is one of the trigger words and not the first one? I mean, is the order forced somewhere? If not, then this unfortunately won't fix all cases.

I'm also having a look at that class right now. My idea was to only apply the boolean conversion in a boolean operation, so rip it out from TranslateSingleString and apply a second processing step "convertToBoolean" on the result of TranslateSingleString for boolean stuff. Just haven't found the correct spot where to inject that second processing step yet.

**Comment by da-anda** [comment]
Boy, this code is anything but easy to read and understand. I would have to dig much deeper into it, but I think the only place where the boolean conversion from the string "true" to the int is required is here: https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/info/InfoExpression.cpp#L33

So something like this might work:
```
m_condition = g_infoManager.TranslateBooleanString(expression, m_listItemDependent);
// if expression didn't  match a boolean trigger word, do full translation
if (m_condition == 0)
  m_condition = g_infoManager.TranslateSingleString(expression, m_listItemDependent);
```
Or maybe the other way around - first do a TranslateSingleString() and then translate the result into one of the boolean consts. But as TranslateSingleString aways returns some integer (haven't figured yet if it's possible to get the string representation back somehow), the example above might be more save? Ideas welcome.

**Comment by ronie** [comment]
> how do we know that the second param of stringcompare is one of the trigger words and not the first one? I mean, is the order forced somewhere? If not, then this unfortunately won't fix all cases.

@da-anda if you look strictly at the code, you're correct indeed.
but according to the docs, the first param *has* to be an infolabel,
so it's not likely to be an issue in real world usage.

for instance, skins will never use something like:
`StringCompare(false,some_infolabel_that_returns_false)`
but yes, if they did it will fail even with my suggested fix.

**Comment by MartijnKaijser** [comment]
If still needed please open a new PR and reference this one.

**Comment by da-anda** [comment]
yes, this PR still makes sense. But as said, I'd simply replace the numeric values by strings, as I really doubt skins need the numeric one for anything (it's also subject to change with every added enum).

**Pull request closed without merging**
