### PR TITLE
[docs] Add references of used dependencies to the readme

### PR DESCRIPTION
**Pull request by MartijnKaijser**
## Description
Add links to all dependency websites/sources

## Motivation and Context
Don't need to search where they are hosted when you want to update them

### CODE REVIEW

**Comment by Razzeee** [comment]
Is c-pluff supposed to be in this list?

**Comment by Rechi** [comment]
No, because you can't use the upstream version (plugin vs addon xml tag and maybe others).

**Comment by Razzeee** [comment]
Not sure if I get you, but aren't we the upstream for our version of c-pluff? So include it just for sake of completion?

**Comment by phunkyfish** [comment]
PR closed as it appears to be abandoned by the author. 

If the author would like it kept open please just request so on the PR. If you feel there is still merit in merging this PR you can request the label be changed to `PR Cleanup: Backburner`.

**Pull request closed without merging**
