### PR TITLE
[skin.estuary] make on addon info dialog description text height a small tick bigger

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description

This to prevent scrolling if the amount of lines match his Text area size.
Bevore was there always a scroll without any following content.

## Screenshots (if appropriate):

Text like them was scrolling always before:
Bildschirmfoto von 2020-08-11 20-24-16

This a view where scrolling needed (to see spaces on top and bottom now):
Bildschirmfoto von 2020-08-11 20-24-26

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by ronie — APPROVED** [review]
looks good to me, thx!

**Comment by AlwinEsch** [comment]
Thanks to you!

**Comment by HitcherUK** [comment]
Can I ask what resolutions this was tested at?

I only ask because I've found what works for 720p doesn't work for 1080p and vise versa when it comes to text boxes.

**Comment by AlwinEsch** [comment]
Has used here 2160p, didn't pay attention to the resolutions that there are differences.
Will check with the different ones.

**Comment by AlwinEsch** [comment]
Have rechecked on my Linux (maybe OS related) there it was excpet 1280x960p OK.

By the 1280x960p it was like them (few pixels on lower line):
Bildschirmfoto von 2020-08-12 12-02-54

**Comment by ronie** [comment]
i'd tested it on a 1080p (16x9) monitor.

**Pull request merged**
