### PR TITLE
Initalize vars claimed by valgrind / write classname instead 'PVR' in…

### PR DESCRIPTION
**Pull request by ghost**
… PVRChannelGroups:LOGDEBUG to make debugging easier

I wasn't able to read my valgrind log because of the mass of messages (as I remember GUIShader was the worst one), I have eliminated all the others and now it looks clean.

### CODE REVIEW

**Comment by hudokkow** [comment]
Thanks, looks good.
jenkins build this please

**Comment by mkortstiege** [comment]
Not sure about the platinum change. Is this our code or should it be send upstream? @Montellese mind having a look?

**Comment by Paxxi** [comment]
@mkortstiege Upstreaming can be looked at but no reason to block this pr.

**Comment by MilhouseVH** [comment]
Confirming notification problem reported by @Uukrull.

Easy way to reproduce (change port 8080 to whatever your webserver is using):
```
curl --data-binary '{"jsonrpc": "2.0", "params": {"message": "This is the message", "image": "error", "displaytime": 5000, "title": "This Is the title"}, "method": "GUI.ShowNotification", "id": "libNotification"}' -H 'content-type:application/json;' 'http://localhost:8080/jsonrpc'
```
should produce a notification with title "This Is the title" and message "This is the message" text, and Error icon, but currently there is no text.

**Pull request merged**
