### PR TITLE
pinsys keys update in Lircmap.xml

### PR DESCRIPTION
**Pull request by hrotkogabor**
PinnacleSysPCTVRemote remote keys for lirc 0.9.0

### CODE REVIEW

**Comment by mkortstiege** [comment]
@sraue, @stefansaraev should we keep the old names for backward compatibility?

**Comment by stefansaraev** [comment]
@mkortstiege well as you wish, I am not an expert here, but old names like "FForward" make no sense :)

**Comment by mkortstiege** [comment]
Yeah, looks strange. I am all for nuking old stuff and completely rely on the new KEY_ names. Will push this one in later today if there are no objections.

**Comment by MartijnKaijser** [comment]
@hrotkogabor please fix the changes by only use tabs and not spaces. 
Squash the changes into a single commit and force push the changes to the same branch

**Comment by hrotkogabor** [comment]
done

**Comment by mkortstiege** [comment]
Please squash changes into a single commit.

**Comment by hrotkogabor** [comment]
finally I squashed it ...

**Pull request merged**
