### PR TITLE
dvdplayer: fix vc1 hwaccel like vdpau - work around an ffmpeg issue

### PR DESCRIPTION
**Pull request by FernetMenta**
fixes not working vc1 for vdpau

### CODE REVIEW

**Comment by fritsch** [comment]
jenkins build this please

**Comment by fritsch** [comment]
@MartijnKaijser Please consider this during your next merge spree

**Comment by MartijnKaijser** [comment]
If you guys agree considering this fix for 15.0 I'm not stopping you merging this.

**Comment by fritsch** [comment]
Thanks @FernetMenta

**Pull request merged**
