### PR TITLE
[Windows][Xbox] Bump Python to 3.8.15 and OpenSSL to 1.1.1q

### PR DESCRIPTION
**Pull request by thexai**
## Description
Bump Python to 3.8.15
Bump OpenSSL to 1.1.1q

## Motivation and context
Should fix recent Xbox issues https://forum.kodi.tv/showthread.php?tid=369438

In addition to Python 3.8.15 its own fixes and improvements, avoids link `Shlwapi.lib` on UWP build (now only is used on desktop build). I think this is likely one of the causes ~or the root cause~ of the recent issues. It also coincides that it is since Xbox uses an OS based on Windows 11 22H2 (same build number 22621).

`Running on Microsoft Xbox Series S with WINDOWS 10.0.22621.1836, kernel: WINDOWS x86 64-bit version 10.0.22621.1836`

Related code changes here: https://github.com/thexai/cpython/commits/kodi/3.8

**EDIT:** 
Root cause is incompatible calls to `CreateFile2` and `CreateDirectoryW` (from Windows 11 22H2 update).
Fixed in https://github.com/thexai/cpython/commit/ff25115e850caf01749c03e747f3b436b279775a

## How has this been tested
Runtime tested on Windows x64 and Xbox Series S (developer mode only). 
In developer mode issue is not reproducible BUT is reproducible in Windows 11 22H2 (desktop) executing UWP build.

## What is the effect on users?
Should fix recent add-ons Xbox issues but untested in Retail mode / Matrix branch

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by afedchin — APPROVED** [review]

**Comment by thexai** [comment]
@wsnipex 
To finish this PR we need to upload new dependencies generated in GitHub actions (https://github.com/xbmc/kodi-deps/actions/runs/3261862730) to mirrors:

**Python 3.8.15** (new build):
```
python-3.8.15-win10-arm-v142-20221017.7z
python-3.8.15-win10-win32-v142-20221017.7z
python-3.8.15-win10-x64-v142-20221017.7z
python-3.8.15-win32-v142-20221017.7z
python-3.8.15-x64-v142-20221017.7z
```

**OpenSSL 1.1.1q**
```
openssl-1.1.1q-win10-arm-v142-20221017.7z
openssl-1.1.1q-win10-win32-v142-20221017.7z
openssl-1.1.1q-win10-x64-v142-20221017.7z
openssl-1.1.1q-win32-v142-20221017.7z
openssl-1.1.1q-x64-v142-20221017.7z
```

Files also posted in Slack

**Comment by tunip3** [comment]
CreateFile2 and createdirectoryw both have uwp safe equivalents called CreateFile2fromapp and createdirectorywfromapp and would allow it to work outside of appdata

https://learn.microsoft.com/en-us/windows/win32/api/fileapifromapp/

**Comment by afedchin** [comment]
> CreateFile2 and createdirectoryw both have uwp safe equivalents called CreateFile2fromapp and createdirectorywfromapp and would allow it to work outside of appdata

and what it changes? an application can't open an item from outside security rights

**Comment by thexai** [comment]
Tested `CreateDirectoryFromAppW` to leave no possibility unexplored:

```c++
#ifdef MS_APP
#include <fileapifromapp.h>
    result = CreateDirectoryFromAppW(path->wide, NULL);
#else
    result = CreateDirectoryW(path->wide, NULL);
#endif
```

https://github.com/thexai/cpython/commit/fab4081da9442cbb88814f4207d5ae62dddb7422

As expected, this alone is not enough to fix things.

test

`Py_Initialize`   tooks 1007 ms

And are produced 15 attempts to use CreateDirectory in places not allowed:

test2

This is only calling  Py_Initialize one time, running Python addons is much worse....

On the other hand this is with PR code:

PR

Only 49 ms

Note that Python is not a native UWP app and makes calls thinking it's on Win32. Also, being multi-platform, it's not even very optimized for Windows. When returning errors, it also makes several retries which makes the problem exponentially worse. It seems surprising but just initializing Python takes hundreds of `CreateFile2` calls since it uses it to explore all the directory trees where the .py modules are.

Actually this is a problem that has always been latent, the only thing that has changed with Windows 11 22H2 is that the disallowed calls (when return errors) take longer than before.

Therefore, it can be said that with the changes in this PR, Python will now be faster even than before Xbox update.

On Windows x64 it took ~42 ms but the previous PR (https://github.com/xbmc/xbmc/pull/21997) also helps improve things and now it's 19 ms.

**Comment by thexai** [comment]
In case someone wants to do more tests, here are the Python builds:

v142 is the PR code
https://www.mediafire.com/file/379l99a8dsjmhry/python-3.8.15-win10-x64-v142-20221017.7z/file

v143 is test code CreateDirectoryFromAppW
https://www.mediafire.com/file/xp4nptmh4gj5vp6/python-3.8.15-win10-x64-v143-20221019.7z/file

**Comment by thexai** [comment]
Just for fun this is with Python 3.8.5  (master/Matrix branch)

**Comment by afedchin** [comment]
over 7 sec.. zomg!

**Comment by thexai** [comment]
Jenkins build this please

**Comment by spcljense** [comment]
I came here to confirm this fixed the issue in retail mode. I've edited the manifest.xml and uploaded it to my Microsoft partner center apps & games workspace as an private non public app. After the certification was successful i've downloaded it on my xbox from the store and i can 100% confirm there are no more delays. Apps open up instantly again.

Thanks Thexai.

**Comment by thexai** [comment]
Thank you for tests and confirming this.

**Comment by spcljense** [comment]
You're welcome sir.

**Pull request merged**
