### PR TITLE
[mysql] fix transaction handling by set autocommit to false when requested

### PR DESCRIPTION
**Pull request by mkortstiege**
Backport of https://github.com/xbmc/xbmc/pull/6467

### CODE REVIEW

**Comment by wsnipex** [comment]
+1, auto commit is evil

**Comment by mkortstiege** [comment]
@topfs2 ok to shove this in for b2?

**Comment by topfs2** [comment]
I'm not a sql guy so really no clue, but I trust it fixes issues?

**Comment by mkortstiege** [comment]
It does. Without i takes much longer to perform all the bulk inserts when eg. adding stuff to the library.

**Pull request merged**
