### PR TITLE
Add options to reduce framerate when Kodi is paused or not playing back video

### PR DESCRIPTION
**Pull request by spayne**
Attached is a proposal to conditionally reduce the render framerate when Kodi is either in Pause or is not playing.   I started discussing this on the Kodi forums here: http://forum.kodi.tv/showthread.php?tid=249563

Here is what the new settings look like:
reduceframerate

In terms of code it's just a few modifications in CApplication::Render to add two new behaviours: 1. use the existing limitFrames mechanism if it looks like a good time to slow down. 2. modify the sleep loop to check CWinEvents::GetQueueSize every 100 milliseconds (worst case) to reduce exit latency.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Gui setting is not acceptable. Problem must be solved without any setting

**Comment by spayne** [comment]
@un1versal: ok next time I'll rebase instead of merge
@MartijnKaijser: I commented on this in the forums.

**Comment by spayne** [comment]
I didn't mean to close it just yet.

**Comment by spayne** [comment]
In summary, this proposal saves power, but is too much like a hack that will add support complexity if integrated into master. A proper solution may become more viable once the render thread becomes split from the main thread. So from the master-branch perspective I'll close the PR.

**Pull request closed without merging**
