### PR TITLE
[CryptThreading] replace hardcoded value for CRYPTO_LOCK by macro

### PR DESCRIPTION
**Pull request by Rechi**
## Description

Replace hard coded value for CRYPTO_LOCK by macro.
## Motivation and Context

Cleanup

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@wsnipex ping

**Comment by wsnipex** [comment]
it doesn't look wrong, but does it fix anything? @jimfcarroll ping, since you added this

**Comment by MartijnKaijser** [comment]
@wsnipex related? http://trac.kodi.tv/ticket/16760

**Comment by wsnipex** [comment]
only in so far that we can scrap the whole locking function once openssl 1.1.x is used.
So it would be great if @Rechi could ifdef this for openssl versions <= 1.1.x

**Comment by Rechi** [comment]
@wsnipex do you really mean **<= 1.1.x**?

**Comment by wsnipex** [comment]
not literally. crypto locking can/should only be used on versions < 1.1.0

**Comment by Rechi** [comment]
I mean if I should check `version < 1.2` (what your first comment means) or `version < 1.1`? (obviously no string checks)

**Comment by wsnipex** [comment]
< 1.1.0

**Comment by Rechi** [comment]
@wsnipex updated

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
thanks! Can someone try this with openssl 1.1.0? maybe @MilhouseVH ?

**Comment by MilhouseVH** [comment]
I can include this in tonight's LibreELEC build, however we use LibreSSL 2.3.5 instead of OpenSSL (LibreSSL has `#define OPENSSL_VERSION_NUMBER 0x20000000L`). This builds OK, not entirely sure how to test...

**Comment by MilhouseVH** [comment]
This has been in my builds for 2 weeks, no reported issues.

**Comment by jimfcarroll** [comment]
This was originally added due to inconsistencies in curl libraries. I don't recall all of the details but I'd love to see it go if there's a better way to handle it now.

**Pull request merged**
