### PR TITLE
dvdplayer: set default screen region for dvb subs

### PR DESCRIPTION
**Pull request by FernetMenta**
fixes dvb subs for streams that don't set screen dimensions

### CODE REVIEW

**Comment by stefansaraev** [comment]
so this fixes https://github.com/xbmc/xbmc/pull/7719#commitcomment-12774136 ?

jenkins build this please

**Comment by Jalle19** [comment]
I saw the issue mentioned in #7719 happen on a 1080i stream, is the resolution assumption made here still valid?

**Comment by FernetMenta** [comment]
I think so

**Comment by popcornmix** [comment]
This PR fixes the bug reported here: 
http://forum.kodi.tv/showthread.php?tid=231092&pid=2088213#pid2088213

**Comment by Leatherface75** [comment]
Seens to work now when i tested it.
Only issue now i have is subs are out of sync on some channels sometimes it's enough to go to delaysettings and change it and then change it back to 0 and it's in sync again but that's another issue.

**Comment by stefansaraev** [comment]
this needs backport. right ?

**Comment by ace20022** [comment]
@Fernetmenta There seems to be problem with some sub streams, cf. http://forum.kodi.tv/showthread.php?tid=239774 . I'm not sure if it's an encoder problem, since ffplay shows the subs.

**Comment by FernetMenta** [comment]
there is close to zero info in the linked forum thread.

**Comment by FernetMenta** [comment]
@ace20022 can you provide the sample you were talking about?

**Pull request merged**
