### PR TITLE
[python] use our provided CA cert if building with unified deps

### PR DESCRIPTION
**Pull request by wsnipex**
follow up from https://github.com/xbmc/xbmc/pull/9424

Not really well tested, specially the cmake side is untested due to lack of time.
@FernetMenta @hudokkow @fetzerch @ksooo

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
imo too complex and does not fit every case. it is much easier to set the environment variable, if desired, before Kodi is started

**Comment by wsnipex** [comment]
which you are still free to do.
Which case is not covered?

**Comment by FernetMenta** [comment]
building kodi with depends is not sufficient for using kodi provided certificate. one may still wand to use her/his own cert. further, setting environment variables in code is an abuse of those.

**Comment by wsnipex** [comment]
ok. You're welcome to come up with a "proper" solution.

**Pull request closed without merging**
