### PR TITLE
add functionality to set custom names for tvshow seasons

### PR DESCRIPTION
**Pull request by Montellese**
The first commit adds the functionality to allow users to set a custom name/title for tvshow seasons. This has been requested quite a few times in the forum and it's a rather small change. The seasons will still be sorted by season number independent of the name/title that has been set for a season.

The second commit moves the "Choose art" context button for tvshow seasons from the main context menu to the "Manage..." sub-menu which was introduced by the first commit (to support "Edit title").

### CODE REVIEW

**Comment by notspiff** [comment]
no nfo support?

**Comment by Montellese** [comment]
@notspiff: Do we support season-level NFOs? Or would you just put it into the episode NFO?

**Comment by notspiff** [comment]
No season level nfo but i would stick it on the show level.

**Comment by Montellese** [comment]
I checked the videodb code and neither `AddTvShow()` nor `SetDetailsForTvShow()` or `UpdateDetailsForTvShow()` adds/sets seasons (except for season artwork and the "all seasons"). But `SetDetailsForEpisode()` adds the season the episode belongs to (but doesn't call `SetDetailsForSeason()`).

I'll look into reading something like
```
<seasons>
  <season number="1" title="foo" />
  <season number="2" title="bar" />
</seasons>
```
from the tvshow level NFO but this will require some special handling in `CVideoInfoScanner` because we don't store all seasons of a tvshow in `CVideoInfoTag` which is basically taking care of the NFO parsing.

**Comment by notspiff** [comment]
yeah, that's correctly summarized. i guess the main difference is that you don't have to "preallocate" the seasons - you certainly have introduced some season entity to store the names already in this pr (didnt read the code yet).

**Comment by Montellese** [comment]
I've looked into this again and it's really tedious to add NFO support because it would require adding an extra property to `CVideoInfoTag` which would only be used for this case and it would require special handling in the import and export handling.
I know that missing NFO support means that people can't export their library and re-import it and get the exact same library but I also don't like adding all this special code for this small feature.

@MartijnKaijser @mkortstiege what do you think?

**Comment by mkortstiege** [comment]
Hm. Are we able to fetch season names from `thetvdb` or any other site? I agree, feels a bit overkill to add for something that has to be managed manually or at best by 3rd party tools.

**Comment by Montellese** [comment]
I have no idea if a scraper site offers this kind of information. Right now it can only be added manually through our GUI.

**Comment by MartijnKaijser** [comment]
so far i don't think any site has this. neither tvdb or tmdb (yes they do tv shows now). 
TVDB is coming with a new API and we could suggest it to TMDB as well

**Comment by anaconda** [comment]
TMDB supports this: http://www.themoviedb.org/tv/61374

http://api.themoviedb.org/3/tv/61374/season/2?api_key=57983e31fb435df4df77afb854740ea9 returns:
https://p.6core.net/p/U41cAJRpEiVks9jrRolU7AEO

**Comment by Montellese** [comment]
@anaconda: Interesting. In that case it might make sense to add NFO support for it. Does anyone know how our scrapers work exactly? Can they retrieve all seasons for a tvshow and store the season numbers and names into the tvshow XML/NFO?

**Comment by Montellese** [comment]
I just noticed that I revisited this a few weeks ago but never updated the PR. I've added NFO serialization/deserialization support for named seasons to the tvshow's NFO. It's not ideal but I couldn't think of a cleaner approach.

I haven't tested this with any scrapers because they'd have to be updated. Obviously it would be nice if we could test it together with a scraper before merging it. But manually setting the name in the GUI has been tested and is working.

**Comment by Razzeee** [comment]
Can't find a good example on tmdb.
TVDB has some, but their basically limited to other numbers like year numbers (e.g. 2013, 2014)

**Comment by Montellese** [comment]
So how do we want to proceed here? Setting the names manually in the GUI or manually in NFOs is working. There's no scraper integration however.

**Comment by notspiff** [comment]
If nfo is there why wouldnt scraper be? Unless stuff changed fundamentally a scraper outputs a nfo file.

**Comment by Montellese** [comment]
@notspiff: What I meant with that was that there's no scraper making use of it yet so it hasn't been tested in that context (e.g. does it make sense to put that information into the tvshow's NFO or should it be in the episodes' NFOs?).

**Comment by notspiff** [comment]
Right. I still.claim tvshow. Duping per episode is just that, duping, and
you grt into the funny of which to use when there are two values from diff
nfo files and such.
8. okt. 2015 08:54 skrev "Sascha Montellese" <notifications@github.com>:

**Comment by Montellese** [comment]
jenkins build this please

**Comment by Montellese** [comment]
So are there any objections here? @mkortstiege @Razzeee

**Comment by Razzeee** [comment]
Nope, all fine.
I'm watching https://tmdb.lighthouseapp.com/projects/83077/tickets/510-add-season-name-to-show-season-list#ticket-510-1 if he gets it in I will have a go at the tmdb tv scraper.

**Comment by DanCooper** [comment]
Nice. But why you don't have added ALL informations for seasons?
For next release of Ember we have added this to tvshow.nfo with this XML structure:
```xml
<seasons>
    <seasondetails>
      <aired>2010-12-05</aired>
      <season>0</season>
      <title>Specials</title>
      <tvdb>137481</tvdb>
      <tmdb>3627</tmdb>
    </seasondetails>
    <seasondetails>
      <aired>2011-04-17</aired>
      <season>1</season>
      <title>Staffel 1</title>
      <plot>Die Serie beginnt zu einem Zeitpunkt, als ein neuer Machtkampf zu entbrennen droht. Die maßgeblich Beteiligten sind die mächtigen Adelsfamilien Stark, Lannister und Baratheon. Robert Baratheon fragt seinen alten Freund Eddard Stark, ob dieser ihm als sein oberster Berater dienen will. Eddard vermutet, dass sein Vorgänger Jon Arryn, der für Robert und ihn wie ein Ersatzvater war, ermordet worden ist. Es stellt sich heraus, dass das Haus Lannister, aus dem auch Roberts Ehefrau Cersei stammt, eigene Ziele hinsichtlich des Eisernen Throns verfolgt. Der Konflikt zwischen diesen Familien und den anderen einflussreichen Adelshäusern (wie den Graufreuds, Tullys, Arryns und Tyrells) führt schließlich zum Bürgerkrieg. Gleichzeitig erwacht im Norden, jenseits des gewaltigen Eiswalls, der die sieben Königreiche dort abschirmt, eine uralte und gefährliche Macht, von der aber während der Thronkämpfe im Süden kaum jemand Notiz nimmt. Jenseits des Meeres auf dem Kontinent Essos planen in der Zwischenzeit die letzten überlebenden Mitglieder der ehemaligen Königsfamilie Targaryen die Rückkehr nach Westeros, um den Thron zurückzugewinnen.</plot>
      <tvdb>364731</tvdb>
      <tmdb>3624</tmdb>
    </seasondetails>
    <seasondetails>
      <aired>2012-04-01</aired>
      <season>2</season>
      <title>Staffel 2</title>
      <plot>Im Reich tobt ein Bürgerkrieg zwischen Stannis und Renly Baratheon sowie dem neuen König Joffrey I. Baratheon, der außergewöhnlich tyrannisch herrscht. Unterstützung erhält Joffrey dabei vom Haus Lannister. Doch Stannis und Renly sind uneinig und streiten sich darum, wer der rechtmäßige Nachfolger ihres Bruders ist. Renly stützt sich auf die Sturmlande und auf das einflussreiche Haus Tyrell, während Stannis immer mehr der mysteriösen Melisandre Vertrauen schenkt. Der Norden hat sich unter Robb Stark für unabhängig erklärt und führt gegen die Lannisters in den Flusslanden und im Westen Krieg. Arya Stark ist auf der Flucht, ihre Schwester Sansa ist eine Geisel der Lannisters in Königsmund, wohingegen Jaime Lannister eine Geisel der Starks ist. Die neue amtierende Hand Tyrion Lannister versucht in Königsmund, die Lage unter Kontrolle zu halten, wobei er sich gegen seine intrigante Schwester Cersei durchsetzen muss. Auf den Eiseninseln plant in der Zwischenzeit Balon Graufreud, von den Thronkämpfen im Reich zu profitieren. Die Männer der Nachtwache unternehmen eine Expedition in das Land jenseits der Mauer, um die unklare Lage vor Ort zu untersuchen. Währenddessen kämpft Daenerys Targaryen auf dem Kontinent Essos um ihr Leben und das Bestehen ihrer Gefolgschaft. Ihr Ziel ist es, Westeros zu erreichen und mit Hilfe ihrer Drachen den Eisernen Thron zu gewinnen.</plot>
      <tvdb>473271</tvdb>
      <tmdb>3625</tmdb>
    </seasondetails>
  </seasons>
```

It whould be great if Kodi also can use this data (or a smillar structure if you don't like ours).

**Comment by Montellese** [comment]
We currently don't support any metadata for seasons apart from artwork, season number and now the custom title. So what you propose is a lot more work.

**Comment by DanCooper** [comment]
Can all this additional data not handled in the same way/time like the new "title" field?
I know, it's more work and the default skin does not support displaying all this additional informations, but I thought it's easier to add the new informations at the "same" time you also added another new field...
I'd implement the changes by myself, but I do not speak C++ or C# (only vb.NET).

**Comment by vbat99** [comment]
What happens if a tvshow.nfo has Season1 and season 2 custom naming, and then there is a Season 3?
IIRC Kodi doesn't re-read the tvshow.nfo after initial scraping into the database.

So users can not add extra custom season names after initial tvshow.nfo addition, except via the gui?

**Comment by NedScott** [comment]
Yes. Any additional changes would require Kodi to re-export the NFO files and overwrite the old ones, or manually updating the NFO files. NFO files are only used for the initial scan of an entry.

**Comment by Montellese** [comment]
Or you manually refresh the tvshow through the user interface which should also re-read the NFO.

**Comment by DanCooper** [comment]
What exactly has been added in Kodi 17? Only the option to set season title via context menu or also "tvshow.nfo" support? Looks like this one does not work: [Link](https://github.com/xbmc/xbmc/pull/6041#issuecomment-68559386)

**Comment by Montellese** [comment]
@DanCooper: Yes that was just an example. It's
```
<namedseason number="1">some title</namedseason>
```

**Comment by DanCooper** [comment]
Thank you for the fast answer. I've now tested, but the result looks wrong: [Screenshot](http://i.imgur.com/NWY6Hwk.png)

**Comment by Montellese** [comment]
You're right. Thanks for the report. It should be fixed with #10641.

**Comment by DanCooper** [comment]
Great :-)

In case of (maybe) later support of season plot/overview and all other unification of all other nodes like <set>:
Why do you not use a better XML code for the seasons? XML attributes are a bad solution for this IMHO. If you whould use something like this it will be easy to add more nodes in a later state:

`<seasons>
    <seasondetails>
      <aired>2010-12-05</aired>
      <season>0</season>
      <title>Specials</title>
      <tvdb>137481</tvdb>
      <tmdb>3627</tmdb>
    </seasondetails>
    <seasondetails>
      <aired>2011-04-17</aired>
      <season>1</season>
      <title>Staffel 1</title>
      <plot>some plot</plot>
      <tvdb>364731</tvdb>
      <tmdb>3624</tmdb>
    </seasondetails>
    <seasondetails>
      <aired>2012-04-01</aired>
      <season>2</season>
      <title>Staffel 2</title>
      <plot>some text</plot>
      <tvdb>473271</tvdb>
      <tmdb>3625</tmdb>
    </seasondetails>
  </seasons>`

I know no one will be do the work to add more fields in database, but I think our XML schema is better and future proof and should be a big problem to use for Kodi.

**Pull request merged**
