### PR TITLE
[gui] FileBrowser: remove "mirror image" button

### PR DESCRIPTION
**Pull request by phil65**
stupid junk, go away :)
@ronie 
@Razzeee

### CODE REVIEW

**Comment by Razzeee** [comment]
Code seems fine. You might want to squash already.

Not sure if this can really go, that's up to the skinners ;)

**Comment by ronie** [comment]
> Not sure if this can really go, that's up to the skinners ;)

removing functionality from kodi core should not be just a skinners decision ;-)

**Comment by notspiff** [comment]
just in case you don't know what it is for: it's used for flipping fanart. it was a very much requested feature when i added it.

**Comment by phil65** [comment]
It took me some time to figure out what that option should be good for. :)
I think anyone who has the ambition to set up perfect artwork for his collection should be able to edit the artwork "manually".
Also, correct skin support needs hacks (stringcompare on a radiobutton)
If any team member objects I am fine with closing this. Just my opinion as someone dealing with UX, this should go.

**Comment by da-anda** [comment]
the feature itself might come in handy at times, but the location where it's implemented is IMO wrong and odd. It would be better suited in the "choose art" dialog (which should be renamed to "manage art" anyways). But to be usable in this dialog, the entire dialog needs some refactoring, which it might need anyways so that optional artwork can also be removed again.

**Comment by notspiff** [comment]
Makes sense  That dialog didnt exist at that time, it used
dialogfilebrowser directly.
6. jan. 2016 18:45 skrev "da-anda" <notifications@github.com>:

**Comment by phil65** [comment]
yeah adding a contextmenu in that art dialog showing "remove" and "flip vertically" might be an option.
FileBrowser is the wrong location though, so let´s remove it there.

**Comment by Razzeee** [comment]
@phil65 
can we remove it when we have prepared the code needed for it in the other dialog?

**Comment by MartijnKaijser** [comment]
@phil65 care to update this so we can kill this mirror image?

**Comment by Razzeee** [comment]
Did this ever make it into estuary/estouchy? And did somebody read about people missing it?

**Comment by ronie** [comment]
it hasn't been removed, so nobody complained about missing it.

relocating it instead of removing, would be preferred imo.

**Comment by MartijnKaijser** [comment]
Nudge :)

**Comment by phunkyfish** [comment]
PR closed as it appears to be abandoned by the author.

If the author would like it kept open please just request so on the PR.

**Pull request closed without merging**
