### PR TITLE
Reverse B button actions in joystick keymap

### PR DESCRIPTION
**Pull request by bb10**
## Description
Reverted B back to the original action of Stop and changed the long press action to Fullscreen.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [X] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Comment by EmilVogt** [comment]
Makes sense to me. I would propose to add the three lines
```
<a>Pause</a>
<b>Stop</b>
<b holdtime="500">FullScreen</b>
```
also to `<FullscreenLiveTV>` and `<FullscreenRadio>` .

**Comment by garbear** [comment]
@bb10 do you want to add keys to FullscreenLiveTV and FullscreenRadio or should this be merged?

**Comment by bb10** [comment]
Done!
I don't use either Live TV nor Radio on Kodi, so I'll just assume that @EmilVogt knows what he's talking about and these changes make sense. 😄

**Comment by garbear** [comment]
Sounds good to me :)

**Pull request merged**
