### PR TITLE
[Log] Fix segfault on kodi shutdown

### PR DESCRIPTION
**Pull request by peak3d**
## Description
See title

## Motivation and Context
Fix Segmentation fault on each windows shutdown.

## How Has This Been Tested?
Win64 Debug build, Start kodi -> Terminate kodi

## Types of change
- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Comment by Rechi** [comment]
This causes segfaults in `TestRegExpLog` and `Testlog`.

**Comment by MilhouseVH** [comment]
@peakd does [this discussion](https://forum.kodi.tv/showthread.php?tid=298462&pid=2765500#pid2765500) pertain to the problem being fixed by this PR (hopefully it does).

Last week I noticed that Kodi on RPi is always crashing when stopping Kodi, but didn't have the time to investigate further.

**Comment by peak3d** [comment]
@MilhouseVH unfortunately my gut feeling is that this PR does not fix the root issue.
There is some other component / global which seems to be accessed after destruction.

This one here just ensures that we don't log from globals which are destructed after the log global.

**Comment by ksooo** [comment]
My recent changes eliminated the g_advancedSettings global. Maybe log now accesses advanced settings after it got destructed? 

Does adding null checks for SettingsComponent and AdvancedSettings fix the problem?

**Pull request closed without merging**
