### PR TITLE
Porting fixes

### PR DESCRIPTION
**Pull request by rbalint**
Tested on Debian buildds:
https://buildd.debian.org/status/package.php?p=kodi&suite=unstable

### CODE REVIEW

**Comment by wsnipex** [comment]
out of curiosity, did anyone ever actually start/run kodi on s390x? Even though I could test this myself, I don't really want to, cause I'd have to set up X first.

**Comment by rbalint** [comment]
I think you could be the first. :-)
I have no access to any s390x machine where I could test X11 applications.

**Comment by wsnipex** [comment]
if I'm ever horribly bored at work, I might give it a try.
Even if the changes are minimal (and fine for me), whats the point? I mean kodi will never build, far less run on all (arcane) platforms debian supports.

**Comment by rbalint** [comment]
Kodi already did build on all release architectures, I just made gtests to pass for most of them.
Sometimes we discover bugs more easily on exotic architectures, but probably the s390x port won't bring much to the table for Kodi. 
BTW I tested starting Kodi on s390x and it exited due to missing GLX but did not crash earlier.

**Pull request merged**
