### PR TITLE
DVDDemuxFFmpeg: fix start_time casting issue

### PR DESCRIPTION
**Pull request by samnazarko**
Fixes issue introduced in https://github.com/xbmc/xbmc/commit/c94f95b08cf9a71789dd9f5181616acc57f84fba.

### CODE REVIEW

**Review by fuzzard — APPROVED** [review]

**Comment by ksooo** [comment]
Which issue exactly is fixed by this PR?

**Comment by samnazarko** [comment]
Discussed In core in Kodi Slack - this fix is needed for 3D MVC.

**Comment by enen92** [comment]
Thanks for the fix Sam

**Comment by ksooo** [comment]
> Discussed In core in Kodi Slack

This cannot be seen by people outside Team Kodi. Maybe next time you should document the issue in a way that anybody can see it. We are an open source project and this is a public repo. For me, it is still not clear what the issue was.

**Comment by samnazarko** [comment]
After the introduction of this commit, 3D ISO playback was broken. When investigating why, the incorrect casting was determined as one of the causes. 

As 3D MVC support is unfortunately not upstream and not platform independent, we only upstreamed what was relevant. 

From a downstream perspective:

>The problem was that the convert() fix which was introduced by Kodi 19.5 corrected the timestamp with the start time of the stream. When you start a 3D iso, then the two 3D streams (h.264 + mvc) are merged on the fly. But that convert fix corrected only the h.264 stream and not the mvc one. That's why the merge of the two streams did not work because the timestamps of the two streams did not match.

Hopefully this sheds some light.

**Pull request merged**
