### PR TITLE
[depends][darwin] configure: remove special tarballs dir & nativeprefix

### PR DESCRIPTION
**Pull request by Rechi**
## Description
Remove special settings for darwin in tools/depends/configure.ac for the tarballs location and the name of the nativeprefix directory. 

## Motivation and Context
Tried to cross compile android and couldn't use the already compiled native depends and needed to redownload the tarballs again.
The nativeprefix was most likely needed at the xcode project time.

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by wsnipex — APPROVED** [review]
looks good to me

**Comment by Rechi** [comment]
jenkins build and merge

**Comment by Rechi** [comment]
jenkins error occurred
jenkins build and merge

**Comment by Rechi** [comment]
jenkins error occurred again, so next try
jenkins build and merge

**Comment by MartijnKaijser** [comment]
Stop using build and merge it doesn't work

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by Rechi** [comment]
this needs some additional changes as other scripts have hardcoded `buildtools-native`

**Comment by Rechi** [comment]
updated, not it should build

**Comment by Rechi** [comment]
jenkins build this please

**Comment by Rechi** [comment]
@wsnipex @Memphiz any objections?

**Comment by wsnipex** [comment]
fine for me

**Comment by Memphiz** [comment]
Whoops - sorry - that last comment was me of course.

**Pull request merged**
