### PR TITLE
SysfsPath: add multi line support

### PR DESCRIPTION
**Pull request by Portisch**
Get all chars of the sysfs file.

## Description
Right now `SysfsPath.Get` only support single line when request a string from `sysfs`.

## Motivation and context
Be able to get whole sysfs file content.

## How has this been tested?
Result by `getline`:
```text
2021-11-27 07:50:34.889 T:4961     INFO <general>: aml_probe_resolutions: Get by 'getline' from '/sys/class/amhdmitx/amhdmitx0/disp_cap': 480i60hz
```

Result by `istreambuf_iterator`:
```text
2021-11-27 07:50:34.889 T:4961     INFO <general>: aml_probe_resolutions: Get by 'istreambuf_iterator' from '/sys/class/amhdmitx/amhdmitx0/disp_cap': 480i60hz
                                                   576i50hz
                                                   480p60hz
                                                   576p50hz
                                                   720p60hz
                                                   1080i60hz
                                                   1080p60hz*
                                                   720p50hz
                                                   1080i50hz
                                                   1080p50hz
```

No other difference could be recorded on tests on Linux platform.

## What is the effect on users?
It may include filtered chars by `getline` like new line `"\n"` on the end.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by Portisch** [comment]
Should be a "test" like this included?

```c
diff --git a/xbmc/platform/linux/test/TestSysfsPath.cpp b/xbmc/platform/linux/test/TestSysfsPath.cpp
index 2c0c27a1a6..74f41575db 100644
--- a/xbmc/platform/linux/test/TestSysfsPath.cpp
+++ b/xbmc/platform/linux/test/TestSysfsPath.cpp
@@ -84,6 +84,22 @@ TEST_F(TestSysfsPath, SysfsPathTestLongString)
   std::remove(filepath.c_str());
 }
 
+TEST_F(TestSysfsPath, SysfsPathTestMultiLine)
+{
+  std::string filepath = GetTestFilePath();
+  std::ofstream m_output{filepath};
+
+  std::string temp{"line1\nline2\nline3"};
+  m_output << temp;
+  m_output.close();
+
+  CSysfsPath path(filepath);
+  ASSERT_TRUE(path.Exists());
+  EXPECT_EQ(path.Get<std::string>(), "line1\nline2\nline3");
+
+  std::remove(filepath.c_str());
+}
+
 TEST_F(TestSysfsPath, SysfsPathTestPathDoesNotExist)
 {
   CSysfsPath otherPath{"/thispathdoesnotexist"};
```

**Comment by lrusak** [comment]
Yes add the test as it's run as part of the test suite on Jenkins.

**Comment by wsnipex** [comment]
I'd cap that read to a max size. 4-8KB should be plenty.

**Comment by Portisch** [comment]
But how to inform the user the ifstream was cut? The user will get just a part of the data if the the 4k limit was exceeded and have no information about EOF or not. It's the same "problem" with `getline`.
In general it might be better to return the status and return the read string as parameter. But this would touch much more places in the source. With the returned status the user can decide how to proceed.

**Comment by Portisch** [comment]
No news?

There would be a "Set" also already be available:
https://github.com/CoreELEC/xbmc/commit/ac01705b3785b5944383f0ae6ebbed2d556dc6c9

**Comment by Portisch** [comment]
Another issue found by the "replacement" of working code...
https://github.com/xbmc/xbmc/pull/20600/commits/f264b59c5bf2fc2cd4a90f13929ae6e193a0f774

**Comment by lrusak** [comment]
I'm hesitant to even review this because the changes aren't actually used in Kodi master.

The interface will likely improve now that we have c++17 and access to std::filesystem.

I think your multi line changes are still valid but currently there is no use case for it.

**Pull request closed without merging**
