### PR TITLE
[Depends] Replace distribute with setuptools.

### PR DESCRIPTION
**Pull request by mrdominuzq**
im a bit puzzled why we have both distribute and setuptools. so here it goes :)

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@wsnipex ping

**Comment by wsnipex** [comment]
jenkins buiild this please

**Comment by MartijnKaijser** [comment]
Seems it didn't start
Jenkins build this please

**Comment by MartijnKaijser** [comment]
It helps if we actually upload the file to the server.
Jenkins build this please again

**Comment by wsnipex** [comment]
out of curiosity, why do you remove the existing setuptools makefile in favor of the one for distutils?

**Comment by mrdominuzq** [comment]
Do you mean distribute :)?  Because distribute is a depecrated fork of setuptools and i Can't see why having it for target :)

**Comment by wsnipex** [comment]
no. I mean there is a working Makefile for setuptools. Why do you delete it?

**Comment by mrdominuzq** [comment]
because i thought setuptools belongs to native and not target since we use native python to compile pillow :)

**Comment by mrdominuzq** [comment]
and it did work on my build system both for android arm x86 and osx :)

**Comment by wsnipex** [comment]
correct, we need it for native and target

**Comment by mrdominuzq** [comment]
can you explain why we need for both native and target :)?

**Comment by mrdominuzq** [comment]
Log tells to bootstrap so added bootstrap command.

**Comment by wsnipex** [comment]
jenkins buiild this please

**Comment by mrdominuzq** [comment]
typo :)

**Comment by wsnipex** [comment]
meh... jenkins build this please

**Comment by mrdominuzq** [comment]
error seems unreleated :)

**Comment by MartijnKaijser** [comment]
@mrdominuzq time to update this?

**Comment by mrdominuzq** [comment]
should be updated now :)

**Comment by mrdominuzq** [comment]
This is another aproach. https://github.com/mrdominuzq/xbmc/commit/bb71ac5f0b5da23d5b6c82cf91545ec1ada790a4

**Comment by Razzeee** [comment]
what's the plan here? rebase and review again? or do you prefere the other aproach?

**Comment by mrdominuzq** [comment]
I think i will go with the otter aproach. Will do a pr tommorow

**Comment by Razzeee** [comment]
I'll close this one for now then

**Pull request closed without merging**
