### PR TITLE
run repository update jobs in low pausable mode

### PR DESCRIPTION
**Pull request by tamland**
Fixes http://trac.kodi.tv/ticket/16271
cc @MartijnKaijser

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
this will pause the check until nothing is playing?

**Comment by tamland** [comment]
yes. any scheduled update occurring while playing will be put on hold until playback ends, like the old behaviour

**Comment by MartijnKaijser** [comment]
great thx
jenkins build and merge

**Comment by stefansaraev** [comment]
is this supposed to block forvever when one tries "check for updates" manualy while playing video/tv ?

**Comment by LS80** [comment]
I have just noticed the same issue as mentioned above.

**Pull request merged**
