### PR TITLE
[pvr] attempt to fix occasional crash when persisting channels

### PR DESCRIPTION
**Pull request by Jalle19**
This tries to fix the crash reported at http://forum.kodi.tv/showthread.php?tid=213283 (has been mentioned on IRC as well).

I'm not sure what the exact problem is, only that the crash happens in `GetLastChannelID()` which is a method we don't even need. I hope that removing this method either fixes the problem (I can't reproduce it so it's hard to say) or moves the crash somewhere else where the cause is more apparent.

@opdenkamp @xhaggi for review. See the commit messages for more justification.

### CODE REVIEW

**Comment by Jalle19** [comment]
@opdenkamp can we merge this in its current state until a better solution comes along? I'd like to see if this fixes the crash.

**Comment by FernetMenta** [comment]
if it makes things slow as @opdenkamp said, I am against it

**Comment by Jalle19** [comment]
@FernetMenta it keeps it as slow as it was before, nothing has changed in that regard. Doing some work in this area to make the whole thing more efficient is for another PR, and frankly I'd like to get @ksooo's work (not just the one branch he has PRed) in before we start looking at any major restructuring (since his changes already fix a lot).

**Comment by opdenkamp** [comment]
you only notice the slowness when doing the initial import of channels on a new setup with a slow storage backend. and indeed, it's already slow.

the change that i proposed doesn't touch any of @ksooo's work though and isn't major restructuring. instead of removing the code that handles queued writes, you can wrap it in a transaction.

**Comment by Jalle19** [comment]
@opdenkamp I guess I'll take a look at what you're suggesting.

**Comment by Jalle19** [comment]
@opdenkamp I added another fix. It turns out that whenever `UpdateLastWatched´ was called (which happens during channel switches at least), we persisted both the channel and its group. This leads to a lot of processing since persisting the group persists all channels in that group and updates the mapping between channels and groups. Somewhere in there the code crashes even with the previous commits (as seen in http://forum.kodi.tv/showthread.php?tid=213283&pid=1884158#pid1884158) so this commit tries to bypass all that code completely.

**Comment by opdenkamp** [comment]
yeah that's what i said in my first comment, it was doing a lot more 
than it should be doing when updating last watched

**Comment by Jalle19** [comment]
I told janumix to test this again, let's hope something has improved.

**Comment by opdenkamp** [comment]
haven't heard back from him I guess? this can go in either way once squashed
jenkins build this please

**Comment by FernetMenta** [comment]
this does tremendously slow down startup for my systems. I hear massiv disk activity until tv and radio menues show up in the main menu.

**Comment by FernetMenta** [comment]
m_strClientChannelName is not written to the database and triggers a persist for every channel

**Comment by Jalle19** [comment]
@FernetMenta I don't see how this can have made it any slower. Sure, it looks like the `bQueueWrite` code path has been removed but it wasn't actually used anywhere.

I'll look into the m_strClientChannelName thing.

**Comment by opdenkamp** [comment]
meh, that's what i suspected that would happen, should have tested this one :)

**Pull request merged**
