### PR TITLE
Binary addons: Multi addons

### PR DESCRIPTION
**Pull request by Montellese**
This work is inspired by @notspiff's work and adds support for addons whose content actually just consist of a list of sub-directories which are addons themselves. The main target are scrapers which are all stored in the same git repository at https://github.com/xbmc/repo-scrapers which a sub-directory for every scraper addon.
This allows us to add such a repository to the list of addons to be built with the addition of a `multi.txt` file containing a line for every actual addon to be copied to the final location. There's no support for intermediate build/compile commands.

I've taken a different approach than @notspiff making use of `ExternalProject_Add()` instead of adding custom commands.

The advantage of this is that we don't have to keep the scraperes in our code and we only have to update one git revision to sync all the default scrapers with the scraper repository.

A disadvantage is that there are no default scrapers (except for `metadata.local`) in our tree anymore so if someone builds and runs/debugs Kodi from a checkout he either doesn't have the default scrapers or he has to copy them to the `addons` directory manually to be able to use them.

### CODE REVIEW

**Comment by akva2** [comment]
@wsnipex don't you use an upload script to the ppa? can't you just pregrab them there and include in the tarball? obviously still buggers every distro with something equivalent.

this was always the plan for my buildsystem. you'd run bootstrap which would download everything, ship its output dir in the tarball and carry on doing the actual build on launchpad.

**Comment by wsnipex** [comment]
as you said, it'd work with your buildsystem pre-bootstrapped, but not really well with what we have now.
Doing this just for ubuntu leaves every other distro in the dust. This really is unnecessary pain for platform independent "text-only" stuff.

**Comment by akva2** [comment]
that was only meant as an example as such. i don't see how it wouldn't work with what you have now, assuming there's a prepare_tarball thingabom that can be reused across distros. but maybe that's the thing, it's integrated with the debian packaging ? if so i see your point..

**Comment by wsnipex** [comment]
yes, its integrated.

**Comment by Montellese** [comment]
Closing as there seem to be some standalone linux specific issues.

@wsnipex: I don't see why we shouldn't use the cmake addon build environment to handle other stuff than binary addons which aren't necessarily platform dependent.

**Pull request closed without merging**
