### PR TITLE
Fix for crash on startup on iOS

### PR DESCRIPTION
**Pull request by bavison**
This is to address the crash caused by PR #4143.

### CODE REVIEW

**Comment by Memphiz** [comment]
thx for the quick fix @bavison - verified - works fine again @MartijnKaijser once this is in -1 broken platform for alpha ;) jenkins build this please

**Comment by MartijnKaijser** [comment]
sorry, accidentally killed it with cancelling Helix branch
jenkins build this please

**Comment by Memphiz** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
hello jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
seems that the revision of this pr is somehow b0rked on the master node - cleared the workspace and here we go again jenkins build this please

**Comment by Memphiz** [comment]
grrrr no clue what the fuck is going on again - started a manual pr build here

http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-PR-Manually/66/

**Comment by Memphiz** [comment]
builds fine - thx

**Pull request merged**
