### PR TITLE
[json-rpc][pvr] Fix 'PVR.Record'.

### PR DESCRIPTION
**Pull request by ksooo**
Bug reported in the forum: https://forum.kodi.tv/showthread.php?tid=337964

I bumped the json-rpc micro version to make it possible to determine whether the bug fix is in place - the change is fully API compatible as the API itself is not affected.

Cause of the bug was a stupid and simple logical error.

### CODE REVIEW

**Comment by ksooo** [comment]
@DaveTBlake ping

**Comment by Rechi** [comment]
jenkins build this please

**Comment by ksooo** [comment]
I will merge this tomorrow if nobody objects. As you can see the fix is trivial.

**Comment by MartijnKaijser** [comment]
Ho ahead

**Review by DaveTBlake — COMMENTED** [review]
Thanks for this @ksooo (sorry for delay but have been off line a few days)

**Pull request merged**
