### PR TITLE
[fix] amlogic: 4k resolutions after f9d8ab7

### PR DESCRIPTION
**Pull request by stefansaraev**
#11986 accidentally broke 4k resolutions on amlogic/linux, and I failed to test that ;)

## Motivation and Context

```
ERROR: failed to create EGL window surface 12291
```
^ then screen is split into 2 (or 4) depending if video is playing or not, and an old frame of kodi GUI is drawn stretched

I dont understand most of the egl code, but it seems to me that GUI is not supposed to run at 4k

ref https://github.com/xbmc/xbmc/blob/master/xbmc/utils/AMLUtils.cpp#L497-L498 and below.

## How Has This Been Tested?

runtime tested on wetek play 2.

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

fyi @lrusak 

cc @wrxtasy @kszaq can you reproduce and confirm this fixes the bug for you ?

### CODE REVIEW

**Comment by lrusak** [comment]
Thanks!!!

**Comment by MartijnKaijser** [comment]
Jenkins build this please 
Ping @peak3d just in case

**Comment by stefansaraev** [comment]
jenkins does not build this code path :)

**Comment by peak3d** [comment]
from my side Ok if it works, I remember that this place was already a few times under change in the last decade.  I guess / hope that you have tested it good....

**Pull request merged**
