### PR TITLE
[infomanager] fix possible crash when accessing ListItem.UserRating

### PR DESCRIPTION
**Pull request by mkortstiege**
This fixes a crash when accessing `ListItem.UserRating`. Reported on the forums @ http://forum.kodi.tv/showthread.php?tid=245064&pid=2141772

/cc @Razzeee, @ronie

### CODE REVIEW

**Comment by ronie** [comment]
see my comments here: https://gist.github.com/mkortstiege/b6ee583b0aa8b30e9ef4#gistcomment-1603852

**Comment by mkortstiege** [comment]
@ronie should we include the music part in here as well or handle separately?

**Comment by ronie** [comment]
@Razzeee you're ok with this?

**Comment by Razzeee** [comment]
No, I'm not okay with you guys fixing bugs ;)
I think https://github.com/mkortstiege/xbmc/blob/fix-crash_userrating/xbmc/GUIInfoManager.cpp#L4397 might also need a safety net?

These also look dangerous, as they mix up the scraped ratings with the userratings :/
But that's not new, I think it was always like that, it only became more visible now.
https://github.com/mkortstiege/xbmc/blob/fix-crash_userrating/xbmc/GUIInfoManager.cpp#L5196
https://github.com/mkortstiege/xbmc/blob/fix-crash_userrating/xbmc/GUIInfoManager.cpp#L5822

**Comment by ace20022** [comment]
@Razzeee that one is protected by an if

**Comment by Razzeee** [comment]
Thanks, ace. Have missed that, everything else should be fine.

**Pull request merged**
