### PR TITLE
Remove redundant smart pointer get()

### PR DESCRIPTION
**Pull request by thebrid**
## Description
Apply clang-tidy check `readability-redundant-smartptr-get`.

## Motivation and Context
Slight code simplification.

## How Has This Been Tested?
Compiled & ran existing tests. Currently running a local build.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by garbear** [comment]
for the comparisons against `NULL`, we could go a step further and use `operator!`

**Comment by thebrid** [comment]
@ksooo updated

**Comment by ksooo** [comment]
jenkins build this please

**Review by ksooo — APPROVED** [review]
Thanks for your contribution.

**Pull request merged**
