### PR TITLE
added: File + path URL-decoded info labels (followup for #3960)

### PR DESCRIPTION
**Pull request by arnova**
This is the first part of the fix for cosmetic issues with unreadable filenames in e.g. the subtitle addon when used icw. URL-encoded filesystems. Obviously it will also require updating the addons to use the new info labels.

### CODE REVIEW

**Comment by arnova** [comment]
@mkortstiege / @MartijnKaijser : Please comment. Hopefully this can be in before we go beta (Note that it's not API-breaking, rather extending). Else it's fine for j*
@amet: Please comment + perhaps you could update the subtitle addon as soon as this has been merged?

jenkins build this please

**Comment by mkortstiege** [comment]
Hmm, not a big fan of special casing this all over the place. What about adding an option to the existing info labels (eg. ListItem.FolderPath(decoded)) instead of introducing others? To have it consistent this has to be applied to the container and player labels as well?

**Comment by arnova** [comment]
@mkortstiege : Good point, will look into it.

**Comment by arnova** [comment]
@mkortstiege: Never did much with info labels. Any pointers at where to look at on how to implement this?

**Comment by mkortstiege** [comment]
Just had a brief look at the listitem info labels and IMO it's not worth the hassle. Do we really have to return those labels URLdecoded? Is there a non-cosmetic reason that we have to deal with it? IMO the addons should handle this if it's just a display label.

**Comment by arnova** [comment]
@mkortstiege : The problem is in our skin. See: https://github.com/xbmc/xbmc/blob/master/addons/skin.confluence/720p/DialogSubtitles.xml#L73 so this can't be fixed in the addon. Any ideas on a (proper) fix for this?

**Comment by mkortstiege** [comment]
No idea, really.

**Comment by jmarshallnz** [comment]
Suggest fix is instead to include a Decode(foo) infolabel?

**Comment by arnova** [comment]
@jmarshallnz : Yeah, that was our idea. Btw. nice to see you (temporarely?) back :-)

**Comment by Rechi** [comment]
@arnova this needs a rebase

**Comment by MartijnKaijser** [comment]
I will close this PR. If there's interest please open a new one (with required changes if needed).

**Pull request closed without merging**
