### PR TITLE
Clean up unused dirty region methods

### PR DESCRIPTION
**Pull request by lrusak**
dirty region methods are unused (and broken for the most part) and should be removed.

Options 0 and 3 are all we need. I would even advocate for removing dirty regions entirely, but this is just a step.

Tested on RPi and methods 1 and 2 make the gui very sluggish. Perhaps it is more of a cpu bottleneck then a gpu one.

On GBM they don't work at all because the egl config using `EGL_SWAP_BEHAVIOR_PRESERVED_BIT` cannot be found. This code was added specifically for the rpi in https://github.com/xbmc/xbmc/commit/5c89074b7bdce305c2ff4a0d2d83b02c51393d3f

### CODE REVIEW

**Comment by MrMC** [comment]
Removing dirty regions entirely would be a big step backwards to the 'why is xxxx consuming large amounts of cpu when nothing is changing" mess.

**Comment by FernetMenta** [comment]
DR can be dropped entirely in favour of https://github.com/xbmc/xbmc/pull/12213

**Comment by FernetMenta** [comment]
@peak3d I don't think we need dr and smart-redraw. You have been running smart-redraw for quite some while, right? Is it good to become default?

**Comment by peak3d** [comment]
@FernetMenta there are a few places left, will do over the weekend

**Comment by popcornmix** [comment]
I did try measuring the fps achieved (shown by debug overlay) of the different methods on a Pi3+.
I was using the TV view of Estuary focused on an episode with a long title that scrolls (so screen is always dirty). Display was 50Hz, so that would be the theoretical highest number.
The first number is algorithmdirtyregions value.
```
0 29 fps (remains high when scrolling stops)
1 38 fps (drops to ~10 when scrolling stops)
2 35 fps (drops to ~10 when scrolling stops)
3 29 fps (drops to ~10 when scrolling stops)
```
It seems there is a benefit with modes 1 and 2 (and obviously a cpu saving when scrolling stops for 1, 2 and 3). It would be interesting to see what @peak3d's smart scheme does with a similar test.

On a quick test I couldn't see any artefacts with modes 1 and 2 (I believe they occurred on alpha'd region around menu bar in confluence but I don't think estuary uses alpha in the same way).

**Comment by MartijnKaijser** [comment]
Any update if can drop it?

**Pull request closed without merging**
