### PR TITLE
[pvr] Bump pvr.hts to version 2.1.8

### PR DESCRIPTION
**Pull request by ksooo**
@Jalle19 @xhaggi @opdenkamp okay?

### CODE REVIEW

**Comment by ksooo** [comment]
jenkins build addons please

**Comment by ksooo** [comment]
CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "Findplatform.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "platform",
  but CMake did not find one.

  Could not find a package configuration file provided by "platform" with any
  of the following names:

    platformConfig.cmake
    platform-config.cmake

  Add the installation prefix of "platform" to CMAKE_PREFIX_PATH or set
  "platform_DIR" to a directory containing one of the above files.  If
  "platform" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/Users/Shared/jenkins/workspace/BINARY-ADDONS/platform_label/osx64/tools/depends/target/binary-addons/macosx10.10_x86_64-target/pvr.hts-prefix/src/pvr.hts-build/CMakeFiles/CMakeOutput.log".

@opdenkamp related to https://github.com/kodi-pvr/pvr.hts/pull/24 ! Any idea what's going wrong?

**Comment by opdenkamp** [comment]
install the platform lib from the build deps ppa
https://launchpad.net/~team-xbmc/+archive/ubuntu/xbmc-ppa-build-depends

**Comment by Jalle19** [comment]
This is on OS X?

**Comment by ksooo** [comment]
@opdenkamp this is an error generated by jenkins.kodi.tv! ???

**Comment by ksooo** [comment]
Yes, OSX (64).

**Comment by opdenkamp** [comment]
it was built as part of kodi correctly when jenkins built the PR. 
@Memphiz does jenkins have to be configured to "remember" the lib and 
not throw it away after building something?

**Comment by ksooo** [comment]
As far as I can see build failed on all platforms (checked OSX64, Linux64, Win32). :-(

**Comment by opdenkamp** [comment]
guess jenkins will have to be set up to build the lib when building 
add-ons only

**Comment by Montellese** [comment]
I don't see how this should work when `kodi-platform` still points to https://github.com/xbmc/kodi-platform/commit/48bdd985b843353eec5804e4dbab2dc8f2b4b13e which doesn't use `libplatform` yet and the cmake buildsystem doesn't have any integration for `libplatform` at all right now.

We do not depend on any ppa, system libs, our depends or prebuilt binaries in the cmake buildsystem (except for linux standalone).

**Comment by opdenkamp** [comment]
see the comment on the other PR

**Comment by ksooo** [comment]
Superseeded by #7069

**Pull request closed without merging**
