### PR TITLE
fixed: broken rfft implementation used in audio visualizer api

### PR DESCRIPTION
**Pull request by fritsch**
this replaces it with a working version using kissfft

This is a follow up of:  https://github.com/xbmc/xbmc/pull/7039

### CODE REVIEW

**Comment by fritsch** [comment]
I would be thankful for PR of the relevant project updates we need.

**Comment by FernetMenta** [comment]
how about moving this to depends as @wsnipex volunteered to do this?

**Comment by fritsch** [comment]
All in favor for doing it, if it makes things cleaner. PR. Thanks in advance @wsnipex

**Comment by Paxxi** [comment]
if we move to depends we'll have to redo the VS parts but it's simple enough so I can take care of that part

**Comment by Memphiz** [comment]
yes thx in advance to whoever moves it to depends :)

**Comment by wsnipex** [comment]
had a quick look at it and now I'm doubting the benefit of moving to depends. The lib is ~4 files, but the changes needed to move it to depends will be roughly the same :)
1. the Makefile is useless for anything but linux and even there it needs changes for cross compiling, so we have to redo the whole buildsys
2. needs ubuntu(and probably lots of other distros) packaging

**Comment by FernetMenta** [comment]
maybe we should go for fftw then. this is available on the various Linux distros, and also available as pre-built for Windows.

**Comment by wsnipex** [comment]
I think we should just merge it as is. Its not very likely that this lib will change.

**Comment by FernetMenta** [comment]
no need to rush. we are going to use fftw anyway in addons. there have to be a really good reason for going with kiss and breaking the strategy of getting rid of libs folder.

**Comment by fritsch** [comment]
One point for kiss is: I understand the code and the algorithm it
implements, as everybody else that did fourier analysis. Furthermore it
fixes real issues we have with most of viz addons that need frequency data.
Nobody knows about side effects fftw produces on non Linux systems ...

2015-05-03 11:21 GMT+02:00 Rainer Hochecker <notifications@github.com>:

> no need to rush. we are going to use fftw anyway in addons. there have to
> be a really good reason for going with kiss and breaking the strategy of
> getting rid of libs folder.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/xbmc/pull/7047#issuecomment-98460095>.
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by FernetMenta** [comment]
we could also add the sources of kiss to some "contrib" folder within the xbmc project files.

**Comment by Paxxi** [comment]
@FernetMenta isn't that what the lib folder basically is?

**Comment by FernetMenta** [comment]
Nope, why crating a lib here? Those two files could be added to the project without compiling a lib and link it statically to the app. Adding an additional VS project is really bad for those 2 files.

**Comment by Paxxi** [comment]
They could be added into main project. i chose this method to maintain a clean separation between our code and 3rd party. The project is statically linked so end result is the same.

**Comment by AchimTuran** [comment]
> Nobody knows about side effects fftw produces on non Linux systems ...
On windows all works very well :)
But I'm not familiar with OSX or Android.

I will use fftw in my GSoC proposal for my xconvolver addon. So we will see how good it works.

**Comment by fritsch** [comment]
http://www.fftw.org/install/windows.html <- First two sentences.

**Comment by Memphiz** [comment]
agree with @FernetMenta - we should add some sort of 3rdparty folder and can add those source files directly to the xcode and vs project files (and the makefiles of course). No need to tinker with libraries in that case.

**Comment by wsnipex** [comment]
+1 on moving it to contrib and directly using the files.

**Comment by AchimTuran** [comment]
> http://www.fftw.org/install/windows.html <- First two sentences.

That's true, but I think they don't wanna support Windows :)


kiss FFT Readme ;)
> DO NOT:
>    ... use Kiss if you need the Fastest Fourier Transform in the World

There is also some support for SIMD in kiss FFT.

As conclusion we need both :)
Today I started to code the benchmark. Next days I will share my results.

**Comment by Memphiz** [comment]
@fritsch mind if i replace this PR with this one here:

https://github.com/Memphiz/xbmc/commits/kiss_rfft

(which basically split the commits properly and moved the source to xbmc/contrib/kissfft)

Also @notspiff how can i test this - i tried all viz i have (windows and osx) but not a single one wants freqdata (so fft isn't called for any of them).

**Comment by notspiff** [comment]
Use nastyfft from my gits.

**Comment by fritsch** [comment]
@memphiz you are welcome. THX much.
Am 10.05.2015 6:14 nachm. schrieb "Arne Morten Kvarving" <
notifications@github.com>:

**Pull request closed without merging**
