### PR TITLE
[TouchScreen] - Fixed touch screen support in WindowScreenCalibration

### PR DESCRIPTION
**Pull request by Memphiz**
As pointed out by users and @NedScott the WindowScreenCalibration was not compatible with touchscreen/gestures yet. Its important for beeing able to set the subtitle position (not so much the rest of the calibration).

This PR makes the window touchscreen aware and adds a default touchscreen mapping for it (swipe up, left, right, down for changing the positions and single finger tap for switching between the calibration modes).

All messages and actions which are altered here are touchscreen specific so i consider this PR safe for Isengard.

Runtime tested on iOS and android tablets...

### CODE REVIEW

**Comment by Memphiz** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
@koying as you are dealing with touchscreens i think you would be the best for beta phase +1 this :)

**Comment by Memphiz** [comment]
@koying - slight reping

**Comment by koying** [comment]
It's on my todo for this WE. 
My N7 died so I only have a Samsung x86 tablet left, for which I have to redo a full build ;)

**Comment by NedScott** [comment]
Does this just need testing on an Android touch screen device? If so, I'll make a test build and ask our users on the forum to try it.

**Comment by Memphiz** [comment]
mhhh i tested it on android arm - i basically only need some main dev to +1 it ... (be it with or without testing)

**Comment by mkortstiege** [comment]
No-brainer as it only affects the calibration window. +1 (without testing). Kind nudge @koying.

**Comment by koying** [comment]
+1.
Not obvious that you have to swipe to increment, though. The "intuitive" way is to try to drag the corners ;)

**Comment by Memphiz** [comment]
yep you are right - but its not worth digging into that for now.

**Comment by Memphiz** [comment]
btw dragging the corners is not possible when you moved them out of screen ;)

**Comment by koying** [comment]
Sure. Might just be worth having a note somewhere for the few users which will use this :)

**Pull request merged**
