### PR TITLE
Music library differential sync and better recentlly added handling

### PR DESCRIPTION
**Pull request by DaveTBlake**
New differential synchronisation facility  for JSON consumers, so that remote apps like Kore and Yatse can request only records changed or added since a given datetime rather than have to request the entire database when only minor things have changed e.g. the playcount of songs or the scraped details for an artist.

Fix the implementation of recently added songs, and those albums and artists with recently added songs. 

Bump database to MyMusic78.db and JSON minor version for non-breaking additions to API.

---
### JSON API Additions
Add **"datenew"** and **"datemodified"** as filter rule fields to `AudioLibrary.GetSongs`,  `GetAlbums` and `GetArtists` methods. These are implemented as new smart playlist rules so not explicitly listed in schema (and so an easily overlooked but useful change).

Add properties to `AudioLibrary.GetProperties`
- Last destructive change (deletions, drop source, cleaning) **"librarylastcleaned"**, 
- Last datetime artist relationships changed (maybe nothing added, but link data has changed) **"artistlinksupdated"**, 
- Last datetime new records added - **"songslastadded"**, **"albumslastadded"**, **"artistslastadded"**, **"genreslastadded"** 
- Last datetime records changed - **"songsmodified"**, **"albumsmodified"**, **"artistsmodified"**

[Note  **"librarylastupdated"** is an existing property giving the last time a library update was perfromed]
All record audit datetimes are UTC values, unlike the older and user displayed values  "dateadded" and "lastplayed" which are local time

#### Differential Sync
Improve the music library update processing to preserve ID use consistently across rescans of music files, and store using database triggers when records are first added ("dateNew") or modified ("dateModified")  to be able to identify records that have changed.

Note the existing field "dateadded" is a optionally a media file date, hence unsuitable for tracking library change history. It's primarily purpose is to indicate songs being "recent" using the users choice of file or scan times to do so.

Keeping song IDs on rescan when filename is same (although embedded metadata may have changed)  allows the original "dateNew" when ID created to be preserved. Library updates are only "destructive",  when changing the relationships of songs and albums to artists, or deleting records, hence store when such a change last happened. JSON consumers can use these fixed IDs to match up results with the data previously returned.

Rework `UpdateArtistSortNames()` to avoid updating songs and albums unnecessarily when processing artist sort names. Ensure that when sort name matches artist name it is added to song and album records as null rather than tidy up later.

#### Recently Added Songs, Albums and Artists
Address some user niggles,  see forum https://forum.kodi.tv/showthread.php?tid=336838 https://forum.kodi.tv/showthread.php?tid=339342 and https://forum.kodi.tv/showthread.php?tid=352091, and extend the options for recently added songs, and those albums and artists with recently added songs. 
- Base recently added albums upon "dateadded" (derived from "dateadded" of songs)  rather than album ID, to always show those albums with the most recently added songs
- Add option for "dateadded" for song to be from the minimum of music file ctime and mtime (in addition to mtime, max of ctime or mtime or time scanned into library). On Windows this is the creation time of the file, on Linux it is the last time that the file  permissions etc. were changed.
- Store "dateadded" as a denormalised field of artist and album tables (not subquery in views that is very slow in MySQL), the indicator of albums or artists with the most recently added songs. Allow for artists that are only album artists (but not song artists - as can happen in classical music) when calculating that artist has recently had songs added.

### CODE REVIEW

**Comment by DaveTBlake** [comment]
@Tolriq perhaps you will find this an interesting feature addition and maybe try it out. Comments welcome. Win64 test build here http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20200609-1654206a-PR18026-merge-x64.exe

**Review by the-black-eagle — COMMENTED** [review]
LGTM.  Been testing for a few days with no issues found.

**Comment by Tolriq** [comment]
JSON changes are now fine and from quick tests does what it should.
Did not do extended tests of all the cases, but implementation details can be updated later if public API does not change.

**Comment by DaveTBlake** [comment]
Thanks for testing this out @Tolriq and @the-black-eagle, best way ahead is to merge it into the nightly which I will do tomorrow unless anyone has more comments to make

**Comment by howie-f** [comment]
@DaveTBlake 
database bump failing on my machine from 77 to 78
same happens when trying to bump from 76 -> 78
(Server version: 10.1.44-MariaDB-0+deb9u1 Debian 9.11)
SQLite not tested.

Kodi crashes on entering music-section from main menu after bumping.

Excerpt from the log after the first start with this pr applied:

```
2020-06-20 11:44:24.186 T:1780     INFO <general>: MYSQL: Connected to version 10.1.44-MariaDB-0+deb9u1
2020-06-20 11:44:24.187 T:1780    ERROR <general>: Unable to open database: MyMusic78 [1049](Unknown database 'MyMusic78')
2020-06-20 11:44:24.187 T:1780     INFO <general>: Old database found - updating from version 77 to 78
2020-06-20 11:44:35.314 T:1780     INFO <general>: Attempting to update the database MyMusic78 from version 77 to 78
2020-06-20 11:45:06.451 T:1780     INFO <general>: UpdateTables - updating tables
2020-06-20 11:45:14.455 T:1780     INFO <general>: CreateAnalytics - creating indices
2020-06-20 11:45:27.117 T:1780     INFO <general>: create triggers
2020-06-20 11:45:28.034 T:1780    ERROR <general>: SQL: [MyMusic78] Undefined MySQL error: Code (1064)
                                                   Query: CREATE TRIGGER tgrInsertGenre AFTER INSERT ON genre BEGIN UPDATE versiontagscan SET genresupdated = now(); END

2020-06-20 11:45:28.034 T:1780    ERROR <general>: Exception updating database MyMusic78 from version 77 to 78
2020-06-20 11:45:28.034 T:1780    ERROR <general>: Error updating database MyMusic78 from version 77 to 78
2020-06-20 11:45:28.035 T:1780     INFO <general>: Old database found - updating from version 76 to 78
2020-06-20 11:45:28.035 T:1780    ERROR <general>: SQL: Can't create database for copy: 'MyMusic76' (1007)
2020-06-20 11:45:28.035 T:1780    ERROR <general>: Unable to copy old database MyMusic76 to new version MyMusic78
2020-06-20 11:45:28.036 T:1780     INFO <general>: Running database version MyVideos117
2020-06-20 11:45:28.036 T:1780     INFO <general>: Running database version TV36
2020-06-20 11:45:28.036 T:1780     INFO <general>: Running database version Epg13
```

**Comment by DaveTBlake** [comment]
Thanks @howie-f that is MariaDB not liking the trigger syntax, no music db migration to v78 will work on MariaDB/MySQL (SQLite is fine).  I'm on fixing it ASAP.

**Pull request merged**
