### PR TITLE
[language] Let's call it what it is: English (United Kingdom)

### PR DESCRIPTION
**Pull request by MartijnKaijser**
@Montellese you know of any downsides this might have?

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@Montellese this indeed causes issues for add-on that have not yet moved to the new language folder layout where we use the language codes as folder names.
Is there any fallback we can add for that?

**Comment by Montellese** [comment]
@MartijnKaijser I don't follow. Is there a problem with the current status quo or with this PR?

**Comment by MartijnKaijser** [comment]
@Montellese With this PR. 
Addons that still use "English" as language folder name won't get get the language file loaded anymore

**Comment by Montellese** [comment]
TBH I already disliked having to add the existing fallback so not a fan of adding another fallback.

**Pull request closed without merging**
