### PR TITLE
[VideoInfoScanner] Prevent logging errors by getting empty directory

### PR DESCRIPTION
**Pull request by larrignon**
## Description
Prevent logging errors by getting empty directory with scraper.

## Motivation and context
Got error message in UI with scraper but nothing to explain this error.
Just found "ERROR <general>: XFILE::CDirectory::GetDirectory - Error getting " in log without the specific directory.
That error is just because of empty directory in function parameter.

## How has this been tested?
Runtime tested with The TVDB v4 addon scraping in French some TV series test folder on my NAS.

## Types of change
- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by larrignon** [comment]
@jenkins4kodi could you help me to add label and milestone to my PR ?
I have no option in website and command line return a not correct permissions message.
My PR is for v20 Nexus.

**Comment by basilgello** [comment]
@larrignon jenkins4kodi is a bot! Milestones and labels can be set by full team members. That's just FYI - everything is assigned. What is needed from you is to apply the proposed diff and `git commit --amend` the patch (optionally with `-S` if you sign your work with GPG keys)

**Comment by CastagnaIT** [comment]
please also set a more readable commit title, something like:
`[VideoInfoScanner] Prevent logging errors by getting empty directory`

**Comment by fuzzard** [comment]
Can you do a rebase and drop the merge commit. Thanks

**Comment by larrignon** [comment]
@fuzzard I did a rebase. Should I do anything else?

**Comment by fuzzard** [comment]
yeah, sorry. will need to do again. Make sure to drop all other commits except your commit de1460a1d7d7950d0ac520fefbfcafdc019122c0

If origin is your github repo, and upstream is the xbmc repo

git fetch upstream
git rebase -i upstream/master
remove any commit that isnt de1460a
git push origin -f

upstream is whatever name you use for the xbmc remote when you added it. origin is presumably your repo

**Comment by fuzzard** [comment]
Thanks for the PR

**Pull request merged**
