### PR TITLE
[add-ons/settings] add python setting getters/setters for bool/int/number/string

### PR DESCRIPTION
**Pull request by Montellese**
This is a follow-up of #12125 which adds typed getters and setters for bool/int/number/string settings. The difference to the existing getter/setter is that when a plugin e.g. tries to retrieve an integer setting using `getSettingString()` it will fail because the types don't match.

## How Has This Been Tested?
I've adjusted @ronie's `service.scrobbler.lastfm` to use the new methods and it still worked.

## Types of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Review by phil65 — APPROVED** [review]

**Comment by romanvm** [comment]
Looks nice. Just one question though: how is attempt to get/set an invalid type handled? The Pythonic way is to throw `TypeError` exception on an invalid type or call `PyErr_SetString(PyExc_TypeError, "<some exception message here>")` on C level.

**Comment by MartijnKaijser** [comment]
Thinking about this why would we need to specify the type when doing get? Understandable you need to set the correct type when writing a setting but for retrieving we already know what was store correct?

**Comment by romanvm** [comment]
@MartijnKaijser Foolpoofing against accidental getter/setter mismatch?

**Comment by Montellese** [comment]
@romanvm: Right now it returns a default value but I could change it to throw an error/exception (just need to check how). Is this preferred?

@MartijnKaijser AFAIK our C++ Python API doesn't allow us to return any type so we'd have to go back to returning a string and then the add-on script has to parse the actual type and value from a string which IMO doesn't make any sense.

**Comment by romanvm** [comment]
@Montellese Yes, an exception would be better.  "Explicit is better than implicit". Of course, if it's not too difficult. Kodi's Python <-> C interoperability layer is a complete mystery to me.

**Comment by Montellese** [comment]
@romanvm It actually wasn't that hard. The necessary exception and translation to `PyExc_TypeError` was already in place. Now all the new getters and setters throw a `TypeError` if a script tries to access a setting of a wrong type.

**Pull request merged**
