### PR TITLE
Update playercorefactory.xml

### PR DESCRIPTION
**Pull request by onetechgenius**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Get lost with your  crap

**Comment by hudokkow** [comment]
Sorry to spam everyone but WTF?? How retarded is this? The "genius" is adding credits to our files and pointing them to xbmcandroid.com/forums which, surprise, surprise, points to tvaddons.ag...

**Comment by FernetMenta** [comment]
if he/she does it again I will contact github and ask for banning.

**Comment by MartijnKaijser** [comment]
already done

**Pull request closed without merging**
