### PR TITLE
[xbmc]Fix format specifiers, size_t is 32-bit on 32-bit windows

### PR DESCRIPTION
**Pull request by Paxxi**
using PRIuS or PRIdS when passing in a uint32_t will cause fmtlib to throw as it's type safe, don't do this.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
tested by ace and fixes the crashes he saw

**Comment by Paxxi** [comment]
Jenkins build and merge this please

**Comment by Rechi** [comment]
@Paxxi `CLog::Log` doesn't support fmtlibs format syntax.

This causes loglines like `ERROR: CProfilesManager: current profile index ({0}) is outside of the valid range ({1})` (https://trac.kodi.tv/ticket/17565)

**Comment by Paxxi** [comment]
yep. Remember that now. Interesting that it's taken this long for the issue to pop up

**Pull request merged**
