### PR TITLE
[cmake] add clang-tidy, cppcheck & iwyu co compile support

### PR DESCRIPTION
**Pull request by Rechi**
## Description
runs clang-tidy, cppcheck and include-what-you-use support, if explicitly enabled, along with the compiler

## Motivation and Context
get the reports of these tools while compiling

## How Has This Been Tested?
compiled with and without enabled clang-tidy, cppcheck and include-what-you-use support support

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
soooo what about #17820 ?

**Review by wsnipex — COMMENTED** [review]
looks good to me. It looks cleaner then https://github.com/xbmc/xbmc/pull/17820 maybe you can add the additional targets so lrusak's use case is covered?

**Comment by Rechi** [comment]
You can add #17820 if you still need it for CI.
This is for working on specific files. In that case you don't want to run the checks on the whole code base, but only on the changed files while compiling them.

**Comment by lrusak** [comment]
aha, still no communication and you decide to just shove this through without any consideration for others, how typical.

Overall I'm fine with this approach, however, it would have been nice to have a discussion about it vs #17820

**Comment by Rechi** [comment]
I explained the difference above. Why would you want to run the checks on the whole code base if you only edited a specific file?

**Comment by lrusak** [comment]
> I explained the difference above. Why would you want to run the checks on the whole code base if you only edited a specific file?

The whole point was for it to be run by CI to generate reports

**Comment by Rechi** [comment]
That's the use case of your PR, not for this one.
As code generating such reports shouldn't get merged, developers have to see them during compiling on their local system.

**Comment by lrusak** [comment]
> That's the use case of your PR, not for this one.
> As code generating such reports shouldn't get merged, developers have to see them during compiling on their local system.

so you're fine if I merge #17820 then?

**Comment by Rechi** [comment]
If you rebase it and use the the same variables for the `find_program` calls, sure. Also the checks shouldn't be run for the `lib/libUPnP` directory.

**Pull request merged**
