### PR TITLE
[dependencies] remove remaining references to libmodplug

### PR DESCRIPTION
**Pull request by candrews**
libmodplug was removed in https://github.com/xbmc/xbmc/pull/9995 but a few lingering references remained - so this pull request removes them.

## Description
Just removing the remaining documentation and script references to libmodplug.

## Motivation and Context
It's always nice to have accurate documentation and not have dependencies expressed on libraries that aren't used.

## How Has This Been Tested?
This is a pretty simple change...

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [X] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

libmodplug was removed in https://github.com/xbmc/xbmc/pull/9995 so remove remaining references

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@wsnipex ping.

**Comment by wsnipex** [comment]
thanks
jenkins build this please

**Comment by MartijnKaijser** [comment]
@candrews can you also make PR against Krypton branch? Same for the other PRs

**Comment by candrews** [comment]
@MartijnKaijser sure! So going forward, should I make PRs against both krypton and master, or just krypton?

**Comment by MartijnKaijser** [comment]
Only master and if we request only then krypton.

**Comment by candrews** [comment]
For this PR, the Krypton PR is https://github.com/xbmc/xbmc/pull/11131

**Pull request merged**
