### PR TITLE
[input] fix long press fallback handling after #7846

### PR DESCRIPTION
**Pull request by xhaggi**
@stefansaraev mind taking a look + could you test it please.

### CODE REVIEW

**Comment by xhaggi** [comment]
use `?w=1` for review .. https://github.com/xbmc/xbmc/pull/7948/files?w=1

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by stefansaraev** [comment]
back to normal. thanks @xhaggi :)

**Comment by xhaggi** [comment]
I've to say thank you .. my mistake, because i didn't double-check it.

**Pull request merged**
