### PR TITLE
AudioTrack: More generalization from the other end

### PR DESCRIPTION
**Pull request by fritsch**
The new FireTV Cube reacts from a min_buffer time of view completely different to other devices, in the sense of that it returns actually "usable" values as min_buffer time. For DTS-HD-MA and TrueHD it already reports 128 ms minimal. Our concept did not assume this.

Therefore:
- Rework the buffer time search by extending it to start from min_buffer already and not blindly doubleing the value
- Move some logs from DEBUG to INFO as they are important to know and amazon changed the default log level so that DEBUG is not visible anymore. Our logging framework "blindly" uses this setting from Android

### CODE REVIEW

**Comment by fritsch** [comment]
Forum Thread: https://forum.kodi.tv/showthread.php?tid=371883

**Comment by fritsch** [comment]
First one: Helps me debugging FireTV devices, cause of their logging policy
Second: Was wrong in code - we did not assume a device might by itself already ask for 128 ms Buffer
Third: This fixes a firmware bug on the Cube, but we had no such watchdog there at all. Effect: Sink get's stuck for up to 4 seconds, eats the audio data, but does not move. Then slowly starts moving, while audio is up to 4 seconds off.

**Comment by thexai** [comment]
This PR changes all game rules on Shield:

info <general>: Trying to open: samplerate: 192000, channelMask: 6396, encoding: 13
info <general>: Minimum size we need for stream: 98432 Bytes
info <general>: Audiotrack buffer params are: period time = **51.266** ms, period size = 157490 bytes, num periods = **2**
info <general>: Created Audiotrackbuffer with playing time of 128.166667 ms min buffer size: 393728 bytes

Before was 32 ms periods and 4 periods

Honestly, I don't think it's time to change this and if it is changed it should be thoroughly tested and there will be no possibility of backport to Nexus

**Comment by fritsch** [comment]
Good spotting. There is something wrong in the code. It should end up with 128/32 as before.  Could you post the entire log?

**Comment by thexai** [comment]
https://paste.kodi.tv/wicogitupi.kodi

**Comment by fritsch** [comment]
Thanks much! I had a logic error here, which was not hit on my FireTV Cube device. Should now match again exactly what we had before.

**Comment by thexai** [comment]
I'm out of time now. I will test it tonight.

**Comment by thexai** [comment]
Now all seems right on Shield:

```
2023-02-15 23:21:44.125 T:15417    info <general>: CActiveAESink::OpenSink - initialize sink
2023-02-15 23:21:44.132 T:15417    info <general>: Trying to open: samplerate: 192000, channelMask: 6396, encoding: 13
2023-02-15 23:21:44.133 T:15417    info <general>: Minimum size we need for stream: 98432 Bytes
2023-02-15 23:21:44.133 T:15417    info <general>: Audiotrack buffer params are: period time = 32.042 ms, period size = 98432 bytes, num periods = 4
2023-02-15 23:21:44.133 T:15417    info <general>: Created Audiotrackbuffer with playing time of 128.166667 ms min buffer size: 393728 bytes
```

no issues found

**Review by thexai — APPROVED** [review]

**Comment by fritsch** [comment]
jenkins build this please

**Pull request merged**
