### PR TITLE
[dvdplayer][subs] Add "none" to the preferred language list. It will …

### PR DESCRIPTION
**Pull request by ace20022**
…disable any kind of available subtitles.

### CODE REVIEW

**Comment by mkortstiege** [comment]
Looks good to me. Only downside is that this will also skip forced subs and disable em altogether. Anyway, +1.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by ace20022** [comment]
I could change that and the option to "only forced".

**Comment by mkortstiege** [comment]
> I could change that and the option to "only forced".

Both would be nice, so the user can choose between prefered langauge, force only and none.

**Comment by MartijnKaijser** [comment]
Was thinking about that same suggestion. If it's possible.

**Comment by ace20022** [comment]
"forced only" added, **untested** and the label is missing. Can someone add it to the po file?

**Comment by MartijnKaijser** [comment]
send you a PR for the string

**Comment by ace20022** [comment]
thx, will squash if you don't mind

**Comment by MartijnKaijser** [comment]
go ahead

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Comment by MartijnKaijser** [comment]
@ace20022 i just noticed that audio stream language now also has the "none" and "forced only" options added. I doubt those make sense?

**Comment by MartijnKaijser** [comment]
"close caption" also shows in both lists and is listed between the other languages and not on top.

Loving the "none' option btw ;)

**Comment by ace20022** [comment]
@MartijnKaijser Hmm, will have a look soon.

**Comment by ace20022** [comment]
> audio stream language now also has the "none" and "forced only" options added.

The download subs for language also has these entries...
> "close caption"

That's because cc was added to the iso list https://github.com/xbmc/xbmc/blob/master/xbmc/utils/LangCodeExpander.cpp#L520 also it's not an official code. I tend to remove it, but I'm not sure that it's not used.

I'm afraid we need to split the options filler methods.

**Pull request merged**
