### PR TITLE
[GLES] VideoShader cleanup

### PR DESCRIPTION
**Pull request by lrusak**
This cleans up and removes unused code for the GLES rendering path.

Currently stretch, 3dlut, and limited color range aren't used by GLES, let's clean it up for now.

Commit's are just broke up logically to allow for easier review.

build and run tested on linux using GBM

### CODE REVIEW

**Comment by lrusak** [comment]
tested on android also and it seems ok http://mirrors.kodi.tv/test-builds/android/arm/kodi-20180122-82b297c5-gles-cleanup-armeabi-v7a.apk

**Comment by lrusak** [comment]
Can I get various platform maintainers to test this? @popcornmix @peak3d 
@MilhouseVH for inclusion in an RPi build (disabling hw accelleration will allow this code path)

**Comment by lrusak** [comment]
I'm going to say that this is good to go :smile_cat:

**Review by FernetMenta — APPROVED** [review]

**Comment by MilhouseVH** [comment]
Problems being reported by RPi users with LiveTV playback since this was included:

https://forum.kodi.tv/showthread.php?tid=298461&pid=2697224#pid2697224
https://forum.kodi.tv/showthread.php?tid=298461&pid=2697525#pid2697525
https://forum.kodi.tv/showthread.php?tid=298461&pid=2697568#pid2697568
https://forum.kodi.tv/showthread.php?tid=298461&pid=2697591#pid2697591

**Pull request merged**
