### PR TITLE
[cmake] C++14

### PR DESCRIPTION
**Pull request by fetzerch**
I've started to check the necessary bits for C++14 support.
Minimum compiler version for GCC is 4.9 (which we now have also on Android).
The code also simplifies setting the standard a bit so that in the end it's enough to modify CMAKE_CXX_STANDARD in one place.
There's no need to enable >C++11 for depends, as long as no library really needs this.

## Description
Enable C++14 support. https://isocpp.org/wiki/faq/cpp14-language

## Motivation and Context
2016 is almost over ;)

## How Has This Been Tested?
Compiles locally, I've added one temporary commit to check if generic lambdas, make_unique, and regex (not c++14 material, but unsupported on older compilers) compile.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fetzerch** [comment]
Jenkins build: http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-All/1730/

@wsnipex: This would require to bump gcc on rbpi to 4.9.

**Comment by Paxxi** [comment]
Thank you! Been looking forward to make_unique for a while 😀

**Comment by hudokkow** [comment]
We can upgrade travis gcc. Should be a two liner.

**Comment by Rechi** [comment]
@fetzerch this needs a rebase

**Comment by fetzerch** [comment]
Closing in favor of https://github.com/xbmc/xbmc/pull/13034.

**Pull request closed without merging**
