### PR TITLE
goom: drop unneeded file which bothers git

### PR DESCRIPTION
**Pull request by FernetMenta**
see title
I have seen this change on other PRs too. something seems to change this comment.

### CODE REVIEW

**Comment by wsnipex** [comment]
yeah, thats a really old one, time to fix it. You commit msg has a typo: should be "recognized"

**Comment by notspiff** [comment]
File should be deleted from git, not be changed to correspond to what current autotools happen to generate.

**Comment by wsnipex** [comment]
are you sure that it will be auto generated on all platforms?

**Comment by notspiff** [comment]
Yes that is output from autoreconf. It is gone in the addon for instance.

**Comment by FernetMenta** [comment]
file dropped
jenkins build this please

**Pull request merged**
