### PR TITLE
[gui] reduce code duplication for mass dialog close

### PR DESCRIPTION
**Pull request by xhaggi**
~~This adds a new method `CloseWindows(std::vector<int> windowIds, bool forceClose)` to the window manager which is used on different places where we mass close dialogs. It reduce the code duplication a lot.~~

This excludes the addon/python dialogs in `CloseModalDialogs()` and use this method where we want to close all active modals e.g. if we leave fullscreen, visualation, video/music osd.

@mkortstiege @Montellese ping

### CODE REVIEW

**Comment by xhaggi** [comment]
forgot to say that it also close the bookmark dialog in case we leave the fullscreen video window which was missing before.

**Comment by xhaggi** [comment]
Instead of closing a fixed list of window ids another more dynamic solution could be the use of `CloseModalDialogs()`. If we won't see any issue in closing every modal dialog in the case we leave the video/music osd and the fullscreen/visualisation window we should prefer this IMO.

**Comment by phil65** [comment]
While at it, perhaps you could also check why Dialog.Close(all) crashes kodi when dialogs are open? (when adding ,true parameter to suppress WindowClose animation it does not crash) Thx! :)

**Comment by xhaggi** [comment]
@phil65 you mean the Built-In right?

**Comment by phil65** [comment]
correct. :)

**Comment by phil65** [comment]
just open ShutdownMenu for example and trigger that builtin. crashes here on latest nightly.

**Comment by xhaggi** [comment]
@phil65 results in an endless loop in https://github.com/xbmc/xbmc/blob/master/xbmc/guilib/GUIWindowManager.cpp#L809 will push a fix.

**Comment by phil65** [comment]
great. thx @xhaggi !

**Comment by xhaggi** [comment]
@ruuk do you see any issue if we force close all modals instead of this static list?

**Comment by ruuk** [comment]
If that is the same method used in that other pull request, it closes all Python windows whether they are opened with doModal() or show(), and in any case it is difficult to implement Python windows using show() for various reasons. It seems like it would be better if we had a method that distinguished between builtin windows and Python windows. Perhaps a check if the window ID is within the relevant range?

**Comment by xhaggi** [comment]
@ruuk as you suggested i've added a check to `CloseModalDialogs()` which now excludes the addon/python dialogs and only close our "internal" known dialogs.

**Comment by xhaggi** [comment]
~~This adds a new method `CloseWindows(std::vector<int> windowIds, bool forceClose)` to the window manager which is used on different places where we mass close dialogs. It reduce the code duplication a lot.~~

This excludes the addon/python dialogs in `CloseModalDialogs()` and use this method where we want to close the active modals e.g. if we leave fullscreen, visualation, video/music osd.

**Comment by xhaggi** [comment]
@mkortstiege what do you think about rename the `CloseModalDialogs` method to `CloseInternalModalDialogs` to make it clear that this only close our internal modal dialogs?

**Comment by mkortstiege** [comment]
No objections to rename. Btw, what about orphaned python/addon dialogs? Is it possible to end up with opened dialogs in case something went utterly wrong within the scripts or addons?

**Comment by xhaggi** [comment]
> tw, what about orphaned python/addon dialogs? Is it possible to end up with opened dialogs in case something went utterly wrong within the scripts or addons?

@mkortstiege I only changed the newly introduced method `CloseModalDialogs()` which has no callers atm. So I don't see any issues with addon/python dialogs.

**Comment by mkortstiege** [comment]
Sure, this it out of the scope of this PR. Was just wondering if this could happen.

**Comment by ruuk** [comment]
@xhaggi I tested this PR with the HDHR addon and everything works as expected.

**Comment by xhaggi** [comment]
@ruuk great and thanks for testing.

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by xhaggi** [comment]
@mkortstiege any objections?

**Comment by mkortstiege** [comment]
Shove it in. In case the removal is causing issue we can add it back.

**Pull request merged**
