### PR TITLE
addons: Add Announce function and register addons for announcements

### PR DESCRIPTION
**Pull request by fetzerch**
This allows addons to receive announcements and react properly on
all kind of events and system state transitions.

For example pvr addons might want to close and reopen their backend
connections when the system goes to or resumes from standby.

### CODE REVIEW

**Comment by FernetMenta** [comment]
This is not thread safe can causes Kodi to crash. Further this is an abuse of the original idea of Announcement. IMO the best option is to revert this.

**Comment by opdenkamp** [comment]
just set the pointers in the call to nullptr. how is this abusing the idea of announcement? seems like the perfect interface for doing things like sending a backend to standby too, which is why @fetzerch wanted this originally iirc.

**Comment by FernetMenta** [comment]
> just set the pointers in the call to nullptr

this does not help. as mentioned, it is not thread safe and protecting the entire dll by a lock makes no sense. further PVRManager already implements IAnnounce

**Comment by opdenkamp** [comment]
what's not thread safe exactly? the dll has been using a shared_ptr since forever if that's what you mean. pvr manager has nothing to do with this, it's not even in the pvr's struct. it's about the add-on performing some action based on an event in kodi. do you have an alternative for that or do you want to dupe the whole announcement interface to get this back? i don't care about this much, i don't use it, but people are using it and just removing the method from the api after 3 years with no alternative seems to me like the big axe solution.

**Comment by FernetMenta** [comment]
> what's not thread safe exactly?

m_Dll is a member of the addon class and it has no protection. It does not matter if the addon itself is accessed via a shared pointer. The shared pointer does not protect the members of the class.

I am not saying that this should not get an alternative but for the moment fixing a crash is more important than this feature used only by a few.

**Comment by ksooo** [comment]
> but for the moment fixing a crash is more important than this feature used only by a few.

 Really? I have an opposite opinion an this.

**Comment by Jalle19** [comment]
Isn't there some easy way to make the whole thing thread-safe?

**Pull request merged**
