### PR TITLE
Add fourcc, colorspace and colorrange to inputstream API

### PR DESCRIPTION
**Pull request by peak3d**
## Description
Add fourcc, colorspace and colorrange to inputstream API

## Motivation and Context
Support dvhe (HEVC + Dolby Vision) for HDR streams

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Comment by ksooo** [comment]
Well, as far as I know we don't allow breaking API changes in beta stage. I'm afraid this change  has to wait until we branched v18.

**Comment by MartijnKaijser** [comment]
I'm fine with this API breakage as it only affect one addon we know of which is maintained by peak3d as well

**Comment by peak3d** [comment]
I changed the code so it should be backwards compatible.
I'll clean up the position of the new members if we make the next big bump.

**Comment by peak3d** [comment]
Jenkins build this please

**Comment by ksooo** [comment]
> I'll clean up the position of the new members if we make the next big bump.

@peak3d yeah, that should be fine. I did the same 'trick' for PVR some days ago, btw. ;-)

**Comment by CiNcH83** [comment]
> Support dvhe (HEVC + Dolby Vision) for HDR streams

AFAIK, Kodi doesn't yet pick the right decoder for DV, no? I tried to play some single-layer DV files on Sony ATV, but those were played without video. This is what my TV provides:

```OMX.dolby.vision.dvhe.stn.decoder        video/dolby-vision```

The files play fine with MX Player with the TV automatically switching to the DV picture profile.
VLC plays the video, but at wrong colors/luminance as it picks the common HEVC decoder instead of the DV enabled HEVC decoder.

**Pull request merged**
