### PR TITLE
[network] improvements to the webserver implementation

### PR DESCRIPTION
**Pull request by Montellese**
These commits don't really contain any new features but improve the implementation of and around `CWebServer` and also makes it possible to run multiple webservers with different configurations and different request handlers (which are currently statically configured).
Furthermore it introduces component logging for the webserver which is currently not possible because it has to be compiled with a special flag. This should make it easier to track down issues with webserver requests.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by stefansaraev** [comment]
needs a rebase

**Comment by Montellese** [comment]
done. jenkins build this please

**Comment by stefansaraev** [comment]
thanks.
last time I tested this, all seemed fine. @MilhouseVH mind including it in your builds for day or two ?

**Comment by MilhouseVH** [comment]
@stefansaraev This will be in tonight's 0504 build (RPi/RPi2/Generic).

**Comment by Montellese** [comment]
needs an Xcode sync

**Comment by ksooo** [comment]
@Montellese feel free to pick Xcode sync here: https://github.com/ksooo/xbmc/commit/21b22ef11ee281562495aeb987d7f64ff80df53b

**Comment by Montellese** [comment]
@ksooo thanks a lot. jenkins build this please

**Comment by Montellese** [comment]
Good to go if jenkins is happy? AppVeyor seems to be having a problem downloading the git repository?

**Comment by stefansaraev** [comment]
yep. it is known issue with appveyor

**Pull request merged**
