### PR TITLE
[fix] return type bool for boolean python functions

### PR DESCRIPTION
**Pull request by Rechi**
## Motivation and Context
https://forum.kodi.tv/showthread.php?tid=303073&pid=2873172#pid2873172

## How Has This Been Tested?
checked return type for `xbmcaddon.Addon().getSettingBool(..)`

## Types of change
- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by Rechi** [comment]
@enen92 ping

**Review by enen92 — APPROVED** [review]

**Comment by mediabrasiltv** [comment]
With this change, Kodi Matrix crash a few seconds after open, Returning to previous code work fine again, no more crash.

**Comment by MilhouseVH** [comment]
Also reported in the [forum](https://forum.kodi.tv/showthread.php?tid=343068&pid=2878222#pid2878222) and I'm able to reproduce [this myself](http://ix.io/1SAA) - will try reverting this PR.

**Comment by MilhouseVH** [comment]
Reverting this PR stops the crashing.

Here's a debug enabled LibreELEC x86_64 crashlog: http://ix.io/1SAO - perhaps just a coincidence that it crashed when the "Dim" screensaver started.

I built Kodi for Ubuntu x86_64, and couldn't get it to crash during normal usage, or after enabling the Dim screensaver, but then I had this crash when clicking Exit from the power menu:
```
*** Error in `/home/neil/projects/kodi.git/kodi-build/kodi-x11': free(): invalid pointer: 0x00007f3411c66bd0 ***
Aborted (core dumped)
```
This is the Ubuntu crash log: http://ix.io/1SAT

Not easy to reproduce with Ubuntu - I started kodi again and then exited immediately which doesn't crash, so there's something that is running in the background and corrupting kodi.

**Comment by Rechi** [comment]
crash is fixed at #16509

**Pull request merged**
