### PR TITLE
Fix zh-cn language name: Chinese (Simple) => Chinese (Simplified)

### PR DESCRIPTION
**Pull request by eatradish**
## Description
Change zh-cn language name: Chinese (Simple) => Chinese (Simplified)

## Motivation and Context
Currently the language name of zh-cn in Kodi is wrong, this PR will fix the wrong name.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
Just a note regarding this, we are currently testing a new translation service, and ive been informed if this were to be merged, it would be more than likely be over written by the existing automated transifex service.

We will keep this open for now, but we believe we will be best to hold on this until we get the translation service sorted, and then we can come back and double check what the state of the translation strings are then.

**Comment by gade01** [comment]
AFAIK
No matter which translation service we use or switch to in the future, this will get overwritten when translations are pushed.

This should be fixed at Transifex it Weblate.

**Comment by scott967** [comment]
Agree that Chinese (Simple} is not a thing.   It would be better if there was a way to use IETF BCP 47 as I don't think zh-cn is a language typography spec (i.e., ,allow HanS and HanT), but that's out of scope.

**Comment by eatradish** [comment]
Why is zh_CN now written as "Chinese (China)" and zh_TW as "Chinese (Traditional)" in the master branch?

**Comment by gade01** [comment]
@eatradish 
>Why is zh_CN now written as "Chinese (China)" and zh_TW as "Chinese (Traditional)" in the master branch?
It is copied from Transifex.
I can correct it at Weblate though.
What would be the correct names for `zh_cn` and `zh_tw`?

**Comment by eatradish** [comment]
> @eatradish
> 
> > Why is zh_CN now written as "Chinese (China)" and zh_TW as "Chinese (Traditional)" in the master branch?
> 
> It is copied from Transifex.
> I can correct it at Weblate though.
> What would be the correct names for `zh_cn` and `zh_tw`?
> 
> Right now `zh_cn` is `Chinese (China)` and `zh_tw` is `Chinese (Taiwan)`.

Sorry, it doesn't say exactly which place, it's here: https://github.com/xbmc/xbmc/blob/81c35da5c555aa010892bcbc4342d6d620585d1d/addons/service.xbmc.versioncheck/ resources/language/resource.language.zh_tw/strings.po#L12

**Comment by eatradish** [comment]
In addition, if it has been changed to Chinese (China), there is no need for me to keep opening this PR.

**Comment by gade01** [comment]
So Chinese (China) and Chinese (Taiwan) is correct?

I'll be glad to change it if it's more correct with Simplified and Traditional.

service.xbmc.versioncheck use Chinese (China) as well in the updated version:
https://github.com/xbmc/repo-scripts/blob/matrix/service.xbmc.versioncheck/resources/language/resource.language.zh_cn/strings.po#L12

**Comment by eatradish** [comment]
> So Chinese (China) and Chinese (Taiwan) is correct?
> 
> I'll be glad to change it if it's more correct with Simplified and Traditional.
> 
> service.xbmc.versioncheck use Chinese (China) as well in the updated version:
> https://github.com/xbmc/repo-scripts/blob/matrix/service.xbmc.versioncheck/resources/language/resource.language.zh_cn/strings.po#L12

Using Chinese (China) and Chinese (Taiwan) is actually better, because for now there are other regions that use simplified Chinese, such as zh_SG, and other regions that use traditional Chinese, such as zh_HK.

**Comment by gade01** [comment]
Perfect, sounds great.
Thanks for explaining. :)

**Pull request closed without merging**
