### PR TITLE
[libUPnP] Remove unused headers from Platinum/Source/Extras

### PR DESCRIPTION
**Pull request by olafhering**
No code from the Extras directory is compiled, so it is unlikely that
any of the interfaces will be used. Remove the headers and remove
Platinum/Source/Extras from the list of include directories.

Signed-off-by: Olaf Hering <olaf@aepfle.de>

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by pkerling** [comment]
Out of interest, is there any particular motivation for doing this?

**Comment by olafhering** [comment]
> Out of interest, is there any particular motivation for doing this?

Yes, shrinking the source.tar.xz to make it easier for legal review.

**Comment by pkerling** [comment]
> legal review

I'm confused, please elaborate

**Comment by olafhering** [comment]
> > legal review
> 
> I'm confused, please elaborate

For shipping it in upcoming Leap releases. It is still a long way to go to get there.

**Comment by pkerling** [comment]
Are you suggesting that someone is going to read through all the code?

**Comment by olafhering** [comment]
> Are you suggesting that someone is going to read through all the code?

I have no idea what they do. But if they indeed inspect each file, there is now 5MB less xz compressed, unused files from xbmc.git to review. Less than I had hoped, but still.

**Comment by pkerling** [comment]
Sounds like you're in for a long ride... All the best.

**Comment by Montellese** [comment]
TBH I'm not a fan of modifying external source code if it doesn't provide any gain for execution. All the patches to libPlatinum fix some issue we ran into while integrating / using it in Kodi but this doesn't really fix anything.

But since I don't really know / understand where the request comes from I can't judge if the team is ok with this change under these circumstances or not.

**Comment by pkerling** [comment]
Did we ever try to upstream these fixes?

**Comment by Montellese** [comment]
Some of them were upstreamed when I took over the UPnP part and introduced the patches (before we didn't track them explicitely).

**Comment by olafhering** [comment]
Is there any downside with this change? If the changed code is really "dead", we have the liberty to change it in any way we want. If there new releases in the next decade, the individual patches have to be reviewed either way at that time.
The plus side is that I do not need to carry yet another change, and it will reduce the build time for everyone by a few nanoseconds because fewer directories have be scanned.

**Comment by pkerling** [comment]
I'm cautiously leaning towards merging this, considering that as @Montellese claims platinum is not actively developed (i.e., chances of ever having this be a external library are slim). If someone disagrees, please speak up before the end of this week.

**Comment by phunkyfish** [comment]
@yol are you going to merge this? It's way past the end of the week ;)

**Pull request merged**
