### PR TITLE
[iOS] migrate to Launch Screen storyboard

### PR DESCRIPTION
**Pull request by kambala-decapitator**
## Description
Modern way of showing launch image on iOS is using storyboard as opposed to the old-school set of static launch images. This PR also displays the real launch image `media/splash.jpg` instead of black screen.

Please note that this change requires building project with Xcode/`xcodebuild` (i.e. not the simple `make`), as they compile storyboards internally. (already done in #16259 )

## Motivation and Context
- The main goal is to support native resolution of any future devices automatically without requiring to add a new static launch image of the proper size, as launch storyboard resizes itself to match screen size at runtime;
- issues like #16128 and #14994 will never take place any more;
- and it simply reduces amount of files in the repository.

## How Has This Been Tested?
Launched on iPhone 6s, iPhone 5, iPhone XR and iPad Air 2 and verified that launch screen is still shown.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [X] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
would be great is someone could also test on the new devices like iPad 10'' and bigger or iPhone X*

**Comment by Memphiz** [comment]
I don‘t think it has the benefits from the former approach.
Remember we can‘t update Xcode so often.
Imagine there is a new phone released and it has a new display. Before I added the new launch image and it resulted in full resolution for that phone.
Now we would need to update Xcode to support the new phone.
At least I think so - no?

**Comment by Memphiz** [comment]
This also needs changes in the buildsteps for Jenkins to use xcodebuild instead of make (similar to what tvOS needs)

**Comment by kambala-decapitator** [comment]
> At least I think so - no?

I thought that with storyboards it's not the case, but let's make a test. I can write a simple iOS app that shows current scale / screen size, which we'll run on newer devices. Unfortunately, the latest device I have is iPhone 8 and iPad Air 2, so we'll need tester(s) with iPhone X* and iPad 10''+ to verify against the latest models.

> This also needs changes in the buildsteps for Jenkins to use xcodebuild instead of make (similar to what tvOS needs)

true, but that's not something blocker, if I understand correctly.

**Comment by fuzzard** [comment]
@Memphiz https://github.com/xbmc/xbmc/pull/16259 will go most of the way to the jenkins issue being resolved.

Have tvos fleshed out as discussed, which would be the base of the further buildsteps required, but shouldnt be a problem. If you want a pr done, let me know, happy to help.

Ive got no input about the rest of this PR and its suitability. Leave that upto you guys

**Comment by kambala-decapitator** [comment]
The test app:
- https://www.dropbox.com/s/kwxbxxuwui50srw/ScreenProps9.txz?dl=0 built with xcode 9
- https://www.dropbox.com/s/k9pqkvkyf8h10ja/ScreenProps10.txz?dl=0 built with xcode 10

Hope it's clear how to run it on device :)

**Comment by kambala-decapitator** [comment]
> Now we would need to update Xcode to support the new phone.

based on the test app it's not the case, as all the values are correct regardless of what iOS SDK was used. @pogarek ran it on XS:


With this we can remove the hardcoded list of devices (that didn't make it into #16017).

**Comment by Memphiz** [comment]
Did you verify the used iOS SDK version in Xcode was below the first initial iOS version that was shipped with the XS?

**Comment by kambala-decapitator** [comment]
XS was released in September 2018 together with iOS 12 and Xcode 10, so it had iOS 12 on board right from the start.

**Review by Memphiz — APPROVED** [review]
Let’s hope apple makes this work for future devices with screen scale 3.33333 aswell ;)
Thx

**Comment by Memphiz** [comment]
@kambala-decapitator before this can be merged we need the Jenkins changes - else the official Jenkins builds will be screwed up without proper device resolution

**Comment by kambala-decapitator** [comment]
@Memphiz thanks!

@fuzzard your turn :)

**Comment by fuzzard** [comment]
Have added a commit to PR https://github.com/xbmc/xbmc/pull/16259 that does the buildsteps changes.

**Comment by kambala-decapitator** [comment]
just for the reference will leave the code I used for the test app: https://gist.github.com/kambala-decapitator/28e7666434e680a6e324d600cb76caab

**Comment by kambala-decapitator** [comment]
@Memphiz so Jenkins has been merged...

**Comment by Memphiz** [comment]
@kambala-decapitator nope it hasn‘t https://github.com/xbmc/xbmc/pull/16259 there was a request from rechi left

**Comment by kambala-decapitator** [comment]
oh right, there's still another PR pending, thanks for reminding

**Pull request merged**
