### PR TITLE
[cmake] fix libdvd depends build

### PR DESCRIPTION
**Pull request by lrusak**
## Description

libdvd{read,css,nav} should be built when KODI_DEPENDSBUILD is set, not the other way around.

Instead of the `NOT` I can flop the logic around instead if desired.

## Motivation and Context

libdvd{read,css,nav} should not be downloaded/built when not doing a depends build

## How Has This Been Tested?

build tested in LibreELEC

With this it now finds and links the correct libraries
```
DVDREAD_LIBRARY:FILEPATH=/home/lukas/libreelec/build.LibreELEC-RPi2.arm-8.0-devel/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/lib/libdvdread.a
DVDCSS_LIBRARY:FILEPATH=/home/lukas/libreelec/build.LibreELEC-RPi2.arm-8.0-devel/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/lib/libdvdcss.a
DVDNAV_LIBRARY:FILEPATH=/home/lukas/libreelec/build.LibreELEC-RPi2.arm-8.0-devel/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/lib/libdvdnav.a
```

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by hudokkow** [comment]
travis doesn't like it.

**Comment by lrusak** [comment]
Do we not include libdvd* on the system for Linux builds?

**Comment by wsnipex** [comment]
This is wrong!

**Comment by lrusak** [comment]
So if it's a depends build it doesn't build libdvd*???

And if it's not a depends build it builds libdvd*??

How does that make sense?

**Comment by wsnipex** [comment]
KODI_DEPENDSBUILD is true when unified depends are used. that means all depends have been built _before_ kodi

**Pull request closed without merging**
