### PR TITLE
[gui] new ACTION_MENU key to focus sidebar menu

### PR DESCRIPTION
**Pull request by xhaggi**
This adds a new key ACTION_MENU which is translated to "menu" to use in keymaps. The key is used to focus the first button control and in pvr the corresponding button control of the current view within our sidebar menu. 

The initial intention was to quick access the sidebar menu if you stay in epg grid, because top/buttom/left/right is used for scrolling and you can't access the menu quickly. As @da-anda said, it would be make more sense if we could get this in all related windows, so here it is.

### CODE REVIEW

**Comment by xhaggi** [comment]
@mkortstiege after we've merged #7346 it's time to re-activate this PR ;)

**Comment by mkortstiege** [comment]
Now that the longpress PR is merged, we should decide how to proceed with this one. Any objections?

**Comment by xhaggi** [comment]
i'll adjust the remote.xml to use longpress tomorrow and if no objections we could merge it in.

**Comment by mkortstiege** [comment]
> i'll adjust the remote.xml to use longpress tomorrow and if no objections we could merge it in.

Sounds good. Thanks!

**Comment by xhaggi** [comment]
Tested on a FireTV with menu-mutton mapped to `Menu` and menu-button longpress to `ContextMenu` and it works like a charm.

**Comment by xhaggi** [comment]
if no objections I'll merge it in tomorrow

**Comment by xhaggi** [comment]
@ronie done

jenkins build this please

**Pull request merged**
