### PR TITLE
Consolidate OpenSSL multi-threading initialization

### PR DESCRIPTION
**Pull request by yol**
OpenSSL is already being used on all platforms, and in #13647 we discussed making it required for digest calculation. This PR is about making OpenSSL required and consolodating the multi-threading initialization in one place for < 1.1. I have code ready for replacing `XBMC_MD5` with OpenSSL code that I'll PR after this is merged.

Currently, we're initializing OpenSSL multi-threading both in `DllLibCurl` and in `CryptThreadingInitializer` depending on different conditions. It might even be initialized twice since they are not mutually exclusive. So my proposal is to do everything once in `CryptThreadingInitializer` - it's not really related to libcurl any more since we need it for our own usage of openssl anyway.

I don't see how linking libcurl statically makes any difference, but I might very well be missing something, so let's see how badly this blows up in my face :-)

### CODE REVIEW

**Comment by pkerling** [comment]
jenkins build this please

**Comment by pkerling** [comment]
jenkins build this please

**Comment by pkerling** [comment]
Would be great to get some input on this. I'm a bit afraid to just merge it, but if no one remembers what this was done for any more I guess we'll have to try.

**Comment by wsnipex** [comment]
>I don't see how linking libcurl statically makes any difference, but I might very well be missing something, 

you can find the background in https://github.com/xbmc/xbmc/pull/5048 and the PR linked there

**Comment by pkerling** [comment]
> you can find the background in #5048 and the PR linked there

Thanks. Since we don't load libcurl dynamically any more, I think the reasons also ceased to apply.

In fact we could probably get by without this code completely since ffmpeg initializes openssl thread locking anyway. Should we keep it around in spite of that?

**Comment by wsnipex** [comment]
ffmpeg can be linked dynamically. I'd rather not risk getting rid of this until we require openssl >=1.1 on all platforms.

**Comment by wsnipex** [comment]
I meant that some distros tend to use gnutls for ffmpeg, so we cannot rely on it for the callbacks.

**Comment by pkerling** [comment]
> I meant that some distros tend to use gnutls for ffmpeg, so we cannot rely on it for the callbacks.

Fair point, makes a lot more sense now :-)

So keeping the initialization code in, what's your stance on this PR overall?

**Comment by wsnipex** [comment]
the PR looks good to me

**Comment by pkerling** [comment]
Thanks. I'll merge this tomorrow if no one brings up any objections.

**Comment by pkerling** [comment]
jenkins build this please

**Comment by Rechi** [comment]
Documentation currently tells that gnutls flavor of libcurl can also be used, as this doesn't seem to be possible any more it should be removed.
https://github.com/xbmc/xbmc/blob/c1d3beedb16ba0cda61919361ba69f4c2c1473c5/docs/README.linux#L50
https://github.com/xbmc/xbmc/blob/c1d3beedb16ba0cda61919361ba69f4c2c1473c5/docs/README.opensuse#L66

**Comment by pkerling** [comment]
Why do you think it's not possible any more?

**Comment by Rechi** [comment]
Was only thinking about the now required openssl headers and only searched for openssl dev package in the docs. Now I searched again with the correct name (`libssl-dev`) so all fine.

**Pull request merged**
