### PR TITLE
Update LinuxInputDevices.cpp

### PR DESCRIPTION
**Pull request by denimjeans**
TranslateKey returned XBMCK_UNKNOWN from code(172)
added the key, hopefully in the correct format-
denim

### CODE REVIEW

**Comment by mkortstiege** [comment]
Looks good to me. @Memphiz mind checking as well? I am not entirely sure if we are adding custom buttons in here.

**Comment by Memphiz** [comment]
mhh KEY_HOME is already mapped to XBMCK_HOME a couple of lines above. What remotr is this? Either our define of KEY_HOME is wrong or there are multiple codes floating around for that key. @seo - iirc you have a good knowledge of input key mapping stuff - a word? ;)

**Comment by Memphiz** [comment]
ops i ment @stefansaraev

**Comment by stefansaraev** [comment]
from include/uapi/linux/input.h
```
#define KEY_HOMEPAGE            172     /* AC Home */
```

**Comment by Memphiz** [comment]
or add that define if possible ;)

**Comment by denimjeans** [comment]
hi, 
define is taken out from include/uapi/linux/input.h as @stefansaraev  refered. if you are using KEY_HOMEPAGE anywhere else, then this might be wrong since it's defined already ;-) . But I am not an expert, though... 
My comments were:
// Rii i7 Home button - TranslateKey returned XBMCK_UNKNOWN from code(172)

**Comment by Memphiz** [comment]
And we can't include that header here and use their define? I am not familiar with this part of the code - but the name of the file suggests that this might be a possible thing to do.

**Comment by denimjeans** [comment]
it's already there: 
line 44: #include <linux/input.h>

**Comment by Memphiz** [comment]
then you could use KEY_HOMEPAGE instead of magic number 172 in your mapping no?

**Comment by denimjeans** [comment]
true, but how to change that? I am not familiar with github and patching etc

**Comment by Memphiz** [comment]
make the change in your local workspace, commit it as extra commit - then do
git rebase HEAD~2 -i

and fixup the last commit into the first (just replace "pick" with "f" in front of the last commit) - and close the editor - after that you will see one commit only on the top of your branch (git log) - this is the altered commit then. To make this apply to this pull request force push the changes to your repo (and this PR will get updated automatically)

git push -f origin master

Hint for the next time - don't work in the master branch but use a branch dedicated to the problem you are working on ...

**Comment by mkortstiege** [comment]
Hm. looks like at least related ;) https://github.com/OpenELEC/OpenELEC.tv/blob/master/projects/WeTek_Play/patches/kodi/0101-add_mapping_for_browser_home_key_on_linux.patch

**Comment by MartijnKaijser** [comment]
already added in other PR

**Pull request closed without merging**
