### PR TITLE
[keymaps] new controller keymap joystick.Tronsmart.Mars.G01.xml

### PR DESCRIPTION
**Pull request by wizetek**
new keymap (based on joystick.xml.sample) for a game controller made by Tronsmart
hardware info link: http://www.tronsmart.com/products/accessories/tronsmart-mars-g01.html

### CODE REVIEW

**Comment by Razzeee** [comment]
PING @jhsrennie @NedScott

**Comment by NedScott** [comment]
Looks good to me.

**Comment by MartijnKaijser** [comment]
@garbear ping

**Comment by garbear** [comment]
Can you send this to the Jarvis branch instead? In Krypton, joysticks now use a common keymap, [joystick.xml](https://github.com/xbmc/xbmc/blob/master/system/keymaps/joystick.xml). Per-joystick button map data has been moved to an add-on, peripheral.joystick: [resources/buttonmaps/xml](https://github.com/kodi-game/peripheral.joystick/tree/master/peripheral.joystick/resources/buttonmaps/xml).

The per-joystick button map data can be created within the GUI. See the [Guide to configure controllers in Kodi](http://forum.kodi.tv/showthread.php?tid=252465). Note that there's currently a bug that disables all non-system, pre-installed add-ons (including joystick support) on first run, so joystick support will have to be enabled manually in the add-on manager until this is fixed.

**Comment by Razzeee** [comment]
Well I don't think there will be another Jarvis release. So we might as well close this. 

@martijnKaijser for confirmation

**Comment by MartijnKaijser** [comment]
Indeed I highly doubt there will be a 16.2

**Comment by NedScott** [comment]
@wizetek I can make this a wiki page for people who want the controller to work in v16. I don't know how many people actually use those keymap pages, but I guess it's better than nothing ;)

http://kodi.wiki/view/Alternative_keymaps_for_Tronsmart_Mars

**Comment by wizetek** [comment]
Wiki is fine and good to have around just in case. Thanks.

**Pull request closed without merging**
