### PR TITLE
binary addons: automatic dependency handling

### PR DESCRIPTION
**Pull request by Montellese**
This is an extracted and cleaned up version of #5329 with only the changes to dependency handling and without the addition of the screensaver and visualization binary addons. A detailed description and discussion can be found in #5329.

Jenkins build is running at http://jenkins.kodi.tv/job/BuildMulti-All/562/ and succeeded for all platforms but IOS/ATV2 will most likely fail due to a change in audioencoder.flac but @wsnipex and @Memphiz already know about it.

Before this can be merged I will have to update all audioencoder addon repositories with win32 dependencies and update the commit hashes of the addons.

### CODE REVIEW

**Comment by FernetMenta** [comment]
awesome!

**Comment by notspiff** [comment]
https://github.com/Montellese/xbmc/commit/e26f75d4731a6d60a54675b9b89da98f688f7e04 should be in the other pr. it's needed for projectm only atm.

**Comment by Montellese** [comment]
@notspiff: Thanks for pointing it out. Must have missed that one during the rebase.

**Comment by Montellese** [comment]
And these are the necessary PRs for WIN32 for the audioencoder addons:
* https://github.com/xbmc/audioencoder.flac/pull/8
* https://github.com/xbmc/audioencoder.lame/pull/6
* https://github.com/xbmc/audioencoder.vorbis/pull/7

**Comment by Montellese** [comment]
I have merged all the win32-specific PRs in the audioencoders. Now I'm just waiting for https://github.com/xbmc/audioencoder.flac/pull/9 to be merged so that IOS/ATV2 will work again as well.

I'd like to get this in during this merge window so that we can rebase #5329 and I can prepare the PVR addons.

**Comment by Montellese** [comment]
Updated with the new commit hashes for flac, lame and vorbis audioencoders. Thanks @wsnipex for fixing the IOS/ATV2 issue.

jenkins build this please

**Comment by Montellese** [comment]
@wsnipex: Hmn IOS/ATV2 failed again, see http://jenkins.kodi.tv/job/IOS-ATV2/2778/consoleFull.

**Comment by notspiff** [comment]
Internal compiler error. Gcc 4.2 is ancient and was buggy as feck even on x86. Drop this useless platform already ;>

**Comment by wsnipex** [comment]
well, the -fPIC is still there. No idea how this is happening, since I specifically test if the compiler eats that flag.

**Comment by notspiff** [comment]
compiler eats the flag cause you havent set the target. it is gcc after all..

**Comment by Memphiz** [comment]
If it was 4 weeks later we wouldn't need to bother with gcc anymore :(

**Comment by wsnipex** [comment]
@notspiff do you mean add_definitions("-fPIC")? could be please be more specific?

**Comment by notspiff** [comment]
when you probe the compiler, you need to set the correct flags for target. in fact i do not know if gcc will reject the flag even then.

**Comment by notspiff** [comment]
oh and you set those using some particular vars canot recall which and only on mobile atm. see top of checkcxxflagfoo.cmake

**Comment by wsnipex** [comment]
anyway, not going to waste more time with these shitty toolchains. Just disable the flac encoder for IOS, nobody needs it on those devices anyway.

**Comment by FernetMenta** [comment]
is there anything this flac encoder can do what ffmpeg can't? may dropping it completely in favor od a flac built-in one.

**Comment by Montellese** [comment]
@FernetMenta: I have no clue, I'm just the cmake monkey.

**Comment by notspiff** [comment]
no technical reason. last time i checked ffmpeg encoder gave 10% larger files or so but that was years ago (at the supposedly same compression level - max for both encoders).

**Comment by FernetMenta** [comment]
@notspiff can we have both? I would assume that loaded addons override built-ins, right?

**Comment by notspiff** [comment]
i am not sure how the factory is written atm but it would at worst require trivial modifications.

**Comment by Montellese** [comment]
or use different addon IDs if we want to allow both.

**Comment by notspiff** [comment]
yeah just checked how i did this thing. separate ids and it is all good.

**Comment by Montellese** [comment]
OK I've added additional functionality to the parsing of `platforms.txt` and now it's possible to specify a negated platform like in the case of `audioencoder.flac` where it contains `!ios`. That should be eaiser and more future proof than having to list all supported platforms and remembering to update them in case there's a new one.

jenkins build this please

**Comment by Montellese** [comment]
Yay. @wsipex @Memphiz you ok with this?

**Comment by wsnipex** [comment]
sure

**Comment by Montellese** [comment]
@Memphiz: Are you ok with disabling audioencoder.flac for IOS/ATV2? I'm not even sure if any of the audioencoders make sense on IOS since they can only be used with tracks on a disc.

**Comment by Memphiz** [comment]
yeah no problem :)

**Comment by uNiversaI** [comment]
Ok the encoders wont compile at all in linux now.

```
$ sudo make -C tools/depends/target/xbmc-audioencoder-addons PREFIX=/usr
make: Entering directory `/home/setup/xbmc/tools/depends/target/xbmc-audioencoder-addons'
Makefile:4: ../../Makefile.include: No such file or directory
make: *** No rule to make target `../../Makefile.include'. Stop.
make: Leaving directory `/home/setup/xbmc/tools/depends/target/xbmc-audioencoder-addons'
```

Is this to be expected at the moment?

**Comment by Montellese** [comment]
Jenkins never complained. Maybe they can only be built from the tools/depends directory due to the relative path to `../../Makefile.include`? I'm sure @wsnipex can tell you what's wrong.

**Pull request merged**
