### PR TITLE
Added lithuanian keyboard layout

### PR DESCRIPTION
**Pull request by Zapata11**

### CODE REVIEW

**Comment by Zapata11** [comment]
In fact layout is called ĄŽERTY, but I agree that it make sense to rename it to AZERTY for better compatibility. lithuanian.xml is updated now.

**Comment by uNiversaI** [comment]
squash commits

**Comment by Zapata11** [comment]
done

**Comment by da-anda** [comment]
@MartijnKaijser Isengard nobrainer?

**Pull request merged**
