### PR TITLE
[backport][GUITextLayout] Fix text wrap and justify alignment

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

backport of #24905
## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by CrystalP — APPROVED** [review]
LGTM. Maybe wait for no negative feedback in v22 for a bit for the merge

**Comment by CastagnaIT** [comment]
> Maybe wait for no negative feedback in v22 for a bit for the merge

yes also better merge #24851 before this one

**Comment by ksooo** [comment]
> yes also better merge https://github.com/xbmc/xbmc/pull/24851 before this one

This one is merged meanwhile and no negative feedback for #24905 for 3 weeks. Let's merge this one.

**Comment by CrystalP** [comment]
Lol I was going to comment soon but didn't have the time to bisect. Something strange happened with the "migrating addons" "migrating database" texts of the splash screen. They used to be centered and are not anymore. This change is a possible candidate,

**Comment by ksooo** [comment]
Yikes!

**Comment by CrystalP** [comment]
It didn't come from here. Issue #25155 created.

**Pull request merged**
