### PR TITLE
Use CMAKE_CXX_STANDARD to settle on --std= C++ option

### PR DESCRIPTION
**Pull request by olafhering**
The project CMakeLists.txt sets the CMAKE_CXX_STANDARD variable,
and it also makes this standard a requirement. As a result, cmake
will pass the desired -std=${val} already to the compiler.

Remove unneeded assignments to CXX11_SWITCH.
Remove uneeded FindCXX11.cmake.

Signed-off-by: Olaf Hering <olaf@aepfle.de>

### CODE REVIEW

**Review by yol — APPROVED** [review]
lgtm

@wsnipex ?

**Comment by wsnipex** [comment]
as is it will remove c++11 from binary addons cxx flags.
@notspiff any reason not to set CMAKE_CXX_STANDARD in KodiConfig.cmake instead?

**Comment by olafhering** [comment]
I think the addons are free to use their own C++ standard. Unless, of course, the header files use features that do require a certain level of C++.

**Comment by AlwinEsch** [comment]
CMAKE_CXX_STANDARD and CXX11_SWITCH are not direct set for addons, only on KodiConfig.cmake.in for creation of them with `@CXX11_SWITCH@`.

Also tested now without `CMAKE_CXX_FLAGS` in [KodiConfig.cmake](https://github.com/xbmc/xbmc/blob/master/cmake/KodiConfig.cmake.in#L21), here on Ubuntu 19.4 the addon compile has worked and not the old CXX11 Errors.

But not sure if this still required on Ubuntu 16.4. Long time ago, but think very much has needed the CXX11 support.

**Comment by wsnipex** [comment]
We've set this flag until now, so we effectively forced addons to use c++11.
I see no issue with CMAKE_CXX_STANDARD for addons instead. They can always override it if needed

**Comment by pkerling** [comment]
@wsnipex Is the add-on issue cleared up? Good for merge?

**Comment by wsnipex** [comment]
nothing has changed. I still think we should set CMAKE_CXX_STANDARD in KodiConfig.cmake if we removed the cxx11 flag. The former is missing here

**Comment by pkerling** [comment]
@olafhering we can merge if you make the change @wsnipex requested

**Comment by olafhering** [comment]
I have updated the PR and some limited testing shows the CXX value is used by external addons.

**Comment by ksooo** [comment]
@olafhering  Recently, travis builds for all binary pvr addons broke. Those addons have a C-API, not C++. Could this breakage be related to this PR?

Example: https://travis-ci.org/kodi-pvr/pvr.hts/builds/524173468

**Comment by pkerling** [comment]
It probably is. Does not look like the build is using the right options. @wsnipex?

**Comment by olafhering** [comment]
> @olafhering Recently, Travis-CI builds for all binary pvr addons broke. Could this breakage be related to this PR?
> 
> Example: https://travis-ci.org/kodi-pvr/pvr.hts/builds/524173468

I have to decipher the log first. The builds lack a "V=1", which would allow better guesses about the uses compiler flags. Perhaps there was no -std= before, while it is used now.

What stands out is "kodi-platform". In my builds I did unfortunately not reach the pvr.* addons yet. But in all other addon the usage of "kodi-platform" has been removed. That pkg appears to be a noop, just drop it.

**Comment by ksooo** [comment]
> hat pkg appears to be a noop, just drop it.

 Interesting POV. Go and fix the regression, please.

**Comment by olafhering** [comment]
> > hat pkg appears to be a noop, just drop it.
> 
> Interesting POV. Go and fix the regression, please.

In a jiffy.

**Comment by ksooo** [comment]
>  In a jiffy.

 Thx.

**Comment by ksooo** [comment]
It's not just "kodi-platform" that bombs, btw.

**Comment by olafhering** [comment]
pvr.hts builds fine for me, even with --std=cxx17.
How do I get kodiplatform out of the way? Just tweaking CMakefile does not help, it is pulled in anyway.

I planned to wipe it from all addons, just did not get around because I reached not 100% addon builds yet.

**Comment by Rechi** [comment]
You building the addons the distro way not the way defined in the travis.yml files?
Test the travis way and it will fail.

**Comment by olafhering** [comment]
Where is it referenced, is there a "master" file that is used for all addons?

**Comment by pkerling** [comment]
> pvr.hts builds fine for me, even with --std=cxx17.

The problem is the other direction. Add-on build does not seem to set `-std=c++11`, which for gcc 5.4 means c++03

**Comment by olafhering** [comment]
Are you saying despite `+set(CMAKE_CXX_STANDARD_REQUIRED @CMAKE_CXX_STANDARD_REQUIRED@)`, the requested value is downgraded anyway? Weird.

Anyway, I think moving forward here means that kodiplatform must go. I can do a mass edit/submit with `hub`, but the travis build must be fixed first to not try to build kodiplatform anway. Where is the place for that?

**Comment by Rechi** [comment]
`cmake/KodiConfig.cmake(.in)` is not used the way travis builds addons and documentation in this repo tells to build addons.

**Comment by wsnipex** [comment]
the PR above _should_ fix it, please verify

**Comment by olafhering** [comment]
> the PR above _should_ fix it, please verify

How does that PR fix it?

kodi-platform uses uint32_t, but makes zero attempt to get that data type.
xbmc/kodi-platform#28 is supposed to fix this bug in kodi-platform.

**Comment by wsnipex** [comment]
I makes sure C++11 standard is set for addons....

**Comment by olafhering** [comment]
> [xbmc/kodi-platform#28](https://github.com/xbmc/kodi-platform/pull/28) is supposed to fix this bug in kodi-platform.

Builds do not use `master`. Is `e8574b883ffa2131f2eeb96ff3724d60b21130f7` hardcoded somewhere, or does it just take a few days until the fix is used?

**Comment by Rechi** [comment]
`git grep e8574b883ffa2131f2eeb96ff3724d60b21130f7` will tell you.

**Pull request merged**
