### PR TITLE
Handle Standard Uppercase ReplayGain Tags for M4A and WMA

### PR DESCRIPTION
**Pull request by complexlogic**
## Description
The [ReplayGain standard](https://wiki.hydrogenaud.io/index.php?title=ReplayGain_2.0_specification) requires uppercase metadata tags, but Kodi currently only reads lowercase ReplayGain tags for the M4A and WMA formats.

## Motivation and context
Kodi successfully reads the standard uppercase ReplayGain tags for all other tag formats, only M4A and WMA are not supported. If this PR is merged, all audio formats supported in Kodi will be conformant with the ReplayGain standard.

## How has this been tested?
1. Generated one M4A and one WMA test file with uppercase ReplayGain tags
2. Scanned files into library using current `master`, verified that the `strReplayGain` field in the music database file is not populated for either test file
3. Made the change contained in this PR, re-scanned the test files into library, verified that the `strReplayGain` field in the music database is populated and correct for both test files.

## What is the effect on users?
The non-standard lowercase ReplayGain tags are still handled, so this won't break any existing functionality.

## Screenshots (if appropriate):
N/A

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by scott967** [comment]
I don't know of a problem with this, but the referenced draft standard requires the replaygain metadata for m4a/mp4 files be provided in an "id3v2 box" which we (and AFAIK taglib) do not support.  Instead free-form metadata is provided by an itunes tag "----:com.apple.iTunes:<str>" where <str> is an undefined string.   In some cases <str> is uppercase, in others title case.

**Comment by CastagnaIT** [comment]
so why not use `StringUtils::CompareNoCase` instead to add more conditions?

**Comment by complexlogic** [comment]
@scott967 Yes, unfortunately the standard wasn't very well designed in several areas, one of which is the recommendation of using non-native tag formats on several file types. It's not only MP4; it also specifies Vorbis comment for WMA, instead of ASF, which is not even mentioned at all.

I am familiar with the ReplayGain "ecosystem" i.e. what is actually implemented in practice and, for M4A files, storing the ReplayGain tags in an MP4 comment within the iTunes namespace is ubiquitous. However, most people interpret the all-uppercase tags to be standard regardless of the metadata format. That is why I think the uppercase tags should be recognized by Kodi for all file types.

**Comment by complexlogic** [comment]
@CastagnaIT That is an interesting idea. The problem is that TagLib does not use `std::string`, it uses a custom string class `TagLib::String`. In order to use that Kodi string comparison function, we would need to first convert `TagLib::String` to a C string which, according to the TagLib documentation, results in a separate heap allocation. 

I think the proposed implementation is robust enough and using `StringUtils::CompareNoCase` would add unneeded complexity and runtime overhead. 
Any other opinions?

**Comment by CastagnaIT** [comment]
for me ok, i leave last word to @scott967
only request is apply jenkins changes
and please prefix your commit title with `[taglib]`

**Comment by complexlogic** [comment]
@CastagnaIT Done.

**Comment by scott967** [comment]
Went back and looked at the original implementation for m4a from PR [https://github.com/xbmc/xbmc/pull/3587](https://github.com/xbmc/xbmc/pull/3587) and didn't see any reason for the casing used there.  Do not see a problem.  I don't have any experience with ASF tags so no comment there.

**Comment by garbear** [comment]
I see no harm in this PR and it purely makes the code more robust. I would go a step further and use StringUtils::ToLower() on everything to make it fully case-insensitive.

**Comment by CastagnaIT** [comment]
@garbear you cannot use StringUtils because its not a c++ string but a class object
otherwise we need to convert `it->first` to string on top of the loop and then use that variable to all conditions

**Comment by complexlogic** [comment]
@garbear @CastagnaIT Another option: the TagLib string class has a member function `upper()` which will convert everything to uppercase. There was PR #4253 back in 2014 which used that function to implement case insensitive tag reading for MP3. We could do something similar for the other formats.

**Comment by garbear** [comment]
@complexlogic `upper()` also accomplishes case-insensitive compare, so I'd chose that, but no biggie

**Pull request merged**
