### PR TITLE
Enable true 1920x1080 output without upscaling on Amlogic-based devices

### PR DESCRIPTION
**Pull request by codesnake**

### CODE REVIEW

**Comment by hudokkow** [comment]
@koying ping

**Comment by koying** [comment]
This is for linux only, which I'm not involved in.
If it actually works (on all aml devices), it's much better, though ;)

**Comment by fritsch** [comment]
jenkins build this please (let's see if it breaks something build wise)

**Comment by MartijnKaijser** [comment]
well it doesn't build.
see http://jenkins.kodi.tv/job/BuildMulti-PR/3277/

**Comment by koying** [comment]
fbdev_window is probably an aml extension.
you have to wrap it with ```#if defined(_FBDEV_WINDOW_H_)```

**Comment by codesnake** [comment]
Strange, why EGLNativeTypeAmlogic.cpp is included into LINUX-RBPI build?

**Comment by MartijnKaijser** [comment]
@popcornmix ping

**Comment by popcornmix** [comment]
It's included because it's unconditional here:
https://github.com/xbmc/xbmc/blob/master/xbmc/windowing/egl/Makefile.in#L4

Is there a build target for amlogic? Ideally it should inside a ``ifeq (@USE_AMLOGIC@,1)`` type construct.

**Comment by koying** [comment]
Historically, the ifdef's were inside the egl implementations.
We moved them to EGLWapper.cpp as we modified them, but amlogic has no specific, linux-only, define, currently. 
Be sure to not use USE_LIBAMCODEC, as it's used on android also.

**Comment by codesnake** [comment]
I've wrapped fbdev_window with ```#if defined(_FBDEV_WINDOW_H_)``` as @koying suggested

**Comment by da-anda** [comment]
jenkins build this please

**Comment by codesnake** [comment]
Any news about this PR?

**Comment by koying** [comment]
Well, you're basically the AML for Linux maintainer, so if it's good for you, good for me.

**Pull request merged**
