### PR TITLE
[json-rpc] Fix playback of pvr channels and pvr recordings - trac#17984.

### PR DESCRIPTION
**Pull request by ksooo**
Superseeds #14299 
Fixes trac#17984 (https://trac.kodi.tv/ticket/17984)

@a1rwulf fyi - could you runtime test this, please?

### CODE REVIEW

**Comment by a1rwulf** [comment]
Works here - thx @ksooo

**Review by a1rwulf — APPROVED** [review]

**Comment by DaveTBlake** [comment]
Git label all very nice, but if you are changing internals then the JSON schema version patch number needs to bump too please, then it is easy for consumers of the API to trace what has changed and why.  That is edit https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/version.txt, the final digit is the patch number

**Comment by a1rwulf** [comment]
So where's the problem?
This has been changed in the PR.

**Comment by DaveTBlake** [comment]
So it has, but wasn't when I looked. Most odd.

**Comment by ksooo** [comment]
It was always there - at least in this PR. Seems you mixed up this PR with the PR by a1rwulf that was super seeded by this PR. a1rwulf's PR did not have the version bump. ;-)

**Pull request merged**
