### PR TITLE
Build jsonschemabuilder for all platforms from source

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Build jsonschemabuilder from source for all platforms

## Motivation and context
Less prebuilt windows dependencies. Its a one source file program, so building in tree always is a minimal time add.

## How has this been tested?
Jenkins

## What is the effect on users?
N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by basilgello** [comment]
This will probably work on Linux since we don't ship it.

**Comment by MediaBrasil** [comment]
@fuzzard 

Please when I run buildsetup win x64

I receive this message error 

Have one tip how I solve, please

  -- Configuring incomplete, errors occurred!
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): e
rror MSB8066: Custom build for 'C:\xbmc_omega\kodi-build.x64\CMakeFiles\8dbac698ecefa7b2f1417bbce9142d36\JsonSchemaBuil
der-mkdir.rule;C:\xbmc_omega\kodi-build.x64\CMakeFiles\8dbac698ecefa7b2f1417bbce9142d36\JsonSchemaBuilder-download.rule
;C:\xbmc_omega\kodi-build.x64\CMakeFiles\8dbac698ecefa7b2f1417bbce9142d36\JsonSchemaBuilder-update.rule;C:\xbmc_omega\k
odi-build.x64\CMakeFiles\8dbac698ecefa7b2f1417bbce9142d36\JsonSchemaBuilder-patch.rule;C:\xbmc_omega\kodi-build.x64\CMa
keFiles\8dbac698ecefa7b2f1417bbce9142d36\JsonSchemaBuilder-configure.rule;C:\xbmc_omega\kodi-build.x64\CMakeFiles\8dbac
698ecefa7b2f1417bbce9142d36\JsonSchemaBuilder-build.rule;C:\xbmc_omega\kodi-build.x64\CMakeFiles\8dbac698ecefa7b2f1417b
bce9142d36\JsonSchemaBuilder-install.rule;C:\xbmc_omega\kodi-build.x64\CMakeFiles\aef7ff1d23731aa4dc75a168f2cd29f5\Json
SchemaBuilder-complete.rule;C:\xbmc_omega\kodi-build.x64\CMakeFiles\46b16891b65497034a41d48277f68d02\JsonSchemaBuilder.
rule;C:\xbmc_omega\CMakeLists.txt' exited with code 1. [C:\xbmc_omega\kodi-build.x64\JsonSchemaBuilder.vcxproj]
  Creating directories for 'libdvdcss'

**Comment by thexai** [comment]
@MediaBrasil 
Works fine but you need clean, download, and rebuild Windows dependencies:

- delete `kodi\project\BuildDependencies\x64` folder
- run `kodi\tools\buildsteps\windows\x64\download-dependencies.bat`
- run BuildSetup.bat

**Comment by MediaBrasil** [comment]
@thexai, 

All new by zero, same error, and I noticed one error before cmake, but it's installed and worked before

" CMake Error at CMakeLists.txt:2 (project):
    No CMAKE_CXX_COMPILER could be found.""

 -- The CXX compiler identification is unknown
  CMake Error at CMakeLists.txt:2 (project):
    No CMAKE_C_COMPILER could be found.

 -- Configuring incomplete, errors occurred!
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): e
rror MSB8066: Custom build for 'G:\xbmcomeganew\kodi-build.x64\CMakeFiles\e0850d7bc02f8c425d853e649ea98c51\JsonSchemaBu
ilder-mkdir.rule;G:\xbmcomeganew\kodi-build.x64\CMakeFiles\e0850d7bc02f8c425d853e649ea98c51\JsonSchemaBuilder-download.
rule;G:\xbmcomeganew\kodi-build.x64\CMakeFiles\e0850d7bc02f8c425d853e649ea98c51\JsonSchemaBuilder-update.rule;G:\xbmcom
eganew\kodi-build.x64\CMakeFiles\e0850d7bc02f8c425d853e649ea98c51\JsonSchemaBuilder-patch.rule;G:\xbmcomeganew\kodi-bui
ld.x64\CMakeFiles\e0850d7bc02f8c425d853e649ea98c51\JsonSchemaBuilder-configure.rule;G:\xbmcomeganew\kodi-build.x64\CMak
eFiles\e0850d7bc02f8c425d853e649ea98c51\JsonSchemaBuilder-build.rule;G:\xbmcomeganew\kodi-build.x64\CMakeFiles\e0850d7b
c02f8c425d853e649ea98c51\JsonSchemaBuilder-install.rule;G:\xbmcomeganew\kodi-build.x64\CMakeFiles\76973b8cafed5c2eb1cf4
269bde3657b\JsonSchemaBuilder-complete.rule;G:\xbmcomeganew\kodi-build.x64\CMakeFiles\c9d8234ac857c9aa1db3277f8d3acfaf\
JsonSchemaBuilder.rule;G:\xbmcomeganew\CMakeLists.txt' exited with code 1. [G:\xbmcomeganew\kodi-build.x64\JsonSchemaBuilder.vcxproj]

**Comment by MediaBrasil** [comment]
here a few more about it

-- Build files have been written to: G:/xbmcomeganew/kodi-build.x64
MSBuild version 17.4.1+9a89d02ff for .NET Framework
  Checking Build System
  Performing configure step for 'JsonSchemaBuilder'
CUSTOMBUILD : CMake warning :  [G:\xbmcomeganew\kodi-build.x64\JsonSchemaBuilder.vcxproj]
    Ignoring extra path from command line:

     "G:/xbmcomeganew/project/BuildDependencies/mingwlibs/x64"


CUSTOMBUILD : CMake warning :  [G:\xbmcomeganew\kodi-build.x64\JsonSchemaBuilder.vcxproj]
    Ignoring extra path from command line:

     "G:/xbmcomeganew/project/BuildDependencies/mingwlibs/x64"


  -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.25393.
  -- The C compiler identification is unknown
  -- The CXX compiler identification is unknown
  CMake Error at CMakeLists.txt:2 (project):
    No CMAKE_C_COMPILER could be found.

**Comment by fuzzard** [comment]
None of those errors have anything to do with this change. The error is it can't find a correct compiler. Use a developer command prompt or set appropriate env cars for target

**Comment by MediaBrasil** [comment]
@fuzzard

Thanks for explain, have one simple way to fix it, I never set env cars before,

Uninstall and install cmake work?

**Comment by thexai** [comment]
@MediaBrasil 

Make sure you have vswhere.exe in this path:

`C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe`

if not you may fix editing location here:
https://github.com/xbmc/xbmc/blob/70a7839c0d14e28c63812ff026a4eb0cccd6e191/tools/buildsteps/windows/vswhere.bat#L38

Maybe you have Visual Studio installed in custom location, etc.

**Comment by MediaBrasil** [comment]
@thexai

Thanks, checked and all is correct, default place. and vswhere.exe is in the correct place.
Work fine compiling nexus, no prob at all, created all zero, and all steps work ok.
When I try Omega I have the issues, and the dependencies are all fine. Probably is another issue.
I have Teamviewer, if you have time to check 
ID 808 213 857- Password wgm4q2k7, maybe you find where is the trouble.

Appreciate your time and info about it

**Comment by MediaBrasil** [comment]
All is fine now, I remove visual studio and reinstall all, solving the issue.

**Pull request merged**
