### PR TITLE
Fixing broken AudioDSP Add-ons

### PR DESCRIPTION
**Pull request by AchimTuran**
This PR tries to fix broken AudioDSP Add-ons. Furthermore, it will port the add-ons to all platforms.

For faster jenkins builds I removed all other binary add-on files. This is only a temporary commit.

### CODE REVIEW

**Comment by AchimTuran** [comment]
jenkins build addons please

**Comment by wsnipex** [comment]
why do you delete all other addons?

**Comment by Montellese** [comment]
@wsnipex: Read the PR description ;-)

**Comment by wsnipex** [comment]
ah sorry :)

**Comment by MartijnKaijser** [comment]
Binary addon definitions have moved to seperate repo

**Comment by AchimTuran** [comment]
@MartijnKaijser 
> Binary addon definitions have moved to seperate repo

I have seen this, but please do not close this PR before the AudioDSP add-ons are fixed. I'm still working on it and I will use this PR for testing with jenkins.

**Comment by AchimTuran** [comment]
jenkins build addons please

**Pull request closed without merging**
