### PR TITLE
Add android API PT + FLOAT

### PR DESCRIPTION
**Pull request by koying**
/cc @FernetMenta @fritsch

### CODE REVIEW

**Comment by FernetMenta** [comment]
nice, how does GetDelay work with PT? Does a sink that is operated in raw non-iec mode require protection from underruns? ActiveAESink would still output SampleOfSilence. This may require some adaption too.

**Comment by koying** [comment]
Tricky part is that a raw PT must calculate its own packet duration to have proper delay calculation, as the sample rate basically means nothing anymore. There must be a better way, maybe passing the duration to the sink AddPackets?
Android (at least the shield) does not need "keepalives" (it actually makes delay calculation tricky), but I cannot generalize. Currently, I just ignore them.

**Comment by koying** [comment]
BTW, I noticed that if the sink returns a m_format.m_frames smaller than a full packet size, sync is broken. I couldn't find the root cause.

**Comment by FernetMenta** [comment]
> Tricky part is that a raw PT sink must calculate its own packet duration to have proper delay calculation, as the sample rate basically means nothing anymore. There must be a better way, maybe passing the duration to the sink AddPackets?

format.m_streamInfo.GetDuration() ?

**Comment by FernetMenta** [comment]
> BTW, I noticed that if the sink returns a m_format.m_frames smaller than a full packet size, sync is broken. I couldn't find the root cause.

My first guess is that this is related to the sink's GetDelay method. For raw ActiveAE sets its internal buffers to 61440 and ignores the value that the sink returns.

**Comment by koying** [comment]
> format.m_streamInfo.GetDuration() ?

lol. Didn't thought of that ;)

**Comment by fritsch** [comment]
I told you on IRC :-)
Am 20.12.2015 6:44 nachm. schrieb "Chris Browet" <notifications@github.com>:

**Comment by koying** [comment]
Updated

**Comment by FernetMenta** [comment]
great. looks all good to me.

**Comment by koying** [comment]
Squashed.
@FernetMenta ok with https://github.com/koying/xbmc/commit/6f2b9e8ec3117487af2eee53cc99f64911accac8 ?
Needed to see HD settings in RAW; IEC samplerate is overridden down the line.

**Comment by koying** [comment]
@FernetMenta Adapted: https://github.com/koying/xbmc/commit/7f8b2a7ec1c7084815ad1ee72cf2ffae0151050f

**Comment by koying** [comment]
Let's move on from here.

jenkins build his please

**Comment by koying** [comment]
Let's move on from here.

jenkins build this please

**Comment by MartijnKaijser** [comment]
\0/

**Pull request merged**
