### PR TITLE
[VideoPlayer] Application crash/exit when changing streams with RDS stream present

### PR DESCRIPTION
**Pull request by djp952**
## Description
VideoPlayer will crash by attempting to terminate the process via exit() if a stream/channel change occurs while the current stream/channel has an RDS stream present.

## Motivation and Context
Working with a a Radio PVR that supports RDS the problem was noted trying to change channels.  I used a similar change made to the Teletext stream years ago, where OpenStream() will implicitly call CloseStream(), and then made any necessary adjustments so that wouldn't blow up either, again based on other stream types like Teletext as reference points.

This problem exists in Leia as well, if PR accepted I would like to issue a backport and try to get that into 18.8.

## How Has This Been Tested?
Tested on Windows x64, debug build of 2020.07.22 nightly Matrix build.  No specific issues were encountered.  After the change set was in place, the call to exit() would no longer occur and channel changes worked fine.  RDS data was cleared between channel changes as expected.

## Types of change
- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by DaveTBlake** [comment]
> This problem exists in Leia as well, if PR accepted I would like to issue a backport and try to get that into 18.8.

No backport. Release of 18.8 is imminent and will be the ;last in the Leia point release. We are having some build issues, otherwise 18.8 would have been out last Sunday.

**Review by AlwinEsch — COMMENTED** [review]
Them looks good for me, think to start next days a update of my https://github.com/AlwinEsch/pvr.rtl.radiofm to have working again (with lack of time not continued until now).

There I know also problems by channels switch where Kodi crash or freeze by this class.

**EDIT:** Thought to make for test of this request, as this addon produce always this problems where seems be fixed here :grinning:

**Comment by djp952** [comment]
That's awesome! Your project was the inspiration for what I've been playing with :)  Of course I took things in my usual convoluted and completely over-engineered direction, but somebody pointed that out to me and thought it would be cool to try my hand.  I've even got "Concept based on pvr.rtl.radiofm" right in the README.md! Very off topic comment, I know - sorry, I look forward to maybe comparing some notes in the future, though.

To keep it on-topic I was a little worried about taking out the WaitUntilEmpty() but haven't found any ill-effects to that at all.

**Comment by djp952** [comment]
@DaveTBlake, now that Leia 18.8 has been released and understanding it's the last expected "dot release" for that baseline, is there any real harm with submitting a backport PR?  Given the nature of the defect Leia users will be unable to use a Radio PVR that supports RDS.  Allowing a backport PR to exist post-18.8 would at least give users the option of building their own Kodi instance from source if they are being stopped by this defect.

I would of course wait until this Matrix PR is accepted/merged before taking any such action, and I really don't want to waste my time, but I would also like to give my users a path forward -- even if it's a painful path :)

**Comment by DaveTBlake** [comment]
> is there any real harm with submitting a backport PR

For clarity (when auditing or bug chasing later etc.) we keep Git for previous branches as tidy as we can, so code changes on old branches that are never going to be released will get closed etc. There comes a point in the dev cycle where fixes are only availlable in the development branch, and that point is now.

I understand your wish to offer the fix to the wider community immediately @djp952. It always feels tough when something just misses a release, but there is always just one more thing to be done and so the line has to be drawn somewhere.  There is no reason why you can't make such a patch to Leia available from your Git repo. 

TBH we would also like to encourage those users that are expert enough to be able to buid Kodi, to be using v19 too. The alpha build seems pretty stable (raise an issue report if you hit problems, or even better contribute fixes) so this does not seem such a terrible thing to encourage.

**Comment by phunkyfish** [comment]
Why remove the wait until buffers are empty?

**Comment by djp952** [comment]
Pretty much just to match the changes made to VideoPlayerTeletext.cpp in the past that dealt with a similar issue.  I can change it up a bit to just call CloseStream(false) from OpenStream and put the wait back (and re-test the use case, of course), if you would prefer that be kept?  I'd hate to introduce an unexpected side-effect, even if RDS is pretty rare.  Uncool to break other people's stuff.

**Comment by phunkyfish** [comment]
I was just curious, if the same changes were made to VideoPlayerTeletext then it's probably ok.

**Comment by AlwinEsch** [comment]
How is the state about this? From my side is OK.

**Comment by phunkyfish** [comment]
It looks reasonable to me.

**Comment by AlwinEsch** [comment]
Have done runtime check with my addon https://github.com/AlwinEsch/pvr.rtl.radiofm and done update to Kodi Matrix there.

Has worked good and all crashes where I know about RDS are fixed with this request.

**Review by AlwinEsch — APPROVED** [review]

**Review by phunkyfish — APPROVED** [review]
LGTM

**Pull request merged**
