### PR TITLE
[WIP] [musiclibrary] Custom label format conflicting with sort by

### PR DESCRIPTION
**Pull request by razzeee**
This is more of a placeholder PR, so we can discuss the problem and find a real solution. I will then edit this to reflect whatever we choose as the best way.

This problem applies to almost all of the musiclibrary. Most some of the sortings are not showing the values they are sorting by. There are the ones, that use the user defined 
values:

```
std::string strTrackLeft=CSettings::Get().GetString(CSettings::SETTING_MUSICFILES_LIBRARYTRACKFORMAT);
  if (strTrackLeft.empty())
    strTrackLeft = CSettings::Get().GetString(CSettings::SETTING_MUSICFILES_TRACKFORMAT);
  std::string strTrackRight=CSettings::Get().GetString(CSettings::SETTING_MUSICFILES_LIBRARYTRACKFORMATRIGHT);
  if (strTrackRight.empty())
    strTrackRight = CSettings::Get().GetString(CSettings::SETTING_MUSICFILES_TRACKFORMATRIGHT);

  std::string strAlbumLeft = g_advancedSettings.m_strMusicLibraryAlbumFormat;
  if (strAlbumLeft.empty())
    strAlbumLeft = "%B"; // album
  std::string strAlbumRight = g_advancedSettings.m_strMusicLibraryAlbumFormatRight;
  if (strAlbumRight.empty())
    strAlbumRight = "%A"; // artist
```

```
AddSortMethod(SortByLabel, sortAttribute, 551, LABEL_MASKS(strTrackLeft, strTrackRight));
```

and there are the ones, that use a fixed format, which in some cases have the value that is sorted by in the right column.

```
AddSortMethod(SortByTitle, sortAttribute, 556, LABEL_MASKS("%T - %A", "%D"));  // Title, Artist, Duration| empty, empty
```

This is the album sort that I changed in the commit log. It might be bad, because the user has set `albumFormatRight` and will think it will show up on the right.
Before:
screenshot 2015-08-17 20 38 01

After:
screenshot 2015-08-17 20 37 39

So how do we handle these cases? And shouldn't we commit on either using the user defined format or the fixed?

### CODE REVIEW

**Comment by Razzeee** [comment]
Seems like nobody is interested or has an opinion?

**Comment by ronie** [comment]
your commit looks fine to make and it certainly makes sense to display the year in the right column if you sort by year. (we do the same when sorting songs by year).

apart from that, i'm fine with how all the other sort options currently are.

**Comment by Montellese** [comment]
IMO if we want to use a fixed format it needs to be translatable because RTL languages might require the items to be in reverse order than they will be with this PR.

**Comment by Razzeee** [comment]
Well that should be possible, but is kodi already handling RTL? Are there any settings for it?

**Comment by Montellese** [comment]
It's not handling it properly all over the place but we are trying to at least give translators the possibility to translate everything and provide it in the proper order. Forcing pre-formatted and concatenated strings should not be done anymore in core (there are still a lot of places where we have such stuff from the past though).

**Comment by Razzeee** [comment]
Well, but I think this conflicts with the user being able to set his own filter format then?

**Comment by Razzeee** [comment]
We should probably find a solution for this. It's quite minor but really throwing of the user interface. 
Maybe we can discontinue the configuration in advanced configuration and merge it to one. Then we would have the format the user wants in one row and the value that is beeing sorted by in another row. 

We should also make this configurable in the normal settings then.

**Comment by Razzeee** [comment]
The more I think about it the more I like my idea above.
Just let the user configure one display format type, per level. The only levels that I can think of where this makes sense are Album and Song.

**Pull request closed without merging**
