### PR TITLE
[gui] fix activation of window if top most modal is dialog busy

### PR DESCRIPTION
**Pull request by xhaggi**
In some cases it happens that the busy dialog is already open before the window activation kicks in.
This will results in a refuse of the activation and some pain for different addon devs because they need to hack around that issue.

This is an attempt to overcome the root cause and adds a new condition to the check for open modals.

Related Trac ticket http://trac.kodi.tv/ticket/15960

### CODE REVIEW

**Comment by xhaggi** [comment]
@mkortstiege or @Montellese mind taking a look please

**Comment by xhaggi** [comment]
i've added a RFC commit which drops the static comparison against WINDOW_DIALOG_BUSY in `CGUIWindowManager` and introduces a new modal dialog type to differ between modals. Currently I've added a default type `NORMAL` and a second type `SYSTEM` where dialog busy is a system modal. I've also adjust the method `CGUIWindowManager::HasModalDialog` to accept a list of types to check for and call it in `CGUIWindowManager::ActivateWindow_Internal` only for `NORMAL` modals. This implementation will gives us more flexibility in case we need more types or handling another dialog like the busy dialog.

**Comment by xhaggi** [comment]
jenkins build this please ... i want to check if everything works fine on all platforms

**Comment by xhaggi** [comment]
@Paxxi mind taking a look too

**Comment by Paxxi** [comment]
Not familiar with the issue but it looks like a nice, clean and extensible way to solve it.

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by mkortstiege** [comment]
+1

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by xhaggi** [comment]
I've done a small optimization to the current modality handling. I've replaced the flag `m_bModal` which is currently used to indicate if the dialog is modal or modeless with a new enum based member `m_modalityType`. This enum holds the values `MODELESS`, `MODAL` and `SYSTEM_MODAL`. Now it's a bit easier to configure the modality of a dialog (without setting the flag and type like i did in my first approach).

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
you should be able to skip the assignments in Show_Internal as the fields are already initialized in the constructor. Still looks like a good change.

**Comment by xhaggi** [comment]
depending on the method you call `CGUIDialog::DoModal()` or `CGUIDialog::Show()` the dialog's type is switch between modal and modeless execpt some special dialogs like BusyDialog which overload this.
I don't know why it was done like this, but IMO a dialog is either a modal or modeless, not sometimes modal and sometimes modeless.

**Comment by xhaggi** [comment]
As this needs to be back-ported for 15.x i'll take a look at unifying the `Show()` and `DoModal()` methods later. If no objections i'll push this in and do a back-port PR.

**Pull request merged**
