### PR TITLE
kodi-send: Add option to send a key press event

### PR DESCRIPTION
**Pull request by danielztolnai**
## Description

Add new feature to the kodi-send EventClient to allow sending keyboard or controller button presses.

## Motivation and Context

The kodi-send tool is only capable of sending [actions](https://kodi.wiki/view/Action_IDs) and executing [built-in functions](https://kodi.wiki/view/List_of_built-in_functions) in its current state. This change allows the user to utilize [keyboard controls](https://kodi.wiki/view/keyboard_controls) directly. This is useful when a single command has to behave differently based on the current screen, for example `kodi-send --button="left"` will move left in the menu but will result in a seek step backward during video playback.

## How Has This Been Tested?

I've tested the new functionality only with Kodi version 17.6 using one local and one remote instance.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by wsnipex** [comment]
I'd be nice to allow several button presses in one command, to allow for macros

**Review by wsnipex — APPROVED** [review]
thanks, looks good

**Comment by danielztolnai** [comment]
Thanks. There are two limitations of sending multiple key presses mixed with actions, though.

1. Sending navigation actions and navigation key presses with such a short time between them will cause some of them to be ignored. For example when running `kodi-send --button="right" --action="down"` only the down action will be executed.
2. Also, as there is no time delay between key presses, sending the same key multiple times will not work perfectly. For example `kodi-send --button="up" --button="up"` will result in only one step up in the menu, while `kodi-send --button="up" --button="left"` will work as intended.

These issues could be fixed by using an optional delay after each button and action when specified on the command line. What do you think?

**Comment by wsnipex** [comment]
yes, introducing a short delay in such cases makes sense. Not sure what would be an appropriate delay, maybe 100ms?

**Comment by a1rwulf** [comment]
Have you investigated why up/up doesn't work without delay while up/left works?
I'd be interested in the root cause, as it sounds like a hidden bug to me.
Adding a delay may workaround it, but finding the root cause would be better imho.

Anyway I'm not gonna block anything, just curious.

**Comment by danielztolnai** [comment]
My first thought was that the reason is that the two key presses of the same button are so close to each other in time that they get recognised as one. On the other hand, using the "queued" parameter might have to prevent this. I will look into this on the weekend.

**Comment by a1rwulf** [comment]
From a first glance I think it depends on what we want to mimic.
A full button press/release cycle seems to require two packets, one for the buttondown and one for the buttonup event.
Could be worth a try:
```
packet = PacketBUTTON(code=0, repeat=0, down=1, queue=1, map_name=keymap, button_name=action['content'], amount=0)
packet.send(sock, addr)
packet = PacketBUTTON(code=0, repeat=0, down=0, queue=1, map_name=keymap, button_name=action['content'], amount=0)
packet.send(sock, addr)
```

**Comment by garbear** [comment]
Down and up should use separate packets. Otherwise, gaming is precluded.

**Comment by a1rwulf** [comment]
Ok - thanks much for looking into it.
I think changing mentioned behaviour exceeds the topic of this PR.

**Comment by danielztolnai** [comment]
Yes, definitely. Even if this is not the intended functionality, modifying this would be a breaking change and also out of scope here. I will push the delay-enabled kodi-send instead.

**Pull request merged**
