### PR TITLE
[PVR] New PVR playback setting: 'Delay mark last watched'.

### PR DESCRIPTION
**Pull request by ksooo**
A neat feature requested in the Forum: https://forum.kodi.tv/showthread.php?tid=337272

screenshot001

Runtime-tested on macOS, latest Kodi master.

@Jalle19 do you have some time for a code review?

### CODE REVIEW

**Comment by a1rwulf** [comment]
Typo in commit message

**Comment by MartijnKaijser** [comment]
Sorry but should channels just be following the already existing delay for the watched status that present for movies and episodes.
I hate that we just add another setting.

**Comment by ksooo** [comment]
The existing setting has a completely different semantics. It fires if a video with a known length was watched for x%.

The new setting fires after a fixed amount of time since start of channel payback.

As I have removed several unneeded pvr settings for Leia I think I have some more free to introduce. ;-)

**Comment by ksooo** [comment]
jenkins build this please

**Review by Jalle19 — APPROVED** [review]

**Pull request merged**
