### PR TITLE
Fixes for rating

### PR DESCRIPTION
**Pull request by phate89**
Some fix for rating. 
1) If there was no rating the old code entered in a loop
2) a typo
3) removed a pointless check.
The existing 102 databases should be dropped

### CODE REVIEW

**Comment by anaconda** [comment]
Thanks.

**Comment by MilhouseVH** [comment]
Thanks - problem solved. :)

Does the change to `AddRatings()` mean that any existing MyVideos102 database should now be dropped and re-migrated?

**Comment by phate89** [comment]
Yes all the 102 databases should be dropped..

**Comment by Razzeee** [comment]
jenkins build this please

**Pull request merged**
