### PR TITLE
[docs] fixes for xbmcvfs.Stat

### PR DESCRIPTION
**Pull request by anxdpanic**
## Description

Fix python function documentation for renamed xbmcvfs.Stat().atime()/.ctime()/.mtime() -> xbmcvfs.Stat().st_atime()/.st_ctime()/.st_mtime()

## Motivation and Context

Incorrect documentation for the specified functions

## How Has This Been Tested?

Generated docs, and python test of functions
Python results: https://pastebin.com/hS92yUn7

## Screenshots (if appropriate):
https://i.imgur.com/giBhRHS.png

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [X] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by wsnipex** [comment]
this looks wrong. the functions are still called [a,c,m]time

**Comment by Rechi** [comment]
I thought the same at first but then found the following.
https://github.com/xbmc/xbmc/blob/4398f988e1577495ab6a9ba1e43e6bd2ac65f465/xbmc/interfaces/swig/AddonModuleXbmcvfs.i#L34-L36
https://github.com/xbmc/xbmc/blob/4398f988e1577495ab6a9ba1e43e6bd2ac65f465/xbmc/interfaces/legacy/Stat.h#L171

**Comment by anxdpanic** [comment]
They appear to be renamed as rechi mentioned
I also checked how the deleteFile/delete doc was done for consistency, since it is renamed as well. https://github.com/xbmc/xbmc/blob/eb161cdb7c4c97e9f054192c9ea9e8d00839c305/xbmc/interfaces/legacy/ModuleXbmcvfs.h#L57-L80

**Review by enen92 — CHANGES_REQUESTED** [review]
Please also change function names that are enclosed in `DOXYGEN_SHOULD_USE_THIS`. They are only used by doxygen and help to reduce possible sources of confusion.

atime -> st_atime https://github.com/xbmc/xbmc/pull/15021/files#diff-087f8fe354d1a46a754595975ec75d1eR169

mtime -> st_mtime https://github.com/xbmc/xbmc/pull/15021/files#diff-087f8fe354d1a46a754595975ec75d1eR183

ctime -> st_ctime https://github.com/xbmc/xbmc/pull/15021/files#diff-087f8fe354d1a46a754595975ec75d1eR197

Nice finding and thanks for fixing.

**Comment by anxdpanic** [comment]
should I do this for deleteFile as well?
https://github.com/xbmc/xbmc/blob/eb161cdb7c4c97e9f054192c9ea9e8d00839c305/xbmc/interfaces/legacy/ModuleXbmcvfs.h#L77

**Comment by enen92** [comment]
Yes please

**Comment by anxdpanic** [comment]
The requested changes are made

**Review by enen92 — APPROVED** [review]

**Pull request merged**
