### PR TITLE
DVDAudioCodecFFmpeg: Do not access private AVFrame fields

### PR DESCRIPTION
**Pull request by fritsch**
We access some fields that we should not access. Keep it open I think I can find some more.

### CODE REVIEW

**Comment by jamrial** [comment]
https://github.com/xbmc/xbmc/blob/master/xbmc/guilib/FFmpegImage.cpp#L287

frame->pkt_duration should be av_frame_get_pkt_duration(frame)

**Comment by fritsch** [comment]
Thanks much, added a commit.

**Comment by FernetMenta** [comment]
this is for v18

**Comment by FernetMenta** [comment]
reason: this is api cosmetic that has zero advantage on behavior. on the other hand it introduces a risk of breaking anything. Makes the decision very simple. This won't get considered for v17. Keep in mind that Kodi does not support shared ffmpeg libs hence ABI compatibility is not an issue.

**Comment by fritsch** [comment]
As you wish as you decide. My point on this: Broken API usage is broken and wrong no matter what we support and what we don't support. I will label it v18.

**Comment by fritsch** [comment]
Obsolete (soon).

**Pull request closed without merging**
