### PR TITLE
[ScriptInvocationManager] make ExecuteAsync() thread-safe

### PR DESCRIPTION
**Pull request by phil65**
Lock is left too early.
Was mentioned on Slack some time ago.

### CODE REVIEW

**Review by FrankHeimes — APPROVED** [review]

**Comment by arnova** [comment]
Looks sane to me.

**Comment by MartijnKaijser** [comment]
Jenkins build this please 
Is this something to backport as well?

**Review by fritsch — APPROVED** [review]
If we want to be more popely than the pope. The lock could be taken one line further down and we could use the dtor to unlock it by introducing a scope, but we are not the pope :-)

**Comment by fritsch** [comment]
@MartijnKaijser yes.

**Pull request merged**
