### PR TITLE
Added JumpToLetter builtin

### PR DESCRIPTION
**Pull request by phil65**
This PR adds a new builtin called jumpletterX which would allow skinners to implement a neat alternative to the classic scrollbar. (still needs a little bit of python though to expose a list of all used sortletters to skinners, would be great to get that functionality into core, too)

SCREENSHOT:
screenshot004

i implemented it in the same way as JumpSMS.
jumpletter[0-9] are not part of this PR, first want to know if it gets accepted at all.

### CODE REVIEW

**Comment by da-anda** [comment]
sorry for digging out old PRs, but I was just in the mood to look for unmerged gems. I hope we could bring this feature into Leia, as the idea/request came up again recently

**Comment by Rechi** [comment]
@phil65 this needs a rebase

**Comment by MartijnKaijser** [comment]
I will close this PR. If there's interest please open a new one (with required changes if needed).

**Comment by zag2me** [comment]
@phil65 Any chance of resurrecting this, been waiting for this feature for years in music would be so useful :)

**Pull request closed without merging**
