### PR TITLE
[win32] - fix DirectSound for streams with very low sample rates

### PR DESCRIPTION
**Pull request by FernetMenta**
fix trac http://trac.kodi.tv/ticket/15804

### CODE REVIEW

**Comment by fritsch** [comment]
jenkins build and merge

**Comment by fritsch** [comment]
jenkins build and merge

**Comment by fritsch** [comment]
Ouh man :-) ... i need sleep, sorry for the noise.

**Comment by MartijnKaijser** [comment]
hahaha

**Pull request merged**
