### PR TITLE
[mediamanager] Use meta data provided disc names and add Blu-ray detection.

### PR DESCRIPTION
**Pull request by ace20022**

### CODE REVIEW

**Comment by ace20022** [comment]
@ksooo @Rechi the thumb stuff is not ready yet. Thanks for the review yesterday

**Comment by FernetMenta** [comment]
without having libbluray-dev installed this results in linker error

**Comment by garbear** [comment]
I just encountered the same thing:

```
[100%] Linking CXX executable kodi.bin
/home/workspace/kodi/xbmc/storage/MediaManager.cpp:733: error: undefined reference to 'XFILE::CBlurayDirectory::CBlurayDirectory()'
/home/workspace/kodi/xbmc/storage/MediaManager.cpp:735: error: undefined reference to 'XFILE::CBlurayDirectory::InitializeBluray(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/workspace/kodi/xbmc/storage/MediaManager.cpp:738: error: undefined reference to 'XFILE::CBlurayDirectory::GetBlurayTitle[abi:cxx11]()'
/home/workspace/kodi/xbmc/storage/MediaManager.cpp:739: error: undefined reference to 'XFILE::CBlurayDirectory::GetBlurayID[abi:cxx11]()'
/home/workspace/kodi/xbmc/storage/MediaManager.cpp:739: error: undefined reference to 'XFILE::CBlurayDirectory::~CBlurayDirectory()'
/home/workspace/kodi/xbmc/storage/MediaManager.cpp:733: error: undefined reference to 'XFILE::CBlurayDirectory::~CBlurayDirectory()'
collect2: error: ld returned 1 exit status
CMakeFiles/kodi.dir/build.make:446: recipe for target 'kodi.bin' failed
make[2]: *** [kodi.bin] Error 1
CMakeFiles/Makefile2:507: recipe for target 'CMakeFiles/kodi.dir/all' failed
make[1]: *** [CMakeFiles/kodi.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ace20022** [comment]
Thx, I'll add the forgotten ifdefs tomorrow

**Pull request merged**
