### PR TITLE
[addons] fix addon version.h, do not give nullptr as string

### PR DESCRIPTION
**Pull request by AlwinEsch**
**Fix with very high priority**
---------------------------------

The change on https://github.com/xbmc/xbmc/pull/16591/files#diff-76f1176ce521a817a7f4c9d779760fe1R281
destroy all Kodi's before, if a binary repo addon was created after this request, it will crash
immediately with nullptr to std::string.

Therefore, no older Kodi would work anymore!

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by AlwinEsch** [comment]
@rechi is there a good list to see which addons was compiled after #16591 by Jenkins for the binary repo and to force a rebuild there, after them is in?

**Comment by peak3d** [comment]
@AlwinEsch we only compile 2 binary addons with jenkins, but t.b.h I don't see your point at all.

**Comment by peak3d** [comment]
@AlwinEsch pls. don't push any fixes until this is clarified. Can you please answer my question (original PR) in what situation the "0.0.0" or nullptr code is executed?

**Comment by AlwinEsch** [comment]
The `GetTypeVersion` call return value becomes passed on older Kodi Versions to a `AddonVersion(const std::string& version)` on Kodi. If there NULL comes a exception.

**Review by peak3d — APPROVED** [review]
IMO this is a theoretical fix, because no addontype has been added / removed in the last period.
This means, that we will most likely never hit this special case (null / 0.0.0). I'm still in the opinion that "0.0.0" is an AddonVersion internal default identifier and should not be passed as initialization. The old AddonVersion class already has an "" -> "0.0.0" transformation.

**Comment by AlwinEsch** [comment]
A change in the exchange of data between Kodi and addon in the headers always requires an API version change. Therefore, better leave it as before.

**Pull request merged**
