### PR TITLE
Implement AdvancedSettings substitution regex.

### PR DESCRIPTION
**Pull request by KyleSanderson**
## Description

Pretty simple (and powerful) feature that allows users to specify regular expression matches for requested path substitutions. This allows users to still scan using a "local" filesystem, and serve media files from a remote path.

## Motivation and context

SMB maxes out at 1.5MB/s.
NFS has a multitude of locking issues.
FileCache is stalled out.

I've gone back to what I know and use HTTP to serve media (where I get line speed). Directory scanning is still an absolute disaster on HTTP, so using SMB for this is very helpful. 

## How has this been tested?

```
<advancedsettings version="1.0">
  <cache>
    <memorysize>134217728</memorysize>
    <readfactor>64.0</readfactor>
    <chunksize>1048576</chunksize>
  </cache>
  <samba>
    <statfiles>false</statfiles>  <!-- Set to false to disable smb stat() on files to speed up listings of large directories (over slow links) -->
</samba>
 <pathsubstitution>
  <substitute>
    <from>smb://10.24.96.1/television/</from>
    <to>http://10.24.96.1:69/</to>
    <regex>mkv$|mp4$</regex>
  </substitute>
  <substitute>
    <from>smb://10.24.96.1/films/</from>
    <to>http://10.24.96.1:70/</to>
    <regex>mkv$|mp4$</regex>
  </substitute>
 </pathsubstitution>
</advancedsettings>
```

## What is the effect on users?

An expanded toolchest for adults.

## Screenshots (if appropriate):
image

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by KyleSanderson** [comment]
Jenkins build this please

**Comment by KyleSanderson** [comment]
Jenkins build this please

**Comment by arnova** [comment]
IMHO this is feature is way too "niche" and rather seems like a "strange workaround". Way don't you use webdav instead of http? That should work much better as (streaming) filesystem...

**Comment by KyleSanderson** [comment]
It's 6~ lines of code to add this functionality which can be used to ignore *.db files and similar on relocations. It's very useful to get out of binds, and to enforce correctness. I'm sure there's other uses besides mine and others.

Yes, while there's multiple reports of issues with WebDAV (and it not being included by default with many distributions), it is something I haven't tried since Frodo (and would be heartbroken to go down yet another bad path).

**Comment by KyleSanderson** [comment]
Very disappointing.

**Pull request closed without merging**
