### PR TITLE
[addons] drop info message on zip install

### PR DESCRIPTION
**Pull request by howie-f**
## Description
let's drop this.

Unbenannt

## Motivation and context
https://forum.kodi.tv/showthread.php?tid=370320

## What is the effect on users?
less confusion for users, less gray hair for moderators

## Types of change

- [X] **Improvement** (non-breaking change which improves existing functionality)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document

### CODE REVIEW

**Review by enen92 — APPROVED** [review]
+1, this is annoying as hell when developing/testing stuff on android :)

**Review by ksooo — APPROVED** [review]
LGTM.

**Comment by mkreisl** [comment]
I think this is a stupid idea. The link above points to a thread where the user can't even find his own ass without help.
What is he doing if he doesn't even know that such addons are not automatically updated?
I think it would make much more sense to display this message once and then suppress it.

**Comment by howie-f** [comment]
@mkreisl do not underestimate the ability of people to find their own ass.
there were discussions in the past to show this message only once, twice or even let the user decide to „don‘t show this message again“ (checkbox or something). i‘ll see what i can do

**Comment by zag2me** [comment]
Absolutely +1

Media centers should be easy to use by all, Info popups and warnings suck!

**Comment by mkreisl** [comment]
> there were discussions in the past to show this message only once, twice or even let the user decide to „don‘t show this message again“ (checkbox or something). i‘ll see what i can do

That is already a very good approach :+1:

**Review by KarellenX — APPROVED** [review]
Great. Removes user confusion.

**Pull request merged**
