### PR TITLE
[music] When adding a new music directory, ask the user if he wants t…

### PR DESCRIPTION
**Pull request by razzeee**
…o scan it

This grabs one of the useful parts about https://github.com/xbmc/xbmc/pull/8069 and aligns music code wise a bit more to video.
If this gets in a user, that adds or edits a folder will get ask if he wants to scan it.

This also features some whitespace/readability changes.
See: https://github.com/xbmc/xbmc/pull/8395/files?w=0 for if you want to check what really changed.

Needs to be tested on all platforms

### CODE REVIEW

**Comment by zag2me** [comment]
Any chance of a windows test build?

In theory this fixes the issue I brought up in the Jarvis testing thread about music basically being impossible to import for every new user. I wouldn't want to get involved in any "should it go in" discussion though ;)

**Comment by DaveTBlake** [comment]
@Razzeee would you set off some manual builds so others can easily test this?

**Comment by Razzeee** [comment]
Jenkins is working on it

**Comment by Razzeee** [comment]
image

As someone asked for screenshots

**Comment by DaveTBlake** [comment]
That was me, thanks Razzee.

A dialog like that would be an immediate improvement, but with different strings.  I presume you are reusing something else? "Change Content" and "refresh information" are a little obscure. Could we have different text, mentioning "library", without too much work?

**Comment by Razzeee** [comment]
I just used the strings that are there for that part, when you set content. They don't make much sense, but anyway others are way better at wording, so I figured just get this up now, the guys will deceide on a better wording or better strings to use.
@da-anda @jjd-uk

**Comment by jjd-uk** [comment]
On the wording, I'm ok with the suggestion from @da-anda on slack, that is:

"Do you want to add the files in this source to your library"

Perhaps also window title should be "Add Content" rather than "Change Content", will need to remind myself exactly under what circumstances you get this dialog.

**Comment by Razzeee** [comment]
I don't think content should show up there at all

**Comment by da-anda** [comment]
as for "content" or not - it actually depends I'd say. We could also write "Do you want to add the content of this source to your library?" which would sound even less technical. In that case the "Add content" dialog header would fit just fine. "Add to library" and "Update library" would ofc also work in according contexts.

**Comment by zag2me** [comment]
Is there any reason we can't mention music in the text?

"Do you want to scan these music tags to your library? (this may take a while)"

**Comment by MartijnKaijser** [comment]
Why does it need "music" media should be enough and then the text can be reused.

**Comment by da-anda** [comment]
"music tags" is again a technical detail nobody cares about, isn't it? People buy songs and want them added - they don't care how or where the meta-data comes from. I'm fine with "Do you want to add the music from this source to your library?" as it's ofc most userfriendly. To be more generic and reusable I suggested "media" above, but considering that adding media is currently the hardest part to do for users, I'm absolutely fine with actually naming the media type to be more clear.

**Comment by jjd-uk** [comment]
If we drop the Content for the title of that dialog then "Set content" also needs to be changed plus they must both fit with context menu option so "Edit content" would need to change.

**Comment by jjd-uk** [comment]
Or if we keep Content then from @da-anda last suggestion, instead of:

"Do you want to add the content of this source to your library?" 

it should be

"Do you want to add the content from this source to your library?"

**Comment by Razzeee** [comment]
Not sure if anyone really read my question in slack, but here is an update to the PR.

image

**Comment by Razzeee** [comment]
I'll replace that in with a from now, so ignore the screenshot

**Comment by zag2me** [comment]
Looks good :+1:

**Comment by jjd-uk** [comment]
With the change from "in" to "from", I'd be ok with that wording.

**Comment by da-anda** [comment]
fine with me, thanks.

**Comment by DaveTBlake** [comment]
In Jarvis please :)

**Comment by MartijnKaijser** [comment]
Build triggered and will be on server in some time with file containing fc74762

**Comment by zag2me** [comment]
Tested the build and it does what it should. 

Tested clicking no and music stays in file view.
Tested clicking yes and music starts scanning into the library

So all good from what I can see :+1: 

The only improvement I can think of is a 2nd dialouge asking if the user wishes to scrape online metadata. But I guess this is out of the scope of this PR (and helix).

**Comment by Razzeee** [comment]
@zag you tested windows?

**Comment by DaveTBlake** [comment]
Yes, @zag just said so on IRC.
@MartijnKaijser says you are concerned about a path problem. I didn't think that was this PR. Can you reassure?

**Comment by Razzeee** [comment]
Yes, as I said in the PR comment "Needs to be tested on all OS"

**Comment by MartijnKaijser** [comment]
Tested on Android with smb:// location

**Comment by Razzeee** [comment]
Can somebody test osx, Linux, ios?

**Comment by ronie** [comment]
works fine on linux.

**Pull request merged**
