### PR TITLE
Curl IPv6 dns resolution (fixes #19442 fixes #20779)

### LINKED ISSUE #19442: IPv6 DNS Resolution Broken in Matrix
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi will no longer resolve IPv6 DNS names. This seems apparent when using Samba shares as media sources. Only IPv4 lookup is attempted causing the DNS lookup to fail. This was working perfectly well in Leia, it was broken by: https://github.com/xbmc/xbmc/pull/19040

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

DNS lookups should query for IPv6 and IPv4, so that IPv6-only services are still able to work correctly.

## Actual Behavior

The connection to the Samba share fails due to no IPv6 DNS resolution.

## Possible Fix

- https://github.com/xbmc/xbmc/blob/Matrix/xbmc/network/DNSNameCache.cpp use getaddrinfo() instead.
- Do not do any kind of DNS resolution within Kodi and just let the operating system handle it which makes much more sense and is less maintenance for the developers.

### To Reproduce

1. Connect KODI to an IPv6 enabled network.
2. Setup a Samba share that only has an IPv6 address in DNS (an AAAA record).
3. Attempt to set up the Samba share as a media source.
4. Observe it fail.

### Debuglog

The debuglog can be found here: I do not know how to produce one but since I have identified the pull request and code that are the problems here.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: CoreElec 19 for ODroid N2 with IPv6 ENABLED.
 - Kodi version: 19/Matrix

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #20779: IPv6 broken in Library scanning and web server
### Describe the bug
Here is a clear and concise description of what the problem is:

When in a IPv6 only network, the network scanning fails with the message "Unable to connect to remote server".

In a wireshark capture I can clearly see a dns lookup being made and the DNS replying all IPv6to the domain `api.themoviedb.org` so this shouldn't be happening

Also, might be related, on start I get the message "Web server failed to start" but this should be an easy one. When I have IPv4 enabled on the system but no actual address the webserver starts and answers on IPv6, but if the IPv4 is disabled on the interface it doesn't start and doesn't reply on IPv6

## Expected Behaviour
Here is a clear and concise description of what was expected to happen:
Kodi should work transparently with IPv6 since there is no actual unreachability (because ipv4 is available behind nat64)

## Actual Behaviour
There are multiple connection errors with curl and the web server not working.

## Possible Fix
For the curl issue, it might be disabled in it, or it might have to do with the parser not accepting IPv6 adresses, because other parts of kodi including add-ons can access content over ipv6 correctly.
For the web server, there probably is a check that searches for available IPv4 addresses and only then starts the server, this should be changed to any IP address (v4 or v6)

### To Reproduce
Steps to reproduce the behaviour:

1. Connect to a IPv6 Only network with nat64 available
2. Start Kodi
3. The issues will happen

### Debug log
The debug log can be found here:
[kodi - Copy.log](https://github.com/xbmc/xbmc/files/7801846/kodi.-.Copy.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:
There are no screenshots that can help to this problem.

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows (other OS may have the same issue)
 - [ ] Windows UWP

 - Operating system version/name: Windows 11/10
 - Kodi version: 20.0-ALPHA1 (19.90.101) Git:20211223-4ac445c4a9

### PR DESCRIPTION
**Pull request by wsnipex**
## Description

IPv6 only DNS resolution was broken by https://github.com/xbmc/xbmc/pull/19040

Our DNS cache doesn't handle IPv6 addresses, it always stores and returns the IPv4 address.
This causes all requests through curl to fail on systems without IPv4 stacks.
Fix this by only using our name cache if it already contains an entry, otherwise pass the unresolved hostname to curl and let it handle lookups itself.

see https://github.com/xbmc/xbmc/issues/19442 and https://github.com/xbmc/xbmc/issues/20779 for details

## How has this been tested?

not really, I hope for the reporters of the issue to verify

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by tiagogaspar8** [comment]
This fixed the issue here!

**Review by lrusak — APPROVED** [review]
I'm fine with the change but can you please provide more context about why the change is needed either in the OP or in the commit message (why is `GetCached` needed instead of `Lookup`).

**Comment by wsnipex** [comment]
OP updated with more info

**Comment by tiagogaspar8** [comment]
Just wanted to let you know that it also works in master, thanks a lot for the help! 😄

**Pull request merged**
