### PR TITLE
Fix pil on android (fixes #17881)

### LINKED ISSUE #17881: Python 3.7 is brocken on Android platform
### Describe the bug
Several Matrix compatible addons are throwing Python errors under Android.
They are working under Windows though!

## Expected Behavior

Addons that are working under Windows OS should als work under Android.

## Actual Behavior

Addons are throwing errors right at loading under Android, but not under Windows.

### To Reproduce

1. Install EmbyCon Video Addon for Matrix from here: https://github.com/faush01/plugin.video.embycon/archive/feature/matrix.zip
2. Install Embuary Helper Script for Matrix from here: https://github.com/sualfred/script.embuary.helper/archive/matrix.zip
3. Just wait some seconds to for the addons to be loaded and you get errors.

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/sajijocuxu.kodi

### Your Environment
Used Operating system:

 - [X ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 5 but also on Nvidia Shield with Android 9
 - Kodi version: 19.0-ALPHA1 Git:20200514-f2e83f2947

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by wsnipex**
## Description

Fix PIL on android
Add needed module for cProfile

## Motivation and Context

Python-Imaging was broken since the move to python3

## How Has This Been Tested?

built and quickly tested on android

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by sualfred** [comment]
Tested on Shield and confirm PIL is working again.

**Comment by wsnipex** [comment]
build error unrelated, let's try again
Jenkins build this please

**Comment by lrusak** [comment]
I think it would be better to find a general solution to patch Python to be able to load these libs so we don't have to patch each python module individually. If you want to do this for the time being that's ok but I would rather use patches than using sed commands.

**Comment by wsnipex** [comment]
those py files are generated, I'm not going to add patches against them.
I agree that a more general solution would be nice, but that's a whole can of worms and out of scope for this fix.

**Comment by lrusak** [comment]
> those py files are generated, I'm not going to add patches against them.

Where do they get generated? I don't have them on my Pillow install on my linux workstation.

**Comment by wsnipex** [comment]
because we install directly on most platforms, but build an egg on android

**Pull request merged**
