### PR TITLE
[depends/binaddons] - unify binary addons and add build result tracking

### PR DESCRIPTION
**Pull request by Memphiz**
This is basically the brother of #6673 

It:
- combines the depends wrappers for binary addons into a single one in tools/depends/target/binary-addons
- gets rid of the hardcoded addons lists but instead builds all addons that have a description in project/cmake/addons/addons
- tracks build results of individual addons in project/cmake/addons/{.success,.failure}
- builds all bin addons even if a couple of them failed to build.

Result on jenkins looks like this then:

http://jenkins.kodi.tv/job/BINARY-ADDONS/platform_label=linux64/106/

(showing the successful and failed builds).

@wsnipex and @Montellese for review

### CODE REVIEW

**Comment by Montellese** [comment]
Looks good from my very basic Makefile foo POV. And now I once again hate batch for being such a PITA.

**Comment by wsnipex** [comment]
@Memphiz see top 2 commits https://github.com/wsnipex/xbmc/commits/binaddons_depends
1st one fixes standalone building on linux, 2nd bumps pvr addons to working versions.

**Comment by hudokkow** [comment]
@wsnipex, see https://github.com/xbmc/xbmc/pull/6665
You're missing pvr.filmon bump and new pvr.pctv addon

**Comment by wsnipex** [comment]
then lets just wait for your PR to be merged.

**Comment by wsnipex** [comment]
then lets just wait for your PR to be merged.

**Comment by wsnipex** [comment]
jenkins build addons please

**Comment by Memphiz** [comment]
@wsnipex you didn't answer my one question - this bumping of that api version is not really related to this is it? (just that i know it)

**Comment by Memphiz** [comment]
build result from jenkins was here:

http://jenkins.kodi.tv/view/Addons/job/BINARY-ADDONS/112/

**Pull request merged**
