### PR TITLE
fix library path for child addons

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

@wsnipex @mapfau this should fix the wrong path. it also makes sure the old libs in temp won't get used.

### CODE REVIEW

**Comment by wsnipex** [comment]
thanks

**Comment by fritsch** [comment]
Verified working. 

Offtopic:
Something else (and most likely offtopic) the decrypter directory is still assumed in /usr/share/kodi/addons/inpustream.mpd/ and not in /usr/lib where those should be.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by garbear** [comment]
@fritsch I may have run into this problem. I need the following patch for retroplayer: https://github.com/garbear/xbmc/commit/3fcbf62a7

@FernetMenta can I ask what you're doing that needs child addons?

**Comment by fritsch** [comment]
@garbear thx - your code looks to solve this issue.

**Comment by FernetMenta** [comment]
@garbear https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDInputStreams/DVDFactoryInputStream.cpp#L67

Creating an object by passing the parent to the constructor creates a clone/child

**Comment by mapfau** [comment]
> Offtopic:
>Something else (and most likely offtopic) the decrypter directory is still assumed in >/usr/share/kodi/addons/inpustream.mpd/ and not in /usr/lib where those should be.

I call  if (!xbmc->GetSetting("__addonpath__", path)) to retrieve the decrypter path.
So maybe there is smething not ok when resolving the special: at this implementation??

**Comment by FernetMenta** [comment]
@mapfau unfortunately it's not that simple. During development the addon and libs are in the same folder. But when installed the arch independent files got to a different place then the arch dependent ones.

I can pass both paths to the addon with props an create.

**Comment by mapfau** [comment]
@FernetMenta This would be great! I would use the installation path of the bnary addon + /decrypters then.

**Comment by mapfau** [comment]
OT: the libcurl.dll library wich currently comes precompiled with date from 05.2015 seems to have an bug when reading gzipped, chunked data. Windows users arrive the problem, that regarding the size of the chunks a .mpd file can not be parsed.

I have tried my 7.47 version and there are no errors at all.

What is the correct way to place a wish to update the CURL version at least for windows?

**Pull request merged**
