### PR TITLE
[settings/ios]- ensure that RES_CUSTOM is the default. Fixes the "do …

### LINKED ISSUE #17986: Season paths not always correct in the Kodi database
### Describe the bug
Here is a clear and concise description of what the problem is:

I have several TV shows whose different seasons are not all under the same folder on my NAS due to lack of diskspace at the time of uploading them there. After they have been added to the Kodi database, the different paths appear only in the episode related data, i.e. table 'episode' and the view 'episode_view' so playback works fine. In the season related view 'season_view', the various paths are not reflected but you see the same path being used for all seasons. Probably the one displayed is the one from the view 'tvshow'.

I'm not sure if this causes the problem with syncing data between Ember Media Manager and Kodi, but these cases just don't work because the correct path is not found. EMM knows where the seasons really are located but Kodi doesn't return the correct value or it's not found by using the API to sync.

In the Kodi debuglog, the situation is seen as "skipping due to no change" but the EMM log says that the item was not found in the host database.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The syncing via API should work without issues for such cases. I don't expect it to work with cases where the episodes of one season are in various folders.

## Actual Behavior

Sync fails because the correct path is not found.

## Possible Fix

Make Kodi populate the path correctly when the season is added to the database.

### To Reproduce

1. Create two different main folders for the TV show, put one season to each and scrape the information in EMM.
2. Add the TV show to Kodi database.
3. Enable Kodi interface in EMM and try syncing the TV show.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/fexidabiqi.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

image

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: CoreELEC nightly 20200531
 - Kodi version: 18.7

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by Memphiz**
…you want to keep the screen settings" dialog that hits clean installations - fixes #17986

fix for http://trac.kodi.tv/ticket/17986
verified in iphone ios 11.x

### CODE REVIEW

**Comment by Memphiz** [comment]
@FernetMenta your code your button :) worked like a charme for me ...

**Comment by ksooo** [comment]
I have the same problem on macOS, btw.

**Comment by Memphiz** [comment]
@ksooo if you've got any spare time you could try the same fix there too?

**Comment by FernetMenta** [comment]
On osx the default should be res_desktop.

**Comment by ksooo** [comment]
Tried the following

```diff --git a/system/settings/darwin_osx.xml b/system/settings/darwin_osx.xml
index 5d73f3be53..ab84e36907 100644
--- a/system/settings/darwin_osx.xml
+++ b/system/settings/darwin_osx.xml
@@ -1,6 +1,13 @@
 <?xml version="1.0" encoding="utf-8" ?>
 <settings version="1">
   <section id="system">
+    <category id="display">
+      <group id="1">
+        <setting id="videoscreen.resolution">
+          <default>17</default> <!-- RES_CUSTOM -->
+        </setting>
+      </group>
+    </category>
     <category id="input">
       <group id="3">
         <setting id="input.appleremotealwayson">
```

Tried with both RES_DESKTOP and RES_CUSTOM. Not working. Question box still appears.

After answering 'no' and quitting Kodi I have the following in my guisettings.xml:

```
[kai@Kais-MacBook-Pro ~/Library/Application Support]$ grep -ri videoscreen.resolution ./Kodi
./Kodi/userdata/guisettings.xml:    <setting id="videoscreen.resolution">22</setting>
[kai@Kais-MacBook-Pro ~/Library/Application Support]$ 
```

**Pull request merged**
