### PR TITLE
[droid] remove google-breakpad

### PR DESCRIPTION
**Pull request by MartijnKaijser**
We don't use it so might as well stop building it

### CODE REVIEW

**Comment by MrMC** [comment]
+1, MrMC fork removed it long ago.

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Comment by tamland** [comment]
Last time I checked it worked fine and created stack traces, so what's the replacement?

**Comment by MrMC** [comment]
gdb :) any competent android developer knows how to get gdb running under droid to debug issues.

**Comment by tamland** [comment]
So you'll be providing training for users that is asked for a crashlog?

Breakpad is for crash reporting, and for when things have already happen, not for debugging. So no, gdb is no way a replacement for breakpad. But you're competent android developer so you already knew that ofc :)

**Comment by MrMC** [comment]
I don't ask for crashlogs from Android users, never had, never will :) I might ask for a logcat which will typically point towards the suspect area. If they can't figure out how to get a logcat, then the last log file.

More important is their setup and what they did. If I can't reproduce the issue then I don't understand the real problem and any fix is a blind fix. And any competent developer knows that blind fixes are a last resort that is sure to come back and bite back in the rear later.

**Comment by tamland** [comment]
That's.. really off-topic, and I can't say I'm that interested in the story of your workflow, sorry:\

The premise of this pr was that "We don't use it so might as well stop building it", which is false: #10230

**Comment by MartijnKaijser** [comment]
In all these years it has been in i think it was only used once to get a crashlog from a user. Not sure why you refer to that PR as it was just a bit of code i forgot to remove with this PR. Any time i had an issue or crash koying asked for a logcat.

**Comment by tamland** [comment]
Because the way you said it it sounded like it was just a build thing and the functionality was already gone. I have used it successfully a few times, it's useful, and atm I have no interest in starting to debug on android. I'm sure others find it useful as well, so unless there's a reason...

**Comment by MrMC** [comment]
reason is... nice idea but turns out to be useless in development/production practice. Both previous android maintainers have dropped it in their own forks, nuff said.

**Pull request merged**
