### PR TITLE
Fixed crash on scanning incomplete id3v2 tags

### PR DESCRIPTION
**Pull request by pokowaka**
It appears that it is possible to read id3v2 tags where it->second.isEmpty() is true. In that case a call to it->second.front() returns garbage, and hence can cause a crash.

### CODE REVIEW

**Comment by stefansaraev** [comment]
@mkortstiege @evilhamster 

jenkins build this please

**Comment by fritsch** [comment]
jenkins build this please (all fine)

**Comment by mkortstiege** [comment]
What about the other tag parsers (ape, ogg, mp4..)?

**Comment by stefansaraev** [comment]
build error unerlated to this pr. shall we backport ?

**Comment by evilhamster** [comment]
Haven't tested this patch myself, but it seems to solves a problem that could occur. Preferably the same safety check should be done on the other parses, but that could be handled outside of this pr. I think this should be merged.

**Comment by pokowaka** [comment]
@mkortstiege similar logic should probably be introduced there as well. If you wish I can spend some more time investigating a better solution.

**Comment by mkortstiege** [comment]
@pokowaka, sure! If you could check it would be nice. No objections in merging this crash fix as is.

**Comment by pokowaka** [comment]
I've slightly refactored the scanning code and added a series of tests.

Which exposed a bug in the taglib library ;-)

**Comment by pokowaka** [comment]
Clearly I'm doing something wrong here.

**Comment by pokowaka** [comment]
Let me fix my branch first.

**Comment by Razzeee** [comment]
You can just force push to this again and we'll be able to reopen the PR.

**Comment by Geocacher** [comment]
I seem to be having the same hard crash in the latest version of Kodi Krypton (17.6) when I import music into my library. It is so severe that I have to totally re-install Kodi. Nothing else will allow me to restart Kodi. Is there anything I can do to ensure that the files are correctly tagged before I try the import? I can't get a log file, because the crash is so severe.

**Pull request closed without merging**
