### PR TITLE
[PVR] Track : Fix flickering while switching channels

### PR DESCRIPTION
**Pull request by ksooo**
This is an attempt to fix flickering while switching channels, reported in the forum and in https://trac.kodi.tv/ticket/17557

@MilhouseVH could you please include this PR in your next build? I need some feedback from the issue reporters as I'nm not able to reproduce the problem on my end. Thanks.

### CODE REVIEW

**Comment by Robinjoeh** [comment]
Would be great to have this backported to Krypton as well.

I can test this build and see if it fixes the issue.

**Comment by ksooo** [comment]
The issue is Leia only. 

Whatever you're experiencing on Krypton, it is something different and as this is not a support channel, report your issue in the forum, please.

**Comment by Uukrull** [comment]
I tested this PR on W10 with the DVBViewer PVR and I still get the "flickering" (I'd call it "shaking" up and down of the OSD)

**Comment by ksooo** [comment]
Thanks for testing. Yeah I was afraid that it will not work, tbh. This was just a desperate attempt. 

Not sure whether the root cause is in videoplayer or some add-ons. We only know that problems started after recent video player channel switch rework. @FernetMenta might have some thoughts on this.

**Comment by FernetMenta** [comment]
I think the issue starts here:

```
16:10:51.705 T:140560885741312   DEBUG: DoWork - Saving file state for video item pvr://channels/tv/Alle Kanäle/pvr.dvblink_100.pvr
16:10:51.705 T:140558306649856    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
16:10:51.705 T:140558306649856   DEBUG: Thread FileCache 140558306649856 terminating
16:10:51.707 T:140558298257152   DEBUG: CDVDAudio::Pause - pausing audio stream
16:10:51.827 T:140558336018176   DEBUG: CDVDInputStreamPVRManager::Close - stream closed
16:10:51.827 T:140558336018176  NOTICE: Creating InputStream
16:10:51.827 T:140558336018176   DEBUG: PVRManager - OpenLiveStream - opening live stream on channel 'RTL HD'
16:10:51.828 T:140558336018176   DEBUG: opening live stream for channel 'RTL HD'
16:10:52.236 T:140558336018176   DEBUG: CFileCache::Open - opening <dvblink/timeshift> using cache
16:10:52.237 T:140558336018176   DEBUG: CurlFile::Open(0x7fd688077450) http://192.168.1.104:8101/dvblink/timeshift?client=1
16:10:53.616 T:140561153243200  NOTICE: CVideoPlayer::CloseFile()
16:10:53.616 T:140561153243200  NOTICE: VideoPlayer: waiting for threads to exit
16:10:53.848 T:140558306649856   DEBUG: Thread FileCache start, auto delete: false
16:10:53.859 T:140558336018176   DEBUG: CDVDInputStreamPVRManager - Open - playback has started on filename pvr://channels/tv/Alle Kanäle/pvr.dvblink_102.pvr
16:10:53.859 T:140558336018176   DEBUG: CDVDInputStreamPVRManager::Open - stream opened: pvr://channels/tv/Alle Kanäle/pvr.dvblink_102.pvr
16:10:53.859 T:140558336018176  NOTICE: Creating Demuxer
16:10:53.859 T:140558336018176   ERROR: OpenDemuxStream - Error creating demuxer
```

the stream does not open within 2 seconds and as a result fast switch fails and renderer gets teared down.

**Comment by ksooo** [comment]
Okay, I close this PR as it does not fix the issue.

**Comment by debutanker** [comment]
Thank you anyway for this support!

**Pull request closed without merging**
