### PR TITLE
[VideoPlayer] Load program from stream property without using streaminfo - backport

### PR DESCRIPTION
**Pull request by phunkyfish**
## Description

Backport for https://github.com/xbmc/xbmc/pull/16314 and #16395 

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by asavah** [comment]
This is possibly causing issue with mpegts streams see https://github.com/xbmc/xbmc/pull/16314#issuecomment-508906306

**Comment by hudokkow** [comment]
jenkins build this please

**Comment by phunkyfish** [comment]
Combined @asavah's fix (#16395) into the backport. Should solve the reported issues with original PRs.

**Comment by Rechi** [comment]
@hudokkow please do not use `Squash and merge` as git now lists you as author of the code changes.

**Pull request merged**
