### PR TITLE
Cleanup includes - Part 3

### PR DESCRIPTION
**Pull request by ace20022**

### CODE REVIEW

**Comment by garbear** [comment]
I'm surprised games had so many unused includes. Thanks.

**Comment by MartijnKaijser** [comment]
@ace20022 Anything holding this up?
Jenkins build this please (just to check freebsd again)

**Comment by ace20022** [comment]
@MartijnKaijser now it's osx ;( Besides that it should be ready

**Comment by MartijnKaijser** [comment]
Jenkins build this please

**Comment by MartijnKaijser** [comment]
Let's try again https://jenkins.kodi.tv/view/Automation/job/BuildMulti-PR-Manually/234/

**Comment by MartijnKaijser** [comment]
OSX build fine this time.

**Pull request merged**
