### PR TITLE
[TexturePacker][gif] The Graphic Control Extension is optional.

### PR DESCRIPTION
**Pull request by ace20022**
This fixes, e.g., skin re-touced's country flags.

Remaining tasks
- [x] win32: build release and upload it

The same applies to the core implementation, but that will be replaced by FFmpegImge.

### CODE REVIEW

**Comment by ace20022** [comment]
@MartijnKaijser not sure if this qualifies for a backport? i have not tested the resulting xbt file.

**Comment by ace20022** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
if backport then lets do it in v16.1

**Comment by ace20022** [comment]
Build of binary addons failed.

**Comment by MartijnKaijser** [comment]
Can you make backport PR?

**Comment by ace20022** [comment]
Sure.

**Pull request merged**
