### PR TITLE
Add contextmenu option to remove resume points

### PR DESCRIPTION
**Pull request by razzeee**
## Description

Adds a new contextmenu item for videos which enables users to remove a resume point.
Not 100% sure about the wording, so if anybody has an better idea, let me know.

## Motivation and Context

I basically got a forum PM asking for this inside script.trakt. As you can't remove a resume point without loosing all your watched data. Before this PR you needed to "Mark as unwatched", which gets rid of all view counts and the view date.

## How Has This Been Tested?

Locally on windows 64

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by Razzeee** [comment]
Some things that might be weird:
- This won't remove items from the homescreen listing for movies in process unfortunatly
- If you have the item multiple times in your view, it will only visually update the selected one. For e.g. one movie shows in both in process movies and recently added on your homescreen. If you remove the resume point it will only update the resume point visualisation of the selected one.

**Comment by ksooo** [comment]
What about fixing the stuff not working before merging features that only work half way?

**Comment by Montellese** [comment]
I always click on the video I want to remove the resume point from, choose "Start from beginning" and then immediately stop the video again. That way I can reset the resume point and keep the watched status. But TBH the only time I have to do that is after testing something which requires me to play a video.

**Comment by Razzeee** [comment]
@ksooo 
Not 100% sure what your refering to. If you mean the other merged PR, that's still on my radar, but I figured yesterday that that's probably not a 30min task. Unlike this. Time was rare the last months.

@Montellese 
Correct, that works.
But
a) Emits all Video started and Video stopped events
b) Might not be very self explaining for non-developers?

And yes, I would probably only do that for tests too. The user that contacted me said this "An example would be, you just want to watch that one scene again."

To be clear, no hard feelings if we don't want this in core.

**Comment by ksooo** [comment]
> Not 100% sure what your refering to. If you mean the other merged PR, that's still on my radar, but ...
No, I was referring to this PR here. I wanted to suggest not to merge this PR if we already know about "Some things that might be weird" after merging., but to fix the "weird" things first.

**Comment by Razzeee** [comment]
Yes, I will have another iteration on this. Wasn't expecting it to get merged after 15mins anyway. First wanted to see if anyone will shoot it down first or if I missed something that was already there.

**Comment by ksooo** [comment]
Cool, thanks.

**Comment by Razzeee** [comment]
Still struggling to find an event to refresh the item in all our frontends. It even seems like home screen has that problem in more places, it's just not as obvious. So for e.g. watching something and  aborting in the middle should imidiatly add it to the home screens "in progress movies".

**Comment by tamland** [comment]
@Razzeee You need to use announcer (see how the other methods in CVideoDatabase are done). Then the directory provides will pick up on it. I would just change DeleteResumeBookMark to take a CFileItem and do it there.

**Comment by Razzeee** [comment]
I tried using the annoncer, but I probably haven't had the right event then. Will have a look at `DeleteResumeBookMark`

**Comment by Razzeee** [comment]
Thanks @tamland 

Works like a charm now. Adresses both mentioned problems.

I've tested this with movies, episodes and files outside of the library. All work fine as far as I can tell.

**Comment by Razzeee** [comment]
jenkins build this please

**Comment by Razzeee** [comment]
So jenkins likes this. I would like to get reviews and/or info if we want this :)

**Comment by ksooo** [comment]
Please do not merge. This needs some more love to get this working for PVR recordings.

**Comment by Razzeee** [comment]
@ksooo Thanks for checking

**Comment by ksooo** [comment]
I will try to do the rework needed to get pvr recordings working as well. You can cherry pick this, then.

**Comment by ksooo** [comment]
@Razzeee feel free to cherry-pick: https://github.com/ksooo/xbmc/commit/946ac0520dbbb506ef4568f69b9a0e4c145bac71 Works well with normal videos and pvr recordings now.

**Comment by ksooo** [comment]
@Razzee code is ready to get merged, imo.

Functionwise, I think this is a useful feature. I like it.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by Razzeee** [comment]
👍 

I wanted to runtime test your changes again (build forever yesterday night and I needed to go to bed). But you probably did that and your implementation is way better anyway :)

**Comment by MilhouseVH** [comment]
@Razzee:
This PR seems to have changed since yesterday, with the addition of extra files, one of which can't be found on Linux:

xbmc/video/jobs/VideoLibraryResetResumepointJob.cpp
needs to be renamed:
xbmc/video/jobs/VideoLibraryResetResumePointJob.cpp (Linux is case-sensitive)

Currently it doesn't build.

**Comment by ksooo** [comment]
> xbmc/video/jobs/VideoLibraryResetResumepointJob.cpp needs to be renamed: xbmc/video/jobs/VideoLibraryResetResumePointJob.cpp

 Ooops. My fault. Just a typo. I introduced the new files and @Razzeee cherryicked my commit.

**Comment by ksooo** [comment]
@Razzeee shall I fix my commit and you cherrypick again or do you want to fix it directly on your PR?

**Comment by Razzeee** [comment]
Should be fixed. I also just tested again and it works like a charm.

Will merge this if jenkins is happy :)

**Comment by MilhouseVH** [comment]
Doesn't look fixed to me...
s1

**Comment by ksooo** [comment]
@MilhouseVH try again, I just fixed my commit.

**Comment by MilhouseVH** [comment]
Nothing changed here - are you force pushing?

**Comment by ksooo** [comment]
screen shot 2017-09-06 at 19 16 07

**Comment by MilhouseVH** [comment]
Yes, it needs a capital P, as it is here:
https://github.com/xbmc/xbmc/pull/12708/files#diff-6090027e717ee17261b4d8f2e929008fR7

**Comment by ksooo** [comment]
@MilhouseVH I know what the proböem is and I fixed it, but @Razzeee needs to cherrypick again!!!

**Comment by MilhouseVH** [comment]
Ah ok sorry! :)

**Comment by ksooo** [comment]
https://github.com/ksooo/xbmc/commit/436d323f29df64822463027d4055fb266bb02244

**Comment by MilhouseVH** [comment]
All good now.

**Comment by ksooo** [comment]
Okay, let's bring this to an end. ;-)

**Pull request merged**
