### PR TITLE
[PVR] Bump add-ons to fix debian packaging

### PR DESCRIPTION
**Pull request by hudokkow**

### CODE REVIEW

**Comment by hudokkow** [comment]
jenkins build addons please

**Comment by hudokkow** [comment]
OSX32 and 64 failed downloading deps from mirror.

@MartijnKaijser your button.

**Comment by MartijnKaijser** [comment]
@hudokkow 
Still several PVR are failing on PPA builds after this
https://launchpad.net/~wsnipex/+archive/ubuntu/kodi-git/+packages?field.name_filter=pvr&field.status_filter=published&field.series_filter=for

**Comment by MartijnKaijser** [comment]
Quote:
"many are missing kodi-platform in build-deps or the cmakelists.txt is broken since his last changes"

**Comment by hudokkow** [comment]
For the record: I *do* build before committing. I use cmake and don't use debuild. But that's lesson learned.

Now for the important part.
We either keep jenkins happy or we keep debuild happy. Yesterday jenkins was happy with (all) add-ons - I assume it still is - but today it is very unhappy with changes to make debuild happy. See http://jenkins.kodi.tv/job/BINARY-ADDONS/203/ for the result of https://github.com/hudokkow/xbmc/commits/debianbuild and respective changes on add-ons.

Since I'm no cmake or debuild genius, someone more knowledgeable than me should see what's going on.

BTW, how come jenkins was/is happy building add-ons and debuild isn't? Shouldn't jenkins use the exact same process to build them as if it was launchpad?

**Comment by Memphiz** [comment]
jenkins builds with unified depends i don't know what debuild does - but this is the real shit about binary addons imo. You pointing to a branch where i can click a commit only to see a list of changed revisions. Its cumbersome to actually get to the real changes

**Comment by Memphiz** [comment]
so for making debian happy you remove ${kodiplatform_LIBRARIES} as dependend libs for the addons - right?

**Comment by wsnipex** [comment]
yes, if its not used anymore. Otherwise you need to add kodi-platform to build-depends in debian/control

**Comment by hudokkow** [comment]
OK, I'm probably missing somethingg but if I remove ${kodiplatform_LIBRARIES} half the platforms on jenkins don't like it and complain with unresolved symbols. Debian/debuild builds fine.
Removing ${kodiplatform_LIBRARIES} and libkodiplatform-dev (>= 16.0.0) is the same as above.


Again, what I'm I missing?

**Comment by wsnipex** [comment]
>Otherwise you need to add kodi-platform to build-depends in debian/control
did you try that?

**Pull request merged**
