### PR TITLE
[video][PVR][Estuary] Watched Information Improvements

### LINKED ISSUE #23652: "tv shows in progress" doesn't appear when you stop the first episode
### Describe the bug
Add new TV show to library, start watching the first episode, stop it after some time, go the main menu.

## Expected Behavior
This TV show appears in the "tv shows in progress" section

## Actual Behavior

It doesn't appear there

### To Reproduce

1. Add new TV show to library
2. start watching the first episode
3. stop it after some time
4. go the main menu

### Debuglog

The debuglog can be found here: will try to create if you absolutely think it's necessary in this case

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS 13.4
 - Kodi version: master nightly from 15.08.2023

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
Fixes #23652 - now shows with no completely watched episodes, but with at least one resume bookmark appear in Estuary's "In progress TV shows" widget and the respective video window node.

Furthermore, introduces some UI improvements for TV shows/seasons/movie sets:
1) TV Shows: Show in progress episodes count along with watched episodes and total episodes count in home screen listings and video window listings.
2) Movie sets: Show watched/in progress/total counts in home screen listings and video window listings.
3) Seasons: Show watched/in progress/total counts in home screen listings and video window listings.

Screenshots:
screenshot00004
screenshot00005
screenshot00006
screenshot00008
screenshot00009
screenshot00010
screenshot00012
screenshot00013

I runtime-tested the changes on Android and macOS, latest Kodi version.

@enen92 can you please have a look at the code changes?
@jjd-uk can you check the skin changes, please?

### CODE REVIEW

**Review by enen92 — COMMENTED** [review]
At a first glance the code looks good. Not sure if it will add noticeable delay now that you do some joins on the bookmark table.

Regarding skin changes (without focusing on the code) in some of the views the xx / xx / xx might be misleading as a possible date format. Maybe not a bad idea to use "|" as a separator

**Comment by ksooo** [comment]
> Not sure if it will add noticeable delay now that you do some joins on the bookmark table.

I did not notice any delays, although I'm really very sensible about such things. Tested on NVidia Shield Pro 2029 and MacBook Pro Late 2016.

>  the xx / xx / xx might be misleading as a possible date format. Maybe not a bad idea to use "|" as a separator

 Absolutely no problem to change that (one liner, because I switched to a skin var for this information). @jjd-uk what do you think? Shall I replace the / with | ?

**Comment by ksooo** [comment]
> the xx / xx / xx might be misleading as a possible date format. Maybe not a bad idea to use "|" as a separator

This would look like this. Opinions?

Screenshot 2023-08-24 at 23 16 01

**Comment by CastagnaIT** [comment]
i agree use backslashes ( / ) are more confusing better pipe char

but also imo i find confusing having the new third value in the middle

immagine

i propose two changes for better reading:

the order of informations should be:
(from the left to the right)
1-total episodes partial watched
2-total episodes watched
3-total episodes

the first one (1) partial watched, when 0 the gui should hide the "0" value from gui (if possible),
imo most of time the partial watching is unused at least if you watch tv shows that duration is not long hours
this will also help users to understand why a third number appears

**Comment by jjd-uk** [comment]
Agreed I think using the pipe **|** is better so it's not confused as a date.

> the order of informations should be: (from the left to the right)
>1-total episodes partial watched 
>2-total episodes watched 
>3-total episodes

Agreed. Taking the Star Trek Enterprise example once you've watched 90 of the 97 episodes you might have:

Total episodes partial watched - 1
Total episodes watched - 90
Total episodes - 97

What should be displayed is:

**1 | 90 | 97**

This in my view would be better than than the current PR format of:

**90 | 1 | 97**

**Comment by jjd-uk** [comment]
> the first one (1) partial watched, when 0 the gui should hide the "0" value from gui (if possible), imo most of time the partial watching is unused at least if you watch tv shows that duration is not long hours this will also help users to understand why a third number appears

This I have no strong opinion on. Displaying 0 would seem to be pointless but I can understand it being there for consistency, but I can also see the point of having the 3rd number only appear once you've partially watched something since that might given better understanding of why it's there.

**Comment by ksooo** [comment]
Thanks for the feedback, @CastagnaIT , @jjd-uk . So, I will change

* slash to pipe
* order to partly watched | completely watched | total episodes/movies

> the first one (1) partial watched, when 0 the gui should hide the "0" value from gui 

@CastagnaIT I think we should display the zero, for consistency. Otherwise users may end up with asking why sometimes there are two sometimes three numbers. This is imo more confusing than it helps.

**Comment by ksooo** [comment]
@jjd-uk , @CastagnaIT , @enen92 suggested changes are incorporated - could you please recheck and approve the PR or tell me what else is subject of discussion. Thanks.

**Review by CastagnaIT — APPROVED** [review]
nothing else to say from my part

**Review by enen92 — APPROVED** [review]
LGTM too

**Review by jjd-uk — APPROVED** [review]
Skin changes look to be insignificant, so I will approve, however I haven't had time to check changes in person.

If you're not in a rush I should have time this weekend.

If not getting this off your table will hold up other things, then then no objection from me for merging.

**Comment by reardonia** [comment]
Why does the video database version get upgraded?  You haven't touched the structure or otherwise changed the db.  This seems wrong, it should stay at "121".

**Comment by ksooo** [comment]
> Why does the video database version get upgraded? You haven't touched the structure or otherwise changed the db. This seems wrong, it should stay at "121".

Wrong, I changed some of the database views and this the version needs to be bumped.

**Comment by reardonia** [comment]
> 

So the views are changed, but the schema is not upgraded?  View changes don't require ALTER? Maybe I don't follow, I thought you have to explicitly "upgrade" the db as per earlier version upgrades.

**Comment by howie-f** [comment]
is it correct that my season no. 4 shows `2 | 12 | 12` ?
from my understanding it should be `2 | 10 | 12`

screenshot00000

screenshot00001

**Comment by ksooo** [comment]
> is it correct that my season no. 4 shows 2 | 12 | 12 ?
> from my understanding it should be 2 | 10 | 12

Well, technically play count (where watched is derived from) and resume bookmark (where in progress comes from) are two different things. An episode can be watched (play count >= 1) AND it can have a resume bookmark.

So, for your example, you have watched all the episodes and additionally you have resume bookmarks set for two of the episodes (most probably because you partially watched them after you had completely watched them).

**Comment by howie-f** [comment]
> (most probably because you partially watched them after you had completely watched them).

right that‘s the reason. hm, ok 🙂

**Comment by chewitt** [comment]
This change just showed up in my nightlies. I can generate a revert patch for my own builds, but could this be made a configurable setting? .. I find it unintuitive to see the partially watched count and prefer the previous behaviour.

**Comment by emveepee** [comment]
For collectors who understand this it can make sense, for many PVR users who record, watch and delete it does like quite binary.

image

**Comment by ksooo** [comment]
Thanks for the feedback, guys.

I'm not in the mood for lengthy discussions. I will partly revert this change. Those numbers will go away shortly. 

Personal note: I used Kodi with this change active for quite a while and found the additional information very handy and informative. But if people feel they are not intuitive (do not even understand what those numbers are for), so be it. No hard feelings.

**Comment by emveepee** [comment]
> Personal note: I used Kodi with this change active for quite a while and found the additional information very handy and informative. But if people feel the numbers are not intuitive (do not even understand what they are for), so be it. No hard feelings.

My most used recent innovation in Kodi has been the "Continue watching" for PVR and the one downside has been when I had more than one partially watched episode.  Perhaps rather then the counts, add a different icon when there are multiple partial watches.

**Comment by ksooo** [comment]
I don’t think I will do that. People will give feedback they need a manual to understand what this icon is used for. ;-)

**Pull request merged**
