### PR TITLE
Jarvis Fix AudioLibrary.GetSongs missing songs when using limits

### PR DESCRIPTION
**Pull request by DaveTBlake**
Backport of #8993 so that AudioLibrary.GetSongs returns the correct number of songs when limits applied, and allows for songs without artists.

Fixes regression introduced by #8306

### CODE REVIEW

**Comment by DaveTBlake** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
sorry - i have aborted your build on jenkins - i need to update the rbpi toolchain once jenkins isn't busy anymore - as i have a limited time frame left today for doing so - i need to keep jenkins clean for today ... please trigger a build again later (in 4 hours or so should be save).

**Comment by Memphiz** [comment]
update done - retrigger jenkins build this please

**Comment by DaveTBlake** [comment]
The Krypton version tested fine, so I can hit merge?

**Pull request merged**
