### PR TITLE
remove internal NFS support

### PR DESCRIPTION
**Pull request by notspiff**
moved to an add-on

replaces https://github.com/xbmc/xbmc/pull/12837

### CODE REVIEW

**Comment by lrusak** [comment]
:+1:

**Comment by candrews** [comment]
Can we bring this back? It would be nice to get into v19.

**Comment by phunkyfish** [comment]
@notspiff do you want to progress this, close it or put it on the backburner?

**Comment by fuzzard** [comment]
Spiff can probably verify this, but I believe pulling NFS out into an add-on was canned due to the use case of storing settings on an NFS share. Issues with plugin not being available due to start order.
He has not maintained VFS.nfs or VFS.smb due to this

**Comment by phunkyfish** [comment]
So this feel like it should go on the backburner for a later date.

**Comment by phunkyfish** [comment]
Going to close this, can be reopened at a later date if required.

**Pull request closed without merging**
