### PR TITLE
[PVR] API 3.0.0 Implementation of "Add maxRecordings to API"

### PR DESCRIPTION
**Pull request by ryangribble**
This is the implementation of one of the API 3.0.0 features from #7626

Add MaxRecordings field to PVRTimer - an (optional) field to limit a supported backend's number of recordings created for a timer.  This field appears directly below the (optional) Lifetime list 

The first 2 commits are the API bump/fields from #7626 and the 3rd commit is the actual PVR Core implementation. This will likely be pulled together by @metaron-uk with whatever other API 3.0.0 changes are "good to go" into a new PR

**PVR Client Changes Requried**
None, unless they wish to use the new field on their TimerTypes

**Context**
This PR relies on the changes in PR #7626 which groups several API changes forming API 3.0.0.
- This PR should not be merged unless PR #7626 has also been merged.
- The necessary supporting API change is contained in commit [[PVR] Add maxRecordings to API](https://github.com/metaron-uk/xbmc/commit/ffdd6dfc48428bd6557cb29c3d665c3aa5a9ab8b). If this change is withdrawn from PR #7626 this PR will be closed.

**Comments**
Please make comments regarding the MaxRecordings change itself here.
For comments regarding any of the other 3.0.0 API changes, please use #7626

@metaron-uk @ksooo @xhaggi @Jalle19 @janbar

### CODE REVIEW

**Comment by ksooo** [comment]
Regarding the implementation. All my previous comments are now addressed. Thanks. Looking good.

Address the API documentation issue I mentioned and I'm fine with this.

**Comment by ksooo** [comment]
And could we please improve the API documentation for lifetime the same way I mentioned for max recordings?

**Comment by ryangribble** [comment]
OK ive updated the API comment for MaxRecording 

I also did LifeTime on a new commit on this PR (@metaron-uk will ultimately re-assemble the PR's anyway so he can move the Lifetime comment to an appropriate PR/commit when the time comes)

**Comment by metaron-uk** [comment]
Works for me - thanks @ryangribble.

**Comment by ksooo** [comment]
-1

Documentation of both lifetime and max recordings do not work for me at all, for the reasons I explained here https://github.com/ryangribble/xbmc/commit/ef1a55c9ec908cdd1eaca06a77c7111a7619d51f

**Comment by ryangribble** [comment]
Moved to #7626

**Pull request closed without merging**
