### PR TITLE
#/$ mismatch in Android build docs

### PR DESCRIPTION
**Pull request by Alcaro**
The terminal commands in this file are prefixed with $, not #. Telling what to do with #-prefixed lines won't help if there are none.

### CODE REVIEW

**Comment by phil65** [comment]
Indeed. Thanks!

**Comment by Razzeee** [comment]
Can you please change the commit message to something less cryptic? I mean I understand it, with knowing what's in the commit. But it should explain what is in the commit without the need to open the code.

**Comment by Alcaro** [comment]
Like that? Yeah, I should've used a slightly more alphanumeric commit message.

**Comment by MartijnKaijser** [comment]
thank you

**Pull request merged**
