### PR TITLE
[fix/cleanup] Fix some cppcheck issues.

### PR DESCRIPTION
**Pull request by ace20022**

### CODE REVIEW

**Comment by ace20022** [comment]
@koying fyi https://github.com/ace20022/xbmc/commit/c289c36625e2c01008d208bdb920e9b0a52372a6

The smbfile syntax error is strange, when is that path compiled in?

**Comment by koying** [comment]
Re AML, good catch :) @Stane1983: I assume it's not on purpose?

Re SMB, DEPRECATED_SMBC_INTERFACE is probably always defined in samba itself, or I don't see how that could build... @mrmc might be able to shed more light

**Comment by MrMC** [comment]
mistake on my end, there's another one strdup("guest")); -> strdup("guest");

DEPRECATED_SMBC_INTERFACE is present via samba.

Kodi uses the DEPRECATED_SMBC_INTERFACE,  it means the old 3.x API not the new 4.x API.
Just a warning, if you use the GPLv2 version, then the #if branch is taken. As both flavors are selectable in depends. Good catch.

**Comment by ace20022** [comment]
@koying @MrMC thanks for the review

I'll merge it later today if there are no objections

jenkins build this please

**Pull request merged**
