### PR TITLE
[pvr] Sort included files alphabetical

### PR DESCRIPTION
**Pull request by AlwinEsch**
Same as from EPG previous and not a special request and was present in #6877, now separated to here.

It sort only the headers alphabetical in following flow.

```
System global headers a-z
Kodi global headers a-z
./pvr folder headers a-z
Own folder headers a-z
```

If OK for you then I merge in.

### CODE REVIEW

**Comment by ksooo** [comment]
Eeek! Introduces lots of merge conflicts with #7079.  I would be happy if this one would get merged after #7079. Is there anything that speaks against this approach?

**Comment by ksooo** [comment]
Removed milestone just for now, until we have agreement on this point.

**Comment by AlwinEsch** [comment]
Hello @ksooo, if it comes not to Isengard then is no problem for me to do behind your one.

**Comment by MartijnKaijser** [comment]
let's put it behind the #7079

**Comment by ksooo** [comment]
Cool. Thanks guys.

**Comment by MartijnKaijser** [comment]
needs a rebase

**Comment by AlwinEsch** [comment]
Request is updated, OK for the others to merge? Any other bigger requests which conflicts with them?

**Comment by ksooo** [comment]
Fine with me.

**Comment by AlwinEsch** [comment]
Thanks.

jenkins build this please.

**Pull request merged**
