### PR TITLE
speed up plugin update

### PR DESCRIPTION
**Pull request by burlizzi**
## Description

optimized a little (factor of 10) detection of update need for plugins

## Motivation and Context

every time the plugin directory needs to be updated (e.g. after video plugin navigation) the directory takes up to 10 seconds to find out  just the availability of new updates in the addon database on my RPi 3

## How Has This Been Tested?

on RPi3, (Libreelec 9.0.2) with enough addons installed (70 in my case) navigate into any Video plugin directory (Youtube) then exit and move up to movies, it will freeze the UI for about 10 sec,

2019-05-18 11:40:30.160 T:1454371696   DEBUG: CAddonMgr::GetAvailableUpdates took 10224 ms

 with the change it is reduced to 1 sec

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by burlizzi** [comment]
I don't understand why the jenkins build failed.

**Comment by Rechi** [comment]
https://jenkins.kodi.tv/job/BuildMulti-PR/12186/console
> ERROR: This PR contains 2 merge commit(s)

**Comment by burlizzi** [comment]
> https://jenkins.kodi.tv/job/BuildMulti-PR/12186/console
> 
> > ERROR: This PR contains 2 merge commit(s)

now I feel stupid... :)

**Comment by burlizzi** [comment]
pull request redone properly

**Pull request closed without merging**
