### PR TITLE
AudioDSP fixes

### PR DESCRIPTION
**Pull request by AchimTuran**
@FernetMenta 
This PR includes the changes from https://github.com/xbmc/xbmc/pull/9855.
- enabled AudioDSP keeps ActiveAE buffering and buffering, because of a wrong timestamp
- add missing channel handling inside AudioDSP
- deny ActiveAE stream creation with enums out of range (inspired by #8460)
  And the fixes for VS2015.
  double clicking the VS solution file opens VS2013, which is wrong
  add missing dependencies in VS to compile add-on callback libraries before Kodi executable

### CODE REVIEW

**Comment by AchimTuran** [comment]
jenkins build this please

**Comment by AchimTuran** [comment]
jenkins build this please

**Comment by AchimTuran** [comment]
@FernetMenta, @fritsch or @AlwinEsch 
This PR is from my side finished. Hopefully jenkins is also happy with my changes.

**Comment by FernetMenta** [comment]
+1
@AlwinEsch your button

**Comment by FernetMenta** [comment]
not sure if bbe8cba517dc23269f1cd6f500856c61602e89db should be part of this pr
btw: Windows build failed

**Comment by AlwinEsch** [comment]
About the windows build, has checked the UUID and was from my "kodiAddonDevKit-SharedLib-API3.vcxproj" but nowhere in Project files defined anymore, a little bit crazy. Maybe somewhere in Jenkins a bad temporary file?

**Comment by AchimTuran** [comment]
@FernetMenta 
> not sure if bbe8cba should be part of this pr
I could extract this commit and create a new PR if you want.

**Comment by FernetMenta** [comment]
@AchimTuran I am not a Windows dev. This caught my attention because the Windows build failed.

**Comment by AchimTuran** [comment]
jenkins build this please

**Comment by AchimTuran** [comment]
Currently I don't know why the Windows build failed. But I like to merge the changes for AE. So far the VS2015 changes are optional.

**Pull request merged**
