### PR TITLE
[infomanager] add ListItem.IsCollection

### PR DESCRIPTION
**Pull request by mkortstiege**
Adds boolean info label `ListItem.IsCollection`.

### CODE REVIEW

**Comment by uNiversaI** [comment]
@mkortstiege @ronie @da-anda 

Lacking experience in skinning limits me, based on this PR above, I hacked around to tried to implement this into confluence.

See https://github.com/uNiversaI/kodi/commit/0a02a47f7d42c1d33d51193e37fc4cc608899eb1

Literally just copied the 3D flag implementation. I think.

**Before**
screenshot034

**After**
screenshot035

##### There are a few problems with this:

1) When you focus on the collection in list view, the flag disappears ***Battlestar Galactica Collection*** example

2) The flag is only visible in ***Media Info View 2*** I probably missed something somewhere if not the **3D** flag will have same issues.

3) Position is copied from 3D lfag implementation so it will overlap with 3D in some conditions.

For these 3 reason I dint PR this half hack as clearly my attempt is flawed but shows what is possible with the correct skinning skills. Would be nice to get it in and take listview a little closer when moviesets are listed.

**Comment by da-anda** [comment]
I don't think we need the collection icon along with the stream details because a collection usually doesn't have any stream details and would be a lonely icon just like in your BattleStar screenshot. Adding the icon to the list is nice though.

**Comment by uNiversaI** [comment]
Discussion on my attempt at http://forum.kodi.tv/showthread.php?tid=223713 as its not ontopi and it is github after all.

**Comment by phil65** [comment]
added by removing code ;)
https://github.com/xbmc/xbmc/pull/6900

**Comment by mkortstiege** [comment]
Included in #6900. Closing.

**Pull request closed without merging**
