### PR TITLE
[addons] cleanup blacklisting

### PR DESCRIPTION
**Pull request by tamland**
Some code improvements and fixes to various oddities after the rollback feature was changed in #8167

### CODE REVIEW

**Comment by stefansaraev** [comment]
jenkins build this please

**Comment by tamland** [comment]
@Montellese @Razzeee Can you review? Very dangerous database changes here.

**Comment by Montellese** [comment]
Spotted a few minors but nothing bad. I don't really have any overview over the general functionality here so I can only really review the code but not the overall logic.

**Comment by tamland** [comment]
Thanks guys. Hopefully I caught everything. A few things were intentional. jenkins build this please.

**Pull request merged**
