### PR TITLE
[python] demote pythons stdout to loglevel debug

### PR DESCRIPTION
**Pull request by wsnipex**
reduces useless log spam

### CODE REVIEW

**Comment by mkortstiege** [comment]
+1

**Comment by tamland** [comment]
This *will* change everything relying on print, not just useless log spam.

**Comment by wsnipex** [comment]
indeed, thats fully intentional. Everything that does not use proper logging is not wanted in NOTICE.

**Comment by MartijnKaijser** [comment]
If an addon does LOGNOTICE and it will override this I think I'm ok

**Comment by MartijnKaijser** [comment]
https://github.com/xbmc/xbmc/pull/8319

**Pull request merged**
