### PR TITLE
[Android][OMX] Clean std

### PR DESCRIPTION
**Pull request by hudokkow**
namespace std cleanup on Android
Already build tested in http://jenkins.kodi.tv/job/Android-ARM/6364/ and http://jenkins.kodi.tv/job/Android-X86/6014/
ping @koying

### CODE REVIEW

**Comment by koying** [comment]
+1 from me. Thanks.
omxplayer is @popcornmix

**Comment by popcornmix** [comment]
No objections to OMX changes, but there seem to be some missing.
There are four calls to "min" that are missing the std:: now in OMXImage.cpp

**Comment by MartijnKaijser** [comment]
@hudokkow any chance of fixing the remarks?

**Comment by hudokkow** [comment]
Already in party mode but done!
jenkins build this please

**Pull request merged**
