### PR TITLE
[swig/python] improve performance of generated typemaps

### PR DESCRIPTION
**Pull request by Montellese**
## Description
This PR improves the performance of Python typemaps generated by the code generator by using C++ `move` semantic. Furthermore I removed a duplicate `PyLong_Check()` which was introduced in the Python 3 migration.

## Motivation and Context
I was investigating the performance of creating and passing `ListItem` instances from a Python add-on to Kodi and realized that `ListItem.setInfo()` and `ListItem.setCast()` made up 90% of the time it took to put together a new `ListItem`. By improving the typemaps using `std::move()`, `std::map::emplace` and `std::vector::reserve()` I saw a performance improvement of ~20-25% for `ListItem.setInfo()` and `ListItem.setCast()`. This might be useful for other add-ons as well but I haven't really tested or profiled it on any other add-ons creating `ListItem` instances.

Even greater performance improvements could be achieved by replacing `ListItem.setCast()` which expects a python `dict` with an implementation which expects a proper object with specific members. But that would also require add-on developers to adjust their code while the changes above are purely Kodi internal.

## How Has This Been Tested?
Manually as part of my media import work.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Review by garbear — APPROVED** [review]
Can't speak to the `[interfaces/legacy]` commit but the first two look good.

**Comment by Montellese** [comment]
> Can't speak to the `[interfaces/legacy]` commit but the first two look good.

I have no idea why that condition was there in the first place. If `item->HasVideoInfoTag()` is false then the subsequent call to `item->GetVideoInfoTag()` will create a new `CVideoInfoTag` instance which sets `CVideoInfoTag::m_playcount` to `-1`, see https://github.com/xbmc/xbmc/blob/e99b7ddc3681e35022e2d1510f373342d34d5e79/xbmc/video/VideoInfoTag.cpp#L82

That's identical to calling `CVideoInfoTag::ResetPlayCount()`, see https://github.com/xbmc/xbmc/blob/e99b7ddc3681e35022e2d1510f373342d34d5e79/xbmc/video/VideoInfoTag.cpp#L1730-L1733

So that extra call is unnecessary.

**Comment by Montellese** [comment]
I got feedback from another add-on / plugin developer that these commits improve the performance of creating and filling `ListItem`s by ~16%.

**Comment by a1rwulf** [comment]
LGTM

**Comment by garbear** [comment]
might be considered a fix. game library listing can be dreadfully slow on my pi

**Pull request merged**
