### PR TITLE
fixes for ff/rw

### PR DESCRIPTION
**Pull request by FernetMenta**
makes ff and rw smoother. does not fix frozen picture on rw when dxva is active

### CODE REVIEW

**Comment by uNiversaI** [comment]
I'll test this and report if its helpful

I also have a frozen picture on RW (audio starts to play and picture freezes) but Im on Linux with VDPAU -> similar as http://trac.kodi.tv/ticket/15978 but for RW

**Comment by uNiversaI** [comment]
OK with this patch applied it is smoother on FF and better on RW comparing to before - up to 16x either direction. I doubt my system can handle 32X any smoother but 32X is a lot better on RW here than on 32X FF smoothness wise. odd.

I cant really tell x4 x8 x16 apart though (looking at the seconds elapsed speed) and you still get the occasional progress goes back for a second while FF and opposite for RW.

Bonus: Fixed the picture freeze (Linux+vdpau) thing for RW when pressed play it immediately played with picture and audio in sync.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by popcornmix** [comment]
Yes, I testing this on Pi2, and rewind was good at all speeds, but FF produced fewer updated pictures at higher speeds. At x32 I would get only occasional updated pictures (e.g. one every 30 seconds).
If I press play after a number of seconds of no picture updates, the position would jump back to when the last picture was displayed. I'll see if I can get a debug log.

**Comment by FernetMenta** [comment]
@popcornmix can you try the updated pr?

**Comment by popcornmix** [comment]
Yes, behaves much better with the new commit.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by uNiversaI** [comment]
Progress bar and time in seconds skips back 1 second while FF and continues increasing and when RW its skips forward one second and continues decreasing, this continues happening while you are using these functions.

Else its working better now in FF vs RW at all speeds.

**Comment by FernetMenta** [comment]
> Progress bar and time in seconds starts increasing then suddenly skips back 1 second while FF

that's work for another day. I see what's going wrong but not trivial to fix with the current code.

**Comment by afedchin** [comment]
rewind still broken on windows and doesn't matter dxva is enabled or not. rewind looks like a slideshow where slide is changed every 5 or more seconds.

**Comment by FernetMenta** [comment]
rewind is a slideshow but it should change more often. assume we go rw 2x. means the clock counts back with double speed. since a decoder can't decode in reverse direction we need to seek back. now some material is really nasty because of very rare recovery points. demuxer might set us back for more than 7 seconds. now while the clock still goes reverse we decode forward. we don't want the first pic coming out of decoder but some other closer to the one on screen. Currently I have hardcoded a value of 1.5 sec * abs(speed) close to the frame on screen. A slow system may need more than 1.5 sec to decode to that point. 
input streams like blurays which implement IDisplayTime still suffer from wrong timestamps. it takes the timestamp of the file pointer of the input stream which is the the same as for the packet just got from demuxer.

**Comment by uNiversaI** [comment]
That explains a great deal :)

**Comment by afedchin** [comment]
@FernetMenta thank you for detailed explanation. I just wanna point your attention on fact that enabling/disabling dxva doesn't matter. 
sorry for noise

**Pull request merged**
