### PR TITLE
[pvr] Bump pvr.hts to version 2.1.7

### PR DESCRIPTION
**Pull request by ksooo**

### CODE REVIEW

**Comment by ksooo** [comment]
@xhaggi @jalle19 @opdenkamp okay?

**Comment by xhaggi** [comment]
jenkins build addons

**Comment by xhaggi** [comment]
jenkins build addons please

**Comment by Jalle19** [comment]
Should probably wait until the merge window opens, that's what I had in mind for the dvbviewer sync.

**Comment by xhaggi** [comment]
sure we do ;)

**Comment by ksooo** [comment]
sure

**Comment by MartijnKaijser** [comment]
why would you wait? It's an add-on which in future you would bump at any moment

**Comment by Jalle19** [comment]
@MartijnKaijser okay, I wasn't sure what the policy was. @ksooo in that case, merge at will (as long as it builds).

**Comment by ksooo** [comment]
jenkins error seems unrelated. merging right now.

**Pull request merged**
