### PR TITLE
Unify music library and files view

### PR DESCRIPTION
**Pull request by Montellese**
This is @notspiff's take at unifying the music library and files view like we have been using it for the video library for quite a while now.

When reviewing please keep in mind that over 90% of the changes consist of code being moved around between classes without applying any cosmetic fixes to them. So please hold off on the cosmetic comments ;-)

I'm not really much of a music library user so this is not well tested from my side. I'll trigger test builds and post the links to them here for people to be able to test this.

**Test builds**
- win32: http://mirrors.xbmc.org/test-builds/win32/KodiSetup-20150910-9b66e67-unify_music.exe
- android x86: http://mirrors.xbmc.org/test-builds/android/x86/kodi-20150910-9b66e67-unify_music-x86.apk
- android arm: http://mirrors.xbmc.org/test-builds/android/arm/kodi-20150910-9b66e67-unify_music-armeabi-v7a.apk
- OSX-64: http://mirrors.xbmc.org/test-builds/osx/x86_64/kodi-20150910-9b66e67-unify_music-x86_64.dmg
- iOS: http://mirrors.xbmc.org/test-builds/darwin/ios/kodi-20150910-9b66e67-unify_music-ios.deb

### CODE REVIEW

**Comment by zag2me** [comment]
Just tested it on windows and when adding a folder for the first time the view doesnt update until I exit out and go back into the music section.

**Comment by Montellese** [comment]
@zag2me: Thanks for testing and for the report. The issue (and some other oddities with an empty database) should be fixed with the latest commit.

**Comment by mkortstiege** [comment]
Thanks for handling this!

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
so far no real problems found. I'd say merge and get it run tested

**Comment by mkortstiege** [comment]
> so far no real problems found. I'd say merge and get it run tested

+1

**Comment by Forage** [comment]
I don't know if it's related to this change, but when taking these changes for a spin I found one issue:

When you go to the album list, call the context menu on an album and select "Album information" you'll end up with an endless loop when the album can not be found.
It will present you with the album title dialog to change the name, followed by the artist name dialog to change the name, followed by the album title dialog, etc. Trying to quickly press the cancel button in between will just give you the same dialog again. No button on the remote (all I have) allows you to break the cycle (return, exit, colour for different Kodi section, etc.). The only way is to clear the name of the artist completely. This finally gives you the "Album not found" error/notification.

**Comment by zag2me** [comment]
Thats an existing bug thats been around a long time ;)

You need to clear the search field to exit. Its a bug indeed.

**Comment by Razzeee** [comment]
Totally, if I can get it reconstructed. Your musicdb and logfile might help @Forage

**Comment by zag2me** [comment]
Taken it to the forums so not to bug people here http://forum.kodi.tv/showthread.php?tid=238853

**Comment by DaveTBlake** [comment]
@Montellese, @Razzeee, @mkortstiege would it be possible to undo this change?

It results in a loss in functionality from the music file view which would seem to be a mistake, or at least deserves further examination than this PR received. Tag data gets scanned from music files but is no longer displayed in file view. Hard to see that loss of functionality is an improvement. See http://forum.kodi.tv/showthread.php?tid=235259&page=12 and on were users discuss it. 

@evilhamster  has shown that this change was the cause. I have looked at fixing this by changes to GUIViewStateWindowMusicNav, but so far can not restore the full functionality that way. Should I raise a PR for my work so far?

**Comment by phil65** [comment]
From a skinner's perspective and from a UX perspective this change is great, so thx again to notspiff for this. If this causes trouble then it should get fixed and not reverted.

**Comment by Montellese** [comment]
I agree with @phil65. This change makes a lot of things easier and there have been several other improvements on top of this change so undoing it would be a real mess. IMO we need to figure out what isn't working anymore and fix those things.

**Comment by jjd-uk** [comment]
@notspiff Can you provide any pointers to DaveTBlake  why the info from tags is not used any more in the music files view after this PR and how it might be best to fix?

See this post for screenshots of the problem http://forum.kodi.tv/showthread.php?tid=235259&pid=2129282#pid2129282

**Comment by notspiff** [comment]
When I find the time I will fix it. It is likely related to the background
info loaders, old code was really messy and i guess something got lost
there in the refactor.
11. okt. 2015 10:54 skrev "jjd-uk" <notifications@github.com>:

**Comment by jjd-uk** [comment]
Thanks

**Comment by DaveTBlake** [comment]
How busy are you @notspiff ? Having started looking at it I am interested in how to fix it and becoming more familiar with the display side of Kodi. 

The tag data is getting loaded in the background OK, but just not displayed.
We can get the artist name / title display back by adding SortByArtist appropriately in creator of GUIViewStateWindowMusicNav. The criteria needed a clean-up, and we could usefully add some other values available from the tag data. But I am not sure where the visible __view types__ are determined. Now we only have List, Big list and Thumbnail, and can't show all the tag data we have. How to get Media Info etc. added to that?

**Comment by notspiff** [comment]
More than i like. If the tags are filled that is a missing content type on
container issue. Need to set album/songs content type appropriately in
::GetDirectory ()
11. okt. 2015 11:31 skrev "DaveTBlake" <notifications@github.com>:

**Pull request merged**
