### PR TITLE
[curl] Handle return code 501 Not Implemented the same as 405 Method Not Allowed 

### PR DESCRIPTION
**Pull request by ampaze**
## Description
The existing fallback for servers not supporting `HEAD` requests is also used when the server responds with return code 501. Previously only return code 405 was checked.

## Motivation and context
Some servers respond with 501 and not 405 when they don't support HEAD requests. 

## What is the effect on users?

It will make any curl based access work with more webservers.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ampaze** [comment]
Would milestone v20 Nexus be possible? The code change is pretty minor.

**Comment by lrusak** [comment]
> Would milestone v20 Nexus be possible? The code change is pretty minor.

It would require a separate PR to the Nexus branch. You can do a backport if this gets merged into master first.

**Comment by ampaze** [comment]
> It would require a separate PR to the Nexus branch. You can do a backport if this gets merged into master first.

Will do!

**Comment by fuzzard** [comment]
According to the following link

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501

it states

501 is the appropriate response when the server does not recognize the request method and is incapable of supporting it for any resource. The only methods that servers are required to support (and therefore that must not return 501) are [GET](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET) and [HEAD](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD).

I dont think this is correct in that sense then?

**Comment by fuzzard** [comment]
This seems to not necessarily be correct, and is more a faulty server.

reading Mozilla docs at 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501

it states

501 is the appropriate response when the server does not recognize the request method and is incapable of supporting it for any resource. The only methods that servers are required to support (and therefore that must not return 501) are [GET](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET) and [HEAD](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD).

so a HEAD should never return 501, and therefore is that then non compliant web server?

**Comment by ampaze** [comment]
@fuzzard Thanks for looking into it. 

Unfortunately non-standard behaviour is a reality in the web 😞 
Even though the webserver in question is doing it wrong as per spec, there is no harm in also handling 501 is there? I can only see benefits: more supported webservers.

**Comment by fuzzard** [comment]
Shouldnt the issue be reported to the web server and fixed there? are you going to go around and patch anything that comes into contact with said web server? surely itd be better to report the issue there, get them compliant, then everything works?

**Comment by arnova** [comment]
> Shouldnt the issue be reported to the web server and fixed there? are you going to go around and patch anything that comes into contact with said web server? surely itd be better to report the issue there, get them compliant, then everything works?

In principle you're correct of course but we had a simular issue in the past with nginx's non-compliant webdav implementation. Yes, they should fix their stuff but it could take quite some time before those fixes propagate back to the ordinary users (if fixed at all). So in this case I'm tempted to allow this workaround fix, as long as it's properly documented why.

**Comment by wsnipex** [comment]
which webserver are we talking about? Please provide more details

**Comment by ampaze** [comment]
> Shouldnt the issue be reported to the web server and fixed there? are you going to go around and patch anything that comes into contact with said web server? surely itd be better to report the issue there, get them compliant, then everything works?

Yes ideally it should be fixed on the server side. But I can see how easy it would be for anyone writing a web application to implement GET requests and for everything else just use the http return code that at a glance seems to be the best fit: 501 Not implemented.

The proposed change is very straight forward, easy to understand and it has no downsides. I can add more documentation if needed.

> which webserver are we talking about? Please provide more details

I don't know which webserver or server side application is used, there is no http header that gives this information.
Also I am not sure what you would do with this information, there is always another application, web dav feature or service around the corner that might make the relatable implementation mistake I outlined above.

**Comment by wsnipex** [comment]
so you access some (random) webservice? Which? Did you try to contact them?

**Comment by ampaze** [comment]
> so you access some (random) webservice? Which? Did you try to contact them?

Have I done anything to warrant your quite aggressive tone? What is happening? 
I have made a pull request with the intention to make Kodi better while solving a problem I found.

I did not:

* open an issue and made vague error descriptions like "it does not work"
* pester or attack anyone for not solving my problem
* posted something and then disapeared

Instead I:

* debugged the problem myself 
* looked through source code I have never seen before
* found a good solution
* read your guidelines 
* made a pull request
* explained why I think it is a useful addition

If you think the code change should not be in Kodi then please give specific reasons. I think I have explained my reasoning for the change and why it will benefit Kodi users (which includes me).

**Comment by wsnipex** [comment]
not sure where you read any aggressiveness, it certainly wasn't intended. 
The reason I think this change is wrong was already given above, it violates the spec. 
I have no repeatedly asked for more info and you have given none, which certainly doesn't help your case.

**Comment by Karlson2k** [comment]
Too late to comment, but let's leave it here for history:
The patch is correct. While we have RFCs that are (more or less) strict and clear and any web server **must** support `GET` and `HEAD` according to RFCs, it does not happen in practice. Same happens with other parts of HTTP specifications, like chunked uploads (it was/is not supported by many HTTP servers, while it is mandatory for HTTP/1.1).

The [RFC's descriptions](https://datatracker.ietf.org/doc/html/rfc9110#name-501-not-implemented) for `501` code is clear: the method is not supported completely by the server. Kodi can just fail (as before the patch) or retry with `GET` method.

We cannot fix everything in the net, but we can use obvious workarounds to improve user experience. 

When using Kodi as a web client, the best approach is "be as compatible as possible, if it does not reduce security".

**Pull request closed without merging**
