### PR TITLE
[python] revert rename of python api during dvdplayer rename

### PR DESCRIPTION
**Pull request by tamland**

### CODE REVIEW

**Comment by tamland** [comment]
jenkins build this please

**Comment by ronie** [comment]
-1 we don't have a DVDPLAYER core anymore.
the python API should reflect that change.

**Comment by MartijnKaijser** [comment]
-1 as well.

**Comment by MrMC** [comment]
could be at least be consistent in case :)

**Comment by Razzeee** [comment]
What @MrMC said.

**Comment by Montellese** [comment]
Yes please use all upper case. Should we keep the DVDPLAYER one for backwards compatibility?

**Comment by MartijnKaijser** [comment]
No don't keep it. It's been said many times thus has been deprecated for two years.

**Comment by phil65** [comment]
should be obselete because of https://github.com/xbmc/xbmc/pull/8525

**Pull request closed without merging**
