### PR TITLE
[win32] Update libmicrohttpd package, use static lib for libmicrohttpd (Helix)

### PR DESCRIPTION
**Pull request by Karlson2k**
Helix backport of #6413.
Resolves some webserver problems as reported on forum.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
i do not think a point release is the place to bump an ancient webserver without knowing any side affects and only doing this on Windows

**Comment by Montellese** [comment]
I agree with @MartijnKaijser. Last time @wsoltys attempted to update libmicrohttpd to 0.9.x it resulted in a lot of crashes and we had to revert back after two weeks or so. So this needs to be thoroughly tested.

**Comment by Karlson2k** [comment]
MHD was updated in my test builds more than month ago. All test builds include updated MHD. Last crash-winner build is with updated MHD too.
So it's good tested already.

**Comment by Karlson2k** [comment]
Version 0.4.5 was build on PlibC which tries to "emulate" thin POSIX layer on Win32. PlibC isn't a best choice because it may try to close file descriptor as SOCKET or HANDLE before closing as file descriptor. It also change locale and codepages and do more funny things that may influence on normal app functionality.

**Comment by Tolriq** [comment]
Please do not release a 14.2 without Windows fix for the crashes I have 250 000 users potentially affected that loves to remind me that remotes makes Kodi crash ...

**Comment by MartijnKaijser** [comment]
Please don't mix yourself into something totally unrelated to the crashing

**Comment by MartijnKaijser** [comment]
I will first want it in master for considerable time before even thinking of backporting. We have lived with the outdated lib for years so imo there's no real urge to backport something like that on the test base of only a few users compared to the total amount out there.

**Comment by Karlson2k** [comment]
OK, no problem.
If it will be fine in master - merge it for Helix. In case of any problems - close.

**Comment by Tolriq** [comment]
@MartijnKaijser : First reading the PR and the comments and not seeing a clear PR talking about the fix it would seem that this is part of the fix ...

Second there's know problem with webserver on Windows since years, reported multiple times, with ask for update of the MHD as all the problems are solved for example on rpi with an up to date MHD.

So yes in fact from remotes maker point of view it's completely related :)

So maybe when there's so big crash problem and a public communication saying we are aware but won't fix, taking time to say the PR is there's you can test it without this new MHD would have been a little better communication.

**Comment by MartijnKaijser** [comment]
sorry, i should indeed pointed to the other PR

**Comment by Tolriq** [comment]
No problem but I must admit that hundreds of angry users mails since December about this may have played a little too much with my nerves :)

So anyway to have details on the PR and fix so I can start communicate that there's a viable solution ?

**Comment by MartijnKaijser** [comment]
This is test thread http://forum.kodi.tv/showthread.php?tid=216275 which has https://github.com/xbmc/xbmc/pull/6403 which is the main crashing fix. It also has other things included that may or may not be backported.

**Comment by AussieFries** [comment]
I have not been able to use the Official XBMC Remote for iOS since Gotham due to constant disconnects. I would highly appreciate it if this fix wil at least be added to Kodi 15.

**Comment by topfs2** [comment]
Bit late to the party but I agree with the others. Bumping library version
in a point release sounds extremely scary and should only be done if its
been tested in master thoroughly, if at all.

**Comment by Karlson2k** [comment]
@MartijnKaijser Think that we should reopen this: http://forum.kodi.tv/showthread.php?tid=219627&pid=1954189#pid1954189

**Pull request closed without merging**
