### PR TITLE
[ios] Add support for iPhoneX full resolution

### PR DESCRIPTION
**Pull request by Memphiz**
As the title says. This adds the needed launch image with the correct size which kicks the iPhoneX out of the compatibility mode (which only has 2001x1125 pixels instead of the full 2436x1125).

It also hides the new home indicator (replacement of the now missing home button) once the user has not touched the display for a couple of seconds.

Tested and confirmed by users

### CODE REVIEW

**Comment by phil65** [comment]
feel free to cherry-pick https://github.com/phil65/xbmc/commit/e3cb144066c58c77249df8965d0af5ef1f0a3e8d :)

**Comment by Memphiz** [comment]
@phil65 - will this estuary change hit master anyway or was it made by you just for this PR here?

**Comment by phil65** [comment]
just for this PR.

**Comment by Memphiz** [comment]
thx @phil65 - added :)

**Comment by Memphiz** [comment]
Build errors unrelated

**Pull request merged**
