### PR TITLE
[confluence] show the subtitles OSD button in live TV too

### LINKED ISSUE #15688: Rapidly playing Youtube videos results in crash
## Bug report
Use a remote like Kore or Yatse to play a Youtube video. While the blue spinner is still displayed in Kodi, use the remote to tell another video to play.
Kodi will then crash.
### Describe the bug
Here is a clear and concise description of what the problem is:
* Use Yatse to play a Youtube video
* While Kodi is displaying the spinner, use Yatse to play another Youtube video

If the Yatse addon from https://yatse.tv/wiki/yatse-kodi-addon is installed, the issue is easier to reproduce. I believe that's because the spinner is displayed for longer.

The spinner seems to have to be spinning to get the crash to happen.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi shouldn't crash :)

## Actual Behavior

Kodi crashes.

### To Reproduce

1. Use Yatse to play a Youtube video
2. While Kodi is displaying the spinner, use Yatse to play another Youtube video

### Debuglog

The debuglog can be found here:
Crash log (including debug log): https://paste.kodi.tv/leqexikeho.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

n/a

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

n/a

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Gentoo Linux
 - Kodi version: master, commit 1a261cfe5c

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by Jalle19**
Fixes #15688

@ronie can you take a brief look? I don't like the amount of duplication in the skin, is there a better way to do this? The button IDs are also just random, things seem to work though.

@FernetMenta can you test this with closed captions in a live TV context somehow? I'll tell the guy who reported the bug to test as well.

### CODE REVIEW

**Comment by Jalle19** [comment]
@popcornmix the bug reporter asked if you could include this patch in your builds? Someone with ATSC is needed to verify this.

**Comment by FernetMenta** [comment]
@Jalle19 will try tomorrow. I can play recordings through the demuxer of vnsi

**Comment by Jalle19** [comment]
@FernetMenta thanks. The reporter tested already though and confirmed it works.

**Comment by FernetMenta** [comment]
@Jalle19 great then I can skip the test. thanks for this pr

**Comment by ronie** [comment]
confluence changes are ok.
i'll make a note to look into simplifying things once this is merged.

**Comment by Jalle19** [comment]
@ronie great, thanks
@BigNoid might want to check if your skin needs a similar change

**Pull request merged**
