### PR TITLE
added: video info dialog for movie sets

### PR DESCRIPTION
**Pull request by notspiff**
## Description
Video info dialog now works(?) for movie sets

## Motivation and Context
Requested by @olympia 

## How Has This Been Tested?
Briefly, not sufficient.

### CODE REVIEW

**Comment by KarellenX** [comment]
Thanks for this @notspiff .

I tested it and found a few issues, some cosmetic, some a carry over from Movie Info page, some can probably be fixed by skinning, others probably not. 

setinfo

1. Highlighting a movie in the top row brings up the Actors dialogue. Pressing Up will bring up the usual "would you like to install Extended Info script for Actors Info" dialogue, which does install if Yes is selected

2. Longer movie titles are truncated making it difficult to determine which movie is which. Scrolling text?

3. Year not required. Strictly not accurate as it is the year of the latest movie in the set.

4. Play button not required. Pressing it takes you back to the Sets list

5. There are no Sets rating. Even though you can add a Rating in the screen, exiting Kodi will clear the rating. Will confuse a lot of users, wondering where all their ratings have gone

6. Ignore

**Comment by DaVukovic** [comment]
Regarding "3" we could probably (if possible) show a year range from the movies which are in the set like it´s done here fore example: 
https://www.themoviedb.org/collection/1241
"Harry Potter Collection (2001-2011)"

Might also depend how the data can be scraped.

**Comment by notspiff** [comment]
great! core changes look good to me.

**Comment by KarellenX** [comment]
Looks great!

Thanks @ronie and @notspiff

**Comment by olympia** [comment]
Could this be added to v18.2?

**Comment by ronie** [comment]
nope, v18.x is for bugfixes only.
adding new functionality is something for v19

**Comment by notspiff** [comment]
rebased.

**Comment by notspiff** [comment]
good to go afaik. any objections?

**Comment by ksooo** [comment]
@notspiff Not sure this worked before, but I just noticed that with this PR merged, cast for movies which are part of a collection are (no longer?) available in video info dialog.

**Comment by ksooo** [comment]
> Not sure this worked before, but I just noticed that with this PR merged, cast for movies which are part of a collection are (no longer?) available in video info dialog.

@ronie maybe a skin issue?

**Comment by ronie** [comment]
can confirm this issue.
doesn't look like a skin thing to me.

**Comment by ksooo** [comment]
This is causing the problem: https://github.com/xbmc/xbmc/pull/15315/commits/bc29de37b7578c2875c9b678b25e00b4dce5cc47#diff-a4b7db2cbfe04fea9817e8014e79fe25R708

The condition evaluates to true not only for the sets itself, but also for the movies contained in the set.

**Pull request merged**
