### PR TITLE
[DOCS] Update README.OpenSuse

### PR DESCRIPTION
**Pull request by mgrep**
Addition of OpenSuse Build Dependencies and cmake build instructions for OpenSuse

## Description
Addition of OpenSuse Build Dependencies and cmake build instructions for OpenSuse

## Motivation and Context
Only Debian/Ubuntu is described in detail but I am on OpenSuse
I shared my own experience with OpenSuse.

## How Has This Been Tested?
Since KODI 15 I use git master repo to build KODI from sources on OpenSuse
succesfully so this is tested thoroughly for a long time. 

## Screenshots (if appropriate):
screenshot_2016-12-22_14-51-23

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by hudokkow** [comment]
Thx!

cc/ me

**Comment by mgrep** [comment]
Can you put me in the direction on how to do that ?

**Comment by hudokkow** [comment]
Do what? I was just cc'ing me so I can keep track of this PR.
Happy holidays!

**Comment by mgrep** [comment]
Silly me, I thought you meant me to cc you, which I find a little strange but I'm new to this so I had an open mind to this.
Happy holidays...

**Comment by Paxxi** [comment]
@wsnipex can you have a look? Seems OK so would be sad to see this forgotten about

**Comment by wsnipex** [comment]
Can you please move the Opensuse specific bits into README.opensuse and keep the general README.linux as generic as possible? e.g. using default CMAKE_INSTALL_PREFIX=/usr/local in the examples and removing the references to the old /project/cmake paths?

**Comment by mgrep** [comment]
I have made the changes and revert README.linux back to the original I hope
I did this the right way as this is still rather new to me and I have some
trouvble with navigating through all of hithub and it's options.
If I did something wrong I want to hear about it so I can fix it.

Met vriendelijke groet,
Maikel Grep
Tel. 06-45535350


De informatie verzonden met dit e-mail bericht kan vertrouwelijk zijn en
uitsluitend bestemd voor de geadresseerde. Indien bovenstaand e-mailbericht
niet aan u is gericht, verzoeken wij u vriendelijk doch dringend het
e-mailbericht te retourneren aan de verzender en het origineel en eventuele
kopieën te verwijderen en te vernietigen.
Ik sta niet in voor de juiste en volledige overbrenging van de inhoud van
een verzonden e-mail, noch voor tijdige ontvangst daarvan.

2017-01-15 17:44 GMT+01:00 Wolfgang Schupp <notifications@github.com>:

**Review by mgrep — COMMENTED** [review]
I have made the changes and revert README.linux back to the original I hope I did this the right way as this is still rather new to me and I have some trouvble with navigating through all of hithub and it's options.
If I did something wrong I want to hear about it so I can fix it.

**Comment by hudokkow** [comment]
Looks good. Can you squash the commits into one?

**Comment by wsnipex** [comment]
the how to compile section (cmake stuff) should also be in README.linux, since the current instructions are for autotools, which do not exist anymore.

**Comment by wsnipex** [comment]
thanks!

**Pull request merged**
