### PR TITLE
[backport] XTimeUtils: Prevent array index out of bounds access in SystemTimeToFileTime

### PR DESCRIPTION
**Pull request by neo1973**
## Description
Backport of #20451.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Review by basilgello — APPROVED** [review]
Good job!

**Review by garbear — APPROVED** [review]

**Comment by DaveTBlake** [comment]
This change has not been applied to master (the related POR was closed) so what is the justification for merging this backport @thexai ?

**Comment by thexai** [comment]
I think this is a "partial backport":

> Closed as #18727 is the better solution for Nexus. Backport is available as #20457 for Matrix.

https://github.com/xbmc/xbmc/pull/20451#issuecomment-958541323

**Comment by DaveTBlake** [comment]
No @thexai , it isn't "partial", that would still mean this code is in master but that master has additional changes or that the issue is fixed in master in a different way. As it stands master does not have a fix for the issue yet, and none of this code.

Less enthusiasm for hitting merge please @thexai 
I will see if we can merge this change into master, otherwise this will be reverted.

@neo1973 thanks for you work, the team has simply had a PR management blip which is none of your doing.

**Comment by thexai** [comment]
Sorry, I have not paid enough attention: I assumed that in master it was already applied (even with a different code).

**Comment by ksooo** [comment]
This PR introduces a serious regression: https://github.com/xbmc/xbmc/pull/20451#issuecomment-963665934

**Comment by DaveTBlake** [comment]
Reverted by https://github.com/xbmc/xbmc/pull/20496
Lesson: don't merge PRs especially backports without care and attention.

**Pull request merged**
