### PR TITLE
[curl] add support for HTTPS proxy type

### PR DESCRIPTION
**Pull request by jjlin**
## Description

Added support for HTTPS proxies under `Settings/System/Internet access`.

The `CURLPROXY_HTTPS` type was introduced in curl 7.52.0 (December 2016).

## Motivation and context

Provides users with the option to use HTTPS proxies in addition to plaintext HTTP and SOCKS proxies.

## How has this been tested?

Tested on a Windows build by installing an addon and verifying via Wireshark that the addon download used the proxy.

## What is the effect on users?

Added support for HTTPS proxies under `Settings/System/Internet access`.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] My change requires a change to the documentation (https://kodi.wiki/view/Settings/System/Internet_access)
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by jjlin** [comment]
> I've made some formatting changes to meet the current code style. The diffs are available in the following links:
> 
> * [PR21966-0001-8f848ddd47-curl-add-support-for-HTTPS-proxy-t.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/23971/artifact/PR21966-0001-8f848ddd47-curl-add-support-for-HTTPS-proxy-t.diff)
> * [PR21966.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/23971/artifact/PR21966.diff)
> 
> For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

This doesn't seem like an improvement to me, but let me know whether this is just a suggestion or an actual requirement for merging.

**Comment by ksooo** [comment]
It’s a requirement.

**Comment by ksooo** [comment]
You need to squash both commits down to a single commit.

**Comment by ksooo** [comment]
> the docs would reflect the current state of expectations,

The docs are part of this FOSS project as well and everybody is invited to contribute to it. :-)

**Comment by ksooo** [comment]
> "Code and cosmetic changes should be in separate commits"

 Every commit has to be aligned with project's clang-format rules.
 
 I admit, the wording is not good. What is meant is that you should provide one commit per logical change, whatever this is. For example, if you apply a functional change to a file, this should be in one commit, and in case you found some other things in that file (logically unrelated to commit 1) you would like to change (e.g. code formatting, c++ modernization at places commit 1 did not touch), put those changes in another commit. This makes the code review far more easy.

**Comment by fuzzard** [comment]
Thanks for the PR.

**Pull request merged**
