### PR TITLE
[Backport][Android] Update build (4.1 -> 5.4.1) and SDK (26 -> 28) versions

### PR DESCRIPTION
**Pull request by peak3d**
Update gradle : 5.4.1
Update Android SDK: 28
Update build-tools: 28.0.3

## Description
Backport of https://github.com/xbmc/xbmc/pull/16559

## Motivation and Context
Get next Leia versions published in google playstore

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [X ] **None of the above** (please explain below)

### CODE REVIEW

**Comment by Rechi** [comment]
Please adjust the commit message and PR title to something expressive. This commit and PR is not what you would expect from `Merge pull request #16559 from peak3d/sdkversion`.

**Comment by Rechi** [comment]
Adjusting the commit message was still missing.

**Comment by peak3d** [comment]
Huh? Oh, I changed the title and was in opinion that this is enough :-(

**Comment by Rechi** [comment]
> Please adjust **the commit message** and PR title [...]

You can see the commit messages of all commit the PR pulls in at https://github.com/xbmc/xbmc/pull/16743/commits.

**Pull request merged**
