### PR TITLE
[addons] allow skins etc. to be activated via info dialog

### PR DESCRIPTION
**Pull request by tamland**
Allows addons that can only have one in use at a time (skins, gui sounds, languages, visualization and screensavers) to be "activated" in the addon info dialog without having to dig through settings.

Reuses the "launch" button for plugins.

### CODE REVIEW

**Comment by mkortstiege** [comment]
In case an addon is already in use it would be nice to alter the button label instead of just disabling it. Other than that i really like the change ;) Thanks.

**Comment by tamland** [comment]
First part's a great idea:), but I'm not sure 'Set as default' would make sense here. (I'm not sure what any of it has to do with the "default" actually). E.g when you select a skin in the settings you select the skin you want to *use*, you don't select the skin you want to have as default.. Makes sense?

**Comment by mkortstiege** [comment]
Well, if you select one of those addons it will become the default for the given section (eg. weather, skin, webif etc). Let's see what the others think about it.

**Comment by phil65** [comment]
I agree with tamland that "set as default" doesnt really make sense in this context. Perhaps "Select", "Choose", "Set" or "Apply"?

**Comment by mkortstiege** [comment]
"Choose" sounds good to me and the label is already there.

**Comment by tamland** [comment]
So are we going with Choose and Chosen(?). I'm going to need two labels, like Use / In use, not just one.

**Comment by tamland** [comment]
On second thought, having the disabled label show the state looks really weird. It's barely visible and not clear at all that it shows actual information. No other buttons does this. E.g "Update" is just disabled if it's already up-to-date.

I've done what I think works best here. It now shows Open, Run or Use depending on the type. Any objections to that?

**Comment by mkortstiege** [comment]
Needs rebase. Could you please add some screenshots to make easier?

**Comment by tamland** [comment]
Rebased. I'm not sure what you want me to take screenshot of though @mkortstiege All it does is change the label of the "launch" button depending on the addon type. It not applicable it's disabled, like the current launch button.

**Comment by MartijnKaijser** [comment]
concept sounds ok to me.

**Comment by mkortstiege** [comment]
Could you please add some doxy so it's clear what's the difference between `CanRun` and `CanUse` and `CanOpen` without having to check the code in detail? Other than that no objections.

**Comment by tamland** [comment]
done. jenkins build and merge

**Pull request merged**
