### PR TITLE
[video] Improve Performance of the "Choose version" dialog

### PR DESCRIPTION
**Pull request by CrystalP**
## Description

Simplified the structure of the query that retrieves art to avoid a table scan for MariaDB engine.
This improved performance of sqlite as well, though not as drastically.

Made art loading async for the "Choose version" dialog, although it doesn't make much difference with the relatively low number of rows of versions or extras.

## Motivation and context

1-2 second delay noticed before the choose version dialog appears after selecting a movie.

It turned out that MariaDB query optimizer failed to use an index of the art table with the subquery structure of the SQL query.
Sqlite didn't have that issue (not to the same degree at least).

## How has this been tested?

Sqlite and MariaDB 10 & 11.

## What is the effect on users?

No delay for version/extra selection with remote database.

## Screenshots (if appropriate):

MariaDB, 64k rows in art table.

Before, 1.5s:
image

After, 3ms:
image

The difference is less drastic with sqlite (20-30% improvement of a considerably lower baseline).

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by ksooo — APPROVED** [review]
Fine for me if it works.

**Review by garbear — APPROVED** [review]
I'm OK with a 50,000% speedup. Record of some kind?

**Comment by fuzzard** [comment]
Jenkins build and merge

**Comment by ksooo** [comment]
@CrystalP we should bevor this. Could you open a PR for Omega?

**Pull request merged**
