### PR TITLE
renderer: eat video frames properly if there is no consumer - fix crash ...

### PR DESCRIPTION
**Pull request by FernetMenta**
@MartijnKaijser does this fix the issue

### CODE REVIEW

**Comment by FernetMenta** [comment]
@MartijnKaijser disregard, I need to have a look when having more time

**Comment by MartijnKaijser** [comment]
@stefansaraev
Could make a build for me with this patch somewhere tomorrow evening? Thx in advance

**Comment by FernetMenta** [comment]
now it should do :)

**Comment by stefansaraev** [comment]
@MartijnKaijser done and uploaded (20150315235245)

3b31ff0 is in. debug syms not stripped so you'll have propper crashlogs from now on.

**Comment by MartijnKaijser** [comment]
Seems to work fine again now. thx
Have fun at Cebit.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
