### PR TITLE
[omxplayer] SendDecoderConfig improvement

### PR DESCRIPTION
**Pull request by deeves-home**
There are rare occasions where the buffer returned by 'GetInputBuffer' isn't large enough to accept extra codec information located in 'm_extradata'. Rather than failing outright, write the data in sections if possible.

### CODE REVIEW

**Comment by popcornmix** [comment]
Do you have a sample file that requires this? (more than 80K of codec config data).

**Comment by deeves-home** [comment]
Apologies for the late reply. The following are samples that require more than the supplied 81K. The codec data for these are roughly in the 106K range:

http://deeves.co.za/temp/fail_smple01.ts
http://deeves.co.za/temp/fail_smple02.ts
http://deeves.co.za/temp/fail_smple03.ts

The following samples are from the exact same stream, just grabbed at other intervals:

http://deeves.co.za/temp/ok_test01.ts
http://deeves.co.za/temp/ok_test02.ts

The streams are generated by a hardware IP encoder connected to a sattelite settop box. I'm still trying to figure out if the encoder is not possibly generating errors since 106K seems a tad excessive. All of the samples were grabbed from the exact same setup, just at diffrent times.

Currently using 56.4.101 of libavformat.

The problem seems to manifest itself in omxplayer as the following error:

```
omxplayer.bin: OMXCore.cpp:785: OMX_ERRORTYPE COMXCoreComponent::FreeInputBuffers(): Assertion `m_omx_input_buffers.size() == m_omx_input_avaliable.size()' failed.
/usr/bin/omxplayer: line 67:  3267 Aborted                 LD_LIBRARY_PATH="$OMXPLAYER_LIBS${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" $OMXPLAYER_BIN "$@"
```

**Comment by deborah-c** [comment]
The reason that the samples require such a large extradata buffer is that when MPEG-4 video is extracted from an MPEG-2 transport stream, the entire stream (from when the PAT makes extraction viable) up to the first 00 00 01 B6 start code (start of VOP) is treated as extradata. This isn't entirely helpful: not only does it result in extradata being arbitrarily large, but it also doesn't start somewhere useful (typically in the middle of a VOP), and doesn't necessarily contain the VOL header that we actually need...

Consequently, I don't think that the correct solution is to allow transfer of outsized extradata. I have an experimental patch for ffmpeg (libavcodec/mpeg4video_parser.c) to change its behaviour to discard the unhelpful part of the stream and make the VO/VOL the extradata.

**Comment by popcornmix** [comment]
This is the suggested ffmpeg patch that means you don't get >80K of garbage in the extradata:
https://github.com/popcornmix/xbmc/commit/3ddb2bf0929df86bd8574814d39b7edada124f26

**Comment by FernetMenta** [comment]
@popcornmix where did you get this patch from?

**Comment by popcornmix** [comment]
@deborah-c wrote much of the the video decode firmware on the VideoCore GPU used on the Pi. I asked her to look for a better solution to this PR.

I'll include it on newclock4 for testing for a while, and try to push upstream if there are no issues. What's your view on the ffmpeg patch?

**Comment by FernetMenta** [comment]
ah, I though recommended by ffmpeg but this is not the case right. I recommend it that you send it upstream for discussion. if there is an issue it saves you lot of testing time.

**Comment by popcornmix** [comment]
Closing as https://github.com/xbmc/xbmc/pull/6957 fixes this issue.

**Pull request closed without merging**
