### PR TITLE
workaround for addon installer deadlocks

### PR DESCRIPTION
**Pull request by tamland**
This fixes deadlocks caused by the addon installer giving jobs to the job manager which depends on waiting on other jobs to finish (see https://github.com/xbmc/xbmc/blob/49cf9e6a5cb2e393cd1769c0b2ae34e2689e4931/xbmc/addons/AddonInstaller.cpp#L729). If the job manager is out of workers, it deadlocks.

Since this is the addon installer being broken at its core,  I see no other way (other than a rewrite) than to give it as many threads as required.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@Paxxi @FernetMenta any remarks or suggestions that fit with the v17 scope?

**Comment by FernetMenta** [comment]
JobManager can be used by every component. Allowing an undefined number of threads is high risk. That would just create another weak point instead of fixing one.

**Comment by notspiff** [comment]
wouldn't some (variant of) https://github.com/notspiff/xbmc/tree/draft_installer_fix do the job ? not tested.

**Comment by tamland** [comment]
>wouldn't some (variant of) https://github.com/notspiff/xbmc/tree/draft_installer_fix do the job ? not tested.

Not tested either but doesn't this end in a loop of constant rescheduling the same job?

>JobManager can be used by every component. Allowing an undefined number of threads is high risk. That would just create another weak point instead of fixing one.

To be fair, it's set to 10000, which is not even that high. Not saying this is 'good' in any way but is it *really* better to have a job manager that can deadlock, and where the 'high' priority isn't 'high' at all, but involves blocking until there's a free thread?

Either way, the proper fix is redesign the whole installer and make it non-blocking. But we need a quick fix for v17.

**Comment by FernetMenta** [comment]
@tamland how about adding an extra prio for that work-around?

**Comment by akva2** [comment]
The idea was to put the job at the end of the queue but i didnt check if queue is lifo or fifo

**Comment by akva2** [comment]
on a pc so can be more verbose. the situation used to be this. consider some addon, with dependency dep1, which again depends on dep2. the installer is a job queue with two workers. the installation jobs were scheduled as 'dep2 dep1 addon'. eventually you ended up in the situation where 'dep1' and 'addon' were executing in parallel. the 'sleep' code was there to make the 'addon' job wait for the 'dep1' job to finish.

if this now deadlocks, it somehow must end up with execution of 'dep1' and 'addon' before 'dep2'. so 'dep1' will wait for 'dep2', 'addon' waits for 'dep1' and it deadlocks. iow, the scheduling code must have changed. the cure then is to give up the worker slot to the 'dep2' job, and reschedule 'dep1' to execute afterwards. which is what i tried to implement in my patch.

**Comment by tamland** [comment]
Added a new priority. Can you please have a look @FernetMenta?

**Comment by FernetMenta** [comment]
my concerns are addressed, thanks

**Comment by tamland** [comment]
ok, 
jenkins build this please

**Pull request merged**
