### PR TITLE
Fixed the bug that ::isalnum's assertion failed

### PR DESCRIPTION
**Pull request by vidonme-developer**
Fixed the bug that ::isalnum's assertion failed when added subtitle's filename's flag-section include chinese on windows.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
any reviewers?

**Comment by FernetMenta** [comment]
this is imo not correct: // alphanumeric char is in [48,122]
isalnum observes the locale and depending on the locale characters like German umlauts are outside this range.

**Comment by vidonme-developer** [comment]
@FernetMenta thanks for your comment! I am going to fix it.

**Comment by vidonme-developer** [comment]
@FernetMenta I fixed it. Please review again.

**Comment by FernetMenta** [comment]
this still does not look right. you can't iterate through an UTF-8 string by casting every byte to char*
please elaborate on the issue you intend to fix.

**Comment by vidonme-developer** [comment]
@FernetMenta I think UTF-8 is compatible with ASCII, that means 'a' is 97 in ASCII and is also 97 in UTF-8, they both use one byte contains the value.

**Comment by FernetMenta** [comment]
your code would incorrectly detect an alphanum for a multibyte character that may be something different.
please answer my question: please elaborate on the issue you intend to fix.

**Comment by vidonme-developer** [comment]
std::string::iterator result = std::find_if(toParse.begin(), toParse.end(), ::isalnum);
The original code(as above) cause assertion fail when add some external subtitle.
e.g. movie is 2012.mp4, and added subtitle is 2012中文.-forced.srt.

Assertion fail is because ::isalnum can not deal with negative value(at least on windows). And chinese is multibyte in UTF-8 and the first byte is negative in char.

I think the original code writer is just want to trim any non-english character in the begining, because the flag he/she want to parse is just english. e.g. "none","default","forced".

**Comment by ace20022** [comment]
Maybe a regex?

**Comment by vidonme-developer** [comment]
My commit is just intend to  fix that assertion fail. So debug can go on.

**Comment by FernetMenta** [comment]
if I am not mistaken Kodi's internal format for strings is wchar. could you try to change isalnum to iswalnum?

**Comment by vidonme-developer** [comment]
String is not wchar, is char.
You can see std::string is used in that function(CUtil::GetExternalStreamDetailsFromFilename), not std::wstring

**Comment by FernetMenta** [comment]
right. can you check debug log for global locale on your system. mine shows:
global locale set to en_US.UTF-8

**Comment by vidonme-developer** [comment]
My log about global locale
18:55:10 T:9736    INFO: load language info file: special://xbmc/language/Chinese (Simple)/langinfo.xml
18:55:10 T:9736   DEBUG: trying to set locale to zho_chn
18:55:10 T:9736    INFO: global locale set to C

**Comment by vidonme-developer** [comment]
That is strange, language is chinese, but global locale is set to C~

**Comment by FernetMenta** [comment]
if setting locale fails, it gets set to C as fallback. do you have Linux or OSX machine to test. would like to know if this a  Windows issue. I don't know why Windows has a special case in CLangInfo::CRegion::SetGlobalLocale

**Comment by taxigps** [comment]
@vidonme-developer your version is old. global set wrong on window with older kodi. I have fixed it. right value is zh-cn.

**Comment by taxigps** [comment]
see https://github.com/xbmc/xbmc/pull/7820

**Comment by vidonme-developer** [comment]
@taxigps  Nice job.   I hvae multi versions of kodi in my computer. 
But assertion is still fail even I running latest kodi and set global local to zh-cn, de-at.en-us...

@FernetMenta 
Anyway ::isalnum(at least on win) does not support value < -1.  (_ASSERTE(c >= -1 && c <= 255);).
And CUtil::GetExternalStreamDetailsFromFilename only parse english strings("forced", "default"...), so any non-english string in the beginning should be trimed.
My origianl commit(with range[48,122]) can do that kind of trim no matter what the global local and charset are.

You can try by yourself if you have time.  Playback a video name as 2012.mp4 and add a external subtitle name as 中文zh.-forced.srt

**Comment by FernetMenta** [comment]
how about this?

```
  // trim any non-alphanumeric char in the begining
  std::wstring wstr;
  g_charsetConverter.utf8ToW(toParse, wstr, false);
  int pos = 0;
  char *locale = setlocale(LC_CTYPE, nullptr);
  std::locale loc(locale);
  for (auto ch: wstr)
  {
    if (!std::isalnum(ch, loc))
      pos++;
  }
  toParse.clear();
  g_charsetConverter.wToUTF8(wstr.substr(pos), toParse);

  std::string name;
  if (!toParse.empty()) // if we have anything to parse
  {
    std::string inputString(toParse);
```

**Comment by vidonme-developer** [comment]
@FernetMenta 
I applied your code and taken some test. It get wrong result in certain case.
e.g. subtitle filename is "狱前教育zh.-forced.srt" and it display as "鐙卞墠鏁欒偛zh.-forced" in variable toParse before trim, and as "鏁欒偛zh.-forced" after trim.  The right result should be "zh.-forced".

Anyway I had thought about convert to wchar as your post. I did not do it because IMO it is 'extra work' -- convert to wchar and convert back again. Because we only need to parse ascii 'a-z && A-Z' at range [48,122] later and UTF-8 is compatible with ascii.

**Comment by taxigps** [comment]
@vidonme-developer you may try to use `iswalnum`

**Comment by vidonme-developer** [comment]
@taxigps FernetMenta did use wchar version of std::isalnum and still get wrong result in certain case.

**Comment by vidonme-developer** [comment]
you can try std::isalnum,std::iswalnum ,isalnum,iswalnum in FernaetMenta's code to add a subtitle name as "狱前教育zh.-forced.srt".   The result is "鏁欒偛zh.-forced" , not "zh.-forced"

**Comment by FernetMenta** [comment]
I have never looked into the desired behaviour in detail. If only ascii is of interest for getting the stream details, why not writing:

```
std::string::iterator result = std::find_if(toParse.begin(), toParse.end(), StringUtils::isasciixdigit);
```

**Comment by vidonme-developer** [comment]
not StringUtils::isasciixdigit, should be StringUtils::isasciialphanum.  This is same as my original commit except it used a existing function--StringUtils::isasciialphanum.   I also agree with the following code. So you commit by yourself directly or I apply the new code and pull request again?
std::string::iterator result = std::find_if(toParse.begin(), toParse.end(), StringUtils::isasciialphanum);

**Comment by FernetMenta** [comment]
> not StringUtils::isasciixdigit, should be StringUtils::isasciialphanum

those two are exactly the same but isasciialphanum requires 3 functions calls for the same task.

**Comment by FernetMenta** [comment]
scratch my last comment :)
could you please update this pr?

**Pull request closed without merging**
