### PR TITLE
FileCache: streamline caching.

### LINKED ISSUE #22702: nfs4: readfactor + buffermode is ignored
### Describe the bug
Here is a clear and concise description of what the problem is:

NFS4 doesn't buffer any data.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

NFS4 should buffer data based on advancedsettings.xml

## Actual Behavior

NFS4 stalls out.

## Possible Fix

Read advancedsettings.xml

### To Reproduce

1. Enable NFS4
2. Restart Kodi
3. Add NFS4 network location
4. Add path
5. Restart Kodi
6. Play media
7. See it pause and never readahead.

### Debuglog

The debuglog can be found here:

No info.

### Screenshots 
Here are some links or screenshots to help explain the problem:

"Source too slow"

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Line rate to the server, just needs some buffering for high wa times.

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android
 - Kodi version: Nexus

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by KyleSanderson**
## Description

This removes a ton of waits, and streamlines media playback substantially. I'm getting 0sec seeking with NFS traffic over the internet all while using a dynamic cache.

## Motivation and context

Caching hasn't worked in XBMC for 20 years. I remember using FileZilla because AdvancedSettings.xml was required to playback files.

## How has this been tested?

NFSv4 over SSH with the chunk bug.

## What is the effect on users?

"Life changing".

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

This fixes https://github.com/xbmc/xbmc/issues/22702

### CODE REVIEW

**Comment by lrusak** [comment]
Can you please add the formatting changes?

**Comment by KyleSanderson** [comment]
Yeah. Sorry, had to flip assets. There's a bit more work I want to do on this after sleeping on it to fix it for "high latency" / jitter links as well. Naively by measuring the latency of each read from source and using that as an amplification factor as well will likely cover those still on tin cans (dsl).

**Comment by arnova** [comment]
First of all: I'm sorry but "Caching hasn't worked in XBMC for 20 years." simply isn't true. It had its defects (and still has) but it certainly worked for most scenarios.

Ok a few questions:
1) What do you mean by dynamic cache?
2) Mind explaining (in detail) the new logic you've implemented?

**Comment by fritsch** [comment]
Same from my side: Please squash the two commits, as the second one patches out stuff from the first. I also would like to know about the logic. Looking at the code - I think the most dominant change was that you only stop reading when there is less than 1 Byte free.

Can you emphasize on your design idea here? Maybe some benchmarks would be great or annotated behaviour like cache filling, cpu usage, etc. The real problem I had with the cache implementation is, that it is too complicated for an outsider to understand all the edge cases. Your changes might work (TM) but maybe only for you and they don't really add to the maintainability.

Therefore: No harm intended, but if we want to fix it for all - we all need to understand what is going on there and where your changes contribute towards a better world. Thanks in advance.

**Comment by arnova** [comment]
One more question: Since you've stated that it's wrong to assume the cache read rate should be equal to the file's average bitrate, I assume the main issue is a fillrate that's too low. But if that's the issue wouldn't a higher readfactor simply workaround this issue?

**Comment by fritsch** [comment]
For me it seems, that the readfactor won't work properly anymore after the cache was filled once. So it seems stuff is getting loaded quiet okayish at first, playback starts - aber after that it seems that cache drops too easily until underruns occur.

I just runtime tested the code here and it seems, that here actually the cache stays filled the entire time (the forward cache I mean) ... but let's wait for @KyleSanderson to explain what he changed.

**Comment by KyleSanderson** [comment]
Apologies in advance for the length.

> First of all: I'm sorry but "Caching hasn't worked in XBMC for 20 years." simply isn't true. It had its defects (and still has) but it certainly worked for most scenarios.

You're right, apologies for the emotional comment. It hasn't worked for me ever out of the box for the past 20 years (I still have a T3CH build kicking around on an asset). I did for fun spin that up and it was using configured for SMB, 128M cache with a readfactor of 1000. I still feel very strongly that this hasn't worked out of the box without configuration for many (network share) users.

Anyway.

OK, so the magic numbers are gone and this now uses the latency figures provided by the underlying VFS with amplification factors. There are 4 caches here which is what makes the semantics quite interesting.

With how seeking previously worked the source would starve for upwards of 5(!) seconds blocking meaningful progress. I've fixed a number of race conditions and crashes previously hidden by arbitrary waits, and also moved everything into the main data path flow.

There's (very) weird things with the returns of caching implementations (like IsCachedPosition returning valid for 0 avail), but that doesn't impact this anymore.

> Mind explaining (in detail) the new logic you've implemented?

How the algorithm works now is:
1. We take the requested read length from (CDVD/Video/etc)Player (which has its own cache).
2. Amplifies it by the peak latency seen from the source (which is a page cache miss from the host and/or network jitter, typically).
3. Amplifies it by a 10th of the average latency of the source.
4. Amplifies by (taking the max returned read rate, and divide it by the average read rate).
5. If the read rate is greater than the max size of the cache, we cap it at the cache size.
6. If the read rate is less than the present cache size, we cap it at the end position of cache size (which insulates against big swings).
7. Finally, if the read rate is less than 2 chunks, we cap it at 2 chunks per a code comment somewhere.

> So in other words, according to you: What's the actual root cause of your issue?

Affer spending a couple hours on this with profiling and gdb, a ridiculous amount of contention and just odd actions being taken. Even if the buffer is increased to 256MB, the read rate still gets far too low with the current algo. With the waits, mixed with high bitrate content, there's no way this works at all for 4K streaming. This testing was done on a 21Mbit/s file with a 101k chunk size (all defaults).

The last bit here (that I think I need help with) is IOCTRL_CACHE_STATUS. It seems to not trigger properly when there's a stall.

I also strongly believe that the memory cache should be increased from a hard coded 20MB (and should grow dynamically to a then configured ceiling), but I don't know how this would impact the JeOS folks.

**Comment by arnova** [comment]
Please note my time is quite limited at the moment. Unfortunately I still don't fully understand all the changes in this PR. If the waits are the problem wouldn't simply lowering them mitigate the issue as well? Furthermore this PR is against Nexus, but it certainly should (only) be against master. Also apply the formatting changes suggested by jenkins to improve readability....

**Comment by fritsch** [comment]
Please rebase and squash your commits, this is not reviewable.

#backup your work:
git branch mybackupof22799
# add xbmc as an upstream
git remote add xbmc-upstream https://github.com/xbmc/xbmc.git
# fetch that upstream (B)
git fetch xbmc-upstream
# rebase on that upstream (B)
git rebase -i xbmc-upstream/master

Now select your commits and squash them into one single commit.

The steps marked with (B) you can do always when you want to do the operation again. The others are only relevant the first time.

**Comment by fritsch** [comment]
And please reopen against master. Nexus is released and only backports reach Nexus.

**Comment by KyleSanderson** [comment]
> And please reopen against master. Nexus is released and only backports reach Nexus.

Your information is old since the force push.

**Comment by enen92** [comment]
Jenkins build this please

**Comment by fritsch** [comment]
> > And please reopen against master. Nexus is released and only backports reach Nexus.
> 
> Your information is old since the force push.

Will be my copy / paste source for the future ...

**Comment by arnova** [comment]
> > And please reopen against master. Nexus is released and only backports reach Nexus.
> 
> Your information is old since the force push.

The formatting changes still haven't been applied....

**Comment by enen92** [comment]
Gave this a spin and it breaks live tv for me...
https://paste.kodi.tv/iyeqilahit.kodi

**Comment by enen92** [comment]
Hey, gave this a spin and breaks live tv for me...
master: https://paste.kodi.tv/ukiyumoyey.kodi
pr: https://paste.kodi.tv/humisupize.kodi

**Comment by KyleSanderson** [comment]
> Hey, gave this a spin and breaks live tv for me... master: https://paste.kodi.tv/ukiyumoyey.kodi pr: https://paste.kodi.tv/humisupize.kodi

Might be a bad port on my end. I went back to the classic limiter from the comments mentioning time constraints...

let me look

**Comment by thexai** [comment]
Tested and found seek is broken. 

i.e: chapter skip on large file blocks until is read all file data from actual position to new position:

seek

The initial speed corresponds to play (70 Mbps) when doing seek it goes up to 1 Gbps until the new point is reached (it takes seconds or even minutes) since all the data is read sequentially.

**Comment by KyleSanderson** [comment]
hmmm. So even with m_seekPossible being set to 0 I capped it at the bounds of the cache to avoid exactly this from happening. What's your storage backend?

Did you get any of the INFO or WARN logs?

**Comment by thexai** [comment]
This is without advanced settings cache (all defaults). Media files in NAS shared NFSv3, 1 Gbps Ethernet.

Same happens in both Windows and Android (Shield)

**Comment by KyleSanderson** [comment]
> This is without advanced settings cache (all defaults). Media files in NAS shared NFSv3, 1 Gbps Ethernet.
> 
> Same happens in both Windows and Android (Shield)

So, it could be seeking related, but I think you're mixing up seeking with it now hard blocking the filesystem underneath (which is why seeking can take forever, because it's 100% network bound).

What I'm seeing on my system is Thumbnail reading the entire file before generating a thumb. Are you sure you're not seeing the same?

**Comment by KyleSanderson** [comment]
https://github.com/xbmc/xbmc/issues/24236#issuecomment-1858921228

Simply wow. Thank you for finally taking a look at this. There's a couple current playback bugs with your new landed code (where playback simply stops) but I'll refrain from reporting them. I'm glad to see ideas were taken from here and they've made it upstream in the appropriate fashion. This has to be the worst development experience I've ever had in a community.

**Pull request closed without merging**
