### PR TITLE
[tools][texturepacker] Fix gif decoding and packaging

### PR DESCRIPTION
**Pull request by ace20022**
Remaining tasks
- [x] add static 5.1.1 lib and upload it
- [x] build release and upload it

### CODE REVIEW

**Comment by ace20022** [comment]
@amet and skinners please test.

**Comment by ronie** [comment]
using giflib 4

it works for some gif images, but not for the ones amet referred to:
https://github.com/xbmc/repo-skins/blob/frodo/skin.pm3-hd/media/home-favourites-focus.gif

i get this output when TexturePacker creates the textures file:
```
This is a GIF - lets load it via libgif...
Gif::PrepareTemplate(): Unknown disposal method: 5
Gif::ExtractFrames(): Could not prepare template after frame 0, skip it
Gif::PrepareTemplate(): Unknown disposal method: 5
Gif::ExtractFrames(): Could not prepare template after frame 1, skip it
....
Gif::PrepareTemplate(): Unknown disposal method: 5
Gif::ExtractFrames(): Could not prepare template after frame 27, skip it
Gif::LoadGif(): Could only extract 0/28 frames.
```

the resulting Textures.xbt file is corrupt and will make kodi crash:
http://pastebin.com/sesvmbLT

**Comment by amet** [comment]
old code(before these changes) creates texture fine using giflib 4

I cant check anything for next few days

**Comment by ace20022** [comment]
>it works for some gif images, but not for the ones amet referred to:
https://github.com/xbmc/repo-skins/blob/frodo/skin.pm3-hd/media/home-favourites-focus.gif

There are only 4 disposal methods (0-3) specified, but this gif reports method 5 for every frame.
We could fallback to another method with a warning, which firefox etc. seems to do, but I'm not a fan of this.

> old code(before these changes) creates texture fine using giflib 4

Yes in this case it works because of that #ifdef: https://github.com/xbmc/xbmc/blob/master/tools/depends/native/TexturePacker/src/decoder/GifHelper.cpp#L424 which disables the complete method. Hence man gifs won't work.

**Comment by amet** [comment]
@ace20022 all gifs packaged with old code and giflib4 work as intended, they are animated gifs and display correctly in a skin

**Comment by ace20022** [comment]
@amet No, only gifs consisting of full frames work. This https://s-media-cache-ak0.pinimg.com/originals/ac/94/09/ac9409fd952edeea2447a1195ae8a7d8.gif , e.g., does not.

**Comment by amet** [comment]
@ace20022 no errors packaging pm3.hd gifs I referenced earlier after changing osx giflib to 4, with 5.1.0 same errors as you are seeing.

**Comment by ace20022** [comment]
@amet Could you please test one more time with both versions 4 and 5?

**Comment by amet** [comment]
unable to test, away from my dev environment for few days

**Comment by ace20022** [comment]
@ronie Could you help? I want to backport it for jarvis.

**Comment by ronie** [comment]
looks good to me. tested with both giflib 4 & 5.

**Comment by ace20022** [comment]
jenkins build this please

**Comment by ace20022** [comment]
@ronie @amet thx for the feedback!

**Pull request merged**
