### PR TITLE
Minor fixups for cross builds

### PR DESCRIPTION
**Pull request by MaxKellermann**

### CODE REVIEW

**Comment by wsnipex** [comment]
mind explaining what this is supposed to fix?

**Comment by MaxKellermann** [comment]
I thought that was already explained in the individual commit messages - do you need more explanation than that, or did you not read them?

**Comment by wsnipex** [comment]
> configure.ac: pass $CFLAGS to $CC in XB_FIND_SONAME
Required for cross-compiling when CFLAGS contains -march=...

Doesn't really explain the change

**Comment by MaxKellermann** [comment]
Oh, I thought it was obvious enough for somebody who knows how cross-compiling works. Maybe it's not, after all. If you call the compiler without "-march=..." it will compile for the build host, not for the build target. That will make the cross-build fail. Is that clear enough?

**Comment by MaxKellermann** [comment]
Oh, maybe you didn't understand because you've never used a multi-arch compiler? gcc usually defaults to the one target because one gcc compiler binary can only do one target anyway. Omitting the "-march=" is a mistake, but rarely has an effect. But there are advanced compilers such as clang which can generate binaries for all targets with just one compiler binary, and omitting the "-march" flag is a fatal mistake here.

**Comment by wsnipex** [comment]
I understand how multi-arch works. I'm just trying to figure out which issue you are trying to solve and which possible caveats exist. As you said, not passing -march has worked for us for a long time now, with gcc and clang.
I agree that it'd be good to support it, but it needs proper testing.

**Comment by MaxKellermann** [comment]
Please confirm that cross-compiling to a non-native (and non-Apple) architecture has worked for you with a generic clang.

Without -march, clang will invoke the native linker, and the native linker will look up the native library. Maybe this has worked because you happened to have all required libraries installed on your native host as well, and the resulting SONAME happened to be the same.

In any case, if this has ever worked, it was a coincidence, and not success by design.

**Comment by wsnipex** [comment]
I've never used clang to cross compile on non-apple, so if this is the issue you are trying to fix, you could have said so in the beginning ;)

**Comment by Memphiz** [comment]
I think the change is sane. ATM on our official builds clang is only used on darwin for building osx32, osx64 and ios builds. The branch you altered for FIND_SO_NAME is not hit with clang in that case. But i think the change is sane. We just don't have any measure to verify it really.

Lets kick jenkins anyway - jenkins build this please

**Comment by MartijnKaijser** [comment]
is this something that can go in before final or for 16.0 ?

**Comment by Memphiz** [comment]
@wsnipex i am ok with this for Isengard - and you?

**Comment by wsnipex** [comment]
yes, ok for me

**Pull request merged**
