### PR TITLE
[addons][audiodecoder] rework about audiodecoder addon system

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description

In connection with my sandbox / API level project, some independent things that are necessary for this type of work are introduced here.

Furthermore, some improvements have been integrated so that more is supported, such as cover art.

There is also a new dialog so that the supported formats can be displayed in the addon information dialog (will be expanded to include other addon types in the future).

It would be a bit too thick to list the contents of the individual commits above, hence all commits with a description in them.

A few commits here, which do not belong directly to audiodecoder, are also brought into other requests.

## Motivation and context

To make it even more usable.

## Screenshots (if appropriate):
Bildschirmfoto vom 2021-10-14 20-33-40

Bildschirmfoto vom 2021-10-14 19-30-48

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [X] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by howie-f — COMMENTED** [review]
not an easy review :) i only have few suggestions for now.. thanks alwin

**Review by AlwinEsch — COMMENTED** [review]
Thanks a lot about review! I added your suggestions.

**Comment by AlwinEsch** [comment]
Have added a new commit where for audiodecoder the namespace becomes renamed. On new files I used already as them and thing it match more the code sryle rights.

About the other files where use namespace ADDON I look also then to change.

**Review by howie-f — APPROVED** [review]
fine in my opinion, i would let it roll this way

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by howie-f** [comment]
wtf, maybe try a windows testbuild?

**Comment by AlwinEsch** [comment]
> wtf, maybe try a windows testbuild?

I tried, on my Local Windows it success by all possible builds (32bit and 64bit) :cry.

It's always strange that VS works there and on other places make problems.

**Comment by AlwinEsch** [comment]
Strange is also that here https://github.com/xbmc/xbmc/pull/20428 it has worked (on Win32-UWP) and since last build also brings the errors.

**Comment by AlwinEsch** [comment]
What a shit, Windows still fails by 32 bit and no idea what goes wrong there, hope someone have a idea?

Crazy that at home there comes no problems.
Also looks his error message a bit strange:
```
23:44:13 C:\Users\Kodi\Kodi\jenkins\builds\workspace\WIN-32\xbmc\addons/kodi-dev-kit/include/kodi/addon-instance/AudioDecoder.h(634): error C2440: '=': cannot convert from 'bool (__cdecl *)(KODI_ADDON_AUDIODECODER_HDL,const char *)' to 'PFN_KODI_ADDON_AUDIODECODER_SUPPORTS_FILE_V1' (compiling source file C:\Users\Kodi\Kodi\jenkins\builds\workspace\WIN-32\xbmc\filesystem\FileDirectoryFactory.cpp) [C:\Users\Kodi\Kodi\jenkins\builds\workspace\WIN-32\kodi-build.x86\libkodi.vcxproj]
```

With the `to 'PFN_KODI_ADDON_AUDIODECODER_SUPPORTS_FILE_V1' ` looks like it not find the used typedef inside audiodecoder.h.

**Pull request merged**
