### PR TITLE
[TEMP][JENKINS][C++17 Torture] Done this to torture jenkins a little and test addons

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description

This is purely for test purposes and to ensure that the addons have been converted.

Posted as a temporary request in Kodi to be visible to everyone.
When the associated add-ons are through, this request is closed again.

Revert "Merge pull request 18403 from lrusak/c++17-revert"

Will start it every few days and list the addons that have yet to be changed here.

## How Has This Been Tested?

| Addon  | Android-ARM | Android-ARM64 | Android-X86 | IOS-ARM64 | LINUX-64 | LINUX-64-Wayland | OSX-64 | WIN-32 | WIN-64
|-- | -- | -- | -- | -- | -- | -- | -- | -- | --
| audiodecoder.modplug |   |   |   | ❌ | ✅ | ✅ |   |   |  
| audiodecoder.nosefart |   |   |   | ❌ | ✅ | ✅ |   |   |  
| audiodecoder.vgmstream |   |   |   | ❌ | ✅ | ✅ |   |   |  
| imagedecoder.raw |   |   |   | ❌ | ✅ | ✅ |   |   |  
| inputstream.ffmpegdirect |   |   |   | ❌ | ✅ | ✅ |   |   |  
| pvr.dvblink |   |   |   | ❌ | ✅ | ✅ |   |   |  
| pvr.dvbviewer |   |   |   | ❌ | ✅ | ✅ |   |   |  
| pvr.hts |   |   |   | ❌ | ✅ | ✅ |   |   |  
| pvr.mediaportal.tvserver |   |   |   | ❌ | ✅ | ✅ |   |   |  
| pvr.vdr.vnsi |   |   |   | ❌ | ✅ | ✅ |   |   |  
| pvr.waipu |   |   |   | ❌ | ✅ | ✅ |   |   |  
| visualization.projectm |   |   |   | ❌ | ✅ | ✅ |   |   |  
| audiodecoder.fluidsynth |   |   |   |   | ❌ | ❌ |   |   |  
| game.libretro.mrboom |   |   |   | ❌ | ❌ | ❌ |   |   |  
| pvr.sledovanitv.cz  |   |  |   | ❌ | ❌ | ❌ |   |   |  

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by AlwinEsch** [comment]
jenkins build this with addons please

**Comment by AlwinEsch** [comment]
jenkins build this with addons please

**Comment by AlwinEsch** [comment]
jenkins build this with addons please

**Comment by AlwinEsch** [comment]
jenkins build this with addons please

**Comment by phunkyfish** [comment]
Why are dvbviewer and hts still listed. They should work with cpp17 before 4 days ago.

**Comment by ksooo** [comment]
Nothing for v19.

@AlwinEsch can this PR be closed?

**Comment by AlwinEsch** [comment]
Yes, will look for 20 about

**Pull request closed without merging**
