### PR TITLE
AESinkAudioTrack: Don't use hardcoded 5_1 or 7_1 masks

### PR DESCRIPTION
**Pull request by fritsch**
Test-Build for: #22077

### CODE REVIEW

**Comment by lrusak** [comment]
Just an FYI you don't need to submit a PR to create and upload a test build.

You can simply have Jenkins build your branch directly and select the platform(s) you want built.

**Comment by fritsch** [comment]
Jep - I know. I eventually - after guarding it with v26 wanted to consider that merging - eventually, let's see what the user's test results reveal. When I did that 4 years ago far too many Boxes refused to play 7.1 afterwards. Curious this time.

**Comment by fuzzard** [comment]
Looks to have not fixed the users issue, any value in this still?

**Comment by fritsch** [comment]
Would help for non-standard 7.1 layouts ... let's just keep it open - but let me remove the milestone. Chances are always high, that we break something on Android, especially for "edge cases" the FW implementations are still not good, which was the reason for forcing the default 7.1 / 5.1 layout for 6 speakers + lfe always.

**Pull request closed without merging**
