### PR TITLE
addonbrowser: add LastUpdated window property

### PR DESCRIPTION
**Pull request by tamland**
Adds a window property to show the last date and time repositories was checked for updates. I'm not sure if 'window properties' is the preferred way to do this. (please comment)

### CODE REVIEW

**Comment by phil65** [comment]
for me a window property sounds fine.

**Comment by ronie** [comment]
perhaps use Updated instead of LastUpdated, for consistency sake.

we use Window(Weather).Property(Updated)

**Comment by tamland** [comment]
Makes sense:)

**Comment by da-anda** [comment]
should we add the Confluence adjustments along with this PR or do them separately?

**Comment by tamland** [comment]
If somebody who knows skins can make the adjustments I can cherry pick it, sure

**Comment by ronie** [comment]
just merge and i'll handle it afterwards.

**Comment by tamland** [comment]
jenkins build and merge

**Pull request merged**
