### PR TITLE
dvdplayer - consider clock not last frame on screen when going rewind

### PR DESCRIPTION
**Pull request by FernetMenta**
another fix for rw

@afedchin can you test again. while having written my last comment I noticed this issue.

### CODE REVIEW

**Comment by afedchin** [comment]
sure. i'll test this now

**Comment by afedchin** [comment]
much MUCH better. but it still not same as smooth as ff.

**Comment by FernetMenta** [comment]
thanks for feedback. 

> but it still not as smooth as ff

that we can remedy by making ff worse :)

jenkins build this please

**Comment by ksooo** [comment]
Tested this as well - on Linux. As @afedchin says, much MUCH better. Thx.

**Comment by uNiversaI** [comment]
FF at 2x and 4x is horrid now, pictures are really unsmooth. Its better at higher speeds x8 x16

**Comment by fritsch** [comment]
You can make a video before and after with your iphone?

**Comment by FernetMenta** [comment]
if this is the case, it is certainly not caused by this pr. This change only affects rewind.

**Pull request merged**
