### PR TITLE
[addons] fix 'system addons'

### PR DESCRIPTION
**Pull request by tamland**
This removes various workarounds and fixes the broken path check for determining which are system addons (the ones per-installed and required to operate). They're now loaded from a manifest file.

Note that this flips the default state for addons installed via cpluff to disabled. For users there will be no change, but if you're a distribution maintainer you'll need to patch the manifest file if you want to have other addons part of the system addon. <-@stefansaraev?

### CODE REVIEW

**Comment by stefansaraev** [comment]
thanks @tamland I think this is good one. I just runtime tested and it works as promised ;)

got a nonreproducible deadlock while trying to disable one of my "system" addons (just once), but I dont think it is related to this PR. 

openelec can use xmlstarlet to patch the manifest at the time service.openelec.settings (which is critical and must always be enabled) is installed. or just ship a trivial patch. (cc @sraue @lrusak - fyi)

+1 :)

**Comment by Razzeee** [comment]
thank you @tamland 
this is awesome, I can use the manifest to exclude those addons from the toplists on the addon website! that makes it a really smart solution :)

**Comment by stefansaraev** [comment]
I tested with Addons*.db removed and kodi fails to start:

http://sprunge.us/aIbY backtrace is not very helpful (cant build with debug syms atm), but audioencoder.xbmc.builtin.aac is not missing. it is in /usr/share/kodi/addons/

**Comment by tamland** [comment]
Thanks @stefansaraev! Obvious mistake in that check:) Should be fix.

**Comment by stefansaraev** [comment]
yes no crash now.

**Comment by stefansaraev** [comment]
hm. there seems to be something wring after fresh start with Addon*.db removed http://sprunge.us/TIOF
CRepositoryUpdater job fires immediately (not sure it's how it supposed to be, iitc - there was some delay before trying repo update before.) and kodi not started

**Comment by tamland** [comment]
@MilhouseVH is this something you can include? To have it together with the controller input pr the manifest file needs to be patched. Untested but I believe https://gist.github.com/tamland/2285003c7d37d98b75d4 should be all.

**Comment by MilhouseVH** [comment]
@tamland: I'll include it in tonight's build (thanks @seo - will include a variation of your xmlstarlet commit).

**Comment by stefansaraev** [comment]
I want that (not so active) github account :)

**Comment by tamland** [comment]
@MilhouseVH put that on hold for a moment will you. Seems like there's *yet another* bug in our database code causing this to not cleanly upgrade from version 21.

**Comment by MilhouseVH** [comment]
OK

**Comment by tamland** [comment]
@MilhouseVH Lets try again together with #9166 :)

**Comment by MilhouseVH** [comment]
Seems to be working fine, will include in future builds. Thanks.

**Comment by tamland** [comment]
@MilhouseVH I'm presuming there's been no issues?

**Comment by MilhouseVH** [comment]
I've not seen any problems reported, so would seem to be all good.

**Comment by tamland** [comment]
jenkins build this please

**Comment by tamland** [comment]
@Memphiz Found some old ios hacks for forcing touch skin here. Not sure if this requires fixing some packaging scripts as well?

**Comment by MartijnKaijser** [comment]
@ronie has some PR for that

**Comment by ronie** [comment]
part of the ios hacks will be gone indeed when we replace re-touched with estouchy:
https://github.com/xbmc/xbmc/commit/9bbb0bbc8961c7702dcfe1b5d7ede1a2fb1964de

i've kept the code in system.h as there's one binary addon depending on it (afaik):
https://github.com/notspiff/audiodecoder.timidity/blob/master/lib/timidity/interface/xskin_i.c#L937

**Comment by tamland** [comment]
Ok, I'll revert those changes and just leave ios broken for the time being. (or do you plan on merging that right away @ronie?)

**Comment by ronie** [comment]
i hope to merge the estouchy pr in a couple of days from now.
depends ofc on the amount of feedback / required changes from the rest of the team.

**Comment by tamland** [comment]
Ok, then I'll add back the changes to Settings.cpp here and merge so we at least don't leave ios completely broken. 

When you rebase on master @ronie remember to add `<addon>skin.estouchy</addon>` to `system/addon-manifest.xml`.

**Comment by ronie** [comment]
will do, thanx for the heads-up!

**Comment by Memphiz** [comment]
@tamland you triggered me with a text which suggests you wanted to link something from me in that comment. I have no clue what you are talking about here - just sounds like breaking ios is in the game ... ;)

**Comment by tamland** [comment]
@Memphiz: we are taking about various ifdefs that makes re-touched the default skin. You can relax. There's no breaking ios;) ronie posted a proper fix together with #9222 2 seconds after I pinged you!

**Comment by MilhouseVH** [comment]
@tamland: I'm getting an odd situation with RPi builds from [build #0220](http://forum.kodi.tv/showthread.php?tid=250817&pid=2252342#pid2252342) onwards, which is when I started including this PR (and it's the only obvious PR that might be related to the problem). Build #0219 is working normally. I don't know if this PR is the cause of the problem, but it is the only obvious candidate.

Starting with build #0220, if I delete Addons22.db (and there are no other Addons*.db in the Database folder) and then start Kodi, `kodi.bin` will fail to startup normally - it will freeze on a blank screen. If `kodi.bin` is restarted (or the device rebooted), Kodi will start normally however this makes for a poor first-run experience.

This is the last line output in the log when kodi fails to start normally:
```
03:12:12 531.334351 T:1859117984   DEBUG: CRepositoryUpdater: running scheduled update
```

If I attach `strace` to the `kodi.bin` process, this is all I see:
```
OpenELEC:~ # .strace -p 1111
Process 1111 attached
futex(0x1210c2c, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 1, {1462911299, 769221290}, ffffffff^CProcess 1111 detached
 <detached ...>
OpenELEC:~ #
```

Killing the `kodi.bin` process with `kill -SIGSEGV` results in the following crashlog: http://sprunge.us/SdBg

Here is a debug-enabled crashlog produced in the same way as above (based on urrent master): http://sprunge.us/RHKK

I'm not sure why Kodi is blocking on a repository update, particularly when a network may not be configured at this point (in my case there is a wired network connection, but users on WiFi may not have a working network connection).

I havenn't been able to reproduce on Ubuntu, even though it does the same repository update:
```
03:56:36 T:139730678401152   DEBUG: CAddonDatabase: xbmc.metadata has been installed.
03:56:36 T:139730678401152   DEBUG: CAddonDatabase: xbmc.pvr has been installed.
03:56:36 T:139730678401152   DEBUG: CAddonDatabase: xbmc.python has been installed.
03:56:36 T:139730678401152   DEBUG: CAddonDatabase: xbmc.webinterface has been installed.
03:56:37 T:139730678401152   DEBUG: CRepositoryUpdater: previous update at 01/01/1601 00:00:00, next at 22/03/2016 03:56:37
03:56:37 T:139730219034368   DEBUG: Thread Timer start, auto delete: false
03:56:37 T:139730219034368   DEBUG: CRepositoryUpdater: running scheduled update
03:56:37 T:139730210641664   DEBUG: Thread LanguageInvoker start, auto delete: false
```

**Comment by tamland** [comment]
@MilhouseVH See #9443

**Comment by MilhouseVH** [comment]
Thanks, will give a try!

**Comment by MilhouseVH** [comment]
#9443 looks like it has fixed the problem - thanks @tamland.

**Pull request merged**
