### PR TITLE
[Video] A few video extras fixes

### PR DESCRIPTION
**Pull request by CrystalP**
## Description

One commit per point.

- Do not scan for extras in a flat folder structure (setting "Movies are in separate folders that match the movie title" is turned off)

- Change AddVideoExtras() to ignore folders when looking for the movie to attach the contents of an "Extras" folder to.
The function enumerates the folder containing the extras folder, but at least with Windows, folders are returned before files. In a recursive situation, this caused the wrong movie parent to be identified (a "sub"-movie contained in a folder at the same level as the extras folder, instead of the movie folder containing the extras folder).
See an example in context paragraph.

- Adapted the video asset removal confirmation dialog to the type of asset

- Fixed nested db transaction in CVideoDatabase::DeleteMovie(). Some callers create a transaction, others don't so DeleteMovie() now creates a transaction only when there isn't one yet and returns error codes to let the caller deal with errors and do the right thing with an already open transaction.

- Modified CVIdeoDatabase::AddVideoAsset to not modify the name of an existing asset already attached to the owner (preserves customized name of extras during library scans). There is a separate rename function SetVideoVersion().

- Honour .nomedia marker in subdirectories of extras folder (was already followed for extras folder itself).

## Motivation and context

Some issues found while reviewing the wiki article on video extras.

- For the following structure and setting "Movies are in separate folders that match the movie title" = OFF

```
...\Movies
...\Movies\Extras\making of.mp4
...\Movies\Extras\interview with the director.mp4
...\Movies\Dune (1984).mp4
...\Movies\Lucy (2014).mp4
````
It's not clear what the library scanner should do with the extras. Actual results: the extras are attached to the first movie (Dune(1984)). There is no convention to designate which movie the extras belong to, and adding them to all movies is not possible due to the db design. It seems best to block this undefined case, and that's the explanation currently in the wiki.

- For the following structure and setting "Movies are in separate folders that match the movie title" = ON and "Scan recursively" = ON

```
...\Movies
...\Movies\Dune (1984)
...\Movies\Dune (1984)\dune.mp4
...\Movies\Dune (1984)\Extras\making of.mp4
...\Movies\Dune (1984)\Lucy (2014)
...\Movies\Dune (1984)\Lucy (2014)\lucy.mp4
...\Movies\Dune (1984)\Lucy (2014)\Extras\making of.mp4
```
It's not expected to be a common situation but the outcome is still surprising, on Windows at least: both extras get attached to the "inner" movie Lucy(2014).

- The video asset removal confirmation dialog title and messages always refer to a video version, even when removing an extra

- video library scans revert the video extra names to the default names (the filename), overwriting user changes.
For example change the name of an extra, add another video file to the extras folder and update the library. The new file is detected and added as extra, but at the same time the name of the existing extra is changed back to default.

- .nomedia files are not honoured in subfolders of the extras directory

## How has this been tested?

Scanned movies and tv shows, with all combinations of "Movies are in separate folders that match the movie title" and "Scan recursively", with an Extras folder in different locations.

Removal of video extra (and version for negative testing).

## Screenshots (if appropriate):

Video extra removal dialog with correct title and text:
image

## What is the effect on users?

Fixed a few unusual situations involving video extras and library scans, fixed extra removal dialog messages.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by neo1973** [comment]
Jenkins build this please.

**Comment by neo1973** [comment]
The Jenkins failures are due to warnings: https://jenkins.kodi.tv/job/android-x86-docker/7448/clang/

**Comment by CrystalP** [comment]
Thanks, I didn't know where to look for a description of the issue.
The commit includes the formatting issue pointed at by Jenkins, not sure what's happening there.

**Comment by neo1973** [comment]
Jenkins build this please

**Review by neo1973 — APPROVED** [review]
Looks good, thank you :slightly_smiling_face:

**Pull request merged**
