### PR TITLE
Splash: fix: flip() under lock - no kodi start (active splash & vsync_always)

### PR DESCRIPTION
**Pull request by mk01**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@xhaggi @mkortstiege ping

**Comment by xhaggi** [comment]
@mk01 does it mean that there is no splash image if vsync is set to always?

**Comment by mk01** [comment]
@xhaggi 

Kodi runs (threads-wise), but Render() from Application.cpp and CSplash both end up stuck on call GetBackBuff (in case of EGL) - while screnn/VT crashes into text mode.

Kodi doesn't finish initial loading, wants to quit after a while, but because main thread is blocked never stops as well. 
(but what is started runs fine until kill -9).

**Comment by fritsch** [comment]
@FernetMenta ping - I think @mk01 is right and architecture wise evil happens here.

**Comment by FernetMenta** [comment]
Holding the lock while swapping front/back buffer should be avoided because swapbuffers would block most of the time. But I don't understand why it would lock up if the lock is held.

**Comment by mk01** [comment]
@FernetMenta 

I know the question was rhetorical, anyhow if I would be able to grasp the complexity and reason, I would tell you. :)

with fresh pull upstream/Isengard, reset --hard, distclean and recompile (with rm -fr on home dir), this is output from gdb (if full debug symbols needed, tell me).
at the bottom of the file is last 10 lines from kodi.log. all stays valid as said before (the test case or values of settings)

http://paste.ubuntu.com/12193718/

**Comment by mk01** [comment]
@FernetMenta @xhaggi 

clearly it might be only adverse effect of something laying in the code already before, but it got visible now with those @xhaggi's commits from end of July.

**Pull request closed without merging**
