### PR TITLE
[dxva] Added advanced setting to workaround dxva color range issues o…

### PR DESCRIPTION
**Pull request by afedchin**
…n some setups.

The main idea of setting is don't do color range conversion by Kodi and let's output frame as driver decides. Default value is false so it needs to be changed only if current output is wrong.

I don't like idea to introduce a new advanced setting, but I don't see any other solution.

@FernetMenta @phate89 @MartijnKaijser ping

### CODE REVIEW

**Comment by FernetMenta** [comment]
@afedchin this looks like something that would fit into this: https://github.com/xbmc/xbmc/pull/9154
platforms can override ProcessInfo without touching platform independent code. I intend to give renderers access to this object to make auto options real automatic, dependent on runtime data.

**Comment by afedchin** [comment]
@FernetMenta I'm not be able to dermine which system has the issue.

**Comment by phate89** [comment]
As I already said I don'know this stuff so maybe I'm not understanding well the code but shouldn't you also request limited if the option is enabled?
The problem that made the conversion in shader needed was because with  some driver the conversion wasn't working. 
But this isn't great quality wise because we convert limited -> full (by gpu) -> limited (from our shader).
So I thought the option was if disabled as default the current behavior, safe,conversion in shader that works everywhere 
With option enabled old behavior. We do a request the limited frame from the gpu and use it directly. Doesn't matter if it fails because it's disabled by default..
With this changes how it behaves when enabled?

**Comment by FernetMenta** [comment]
@afedchin at least we know it's Windows. You could even white or blacklist particular GPUs there. All better than an advanced settings that less than 10 people are aware of.

**Comment by afedchin** [comment]
@FernetMenta a black/white list will not work. it doesn't depends on GPU, it depends on driver (and/or driver settings) which we cannot determine. It also may depend on windows version I don't know exactly. I can just remove any color conversion after dxva processing at all and let's driver do that depending on driver settings (really I don't care, because all my PC's has no issue at all, but I try to find best solution)

@phate89 Actually we cannot determine will dxva convert color range or not (as described above). This is why some user faced with the issue.

**Comment by phate89** [comment]
I know that but that's the only way you can get the best quality from kodi. Everything else is worse because you always convert the color range..
I thought that if an advanced user isn't satisfied of the default quality can try to enable and see if its hardware works OK to get the best possible quality.
I don't understand what the advanced setting does right now. If you enable it you get the gui in limited range and the video in full range?

**Comment by afedchin** [comment]
if you enable the setting video will be same as driver output. let's wait test build with another possible solution.

**Comment by FernetMenta** [comment]
```
  m_DXVACheckCompatibility = false;
  m_DXVACheckCompatibilityPresent = false;
  m_DXVAForceProcessorRenderer = true;
  m_DXVANoDeintProcForProgressive = false;
  m_DXVAAllowHqScaling = true;
  m_DXVAPassColorRange = false;
```

I see no reason why other platforms should be aware of these settings. It's Windows only. 

Advanced settings are evil in general but platform specific advanced settings are even worse. ( I know that all platforms contribute to this mess)
I just noticed a half a dozen of them that will be gone next week :)

**Pull request closed without merging**
