### PR TITLE
[fontconfig] - bump to 2.11.1 - fixes #15864

### PR DESCRIPTION
**Pull request by Memphiz**
As the topic says. It fixes trac ticket #15864 (bad rendering of some subtitles) - confirmed on ios by the bug reporter.

Jenkins built fine:

http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-All/671/ (some addons failed due to problems downloading the tarballs from our mirrors - to be ignored...)

### CODE REVIEW

**Comment by Paxxi** [comment]
Should this be matched on win32 as well?

**Comment by Memphiz** [comment]
1. User reported that the problem doesn't happen on desktop (i can ask him if it was windows but i really prefer to don't work with him ever again ...)
2. There is no win32 source for this fontconfig version (i looked into the readme of our current win32 package and it pointed to some gnome.org mirror with win32 sources - we already use the latest).
3. Since there was no straight forward way to update the windows package because of 2. i left it out here. Though of course we prefer to keep the used versions in sync across all platforms as much as possible.

**Comment by uNiversaI** [comment]
Dont know if this would apply https://gitorious.org/sbuild/sbuild/source/0d74fab76a38b9cd0d00825280d135fa1a24f1eb:src/mingw/fontconfig-2.11.1-2/mingw-fontconfig.RELEASE_NOTES

**Comment by Paxxi** [comment]
don't think it should be any real trouble to build it, wouldnt be well tested though so best to hold of until v16 unless we have verifiable issues on windows

**Comment by Memphiz** [comment]
will merge in the next daysif no objections

**Pull request merged**
