### PR TITLE
AE: add a switch to signal that streaming will continue

### PR DESCRIPTION
**Pull request by FernetMenta**
prevents AE from falling back to gui sound mode immediately if VP wants to open a new stream

### CODE REVIEW

**Comment by peak3d** [comment]
works as expected, thx.

**Comment by FernetMenta** [comment]
build error unrelated

**Comment by Rechi** [comment]
@FernetMenta have you actually looked into the compile output?
The failure is definitely related to this change.

**Comment by FernetMenta** [comment]
sorry, I incorrectly interpreted this as one of those timeouts we have very often.

@popcornmix can you fix OMXaudio?

**Pull request merged**
