### PR TITLE
[PVR] API enhancements (series timer type, recording status, timer EpisodeName)

### PR DESCRIPTION
**Pull request by metaron-uk**
Adds 3 non-breaking changes to the API:
1. PVR_TIMER_TYPE_REQUIRES_EPG_SERIES_ON_CREATE (see http://forum.kodi.tv/showthread.php?tid=227026&pid=2103890#pid2103890 )
2. Adds PVR_TIMER.strEpisodeName (see conversation in https://github.com/xbmc/xbmc/pull/8005 )
3. Adds an iStatus field (now individual booleans) to recordings (currently with: record in progress/keep forever/expires soon). Should also reduce CPU load to answer the 'isCurrentlyRecording' question and be more accurate (see conversation in https://github.com/xbmc/xbmc/pull/7905) while a proper solution is developed to fix the 'buffering' question. This also adds potential for extra 'about to expire' and 'keep forever' icons in the future (not included in this PR).

Change 1 also required db schema bump.
Change 2  required an additional info tag adding

pings: @ksooo, @ryangribble, @ronie (for the confluence skin changes in the strEpisodeName commit and possible future icons), @janbar, @glenn-1990, @Jalle19, @opdenkamp, @FernetMenta .

NB: I will be on holiday (i.e. not contactable) between 16th and 21st September, so will miss the final run-up to the 20th Alpha 3 merge deadline. I'm not proud though, so feel free to cherry pick from this PR if necessary and I'll close it when I get back. 
If that means I don't need to bump all the addons so much the better!

### CODE REVIEW

**Comment by ryangribble** [comment]
@ksooo yes we will implement support for the requires Epg series attribute in pvr.wmc, if merged.

**Comment by metaron-uk** [comment]
I've incorporated most of the 1st round of feedback. Still need to finish the EPG database part of the 'isSeries' restriction, but would welcome feedback on the 'Flags' idea so far.

**Comment by ryangribble** [comment]
Looks good so far (note - not runtime tested yet)

**Comment by metaron-uk** [comment]
@ksooo, @ryangribble I've completed the database changes, runtime tested against a hacked version of pvr.mythtv (https://github.com/metaron-uk/pvr.mythtv/tree/changeAPIcheck) and rebased.

@ksooo If it is possible to conduct a second code review this evening, I will check back later to incorporate any feedback. Hopefully I've not left any trailing spaces.... (I'm on holiday from tomorrow morning until 21st, so @ryangribble if changes are needed and you want to take on the baton to get this into Jarvis, be my guest!)

Things checked:
Database (migration Epg10.db -> Epg11.db, database reset via UI, delete and create new database)
screenshot
UI (does 'series' recording type appear when you select a series, does it not appear when you select a movie)

That you can playback an in progress recording and buffering features are different than when playing back an ordinary recording (as there isn't anything else hanging off the new recording status booleans at present)

That the timer list includes 'Subtitles' even when no EPG information is available
screenshot027

Have chosen API 4.1.0 as this is a non-breaking (i.e. additions only) API change (not a bug fix only which I assume would be a 4.0.1)

Potential issues:
1) strSubtitle required me to add a new **ListItem.TimerSubtitle** GIU code: ping @ronie 
2) I have added bRecordingInProgress, bExpiresNever and bExpiresSoon for recordings. See this forum posting for justification: http://forum.kodi.tv/showthread.php?tid=227026&pid=2105057#pid2105057
3) I have added several EPG status flags, not not just 'IsSeries'. This was based on discussions with krustyreturns (http://forum.kodi.tv/showthread.php?tid=227026&pid=2101144#pid2101144) and information found on line about the EPG tags which UK broadcasters should provide (http://www.digitaluk.co.uk/__data/assets/pdf_file/0007/86326/DUK_Guide_for_Schedule_Providers.pdf)

Several of these features aren't fully 100% end to end yet, which I know is something @Ksooo is keen on avoiding to prevent API bloat. Personally I think all these flags have a purpose, even if not all of them are fully implemented by backends, clients or kodi core yet. As there won't be scope to add them once the API is frozen, I've put them in now. I hope this is OK.

Also, I've created minimal addon branches which just rolls the requested PVR API version from 4.0.0 to 4.1.0. I figured as there are no essential code changes (other than a re-compile) and @ksooo just rolled to 4.0.0 a day ago, this would be OK. PRs for the addons to follow shortly.

**Comment by metaron-uk** [comment]
ping @opdenkamp @Jalle19 @janbar  - WIP should now be complete with 1st round of comments incorporated. If possible I'd like this to make Jarvis Alpha 3.

**Comment by ksooo** [comment]
Generally I always have a problem with API extensions without a concrete use case (PR in best case). IMO, some of the extensions suggested here fall exactly into this category.

* Add strSubtitle to PVR_TIMER : +1, fine by me
* Add status booleans to PVR_RECORDING: -1, as I'm missing the concrete use cases. Fixing CPVRecording::IsBeingRecorded using one of the new booleans does not make much sense as the only calling method gets actually not fixed by this. The data needed for this (something like IsRealTime flag or function) is not yet available at the API. The other two new booleans are just "dangling", without a caller.
* Add EPG flags: same here, -1. Much stuff added, no caller for the new functionality, not even accessible for skins (guiinfo). Do we really need all this flags? Is there at least one backend that proviedes all these flags?
* Add Timer Type EPG Series Restrict Flag: +1, fine by me.

**Comment by ksooo** [comment]
Regarding the Addon PRs: Are they all just API bumps without functional enhancements, even without addon version bump and changelog? I thought that at least pvr.wmc will come with support for the API stuff you have added here?

**Comment by ksooo** [comment]
Sorry, WIP badge will stick for now.

**Comment by metaron-uk** [comment]
My aim was to get the API changes in now before the Alpha 3 cut-off. The pvr.wmc stuff was going to be done by krustyreturns / @ryangribble and I was going to PR janbar for mythtv. 

IMHO the addons don't need to support the new features to roll the API, just have a means of implementing them later on. (The addon update window is always open after all). As there wasn't any need to change the addons, I thought a version bump just to say 'use latest PVR library' just a re-compile needed seems overkill.

I accept your point about most of the EPG and Recording flags not having anything to drive on the UI with these commits. I'm guessing the skinning interface freezes with Alpha 3 as well, so they really need to go in at the same time. I've got several ideas but have run out of time to implement them.

Happy this says at WIP for now. If you or someone else wants to cherry pick the bits you feel comfortable with for Jarvis feel free, otherwise I'll try and address the shortcomings for "Kxxxxxx" (along with a proper realtime PVR api fix when the videoplayer part is ready and it can be tested end-to-end).

Good night, talk to you next week. :)

**Comment by ryangribble** [comment]
Thanks for the work @metaron-uk. The main one of importance for us is the bIsSeries boolean and the timer type attribute to prevent showing a type when the Epg item is not a series. Otherwise we get a backend error whenever a user tries to add a repeating timer for a Epg entry that isn't flagged as series 

So I'll think about  cherry pick those changes to  get them into alpha 3

**Comment by ksooo** [comment]
> IMHO the addons don't need to support the new features to roll the API, just have a means of implementing them later on.

 Yep.

> I thought a version bump just to say 'use latest PVR library' just a re-compile needed seems overkill.

 No overkill. API bumps should always result in a new addon version. Imagine the addon will never ever touched again (or more realistic, not for a longer time), then the changelog (users see in Kodi UI, btw) will contain misleading/wrong information (last action: bumped API to v4.0.0, but meanwhile it actually is 8.0.0 ;-).

> I'm guessing the skinning interface freezes with Alpha 3 as well, so they really need to go in at the same time.

 This is my take on this as well.

 Good night and thanks for all what you've done already for Kodi. Much appreciated.

**Comment by ksooo** [comment]
@ryangribble 

> The main one of importance for us is the bIsSeries boolean and the timer type attribute to prevent showing a type when the Epg item is not a series.

 I understand the timer type attribute stuff. You flag the respective type in your addon and Kodi's Timer Settings dialog will not display this type. All fine. The respective commits in this PR are IMO okay and you could "git cherry-pick" them and put them a new Kodi PR.

 But I'm puzzled about EPG_TAG_FLAG_IS_SERIES. The current PR does nothing else than making this flag available to Kodi core - but no guiinfo (skin) bindings or something else. So, if you set this flag in your addon, Kodi will do know about this flag, but will do absolutely nothing with it! What do you expect Kodi to do if this flag is set?

**Comment by ksooo** [comment]
The longer I'm looking at the proposed API change to introduce PVR_TIMER.strSubTitle the more I do not like it. :-/

If an addon wants to create a timer title containing a concatenation of EPG_TAG.strTitle and EPG_TAG.strEpisodeName and whatever else, why shouldn't it just fill PVR_TIMER.strTitle with all this? 

PVR_TIMER.strTitle is just a string wihout any semantics except "a title that should make some sense for end users reading it" - no restriction to EPG content or anything else.

If you're looking at things like this, there is no API change needed to achieve the goal to display "better" timer titles in PVR Timer window - which is basically the only functional enhancement I see in the related commits of this PR.

**Comment by Jalle19** [comment]
FWIW I don't see why we need `PVR_TIMER.strSubTitle` either.

**Comment by ryangribble** [comment]
@ksooo 
> I understand the timer type attribute stuff. You flag the respective type in your addon and Kodi's Timer Settings dialog will not display this type. All fine. The respective commits in this PR are IMO okay and you could "git cherry-pick" them and put them into a separate Kodi PR.

> But I'm puzzled about EPG_TAG_FLAG_IS_SERIES. The current PR does nothing else than making this flag available to Kodi core - but no guiinfo (skin) bindings or something else. So, if you set this flag in your addon, Kodi will do know about this flag, but will do absolutely nothing with it! What do you expect Kodi to do if this flag is set?

Hmm either I havent explained myself well enough or you may have missed the one (crucial) point where this IS_SERIES flag is used in Kodi Core: https://github.com/metaron-uk/xbmc/commit/e5bc5e3e6912875559feb93946a09bc5fb920981#diff-db4d826cc7a0144872b2c6453d75d062R890

As previously mentioned, we needed a way to say that a TimerType REQUIRES an EPG item to "be a series".  This is because with pvr.wmc if the user tries to perform a repeating EPG based timer for a EPG item that is NOT a series (as flagged in the WMC backend) then a backend error will occur.  The first proposed implementation used the existing Kodi EPG Tag fields of SeriesNumber EpisodeNumber and EpisodePartNumber to determine if an EPG item "is a series" or not and thus control the TimerType visibility... but some of our user's EPG data doesnt include the Series/Episode data but still does flag an item as "IsSeries=true".  So we wanted to have a boolean attribute on EPG Tag for "IsSeries".  Meanwhile metaron proposed to add a number of other EPG Tag attributes and stores them all in a single iFlags field (to avoid future EPG database changes and so on).  I think this is a good plan.  I take the point that there isnt a concrete use case for all the other fields at the moment, but there is for the IsSeries one.  So shall I cherrypick these commits and scale back the EPGTag iFlags to only include the one possible option for now?  That seems better for expanding in the future, rather than changing it to an explicity boolean IsSeries property...

**Comment by ksooo** [comment]
@ryangribble 

> Hmm either I havent explained myself well enough or you may have missed the one (crucial) point where this IS_SERIES flag is used in Kodi Core:

Ooops. Obviously I did. Sorry.

> But there IS a concrete use case for the IsSeries one.

 Sure. And now that I got it I have no longer a problem with it. ;-)

> So shall I cherrypick these commits and scale back the EPGTag iFlags to only include the one concrete option for IsSeries for now?

  Yes, please. And please make a note in the API doxy that iFlags is there because we intend to add more flags over time (when concrete use cases come in).

**Comment by ryangribble** [comment]
OK ive cherry picked the required commits and made the requested adjustments under a final commit, the pull request is here: #8075

**Comment by metaron-uk** [comment]
I've incorporated most of the code review feedback while I had it fresh in my mind and re-based on @ryangribble 's API 4.1 (thanks for seeing this through into Jarvis by the way, I submitted https://github.com/janbar/pvr.mythtv/pull/17).
I will continue to tinker with this in preparation for Kxxxx, including 'uses' for the new recording iFlags.

**Justifications**
*regarding 'strSubtitle' for PVR_TIMERs:*
This has two benefits I can see, but they aren't necessarily 'must haves':
1) The skin can choose if it wants to display subtitles for timers, and when it does, choose the format to display them (i.e. separated by a dash (as pvr.mythtv used to do), enclosed in brackets (as confluence currently does for strEpisodeName), a separate column, or whatever it wishes)
2) The main benefit I can see is that 'Find Similar' can return similar items by searching on 'title' alone. The presence of subtitle in brackets for upcoming shows means it never returns anything using pvr.mythtv at present. 
screenshot031

*regarding 'iLifetime' 'bExpiresNever' and 'bExpiresWithin24Hrs' (replacing 'soon'):*
iLifetime == bExpiresNever == bExpiresWithin24Hrs == 0 : not defined / not used
iLifetime >0, bExpiresNever == bExpiresWithin24Hrs == 0 : expires in iLifetime days
iLifetime == 0, bExpiresNever == 1, bExpiresWithin24Hrs == 0 : will never expire
iLifetime == 0, bExpiresNever == 0, bExpiresWithin24Hrs == 1 : will expire within 24 hrs
Maybe bExpiresNever + bExpiresWithin24Hrs could be made a 2 bit 'validity' field for iLifetime
(00 = use if non-zero; 10 = expires never; 01 = expires within 24h, 11 = reserved), but that might be overkill - booleans are easier to code!
I will see if I can come up with some preliminary 'icons' and logic for skins to use here.

*regarding the new iFlags variables:*
Might be worth me taking a look at Emby as KrustyReturns suggested. I can see icons indicating 'surround sound', '3d' or 'audio description' might be really useful for some users and clutter for others, so probably this needs configuration options as well as confirmation that a backend can drive them.
I get the impression WMC can could do some of this already, but pvr.mythv although it has some of the data in the backend and uses it in the internal EPG, doesn't offer it up via the services interface (yet!)

Still I've plenty of non-api changes to keep me busy for now!

**Comment by metaron-uk** [comment]
REQUIRES_SERIES_ON_CREATE made Jarvis thanks to @ryangribble,
You can't do a 'find similar' on a timer anymore, so the 'timer subtitle' change has little purpose.
Extended EPG attributes aren't supported by the API interface with my backend of choice (mythtv) yet so I can't test them (although at least some of them are provided by my listings provider...).
I can't get too excited about displaying recording lifetimes at the moment, although I might re-think this position in the future. A 'will keep this forever' icon might be nice.
I'm closing this PR to avoid it confusing people.

**Pull request closed without merging**
