### PR TITLE
[Android] Change the directory used to verify the SDK path

### PR DESCRIPTION
**Pull request by joseluismarti**
## Description
The configure script checks the path provided in the `--with-sdk-path` parameter is the Android SDK. The script checks for the existence of `tools/bin/sdkmanager` in this path.

The "tools" directory belongs to the [SDK Tools](https://developer.android.com/tools/releases/sdk-tools) package. This package is obsolete and no longer needed in current versions of build-tools, so it's preferable to check with the "cmdline-tools" directory that belongs to the SDK Command-Line tools package.

## Motivation and context
Fixes SDK path verification error message when configuring the build for the first time on a clean install.

## Types of change
- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by joseluismarti** [comment]
Oops! builders have the "cmdline-tools" package installed in another directory.

I thought they are using the proposed path in the [Readme](https://github.com/xbmc/xbmc/blob/master/docs/README.Android.md#32-configure-android-sdk): SDK path/cmdline-tools

**Comment by hugbug** [comment]
I confirm the problem this PR is trying to solve. I had to manipulate on file system to get the configure script pass.

> Oops! builders have the "cmdline-tools" package installed in another directory.

Maybe test for both locations with OR to make the script compatible with both packages?

**Comment by joseluismarti** [comment]
Right, it's better to test in both locations, I'll change it

**Comment by joseluismarti** [comment]
It can be merged, solve the issue:

`configure: error: verify sdk path`

with current versions of the Android SDK Command line tools

**Pull request merged**
