### PR TITLE
AE: make sure not to feed data into tempfilter after it got drained

### PR DESCRIPTION
**Pull request by FernetMenta**
fix occasional crashes

@popcornmix does this help?

### CODE REVIEW

**Comment by popcornmix** [comment]
No change I'm afraid:
```
#0  0x760bdf70 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x760bdf70 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x760bf324 in __GI_abort () at abort.c:89
#2  0x01786208 in yae_load_frag (src_end=0x0, src_ref=0x0, atempo=0x73c43b90) at libavfilter/af_atempo.c:540
#3  yae_flush (dst_end=0x0, dst_ref=0x73c43c44, atempo=0x73c43b90) at libavfilter/af_atempo.c:925
#4  request_frame (outlink=0x0) at libavfilter/af_atempo.c:1143
#5  0x016cd8d0 in ff_request_frame_to_filter (link=0x4e15e7e0) at libavfilter/avfilter.c:387
#6  0x016d1ab4 in ff_filter_graph_run_once (graph=<optimized out>) at libavfilter/avfiltergraph.c:1434
#7  0x016d20f0 in av_buffersink_get_frame_flags (ctx=0x67d69cc0, frame=0x67da22f0, flags=0) at libavfilter/buffersink.c:144
#8  0x008c10c8 in ActiveAE::CActiveAEFilter::ProcessFilter (this=0x67d6db30, dst_buffer=0x67de07b4, dst_samples=1200, src_buffer=<optimized out>, src_samples=0, src_bufsize=0)
    at Engines/ActiveAE/ActiveAEFilter.cpp:255
#9  0x008c045c in ActiveAE::CActiveAEBufferPoolAtempo::ProcessBuffers (this=0x67de0588) at Engines/ActiveAE/ActiveAEBuffer.cpp:861
#10 0x008bd02c in ActiveAE::CActiveAEStreamBuffers::ProcessBuffers (this=0x67d6aca8) at Engines/ActiveAE/ActiveAEStream.cpp:644
#11 0x008ae600 in ActiveAE::CActiveAE::RunStages (this=0x0, this@entry=0x4270050) at Engines/ActiveAE/ActiveAE.cpp:1837
#12 0x008b0bac in ActiveAE::CActiveAE::StateMachine (this=this@entry=0x4270050, signal=signal@entry=22, port=port@entry=0x0, msg=<optimized out>) at Engines/ActiveAE/ActiveAE.cpp:924
#13 0x008b1138 in ActiveAE::CActiveAE::Process (this=0x4270050) at Engines/ActiveAE/ActiveAE.cpp:1045
#14 0x01adde14 in CThread::Action (this=0x4270058) at Thread.cpp:221
#15 0x01ade0e0 in CThread::staticThread (data=0x4270058) at Thread.cpp:131
#16 0x76422e90 in start_thread (arg=0x745ff410) at pthread_create.c:311
```
and the new error message doesn't appear in log.

**Comment by FernetMenta** [comment]
@popcornmix updated, can you try again

**Comment by popcornmix** [comment]
Looks okay to me with latest commit. Will include in tonight's build to see if it solves original reporter's problems.

**Comment by FernetMenta** [comment]
thanks
jenkins build this please

**Pull request merged**
