### PR TITLE
[posixdirectory] don't force translation to utf8

### PR DESCRIPTION
**Pull request by mkortstiege**
Do not blindly translate to UTF8. 

@Karlson2k, as discussed on IRC. Your button.

### CODE REVIEW

**Comment by notspiff** [comment]
uhm. yes we want to force translation to utf-8, it's the only thing our gui will handle. why would you want to break this ?

**Comment by mkortstiege** [comment]
Right. To trigger happy here, we need the UTF8 Label. Closing.

**Comment by notspiff** [comment]
i assume there was an issue here, care to entertain my curiosity ?

**Comment by mkortstiege** [comment]
Sure :). There's an report where rename (move) fails in the FileManager and @Karlson2k suggested we might drop the charset translation. But that's just handling the Label as you pointed out.

**Comment by Karlson2k** [comment]
We don't support non-UTF-8 local filesystems. UTF-8 is hardcoded deeply in many places.
No need to translate.

**Comment by notspiff** [comment]
uhm. that's new. but also irrelevant since this was the label and not the path.

**Pull request closed without merging**
