### PR TITLE
[binary addons] Fix patch.exe usage on Windows

### PR DESCRIPTION
**Pull request by fetzerch**
Windows UAC requires admin permissions for executables called patch.exe. This installs a manifest which disables that behavior for our binary addons.

Fixes the issue that patches are silently ignored on Windows when UAC is active. (see https://github.com/xbmc/xbmc/pull/8992)

The alternative would be to rename patch.exe to for example p.exe. But that change would require a few `if(win32)`s in some places.

@paxxi: please test locally (with a clean build).
@wsnipex, @Montellese, @MartijnKaijser: This is probably interesting for you. The bug did not appear on jenkins because UAC is disabled on the windows build slave.

### CODE REVIEW

**Comment by afedchin** [comment]
why do not use patch.exe from msys2? it doesn't require high privileges.

**Comment by Paxxi** [comment]
It's not that patch requires admin privilege. This whole mess is a compatibility shim Microsoft added with Vista because installers often used the name and they always assumed everything is writable. So to not break everything Microsoft thought it's a good idea to display the uac if the file is called patch.exe or setup.exe and don't include a manifest

**Comment by wsnipex** [comment]
Wouldn't it make more sense to include the manifest in the downloaded file instead?

**Comment by fetzerch** [comment]
@wsnipex: Sure, in that case we could even include the manifest in the exe so that we don't have to touch the cmake files (http://math.nist.gov/oommf/software-patchsets/patch_on_Windows7.html). Who can help with that?

**Comment by Paxxi** [comment]
finally got around to testing this, works perfectly.
@fetzerch basically just run mt on our current patch.exe and upload somewhere?

**Comment by MartijnKaijser** [comment]
Out on our mirror and download it on each build

**Comment by Paxxi** [comment]
it's up on ftp now, should be on mirrors in around 30? minutes. Renamed archive to not overwrite the old one, it's now patch-2.5.9-7-bin-2.zip

**Comment by fetzerch** [comment]
@paxxi: Works here. Do you think it's worth to add a readme to the package with instructions so that it doesn't get forgotten when the next touches the package?

jenkins build this please

**Comment by Paxxi** [comment]
Yeah that might be a good idea, can try and get it done tomorrow but it'll change the package name again

**Comment by Paxxi** [comment]
@fetzerch new zip uploaded patch-2.5.9-7-bin-3.zip that includes the manifest and a readme.txt

**Comment by fetzerch** [comment]
thanks!
jenkins build this please

**Comment by fetzerch** [comment]
Jenkins addon build error is unrelated --> merging.

**Pull request merged**
