### PR TITLE
[PVR] Feature: PVR Reminders

### PR DESCRIPTION
**Pull request by ksooo**
Here are some pictures hopefully explaining the feature and it's implementation quite well:

Highlights:
+ works with every pvr addon, even if it does not support timers (recordings)
+ no pvr addon changes needed to get this work (I implemented it completely in the core), but if a backend supports reminders, design is prepared for that. I can easily extend the core in case of actual demand.
+ support for one shot reminders as well as for reminder rules (similar to timer rules)

screenshot000
screenshot001
screenshot002
screenshot003
screenshot004
screenshot005
screenshot006

### CODE REVIEW

**Comment by ksooo** [comment]
@Jalle19 if you find some time, could you take a look at the code?

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Comment by shamanNS** [comment]
@ksooo Can this feature be backported to Leia branch?
And be used with pvr.iptvsimple Leia branch (which as far as I could tell was last updated to support PVR API v5.10.1; addon.xml imports v5.10.3 ... for pvr addon v3.8.0)

**Comment by ksooo** [comment]
>  Can this feature be backported to Leia branch?

 No, far to much code changes involved.

**Comment by TehTux** [comment]
@shamanNS Maybe that's something for you: https://kodi.wiki/view/Add-on:KN_Switchtimer_Service

**Pull request merged**
