### PR TITLE
[depends] bump libudfread to 1.1.0

### PR DESCRIPTION
**Pull request by lrusak**
changelog is here: https://code.videolan.org/videolan/libudfread/-/blob/master/ChangeLog

@Paxxi can you please do your thing for windows?

### CODE REVIEW

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
@DaVukovic are you able to test this to make sure bluray ISO's don't break?

**Comment by DaVukovic** [comment]
@lrusak can't complain. Bluray ISO works as expected :+1:

**Comment by Paxxi** [comment]
here you go, it's untested
```
libudfread-1.1.0-x64-v142-20200706.7z
libbluray-1.1.2-arm64-v142-20200706.7z
libbluray-1.1.2-win10-arm64-v142-20200706.7z
libbluray-1.1.2-win10-arm-v142-20200706.7z
libbluray-1.1.2-win10-win32-v142-20200706.7z
libbluray-1.1.2-win10-x64-v142-20200706.7z
libbluray-1.1.2-win32-v142-20200706.7z
libbluray-1.1.2-x64-v142-20200706.7z
libudfread-1.1.0-arm64-v142-20200706.7z
libudfread-1.1.0-win10-arm64-v142-20200706.7z
libudfread-1.1.0-win10-arm-v142-20200706.7z
libudfread-1.1.0-win10-win32-v142-20200706.7z
libudfread-1.1.0-win10-x64-v142-20200706.7z
libudfread-1.1.0-win32-v142-20200706.7z
```

**Comment by lrusak** [comment]
@Paxxi thanks! did the deps get uploaded? Jenkins seems to have an issue
```
08:25:14 libbluray-1.1.2-win32-v142-20200706.7z|Download of http://mirrors.kodi.tv/build-deps/win32/libbluray-1.1.2-win32-v142-20200706.7z failed
```

**Comment by Paxxi** [comment]
Oh, uploaded to the wrong folder, fixed it now. try again in 15-30 minutes and they should be synced.

**Comment by lrusak** [comment]
jenkins build this please

**Pull request merged**
