### PR TITLE
[VideoPlayer/DVDCodecs] add support for Actions video decode hardware Acceleration

### PR DESCRIPTION
**Pull request by sczactions**
@koying 
refer to  AML solutions , we  add Actions video decoder hardware Acceleration

### CODE REVIEW

**Comment by sczactions** [comment]
Dear koying:
    Excuse me, do you  mind having a look ?  I add Actions video decoder hardware Acceleration based on mediacodec.
/cc @koying

**Comment by FernetMenta** [comment]
@sczactions this pr does not even apply because of conflicts. I suggest that you first rebase. Why do you think we should adapt this change to our code base? What systems would benefit from it?

**Comment by sczactions** [comment]
@FernetMenta 
(1)I am sorry，Because of my mistake ,the code had not been rebased to the correct version that cause conflicts. I apologize and regret for any inconvenience caused by our mistake .
(2) I am  working to help increase the KODI APP coverage to include Actions Semiconductor’s  32bit Application Processor.  And are hoping to include this in the mainline so other people using KODI on Actions’ application processors can receive “HW” accelerated benefits.

**Comment by FernetMenta** [comment]
> I am working to help increase the KODI APP coverage to include Actions Semiconductor’s 32bit Application Processor

Please name products using this chip without Android

**Comment by sczactions** [comment]
@FernetMenta  Sorry for late response.First,Please allow me to introduce the products  using Actions Semiconductor’s  32bit/64bit Application Processors.

Android Platform:OTT  box products such as 10moons T2 Quad Core,10moons LT390W YunOS Quad Core and so on. tablet products such as Aino NOVO10 Hero Quad Core,Ainol Novo 9 Spark II,Ainol Novo8 Discovery,Ramos W31 Quad Core and so on;

Ubuntu Platform:Single-Board-Computer products such as LeMaker Guitar based on Actions S500 SoC

**Comment by fritsch** [comment]
@sczactions we have a big mess on linux world by supporting up to 5 different hw accelerators. We don't want to do that on Android at all. Kodi will only support Mediacodec in the future so every platform that wants to run kodi in a proper way needs to support _the_ standard Android video acceleration API, which is mediacodec.

**Comment by FernetMenta** [comment]
Regarding Android it's like fritsch mentioned but for Linux this could be a nice addition. Would you actively maintain this codec in case we integrate it?

**Comment by sczactions** [comment]
@FernetMenta  First, Thank you very much for sparing your precious time to Follow up on this issue. OTT box ,tablet and Single-Board-Computer products using  Actions Semiconductor’s 32bit/64bit Application Processors is under fast development ,and  because of kodi's Excellent user experience ,productors using Actions Semiconductor’s 32bit/64bit Application Processors  have a strong desire to Perfectly support Kodi  hw accelerators.I will be very appreciative if it can be integrated and will actively maintain this codec in the future.

**Comment by MartijnKaijser** [comment]
Please drop anything android related because we will not accept anything else than standard MediaCodec. So all code additions must be linux only so I guess you can also drop the setting additions as it should be auto detected. Secondly you changed the file permissions so please revert those.

**Comment by stefansaraev** [comment]
from what I can find online (and it's not much) this actions thing looks like android-only, anyway. 

does it support anything non-android, @sczactions ?

**Comment by sczactions** [comment]
@stefansaraev   Sorry for late response.now is android-only.In the futurn , I will make it to support 
linux

**Pull request closed without merging**
