### PR TITLE
[cmake] refactor addon bindings

### PR DESCRIPTION
**Pull request by wsnipex**
refactor definition, install, copying of addon bindings/headers

- old addon-bindings.mk was a relic from autotools
- move to cmake syntax
- unify definition of addon bindings/headers in a single file
- remove duplication in install script
- allow including whole directories

## Motivation and Context
Cleanup and new functionality

## How Has This Been Tested?
only on linux -  and not thoroughly 

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

ping @AlwinEsch @hudokkow  @Rechi @FernetMenta

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build this with addons please

**Comment by wsnipex** [comment]
jenkins build this with addons please

**Review by Rechi — APPROVED** [review]

**Review by hudokkow — APPROVED** [review]

**Comment by FernetMenta** [comment]
thanks!

**Comment by wsnipex** [comment]
updated: also move kodi-addon-dev-kit handling to AddonBindings.cmake

jenkins build this with addons please

**Pull request merged**
