### PR TITLE
[confluence] Show user rating in info

### PR DESCRIPTION
**Pull request by razzeee**
Shows the user rating in the DIalogVideoInfo list.
@ronie 

Also a small cleanup for an obsolete declaration

### CODE REVIEW

**Comment by mkortstiege** [comment]
I've not runtime tested this, but won't adding the user rating label lead to a scrolling in the info area?

**Comment by Razzeee** [comment]
That's probably dependent on your display and how much data the scraper can gather. The one that seems at the limit is movies.
!http://i.imgur.com/nlqryaN.png!

!http://i.imgur.com/puBdJXu.png!

**Comment by mkortstiege** [comment]
Found a scenario where at least one existing item falls out of the actual info area.

screenshot001

I had to switch to preferred language `de` in order to get the original title. Looks like we need to re-layout the info dialog if we want to show user ratings as `path` is on next page and there's not scroll indicator.

**Comment by Montellese** [comment]
Why don't we combine it with the `Rating` row?

**Comment by Razzeee** [comment]
I like @Montellese idea, but I don't know how we can make clear which is which.

**Comment by phil65** [comment]
If we show the user rating, then we should also add a button to set that rating. The user rating label could perhaps get moved to the button control label in that case

**Comment by Razzeee** [comment]
Yes, but as of now the video db info is just a list. And from my limited skinning skills I would assume, that you can't have buttons in a list?
The music db info screen is done without a list and seems like the items are placed by hand.

**Comment by phil65** [comment]
atm the info part is a list container, and you can also assign <onclick> actions to the items.
My idea was to move "set rating" to the horizontal menu though.

**Comment by Razzeee** [comment]
So should I edit this to be just the cleanup?

**Comment by phil65** [comment]
I´d say let´s wait for @ronie or someone else with an opinion on this.

**Pull request closed without merging**
