### PR TITLE
Make artist count aware of the include compilation artist setting

### PR DESCRIPTION
**Pull request by razzeee**
Before this the artist count generated by core is "wrong" when you hide all compilation artists from the music library.
So you end up with this count not matching the amount of artists in the artists listing.

I also included a code modernization, which can be dropped, if it's not liked.

### CODE REVIEW

**Comment by DaveTBlake** [comment]
Maybe it is just my age, but I find all those "auto" less easy to read. I have to think what the var type is rather than the person that coded it! But good catch with the query.

**Comment by phate89** [comment]
I understand the use of auto but usually it's used when you have a return value from a not too clear function. Replace for example int i=0 seems too much for me

**Comment by Razzeee** [comment]
Well it really depends on which way we want to go. I actually use it everywhere you can, as it's quiet clear from the right side what type it will be.

I would be interested in the opinions of
@Paxxi and  @Montellese

**Comment by Jalle19** [comment]
I wouldn't use auto for strings, ints and booleans, only for user-defined types.

**Comment by Montellese** [comment]
I mainly use `auto` for stuff like vectors, maps, iterators etc where it's a lot of work to write the type and where it would be a lot of work when the type changes in the future.

Personally I wouldn't use it for builtin types and `std::string` et al. either but that's probably down to personal preference unless we nail it down in our coding guidelines.

**Comment by Razzeee** [comment]
So let's nail it down in the guidelines?

**Comment by tamland** [comment]
when in doubt, consult core guidelines https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es11-use-auto-to-avoid-redundant-repetition-of-type-names

**Comment by Paxxi** [comment]
I feel that any return value assignment are fair game for use of auto. This can remove a source of type mismatch, e.g assigning size_t to unsigned int and it's fairly easy to know the type. Using it when declaring int, float or double could cause confusion if not familiar with the type deduction rules. 
It's not clear that auto I = 0; is an int32_t and that auto i=1.0 is a double and not a float

**Comment by Razzeee** [comment]
I've taken the ```auto``` stuff down a notch. Hopefully it's okay like that.

**Comment by Razzeee** [comment]
let's see if it builds everywhere
jenkins build this please

**Comment by Razzeee** [comment]
Builds are fine, just the obligatory addon fail on windows.

I would like to merge this, so speak up if somebody has any problems with how the code is.

**Pull request merged**
