### PR TITLE
VAAPI/VDPAU: check settings value again, not status

### PR DESCRIPTION
**Pull request by mglae**
## Description

Fix #18837 changing GetBool() to IsEnabled()

## Motivation and Context

VAAPI MPEG2 acceleration cannot disabled any more.

## How Has This Been Tested?

Linux Kodi X11 on AMD GPU.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
Probably fine. Likely this needs to be fixed in a couple places.

**Comment by mglae** [comment]
One place I see in VDPAU. Do you have other places in mind?

**Comment by fritsch** [comment]
Please add the VDPAU if possible.

**Comment by mglae** [comment]
Done.

**Review by lrusak — APPROVED** [review]
LGTM

**Pull request merged**
