### PR TITLE
[cmake] fix binary addon builds on Leia

### PR DESCRIPTION
**Pull request by phunkyfish**
## Description

Fixes broken binary addon builds on Leia caused by: https://github.com/xbmc/platform/pull/5

It's a backport of: https://github.com/xbmc/xbmc/pull/16417

## How Has This Been Tested?

Tested on OSX, addons would not build before this change and build afterwards.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by phunkyfish** [comment]
@Rechi hope this is the correct change to fix this.

**Comment by Rechi** [comment]
This isn't correct, as Leia doesn't need the darwin_embedded checks.

**Comment by phunkyfish** [comment]
True, but what is the right way of fixing this?

**Comment by phunkyfish** [comment]
Would you mind also explaining why the old git reference for p8-platform stopped working for Leia?

Learning exercise.

**Comment by phunkyfish** [comment]
Could we just create a release for Leia and update the reference to that?

**Comment by phunkyfish** [comment]
https://github.com/xbmc/xbmc/pull/16425

**Comment by phunkyfish** [comment]
If anytime a commit is made to p8-platform it breaks Leia even this temporary fix doesn’t make a lot of sense as it will just break again.

**Comment by phunkyfish** [comment]
We added darwin_embedded checks to a number of addons to allow them to work for both Leia and Matrix.

Why is this any different @Rechi?

**Comment by phunkyfish** [comment]
Jenkins build this please

**Comment by Rechi** [comment]
It was added for add-ons in the Leia branch, so one only has one branch, but it would still work without the change in Leia branch for Leia.

**Comment by phunkyfish** [comment]
Ok thanks. Any guidance on what the best way to fix this is?

**Comment by phunkyfish** [comment]
I’m still stumped on how to fix this 😉

**Pull request closed without merging**
