### PR TITLE
Reorganize FindVAAPI.cmake

### PR DESCRIPTION
**Pull request by lrusak**
Correctly search libva-* libs and include dirs for the current platform.
va-drm should probably also be conditional, but I am unsure which
platforms need it.

The imported VAAPI::* targets were never used and have been removed
for simplicity.

@pkerling I hope it's ok for me to pick your commit and PR it and change the commit and commit message a little bit. The original commit is here, https://github.com/pkerling/xbmc/commit/fc0c133f4f9a743d46844ba4ace50101c8e9031b

### CODE REVIEW

**Review by FernetMenta — APPROVED** [review]
looks good to me

**Comment by pkerling** [comment]
@lrusak sure it's ok, less work for me ;-)

**Review by hudokkow — APPROVED** [review]
I'm fine with this.
I guess we'll update the module as more platforms go in, namely wayland.

**Comment by hauihau** [comment]
@lrusak: Looks like there is a typo in https://github.com/xbmc/xbmc/blob/master/cmake/modules/FindVAAPI.cmake#L28. There is a lower case "x" which leads to -lva-x11 not being added to the libraries resulting in undefined references to vaGetDisplay while linking kodi.bin. Changing it to an upper case "X" fixes the issue.

**Comment by lrusak** [comment]
@hauihau thanks for pointing that out, I'll PR a fix

**Comment by bh** [comment]
I have an similar issue while linking `kodi.bin`:

Arch Linux x86_64
GIT Head is commit b43d766dd864cc27d8eedcf340b59ab6a1a9e68b:

```
build/windowing/X11/windowing_X11.a(WinSystemX11GLContext.cpp.o):WinSystemX11GLContext.cpp:function CWinSystemX11GLContext::RefreshGLContext(bool): error: undefined reference to 'vaGetDisplay'
build/windowing/X11/windowing_X11.a(WinSystemX11GLContext.cpp.o):WinSystemX11GLContext.cpp:function CWinSystemX11GLContext::GetVaDisplay(): error: undefined reference to 'vaGetDisplay'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/kodi.dir/build.make:458: kodi.bin] Error 1
make[2]: Leaving directory '/home/bhe/builds/kodi-git/src/xbmc'
make[1]: *** [CMakeFiles/Makefile2:280: CMakeFiles/kodi.dir/all] Error 2
make[1]: Leaving directory '/home/bhe/builds/kodi-git/src/xbmc'
make: *** [Makefile:141: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

**Pull request merged**
