### PR TITLE
[PVR] Fix grid container model access with invalid index in CGUIEPGGridContainer::GetDescription().

### LINKED ISSUE #18256: Opening EPG (pvr.hts) with *assumed* faulty skin crashes matrix
### Describe the bug
Here is a clear and concise description of what the problem is:

while with skins estuary, rapier, quartz everything is fine, opening the epg with skin aeon.nox.silvo crashes kodi.
i stumbled over this while testing addon-updates with different skins.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

epg should open correctly and not crash kodi

## Actual Behavior

kodi crashes

### To Reproduce
1. install skin aeon.nox.silvo from official repo to current master
2. open live-tv via main menu (mypvrchannels opens)
3. switch to the epg via sidebar

### Debuglog

latest records before the crash:
```
2020-08-05 21:36:51.609 T:3083     INFO <general>: initializing python engine.
2020-08-05 21:36:52.016 T:3083     INFO <general>: CPythonInvoker(16, /var/lib/matrix/.kodi/addons/script.skinshortcuts/default.py): script successfully run
2020-08-05 21:36:52.037 T:3083     INFO <general>: Python interpreter stopped
2020-08-05 21:36:53.625 T:2537     INFO <general>: Loading skin file: custom_1126_Confirm.xml, load type: KEEP_IN_MEMORY
2020-08-05 21:36:57.615 T:2537     INFO <general>: Loading skin file: MyPVRChannels.xml, load type: KEEP_IN_MEMORY
2020-08-05 21:37:00.983 T:2537     INFO <general>: Loading skin file: MyPVRGuide.xml, load type: KEEP_IN_MEMORY
2020-08-05 21:37:01.011 T:2537    ERROR <general>: GetGridItemPtr: Requested EPG tag (0, 6) outside grid boundaries!


############### END LOG FILE ################

############ END Kodi CRASH LOG #############
```

maybe `GetGridItemPtr: Requested EPG tag (0, 6) outside grid boundaries!` is a starting point

### Your Environment
Used Operating system:

 - [X] Linux

 - Operating system version/name: Debian Stretch
 - Kodi version: current master https://github.com/xbmc/xbmc/commit/da34f16569aba4ca71b5ffcd59a489f004163c35 pvr.hts 7.1.1 built from source

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
Fixes #18256 

Runtime tested on macOS, latest Kodi master + pvr.demo.

@phunkyfish mind looking at the code change?

@ronie , @howie-f fyi

### CODE REVIEW

**Review by phunkyfish — APPROVED** [review]
👍, thanks for the quick fix.

**Comment by howie-f** [comment]
that was really quick, thanks a lot

**Comment by ronie** [comment]
thx, can confirm the crash is fixed now.

**Comment by ksooo** [comment]
WIN-32 Jenkins error is unrelated.

**Pull request merged**
