### PR TITLE
[addons] add / fix binary addon gui parts

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description

This request include some fixes and improvement of the binary addon GUI interface. Found this by development of the web browser addon system and also good to have for all.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ksooo** [comment]
No api version bump???

**Comment by AlwinEsch** [comment]
There is nothing changed on GUI, only a fix to check used headers. The version on audio engine is changed.

**Comment by AlwinEsch** [comment]
Ah forgeot was on wrong request

**Comment by AlwinEsch** [comment]
jenkins build this please

**Pull request merged**
