### PR TITLE
Update libmicrohttpd package, use static lib for win32

### PR DESCRIPTION
**Pull request by Karlson2k**
Replace outdated for years MHD package with latest one.
As it compiled by VS, it's possible to use static package that resolves part of dll hell and reduces total size of application (unused parts of MHD code are excluded by compiler).

### CODE REVIEW

**Comment by Montellese** [comment]
Any reason why you didn't take a specific release (e.g. 0.9.37 which is used by latest Ubuntu stable) or 0.9.39? Did you use any specific flags to build this or does it come with HTTPS support etc?
We also may have to update the installer to remove the old `system/webserver` directory which doesn't seem to be used anymore.

IMO we should also bump the version used in depends so that most Kodi installs use the same version.

**Comment by Paxxi** [comment]
+1 for static lib. I agree with @Montellese though that we should probably pick a released version and not from svn.

**Comment by Karlson2k** [comment]
As MHD developer, I ported MHD to Visual Studio. I did it before 0.9.39 release, but forgot to add VS files to `EXTRA_DIST` so those files are missing in 0.9.39 tarball.
HTTPS for autotools MHD builds can be disabled by `configure --disable-https`. For VS builds HTTPS currently is not supported.

**Comment by Montellese** [comment]
Aw that's a shame. The main thing I was looking forward to with a new MHD version was HTTPS support.

**Comment by MartijnKaijser** [comment]
so any objections for merging this and see what it leads to for the next couple of weeks?
Should other platforms be bumped as well to 0.9.39 at least?
jenkins build this please

**Comment by Montellese** [comment]
IMO we should get as many platforms to the same version as possible. The code should be able to handle multiple versions but it makes debugging a lot easier if all platforms use a similar version.

**Comment by Karlson2k** [comment]
We can update to 0.9.39 for all platforms - no breaking changes.
I can also rebuild win32 from svn 0.9.39, but I changes from 0.9.39 are minimal.

@Montellese For proper HTTPS support we have a choice: use MinGW builds (I don't like it, bad compatibility with app's CRT lib), port GnuTLS to VC (and all depends) - not really easy or port MHD to OpenSSL support. I will think about last option.
Why do you need HTTPS? HTTP is ok for local control.

**Comment by MartijnKaijser** [comment]
wasn't openssl an issue for using? iirc some one mentioned that but don't know in what context

**Comment by Montellese** [comment]
I consider using Basic Authentication over HTTP a crime because the username and password are sent to the server unencrypted so it's not really any "protection" at all. So giving our users the possibility to define a username and password is giving them a false impression of "security".

**Comment by Memphiz** [comment]
btw - airplay uses digest auth over http for the password feature. Its definitly better then basic auth and doesn't need ssl support (and its kinda easy to implement - see CAirPlayServer::CTCPClient::checkAuthorization).

**Comment by Memphiz** [comment]
this is the server side of authentication of course...

**Comment by Paxxi** [comment]
@Karlson2k can't you steal libcurls ssl abstraction layer? It works with everything, even windows schannel api, that way we can use it in microhttpd and ffmpeg so we don't have to bother with openssl or gnutls on win32

**Comment by MartijnKaijser** [comment]
so lets bump all platform to mentioned revision so we can get the outdated lib updated this window for proper testing?

**Comment by Paxxi** [comment]
what's the status on this, is it on track to be merged for alpha2?

**Comment by MartijnKaijser** [comment]
jenkins build this please 
If no one is going to object this will be merged in a week

**Comment by Karlson2k** [comment]
Will replace test versions with single revision from SVN for all platforms.

**Comment by Karlson2k** [comment]
One unified revision for all platforms. No need for custom patches anymore.

jenkins build this please

**Comment by MartijnKaijser** [comment]
mirror wasn't synced yet i think
jenkins build this please

**Comment by Montellese** [comment]
Since the win32 version of libmicrohttpd doesn't support SSL/TLS you could also disable it for the one built with depends. We aren't using it anyway in Kodi.

**Comment by Karlson2k** [comment]
@Montellese Can be done in other commit/PR. 
If somebody will start working on HTTPS support, I'll try to update win32 version of libmicrohttpd to support HTTPS in VS port.

**Comment by Montellese** [comment]
I already had HTTPS support working more than two years ago but back then we didn't have depends so it wasn't really an option to update libmicrohttpd for non-win32 to a version that properly supported HTTPS so it never got anywhere. That's why I asked in this PR before if this supports SSL/TLS.

**Comment by Karlson2k** [comment]
Added more general fixes for POSIX depends.

jenkins build this please

**Comment by Karlson2k** [comment]
OSX64 fail is unrelated, the rest is fine.
Additionally fixed one more lib, that uses libgrypt.

**Comment by Karlson2k** [comment]
If everybody are happy with it, I'll merge it today.

**Comment by Montellese** [comment]
There seems to be an issue with stopping the MHD daemon(s). At least on WIN32 it takes 120 seconds (probably some timeout).

**Comment by Memphiz** [comment]
Its even worse on linux64 - stopping the webserver never happend this night when the tests were run. Its fine on osx though. @Karlson2k any chance you could have a look? Else i need to disable webserver tests for osx too which would be uncool.

**Comment by Karlson2k** [comment]
@Montellese @Memphiz 
I'll check it.

**Comment by Karlson2k** [comment]
Just to inform: I'm working on it. As workaround - disabled THREAD_PER_CONNECTION solve the problem.

**Comment by Karlson2k** [comment]
See PR #6892.

**Pull request merged**
