### PR TITLE
fixed: Enable retry without range set for e.g. broken HDHomerun servers (fixes #14204)

### PR DESCRIPTION
**Pull request by arnova**

### CODE REVIEW

**Comment by NedScott** [comment]
With this PR, I am now able to open HDHomeRun UPnP links again.

**Comment by arnova** [comment]
@NedScott : Thanks for testing. @MartijnKaijser : I assume we want this for 15.2 or is it too late ?

**Comment by MartijnKaijser** [comment]
Not too late

**Comment by arnova** [comment]
jenkins build and merge please

**Comment by NedScott** [comment]
Backport needed?

**Comment by arnova** [comment]
@NedScott : There's already a PR for Isengard : https://github.com/xbmc/xbmc/pull/7930

**Pull request merged**
