### PR TITLE
VideoPlayer: fixup flush after  cdd5417611ddce737fef6008a6a67ebad84be67a

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

### CODE REVIEW

**Comment by boot2k3** [comment]
This change broke AML in CVideoPlayer::OnLostDisplay() again. After cdd5417 it was fixed.

**Comment by FernetMenta** [comment]
get lost. CoreElec members are not welcome here

**Comment by adamg88** [comment]
Why is that? Because we always point out how your shitty PRs always break something?

**Comment by FernetMenta** [comment]
I quote Adam Green @adamg88

> Why is that? Because we always point out how your shitty PRs always break something?

If you say my PRs are shitty, you also say that entire video player and audio engine are shitty. Why don't you write your own player instead of just raping our code.

**Pull request merged**
