### PR TITLE
DVDDemuxFFmpeg: Fix issues after st->cur_pts replacement part 2

### PR DESCRIPTION
**Pull request by popcornmix**
## Description
Fix issues after st->cur_pts replacement part 2

## Motivation and context
The move to ffmpeg5 removed st->cur_pts which kodi was using in a number of places.

The part 1 fixup fixed issues with resuming a PVR stream, but issues with no audio or video remained.

## How has this been tested?
Live TV and playback from local files seem fine.

## What is the effect on users?
Fixes issues described in https://github.com/xbmc/xbmc/issues/23199 and https://github.com/xbmc/xbmc/pull/23557

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by popcornmix** [comment]
@enen92 does this PR help your PVR no video case?

**Comment by enen92** [comment]
@popcornmix yes, works great!

**Comment by popcornmix** [comment]
@enen92 I've added a commit to ensure m_currentPts is valid after a seek - let me know if that is okay for you.

@FernetMenta are you happy with these commits?

**Comment by enen92** [comment]
Yes, still works :)

**Comment by FernetMenta** [comment]
> @enen92 I've added a commit to ensure m_currentPts is valid after a seek - let me know if that is okay for you.
> 
> @FernetMenta are you happy with these commits?

Looks good.

**Review by enen92 — APPROVED** [review]
Fixes the regression with my Pvr channels

**Comment by enen92** [comment]
Jenkins build this please

**Comment by popcornmix** [comment]
@FernetMenta I don't think the calls to `Read()` behave as we discussed.
I was under impression that avoiding setting `m_pkt.result = -1` would allow that packet
to be reused on a subsequent call to `Read()`, to avoid the loss of a useful frame.

But in `Read()` [here](https://github.com/xbmc/xbmc/blob/efe703a063e10b8bbe0493c0c88b75805364c875/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp#L1185) we invalidate the packet preventing it from being used again.

This means we typically lose an I frame after seeking which is not good.

**Comment by FernetMenta** [comment]
@popcornmix you are right. Sorry, I seem not to remember the details anymore. The mechanism for saving packets was implemented to handle stream changes. Maybe you could slightly change Read() in a way that it handles requests to timestamps and saves the packet for that purpose similar as streamchange does.

**Comment by FernetMenta** [comment]
Looks like you already have done that 👍

**Pull request merged**
