### PR TITLE
[Util] Generalize external subtitle retrieval method(s).

### PR DESCRIPTION
**Pull request by ace20022**
I need this for external audio files and maybe for chapter files.
@mkortstiege Could you please have a look/ review it?
I have not fully tested it for regressions...

### CODE REVIEW

**Comment by mkortstiege** [comment]
Looks good. Will runtime test this later today.

**Comment by ace20022** [comment]
> I wonder if we should stop searching once we found a valid subtitle directory. If we agree we should do it outside of this PR since it's changing behavior.

Agree, 1 sub dir should be enough.

**Comment by mkortstiege** [comment]
+1. Works as intended.

**Comment by ace20022** [comment]
Thx for the review!

jenkins build this please

**Comment by hudokkow** [comment]
jenkins build this please

**Pull request merged**
