### PR TITLE
[gui] CGUIDialogYesNo warnings

### PR DESCRIPTION
**Pull request by ace20022**
@xhaggi for review

### CODE REVIEW

**Comment by Paxxi** [comment]
Thanks @ace20022, this warning has been bugging me a while :)

**Comment by xhaggi** [comment]
looks good

**Comment by ace20022** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Comment by mkortstiege** [comment]
Build error is unrelated.

**Pull request merged**
