### PR TITLE
[backport][Leia] automatic doxygen generation

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description

Backport about #20511

On Leia only added to become created docs complete in uploaded versions.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ksooo** [comment]
A PR for Leia? Leia is EOL.

**Comment by AlwinEsch** [comment]
> A PR for Leia? Leia is EOL.

See note above "On Leia only added to become created docs complete in uploaded versions."

Is to have something like this https://alwinesch.github.io/usergroup0.html possible.

**Comment by enen92** [comment]
Either way, I think Leia can be skipped. Why not storing docs since matrix only?

**Comment by AlwinEsch** [comment]
Okey Dokey :sweat_smile:

**Pull request closed without merging**
