### PR TITLE
[gcc] fix gcc 4.6 compiler error introduced by #6828

### PR DESCRIPTION
**Pull request by xhaggi**
@wsnipex ping

### CODE REVIEW

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
thanks @xhaggi

**Comment by xhaggi** [comment]
@notspiff thanks, thought the same but ended up with this overload. will change it back ;)

**Comment by xhaggi** [comment]
@notspiff done .. jenkins build this please

**Comment by xhaggi** [comment]
same here, build failures are unrelated due to github outages

**Pull request merged**
