### PR TITLE
[backport] [cmake] Platform specific overrides

### PR DESCRIPTION
**Pull request by fetzerch**
Backport of https://github.com/xbmc/xbmc/pull/10918

### CODE REVIEW

**Comment by fritsch** [comment]
jenkins build this please please

**Comment by FernetMenta** [comment]
@fritsch see my comments on the PR to master

**Comment by fritsch** [comment]
@FernetMenta seen it, though wondering as the proposed idea is the same currently already used for the Factory stuff.

**Comment by FernetMenta** [comment]
@fritsch right, it does not fit there either and it does not fit for other things, see my comment on the Mir PR. "linux" does not sufficiently define a platform in the context of the requirements we have here. X11, Mir, Wayland define the platform

**Comment by fetzerch** [comment]
I don't see the relation to this PR. This one is if you have a header with defines specific for a platform.

The other problem is that you want to select a certain cpp depending on a variable. And that we have in several places with different variables. X11, Mir, Wayland is one part of the equation. Just 2 other random examples: https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/CMakeLists.txt and https://github.com/xbmc/xbmc/blob/master/xbmc/cores/AudioEngine/CMakeLists.txt. Not sure if this problem is really generic enough to handle that in a cmake macro. Also I think we're missing a generic concept of options that are exclusive (such as wayland, x11) or where you can have multiple options enabled (such as VDPAU/VAAPI, or ALSA/PA).

The impact for this PR is that we need to think what to do if we have several vars instead of just the platform.

**Comment by FernetMenta** [comment]
Your links make the problem obvious too. X11, vaapi, vdpau are no options but currently they are treated as options by macros like FOUND_X11. Those components do define a platform/port.

**Comment by fritsch** [comment]
Do we want to split? Krypton - which is "gone" anyways and future master?

**Comment by FernetMenta** [comment]
I don't think so, otherwise we cold have gone with the ifdef from the beginning

**Comment by fetzerch** [comment]
The "platform" variable in cmake can't be changed without rewriting huge parts. They define for example how installation or packaging is done. We can have (a) new variable(s) for this. But we have to sort out all the 'options' before and that's going to take a while.

**Comment by FernetMenta** [comment]
ok, then go ahead with this for k

**Comment by fritsch** [comment]
jenkins build this please

**Comment by fritsch** [comment]
Thanks very much.

**Comment by stefansaraev** [comment]
the backport PR is exactly 2 days old. not 2 months. if you disagree to the ifdef, this can be reverted.

**Comment by FernetMenta** [comment]
sure, it has to be reverted. I just commented on the ifdef.

**Pull request merged**
