### PR TITLE
VideoPlayer: catch silly CRedirectException, fixes crash

### PR DESCRIPTION
**Pull request by FernetMenta**
fix http://trac.kodi.tv/ticket/16874

We really should not deal with C++ exceptions as long catch blocks can't be forced.

@MilhouseVH /cc

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Tested on RPi2, problem appears to be fixed - thanks.

**Comment by arnova** [comment]
@FernetMenta : IMHO the proper fix for this should not use CCurlFile open/close to het the final URL but just have a separate function in CCurlFile (without the exception part) giving us the final URL. Seems much cleaner ?

**Comment by FernetMenta** [comment]
@arnova not sure what exactly you are proposing. Do you have time to do this?

**Comment by arnova** [comment]
@FernetMenta : Working on it. I think in half an hour or so.

**Comment by arnova** [comment]
@FernetMenta : What I had in mind doesn't seem that straightforward after all. But it still feels like we shouldn't be bothered with handling such exceptions at this level?

**Comment by FernetMenta** [comment]
@arnova not sure if I got your question. What level do you mean?

**Comment by arnova** [comment]
VideoPlayer level. The redirect was implemented as a hack for IFile, therefor it's handled there. Anything else not going through IFile, requires special treatment which sucks imho.

**Comment by FernetMenta** [comment]
yes, VideoPlayer only need to catch the error.
Are you ok with this PR now?

**Comment by arnova** [comment]
I think I can live with it ;-), although as *pretty* as I would like (note: can't think of anything else atm)...

**Comment by FernetMenta** [comment]
@arnova thanks. still enough work to keep you busy in the future :)

**Pull request merged**
