### PR TITLE
Inject CPPFLAGS (e.g. to disable FORTIFY)

### PR DESCRIPTION
**Pull request by atupone**
I need this to inject CPPFLAGS from the distribution script in order to disable FORTIFY_SOURCE

### CODE REVIEW

**Comment by Jalle19** [comment]
Ping @wsnipex perhaps?

**Comment by wsnipex** [comment]
CPPFLAGS should be appended after INCLUDES(which are the ancient deprecated version of AM_CPPFLAGS) on the actual compiler invocation, so they can always override.

please also provide more details why you need this. Sounds like you want to override stuff that your build system injects?

**Comment by atupone** [comment]
I want to add FORTIFY_SOURCE=0 with something like that

CPPFLAGS=-DFORTIFY_SOURCE=0 ./configure

configure already provide the usage of CPPFLAGS but seems that is not used.

gcc that my system (gentoo) provides use by default fortify but I can change with precompiler options

If there are other way to add things to INCLUDES I'm glad to know

**Comment by wsnipex** [comment]
As I said, CPPFLAGS should be added after all other flags on the actual compiler invocation, not in DEFINES.

**Comment by atupone** [comment]
I understand now what you mean. You want I change the commit to do that. I will soon

**Comment by MartijnKaijser** [comment]
@wsnipex ping

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
strange, addons failed on rpi. Not sure how this could be related
jenkins build addons please

**Pull request merged**
