### PR TITLE
[Jarvis][travis-ci] Add travis linux support

### PR DESCRIPTION
**Pull request by hudokkow**
Backport of https://github.com/xbmc/xbmc/pull/9047

### CODE REVIEW

**Comment by hudokkow** [comment]
Missing boost and some other libs. Investigating.

**Comment by hudokkow** [comment]
All green and squashed.

**Comment by MartijnKaijser** [comment]
@hudokkow if you're bored we also have some audioencoder in our git ;)

**Comment by hudokkow** [comment]
I'm not bored... I have a 5 month old daughter... and a wife that just got promoted to mom, if you know what I mean.
Translation: my free time isn't actually mine nowadays. How I miss a few :beers:

**Comment by MartijnKaijser** [comment]
hahaha just kidding :)
Go drink beer

**Comment by hudokkow** [comment]
I think I missed a :grinning: in my previous comment.
Yes, I'll look into it! After pvr. json depends are killing me.

**Pull request merged**
