### PR TITLE
[binary addons] fix/support ZIP packaging

### PR DESCRIPTION
**Pull request by Montellese**
These commits add/fix support for packaging built binary addons into a ZIP archive. Most of the functionality has already been provided by @notspiff and the rest I "stole" from his other cmake scripts after some kind pointers from him.
With these changes it is possible to extecute the `package-addons` or any of the `package-<addon-id>` targets on the generated build files to package all or a specific addon that has previously been built.

There are two things that need attention:
- The fixed path in https://github.com/xbmc/xbmc/compare/xbmc:master...Montellese:cmake_addons_packaging?expand=1#diff-b100f554dc9c53a628bcf373a545eda9R289 looks very ugly but I couldn't find a variable that would provide this path.
- Where should the generated ZIP files be copied/installed to? I used CMAKE_INSTALL_PREFIX for now (see https://github.com/xbmc/xbmc/compare/xbmc:master...Montellese:cmake_addons_packaging?expand=1#diff-88c873338ed1cc64c771fdefc1f40754R15) but I'm pretty sure that that's the wrong location for linux/depends. It's also not the proper location for win32 but it was the easiest for now. This will most likely only be something used by jenkins to upload the ZIP archives to our mirrors.

I had to bump the audioencoder addons because they were missing `include(CPack)`. @notspiff: Is there a reason why this include is not in `addon-helpers.cmake`?

### CODE REVIEW

**Comment by notspiff** [comment]
Sadly cpack needs to be included after the build_addon call(s) or it will be a nop.

**Comment by Montellese** [comment]
@notspiff: I've just tried the following:
* I removed the `include(CPack)` line from `audioencoder.wav`'s `CMakeLists.txt`
* I added `include(CPack)` at the very end of `build_addon()`
* I built `audioencoder.wav`
* I executed the `package-addons` target introduced by this PR

and everything worked fine. I remembered that we do something similar at work as well i.e. packing all the CPack related logic (including the call to `include(CPack)`) into a method and call that method from the different service buildsystems.

**Comment by notspiff** [comment]
yed. now try something outputting multiple addons.

**Comment by wsnipex** [comment]
please create a new dir for the addon zips, e.g. ${ADDON_INSTALL_DIR}/zips

**Comment by Montellese** [comment]
@wsnipex: Yeah I was wondering if we should stuff it into `${BUILD_DIR}/zips` or if we should introduce an additional variable for it (but we'd have to pass it through all the different externalproject calls).

**Comment by wsnipex** [comment]
just pass BUILD_DIR to BUILD_ARGS and it will be available

**Comment by Montellese** [comment]
Yes I know but before doing that I was wondering if we should provide an additional variable for it (which could default to `${BUILD_DIR}/zips`) or not.

**Comment by Montellese** [comment]
Added a commit that introduces the `PACKAGE_DIR` variable which defaults to `${BUILD_DIR}/zips` and is passed to the addon's buildsystem.

**Comment by wsnipex** [comment]
looks good, the option makes sense

**Comment by Montellese** [comment]
jenkins build addons please

**Comment by Montellese** [comment]
All worked fine except linux which had an unrelated error. Triggered another linux binary addons build manually.

**Comment by Montellese** [comment]
linux is fine as well: http://jenkins.kodi.tv/job/BINARY-ADDONS/258/platform_label=linux64/

**Pull request merged**
