### PR TITLE
[settings] Promote hideemptyseries to GUI setting.

### PR DESCRIPTION
**Pull request by ghost**
This promotes `videolibrary.hideemptyseries` from an advanced setting to a GUI
one.  This is enabled by default.
## 

See https://github.com/xbmc/xbmc/pull/5752#issuecomment-68108700 and below. This is valid even without 5752.

Please note that **default value is changed** from false to true. I'm fine if you want it reverted.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
In some ways this setting might work better as a "Blade" setting (Misc Options), within the TV shows library - this would make enabling/disabling easier, and might also address the issue Montellese raises in the previous post.

Though presumably because it impacts JSON results, which is what this PR and #5752 attempt to address, it has to be a "System Setting"?

**Comment by Montellese** [comment]
@MilhouseVH: Yeah it would probably be better off as a side menu setting but as you said it also affects other areas like whether tvshows are removed during clean library etc. IMO this has to be split up into separate settings. One would be a toggle in the library view to show/hide empty tvshows. The other would be in the video library settings and would cover what to do with empty tvshows during library cleaning.

**Comment by anaconda** [comment]
It's official - I can't find a way to migrate advanced settings to the GUI. Either it has always priority over the GUI setting (you toggle it in GUI, restart and then realize it's ignored because as.xml has the opposite value), or GUI has always priority over as.xml. I can't see how it'd be possible to only "import" the value in as.xml only once.
Even `IsDefault()` doesn't help here, if the user had `true` in as.xml but then changed his mind and now wants the GUI setting to be set at the default value.

So my proposal:
* add "Keep TV shows without episodes when cleaning the library" in Video -> Library, default is false. (Again, I'd remove that completely. Users should delete it from the filesystem - see comment above.)
* add "Hide empty TV shows" to the side blade, in library view. Default is true (makes sense to me, but I'm ok if you want it false) and we don't migrate anything. I've verified that side blade settings are accessible via JSON-RPC.
* kill `hideemptyseries` in as.xml right now, otherwise both ways to achieve the same result would confuse people when it'll be removed.

**Comment by HitcherUK** [comment]
RE add "Keep TV shows without episodes when cleaning the library" in Video -> Library, default is false. (Again, I'd remove that completely. Users should delete it from the filesystem - see comment above.)

I'm sure I'm not the only who has plenty of empty tv show folders - the reason being you may have watched a season and are waiting for the next to air. If you remove the tv show folder then SickBeard will not make a new one when there are more episodes available. Also when you add a  new show to SB it will make a tv show folder ready for when there's episodes to go in it.

Thanks.

**Comment by anaconda** [comment]
Currently empty TV shows (empty = no episodes) are removed silently, so artwork etc are lost. In Helix they're kept if `<video><hideemptyseries>true</hideemptyseries></video>` is added to advancedsettings.xml, but that doesn't work if you want them shown in the library.

So, just to fully understand your comment: will you be fine if there's no setting, but they're kept by default and are only removed if the TV show directory doesn't exist?

**Comment by HitcherUK** [comment]
Correct, thanks.

**Comment by Montellese** [comment]
OK I think only removing TV shows during clean library if the tvshow folder is gone sounds sane (i.e. without a setting). And moving the "Hide empty TV shows" to the video library side blade makes sense to. Tough luck if the advanced setting can't be migrated.

**Comment by HitcherUK** [comment]
That sounds logical and is in keeping with the current cleaning/deleting method.

**Comment by tamland** [comment]
Not sure I quite got the problem with using a setting, but it seems to me that this is one of those things that really belongs hidden in 'advanced' that most people won't be bothered with, not so prominent in the side blade. Its functionality also overlaps/conflicts with 'hide watched' which will hide empty tv shows.

**Comment by Montellese** [comment]
@anaconda: Are you planning on updating this according to the discussion?

**Comment by anaconda** [comment]
> @anaconda: Are you planning on updating this according to the discussion?
Sorry, I think I’ll miss February and probably March merge windows.=

**Comment by NedScott** [comment]
Can we get a v16 Jasslehoff label on this so it doesn't get forgotten?

**Comment by mkortstiege** [comment]
You can add whatever label you want ;) but this is not yet ready for merging.

**Comment by vbat99** [comment]
I believe discussion on this pull request has two discussion issues.
1. Add Hide Empty Series to a Gui option.
2. Removal of Empty Series on Library Clean-up.

I am all for an option on the Blade to Show/Hide Empty Series when viewing TV Shows that are in the Library.

My concern is #2 above, which Pull #6024 doesn't address.
This needs to be an option in Settings -> Video -> Library, Something like On Clean, remove Empty Series, With the logic being if False AndAlso Series Folder Exists, keep in the Library Database.

Discussion between @Montellese & @anaconda seem to point almost in the right direction, that the logic of Clean library should only remove a TV Series from the Database, when the TV Series path no longer Exists, Yet they it is also discussed to force empty series to be removed.

I feel my suggestion above to add an option to the Video library, possibly under Expert mode, would be of use to all users of XBMC, and leave the choice in the Users hands. This option could be set as selected by default if Team Kodi prefers, but Please, make it an option for the user's to select.

**Comment by phil65** [comment]
I agre with @tamland that this should definitely not get placed inside the side blade. Should be in settings instead.

**Comment by vbat99** [comment]
@phil65 So a user has to travel to Settings->Video->Library to show/hide empty series, yet on the blade is the option to Hide Watched episodes?
Hide Empty Series should be above Hide Watched.  Keeping with the current format.

**Comment by MartijnKaijser** [comment]
I agree with @phil65, it should be in settings and not sideblade. It's a setting you only use very few times

**Comment by vbat99** [comment]
Ok, that makes sense.

**Comment by NedScott** [comment]
I don't feel strongly about this, so I won't object to whatever is decided, but I'd like to explain how I view the "hid empty" setting:

How often the setting is used will change greatly for people who want the setting vs everyone else. When you have empty TV show folders, because you delete files as you watch them, then something like this will be used as often as "hide watched". There are users who never use "Filter", "Search", or "hide watched" (at least not often), but the sidebar is still the most logical plac for such options. It is where you go when you want to filter the current view/list. It is not a once-off toggle lik "hide .. (Parent directory)" or hiding the progress bar of updates. People with empty TV show folders want to be able to sometimes see "everything", and then sometimes just shows that have episodes. It's the same logic as "hide watched". Even if it is not common, the sidebar with all the other view/filter options is the most intuitive location for the setting.

Maybe we can have it both ways? Put it in settings, but then skinners can add their own toggle to that setting in their own sidebars? I think that's possible with JSON-RPC?

If we can't agree on this switch location then maybe we should split this PR. What we need more than anything is a toggle for cleaning empty TV show folders or not, so that it is not attached to the hide-empty as.xml setting. Promoting the as.xml setting to the GUI, where ever we put it, is just a bonus.

**Comment by phil65** [comment]
Perhaps DialogMediaFilter ("Hide watched" belongs there, too), but not sidebar. It´s a power user feature imo and it´s not as if the whole world complained that this setting was hidden in AS.xml.

**Comment by NedScott** [comment]
I complained about it, actually :)

It's one of the top items on my personal list of as.xml settings that I think should be in the GUI. If I had my way I would make "hide watched", "filter", "search", etc always visible in the default skin. I think more people would use these filters/toggles if they weren't hidden out of sight :)

If we are adding a GUI setting then it should go in a logical location for those who use the setting. It shouldn't be hidden because some people don't plan on using it very often, IMO.

However, I'm totally fine with starting out with a video library setting. Anything is better than hidden away in as.xml.

**Comment by NedScott** [comment]
@mkortstiege I don't have the ability to add labels. I just mean the J**** label, and not the v16 alpha 1 label.

**Comment by Montellese** [comment]
@phil65: Putting these things in `CGUIDialogMediaFilter` would be bad for user experience because the dialog is very slow to open on the raspberry pi and the bigger your library is the slower it opens. I would like to use it more often but having to wait a few seconds on my RPi2 until it is open sucks (yes I've written that dialog myself).

@NedScott: Skinners can't directly use JSON-RPC. They would have to write and depend on an addon to do that AFAIK.

I don't have a strong opinion on this either. On the one side (simply looking at the functionality) I think it is the same as "Hide watched" and should be in the side blade but on the other side I would never use it (but I use hide watched all the time) so it would just be a dead button taking up space for me.

IMO we should split this PR up as proposed and fix the library cleaning issue and then we can find a solution for the hide empty tvshows in another PR.

**Comment by mkortstiege** [comment]
> IMO we should split this PR up as proposed and fix the library cleaning issue and then we can find a solution for the hide empty tvshows in another PR.

+1

**Comment by anaconda** [comment]
@MartijnKaijser I've got a report that JSON-RPC output is incomplete on Jarvis after this PR.
Turns out complete fix was merged after branching and it's only in Krypton (#5752).
By inverting the default for this setting, it'll act like the old "hideemptyseries" advanced setting (it affected JSON-RPC output too, but was disabled by default). Would you be okay with such a fix for Jarvis?

**Comment by MartijnKaijser** [comment]
I'd say add backport the fix please.

**Comment by vbat99** [comment]
With release of Kodi 16, I am seeing discrepancies in the function of cleaning of the library as follows:
Note: Show empty TV Series is enabled.

1.  TV Series added that no episodes.
Clean library and series remains.  Good.
Remove Series folder fro source, and perform Clean Library.  Series name remains in list of TV Series.  um, not good.
Disable Show Empty TV series, and perform Clean Library.  Re-Enable Show Empty.  Series still listed. - Still not good.

2.  TV Series with one or more episodes, added to library.
Remove Series Folder from source, and perform Clean Library.  Series name remains, but now displays no episodes. - well it cleaned the episode, but the series remains.
Disable Show Empty TV Series, and perform Clean.  Re-Enable Show Empty TV Series.  Series is removed from library.

Should the Clean Library not be checking to see if the Series folder exists to determine if it is to be removed from the Library?
It should not matter if the Show Empty is enabled or disabled, but whether there is an actual Series Folder.

BTW, the steps above a reproduce-able, as I needed to confirm as I was writing this.
I hope this log is sufficient, else let me know what I can do.  
http://pastebin.com/cUBvhYpa

**Comment by anaconda** [comment]
#8133

**Comment by vbat99** [comment]
@anaconda Thanks, read #8133 just now, your on to it.  Thanks.

**Pull request merged**
