### PR TITLE
[cmake] Add support for Bluetooth

### PR DESCRIPTION
**Pull request by hudokkow**
## Description
Build with bluetooth support if we find it.

## Motivation and Context
Get CMake up to par with autotools. See https://github.com/gentoo/gentoo/pull/3027#issuecomment-266276021
Fixes http://trac.kodi.tv/ticket/17129

## How Has This Been Tested?
Build tested under linux64

## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)

ping @wsnipex

### CODE REVIEW

**Comment by hudokkow** [comment]
Corrected after chat with @wsnipex.
jenkins build this please

**Review by wsnipex — APPROVED** [review]

**Comment by stefansaraev** [comment]
are those extra eventlients that require bluetooth still in use ?

**Comment by hudokkow** [comment]
That's a good question but I don't use any of them myself. Would love to know. ;)

**Comment by hudokkow** [comment]
jenkins build and merge

**Comment by hudokkow** [comment]
Build is fine: http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-PR-Manually/244/

**Comment by candrews** [comment]
With this change, I'm still seeing this message from cmake:
```
  Manually-specified variables were not used by the project:
    ENABLE_BLUETOOTH
```

Is the variable named something different?

**Comment by hudokkow** [comment]
Just did a clean build with `ENABLE_BLUETOOTH=no` and it's honored. Can't see those lines in my build log. Same without the variable (auto mode).

**Pull request merged**
