### PR TITLE
[Android] Display some cpu info that was missing in System information

### PR DESCRIPTION
**Pull request by joseluismarti**
## Description
Gets the values of the items: Hardware, Serial and Revision when they are available in from ```/proc/cpuinfo``` output.

## How has this been tested?
Tested on Amazon Fire TV Stick 4K Max (Android TV 9).

Add screenshots of before and after the change.

## Screenshots (if appropriate):
Before:
antes

After:
despues

## Types of change
- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by thexai — APPROVED** [review]
Some values like serial I don't know if they can have much value for users. In Shield I think that none of these fields are available and for this reason I did not add them at first. 

Still, since the variables are already defined in the GUI, I think it's fine to have these values when the HW provides them.

**Comment by thexai** [comment]
Perhaps some value of interest can be obtained from here in a more compatible way:
https://github.com/xbmc/libandroidjni/blob/master/src/Build.cpp

And the missing ones can be added to `libandroidjni` i.e. "SOC_MODEL"
https://developer.android.com/reference/android/os/Build

This is just to give ideas for another PR 😀

**Comment by joseluismarti** [comment]
> Perhaps some value of interest can be obtained from here in a more compatible way: https://github.com/xbmc/libandroidjni/blob/master/src/Build.cpp

These methods seem to refer more to product or model information and not to CPU info.

They are displayed in the log at start-up:
https://github.com/xbmc/xbmc/blob/master/xbmc/platform/android/PlatformAndroid.cpp

> And the missing ones can be added to `libandroidjni` i.e. "SOC_MODEL" and "SOC_MANUFACTURER" https://developer.android.com/reference/android/os/Build

Yes, I was looking at these methods SOC_* but they are available from API level 31 onwards.

**Review by garbear — APPROVED** [review]
By "Serial" it means "CPU serial", right? I see no benefit to showing a long hard to read hexidecimal number in a Media Center. IMO "CPU serial" should be removed from the GUI entirely. OK thing for the log though, because why not.

But that's another conversation. My approval here is purely because the feature is added cleanly - 11 lines added, 0 lines deleted, so no risk of changing existing code.

Can you test with hardware that is missing these fields? It'd be nice to know this degrades gracefully and doesn't add any useless noise to a GUI view.

**Comment by joseluismarti** [comment]
> By "Serial" it means "CPU serial", right? I see no benefit to showing a long hard to read hexidecimal number in a Media Center. IMO "CPU serial" should be removed from the GUI entirely. OK thing for the log though, because why not.

Yes, I agree with you.

> Can you test with hardware that is missing these fields? It'd be nice to know this degrades gracefully and doesn't add any useless noise to a GUI view.

It will not add noise, if these fields are not found in the output, doesn't show the related label:value in the GUI.

**Comment by thexai** [comment]
Tested on Shield 2019 and it shows the same infos as before

**Pull request merged**
