### PR TITLE
fixed: Crash when we're unable to retrieve info from remote server

### PR DESCRIPTION
**Pull request by arnova**
Fix for the crash mentioned in my team-email. If ok'ed, I'll prepare a backport for Krypton.

### CODE REVIEW

**Comment by arnova** [comment]
Note that I'm not sure the fix is in the right location, perhaps it should be somewhere in CVideoLibraryRefreshingJob

**Comment by Rechi** [comment]
maybe adapt it to the way of #12373

**Comment by arnova** [comment]
@Rechi : Thanks for the heads up. See my comment in the other PR

**Comment by mkortstiege** [comment]
Issue handled in https://github.com/xbmc/xbmc/pull/12373

**Pull request closed without merging**
