### PR TITLE
Compatibility with libcec v2.1.4

### PR DESCRIPTION
**Pull request by bfg1981**
This patch make kodi work without libraries not in Ubuntu standard library

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@opdenkamp ping

**Comment by opdenkamp** [comment]
sorry, but v2.1.4 has known issues and is no longer supported, and i don't want to infest xbmc's code with ifdefs to make it compile. please upgrade to 2.2.0. i'll fix the configure check and version in the 2.2.1 release.

**Comment by bfg1981** [comment]
@opdenkamp That's fair, just thought compiling on standard Ubuntu would be preferable, anyway, IIRC there are some issues with that that states it supports v2.1.0, those should be fixed.

**Comment by bfg1981** [comment]
A harcoded (enquirable?) variable that states that it support 2.1.0, I seem to remember, I should probably have a look once I have my coding computer present

**Pull request closed without merging**
