### PR TITLE
game: fix order of init/deinit in ServiceManager

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

@garbear /cc

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by garbear** [comment]
What ever happened to the LIFO idea? This is going to keep biting us without a LIFO.

**Review by garbear — APPROVED** [review]

**Comment by garbear** [comment]
`CInputManager` is accessed from main() on linux. It doesn't need to be initialized, it just has to be created. `CAppParamParser` sets some properties that are read upon its initialization.

**Comment by FernetMenta** [comment]
this pr makes it lifo

in:

m_announcementManager
m_gameServices.reset(new GAME::CGameServices);
m_peripherals.reset(new PERIPHERALS::CPeripherals);
m_inputManager.reset(new CInputManager);

out:
m_inputManager.reset();
m_peripherals.reset();
m_gameServices.reset();
m_announcementManager.reset();

prior to this it was no lifo because announcementManager is supposed to be first. your ctor init made game first.

**Comment by FernetMenta** [comment]
> CInputManager is accessed from main() on linux

in this case it shouldn't be owned by ServiceManager

**Comment by FernetMenta** [comment]
btw: kodi-test crashed because peripherial depends on announcementManager

**Comment by garbear** [comment]
> in this case it shouldn't be owned by ServiceManager

In the case where it is owned by ServiceManager, main() shouldn't call into CInputManager.

The change here is correct. I can refactor the `CAppParamParser` issue later today.

**Comment by garbear** [comment]
BTW #12426 can be reverted once we take care of this mess.

**Comment by FernetMenta** [comment]
@garbear do you want to take over this pr?

**Comment by garbear** [comment]
No :) But I think I see how things should be so I'll tackle this issue and open a new PR.

**Comment by FernetMenta** [comment]
that's what I meant. if you open a new PR, I con close this one, right?

**Comment by garbear** [comment]
Superseded by #12432

**Pull request closed without merging**
