### PR TITLE
Implement range check in URIUtils::resolvePath

### PR DESCRIPTION
**Pull request by enen92**
## Description
This adds a simple range check for `realPath` in `URIUtils::resolvePath` to avoid kodi crashing if the value is empty.

Not sure who to ping. Pinging @phunkyfish since he's used to close PRs by now :)

## Motivation and Context
Fix the DoS condition of https://github.com/xbmc/xbmc/issues/17432

## How Has This Been Tested?
Compile and runtime test

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Review by phunkyfish — APPROVED** [review]
Nice 👍

**Comment by MilhouseVH** [comment]
Thanks, I can confirm this prevents the crash.  With this PR the response is now:
```
NUC:~ # curl -X POST -H "content-type:application/json" http://localhost:8080/jsonrpc -d '{"jsonrpc":"2.0","method":"Files.GetDirectory","id":"1583238585622","params":{"directory":"plugin://foobar/./","media":"video","properties":["title","file","mimetype","thumbnail","dateadded"],"sort":{"method":"none","order":"ascending"}}}';echo
{"error":{"code":-32602,"message":"Invalid params."},"id":"1583238585622","jsonrpc":"2.0"}
```
which may or may not be correct, but at least it doesn't crash!

**Comment by enen92** [comment]
Jenkins build and merge

**Comment by lrusak** [comment]
jenkins build this please

**Pull request merged**
