### PR TITLE
cppcheck performance fixes in dbwrappers/

### PR DESCRIPTION
**Pull request by tobbi**
This is another round of fixes for the files under dbwrappers/

I hope you are okay with me removing string initializations. But since strings do default to an empty string when not initialized, I assume that it's redundant to initialize them again.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@Montellese perhaps you could take a brief look as well

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by tobbi** [comment]
Is there anything that still needs to be done for this PR?

**Comment by MartijnKaijser** [comment]
let's try again the build, jenkins build this please

any further remarks?

**Comment by tobbi** [comment]
Jenkins is green, so this can be merged.

**Comment by mkortstiege** [comment]
Please squash.

**Comment by tobbi** [comment]
done squashing.

**Comment by mkortstiege** [comment]
jenkins build and merge

**Pull request merged**
