### PR TITLE
[Windows] Bump libass to 0.15

### PR DESCRIPTION
**Pull request by Paxxi**
Includes font loading fix as well

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by enen92** [comment]
I think the fix for 0.14 needs to get in first (and then backported) and only after that we can update the library in v20?

**Comment by Paxxi** [comment]
This includes the fix for for 0.14 so I skipped that step for v20 but I can do that if we want to.

**Comment by fuzzard** [comment]
Ping @Paxxi know you've been busy, so just wanted to put this back on your radar when you get time. I think @enen92 was hoping to get a 0.15.1 version done if possible

**Comment by enen92** [comment]
Yeah it'd be great if this PR could be updated with the patches from 0.15.1. this version fixes bundled fonts in ass files which is not included in 0.15.0

**Comment by Paxxi** [comment]
Thanks for reminding me, I've built and done some tests on 0.15.1 now, waiting for upload to mirrors

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
Failure looks unrelated

**Pull request merged**
