### PR TITLE
Provide seeds for random_shuffle

### PR DESCRIPTION
**Pull request by danhawkins87**
Add srand(time(0)) as a seed to random_shuffle so that Party Mode and Playlists
shuffle differently each time.

### CODE REVIEW

**Comment by mkortstiege** [comment]
Looks good to me. jenkins build this please.

**Comment by Paxxi** [comment]
When we're touching these we should update them to use std::shuffle, random_shuffle is deprecated

**Comment by popcornmix** [comment]
I don't get this. srand is a void function that should be called once per program run.
Why are we passing it as a random number generator function?

**Comment by uNiversaI** [comment]
@popcornmix my guess is because @danhawkins87 found out that rand is not really random at all and is trying to somehow improve on the uniqueness or generated random, so that less repeated material occurs.
I know little about programming and if te above is case, I dont think this will make much difference at all.

**Comment by fritsch** [comment]
@uNiversaI ppssssst :-)

what @popcornmix says makes sense. Same question for me?

**Comment by fritsch** [comment]
```

For every different seed value used in a call to srand, the pseudo-random number generator can be expected to generate a different succession of results in the subsequent calls to rand.

Two different initializations with the same seed will generate the same succession of results in subsequent calls to rand.
```

**Comment by Paxxi** [comment]
right so this won't work. @danhawkins87 please change this to the method I suggested above and it should be fine. mt19937 (mersenne twister) should be a good generator to use and remember to seed it with something like random_device or it'll produce the same value every time.

Questions? poke me and I'll try to flesh it out some more

**Comment by Paxxi** [comment]
Since nothing's happened here for a while I created a pr to resolve this, see #8192
I'm closing this

**Pull request closed without merging**
