### PR TITLE
video library: refactor "Refresh" and add it to JSON-RPC

### PR DESCRIPTION
**Pull request by Montellese**
This refactors the whole "Refresh" logic from the video info dialog into a new `CVideoLibraryRefreshingJob` which can be run with a modal dialog (like it is now), with a progress dialog (no idea if that's a real use case) or completely in the background. This refactor allows us to expose this functionality to JSON-RPC as `VideoLibrary.RefreshMovie/TVShow/Episode/MusicVideo` and use the background mode without any GUI interaction.

I've also cleaned up the whole logic a bit and fixed some labels which always contained "movie" even when refreshing a tvshow, episode or musicvideo. I hope I didn't break anything but the existing code is a mess anyway. There are two lines that I didn't understand so I put a `// TODO: why???` next to it.

I've also noticed that `CFileItem::GetBaseMoviePath()` is broken for several scenarios. I've fixed one of them but didn't find a simple way to fix the others as well. This can result in very odd behaviour when trying to refresh an item from the files node.

EDIT: Needs an Xcode sync.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
How would refresh work with progress or jsonrpc? Current behaviour is when you hit refresh you get asked to use local information if you have nfo and when doing online you have to choose which show or movie. If perfect match you only have one but when having multiple it gets tricky.

**Comment by phil65** [comment]
Thx @Montellese! Will instantly make use of this once included. :)

**Comment by Montellese** [comment]
@MartijnKaijser: For the NFO vs online lookup there's an optional parameter `ignorenfo` which defaults to `false` but can be manually passed. Concerning multiple potential hits it works exactly the same as during the library scan i.e. it simply picks the first match and goes with that.

**Comment by Tolriq** [comment]
@Montellese I have not checked all non JSON patch since Gotham but is the multiple tvshow Id when using multiple folders still present or only 1 global id ?

If still present does this works whatever id is sent or will only the episodes in the associated folder be refreshed ?

**Comment by Montellese** [comment]
@Tolriq: I haven't tested that use case yet. The problem is that you can't really get into that situation anymore with the "new" code. IIRC it can only happen when upgrading from an older installation. But I'll have to check if there's upgrade logic for that case as well in which case this wouldn't be a problem.

**Comment by Montellese** [comment]
OK just checked. With the update from videodb 82 to 83 all duplicate tvshows (due to multiple paths) were merged into a single tvshow with a single tvshowid and multiple paths. So theoretically this shouldn't be an issue here but I'll try to test it anyway.

**Comment by Tolriq** [comment]
Thanks for the migration test and confirmation that the multiple ids are now history, this is good news :)

**Comment by Montellese** [comment]
I've added the possibility to manually pass in a specific search title through JSON-RPC to give more control over the scraper result that is chosen due to the fact that the logic simply chooses the first/best scraper result.

**Comment by Montellese** [comment]
@Memphiz or @mkortstiege could I get an xcode update on this one?

**Comment by xhaggi** [comment]
xcode sync: https://github.com/xhaggi/xbmc/commit/a1de8b264fa199cd948dd7517bc113a189a8e7db

**Comment by Montellese** [comment]
@xhaggi: That was fast, thanks. jenkins build this please

**Comment by MartijnKaijser** [comment]
@Tolriq could you give it a test run?

**Comment by Tolriq** [comment]
No problem if you can trigger a Windows build I can download.

**Comment by MartijnKaijser** [comment]
Thx, build is queued so might take some time before its done. Can be found in test-builds with branch in filename

**Comment by phil65** [comment]
Did some quick testing (with movies only for now) and everything seems to work fine. Thx!

**Comment by Montellese** [comment]
Here's the win32 test build: http://mirrors.xbmc.org/test-builds/win32/KodiSetup-20150713-f53b0db-refactor_video_item_refresh.exe

**Comment by Tolriq** [comment]
Yes downloaded it :) But it's non working day in France today, will check more tomorrow

**Comment by Tolriq** [comment]
Not related at all to the PR, but during tests I had a strange behavior : 

image

No way to delete the last letter in this dialog I have to press enter to open the dialog then I can delete.

I tested over official RC2 and it's present too, reporting here as I know @Montellese knows well dialogs and RC2 is near final so can get quick attention.

Returning to PR test, but from quick code look I do not see any notification sends ?
Even if no new  "VideoLibrary.OnScanStarted" type even VideoLibrary.OnUpdate should be fired so remote could fetch the updated data after no ?

**Comment by Tolriq** [comment]
Ok so tests results : (Not only JSON)

First refreshing items changes Id ? I was thinking dropping / adding again without keeping id was Eden time and now correctly handled. Id change makes impossible for remotes to handle themselves missing playlist API for example.

About my question : Refreshing does trigger a onRemove notification and an onUpdate notification but since the IDs are different no way for remotes to make a match .

Movie refreshing / TvShow seems to work (not tested with a title param or the refresh episodes yet due to next point).

For episodes there seems to be a lot of problems.
From JSON no notification triggers so I suppose this does not work.
From GUI : For an episode with an nfo, if I choose ignore nfo and refresh from internet, the screen does shows back with updated information but I only get a onRemove notification and the episode disappear from Kodi. If I refresh from nfo I get the 2 notifications and the id change.

No test for musicvideos.

**Comment by Tolriq** [comment]
@Montellese will move to holidays tomorrow other things to tests / help with for episodes ?

Any insight about the ID change on refresh ?

**Comment by Montellese** [comment]
@Tolriq: Thanks for the detailed feedback. I didn't have time to look into it yet. During my last testing I also saw once that the ID changed but then when I tried to reproduce it, it didn't happen anymore. And episodes worked fine for me as well. But maybe I broke something during a rebase.

**Comment by Tolriq** [comment]
@Montellese the trick with ID is that if you refresh the last item it will keep the id and reuse it.
But if you refresh like ID 1 it will get a new ID based on last one + 1.

I find it quite strange, since this means that the ID is not a simple auto increment from sqlite since refreshing the last one would give a new ID too.

**Comment by Montellese** [comment]
I know what the issue with the changing ID is and I also saw it once while working on this PR but then I tried to reproduce it and it didn't happen anymore.

**Comment by Tolriq** [comment]
Well I can reproduce it at 100% with this build so if you need logs or something just tell. (I still have no build machine to do real debugging :() I guess Windows 10 will be my excuse to finally format this bugged computer :( (Do you know if Kodi will build from Visual Studio 2015 as it would be best to start up 2 date and fresh).

To remove any update problem or anything I did start fresh with this build : Install this build, create a shortcut with -p to be in portable mode, add 2 smb sources (1 movie 1 shows) scrape from mostly nfos. And that's all.
ID change from JSON and from GUI.

**Comment by Montellese** [comment]
@Tolriq: I just checked current master and refreshing an item in the video library results in remove + add so there will always be a new ID.

**Comment by Tolriq** [comment]
I suppose not the time / place to ask about fixing this non sense :(

I'm packing for holidays so can't really follow up for 1 week.

**Comment by Montellese** [comment]
@Tolriq: I just tried all kinds of combinations of refreshing episodes in the GUI and I couldn't see any unexpected behaviour. I refreshed a tvshow with all episodes, I refreshed an episode without NFO, I refreshed an episode with NFO and ignored it and I refreshed an episode with NFO and used it and all worked perfectly fine.

**Comment by Montellese** [comment]
@Tolriq: I've also looked into keeping the ID of the media item when refreshing from the GUI or JSON-RPC but the way the info scanner is currently written, I don't see a way to do it without breaking other use cases.

**Comment by Tolriq** [comment]
@Montellese very bad news about the ids :( No way to get that even in 17 ? This is very very limiting for tons of things.

Anyway about the refresh problem : 

http://yatse.tv/Files/Kodi.zip contains all needed information to reproduce.

Image 1 is the status of a show
Image 2 is the message after pushing the refresh button in show information
Image 3 is the resulting window after the refresh showing the correct information (Vikings / Season 1 / Episode 7)
Image 4 is what happens after closing the window, the said episode is gone.

There's also a fake mkv file with the correct name, the associated nfo the full smb path and the logs of those operations.


For the refresh from JSON not sure what I can give you or maybe you have updated some things and I need to test a more recent build ?

**Comment by Montellese** [comment]
@Tolriq: Thanks for the detailed feedback. I copied your stub and NFO file into my usual library location into a `Vikings/Season 1` directory, scanned it into the library, manually updated the tvshow and the episode (once with getting metadata from scrapers and once from NFO) and everything worked perfectly fine.

**Comment by Tolriq** [comment]
Well maybe a bug with smb ? I did gave the exact used path in the zip.

**Comment by Montellese** [comment]
@Tolriq: Tried again under the following path: `\\NAS\Shows\_OK\Vikings\Season 1` so apart from the name of the machine it's identical and everything still works fine.
Did you try again with the latest version (I didn't fix anything, just rebasing)?

**Comment by Tolriq** [comment]
No :) I did ask if I should but did not see a new compiled build.

I see some PR about Visual Studio 2015 will it work with it when I format ?

**Comment by Montellese** [comment]
Sorry, forgot about the test build. I triggered one at http://jenkins.kodi.tv/job/WIN-32/5672/ so it should be done in a bit and then some more time until it's available on the mirrors.

We'll probably wait with moving to VS2015 because AFAIK there are still people who only have access to VS2013 (full version not the free one). I'm also still only on VS2013 myself.

**Comment by Tolriq** [comment]
Well I'll see if I reinstall VS2013 on Windows 10 so :(

Got the file will do the new tests today.

**Comment by Tolriq** [comment]
Exact same.

In log I see : ERROR: VideoInfoScanner: Asked to lookup episode smb://diskstation/Shows/_OK/Vikings/Season 1/Vikings.S01E03.FASTSUB.VOSTFR.720p.HDTV.x264-PROTEiGON.mkv online, but we have no episode guide. Check your tvshow.nfo and make sure the <episodeguide> tag is in place.

So maybe not related to this PR at all :( (TBH never used this before).

But sounds like a major problem as Items should not disappears from the DB while still having shown a correct information before. So sounds like a major bug. (A scan for new content on the source bring them back)

Anyway about the PR :

```
{"jsonrpc":"2.0","id":1,"method":"VideoLibrary.RefreshEpisode","params":{"episodeid" : 4}}
```

Still does not work, no notification triggered about delete / update and no data change even if I updated the NFO.
For Shows and Movies even with no NFO change I get the notifications.

But it returns :
```
{"id":1,"jsonrpc":"2.0","result":"OK"}
```

**Comment by Montellese** [comment]
Maybe it's a problem in combination with the tvshow's NFO (which you didn't provide in the ZIP file). Could you try the refresh logic without this PR to check if it's a general issue?

I'll look into the episode refresh but it worked perfectly fine for me yesterday with your NFO (which is French) and the scraper data (which is English). Depending on what I used in `VideoLibrary.RefreshEpisode` the GUI showed the plot in French or English. I didn't check notifications though.

**Comment by Tolriq** [comment]
The first problem is also present in Helix (14.2) so not related to this PR (but still important)
(The show NFO : http://pastebin.com/tkQWcs3Q)

I did try the RefreshEpisode with others shows in case it was a problem like Viking all responded OK but none worked and no data changes (I tried to update the titles)

**Comment by Montellese** [comment]
@Tolriq: `VideoLibrary.RefreshEpisode` should now also work properly. I triggered a test build at http://jenkins.kodi.tv/job/WIN-32/5692/.

**Comment by Tolriq** [comment]
@Montellese This build is under drugs ;)

The return from a JSON query : 
```
{ñ£ø0Ì¶;ý├"ØqpnÝÁ░Ö   Ã Í85─╚00ÚÀ%ø=zMS┤Ió
ÊmtUéï└1«Ã╠═Ü├ÿ)F$E▓¹p!Ì7|¢╩3Hv´È5Ôk º,¡·ú°        ª_ä%└{x¶¨╠³
```

**Comment by Montellese** [comment]
@Tolriq: I'm assuming this is TCP? I only tried sending request over HTTP but I also listened to notifications on TCP. Something must have gone wrong with the build. Will rebase and trigger another build.

**Comment by Montellese** [comment]
Rebased and test build triggered at http://jenkins.kodi.tv/job/WIN-32/5728/.

**Comment by Tolriq** [comment]
@Montellese it was http ;) Will try the new one.

**Comment by Tolriq** [comment]
@Montellese it's the same http is completely broken on those builds.

 ```
ÿÁ±²ñ┌kÈ¼W■oI&ÚÅ┴ïù´âÈm³-ïCá^O║jÆ·ÞYÍ>┐/çÌÈ×`QNþa:ð«¥uP
 ```

But TCP seems to work :
 ```
{"jsonrpc":"2.0","id":1,"method":"VideoLibrary.RefreshEpisode","params":{"episodeid" : 105}}{"id":1,"jsonrpc":"2.0","result":"OK"}{"jsonrpc":"2.0","method":"VideoLibrary.OnRemove","params":{"data":{"id":105,"type":"episode"},"sender":"xbmc"}}{"jsonrpc":"2.0","method":"VideoLibrary.OnUpdate","params":{"data":{"item":{"id":2124,"type":"episode"}},"sender":"xbmc"}}
 ```

**Comment by Montellese** [comment]
@Tolriq: Just tested the lates build locally by sending HTTP GET and POST request using a chrome extension and the response looks perfectly fine to me. I tested several JSON-RPC methods including `VideoLibrary.RefreshMovie` and `VideoLibrary.RefreshEpisode` and everything is fine. Are you sure that it's not a problem on your end?

And looking at the TCP output it looks like it worked this time right?

**Comment by Tolriq** [comment]
@Montellese Ok so yes the problem was on my side with Windows 10 update on the test machine that now have something by default on port 80 that returns this ...

But in Helix when Webserver did not start I had a small popup saying problem starting WebServer this is no more the case in Isengard.

I can change to a correct value then it works, but when I change back to an used port no error or anything, Kodi update the UI to used port without any problems.

In 14.2 this is not the case, there's an error and the value revert back to the correct one.

And tied to this: Even if the web server is not started Zeroconf continue to advertise the webserver being present.

This explains the soon hundred of support I receive from problems with Windows 10. I was assuming it was users being dumb, but in fact they have no way to know about the problem at all.

I would really appreciate a fix for that in a 15.1 release as current support level about Windows 10 is awful.

About the PR, yes it seems it works from the notification, but have not yet done real tests about values updating and the nfo no nfo thing to see it it reproduce the GUI item removal.
(Do I need to open an issue or something about the removal of items so it's not forgotten ?)

**Comment by Montellese** [comment]
Only one or two people on the team have moved to Windows 10 so nobody has looked into any specific issues yet. Yes you should get a notification if the webserver couldn't be started but maybe there's a different issue with Windows 10 that the webserver starts fine and thinks it can handle requests but it can't.

Yes please create a trac ticket about the issue you had with your NFO and provide the tvshow and episode NFOs and the screenshots you made. I'm not very knowledgeable in that area.

Thanks for taking the time to do all these tests.

**Comment by Tolriq** [comment]
Will open the issue.

About the Windows 10 issue, do you need some logs or can I help to have a fix for 15.1 ?

**Comment by Montellese** [comment]
Having some logs where the webserver seems to start but isn't working would certainly help. I have updated my stoneage laptop from Win7 to Win10 last weekend but it's a clean install and setting up a buildsystem would take forever (because it's so slow) but maybe I'll find some time to install Kodi and test it myself.
Please also create a trac ticket for this as it has nothing to do with this PR.

**Comment by Tolriq** [comment]
After a quick test : Kodi 14.2 on Windows 10 does show the error popup and refuse the update of the port as it does on Windows 8. So the error maybe not related to Windows 10 at all just Isengard.

Anyway will open a trac issue too, hoping that it will not have a message on it in 6 month as some others opened ;)

**Comment by Montellese** [comment]
jenkins build this please

**Comment by hudokkow** [comment]
Build problems unrelated, just some random addon playing difficult...
jenkins build this please

**Comment by Montellese** [comment]
Rebased. jenkins build this please

**Comment by MilhouseVH** [comment]
What was the conclusion about the lack of `OnUpdate` notifications when calling `RefreshFoo`?

Receiving the `OnUpdate` notification whenever an existing tvshow (which may add new seasons  and episodes), movie or episode is updated during one of these `RefreshFoo` methods would be nice (though probably not essential).

**Comment by Montellese** [comment]
@MilhouseVH: There should be an `OnUpdate` notification but the order will be
* `RefreshFoo` (with ID X)
* `OnRemove` (with ID X)
* `OnUpdate` (with a new ID)

**Comment by MilhouseVH** [comment]
Ah right, thanks - I see them now. However there might be just one small problem - if there is no `OnScanFinished` notification, how is the caller to know when all items have been processed by the `RefreshFoo` call? In particular, if refreshing a tvshow and all episodes, how would the caller know when all episodes have been refreshed or new episodes added?

It seems that an `OnScanFinished` notification is required once `RefreshoFoo` is complete processed.

**Comment by MilhouseVH** [comment]
Here's an example of the `RefreshFoo` request and resulting notifications when refreshing an existing TV show that has five existing episodes (episodes 1-4 plus a special), and two new episodes yet to be added (episodes 5-6):
```
> {"method":"VideoLibrary.RefreshTVShow", "params": {"tvshowid": 210, "ignorenfo": false, "refreshepisodes": true}
< {"method":"VideoLibrary.OnRemove", "params":{"data":{"id":12759,"type":"episode"}}}
< {"method":"VideoLibrary.OnRemove", "params":{"data":{"id":12760,"type":"episode"}}}
< {"method":"VideoLibrary.OnRemove", "params":{"data":{"id":12761,"type":"episode"}}}
< {"method":"VideoLibrary.OnRemove", "params":{"data":{"id":12762,"type":"episode"}}}
< {"method":"VideoLibrary.OnRemove", "params":{"data":{"id":12762,"type":"episode"}}}
< {"method":"VideoLibrary.OnRemove", "params":{"data":{"id":210, "type":"tvshow"}}}
< {"method":"VideoLibrary.OnUpdate","params":{"data":{"item":{"id":236,"type":"tvshow"}}}}
< {"method":"VideoLibrary.OnUpdate","params":{"data":{"item":{"id":13105,"type":"episode"}}}}
< {"method":"VideoLibrary.OnUpdate","params":{"data":{"item":{"id":13106,"type":"episode"}}}}
< {"method":"VideoLibrary.OnUpdate","params":{"data":{"item":{"id":13107,"type":"episode"}}}}
< {"method":"VideoLibrary.OnUpdate","params":{"data":{"item":{"id":13108,"type":"episode"}}}}
< {"method":"VideoLibrary.OnUpdate","params":{"data":{"item":{"id":13109,"type":"episode"}}}}
< {"method":"VideoLibrary.OnUpdate","params":{"data":{"item":{"id":13110,"type":"episode"}}}}
< {"method":"VideoLibrary.OnUpdate","params":{"data":{"item":{"id":13111,"type":"episode"}}}}
```
Given the above, it's impossible for the caller to know when to stop waiting/listening for further `OnUpdate` notifications without some sort of notification that the scan is complete (ie. an `OnScanFinished` notification).

**Comment by Montellese** [comment]
@MilhouseVH: That was already the case before this PR. Apart from the case where a TV show is refreshed with all its episodes this is not a scan, just a refresh so sending `OnScanStarted` and `OnScanFinished` seems inappropriate for movies, episodes and musicvideos.

**Comment by MilhouseVH** [comment]
Presumably you're referring to the GUI "refresh" method, as I'm not aware that it was possible to refresh a tvshow using JSON-RPC before this PR - I was only aware of `VideoLibrary.Scan`, which of course emits the `OnScanStarted`/`OnScanFinished` notifications.

I mentioned `OnScanStarted`/`OnScanFinished` as that is the existing notification, but if `RefreshFoo` were to emit `OnRefreshStarted` and `OnRefreshFinished` notifications would that be any easier/better?

I agree that `On*Started`/`On*Finished` messages are not necessary for movies, episodes and musicvideos as there will only ever be a single `OnRemove`/`OnUpdate` notification, ie. predictable, but thought it would be consistent for them to at least have an `On*Finished` notification if this is ever added for `RefreshTVShow`.

However when using `RefreshTVShow` with `refreshepisodes: true` the number of `OnRemove`/`OnUpdate` notifications is indeterminate, so some sort of `On*Finished` message would seem appropriate, particularly as this method is asynchronous and the caller will never know when the refresh is finished.

**Comment by MilhouseVH** [comment]
Another issue due to the lack of any "Finish" notification.

What if the item being refreshed is removed from the file system before the `RefreshFoo` request is made (ie. the media is deleted, then the library item refreshed with one of these new methods)? 

In such a situation, there will then be an `OnRemove` notification, but there will be no `OnUpdate` notification, so it will not be possible for an application to reliably detect when a simple `RefreshMovie` or `RefreshEpisode` call has finished updating the library.

For apps that need to know when the library update is complete, it's probably best to just stick with the existing `RemoveFoo`/`ScanLibrary` approach.

**Comment by MilhouseVH** [comment]
I had added support for these `RefreshFoo` methods to texturecache.py, but given that it is impossible to serialise the calls (as the caller never knows when the method has finished) I'll shortly be disabling support by default and reverting to `Remove`/`Scan`. Shame to see this effort go to waste - without a `Finished` notification these new methods are in some circumstances unusable.

**Comment by Montellese** [comment]
@MilhouseVH: no offense but you should know better than to complain about missing features on github.
And while we're on it I'm sick of doing stuff for JSON-RPC because no matter what I add, it's never good enough and people always come back with what else they want.

This PR started out because I wanted to get the video item refreshing logic in line with the rest of the video library changes I made moving specific actions to jobs. I then realized that this would also finally allow JSON-RPC to make use of this functionality which was impossible before and was something people have been asking for for several years. So actually that's just a nice by-product but obviously that's not good enough. Maybe I should revert the JSON-RPC change from this PR because it's obviously unusable and is "effort gone to waste".

**Comment by MartijnKaijser** [comment]
Well said

**Comment by MilhouseVH** [comment]
@Montellese: No offence taken, and I mean no offence to you either.

Obviously your efforts are appreciated, and these new methods will be of benefit to users (probably), however I'm just highlighting one or two use cases where the current implementation is a problem and which makes these methods, for me anyway, unusable.

If you don't feel it appropriate to add a "Finished" notification that is of course your prerogative, although not one I really understand having tried to use these new methods in anger.

**Comment by Montellese** [comment]
I never said adding a set of notifications is wrong or inappropriate, I just don't have the time to do it myself and I'm pretty sure whatever I would come up with someone else would feel like it's incomplete or not done in the right way because it doesn't fit hat person's exact use case.

And coming here and saying things like
> I added it but I'll have to disable it again

and
> Shame to see this effort go to waste

just looks to me like you're trying to make me feel bad about not having added these notifications. There's no additional and/or constructive information in these comments. You had already made your point that it isn't good enough for your use case (which should also have happened in the forum and not here IMO).

**Comment by MilhouseVH** [comment]
Yeah, true, I apologise for goading a reaction.

**Comment by tamland** [comment]
Another regression I found: before this PR it used to show a modal dialog with progress when downloading (and was cancellable). This is gone. Instead gui hangs until it completes. This goes for both when pressing \<i\> on an unscanned video and using "Refresh".

**Comment by Montellese** [comment]
@tamland: That's odd as it explicitly sets the progress dialog in https://github.com/xbmc/xbmc/pull/7306/files#diff-1f0dbc342bd6b14488222febada4800aR91 and also passes it on to `CVideoInfoScanner::FindMovie()` at https://github.com/xbmc/xbmc/pull/7306/files#diff-1f0dbc342bd6b14488222febada4800aR148.

**Comment by tamland** [comment]
I don't think you ever open the dialog. `SetProgressDialog` just sets a member variable. It definitely isn't showing in gui..

**Comment by Montellese** [comment]
Yes but calling `CProgressJob::SetTitle()` or `SetProgress()` should automatically open the progress dialog if it hasn't already been opened. I'm looking into it.

**Comment by Montellese** [comment]
@tamland: see #7918.

**Pull request merged**
