### PR TITLE
[Depends] Replace distribute with setuptools

### PR DESCRIPTION
**Pull request by mrdominuzq**
## Description
Setuptools should be installed as native instead of target.  And now setuptools depends on things that depend on setuptools. So I think it's easier to install the whl file with pip

I also added openssl because pip needs it

## Motivation and Context
We use native python to compile so setuptools belongs there

## How Has This Been Tested?
build test

## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Razzeee** [comment]
Would be cool, if you could fill your PR description with a little more life. Your code/reference might speak for itself, but it's really helping us to understand things.
And please set the checkboxes, that apply.

**Comment by mrdominuzq** [comment]
Yes of course :)

**Comment by wsnipex** [comment]
Please explain what issue this fixes, since it seems totally wrong to me. We certainly won't include openssl in native depends.

**Comment by mrdominuzq** [comment]
Pycryptodome can't find setuptools, this fixes it. Pip needs openssl.

**Review by wsnipex — CHANGES_REQUESTED** [review]
We build pycryptodome just fine, so this PR doesn't fix a real issue. Instead it requires adding native openssl without any benefit.
If you can make it work without native openssl, it'd be ok.

**Comment by mrdominuzq** [comment]
I Think That if a patch is needed to build then there's a issue :) but minor detail. Another issue is the circular dependencies. Newer setuotools depends on pyparsing and pyparsing depends on setuptools. I will look into installation without openssl :)

**Comment by Razzeee** [comment]
@mrdominuzq Did you come up with something?

**Comment by mrdominuzq** [comment]
yes just didnt have the time. new job and all that :)

will see if i can do something today.

**Comment by mrdominuzq** [comment]
opened a new PR #12804 
The other branch got fucked :P

**Pull request closed without merging**
