### PR TITLE
Fix content types. Fixes #16392

### PR DESCRIPTION
**Pull request by razzeee**
@phil65 wished for some fixes for content types.

Some of the music problems are oversight of the now infamous #8011 
Everything is pretty self explanatory, we're just making sure not to always set "files" and fall back to "" if it really should be "".

### CODE REVIEW

**Comment by phil65** [comment]
Thx.
Quick roundup for @ronie: This makes sure that the music library root for example does not return "files" as a content type. That way it is in line with movie section and can help skinners to choose the proper viewtype for that type of content.

In the long-term I would prefer to set all those paths to content type "nodes" or something similar instead of "", but that´s ofc not related to this PR.

**Comment by DaveTBlake** [comment]
Might want to check out this ticket too http://trac.kodi.tv/ticket/16392 possibly related.
At least @jeroenpardon may like to know it about this.

**Comment by Razzeee** [comment]
Yep, just seen that. Should also be fixed, by what I did here.

**Comment by ronie** [comment]
@phil65 thx, haven't tested it yet, but description looks good.

**Comment by phil65** [comment]
@Razzeee I now tested and everything looks fine now. Thx for fixing this.

**Comment by phil65** [comment]
I think I was too quick here. Content type for *library root --> files* is correctly set to "files", but *library root --> files --> some subfolder* switches back to "" instead of "files". It should stay "files" for all subfolders in files section.

**Comment by Razzeee** [comment]
Will look at that later. Can you check if video also has this bug?

**Comment by Razzeee** [comment]
Found another problem with videos, that now should be gone.

**Comment by Razzeee** [comment]
Would like to merge this.

jenkins build this please

**Comment by DaveTBlake** [comment]
Before we merge this can we be sure it hasn't broken file view of intrinsic tag data again.

I am doing some combined testing of recent changes, so it could be something else, but I have seen some problems. So hold off until I have nailed this down please.

**Comment by Razzeee** [comment]
Sure, that's why we ask before merging.

**Comment by DaveTBlake** [comment]
My testing has been inconclusive I'm afraid. Frustrating!!

There are times when going back to a music souce in file view, although tags were scanned on first visit, it does not get scanned and is therefore unable to show tag data. But I have been unable to tie the behaviour to this change, nor to repeat it consistently. It could be down to list caching I guess.

I would prefer someone else gives file view a good testing, may be @jjd_uk if he is back, but not going to press if you want to continue.

**Comment by phil65** [comment]
I would like to have this pulled in since it fixes some obvious bugs.

**Comment by MartijnKaijser** [comment]
Yep. Get it merged and see what's left to fix.

**Comment by guidosarducci** [comment]
FYI, this change does not resolve a skin problem I have seen since first running Jarvis, where VideoPlayer.Content categorizes my library TV shows as "files" instead of "episodes".

Non-library videos identify as "files" and library movies identify as "movies", but I haven't been able to check "livetv" or "musicvideos" content.

This is with a build from recent commit 6bcc4db1129fd65a3d97c9fa9a39437839622985, which includes this merge, running on android AFTV v1. All my userdata/libraries were copied from Isengard, where this all works fine.

**Pull request merged**
