### PR TITLE
FIX: [cmake] use specific Android profile (so versions)

### PR DESCRIPTION
**Pull request by koying**
Use android cmake profile (which handles the android-specific non-versioned .so) and get-rid of last RPL hacks

### CODE REVIEW

**Comment by koying** [comment]
jenkins build this please

**Comment by stefansaraev** [comment]
that means rpl-native can be dropped. trivial cleanup: feel free to pick and squash https://github.com/stefansaraev/xbmc/commit/626279a106833ae10d1d65b0ae7db17857147115 https://github.com/stefansaraev/xbmc/commit/4234faab86f97a976f832072c3f821b7cec4ac22

**Comment by koying** [comment]
@stefansaraev Applied, thanks.

**Review by wsnipex — APPROVED** [review]
great :+1:

**Comment by koying** [comment]
jenkins build this please

**Comment by koying** [comment]
@hudokkow @fetzerch @Rechi Any comments?

**Review by Rechi — APPROVED** [review]
can't say much about the changes, but they look good to me

**Comment by hudokkow** [comment]
Same ^^
wsnipex is our resident depends guru

**Pull request merged**
