### PR TITLE
Change Python sys.path population order

### PR DESCRIPTION
**Pull request by romanvm**
Now third-party dependencies are added after Python standard library path as it should be.

## Motivation and Context
Previously addon dependencies paths were added to `sys.path` list before Python standard library paths. It did not cause problems earlier (?) but in Python 3 it prevents from using `future` library for converting code from Py2 to Py3 because it requires the standard library paths to be inserted before its own paths.
Also this is more correct for technical POW, because normally in regular server/desktop Python `sys.path` is populated in the following order:

- Current script path.
- Standard lib paths from a current virtual environment.
- Standard lib paths from the main Python installation.
- Third-party lib paths from `site-packages` in the virtual environment.

## How Has This Been Tested?
I built and installer and checked `sys.path` in a debugger. It works as expected:
```
(Pdb) pp sys.path
['D:\\Kodi18_Py3\\portable_data\\addons\\addon.tester',
 'D:\\Kodi18_Py3\\system\\python\\DLLs',
 'D:\\Kodi18_Py3\\system\\python\\Lib',
 'D:\\Kodi18_Py3\\python36.zip',
 'D:\\Kodi18_Py3',
 'D:\\Kodi18_Py3\\system\\python\\Lib\\lib-dynload',
 'D:\\Kodi18_Py3\\system\\python\\Lib\\lib-dynload\\RelWithDebInfo',
 'D:\\Kodi18_Py3\\system\\python\\Lib\\plat-win32',
 'D:\\Kodi18_Py3\\system\\python\\Lib\\lib-tk',
 'D:\\Kodi18_Py3\\system\\python',
 'D:\\Kodi18_Py3\\system\\python\\lib\\site-packages',
 'D:\\Kodi18_Py3\\portable_data\\addons\\script.module.bottle\\lib',
 'D:\\Kodi18_Py3\\portable_data\\addons\\script.module.certifi\\lib',
 'D:\\Kodi18_Py3\\portable_data\\addons\\script.module.chardet\\lib',
 'D:\\Kodi18_Py3\\portable_data\\addons\\script.module.idna\\lib',
 'D:\\Kodi18_Py3\\portable_data\\addons\\script.module.requests\\lib',
 'D:\\Kodi18_Py3\\portable_data\\addons\\script.module.urllib3\\lib',
 'D:\\Kodi18_Py3\\portable_data\\addons\\script.module.web-pdb\\libs']
```

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Rechi** [comment]
@romanvm do you think this would break something for python 2.7, as you have PRed it against feature_python3 and not master?

**Comment by romanvm** [comment]
I'm not sure if there won't be any merge conflicts. And this patch is only needed for `future` library to work with Python 3 in Kodi.

**Comment by Rechi** [comment]
> I'm not sure if there won't be any merge conflicts.

Don't care about merge conflicts, the feature branch can be rebased if merge conflicts with the master branch occur.

> And this patch is only needed for future library to work with Python 3 in Kodi.

Sure, but we should get already as much as possible into master (if it doesn't break anything).

**Comment by MilhouseVH** [comment]
FYI: I included this PR in last night's LibreELEC [RPi/RPi2](https://forum.kodi.tv/showthread.php?tid=298461&pid=2679867#pid2679867) and [Generic (x86_64)](https://forum.kodi.tv/showthread.php?tid=298462&pid=2679868#pid2679868) test builds.

Seems OK so far (tested Netflix, Youtube addons).

**Comment by romanvm** [comment]
> Don't care about merge conflicts, the feature branch can be rebased if merge conflicts with the master branch occur.

Ok, if merging Py3 branch to master won't restore the old behavior. Also we will need to publish Kodi test build with Python 3 so that addon developers can test their addon compatibility, and those test builds must include this update.

So what's the best course of action for me? Close this PR and make a new one based on `master`?

**Comment by Rechi** [comment]
Just update your branch to only contain the one commit on top of master.

**Comment by ronie** [comment]
imo it's not worth the risk.. some gut feelings tells me this will cause breakage one way or another.
most likely on linux systems, which come with a lot of python modules pre-installed.

python modules in our repo could be either newer or older than the ones shipped with linux.
if we suddenly start to prefer system modules above repo modules, breakage can occur.

imo i'd be better to merge this into the py3 branch, which is going to break all addons anyway.

just my 2 cents...

**Comment by tamland** [comment]
Where did you find this list? I'm pretty sure the normal order is: current script path, standard lib paths, user site, system site. (This patch inverts the last two)

**Comment by romanvm** [comment]
Also, although the general principle of this update can be applied to both Py3 and master (Py2) branches, respective pieces of code are slightly different in those branches.
Py3:
```c++

  // we want to use sys.path so it includes site-packages
  // if this fails, default to using Py_GetPath
  PyObject *sysMod(PyImport_ImportModule((char*)"sys")); // must call Py_DECREF when finished
  PyObject *sysModDict(PyModule_GetDict(sysMod)); // borrowed ref, no need to delete
  PyObject *pathObj(PyDict_GetItemString(sysModDict, "path")); // borrowed ref, no need to delete

  if (pathObj != NULL && PyList_Check(pathObj))
  {
    for (int i = 0; i < PyList_Size(pathObj); i++)
    {
      PyObject *e = PyList_GetItem(pathObj, i); // borrowed ref, no need to delete
      if (e != NULL && PyUnicode_Check(e))
        addNativePath(PyUnicode_AsUTF8(e)); // returns internal data, don't delete or modify
    }
  }
  else
  {
      std::string GetPath;
      g_charsetConverter.wToUTF8(Py_GetPath(), GetPath);
      addNativePath(GetPath);
  }
```
master:
```c++

```

**Comment by romanvm** [comment]
> Where did you find this list? I'm pretty sure the normal order is: current script path, standard lib paths, user site, system site. (This patch inverts the last two)

Just print `sys.path` from inside a virtual environment and see. Virtual environment's `site-packages` always comes the last and system `site-packages` and `dist-packages` are excluded.  We don't have virtual environments in Kodi but addon dependencies can be considered as rough equivalent so they should come last as well.

**Comment by romanvm** [comment]
@ronie good point about possible conflicts between system-wide modules and Kodi modules. And we can't exclude system `site-packages` because, for example, on LibreElec this directory contain third-party binary modules that are normally included with Kodi, like Pillow or Pycrypto. But we do need `future` library to work to simplify addon migration.

**Comment by tamland** [comment]
> Just print sys.path from inside a virtual environment and see. Virtual environment's site-packages always comes the last and system site-packages and dist-packages are excluded. We don't have virtual environments in Kodi but addon dependencies can be considered as rough equivalent so they should come last as well.

Virtual env doesn't include system site (and it's a terrible hack, so not the place i would look for guidance). The non-virtualenv order for me is: 
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/home/user/.local/lib/python3.6/site-packages
/usr/lib/python3.6/site-packages

I.e. user site before system. And the reason for this is to always make it possible to override system package. If it's not in this order, any random thing the user installs to the system can start breaking kodi add-ons.

**Comment by MilhouseVH** [comment]
I'll drop this from future test builds until there's agreement on how to proceed.

**Comment by romanvm** [comment]
@tamland 
>Virtual env doesn't include system site (and it's a terrible hack, so not the place i would look for guidance).

Hack or not, but using a virtual environment is a standard practice in modern Python development/deployment. Nobody in their right mind pollutes global sites with application-specific dependencies. I'm more concerned about @ronie 's point about system/addon dependencies conflict that is true for Python 3 as well. But then again, we do need `future` for smooth migration. If somebody has alternative suggestions besides an ugly hack to detect the presence of `script.module.future` in addon's dependencies so that to insert it the very last to `sys.path`, I'm open to suggestions.

**Comment by tamland** [comment]
> Hack or not, but using a virtual environment is a standard practice in modern Python development/deployment. Nobody in their right mind pollutes global sites with application-specific dependencies. I'm more concerned about @ronie 's point about possible system/addon dependencies conflict that is true for Python 3 as well. But then again, we do need future for smooth migration. If somebody has alternative suggestions besides an ugly hack to detect the presence of script.module.future in addon's dependencies so that to insert it the very last to sys.path, I'm open to suggestions.

That wasn't the point. Distos install all kinds of applications to this dir and it's nothing you can do about it. I'm saying the same thing as @ronie. But if our modules are between standard lib and system site as I said there wont be any breakage and the future module will still be after standard lib.

If this future module doesn't handle that, then it won't work on in a standard linux python setup either..

**Comment by romanvm** [comment]
> If this future module doesn't handle that, then it won't work on in a standard linux python setup either..

It just needs to be after the standard lib paths, either in global (user or system) or virtual env's `site-packages`. Since we cannot install anything there from Kodi (and on some systems like Windows or Android) Kodi is shipped with its own self-contained Python), the only way we can place `future` after the standard lib is to change how module dependencies are inserted in `sys.path`. Again, I agree with the point about potential version conflicts on Linux systems, but the only solution I can think of now is `script.module.future` specific hack in `PythonInvoker.cpp`.

**Comment by romanvm** [comment]
So what options do we have, except for `script.module.future` specific hack to `PythonInvoker.cpp` like this one?
```c++
  std::string futurePath; // Path fo script.module.future package

  // add all addon module dependencies to path
  if (m_addon)
  {
    std::set<std::string> paths;
    getAddonModuleDeps(m_addon, paths);
    for (std::set<std::string>::const_iterator it = paths.begin(); it != paths.end(); ++it)
    {
      if ((*it).find("script.module.future") == std::string::npos)
        addPath(*it);
      else
        futurePath = *it;
    }
  }
  else
  { // for backwards compatibility.
    // we don't have any addon so just add all addon modules installed
    CLog::Log(LOGWARNING, "CPythonInvoker(%d): Script invoked without an addon. Adding all addon "
        "modules installed to python path as fallback. This behaviour will be removed in future "
        "version.", GetId());
    ADDON::VECADDONS addons;
    CServiceBroker::GetAddonMgr().GetAddons(addons, ADDON::ADDON_SCRIPT_MODULE);
    for (unsigned int i = 0; i < addons.size(); ++i)
    {
      std::string path = CSpecialProtocol::TranslatePath(addons[i]->LibPath());
      if (path.find("script.module.future") == std::string::npos)
        addPath(path);
      else
        futurePath = path;
    }
  }

  // we want to use sys.path so it includes site-packages
  // if this fails, default to using Py_GetPath
  PyObject *sysMod(PyImport_ImportModule((char*)"sys")); // must call Py_DECREF when finished
  PyObject *sysModDict(PyModule_GetDict(sysMod)); // borrowed ref, no need to delete
  PyObject *pathObj(PyDict_GetItemString(sysModDict, "path")); // borrowed ref, no need to delete

  if (pathObj != NULL && PyList_Check(pathObj))
  {
    for (int i = 0; i < PyList_Size(pathObj); i++)
    {
      PyObject *e = PyList_GetItem(pathObj, i); // borrowed ref, no need to delete
      if (e != NULL && PyUnicode_Check(e))
        addNativePath(PyUnicode_AsUTF8(e)); // returns internal data, don't delete or modify
    }
  }
  else
  {
      std::string GetPath;
      g_charsetConverter.wToUTF8(Py_GetPath(), GetPath);
      addNativePath(GetPath);
  }

  Py_DECREF(sysMod); // release ref to sysMod

  // Add the path to script.module.future to sys.path as the last entry.
  // This is needed for "future" Python 2->3 conversion library to work properly.
  if (!futurePath.empty())
    addPath(futurePath);
```

**Comment by tamland** [comment]
If you look at the code comment it says "we want to use sys.path so it includes site-packages. if this fails, default to using Py_GetPath" which sounds too me it's possible to get them separately and insert addon paths in the middle.

**Comment by romanvm** [comment]
@tamland I'm not sure what you mean by "get them separately". From what I see this part simply iterates over `sys.path` list of the main Python interpreter to add its elements to `sys.path` of a sub-interpreter where an addon is launched or, if `sys.path` is not initialized, appends contents of `PYTHONPATH` environment variable to that of a the sub-interpreter. And `PYTHONPATH` is just a string containing a list of paths delimited by OS-specific separators.

We can parse `sys.path` or `PYTHONPATH` to detect where standard lib paths end and sites (user or system) begin, but this may be tricky considering that those lists have different structure on different OSes.

**Comment by tamland** [comment]
Guess it from sys.path. It's always called `site-packages` right? There's also this: https://docs.python.org/3.5/library/site.html#site.getsitepackages

**Comment by romanvm** [comment]
> Guess it from sys.path. It's always called site-packages right?
Not quite. On some Linux distributions there are `dist-packages` dirs.

> There's also this: https://docs.python.org/3.5/library/site.html#site.getsitepackages

This is good but we need standard lib paths as well and there's no easy way to get only those. Also there's a fallback route with `Py_GetPath()` (that gets `PYTHONPATH` list as a string) for the case when `sys.path` is not initialized.

**Comment by romanvm** [comment]
After some additional research I found out that `future` uses different layout for Python 3. I'm closing this PR as not relevant.

**Pull request closed without merging**
