### PR TITLE
[VideoDatabase] Save correct stream details for  multi-episode Blurays.

### PR DESCRIPTION
**Pull request by 78andyp**
## Description

I have The Last of Us on UHD. There are multiple episodes per ISO.

I noticed that whenever I watched an episode - the episode details shown at the bottom right change for every episode on the disc.

If I then watch the next episode - again the details for every episode on the disc change to the episode just watched.

## Motivation and context

Firstly this is wrong. It appears the the `streamdetails` table only allows one stream per filename (the filename is the <disc>.iso).

Secondly, i've been working on some code to make episode selection from ISO easier (trying to make an educated guess as to which title(s) are which episode) - and part of this is much easier if the correct episode length is recorded for each episode.

Base
Having just refreshed from scraper - no details shown and duration from scraper.
image
image

Before
Having just watched episode 1 - the details for both Episodes 1 and 2 (both on first ISO) have changed.
image
image

After
Having just watched episode 1 - only episode 1 has changed
image
image

Then watching episode 2 - only 2 has changed and 1 is preserved.
image
image

## How has this been tested?

The only fix I can think of is adding an additional field in the `streamdetails` table - `iEpisodeHash`. This defaults to -1 (the default in a `VideoTagInfo`). This then allows more than one stream per filename.

BUT
1) This requires bumping the database schema version to 125.
2) All existing `streamdetails` will have their `iEpisodeHash` set to -1 so effectively become orphan `streamdetails` for the episodes with `streamdetails` already in the table - I'm not sure the best way to deal with this - both from a wasted space in database perspective and also it effectively 'resets' the information for all episodes that have already been watched.

Other than that it works on my test build.

As above.

Window 11 x64.

## What is the effect on users?

See BUTS above.

Should mean accurate episode details reported per episode for those on discs.

Thanks for looking at this. I hope I haven't buggered anything up.
If there is a better way of doing this I'd be interested to learn.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CrystalP** [comment]
The idea of subdividing the stream information of a TV show ISO into episodes seems fine.

For comparison, did you check what happens when a BD/DVD is ripped as a file structure rather than ISO?

Would extras or other assets in the same ISO fit in the same model? Movies can also have multiple editions on the same disc using seamless branching IIRC.
That's not a request for changes, just thinking about the design and capabilities down the line.

A different category of files containing other files would be archives. I don't know how they're handled by Kodi though.

Do others want to chime in?

**Comment by 78andyp** [comment]
> The idea of subdividing the stream information of a TV show ISO into episodes seems fine.
> 
> For comparison, did you check what happens when a BD/DVD is ripped as a file structure rather than ISO?
> 
> Would extras or other assets in the same ISO fit in the same model (assuming core/nfo/scrapers are modified to recognize them)? Movies can also have multiple editions on the same disc using seamless branching IIRC. That's not a request for changes, just thinking about the design and capabilities down the line.
> 
> A different category of files containing other files would be archives. I don't know how they're handled by Kodi though.
> 
> Do others want to chime in?

Thanks.

Regarding BDMV folders - this seems completely messed up in 21b1 anyway.

I have a source that simply contains the files of one disc (Vikings S01 E01-03):

image

After scraping I get:
image

When I use this PR I get the same - and when I play the episode 1 entry that works - that is reflected correctly in `streamdetails`.

So - I think this code works and doesn't break anything for folders - but BDMV folders needs fixing - unless I'm doing anything wrong.

**Comment by 78andyp** [comment]
I found a disc that had a special with the same 'episode' number as a real episode - so I've updated the code to include a hash equal to `(season * 1000) + episode` so the details remain unique.

**Comment by 78andyp** [comment]
Messed up rebase. Will close and make new commit.

**Pull request closed without merging**
