### PR TITLE
Do not return plain const from `CCompileInfo::GetWebserverExtraWhitelist()`

### PR DESCRIPTION
**Pull request by jfly**
This is in response to this PR feedback: https://github.com/xbmc/xbmc/pull/21113#discussion_r835767499

## Motivation and context

Followup from this PR feedback: https://github.com/xbmc/xbmc/pull/21113#discussion_r835767499

## How has this been tested?

I've confirmed that the code still compiles.

## What is the effect on users?

No effect

## Screenshots (if appropriate):

N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by howie-f** [comment]
thanks. i would only suggest to change the commit message and pr description to something like `do not return plain const from CCompileInfo::GetWebserverExtraWhitelist()`
this change is fine.

**Comment by jfly** [comment]
Oops, I have no idea what I was thinking when I wrote that original commit message :p. Fixed!

**Review by garbear — APPROVED** [review]
LGTM

**Review by wsnipex — APPROVED** [review]

**Comment by howie-f** [comment]
jenkins build and merge

**Pull request merged**
