### PR TITLE
[cmake] allow RPi to build with lirc support

### PR DESCRIPTION
**Pull request by lrusak**
## Description

Allow the Raspberry Pi to be built with lirc and eventclient support

## Motivation and Context

Fixes lirc not being available on RPi when building with cmake

## How Has This Been Tested?

Tested in LibreELEC

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fetzerch** [comment]
lgtm, thanks

**Comment by lrusak** [comment]
Wait on this for a sec, still needs some more testing

**Comment by lrusak** [comment]
false alarm, this is good to go :+1:

**Comment by lrusak** [comment]
@fetzerch added a fixup

**Comment by MilhouseVH** [comment]
All good with this.

**Comment by fetzerch** [comment]
@lrusak: thx, can you squash the commits please?

**Comment by lrusak** [comment]
You should be able to squash at merge no?

**Comment by fetzerch** [comment]
Good point, I see this option for the first time now ;)
jenkins build this please

**Pull request merged**
