### PR TITLE
[videoplayer] refactor/cosmetics GetExternalStreamDetailsFromFilename

### PR DESCRIPTION
**Pull request by ace20022**

### CODE REVIEW

**Comment by ace20022** [comment]
@FernetMenta for review. the second commit seems somewhat lost, but it bugged me for a while now.

**Comment by ace20022** [comment]
nvm I'll move the second commit to another pr.

**Comment by FernetMenta** [comment]
+1

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
je jenkins build this please

**Pull request merged**
