### PR TITLE
Limit Gui Rendering when playing fullscreen video

### PR DESCRIPTION
**Pull request by fritsch**
Allow Render skips:
This is work done by @popcornmix and @FernetMenta monkeyed together by me. This was tested for RPB in the @Milhouse builds for months. It was also tested be volunteers of OpenELEC and OSMC during the easter weekend.

IMX specifics:
IMX is currently too slow for rendering 50 progressive frames while anything from fb0 is blended into the image. We found out, that the hw is capable enough to render OSD, subs, etc. with 15 fps while in fullscreen. Therefore the new special settings.

RPB:
I adjusted popcornmix's work to fit the new string numbers

### CODE REVIEW

**Comment by fritsch** [comment]
jenkins build this please

**Comment by fritsch** [comment]
This can btw. also help Baytrail or HD2000 Users (Celeron NUC1) or SNB users with old intel GPUs.

**Comment by FernetMenta** [comment]
please squash at least the first 2 commits to get a clean diff.

**Comment by fritsch** [comment]
Will do, I did not want to "anonymize" your authorship - but that makes obviously sense.

**Comment by popcornmix** [comment]
I think you also need https://github.com/popcornmix/xbmc/commit/44e06f53da02dd30749266115e18a2049347dd11
Otherwise you get occasional artefacts (e.g. last frame of fade animation remains on screen)

**Comment by FernetMenta** [comment]
yes, this is needed

**Comment by fritsch** [comment]
Thx much. Added into the first commit where it belongs (three commits squash together) sorry @ jenkins

**Comment by fritsch** [comment]
The one @popcornmix referenced:
>Otherwise you get occasional artefacts (e.g. last frame of fade animation remains on screen)

**Comment by fritsch** [comment]
As we are already on the cherry-pick / nit pick: What about adding that to linux, too - but set it to "Off" by default, cause of the know bad gpu systems?

**Comment by FernetMenta** [comment]
this change is only useful for systems with separate layers for gui and video. while the video layer goes fps of source, the gui layer reduces rendering. how would this apply to systems like NUC?

**Comment by fritsch** [comment]
>this change is only useful for systems with separate layers for gui and video. while the video layer goes fps of source, the gui layer reduces rendering. how would this apply to systems like NUC?

Had been a nice addition for this poor underwowered HW, but makes sense - have only looked at the relevant logic here: https://github.com/fritsch/xbmc/blob/dceab971ed71caa55fe4a50af9d68ff0cf170ae8/xbmc/Application.cpp#L2457

But that answers the question

**Comment by fritsch** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
+1

**Comment by popcornmix** [comment]
I've updated newclock4 branch with the version from this PR and it behaves as expected.
No complaints from last night's Milhouse build, so +1 here.

**Comment by fritsch** [comment]
@popcornmix I had to revisit it today, after the comments and hints by @da-anda  - you are also fine with the updated PR? Some strings have changed and cause of the max values the 24 value was exchanged with 25.

**Comment by popcornmix** [comment]
Updated, and still seems fine.

**Comment by fritsch** [comment]
Thanks much.

jenkins build this please

**Comment by FernetMenta** [comment]
@fritsch just noticed on Linux:
CSettingsManager: requested setting (videoplayer.limitguiupdate) was not found

**Comment by fritsch** [comment]
@FernetMenta So it defaults to 0 right?

**Comment by fritsch** [comment]
Two options:
a) #ifdeffery
b) adding to all settings.xmls?

**Comment by MartijnKaijser** [comment]
c) only add to settings.xml and set it hidden. imx and rpi xml should override the hidden from the main setting.xml

**Comment by fritsch** [comment]
@MartijnKaijser exactly :-) thx. Will do

**Comment by FernetMenta** [comment]
it is only used in a single place in the code. why adding it to all platforms and hide the actual purpose in the code? it should be made clear for everyone reading the code what's the purpuse of this setting is. an ifdef is the appropriate method for those kind of tasks

**Comment by FernetMenta** [comment]
and don't forget the comment that it is only for systems with multiple layers :)

**Comment by fritsch** [comment]
Raspberry Pi, IMX anything else? The other Bypass renderer?

**Comment by fritsch** [comment]
See: https://github.com/xbmc/xbmc/pull/6923

**Comment by DBMandrake** [comment]
@fritsch 

OSMC has these patches in the most recent Kodi build and during testing I think I have uncovered an unintended side effect of the GUI rate limit on imx6 - it seems to rate limit software rendered video as well as the GUI overlays...

For example if I play a WMV3 (currently only rendered in software) with "Limit GUI updates when playing video" set to 12fps, although codecinfo reports approx 22fps playback is extremely stuttery, with a visual estimate of only about 5fps at most. (Not even the 12fps set in the GUI limit)

Setting "Limit GUI updates when playing video" to Off restores normal playback of software rendered video.

**Comment by fritsch** [comment]
@DBMandrake: Haha - yes makes sense. This does not think of non hw accelerated playback. Can you verify, that this: https://github.com/fritsch/xbmc/commit/dceab971ed71caa55fe4a50af9d68ff0cf170ae8#diff-63246197ac0f0ac89358c1155ad21d5bR2485 condition is also hit?

@FernetMenta that's in deed a design flaw.

**Comment by fritsch** [comment]
@popcornmix the PI should show the same issue when doing mpeg-2 playback without licence.

**Comment by popcornmix** [comment]
Pi still uses MMALRenderer for software playback - not GLES, so doesn't have this issue.

**Comment by fritsch** [comment]
Oki, then we need some intelligent query of IsVideoLayer / IsGuiLayer to find out which is currently doing the render work.

**Comment by FernetMenta** [comment]
calling IsVideoLayer doesn't sound too sophisticated to me :)

**Comment by fritsch** [comment]
@FernetMenta ... here is a video for you: https://www.youtube.com/watch?v=BKorP55Aqvg 

PR welcome.

**Comment by FernetMenta** [comment]
perfect, so I will do the travel arrangements for you :)

**Comment by fritsch** [comment]
Hehe - yeah, will do this evening.

**Comment by fritsch** [comment]
@DBMandrake I posted a fix into your IRC channel ... if you want to test, you are welcome.

**Comment by DBMandrake** [comment]
Hi @fritsch - I don't use IRC so wouldn't have seen that, but I will try the patch from #6944 and comment there if it is good. Thanks.

**Pull request merged**
