### PR TITLE
dvdplayer - dispose ffmpeg hw decoder prior to opening a new one

### PR DESCRIPTION
**Pull request by FernetMenta**
@Memphiz this should fix the single codec issue reported in http://trac.kodi.tv/ticket/14978

### CODE REVIEW

**Comment by Memphiz** [comment]
will do a testbuild and give it to the user - thx a bunch @FernetMenta

**Comment by FernetMenta** [comment]
@Memphiz updated, could you provide a new testing build for for ticket?

**Comment by MartijnKaijser** [comment]
@FernetMenta triggered new one. http://jenkins.kodi.tv/job/OSX-64/5215/

**Comment by FernetMenta** [comment]
It is confirmed working for OSX but before backport it would be nice if someone could test on Windows.

jenkins build this please

**Comment by afedchin** [comment]
I'll test this asap

**Comment by afedchin** [comment]
after quick test, seems this works fine on windows

**Pull request merged**
