### PR TITLE
[estuary] fix overlap in fanart view

### PR DESCRIPTION
**Pull request by howie-f**
## Description
cleans a little overlap in Fanart-View of estuary.

for a very long time i'm thinking.. that must be an accident, this is not intended. but could be it is just me.
not sure if it's fixed correctly, but the result is fine imo.

## Screenshots (if appropriate):

before:
ugly

after:
cute

## Types of change

- [X] **Cosmetic change** (non-breaking change that doesn't touch code)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document

### CODE REVIEW

**Review by jjd-uk — COMMENTED** [review]
I'm not sure that this is the correct way to go about this. It could also be done by changing the constant **list_y_offset** from 0 to 20 at https://github.com/xbmc/xbmc/blob/master/addons/skin.estuary/xml/Includes.xml#L35 as that would make it consistant and also do the scroll bars, however that obviously has much wider impact on everywhere that **list_y_offset** is used. 

Let's wait for @ronie's view on this.

**Comment by howie-f** [comment]
another option would be to change `<movement>` like here https://github.com/howie-f/xbmc/commit/2b28d6a4e2d2325dee926dcd0491c358f14d87e2

it would result in a -- nearly -- consistant look with pvr.
screenshot00000

pvr channels unchanged:
screenshot00001

**Comment by jjd-uk** [comment]
That change to the **<movement>** value within `<include name="ListContainer">` looks to be the best option to me.

**Comment by ronie** [comment]
looks good to me, thx!

**Pull request merged**
