### PR TITLE
Update win32 installer with inputstream and Peripheral addons

### PR DESCRIPTION
**Pull request by MartijnKaijser**

### CODE REVIEW

**Comment by Tolriq** [comment]
@MartijnKaijser please add "/norestart" to vc2010\vcredist_x86.exe call as it's the one that triggers a restart without asking user in the middle of installation.

Proper way would be to also add the switch to 2013 / 2015 and if any result code is 3010 ask for a reboot at the end of Kodi setup. 

Note that vc2008 does not support this parameter.

**Comment by MartijnKaijser** [comment]
Stop commenting in unrelated PRs!

**Comment by Tolriq** [comment]
Considering you update the exact file that needs update this PR sounds quite related. 
But I guess some things never change. I'll stop bothering and maybe make a PR in 2 years when this won't have been addressed ;)

**Comment by MartijnKaijser** [comment]
I don't give a damn what you think. Your attitude over the years makes my hate towards you grow day by day. Fact is I'm not alone in this.

**Comment by Tolriq** [comment]
At least you now publicly says you act by hate and not by reason.

I hate not being smart enough to not answer but well ;)

We could run a popularity check but your reputation is way worse than mine on a global level, I may pissed of a few people that does not like to be proven wrong, but at least I try to help and contribute to this project.
But I do not insult every user or external dev every 2 threads on forums.

I have no problem to stop helping or contributing or posting on github: open a public thread on the forums and have more people asking me to stop than people asking me to continue and I'll follow the vote.

**Pull request merged**
