### PR TITLE
[database] Reset path hashes when cleaning up files in video database

### PR DESCRIPTION
**Pull request by yol**
By performing a database clean-up, effectively the state in the database
is brought in sync with the state of the source in terms of files that
were removed from the source. This has to be reflected by updating the
hash of the path so the next library scan is not operating on outdated
information. However, since added items are not reflected, it would be
wrong to update the path hash to the actual directory contents. Just
resetting the hash for any path that had changes (i.e. saw removed
files) makes sure that the next library update does not miss both newly
added files and files that were removed before a clean-up but later
re-added.

Fix for https://forum.kodi.tv/showthread.php?tid=331918&pid=2747580#pid2747580

"After deleting a folder/moviefile from webdav-source and doing "clean library" kodi deletes movie from library - perfect. But if you re-add this folder/file to the webdav-source re-adding via "update library" does not rescan it to library."

### CODE REVIEW

**Comment by DaveTBlake** [comment]
Possibly a silly question (I really don't now about the video database) but why are the paths not deleted during cleanup?

Also could this be tagged with "video database", rather than generic database as it does not effect all or even most db.

**Comment by Rechi** [comment]
One path can contain multiple videos, but one could just delete some of them.

**Comment by pkerling** [comment]
> Also could this be tagged with "video database", rather than generic database as it does not effect all or even most db.

I don't think we have separate tags for video/music DB at the moment.

> One path can contain multiple videos, but one could just delete some of them.

Yeah, I'd even say this is rather common.

**Comment by DaveTBlake** [comment]
>I don't think we have separate tags for video/music DB at the moment.

That is true , for Git labels we don't but "[...]" can say what you like.  [music] gets used for the music library and so I assumed [video] for video library, maybe that is incorrect?  Also I think it helpful to write "video database" rather than "**the** database" when what you are working on is just video db related not music or texture databases. It's no big deal of course.

>One path can contain multiple videos, but one could just delete some of them.

Thanks for explanation. Also I can see that empty paths get deleted further down.

**Comment by pkerling** [comment]
> That is true , for Git labels we don't but "[...]" can say what you like. [music] gets used for the music library and so I assumed [video] for video library, maybe that is incorrect?

I have no idea honestly - I don't think we have a list for that. I assumed that `[video]` would be related to rendering?

> Also I think it helpful to write "video database" rather than "the database" when what you are working on is just video db related not music or texture databases.

Good point. I'll change the messages before merging.

**Comment by pkerling** [comment]
@notspiff Quick review would be appreciated

**Review by notspiff — APPROVED** [review]

**Pull request merged**
