### PR TITLE
Fixes and code improvements from game branch

### PR DESCRIPTION
**Pull request by garbear**
Just some improvements I made in the course of my retroplayer work. The bug fixes here don't affect Krypton, so they don't need to be backported.

For when master is branched for v18 development.

## Types of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by popcornmix** [comment]
Aren't the DVDCodecUtils patches real bug fixes that are wanted for Krypton?
Ping @fritsch

**Comment by garbear** [comment]
It's dead code in Krypton, though I've been using it in RetroPlayer for years. I guess we could backport them.

**Comment by FernetMenta** [comment]
I don't think we should patch dead code. Better remove that entire method and embed it into retro player.

**Comment by garbear** [comment]
it's only dead code in master. in my branch I've been maintaining it. it would be nice if we could save refactoring until after I merge the upcoming retroplayer pr due to the heavy load I'm under every time I rebase.

**Comment by FernetMenta** [comment]
I progress VP development on a separate brach like you do with retroplayer. When I merge VP changes back to master this dead code might be disappear. Please don't shift the rebase burdon to my side :)
This function is yours, please take ownership on your branch and delete the dead code here. This will eliminate any further merge conflicts.

**Comment by garbear** [comment]
Let's race ;) if you can wait two days to remove this dead code, I'll get retroplayer in and you can safely rebase.

**Comment by FernetMenta** [comment]
I can wait much longer than 2 days. But please don't make retroplayer dependent on code in VP.

**Comment by FernetMenta** [comment]
in other words, I am fine with this :)

**Comment by garbear** [comment]
RetroPlayer only depends on a small bit of VP code that you're trying to separate anyways, so it'll work well to highlight what we can compartmentalize out of the two players.

Here's the PR I'm opening later today: https://github.com/garbear/xbmc/compare/bc119a1b0...garbear:retroplayer?expand=1. The player core's commit will be labeled 0006.

**Comment by garbear** [comment]
jenkins build this please

**Pull request merged**
