### PR TITLE
[confluence] add "In progress" submenu entry to TV SHOWS - Depends on #8261

### PR DESCRIPTION
**Pull request by un1versal**
This PR depends on #8261, **without it this wont work**.

This PR is a re-hash of #4469 and solves the issues quoted as being blockers. TV Show users will certainly appreciate this.
its is **fully working and tested** with current/recent master by various users e.g. @sopparus and others not on Github. 

This has been requested for over 2 years in various threads and is condensed into http://forum.kodi.tv/showthread.php?tid=233374

This PR being up gives opportunity to more testing to happen by more people, as well as gaining some feedback. Its probably too late (sadly) for V16, but here is hoping for some positive and honest feedback.

If anyone who provides test builds is interested they can implement and widen the test audiences.

capture

### CODE REVIEW

**Comment by ronie** [comment]
looks good to me.

**Comment by HitcherUK** [comment]
And me, thanks.

**Comment by un1versal** [comment]
Thank you, fingers crossed  #8261 goes in and this shortly after.

**Comment by sopparus** [comment]
possible to merge this now?

**Comment by HitcherUK** [comment]
Still waiting on https://github.com/xbmc/xbmc/pull/8261

**Comment by un1versal** [comment]
> Still waiting on #8261

and #8261 will wait somemore now its waited so long that it needs rebasing json bumps again since its being left for some later date.

This will be up-to-date and rebased in 2 minutes.

**Comment by ronie** [comment]
thx!

**Pull request merged**
