### PR TITLE
[PAPlayer] Fix incorrect usage of GetPath in VideoPlayerCodec

### PR DESCRIPTION
**Pull request by enen92**
## Description
Found while working on other stuff, if a `plugin://` item reaches `PAPlayer.OpenFile` the codec determination (at least some of the logic) will be based on that path and not on the final url (which resulted from the resolution of the plugin url)

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Comment by fritsch** [comment]
Most likely correct, but I am not 100% sure.

@FernetMenta  is the only one that might know for 100%.

**Comment by FernetMenta** [comment]
Definitely wrong because strFile is used by tagloader. 

From the given description I can't tell what this change is trying to fix.

**Comment by enen92** [comment]
Sorry @FernetMenta, from your comment it wasn't clear, at least for me, which implementation is definitely wrong. Since the tagloader reads tags from the actual file and you did the same for the audio equivalent (see https://github.com/xbmc/xbmc/commit/1420712940861905c4d18a3fdb4d5221429ad816#diff-5ea9e71f6e2a8d47d312819084ba326cR55) I suppose (only now...) that you actually mean that this is right and the usage of `GetPath` is wrong. Can you please confirm?

Explaining a bit the problem, I found this while working on my other open PR (trying to make plugin resolution async). Since you said it couldn't be solved with a synchronous approach using the dialogbusy, I'm trying to implement a new approach using messages. Means that at some point the FileItem pointer is destructed. I ran into a dangling pointer case since there's a thread/job (tag loader) that is continuously trying to open the file (plugin://) until the point kodi ends up crashing. While I can't make the current kodi master crash because of this, the root cause the problem is this continuous loop trying to load a tag from a plugin:// path as if it was a readable file.

**Comment by FernetMenta** [comment]
Sorry, I was wrong. Tagloader wants dynpath as well. It would be less confusing if you just fixed the call to tagloaded. Why don't you eliminate that strFile and strFileToOpen crap. That's leftovers from the old days when players did not handle fileItem but only strings.

**Comment by enen92** [comment]
Yes, I got to the same conclusion yesterday although I was not around by that time - strFile and strFileToOpen can be removed since by the time the item gets here the dynpath already contains the final stream url. Thanks much for confirming and allowing this to go forward.
Regards

**Comment by enen92** [comment]
@fritsch back to you if possible, as it needs a green check mark to go in :)
Thanks

**Review by fritsch — APPROVED** [review]

**Pull request merged**
