### PR TITLE
added: FFmpeg-supplied RTMP support

### PR DESCRIPTION
**Pull request by notspiff**
This enables FFmpeg supplied RTMP.

It is not as capable as librtmp, but does fine in no-crypto situations. The add-on overrides.

### CODE REVIEW

**Comment by notspiff** [comment]
note this is incomplete, we need to change the build options for ffmpeg. will do if this is welcome.

**Comment by fritsch** [comment]
It is welcome. Please go ahead. Thanks much in advance.

**Comment by notspiff** [comment]
turns out ffmpeg build options have changed (?) and we now build all protocols so no buildsystem changes ncessary. the rebased branch should now build. @FernetMenta please review

**Comment by notspiff** [comment]
i have not yet runtime tested the rebased code so that should be done before the green is hit.

**Comment by notspiff** [comment]
lightly runtime tested with some streams. works as expected afaict.

**Comment by notspiff** [comment]
added a second commit which calls the global network init function of avformat. quells a runtime warning and adds forward compatibility.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
Is the depends version now obsolete with this and should be removed?

**Comment by FernetMenta** [comment]
As far as I understood @notspiff the addon inputstream.rtmp still requires it in this phase.

**Pull request merged**
