### PR TITLE
AESinkAudioTrack: Fixup boilerplates

### PR DESCRIPTION
**Pull request by fritsch**
These are the results of the work I was able to do during christmas break. Seeking with RAW works way better. Kodi complexity was highly reduced and sleep workarounds as well.

Someone needs to bring it forward. Best someone with a Shield and other devices.

I want to park that here for reference as everyday job starts again.

### CODE REVIEW

**Comment by supertoto1977** [comment]
Hello @fritsch,
Just did a quick test of your changes on Shield 2019 pro and latest master.
The revert of "[AEsinkAUDIOTRACK] Fix TrueHD IEC frame duration" reintroduces video micro stutters while playing TrueHD with IEC device as expected.
TrueHD with IEC is still buggy, and i worked on a fix (see https://forum.kodi.tv/showthread.php?tid=371292).
However, in RAW mode, the chapter jump, fast forward and fast rewind work better. Kodi recovers the sound now.
Need to be tested on a longer period with different audio formats.
I suggest to keep only the changes regarding the RAW mode and revert the changes which impacts the IEC mode and TrueHD.

**Comment by fritsch** [comment]
Your suggestion is technically wrong. The microstutter is an effect on the Shield, but we are not the Shield video player. 

I reverted the TrueHD change, cause it is not correct. The calculated IEC frames (padded filled up to 192 khz 8 channel 16 bit) to sink ratio work differently. See also AESinkALSA, AESinkWasapi. It "fixed" by accident the microstuttering, cause it drove the delay always to 0.0 ... which is in general wrong - delay 0 means: sink is underrunning constantly and that is the reason the video player did never "adjust". While it causes additional rare "Adjust" issues for the audio.

With the IEC revert you should not see any audio dropouts, but the video microstuttering is back, as then its root-cause comes out again.

As you were working on a proper fix: What's your state of investigation? What's the root-cause?

**Comment by fritsch** [comment]
And: We are in Omega now, so we should fix it properly right? And not rely on workarounds like: bypassing audio / video sync adjust control by flying under videoplayer's delay radar. Whatever causes the micro stutter (vblank interval, race in mediacodec surface, etc.) needs to be found. We will never find it, if we break TrueHD for all other device.

You could retest this with another device, e.g. xioami iirc can do TrueHD PT with IEC as well.

**Comment by fritsch** [comment]
Good - went through the code once more. Paplayer for TrueHD is not yet correct. But I forwarded the ratio division for the 12 units through delay and other parts.

**Comment by fritsch** [comment]
Reducing the delays to such a low value makes basically no sense from another POV: Imagine you have 16 ms buffer ... that would mean that you needed to comeback adding packages every maximum 8ms. This will cause heavy CPU spikes and just force what you exactly want to fix.

Have a look here: https://github.com/xbmc/xbmc/pull/22392/commits/d21127f495a2414c738de3177eb279a207c3a6e6 this tries to fix the Duration (1) and additionally it cares that the Delay that the sink returns matches (2) <- and this was the culprit all the time.

The IEC format is packed "specially", so that it "correlates" to normal frames / channels / samplerate. That means: It was meant like if you add the amount of "ms" that is encapsulated inside the IEC frame, the data written to the sink, even the sink has no single idea that truehd is in there, would naturally report a compatible delay, just cause of the "size of the packing" we wrote onto it. This relation sadly got broken with the 24 to 12 adjustment. So even on other platforms Windows / Linux - we now have after this change a constant A/V delay - the good: it's constant. But according to a 150 ms buffer Windows / Linux should now constantly have a 75 ms A/V delay. Many might not see that, but this is the real thing I want to fix.

I hope it works properly again at least for Android IEC after the change above.

So left:
- Fixing delay for Windows / Linux
- Fixing RAW PaPlayer playback, as the time here is only correct for IEC.

**Comment by fritsch** [comment]
And for every day work: Same here -> off to my 50+ hours job ;-).

**Comment by thexai** [comment]
Tested on Windows and Android and this is very very promising.

IEC: seems now works perfect in Android and TrueHD dropouts _may_ be 100% eradicated.
Also fixed zero HW-Delay issue.
RAW: not perfect yet but is a BIG improvement TrueHD is near perfect, sound returns 100% after pause. DTS-HD MA still has issues after seek.
Also tested in Windows and no regressions found all is 100% perfect

I think it should be merged quickly to get more feedback

**Review by thexai — APPROVED** [review]

**Pull request merged**
