### PR TITLE
Fix unhandled exception with invalid fmt arguments

### PR DESCRIPTION
**Pull request by garbear**
Follow up to #11903

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by Paxxi** [comment]
Don't log here, this introduces a circular dependency between clog and stringutils. Also invalid format should be a bug so letting the exception propagate and crash is a reasonable way to handle it. Possibly not for translations though

**Comment by Paxxi** [comment]
There's little reason to specify a type in the format specifier unless you want an exception thrown or when specifying a certain formatting. Most uses should be fine with `{} ` or for positional `{#}`

**Comment by Montellese** [comment]
Right now it actually doesn't behave any different than it did before with the added benefit that a lot of cases are already handled at compile-time which weren't before. With the old code you get a crash when you try to e.g. format an `std::string` instead of a `const char*`.

Maybe we can let it crash in debug mode and catch the exception in release mode? But I don't really like that either :-/

**Comment by Paxxi** [comment]
Would be so much simpler if we had a higher level method for all translations where we could catch and log the error. Thinking about it, maybe it's time to add one.

**Comment by garbear** [comment]
Comment from @FernetMenta:

> A wrong format is not a runtime error. Having the app crash is much better than hiding the error.

Closing.

**Pull request closed without merging**
