### PR TITLE
[skin][estuary] Add to some views support of PlotOutline

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

Add support of short plot to views with small text space for full plot

## Motivation and Context

Not all estuary views have large space to display a long plot
since listitem has support for a short plot `Listitem.PlotOutline`, you can give the possibility (when available) to use a short plot instead of the full one, to the estuary views with little space:
fanart, shift, widelist, poster

it's not a big improvement, but at least in several cases it's less likely to have truncated text,
or gives the possibility to show more complete text

if PlotOutline not exists fallback to Plot

## How Has This Been Tested?

Examples on screenshots,
missing the screenshots of Shift view because it clearly has a very very small textbox size

## Screenshots (if appropriate):
Purely as an example to show that you reduce the possibility of having truncated text
(before -> after)
before: full plot text (Plot)
after: short plot text (PlotOutline)

fanart:
fanart
fanart_plotoutline

poster:
poster
poster_plotoutline

widelist:
widelist
widelist_plotoutline

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by howie-f** [comment]
@CastagnaIT is this netflix/addon-specific? i‘ve never seen those colored plots on my local tvshows (scrolling turned on by default)

**Comment by garbear** [comment]
I personally prefer the short plot. Reading long text is not exactly pleasant on a TV screen.

**Comment by CastagnaIT** [comment]
@howie-f you can use the plot or plotoutline however you like
with kodi you can change the text style of all your texts by using label formatting
is explained in the wiki

**Comment by HitcherUK** [comment]
+1
Looks good to me and the full fat plot can be read on the info screen anyway.

**Pull request merged**
