### PR TITLE
[pvr] Make Kodi wait for all PVR clients before starting

### PR DESCRIPTION
**Pull request by iacobazzi**
PVRmanager.cpp modified to make Kodi waits for all PVR clients before starting

### CODE REVIEW

**Comment by Jalle19** [comment]
This approach was shot down before, I doubt it will be any better this time.

**Comment by stefansaraev** [comment]
to add: in my opinion, ```m_addons->CreatedClientAmount() < m_addons->EnabledClientAmount() ``` is wrong here. there is no guarantee that an enabled addon will start. it may fail to create an instance for many reasons that are not in your (our) control

**Comment by iacobazzi** [comment]
For Jarvis it is slightly different, it uses
m_addons->ConnectedClientAmount()<
m_addons->EnabledClientAmount()

2016-05-24 15:22 GMT+02:00 Agostino Iacobazzi <agostino.iacobazzi@gmail.com>
:

**Comment by iacobazzi** [comment]
Maybe, Surely it has to be verified.
I'm testing it on Jarvis and everything works.
For now it is the only way I've been able to have three PVR addon working
togheter....

2016-05-24 15:16 GMT+02:00 Stefan Saraev <notifications@github.com>:

**Comment by DaveTBlake** [comment]
No idea what this does, but can you change the PR title to something meaningfull not just "master".

**Comment by FernetMenta** [comment]
won't work with dynamic connection handling. further I see no reason why this should be required. pvr manager gets reset whenever a new client gets connected.

**Comment by iacobazzi** [comment]
Ok, as I said with dynamic connection handling I've never had all the
channels with Jarvis and enabled PVR Mediaportal, SimpleIPTV and Filmon...
9 times out of 10 only channels from Filmon are loaded, no reset at all for
the other addon. Have you tried such a configuration?

Maybe it depends on my HTPC setup, I don't know, I'm happy that now it is
working!
Thanks to all

2016-05-24 16:28 GMT+02:00 Rainer Hochecker <notifications@github.com>:

**Comment by ksooo** [comment]
There is no dynamic PVR connection handling in Jarvis, at least not the dynamic connection handling @FernetMenta is referring to.

**Comment by ksooo** [comment]
Have you tried  a recent Krypton nightly? There are chances that your patch is not required any longer. Have not tried myself, though.

**Comment by iacobazzi** [comment]
I'd love it! actually I tried a night build of Kripton last week, but with
only Filmon and SimpleIPTV not all the channels were loaded, only those
from Filmon.
With the patch Kypton worked well.
I have not tried any recent night build, I'll be really happy with a real
dynamic handling of PVR addon!!!
😀
Surely I'll try extensively Kripton builds, thank you

2016-05-24 19:55 GMT+02:00 Kai Sommerfeld <notifications@github.com>:

**Comment by FernetMenta** [comment]
the suggested patch makes no sense for v17. closing it.

**Pull request closed without merging**
