### PR TITLE
[PVR] Channel groups enhanancements

### PR DESCRIPTION
**Pull request by ksooo**
Here comes a couple of changes/enhancements around channel groups:

1) It is now possible to distinguish which group was delivered by which client. This means, you can now have multiple groups with the same name in Kodi. Something like "Sport" is quite common, right? Before this PR the channels from the different backends where merged into a single local group. No user control about that.
2) Implemented a deterministic sort algorithm for channel groups. First by group type (all, local, client-supplied), then by client priority (as given by the user in PVR settings), then by client-supplied order, then by group name. 
3) It is now possible to fully user-sort the groups using the Channel group manager. There is a new setting to disable usage of channel group order supplied by backends (which is still the default) to give the user some control here.
4) Couple of smaller enhancements like displaying the client's "friendly name" in the channel group selection dialog and in the Channel group manager.
5) Client-supplied group names now can locally be overridden by the user. The user-set value will be kept in local PVR database. PVR add-on API currently does not support to rename a group in the backend.
5) Removed the setting "Sync groups with backend" because to my understanding this setting did nothing useful. What it did was to delete any local groups in case they were not delivered by any client after fetching the groups from the clients. Why should a user ever want to have this behavior, to trash hours of work invested in the Channel group manager to setup local groups? I I don't want to have a local group anymore, I will just delete it myself in the Channel group manager.

 Well, lots of stuff, but I tried to keep it reviewable by splitting stuff up into different commits.
 
 I runtime.tested the changes for quite some time now on macOS and Android, latest master and did not find any regressions so far.

 @phunkyfish if you could find some time to review, that would be great. 
 
 BTW: I have no intention to backport this to Nexus, but could do if people feel that's worth it.

### CODE REVIEW

**Review by phunkyfish — APPROVED** [review]
Really nice changes. Even took it for test run and looks good. My opinion is we leave this in Omega, I don't think we should backport.

**Comment by ksooo** [comment]
> My opinion is we leave this in Omega, I don't think we should backport.

Yes, too heavy code changes. Regression potential is definitely given.

**Comment by xpeiro** [comment]
Hi! First of all thanks for the awesome work. This may not be the best place to ask this, but in kodi Nexus it was possible to make a widget out of a pvr channel group by pointing to "pvr://channels/tv/GROUPNAME/" . This does not work on Omega. Pointing at "pvr://channels/tv/*" to get All Channels still works fine so I was wondering if these changes to channel group handling have anything to do with it? Thanks again in any case.

**Comment by ksooo** [comment]
@xpeiro With Omega, GROUPNAME alone is no longer unique, as multiple pvr clients can supply a group with the same name and those groups are treated as separate groups now. Formerly they were merged into one group. 

Syntax for channel group urls now is "pvr://channels/(tv|radio)/<groupname>@<clientid>"

So, you need to append after the group name an "@" followed by the client id, which you can obtain from kodi.log, for example.

Please note that those urls are kodi-internal, not part of Kodi's API, and can be changed at any time without notice (like it happened for Omega)

**Comment by ksooo** [comment]
Turn on pvr component debugging and you will find the client id very quickly in the log file.

**Comment by xpeiro** [comment]
Thanks, I did enable pvr component debugging, but I'm still not finding it. Am I looking for an integer or a string? Do you mean "pvr.iptvsimple"? That is the only "identifier" I see repeated a lot. I tried appending @pvr.iptvsimple but no dice, in the log I can see the error "channel group segment syntax error." when kodi tries to load the path. Anyway, the "last played" default widget is close enough to what I need, and I guess that's just how it goes when stuff gets improved for most users, there's always a edge case that gets lost/worse. Thanks anyway for your time!

**Pull request merged**
