### PR TITLE
[cmake] refactor module helpers function/macros

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
generalise functions/macros further to more easily accommodate the difference between
a native and a target lib/tool and the relevant source locations

extract download/url steps from externalproject_add to allow override of in-tree source
step.

update comments

## Motivation and context
Some refactoring found whilst looking at future cmake changes. Main goal is to generalise function/macros to allow the ability to use for either target or native libs in tools/depends dirs.

@wsnipex the diff looks a lot bigger than the changes really are. Most of it is removing a variable set and used in get_versionfile_data function. There really was no need, so we just set MODULE before calling, and change all instances of UPPER_MODULE_NAME to MODULE.
The other change being the removal of hardcoding DEPENDS_PATH in functions, and allow find modules to set the type (native or target) which then applies either DEPENDS_PATH or NATIVEPREFIX as appropriate for search/install paths using the interim DEP_LOCATION variable.

## How has this been tested?
Build osx

## What is the effect on users?
N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by wsnipex — APPROVED** [review]

**Comment by howie-f** [comment]
not sure why this happens. i can confirm it's building fine on debian 11
```
build/libdvd/lib

-rw-r--r-- 1 fhw fhw  79874 Jun 21 16:59 libdvdcss.a
-rwxr-xr-x 1 fhw fhw    924 Jun 21 16:59 libdvdcss.la
-rw-r--r-- 1 fhw fhw 270618 Jun 21 17:00 libdvdnav.a
-rwxr-xr-x 1 fhw fhw   1127 Jun 21 17:00 libdvdnav.la
-rw-r--r-- 1 fhw fhw 299350 Jun 21 17:00 libdvdread.a
-rwxr-xr-x 1 fhw fhw    932 Jun 21 17:00 libdvdread.la
```
@Portisch which distro are you building on?

**Comment by mackal** [comment]
> not sure why this happens. i can confirm it's building fine on debian 11
> 
> ```
> build/libdvd/lib
> 
> -rw-r--r-- 1 fhw fhw  79874 Jun 21 16:59 libdvdcss.a
> -rwxr-xr-x 1 fhw fhw    924 Jun 21 16:59 libdvdcss.la
> -rw-r--r-- 1 fhw fhw 270618 Jun 21 17:00 libdvdnav.a
> -rwxr-xr-x 1 fhw fhw   1127 Jun 21 17:00 libdvdnav.la
> -rw-r--r-- 1 fhw fhw 299350 Jun 21 17:00 libdvdread.a
> -rwxr-xr-x 1 fhw fhw    932 Jun 21 17:00 libdvdread.la
> ```
> 
> @Portisch which distro are you building on?

This happens with the gentoo live ebuild. Why it works on other distros is that LIB_TYPE gets set somewhere else, but the gentoo live ebuild builds with system libs so a valid LIB_TYPE never leaks over into the FindLibDvd cmake stuff.

**Comment by Portisch** [comment]
CoreELEC:
https://github.com/CoreELEC/CoreELEC/blob/97f8019ea7a70fbb74ba24bc1600971de62cc3c0/projects/Amlogic-ce/packages/mediacenter/kodi/package.mk#L259

**Comment by Portisch** [comment]
I will get a log tomorrow. It looks like `LIB_TYPE` is set with Flatbuffers cmake file but afterwards it's emtpy?

**Comment by howie-f** [comment]
can replicate with

> Moving LibDvd to be the first thing in the required_deps

**Comment by mackal** [comment]
> LIB_TYPE is set here: https://github.com/xbmc/xbmc/blob/master/cmake/scripts/common/ModuleHelpers.cmake#L99 If it isn't for you, we need more info on how to reproduce

that is never called by FindLibDvd.cmake (or any other place if you're building with mostly system libs)

**Comment by wsnipex** [comment]
> > LIB_TYPE is set here: https://github.com/xbmc/xbmc/blob/master/cmake/scripts/common/ModuleHelpers.cmake#L99 If it isn't for you, we need more info on how to reproduce
> 
> that is never called by FindLibDvd.cmake (or any other place if you're building with mostly system libs)

ofc it's called, but too late

**Comment by vpeter4** [comment]
> please try [wsnipex@c47c435](https://github.com/wsnipex/xbmc/commit/c47c435bdb75551d20ee953244dd0eebfdd966f8)

it is working at least for CoreELEC

**Comment by howie-f** [comment]
here too

**Pull request merged**
