### PR TITLE
[addons] add support for pre-gzipped addons.xml in repositories

### PR DESCRIPTION
**Pull request by tamland**
As discussed in forums and irc/slack this allows us to gzip addons.xml on mirrors.

With the current addons.xml it saves us ~70% bandwidth compared uncompressed.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
awesome \o/
If you have an updated repo script i can put it on the server so we can get this live tested :)

**Comment by MartijnKaijser** [comment]
Tested on windows and android. No problems so far. 
@MilhouseVH can you include in builds as well?

**Comment by MilhouseVH** [comment]
OK

**Comment by MartijnKaijser** [comment]
jenkins build this please. Would be great to have others give this a quick review before we merge.

**Comment by MartijnKaijser** [comment]
@tamland could you also bump addon version to 2.4.0 ?

**Comment by tamland** [comment]
@MartijnKaijser no need to bump after all?

**Comment by akva2** [comment]
wtf happened here. the addons.xml has been gzipped on the transport level since the beginning.

**Comment by MartijnKaijser** [comment]
@akva2 not a single mirror has gzip enabled so even though it's requested to get it zipped the server will just provide a plain xml

**Comment by akva2** [comment]
K. Tgat

-------- Opprinnelig melding --------
Fra: Martijn Kaijser <notifications@github.com>
Dato: 09.12.2015 08:21 (GMT+01:00)
Til: xbmc/xbmc <xbmc@noreply.github.com>
Ko: Arne Morten Kvarving <Arne.Morten.Kvarving@sintef.no>
Emne: Re: [xbmc] [addons] add support for pre-gzipped addons.xml in repositories (#8464)


@akva2<https://github.com/akva2> not a single mirror has gzip enabled so even though it's requested to get it zipped the server will just provide a plain xml

**Comment by MartijnKaijser** [comment]
@notspiff http://paste.ubuntu.com/13851713/ this is what was tested directly on the mirror we have. Last on is one test repo on github that does provide gzip

**Comment by akva2** [comment]
indeed. things must have changed in the last 6 years.. :)

**Comment by MartijnKaijser** [comment]
@tamland seems multi source in one repo is not working
http://forum.kodi.tv/showthread.php?tid=251420

**Pull request merged**
