### PR TITLE
Silence a lot of warnings

### PR DESCRIPTION
**Pull request by Paxxi**
Not much to add, silenced a lot of conversion warnings and some others mainly in VS but should probably silence other compilers as well. Tested on Win32 and Ubuntu 14.04

### CODE REVIEW

**Comment by FernetMenta** [comment]
IMO most of those should be fixed properly. There is a reason for the warnings and we should not just ignore it by using a cast.

**Comment by Paxxi** [comment]
I've tried to be mindful about why the warnings are there, changing a few variables where it makes sense and don't risk anything breaking. I may have made the PR a bit too big, making it hard to judge which casts makes sense or not.

I also think that minimizing warnings that have been there for ages and don't seem to cause errors makes it easier to spot warnings for new code.

**Comment by FernetMenta** [comment]
The fact that those warnings are there for ages does not justify to ignore those in the future.

**Comment by Paxxi** [comment]
Fair point, I'll close this and go back to the drawing board

**Pull request closed without merging**
