### PR TITLE
[depends] Update flatbuffers to 23.3.3 and raise min OSX version to 10.14

### PR DESCRIPTION
**Pull request by neo1973**
## Description
Because the currently used flatbuffers 2.0.0 doesn't build with GCC>=13 due to missing includes, update it to version 23.3.3.

The new flatbuffers requires C++17 which is poorly supported by OSX 10.13, e.g. `std::optional` and `std::variant` aren't really usable. Therefore raise the minimum supported OSX version on x86_64 to 10.14 to make flatbuffers build.
 
## Motivation and context
See above.

## How has this been tested?
Build with GCC 13.1 on Arch.

## What is the effect on users?
None

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by neo1973** [comment]
Does anyone know why the OSX build is marked as failed? It created a DMG and the unit tests are successful.

**Comment by fuzzard** [comment]
Warning thresholds. Its got new warnings about new deprecations in 10.14

**Comment by AlwinEsch** [comment]
As note, there also another request here https://github.com/xbmc/xbmc/pull/22515 with update about flatbuffers, think the old can be then closed as this here with newer version and more detailed.

**Comment by kambala-decapitator** [comment]
Yeah, 10.13 has some limitations in its libc++ regarding 17 support. Bumping is fine if there seems no other solution.

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
@neo1973 cherry-pick the following and that should fix the warning count

https://github.com/fuzzard/xbmc/commit/550bc231c27f7605e485482df870e5eb8bd2f332
https://github.com/fuzzard/xbmc/commit/5334e6bf11628e7c337634dbbf584210100bf1c5

**Comment by neo1973** [comment]
Thanks a bunch for the fixes @fuzzard :slightly_smiling_face:

**Pull request merged**
