### PR TITLE
cleanup internal rar vfs in favour of vfs.rar

### PR DESCRIPTION
**Pull request by stefansaraev**
as title says.

https://github.com/notspiff/vfs.rar needs to be added to kodi-binary-repo

## How Has This Been Tested?

briefly runtime tested on linux, srt subtitles inside a rar file stored in same folder as a movie work fine with vfs.rar installed. 

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

@notspiff fyi there will be rarfolderXXXXX leftovers in .kodi/temp. is there something special we need to do to cleanup or vfs.rar "should" take care ?

### CODE REVIEW

**Comment by stefansaraev** [comment]
last commit makes subtitles work again. and I did not squash yet for a reason - it may break something else, tbh I am not sure what I am doing here.

**Comment by notspiff** [comment]
while it should delete all temporary files on shutdown of th add-on, it will indeed leave the folders. i guess i should add some rmdir's as well.

**Comment by notspiff** [comment]
it used to: call directly to the rar manager to obtain the archive contents, and handle recursion into archives-in-archives manually.
now: you do a recursive listing through the vfs instead. it will unroll archives as part of its recursion.

**Comment by stefansaraev** [comment]
nope. recursive listing does not unroll content of embedded archives.

ScanArchiveForAssociatedItems is used only to find external subtitles / audio in rar archives. and the file name found is supposed to match the movie file name. I see no point supporting multiple levels of embedded archives here. so I'll handle the rars just like zips for now.

**Comment by stefansaraev** [comment]
squashed. I think this is all I can do for now. if removal of embedded rar archives support is not wanted, someone else has to reimplement it ;)

please review

**Comment by Paxxi** [comment]
jenkins build this with addons please 
Provided vfs.rar builds on all platforms it's probably time to get this in

**Comment by stefansaraev** [comment]
pushed to my repo-binary-addons/vfs.rar. could you please re-trigger jenkins ?

**Comment by Rechi** [comment]
retriggering jenkins to check if vfs.rar builds now on all platforms after a fix was added

jenkins build this with addons please

**Comment by stefansaraev** [comment]
ok. added static cast. I hope that will fix it.

**Comment by Paxxi** [comment]
jenkins build this with addons please

**Comment by stefansaraev** [comment]
rebased onto master. temp commit that pointed repo-binary-addons to my branch removed. 
we need to find out whether last commit is acceptable if jenkins is happy.

**Comment by Rechi** [comment]
jenkins build this with addons please

**Comment by Paxxi** [comment]
As I won't have any time energy to fix the Windows build anytime soon I'm not hitting the button but looks ok to merge to me.

**Comment by Paxxi** [comment]
jenkins build this with addons please

**Comment by stefansaraev** [comment]
@bkuhls would be nice if you stop referenceing kodi PRs in your commit mesages :)

**Comment by lukastribus** [comment]
FYI the move from internal RAR support to an addon also fixed the following crash, so thanks for this:
https://trac.kodi.tv/ticket/16675

**Pull request merged**
