### PR TITLE
Fix regression of Kodi making 6x HTTP requests when playing internet streams

### PR DESCRIPTION
**Pull request by matthuisman**
## Description
Fixes regression (introduced in 19.1 and 20) of Kodi making 6x HTTP requests after starting playback of any internet stream without video information

Will backport fix for 19.2

## Motivation and context
https://github.com/xbmc/xbmc/pull/19510 adds a call to IsBluray() in OnPlaybackStarted
IsBluray() calls GetOpticalMediaPath()
which then tries to get the 6x Bluray file identifiers (VIDEO_TS.IFO, etc etc)
https://github.com/xbmc/xbmc/blob/master/xbmc/FileItem.cpp#L1865

Issue is, its calling this for internet streams causing 6x http requests
Here is a log: [kodi.log.txt](https://github.com/xbmc/xbmc/files/6521653/kodi.log.txt)

## How has this been tested?
Windows

test.strm with below url in it:
http://cdn.theoplayer.com/video/elephants-dream/playlist-single-audio.m3u8
then open via kodi file manager.
(any internet stream without video info stored will cause the bug)

Note before this fix, 6x extra http requests to the bluray paths.
With this PR, no extra requests.
(cleared userdata between tests to ensure no video info caching)

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Review by arnova — APPROVED** [review]
LGTM

**Comment by matthuisman** [comment]
backport done: https://github.com/xbmc/xbmc/pull/19777

**Comment by matthuisman** [comment]
@arnova 
just quickly - do we actually want SetUpdateStreamDetails() to be set for Internet streams?
looking at the code, it seems maybe just DVD / Blu-rays are wanted?
Maybe we want to actually NOT SetUpdateStreamDetails() if Internetstream?

**Comment by arnova** [comment]
> @arnova
> just quickly - do we actually want SetUpdateStreamDetails() to be set for Internet streams?
> looking at the code, it seems maybe just DVD / Blu-rays are wanted?
> Maybe we want to actually NOT SetUpdateStreamDetails() if Internetstream?

Yes we want this. This is actually why this code was conceived in the first place: allow addons to fetch stream details for internet streams.

One comment on this PR: It could really use a proper comment why the isinternetstream()-check is required.

**Comment by matthuisman** [comment]
@arnova
just seen your edit...

What is wrong?
I had asked - do we want file stream details set for internet streams.
If not - then  this logic is wrong...
We would want to just skip the check if internet streams.

**Comment by arnova** [comment]
> @arnova
> just seen your edit...
> 
> What is wrong?
> I had asked - do we want file stream details set for internet streams?
> 
> If not - then yes this logic is wrong...
> We would want to just skip the check for internet streams.

Ah yes, now I get it. I misread it earlier. This may not be a bad idea, although this is a sensitive area and may cause regressions.

@DaveTBlake : Any thoughts about this?

**Comment by matthuisman** [comment]
Being so sensitive, it's odd the change got in without testing with an internet stream in the 1st place. 

Whatever happens, internet stream needs to be checked before Blu-Ray. The blue ray check is very expensive. 

Either it's used to skip the if statement altogether or used to resolve it before Blu-Ray check.

**Comment by DaveTBlake** [comment]
The problem/sensitivity as I understand it is that IsInternetStream() merely looks to see if the thing playing is accessed via the internet, not that is truely a "stream". As far as the player is concerned everything is just a data stream anyway, but the rest of Kodi needs to know and be able to differentiate between continuous data streams, and access to a finite file with header information etc. 

Hence adding or removing IsInternetStream() to a conditional test, or changing IsInternetStream() itself could have (and historically has had) all kinds of regressions and unforeseen consequences.

>Being so sensitive, it's odd the change got in without testing with an internet stream in the 1st place. But I guess kind of easy to miss. It only affects Internet streams without any info (eg. Via a strm file).

@matthuisman the variety of things that Kodi can play (media formats, finite files, continous streams, local or remote, strm files and other playlist formats, with and without header info etc.) plus the variety of routes to initiate playback (GUI, JSON, Python and complex/combined calls), makes for a testing nightmare.

I am going to be super-cautious about hitting merge on a backport of this. I would be absolutely delighted for someone to make the case and prove a valid way forwards.

**Comment by matthuisman** [comment]
Could we revert the original commit that introduced the issue then ?https://github.com/xbmc/xbmc/pull/19510/files

Or, revert to original behavior just for internet streams which would be not trying to set the info?
That would involve changing this PR so if it's internet stream and that property isn't set, then it wouldn't set

**Comment by the-black-eagle** [comment]
I don't think you can just drop in `IsInternetStream()` like that as it negates the whole point of having the property (i.e. having addons be able to retrieve stream details whilst ignoring other streams, such as your`.strm` example).  The change in this PR will attempt to save stream details for any stream, whether we want them or not.  Your other proposed change would exclude disc images served via http or ftp etc.

I haven't had chance to re-visit this properly yet but just off the top of my head it might be better to check for a valid dbid before proceeding with the disc checks.  That way, we know the content is in the db.  If it's not (and an addon has not set the property) then we probably don't need to save any details. Alternatively, maybe `IsBluray()` could be replaced with `StringUtils::StartsWithNoCase(file.GetPath(),"bluray")` and something similar for files ending with `.ifo` or `.vob`

I fully understand why you want to change it, but I don't think it's quite so straightforward as it might first appear.

**Comment by matthuisman** [comment]
I'm confused. If you want them to be included, then what's wrong with this PR? It simply checks for them before the expensive Blu-Ray check? They are still included...

**Comment by the-black-eagle** [comment]
No, you can leave it open.  The point I was trying to make is that we generally _don't_ want stream details for actual internet streams as they are not normally in the db _but_ an addon can supply Kodi with a file and by setting the `get_stream_details_from_player` property on that file, then Kodi _will_ save those details.  I don't think there are actually any addons that do this at the moment, it was added a while ago as a future feature.

Having looked at your log, I do agree that we shouldn't be making those calls if we can avoid it.  Maybe not many people do use strm files but we should handle the use of them more gracefully than hitting up remote servers with 403's.  I'm therefore quite happy to see it changed, but it has to be in a way that doesn't change the current functionality.

**Comment by the-black-eagle** [comment]
This should work correctly, or at least, it does in all my tests.  It avoids any unnecessary calls to remote servers but works for bluray and dvd for both local and streamed content.

```
if (file.GetProperty("get_stream_details_from_player").asBoolean()
      || ((!file.HasVideoInfoTag() || !file.GetVideoInfoTag()->HasStreamDetails())
      && (StringUtils::StartsWithNoCase(file.GetPath(),"bluray://")
      || StringUtils::EndsWithNoCase(file.GetDynPath(),".ifo")
      || StringUtils::EndsWithNoCase(file.GetDynPath(),".vob")
      || StringUtils::EndsWithNoCase(file.GetDynPath(),".iso"))))
    m_appPlayer.SetUpdateStreamDetails();
```

**Comment by matthuisman** [comment]
If that's a way of detecting Blu-Ray, then maybe the is Blu-Ray could use
that instead? It would stop this issue happening again. I think quite a few
may be unaware that is Blu-Ray would cause http calls if done on an
internet stream

**Comment by the-black-eagle** [comment]
Nah, it'll only work for scanned in library content.  Besides, those calls happen because when the first check in `IsBluray()` fails (protocol is not 'bluray') it calls `GetOpticalMediaPath()` which appends 'index.bdmv' to the current file path and then checks for the existence of the appended file.  It is those checks for existence that causes the http requests to the remote server and there are four of them because if the first fails, we try again but append a directory as well as the filename. If that fails, we repeat the process but with 'INDEX.BDM'.  Same for dvd but that only uses 2 calls. So the root cause is actually the `CFile::Exists()` calls here. https://github.com/xbmc/xbmc/blob/master/xbmc/FileItem.cpp#L1865-L1894

Happily, all bluray stuff in the library starts with `bluray://` whether it's an iso or a bdmv file structure so it's a useable check for this particular use case.  As the background loader can't get the stream details for bluray and dvd, we need to catch those types here and get the stream details from the videoplayer.

**Comment by arnova** [comment]
Assuming that items should already be in the db is wrong! There are many ppl out ther, like myself, that play all their stuff in file mode....

**Comment by the-black-eagle** [comment]
@arnova Actually, it doesn't matter whether you have scanned stuff in or not (or whether you use the library or file mode).  Those tests will still save the stream details against the relevant files regardless. Admittedly, there might be a further navigation step in file mode to see the details (actual file name rather than just movie (directory) name) but that is because of using file mode, not a limitation of the re-implementation of these tests.

I'm not assuming anything here, just going by how stuff already works - everything Kodi plays is added to the db, regardless of whether or not it needs to be or should be.  So, as soon as you play a dvd or bluray, it is added to the db and the stream details can be saved for it.  That happens whether it is already in the library (via scanning/scraping) or not (just using a source and playing a file).

**Comment by arnova** [comment]
Those tests will still save the stream details against the relevant files regardless. Admittedly, there might be a further navigation step in file mode to see the details (actual file name rather than just movie (directory) name) but that is because of using file mode, not a limitation of the re-implementation of these tests.
> 

I'm not sure which scenario you're referring to then (?) And I also don't understand why the limited/self-implemented dvd/br checks here suffice..... And finally, if they do suffice: it should end up in URIUtils (as a new function or as part of the existing functions there)...

**Comment by the-black-eagle** [comment]
There are only three things we need to check.  Either it's bluray, a dvd file or a disc image. So all that's needed is
```
if (file.GetProperty("get_stream_details_from_player").asBoolean()
      || ((!file.HasVideoInfoTag() || !file.GetVideoInfoTag()->HasStreamDetails())
      && (URIUtils::IsBluray(file.GetPath())
      || file.IsDVDFile()
      || file.IsDiscImage())))
    m_appPlayer.SetUpdateStreamDetails(); 
```
Much tidier.

**Comment by matthuisman** [comment]
@the-black-eagle
Do you want me to update the PR to that?
Or can I close this and you will PR the fix?
Backport for 19.X as well pretty please :)

**Comment by arnova** [comment]
> @the-black-eagle
> Do you want me to update the PR to that?
> Or can I close this and you will PR the fix?
> Backport for 19.X as well pretty please :)
> 
> as the original author, I'm sure you know best :)

Perhaps combining both your solutions is not such bad thing after all but with one minor modification: passing true to IsInternetStream() like "IsInternetStream(true)". This would allow flags to be fetched for addons that haven't implemented the "get_stream_details_from_player"-flags. There *could* be regressions introduced by this, not sure though so perhaps we should just test it for a while in master.

**Comment by the-black-eagle** [comment]
@arnova I would guess that most addons have not implemented "get_stream_details_from_player" so if `IsInternetStream()` is added we will be saving details for pretty much every stream played.  That's probably not so much of an issue these days so if you want it added in, that's fine by me.
@matthuisman I already have a PR ready to go, once we're all agreed on the addition (or not) of `IsInternetStream()`.  I agree that this is a candidate for a backport but need to get approval from @DaveTBlake first.  I'd also suggest that if we _do_ add `IsInternetStream()` that we don't backport that bit as that will change behaviour whereas the checks will fix an issue.

**Comment by matthuisman** [comment]
Perfect. I'll close both my prs.
Thank you for working out a proper fix 😊

**Pull request closed without merging**
