### PR TITLE
[Docs] ListItem InfoLabels Documentation Incomplete/Malformed

### PR DESCRIPTION
**Pull request by DeltaMikeCharlie**
## Description
The current online documentation for ‘ListItem’ InfoLabels ends at ‘ListItem.AddonLifecycleDesc’, however, more labels are documented in the source file.  There is also some malformed documentation in the ‘listitem_labels’ section of ‘GUIInfoManager.cpp’

A single empty line appears to interrupt the documentation creation process.  Removing this empty line produces documentation up to ‘ListItem.HasVideoExtras’ (the last item documented in the source file) and removes the malformed documentation from ‘GUIInfoManager.cpp’.

## Motivation and context
Provide accurate documentation.

## How has this been tested?

- Build the documentation locally and observe the issues.
- Remove the blank line,
- Rebuild the documentation locally and observe the results. 

## What is the effect on users?
None.  For developers only.

## Screenshots (if appropriate):
**Before**
dUdVhTA
**After**
oc6W1xU

## Types of change
- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [X] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by ksooo — APPROVED** [review]
Good catch. Thanks.

**Review by neo1973 — APPROVED** [review]

**Comment by MikeSiLVO** [comment]
I think this PR caused a couple of unwanted changes (issues?).

Header blue bar now goes down the side until it reaches the change:

firefox_WTwnGW3ZEl

Then at the change I see html(?) code instead of formatted description: 

firefox_1iDbpIPrSY

**Comment by ksooo** [comment]
The problem is only caused indirectly by this PR. some parts of the documentation are now rendered for the first time, and there are syntax errors, namely:

https://github.com/xbmc/xbmc/blob/master/xbmc/GUIInfoManager.cpp#L6491

Can you see it? ;-) There is one ` that needs to be removed.

///     @skinning_v19 **[New Infolabel]** \link ListItem_AddonLifecycleDesc `ListItem.AddonLifecycleDesc``\endlink

**Comment by ksooo** [comment]
@DeltaMikeCharlie are you interested in opening a PR to fix the problem @MikeSiLVO reported here? See my (untested) proposal for a fix.

**Comment by DeltaMikeCharlie** [comment]
> @DeltaMikeCharlie are you interested in opening a PR to fix the problem @MikeSiLVO reported here? See my (untested) proposal for a fix.

OK.

**Comment by DeltaMikeCharlie** [comment]
Actually, there are some unescaped commas.
https://github.com/xbmc/xbmc/blob/5b97125fe1e90342fd2f163a3c04aafefdb034e4/xbmc/GUIInfoManager.cpp#L6913

On both Chromium and Firefox on my Ubuntu development system, the first issue at the top of the list item has been fixed.
Using Firefox on my host Win10 machine, I can see the second error with the malformed ListItem.AddonLifecycleDesc table and the HTML code, but I could never see this manifest under Ubuntu.  I copied the updated html to Windows and both issue were resolved.

**Comment by DeltaMikeCharlie** [comment]
Here is another.
image

**Pull request merged**
