### PR TITLE
[pvr] fix add-ons new being disabled

### PR DESCRIPTION
**Pull request by opdenkamp**
this attempts to fix the annoying new add-ons being disabled thing in pvr.

it removes the clients table from pvr, and uses the standard add-ons table for IDs now instead, and only disables new add-ons when they don't have a user set configuration.

add-ons won't be disabled when they have the following in addon.xml in the pvr extension point (this only applies to pvr add-ons): `needs_configuration=false`

it also stops the add-ons from being disabled when the database is reset.

ping @Jalle19 you had another PR for this some time ago, can you test this please

### CODE REVIEW

**Comment by Jalle19** [comment]
You're missing the database version bump and the respective code for dropping the table when upgrading.

**Comment by opdenkamp** [comment]
That was on purpose really, because we just abondoned the table and won't re-use it.

**Comment by opdenkamp** [comment]
jenkins build this please

**Comment by opdenkamp** [comment]
now that i think of it, we do need to upgrade and change the add-on IDs used by previous versions, because the one used in the addondatabase won't be the same as the pvr one

**Comment by opdenkamp** [comment]
cleaned it up a bit and fixed the issue that made you have to enable the pvr manager twice when starting up for the first time or after a db reset

jenkins build this please

**Comment by tamland** [comment]
This upgrade didn't go too well for me. It gets stuck in a infinite loop when executing the query.

And it broke the addon browser. This db is used for repos. You can't just add random addons to it.

**Comment by opdenkamp** [comment]
I've tested clean installs without pvr, upgraded installs and new installs, and it worked in all situations for me. Can you link me your log. Must have missed something.

As for the db, it's for registered add-ons and these are not random, and I should have done this before merging in PVR instead of trying to fix it up now. But that's a bit late now ;-) I'll take a look at the browser.

**Comment by opdenkamp** [comment]
I can see a problem in the download section of the add-ons browser, where it's suddenly listing dupes, but I don't see yet how this could have happened. The add-ons that I added have the repo id in the db set to 0 (first real one starts at 1), so the pvr ones shouldn't be interfering with something from another repos.

**Comment by opdenkamp** [comment]
Just checked the db contents, and it's listing them correctly there too
```
sqlite> SELECT a.name, a.version, a.addonID FROM addon a, addonlinkrepo b WHERE b.idRepo = 0 AND a.id = b.idAddon;
Tvheadend HTSP Client|2.0.5|pvr.hts
```

**Comment by tamland** [comment]
No idea about the dupes, but 'get addon' just fetch all addons from the db so they'll be listed there, which they shouldn't.

As for the db I already deleted it (that was probably dumb) so sorry I can't be of any help. I guess we'll soon find out if it's me or you screwing up:) I don't really use pvr but just have pvr.demo for testing. I checked gdb and hangs at line 168 and the last log line was "Cleaning triggers.." if that is of *any* help.

**Comment by opdenkamp** [comment]
I'm checking what's going on exactly, but I probably won't have time to fix it before late this evening. The `addonlinkrepo` table looked correct here, and `repository.xbmc.org` didn't match to any pvr add-on (with repo id 0 instead of 1), but I was still seeing dupe entries listed in the window.

**Comment by opdenkamp** [comment]
Right, checked on another host, and it looks like it's just showing dupes for the add-ons that have a newer version around. Which may not be related to this PR.

**Comment by opdenkamp** [comment]
And... it wasn't me :) The dupe add-ons show up if you upgrade from Helix to https://github.com/xbmc/xbmc/commits/7764bc91f998fd8b1de06b8698c208fd8745732d (commit before this PR went in).

So that just leaves that loop that you saw. Which could perhaps be a stale tree or ccache if it was built locally. I'm not seeing it and I've just tested an upgrade from Helix to that commit I linked above, from a clean ~/.kodi dir. Can you try reproducing it?

**Comment by opdenkamp** [comment]
the dupe add-ons are actually caused by your commit: b72f00a75c63ebe5b846d28824bcbe3ba1daebc6

`DELETE FROM repo` will add each add-on to the db a second time

**Comment by tamland** [comment]
What I was talking about was Get add-on->All add-ons. Specific repos works ofc. because it looks at the repo ID, but 'All' does not and now lists local PVR add-ons, which it should not. Basically everything that uses `GetAddonVersion`, `GetAddon`, `GetAddons` and `Search` is broken because it assumes the addons those returns exist in a repo.

Why does PVR clients have to be added to the `addons` table anyway? All the into stored there you already have locally right? If it's only to store a flag for whether or it it has been configured (I'm not sure I understood this part correctly) wouldn't it be better to just create a new table for that?

**Comment by opdenkamp** [comment]
Why shouldn't local add-ons be listed? That's not broken afaict?

We need an id for the add-on, which we first got from a table 'clients' in the pvr db. This id also determined whether or not the add-on should be disabled. This id is used in pvr for things like matching a channel to the correct add-on.

So instead of having half the add-on related administration in addonmanager and the other half in pvrmanager, it's all done in addonmanager now in which it belongs.

**Comment by MartijnKaijser** [comment]
"Get add-ons" should never list add-ons that are not part of a repo. You have enabled/disabled for that

**Comment by opdenkamp** [comment]
Right, `All add-ons` is the key here, missed that part. It's when you have more than one repository installed only. Probably just have to adapt the queries to include a check for repoid > 0, then everything will be happy again. Will check in the evening. I find this less disturbing than all add-on being listed twice when you upgrade ;-)

**Comment by opdenkamp** [comment]
found a bit of time ;-)
fixed in the second commit of https://github.com/xbmc/xbmc/pull/6652

**Comment by MilhouseVH** [comment]
Several reports of the db update hanging when upgrading to TV28.

http://forum.kodi.tv/showthread.php?tid=211501&pid=1951254#pid1951254

**Comment by doveman** [comment]
I'm getting stuck on the bootscreen. 

Debug Kodi.log: http://pastebin.com/acTrp5xj

My TV26, TV27 and TV28.db files are all 36KB and TV28.db-journal is 17KB.

TV27.db: https://drive.google.com/file/d/0B1fDI89phEEScmdsbWl4b0ZObzg/view?usp=sharing

**Comment by opdenkamp** [comment]
Will check in the evening

**Comment by tamland** [comment]
'Search' also lists local PVR addons now btw. The existing queries in CAddonDatabase should really have be changed to check that the addon is in a repo before this. I'm still puzzled by why addons that are not in a repository was moved to the table *specifically for storing addons that are in a repository*. It would seem a lot easier to me to just add a new table for this..

**Pull request merged**
