### PR TITLE
[cmake] Fixes rpi ARCH

### PR DESCRIPTION
**Pull request by nsenica**
## Description
If the ARCH is set to arm-linux-gnueabihf kodi will be looking for libX-arm-linux-gnueabihf.so's but they don't exist, since the architecture libs are compiled with is arm.

## Motivation and Context
See above

## How Has This Been Tested?
Built kodi.
This probably will require a bit more testing just to be sure that it doesn't break anything.

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by popcornmix** [comment]
I've been building with ``-DWITH_ARCH=arm`` to fix loading of binary addons.
Assuming this is an equivalent fix, then +1 from me.

**Comment by nsenica** [comment]
@popcornmix That's exactly what this fixes :)

**Comment by wsnipex** [comment]
jenkins build this with addons please

**Comment by wsnipex** [comment]
@MilhouseVH could you include this in your builds please?

**Comment by lrusak** [comment]
@wsnipex It won't matter. This change is only for compiling on an arm host it seems. we set `-DWITH_ARCH=arm` because the arm cpu will never be detected when building on x86_64.

see, https://github.com/LibreELEC/LibreELEC.tv/blob/master/packages/mediacenter/kodi/package.mk#L188

**Comment by wsnipex** [comment]
this will trigger whenever you build for rbpi (CORE_SYSTEM_NAME=rbpi) and CPU=arm1176jzf-s or cortext-a7 or cortex-a53

**Pull request merged**
