### PR TITLE
[gif] - support for animated splash screens

### PR DESCRIPTION
**Pull request by Memphiz**
Based on #5180 this adds support for animated splash screens.

I don't really think i have done the refactor of splash.cpp right - i just am not into gui stuff :(. But in case we somehow want to support animated splash screens for helix (because their were some animated ones in the logo suggestion thread in the forum) - i think this could be a base to work on it.

Also the rendering of the splash is done in our normal application render loop - this means XBMC is loading up in the background while the animation is playing.

### CODE REVIEW

**Comment by zag2me** [comment]
@Memphiz is there a reason this has not been merged yet? There is a sticky on the forums for splash animations and some nice ones ready to go. http://forum.kodi.tv/showthread.php?tid=209673&page=22

**Comment by Memphiz** [comment]
The reason is that it was not decided how this should be handlded. Either make the animation blocking (delaying startup) or async (kodi startsup in the background while splash animation is running - which could lead to missing toast dialogs in the background).

**Comment by zag2me** [comment]
My view is it should block and delay startup. Purely from a UI point of view thats how I imagine it to work.

**Comment by afedchin** [comment]
My point of view is it shouldn't delay startup. If my hw allows to start quickly why should I wait until splash is finished? as an example splash on startup win7 doesn't delay startup.

**Comment by MartijnKaijser** [comment]
indeed no wait on splash

**Comment by ace20022** [comment]
@Memphiz I've reopened the pr: https://github.com/Memphiz/xbmc/pull/13 This should be reviewd and merged into this pr before it can be included imo.

**Comment by Memphiz** [comment]
But the PR you opened is against a different branch. I need to dive into this branch mess again i think. Not sure when i get some time.

**Comment by Memphiz** [comment]
To add to this - "no wait on splash" is something which is not covered yet at all. ATM its that the splash is played to the end and in the background Kodi loads up. What you want is that the splash is aborted. The question is which criteria is used for an abort in that case.

**Comment by Memphiz** [comment]
ok - rebased and integrated the changes from @ace20022 - needs heavy squashing at the end. Please if someone could download http://sourceforge.net/projects/giflib/files/giflib-5.1.0.tar.bz2/download and upload it to the build-deps/sources on our mirrors  it would be great. (can do sunday evening earliest...)

**Comment by topfs2** [comment]
I agree with zag that it makes sense to play splash until its done and kodi
loaded. Aborting the splash before could be added later.
Den 27 feb 2015 15:36 skrev "Memphiz" <notifications@github.com>:

**Comment by da-anda** [comment]
is there a chance to get the animated gif support in, independet from the splash stuff? Or just get this PR in during next merge window? Couldn't believe that animated gifs are not working atm.

**Comment by Memphiz** [comment]
they should working iirc some rbpi builds use gif spinners no?

**Comment by Memphiz** [comment]
Also this whole animated gif stuff is out of my league tbh. I never grasped how this is ment to be integrated into the gui rendering.

**Comment by da-anda** [comment]
right - it could work as part of skin textures, but not in picture library - that's what I was referring to.

**Comment by ace20022** [comment]
> but not in picture library

that requires some more work

> it could work as part of skin textures

but buggy :p

maybe I find some time (and motivation) within the next weeks.

**Comment by da-anda** [comment]
@ace20022 that would be great. Just one more question, would it make sense (or work at all) to implement the picture decoders etc in a similar way to audio encoders/decoders? So more like a interface and then have various add-ons as handlers for certain file types? That way we could have add-ons that use platform specific libs and as fallback our own implementation or alike. I'm not requesting any of this, just more of a general question if it could work and might be worth working towards.

**Comment by popcornmix** [comment]
Animated gifs work in skins already. E.g. https://github.com/popcornmix/xbmc/commit/b854abab6d8f970442fa57b4d4d46f4d09d5e5d1

**Comment by ace20022** [comment]
@popcornmix that only works correctly because that gif contains 11 full images/frames.
@Memphiz I want to resume the work on gifs, but without splash support (as a start). Which of your prs is the most up to date? I guess https://github.com/xbmc/xbmc/pull/5180.

**Comment by Memphiz** [comment]
well #5181 is more upto date - #5180 is without splash support yeah (but also rather old) - but the splash support is only the change in application.cpp iirc - so imo #5181 should be a better start point.

**Pull request closed without merging**
