### PR TITLE
addons: avoid db access when finding addons

### PR DESCRIPTION
**Pull request by FernetMenta**
fixes huge delay when loading pvr guide window and maybe some other issues not came to surface after https://github.com/xbmc/xbmc/pull/9051

### CODE REVIEW

**Comment by FernetMenta** [comment]
@ksooo /cc

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by fritsch** [comment]
Nice! Thanks very much.

**Comment by tamland** [comment]
Absolutely not acceptable as it completely breaks #9051 and goes again the entire design behind the addon system. You should try to fix the underlying pvr issues.

**Comment by fritsch** [comment]
@tamland caching the database addons and only updating them when either removal or installing them is the way to go ...

**Comment by tamland** [comment]
@fritsch Yes, precisely, but that's not possible atm. Mainly because of issues in pvr and binary addons.

**Comment by FernetMenta** [comment]
@tamland the please go ahead it fix the things you did break. if you don't I'll inject this

**Comment by FernetMenta** [comment]
We had a method to query addons of a specific type. We need this method again!

**Comment by Montellese** [comment]
@FernetMenta: no offense but you can't go around rejecting all kinds of PRs that don't exactly meet your vision of VideoPlayer but then go and inject workaround code that doesn't match someone else's design vision and ignore their objections.

**Comment by tamland** [comment]
So 2 minutes in and we're already at making threats? I don't even know what the issue is or seen any reports of issues from it. <- Why not start helping me with that??

**Comment by FernetMenta** [comment]
@tamland approximately one week ago I asked to if you could provide a method to query addons of a specific type but you did not respond. We need such a method. 

@Montellese if I reject something I give reasons and provide guidance for a solution. This I was missing here.

**Comment by tamland** [comment]
Is that what you mean by query a specific type? Filetypes? The summary of this pr mentions pvr guide. I thought that previous discussion was an entirely different discussion; about how decoder addons queries file extension information.

What I tried to explain there is that a better approach, regardless of whether or not GetAddons have caching, is to move this responsibility out of CAddonMgr and CAddon (since it's very specific for some addon types) to some different 'manager' which then subscribes to changes from CAddonMgr and updates as needed.

That way you don't have to rely on GetAddons being extremely efficient, _nor_ do  you have to constantly recreate decoder instances just query it for some information. 

I also mentioned the broader goal in same discussion. Namely to get rid of the remaining mutation and coupling issues some addon types have such that the addon manage *can* do it's own caching properly; avoiding db access completely.

**Comment by FernetMenta** [comment]
I think you don't understand the issue. This has nothing to do with pvr, encoders, or decoders but with binary addons in general. Depending on the typ of the addon it can extend almost any function. a vfs addon can extend the filesystem and every time this part is accessed we have to check if a specific addon is enabled and has certain properties.

Note that this was used to work until you changed it. Maybe we should just split binary addons from the old python system. @AlwinEsch what do you think?

**Comment by tamland** [comment]
Then what is the issue, and _where_ is it? 

What I'm talking about, and what you are changing here, is the generic addon system used by the entire application that has nothing to do with python or binary addons specifics.

**Comment by FernetMenta** [comment]
> Then what is the issue

The issue is that the system had a method for binary addons to be queried. By adding a db access you made this method not usable anymore.

> and where is it?

it is everywhere binary addons can be used because they extend the system. you are very aware of https://github.com/xbmc/xbmc/pull/9250 and this is not the only location.

**Pull request closed without merging**
