### PR TITLE
Controller dialog: Hide features not supported by game add-on

### PR DESCRIPTION
**Pull request by garbear**
A game add-on specifies which libretro buttons it supports using its buttonmap.xml. For example, 2048 is [here](https://github.com/kodi-game/game.libretro.2048/blob/master/game.libretro.2048/resources/buttonmap.xml). Because only a subset of buttons is defined, we can hide the unused buttons in the GUI.

The benefit is a simpler dialog and less ambiguity as to which buttons are used. The downside is the dialog is more confusing, because while no buttons are mysteriously omitted, others are awkwardly omitted. You can see this in the screenshots below, where 2048 is greatly simplified, but Mr.Boom awkwardly leaves out the X button.

I think the benefits outweigh the downsides, but it's debatable.

Another problem currently is that 2048 and Mr.Boom aren't "platforms" and have no controller, so they use the mapping for the default 360 controller. This is confusing, because the user has no way of knowing which actions each button has in the game. MAME faces a similar problem, because button maps can be specific per-game.

## Motivation and Context
Another plane bug bites the dust.

## How Has This Been Tested?
Tested on OSX with 2048 and Mr.Boom.

## Screenshots (if appropriate):
Mapping a controller while playing 2048:

screen shot 2018-10-01 at 12 35 47 pm

Mapping a controller while playing Mr.Boom:

screen shot 2018-10-01 at 12 36 56 pm

### CODE REVIEW

**Comment by garbear** [comment]
jenkins build this please

**Comment by garbear** [comment]
There was a rebase error so I included three refactors from my retroplayer-18beta3 branch. These have been in the test builds for quite a while, so not too risky I hope.

**Comment by garbear** [comment]
GBM error unrelated

**Comment by Rechi** [comment]
> GBM error unrelated

Which error, there is none.

**Comment by garbear** [comment]
https://jenkins.kodi.tv/job/BuildMulti-PR/9913/ it was automatically rebuilt

**Pull request merged**
