### PR TITLE
[videodb] support unique IDs for musicvideos

### PR DESCRIPTION
**Pull request by Montellese**
## Description
This commit brings music videos in line with movies, tvshows and episodes in the video database to also support multiple unique IDs. 

## Motivation and Context
Kodi core / library doesn't really make use of it right now but it might also be helpful for third party applications which can access and modify the unique IDs through JSON-RPC.

## How Has This Been Tested?
Manually as part of my media import work.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Review by garbear — APPROVED** [review]
Makes sense that music videos should get the same treatment as videos and music.

**Comment by Montellese** [comment]
Not sure what went wrong with the iOS-ARM64 build. The build log says `** BUILD SUCCEEDED **` but the build status is failed.

**Comment by phunkyfish** [comment]
> Not sure what went wrong with the iOS-ARM64 build. The build log says `** BUILD SUCCEEDED **` but the build status is failed.

Same thing happened to @ksooo. You can ignore as unrelated.

**Comment by DaveTBlake** [comment]
Just thinking about JSON changes generally: because of the serial nature of schema version once a change has been made to the API for master and not backported, then it becomes impossible to do any JSON API related fixes to Matrix. Any change has this effect, even a patch bump. We certainly hit that with v18, when a breaking change was merged early into master and so blocked a number of fixes that it would have been better to have.

@Montellese do you have any thoughts on that? I wondered if we simply hold back merging JSON changes to master until at least v19.1 is out. Or would it be viable to backport non-breaking changes, although that could get messy if is support for new features that Matrix does not have.  Maybe we just live with it as we always have, but if there is a way to avoid blocking ourselves that would be good.

**Comment by Montellese** [comment]
Well by our definition of backporting there shouldn't be any new JSON-RPC features being added to Matrix. In theory only the path / bugfix version should change for Matrix point releases.

IIRC in the past we discussed whether we should just bump the JSON-RPC API major version with a release. Then you can still bump minor and patch versions. But it sends the wrong signal to clients because they have to assume that there have been backwards incompatible changes even though nothing changed. Maybe this can be done using the minor version instead? So bump the minor version directly after the release so that you can still increment the patch / bugfix version for point releases?

**Comment by Montellese** [comment]
@DaveTBlake should I wait with merging this due to the JSON-RPC versioning issue?

**Comment by DaveTBlake** [comment]
> @DaveTBlake should I wait with merging this due to the JSON-RPC versioning issue?

Yes @Montellese  if you can delay until after 19.1 that would be helpful I think, or at least give us maximum flexibility with JSON fixes. But if it holding up other work then obviously we can reconsider.

**Comment by Montellese** [comment]
I'm not in a hurry with this. I just went through all the stuff I developped as part of media import and extracted everything into PRs which applies to Kodi core independent of media import.

**Comment by phunkyfish** [comment]
@DaveTBlake now that 19.2 is out is it ok for json APIs to diverge?

**Comment by DaveTBlake** [comment]
> Now that 19.2 is out is it ok for json APIs to diverge?

Yes I would say that the dust has settled enough Matrix. There are a number of API PRs waiting, I would suggest that we merge in creation order, with the necessary sequence of rebases

**Pull request merged**
