### PR TITLE
[guilib] Add Infolabels for versions

### PR DESCRIPTION
**Pull request by CrystalP**
## Description

Cherry-picks the commit of #24603 and completes it according to discussion in PR
* Add VideoPlayer.HasVideoVersions (same logic as ListItem.HasVideoVersions)
* Add VideoPlayer.VideoVersionName (same logic as ListItem.VideoVersionName)
* Modify both VideoVersionName labels to return a string only for versions and blank for extras

Doxy of the labels added/modified.

## Motivation and context

c/p of #24603 - Provides infolabel to skins to display the version name for a playing movie, for example on seekbar or fullscreeninfo

## How has this been tested?

Not a skinner so unfortunately not well tested. It builds.

## What is the effect on users?

Enables skins to display version name on OSD for example.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by ksooo — APPROVED** [review]
LGTM

**Comment by CrystalP** [comment]
Jenkins build this please

likely unrelated android docker failure after 30s

**Comment by scott967** [comment]
Thanks for merging.  Got to go Hawaii --> Florida today.  I haven't had a chance to skin it but hope this suffices for 21.  Closed https://github.com/xbmc/xbmc/pull/24603

**Comment by Hitcher** [comment]
`VideoPlayer.HasVideoVersions` doesn't seem to be working.

Add this code after this [line](https://github.com/xbmc/xbmc/blob/511d828268122060b01023c99912859eecfb17a0/addons/skin.estuary/xml/Variables.xml#L405) to test.

```
		<value condition="VideoPlayer.HasVideoVersion">VideoPlayer.HasVideoVersion = True</value>
		<value condition="!VideoPlayer.HasVideoVersion">VideoPlayer.HasVideoVersion = False</value>
```

**Comment by jjd-uk** [comment]
@Hitcher @CrystalP I can confirm that `VideoPlayer.HasVideoVersion` is not working.

Slightly different code  placement to @Hitcher

Changed https://github.com/xbmc/xbmc/blob/master/addons/skin.estuary/xml/Variables.xml#L414-L422 to

```
	<variable name="OSDSubLabelVar">
		<value condition="VideoPlayer.HasVideoVersion">VideoPlayer.HasVideoVersion = True</value>
		<value condition="!VideoPlayer.HasVideoVersion">VideoPlayer.HasVideoVersion = False</value>
		<value condition="Window.IsActive(visualisation) + Integer.IsGreater(Playlist.Length(music),1) + Integer.IsGreater(Playlist.Position(music),0)">$LOCALIZE[554] $INFO[Playlist.Position] / $INFO[Playlist.Length]</value>
		<value condition="VideoPlayer.Content(musicvideos)">$VAR[NowPlayingSublabelVar,,[CR]]$INFO[player.chapter,[COLOR button_focus]$LOCALIZE[21396]: [/COLOR]]$INFO[Player.ChapterCount,/]$INFO[Player.ChapterName, - ]</value>
		<value condition="VideoPlayer.Content(episodes) + !player.chaptercount">$INFO[VideoPlayer.Season,[COLOR button_focus][CAPITALIZE]$LOCALIZE[36906][/CAPITALIZE]:[/COLOR] S]$INFO[VideoPlayer.Episode,E,: ]$INFO[VideoPlayer.Title]</value>
		<value condition="VideoPlayer.Content(episodes) + player.chaptercount">$INFO[VideoPlayer.Season,[COLOR button_focus][CAPITALIZE]$LOCALIZE[36906][/CAPITALIZE]:[/COLOR] S]$INFO[VideoPlayer.Episode,E, - ]$INFO[VideoPlayer.Title,,[CR]]$INFO[player.chapter,[COLOR button_focus]$LOCALIZE[21396]:[/COLOR] ]$INFO[Player.ChapterCount,/]$INFO[Player.ChapterName, - ]</value>
		<value condition="VideoPlayer.Content(LiveTV) | PVR.IsPlayingRecording | PVR.IsPlayingEpgTag">$INFO[VideoPlayer.Season,[COLOR button_focus][CAPITALIZE]$LOCALIZE[36906][/CAPITALIZE]:[/COLOR] S]$INFO[VideoPlayer.Episode,E, - ]$INFO[VideoPlayer.EpisodeName]</value>
		<value condition="player.chaptercount + [!VideoPlayer.Content(episodes) + !VideoPlayer.Content(LiveTV)]">$INFO[player.chapter,[COLOR button_focus]$LOCALIZE[21396]:[/COLOR] ]$INFO[Player.ChapterCount,/]$INFO[Player.ChapterName, - ]</value>
		<value>$INFO[VideoPlayer.Genre]</value>
	</variable>
```

On 

image


this gives me 

image

**Comment by Hitcher** [comment]
Doh, yeah it's working just fine now. Sorry for the noise.

**Comment by Hitcher** [comment]
Is found out why I got it wrong - it was labeled this way in the skin changes thread.
Will change it to the correct spelling.

**Comment by jjd-uk** [comment]
Btw @Hitcher does VideoPlayer.VideoVersionName always return something for you? so in the case of only one movie version it returns **Standard Edition** even if there are no other versions. I thought it been agreed to not return anything on that case.

**Comment by Hitcher** [comment]
> Btw @Hitcher does VideoPlayer.VideoVersionName always return something for you? so in the case of only one movie version it returns **Standard Edition** even if there are no other versions. I thought it been agreed to not return anything on that case.

Yes it does. I had to use `VideoPlayer.HasVideoVersions` to display `VideoPlayer.VideoVersionName` so I don't see **Standard Edition** in the label.

**Pull request merged**
