### PR TITLE
[depends] Bump libbluray to 1.3.4

### PR DESCRIPTION
**Pull request by enen92**
## Description
This bumps libbluray to v.1.3.4. This version essentially brings fixes to freebsd, nothing fancy, patches still apply cleanly.

Windows bump: https://github.com/xbmc/kodi-deps/pull/22

Windows libs that need to be uploaded to the mirrors attached (from the artifacts of the PR above: [libbluray-1.3.4-windows.zip](https://github.com/xbmc/xbmc/files/12122869/libbluray-1.3.4-windows.zip)

@wsnipex @fuzzard if not asking for too much could you upload the sources and win libs to the mirrors :)
Will runtime test once I can quickly generate testbuilds through jenkins.

### CODE REVIEW

**Comment by fuzzard** [comment]
windows libs from https://github.com/xbmc/kodi-deps/actions/runs/5620531531 have been uploaded.

tar.bz source tarball from https://download.videolan.org/pub/videolan/libbluray/1.3.4/ has been uploaded. Note that this has a different hash to the artifact on gitlab (and therefore the hash you have in this PR). The mirrors matches the sha512 file supplied on the videolan mirror https://download.videolan.org/pub/videolan/libbluray/1.3.4/libbluray-1.3.4.tar.bz2.sha512

For reference, generally we aim for tarball from any official mirror/site over a gitlab/github artifact when available.

**Comment by enen92** [comment]
thanks @fuzzard!
jenkins build this please

**Comment by enen92** [comment]
Tested windows, Linux and android (iso) without noticing any regressions. Merging on Friday if no one opposes.

**Comment by enen92** [comment]
> Tested windows, Linux and android (iso) without noticing any regressions. Merging on Friday if no one opposes.

Friday I'm in love 🎵

**Comment by MediaBrasil** [comment]
@enem92

I think you forget to update the 2 bd-java files to version 1.3.4, continue 1.3.2 (previous version). In all previous libbluray bump versions, the bd-java version was updated too.

**Comment by MediaBrasil** [comment]
@CrystalP

Here changelog

2022-11-25: Version 1.3.4
- Improve API documentation.
- Improve JVM probing.
- Improve support for FreeBSD and Solaris.
- Improve .jar file search.
- Add configure option to build without external libudfread.

2022-09-19: Version 1.3.3
- Initial support for Java 18.
- Add support for the OpenBSD operating system.
- Improve support for FreeBSD, NetBSD, and DragonFlyBSD
- Improve Java 17 support.

2022-06-28: Version 1.3.2
- Fix build/run failure after Oracle Java CPU for April 2022

**Comment by enen92** [comment]
@MediaBrasil thanks for noticing. The code included in the bundle is correct, only the naming is wrong. Fixed it in https://github.com/xbmc/kodi-deps/pull/26 but will require a new upload to the mirrors :(

**Pull request merged**
