### PR TITLE
[PVR] Fixes for broken timer handling

### LINKED ISSUE #15682: PVR Timers - Deactivate context menu available in Cancelled and Aborted states
### Describe the bug
Here is a clear and concise description of what the problem is:

If a timer is cancelled or aborted it's still possible to deactivate it.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

If the state is cancelled or aborted it should not be possible to Deactivate the timer. (Assumes cancelled and aborted mean the same thing).

## Actual Behavior

If timer is in state cancelled or aborted deactivate is selectable in context menu.

## Possible Fix

Grey out the deactivate button in the context menu if the state is cancelled or aborted.

### To Reproduce

1. Load timers with a cancelled or aborted state from a PVR backend
2. Load PVR Timer UI
3. See that deactivate is selectable in the context menu.

### Debuglog

The debuglog can be found here:

https://gist.github.com/phunkyfish/fe15e102bcc7b7c4dc49942abdb8e0a3

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSX, Windows, LibreElec 9 Intel/Rpi
 - Kodi version: 18.2RC

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by phunkyfish**
## Description

- Don't display Activate/Deactivate in timer context menu if timer state is PVR_TIMER_STATE_ERROR
- Don't display enabled toggle in timer settings dialog if timer state is PVR_TIMER_STATE_ERROR
- Don't include timer in active or recording lists if timer state is PVR_TIMER_STATE_ERROR

## Motivation and Context

Deactivating doesn't make sense when a timer is in this state.

Fixes #15682

## How Has This Been Tested?

Built kodi, on OSX with just pvr.vuplus to test.

## Types of change

- [ x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ksooo** [comment]
You should change title and description of this PR to match the content. We exegesis the scope more to "Fixes for broken timer handling."

**Comment by phunkyfish** [comment]
Done ;)

**Review by ksooo — APPROVED** [review]
Code changes look good to me. Cannot runtime-test myself, thus I do assume you did.

**Comment by phunkyfish** [comment]
Yes, I have tested this.

Timer in an error state when it would be recording now.
Timer in an error state when it should be recording next
Timer in an error state that should be completed if not an error
Timer in an error state which is not now or next

**Comment by ksooo** [comment]
Very nice. Thanks for your first contribution to the Kodi PVR component. :-)

**Comment by phunkyfish** [comment]
Thanks, it’s was fun and thanks for the guidance.

**Pull request merged**
