### PR TITLE
[depends] Bump libdcadec to version 0.2.0

### PR DESCRIPTION
**Pull request by Rechi**
FFmpeg 3.0 requires libdcadec >= 0.1.0

### CODE REVIEW

**Comment by fritsch** [comment]
We did not bump ffmpeg as of now - there are some thousand deprecated warnings :-) is it backwards compatible? (let's see what jenkins does)

jenkins build this please

**Comment by afedchin** [comment]
just out of curiosity, what's wrong with ffmpeg3.0? I'm using it in my mvc build without issues. I've dropped libdcadec and compiling ffmpeg with internal dca decoder.

**Comment by fritsch** [comment]
@afedchin nothing. The some thousand warnings. We need to look at every one of it and see if it's critical or not. Besides that nothing is wrong with it.

**Comment by Rechi** [comment]
Jenkins failed because the new version isn't uploaded to the mirrors yet.

**Comment by MartijnKaijser** [comment]
uploaded

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by Rechi** [comment]
added a fix for linux-rpi, but maybe there is something better to fix the issue.

**Comment by jjd-uk** [comment]
Isn't libdcadec dropped for ffmpeg 3.0? as I thought they were now using an internal dca decoder for all dts formats.

**Comment by stefansaraev** [comment]
it is dropped in ffmpeg master. still used in 3.0 branch

**Comment by jjd-uk** [comment]
According to the changelog the internal decoder is introduced in 3.0 see L81 https://github.com/FFmpeg/FFmpeg/blob/e259dc86a80398d56d1aabcf6203f80616a4d04d/Changelog

So wouldn't it be better to use this straightaway since libdcadec is being dropped.

**Comment by stefansaraev** [comment]
thats right indeed. nice. ping @popcornmix

**Comment by jjd-uk** [comment]
If I understood right this is the commit that introduces the internal ffmpeg decoder https://github.com/FFmpeg/FFmpeg/commit/ae5b2c52501d5009fe712334428138a9b758849b

**Comment by popcornmix** [comment]
I suspect removing the use of "ssat" on arm will hurt performance.

It appears that ffmpeg has this implemented (at least in n3.0.1) and uses the ssat asm.
I suspect it works for ffmpeg by using the ``av_always_inline`` keyword which allows the compiler to work out that ``bits`` is always a contant.

Is there any need to bump this lib, if it gets removed when we next bump ffmpeg?

**Comment by Rechi** [comment]
Obsolete by #9491

**Pull request closed without merging**
