### PR TITLE
Json fixes

### PR DESCRIPTION
**Pull request by hudokkow**
## Description
Fix json error.

## Motivation and Context
Error in code.

## How Has This Been Tested?
Build/runtime tested

## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document

Fixes:
> 15:46:16.561 T:140144809965888   ERROR: JSONRPC: Unable to parse JSON Schema definition for ""
15:46:16.561 T:140144809965888   ERROR: JSONRPC: Invalid JSON Schema definition for method ""

https://github.com/xbmc/xbmc/commit/555c9df8bf74b926b23c32c4cde64b4fe5336171 is cosmetics only

@ksooo fyi

### CODE REVIEW

**Comment by Montellese** [comment]
Looks good. The order of the methods isn't really relevante though.

**Review by Montellese — APPROVED** [review]

**Comment by hudokkow** [comment]
jenkins build and merge

**Comment by hudokkow** [comment]
jenkins build this please

**Comment by hudokkow** [comment]
ffs, jenkins build this please

**Comment by ksooo** [comment]
@hudokkow good catch! thanks.

**Pull request merged**
