### PR TITLE
Update README.raspberrypi

### PR DESCRIPTION
**Pull request by rinaldus**
Since XBMC was renamed to Kodi, I don't see a reason to have local directories named "xbmc".

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@popcornmix ping

**Comment by popcornmix** [comment]
It's hard to feel too strongly on this.
I think I'd prefer the git clone command was left as is. The upstream repo is still called xbmc so calling the directory seems more natural to me.
Changing /opt/xbmc-bcm to /opt/kodi-bcm I have no objection to.

**Comment by MartijnKaijser** [comment]
@rinaldus can you update according to the comments?

**Comment by rinaldus** [comment]
@MartijnKaijser , what I need to update? My suggestion was not accepted.

**Comment by rinaldus** [comment]
@MartijnKaijser , updated.

**Comment by popcornmix** [comment]
Change is fine by me.
Should be squashed before merging.

**Comment by rinaldus** [comment]
@popcornmix , what is it? Should I to do anything else?

**Comment by popcornmix** [comment]
``git rebase -i HEAD~2``
in the editor replace p (for pick) with f (for fixup) on second commit.
You should now have a single commit.
``git push -f``
and the PR will update with a single, squashed commit.

**Comment by rinaldus** [comment]
@popcornmix , thanks! I squashed my 2 commits.

**Comment by ericdomi65** [comment]
Hello,
I'm new and little bit newer in development. 
I tried to follow steps to install kodi source on rasbian Jessie, after having made an update and upgrade.

OK! when i try to launch make -C tools/~~~~~~/xbmc i get no such file or directory
Likely because ending /xbmc does'nt exist 
So today i'm going to wait for help until i won't bear anymore to launch the command on the previous directory(depends/target itself) 
Can you help me or what do you think of that?

**Comment by Rechi** [comment]
this should be `make -C tools/depends/target/cmakebuildsys`
Can make a PR which correts that?
It's also wrong in README.android.

**Comment by ericdomi65** [comment]
This time it's working; I had to cd to ./build to do the other make, then
the sudo make install did it well
But what to do now with kodi.bin : I mean I'd like to type kodi to launch it

Thank you anyway for your help
Eric

Eric Abadie
"Soyez plus philosophe que moi et on verra si je vous estime..."

2017-03-06 19:18 GMT+01:00 Rechi <notifications@github.com>:

**Comment by ericdomi65** [comment]
Hi,
Have you received my answer?
Please tell me how to make the corrections if it is what you mean by PR

Eric Abadie
"Soyez plus philosophe que moi et on verra si je vous estime..."

2017-03-06 19:18 GMT+01:00 Rechi <notifications@github.com>:

**Pull request merged**
