### PR TITLE
Allow named groups on m_videoCleanDateTimeRegExp

### PR DESCRIPTION
**Pull request by clashlab**
Some of my video files are name with the year before the movie title (ie: "1999 - Matrix"). I didn't find a way to only change cleandatetime in advancedsettings.xml to allow this naming (the first group is hardcoded to be the title, the second the year). So here's a patch to use named groups allowing to place year and title in any order.

I defined 2 groups: "year" and "title". To name a group, simply put "?P&lt;group_name&gt;" juste after the opening parenthesis.
As advancedsettings.xml is an XML file, the '<' and '>' characters will have to be escaped "&amp;lt;" and "&amp;gt;" respectively, so a named group will start with "?P&amp;lt;group_name&amp;gt;"

I also change the default value for m_videoCleanDateTimeRegExp to support the actual naming and the one I introduced.

Also, using the named groups "title" and "year" isn't mandatory, the actual regex will still work as expected.

### CODE REVIEW

**Comment by mkortstiege** [comment]
Dang.. totally forgot about this, Sorry. @MartijnKaijser, IMO it's too late for Isengard.

**Comment by mkortstiege** [comment]
@clashlab, could you please rebase?

**Comment by clashlab** [comment]
Not until early September

**Comment by clashlab** [comment]
Rebased using PR #8125

**Comment by clashlab** [comment]
I did the rebase, sorry for the delay and the mess with the branches

**Comment by MartijnKaijser** [comment]
ping @mkortstiege or some one else for review/merge ?

**Comment by tamland** [comment]
If still wanted it will need unit tests of CUtil::CleanString

**Comment by MartijnKaijser** [comment]
I will close this PR. If there's interest please open a new one with required changes.

**Pull request closed without merging**
