### PR TITLE
[addons][peripheral] cleanup API, improve "C" interface, documentation rework for Doxygen

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description

Make this addon like the others usable within "C" and make his docs usable on addon doxygen view.

The docs can be maybe a bit improved, has taken parts from forum and added als a bit with my poor english.

Reworked docs are visible here http://alwinesch.github.io/group__cpp__kodi__addon__peripheral.html.

## User related:

Not user relevant

Only for all binary addon system requests may be for the user:
- Binary addon system revised to ensure higher security in its data exchange between addon and Kodi
- Revised binary addon system documentation for outside developers

Commit 1:
-------------------------
**[addons][peripheral] clang clean up on addon headers**

This done to have in correct clang style on next changes, otherwise there is a clutter in text style.

Commit 2:
-------------------------
**{addons][peripheral] don't use C++ class pointer within "C" structure**

This makes it hard to use the header for "C" only (e.g. base for other languages).

Commit 3:
-------------------------
**[addons][peripheral] make all "C" interface structures to own memory**

This done to prevent API backward problems if something becomes replaced e.g. on props or to kodi calls.

Commit 4:
-------------------------
**[addons][peripheral] spearate "C" parts to own file**

This place the "C" parts about peripheral to a new file on "kodi/c-api/addon-instance/peripheral.h".
This done to allow also "C" language only (as base for other languages) and to confirm safe "C" ABI between addon and Kodi.

Commit 5:
-------------------------
**[addons][peripheral] move PeripheralUtils.h to own "peripheral" folder**

This done to hold the "addon-instance" dir more clean and to have about every instance type only one file there. If more are needed use them an extra folder.

So can more easy seen which instance types are possible.

Commit 6:
-------------------------
**[addons][peripheral] use C++ classes for addon function values**

This changes the addon functions that they used direct the C ++ classes for their values.
It is intended to keep "C" away from "C++" addons as much as possible and to have the interface more secure.

Because these classes were already available, it was easy to convert and the respective work on the addon is no longer necessary.

Commit 7:
-------------------------
**[addons][peripheral] update and add new peripheral documentation**

This cleanup them to have usable with doxygen for binary addons.
Further are some doc parts taken from forum to have description about addon system.
Also are some new parts added as e.g. PeripheralUtils.h not have before docs.

Commit 8:
-------------------------
**[addons][peripheral] increase API to 2.0.0**

## How Has This Been Tested?

Tested with peripheral.joystick and request https://github.com/xbmc/peripheral.joystick/pull/186

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by garbear — APPROVED** [review]
Changes are entirely confined to xbmc/addons and xbmc/peripherals. The changes in xbmc/peripherals are small and entirely mechanical, so it's clear that very little outside of joysticks will be affected by this PR. Within xbmc/addons, it's easy to see that this PR only uses the patterns from the other API cleanups, so everything I can see is correct.

**Comment by garbear** [comment]
Good job on the documentation part. I like how you included my cool and entirely confusing graph at http://alwinesch.github.io/group__cpp__kodi__addon__peripheral___docs___lifetime.html!

**Comment by AlwinEsch** [comment]
Yeah :smile, also looking to use them as "dot" format (https://renenyffenegger.ch/notes/tools/Graphviz/examples/index) inside doxygen (there supported), hope it works and then easier for changes.

**Comment by AlwinEsch** [comment]
@garbear Is updated, instead of images use it now the "dot" format.
They looks not so good like your images but it allow a edit :smiley:, how looks now still available here http://alwinesch.github.io/group__cpp__kodi__addon__peripheral___docs___lifetime.html

**Comment by garbear** [comment]
you created the dot files, that's amazing! they look great. now, I can correct the class names. I'll send a follow-up PR for the class names to not block this PR.

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by AlwinEsch** [comment]
Addon updates comes around 10:00 - 11:00 o'clock UTC, after the ubuntu launchpad has created this Kodi version.

**Pull request merged**
