### PR TITLE
Update flatbuffers to v23.1.4

### PR DESCRIPTION
**Pull request by cscd98**
## Description
This updates the flatbuffers version referenced in tools/depends from v2.0.0 to v23.1.4. The substantial version change is due to them switching to yearly release versions :(

## Motivation and context
The version of flatbuffers included in mirrors.kodi.tv is 2.0.0. This is breaking, Kodi now uses three params for VerifyField(const Verifier &verifier, voffset_t field, size_t alignfunction. v2.0.0 has two parameters (const Verifier &verifier, voffset_t field) and therefore causes compilation to cease working.

In v2.0.0:
https://github.com/google/flatbuffers/blob/v2.0.0/include/flatbuffers/flatbuffers.h#L2643

Whereas the 3 param version is now used as seen in:
https://github.com/google/flatbuffers/blob/bc901436dbe574bda153d1b2693e048c9b23a502/include/flatbuffers/table.h#L115
https://github.com/google/flatbuffers/blob/b190ce11b0013e90330b0ba29dee24f4bef08645/include/flatbuffers/verifier.h#L104

An issue was created for this but was closed, but it is still a problem:
https://github.com/xbmc/xbmc/issues/22367

I myself cannot cross compile from x86_64 to aarch64 because it is trying to use VerifyField

## How has this been tested?
Compilation now succeeds where before it did not. I am unable to test kodi yet, as I am trying to fix other compile/linking issues on aarch64.

Before this can be tested https://github.com/google/flatbuffers/archive/refs/tags/v23.1.4.tar.gz must be uploaded to http://mirrors.kodi.tv/build-deps/sources/ and renamed to flatbuffers-23.1.4.tar.gz

I do not have access to do this myself, I tested this change by using github downloads for now,

This affects Nexus as well as master.

## What is the effect on users?
The ability to cross compile to other architectures or use -DENABLE_INTERNAL_FLATBUFFERS=ON option

## Types of change
- [x] **Bug fix** (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
I'm not sure what this is fixing? Our internal depends uses 2.0.0 of flatbuffers.

https://github.com/xbmc/xbmc/blob/fb8949922a0f478fecf65a89e1f2d39e603e652b/tools/depends/target/flatbuffers/FLATBUFFERS-VERSION#L2

This is regularly tested with our CI.

**Comment by craigcarnell** [comment]
> I'm not sure what this is fixing? Our internal depends uses 2.0.0 of flatbuffers.
> 
> https://github.com/xbmc/xbmc/blob/fb8949922a0f478fecf65a89e1f2d39e603e652b/tools/depends/target/flatbuffers/FLATBUFFERS-VERSION#L2
> 
> This is regularly tested with our CI.

If you download http://mirrors.kodi.tv/build-deps/sources/flatbuffers-2.0.0.tar.gz and extract it, then open include/flatbuffers/flatbuffers.h you will see the header function with only TWO params:

```
 bool VerifyField(const Verifier &verifier, voffset_t field) const {
```

This is incompatible with the usage below which has THREE params which causes a compilation fail:
build/cores/RetroPlayer/messages/savestate_generated.h:102:32: error: no matching function for call to ‘KODI::RETRO::Savestate::VerifyField<uint8_t>(flatbuffers::Verifier&, KODI::RETRO::Savestate::FlatBuffersVTableOffset, int) const

I can't say for your CI... I haven't done this kind of thing in a while so I'm a bit rusty... anyone else can confirm? :)

**Comment by garbear** [comment]
I was able to build this PR with the following temporary change:

```
diff --git a/tools/depends/native/flatbuffers/Makefile b/tools/depends/native/flatbuffers/Makefile
index 18008728dd..6e017c5f38 100644
--- a/tools/depends/native/flatbuffers/Makefile
+++ b/tools/depends/native/flatbuffers/Makefile
@@ -11,6 +11,10 @@ ARCHIVE=$(SOURCE).tar.gz
 SHA512=8b3e1b9596a76548faca529fe5070e775be50bfdea079ba4f66014f5a1bfb93f8edd7e56f97363c897d2db8391277a9099a61d14e4298c3669ab7068bbf07865
 include ../../download-files.include
 
+SOURCE=v$(VERSION)
+ARCHIVE=$(SOURCE).tar.gz
+BASE_URL=https://github.com/google/flatbuffers/archive/refs/tags
+
 APP=$(PLATFORM)/build-cmake/flatc
 
 # BUILD Notes
diff --git a/tools/depends/target/flatbuffers/Makefile b/tools/depends/target/flatbuffers/Makefile
index cd65e66c7f..d542263767 100644
--- a/tools/depends/target/flatbuffers/Makefile
+++ b/tools/depends/target/flatbuffers/Makefile
@@ -21,6 +21,10 @@ else
        BUILD_FLATC=OFF
 endif
 
+SOURCE=v$(VERSION)
+ARCHIVE=$(SOURCE).tar.gz
+BASE_URL=https://github.com/google/flatbuffers/archive/refs/tags
+
 CMAKE_OPTIONS := -DCMAKE_BUILD_TYPE=Release \
                  -DFLATBUFFERS_CODE_COVERAGE=OFF \
                  -DFLATBUFFERS_BUILD_TESTS=OFF \
```

The version bump is welcome regardless of whether it fixes a problem. If it indeed does fix a problem then we should backport.

But I wonder why the headers are getting crossed between versions.

**Comment by lrusak** [comment]
You are looking at generated code that depends on the version of the flatc compiler being used.

I would recommend starting with a clean build folder.

I would also post a cmake log that shows the configuration output.

Expected:
```
-- Found FlatC: /home/lukas/Documents/git/xbmc/build/build/bin/flatc (found version "2.0.0") 

-- Found FlatBuffers: /home/lukas/Documents/git/xbmc/build/build/include (found version "2.0.0")
```

This is when using the option `-DENABLE_INTERNAL_FLATBUFFERS=ON`

**Comment by craigcarnell** [comment]
> You are looking at generated code that depends on the version of the flatc compiler being used.
> 
> I would recommend starting with a clean build folder.
> 
> I would also post a cmake log that shows the configuration output.
> 
> Expected:
> 
> ```
> -- Found FlatC: /home/lukas/Documents/git/xbmc/build/build/bin/flatc (found version "2.0.0") 
> 
> -- Found FlatBuffers: /home/lukas/Documents/git/xbmc/build/build/include (found version "2.0.0")
> ```
> 
> This is when using the option `-DENABLE_INTERNAL_FLATBUFFERS=ON`

That probably explains it.

```
Found FlatC: /usr/bin/flatc (found version "2.0.6")
Found FlatBuffers: /home/xbmc/opt/xbmc-deps/aarch64-linux-gnu-debug/include (found version "23.1.4")
```

Before FlatBuffers said 2.0.0 naturally. I am using Ubuntu 22.10, perhaps that is why I have /usr/bin/flatc v2.0.6

**Comment by lrusak** [comment]
> The version bump is welcome regardless of whether it fixes a problem. If it indeed does fix a problem then we should backport.
> 

Yep I agree, no functional changes are needed but it would probably be good to runtime test.


> 
> But I wonder why the headers are getting crossed between versions.

This looks like an issue of the user having mixed flatbuffers versions or possibly the generation not regenerating after switching branches.

**Comment by garbear** [comment]
Yes, native and target flatbuffers are getting mixed.

The cmake output should read:

```
Found FlatC: /home/xbmc/opt/xbmc-deps/x86_64-linux-gnu-native/bin/flatc (found version "23.1.4")
Found FlatBuffers: /home/xbmc/opt/xbmc-deps/aarch64-linux-gnu-debug/include (found version "23.1.4")
```

**Pull request closed without merging**
