### PR TITLE
[Android] support ClearKey crypto type

### PR DESCRIPTION
**Pull request by glennguy**
## Description

Along with Widevine, PlayReady and WisePlay this will add ClearKey as a valid type for encryption scheme. Really these types are only used so far on Android.

Of course, this requires changes to the inputstream API and so will require releases for all binary add-ons consuming it.

## Motivation and context

We plan to add ClearKey support to inputstream.adaptive in the near future and this prepares for that. Benefits are that we can continue to reference the key system types in the kodi add-on dev kit, and that decrypting ClearKey protected videos on Android can use the Android MediaDrm API to do it, avoiding doing this in software.

## How has this been tested?

Not tested - as above, the implementation in inputstream.adaptive is yet to be done.

## What is the effect on users?

They will stop asking 'are we there yet' for ClearKey on the IA issue tracker :)

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [x] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by glennfiddich** [comment]
Why only in android? ClearKey encryption scheme could be easely used in other platforms supported by kodi.

Sorry for my poor english

**Comment by matthuisman** [comment]
I may be mistaken, but I think IA will support it on all platforms. this just allows IA to use media DRM on android.

**Comment by glennguy** [comment]
Correct @matthuisman, to be very clear:

> Really these types are only used so far on Android.

means the code changes will only have an effect on Kodi Android. On other platforms there is no option but to do decrypting in software (in IA)

**Review by phunkyfish — APPROVED** [review]
Looks perfectly sane to me.

**Comment by phunkyfish** [comment]
Also added @AlwinEsch as a reviewer as this touches the binary addon API.

note that this PR must be merged the day before any related add-on PRs are merged.

**Comment by CastagnaIT** [comment]
closed as superseeded by #23541

**Pull request closed without merging**
