### PR TITLE
move CUtil tests to gtest unit tests

### PR DESCRIPTION
**Pull request by notspiff**
Some tests for CUtil exist under some nasty define. Move them to proper gtest unit tests.

Requires project updates.

### CODE REVIEW

**Comment by Memphiz** [comment]
mhh since osx builds tests from makefile too it only needs windows project adaption i guess?

**Comment by notspiff** [comment]
right.

**Comment by Memphiz** [comment]
@notspiff https://github.com/Memphiz/xbmc/commit/2684d9b8f05d29cdab5ef44bea73861a9f6194ca - cherry-pick this - can't do a PR to your repo.

Jenkins unit tests from my branch are running here: http://jenkins.kodi.tv/job/TestMulti-All/187/

once they are through witout mentioning the affected tests this can go in any time.

**Comment by notspiff** [comment]
i will cherry but you can do a PR - this is sent from a fork. if not, i couldn't send a pr here either :)

**Comment by Memphiz** [comment]
well technically it should work - but i can't find a "notspiff" repo to pick as destination in the drop down list... might be a github issue - but i met this issue a lot of times already for different repos. Might be something with public/private repo setting or just a bug ;)

**Comment by Memphiz** [comment]
Funny - as of jenkins those test weren't even run before:

567 tests (+3)

Also one of those fails on windows:

http://jenkins.kodi.tv/job/WIN-32/4405/testReport/junit/(root)/TestUtil/MakeLegalPath/

**Comment by notspiff** [comment]
correct, they were not run before. the code were in there but that was all.

**Comment by notspiff** [comment]
rebased with fix for win32 (it was simply borked in the code..)

**Comment by Memphiz** [comment]
thx

**Pull request merged**
