### PR TITLE
[gif] Some improvements

### PR DESCRIPTION
**Pull request by ace20022**

### CODE REVIEW

**Comment by ace20022** [comment]
@HitcherUK could you please try this?

http://kodi.wiki/view/Texture_Attributes#Formats is outdated, now any gif should work.

**Comment by HitcherUK** [comment]
Will do, thanks.

**Comment by ace20022** [comment]
jenkins build this please

**Comment by HitcherUK** [comment]
Build failed -

http://jenkins.kodi.tv/job/WIN-32/6190/

**Comment by ace20022** [comment]
Only pvr failed: http://jenkins.kodi.tv/job/WIN-32/6202/

**Comment by HitcherUK** [comment]
Thanks, it works again as a skin texture but trying to view it in a list and/or slideshow doesn't.

**Comment by ace20022** [comment]
>but trying to view it in a list and/or slideshow doesn't.

But that didn't work before, did it?

**Comment by HitcherUK** [comment]
> But that didn't work before, did it?

No, but I wasn't sure if this was meant to enable them there as well.

**Comment by ace20022** [comment]
That's a bit more work, thx for testing!

**Pull request merged**
