### PR TITLE
[backport] [scraper] Pass JSON serialized path settings to python scrapers

### PR DESCRIPTION
**Pull request by Montellese**
## Description
This is a partial backport of #17062 and #17063.

## Motivation and Context
It was requested by @romanvm and @rmrector.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by Montellese** [comment]
See #17112 for the backport for Leia.

**Review by rmrector — APPROVED** [review]

**Review by romanvm — APPROVED** [review]

**Comment by Montellese** [comment]
IMO this is ready to be merged into `Leia`. Who is the release manager?

**Comment by rmrector** [comment]
@DaveTBlake

**Comment by DaveTBlake** [comment]
Sorry I have not been following this work. I'm sure it is all fine, but can someone just confirm the scope of the impact of this change. I assume Python scrapers only, is that correct?

**Comment by rmrector** [comment]
Ya, the functional change is limited to Python scrapers. There is also a structural change for subsettings, motivation detailed in the second paragraph of #17062 .

**Comment by Montellese** [comment]
Actually I think this would even work without refactoring where `ISubSettings` are handled. I'll give it a try and report back. Without that commit this would purely touch the python scraper implementation.

**Comment by Montellese** [comment]
Yup that seems to work as well. @rmrector could you verify the functionality again with the reduced version?

**Review by rmrector — APPROVED** [review]
Yup, a quick run works just fine. Thanks for slimming down the backport.

**Comment by Montellese** [comment]
@DaveTBlake now it's really ready :-)

**Comment by DaveTBlake** [comment]
Thanks for slimming this down @Montellese , always good to simplify  backports if possible, glad that I was slow on the button.

**Pull request merged**
