### PR TITLE
[guilib] implicit referencing for listitem bools / ints

### PR DESCRIPTION
**Pull request by phil65**
some code refactoring + also allow implicit referencing for listitem bools, listitem ints and container bools.

@ronie @xhaggi

### CODE REVIEW

**Comment by ronie** [comment]
tested & works great :-)
thx!

**Comment by phil65** [comment]
jenkins build this please.

**Comment by phil65** [comment]
stupid jenkins build this please.

**Comment by phil65** [comment]
jenkins build this please.

**Comment by phil65** [comment]
jenkins build this please.

**Comment by ronie** [comment]
looks like this is causing regression with grouplists...
explicitly referencing a grouplist in a bool now always returns false.

you can test by adding a label in Estuary to SkinSettings.xml and adding this condition:
`<visible>Container(610).HasNext</visible>`

it works as expected in krypton, but in leia the label never shows up.

**Pull request merged**
