### PR TITLE
[PVR][JSON-RPC] Expose EPG tag's icon path as 'thumbnail' property.

### LINKED ISSUE #19967: Thumbnail of PVR Broadcast not filled in JSON RPC Call
### Describe the bug
Here is a clear and concise description of what the problem is:
When calling the JSON RPC Method "PVR.GetBroadcasts" an array of "PVR.Details.Broadcast" objects is returned. These objects contain the property "string thumbnail", but it is just empty when calling the method for a specific channelid. 

Same with JSON RPC Method "PVR.GetChannels" for a specific channelgroup id, for objects "broadcastnow" and "broadcastnext" no thumbnail is available.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I would expect that the EPG Image which is assigned to the corresponding broadcast is set as thumbnail. 

## Actual Behavior
As already menitoned, the field is just empty. After checking the Kodi core code in xbmc/interfaces/json-rpc/FileItemHandler..cpp, it seems that only video and audio files are handled correctly by the code setting the thumbnail (via CThumbLoader), but EPG Images of PVR Broadcasts are not respected.

### To Reproduce
Just call the described JSON RPC calls for a broadcast with EPG Image.

### Debuglog

Not relevant.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux
 - [ ] OSX
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Matrix 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
Fixes #19967 

@DaveTBlake does this change require a json-rpc API version increase?

@phunkyfish this is a one-liner. It seems, it was originally simply forgotten to add.

### CODE REVIEW

**Comment by louisbraun** [comment]
Thanks a lot for quick reaction and the fix. 

Since this is just a really minor bug fix...would it be possible to add it to next Matrix version? I'd like to use this in my Skin, and waiting on v20N would be rather annoying ;)

**Comment by ksooo** [comment]
> Thanks a lot for quick reaction and the fix.

@louisbraun Did you have the chance to runtime-tested it?

> would it be possible to add it to next Matrix version

@DaveTBlake your take on this?

**Comment by DaveTBlake** [comment]
> does this change require a json-rpc API version increase?

Yes, it is an internal implementation change so make a patch bump so that API consumers know "thumbnail" will now return data. Hence to 12.3.2

The schema `Version` method description documents it as follows
```
"major": "Bumped on backwards incompatible changes to the API definition"
"minor": "Bumped on backwards compatible additions/changes to the API definition" 
"patch": "Bumped on any changes to the internal implementation but not to the API 
```

Also yes as a fix, correction of an omission is a fix, a backport to v19 is wanted. While API used by v20 and v19 are inline we can continue to makes fixes

**Comment by louisbraun** [comment]
Great news! 👍 

I had not the change to test it...stupid question: is a windows build available from current master? Then i can test it later today.

**Comment by ksooo** [comment]
>  is a windows build available from current master

that wont help as this PR was not merged yet

**Comment by phunkyfish** [comment]
> > is a windows build available from current master
> 
> that wont help as this PR was not merged yet

We can create a test build from this PR for windows.

**Comment by ksooo** [comment]
@louisbraun here is a test build: http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20210714-55131611-pvr-serialize-epgtag-thumbnail-x64.exe

**Comment by louisbraun** [comment]
Awesome 👍 Just tested it...works like a charm :)

Now i'm at last able to integrate epg images in my python created PVR views in my skin (see https://github.com/louisbraun/skin.unfussy)

**Review by phunkyfish — APPROVED** [review]

**Pull request merged**
