### PR TITLE
fix high cpu load issues

### PR DESCRIPTION
**Pull request by FernetMenta**
see title
@popcornmix @MilhouseVH does this fix the high CPU load issue you were observing?

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Unfortunately not, it doesn't appear to have made any difference either way (not better, not worse) - still about 40-50% CPU (1GHz Pi1) while idle at Music > Files.

**Comment by FernetMenta** [comment]
do you observe this only in music menu? no high load in video menu?

**Comment by MilhouseVH** [comment]
Yes, there is the same high load in Videos > Files too.

Idle load on a 1GHz Pi1 with clean `.kodi` is about 9-10%, but when entering `Music > Files` and `Videos > Files` the CPU load is pegged at between 40 and 50%, and the SoC temperature steadily rises to 85C which in my experience only happens when the GUI is being hammered (eg. scrolling text, some part of the GUI being constantly updated etc.).

I've tried enabling `visualizedirtyregions` but I'm not seeing anything, so if there is some crazy GUI update going on, it's not visual.

**Comment by MilhouseVH** [comment]
If anything, the CPU load in Videos > Files is actually higher at about 57% than in Music > Files (40-45%).

**Comment by FernetMenta** [comment]
DR seems to be broken. there is always a control which is dirty. I am trying to locate it ...

**Comment by FernetMenta** [comment]
that seems to be the culprit: https://github.com/xbmc/xbmc/commit/c03ecbeff265d422cc503806023cc1b28050e7bb

**Comment by MartijnKaijser** [comment]
This one is obsolete by the other fix?

**Comment by FernetMenta** [comment]
still valid

**Comment by popcornmix** [comment]
Added to newclock4 so we can test in tonight's Milhouse build.
@MilhouseVH I'd be interested if you can still see a CPU increase now the other fix is in.

**Comment by MilhouseVH** [comment]
Sorry for the delay responding. After #7504, and now with this commit, I'm still not seeing high CPU load so it appears this commit has had no negative effect.

**Comment by MartijnKaijser** [comment]
should this be rebased and merged?

**Comment by popcornmix** [comment]
This commit has been in Milhouse builds for a few months, so I'm fairly happy it doesn't cause any problems.

**Comment by FernetMenta** [comment]
I need to find time to get my head around this again. Would like to leave it open as a reminder.

**Comment by FernetMenta** [comment]
@mkortstiege could you test this please. it should fix http://trac.kodi.tv/ticket/16524

**Comment by mkortstiege** [comment]
Sorry, no nvidia hardware here.

**Comment by simonbuehler** [comment]
can test tonight when i manage to bend the ebuild src to your branch

**Comment by simonbuehler** [comment]
Starting Kodi (17.0-ALPHA1 Git:2016-01-25-9cc4a76-dirty). Platform: Linux x86 64-bit
... pausing ...
 0.8%CPU 
:ok_hand:  

great work, thanks

**Comment by FernetMenta** [comment]
thanks!
jenkins build this please

**Pull request merged**
