### PR TITLE
[GLES] more shader cleanup

### PR DESCRIPTION
**Pull request by lrusak**
This has a few purposes:
 1. to align GLES code more similarly with GL code
 2. to allow using glslangValidator more easily as it only accepts `.frag` and `.vert` extensions
 3. to prepare for a separate GLES 3.0 code path

git does something funny when displaying the complete diff as it shows some files being removed and some new files being added. This is because the diff only detects the same file if it is 50% or more similar. So when removing the header which is over 50% of the file git thinks the file isn't the same. So I have split the commits into renaming the files, then in another commit changing the contents. If you view the individual commits it show things more clearly. This also allows the git history to be complete. If anyone has any hints or tips about this that would be awesome.

build and runtime tested on GBM but should be worth testing on android and other GLES platforms.

### CODE REVIEW

**Comment by MrMC** [comment]
Why is Copyright and licensing being removed from these files ?

**Comment by lrusak** [comment]
@MrMC I'm not really sure. I think it had to do with running through the glslangValidator, but it seems to work fine with the headers. I've fixed it.

**Comment by MrMC** [comment]
thx, copyright and licensing should never get removed without the consent of the authors.

**Comment by lrusak** [comment]
Yep sorry, that's my bad

**Review by FernetMenta — APPROVED** [review]
I think this is ok

**Pull request merged**
