### PR TITLE
Add 19.3 release to Linux metainfo

### PR DESCRIPTION
**Pull request by razzeee**
Backport of https://github.com/xbmc/xbmc/pull/20415

### CODE REVIEW

**Comment by thexai** [comment]
The train for 19.3 left a long time ago.

This should move to 19.4, right? and close Milestone 19.3    

@DaveTBlake ?

**Comment by DaveTBlake** [comment]
> his should move to 19.4, right? and close Milestone 19.3

Yes, done.

**Comment by razzeee** [comment]
Well, technically, I would like to get this merged, to target this sha, so that we can build a flatpak of 19.3 that's correct.

**Comment by thexai** [comment]
I am not familiarized with Linux things but I think it can be merged right now without any problem (both master and Matrix branch). 

Never is too late 😀

**Comment by thexai** [comment]
jenkins build this please

**Comment by razzeee** [comment]
jenkins build this please

**Pull request merged**
