### PR TITLE
[gui] no need to store/restore modeless dialogs while unload/load skin

### PR DESCRIPTION
**Pull request by xhaggi**
There is no need to store/restore modeless dialogs while unload/load skin. A modeless dialog will automatically be opened/closed depending on its visible condition.

This also leads to problems if different skins use custom modeless dialogs with the same id (skin A and B use window id 1000) and you switch between this skins (see http://forum.kodi.tv/showthread.php?tid=314185)

@BigNoid mind taking a look.

### CODE REVIEW

**Comment by BigNoid** [comment]
I see no regressions when testing, e.g. custom windows/dialogs still load when its visible after switching skins.

Not sure if it should be part of this PR or not, but I do think we need an extra function like ```CGUIWindowManager::RemoveFromWindowHistory()``` that can remove custom window id's from history when ```CGUIWindowManager::DeInitialize()``` is called. Right now if you switch to a skin from Estuary's addoninfo (navigated to through the main menu addon menu item) and you go back, you can go back to the new skin's custom window with ```id="1100"``` which can lead to unexpected results like a black screen if that window/dialog should not be visible.

**Comment by xhaggi** [comment]
Added another commit to address your comment. It makes totally sense to remove the custom window from our window history while destroy them.

**Comment by BigNoid** [comment]
Works great, thx for adding that 👍

**Comment by xhaggi** [comment]
Thanks for testing it.

jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by xhaggi** [comment]
jenkins build this please

**Pull request merged**
