### PR TITLE
[Estuary] Fix Music Viz & Remove Time Remaining

### PR DESCRIPTION
**Pull request by jjd-uk**
## Description
Fix and clean up the Music Viz and Video OSD

###  [CEANUP] - Remove time remaining labels

After introduction of the new top seekbar the **time remaining** info is never displayed. So if it's not wanted anymore it should be removed.

###  [FIX] - Modify music viz Info background image width

Following https://github.com/xbmc/xbmc/pull/18465 the Music Viz info background as well as cover image & metadata slide off to the left, this caused the right edge of the background to be seen as it slides off.

 **Before Fix**
 image
 
Video does not have this problem, here the background image is set to 120% and setting the Music Viz image to the same fixes the issue.

**After Fix**
image

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by jjd-uk** [comment]
### Time Remaining

If the Time Remaining not being seen now wasn't intentional and people want it back, then there 2 options as I see it in order to bring it back, however I'm not convinced we need both **Time Remaining** and **Ends at** to be shown

**Option1**
Move to bottom left when Info is displayed and it's NOT PVR (as recording label goes here for PVR, although Recording label could be removed and incorporated in $VAR[SeekLabel ).

image

**Option 2**
Move to new to seekbar however this requires other label adjustments
image

**Review by ronie — APPROVED** [review]
looks good to me as is.

**Comment by ksooo** [comment]
> Move to bottom left when Info is displayed and it's NOT PVR (as recording label goes here for PVR,

 Oh no. I want time remaining also for PVR recordings, please.

**Comment by jjd-uk** [comment]
@ksooo well it appears that @ronie doesn't want Time Remaining at all so you'll need to convince him. I'm not convinced either about the need for it, but I'm willing to do the work to reinstate it somewhere it can be seen. However if I was to do the work to reinstate the Time Remaining then I would want clear guidance on what would be acceptable, as I don't want to get into bike shedding on something I care nothing about.

**Comment by ksooo** [comment]
I'm fine with removing it completely. I just did not wanted inconsistency (like available everywhere but PVR).

**Comment by jjd-uk** [comment]
So no problem then, all is fine with the PR in it's current state as it is consistent in that it removes the no longer showing Time Remaining labels for both `Player.TimeRemaining` and `PVR.EpgEventRemainingTime` .

**Comment by zag2me** [comment]
Will this still allow the user to display the seek bar with the up arrow on Music Viz?

**Comment by jjd-uk** [comment]
> Will this still allow the user to display the seek bar with the up arrow on Music Viz?

Up is skip to Next Track???

**Comment by zag2me** [comment]
> > Will this still allow the user to display the seek bar with the up arrow on Music Viz?
> 
> Up is skip to Next Track???

Sorry I meant select which should bring up the track name and progress bar manually. Usually I leave this on all the time so I can see the progress and track info.

**Comment by jjd-uk** [comment]
> > > Will this still allow the user to display the seek bar with the up arrow on Music Viz?
> > 
> > 
> > Up is skip to Next Track???
> 
> Sorry I meant select which should bring "up" the track name and progress bar manually. Usually I leave this on all the time so I can see the progress and track info.

On my install that brings up the OSD menu view with track info, progress, player controls & settings (the same as pressing M on keyboard) so that is all completely unchanged from before after the introduction of ronie's new seek bar. The new seek bar is only seen when you have only the fanart or viz with no info/menu overlay and perform a seek action.

**Comment by DaveTBlake** [comment]
> ...all is fine with the PR in it's current state as it is consistent...

Good to merge?

**Comment by jjd-uk** [comment]
Yep

**Pull request merged**
