### PR TITLE
[macos] implement code signining

### PR DESCRIPTION
**Pull request by kambala-decapitator**
## Description
Adds ability to sign the built .app/.dmg and notarize the .dmg. New cmake variables:

- CODE_SIGN_IDENTITY
- DEV_ACCOUNT
- DEV_ACCOUNT_PASSWORD
- DEV_TEAM (optional)

`CODE_SIGN_IDENTITY` is used to sign binaries and .dmg (passed to `codesign` in `--sign` parameter), others are used to perform notarization (passed to `altool` in `--username`, `--password` and `--asc-provider` parameters respectively).

Example: `make -C tools/depends/target/cmakebuildsys CMAKE_EXTRA_ARGUMENTS='-D CODE_SIGN_IDENTITY="Developer ID Application: Kodi Foundation" -D DEV_ACCOUNT=appleid@kodi.tv -D DEV_ACCOUNT_PASSWORD=mypassword'`

## Motivation and Context
Starting with macOS 10.15 Catalina (even with 10.14.5 for new developer certificates, which applies to Kodi) all software distributed not through Mac App Store must (should?) be notarized by Apple. Otherwise it would be impossible to use such software without workarounds/hacks because of Gatekeeper. And notarization implies code signing. Further reading: https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution?language=objc

## How Has This Been Tested?
Built `dmg` target on local machine and on jenkins and checked that the resulting .app/.dmg are code signed properly and notarization process finishes successfully.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [X] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [X] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
I'll modify Jenkins steps to use Kodi's developer account for signing as soon as we setup process to import private key and developer account credentials.

**Comment by kambala-decapitator** [comment]
also signed and notarized all existing releases with script https://gist.github.com/kambala-decapitator/0c801357d37f3756b90f00ce3ef6a0a0

**Comment by djp952** [comment]
Hi kambala-decapitator, may I ask a question about this? How are third-party binary addons (PVR clients, Visualizations, etc) that aren't built as part of Kodi supposed to handle this change? .dylib modules not signed with the same certificate Kodi used will not load (nor will unsigned .dylib files).

I can open an Issue, but wanted to ping you quickly to see if I'm missing something on my end, like if the .dylib was signed with a formal Apple Developer ID certificate that would work?

If this wasn't considered and there is no simple solution, no problem, I'll open an Issue so it can be discussed.  Thank you!

**Comment by kambala-decapitator** [comment]
@djp952 #17269

signed app can only load external dylibs that are signed with the same certificate.

**Comment by phunkyfish** [comment]
> @djp952 #17269
> 
> signed app can only load external dylibs that are signed with the same certificate.

So to run any 3rd party binary addon on a Mac you must build kodi yourself and then build the addon yourself?

Can a kodi you build yourself still use the binary addon repos even if those are signed and your Kodi is not?

**Comment by kambala-decapitator** [comment]
> signed app can only load external dylibs that are signed with the same certificate.

Seems that I was wrong: 3rd party libs can be signed with any other developer ID: https://helpx.adobe.com/au/indesign/kb/indesign-plugin-notarization.html (thanks to @fuzzard)

@phunkyfish I think unsigned app can't load signed dylibs (but I can be wrong), but you can easily remove the signature with `codesign` command. (Removing signature from Kodi itself might not be a 1 step because of python eggs)

**Comment by djp952** [comment]
**kambala-decapitator**, thank you for that link, I didn't see this come in while I was entering the Issue referenced above.

I do think, though, that having a requirement that people contributing their time and energy to extending Kodi for free apply for and subsequently maintain an Apple Developer ID will turn them away from this platform.

If this is the only valid path forward, and it's documented accordingly, that should suffice.  My users will be disappointed since I won't be paying Apple money to contribute to Kodi, but they can switch to Windows or Android :)

**Comment by kambala-decapitator** [comment]
Main reason for signing is described in Motivation and Context. In the worst case we can always just revert to unsigned distribution.

There's also an option for 3rd party to use free developer certificate, but it's valid only for 7 days - after that new free certificate must be generated and dylib must be resigned with it.

**Comment by djp952** [comment]
I get it, but also find it disappointing that a serious breaking change was not only introduced but subsequently accepted and then distributed (or in this case just completely replaced) existing  baselines without providing any advance notice or documentation of the required path forward to community contributions to this project.  This should have been at minimum exclusive to Matrix in order to give third-party contributors time to make a choice on if or how they will accommodate it.

Opinion, of course.  Kodi will do what Kodi will do and that's that.  This one just kinda hurts.

**Comment by phunkyfish** [comment]
@djp952 I think the intent here was to open kodi up to more users. All these side effects were unknown surprises I’m afraid.

Maybe we should look at providing signed and unsigned versions.

**Comment by djp952** [comment]
Hmmm. Old 18.5 was working fine after the upgrade to Catalina. Are permissions for existing installed apps grandfathered in? I had to reinstall using the notarized dmg to duplicate the users concern. MacOS is a mystery to me :)

Any chance there is a programmatic solution that could be tied to "Unknown Sources"?  I doubt it but that seems ideal, letting the user opt in and accept risk rather than leaving them exposed by default.

I'm sure you guys will figure something out :) Keeping the users safe is the important part!

**Comment by fuzzard** [comment]
Just to keep you updated, we have a solution in theory, just need to get it implemented.
Unfortunately the macos side of things has been a little neglected, so we are having to redo a lot of the macos build scripts for the automation.

**Comment by djp952** [comment]
Awesome! Let me know if you want/need a guinea pig to test anything out for you guys.

**Comment by DaveTBlake** [comment]
Seems that you found another way around this issue, so can this be closed? Pulling backport off anyway.

**Comment by phunkyfish** [comment]
This may still be needed as they did it manually for 18.6 and matrix.

**Comment by DaveTBlake** [comment]
Ah right. Well we will let @kambala-decapitator enjoy the rest of his holiday first :)

**Comment by fuzzard** [comment]
Yeah, this will still go in to matrix, and if an 18.7 happens, we'll backport it as well just so we dont have to manually sign/notarize the release like kambala did for the 18.6 version just done.

Kambala was working on how we can have jenkins handle certs from master to the build slaves without having to manually install/manage certs on the build slaves.

If we cant get that sorted out in a reasonable time, the fallback is to just install certs manually, and work on the jenkins thing later

**Review by fuzzard — APPROVED** [review]

**Comment by kambala-decapitator** [comment]
PR is ready for review.

- cmake/bash/doc changes in commits
- adjusted jenkins job: https://jenkins.kodi.tv/job/OSX-64-codesign-test/

Jenkins job contains the following changes:

1. 3 credentials added (Bindings section)
2. extra script added before calling `configure-xbmc`

Remarks:

- the extra script from 2) above could be moved to a file, but then it must reside in a private repo
- [75 notarizations per day is allowed](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow). If needed, we can disable notarisation of PRs and do it only for nightlies, releases and when specified manually. (new Jenkins setting will be needed)
- successful debug build with one addon: https://jenkins.kodi.tv/job/OSX-64-codesign-test/18/
- successful release build with all addons: https://jenkins.kodi.tv/job/OSX-64-codesign-test/23/
- backport to Leia should be possible, but requires Xcode 10 because `altool` utility isn't available in older Xcodes. It might be possible to use it as a standalone though, but needs testing.
- it'll be possible to make PR green once jenkins job changes are imported into the main OSX job

**Review by Memphiz — APPROVED** [review]
Looks straight forward. How long does that notarization step take?

**Comment by kambala-decapitator** [comment]
> How long does that notarization step take?

around 5-7 minutes. From the release build's log:

> 23:05:11 uploading ./org.xbmc.kodi-osx_19.0-0~alpha1_macosx-intel-x86_64.dmg for notarization
> 23:05:34 requestUUID: e5377d3c-a28a-42f4-96fc-d3d1bb32647d, waiting...
> 23:12:48 2020-07-12 15:12:48.187 altool[9128:1296643214] No errors getting notarization info.

**Comment by DaveTBlake** [comment]
> backport to Leia should be possible

I would not bother. We only have to do so one more time (if that), so a manual approach is fine.

**Comment by kambala-decapitator** [comment]
jenkins build this please

**Pull request merged**
