### PR TITLE
[VideoDatabase] Save correct stream details for multi-episode Blurays.

### PR DESCRIPTION
**Pull request by 78andyp**
## Description

Note - I messed up rebase in #24173 - this is the same thing.

I have The Last of Us on UHD. There are multiple episodes per ISO.

I noticed that whenever I watched an episode - the episode details shown at the bottom right change for every episode on the disc.

If I then watch the next episode - again the details for every episode on the disc change to the episode just watched.

## Motivation and context

Firstly this is wrong. It appears the the `streamdetails` table only allows one stream per filename (the filename is the <disc>.iso).

Secondly, i've been working on some code to make episode selection from ISO easier (trying to make an educated guess as to which title(s) are which episode) - and part of this is much easier if the correct episode length is recorded for each episode.

Base
Having just refreshed from scraper - no details shown and duration from scraper.
image
image

Before
Having just watched episode 1 - the details for both Episodes 1 and 2 (both on first ISO) have changed.
image
image

After
Having just watched episode 1 - only episode 1 has changed
image
image

Then watching episode 2 - only 2 has changed and 1 is preserved.
image
image

## How has this been tested?

The only fix I can think of is adding an additional field in the `streamdetails` table - `iEpisodeHash`. This defaults to -1 (the default in a `VideoTagInfo`). This then allows more than one stream per filename.

BUT
1) This requires bumping the database schema version to 125.
2) All existing `streamdetails` will have their `iEpisodeHash` set to -1 so effectively become orphan `streamdetails` for the episodes with `streamdetails` already in the table - I'm not sure the best way to deal with this - both from a wasted space in database perspective and also it effectively 'resets' the information for all episodes that have already been watched.

Other than that it works on my test build.

As above.

Window 11 x64.

## What is the effect on users?

See BUTS above.

Should mean accurate episode details reported per episode for those on discs.

Thanks for looking at this. I hope I haven't buggered anything up.
If there is a better way of doing this I'd be interested to learn.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by 78andyp** [comment]
> I'm not so sure anymore than an episode / hash field in streamdetails is correct, because each record is attached to an idFile.
> 
> But episode/season numbers are attributes of tv show/season/episode, and are identified by a media_id / media_type.
> 
> Thinking beyond the case of a disc with episodes, we would need this extension to work with something similar like extras for example.
> 
> Thinking out loud, the other way to implement what you did would be to have one file / idFile per "virtual video" inside the file, if that makes any sense?

Thanks. I haven't really looked at the video versions and extras yet. If they are different files (and I accept that most people use MKVs so they probably are) - then it should be fine - each file has a seperate `idFile`.

This issue only occurs if there are multiple 'virtual videos' in a file and the only case I've come accross is Bluray ISOs.

DVDs (both VIDEO_TS and ISO) don't seem to update `streamdetails` - I assume the DVD play library doesn't return information.

The only problematic case I've come accross is if, when trying to play an episode, you select the wrong title (hence PR #24178) then it will save the wrong stream details.

I'm thinking there should also be a way to browse the titles without stream details being updated (and I'm working on that currently through Video -> Files -> ...)

**Comment by CrystalP** [comment]
I meant extras in an iso. Extra as its own file is already ok as one record of "file" table.

Kodi supports archive files (rar) but I don't know if multiple files in the archive are supported.

The BD/DVD as folder structure is a further complication as the multiple physical files would need to be abstracted as one file like an ISO and then subdivided... It hurts thinking about it.

**Comment by 78andyp** [comment]
> I meant extras in an iso. Extra as its own file is already ok as one record of "file" table.
> 
> Kodi supports archive files (rar) but I don't know if multiple files in the archive are supported.
> 
> The BD/DVD as folder structure is a further complication as the multiple physical files would need to be abstracted as one file like an ISO and then subdivided... It hurts thinking about it.

The key here must be the `playlist`. I've been thinking about extras.

There are two problems here.

Lets say I have an ISO and i've just included the episodes in the name - say S01E08E09 - then I will only have those two episode entries in TV shows (eg. in the pictures above episodes 8 and 9 are in one phyiscal ISO).

If I want to play extras I from that ISO (and by my count there are 15!) I have to select an episode and then choose 'Show Blu-ray Menu' or 'Select from all titles ...'. With the former I can find the extra I want but have no idea what the playlist is. With the latter I just have to take an educated guess.

The problem with this, is that whatever playlist you play, Kodi will assume that's the episode and save the stream details for it (whether you want it to or not).

Episodes are less of a problem (and #24178 goes a fair way to help with that).

I don't know currently what happens with a movie ISO containing two cuts - can the video versions stuff handle this currently??

Thinking about it I would suggest that we add two extra fields into `streamdetails`.

1) We need to refer to the playlist - this is going to be unique per file (ie. disc).
2) We change the `iEpisodeHash` to just `iHash` - this is going to be unique (but two way)  per file/disc but 'usable' - ie. we can associate playlist 801 with season 1 episode 8 etc..

This will mean we can simply the (re)play of episodes - as we can search in `streamdetails` for both the stream details that are already displayed but also the playlist. We can then add a dialog if an episode is played but a different playlist is selected asking if we should replace the existing playlist.

We could even use the #24178 code to match playlists to episodes when adding to library. Extras will need manual matching (but once done it can be saved in `streamdetails`) - this will need a new GUI dialog.

Thoughts??

**Comment by 78andyp** [comment]
Looking at video versions and movie ISOs with more than one cut.
The Wicker Man UHD.
There are two discs - disc 1 has the Final Cut.
Disc 2 has the Directors Cut and the Theatrical Cut.

Using video versions I can add the second ISO as an additional version.
I can even add the same file a second time under a different version:
image

This does seem to create a second `idFile` for the same file and this is reflected in `streamdetails`.
image

So I guess we could use the `videoversion` table:
image

`mediaType` could be `episode` and the `idType` could be the season/episode hash??

**Comment by 78andyp** [comment]
We would still need to store playlists (perhaps add a column in the `videoversion` table) so we can avoid:
image

which is what I get when selecting theatrical or directors cut.

**Comment by CrystalP** [comment]
Yes I was thinking about using the BD playlist as well. It's a good key for a BD and should work for any the contents of a disc as far as I know: episodes, extras, main feature, multiple cuts.

Where/how to store it, and where to store the relationship with episodes though.

Thinking of streamdetails as an object, seems to me that it shouldn't contain the mapping to episodes or movies, but storing the playlist in there could make sense as a new primary key of streamdetails.
FYI some movies are also considered as "special" episodes, so putting the episode#/hash in streamdetails would be problematic.

The other way is to store the playlist in the file table, with one record per playlist. That way the rest of the data model doesn't need to change.


@da-anda do you have thoughts about integrating the concept of multiple videos in a file in the db (episodes in ISO here, but could be more in the future)?

**Comment by da-anda** [comment]
sorry, I do not have a concept for this right now (need to dig into the DB and current structure first). One random thought was that we could maybe use VFS for this and convert ISO files to a VFS directory and the playlists as files. Not sure if this would actually work though or just cause issues in other places.

Btw, MKVs can also contain multiple video streams and also be segmented IIRC, so technically you could have one MKV file that contains f.e. theatrical cut and extended cut, or 3D + SD + HD + UHD-HDR in one file, which would also be video versoins where each would need it's own streamdetails dataset. This stuff is not really common though, but is super simple to create (in case the streams have the same framecount at least so that you can reuse one audio stream for all)

**Comment by 78andyp** [comment]
Thinking about it - I think putting the playlist in streamdetails makes sense - as ultimately there will only be one stream per playlist  and they will be inexorably linked. When we want to play an certain episode or movie version again - what we effectively want to do is play the stream again (and we already use the streamdetails to display information in the bottom right) and the way we relate the stream to the 'physical' disc is the playlist/video version.

Where the episode/video version is a file then the playlist is irrelevant and the filed can be -1.

@da-anda - that would work for BDs where there are .mpls files but not for DVDs - the playlists are within the IFO files and I don't think  we parse those in the same way - we rely on the DVD menu. I know back in the MyMovies and Windows Media Center days there was a way to play episodes straight from the DVD directly but  don't know how it worked.

I'll have a go changing this commit to put a playlist field in streamdetails and see how it goes. I'l rebase first to make sure i've got all the latest videoversion updates.

PS Happy Christmas/Holidays everyone :)

**Comment by 78andyp** [comment]
Looking further `streamdetails` doesn't actually have a unique ID field (most references to are to idFile).
So, if we wanted to associate a stream in streamdetails with an episode (ie. add a stream field in the episode table and then put the playlist in streamdetails as above) we can't without a unique ID in streamdetails. 

So, which is preferable:
1) Add unique ID field in streamdetails and then stream field in episodes (and any other table eg. movie/videoversion etc..) that refers to the unique ID in streamdetails
2) Add a hash field along with a playlist field in streamdetails - and use the hash to associate with episode/movie(version) etc.. (ie. calculate season/episode hash as above and say use a negative number for move/version)

1 is probably the 'proper' way to do it, but 2 would be more straightforward. Any thoughts??

**Comment by 78andyp** [comment]
@CrystalP - what do you think?? This is probably the 'correct' way to do it - associate an episode with a stream and that stream with a playlist.

If everyone is happy with this approach then I'll add it to movies as well.

**Comment by 78andyp** [comment]
@ksooo - I'd be grateful for your thoughts.

I am currently looking at extending this to multple move versions on a Bluray disc. This is not uncommon.
But the videoversion code as it stands uses `idFile` as a primary key - so there can only be one version per file (and each ISO is one file in the `files` table).
Is it OK to remove the primary key constraint from the `idFile` field in the `videoversions` table??
Is there a better way??

**Comment by ksooo** [comment]
> I am currently looking at extending this to multple movie versions on a Bluray disc.

Please, refrain from this for now. We are in the middle of stabilizing the video versions/extras feature for movies so we can ship something stable and valuable for Omega. No time to take care about any new functionality for this feature at the moment. Please wait with your feature until development for v22 has started.

**Comment by 78andyp** [comment]
Thanks. I'll leave it as it is for episodes for now.

**Comment by rmrector** [comment]
Kodi has a very flexible pathing system along with the virtual file system, which among other things allows you to point to a file inside of another file, such as a playlist file inside of a Blu-ray ISO or physical disc. That should let you point stream details to each playlist without adding a new column.

I don't know of anything written down to point you to, nor exactly what code will be enlightening. Such a thing does exist in some places for Blu-rays already, though, which can be observed - maybe enough to work backward from to reuse for this feature. In Video Files, open the context menu on your ISO and select "Browse into", navigate to a playlist, then view the skin InfoLabel **ListItem.FileNameAndPath**. The resulting path looks like `udf://nfs%3a%2f%2fSERVER%2fsrv%2fThe%20Disc.iso/BDMV/PLAYLIST/00071.mpls`.

It looks unwieldy but it is basically a [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) - scheme is 'udf', host is percent-encoded path to the containing file `nfs://SERVER/srv/The Disc.iso`, and the path points to the internal file `/BDMV/PLAYLIST/00071.mpls`. In code you can use the **URL.h** / `CURL` class to build and parse it.


This system is also used for paths to files inside archives like RAR and ZIP files; and images can be more advanced, such as pointing to embedded cover art in a music file or a thumbnail generated from a video file.

**Comment by 78andyp** [comment]
> Kodi has a very flexible pathing system along with the virtual file system, which among other things allows you to point to a file inside of another file, such as a playlist file inside of a Blu-ray ISO or physical disc. That should let you point stream details to each playlist without adding a new column.
> 
> I don't know of anything written down to point you to, nor exactly what code will be enlightening. Such a thing does exist in some places for Blu-rays already, though, which can be observed - maybe enough to work backward from to reuse for this feature. In Video Files, open the context menu on your ISO and select "Browse into", navigate to a playlist, then view the skin InfoLabel **ListItem.FileNameAndPath**. The resulting path looks like `udf://nfs%3a%2f%2fSERVER%2fsrv%2fThe%20Disc.iso/BDMV/PLAYLIST/00071.mpls`.
> 
> It looks unwieldy but it is basically a [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier) - scheme is 'udf', host is percent-encoded path to the containing file `nfs://SERVER/srv/The Disc.iso`, and the path points to the internal file `/BDMV/PLAYLIST/00071.mpls`. In code you can use the **URL.h** / `CURL` class to build and parse it.
> 
> This system is also used for paths to files inside archives like RAR and ZIP files; and images can be more advanced, such as pointing to embedded cover art in a music file or a thumbnail generated from a video file.

Thank you. That's interesting. I'll try and adapt this to use that.

**Pull request closed without merging**
