### PR TITLE
DisplaySettings: Fix off by 1 iterator start in UpdateCalibrations()

### PR DESCRIPTION
**Pull request by yuri-sevatz**
## Description
Trying to fix "Video calibration settings changes are lost after Kodi restart"

Fixes what looks like an off-by 1 the iterator start position in DisplaySettings;:UpdateCalibrations().  It looked off when I went through the diff that caused the above bug here:
https://github.com/xbmc/xbmc/commit/e8c158606000f19fef478184e20898f8ff8bd5c4

## Motivation and Context
Video Calibration settings does not persist without this.

https://github.com/xbmc/xbmc/issues/15165

## How Has This Been Tested?
Just calibrated video and rebooted, verified that my overscan settings came up again.

I am extremely new to this project, so take my conclusions with a grain of salt until the author of the diff causing the bug has had a chance to go over it :+1: 

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fritsch** [comment]
Thanks much. That looks good to me.

**Comment by fritsch** [comment]
@peak3d https://github.com/xbmc/xbmc/commit/e8c158606000f19fef478184e20898f8ff8bd5c4 <- can you comment as you did the original commit?

**Comment by peak3d** [comment]
From concept RES_DESKTOP is a virtual one, after RES_DESKTOP index all USER modes should be listed.
Checking for RESDESKTOP seems to be wrong to me, we should go and print out the resolutions found to get the root cause of the issue.

**Comment by yuri-sevatz** [comment]
@peak3d 

The version before your patch uses RES_DESKTOP like the number of desktop resolutions.  (i.e. a length).  This length can be added to 0 to find the index of the first non-desktop display mode.  It was used like this in the code before your change.

> From concept RES_DESKTOP is a virtual one, **after** RES_DESKTOP index all USER modes should be listed.

I think this might explain the confusion and the bug here. If RES_DESKTOP is the length of all desktop resolutions, then adding 1 to RES_DESKTOP will position the iterator one-more-than-one-past-the-end of all desktop resolutions, which would be the the second non-desktop resolution (not the first!)

You should probably be thinking of it like:

**At** RES_DESKTOP index all USER modes should be listed.

**Comment by peak3d** [comment]
@yuri-sevatz could you pls. provide the log?

**Pull request closed without merging**
