### PR TITLE
[addons] improve safety of installing/uninstalling addon files

### PR DESCRIPTION
**Pull request by tamland**
This change should ensure that addons are either completely installed to the file system, or not installed if something fails, not leaving any partially installed/removed files.

Unlike the current procedure which just copies files one-by-one over the existing folder _praying_ everything goes ok.

Also includes some fixes to RemoveRecursive.

cc @Paxxi

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@Memphiz ping as well since you might want xcode still added right?

**Comment by Memphiz** [comment]
thx @MartijnKaijser 

can't do a PR to tamlands repo - so @tamland please pick https://github.com/Memphiz/xbmc/commit/4eae05e7cace139e57ff18e6998606c0bd2063af

**Comment by wsnipex** [comment]
the new file needs adding to xbmc/addons/CMakeLists.txt

**Comment by tamland** [comment]
already are..

**Comment by tamland** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
@tamland it fails on Windows

**Comment by tamland** [comment]
jenkins build this please

**Review by Paxxi — APPROVED** [review]
Sorry for the delay, changes look solid.

**Comment by tamland** [comment]
did anyone test this on windows..?

**Comment by MartijnKaijser** [comment]
@tamland nope not yet. Last i wanted to try it didn't build yet. Will build one now and let you know

**Comment by tamland** [comment]
Can any windows devs help with this? It seems like unpacking the archive suddenly fails (and silently, without returning error) with this weird message:
>XFILE::CDirectory::Create - Error creating C:\
>ERROR: Previous line repeats 264 times.

and `XFILE::CFile::Rename` also fails for a directory that should have been checked to exist. Log: http://paste.ubuntu.com/23359807/

**Comment by Paxxi** [comment]
@tamland I'll look at it now

**Comment by Paxxi** [comment]
The reason for the 260 error messages is this bit
https://github.com/xbmc/xbmc/blob/master/xbmc/filesystem/File.cpp#L116
For every file in the addon it will try to create the directory C:, c:\users, c:\users\per, c:\users\per\appdata, c:\users\per\appdata\local, c:\users\per\appdata\local\temp, c:\users\per\appdata\local\temp\guid

This should at a minimum be wrapped in an `if (CDirectory::Exists())` but it really should be moved into the CDirectory::Create implementations and probably reversed, try to create the full path, if that fails chop of a bit and try again, it's most likely that we're only missing one bit and not the whole path.

In my case installing from repo works but will spam the log.

Regarding the rename error I assume it's this bit

**Comment by tamland** [comment]
> That's a directory and it's expected that CFile::Rename fails on it.

Sure about that? That's not how it's implemented on other platforms. And there is no CDirectory::Rename. So I think it's a windows bug. It calls the [correct function](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365240(v=vs.85).aspx) for renaming directories but fail for some reason

**Comment by Paxxi** [comment]
You're right about the CFile::Rename, it seems I spoke too soon. It should support moving a directory on windows as well, as long as it's not moving it across drive/filesystem boundries.

I'm taking another look at it

**Comment by Paxxi** [comment]
I don't seem to be able to reproduce the issue with the rename failing.

One theory could be that something has an open file handle to a file in it, that will prevent a move/rename.

**Comment by tamland** [comment]
Ok, seem like there was just a misunderstand on my part and that the change works as indented on windows. Thanks for the help anyway @Paxxi :)
The only issue is with updating the skin that is in-use, which is not related to this pr. Same with the 'creating C:\': this looks like an old issue. So if no objections I'll go ahead with this.

**Comment by Paxxi** [comment]
Wait until tonight, @martijn mentioned a way to repro yesterday so I want to have a look at if we can fix updating the active skin as well

**Comment by Paxxi** [comment]
Okay I tested this and the file causing the issue is Textures.xbt that we keep open. I'm not familiar enough with our texture loading to solve this and poking at it may introduce some unpleasant regressions so lets go with this as is for now.

**Comment by stefansaraev** [comment]
this is quite intrusive change.

http://forum.kodi.tv/showthread.php?tid=269815&pid=2443873#pid2443873

it breaks installing/upgrading addons at least on LibreELEC.

**Comment by popcornmix** [comment]
Also fails on Pi LibreELEC
http://forum.kodi.tv/showthread.php?tid=269814&pid=2445125#pid2445125

**Comment by tamland** [comment]
#10794

**Pull request merged**
