### PR TITLE
[estuary] smartplaylist rules container did not work with a mouse

### PR DESCRIPTION
**Pull request by ronie**
@phil65

### CODE REVIEW

**Comment by phil65** [comment]
interesting... smells like a bug in core though, too?

**Review by phil65 — APPROVED** [review]

**Comment by ronie** [comment]
you tell me :-)

but yeah, this was an odd one to track down.

**Comment by phil65** [comment]
got it. The issue was that the layouts didnt have a width defined. So nothing really which has to get fixed in core i would say.

**Comment by ronie** [comment]
feel free to close if you're going to fix it elsewhere

**Comment by phil65** [comment]
nope, this one makes more sense. :)

**Pull request merged**
