### PR TITLE
FIX Android: On newer kernels neon cpu feature is represented as asimd

### PR DESCRIPTION
**Pull request by Stane1983**
Newer kernels, for example starting from 3.14.33 kernel; commit:
https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/diff/?h=linux-3.14.y&id=42b34c73ae40e3158779a5d47dcd514702804613

More on forum thread: http://forum.kodi.tv/showthread.php?tid=257253

### CODE REVIEW

**Comment by fritsch** [comment]
Thanks much

jenkins build and merge

**Comment by fritsch** [comment]
Windows failure unrelated.

**Comment by MartijnKaijser** [comment]
@Stane1983 can you PR against jarvis branch? Thx

**Comment by Stane1983** [comment]
@MartijnKaijser done with #9011

**Pull request merged**
