### PR TITLE
[windows] use curl instead of wget to download dependencies 

### PR DESCRIPTION
**Pull request by lrusak**
This is intended to help our downloading issues on our windows builders.

Windows has had native curl support for a while now, let's use it instead of our custom wget binary.

We'll see what jenkins says. We may have to test this with clean workspaces. I'm also not sure if we need the `--verbose` switch but I wanted to leave it in to help diagnose any issues.

I also added a commit to fix the warning with `tar.exe`

### CODE REVIEW

**Comment by CrystalP** [comment]
It works (same result as wget) but the output is completely spammed by the --verbose option.
curl seems to have only one verbosity level.

```
< HTTP/1.1 200 OK
< Date: Mon, 08 May 2023 06:04:52 GMT
< Server: Apache/2.4.6 (Springdale Linux) OpenSSL/1.0.2k-fips
< Last-Modified: Sun, 05 Jan 2020 13:51:09 GMT
< ETag: "52164-59b64d5c44d40"
< Accept-Ranges: bytes
< Content-Length: 336228
< Content-Type: application/x-troff-man
<
* schannel: failed to decrypt data, need more data
* schannel: failed to decrypt data, need more data
* schannel: failed to decrypt data, need more data
{ [16384 bytes data]
* schannel: failed to decrypt data, need more data
* schannel: failed to decrypt data, need more data
* schannel: failed to decrypt data, need more data
* schannel: failed to decrypt data, need more data
* schannel: failed to decrypt data, need more data
* schannel: failed to decrypt data, need more data
{ [16384 bytes data]
and on and on for each package...
```

Also, ironically it downloads a curl package :-) future improvement I guess

**Comment by lrusak** [comment]
> It works (same result as wget) but the output is completely spammed by the --verbose option.
> 
> curl seems to have only one verbosity level.
> 
> maybe there is a way to turn off the schannel stuff.
> 
> 

Can you test with the `--include` option instead of `--verbose`. This should show the headers without all the extra crap.

> 
> 
> Also, ironically it downloads a curl package :-) future improvement I guess

Yea, I imagine the downloaded package is libcurl and not the curl binary?



Also, this didn't seem to fix the dns issue but it allowed the downloads to retry so I think it's still an improvement. Not needing to include the wget binary is also an improvement.

**Comment by CrystalP** [comment]
example of output with --include:

```
==================================================
Getting curl-7.67.0-x64-v141-20200105.7z...
Downloading curl-7.67.0-x64-v141-20200105.7z...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1243k  100 1243k    0     0   694k      0  0:00:01  0:00:01 --:--:-- 1111k
Extracting curl-7.67.0-x64-v141-20200105.7z...
Re-arrange old-formed package curl-7.67.0-x64-v141-20200105.7z if necessary...
Copying curl-7.67.0-x64-v141-20200105.7z to build tree...
Post-Cleaning curl-7.67.0-x64-v141-20200105.7z...
Done curl-7.67.0-x64-v141-20200105.7z.

```

No header info there, I don't see the difference with/without --include actually.

So... to keep the additional details of --verbose, I'd suggest to filter the crap out with a grep-like builtin of Windows like so:

`curl --retry 5 --retry-all-errors --retry-connrefused --retry-delay 5 --verbose --location --remote-name "!DOWNLOAD_URL!" 2>&1 | find /V "need more data" | find /V "bytes data]"
`
however it breaks the progress indicator.

Yes I didn't pay attention earlier it's a package for libcurl.

**Comment by CrystalP** [comment]
after a few tries, --include is supposed to be used in addition to --verbose and adds even more information.

variations on the redirection didn't provide more options, all outputs are in the same stream.

**Comment by lrusak** [comment]
> after a few tries, --include is supposed to be used in addition to --verbose and adds even more information.
> 
> 
> 
> variations on the redirection didn't provide more options, all outputs are in the same stream.

Thanks for the testing. I can just drop the verbose flag. We just want the downloads to work.

**Comment by CrystalP** [comment]
or maybe run without --verbose first, and in case of failure run another time with --verbose

**Comment by lrusak** [comment]
squashed the fixup, good to go?

**Review by CrystalP — APPROVED** [review]

**Comment by lrusak** [comment]
jenkins build this please

**Review by thexai — APPROVED** [review]

**Pull request merged**
