### PR TITLE
VideoPlayer: another fix for dropping

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

@Voyager1 that I missed yesterday.

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by mazeyx** [comment]
@FernetMenta is this the fix for the delay in video kicking in, audio starts straight away then you need to wait 5 seconds on a black screen before video shows up via smb share on android tv. affecting the latest nightly kodi-20160412-6167026-master-armeabi-v7a.apk, reverting to the nightly before that fixes it kodi-20160410-25dc4bf-master-armeabi-v7a.apk.

**Comment by FernetMenta** [comment]
I don't think this change is anyhow related to the issue you describe.

**Comment by mazeyx** [comment]
@FernetMenta the problem is resolved now with the latest nightly :)

**Pull request merged**
