### PR TITLE
freebsd: use linux.xml for settings as they should use the same settings

### PR DESCRIPTION
**Pull request by lrusak**
freebsd crashes currently because settings aren't available. Instead of syncing freebsd.xml and linux.xml to be exactly the same I've just dropped freebsd.xml and we can use linux.xml instead.

### CODE REVIEW

**Comment by wsnipex** [comment]
I don't use freebsd, so I'm probably not the right person to review this.
But iirc we had it like this in the past and there might have been a reason to move it to it's own file.

We could also just symlink the file instead of the code changes, if using the same settings xml is deemed ok.

**Comment by lrusak** [comment]
> I don't use freebsd, so I'm probably not the right person to review this.
> But iirc we had it like this in the past and there might have been a reason to move it to it's own file.
> 
> We could also just symlink the file instead of the code changes, if using the same settings xml is deemed ok.

currently there is no freebsd specific settings. So either we can do what's in this PR. Do what you said and just symlink them, or I can just have two duplicate files so they are still separate.

**Comment by wsnipex** [comment]
I'd go with the symlink, that way it's clearer that we currently reuse the linux config
No strong opinion here though, so go with whatever you like best

**Comment by lrusak** [comment]
> I'd go with the symlink, that way it's clearer that we currently reuse the linux config
> No strong opinion here though, so go with whatever you like best

Updated

**Comment by lrusak** [comment]
jenkins build this please

**Review by wsnipex — APPROVED** [review]
ACKed, since nobody else seems to care about freebsd

**Pull request merged**
