### PR TITLE
move the touch command to the codegenerator makefile which runs on all platforms

### PR DESCRIPTION
**Pull request by Memphiz**
this should fix building with autotools/xcode again after #11400

### CODE REVIEW

**Comment by Memphiz** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
while at it, can you also add the override headers for droid? https://github.com/xbmc/xbmc/blob/Krypton/xbmc/cores/AudioEngine/overrides/android/AEDefines.h
Since we don't know the target OS at this stage, I'd simply ifdef them

**Comment by Memphiz** [comment]
@wsnipex i only added the missing file I have no clue at all what about this PR is or what it should do ... if you really wanna drag me into it i can try during the week sometime ... busy ATM

**Comment by wsnipex** [comment]
then just leave as is and be done with it. It shouldn't have been merged like this in the first place, so at least it will build.

**Comment by MartijnKaijser** [comment]
@Memphiz can this be merged?

**Comment by Memphiz** [comment]
Jep

**Pull request merged**
