### PR TITLE
[libdvd] latest versions libdvdcss 1.4.1 libdvdread/libdvdnav 6.0.0

### PR DESCRIPTION
**Pull request by Voyager1**
## Description

This PR bumps the libdvd libraries to latest versions, while keeping our current set of patches. 

## How Has This Been Tested?

This will obviously require a lot of RT testing. Initial testing with some DVDs with and without menus seem to be positive, nothing seems broken at this point.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
thx. Better get this in to get head start on regression testing.

**Comment by Rechi** [comment]
I would prefer a VERSION naming more like we do for FFmpeg and those versions should be tags and not branches in the libdvd repos

**Comment by Voyager1** [comment]
I chose to use branches because that way if something breaks we can easily switch back to the old one.
Changing to tags would require changes in the cmake file I think here: https://github.com/afedchin/xbmc/blob/73538606ad95d8853c2c49ce2ffce1c659f78184/cmake/modules/FindLibDvd.cmake#L71 
I'm not the expert so help is appreciated.

**Comment by Rechi** [comment]
Same is true for tags, just create a new.
The linked cmake file doesn't need changes, github accepts branch name, tag and sha revision at the archive url.

**Comment by Voyager1** [comment]
ok. But I need to use ARCHIVE= instead of VERSION=, correct?

**Comment by Rechi** [comment]
In `tools/depends/target/libdvd*/DVD*-VERSION` just place a tag name after `VERSION=`, it accepts the same things as github does

**Comment by Voyager1** [comment]
@Rechi thanks for the help. Done as per your suggestion. I did also split the cmake from the UWP stuff in all three libraries.

**Review by Rechi — COMMENTED** [review]
Can't say anything about the libdvd changes, but thanks for switching to tags as version.

**Pull request merged**
