### PR TITLE
[depends][windows] Fixup for libbluray version

### PR DESCRIPTION
**Pull request by enen92**
## Description
Unfortunately libbluray for windows was built with the incorrect version for the bd-java files (forgot to bump the version in the cmake patch file). Although the code is correct and the fact we are actually running v.1.3.4 the files are incorrectly named. This can lead to confusion.
Fixed that in https://github.com/xbmc/kodi-deps/pull/26.

image
vs 
image

@fuzzard sorry :/ I know no one likes to be a mirror upload monkey

### CODE REVIEW

**Comment by enen92** [comment]
@fuzzard while being annoyed by the same person (me) probably you can take a quick look into this too? I'd like to have it in alpha3

**Comment by fuzzard** [comment]
Have uploaded. dont think it was worthwhile doing for a purely cosmetic naming issue, but they should be up in the next hour or two.

**Comment by enen92** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Pull request merged**
