### PR TITLE
[gui] merge skin XMLs for MusicPlaylist and VideoPlaylist

### PR DESCRIPTION
**Pull request by phil65**
merges the two playlist windows.
One of those had to deal with mixed content before already anyways, so shouldnt be a big deal for skinners to make this change.
@ronie
@mkortstiege

### CODE REVIEW

**Comment by mkortstiege** [comment]
Fine by me. At some point we might want to merge the actual dupe code of those sections as well though.

**Comment by Razzeee** [comment]
Can you sqash this please? I'll try to have a look on the c++ side of things

**Comment by ronie** [comment]
tested and works ok.

**Comment by akva2** [comment]
@as razzee says it's not entirely trivial. i did try it at some point, holding a reference to a GUIMediaWindow to apply the operations to. iirc i got bitten by protected things and had to friend and at that point i gave up. friend is not an acceptable solution imo.

**Comment by phil65** [comment]
sorry, @as, we didnt want to disturb you. ;)
@Razzeee i will squash when reviewing process is over.

**Comment by phil65** [comment]
squashed and rebased.

**Pull request merged**
