### PR TITLE
Backport: Improve keyboard handling during button mapping

### PR DESCRIPTION
**Pull request by garbear**
Backport of #11645

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Sorry but isn't this a bit to big for a backport? It touches so many things

**Comment by garbear** [comment]
your call. I can drop the first two commits, which will leave the patch at +200/-3, which would be a lot safer as it doesn't touch existing code

**Comment by MartijnKaijser** [comment]
i'd say keep it simple

**Comment by garbear** [comment]
K, it's been updated to a small addition. It shouldn't disturb any existing code.

**Comment by MartijnKaijser** [comment]
Jenkins build this please

**Pull request merged**
