### PR TITLE
Linux: default to OpenGL core profile 3.2

### PR DESCRIPTION
**Pull request by FernetMenta**
Default should be the better option. Users can still set the legacy mode.

### CODE REVIEW

**Comment by wsnipex** [comment]
doesn't that suggest we fully support old GPUs?

**Comment by FernetMenta** [comment]
I don't understand the question. Per default users should get the best working option. That comes with an up-to-data version of OpenGL. Legacy mode still works and can be activated (for now).

**Comment by FernetMenta** [comment]
btw: setting override to a higher version than available on a system should result in highest available version (at least does so on my testsystem, I set to 6.5)
The only reason why someone wnats to use forces legacy mode is for compatibility with outdated visualizations.

**Comment by wsnipex** [comment]
my question was in regard what happens if the hardware doesn't support this version. If GL falls back to the highest version the system supports, all is good.

**Review by wsnipex — APPROVED** [review]

**Comment by FernetMenta** [comment]
closing in favour of https://github.com/xbmc/xbmc/pull/13517

**Pull request closed without merging**
