### PR TITLE
[xbmc] Fix formatting I messed up

### PR DESCRIPTION
**Pull request by Paxxi**

### CODE REVIEW

**Comment by Paxxi** [comment]
@tamland this should be correct but maybe you can double check

**Comment by tamland** [comment]
thanks. did you find out which tool is messing with it?

**Comment by mkortstiege** [comment]
Good to go i guess?

**Comment by Paxxi** [comment]
@tamland looks like it was Araxis Merge that messed with it. Have changed it's whitespace settings so will see how it behaves.

**Pull request merged**
