### PR TITLE
[Fix][bluray] Allow reading the disc's root directory.

### PR DESCRIPTION
**Pull request by ace20022**
@mkortstiege that's needed for the sub re-factor https://github.com/xbmc/xbmc/pull/6703. But since it's a general fix I've opened a extra pr.

### CODE REVIEW

**Comment by ace20022** [comment]
jenkins build this please

**Comment by mkortstiege** [comment]
So this would external subtitles in the iso? Not sure if we should support that. In case i misread, please ignore or enlighten me ;)

**Comment by ace20022** [comment]
no, ext. subs for blu-ray folders.

**Comment by mkortstiege** [comment]
OK, thanks.

**Comment by ace20022** [comment]
jenkins build this please

**Pull request merged**
