### PR TITLE
Android: add colorMode config to .Main activity in AndroidManifest.xml

### LINKED ISSUE #24164: Kodi crashes after getting "HDMI is plugged in: false" event
### Describe the bug
I've tried to find this bug described anywhere for close to 6 months now without any luck, so I am trying to report it here now. Forgive me if this has been posted before. It started on v20 and I am now on v21 Beta 1 to see if it would fix my problem, but alas. The problem actually started when I got a new AVR. Whenever I shut my TV/AVR off for a small amount of time, when I turn it back on, Kodi has crashed in the meanwhile and I have to reopen the app. Not a huge deal, but it means that no updates have been made during this time so I have to start with a Update Library every morning.

The new AVR is a Yamaha RX-A4A and I did not have the same problem with my old AVR, a Denon AVR-X1500H. I've tried fidling with all sorts of combinations of settings on the AVR, Shield and Kodi but to no luck. I've even tried to start with a fresh install of Kodi and redo my whole library to no avail.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Not to crash 

## Actual Behavior

Crashes after a period of time

## Possible Fix

From what I can tell from the debuglog, after turning my TV and AVR off, after around 4-5 minutes Kodi gets a `HDMI is plugged in: false` event which causes it stop the application altogether. I don't fully understand why it gets this message, what role the AVR has to do in it, and why that causes it to stop, but it would be nice if it didn't.

### To Reproduce

1. Have Kodi running on a Shield TV connected to a Yamaha RX-A4A AVR.
2. Turn off AVR for some time.
3. Turn back on and see that Kodi has crashed in the meantime.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/ixecohirib

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 11 (Shield TV Pro (2019) 9.1.1)
 - Kodi version: 20 and 21

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by spdfrk**
colorMode was added to .Splash but missing in .Main causing Kodi to be closed when color mode was switched or due to some TV + AVR setups.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by fritsch — APPROVED** [review]
Thanks very much!

**Review by a1rwulf — APPROVED** [review]
Great work @spdfrk !

**Comment by enen92** [comment]
@spdfrk mind backporting to nexus branch too?
Thanks for the fix

**Comment by matthuisman** [comment]
ive done a backport https://github.com/xbmc/xbmc/pull/24711 if thats OK :) 
I suspect Nexus also wants to re-release soon so trying to save some time

**Comment by fritsch** [comment]
jenkins build this please

**Comment by fritsch** [comment]
Thanks @fuzzard !

**Pull request merged**
