### PR TITLE
[guilib] remove deprecated controls

### PR DESCRIPTION
**Pull request by ronie**
remove some (very) old stuff that's been gathering dust for years...

@phil65 / whoever want to review

### CODE REVIEW

**Comment by ronie** [comment]
jenkins build this please

**Comment by stefansaraev** [comment]
fyi, selectbutton seems to be used by Rapier

**Comment by ronie** [comment]
most skins will still have a default selectbutton defined in defaults.xml, but it's not used for anything.
the last selectbutton was removed from kodi 6 years ago:
http://forum.kodi.tv/showthread.php?tid=74818&pid=545207#pid545207

**Comment by phil65** [comment]
Checkmark and multiselect are no-brainers I think.
At the moment the selectbutton still works when used for viewtype selection for example.
I would still be fine with a removal though, that type of button is not very intuitive.
@gaze01 do you use this in Rapier? Are you fine with removing it?

**Comment by ronie** [comment]
i've checked all repo skins from eden till krypton, none of them is using a selectbutton control :-)

**Comment by phil65** [comment]
Ok :) Then feel free to merge.

**Comment by phil65** [comment]
I think there also was a reference to CheckmarkControl in SettingControl.cpp, did you check that?

**Comment by gade01** [comment]
> @gade01 do you use this in Rapier? Are you fine with removing it?

I think it's an old leftover in Defaults.xml - nothing used directly in the skin. Absolutely fine by me to remove it ;)

**Comment by ronie** [comment]
> I think there also was a reference to CheckmarkControl in SettingControl.cpp, did you check that?

yeah, it's a (confusing) internal name that actually refers to a radiobutton.

**Comment by phil65** [comment]
oh, while you´re at it, perhaps also time to bury the remaining "largeimage" stuff?

**Comment by ronie** [comment]
@phil65 done.

i've also removed the Skin.SetLargeImage builtin.
not sure if there's a usecase for it, but i couldn't think of one.

**Comment by ronie** [comment]
jenkins build this please

**Comment by phil65** [comment]
Yup, I also think it´s safe to remove that builtin.

**Comment by ronie** [comment]
rebased.
jenkins build this please

**Comment by ronie** [comment]
jenkins build this please

**Pull request merged**
