### PR TITLE
[android] use ndk 18

### PR DESCRIPTION
**Pull request by Rechi**
## Description
- fixes all the wrong android readme changes from @hudokkow introduced in #14072
- switch to ndk 18

## How Has This Been Tested?
compiled

## Types of change
- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [x] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Review by denasman2316 — APPROVED** [review]

**Comment by wsnipex** [comment]
what's wrong with using $HOME? /opt, by default, belongs to root and is not writeable for normal users.

**Comment by Rechi** [comment]
`docs/README.Android.md` and `tools/depends/README.md` didn't match, so I fixed it.

**Comment by wsnipex** [comment]
I don't care either way, but if we stick to /opt, you'd have to use sudo for many of the commands, or copy/paste will fail.

**Comment by hudokkow** [comment]
^^ that!

Can you point `all the wrong android readme changes` my commits introduced? Honest question, I swear.

Not to excuse myself with all the **wrong** stuff I wrote but after about 5  months of trying to get people on board testing and proofreading these docs I gave up.

Back to barbecue, beer, pool and having fun.

**Comment by Rechi** [comment]
I already did that more then a month ago, see https://github.com/xbmc/xbmc/pull/14072#discussion_r210707838 and following. That are the ones which are really wrong (toolchain, host, ndk version).

In this PR I additionally adjusted the paths mentioned in `docs/README.Android.md` and `tools/depends/README.md` to match, which I haven't mentioned in any comment in you PR as I noticed it today.

**Comment by hudokkow** [comment]
Thank you!

Please correct if you have the time. I know I don't.

**Comment by Rechi** [comment]
@wsnipex @hudokkow changed `docs/README.Android.md` back to `$HOME/android-tools` instead of `/opt` and adjusted the paths in `tools/depends/README.md`

**Review by wsnipex — APPROVED** [review]
thanks

**Comment by MartijnKaijser** [comment]
runs on arm and arm64

**Comment by AkariDN** [comment]
@Rechi @MartijnKaijser ndk 18 also requires gradle plugin 3.1+ and gradle 4.4+ to build apk (see [known issues](https://android.googlesource.com/platform/ndk/+/ndk-release-r18/CHANGELOG.md)).

I've tested "make apk" with latest plugin 3.2 and gradle 4.6 with following changes:
* tools/android/packaging/build.gradle
```
classpath 'com.android.tools.build:gradle:3.2.0'
gradleVersion = '4.6' //version required
```
* tools/android/packaging/gradle/wrapper/gradle-wrapper.properties
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip
```
* tools/android/packaging/Makefile.in (apk is now located at folder "releaseUnsigned")
```
@cp xbmc/build/outputs/apk/$(BUILD_TYPE_LC)Unsigned/xbmc-$(BUILD_TYPE_LC)Unsigned-unsigned.apk images/kodiapp-debug-$(CPU)-unaligned.apk
```
* Also gradle 4.6 requires SDK Build Tools 28.0.3, so this also needs to be changed in "tools/android/packaging/xbmc/build.gradle.in" and other places
```
buildToolsVersion "28.0.3"
```

**Comment by AkariDN** [comment]
> Did you get any errors?

Yes. I got "No toolchains found..." error in "make apk" on my local machine with archlinux.

> Where have you read that Gradle 4.4 or higher is required?

[Here](https://android.googlesource.com/platform/ndk/+/ndk-release-r18/CHANGELOG.md): This version of the NDK is incompatible with the Android Gradle plugin version 3.0 or older... update your project file to use plugin version 3.1 or newer.
[Here](https://developer.android.com/studio/releases/gradle-plugin#updating-plugin): 3.1.0 (March 2018) This version of the Android plugin requires the following: Gradle 4.4 or higher. Build Tools 27.0.3 or higher.

**Comment by Rechi** [comment]
Which architecture are you building for?
On which system (os, distro, version) are you building?
You followed the steps in the readme exactly?

**Pull request merged**
