### PR TITLE
Drop AsyncFileCopy and some random seemingly unused stuff

### PR DESCRIPTION
**Pull request by Jalle19**
## Description

Just some minor things I've found while trying to pick up coding on Kodi again.
## Motivation and Context

Gotta start somewhere
## How Has This Been Tested?

It seems to build

### CODE REVIEW

**Comment by Jalle19** [comment]
Is it normal for the unit tests to fail when built with Clang? @MartijnKaijser ?

**Comment by Paxxi** [comment]
Unit test fail sometimes on Linux currently. Not the tests themselves but it crashes before results can be written. 

Changes look fine

**Comment by Jalle19** [comment]
jenkins build this please

**Comment by Jalle19** [comment]
@Paxxi good to go? Jenkins seemed happy.

**Comment by Paxxi** [comment]
I think we agreed at de con that only fixes would be merged until we branch so hold of on it for a bit

**Comment by Jalle19** [comment]
I must have missed that part because it's been pointed out twice and I'm always surprised :D

**Comment by MartijnKaijser** [comment]
I'd say more of minor cleaning up is still OK. Just no big refactoring and features

**Comment by tamland** [comment]
Broke build: https://github.com/xbmc/xbmc/blob/master/xbmc/utils/Makefile.in#L4 How did this pass jenkins?

**Comment by MartijnKaijser** [comment]
@tamland jenkins only build cmake nowdays.

**Comment by Jalle19** [comment]
https://imgflip.com/i/1b3gmz

Sorry about that, will take the old/current build system into account the next time.

**Comment by Jalle19** [comment]
s/brake/break/

**Pull request merged**
