### PR TITLE
[cleanup] Remove unnecessary semicolons from headers

### PR DESCRIPTION
**Pull request by thexai**
## Description
Remove unnecessary semicolons from headers.

## Motivation and context
Cleanup and unify the format style.

Made using Notepad++ search and replace:

**Commit 1:** `; };\r\n` ---> `; }\r\n`
**Commit 2:** `) {};\r\n` --> `) {}\r\n`
**Commit 3:** `){};\r\n` ---> `) {}\r\n` and `) { };\r\n` ---> `) {}\r\n`
**Commit 4:** `;};\r\n` ---> `; }\r\n`
**Commit 5:** Jenkins says....

## How has this been tested?
Build with VS 2019

## What is the effect on users?
Nothing

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [X] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ksooo** [comment]
Awesome!

**Comment by thexai** [comment]
Is pending to  squash in one commit

**Review by garbear — APPROVED** [review]
Good Ol' Notepad++ :slightly_smiling_face:

**Review by enen92 — APPROVED** [review]
Merging as this is a good candidate for an infinitive rebase

**Pull request merged**
