### PR TITLE
changed: get rid of PlayListPlayer include in Application.h

### PR DESCRIPTION
**Pull request by notspiff**
before: touch PlayListPlayer.h -> 156 objects rebuilt
after: touch PlayListPlayer.h -> 42 objects rebuilt

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by hudokkow** [comment]
> /Users/Shared/jenkins/workspace/IOS/xbmc/platform/darwin/ios-common/AnnounceReceiver.mm:164:19: error: use of undeclared identifier 'g_playlistPlayer'
    int current = g_playlistPlayer.GetCurrentSong();
                  ^
/Users/Shared/jenkins/workspace/IOS/xbmc/platform/darwin/ios-common/AnnounceReceiver.mm:168:46: error: use of undeclared identifier 'g_playlistPlayer'
      [item setValue:[NSNumber numberWithInt:g_playlistPlayer.GetPlaylist(g_playlistPlayer.GetCurrentPlaylist()).size()] forKey:@"total"];
                                             ^
/Users/Shared/jenkins/workspace/IOS/xbmc/platform/darwin/ios-common/AnnounceReceiver.mm:168:75: error: use of undeclared identifier 'g_playlistPlayer'
      [item setValue:[NSNumber numberWithInt:g_playlistPlayer.GetPlaylist(g_playlistPlayer.GetCurrentPlaylist()).size()] forKey:@"total"];

http://jenkins.kodi.tv/job/IOS/7528/consoleFull

**Comment by notspiff** [comment]
include added

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
