### PR TITLE
[infomanager] add System.HasModalDialog info bool

### PR DESCRIPTION
**Pull request by mkortstiege**
Adds `System.HasModalDialog` info bool. Returns true if there's a modal dialog displayed.

@phil65, please give it a try. /cc @BigNoid, @HitcherUK, @ronie.

### CODE REVIEW

**Comment by ronie** [comment]
very useful stuff!

**Comment by phil65** [comment]
cool :) Thx! Will test it.

**Comment by xhaggi** [comment]
+1

**Comment by phil65** [comment]
Seems to work fine. Thx @mkortstiege .

**Comment by mkortstiege** [comment]
Cool. Objections to shove in?

**Comment by mkortstiege** [comment]
jenkins build and merge

**Pull request merged**
