### PR TITLE
[PVR][Recordings]: re-map showTitle and title for JSON api

### PR DESCRIPTION
**Pull request by flubshi**
## Description

This is one two possible solutions for the swapped fields showTitle and title for PVR recordings (see motivation).
This proposal re-maps the internal stored fields showTitle(episodeName) and title(showTitle) when serializing. As a consequence, the PVR recordings json api returns analogous to the tv shows api: showTitle as the showTitle and the episodeName as title.

Which is the preferred way to go? Feedback is welcome.

For an alternative proposal, see: https://github.com/xbmc/xbmc/pull/16025

## Motivation and Context

When extending the json api here https://github.com/xbmc/xbmc/pull/15869, @ksooo already mentioned to rename showTitle to episodeName. Unfortunately I did not get the whole picture:
There seems to be confusion for the fields title, showTitle, episodename. 

For internal stored tv shows (scraped), there are two fields used:
- showTitle: stores the title of the tv show (e.g. 'Scrubs')
- title: the title of the actual episode (episodename)

For PVR plugins, for recordings the PVR plugins have to use the fields title and episodeName. Internally, the title is assigned to title and episodeName to showTitle. As a consequence, when we decided to expose showTitle to the API, now it returns:
- showTitle: the title of the actual episode (episodename)
- title: stores the title of the tv show (e.g. 'Scrubs')

This means, for PVR recordings the fields showTitle and title are swapped.

## How Has This Been Tested?

Compiled, executed and retrieved recordings via JSON api. It now returns showTitle as showTitle and episodeName as Title.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by DaveTBlake** [comment]
Thanks for looking at this @flubshi, we do need to sort of this inconsistency of PVR having the episode name in the showTitle rather than the title of the TV show.

Can you also bump the patch number of the API version to indicate to JSON consumers that something internal has changed (fixing an issue)

**Comment by flubshi** [comment]
Thanks @DaveTBlake for your feedback. Version is bumped.

Does it mean this PR is favored over https://github.com/xbmc/xbmc/pull/16025 ?

**Comment by ksooo** [comment]
No, did not find the time to deal with this, sorry.

**Comment by DaveTBlake** [comment]
>Does it mean this PR is favored over #16025 ?

By me yes, I prefer this fix. It avoids a schema change, but more importantly the property names and use match elsewhere - "label"/"title" is the episode and "showTitle" is the TV show, PVR should be the same not add yet another property "episodeName". You achieve that here, and you explain in the comment why the serialization is as it is.

**Review by ksooo — CHANGES_REQUESTED** [review]
I'm not sure this goes far enough. It seems that CPVRRecording fills the members m_strTitle and m_strShowTitle which it inherits from CVideoInfoTag with wrong values, compared to what CVideoInfoTag expects. IMO, this should be fixed instead of overwriting what CVIdeoInfoTag::Serialize did.

**Comment by ksooo** [comment]
> PVR should be the same not add yet another property "episodeName". 

 Absolutely, but not only at the JSON level. It should use same semantics as CVideoInfoTag also in the core.

**Comment by flubshi** [comment]
> IMO, this should be fixed instead of overwriting what CVIdeoInfoTag::Serialize did.

What exactly is the right way? Do we have to change it here?
https://github.com/xbmc/xbmc/blob/d68bd9b707a42f777c4a3600c626599934a75bba/xbmc/pvr/recordings/PVRRecording.cpp#L73-L74
Like: 
- If recording.strEpisodeName is empty: m_strTitle  = recording.strTitle;
- else: swap strTitle and showTitle

**Comment by flubshi** [comment]
@ksooo Is this the solution that was in your mind?

**Comment by ksooo** [comment]
Generally the idea is good, but in practice it will cause trouble, unfortunately. The real fix is really much effort, including PVR API change, new GUI labels skin changes, addon changes.

I think this should stay as it is until we fix it to full extend. It is not optimal like it is, but I'm afraid just swapping data will break more stuff than it actually fixes. Very often, programms have no episode name (as not all programms are tv shows with seasons and episodes), but do have a sub title, transporting any additional info for the programm (like "Spielfilm, Deutschland, 2019") . As Kodi PVR core and API currently have no dedicated subtitle field, there are pvr addons filling the field episodename with the sub title. If you make such "misused" episodename field data the the recording title and the title the show title, you will end up in the GUI with subtitles displayed at several places (ListItem.Item), often the actual program title displayed less prominent or not at all. Strictly speaking, this is an addon bug, but otherwise Kodi has no support for important data like sub title (or sometimes called extra data).

So, the right fix is to extend Kodi and addons with proper sub title data support (extend Addon API, add core upport, add GUI engine support, adapt skins). And this is a shitload of work, I'd say.

**Comment by flubshi** [comment]
Thanks for your feedback. I think such a change exceeds my current cpp/kodi skills. And it should anyway accomplished by someone who gets the whole picture. Thus, I have to close this PR.

**Pull request closed without merging**
