### PR TITLE
[guilib] add Container(id).Position for grouplist controls

### PR DESCRIPTION
**Pull request by mkortstiege**
This adds `Container(id).Position` for grouplist controls.

/cc @BigNoid, @HitcherUK, @phil65, @ronie, @vonH

### CODE REVIEW

**Comment by mkortstiege** [comment]
Would be nice if this could be tested.

**Comment by BigNoid** [comment]
Works as intended.

**Comment by HitcherUK** [comment]
Sorry I thought I'd already commented - works great. Thanks.

**Comment by HitcherUK** [comment]
@mkortstiege Ran into a problem when the first item is hidden and the position gets set to 1 instead of 0. No problems when any other items are hidden.

**Pull request merged**
