### PR TITLE
Fix crash during close of kodi if vfs and pvr addons are present.

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description

Error was coming with https://github.com/xbmc/xbmc/pull/12379. During my test there was no PVR addon active and seen it now. This make the m_vfsAddonCache reset short before the manager, then are the related addons, normally closed.

Related to:
```
Thread 1 "kodi.bin" received signal SIGSEGV, Segmentation fault.

#0  __GI___pthread_mutex_lock (mutex=0x8) at ../nptl/pthread_mutex_lock.c:67
#1  0x0000555d3ee0e0ae in (anonymous namespace)::(anonymous namespace)::RecursiveMutex::lock (this=0x8)
    at /home/alwin/Development/kodi/xbmc/threads/platform/pthreads/CriticalSection.h:49
#2  0x0000555d3ee0f1da in (anonymous namespace)::CountingLockable<XbmcThreads::pthreads::RecursiveMutex>::lock (this=0x8)
    at /home/alwin/Development/kodi/xbmc/threads/Lockables.h:60
#3  0x0000555d3ee0f154 in (anonymous namespace)::UniqueLock<CCriticalSection>::UniqueLock (this=0x7ffe8296b2f0, lockable=...)
    at /home/alwin/Development/kodi/xbmc/threads/Lockables.h:127
#4  0x0000555d3ee0e0f1 in CSingleLock::CSingleLock (this=0x7ffe8296b2f0, cs=...)
    at /home/alwin/Development/kodi/xbmc/threads/SingleLock.h:38
#5  0x0000555d3f752245 in (anonymous namespace)::CVFSAddonCache::GetAddonInstances (this=0x0)
    at /home/alwin/Development/kodi/xbmc/addons/VFSEntry.cpp:49
#6  0x0000555d3fcdd531 in (anonymous namespace)::CFileDirectoryFactory::Create (url=..., pItem=0x7ffe8296bb90, strMask=...)
    at /home/alwin/Development/kodi/xbmc/filesystem/FileDirectoryFactory.cpp:88
#7  0x0000555d3fccad15 in (anonymous namespace)::CDirectoryFactory::Create (url=...)
    at /home/alwin/Development/kodi/xbmc/filesystem/DirectoryFactory.cpp:110
#8  0x0000555d3fcc90f1 in (anonymous namespace)::CDirectory::Exists (url=..., bUseCache=true)
    at /home/alwin/Development/kodi/xbmc/filesystem/Directory.cpp:308
#9  0x0000555d3fcc8fa5 in (anonymous namespace)::CDirectory::Exists (strPath=..., bUseCache=true)
    at /home/alwin/Development/kodi/xbmc/filesystem/Directory.cpp:290
#10 0x0000555d3f68dd15 in (anonymous namespace)::CAddonDll::Destroy (this=0x7fcb8801ce50)
    at /home/alwin/Development/kodi/xbmc/addons/binary-addons/AddonDll.cpp:328
#11 0x0000555d3f70f71f in PVR::CPVRClient::Destroy (this=0x7fcb8801ce50) at /home/alwin/Development/kodi/xbmc/addons/PVRClient.cpp:208
#12 0x0000555d3f9c18b3 in PVR::CPVRClients::Unload (this=0x555d428d1570)
    at /home/alwin/Development/kodi/xbmc/pvr/addons/PVRClients.cpp:153
#13 0x0000555d3f9c10d4 in PVR::CPVRClients::~CPVRClients (this=0x555d428d1570, __in_chrg=<optimized out>)
    at /home/alwin/Development/kodi/xbmc/pvr/addons/PVRClients.cpp:59
#14 0x0000555d3f9c113e in PVR::CPVRClients::~CPVRClients (this=0x555d428d1570, __in_chrg=<optimized out>)
    at /home/alwin/Development/kodi/xbmc/pvr/addons/PVRClients.cpp:60
#15 0x0000555d3f9e191a in std::_Sp_counted_ptr<PVR::CPVRClients*, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x555d42b747f0)
    at /usr/include/c++/6/bits/shared_ptr_base.h:372
#16 0x0000555d3edd139c in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x555d42b747f0)
    at /usr/include/c++/6/bits/shared_ptr_base.h:150
#17 0x0000555d3edd108f in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7ffe8296ca08, 
    __in_chrg=<optimized out>) at /usr/include/c++/6/bits/shared_ptr_base.h:662
#18 0x0000555d3f04f384 in std::__shared_ptr<PVR::CPVRClients, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7ffe8296ca00, 
    __in_chrg=<optimized out>) at /usr/include/c++/6/bits/shared_ptr_base.h:928
#19 0x0000555d3f9dea1a in std::__shared_ptr<PVR::CPVRClients, (__gnu_cxx::_Lock_policy)2>::reset (this=0x555d42ba9760)
    at /usr/include/c++/6/bits/shared_ptr_base.h:1025
#20 0x0000555d3f9d780c in PVR::CPVRManager::Deinit (this=0x555d42ba9430) at /home/alwin/Development/kodi/xbmc/pvr/PVRManager.cpp:386
#21 0x0000555d3f825984 in CServiceManager::Deinit (this=0x555d4289d1a0) at /home/alwin/Development/kodi/xbmc/ServiceManager.cpp:155
#22 0x0000555d3f76809a in CApplication::Cleanup (this=0x555d42810bc0) at /home/alwin/Development/kodi/xbmc/Application.cpp:2796
#23 0x0000555d3f84bbd7 in CXBApplicationEx::Destroy (this=0x555d42810bc0) at /home/alwin/Development/kodi/xbmc/XBApplicationEx.cpp:61
#24 0x0000555d3f84bd5b in CXBApplicationEx::Run (this=0x555d42810bc0, playlist=...)
    at /home/alwin/Development/kodi/xbmc/XBApplicationEx.cpp:164
#25 0x0000555d3f3eea0b in XBMC_Run (renderGUI=true, playlist=...) at /home/alwin/Development/kodi/xbmc/platform/xbmc.cpp:88
#26 0x0000555d3edd0dd6 in main (argc=1, argv=0x7ffe8296d138) at /home/alwin/Development/kodi/xbmc/platform/posix/main.cpp:115
```

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by garbear** [comment]
CServiceManager::Deinit() should deinitialilze in the opposite order as initialization. If this was enforced, this error wouldn't have occurred. I started on a PR to fix this but never finished...

**Comment by AlwinEsch** [comment]
I think also the initialization is a bit in wrong flow. PVRManager need normally the BinaryAddonCache but thems becomes created behind. Does only work with the `m_PVRManager->Init();` done on other function.

**Comment by FernetMenta** [comment]
for what reason should PVRmanager need BinaryAddonCache?

**Comment by AlwinEsch** [comment]
CPVRManager create during contruct the CPVRClients and this use BinaryAddonCache during start.

**Comment by ksooo** [comment]
> for what reason should PVRmanager need BinaryAddonCache?

More precisely: Why does CFileDirectoryFactory::Create need CVFSAddonCache::GetAddonInstances while in CPVRClient::Destroy => CAddonDll::Destroy (base class of CPVRClient)?

<pre>
#5  0x0000555d3f752245 in (anonymous namespace)::CVFSAddonCache::GetAddonInstances (this=0x0)
    at /home/alwin/Development/kodi/xbmc/addons/VFSEntry.cpp:49
#6  0x0000555d3fcdd531 in (anonymous namespace)::CFileDirectoryFactory::Create (url=..., pItem=0x7ffe8296bb90, strMask=...)
    at /home/alwin/Development/kodi/xbmc/filesystem/FileDirectoryFactory.cpp:88
</pre>

**Comment by AlwinEsch** [comment]
It's again a bit a chicken and egg problem. CPVRClients need BinaryAddonCache and BinaryAddonCache need CPVRClient who needs then CPVRClients.

Hope to becomes them fixed with remove of CBinaryAddonCache, thats why also the CVFSAddonCache is added. This type is the only one who not becomes handled from a own manager.

**Comment by FernetMenta** [comment]
PVRManager does not construct the addons anymore. I changed this, didn't I.

**Comment by AlwinEsch** [comment]
Has found my fault reason, there was a check to prevent the use of Binary addon cache: https://github.com/xbmc/xbmc/blob/master/xbmc/filesystem/FileDirectoryFactory.cpp#L85

Also a bit hacky this way, but I correct them there to use the new one.

With PVRManager you are right, is not done from them itself.

**Comment by AlwinEsch** [comment]
Ah forget it, the IsBinaryAddonCacheUp is only be usable during start and after end of Deinit.

**Comment by AlwinEsch** [comment]
@ksooo it use it since the the VFS addon system was added. Always if something in Kodi checks for a directory becomes also checked over a present VFS addon.

So far, that was never noticeable since in the addon system during the end no items were used.

**Comment by AlwinEsch** [comment]
I check here again after rebase and bring it in now to have the fault fixed. There comes in future a bigger improvement of the parts like them.

How the VFS with his addons are currently handled does I'm not like.

**Comment by AlwinEsch** [comment]
Have checked must also the change for audio decoder in (https://github.com/xbmc/xbmc/pull/12336) where it becomes removed from binary addon cache.

The audio decoder addon simulates a VFS access who becomes also problematic if binary addon cache becomes destructed before PVR (there on request it becomes complete removed from this cache).

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by itsmejerry04** [comment]
Struggling with Live TV as I keep getting the PVR manager is starting up: 0%.  I have installed NextPVR and it works fine on the PC but it doesn't work at all.  I have restarted Kodi and the PC but still not working.

**Comment by MartijnKaijser** [comment]
@itsmejerry04 don't comment on a random PR but ask on the forum

**Pull request merged**
