### PR TITLE
[RetroPlayer] rename GBM related buffers/pools/renderers to DMA

### PR DESCRIPTION
**Pull request by lrusak**
Just a simple name change. `GBM` doesn't represent the full capability of code path. In reality the buffer type doesn't matter as long as it is a (direct-memory-access) `DMA` type.

I thought about naming this `PRIME` which refers to buffer sharing but I thought `DMA` is more fitting.

I'm doing this so in the future once we figure out #17517 we can have wayland use this render method with #17523 and some other cmake changes. I just wanted to get this trivial name change out of the way.

### CODE REVIEW

**Comment by zag2me** [comment]
Great! I always thought GBM sounded like it had something to do with 🗡 games 🗡

**Comment by lrusak** [comment]
jenkins build this please

**Comment by garbear** [comment]
+1 on generalizing GBM to DMA.

I viewed the commit, hit ctrl+f, typed "direct", and got no results. I die in agony when I see an unfamiliar acronym in the source code, and the entire internet, much less the codebase, is no help to me in decoding it.

The three words "direct memory access" in a comment preceding the most hierarchically prominent use of the acronym would be welcome, bonus points for >= 4 words of documentation.

**Comment by lrusak** [comment]
Documentation added!

**Comment by lrusak** [comment]
Tvos build failure unrelated

**Pull request merged**
