### PR TITLE
Change xbmc.org to kodi.tv

### PR DESCRIPTION
**Pull request by kekePower**
A minor change, but why not.

### CODE REVIEW

**Comment by stefansaraev** [comment]
this should go first to master branch :)

**Comment by kekePower** [comment]
Do I make a new pull request on the master or is this request enough?

**Comment by stefansaraev** [comment]
please make new. release managers will decide if this one will be merged to jarvis

**Comment by kekePower** [comment]
Wrong tree. Will create new pull on master.

**Pull request closed without merging**
