### PR TITLE
RetroPlayer: Fix black screen when playing games

### PR DESCRIPTION
**Pull request by garbear**
This contains two fixes for two separate bugs causing a black screen during gameplay. It also contains some minor improvements that shouldn't affect playback.

### CODE REVIEW

**Comment by garbear** [comment]
jenkins build this please

**Comment by garbear** [comment]
jenkins build and merge

**Comment by garbear** [comment]
Windows failed due to an IO error.

**Comment by thejims** [comment]
After this was added whenever I launch games via IARL I only get a blank/black screen.  Works fine in prior releases.
Crash logs from when this occurs:
http://sprunge.us/NTjX

**Comment by garbear** [comment]
Fixed by #12546

**Pull request merged**
