### PR TITLE
Fix compilation issues for Android on OS X. Fixing errors around pick…

### PR DESCRIPTION
**Pull request by yuvalt**
…ing the wrong "locale.h" and "log.h".

### CODE REVIEW

**Comment by yuvalt** [comment]
Yes, exactly. It picked wrong headers and just failed compiling.

**Comment by bmc08gt** [comment]
@bmc08gt subbing myself in, will be compiling on OSX for android shortly

**Comment by Velek** [comment]
Interested in looking into this.  Since I have Java 1.7 installed on my system right now, is there a way to install the 1.6 jdk to a different path?  I tried to install it to the recommended "android-dev" volume, but it wants there to be an OS on the destination volume.

**Comment by MartijnKaijser** [comment]
Changes are outdated compared to current master

**Pull request closed without merging**
