### PR TITLE
[cmake] Fix crosscompiling for Raspberry Pi

### PR DESCRIPTION
**Pull request by fetzerch**
Some smaller fixes to get crosscompiling working again.

@wsnipex: With this changes the cmake run looks good for the rbpi. But compilation fails when building MMALCodec.cpp. Is MMAL really an optional dependency on the pi? Guess it should be a required one. Is MMAL used on other platforms?

### CODE REVIEW

**Comment by Razzeee** [comment]
@popcornmix

**Comment by popcornmix** [comment]
I'd say MMAL is required for Pi (no one would want to build without it).
It is not used on other platforms.

**Comment by wsnipex** [comment]
I seem to remember that MMAL was optional once. Anyway, its required in autotools now as well.

**Comment by fetzerch** [comment]
@wsnipex, @popcornmix: Thanks, build is working fine now :). I couldn't test the built executable though.

**Comment by fetzerch** [comment]
@popcornmix: Fixed one build error on the Raspberry Pi 2 and the build is working there now as well. Could you try it again on your side? (yuv2rgb.neon.S was not built since the platform is not 'arm' but 'arm-linux-gnueabihf')

I changed the README.raspberrypi to default to Raspberry Pi 2. Is that fine?
@wsnipex: Couldn't find any readme changes in the old branches. But I hope it's fine now.

**Pull request merged**
