### PR TITLE
[FFmpegImage] - fixed missing transparency of images with indexed colortables

### PR DESCRIPTION
**Pull request by Memphiz**
what the title says ...

### CODE REVIEW

**Comment by Memphiz** [comment]
@fritsch one ack of you and i would merge this straight away ( i did a compile and function test a min ago).

**Comment by Memphiz** [comment]
mhh ops - one superfluous bracket in there ... *grr*

**Comment by fritsch** [comment]
What do you think, would it be smarter to the macro ffmpeg gives us at hand?

via: libavutil/pixdesc.c

#define pixdesc_has_alpha(pixdesc) \
    ((pixdesc)->nb_components == 2 || (pixdesc)->nb_components == 4 || (pixdesc)->flags & AV_PIX_FMT_FLAG_PAL)

**Comment by Memphiz** [comment]
IMO ffmpeg should use this internally and we as the API caller shouldn't even care.

**Comment by fritsch** [comment]
It's not ffmpeg's fault. It's ours - we need to detect alpha as that's our communication with Texture.cpp

**Comment by Memphiz** [comment]
if that macro you pointed out means ALPHA is present - shouldn't ffmpeg add the needed alpha flag for us then?

**Comment by Memphiz** [comment]
Our API is the pixel format description and not the macro no?

**Comment by Memphiz** [comment]
just verified - with ffmpeg from our depends i need this patch - else i get opaque background in the thumb...

**Comment by fritsch** [comment]
@Memphiz the alpha flag only means: it has a dedicated alpha channel, which an indexed image obviously has not ... 

Patch is fine.

**Comment by Memphiz** [comment]
Ok - but if it works for you with ffmpeg master - what did they change? ^^

**Comment by fritsch** [comment]
@Memphiz they did not change anything - I did not properly rebuild without flag. all fine.

**Pull request merged**
