### PR TITLE
Fix inversion of export library dialogs, fix #16317, fix #16358

### LINKED ISSUE #16358: Path substition for passwords.xml on network share not working
### Describe the bug
Here is a clear and concise description of what the problem is:

Path substitution in general appears to be mostly fixed thanks to #15971 but using advancedsettings.xml for path substitution of passwords.xml located on a network share causes a crash at startup.  The crash occurs even when passwords.xml contains no passwords.
````
<passwords>
</passwords>
````
Path substitution of passwords.xml within the local file system, as opposed to a network location, appears to work correctly.  The network location of my passwords.xml file does _**not**_ itself require a password as it is using NFS.  This previously worked (did not crash) in v17.6.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Path substitution of passwords.xml located on a network share should work like any other path substitution.

## Actual Behavior

Kodi crashes at startup when path substitution of passwords.xml points to a network share.

### To Reproduce

1. Add to your advancedsettings.xml the following:
````
<substitute>
  <from>special://profile/passwords.xml</from>
  <to>nfs://YOUR_SERVER/YOUR_PATH/userdata/passwords.xml</to>
</substitute>
````
2. Launch Kodi

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/faripaxehu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS 10.13.6
 - Kodi version: 18.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by MilhouseVH**
Seems to have been inverted by https://github.com/xbmc/xbmc/pull/7800/files#diff-cc6ead21ea518ad3638e13347df6cad4L1597

http://forum.kodi.tv/showthread.php?tid=243558

Closes http://trac.kodi.tv/ticket/16317, http://trac.kodi.tv/ticket/16358

### CODE REVIEW

**Comment by MilhouseVH** [comment]
This isn't the right fix, investigating further...

**Comment by MilhouseVH** [comment]
This should be the correct fix for the singleFile inversion.

Added a second commit that clears the cancelled flag before the dialog is opened otherwise a cancelled YesNo dialog will continually be seen as cancelled even if a Yes or No button is clicked.

**Comment by MilhouseVH** [comment]
Squashed an update to first commit after testing with JSON.

**Comment by MilhouseVH** [comment]
Now tested successfully exporting library to single or separate files via GUI, JSON and `exportlibrary()` builtin.

**Comment by mkortstiege** [comment]
@Paxxi mind having a look. I think you've and someone else changed it around the last few merge windows ;)

**Comment by Paxxi** [comment]
I tried exporting without this and found no odd behaviour, need to try this and read through the code before commenting. Will make some time for it before next window, hopefully tomorrow

**Comment by MilhouseVH** [comment]
@paxxi: I just tried a build of master (07f691e6ddccff40baff2c4b96dc9d907f761bbb) on Ubuntu and the export library dialog remains broken as per this PR... are you sure you're building master and not Isengard (this bug is not in the Isengard/15.2 branch)?

1) The buttons are reversed - "Separate" prompts for a directory, "Single file" prompts with the thumbnails/fanart dialog (should be the other way around)

​2) Click Export... then cancel the dialog (doesn't matter which dialog: Separate/Single file, Thumbnails/Fanart, or the Actors dialog - they're all instances of the same Yes/No dialog) then click on Export... again. Click on either button and nothing happens, the dialog just closes as  the Yes/No dialog is now forever considered "cancelled" no matter what button is clicked, as the `m_bCanceled` flag is never cleared before the dialog is shown.

**Comment by Paxxi** [comment]
fix looks good, thanks for the explanation @MilhouseVH

**Pull request merged**
