### PR TITLE
[PVR, json-rpc] Fix Input.Select for PVR fullscreen windows

### PR DESCRIPTION
**Pull request by ksooo**
Jarvis backport for #8533

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by ksooo** [comment]
Jenkins error (WIN32) is unrelated to this PR.

> failed to compile /xbmc/system/players/dvdplayer/avcodec-56.dll

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
Fix confirmed team-internally.

**Pull request merged**
