### PR TITLE
[depends/cmake-native] - bump native cmake to 3.6.2

### PR DESCRIPTION
**Pull request by Memphiz**
At devcon i realised the cmake in our depends was to old to test the xcode generator.

Bump to 3.6.2

@fetzerch or @hudokkow - your call

### CODE REVIEW

**Comment by Memphiz** [comment]
tarball uploaded to mirrors ...

**Comment by fetzerch** [comment]
Fine by me, we use 3.6.2 on the windows build slave already, so that would make it consistent.
If there are issues with the Xcode generator with older versions, we should can also bump the minimum version to 3.6 (https://github.com/xbmc/xbmc/pull/10396/commits/45d5c53662ff57634109743281cbebbe555e749f).

jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by hudokkow** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
Usual segfault in osx testing ...

**Pull request merged**
