### PR TITLE
Add fmt to dependencies list in Makefile to fix CMake error

### PR DESCRIPTION
**Pull request by sryze**
## Description
Added `fmt` to the list of dependencies so that cmake doesn't fail when [generating an Xcode project](https://github.com/xbmc/xbmc/blob/master/docs/README.macOS.md#61-build-with-xcode).

## Motivation and context

fmt is one of the required dependencies listed in CMakeLists.txt but is not built by default because it has not been added to the `DEPENDS` variable in `tools/depends/target/Makefile`. So if you try to run the cmake command mentioned at https://github.com/xbmc/xbmc/blob/master/docs/README.macOS.md#61-build-with-xcode it will fail to find the Fmt package.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
This is incorrect now. For apple platforms it uses the FindFMT.cmake file to build fmt. There should a a fmt target in the Xcode project. 
If it's missing, or not being executed, the fix needs to be done in the find module

**Comment by fuzzard** [comment]
If you need some help with building, ping my username on the forums, and happy to work with you to resolve any issue

**Comment by fuzzard** [comment]
@sryze you may be interested in testing https://github.com/xbmc/xbmc/pull/22076

It fixes the issue when no pre-existing fmt lib is in depends paths, to correctly trigger a force build of fmt.

**Comment by sryze** [comment]
@fuzzard Yes, with that patch fmt is successfully found in xbmc-depends by CMake. Thanks!

**Pull request closed without merging**
