### PR TITLE
[setting] hunt missing setting id constants

### PR DESCRIPTION
**Pull request by xhaggi**
@Montellese as you pointed out here are the missing setting id constants ;)

### CODE REVIEW

**Comment by Montellese** [comment]
Thanks. jenkins build and merge

**Comment by xhaggi** [comment]
Sorry forgot to rename the eventlog settings ids. I've pushed a separate commit for that.

**Comment by Montellese** [comment]
Aborted the previous jenkins build. jenkins build and merge

**Comment by xhaggi** [comment]
Thanks :+1:

**Comment by xhaggi** [comment]
build errors are unrelated.

**Pull request merged**
