### PR TITLE
xbmc: cppcheck performance fixes

### PR DESCRIPTION
**Pull request by tobbi**
** THIS IS THE LAST ONE FOR NOW**

## Description

This fixes a few performance issues found with 
```
% cppcheck --enable=performance xbmc/ --check-level=exhaustive --force
```

There is one issue I didn't fix:
```
xbmc/TextureCache.cpp:160:29: performance: Searching before insertion is not necessary. [stlFindInsert]
    m_processinglist.insert(url);
```
because in the if statement that we use to check if the list contains the item, we perform a couple more initialization steps.

## Motivation and context
This fixes issues reported by cppcheck.

## How has this been tested?
I compiled the code to see if I made mistakes while fixing cppcheck issues. The changes themselves should be pretty self-explanatory.

## What is the effect on users?
Eh, changes should be barely noticeable. 

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [X] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by neo1973** [comment]
For this PR and the previous ones, are you planing on addressing the review comments and applying the Jenkins format changes?

**Comment by tobbi** [comment]
> For this PR and the previous ones, are you planing on addressing the review comments and applying the Jenkins format changes?

Yes, I am, I just haven't gotten to it yet.

**Comment by tobbi** [comment]
The last commit seems to have fixed the formatting issues.

Furthermore, most of the changes got superseded by the ones on master, so for this PR, only the one above remains.

**Comment by tobbi** [comment]
> I've made some formatting changes to meet the current code style. The diffs are available in the following links:
> 
>     * [PR25537-0001-23cfad369f-xbmc-base-cppcheck-performance-fix.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/31240/artifact/PR25537-0001-23cfad369f-xbmc-base-cppcheck-performance-fix.diff)
> 
>     * [PR25537.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/31240/artifact/PR25537.diff)
> 
> 
> For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

I wonder if jenkins was just slow because I think I've added the formatting patches in the last commit (yet the message appeared after it).

**Comment by tobbi** [comment]
My time is limited these days (I'm writing a master's thesis at the moment). Nonetheless, I'll try to rebase the other ones as soon as my time permits (maybe a few every few days).

**Review by the-black-eagle — COMMENTED** [review]
Shouldn't that be just `strPath.resize(last_sep);`

**Comment by tobbi** [comment]
> Shouldn't that be just `strPath.resize(last_sep);`

Yes, you're right. i'm on it. Seems like I never compiled the changes.

**Review by garbear — APPROVED** [review]

**Comment by ksooo** [comment]
@tobbi please fix the compile errors.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by tobbi** [comment]
> @tobbi please fix the compile errors.

I think the jenkins build is outdated so all should be well with the build you just started.

**Review by ksooo — APPROVED** [review]

**Pull request merged**
