### PR TITLE
DCADEC: Display real stream information - don't hide what we know

### PR DESCRIPTION
**Pull request by fritsch**
Don't hide stream information depending on user setting concerning playback. It makes no sense to display DTS or 5.1 channels depending on user's output settings.

### CODE REVIEW

**Comment by hudokkow** [comment]
Aren't you still on vacation? :P

**Comment by fritsch** [comment]
I just returned and as I did not have to argue for 10 days :-) I was happy to find @FernetMenta that will speed up to get back into business

**Comment by fritsch** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by popcornmix** [comment]
I assume this means we are using external libdcadec for demuxing, but may be using ffmpeg's dcadec for decoding. Are we happy this is valid? I just wonder if it's possible the extradata of the two libraries could be formatted differently or the framing of decoding packets could be done differently.

Most likely it's not, but I'd feel better if someone could say "it will all be fine".

**Comment by FernetMenta** [comment]
demuxing and parsing (split of extradata) is not done by decoder. find_stream_info uses decoders for extraction of parameters not seen by demuxer.

**Comment by fritsch** [comment]
@wsnipex rebased - ready to go.

**Comment by fritsch** [comment]
@FernetMenta: Fine with you? Or should I try to add some more arguments why this setting is useful?

**Comment by FernetMenta** [comment]
Regarding the setting I still do think it is wrong to align all features to the weakest devices. I doubt there are many systems running OSX, Linux, or Windows that can't cope with it. At least it should default to true on those. There is no one-fits-all. For this reason we maintain different settings for the various platforms.

**Comment by fritsch** [comment]
Yes, that is right. A follow up PR can set it to true in general and platforms that know they are too slow to use it can overwrite that with their platform xml. Is that possible btw.? To overrule global settings with the platform specific one?

**Comment by popcornmix** [comment]
Yes, platform specific settings can override default settings:
Set default to true in settings.xml
Include the same setting in rbp.xml and imx6.xml which sets default to false.
Include the same setting in rbp2.xml and imx6.xml which sets default to true.

There's still the issue of low end Android or Atom devices, but that is speculative - I don't think anyone has confirmed which of these devices fail to keep up. I'm pretty sure Atom will be fine and almost all Android devices will be fine (Pi2 is fine, and most Android devices are comparable).

**Comment by fritsch** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
good to go?

**Comment by fritsch** [comment]
Yes.

**Pull request merged**
