### PR TITLE
Add PT-BR keyboard layout

### PR DESCRIPTION
**Pull request by luizoti**
I do not know if there is any reason for not having a PT-BR layout, however this layout works, and it has the most common keys in Brazil, I believe I did not notice the lack of any key.

## Description

Add PT-BR layout.

## Motivation and context

The lack of this keyboard makes its use more difficult.

## How has this been tested?

It was tested by me, on kodi 17, 18 and 19 (not that there should be a big difference)

## What is the effect on users?

More practical use of the system.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
This should probably just be added to the portuguese.xml file

**Comment by luizoti** [comment]
Two layouts in one file?, because portuguese.xml is PT-PT.

**Comment by lrusak** [comment]
> Two layouts in one file?, because portuguese.xml is PT-PT.

Yes two layouts in one file. Many of the languages have more than one layout present.

**Comment by luizoti** [comment]
haa, ok, não sabia dessa possibilidade, boletim eu abri o arquivo portuguese.xml, mas ele possui apenas pt-pt então nem pensamento nisso.

**Pull request closed without merging**
