### PR TITLE
[win32] Fixed libcurl initialization when the env variable OPENSSL_CO…

### PR DESCRIPTION
**Pull request by afedchin**
…NF points to existing openssl.conf file.

this fixes http://trac.kodi.tv/ticket/16048

ping @Paxxi @FernetMenta

### CODE REVIEW

**Comment by Paxxi** [comment]
:+1: a better version of what I was thinking.

**Comment by afedchin** [comment]
for quick fix yes, but the problem is more deeply. 
here is a callstack before exception occurs:
```
>	Kodi.exe!dll_fgets(char * pszString=0x06ea5400, int num=511, _iobuf * stream=0x74cae060) Line 1115	C++
 	libeay32.dll!0f372ed4()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for libeay32.dll]	
 	libeay32.dll!0f3719db()	Unknown
 	libeay32.dll!0f3c638f()	Unknown
 	libeay32.dll!0f3c6250()	Unknown
 	libeay32.dll!0f3c70f7()	Unknown
 	libcurl.dll!0ff74b1f()	Unknown
 	Kodi.exe!XCURL::DllLibCurl::global_init(long p1=3) Line 63	C++
 	Kodi.exe!XCURL::DllLibCurlGlobal::Load() Line 84	C++
 	Kodi.exe!CApplication::Initialize() Line 1140	C++
 	Kodi.exe!WinMain(HINSTANCE__ * hInst=0x00af0000, HINSTANCE__ * __formal=0x00000000, char * commandLine=0x00437b14, int __formal=10) Line 205	C++
```

I've tried to catch which methods from our emu_msvcrt.cpp is used by libeay32 and only one method is used before dll_fgets. it is dll_getenv

I've faced with the same problem if I use this code to read file (from binary addon)
```
  std::ifstream t(fullPath);
  std::string str((std::istreambuf_iterator<char>(t)), std::istreambuf_iterator<char>());
```
If I replace this with fopen+fread, all works fine.

I'm not expert of cpp but i think this should be fixed in the root of problem. May be someone who knows cpp beter can help us with this. @Karlson2k what do you think about this?

**Comment by Paxxi** [comment]
As we're so late in the release cycle we shouldn't mess with the dll hooks. We should merge this fix and ill stick it on my todolist to research a proper fix.

**Comment by afedchin** [comment]
I agree, so I prepared this for the quick fix

**Comment by mooseforgoose** [comment]
is there a simple way to fix because im not very tech savvy

**Comment by afedchin** [comment]
jenkins build this please

**Comment by afedchin** [comment]
if no objections. i'll merge this today's evening

**Comment by Karlson2k** [comment]
@afedchin A little bit too late, but Win32 have a lot of copies on Environment variables.
First one is global variables, usually not modifiable by user processes.
Second one is process's copy of variables. Accessible by through `SetEnvironmentVariable()` and `GetEnvironmentVariable()`. (BTW always use wide-version, because ANSI-versions call wide-versions internally, after transcoding)
Third one and more - are CTR's copies of process's copy. Each CTR version (static and each dll) create an its own copy during initialization. Those copies are accessible by `getenv()` and `putenv()`.
If you modify process's copy by `SetEnvironmentVariable()` **after** CTR initialization then CTR's copy of variables will not be modified. (I guess that `libcurl` use `getenv()` to read variables.)
To deal with all this mess, we have https://github.com/xbmc/xbmc/blob/master/xbmc/utils/Environment.h
Use [CEnvironment::unsetenv()](https://github.com/xbmc/xbmc/blob/master/xbmc/utils/Environment.cpp#L234) to properly unset variables.

**Comment by afedchin** [comment]
thanks you. I didn't know about different copies for each dll. will prepare better fix asap

**Pull request merged**
