### PR TITLE
[Backport][Video] Fix Episode NFO parsing error (introduced in #24565).

### LINKED ISSUE #25224: Multi-episode video & NFO files not being properly displayed (KODI 21.0 Omega) when using local information
### Describe the bug
Here is a clear and concise description of what the problem is:

When ingesting a multi-episode video file with single/shared NFO & single/shared thumb (e.g. "Star Trek:  The Next Generation 1x01 & 1x02 - Encounter at Farpoint", both episodes show up in the episode list as separate entries, but only the information for the first episode is displayed - the second episode is listed only as an episode number with no other information (no name, no episode description, no actor or other information), however the shared thumb is displayed.  Previous versions showed each episode as a discreet entry with separate descriptions/information and a shared thumb.

I've tried varying the naming convention used, including using the examples suggested in the Wiki without success.

I have not tested this using Kodi's "native" scraping capability - only via the option for using locally stored information with both newly created NFO files and older NFO files that were known to produce the desired results with previous versions of Kodi.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expected behavior is that both episodes would be displayed as discreet episodes with their unique description, actor, etc. information while sharing the same thumb.

## Actual Behavior

Actual behavior is per description provided in "Describe the bug" above.

## Possible Fix

I can't offer any useful suggestions for how to 'fix' this (if it is, indeed, unintended behavior), but only ask that the behavior of previous versions be restored, or the wiki be updated to reflect the new behavior and the proper NFO syntax for correct multi-episode display within Kodi.

### To Reproduce

1.  Ensure Kodi is set to scrape show/episode data via local information (this is untested with Kodi's built-in/plug-in media scrapers)
2.  Start with a multi-episode video file that is named following the suggested naming conventions in the wiki
3.  Create the associated NFO and thumb files by hand or via whatever tool/scraper you prefer that creates proper Kodi formatted NFO files
4.  Ingest the multi-episode file in Kodi either via the "Update Library" feature, the "Scan for new content" feature, or the episode information refresh feature.
5.  If your results are the same as mine, you will see what is shown in the attached JPG files

### Debuglog

The debuglog can be found here:

(used episode information refresh for the log)

https://pastebin.com/wh4CLn7b

### Screenshots 
Here are some links or screenshots to help explain the problem:

Screenshots attached showing how episodes are displayed

kodi_KD1SmNacYx

kodi_Ulc9vDrlYS

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Filenames used were as follows:

TNG 1x01 & 1x02 - Encounter at Farpoint.mkv
TNG 1x01 & 1x02 - Encounter at Farpoint.nfo
TNG 1x01 & 1x02 - Encounter at Farpoint-thumb.jpg

NFO file is here:

https://pastebin.com/wTPFq8hD

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:  Windows 11 23H2
 - Kodi version:  21.0 Omega

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by 78andyp**
## Description

Backport of #25198 

As reported in the forum https://forum.kodi.tv/showthread.php?tid=377480.

Error introduced in https://github.com/xbmc/xbmc/pull/24565 (I cannot reproduce the problem I was attempting to fix).

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CastagnaIT** [comment]
on backport PR's please use title same of original PR otherwise is not understandable on git history, the best if you add also [backport] prefix

**Comment by ksooo** [comment]
I prefer [Omega] because this makes clear a) that it is a backport and b) to which branch.  But we have no hard guideline for this.

**Comment by CastagnaIT** [comment]
@ksooo its fine, anyway my main point was something like "[xy] #3838" not so good to have in branch

**Comment by KarellenX** [comment]
Could someone kick off a Win64 test build for this. Thanks.

**Review by neo1973 — APPROVED** [review]

**Pull request merged**
