### PR TITLE
[win32] A set of DX fixes for windows.

### PR DESCRIPTION
**Pull request by afedchin**
Urgent fixes:
- Fixed rendering video after resize
- Fixed drops for PS rendering.

@da-anda @Voyager1

### CODE REVIEW

**Comment by afedchin** [comment]
jenkins build this please

**Comment by afedchin** [comment]
jenkins build this please

**Comment by Voyager1** [comment]
looks good, I tested briefly and confirm the PS rendering is fixed, as well as the resize issue. Thanks!!

**Comment by da-anda** [comment]
@afedchin as you pinged me, what should I test on my legacy hardware? And is there a test build up already somewhere? If not, I'll trigger one as I don't have the time to update my build env VM to VS2015 atm.

**Comment by da-anda** [comment]
I just tested and couldn't reproduce the cropping issue anymore, so seems to be fixed.

**Comment by afedchin** [comment]
thanks.

**Comment by NedScott** [comment]
Do you want this documented on the wiki for advancedsettings.xml?

**Pull request merged**
