### PR TITLE
[guilib] add static_assert beside type trait to produce readable erro…

### PR DESCRIPTION
**Pull request by xhaggi**
@Montellese as you suggested in #11869

### CODE REVIEW

**Comment by Montellese** [comment]
Thanks. Have you tried it out with out without the `static_assert()` assert to see the difference?

**Comment by xhaggi** [comment]
I'm on Xcode and there is no difference.

**Comment by xhaggi** [comment]
> No matching member function for call to 'GetWindow'

and some details:

> /xbmc/guilib/GUIWindowManager.h:154:48: Candidate template ignored: disabled by 'enable_if' [with T = CSettings]

**Comment by xhaggi** [comment]
@Montellese good to go in?

**Comment by Montellese** [comment]
Ah you're right I didn't consider the `enable_if`. In that case the `static_assert` isn't really necessary. Sorry about the noise :-/

**Comment by xhaggi** [comment]
Np will close the PR

**Pull request closed without merging**
