### PR TITLE
[droid] Don't show option "sync playback to display" as it's not supp…

### PR DESCRIPTION
**Pull request by MartijnKaijser**
…orted on Android

### CODE REVIEW

**Comment by FernetMenta** [comment]
thanks, saves a lot of questions from users :)

**Comment by MartijnKaijser** [comment]
prepare for "why isn't this setting on android while my other ..... has it" :)

**Comment by koying** [comment]
@FernetMenta What's the result of enabling the setting for android currently? Just nothing?

**Comment by fritsch** [comment]
The Sync comes up as NULL and it falls back to current host counter.

**Comment by koying** [comment]
OK. So, we don't need to care about people having enabled the option and
not being able to deactivate it.
Might be cleaner to force it to false, but I'll leave it to you to decide.

Le mar. 17 nov. 2015 21:53, Rainer Hochecker <notifications@github.com> a
écrit :

**Comment by MartijnKaijser** [comment]
how can we force to disable if it's enabled? Should be some update mechanism iirc

**Comment by MartijnKaijser** [comment]
@Montellese had a good holiday? Any pointers how this is done now days?

**Comment by Montellese** [comment]
Yeah you need to define an update handler which sets the setting's value to false for droid. Look for `<update type="change">` in `settings.xml` and you should find other examples.

**Comment by MartijnKaijser** [comment]
sadly not really an example that would help changing it in current installs from true to false

**Pull request merged**
