### PR TITLE
[cleanup] Remove check for language (codes) from language addons.

### PR DESCRIPTION
**Pull request by ace20022**
This was quite useless before the language addons were introduced, but now it's really useless with only one pre-installed addon.

I'm not sure about the second commit, it might be useful to check load a language.
@Montellese for review.

### CODE REVIEW

**Comment by Montellese** [comment]
Yeah I was thinking about removing these too but didn't want to change anything not really necessary in that PR.

**Comment by Montellese** [comment]
jenkins build and merge

**Comment by mkortstiege** [comment]
late +1 ;)

**Comment by ace20022** [comment]
jenkins build this please

**Comment by ace20022** [comment]
just fyi I'm working on user defined lang integration for non iso codes that got lost like Portoguese (Brazil) <-> ptbr.

**Pull request merged**
