### PR TITLE
FIX: [GLES;texture] if we have nothing to draw, don't try

### PR DESCRIPTION
**Pull request by koying**
Android O (emulator?) crashes on glDrawElements with zero elements.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@peak3d for review

**Comment by peak3d** [comment]
looks reasonable - go from my side

**Review by peak3d — APPROVED** [review]

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
