### PR TITLE
[upnp] startup honors user settings.

### PR DESCRIPTION
**Pull request by MartijnKaijser**
Patch from @Rallymen007
https://github.com/xbmc/xbmc/pull/10072

Ping @Montellese

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Comment by Montellese** [comment]
Sorry for the (too) late reply. To match our coding style the curly braces should be removed.

And for the upnp controller to work the server has to be running as well i.e. the controller must only be started if the server is enabled as well. That's also how it is in the settings i.e. the controller setting is greyed out if the server isn't enabled.

**Comment by MartijnKaijser** [comment]
oops sorry. Best revert this instead of adjusting?

**Comment by Rallymen007** [comment]
These should have been fixed, the content of the file in commit 852f4d7 seems correct to me

**Comment by Rallymen007** [comment]
Oh no I got it wrong, sorry.

I can do it either way

**Comment by Montellese** [comment]
Follow-up PR is enough.

**Pull request merged**
