### PR TITLE
[PVR][Estuary] PVRInfoPanel cleanup.

### PR DESCRIPTION
**Pull request by ksooo**
Cleanup PVRInfoPanel and refactor channels, recordings, timers, timer rules and search window to use PVRInfoPanal - for consistent and improved user experience.

Before:
screenshot003
screenshot004
screenshot005

After:
screenshot000
screenshot001
screenshot002

@ronie for review?

### CODE REVIEW

**Comment by da-anda** [comment]
I think I'd personally move the thumb/icon to the right, like it was on most of the older views. That way we also wouldn't need a default thumb for everything that might not necessarily make sense (visually). But that's just my taste.

**Comment by MartijnKaijser** [comment]
fyi I don't have any thumbs added so i would get the default thumb everywhere? I'm surely not alone as adding them isn't noob friendly.

**Comment by ksooo** [comment]
This PR is about consistency and code reusage. Improvements are for another round. No discussion about left/right, larger/smaller, nose dripping, unwanted Christmas gifts,... please. ;-)

I tried channel logos on the right and it looked ugly (imo). So I decided to put them on the left. Default icon on the left still looks better than lots of empty space on the right.

**Review by ronie — APPROVED** [review]
looks good to me

**Pull request merged**
