### PR TITLE
Add plugin on android:scheme to open emby video

### PR DESCRIPTION
**Pull request by deblockt**

### CODE REVIEW

**Comment by Jalle19** [comment]
@koying

**Comment by koying** [comment]
How does it work, i.e. how is the "plugin:" url generated?

**Comment by deblockt** [comment]
The "plugin:" URL is generated by Emby plugin. Emby uses it to play video (with smb or http).

URL is saved on files.strFileName column.
this is an URL exemple : 
```
plugin://plugin.video.emby.movies/?dbid=1&mode=play&id=e88aeee4c4f9171cceab2bb2e5a31856&filename=4+Bassets+pour+un+danois.avi
```

**Comment by koying** [comment]
Ok, but adding "plugin:" to the manifest is for opening "plugin://..." url's from *outside* kodi.
So it'd eg means a web page with a "plugin://" url that, when clicked, would open Kodi to play it.

Is it what you're trying to achieve?

**Comment by deblockt** [comment]
I have wrote an external app to show recomendation tiles on android TV.
When we click on recomendation tiles, i open kodi intent with file URL as parameter.

When file URL start by plugin://, a blue screen is displayed because plugin:// is not on android:scheme and intent can not be started.

**Comment by koying** [comment]
You don't need this, then.
Just create an intent targeted at Kodi:

```
Intent intent = new Intent();
intent.setComponent(new ComponentName("org.xbmc.kodi","org.xbmc.kodi.Splash"));
intent.setAction(Intent.ACTION_VIEW);
intent.setData(Uri.parse("plugin://..."));
```

See also https://github.com/Razzeee/xbmc/pull/2

**Comment by MartijnKaijser** [comment]
i guess this can be closed?

**Pull request closed without merging**
