### PR TITLE
[confluence] update roboto fonts

### PR DESCRIPTION
**Pull request by un1versal**
```
Roboto-Bold.ttf     - Version 1.00000;2011 -> 2.001150;2014
Roboto-Regular.ttf  - Version 1.00000;2011 -> 2.001101;2014
```

Source https://github.com/google/fonts/tree/master/apache/roboto via http://www.google.com/fonts

Also has all licensing info, which remains unchanged.

Should have been done a while ago now,
For instance small things like #7009 benefit from this, so will other languages which glyphs have been updated. A benefit in general :smile: 

@ronie... @da-anda @MartijnKaijser

### CODE REVIEW

**Comment by Danny3** [comment]
The licence seems to be the same, please see my last comment on trac
http://trac.kodi.tv/ticket/15847#comment:3

**Comment by uNiversaI** [comment]
There are actually newer versions of roboto fonts ->  2.001101;2014

See https://github.com/google/fonts/tree/master/apache/roboto which is really the only place we should be getting these from. Ill update PR asap. Licensing is same yes.

**Comment by BigNoid** [comment]
+1 new version looks better too imo.

**Comment by da-anda** [comment]
testend and looks good to me. The only thing I'd probably like to do is to add a link to the github repo where the source of these fonts can be found. Not sure if this is required by the Apache2 license, but still a nice to have IMO. No necessity though, only if you guys also think it's a nice idea.

**Comment by uNiversaI** [comment]
@da-anda, Not a licence requirement, added source anyway to README because the copyright in README.txt needed updating to match https://github.com/google/fonts/blob/master/apache/roboto/COPYRIGHT.txt 

Also took liberty in renaming NOTICE.txt to LICENCE.txt and updated boilerplating there as well.

License is still same only copyright seems to have been updated, I thought it wise to actually review that and match requirements exactly.

**Comment by da-anda** [comment]
@MartijnKaijser button is yours

**Comment by MartijnKaijser** [comment]
@ronie any objections?

**Comment by ronie** [comment]
nope.

**Pull request merged**
