### PR TITLE
[Estuary] Rework PVR windows

### PR DESCRIPTION
**Pull request by ksooo**
This PR reworks PVR channels, recordings, timers, timer rules and search windows, plus the channels OSD dialog to share a common layout. Before, every window had its own implementation which led to smaller or larger visual inconsistencies.

Channels OSD dialog:
screenshot00010

Channels window:
screenshot00004

Search results window:
screenshot00009

Timer rules window:
screenshot00008

Timers window:
screenshot00007

Recordings window:
screenshot00005

### CODE REVIEW

**Comment by howie-f** [comment]
thanks, looked at it at runtime, i like it. anyway in https://github.com/xbmc/xbmc/pull/19380 i'm fixing i very small visual glitch in Estuary's Fanart-View for Movies & TVShows by bringing it in line with the "old" pvr views.
maybe a good idea to fix it with this pr, too? like make it consistent with the "new" pvr views?

**Comment by ksooo** [comment]
@howie-f sorry, no idea what you mean. Could you come up with a diff for this PR?

**Comment by howie-f** [comment]
point is if this pr goes in (what i do promote) the pvr views are not consistent to the FanArt-Views anymore. for example the option field: it is opaque and the list goes to the very bottom (like in the "old" pvr views)

screenshot00000

my suggestion is those views should be changed then, too. but it's something others have to agree on and it doesn't need to be done in this pr... though i'm aware pvr is a seperate section.... i just think it's better when it looks the same everywhere

**Comment by ksooo** [comment]
> my suggestion is those views should be changed then, too

 ... but not in this PR.

**Comment by ksooo** [comment]
> option field: it is opaque and the list goes to the very bottom (like in the "old" pvr views)

 This is problematic everywhere, because when you page the lost using page up/down, there are entries on top and bottom, you never can read because they are always halfway hidden behind top or bottom bar. This is why I changed it for PVR, where it was most obvious to me.

**Comment by howie-f** [comment]
> This is problematic everywhere, because when you page the lost using page up/down..

yes, that's why it is the suggestion. i'll try to match the FanArt-views with your new pvr views because i think it's just better. then we can see if it will follow up or not ;)

**Review by ronie — APPROVED** [review]
very nice cleanup, thx!

**Review by phunkyfish — APPROVED** [review]
I like the change, so a thumbs up from me.

**Comment by jjd-uk** [comment]
Sorry late to the party on this one.

@ronie I thought the underflow of items in a list to the very top and bottom, so items would show in Topar/Bottombar area, was 
a central part of the Estuary style? so this now introduces inconsistency with List, Widelist and Fanart views.

Personally I never cared for the underflow so I'm ok with what has been done here, so my main concern is the inconsistancy that has been introduced. If the underflow is no longer seen as part of the Estuary style then should List, Widelist and Fanart views should be changed to match this new style use within PVR? If so and if no one else has started anything, then I am ok to do the work to restore consistency.

**Comment by ksooo** [comment]
The underflow does not work for the PVR views. If you page through the list (page up/down), then there are items you never can read as they are either hidden top bar or bottom bar elements.

**Comment by ksooo** [comment]
> should List, Widelist and Fanart views should be changed to match this new style used within PVR? If so and if no one else has started anything, then I am ok to do the work to restore consistency.

+1 for this. If I remember correctly, @howie-f also wanted to work on that.

**Comment by jjd-uk** [comment]
Yes I fully understand that, and I see that that PVR views are particular propblematic with the lists being on left side so underflowing to an area containing a greater density of text. As I said I never cared for the underflow it in the first place because of that reason. As howie-f pointed out, the Fanart view is very similar in this respect also, so has a similar problem when paging up/down.  So if you then change Fanart to match what is done here, then that also begs the question does List & Widlelist also need to change to keep a consistency of style? in my view they do.

**Comment by jjd-uk** [comment]
So my comments simply boil down to 2 questions.

1) Should Fanart view be changed to match?
2) If 1) is done, then do List & Widelist also need a matching style?

I think howie-f was suggesting to only do 1) whereas I think 1) & 2) are needed, and I'm ok to do the work for that, plus check for any other areas there might now be inconsistent.

**Comment by howie-f** [comment]
@jjd-uk thanks. feel free to pick up what i started here https://github.com/howie-f/xbmc/commit/ba4ce3973a1cab5e665ba5fcb551c1c5e8886f20
it basically adjusts Fanart, WideList and List. Movies and TVShows affected... but Music, AddonBrowser etc. are not changed.
first tests seem ok. confidently handing it over to you :)

**Pull request merged**
