### PR TITLE
VideoPlayer: fix general synchronize, often resulted in global timeout

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by popcornmix** [comment]
Cool - I often saw invalid global timeouts (see the hack here: https://github.com/popcornmix/xbmc/commit/940614f061cf2fd0f94e28ee6934d89cbc9865f2)
A quick test of this PR didn't show any problems with MMAL or OMXPlayer.

**Comment by FernetMenta** [comment]
build error on Android-Arm unrelated

**Comment by fritsch** [comment]
This introduces an issue for me: http://sprunge.us/bBGM tuning to a channel in vnsi needs a long time (~ 15 seconds).  Reverting this commit fixes it.

**Comment by MilhouseVH** [comment]
Also, [hang at end of playback](http://forum.kodi.tv/showthread.php?tid=269815&pid=2433668#pid2433668).

**Comment by MilhouseVH** [comment]
And one more: this [sample video](https://www.dropbox.com/s/uptq22l2nv95h7r/blechnarrisch.ts?dl=0) is now very slow to start playback on LibreELEC #1009 NUC/ION2 and Ubuntu after #10668 - you see the busy spinner for about 45 seconds after pressing "Play" before the video appears. Prior to #10668, playback started instantly.

Debug log with #10668: http://sprunge.us/WTSa

**Comment by FernetMenta** [comment]
you are running an already outdated version

**Comment by MilhouseVH** [comment]
Yes, you are correct - with latest master (04d0abba5ec226ea0f03d6d7152b520cd69ef329) both issues I reported above are now resolved. Sorry for the noise!

**Pull request merged**
