### PR TITLE
[epg] cleanup for CEpgInfoTag

### PR DESCRIPTION
**Pull request by xhaggi**
see commit messages.

@opdenkamp @Jalle19 ping

### CODE REVIEW

**Comment by Jalle19** [comment]
Can you explain the reasoning of the first commit a bit more? Why is locking not necessary?

**Comment by xhaggi** [comment]
Because we only update it on import where we hold a lock and never alter it later.
Therefor it's not necessary that it is thread-safe. Discussed with @opdenkamp on IRC before.

**Comment by xhaggi** [comment]
@opdenkamp would be nice if you could take a look.

**Comment by xhaggi** [comment]
@opdenkamp done.

**Comment by opdenkamp** [comment]
+1

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by xhaggi** [comment]
jenkins build and merge

**Comment by MartijnKaijser** [comment]
failure was unrelated

**Comment by ksooo** [comment]
I understand from what Lars told me that the goal is to make CEpgInfoTag const, but today it has many non-const member functions modifying (almost) all members in a non-threadsafe way after #6498. 

My favorite: https://github.com/xbmc/xbmc/blob/master/xbmc/epg/EpgInfoTag.cpp#L510

As CEpgInfoTag instances today get accessed from several different threads I'd opt for reintroducing the lock for this class (for now). Especially as reintoducing the lock is very much effort compared to making the class const.

Opinions on that?

**Comment by opdenkamp** [comment]
the tags don't change once created, except for channel tags and recordings tags in them. those should be protected indeed, the rest doesn't

**Comment by ksooo** [comment]
Okay. Easy going then. I will come up with a PR protecting m_pvrchannel and m_recording (again) soon.

**Pull request merged**
