### PR TITLE
[cleanup] fix a bunch of double-promotion warnings

### PR DESCRIPTION
**Pull request by lrusak**
This PR aims to fix a bunch of the double-promotion warnings that we have. This fixes all of the warnings for my current platform and build configuration (should be a large chunk of the generic ones).

Most changes are trivial by either adding or removing the float literal `f`.

Some changes are a little more involved as they require casting to double or to float. I've done basic testing but the database changes could use a second set of eyes.

Please comment if you see anything concerning or have any questions about choices that I made.

### CODE REVIEW

**Review by garbear — APPROVED** [review]
I try to be double/float-correct, and it looks like I only missed one or two spots in RetroPlayer and games. It's great that we can add -Wdouble-promotion now.

**Review by yol — APPROVED** [review]
wayland change seems ok

**Comment by lrusak** [comment]
added a bunch more fixes for the clang platforms. I'm not sure if clang is more verbose with this warning or if gcc is just missing some? The platform specific ones were just gone off what I think was right, we'll see what jenkins says about iOS/TVOS/OSX/Android.

**Review by garbear — APPROVED** [review]

**Comment by lrusak** [comment]
should I fix the warnings in the `contrib/kissfft/kiss_fft.c` and `contrib/kissfft/kiss_fftr.c` files? I'm not sure how to handle these externally added files.

**Review by garbear — APPROVED** [review]

**Review by DaveTBlake — APPROVED** [review]
The changes in music related code look fine to me.
I have nuked some of the other IDE differences whitespace only changes introduced on otherwise unreleated lines, so a rebase is probably in order.

**Pull request merged**
