### PR TITLE
[Estuary] Cleanup noise from DefaultVideoVersions icon

### PR DESCRIPTION
**Pull request by the-black-eagle**
## Description
Clean up the noise from the icon.  I still think it is a little jagged compared to the other Estuary icons, but I'm useless at graphics.  Those dots were really bugging me though!

## Screenshots (if appropriate):

Before:
 
screenshot00122

After:
screenshot00123

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [X] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by HitcherUK** [comment]
I think it needs to be slightly smaller as it looks larger than the other icons and have some smoothing of the edges.
Maybe @samfishermike could take a look?

**Comment by jjd-uk** [comment]
Most of the existing icon seem to come from Google Material Design icons, so has anyone check if there's anything appropriate?

**Comment by zag2me** [comment]
I did a redraw using GIMP. Hopefully it helps.

new

**Comment by da-anda** [comment]
to me the icon looks more like a server rack than resembling video versions

**Comment by da-anda** [comment]
> Would perhaps this Google DVR icon perhaps suit better? What do you think @da-anda?

might be a bit too similar with icons that are usually use for subtitles, especially when it's small? I fear that we might have to come up with our own. Maybe something like a duplicated media (or video) icon, or a media/video icon along with `1 2 3`, or a media/video icon with HD/4K/* tags?

**Review by jjd-uk — APPROVED** [review]
As this PR is a necessary cleanup of an exisiting icon I'll approve. I think this will do until we find or produce something better.

**Review by Hitcher — APPROVED** [review]
Agreed, this will suffice for now but it doesn't really say 'versions'.

**Comment by jjd-uk** [comment]
If no objections I will merge tomorrow.

**Pull request merged**
