### PR TITLE
WIP: Include LFE mixing setting

### PR DESCRIPTION
**Pull request by fritsch**
There are some setups out there, that consist of e.g. 5.0 speakers or 2.0 speakers which have both Full Range L and R speakers. Currently AE does not include lfe channel when downmixing, which is good practice and recommended by several dolby formats.

Never the less, some people requested to be able to include the lfe channel when downmixing.

I currently don't have much time to work on this feature at once, therefore I post it early, but don't yet intend to merge it. Testers are obviously welcome.

### CODE REVIEW

**Comment by TheTyrius** [comment]
@fritsch Would you be willing to reconsider this PR? I've been searching for a solution to keep the LFE track on downmix, and having this option directly in kodi would of course mean minimal interference with the signal chain.

Is there a reason you did not pursue further? From the diff it doesn't seem unreasonable complexity-wise to have this (but I'm not an expert on this what-so-ever).

**Comment by rsalvaterra** [comment]
@fritsch, please, **please** consider prioritizing this. As someone relying on a stereo (2.0) hi-fi with full range speakers, I need this feature ten years ago (basically ever since I started using OpenELEC, now LibreELEC). I've always noticed something odd with the sound (especially in high action scenes), but only now I realised this is the exact problem: not optionally including the LFE channel when downmixing to 2.0.

**Comment by fritsch** [comment]
I rebased it - while doing so I realized again why I did not like it ... especially in ActiveAE.cpp it's yet another value that gets passed through in every function. Maybe it's useful for someone.

**Comment by TheTyrius** [comment]
I see what you mean. Do you think this is a (maintainability) reason to not merge the feature?

> From https://ffmpeg.org/ffmpeg-resampler.html `lfe_mix_level [...] is a value expressed in deciBel, and must be in the interval [-32,32].`
Do you know if this is applicable here, or if the way the value is set here it is a scalar 0-1?

**Comment by fritsch** [comment]
Should be a weight. The idea is that we mix "a part" of the volume of the sub into each front speaker. So 100% would double it, as it is put into left and right. 0.5 should take half into left and half into right.

**Comment by fritsch** [comment]
Changed the weight -> 100% now reflects also 100% in volume and is similarish to center volume. Feel free to runtime test it ... when I originally wrote it, it was long time ago.

**Comment by rsalvaterra** [comment]
> Feel free to runtime test it ... when I originally wrote it, it was long time ago.

I'd love to test the patch as-is, but unfortunately I don't have the possibility to do Kodi builds. That said, I'm running LibreELEC daily. If this this gets merged to master, eventually it will hit some LibreELEC daily build and I will most definitely test and provide feedback on it.

**Comment by TheTyrius** [comment]
I like the re-scaling around "neutral" 100% which seems more intuitive from a user-perspective. It might make sense to also include a 200% option: Most (?) AVRs apply a boost to the LFE channel that is stored at a lower reference level by specification, so for downmixing it may make sense to be able to do so at an increased level for similar results). My 2.0 setup is currently being revamped (which sparked my interest here in the first place) and I will do some testing around this when I can. 

A heart-felt _thank you_ for taking time to look at this old PR!

**Comment by fritsch** [comment]
Let's not bikeshed it to death, while no one has ever run it ... so, then - will wait on the feedback.

As this is a developer space, let's focus on that -> feature discussion is on the forum.

**Comment by TheTyrius** [comment]
So far my tests have come up empty: With the setting activated I am not getting any sound from the LFE trying multiple "channel check" videos (all 5/7 othter channels play fine).

Can someone confirm whether my build is to blame or there is something still missing with the feature?

**Comment by fritsch** [comment]
With ffmpeg debugging enabled (debug + component logging), you can see that the matrix weight for LFE is not there yet. It's set, but then left out when the downmixing happens.

One reason why this is WIP. When I made it (some years ago) I only wanted to show the path inside ActiveAE and the correlation to settings, with the hope that someone takes it up.

**Comment by fritsch** [comment]
Pick the trace above to see how far the value is coming.

**Comment by TheTyrius** [comment]
The trace shows an initial value of 0 on start-up, which is then changed to 1 after the skin is loaded (🥳).
However I then get mixlevels of 0 two times in the traces right after `CActiveAESink::OpenSink - DIRECTSOUND Initialized:` on playback start. `ActiveAE::CActiveAEResampleFFMPEG::Init: Mixing Level: 1` happens again only when playback is stopped. I can provide a full log via forum message if it helps.

This makes me believe it is very close to working, however I was so far unable to determine where the value is overwritten when playback starts.

Hardcoding the value to `2.0` has shown good results in a quick initial test.

**Comment by fritsch** [comment]
Simply link your debuglog

**Comment by TheTyrius** [comment]
While I still don't quite see through the data flow, I experimented with passing `m_settings.mixSubLevel` in `ActiveAE.cpp:1435` and in `CActiveAEBufferPoolResample::Create` calling `ChangeResampler()` when `m_mixSubLevel` has changed. I suspect there is something missing there, but I couldn't reach the desired combination yet.

Sadly I'll be away from my development machine for a few days.

PS: Please forgive me that I have a largely irrational fear of sharing a 1000+ line debuglog (I am only human unlike some of the team kodi, and cannot help it 😢). It may also be of limited use at this point: With the latest state of the PR, on playback start all trace values are 0.

**Comment by jjd-uk** [comment]
This isn't a support area, but for Kodi to have full audio control on Windows you should be using WASAPI. Directsound should be avoid if possible as it sends all audio through the Windows Audio Mixer.

**Comment by fritsch** [comment]
I compiled it yesterday - not so happy to see that Ubuntu 20.04 is not supported anymore - without manually getting libdisplayinfo, libfmt and libpsd logging properly installed ... I checked  through the code and come to clear conclusion: It's wrong on many levels ;-).

Most wrong is:
It is a user setting, not a stream property. The setting is an ActiveAE setting, but it is needed inside the Resampler / Remapper only and should not be overwritten when a stream starts, etc. So I need to change it, so that it only affects exactly this subsystem by simply adding a Setter towards the Resampler.

**Comment by TheTyrius** [comment]
> This isn't a support area, but for Kodi to have full audio control on Windows you should be using WASAPI. Directsound should be avoided if possible as it sends all audio through the Windows Audio Mixer.

Very true, thanks for mentioning! I tried both, initially just with everything at default (which I guess is still Directsound for compatibility reasons) and the new setting on, but then also with WASAPI (which I usually use), different sample rates etc to see if some codepaths are functionally different.

> It is a user setting, not a stream property. The setting is an ActiveAE setting, but it is needed inside the Resampler / Remapper only and should not be overwritten when a stream starts, etc. So I need to change it, so that it only affects exactly this subsystem by simply adding a Setter towards the Resampler.

This makes sense with my (very) superficial understanding from looking at the value passing. Thank you again for taking the time to improve this 🤍 I am pretty out of my depth on anything more than add-on dev, so I'm looking forward to seeing/learning how the new approach might be realized.

**Pull request closed without merging**
