### PR TITLE
[win32][depends] Updated taglib to v1.11

### PR DESCRIPTION
**Pull request by Paxxi**

### CODE REVIEW

**Comment by Paxxi** [comment]
@Razzeee @DaveTBlake here you go, files are uploaded and should be available in 30 minutes or so

**Comment by MartijnKaijser** [comment]
Also uploaded for non-win32 platforms
http://mirrors.kodi.tv/build-deps/sources/taglib-1.11.tar.gz

**Comment by MrMC** [comment]
does this fix the issue see with currnet taglib ?

**Comment by MartijnKaijser** [comment]
That's what we'll find out. First needed a compiled win32 version

**Pull request merged**
