### PR TITLE
changed: Prefer openssl over gnutls for libcurl on Linux and Ubuntu

### PR DESCRIPTION
**Pull request by arnova**
On most of my systems gnutls has proven not to be stable/reliable for libcurl, therefor make the default openssl.

### CODE REVIEW

**Comment by wsnipex** [comment]
not against this, just asking what issues you have?

**Comment by arnova** [comment]
@wsnipex : Previously crashes and lockups. Currently lockups again on Ubuntu 14.04.

**Comment by popcornmix** [comment]
I found using gnutls caused hanging when opening streams, and openssl avoided the issue. This was on a Pi with libs from debian. See: http://trac.kodi.tv/ticket/14674#comment:19

So, I agree gnutls was less reliable in my usage and openssl should be the recommended choice.

**Comment by arnova** [comment]
Perhaps even ditch the | libcurl4-gnutls-dev completely ?

**Comment by wsnipex** [comment]
I'd rather not.

**Comment by arnova** [comment]
Ok. If no objections, will merge today. Can someone also update our buildbot so it uses openssl instead of gnutls (for Linux) ?

**Comment by Memphiz** [comment]
does this matter? we don't distribute binaries for linux...

**Comment by arnova** [comment]
@Memphiz: Probably not.

**Pull request merged**
