### PR TITLE
[WIN32][VFS][CURL]Possible fix for deadlock when stopping playback

### PR DESCRIPTION
**Pull request by Paxxi**
This is to get a discussion started on how best to fix a deadlock mentioned by @natethomas and referenced in http://forum.kodi.tv/showthread.php?tid=200735&pid=2006850#pid2006850 . 

What happens in my testing is that CFileCache is waiting on either m_seekEnded or for more data. When we stop playback our main thread calls stopthread on dvdplayer and blocks. Dvdplayer calls stopthread on CFileCache and blocks. CFileCache doesn't get any new events since everything is blocking waiting for it to go away.

First line of the fix seems like it shoul've been there from the start and I think it should go in.
Second line I'm not entirely sure about. I don't see a scenario where it would be bad to force close the file but maybe someone more familiar with dvdplayer can chime in on what bad things can happen.
@FernetMenta thoughts?

### CODE REVIEW

**Comment by arnova** [comment]
The second line looks a bit weird as CFileCache::StopThread() will call m_source.Close() now but  CFileCache::Close() will call both CFileCache::StopThread() followed by  m_source.Close(). But the order is different there so expect there will be problems from doing it this way.

**Comment by Paxxi** [comment]
Yeah I'm not sure yet how a good solution would look, it needs more research and discussion

**Comment by FernetMenta** [comment]
1)
the actual problem is that the waits in this code don't have a timeout. threads should never block forever praying that the event will come. I would keep them looping and handling timeout properly.

2)
m_source seems not protected. not sure if close is supposed to be called outside of process()

**Comment by Paxxi** [comment]
@FernetMenta agreed, however there's another scenario where we block in CFile::Read e.g curlfile waiiting in select which the cache really knows nothing about how long it will block.

**Comment by arnova** [comment]
@Paxxi : Yeah, that's a related problem. See related bug report here: http://trac.kodi.tv/ticket/15946

**Comment by Paxxi** [comment]
@arnova right. I've tested a few other solutions today and they reduce the occurence of the issue but then I've noticed that after starting+stopping a video 3-4 times it will deadlock at the same place while not actually playing the video so no real progress yet.

**Comment by arnova** [comment]
So just to be clear (unfortunately I can't reproduce thus I can't witness it in the debugger either), the main problem is that the source-read() call in the CFileCache thread blocks, right? If so, then forcing a close off-thread may be the only solution, but I do wonder how save this is (calling Read() in one thread and calling Close() for the same handle from another). Have you check this @Paxxi  ?

**Comment by Paxxi** [comment]
Yeah I did try it out and it didn't go all that well, I think it leaves some bad state in curl because I saw random crashes with corrupt memory when trying to play the video again. It didn't hang though :)

**Comment by Paxxi** [comment]
@arnova I did try another method as well, since in the callstacks I've gotten when breaking into the debugger is mostly in the curlfile write callback method I thought that we could cancel io that way.

What I did was, add a method CancelPendingIO that set the m_cancel flag in CurlFile and whn it's set in the write callback it would return the wrong number of bytes written which is documented by curl as a write error that it should mark as broken/dead and stop trying to read/write on that socket. It didn't work though as curl didn't return from multi_perform still.

sample callstack https://gist.github.com/Paxxi/23e059b65c93b978725b#file-gistfile1-txt-L447

**Comment by Paxxi** [comment]
can someone upload http://delusional.nu/curl-7.42.1-win32.7z to win32 depends, would like to do a test build of this and see if it solves it for others as well.

**Comment by arnova** [comment]
@paxxi: Keep in mind that the problem may also be related to the OpenSSL/GNUTLS/? (don't know what we use on Windows) version we're using. On Linux we also had a bunch of problems with those in the past.

**Comment by Paxxi** [comment]
we use windows own schannel for ssl on windows. Testing with openssl instead works perfectly for me so I repackaged curl using openssl instead as a workaround for now. I want to get back to using schannel on win32, waiting on the curl team to see what they say.

**Comment by arnova** [comment]
Then that's probably what our previous version also used (=OpenSSL) since I didn't spot anything obvious in Curl's changelog. I don't know anything about ssl on Windows but I do know that both OpenSSL and GNUTLS require crypto-locking on Linux (else it may crash/lockup when multiple threads call into Curl), this may be the case here as well.

**Comment by Paxxi** [comment]
As far as I can tell it's not a threading issue, it's a design issue in the innermost readwrite loop in curl, it uses the same code for all implementations but the function to determine if it should continue is specific for different ssl libraries. 

I think we used gnutls for our old curl version but it's a huge pain to use on windows so I opted for openssl this time.

**Comment by Memphiz** [comment]
@Paxxi uploaded - needs some minutes to sync through the mirrors as usual...

**Comment by Paxxi** [comment]
ok test build at http://mirrors.kodi.tv/test-builds/win32/KodiSetup-20150531-a231852-deadlock.exe
@natethomas can you try it out when you have the time? and anyone else that's seen the issue

**Comment by natethomas** [comment]
I'll need to spend some time watching videos, but a quick 3 minute test doesn't seem to be locking at all. Looks like you might have gotten it fixed! :+1:

**Comment by natethomas** [comment]
A bunch more testing, and I'm not seeing any issues. Looks like you could probably merge the PR @Paxxi .

**Comment by kricker** [comment]
Also did some testing and also not seeing any issues.

**Comment by Paxxi** [comment]
@arnova any objections? Otherwise I'll probably merge this tomorrow morning

**Comment by arnova** [comment]
@Paxxi: No, I'm fine with this. Seems like the best (proven) solution. The m_seekEnded fix is no longer required? It's hard for me to wrap my head around the fact whether it's required or not.

**Comment by Paxxi** [comment]
I don't think it's needed, haven't hit that issue when using this libcurl so I think it should be fine

**Comment by afedchin** [comment]
seems this cause segfaults on some systems. @Paxxi please take a look http://forum.kodi.tv/showthread.php?tid=229644 the segfault occurs somewhere inside global_init method of libcurl.

**Pull request merged**
