### PR TITLE
[WIP] Add android API PT + FLOAT

### PR DESCRIPTION
**Pull request by koying**
This enables API-based passthrough (including HD) on Android (and float encoding, while at it)

Please bear with me, as it was my first journey in the internals on audio playing, so "assume no malice" ;)

By looking at the current kodi code, I took the following assumptions:
**A1)** SYNC_DISCON means audio clock is master and is used for passthrough
**A2)** The recent "large sync error" changes kind of broke SYNC_DISCON by forcing skip/dup anyway
**A3)** Our "internal" samplerate notion is a mix between actual samplerate and input bitrate, so it can hold any value
**A4)** We don't support frames of variable sizes, internally
**A5)** Some padding is happening when feeding the sink to meet the "minimum frames" requirement

Requirements:
**R1)** Bytestream must go unaltered from demuxer to AE sink (not skip/dup/silence)
**R2)** Sink must be fed by full packet. Not actually sure of this requirement, but given A5, plus the fact that the sink only updates its position by full packets, that's how I implemented it.

For the functionality, the following options were considered:
**O1)** Use the already existing IEC61937 encapsulated passthrough format and "decapsulate" it in sink.
This was working for AC3/EAC3 but quite inefficient:
- out of a 6144 byte IEC61937 packet, only 1536 are meaningfull, so we are transporting 3 times as much zero as data
- IEC61937 imposes endianess, so the operation had to be reverted in sink
- Even more operations were to be reverted for HD adio (burst modes)

**O2)** Create a "RAW" passthrough formats that , currently, only the droid sink will support:
- Only meaningful bytes are moved around
- No time-consuming process in the sink
- Still needs to do light encapsulation of variable-rate HD audio to mitigate A4
- Sample rate is not menanigful as such, as it actually is the bitrate (A3)

I started with O1 but then shifted to O2

The changes to DVDplayeraudio are to mitigate A1 & A2. Those are quite empiric due to my lack of knowledge, so any better solution that meets R1 is welcome

/cc @FernetMenta @anssih @fritsch @AlwinEsch

### CODE REVIEW

**Comment by FernetMenta** [comment]
We discussed briefly on IRC. This are design consideration:

- Audio sync in player is almost gone in VideoPlayer branch. It is done in AE. -> SYNC_DISCON and friends are history
- Having two passthrough formats make no sense. As discussed on Slack: Switching to RAW seems to be the way to go
- AE requires some changes to determine packet start/end, and playing time
- IEC encapsulation will be done in sink stage. (not sure yet if in sink or ActiveAESink)
- sinks that support passthough need to implement some method for sync

R2) can be easily done by sink when audio buffers convey info for start/end of frame.
R1) sinks need to implement methods for sync

You can better progress this if you base on my master (VideoPlayer)

**Comment by FernetMenta** [comment]
I nobody objects, I will move the IEC packer from player to ActiveAESink. I should have some time this week, at least I can start with this.

**Comment by fritsch** [comment]
@FernetMenta as discussed this is an important step into the right direction. Thanks much for starting.

**Comment by FernetMenta** [comment]
@koying I have finished moving IEC packing into AE, maybe some minors like bugs left though. Was more work than I originally thought it would be :) git shows for the major commit. 

```
Showing  58 changed files  with 1,307 additions and 1,114 deletions.
```
Also contains a lot of clean-up.
I left the commits for the sinks, that platform devs can get a better overview of what needs to be changed. Check out my master branch. CActiveAESink::OutputSamples does the IEC packing now, if a sink signals that it wants to have it this way.

**Comment by fritsch** [comment]
Mmh the sink commits are in your aewip branch: https://github.com/FernetMenta/xbmc/commits/aewip master has them squashed.

I started a bit for Audiotrack: https://github.com/FernetMenta/xbmc/commit/515f4c31f36fc0dda7b322fe2262eb257c1f2442 - have fun :-)

Also the entry point in ActiveAESink, you can fill out as you wish: https://github.com/FernetMenta/xbmc/blob/master/xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp#L163 or just ask on IRC

**Comment by koying** [comment]
@FernetMenta @fritsch Okido, thanks. I will shift dev to the videoplayer asap (as it seems everybody is already running it, anyway ;) )

**Pull request closed without merging**
