### PR TITLE
[PVR] API 3.0.0 Implementation of "Visibility Controls for timer types"

### PR DESCRIPTION
**Pull request by ryangribble**
This is the implementation of one of the API 3.0.0 features from #7626 

New TimerType attributes that allow PVR addons to specify whether TimerTypes should be visible in the "Add Timer" window based on whether the EPG info is/isn't present.  This is the end result of discussion on #7660

The first 2 commits are the API bump/fields from #7626 and the 3rd commit is the actual PVR Core implementation.  This will likely be pulled together by @metaron-uk with whatever other API 3.0.0 changes are "good to go" into a new PR

**PVR Client Changes Requried**
PVR Clients that have implemented the new Kodi16 Series Recording changes and were relying on the previous hard coded behaviour that was hiding Single Guide Based timer types (but not Repeating Guide Based timer types) on creation, will need to be tweaked to specify the Forbid/Require attributes on their timer types as appropriate.  This is a minor change, so far only known to affect pvr.hts

**Context**
This PR relies on the changes in PR #7626 which groups several API changes forming API 3.0.0.
- This PR should not be merged unless PR #7626 has also been merged.
- The necessary supporting API change is contained in commit [[PVR] Menu visibility controls for timer types](https://github.com/metaron-uk/xbmc/commit/116414607facab6bf377de525135e69c38f0c043). If this change is withdrawn from PR #7626 this PR will be closed.

**Comments**
Please make comments regarding the TimerType Visibility change itself here.
For comments regarding any of the other 3.0.0 API changes, please use #7626

@metaron-uk @ksooo @xhaggi @Jalle19 @janbar

### CODE REVIEW

**Comment by metaron-uk** [comment]
Thanks for doing these two changes @ryangribble, one thing less to worry about. I'll check them out with my working mythtv code next, but as @ksooo says, looking good.

My plan was to create a PR for each client which rolls in all the necessary changes to support API3.0.0 (whatever that ends up being) once there seems to be a consensus on the content. I'm happy to include this change along with the others where required. 

I'll start off with a PR for mythtv, then the 'foreign' clients (i.e. not hts or wmc) then add those at the end if they are still outstanding.

**Comment by ryangribble** [comment]
Fixed the doxy comments (force pushed)

**Comment by ryangribble** [comment]
ALso have updated the PR text to note that PVR Clients that relied on previous hardcoded hiding behaviour (eg TVHeadEnd as @ksooo mentioned) require a tweak to use the new attributes to maintain existing behaviour.

**Comment by ryangribble** [comment]
Moved to #7626

**Pull request closed without merging**
