### PR TITLE
XBMCApp: Use STOP if PAUSE is not supported

### PR DESCRIPTION
**Pull request by fritsch**
Test for: #12866

### CODE REVIEW

**Comment by fritsch** [comment]
Testbuild pending, will have: androidstop in name.

**Comment by koying** [comment]
Nope, I don't want to stop instead of pause.
Or do I miss something?

**Comment by fritsch** [comment]
It's for:
onVisibleBehindCanceled
onStop
onAudioFocusChange

only? 

Do I miss something?

**Comment by koying** [comment]
Not following you.
Currently, when Kodi loses the focus, the current playback is paused.

I want to keep that.

The issue solved with the other PR is that, obvisouly, you cannot pause a non-pausable stream.
Furthermore, there was a reflection on whether timeshifted live streams should be stopped or paused.

Pro for stop: avoid to forget about the timeshift being filled up
Con for stop: When we stop, the existing timeshift buffer is lost forever.

Anyway, as there is no way to find out if the player is playing a timeshift, the "stop for all pvr" option is not possible

**Comment by fritsch** [comment]
Okay - that means, we keep the PAUSE as it is now?

**Comment by koying** [comment]
Yep

**Comment by fritsch** [comment]
Can't we just use CanPause on the applications player interface instead? (Added this code)

**Comment by fritsch** [comment]
The updated original PR does exactly the same, while querying player only once. Sorry for the noise.

**Pull request closed without merging**
