### PR TITLE
reduce padding on dialog buttons

### PR DESCRIPTION
**Pull request by ronie**
give translators a bit more room to breathe

request: http://forum.kodi.tv/showthread.php?tid=251989

2o5e8r2

### CODE REVIEW

**Comment by HitcherUK** [comment]
Couldn't this just become a fullscreen dialog seeing as it's almost there anyway?

**Comment by ronie** [comment]
sure, no objections from my end. could be done as a follow-up to this PR i think?

for Jarvis i'd prefer to stick to small non-intrusive changes like this, instead of recoding it to a full window.

**Comment by MartijnKaijser** [comment]
good to go?

**Comment by ronie** [comment]
yup. no-brainer.

**Pull request merged**
