### PR TITLE
[musicdb] improves performance for querying the album view

### PR DESCRIPTION
**Pull request by xhaggi**
This will improves the overall performance for queries which select from `albumview`. 
I've dropped the group by from the album view because it dramatically slow down each related query.
Further more I've optimized the albums by artist where condition to use a sub-select instead of group by + join + or, which also reduce the query time.

Related forum thread: 
http://forum.kodi.tv/showthread.php?tid=223731

Some execution times before and after.

```
SELECT albumview.* FROM albumview JOIN song ON song.idAlbum = albumview.idAlbum JOIN song_artist ON song.idSong = song_artist.idSong JOIN album_artist ON albumview.idAlbum = album_artist.idAlbum WHERE song_artist.idArtist = 779 OR  album_artist.idArtist = 779 GROUP BY albumview.idAlbum
```

SQLite: 1306ms
MySQL/MariaDB: 4466ms

```
SELECT albumview.* FROM albumview  WHERE (EXISTS (SELECT 1 FROM song JOIN song_artist ON song.idSong = song_artist.idSong WHERE song.idAlbum = albumview.idAlbum AND song_artist.idArtist = 780 ) OR EXISTS (SELECT 1 FROM album_artist WHERE album_artist.idAlbum = albumview.idAlbum AND album_artist.idArtist = 780))
```

SQLite: 1ms
MySQL/MariaDB: 91ms

@mkortstiege mind taking a look.

@sopparus thanks for sharing your mysql/mariadb server ;)

### CODE REVIEW

**Comment by Montellese** [comment]
Please use `(NOT) EXISTS` instead of `(NOT) IN` as it is further optimized to stop as soon as the condition is met instead of executing the full subquery.

**Comment by xhaggi** [comment]
In that case there is no difference between EXISTS vs. IN, the query plan looks the same.
As there is no benefit should I change it to EXISTS?

BTW take a look 10 lines above ;)
https://github.com/xbmc/xbmc/pull/6941/files#diff-dab45208f50daf6a73c9472dd2ad7e3dL5749

**Comment by Montellese** [comment]
A while ago I started changing all IN conditions to EXISTS conditions in the videodb whenever I have to touch an existing query and I use EXISTS for all new queries. Are you sure that the query plan is the same? Is this for MySQL or SQLite?

**Comment by mkortstiege** [comment]
Nice! As for the view update you need to bump the db schema so it get's re-created.

**Comment by xhaggi** [comment]
@Montellese I've compared the query plan in sqlite and it differs for IN and EXISTS. As this has no effect to MySQL, but to SQLite i'll change it to EXISTS to be consistent with your changes in videodb.

@mkortstiege thanks for the hint, but i leave the version as it is because we want to test against the same database version. Will bump it now ;)

**Comment by xhaggi** [comment]
@Montellese @mkortstiege please take a second look, thanks.

**Comment by Montellese** [comment]
Looks good for me.

**Comment by xhaggi** [comment]
jenkins build this please

**Pull request merged**
