### PR TITLE
Prevent crashing when visualToLogicalMap contains garbage values

### PR DESCRIPTION
**Pull request by AhmedAdelAbouzeid**
## Description And Context
Follow up to #17790 
* Initialize visualToLogicalMap before passing it to Fribidi to prevent crashing when the mapping contain invalid values
* Correct the values in visualToLogicalMap when the visual string is shorter than the original logical string (due to multiple code points possibly representing a single grapheme)

## How Has This Been Tested?
The changes were tested using Kodi on Windows 10 x64 (1909)
A search was performed using the Youtube add-on for videos whose titles contain emojis, kodi no longer crashes when displaying the search results

## Screenshots (if appropriate):
KodiEmojiCrash

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by yeahme49** [comment]
Just tested and it fixed the crash for me.

**Comment by fuzzard** [comment]
jenkins build this please

**Review by phunkyfish — APPROVED** [review]
Thanks again @AhmedAdelAbouzeid

**Comment by AhmedAdelAbouzeid** [comment]
@phunkyfish thanks a lot for reviewing.

**Comment by phunkyfish** [comment]
Thanks again for the contribution @AhmedAdelAbouzeid !!!

**Pull request merged**
