### PR TITLE
added: include watched status for movies in actor search dialog

### PR DESCRIPTION
**Pull request by notspiff**
## Description

It is useful to see watched status for movies when searching from the info dialog. This adds a textual indicator, and changes the dialog to the detailed one (with thumbs).
## Motivation and Context

Easily finding an unwatched movie with a specific actor.
## How Has This Been Tested?

Simple human inspection.
## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

ref http://forum.kodi.tv/showthread.php?tid=293624

### CODE REVIEW

**Comment by fritsch** [comment]
Code is fine (as always :-))

**Comment by phil65** [comment]
Just an idea: since [TYPE] MOVIETITLE (YEAR) (WATCHEDSTATUS) might become a bit too much, perhaps use DialogSelect detailedmode and move either TYPE or WATCHEDSTATUS to label2? That way we could also show the cover/thumb of the movie.

**Comment by MilhouseVH** [comment]
I like the idea, but can't help thinking the list is now a little overloaded...

s1

**Comment by notspiff** [comment]
please try now.

**Comment by MilhouseVH** [comment]
That's a big improvement - thanks!

s2

**Review by MartijnKaijser — APPROVED** [review]

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by phil65** [comment]
Thanks for makin those changes!

**Pull request merged**
