### PR TITLE
[profiles] separate bookmarks for each profile

### PR DESCRIPTION
**Pull request by Rechi**
every user get separate bookmarks, if the media sources are shared

### CODE REVIEW

**Comment by mkortstiege** [comment]
I've not runtime tested this yet but i like the idea. In first sight, I thought it might be idProfile though.

**Comment by Rechi** [comment]
It's no problem to rename idUser to idProfile.

**Comment by Tolriq** [comment]
This will impact remote makers that all assume 1 file = 1 resume point.

If this change this is major impact and profiles should be better supported in JSON api, and allow a way to connect a profile when on profile choice screen.

**Comment by Rechi** [comment]
It could be changed that there still is only 1 resume point and the other bookmarks are separated for each profile.
Would this solve the problem?

**Comment by Tolriq** [comment]
Well not really my call, but the current change would be welcomed in the future, but just need a more global approach of profiles for remotes.

My concern are more about Isengard being in an half state meaning again hacks for remotes.

I suppose only bookmarks for Isenguard and proper solution for future could be a good target.

**Pull request closed without merging**
