### PR TITLE
[PVR][Settings] Recording timer padding 

### PR DESCRIPTION
**Pull request by ivanllc**
## Description
Padding time in PVR Recording settings.  Add "2" minutes in padding time option box.

## Motivation and context
Padding time should allows user more fine-grained control of recording. 
The padding time  prevents PVR settings from EGP not match with real broadcasting time, in many cases just a little bit time shift.
0, 1, 2, 3, 5... Fibonacci series?  

## How has this been tested?
Simple variable return list of integers. 

## What is the effect on users?

Add padding time option "2" minutes.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ksooo** [comment]
@ivanllc please squash down to a single commit and I will approve the PR. Thanks.

**Comment by ivanllc** [comment]
> @ivanllc please squash down to a single commit and I will approve the PR. Thanks.
@ksooo  coz I don't know how to squash pull request commits in Github web, no "squash and merge button" in my PR view.
I have tried Github desktop and merge form ivanllc/xbmc:rec_timer_padding into ivanllc/xbmc:master (may be  incorrect branch operation). 
I have read the contribute guide, I also know incorrect git push may mess the commits history,  Any tutorial web page or video about that correct squash and merge is welcome, especial  in kodi.  Thanks.

**Comment by ksooo** [comment]
@ivanllc https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together

**Comment by garbear** [comment]
I checked the commit history and you should be able to do

```
git reset --hard 3e6a4d8461b357bd85c8d40bc2d36f00c90b3e76
git push -f
```

**Comment by ivanllc** [comment]
> I checked the commit history and you should be able to do
> 
> ```
> git reset --hard 3e6a4d8461b357bd85c8d40bc2d36f00c90b3e76
> git push -f
> ```


Thanks, 
I have reset it in branch rec_timer_padding and roll back to the commit. 
Should i run this command in "master" branch of my repo again coz some incorrect merge(dcaa61c342158a3b5b87f7bbecd0d0c9df5684f0) I have made?

**Comment by ksooo** [comment]
@ivanllc can you please apply the code formatting diff from Jenkins and squash down to a single commit? Then we are ready to go.

**Review by ksooo — APPROVED** [review]
Thank you very much for your first contribution to the Kodi project.

**Pull request merged**
