### PR TITLE
Fixes for using giflib 5.1 in GifHelper.cpp

### PR DESCRIPTION
**Pull request by kmihelich**
This fixes a few API changes for building against giflib 5 that were missed in the recent move of this code to native.

### CODE REVIEW

**Comment by Memphiz** [comment]
but we compile texturepacker without those changes - also using giflib5 ... how can this work?

**Comment by kmihelich** [comment]
My bad, these API changes are for giflib 5.1.  I've updated the changes to also check for the minor.

**Comment by Memphiz** [comment]
which distribution is using giflib 5.1? let me guess - this is gentoo?

**Comment by kmihelich** [comment]
Arch Linux.  5.1.0 was released on May 15, 2014, so this isn't brand new.

**Comment by Memphiz** [comment]
@wsnipex for you ...

**Comment by ace20022** [comment]
@Memphiz Do you now understand what I was trying to say?

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
@ace20022 what you tried to say when?

**Comment by ace20022** [comment]
@Memphiz these changes are (semantical) the same as the ones in my pr to your branch that I asked you to merge with your pr (https://github.com/xbmc/xbmc/pull/5436).

**Comment by Memphiz** [comment]
@ace20022 you seem to have taken offense for something that wasn't even ment offensive. I can only imagine that you are talking about PR13 to my repo - and as said there - i just hadn't time to look into it. When i did the texturepacker stuff i didn't even think about anything different then what we package (giflib5) and ... well i think i don't need to defend myself here for what its worth...

**Comment by ace20022** [comment]
@Memphiz nah, It was my fault; I had not written my thoughts clear enough.

**Comment by wsnipex** [comment]
since the jenkins win32 build log is gone, does anyone know why it failed?

**Comment by ace20022** [comment]
Probably because of a downooad error, see the last comments in #4143

**Comment by Memphiz** [comment]
@wsnipex fyi i hat to cut down the number of logs to keep because those took up nearly all the space on the jenkins server 2 weeks ago (i didn't think of that when i made this partition 10gb) - once i have some time i will give the jenkins server more space and then increase the number of kept logs again...

**Comment by bkuhls** [comment]
wfm

**Comment by kib** [comment]
Logs have been increased, win issue has been fixed so

jenkins build this please

**Pull request merged**
