### PR TITLE
[cmake] File renaming for readability

### PR DESCRIPTION
**Pull request by hudokkow**
@wsnipex, @fetzerch, followup of https://github.com/xbmc/xbmc/pull/9742

### CODE REVIEW

**Comment by fetzerch** [comment]
I don't have a very strong opinion about that. But for consistency, shouldn't also `kodi-config.cmake` be renamed to `KodiConfig.cmake` (find_package looks for both versions). I'm just wondering if it makes sense to somehow stick closer to @notspiff's fork. But we probably deviated a lot already anyways.

**Comment by hudokkow** [comment]
KodiConfig.cmake makes sense. Will change.
As for the rest, I also don't have a strong opinion. Whatever we decide, we should enforce it and the sooner the better. This is somewhat intrusive and may cause some trouble rebasing big PRs.

**Comment by notspiff** [comment]
don't mind my fork, i'll handle the rebasing.

**Comment by hudokkow** [comment]
Thanks Arne.
I will merge tomorrow after a jenkins run if nobody objects.

**Comment by hudokkow** [comment]
jenkins build: http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-All/1361/ with https://github.com/xbmc/kodi-platform/pull/25

**Comment by hudokkow** [comment]
jenkins build this with addons please

**Comment by hudokkow** [comment]
One last time to make sure after PRs final review: jenkins build this with addons please

**Comment by hudokkow** [comment]
Build is fine on jenkins, Travis is borked with tests. Appveyor must be on vacation with Martijn

@afedchin, @notspiff, @mapfau, @AchimTuran and @wsnipex for audioencoder.* add-ons:

This is going in now. Time to hit the trigger on the PRs mentioned above.

**Pull request merged**
