### PR TITLE
[Android] Priorize timer instead HDMI_AUDIOPLUG on refreshrate switch

### PR DESCRIPTION
**Pull request by fritsch**
Backport of:  #16978

### CODE REVIEW

**Comment by fritsch** [comment]
The reviewers were chosen automatically. Sorry for the noise :-)

**Review by peak3d — APPROVED** [review]

**Comment by peak3d** [comment]
@ksooo do you want to review / test ?

**Comment by ksooo** [comment]
Sorry, no Leia test environment here.

**Comment by peak3d** [comment]
Jenkins build this please

**Pull request merged**
