### PR TITLE
[cleanup] remove unused depends

### PR DESCRIPTION
**Pull request by stefansaraev**
remove now unused libogg/libvorbis dependencies. also clean up flac leftovers

jenkins was happy. last commit is to test travis ci, will squash later

### CODE REVIEW

**Comment by wsnipex** [comment]
Did I miss something or did ffmpeg stop suggesting the use of libvorbis, cause its internal support was bad quality?

**Comment by stefansaraev** [comment]
I never heard ffmpeg suggesting using libvorbis cause internal ogg decoder was bad quality. in the past, libvorbis was used for audio encoding, not anymore. do you know any good reason we would need ogg muxer and vorbisenc now ?

**Comment by fritsch** [comment]
libopus > libvorbis >= libfdk_aac > aac > libmp3lame >= libfaac >=
eac3/ac3 > libtwolame > vorbis > mp2 > wmav2/wmav1

via: https://trac.ffmpeg.org/wiki/Encode/HighQualityAudio


2016-04-26 12:03 GMT+02:00 Stefan Saraev <notifications@github.com>:

> I never heard ffmpeg suggesting using libvorbis cause internal ogg decoder
> was bad quality. in the past, libvorbis was used for audio encoding, not
> anymore. do you know any good reason we would need ogg muxer and vorbisenc
> now ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/xbmc/pull/9686#issuecomment-214690922>
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by fritsch** [comment]
In short: if you encode vorbis with ffmpeg libvorbis should be used.
>libvorbis (-codec:a libvorbis) is recommended over the very experimental, native FFmpeg Vorbis audio encoder (-codec:a vorbis -strict experimental) since it does not provide comparable quality to libvorbis.

**Comment by stefansaraev** [comment]
we are talking different things there. see what I wrote. we do not do internal vorbis encode anymore. that's moved to an addon, which uses own "libvorbis" dependencies and links staticaly. 

anyhow, I tried to cleanup stuff that (seems to) not make sense in kodi nowadays, if you dont want the mess cleaned up, okay. #9683 is enough for me. I dont even use unified deps, and I will never do, anyway

**Comment by FernetMenta** [comment]
+1 for this cleanup
endocders can be done by addons.

**Comment by fritsch** [comment]
jenkins build this please

**Pull request merged**
