### PR TITLE
[homescreen] update selection of recently added movies and tvshows/episodes

### PR DESCRIPTION
**Pull request by InuSasha**
- movies+tvshows+musicvideos can filter out the seen one
- tvshows have now 4 selection modes (tvshows with recently added episodes, tvshows in )
- setup over videolibrary settings (defaults to the old behavior)

@ a native english speaker: please check my speelings

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
i give this very little no change being included.
i'll leave it for @ronie to decide

**Comment by InuSasha** [comment]
@MartijnKaijser have you a reason for it?

**Comment by MartijnKaijser** [comment]
you put controls in to Kodi stettings which have absolutely no affect at all if users switch skins. We cannot force skins to use these settings and they will use whatever plugin/addon to fill their homescreen widgets. So user switches skin, and the settings do nothing. We get the complaints.

**Comment by InuSasha** [comment]
Both controls have no direct effect to the skin.
These effect to the RecentlyAddedJob. So every skin, with use this job will automaticlly have this feature.
Only the skin change from scale to keep is relevant, i think. But this will only streatch the tvshow cover :)

**Comment by MartijnKaijser** [comment]
what i mean that users see the settings and expect them to work regardless in which skin. not all skins use current implementation and use some third-part plugins which have their own settings.

**Comment by InuSasha** [comment]
sorry. now i know what you mean.
A simple solution is, to add an infomation in the help comment ("only for skin, which support preview").
@ everyone: anyone who now a better solution for the problem please tell

But the use case of preview/recently added on home is broken for me (and i believe same other). because i see only the ten last seen movies. Or when i add a season i only see the last episodes not the first. So i can deactivate the preview completly

**Comment by HitcherUK** [comment]
A better change IMO would be to allow the use of custom playlists for Confluence's home screen.

**Comment by ronie** [comment]
imo the RecentlyAddedJob has served it's purpose and should be removed in the near future.
i doubt many skins, beside confluence, still use it.
we have other/better ways to provide similar functionality these days.

**Comment by InuSasha** [comment]
@ronie will the preview be gone completly, or only the implementation will change.
in the second case, how can help to get my proposal in it?

**Comment by ronie** [comment]
i think content provided by playlists, like @HitcherUK suggested, is the best way.
not a fan of allowing users to create custom ones though, since we try to keep Confluence simple/stupid without too many options.

**Comment by HitcherUK** [comment]
> i think content provided by playlists, like @HitcherUK suggested, is the best way.
> not a fan of allowing users to create custom ones though, since we try to keep Confluence simple/stupid without too many options.

Confluence does allow a custom playlist to be enable at startup. ;)

**Comment by phil65** [comment]
@HitcherUK : https://github.com/xbmc/xbmc/pull/7215
;)

**Comment by ronie** [comment]
hehe @phil65 beat me to it :-)

**Comment by phil65** [comment]
I agree that we should get rid those properties, and smart playlists sound like a reasonable alternative.
There are a lot of ways to do it, it all depends on the requirements. I could sketch some of them:
1) Create a custom skin dialog to choose from a predefined list of smart playlists
2) Use something like the selectdialog functionality from script toolbox for that dialog ( I could strip out that functionality so that it is as light as possible)
3) Use Skin.SetFile on a predefined path containing the smart playlists (this doesnt allow translating though)

I think those are the most suited ones for this use case. I am not sold yet which one is the best, but skin code would definietely stay a lot cleaner if we allow some very basic python dialogs for these use cases.

**Comment by ronie** [comment]
4) add three smartplaylists to confluence (movies/episodes/albums) and hard-code the paths.

**Comment by phil65** [comment]
well I think it would be worth the 50whatever lines of code to give the users the possibility to choose between the most popular list types (latest, random, in progress)
But your suggestion would probably a first nice starter we can all agree on. ;)

**Comment by BigNoid** [comment]
Also -1 on this pr from my side. These properties need to be removed instead of extended.
As far as replacing goes, almost all video stuff can be done with smart playlists (except for recommended episodes). For music the smart playlists are rather limited and the functionality as is now, cant be replaced with a smpl or ```musicdb://``` path. It would need a script to actually play the album from the list when selecting it afaik as the former options just open the album in the music library

**Comment by ronie** [comment]
closing this as it's not the direction we want to go in.

**Pull request closed without merging**
