### PR TITLE
[travis-ci] Add travis linux support

### PR DESCRIPTION
**Pull request by hudokkow**
Investigating pvr add-ons integration problems and got sidetracked... ;)

See file notes for problems and current limitations.
@MartijnKaijser

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
i enabled travis so you could give it a try when you update this PR (i think)

**Comment by hudokkow** [comment]
Already tested (see https://travis-ci.org/hudokkow/xbmc/builds). Added badge to README.md

Backport coming or we're going to get into trouble with builds failing on Jarvis

**Comment by hudokkow** [comment]
All green!

**Comment by hudokkow** [comment]
@MartijnKaijser  you might want to disable "Build pushes". No need to build twice.

**Comment by MartijnKaijser** [comment]
Uhm you would actually want updated PRs build even if they are force pushed or was there some other issue?

**Comment by hudokkow** [comment]
Currently it builds when you PR and when you merge. If it builds the PR, no need to build again when merged. Waste of resources...

**Comment by MartijnKaijser** [comment]
Correct though it should rebuild when PR gets updated. Any way we'll find out

**Comment by hudokkow** [comment]
I think its more complicated than that and involves black/whitelisting branches according to the documentation. If you feel like testing it, just disable "Build pushes" under Settings and we'll see.
Anyway, lets not span everyone. We can continue this in slack/forum.

**Comment by tamland** [comment]
I didn't get the memo so sorry for asking obvious questions, but we have jenkins... that builds for all platforms...

**Comment by hudokkow** [comment]
Yes, we do. And may it live long and prosper. :grin: 
Think of it as an early warning system. If [pull requests] (https://travis-ci.org/xbmc/xbmc/pull_requests) fail on travis, they will fail on jenkins.

**Comment by MartijnKaijser** [comment]
See it as additional first check cause travis only build linux atm. So we certainly still need Jenkins for all platforms and additionally to also create the actual binaries.
Also it's near zero maintenance (only need some build instruction adjustments) and not run on our servers

**Comment by Razzeee** [comment]
if we can get it to build on all platforms, we could build binary addons only on travis. And remove them from the jarvis build. Might solve builds/merges failing due to addons not building. Which is out of our hands anyway?

**Comment by hudokkow** [comment]
@Razzeee, that's a great idea!

**Comment by AchimTuran** [comment]
@hudokkow 
Cool that we now have Travis CI for our xbmc repo. Awesome work :+1: 

@Razzeee 
> If we can get it to build on all platforms, we could build binary addons only on travis. And remove them from the jarvis build. Might solve builds/merges failing due to addons not building. Which is out of our hands anyway?

That's the plan for AudioDSP since I have read about CI services, but I couldn't find the time to set up to whole chain. Furthermore it will give us further posibilities like deploying add-ons without normal releases, developing and testing for many platforms without setting up the whole environment and give 3rd party developers the possibility to build their add-ons without jenkins access.

We could use https://bintray.com/ for deploying and managing our versions.

@ace20022 
> Just in case you didn't know and it's reasonable/planned to add something similar for win: http://www.appveyor.com/ (found by accident)

Currently I'm trying to set it up for our AudioDSP add-ons :smile:

**Comment by hudokkow** [comment]
It seems there's a bunch of us looking at the same. Feels good to share a vision! :+1:

**Pull request merged**
