### PR TITLE
Fix MacOSX 10.13 SDK build

### PR DESCRIPTION
**Pull request by lobermann**
Fix the build on MacOS when using the 10.13 SDK Version with XCode 9 but still using 10.12 MacOS

## Description
When updating XCode to the new version it also updated to the SDK Version 10.13, but the OS itself is still on 10.12 . After working on this issue for a day with @Rechi and @FernetMenta this is what I had to change to make the build work again.

What was fixed:

Error: `configure: error: error in configure of --with-sdk=10.13`
Fixed by adding SDK Version 10.13 Support

Error: libgcrypt: `The CPU Jitter random number generator must not be compiled with optimizations. See documentation. Use the compiler switch -O0 for compiling jitterentropy-base.c.`
Most likely caused by the recent update of libgcrypt. Fixed by patching the Makefile to also replace the -Og flag with -O0

Error:
````
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /Users/Shared/xbmc-depends/x86_64-darwin16.7.0-native/bin/cmake
  Expected in: /usr/lib/libSystem.B.dylib
````
Fixed build issue by updating CMake to 3.9.4, patching it to address the issues on macos and adding additional parameters for the native toolchain build.

I am not sure which of those changes we want to get into master right now. 
The SDK Part is no problem.
The libgcrypt should also not cause any issues on other systems, as the patch is only executed on MacOS. But I can only test it on my mac.
The CMake update worked by just increasing the version number and built without issues. So I assume it is OK for other systems also. I think Windows is also using those dependencies, or? Needs to be tested. Also, the CMake tar.gz needs to be put onto the mirror if merged.

## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by hudokkow** [comment]
Do we really need the latest cmake RC? I would prefer the latest stable release.

**Comment by lobermann** [comment]
@hudokkow unfortunately yes, as the issue is only fixed in 3.10, and not in 3.9.4 ... and trying to patch 3.9.4 did not work. Not sure when the first official release of 3.10 will be.

**Comment by hudokkow** [comment]
OK. Thanks.

**Comment by FernetMenta** [comment]
I don't thinnk we should bump cmake to a non-released version. Maybe there are not even 10 people out there who run XCode 9 on OSX 10.12 and want to build Kodi. Those can easily patch cmake to rc while all others use a stable release.

**Comment by MrMC** [comment]
https://github.com/MrMC/mrmc/commit/0cab5053593299cde210e22bbe75f69e4587c63d

**Comment by lobermann** [comment]
thanks to the patch from @Rechi it works now with 3.9.4.

**Review by Rechi — APPROVED** [review]

**Comment by Rechi** [comment]
@wsnipex cmake version bump is okay for you?

**Comment by lobermann** [comment]
@FernetMenta I think you have done this already, or? Can you share how to use the system cmake?

**Comment by FernetMenta** [comment]
@lobermann I hacked Makefile.include after having run configure. I think cmake-native should be made configurable to this list: https://github.com/xbmc/xbmc/blob/master/tools/depends/native/Makefile#L7

**Comment by wsnipex** [comment]
to use cmake from system, you'd have to add a configure switch and cmake check to depends/configure.ac and fixup https://github.com/xbmc/xbmc/blob/master/tools/depends/Makefile.include.in#L67 to use it

**Comment by Memphiz** [comment]
Damn - i didn't realise that this PR is up. I worked on that during devcon (using xcode9 for osx and ios) and figured the same stuff (and a bit more) out again. Not sure how this will influence now ... which PR do we want to use then? :)

**Comment by Memphiz** [comment]
My approach is btw to use a deploymenttarget to the natvie build which matches the running osx version. This ensures that native binaries that are built with newer SDKs are able to run on the host.

**Comment by Memphiz** [comment]
Also the cmake bump is not needed - the patch is enough ...

**Comment by Memphiz** [comment]
i will merge this PR with mine - because this one is to osx specific and leaves out ios to much. I do a new PR with the merged state ...

**Comment by Memphiz** [comment]
Please continue here:

https://github.com/xbmc/xbmc/pull/12969

**Pull request closed without merging**
