### PR TITLE
[TexturePacker] - fix decode of png files with indexed color palette - t...

### PR DESCRIPTION
**Pull request by Memphiz**
...hx @BigNoid for reporting the problem

@Montellese or @Karlson2k please do a new windows package with this change.

info ping to @uNiversaI

### CODE REVIEW

**Comment by Memphiz** [comment]
jenkins build this please

**Comment by uNiversaI** [comment]
Sure, upload new build for windows into mirrors and link? you doing version bump since its a bug fix? Ill update whatever needed. thx for ping

**Comment by Memphiz** [comment]
Built the package - will upload this evening...

**Comment by Memphiz** [comment]
@uNiversaI @BigNoid http://mirrors.kodi.tv/build-deps//win32/texturepacker-1.0.2-win32.7z

**Comment by Memphiz** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
ios error unrelated...

**Comment by uNiversaI** [comment]
Thx @Memphiz updated http://kodi.wiki/view/TexturePacker

**Comment by Memphiz** [comment]
thx

**Pull request merged**
