### PR TITLE
[swig] Bump to 3.0.12

### PR DESCRIPTION
**Pull request by hudokkow**
## Description
Update swig to latest release

## Motivation and Context
Keep deps up-to-date

## How Has This Been Tested?
Not at all.

### CODE REVIEW

**Comment by hudokkow** [comment]
jenkins build this please

**Comment by hudokkow** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by hudokkow** [comment]
It won't build. There's some dep missing that became mandatory in 3.0.11. Forgot the name but I have some build logs with this somewhere in my disk.
I need a vacation. And a vacation of the vacation after that.

**Comment by Rechi** [comment]
wrong file was uploaded to the mirrors
tested it on osx and linux and is now working

jenkins build this please

**Comment by hudokkow** [comment]
Ah!
Thx @Rechi

**Comment by Rechi** [comment]
@wsnipex please have a look, its working now

**Comment by wsnipex** [comment]
fine for me.

**Pull request merged**
