### PR TITLE
[pvr] drop channel guide button from info dialog + add channel guide to context menu

### PR DESCRIPTION
**Pull request by xhaggi**
First, this PR drops the channel guide button (introduced by myself) from the guide info dialog, because normally you open the pvr guide info dialog from within the channel guide dialog not the other way around. In that case it'll end-up in an unsightly UI workflow.

Second, I added a new entry "Channel guide" to the context menu for all channel items with existing EPG data. You can now reach the channel guide from there.

## Motivation and Context

Unsightly UI workflow.

## How Has This Been Tested?

Runtime tested on MacOS

### CODE REVIEW

**Comment by ksooo** [comment]
You should implement the new context menu entry using the new context menu system (See PVRContextMenus.cpp).  Although there are still a few leftovers of the old system in pvr code we should not introduce new "old way" entries.

**Comment by xhaggi** [comment]
Thank you for pointing me to the right place 👍 Will move it over.

**Comment by xhaggi** [comment]
@ksooo updated

**Comment by xhaggi** [comment]
I've done some tests and it works on homescreen + channel window.

**Comment by xhaggi** [comment]
I've changed the condition in IsVisible so the context entry is only shown if epg data exists.

**Comment by xhaggi** [comment]
@phil65 or @ronie I've changed estuary to show colored background images (same as it's done for pvr guide info dialog) if the channel guide is used outside fullscreen. Could one of you taking a look.

**Comment by ksooo** [comment]
I can only speak for the non-Estuary changes, which are looking good.

**Comment by xhaggi** [comment]
@ksooo thx for reviewing

**Comment by phil65** [comment]
Skin change looks fine.

**Review by phil65 — APPROVED** [review]

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by xhaggi** [comment]
Build errors are unrelated.

**Pull request merged**
