### PR TITLE
[Depends] Replace distribute with setuptools

### PR DESCRIPTION
**Pull request by mrdominuzq**
## Description

setuptools belongs in native for it to be used

## Motivation and Context

We use native python to compile so setuptools belongs there

## How Has This Been Tested?

Only build tested for android
## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by wsnipex** [comment]
how is that supposed to work? We need target setuptools for cross compiling binary modules like pillow and cryptodome. On which platform did you test this?

**Comment by mrdominuzq** [comment]
You should be using distutilscross for that, but that package are not even used. Native python is used to build but pillow and cryptodome depends on setuptools modules to build. But try to delete the patch from cryptodome and compile, You Will see that it cant find setuptools.

**Comment by mrdominuzq** [comment]
Did compiling on Ubuntu mate 16.04

**Comment by jaylinski** [comment]
Can somebody explain to me how `distribute` is still working? The version used in Kodi is from 2011 (https://pypi.org/project/distribute/0.6.21/), was last updated in 2013 and doesn't even support the current Python version (3.8).

Doing a depends build on Ubuntu 18.04 gives me the following error:
```
Setuptools installation detected at /opt/xbmc-deps/x86_64-linux-gnu-native/lib/python3.7/site-packages/setuptools-41.0.1.post20200209-py3.7.egg
Not patching, --root or --prefix is installing Distribute in another location
running install
Traceback (most recent call last):
  File "setup.py", line 211, in <module>
    scripts = scripts,
  File "/opt/xbmc-deps/x86_64-linux-gnu-native/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/xbmc-deps/x86_64-linux-gnu-native/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/xbmc-deps/x86_64-linux-gnu-native/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "build/src/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "build/src/setuptools/command/install.py", line 82, in do_egg_install
    easy_install = self.distribution.get_command_class('easy_install')
  File "build/src/setuptools/dist.py", line 362, in get_command_class
    self.cmdclass[command] = cmdclass = ep.load()
  File "build/src/pkg_resources.py", line 1992, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "build/src/setuptools/command/easy_install.py", line 25, in <module>
    from setuptools.package_index import PackageIndex
  File "build/src/setuptools/package_index.py", line 157, in <module>
    sys.version[:3], require('distribute')[0].version
  File "build/src/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "build/src/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: distribute
Makefile:22: recipe for target '.installed-x86_64-linux-native' failed
make[2]: *** [.installed-x86_64-linux-native] Error 1
make[2]: Leaving directory '/root/kodi/tools/depends/native/distribute'
Makefile:61: recipe for target 'distribute' failed
make[1]: *** [distribute] Error 2
```

Would be nice to get this rebased an merged. :)

**Comment by jaylinski** [comment]
@mrdominuzq Are you still active here on GitHub? Otherwise I'll try to open a rebased PR based on this one.

**Comment by mrdominuzq** [comment]
still active :) but not enough time :( but feel free to make a PR. :)

**Comment by jaylinski** [comment]
@mrdominuzq I think this PR can now be closed, since #17360 got merged.

**Comment by mrdominuzq** [comment]
Perfect :) if You have the time You should check distutilcross not bring used and setuptools target shouldnt be there :)

**Pull request closed without merging**
