### PR TITLE
[JSON]Player.GetActivePlayers return "playertype" (external, remote, internal) 

### PR DESCRIPTION
**Pull request by popy2k14**
## Description
Would be good to return the playertype "external", "remote" or "internal" when external/remote/internal player is active, so the developer on the other side can decide todo other things, like remap buttons, ....

## Motivation and Context
I want to control MPC-HC and know that the external player is active.

## How Has This Been Tested?
Tested on my dev machine and main htpc.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X ] My change requires a change to the documentation, either Doxygen or wiki
**- [ ] I have updated the documentation accordingly** must be done
- [X ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [X ] I have added tests to cover my change
- [X ] All new and existing tests passed

### CODE REVIEW

**Comment by DaveTBlake** [comment]
Thank you for this contribution to Kodi especially the JSON API.  It makes a sensible follow on from https://github.com/xbmc/xbmc/pull/13775 which exposed this information to the Python API, it is good to try and keep the JSON API in line with the Python one.

However a few changes are needed before this is ready. Previously GetActivePlayers returned what kind of media was being played, with this change you do not know whether the external player is playing music or video. Adding to an enumerated type in that way is also a breaking change, and this information is better added in a non-breaking way then it can be part of v18.

Happy to work with you to achieve this, but don't have time just now. I will be able to give better guidence later.



Once we have come up with a way to add this in a non-breaking way
- the schema version needs to be updated to communicate to consumers that the API has changed
- the values of enmerated type are also a part of the schema, that would need to change inline with the code. adding to an enumberated type is also a breaking change

**Comment by popy2k14** [comment]
ok, thanks. Waiting for guidence.

**Comment by DaveTBlake** [comment]
A bit longer than I expected @popy2k14 
How I think this needs to be approached, espcially the schema additions,  is probably best shown by looking at this is my repo https://github.com/xbmc/xbmc/compare/master...DaveTBlake:JSONPlayerExt#diff-9c2a40e0c0359d72671c8181d11db75dR1073

Adding a field to the results array is a non-breaking change and backwards compatible - previous use of the method is preserved . Values are also consistent with the player type returned by GetPlayers, and the "remote" players (e.g. via upnp) covered too for completeness.

I suggest that you update this PR (forced push) to match that, and do some testing of course to validate

**Comment by Rechi** [comment]
jenkins build this please

**Comment by popy2k14** [comment]
Thanks a lot, will look into it  tomorrow and change the PR accordingly.

**Comment by popy2k14** [comment]
@DaveTBlake thanks a lot for diff. Thats a lot better and not breaking anything.
I have changed the name of the PR and the code.
Also tested this on my dev machine and working like it should.
Can you please merge this to current master?

Thanks a lot
pOpY

**Review by DaveTBlake — APPROVED** [review]
Thanks @popy2k14 this is a useful non-breaking change that keeps JSON in line with the data exposed via Python API.
I also have edited the title to make it easier to spot JSON when looking through Git history

**Comment by popy2k14** [comment]
Thanks!

**Pull request merged**
