### PR TITLE
filesystem: add xbt:// implementation and support loading image resources from XBT files

### PR DESCRIPTION
**Pull request by Montellese**
@MartijnKaijser and @ronie asked me if it would be possible to support loading images from image resource addons from an XBT file which would greatly reduce the size of those image resource addons.

Since I had (and still have) no real clue how our texture packer and the whole XBT stuff works I just jumped in and obviously figured out that the logic responsible for loading the skin images from the respective XBT is pretty much hardcoded. So I thought it might be easiest (also for testing) to implement a `xbt://` VFS (similar to `zip://`) which would support reading XBT files and extracting single files/images from it.

So this is what I added up to now:
- refactored the XBTF reader/parser implementation a bit
- added some helper methods to the XBTF logic
- generalized `CZipDirectory`'s "directorization" logic into a `XFILE::Directorize` template which takes a list of file entries with full paths and analyzes their path to figure out and create the proper directory structure.
- add `CXbtManager` to cache already parsed XBT files
- added `CXbtDirectory` and `CXbtFile` VFS implementations
- extended `CResource` to support getting the full path to a resource file instead of doing that in `CResourceFile`
- extended `CImageResource` to check if a image resource file exists and if not, check if there's a `Textures.xbt` file and if it contains a matching image file instead
- extended `CBaseTexture::LoadFromFileInternal() to handle loading textures from`xbt://` paths differently because we can directly load the actual texture from the XBT file and don't have to go through our image loader (which wouldn't work anyway)

There are also a few things that need to be considered/decided/resolved before this can be merged:
- [ ] I'm not very happy with having to add this special handling into `CBaseTexture` but I'm not familiar with this code so if anyone familiar can point me to a better place that would be very appreciated.
- [x] There are a few TODOs in `CXbtFile` because I haven't (fully) implemented `Seek()` and `Stat()` yet. Do we have any documentation on the different fields that must/should be filled in `Stat()`?
- [x] Right now any loaded XBT will be cached indefinitely in `CXbtManager`. We need to decide whether that's ok or find a way to either uncache them after a certain time or find another criteria for uncaching.
- [x] Updating a cached XBT in an image resource addon currently isn't detected and doesn't result in a re-caching.

### CODE REVIEW

**Comment by Montellese** [comment]
Thanks to @Memphiz for the very fast Xcode sync (and I didn't even have to ask for it). jenkins build this please

**Comment by Montellese** [comment]
jenkins build this please

**Comment by Montellese** [comment]
Linux build should be fixed now. jenkins build this please

**Comment by ronie** [comment]
> extended CImageResource to check if a image resource file exists and if not, check if there's a Textures.xbt file and if it contains a matching image file instead

this should be the other way around, no?
for skins we first check the textures.xbt file for images, if it does not contain the requested image,
we look for the image outside of the .xbt file.

**Comment by Montellese** [comment]
@ronie: Well checking if the `Textures.xbt` exists is cheap but checking if a file exists inside the `Textures.xbt` is not. I wasn't sure if we supported a mix of `Textures.xbt` and normal files in which case this should be the faster approach. If it's always either `Textures.xbt` or normal files I can turn it around.

**Comment by MartijnKaijser** [comment]
It's always first XBT then if file not available see if there's  a normal file. Would it be an option to have build some index list on first load which you can check against before going into the xbt file?

**Comment by Montellese** [comment]
Where would the index come from without reading the XBT? With skins it's easy because when loading the skin we know exactly that we will use the skin's XBT and also a theme-specific XBT depending on the user's settings. But with resource addons we have no clue if the XBT will ever be used.

I haven't done any performance measurements so it might not be noticably slower so I can change the logic around.

**Comment by akva2** [comment]
you introduce a manager. have it manage (the cache of xbt's), create the cache on first access? it's not gonna be a huge amount of data. it's how archives work.

**Comment by Montellese** [comment]
@akva2: That's basically how it works right now i.e. opening an XBT goes through the manager and if it hasn't cached the XBT's content yet it does so when first asked for it. What is missing is reloading of changed XBTs (which is/was present for skin XBTs so the logic already exists).

**Comment by Montellese** [comment]
Changed the logic around to first look for and in the XBT and then fall back to normal files. I also adjusted the implementation of `CResourceImage` to remove a cached XBT from `CXbtManager` before the addon is uninstalled/updated.

**Comment by Montellese** [comment]
jenkins build this please

**Comment by Montellese** [comment]
jenkins build this please

**Comment by Montellese** [comment]
Only binary addons failed on Linux. Everything else is fine.

**Comment by MartijnKaijser** [comment]
tested and worked yesterday

**Comment by Montellese** [comment]
@MartijnKaijser: Thanks for testing and for the feedback. Did you also test the TexturePacker? Does it need a version bump or something?

Would be nice if someone could review the code, especially the changes in `CBaseTexture` and the implementation of `CXbtFile`.

**Comment by Montellese** [comment]
jenkins build this please

**Comment by hudokkow** [comment]
OSX32 failure unrelated (github pull crap).
Lets try again and jenkins build this please

**Comment by Montellese** [comment]
Failures are fully binary addon related. Anyone willing to do a review or is this good to go?

**Comment by MartijnKaijser** [comment]
@Paxxi @mkortstiege ?

**Comment by mkortstiege** [comment]
IMO good to go. In case issue pop up we can fix em afterwards.

**Comment by ronie** [comment]
this doesn't seem to work (at all) on my end:
http://xbmclogs.com/palinttkk

screenshot000

**Comment by Montellese** [comment]
@ronie: Thanks for the report. See #7810 for a fix of `TexturePacker` (Kodi is working fine).

**Comment by ronie** [comment]
@Montellese i got a report on the forum that this PR also breaks skin themes.
the option to select a different theme is now always greyed out in appearance settings, even though a skin contains multiple themes.

**Comment by Montellese** [comment]
@ronie: This PR doesn't touch any settings related code at all so I'm pretty sure that's no the reason. But IIRC there has been an issue with skin themes settings for a while.

**Comment by uNiversaI** [comment]
Skin themes use to work just fine until this.

@Montellese Default skin can no longer load individually named xbt. After this PR the theme selection is now disabled totally in skin, it will load the xbt named **Textures.xbt** only, so its not the texture packer changes.
screenshot002

The textures created with the new texturepacker seem to work OK.

**Comment by ronie** [comment]
> @ronie: This PR doesn't touch any settings related code at all so I'm pretty sure that's no the reason.

@montellese themes *are* xbt files and this PR has a lot to do with that ;-)

**Comment by Montellese** [comment]
See #7818.

**Pull request merged**
