### PR TITLE
FFmpeg decoder GUI control

### PR DESCRIPTION
**Pull request by gominoa**
Here's a FFmpeg GUI control. It hangs off GUIImage so works exactly the same in a skin like so:

```
<control type="ffmpeg">
  <left>480</left>
  <top>100</top>
  <width>320</width>
  <height>180</height>
  <texture fallback="whateves.jpg">/some/video/file.mp4</texture>
</control>
```

Since it is GUIImage, you should be able to use any tag that works on "image" control (Not that I've tried it)

Here's a demo video (https://vid.me/Suu) showing the Confluence background replaced with 4 "ffmpeg" controls. The background/left/middle videos are .avi/.swf/.mp4 respectively. The right blue is a bad filename to show we get fallback= for free.

It adds ffmpeg support to GUITexture, whos job is to grab a texture from somewhere (currently g_TextureManager or g_largeTextureManager) and put it on screen. Give it one more place to grab from (FFmpegVideoDecoder) and a new flag (useFFmpeg) in CTextureInfo same as useLarge and g_largeTextureManager. Add "ffmpeg" to GUIControlFactory aliased to GUICONTROL_IMAGE same as "largeimage" is aliased. Video is opened in CGUITextureBase::AllocResources() and closed in CGUITextureBase::FreeResources(). GUITexture already handles animated GIFs with UpdateAnimFrame() so add UpdateFFmpeg() to handle decoding.

You get everything "image" can do for free, with a video instead of a picture (fine print: software decode). It should be easy to make a screensaver and a visualization out of this. They might as well be native as going through the addon layer would be silly. Or push it off on the skin guys since they can invoke a video themselves. Put a "ffmpeg" instead of "visualisation", boom done. Plus you can delete 'karaokevideobackground.cpp' (which is twice the size of this commit) because karaoke can already use viz as background. Wheeeeeee

### CODE REVIEW

**Comment by topfs2** [comment]
Thinking on @FernetMenta point, wouldn't a nicer approach be to merge it in under the image control? So that if a device is to slow we use the fallback?

**Comment by topfs2** [comment]
Because it would be nice to add it in for I** even if just as a limited test, I mean from this PR its up to the skin if they want to use it and they can do a skin setting AFAIK if they want

**Comment by FernetMenta** [comment]
FFmpegVideoDecoder is an architectural flaw and will die. I don't want any other components make use of this because users will cry when we drop features.

**Comment by FernetMenta** [comment]
apart from this ffmpeg should not linked with GuiBaseTexture

**Comment by topfs2** [comment]
Do we have any other internal decoder possible to hook into instead? Seems sad for such a great feature to vanish because of cleaning :)

**Comment by FernetMenta** [comment]
It does not vanish only because of cleaning. Hacking video deciding into gui texture alone is no-go. btw: I am not aware of any post in the forum requested such a feature.

**Comment by topfs2** [comment]
I would personally love it :) but for me it would be enough with apng which
doesn't require ffmpeg.

**Comment by zag2me** [comment]
Can we make a decision as to this or the animated Gif/PNG PR then?

This has come up repeatedly over the past 5 years and there have been a multiple attempts to get some king of animated backgrounds or splash screens. None have got anywhere yet which is a shame especially when users have been working so hard on the intro animations recently.

**Comment by MartijnKaijser** [comment]
i think we should care more about stability and proper startup logic than some random user wanting to have a animated gif as startup.

**Comment by FernetMenta** [comment]
As already explained, there are a couple of things which are wrong with this PR. All behavior needs to be encapsulated into a separate control, not hacked into gui texture. The render thread must not be hijacked for video decoding.

**Pull request closed without merging**
