### PR TITLE
[addon] prevent publicate of C++ functions / classes from headers, fix old to new pvr update and cleanup General parts

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description
This fix the stupid clang feature about export of C++ parts within addon headers, where a on addon A compiled class or function becomes public on addon B and this call A instead his.

Further is the General part cleaned up and "C++" / "C" parts separated.

Also is a change added to allow two different addon type ID's, to allow better change and update of it.

**Addons not need a recompile!** only want to have them in before the rest of PVR's becomes updated.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ksooo** [comment]
The title of this PR is a bit misleading, as there is only one commit out of 6 which is PVR related.

**Review by phunkyfish — APPROVED** [review]
Looks good, also runtime tested and addons now only call their own contexts.

**Comment by ksooo** [comment]
@phunkyfish did you have the chance to test migration API level 6.x.x -> 7.0.0? For me, the old addons silently (!) disappeared from list of installed addons. I had to manually reinstall all my pvr client addons. If I understand correctly, this PR should contain a fix for that.

**Comment by phunkyfish** [comment]
I did not as I had already built and installed the PR before it was merged my my addon were already the new version.

**Comment by phunkyfish** [comment]
But to test this we would need this merged and to release the pvr addons right?

**Comment by ksooo** [comment]
> But to test this we would need this merged and to release the pvr addons right?

 @AlwinEsch ?

**Comment by AlwinEsch** [comment]
jenkins build this with addons please

**Review by ksooo — APPROVED** [review]
lgtm, runtime-tested, "incompatible addon disabled" dialog appears now.

**Pull request merged**
