### PR TITLE
[PVR] Addon API 5.0.0

### PR DESCRIPTION
**Pull request by ksooo**
I'd like to propose the following extensions and changes to the PVR Addon API for Krypton:
1. Introduce "no guilib used" return value for GetGUIAPIVersion and GetMininumGUIAPIVersion. Addons not using guilib now are able to state this, making it unnecessary to recompile these addons on bump of guilib. Discussion on this: https://github.com/kodi-pvr/pvr.hts/pull/153
   **Addon Maintainer Todo**: If GUI lib is not used by the addon,  GetGUIAPIVersion and GetMininumGUIAPIVersion should be changed to return "" (empty string). Additionally, addon.xml.in should be changed to not include <import addon="kodi.guilib" version="x.y.z"/>
2. Introduce a callback function that can used by addons to propagate connection state changes. This makes it possible to inform kodi (users) on events like "wrong credentials", "version mismatches", "connection loss", "successful reconnect after connection loss", ... all not possible today. Once an addon is loaded and connected, today there is no standard way to propagate those changes. Now, Kodi can react on changes, and not just by displaying a kai toast, but for example also by refetching addon properties (after reconnect, version numbers etc. may be different - because backend was just updateted, for example), which is done today exactly once after the addon has been loaded. Discussion on this: https://github.com/kodi-pvr/pvr.hts/pull/136#issuecomment-158338480
   **Addon Maintainer Todo**: no mandatory addon changes. recompile of the addon is sufficient. but feel free to use the new functionality to enhance your addon
3. Get rid of another magic number: Introduce EPG_TAG_INVALID_UID
   **Addon Maintainer Todo**: change all code that denotes an "invalid" epg tag uid to use the new constant for that purpose
4.  Remove unused method GetCurrentClientChannel
   **Addon Maintainer Todo**: yeah, remove that function
5. Introduce a callback function for asynchronous announcment of epg data transfer and event state changes. If an addon supports this feature PVR startup time can be improved signifilly. Kodi can be provided with "realtime" epg data (immediate UI chnages, no more operating on tags already deleted in the backend etc.). Reference implementation for pvr.hts gives quite impressive results. ;-)
   **Addon Maintainer Todo**: no mandatory addon changes. recompile of the addon is sufficient. but feel free to use the new functionality to enhance your addon
6. Add function SetEpgTimeFrame. This one is needed in conjunction with the new epg data callback. Knowing the epg time frame Kodi is interested in the addon can prevent to send dta to Kodi that are actually not of interest (reduces amount of data transferred from addon to Kodi).
   **Addon Maintainer Todo**: add this function. refer to https://github.com/xbmc/xbmc/pull/8736/files#diff-e73115cc4e6a02ef7029ee04f8ddd2a8R648 for implementation details
7. Add (optional) field PVR_RECORDING.iChannelUid. Today, it is very expensive to find an epg tag for a given recording due to organization of Kodi core data. Having the channel uid in addition to the epg event uid greatly improves performanace
   **Addon Maintainer Todo**: no mandatory changes, but highly recommended to fill this field, because it is a prerequisite for performance improvements on the kodi side of things
8. Remove unused PVR_SIGNAL_STATUS.d*Bitrate fields.
   **Addon Maintainer Todo**: yeah, just remove this if used in your addon
9. Get rid of another magic number: Introduce PVR_CHANNEL_INVALID_UID
   **Addon Maintainer Todo**: change all code that denotes an "invalid" channel uid to use the new constant for that purpose

@FernetMenta  @Jalle19 others... Feedback welcome

### CODE REVIEW

**Comment by xhaggi** [comment]
@ksooo thanks, nice additions, I like the idea with the new callback if the state is changed and everything else except the last commit ;)

**Comment by ksooo** [comment]
@xhaggi see my comment about the last commit. What you fear (not to see progress at all, because startup takes longer than 30 secs) is not true. ;-)

**Comment by xhaggi** [comment]
okay then it's fine by me :)

**Comment by ksooo** [comment]
Feedback from @xhaggi and @FernetMenta incorporated.

**Comment by ksooo** [comment]
jenkins build this please
(just for testing latest changes - no merge planned yet)

**Comment by ksooo** [comment]
More feedback from @xhaggi incorporated.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by xhaggi** [comment]
@ksooo great thanks :) next would be dropping the readytouse member but as you said it is something for a separate PR

**Comment by xhaggi** [comment]
and using more friendly method names like `IsConnected` instead of `ReadyToUse`

**Comment by ksooo** [comment]
> and using more friendly method names like IsConnected instead of ReadyToUse

yeah, but also in another PR

**Comment by ksooo** [comment]
jenkins build this please

**Comment by xhaggi** [comment]
sure :)

**Comment by Jalle19** [comment]
@ksooo while you're at it, could you remoe the `GetCurrentClientChannel()` method from the API? As far as I can tell Kodi doesn't use it anywhere.

**Comment by ksooo** [comment]
@Jalle19 good point. Are there more?

**Comment by Jalle19** [comment]
Not sure, I think that's the only one that's completely unused.

**Comment by Tolriq** [comment]
Sorry for hijacking but since PVR is really improving and users are really starting to use the full power of it, is there any interested to work on completing the JSON counterpart so that remotes can use that power too ?

Usually I'd talk with Montellese but he have no setup and no real interest in PVR.

**Comment by xhaggi** [comment]
@Tolriq could you please create a forum thread and tell us which parts we neee to expose over json-rpc. that would be highly appreciated.

**Comment by Tolriq** [comment]
http://forum.kodi.tv/showthread.php?tid=255793, will complete later today or tomorrow wife not happy I'm late :p

**Comment by msduketown** [comment]
Nice. Some pro-active API compatibility attempts by community members. @opdenkamp is wearn down and now KSOO and Xhaggi are the PVR-managers? Glad to find out..

**Comment by opdenkamp** [comment]
lol :) @ksooo is a team member nowadays and I'm still around. Just not very active because of other stuff ;)

**Comment by ksooo** [comment]
@Jalle19 Removal of GetCurrentClientChannel is now part of this PR.

**Comment by Glenn-1990** [comment]
@ksooo @Jalle19 
Shouldn't we need a method to control the player from a pvr addon, this to handle the stuck in fast forward/ backward when we reached the end of the timeshift buffer? 
This was discussed here:
https://github.com/kodi-pvr/pvr.hts/issues/144

In this way pvr clients can also unpause the stream when the maximal timeshift period was reached.

**Comment by ksooo** [comment]
Please do not use this PR for discussing ideas for API changes not already part of this PR. This will mess up things to much. ;-) 

I suggest to do this in the forum or in a separate PR which later can be cherry picked here.

**Comment by Jalle19** [comment]
@ksooo I have a very strong feeling that the three bitrate fields here are unused: https://github.com/xbmc/xbmc/blob/master/xbmc/addons/include/xbmc_pvr_types.h#L280

@FernetMenta perhaps you know better? Hard to tell if some skin is using it but I truly doubt it since AFAIK no addon supplies anything valid in these fields.

**Comment by FernetMenta** [comment]
@Jalle19 not sure either but I think so too.

**Comment by Jalle19** [comment]
@ksooo I think they're safe to remove, any breakage would be noticed quite quickly. @ronie do you have any magic tricks on how to grep all common skins for strings?

**Comment by ronie** [comment]
@Jalle19 you would need to check out the skin repo https://github.com/xbmc/repo-skins
and grep through the isengard/jarvis branches for those strings.

just let me know if i can help.

**Comment by Jalle19** [comment]
Should be safe to remove:

```
negge@palinski:/tmp/repo-skins$ grep -R actstreamvideobitrate *
negge@palinski:/tmp/repo-skins$ grep -R actstreamaudiobitrate *
negge@palinski:/tmp/repo-skins$ grep -R actstreamdolbybitrate *
negge@palinski:/tmp/repo-skins$
```

This is from the `jarvis` branch.

**Comment by FernetMenta** [comment]
@ksooo what do you plan to merge this? player requires a small API change because all addons no having a demuxer are broken atm.

**Comment by ksooo** [comment]
End of January, early February would be fine, but is not settled. Any chance your change is ready until then?

**Comment by FernetMenta** [comment]
> Any chance your change is ready until then

my change can be ready this afternoon :) it is actually a fix so I don't want to wait this long. are you ok if I apply it to v4 of the api?

**Comment by ksooo** [comment]
@FernetMenta v4 for your fix is fine by me.

**Comment by ksooo** [comment]
Rebased and introduced changes 5. to 8 (initial comment updated => https://github.com/xbmc/xbmc/pull/8736#issue-124593370).

Only cosmetical changes for item 1 to 4 - so no review needed for the related commit, we have done this already.

Review for item 5 to 8 is ofc very welcome. Maybe @Jalle19 @xhaggi mind taking a look?

**Comment by ksooo** [comment]
BTW, reference implementation for all changes can be found here: https://github.com/ksooo/pvr.hts/commits/pvr-api-5-0-0

Everything is runtime tested and in daily use for some weeks now.

**Comment by ksooo** [comment]
I would still really appreciate code review for item 5 to 8. I would be happy to be able to merge this PR by mid of February if nothing serious speaks against it. Don't be scared, lots of commits, yes, but item 1 to 4 alrady has been reviewed and for the others (5-8), most of them just contain a small number of changes lines of code - thus not much effort to review. 

Maybe @Jalle19 @xhaggi mind taking a look?

**Comment by ksooo** [comment]
Worked in @Jalle19's code review feedback. Thx, Sam.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Comment by Hedda** [comment]
@ksooo @Glenn-1990 Will Glenn's pull request #9045 also make it as part of this API update?

**Comment by ksooo** [comment]
> Will Glenn's pull request #9045 also make it as part of this API update? 

@Hedda #9045 does not include any PVR addon API changes.

**Comment by ksooo** [comment]
Rebased. Ready for merge.

**Comment by ksooo** [comment]
Note: pvr.dvblink and pvr.dvbviewer PRs are intentionally missing, because they require a "real" implementation of API 4.2.0 as they actually support timeshifting. Once 4.2.0 has been implemented for these addons I can submit PRs for 5.0.0

**Comment by ksooo** [comment]
If nobody objects I will merge this PR tomorrow.

**Comment by ksooo** [comment]
Rebased.

**Comment by ksooo** [comment]
jenkins build this please

**Pull request merged**
