### PR TITLE
[xbmc][fix] Change texture loading to not block skin updates

### PR DESCRIPTION
**Pull request by Paxxi**
redesign texture loading to avoid locking the texture bundle during skin reloads.
## Description

Cuts down on indirection and caching, simplifies design

Redesigned texture manager to cache the bundle textures which should avoid
opening the bundle too many times. This could probably lead to increased memory
usage for large skins.

The changes to the global handling is because of teardown ordering, having
CGUITextureManager as a global causes it to be destroyed after g_windowing and
we crash.

## Motivation and Context
We keep the Texture.xbt open for the duration of the process lifetime which causes
issues when trying to update the currently used skin.

## How Has This Been Tested?

Tested by upgrading metropolis skin on windows.
## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
not entirely sure who's suited for review, @FernetMenta maybe?

**Comment by MartijnKaijser** [comment]
@Montellese also did some refactoring some years ago

**Comment by MartijnKaijser** [comment]
Tested on Windows reloading/switching/updatings skins and also switching themes and no lockup so far.

**Comment by MartijnKaijser** [comment]
No issues as well on Android ARMv8a.  Any reviews?

jenkins build this please

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
@MilhouseVH could you include this in your build? Would like to see if it has any impact on performance, especially on the pi

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by popy2k14** [comment]
Any news on this?
Can i have a test build for windows?

**Comment by hudokkow** [comment]
@popy2k14 -> http://mirrors.kodi.tv/test-builds/win32/KodiSetup-20161105-18bea15-texture.exe

**Comment by popy2k14** [comment]
@hudokkow: thx, will try it in the afternoon and report back.

**Comment by popy2k14** [comment]
Sadly, the build does'nt start, it crashes on splash screen!
Also tested with estuary skin (manually edit the guisettings.xml).
After reverting to mast 04.11.2016 build kodi starts normal and both tested skins working.

Here is the log right before the crash: https://drive.google.com/file/d/0B4JpRMZvEb3saGh4aFFFUzdpeGc/view?usp=sharing

pOpY

**Comment by popy2k14** [comment]
Any news on this? Can i have a newer test build?

**Comment by da-anda** [comment]
is this one still needed?

**Pull request closed without merging**
