### PR TITLE
[tests] - move atomics tests from shared_ptr of thread array to vector o...

### PR DESCRIPTION
**Pull request by Memphiz**
...f shared_ptr of thread - fixes tests broken by change to c++11 shared pointers for clang 3.5

once unit tests on jenkins are ok we can merge this:

http://jenkins.kodi.tv/view/Helpers/job/TestMulti-All/123/

thx @notspiff

### CODE REVIEW

**Comment by Memphiz** [comment]
damn testsuite doesn't compile at all with osx clang - another thing which is broken due to c++11 change ... *w00t* ... and i wanted to go to bed early today ... i really hate this shit...

**Comment by hudokkow** [comment]
Please, don't despair. This is a much needed change.
I know, I know... don't make unnecessary comments on PRs.

**Comment by notspiff** [comment]
https://github.com/notspiff/kodi-cmake/commit/d956a6e1796d33668c8a672683866e49908146b5

i need(ed?) this for clang in my fork.

**Comment by Memphiz** [comment]
its more about planting "-DGTEST_USE_OWN_TR1_TUPLE=1" somewhere so that its used in kodi-test target only ... didn't figure out where to add it yet (beside to CXXFLAGS in Makefile.include which is a bit to generic imo :( ).

**Comment by notspiff** [comment]
set_target_properties(kodi-test PROPERTIES COMPILE_FLAGS -DGTEST_USE_OWN_TR1_TUPLE=1)

/hides

**Comment by Memphiz** [comment]
funny :)

**Comment by notspiff** [comment]
well, the simplicity of cmake code does make me smile ;P (that's the actual cmake code to do what you want).

**Comment by Memphiz** [comment]
@notspiff the problem is not doing this with automake - its about finding the right target which was obviously missnamed by the initial gtest author...

http://pastebin.com/vzS06hzj

**Comment by Memphiz** [comment]
cpt @notspiff mind testing this with your clang if i broke something?

**Comment by notspiff** [comment]
all good.

**Comment by Memphiz** [comment]
thx - jenkins tests are fine too - jenkins build and merge

@MartijnKaijser i guess the next thing that might break because of c++11 is the coverage build - right?

**Comment by MartijnKaijser** [comment]
Nope, coverity was just fine.

**Pull request merged**
