### PR TITLE
VideoPlayer: change time parameter of SeekTime from int to double

### PR DESCRIPTION
**Pull request by FernetMenta**
fixes i.e. seeking for PVR for cases where pts is larger than INT_MAX * 1000

pvr and inputstream addons need to be adapted

### CODE REVIEW

**Comment by FernetMenta** [comment]
@ksooo @peak3d @notspiff ping

**Comment by peak3d** [comment]
ack. Will change as soon as it its merged

**Comment by ksooo** [comment]
v17? Really?

**Comment by ksooo** [comment]
Who is going to adapt the pvr addons?

**Comment by ksooo** [comment]
You need to update https://github.com/xbmc/xbmc/blob/master/addons/xbmc.pvr/addon.xml for the pvr addon api bump.

**Comment by FernetMenta** [comment]
@ksooo pvr addons will break for a short while, I will do the changes online after this was merged. objections?

jenkins build this please

**Comment by ksooo** [comment]
> @ksooo pvr addons will break for a short while, I will do the changes online after this was merged. 

 thanks.

> objections?

 no, not from my side.

**Comment by notspiff** [comment]
@FernetMenta i am travelling. gave you push rights to inputstream.rtmp

**Comment by FernetMenta** [comment]
@notspiff ok, I will update rtmp too.

**Comment by ksooo** [comment]
@FernetMenta please do not forget to announce this api change in the forum.

@dennishamester ping, pvr.octonet needs to be adjusted

**Pull request merged**
