### PR TITLE
[addons][pvr] fix wrong header include, reduce CAddonDll use, take ch. uid for signal ask

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description

Few independent code parts taken from rework request to reduce his size.

Commit 1:
----------------------------
**[addons] change `xbmc_addon_types.h` include to `AddonBase.h` on `AddonStatusHandler.h`**

The xbmc_addon_types.h is obsolete and only include the AddonBase.h.
There was the last place in Kodi where it was included in his sources.

Commit 2:
-------------------------
**[addons][pvr] Pass in addon string ID and not its class**

This change is an independent part of the rework to switch to the new API.
This removes the use of `CAddonDll` in some places and gives its string
identification instead.

This is not critical since the called up positions only need this.

The background to this change is that in the multiple instance way the
addon class is no longer usable because it can also affect other instances.

The other reason is to reduce the rework request in size.

> **Note:** The complete addon handling way need to be reworked after PVR is changed (that all systems equal) and to have all Types secure in case of changes und updates. But to heavy to include on this or PVR rework. This request not change the way, it takes only the id instead class on some places.

Commit 3:
------------------------
**[addons][pvr] add GetPlayingChannelUniqueID to playback state**

This add `int CPVRPlaybackState::GetPlayingChannelUniqueID() const` to get
on wanted places the currently running PVR channel unique identifier.

This are also now used by "CPVRGUIInfo::UpdateQualityData()" and
`CPVRGUIInfo::UpdateDescrambleData()` and this `!IsPlayingRecording()`
becomes replaced with them.

`GetPlayingChannelUniqueID()` match more the wanted target as to ask
that is not a recording.

Further is this value also needed on reworked PVR system to pass to addon.
But this change here is mostly independent and thats why separated

## Motivation and Context
To reduce amount of changes on https://github.com/xbmc/xbmc/pull/16485

After this is in a rebase of #16485 becomes done

## How Has This Been Tested?
Doing the next days check on addons.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Tested and works normal, for signal info

Bildschirmfoto von 2020-03-23 14-04-18

**Review by phunkyfish — APPROVED** [review]
I also just ran it this morning and everything appears ok. Sorry for the delay in getting around to this!

**Comment by AlwinEsch** [comment]
Hi @phunkyfish, NP, 2 days after request start are no delay for me :smile:, thanks a lot for test!

**Review by ksooo — APPROVED** [review]
If it works...

**Pull request merged**
