### PR TITLE
VideoPlayer: fix relative seeks

### PR DESCRIPTION
**Pull request by FernetMenta**
Holding down the key generates many relative seek commands. If the calling thread is blocked, there is not enough time for rendering.
Now VideoPlayer processes those messages asynchronously.

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by popcornmix** [comment]
You'll need a fix like: https://github.com/popcornmix/xbmc/commit/459aebfcb6dd7833590917e5908a87d0b971b400
Should I see any change with this PR? Behaviour when holding down right hasn't changed (video plays at normal speed until released).

**Comment by FernetMenta** [comment]
I will pick the omx fix, thanks

> video plays at normal speed until released

if this is the case, something is wrong with mmal or input. a seek flushes demux queue and decoder. does player get seek commands?

**Comment by popcornmix** [comment]
I've added a log message to SeekTimeRelative, but I only see that when I release the key.
The seek bar does move while I'm holding the key down, and it does seek to the expected place when I release.
http://paste.ubuntu.com/23305122/

**Comment by FernetMenta** [comment]
Where did you add the log? Maybe in issue in SeekHandler. Could you add some logging to this chain of functions please. Something must go wrong before it comes to VideoPlayer.

**Comment by da-anda** [comment]
might you guys be talking about different things? Multiple skips steps vs only one with instant seek (aka old behavior before skip steps)?

**Comment by FernetMenta** [comment]
@da-anda use case here is having additive seek disabled by setting delay to zero

**Comment by popcornmix** [comment]
Log was in SeekTimeRelative.
I've found the issue. I had set a single seek step forwards and backwards but not zeroed the skip delay. I had imagined that with only a single seek step then the delay would be ignored (what does it mean in this case?)
I now get ~10 log message per second from SeekTimeRelative. Player shows 0% buffering constantly while holding the seek key down, but you do get one or two video frames displayed about once per second.

Seeking is much slower when delay is set to 0.
With delay=750ms and step=30s I can seek from start to end of 42 minute video in 7 seconds.
With delay=0ms and step=30s I can seek from start to end of 42 minute video in 114 seconds.

I assume that in the first case we get ~10 seeks of 30s per second.
In the second I assume we only update the current seek position when video frame emerge, so ~1 seek of 30s per second.

Log file with delay set to zero.
http://paste.ubuntu.com/23307782/

**Comment by FernetMenta** [comment]
> Seeking is much slower when delay is set to 0.
With delay=750ms and step=30s I can seek from start to end of 42 minute video in 7 seconds.
With delay=0ms and step=30s I can seek from start to end of 42 minute video in 114 seconds.

That's expected behaviour, isn't it? Before being able to do the next jump you have to land first.

> but you do get one or two video frames displayed about once per second.

That's a remaining issue. Every relative seek should result in a displayed video frame.

**Comment by popcornmix** [comment]
> That's expected behaviour, isn't it? Before being able to do the next jump you have to land first.

It's one possible expected behaviour...
Compare with 8x fast forward. The clock moves at 8x real time regardless of how long it is taking the seek/demux/decode/render paths. On a slower platform/network/disk the clock moves at a fixed rate but you get fewer decoder video frames during the process.
The repeated skip could behave the same way. The number of 30s seeks per second depends on the key repeat rate. Skipping from one end of a one hour video could always take the same time, with speed of platform determining the time between video frames actually appearing.

But that is probably a harder system to implement, and isn't a blocker for this PR.

**Comment by FernetMenta** [comment]
if all you want to achieve is getting fast from one end to the other, you should use additive seek or big step forward. not producing a picture after a relative seek makes no sense bacause you don't know where you are.

**Comment by popcornmix** [comment]
No problem - as long as the behaviour is expected I'm happy.

**Comment by FernetMenta** [comment]
jenkins build this please

**Pull request merged**
