### PR TITLE
VTB on OSX: fix flickering video caused by buffer overwrite

### PR DESCRIPTION
**Pull request by FernetMenta**
see title. This applies the same concept we already have for vdpau and vaapi.

### CODE REVIEW

**Comment by FernetMenta** [comment]
@Memphiz I think iOS has the same issue. There you could use the standard functions glFenceSync that are available for GLES.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please  (github died for awhile)

**Comment by MartijnKaijser** [comment]
ignore the win32 fail

**Comment by Memphiz** [comment]
Nice - great work - thx - so thats the fix for the stuttering issue?

**Comment by FernetMenta** [comment]
@Memphiz "stuttering" is not the right term if you mean this case: http://forum.kodi.tv/showthread.php?tid=281517

"choppy" is better suited here. But since there a always multiple definitions out there, I requested a video for better diagnosis :)

jenkins build this please

**Comment by MrMC** [comment]
might want to check the ref count on m_vtbbuf, vda/vtb will not re-use it if greater than one.

**Comment by popcornmix** [comment]
glFenceSync is GLES3 only, not GLES2:
https://www.khronos.org/opengles/sdk/docs/man3/html/glFenceSync.xhtml

**Comment by FernetMenta** [comment]
> might want to check the ref count on m_vtbbuf, vda/vtb will not re-use it if greater than one.

that is not the problem here

**Comment by MrMC** [comment]
ok mr.expert :)

**Pull request merged**
