### PR TITLE
Move to C++11; use as much std:: instead of boost:: as possible

### PR DESCRIPTION
**Pull request by koying**
This solves crashes on x86 droid (at least on Nexus Player).

Should work on all GCC platforms.
@Memphiz @Karlson2k Could you check if it's feasible on your platforms, please

### CODE REVIEW

**Comment by koying** [comment]
There's no rush, so I suggest to PR vs my branch for core and we will wait
for your green light for the side stuff you need to do.

**Comment by Memphiz** [comment]
for reference:

https://github.com/Memphiz/xbmc/commits/c%2B%2B11

and

https://github.com/opdenkamp/xbmc-pvr-addons/pull/400

**Comment by MartijnKaijser** [comment]
Guess this is not something we want in our first alpha build right? Which means we need to custom compile android x86 with this PR if at all possible.

**Comment by Memphiz** [comment]
it needs sdk bumps for darwin before it can hit mainline ...

**Comment by MartijnKaijser** [comment]
So a 14.1 release ;) 
OK let's do that first and then bump and hold back the alpha release as we need this for Android

**Comment by topfs2** [comment]
Imo for I*** it can be in alpha, the sooner the better
Den 28 jan 2015 22:31 skrev "Martijn Kaijser" <notifications@github.com>:

**Comment by koying** [comment]
Ping me when you're OK to merge. There will be a bit of work to rebase
properly to latest master ;)
Le 29 janv. 2015 08:06, "Tobias Arrskog" <notifications@github.com> a écrit
:

**Comment by Karlson2k** [comment]
@koying This will fix win32 "Release" builds: https://github.com/Karlson2k/xbmc/commit/6e1b78f6c34a18a3395a3259e4d19bfda791d1a7

**Comment by koying** [comment]
Shouldn't we use assert.h rather than cassert? Not quite clear to me which one is preferred in c++11...

**Comment by topfs2** [comment]
Afaik in CPP you should use the cfoo over foo.h.
Den 29 jan 2015 13:59 skrev "Chris Browet" <notifications@github.com>:

**Comment by MartijnKaijser** [comment]
sdk bumps are done ;)

**Comment by Memphiz** [comment]
We need somehow take care of letting users know that once this PR is merged our minimum system requirements are bumped to osx 10.7 and ios 5.1 - any idea how to do so?

**Comment by koying** [comment]
@Karlson2k Could you rebase your patch vs. latest master, please

**Comment by koying** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
At least for osx and ios builderror is because of newly introduced "C++11 requires a space between literal and identifier" in the pvr addons *sigh*

**Comment by tamland** [comment]
So I guess gcc 4.6 compatibility have to be kept, since that's what jenkins' using? There *is* a few features missing, such as override and member initializers.

**Comment by koying** [comment]
jenkins build this please

**Comment by koying** [comment]
jenkins build this please

**Comment by koying** [comment]
No-go with gcc 4.6, so this is a problem indeed for Linux

**Comment by tamland** [comment]
Because that autoconf check obviously use features not available in 4.6. Like override. Drop it

**Comment by wsnipex** [comment]
if we really want to, we could even bump our jenkins slave up to gcc-4-9: https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test?field.series_filter=precise

**Comment by koying** [comment]
jenkins build this please

**Comment by Karlson2k** [comment]
Why not to use some configure tests and local mapping?
If std::shared_ptr is available - use it, if not - use boost:: , same for others/
We can hide real implementation with some `#define ` or local class `utils::shared_ptr`.

**Comment by MartijnKaijser** [comment]
would be great if we could get this in for extensive testing before window ends

**Comment by wsnipex** [comment]
ping. should we update our build slaves to gcc 4.8 and simply drop build support for older versions? Didn't check if we need a newer libc as well though(probably)

**Comment by tamland** [comment]
last build succeed on linux. don't think that will be necessary

**Comment by koying** [comment]
Indeed. We don't use "core" c++11 stuff, and the m4 wasn't actually compatible with c++0x, which is fine for now (see f5dbbbbfe53e2f90161ad50407730600d5fce3a7).
I'm stuck with OSX, which needs a pvr-addons patch. @Memphiz, time permitting, could you have a look at this?

**Comment by Memphiz** [comment]
rebasing to master (which will bump pvr addons to a newer revision) should fix it... - if rebase is to much work for now you could just bump tools/depends/target/xbmc-pvr-addons to b2dc035404e14f137033876d14ad92ae3bde5f27

**Comment by koying** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
for ios build error please cherry-pick https://github.com/Memphiz/xbmc/commit/bb5e891a29e39cee3893dbda319c55e91f62dcf1

Still investigating the osx issue (one was jenkins / github / network issue - the other some sort of strange permission problem - @wsnipex how often do you do testbuilds on that jenkins slave - i fear it might influence permission wise somewhere).

**Comment by Memphiz** [comment]
Ahh no where did i look at *wonders* ... issue is with stdbool.h in rsxs - well it looks familiar - now i try to remember what the problem with stdbool was ...

**Comment by koying** [comment]
This thing is a nightmare ;)
Unless someone says otherwise, as soon as I get a clean build, I push the button...

**Comment by Memphiz** [comment]
win32 would need either an std:: prefix here:

https://github.com/xbmc/xbmc/blob/master/xbmc/win32/WIN32Util.cpp#L520

or an added include for cassert or assert.h - not sure which one is supposed to be used here @Karlson2k

**Comment by Memphiz** [comment]
Koying  i will beat you to it once jenkins builds this!

**Comment by wsnipex** [comment]
didn't do any test builds yet

**Comment by Memphiz** [comment]
@koying you saw my comment about cherrypicking something from my repo?

**Comment by koying** [comment]
Picked. That doesn't fix OSX, yet, right?
Linux'es failed on git checkout, for some reason...

**Comment by Memphiz** [comment]
Yes still on trying to readup about the osx issue with stdbool.h in rsxs

**Comment by Memphiz** [comment]
@koying please pick https://github.com/Memphiz/xbmc/commit/9792e07682bef6f7f05f29f8ff005476d064311d

Sorry for the delay but it was a bitch to find a sane fix...

**Comment by koying** [comment]
Thanks :)

jenkins build this please

**Comment by Memphiz** [comment]
@koying i am on it - we are a step further now - seems there went some new non c++11 compliant code in since the last time this worked ...

**Comment by Memphiz** [comment]
@koying this stuff here is driving me nuts:

https://github.com/xbmc/xbmc/blob/master/xbmc/guilib/GUIFontCache.h#L37

It leads to a dozens of errors because the compiler seems to be confused about std::vector and boost::vector ... i am not sure when i will be able to solve this - i try to do yet another night shift now but really am not so positive.

We should really try to switch at least one more paltform to clang so that i am not the only one fighting this compiler... (which seems the most restrictive compiler out there atm).

**Comment by Memphiz** [comment]
@koying the way you cherry picked you lost the prefixes of my commit messages - please go to the pita, add me as remote and do a real cherry-pick at the end ...

**Comment by Memphiz** [comment]
@koying - top 3 commits ... especially pay attention to the top most commit - i am not sure if the template aliasing is supported by all gccs we use ... we'll see - but due to the heavy templating used/introduced in that guifontcache this is needed:

https://github.com/Memphiz/xbmc/commits/c%2B%2B11

HOLY SHIT ... i will never touch such a header hell again in years...

**Comment by Memphiz** [comment]
Ok - as expected linux64 is not fine with template aliasing (all other platforms built fine now on jenkins) (rbpi is still missing some cassert includes - doing testbuilds until i catched all).

Also in general what i saw - building with c++11 is significantly slower then without (at least with clang) ...

@Bavision - you are a template guru i think. Do you have any idea how we can move the typedef here to the cpp file from the header? We need to keep the header free from boost includes! (and only that typedef pulls in the boost stuff...): 
https://github.com/Memphiz/xbmc/commit/35cc603345e16193324d271d6f215b2e56911af4

Ideally instead replacing all boost stuff with stdlib stuff would be a solution too...

**Comment by MartijnKaijser** [comment]
@bavison ping

**Comment by Paxxi** [comment]
I'm no template ninja but maybe this would work @Memphiz ? builds fine in vs2013 but I haven't tested it on linux https://github.com/Paxxi/xbmc/commit/642465fc07e2466c7bdc5ac6b7f2e1764678f92a

**Comment by bavison** [comment]
I'm not really that much of a template guru - that font cache code was the most advanced use of templates I'd ever tried! I was on the verge of suggesting a #define as a substitute for the type alias that would work on a broader range of compilers, but having briefly examined @Paxxi's solution, it looks it good to me, assuming it works...

**Comment by Memphiz** [comment]
@Paxxi looks good - some bits where missing - i changed it accordingly (i moved the ctor and dtor to the cpp file and created the impl there - because i had a bad access at runtime - your assumption that ::Lookup is called first and you can instantiate impl there was wrong as it seems). Will kick test builds... thx

**Comment by Memphiz** [comment]
@koying we have green lights:

http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-All/612/

testbuilds are on the mirror - built from my branch - top 3 commits to be picked ...

**Comment by koying** [comment]
Yeah. Thanks guys :)
I hope I can find a slot tomorrow to merge.

**Pull request closed without merging**
