### PR TITLE
Attempt to fix FileFactory test

### PR DESCRIPTION
**Pull request by notspiff**
not sure if this is what triggers it, but it is definitely not correct in any case.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Seems to break test-suite on windows

**Comment by notspiff** [comment]
Wrong.

**Comment by notspiff** [comment]
jenkins build this please

**Comment by notspiff** [comment]
jenkins build this please

**Comment by notspiff** [comment]
jenkins build this please

**Comment by notspiff** [comment]
all green. had to disable 2 problematic tests - i do not think tls likes global vars. will improve commit message and re-run just to see if it is just a fluke.

**Comment by notspiff** [comment]
jenkins build this please

**Comment by fritsch** [comment]
@notspiff please merge when you are ready! And I think you are, right?

**Pull request merged**
