### PR TITLE
remove glew, its superseded by egl

### PR DESCRIPTION
**Pull request by wsnipex**
@Memphiz ping

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
interesting - no glew - ehrm - clue where this was even used before on osx - also what has egl todo with osx? (seems like i don't know much about this whole story...)

**Comment by akva2** [comment]
Uhm where is the overlap of glew and egl? Egl is windowing, glew is extension handling. I didnt think egl handled those?

You dont really see glew in apps, it just 'fixes' gl.h to preload extensions. It also handled wgl mess (not relevant).

**Comment by wsnipex** [comment]
I don't really know the details, this PR was a reponse to @FernetMenta pinging me in https://github.com/xbmc/xbmc/pull/8604#issuecomment-165380903

**Comment by FernetMenta** [comment]
this PR is ok but it has nothing to to with egl.

**Comment by FernetMenta** [comment]
@wsnipex ready to merge?

**Comment by wsnipex** [comment]
yes, but I'd wait for the next merge window.

**Comment by MartijnKaijser** [comment]
There's not really a merge window yet I guess since we haven't released Jarvis or even RC. Also no nightly build of master for other platforms

**Pull request merged**
