### PR TITLE
[Video] Modify Streamdetails to return correct resolution for 4:3 video

### LINKED ISSUE #18738: Matrix: 4:3 4K TV/Movies showing 8K tags
### Describe the bug
Here is a clear and concise description of what the problem is:

A movie or tv show that is "4K" 4:3 (1.33:1) shows with an 8K tag in the info screens.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Should display the 4K tag, instead of the 8k tag.

## Actual Behavior

Is displaying the 8K tag.

## Possible Fix

Some discussion in forum post:
https://forum.kodi.tv/showthread.php?tid=358184

### To Reproduce

1.  Play a movie or TV show which is in a 3840x2880, 4K 4:3 size.
2.  Default Estuary skin.
3.

### Debuglog

The debuglog can be found here:

N/A

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://i.ibb.co/kJfc3q6/BGC-Est-Matrix01.png

https://i.ibb.co/NmhmTsB/BGC-Est-Matrix03.png

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LIbreElec
 - Kodi version:  LibreElec Matrix build LibreELEC-Generic.x86_64-9.80-nightly-20201103-f0d82de

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by jjd-uk**
## Description

Modify Streamdetails to return correct video resolution for 4:3 videos

## Motivation and Context
Forum user report of a 3840 x 2880 4K in a 4:3 aspect being flagged as 8K, this was due to 4K height being limited to 2160p previously and as can be seen here https://www.wearethefirehouse.com/aspect-ratio-cheat-sheet this is not correct for 4:3 apect ratio video.

In addition I've modified 720p, 1080p, & 8K to take account of 4:3 ratios, again using as a reference https://www.wearethefirehouse.com/aspect-ratio-cheat-sheet

## How Has This Been Tested?
Tested locally with a variety of videos to make sure there's no regression however I don't have any 4:3 videos greater than 720p in resolution. This therefore needs to be sanity checked as perhaps there was good reason not to include 4:3 aspect ratio heights.

## Screenshots (if appropriate):

From user on forum showing the problem

image

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by jjd-uk** [comment]
These seemed to be obviously wrong to me, however perhaps I'm missing a reason 4:3 aspect ratio videos were never taken into account.

**Review by ronie — APPROVED** [review]
looks ok to me

**Comment by jjd-uk** [comment]
Will merge tomorrow if no objections.

**Comment by jjd-uk** [comment]
Fixes Issue https://github.com/xbmc/xbmc/issues/18738

**Pull request merged**
