### PR TITLE
ALSA: Ensure pcm name conflicts resolve to descriptive names

### PR DESCRIPTION
**Pull request by runderwo**
Ensure all ALSA pcms that begin with a name that's simple enough to cause conflicts end up with a descriptive name.  The previous code changed the first name in place, which would always leave one pcm behind with a non-descriptive name.  Example: "USB Audio, Analog"

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
I don't really understand the problem. Can you elaborate? Maybe post the output of `aplay -L` and show some screenshots of the Kodi audio device selection before and after this PR?

**Review by fritsch — APPROVED** [review]
If it causes less confusion for users, great.

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Review by neo1973 — APPROVED** [review]

**Pull request merged**
