### PR TITLE
[cmake] remove usage of kodi-platform

### PR DESCRIPTION
**Pull request by olafhering**
Currently only the following binary addons use kodi-platform:
 pvr.demo
 pvr.dvbviewer
 pvr.njoy
 pvr.vuplus
 pvr.wmc
They have to add it to their own private dependency tracker.
    
Signed-off-by: Olaf Hering <olaf@aepfle.de>

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by olafhering** [comment]
followup for #15781

**Review by Rechi — CHANGES_REQUESTED** [review]
> None of the addons referenced by repo-binary-addons really needs this broken thing.

You are wrong two times, it is used by addons and it's not broken

**Comment by olafhering** [comment]
> > None of the addons referenced by repo-binary-addons really needs this broken thing.
> 
> You are wrong two times, it is used by addons and it's not broken

It is in a couple of ways.

None of the addons really needs it, they just happen to reference this pkg.

**Comment by Rechi** [comment]
see
https://github.com/kodi-pvr/pvr.demo/blob/1c1bd8629dc8d6d85477afcc241a17cda9269daa/src/PVRDemoData.cpp#L22
https://github.com/kodi-pvr/pvr.demo/blob/1c1bd8629dc8d6d85477afcc241a17cda9269daa/src/PVRDemoData.cpp#L86

**Comment by olafhering** [comment]
> pvr.demo

Probably the only thing that has a hard requirement for it.

**Comment by Rechi** [comment]
No there are others too.

**Comment by a1rwulf** [comment]
pvr.iptvsimple for example:
https://github.com/kodi-pvr/pvr.iptvsimple/blob/Matrix/CMakeLists.txt

**Comment by olafhering** [comment]
pvr.dvbviewer needs it. How would it get it?

**Comment by olafhering** [comment]
created a bunch of PR for binary addons that do not need kodi-platform.

The ones listed above perhaps need an entry in their depends/ directory.

**Comment by palinek** [comment]
But `kodi-platform` is built no matter if this PR is merged, because of the `---- Preparing general dependencies ----` step -> https://github.com/xbmc/xbmc/blob/master/cmake/addons/CMakeLists.txt#L190 & https://github.com/xbmc/xbmc/blob/master/cmake/addons/depends/CMakeLists.txt#L33.

**Comment by olafhering** [comment]
> But `kodi-platform` is built no matter if this PR is merged

Thanks for review. There might be more to it, I'm not familiar with the enitre system.

IF any of the addons really requires kodiplatform, the hard dependency has to be added to that addon, not to everything unconditionally.

**Comment by AlwinEsch** [comment]
I also see it better to leave this to the addon, not many, but a few that currently need it or have it in there.

In some, probably only accidentally used and needed nothing in it (XML part).

Here is a quick search which it in their CMakeLists.txt:
- audiodecoder.modplug
- audiodecoder.nosefart
- audiodecoder.openmpt
- audiodecoder.sidplay
- audiodecoder.snesapu
- audiodecoder.stsound
- audiodecoder.vgmstream
- game.libretro
- game.netplay
- game.shader.presets
- peripheral.joystick
- peripheral.steamcontroller
- pvr.argustv
- pvr.demo
- pvr.dvblink
- pvr.filmon
- pvr.hdhomerun
- pvr.hts
- pvr.iptvsimple
- pvr.mythtv
- pvr.njoy
- pvr.octonet
- pvr.pctv
- pvr.rtl.radiofm
- pvr.sledovanitv.cz
- pvr.stalker
- pvr.teleboy
- pvr.vbox
- pvr.vdr.vnsi
- pvr.vuplus
- pvr.wmc
- pvr.zattoo
- vfs.nfs
- vfs.rar

Think if some of the addons are updated and even the kodi-platform and p8-platform are used in their dependencies, this request may come in.

**Comment by palinek** [comment]
Note 2: to make it build for all CI I needed even more changes:
https://github.com/xbmc/xbmc/compare/master...palinek:test_build
https://github.com/palinek/pvr.sledovanitv.cz/compare/cleanups...test_build

Why are the `dlfcn*` headers included in  `include/kodi/libXBMC_addon.h` ?

**Comment by AlwinEsch** [comment]
Make no problem to remove, maybe few addons use it but they can incude it also byself.

Is an old remnant where libXBMC_addon.h still had a shared lib between addon and kodi which was loaded with `dlfcn`, this was also the main reason why p8-platform with all addon winking (in Windows) was absolutely necessary.

Here where it was present (a long time ago):
https://github.com/xbmc/xbmc/tree/e2563f6529ea0f08fe153d6baa9dff0935ea8d65/lib/addons

Currently is this the only part where `dlfcn` becomes used, but this does it only for himself:
https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-addon-dev-kit/include/kodi/tools/DllHelper.h
Some audiodecoder addons use them, but this can add a p8-platform byself to depends.

Also have in mind to make changes to take the `dlfcn-win32.h` over another way and to prevent p8-platform. Some parts on them are on newest C++ no more needed further are some parts on them taken from somewhere else and not up to date. e.g. https://github.com/dlfcn-win32/dlfcn-win32

**Comment by olafhering** [comment]
I think this is not going anywhere.

**Pull request closed without merging**
