### PR TITLE
[configure] check for minimum required yajl and tinyxml versions

### PR DESCRIPTION
**Pull request by wsnipex**
- since https://github.com/xbmc/xbmc/pull/5158 we require yajl2
- QueryBoolAttribute - used in at least ButtonTranslator.cpp - was added in tinyxml 2.6.2

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by notspiff** [comment]
Please fix cec while at it (2.2.0)

**Comment by wsnipex** [comment]
I'd love to, but libcec insists that it is 2:1:0. @opdenkamp pretty please fix that.

**Comment by opdenkamp** [comment]
next version

**Comment by wsnipex** [comment]
meh... yajl added the pc file in 2.0.3, we use 2.0.1...

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
ugly now, but that version header exists in yajl 1 already, so we have to specifically check that header :/
jenkins build this please

**Comment by wsnipex** [comment]
jenkins build this please .-.-.-.

**Comment by topfs2** [comment]
IMO require yajl 2.0.4 its available in ubuntu thrusty. Which Ubuntu wise seems old enough.

**Comment by wsnipex** [comment]
nah, if we compile and work with 2.0.0 we should support it. And we'd need to bump internal yajl as well.
Once we need a newer version, this check can be reduced to pkg-config alone.

**Comment by topfs2** [comment]
Cool I'm fine with anything 2.x as it cleans up the code and helps me use json stuff outside kodi
Thanks for fixing the configure for me :)

**Pull request merged**
