### PR TITLE
cmake: two fixes for dependencies

### PR DESCRIPTION
**Pull request by Montellese**
These two commits are extracted from #6227 and I ran into them while trying to get the PVR addons built as binary addons for android.

The first commit re-adds the definition of `DEPENDS_PATH` on all depends-based builds. It was already set for darwin-based builds but not for any others. The whole logic there could probably do with a refactor as all platforms with `$(PREFIX)` set use it for `DEPENDS_PATH` but right now it's split between darwin and the rest. The re-added line has been lost in 61b712b63673f5c54d787aa5d2f92d2f3b21396c which moved this logic to a new file.

The second commit adds `${BUILD_ARGS}` to the arguments passed to cmake for the configuration step of addon dependencies. Without this the buildsystem of the dependencies is missing all kinds of important information but mainly `CMAKE_TOOLCHAIN_FILE` which points to a file containing all the target platform specific information (like which toolchain / compiler to use and where to look for include/library files).

@wsnipex for review please.

### CODE REVIEW

**Comment by wsnipex** [comment]
thanks much, looks good.
jenkins build this please

**Comment by Montellese** [comment]
Doesn't seem to work for android (other builds aren't finished yet). Both ogg and lame dependencies fail to build but with all those parallel builds running at the same time reading the output is a PITA.

**Comment by Montellese** [comment]
Trying to untangle the build output of the android ARM (see http://jenkins.kodi.tv/job/Android-ARM/3068/consoleText) I came across this:
```
checking build system type... x86_64-unknown-linux-gnu
checking host system type... 
Invalid configuration `arm-linux-androideabi': system `androideabi' not recognized
configure: error: /bin/sh ./config.sub arm-linux-androideabi failed
make[8]: *** [ogg-prefix/src/ogg-stamp/ogg-configure] Error 1
```

**Comment by Montellese** [comment]
@wsnipex: Is it possible that we need to provide `config.guess` and `config.sub` (and probably `config.site`) to these dependency builds?

**Comment by kib** [comment]
The Android x86 does the same:
Invalid configuration `i686-linux-android': system `android' not recognized
configure: error: /bin/sh ./config.sub i686-linux-android failed

**Comment by wsnipex** [comment]
yes, it looks like we need to copy config.site/guess/sub. Thats what we discussed already in the other PR

**Comment by wsnipex** [comment]
hmm it actually loads config.site from our toolchain.
configure:1843: loading site script /opt/xbmc-depends/arm-linux-androideabi-android-14/share/config.site

I somehow remember that passing in the DEPENDS_PATH was specifically added for darwin only, as it caused issues on other platforms. I'll try to look into it some more.

**Comment by wsnipex** [comment]
@Montellese https://github.com/wsnipex/xbmc/commit/303609ee143e0c34114599ee818a27236756744c fixes audioencoders building on droid. This never really worked before, as autotools depends were always built host native :/ We just happened to have suitable target libs from normal unified deps around already.

didn't have much time to test this patch though, but I though I post it before we duplicate work.

**Comment by wsnipex** [comment]
before I forget. We currently install addon deps into the normal kodi dependencies prefix. This is probably not wanted as it could potentially break something for kodi. So we should use a different DEPENDS_PATH

**Comment by Montellese** [comment]
@wsnipex: Thanks for the fix. Yeah I noticed that as well and wasn't sure if it was intended. The question is if we want to be able to access dependencies that were previously build with the depends system when building binary addons. If yes, we need to provide the cmake buildsystem with the path to that install prefix and a path to where the binary addon dependencies should be installed to. Otherwise the latter is enough.

**Comment by wsnipex** [comment]
I'd tend to keep the cmake system independent from unified deps. If there is a really good reason why we'd need the kodi depends, we can still add them to the cmake search path.

**Comment by Montellese** [comment]
How will kodi-config.cmake, kodi-platform and tinyxml end up in the binary addons prefix? Would it be possible to add them to `project/cmake/addons/depends/common` and let them be built as part of the binary addons build? That way kodi-platform would be part of the binary addon buildsystem and wouldn't have to be defined as a dependency in every addon (as discussed in the other PR) and it would still work the same for all platforms.

**Comment by wsnipex** [comment]
re kodi-config: https://github.com/xbmc/xbmc/blob/master/project/cmake/scripts/common/prepare-env.cmake#L48  you just have to adjust KODI_LIB_DIR
we could add kodi-platform and tinyxml to that file as well.

**Comment by Montellese** [comment]
I just gave this a try when building for android and simply not setting `DEPENDS_PATH` in `xbmc-addons.include` worked fine and did not pollute unified depends BUT due to `Toolchain.cmake` the unified deps installation path is automatically set as a place to look for includes and libs.

**Comment by Montellese** [comment]
@wsnipex: What should we do here? The second commit is an obvious fix but the first one isn't. Should we try to not set the `DEPENDS_PATH` anymore so that binary addon dependency builds don't pollute kodi's `PREFIX` anymore? That will however mean that we will build all binary addon dependencies in addition to them probably already being built during depends.

**Comment by wsnipex** [comment]
I'm already on it. hang on please

**Comment by wsnipex** [comment]
@Montellese not setting DEPENDS_PATH breaks cross compiling on autotools depends, because config.site from $PREFIX/share is not used. Simply copying that doesn't work corretly either, so we'd need to modify or create a new one just for the cmake system. This is a whole new rabbit hole, so I suggest keeping DEPENDS_PATH=$PREFIX for now in order to not delay stuff too much.

**Comment by Montellese** [comment]
jenkins build this please

**Comment by Montellese** [comment]
OSX32 failure is unrelated and OSX64 worked fine. @wsnipex: I made a few adjustments to `xbmc-addons.include`. Let me know if you're ok with it.

**Comment by wsnipex** [comment]
sure, looks good. Needed a refactor :)
could you add https://github.com/wsnipex/xbmc/commit/d801b20952fb52f8954dcf1d71cd2bf5fec8f532 as well?

**Comment by Montellese** [comment]
@wsnipex: Done but that commit breaks win32. But I've been meaning to clean up the ARCH_DEFINES on win32 anyway because I had to use some `remove_definitions()` in the visualization addons and I don't like that at all.

**Comment by wsnipex** [comment]
ok. If its a problem, we can make an exception for win. in the meantime, lets see if it works for the other platforms.
jenkins build this please

**Comment by Montellese** [comment]
Oops, WIN32 build failed (as predicted) but it did not fail the build :-/

**Comment by Montellese** [comment]
Yeah we'll probably have to exclude win32 from that logic because the VS compiler doesn't understand `-D` syntax and we're already using the `CMAKE_USER_MAKE_RULES_OVERRIDE` and `CMAKE_USER_MAKE_RULES_OVERRIDE_CXX` variables to pass in files which properly setup `CMAKE_C_FLAGS` and friends for win32.

**Comment by Montellese** [comment]
Actually the problem seems to be that we don't pass on the `ARCH_DEFINES` as `ARCH_DEFINES` anymore.

**Comment by wsnipex** [comment]
I have to admit I kinda lost overview of where thats used, but probaly only somewhere in the addon helper scripts. Does adding it back fix the issue? Cause I don't see any harm in that.

**Comment by Montellese** [comment]
Yeah adding it back solves the issue. I just realized that for some reason kodi-config.cmake is created with an empty `add_definitions()` call when I don't pass `ARCH_DEFINES` to the addon dependency builds. Still trying to figure out why. But I have a feeling this might be solved by #6282.

**Comment by wsnipex** [comment]
nice. So merge #6282, then this one?

**Comment by Montellese** [comment]
Yeah I'll merge #6282 when the next merge window starts. But with this one we first need to figure out why OSX32 and IOS/ATV2 fail.

**Comment by wsnipex** [comment]
same old error: 
>ld: warning: ignoring file
  CMakeFiles/cmTryCompileExec652980293.dir/testCCompiler.c.o, file was built
  for unsupported file format ( 0xcf 0xfa 0xed 0xfe 0x 7 0x 0 0x 0 0x 1 0x 3
  0x 0 0x 0 0x 0 0x 1 0x 0 0x 0 0x 0 ) which is not the architecture being
  linked (i386): CMakeFiles/cmTryCompileExec652980293.dir/testCCompiler.c.o

>  Undefined symbols for architecture i386:

>  "_main", referenced from:
        start in crt1.10.6.o

>  ld: symbol(s) not found for architecture i386

>  collect2: ld returned 1 exit status

**Comment by Montellese** [comment]
I think the actual issue is
```
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/usr/bin/llvm-gcc-4.2 -- broken
checking for ldap.h... CMake Error at /Users/Shared/jenkins/workspace/OSX-32/tools/depends/xbmc-depends/buildtools-native/share/cmake-2.8/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler
  "/Applications/Xcode.app/Contents/Developer/usr/bin/llvm-gcc-4.2" is not
  able to compile a simple test program.

  It fails with the following output:
```

**Comment by Montellese** [comment]
I pushed the commit for the missing `${BUILD_ARGS}` already to master. Then I ran some tests. Only applying the first commit from this PR will still work on OSX but fails on android which needs the second commit. Adding the second commit will however break OSX32.

**Comment by wsnipex** [comment]
so https://github.com/Montellese/xbmc/commit/a27436905b52cdb2ac03405cc8d984daa38b3973 break OSX again? Then why not exclude darwin from passing the cflags?

**Comment by Montellese** [comment]
Yeah I'll give that a try.

**Comment by wsnipex** [comment]
the builds from your test branch look good :)

**Comment by Montellese** [comment]
Yeah that was without the last commit. A test build with the last commit but excluding darwin builds is running at http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-All/598/.

**Comment by wsnipex** [comment]
thats what I was referring to. Seems to fix it.

**Comment by Montellese** [comment]
Yup all builds went fine. Would be interesting to know which flag is causing problems but iterating through this with jenkins builds is so tedious. I also don't know if the `NOT APPLE` condition I used as a test is the best way to go.

**Comment by Montellese** [comment]
jenkins build this please

**Comment by Montellese** [comment]
That didn't go well. Now linux and RPI fail as well :-/

**Comment by wsnipex** [comment]
and OSX as well :/ Lets go back to the old version that excludes apple and be done with it

**Comment by Montellese** [comment]
Done but I've added two `TODO` comments that we should look into this more carefully when we have the necessary access.
jenkins build this please

**Comment by Montellese** [comment]
*grr* typo
jenkins build this please

**Comment by Montellese** [comment]
It finally built fine apart from the jenkins problem on OSX64.

**Comment by Montellese** [comment]
I just realized that I screwed up the comitt that should pass config.sub and config.guess to the binary addon dependencies because I used cmake variable notation instead of Makefile variable notation.

**Comment by wsnipex** [comment]
hmm, not sure I follow.

**Comment by Montellese** [comment]
The line at https://github.com/Montellese/xbmc/commit/38857179dc182cf7b1cef96dc8d8508f7c9513e9#diff-4331f22e2921896dd680ed39048db0beR19
was
```
CMAKE_EXTRA += -DDEPENDS_PATH=$(PREFIX) -DAUTOCONF_FILES="${CONFIG_SUB} ${CONFIG_GUESS}"
```
i.e. curly braces around `CONFIG_SUB` and `CONFIG_GUESS`instead of
```
CMAKE_EXTRA += -DDEPENDS_PATH=$(PREFIX) -DAUTOCONF_FILES="$(CONFIG_SUB) $(CONFIG_GUESS)"
```

**Comment by wsnipex** [comment]
oh, that doesn't matter, make accepts both

**Comment by Montellese** [comment]
Ah I didn't know that. I changed it either way. Better be consistent. I also shuffled around the logic in `xbmc-addons.include` a bit. Please take another look.
jenkins build this please

**Comment by wsnipex** [comment]
looks good. Could you include this last fix please: https://github.com/wsnipex/xbmc/commit/4e62b3c9a152342deba2304c986da2ab21b7f739

it just makes sure the cmake project dir is clean, otherwise builds from depends fail.

**Comment by Montellese** [comment]
jenkins build this please

**Comment by Montellese** [comment]
All builds succeeded *yay*.
@wsnipex: I'll give you a chance for a final look and feel free to merge if all is ok.

**Comment by wsnipex** [comment]
it can't get worse can it :P

**Pull request merged**
