### PR TITLE
use spdlog's dup_filter_sink to avoid duplicate log messages (fixes #18535)

### LINKED ISSUE #18535: Kodi 19 - Log spam on pausing video
### Describe the bug
Here is a clear and concise description of what the problem is:

While playing a Video from local drive  in Windows, if video is paused by pressing space, immediately the log starts filling with the following message at rate of 2 messages per second.
`WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer`
So if I pause the video for 5 minutes to go do something, the log gets 600 of these messages.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Pausing a Video should not cause LOG file to fillup

## Actual Behavior

```
2020-10-07 18:02:18.417 T:11552 WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-10-07 18:02:18.918 T:11552 WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-10-07 18:02:19.419 T:11552 WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-10-07 18:02:19.920 T:11552 WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-10-07 18:02:20.421 T:11552 WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-10-07 18:02:20.922 T:11552 WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
```

### To Reproduce

1. play any video from kodi library, files in local drive
2. pause the video for 30 seconds
3. log has 60 messages

### Debuglog

The debuglog can be found here:
[Debug Log](http://paste.kodi.tv/luqejuhaxu)

### Screenshots 
Here are some links or screenshots to help explain the problem:

Not Applicable

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Not Applicable

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Windows 10 2004
 - Kodi version:
Nightly 19.0-ALPHA2 (18.9.702) Git:20201007-f1074bd420
(Tested from Alpha1 snapshot to 7 OCT 2020 nightly)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by Montellese**
## Description
This puts a `spdlog::sinks::dup_filter_sink_mt` between the existing distribution sink and the `spdlog::sinks::basic_file_sink_mt` which is responsible for writing all log messages to Kodi's log file. Therefore the duplicate log filtering is only applied to the log messages going to the log file but not to log messages going to other channels (e.g. Android's logcat or Visual Studio debug output).

I've configured the `dup_filter_sink` to filter duplicates for 10 seconds. Is that OK or should I increase / decrease it? Log messages are only considered duplicates if they have the exact same log message and if they are logged within the specified time window.

This should fix #18535 and all other cases where we log the same messages multiple times in a row. The new log output in Kodi's log file now looks like this:
```
...
2021-01-18 07:56:56.204 T:8340  WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
2021-01-18 07:57:06.497 T:8340  WARNING <general>: Skipped 19 duplicate messages..
2021-01-18 07:57:06.496 T:8340  WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
2021-01-18 07:57:16.822 T:8340  WARNING <general>: Skipped 19 duplicate messages..
...
```

## How Has This Been Tested?
Manually by pausing playback of a video as described in #18535.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by Montellese** [comment]
Not sure if this is acceptable for Matrix? It more or less restores the behaviour from before the move to `spdlog` but it's not identical.

**Comment by jjd-uk** [comment]
If there's low risk of being able to cause any unforeseen side effects or issues being introduced, then it should still be acceptable for v19,, you just need to get @DaveTBlake approval to merge. I'll label it v19 anyway until someone says otherwise.

**Review by DaveTBlake — APPROVED** [review]
Yeap I consider this an issue fix, and good to reduce log spam wherever possible.

**Comment by wsnipex** [comment]
it's sensible as a feature, but it is a workaround for the linked issue. The real fix for that is https://github.com/xbmc/xbmc/pull/19074

**Comment by Montellese** [comment]
> it's sensible as a feature, but it is a workaround for the linked issue. The real fix for that is https://github.com/xbmc/xbmc/pull/19074

While it's a workaround for the linked issue it also generally restores the behaviour we had before `spdlog`.

**Comment by gabime** [comment]
@Montellese Since “_mt” dup sink is used, the basic_file_sink_mt can be changed to “basic_file_sink_st” and save (the now redundant, because it is already protected by the parent dup sink) locks in it.

**Comment by Montellese** [comment]
@gabime Thanks a lot for your input. Does this apply to all `_mt` distribution sinks? Because we already use a `dist_sink_mt` at the base where we add platform specific debug loggers (without duplicate handling) and now the `dup_sink` containing the file sink. Can we change all other sinks to `_st`?

**Comment by gabime** [comment]
Yes, as long as those sinks are not shared by other loggers.

**Comment by Montellese** [comment]
> Yes, as long as those sinks are not shared elsewhere (with other loggers in for example)
We add the base distribution sink to all loggers. So all loggers use the same sink setup and should log into the `dist_sink_mt`.

**Comment by gabime** [comment]
so should be fine.

**Comment by Montellese** [comment]
> so should be fine.

Thanks for your valuable input.

I've added a new commit before the actual fix commit which changes all subsequent sinks from multi- to single-threading. I've also adjusted the second / existing commit to use `dup_sink_st` instead of `dup_sink_mt`. Now only the base sink uses `dist_sink_mt` and all others are `_st`.

**Comment by Montellese** [comment]
@DaveTBlake can this be merged or will it not go into Matrix?

**Pull request merged**
