### PR TITLE
pvr build clean-up and fix

### PR DESCRIPTION
**Pull request by FernetMenta**
1) removes obsolete pvr in-tree build

2) fix install of arch dependent files when installing kodi

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by opdenkamp** [comment]
I think that we should keep this one, so you can stick an add-on in the main tree while developing, with some adaptions to build the new cmake based one. It makes it a lot easier for developers to do their work and set breakpoints in the add-on.

**Comment by FernetMenta** [comment]
well, currently it is of no value because it is broken. i never keep broken code because it might be useful in the future. git won't forget it. i disagree that it makes anything easier. you can develop and debug with the new system quite well. did you read my post on the forum?

**Comment by opdenkamp** [comment]
Nope, haven't read it, will check in the evening. If it allows me to have a git clone of the add-on in tree in which I can set breakpoints in my IDE, then it's fine. If not, then I'll take a look at adapting it for the cmake stuff this week.

**Comment by FernetMenta** [comment]
don't worry, I won't accept any loss in development convenience either :) I use Eclipse having loaded kodi and vnsi as two projects into the same workspace and can debug both at the smae time just it worked before.
@Montellese is currently working on something making it even better.

**Comment by wsnipex** [comment]
looks good.

@opdenkamp see https://github.com/xbmc/xbmc/pull/6592

**Comment by notspiff** [comment]
note that debugging and breakpointing would work even if the build systems were completely separate. a debug build has all sources. i understand the convenience factor and all (i do question the convenience of eclipse however :D) but right should be right.

**Comment by opdenkamp** [comment]
sure, it would work, but not in a very convenient way in eclipse (which is great if you have an i7 with a ton of ram for java ;-))

**Comment by FernetMenta** [comment]
@opdenkamp actually this fixes a bug for kodi install which is annoying. how much longer do you need to think about this?

**Comment by Montellese** [comment]
I just saw that there's a docs/README.pvr. maybe that one could be removed as well?

**Comment by opdenkamp** [comment]
@FernetMenta sorry, it's fine, merge away

**Comment by FernetMenta** [comment]
thanks. @Montellese I will do the readme with a separate pr.

**Pull request merged**
