### PR TITLE
[guilib] Fix gif animations in case of a too large gif.

### PR DESCRIPTION
**Pull request by ace20022**

### CODE REVIEW

**Comment by ace20022** [comment]
@ronie or a skin dev: I guess that this problem also exists for bundled animations. Could you please make a xbt animation with too large frames and a modified skin? On my system textures are limited to 4096x4096 pixels. Then I can debug that case too.

**Comment by ronie** [comment]
sorry, i'm not sure what you're asking.
xbt animation? too large frames?

**Comment by ace20022** [comment]
> sorry, i'm not sure what you're asking.
> xbt animation? too large frames?

Sorry, I have no clue of all that texture bundle stuff. Looking at the code path at https://github.com/ace20022/xbmc/blob/gif_fix3/xbmc/guilib/TextureManager.cpp#L338 gives me the impression that there can be animations or gifs inside a texture bundle. I hope that makes it a bit more clear.

**Comment by ronie** [comment]
ok so you need a textures file that includes an animated gif?

if you could please provide one, as i'm still not sure what you mean with 'too large frames'.
i'll create the Textures.xbt + skin mod for testing.

**Comment by ace20022** [comment]
Thanks in advance! https://www.dropbox.com/s/qkdjtslpfqnkgej/nasa-13500x6750.gif?dl=1
This gif has only one frame, but that should be enough.

**Comment by ronie** [comment]
i get this warning when i compile the textures file:
> This is a GIF - lets load it via libgif...
> Gif::LoadGif(): Memory consumption too high: 364500000 bytes. Restricting animation to 1. File media/nasa-13500x6750.gif
> nasa-13500x6750.gif

result:
kodi_005

modified confluence skin:
https://www.dropbox.com/s/ko044o5ronz0j9m/skin.confluence.zip?dl=0

**Comment by ace20022** [comment]
Thanks much! Like I suspected, should be fixed now.

jenkins build this please

**Comment by msduketown** [comment]
Problems with logfiles: http://forum.kodi.tv/showthread.php?tid=249273

**Pull request merged**
