### PR TITLE
VideoPlayer: fixes issues gapless brought to surface

### PR DESCRIPTION
**Pull request by FernetMenta**
this fixes some DVD issues

### CODE REVIEW

**Comment by FernetMenta** [comment]
@Voyager1 @mapfau @afedchin I added a fix to this pr. ffmpeg filter did overwrite the current (allocated) pic and in case filter produced no output, current got undefined.

**Comment by afedchin** [comment]
will take a look today later

**Comment by mapfau** [comment]
There are no artefacts / exeptions on my system anymore! I tested ffmpeg nd DXVA.Well done!

I'm not sure if this is because of missing data: I'm not able to continue any episode (sponge).
1st the fish swims, 2nd. the license ist displayed. Finally there comes "select episode" but if I choose one (regardles wich) the dvd stopps. Yesterday I was sure theat I was able to continue an episode, but not 100% sure.....

**Comment by afedchin** [comment]
@mapfau spange sample has no episodes and has only DVD menu.

**Comment by mapfau** [comment]
Selecting benelux language display a pink video with synapses(???, haha), it stops finally with a black frame and it seems that there is running something out of mem

**Comment by mapfau** [comment]
@afedchin I have a menueitem in german "Episode auswählen" if I watch the sponge dvd image.

**Comment by mapfau** [comment]
Yes, there is some memory not freed, using taskmanager shows this wery well.

**Comment by FernetMenta** [comment]
@mapfau you still need the WinRenderer change we mentioned yesterday

**Comment by mapfau** [comment]
@FernetMenta I have pulled your actual master - does it include the change?
It is the ManageTextures move, isn't it?

**Comment by afedchin** [comment]
@FernetMenta there is a memory issue. each frame (not stills) eat a memory. Kodi reach a 2GB after a few minutes of TARZ main menu. seems frames aren't freed. This not happens with hw decoder.

**Comment by mapfau** [comment]
not gone too deep into av_frame_move_ref until now, but for the first look it doesn't seem to care about allocated memory in dst.

**Comment by FernetMenta** [comment]
@mapfau 
1) yes, the ManageTextures
2) my master does not have this change included

**Comment by mapfau** [comment]
@FernetMenta Applying the change from yessterday does not affect the issue.
For me it seems that av_frame_move_ref is for moving something valid(src) into something empty(dst). src is memsetted to 0 after the move (*dst = *src) was applied.
But pls. be gracious, ffmpeg is not my every days playground....

**Comment by FernetMenta** [comment]
could you add this: https://github.com/FernetMenta/xbmc/commit/bc2db13aba234efddf8f1a4af3baa72add05062e

I cleared the wrong ref there

**Comment by mapfau** [comment]
running well - we could have seen this also :-(

**Comment by afedchin** [comment]
@FernetMenta I've found this also. This fixes the issue and works well with hw decoder also.

**Comment by FernetMenta** [comment]
thanks! I squashed the change and added the WinRenderer fix here. @afedchin is it correct this way?

**Comment by afedchin** [comment]
@FernetMenta yes, it is. So there is a issue with render flags and hw decoder. the flags contains only RENDER_FLAG_TOP and no RENDER_FLAG_FIELD0/1 this brokes deinterlacing with hw decoder.

**Comment by afedchin** [comment]
@FernetMenta got it. will fix in my PR for dxva stills.

**Comment by FernetMenta** [comment]
@afedchin those flags are only relevant for BOB and WEAVE where RenderManager calls renderer twice. For DXVA specific modes you need to check DVDVideoPicture.iFlags like shown here:

```
  // set fieldsync if picture is interlaced
  EFIELDSYNC mDisplayField = FS_NONE;
  if( pPicture->iFlags & DVP_FLAG_INTERLACED )
  {
    if( pPicture->iFlags & DVP_FLAG_TOP_FIELD_FIRST )
      mDisplayField = FS_TOP;
    else
      mDisplayField = FS_BOT;
  }
```

**Comment by afedchin** [comment]
@FernetMenta thanks. this https://github.com/xbmc/xbmc/commit/339ce49f3adddb53c89d7d78c28696f5afe64498 causes an issue. before that WinRenderer reported about VS_INTERLACEMETHOD_DXVA_[BOB|BEST] and Render manager selects PRESENT_METHOD_BOB. I think proper fix is return VS_INTERLACEMETHOD_DXVA_AUTO to this purpose. what do you think? Or just fix winrenderer to make it returns VS_INTERLACEMETHOD_RENDER_BOB for DXVA method?

**Comment by afedchin** [comment]
never mind.

**Comment by Voyager1** [comment]
thanks - testing done and all good! you guys rock :-)
Note that I combined it with @afedchin dxva deinterlacing fix #8939

**Comment by FernetMenta** [comment]
jenkins build this please

**Pull request merged**
