### PR TITLE
ADD: [droid] move activity to front when playback is started

### PR DESCRIPTION
**Pull request by koying**
On Android, this brings the app in the foreground if a video is launched when minimized

/cc @FernetMenta @MartijnKaijser @da-anda

### CODE REVIEW

**Comment by garbear** [comment]
I recommend a change: have the g_windowing classes should register for a "playback started" event so we can avoid polluting CApplication with more windowing stuff

**Comment by koying** [comment]
"Playback started" is too late in this instance. For droid, I need to make the window show up *before* the codec is created, or the rendering surface is not yet recreated.
Now, if it's a big issue, mediacodec will fall back to non-surface playback, but it's not nice...
 
jenkins build this please

**Comment by koying** [comment]
An option would be to add an additional "BeforePlayback" event, though

**Comment by da-anda** [comment]
I actually could need such an event also for 3D stuff. Currently the 3D dialog to ask for preferred playback mode is triggered when the first frame is already visible, which is bad, as it results in 2 refresh rate switches in a row in worst case. I was asking for a new signal at an earlier stage, but didn't get much feedback on this. For the 3D case though, I might need the stream to be analyzed already, so that the stream details/hints are already available, but from your description this would be to late for your needs?

**Comment by koying** [comment]
Well, no. The stream can be analysed (it's pure ffmpeg), just the h/w codec not yet created.

@FernetMenta Mind giving your thought about an additional event and where to put it between analysis and actual start of playback? Thx

**Comment by popcornmix** [comment]
+1 for an event when demuxer has extracted stream details (resolution/framerate) which is used for hdmi mode change.
Always seemed ugly to me that you can get a few frames of video and a burst of audio out before the hdmi mode change. You want to change hdmi mode at the earliest possible time.

**Comment by FernetMenta** [comment]
I have a look and give feedback soon

**Comment by FernetMenta** [comment]
> I recommend a change: have the g_windowing classes should register for a "playback started"

absolutely no-go that a lower layer registers in a higher one

**Comment by FernetMenta** [comment]
g_windowing should not be used anymore. it will disappear in a way that is will be fully encapsulated by render system.

> Always seemed ugly to me that you can get a few frames of video and a burst of audio out before the hdmi mode change. 

I am working on this but need to separate the render thread first. Currently player can do a synchronous mode switch without risking dead lock.

@koying how urgent is this? do you want this for Jarvis?

**Comment by koying** [comment]
No urgency, just a nice-to-have. Can be delayed to 17

**Comment by FernetMenta** [comment]
@koying I think this change does is almost: https://github.com/FernetMenta/xbmc/commit/6832807d624bce39aa74fb83f84ba3a94f9430b8

If minimized you can switch to front on a change of resolution, right? As mentioned, the problem is a synchronised resolution switch.

**Comment by koying** [comment]
Well, this PR is independent of resolution switch.
It handles the case where a video is sent to Kodi (via json or upnp) when we are minimized.

An android limitation is that we have to be maximized for the rendering surface (in the android acceptation, not egl) to be recreated by the OS, as it it destroyed when we go out-of-focus / minimized, and we use that surface at codec creation time.

**Comment by da-anda** [comment]
btw - not only video playback - you'd also want the app to come to foreground when you push a photo via AirPlay or UPNP. Actually it probably should always come to foreground when any playback starts, regardless of media type. Music can ofc still continue in background once playing and app is minimized, but if minimized and nothing is already playing, then on a new playback start the app should come to foreground. That's at least what I would expect to happen on a TV.

**Comment by FernetMenta** [comment]
> Actually it probably should always come to foreground when any playback starts, regardless of media type

not sure if this is a good idea for all platforms. on a desktop system like Windows, Linix, OSX you don't want this behaviour.

**Comment by FernetMenta** [comment]
@koying the commit I linked sends an event to gfx context regardless of a resolution change. should be no big deal to trigger additional behaviour

**Comment by da-anda** [comment]
> not sure if this is a good idea for all platforms. on a desktop system like Windows, Linix, OSX you don't want this behaviour. 

why not? Assuming an HTPC with Kodi running in the background and somebody is pushing media to it, I'd expect to see it. Audio would be the only thing in question, but as Kodi is a media center intended to be used on a TV and not a desktop player I don't see an issue with also doing it for audio on every paltform.

**Comment by Tolriq** [comment]
Bring Kodi front is asked a lot by users, as it's second most used feature for some of my additionnal tools.

Users are lazy, they forget to bring Kodi front before moving to sofa and want to start a media from remote, but needs to get up to have it displayed.

For audio I pretty agree with @da-anda way (display if not already playing)

**Comment by koying** [comment]
I must say I quite agree with what is being said. Audio can be debated, and the Video logic tweaked (especially when chaining videos/playlists), but generally, if I push a video to Kodi, I actually want to see it ;)

This not taking into account the platform-specifics guidelines in the matter, of course, but for Windows (that I use), it wouldn't shock me.

**Comment by fritsch** [comment]
As long as you can still debug on single screen without the player windows jump infront of your IDE ... also there is a usecase for playing music videos in a playlist.

Not sure - the usability guys shall decide and get the bugreports later on :-)

**Comment by koying** [comment]
Setting?
/me runs ;)

**Comment by da-anda** [comment]
good point with the debugging @fritsch, but I don't think we should focus on developers usecases. Having a setting (expert or as.xml) would be fine with me, or whatever else makes sense on dev environments (environment setting, startup command, disable in debug mode, ...).

@koying it should only happen on initial playback start - so once playing and in background, an item from a playlist should ofc not trigger the app to come to foreground.

One thing to think about is also if we should remember what has been playing before and continue playback once the "pushed" media is finished. Like when you have friends at home, listen to background music while having a nice chat and someone would like to push the new StarWars trailer. Ideally background music would be paused and continue after video is finished. So pause PlayerA, have PlayerB do it's thing and continue with PlayerA. Alternatively, stop playback of current media to create a resume point, queue the new item(s) in a playlist and add the previously playing item to the end of the queue.

**Comment by FernetMenta** [comment]
This behaviour makes sense for a HTPC but on a multi-desktop, multi-user system you don't want application anarchy. Assume you do email on desktop 3 and Kodi is minimized on desktop 1. You certainly don't want Kodi get to front, I am not even sure if this is possible. An application may be minimized while the user who started it is logged off. 

We distinguish between those modes: headless, HTPC, desktop, ...
imo we don't need a setting, those a best selected via a cmd line parameter.

The HTPC behaviour ideally goes to separate object. Something like HTPCController.

**Comment by fritsch** [comment]
if --standalone is passed, try to get focus always. If not, not. We already have this option currently.

**Comment by da-anda** [comment]
As I doubt you push to Kodi running in a desktop env while you're working on it, I don't really see an issue if it would always come to foreground in these cases. I'm not objecting in any way to be smart about or disable it - just not sure it's worth extra work to distinguish for the very rare cases where it might be a unwanted behavior.

**Comment by da-anda** [comment]
@fritsch - IMO it should be on by default as that's what most might expect and is the intended usecase of Kodi. While usage as a desktop app is possible, it's not the main usecase.

**Comment by fritsch** [comment]
@da-anda whatever you like best - i have no strong opinion - when I can disable that it jumps into my debugger window all fine with me ... don't forget the windows user with pseudo fullscreen and two screens ... that prefer moving it to one screen and do something else on the other. They would hate if you remove their focus :-)

**Comment by FernetMenta** [comment]
crappy option "standalone" is buggy and needs to go. we need something similar but more robust.

@da-anda it is not about extra effort, this is about architecture and separation of concerns. The application is in that bad shape because this has been ignored for a long time. you don't know if this is even possible on all platforms, do you? as a result you would need something like "bring to front, if possible" or "try to bring to front". this is hopefully not want you want to go for.

**Comment by da-anda** [comment]
@fritsch in these cases the window is not minimized, so we shouldn't have to take action. Maybe we have to differentiate between "bring to front and grab focus" and "restore window" on a platform level (let the platform implementation decide)? I understand and agree that catching the focus is really not wanted when used as desktop player, but as said - when being used as dekstop player, you usually don't remote control it and will not end up in this situation at all (unless somebody plays a trick on you). I'm also fine with limiting this to Android atm until we sorted out on how to deal with this on other platforms, as Android has the most benefit and other platforms are more a nice to have.

@FernetMenta you know our internals and architecture best - whatever you suggest it shall be. I have no strong opinion on a certain implementation way, but I for sure don't want to see this end up in a ifdef mess. My thoughts mainly focus on what would make sense or might be expected on user level - not the technical implementation. If you want me to I can give it a thought, but you know things way better.

And no, I don't know if it's possible on all platforms and it might not even be needed on all (OE won't need it I guess). From a usability POV my main concern is Android atm - other platforms are secondary.

**Comment by FernetMenta** [comment]
Don't get me wrong. I support this use case but I think we should not generalise it. If I am not mistaken, desktops like Unity not even support refresh rate switching.

> From a usability POV my main concern is Android atm - other platforms are secondary.

I think you need a refresher on this one, in particulat the last bullet :)
 http://forum.kodi.tv/showthread.php?tid=33548

**Comment by da-anda** [comment]
> I think you need a refresher on this one, in particulat the last bullet :)
> http://forum.kodi.tv/showthread.php?tid=33548

hehe, I haven't said it should be implemented platform specific, did I? ;) Ofc the overall implementation should be agnostic - my thought was more in the direction that other platforms could simply ignore it by only having a stub function for the time being.
I know this feature is labeled K*, just had hoped we could implement it on Android already for Jarvis and do the other platforms later.

So what do you suggest on how to proceed here? Where should the "trigger/detection logic" end up in? cApplication? separate class that observes existing signals/messages which either fires of a new signal when criteria is met or directly informs the windowing component to take action? I'm not sure where or how to hook in your mentioned HTPCController.

Btw - should we move this discussion to the dev/architecture subforum?

**Comment by FernetMenta** [comment]
> just had hoped we could implement it on Android already for Jarvis and do the other platforms later

Jarvis has feature freeze

> So what do you suggest on how to proceed here?

I am already working on separation of the render thread. I think this will change quite a lot, i.e. g_windowing will disappear. Once this is completed, we'll have a clearer view on this.

**Comment by da-anda** [comment]
> Jarvis has feature freeze

well, on Android TV/FireTV with very limited possibilities to restore an app running in background it could be considered a fix if we wanted to ("why can I hear the video playing but not see it") - but no strong feelings to get it in or not. Would have been a nice thing to have for a good user experience.

> I am already working on separation of the render thread. I think this will change quite a lot, i.e. g_windowing will disappear. Once this is completed, we'll have a clearer view on this.

ok, let's wait then. Thanks.

**Comment by Rechi** [comment]
@koying this needs a rebase

**Comment by koying** [comment]
Abandonned

**Pull request closed without merging**
