### PR TITLE
Input fixes and modernization

### PR DESCRIPTION
**Pull request by garbear**
My next step toward the Player Manager is the ability to map keyboards in the controller dialog. Because I didn't want to build on decayed code, I did a bunch of modernization and improvements. 

Most changes are local to input code. The only commits that affect outside code are the two changes to CKey.

## How Has This Been Tested?
Tested by mapping controllers in the controller dialog on OSX.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by garbear** [comment]
Found a couple places where key modifiers were compared using `==` instead of `&`. This breaks when more modifiers are added, so I've changed the check accordingly in the commit I just pushed.

**Comment by garbear** [comment]
jenkins build this please

**Comment by MilhouseVH** [comment]
An issue has cropped up [on the forum](https://forum.kodi.tv/showthread.php?tid=298462&pid=2695169#pid2695169) - most likely following this change - that is now affecting keyboard modifier keys, can you take a look? Thanks!

**Comment by garbear** [comment]
Most definitely due to the `Keyboard: Expose more modifiers` change. Thanks, I'll take a look.

**Comment by garbear** [comment]
Should be fixed by #13435

**Pull request merged**
