### PR TITLE
Split VideoDatabase in multiple source files

### PR DESCRIPTION
**Pull request by notspiff**
## Description
This is just a probe to see if it is wanted or not.

## Motivation and Context
The video database is one monotone class. This is not meant to change this. However, it's a pain to navigate. I want to split it up in multiple source files so it is easier to find relevant functions etc. Some peeps like to keep the one-class-one-source rule hard. What's your opinions?

### CODE REVIEW

**Comment by a1rwulf** [comment]
I normally prefer one class one file.
In this case however, I wouldn't object.

**Comment by notspiff** [comment]
> I normally prefer one class one file.
> In this case however, I wouldn't object.

i agree about the preference in general, but here i think a split file is the lesser of two evils.

**Comment by notspiff** [comment]
updated with my suggestion for the splitting.

**Comment by DaveTBlake** [comment]
OTOH I can see the sense in this, but on the other I'm not sure I like it. Not objecting though, just a little uneasy. 

Can I suggest that the layout of the CVideodatabase header file is changed to match this spit, it roughly does but not completely. To make it extra obvious maybe some doxygen comments too.

I assume that huge Musicdatabase.cpp would be next candidate for this, assuming we go this way. If that is to follow then let me be the one to do it. I would rather be hands on than caught out by it.

**Pull request closed without merging**
