### PR TITLE
rename kaitoast xml to DialogNotification.xml

### PR DESCRIPTION
**Pull request by ronie**
rename outdated / meaningless / confusing xml filename to something more fitted.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Jep :)

**Comment by HitcherUK** [comment]
Yep, or it's window name (infodialog) DialogInfo?

**Comment by ronie** [comment]
python already uses xbmcgui.Dialog().notification() to pop up the kaitoast dialog,
so i'd rather stick to that.

i've added a commit to change the dialog name as well.

**Comment by MartijnKaijser** [comment]
Maybe change the internal name as well at same time?

**Pull request merged**
