### PR TITLE
xbmc\cores\VideoPlayer\IVideoPlayer.h: Implemented template method

### PR DESCRIPTION
**Pull request by brokmich**
## Description

Implementes template method in IVideoPlayer.h file to reduce duplicated methods 

## Motivation and context

 This is for a school project, we are learning about software design, and had to contribute to an open source repository

## How has this been tested?

Local Windows PC

## What is the effect on users?

None

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by garbear** [comment]
Hi @brokmich!

While we appreciate the interest in open source (and especially for choosing Kodi to contribute to), a PR like this isn't generally the best way to get started.

One thing you learn as you pick up software design is the principal of Chesterton’s Fence. It loosely says that a change should not be made until the reasoning behind the current state of affairs is understood.

Every one of our half-million lines of code has a reason for being the way it is. I'm not saying the reasons are always valid, and they should certainly be challenged often. But given that every change carries risk, we don't like to take on the risk of change unless it is clearly enunciated why we should do so.

I appreciate that you are honest about this being a student contribution. PRs notify everyone on the team, and most of the team gets confused when they see PRs like this and can respond harshly out of annoyance. I've worked with students for five years of GSoC now, so if you or your professor/mentor email me at garrett@kodi.tv I can offer assistance in contributing to Kodi.

**Comment by brokmich** [comment]
Hi @garbear, I understand what you said and I also agree that starting with a PR like this isn't the best way, and even though I would've liked to keep my changes in a local repository we were required to make an oficial PR for the grade. I'm sorry for the inconvenience and am very grateful for the light hearted reply :)

**Comment by garbear** [comment]
Fair enough! Does the PR need to remain open for the grade? The team handles such a high volume of code contribution that we can't really have "demo" PRs cluttering our workspace, so I intend to close the recent PRs.

What I can do, is create a label for classroom submissions, that will indicate developers should treat the PRs as such. That way, a developer can opt in to offer review as if it *were* a serious PR, as PR feedback was an incredibly valuable way I was able to become an open source developer.

When a PR is understood to be a classroom submission, we can also know that it can be closed when done being treated for grading purposes.

Another service we can offer is that green check a PR gets when it passes our CI infra. I'll have to ask the team about this, because every change pushed will hammer our servers for an hour while excluding all other PR runs. However, it's important to learn how to make a PR "go green", as that's a basic requirement across the entire open source ecosystem. I would hope CI is a part of a software design course.

Finally, my observation is that the most valuable lesson of opening a PR is seeing it through to merge. Otherwise, you don't ever get the full feedback process needed to learn how to successfully contribute to open source. Anyone can throw code at the wall; proper design is doing it right. It's perfectly fine to skip the "doing it right" part for the grade, but I find it's the lesson that most values everyone's time.

I'm pointing the team to this msg. I'll see what they think of a "classroom submission" label.

**Comment by garbear** [comment]
I'm bringing the rest of the team into the discussion: https://github.com/xbmc/xbmc/pull/23515

The other PRs have been closed, but I like that you marked this as a draft, so it can sit gray for a while. After the new check box is added, you can resubmit this PR and get a nice green PR to show the professor.

**Comment by brokmich** [comment]
The PR being closed doesn’t affect the grade so no worries there :) thanks for the interest in our learning process and i hope we can really make the best of this cool new feature

**Comment by garbear** [comment]
Who said anything about grades? 😉 Grades don't get you anywhere in open source, I should know as a college dropout. You get code merged by having good f'ing PRs.

Only one person matters: the maintainer. Learning how to make them say "wow" when reviewing your PR is the best skill you could learn in open source. Greenness matters. So do many other small things which are often overlooked. Hopefully with the new focus on student code we can pass on some of this wisdom.

**Comment by garbear** [comment]
I found evidence that "greenness matters": https://github.com/xbmc/xbmc/pull/23512#issuecomment-1635113434

For a maintainer, the most valuable resource, for that maintainer, is their time. We use CI as a first-line-of-defense to guard our time.

Notice how the maintainer in that PR didn't look at the code, they pointed to the red CI result.

I had a thermodynamics professor once that would throw out your test if you didn't include units in your answers. You could also imagine an English professor that would throw out your essay if you didn't use periods or indentation. Learning how to get a PR green is kinda like that.

**Comment by brokmich** [comment]
Thanks so much :) Even though this was sort of like a mini trial for us to simply make a PR, we did learn more things than we expected from you and your team! Well be taking all this info into consideration and i'll even mention it to our professor. Again thank you so much for your time and I'm sorry if we were a nuisance to you and your team. 

Best regards, an aspiring group of software developers from the University of Costa Rica. 
¡Pura Vida! As we say here. 
@lizethcorrales @jsedo

**Comment by garbear** [comment]
The team was actually really confused. Not because we got student PRs, we get lots of student PRs. But always at the beginning of the year as GSoC ramps up and never mid-year!

I'm actually grateful that your team popped up, because we needed a way to better deal with the GSoC ramp-up PRs, and now thanks to https://github.com/xbmc/xbmc/pull/23515 we have a process for those. Make sure to show your professor https://github.com/xbmc/xbmc/pull/23515 when it's merged so they can see that your team has already had an impact on the project.

¡Pura Vida!

**Pull request closed without merging**
