### PR TITLE
[Estuary] Fix hasvideextras overlay for views

### PR DESCRIPTION
**Pull request by CrystalP**
## Description

Adjusted the visibility conditions in infowall, poster and shift for list items that have hasvideoextras = true

Was missed in PR #24456.

## Motivation and context

Brought up in forum https://forum.kodi.tv/showthread.php?tid=337992&pid=3179078#pid3179078

## How has this been tested?

Tried all library views.

## What is the effect on users?

Consistent display of the extras overlay across views.

## Screenshots (if appropriate):

Before:
image

After (star on elephant's dream):
image

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by jjd-uk** [comment]
Sorry but it's not clear to me exactly what you're seeking to fix here.

Is to display the Extras icon even when unwatched? in which case this does not work without changes to the Variable `WallWatchedIconVar`.

**Comment by CrystalP** [comment]
> Is to display the Extras icon even when unwatched? in which case this does not work without changes to the Variable `WallWatchedIconVar`.
> 
> [edit] It's where there is no versions is it? so only extras?

WallWatchedIconVar was changed in the previous PR #24456 but it was not enough, it didn't make the diffuse rectangle + icon appear at the bottom of the posters. With this PR the icon should have visibility similar to the list based views, and I would like the confirmation of a skinner that I didn't miss anything.

See discussion in the previous PR, there is only one icon representing multiple overlapping pieces of information, which is not ideal of course. The current solution was deemed good enough for v21 but I leave it up to the skinners to improve on it, the info labels are available and functional.

**Review by jjd-uk — APPROVED** [review]
LGTM

**Comment by jjd-uk** [comment]
>  The current solution was deemed good enough for v21 but I leave it up to the skinners to improve on it, the info labels are available and functional.

The Variable `WallWatchedIconVar` has become a bit of a dumping ground for icons to overlay posters. So I will see if I can get this improved for v21.

**Review by Hitcher — COMMENTED** [review]
Looks good, thanks.

**Pull request merged**
