### PR TITLE
[cmake] remove hard requirement for intl in Python

### PR DESCRIPTION
**Pull request by olafhering**
There just is no such library in Tumbleweed, as a result configure fails.

IF this is a distribution specific packaging, it has to be wrapped accordingly.

Signed-off-by: Olaf Hering <olaf@aepfle.de>

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by olafhering** [comment]
````
14:44:18 ./Modules/_localemodule.c:647: error: undefined reference to 'libintl_bind_textdomain_codeset'
14:44:18 ./Modules/_localemodule.c:628: error: undefined reference to 'libintl_bindtextdomain'
14:44:18 ./Modules/_localemodule.c:606: error: undefined reference to 'libintl_textdomain'
14:44:18 ./Modules/_localemodule.c:593: error: undefined reference to 'libintl_dcgettext'
14:44:18 ./Modules/_localemodule.c:579: error: undefined reference to 'libintl_dgettext'
14:44:18 ./Modules/_localemodule.c:566: error: undefined reference to 'libintl_gettext'
14:44:18 collect2: error: ld returned 1 exit status
````

So finally this is actually some useful info what libintl.so is all about.

**Comment by olafhering** [comment]
It looks like something is trying to build a variant of python2.7? If so, is it correctly wrapped?

**Comment by wsnipex** [comment]
Which do you need to touch KODI_DEPENDSBUILD specific requires? This is only used for cross compiling with the kodi depends system. If you build with system libraries this is not used.

**Comment by Paxxi** [comment]
It's not a good idea to remove things from Python as that exposes platform differences to addon authors. It looks like the package is called gettext-tools in suse (https://software.opensuse.org/package/gettext-tools) so maybe this can be updated to alternatively search for that package?

**Comment by olafhering** [comment]
As I said, there is no 'libintl.so' in SUSE. I could do some software archeology to find the last version which did include that file, if it really was ever shipped.

I think the issue is the usage of `cmake -DKODI_DEPENDSBUILD=TRUE`, which I will double check why this is even used.

**Comment by wsnipex** [comment]
intl is coming from https://github.com/xbmc/xbmc/tree/master/tools/depends/target/gettext which we build when using our depends system.

**Comment by pkerling** [comment]
> I think the issue is the usage of cmake -DKODI_DEPENDSBUILD=TRUE

If you're having `KODI_DEPENDSBUILD` and are not using the depends system, there is some other error.

**Comment by olafhering** [comment]
It is unfortunately not that easy. I just set it to false, and the built-in copy of dvdnav.so was build. It is expexted that everything comes from the host. I need to explore this in detail in the coming days, if there are other knobs that I miss.

**Comment by pkerling** [comment]
>  I just set it to false, and the built-in copy of dvdnav.so was build

That is expected. In any case, do *not* build with `KODI_DEPENDSBUILD` unless you are really using the depends system. It will not work in any way like you expect.

You can disable DVD support. libdvd* have too many patches so you can't (easily) use upstream.

Anway, closing this.

**Pull request closed without merging**
