### PR TITLE
bump python api for kodi k***

### PR DESCRIPTION
**Pull request by ronie**
bump python api to 2.25.0 for kodi k***

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
should we wait with this or just bump again on next change?

**Comment by tamland** [comment]
Why? there's no api change

**Comment by MartijnKaijser** [comment]
python 2.6 > 2.7.10

**Comment by ronie** [comment]
sorry, should have mentioned this one can go in after the VideoPlayer merge.

in the xbmc.Player() class, the PLAYER_CORE_DVDPLAYER has been renamed to PLAYER_CORE_VideoPlayer.

https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/legacy/ModuleXbmc.cpp#L535

there's a handful of addons in our repo that specify the player core, those addons are broken now.

**Comment by MartijnKaijser** [comment]
While they have been warned way, way in advance to not do that
http://forum.kodi.tv/showthread.php?tid=173887&pid=1516662#pid1516662

**Comment by ronie** [comment]
i know, most of them have been updated since then, just a couple (i think i counted 5) are still using it.

i'll mention it again in the python changes for k*** thread.

**Comment by tamland** [comment]
That should not have been changed. I'm guessing an oversight on @FernetMenta's side

**Comment by ronie** [comment]
why not? our DVDPlayer is gone, dead, burried, will never come back :-)

**Comment by tamland** [comment]
Because it breaks the addons you mentioned for no reason whatsoever. This has nothing to do with DVDPlayer and VideoPlayer. It even contains a typo. camel case instead of upper case.

**Comment by tamland** [comment]
Also python 2.6 > 2.7.10 is not an api change. IMO we should restrict api bumps to when there are changes that actually might be worth knowing about for addons. Otherwise, what's the point of versioning?

**Comment by MartijnKaijser** [comment]
Ìt's not an oversight. It's intentional and that method should die a horrible death to let addons pick the player this way. It has already extensively discussed over time and the proper method would be to let addon call core to see what players are available and pick from that.

**Comment by tamland** [comment]
Then why add the new `PLAYER_CORE_VideoPlayer` constant? The way to do this is simply ignore the choice, not forcefully remove the constant and introduce `AttributeError` to everything attempting to reference it.

**Comment by MartijnKaijser** [comment]
ask @FernetMenta. For all care that method of calling a specific player is dead and don't allow it to repo on any update.

**Comment by ronie** [comment]
> Also python 2.6 > 2.7.10 is not an api change. IMO we should restrict api bumps to when there are changes to our api that actually might be worth knowing about for addons.

while not strictly an API change, this is surely something addons devs should know about.
the bump has been requested by devs many times as they had to implement workarounds to bugs that existed in 2.6. 
that code can be dropped now.

also the PIL to Pillow change might require (haven't checked yet) some addons to fix their import method of the module.

another main advantage of 2.7 is that addons can/should now use the included json module instead of depending on simplejson. simplejson is utterly slow compared to json and imo we should consider removing it from our K*** repo.

**Comment by tamland** [comment]
Merge now? The situation now with the render capture change is not good. People are already developing for it but there is no way to check the api version (you have to resort to try/except)

**Comment by ronie** [comment]
yup, makes sense.

**Pull request merged**
