### PR TITLE
[osx][droid] target zlib Makefile modified to ensure correct compiler

### PR DESCRIPTION
**Pull request by kraka40**
## Description
 Allowed for full compile of android apk on osx platform. The zlib library was incorrectly picking up the native archiving tools. 

The addition of CROSS_PREFIX to the Makefile configuration command ensures that the correct target binaries are utilized.  The zlib configuration script makes assumptions when using CHOST to guess target operating system (uname).  To get around this, --uname=$HOST is added to the configuration parameters.

## Motivation and Context
Allows for android cross compile of OSX

## How Has This Been Tested?
Tested on OSX only, produced a valid an functioning apk. apk side-loaded to firetv gen1 and operating.

Darwin Kernel Version 16.5.0
NDK 12.1.2977051
SDK 25.2.5
javac 1.8.0_111

## Types of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
ping @Memphiz

**Comment by Memphiz** [comment]
Not complete maybe -  I am working on it here https://github.com/xbmc/xbmc/pull/12059

**Comment by Memphiz** [comment]
Correct me if i am wrong - but are native compilers not just called "gcc" without any prefix?

**Comment by kraka40** [comment]
@Memphiz native compiler should be gcc, as to prefix not sure .. i'm sure a prefix could be added to pick up a specific gcc version locally if the system has multiple versions. 

As to the failed checks with my patch .. don't understand why they failed as they seem completely unrelated to zlib compilation or zlib library utilization
.

**Comment by Rechi** [comment]
@Memphiz compiler is always the one specified as CC so that isn't an issue.
In my opinion #12059 is the way to go because it removes the hardcoded `AR` and `ARFLAGS` for darwin.
It should always use the values defined by the depends configure step.
Also I'm not sure if this breaks other platforms, although it doesn't look like it will break anything.

**Comment by MartijnKaijser** [comment]
@Memphiz is this still relevant now your PR was merged?

**Comment by Memphiz** [comment]
Not really - I would need to backport those changes from master instead of this PR

**Comment by MartijnKaijser** [comment]
Let's close this. @kraka40 thx for helping out regardless

**Comment by kraka40** [comment]
No problem. Change is pretty simple regardless should a backport be required.

**Pull request closed without merging**
