### PR TITLE
IMX: Special case D: modes

### PR DESCRIPTION
**Pull request by fritsch**
This was brought up in the osmc forum. Users with DVI monitors still missed some modes - Here is the output of the modes:

```
S:1280x1024p-60
S:1152x864p-75
V:1280x1024p-75
V:1024x768p-75
V:1024x768p-60
V:800x600p-75
V:800x600p-60
V:640x480p-75
V:640x480p-60
U:720x400p-70
D:1680x1050p-59
V:640x480p-60
```

See the D: mode which is entirely special. It is added last.

### CODE REVIEW

**Comment by fritsch** [comment]
@koying ping - Another one from that series to make DVI users happy. As you see in the above output, when we would not enumerate D: he could not have his native resolution. Duplicate check is done anyways.

**Comment by koying** [comment]
This is getting really messy, but hey, fine by me ;)
If you are bored, IMO, you might as well remove the "lexical sort" stuff altogether. I think it was barely acceptable when generic (from a readability pov) but now is really ugly.

**Comment by fritsch** [comment]
We still need that - as we might have duplicate D modes, in the sense of same width, height, refreshrate, but probably not audio aware? Therefore I wanted to handle those last :-)

**Comment by koying** [comment]
Sure. But would't 4 vectors and an "obvious" ("S" then "U" then "V" then "D") merge be more readable? No performance issues, here.

**Comment by fritsch** [comment]
Hehe, obviously yes :-)

2015-05-14 20:38 GMT+02:00 Chris Browet <notifications@github.com>:

> Sure. But would't 4 vectors and an "obvious" ("S" then "U" then "V" then
> "D") merge be more readable? No performance issues, here.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/xbmc/pull/7139#issuecomment-102131065>.
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by koying** [comment]
Up to you, just a suggestion ;)

**Comment by fritsch** [comment]
Not so sure anymore: http://sprunge.us/Ojfh you decide.

**Comment by koying** [comment]
Yeah, it's cumbersome vs. cumbersome ;)
But at least, what is happening seems more clear with v2, and it will be easier if someone decides a "V:" is better than a "U:" :)

**Comment by mk01** [comment]
@fritsch 

order in /sys/..../modes has nothing to do with order in which those are parsed into xbmc. 
remember imx6 can't play 59hz, but you will parse into xbmc with refresh 59hz. imx6 on setting this mode will internally setup 60hz. dbmandrake already confirmed, that the screen is distorted. 

also don't be "fixing" perspective around VUDS. this has no impact to any operations - it is only informative value shown by fb subsystem what was origin of that particular video mode. 

if you simply want Detailed modes without considering all the impacts first, just add 
```
&& !StringUtils::StartsWith(probe_str[i], "D:")
```

there is no need to invent wheel again.

**Comment by fritsch** [comment]
@mk01 

Can you reword your post, please? The code does not assume any order, it parses the modes and orders them the way we want it. If you say, that the 1680 Mode do not work anyways, then this PR os obsolote and I will close it.

Concerning the "new wheel": The code is much clearer than it was before, we get rid of the sorting which is O(n log n) anyways + O(n) for going through the list in favor of O(2n) \in O(n).

While we are at parsing: I could not parse that part of your comment :-)

**Comment by mk01** [comment]
@fritsch 

I wasn't commenting the algorithm complexity. "wheel" means - it parses the modes and orders them the way we want it exactly as before. there is no change in workflow nor result. only one liner is replaced with few cycles, four new array definitions and array handling code. nothing more no less.

And it is not up to me to judge readability, I'm not maintainer.

I'm trying to say that (until) the other problems (or scenarios considered) the straight forward solution is simply allow D: in the if. Then it will start (showing in /sys/..../mode) D: in that particular case. 
If you change to SUVD, you will not conform to EDID 1.3+. Best case they are the same, worst case you choose a mode with timing not be "native".
And (again) still consider the current internals of FB subsystem which ignores "GTF Supported" flag and calculates ALL D: modes via GTF (creating those *59 broken variants).

**Comment by fritsch** [comment]
That's exactly the issue, when adding the if clause, they have more priority than S modes and are evaluated before hand and the doublete match algorithm will filter the S modes out!

Therefore D has to go behind the others.

**Comment by mk01** [comment]
@fritsch 

what you described as a problem, is what should happen. it is as EDID standard expects.
now I start be confused what 'issue' are we trying to hunt.

**Comment by fritsch** [comment]
We try to get DBMandrakes 1680x1050 mode being enumerated.

**Comment by fritsch** [comment]
As further discussed on IRC - I will close this. This is against spec and from what I figured - the monitor needs fixing :-)

**Pull request closed without merging**
