### PR TITLE
AESinkAudioTrack: Pause-Burst - a little revisit

### PR DESCRIPTION
**Pull request by fritsch**
v1: Initial
v2: Include extra_sleep as this is wallclock time
v3: Filter broken hw-delay
v4: Let pause faked by smoothing
v5: Don't sleep if buffer empty
v6: Reality check
v7: Smooth out
v8: Early exit smoothing if buffer reached
v9: Fine tune once more

The RAW API is one of the worst things google has to offer. It was not meant to be A/V sync compatible as important methods like creating and pushing pause_bursts is not possible. That's why kodi's sink fakes the non existing pause by "pausing" the sink and sleeping the pause away. After player resumed it tries to push as fast to reduce the buffer_size offset by pushing real samples. When real sample's buffer matches audio sink's buffer we continue normal playback.

### CODE REVIEW

**Comment by fritsch** [comment]
I implemented this while looking for a Sony Defect here: https://github.com/xbmc/xbmc/issues/20911 - sadly there is another issue, where the sink (firmware) decides to run full ... adb might help here.

@thexai could you please take a small look if I have forgotten something needed for TrueHD after the "ratio" rework. Thanks much.

I tested this on FireTV 4K Max: AC3, DTS and E-AC3 (5.1)

**Comment by thexai** [comment]
Tested on Shield 2019 with RAW and no issues found. Tested TrueHD, DTSHD-MA, DTS, AC3 and DD+.

**Comment by thexai** [comment]
From https://github.com/xbmc/xbmc/pull/20550 ratio changes only affects IEC. RAW path is as before.

**Review by thexai — APPROVED** [review]

**Comment by fritsch** [comment]
Awesome. Thanks very much. Any slight improvement on e.g. seek? Or "old one" also worked okayish?

**Comment by thexai** [comment]
Seek works well all formats except TrueHD (no sound after seek 50% of times) but as Shield has IEC is not need use TrueHD + RAW. Probably on other devices that only support RAW they don't support TrueHD anyway.

Note that "TrueHD + RAW + seek" issue has always existed I think.

**Comment by fritsch** [comment]
If you have a component log of the seek issue for TrueHD, feel free to post - let's see what happens. Thanks again for testing.

**Comment by thexai** [comment]
Log has many lines not fit on paste.kodi.tv:
[kodi.zip](https://github.com/xbmc/xbmc/files/7966597/kodi.zip)

Played TrueHD file and 3 seeks

**Comment by fritsch** [comment]
Thanks much, that TrueHD seeking does not look good at all. It seems the Sink is not moving anymore, while still properly eating data. Some kind of flush / stall detection would be good. If e.g. the timestamp or head position does not move for let's say 1 seconds -> reset the sink by returning something to AE in that case.

**Comment by fritsch** [comment]
```
diff --git a/xbmc/cores/AudioEngine/Sinks/AESinkAUDIOTRACK.cpp b/xbmc/cores/AudioEngine/Sinks/AESinkAUDIOTRACK.cpp
index 6cc19ffb4e..61cb38ded7 100644
--- a/xbmc/cores/AudioEngine/Sinks/AESinkAUDIOTRACK.cpp
+++ b/xbmc/cores/AudioEngine/Sinks/AESinkAUDIOTRACK.cpp
@@ -608,6 +608,7 @@ bool CAESinkAUDIOTRACK::IsInitialized()
   return (m_at_jni && m_at_jni->getState() == CJNIAudioTrack::STATE_INITIALIZED);
 }
 
+static int watchdog = 0;
 void CAESinkAUDIOTRACK::GetDelay(AEDelayStatus& status)
 {
   if (!m_at_jni)
@@ -628,7 +629,13 @@ void CAESinkAUDIOTRACK::GetDelay(AEDelayStatus& status)
     m_headPos += (1ULL << 32); // add wraparound, e.g. 0x0000 FFFF FFFF -> 0x0001 FFFF FFFF
   // clear lower 32 bit values, e.g. 0x0001 FFFF FFFF -> 0x0001 0000 0000
   // and add head_pos which wrapped around, e.g. 0x0001 0000 0000 -> 0x0001 0000 0004
-  m_headPos = (m_headPos & UINT64_UPPER_BYTES) | (uint64_t)head_pos;
+  uint64_t hp = (m_headPos & UINT64_UPPER_BYTES) | (uint64_t)head_pos;
+  if (m_headPos == hp)
+    watchdog++;
+  else
+    watchdog = 0;
+
+  m_headPos = hp;
 
   double gone = static_cast<double>(m_headPos) / m_sink_sampleRate;
 
@@ -777,6 +784,12 @@ unsigned int CAESinkAUDIOTRACK::AddPackets(uint8_t **data, unsigned int frames,
   if (!IsInitialized())
     return INT_MAX;
 
+  if (watchdog == 20)
+  {
+     watchdog = 0;
+     return INT_MAX;
+   }
+
   // for debugging only - can be removed if everything is really stable
   uint64_t startTime = CurrentHostCounter();
```

Yes - it's a hack but maybe it helps when AE reconfigures us in this case ...

**Comment by thexai** [comment]
Behavior changes but still happening with the diff:

After seek sound it takes 0.5 or 1s to come and many times it seems to come back OK but it goes away after 4 or 5 seconds and it doesn't come back. Other times it doesn't go away completely but stays choppy all the time.

Without diff: 
These 4-5 s after seek with sound OK does not happening. The sound returns choppy at the moment after seek or does not return.

**Comment by thexai** [comment]
Similar behavior can be observed with Kodi IEC if these code is removed:

https://github.com/xbmc/xbmc/blob/bffe7c98c7bd701c5bd36e6c9740f4bd14f0de84/xbmc/cores/AudioEngine/Utils/AEBitstreamPacker.cpp#L227

**Comment by fritsch** [comment]
Good. Then most likely sadly something that needs fixing inside their packer.

Btw. The 20 was chosen arbitrarily as a first test hack... I don't want to make a second one :-). Let's keep it as is for now.

**Pull request merged**
