### PR TITLE
[gif] Try to skip erroneous frames instead of giving up immediately.

### PR DESCRIPTION
**Pull request by ace20022**

### CODE REVIEW

**Comment by ace20022** [comment]
For @ronie please test.

**Comment by ace20022** [comment]
jenkins build this please

**Comment by ronie** [comment]
thanx, it doesn't fully fix the issue...
the animation doesn't loop. all frames are only displayed once and it stops at the last frame.

**Comment by ace20022** [comment]
Could you please double check? The last frame has a display time oft appr. 5 seconds.

**Comment by ronie** [comment]
yeah, i'm aware. it doesn't loop at all.

**Comment by ace20022** [comment]
It does loop for me, tested as background image. Can you provide a "sample" of who you use it?

**Comment by ronie** [comment]
using current master with this PR applied on ubuntu 15.10
i'm using the image provided here: https://github.com/xbmc/xbmc/pull/8188#issuecomment-167374459
and have set it as a custom background in Confluence

log: http://xbmclogs.com/pu2w2gw0b

**Comment by ace20022** [comment]
That's the same I did. Then it must be your libgif version, I'll temporarily add more logging.

**Comment by ace20022** [comment]
@ronie Please retry and post the log.

**Comment by ronie** [comment]
i'm using giflib 4.1.6 and it didn't compile (because GIFLIB_MAJOR, GIFLIB_MINOR, GIFLIB_RELEASE are undefined) so i had to manually define them in gif_lib.h first.

here's the log:
http://xbmclogs.com/p8spay2ba

**Comment by ronie** [comment]
ubuntu 15.10 ships with giflib 4.1.6

if i compile kodi against giflib 5.1.1 everything works ok.

**Comment by amet** [comment]
@ronie/ @ace20022 

trying to package gifs from https://github.com/JezzX/skin.pm3-hd/tree/master/media it fails on giflib 5, giflib 4 works fine.

**Comment by ace20022** [comment]
Hi @amet Could you please describe the exact steps? I have zero knowledge of skin packaging

**Comment by amet** [comment]
Hi @ace20022 , I do it on OS X and we used 5.1.0 on it.

I tried to package PM3.HD skin by running make xcode_depends and kept getting an error with 5.1.0, since we have a support for 4.* I figured that works.. screw it :)

I am on IRC if its easier

**Comment by ace20022** [comment]
@ronie I think I found it, could you please confirm?
@amet thx for the pointer! Texturepacker's (gif) code is outdated and there's a wrong #ifdef so that every version < 5 can't work.

**Comment by ronie** [comment]
confirmed! it's looping like a pro now. :-)

would you consider this backport material or to risky?

**Comment by ace20022** [comment]
jenkins build this please

**Comment by ace20022** [comment]
The addon build error is unrelated.

**Comment by wsnipex** [comment]
this breaks building with giflib 5.0.x. as we use for our PPAs:
https://launchpadlibrarian.net/232955751/buildlog_ubuntu-wily-i386.kodi_2%3A17.0~git20160105.0200-8e324f2-0wily_BUILDING.txt.gz

**Pull request merged**
