### PR TITLE
cmake: provide more control over the platforms a binary addon's dependency is built for

### PR DESCRIPTION
**Pull request by Montellese**
These commits are taken from #6227. They add support for the same `platforms.txt` for binary addon dependencies as is already supported for binary addons. Right now a binary addon's dependency can only be put into either the `depends/common` directory (which means that it's built for all platforms) or into the `depends/${CORE_SYSTEM_NAME}` (e.g. `depends/android`) directory (which means that it's only built for that platform). If a dependency is used by multiple but not all platforms we'd have to create the same dependency definition in multiple platform target specific directories which makes it harder to update the dependency and easier to miss a platform.
With this change it becomes possible to define such a dependency in `depends/common` but provide an additional `platforms.txt` with a specific list of platforms.

The logic is taken almost 1:1 from the `CMakeLists.txt` for binary addons so maybe it could be extracted into a separate helper method.

The last two commits clean up the logic that puts together the list of dependencies for a binary addon and how it's made available to the binary addon buildsystem.

### CODE REVIEW

**Comment by Montellese** [comment]
OK I have extracted the logic that checks and parses `platforms.txt` into a new `check_target_platform()` function which is used by the main `CMakeLists.txt` and `handle-depends.cmake`.

**Comment by Montellese** [comment]
jenkins build this please

**Comment by Montellese** [comment]
@wsnipex @notspiff: any objections or anything that should be different?

**Comment by Montellese** [comment]
IOS jenkins failure is unrelated (git problems). All other platforms are fine.

**Comment by wsnipex** [comment]
looks fine to me.

**Pull request merged**
