### PR TITLE
[osx] - fixed compilation of testsuite

### PR DESCRIPTION
**Pull request by Memphiz**
what the title says ...

### CODE REVIEW

**Comment by FernetMenta** [comment]
thanks. sorry, wasn't by intent

**Comment by Memphiz** [comment]
I know :) question is how to make those ac3 matching unit tests work again. how are we supposed to get the bitsperchannel now that the DataFormatToBits function returns 8 bits for AE_FMT_RAW?

**Comment by fritsch** [comment]
That won't work too easily as it needs the StreamInfo now to tell the bits ... during that transition I added some new functions that does the old job but uses the StreamInfo instead ...

**Comment by Memphiz** [comment]
where is it - i can use that instead but didn't spot it in the commits tbh

**Comment by fritsch** [comment]
Sorry - I was not clear enough - I had to do that in my PulseAudio Sink. As it is currently, we need to reimplement  StreamInfoToBits methods

**Comment by Memphiz** [comment]
That would be helpfull i think - are you able to work on that?

**Comment by Memphiz** [comment]
How come that AE_FMT_RAW has 8 bits btw? ^^ shouldn't it be 0 because its an "invalid" format somehow?

**Comment by FernetMenta** [comment]
that means that one byte of raw data is conveyed as one byte in AE. this is raw encoded data. what do you intend to do with it?

**Comment by FernetMenta** [comment]
AE treats a 100 byte of raw data as 100 frames, 1 channel, 8 bits.

**Comment by fritsch** [comment]
https://github.com/xbmc/xbmc/blob/Jarvis/xbmc/cores/AudioEngine/Utils/AEUtil.cpp#L128 <- it was used in some places.

**Comment by fritsch** [comment]
Just returning 16 for all AE_FMT_RAW would restore the old behaviour - though it had totally different semantics.

**Comment by FernetMenta** [comment]
those sinks you mentioned don't get any raw data. they get iec encoded data

**Comment by fritsch** [comment]
Yes, you are right.

**Comment by Memphiz** [comment]
I could also just hard code it in the osx sink - is 16 bit per channel correct for all passthrough formats including hd bitstreaming?

**Comment by FernetMenta** [comment]
16 bit per channel is correct for iec encoded passthrough (that is the only format we have currently)

**Comment by Memphiz** [comment]
So the decision is to hardcode it in the sink?

**Comment by FernetMenta** [comment]
not sure if hardcode is the right term here. AE initializes the sink with AE_FMT_RAW. Then the sink decides if it wants pure raw or iec encoded raw. it it is iec, the sink sets data format to AE_FMT_S16

**Comment by Memphiz** [comment]
Now i am tilt ... So the osx sink is borked for sure when it comes to passthrough atm right? (It Never Sets this Format iirc)

**Comment by FernetMenta** [comment]
what does it set there?
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/AudioEngine/Sinks/AESinkDARWINOSX.cpp#L290

**Comment by Memphiz** [comment]
thats for bitstreaming when the sink has no native ac3 stream in the device (then we use a 16bit stereo pcm stream instead)... so i need to do this in the native case too now?

**Comment by FernetMenta** [comment]
I don't have a clue what you call "native". In version < 17 all that AE did support was iec packed bitstreaming. That was transmitted via PCM 16 bits. Now for passthrough a sink can chose between iec packed and raw.

**Comment by Memphiz** [comment]
on osx the sound device can either have dedicated ac3 / dts stream - we called that native - pther devices don't have this sort of streams but are digital (like hdmi) - in those cases we picket a 2.0 pcm 16bit stream from the device to passthrough ac3/dts - that is what we are refering to bitstreaming in the sink. Before we only altered the aeformat in the sink initialize when AE_FMT_AC3 was requested and we had no native stream for it - indeed we changed the format to AE_FMT_S16 - in case we had a native stream we simply left it to AE_FMT_AC3 - i guess now with the introduced AE_FMT_RAW i am supposed to set S16 in both cases - right?

**Comment by FernetMenta** [comment]
Before formats like AE_FMT_AC3 did not even (really) exist. AC3 was iec packed and was transmitted as S16. In the current state no sink is capable of accepting raw, at least Audiotrack will be, that was the reason for this change.
The sink knows whether it can accept raw or iec packed raw. If the sink requests iec packed (again this is the only format we were dealing with so far), it should also request S16.
For raw it should request AE_FMT_RAW. (we don't have this case yet)
I don't think the OSX sink can handle real raw data, other than iec packed.

**Comment by Memphiz** [comment]
Ok - thx for that Info - in that case it is clear to me what to do to fix the sink :)

**Comment by FernetMenta** [comment]
you did not even tell me if it is broken or not :) this is all about testsuite, isn't it?

**Comment by Memphiz** [comment]
I had no time to Test it but based on what the Test Suite does its broken pretty sure (it simply won't find suitable streams for Pass through because of 16bit is not 8bit in the if Statement in scoreformat) - even if i fix that it still would Leave AE_FMT_RAW untouched in Case we have native ac3/DTS streams in the audio device - and i am sure in that case when AE would Feed the sink with real RAW Data it wouldn't work ...

**Comment by FernetMenta** [comment]
you could have said earlier that there is is a problem with the osx sink. I just need to attach my mac to HDMI and fix it. much faster and more efficient than this silly test suite :)

**Comment by Memphiz** [comment]
sorry - i think it went into my comment for this commit - https://github.com/xbmc/xbmc/commit/071d9423d5dc0632f3505627f5adc73cea0d528e#diff-5aa21af1dad0024b0b8aadbd4b6acbe5 (the changeset for aeutil.cpp) and i forgot to state it here again...

**Pull request merged**
