### PR TITLE
remove Audio DSP, it is unmaintained and not in a working state

### PR DESCRIPTION
**Pull request by FernetMenta**
I had hoped that we get this working for v18 but it turned out that this won't be the case. In the current state it makes no sense to carry not working bits in master.

### CODE REVIEW

**Comment by fritsch** [comment]
@AchimTuran could you give us your +1 as well?

**Comment by AchimTuran** [comment]
But also please ask @AlwinEsch as he did some rework of the AudioDSP binary add-on API.

**Comment by FernetMenta** [comment]
the code is still in git if somebody wants to resurrect the code. for current master all code removed by this pr is dead code.

**Comment by gade01** [comment]
Should DialogAudioDSPManager.xml be removed from skins with this PR?

**Comment by FernetMenta** [comment]
@gade01 thanks, I'll remove those

**Comment by ksooo** [comment]
Please also remove CONTEXT_BUTTON_ACTIVE_ADSP_SETTINGS which still can be found in xbmc/dialogs/GUIDialogContextMenu.h

**Comment by FernetMenta** [comment]
done

**Comment by FernetMenta** [comment]
it does not apppear on search

**Comment by fritsch** [comment]
Will send a PR:
```
fritsch@t440s:~/Desktop/xbmc-fritsch/xbmc$ git grep -i OSDAudioDSPSettings
addons/skin.estouchy/xml/Includes.xml:                  <onclick>ActivateWindow(OSDAudioDSPSettings)</onclick>
addons/skin.estuary/xml/DialogSettings.xml:                     <visible>![Window.IsActive(osdaudiodspsettings) + Window.Is(osdaudiosettings)]</visible>
addons/skin.estuary/xml/VideoOSD.xml:                   <visible>![Window.IsVisible(SliderDialog) | Window.IsVisible(osdaudiosettings) | Window.IsVisible(osdvideosettings) | Window.IsVisible(OSDAudioDSPSettings) | Window.IsVisible(VideoBookmarks) | Window.IsVisible(playerprocessinfo) | Window.IsVisible(osdcmssettings) | Window.IsVisible(PVROSDChannels) | Window.IsVisible(pvrchannelguide)]</visible>
```

**Comment by Sidordroid** [comment]
The sound of music tracks in Kodi leaves much to be desired. Especially there is not enough low frequencies. Please implement the ability to enable low frequencies when watching videos and listening to music

**Comment by garbear** [comment]
@Sidordroid a two-year-old PR is not really the place to post a feature request.

If you believe this is actually a bug, you can file a GitHub issue (and please follow the template).

Feature requests, instead, should be posted on the forum.

**Pull request merged**
