### PR TITLE
Move to C++11; use as much std:: instead of boost:: as possible

### PR DESCRIPTION
**Pull request by Memphiz**
superseed of #6023

This solves crashes on x86 droid (at least on Nexus Player).
sry @koying to risky that someone poissons the tree again. Also i told you that i will beat you to it ;)Move to C++11; use as much std:: instead of boost:: as possible
superseed of #6023

This solves crashes on x86 droid (at least on Nexus Player).
sry @koying to risky that someone poissons the tree again. Also i told you that i will beat you to it ;)

### CODE REVIEW

**Comment by Memphiz** [comment]
jenkins build and merge

**Comment by MartijnKaijser** [comment]
@Memphiz build failed after it compiled successfully because I think disk is full one of the osx builders

**Comment by koying** [comment]
Hehe... Was a bit confused this morning seeing the other one was closed ;) 
Thanks @Memphiz for your hard work. 

I promise I won't do that again either ;)

**Comment by Memphiz** [comment]
@MartijnKaijser it failed because even my first try to disable osx32 uploads was improper ;) - should be fine from now on.

**Comment by MartijnKaijser** [comment]
or that :) Just briefly looked through the log and saw it build and some ignore low disk warning so thought that was it. 
Thanks for sticking with this PR and getting it in :)

**Pull request merged**
