### PR TITLE
[inputstream] bye, bye libKODI_inputstream.cpp

### PR DESCRIPTION
**Pull request by AlwinEsch**
Remove the dll for inputstream addons

## Description
The libKODI_inputstream.* is no more needed

## Motivation and Context
Cleanup to remove not needed and complicated parts

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by AlwinEsch** [comment]
jenkins build this with addons please

**Comment by afedchin** [comment]
jenkins build this with addons please

**Comment by MartijnKaijser** [comment]
I sure hope you have runtime tested this!

**Comment by AlwinEsch** [comment]
Yes, with inputstream.mpd.

bildschirmfoto vom 2016-12-12 00-28-52

**Pull request merged**
