### PR TITLE
[CDatabase] Fix return value during CreateDatabase()

### PR DESCRIPTION
**Pull request by AchimTuran**
When CommitTransaction() fails, we would never see it. This fixes the return value.

### CODE REVIEW

**Comment by Montellese** [comment]
Looks good, thanks.

**Comment by AchimTuran** [comment]
Can I merge this PR?

**Comment by hudokkow** [comment]
@Montellese ACK and added to beta3, so I would say yes.

**Comment by Razzeee** [comment]
There are two more places in this class where this might be nice to add.

**Comment by stefansaraev** [comment]
from what I see current code does not rely on CreateDatabase() return value. at all. zero chance to break  something. so this is ok for immediate merge ;)

**Comment by AchimTuran** [comment]
> There are two more places in this class where this might be nice to add.

Thx @Razzeee I will add those fixes to.

> from what I see current code does not rely on CreateDatabase() return value. at all. zero chance to break something. so this is ok for immediate merge ;)

Aftewards I'm fine with merging this commit.

**Comment by stefansaraev** [comment]
> But I'm not sure about the fixes from 521 - 566. Would be nice if someone could review

looks ok to me. jenkins build this please

**Comment by Razzeee** [comment]
jenkins build and merge

**Comment by Razzeee** [comment]
jenkins build and merge

**Comment by stefansaraev** [comment]
unrelated win32 addon build fail

**Pull request merged**
