### PR TITLE
[pm] resume last played media after sleep

### PR DESCRIPTION
**Pull request by xhaggi**
Follow-up of #13138. I just want to push things forward and @Falcosc didn't find time to adjust his PR.

> Auto resume the media which was used during enter sleep mode and resumes it on wake with forced play (playerstate handling is already implemented as part of resume point but I don't know why the player state is allways empty, this issue does force play on my PR)
But this is only the first step, a very basic solution which could be improved step by step.

### CODE REVIEW

**Comment by Voyager1** [comment]
there may be an issue with resuming the playback of ISO's and ISO stack parts. 
For ISOs you can first of all not use the getTime, you need to save player state (its a string that serializes the internals of the navigator). Upon resume you have to restore the player state to resume playback.
For ISO stacks, the current file item is the stack part, not the stack itself. But to properly resume, you need to start from the stack. So upon stopping you should save the stack (get it via stackHelper), save the current part number (get it also via stackHelper) and the player state! To resume, you need to PlayFile the stack (not the part), with setting the part number and the offset. It will eventually reopen the correct part. The problem is that you can't (at this point) pass the playerstate, only use START_OFFSET_RESUME, which goes to the video db... So if needed we will have to find a solution to get the state from memory instead of the db.

**Comment by FernetMenta** [comment]
@Voyager1 how about merging this and you add resume for stacks later? seems nobody but you is familiar with this.

**Comment by Voyager1** [comment]
@FernetMenta @xhaggi makes sense. It's not only for ISO stacks but, before that, for normal ISOs as well that you need to save player state and populate options.state before starting playback. So I suggest we remove the wip commit and merge. Also, I will need a way to debug this without putting my machine to sleep all the time :-)

**Comment by xhaggi** [comment]
Ok will drop the WIP commit.

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by xhaggi** [comment]
@ksooo I removed the call to `TriggerPlayChannelOnStartup` from `CPVRManager::OnWake()`. If we really need to force playing TV after sleep we could address it later.

**Review by FernetMenta — APPROVED** [review]
looks good to me

**Pull request merged**
