### PR TITLE
[lang] Add proper support for custom languages

### PR DESCRIPTION
**Pull request by ace20022**
The first commit adds custom languages to our language lists, e.g., preferred subtitle language.
The second one adds support of custom languages to our conversion methods and therefore support for preferred selection and presentation of the name in the gui.

For example Portuguese (Brazil) can be added via:

```
<advancedsettings>
<languagecodes>
  <code>
    <short>ptbr</short>
    <long>Portuguese (Brazil)</long>
  </code>
</languagecodes>
</advancedsettings>
```

### CODE REVIEW

**Comment by uNiversaI** [comment]
neat, would this support
```
<advancedsettings>
<languagecodes>
  <code>
    <short>pt_br</short>
    <long>Portuguese-Brazil</long>
  </code>
</languagecodes>
</advancedsettings>
```

Or is just restricted to that format you exemplified?

**Comment by Paxxi** [comment]
I don't approve of the short format, no need to invent our own when there's a perfectly good standard already. Should be as @universal mentioned

**Comment by ace20022** [comment]
There are absolutely no constraints. If I would add restrictions the feature would be useless.

**Comment by Paxxi** [comment]
Maybe i misunderstood the feature, can you give an example of why and where this would be used?

**Comment by Montellese** [comment]
I'd also be interested in who is using such odd codes like `ptbr`.

**Comment by ace20022** [comment]
Currently we don't support Portuguese (Brazil) or any non iso lang, but our subs services do.
IIRC this worked for installed languages before. @Wanilton brought this up, maybe he can explain it better than I. Also a user might prefer Klingon subs, who knows.

**Comment by Wanilton** [comment]
I request this for Ace20022, for now Portuguese (Brazil) or any other non ISO language, don´t list for select anymore in subtitles area, get subtitle via GUI is a great feature, Portuguese and Portuguese (Brazil), are distinct, and now only Portuguese is available. I compiled master with this PR and work great. I don´t know if is necessary short, but long is.

Thanks Ace20022.

**Comment by uNiversaI** [comment]
I agree with @Wanilton Portuguese Brazil and Portuguese Portugal are distinct like imo similar differences English GB and English US. 

But yes, no restrictions makes sense so one can use whatever is available then.

**Comment by Paxxi** [comment]
The feature as such seems good but I'm still wondering why not use the iso format of language_region. Is this sent somewhere outside of Kodi requiring random language strings?

**Comment by ace20022** [comment]
> I'm still wondering why not use the iso format of language_region.

I do not know even one media "standard" that uses language_region for languages.

Just to be sure, the advanced setting is there since ages. You can use whatever format you want.
Adding all regions to the language list will make that list "unbrowsable" imo. Also I guess we don't have a list of all possible regions. Furthermore we use ISO 639-2/T codes whenever possible.

The only thing that comes to my mind is to add installed languages to the list. But that will not cover all (odd) cases. In our Brazil language addon we have https://github.com/xbmc/repo-resources/blob/isengard/resource.language.pt_br/resources/langinfo.xml. So we get pt as language code when looking up ```Portuguese (Brazil)```. Hence the file name will be ```sub.pt.ext``` and therefore we get ```Portuguese``` when re-reading the file.

 I've just check opensubtitles and Brazil: https://github.com/amet/service.subtitles.opensubtitles/blob/Gotham/service.subtitles.opensubtitles/service.py#L143 There are special cases for two languages. ```Portuguese (Brazil)``` is mapped tp ```pob```. 

I sum I don't think that rewriting a whole lot of our code just to support some odd cases that can be handled via an adv. setting is worth the effort.

And if others of the team don't want this, then please vote -1 before the 20th.

**Comment by Paxxi** [comment]
I'm satisfied with that explanation, ok to merge from me

**Comment by mkortstiege** [comment]
+1

**Comment by ace20022** [comment]
@Montellese okay?

jenkins build this please

**Comment by Montellese** [comment]
Sure it's not very intrusive.

**Comment by hackedbellini** [comment]
Sorry for commenting on an already closed PR.

Someone on irc pointed this for me when I commented about this issue: http://trac.kodi.tv/ticket/15932

I still need to test kodi again to see if the issue was really fixed. But just a quick comment... Should this PR be the "fix" for my issue, or not exactly?

**Comment by MartijnKaijser** [comment]
No it doesn't change it

**Comment by ace20022** [comment]
@hackedbellini Don't use github for such questions. If you want to have "Portuguese (Brazil)" in that list use:
```
<advancedsettings>
<languagecodes>
  <code>
    <short>ptbr</short>
    <long>Portuguese (Brazil)</long>
  </code>
</languagecodes>
</advancedsettings>
```

So it fixes your issue in some way

**Comment by palula** [comment]
Hello everybody!

Currently I'm using [OpenELEC's](http://releases.openelec.tv/OpenELEC-RPi2.arm-6.0.0.img.gz) last bundle (which at the moment of this post, ships with [Kodi Isengard 15.2](http://kodi.tv/kodi-15-2-isengard-release-candidate/).

Albeit using the XML excerpt available here, I could see the changes in the subtitles --- my subtitles section of Kodi's configuration shows Portuguese (Brazil) --- however, there were no noticeable changes when downloading subtitles and the resulting message is always **No subtitles found**.

**Comment by MartijnKaijser** [comment]
Use the forum

**Comment by fernandog** [comment]
@ace20022 can you take a look a this? I think it's an issue. Don't know if trac notified you when i tagged you.
thanks

http://trac.kodi.tv/ticket/15932#comment:10

**Pull request merged**
