### PR TITLE
[guilib] auto-width for button controls

### PR DESCRIPTION
**Pull request by mkortstiege**
This adds auto-width for button controls. Needs some testing.

### CODE REVIEW

**Comment by phil65** [comment]
Skinners will love you for this :)
Thx!

**Comment by mkortstiege** [comment]
Added a commit that enables auto-width for togglebutton controls

**Comment by phil65** [comment]
@HitcherUK mind givin this a shot?

**Comment by HitcherUK** [comment]
Downloading now, will report back later.

PS Many thanks. ;)

**Comment by HitcherUK** [comment]
Looking good so far except for strings with line breaks in them as seen here for **Artwork[CR]Downloader**

image

**Comment by mkortstiege** [comment]
@HitcherUK, works for me. Mind sharing the skin xml so i can test it?

**Comment by HitcherUK** [comment]
Here you go -

http://pastebin.com/rnVGUKsY

I've moved the strings from the language file so you can see them properly. It seems to widen the button more than the others but not enough.

Thanks.

**Comment by mkortstiege** [comment]
Updated and rebased. @HitcherUK, new test build is triggered and should be ready in ~1h.

**Comment by HitcherUK** [comment]
@mkortstiege Fixed the textoffsetx problem but there's a slight problem with the togglebutton.

Default label -

screeshot

Alt label -

screenshot

The `<altlabel>...</altlabel>` seems to be using the width of the `<label>...</label>` when it comes to spacing in the grouplist.

Test code - http://pastebin.com/eM50ykq9

Browse to a TV show and press info.

Thanks.

**Comment by mkortstiege** [comment]
Will be part of https://github.com/xbmc/xbmc/pull/7384

**Comment by mkortstiege** [comment]
Reopened and rebased. jenkins build this please

**Comment by mkortstiege** [comment]
Added wrapline for button controls commit.

**Comment by mkortstiege** [comment]
Rebased. @BigNoid, @HitcherUK, @phil65 and @ronie would be cool if you guys could give this one a try.

**Comment by HitcherUK** [comment]
@mkortstiege could you provide a build for testing please? If not, I'll give me a day or so and I'll do my own.
Thanks.

**Comment by MartijnKaijser** [comment]
@HitcherUK will be in the usual place in an hour or so with branch name in the filename

**Comment by HitcherUK** [comment]
Look good, thanks.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by mkortstiege** [comment]
Anyone tested this? Objections?

**Comment by ronie** [comment]
works ok as far as i can see.
good to go imo.

**Comment by mkortstiege** [comment]
jenkins build and merge

**Comment by HitcherUK** [comment]
@mkortstiege I've started to add this properly for Jenkins and came across this problem.

When using variable labels the size doesn't change when the condition does.

screenshot000

screenshot001

Thanks.

**Comment by mkortstiege** [comment]
Will see if i can get it fixed this weekend.

**Comment by HitcherUK** [comment]
Thanks. Let me know if you need any test code.

**Pull request merged**
