### PR TITLE
[linux] move platform dependent code to xbmc/platform

### PR DESCRIPTION
**Pull request by lrusak**
@FernetMenta is this what you had in mind?

### CODE REVIEW

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
Jenkins seems happy, I'm not sure about the OSX build failure (seems unrelated)

**Comment by lrusak** [comment]
@FernetMenta are you happy with this?

**Comment by FernetMenta** [comment]
@lrusak looks good imo. thanks!

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
@FernetMenta good to merge?

**Comment by FernetMenta** [comment]
I think so :)

**Pull request merged**
