### PR TITLE
[backport] Load filestream details while scanning

### PR DESCRIPTION
**Pull request by alexiri**
Backport of #20247, which has been in master for a while now and hasn't caused any issues.

## Description

This small change loads the full filestream details while adding new files during scanning.

## Motivation and context

When new episodes are added to the video library, their duration, codec, etc. is not known. This information won't be loaded by Kodi until the episode is played or certain playlist views are opened. With this change, the filestream details are loaded when a new video is being added to the library so all the details are available from the very beginning.

## How has this been tested?

I tried adding several episodes and movies and the stream details show up right after scanning.

## What is the effect on users?

Users will see the full details of their videos from the beginning.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by howie-f — APPROVED** [review]
since it‘s identical to master it will get my approval. i’m not completely opposed, but if we strictly follow our rules improvements will not be backported. exceptions should be made by rm. thanks for your work @alexiri , much appreciated

**Comment by arnova** [comment]
Looks ok but I don't think this should be backported since it's not a fix....

**Comment by alexiri** [comment]
While the existing code is not broken per se (hence why I didn't mark it as a bugfix), one could argue that the existing functionality _is_ broken: when a video is added to the library, _all_ it's metadata should be added to the database, not just a subset. In that sense, an argument could be made that this _is_ in fact a fix worthy of a backport. :)

**Comment by afontenot** [comment]
Here's my thinking:

1. It's very surprising, unintuitive behavior that scanning a media file (which the user may *manually* trigger) will sometimes not result in metadata being available for the media file. Users are unlikely to understand why this is happening (and there are multiple reports of confusion that you can find on forums). Furthermore, the behavior is likely unexpected for plugin and application developers. This may not be a bug in Kodi *per se*, but other developers may have bugs in their programs that result from the metadata being unavailable. (Case in point: I wrote a program that encountered this.)

2. More than just being unexpected, the resulting behavior is *unpredictable*. The fact that it's more-or-less impossible to say when Kodi will decide to collect the metadata on a file means that it's extremely unlikely that anyone is relying on the current behavior - precisely because there's nothing to be relied *on*. It's also unlikely to cause performance issues, because the user already expects intensive behavior while scanning. (If anything, it's likely to alleviate issues caused by scanning randomly while the user is trying to browse the list.)

It's possible of course that this patch contain bugs, but it seems like a pretty small, self-contained change. If it's seen testing on the next major version of Kodi, I think there's probably little harm in backporting it. I have also been testing the patch on the Matrix branch myself for close to a couple months now, and have noticed no issues, even on underpowered hardware (Raspberry Pi reading an NFS directory).

**Comment by nbarrientos** [comment]
It'd be beneficial for me too if this could be given a push :wink:. Thanks.

**Comment by DaveTBlake** [comment]
@afontenot thank you for your efforts, but I'm afraid I am going to reject this as a backport. Backports really are only for fixes, and this is an improvement. 

I understand how you may feel about it, I have been in this position myself with my own work. It may well be better behaviour for users, but changing behaviour during a point release is not part of the normal deveopment cycle. Also this kind of scanning change can look so innocent and yet come back to bite us once exposed to diverse use. Been their and done that too!

Finally there was also discussion on the master PR about implementing this in a better way using a background job. It is an improvement that can yet be improved. Continued deveolpment of this feature, or others, on master is very welcome.

**Comment by afontenot** [comment]
@DaveTBlake No worries, @alexiri deserves all the credit though as the person who wrote the patch.

**Pull request closed without merging**
