### PR TITLE
VideoPlayer: rework handling of playing time

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

@ace20022 this also fixes time and progress bar in menues.

### CODE REVIEW

**Comment by popcornmix** [comment]
A couple of days ago I noticed that omxplayer was a few seconds out when displaying elapsed time. Audio/video/subs were in sync. When looking into it I couldn't understand the distinction in GetTime and GetDisplayTime, but I saw a comment that fernet was reworking this so I decided to wait and fix it after the rework. After this PR the problem has disappeared.

So +1 for this

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by ace20022** [comment]
Thx, will quick- check with multi vid soon.

**Comment by ace20022** [comment]
I replied in the forum and added another test file.

**Comment by FernetMenta** [comment]
@ace20022 4031366 does a seek after audio stream has ended. after the seek audio stream is detected as missing and playback continues.
that's best idea I have because I found no means in ffmpeg demuxer to signal an ended stream.

**Comment by FernetMenta** [comment]
@ace20022 ok to merge? there may be more things to to fore your use case but this PR also fixes a couple of issues for current behaviour.

**Comment by ace20022** [comment]
@FernetMenta sure

**Comment by FernetMenta** [comment]
jenkins build this please

**Pull request merged**
