### PR TITLE
[pvr] bye, bye libXBMC_pvr.cpp

### PR DESCRIPTION
**Pull request by AlwinEsch**
Remove the use of shared add-on library for pvr add-ons.
Reopen from #10408 (due to jenkins problem)

## Description
The lib is no more used on add-on. It can be added without changes on add-ons, they need only a recompile.

## Motivation and Context
Cleanup binary add-ons

## How Has This Been Tested?
Has tested several PVR add-ons with normal operation.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by AlwinEsch** [comment]
jenkins build this with addons please

**Comment by AlwinEsch** [comment]
Can someone help me why jenkins always not find the time for the build?

**Comment by afedchin** [comment]
jenkins build this with addons please

**Comment by MartijnKaijser** [comment]
Why was this merged? Seems like pvr Addons are now broken 
http://forum.kodi.tv/showthread.php?pid=2476375#pid2476375

**Comment by FernetMenta** [comment]
This is dev branch and I see no issue in pvr addons being broken for a short time.

**Comment by MartijnKaijser** [comment]
sorry i just saw it was mentioned in the PR description that they need a rebuild. all fine

**Pull request merged**
