### PR TITLE
[AdvancedSettings] add new cleanstrings

### PR DESCRIPTION
**Pull request by DaVukovic**
## Description

New cleanstrings added and re-organized them in alphabetical order so it's easier to find what is missing or not

## Motivation and context

As we already strings like x264 or 1080p we thought it might be useful to add other resolutions, audio standards, video codecs as well

## What is the effect on users?

Better scraping experience if filenames contain video codecs or resolution-/media-flags.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by jjd-uk** [comment]
I don't think languages such as  **dutch**, **german** ,**se** & **swedish**  should go into default file in core otherwise why not all languages and country codes,. I believe these should be additions to your local advancedsettings,xml if they are needed for your files.

Shouldn't 2160 be 2160p?

I would also suggest also adding:

10bit
aac
ddp
dts-hd
hdr10
remux
truehd
uncut
web
web-dl
webrip

I'm unsure how full stops are handled so would need testing giving other possiblities of:

2.0
5.1
7.1
dts-hs.ma

**Comment by DaVukovic** [comment]
The languages have been added long time ago obviously as it wasn't me who added them ;)
I can remove them if we decide that those aren't needed or better placed somewhere else

`uncut` can be found multiple times on tmdb. So I guess that's not a good addition. Same for `web` (Unknown User: Dark Web for example). 

I don't think ppl will do channel references with dots in their filenames. As dots in filenames can be interpreted differently depending on the system in use. Using those channels without a dot would end up in real movies probably being ignored ("21", "21 Jump Street", "Halloween H20: 20 Years later" just to name a few ). So I guess we better don't try to add those. Ppl can still use `<moviename>_<year>.whatever.will.be.placed.here.ext` to have everything ignored after the year. If users don't want to use the year (like I do), we would probably end up with movies not being found. 

I'll add other audio formats as well, like "dolbydigital" and the hd-audio formats, like "dts-hdma", "dts-hra", "dts-x" (normally it's "dts:x" but I guess ":" is also treated strange in filenames). 

Yes..2160 should 2160p. Will change that

**Review by KarellenX — APPROVED** [review]
Thanks @DaVukovic 

After reading the post by you and jjd-uk, I cannot think of any other values to add.

Alphabetical sorting of the string will make it easier to quickly check if a scrape has failed due to a false match, as has sometimes been reported on the forum especially with the word "sample", but that is in another area of the code base.

I agree that the languages added by a previous PR should not be there as that would be something unique to a users setup and added as an advancedsettings.xml entry, but won't make a difference if they remain.

**Comment by DaVukovic** [comment]
Did the changes mentioned above

**Comment by jjd-uk** [comment]
> The languages have been added long time ago obviously as it wasn't me who added them ;) I can remove them if we decide that those aren't needed or better placed somewhere else

Ah yes you're right, because you reordered everything I missed that they had already been there when viewing on my mobile. Thanks for removing those as it doesn't seem right only a select few were there.

> `uncut` can be found multiple times on tmdb. So I guess that's not a good addition. Same for `web` (Unknown User: Dark Web for example). 

Yep you're right, could cause issue with movie title e.g. Charlotte's Web

One final possible addition is `hlg` in order to cover all the HDR formats. Although I've never personally seen a file in this format, many European boradcasters use it for 4K HDR broadcasts so I guess it maybe possible to get a recording in HLG from PVR.

**Review by jjd-uk — APPROVED** [review]
Approving - it's fine with me as it is, so will leave it up to you if you can be bothered to add `hlg` as well.

**Comment by chrisc25** [comment]
I think this is some really good work, and a really great idea.

My thoughts on it would be to add:
**.8bit, .12bit** - as you have 10bit and it would cater for all
also with resolutions futureproofing it a bit more
**.2160i, .4320p, .4320i** - i know less common and last two not around yet
also is this replacing or just adding, as I personally would hate to loose **.3dsbs**

**Comment by DaVukovic** [comment]
@chrisc25 Please create a new PR and the things you think are needed to add ;)

I'll merge this PR now as it is.

**Pull request merged**
