### PR TITLE
[Windows][Depends] taglib: reduce build time enabling parallel build

### PR DESCRIPTION
**Pull request by thexai**
## Description
taglib: reduce Windows build time enabling parallel build (MSVC /MP flag)

## Motivation and context
taglib is very slow to build on Windows because source code contains many small files and are not build in parallel because MSVC /MP flag is not enabled.

Tested in two systems taglib build time before/after PR:

**Intel Core i5-6500 (4 cores)**
Before:  3m 49s   
After: 2m 21s

**Intel Core i7-13700k (24 cores)**
Before: 0m 46s   
After: 0m 14s

taglib is compiled every time in Jenkins, so this time reduction will be noticeable every time Kodi is build.

Surely the same could be applied to other Windows dependencies although the time difference will not be so noticeable in other cases. This should also be taken into account when adding new in tree dependencies.

https://learn.microsoft.com/en-us/cpp/build/reference/mp-build-with-multiple-processes?view=msvc-170

## How has this been tested?
Build taglib for Windows x64 and UWP-64 targets using Visual Studio 2022

## What is the effect on users?
Reduces Kodi build time on Windows

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
Give me some time to look at this.

We should already have /MP from cxxflags. https://github.com/xbmc/xbmc/blob/9d1fbff8b6a4068561bc16163be893579df0c440/cmake/scripts/windows/ArchSetup.cmake#L67

So I think a more general fix is to work out why I haven't got them passing through to the externalproject_add call already.

**Comment by thexai** [comment]
> So I think a more general fix is to work out why I haven't got them passing through to the externalproject_add call already.

That would be even better. In case it helps, only the projects under the "External Projects" do not inherit the /MP flag, others as effects11 and upnp already have it.

ep


except spdlog that has it because is it in origin: 
https://github.com/gabime/spdlog/blob/v1.x/CMakeLists.txt#L34-L36

**Comment by fuzzard** [comment]
@thexai mind trying https://github.com/fuzzard/xbmc/commit/5611db975b4d4ef0c0dc00fab026d63feead3a4d

looks to work/populate flags as intended. Have tested a full x86 build
definitely got an improvement on taglib in my vm (~2m40s > ~1m35), and the /MP flag is being used in the externalproject_add target

Had to add an argument to disable adding the project flags. They caused the build tool flatc to fail linking for whatever reason. i might need to alter the name and the docs, but can deal with that later.

**Comment by thexai** [comment]
Go ahead with your changes, tested and all seems fine.

> Had to add an argument to disable adding the project flags. They caused the build tool flatc to fail linking for whatever reason. i might need to alter the name and the docs, but can deal with that later.

In my case can not replicate this, even disabling line `set(WIN_DISABLE_PROJECT_FLAGS 1)` in FindFlatC.cmake all is working:

```
Build started...
1>------ Build started: Project: ZERO_CHECK, Configuration: Release x64 ------
1>Checking Build System
2>------ Build started: Project: flatbuffers, Configuration: Release x64 ------
2>Creating directories for 'flatbuffers'
2>Building Custom Rule T:/KODI/kodi/CMakeLists.txt
2>Performing download step (download, verify and extract) for 'flatbuffers'
2>-- verifying file...
2>       file='T:/KODI/kodi/project/BuildDependencies/downloads/flatbuffers-2.0.0.tar.gz'
2>-- File already exists and hash match (skip download):
2>  file='T:/KODI/kodi/project/BuildDependencies/downloads/flatbuffers-2.0.0.tar.gz'
2>  SHA512='26a06b572c0e4c9685743bd2d2162ac7dcd74b9324624cc3f3ef5b154c0cee7c52a04b77cdc184245d2d6ae38dfdcc4fd66001c318aa8ca001d2bf1d85d66a89'
2>-- extracting...
2>     src='T:/KODI/kodi/project/BuildDependencies/downloads/flatbuffers-2.0.0.tar.gz'
2>     dst='T:/KODI/kodi-build/build/flatbuffers/src/flatbuffers'
2>-- extracting... [tar xfz]
2>-- extracting... [analysis]
2>-- extracting... [rename]
2>-- extracting... [clean up]
2>-- extracting... done
2>No update step for 'flatbuffers'
2>No patch step for 'flatbuffers'
2>Performing configure step for 'flatbuffers'
2>CUSTOMBUILD : CMake warning :
2>  Ignoring extra path from command line:
2>
2>   "T:/KODI/kodi/project/BuildDependencies/mingwlibs/x64"
2>
2>
2>CUSTOMBUILD : CMake warning :
2>  Ignoring extra path from command line:
2>
2>   "T:/KODI/kodi/project/BuildDependencies/mingwlibs/x64"
2>
2>
2>-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
2>-- The C compiler identification is MSVC 19.34.31937.0
2>-- The CXX compiler identification is MSVC 19.34.31937.0
2>-- Detecting C compiler ABI info
2>-- Detecting C compiler ABI info - done
2>-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped
2>-- Detecting C compile features
2>-- Detecting C compile features - done
2>-- Detecting CXX compiler ABI info
2>-- Detecting CXX compiler ABI info - done
2>-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.34.31933/bin/Hostx64/x64/cl.exe - skipped
2>-- Detecting CXX compile features
2>-- Detecting CXX compile features - done
2>-- Looking for _strtof_l
2>-- Looking for _strtof_l - found
2>-- Looking for _strtoui64_l
2>-- Looking for _strtoui64_l - found
2>-- CMAKE_CXX_FLAGS: /permissive- /MP /FS /DWIN32 /D_WINDOWS /EHsc /wd"4996"  /O2 /Ob2 /DNDEBUG /Zi /W4 /WX /wd4512 /wd4316
2>fatal: not a git repository (or any of the parent directories): .git
2>CMake Warning at CMake/Version.cmake:22 (message):
2>-- Proceeding with version: 2.0.0.0
2>  git describe failed with exit code: 128
2>Call Stack (most recent call first):
2>  CMakeLists.txt:559 (include)
2>
2>
2>-- Configuring done
2>-- Generating done
2>CUSTOMBUILD : CMake warning :
2>  Manually-specified variables were not used by the project:
2>
2>    CMAKE_BUILD_TYPE
2>    PROJECTSOURCE
2>
2>
2>-- Build files have been written to: T:/KODI/kodi-build/build/flatbuffers/src/flatbuffers-build
2>Performing build step for 'flatbuffers'
2>MSBuild version 17.4.1+9a89d02ff for .NET Framework
2>  Checking Build System
2>  Building Custom Rule T:/KODI/kodi-build/build/flatbuffers/src/flatbuffers/CMakeLists.txt
2>Performing install step for 'flatbuffers'
2>MSBuild version 17.4.1+9a89d02ff for .NET Framework
2>  -- Install configuration: "Release"
2>  -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/flatbuffers
2>  -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/flatbuffers/base.h
2>  -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/flatbuffers/code_generators.h
2>  -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/flatbuffers/flatbuffers.h
2>  -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/flatbuffers/flatc.h
2>  -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/flatbuffers/flexbuffers.h
2>  -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/flatbuffers/grpc.h
2>  -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/flatbuffers/hash.h
2>  -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/flatbuffers/idl.h
2>  -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/flatbuffers/minireflect.h
2>  -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/flatbuffers/pch
2>  -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/flatbuffers/pch/flatc_pch.h
2>  -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/flatbuffers/pch/pch.h
2>  -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/flatbuffers/reflection.h
2>  -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/flatbuffers/reflection_generated.h
2>  -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/flatbuffers/registry.h
2>  -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/flatbuffers/stl_emulation.h
2>  -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/include/flatbuffers/util.h
2>  -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/lib/cmake/flatbuffers/FlatbuffersConfig.cmake
2>  -- Installing: T:/KODI/kodi/project/BuildDependencies/x64/lib/cmake/flatbuffers/FlatbuffersConfigVersion.cmake
2>Completed 'flatbuffers'
2>Done building project "flatbuffers.vcxproj".
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Elapsed 00:05,059 ==========

```

**Comment by thexai** [comment]
> Im questioning passing the CMAKE_EXE_FLAGS through, as they are populated with a bunch of core specific delayload stuff. but will leave them as is for now

Maybe create a subset of flags or specific flags for build deps (different of core)

**Comment by fuzzard** [comment]
Flatbuffers is a different target to flatc. We do an executable check for flatc, so it probably won't build in an existing project structure.

Either way , I'll look to clean it up in a few days and PR then.. Holiday time 😀

**Comment by thexai** [comment]
Closed in favor of https://github.com/xbmc/xbmc/pull/22323

**Pull request closed without merging**
