### PR TITLE
Moved userdata to XDG_DATA_HOME

### PR DESCRIPTION
**Pull request by ghost**
Moved the current default userdata location to $XDG_DATA_HOME or ($HOME/.local/share if not available), as per the base directory specification ( http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html ).

Adjusted launch script to migrate from both ~/.kodi and ~/.xbmc to $XDG_DATA_HOME.

Hopefully that's all.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@wsnipex ping as reminder :)

**Comment by EvanPurkhiser** [comment]
:tada:

**Comment by MilhouseVH** [comment]
Note sure why, but with OpenELEC (on RPi) and kodi master (which now includes this PR), I'm getting the following error at kodi.bin startup:
```
Jan 02 17:10:35 rpi512 kodi.sh[431]: ERROR: Unable to create application. Exiting
Jan 02 17:10:35 rpi512 kodi.sh[431]: *** Error in `/usr/lib/kodi/kodi.bin': corrupted double-linked list: 0x0241b368 ***
```
There is no kodi.log produced, I guess it doesn't get far enough to open the log.

Working through the commits in this PR, with only 2eb454aa72cbb532244ab5f8c2fb1bd845163d3f the following error occurs at startup:
```
Jan 02 17:49:22 rpi512 kodi.sh[1048]: Could not init logging classes. Permission errors on ~/.kodi (/storage/.local/share/kodi/temp/)
Jan 02 17:49:22 rpi512 kodi.sh[1048]: ERROR: Unable to create application. Exiting
```

With both 2eb454aa72cbb532244ab5f8c2fb1bd845163d3f + c70182910cff43011e5c4e3feb0507972e5817f1, the following error occurs:
```
Jan 02 17:56:26 rpi512 kodi.sh[432]: ERROR: Unable to create application. Exiting
Jan 02 17:56:26 rpi512 kodi.sh[432]: *** Error in `/usr/lib/kodi/kodi.bin': corrupted double-linked list: 0x01eff368 ***
```

Running kodi.bin in gdb reveals the following:
```
Starting program: /usr/lib/kodi/kodi.bin --standalone -fs --lircdev /run/lirc/lircd
Cannot access memory at address 0x0
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
ERROR: Unable to create application. Exiting

Program received signal SIGSEGV, Segmentation fault.
0xb5608e3c in free () from /lib/libc.so.6
(gdb) bt
#0  0xb5608e3c in free () from /lib/libc.so.6
#1  0xb5794fb4 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string() () from /usr/lib/libstdc++.so.6
#2  0x005cf350 in CProfile::~CProfile() ()
#3  0x005cf0c8 in void std::_Destroy_aux<false>::__destroy<CProfile*>(CProfile*, CProfile*) ()
#4  0x005cdda8 in CProfilesManager::Clear() ()
#5  0x006042c4 in CSettingsManager::OnSettingsCleared() ()
#6  0x006065bc in CSettingsManager::Clear() ()
#7  0x0036cc04 in CSettings::Uninitialize() ()
#8  0x0036ceec in CSettings::~CSettings() ()
#9  0xb55c4674 in ?? () from /lib/libc.so.6
#10 0xb55ac44c in __libc_start_main () from /lib/libc.so.6
#11 0x0035d430 in _start ()
```
With this entire PR reverted, kodi.bin on OpenELEC will start OK.

This may be a peculiarity of OpenELEC, perhaps @sraue or @stefansaraev could eyeball what has changed.

**Comment by MilhouseVH** [comment]
OK looks like this is OpenELEC specific and @stefansaraev is [already on it](https://github.com/OpenELEC/OpenELEC.tv/pull/3657#issuecomment-68548670).

**Comment by stefansaraev** [comment]
well.. with or without my OE specific changes it should not crash.

**Comment by FernetMenta** [comment]
I have trouble too starting kodi on pi:
Could not init logging classes. Permission errors on $XDG_CACHE_HOME/kodi

**Comment by fritsch** [comment]
https://github.com/xbmc/xbmc/pull/6102 <- does that fix the issue? Will only work if you start with "kodi" wrapper - other parts of xbmc code need an additional fix

**Pull request merged**
