### PR TITLE
[confluence][core] add missing & new icon types and cleanup

### PR DESCRIPTION
**Pull request by un1versal**
This is something that been a pet peeve, but even though messing with C++ scares me a bit, I wanted to have a go at it anyway and maybe learn something new.

**All these changes will all work without and will not break anything existing**\* @da-anda @ronie

Top commit we do:
- add [new but existing defined file:](https://github.com/xbmc/xbmc/blob/master/xbmc/Util.cpp#L609)   DefaultVCD.png 
- add [new but existing defined file](https://github.com/uNiversaI/kodi/blob/ee89b7c74677ce0a448a4c6a98ca75c813e3cad5/xbmc/filesystem/SourcesDirectory.cpp#L99-L100):   DefaultRemovableDisk.png **used for removable drives like USB**\* \* and is **_tested working**_
- update **_DefaultVideoDeleted**_ used in PVR (just couldn't bare looking at that file anymore) this is basically a slight color variation on same file I use on my revamp(ed) themes.
- update **_DefaultDVDRom.png**_ chnage glyph to dvdrom type

```

modified:   addons/skin.confluence/media/DefaultDVDRom.png
modified:   addons/skin.confluence/media/DefaultVideoDeleted.png
new file:   addons/skin.confluence/media/DefaultRemovableDisk.png
new file:   addons/skin.confluence/media/DefaultVCD.png
```
## 

Second commit only:
Allow DVD and ISO9660 to display different icon
e.g RETAIL vs Burned DVD-R

IsISO9660 = DefaultDVDRom.png
IsDVD     = defaultDVDFull.png
## 

Third commit 
- The Deleted and unused file was removed in https://github.com/xbmc/xbmc/commit/b9e47838936a86d46d3d0d228943f0a3a7312cbc

**notes**
- Updates are explained further and **bluray** portions has been split with https://github.com/xbmc/xbmc/pull/6946

### CODE REVIEW

**Comment by da-anda** [comment]
I'm not sure we want a breaking change for skins at this point, so I'm not sure about the renaming of the DefaultDVD file - otoh it's not really breaking stuff - worst case is that a wrong/fallback icon is shown, right? The isBluray stuff looks fine and should work I think. Can test it.

**Comment by Montellese** [comment]
@da-anda: I also first wanted to comment about skin breakage but it looks like those images aren't even referenced anywhere.

**Comment by uNiversaI** [comment]
The only image that may break was DefaultDVDFull if other skins use same naming, I can rename it back not a big issue.

Not sure what images you referring to except the one I removed isn't referenced anywhere?

**Comment by da-anda** [comment]
@uNiversaI sorry, didn't check if the file was used - assumed it was because it otherwise wouldn't have been there. Note that the file was initially starting lowercase (defaultDVDFull). If our skinners could confirm the files are usually not used by skins we can ofc rename it to DefaultDVD.
@ronie @BigNoid ?

**Comment by ronie** [comment]
https://github.com/xbmc/xbmc/blob/master/xbmc/Util.cpp#L593

**Comment by uNiversaI** [comment]
@ronie ah thx, but that never shows up ever? Can anyone clarify why it doest show up?

Re: Icons not showing up.
I never seen DefaultDVDEmpty.png icon show up and I also for retail or Burned DVD, never seen DefaultDVDRom in minimal Ubuntu + kodi either all I get is a DefaultFolder.png (on windows test I see DefaultDVDRom but never Linux minimal using udev rules to mount cd/dvd.

Im not trying to solve icons not showing up but for full disclosure I thought then best to mention reason why I removed DefaultDVDEmpty.png

We also dont have DefaultVCD.png icon anywhere, does it work?

No knowledge how to address the icons not showing up in minimal ubuntu and is outside scope of this PR.

@ronie suggestions maybe @mkortstiege or @notspiff for clews and thought or ideas

Ill restore DefaultDVDEmpty.png then

**Comment by mkortstiege** [comment]
No idea about opticals, sorry.. I pretty much removed all that crap in 2000 from my setups ;)

**Comment by uNiversaI** [comment]
ok https://github.com/uNiversaI/kodi/commit/e68369fdd1611242806e2692e676f822a943f0c3

Ive renamed back DefaultDVDFull to defaultDVDFull so @ da-anda and skinners no worries about renaming files if used.

added back the DefaultDVDEmpty.png even though Ive no idea about why doesnt show up here C++ Im unsure needs a more experienced hand.

added a new file DefaultVCD.png which is referenced https://github.com/xbmc/xbmc/blob/master/xbmc/Util.cpp#L609 that came up  with @ronie link

@mkortstiege yes, not an option here opticals are 80% of my collection and would take 10 years on current hardware to convert and compress movie only and also all music, and some 300TB estimate at 4GB per dvd/bluray though currently bluray drive died on htpc.

**Comment by da-anda** [comment]
@uNiversaI about the renaming - it's ofc not a big thing to do, but Helix skins should also work in Isengard. Once we have a stage where we're not backwards compatible anymore we can do the renaming as well. OK?

**Comment by uNiversaI** [comment]
@da-anda, yes ofc, hence why its all back to origin on that front, Not at all a concern happy to keep things working :)

But here now aside from feedback on the latest changes is just the bluray drive icon which if this is correct should show up when a Bluray disk is inserted in the bluray drive.

Outside scope of this PR - Would be nice to get experienced hands on this code handling visibility of these icons types for opticals in the Linux front, so as to establish why some of these are hardly seen or not seen when they should.

**Comment by uNiversaI** [comment]
@ronie @da-anda @mkortstiege after https://github.com/xbmc/xbmc/commit/b9e47838936a86d46d3d0d228943f0a3a7312cbc we remove **DefaultMusicSearch.png** 

Though may as well add that cleanup here. :+1:

**Comment by uNiversaI** [comment]
@ace20022 I know in Linux libcdio wont recognise a bluray in drive as it detects unknown filesystem so this part wont work in linux right? Does it require any more magic to work?

Can someone kick a windows build of this to test on windows to see at least the code behind the bluray icon works?

**Comment by da-anda** [comment]
just triggered a windows test build - should be ready for DL in ~1h (build time + mirror syncing)

**Comment by da-anda** [comment]
I don't see any Bluray icon with this PR - it still shows the green DVD one. So it appears the check doesn't work. I was using an external Blu-ray drived (USB)

**Comment by uNiversaI** [comment]
Can you post a link to windows build?

Not sure if the check is 100% correct or if more is needed, Hence I  am asking ace2002 to look it over and maybe help with remainder, or if you can help with that, idk.

Not sure how a usb drive would make a difference or if it matters. But my c++ foo is poor.

**Comment by da-anda** [comment]
@uNiversaI windows test-builds by jenkins end up here: http://mirrors.kodi.tv/test-builds/win32/
The builds always contain the hash of the last commit and the name of the branch. So the test build for your branch "icon2" is this one: http://mirrors.kodi.tv/test-builds/win32/KodiSetup-20150410-4d4ee9f-icons2.exe

**Comment by uNiversaI** [comment]
Thanks for that!

Do you think its better to separate the Bluray portion from the rest here and make this only about the other icons and separate the bluray icon addition + code to a separate PR?

Because all the other icons should work without any changes to skin or core I have them working already like usb drive etc.

**Comment by ace20022** [comment]
I'll look into it, but give me some time.

**Comment by ace20022** [comment]
What kind of items do you exactly want to have that icon attached?

**Comment by uNiversaI** [comment]
If bluray disk is inserted on optical drive, for one, was the idea behind this one, But in Linux Kodi's libcdido doesnt recognise the bluray filesystem.

On a separate note from this PR.
Going forward, I suppose you also have bluray iso, Idk if you want to add a separate icon for iso images instead of using the images you are using now.

**Comment by ace20022** [comment]
It also doesn't work on win without some changes, I saw some strange code paths on the first glance.
I suggest that you split this pr. The blu-ray stuff needs more time and regression testing.

**Comment by uNiversaI** [comment]
Will do. 

thx.

**Comment by uNiversaI** [comment]
OK now split **bluray**  portion from this PR into https://github.com/xbmc/xbmc/pull/6946

@da-anda @ronie this PR is now 100% safe and all files should work OTB and everything is backwards compatible all skins should be safe

This will bring default theme closer to my theme variants where these files have been added and working for quite a while now but this makes the iso vs dvd distinction code side.

feel free to review but should work all fine.

**Comment by uNiversaI** [comment]
@da-anda any more paint in that bucket of yours?

**Comment by uNiversaI** [comment]
ping @da-anda @ronie would be good in isengard since the changes are innocuous and benefits external usb drives and improves upon some default images who just needed some attention.

**Comment by da-anda** [comment]
I don't like the new add-on folder icons, rest is fine IMO. UI-sounds is not at all obvious IMO and for audio encoder and decoder, maybe symbolizing compressing and deflating audio (or "in" and "out" of a file) would work better from a symbolic POV?

**Comment by uNiversaI** [comment]
@da-anda 

Please see again, I removed the changes to default addon folder icons. Mainly because Audio/encoders dont necessarily compress/deflate anything (think lossless also) so it has to be something else that doesnt imply compressing/deflating and Im not sure what atm.

So this could go in to isegard as it really as is all works and breaks nothing existing, just nice additions and cleanup.

**Comment by mkortstiege** [comment]
Looks good to me. @da-anda your button.

**Comment by ronie** [comment]
please revert https://github.com/xbmc/xbmc/commit/ecea1fff0d7ac5ed2c6bbd4451cadea78cd1fe6e

this is an api change (it introduces a new icon), it breaks proper display of the dvd icon in skins.
on top of that, all default icons start with a capital D, so it should have been DefaultDVDFull.png

**Comment by uNiversaI** [comment]
I can revert that but "DefaultDVDFull.png" is 100% incorrect

see https://github.com/xbmc/xbmc/blob/master/addons/skin.confluence/media/defaultDVDFull.png

Why does this break proper display?

**Comment by ronie** [comment]
> FYI this does not introduce a new icon

the fact that there happens to be some stray icon in Confluence is probably what's causing the confusion.

there was no defaultDVDFull or DefaultDVDFull in our source-code, until this PR added it.
since many other skins in our repo do not includes that icon, it will cause issues.

**Comment by uNiversaI** [comment]
> the fact that there happens to be some stray icon in Confluence is probably what's causing the confusion.
> 
> there was no defaultDVDFull or DefaultDVDFull in our source-code, until this PR added it.
> since many other skins in our repo do not includes that icon, it will cause issues.

There IS
***HELIX***
https://github.com/xbmc/xbmc/blob/Helix/addons/skin.confluence/media/defaultDVDFull.png

***FRODO***
https://github.com/xbmc/xbmc/blob/Frodo/addons/skin.confluence/media/defaultDVDFull.png

***XBMC-ANTIQUATED***
https://github.com/xbmc/xbmc-antiquated/blob/master/addons/skin.confluence/media/defaultDVDFull.png

**Pull request merged**
