### PR TITLE
[PVR] PVR client cleanup and improvement

### PR DESCRIPTION
**Pull request by ksooo**
First commit is a larger cleanup and routes all calls to the client addon through a single proxy method. So, common tasks before after the client addon call can be held in one place . The diff is large, thus not easy to read. Take a look at a good example snippet, to get the idea: https://github.com/xbmc/xbmc/pull/13040/commits/2a62ed20196c48f700c00599af3314fc2c7351e7#diff-d63034db2a0e41f8c4bf14542b168cd4L569

Second commit improves pvr manager shutdown performance. I've seen cases before where the client addon could not reach the backend (network problems, misconfiguration, ...) and pvr manager shutdown took ages, because it had to wait for the timeouts for a bunch of backend calls ongoing while pvr manager should be shut down - pvr gui info thread updating backend data cache and calling several client addon methods in a row is one of the candidates causing this.  

This changes are runtime-tested on macOS, latest Kodi master.

@FernetMenta  for review?

### CODE REVIEW

**Comment by ksooo** [comment]
jenkins build this please

**Review by FernetMenta — APPROVED** [review]
looks sane imo. but I think this is going to be obsolete after we split pvr and streaming api. not sure about the status of @AlwinEsch 's work

**Comment by ksooo** [comment]
I don't think this will be obsolete, as it makes sense as long as you have a PVR API with more than one function, which will be still the case, even after we rip off inputstream functions.

**Comment by ksooo** [comment]
I'm not aware that Alwin is working on the API split, btw.

**Comment by FernetMenta** [comment]
@ksooo before the API can be split the PVR addon has to be migrated to the new design. That I hoped @AlwinEsch was working on.

**Comment by ksooo** [comment]
> before the API can be split the PVR addon has to be migrated to the new design. That I hoped @AlwinEsch was working on.

 Ah, okay.

**Pull request merged**
