### PR TITLE
add timer via json-rpc

### PR DESCRIPTION
**Pull request by stevegal**
adds the ability to set a timer based on the broadcast id via the son-rpc interface

### CODE REVIEW

**Comment by stevegal** [comment]
this adds the ability to add a timer for the pvr from the broadcast id via the json-rpc interface. This will be useful in web applications that want to add timers via a remote epg view.

**Comment by Jalle19** [comment]
You should probably take https://github.com/xbmc/xbmc/pull/7079 into account since it will get merged as soon as we branch Isengard (which should be soon).

**Comment by stevegal** [comment]
Okay. I'll have a look. Do I do this as part of the same pull request or add it in a new one?

**Comment by Jalle19** [comment]
This is a good start in either case so if you want to create a new one or not is up to you.

**Comment by stevegal** [comment]
thanks. I'm a bit of a noob to git. So do I create a fork from ksooo:pvr-series-recordings and branch from there? Thanks for your patience and advice!

**Comment by stevegal** [comment]
think I figured it out. Looks like its as simple as adding as bool to the timer and json.... working on it now.. pi build in progress so  can check it works.

**Comment by ksooo** [comment]
@stevegal yes, you got it right. See https://github.com/ksooo/xbmc/commit/69396ea0af0310e1941e7b9ea1e7f870c03991c3#diff-db4d826cc7a0144872b2c6453d75d062R632

**Comment by stevegal** [comment]
Looks like I properly messed this up trying to sync with the par branch. If that branch is going to xbmc master soon, then I'll try and clean this up and re-branch then.

**Pull request closed without merging**
