### PR TITLE
[Remote]Only log first connection attempt to avoid spamming the logs

### PR DESCRIPTION
**Pull request by Paxxi**
Not a 100% sure about the LIRC change, if it should ignore every failure or just the two common that I included now.

Also cleaned up constructors when I was touching things anyway

### CODE REVIEW

**Comment by fritsch** [comment]
jenkins build this please

we need this, cause spamming, blocking the mainloop still interferes with dvdplayer, render and so on.

**Comment by Paxxi** [comment]
that seems strange, both irss and lirc runs in their own thread but I guess threads will block in CLog when waiting for io

**Comment by Paxxi** [comment]
rpi failure seems unrelated, something about dirty git env.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
I'll  merge this this evening unless there's any objections, need to shut it up before alpha 2

**Comment by fritsch** [comment]
Yeah - pull the trigger. @MartijnKaijser has acked it for alpha2 and @FernetMenta ships it in testing builds. Thanks much.

**Pull request merged**
