### PR TITLE
Commercial skipping notifications and toggle action

### PR DESCRIPTION
**Pull request by b-pass**
**This is a resubmit of https://github.com/xbmc/xbmc/pull/7330**

An implementation to address this feature request from the forums: http://forum.kodi.tv/showthread.php?tid=208206

This adds a new action, TOGGLE_COMMSKIP which turns Commercial Skipping on/off for the current recording only (next record starts back at the default setting from advancedsettings.xml).

Also adds an option to display notifications of commercials and their lengths.

### CODE REVIEW

**Comment by mkortstiege** [comment]
@FernetMenta, @fritsch  mind having a look?

**Comment by b-pass** [comment]
Resynced with upstream master and resolved conflicts.

**Comment by mkortstiege** [comment]
Thanks. @FernetMenta, @ksooo for review please.

**Comment by b-pass** [comment]
This branch became a mess trying to track the change that turned DVDPlayer into VideoPlayer. I'll open another PR on a new branch.

**Pull request closed without merging**
