### PR TITLE
Addon alt path

### PR DESCRIPTION
**Pull request by wsnipex**
@ksooo @stefansaraev can you try this please?

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by stefansaraev** [comment]
works for me.

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
This thingy also made osx crash on that assert. We should really stop to diddle with this stuff in beta stage ... confirmed that this PR fixes the crash on osx too.

**Pull request merged**
