### PR TITLE
Fix memory leak

### PR DESCRIPTION
**Pull request by Paxxi**
## Description

Fixes a memory leak introduced with #17186 . I missed it but Coverity caught it 😄 

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by fritsch** [comment]
Thanks much.

**Review by crazy-matt — APPROVED** [review]

**Review by fuzzard — COMMENTED** [review]
Disregard this first comment. 

Also st is created with new, with no corresponding delete as well in that method. Worth doing the delete for that as well?
https://github.com/Paxxi/xbmc/blob/542470e4f8ebc5ae60d52306e8740e7404f03a60/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp#L1508

**Comment by Paxxi** [comment]
@fuzzard , check the line below. `stream` is a pointer to base class and `st` is a pointer to the real class, stream is always assigned st directly after it's created.

One new early return was added that didn't delete stream and that's what coverity caught

**Comment by fuzzard** [comment]
Sorry for the noise

**Pull request merged**
