### PR TITLE
[tools/codesign][tvOS] Do fake sign, needed for jailbroken devices

### PR DESCRIPTION
**Pull request by sy6sy2**
## Description

At the moment fake sign with `ldid` tool is only performed on iOS deb. This PR enable it for both iOS and tvOS.
Without this fake sign step we can install Kodi on jailbroken Apple TV with `dpkg -i` but Kodi will crash instantly during start.

## Motivation and Context

To be able to easily install Kodi on jailbroken Apple TV devices. The user will not have to perform the fake sign by himself.

## How Has This Been Tested?

* `dpkg -i` of the iOS deb file correctly install Kodi on jailbroken iPhone (checkra1n) and Kodi runs well
* `dpkg -i` of the tvOS deb file correctly install Kodi on jailbroken Apple TV 4K (checkra1n) and Kodi runs well

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by kambala-decapitator — CHANGES_REQUESTED** [review]

**Comment by fuzzard** [comment]
Whilst you are in here @sy6sy2 Do you want to have a look at the following patch.

- Just cleans up some unnecessary if check that is always valid anyway (all 3 apple platforms). 
- Removes the eggs extraction for jailbroken fakesign, and only does for osx target. As discussed, on ios/tvos we dont use eggs. Im not even sure if we need to sign it for osx, but ill leave that in for now, as it may be needed if we ever go the store route.
- As far as i can find, we dont have anything that uses .pvr .0 or .vis extensions anymore.
- Have done Kambala's pickups as well

https://paste.kodi.tv/wokaduyolu

Also as discussed on slack, id be interested whether the following line could be removed completely. Definitely something you would need to test on a jailbreak though. https://github.com/xbmc/xbmc/blob/0a33c06574af0c49f9a7c615e0560127313aa188/tools/darwin/Support/Codesign.command#L31

**Comment by sy6sy2** [comment]
Should we keep

```bash
if [ "${PLATFORM_NAME}" == "macosx" ]; then
  MACOS=1
fi
```

or use `"${PLATFORM_NAME}" == "macosx"` in every `if` like we do for tvOS and iOS?

**Comment by fuzzard** [comment]
Its already in, so i wouldnt bother changing it personally.
Second question, yes, its one of the ifs i remove in the patch above.

**Comment by sy6sy2** [comment]
Last push tested on macOS, Jailbroken Apple TV and iPhone. Not tested with real code signing for iOS and tvOS.

**Review by kambala-decapitator — APPROVED** [review]

**Review by fuzzard — APPROVED** [review]

**Pull request merged**
