### PR TITLE
[fix][bluray] Fix Blu-Ray playback for all playback paths and refactor ShowPlaySelection

### PR DESCRIPTION
**Pull request by ace20022**
This fixes an issue first described in http://forum.kodi.tv/showthread.php?tid=214883.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by ace20022** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
@topfs2 @mkortstiege ok for backport?
ignore build failure on ios

**Comment by mkortstiege** [comment]
A bit much refactor for a backport IMO. I'll leave it to others to decide as I don't have a bluray drive or isos and actually never tried bluray in kodi.

**Comment by arnova** [comment]
-1 on backport. Too much code that may break.

**Comment by ace20022** [comment]
> Too much code that may break.

In relation to?

**Comment by fritsch** [comment]
I don't see any code that might "break" more than the old code. All changes are straight forward in my eyes.

**Comment by arnova** [comment]
It's seemed like a relatively big change but perhaps I don't have a proper overview of what's actual doing. It all depends on the chances of this causing regressions...

**Comment by ace20022** [comment]
The issue that is fixed is that blu-rays with bdj titles can't be played in all situations, e.g., via rpc/remotes, recently added and library for some skins. Not even the main title or the simple menu. That's a real regression to 13.x.
The actual fix is in https://github.com/ace20022/xbmc/commit/f66b28936101d77d3fc50edac7807a5c81e24ec2.
I could drop the other commits, but these only move code to a own class.

**Comment by topfs2** [comment]
Does simplemenu use existing skin xmls or is it an addition? And what backport is this from?

**Comment by ace20022** [comment]
> Does simplemenu use existing skin xmls or is it an addition?

It uses a select dialog: ```
CGUIDialogSelect* dialog = CGUIDialogSelect*)g_windowManager.GetWindow(WINDOW_DIALOG_SELECT);```



> And what backport is this from?

Is this an answer to your question: https://github.com/xbmc/xbmc/pull/6334 ?

**Comment by MartijnKaijser** [comment]
so what's the verdict because i want to kick out 14.2 soon?
It's a localised patch that only affect the bluray selection dialog and has been in master for quite a while now and i have had no problems.

**Comment by topfs2** [comment]
My concerns were quelched so I have nothing against it

**Pull request merged**
