### PR TITLE
cleanup after settings shuffle

### PR DESCRIPTION
**Pull request by ronie**
let's cleanup after ourselves, no need to drag dead code around for years to come.

@jjd-uk

### CODE REVIEW

**Comment by jjd-uk** [comment]
I was planning on attempting a clean up after merger, so thanks for this. I'd only kept the old stuff while testing so I could easily swich between old & new.

**Comment by jjd-uk** [comment]
Bugger, completely missed those changes to remote.xml were needed, and thought I'd corrected the cosmetics, so +1 on the cleanup done here.

**Comment by FernetMenta** [comment]
does this fix empty categories for video and appearance? how can I get video settings back?

**Comment by MartijnKaijser** [comment]
@FernetMenta what skin are you using? If confluence you need https://github.com/xbmc/skin.confluence/pull/12

**Comment by FernetMenta** [comment]
I have been using Confluence. With this bug I can't switch to any other skin. When will this patch be available for simple installation?

**Comment by MartijnKaijser** [comment]
@FernetMenta you can download the skin zip here https://github.com/jjd-uk/skin.confluence/archive/settings.zip  and unpack it in your local confluence folder and it should work again.

**Comment by FernetMenta** [comment]
@MartijnKaijser thanks, that was simple enough for me :)

**Comment by Angelinas1** [comment]
@ronie ,not all dead....weatherSettings  is much alive :)

**Comment by ronie** [comment]
nope, the weathersettings window is gone.
the weather related settings have been moved to a category under service settings.

**Comment by axbmcuser** [comment]
@ronie
So best thing to come close to a WeatherSettings-shortcut is now "ActivateWindow(ServiceSettings)"? Thanks

**Comment by ronie** [comment]
sorry, no support on github. please use our forum.

**Pull request merged**
