### PR TITLE
[PVR] CPVRClients: cleanup and optimization

### PR DESCRIPTION
**Pull request by ksooo**
A bunch of code cleanups and optimizations...

Changes are runtime-tested on macOS, latest Kodi master.

@Jalle19 not an easy task, but maybe you can have a look?

### CODE REVIEW

**Comment by ksooo** [comment]
> this just extends the C-isms from the addon interface one step furher up the stack

 This is only one aspect. It also offers the possibility for consistent and efficient (lambda + std::function to implement call proxy based) pre and post condition handling - for example generic and consistent error handling. At the CPVRClients implementation level in-depth knowledge about addon errors (the particular PVR_ERROR) is still important. And my goal was to get this unified at that level. Further encapsulation and C++-ism is done exactly one level up - at CPVRClients.

I consider every C-API function not returning PVR_ERROR a design flaw. All of the API functions can fail at any time for several reasons (lost backend server connection, for example), but couple of them are not at all able to propagate the error reason (like the ones returning void) or only partly (like the ones returning -1 in case of any error, including "error not implemented"). Think of functions like IsTimeshifting. What does a return value of "false" mean? Not time shifting? Not implemented? Connection to backend lost? ... 

class CPVRClients needs to be able to handle errors in a consistent way for all API calls and I think a nice  implementation for this is the approach I've taken - and (unfortunately) this requires a function call prototype returning a PVR_ERROR. That's the reasoning for the consequent C-ism I have introduced for CPVRClient. It's pragamatic and working well. And finally CPVRClient is (well, should be) a private interface exclusively for class CPVRClients.

CPVRClients API itself should be "clean" C++. Currently it is not and I did not touch this (for now).

My goal is to (later) remove any PVR Addon C-API data types from that API level and to eliminate all direct calls to CPVRClient methods not done from CPVRClients implementation.

I hope this makes some sense?

**Comment by ksooo** [comment]
@Jalle19 if you don't mind I'd really would like to merge this. I'm convinced it is a step in the right direction.

**Comment by Jalle19** [comment]
Sure, go ahead!

**Comment by ksooo** [comment]
Thanks.

**Pull request merged**
