### PR TITLE
[addons] fixed/reworked serialization way for addon extensions on database

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description

This request is related to report from @garbear to me, with game addons the repo does not have the necessary data to identify it correctly.

This adds a way to store the complete content of the master addon type extensions in the database and to have all its content available. As if it were installed.

I'm not sure yet if everything is in the right way and maybe you still have an idea?

## User related

- Improve addon type management in addon database to use the complete content of the addon.
  - Previously, with some add-on types (e.g. game add-ons), some necessary content was not available and could not be correctly identified from the add-on repo.

Commit 1:
------------------------------
**[addons] use CAddonInfo within repo addon content scan**

This changes to the following functions from IAddon to CAddonInfo:
- CAddonManager::AddonsFromRepoXML
- CRepository::FetchIfChanged
- CRepository::FetchIndex
- CAddonDatabase::UpdateRepositoryContent
- SerializeMetadata (AddonDatabase.cpp)

The main reason is to have CAddonInfo available on "SerializeMetadata" and to have all its content available within the database (future changes).

In addition, this also has other advantages:
- The performance is significantly better because the associated addon class does not have to be created for each individual repo addon
- It is a step further to separate add-on management and usage
  - The background is that the CAddon class (and associated child class) should only be created when actually used
- Adjusted the addon manager a little to separate the contained parts into groups
  - The aim is to have a clearer overview in the addon manager which parts are used externally and which parts are only used internally for management

It is easy to contribute to this, since this chain of use is not very cross-branched.

Commit 2:
------------------------------
**[addons] add reworked serialization way for addon extensions on database**

This changes the way the field of the addon.xml of `<extensions point="addon_type_name">...</extension>` is stored in the database.

Previously, only the addon type string was stored as "extension" in json and any sub-data was stored separately under "extrainfo". This makes it difficult to process more complex data.

This introduces a way to save the complete extension's in a json format and when reading all the data of the main addon type is available.

**WARNING:**
A way has to be introduced in order to update the add-on database appropriately, otherwise the content of the previous version is no longer visible in Kodi.
As a temporary test way, the old "Addons32.db" can be deleted so that it is recreated.

Commit 3:
------------------------------
**[addons] update database table to ver. 33 and add update point**

This increases the database version to 33 and adds an update call to change the "metadata" in json format.

The problem with game addons has not yet been resolved directly with this database update, only the old format is converted to the new one (and parts are missing).

Only when the regular update process is carried out will the content be converted to the new type.

Commit 4:
------------------------------
**[addons] fix database wrong handle to change "broken" to new "lifecycledesc"**

Before was there in database the "broken" value from json checked for presence only.
As them sould always present was every addon marked as broken.

This now done by database update and changed to current types.

Also is a fix call added to change previous changed database and have correct again.

This error was brought by me on https://github.com/xbmc/xbmc/pull/18438

## How Has This Been Tested?
Here example how new stored as json in database (the line with `children` there):
```json
{
  "art":{
    "fanart":"http://mirrors.kodi.tv/addons/matrix/skin.aeon.nox.silvo/resources/fanart.jpg"
  },
  "author":"SiLVO","broken":"",
  "dependencies":[
    {"addonId":"xbmc.gui","minversion":"5.15.0","optional":false,"version":"5.15.0"},
    {"addonId":"script.skinshortcuts","minversion":"1.0.10","optional":false,"version":"1.0.10"},
    {"addonId":"service.library.data.provider","minversion":"0.0.7","optional":false,"version":"0.0.7"},
    {"addonId":"resource.images.studios.white","minversion":"0.0.1","optional":false,"version":"0.0.1"},
    {"addonId":"resource.images.recordlabels.white","minversion":"0.0.1","optional":false,"version":"0.0.1"}
  ],
  "disclaimer":"",
  "extensions":[
    {
      "children":[
      ],
      "type":"xbmc.gui.skin",
      "values":[
      {
        "content":[
          {"key":"@debugging","value":"false"}
        ],
        "id":""
      },
      {
        "content":[
          {"key":"res@width","value":"1920"},
          {"key":"res@height","value":"1080"},
          {"key":"res@aspect","value":"16:9"},
          {"key":"res@default","value":"true"},
          {"key":"res@folder","value":"16x9"}
        ],
        "id":"res"
      }]
    }
  ],
  "extrainfo":[
  ],
  "icon":"http://mirrors.kodi.tv/addons/matrix/skin.aeon.nox.silvo/resources/icon.png",
  "path":"https://mirrors.kodi.tv/addons/matrix/skin.aeon.nox.silvo/skin.aeon.nox.silvo-7.9.6.zip",
  "screenshots":[
    "http://mirrors.kodi.tv/addons/matrix/skin.aeon.nox.silvo/resources/screenshots/screenshot-01.jpg",
    "http://mirrors.kodi.tv/addons/matrix/skin.aeon.nox.silvo/resources/screenshots/screenshot-02.jpg",
    "http://mirrors.kodi.tv/addons/matrix/skin.aeon.nox.silvo/resources/screenshots/screenshot-03.jpg",
    "http://mirrors.kodi.tv/addons/matrix/skin.aeon.nox.silvo/resources/screenshots/screenshot-04.jpg",
    "http://mirrors.kodi.tv/addons/matrix/skin.aeon.nox.silvo/resources/screenshots/screenshot-05.jpg",
    "http://mirrors.kodi.tv/addons/matrix/skin.aeon.nox.silvo/resources/screenshots/screenshot-06.jpg",
    "http://mirrors.kodi.tv/addons/matrix/skin.aeon.nox.silvo/resources/screenshots/screenshot-07.jpg",
    "http://mirrors.kodi.tv/addons/matrix/skin.aeon.nox.silvo/resources/screenshots/screenshot-08.jpg",
    "http://mirrors.kodi.tv/addons/matrix/skin.aeon.nox.silvo/resources/screenshots/screenshot-09.jpg",
    "http://mirrors.kodi.tv/addons/matrix/skin.aeon.nox.silvo/resources/screenshots/screenshot-10.jpg",
    "http://mirrors.kodi.tv/addons/matrix/skin.aeon.nox.silvo/resources/screenshots/screenshot-11.jpg",
    "http://mirrors.kodi.tv/addons/matrix/skin.aeon.nox.silvo/resources/screenshots/screenshot-12.jpg"
  ],
  "size":51818074
}
```
It becomes a json part added about.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by phunkyfish** [comment]
jenkins build this please

**Comment by phunkyfish** [comment]
So with commit 3 a game addon update (for all games) is required in order to properly update the DB? Is that correct?

What is the impact if that update does not happen?

**Comment by AlwinEsch** [comment]
> So with commit 3 a game addon update (for all games) is required in order to properly update the DB? Is that correct?
> 
> What is the impact if that update does not happen?

Was a bit bad written from me (the "regular update process"). 
On next repo content update where his addons.xml have a change (auto or triggered by hand) becomes it corrected, see https://github.com/xbmc/xbmc/blob/master/xbmc/addons/Repository.cpp#L374

Only was without set by `void CAddonDatabase::UpdateTables(int version)` all entries in database no more available and addon types missing.

**Comment by phunkyfish** [comment]
Ok, makes sense.

**Review by garbear — APPROVED** [review]
Runtime tested on Win64

**Comment by AlwinEsch** [comment]
@garbear How it has worked about database update and was needed game addons direct available to install?

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by phunkyfish** [comment]
```
/Users/Shared/jenkins/workspace/OSX-64/xbmc/addons/test/TestAddonInfoBuilder.cpp:132:11: error: no member named 'SetType' in 'ADDON::CAddonInfoBuilder::CFromDB'
07:04:28   builder.SetType(ADDON_PLUGIN);
07:04:28   ~~~~~~~ ^
07:04:28 1 error generated.
07:04:28 make[3]: *** [CMakeFiles/kodi-test.dir/xbmc/addons/test/TestAddonInfoBuilder.cpp.o] Error 1
07:04:28 make[3]: *** Waiting for unfinished jobs....
07:04:28 /Users/Shared/jenkins/workspace/OSX-64/xbmc/addons/test/TestAddonDatabase.cpp:41:85: error: no viable conversion from 'vector<shared_ptr<ADDON::IAddon>>' to 'const vector<shared_ptr<ADDON::CAddonInfo>>'
07:04:28     database.UpdateRepositoryContent("repository.a", AddonVersion("1.0.0"), "test", addons);
07:04:28                                                                                     ^~~~~~
07:04:28 /Applications/Xcode10.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/vector:551:5: note: candidate constructor not viable: no known conversion from 'ADDON::VECADDONS' (aka 'vector<shared_ptr<ADDON::IAddon> >') to 'const std::__1::vector<std::__1::shared_ptr<ADDON::CAddonInfo>, std::__1::allocator<std::__1::shared_ptr<ADDON::CAddonInfo> > > &' for 1st argument
07:04:28     vector(const vector& __x);
07:04:28     ^
07:04:28 /Applications/Xcode10.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/vector:558:5: note: candidate constructor not viable: no known conversion from 'ADDON::VECADDONS' (aka 'vector<shared_ptr<ADDON::IAddon> >') to 'initializer_list<std::__1::vector<std::__1::shared_ptr<ADDON::CAddonInfo>, std::__1::allocator<std::__1::shared_ptr<ADDON::CAddonInfo> > >::value_type>' (aka 'initializer_list<std::__1::shared_ptr<ADDON::CAddonInfo> >') for 1st argument
07:04:28     vector(initializer_list<value_type> __il);
```

**Review by phunkyfish — APPROVED** [review]
Code looks good. There are just some minor compiler issues to fix on some platforms.

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by garbear** [comment]
> @garbear How it has worked about database update and was needed game addons direct available to install?

I only tested a fresh installation, not a database update. Is there anything specific I should test? Little busy with work this week.

**Comment by AlwinEsch** [comment]
Was to have e.g. `Addons32.db` present before and to see after auto update to `Addons33.db` that it also works (maybe with a delay until he find a addon mirror change).

**Comment by AlwinEsch** [comment]
@phunkyfish and @howie-f, have added a more correct about the problem.

On database update becomes now the old "broken" changed to new and if from https://github.com/xbmc/xbmc/pull/18438 a bad database update present becomes it fixed.

**Comment by phunkyfish** [comment]
> @phunkyfish and @howie-f, have added a more correct about the problem.
> 
> On database update becomes now the old "broken" changed to new and if from #18438 a bad database update present becomes it fixed.

Ok, still approved by me ;)

**Review by howie-f — APPROVED** [review]
a recent runtime test on debian works fine. cannot spot anything bad :+1:

**Comment by phunkyfish** [comment]
jenkins build this please

**Pull request merged**
