### PR TITLE
dvdplayer: drop work-around for very fast ff, obsolete after flushing…

### PR DESCRIPTION
**Pull request by FernetMenta**
… render buffers correctly after seek

@uNiversaI does this fix the ff issue for you?

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
should it also be backported in case it has positive results?

**Comment by FernetMenta** [comment]
yes

**Comment by uNiversaI** [comment]
Seems better, thanks.

**Comment by hudokkow** [comment]
Backport: https://github.com/xbmc/xbmc/pull/7709

**Pull request merged**
