### PR TITLE
[skins] adjustments to support xml based library nodes

### PR DESCRIPTION
**Pull request by ronie**
changes to Estuary & Estouchy to add support for xml based nodes.
1) replace all videodb:// and musicdb:// (as well as some addons:// and special://) paths by library:// paths.
2) add Library.HasNode() checks where needed.

this PR depends on both https://github.com/xbmc/xbmc/pull/16993 and https://github.com/xbmc/xbmc/pull/16994, so please do not merge before those are in.

### CODE REVIEW

**Comment by sualfred** [comment]
Looks okay to me. Just keep in mind that .xml paths will ignore settings like "hide empty tvshows". 

And the window history is going to be dropped. So "TV Shows" will always lead to the titles.xml no matter if he was in "season X of show Y" before. With the videodb:// path this is remembered.

**Comment by HitcherUK** [comment]
What happens to all the `addons://sources/` with no path?

**Comment by ronie** [comment]
> Looks okay to me. Just keep in mind that .xml paths will ignore settings like "hide empty tvshows".
> 
> And the window history is going to be dropped. So "TV Shows" will always lead to the titles.xml no matter if he was in "season X of show Y" before. With the videodb:// path this is remembered.

guess we'll have to figure out which settings don't work with library based nodes...
i'll put this PR on hold 'till that (and the window history problem) has been fixed.

**Comment by ronie** [comment]
> What happens to all the `addons://sources/` with no path?

sorry, don't get what you mean?

**Comment by HitcherUK** [comment]
> sorry, don't get what you mean?

Now that `<property name="path">addons://sources/game/</property>` etc have been removed how do the lists get filled?

**Comment by ronie** [comment]
ah, that one..
as far as i could tell the path property wasn't used anywhere so i removed them.
please let me know if i'm wrong, as i might've simply missed it.

**Comment by ronie** [comment]
jenkins build this please

**Pull request closed without merging**
