### PR TITLE
fix metadata from mkv tags

### PR DESCRIPTION
**Pull request by DarkShortie**
## Description

As described [here](https://kodi.wiki/view/Video_file_tagging#Title) it should be possible to specify a TMDB or IMDB scraper URL in the mkv tags. In addition it should be possible to to embedd nfo and override nfo files into the mkv file [described here](https://kodi.wiki/view/Video_file_tagging#MKV_tag_options).

Most of this functionality is not working, the only things that seem to work is setting title, year and director using tags and embedding a nfo file. The TMDBURL and IMDBURL tags are not working.

## Motivation and context

This pull request adds the missing code to use the nfo override from attachments and handle the TMDBURL and IMDBURL tags to do the same.

## How has this been tested?

Local build with the changes and a test mkv with a random name which was changed between each of the test runs to make sure no data is reused from the database.

Different test runs where executed:

* For the first test an override nfo which just contains an url to TMDB was added as kodi-override-metadata using MKVToolnix. Before the code changes Kodi was not able to fetch any metadata, after the code changes Kodi hsa taken the url from the kodi-override-metadata and used it for scraping like expected.

* Another test was done by removing the kodi-override-metadata again and adding a tag TMDBURL pointing to a different TMDB url then the test before. The tag was added with mkvpropedit to the mkv file. For this a small xml file was created, which contain the tag and with this the metadata of the mkv file was changed `mkvpropedit --tags all:tags.xml sdgjlkSHJgalkghl.mkv`

tags.xml

```
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Tags SYSTEM "matroskatags.dtd">
<Tags>
<Tag>
<Simple>
<Name>TMDBURL</Name>
<String>https://www.themoviedb.org/movie/2637</String>
</Simple>
</Tag>
</Tags>
```

## What is the effect on users?

The already documented functionality of using metadata/nfo url from mkv files is now working.

## Types of change
- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by DarkShortie** [comment]
Formatting changes are included in the updated commit.

**Comment by jjd-uk** [comment]
I don't think there's is many that know this part of the code well, so it may take some time for a review to be done. I've reached out to @notspiff who might be able to do the review, however he's very busy with work/family and doesn't have much free time.

**Review by garbear — APPROVED** [review]
I can approve. The description links to the spec, and the changes here seem to implement it correctly. Testing demonstrates this.

It would be nice to back this change with unit tests but we currently don't test video tags so that would require some heavy lifting. Good idea for a follow-up PR.

Code is fine and my only suggestion would be to improve the commit history. Not a blocker because PRs provide history now, but GH may not be around forever. A good commit history would break the two changes into separate commits with more descriptive commit titles. Bonus coins for commit descriptions.

**Comment by fuzzard** [comment]
Thanks for the PR, i'll merge it for Alpha 3 and see what shakes out.

**Pull request merged**
