### PR TITLE
[PVR][JSONRPC] Standardize EpgTagInfo serialization names

### PR DESCRIPTION
**Pull request by emveepee**
## Description

Standardize EpgTagInfo season and episode fields with VideoTagInfo.  Expose episodename

Currently EpgTagInfo uses seasonnum and episodenum for season and episode information.  Season and episode are used in VideoInfoTag for other video including PVR recordings.  This PR changes the names to match.

It also exposes episodename from PVR.  There is still an issue for serialized shows.  A TV Show title would be episodename and PVR titles would be showtitle.  Title is needed for Movies.

## Motivation and context

Users cannot use Player.GetItem to retrieve season and episode from Live TV.  The PR could add seasonnum and episodenum to List.Fields.All but that would mean utilities that monitor Player.GetItem would need to ask for both sets of values and adapt depending on what thecontent is  

## How has this been tested?

Tested using Kodi jsonrpc

Windows 11 with pvr.nextpvr

## What is the effect on users?

Users will be able to call Player.GetItem and get season and episode information for Live TV.  Currently season and episode is only returned from PVR Recordings and TV Shows

Any jsonrpc calls to PVR.GetBroadcasts PVR.GeBroadcastDetails using PVR.Fields.Broadcast will need to be updated if they use seasonnum or episodenum.  The calls will fail.

## Screenshots (if appropriate):

```
{
    "jsonrpc": "2.0",
    "method": "Player.GetItem",
    "params": {
        "playerid": 1,
        "properties": ["title","season","episode", "episodepart","episodename"]
    },
    "id": 1
}
```

```
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "item": {
            "episode": 6,
            "episodename": "Baby Off Board",
            "episodepart": -1,
            "id": 562,
            "label": "CIII-HD",
            "season": 1,
            "title": "Family Law",
            "type": "channel"
        }
    }
}
```

Changed call uses season/episode not seasonum/episodenum

```
{
    "jsonrpc": "2.0",
    "method": "PVR.GetBroadcastDetails",
    "params": {
        "broadcastid": 67,
        "properties": ["title","season","episode", "episodepart","episodename"]
    },
    "id": 1
}
```
```
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "broadcastdetails": {
            "broadcastid": 67,
            "episode": 6,
            "episodename": "Baby Off Board",
            "episodepart": -1,
            "label": "Family Law",
            "season": 1,
            "title": "Family Law"
        }
    }
}
```

```
		"PVR.Fields.Broadcast": {
			"extends": "Item.Fields.Base",
			"id": "PVR.Fields.Broadcast",
			"items": {
				"enums": [
					"title",
					"plot",
					"plotoutline",
					"starttime",
					"endtime",
					"runtime",
					"progress",
					"progresspercentage",
					"genre",
					"episodename",
					"episode",
					"episodepart",
					"firstaired",
					"hastimer",
					"isactive",
					"parentalrating",
					"wasactive",
					"thumbnail",
					"rating",
					"originaltitle",
					"cast",
					"director",
					"writer",
					"year",
					"imdbnumber",
					"hastimerrule",
					"hasrecording",
					"recording",
					"isseries",
					"isplayable",
					"clientid",
					"hasreminder",
					"season"
				],
				"type": "string"
			}
		},
```

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [x] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] I have added tests to cover my change
- [x] All new and existing tests passed

The wiki will need to be updated.

### CODE REVIEW

**Comment by ksooo** [comment]
I see the reasoning for this PR, but want to ask the question whether this change which provides no new functionality is worth the hassle that every client using the API must be adapted, because it would break otherwise.

**Comment by ksooo** [comment]
> there is new functionality

Alright. You added episodename. 

What i meant is that you **changed** existing field names which means that all existing JSON-RPC clients using the old field names will break and need to be adjusted and I’m asking whether this is really something we want, because only improvement is consistency, cost is breakage of  existing clients.

**Comment by ksooo** [comment]
> how long should the inconsistent behaviour be maintained?

you know how open source projects work. You never know all the clients using the affected API and you do not know whether those clients are still maintained actively or whether your change will render them useless for ever. This is why I’m already a bit hesitant with incompatible API changed of any kind. 

> I could also serialize "season" and "episode" in EpgTags and "seasonum" and "episodenum" can be deprecated.

That would be the approach i would suggest, yes. 

To make you actually cry ;-) - I consider seasonnum and episodenum better, because these names are more speaking. So, the change could be quite the opposite of what you do with this PR. Deprecate season and episode, introduce the num fields where not existing.

**Comment by emveepee** [comment]
> To make you actually cry ;-) - I consider seasonnum and episodenum better, because these names are more speaking. So, the change could be quite the opposite of what you do with this PR. Deprecate season and episode, introduce the num fields where not existing.

As I worked through it I think it is impossible because "season" is required field in a few calls so hard to deprecate and make optional.

**Comment by ksooo** [comment]
> "season" is required field in a few calls so hard to deprecate and make optional.

No, do not make it optional. Keep it required while deprecating it. Later, remove it. Make the new fields replacing the existing ones later mandatory from the beginning.

**Comment by emveepee** [comment]
> > "season" is required field in a few calls so hard to deprecate and make optional.
> 
> No, do not make it optional. Keep it required while deprecating it. Later, remove it. Make the new fields replacing the existing ones later mandatory from the beginning.

OK, I will see if "OneOf:" works with JSONRPC properties too.

**Comment by emveepee** [comment]
@ksooo I have done the preliminary work in the second commit but it still needs extensive testing since it is high impact and such low gain. I strongly suggest commit one only decrecating episodenum and seasonnum.

It isn't just the complexity or testing all the changed jsonrpc  Throughout core these values are known simply as season and episode in playlists, sorts, display, database, skins etc.  I also have no idea on the impact on Python, I suspect it needs to change too.

**Comment by ksooo** [comment]
> Throughout core these values are known simply as season and episode in playlists, sorts, display, database, skins etc.

Sorry,  i did not know that these fields are used at so many different places, also outside PVR. Seems, they are „standard“ in Kodi. So yes, let’s go with season/episode and deprecate seasonnum/episodenum.

**Review by ksooo — CHANGES_REQUESTED** [review]
JSON-RPC API needs to be bumped: https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/version.txt

Unrelated second commit needs to be removed from this PR.

**Comment by emveepee** [comment]
> JSON-RPC API needs to be bumped: https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/version.txt
> 
> Unrelated second commit needs to be removed from this PR.

So you want that moved to new fourth PR with a second jsonrpc version?

**Comment by ksooo** [comment]
> So you want that moved to new fourth PR with a second jsonrpc version?

618a47caaf758a8dffc8b0078ab04971a7638e95 is already part of #25439 and thus should not be part of this PR.

Your recent JSON-RPC changes should **all** go in one PR to save API bumps. I suggest to use this one. Currently, you are also changing the API in #25439.

**Comment by emveepee** [comment]
> Unrelated second commit needs to be removed from this PR.

I finally got what you mean and it makes sense,  I was looking at the second commit.  I will merge whatever GUI changes needed to the other PR and have just one commit on both.

**Review by ksooo — APPROVED** [review]
LGTM

**Comment by fuzzard** [comment]
Jenkins build this please

**Pull request merged**
