### PR TITLE
[Subtitles] Fix wrong aspect ratio / scaling with ffmpeg subs

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

This fix wrong aspect ratio and scaling and relative position with ffmpeg subtitles like PGS / TS sub format, a regression introduced with #20204

## Motivation and context

With PR #20204 i have add a calculation to keep the aspect ratio with image subs format to avoid stretching subs e.g. when the screen has wide resolutions but this led to some regressions like wrong image position due to different scale between x/y positions and height/width image scale reported by #20729 and maybe #20544

An example of wrong text position (from Issue #14866)
Text off video (before):
immagine
Text on video (now, like other player VLC/MPV):
immagine

This is another side effect that can happens when you align to screen frame size instead of the video size, when you resize the window or you use wide resulution the text go off video:
immagine

compared to other players (like VLC/MPV) Kodi has always handled scaling/positioning by using window frame size instead to use the actual "video" size, and this confused me.

i didn't understand the initial reason for this choice, which i think was made seems about 8 years ago...
if someone has more info about this please let me know, but i think we can change it and see if there are special cases that can cause problems,
then if we scale the subtitles by aligning to the video size `ALIGN_VIDEO` instead of screen frame size `ALIGN_SCREEN` solve the problems

## How has this been tested?

I have tested some MKV/PGS and TS files and compared to VLC now seem result the same output see screenshots below

This should solve also the BlueRay menu #20544 but i cannot test it, can someone test and report?

And is appreciated if some other tests with other files to be sure

## Screenshots (if appropriate):
Before:
immagine
After:
immagine
VLC:
immagine

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by enen92** [comment]
@thexai sorry to bother. Can you runtime test this to check if it solves the corrupted BR menus (with the PR from lukas reverted)?

**Comment by thexai** [comment]
Tested now compiled from this branch: https://github.com/thexai/xbmc/commits/ffmpeg_sub_scale  (this PR + revert Lukas commit on top) and seems all fine with BR menus or at least nothing evident bad.

screenshot00000

**Review by thexai — APPROVED** [review]

**Comment by thexai** [comment]
screenshot00002

**Comment by enen92** [comment]
^^ Looks broken on the menu items (reproducir, escenas, etc) or was it the expected appearance?

**Comment by jjd-uk** [comment]
> ^^ Looks broken on the menu items (reproducir, escenas, etc) or was it the expected appearance?

Going by https://github.com/xbmc/xbmc/issues/20544#issuecomment-997799971 I am assuming top image is the broken one and bottom image is how it should be. Seems to match the bottom image in that post.

**Comment by thexai** [comment]
Yes, it is not the best graphics design to test like this because it already seems broken from origin... but it's okay

**Review by enen92 — APPROVED** [review]

**Comment by maff76** [comment]
not found anything out of place as yet

**Pull request merged**
