### PR TITLE
[depends] bump cmake 3.18.4

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Macos build failure when using xcode 12.2

```
: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can’t open file: /src/xbmc/kodi-build/kodi.build/Debug/compileinfo.build/Objects-normal/arm64/CompileInfo.o (No such file or directory)
```

## Motivation and Context
Xcode 12.2 introduces changes to arch types. 3.14.5 cant handle when multiple
default arch types are provided, and pulls just the first arch (resulting in arm64)

Fix was applied to 3.18.1, but figure best to go to latest of 3.18 series

cmake 3.14.5 issue is caused due to https://gitlab.kitware.com/cmake/cmake/-/blob/v3.14.5/Source/cmGlobalXCodeGenerator.cxx#L3257-3267
When multiple archs are provided (new in xcode 12), the old assumption was to pick the first in the list (happens to be arm64)

cmake fix
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5023

The findccache fix is due to cmake 3.19 change, where script will fail without the shebang. Included here, as it causes no harm in using it.

## How Has This Been Tested?
Built on osx
Reported and Tested by @ksooo 

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
Jenkins build this please

**Review by ksooo — APPROVED** [review]
works now

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
All building proper now. @DaveTBlake up to you if you want in 19 or not. Its only dev build related, no user facing changes

**Comment by lrusak** [comment]
Probably worth doing a build with add-ons also

**Comment by fuzzard** [comment]
Jenkins build this with addons please

**Comment by fuzzard** [comment]
Jenkins build this please with addons

**Comment by phunkyfish** [comment]
jenkins build this with addons please

**Comment by lrusak** [comment]
jenkins build this with addons please

**Comment by DaveTBlake** [comment]
>All building proper now

And then build with addons went red. Bumped to beta 2

**Comment by fuzzard** [comment]
Just pointing out the failures were unrelated. The android failure was a quality gate failure totally unrelated (dummy_libxbmc configure.ac), ios failure was an automake download failure. The key thing, addons built fine for 2 x android platforms, + all linux.

I dont intend to build again at this point

**Comment by ksooo** [comment]
jenkins build wuth addons please

**Comment by ksooo** [comment]
jenkins build with addons please

**Comment by ksooo** [comment]
jenkins build this with addons please

**Review by phunkyfish — APPROVED** [review]
Also runtime tested this. All good here.

**Comment by ksooo** [comment]
Let's shove it in.

**Pull request merged**
