### PR TITLE
[utils] include fmt/xchar.h

### PR DESCRIPTION
**Pull request by candrews**
backport #19900

fmt 8 moved wchar/custom char overloads to xchar.h, so for fmt 8 compatibility, xchar.h must be included

See https://github.com/fmtlib/fmt/commit/76ee490468212f8705a1421b4c88f8f814b2d351

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ksooo** [comment]
Will we ever use fmt 8 with Matrix?

**Comment by Paxxi** [comment]
We won't but Gentoo need it. It's minor enough that I don't see any risk for official builds

**Comment by ksooo** [comment]
Okay.

**Comment by z3ntu** [comment]
For the record, I've also included the patch for Alpine Linux https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/22619 (not yet merged because other pieces of software still aren't patched)

**Pull request merged**
