### PR TITLE
[depends] Updated taglib to v1.11

### PR DESCRIPTION
**Pull request by MartijnKaijser**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MrMC** [comment]
did it fix it ?

**Comment by Razzeee** [comment]
If we're talking about the same problem, yes.

**Comment by Paxxi** [comment]
Has anyone tested a debug build, I'm thinking I forgot to change the iterator debug level?

**Comment by DaveTBlake** [comment]
@Paxxi building for debug (on Windows), what do I need to look out for?

**Comment by DaveTBlake** [comment]
Ah, got errors in VS2015
```
LNK2038	mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in AddonBuilder.obj	Kodi	C:\GitProjects\xbmc\project\VS2010Express\tagd.lib(tbytevector.obj)
```
What needs to be done?

**Pull request merged**
