### PR TITLE
[Matrix][PVR][json-rpc] Re-introduce broadcast properties 'hastimer', 'hastim…

### PR DESCRIPTION
**Pull request by ksooo**
…errule', 'hasrecording', 'recording' and channel attribute 'isrecording'.

Backport of #19498 
 
@Tolriq fyi
@DaveTBlake fyi, as discussed in the original PR, to backport this is okay
@phunkyfish when you find some time for a code review

### CODE REVIEW

**Comment by Tolriq** [comment]
Thanks for backport.

I forget to code review the previous PR and in all cases there's no choices for Matrix, but we really need to refactor this part of the code to once and for all better handle all the use case.
Would allow proper fix for https://github.com/xbmc/xbmc/pull/19154 and prevent the multiple redundant calls triggered here.
If I request all the fields in one query this generates 3 calls to GetTimerForEpgTag and 2 for GetRecordingForEpgTag while 1 for each would be enough that's a lot of unnecessary calls and performance impacts.

**Comment by ksooo** [comment]
@Tolric For v19 this will go in as it is. It is working and the code is non-intrusive, thus low risk.

**Comment by Tolriq** [comment]
That's what I said ;) But since I have no other place to talk, I'm pointing the need to address this for the future.

**Review by phunkyfish — APPROVED** [review]
LGTM

**Pull request merged**
