### PR TITLE
Introduce CServiceBroker::SettingsComponent

### PR DESCRIPTION
**Pull request by ksooo**
This PR supersedes #14485. It introduces a new toplevel service SettingsComponent at the Service Broker and makes "Advanced Settings" and "Settings" subcomponents of the new toplevel component. This eliminates `g_advancedSettings` global singleton and by this certain crashes on Kodi exit are fixed.

You should review commit by commit. The commits named "Introduce..." and "New..." are the "interesting" ones, the others are just "renaming" without functional changes.

### CODE REVIEW

**Review by FernetMenta — APPROVED** [review]
looks good to me

**Comment by ksooo** [comment]
@MilhouseVH could you include this PR in your next testbuilds, please?

**Comment by MilhouseVH** [comment]
@ksooo unfortunately my build machine will be offline for a week or so while I have building work done, there's not likely to be any new test releases until it's back online.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
Headsup: If nobody objects I will merge this tomorrow.

**Comment by garbear** [comment]
No objections

**Pull request merged**
