### PR TITLE
fixed: Dir cache should ignore url (protocol) options (fixes #16469)

### LINKED ISSUE #16469: Feature Request: Move library update and other processes outside of Kodi GUI exe
I would like to have library scans, etc. to be able to run as a service outside of Kodi running.  For example on Windows if I shut down Kodi, I don't want to have to do scans when I come in if they could be running separately.  

Also this would be good for Nvidia Shield where Kodi isn't always active (although I am not sure if there is something similar to a service in andoird)

### PR DESCRIPTION
**Pull request by arnova**

### CODE REVIEW

**Comment by arnova** [comment]
@MartijnKaijser: Your button.

**Comment by DaveTBlake** [comment]
Just to tie things together this is the backport of #8724, that superseds #8717 and fixes the JSON playlist play item failure for Jarvis essential for release.

**Comment by DaveTBlake** [comment]
Hold on that merge, we may have a problem reported on the Krypton version #8724 that has been merged

**Comment by DaveTBlake** [comment]
Looks like the corrections to the Krypton version in #8724 and then  #8797 have been applied to this PR. Ready to go @arnova ?

**Comment by arnova** [comment]
@DaveTBlake : Actually it requires one adjustment: fastlookup should be disabled since it has become useless now in its current state (no biggy). Note that for master I'm working on a fix for CFIleItemList to properly fix that as well, but I'm not sure whether we should incorporate that in Jarvis as well.

**Comment by arnova** [comment]
@DaveTBlake : Updated with fastlookup disabled

**Comment by MartijnKaijser** [comment]
good to go?
jenkins build this please

**Comment by arnova** [comment]
@MartijnKaijser : Yes good to go. Build error is unrelated.

**Pull request merged**
