### PR TITLE
[confluence][DialogkaiToast] align kai dialog to bottom of screen

### PR DESCRIPTION
**Pull request by un1versal**
Small cosmetic improvement that's annoyed me for a long time

**Before**

screenshot033
screenshot039

**After**
screenshot042

screenshot037

### CODE REVIEW

**Comment by Razzeee** [comment]
Not sure if I think that this is an improvement. Why do you think it is?

**Comment by MartijnKaijser** [comment]
don't like it either. maybe if it would also be put entirely to the right

**Comment by un1versal** [comment]
> Not sure if I think that this is an improvement. Why do you think it is?

Sound volume adjustment, fast forward, passtrough audio in use messages/dialogs aligned at the top edge.

These kai messages and the working dialog are all over the place at the bottom and neither cover text or images behind nor allow it to be read or see properly, this way at least it goes along with what is done at the top.

for instance
screenshot044
screenshot049

> don't like it either. maybe if it would also be put entirely to the right

I can try if you think that would fit better

**Comment by un1versal** [comment]
@MartijnKaijser aligned to right (changes no pushed let me know and Ill push them)
screenshot055
screenshot056

**Comment by phil65** [comment]
-1

**Comment by da-anda** [comment]
The kaitoast doesn't slide in but fade in and out and therefore it's a "hovering" infobox and not a drawer attached to any corner. So also -1 from my end.
Also I think all sliding components atm are triggered by direct user interaction while kaitoasts are not necessarily related to the current user action - so applying the same look and feel would be a bit wrong IMO

**Comment by Tolriq** [comment]
IMO the logical way would be to move the things that are tied to close to the edges.
Consistent padding / margins on 4 side is mandatory for easier reading and easy eye understanding it's a popup.

And tied to this are the animations for showing those popups.

For volume the animation is logical to where it's positioned.

For the player status top bar, the animation is fade so the control seems out placed.
Same for the notifications.

In a perfect world, everything should fade and be either top left / bottom right with x pixels distance from edges on both side that touch the edges.

**Comment by da-anda** [comment]
@Tolriq I agree that the margins could be aligned - that's the only thing that I'd change if I had to change something. But it's nothing that bothered me enough to take action, as it's really just a minor visual thing.

**Comment by un1versal** [comment]
> @Tolriq I agree that the margins could be aligned - that's the only thing that I'd change if I had to change something. But it's nothing that bothered me enough to take action, as it's really just a minor visual thing

@da-anda Ieither close this or tell me if you prefer to adjust margins to be same from right and bottom for these.

**Comment by da-anda** [comment]
if you want to spend time on it, feel free to fix the alignment, but I just noticed that more stuff has no balanced margins and that this skin also doesn't really depend on them visually. So I'd say it's better to spend your time with more important stuff in your life.

**Comment by un1versal** [comment]
>So I'd say it's better to spend your time with more important stuff in your life.

Im a captive audience unfortunately, Im confined to small place due to health, so anything to keep me busy and learning something is better than watching videos of kittens all day long :wink.

If you give me some pointers, I dont mind to have a look, but since I dont expect others to to have that sort of time, feel free to close this and Ill open a thread in forums so to do this over some time and not annoy all 70+ kodi githubers.

**Pull request closed without merging**
