### PR TITLE
Introduce LockState enum

### PR DESCRIPTION
**Pull request by howie-f**
## Description
This PR is introducing an ENUM to get rid of those constants in the source-tree.
used in #17129 

LOCK_STATE_NO_LOCK                        =  0
LOCK_STATE_LOCK_BUT_UNLOCKED =  1
LOCK_STATE_LOCKED                          =  2

if everyone is happy with the naming i'll rework the tree

### CODE REVIEW

**Comment by garbear** [comment]
The header looks fine (might want a 2020). I could evaluate the naming better with all occurrences replaced in this PR.

**Comment by howie-f** [comment]
> Needs to be added in CMakeLists.txt.
you sure? i can't even find LockType.h in a CMakeLists.txt and had no building problems

**Comment by lrusak** [comment]
I'm not really sure why you need two PR's for this?

**Comment by fuzzard** [comment]
If it's not included in the CMakelists.txt of the folder, it won't be built.

Having said that, Is LockState really the correct wording, and location in XBMC/ ?
My concerns are lock state is ambiguous, in this case it's a lock state of a profile? Better located in XBMC/profiles and to name it with something like profile_lockstate so no confusions around threading/mutex and some random enum purely for profile state

**Comment by howie-f** [comment]
LockState.h should represent the possible lock-states of a mediasource.
It is first used in #17129 (d7862eb5f9) to get rid of the constants actually used.
To me this is not a "must have", but a nice idea.

This is a copy of file xbmc/LockTypes.h which I adapted.
as even LockTypes.h was absent in CMakeLists.txt i now added both.

**Comment by howie-f** [comment]
superseded by #17129

**Pull request closed without merging**
