### PR TITLE
Backport: PeripheralBusUSB Fixes

### PR DESCRIPTION
**Pull request by fritsch**
Backport of: #17182

### CODE REVIEW

**Comment by candrews** [comment]
In this backport, can you also add the missing cassert include? See #17196

**Comment by fritsch** [comment]
Yes, sure. Any idea why our jenkins is green?

**Comment by asavah** [comment]
AFAIK it's because of bumped fmt version, I ve stumbled into this too.
jenkins has older fmt version.
fmt https://github.com/fmtlib/fmt/commit/2f9acd18380cf80ce212bd2869364d4f36d783fb removed cassert form format/fmt.h which was pulled by StringUtils.h which was pulled by log.h.
Basically asserts worked "by chance" because log.h was included.

**Comment by fritsch** [comment]
@asavah thanks. Yes it was by chance and laziness on my side :-) Thanks both.

**Comment by DaveTBlake** [comment]
Ready to merge @fritsch ?

**Comment by fritsch** [comment]
Thanks @DaveTBlake

**Pull request merged**
