### PR TITLE
[estuary] CPU/RAM/version info reworked

### PR DESCRIPTION
**Pull request by hudokkow**
## Description
Rework CPU/RAM/version info

## Motivation and Context
Do not truncate multicore CPU info. Not really possible for new CPU's crazy core/thread count but looks better IMO.

## How Has This Been Tested?
Runtime tested on Ubuntu.

### BEFORE:
screenshot001

### AFTER:
screenshot000

### AFTER (no decimal):
screenshot004

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Still wonder why we show decimal places for CPU usage :)

**Review by ronie — APPROVED** [review]
looks good to me

**Comment by hudokkow** [comment]
I was on the fence about nuking the decimal part. I'll see what I can do. My blue-eyed 3y old blond is saying Kodi time is up today.

**Comment by hudokkow** [comment]
Updated to remove decimal. See new screenshot in PR description.

**Comment by ronie** [comment]
i would simply use 3.0f% for all.
otherwise the label will constantly vary in width i think?

**Comment by hudokkow** [comment]
Yep, it doesn't vary with NotoMono. Still varies slightly with Noto. Sent fixup commit. Can squash later if everything is OK.

**Comment by ronie** [comment]
good to go imo

**Comment by lrusak** [comment]
I think it looks much better! It does look kind of busy with the `#` symbols all over though, not sure what to do about that.

**Comment by chewitt** [comment]
Can you run a screenshot without the # marks for a comparison?

**Comment by kib** [comment]
How about:
`System CPU usage: [0] 10% [1] 0% [2] 3% [3] 0% [4] 2% [5] 1% [6] 0% [7] 0%`

**Comment by kib** [comment]
or simply
`System CPU usage (8 cores): 10% - 0% - 3% - 0% - 2% - 1% - 0% - 0%`

**Comment by xodidox** [comment]
As the space is extended now, why don't still use the "CPU0:" which is more clear than a bunch of mixed numbers?

**Comment by da-anda** [comment]
how about adding some space between the CPU/memory bars and the compile+version info? Right now it looks like it's somehow related to the bars, while it's not. So some additional space might not harm. But up to you, no strong feelings about it.

**Comment by quthla** [comment]
Or maybe make vertical bars for every cpu core with textual % below?

**Comment by a1rwulf** [comment]
Imho there's a bunch of unused space in the middle of the screen.
What do you think about placing 1 core at a given line, like "top" does:
```
Cpu1: 10% 
Cpu2: 10% 
Cpu3: 10% 
Cpu4: 10% 
Cpu5: 10% 
Cpu6: 10% 
Cpu7: 10% 
Cpu8: 10% 
```
We could think about going for a 4x2 grid etc. if cpu count exceeds 8 or so.
Like:
```
Cpu1: 10%    Cpu5: 10% 
Cpu2: 10%    Cpu6: 10% 
Cpu3: 10%    Cpu7: 10% 
Cpu4: 10%    Cpu8: 10% 

```
Anyway not sure how hard it is to do it like this, so feel free to ignore ;)

**Comment by hudokkow** [comment]
## Fresh buckets of paint available (mine is purple, btw) :laughing: :rofl: :

@lrusak, @chewitt:
screenshot000

@kib:
screenshot001
screenshot002

@xodidox:
screenshot003

@hudokkow (me):
screenshot004
screenshot005

@da-anda:
Agreed. I'll add some negative space to differentiate one from the other.

@quthla:
Only browsed the code diagonally and I might be wrong but I don't think the GUI engine supports vertical progress bars. Besides, I think the *graphic equalizer* look is not the way to go. Someone prove me wrong please.

@a1rwulf:
Info per core is not exposed in `CCPUInfo`. Same goes for the `(8 cores)` part in `System CPU usage (8 cores)`. I cheated by hardcoding the string to see how it looks.
Not that it's hard to expose the info we need but that code could use some cleanup (first) and platform separation (second) before anything else.

Anyway, enjoy painting the bikeshed folks! :wink: :+1:

**Comment by a1rwulf** [comment]
@hudokkow thx for the clarification - that's basically all I wanted to say, I'll drop out of this in order to reduce cooks ;)

**Comment by jjd-uk** [comment]
On the latest screenshots the spacing for each value looks far too much over to the right, taking 1st screenshot as an example it's:

0:     8% 1:     0% 2:     0% 3:     0% 4:     2% 5:     2% 6:     2% 7:     0% 

so 8% could easily be mistaken as value for CPU1 for example.

Shouldn't the formatting be more like

0: 8%     1: 0%    2: 0%     3: 0%     4: 2%     5: 2%     6: 2%     7: 0%

**Comment by davilla** [comment]
"System CPU usage (%)" then drop all those redundant %'s

**Comment by da-anda** [comment]
I actually wanted to stay out of this, but we also could get rid of the "CPU" in all those labels, if we would group the info shown on this screen in two sections with according headlines:
```
# CPU ##############################
Model:            Intel ...
Temperature:   ...
Speed:             ...
Usage (cores in %):     [#1: 100]  [#2: 100]  [#3: 10]  [#4: 10]

# MEMORY ##########################
Total:
Free:
```
but again, no strong feelings about any of this. It's not like this screen is used much. Additionally, the CPU info is also shown in the bottom bar incl the stats of all cores, so who cares if it's cut off up there?

**Comment by ksooo** [comment]
> "System CPU usage (%)" then drop all those redundant %'s

 KISS. Who needs that in depth insight into CPU details?

**Comment by ksooo** [comment]
More obvious to change for me: Get rid off the reduntent memory values - total/free/used. But this may be for another PR.

**Comment by boot2k3** [comment]
May be
CPU0  CPU1  CPU2  CPU3  CPU4  CPU5 CPU6  CPU7
 10%     10%     10%     10%    10%     10%    10%     10%
?

**Comment by phunkyfish** [comment]
@hudokkow do you want to progress this , close it, or put it on the backburner?

**Comment by phunkyfish** [comment]
As there has been no comment on this PR it will be closed in 2 weeks time if no comment stating to do otherwise is added.

**Comment by ronie** [comment]
the idea was ok, but killed by bikeshedding :-)

**Comment by phunkyfish** [comment]
Going to close this, can be reopened at a later date if required.

**Pull request closed without merging**
