### PR TITLE
[Android] Fix for false Flag "Channel is empty"

### PR DESCRIPTION
**Pull request by timfehr**
## Description
Removed the Channel.isBrowsable test. Based on #14170.

## Types of change
- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by Rechi — COMMENTED** [review]
I can't judge this.

**Comment by fehritale** [comment]
What do you need to judge it?

**Comment by Rechi** [comment]
@MartijnKaijser requested a review from me, so I told him I don't know if it is right or wrong.

**Comment by MartijnKaijser** [comment]
@koying is it correct now?

**Comment by peak3d** [comment]
From what I have read in the other PR, this is exactly what koying suggested.
@fehritale does channel work with your PR ?

**Comment by fehritale** [comment]
@peak3d did not test it, because i do not know how to build an apk. I just removed to code koying suggested and fixed the intendation that was wrong with the other PR.

**Comment by peak3d** [comment]
@fehritale I can trigger a build, are you able to test then? To be honest I don't use this channel feature and I would not know how to reproduce / verify.

**Comment by Rechi** [comment]
apks can be downloaded from http://jenkins.kodi.tv/job/Android-ARM/10767/ or http://jenkins.kodi.tv/job/Android-ARM64/6857/

**Comment by fehritale** [comment]
@Rechi Is the ARM64 the apk for the Nvidia Shield TV?
@peak3d If you trigger it, yeah I will be able to test it.

**Comment by peak3d** [comment]
You can use both, I would suggest the 64 bit version as its more common.

**Comment by Rechi** [comment]
A new triggered version won't be different to the versions I linked. I don't know if you usually use arm64 or arm.

**Comment by peak3d** [comment]
@Rechi wasn't aware of the already existing apk, so I'll not trigger anything as apk's are already there

**Comment by fehritale** [comment]
@Rechi @peak3d Thanks! I will try it today and let you guys know the result.

**Review by peak3d — APPROVED** [review]
From code changes it looks sane for me, but I cannot runtime test.

**Comment by fehritale** [comment]
Test results:
Created a new smart playlist with version Alpha2, Channel could not be added due "Channel is empty".

"Updated" Kodi to the merged version i downloaded, created a new smart playlist and it could be added as channel. So no more "Channel is empty" and it fixed it for me. @Rechi @peak3d

**Comment by HitcherUK** [comment]
Confirmed fixed.

**Pull request merged**
