### PR TITLE
libcdio: add osx 10.13 patch

### PR DESCRIPTION
**Pull request by FernetMenta**
make libcdio compile on OSX 10.13
source: http://git.savannah.gnu.org/cgit/libcdio.git/commit/?id=09eb9abcf3cf4322984f6072fb656116dc59a8b0

### CODE REVIEW

**Comment by Rechi** [comment]
@FernetMenta please remove the unnecessary white space changes from the patch file.

**Comment by FernetMenta** [comment]
@Rechi I don't intend to touch the original patch file that I created with git-format-patch from original sources.

**Comment by Rechi** [comment]
You can use git-format-patch with the parameter `-w` (https://git-scm.com/docs/git-format-patch#git-format-patch--w) which will ignore all space changes.
Just for reference the non white space changes are https://github.com/xbmc/libcdio/commit/09eb9ab?w=1.

**Comment by FernetMenta** [comment]
@Rechi I really don't care about white spaces in a patch file that will disappear anyway when we bump version next time. I don't have time to bother with trivialities, sorry. Take the PR as is or close it.

**Comment by wsnipex** [comment]
OSX is not my area

**Comment by ksooo** [comment]
Can we merge this, please?

**Comment by Rechi** [comment]
sure
jenkins build and merge

**Pull request merged**
