### PR TITLE
[Binary add-ons] Point audio encoders/decoders to master instead of SHA

### PR DESCRIPTION
**Pull request by hudokkow**
To go in after https://github.com/xbmc/xbmc/pull/7570 and respective add-on PRs are merged.

### CODE REVIEW

**Comment by hudokkow** [comment]
jenkins build addons please

**Comment by hudokkow** [comment]
What? jenkins build this please

**Comment by hudokkow** [comment]
jenkins build addons please

**Comment by hudokkow** [comment]
jenkins build addons please

**Comment by Montellese** [comment]
Something went completely wrong with that build. Not sure if it's a problem in the binary addons build jobs. Let's try again. jenkins build addons please

**Pull request merged**
