### PR TITLE
[aml] add gui settings to enable/disable sd material hw decoding

### PR DESCRIPTION
**Pull request by stefansaraev**
alternative of #9772

cc @koying @codesnake

### CODE REVIEW

**Comment by codesnake** [comment]
For me this looks like more elegant solution. Compiled and tried on several videos and it seems works without problems.

**Comment by stefansaraev** [comment]
jenkins build this please

**Comment by mazeyx** [comment]
these options are greyed out on android arm tv and have no effect, anyway this could be enabled id like to use software decode on sd content (would fix a zoom issue im having with media codec surface enabled)

**Comment by stefansaraev** [comment]
@mazeyx those are aml specific, but I somehow forgot to make them conditional argh. will fix. thanks!

**Pull request merged**
