### PR TITLE
Change smallstepback to seek(-7) + debugging and reload keymap

### PR DESCRIPTION
**Pull request by NedScott**
This way we can start to deprecate smallstepback completely thanks to the new seek built-in.

smallstepback to Seek(-7) on all our default keymaps.

Plus two actions I've been meaning to do as a PR anyways, but they seemed too minor to do on their own. For keymap.xml only:
shift+control+K: reloads keymaps
shift+control+d: toggle debugging

Two modifiers are used to help prevent any accidental triggering and shouldn't conflict with anything else.

### CODE REVIEW

**Comment by NedScott** [comment]
Slightly off topic, but while I was doing this I was really surprised to see us not have a smallstepback in remote.xml.

**Comment by jjd-uk** [comment]
Much better than the other PR in my opinion as it will allow users to tune the size of the step back by simply altering the value given to the Seek builtin withiin the keymap e.g. user could alter to Seek(-5) for -5s step back.

+1 from me

**Comment by xhaggi** [comment]
@NedScott sorry for merging the seek-step PR without waiting for your response, but i got 3 positive feedbacks and thought it's fine. 

This is much better as adding the 7 sec step back to the default step config and thanks @jjd-uk for this idea ;)

**Comment by xhaggi** [comment]
@NedScott could you squash everything together and name it `[keymaps] smallstepback -> Seek(-7)`

**Comment by NedScott** [comment]
I was afraid someone was going to ask me to do something like that. Honestly, I have no idea how to do that. I spent a few hours here and there trying to learn how to use git and merging and smashing, and I'm embarrassed to say that I still don't know what to do. I made these changes using github's web interface, so these files don't even exist on my computer, which I think is where the disconnect happens.

I'll give it another try, though.

**Comment by Jalle19** [comment]
@NedScott you'll need to do something like this:

* clone your fork to your computer (`git clone blablabla`)
* checkout this specific branch (`git checkout keymap_tweak`)
* start an interactive rebase of the last ten commits (`git rebase -i HEAD~10`)
* in the text editor you get, change all `pick` to `fixup`, except the first one. This means all the other commits will be squashed into the first one
* "save the file" and the rebase will happen
* force push the branch back to Github (`git push -f origin`)

**Comment by arnova** [comment]
With force push I would *ALWAYS* do "git push -f origin {branch_name}" but that's just my 2c.

**Comment by xhaggi** [comment]
the latest version of git refuse the force push if the local branch does not hold the same name as the remote, but you are right if you don't set the upstream branch before you need to specify it like you said.

But I would prefer to do the following to configure the upstream branch:

`git push -u origin <your-branch>`

and later you can easily do

`git push -f`

**Comment by Jalle19** [comment]
@arnova I do that too, I just thought I'd make the instructions as simple as possible.

**Pull request merged**
