### PR TITLE
[win32] don't define _USE_32BIT_TIME_T

### PR DESCRIPTION
**Pull request by Jalle19**
Noticed this while developing a PVR addon. I don't know the reason behind this macro, some suggested it may be a leftover from ye olde days.

Pinging @Paxxi since it's enough to fix any bugs you might encounter. Please ping others if you know who might know the details behind this.

### CODE REVIEW

**Comment by Jalle19** [comment]
jenkins build this please

**Comment by Montellese** [comment]
IIRC I simply copied all of them from the `XBMC.vcxproj`. Not sure if they are needed for the audioencoder addons but if that's the case and they are in the way of PVR addons they need to be manually added there. Some probably goes for `NOMINMAX` which is causing issues in different binary addons.

**Comment by Jalle19** [comment]
This doesn't cause a problem as long as all addons use the same flag, but at the same time it feels like a hack. I've tested without this flag briefly and at least the EPG grid works as expected.

**Comment by Memphiz** [comment]
Correction - this doesn't cause a problem as long as all addons use the same flag, or in case time_t is used in an ABI it doesn't cause a problem as long as all addons and kodi itself use the same flag. So the fact that this define is set on kodi project and not on addons looks wrong to me (even if we don't use time_t in the ABI atm...)

**Comment by Paxxi** [comment]
this PR misses the defines in the VS project files so there's a high possibility that stuff will break as is, I'll look through it, if we will break things we should get it ready for this alpha window to get plenty of testing.

**Comment by Jalle19** [comment]
@Paxxi you're right, I was so into all this cmake stuff earlier that I didn't think of that. Will push an update.

@Memphiz the intention was to remove the define from Kodi as well

**Comment by Paxxi** [comment]
@Jalle19 I think you can hold off on this, there's a whole lot of possible breakage here. 
1. There's a few places in kodi itself assigning it to a 32-bit int, e.g hfs and egg code.
2. Afaik time_t is mostly 32-bit on Linux so we depend on mingw libraries that are built with the flag, e.g. Nettle and hogweed

**Comment by Jalle19** [comment]
@Paxxi this flag is only used on Windows, there's not even a GCC equivalent to it.

**Comment by Paxxi** [comment]
I know it's only used on windows but currently we need it not to break Linux libraries built with mingw and I assume those are built that way because they expect time_t to be 32-bit and would break otherwise. To get rid of the flag on our end we would need to go through these and rebuild them.

To make it clear, Linux libraries here means libraries we use on windows that doesn't build outside msys/mingw

**Comment by Jalle19** [comment]
@Paxxi I dropped it from the VS project, will need to use grep to find it's defined anywhere else.

**Comment by Jalle19** [comment]
I'll defer this to @Paxxi on a rainy day

**Pull request closed without merging**
