### PR TITLE
[cec] replace disable-cec-adapter-if-no-cec-tv-found dialog with a setting

### PR DESCRIPTION
**Pull request by ksooo**
Followup to #6653. Replaces the dialog in question with an adapter setting.

@opdenkamp what do you think?

### CODE REVIEW

**Comment by opdenkamp** [comment]
The only reason for having the dialog is that some devs were complaining about CEC logging when debugging is enabled and there's no TV with CEC support. The polling process itself doesn't cause any issues at all. So this setting defeats the purpose, you can use the `enabled` setting for this if you want to disable CEC.

**Comment by ksooo** [comment]
The problem with the dialog is that it even pops up on systems usually using a CEC capable TV when you start this kind of system without the CEC capable TV switched on. This happens for instance if the system starts up automatically at nights for doing maintenence stuff, like EPG updates.

So, would it be okay for you to introduce a setting with options what to do when no CEC capable TV was found:
- ask user
- disable the adapter
- do nothing

The current situation with the dialog popping up every night (in my case), preventing the system from going down after nightly maintenence and confusing my wife/kids when the switch on the TV to watch TV etc. is for me and others a nogo and needs to be fixed asap, IMHO.

**Comment by ksooo** [comment]
... or even better, tell those devs that they should go and disable the adapter by themselfes. Then we could simply revert the commit that ntroduced that silly (sorry, Lars ;-) dialog.

**Comment by Paxxi** [comment]
This should absolutely not be a setting, if it can't find an adapter then let it do it's thing in the background. It shouldn't open that annoying dialog either as it currently does ad it has no function. If cec is too noisy then shut it up and stick more of the logging as debug logging, it's not an issue that concerns the end user and we shouldn't force a decision on them

**Comment by ksooo** [comment]
+1 on what @Paxxi said. 

@opdenkamp as I and other end (not debugging dev) users can't live with the current situation, would you mind if I revert the commit that introduced the dialog? We should not release Isengard with this stuff, imo.

**Comment by opdenkamp** [comment]
it already is debug logging, this just prevents the debug log spam. reverting it is fine with me

**Comment by ksooo** [comment]
@opdenkamp thx. will revert.

**Pull request closed without merging**
