### PR TITLE
[xbmc][utils] Remove auto_aptr

### PR DESCRIPTION
**Pull request by Paxxi**
std::unique_ptr handles this just fine by specifying [] in the template type

### CODE REVIEW

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by Montellese** [comment]
Looks good. `CAutoPtrFind` and `CAutoPtrSocket` could be replaced with `std::unique_ptr` and a custom deleter.

**Comment by Paxxi** [comment]
I'm currently looking at that but I don't think unique_ptr works as the invalid value isn't nullptr so it won't know what it is.

But we could use a generic scopeguard and it's easy enough to write.

**Comment by Paxxi** [comment]
jenkins build this please

**Pull request merged**
