### PR TITLE
[python] prevent segfault when calling DialogProgress(BG) methods before...

### PR DESCRIPTION
**Pull request by tamland**
... create()

### CODE REVIEW

**Comment by ace20022** [comment]
handle might be also null there https://github.com/xbmc/xbmc/pull/6284/files#diff-ea679e8fd64ae4318868722d0de5fdadR456 .

**Comment by tamland** [comment]
@ace20022 I don't think GetHandle can return null. That's why I left it out.

**Comment by tamland** [comment]
@jimfcarroll not null if you call create, but it you don't

**Comment by jimfcarroll** [comment]
Yup.

**Comment by tamland** [comment]
jenkins build this please

**Pull request merged**
