### PR TITLE
[pvr.mythtv] bump addon to version 2.7.4

### PR DESCRIPTION
**Pull request by janbar**
- Remove EPG associations with recording due a performance issue

### CODE REVIEW

**Comment by janbar** [comment]
issue was raised in PR #8141

**Comment by Jalle19** [comment]
jenkins build addons please

**Comment by ksooo** [comment]
Sorry for jumping in here, but shouldn't the performance issue have been fixed with #8022?

**Comment by janbar** [comment]
@ksooo here I didn't fix the issue but i removed the commit relates the epg associations. It had been added for Kodi 15.2 with the bump of 2.6.2. After check it can break the addon for rpi/android users. So here i remove this feature which is not ready to use for the stable relase.

**Comment by janbar** [comment]
@ksooo here the source issue causing the performance issue is no longer #8022 , but #8141. And this cannot be fixed for Isengard because it requires a major update of EPG container.

**Comment by janbar** [comment]
@ksooo the #8022 had fixed an issue for recording playback. But still one more in recordings update for the addon pvr.mythtv.

**Comment by kib** [comment]
jenkins build addons please

**Comment by ksooo** [comment]
@janbar okay. Thanks for explaining.

**Comment by janbar** [comment]
jenkins seems to be out to build binary-addons for android or rpi. I hope you will merge it before 15.2 is out.

**Comment by mkortstiege** [comment]
@Jalle19 what's the status here?

**Comment by Jalle19** [comment]
@mkortstiege should go in once it builds. Jenkins says:

```
Strings match run condition: string 1=[rbpi], string 2=[win32]
Run condition [Strings match] preventing perform for step [BuilderChain]
```

**Comment by stefansaraev** [comment]
jenkins build addons please

**Pull request merged**
