### PR TITLE
[json] fix: CAddonsOperations::SetAddonEnabled - set disabledReason -

### PR DESCRIPTION
**Pull request by howie-f**
## Description
this supersedes https://github.com/xbmc/xbmc/pull/19095
it fixes setting of `AddonDisabledReason` when `CAddonsOperations::SetAddonEnabled` is executed via JSON-RPC call to `SetAddonEnabled`.

- if the add-on is enabled it needs to be set to `AddonDisabledReason::NONE`
- if the add-on is disabled it needs to be set to `AddonDisabledReason::USER`
(this is now consistent to enabling / disabling by gui)

please note that this doesn't change the API or exposed interfaces, so i feel a version bump is not needed.

## How Has This Been Tested?
```
1. send -> '{"jsonrpc":"2.0","method":"Addons.SetAddonEnabled","params":{"addonid":"pvr.hts","enabled":true},"id":1}'
2. send -> '{"jsonrpc":"2.0","method":"Addons.SetAddonEnabled","params":{"addonid":"pvr.hts","enabled":false},"id":1}'
```
...and examining the results in the database

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document

@phunkyfish would you mind taking a look as you are the original author of this code. probably you had intentions i do not know yet.

### CODE REVIEW

**Comment by phunkyfish** [comment]
If `disabledReason` is being removed from the API then this means the API is changing, right?

**Comment by phunkyfish** [comment]
I see. Thanks for explaining. So we have corrected the bad behaviour that was observed via the API. But the API contract does not change.

**Comment by phunkyfish** [comment]
Honestly, at this stage I don’t remember. But if this PR corrects the error, then good 😉

**Review by phunkyfish — APPROVED** [review]
👍

**Review by DaveTBlake — CHANGES_REQUESTED** [review]
> please note that this doesn't change the API or exposed interfaces, so i feel a version bump is not needed.

API consumers also want to know when the internal implementation of a method has changed, and that is the purpose of the patch number. It is documented in the schema

https://github.com/xbmc/xbmc/blob/9f0301d844c242308e2390fa42240e3736d00cbf/xbmc/interfaces/json-rpc/schema/methods.json#L34

JSON API version needs to be bumped to v12.0.1 in /xbmc/interfaces/json-rpc/schema/version.txt

**Comment by howie-f** [comment]
> needs to be bumped to v12.0.1

sure makes sense as the function behaves differently internal. done

**Review by DaveTBlake — APPROVED** [review]

**Pull request merged**
