### PR TITLE
[remote] add support to delete in MyPictures via remote

### PR DESCRIPTION
**Pull request by un1versal**
Useful when you have many pictures or screenshots and you want to delete a few or a group with few clicks as possible.

Context menu is great but impractical for more than one or two.
Filemanager you have no preview of the file to know what to do with actions that work there I wanted to add to this area..

### CODE REVIEW

**Comment by uNiversaI** [comment]
@mkortstiege @MartijnKaijser

**Comment by uNiversaI** [comment]
ping anyone @MartijnKaijser @mkortstiege

**Comment by mkortstiege** [comment]
No objections if there's a confirm dialog before performing the actual delete.

**Comment by uNiversaI** [comment]
yes theres a dialog.

**Comment by mkortstiege** [comment]
OK. @MartijnKaijser your button.

**Pull request merged**
