### PR TITLE
[PVR] Fix crash after selecting 'Add timer' in PVR timer window, closes Trac16539

### PR DESCRIPTION
**Pull request by ksooo**
http://trac.kodi.tv/ticket/16539

Imo, we need a Jarvis backport for this one. Small code change, low regression risk.

@jalle19 @xhaggi mind taking a look.

### CODE REVIEW

**Comment by Jalle19** [comment]
+1, thanks for handling the ticket.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
win-32 jenkins error is unrelated

**Pull request merged**
