### PR TITLE
[epg] Sort included files alphabetical

### PR DESCRIPTION
**Pull request by AlwinEsch**
Also not a special request and was present in #6877 and now separated to here.

Is sort only the headers alphabetical in following flow.
- System global headers a-z
- Kodi global headers a-z
- Own folder headers a-z

If OK for you then I merge in.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by AlwinEsch** [comment]
Has not seen this bad change of #7248 on last update.
jenkins build this please again

**Comment by MartijnKaijser** [comment]
fine with me as it's on cosmetics really

**Comment by mkortstiege** [comment]
+1

**Comment by AlwinEsch** [comment]
Thanks

**Pull request merged**
