### PR TITLE
[cmake] bail out if waylandpp isn't found via pkg-config

### PR DESCRIPTION
**Pull request by lrusak**
This has been a consistent thorn in my side for a while. I've always had to compile kodi-wayland with `PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig:$PKG_CONFIG_PATH cmake ..`.

~~This PR adds `/usr/local` (the normal unix custom installation path) to the `CMAKE_PREFIX_PATH` variable. This is used to set the default search paths for various cmake things include pkg-config searches. see https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html~~

I've also added to the FindWaylandpp.cmake module to bail out if the pkg-config variables cannot be found.

I decided to do this after trying to setup the FreeBSD build box to build for wayland also. This resulted in the following error after waylandpp was installed to `/usr/local`

```
17:53:36 gmake[2]: *** No rule to make target '/protocols/presentation-time.xml', needed by 'wayland-extra-protocols.hpp'.  Stop.
17:53:36 gmake[1]: *** [CMakeFiles/Makefile2:487: CMakeFiles/generate-wayland-extra-protocols.dir/all] Error 2
```
This happened because even though cmake could find waylandpp, the pkg-config module couldn't and thus `PC_WAYLANDPP_PKGDATADIR` was empty which resulted in the variable `WAYLANDPP_PROTOCOLS_DIR` being set to `/protocols` which is obviously incorrect.

After this change the variable is set to the correct path
```
WAYLANDPP_PROTOCOLS_DIR:INTERNAL=/usr/local/share/waylandpp/protocols
```

### CODE REVIEW

**Comment by wsnipex** [comment]
interesting that this is needed on some systems, what's the output of: 
`pkg-config --variable pc_path pkg-config`

**Comment by lrusak** [comment]
> pkg-config --variable pc_path pkg-config
```
$ pkg-config --variable pc_path pkg-config
/usr/lib64/pkgconfig:/usr/share/pkgconfig
```

**Review by yol — CHANGES_REQUESTED** [review]
Hrm. 

+1 on the FindWaylandpp.cmake and Makefile changes

-1 on the ArchSetup.cmake changes. Our build system should not override the platform setup. Every user should be free to set up their system in the way they like it and we should not just assume stuff because it suits our Jenkins setup. If you want `/usr/local` to be searched, set up your system environment to do so, which CMake will honor. It is not standard behavior and would in fact be unexpected - to me, at least. (That said, line 6 in the freebsd ArchSetup.cmake also looks questionable, but I don't know too much about FreeBSD)

**Comment by wsnipex** [comment]
for reference, ubuntu 20.04:
$ pkg-config --variable pc_path pkg-config
`/usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig`

I suspect this is related to ldconfig, ubuntu adds /usr/local/lib by default.

**Comment by yol** [comment]
```
$ pkg-config --variable pc_path pkg-config
/usr/lib/pkgconfig:/usr/share/pkgconfig
```

YMMV I guess :man_shrugging: That's why I'm saying we should honor the system.

**Comment by wsnipex** [comment]
I agree with @yol, we shouldn't force those dirs, in fact I've had to patch out such stuff several times in depends ;)

**Comment by lrusak** [comment]
> -1 on the ArchSetup.cmake changes. Our build system should not override the platform setup. Every user should be free to set up their system in the way they like it and we should not just assume stuff because it suits our Jenkins setup. If you want `/usr/local` to be searched, set up your system environment to do so, which CMake will honor. It is not standard behavior and would in fact be unexpected - to me, at least. (That said, line 6 in the freebsd ArchSetup.cmake also looks questionable, but I don't know too much about FreeBSD)

Sure. I can drop it.

**Review by wsnipex — APPROVED** [review]

**Review by yol — APPROVED** [review]
Thanks :+1:

**Pull request merged**
