### PR TITLE
[Windows] Fix: enables passwordless SMB authentication

### LINKED ISSUE #19600: Kodi prompts for username/password to access an passwordless SMBv3 share resource
### Describe the bug
Here is a clear and concise description of what the problem is:
Kodi prompts for username/password to access an passwordless SMBv3 share resource

Is needed type some random or bogus login user/password to access. This is not intuitive and is confusing for much users.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Do not prompt for username / password

## Actual Behavior
Prompts username/password:
screenshot00002

### To Reproduce

Are used two machines with Windows 10 20H2 (19042.928):

hostname PC -----> Kodi is running on this.
hostname ASUS-ZENBOOK ----->  Shared folders are configured on this.

Two machines has SMBv1 disabled (default Windows 10 20H2 setting)
On ASUS-ZENBOOK current Windows account has password changed to NOT match with PC (avoids access granted due share same Windows account).

On ASUS-ZENBOOK configure a passwordless share:

Go to "Network and Sharing Center" > All Networks and check "Turn off password protecting shared":

Screenshot 2021-04-18 111722

Configure shared folder and add "everyone" user permissions:

Screenshot 2021-04-18 112132

Make sure on "Password Protection" zone appears text "People without user account and password for this computer can access folders shared with everyone":
 
Screenshot 2021-04-18 111926

For test purposes, configure another shared with normal one user permissions (NOT everyone).

### Screenshots 
Here are some links or screenshots to help explain the problem:

Kodi prompts username/password just trying to get to the root of ASUS-ZENBOOK:

screenshot00002

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: v19.0 - v20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by thexai**
## Description
Fix: enables passwordless SMB authentication.

Fixes https://github.com/xbmc/xbmc/issues/19600.

## Motivation and context
Currently when connecting to a passwordless SMB resource Kodi keeps asking for username/password, which is confusing.

This is because when username/password are empty, Kodi passes `NULL` to `WNetAddConnection2W` function and the current Windows account user/password is used.

https://github.com/xbmc/xbmc/blob/ce2a04adf112822c5c01019adb79e6115544b880/xbmc/platform/win32/filesystem/Win32SMBDirectory.cpp#L728-L729

This is fine because many times it will coincide with what you want but it does not work if you want to access a resource without a password.

Fix consists on try user "guest" password "" (empty) if user/password provided is empty and previous attempt with NULL/NULL (current Windows account user/password) has failed.

## How has this been tested?
Are used method and setup described here: https://github.com/xbmc/xbmc/issues/19600

## What is the effect on users?
Avoids Kodi prompts for user/password if SMB resource has no password configured.

## Screenshots (if appropriate):
**Before:**
screenshot00000

screenshot00001

**After:**
screenshot00003

screenshot00004

**Also is tested that is still prompting password for access to "normal_share" folder:**
screenshot00005

**IMPORTANT NOTE:** Due Windows caches access permissions once "passwordless_share" is accessible by using Kodi with this patch (PR) access remains possible even with "normal" Kodi (without PR) until is restarted Windows.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
Not that this doesn't actually fix the referenced issue. This fix only works for windows and not Unix like platforms.

**Comment by thexai** [comment]
> This fix only works for windows and not Unix like platforms.

Then fix the issue on Windows only (as is tagged) 😉

**Comment by fuzzard** [comment]
I believe why lrusak commented was, when you add fixes xxx, the bot will auto close the issue once merged. Where that's an incorrect action

**Comment by thexai** [comment]
OK, it can be reopened manually later.

**Comment by lrusak** [comment]
The referenced issue actually mentions that it works on windows already https://github.com/xbmc/xbmc/issues/18832#issuecomment-731671159
>Kodi v19 beta 1 for Android does not connect to unpassworded Windows 10 share that Kodi v18.9 for Android connected to just fine. Kodi v19 beta 1 for Windows, on the other hand, connects to the same unpassworded Windows 10 SMB share just fine.

**Comment by thexai** [comment]
Works although keeps asking password:

@jjd-uk :
> I've just tested this today.
> 
> With SMB3 being used I can connected to a share with no password. However to do so when creating the new network location in Kodi I had to use bogus user/pawword details, I tried both a single space for user/pwd and z as user/pwd so I would presume just anything must be entered. 

Fix consists in NOT asking password

**Comment by lrusak** [comment]
> Works although keeps asking password:
> 
> @jjd-uk :
> 
> > I've just tested this today.
> > With SMB3 being used I can connected to a share with no password. However to do so when creating the new network location in Kodi I had to use bogus user/pawword details, I tried both a single space for user/pwd and z as user/pwd so I would presume just anything must be entered.
> 
> Fix consists in NOT asking password

it's unclear what platform @jjd-uk was testing on

**Comment by thexai** [comment]
> it's unclear what platform @jjd-uk was testing on

Windows 10 with SMBv3. 

Tomorrow I will try to do a more detailed explanation of how to test it and how to configure an SMBv3 resource without password in Windows 10.

**Comment by jjd-uk** [comment]
That test I did was connecting to a SMB3 share on Windows 10 from an Android device. When it comes to SMB I can test most combination of devices since I have Win10, Qnap, and Synology providing SMB3 network shares to Win10, LibreElec and Android clients.

**Comment by thexai** [comment]
> > it's unclear what platform @jjd-uk was testing on
> 
> ~Windows 10 with SMBv3.~ Android

Well in Windows the behavior is the same in that case:

**Note - Does not work with v19 on Windows currently**
https://forum.kodi.tv/showthread.php?tid=362113&pid=3031222#pid3031222

I guess that's why @jjd-uk  it says it doesn't currently work  in this guide (because is needed enter a random chars in password)

I am aware that the unsafe method is not recommended and fortunately many people do not use it. Without a doubt, the most practical thing is to use a local Windows user (the same on both PCs) and Kodi uses the password of the Windows account automatically without having to enter it and without having to save it in password.xml. That is what I have always used.

This PR is only a small improvement to make it compatible with the unsafe method as well. The insecurity is given by the configuration in Windows. Logically, if Kodi lets you enter without a password, it will always be because the source does not have a password.

**Comment by afedchin** [comment]
vfs.smb2 addon uses `Guest` username in any case if username isn't defined. see [source](https://github.com/afedchin/vfs.smb2/blob/Leia/src/SMBSession.cpp#L146) this saves one try to connect.

**Comment by thexai** [comment]
First try with `NULL`/`NULL` is needed because is current Windows account user/pass and most common case. Remove this breaks current behavior that is OK on secured (default) connections.

**Comment by jjd-uk** [comment]
> 
> **Note - Does not work with v19 on Windows currently**
> https://forum.kodi.tv/showthread.php?tid=362113&pid=3031222#pid3031222

This will hopefully explain that further.

That is there because in https://forum.kodi.tv/showthread.php?tid=362113&pid=3031436#pid3031436 **Step 5 OPTION 2 - Share with no password** then entering of something random chars does not work on Windows, that hack/cheat only works on devices that use the SAMBA library so that's Android, Linux etc so they must do something different in this respect.

When I try the same thing on Windows then I get similar what you posted above

image

So no matter what I do on Windows only I cannot connect to a share with no password, as the randam chars hack does NOT work on Windows. 

I've not yet had time to test this PR.

**Comment by thexai** [comment]
> entering of random chars does not work on Windows, that hack/cheat only works on devices that use the SAMBA library so that's Android, Linux etc

With more reason this PR is needed since it fix this 😃

**Comment by thexai** [comment]
Here is a build based on Matrix to make testing easier:

https://github.com/thexai/xbmc/releases

Also includes all previous WS-Discovery stuff.

**Comment by thexai** [comment]
To be 100% sure that this change works in all cases, I have just tested it using a Synology NAS that uses SAMBA as an SMB server.

Here are all the steps to create a shared folder with guest access (paswordless):

Enable guest user (by default is disabled on DSM)
Captura de pantalla 2021-04-24 174334

Captura de pantalla 2021-04-24 174453

From this window **is need remove password for guest** although DSM refuse do it.... is need to do via SSH:

Enable SSH
Captura de pantalla 2021-04-24 175102

Use SSH client e.g. Kitty
Captura de pantalla 2021-04-24 180049

type `sudo synouser --setpw guest ''`

Captura de pantalla 2021-04-24 180427

Create or edit shared folder
Captura de pantalla 2021-04-24 174632

Assign only guest user permissions red/write or read only
Captura de pantalla 2021-04-24 174831

Go to Kodi
Captura de pantalla 2021-04-24 180855

Access without prompt password
Captura de pantalla 2021-04-24 180805

**Comment by jjd-uk** [comment]
I have tested and confirmed the issues of constantly prompting for a password even on a share with no password is now gone and I can now connect to share with no password. This on top of WS-Discovery means that full SMB functionality as it was in v17 (browsing & passwordless shares) has been restored for the Windows client.

I'm not able to do a code review hence no approval.

**Review by arnova — APPROVED** [review]

**Review by afedchin — APPROVED** [review]

**Pull request merged**
