### PR TITLE
Refresh lists on playcount update

### PR DESCRIPTION
**Pull request by razzeee**
This will refresh lists whenever a player stops. Particular useful for home screens which will pick up changes after watching a video or playing a song.

One problem of this might be that we don't want some lists to refresh this "often"?
We will probably only learn this, if we merge this and learn to love or hate it.

### CODE REVIEW

**Comment by Razzeee** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
I would like to take this opportunity to mention that the entire AnnouncementManagement is pain in the rear. Nothing directly related to this PR but AnnouncementManager is like cancer. Everybody hooks new functions into this not being aware that it may hijack the main/render thread for things like database queries/updates. @popcornmix recently observed some >10 seconds blocking of the main thread when playback was started -> main thread did some database work.
Even external clients have already hooked into this mechanism. I strongly recommend a redesign of AnnouncementManager.

**Comment by Montellese** [comment]
@FernetMenta: I have been preaching this ever since topfs2 and I added it solely for the purpose of being able to send notifications to JSON-RPC clients and people started abusing it for something else (like updating recently added items etc).

**Comment by Razzeee** [comment]
Well I assumed it was proper / without blocking. 
Good to know, might also be a possible gsoc project.

**Comment by Razzeee** [comment]
Btw this seems to mostly fix the widgets for music, as video seems to refresh magically

**Comment by Paxxi** [comment]
Some more side tracking, @FernetMenta how's your render thread separation going?

**Comment by Razzeee** [comment]
Just rethought this completely and changed 100% of the code

**Comment by Razzeee** [comment]
jenkins build this please

**Comment by Razzeee** [comment]
Jenkins built fine just the usual addon problem. 
I would like to merge this later today.

**Pull request merged**
