### PR TITLE
text rendering: dont change character spacing on justify

### PR DESCRIPTION
**Pull request by tamland**
I'm no expert but I think the normal way is to only add space between words. Certainly looks better if you ask me.

### CODE REVIEW

**Comment by tamland** [comment]
before - after
before after

**Comment by notspiff** [comment]
hybrid is also often used with good results. some small adjustment allowed between chars the the rest between words.

**Comment by tamland** [comment]
The current one is a hybrid. Spacing between words are 6 times larger..

**Comment by notspiff** [comment]
right but without the cap i assume?

**Comment by NedScott** [comment]
Every document editor I've ever seen adjusts character spacing and actual spaces.

**Comment by Montellese** [comment]
IMO the before looks much better than the after. Word does this too and sometimes it yields awkward results for some lines but I guess there's no ideal solution.

**Comment by tamland** [comment]
Latex, any web browser, any book/newspaper I could find; no spacing between character. Word isn't exactly known for good typesetting.. I can't find anything that change character spacing like this tbh. Ideal solution is to auto split long words, but that's seem like a very hard problem to get right.

@notspiff right. But you won't get good results. At these sizes even 1 px is too much an will be visible. Less extreme example:
before2
after2
notice the uneven spacing of the C in "ROC" and the last l in "will" for instance.

**Comment by NedScott** [comment]
Since this discussion I've been keeping an eye out for this in various places. From what I've seen, adjusting spaces only does seem to be more common and often results in something that looks better. Both methods can make weird results, but over all, I now agree with tamland. 

In other words, no objections from me.

**Comment by HitcherUK** [comment]
If it's any use to the discussion I've had complaints of weird font spacing in Conq where I use justify for textboxes. I've also done some research today and the only mention of spacing between the actual fonts and not the words had this to say about it.

"If you’re us­ing jus­ti­fi­ca­tion in a high-end lay­out pro­gram, you’ll have the choice of dis­trib­ut­ing the ex­tra space in each line be­tween words or be­tween let­ters (or some com­bi­na­tion). Please—put it be­tween the words. Type de­sign­ers spend a lot of time get­ting the spac­ing be­tween char­ac­ters right. (Some of us would even say spac­ing is the essence of type de­sign.) If your char­ac­ter spac­ing is chang­ing from line to line, your jus­ti­fied text block will look horrible."

**Comment by kib** [comment]
+1, touching intercharacter kerning values is a big no no

**Comment by tamland** [comment]
Ok, will trust the experts on this one. IMO those narrow columns looks bad when justified regardless, but that will be up to skinners to not use it for those boxes

**Comment by tamland** [comment]
jenkins build this please

**Pull request merged**
