### PR TITLE
Const correct audioengine

### PR DESCRIPTION
**Pull request by rikardfalkeborn**
## Description
Add const to member functions.

## How Has This Been Tested?
Compile tested on Linux.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fritsch** [comment]
Thanks much. This is good practice to make methods const to keep the "const state" of the object those methods belong to. If we changed something in the future that would have a side-effect when calling these the compiler would directly warn.

Fine with me!

**Review by fritsch — APPROVED** [review]
Thanks much.

**Comment by rikardfalkeborn** [comment]
Hmm, seems the testrunner on FreeBSD core dumped
```
19:00:34 /home/jenkins/workspace/FreeBSD/tools/buildsteps/freebsd/run-tests: line 10: 71307 Abort trap              (core dumped) build/kodi-test --gtest_output=xml:gtestresults.xml
```
I couldn't see any other builds where this happened, but I can't really figure out why this change would cause a core dump....

**Comment by Rechi** [comment]
The test suite is a bit buggy.

**Pull request merged**
