### PR TITLE
[addons] improve database performance

### PR DESCRIPTION
**Pull request by tamland**
This reduces our ~3000 or so queries down to 3, hopefully improving performance a bit.

Would be great if someone using pi could post some numbers (it will print the query along with timings when browsing repository).

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Looks like this is causing a crash when entering Add-ons > Install from repository > All repositories > *crash*

http://sprunge.us/KcSW

**Comment by MilhouseVH** [comment]
Strange, can't seem to reproduce the crash now that Kodi has restarted - maybe something funky in Addons21.db, that's now been fixed by the restart?

Anyway, these are the timings on RPi1 when entering Add-ons > Install from repository > All repositories:
```
20:38:27 2471.742920 T:1670128544   DEBUG: CAddonDatabase: query SELECT addon.* FROM addon JOIN addonlinkrepo ON addon.id=addonlinkrepo.idAddon JOIN repo ON addonlinkrepo.idRepo=repo.id WHERE repo.checksum IS NOT NULL AND repo.checksum != '' ORDER BY addon.addonID returned 972 rows in 119 ms
20:38:28 2471.882812 T:1670128544   DEBUG: CAddonDatabase: query SELECT addon.addonID as owner, addonextra.key, addonextra.value FROM addon JOIN addonextra ON addon.id=addonextra.id JOIN addonlinkrepo ON addon.id=addonlinkrepo.idAddon JOIN repo ON addonlinkrepo.idRepo=repo.id WHERE repo.checksum IS NOT NULL AND repo.checksum != '' ORDER BY addon.addonID returned 794 rows in 69 ms
20:38:28 2472.030029 T:1670128544   DEBUG: CAddonDatabase: query SELECT addon.addonID as owner, dependencies.addon, dependencies.version, dependencies.optional FROM addon JOIN dependencies ON addon.id=dependencies.id JOIN addonlinkrepo ON addon.id=addonlinkrepo.idAddon JOIN repo ON addonlinkrepo.idRepo=repo.id WHERE repo.checksum IS NOT NULL AND repo.checksum != '' ORDER BY addon.addonID returned 1879 rows in 134 ms
20:38:28 2472.274414 T:1670128544   DEBUG: CAddonDatabase::GetAddons took 652 ms
```

Without this PR, it would take about 4000ms - 4500ms:
```
19:47:15 257.055511 T:1578779552   DEBUG: CAddonDatabase::GetAddons took 3994 ms
19:47:21 262.623047 T:1804456864   DEBUG: CAddonDatabase::GetAddons took 3817 ms
19:47:37 278.867126 T:1804456864   DEBUG: CAddonDatabase::GetAddons took 4071 ms
19:47:46 287.963776 T:1578779552   DEBUG: CAddonDatabase::GetAddons took 4643 ms
19:48:23 324.743530 T:1804456864   DEBUG: CAddonDatabase::GetAddons took 3927 ms
19:50:22 443.750397 T:1618518944   DEBUG: CAddonDatabase::GetAddons took 4732 ms
19:50:36 458.299316 T:1578779552   DEBUG: CAddonDatabase::GetAddons took 3901 ms
```
so a pretty significant improvement.

I can include this PR in tonight's RPi test builds, may need to keep an eye out for any other crash reports.

**Comment by tamland** [comment]
@MilhouseVH Noticed the same on my android device. I've been able to crash it multiple times at the same place as you; it takes a lot of tries but it does occasionally crash. I pulled the db file and it works perfectly fine on other machines, so it not corrupt. It smells undefined behavior long way.

Perhaps someone can review the code to shed some light on it?

This is the source of the crash, from the above log:
````
#0  0x75527080 in std::string::assign(std::string const&) () from /usr/lib/libstdc++.so.6
#1  0x0052c43c in dbiplus::field_value::get_asString() const ()
#2  0x0052cda8 in dbiplus::field_value::field_value(dbiplus::field_value const&) ()
#3  0x00526060 in dbiplus::Dataset::get_field_value(int) ()
#4  0x003edc50 in dbiplus::Dataset::fv(int) ()
#5  0x004dc580 in CAddonDatabase::GetRepositoryContent(std::string const&, std::vector<std::shared_ptr<ADDON::IAddon>, std::allocator<std::shared_ptr<ADDON::IAddon> > >&) ()
````

**Comment by MartijnKaijser** [comment]
No crashes so far :)

**Comment by tamland** [comment]
Yeah, helps to get some sleep. Thanks for testing!

**Pull request merged**
