### PR TITLE
disable plugin caching

### PR DESCRIPTION
**Pull request by tamland**
Supersedes #9898

### CODE REVIEW

**Comment by L2501** [comment]
this causes some bad behaviour like having to enter search queries every time you go up back into a search result like in the twitch addon.

**Comment by phil65** [comment]
might be that this should be solved inside the plugin now? @tamland ?

**Comment by tamland** [comment]
Well yes obviously, disabling plugin caching will cause plugins to not cache.. If we want it in core it needs to be re-implement (in a way that it doesn't get stuck indefinitely). But preferably plugins shouldn't be so slow they need caching. If that's an answer(?):)

**Comment by popcornmix** [comment]
Got a [report](http://forum.kodi.tv/showthread.php?tid=269814&pid=2465506#pid2465506) of youtube add-on being slow after this PR went in.

I know that is not unexpected and there are reasons for disabling caching, but thought I'd mention it in case anyone has ideas for improving this. I suspect there may be many similar reports.

**Comment by zag2me** [comment]
Generally you would want to cache online plugins from my experience using them daily. I value speed over updates. Just my opinion...

**Comment by dentaku65** [comment]
Please restore the cache for plugins; the perception is lack of performance using Kodi, at least on RPI3. Or place an option to enable the cache for plugins, if possible.

**Comment by arnova** [comment]
@tamland : I agree with @dentaku65 I think this change has too many drawbacks.

**Comment by DaveTBlake** [comment]
This seems to be the cause of  http://trac.kodi.tv/ticket/17211 and multiple complaints on the forum.

@tamland this change is causing problems, but I'm afraid I don't know enough to be able to solve the issues

**Comment by koying** [comment]
Maybe implementing a TTL for transient cache would be an alternative solution?

**Comment by arnova** [comment]
I think for v17 this should just be reverted. As that seems the safest solution for now.

**Comment by tamland** [comment]
The fix is to remove the permanent/global caching in GUIMediaWindow, and instead cache until you go back or leave the window. That should solve the navigation sluggishness. After that we should really think about whether we should provide caching for plugins, because what we have now at least is completely broken.

@DaveTBlake if so, that would be really weir (and unrelated) as this pr just flips the cache policy for plugins.

**Comment by koying** [comment]
@tamland From the ticket, "If the playlist is populated by web query" + "Install "radio" music addon", so that seems addon related indeed.

**Comment by dentaku65** [comment]
Installed Krypton RC3 today via LibreElec... still having navigation slowness inside the add-ons. Using this on every day basis is a nightmare.

**Comment by MartijnKaijser** [comment]
@dentaku65 this is not in RC3. Also use the forum

**Comment by dentaku65** [comment]
@MartijnKaijser ah ok, sorry

**Pull request merged**
