### PR TITLE
[FIX][JSONRPC] Respect boolean values when exporting video/audio via …

### PR DESCRIPTION
**Pull request by the-black-eagle**
…json

## Description
Fixes the video library and audio library exports to properly respect the boolean values of the set export options e.g. `"overwrite": true` 

## Motivation and context
See https://github.com/xbmc/xbmc/issues/16761#issuecomment-862440575 .  The current code doesn't check the boolean values correctly and a missing option defaults to `true`.  This change checks for `true/false` values and a missing option defaults to `false`. This now matches the expected behaviour as defined in the jsonrpc schema.

## How has this been tested?
Tested locally with variations of `curl -X POST -H 'Content-Type: application/json' -i http://localhost:8080/jsonrpc --data '{"jsonrpc":"2.0","method":"VideoLibrary.Export","params":{"options":{"actorthumbs":true,"images":true,"overwrite":false}},"id":1}'`
and ensured the correct options were applied.   Internally, that line will generate a cmd of `"exportlibrary2(video, separate, dummy, artwork, actorthumbs)"` which is correct.

The same json request run against master will generate `"exportlibrary2(video, separate, dummy, artwork, overwrite, actorthumbs)"` which is wrong as overwrite should be false and thus missing from that.

## What is the effect on users?
Option values will be correctly applied when using the json interface to export the video or audio libraries. Missing options will default to false.
## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by DaveTBlake** [comment]
You need to bump the schema patch number too when fixing issues involving JSON. 

This can be backported because it is a fix AND so far all JSON changes for v20 have also been backported. However there are a couple of JSON changes pending that  are not going to be backported, once they are merged further fixes for the v19 release become impossible. So this is a reminder for me an everyone else, to get this in before those (and apologies for those that have been waiting on those PRs and will then have to rebase, but at least this fix makes the wait purposfull).

**Comment by the-black-eagle** [comment]
Oh, didn't bump the schema because this doesn't change it, only the underlying processing so I figured I didn't need to.  Guess I figured wrong!  Will wait for Jenkins to finish else it will upset him.

**Comment by DaveTBlake** [comment]
Understandable, but schema version does not only cover schema changes.

```

**Comment by DaveTBlake** [comment]
Understandable, but schema version does not _only_ cover schema changes :)
API consumers need a way to know the JSON they are using does or does not include an underlying fix. 

The schema `Version` method description documents it as follows

```
"major": "Bumped on backwards incompatible changes to the API definition"
"minor": "Bumped on backwards compatible additions/changes to the API definition" 
"patch": "Bumped on any changes to the internal implementation but not to the API definition" 
```

**Comment by the-black-eagle** [comment]
Ping @DaveTBlake, if you can review when you have some time.  Thanks.

**Review by DaveTBlake — APPROVED** [review]
Sorry been a bit distracted, this can go in now

**Pull request merged**
