### PR TITLE
Change SetShellVarContext from current to all

### PR DESCRIPTION
**Pull request by kwade00**
## Description

Changed one line in the Installer section and one line in the Uninstaller section. SetShellVarContext was set to 'current'; changed so that it sets to 'all'.

## Motivation and Context

SetShellVarContext tells the installer whether to perform the install for all users or just the current user. Since we require admin privileges for installation, it makes the most sense and fits with Windows standards to peform the installation for all users. This will put the shortcuts in the all users menu and the uninstall registry entries in the all users area of the registry.

## How Has This Been Tested?

I do not have a worthy machine for testing, but the change is a very simple NSIS script change.

## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by Paxxi — APPROVED** [review]
looks good to me

**Comment by Paxxi** [comment]
thank you @kwade00 , very much appreciated!

**Comment by MartijnKaijser** [comment]
@kwade00 could you PR the same change to Krypton branch?

**Comment by kwade00** [comment]
Done. #11815

**Pull request merged**
