### PR TITLE
[RFC][FONTCACHE] get rid of boost multi_index

### PR DESCRIPTION
**Pull request by Paxxi**
Ok so there seems to be some resistance against updating boost so then let's try and get rid of it. Here's a quick replacement for the font cache, it works fine, not perf tested and not cleaned up prroperly.

### CODE REVIEW

**Comment by Paxxi** [comment]
@koying @Memphiz @MartijnKaijser @fritsch review please :)

**Comment by Memphiz** [comment]
i nominate @bavison for a comment as well because he knows the code best.

**Comment by koying** [comment]
You have my +100 :)
I'll do droid testing next WE

**Comment by bavison** [comment]
I'd like to see some evidence that the change doesn't represent a significant speed hit. I deliberately chose boost:multi_index because none of the STL containers are efficient for use with more than one search criterion. Basically there are two things we need to do fast with the cache:

a) locate the oldest entry so we can expire it and re-use its resources
b) locate the entry where the text attributes and position match a previous rendering so we can re-use the same handle for a block of vertices previously transferred over to the GPU (this transfer is the slow operation which the font cache is attempting to optimise)

With the multi-index container, removing the oldest entry and reinserting it is O(1), and looking it up by the hash is also normally O(1).

It looks to me as though you have replaced the multi-index container with a simple std::list where the entries are ordered by age. This retains the O(1) removal and insertion, but the lookup uses find_if() which is now O(N).

If you really need to remove Boost, then I think the next best thing is to have two containers: one linked list and one hash table, each element containing a pointer to the corresponding element of the other container so that they can be removed and re-added in step. The payload information (vertex buffer handle) only needs to be stored in one or the other. Alternately, just use a hash table container and implement the linked list C style, using a pointer field inside the object.

But then the next question is whether you're happy to mandate C++11 support, because before that I believe the STL didn't even contain a single-index hash table container. I think your options would be to:

1) write a hash table container from scratch
2) mandate C++11 and use something like std::unordered_map
3) use std::map and live with lookup, removal and insertion going up to O(log N) - not great but better than O(N)

**Comment by fritsch** [comment]
Though your O Calculus is certainly correct - I also really want to see real life benchmarks, cause for small n it does not really matter if you have ld (n) or just n, let's say for (n < 10) for logarithmus dualis.

So what we need to know: how many elements are in those lists on average?

**Comment by popcornmix** [comment]
I believe C++11 is already a requirement for Kodi, so using C++11 features shouldn't be a problem.

**Comment by bavison** [comment]
It's a matter of the theme design and of what the maximum number of strings that have been visible on screen at the same time has been - not just instantaneously but at any time since the cache was flushed. If you've got a library open, with a clock in ther corner and a ticker at the bottom, and open a dialog box containing lots of buttons, then N will be in the tens and quite possibly low hundreds.

**Comment by fritsch** [comment]
Also take the "hash" method into account, which might be very expensive, when it is designed to not cause collisions (not the case for this key value map). From my personal experience - using a (hash)map with less than 50 elements is overkill.

**Comment by fritsch** [comment]
I think we should concentrate on howto "benchmark" this. I don't think that one "feels" the better / worse performance at all.

**Comment by Paxxi** [comment]
I added some quick and dirty logging, both methods mostly use 0ms, and sometimes 1 on container sizes ranging between 0 and 400.
More testing certainly needed but initial tests are promising at least.

**Comment by fritsch** [comment]
@MilhouseVH Could you give that a test in your nightlies, please?

**Comment by MilhouseVH** [comment]
This is now in my latest test build [#0716](http://forum.kodi.tv/showthread.php?tid=231092&pid=2054641#pid2054641)

**Comment by fritsch** [comment]
Thank you very much.

**Comment by fritsch** [comment]
@Paxxi Could you link your benchmark commit here, so that we can make some tests on different hw offline? Also can you post your figures, before and after?

**Comment by Paxxi** [comment]
Yeah I'll clean it up and post it tonight. I took it as an opportunity to test a new logging framework so it probably wont build on other platforms yet

**Comment by Paxxi** [comment]
Ok cleaned it up a bit and tested again, these numbers are with a debug build browsing through my list of tv shows. The tests aren't identical but browsing through the same lists at least.

logs can be found at
http://delusional.nu/boost.txt and http://delusional.nu/simple_list.txt
times are in nanoseconds and size is the size of the list/multiindex.

testing branch is in my repo https://github.com/Paxxi/xbmc/tree/bench , first commit is for testing with boost and second commit is for testing without boost.
No guarantee it builds on anything other than Windows.

Please don't ask me to explain the data, it's really not my strong side :)

**Comment by popcornmix** [comment]
Seems to be something wrong with the timing. Most times are zero and when non-zero they are ~10000. I suspect the timer doesn't really have nanosecond resolution.
I'll try running on Pi1. I know I have a working microsecond timer on there.
The fact that the size of the container reaches ~600 is useful info. It does suggest an O(n) lookup will be expensive.

**Comment by Paxxi** [comment]
apparently I forgot to include a file for the logger, should be added in the branch now and it seems it actually builds with no makefile changes on linux :)

**Comment by fritsch** [comment]
@Paxxi Are you sure that does not fallback on the sysclock which ms only?

http://www.cplusplus.com/reference/chrono/high_resolution_clock/ <- use that one?

**Comment by Paxxi** [comment]
thanks to @afedchin for pointing out that the steady_clock implementation is broken in VS2013 so here's a new try using QueryPerformanceCounter and times should be in microseconds.
http://delusional.nu/boost2.txt
http://delusional.nu/simple2.txt
Values for boost seems reasonable, they're fairly steady for cache hits as they should be

**Comment by Paxxi** [comment]
quick summary

method | N | min | q1 | median | q3 | max | sum | mean | stddev | stderr
-------|---|-----|----|--------|----|-----|-----|------|--------|-------
simple | 42923 | 6 | 18 | 30 | 36 | 4363 | 1.42983e+06 | 33.3115 | 54.2196 | 0.261705
boost | 57586 | 2 | 3 | 5 | 15 | 2776 | 820739 | 14.2524 | 31.7456 | 0.13229

**Comment by fritsch** [comment]
Nice figures. So using a map is next? :-)

**Comment by Paxxi** [comment]
ok more so more figures data for unordered_map http://delusional.nu/map.txt
first cache hits

method | N | min | q1 | median | q3 | max | sum | mean | stddev | stderr
-------|---|-----|----|--------|----|-----|-----|------|--------|-------
simple | 42923 | 6 | 18 | 30 | 36 | 4363 | 1.42983e+06 | 33.3115 | 54.2196 | 0.261705
boost | 57586 | 2 | 3 | 5 | 15 | 2776 | 820739 | 14.2524 | 31.7456 | 0.13229
unordered_map | 78425 | 4 | 7 | 8 | 15 | 3800 | 1.21149e+06 | 15.4478 | 28.5784 | 0.10205

and cache misses

method | N | min | q1 | median | q3 | max | sum | mean | stddev | stderr
-------|---|-----|----|--------|----|-----|-----|------|--------|-------
simple | 6713 | 9 | 37 | 46 | 68 | 5263 | 428641 | 63.8524 | 126.856 | 1.54829
boost | 8989 | 10 | 54 | 72 | 112 | 4259 | 822482 | 91.4987 | 97.4275 | 1.0276
unordered_map | 9199 | 15 | 147 |  334 | 446 | 4146 | 2.92865e+06 | 318.366 | 211.533 | 2.2055

**Comment by Paxxi** [comment]
looking at these values I must say it's some nice work you've done @bavison with hit rates around 85-90% that's a nicely tuned cache :)

**Comment by MartijnKaijser** [comment]
@Paxxi if this was (one of) the last part of totally getting rid of boost it's worth a shot perhaps.

**Comment by Paxxi** [comment]
@MartijnKaijser This is the big one, second would be circular cache in time smoother and the rest is silly stuff like using lexical cast when atoi would suffice.

**Comment by Paxxi** [comment]
ok more so more figures data for unordered_map with a doubly linked list for fast removal of old entries http://delusional.nu/map_list3.txt
first cache hits

method | N | min | q1 | median | q3 | max | sum | mean | stddev | stderr
-------|---|-----|----|--------|----|-----|-----|------|--------|-------
simple | 42923 | 6 | 18 | 30 | 36 | 4363 | 1.42983e+06 | 33.3115 | 54.2196 | 0.261705
boost | 57586 | 2 | 3 | 5 | 15 | 2776 | 820739 | 14.2524 | 31.7456 | 0.13229
unordered_map | 78425 | 4 | 7 | 8 | 15 | 3800 | 1.21149e+06 | 15.4478 | 28.5784 | 0.10205
uo_map+list | 55855 | 4 | 8 | 12 | 30 | 3924 | 2.39368e+06 | 42.8552 | 84.7321 | 0.358523
and cache misses

method | N | min | q1 | median | q3 | max | sum | mean | stddev | stderr
-------|---|-----|----|--------|----|-----|-----|------|--------|-------
simple | 6713 | 9 | 37 | 46 | 68 | 5263 | 428641 | 63.8524 | 126.856 | 1.54829
boost | 8989 | 10 | 54 | 72 | 112 | 4259 | 822482 | 91.4987 | 97.4275 | 1.0276
unordered_map | 9199 | 15 | 147 |  334 | 446 | 4146 | 2.92865e+06 | 318.366 | 211.533 | 2.2055
uo_map+list | 7445 | 15 | 108 | 289 | 468 | 312424 | 3.08904e+06 | 414.915 | 4405.94 | 51.0629

this approach yields far bigger caches, not yet sure where my logic's broken but perf isn't all that bad still except the max value for cache miss but that can have been because an accidental breakpoint.

**Comment by popcornmix** [comment]
Note: Milhouse builds have been unreliable over the last few days (since this PR was introduced), and a test build with this PR reverted has been reported as fixing the instability. It appears to cause a leak of resources (textures?) that eventually causes GPU allocation failures.
Some info here: http://forum.kodi.tv/showthread.php?tid=231092&pid=2056217#pid2056217

**Comment by Paxxi** [comment]
Thanks @popcornmix I noticed something like what's described there with the fonts. I probably missed some cleanup. Will try and clean up my latest testing and update this pr with the map+list version

**Comment by FernetMenta** [comment]
@Paxxi do you intend to continue work on this?

**Comment by Paxxi** [comment]
@FernetMenta not sure when I will have the time and energy, have been low on both for some time. If you're interested go ahead and continue on it or replace it all together. 
Will try and focus on upgrading to vs2015 first and foremost.

**Comment by FernetMenta** [comment]
@Paxxi see #8996

**Comment by Paxxi** [comment]
Closing this as it's superseded by #8996

**Pull request closed without merging**
