### PR TITLE
Remove use of pcrecpp from Kodi

### PR DESCRIPTION
**Pull request by rschupp**
## Description
Remove use of pcrecpp from Kodi

This PR converts the only user of  prcecpp in Kodi, `xbmc/filesystem/FTPParse.cpp` , to use `std::regex` instead.
It also removes any reference to pcrecpp from tooling.

The first commit is the actual port from pcrecpp to std::regex. It simply changes `pcrecpp::RE` initializers to `std::regex` and methods `pcre::FullMatch` and `pcre::PartialMatch` to `std::regex_match` and `std::regex_search`, resp.

The only exception is changing the conversion from three-letter abbreviated month name to month number (`tm_mon` in `struct tm`) from the elaborate (pseudocode)
```
if month ~ "jan":
  tm_mon = 0
else if month ~ "feb":
  tm_mon = 1
...
```
to a more compact (and efficient) form (`setMonFromName`).
  
The other commits are optional code clean up:
- remove getDayOfWeek(): unused outside of FTPParse.cpp
- replace atoi() with std::stoi() and strtod() with std::stoul()
- move all regexes to where they're used and use "auto" to name sub matches

## Motivation and context
There are lots of complaints that Kodi still uses the EOL pcre v1 library (and its C++ covenience wrapper pcrecpp) , but efforts to port to pcre2 seem to have been forestalled by the fact that there is no equivalent of pcrecpp for pcre2, see e.g. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1000113#21

## How has this been tested?
Build (using latest LibreELEC) and tested against a Linux server (proftpd), file listings in `Videos/Files` or `Settings/File Manager` look as expected wrt. reported file sizes and modification dates.

## What is the effect on users?
None.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by basilgello** [comment]
Thanks for this PR! This greatly helps in Debian!

**Comment by basilgello** [comment]
Should I try linking to pcre2 already or this is kind of preliminary step?

**Comment by rschupp** [comment]
@basilgello 
> Should I try linking to pcre2 already or this is kind of preliminary step?

Not yet, somebody still has to port `utils/RegExp.cpp` to pcre2 (or std::regex).

**Comment by basilgello** [comment]
Ah, ok :)

**Comment by lrusak** [comment]
> Don't bother with pcre2. Only reason we did not go for std::regex earlier
> was the xml scraper legacy and that is no more a concern. std::regex should
> be ample, i suspect the whole cregexp wrapper can and should be dropped.
> 

I'm not sure if this works or not since it was from 6 years ago. https://github.com/lrusak/xbmc/commit/1a48ffc91cabf208bfa52053d61e19ae6daea3ec

**Comment by basilgello** [comment]
Let me check :) TBH I was bit hesitant to rewrite pcre stuff as it is a potential can of security worms :) But I need it in Debian.

**Comment by rschupp** [comment]
AFAICT nothing in kodi relies on regular expression features that aren't available in std::regex. 
`xbmc/utils/RegExp.h` has methods dealing with named captures (in pcre syntax "(?<name>...)") which std::regex doesn't implement, but no code uses this syntax. Moreover,  kodi still compiles after removing these methods (see below).
```diff
--- a/xbmc/utils/RegExp.h
+++ b/xbmc/utils/RegExp.h
@@ -111,15 +111,10 @@ public:
   };
   int GetSubCount() const { return m_iMatchCount - 1; } // PCRE returns the number of sub-patterns>
   int GetSubStart(int iSub) const;
-  int GetSubStart(const std::string& subName) const;
   int GetSubLength(int iSub) const;
-  int GetSubLength(const std::string& subName) const;
   int GetCaptureTotal() const;
   std::string GetMatch(int iSub = 0) const;
-  std::string GetMatch(const std::string& subName) const;
   const std::string& GetPattern() const { return m_pattern; }
-  bool GetNamedSubPattern(const char* strName, std::string& strMatch) const;
-  int GetNamedSubPatternNumber(const char* strName) const;
   void DumpOvector(int iLog);
   /**
    * Check is RegExp object is ready for matching
```

**Comment by rschupp** [comment]
Converting all of kodi to use std::regex is a major undertaking, `xbmc/utils/RegExp.h` and its public methods are referenced on 426 lines on 43 files.

I suggest to convert `RegExp.cpp` to use std::regex first, as it has a rather small interface (you can drop the named capture stuff, see above) and then conversion from `CRegExp` to std::Regex can be done gradually, e.g. dust off https://github.com/lrusak/xbmc/commit/1a48ffc91cabf208bfa52053d61e19ae6daea3ec

**Comment by rschupp** [comment]
> AFAICT nothing in kodi relies on regular expression features that aren't available in std::regex.

Correction: according to https://en.cppreference.com/w/cpp/regex/ecmascript std::regex supports:
- non-greedy quantifiers `*?`, `+?`, `??`, `{...}?`
- positive and negative lookahead `(?=pattern)`, `(?!pattern)`

but does **not** support:
- "internal" option setting `(?i)`, `(?i:pattern)`: not used in kodi
- possessive quantifiers `*+`, `++`, `?+`, `{...}+`: not used in kodi
- positive and negative lookbehind `(?<=pattern)`, `(?<!pattern)`: not used in kodi
- named capture groups `(?<name>...)`, `(?'name'...)`, `(?P<name>...)`: not used in kodi
- verbs `(*FAIL)` etc: not used in kodi
- alphabetic "assertion" names `(*positive_lookahead:...)` etc: not used in kodi
- conditional groups `(?(condition)yes-pattern)`,  `(?(condition)yes-pattern|no-pattern)`: not used in kodi
- ["atomic" groups](https://www.pcre.org/current/doc/html/pcre2pattern.html#TOC1) `(?>pattern)`: **used** in  `xbmc/cores/VideoPlayer/DVDSubtitles/webvtt/WebVTTHandler.cpp` 
- more stuff

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by tomachinz** [comment]
Nice work people! Kodi is now building for the first time on my (noob) machine after pcre was disabled good work!

**Pull request merged**
