### PR TITLE
Remove the copying.txt file as copy of LICENSE.GPL (future LICENSE.txt)

### PR DESCRIPTION
**Pull request by Hedda**
Recommend that the copying.txt file is removed because it is just a copy of the LICENSE.GPL file (which in turn may be renamed to LICENSE.txt in the future).

As per the discussion in pull request #8958 

Anyway, at least one of these files can be removed as the content text is the same so no need to keep both files for reduncancy.

### CODE REVIEW

**Comment by un1versal** [comment]
https://github.com/xbmc/xbmc/search?utf8=%E2%9C%93&q=copying.txt

umpteen headers to update here, good luck

**Comment by MAFLO321** [comment]
@Hedda only one file to edit: https://github.com/xbmc/xbmc/search?utf8=%E2%9C%93&q=%22copying.txt%22
and there the [line](https://github.com/xbmc/xbmc/blob/f42c66f130805765b0c30d947980d5f2af847cde/project/Win32BuildSetup/BuildSetup.bat#L200) clould be removed because of duplicate of "LICENSE.GPL" in the next line

**Comment by un1versal** [comment]
@MAFLO321 youre blind, its best if you remove LICENSE.GPL since all boilerplates reference the copying file

**Comment by stourwalk** [comment]
Or you're both right about different things.

One file to edit to handle the removing the actual file
lots of files to edit to remove the reference in the boilerplates comment.

**Comment by MAFLO321** [comment]
sorry, that was my falt.. you are right @un1versal that would be the best and rename "copying.txt" to "COPYING" that would be the easiest way.

**Comment by MartijnKaijser** [comment]
i'm gonna close this for now as it needs to be correctly all over the place

**Pull request closed without merging**
