### PR TITLE
[cleanup] Remove unused files

### PR DESCRIPTION
**Pull request by fetzerch**
xbmc/utils/WindowsShortcut.h/cpp and
xbmc/win32/WMIInterface.h/cpp are unused.

### CODE REVIEW

**Comment by fetzerch** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
please try again after you accept team invite for github

**Comment by fetzerch** [comment]
@MartijnKaijser: Thanks much!

jenkins build this please

**Comment by Paxxi** [comment]
Good find

**Pull request merged**
