### PR TITLE
[win32] fix crash after #13722 + cosmetics

### PR DESCRIPTION
**Pull request by afedchin**
see title

### CODE REVIEW

**Review by FernetMenta — APPROVED** [review]
thanks very much!

**Comment by DaveTBlake** [comment]
Thanks for this @afedchin, but now master is giving me crashes on exit. Seems to be from `CGUIWindowManager::DeInitialize()` so related to this or #13722?

**Comment by FernetMenta** [comment]
https://github.com/xbmc/xbmc/pull/13720 will fix this

**Comment by DaveTBlake** [comment]
So really @FernetMenta I had best just give up on trying to rebase and get a working test build until all the global killing is over?

**Comment by garbear** [comment]
@DaveTBlake global killing is never truly over with Kodi :) I have a few lined up, but yea I'll ping you whenever I open a PR. I've never failed to break something with a globals refactor :)

**Pull request merged**
