### PR TITLE
[tools/depends] Bump ldid to 2.1.2-b462a92

### PR DESCRIPTION
**Pull request by sy6sy2**
## Description

`ldid` tool allows us to fake sign our Kodi binaries and libraries so that any jailbroken user can directly install our deb file without the painful 7-days signing process.

This version of `ldid` add support to jailbroken iOS 14 devices (see https://github.com/sbingner/ldid/pull/2).

Before, we used a pre-build `ldid` binary.
Now, with this PR we build `ldid` directly from source files, like we do for all other Kodi dependancies.

## Motivation and Context

Without this PR, jailbroken iOS 14 users needs to re-fakesign Kodi after the install with the `ldid -S /Applications/Kodi.app/Kodi` command.
Without this step, Kodi won't open.

## How Has This Been Tested?

* Tested on iPhone 7, iOS 13.3.1, checkra1n by me.
* Tested on iPad Air 2, iOS 14 by Piprider007 (see https://forum.kodi.tv/showthread.php?tid=357282&pid=2980176#pid2980176)
* Tested on Apple TV 4K tvOS 13.4.8 (Kodi + TopShelf feature), checkra1n by me.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by sy6sy2** [comment]
But, even if this PR is merged, all current deb files that we have on:
* http://mirrors.kodi.tv
* Official Kodi Cydia repo
* BigBoss Cydia repo
are broken for all iOS 14 jailbroken users 😕 

No need to build Kodi again, we just need to unpack the deb file, re-fakesign Kodi with the new ldid binary, then re-create the deb file.
I can do it manually, at least for Kodi 18.8-0 deb file, and re-upload on the FTP the correct deb file. What is your point of view about that? Should I bump the version (like we did for android recently), let's say Kodi 18.8.1-0?

**Comment by phunkyfish** [comment]
I don’t think we should update to an unreleased version of a library.

**Comment by sy6sy2** [comment]
The problem is that we do not compile ldid from source, we just untar the binary... so it's not possible to apply a patch.

**Comment by phunkyfish** [comment]
That we should probably request the changes are upstreamed.

**Comment by sy6sy2** [comment]
The "real" upstream is Saurik (the creator of Cydia and also a lot of thing in the jailbreak community) --> git://git.saurik.com/ldid.git

sbingner is also a well know guy of the jailbreak community since some time (creator of TetherMe).

Checkra1n jailbreak is still closed-source, so it's hard to exactly know what is the version of ldid in checkra1n devices...

**Comment by fuzzard** [comment]
Did you try to add it to build in Kodi build system?
I'm not real concerned about whoever upstream is, and if you need to base off hash (we already have these situations), but would be nice to get away from anything precompiled imo

**Comment by sy6sy2** [comment]
I did not try yet. But I will try to let Kodi build ldid directly during the depends process.
You are right, it will be cleaner.

**Comment by sy6sy2** [comment]
In this state, deb file built from this [job](https://jenkins.kodi.tv/view/Automation/job/BuildMulti-PR-Manually/383/) works great on iOS.
I will try the tvOS deb tonight.

**Comment by sy6sy2** [comment]
Works great on Apple TV too.
Anything to change before I ask Jenkins to re-build?

**Comment by sy6sy2** [comment]
jenkins build this please

**Comment by sy6sy2** [comment]
If you have time guys, can you have a look to this PR for a last review.
If possible I would like to have it include in the next hotfix release so that any iOS 14 jailbroken user can have a working Kodi 18 release. 🙏

**Comment by phunkyfish** [comment]
It's fine by me once @fuzzard and @kambala-decapitator are happy with it. I'm not sure about v18 though, we would usually not change any depends in a stable release unless absolutely necessary.

Will leave it to you guys to decide.

**Review by phunkyfish — APPROVED** [review]
Looks fine to me. But a final pass from @fuzzard would be good.

**Comment by phunkyfish** [comment]
Just curious. Did you ask sbingner to make a release? It would be much cleaner than building from a hash.

**Comment by sy6sy2** [comment]
> I'm not sure about v18 though, we would usually not change any depends in a stable release unless absolutely necessary.

No problem for me, I can always re-fakesign Kodi 18.9 manually and re-upload it on our mirror so that any jailbroken iOS 14 users will be happy.

> Just curious. Did you ask sbingner to make a release? It would be much cleaner than building from a hash.

Yes I ask him [here](https://github.com/sbingner/ldid/pull/2) but no answer yet.

**Comment by fuzzard** [comment]
If it works, go nuts. I wouldnt be backporting to 18 though, far too late.

**Review by kambala-decapitator — APPROVED** [review]
Also agree that Leia can be uploaded manually, won't be needed that often :)

**Pull request merged**
