### PR TITLE
[cmake][backport] PR11088, PR11158 and PR11183

### PR DESCRIPTION
**Pull request by hudokkow**
Backport:
#11088
#11158
#11183 (partial)

Ping @wsnipex, @stefansaraev and @fetzerch
I might have missed some follow up to the original PR (#11088)

### CODE REVIEW

**Comment by stefansaraev** [comment]
thanks. lgtm. should be ok if jenkins is happy.

cc @MilhouseVH this is worth a build test on LE before merging, if you have time.

**Comment by wsnipex** [comment]
thanks, one to cross off my list :)

**Comment by hudokkow** [comment]
> thanks, one to cross off my list :)

Ditto!

**Review by fetzerch — APPROVED** [review]
Thanks!

**Comment by lrusak** [comment]
Works for me! This allows us to get rid of another patch :+1:

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Pull request merged**
