### PR TITLE
fixed: Seeking with FileCache could lockup due to terminated thread

### PR DESCRIPTION
**Pull request by arnova**
Backport of #17211

### CODE REVIEW

**Comment by DaveTBlake** [comment]
Is this tested and ready for merge @arnova ? I know that some of this FileCache stuff has been a bit fragile, where are we with this?

**Comment by arnova** [comment]
> Is this tested and ready for merge @arnova ? I know that some of this FileCache stuff has been a bit fragile, where are we with this?

This one should be fairly safe and the original fix has been in master for about a week now, so if you're fine with this, hit green ;-)

**Comment by DaveTBlake** [comment]
Ho, fast on the button @fritsch, I was just hovering over it

**Comment by fritsch** [comment]
:-) I have seen you moving the mouse and wanted to overtake you :P

**Pull request merged**
