### PR TITLE
[pictures] minor settings cleanup

### PR DESCRIPTION
**Pull request by mkortstiege**
This removes two superfluous options related to `EXIF` handling in pictures section.

### CODE REVIEW

**Comment by Razzeee** [comment]
Code seems fine. This will emulate them always being true correct? I think thats a good idea also.

**Comment by mkortstiege** [comment]
> Code seems fine. This will emulate them always being true correct? I think thats a good idea also.

Jep. Both settings default to true.

**Comment by MartijnKaijser** [comment]
ok

**Comment by mkortstiege** [comment]
@Montellese, @Paxxi objections?

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
I'm not sure about removing the rotate setting, afaik it's not uncommon with broken data for this field.

**Comment by MartijnKaijser** [comment]
@Paxxi and what are you gonna do with broken data?
go back and forward to settings for each picture?

**Comment by Paxxi** [comment]
No but if you have lots of pics with broken data it might be nice to have a choice on how they're displayed.

A rotate image key or rotate in sidebar would work as well

**Comment by MartijnKaijser** [comment]
having this option burried in settings doesn't help either for broken pictures

**Comment by mkortstiege** [comment]
> A rotate image key or rotate in sidebar would work as well

Enter rotates.

**Comment by rmlevit** [comment]
I am brand new to github and I apologize if I'm doing this wrong, but I'm posting to inform you that this decision has caused problems for users of Kodi 16 on Android, Windows and Linux platforms. I run Kodi on a Raspberry Pi. Upon upgrading to version 16, slideshow or navigation into directories containing large numbers (hundreds) of JPG images is now sucking up all available RAM and causing Kodi to crash and reboot, or just to freeze and remain unresponsive, every single time.

Without an option to stop Kodi from scraping the media info from image files, it now seems to try to scrape all the media info by default. If the directories contain hundreds of JPG files, available RAM plummets below 40Mb and Kodi freezes. Trying to run a recursive slideshow on the directory without actually traversing into it also results in the same crash/reboot or freeze.

Directories with a small number of images are not affected. I don't know what the thrsmeshhold is at which the directory contains too many images to handle, but I suppose it must depend on how much RAM the platform has. The following logic is badly needed:

PUBLIC CONST maxFilesToScrape = 100
SUB doSlideshow (imageDirectory AS fileSystem.directory)

     DIM file AS fileSystek.file
          IF imageDirectory.fileCount <= maxFilesToScrape THEN
               FOR EACH file in imageDirectory
                    SCRAPE file.mediaInfo
          NEXT file
     ELSE
          DO NOT SCRAPE mediaInfo
     END IF
    ...
END SUB

**Comment by markst** [comment]
@rmlevit are you sure the exif scraping is the reason for the ram maxout?

**Pull request merged**
