### PR TITLE
[PVR] Fix 'Stop recording' from inside PVR channel window, another case.

### PR DESCRIPTION
**Pull request by ksooo**
Followup to #9839, where I forgot to handle another special case.

@xhaggi @Jalle19 for review?

### CODE REVIEW

**Comment by xhaggi** [comment]
+1

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins is happy, more seems not to be possible these days. ;-)

**Comment by hudokkow** [comment]
> jenkins is happy, more seems not to be possible these days. ;-)

I see what you did there, eheheh! :stuck_out_tongue_winking_eye:

**Pull request merged**
