### PR TITLE
VideoPlayer: handle exceptional case where distance between keyframes…

### PR DESCRIPTION
**Pull request by FernetMenta**
The user who created http://trac.kodi.tv/ticket/16911 has issues with self encoded videos. The distance between keyframes is chosen much to large, 240 frames. For 24fps that results in 10 seconds while demux queue is only 8 seconds. As a result audio queue may be full while video has still not found a key frame required to start.

### CODE REVIEW

**Comment by Jalle19** [comment]
Does this affect situations where you pull the antenna cable while watching live TV, then insert it again after let's say 30 seconds?

**Comment by FernetMenta** [comment]
Not sure what exactly you mean by "affect". The scenario you described has always been working for me using vnsi. I just tried and it is not broken with this change here.

**Comment by Jalle19** [comment]
@FernetMenta that's all I wanted to know, thanks

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
Android build error unrelated
Fix confirmed by http://trac.kodi.tv/ticket/16911#comment:17

**Pull request merged**
