### PR TITLE
dvdplayer: fix clock speed

### PR DESCRIPTION
**Pull request by FernetMenta**
fix clock speed and get rid of this rounding magic

### CODE REVIEW

**Comment by FernetMenta** [comment]
@MartijnKaijser @topfs2 maybe reconsider a 14.2? this alone would be worth it.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by fritsch** [comment]
Now, that we have discussed this. What about LOGWARNING - that is printed once, when we see that passthrough audio is active and video clock is active, but fps not fitting to the video fps and therefore the audio clock is wrong to passthrough without lots of drops / dupes (at least once a minute) or something?

**Comment by FernetMenta** [comment]
would be nice if you could do so. my list of to-dos is long and I won't be able to work on this for quite a while

**Comment by fritsch** [comment]
Jep, will do! Just thought I ask for your oppinion before doing that.

**Pull request merged**
