### PR TITLE
[Subtitles] Bump libass to 0.15.2

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

This PR updates the libass version to 0.15.2 already uploaded in mirrors

This include also two main bugfixes to our Windows patches:
- Fixed crash when loading fonts from the user folder
- Fixed loading of fonts with non-ascii file names

@Paxxi please check correctness of this commit, and when you have a bit of time https://github.com/xbmc/libass need to be sync with your repo

@enen92 Maybe a backport to Matrix?

## Motivation and context

Keep update with current versions + Windows bugfixes

## How has this been tested?

Tested on Windows 64bit

## What is the effect on users?

Users can load ttf fonts from the user folder without Kodi crashes

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
Tools/depends isn't used by windows, so of you update that can you remove the [windows] aspect, as you are then updating every platform

**Comment by wsnipex** [comment]
libass 0.15.2 uploaded to mirrors
jenkins build this please

**Review by thexai — APPROVED** [review]
Tested on Windows x64

**Review by enen92 — APPROVED** [review]
Tested on linux and android, all my samples work.
Thanks

**Comment by enen92** [comment]
Regarding the backport I don't think its worth it. Matrix is still in 0.14.0 and the majority of the improvements that have been done incrementally to libass are not part of Matrix. Since subtitles is seeing a big rework for v20 i'd keep this v20 only.

**Comment by thexai** [comment]
I agree with @enen92. In any case, it shouldn't be done without testing it on Xbox first. So it would not be for v19.2 that is imminent.

**Pull request merged**
