### PR TITLE
[CONFLUENCE] use VARs for list overlays

### PR DESCRIPTION
**Pull request by phil65**
as title says. again, saves some code and also some condition checks.
@ronie again for review.

### CODE REVIEW

**Comment by ronie** [comment]
would you mind moving the variable definitions to includes.xml, where the other vars are listed as well?
i think it would be nice if we keep them all together in a single xml file.

**Comment by ronie** [comment]
^ @phil65 ?

**Comment by phil65** [comment]
Can do, but they´re already "split" in two files already now...

**Comment by ronie** [comment]
ok, fixed that. :-)

**Pull request closed without merging**
