### PR TITLE
RegExp for URL path comparision - essential for dynamic subdomains

### PR DESCRIPTION
**Pull request by ghost**
@FernetMenta: do you remember the discussion about it?

### CODE REVIEW

**Comment by mapfau** [comment]
OT: the current xbmc master does not compile on my machine because of missing:

demuxStream->uniqueId

**Comment by FernetMenta** [comment]
I thought we had this already. Did this change get lost?

jenkins build this please.

**Comment by mapfau** [comment]
Yes, it seems that it was one in the monster commit... 
Just noticed that I have an inconsitend line ending in my commit :-(
Can I still correct it in this PR?

**Comment by FernetMenta** [comment]
@mapfau just force push to this branch and the PR will update. I'll cancel jenkins job.

**Comment by mapfau** [comment]
thanx, done

**Comment by FernetMenta** [comment]
jenkins build this please

**Pull request merged**
