### PR TITLE
[adsp] disable binary add-on until they build on all platforms

### PR DESCRIPTION
**Pull request by MartijnKaijser**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build addons please

**Comment by MartijnKaijser** [comment]
@Montellese add-ons still fail/succeed to build while they shouldn't even start right?

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build addons please

**Comment by Montellese** [comment]
At least on win32 it should only build the addons whose buildsystem has been successfully prepared by cmake. It looks like the same logic should be used by platforms using the depends system as well but I've never tried that myself. I also don't know how the depends-based approach cleans previous binary addon builds. On win32 we clean everything and rebuild everything.

**Comment by MartijnKaijser** [comment]
somehow after kicking it again through the backpanel it worked

**Pull request merged**
