### PR TITLE
Aml mxs specifics

### PR DESCRIPTION
**Pull request by t-nelson**
Cleanup for AML MXS device specifics

### CODE REVIEW

**Comment by koying** [comment]
Ping to myself. Rebase after #6432

**Comment by Stane1983** [comment]
Sorry for delayed reply... I don't see any other option at the moment, but I don't think aml_wired_present() is good check. What if someone connects USB eth adapter? In that case eth0 interface will also be created. I can't check this, I don't have any MXS dongle or usb eth adapter.

**Comment by davilla** [comment]
aml_wired_present check was aimed at aml sticks like gamestick and such and was never intended to handled ALL types of wired network adapters.

**Comment by Hedda** [comment]
Is the plan still for these to be rebased and go in now that #6432 been merged?

**Comment by koying** [comment]
Well, I wondered yesterday and I would more in favor of removing the cpufreq hacks also. All those things should be handled at the OS level, really, and shouldn't be forced by Kodi.

In this instance, the differentiation between M6 and MXS is pointless.

**Comment by koying** [comment]
obsolete

**Pull request closed without merging**
