### PR TITLE
[Teletext] Fix diacrit unicode chars using harfbuzz

### PR DESCRIPTION
**Pull request by enen92**
## Description
Kodi's teletext implementation is not able to render alphanumeric chars which have diacritical marks. The implementation of the decoder is correct and it respects the standard (ETS 300 706) the root cause of the problem being the fact we rely on libfreetype2 for the composition. libfreetype does not support composition of unicode characters, delegating it to external shaping or auxiliar libraries (see https://lists.gnu.org/archive/html/freetype/2002-09/msg00078.html). To be able to do this we actually render two alphanumeric chars to the same buffer and do some sort of magic with the pitch. As you can imagine, this does not work reliable.
Since for v20 we include harfbuzz for the skinning engine and libass, we can simply use the unicode part of the harfbuzz library to handle the combination and render the resulting character instead.

Unsure who can review this. Lottery result says @ksooo :)

## Motivation and context
Characters like ã, õ, Ó, etc are displayed without the diacritical marks nowadays.

## How has this been tested?
Runtime tested with Portuguese tv channels and one old spanish txt sample.

## What is the effect on users?
Diacritical marks should now render correctly in the teletext gui dialog.

## Screenshots (if appropriate):

**Master:**
Screenshot 2022-11-21 at 13 01 52
Screenshot 2022-11-21 at 13 02 18
Screenshot 2022-11-21 at 13 03 06

**PR:**
Screenshot 2022-11-21 at 11 42 46
Screenshot 2022-11-21 at 11 43 59
Screenshot 2022-11-21 at 11 44 42

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by enen92** [comment]
Looks like one of the pages even tests the decoder :)

Screenshot 2022-11-21 at 14 03 42

**Comment by ksooo** [comment]
> Unsure who can review this. Lottery result says @ksooo :)

I feel like I cannot say anything regarding the correctness of this change, sorry. Best reviewer would be @AlwinEsch I guess.

**Comment by scott967** [comment]
Don't know harfbuzz, but isn't there a unicode normalization in there that auto-composes if the font supports the composed codepoint?

**Comment by enen92** [comment]
That's what this PR does...

**Comment by scott967** [comment]
OK from looking at it I was thinking the commit was only for diacritical marks, I was thinking of the more general case for all NFC normalization.

**Comment by fuzzard** [comment]
Can see a clear difference. Only affects teletext, lets merge

**Pull request merged**
