### PR TITLE
Revert "AE: change usage of swr_set_compensation"

### PR DESCRIPTION
**Pull request by FernetMenta**
This reverts commit 7f4f89ba3a36454b01c80103068e338a7d65dbfa.

fix for http://trac.kodi.tv/ticket/16887

### CODE REVIEW

**Comment by fritsch** [comment]
Please let's wait until: http://trac.kodi.tv/ticket/16887#comment:22 has verified. Perhaps that only covers another issue :-)

**Comment by FernetMenta** [comment]
I have confirmed it working. You can do this too if you player the provided sample. I will merge this evening.

**Comment by FernetMenta** [comment]
got confirmed this very moment, what a surprise :)

jenkins build this please

**Comment by fritsch** [comment]
This breaks DTS in flac. Which is not really a breakge as I consider the dts wav encoded to flac as something totally non standard. But it seems we somehow apply some compensation even when just doing audio playback, meaning: the very moment we call sws_whatever_compensation we alter audio so that it is not "bit perfect" anymore and this results in DTS RAW issues (e.g. noise).

**Comment by fritsch** [comment]
Some comments by our ffmpeg friends:

```
20:50 <@nevcairiel> fritsch: tell them to diaf rather quickly =p
21:13 <@nevcairiel> for some reason thats a recurring idiocy
21:13 <+wm4> fritsch: use the kodi funds or whatever you have to hire a hitman?
21:22 < rcombs> fritsch: I'd recommend telling the user to fuck off
(asked before I added this cites here)
```

**Pull request merged**
