### PR TITLE
[python] fix memory leak in multiselect

### PR DESCRIPTION
**Pull request by tamland**
As discussed in https://github.com/tamland/xbmc/commit/eb6676a6b3eb20ae9e85574d158d00460b88aff7

cc @jimfcarroll, @ace20022

### CODE REVIEW

**Comment by tamland** [comment]
jenkins build this please

**Comment by jimfcarroll** [comment]
+1 - Looks good.

**Comment by tamland** [comment]
jenkins build this please

**Comment by tamland** [comment]
Indeed looks like the `>>` was the issue. The old swig in depended doesn't understand c++11:)

**Comment by ace20022** [comment]
Thx!

**Pull request merged**
