### PR TITLE
Fix compilation on sh4/sparc/arc/xtensa

### PR DESCRIPTION
**Pull request by bkuhls**
## Description
These commits fix compilation on sh4/sparc/arc

## How Has This Been Tested?
Compile-tested using buildroot toolchains.

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by bkuhls** [comment]
Added xtensa support, also rewrapped if-def lines.

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
out of interest: Does anyone actually run kodi on those platforms? e.g. sparc feels almost as useful as s390x support ;)

**Comment by bkuhls** [comment]
A debian port for sparc64 exists for which kodi is currently not available, a buildroot-toolchain for sparc64 can build kodi with these patches. My goal here is to make kodi builds possible when small fixes like these are enough to achieve this, I do not have access to the hardware supported by this patch ;)

**Comment by MartijnKaijser** [comment]
@wsnipex good for merge?

**Pull request merged**
