### PR TITLE
pipewire: remove CPipewireGlobal class

### PR DESCRIPTION
**Pull request by lrusak**
the `CPipewireGlobal` class was basically used for caching data. some of the data was only used once and much of the data wasn't used at all. It's just an unneeded layer and we can simplify things by getting rid of it.

### CODE REVIEW

**Review by neo1973 — APPROVED** [review]

**Review by neo1973 — CHANGES_REQUESTED** [review]
I just noticed that now it re-enumerates the devices when starting or stopping media resulting in log spam:
```
2024-11-01 19:49:10.241 T:32330    info <general>: Enumerated PIPEWIRE devices:
2024-11-01 19:49:10.241 T:32330    info <general>:     Device 1
2024-11-01 19:49:10.241 T:32330    info <general>:         m_deviceName      : Default
2024-11-01 19:49:10.241 T:32330    info <general>:         m_displayName     : Default
2024-11-01 19:49:10.241 T:32330    info <general>:         m_displayNameExtra: Default Output Device (PIPEWIRE)
2024-11-01 19:49:10.241 T:32330    info <general>:         m_deviceType      : AE_DEVTYPE_PCM
2024-11-01 19:49:10.241 T:32330    info <general>:         m_channels        : FL, FR
2024-11-01 19:49:10.242 T:32330    info <general>:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
2024-11-01 19:49:10.242 T:32330    info <general>:         m_dataFormats     : AE_FMT_RAW,AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_S24NE3,AE_FMT_FLOAT
2024-11-01 19:49:10.242 T:32330    info <general>:         m_streamTypes     : No passthrough capabilities
2024-11-01 19:49:10.242 T:32330    info <general>:     Device 2
2024-11-01 19:49:10.242 T:32330    info <general>:         m_deviceName      : alsa_output.pci-0000_05_00.6.analog-stereo
2024-11-01 19:49:10.242 T:32330    info <general>:         m_displayName     : Family 17h/19h HD Audio Controller Analog Stereo
2024-11-01 19:49:10.242 T:32330    info <general>:         m_displayNameExtra: Family 17h/19h HD Audio Controller Analog Stereo (PIPEWIRE)
2024-11-01 19:49:10.242 T:32330    info <general>:         m_deviceType      : AE_DEVTYPE_PCM
2024-11-01 19:49:10.242 T:32330    info <general>:         m_channels        : FL, FR
2024-11-01 19:49:10.242 T:32330    info <general>:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
2024-11-01 19:49:10.242 T:32330    info <general>:         m_dataFormats     : AE_FMT_RAW,AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_S24NE3,AE_FMT_FLOAT
2024-11-01 19:49:10.242 T:32330    info <general>:         m_streamTypes     : No passthrough capabilities
```
See https://paste.kodi.tv/izubobubav.kodi for the full log.

**Comment by lrusak** [comment]
> I just noticed that now it re-enumerates the devices when starting or stopping media resulting in log spam:
> 
Thanks for catching that. I can see why it happens. One of the main drivers behind this is to make the pipewire code more agnostic to the system that is using it. I would like to eventually shift the code so it can be used for video stuff also.

The new code will make a `CPipewireNode` instance for all nodes, as before it would only allow `Audio/Sink` types. So when we create a new node in kodi (the playback stream) a new Node is created and the trigger to enumerate devices is fired in `CPipewireProxy`.

The options are to possibly add a map for specific node types, so we can call `GetAudioNodes` or similar, or we just move the `Audio/Sink` back into the `CPipewireRegistry`.

**Comment by lrusak** [comment]
@neo1973 I pushed a fixup to fix the described issue

**Review by neo1973 — APPROVED** [review]
Thanks, looks good now :+1:

**Comment by lrusak** [comment]
squashed

**Comment by fuzzard** [comment]
Jenkins build this please

**Pull request merged**
