### PR TITLE
[eventserver] Fix runscript builtin

### PR DESCRIPTION
**Pull request by Paxxi**
Don't parse the action in EventServer, Builtins want it unmodified

### CODE REVIEW

**Comment by Paxxi** [comment]
@anaconda test please, seems fine in my testing.

**Comment by anaconda** [comment]
Yep, this fixes it. Thanks!

**Comment by mkortstiege** [comment]
+1. jenkins build this please.

**Comment by anaconda** [comment]
No, got broken in #8018 4 days ago in master.

**Pull request merged**
