### PR TITLE
[cmake] find_package(PkgConfig) sets required variables

### PR DESCRIPTION
**Pull request by olafhering**
Per cmake 3.4 documentation, FindPkgConfig does set the used variables.
There is no need to set them again.

Remove PKG_CONFIG_EXECUTABLE check
Remove setting of PKG_CONFIG_FOUND

Signed-off-by: Olaf Hering <olaf@aepfle.de>

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by Rechi — APPROVED** [review]

**Review by AlwinEsch — APPROVED** [review]

**Comment by pkerling** [comment]
Unfortunately there is no indication why this was ever required, but if Jenkins is happy...

**Comment by wsnipex** [comment]
FindPkgConfig.cmake uses PKG_CONFIG_EXECUTABLE to look for the binary. Setting this variable allows the user to override the binary location. This is useful mostly for some of the more arcane cross-compile setups out there. I'm not sure if it is still used, but it certainly doesn't hurt.

**Comment by Rechi** [comment]
This is inside a if `KODI_DEPENDSBUILD`, so not used for arcane cross-compile setups.
Also one can always override the value for find_program, find_library and find_path without any additional hacks needed.

**Comment by olafhering** [comment]
I think specified a specific binariy can be done today, and I think this does not depend on cross or not:

````
-DPKG_CONFIG_EXECUTABLE:STRING=$(type -P false)
...
[   26s] -- Found PkgConfig: /usr/bin/false (found version "false (GNU coreutils) 8.31
[   26s] Copyright (C) 2019 Free Software Foundation, Inc.
[   26s] License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
[   26s] This is free software: you are free to change and redistribute it.
[   26s] There is NO WARRANTY, to the extent permitted by law.
[   26s]
[   26s] Written by Jim Meyering.")
````

To me it looks like all 5 lines can be removed, they look like a no-op.

**Comment by DaveTBlake** [comment]
@Rechi @AlwinEsch any reasons this has not been merged? It seems to be lurking and forgotten, so one of you hit the button

**Comment by Rechi** [comment]
@popcornmix please always set the version label and milestone before or right after merging a PR.

**Pull request merged**
