### PR TITLE
FFmpeg: Bump to 3.1.5-Krypton-Beta5-1

### PR DESCRIPTION
**Pull request by fritsch**
Rebase on upstream ffmpeg. Nothing too critical for us: https://github.com/xbmc/FFmpeg/commit/2a5c41e3e4a7e763503af59de903d5649dcc071a

### CODE REVIEW

**Comment by fritsch** [comment]
Updated to include the old ancient I-Frame workaround for AMD gpus.

jenkins build this please

**Comment by afedchin** [comment]
thanks

**Comment by fritsch** [comment]
@FernetMenta fine with you?

**Comment by fritsch** [comment]
Got ack on slack.

**Pull request merged**
