### PR TITLE
[video] replace play stack selection dialog with select dialog

### PR DESCRIPTION
**Pull request by mkortstiege**
Yet another dialog nuke PR. This nukes the play stack selection dialog in favor of the generic select one.

Before:
screenshot from 2015-08-23 20 03 22

After:
screenshot from 2015-08-23 20 04 58

/cc @phil65, @ronie

### CODE REVIEW

**Comment by phil65** [comment]
+1, nice.

**Comment by ronie** [comment]
always hated that fugly dialog.

nuke! nuke! nuke!

**Comment by MartijnKaijser** [comment]
may i also add that the header text is also bit weird

**Comment by mkortstiege** [comment]
Updated. Changed the dialog header to `Play part ...` (same as the context menu action that triggers it).

**Pull request merged**
