### PR TITLE
[Estuary] fix texture paths

### PR DESCRIPTION
**Pull request by ronie**
fixes the 'could not find texture' errors reported by @MilhouseVH

### CODE REVIEW

**Comment by MilhouseVH** [comment]
No more errors - thanks for the quick fix!

**Comment by MilhouseVH** [comment]
Do you know where the following is coming from?
```
20:59:21 104.878525 T:1961242624   ERROR: CGUITextureManager::GetTexturePath: could not find texture 'dialogs/volume/progress/p0.png'
```

**Comment by stefansaraev** [comment]
@MilhouseVH https://github.com/xbmc/xbmc/blob/master/addons/skin.estuary/1080i/DialogVolumeBar.xml#L36

**Comment by MilhouseVH** [comment]
@stefansaraev it's not actually the volume indicator - if I reduce the volume to zero I get the muted image, and there is no error logged. The error being logged is actually from the "Buffering" overlay that appears when watching a video - at the beginning this is at 0% buffered and it obviously tries to load a non-existent 0% image.

**Comment by stefansaraev** [comment]
sure, same thing. :)
https://github.com/xbmc/xbmc/blob/master/addons/skin.estuary/1080i/VideoFullScreen.xml#L32

**Comment by MilhouseVH** [comment]
Snap. :)

I guess a blank p0.png image would be one way to solve it...

**Comment by ronie** [comment]
yup, added.

**Pull request merged**
