### PR TITLE
fixed: broken rfft implementation used in audio visualizer api 

### PR DESCRIPTION
**Pull request by Memphiz**
this replaces it with a working version using kissfft

This is a follow up of: #7039

It puts kissfft in a contrib folder in our source tree. All project files adapted. All platforms are happy - see:

http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-All/740/

(win32 addons failed because of network issues connecting to our mirrors... - unrelated to thi PR)

Tested with nastyfft visualisation from @notspiff repo. The way it is done it can be replaced with a better fft implementation if someone else wants to do it (and i mean do it for all platforms - not only for the one the developer feels comfortable with...).

ATM there are no visualisations in our tree using fft anyway as far as i can see.

### CODE REVIEW

**Comment by AchimTuran** [comment]
hi @Memphiz,
> ATM there are no visualisations in our tree using fft anyway as far as i can see.

How do the viz get his amplitude values? Do they use his own fft?

Maybe we can adept a generic fft implementation from my LXC_fftHandles callback idea.
https://github.com/AchimTuran/LibXConvolver/tree/master/LibXConvolverCore/LXC_fftHandles
At the Moment it supports fftw and KissFFT, but more will follow.

**Comment by Memphiz** [comment]
@AchimTuran well it looks like you are really into it. For viz we basically only need this easy interface https://github.com/Memphiz/xbmc/commit/8492850b3fb1d670941ca9a3fc96d1d9b541aa4e#diff-12be8eb70b39a19a925ec6ce92d5750fR1 (yours looks a bit very generic which might be a bit to much in this case - maybe not - at least i didn't want to dive into it from the first looks).

It would be great if you could do some benchmarks. When your results say fftw is worse the performance boost i could try to make it work on our platforms (adding it to unified depends and make a proper windows package). The benchmark tool would be a really tiny cmdline tool in the best case which i could easily compile for our platforms (for doing on target benchmark tests with ios for example).

Until then - let it be kissfft and let it be as KISS as it is now ;)

**Comment by AchimTuran** [comment]
> The benchmark tool would be a really tiny cmdline tool in the best case which i could easily compile for our platforms

That's exactly what I try to achieve ;) But I know nothing about iOS :) But I use only STL functions and classes. On windows all results will be saved to an *.csv file.

> yours looks a bit very generic which might be a bit to much in this case - maybe not - at least i didn't want to dive into it from the first looks

You're right :) It's very generic. It took some time to design this API. But it's very easy to use:
```
LXC_FFT_HANDLE fftHandle;
LXC_get_fftHandle(&fftHandle, LXC_fftModule_fftwf, LXC_Native, fftSize, timeDomainSize); // creates fft
fftHandle.LXC_fft(&fftHandle.LXC_fftPlan); // runs fft and data is stored in fftHandle.LXC_fftPlan.LXC_specific_fftPlan
```
Here is the definition from [LXC_FFT_HANDLE](https://github.com/AchimTuran/LibXConvolver/blob/master/LibXConvolverCore/LXC_fftHandles/LXC_fftHandles_types.h)

> Until then - let it be kissfft and let it be as KISS as it is now ;)

Yeah just merge it and we can later improve it. Maybe after GSoC.

**Comment by MartijnKaijser** [comment]
@Memphiz is this something we could shove in 15.0 ? It's not widely used anyway right?

**Comment by Memphiz** [comment]
Yep

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
@Memphiz looks like test suite needs some love
http://jenkins.kodi.tv/job/WIN-32/4788/

**Comment by Memphiz** [comment]
For kiss_fft.c and kiss_fftr.c we need to set "compile as cpp" in the Compiler settings - i did this only for the debug and Release Target but it also needs to be done for the testsuite Target. I am on a windows mashine wednesday earliest if noone Else beats me to it

**Pull request merged**
