### PR TITLE
Fix hidden overloaded virtual functions and override warnings

### PR DESCRIPTION
**Pull request by garbear**
Alternative to #12235. The fix for hidden functions comes from @notspiff .

These fixes have been sitting in my repo for about a month, and by this point I'm sure several other people have fixes for these sitting around as well.

### CODE REVIEW

**Comment by FernetMenta** [comment]
drop VP changes from here, those need to go to vpupdates
instead of killing warnings this way without looking at bahvoiur and taking the chance of cleaning up the interface, you should take the opportunity and clean up the interface properly.

**Comment by notspiff** [comment]
Poor little rainer cannot handle a rebase like real men. Lol.

5. jun. 2017 08:09 skrev "Rainer Hochecker" <notifications@github.com>:

**Comment by FernetMenta** [comment]
it is code I maintain and I set the rules for it. submitting code to vpaupdates is not more work for the author.

**Comment by notspiff** [comment]
Yes. And i am free to mock.

5. jun. 2017 09:05 skrev "Rainer Hochecker" <notifications@github.com>:

it is code I maintain and I set the rules for it. submitting code to
vpaupdates is not more work for the author.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/xbmc/xbmc/pull/12238#issuecomment-306118678>, or mute
the thread

**Comment by notspiff** [comment]
Also claiming that having everybody else do shit different due to your
curious ideas is not more work is absolutely hillariously selfish dribble.

5. jun. 2017 09:08 skrev "Arne Morten Kvarving" <cptspiff@gmail.com>:

**Comment by garbear** [comment]
VP changes split off to #12250 (and yes it is more work for me, but I respect fernet's decision to keep VP changes under his control)

Test compiled on Xcode and it looks like there's been another 50-60 override warnings introduced in the last month, but lets get this in and I'll address the other ones later.

The goal of cleaning up the interfaces is orthogonal to killing warnings, so that can come in a later PR.

**Comment by notspiff** [comment]
Gape and you will keep getting your daily dose of rape.

5. jun. 2017 23:35 skrev "Garrett Brown" <notifications@github.com>:

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by garbear** [comment]
Has to rebase after #12239. Jenkins, you know what to do...

**Comment by garbear** [comment]
jenkins build this please

**Pull request merged**
