### PR TITLE
Remove CAnnouncementManager::GetInstance()

### PR DESCRIPTION
**Pull request by garbear**
This removes the static function `CAnnouncementManager::GetInstance()`.

## Motivation and Context
Split out from https://github.com/xbmc/xbmc/pull/14302

## How Has This Been Tested?
Kodi compiles and runs on OSX.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Comment by FernetMenta** [comment]
@garbear don't you remember our discussion? we came to the conclusion that we should use shared pointers
https://github.com/xbmc/xbmc/blob/master/xbmc/ServiceBroker.h#L122

**Comment by garbear** [comment]
OK will update tmrw

**Comment by garbear** [comment]
@FernetMenta updated

**Review by FernetMenta — APPROVED** [review]
Lgtm. Thanks

**Pull request merged**
