### PR TITLE
[linux] allow overriding the userdata dir

### PR DESCRIPTION
**Pull request by wsnipex**
## Description

Allows overriding the userdata location by setting the env var KODI_USERDATA_DIR
The 2nd commit is an only remotely related cosmetic, let me know if I should remove it.

## Motivation and Context

It's useful to be able to specify an (alternative) location for our userdata.
Previously you could only set the HOME var, but .kodi was always appended and overriding HOME can potentially have unexpected side effects with scripts/addons that are launched from within kodi.

## How Has This Been Tested?

started on  ubuntu with and without setting KODI_USERDATA_DIR

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Considering there is already a `userdata` directory, isn't the name `KODI_USERDATA_DIR` a little confusing when this configures the root directory for `.kodi`, and not `userdata`?

**Comment by wsnipex** [comment]
I don't disagree. But KODI_HOME is already used for application install data. (which is also non-obvious)
Any suggestions for a less ambiguous name?

**Comment by MilhouseVH** [comment]
`KODI_DATA`? `KODI_DATA_DIR`? Probably just want to avoid using `USERDATA`.

**Comment by a1rwulf** [comment]
My vote for `KODI_DATA` given that we have `KODI_HOME` and source also shows `KODI_TEMP` it's most in line with them imho.

**Comment by wsnipex** [comment]
changed to KODI_DATA

**Comment by wsnipex** [comment]
@Memphiz would you want that for OSX as well?

**Comment by Memphiz** [comment]
I think we have the correct location in OS X land - no need to override it there imo.

**Pull request merged**
