### PR TITLE
Do not scroll list label if <scroll>false</scroll>

### PR DESCRIPTION
**Pull request by Black09**
With the recent change of commit https://github.com/xbmc/xbmc/commit/e4753e8aaae90dc764435c1dec0c08aea533ea18 it wasn't possible anymore to disable scrolling with `<scroll>false</scroll>`. This fixes it.

### CODE REVIEW

**Comment by HitcherUK** [comment]
@ronie I've just noticed that the default (scroll=true) for focused items doesn't work anymore. Isn't the intended behaviour meant to be true for focused items and false for non focused items if they're not defined by the skin?

Thanks.

**Comment by ronie** [comment]
hope you don't mind if i pass that question to @Black09

**Comment by ronie** [comment]
seems to work as expected in Confluence though.
i've tested List view (CommonRootView), label scrolls when focused, doesn't scroll when unfocused.

**Comment by HitcherUK** [comment]
@ronie @Black09 Sorry guys, for some reason I had <scroll>false</scroll> for labels in my defaults.xml.

**Pull request merged**
