### PR TITLE
Cmake mmal

### PR DESCRIPTION
**Pull request by wsnipex**
## Description

Modernize FindMMAL and add a missing library 

## Motivation and Context

addresses some of the issues raised in http://forum.kodi.tv/showthread.php?tid=255893&pid=2477415#pid2477415

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by hudokkow** [comment]
For reference, should (partially) fix http://trac.kodi.tv/ticket/17110

**Comment by wsnipex** [comment]
added a fix for the 2nd parser error reported in that ticket
jenkins build this please

**Comment by popcornmix** [comment]
Tested this PR with cmake cross compile (Ubuntu host and raspberry pi 2 target) and all was fine, so no objections.

**Comment by wsnipex** [comment]
windows build here: http://jenkins.kodi.tv/job/WIN-32/lastSuccessfulBuild/

**Pull request merged**
