### PR TITLE
changed: Improve handling of internet filesystems (http/https) on LANs

### PR DESCRIPTION
**Pull request by arnova**
Alternative for #16069

### CODE REVIEW

**Comment by DaveTBlake** [comment]
Adding a parameter to IsInternetStream does not improve handling of internet filesystems unless you also change the various calls to ` IsInternetStream(true)`, this PR needs to do that too. But it means that the original question of which IsInternetStream calls do you exclude from the IsLAN test and why still remains.

**Comment by arnova** [comment]
@DaveTBlake : The IsInternetStream(true) calls are only used to determine whether we need to perform caching in 3 places, but I guess we don't even need that for LAN, so we would make this PR even simpler. Would you be ok with that?

**Comment by DaveTBlake** [comment]
I didn't intend to sound like I was objecting @arnova I'm happy you have looked at this, I just didn't see how this PR replaced the other one.

If you have checked everywhere that uses IsInternetStream() only wants "true" internet streams and not media across LAN then go for it.

**Comment by arnova** [comment]
@DaveTBlake : Since I couldn't come up with an alternative, this seems the best way until we can come up with something better. Merge as is, ok?

**Comment by arnova** [comment]
ping @DaveTBlake / @notspiff

**Comment by notspiff** [comment]
jenkins build this please

**Comment by notspiff** [comment]
feel free to merge once green.

**Comment by arnova** [comment]
jenkins build this please

**Comment by arnova** [comment]
jenkins build this please

**Comment by arnova** [comment]
jenkins build this please

**Comment by arnova** [comment]
jenkins build this please

**Comment by arnova** [comment]
@notspiff (or someone else): Mind kicking of another jenkins build, somehow it's not working with my account (anymore)?

**Comment by arnova** [comment]
jenkins build this please

**Comment by MilhouseVH** [comment]
FYI I've had a reported issue relating to this PR: https://forum.kodi.tv/showthread.php?pid=2859068#pid2859068

Reverting this PR fixes [the issue](https://forum.kodi.tv/showthread.php?tid=343068&pid=2859236#pid2859236) but I don't know if this is emby specific or not.

**Comment by arnova** [comment]
I'm seeing 

> FYI I've had a reported issue relating to this PR: https://forum.kodi.tv/showthread.php?pid=2859068#pid2859068
> 
> Reverting this PR fixes [the issue](https://forum.kodi.tv/showthread.php?tid=343068&pid=2859236#pid2859236) but I don't know if this is emby specific or not.

I'm seeing all kinds of Python errors/exceptions in the log so one needs to fix those first. Furthermore have no way of reproducing this (no Emby). I'm wondering whether this PR is the actual cause or just some "trigger"

**Comment by MilhouseVH** [comment]
I'll ask him to test with a "cleaner" system and see if he can reproduce before adding Emby, and then with Emby.

**Comment by arnova** [comment]
thanks @MilhouseVH

**Comment by MilhouseVH** [comment]
@arnova the earlier reported issue is definitely being [triggered by Emby](https://forum.kodi.tv/showthread.php?tid=343068&pid=2861402#pid2861402), but as the Emby developers aren't interested in investigating Kodi 19 related issues, that's a bit of a dead end for now.

However, I've had another (similar) issue reported - this time with [pvr.hdhomerun](https://forum.kodi.tv/showthread.php?tid=343068&pid=2862936#pid2862936), which again seems to be due to this PR - testing with and without this PR produces a [not working and working result](https://forum.kodi.tv/showthread.php?tid=343068&pid=2862994#pid2862994) (click link for post, which has logs).

I hope this is information is helpful, let me know if you need more info and feel free to jump in on the linked forum thread and ask away... I've no idea if the add-ons (pvr.hdhomerun, probably Emby) now need tweaking in some way, or if this PR has introduced an unwanted side-effect.

**Comment by dapharsyde** [comment]
I just came across this issue as well, triggered by Emby.  In kodi.log, there was 1GB of entries like this:

`2019-06-22 23:44:25.561 T:140517633509120 WARNING: ReadEdl - Error adding cut from line 9812 in EDL file: http://192.168.1.5:8096/emby/Videos/3169329/stream.edl?static=true&MediaSourceId=55a4eaa846eb78549b26e8057f327bf7&api_key=67843ce05fea4138b65b3ba096ea7c91
2019-06-22 23:44:25.561 T:140517633509120   ERROR: AddCut - Times are around the wrong way or the same! [00:00:05.000 - 00:00:05.000], 0
2019-06-22 23:44:25.561 T:140517633509120 WARNING: ReadEdl - Error adding cut from line 9813 in EDL file: http://192.168.1.5:8096/emby/Videos/3169329/stream.edl?static=true&MediaSourceId=55a4eaa846eb78549b26e8057f327bf7&api_key=67843ce05fea4138b65b3ba096ea7c91
2019-06-22 23:44:25.561 T:140517633509120 WARNING: ReadEdl - Error on line 9814 in EDL file: http://192.168.1.5:8096/emby/Videos/3169329/stream.edl?static=true&MediaSourceId=55a4eaa846eb78549b26e8057f327bf7&api_key=67843ce05fea4138b65b3ba096ea7c91
2019-06-22 23:44:25.561 T:140517633509120   ERROR: AddCut - Times are around the wrong way or the same! [00:00:00.000 - 00:00:00.000], 0
2019-06-22 23:44:25.561 T:140517633509120 WARNING: ReadEdl - Error adding cut from line 9815 in EDL file: http://192.168.1.5:8096/emby/Videos/3169329/stream.edl?static=true&MediaSourceId=55a4eaa846eb78549b26e8057f327bf7&api_key=67843ce05fea4138b65b3ba096ea7c91`

Prior to this change, I do not think the EDL was being requested when playing Emby videos.  I suspect the Emby plugin is not returning valid EDL information, which results in all of these errors being written to the kodi.log file - upwards of 1GB for a 20min video.

**Comment by arnova** [comment]
I have an idea what the problem could be. Will have a closer look when I'm back from vacation in a week or so.

**Comment by arnova** [comment]
@MilhouseVH : I think we should also revert this one for now. This requires a more fine grained solution

**Pull request merged**
