### PR TITLE
[network] Fix CZeroconfBrowserAvahi::doRemoveServiceType map iterator usage

### PR DESCRIPTION
**Pull request by ksooo**
@paxxi as discussed. btw, std::remove_if is not available for std::map

### CODE REVIEW

**Comment by ksooo** [comment]
Btw, this code seems to get called on every exit of (linux) Kodi! Could be responsible for any kind kind of weird exit behaviour ... Stack corruption, hangs, defaults,  ...

**Comment by MartijnKaijser** [comment]
backport?

**Comment by ksooo** [comment]
@MartijnKaijser yep, should be backported.

**Comment by ksooo** [comment]
@paxxi good to go?

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
@fritsch good to go?

**Comment by fritsch** [comment]
Yes, of course it's fine. An alternative would have been remove_if, but this is fine as is!

**Comment by Paxxi** [comment]
Remove_if only wants an iterator so should work fine with map, it's a global method in algorithm and not a member method. 
As this is merged no need to to do anything about it

**Pull request merged**
