### PR TITLE
refactor builtins

### PR DESCRIPTION
**Pull request by FernetMenta**
credits to @notspiff for this excellent work
- makes CBuiltins a singleton
- refactors the methods into several files

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
@FernetMenta pick Paxxi@ef74a3d14aad5951807f5149e78c796f8757475e for VS projects and a few nitpicks.

:+1: and great work @notspiff even if I had some stupid comments when you first PR:ed it :)

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
@Paxxi I fixed the remaining build errors and squashed them into related commits. good to go?

**Comment by Paxxi** [comment]
@FernetMenta go ahead and merge

**Comment by anaconda** [comment]
Executing `./kodi-send.py -a RunScript(/Users/anaconda/x.py)'` I'm now getting:
`2015-09-14 19:57:17.998 kodi.bin[28112:2498559] Debug Print: Keymapping error: no such action 'runscript' defined`
but it's there:
https://github.com/xbmc/xbmc/commit/aad7483948e9902e2dce65a43489ef303f5ab899#diff-4311d3b58263abcf3ced3c4dcc66e224R303
master on OS X and Milhouse build #0913.

**Comment by FernetMenta** [comment]
@anaconda are you saying this fails only on OSX? I have no clue what Milhouse build 913 is

**Comment by anaconda** [comment]
@FernetMenta OpenELEC master builds for the Pi. So OS X and Pi.

**Comment by Paxxi** [comment]
@FernetMenta I can look into this, you go do important work instead :)

**Comment by FernetMenta** [comment]
you mean I should prepare my client workshop for tomorrow? :)

**Comment by Paxxi** [comment]
nah, rewrite dvdplayer :)

**Comment by lolorc** [comment]
Looks like LIRC.Start, LIRC.Stop and LIRC.Send got forgotten, those are now unknown actions.
"kodi-send --action=LIRC.Stop" to reproduce => "ERROR: Keymapping error: no such action 'lirc.stop' defined"

**Comment by lolorc** [comment]
@FernetMenta @notspiff I know this is a merged PR, any comment on this regression tho ?

**Comment by notspiff** [comment]
Sorry fell my list. Will investigate asap, likely tmrw.
1. mai 2016 11:59 skrev "Laurent" <notifications@github.com>:

**Comment by lolorc** [comment]
i'm circumventing by using a python script that I run from kodi-send.
funnily enough the Lirc builtin actions work from python; xbmc.executebuiltin("LIRC.Stop", True) for instance.

**Comment by notspiff** [comment]
https://github.com/xbmc/xbmc/pull/9751

**Pull request merged**
