### PR TITLE
AESinkOSS: Fix compilation after STREAM_TYPE transition

### PR DESCRIPTION
**Pull request by fritsch**
This completes the transition from the AE_FMT_Passthrough formats to StreamInfo.

### CODE REVIEW

**Comment by fritsch** [comment]
@Fneufneu Are you the maintainer of this Sink? Does it now work?

**Comment by wsnipex** [comment]
does the alsa sink really need oss? https://github.com/fritsch/xbmc/blob/637cd21dcb472ec72de43221edf8ca43b1ca384d/xbmc/cores/AudioEngine/CMakeLists.txt#L63-L67

**Comment by fritsch** [comment]
Yes. There is a fallback. In theory ...

Am 10.10.2016 1:33 nachm. schrieb "Wolfgang Schupp" <
notifications@github.com>:

**Comment by fritsch** [comment]
@Fneufneu yet another ping. Anyone else that builds on free bsd that can verify if it's working?

**Comment by AlwinEsch** [comment]
@Fneufneu how is the current state of the test of them?

**Comment by AlwinEsch** [comment]
jenkins build this please

OK to merge? Want to have the compilation fault fixed.

**Comment by FernetMenta** [comment]
removing it from the build is better than keeping something broken. fixing compile errors is just pretending it is working but it does not. we had windows sinks broken because of this.

**Comment by Fneufneu** [comment]
i have the same patch in my personnal branch since july and it worked at the time.
not sure now because i have some fix to do to able to build kodi again but we can merge this PR safely.

**Comment by fritsch** [comment]
If that fixes your issues, please merge. Else close and superseed this PR
:-)

Am 21.11.2016 10:44 vorm. schrieb "Fneufneu" <notifications@github.com>:

**Comment by Fneufneu** [comment]
i don't have write access anymore so i can't merge this PR :/
@fritsch

**Pull request merged**
