### PR TITLE
[addons] [lang] Link to GitHub issues instead of Trac

### PR DESCRIPTION
**Pull request by VelocityRa**
## Description

Updates the `Report-Msgid-Bugs-To` property in addon language files to point to GitHub Issues instead of Trac.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [x] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Comment by VelocityRa** [comment]
Oh, like this?

**Comment by MartijnKaijser** [comment]
Estuary/Estouchy English can also be done.

**Comment by VelocityRa** [comment]
Ok, done.

**Comment by MartijnKaijser** [comment]
If you feel like it trac is probably also referenced here https://github.com/xbmc/translations  which we used for translation pushing.

**Comment by VelocityRa** [comment]
Sure, I'll do it in a few hours.

**Pull request merged**
