### PR TITLE
[Subtitles][ASS] Make ASS subtitles belonging  to the same ass track …

### LINKED ISSUE #18298: Subtitle with overlapping timestamp show/disappear incorrectly
### Describe the bug
Subtitle with overlapping timestamp show/disappear incorrectly.

e.g. The following subtitle has a line shown on screen at upper right between 1s to 9s. In addition, it has another subtitle shown at normal position every 2 seconds between 0 to 10s. When Kodi plays it, the subtitle on the upper right will disappear between 6s to 8s while it should be on screen all the time. This has been tested on Kodi 18.8 Windows, macOS and CoreELEC.

```
[Script Info]
Title: [Test]
Original Script: Tester
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1280
PlayResY: 720
YCbCr Matrix: TV.709
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Calibri,50,&H00FFFFFF,&HF0FFFFFF,&H007B66D0,&H808060E3,-1,0,0,0,100,100,0,0,1,2,1.5,2,10,10,13,1
Style: TOP,Candara,40,&H00FFFFFF,&HF0FFFFFF,&H00169CE1,&HF0FFFFFF,-1,0,0,0,100,100,0,0,1,1.5,0,9,10,12,8,128

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:00:09.00,TOP,,0,0,0,,{\be3\blur3\fad(200,200)}Should be on screen from 1s to 9s
Dialogue: 0,0:00:00.00,0:00:02.00,Default,,0,0,0,,{\be3}Should show/hide every 2s
Dialogue: 0,0:00:04.00,0:00:06.00,Default,,0,0,0,,{\be3}Should show/hide every 2s
Dialogue: 0,0:00:08.00,0:00:10.00,Default,,0,0,0,,{\be3}Should show/hide every 2s
```

## Expected Behavior

The subtitle on the upper right should show between 1s to 9s without disappearing.

## Actual Behavior

The subtitle on the upper right will disappear between 6s to 8s

## Possible Fix

I was suspecting this is caused by outdated [libass](https://github.com/libass/libass) library as [mpv](https://github.com/mpv-player/mpv) shows the subtitle correctly (which uses same libass library to render ass subtitle as Kodi but from master branch). I tried to compile Kodi with libass from master branch but the result is the same. I cannot guarantee I compiled Kodi with correct libass library correctly though.

### To Reproduce

1. Save the above subtitle to a file named `test.ass`.
2. Play any video longer than 10s with the test subtitle file.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ehiyudeqiw.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

Kodi test video at 7s, subtitle on top is not showing:
kodi

mpv test video at 7s, subtitle on top is showing:
mpv

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10, macOS Catalina, CoreELEC
 - Kodi version: 18.8

### PR DESCRIPTION
**Pull request by enen92**
…sequential

## Description
The subtitle logic is far from easy to follow. At the moment, whenever an overlay is added to an overlay container, the stop PTS of the previous subtitle might be modified if it has a stop time higher than the new overlay start pts.
At first I didn't understand why this logic exists but after a while I got to the conclusion that it exists because of ASS subtitles. Libass generates all images (a new texture) that belong to a given PTS when called with a start and stop PTS. If that logic is removed, and if 2 subtitles entries exist at the same time, we are effectively calling libass to generate images for those 2 time frames. If the 2 time-frames overlap, we might end up with duplicated subtitles. This logic exists to ensure that the subtitle collection is sequential, and that only an "overlay" exists at each moment in time.

Apart from not easy to follow, this also has a bug with overlapping subs. If a subtitle entry exists that starts after the previous one and stops before the previous one, we will set the previous subtitle stop pts to the new stop pts - leading to a possible case where a timeframe exists with no subtitle at all. See the following example:

```
Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,{\be3}Should show/hide every 2s
Dialogue: 0,0:00:01.00,0:00:09.00,TOP,,0,0,0,,{\be3\blur3\fad(200,200)}Should be on screen from 1s to 9s
Dialogue: 0,0:00:04.00,0:00:06.00,Default,,0,0,0,,{\be3}Should show/hide every 2s

```

After passing through the old logic, this becomes:

```
Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,{\be3}Should show/hide every 2s
Dialogue: 0,0:00:01.00,0:00:06.00,TOP,,0,0,0,,{\be3\blur3\fad(200,200)}Should be on screen from 1s to 9s
Dialogue: 0,0:00:04.00,0:00:06.00,Default,,0,0,0,,{\be3}Should show/hide every 2s
```

Which makes the second subtitle not to render until the final 9s.

To solve this issue I moved the logic to a new method in DVDLineCollection (MakeSequential), fixed the said edge case by removing the overlapping sub, improved the docs and made the call only where we need it - in the libass parser.

## Motivation and Context
Fixes https://github.com/xbmc/xbmc/issues/18298

## How Has This Been Tested?
With the provided sample in the issue report. Tested other overlapping subs (srt), with overlapping start times, overlapping subs and didn't spot any different behaviour. I didn't test other subtitle formats like PGS.

@Doraemoe can you please do a comprehensive test with your media to see if any issue pops up? 

Any help testing this extensively is also appreciated!

## Screenshots (if appropriate):

**Master:**
MASTER

**PR:**
PR

Note the top overlay showing as supposed.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by enen92** [comment]
This needs to take into account the replace property like the old logic did.

This also needs to be tested with muxed ass subs as the codec might also contain the same bug.

**Comment by enen92** [comment]
The removal of the logic in `CDVDOverlayContainer::Add` introduced a regression in the ASSCodec for muxed ass subtitles. The old implementation relied on it to ensure the sequential behaviour. 
Added a second commit to fix the behaviour of the codec after the removal of that block of code.
This PR is then ready for review.

**Comment by Doraemoe** [comment]
Thank you @enen92, I have tested this branch on many of my ass subtitles, they all work correctly now 🙌. However, I am now seeing pgs subtitle not disappearing correctly, here are the screenshots:

current version (correct):
correct

this branch (incorrect):
error

I have extract the subtitle track from the file and uploaded it here: https://d.pr/f/FZAzuR 
The example subtitles start around 1:25:15. I do not know if there is an easy way to use this file, I have to use `mkvmerge` to merge this track to a mkv file to use it.

**Comment by enen92** [comment]
Thanks. I'll take a look, maybe I can muxed it into the video using mkvtoolnix.

**Comment by enen92** [comment]
Ok, this is not as easy as I initially suppose. 
If subtitles are muxed within the container, the codec only has access to the subtitle that is being added the last one that was already added. There's no global view over the global container, which means the old logic makes sense and has to stay. I'll come up with a much more localized fix that shouldn't introduce any regression (TM).

**Pull request closed without merging**
