### PR TITLE
Krypton: add replaygain to dsf files

### PR DESCRIPTION
**Pull request by yoyoto**
## Description
Add parsing of replaygain info from dsf file when reading those files.

## Motivation and Context

Up to now replaygain is never applied when you read a dsf file. With this patch replaygain is parsed and correctly applied.

## How Has This Been Tested?

Tested with my own dsf files, checking the logs to verify the correct replaygain was applied on my files when reading them.

## Types of change

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@yoyoto please make sure this is first PRed to our master branch before sending it to our Krypton branch.

Ping @FernetMenta @DaveTBlake

**Comment by akva2** [comment]
s/\t/  /g

**Comment by DaveTBlake** [comment]
@MartijnKaijser are we still adding new features/imporvemnt to Krypton, I thought that dev was frozen now release is done? Missing functionality is not a bug, otherwise I have a long list of missing things we could add to Krypton. IMO this PR should be raised against master period, no backport.

Sorry @yoyoto, but there are windows for these things, and in the beginning contributing you can often miss the boat.

Also a bit unhappy that this makes the TagLib tag loader dependant on the FFmpeg tag loader, in my mind the tag factoiries should be kept separate and clean. If tags from dsf and mka files are handled using the FFmpeg tag factory, then that is where the replay gain should be done too. 

So can you look at doing it that way for master branch.

**Comment by yoyoto** [comment]
Ok, since this is my first pr I was bound to mess up. I'll try to correct the code as you suggested and pr on master next time. Thanks.

**Comment by DaveTBlake** [comment]
@yoyoto please do, contributions are very welcome. Ask questions if you are unsure, and happy to discuss on the Music Support forum where more people can see it.

**Comment by AchimTuran** [comment]
Oh might also be helpful to read our contribution guide.
https://codedocs.xyz/xbmc/xbmc/code_guidelines.html

**Comment by MartijnKaijser** [comment]
@yoyoto correct Krypton is frozen for new features. We're happy to include in our upcoming v18

**Comment by MartijnKaijser** [comment]
Reminder for @yoyoto to send the patch to master branch :)

**Comment by MartijnKaijser** [comment]
@yoyoto if you want this in Kodi please create a pull request to our master branch.
@DaveTBlake maybe something you can pick up if there's no response?

**Pull request closed without merging**
