### PR TITLE
spelling: compiler defines

### PR DESCRIPTION
**Pull request by jsoref**
## Description

Fix spelling for compiler defines

## How Has This Been Tested?
- [x] Travis
- [x] AppVeyor

## Types of change
- [x] Spelling

## Checklist:
- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document

### CODE REVIEW

**Comment by jsoref** [comment]
Split from #11346 ; @AlwinEsch: if you want, I can adjust whitespace...

**Review by Jalle19 — COMMENTED** [review]
Have you checked all the build scripts etc. in case any of these are used there?

**Comment by notspiff** [comment]
none of these are exported from the compile units (apart from the trivial header guard and string change), so it shouldn't be able to break any build scripts.

**Comment by Jalle19** [comment]
jenkins build this please

**Review by Paxxi — APPROVED** [review]

**Comment by Paxxi** [comment]
jenkins build and merge this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
