### PR TITLE
[gui] refactor call to UpdateButtons out of CGUIMediaWindow::OnFilterItems

### PR DESCRIPTION
**Pull request by xhaggi**
Follow-up for #8678 

@Razzeee and @phil65 mind taking a look.

### CODE REVIEW

**Comment by phil65** [comment]
Thx! :)

**Comment by Uukrull** [comment]
I just tested it but it has the same problem with the empty Live TV screen. [Debug log](http://xbmclogs.com/p4yhyuvbm)

**Comment by xhaggi** [comment]
This will revert the changes done in #8678 so i guess there is something wrong with your setup.

**Comment by xhaggi** [comment]
I've give it a try with confluence and get the same empty list at the first access. Not sure this is caused by the changes to `UpdateButtons()`, will do some further testing.

**Comment by xhaggi** [comment]
@Uukrull the issue you mentioned is fixed by #8718

**Comment by Razzeee** [comment]
I really don't like that it looks like each time
```
OnFilterItems(XXXXX);
```
get called it needs to be followed up with UpdateButtons(); and you have to know that you have to do it.
Not sure how to solve the overwriting, but this might lead to other problems down the line. :/

**Comment by xhaggi** [comment]
I've done this to overcome the issue mentioned by @Uukrull, but later found the root cause was skin related. However I don't like the way we implicit call `UpdateButtons()` in `OnFilterItems()` because we normally call it after some method call where it is necessary/required e.g. 
```
UpdateButtons();
Refresh(true);
```
or
```
OnEditChanged(iControl, m_name);
UpdateButtons();
```

Please take a look at https://github.com/xbmc/xbmc/search?utf8=%E2%9C%93&q=UpdateButtons%28%29&type=Code

IMO it's more clear if we do the same for `OnFilterItems()`

**Comment by phil65** [comment]
I agree with @xhaggi, especially considering that UpdateButtons() also updates the visibility of the viewtypes and changes them accordingly. Should get uncluttered.

**Comment by Razzeee** [comment]
I also think it's worse the other way around. So I would like to get this merged, but I'm wondering if we should add a comment/documentation to ```OnFilterItems()``` that it needs a call to UpdateButtons() if that is the case/we haven't documented that.

**Comment by Razzeee** [comment]
jenkins build this please

**Comment by hudokkow** [comment]
Build is fine. pvr.hts keeps failing on Win32

**Comment by MilhouseVH** [comment]
Not sure where to report this... here, #8678 or #8718 but the "empty channels" problem is still an issue with latest master (92042ae1): [forum post](http://forum.kodi.tv/showthread.php?tid=250817&pid=2205820#pid2205820).

**Comment by xhaggi** [comment]
@MilhouseVH did you verified it by yourself? You could use the pvr demo addon too.

**Comment by Mike-KL** [comment]
@xhaggi regarding Milhouse comments and link to forum post/thread above,  I have just checked with #0106 Milhouse openelec build on my rpi2 and can confirm "empty channels" are present on first access of "PVR TVHeadend HTSP Client v2.2.11"

I then disabled TVHeadened HTSP Client, enabled the pvr demo client and same issue occurs on 1st access of either client. (occured yet again with TvHeadend HTSP client on 1st access occurance when re-enabling etc)

**Comment by xhaggi** [comment]
could you pastebin the MyPVRChannels.xml of the confluence skin?

**Comment by Mike-KL** [comment]
Not very familar with Skins, don't appear to have a MyPVRChannels.xml in the confluence skin anywhere?  Only file currently held in Userdata\addon_data\skin.confluence is a settings.xml
(Note Did play around with installing and enabling skin.eminence.2 and associated scripts in past but its currently disabled and I am using standard confluence if this is relevant at all)

**Comment by popcornmix** [comment]
@Mike-KL on OE it will be /usr/share/kodi/addons/skin.confluence/720p/MyPVRChannels.xml

**Comment by MilhouseVH** [comment]
http://pastebin.com/0uXn93VJ from RPi2 build #0105b.

**Comment by MilhouseVH** [comment]
That file doesn't look right...

**Comment by Mike-KL** [comment]
@popcornmix thank you for pointing me in right direction
@xhaggi requested MyPVRChannels.xml from skin.confluence http://pastebin.com/C2NVYy6N

**Comment by MilhouseVH** [comment]
I think this is a build error on my part, it looks like the build may have been using an out of date skin package for the last few builds, which is a bit embarrassing. I'll test with pvrdemo and a fixed build and confirm the situation.

**Comment by MilhouseVH** [comment]
Fixed the build, now using the updated skin and can no longer reproduce the problem with PVRDemo - apologies for the cockup!

**Pull request merged**
