### PR TITLE
[guilib] CGUIWindowFileManager cleanup

### PR DESCRIPTION
**Pull request by phil65**
cleaned up defines and actually use them.
@Razzeee

### CODE REVIEW

**Comment by Razzeee** [comment]
A bunch of ids changed, doesn't this break behavior? Are those only used internally?

**Comment by phil65** [comment]
Only used internally. Skinners never reference the buttons of a contextmenu directly.

**Comment by Razzeee** [comment]
Nvm seems sane. 

jenkins build this please

**Comment by phil65** [comment]
build failure unrelated.

**Pull request merged**
