### PR TITLE
[win32] Update rendering system to DirectX11.

### PR DESCRIPTION
**Pull request by afedchin**
This is work to porting Kodi rendering system to DirectX 11. Here is testing thread on the forum http://forum.kodi.tv/showthread.php?tid=218274

New features (compared to dx9 version):
- Caching font vertices on GPU side (see #4143)
- Hardwarebased stereoscopic 3D (requires Win8).
- Support interleaved stereoscopic mode.
- New checkerboard stereoscopic mode.
- No longer need to install the DX to the target platform, but for properly work video API this requires updates (see below)

~~This also require changes in ffmpeg use D3D11 Video API to decoding, see afedchin/ffmpeg@d335d996a.~~

To properly work video API (dxva rendering and decoding) on Windows Vista/7 this requires:
- Windows Vista: SP2 with [KB971512](https://www.microsoft.com/en-us/download/details.aspx?id=3274)
- Windows 7: [Platform Update for Windows 7](https://www.microsoft.com/en-us/download/details.aspx?id=36805)

need to find a way to trigger user to get that installed.

~~PS. The first few commits not fully reflect their essence, everything was done chaotically without a clear plan of action. Some things are reworked multiple times, as an example GUI sahders. Currently I don't see how can I change (split or squash) commits to make them more clear.~~

PS. This breaks bisect windows builds.

### CODE REVIEW

**Comment by Paxxi** [comment]
I also work chaotically so once finished I tend to make a new branch and cherry pick related changes and squish them to make it cleaner. It's quite a lot of work though on something big like this.

Just wanna say awesome work!

**Comment by Memphiz** [comment]
You could for example git reset all your commits (so you have them as pending changes) and then pick some added files with a nice commit message and then commit maybe removed files together and at the end when only modified files are left - git commit -p relevant chunks of them (if possible). Just an idea on how to do it. Looks like you should try to reduce the number of commits before it can be reviewed properly.

**Comment by afedchin** [comment]
Decrease amount of commits and made them more relevant to their description.

@Paxxi @Memphiz I was already thinking about both ways. But all of them make me cry.

**Comment by afedchin** [comment]
Here is branch rewritten which is easier to review https://github.com/xbmc/xbmc/compare/master...afedchin:dx11_new, but it can break bisect. @Memphiz  @Paxxi What do you think?

**Comment by Paxxi** [comment]
Looks a lot better, I'm not a user of bisect so personally I don't care but some might disagree about it I guess.
Will try to get time during the weekend to go through it all 😊

**Comment by afedchin** [comment]
I've reviewed this and found what this broke existing screensavers/visualizations on other platforms. I've also found a few bugs. So I suggest to move to the new branch (or update this) because it contains all new fixes/improvements/cosmetics. This branch has become too difficult for support and fix. Yes I know what dx11_new break bisect, but only for windows builds.

**Comment by FernetMenta** [comment]
nice work! regarding

> This also require changes in ffmpeg use D3D11 Video API to decoding, see afedchin/FFmpeg@d335d99.

could you ask at ffmpeg whether they prefer a configure switch or something else?

**Comment by afedchin** [comment]
I've sent the question. But I think this patch will not be accepted because it is not full. It is enough to work decoders but not enough to compile full ffmpeg.

**Comment by afedchin** [comment]
@FernetMenta I've reworked dxva related code as Hendrik suggested. No more need changes to ffmpeg.

**Comment by FernetMenta** [comment]
>  No more need changes to ffmpeg.

great!

**Comment by Paxxi** [comment]
### It's time we get started on reviewing this properly so let's start with some ground rules

1. There are style issues such as braces, indent, concistency and some spelling, We don't talk about that now, it can be handled in a later stage.
2. I don't think we should spend any time on Effects11 and wether it's in the correct place, it doesn't matter at this point
3. We don't need to discuss dxerr, same as Effects11, see http://blogs.msdn.com/b/chuckw/archive/2012/04/24/where-s-dxerr-lib.aspx for explanation of why it's needed.

### My initial thoughts

I've spent the day going through all kodi code, haven't touched the visualizations yet and I find it very solid. The design seems sound and well encapsulated, it touches very little or no shared code and the separations are clean. I will spend some more time over the week going back over it as it's fairly big.

@FernetMenta I hope you have some time and or energy to review as well as you probably know the architecture of this code the best

**Comment by afedchin** [comment]
@Paxxi I've added most of your comments to the commits.

**Comment by afedchin** [comment]
As for WinRender.cpp#1033. I agree with you. But I suggest to fix it in separate PR before Isengard release.

**Comment by MartijnKaijser** [comment]
@FernetMenta @fritsch i would appreciate if you could comment if the architectural changes are within reason (if there are at all). This would give @afedchin time to do any alterations by the time we can merge this for 16.0

**Comment by FernetMenta** [comment]
Regarding player and videorenderer there are no significant architectural changes, apart from DX9->DX11 transition of course. nice solution for keeping compatibility with ffmpeg. 
should go in as soon window is open again

**Comment by afedchin** [comment]
damn, after rebase fritsch's comment was lost. it can be found here https://github.com/afedchin/xbmc/commit/5e8a30d4b109e068f1918d9613d87d0dec8ec604#commitcomment-11474698

**Comment by afedchin** [comment]
so time to final review I think.
@FernetMenta @Paxxi objection? suggestions?

**Comment by FernetMenta** [comment]
if nothing substantial has changed here, I am still ok woth this

**Comment by MartijnKaijser** [comment]
Needs a rebase

**Comment by afedchin** [comment]
rebased
jenkins build this please

**Comment by Paxxi** [comment]
You have my ok, merge when possible to avoid having to rebase this more than necessary

**Comment by afedchin** [comment]
just to be sure jenkins build this please again

**Pull request merged**
