### PR TITLE
[texture/iimage] Pass the texture's width to iimage's Decode() method.

### PR DESCRIPTION
**Pull request by ace20022**
I accidentally picked the wrong method ;)

### CODE REVIEW

**Comment by ace20022** [comment]
@fritsch it's unbelievable how many dimensions are available in this class...

jenkins build this please

**Comment by mkortstiege** [comment]
Build error is unrelated. @fritsch, good to go?

**Comment by fritsch** [comment]
Yes @ace20022 knows what he is doing :-)

**Comment by mkortstiege** [comment]
Ok ;)

**Pull request merged**
