### PR TITLE
Don't terminate player on sleep

### PR DESCRIPTION
**Pull request by Falcosc**
## Description
If possible pause the player. Only if pause is not possible or would trigger timeshift, we use the old way to terminate the player.
It does pause the player onsleep. And it does not terminate a already paused player.

## Motivation and Context
https://forum.kodi.tv/showthread.php?tid=324710
If you want to resume your movie, you would like to keep the player instead of terminating it on sleep.
And you can't change this behaivor with an addon, because you don't know the last player state after or on sleep. It's not possible to differentiate between user did close the player or kodi did close the player on sleep. And the addon solution "restart terminated player" was odd anyway if you use sleep.

## How Has This Been Tested?
It got testet on Windows 10 64bit with an Intel Apollo Lake and the intel graphic driver 15.60.

If you trigger onsleep from outside with power button, it does still fail to enter sleep sometimes, like it does with the old code. My change does not fix this bug. I did try to fix this as well during implementiung my improvement but even if the pause or stop action is the first action onsleep it does still don't work some times.

## Types of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [?] All new and existing tests passed
I did not find a documentation about kodi tests on local environments.

### CODE REVIEW

**Comment by FernetMenta** [comment]
This won't work with most content streamed over network. The socket connections will fail on sleep and won't recover on wake. Even if the code were ready to recover, the connections may have become invalid/expired.

Kodi has a mechanism to resume from last position. You should try to use this.

**Comment by Falcosc** [comment]
The main problem is that we don't know if the player was stoped by user or stoped by kodi. You can't just resume everything. If the user did close the player we should not resume.

And a resume of an terminated player is not very easy because of playlist and used media information.
Should be a new player state a better solution?

**Comment by FernetMenta** [comment]
Every socket connection will fail on sleep if not shut down gracefully. You donˋt know in advance after what time the server will close the connection too. In order to make this work, you have to start from beginning.

You named the root cause and it is alway much better to fix the root cause than to try workarounds. Why donˋt you store the state before going to sleep and restore the state on wake?

**Comment by Falcosc** [comment]
could you suggest where to store the last state?
Store it into db, store it into application state, into applicationplayer state or into power management?
Should we implement a new player sleep state instead of termination+reconstration?

Should we terminate the player for media which does not have any problems with sleep?

**Comment by FernetMenta** [comment]
> If I just think about how fast a kodi device resume is expected from an user based on his mobile devices expirience, I don't even like the player termination.

you can't compare sleep mode to this. mobile devices don't go into sleep mode.

> Should we terminate the player for media which does not have any problems with sleep?

it is almost impossible to detect this. Kodi supports vfs addons, inputsteam addons, etc. 

It does not matter anyway. Starting a local file from beginning and seek is fast enough.

> could you suggest where to store the last state?

keep it simple for the frst iteration. kodi already supports resume from last position. you just need to automate this without showing the dialog.

**Comment by Falcosc** [comment]
I does still have many solutions in mind and don't want to implement all of them just to know that the frist 3 ones where not the way to go.

all of my ideas base on:
- store the last state (none, play, pause)
- resume to the last state
- store and resume playlist information
(pause is 2nd step, playlist is 3rd step)

**Ways to handle sleep and wake**
A) 
clear everything to nothing
query database to get the last media resume point
resume it and apply the last state  (optional support pause)
(optional support) store and resume playlist information

B)
Terminate only player but keep media information (I guess media is hold in applcation state)
resume media to stored player state
keep playlist or terminate and recreate it?

c)
terminate  only streams and files (without clearing playlist?)
resume to the stored state

d) I'm sure that there are many more possiblities

**Ways to store last state**

All solutions need to store the last used player state to resume (was play) or to do nothing (was none)
Where should something like this be holded?
1) Applicationplayer member would be my first guess
But maybe 2) Application member 3) Power managment member 4) as new structure into the database

**Which does match best**

Now lets multiply the ways to store with the ways to handle terminate and resume. :D
Who could vote for a concept or decide which should be used? Because I don't can't decide it and don't want to create pull requests for all ways to implement this ;)

Of corse I would only implement the very first step (resume play after standby only) but we should keep the big picture in mind and select a proper concept which does support different player resume states and playlist to keep the need of refactoring low. Unfortunately I don't know anything about playlists which makes it even harder for me to look ahead.

**Comment by da-anda** [comment]
I think the first step would be to no only store the resume point of media in the DB, but also it's playback settings (which audio/video track, which subtitle etc) which are lost atm. After this is done, try to tackle the next step by storing the resume point information in all desired cases (playback stop, shutdown, suspend, standby, TV being turned off/CEC event...). And once this is in, add a setting for auto-resume with options like "always", "on wakeup from standby", and/or whatever you see fit

**Comment by Falcosc** [comment]
Thanks for the tracks and subtitle input.

We should seperate the topics into 2 things:

1st: resume information per media
2nd: resume information per application

media based resume information are:
- resume point
- track selection
- subtitle selection

application based resume information are:
- last used player state
- last window (don't needed because it did not get resettet?)

I don't want not talk about media based resume information because I want to use existing resume and store functions.
For application based resume we don't have anything expect for manuall selection in an ui where the resume point gets not get displayed after wakeup (properly an existing bug of missing window refresh) and it's more common to resume to your paused standard movie with default region settions instead to resume to a special multitrack video.

What are playlists? application based or not? But could be decided on the last step anyway.
But it creates such a complicated big picture. Does we realy need to store track and playlist selection for long time? Wouldn't it just be enoght to keep it in memory instead of clearing the memory?

Store into db vs store in memomry vs don't even clear this information at all.
These 3 ways are basically my A), B) and C) from my last reply.

I don't want to create a better power off support because when you close something you request for a fresh start.
But if you pause a video you want to resume it an hour later.

Is there a possible iteration and more importand a direction (implementation concept) which got approved by the team?

**I would just go with "store last user requested player state"**

Action: playaer state
- Close: remove state
- hibernate: store state
- standby: store state
- CEC: store state
And we reuse store media info and resume media info function calls to support all media based resume improvements. 

And for this single change I did already need an aprovement of the team about which direction should be selected

A1 A2 A3 A4
B1 B2 B3 B4
C1 C2 C3 C4
or any other ways to handle state save and termination scope.

**Comment by da-anda** [comment]
I think we should move the discussion to the forum - would you be OK with this? Because I fear you just opened pandoras box ;)
FWIW I basically had the very same idea a couple months ago and had been discussing a little with another team member about it. In my case the reason had been PVR, where there is currently no way to resume playback after playback got automatically stopped by a CEC event when the TV is turned off. We basically came to the conclusion that this feature ideally should apply to any media playback etc, which is basically what you're up to now, but none had the time back then to work on it (and I also lack C++ skills for that matter, which makes it even harder, but ofc not impossible for me). I also think that auto-resume could/should be an option for a cold start, which could basically replace startup playlists. Many of this is ofc unrelated to your current request, but might be worth considering for the big picture. Thus I think a discussion on the forum might be good. But if you would rather like to just continue with your current demand and ignore the rest, it's also fine with me.

**Comment by Falcosc** [comment]
Yes I did miss something. Streams are not supported by media based resume point storage.
But we have a PVR resume point.

What about a common resumePlayer function in the power management? Currently this function will get ony media resume and PVR resume function calls (don't know where pvr resume is stored, but have it) We use existing save PVR channel and save media resumepoint.

CEC should handled like sleep. I didn't look into it but If CEC is triggering a PC Power off or a Application Close it should be changed anyway to sleep/standby because you don't want to reset the whole OS just because you turn your display on and off.

After CEC is using non breaking power modes where we keep the memory it should be easy.

Then we could use or create an interface for non resetting actions (hibernate, sleep, cec triggered hibernate or sleep)

My main purpose is to seperate between keeping memory and termiating application. I don't like resumes after application termination because that just slow down the boot. But I like to keep what is already loaded.
For the previos discussion. It's ok to terminate stream and connections but I don't like to terminate any more things if you let your computer online. In my opinion we should not do to many special things when OS is trying to store our memory, because this sleep feature is make to retain the memory not to implement whole termination processes on sleep.

For that reason I would like to store the last player state as close as possible to the player to make something like player.sleep and player.wake
Application functions level would be ok for me in the first step if the player would need to much refactoring to support a new state.

What do you think about it?

**Comment by MrMC** [comment]
https://github.com/MrMC/mrmc/commit/1890a749bd21194b89329aa31f28b749a460000b#diff-1b0a8f606067a390b896871ed100a2d0

the important bit is g_application.LastProgressTrackingItem

Does most of what you want to do here. Also implemented in iOS/tvOS where when you are pushed to background, the OS can suspend or terminate the app with little or no warning.

**Comment by Falcosc** [comment]
Thanks for participating. This could be a problem.
Is it ok to create a similar copy this functionality into the os indipendent Kodi code or would this case problems?

**Comment by MrMC** [comment]
No problem, we are gplv2, a fork of xbmc/kodi in fact.

**Comment by hudokkow** [comment]
@MrMC is a former Kodi Team member. Code is free as long as respect authorship. ;)

**Comment by Falcosc** [comment]
Copy wouldn't be useable anyway, but we could at least reause the idea because the fork has the same architecture.

**I would like to define something to exclude  at least some usecases/solution designs to make the selectio more easy:**
_After destroy Applicationcontext: Don't automatically resume to exactly the same player state on boot
After sleep/idle/etc state with keeping applicationcontext: use automatic resume to last used state._

This definition is inspired by mobile devies and the way how OS is handling sleep modes.

**Comment by da-anda** [comment]
I think your current concept is fine. Unfortunately I can't assist much in the architecture part (where to put/store what), as I myself first need to get up to speed with the codebase. Maybe @FernetMenta can give some pointers on where to best store the temporary resume info as I doubt cApplication is the best place for it when thinking about the upcoming support for multiple players in parallel. IMO cApplicationPlayer would be a good place, which you also suggested already. Like extending cApplicationPlayer with "canSuspendPlayback()", "suspendPlayback()", "canResumePlayback()" and "resumePlayback()" methods. Otoh this approach might not work well if we would like to add support for resume support after sudden power loss or alike (we would have to inject the temporary resume point that got stored somewhere into a newly created applicationPlayer instance, which I'm not sure is the best approach to this, but would ofc work)

**Comment by Falcosc** [comment]
I don't want see an autoresume on boot implementation inside of kodi especially not after a crash because it would be to complex to implement resume crash loop detection.
And I even don't like autoresume after clean kodi shutdown because if kodi application context got destroyed the user did this on purpose. If he didn't on purpose: autoresume should not be used as fix for broken applications where code would crash or trigger an emergency shotdown.

For that reason I want to define that this is the wrong way to do if nobody does complain about this definition, we don't need to talk anymore about persistent player states. It's enoght to have media based states persistent.

**Comment by FernetMenta** [comment]
Focus on your use case first, hence keep a copy of the tracking bookmark in power manager. On wake start player with last position.

**Pull request closed without merging**
