### PR TITLE
VideoPlayer: fix aspect ratio of libass subs

### PR DESCRIPTION
**Pull request by FernetMenta**
fixes wrong positioned overlays

### CODE REVIEW

**Comment by taxigps** [comment]
@FernetMenta Please revert this. it's not a fix, it's make a problem. see https://github.com/xbmc/xbmc/issues/14789

**Comment by taxigps** [comment]
storage aspect ratio (SAR) = aspect ratio in frame we set use ass_set_margins
display aspect ratio (DAR) = aspect ratio in the 3d screen we see in fact, it's the full screen, not left/right half screen.

**Comment by FernetMenta** [comment]
reference: https://forum.kodi.tv/showthread.php?tid=333956

**Comment by taxigps** [comment]
ok. can you send me the sample file in that forum thread, I can't access google.com and want to try fix 3d issue without breaking other behavior.

**Comment by MartijnKaijser** [comment]
@taxigps what method works for you?

**Comment by taxigps** [comment]
@FernetMenta @MartijnKaijser Thanks!

**Pull request merged**
