### PR TITLE
added Android badges

### PR DESCRIPTION
**Pull request by PanderMusubi**
## Description
Added badges to Android app stores offering Kodi.

## Motivation and Context
These badges are customary for Android apps and provide quick naigation for users that want to install on Android.

## How Has This Been Tested?
Tested in browser, which is sufficient.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [X] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [X] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by da-anda** [comment]
not sure we want a link to f-droid here since AFAIK we don't maintain it and thus have no idea which AKP is ending up there (could be malicious etc)

**Comment by PanderMusubi** [comment]
Well, the built for F-Droid is usually safer as extra checks are run before the build process and because of these checks certain code gets inspected manually. I have asked for more details to be posted here at https://gitlab.com/fdroid/fdroiddata/issues/1771 so you get a better understanding for the F-Droid build.

**Comment by licaon-kter** [comment]
@da-anda The APK is build from the project source, it's malicious as much as the code here is.

**Comment by peak3d** [comment]
I ersonally don't see any reason why not adding it to F-droid if there is someone maintaining the upload. NDK20 will be in the next 18.5 version IIRC

**Comment by PanderMusubi** [comment]
You can see the active build and upload support in https://gitlab.com/fdroid/fdroiddata/issues?scope=all&utf8=%E2%9C%93&state=all&search=kodi

**Comment by Razzeee** [comment]
@licaon-kter would you be interested in joining our slack server?

**Comment by licaon-kter** [comment]
@Razzeee No, not really. :)
I'm no dev so I can help by testing stuff on a buildserver and give you feedback but not much else.

**Comment by Razzeee** [comment]
The slack is not only for devs. Your the f-droid package maintainer, aren't
you? That's why we would like to have you.

**Comment by licaon-kter** [comment]
@Razzeee I'm a _metadata integrator_ of sorts, yes, maintainer sounds too fancy. :)

Also, I'd rather not use a non-FOSS silo like Slack, imho, we can exchange messages in a Github/Gitlab issue or maybe on XMPP (MUC or 1:1).

**Comment by Razzeee** [comment]
I figured you might say this :)

**Comment by Razzeee** [comment]
what about IRC on freenode?

**Comment by licaon-kter** [comment]
Looks like I need to register my nick with my email and such for Freenode, so no. :)

**Comment by DaVukovic** [comment]
There's no need to register your nick. A registration is only needed if you want to avoid that someone else is using your nick. If you don't care, then you don't need to do that.

**Comment by phunkyfish** [comment]
How should we progress this?

**Comment by Razzeee** [comment]
We want to communicate that the f-droid version is unofficial, so I'm probably going to change the readme to make sure people understand that. (as the f-droid version is quiet out of date)

**Comment by PanderMusubi** [comment]
Four months ago 18.5 was published. The automated building is not working because of the version info in Kodi's code, see https://gitlab.com/fdroid/fdroiddata/-/issues/1771#note_299674568 for the issue

**Comment by Razzeee** [comment]
Why 18.5? The latest on f-droid seems to be 18.3?

**Comment by PanderMusubi** [comment]
Sorry, yes indeed. I know build attempts have been made. Best is to have a look at the Kodi issues at fdroiddata, think you might be able to help out getting automated build going again (more than me).

**Comment by yol** [comment]
@PanderMusubi someone would need to step up to maintain the f-droid build actively. as before, no one in the team is currently interested.

**Pull request merged**
