### PR TITLE
VideoPlayer: set demuxer speed other than pause and normal

### PR DESCRIPTION
**Pull request by FernetMenta**
fixes https://trac.kodi.tv/ticket/18055

### CODE REVIEW

**Comment by Rechi** [comment]
jenkins build this please

**Comment by ksooo** [comment]
Tested with pvr.hts plus tvheadend. Unfortunately, this change leads to (green) picture artifacts while seeking. So, no improvement. Things got even worse than before.

**Comment by FernetMenta** [comment]
> this change leads to (green) picture artifacts while seeking

I doubt. Seek does not change playspeed. Means this code won't get hit on seek.

**Comment by ksooo** [comment]
Oops, I used wrong words. I was actually writing about fast forward / rewind.

**Comment by FernetMenta** [comment]
This PR reinstates behaviour of v17. Current master only sets demuxer speed for normal and pause. If tvh can go faster than normal it does not need setting of demuxer speed and you could ignore the calls in the addon. Other pvr and inputstream addons need this, see trac ticket.

**Comment by ksooo** [comment]
Before this PR, it worked better. Please do not let "suffer" official add-ons in favor to some random unofficial pvr add-on (referring to the trac ticket, where the submit not even reveals details of his add-on) - at least not in beta stage. I guess I will not find the time soon to adjust pvr.hts. Thanks.

**Comment by FernetMenta** [comment]
For the record: this reinstates v17 behaviour. The issue is clearly tvh.
If you block this PR you do this in favour of malfunctioning tvh and against correct behaviour and other addons you may not be aware of.

The comment in this code give a clear and valid reason why this change is required. On the other hand we don't know a valid reason why tvh addon abuses this function.

I leave the decision to you and the team.

**Comment by ksooo** [comment]
Sorry, not looking at the code but on the screen as a user, v17 does not show the artifacts while ff/rew. So, from user's POV this PR introduces a regression for one of our most used pvr add-ons. Not good.

I'm not saying that there is nothing to improve/fix in pvr.hts / tvheadend. I'm only saying that this is not a good timing (we're in beta) for this change and that I'm afraid I dull not have time to adjust pvr.hts and I don't have the skills to fix tvheadend if it turns out to be the root cause.

**Comment by FernetMenta** [comment]
Ignoring speed changes other than pause and normal in tvh addon is adding 2 lines

https://github.com/kodi-pvr/pvr.hts/blob/b244c01513e6671751058316406f68123b812cef/src/tvheadend/HTSPDemuxer.cpp#L199

```
if (speed != 0 && speed != 1000)
return;
```

**Comment by ksooo** [comment]
> Ignoring speed changes other than pause and normal in tvh addon is adding 2 lines

 I have other priorities at the moment. I will put this on my list, but do not make any promises when it will be ready.

**Pull request merged**
