### PR TITLE
[skin.estuary] Rework PVR Info panel (used in Recordings, Timers, Tim…

### PR DESCRIPTION
**Pull request by ksooo**
Another take to rework the PVR info panel...

Concept:

screenshot003

Examples:

screenshot002
screenshot004
screenshot005

@ronie good to go?
@phunkyfish fyi

### CODE REVIEW

**Comment by Jalle19** [comment]
Looks like I'm running out of disk space 😅

**Comment by ksooo** [comment]
> Looks like I'm running out of disk space 

 It wasn't me. ;-)

**Comment by ksooo** [comment]
@ronie I'm not done with this. It's still not what I actually have in mind. Will ping you if I think this is ready for a review.

**Comment by ksooo** [comment]
@ronie I think that's it. I moved the thumb/channel logo to the left and the progress bar from beneath to the right of the thumb/logo. Looks better, imo.

screenshot000
screenshot001
screenshot002

**Comment by ronie** [comment]
as i mentioned on the previous pr (which may not have been clear) the amount of infolabels you are trying to put in this view is too much.

if you take a look at the views estuary uses for episodes (for instance), you'll see it will just show the icon + plot on the side. nothing more, nothing less.

in order to fit somewhat within the general estuary design, the pvr views could really use some simplification.

as suggested earlier, to reduce the number of infolabels that are (potentially) shown,
i would start by removing the ones that are already shown on the left side.
next, remove items like writer / director / cast...

here's a mockup of what i believe is the max amount of info you can display before getting overly crowded:

pvr

**Comment by ksooo** [comment]
@ronie thanks for the feedback. 

I'm with you - my approaches do look all far to crowded. I like your mockup, with one addition: I think we should display title/episode title as well on the right side as it makes more clear what is actually displayed and because it is not always redundant information - for exemple in Timers window, ListItem.Label on the left side is the timer's/timer rule's name which can be any string the user chooses as a name for the timer. Timer name being equal to EPG title feels natural, but is just a "coincidence". Same holds for recordings. Last, in channels window, ListItem.Label is the channel name.

**Comment by phunkyfish** [comment]
The issue I see here is that the dialog will then need to be different depending on which screen it is used on. E.g. channels and timers show the channel name on the left, recordings do not. Timers show the date and time on the left recordings no not etc.

But maybe separate dialogs is the right approach anyway.

**Comment by ksooo** [comment]
I will revert the recent changes we did to the PVRInfoPanel as imo what we currently have is worse than what we had before we recently started fiddling around with adding more and more info to it.

**Pull request closed without merging**
