### PR TITLE
BuildSetup: don't copy the contents of \system in \BUILD_WIN32\applic…

### PR DESCRIPTION
**Pull request by wiromare**
…ation

@Paxxi

### CODE REVIEW

**Comment by Paxxi** [comment]
As far as I can tell from the diff this doesn't change the behaviour in any way but it does clean up the exclude_dll.txt file which is good ofc.

Have you seen any specific issue that this would solve?

**Comment by wiromare** [comment]
in my case, i don't know why, xcopy fails to copy some extra files included in my modified version of kodi

after xcopy ..\..\system\*.dll BUILD_WIN32\application /E /Q /I /Y /EXCLUDE:exclude.txt > NUL

maybe it could be them same for you in future

anyway, even if nsis don't catch them I thought it was wrong to copy those folders in application

**Comment by Paxxi** [comment]
Those folders aren't copied into the application folder in any of our nightly builds so either there's been a regression today or some other modification of yours may be at fault.

**Comment by wiromare** [comment]
because nsis don't catch them 

  ;Start copying files
  SetOutPath "$INSTDIR"
  File "${app_root}\application\*.*"
  SetOutPath "$INSTDIR\addons"
  File /r "${app_root}\application\addons\*.*"
  File /nonfatal /r "${app_root}\addons\peripheral.*"
  File /r "${app_root}\addons\skin.*"
  SetOutPath "$INSTDIR\media"
  File /r "${app_root}\application\media\*.*"
  SetOutPath "$INSTDIR\system"
  File /r "${app_root}\application\system\*.*"
  SetOutPath "$INSTDIR\userdata"
  File /r "${app_root}\application\userdata\*.*"

in your setup if you run buildsetup.bat in BUILD_WIN32\application you should see the system's folders also in application

**Comment by Paxxi** [comment]
ahh ok, I'll try it out later today and see

**Comment by Paxxi** [comment]
yup you were entirely correct, thank you!

**Pull request merged**
