### PR TITLE
[VideoPlayer] Ignore stall conditions on video streams flagged as consisting of still images

### PR DESCRIPTION
**Pull request by djp952**
## Description

This PR attempts to fix (again) Issues [18389](https://github.com/xbmc/xbmc/issues/18389) and [17041](https://github.com/xbmc/xbmc/issues/17041).

My first try to fix this a few months ago (sorry for the delay to revisit) via PR https://github.com/xbmc/xbmc/pull/18446 was inadequate and deemed to cause potential new problems.  I believe that I have found a more elegant yet still low-impact solution to this concern.

This PR does not attempt to resolve related stream startup time concerns as Kodi still requires knowledge of the video stream properties and flags before any playback of audio streams can begin.  Kodi strongly favors video over audio, and this PR will not change that.  Streaming a "MusicChoice" channel via a PVR will still need to wait until the first MPEG-TS video stream PMT packet and the video PES packet are encountered/parsed.

## Motivation and Context

Motivation is to fix these Issues without breaking anything else this time and get PVR channels like "MusicChoice" functional for all PVR addons while still taking into account the feedback received from the original pull request.

Related Issues: [18389](https://github.com/xbmc/xbmc/issues/18389) and [17041](https://github.com/xbmc/xbmc/issues/17041)

What I found was that MusicChoice MEPG-TS streams properly set the AV_DISPOSITION_STILL_IMAGE flag in ffmpeg.  If a video stream with this flag set is detected, ignoring the VideoPlayerVideo stall condition seems appropriate to do and solves the underlying problem.

Analysis of the ffmpeg code indicated that only MPEG-TS streams are eligible to set this flag, so there should be no impact to stream(s) that do not originate from this input format.

That said, I would recommend that at a minimum @FernetMenta review this PR to help ensure that it will not cause any nasty side effects while meeting the defect criteria in the original Issues.

Primarily tested on Windows x64 20H2 (19042), but no new problems were noted on other platforms I was also able to execute the change on. 

## How Has This Been Tested?
Proposed change set has been tested on Windows x64 (20H2) and Linux x32 systems., and no problems were detected on either platform.  PVR streams that do not flag AV_DISPOSITION_STILL_IMAGE work as they did, and streams that do flag AV_DISPOSITION_STILL_IMAGE also work now, and avoid the "log spam" that would otherwise cause.

My ability to test DVD and Blu-Ray content with still image menu system(s) is limited, but I didn't find any issues there either.

Thank you for your time.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by FernetMenta** [comment]
You try to cure something by hiding the symptom. This is not correct. VideoPlayerVideo should go to stalled state regardless of this new flag. You should change VP's action taken upon stalled condition in regard to this flag.

**Comment by djp952** [comment]
No problem, will rework from that guidance.  By doing it here I was also trying to avoid the constant logging of the stall during playback, since there isn't actually anything wrong with the stream.  For example:

> 2021-01-11 14:27:43.532 T:7964     INFO <general>: CVideoPlayerVideo - Stillframe detected, switching to forced 25.000000 fps
> 2021-01-11 14:27:48.655 T:7964     INFO <general>: CVideoPlayerVideo - Stillframe left, switching to normal playback
> 2021-01-11 14:27:49.170 T:7964     INFO <general>: CVideoPlayerVideo - Stillframe detected, switching to forced 25.000000 fps
> 2021-01-11 14:27:49.875 T:7964  WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
> 2021-01-11 14:27:50.425 T:7964  WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
> 2021-01-11 14:27:54.711 T:7964     INFO <general>: CVideoPlayerVideo - Stillframe left, switching to normal playback
> 2021-01-11 14:27:55.228 T:7964     INFO <general>: CVideoPlayerVideo - Stillframe detected, switching to forced 25.000000 fps
> 2021-01-11 14:27:55.906 T:7964  WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
> 2021-01-11 14:27:56.456 T:7964  WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
> 2021-01-11 14:28:00.720 T:7964     INFO <general>: CVideoPlayerVideo - Stillframe left, switching to normal playback
> 2021-01-11 14:28:01.252 T:7964     INFO <general>: CVideoPlayerVideo - Stillframe detected, switching to forced 25.000000 fps
> 2021-01-11 14:28:01.954 T:7964  WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
>

**Comment by FernetMenta** [comment]
> No problem, will rework from that guidance. By doing it here I was also trying to avoid the constant logging of the stall during playback, since there isn't actually anything wrong with the stream. For example:
> 
> > 2021-01-11 14:27:43.532 T:7964     INFO : CVideoPlayerVideo - Stillframe detected, switching to forced 25.000000 fps
> > 2021-01-11 14:27:48.655 T:7964     INFO : CVideoPlayerVideo - Stillframe left, switching to normal playback
> > 2021-01-11 14:27:49.170 T:7964     INFO : CVideoPlayerVideo - Stillframe detected, switching to forced 25.000000 fps
> > 2021-01-11 14:27:49.875 T:7964  WARNING : CRenderManager::WaitForBuffer - timeout waiting for buffer
> > 2021-01-11 14:27:50.425 T:7964  WARNING : CRenderManager::WaitForBuffer - timeout waiting for buffer
> > 2021-01-11 14:27:54.711 T:7964     INFO : CVideoPlayerVideo - Stillframe left, switching to normal playback
> > 2021-01-11 14:27:55.228 T:7964     INFO : CVideoPlayerVideo - Stillframe detected, switching to forced 25.000000 fps
> > 2021-01-11 14:27:55.906 T:7964  WARNING : CRenderManager::WaitForBuffer - timeout waiting for buffer
> > 2021-01-11 14:27:56.456 T:7964  WARNING : CRenderManager::WaitForBuffer - timeout waiting for buffer
> > 2021-01-11 14:28:00.720 T:7964     INFO : CVideoPlayerVideo - Stillframe left, switching to normal playback
> > 2021-01-11 14:28:01.252 T:7964     INFO : CVideoPlayerVideo - Stillframe detected, switching to forced 25.000000 fps
> > 2021-01-11 14:28:01.954 T:7964  WARNING : CRenderManager::WaitForBuffer - timeout waiting for buffer


The warnings are not related to still frames. Those messages indicate an issue with renderer that should not be ignored.

**Comment by djp952** [comment]
I'd like you to reconsider this PR as-is before pushing the suggested update(s) to it.  Based on your suggestions the solution is much more impactful than I feel it needs to be and will not solve the underlying problem in any more efficient manner than has been proposed.

The problem here is that Kodi is ignorant/intolerant of MPEG-TS streams wherein the video PES consists of still frames and is properly flagged as such by ffmpeg.  The presence of such PES data is not in error and should not cause egregious playback problems and/or log spam.

I'm fine with pushing a ridiculously overengineered version of the same basic solution if you want me to, but I must assume it will be summarily dismissed in similar fashion due to some presumed deficiency or clang-format issue.

It's either six-of-one or half-a-dozen of the other; which version will you accept as legitimate?

**Comment by FernetMenta** [comment]
If you think I advise you to implemented ridiculously overengineered solutions you should not ping me. Further I am not the person who accepts PRs nor do I complain about clang-format issues.
I only can tell you if your changes are correct, where I see problems, and where new behavior of VideoPlayer is best implemented.

> The problem here is that Kodi is ignorant/intolerant of MPEG-TS streams wherein the video PES consists of still frames and is properly flagged as such by ffmpeg

Maybe you are intolerant of other scenarios because you are going to break DVD menus. DVD menus are implemented by video streams that consists of still frames. Sounds familiar? When decoding a still picture it is important that the decoder is emptied because the still image might be comprised of multiple encoded frames. It is also important that processing of overlays continues. Also important that the still picture is continuously rendered or you will get a black screen if renderer has to reconfigure for what reason ever. You broke all of this.

Instead of moaning you could take a look into VideoPlayer and study how DVD menus are handled there. Maybe all that it takes to get your scenario fixed is to skip this block https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/VideoPlayer.cpp#L1836 if AV_DISPOSITION_STILL_IMAGE is set on the video stream.

**Comment by djp952** [comment]
I apologize, I incorrectly assumed you wanted me to overengineer the flag check itself (a flag that the stream "tolerates stalls") based on the commentary in the original PR.  I was modifying interfaces, adding overloads, all kinds of useless things, assuming you'd want the same available for the audio interfaces, considering a new PVR stream property so it can't hurt anything else, etc, etc, hence the aforementioned moaning about it.  The code position you referenced is exactly where that was all culminating and would be checked.  Thank you for the clarification, hopefully it's understandable where the frustration came from.

Given that DVDs don't use MPEG-TS (right?) and ffmpeg will only set this flag for MPEG-TS streams I found no impact to DVD menus at all with the original push.  What additional level of DVD testing do you want me to execute and document, or is verifying it on "a bunch of discs" going to be sufficient?

Also, do you foresee any concerns with Blu-Ray content that need to be protected against? I did not previously consider checking if ffmpeg will set this flag for Blu-Ray menus and need to do so.  I tested Blu-Rays, but not exhaustively.

It'll be a good day or two before I can play with this again anyway :)

**Comment by FernetMenta** [comment]
> Given that DVDs don't use MPEG-TS (right?)

Right, DVDs use mpeg-ps, but Blurays do use mpeg-ts. But does not matter because you test a flag that is an abstraction. ffmpeg is free to set AV_DISPOSITION_STILL_IMAGE on any stream from any container.

**Comment by djp952** [comment]
If you feel that doing the same check in the location you recommended will suffice, I've pushed an update that does that.  While I can't claim any reduced logging this way, it does solve the main problem that are referenced by the Issue(s).

I ran through about 40 Blu-Rays but didn't find any that set the AV_DISPOSITION_STILL_IMAGE in the menu systems, extras, or otherwise.  Perhaps a custom made disc with just photographs might do this?  Also rechecked about 20 DVDs just to be on the safe side.

My opinion is that at a minimum requires a comment to explain it if left as-is,.  Also perfectly fine with adding a method to CCurrentStream to hide the specific flag check and make the if statement more readable.  Would prefer a suggested method name, "ToleratesStall()" would be my choice but it doesn't feel accurate enough.

Thank you again!

**Comment by FernetMenta** [comment]
You did not follow my advice to add the condition here: https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/VideoPlayer.cpp#L1836

CVideoPlayer::HandlePlaySpeed does already cope with still frames. The variable used for this just doesn't have a proper name. Instead of "isInMenu" ist should be called "tolerateStall" or something. Then:

```
bool tolerateStall = IsInMenuInternal() || (m_CurrentVideo.hint.flags & StreamFlags::FLAG_STILL_IMAGES);
```

With this new flag other demuxers also get the chance to trigger this behaviour. If you define this new flag like AV_DISPOSITION_STILL_IMAGE, there is no change required in demuxer ffmpeg.
This is ugly but the other flags in StreamFlags are also defined with the same values as in ffmpeg: https://github.com/FFmpeg/FFmpeg/blob/2e2891383e596314a9888ba9b99d6987c82d7c9b/libavformat/avformat.h#L855

Comes from:
https://github.com/xbmc/xbmc/commit/e3ac6ab0a1acacec355eb10b0a2323c0ffd9c146

**Comment by djp952** [comment]
Thanks! I hope I got it right this time, and I like this much better myself.  Please note that I intentionally left isInMenu and tolerateStall as separate local variables due to the use of isInMenu to support the following functionality:

```
  // handle ff/rw
  if (m_playSpeed != DVD_PLAYSPEED_NORMAL && m_playSpeed != DVD_PLAYSPEED_PAUSE)
  {
    if (isInMenu)
    {
      // this can't be done in menu
      SetPlaySpeed(DVD_PLAYSPEED_NORMAL);

```

Fingers crossed; looks good from here functionality-wise but at some point I would like to talk to you about the logging concerns.  "works" is more important, of course.

**Comment by FernetMenta** [comment]
Looks good to me. Regarding the logging, I would make those debug logs:

```
2021-01-11 14:27:48.655 T:7964 INFO : CVideoPlayerVideo - Stillframe left, switching to normal playback
2021-01-11 14:27:49.170 T:7964 INFO : CVideoPlayerVideo - Stillframe detected, switching to forced 25.000000 fps
```

**Comment by djp952** [comment]
That works for me, sir.  Done.

**Comment by FernetMenta** [comment]
@fritsch this is a fix. you should to consider this for v19

**Comment by fritsch** [comment]
Thanks much, yes - I added the labels.

**Comment by djp952** [comment]
Are there any additional actions that I need to take on this PR for it to be approved; am happy to do whatever I need to do; thank you :)

**Comment by fritsch** [comment]
No - I just push it now. I visit you at home, when we get outtages :P

**Comment by djp952** [comment]
> No - I just push it now. I visit you at home, when we get outtages :P

That would be awesome, actually :)  Just need to know what to order for dinner.  Thank you (and everyone else) that work so hard on this stuff...

**Pull request merged**
