### PR TITLE
Revert "[Backport][Inputstream] Add IChapter interface #16581"

### PR DESCRIPTION
**Pull request by AlwinEsch**
This reverts commit da9b5f1f67684cfa4a0dbba9fa66ba753b860f16.

The API change on Leia has destroyed all after them created addons to use on
older Leia versions.

See e.g. here https://github.com/xbmc/inputstream.rtmp/issues/57

Not sure if also a revert here is needed https://github.com/peak3d/inputstream.adaptive/tree/Leia, seen the last commit is from 2 Sep 2019.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by peak3d** [comment]
Would't it be easier to fix the issue instead reverting? Do you know what happens exactly @AlwinEsch ?

**Comment by phunkyfish** [comment]
How would you fix this for a user on 18.1? I'm not sure that's possible.

**Comment by DaveTBlake** [comment]
@peak3d  https://github.com/xbmc/xbmc/pull/16977 was not a fix and made a breaking change to the addon API , it should not have been backported to Leia at all.

**Comment by AlwinEsch** [comment]
WIth them https://github.com/xbmc/xbmc/pull/16591 you added a check for this cases (on Matrix), but this not on Leia. 

Every new compiled inputstream addon after your request is then no more usable on Leia 18.0 to 18.5.

**Review by peak3d — APPROVED** [review]

**Review by phunkyfish — APPROVED** [review]
Once Jenkins is happy.

**Pull request merged**
