### PR TITLE
[Krypton] [cmake] build TestWebServer only if HTTPRequestHandlers are build

### PR DESCRIPTION
**Pull request by candrews**
Backport https://github.com/xbmc/xbmc/pull/11237 to Krypton - thanks @Rechi and @fetzerch

The defines HAS_WEB_SERVER and HAS_WEB_INTERFACE are already defined if HAVE_LIBMICROHTTPD is defined. There is no need to generally set it for windows.
TestWebServer must only be compiled if the HTTPRequestHandlers are build.

## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Rechi** [comment]
> The defines HAS_WEB_SERVER and HAS_WEB_INTERFACE are already defined if HAVE_LIBMICROHTTPD is defined. There is no need to generally set it for windows.

I don't see anything like that in this PR.

**Comment by candrews** [comment]
That's not part of the PR, it's just a statement (your words, I believe). I took it verbatim from the original PR at https://github.com/xbmc/xbmc/pull/11237

**Comment by candrews** [comment]
You're right, I didn't include the [win] commit (I didn't notice it as it's not relevant to my use case). I've now updated this PR to include both commits from the original PR.

**Comment by candrews** [comment]
The Jenkins build failures don't appear to be related to this PR.

**Comment by Rechi** [comment]
jenkins build this please

**Review by Rechi — APPROVED** [review]

**Pull request merged**
