### PR TITLE
Improve 'Choose Art' dialog

### PR DESCRIPTION
**Pull request by ronie**
## Description

This is an effort to fix two annoyances i have with the Choose Art dialog.

## Motivation and Context

1) currently, if you select 'Choose Art > Thumbnail' Kodi will list artwork for *all* art types, instead of only thumbs.
for instance, selecting a thumbnail for an album will list discart images, back covers, spine, and what not...

2) currently, if you select 'Choose Art' for an art type that has no available images, Kodi will list the thumbnail. it should only show the 'browse' option in this case.

## Screenshots (if appropriate):
1) choosing a thumbnail for an album:

before:
before

after:
after

2) choosing a discart image, when none are available:

before:
before2

after:
after2

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Comment by DaveTBlake** [comment]
This bevaiour was not a mistake that needs correction, but something deliberate. However @ronie I take your point about it not being nice once you do have lots of types of art being fetched so I'll take a look, but the solution maybe something other than simply removing that code. We still have users with historic scraped data and no "aspect" values in the lists of possible art. I want to be sure all cases are covered.

**Comment by ronie** [comment]
@DaveTBlake, art with no aspect will still be listed.

it only removes art that *does* have an aspect, but does not match the art type you're editing.
i.e. does not list aspect="discart" images when i'm setting a thumbnail (aspect="thumb")

**Review by rmrector — APPROVED** [review]
"Thumbs" up from me. I was a little iffy leaving the video library counterpart to the second commit, but it has weirder, more specific rules, so it can stay for now.

**Comment by DaveTBlake** [comment]
>art with no aspect will still be listed. it only removes art that does have an aspect, but does not match the art type you're editing.

Good, I didn't get to test I was just going from (faulty) memory.

I guess being able to select a _thumb_ as a _clearlogo_ or _discart_ makes little sense even if there are no alternatives of that aspect, so OK for 2).

I would like to continue to support a way to see all the possible art regardless of aspect. There is nothing that binds what aspect values are in the list of possible art previous fetched by a scraper, to the list of art types listed on the "Choose art type" dialog. That list contains all the types of art that Kodi has at least one stored of that type for one item (of that kind). Users can add local art of any type they like, and the scraper aspects could be anything too or change over time - core does not care. So possible remote art could get hidden 

Currently _all_ the possible remote art, regardless of aspect, gets listed under thumbnail and I can see that is problematic.  Would reducing that to be remote art with: 
-no aspect, 
-aspect=_thumb_  
- aspect is a value that does not match any of the types we already have
be an acceptable compromise?

**Comment by rmrector** [comment]
The first dialog (that shows art types) could be expanded to also include all art types in the "possible art" list, but I sure don't want to see multiple aspects/art types in a list for one art type. "thumb" means something just as specific as every other, it doesn't deserve pollution any more than they do.

And as far as artwork with no aspect, it only ever meant one art type per media item (thumb for the music library and episodes, poster for everything else), so it's a simple translation. Not that it needs addressed here, but that has a simple solution as we move forward.

**Comment by DaveTBlake** [comment]
OK @rmrector so you get my point about wanting to avoid having possible art of a type that the user doesn't see, but don't want type "pollution". In my early testing when I added the extended art support to v18 I had so few images to choose from having them shown for more than one type was not an issue.

Both scraping, local art and JSON API commands (from other addons or whatever) are sources for extended types art, there is no one place we can look that defines what type of art there are. I think it was good to remove that limit from core code, but it does make handling art type a bit more complicated.

I'll have a look at expanding the way the first "Choose Art Type" dialog is populated as you suggest (unless either ronie or you would like to do it).

**Comment by ronie** [comment]
i'm afraid i fail to follow what this discussion is about...
is there something wrong with my code?

if so, could you please provide a step-by-step way to reproduce it?

**Comment by rmrector** [comment]
Sorry. It's related but doesn't really need addressed here.

I'll take a look at this for another PR, I want to work with the "available but not assigned artwork" bit in the database.

**Comment by DaveTBlake** [comment]
>is there something wrong with my code?

No worries @ronie , not saying that.
Just me looking at the code that this PR removes, and reviewing why I deliberately implemented it that way originally. @rmrector has suggested a better way to achieve the one outcome that I still think is necessary without showing mixed art types under one heading (the thing that annoyed you).

**Comment by DaveTBlake** [comment]
Did some testing of this and found that it makes it look like I have no possible remote thumbs to select from. The previously scraped results  that are saved in the artist table  strImage field have aspect="poster" for thumbnails for many of the artists.

Listing artwork for _all_ art types, instead of only thumbs has hidden the fact that the XML scraper has been returning "poster"

When making this change the XML scraper will need to be updated too, and users with older scraper results stored will need to rescrape or the db entries otherwise updated (could replace "poster" with "thumb" or remove `aspect="poster"` using SQL).

**Comment by DaveTBlake** [comment]
Reconsidering this, users having older stored scraper results with `aspect="poster"` is not a show stopper. Choosing art happens one artist or album at a time, the user clicks to choose a different thumb and sees no remote images listed, all they need do is refresh the item scrapering online (skipping any NFO) and it  will fetch a new list of available art.  Being prompted to ignore NFO files (#15791)  will help that. 
I guess it could be an issue if they user wants to keep the other data from the NFO and just update the available art, but that is a longstanding workflow issue.

However we do need #15805 that includes all scraper available types in the choose art list, to be merged before this.

**Comment by DaveTBlake** [comment]
Since #15805 is in v18 I think there was the (vague) intention to backport this too despite being more improvement than outright fix. I was reminded by having fix https://github.com/xbmc/xbmc/pull/16207, also art type related,  to backport. In the light of that fix it would make a lot of user sense to backport this. 

Any thoughts @ronie @rmrector ?

**Pull request merged**
