### PR TITLE
[gui] change some settings from spinner to list

### PR DESCRIPTION
**Pull request by stefansaraev**
cosmetics. changed:
video -> subtitles -> font
tv -> playback -> fallback framerate
system -> video output -> refresh rate

### CODE REVIEW

**Comment by HitcherUK** [comment]
@phil65 will be happy ;)

**Comment by phil65** [comment]
True. ;)
I experienced some onclick delays when changing some values from spinners to lists while dealing with this some time ago (so the SelectDialog took a small time to show up). See https://github.com/xbmc/xbmc/pull/6176
Did you experience the same when testing this or was my system just behaving weirdly? :)

**Comment by stefansaraev** [comment]
> Did you experience the same when testing this or was my system just behaving weirdly? :)

well, I dont notice any delay. but it could be just my perception. dunno.

**Comment by Razzeee** [comment]
jenkins build and merge

**Comment by stefansaraev** [comment]
no need for jenkins

**Pull request merged**
