### PR TITLE
[smartplaylist] make mood field browseable

### PR DESCRIPTION
**Pull request by mkortstiege**
This enables mood browsing for songs within the smart playlist editor.

@Montellese for review please.

### CODE REVIEW

**Comment by Montellese** [comment]
Are you sure this works? I thought the moods field may contain multiple modds separated by a comma or slash.

**Comment by mkortstiege** [comment]
Right, I actually only tested with single mood values. Will try to get my hands on a real database, test again and adjust this one.

**Comment by mkortstiege** [comment]
Song mood is not implemented that way. There's no separator handling so whenever a song contains more than one mood it's stored as such. While thinking about it, i think we kinda agreed on having it a single value because it's song based. Will try to get my hands on a db nonetheless.

**Comment by mkortstiege** [comment]
@MartijnKaijser provided a .db and ofc.. it's stored comma separated in the tags. Will have to update the entire mood handling for J***. Yay ;)

**Pull request closed without merging**
