### PR TITLE
[settings] Moved subtitles settings to appropriate category

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

Add new "Subtitles" category menu to contains all settings related to subtitles

The existing "Language" category now contains only settings for language purposes
and has been merged with Accessibility which have the same purpose

## Motivation and context

A lot of changes has been done for subtitles in v20 that has introduced also a lot of new features,
therefore the current "Language" menu is no longer appropriate to contains all these subtitles settings

@enen92 this was the menu scheme discussed long time ago

suggestions for setting levels? otherwise i keep as original

## What is the effect on users?

A better consistent setting menu

## Screenshots (if appropriate):
immagine
immagine
immagine

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by enen92** [comment]
pinging @jjd-uk too as he was also in the loop (at least from my side) when we start thinking about this

**Comment by scott967** [comment]
Good improvement

**Review by enen92 — APPROVED** [review]
Looks good to me, nice improvement.

**Comment by enen92** [comment]
pinging @KarellenX as if this goes in the wiki needs an update on the settings category

**Review by jjd-uk — APPROVED** [review]
Another good improvement

**Comment by CastagnaIT** [comment]
jenkins build and merge

**Pull request merged**
