### PR TITLE
[depends] libdvd: get rid of unused git_rev, it breaks packaging

### PR DESCRIPTION
**Pull request by wsnipex**
## Description

GIT_REV in libdvd is not used for anything, but it breaks PPA packaging. Get rid of it.

## Motivation and context

https://github.com/xbmc/xbmc-packaging/pull/37

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [X] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by fuzzard — APPROVED** [review]

**Review by lrusak — APPROVED** [review]

**Comment by lrusak** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
looks like we have a couple of builders with broken tarballs:
`14:19:31 checking for newlocale... make[2]: Entering directory '/home/jenkins/workspace/LINUX-64-GL/tools/depends/target/libdvdcss'
14:19:31 rm -rf x86_64-linux-gnu-debug; mkdir -p x86_64-linux-gnu-debug
14:19:31 cd x86_64-linux-gnu-debug; tar --strip-components=1 -xf /home/jenkins/xbmc-tarballs/libdvdcss-1.4.2-Leia-Beta-5.tar.gz
14:19:31 tar: This does not look like a tar archive
14:19:31 gzip: stdin: not in gzip format
14:19:31 tar: Child returned status 1
14:19:31 tar: Error is not recoverable: exiting now
14:19:31 Makefile:32: recipe for target 'x86_64-linux-gnu-debug' failed`

**Comment by fuzzard** [comment]
Jenkins build this please

**Review by garbear — APPROVED** [review]

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Pull request merged**
