### PR TITLE
[curl] only use HTTP2 with SSL

### PR DESCRIPTION
**Pull request by wsnipex**
## Description

Cloudflare decided in it's infinite wisdom not to follow standards
that allow HTTP2 requests without encryption.
This changes curl to only use HTTP2 with SSL.

## Motivation and Context

Numerous reports of TMDB scrapers failing, IPTV issues..

## How Has This Been Tested?

not yet. Please test on all platforms but windows, which is not affected

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by sy6sy2** [comment]
I will try iOS, tvOS and macOS.

**Comment by sy6sy2** [comment]
The Gismeteo remains on macOS with the current Jenkins build.
Debug log with CURL log enable --> https://paste.kodi.tv/zudoxeruyi.kodi

**Comment by nunojsa** [comment]
Can say that this worked for me on Linux (Ubuntu Mate 20.04)

**Comment by arnova** [comment]
@wsnipex : Obviously there's the risk of regressions with this. An alternative could be first trying plain HTTP2 and if it fails HTTP2 with TLS (or perhaps the other way around is better anyway?). But maybe we should just see how your PR works out and keep this in mind in case issues surface.

**Comment by sy6sy2** [comment]
Tested with HDHomeRun guide (without this fix TV guide is empty):
* macOS : Ok
* tvOS : Doing
* iOS : Doing

**Review by sy6sy2 — APPROVED** [review]

**Comment by wsnipex** [comment]
@arnova I don't see a real risk, since that setting is the curl default and behaves like all modern browsers

**Comment by KarellenX** [comment]
Is there a build for this somewhere? I would like the member using FreeBSD to test this out...
https://forum.kodi.tv/showthread.php?tid=357709&pid=2982366#pid2982366

**Comment by arnova** [comment]
> @arnova I don't see a real risk, since that setting is the curl default and behaves like all modern browsers

Ah yes, that's right ofc. Then I think we're good :-)

**Comment by wsnipex** [comment]
@KarellenX we don't provide freebsd builds, he would have to compile himself.

**Pull request merged**
