### PR TITLE
[addon] remove not needed header comment in CScreenSaver

### PR DESCRIPTION
**Pull request by AlwinEsch**
The comment says 'Things that MUST be supplied by the child classes', but there
are no childs, is everything inside him.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
jenkins build this please and merge

**Comment by akva2** [comment]
childs refer to instances in the context. so it's not wrong as such, just imprecise.

**Comment by AlwinEsch** [comment]
For me the text was not understandable, to use as calls for screensaver is it clear that the rest of kodi must call them.
And for calls on add-on is it only:
```cpp
  void Start();
  void Render();
  void GetInfo(SCR_INFO* pInfo);
```

The GetInfo becomes also removed in future, was never used in Kodi and add-ons.

**Comment by akva2** [comment]
Not disagreeing or objecting to anything, just providing the information.

**Comment by AlwinEsch** [comment]
jenkins build this please

**Pull request merged**
