### PR TITLE
ADD: [droid;key] channel up/down

### PR DESCRIPTION
**Pull request by koying**
Synonym to PgUp/PgDown

### CODE REVIEW

**Comment by iz8mbw** [comment]
Will this PR enable in Kodi PgUp/PgDown when with the TV remote the channel up/down is pressed (using HDMI CEC)?

**Comment by koying** [comment]
Possibly. Depends what your flavour of CEC is sending for those keys.
If you see something in the kodi log when you press the keys, currently, there is a good chance

**Review by Rechi — COMMENTED** [review]
👍, can't test myself

**Comment by iz8mbw** [comment]
With remote of my TV I can send and use channel up/down that will give PgUp/PgDown on Kodi 18 with LibreELEC on Raspberry Pi 2.
Instead with the same remote and same TV on Nvidia Shield (Kodi 18 on Android) the channel up/down does not work, I don't know if is the Nvidia Shield that does not pass that HDMI CEC command to Kodi or if it's Kodi that does not recognized them.
If it's Kodi 18 that does not recognized channel up/down may be with this PR now will works.
If you give me a Kodi 18 APK file (arm64-v8a) that include this PR I can test on my Nvidia Shield.

**Comment by koying** [comment]
It all depends on how the Shield traps those keys and send them to the apps...
Will surely be in next nightly. Handling the keys themselves is separate from a CEC issue

**Comment by Rechi** [comment]
@iz8mbw open a thread in the forum with a debug log from a recent nightly.
For me this change doesn't look to be related to CEC handling.

**Comment by iz8mbw** [comment]
@Rechi I will check by myself in the Debug log of a recent nightly (or better the nightly that include this PR) and IF I cannot see the HDMI-CEC command about channel up/down it's not a Kodi releated problem but it's a "limitation" of the Nvidia Shield that will not recognize (or not pass to Kodi) the channel up/down commands.

**Comment by koying** [comment]
Re CEC, it works with my Sony X85 + Shield *if* I go to some buried CEC configuration on TV where I can choose that the TV related key are passed to CEC

image

**Comment by iz8mbw** [comment]
Also my TV remote works in CEC with Shield, but NOT for Channel UP and
Channel DOWN keys.
Channel UP and Channel DOWN CEC works with Shield? Did you tried also these
two keys?

Same TV (Panasonic OLED), same remote, with Raspberry Pi 2 and Odroid
C2 Channel
UP and Channel DOWN CEC works in Kodi...

Il 26/feb/2018 20:17, "Chris Browet" <notifications@github.com> ha scritto:

**Comment by koying** [comment]
CEC implementations vary greatly, as I said.
The libcec provided by Pulse Eight (https://github.com/Pulse-Eight/libcec) workarounds those, and is used in our pure linux platforms, like LE

**Comment by iz8mbw** [comment]
@koying  @Rechi 
Hi guys. Just tested this PR via the last nightly, I can CONFIRM that now, via HDMI-CEC, both Channel UP and Channel DOWN (PgUp/PgDown) works in Kodi with my TV remote and Nvidia Shield!!! Many thanks!
Tested on Nvidia Shield and Panasonic TX-55EZ950 TV (OLED).
Anyway the strange is that with the yesterday nightly, so without this PR, no CEC info on the debug log about these two keys pressed... I expected to see "some" HDMI-CEC commands on debug log.

**Pull request merged**
