### PR TITLE
[guiinfo] Fix LISTITEM_EPISODE and LISTITEM_SEASON...

### PR DESCRIPTION
**Pull request by ksooo**
... to return empty string in case the value is 0. Fix is needed for #7209

@xhaggi mind taking a look.

### CODE REVIEW

**Comment by xhaggi** [comment]
please check the code before i added the pvr specific processing. I'm sure i didn't change any condition (greater or equal zero). i don't want to introduce a new issue. @mkortstiege could you please take a look too.

**Comment by ksooo** [comment]
> I'm sure i didn't change any condition (greater or equal zero)

@xhaggi you did. https://github.com/xbmc/xbmc/commit/55302052602d5feb776435a2a69c232f31af5a55#diff-127e5f2786eb19ac8e0e2f04b3bf8306R4865 and https://github.com/xbmc/xbmc/commit/55302052602d5feb776435a2a69c232f31af5a55#diff-127e5f2786eb19ac8e0e2f04b3bf8306R4888

**Comment by ksooo** [comment]
Added "Isengard" label since this is a regression.

**Comment by xhaggi** [comment]
https://github.com/xbmc/xbmc/pull/6748#discussion_r26557178

check the comments in the related PR

**Comment by xhaggi** [comment]
@Montellese ping you too

**Comment by ksooo** [comment]
Regarding the old PR: As I can see the reason for the need to initialize the variables, I cannot see how the forum discussion should be related. Are the values returned by ListItem::[Season|Episode] stored in the epg database?

**Comment by mkortstiege** [comment]
Since season can be 0 (specials), this change is wrong. If it's causing issues for PVR it should be fixed for those fileitem types only.

**Comment by ksooo** [comment]
Ah! Just saw that the old PR contained two commits. One fixes the database problem mentioned  in the forum, the other the initialization of the variables in GUIInfoManager. 

I think, init  of vars is fine, comparing them against >= 0 instead > 0 is wrong. The database fix is unrelated to the ListItem changes, IMO.

**Comment by ksooo** [comment]
@mkortstiege Well, I tend to disagree. The fact that season can be 0 is not related or problematic here. GUIInfoManager just prepares data for representiin at the UI. Representing 0 season as "0" is wrong. My fix changes behaviour to return "" in this case. Nothing else. @ronie requested that behaviour and I think he is right.

**Comment by mkortstiege** [comment]
@ksooo I can't see how returning an empty string can be right. We are storing specials as season 0 in database. @ronie, mind explaining why it should be empty instead of the value we're storing?

**Comment by Montellese** [comment]
IMO whatever is returned for `LISTITEM_SEASON` should be in line with how we format the label of special episodes. Normal episodes are `SxxEyy` and special episodes are `Syy`.
But in the end it all comes down to convention. Skinners will either have to check the value returned for `LISTITEM_SEASON` against `"0"` or against `""` to determine whether it's a special episode or not.

**Comment by mkortstiege** [comment]
Right. We have to come up with a convention for J***. Pushing this as fix to Isengard is wrong and will cause regressions.

**Comment by ksooo** [comment]
Wow, two characters changed, big discussion triggered... ;-)

Regarding consistency: @ronie mentioned that the VIDEOPLAYER_SEASON and VIDEOPLAYER_EPISODE already behave like I changed the respecting LISTITEM stuff. And before @xhaggy's chance back in March the LISTITEM stuff did also behave consistent. Currently, without my PR, behaviour is inconsistent.

@mkortstiege are you mixing up internal data representation (e.g database) with UI representation? Cannot see how things should be related.

**Comment by ksooo** [comment]
And please be aware that current code is returning "S0" if both episode and season are 0. This does make absolutely no sense. Period.

**Comment by ksooo** [comment]
@mkortstiege I have no problem to not include it for Isengard, but out of curiosity, which regressions will it actually cause?

**Comment by Montellese** [comment]
> And please be aware that current code is returning "S0" if both episode and season are 0. This does make absolutely no sense. Period.

And that's YOUR opinion.
For me an episode with season 0 and episode 0 does not make any sense at all but assuming I had such an episode I'd expect it to be shown as "S0" (or "S00") because it's a special episode with the episode number being 0. Not showing anything at all doesn't fit with the representation of the rest of the special episodes or any episodes at all. And that's MY opinion.

IMO the most important thing in the end is that the information we provide (whatever it will be) is consistent across different info labels and across all special cases.

**Comment by ksooo** [comment]
...

**Comment by ksooo** [comment]
This eats up to much of my spare time. Sorry, don't wanted to bother anyone.

**Comment by xhaggi** [comment]
:smile: i don't want to start such a discussion. I'm not very familiar on how the returned season and episode values are used by our skins. 

VIDEOPLAYER_SEASON and EPISODE don't handle the special case, but you are right @ksooo here we check `greater zero` and return an empty string if lower 1.

BTW the main reason for this PR is that the PVR API returns 0 for season/episode in case the backend don't support it or can't provide the information for the show. @ronie in that case we need to check for 0 in skin to hide the info or output a default label.

**Comment by xhaggi** [comment]
BTW we should adjust the VIDEOPLAYER_ info labels to be consistent with the LISTITEM_ ones

**Comment by xhaggi** [comment]
@ksooo don't give up. I know sometime it's a little bit annoying if such a discussion starts about such a small alteration, but it's necessary to find the right solution.

**Comment by ksooo** [comment]
@xhaggi sure, but as UI is not my home playground I'm no longer interested in this larger discussion.

 Just wanted to help @ronie, because he requested the changed behaviour (at least I understood him this way) and I thought this would be a no-brainer.

**Comment by ronie** [comment]
my request was to not return 0 for epg items that:
1) are not episodes
2) don't have season/episode info in the db

it was not my intention for it to be changed globally.

it's not realistic to expect me to work around it in the skin. 
if kodi is going to return tv show specific info for non-tv show items,
then it should be fixed there.

it shouldn't be too hard to ad the ```if (iSeason > 0)``` check for epg items only -)

**Comment by xhaggi** [comment]
@ksooo any interest, in doing that :grimacing:

**Comment by ksooo** [comment]
@xhaggi I will not have the time to sort this out, sorry. It is not even clear to me what exactly shall be achieved.

**Comment by ronie** [comment]
this is what i had in mind: http://pastebin.com/Wax7nusk

**Pull request closed without merging**
