### PR TITLE
[music][video] (Music|Video)Utils::IsItemPlayable: Fix playlist detection

### PR DESCRIPTION
**Pull request by ksooo**
@basilgello fixes the problem you have reported here: https://github.com/xbmc/xbmc/pull/22107#issuecomment-1352027885, could you please review and  runtime test?

Runtime-tested on macOS, latest Kodi master.

Needs backport.

### CODE REVIEW

**Comment by emveepee** [comment]
@ksooo,  I do get that error message but the change you added seems to be already covered later here https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/builtins/PlayerBuiltins.cpp#L599 in IsAudio() and isVideo()  Is the issue with smartplaylists?

**Comment by basilgello** [comment]
@emveepee the issue was with M3U/PLS/STRM files. In the absence of time to craft proper PVR addon for Kyivstar.TV I use these playlists to play ephemeral streams.
@ksooo Thanks for the PR, I will try to rebuild Nexus RC1 with this patch tonight and report the results!

**Comment by ksooo** [comment]
@basilgello discovered at least two glitches/problems. This PR is supposed to fix one of these, not both. let me explain: from the log lines:

```log
2022-12-14 21:07:04.739 T:981     debug <general>: LoadDetails: Unsupported item type (path=/tmp/test.m3u)
```
Can be ignored here. This is just debug, but does not indicate an error for the use case discussed.

```log
2022-12-14 21:07:04.739 T:981     error <general>: GetItemsForPlayList: Unable to get playlist items for /tmp/test.m3u
```
This denotes a bug that is supposed to be fixed by this PR. Due to the fact that the playlist is not detected as such properly by `IsItemPlayable`, a fallback code path is taken to load the playlist instead of the code path designated for this use case. The line of code @emveepee mentioned does "fix" this problem by luck, as this code path is last resort for things we do not known how to handle properly and it seems to actually be able to load the playlist (I did not know that before) - we have far too many places where playlists are loaded, unfortunately. Hard to understand/maintain.

```log
2022-12-14 21:07:04.743 T:981     error <general>: Playlist Player: skipping unplayable item: 0, path [/tmp/test.m3u]
2022-12-14 21:07:04.744 T:981     debug <general>: Playlist Player: one or more items failed to play... aborting playback
```
This is something NOT supposed to be fixed by this PR. As I said, I tested with my own m3u, containing mp3 files located on my local disk next to the m3u file and the playlist was loaded and played just fine. Must be something with the content of the playlist used by @basilgello. Again, if there is a problem with that, this PR is not supposed to fix it. We should open a separate issue/PR for that.

**Comment by basilgello** [comment]
@ksooo Let me test but the contents of that M3U is standard PVR stream:

```
#EXTM3U
#EXTINF:-1,Test
#KODIPROP:mimetype=application/x-mpegurl
#KODIPROP:inputstream=inputstream.ffmpegdirect
#KODIPROP:inputstream.ffmpegdirect.manifest_type=hls
https://grandcentral.1plus1.video/vod/partner/viasat/202111/7e3e08bacb383f13a5fe76833b52ffe6a0edaa3d0004b9d5d347196fa1986d9c/272add83f4064deaeb4edeeaa026a1ac/1671187631?return_http=true
```

**Comment by ksooo** [comment]
Yes, please share in slack. Then I can have a look myself.

**Comment by emveepee** [comment]
.Perhaps you need to add to your change a return of false when the known mime type doesn't match the playlist type?  @basilgello is your /tmp folder identified as a music folder?

**Comment by basilgello** [comment]
Done!

**Comment by basilgello** [comment]
@emveepee no! It is a random playlist having one pvr stream. Replace with strm or pls and you'll get same behavior - beta1 worked, rc1 does not even try.

**Comment by ksooo** [comment]
@basilgello were you able to runtime-test this patch? If yes, what is the result?

**Review by basilgello — APPROVED** [review]

**Comment by emveepee** [comment]
@ksooo I still think something is funny with the test.  Running in the debugger, when I kodi-send a normal m3u8 it plays but the mime type is reported as audio/mpegurl  which inputstream .ffmpegdirect corrects.

```
2022-12-16 15:07:41.090 T:23568    info <general>: AddOnLog: inputstream.ffmpegdirect: inputstream.ffmpegdirect property: inputstream.ffmpegdirect.manifest_type = hls
2022-12-16 15:07:41.091 T:23568    info <general>: AddOnLog: inputstream.ffmpegdirect: Stream mimetype: application/x-mpegurl
```

**Comment by ksooo** [comment]
@emveepee sorry, all this is really not my home turf / play ground. I don't think I will investigate this further. I feel I have not broken anything here. I definitely did not touch how mime types of playlists will be determined.

**Comment by basilgello** [comment]
@emveepee Do you mean `GetMimeType()` returning `audio/mpegurl` ? That's weird but really, which mimetype should the stream have if it has video, audio and subtitles? ffmpeg likely checks stream by stream and audio is the last stream by id.

**Comment by ksooo** [comment]
The item's mime type will determined by the file extension. m3u is supposed to be audio. See utils/Mime.cpp

**Comment by emveepee** [comment]
That's why I thought this might be negative in some cases since previously if folder was a video folder that could override the mime type.

**Pull request merged**
