### PR TITLE
[library.kodi/librariy.xbmc] - fixed dylib names for osx/ios and don'…

### PR DESCRIPTION
**Pull request by Memphiz**
…t wrap our addon libraries.

Backport from MrMC https://github.com/MrMC/mrmc/commit/33d38edff51332bc393888d05cfba53f83ad5ed1#diff-25bb87ae2148a0a2abba0a8a4296b5bf

This basically makes our libraries proper dylibs on osx/ios and removes the fs wrapping which is not what we want for these libraries. Thx to @MrMC for finding that one.

### CODE REVIEW

**Comment by Memphiz** [comment]
@wsnipex do you have any idea if i need anything more? Binary addons are still compiling and working so i guess this is ist?

**Comment by Memphiz** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
jenkins build this please with addons

**Comment by Memphiz** [comment]
haha @wsnipex i found out why the trigger with addons didn't work ... because the trigger phrase had the normal trigger phrase in it and so the normal build without addons was triggered ... jenkins build this with addons please (<- i made them distinct now ...)

**Comment by wsnipex** [comment]
if our dyloading class handles dylib(probably, but didn't check), then that should be all you need.

**Comment by Memphiz** [comment]
Yes dyloading works (renamed the dylib and watched it failing for being sure) - have to check why it didn't compile though ;)

**Comment by Memphiz** [comment]
should be work much better now (was missing CXXFLAGS and so there was no c++11 linkage - this doesn't seem to be needed on the latest xcode7 buildtools i use locally - maybe they added c++11 implicitely) - fyi @davilla - jenkins build this with addons please

**Comment by MrMC** [comment]
makes sense

**Comment by Memphiz** [comment]
i think the addon errors are unrelated to this pr ... pvr.hts seems broken codewise atm ...

**Pull request merged**
