### PR TITLE
GBM: fix setting no HDR mode (on SDR display)

### LINKED ISSUE #24585: Display HDR capabilities are being misdetected (SDR detected as HDR)
### Describe the bug
$subject, basically. HDR to SDR tone mapping isn't working anymore on an Apollo Lake (Pentium N4200, Intel Gen9 iGPU) system, with the GBM backend. It has been working fine with the X11 backend. Note that it works just fine on both Haswell (Core i5-4250U) Gen7 and Alder Lake (Intel N100) Gen12 systems, only this Apollo Lake system seems to be affected.

## Expected Behavior
HDR to SDR tone mapping should work, the same way it worked with the X11 backend.

## Actual Behavior

HDR to SDR tone mapping doesn't work.

### To Reproduce

1. Enable HDR to SDR tone mapping.
2. Play an adequate video.

### Debuglog

https://paste.kodi.tv/gewusedovi.kodi

### Your Environment
Used Operating system:

- [ ] Android
- [ ] iOS
- [ ] tvOS
- [x] Linux
- [ ] macOS
- [ ] Windows
- [ ] Windows UWP

 - Operating system version/name: LibreELEC nightly, https://github.com/LibreELEC/LibreELEC.tv/commit/40b8914fbdb41e6676f9885553360f7cfbef72d5.
 - Kodi version: commit 06e228046c9f1316c7585bd61bfa1e28e22382da.

### PR DESCRIPTION
**Pull request by mglae**
## Description

SetHDR() has to return false if HDR cannot be enabled.

m_passthroughHDR has to be cleared in CLinuxRendererGLES::UnInit()

## Motivation and context

Fix #24585

As shown in the issue SDR displays are detected as HDR capable.  Therefore e.g. allow tone mapping cannot be used.

In CLinuxRendererGLES::Configure() m_passthroughHDR is set to the result of the SetHDR() call and later used to selecting color primaries and to enable tone mapping. 

Backport ~is required~ done.

## How has this been tested?

Building Generic image of recent LE master with this PR. Tone mapping is working on my SDR displays.

~Due to lack of supporting hardware HDR display functionality has to be tested by volunteers.~ HDR display succesful tested by @smp79 

## What is the effect on users?

GBM HDR tone mapping working. 

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by smp79** [comment]
> Due to lack of supporting hardware HDR display functionality has to be tested by volunteers.

No issues here with this PR and HDR display.

**Comment by smp79** [comment]
I spoke too soon - I found a major issue. It would appear that this PR is forcing tonemapping for non-HDR videos. And for some reason I see this issue only with SD content like DVDs and 576i TV channels which look extremely overbright.

IMG_20240319_002227

**Comment by mglae** [comment]
Debug log?

**Comment by smp79** [comment]
https://gist.githubusercontent.com/smp79/b4cfd1400195af54a0738d7e8f8746ae/raw/792c5e624effffeb98f456ab0d799bd1e2170057/gistfile1.txt

**Comment by smp79** [comment]
The only difference I see playing the same file
Without this PR:
`debug <general>: LinuxRendererGLES::Configure: HDR passthrough: on`

With this PR:
`debug <general>: LinuxRendererGLES::Configure: HDR passthrough: off`

**Comment by smp79** [comment]
Omg, I'm an idiot. This PR works fine. I forgot to remove https://github.com/xbmc/xbmc/pull/24160 before testing. 
The part that broke it was
```
-    if (buf.hasLightMetadata || (buf.hasDisplayMetadata && buf.displayMetadata.has_luminance))
-    {
-      toneMap = true;
-    }
+    toneMap = true;
```
Sorry about the noise.

**Comment by mglae** [comment]
But you are right; this PR rise another issue. m_passthroughHDR is never cleared after being set. This may show strange color or brightness.

The PR update should work together with your.

**Comment by smp79** [comment]
> The PR update should work together with your

Nope, it didn't fix the brightness. 
I can just remove the tonemap changes from my PR as the primary goal was to fix the HDR passthrough.

**Comment by mglae** [comment]
Thanks again for testing (I missed a ! operator)

BTW: cause of jenkins build errors is already fixed.

**Comment by ilikenwf** [comment]
@smp79 so after modification this as well as your metadata patch should work?

**Comment by smp79** [comment]
> I missed a ! operator

You mean  `m_passthroughHDR != false;`? This didn't fix it.

**Comment by smp79** [comment]
I removed the tonemap changes from https://github.com/xbmc/xbmc/pull/24160. This PR now works fine with and without my PR.

**Pull request merged**
