### PR TITLE
[win] define __SSE__ and __SSE2__ for the whole platform

### PR DESCRIPTION
**Pull request by Rechi**
## Description

`__SSE__` and `__SSE2__` will be defined for the whole platform.

## Motivation and Context
Enable SSE and SSE2 where possible.

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Rechi** [comment]
maybe @Paxxi for comment

**Comment by Paxxi** [comment]
Add them to cmake instead, and the check is not necessary because we don't run on cpu without sse2. 

Should be in cmake/platform/defines roughly, don't remember the exact file

**Comment by Paxxi** [comment]
Also thank you :) I tend to review on my phone and be a bit terse in my writing.

**Comment by Rechi** [comment]
@Paxxi updated
adding it to `project/cmake/platform/windows/defines.txt` didn't work, so I added it to `project/cmake/scripts/windows/ArchSetup.cmake`

**Comment by Paxxi** [comment]
Perfect

**Pull request merged**
