### PR TITLE
kodi-dev-kit: pvr Stream.h: fix language codes truncated to two chars

### PR DESCRIPTION
**Pull request by mglae**
## Motivation and Context

I.e. "mis" for "Miscellaneous languages" is truncated to "mi" and shown as "Maori".

## How Has This Been Tested?

With rebuild pvr.vdr.vnsi

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by phunkyfish — APPROVED** [review]
Thanks for finding this. @AlwinEsch this is still a PVR update to come, correct? So this can be merged and will be picked up in the next release?

**Comment by ksooo** [comment]
Is "mis" really a standardized language code? All language codes I know are 2 letter.

**Comment by ksooo** [comment]
> /// @brief 3 letter language id.

 Okay, then. Sorry for the noise.

**Review by AlwinEsch — APPROVED** [review]
Yes that I used the 2 there was absolutely wrong, thanks a lot to see and to fix!

**Comment by AlwinEsch** [comment]
> Thanks for finding this. @AlwinEsch this is still a PVR update to come, correct? So this can be merged and will be picked up in the next release?

Yes, this can in shortly before https://github.com/xbmc/xbmc/pull/17438

**Comment by phunkyfish** [comment]
Cool, I’ll leave it with you.

**Pull request merged**
