### PR TITLE
fix ServiceManager init/deinit

### PR DESCRIPTION
**Pull request by FernetMenta**
fixes issues introduced by #12432

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by ksooo** [comment]
Confirming that Kodi starts again with this fix, before it crashed 100% due to this==0x0 here:

<pre>
kodi.bin`PERIPHERALS::CPeripherals::GetPeripheralsWithFeature(this=0x0000000000000000, results=size=0, feature=FEATURE_CEC, busType=PERIPHERAL_BUS_UNKNOWN) const at Peripherals.cpp:255
</pre>

**Review by ksooo — APPROVED** [review]

**Pull request merged**
