### PR TITLE
[cmake] improve addon related version handling

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description
The first commit alow the check of defininition also by given include folder.
The second delete the generated addon.xml's in case the versions.h file is changed.

Without them comes it to problems if a version is changed. The related addon.xml.in are not generated new and has needed always a delete by hand before.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by AlwinEsch** [comment]
@wsnipex is this way OK?

**Comment by AlwinEsch** [comment]
Why simply when it is also complicated ;-)

Thanks a lot! Is changed and works nice.

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
fine for me

**Pull request merged**
