### PR TITLE
[osx] - no need for KODI_HOME env in xcode

### PR DESCRIPTION
**Pull request by Memphiz**
This removes the need for specifying the KODI_HOME env var in xcode.

@fetzerch ping - give this a shot please

### CODE REVIEW

**Comment by Memphiz** [comment]
jenkins build this please

**Comment by MrMC** [comment]
nice one.

**Comment by fetzerch** [comment]
Great, thanks much.

Confirming that it works with cmake/xcode and cmake/makefiles.

**Comment by Memphiz** [comment]
build error is unrelated

**Comment by ksooo** [comment]
@Memphiz does not work here. Without KODI_HOME, Kodi crashes on start.

Running latest kodi master on sierra with xcode8, dependencies rebuild from scratch (worked fine).

<pre>
2016-09-23 20:53:59.737761 Kodi[57079:1192664] Debug Print: Detected Mavericks...
2016-09-23 20:53:59.774725 Kodi[57079:1192664] SLPSGetCurrentProcess(): This call is deprecated and should not be called anymore.
2016-09-23 20:53:59.774772 Kodi[57079:1192664] set_foreground_operation_state(): This call is deprecated and should not be called anymore.
2016-09-23 20:53:59.944627 Kodi[57079:1192664] Debug Print: Log level changed to "LOG_LEVEL_DEBUG"
2016-09-23 20:53:59.945281 Kodi[57079:1192736] Debug Print: Thread Announce start, auto delete: false
sh: /Users/kai/Library/Developer/Xcode/DerivedData/Kodi-dnzkudcfgvydmwcriioqctsgbeur/Build/Products/Debug/tools/darwin/runtime/preflight: No such file or directory
2016-09-23 20:53:59.958628 Kodi[57079:1192664] Debug Print: special://profile/ is mapped to: special://masterprofile/
2016-09-23 20:53:59.958710 Kodi[57079:1192664] Debug Print: -----------------------------------------------------------------------
2016-09-23 20:53:59.958748 Kodi[57079:1192664] Debug Print: Starting Kodi (17.0-BETA3 Git:2016-09-23-d3bc525). Platform: OS X x86 64-bit
2016-09-23 20:53:59.958783 Kodi[57079:1192664] Debug Print: Using Debug Kodi x64 build
2016-09-23 20:53:59.958814 Kodi[57079:1192664] Debug Print: Kodi compiled Sep 23 2016 by Clang 8.0.0 (clang-800.0.38) for OS X x86 64-bit version 10.8.0 (1080)
2016-09-23 20:53:59.959035 Kodi[57079:1192664] Debug Print: Running on Apple Inc. MacBookPro8,2 with OS X 10.12, kernel: Darwin x86 64-bit version 16.0.0
2016-09-23 20:53:59.959085 Kodi[57079:1192664] Debug Print: FFmpeg version/source: 3.1.3-kodi-3.1.3-Krypton-Beta3
2016-09-23 20:53:59.959130 Kodi[57079:1192664] Debug Print: Host CPU: Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz, 8 cores available
2016-09-23 20:53:59.959179 Kodi[57079:1192664] Debug Print: special://xbmc/ is mapped to: /Users/kai/Library/Developer/Xcode/DerivedData/Kodi-dnzkudcfgvydmwcriioqctsgbeur/Build/Products/Debug
2016-09-23 20:53:59.959232 Kodi[57079:1192664] Debug Print: special://xbmcbin/ is mapped to: /Users/kai/Library/Developer/Xcode/DerivedData/Kodi-dnzkudcfgvydmwcriioqctsgbeur/Build/Products/Debug
2016-09-23 20:53:59.959279 Kodi[57079:1192664] Debug Print: special://xbmcbinaddons/ is mapped to: /Users/kai/Library/Developer/Xcode/DerivedData/Kodi-dnzkudcfgvydmwcriioqctsgbeur/Build/Products/Debug/addons
2016-09-23 20:53:59.959312 Kodi[57079:1192664] Debug Print: special://masterprofile/ is mapped to: /Users/kai/Library/Application Support/Kodi/userdata
2016-09-23 20:53:59.959354 Kodi[57079:1192664] Debug Print: special://envhome/ is mapped to: /Users/kai
2016-09-23 20:53:59.959402 Kodi[57079:1192664] Debug Print: special://home/ is mapped to: /Users/kai/Library/Application Support/Kodi
2016-09-23 20:53:59.959443 Kodi[57079:1192664] Debug Print: special://temp/ is mapped to: /Users/kai/.kodi/temp
2016-09-23 20:53:59.959480 Kodi[57079:1192664] Debug Print: special://logpath/ is mapped to: /Users/kai/Library/Logs
2016-09-23 20:53:59.959528 Kodi[57079:1192664] Debug Print: special://frameworks/ is mapped to: /Users/Shared/xbmc-depends/macosx10.12_x86_64-target/lib
2016-09-23 20:53:59.959566 Kodi[57079:1192664] Debug Print: The executable running is: /Users/kai/Library/Developer/Xcode/DerivedData/Kodi-dnzkudcfgvydmwcriioqctsgbeur/Build/Products/Debug/Kodi
2016-09-23 20:53:59.959611 Kodi[57079:1192664] Debug Print: Local hostname: kso-mac.fritz.box
2016-09-23 20:53:59.959681 Kodi[57079:1192664] Debug Print: Log File is located: /Users/kai/Library/Logs//kodi.log
2016-09-23 20:53:59.959734 Kodi[57079:1192664] Debug Print: -----------------------------------------------------------------------
2016-09-23 20:53:59.960497 Kodi[57079:1192664] Debug Print: load settings...
2016-09-23 20:53:59.961091 Kodi[57079:1192664] Debug Print: CSettings: error loading settings definition from special://xbmc/system/settings/settings.xml, Line 0
Failed to open file
2016-09-23 20:53:59.961159 Kodi[57079:1192664] Debug Print: Unable to load settings definitions
ERROR: Unable to create application. Exiting
</pre>

**Comment by Memphiz** [comment]
that doesn't look right - special://xbmc should point to your source dir - for example here it points to:

Debug Print: special://xbmc/ is mapped to: /Users/memphis/src/xbmc-memphiz

for you:

/Users/kai/Library/Developer/Xcode/DerivedData/Kodi-dnzkudcfgvydmwcriioqctsgbeur/Build/Products/Debug

Are you building the Kodi target? Or the Kodi.app Target?

**Comment by ksooo** [comment]
Kodi i guess...

**Comment by ksooo** [comment]
screen shot 2016-09-23 at 22 34 37

**Comment by ksooo** [comment]
Maybe this is the problem (al
screen shot 2016-09-23 at 22 37 48
though i never changed anything here)?

**Comment by ksooo** [comment]
Changing that to "Kodi" does not solve the prob, hmm.

**Comment by Memphiz** [comment]
Well i need to Check myself once i have my macmini back and can update it to sierra... Problem is that the binary is built out of our tree - where Mine is built in the folder "Build" in our tree...

**Comment by ksooo** [comment]
How can one control where the binary is built?

**Comment by Memphiz** [comment]
http://stackoverflow.com/questions/14428770/how-do-i-specify-where-xcode-stores-the-compiled-binaries

Intermediate folder should be in the source - i guess thats why we need to use KODI_HOME still for some setups :( - there is no way in determining the src tree when the binary is somewhere else

**Comment by ksooo** [comment]
> thats why we need to use KODI_HOME still for some setups :(

 seems we need it for the standard xcode setup as i never touched those xcode settings before. could you please re-document that in README.osx ?

**Comment by ksooo** [comment]
Here is what works for me:

1. no changes in Xcode -> Preferences -> Locations
2. change Xcode -> Preferences -> Locations -> Advanced -> Build Location to "Custom" + "Relative to Workspace"

screen shot 2016-09-24 at 13 05 46

**Comment by Memphiz** [comment]
yeah seems i have this - but i don't know where this is saved because i have never touched this since xcode4 or so :) (seems that setting is super sticky)

**Comment by Memphiz** [comment]
@fetzerch so can cmake do those kind of adaptions? I doubt it - that would mean we have no automated solution for this with cmake + xcode ...

**Comment by fetzerch** [comment]
you mean to configure where the binaries are put? Kodi is built to <BUILD_DIR>/$(Configuration)/Kodi.bin.
And since we want KODI_HOME to point to <BUILD_DIR>, your change worked fine here.

**Comment by Memphiz** [comment]
ahh ok - so xcode picks that build dir up already - fine then ...

**Comment by ksooo** [comment]
sorry, don't get that. why it did not work for me, then? my fault? nope, as i used xcode default configuration settings for build location...

**Comment by Memphiz** [comment]
you didn't generate the xcode project with cmake ...

**Comment by Memphiz** [comment]
in the end ther might be a way to set that path in xcode project somehow - but we will switch to cmake xcode generation so i don't bother about that ...

**Comment by ksooo** [comment]
> you didn't generate the xcode project with cmake ...

 ah, okay. thanks for explaining

**Pull request merged**
