### PR TITLE
[Skins] Update language files

### PR DESCRIPTION
**Pull request by ronie**
## Description
as it's been a while since there's been an automated update from Transifex (and since no one knows if/when there'll be one)
i put in some manual labor to export the skin language files from Transifex.

## How Has This Been Tested?
i've tested the dutch language files in Estuary / Estouchy.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by gade01 — APPROVED** [review]
Thanks, it looks really good.

**Review by ksooo — APPROVED** [review]
Nice.

**Comment by ksooo** [comment]
Don't we need an addon version bump to push the updated strings to the addon repo?

**Comment by ronie** [comment]
> Don't we need an addon version bump for both skins to push the updated strings to the addon repo?

skins are shipped with kodi only, they are not in the repo.

**Pull request merged**
