### PR TITLE
[Estuary] Fix background for WallWatchedIconVar

### LINKED ISSUE #22765: [Estuary] Kodi 20.0 white icons on white posters
### Describe the bug
Here is a clear and concise description of what the problem is:

On Kodi 20.0 the placement of the check mark icon representing Watched state and the three disc icon representing a set in views showing posters have been moved from under the poster to the bottom corner of the poster. The problem here is that being solid white it will not show up when displayed over a solid white area of some posters. The is only a problem in the Shift view, in other views like Wall and Poster the corner has an added shadow that allows the check mark to be seen.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

To be able to see the icons regardless of the graphics of the poster. 

## Actual Behavior

White icons disappear on white backgrounds in Shift view.

## Possible Fix

Add the shadow on Shift view like it is on other views.

### To Reproduce

1. Have a movie in your library with a poster that has a solid white area in the bottom left corner.
2. Enter Movies and change to Shift view.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android (Fire Stick and Google TV)
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows 10
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

I realize that some things can get over looked when doing major upgrades, like from Matrix to Nexus, and this will be fixed in Nexus 20.1. You guys have done an amazing job on this, thank you for all your hard work.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by jjd-uk**
## Description
Infowall view is missing the icon background for inprogress.
Shift view is missing the icon background for inprogress & watched.

The missing background meant the white inprogress/watched icons could not be clearly seen when there's poster with white within the icon area.

## Motivation and context
Fix https://github.com/xbmc/xbmc/issues/22765

## How has this been tested?
Tested locally with a mix of watched, unwatched, & inprogress items.

## Screenshots (if appropriate):

**InfoWall Inprogress Before**

infowall_inprogress_before

**InfoWall Inprogress After**

infowall_inprogress_after

**Shift Inprogress Before**

shift_inprogress_before

**Shift Inprogress After**

shift_inprogress_after

**Shift Watched Before**
shift_watched_before

**Shift Watched After**

shift_watched_after

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by jjd-uk** [comment]
Been a while since I've done a PR so hopefully all is correct.

Not sure how active @ronie is at the moment, so added you @enen92 to give it a check if you're able.

**Comment by scott967** [comment]
I took a look at View 54 InfoWall, and I note that in the include InfoWallMovieLayout when there is no poster, the ListItem.Icon is shown above a textbox of the ListItem.Label.  These icons draw on top of the label text.   But it isn't just a problem here.  Agree that this PR works as intended.

screenshot00005

**Comment by jjd-uk** [comment]
@scott967 Not strictly the problem this was seeking to fix, but I did check that as well, however I didn't have anything with such long names. I will take another look at it.

**Comment by jjd-uk** [comment]
Closing this for now as I'm reworking it.

**Pull request closed without merging**
