### PR TITLE
[backport][WM] Stop bypassing lockcode of mediasources

### PR DESCRIPTION
**Pull request by howie-f**
## Description

backport of #17129 / #17381 to Kodi Leia (+ some additional cleanup)

## How Has This Been Tested?
running on debian in the living room. all tests passed.

## Types of change
- [X] **Bug fix** (non-breaking change which fixes an issue)
- [X] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document

### CODE REVIEW

**Comment by howie-f** [comment]
okay, i think it's ready to go now. so @garbear, if you're in the mood for a review...

**Review by garbear — APPROVED** [review]

**Comment by fritsch** [comment]
Thanks very much. Please reword the last commit, so that it's clear which scope it has. "Fix:  doxy" looks a bit odd.

**Comment by howie-f** [comment]
> Thanks very much. Please reword the last commit, so that it's clear which scope it has. "Fix: doxy" looks a bit odd.

better this way? i tended to squashing it into https://github.com/xbmc/xbmc/pull/17386/commits/4c553bb54a8b933a252e38d59414f2883ec6dc80 where it belongs..

**Comment by fritsch** [comment]
To have the clear cherry-pick history from master I suggest to have it like: GuiPassword: Fix doxygen header

If it was a master commit, the squash would be the way to go

**Comment by howie-f** [comment]
ok, then i‘ll rename once jenkins finishes

**Comment by DaveTBlake** [comment]
This probably looks worse than it is, but not prepared to risk merging it on day of 18.6 release, so bumped milestone to 18.7

**Comment by howie-f** [comment]
of course i understand this decision, but i feel like #17412 should be fixed before 18.6 goes out (even though i don't know if my fix appropiate). just my 2 cents

**Comment by DaveTBlake** [comment]
Your timing was just unfortunate @howie-f, 18.6 was due out over a month ago, and been held back by issues with the binary addons built for some platforms and then illness. We now have a small window with people available to do the release, so it is happening with the 30+ fixes that are ready, merged and tested in the nighly builds. If there are more issues to be mopped up then we can have a 18.7

**Comment by phunkyfish** [comment]
This looks very ready to go in. Can someone push the button?

**Comment by fuzzard** [comment]
Cheers for the work @howie-f

**Pull request merged**
