### PR TITLE
VAAPI: restore accidentally lost call to sync of vaapi render picture

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by fritsch** [comment]
To play devil's advocate here: does that fix a known issue?
Background: we run that since several months without any bugreport now by accident. I currently don't understand why it works currently without the fences and wanted to understand that.

Any idea?

**Comment by FernetMenta** [comment]
> Any idea?

The sync is required for a deterministic behaviour. Without it you can get buffer overwrites or decoder pipeline can block waiting for gl operations to be finished.
Without the sync it may work by chance depending on the drivers implementation and other components you can't influence directly. Not seeing any obvious issues does not mean that the code was correct. See vda on OSX. It has always been broken but the symptoms started showing on some systems as we changed the format of the video surface.

If you don't do this right, you'll end up in very hard to track down errors like the AMD asic hang you should remember: https://github.com/xbmc/xbmc/pull/1649

**Comment by fritsch** [comment]
Thx. So in essence: it worked by chance and not cause we have some serialized code somewhere, which should be investigated.

**Comment by FernetMenta** [comment]
I don't claim this but I have no indicators that we do.

**Pull request merged**
