### PR TITLE
[videothumbloader] skip thumb extraction for bluray items

### PR DESCRIPTION
**Pull request by mkortstiege**
Skip over bluray items, extracting thumbs for those will wail anyways.

/cc @ace20022 since i am not 100% sure about chapter thumbs.

### CODE REVIEW

**Comment by arnova** [comment]
Why do they fail? Is ffmpeg unable to handle that?

**Comment by mkortstiege** [comment]
> Why do they fail? Is ffmpeg unable to handle that?

From what i recall it's not even guaranteed it's grabbing from the actual main movie. @MartijnKaijser pinged me about this and i've just monkeyed that PR together :)

**Comment by MartijnKaijser** [comment]
it tries to grab metadata from the index.bdmv file each time you browse you library. Which fails and next time tires to do that again

**Comment by MartijnKaijser** [comment]
''' 19:52:01 T:2100194816   DEBUG: virtual bool CThumbExtractor::DoWork() - trying to extract filestream details from video file smb://SKYNET-SERVER/Multimedia/Movies/Star Wars Episode I - The Phantom Menace (1999)/BDMV/index.bdmv

**Comment by arnova** [comment]
But does this only concern index.bdmv files then? And if not: shouldn't the exclusion be more strict then?

**Comment by da-anda** [comment]
because I just stumbled over it - thumb extraction is already skipped for blurays in DVDFileInfo
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/dvdplayer/DVDFileInfo.cpp#L110

**Comment by mkortstiege** [comment]
Jep, we're skipping extraction for opticals. Not sure why it's not yet done in the actual worker as suggested here. Objections?

**Comment by mkortstiege** [comment]
jenkins build this please.

**Pull request merged**
