### PR TITLE
[addon] remove all windows.h includes

### PR DESCRIPTION
**Pull request by Rechi**
## Description
Remove all includes of `windows.h` in the add-on dev kit headers.
If an add-on needs something from it, it has to include it themself.
List of add-ons which must be adapted before this changes is merged.

| add-on | PR | merged |
| --- | --- | --- |
| pvr.stalker | https://github.com/kodi-pvr/pvr.stalker/pull/88 | :white_large_square: |
| pvr.vbox | https://github.com/kodi-pvr/pvr.vbox/pull/189 | :heavy_check_mark: |
| pscreensaver.biogenesis | https://github.com/notspiff/screensaver.biogenesis/pull/6 | :heavy_check_mark: |
| screensaver.greynetic | https://github.com/notspiff/screensaver.greynetic/pull/6 | :heavy_check_mark: |
| screensaver.pyro | https://github.com/notspiff/screensaver.pyro/pull/6 | :heavy_check_mark: |
| screensaver.stars | https://github.com/notspiff/screensaver.stars/pull/9 | :heavy_check_mark: |
| vfs.rar | https://github.com/notspiff/vfs.rar/pull/4 | :heavy_check_mark: |

## Motivation and Context
Windows has some functions with the same name as we use (e.g `CreateDirectory`, ...) and the special windows ANSI / UNICODE handling makes it hard to compile add-ons without other stupid hacks.

## How Has This Been Tested?
compiled all binary add-ons

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
imo you can merge this. No problem if an addon is broken for a while in master

**Comment by MartijnKaijser** [comment]
jenkins build with addons

**Comment by MartijnKaijser** [comment]
jenkins build this with addons please

**Comment by Rechi** [comment]
I merge this now.
PR for the last effected add-on is created that's all I can do.

**Pull request merged**
