### PR TITLE
Fix episode thumbs still showing Spoiler Overlay after being watched

### PR DESCRIPTION
**Pull request by therealcodlord**
## Description
Fix for the issue raised a long time ago in #15296 
The setting we are speaking of here is **Settings -> Media -> Videos -> Show information for unwatched items** 
And the **Episode thumb** option which can be:
- Selected = TV show episode thumbs will always be shown regardless of watched status. 
- Unselected = TV show episode thumbs will be hidden for unwatched episodes.

When the option was unselected, there was a bug which meant on an initial media add/scan to library the thumbs would be hidden (by the spoiler overlay) but they would remain hidden when watched or when the watched status was changed.

## Motivation and context
Fix/change to make the GUI interface responsible for hiding the thumbs where appropriate, and leave the database library art alone - media scrapers can do their job and users can still choose custom artwork.
See #15296 for more details.

## How has this been tested?
Built on Ubuntu 20.10
Tested by changing the selection status of the **Episode thumb** setting and:
Looking at existing TV Shows with a mixture of watched/unwatched items and changing the watched status.
Tested the different list views and the information dialog view of the default Estuary skin.
Tested by adding a new TV Show to the library with the "Episode thumb" both selected and unselected and seeing that the thumbs are shown/hidden appropriately.

## What is the effect on users?
Users will have TV show thumbs for unwatched episodes hidden (if they set the appropriate setting) and thumbs will show/hide as episodes are watched or marked as watched/unwatched.
HOWEVER: Users who have set the setting and added/scraped TV shows to their library with the old version of the code will need to do a refresh of the show for this fix to take effect. That is because the thumb artwork in their database will already be set wrong for unwatched items.

## Types of change
- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

Bug fix, but also improvement on previous implementation as this now does not change artwork in the database, now only changes what is shown in the GUI interface.

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by biner73** [comment]
I've also noticed this bug. I had a look at the code, and it makes sense to me. Leaving the thumbs alone in the db, and using the overlay in the presentation  layer is a cleaner way to do it. I've been testing this for a few days, and it's working great, no issues, and the thumbs behave as expected when switching between watched/unwatched for episodes.

**Comment by HitcherUK** [comment]
Tested today and it works exactly as expected.

Thanks for your contribution.

**Comment by ksooo** [comment]
Should "GetThumbHideIfUnwatched" be a method of "CFileItem"? Seems a better fit than "CGUIInfoManager", imo.

**Review by ksooo — CHANGES_REQUESTED** [review]

**Comment by therealcodlord** [comment]
@HitcherUK Changing the order of fanart/overlay would be reverting a previously committed/released change. Personally I prefer the fanart to be shown rather than the overlay. But, regardless of my personal opinions I think any change to the order should not be done in this change. My reasons: There are other places in Kodi that do not yet handle any of the showing/hiding spoiler logic. For example the web interface or the Kodi Kore interface. I am coding/testing more changes to remedy that in a separate PR and I think we should have this discussion along with those changes as then it can be decided how best all the interfaces should handle this sort of logic and exactly what should be shown and when in a consistent manner across all the interfaces.

I will make the changes suggested by @ksooo moving the method to CFileItem.

As I am a beginner here I don't actually know how to do a backport so if someone could help me out there or point me to a suitable resource etc? Thanks!

**Comment by ksooo** [comment]
> As I am a beginner here I don't actually know how to do a backport

 Let's do it step by step. First we need to bring this PR into a state where it can be approved/merged. Then, we create the backport PR out of the approved master PR. Saves us all some time.

**Comment by jjd-uk** [comment]
For a Backport checkout the Matrix branch, apply your changes on top then push to a new branch on your repo, then create a PR to the Matrix branch.

**Review by ksooo — CHANGES_REQUESTED** [review]
Some things that should be improved.

**Review by ksooo — APPROVED** [review]
Thank you very much for your contribution.

**Comment by HitcherUK** [comment]
@therealcodlord Any chance of adding a boolean to the GUI settings so skins know if this is enabled for episodes please?

At the moment it's only stored as an integer which isn't available to skinners -

`<setting id="videolibrary.showunwatchedplots" default="true">0,1,2</setting>`

Whereas booleans are -

`System.GetBool(boolean)`

Thanks.

**Pull request merged**
