### PR TITLE
Add disabled textures for radio buttons and spin controls

### PR DESCRIPTION
**Pull request by braz96**
This pull request adds support for additional textures for radio buttons and spin controls when they are disabled. For example, the following control options are available to skins:

radiobuttons:
`<textureradioondisabled colordiffuse="disabled">radioon.png</textureradioondisabled>`
`<textureradiooffdisabled colordiffuse="disabled">radiooff.png</textureradiooffdisabled>`

spin controls:
`<textureupdisabled colordiffuse="disabled">upspincontrol.png</textureupdisabled>`
`<texturedowndisabled colordiffuse="disabled">downspincontrol.png</texturedowndisabled>`

This is the first time I've touched any C++ code in about 13 years, so go easy on me. :) I built this on my Windows 8 htpc and it seems to work as intended. I welcome any comments or suggestions. The one area I wasn't too sure about is the legacy interface file Control.cpp. Some additional code may be needed there.

Forum discussion link: http://forum.kodi.tv/showthread.php?tid=224145&pid=1981755#pid1981755

Thanks!

### CODE REVIEW

**Comment by bryanbrazil** [comment]
Added a new commit to convert tabs to spaces, as requested. Went ahead and squashed the commit, though, and lost the comment. I'm guessing I shouldn't squash any commits after initiating a pull request until told to do so.

**Comment by ronie** [comment]
great, thanx for this!
definitely a +1 from my end.

not sure who of the team would be most suitable to check the code...
@mkortstiege could i interest you to review this one ? ;-)

**Comment by Montellese** [comment]
The changes look good in general.

But I'm not sure about the changes to the legacy Control classes which are used for the python API. Inserting function parameters between existing parameters will break backwards compatibility of the API because the original order of the parameter doesn't work anymore. IMO we should split those changes into a separate commit and then if we decide to postpone those changes we can easily remove that commit.

**Comment by bryanbrazil** [comment]
Thanks, will split into two commits. 

Quick procedural question, how best to do this? Rebase and Edit the existing commit?

**Comment by Montellese** [comment]
```
git reset --soft HEAD~1
git reset HEAD xbmc/interfaces/legacy/Control.*
git commit -m "[guilib] add disabled textures for radio buttons and spin controls"
git add xbmc/interfaces/legacy/Control.*
git commit -m "[python] add disabled textures for radio buttons and spin controls"
```
That way you can also fix the commit message of your comment commit.

**Comment by bryanbrazil** [comment]
Thanks for the git help Montellese, I will remember this for next time.

**Comment by Montellese** [comment]
Great thanks. The first commit should be good.

@MartijnKaijser @ronie: How should we handle the python API change? From a cosmetic PoV the changes look correct (i.e. all texture parameters are right next to each other) but from an API breakage PoV the new parameters should go at the end.

**Comment by MartijnKaijser** [comment]
i would avoid any API breakage at any point and just put them at the end.
Should also bump API versions for gui / python

**Comment by tamland** [comment]
Sure it will break if you put the in the middle, but anybody in their right mind would use keyword arguments for that method so I don't think that they're 'logically' ordered really matter;)

**Comment by MartijnKaijser** [comment]
Indeed. I've never seen someone using the enumeration method and only use keywords

**Comment by bryanbrazil** [comment]
Just checking in to see if there's anything else I need to do for this. If not, I'll wait patiently. :)

**Comment by Montellese** [comment]
Apart from the minor I commented on all the new parameters added to the python legacy API need to be moved to the end of the respective parameter list.

Apart from that it looks good but we'll have to wait for 15.0 to be released before we merge new features.

**Comment by bryanbrazil** [comment]
@Montellese 
Made the requested changes, thanks!

**Comment by MartijnKaijser** [comment]
@bryanbrazil care to rebase?
any objection for 15.0?

**Comment by bryanbrazil** [comment]
No objection to 15.0, though I'm out of the country right now. Won't be
back and in front of a computer until June 6.

**Comment by ronie** [comment]
not a fan of messing with the skinning engine at this point, so let's wait till J*.

**Comment by MartijnKaijser** [comment]
@bryanbrazil can you rebase?

**Comment by bryanbrazil** [comment]
Hi Martijn,

Rebased, but now I can't figure out how to push the changes to my remote branch. Git reports permission denied, cannot read from remote repository. Any ideas?

Sorry for the basic questions, working with upstream repos is frustrating for a git beginner like myself. :)

**Comment by hudokkow** [comment]
This PR's branch (https://github.com/bryanbrazil/xbmc/tree/disabledtextures) isn't up-to-date.

There are others ways to do it but this should minimize risks. Please follow these steps, one at a time:

> git checkout master
git fetch upstream
git merge upstream/master
git push

At this point your master branch should be up-to-date with ours. Now, lets rebase your disabledtextures branch.

> git checkout disabledtextures
git rebase master
git push -f

If *git rebase master* has conflicts, you need to solve them and continue with *git rebase --continue*
You can also run *git rebase --abort* and stop the rebase if you're in doubt/think something is wrong. We're were to help so feel free to ask.

**Comment by bryanbrazil** [comment]
@hudokkow 

Thanks for the git help! Unfortunately, I can't get past the "git merge upstream/master" step. It says I have a conflict, which I'm assuming is xbmc/interfaces/legacy/Control.cpp, but even after I fix the conflict it won't continue. Not sure what to do, I may have messed things up with whatever I tried before, no idea.

**Comment by hudokkow** [comment]
Without seeing what you're doing and git output, I can't help more but it seems you're forgetting to add the changes with **git add xbmc/interfaces/legacy/Control.cpp** after you solved the conflicts.

So it should be:
> git checkout disabledtextures
git rebase master
<<<<<< solve conflicts
git add xbmc/interfaces/legacy/Control.cpp
git rebase --continue
git push -f

Anyway, I cherry-picked your commits and rebased on master. See https://github.com/hudokkow/xbmc/commits/disabledtextures Only conflict I could see is Control.cpp, everything else applies cleanly.

**Comment by bryanbrazil** [comment]
@hudokkow 

I give up, I'm thinking git is one of those things I'm never going to understand. I wasn't able to get to rebase, couldn't get past merging upstream/master as mentioned above. Git said i had to do a pull first, so just did that and was able to get through the first set of steps. Now I get a multitude of conflicts when trying to rebase on the disabledtextures branch. Not sure if I messed up the master branch or what. Might be best if one of the devs takes this over. :(

**Comment by hudokkow** [comment]
@bryanbrazil, closing this one in favour of #7505

**Pull request closed without merging**
