### PR TITLE
[music videos] adding "All albums" option

### PR DESCRIPTION
**Pull request by sialivi**
Adds the missing "All albums" option when browsing Music Videos by Artist, which was requested in [this thread.](http://forum.kodi.tv/showthread.php?tid=185443)

### CODE REVIEW

**Comment by uNiversaI** [comment]
One of these commits is too many

**Comment by Paxxi** [comment]
To clarify what I think @universal meant is that you should squish your commits into one.

**Comment by sialivi** [comment]
I might need some guidance; I haven't used Git before, so unfortunately I don't know how to do that (without possibly making an even bigger mess). Sorry for the inconvenience.

**Comment by uNiversaI** [comment]
Thers a few ways to do this. One way is.

1 ) open a terminal in your git master branch and issue these commands:

```
git checkout master
git rebase -i HEAD~2
```

shortly after your text editor will open up with the two commits ontop and some comments below:
```
pick   [music videos] adding "All albums" option 	       5f8ada7
pick   Merge pull request #1 from sialivi/sialivi-patch-1   268444c

# Rebase 5f8ada7..268444c onto befef23
#
# Commands:
#  p, pick = use commit
#  r, reword = use commit, but edit the commit message
#  e, edit = use commit, but stop for amending
#  s, squash = use commit, but meld into previous commit
#  f, fixup = like "squash", but discard this commit's log message
#  x, exec = run command (the rest of the line) using shell
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out

````
pay attention to this part on that text file

***# If you remove a line here THAT COMMIT WILL BE LOST.***

2) So you remove the line you dont want from that text file and save it then close editor down.
 ***Hint***Remove this line  ***Merge pull request #1 from sialivi/sialivi-patch-1   268444c***

Git will do some work and that removes the unwanted commit.

Then push chnages which updates this PR automatically by issuing: :

```git push -f```

***note:***
You can rebase onto master origin and push so it updates your branch as well
```
git pull --rebase master origin
git push -f
```

that should do it, there's several ways how to do this I suggest you brush up by doing some reading and practising.

**Comment by sialivi** [comment]
@uNiversaI Sorry for the late reply, I'm hospitalized for an extended period of time. Thanks for the detailed steps, unfortunately I'm not set up to perform them from my tablet. I see there's already a rc1 ticket, so chances are that I won't be discharged from hospital in time to fix this. Maybe it's possible for some other kind soul to do it.

**Comment by uNiversaI** [comment]
Ill see about cherry picking these commits and pushing them on your behalf.

**Comment by sialivi** [comment]
@uNiversaI That would be most appreciated, if it's not too late now that RC2 is out.

**Comment by uNiversaI** [comment]
@sialivi Its not up to me I will backport to isengard if asked IMO features wont be accpted after feature freeze and you took your sweet time with this.

**Pull request closed without merging**
