### PR TITLE
cppcheck performance fixes in win32/

### PR DESCRIPTION
**Pull request by tobbi**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
Doesn't compile 

http://jenkins.kodi.tv/job/WIN-32/3307/console

**Comment by tobbi** [comment]
Okay, will check!

**Comment by MartijnKaijser** [comment]
Let's try again 
jenkins build this please

**Comment by tobbi** [comment]
I didn't change anything yet. I doubt something has improved in the meantime.

**Comment by MartijnKaijser** [comment]
well our builder acts up sometimes. that' s why i redid it
http://jenkins.kodi.tv/job/WIN-32/3352/console

**Comment by tobbi** [comment]
Can you please try one more time? I *believe* the reason why this failed was because I accidentally misspelled something.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by tobbi** [comment]
That seems to have worked. Merge please?

**Pull request merged**
