### PR TITLE
[Confluence] update weatherfanart support for jarvis

### PR DESCRIPTION
**Pull request by ronie**
confluence supports weather fanart by manually downloading, installing and configuration using the instructions found in a sticky on the forum.

far from ideal imo. let's make things a bit easier, since we can use image resources in jarvis.

### CODE REVIEW

**Comment by phil65** [comment]
+1, no-brainer.

**Comment by un1versal** [comment]
Thank you, Thank you., Ill test this asap.

Isnt this locking the choices to resource.images.weatherfanart.multi only?
 I prefer the multi in any case but what if other people install ```resource.images.weatherfanart.prairie ``` or ``` resource.images.weatherfanart.simple ``` for instance?

**Comment by un1versal** [comment]
+1  
Crashes are not gone, so http://trac.kodi.tv/ticket/16314 soon as I added this crashes are back weather fanart images are for some reason crashing Kodi.

However Weather fanart images now work with ```resource.images.weatherfanart.multi```, but as I suspected and tested with other weather fanart addons, it wont work at all.

Slight offtopic: I suspect any image resource addons that are specifically locked to one specific addon like #8105 will only also work with that one only.

Personally Im OK with these *defaults*, but maybe put something in the addon descriptions to let users know? Unless of course there's a clever way to work around that. :grinning:

**Comment by ronie** [comment]
confluence only supported weather packs with multiple images for each weather condition.
there's only one such pack available. so nothing's changed in that regard.

**Pull request merged**
