### PR TITLE
[docs] Fixes for doxygen 1.8.17

### PR DESCRIPTION
**Pull request by enen92**
## Description
Python API seems broken in doxygen 1.8.17 (see for instance: http://alwinesch.github.io/group__python__xbmc.html). Seems like html definitions in ALIAS don't play well with doxygen-based format in the same line (e.g. in `@brief` definitions). In this PR:

- Define the line break (`<hr>`) as part of the alias for python_func as it is common to all definitions and is the main cause of the breakage

- Fix the infolabel table (got broken again somewhere in the matrix development cycle)

- Other minor minimal typo/fixes found while fixing the issue

## Motivation and Context
Fix the issue reported by @AlwinEsch . Hopefully at some point we can drop codedocs in favor of another alternative that doesn't use such an old version of doxygen.

## How Has This Been Tested?
compile and tested. You can confirm all is working like before by visiting the result in: https://codedocs.xyz/enen92/xbmc/group__python__xbmc.html

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by phunkyfish — APPROVED** [review]
Looks good.

**Comment by phunkyfish** [comment]
Can this go in @enen92 ?

**Comment by enen92** [comment]
ping @AlwinEsch

**Review by AlwinEsch — COMMENTED** [review]
Looks good :+1: 

Only this few places:
- https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-addon-dev-kit/doxygen/Doxyfile#L247 
  - Can you add the `<hr>` here too
- https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-addon-dev-kit/include/kodi/General.h#L642 
  - Can you remove the line here too (no idea why I added there :thinking:)
- https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-addon-dev-kit/include/kodi/AudioEngine.h#L125 
  - Remove the line with `/// -----------`
  - I do also remove on my PVR changes, thought to have them, for prevent of line add, on all `@copydetails` places (and not thought about the new version).
- https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-addon-dev-kit/include/kodi/AudioEngine.h#L270
  - Remove the line `**Audio engine format information:**` complete

I must also also look in my C++ parts that everywhere on class functions the group add is correct. Think to create, if I find, itself a request about.

**To stupid that they make in a patch version of doxygen so big changes!!! :gun::unamused:**
Thanks a lot, for your fixes about!

Funny, an seems a good bug (or maybe thought as feature :smile: :smirk:) is that doxywizard shows another character size on his log, if something like the `--------------------` error present:
Bildschirmfoto vom 2020-05-11 14-02-38

After remove of line by General.h it was there everywhere in right size.

**Comment by AlwinEsch** [comment]
Found another bug where was in 1.8.16.
Here about code example end need a new line added between https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/legacy/ListItem.h#L1043

The:
```cpp
      /// ~~~~~~~~~~~~~
      ///-----------------------------------------------------------------------
```

**Comment by enen92** [comment]
Finally found some time to address your extra requests @AlwinEsch. Please do a quick check if you have time.
I plan to merge it tomorrow if jenkins is happy (no code changes here).

**Review by AlwinEsch — APPROVED** [review]
Have currently not direct a PC to test, but looks good to me and much other (not version related) fixed.
👍

**Pull request merged**
