### PR TITLE
[addons] show progress of repository updates

### PR DESCRIPTION
**Pull request by tamland**
Adds a background dialog indicating the progress of 'Check for updates' after it was moved to the side menu in #6602 and all visual feedback removed as a result of that.

cc @stefansaraev, @Montellese for review.

### CODE REVIEW

**Comment by stefansaraev** [comment]
thanks much for this. unforortunately I wont be able to test this before next tuesray

**Comment by tamland** [comment]
Found some more bugs here, and changed the ShouldCancel calls as you said @Montellese and added back those 700 (it's hardly that important). How are you doing on that testing @stefansaraev;)

**Comment by stefansaraev** [comment]
@tamland first test was good, all working as expected, but I didnt comment here to avoid spaming all devs, as @Montellese had comments. will retest again tonight. thanks

**Comment by tamland** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
@Montellese @mkortstiege something we could merge for 15.0?

**Comment by mkortstiege** [comment]
Not commenting on code, but what about the new strings? Do we want/allow new ones at this point?

**Comment by MartijnKaijser** [comment]
We have language addons so they can be updated at any time after release.

**Comment by stefansaraev** [comment]
@tamland plans for this? I am using it for like month and everything seems to be ok.

**Comment by tamland** [comment]
Technically it's a feature, but even api changes went in in beta 2 so who knows. If @Montellese is ok with the code now, it's ok by be.

**Comment by tamland** [comment]
jenkins build this please

**Comment by Montellese** [comment]
I'm ok with the changes but after seeing all the issues we have with the libCEC bump I've become cautious again concerning merging anything but obvious bug fixes during beta / RC.

**Comment by MartijnKaijser** [comment]
i've had it in my OE builds and Android as well. No issues so far but i'll trust your opinion to merge or not. It's no deal breaker if not included

**Comment by zag2me** [comment]
Would be "nice to have", I just came up against this while having a problem update an add-on

**Comment by arnova** [comment]
This is at least partially a bug-fix. Perhaps we should at least merge the parts that fix actual bugs.

**Pull request merged**
