### PR TITLE
Expose VERSION_CODE and GIT SHA to GUI

### PR DESCRIPTION
**Pull request by peak3d**
## Description
Currently we provide a long and short Kodi version to the GUI. With this PR the GUI / skin can build the full version string with own formatting.

## Motivation and Context
During discussions regarding versioning we worked out that it makes sense to expose VERSION_CODE defined here: https://github.com/xbmc/xbmc/blob/master/version.txt#L8 as it is already used for android and windows release management. In future VERSION_CODE changes will result in a new build stored on our mirrors.
To let users provide the VERSION_CODE in bug reports, it should be printed in settings::SystemInformation and also in kodi.log file.

In Estuary version + git sha string was already too long to display, and it got worse after adding version_code to it. 

## Open questions
- Does such a change need a GUI API version bump?

## How Has This Been Tested?
Start kodi, open / review settings::SystemInformation

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [X] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Comment by DaveTBlake** [comment]
Thanks for this @peak3d . Small desc correction, we have been using the version code in our release process to both Play store and Windows store for some time, but had no way to expose this information  to the user or see it in their debug logs. It is certainly something easier for users to recognise and report than Git SHA.

If we make more use of the Play store beta testing channel then we may also need to make more use of code version increments, it will be helpful to have code version readily visible

**Comment by peak3d** [comment]
Comment updated

**Comment by ronie** [comment]
proposed estuary change, does this look ok to you?

sysinfo

**Comment by peak3d** [comment]
Great

**Review by wsnipex — APPROVED** [review]

**Pull request merged**
