### PR TITLE
[Windows] Fix vulnerability in wasapi for missing 'PKEY_Device_EnumeratorName' property

### PR DESCRIPTION
**Pull request by CrystalP**
## Description

Same fix as #25648, for the WASAPI sink this time. Modified the IsUSBDevice() function to test for VT_EMPTY after retrieving the property, as described in MS doc, and don't attempt to use the invalid pointer.

Also silenced a few VS warnings in struct AEWASAPIDeviceWin32 function definitions.

## Motivation and context

The WASAPI sink is affected by the same problem that required a fix with #25648. It calls a IsUSBDevice() function that queries the property PKEY_Device_EnumeratorName, but it's not provided with RDP connections.

testing of @thexai showed that wasapi can't be used with RDP (maybe the exclusive mode?) so it's not going to cause real crash but it's still a good idea to include protection in the code, and for consistency.

## How has this been tested?

Without RDP still works the same.
@thexai tested RDP and wasapi can't be used so no impact either.

## What is the effect on users?

None.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CrystalP** [comment]
unrelated TV OS build error, the PR touches a Windows-only file?

Jenkins build this please

**Review by thexai — APPROVED** [review]
The changes are correct. Even so, it doesn't crash without this PR and WASAPI + RDP. I don't remember the exact details but I already tested it at the time.

**Comment by thexai** [comment]
Just out of curiosity, are there any reports of crashes due to this (WASAPI + DRP) on the master or Omega branch?

**Comment by CrystalP** [comment]
In the original PR you wrote that connecting with RDP makes Kodi reopen AE and default to DirectSound, causing the crash.

Wasapi has same vulnerable code, though it's less likely to be triggered: Kodi could be started after RDP is connected with Wasapi configured as output, or output could be changed from default DS to Wasapi.

I'm not aware of actual crashes but kept a note that this should be cleaned up. In theory all GetValue() for strings could cause the same problem but I wanted to focus the change.

I'm not a RDP user and don't particularly care about the backport. The fix seemed low-risk.

**Comment by thexai** [comment]
> Kodi could be started after RDP is connected with Wasapi configured as output, or output could be changed from default DS to Wasapi.

Already tested this scenario --> Not crash

Maybe next weekend I'll do some testing to find out why, but it's not a priority right now.

**Comment by CrystalP** [comment]
> Already tested this scenario --> Not crash
>Maybe next weekend I'll do some testing to find out why, but it's not a priority right now.
>Maybe is not possible open WASAPI in exclusive mode in RDP then WASAPI is not usable --> not crash

Maybe. I didn't see the DirectSound crash first hand and thought that it was happening in the FromW call, but maybe that wasn't it.

Take your time. I'm preparing a DirectSound refactor but it doesn't depend on this.

**Comment by thexai** [comment]
Tested and the reason of no crash is the code is not reached because WASAPI is not usable with remote desktop:

```
2024-12-15 13:15:29.475 T:11384    info <general>: CActiveAESink::OpenSink - initialize sink
2024-12-15 13:15:29.477 T:11384 warning <general>: CAESinkWASAPI::InitializeExclusive: format AE_FMT_FLOAT not supported by the device - trying to find a compatible format
2024-12-15 13:15:29.477 T:11384 warning <general>: CAESinkWASAPI::InitializeExclusive: Input channels are [FL, FR] - Trying to find a matching output layout
2024-12-15 13:15:29.790 T:11384 warning <general>: AESinkWASAPI: Match only number of audio channels as fallback
2024-12-15 13:15:30.087 T:11384   error <general>: CAESinkWASAPI::InitializeExclusive: Unable to locate a supported output format for the device.  Check the speaker settings in the control panel.
2024-12-15 13:15:30.087 T:11384    info <general>: CAESinkWASAPI::Initialize: Could not Initialize Exclusive with that format
2024-12-15 13:15:30.087 T:11384   error <general>: CAESinkWASAPI::Initialize: WASAPI initialization failed.
```

Anyway, the PR is fine and you can merge it whenever you want.

**Comment by CrystalP** [comment]
OK thanks for the testing. It's more consistent that way even though not strictly required. There won't be a surprise if wasapi non-exclusive ever happens.
Modified title and description of the PR. No backport.

**Pull request merged**
