### PR TITLE
[Estuary] fix loss of focus and navigation on the Home screen

### PR DESCRIPTION
**Pull request by Voyager1**
## Description

This fixes a rare issue that seems to occur with Estuary, on the home screen.
Sometimes, when returning to the home screen, apparently no control has focus anymore and keyboard or remote control navigation doesn't work anymore. One can still "hear" the clicks but no visible response...

## Motivation and Context

The issue is that some button (that is invisible), part of the TopBar, gets the focus and performs no function. Arrow keys aren't able to jump out of the topbar and the (invisible) button stays focused. The button doesn't seem to have a function either. Without mouse controls it's impossible to navigate the UI from that point on.

It's easy to reproduce this problem if you have a keyboard that has a "internet homepage" key: when in the homescreen, press the keyboard key "internet homepage" and watch the focus go away. Try to navigate, nothing works anymore.

The solution was to remove this control, because it doesn't serve any apparent function.

## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by phil65** [comment]
That invisible button is useful for touch control (allows going back via tapping in top-left corner)
What happens internally when pressing the "internet homepage" key?

**Comment by Voyager1** [comment]
Debug Print: CInputManager::HandleKey: 0 (0xf200, obc-61697) pressed, action is
Debugging leads to resolution of action ID=159 (FirstPage)
GUIBaseContainer.cpp:375 SelectItem(0)
...
the next time, the focused control is this (invisible) button and navigation using arrow keys has no effect.

**Comment by Voyager1** [comment]
@phil65 - I think I have found a bug in Application that may be the root cause of this:
https://github.com/xbmc/xbmc/blob/master/xbmc/Application.cpp#L326
break; statement is missing which causes the setfocus to be called when that's not what we want. Putting a break there also seems to fix the issue...

**Comment by phil65** [comment]
cool, thx.
If that doesnt work out, you can try adding <visible>!Window.IsActive(home)</visible> to that button control instead of removing it.

**Comment by Voyager1** [comment]
@phil65 - the code fix in #13359 fixes the issue indeed, however, with mouse controls enabled, I can still reproduce the issue in the following way: Home screen, mouse click on top left corner, try navigating with cursor keys...
Then I tried to add the `<visible>` tag as per your suggestion, and that fixes the issue completely. I'll update this PR with that commit.

**Comment by Voyager1** [comment]
@phil65 updated and tested.

**Review by phil65 — APPROVED** [review]

**Pull request merged**
