### PR TITLE
fix skin variable parsing: dont skip if element text is empty

### PR DESCRIPTION
**Pull request by tamland**

### CODE REVIEW

**Comment by BigNoid** [comment]
+1 I expect it to stop if the condition is met, no matter if the value is empty. Tested and works as intended.

**Comment by ronie** [comment]
great, thx!

**Comment by tamland** [comment]
jenkins build and merge

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by phil65** [comment]
Late thx, this was the reason I think why I put "-" in there instead.

**Pull request merged**
