### PR TITLE
[PVR] Fix trac17246 - another approach

### PR DESCRIPTION
**Pull request by ksooo**
This is a fix for trac 17246: http://trac.kodi.tv/ticket/17246

Completely new approach this time, which should no longer lead to crashes the previous approach has caused. ;-)

The gist of the fix is to obtain and remember the pointer to the extended progress bar dialog instance early (PVR Manager init), avoiding the deadly <code>g_WindowManager.GetWindow()</code> call.

I discovered other scenarios which could lead to the same deadlock (in <code>CPVRMananger::ShowProgressDialog(string,int)</code>)which are are also fixed now.

The stack trace of one of the possible deadlocks:
kodi-frozen

@Jalle19 for review?

### CODE REVIEW

**Review by Jalle19 — COMMENTED** [review]
If it works, sure. I'm wondering if it would make sense to remove this feature altogether since most backends AFAIK are able to supply channel icons on their own.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
We have positive feedback from the reporter of the crashes the first approach introduced.

**Comment by ksooo** [comment]
The submitter of the trac ticket got a a test build, did runtime testing, and confirmed that the original issue is solved, no crashes.

**Pull request merged**
