### PR TITLE
[epg] fix use of new epg database column iYear

### PR DESCRIPTION
**Pull request by xhaggi**
As pointed out by @Uukrull this will fix the wrong value list for INSERT/UPDATE and the use of the wrong column name for column iYear.

@Uukrull mind taking a look or test if possible thanks.

### CODE REVIEW

**Comment by xhaggi** [comment]
@Jalle19 or @ksooo also take a look.

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by Jalle19** [comment]
Looks okay now (I hope)

**Comment by Uukrull** [comment]
I applied the fix yesterday and it works as it should (without this, the update EPG thread crashed on my W7 machine).

**Pull request merged**
