### PR TITLE
[gui] don't switch to another window if there are active modal dialogs

### PR DESCRIPTION
**Pull request by xhaggi**
With this Kodi behaves like every other (desktop) application where you can't jump over to another
window if you have open modal dialogs. This only prevents the user from switching to another window which means only if the user actively trigger the window change by a remote key or built-in.

Now we can safely remove the call to `CloseModalDialog()` which introduced some regressions in combination with our python dialogs. Which is done in the first commit.

@mkortstiege @Montellese mind taking a look
@ruuk your python test scripts works as expected
@AlwinEsch as a hint

### CODE REVIEW

**Comment by mkortstiege** [comment]
+1 for this behavior (as already wrote on IRC).

**Comment by Montellese** [comment]
Looks much cleaner than simply closing all dialogs.

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by mkortstiege** [comment]
Damn github today .. jenkins build this please.

**Comment by xhaggi** [comment]
let's do it once again .. jenkins build this please

**Comment by ruuk** [comment]
Tested with the HDHomeRun addon where I originally had issues, and all works as expected now.

**Comment by xhaggi** [comment]
any objections? if not I'll merge this in tomorrow.

**Comment by mkortstiege** [comment]
No objections from my side as long it's part of alpha2 ;)

**Comment by AlwinEsch** [comment]
Looks nice and good way, thank a lot.

**Comment by afedchin** [comment]
I think this breaks transition to fullscreen video on start stereoscopic movie with stereo mode select dialog. Now need switch fullscreen manually after selecting stereo mode .

**Comment by FernetMenta** [comment]
not having looked into the details but this feels like an issue of the selection dialog. either make it non-modal or open the dialog as modal after the switch to full screen.

**Comment by Lunatixz** [comment]
This PR breaks fullscreen video transitions, and keeps videowindow control type workarounds from working, since you can't call another window while one is active...

further discussion in forum post.
http://forum.kodi.tv/showthread.php?tid=227733&pid=2020203#pid2020203 

I hope this push can be reversed...

**Comment by afedchin** [comment]
this fixed already by #7125

**Comment by Lunatixz** [comment]
Thanks :)

**Comment by ronie** [comment]
is this also available to skins or only kodi internally?

the activatewindow() builtin doesn't have the force option:
https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/Builtins.cpp#L301

**Comment by ruuk** [comment]
> is this also available to skins or only kodi internally?
> 
> the activatewindow() builtin doesn't have the force option:
> https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/Builtins.cpp#L301

I was just looking at the same thing, because this affects the HDHR addon as well. Wondering what the chances of a pull request adding that could make it into Isengard. Also, fwiw I don't think this change (#6828) is the one that caused the issue that is fixed by #7125 - at least for the issues that Lunatixz and I are having. I think it was a later one, as I tested this pull request initially.

**Comment by Lunatixz** [comment]
I'm having an unrelated problem, ruuk... Issue I'm having now is with domodel enforcement. Keeping me from activating multi window.

**Comment by xhaggi** [comment]
> is this also available to skins or only kodi internally?

only for internal usage atm as a workaround for some situation.

@ruuk and @Lunatixz could you please provide your scripts and detailed explanation where to find issue. I'll take a look if something is wrong. As @ronie said, you need to close all modal dialogs before opening a new window, this is because a modal would stay on top of the newly opened window. That's the main reason why we added a check for active modal dialogs before activating the new window.

**Comment by ruuk** [comment]
I'm not sure what was changed, but in the Isengard beta, I can no longer activate the fullscreen video from a dialog window (this still worked with this pull request). In fact I believe that previously starting video fullscreen automatically activated the fullscreen video window, and no longer does so. The desired behavior in the addon is to have the dialog remain above and overlay the fullscreen video. Compiling from master today, I didn't seem to have the issue I was having in the Isengard beta - I noticed this when testing out a [ForceAcvtivateWindow builtin] (https://github.com/ruuk/xbmc/commit/085b586716443cbd131888d15ddc188a4b89cfc6) I was testing out.

I'm going to check this out more tomorrow to see if I can figure out what's up.

In any case, maybe we ultimately need a new dialog meant specifically for overlaying video, because the current method of doing this seems to be at odds with the direction being taken with modal dialogs. Of course this doesn't help with the Isengard release.

I'm not quite clear on the git strategy we use, but if master represents the next Isengard build, then it would appear that the issue I have is gone. Not sure if @Lunatixz issue has the same cause.

**Comment by Lunatixz** [comment]
My original issue that I shared with @ruuk was resolved in kodi nightlies, but my new issue is the domodel enforcement, My plugin opens a windowxmldialog, then <onload> another window. The main window has to remain open... while it calls a workaround for the videowindow control type.

More info here:
http://forum.kodi.tv/showthread.php?tid=227733&pid=2020196#pid2020196

**Comment by Lunatixz** [comment]
Any activity on this issue? I need to use onload to activate another window while a domodel is open.

Activating window ID: 19506
08:35:21 T:10524    INFO: Activate of window '19506' refused because there are active modal dialogs

info can be found here: http://forum.kodi.tv/showthread.php?tid=227733&pid=2020196#pid2020196
I can also provide any information you need...

**Comment by xhaggi** [comment]
you need to close the modal before you can open the window. please provide some further info what do you want to do + pastebin the code snippet

**Comment by Lunatixz** [comment]
I'm trying to open a resized videowindow control type from a windowxmldialog domodel... For whatever reason traditional windowxml videowindow control type parameters never worked for a dialog window. So I use this workaround : 
http://forum.kodi.tv/showthread.php?tid=159445&pid=1368943#pid1368943
and call it with onload :
https://github.com/Lunatixz/script.pseudotv.live/blob/master/resources/skins/Default/1080i/script.pseudotv.live.EPG.xml#L3

This has worked perfect for the last few major builds of XBMC/Kodi till 15... and it looks like the domodel restrictions is the issue.

**Comment by Lunatixz** [comment]
beta 2 and no change, closing current domodel is not an option... so where does that leave me? help would be great

**Comment by Lunatixz** [comment]
I'm probably not explaining my problem well enough? At least I hope thats why nobody is looking into this... I admit my knowledge in kodis gui controls are limited. From my understanding of the changes there is no way to activate another window while another domodel is open... This creates a unique problem for my plugin which features a videowindow control that is activated onload from another xml domodel. If someone can provide either a solution for my problem or commit a change to Kodi that fixes the issue.. that would be great! Thanks

**Comment by phil65** [comment]
If you need to change the window beneath a dialog, then why not close dialog, change window, and open dialog again?
Also What do you mean with "domodel"? From context I would guess you mean a dialog?

**Comment by Lunatixz** [comment]
@phil65 there is nothing to change, i'm calling a blank window with no parameters, take a look at this: http://forum.kodi.tv/showthread.php?tid=159445&pid=1368943#pid1368943 it explains what i'm doing...

**Comment by Lunatixz** [comment]
So i've tried every possible solution... it just seems to me that if you have a fullscreen video and a windowsxmldialog it's not possible to use a sizable videowindow control type without using the aforementioned hack. Which now because of domodel restrictions isn't possible in 15.

Is there anyone here that could provide me a solution? My basic need is to have a videowindow control type that is sizable from a windowsxmldialog "EPG" that is overlaid over another windowsxmldialog "Overlay". I can not close the previous window... it needs to remain open at all times...

HELP! it's pathetic that I need to go to this level for support... not one dev can spare a minute to help?

**Pull request merged**
