### PR TITLE
events: only log incompatible/broken add-ons that are installed

### PR DESCRIPTION
**Pull request by Montellese**
This avoids events for add-ons that have been marked incompatible/broken but are only available in a repository and haven't been installed by the user.

### CODE REVIEW

**Comment by tamland** [comment]
You only log events for unmet dependencies, not when it was marked broken or unbroken by repository. What you want is to remove the `if markedAsBroken` and rather check `newAddon->Props().broken`. It's either `DEPSNOTMET`, custom reason or empty (then it's unbroken.)

**Comment by Montellese** [comment]
But `newAddon->Props().broken` by itself doesn't tell me if the state has changed right?

**Comment by tamland** [comment]
Ah nope. Need to check that as well. (the block right above does that)

**Comment by Montellese** [comment]
@tamland: Could you take another look at the first commit?
@MartijnKaijser @ronie: I added a second commit that should fix the problems with the incompatible addons due to unmet dependencies.

**Comment by ronie** [comment]
confirmed working (after deleting the addon db).

**Comment by Montellese** [comment]
Updated again and confirmed by @tamland. jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
