### PR TITLE
[Fix][settings] Fix min/max constraints and language list for subs download

### PR DESCRIPTION
**Pull request by ace20022**
@Montellese for review. https://github.com/xbmc/xbmc/commit/a09a0bd42fd8000125435df4c3626ed07e0c4a0e leads to a almost complete rebuild. I could also change the xml file, but I wasn't sure about the naming conventions.

Also the maximum constraints that exist are rather arbitrary, imo.

### CODE REVIEW

**Comment by ace20022** [comment]
Ping @Montellese Just in case you confused the prs ;)

**Comment by Montellese** [comment]
I would prefer changing the settings XML files (all of them) because all other attributes and tag names are all lower case as well.
Apart from that this looks good. I was actually wondering why this relyed on the installed languages when I did the language addons PR.

**Comment by ace20022** [comment]
> I was actually wondering why this relyed on the installed languages when I did the language addons PR.

git blame told me that it wasn't you ;)

> all other attributes and tag names are all lower case as well.

I was just not sure because it is the only two word attribute, will change it

**Comment by ace20022** [comment]
@Montellese changed.

There are some other flaws:

* users with more than max items will get the default setting when this is merged.
* a user can select more than max items. When clicking ok, the (new) list/setting is not saved, but there's no indication/message why.
* with ```streamlanguages ``` we also get ```original``` and ```default``` which do not work (I guess).
Not sure if that justifies a new method (cf. https://github.com/xbmc/xbmc/blob/master/xbmc/LangInfo.cpp#L1129).

**Comment by Montellese** [comment]
> * users with more than max items will get the default setting when this is merged.

Maybe we can implement an update logic? Is there any reason why a user can only choose 3 languages anyway?

>* a user can select more than max items. When clicking ok, the (new) list/setting is not saved, but there's no indication/message why.

Yes this has always been like that and I never liked it but some people desperately wanted list settings.

> * with streamlanguages we also get original and default which do not work (I guess). Not sure if that justifies a new method (cf. https://github.com/xbmc/xbmc/blob/master/xbmc/LangInfo.cpp#L1129).

Better than showing options that don't make any sense.

**Comment by ace20022** [comment]
As said, all max item settings are unnecessary imo. I'll remove it in this case. And I'll a new method.

**Comment by ace20022** [comment]
@Montellese done. Found some other strange things. I'll use a new pr when I've investigated them more closely.

**Comment by Montellese** [comment]
Thanks, looks good. jenkins build this please

**Comment by ace20022** [comment]
jenkins build this please

**Pull request merged**
