### PR TITLE
Add harfbuzz packages

### PR DESCRIPTION
**Pull request by Paxxi**
built with -DHB_HAVE_FREETYPE=ON

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by enen92 — APPROVED** [review]

**Comment by enen92** [comment]
@naseef can you check if this works well with your new PR on windows? Thanks

**Comment by enen92** [comment]
Jenkins build this please

**Comment by naseef** [comment]
> @naseef can you check if this works well with your new PR on windows? Thanks

It seems the package is not uploaded in the mirror. 

Getting
```
harfbuzz-2.8.0-x64-v142-20210531.7z|Download of http://mirrors.kodi.tv/build-deps/win32/harfbuzz-2.8.0-x64-v142-20210531.7z failed
One or more packages failed to download
ERROR: Not all formed packages are ready!
```

**Comment by lrusak** [comment]
jenkins build this please

**Comment by naseef** [comment]
PR #19765 build fails with the error on Windows x64
```
harfbuzz.lib(harfbuzz.obj) : error LNK2019: unresolved external symbol __imp_DWriteCreateFactory referenced in function
 _hb_directwrite_shaper_face_data_create [C:\Users\xxxxxx\kodi\kodi-build.x64\kodi.vcxproj]
harfbuzz.lib(harfbuzz.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4 [C:\Users\xxxxxx\kodi\kodi-build
.x64\kodi.vcxproj]
harfbuzz.lib(harfbuzz.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4 [C:\Users\xxxxxx\kodi\kodi-bui
ld.x64\kodi.vcxproj]
C:\Users\xxxxxx\kodi\kodi-build.x64\Release\kodi.exe : fatal error LNK1120: 3 unresolved externals [C:\Users\xxxxxx\kodi\kodi
-build.x64\kodi.vcxproj]
```

**Comment by naseef** [comment]
> PR #19765 build fails with the error on Windows x64
> 
> ```
> harfbuzz.lib(harfbuzz.obj) : error LNK2019: unresolved external symbol __imp_DWriteCreateFactory referenced in function
>  _hb_directwrite_shaper_face_data_create [C:\Users\xxxxxx\kodi\kodi-build.x64\kodi.vcxproj]
> harfbuzz.lib(harfbuzz.obj) : error LNK2001: unresolved external symbol __CxxFrameHandler4 [C:\Users\xxxxxx\kodi\kodi-build
> .x64\kodi.vcxproj]
> harfbuzz.lib(harfbuzz.obj) : error LNK2001: unresolved external symbol __GSHandlerCheck_EH4 [C:\Users\xxxxxx\kodi\kodi-bui
> ld.x64\kodi.vcxproj]
> C:\Users\xxxxxx\kodi\kodi-build.x64\Release\kodi.exe : fatal error LNK1120: 3 unresolved externals [C:\Users\xxxxxx\kodi\kodi
> -build.x64\kodi.vcxproj]
> ```

I think the issue is caused by enabling direcwrite support and [this patch](https://github.com/Paxxi/harfbuzz/commit/bcd28eaf3339b6b6762a7914ee7a9e734dccfa42#diff-0ed175486367eab57a67582c28e91f0f01412c0b1686f717427c940aa18ac560). I'm curious wheather  harfbuzz in libass need directwrite support?

**Comment by Paxxi** [comment]
Sorry about that. Built new ones that are dynamically linked and and tested them on x64 with your PR, linked and ran.
Waiting on getting them uploaded to mirrors.

**Comment by naseef** [comment]
@Paxxi  I hope I'm not disturbing you, when the package will be uploaded to the mirrors?

**Comment by lrusak** [comment]
@naseef packages are uploaded now.

**Comment by enen92** [comment]
jenkins build this please

**Comment by naseef** [comment]
PR  #19765 working fine with Windows x64 build. ( Tested with Malayalam language)

**Review by enen92 — APPROVED** [review]

**Pull request merged**
