### PR TITLE
[docs] Add pvr.seek to possible actions of SliderControl

### PR DESCRIPTION
**Pull request by enen92**
## Description
Found while working on other issue. This was added in https://github.com/xbmc/xbmc/pull/14363.
PR adds also revision info for the control.

@DaVukovic mind adding to the wiki if this is merged?

## Motivation and Context
Complete docs.

## How Has This Been Tested?
compile & see

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [x] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by DaVukovic** [comment]
Will do :+1:

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by Rechi** [comment]
jenkins build this please

**Comment by enen92** [comment]
@Rechi just out of curiosity, why did you remove the No-Jenkins label if the only changed file is a dox file? Cheers

**Comment by Rechi** [comment]
@MartijnKaijser wanted jenkins to build this PR. Adding `No-Jenkins`-label only is useful directly at PR creation as otherwise the auto PR build is triggered immediately.
Also I included now all .dox files in the xbmc folder to the auto exclude files in jenkins. That means if only excluded files are changed in a PR jenkins will automatically ignore the PR. So no need to add the ` No-Jenkins`-label on new doxy only PRs.

**Pull request merged**
