### PR TITLE
Enable udp protocol to carry options

### PR DESCRIPTION
**Pull request by a1rwulf**
See title.

### CODE REVIEW

**Comment by a1rwulf** [comment]
@FernetMenta any objections to this?

**Comment by FernetMenta** [comment]
why is this needed?

**Comment by a1rwulf** [comment]
I use iptv.simple with my digital devices octopus multicast streamer and use custom url parameters.
This for example allows me to add a hint to the stream and skip avprobe for my TV channels.
I thought it might be useful for others as well, especially since other protocols can already have parameters.

**Comment by FernetMenta** [comment]
doesn't this just create some hidden communication channel to addons or external components? 
udp is at layer 4 (osi) and does not support paramters like https. seems you are abusing the generic udp protocol for some custom udp mulitcast protocol at the application layer.

**Pull request closed without merging**
