### PR TITLE
GUILIB: remove unnecessary threading for focus actions

### PR DESCRIPTION
**Pull request by sarbes**
## Description
The PR changes the message behavior of focus actions. It uses the faster, non-threaded codepath.

## Motivation and context
Previously, focus/unfocus actions would use the threaded message queue. The way it is set up, it would introduce a one frame delay for those messages. But skins like Estuary require those messages to reach its consumer in the same processing cycle.

Possibly fixes https://forum.kodi.tv/showthread.php?pid=2726367#pid2726367.

## How has this been tested?
Compiles and runs fine on my Linux system

## What is the effect on users?
Less resources wasted, depending on the scene. Possibly less jank.

## Screenshots (if appropriate):
Previously, selecting the Caminandes movie by pressing down would result in loading the Tears of Steel fanart for one frame. Only in the next frame, the appropriate fanart would load.
image

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by sarbes** [comment]
jenkins build this please

**Comment by neo1973** [comment]
With this change I run into an endless recursion when entering the settings screen of the _Copacetic_ skin:

<details>
<summary>Backtrace</summary>

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007fb0c76a5463 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:78
#2  0x00007fb0c764c120 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007fb0c76334c3 in __GI_abort () at abort.c:79
#4  0x00005f12126b9101 in __sanitizer::Abort() ()
#5  0x00005f12126b6d3d in __sanitizer::Die() ()
#6  0x00005f12126978df in __asan::ScopedInErrorReport::~ScopedInErrorReport() ()
#7  0x00005f1212694031 in __asan::ReportDeadlySignal(__sanitizer::SignalContext const&) ()
#8  0x00005f1212692e36 in __asan::AsanOnDeadlySignal(int, void*, void*) ()
#9  <signal handler called>
#10 0x00005f12125ede57 in ___interceptor_strlen.part.0 ()
#11 0x00005f1212af1c91 in std::type_info::hash_code (this=0x5f121b5c0400 <typeinfo for CApplicationPlayer>) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/typeinfo:121
#12 0x00005f1212af1b0e in std::type_index::hash_code (this=0x7fb0c1209260) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/typeindex:100
#13 0x00005f1212af1961 in std::hash<std::type_index>::operator() (this=0x5170000000c8, __ti=...) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/typeindex:121
#14 0x00005f1212af112a in std::__detail::_Hash_code_base<std::type_index, std::pair<std::type_index const, std::shared_ptr<IApplicationComponent> >, std::__detail::_Select1st, std::hash<std::type_index>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, false>::_M_hash_code (this=0x5170000000c8, __k=...) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/bits/hashtable_policy.h:1335
#15 0x00005f1212af0750 in std::_Hashtable<std::type_index, std::pair<std::type_index const, std::shared_ptr<IApplicationComponent> >, std::allocator<std::pair<std::type_index const, std::shared_ptr<IApplicationComponent> > >, std::__detail::_Select1st, std::equal_to<std::type_index>, std::hash<std::type_index>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::find (this=0x5170000000c8, __k=...) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/bits/hashtable.h:1759
#16 0x00005f1212aefeb5 in std::unordered_map<std::type_index, std::shared_ptr<IApplicationComponent>, std::hash<std::type_index>, std::equal_to<std::type_index>, std::allocator<std::pair<std::type_index const, std::shared_ptr<IApplicationComponent> > > >::find (this=0x5170000000c8, __x=...) at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/bits/unordered_map.h:888
#17 0x00005f1212b13495 in CComponentContainer<IApplicationComponent>::GetComponent<CApplicationPlayer> (this=0x517000000098) at xbmc/utils/ComponentContainer.h:41
#18 0x00005f1212b13e20 in CComponentContainer<IApplicationComponent>::GetComponent<CApplicationPlayer> (this=0x517000000098) at xbmc/utils/ComponentContainer.h:33
#19 0x00005f1215c908db in CApplication::FrameMove (this=0x517000000080, processEvents=false, processGUI=true) at xbmc/application/Application.cpp:1736
#20 0x00005f12157c4d51 in CGUIWindowManager::ProcessRenderLoop (this=0x514000084040, renderOnly=true) at xbmc/guilib/GUIWindowManager.cpp:1480
#21 0x00005f12157a8445 in CGUIWindowManager::CloseWindowSync (this=0x514000084040, window=0x51900022e780, nextWindowID=10035) at xbmc/guilib/GUIWindowManager.cpp:1861
#22 0x00005f12157acacf in CGUIWindowManager::ActivateWindow_Internal (this=0x514000084040, iWindowID=10035, params=std::vector of length 0, capacity 0, swappingWindows=true, force=false) at xbmc/guilib/GUIWindowManager.cpp:881
#23 0x00005f12157a969e in CGUIWindowManager::ActivateWindow (this=0x514000084040, iWindowID=10035, params=std::vector of length 0, capacity 0, swappingWindows=true, force=false) at xbmc/guilib/GUIWindowManager.cpp:802
#24 0x00005f1218b89d46 in (anonymous namespace)::ActivateAndFocus<true> (params=std::vector of length 2, capacity 2 = {...}) at xbmc/interfaces/builtins/GUIBuiltins.cpp:146
#25 0x00005f1218b745f2 in CBuiltins::Execute (this=0x5f121ff2a9a0 <CBuiltins::GetInstance()::sBuiltins>, execString="ReplaceWindowAndFocus(skinsettings,4010)") at xbmc/interfaces/builtins/Builtins.cpp:158
#26 0x00005f1215cbaa15 in CApplication::ExecuteXBMCAction (this=0x517000000080, actionStr="ReplaceWindowAndFocus(skinsettings,4010)", item=std::shared_ptr<CGUIListItem> (empty) = {...}) at xbmc/application/Application.cpp:3055
#27 0x00005f1215cb6d15 in CApplication::OnMessage (this=0x517000000080, message=...) at xbmc/application/Application.cpp:3031
#28 0x00005f1215cbb891 in non-virtual thunk to CApplication::OnMessage(CGUIMessage&) () at xbmc/application/Application.cpp:3087
#29 0x00005f121579f3c2 in CGUIWindowManager::SendMessage (this=0x514000084040, message=...) at xbmc/guilib/GUIWindowManager.cpp:510
[...]
#5206 0x000057cebb4fa5a2 in CGUIWindowManager::SendMessage (this=0x514000084040, message=...) at xbmc/guilib/GUIWindowManager.cpp:510
#5207 0x000057cebaf72f8f in CGUIAction::ExecuteActions (this=0x51c00003eec0, controlID=4010, parentID=10004, item=std::shared_ptr<CGUIListItem> (empty) = {...}) at xbmc/guilib/GUIAction.cpp:89
#5208 0x000057cebb01c41e in CGUIButtonControl::OnFocus (this=0x51c00003e880) at xbmc/guilib/GUIButtonControl.cpp:410
#5209 0x000057cebb0602fa in CGUIControl::UpdateStates (this=0x51c00003e880, type=ANIM_TYPE_FOCUS, currentProcess=ANIM_PROCESS_NORMAL, currentState=ANIM_STATE_APPLIED) at xbmc/guilib/GUIControl.cpp:849
#5210 0x000057cebb062247 in CGUIControl::Animate (this=0x51c00003e880, currentTime=4416) at xbmc/guilib/GUIControl.cpp:874
#5211 0x000057cebb04941f in CGUIControl::DoProcess (this=0x51c00003e880, currentTime=4416, dirtyregions=std::vector of length 0, capacity 128) at xbmc/guilib/GUIControl.cpp:128
#5212 0x000057cebb0caa85 in CGUIControlGroup::Process (this=0x51900022e780, currentTime=4416, dirtyregions=std::vector of length 0, capacity 128) at xbmc/guilib/GUIControlGroup.cpp:96
#5213 0x000057cebb04a512 in CGUIControl::DoProcess (this=0x51900022e780, currentTime=4416, dirtyregions=std::vector of length 0, capacity 128) at xbmc/guilib/GUIControl.cpp:146
#5214 0x000057cebb4b99c1 in CGUIWindow::DoProcess (this=0x51900022e780, currentTime=4416, dirtyregions=std::vector of length 0, capacity 128) at xbmc/guilib/GUIWindow.cpp:334
#5215 0x000057cebb514cea in CGUIWindowManager::Process (this=0x514000084040, currentTime=4416) at xbmc/guilib/GUIWindowManager.cpp:1217
#5216 0x000057cebb9eee88 in CApplication::FrameMove (this=0x517000000080, processEvents=false, processGUI=true) at xbmc/application/Application.cpp:1819
#5217 0x000057cebb51ff31 in CGUIWindowManager::ProcessRenderLoop (this=0x514000084040, renderOnly=true) at xbmc/guilib/GUIWindowManager.cpp:1480
#5218 0x000057cebb503625 in CGUIWindowManager::CloseWindowSync (this=0x514000084040, window=0x51900022e780, nextWindowID=10035) at xbmc/guilib/GUIWindowManager.cpp:1861
#5219 0x000057cebb507caf in CGUIWindowManager::ActivateWindow_Internal (this=0x514000084040, iWindowID=10035, params=std::vector of length 0, capacity 0, swappingWindows=true, force=false) at xbmc/guilib/GUIWindowManager.cpp:881
#5220 0x000057cebb50487e in CGUIWindowManager::ActivateWindow (this=0x514000084040, iWindowID=10035, params=std::vector of length 0, capacity 0, swappingWindows=true, force=false) at xbmc/guilib/GUIWindowManager.cpp:802
#5221 0x000057cebe8e4f26 in (anonymous namespace)::ActivateAndFocus<true> (params=std::vector of length 2, capacity 2 = {...}) at xbmc/interfaces/builtins/GUIBuiltins.cpp:146
#5222 0x000057cebe8cf7d2 in CBuiltins::Execute (this=0x57cec5c86120 <CBuiltins::GetInstance()::sBuiltins>, execString="ReplaceWindowAndFocus(skinsettings,4010)") at xbmc/interfaces/builtins/Builtins.cpp:158
#5223 0x000057cebba15bf5 in CApplication::ExecuteXBMCAction (this=0x517000000080, actionStr="ReplaceWindowAndFocus(skinsettings,4010)", item=std::shared_ptr<CGUIListItem> (empty) = {...}) at xbmc/application/Application.cpp:3055
#5224 0x000057cebba11ef5 in CApplication::OnMessage (this=0x517000000080, message=...) at xbmc/application/Application.cpp:3031
#5225 0x000057cebba16a71 in non-virtual thunk to CApplication::OnMessage(CGUIMessage&) () at xbmc/application/Application.cpp:3087
#5226 0x000057cebb4fa5a2 in CGUIWindowManager::SendMessage (this=0x514000084040, message=...) at xbmc/guilib/GUIWindowManager.cpp:510
#5227 0x000057cebaf72f8f in CGUIAction::ExecuteActions (this=0x51c00003eec0, controlID=4010, parentID=10004, item=std::shared_ptr<CGUIListItem> (empty) = {...}) at xbmc/guilib/GUIAction.cpp:89
#5228 0x000057cebb01c41e in CGUIButtonControl::OnFocus (this=0x51c00003e880) at xbmc/guilib/GUIButtonControl.cpp:410
#5229 0x000057cebb0602fa in CGUIControl::UpdateStates (this=0x51c00003e880, type=ANIM_TYPE_FOCUS, currentProcess=ANIM_PROCESS_NORMAL, currentState=ANIM_STATE_APPLIED) at xbmc/guilib/GUIControl.cpp:849
#5230 0x000057cebb062247 in CGUIControl::Animate (this=0x51c00003e880, currentTime=4416) at xbmc/guilib/GUIControl.cpp:874
#5231 0x000057cebb04941f in CGUIControl::DoProcess (this=0x51c00003e880, currentTime=4416, dirtyregions=std::vector of length 0, capacity 128) at xbmc/guilib/GUIControl.cpp:128
#5232 0x000057cebb0caa85 in CGUIControlGroup::Process (this=0x51900022e780, currentTime=4416, dirtyregions=std::vector of length 0, capacity 128) at xbmc/guilib/GUIControlGroup.cpp:96
#5233 0x000057cebb04a512 in CGUIControl::DoProcess (this=0x51900022e780, currentTime=4416, dirtyregions=std::vector of length 0, capacity 128) at xbmc/guilib/GUIControl.cpp:146
#5234 0x000057cebb4b99c1 in CGUIWindow::DoProcess (this=0x51900022e780, currentTime=4416, dirtyregions=std::vector of length 0, capacity 128) at xbmc/guilib/GUIWindow.cpp:334
#5235 0x000057cebb514cea in CGUIWindowManager::Process (this=0x514000084040, currentTime=4416) at xbmc/guilib/GUIWindowManager.cpp:1217
#5236 0x000057cebb9eee88 in CApplication::FrameMove (this=0x517000000080, processEvents=false, processGUI=true) at xbmc/application/Application.cpp:1819
#5237 0x000057cebb51ff31 in CGUIWindowManager::ProcessRenderLoop (this=0x514000084040, renderOnly=true) at xbmc/guilib/GUIWindowManager.cpp:1480
#5238 0x000057cebb503625 in CGUIWindowManager::CloseWindowSync (this=0x514000084040, window=0x51900022e780, nextWindowID=10035) at xbmc/guilib/GUIWindowManager.cpp:1861
#5239 0x000057cebb507caf in CGUIWindowManager::ActivateWindow_Internal (this=0x514000084040, iWindowID=10035, params=std::vector of length 0, capacity 0, swappingWindows=true, force=false) at xbmc/guilib/GUIWindowManager.cpp:881
#5240 0x000057cebb50487e in CGUIWindowManager::ActivateWindow (this=0x514000084040, iWindowID=10035, params=std::vector of length 0, capacity 0, swappingWindows=true, force=false) at xbmc/guilib/GUIWindowManager.cpp:802
#5241 0x000057cebe8e4f26 in (anonymous namespace)::ActivateAndFocus<true> (params=std::vector of length 2, capacity 2 = {...}) at xbmc/interfaces/builtins/GUIBuiltins.cpp:146
#5242 0x000057cebe8cf7d2 in CBuiltins::Execute (this=0x57cec5c86120 <CBuiltins::GetInstance()::sBuiltins>, execString="ReplaceWindowAndFocus(skinsettings,4010)") at xbmc/interfaces/builtins/Builtins.cpp:158
#5243 0x000057cebba15bf5 in CApplication::ExecuteXBMCAction (this=0x517000000080, actionStr="ReplaceWindowAndFocus(skinsettings,4010)", item=std::shared_ptr<CGUIListItem> (empty) = {...}) at xbmc/application/Application.cpp:3055
#5244 0x000057cebba11ef5 in CApplication::OnMessage (this=0x517000000080, message=...) at xbmc/application/Application.cpp:3031
#5245 0x000057cebba16a71 in non-virtual thunk to CApplication::OnMessage(CGUIMessage&) () at xbmc/application/Application.cpp:3087
#5246 0x000057cebb4fa5a2 in CGUIWindowManager::SendMessage (this=0x514000084040, message=...) at xbmc/guilib/GUIWindowManager.cpp:510
#5247 0x000057cebaf72f8f in CGUIAction::ExecuteActions (this=0x51c00003eec0, controlID=4010, parentID=10004, item=std::shared_ptr<CGUIListItem> (empty) = {...}) at xbmc/guilib/GUIAction.cpp:89
#5248 0x000057cebb01c41e in CGUIButtonControl::OnFocus (this=0x51c00003e880) at xbmc/guilib/GUIButtonControl.cpp:410
#5249 0x000057cebb0602fa in CGUIControl::UpdateStates (this=0x51c00003e880, type=ANIM_TYPE_FOCUS, currentProcess=ANIM_PROCESS_NORMAL, currentState=ANIM_STATE_APPLIED) at xbmc/guilib/GUIControl.cpp:849
#5250 0x000057cebb062247 in CGUIControl::Animate (this=0x51c00003e880, currentTime=4416) at xbmc/guilib/GUIControl.cpp:874
#5251 0x000057cebb04941f in CGUIControl::DoProcess (this=0x51c00003e880, currentTime=4416, dirtyregions=std::vector of length 0, capacity 128) at xbmc/guilib/GUIControl.cpp:128
#5252 0x000057cebb0caa85 in CGUIControlGroup::Process (this=0x51900022e780, currentTime=4416, dirtyregions=std::vector of length 0, capacity 128) at xbmc/guilib/GUIControlGroup.cpp:96
#5253 0x000057cebb04a512 in CGUIControl::DoProcess (this=0x51900022e780, currentTime=4416, dirtyregions=std::vector of length 0, capacity 128) at xbmc/guilib/GUIControl.cpp:146
#5254 0x000057cebb4b99c1 in CGUIWindow::DoProcess (this=0x51900022e780, currentTime=4416, dirtyregions=std::vector of length 0, capacity 128) at xbmc/guilib/GUIWindow.cpp:334
#5255 0x000057cebb514cea in CGUIWindowManager::Process (this=0x514000084040, currentTime=4416) at xbmc/guilib/GUIWindowManager.cpp:1217
#5256 0x000057cebb9eee88 in CApplication::FrameMove (this=0x517000000080, processEvents=true, processGUI=true) at xbmc/application/Application.cpp:1819
#5257 0x000057cebb9f07ce in CApplication::Run (this=0x517000000080) at xbmc/application/Application.cpp:1865
#5258 0x000057cebac657d5 in XBMC_Run (renderGUI=true) at xbmc/platform/xbmc.cpp:61
#5259 0x000057ceb8433ab0 in main (argc=1, argv=0x7fffc8949238) at xbmc/platform/posix/main.cpp:70
```
</details>

<details>
<summary>log</summary>

```
2024-08-04 02:22:55.302 T:218371   debug <general>: Keyboard: scancode: 0x1c, sym: 0x0d (enter), unicode: 0x0d, modifier: 0x0
2024-08-04 02:22:55.303 T:218371   debug <general>: HandleKey: return (0xf00d) pressed, window 10000, action is Select
2024-08-04 02:22:55.303 T:218371   debug <general>: Activating window ID: 10004
2024-08-04 02:22:55.308 T:218371   debug <general>: ------ Window Deinit (Custom_1160_System_Idle_Window.xml) ------
2024-08-04 02:22:55.441 T:218371   debug <general>: ------ Window Deinit (Home.xml) ------
2024-08-04 02:22:55.450 T:218371   debug <general>: ------ Window Init (Settings.xml) ------
2024-08-04 02:22:55.450 T:218371    info <general>: Loading skin file: Settings.xml, load type: KEEP_IN_MEMORY
2024-08-04 02:22:55.469 T:218371   debug <general>: Skin file /home/mark/.kodi/addons/skin.copacetic/16x9/Settings.xml loaded in 18.80 ms
2024-08-04 02:22:55.469 T:218371   debug <general>: Alloc resources: 19.34 ms (18.88 ms skin load)
2024-08-04 02:22:55.473 T:218371   debug <general>: Activating window ID: 10035
2024-08-04 02:22:55.473 T:218371   debug <general>: Activating window ID: 10035
2024-08-04 02:22:55.473 T:218371   debug <general>: Activating window ID: 10035
2024-08-04 02:22:55.473 T:218371   debug <general>: Activating window ID: 10035
2024-08-04 02:22:55.473 T:218371   debug <general>: Activating window ID: 10035
2024-08-04 02:22:55.474 T:218371   debug <general>: Activating window ID: 10035
2024-08-04 02:22:55.474 T:218371   debug <general>: Activating window ID: 10035
2024-08-04 02:22:55.474 T:218371   debug <general>: Activating window ID: 10035
2024-08-04 02:22:55.474 T:218371   debug <general>: Activating window ID: 10035
2024-08-04 02:22:55.474 T:218371   debug <general>: Activating window ID: 10035
2024-08-04 02:22:55.475 T:218371   debug <general>: Activating window ID: 10035
2024-08-04 02:22:55.475 T:218371   debug <general>: Activating window ID: 10035
2024-08-04 02:22:55.475 T:218371   debug <general>: Activating window ID: 10035
2024-08-04 02:22:55.475 T:218371   debug <general>: Activating window ID: 10035
... Repeats endlessly ...
```
</details>

**Comment by MikeSiLVO** [comment]
I get a crash on Windows using Copecetic.

Narrowed it down to the Focus_Setter includes slide animation.

Changing line 49 of Components.xml from this:
``<animation effect="slide" end="0,0" time="$PARAM[time]" reversible="false">Focus</animation>``

To this:
``<animation effect="slide" end="0,0" time="$PARAM[time]" reversible="false" condition="!Window.IsVisible(settings)">Focus</animation>``

Fixed the crashing for me. Not sure if that will work for you...

**Comment by sarbes** [comment]
I'm gonna close this one. The current implementation executes the focus action on the next frame. Skins might (wrongly) expect it to be executed on the current frame. This is a hack, and working around might not be easy.

**Pull request closed without merging**
