### PR TITLE
VideoPlayer: mark overrides.

### PR DESCRIPTION
**Pull request by ghost**
Makes clang much more happy, and much more silent...
@FernetMenta

### CODE REVIEW

**Comment by garbear** [comment]
nice, just had to go through and update the entire 15k-line controller input pr

**Comment by FernetMenta** [comment]
this was on my list too. it is not about just silencing warnings. this is a great opportunity to clean an interface and correct old mistakes. IsInMenu is a good example. It is protected and not supposed to be called from outside but the interface defines it public and it is called from outside which can result in a crash.
Only add the override keyword if you know that this is correct.

**Comment by anaconda** [comment]
To be honest, I have assumed that after your work (and you constantly working on it daily) it was clean already and these were just warnings, yes :-)
I see `IsInMenu` has been addressed in a different PR - does this just need a rebase (so everything else is okay) or do you prefer to address these warnings-but-not-just-wanings yourself later when you have time?

**Comment by FernetMenta** [comment]
> To be honest, I have assumed that after your work (and you constantly working on it daily) it was clean already and these were just warnings, yes :-)

nope, it is not and there is still a long way to go 

> or do you prefer to address these warnings-but-not-just-wanings yourself later when you have time?

anybody is welcome to do so. does not all have to be done in a single change. as mentioned, the goad is not to kill a warning but to verify that behaviour is correct. see IsInMenu as an example.

**Comment by MartijnKaijser** [comment]
@FernetMenta can this be closed?

**Comment by FernetMenta** [comment]
yes

**Pull request closed without merging**
