### PR TITLE
[cleanup] silence compiler warnings

### PR DESCRIPTION
**Pull request by Rechi**
## Description
Silence compiler warnings.

## Motivation and Context
I don't like those warnings.

## How Has This Been Tested?
compiled

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by notspiff** [comment]
may as well fix the other grammar error as well ;) (silent -> silence)

**Comment by Rechi** [comment]
jenkins build this please

**Comment by Rechi** [comment]
any objections?

**Review by Paxxi — APPROVED** [review]

**Comment by Paxxi** [comment]
jenkins build and merge this please

**Comment by Rechi** [comment]
jenkins build and merge

**Pull request merged**
