### PR TITLE
[fix] coverity issues

### PR DESCRIPTION
**Pull request by Rechi**
## Description
Fix a few coverity issues

## Motivation and Context
reduce coverity issues

## How Has This Been Tested?
build for windows and osx

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by Rechi** [comment]
jenkins build this please

**Comment by Rechi** [comment]
@Montellese are the web server changes okay?
don't know whom I should ping for the other changes

**Comment by Montellese** [comment]
@Rechi: webserver changes look ok. I'm actually confused because I did those changes during my last webserver cleanup as well but I had to do quite a few rebases there so maybe I lost that commit (and hopefully only that one).

**Review by Montellese — APPROVED** [review]

**Review by AlwinEsch — APPROVED** [review]

**Comment by Rechi** [comment]
any objections?

**Pull request merged**
