### PR TITLE
Add cmake instructions for vs 2017

### PR DESCRIPTION
**Pull request by razzeee**
## Description

Adds some instructions for vs 2017

## Motivation and Context

I keep forgetting to use `Visual Studio 15` as cmake target. So I think we should add this to the readme.
## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by gelotus** [comment]
@Razzeee FYI I'm build with vs17 14.1x and I haven't problems at all

**Comment by gelotus** [comment]
Maybe the windows build instructions in the wiki are little outdated, for building I'm follow the Jenkins log commands

**Comment by Rechi** [comment]
If you have installed `VC++ 2015.3 v140 toolset(x86,x64)` `Visual Studio 14` generator may still work.

**Comment by hudokkow** [comment]
I'm rewriting our git docs from the ground up. You can see current WIP state at https://github.com/hudokkow/xbmc/pull/2

[Windows build guide](https://kodi.wiki/view/HOW-TO:Compile_Kodi_for_Windows) is the most confusing one we currently maintain, imo.
I intend to write a new guide with only what one needs **now** and for **current** master state. 
That means dropping references for older VS versions and instructions that span some 10 years. No references to 10 year old SDKs no longer needed, for instance.

I would appreciate it very much if someone could take a picture of what one needs to select in VS2017 component install (similar to screenshots present in the wiki).

Otherwise I'll set up a VM or convert my jenkins bot to VS2017 and try it for myself.

BTW, this README is getting the hammer in favor of complete build guides without the need to continuously jump across several locations for a bit of information and it will only contain CMake's related stuff (available targets, variables, etc.) that control the build configuration.

Sorry for hijacking this @Razzeee

**Comment by Razzeee** [comment]
Not a problem good to know. Can we still merge this or should this be closed?

This is what I have installed, and I was able to successfully build.
grafik

**Comment by hudokkow** [comment]
Please merge. The more info I have about Windows build the better. Not my cup of tea but I'll write and test the guide. :wink:

**Pull request merged**
