### PR TITLE
remove slingbox support

### PR DESCRIPTION
**Pull request by stefansaraev**
it's been discussed that slingbox support should go. do we want it removed ?

@FernetMenta for the dvdinputstreamtv cleanup commit
@opdenkamp for the pvr cleanup commit.

### CODE REVIEW

**Comment by Jalle19** [comment]
Funny, I was working on the same thing today. +1 from me, I searched the forums and Slingbox support has seemingly been broken for some time anyway. Plus that crap is limited to 240p (yes, really).

**Comment by Jalle19** [comment]
jenkins build this please, I have a feeling some parts are missing.

**Comment by Paxxi** [comment]
:+1:

**Comment by Jalle19** [comment]
This will be a first step in perhaps getting rid of the horrible stuff that is `ILiveTVInterface`.

**Comment by hudokkow** [comment]
3 of us working on the same thing -> https://github.com/hudokkow/xbmc/tree/drop_slingbox
+1

**Comment by opdenkamp** [comment]
+1

**Comment by Jalle19** [comment]
@FernetMenta care to comment before merging?

**Comment by Hedda** [comment]
Maybe it would be better if reimplemented as a PVR client addon for Kodi instead? 

Later Slingboxes support streaming Apple HLS (HTTP Live Streaming) protocol in high-resolution to SlingPlayer clients.

http://sourceforge.net/projects/slingboxsdk/

**Comment by Jalle19** [comment]
Yes

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Pull request merged**
