### PR TITLE
VideoPlayer: fix some remaining http header issues

### PR DESCRIPTION
**Pull request by FernetMenta**

### CODE REVIEW

**Comment by FernetMenta** [comment]
@emilsvennesson could you test this please?

**Comment by basrieter** [comment]
I check this and as far as I could see, the cookies were now correctly passed on to ffmpeg and added to the requests.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by emilsvennesson** [comment]
@FernetMenta I don't have the software installed to compile Kodi right now. :/ I will be happy to try it out if you merge it though.

**Comment by MartijnKaijser** [comment]
@emilsvennesson watch this build http://jenkins.kodi.tv/job/WIN-32/9941/  which will end up on http://mirrors.kodi.tv/test-builds/win32/ with this branch name

**Comment by emilsvennesson** [comment]
@MartijnKaijser Ah, that makes it easier. :-) Thanks!

@FernetMenta I just tried it out and can confirm that it works. :smirk:

**Comment by FernetMenta** [comment]
thanks all!

**Comment by basrieter** [comment]
Thanks you guys for this nice essential application. Happy to contribute.

**Pull request merged**
