### PR TITLE
[addons] refresh label2 after updating download progress

### PR DESCRIPTION
**Pull request by tamland**
regression from c5b89136. @HitcherUK

### CODE REVIEW

**Comment by HitcherUK** [comment]
@tamland This fixes displaying label2 when downloading an addon but now the list is being constantly refreshed making it strobe and triggering any focus animations.

**Comment by tamland** [comment]
@HitcherUK Need more info again. Not seeing that at all in confluence. Works exactly like before as far as I can tell.

**Comment by HitcherUK** [comment]
If you switch to Info view 2 you'll see what I mean or just focus on the side menu in the list views. If you have a zoom focus animation it's constantly zooming.

**Comment by tamland** [comment]
@HitcherUK can you try again?

**Comment by HitcherUK** [comment]
Mind triggering a Windows test build I'm at work right now. Thanks.

**Comment by tamland** [comment]
@HitcherUK http://mirrors.kodi.tv/test-builds/win32/KodiSetup-20160229-5943cba-fix_label2_refresh.exe

**Comment by HitcherUK** [comment]
Perfect now tamland, sorry for the hassling. ;)

**Comment by tamland** [comment]
Thanks for testing!

**Pull request merged**
