### PR TITLE
Keymaps: update OSMC remote keymapping and add support for 3rd generation remote

### PR DESCRIPTION
**Pull request by samnazarko**
## Description
This PR removes the need to depend on downstream strings for low battery for existing remotes and adds support for the new OSMC remote. 

## Motivation and context
This remote is used outside of OSMC and on other devices such as LE; Windows and Linux platforms. The same can be said for the new remote. 

## How has this been tested?
Verified on all platforms.

## What is the effect on users?
No change to users that do not use an OSMC remote.

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by samnazarko** [comment]
Don't merge just yet (or backport). Checking a couple of things.

**Review by garbear — APPROVED** [review]
Both changes look OK to me. Given that one change is an improvement and one is a feature, I would separate them into two commits. That way, if there's a problem with one, it can be reverted without losing the functionality of the second.

**Comment by samnazarko** [comment]
Thanks for the prompt review. Makes sense. I'll make that change shortly.

**Comment by samnazarko** [comment]
Updated now.

**Comment by garbear** [comment]
LGTM

**Pull request merged**
