### PR TITLE
FIX: [aml] stuck when doing ff or rw

### PR DESCRIPTION
**Pull request by koying**
cf. https://github.com/xbmc/xbmc/commit/17f5565d98e39fa3b67e8ff59a2373e69b6c4d65#commitcomment-12784708

### CODE REVIEW

**Comment by Jalle19** [comment]
Will this need backporting?

**Comment by MartijnKaijser** [comment]
Absolutely

**Comment by FernetMenta** [comment]
thx

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by koying** [comment]
No good. Long jumps still broken. 
I suggest a plain revert of the problematic commit rather than risk adding regressions...

**Comment by FernetMenta** [comment]
I think a plain revert is risky. This change was done in turn of fixing a segfault caused by player observing decoder's cache lavel. those functions have disaeared. 
Why is it a big deal to did into this and fix it properly?

**Comment by koying** [comment]
I cannot find a logic flaw. Seems that, after a seek out of buffer, the codec just eats packets until it start producing back pictures, without an obvious pattern.

Going for the revert.
The only way I see it could cause problems is if the decoder is stuck, otherwise there is no queue draining. Using it almost daily without ever noticing the segfault in question, and then again we'd better fix it rather than trying to prevent it ;)

**Comment by FernetMenta** [comment]
I am not sure if you understand what I am talking about. this particular change did not fix a segfault. feel free to revert this as long as you don't touch the change that fixes the segfault.

**Comment by koying** [comment]
jenkins build and merge

**Pull request merged**
