### PR TITLE
Revert to process action without unicode. #16329

### PR DESCRIPTION
**Pull request by sportica**
Revert to process actions without Unicode. 

https://github.com/xbmc/xbmc/pull/7952
http://trac.kodi.tv/ticket/16329

### CODE REVIEW

**Comment by sportica** [comment]
@MilhouseVH Would you please test this?

**Comment by MilhouseVH** [comment]
Tested (OpenELEC x86 + Ortek VRC-1100, English language) and working well - many thanks!

**Comment by stefansaraev** [comment]
jenkins build this please

**Comment by mkortstiege** [comment]
jenkins build and merge

**Pull request merged**
