### PR TITLE
[VideoPlayer] WinRenderer: fix render capure when dxva render method …

### PR DESCRIPTION
**Pull request by afedchin**
…is used.

This fix an issue with bookmarks when dxva rendering is used.

@MartijnKaijser please test this. iirc there is an issue on your nVidia with dxva rendering directly to render target.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
did i have an issue? Willing to test if i know what to look for :)

**Comment by afedchin** [comment]
@MartijnKaijser As I said IIRC. 
To test this just start playback (make sure what dxva decoding is used or dxva rendering is forced in settings) then open bookmarks osd dialog and create a new bookmark. The new bookmark should be with a valid picture.

**Comment by MartijnKaijser** [comment]
confirmed fixed. First time ever i used a bookmark btw

**Comment by MartijnKaijser** [comment]
fyi I got broken bookmark on Intel HD4600 actually and this PR fixed it. Not tested nvidia atm

**Comment by afedchin** [comment]
please check on nVidia because it had the issue http://forum.kodi.tv/showthread.php?tid=218274&pid=1932482#pid1932482

**Comment by MartijnKaijser** [comment]
don't see any issues at the moment

**Comment by afedchin** [comment]
do you have no isse with and without this PR on nVidia?

**Comment by MartijnKaijser** [comment]
not with at least

**Comment by afedchin** [comment]
jenkins build this please

**Pull request merged**
