### PR TITLE
remove service.xbmc.versioncheck

### PR DESCRIPTION
**Pull request by ronie**
the addon is outdated & unmaintained.
it hasn't even been updated for kodi leia.

### CODE REVIEW

**Comment by Rechi** [comment]
The add-on is still working, it only needs one who adds the new Kodi versions.

**Comment by anxdpanic** [comment]
Submitted the addition of 18.x, https://github.com/XBMC-Addons/service.xbmc.versioncheck/pull/20

**Comment by ronie** [comment]
@anxdpanic i'll send you an invite to the XBMC Add-ons repo, so you can handle merging your PR's as well.

**Comment by anxdpanic** [comment]
Thanks, will try to keep on top of it.

**Pull request closed without merging**
