### PR TITLE
[WIP] Integrate AudioDSP better into AE

### PR DESCRIPTION
**Pull request by AchimTuran**
In this PR I did the following changes:
- Simplify AudioDSP API
- Introduce a new buffer class for AudioDSP in AE
- Remove the dependency of ApplicationMessenger, because AE should manage the AudioDSP manager class
- Always enable AudioDSP
- Improve thread safety
- Fix some issue with the internal used FFMPEG resampler for AudioDSP

To dos:
- Cleanup
- Test this on all platforms
- Test if passthrough works
- Test if bypassDSP is working properly

### CODE REVIEW

**Comment by AchimTuran** [comment]
jenkins build this please

**Comment by AchimTuran** [comment]
@FernetMenta, @fritsch or @AlwinEsch 
Under Windows the most stuff works and is much more stable then before.

But I couldn't get passthrough working. I guess that something is currently wrong with these changes. Can you help to get it working?
I'm getting these errors:
Debug Print: ActiveAE::SyncStream - average error of 7654.129078, start adjusting
Debug Print: ActiveAE::SyncStream - average error 24.129078, last average error: 7654.129078
Debug Print: ActiveAE::SyncStream - average error of 7641.362811, start adjusting
Debug Print: ActiveAE::SyncStream - average error 21.362811, last average error: 7641.362811
Debug Print: ActiveAE::SyncStream - average error of 7636.629072, start adjusting
Debug Print: ActiveAE::SyncStream - average error 26.629072, last average error: 7636.629072
Debug Print: ActiveAE::SyncStream - average error of 7651.276295, start adjusting
Debug Print: ActiveAE::SyncStream - average error 21.276295, last average error: 7651.276295
Debug Print: ActiveAE::SyncStream - average error of 7629.852134, start adjusting
Debug Print: ActiveAE::SyncStream - average error 29.852134, last average error: 7629.852134
Debug Print: ActiveAE::SyncStream - average error of 7652.707041, start adjusting
Debug Print: ActiveAE::SyncStream - average error 22.707041, last average error: 7652.707041
Debug Print: ActiveAE::SyncStream - average error of 7653.389322, start adjusting
Debug Print: ActiveAE::SyncStream - average error 23.389322, last average error: 7653.389322
Debug Print: ActiveAE::SyncStream - average error of 7646.182370, start adjusting

**Comment by AchimTuran** [comment]
Dialog changes for AudioDSP V2 are present in https://github.com/xbmc/xbmc/pull/10755.

**Comment by FernetMenta** [comment]
timestamps seem to be messed up. could you remove all ADSP only changes from this PR? Then we can review only the interface to AE.

**Comment by AchimTuran** [comment]
That's what I also think.

Sure I can revert them all and then we try to fix them. Afterwards we can create a new PR for the adsp commits.

**Comment by AchimTuran** [comment]
Ok, I got passthrough working. Seems to be that I did some mistake during removing adsp from the buffer.

**Comment by FernetMenta** [comment]
please don't forget to remove adsp only changes from this pr or submit interface changes in a separate pr.

**Pull request closed without merging**
