### PR TITLE
Folder resume

### PR DESCRIPTION
**Pull request by gentoo-root**
Make bookmarks when playing folders with music and video and allow to resume from bookmarked position. Don't resume from bookmark if folder was changed (you can disable this feature in settings). CUE sheets for music are supported. Also highlight currently played folder, not only current file.

Original patch for 10.0 Dharma was here: http://trac.kodi.tv/ticket/11204. A year ago I've made folder resume feature for Frodo (based on original patch), and now I've ported it to Kodi master.

### CODE REVIEW

**Comment by mkortstiege** [comment]
Hm. I am not entirely against but is there a user base for this? It seems to be a bit over-engineered and adds a good bunch of code that has to be maintained and tested. There must be reason it is around since Dharma ..

As for the hash parts we could move the mtime hash methods to a `Util` class. There's also a function to get a recursive directory listing. All that code is used in the `VideoInfoScanner`.

**Comment by Montellese** [comment]
I can see this being useful for music, especially for audiobooks, but not sure about videos either as there this is basically what hide watched is for to only see the seasons/episodes that haven't been viewed yet.

**Comment by Montellese** [comment]
I didn't go through all the changes yet (especially not the integration into the databases and the library views) because I think we first need to decide if and where this really makes sense. Maybe @gentoo-root can provide us with his use case(s)?

**Comment by gentoo-root** [comment]
Thanks for your replies!
Well, the use cases are rather obvious and were already mentioned by @mkortstiege and @Montellese, and I didn't invent any other one. For audiobook listeners this feature will be useful, many people wait for it (http://forum.kodi.tv/showthread.php?tid=219425, there also people say it has been asked before and it's in Popular Feature Requests list). For videos it's also handy to start folder with episodes, and the next time just resume from saved position with just two clicks. It's convenient that videos play one by one and remember position where they were stopped last time. Basically, if resume is supported for single videos and will be supported for audio folders, why don't implement this feature also for video folders? Especially if it was supported by original patch.

**Comment by mkortstiege** [comment]
IMO folder/node resume makes sense for audio but i still think we already have code in place like `hide watched`, `play from here` and the recently added `jump to first unplayed item` for videos that pretty much cover the needs. Furthermore it feels like the entire feature is mainly designed around the files node.

**Comment by Montellese** [comment]
I have to agree with @mkortstiege. In the video library there are features to only let you see the unplayed items and to directly jump to the first unplayed item etc.
IMO this makes perfect sense for audiobooks but I'm also not sure if it does make sense for usual music. IMO starting with the song having been played last makes sense but starting in the middle of the song doesn't.

**Pull request closed without merging**
