### PR TITLE
[addons] fix event publishing and database handling

### PR DESCRIPTION
**Pull request by howie-f**
## Description
follow up pr to #18447

corrects publishing of events necessary for the gui update and also adds missing error handling for underlying database calls to make the whole codepath more robust.

## How Has This Been Tested?
runtime tested on debian

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [X] **Improvement** (non-breaking change which improves existing functionality)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document

### CODE REVIEW

**Review by phunkyfish — APPROVED** [review]
LGTM

**Review by ksooo — APPROVED** [review]
Thanks.

**Comment by howie-f** [comment]
the approach to fire a gui update event in `AddUpdateRuleToList`, `RemoveAllUpdateRulesFromList` and (missed) `RemoveUpdateRuleFromList` is correct, but has consequences to the gui behavior:

after an addon is updated or downgraded via `Update` button of the AddonInfoDialog the AddonBrowser returns to its first list-entry, not to the addon we up-/downgraded like it did before. (in this example a version switch on `Sticky Matrix` was performed, which is near the bottom of the list, but we get a focused `AAC encoder` afterwards)

screenshot000

thus a different approach needs to be taken, the gui event is now only fired by the auto-updates-toggle-button.
this way the behavior is like before and we see the correct pin-icons.

**Comment by ksooo** [comment]
> the gui event is now only fired by the auto-updates-toggle-button.

 Sorry, this seems the wrong approach. The original approach was correct. We need to find why the item focus is lost and how to recreate it.

**Comment by howie-f** [comment]
in order to prevent gui glitches by firing colliding `AddonEvents` it's inevitable to replace `UpdateRuleModified` with `AutoUpdateStateChanged`. a solution keeping the previous event unfortunately wasn't found.
gui behaves flawlessly with the recent changes.

@ksooo would you mind having a look again please?

**Comment by phunkyfish** [comment]
Ok, this does propagate events correctly so I'm OK with this approach.

**Comment by ksooo** [comment]
No hard feelings here and no better idea for a better fix - not a guilib guy here.

**Pull request merged**
