### PR TITLE
[retroplayer] rework to new code style without shared lib

### PR DESCRIPTION
**Pull request by AlwinEsch**
Remove the use of shared add-on library for game add-ons.

## Description
The lib is no more used on add-on. It can be added without changes on add-ons, they need only a recompile.

## Motivation and Context
Cleanup binary add-ons

## How Has This Been Tested?
Has tested it with game.libretro.nestopia, but due to libretro build problems (related to my linux) used hack way and control was not possible (with and without this).

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by AlwinEsch** [comment]
@garbear can you test and confirm that games are playable?

**Comment by AlwinEsch** [comment]
jenkins build this with addons please again

**Comment by akva2** [comment]
@AlwinEsch it's not pretty but at least it works this way;

to build those things on linux you do:
1) build kodi.
2) build and install p8-platform with -DCMAKE_INSTALL_PREFIX=<kodi-build-dir>/build
3) build and install kodi-platform with -DCMAKE_INSTALL_PREFIX=<kodi-build-dir>/build
4) clone game.libretro and build using  -DCMAKE_PREFIX_PATH=<kodi-build-dir>/build -DKODI_BUILD_DIR=<kodi-build-dir>.
5) clone the add-on somewhere
6) go to depends/common/<retro core name>
7) git clone <url in retrocore.txt>
8) copy CMakeLists.txt into retrocore
9) cd retrocore; mkdir build; cd build; cmake .. -DCMAKE_INSTALL_PREFIX=<kodi-build_dir>/build; make; make install
10) now build the addon using -DCMAKE_PREFIX_PATH=<kodi-build-dir>/build -DKODI_BUILD_DIR=<kodi-build-dir>.

you now have the add-on built and it's put into kodi build tree for testing. don't forget the idiotic manual enabling step for the add-on.

i have tested one core and it seemed to work fine.

**Comment by hudokkow** [comment]
I would say this is working. Tested with top 2 commits from https://github.com/hudokkow/xbmc/commits/cmake_gameezz and spent the last hour in the 90's. ;)

virtualbox_2016-12-14_15-27-37

**Comment by AlwinEsch** [comment]
Thanks a lot. From the ugly duckling will soon become a swan ;).

Everything of the libKODI* and libXBMC* who are related to add-on types itself are becomes soon complete removed and added to the related class, e.g. AddonCallbacksPVR.cpp comes in PVRClient.cpp and the libXBMC_pvr.h goes complete away.

Problematic is it only to bring this in on a way who is good for overview and not to much together. The hard think is that not only one add-on type need to changed, there must be always all corrected together.

For this coming soon some requests who are on first view not direct good e.g. some `void*`.

**Comment by hauihau** [comment]
Hi Alwin,

did you forget a file? xbmc/lib/addons/library.kodi.game/libKODI_game.cpp is still in tree.

**Comment by AlwinEsch** [comment]
Ups, thanks a lot! Yes has forgot it.

**Pull request merged**
