### PR TITLE
FIX: [droid;amcs] do not stop video when loosing main surface

### PR DESCRIPTION
**Pull request by koying**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build this please (test)

**Comment by MrMC** [comment]
if you lose the surface what are you playing on ?

**Comment by koying** [comment]
When doing refresh rate switching, the surface gets destroyed/recreated
(only once, apparently, for strange reasons)

This prevents the video from being stopped when we get the surface
destroyed notif.

Le mer. 28 oct. 2015 22:34, Scott Davilla <notifications@github.com> a
écrit :

**Comment by MartijnKaijser** [comment]
it now works on first play

**Pull request merged**
