### PR TITLE
Sysinfo update

### PR DESCRIPTION
**Pull request by Karlson2k**
Small updated for SysInfo, mostly Android-related.
With this updated we'll get nicer strings in startup log.

### CODE REVIEW

**Comment by mkortstiege** [comment]
I am not a fan of the hard-coded android version numbers. Is there maybe a more elegant way?

**Comment by wsnipex** [comment]
http://developer.android.com/reference/android/os/Build.VERSION.html#SDK_INT

**Comment by Karlson2k** [comment]
This is all about host OS version.
This patch will allow to print minimal required Android version in startup log, i.e. it's about how Kodi was compiled, not about current environment.
http://developer.android.com/guide/topics/manifest/uses-sdk-element.html#ApiLevels

**Comment by stefansaraev** [comment]
ping

**Comment by Karlson2k** [comment]
Will update it in next few days.

**Pull request closed without merging**
