### PR TITLE
store arbitrary artist art in art table

### PR DESCRIPTION
**Pull request by ronie**
store artist artwork (artist logo, artist banner, etc..) in the art table.
skins will be able to display this artwork using ListItem.Art()

we already have this functionality for all other media types (movies, tvshows, albums, etc..)
but it was never hooked up to artists.

@DaveTBlake

### CODE REVIEW

**Comment by DaveTBlake** [comment]
>it was never hooked up to artists.

But we do already store scraped artist art in the art table (from CMusicInfoScanner). Also there is an user reported issue of artist art getting stuck as the wrong image , so I would like to check this out a bit more.

**Comment by jjd-uk** [comment]
@DaveTBlake I believe ronie is waiting on your approval for this one.

**Comment by DaveTBlake** [comment]
Sorry for delay @ronie I lost sight of this, thanks for reminder @jjd-uk 

On the one hand it makes sense to make artist art consistent with how album art is handled, so thanks for this.  However I am having difficulty actually invoking this code in testing, and I'm not sure how to cause the  album art processing it replicates either.  Perhaps you can help me out? Maybe I'm holding it wrong? 

How does any additional arbitrary art (banners, logos etc.) _for music_ get into Kodi?

**Comment by DaveTBlake** [comment]
> How does any additional arbitrary art (banners, logos etc.) for music get into Kodi?

Is the answer that currently they don't, but that #11755 would make it possible via the new Python scrapers? So does that also mean that the existing CAlbum implementation is redundant until then too, or am I missing something?

**Comment by Rechi** [comment]
@ronie this needs a rebase

**Comment by DaveTBlake** [comment]
Closing as changes included in #12891, thanks for the inspiration @ronie

**Pull request closed without merging**
