### PR TITLE
PluginDirectory: Refactor to remove the dependency on GUI (concurrent busy dialogs)

### LINKED ISSUE #14838: Leia addon crash on xbmc.executebuiltin(PlayMedia...
### Describe the bug

Windows Runtime Error after an addon executes 
`xbmc.executebuiltin('PlayMedia("plugin://plugin.video.crackle/?id=2537&mode=103&type=movies")')`

Also, ActivateWindow does nothing but should launch into a video window.

## Expected Behavior

A movie is played from the Crackle plugin.video.crackle addon.

## Actual Behavior

Windows crashes with a Runtime Error.

## Possible Fix

Kodi Core revert to Krypton behaviour.

### To Reproduce

Install plugin.program.simple.favourites from this zip.
https://github.com/primaeval/repository.primaeval/raw/master/jarvis/plugin.program.simple.favourites/plugin.program.simple.favourites-0.1.13.zip
Install Crackle from Kodi repo.
Kodi\Addons\Programs\Simple Favourites\Add\Video Addons\Crackle\Movies
"Add" a movie from Context Menu.
Back out of Addon.
Go back in to Simple Favourites.
Click on the movie.
Kodi crashes with a Runtime Error.

The xbmc.executebuiltin(PlayMedia command is launched from here:
https://github.com/primaeval/plugin.program.simple.favourites/blob/master/main.py#L95

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/bihoqubali.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

error

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Screenshot after clicking on movie from top of Simple Favourites addon.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Kodi (18.0-RC1 Git:20181109-a948f998d9). Platform: Windows NT x86 64-bit
and
Kodi (18.0-BETA3 Git:18.0b3-Leia). Platform: Linux x86 64-bit
Running on LibreELEC (official): 8.90.006 9.0, kernel: Linux x86 64-bit version 4.18.11

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #16756: Kodi crashes when 2 concurrent busy dialogs occur
### Describe the bug

Kodi crashes while browsing in the official YouTube add-on if 2 "busy/wait" actions occurs at once.

## Expected Behavior

Kodi does not crash.

## Actual Behavior

Kodi crashes.

### To Reproduce

1. Add 2 videos from YouTube to the playing queue (use the "Queue video" action).
2. Go back to the GUI and leave the first video playing in the background.
3. Execute just about any other "busy" action in the add-on (e.g. a search for another video) just before the first video ends and the second one tries to start in the background (so that both the second video loading and the search occurs at once).
4. Kodi crashes.

### Debuglog

The debuglog can be found here:
http://ix.io/1YCl
The crashlog is from Amlogic MX2 box running Kodi 18.2 because that is the slowest device laying around right now but the same happens on at least 2 different devices as well.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)

The timing can be a little tricky but it is more easy to reproduce on a slow device (e.g. RPi) where the loading times are bigger.

It is probably not YouTube specific. At least I've tested that the second action can be executed from another add-on while the YouTube video is loading in the background and the Kodi still crashes.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 9.1.501 (tested on Rockchip and Amlogic)
 - Kodi version: 18.4/Leia

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by enen92**
## Description
This pull request is intended at fixing the current unpredictable situation with concurrent busydialogs crashing kodi when actions involving plugin/python execution are involved. To be able to accomplish this, plugin resolution logic was made async so that the GUI dependencies could safely be removed from `CPluginDirectory` (VFS). Since we have no control over the addon code nor the time python takes to execute the scripts, plugin actions called from the main thread should be wrapped around busyloaders (BusyDialog) to allow the cancelation of the action by the user. The action can also be executed synchronously without a busyloader in other cases (e.g. plugin execution as part of a job, running in other threads other than the main thread  - the case of python scrappers), etc.

A new message was created to route plugin resolution attempts to CApplication whenever the action is executed from the main thread or should be routed to it. This is currently the case of `PlayListPlayer` that receives plugin playback requests from CApplication when plugin:// playable paths are sent via the JSON-RPC. Similar use cases may appear in the future.

As a side effect of the refactor, python execution is also a bit faster due to the way scripts are stopped.

Thanks to @ksooo for a similar implementation in the PVR section. @yol and @phunkyfish for the help provided.

## Motivation and Context
Kodi crashes fairly often due to the co-existence of multiple busydialogs. This is unpredictable and occurs more than desirable. While this PR doesn't promise to solve all those occurrences, at least I was not able to reproduce both of our 2 open issues anymore.
Hence this fixes https://github.com/xbmc/xbmc/issues/14838 and fixes https://github.com/xbmc/xbmc/issues/16756

## How Has This Been Tested?
This was tested with the description of issue https://github.com/xbmc/xbmc/issues/16756 using the youtube addon. 

Additionally it was also tested by crafting a plugin (and a script) with the following code:

```python
import xbmc
xbmc.executebuiltin('PlayMedia("plugin://plugin.video.rtpplay/live/play?channel=rtp2&name=rtp1&prog=test&label=test)')
endOfDirectory(plugin.handle)
```

I also used @anxdpanic test addon for this particular issue - which can be obtained in https://github.com/anxdpanic/plugin.script.testing/tree/sru_and_pm_crashes

I tested plugin execution (and playback requests) from JSON-rpc using kore and yatse to make sure the busydialog is shown and there aren't any GUI freezes (it can't be executed synchronously if GUI is available).

Also tested python scrappers and my items where scrapped into the library.

Tested multiple addons for possible regressions and haven't found any. @anxdpanic did similar tests.

## Requests
 ~~@mediaminister @dagwieers this PR removes the dialog progress as a busyloader that was introduced in https://github.com/xbmc/xbmc/pull/14225 by @AkariDN. I don't see a use for that and I suspect it was introduced to bypass something that was not well implemented in inputstreamhelper at the time (download and extraction of libwidevine on arm/rpi). It'd be nice if you guys could confirm all is working as expected in your addon. The progressdialog can be added to the current logic if justified, but I'd prefer to understand the need for this first.~~ 
Note: akariDN explained the need for it

~~I'd like to have this in the first alpha release of Matrix if possible (@DaveTBlake fyi)~~ (edit:deferred to alpha2)

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by AkariDN** [comment]
> this PR removes the dialog process as a busyloader that was introduced in...

No. My PR just prevents displaying the busy dialog if a progress dialog is active, e.g. while cleaning video database with items from plugin sources (item existence is checked via calling a plugin).

**Comment by enen92** [comment]
@AkariDN so this was part of your PR to add plugin library items with metadata=None scraper? If so I'll add it for now. That implementation will probably be deprecated once montellese's mediaimporter makes it into master though

**Comment by AkariDN** [comment]
This is not related to inputstreamhelper. Video database cleaning procedure displays a progress dialog and calls ```CPluginDirectory::CheckExists``` (which triggers a busy dialog in ```CPluginDirectory::WaitOnScriptResult```) for every plugin item, so there is no need to show two status dialogs simultaneously. My PR fixes this issue - active progress dialog is used instead of new busy dialog. If your version of ```CPluginDirectory::CheckExists``` doesn't show a busy dialog then everything is fine.

**Comment by enen92** [comment]
As far as I understand, `CheckExists` and the need for progressdialog when executing plugins were introduced by you in https://github.com/xbmc/xbmc/pull/14210 as part of the work to support plugin items in library with metadata.local scraper. I am not aware of any plugin that makes use of it (at least there is none in our repo) so I suspect only your plugin uses (or used to use) that feature. There's also https://github.com/AkariDN/plugin.video.testlib but it hasn't been updated for a while and it's not py3 compatible. Thus, that's why I am kindly asking you if you can check/test with your plugin if this feature is broken after this PR or, alternatively, guide me on how to do it. I am not familiar with this feature unfortunately.

**Comment by AkariDN** [comment]
I didn't introduce any progressdialogs when executing plugins. Displaying the busy dialog while calling a plugin was introduced a long time ago before my PR. I just fixed the issue with two status dialogs. If your PR completely removes busy dialog from CPluginDirectory then this issue automatically resolves. Of course, I can test it, but it will take some time, because I have no py3 test suite (I need to update my test plugin etc.). About other plugins - it's used [here](https://github.com/bigretromike/nakamori) and maybe somewhere else)

**Comment by enen92** [comment]
Maybe I expressed myself incorrectly: you didn't introduce a progress dialog in plugin execution but rather avoided showing the busydialog if a progress dialog was active (which inherently introduced another GUI dependency in CPluginDirectory). At first I didn't understand why and thought it was related to inputstreamhelper, now I do.

Regarding if it is still needed or not after this PR, it all comes down from where the plugin is executed from. If cleaning up the library is executed from the main thread, it is still needed. If not, all is good. I suspect it is still needed.
I'll try to run a few tests with the addon you pointed out (might be a bit of work as the addon is not python3 compatible).

**Comment by AkariDN** [comment]
Library cleanup is executed from main thread.

Sorry, about that addon - don't waste time. Reviewing plugin's code I found that functionality is [declared](https://github.com/bigretromike/nakamori/issues/306) but implemented incompletely and with some bugs... I'll check it faster using my own plugin.

**Comment by AkariDN** [comment]
@enen92 I've tested library cleanup and Kodi freezes while checking item existense (via call to plugin) and this cannot be cancelled. Moreover, cancelling is not working as expected in other cases too: when I open plugin folder busy dialog appears, and after pressing Esc Kodi freezes until plugin completion.

**Comment by enen92** [comment]
> Moreover, cancelling is not working as expected in other cases too: when I open plugin folder busy dialog appears, and after pressing Esc Kodi freezes until plugin completion.

Can you let me know which plugin you use? Or does it happen with all plugins? Just by navigating though the plugin directory?

**Comment by AkariDN** [comment]
Add some time consuming job (connecting to unexisting address or just "sleep") to any plugin and check
```Python
def main(argv):
    xbmc.sleep(5000)
```

**Comment by enen92** [comment]
@AkariDN I gave it a whirl and in fact it happens that you have a GUI freeze until the script ends execution after cancelling the busydialog. However, the exact same behaviour happens also in current master. I wouldn't worry about that here (it is out of the scope of this PR) although it can be improved (and I'll try to improve it later). I think it all comes down to the fact the `CScriptInvocationManager` `stop()` is waiting for the execution thread to end and...in certain cases (plugin navigation / GetDirectory) it shouldn't to avoid freezing the render loop.

That being said, I'm a bit more worried about your other issue (freeze while cleaning up the library with metadata local and plugins). I have no idea how to test the functionality and fix the error. Can you check if avoiding the busydialog if the progress is active solves the issue for you?

**Comment by mediaminister** [comment]
> This is not related to inputstreamhelper. 

Okay. So, I don't have to test this.

**Comment by AkariDN** [comment]
> I have no idea how to test the functionality and fix the error.

Library cleanup uses ```CPluginDirectory::CheckExists``` for plugin items. The freeze occurs in subsequent call to ```AsyncGetPluginResultAction(...).ExecuteSynchronously()``` because you removed busy/progress dialog from ```CPluginDirectory::WaitOnScriptResult``` which processed the render loop.

You can test it by calling this code from the main thread (put this code anywhere, for example in start of ```CVideoDatabase::CleanDatabase```):
```C++
CGUIDialogProgress* p = CServiceBroker::GetGUI()->GetWindowManager().GetWindow<CGUIDialogProgress>(WINDOW_DIALOG_PROGRESS);
p->Open();
CFileItem item;
// Write here real plugin url which takes some time to execute
AsyncGetPluginResultAction("plugin://your.favorite.plugin/", item, false).ExecuteSynchronously();
p->Close();
return;
```
In other words
1. ```CPluginDirectory::CheckExists``` should not block the render loop if this function is called from the main thread
2. If progress dialog is active, pressing Cancel should cancel plugin execution

**Comment by FernetMenta** [comment]
The issue can't be solved with a synchronous approach. The main thread must not be blocked with long running script operations. The current hack uses the busy dialog because it drives the render loop while waiting. 
In order to solve this properly you need to start the script (not on the main thread) and wait for a finish event in an asynchronous way.

**Comment by enen92** [comment]
Thanks for your (always valuable) input Fernet. 

I honestly though the usage of the busydialog to drive the script execution was intentional and was not really a hack, i.e., as they are long running scripts the user must have a way to cancel the script execution and the GUI should also have some way to show it is busy doing some heavy task. I think I see at a high-level what you mean: trigger the execution on a separate thread and receive some event/message when the processing is done, managing the state of executions somewhere else rather than CApp. I think I may be able to implement that and drive it forward. 

What I fail to see is how Kodi is supposed to show it is busy while the script is running or how to async cancel the script execution that was started in another thread. In other words, how the current behaviour could be "simulated" in a new implementation without the `DialogBusy`. Could `DialogBusyNoCancel` (as a modal dialog) be a possible option? Maybe if some event is hooked when creating the dialog and triggered `onClose`, the thread that started the execution could be notified and knows what script to kill?

Although probably not the definitive fix for the busydialog/plugin issues, I think this PR still has its merit by removing the dependency of filesystem on GUI (at least vfs calling into GUI). I hope it can still be move forward (after fixing the issue AkariDN points out) as the first step into fixing the overall issue.

**Comment by mediaminister** [comment]
It seems this PR has problems:
When running an external JSON-RPC command:
```
curl -n -X POST -H "contehost:8080/jsonrpc -d '{"jsonrpc": "2.0", "method": "Player.Open", "params": {"item": {"file": "plugin://plugin.video.vrt.nu/play/latest/het-journaal" }}, "id": 1}'
```

Kodi crashes with
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

**Comment by enen92** [comment]
@mediaminister isn't that the bug report that was just opened for master (https://github.com/xbmc/xbmc/issues/18122) ?

**Comment by mediaminister** [comment]
No, with this PR a single JSON-RPC command always crashes Kodi.

**Comment by enen92** [comment]
Hey @FernetMenta, sorry to bother you (again :) ).

I've come with a new implementation that I think matches your request (not blocking the main thread/get rid of the busydialog) while still keeping the requirements (cancellation and visual feedback). 

Can you please, code/implementation aside (although also appreciated) validate the design? I've already invested lots of hours into this so I'd prefer to have some validation before "wasting" a few more :)

**Explaining the approach:**

- Application no longer uses the busy dialog to drive the plugin execution

- There is a new component registered into the service broker (`CPluginExecutor`) whose responsibility is to receive the plugin resolution requests (`AsyncGetPluginResult`) offloaded from the main thread (via application messenger), resolve the items and pipe the resulting file item to the consumer (CApp, playlistplayer, etc - basically one of the params of the message)

- The executor offloads plugin resolution tasks as jobs, thus on a different thread. Stores a pointer to the action in a member/container variable (this allows to know if the component is busy or not)

- There's a new boolean condition `System.AddonIsBusy` that can be used by skins to show kodi is busy doing background work (whether the container is empty basically). Name is irrelevant at this point, only the concept.

- The `CPluginExecutor` hooks into the `ACTION_STOP` action (after the players) for cancellation. This means that hitting stop on a remote is still able to kill those background tasks.

- The render loop is no longer blocked and the user can navigate the interface freely while busy actions are running on the background.

**TODO**

- Skinning part is not done. At the moment I'm testing/developing this with a simple label in https://github.com/xbmc/xbmc/blob/master/addons/skin.estuary/xml/Includes.xml#L927:

```xml
<control type="label">
    <font>font45</font>
    <left>-200</left>
    <visible>System.IsAddonBusy</visible>
    <align>left</align>
    <shadowcolor>text_shadow</shadowcolor>
    <aligny>center</aligny>
    <height>110</height>
    <label>BUSY!</label>
</control>
```

- I have yet to figure out how to implement the AkariDN dialog progress with metadata local scrapper when cleaning up the library with plugin:// paths. Nevertheless, any implementation even if violating the design will be just temporary as I hope we can nuke it completely if mediaimporter makes it into master.

**Notes:**
- `TMSG_QUEUE_NEXT_ITEM` is pretty much the same as the `GUI_MSG_QUEUE_NEXT_ITEM` moved to Application `OnMessage` because we need to send the plugin result there now.

Your input is greatly appreciated,

Regards

**Comment by FernetMenta** [comment]
@enen92 

> offloaded from the main thread (via application messenger)

This is a bad idea. AppMessenger was originally developed to run tasks on the main/render thread. Using it for direction away from the main thread does the opposite you are trying to accomplish. It puts additional load on the main thread because the dispatcher runs on the main thread.

When making behaviour async, the app has to be aware of the state. If you don't care about the state, you may run into situation where multiple jobs are running, i.e. user presses next a couple of times. A GUI variable that signals a state does not enforce correct behaviour.

**Comment by enen92** [comment]
Well, sad to hear this is wrong again since it took me really a lot of time, but thanks anyway for your input - could learn a lot from it. I understand your points.

So, for my next attempt:
- This can't use AppMessenger for the communication between components to avoid the increased load on the main thread

- CApp has to manage state of a resolving task to avoid concurrency of tasks in case of user input. Submitting a new task should cancel any other that may be running and avoid a "first one to finish wins" situation as we have in this implementation. Might be hard to find out how to avoid badly written plugins completely lock the state (some sort of timeout is needed).

- Plugin resolution has to signal the App somehow that the item is ready.

@FernetMenta do you think the AppPort protocol can be used for this last point? I.e. to signal an event to CApp so it can take the appropriate decision when plugin items are ready? Or was AppPort designed with a completely different use case in mind? I see `setRenderGUI` there (although optional) so I am unsure this should be only used by components that should take over application rendering and input (not really the case of plugins). If AppPort can't be used, I'm pretty much out of ideas.

**Comment by FernetMenta** [comment]
@enen92 AppPort is the communication channel from windowing system to application. If you ran Kodi headless, AppPort wouldn't be registered. The communication method is not primary challenge here.
First you have to distinguish between user initiated actions and system initiated actions. The latter should not result in showing the busy dialog. Let's look at user initiated actions first. Assume user opens a plugin directory. Here kodi should display the busy dialog while the plugin does work. All actions but cancel should be disabled. The best location for handling this state is CApp::OnAction. The problem is the weak design of the interfaces: python JSON-RPC, and builtins which is the worst. This interfaces call methods like Play directly and could interrupt waiting for plugin response. Ideally those interfaces would have defined communication channels too. Maybe as a first step and workaround CApp could just disable external interfaces while in waiting state.
An example for system generated actions is QueueNextItem (initiated by players). A good place for tracking the state might be ApplicationPlayer. The logic there could cancel any running plugin actions when user stops playback or opens a new file.

**Comment by Lunatixz** [comment]
@enen92 What is the status of this issue? I'm experiencing a fatal Kodi crash error: `FATAL <general>: Logic error due to two concurrent busydialogs, this is a known issue. The application will exit.`

The issue arises when playing a plugin:// path from IPTV simple PVR backend and changing to another plugin:// path.

I can confirm no none of the plugins involved call busydialogs.

**Comment by enen92** [comment]
This PR is abandoned. I also don't think disabling interfaces is a proper fix. I'd rather have some sort of busy queue which accepts jobs/resolutions and locks the GUI/and input while the queue is not empty. Cancel them all, sequentially if cancel is requested.
I don't have time ATM to work on this and it requires far too much effort to implement and see it refused again.
Feel free to pick it up

**Comment by enen92** [comment]
Closing it for now

**Comment by Ch1llb0** [comment]
Would sure be great to see a fix for this some day... Just wanted to express this. 👍🏻
Especially when queueing files for YT playback via Yatse, multiple busy dialogs can really get in the way of things.

**Pull request closed without merging**
