### PR TITLE
[PVR] Fix playing channel not always highlighted in dialogs/windows.

### LINKED ISSUE #23968: [PVR] TV Channels played from the TV widget don't appear highlighted in the channels OSD if the "All Channels" group is hidden
### Describe the bug

I always have the "All channels" group hidden:

koditv4

If I play a previously played channel from the TV section:

koditv0

the channel isn't highlighted in the channels OSD:

koditv1

If the "All Channels" group isn't hidden, works as expected:

koditv3

## Expected Behavior

It should be like this:

koditv2

## Actual Behavior

koditv1

### Debuglog

[kodi.log](https://github.com/xbmc/xbmc/files/13056220/kodi.log)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 64-bit
 - Kodi version: 21.0-BETA1 (20.90.801) Git:20231018-8262078680

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
Fixes #23968 - take 2.

Runtime-tested on macOS and Android, latest Kodi master.

@phunkyfish something for you to review, thanks.

@Uukrull could you runtime-test and report back, please?

### CODE REVIEW

**Comment by Uukrull** [comment]
PR tested and working. The only nitpick I found is that the channels OSD doesn't automatically change to the group of the channel.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
> The only nitpick I found is that the channels OSD doesn't automatically change to the group of the channel.

@Uukrull yes, but as this never worked and is not easy to fix this needs to be something for another PR. 

@phunkyfish from my perspective, the PR is ready to go in as it is now.

**Review by phunkyfish — APPROVED** [review]

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins errors are unrelated

**Pull request merged**
