### PR TITLE
[Estuary] set text width for spinner

### PR DESCRIPTION
**Pull request by DaVukovic**
## Description

This PR limits the text width for spin-control in add-on settings. We can talk about the width and I'll happily change it if needed. For reference I took one of the music information providers which do have some long texts for the things to choose from . 

Let me know if we agree or not and if not which width should be used if any. 

## Motivation and context

https://github.com/xbmc/xbmc/issues/21184
Changing the texts is one solution, but if longer texts do fit better or explains the setting better, those texts shouldn't be cut. 

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by garbear** [comment]
Do you have before/after screenies?

**Comment by DaVukovic** [comment]
Sure. That PR was done fast yesterday evening during meeting all the ppl at devcon. So I simply forgot ;)

Here you go:
image

that's at least the "after". The "before" can be seen at the linked issue.

**Review by garbear — APPROVED** [review]
Looks like a good visual improvement, and with no code changes there's low risk. I don't see any problems

**Comment by gade01** [comment]
I'm afraid a textwidth of 700 will be too long.

Notice the long labels in this screenshot.
This is a textwidth of 470.

screenshot00002

Maybe the textwidth should be somewhere in between.

**Comment by CastagnaIT** [comment]
i think that hardcode this in xml is only a workaround it should be fixed in spinner control sourcecode
allowing it to self-adapt to the text lenght

**Comment by DaVukovic** [comment]
I totally agree that it would be nice to have kind of a dynamic text.width. But that need to be done by someone else, because that's out of my paygrade ;)

If anyone wants to fix that, I'll happily close this pr.

**Comment by CastagnaIT** [comment]
ATM i don't have time to investigate but i might try it in next future, leave the Issue opened so i can remember it,
furthermore this workaround only works if each skin adds it, estouchy skin is still broken

> what happens if the option to choose from will get longer than what we see above. For me, the description should be longer than the selection to choose from. If the selection is longer than the description, then the description is bad.

for limit cases we should set a certain min/max length bound limits for the text of the option to be chosen
so as not to allow too much (or too less) space in special text cases with too long (or too short) texts

**Comment by CastagnaIT** [comment]
fix PR opened take a look #21236

**Comment by DaVukovic** [comment]
Great thanks. Way better than mine. I'll close this one then

**Pull request closed without merging**
