### PR TITLE
[pvr] add pvr.vbox (new PVR addon)

### PR DESCRIPTION
**Pull request by Jalle19**
This is a new addon I've developed for use with VBox TV Gateway devices (see http://www.vboxcomm.com/products/xti-family.html).

@opdenkamp have I missed something or is this all that is required for inclusion?

### CODE REVIEW

**Comment by Jalle19** [comment]
jenkins build addons please

**Comment by hudokkow** [comment]
That's all it's needed.
No need for the complete commit SHA. First 7 digits is enough.

**Comment by Jalle19** [comment]
@hudokkow copying the whole hash was easier. Does it hurt to have the full hash there or should I change it?

**Comment by hudokkow** [comment]
I don't think it hurts at all. Atleast jenkins builds fine. I guess it's a matter of consistency.
Nice add-on, btw.

**Comment by Jalle19** [comment]
@hudokkow thanks

I'll merge this in the upcoming days unless anyone has any objections. If someone wants to review the code, be my guest!

**Comment by Jalle19** [comment]
I have some last minute changes pending so I'll update this PR at least once still before merging.

**Comment by Jalle19** [comment]
jenkins build addons please

**Pull request merged**
