### PR TITLE
Add Volume to Game OSD settings

### PR DESCRIPTION
**Pull request by garbear**
This adds a Volume setting to the game OSD.

The main reason was to show the hotkey in the GUI, but I decided to make the volume setting clickable.

## How Has This Been Tested?
Tested on Windows.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by garbear** [comment]
Pushed a commit removing a global from the code. @FernetMenta is the change to the player callback OK, or should we add a second player callback for volume?

**Comment by FernetMenta** [comment]
this looks like hard to understand spaghetti code to me. you register a player method into GUI and call back into application, that fires a thread msg to set volume?? (if I interpret this correctly).
volume is set from application to player, not the other way round.

**Comment by garbear** [comment]
Volume is set from application to player. Player fires a GUI msg to update the GUI. No architectural dependencies are violated.

**Comment by FernetMenta** [comment]
> No architectural dependencies are violated.

I see it differently. You created a circular dependency between player and application. Creating GetVolume / SetVolume in IPlayerCallback is no-go. Concatenating callbacks is still bad enough.

**Comment by garbear** [comment]
>  Creating GetVolume / SetVolume in IPlayerCallback is no-go

Thanks, that's what I was asking. I'll adjust the PR.

**Comment by Rechi** [comment]
@garbear this needs a rebase

**Comment by garbear** [comment]
Rebased. I was able to solve the gui dependency in #12715, once that gets merged I'll port the fix to this PR.

**Comment by garbear** [comment]
Circular dependency has been fixed. Good call, impact is much less. Jenkins build this please.

**Pull request merged**
