### PR TITLE
Quell some warnings

### PR DESCRIPTION
**Pull request by notspiff**
These are no-brainer cherry-picks from https://github.com/xbmc/xbmc/pull/10981

### CODE REVIEW

**Comment by hudokkow** [comment]
Thx! jenkins build this with addons please

**Comment by notspiff** [comment]
done.

**Comment by hudokkow** [comment]
jenkins build this with addons please

**Comment by hudokkow** [comment]
jenkins is happy. Backport worthy?

@fernetmenta, since you raised some concerns in https://github.com/xbmc/xbmc/pull/10981, are you OK with this? It barely touches VP code.

**Comment by FernetMenta** [comment]
all good

**Comment by hudokkow** [comment]
Thx both!

**Pull request merged**
