### PR TITLE
[python][addon] Add nullptr checks to parameter handling

### PR DESCRIPTION
**Pull request by Paxxi**
This should solve the crash introduced with #9666
@phil65 for review, works with your sample addon

### CODE REVIEW

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by AlwinEsch** [comment]
Hi @Paxxi #9807 :)

I close my then.

**Comment by Paxxi** [comment]
Sorry @AlwinEsch didn't see you had already looked into it, both work so whichever is fine by me

**Comment by phil65** [comment]
Thx to both of you for investigating. :) Choose whatever you think is the better fix.

**Pull request merged**
