### PR TITLE
Clean up some music library related compiler warnings 

### PR DESCRIPTION
**Pull request by DaveTBlake**
Clean up some recently introduced GCC compiler warnings and Coverity issues

### CODE REVIEW

**Review by lrusak — APPROVED** [review]
Fine by me but in the future it would be nice if you could break up the commits into separate categories, etc :smile:

**Comment by garbear** [comment]
Right, saying what warnings each set of changes fix would assist review, and bonus points for copy/pasting the compiler warning message for each. Never the less the changes here LGTM.

**Review by garbear — APPROVED** [review]

**Comment by DaveTBlake** [comment]
>Fine by me but in the future it would be nice if you could break up the commits into separate categories

**Comment by DaveTBlake** [comment]
>Fine by me but in the future it would be nice if you could break up the commits into separate categories, 

I really don't know how you would want this split @lrusak ?

>Right, saying what warnings each set of changes fix would assist review, and bonus points for copy/pasting the compiler warning message for each.

@garbear I really don't care about bonus points, and I would have thought that it was obvious what the issues were. 
GCC warned "comparison between signed and unsigned integer expressions [-Wsign-compare] for (unsigned int i = 0; i < iAddedFields; i++) "

I no longer have the Coverity report to paste. It reported the unused variables, lack of checking a return value on BuildSQL, and an inaccessible part of a series of if statements (looked like a git merge error sometime that left a repeated clause).

**Comment by lrusak** [comment]
> I really don't know how you would want this split @lrusak ?
> 

I'm just saying that you have various different fixes all lumped into the same commit with a vague commit message :smiley: A little more specificity would be nice next time :+1:

**Comment by DaveTBlake** [comment]
The commonality is the area of code they are in (too late for the commit message). It makes sense to me to gather a few one line fixes to compiler warnings in one area of code into one commit and PR.

It is kind of ironic because normally my PR comments have lots of design detail for reviewer or anyone looking later. This seemed too simple to need it. But then the PRs often don't attact reviewers without me begging lots, maybe not mentioning music and vague commit messages is the way to go in future 😃

**Comment by garbear** [comment]
I was just being pedantic. I've seen your previous PRs, you have more than enough comment credit!

**Pull request merged**
