### PR TITLE
[Music][JSON]Add and process musicbrainz albumstatus tag

### PR DESCRIPTION
**Pull request by the-black-eagle**
## Description
As per the title this gives Kodi the ability to read and use the musicbrainz album status tag (see https://musicbrainz.org/doc/Release#Status)

## Motivation and Context
This PR will read and add the tag to the music library for use either in skins via the new `ListItem.AlbumStatus` listitem or in a smartplaylist/node so that users can  divide their library based on the contents of the tag.  Current possible values are `official, bootleg, promotion & pseudo-release`. 
Implemented due to a request -> https://forum.kodi.tv/showthread.php?tid=354608

## How Has This Been Tested?
Tested by re-scanning my music library into both sqlite and MySQL db's and checking that the tag value was correct for any files where the tag was set.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ronie** [comment]
@the-black-eagle can you add support for python scrapers as well?
since the info is available on musicbrainz, it can easily be scraped.

requires a 1 line change here:
https://github.com/xbmc/xbmc/blob/bd471b1eb44362c44c2f466c064e8ded39db7513/xbmc/addons/Scraper.cpp#L750-L766

`album.strReleaseStatus = FromString(item, "album.releasestatus");`

**Comment by the-black-eagle** [comment]
@ronie Yes sure, thanks for the heads up!

**Comment by DaveTBlake** [comment]
Thanks for this both. Marked up the PR title to make the JSON bump easier to spot in git log, and it also adds an info label.

While Musicbrainz via scraping of tagging music file using Picard offers limited status values "official", "bootleg" etc., users can of course give this metadata any values that the want, so this will have broader user benefits

**Comment by DaveTBlake** [comment]
Can the last one line change commit be squashed into the first please @the-black-eagle , otherwise this looks good to go

**Comment by the-black-eagle** [comment]
@DaveTBlake Squashed as requested.

**Review by DaveTBlake — APPROVED** [review]
LGTM @the-black-eagle

**Pull request merged**
