### PR TITLE
Test PR for API 29

### PR DESCRIPTION
**Pull request by Tolriq**
Test PR for API 29 with mandatory flag to fix enable local device browsing

Just a test PR to have Jenkins build for me so I can test more as I see beta 1 is around the corner.

If someone can force Jenkins to provide downloadable APK that would be nice.

### CODE REVIEW

**Comment by jjd-uk** [comment]
APK's can be found under Build Artifacts

https://jenkins.kodi.tv/job/Android-ARM64/16706/
https://jenkins.kodi.tv/job/Android-ARM/19941/

**Comment by Tolriq** [comment]
Thanks, tested the basic and the flag is enough for mandatory stuff to works.

Still requires real binary addons / input stream tests to ensure the other API 29 changes does not break them.

**Comment by DaveTBlake** [comment]
Thanks @Tolriq for this reminder re sdk29, we certainly need a version that will run on newer Android devices before we can push v19 to the Playstore Beta channel.

@phunkyfish are you able to test PVR on Android 10 or 11, or know someone that can?
Addons and data access are the primary focus.
@peak3d obviously your area but hope we can get you some useful test feedback

**Comment by phunkyfish** [comment]
Sorry, I’m afraid I don’t have any android devices.

**Comment by jjd-uk** [comment]
@DaveTBlake this appears to have only been raised by Tolriq to allow  the manifast change to be built for him to test as peak3d has not yet revisited https://github.com/xbmc/xbmc/pull/18694 to make the manifest change there after the feedback on that PR.

**Comment by DaveTBlake** [comment]
Yes I am aware @jjd-uk. Testing is needed before merging into Beta, and this produces a useful test build for that purpose.

**Comment by DaveTBlake** [comment]
Closing as now superseded

**Pull request closed without merging**
