### PR TITLE
FIX: [droid] manually download obb if store failed

### PR DESCRIPTION
**Pull request by koying**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
* Created OBB folder on the mirror 
* Created Jenkins job MIRROR-OBB where you fill in git SHA and manifest version code (use with caution as it just overwrites previous file)
** main.<version_code>.org.xbmc.kodi.apk
** main.<version_code>.org.xbmc.kodi.obb

**Comment by Memphiz** [comment]
saw your ping on slack - yep that will work - nice work martijn :)

**Comment by Memphiz** [comment]
though i am not sure if we need to copy the apk aswell or if the obb would be enough (atm the job copies both)

**Comment by MartijnKaijser** [comment]
Yeah I had my doubts what to do. But now I'm absolutely sure I upload matching apk+obb to play store

**Comment by koying** [comment]
BTW, the code of Splash.java has become hackugly, so don't focus on that.
It's meant to be properly rewritten in J*.

**Pull request merged**
