### PR TITLE
Read scaled JPEGs

### PR DESCRIPTION
**Pull request by waldheinz**
## Description

Use libjpeg-turbo's `scale_num` /  `scale_denom` capabilities to get a nice performance boost when reading JPEGs. 

I'd only like to get some feedback of something like this seems acceptable. I know the code is a pile of garbage as-is, but it works for testing and the improvement is substantial. As this change introduces no new dependecies (libjpeg-turbo is already a hard dependecy of Kodi, as I see it) and does not introduce new features (but improves the performance of an existing feature), I opted not to implement it as an addon. If the direction this is going seems ok, I'd

  * clean up the code formatting
  * add error handling
  * figure out how to properly link Kodi with libjpeg
  * ...
  * whatever needs to be done :smiley: 

## Motivation and Context

For thumbnailing/showing large JPEG files, the full image is decoded / held in memory / scaled down, which is wasteful. This patch reads only a fraction of the data (for large images, where it hurts most). For details refer to

> https://github.com/LuaDist/libjpeg/blob/master/libjpeg.txt#L1151

> Smaller scaling ratios permit significantly faster decoding since fewer pixels need be processed and a simpler IDCT method can be used.

(it's the same for libjpeg-turbo, but this is the first link google spat at me)

## How Has This Been Tested?

I tried the prototype on my x86-64 development machine and my Amlogic based box attached to the TV. Works as intended and, yep, it's faster.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by waldheinz** [comment]
Although this is very empirical, for my ARM set top box and a folder of images in the ballpark of 4000x6000px², this patch makes the difference between:

* constantly going OOM and generating maybe one thumb per two seconds and
* filling a screen full of thumbs in about a second (and now we're I/O bound by the NFS mount over Wifi, not CPU bound)

For my i7 dev machine the difference is not really perceptible except if you have an eye on the CPU load while generating thumbs.

I'd really appreciate some help with getting the linking right, as I cannot reproduce the CI failures here. For my dev machine and coreelec based build system, it "just works". What am I missing?

I'll split off the code from the header tomorrow, thanks for the initial feedback.

**Comment by Rechi** [comment]
> libjpeg-turbo is already a hard dependecy of Kodi, as I see it

This isn't true, libjpeg-turbo isn't a direct dependency of Kodi. Why do you think so?

**Comment by notspiff** [comment]
Note there is a JpegImage in git history. We used libjpeg-turbo some years
ago.

Did u check if ffmpeg can do the same?

Den tir. 27. nov. 2018, 23:00 skrev Rechi <notifications@github.com:

**Comment by waldheinz** [comment]
> This isn't true, libjpeg-turbo isn't a direct dependency of Kodi. Why do you think so?

Hmm, because IIRC the configure step told me it was missing and it's mentioned here:

> https://kodi.wiki/view/HOW-TO:Compile_Kodi_for_Ubuntu

But grepping through the source tree it seems it's mainly used by `TexturePacker`, which seems to be a build-time tool. Is this a deal breaker? I guess there are very few Kodi installations which lack `libjpeg` or `libjpeg-turbo` (the code in this PR works with both), but I really have no idea what's the state on Android/iOS/.... I'll have a look if this can be done with ffmpeg directly and report back.

> Note there is a JpegImage in git history. We used libjpeg-turbo some years ago.
> Did u check if ffmpeg can do the same?

I'll have a look what the old `JpegImage` did and if the scaled reading trick is possible with ffmpeg.

While I'm at it, one of the regulars here might want to take the time and try this out. It really makes the difference between "oh crap, this image viewer is useless" and "it's fine", and there is still room for improvement. I really think Kodi needs "something like this", that's why I posted that code here to get a discussion started. :+1:

**Comment by waldheinz** [comment]
So I've had a look at FFMpeg and here's what I've found:

* it uses the mjpeg decoder when decoding a plain JPEG/JFIF file (checked by examining the output of `ffplay <image.jpg>`)
* that decoder does not seem to [support scaled decoding](https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/mjpegdec.c#L2785)

**Comment by notspiff** [comment]
In that case i guess we should resurrect
https://github.com/notspiff/imageencoder.jpeg-turbo

Den ons. 28. nov. 2018, 08:53 skrev Matthias Treydte <
notifications@github.com:

**Comment by candrews** [comment]
> So I've had a look at FFMpeg and here's what I've found:
> 
>     * it uses the mjpeg decoder when decoding a plain JPEG/JFIF file (checked by examining the output of `ffplay <image.jpg>`)
> 
>     * that decoder does not seem to [support scaled decoding](https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/mjpegdec.c#L2785)

Perhaps the best solution for the longer term is to submit a patch to the ffmpeg project implementing scaled decoding?

**Comment by zag2me** [comment]
Did this ever get up-streamed in the end? Or is this PR a dead end?

I was just capturing a video for the forums and it shows perfectly how slow Kodi is to generate the thumbnails. Creating artist and album thubmnails is slow on 4K setups, this PR would hopefully make it smoother on my Shield.

 https://www.youtube.com/watch&v=zwZqjJOtenA

**Comment by pkerling** [comment]
We haven't heard back from @waldheinz about `JpegImage`. I guess this could also be because it was/is not entirely clear whether we want this solution in the first place.

Personal opinion: Having it in ffmpeg would be nice, but it is not a requirement for me. ffmpeg is not aimed at working with still pictures, so I think it is reasonable to use other libraries for that purpose if needs justify the effort required (and someone is willing to do it of course). @notspiff do you agree?

**Comment by waldheinz** [comment]
> because it was/is not entirely clear whether we want this solution in the first place

Mainly this. Thing is, adding scaled reading to ffmpeg is beyond my interest and capabilities. I also think relying on ffmpeg for image reading, while being convenient and allowing to keep the list of dependencies (and maintenance burden) for Kodi short, is not likely to give the best user experience in general. Faster JPEG reading is one aspect of this, reading HEIF images is another:

> https://trac.ffmpeg.org/ticket/6521

And there are probably more issues. I can't decide how Kodi wants to go forward with those issues, but if the decision is made that linking against libjpeg(-turbo) is ok for Kodi, I'm willing to bring this PR forward to an accrptable state.

Having this functionality in an plugin is IMHO only worth the additional effort (and the risk that many users will not have the plugin installed when they would actually benefit from it very much) if there is a reasonable number of platforms or Kodi installations where libjpeg is not readily available.

**Comment by notspiff** [comment]
I already have this working just fine in an addon. Need some core
adjustments so i am waiting for v19 cycle.

Den lør. 23. mar. 2019, 10:05 skrev Matthias Treydte <
notifications@github.com>:

**Comment by phunkyfish** [comment]
@waldheinz do you want to progress this or close it?

**Comment by waldheinz** [comment]
I would be willing to update this when it‘s been decided if that functionality is actually wanted / needed.

Per @notspiff it seems an plugin implementation offering similar performance is already available. I do not know how to benefit from that, though.

**Comment by phunkyfish** [comment]
@notspiff thoughts?

**Comment by phunkyfish** [comment]
@notspiff is this in an addon now? I.e. is this PR obseleted?

**Comment by notspiff** [comment]
It will certainly never be merged in core, we ripped out jpeg-turbo a long
time ago. I have an addon but i have not looked at it in a long time, nor
is it likely i will in a while. Sits in my repos if anyone wants to pick it
up.

tor. 16. apr. 2020, 19:44 skrev phunkyfish <notifications@github.com>:

**Comment by phunkyfish** [comment]
Going to close this, can be reopened at a later date if required.

**Pull request closed without merging**
