### PR TITLE
fix dlfcn-win32 include after p8-platform rename

### PR DESCRIPTION
**Pull request by FernetMenta**

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build addons

**Comment by FernetMenta** [comment]
jenkins build addons please

**Comment by FernetMenta** [comment]
beyond my skills @opdenkamp @fetzerch @wsnipex could you follow up?

**Comment by akva2** [comment]
you simply change the line i pointed to, and make it just ${CMAKE_INSTALL_PREFIX}/include. and remove the following 3 lines (the if(WIN32) bit).

**Comment by akva2** [comment]
note that kodiplatform and kodi sets prefixed include paths as well. so this will make things inconsistent.

**Comment by Montellese** [comment]
IIRC I added that win32 specific include path because one of the header files that we share with kodi core couldn't handle the include path including the "platform" bit because there the header file is simply part of `xbmc/addons/include`. But I don't know if that's still the case.

**Comment by FernetMenta** [comment]
objections if I merge this? at least it fixed current build for win32. you can still adapt cmake to whatever you prefer

**Comment by MartijnKaijser** [comment]
@Memphiz ping. Jenkins needs some binary addons love as the ios builder isn't doing something.

**Comment by opdenkamp** [comment]
fine with me

**Comment by Memphiz** [comment]
sorry for that - should be fixed ... might need to kill and retrigger ... sry - on the run

**Pull request merged**
