### PR TITLE
Whitespace

### PR DESCRIPTION
**Pull request by hudokkow**
## Description
Extracted from https://github.com/hudokkow/xbmc/pull/4

Follow up to https://github.com/xbmc/xbmc/pull/14020

PRing now because I've been rebasing this for 12 days and it's a PITA.
Should not have any functional changes and I would like to merge it as soon as possible, if jenkins agrees.

~~First **9 commits will go away** from this PR once https://github.com/xbmc/xbmc/pull/14020 goes in.~~ **Already in master.**

## Motivation and Context
General cleanup. I needed a solid ground to check, grep and replace copyright notices with SPDX counterparts.

Similarly to https://github.com/xbmc/xbmc/pull/14020, it proved almost impossible to do it consistently with all the trailing space poking around.
I took the hammer approach and nuked **every** trailing space.

## How Has This Been Tested?
Linux build tested and brief runtime.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Cleanup (non-breaking change, hopefully)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Review by Rechi — DISMISSED** [review]
- don't change addons/*, if those aren't upstreamed
- don't change  project/Win32BuildSetup/tools/7z/*, aren't those files direct copies from 7z?

There is a massive amount of changes which are not white space only.

**Comment by hudokkow** [comment]
> There is a massive amount of changes which are not white space only.

Those were the commits that went in in https://github.com/xbmc/xbmc/pull/14020. They shared the initial branch.

Fixed, rebased and jenkins is green.
Button is yours, @Rechi.

**Review by Rechi — COMMENTED** [review]
Don't know if this repo is upstream for `addons/resource.language.en_gb` and `addons/webinterface.default`, but the important blockers are fixed now.

**Comment by hudokkow** [comment]
`addons/resource.language.en_gb` is our main language addon.

`addons/webinterface.default` is `Chorus 2` AFAIK. I'm not actually sure it is considered master but it had a few commits over the years. Apart from that, https://github.com/xbmc/chorus2 seems to be newer (v2.4.2 vs v2.4.4).

**Comment by hudokkow** [comment]
Removed `addons/webinterface.default` changes. Doesn't make any sense changing it here if it is not master location.

No need for another jenkins run. Removed changes don't touch code.

**Comment by garbear** [comment]
I can almost hear the jenkins merge conflict comments piling up

**Comment by hudokkow** [comment]
Yeah, happened this morning with https://github.com/xbmc/xbmc/pull/14020 but this one is much worse.

**Comment by garbear** [comment]
and I thought I was so popular when I woke up to so many of my PRs commented

**Pull request merged**
