### PR TITLE
[groovy] Update to 2.4.21

### PR DESCRIPTION
**Pull request by a-andre**
## Motivation and Context

Groovy 2.4.4 is unsupported and vulnerable to privilege escalation.
See https://issues.apache.org/jira/browse/GROOVY-9824.

To reduce the risk of breaking functionality by API changes groovy hasn't be updated to a newer version (2.5.x or 3.x).

Jar file was downloaded from https://dl.bintray.com/groovy/maven/

## How Has This Been Tested?

Untested

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
Are you aware that groovy is only used to build Kodi and isn't actually included in the build?

Otherwise this is likely harmless.

**Comment by garbear** [comment]
To expand on @lrusak's comment, the vulnerability to privilege escalation does not apply to us, because the vulnerability is only possible with groovy input, and our input is our trusted code.

**Comment by lrusak** [comment]
> To expand on @lrusak's comment, the vulnerability to privilege escalation does not apply to us, because the vulnerability is only possible with groovy input, and our input is our trusted code. But thanks for reporting anyways.
> 
> @lrusak is there a reason for close?

Never had a reply from the author. I also think things like compiled jars should be added from trusted team members. 😄

**Comment by a-andre** [comment]
Sorry, for the late response. I'm aware the groovy is only used at build time. But IMO vulnerable files shouldn't be part of the repository especially if there is an easy fix. Other scripts on a developers systems might use the vulnerable jar (somehow) to do harm.
I agree, a trusted team member should update the compiled jar.

**Pull request closed without merging**
