### PR TITLE
[skin][estuary]Replace non-DFSG-free fallback fanart picture

### PR DESCRIPTION
**Pull request by basilgello**
## Description

Original 'addons/skin.estuary/extras/home-images/movie.jpg' is licensed under 'CC-2.0' which turns out to be not Debian Free
Software Guidelines (DFSG) free:

https://wiki.debian.org/DFSGLicenses#Creative_Commons_Attribution_Share-Alike_.28CC-BY-SA.29_v3.0

## Motivation and Context

To avoid rejection from Debian:

https://lists.debian.org/debian-multimedia/2021/01/msg00356.html

I decided to replace the picture in question with a DFSG-free one from this link:

https://pxhere.com/en/photo/760926

which is licensed under 'CC0-1.0' (Creative Commons Zero) license.

## Screenshots (if appropriate):

Before:

image

## Types of change
- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [x] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by basilgello** [comment]
@DaveTBlake @ronie please review and merge this ASAP as I have to import Git snapshot to Debian to avoid pulling Kodi from bullseye (again).

I took the picture from pxhere and resized it to fit the original size of existing one (1280x746). Since it is a fallback for movie file. I don't know how to test it, but can do if told how.

**Review by DaveTBlake — APPROVED** [review]
I have no problem with changing image for 19.0 final for copyright on Debian.  It is up to @ronie to sign off on your image choice

**Review by ronie — CHANGES_REQUESTED** [review]
@basilgello there's a black bar at the top & bottom of the image (which does not appear to be there on the original image), mind fixing that?

also please use a little bit of jpeg compression to reduce the file size, it's currently more than 3 times the size of the old image.

**Comment by ksooo** [comment]
Maybe a dumb question. Where in Estuary is this image used? I can't remember that I have seen it anywhere.

**Comment by jjd-uk** [comment]
> Maybe a dumb question. Where in Estuary is this image used? I can't remember that I have seen it anywhere.

Fanart view when the parent folder 3 dots is selecred and as a fallback image if there's no fanart for movie/tv show

image

**Comment by basilgello** [comment]
> @basilgello there's a black bar at the top & bottom of the image (which does not appear to be there on the original image), mind fixing that?

Done!

> also please use a little bit of jpeg compression to reduce the file size, it's currently more than 3 times the size of the old image.

Also done!

**Comment by basilgello** [comment]
> > Maybe a dumb question. Where in Estuary is this image used? I can't remember that I have seen it anywhere.
> 
> Fanart view when the parent folder 3 dots is selecred and as a fallback image if there's no fanart for movie/tv show
> 
> image

**Review by ronie — APPROVED** [review]
thx!

**Comment by garbear** [comment]
thanks, not only does this improve licensing but the new image is a fresh welcome change!

**Pull request merged**
