### PR TITLE
[EPG][PVR] Guide window: Show channels without EPG data

### PR DESCRIPTION
**Pull request by ksooo**
- Show channels without EPG data in PVR Guide window
- When selecting an EPG "gap" (usually labeled "no information available"), switch to the associated channel

Feature was requested here: http://forum.kodi.tv/showthread.php?tid=239713

### CODE REVIEW

**Comment by ksooo** [comment]
@xhaggi mind taking a look.

**Comment by xhaggi** [comment]
+1

**Comment by xhaggi** [comment]
one question about the second commit: is there any advantage other than all channels starts at the same time if we have this gap items?

**Comment by ksooo** [comment]
First, you need something you can click on for switching to the associated channel. For channels without any EPG data, before this PR, there was simply nothing.

Second, it's for consistency. Gap tags are not new. They were inserted already at the start of the channel grid to begin of the first event and also in gaps between actual EPG data, but inconsistently not to fill the gap from the end of the last event to the end of the EPG grid.

**Comment by xhaggi** [comment]
okay thanks for explaining it, no objections then

**Comment by ksooo** [comment]
jenkins build this please

**Pull request merged**
