### PR TITLE
[json-rpc] Fix 'Artist Slideshow' addon not working for PVR radio channels…

### PR DESCRIPTION
**Pull request by ksooo**
… providing artist information via RDS. We must not cut off the music info tag from the pvr channel item.

Addon uses 'GetItem' to get the artist for playing item which did not handle items correctly which both handle a 'CPVRChannel' and a 'CMusicInfoTag'. The music info tag was cut off, thus no artist information available. Fix is to keep both tags.

@pkscout fyi
@phunkyfish mind looking at the code change?  
@DaveTBlake do we need an API bump for this? If yes, minor or micro number increase?

### CODE REVIEW

**Review by phunkyfish — COMMENTED** [review]
Should this if statement and the next one not be consolidated now that the `break` has been moved?

**Comment by DaveTBlake** [comment]
>do we need an API bump for this? If yes, minor or micro number increase?

Yes, internal implementation change => patch (micro?) number bump e.g. 11.15.**1** please

**Comment by ksooo** [comment]
> Should this if statement and the next one not be consolidated now that the break has been moved?

Not sure what you mean. Can you explain in more detail, please?

**Comment by phunkyfish** [comment]
There are now two `if (player == Video)` conditions (lines 176 and 217) following each other due to the change. My comment is questioning whether these can now be combined or whether they should stay separate.

**Comment by Tolriq** [comment]
GetItem is used by anything that displays what Kodi is currently playing.
With this change the returned fileitem is different so the returned data is probably quite different.

**Comment by ksooo** [comment]
> With this change the returned fileitem is different so the returned data is probably quite different.

 Are you just guessing or do you have some prove that this PR breaks something?

**Comment by ksooo** [comment]
> My comment is questioning whether these can now be combined or whether they should stay separate.

 I will combine them. Thanks.

**Comment by ksooo** [comment]
@phunkyfish @DaveTBlake I addressed your comments.

**Comment by Tolriq** [comment]
@ksooo  I have a little knowledge JSON so it's a more than educated guess, IMO the real question would be have you tested for regressions?

Previously the item parsed and returned to caller was ```CServiceBroker::GetPVRManager().PlaybackState()->GetPlayingChannel() ``` now it's ```g_application.CurrentFileItem()``` and since this "fix" something this means that those items are different.

I don't know the difference between the content of those 2 fileItems but they are for sure different and your change have for sure some impacts on every remote that displays what kodi is playing.

I do not have full PVR setup but common JSON to test would be:
```{"id":90,"jsonrpc":"2.0","method":"Player.GetItem","params":{"properties":["album","albumartist","artist","episode","art","file","genre","plot","rating","season","showtitle","studio","imdbnumber","tagline","title","track","year","streamdetails","originaltitle","playcount","runtime","duration","cast","writer","director","userrating","firstaired","displayartist"],"playerid":1}}```
on multiple different PVR content and see the differences.

**Comment by ksooo** [comment]
> Previously the item parsed and returned to caller was CServiceBroker::GetPVRManager().PlaybackState()->GetPlayingChannel() now it's g_application.CurrentFileItem() and since this "fix" something this means that those items are different.

The items returned by GetPlayingChannel() and CurrentFileItem() must be identical in case a pvr channel is currently played. The latter is checked via the call to IsPVRChannel(). The bug that is fixed here is that an additional music info tag which might be attached to the playing pvr radio item was cut off. Consequence of the bug was, that the music info tag properties of the playing item could not be retrieved. In case that due to the change some clients break, they need to be adjusted, because they are not properly handling items which can be both "channels" and "music". This is nothing new. For example, we have that for music videos, which are both "music" and "video".

**Comment by ksooo** [comment]
I double-checked the implementation and behavior is as I expect it: The PVR channel property values have higher priority than the music info tag properties. In case both the musicinfo tag and the channel implement a field, the channel value wins. So, no regressions.

**Review by phunkyfish — APPROVED** [review]
👍

**Comment by Tolriq** [comment]
There's something that does not match between the explanation and what the PR does.

> The items returned by GetPlayingChannel() and CurrentFileItem() must be identical in case a pvr channel is currently played.

But they are not as this PR change what is returned.

> The bug that is fixed here is that an additional music info tag which might be attached to the playing pvr radio item was cut off. 

The change is that you no more use the same source item. If both items are supposed to be identical then the fix should be on the calling side. So adding the missing tags to ```GetPlayingChannel()```
If both items are meant to be different then the question is why the other one was used in the first place and what other difference in those items is present.

**Comment by ksooo** [comment]
> But they are not as this PR change what is returned.

 They are. Please distinguish between "same instance" and "same content" (technique vs semantics).

 I'm not going to take lengthy discussions on this kind of basic stuff, sorry.

**Comment by Tolriq** [comment]
No problem as for all the other PVR serialization problem I'll stop asking for fix when problem arise. (Like all the things that JSON says are arrays but PVR returns as strings in this exact getItem)

**Comment by ksooo** [comment]
> No problem as for all the other PVR serialization problem I'll stop asking for fix when problem arise. (Like all the things that JSON says are arrays but PVR returns as strings in this exact getItem)

 What kind of nonsense is that? If you encounter a problem, open an issue here and if you have a point, we will be happy to assist. I'm not aware of any of those PVR JSON-RPC issues you mentioned. Open an issue, describe what is not working and we will see what we can do about that.

**Comment by Tolriq** [comment]
Just in case it was reported many times: https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/epg/EpgInfoTag.cpp#L164-L166 DeTokenize is wrong the API requires array since like 5 kodi versions. There's probably side effects and solution is probably to handle this at getItem side.

**Comment by ksooo** [comment]
Open an issue and I will have a look. No issue no problem.

**Comment by ksooo** [comment]
Now it's me going off topic for this PR:

```
PVR.Details.Broadcast": {
    "extends": "Item.Details.Base",
    "properties": {

...
      "cast": { "type": "string" },
      "director": { "type": "string" },
      "writer": { "type": "string" },
```

So, what is your point here???

**Comment by Tolriq** [comment]
The same serialization is made for Player.GetItem (Or maybe it's at another place did not took time to search) 
And definition is then https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/types.json#L862

**Comment by DaveTBlake** [comment]
Elsewhere in video these are arrays @ksooo , and they all should tie up as general list items here
```
"List.Item.Base": {
    "extends": [ "Video.Details.File", "Audio.Details.Media" ],
    "properties": {
...   
   "writer": { "$ref": "Array.String" },
      "studio": { "$ref": "Array.String" },
      "mpaa": { "type": "string" },
      "cast": { "$ref": "Video.Cast" },
  ```

**Comment by ksooo** [comment]
An EPG tag is not video. So, while it could make sense to have the same definition for same semantics, it is not a bug if they are not.l equal.

**Comment by DaveTBlake** [comment]
It kind of is a bug @ksooo , or at least more than just semantics. The case in point `Player.GetItem` returns "List.Item.All" which extends "List.Item.Base", that specifies "writer" etc. as an array. 

An EPG tag may not be the same as a video tag internal to Kodi, but in the API  if a common property name is used by differnt kinds of item, then all the definitions of it need to match.

**Comment by ksooo** [comment]
Can GetItem actually be used to get EPG tags? Are we starting to mix up things here?

**Comment by Tolriq** [comment]
Totally off topic but let's finish it.
Player.GetItem says it returns "List.Item.All" that definition says the field "writer","cast","director", ... are arrays. When a PVR channel is playing kodi returns a string, this breaks the definition and every strong typed client that rely on the schema to parse the object fails because schema says: I'll return an array and Kodi returns a string. (Meaning a field can be either a string or array making the schema useless)

This is completely a bug. I have added workaround to ignore wrong returned data after all the reports but this means that I can't display that data to users when they are playing PVR stuff. This is not a major deal as most don't use strong typed things and I have workaround so stopped asking.

For your edit: I quickly searched for "director" serialization and posted that one, there's many something else directly in PVRChannel that triggers that, but the end result is there, when Kodi plays PVR Player.GetItem returns data that breaks the schema definition.

**Comment by ksooo** [comment]
Again: Can GetItem actually be used to get EPG tags? Are we starting to mix up things here?

**Comment by DaveTBlake** [comment]
>Can GetItem actually be used to get EPG tags?

I don't know, sorry I don't have a PVR setup I can test, I suggest perhaps you do that @ksooo. What does Player.GetItem return for "writer", etc.

**Comment by ksooo** [comment]
Now (!) I see the problem: PVRChannel mixes in EPG tag fields when serializing own data! What a mess (there since 2014).
 As we have found out, EPG tag data are not compatible as they are not derived from List.Item.All.

https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/channels/PVRChannel.cpp#L84-L95

Then, we're facing actually a bug.

**Comment by ksooo** [comment]
@Tolriq  you made your point. Well done. Now let's move the discussion how to fix over to the issue you now should write for the epg serialization problem.

**Pull request merged**
