### PR TITLE
[RFC] Thread local database handling

### PR DESCRIPTION
**Pull request by xhaggi**
This introduces thread local database instances accessible via the CDatabaseManager. 
The main goal is holding only one connection/database instance per thread and do not open/close per method call or pass database instances as method parameters to the underlying implementations.

@Montellese @jimfcarroll mind taking a look?

### CODE REVIEW

**Comment by arnova** [comment]
Nice. Will the Get()-ers always return non-NULL (what happens in case of e.g. db open failure)?

**Comment by xhaggi** [comment]
If we can't establish a database connection an exception is thrown.

**Comment by FernetMenta** [comment]
why do you think thread local key-value pairs are appropriate here?

**Comment by xhaggi** [comment]
I want to avoid sharing database connections between threads and I also want to reduce the amount of `CDatabase` instances we create.

**Comment by Paxxi** [comment]
I was thinking about a more non-intrusive method, basically use a connection pool and have db.Open() check out a connection from the pool and db.Close() return it back to the pool. Should be doable without touching everything db related.

I haven't gone through everything yet but is thread local the correct method here? It could be troublesome in a Job or callback expecting to see a db instance and getting nothing because it's on the wrong thread.

**Comment by xhaggi** [comment]
> I was thinking about a more non-intrusive method, basically use a connection pool and have db.Open() check out a connection from the pool and db.Close() return it back to the pool. Should be doable without touching everything db related.

how does it fit into threads? we need to avoid sharing the same connection between threads.

> I haven't gone through everything yet but is thread local the correct method here? It could be troublesome in a Job or callback expecting to see a db instance and getting nothing because it's on the wrong thread.

why should a thread rely on a database instance of another thread? do we share database related states between different threads?

**Comment by xhaggi** [comment]
@Paxxi the main goal of this PR is to avoid the calls to Open/Close. Some classes use a `CDatabase` member to overcome this in a particular case or pass it as parameter, but in most cases we call Open, do something and call Close. Why should we do that if we know that we access the database again in the next few seconds. Sure with sqlite it's not a real problem (I've never done some performance tests) but if you use external MySQL database server this could be a bottleneck.

**Comment by FernetMenta** [comment]
I see no reason to use low level concepts like thread local for a database. Why do we have multiple db connections and not a single instance?

**Comment by xhaggi** [comment]
> Why do we have multiple db connections and not a single instance?

We have a multi-thread application and sqlite can only handle one transaction per connection.

> I see no reason to use low level concepts like thread local for a database.

Let me know how to reach the goal in that case? a single connection per thread sounds reasonable to me.

**Comment by Montellese** [comment]
Haven't had time to look at it yet or think about it but just wanted to throw in that CDatabase connections are counted so if you do Open() several times you don't always open a new connection. So Open(), Open(), Close(), Close() may look like two connections but it's actually just one.

**Comment by xhaggi** [comment]
@Montellese right, that's the reason why i've put `CDatabase` into a thread local to avoid multiple instances per thread.

**Comment by FernetMenta** [comment]
> We have a multi-thread application and sqlite can only handle one transaction per connection

I have seen quite a couple of db applications and none of them was using thread local storage. IMO a single connection is sufficient. If it isn't the problem is somewhere else.

**Comment by xhaggi** [comment]
Take a look at https://www.sqlite.org/threadsafe.html

> Multi-thread. In this mode, SQLite can be safely used by multiple threads provided that no single database connection is used simultaneously in two or more threads.

**Comment by Montellese** [comment]
> I have seen quite a couple of db applications and none of them was using thread local storage. IMO a single connection is sufficient. If it isn't the problem is somewhere else.

We are doing database queries (mostly reading, some writing) in a lot of different threads in parallel (core, video scanner, addons, JSON-RPC, UPnP, ...). Our database wrapper only supports two simultaneous data sets to be active so you can only evaluate / execute two queries at the same time so having a single connection would completely break the whole application. But that is more of a limiation of the database wrapper implementation (who writes his own database wrapper these days anyway?).

**Comment by FernetMenta** [comment]
In this mode it blocks internally, hence there is no benefit over a single connection with a lock. I seriously doubt that a db not capable of dropping a column has a highly sophisticated transaction handling optimize d for performance.

**Comment by FernetMenta** [comment]
> We are doing database queries (mostly reading, some writing) in a lot of different threads in parallel (core, video scanner, addons, JSON-RPC, UPnP, ...).

this is still at the very lower end of what typical db applications do.

**Comment by xhaggi** [comment]
Okay no problem, we can close it.

**Comment by FernetMenta** [comment]
Sorry, I hope I did not discourage you on this endeavour but I think our main problems are on the application layer. Every task accesses all and everything at any time. I think we should try to solve those problems first.

**Comment by Montellese** [comment]
@FernetMenta: Unfortunately those are much more difficult and much more work so I wouldn't stop people from doing changes to the system that may not be the ideal solution but are better than what we have now.

**Comment by FernetMenta** [comment]
@Montellese but it's always those not ideal changes which make architecture decay.

**Comment by Montellese** [comment]
@FernetMenta: Take the database schema as an example. We have been talking about completely re-writing it ever since I joined the team 4 years ago and nothing has happened yet. If I had stopped making changes to the video library/database because of that we would still have the same feature set as 4 years ago.

**Comment by FernetMenta** [comment]
@Montellese that's a different story. You did not introduce new concepts by make changes to the schema.

**Pull request closed without merging**
