### PR TITLE
[fix] Allow mixed Audio&Video playlists

### PR DESCRIPTION
**Pull request by VioletRed**
Avoid trying to play music videos with PAPlayer.

Fix bug in commit d09993ea7c840b632f75a0090fd6fe4b4f1f9722

### CODE REVIEW

**Comment by VioletRed** [comment]
@FernetMenta, could you take a look at this?

**Comment by FernetMenta** [comment]
thanks
jenkins build and merge

**Comment by VioletRed** [comment]
Is there a problem with the OSX_64 building machine? It doesn't seem like it even started building.

> Building remotely on OSX-i5-1-macminivault (osx osx64 ios atv2 osx32 darwin osxallbuilds) in workspace /Users/Shared/jenkins/workspace/OSX-64
 > /usr/bin/git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > /usr/bin/git config remote.origin.url git://github.com/xbmc/xbmc.git # timeout=10
Fetching upstream changes from git://github.com/xbmc/xbmc.git
 > /usr/bin/git --version # timeout=10
 > /usr/bin/git fetch --tags --progress git://github.com/xbmc/xbmc.git +refs/pull/*:refs/remotes/origin/pr/* +refs/heads/*:refs/remotes/xbmc/* +refs/heads/*:refs/remotes/origin/* # timeout=40
Checking out Revision 2a5aaae1b85d14807e89ba549c2b5b8ea1cedb21 (detached)
 > /usr/bin/git config core.sparsecheckout # timeout=10
 > /usr/bin/git checkout -f 2a5aaae1b85d14807e89ba549c2b5b8ea1cedb21 # timeout=20
FATAL: Could not checkout null with start point 2a5aaae1b85d14807e89ba549c2b5b8ea1cedb21
hudson.plugins.git.GitException: Could not checkout null with start point 2a5aaae1b85d14807e89ba549c2b5b8ea1cedb21

**Comment by FernetMenta** [comment]
build error not related

**Pull request merged**
