### PR TITLE
[Texturepacker] - removesdl

### PR DESCRIPTION
**Pull request by Memphiz**
This removes SDL from TexturePacker and replaces its functionality in favor of an imagedecoder abstraction with with implementations for libgif, libpng and libjpeg. This is a followup of the last devcon discussion for the goal to remove SDL (which might be a bit liquid now).

@davilla here it is ...

It also fixes the completly broken win32 projects files and removes MakeDDS because it wasn't used @MartijnKaijser  @ronie - correct me if MakeDDS was used by some then i will try to fix it - but its a pita.

### CODE REVIEW

**Comment by Memphiz** [comment]
rebased updated and squashed ... @uNiversaI ping we have a proper texturepacker package for windows now which has no dependencies and is self contained ... 

iirc you had a wiki or something which provided the tool - please update it to use this in the future:

http://mirrors.kodi.tv/build-deps//win32/texturepacker-1.0.0-win32.7z

**Comment by wsnipex** [comment]
I'lL add a texturepacker package for ubuntu as well, after this in merged.

**Comment by ronie** [comment]
wiki updated: http://kodi.wiki/view/TexturePacker

**Comment by Memphiz** [comment]
thx :)

**Comment by Memphiz** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
@wsnipex something bad happened when cloning the flac encoder repo ... you something about it? (see jenkins logs).

**Comment by Montellese** [comment]
Maybe a temporary github problem as most builds worked fine?

**Comment by Memphiz** [comment]
come on jenkins build this please

**Comment by wsnipex** [comment]
win32 error unrelated, github timeout.

**Comment by Memphiz** [comment]
Merging in 8 hours if no objections - thx wsnipex for sharing the Fun ;)

**Comment by uNiversaI** [comment]
@Memphiz It just prints a lot of useless messages like **This is a PNG - lets load it via libpng...** etc but otherwise seems to work fine.

**Comment by Memphiz** [comment]
> NUL the output to only get errors printed ... thx for testing (the output might be useless to you and users - but once there is a problem it might be good to have it).

**Comment by uNiversaI** [comment]
@Memphiz 

do you actually see any errors?
I see this

```
...unable to load image Fanart_Fallback_Music_Small.jpg
...unable to load image Fanart_Fallback_Small.jpg
```

**Comment by Memphiz** [comment]
@uNiversaI nope see: http://pastebin.com/gbF73MGH

windows 7 ultimate 64 bit here - with skin.confluence

**Comment by uNiversaI** [comment]
yes same here. wont load.

**Comment by Memphiz** [comment]
they look wonkey in github already ... i will try to look into it tomorrow maybe

**Comment by Memphiz** [comment]
found and fixed the jpeg detection error - will need to recompile the texturepacker.exe, redo the package and reupload.

**Comment by Memphiz** [comment]
@uNiversaI mirrors should be synced i think - can you repull the texturepacker and test again please?

**Comment by uNiversaI** [comment]
@Memphiz thanks that seems to work ok now! Let me know if there is anything you need that I can do.

**Comment by Memphiz** [comment]
jenkins build and merge

**Pull request merged**
