### PR TITLE
[nfs] change connection timeout to 30sec

### PR DESCRIPTION
**Pull request by CvH**
## Description
Change the connection timeout of the nfs client to 30 sec.

## Motivation and context
Since https://github.com/xbmc/xbmc/pull/15686 kodi fails to playback files from a nfs share if the hdd needs to spin up. The 5 sec timeout is set too short, its not enough time to spin up a HDD. For samba kodi uses a [30sec timeout](https://github.com/CvH/xbmc/blob/c82dcac90fa7112b657b42c587fa13ee38ebbb4c/xbmc/settings/AdvancedSettings.cpp#L262).

## How has this been tested?
Putting the values into advancedsettings.xml
```
<advancedsettings version="1.0">
  <network>
    <nfstimeout>30</nfstimeout>
  </network>
</advancedsettings>
```

## What is the effect on users?
No errors anymore if the HDD at the NAS needs to spin up before playback.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

needs changes to the wiki https://kodi.wiki/view/Advancedsettings.xml#network

### CODE REVIEW

**Comment by DaveTBlake** [comment]
To my knowledge the 5s default was deliberate and therefore not a bug to fix and therefore backport. If 5s is too short for any system then it can be configured (or set to the original infinity) by an entry in advancedsettings.xml so this is user reslovable.

If we want to change the default value for v20 then OK, but an improvement and no backport.

**Comment by arnova** [comment]
@DaveTBlake : FYI, we had similar issues with Curl and Smb in the past and we also fixed that by bumping the timeout to even 30 seconds. See https://github.com/xbmc/xbmc/commit/73be9522c13601f17bd2800ac379fa32611f9cfe and https://github.com/xbmc/xbmc/commit/6f5a05435b28b9f434063afb2ddf1afdfcbe6e92 . So IMO it even makes sense to change the NFS timeout to 30 secs.

**Comment by DaveTBlake** [comment]
Sure @arnova I would be good with 30s. 

FWIW I have set the value in my home installation back to the old to forever behaviour which never gave me any issues.

**Comment by arnova** [comment]
@CvH : Can you please change the value in this PR to 30 secs? Then it's consistent with smb/curl.

**Comment by CvH** [comment]
@arnova I intentionally didn't raised the numbers too much because these hack has the side effect that you get a frozen gui while you wait for the timeout, so if your source is down/... for some reason you have a 30sec frozen Kodi. 
I chose a number that should fix the most problems without increasing the problems too much.

A frozen gui is not a good experience, if you use Kodi with a unstable WLAN this is pure joy. 30 secs is a long time and basically feels like Kodi is crashed.

Just to clarify this is just a dirty hack like https://github.com/xbmc/xbmc/commit/73be9522c13601f17bd2800ac379fa32611f9cfe and https://github.com/xbmc/xbmc/commit/6f5a05435b28b9f434063afb2ddf1afdfcbe6e92 . 

A real fix would would require proper handling in Kodi for all kind of connection problems. 
Similar problems could be observed at the addon-repository and pvr (likely others too).

**Comment by arnova** [comment]
> @arnova I intentionally didn't raised the numbers too much because these hack has the side effect that you get a frozen gui while you wait for the timeout, so if your source is down/... for some reason you have a 30sec frozen Kodi. I chose a number that should fix the most problems without increasing the problems too much.
> 
> A frozen gui is not a good experience, if you use Kodi with a unstable WLAN this is pure joy. 30 secs is a long time and basically feels like Kodi is crashed.
> 
> Just to clarify this is just a dirty hack like [73be952](https://github.com/xbmc/xbmc/commit/73be9522c13601f17bd2800ac379fa32611f9cfe) and [6f5a054](https://github.com/xbmc/xbmc/commit/6f5a05435b28b9f434063afb2ddf1afdfcbe6e92) .
> 
> A real fix would would require proper handling in Kodi for all kind of connection problems. Similar problems could be observed at the addon-repository and pvr (likely others too).

The real fix would be making filesystem operations asynchronous (threaded) but implementing this is non-trivial. 

For now I still believe it would be best if the timeout setting is consistent with SMB/Curl.

**Comment by CvH** [comment]
changed to 30sec

**Comment by chewitt** [comment]
I plan to merge this over the weekend unless there are any further objections?

**Comment by arnova** [comment]
No, go ahead. No biggy anyway

**Pull request merged**
