### PR TITLE
fixed: External subtitles in custom folder did not work with url encoded files

### PR DESCRIPTION
**Pull request by arnova**
Apparently this has always been broken but never been noticed: Playing URL-encoded movie from eg. http + autoloading an external subtitle stored in the custom sub folder on hd.

### CODE REVIEW

**Comment by mkortstiege** [comment]
So basically `ChangeBasePath` now just adds the missing url decode? What about the other spots where strMovieFileNameNoExt is used? Would be way easier to review and follow without the var renaming ;)

**Comment by arnova** [comment]
@mkortstiege : It basically does an url decode yes. But in theory it could also work the other way around (although less likely): eg. playing a file from hd and having subtitles on an url-encoded filesystem (e.g. webdav). That's why I used ChangeBasePath() which was specifically written for cases like this.

By other you mean only the "rar/zip" case on the bottom of the same function, right? 

Couldn't perform the fix without the rename. Perhaps you want me the split it into 2 commits, with the first one first renaming the var?

**Comment by arnova** [comment]
@mkortstiege : Updated

**Comment by mkortstiege** [comment]
Besides the really not obvious function name it looks good to me. jenkins build this please.

**Comment by arnova** [comment]
FYI: The name was "invented" by JM, not me, I only wrote the function implementation ;-)

**Comment by ace20022** [comment]
fyi there's a large refactoring in progress: https://github.com/xbmc/xbmc/pull/6096 and https://github.com/mkortstiege/xbmc/compare/subsearch_refactor

**Comment by arnova** [comment]
@ace20022 : When is that going in? Mind rebasing on mine, or the other way around (I don't mind either way)?

**Comment by ace20022** [comment]
Get this one in first, because no one knows when the other is finished ;)

**Comment by arnova** [comment]
@mkortstiege : If you're good with this then, please hit the button.

**Pull request merged**
