### PR TITLE
[lib][taglib] Updated taglib that fixes a crash when playing flac files

### PR DESCRIPTION
**Pull request by Paxxi**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by fritsch** [comment]
@Paxxi Thank you very much and also thanks to @wsnipex who has built the linux ppa packages.

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
@wsnipex can you review the changes to unified depends?
I removed the make -C ... stuff as there's no makefiles in the build dir or any dir
rm -rf build should work as clean right? afaik cmake stores everything build-related in there

**Comment by Paxxi** [comment]
Meh no rush, need to redo this, I probably failed at thinking:)

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
looks fine

**Comment by Paxxi** [comment]
@mkortstiege and @koying mind runtimetesting this on mac and android?

**Comment by Paxxi** [comment]
jenkins build and merge please

**Pull request merged**
