### PR TITLE
[guilib] fix: clear m_expressions in ClearIncludes()

### PR DESCRIPTION
**Pull request by phil65**
Also adds missing handling of expressions in ClearIncludes().
@xhaggi

### CODE REVIEW

**Comment by ronie** [comment]
just wondering, is there any benefit over defining them in colors/default.xml?

**Comment by xhaggi** [comment]
thanks for fixing the clear of `m_expressions`. not sure about the second one as ronie said. but you know it better if it makes sense.

**Comment by phil65** [comment]
I would like to use them for colordiffuses related to transparency.  I dont think they really belong into theme files,  but that would be the alternative,  correct.

**Comment by ronie** [comment]
as colordiffuse is also used to colourize textures, having them in theme files is correct imo.

**Comment by phil65** [comment]
https://github.com/xbmc/skin.estuary/commit/7143c130d0b5bdb9ae6e01815e88e98f4f88613c
that should show why it can be useful. bg_alpha_hex is put directly next to bg_alpha because both need to have the same value so it doesnt make sense to allow customizing one of them in themes file. It is also easier to maintain that way.

**Comment by phil65** [comment]
Couldnt find consensus on first commit --> dropped it.
So now this only includes a fix for expressions.

**Comment by phil65** [comment]
jenkins build this please.

**Pull request merged**
