### PR TITLE
[fix] hide samba settings if smb fs not available

### PR DESCRIPTION
**Pull request by stefansaraev**
^^

cc @Montellese

### CODE REVIEW

**Comment by Montellese** [comment]
Is the define registered with the settings system (somewhere in Settings.cpp or SettingConditions.cpp)?

**Comment by stefansaraev** [comment]
uups. brainfart. updated.

**Comment by Montellese** [comment]
Should be good.

**Comment by stefansaraev** [comment]
jenkins build this please

**Comment by stefansaraev** [comment]
osx build error unrelated

**Pull request merged**
