### PR TITLE
[skin] Estouchy

### PR DESCRIPTION
**Pull request by ronie**
new default skin for touchscreen devices.

screenshot01
screenshot02
screenshot03
screenshot04
screenshot05
screenshot06
screenshot07
screenshot08
screenshot09
screenshot10

changes:
- remove the re-touched git submodule
- add estouchy to our source-code and compile it on all platforms
- use  system/settings/darwin_ios.xml instead of Settings.cpp to define it as the default skin on ios

### CODE REVIEW

**Comment by ronie** [comment]
jenkins build this please

**Comment by afedchin** [comment]
Seems you didn't change BuildSetup.bat
https://github.com/xbmc/xbmc/blob/master/project/Win32BuildSetup/BuildSetup.bat#L194
https://github.com/xbmc/xbmc/blob/master/project/Win32BuildSetup/BuildSetup.bat#L236

**Comment by ronie** [comment]
@afedchin i did: https://github.com/ronie/xbmc/commit/9bbb0bbc8961c7702dcfe1b5d7ede1a2fb1964de#diff-e4cb176f9059a98807965e7280211263L192

**Comment by afedchin** [comment]
oki. sorry for noise

**Comment by Razzeee** [comment]
Awesome, thank you!

Party

**Comment by phil65** [comment]
yup, very cool :) Thanks!

**Comment by AlwinEsch** [comment]
beautiful new skin for it
Thanks a lot :)

**Comment by notspiff** [comment]
Screenshots!

**Comment by ronie** [comment]
> Screenshots!

right, added :)

**Comment by BigNoid** [comment]
Looking good, thx @ronie !

**Comment by ronie** [comment]
jenkins build this please

**Comment by ronie** [comment]
jenkins build this please

**Comment by ronie** [comment]
rebased.

jenkins build this please

**Pull request merged**
