### PR TITLE
[cmake] HandleDepends: add file hash checking

### PR DESCRIPTION
**Pull request by Rechi**
## Description
check if correct files are downloaded

## Motivation and Context
files won't get always re-downloaded, as cmake doesn't reuse files which do not have a hash set

## How Has This Been Tested?
build a binary addon multiples times

## Types of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by wsnipex — APPROVED** [review]
thanks, been on my list for a while

**Comment by Rechi** [comment]
@wsnipex should I set `TARBALL_DIR` to `TARBALLS_LOCATION` for depends based builds?

**Comment by wsnipex** [comment]
yes, that makes sense

**Comment by Rechi** [comment]
@wsnipex updated

**Comment by wsnipex** [comment]
looks good :+1:

**Pull request merged**
