### PR TITLE
[muscidb] do not blindly add karaoke genre

### PR DESCRIPTION
**Pull request by mkortstiege**
Get rid of empty karaoke genre in music library. No brainer ..

### CODE REVIEW

**Comment by mkortstiege** [comment]
Will merge this one later today if no one objects.

**Comment by da-anda** [comment]
it is used, see https://github.com/mkortstiege/xbmc/blob/musicdb-karaoke/xbmc/music/MusicDatabase.cpp#L693

**Comment by mkortstiege** [comment]
Right, it is created whenever needed (as every other genre). This one is removing the superfluous adding while creating the views. So whenever you start with no media, you end up with an emtpy genre node for karaoke.

**Comment by da-anda** [comment]
ah sorry, I misread the line I linked and didn't see that the Genre is actually created there as well. Sorry for the noise.

**Pull request merged**
