### PR TITLE
[videoinfoscanner] properly handle excludes (fixes #16444)

### PR DESCRIPTION
**Pull request by mkortstiege**
Ensure we're properly handling .nomedia files while recursing show folders. Discussion at https://forum.kodi.tv/showthread.php?tid=251714&page=2

## Motivation and Context

https://trac.kodi.tv/ticket/16444

## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by razzeee — APPROVED** [review]

**Comment by Razzeee** [comment]
jenkins build this please

**Comment by Razzeee** [comment]
jenkins build this please

**Comment by Razzeee** [comment]
jenkins build this please

**Comment by Rechi** [comment]
@Razzeee this is for Krypton so failing IOS-ARM64, LINUX-64-Wayland and WIN-64 is expected.

**Pull request merged**
