### PR TITLE
[WinRenderer] A set of important fixes.

### PR DESCRIPTION
**Pull request by afedchin**
partially backport of #8683
- [x] fixes color range issue with dxva.
- [x] added support of rotated videos.

### CODE REVIEW

**Comment by afedchin** [comment]
jenkins build this please

**Comment by afedchin** [comment]
@MartijnKaijser you are free to merge this when it's needed.

**Comment by phate89** [comment]
@afedchin Is this fix in final stage? The color range conversion is ok but the rotated renderer doesn't. I tried a full hd portrait mode video and it gets stretched horizontally to fill the screen
http://xbmclogs.com/pxmag5ldg

**Comment by afedchin** [comment]
@phate89 please add a sample to http://trac.kodi.tv/ticket/15455 I'll take a look

**Comment by da-anda** [comment]
weird - I grabbed todays Jarvis nightly and my samples also don't work anymore

**Comment by phate89** [comment]
also in krypton doesn't work..

**Comment by da-anda** [comment]
portrait videos are also borked with pure software rendering (there they get streched like @phate89 mentioned)

**Comment by afedchin** [comment]
proper fix #8810

**Pull request merged**
