### PR TITLE
[Confluence] remove startup playlist option

### PR DESCRIPTION
**Pull request by phil65**
This stuff belongs into a separate add-on, not into skin settings.

### CODE REVIEW

**Comment by ronie** [comment]
hmmm... care to elaborate? 
why should we move stuff to an addon that can be easily handled by a skin?

**Comment by phil65** [comment]
- because it conflicts with other add-ons which do the same / similar things
- because the setting does not affect the skin itself in any form (so it´s semantically wrong to have it there)
- because less settings is a good thing

**Comment by ronie** [comment]
it never bothered me as such, but i can see some benefit of using an addon for it.
ie. only configure the addon once and it will work in any skin,
instead of having to configure it separately in the skin settings of every skin you're using.

**Comment by phil65** [comment]
Updated.

**Comment by phil65** [comment]
removed bg include again and squashed.

**Comment by mkortstiege** [comment]
@phil65 could you please rebase?

**Comment by MartijnKaijser** [comment]
@phil65 time to merge this?

**Comment by ronie** [comment]
up to @HitcherUK, he'll be maintaining Confluence from Kodi K*** and onwards :-)

**Comment by HitcherUK** [comment]
Conflicts need resolving first though.

**Comment by MartijnKaijser** [comment]
@phil65 care to rebase?

**Comment by phil65** [comment]
Rebased.

**Comment by phil65** [comment]
Removed the label, too (as suggested by ronie)

**Comment by phil65** [comment]
ping @HitcherUK 
or do you want to keep this option?

**Pull request merged**
