### PR TITLE
Bump c-pluff to 0.1.4

### PR DESCRIPTION
**Pull request by razzeee**
Bumped to the new version of https://github.com/jlehtine/c-pluff/releases/tag/0.1.4

With our patches added, I will check if we can get them upstream. I really hope I haven't overlooked anything while doing this.

More tests, eyes and comments welcome.

### CODE REVIEW

**Comment by Razzeee** [comment]
jenkins build this please

**Comment by Razzeee** [comment]
Builds are already gone :(

jenkins build this please

**Comment by Razzeee** [comment]
build failed on OSX-64 and IOS
Can somebody of the mac users have a look?

**Comment by Razzeee** [comment]
@tamland 
you should probably have a look too, as this PR is addon related if I understand it right

**Comment by Razzeee** [comment]
jenkins build this please

**Comment by tamland** [comment]
Thought this project died a decade ago:)

It seem like there have been several patches applied in our tree though (jlehtine/c-pluff/pull/1) such as d74e3dad135d9d5566868e7612839a11636a8430, so this is not going to work. We need to get in line with upstream first.

**Comment by Razzeee** [comment]
@tamland 
I tried to keep the patches, so we should be fine. Unless I missed something https://github.com/xbmc/xbmc/commit/4e2beb6919e96cbe4a63e8695aa79ec87905c272 for e.g. is unharmed, as the summary was removed again later and I reverted c-pluff to still use addon.xml instead of plugin.xml

the latest push readded https://github.com/xbmc/xbmc/commit/bbea12bc603cc521473fdcbe25d6e504611fd4cf as I reverted this by mistake. might fix the osx build problems.

jenkins build this please

**Comment by tamland** [comment]
Then I guess we're good. If you're already cherry picking patches though can bump them to a patches dir like we do with every other lib?

**Comment by wsnipex** [comment]
I know I'm repeating the same question as in your gtests PR, but is there a reason we cannot move this to depends?

**Comment by Razzeee** [comment]
@wsnipex 
I'm no expert on depends with C++, but the visual studio project embedded might keep us from doing that?
Not 100% sure why jmarshallnz did that https://github.com/xbmc/xbmc/commit/c6aefd391c8f70436021c023dcc81dda5cf3e806

**Comment by MrMC** [comment]
nothing technical prevents it, already been done in MrMC fork. For non-win platform anyway.

**Comment by MartijnKaijser** [comment]
maybe @jmarshallnz can dig his mind why he did that https://github.com/xbmc/xbmc/commit/c6aefd391c8f70436021c023dcc81dda5cf3e806

**Comment by MrMC** [comment]
I suspect it was to actually have source in master to build for windows. At one time it was in vendor branch and binary maybe. I do remember getting it to actually build from source code for osx long, long ago.

**Pull request closed without merging**
