### PR TITLE
[pvr][gui] reduce amount of dialogs for PVR 

### PR DESCRIPTION
**Pull request by xhaggi**
As internally discussed we want to reduce the amount of skin files so this is the first try.
It will merge the recording and guide info dialog together because they both hold identical information
 apart from the buttons.

As the window ids stay the same we can greatly differ between them in the skin xml to show e.g. different buttons.

guide info:
screenshot000

recording info:
screenshot001

@ronie @phil65 @mkortstiege mind taking a look.

### CODE REVIEW

**Comment by hudokkow** [comment]
Nice! +1

**Comment by phil65** [comment]
Nice first step :) code changes look fine to me, didn´t runtime-test yet though.

**Comment by xhaggi** [comment]
@ronie could you please give us a positive/negative response on this, thanks.

**Comment by metaron-uk** [comment]
+1 from me. Ping @ksooo.

If this could be merged after #7626 so I don't have to rebase I'd appreciate it as it deletes one of the files I change.

Runtime tested with my API3.0.0 mythtv prototype (#7626) which adds season/episode/EpisodeTitle to recordings and works well.
screenshot020

Also works on EPG data, but I only have EpisodeTitle available from my backend currently.

PS: I think I found a bug preventing correct display of listitem.season/listitem.episode in xbmc/GUIInfoManager.cpp, but will PR later as I want to do a bit more testing and again it will conflict with #7626. (see https://github.com/metaron-uk/xbmc/commits/seasonEpisodeDisplay )

**Comment by xhaggi** [comment]
same here any objections?

@ksooo or @Jalle19 mind taking a look too and let me know your opinion

**Comment by xhaggi** [comment]
@ronie ping you too

**Comment by Jalle19** [comment]
No objections

**Comment by ronie** [comment]
+1 from my end as well. the less dialogs, the better!

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
