### PR TITLE
[cmake] Add additional include dir for addons

### PR DESCRIPTION
**Pull request by fetzerch**
Half of the binary-addon ignore the fact, that KODI_INCLUDE_DIR contains the kodi directory itself and include directives hence must not specify it (wrong: `#include "kodi/libXBMC_addon.h"`, good: `#include "libXBMC_addon.h"`). This happens to work when building against system installed Kodi because the compiler searches additionally in `/usr/include`. When building against a different installation directory, compilation fails with include not found errors.

Instead of fixing tons of addons with blindly copied project files, I think it's simpler if we just add the basedirectory as include directory as well.

This is a followup on https://github.com/xbmc/xbmc/pull/9671, where I mentioned the problem already.
What do you think: @notspiff, @wsnipex, @hudokkow.

(Needs a jenkins run with addons to make sure it doesn't break anything!)

### CODE REVIEW

**Comment by hudokkow** [comment]
IMO the proper fix is to change addons. No, I'm not volunteering. ;-)
In the meantime, this looks sane.
Travis failure is unrelated.
jenkins build this please

**Comment by fetzerch** [comment]
If we decide to fix the addons, I would remove "kodi" from the include path and force the addon devs to specify it in the include directives. Otherwise these errors will slip in again.

Here's the full list generated from https://github.com/xbmc/repo-binary-addons:
Addons with `#include "kodi/libXBMC_addon.h"`:
```
adsp.basic
adsp.biquad.filters
adsp.freesurround
audiodecoder.sidplay
peripheral.joystick
pvr.argustv
pvr.demo
pvr.dvblink
pvr.dvbviewer
pvr.filmon
pvr.hdhomerun
pvr.hts
pvr.iptvsimple
pvr.mediaportal.tvserver
pvr.mythtv
pvr.nextpvr
pvr.njoy
pvr.pctv
pvr.stalker
pvr.vbox
pvr.vdr.vnsi
pvr.vuplus
pvr.wmc
screensavers.rsxs
```

Addons with `#include "libXBMC_addon.h"`:

```
audiodecoder.2sf
audiodecoder.dumb
audiodecoder.fluidsynth
audiodecoder.gme
audiodecoder.gsf
audiodecoder.modplug
audiodecoder.ncsf
audiodecoder.nosefart
audiodecoder.openmpt
audiodecoder.organya
audiodecoder.qsf
audiodecoder.snesapu
audiodecoder.ssf
audiodecoder.stsound
audiodecoder.timidity
audiodecoder.vgmstream
inputstream.mpd
inputstream.smoothstream
screensaver.asterwave
screensaver.cpblobs
screensaver.matrixtrails
visualization.milkdrop
visualization.projectm
visualization.vsxu
```

**Comment by wsnipex** [comment]
please read https://github.com/xbmc/audioencoder.vorbis/commit/39fa0f4455fc272f2354b6f973f8dd8a500c3b69 for rationale why we should finally fix the pvr addons. Many other addons are already fixed.

**Comment by hudokkow** [comment]
I'll have a look this weekend.
Is it jenkins build this please with addons ?

**Comment by hudokkow** [comment]
All add-ons adapted, hopefully without errors. Didn't had the time to check.

**Comment by fetzerch** [comment]
Oh wow, thanks much for the effort! Let's hope that this is a sustainable fix. It's just too easy to get wrong. There are a few more in @garbear's kodi-game repo, but I can take care of them.

Then that PR is not needed anymore.

**Comment by hudokkow** [comment]
Don't worry about the remaining add-ons. I'll have a look at them during the weekend. There's a few more bits and pieces in need of attention.

**Pull request closed without merging**
