### PR TITLE
[addon browser] check that old-style add-on fanart exists

### PR DESCRIPTION
**Pull request by rmrector**
## Description
When an add-on doesn't have an "&lt;assets&gt;" tag in their addon.xml, Kodi falls back to building a path to the "fanart.jpg" in the addon's base directory, but doesn't check that it actually exists, so can have a path to a file that doesn't exist.

This only works when browsing already installed add-ons, not browsing through a remote repo. Krypton had the same behavior as this PR. Jarvis did something else for remote repos that I can't quite figure, but since this is for backward compatibility I didn't want to spend a lot of time hunting that down.

## Motivation and Context

Skins that key on `String.IsEmpty(ListItem.Art(fanart))` can't fall back to some other fanart, [forum thread](https://forum.kodi.tv/showthread.php?tid=335941).

## How Has This Been Tested?

Quick runtime test.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Your request makes sense. Have you checked the performance differences with them and how often on this place becomes used?

**Comment by Rechi** [comment]
What's the use case where a skin has to check `String.IsEmpty(ListItem.Art(fanart))`?

**Comment by HitcherUK** [comment]
> What's the use case where a skin has to check `String.IsEmpty(ListItem.Art(fanart))`?

Visible conditions, variables, etc.

**Comment by Rechi** [comment]
Sure, but making only a fallback image visible or something completely different?

**Comment by HitcherUK** [comment]
> Sure, but making only a fallback image visible or something completely different?

Possibly but who knows what a skinner has in mind?

**Comment by rmrector** [comment]
@AlwinEsch Bah, yeah, `FillCpluffMetadata` ends up called for many add-ons (sometimes more than once) when navigating through most levels in the add-on browser.

I can add the check back to [AddonsDirectory](https://github.com/xbmc/xbmc/commit/8851244935144282a89b9a6a0d5b0cb42bea6f84#diff-b89b66685660482213bf1555338589e2L838) where it was in Krypton, so it will only check image existence for an add-on when it is actually included in the list. I had really wanted to keep this back-compat chunk together, so that when it's removed there is little chance of leaving some of it behind.

@Rechi one specific example would be if a skinner wants to fall back to one of multiple images with a 'multiimage' control rather than a single image. This also isn't limited to skinners: JSON-RPC consumers will see it as well, and they likely don't have a specialized way to fall back to some other image if the URL/path lookup fails when trying to display an image. More generally, this is just presenting bad data, which isn't good no matter how the data is currently used.

**Comment by Rechi** [comment]
I wasn't sure where the check was done in Krypton as it wasn't changed in the assets PR.
Adding it back to the AddonsDirectory vfs looks okay, AddonMgr is the wrong place for the check IMO.

**Comment by rmrector** [comment]
Moved the check to AddonsDirectory, with a second commit to allow move semantics on SetArt. I think I got that one right but I'm a C++ noob so I would appreciate it if someone double-checked that.

@Rechi and I was wrong about the JSON-RPC interface, the AddonsOperations handler does check for the existence of thumbnail/fanart when called - I found another to replace it, though; in Python, `xbmcaddon.Addon().getAddonInfo('fanart')`, but I don't think that's used often so I'd rather not scatter more backward compatibility stuff around.

Since explicitly listing the images in the "assets" tag nicely solves this problem (and the extra bits this PR doesn't cover), should the addon-checker require it be used, so that someday we might be able to remove the BC and simplify a few operations?

**Comment by Rechi** [comment]
> `xbmcaddon.Addon().getAddonInfo('fanart')`

It returns the fallback in v17, but existence of the file can be easily checked in python.

**Comment by Rechi** [comment]
You are right it wasn't checked for non installed add-ons and it still shouldn't.
It only does the check for installed add-ons and the same check existed in Krypton. @tamland you removed it.

**Comment by tamland** [comment]
> You are right it wasn't checked for non installed add-ons and it still shouldn't. It only does the check for installed add-ons and the same check existed in Krypton. @tamland you removed it.

That's what I'm not aware of existing; are you sure?

**Comment by Rechi** [comment]
Yes I'm sure as I've already checked if the code existed and where it got removed.
It was removed at #12244.

**Comment by tamland** [comment]
Ah, right

**Comment by rmrector** [comment]
Is this PR good to go? I'll try to start a conversation about "assets" and noicon/nofanart and backward compatibility around them elsewhere.

**Comment by rmrector** [comment]
Let backward compatibility die, encourage new submissions to use the "assets" tag with xbmc/addon-check#151.

**Comment by sualfred** [comment]
@rmrector 
I know backward compatibility has been dropped. I'm fine with it.
But is there a way empty the Listitem.Art(fanart) if it's not correctly defined in assets?
For us skinners it's super annoying that the fanart value is filled but no picture is shown. We have no way to work around it.

**Pull request closed without merging**
