### PR TITLE
[Fix] Reworked TrueHD MAT packer to support high bitrate Atmos streams (fix audio dropouts)

### LINKED ISSUE #16704: Kodi 18.4 crashes with high bitrate TrueHD+Atmos audio stream
### Describe the bug
When playing either an MKV or MKA file containing high bitrate (16,000kps) audio stream with HDMI pass-through Kodi 18.4 crashes: after a couple of seconds and audio begins to stutter.

I can replicate on Intel NUC8i3 (LibreElec 9.2), Odroid N2 (CoreElec latest nightly) and Windows 10 Pro (Kod 18.4 x64).

I have been playing Atmos music blu-ray rips to MKA and MKV successfully (actually I have had very occasional audio dropouts). These Atmos+TrueHD streams are usually around 7000kbps max. I have just converted the new The Beatles - Abbey Road 50th Ann. Blu-ray Audio and the Atmos stream is 16,000kbps. These files crash Kodi.

The same file playback without issue in Foobar2000.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

These files should bitstream via HDMI to my Denon AVR and play in full Atmos without crashing Kodi and without any audio dropouts.

## Actual Behavior

After selecting a file (in the library or simply a file), Kodi starts playing the crashes after a couple of seconds and after audio is heard for a few microseconds or so. Kodi in Windows crashes back to Windows. Kodi on Linux crashes then re-starts at the main Kodi menu.

## Possible Fix

Reading the logs it looks like there's a cache reading problem?

The the Kodi Crash log for the MKV I see this:

2019-10-01 10:50:30.682 T:140475424659200   DEBUG: CDVDInputStreamFile::SetReadRate - set cache throttle rate to 3123413 bytes per second

Is this cache throttle rate too small for 16,000kbps file?

### To Reproduce

Change Audio Settings to use HDMI Pass-through and set the AVR Surround format to TrueHD enabled

Download the two small 30 second sample files here:
https://drive.google.com/drive/folders/1Dv8rQ00Ur_6tVb1iXc1iZPCYMiT96gRp?usp=sharing

1.  Copy the sample mka to a Kodi audio source
2.  Play the file (from Music menu)
3.  Kodi crashes 

1.  Copy the sample mkv to a Kodi video source
2.  Play the file (from Video menu)
3.  Kodi crashes 

### Debuglog

The debuglogs can be found here:

LibreElec 9.2 on NUC8i3 playing MKA file:
https://paste.kodi.tv/efoqikuhax.kodi

LibreElec 9.2 on NUC8i3 playing MKV file (same audio stream)
https://paste.kodi.tv/konunolupo.kodi

Kodi 18.2 on Windows x64 palying MKA file:
https://paste.kodi.tv/qibofewuja.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
18.4 latest official (LibreElec 9.2 and Windows 10 Pro x64)
18.4 CoreElec Nightly dated 1 Oct 2019

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by thexai**
## Description
Reworked TrueHD MAT packer to support high bitrate Atmos streams (fix audio dropouts).

Fixes https://github.com/xbmc/xbmc/issues/16704

## Motivation and context
This is a follow up of https://github.com/xbmc/xbmc/pull/17068 referenced  PR only fix crashes but not audio dropouts.

@anssih says:

> However, audio dropouts still remain. To fix those, the TrueHD packet
> offsets will need to be dynamically scaled based on the input_timing
> field (TrueHD bytes 2-3) which allows determining the amount of time
> required between the previous frame and the current frame.

This PR basically does the aforementioned. Lets handle audio chunks of arbitrary length and variable offsets throughout the entire chain (CDVDAudioCodecPassthrough, CActiveAESink, CAEBitstreamPacker and IEC packer).

The hardest work is in MAT packer and luckily there is already a code in ffmpeg that has been able to adapt.

Seems also exist a secondary bug: 
After fixing the main issue of audio chunks > 2560 bytes that causes dropouts at specific timestamps, there are still smaller but more random dropouts....

I have solved this by reducing the number of consecutive audio chunks (basic audio units) that are stored in the buffer from 24 which is the "nominal" value to 12. I guess some part of code can't handle buffers of `TRUEHD_BUF_SIZE 61440` bytes length due some bug and memory gets corrupted/overwritten under some specific conditions when all or most of the available space is used.

## How has this been tested?
Runtime tested on RTX 2060 + Denon AVR and  Intel NUC8i3BEK + Denon AVR (Windows x64 only)
As code touched is common in all platforms should fix audio dropouts on Android and Linux too.

Forum feedback is positive 😃
https://forum.kodi.tv/showthread.php?tid=327153&pid=3065548#pid3065548

## What is the effect on users?
Fixes audio dropouts playing high bitrate TrueHD Atmos streams.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Ch1llb0** [comment]
Wouldn't this be something that warrants a back-port to v19 as a bug fix?

**Comment by thexai** [comment]
> Such 'overflow' must be legal and we should cater for it. According to nevcairiel's notes a whole MAT frame can also overflow into the next one so we should also cater for that.

All this is already implemented and is handled in this PR. Otherwise it would not work well.

I answered the question why it had been assumed in the code (which exists now) that all frames are equal to 2560 bytes. It was simply the easiest way to start supporting TrueHD at the time (years ago) it was implemented. This has surprisingly worked correctly 95% of the time without considering all cases.

**Comment by graham8** [comment]
> the track seems to run at about 2x the normal speed

This may be because of a scaling issue which was corrected in https://github.com/xbmc/xbmc/commit/ebb64f16735b72f6f7cd1cd3eed2c93e7f5c0fe3

**Comment by thexai** [comment]
@VonMagnum 
Try this new build: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20211020-0f949470-fix-TrueHD-Matrix-arm64-v8a.apk with PaPlayer

**Comment by graham8** [comment]
> It still runs around 2x normal speed.

I think this problem pre-dates this patch.

**Comment by VonMagnum** [comment]
> > It still runs around 2x normal speed.
> 
> I think this problem pre-dates this patch.

I have no idea what's causing it, but the official KODI 19.2 build doesn't have the issue (it does have the issue with high bit-rate Atmos files).  That fix got my INXS "Kick" Atmos album working without skips (MKV).  The issue appears to only be with .MKA files, which aren't gapless with PaPlayer anyway (might be better to run it with Videoplayer for now for that reason even without it showing the current track).

**Comment by graham8** [comment]
> has similar duration in time (same magnitude order) that other audio formats:

That's what I suspected.  12 frames seems as good any other number from my tests.

**Review by fritsch — APPROVED** [review]
Better than current implementation, we make progress.

**Comment by apguy** [comment]
Works perfectly on coreelec. 

Thank you

**Comment by mitzsch** [comment]
May I ask if it could be possible to get this awesome patch reworked for the FFmpeg implementation? FFmpeg is suffering from the exact same behavior described here and any other software using it as a basis is also affected.  I´ve also seen that these modified files here share many similarities with the FFmpeg libavformat/spdifenc.c file so it shouldn´t be impossible, should it?

**Comment by graham8** [comment]
Wouldn't this question be better put to the FFmpeg team?

**Comment by mitzsch** [comment]
Right! I just wanted to ask here to reach out to the guys who made this patch! :)
I already opened a ticket over at the trac.ffmpeg.org page (https://trac.ffmpeg.org/ticket/9569) - hopefully, someone sees it over there, sadly ffmpeg is just a mirror on github.

**Pull request merged**
