### PR TITLE
[cmake] Add platform specific cmake search configurations

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
This enables a platform to specifically define at a more global level search parameters for cmake find_* calls.

## Motivation and context
For Apple platforms, we have the issue of things like homebrew populating libraries into cmakes default search paths. In the event we may not have libs created (eg Fmt). This just allows us to lock down search paths to things we actually want on some platforms.

Im not sure if its best done as in 2481f3fb58d8ed4342bc7779b5eba7984f04c273 or if its better to just add as a toolchain variable. The main reason i went this way is there already is windows specific stuff that could use this as well such as in https://github.com/xbmc/xbmc/blob/a4f66924c3c5ddf6fcd0e0038020ff94cffbd213/cmake/modules/FindMariaDBClient.cmake#L12-L16
I dont have the time right now to do the full testing on windows, hence why its not done in this PR, but i would think its most likely best to use this for it as well. Essentially any platform non linux/freebsd we always provide and expect our libs to be used, so we probably should just lock search paths down.

Due to this change, ive also updated PATHS usage in some cmake find_* calls. Generally HINTS is used if a path to something is generated (ie pkgconfig call, or our depends_path), and PATHS is a last resort hard coded. cmake docs say https://cmake.org/cmake/help/latest/command/find_library.html

> Search the paths specified by the HINTS option. These should be paths computed by system introspection, such as a hint provided by the location of another item already found. Hard-coded guesses should be specified with the PATHS option.

For our purposes its probably just splitting hairs, and i havent changed everything over.

NO_DEFAULT_PATH may be the most drastic measure, but as shown in above for windows, and also the removals of apple targeted options (eg FindSpdlog.cmake), its probably just easier to lock it down to expected search paths and be done with the continually occurring issues being raised about individual system setups finding more stuff added by some obscure thing to system paths

## How has this been tested?
Jenkins build for all platforms

## What is the effect on users?
N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by wsnipex** [comment]
I'd expect ${DEPENDS_PATH}/lib to cause issues on Linux with system libs since this could override paths from pkgconfig.
I'd go with locking other platforms down via toolchain

**Comment by fuzzard** [comment]
The HINTS are just a search item, so if it doesnt find anything, it goes onto the pkg-config var as a path, and if theres nothing there, further down the search chain cmake uses.

On a linux build without any CI stuff (eg a regular user/system) depends_path is set to ${CMAKE_BINARY_DIR}/${CORE_BUILD_DIR} so it will search the lib/include folder inside the build dir. It wont find anything (unless enable options are on) and will continue on the rest of the normal search paths.

**Comment by howie-f** [comment]
quick test reveals nothing evil with my system libs during configure. (usually i'm the one hitting edge cases, harhar)

<details>
<summary>Debian Bookworm</summary>
<pre>
-- The CXX compiler identification is GNU 12.2.0
-- The C compiler identification is GNU 12.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Source directory: /home/fhw/xbmc
-- Build directory: /home/fhw/.tmp/.kodi-build21
-- Generator: Single-configuration: Release (Unix Makefiles)
-- CMake Version: 3.25.1
-- System type: Linux
-- Found MOLD: /usr/local/bin/mold  
-- Linker: mold
-- Host architecture is little-endian
-- Core system type: linux
-- Platform: x11
-- CPU: x86_64, ARCH: x86_64-linux
-- Cross-Compiling: FALSE
-- Execute build artefacts on host: 
-- Depends based build: 
-- statx is available
-- Checking to see if CXX compiler accepts flag -msse
-- Checking to see if CXX compiler accepts flag -msse - yes
-- Checking to see if CXX compiler accepts flag -msse2
-- Checking to see if CXX compiler accepts flag -msse2 - yes
-- Checking to see if CXX compiler accepts flag -msse3
-- Checking to see if CXX compiler accepts flag -msse3 - yes
-- Checking to see if CXX compiler accepts flag -mssse3
-- Checking to see if CXX compiler accepts flag -mssse3 - yes
-- Checking to see if CXX compiler accepts flag -msse4.1
-- Checking to see if CXX compiler accepts flag -msse4.1 - yes
-- Checking to see if CXX compiler accepts flag -msse4.2
-- Checking to see if CXX compiler accepts flag -msse4.2 - yes
-- Checking to see if CXX compiler accepts flag -mavx
-- Checking to see if CXX compiler accepts flag -mavx - yes
-- Checking to see if CXX compiler accepts flag -mavx2
-- Checking to see if CXX compiler accepts flag -mavx2 - yes
-- Found SSE: 1  
-- Found SSE2: 1  
-- Found SSE3: 1  
-- Found SSSE3: 1  
-- Found SSE4_1: 1  
-- Found SSE4_2: 1  
-- Could not find hardware support for AVX (missing: _AVX_TRUE) 
-- Could not find hardware support for AVX2 (missing: _AVX2_TRUE) 
-- Found Git: /usr/bin/git (found version "2.39.2") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1") 
-- Found CCache: /usr/bin/ccache (found version "4.7.5") 
-- Found ClangFormat: /usr/bin/clang-format (found version "14.0.6") 
-- Found FlatC Compiler: /bin/flatc (found version "2.0.8")
-- Found JsonSchemaBuilder: /home/fhw/.tmp/.kodi-build21/build/bin/JsonSchemaBuilder  
-- Found Lzo2: /usr/lib/x86_64-linux-gnu/liblzo2.so  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.13") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.39") 
-- Found GIF: /usr/lib/x86_64-linux-gnu/libgif.so (found version "5.2.1") 
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "62") 
-- Building internal TexturePacker
-- Shipping internal TexturePacker
-- Internal TexturePacker will be executed during build
-- Found Alsa: /usr/lib/x86_64-linux-gnu/libasound.so (found version "1.2.8") 
-- Could NOT find Avahi (missing: AVAHI_CLIENT_LIBRARY AVAHI_COMMON_LIBRARY AVAHI_CLIENT_INCLUDE_DIR AVAHI_COMMON_INCLUDE_DIR) 
-- Could NOT find CAP (missing: CAP_LIBRARY CAP_INCLUDE_DIR) 
-- Found Dav1d: /usr/lib/x86_64-linux-gnu/libdav1d.so (found version "1.0.0") 
-- Found DBus: /usr/lib/x86_64-linux-gnu/libdbus-1.so (found version "1.14.8") 
-- Found Cdio: /usr/lib/x86_64-linux-gnu/libcdio.so (found version "2.1.0") 
-- Found Iso9660pp: /usr/lib/x86_64-linux-gnu/libiso9660++.so (found version "2.1.0") 
-- Could NOT find LCMS2 (missing: LCMS2_LIBRARY LCMS2_INCLUDE_DIR) 
-- Could NOT find LircClient (missing: LIRCCLIENT_LIBRARY LIRCCLIENT_INCLUDE_DIR) 
-- Could NOT find MDNS (missing: MDNS_LIBRARY MDNS_INCLUDE_DIR) 
-- Found MicroHttpd: /usr/lib/x86_64-linux-gnu/libmicrohttpd.so (found version "0.9.75") 
-- Found Python3: /usr/include/python3.11 (found version "3.11.2") found components: Development Development.Module Development.Embed 
-- Found Python3: /usr/bin/python3 (found version "3.11.2") found components: Interpreter 
-- Could NOT find Sndio (missing: SNDIO_LIBRARY SNDIO_INCLUDE_DIR) 
-- Found UDEV: /usr/lib/x86_64-linux-gnu/libudev.so (found version "252") 
-- Found udfread: /home/fhw/.tmp/.kodi-build21/build/lib/libudfread.a (version: "1.1.2")
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.14") 
-- Found XSLT: /usr/lib/x86_64-linux-gnu/libxslt.so (found version "1.1.35") 
-- Found VAAPI: /usr/lib/x86_64-linux-gnu/libva.so (found suitable version "1.17.0", minimum required is "0.39.0") 
-- Found GLX: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found ASS: /usr/lib/x86_64-linux-gnu/libass.so (found version "0.17.1") 
-- Found Patch: /usr/bin/patch (found version "2.7.6") 
-- Found CrossGUID: optimized;/home/fhw/.tmp/.kodi-build21/build/lib/libcrossguid.a;debug;/home/fhw/.tmp/.kodi-build21/build/lib/libcrossguid-dgb.a (found version "ca1bf4b810e2d188d04cb6286f957008ee1b7681") 
-- Found UUID: /usr/lib/x86_64-linux-gnu/libuuid.so (found version "2.38.1") 
-- Found Curl: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.88.1") 
-- FFmpeg 6.0.0 not found, falling back to internal build
-- Found FlatBuffers: /usr/include/  
-- Found Fmt: /usr/lib/x86_64-linux-gnu/libfmt.so.9.1.0 (found version "9.1.0") 
-- Found FreeType: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "24.3.18") 
-- Found FriBidi: /usr/lib/x86_64-linux-gnu/libfribidi.so (found version "1.0.8") 
-- Found Fstrcmp: /usr/lib/libfstrcmp.so (found version "0.7.D001") 
-- Found HarfBuzz: /usr/lib/x86_64-linux-gnu/libharfbuzz.so (found version "6.0.0") 
-- Found Iconv: /usr/lib/x86_64-linux-gnu/libc.so  
-- Found KissFFT: /home/fhw/xbmc/xbmc/contrib
-- Found LibDvdCSS: /home/fhw/.tmp/.kodi-build21/build/lib/libdvdcss.a (found version "1.4.3-Next-Nexus-Alpha2-2") 
-- Found LibDvdRead: /home/fhw/.tmp/.kodi-build21/build/lib/libdvdread.a (found version "6.1.3-Next-Nexus-Alpha2-2") 
-- Found LibDvdNav: /home/fhw/.tmp/.kodi-build21/build/lib/libdvdnav.a (found version "6.1.1-Next-Nexus-Alpha2-2") 
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found suitable version "3.0.9", minimum required is "1.1.0")  
-- Found PCRE: /usr/lib/x86_64-linux-gnu/libpcrecpp.so  
-- Found RapidJSON: /home/fhw/.tmp/.kodi-build21/build/include (found version "1.1.0") 
-- Found Spdlog: /usr/lib/x86_64-linux-gnu/libspdlog.so (found version "1.10.0") 
-- Found Sqlite3: /usr/lib/x86_64-linux-gnu/libsqlite3.so (found version "3.40.1") 
-- Found TagLib: /usr/lib/x86_64-linux-gnu/libtag.so (found version "1.13") 
-- Found TinyXML: /usr/lib/x86_64-linux-gnu/libtinyxml.so (found version "2.6.2") 
-- Found TinyXML2: /usr/lib/x86_64-linux-gnu/libtinyxml2.so.9.0.0 (found version "9.0.0") 
-- Found EGL: /usr/lib/x86_64-linux-gnu/libEGL.so (found version "1.5") 
-- Found X: /usr/lib/x86_64-linux-gnu/libX11.so (found version "1.8.4") 
-- Found XRandR: /usr/lib/x86_64-linux-gnu/libXrandr.so (found version "1.5.2") 
-- Found LibDRM: /usr/lib/x86_64-linux-gnu/libdrm.so (found version "2.4.114") 
-- Found OpenGl: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found MariaDBClient: /usr/lib/x86_64-linux-gnu/libmariadbclient.so (found version "3.3.5") 
-- Could NOT find Shairplay (missing: SHAIRPLAY_LIBRARY SHAIRPLAY_INCLUDE_DIR HAVE_SHAIRPLAY_CALLBACK_CLS) 
-- Found Java: /usr/bin/java (found version "17.0.8") found components: Runtime 
-- Found SWIG: /bin/swig4.0 (found version "4.1.0") 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- #---- CONFIGURATION ----#
-- Platforms: x11
-- App package: org.xbmc.kodi
-- -- PATH config --
-- Prefix: /opt/omega
-- Libdir: /opt/omega/lib
-- Bindir: /opt/omega/bin
-- Includedir: /opt/omega/include
-- Datarootdir: /opt/omega/share
-- Datadir: /opt/omega/share
-- Docdir: /opt/omega/share/doc/kodi
-- CCACHE enabled: Yes
-- CLANGFORMAT enabled: Yes
-- CLANGTIDY enabled: No
-- CPPCHECK enabled: No
-- INCLUDEWHATYOUUSE enabled: No
-- ALSA enabled: Yes
-- AVAHI enabled: No
-- BLUETOOTH enabled: No
-- BLURAY enabled: No
-- CAP enabled: No
-- CEC enabled: No
-- DAV1D enabled: Yes
-- DBUS enabled: Yes
-- ISO9660PP enabled: Yes
-- LCMS2 enabled: No
-- LIRCCLIENT enabled: No
-- MDNS enabled: No
-- MICROHTTPD enabled: Yes
-- NFS enabled: No
-- PIPEWIRE enabled: No
-- PLIST enabled: No
-- PULSEAUDIO enabled: No
-- PYTHON enabled: Yes
-- SMBCLIENT enabled: No
-- SNDIO enabled: No
-- UDEV enabled: Yes
-- UDFREAD enabled: No
-- XSLT enabled: Yes
-- VAAPI enabled: Yes
-- GLX enabled: Yes
-- VDPAU enabled: No
-- MARIADBCLIENT enabled: Yes
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fhw/.tmp/.kodi-build21
</pre>
</details>

<details>
<summary>Debian Bullseye</summary>
<pre>
-- The CXX compiler identification is GNU 10.2.1
-- The C compiler identification is GNU 10.2.1
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Source directory: /home/fhw/xbmc
-- Build directory: /home/fhw/.tmp/.kodi-build21
-- Generator: Single-configuration: Release (Unix Makefiles)
-- CMake Version: 3.18.4
-- System type: Linux
-- Found MOLD: /usr/local/bin/mold  
-- Linker: mold
-- Check if the system is big endian
-- Searching 16 bit integer
-- Searching 16 bit integer - Using unsigned short
-- Check if the system is big endian - little endian
-- Host architecture is little-endian
-- Core system type: linux
-- Platform: x11
-- CPU: x86_64, ARCH: x86_64-linux
-- Cross-Compiling: FALSE
-- Execute build artefacts on host: 
-- Depends based build: 
-- statx is available
-- Checking to see if CXX compiler accepts flag -msse
-- Checking to see if CXX compiler accepts flag -msse - yes
-- Checking to see if CXX compiler accepts flag -msse2
-- Checking to see if CXX compiler accepts flag -msse2 - yes
-- Checking to see if CXX compiler accepts flag -msse3
-- Checking to see if CXX compiler accepts flag -msse3 - yes
-- Checking to see if CXX compiler accepts flag -mssse3
-- Checking to see if CXX compiler accepts flag -mssse3 - yes
-- Checking to see if CXX compiler accepts flag -msse4.1
-- Checking to see if CXX compiler accepts flag -msse4.1 - yes
-- Checking to see if CXX compiler accepts flag -msse4.2
-- Checking to see if CXX compiler accepts flag -msse4.2 - yes
-- Checking to see if CXX compiler accepts flag -mavx
-- Checking to see if CXX compiler accepts flag -mavx - yes
-- Checking to see if CXX compiler accepts flag -mavx2
-- Checking to see if CXX compiler accepts flag -mavx2 - yes
-- Found SSE: 1  
-- Found SSE2: 1  
-- Found SSE3: 1  
-- Found SSSE3: 1  
-- Found SSE4_1: 1  
-- Found SSE4_2: 1  
-- Could not find hardware support for AVX (missing: _AVX_TRUE) 
-- Could not find hardware support for AVX2 (missing: _AVX2_TRUE) 
-- Found Git: /usr/bin/git (found version "2.30.2") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found CCache: /usr/bin/ccache (found version "4.2") 
-- Found ClangFormat: /usr/bin/clang-format (found version "11.0.1-2") 
-- Found FlatC Compiler: /usr/bin/flatc (found version "1.12.0")
-- Found JsonSchemaBuilder: /home/fhw/.tmp/.kodi-build21/build/bin/JsonSchemaBuilder  
-- Found Lzo2: /usr/lib/x86_64-linux-gnu/liblzo2.so  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.37") 
-- Found GIF: /usr/lib/x86_64-linux-gnu/libgif.so (found version "5.1.9") 
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "62") 
-- Building internal TexturePacker
-- Shipping internal TexturePacker
-- Internal TexturePacker will be executed during build
-- Found Alsa: /usr/lib/x86_64-linux-gnu/libasound.so (found version "1.2.4") 
-- Could NOT find Avahi (missing: AVAHI_CLIENT_LIBRARY AVAHI_COMMON_LIBRARY AVAHI_CLIENT_INCLUDE_DIR AVAHI_COMMON_INCLUDE_DIR) 
-- Could NOT find CAP (missing: CAP_LIBRARY CAP_INCLUDE_DIR) 
-- Found Dav1d: /usr/lib/x86_64-linux-gnu/libdav1d.so (found version "0.7.1") 
-- Found DBus: /usr/lib/x86_64-linux-gnu/libdbus-1.so (found version "1.12.24") 
-- Found Cdio: /usr/lib/x86_64-linux-gnu/libcdio.so (found version "2.1.0") 
-- Found Iso9660pp: /usr/lib/x86_64-linux-gnu/libiso9660++.so (found version "2.1.0") 
-- Could NOT find LCMS2 (missing: LCMS2_LIBRARY LCMS2_INCLUDE_DIR) 
-- Could NOT find LircClient (missing: LIRCCLIENT_LIBRARY LIRCCLIENT_INCLUDE_DIR) 
-- Could NOT find MDNS (missing: MDNS_LIBRARY MDNS_INCLUDE_DIR) 
-- Found MicroHttpd: /usr/lib/x86_64-linux-gnu/libmicrohttpd.so (found version "0.9.72") 
-- Found Python3: /usr/include/python3.9 (found version "3.9.2") found components: Development Development.Module Development.Embed 
-- Found Python3: /usr/bin/python3.9 (found version "3.9.2") found components: Interpreter 
-- Could NOT find Sndio (missing: SNDIO_LIBRARY SNDIO_INCLUDE_DIR) 
-- Found UDEV: /usr/lib/x86_64-linux-gnu/libudev.so (found version "247") 
-- Found udfread: /home/fhw/.tmp/.kodi-build21/build/lib/libudfread.a (version: "1.1.2")
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.10") 
-- Found XSLT: /usr/lib/x86_64-linux-gnu/libxslt.so (found version "1.1.34") 
-- Found VAAPI: /usr/lib/x86_64-linux-gnu/libva.so (found suitable version "1.10.0", minimum required is "0.39.0") 
-- Found GLX: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found ASS: /usr/lib/x86_64-linux-gnu/libass.so (found version "0.15.0") 
-- Found Patch: /usr/bin/patch (found version "2.7.6") 
-- Found CrossGUID: optimized;/home/fhw/.tmp/.kodi-build21/build/lib/libcrossguid.a;debug;/home/fhw/.tmp/.kodi-build21/build/lib/libcrossguid-dgb.a (found version "ca1bf4b810e2d188d04cb6286f957008ee1b7681") 
-- Found UUID: /usr/lib/x86_64-linux-gnu/libuuid.so (found version "2.36.1") 
-- Found Curl: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.74.0") 
-- FFmpeg 6.0.0 not found, falling back to internal build
-- Found FlatBuffers: /usr/include  
-- Found Fmt: /usr/lib/x86_64-linux-gnu/libfmt.so.7.1.3 (found version "7.1.3") 
-- Found FreeType: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "23.4.17") 
-- Found FriBidi: /usr/lib/x86_64-linux-gnu/libfribidi.so (found version "1.0.8") 
-- Found Fstrcmp: /usr/lib/libfstrcmp.so (found version "0.7.D001") 
-- Found HarfBuzz: /usr/lib/x86_64-linux-gnu/libharfbuzz.so (found version "2.7.4") 
-- Found Iconv: /usr/lib/x86_64-linux-gnu/libc.so  
-- Found KissFFT: /home/fhw/xbmc/xbmc/contrib
-- Found LibDvdCSS: /home/fhw/.tmp/.kodi-build21/build/lib/libdvdcss.a (found version "1.4.3-Next-Nexus-Alpha2-2") 
-- Found LibDvdRead: /home/fhw/.tmp/.kodi-build21/build/lib/libdvdread.a (found version "6.1.3-Next-Nexus-Alpha2-2") 
-- Found LibDvdNav: /home/fhw/.tmp/.kodi-build21/build/lib/libdvdnav.a (found version "6.1.1-Next-Nexus-Alpha2-2") 
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found suitable version "1.1.1n", minimum required is "1.1.0")  
-- Found PCRE: /usr/lib/x86_64-linux-gnu/libpcrecpp.so  
-- Found RapidJSON: /home/fhw/.tmp/.kodi-build21/build/include (found version "1.1.0") 
-- Found Spdlog: /usr/lib/x86_64-linux-gnu/libspdlog.so (found version "1.8.1") 
-- Found Sqlite3: /usr/lib/x86_64-linux-gnu/libsqlite3.so (found version "3.34.1") 
-- Found TagLib: /usr/lib/x86_64-linux-gnu/libtag.so (found version "1.11.1") 
-- Found TinyXML: /usr/lib/x86_64-linux-gnu/libtinyxml.so (found version "2.6.2") 
-- Found TinyXML2: /usr/lib/x86_64-linux-gnu/libtinyxml2.so (found version "8.0.0") 
-- Found EGL: /usr/lib/x86_64-linux-gnu/libEGL.so (found version "1.5") 
-- Found X: /usr/lib/x86_64-linux-gnu/libX11.so (found version "1.7.2") 
-- Found XRandR: /usr/lib/x86_64-linux-gnu/libXrandr.so (found version "1.5.1") 
-- Found LibDRM: /usr/lib/x86_64-linux-gnu/libdrm.so (found version "2.4.104") 
-- Found OpenGl: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found MariaDBClient: /usr/lib/x86_64-linux-gnu/libmariadbclient.so (found version "3.1.20") 
-- Could NOT find Shairplay (missing: SHAIRPLAY_LIBRARY SHAIRPLAY_INCLUDE_DIR HAVE_SHAIRPLAY_CALLBACK_CLS) 
-- Found Java: /usr/bin/java (found version "11.0.20") found components: Runtime 
-- Found SWIG: /usr/bin/swig4.0 (found version "4.0.2") 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- #---- CONFIGURATION ----#
-- Platforms: x11
-- App package: org.xbmc.kodi
-- -- PATH config --
-- Prefix: /opt/omega
-- Libdir: /opt/omega/lib
-- Bindir: /opt/omega/bin
-- Includedir: /opt/omega/include
-- Datarootdir: /opt/omega/share
-- Datadir: /opt/omega/share
-- Docdir: /opt/omega/share/doc/kodi
-- CCACHE enabled: Yes
-- CLANGFORMAT enabled: Yes
-- CLANGTIDY enabled: No
-- CPPCHECK enabled: No
-- INCLUDEWHATYOUUSE enabled: No
-- ALSA enabled: Yes
-- AVAHI enabled: No
-- BLUETOOTH enabled: No
-- BLURAY enabled: No
-- CAP enabled: No
-- CEC enabled: No
-- DAV1D enabled: Yes
-- DBUS enabled: Yes
-- ISO9660PP enabled: Yes
-- LCMS2 enabled: No
-- LIRCCLIENT enabled: No
-- MDNS enabled: No
-- MICROHTTPD enabled: Yes
-- NFS enabled: No
-- PIPEWIRE enabled: No
-- PLIST enabled: No
-- PULSEAUDIO enabled: No
-- PYTHON enabled: Yes
-- SMBCLIENT enabled: No
-- SNDIO enabled: No
-- UDEV enabled: Yes
-- UDFREAD enabled: No
-- XSLT enabled: Yes
-- VAAPI enabled: Yes
-- GLX enabled: Yes
-- VDPAU enabled: No
-- MARIADBCLIENT enabled: Yes
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fhw/.tmp/.kodi-build21
</pre>
</details>

**Pull request merged**
