### PR TITLE
[coverity] Prevent some warnings

### PR DESCRIPTION
**Pull request by ace20022**

### CODE REVIEW

**Comment by ace20022** [comment]
@fritsch Do you agree?

**Comment by ace20022** [comment]
@fritsch hmm, please don't press the button.

**Comment by ace20022** [comment]
@fritsch okay, empty line removed ;)

**Comment by fritsch** [comment]
Jep it's fine, as it is created above, I still don't really understand the coverity error :-)

**Comment by Paxxi** [comment]
Don't know what the coverity  message said but pMap  can never be nullptr as new throws on errors

**Comment by fritsch** [comment]
*** CID 1351899:  Control flow issues  (DEADCODE)
/xbmc/guilib/TextureManager.cpp: 434 in CGUITextureManager::Load(const std::basic_string<char, std::char_traits<char>, std::allocator<char>>&, bool)()
428
429         if (pMap)
430         {
431           m_vecTextures.push_back(pMap);
432           return pMap->GetTexture();
433         }
>>>     CID 1351899:  Control flow issues  (DEADCODE)
>>>     Execution cannot reach the expression "~shared_ptr" inside this statement: "frame.~shared_ptr();".
434       }
435
436       CBaseTexture *pTexture = NULL;
437       int width = 0, height = 0;
438       if (bundle >= 0)
439       {

@Paxxi

**Comment by Paxxi** [comment]
Weird one but I guess that it sees destructor being created for the outer scope which won't be reached in that code path. Not sure why it would complain though since the destructor will run anyway

**Comment by ace20022** [comment]
@Paxxi ofc, stupid me, will remove the other check too. It's a false positive imo...

**Comment by ace20022** [comment]
Added some more. @Paxxi Could you please have a closer look at https://github.com/ace20022/xbmc/commit/93372c85435adea94b38d19f4f79558c5d321b16 ?

**Comment by tamland** [comment]
@ace20022 The proper fix for cid 1287130 and 1311755 is to remove the two null check as they're  superfluous (all other constructors *will* dereference). I've fixed this in f1ea62e66e5297a btw. Would save me a rebase:)

Also, defining the default constructor like that will not initialize the members, and thus leave those version objects in an undefined state.

**Comment by ace20022** [comment]
You're right  ```mEpoch``` wouldn't be initialized. I'll drop that commit.

**Comment by ace20022** [comment]
jenkins build this please

**Pull request merged**
