### PR TITLE
[Estuary] Add widget "editor"

### PR DESCRIPTION
**Pull request by MikeSiLVO**
## Description
Added a way to hide Widgets for Movies, TV Shows, Music, Music Videos, TV (PVR), and Radio.

I used Custom_1101_SettingsList.xml as basis for new dialog. 

Throwing this up for further discussion about the opinions on this. Not sure I selected the correct items in types of changes or checklist.

## Motivation and context
Recent mention of wanting the ability to hide certain Widgets

## How has this been tested?
Turned "on/off" all or some Widgets.

## What is the effect on users?
Able to customize home screen by disabling unwanted Widgets

## Screenshots (if appropriate):

screenshot

screenshot2

screenshot4

screenshot3

screenshot5

screenshot6

screenshot7

screenshot8

screenshot9

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [X] **New feature** (non-breaking change which adds functionality)
- [X] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by jjd-uk** [comment]
I'm personally fine with the principle of this, not sure how much that matters, although I seem to be the de facto Estuary maintainer by accident. However on vacation at the moment so zero time to look the implementation used here.

Perhaps @Hitcher and @jurialmunkey can provide their views.

**Comment by MikeSiLVO** [comment]
I'm not sure of the Edit wording since it's just a toggle on/off but I thought matching it to an existing button would show that there is a place for such an option.

Perhaps a separate Widget section is an alternative to the dialog...?

**Comment by jurialmunkey** [comment]
> I'm not sure of the Edit wording

You could use "Customise widgets" instead.

> Perhaps a separate Widget section is an alternative to the dialog...?

I personally prefer it how you have it now. To me, it's much clearer to have grouped together.

For example, if you turn off the "Movies" menu item, it is immediately clear how you regain access to the widgets (re-toggle Movies menu back on). However, if the widgets were on a separate page, it wouldn't be clear why the Movies widgets were missing or how you get them back.


As to the PR itself - it all looks good/sensible to me!

**Comment by Hitcher** [comment]
> > I'm not sure of the Edit wording
> 
> You could use "Customise widgets" instead.

Or 'Show/hide widgets'.

**Comment by MikeSiLVO** [comment]
Updated to include the category widgets, removed the button that only disabled some category widgets, and added a new button to toggle the addons one.

I'll update the strings.po with whatever preferred wording is decided :)

**Comment by ksooo** [comment]
I’m not a skinner, and seeing lots of duplicated code in this pr I’m asking myself whether a new include could be created that contains the repeated code need for defining a widget editor item?

**Comment by jurialmunkey** [comment]
> I’m not a skinner, and seeing lots of duplicated code in this pr I’m asking myself whether a new include could be created that contains the repeated code needed for defining a widget editor item?

This is a good point. Can be optimised a bit. By itself, an include won't save much - only two lines - but it's not nothing either. The bigger optimisation in terms of number of lines is to move the visibility conditions into the buttons themselves, then combine everything into a single large grouplist to avoid repeating the grouplist code 6 times.

e.g.

Definition of include
```xml
<!-- Include Def -->
<include name="WidgetSelectorRadioButton"
	<control type="radiobutton" id="$PARAM[id]">
		<width>700</width>
		<include>DialogSettingButton</include>
		<label>$PARAM[label]</label>
		<onclick>Skin.ToggleSetting($PARAM[setting])</onclick>
		<selected>!Skin.HasSetting($PARAM[setting])</selected>
                <visible>$PARAM[visible]</visible>
	</control>
</include>
```

Example button
```xml
<!-- Example Button -->
<include content="WidgetSelectorRadioButton">
	<param name="id">22101</param>
	<param name="label">$LOCALIZE[31148]</param>
	<param name="setting">home_movies_categories_widget</param>
        <param name="visible">String.IsEqual(window(home).Property(widgeteditor_content),movies)</visible>
</include>
```

Then all buttons go in a single grouplist like so (also remove the enclosing group and just use a grouplist as 22000).

```xml
<control type="grouplist" id="22000">
	<orientation>vertical</orientation>
	<top>80</top>
	<left>0</left>
	<width>700</width>
	<height>630</height>
	<itemgap>0</itemgap>
	<!-- Movies Buttons -->
	<include content="WidgetSelectorRadioButton">
		<param name="id">22101</param>
		<param name="label">$LOCALIZE[31148]</param>
		<param name="setting">home_movies_categories_widget</param>
		<param name="visible">String.IsEqual(window(home).Property(widgeteditor_content),movies)</visible>
	</include>
	<!-- ... other movies widgets here ... -->
	<!-- TV Show buttons -->
	<include content="WidgetSelectorRadioButton">
		<param name="id">22201</param>
		<param name="label">$LOCALIZE[31148]</param>
		<param name="setting">home_tvshows_categories_widget</param>
		<param name="visible">String.IsEqual(window(home).Property(widgeteditor_content),tvshows)</visible>
	</include>
	<!-- ... other tvshows widgets here ... -->
	<!-- etc. -->
</control>

**Comment by MikeSiLVO** [comment]
How is adding a visible condition to ~40 buttons or so better than just 6, one for each grouplists?

**Comment by jurialmunkey** [comment]
> How is adding a visible condition to ~40 buttons or so better than just 6, one for each grouplists?

Same reason why there's only one grouplist in SettingsCategory.xml and not 100 or however many different categories of settings there actually are: it reduces replicated code and makes future maintenance and expansion easier. 

A few examples:

- The dialog style changes in the future. Edits are only needed to one grouplist, not six (or however many more get added).
- Expanding to add new categories of items simply involves adding new buttons (vs. adding another new grouplist). This is quite likely considering there's actually 12 home menu items with widgets, not just the 6 currently covered (there's also games, addons, pictures, videos, favourites, and weather).
- A button is needed which covers multiple types of menus. With separate grouplists you need to replicate the button in each group, vs simply adding one button with multiple visibility conditions. That's not currently needed but could in the future, with a good example being folding the "edit categories" button into the dialog (it does the same thing for every menu - it opens library node editor).

**Comment by MikeSiLVO** [comment]
I lessened the lines in this [followup PR](https://github.com/MikeSiLVO/xbmc/commit/bed26e928d666c5d2d6a6b895b3b561029f86a8c) where all the DialogSettingButton includes could all be the same width.

I agree with the too many grouplists. My first thought went toward doing something like I do with my [one dialog for settings](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/blob/master/16x9/custom_1114_DialogSettings.xml#L33).

```xml
<include condition="String.IsEqual(Window(Home).Property(DialogSettings),videoosd)">VideoOSDSettings</include>
<include condition="String.IsEqual(Window(Home).Property(DialogSettings),musicosd)">MusicOSDSettings</include>
<include condition="String.IsEqual(Window(Home).Property(DialogSettings),videoinfo)">VideoInfoSettings</include>
<include condition="String.IsEqual(Window(Home).Property(DialogSettings),livetv)">LiveTVSettings</include>
```

Combine 1101, 1105, and 1106 into one 1101_DialogSettings.xml using the same grouplist.

Also a good point about expanding but as I was adding the addons section I noticed there is an include when the grouplist has no items. That would need to be reworked to only show if there is not any actual addons at all installed and then it has to be based on the different widgets being on/off or not. Just seemed to be heading toward the too complicated since I wasn't sure how this PR would be received.

Personal preference maybe but I wouldn't use a radiobutton to open up the librarian node editor in the dialog so I would still have to use a new button.

Not sure how deep this PR should go but I don't mind reworking all of it 😄

**Comment by jjd-uk** [comment]
Just a note to say I won't be in a position to review for at least another 10 days when I get home.

**Comment by jurialmunkey** [comment]
@MikeSiLVO - just to be clear, I'm not suggesting my examples be included. Those are just for demonstration purposes of why switching to single grouplist would be useful for potential additions in the future. I think the current functionality is fine for this PR.

The only point is to simplify the code so future PRs are easier to implement without needing to refactor the entire dialog just to add a single button or change the width etc.

**Comment by MikeSiLVO** [comment]
I'll go in whatever direction that is decided.

I have a branch I can PR for combining the two current settings dialogs (1101 & 1105):
[Combine Dialogs](https://github.com/MikeSiLVO/xbmc/commit/8c0aebc540d1e983769bc6fa494afb578652941b)

Another branch with 2 commits. One is the same as above for combining the dialogs and a second one adding the widget "editor" to the new combined dialog:
[Combine dialogs](https://github.com/MikeSiLVO/xbmc/commit/8c0aebc540d1e983769bc6fa494afb578652941b)
[Add widget "editor"](https://github.com/MikeSiLVO/xbmc/commit/73d38ace2436ee4b53656532e7fae2f923e74ac6)

**Comment by jurialmunkey** [comment]
Code to combine the dialogs looks good - I'm always in favour of reusing dialogs where possible. 

Including buttons as a block is probably best of both worlds (use this approach myself for a lot of custom settings dialogs) - removes need for individual visibility conditions but still allows for combined visibility conditions if needed in the future. And with the button width etc. being standardised now, there's no need for the individual button includes to reduce the duplication.

> Another branch with 2 commits. One is the same as above for combining the dialogs and a second one adding the widget "editor" to the new combined dialog:

I think this is reasonable. Feels excessive to open a separate PR for combining the dialogs first.

**Comment by MikeSiLVO** [comment]
I am wondering if the Edit categories buttons should be moved from under their respective menu items to the top and get rid of one since it is the same button.

Just have one for video and one for music?

```xml
<control type="button" id="6110">
	<label>- $LOCALIZE[31157]</label>
	<include>DefaultSettingButton</include>
	<onclick condition="System.AddonIsEnabled(plugin.library.node.editor)">ActivateWindow(programs,plugin://plugin.library.node.editor/?ltype=video,return)</onclick>
	<onclick condition="System.HasAddon(plugin.library.node.editor) + !System.AddonIsEnabled(plugin.library.node.editor)">EnableAddon(plugin.library.node.editor)</onclick>
	<onclick condition="!System.HasAddon(plugin.library.node.editor)">InstallAddon(plugin.library.node.editor)</onclick>
	<enable>!Skin.HasSetting(HomeMenuNoMovieButton)</enable>
</control>
```

```xml
<control type="button" id="6120">
	<label>- $LOCALIZE[31157]</label>
	<include>DefaultSettingButton</include>
	<onclick condition="System.AddonIsEnabled(plugin.library.node.editor)">ActivateWindow(programs,plugin://plugin.library.node.editor/?ltype=video,return)</onclick>
	<onclick condition="System.HasAddon(plugin.library.node.editor) + !System.AddonIsEnabled(plugin.library.node.editor)">EnableAddon(plugin.library.node.editor)</onclick>
	<onclick condition="!System.HasAddon(plugin.library.node.editor)">InstallAddon(plugin.library.node.editor)</onclick>
	<enable>!Skin.HasSetting(HomeMenuNoTVShowButton)</enable>
</control>
```

6110 and 6120 are identical minus the id and enable ofc.

```xml
<control type="button" id="6130">
	<label>- $LOCALIZE[31157]</label>
	<include>DefaultSettingButton</include>
	<onclick condition="System.AddonIsEnabled(plugin.library.node.editor)">ActivateWindow(programs,plugin://plugin.library.node.editor/?ltype=music,return)</onclick>
	<onclick condition="System.HasAddon(plugin.library.node.editor) + !System.AddonIsEnabled(plugin.library.node.editor)">EnableAddon(plugin.library.node.editor)</onclick>
	<onclick condition="!System.HasAddon(plugin.library.node.editor)">InstallAddon(plugin.library.node.editor)</onclick>
	<enable>!Skin.HasSetting(HomeMenuNoMusicButton)</enable>
</control>
```

Change the labels to something like:
```xml
<label>$LOCALIZE[31157] ($LOCALIZE[3])</label>
```

`Edit categories (Videos)`

```xml
<label>$LOCALIZE[31157] ($LOCALIZE[2])</label>
```

`Edit categories (Music)`

Or some other variation, including adding new strings?

I don't think the enable part is necessary, and I also don't know whether or not I should add another change, but I figured I'd ask.

Lastly, do you think I should PR the other branch or wait till there's a consensus?

**Comment by jurialmunkey** [comment]
> Lastly, do you think I should PR the other branch or wait till there's a consensus?

No need for a new PR. You can keep this one and overwrite the branch with the commits from the new branch by hard resetting this branch to match the new branch. Then simply force push it back to your fork to update the PR.

```
git checkout widget_editor
git reset --hard dialogsettings_widgeteditor
git push origin +widget_editor
```

**Comment by MikeSiLVO** [comment]
Will do, thanks!

Over the years of trying to keep my mod of Aeon Nox 5 in sync with BigNoids changes helped me learn all about rebasing, hard resets, force push, and a few other things along the way.

Wasn't sure how things would progress here so I thought having a separate PR was easier to keep track of the (ongoing?) discussion but I can edit this one if you think that's the best way to proceed :)

**Comment by jjd-uk** [comment]
Yes keep it all here. Do separate commits if you think splitting will help with reviewing, then when ready for merger we can squash the commits.

**Comment by MikeSiLVO** [comment]
Ok, will update this PR now with the latest from my other branch.

First time trying a hard reset using gui only so hopefully it works but if not I will fix it using cli...

**Comment by MikeSiLVO** [comment]
Probably a good idea for me to change DialogSettings to SettingsDialog to avoid any confusion with DialogSettings.xml.
https://github.com/MikeSiLVO/xbmc/commit/f69af3734a86f766e3725109968ae351a5e96498

**Review by jjd-uk — APPROVED** [review]
LGTM, thanks a lot for this :)

**Comment by jjd-uk** [comment]
> Probably a good idea for me to change DialogSettings to SettingsDialog to avoid any confusion with DialogSettings.xml. [MikeSiLVO@f69af37](https://github.com/MikeSiLVO/xbmc/commit/f69af3734a86f766e3725109968ae351a5e96498)

Only just noticed this comment, it's a good point. If you can change PR to use SettingsDialog then in my view this can be merged.

**Comment by MikeSiLVO** [comment]
> Only just noticed this comment, it's a good point. If you can change PR to use SettingsDialog then in my view this can be merged.

Updated :)

**Comment by MikeSiLVO** [comment]
I also have another Branch where I changed the skin settings to include `_no_` if that is preferred.

https://github.com/MikeSiLVO/xbmc/commit/0360af8ff0e82b44e619aa1309a3e8323ef894aa

**Comment by jjd-uk** [comment]
> I also have another Branch where I changed the skin settings to include `_no_` if that is preferred.
> 
> [MikeSiLVO@0360af8](https://github.com/MikeSiLVO/xbmc/commit/0360af8ff0e82b44e619aa1309a3e8323ef894aa)

I assume this is the match the style of the existing Category widget setting https://github.com/xbmc/xbmc/blob/master/addons/skin.estuary/xml/SkinSettings.xml#L154

It's only very minor code cosmetics, but since you already have the code prepared I think it would be a nice to have here so code is consistent between old & new.

**Comment by MikeSiLVO** [comment]
Updated for consistency :)

**Comment by MikeSiLVO** [comment]
@jjd-uk Is there anything else you'd like me to change?

**Comment by jjd-uk** [comment]
Nope it all looks good to me.

However simply due to number of lines of code changed I'd like to get one @Hitcher or @jurialmunkey to give one more look over the code to make sure I've not missed anything before this gets merged. I'll look that get this merged by this time next weekend.

**Comment by jurialmunkey** [comment]
All looks good to me.

My only comment would be that the ID numbering in the dialog is a bit all over the place, but that's an inherited issue from the old dialogs. 

If you're feeling particularly motivated, could be an opportunity to tidy it up, but it's definitely not something worth holding up the PR any longer over either!

**Review by jurialmunkey — APPROVED** [review]

**Review by Hitcher — APPROVED** [review]
It all looks good to me.

**Comment by MikeSiLVO** [comment]
@jurialmunkey Made the ids consistent for button includes
https://github.com/xbmc/xbmc/pull/25355/commits/ccb2f3b699194a0e8e64638b065775f1ff0da723

**Comment by jjd-uk** [comment]
I intend to merge this at the weekend sometime 27th/28th July if anyone has anymore comments.

**Comment by jurialmunkey** [comment]
> I intend to merge this at the weekend sometime 27th/28th July if anyone has anymore comments.

@jjd-uk - Most recent changes all look good. No further comments from me. Big thanks to @MikeSiLVO - you've gone above and beyond in accommodating all the additional workshopping here!

**Comment by ksooo** [comment]
@jjd-uk anything that still speaks against merging this?

**Comment by jjd-uk** [comment]
> @jjd-uk anything that still speaks against merging this?

Nope I had meant to merge this by now.

**Comment by jjd-uk** [comment]
Thanks a lot for your work on this @MikeSiLVO

**Pull request merged**
