### PR TITLE
[PVR] Improve epg association by broadcast ID

### PR DESCRIPTION
**Pull request by janbar**
Using a new map `m_epgEvents` which is updated when receiving an new event and for new scanned EPG.

### CODE REVIEW

**Comment by janbar** [comment]
ping @ksooo

**Comment by janbar** [comment]
For info the container keep references of epg tag for 7 days back. It is an arbitrary value and i can update it to 1 day or other if needed.

**Comment by janbar** [comment]
@ksooo, until now function CEpgContainer.GetTagById(unsigned int iBroadcastId) do a full scan of all epg tables to retrieve epgtag by the unique broadcast Id. that causes a performance issue with RPI or slim hardware and it consumes lot of CPU during recordings update when epg association is enabled (addon tvheadend and mythtv before 2.7.4 for which i disabled this feature). Users having more than few channels cannot really use pvr addons having epg association.
So here the objective is to build a container to index globally epgtag by unique broadcast Id, and finally use it to quickly find epgtag with minimum of hardware resource. This container is ```m_epgEvents```, and here it is filled when receiving an epg event and ONLY WHEN NEEDED. That means only after an epg has been updated: to do i use the member lastScanTime of epg which contains the timestamp of last update. So the table ```m_epgScans``` is intented to save the last stamp per epg when we have processed to fill ```m_epgEvents```: So only when ```CEpg.m_lastScanTime > m_epgScans.find(epgId).second```.
IMO there is nothing expensive and here it fully resolves the performance issue. This fix will allow me to re-enable the feature for the pvr.mythtv addon, and probably it will help to resolve performance issue with tvheadend addon.

**Comment by janbar** [comment]
m_lastScanTime is set here https://github.com/xbmc/xbmc/pull/8240/files#diff-ba344e01c87a7dea3d6fdc4b67bc8c4dL402 , once epg table is refilled. I use this logged time to check if update of the new container is required.

**Comment by ksooo** [comment]
@janbar Thanks for explaining the problem and the approach for the fix. I think now I've understood. This makes all sense. No objections from my side.

But what I do not understand is why you hold past data in m_epgEvents. How is this related to this PR? It feels somehow wrong to me that m_epgEvents is not in sync with m_epg. So, if <code>CEpgContainer::GetTagById(broadcastid)</code> is used one gets data that one does not get when <code>CEpgContainer::GetById(epgId)->GetTag(broadcastid)</code> is used? This feels not okay.

**Comment by janbar** [comment]
```CEpg::GetTag(uniqueID)``` is no longer referenced and will be removed. Also its deletion could be part of this PR.
IMO Nothing is wrong; the new container is only intented to match epgtag by broadcast Id and its life-cycle is different than epg. It is unreasonable to try to build code to sync past data because this task is resource-intensive and has no reason to be. The ```m_epgEvents``` container has its own life-cycle and we purge these old data as we need: Here i propose to keep 3 days back but we can keep only one day as epg containers. Now this is not very important: The objective is to allow to match broadcast id with epgtag and to be able to associate recordings with tags which could be displayed with special icons on the screens of the EPG guide. Then some old associated tags could be no longer referenced from guide: they will be purged in according with the life-cycle of ```m_epgEvents```.

**Comment by ksooo** [comment]
Sorry, I think holding past data in the map is completely unrelated from the purpose of this PR. I want you to remove this part from the PR and to put it in a separate PR, please.

**Comment by janbar** [comment]
I am afraid to not anderstand what you mean by "holding past data". Please could you be more clear ?

Guessing you mean "keeping reference of epg tags from the past", we have to keep them or at least  using AdvancedSetting::m_iEpgLingerTime to set the period to keep instead using static value. But releasing all past references will break the associations to display the icon "play recording", which actually available for period of epg linger time.

**Comment by ksooo** [comment]
> we have to keep them for at least using AdvancedSetting::m_iEpgLingerTime to set the period to keep instead using static value

Yes, this is basically what I mean. Only difference to what you wrote above is that I want it <bold>exactly</bold> kept for AdvancedSetting::m_iEpgLingerTime, not <bold>at least</bold>. This way you keep m_epgs content in sync with m_epgEvents. If you change your code to hold data for exactly amount of time specified in AdvancedSetting::m_iEpgLingerTime and I'm fine with this PR. :-)

**Comment by janbar** [comment]
Also conflict has to be managed after merging #8247

**Comment by ksooo** [comment]
@janbar thanks a lot. All fine by me now.

**Comment by ksooo** [comment]
Sorry for bothering you again. You seem to like to use "auto" even for trivial types like int. IMO this makes code less readable and thereby contradicts the purpose of auto. Could you please change your code to use auto only for non-trivial types like iterators and such? This is how we use auto, at least in PVR and EPG code. Thx.

**Comment by janbar** [comment]
Rebased

**Comment by janbar** [comment]
I does'nt use auto for my projects, but seems here it is use since Jarvis but only for iterations. You should update the wiki to explain what you require about ```auto```.
I rebased ;)

**Comment by ksooo** [comment]
Thx.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
Some random binary addons failed to build. Definitely not related to this PR.

**Pull request merged**
