### PR TITLE
blind attempt at adjusting add-on mingw support to new paths

### PR DESCRIPTION
**Pull request by notspiff**
ran into this while trying to setup appveyor for game add-ons. this has not been adjusted for new paths or something something.

### CODE REVIEW

**Comment by Rechi** [comment]
@notspiff everything is correct in that part of code

**Comment by notspiff** [comment]
okay, then. hard to guess what's up when all i get is 'make.exe not found' :)

**Comment by Rechi** [comment]
#12104 was the fix for adding windows x64 support.
Before that `game.libretro.2048` failed to build on x64.

**Comment by notspiff** [comment]
job for game.libretro.2048 fails precisely in the same way so something is not happy on appveyor. there's some registry crap going on and msys2 warns you have to restart the shell (probably for PATH entries). meh.

**Pull request closed without merging**
