### PR TITLE
[Backport][Nexus] Adds UID / GID and permissions features in NFS

### PR DESCRIPTION
**Pull request by pduveau**
Backport from #23302

### CODE REVIEW

**Comment by lrusak** [comment]
Features typically don't get backported, only fixes.

**Comment by pduveau** [comment]
I saw few issues opened on version 20.x that can be solved with these enhancements in a future 20.2. There are users that will not be able to upgrade to version 21 due to the end of support of some devices. For example, I have an Odroid N2+ that was before under coreelec. The corelec team decided to stop upgrade Kodi over version 20.x for this device. This is the reason why I switched to Android.

**Comment by bossanova808** [comment]
Just adding as this is a common misunderstanding: CoreELEC 21 (Kodi 21) will indeed work on Odroid N2+ -> see https://coreelec.org/ - and there are alpahs already available.  

_CoreELEC 21 becomes the active development branch and it is based on CoreELEC 20. **All devices that are able to run CoreELEC 20 will also be supported by CoreELEC 21.0-Omega**._

**Comment by pduveau** [comment]
I had read something a few weeks ago (maybe 2 months) that the developments on amlogic-ng were going to be stopped because of those on amlogic-ne. I'm glad for their owners to read that this is not the case. I must have been confused. So let's forget this backport.MMyMayMainMaintMainteNowMaintenaNowNow Now that I've switched from Coreelec to Android, I don't think I'll go back. So let's forget this backport.

**Pull request closed without merging**
