### PR TITLE
Change some Lirc mappings from 'mytv' to 'livetv'

### PR DESCRIPTION
**Pull request by LS80**
It looks like there may be other entries which also need changing. With my equipment I was only able to test a devinput device on OpenELEC with the following in .kodi/userdata/Lircmap.xml.

```
<lircmap>
    <remote device="devinput">
        <livetv>KEY_TUNER</livetv>
    </remote>
</lircmap>
```

### CODE REVIEW

**Comment by mkortstiege** [comment]
Looks good to me. Ping @stefansaraev for sanity check ;)

**Comment by LS80** [comment]
`KEY_TV` is still mapped to `mytv`.

**Comment by stefansaraev** [comment]
looks ok

**Comment by LS80** [comment]
Perhaps the same change should be made to the device 'linux-input-layer'?

**Comment by Jalle19** [comment]
What's the difference between `mytv` and `livetv`?

**Comment by LS80** [comment]
By default there is no difference as both map to `ActivateWindow(TVChannels)`
See [remote.xml](https://github.com/xbmc/xbmc/blob/master/system/keymaps/remote.xml#L73).

This PR enables mapping `mytv` and `livetv` to different commands e.g.

    <keymap>
      <global>
        <remote>
          <mytv>ActivateWindow(VideoLibrary,TvShowTitles)</mytv>
          <livetv>ActivateWindow(TVChannels)</livetv>
        </remote>
      </global>
    </keymap>
 
Without this PR there seems to be little point in having both `mytv` and `livetv` as the same button sends both commands.

**Comment by Jalle19** [comment]
It seems reasonable that `mytv` would go to the TV shows node indeed and `livetv` to the TV channels node.

**Comment by LS80** [comment]
I agree. If this is merged I'll make another PR to change the `mytv` mapping in remote.xml.

**Comment by Jalle19** [comment]
Any objections?

**Comment by mkortstiege** [comment]
No objections.

**Pull request merged**
