### PR TITLE
[dvd] add missing wrapper functions

### PR DESCRIPTION
**Pull request by olafhering**
Add wrapper functions for dvdnav_angle_change,
dvdnav_get_video_resolution and dvdnav_get_current_time for static
libdvdnav.

Fixes commit 352be9c3595dd1cd4842f2344ed137631b7ff17a ("[videoplayer][dvd] Add angle selection.")
Fixes commit b5807c2d8574b7e4e3a18e269fd8878ea1bbed55 ("[VideoPlayer] Fixed DVD playing time.")

Signed-off-by: Olaf Hering <olaf@aepfle.de>

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by pkerling** [comment]
What do you intend to fix with this? The code is dead.

https://github.com/xbmc/xbmc/blob/fd83c58f36b945fbd3ea2f13191fc3cf6bc77955/xbmc/cores/VideoPlayer/DVDInputStreams/DllDvdNav.h#L107

**Comment by olafhering** [comment]
kodi will link directly to libdvdnav.so to get that non-working private shared object out of the way.

**Comment by pkerling** [comment]
This creates more questions than it answers. Please be more elaborate.

**Comment by olafhering** [comment]
Well, then lets not go down that hole.

The commit completes these two other commits, as mentioned in the commit message.

**Comment by pkerling** [comment]
@rechi What do you think? Should we remove the dead code that depends on `USE_STATIC_LIBDVDNAV`? I don't see much value in maintaining this.

@olafhering If you want to help resolve the libdvd* situation, see #15899

**Comment by olafhering** [comment]
I know nothing about DVD players.

But what I learned: there are DVD players, and then there is kodi...

Why on earth is it required mess around with internals of libdvdread in the first place?
I'm sure kodi can be adjusted to use the APIs provided by libdvdnav and libdvdread. It just takes some time.

I can likely live with the removal of the code within `USE_STATIC_LIBDVDNAV`. Among other required changes, kodi can just call directly into libdvdread.

**Comment by pkerling** [comment]
> But what I learned: there are DVD players, and then there is kodi...

Kodi is a media center, not a DVD player :-) (This is an important distinction because it implies *a lot* of additional complexity)

> Why on earth is it required mess around with internals of libdvdread in the first place?
I'm sure kodi can be adjusted to use the APIs provided by libdvdnav and libdvdread. It just takes some time.

Please do your research before making assumptions and accusations. libdvd* simply does not provide any API for reading ripped DVDs in directory structures via vfs (there are only hooks for ISOs). Therefore, it is libdvd* that has to adjust. I do not like the stdio monkey-patching either. But it's the solution we have now, and it works.

All of this is public information. See https://code.videolan.org/videolan/libdvdread/issues/3

**Comment by Rechi** [comment]
If the code isn't used remove it.

**Comment by olafhering** [comment]
Go ahead and remove the dead code.

**Comment by pkerling** [comment]
Removal PR'ed.

@olafhering As said before, contributions to a clean solution that keeps the current feature set (i.e. does not break DVD folders on remote locations) are very much welcome.

**Pull request closed without merging**
