### PR TITLE
[Estuary] Hide seekbar when video is paused

### LINKED ISSUE #17952: Subtitles are covered by OSD on pause
### Describe the feature
Here is a clear and concise description of what the problem is:

Some skins - and very notably the current Kodi default skin Estuary - have a "video paused" view that shows a UI covering the bottom and top of the screen. When viewing video with subtitles or closed captions, the UI elements cover the captions, making it harder - sometimes impossible - to read them.

This is a serious problem for people that are hard of reading, or even just when there is a lot of stuff going on in the video: I find myself pausing when viewing Japanese videos when the characters are talking very fast or one on top of each other (it is common in some types of videos), so I can take the time to read the subtitles. This effort is completely undone by over-enthusiastic skins - and Estuary is a great example although far from the only one - that like to cover the bottom 10% of the screen on pause. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I think the correct approach is to make sure that subtitles are not covered by skin UI regardless of which UI is used and its size. When paused, and a skin UI is layered over the subtitles, the subtitle position should be changed so that it is not covered - likely just raised above the bottom UI part. This is similar to how the Netflix web player behaves: when you move the mouse and a the bottom seekbar and buttons are showing, the Netflix player raises the location of the subtitles so they show above the player UI.

## Actual Behavior

Here is Estuary blocking the viewer from reading the captions:

Screenshot_20200527-182848

I've tried reporting the issue in Estuary bug report forum, but it wasn't addressed (or even acknowledged) - and I'm actually OK with that, as this is not only an Estuary problem (there are other skins with similar issues: the otherwise excellent Estouchy skin has a pause UI that takes a huge 20% of the screen, while the popular Aeon Nox skin completely covers the captions and there isn't even a part that is somewhat transparent, like in Estuary).

## Possible Fix

A possible fix is discussed in the expected behavior. Another - possibly easier - fix would be to have an alternate way to pause the video player without showing the paused view. This would also be useful for Frame Advance control for people who want to use that without the overlaying UI.

### To Reproduce

1. Play a video with subtitles or closed captions.
2. Press pause while a caption is being shown

### Screenshots 
Here are some links or screenshots to help explain the problem:

See above.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu
 - Kodi version: 18.6

### PR DESCRIPTION
**Pull request by ronie**
## Description
A request that pops up from time to time is to not cover the subtitles area when a movie is paused.

This changes Seekbar Dialog to only show a small 'paused' label instead of covering the top and bottom are of the screen.

@jjd-uk i recall you had some ideas about this as well, though not sure if you've started working on it...

## Motivation and Context
fixes https://github.com/xbmc/xbmc/issues/17952

## Screenshots (if appropriate):
before:
before

after:
ex1

ex2

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ksooo** [comment]
Could we make this a skin setting, please?

**Comment by jjd-uk** [comment]
I've been working on displaying the complete seekbar at the top when seeking (enabled by skin setting), just about complete but not fully tested yet. This is a lower impact change so is a good first step in case what I have in mind provokes prolonged debate.

**Comment by ronie** [comment]
@jjd-uk i found that mockup you've posted previously and i quite like it.
so i've adopted it (more or less) now..

ex1

also, i've added support for seeking / forwarding / rewinding to it as well:

ex2

**Comment by ronie** [comment]
> Could we make this a skin setting, please?

@ksooo i hope we can avoid that.
is there any reason you want the seekbar to cover both the top and bottom of the screen?

**Comment by ksooo** [comment]
> is there any reason you want the seekbar to cover both the top and bottom of the screen?

I don't care where it locates on the screen, what would not like to miss is the movie information (title, progress etc.) while paused. MAybe we could hide the bottom (seekbar), but not the top of the screen?

**Comment by ksooo** [comment]
What I do not like about seek bar on top while paused is that this is inconsistent. I'm not a ux designer, but I'm quite sure that having the seek bar sometimes at the bottom and sometimes elsewhere is not very good design. Users (for example myself) will expect the bar always at the same position I guess.

**Comment by jjd-uk** [comment]
The way I've done it is via a skin setting to make it entirely optional to have seekbar at the top, without the setting enabled it remains exactly the same as present. I'm away from home until the 5th Oct and unfortunately don't have my code pushed to my public github to show what I've done.

Regarding this implementation it's slightly different. I've got the numerical chapter info top left, then the seek label centred alongside the time info. If you want to push this for Alpha 2 then if it's wanted I can then make refinements for Alpha 3.

**Comment by ksooo** [comment]
> The way I've done it is via a skin setting to make it entirely optional to have seekbar at the top, without the setting enabled it remains exactly the same as present.

 That would be much appreciated.

**Comment by howie-f** [comment]
as a quick idea: is it maybe an option to show the small top-seekbar only if subtitles are enabled? not sure if the skin can actually know whether they are or not, but think that would be a nice ux. (if a skin setting is disabled we wouldn't show it at all)

**Comment by smp79** [comment]
I'd like an option to remove *all* on-screen graphics when paused. That would include not only a seek bar but any "paused" messages as well.

**Comment by smp79** [comment]
It's perfect now, thank you. I love that it auto hide itself after a few seconds.

**Comment by ronie** [comment]
@jjd-uk i've added the chaptercount, as you suggested:
chap

@smp79 makes sense, i've changed it and it will now auto-hide after a few seconds (as you already found out)


> I don't care where it locates on the screen, what I would not like to miss is the movie information (title, progress etc.) while paused.

@ksooo the info is still available on the videoosd & fullscreeninfo dialogs (even when paused), my PR does not touch those bits.

> What I do not like about seek bar on top while paused is that this is inconsistent.

the seekbar is a general overlay that can be shown all throughout the skin (if a skinner wishes to).
for example, confluence (which also displays it at the top), will have it available on every window:
confluence

imo the purpose of the seekbar is to display the player state (seeking / forwarding / pause / etc...) and not much more.
it's not really comparable (in terms of consistency) with any other dialog.

**Comment by jjd-uk** [comment]
Looks good based solely off the screenshot (as I have no access to a Kodi install while I'm away) so thumbs up from me.

**Comment by ksooo** [comment]
@ronie Sorry, I'm late to the party, but this does not work for PVR, as PVR progress (with time shift information etc.) works a bit different than 'normal' progress:

screenshot00001
screenshot00000

Grep for 'PVRProgress' in Estuary sources to see how proper progress bar for PVR needs to be implemented.

**Comment by Solarunit** [comment]
I've been waiting for this for years! Many thanks!! Can't wait to test it. :tada:

**Comment by TheMontezuma** [comment]
I love it.
I merged locally the changes with LibreELEC 9.2.6 / KODI 18.9 and I can finally pause and read subtitles as I know it from normal DVD/Bluray players.

**Pull request merged**
