### PR TITLE
[cmake/win32] Bump minimum CMake version to 3.6

### PR DESCRIPTION
**Pull request by fetzerch**
There seem to be some issues with older CMake versions on windows (< 3.4).
Therefore let's bump the minimum required version to 3.6 which introduced the VS_STARTUP_PROJECT var. We use that to allow users to directly build and run Kodi with F5. (older versions would have the ALL_BUILD target preselected which builds everything including tests and doesn't start kodi).

On windows this bump should be non-intrusive, because devs have to download and install CMake anyways manually, so let's save us some troubles.

ping: @Paxxi

### CODE REVIEW

**Comment by Paxxi** [comment]
Fully agree, there's no real reason to have an older version intalled on windows and it's a fairly important feature for usability

**Comment by fetzerch** [comment]
AppVeyor still has 3.5.1 installed. Seems like there's no way to manually update that via appveyor.yml, so it's have to wait until they have updated. Ticket: https://github.com/appveyor/ci/issues/1001

**Comment by MartijnKaijser** [comment]
Ping @fetzerch

**Comment by fetzerch** [comment]
Build fails because the mingw libs (ffmpeg, libdvd) can't be found. @Paxxi any idea?
I think the error is unrelated to this PR, other appveyor builds fail as well. Maybe we should get this one in anyways as it fixes appveyor log output.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
Appveyor is a bit special as we use pre-built ffmpeg and libdvd afaik to save time, not sure if they end up in the correct place

**Comment by fetzerch** [comment]
@Paxxi: I've temporarily added a few "dir" calls yesterday. I think it fails even to download ffmpeg/libdvdnav - even though the url works locally. Does it makes sense to try adding the files to our mirror?

**Comment by fetzerch** [comment]
Appveyor build fixed, merging.

**Pull request merged**
