### PR TITLE
[addons] workaround for pausing repository updates during playback

### PR DESCRIPTION
**Pull request by tamland**

### CODE REVIEW

**Comment by stefansaraev** [comment]
thanks. seems to work fine. this replaces #8211 right ?

**Comment by Razzeee** [comment]
I think this is just ment as a workaround for Jarvis. Nothing that should be permanently in the codebase, if I understood tamland correct yesterday.

**Comment by tamland** [comment]
It's "temporary" until a better solution for the whole don't interrupt playback problematic can be found:) The job manager workaround is equally bad so that's a dead end..

**Comment by tamland** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
@MilhouseVH care to include this in your builds (if not already) and ask users to test?

**Comment by MilhouseVH** [comment]
I've had this in my builds since [#1122](http://forum.kodi.tv/showthread.php?tid=231092&pid=2168144#pid2168144) and no complaints so far, however I have to be honest - how is this supposed to be tested?

**Comment by MartijnKaijser** [comment]
Play a video and hit repo update (i think)

**Pull request merged**
