### PR TITLE
[Android] Neon is being enabled by default

### PR DESCRIPTION
**Pull request by joseluismarti**
## Description
Since NDK 21 Arm code is built with Neon by default.

We don't need to enable it, by passing `-mfpu=neon` when compiling.

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by fuzzard — APPROVED** [review]
Should we change https://github.com/xbmc/xbmc/blob/7e58d70dbec409c9341e580f56207969965908e5/tools/depends/target/ffmpeg/Makefile#L38-L42 while your at it and just enable always for android?

**Comment by joseluismarti** [comment]
I think we should remove it as Android Clang automatically enables Neon

**Comment by joseluismarti** [comment]
Checking again `--enable-neon` is an ffmpeg configuration flag, best to keep it

**Comment by joseluismarti** [comment]
No need to change, I've checked that this flag (`--enable-neon`) is already active on armv7a target.

See configure steps for 'ffmpeg':
```
C compiler                /usr/bin/ccache /home/jenkins/android-tools/android-sdk-linux/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang
C library                 bionic
host C compiler           gcc
host C library            glibc
ARCH                      arm (cortex-a9)
version string suffix     "Kodi"
big-endian                no
runtime cpu detection     yes
ARMv5TE enabled           no
ARMv6 enabled             yes
ARMv6T2 enabled           no
VFP enabled               yes
NEON enabled              yes
...
```

**Pull request merged**
