### PR TITLE
[WindowTranslator] Fix audio/video/subtitle window dialog names

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

this will refect the same action id names, less confusion between names
since was also not documented and not officially released yet we can change them

## Motivation and context

reported comment https://github.com/xbmc/xbmc/pull/25762#issuecomment-2474545555

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CastagnaIT** [comment]
@Hitcher try test this

**Comment by Hitcher** [comment]
Thanks, will report back.

**Comment by Hitcher** [comment]
Works perfectly, thanks.

**Comment by CastagnaIT** [comment]
@Hitcher please approve so i can merge

**Review by Hitcher — APPROVED** [review]
Thanks.

**Pull request merged**
