### PR TITLE
Extend IsRemote check to some vfs paths (closes #14817)

### LINKED ISSUE #14817: Library stucks on loading when there is no Internet connection
**Description**

Kodi stucks on "Loading directory" when it is used without Internet connection.

**Steps to reproduce the bug**

1. Clean installation of Kodi 18
2. Add a sample movie to the Movies library (and retrieve its information through TMDB addon)
3. Exit Kodi
4. Disconnect the computer from Internet (i.e. unplug the Ethernet cable and/or disable WiFi)
5. Run Kodi
6. Enter the Movie library in the main menu of the Home page
7. A popup saying "Loading directory" appears and stays like that...

_Note: the same issue happens if you try to enter the "Recently added", "Genres", "Years", etc. menus from the shortcuts at the top of the Home page. The issue is probably happening also for TV Shows and other contents._

**Setup**

Kodi 18.0 beta 5 x64
Windows 10

**Debug log**

The debug log can be found [here](https://pastebin.com/7ipgjTTR).

**Forum thread**

The related Kodi forum thread can be found [here](https://forum.kodi.tv/showthread.php?tid=337149).

### PR DESCRIPTION
**Pull request by enen92**
## Description
This PR extends the `IsRemote` check to: 
- `videodb://`
- `musicdb://`
- `library://`
- `plugin://`
- `androidapp://`

 vfs paths, returning false to the check. Closes https://github.com/xbmc/xbmc/issues/14817

Credits go to @garbear for tracking the root cause in the issue comments.

## Motivation and Context
Kodi stucks on "Loading directory" when it is used without Internet connection and the user navigates to the movie or tvshow library.

## How Has This Been Tested?

Run time tested in OSX and respective test extended.

## Screenshots (if appropriate):
**Before**:
before
**After**:
after

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by DaveTBlake** [comment]
This looks fine of itself but I am curious what caused the regression, any ideas?

The other way to fix this would be in `CURL::IsLocal()` https://github.com/xbmc/xbmc/blob/eb161cdb7c4c97e9f054192c9ea9e8d00839c305/xbmc/URL.cpp#L622-#L625
After all VFS paths should be returned as local

**Comment by enen92** [comment]
@DaveTBlake thanks for looking. For what I understand `CURL::IsLocal()` is only used to check if the path belongs to localhost so I am not sure if it is a good idea to overload it with kodi vfs paths. Furthermore, some of the vfs paths are not local (e.g. `nfs://`, `smb://`), etc. Similar fixes have been paths on the exact same place so I'd prefer to do the same.

I've given this a little test on my phone (without wifi nor mobile data) and found a few more missing:
- androidapp://
- plugin://

I'll add those to this PR. If you have a music library can you also test is something is missing?

**Review by garbear — APPROVED** [review]

**Comment by DaveTBlake** [comment]
@enen92 I don't want to hold this up, but it is bugging me to understand what changed that means these vfs paths need adding to the IsRemote check. Why didn't it cause problems before? I'm sure I have used Krypton without an internet connection.  but have not been able to get a debug build going to check.

**Comment by axlt2002** [comment]
@enen92 thanks for your feedback. I was looking at your PR and saw the code: 

videodb://movies/titles
library://video/

and that is why I asked you to include also the follwoing (Kodi actually stucks with them as well):

videodb://tvshows/titles
library://music/

Sorry, but may be I'm missing a point here. Where the two inclusions I proposed are covered by the actual PR?

Thanks for the clarification.

**Comment by jjd-uk** [comment]
@axlt2002 I'm not 100% sure but I believe you are misunderstanding the code, the actual code changes are those in xbmc/utils/URIUtils.cpp I think the other changes in xbmc/utils/test/TestURIUtils.cpp are merely to extend our automated unit tests to contain usage examples so any changes in future which break this will be flagged.

**Comment by axlt2002** [comment]
@jjd-uk thanks a lot for the explaination! That was exactly my mistake in understanding!

So I will just wait for the PR to be merged! ;)

Thanks to all!

**Comment by axlt2002** [comment]
Hi guys, do you have any update about the merge of this commit? Just asking because my Kodi is actually usable with some difficulties on my tablet that I use offline... :)

Thanks for your help.

**Comment by enen92** [comment]
@axlt2002 be patient. Dave investigated the reason for a different behaviour in Krypton vs Leia and found the main reason. Unfortunately life got on the way and he could not yet come back to this PR.
I'll leave this for him to comment and merge when he has some time which likely will be today or during the following days.
The only way, if you don't want to wait a bit, is to compile Kodi containing this patch yourself and install it on your system. Otherwise just be patient, all team members are volunteers

**Comment by axlt2002** [comment]
@enen92 thanks for your feedback. Far from me to put pressure on this of course...I also develop an add-on for Kodi and I'm volunteer as well. :) It was just to have an update on this and you gave it to me, thanks.

Keep in touch and wish you all a great day!

**Review by DaveTBlake — APPROVED** [review]
Sorry for delay guys. Looking deeper it seems that the reason `IsRemote` needs these additional checks is because  there have been changes to network management in v18. Previous versions were finding more network adaptors than v18 does, for example v17 reports 5 on my Win10 PC rather than the 1 reported by `CServiceManager::GetNetwork` in v18. So potentially the network avialable check was successful in v17 even when there was no connection.  Correcting that check had the knock on effect of revealing that `IsRemote` was returning true for vfs paths, and hence producing the hang reported when trying to show the library window when internet not connected.

**Comment by axlt2002** [comment]
Thanks a lot Dave!

**Pull request merged**
