### PR TITLE
Expose various hardware blending modes to the skinning engine

### PR DESCRIPTION
**Pull request by sarbes**
## Description
This PR adds various blending options to our skinning engine, enabling our skin devs to employ more interesting effects.

For now it is OpenGL exclusive, but I'm planning to port it to OpenGL ES. DirectX would have to be covered by someone with experience in the field (maybe @thexai?). 

The advanced blending options (like "advancedscreen") would need small additions to the shader(s). On the OGL side, it needs GL_KHR_blend_equation_advanced to work. Otherwise, shader trickery would be needed. I'm curious if this can be done in DX.

## Motivation and context
More GUI effects are always nice to have :).

## How has this been tested?
I've tested it on my RX 570. I expect it to work the same on all relatively recent (<10 year old) hardware.

## What is the effect on users?
None if the skin doesn't use it. If an unsupported blend mode is used, it should reverse to the default "add".

## Screenshots (if appropriate):
kodi_blending

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by sarbes** [comment]
Well, GLES was not hard to do :).

**Comment by enen92** [comment]
Please do not forget to add this option to the dox files of the controls where it is applied :) thanks a lot for your work on this

**Comment by sarbes** [comment]
> Please do not forget to add this option to the dox files of the controls where it is applied :) thanks a lot for your work on this

I've already added a short explanation to the GUIImage.dox. Do you have something else in mind?

**Comment by enen92** [comment]
Yeah, all good. I missed your changes to guiimage.dox :)

**Comment by sarbes** [comment]
Looking at it now, I'm not sure if flexible blending would provide much value. We could do shader based blending (e.g. max(texture, diffuseTexture)), but that's a different cattle of fish.

**Pull request closed without merging**
