### PR TITLE
added: IsScreensaverInhibited info label

### PR DESCRIPTION
**Pull request by arnova**
Forgot to add this when I implemented the inhibit-screensaver builtin.

### CODE REVIEW

**Comment by arnova** [comment]
> Should be `System.IsScreensaverInhibited` (with an ed) but otherwise looks good

Well I considered that but we already had a "IsInhibit", so I named this in line with that. Ideally that should be named "IsIdleShutdownInhibited" but changing that will cause compatibility problems ofc. I will changed it as you suggested and I guess we'll have to accept the "IsInhibit"-flaw....

**Comment by garbear** [comment]
Where is 'IsInhibit' used? Ideally this should be updated to "IsInhibited" everywherer

**Comment by arnova** [comment]
> Where is 'IsInhibit' used? Ideally this should be updated to "IsInhibited" everywhere

@garbear :  Here: 
https://github.com/xbmc/xbmc/blob/b6cf019020deea3a2437758033a0dc9ef45127ee/xbmc/guilib/guiinfo/GUIInfoLabels.h#L150
https://github.com/xbmc/xbmc/blob/b6cf019020deea3a2437758033a0dc9ef45127ee/xbmc/GUIInfoManager.cpp#L1317
https://github.com/xbmc/xbmc/blob/b6cf019020deea3a2437758033a0dc9ef45127ee/xbmc/GUIInfoManager.cpp#L1807

Please note that I don't like that builtin name anyway since it doesn't give any clue about what is inhibit(ed) (;-)) So ideally it should be "IsIdleShutdownInhibited". It's also strange that there's also a System.HasShutdown-builtin which seems to do the same thing (or the comment is wrong here: https://kodi.wiki/view/List_of_boolean_conditions)

**Review by garbear — APPROVED** [review]
Thanks for pointing that out. You make a really good point about the ambiguity. I'm in favor of deprecating `isinhibit` and making it more clear.

This PR looks good.

**Comment by arnova** [comment]
> Thanks for pointing that out. You make a really good point about the ambiguity. I'm in favor of deprecating `isinhibit` and making it more clear.
> 
> This PR looks good.

Thanks, I will take care of the (dis)ambiguity in another PR then.

**Pull request merged**
