### PR TITLE
[EPG] Fix: Only notify observers for async epg event state changes, not for 'polled' events

### PR DESCRIPTION
**Pull request by ksooo**
Fixes problem reported here: http://forum.kodi.tv/showthread.php?tid=263031

@FernetMenta fyi, was just a typo/brain fart on my side.

### CODE REVIEW

**Comment by FernetMenta** [comment]
that was fast :) thanks!

**Comment by ksooo** [comment]
rebased

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
travis-ci errors are unrelated

**Comment by ksooo** [comment]
Bug reported in the forum to be fixed by this PR.

**Comment by xhaggi** [comment]
backport?

**Comment by ksooo** [comment]
no. only effects Krypton (PVR API 5.0.0 regression)

**Comment by xhaggi** [comment]
okay :)

**Pull request merged**
