### PR TITLE
[video] Video navigation window: Replace context menu items 'Set actor/artist thumb'…

### PR DESCRIPTION
**Pull request by ksooo**
… with 'Choose art' to make it possible again to add and set other artwork, not only thumbnails.

Fixes a regression introduced with v21.1, reported in the Forum: https://forum.kodi.tv/showthread.php?tid=378663&pid=3208333#pid3208333

screenshot00004
screenshot00003

Runtime-tested on macOS, latest xbmc master.

Needs backport.

@enen92 if you are around, could you review?

### CODE REVIEW

**Comment by KarellenX** [comment]
Does this regression and fix have any connection to this bug... https://github.com/xbmc/xbmc/issues/25662

**Comment by ksooo** [comment]
> Does this regression and fix have any connection to this bug... https://github.com/xbmc/xbmc/issues/25662

Unrelated.

**Comment by KarellenX** [comment]
ok, thanks.

**Review by enen92 — APPROVED** [review]
LGTM

**Pull request merged**
