### PR TITLE
Revert changes in addon lib and bump versions

### PR DESCRIPTION
**Pull request by FernetMenta**
fix FreeString

related to https://github.com/opdenkamp/xbmc-pvr-addons/pull/441

### CODE REVIEW

**Comment by opdenkamp** [comment]
got to bump depends and windows to https://github.com/opdenkamp/xbmc-pvr-addons/commit/2fb0fc22668b1efdec05e66161d6c419844ee9cd and good to go then

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by da-anda** [comment]
could this be related to the freeze/crash on splash screen I'm currently noticing whith PVRmanager enabled and TVheadend client? Once I disable PVRmanager Kodi is booting just fine again.

**Comment by opdenkamp** [comment]
could possibly have caused corruption with strange results

**Comment by FernetMenta** [comment]
jenkins build and merge

**Comment by FernetMenta** [comment]
it built on Android-Arm and failed on Android-X86. seems unrelated. no idea why it did not even start on some other platforms.

**Comment by opdenkamp** [comment]
@FernetMenta we forgot to revert the changes to libXBMC_addon.h and libXBMC_addon.cpp in here (commit db44ba5faf00cf29ac7a45ef49a933d1ef45366b)

**Comment by opdenkamp** [comment]
pr incoming

**Comment by FernetMenta** [comment]
oops, thanks!

**Comment by opdenkamp** [comment]
fyi: if you've got the add-ons checked out in /pvr-addons, then you can check API changes like this by doing `cd pvr-addons && make sync && git diff`

**Pull request merged**
