### PR TITLE
Add browse for subtitle action

### PR DESCRIPTION
**Pull request by notspiff**
This allows mapping a key to browse for subtitle in video fullscreen window. Ref forum.kodi.tv/showthread.php?tid=306428&pid=2521764

### CODE REVIEW

**Comment by da-anda** [comment]
would it make sense to also expose this via JSON-RPC? Might also be useful for smartphone remotes f.e.. What do you think?

**Comment by notspiff** [comment]
I don't see how that is related to this pr. This adds a mappable action so you do not have to hop through osd to browse.

Also i think json already supports pushing subtitles to the player.

**Comment by da-anda** [comment]
from what I have seen in the JSON-RPC methods schema you can only set a specific subtitle, but not trigger the builtin search dialog. I only mentioned that it also might be nice to have the option to trigger this builtin search dialog via JSON-RPC, which would expose the same functionality for physical remotes (via keymaps) to smartphone remotes/webinterfaces. It's no blocker, but would IMO fit within this PR. The only thing to consider when exposing this to JSON-RPC is that this method needs to be called from GUI thread I suppose (I'm not that experienced with threading).

PS: there seems to be a merge conflict atm

**Comment by notspiff** [comment]
so you want a json action to trigger the dialog on screen? this should work just fine through the generic Action input operation.

have rebased (a refactoring pr from garbear landed and caused the conflict).

**Comment by da-anda** [comment]
ah, you mean via `Input.ExecuteAction`? Totally missed that. Great. Thanks.

**Comment by gade01** [comment]
Is it on purpose this function can't be called from VideoOSD.xml?

I can only get it working if mapped to a keymap and called in VideoFullScreen.xml

**Comment by notspiff** [comment]
yes.

**Comment by gade01** [comment]
Ok, thanks.

**Pull request merged**
