### PR TITLE
[win32] add screensaver add-ons to installer

### PR DESCRIPTION
**Pull request by MartijnKaijser**

### CODE REVIEW

**Comment by afedchin** [comment]
looks good

**Comment by afedchin** [comment]
thanks

**Comment by MartijnKaijser** [comment]
I'll merge this as it was forgotten/missed in the moving of the binary add-ons. Already made a testbuild which works

**Comment by Montellese** [comment]
It wasn't forgotten. There simply wasn't any binary addon screensavers for win32 at that time.

**Comment by MartijnKaijser** [comment]
original milkrdop was there?

**Comment by Montellese** [comment]
milkdrop etc are visualizations not screensavers.

**Comment by MartijnKaijser** [comment]
arghh... that's true :(

**Pull request merged**
