### PR TITLE
[resource.ui.sounds.confluence] Give it a destiguishing name

### PR DESCRIPTION
**Pull request by un1versal**
In addon manager listing, having both Skin and this addon showing up with same name, first reaction is, what?

This makes clear and unique.

### CODE REVIEW

**Comment by tamland** [comment]
I think it would be better to create an icon distinguish it, or a different name entirely. We don't call the other one "Confluence skin" for instance.

**Comment by uNiversaI** [comment]
Im only re-naming it according to the addon **id** you gave it, and changing the addon name to match.

The icon is neither here nor there because atm it has none, so the [DefaultAddon.png](https://github.com/xbmc/xbmc/blob/master/addons/skin.confluence/media/DefaultAddon.png) is different enough. 

The listing name is the issue, has having 2 instances of same name - Confluence doesnt feel right.

How about **Default ui sounds**? That way its unique enough and not tied to any particular skin name.

Ill see if I can make an icon anyway.

**Comment by MartijnKaijser** [comment]
Make it "Confluence UI Sounds". It's the same as some other sound packages that are now in Repo and just add the confluence icon.png to it
Thx

**Comment by uNiversaI** [comment]
@MartijnKaijser done, have a look, I thought a slightly different icon would be better than skin icon. After all not the same thing.

**Pull request merged**
