### PR TITLE
GUIMediaWindow: prevent from updates while updating

### PR DESCRIPTION
**Pull request by FernetMenta**
Updating listitems more than once at a given time is not allowed.

### CODE REVIEW

**Comment by DaveTBlake** [comment]
Thanks for this @FernetMenta. In my initial testing, having cherry-picked it into my current dev build (not working on any related area), party mode is working now.

However I have a had an odd experience with a break point taking me off to VS2017 (I set it to try and understand how the fix worked), and being unable to return to the Kodi GUI.  It was stuck in an infinite loop in CGUIWindowMusicBase, waiting for the music info loader to complete. Again, nothing I have been working on in the branch I was using. Anyway I need to do some more checking in case something else has gone astray.

**Comment by DaveTBlake** [comment]
There is definitely something amiss - having added library items to the playlist duirng playback, if you swop focus to another app then you can not get back to Kodi. All very odd, I will need to do more checking to see if it is somehow related to this PR or some other recent change. I rebased recently and it could be something else.

**Comment by FernetMenta** [comment]
Whatever strange behviour you may observe, it does not change the fact that this PR is correct. Updating the vecItems of GUIMediaWindow must only be done once at a given time. There may be more old crappy code that needs fixing.

**Comment by DaveTBlake** [comment]
>Whatever strange behviour you may observe, it does not change the fact that this PR is correct

If that is your view point then why ask for testing?   I really don't understand your attitude or approach to development

**Comment by FernetMenta** [comment]
> why ask for testing?

This change fixed the original issue, party mode, for me and I wanted to know if that is true for you as well. Obviously it is: "In my initial testing, having cherry-picked it into my current dev build (not working on any related area), party mode is working now."

This change does nothing but enforce design constraints. Hence it can't be wrong. If you observe issues that come to surface now, please open another ticket with detailed steps to reproduce.

**Comment by DaveTBlake** [comment]
On further testing (because I believe it is useful even if you don't)

- The change focus issue seems to be long standing. Kodi GUI only come to top window (gets painted?) when it gets mouse or keyboard input. Not related to busydialog.
- Kodi now crashes when it tries to play a library item which is for some reason inaccessible. This is busydialog related, but not specific to this PR
- **With this PR** playing in party  mode while switching to a node that is slow to load can cause Kodi to hang 

So this change has introduced new undesirable behaviour. It can be  difficult to reproduce as it happens when the player is moving to next song, at the same time as a large slow to load node (one with many items) is trying to load for the first time. Running in debug and breaking all Kodi gets stuck in a thread sleep. In preventing "update while updating" I suspect that the background loader is no longer able to communicate that it has completed.

My test to reproduce is to play a playlist of short songs (hence play next happens often) while browsing songs node on a large library for the first time since installing (hence slow to load and shows busydialog)

**Comment by FernetMenta** [comment]
@Memphiz as discussed on Slack: this fixes https://github.com/xbmc/xbmc/commit/7a0cd0b3e88c31726d3c96fed1c88724ff26d194#r29311923

**Comment by Memphiz** [comment]
Thx - sounds like there are some more  issues hidden somewhere as of daveblake. But one after the other ...

**Comment by DaveTBlake** [comment]
I fear there is a fundamental problem with adding the contraint "updating listitems more than once at a given time is not allowed" to a multi-threading system as Kodi is.

Unlike video, users can browse their music library while playback is happening. That can mean that they are changing from one node to another (which can be slow to load and so a busy dialog is needed) at the same moment as the player move to the next track (and also attempts to show a busy dialog too). 

Making those two events happen at the same time is a little fiddly, but it does occur, and this change seems to make it worse causing a hang.

**Comment by FernetMenta** [comment]
> I fear there is a fundamental problem with adding the contraint "updating listitems more than once at a given time is not allowed" to a multi-threading system as Kodi is.

you don't understand. I did not add the constraint, it has been there forever but was not enforced. you can't update the SAME listitems by mutliple thread at the same time. this is nonsense. one thread would overwrite the listitems of the other thread.

**Comment by DaveTBlake** [comment]
An unenforced constraint is not very constraining....
I do understand what you did and why, and I want to achieve the same as you - Kodi both run stability  and functionally rich - but I also see problems. 

Things like simultaneous browsing and playback are fundamental system requirements. Maintaining the current playing fileitem on play next, and updating the listitems when the user switches node (or changes sort order?) are both things that can show the busy dialog, and they are things that can happen at the same time or at least be initiated simultaneously.  Kodi needs to be abe to handle that. Have you allowed for it while enforcing the contraints on busydialog?

The current item, and the list of items that lies behind the media window are NOT the same item (although there is a relationship with the current item getting highlighted if it is in the list, it may not be), but the processes that update them do use the same one busy dialog.

Now maybe this is the wrong place to raise this, sorry if that is the case

**Comment by FernetMenta** [comment]
You are mixing up things. This PR is about preventing from multiple updates of the same items. This has nothing to do with busy dialog.

**Comment by DaveTBlake** [comment]
Then it is just an unfortunate coincidence that it is much easier to generate the busydialog related issue with my test build + this PR than it is without it?!

Since @da-anda and @karellen have reported this does fix party mode playback issue then,  despite whatever behaviour I am seeing, this should go into before alpha2

**Comment by DaveTBlake** [comment]
I really don't know either. I have rebased, and pulled in this and the advancing playlist fix, and now I am getting different behaviour again. I can only think there is some timing issue burried somewhere yet to be found. :(

With my current build I am seeing that very slow loading nodes will interrupt playback, to be precise delay track change. I don't think that happened before, and need to retest.  However it is behaviour that makes some sense.

I will keep chasing and see if I can pin it down more. But I accept it makes no sense for the variations I am seeing in behaviour to be related to this PR in particular.

**Pull request merged**
