### PR TITLE
GetOpticalMediaPath: move to video utils

### PR DESCRIPTION
**Pull request by notspiff**
## Description
Move GetOpticalMediaPath from CFileItem to VideoUtils

## Motivation and context:
This method has very little to do with the item apart from using its path. Let's trim some fat off CFileItem.

## How has this been tested?
It works.

## What is the effect on users?
None

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Review by enen92 — COMMENTED** [review]
I am not sure I like this. The videoutils was introduced by @ksooo and has a bunch of dependencies on GUI (it is in fact a gui class - should be moved to a guilib folder to make it more obvious). Doing this increases the coupling of fileitem to gui (I know it extends guifileitem but I plan to kill that).

**Comment by garbear** [comment]
> The videoutils was introduced by @ksooo and has a bunch of dependencies on GUI (it is in fact a gui class - should be moved to a guilib folder to make it more obvious)

Maybe a solution is to refactor into a new utils file without the dependency baggage of the existing VideoUtils?

**Comment by enen92** [comment]
> > The videoutils was introduced by @ksooo and has a bunch of dependencies on GUI (it is in fact a gui class - should be moved to a guilib folder to make it more obvious)
> 
> Maybe a solution is to refactor into a new utils file without the dependency baggage of the existing VideoUtils?

Yeah that would be the way forward imho. Not everything on that file depends on gui and we probably want to take advantage of the fact the file is still quite recent/small and is not already stuffed with all kinds of things.

**Comment by notspiff** [comment]
i tried and there is nothing in VideoUtils that does not depend on GUI as long as we keep the current structure of anonymous functions. I will  have to expose more of them to be able to break it up. I will put in the effort to split that file though but it's not a straight forward this-guy-goes-there-this-guy-goes-there kinda thing..

i would also like to point out that this is just the first step in a process where I remove a lot of dependencies in FileItem, including the dependency on VideoUtils, so your point would not really be valid in the end.

**Comment by notspiff** [comment]
updated.

**Review by fuzzard — APPROVED** [review]
Reorg + tests, win for me.

**Pull request merged**
