### PR TITLE
Invalidate repo data on version change

### PR DESCRIPTION
**Pull request by tamland**
This changes the addon DB to store the repo version the info was fetched from. This is to ensure that the repo we are comparing against is actually the same. For instance if the `dir` entires in the addon have changed, the checksum is invalid and the repo should be checked for updates immediately.

@MartijnKaijser Let me be very clear that this **incidentally** fixes your ABI problem. It only works because the current repo updater force re-check dependencies, even if nothing changed in the repo (which is a quite broken behavior).

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@mkortstiege for check.

@topfs2 i'd like this to be considered as backport as this fixed all those broken keyboard reports because skins don't update or are marked broken

**Comment by MartijnKaijser** [comment]
upgraded from 13.x to this build and it successfully fetches new skin on first run

**Comment by mkortstiege** [comment]
Looks good.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by opdenkamp** [comment]
this breaks because of `DELETE FROM repo` and adds each add-on another time in the db. running helix and then upgrading to this will leads to a dupe of each add-on

**Comment by opdenkamp** [comment]
so this line is bad https://github.com/xbmc/xbmc/pull/6568/files#diff-130a411077441f19c8eb4b80f5b382d7R102

**Comment by opdenkamp** [comment]
specifically add-ons -> get add-ons -> kodi add-on repos -> pick something like video

**Comment by tamland** [comment]
Hm, I guess mine happed to recreate the repos in the same order as I never saw that issue. I'm not even sure why I added that line. 'Alter table' should be enough right?

**Comment by opdenkamp** [comment]
Created a pr that fixes it for me

**Pull request merged**
