### PR TITLE
[lib][taglib] Updated taglib that fixes a crash when playing flac files

### PR DESCRIPTION
**Pull request by Paxxi**

### CODE REVIEW

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by fritsch** [comment]
If jenkins is fine, please add to 15.1

@wsnipex do you need to copy the updated libtag packages to the team ppa or are they already there?

**Comment by wsnipex** [comment]
already there

**Comment by Paxxi** [comment]
ahh, didn't see 15.1 as it was closed.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
