### PR TITLE
[Depends] libass get rid of rpl

### PR DESCRIPTION
**Pull request by mrdominuzq**
no problem on android x86

### CODE REVIEW

**Comment by koying** [comment]
On what was this tested, exactly?
Was it on Android 4.4 with a NDK 17 toolchain?

**Comment by koying** [comment]
BTW, does it fix something? Why libass specifically?

**Comment by mrdominuzq** [comment]
Tested with 17 toolchain and Android 5.1. It doesnt fix anything but it removes The Need to use rpl :)

**Comment by MrMC** [comment]
removal of autoreconf is wrong, you need that to pick up the correct libtool which would contain the correct xxx.so naming in the 1st place.

https://github.com/xbmc/xbmc/pull/9308 causes libtool to generate correct xxx.so naming

rpl is rather handy, personally I'd keep it around just in case it's needed in the future.

**Comment by mrdominuzq** [comment]
well i did add the autoreconf, so i'm not sure what you mean :)

**Comment by MrMC** [comment]
opps, my bad, read it too fast. @MartijnKaijser , it good as it.

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
