### PR TITLE
[WIndows][addons][backport] Improve patch finding

### PR DESCRIPTION
**Pull request by Paxxi**
On Windows we only want to find patch.exe included with git.
All other patch.exe is broken in some way and will cause build
failures

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by DaveTBlake** [comment]
Many thanks for this @Paxxi I'm sure many Xbox users will be glad to get `inputstream.adaptive` addon back again in v18.6

**Comment by Rechi** [comment]
Was the case where no "valid" patch executable is installed on the build machine actually tested?

**Comment by Paxxi** [comment]
No, it's not really a scenario that should ever happen as users should have git installed

**Comment by Rechi** [comment]
In that case why wasn't the fallback remove if it will never happen?
Then there is something else wrong with this, see https://ci.appveyor.com/project/xbmc/inputstream-rtmp/builds/30321302.

**Comment by Paxxi** [comment]
I kept it as small as possibe to unblock the Leia release as I didn't have any time to test things.

Since we don't use appveyor it's not really a critical issue, should be fixed but I won't have any time to look at it for the foreseeable future

**Comment by AlwinEsch** [comment]
With this request seems the AppVeyor build support broken, see https://ci.appveyor.com/project/xbmc/vfs-sacd-tj1lq

**Pull request merged**
