### PR TITLE
[depends] patch taglib: Efficient lookup for an ID3v2 tag in MPEG fil…

### PR DESCRIPTION
**Pull request by Rechi**
…es with garbage.

## Description
add https://github.com/taglib/taglib/commit/d2e0e5522308ce4c905c205c7bf5972ea71cd6e5 as a patch

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by DaveTBlake** [comment]
Many thanks for this.
Does something else need to be done for win32? And either way is it not best to apply #11522 the update v.1.11 on win32 first?

**Comment by popcornmix** [comment]
> I still think it crazy to even try scanning ID3 tags from a Shoutcast, but always good to have a TagLib that can cope.

But is there evidence this only affects Shoutcast?
It sounds like any mp3 file without ID3 tags would provoke the bug.
It seems likely that any live streaming site that uses mp3 format wouldn't have ID3 tags, so a generic fix seems much better than a Shoutcast specific hack.

**Comment by Rechi** [comment]
@DaveTBlake this doesn't affect windows, it's for all platforms expect Windows.
I think @Paxxi will do something similar for Windows.

**Comment by DaveTBlake** [comment]
Good point @popcornmix. The absense of tags from an mp3 file is fine (as best I can test). The issue here is giving a continuous stream of untagged data to something that is looking for ID3 tags anywhere in a file - it takes a long time to  stop looking! Shoutcasts are the only example of this I have found, but I guess there could be other continuous streams that end ".mp3".

Yes there has been a regerssion in TagLib, they are fixing it, and good for us to use that fix. But this bug  has revealed that we are treating their utility in an incorrect way. I think we should take more care over what we throw at a tag scanner. Calling a routine designed to scan ID3 tags from a finite file with a stream of untagged data is wrong, it is beyond its scope.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by DaveTBlake** [comment]
Same patch implemented for win32 by  #11547.  Thanks all.

**Pull request merged**
