### PR TITLE
[depends] filter out unwanted optimization flags

### PR DESCRIPTION
**Pull request by wsnipex**
## Description
We currently build depends (and kodi in some cases) with - in some cases - aggressive compiler optimization flags, even for debug builds.
This change will remove -O[2,3] flags when --enable-debug (the default) is given and use -Og  instead

>-Og
    Optimize debugging experience. -Og enables optimizations that do not interfere with debugging. It should be the optimization level of choice for the standard edit-compile-debug cycle, offering a reasonable level of optimization while maintaining fast compilation and a good debugging experience. 

## Motivation and Context
Increase debugging experience for devs

## How Has This Been Tested?
It has not. Please test on your platform of choice and give feedback

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by koenkooi** [comment]
This PR reminded me of something, have you considered using -Os instead of -O2? That made a noticable impact a few years ago on embedded, but mostly because storage was slow and caches were tiny. See slide 55 of http://free-electrons.com/doc/embedded_linux_optimizations.pdf .

If you feel that is worth exploring I can cook up a PR and do some tests on armv7/aarch64/x86 next week.

**Comment by wsnipex** [comment]
Most embedded platforms already use -Os, specially on android.
If RPI should use that as well, would be up to @popcornmix

**Comment by popcornmix** [comment]
@MilhouseVH didn't you do some tests of ``-Os`` vs ``-O2``?

**Comment by MilhouseVH** [comment]
> @MilhouseVH didn't you do some tests of -Os vs -O2?
I may have done, a while back, but can't recall the conclusion now. :(

However LibreELEC recently dropped `-O2` as it caused some issues (see https://github.com/LibreELEC/LibreELEC.tv/pull/644, implemented in https://github.com/LibreELEC/LibreELEC.tv/pull/696), and @stefansaraev expressed a preference for `-Os`.

**Comment by popcornmix** [comment]
Yes, I think OE switched a couple of times between size/speed as default optimisation but I think there wasn't a clear winner.
I think without strong evidence to the contrary I'm happy with ``-Os`` rather than ``-O2``.
At least the code is smaller and fits instruction caches better.

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
meh, slaves are acting up again :(
jenkins build this please

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
jenkins build this with addons please

**Comment by wsnipex** [comment]
rebased. jenkins build this with addons please

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
anyone cares to test/review?

**Comment by hudokkow** [comment]
Can probably test tonight.

I say pull the trigger. We have plenty of time to test and find problems.

**Comment by hudokkow** [comment]
Tested with android and rpi builds. Working as intended.

**Comment by FernetMenta** [comment]
Is it supported to have depende built as release and kodi as debug?

**Comment by wsnipex** [comment]
yes, should work by setting the CMAKE_BUILD_TYPE

**Comment by FernetMenta** [comment]
btw: this does not work for ffmpeg. ffmpeg needs to be configured with --disable-optimizations if you want to debug it

**Pull request merged**
