### PR TITLE
[VideoPlayer] fixup! stalls after seek.

### PR DESCRIPTION
**Pull request by afedchin**
see title

@FernetMenta ping

### CODE REVIEW

**Comment by FernetMenta** [comment]
+1
thanks!

**Comment by popcornmix** [comment]
I'm not sure this is a complete fix. For many files a couple of seconds after seeking I now get a ~500ms stall then video continues as normal.
That is obviously better than without this PR where stalls could last for several seconds, but it's not as good as it used to be with no stalls (I believe the stalls appeared with inputstream PR).
Ping @FernetMenta

**Comment by FernetMenta** [comment]
how far is pts off after seek?

**Comment by afedchin** [comment]
pst off equals to amount of seek. as an example: before seek pts was 4206756746.333336 after seek forward for 30 sec the pts became 4236536500.000000

**Comment by FernetMenta** [comment]
I meant offset related to clock
timeToDisplay = DVD_TIME_TO_MSEC(pts - iPlayingClock);

**Comment by afedchin** [comment]
timeToDisplay: 29476 just after seeking forward 30 sec.
timeToDisplay: 184887 just after randon seeking forward about 3 min.

**Comment by afedchin** [comment]
timeToDisplay: -176686 just after random seeking backward.

**Comment by FernetMenta** [comment]
I can't reproduce here. Does it happen with only some material? With SW decodeing?

**Comment by afedchin** [comment]
try with bluray.

**Comment by FernetMenta** [comment]
I don't see how this matters. After seek the renderbuffers get flushed. There should be a buffer available and maxWaitTime is meaningless. 
What do I miss?

**Comment by afedchin** [comment]
If I understand correctly CRenderManager::DiscardBuffer() doesn't make all buffers as free and only marks them to discard. The actual freeing of frames occurs on FrameMove. So CRenderManager::WaitForBuffer will wait till timeout or till FrameMove

**Comment by FernetMenta** [comment]
correct but this happens all within one render cycle that is max 41ms.
looks like that the event is not set when buffer are pushed to queue of free buffers.

**Comment by popcornmix** [comment]
Actually my stall seems to follow a "timeout waiting for buffer" message:
http://paste.ubuntu.com/16363857/

I get one of these a couple of seconds after most seeks (but not during normal playback).
Can't see an obvious reason for this. The last couple of calls to Decode returned pictures.
The same picture was passed to RenderUpdate many (17) times before the timeout.

**Comment by FernetMenta** [comment]
> Actually my stall seems to follow a "timeout waiting for buffer" message:

That's 7 seconds after the seek. During this timeframe many pictures have passed. What relationship do you see to this PR?

**Comment by popcornmix** [comment]
Yes, I think I'm wrong with relating it to this PR.

I attempted to bisect to find the start of this stall.
The bisect found "Merge pull request #9592 from FernetMenta/inputstream" which actually caused very long stalls (of many seconds). I believe this PR fixed the long stalls, but there was still a shorter stall remaining.
So there are possibly two unrelated stall bugs that overlapped in time.

**Comment by FernetMenta** [comment]
bisect is of no interest. things that never worked properly or only by chance can't get broken. better investigate why pts jumps forward.

**Pull request merged**
