### PR TITLE
Fix JSON output of album and artist mood to be array as in spec

### PR DESCRIPTION
**Pull request by DaveTBlake**
Since #8012 ensured that all available info was copied in CMusicTagInfo.SetArtist, SetAlbum and SetSong, it inadvertently impacted the interface format of the way artist and album mood was output to JSON. The spec says it will be an array of values  [mood1, mood2, mood3], this became a single value 'mood1 / mood2 / mood3'.

This was spotted and discussed in #8306. This simple fix restores prevous output format, and it was hoped a fix would be part of Jarvis beta. But I am not completely happy with this solution so I have raised this PR to encourage others to look at it with me.

We now end up  mood in two places in FileItem - `CMusicDatabase::SetPropertiesFromAlbum` stores it in "album_mood" and "album_mood_array" properties (outside the item.MusicInfoTag structure). But `CFileItem::SetFromAlbum` calls both `SetPropertiesFromAlbum` and `GetMusicInfoTag()->SetAlbum(album)`. The latter is changed by #8012 to set the mood string `CMusicInfoTag.m_strMood`. Subsequently `CFileItemHandler::HandleFileItem` calls `FillDetails` calls `GetField` that first tries to get mood from serialised value of CMusicInfoTag first so the properties "album_mood_array" "album_mood" aren't used here. 

Are they used anywhere? Or can (and should) we remove "album_mood" and "album_mood_array" from `CMusicDatabase::SetPropertiesFromAlbum` ?

Also mood in the database is just a string, does splitting it into an array make any sense? So should the API change instead?

@Tolriq, @ronie, @jjd-uk from previous discussion. @Razzeee like to have a look. Maybe the bigger quession has to wait until @Montellese gets back?

### CODE REVIEW

**Comment by Tolriq** [comment]
To add some history, this field and many other was string before.

They all were changed in Frodo or Gotham (can't remember) to arrays as well they are arrays of data, and it was more logical to serve data as arrays, since it's not consumer job to check for a potential separator (that can be different in some cases) and guess if string or array.

So reverting to String does not seems right.

Even if I doubt many use this field, keeping the API compatible for Jarvis at this stage seems the most important.

Migrating to String would be a incompatible change and require a bump of API from 6.X to 7.X seems overkill for a simple unused field.

So in the end, even if the fix is not perfect for Jarvis at least it does not kill all API consumers, and maybe a better fix can be found for K.. (But IMO this is not an API change, just a fix)

**Comment by DaveTBlake** [comment]
Got that JSON output wants an array for separate mood values where multiple mood values have been scraped for album and artists. It is efficient to store this little used (?)  data in the database as a single string,  but that does not mean we change API. This PR restores the array output.

@Tolriq you are right this is a fix not an API change, and wants to be in Jarvis. I realise from what you and @Montellese said before that I should probably increment subversion though.

My outstanding question is whether we should now be storing  mood in two places in CFileItem. It isn't going to break anything, but it does make me feel that this is a fix rather than good design.

**Comment by Tolriq** [comment]
@DaveTBlake for the API bump this is more complicated than your previous PR.

Previous case was : 
API version A says X, then it was broken, then you provided a fix that changed the API to Y so bump, then you fixed the API to get back to X so another bump.

In this case the api says X it was broken now you fix it, so only minor version should be bumped as X is still X.

**Comment by ronie** [comment]
thanx, tested and the mood issue is fixed in json.

**Comment by Tolriq** [comment]
@DaveTBlake I made a mistake in terms in my explanation :(
Since api is not changed it's the revision that needs update sorry :(

6.32.1 should be following @Montellese convention.

**Comment by DaveTBlake** [comment]
I have convinced myself that having mood in two places in CFileItem is not an issue, or at least it is not the only time such a thing happens. There is also reason to keep  "album_mood" and "album_mood_array" in CMusicDatabase::SetPropertiesFromAlbum. This aspect of music section is a little convoluted, better left as it is until I understand it all better (or someone else does!) - if it ain't broke don't fix it!!

I have added a bump to JSON minor version to indicate that mood is returned correctly unlike previous minor versions.

This has been tested by @ronie and @Tolriq - thanks - but would be nice to have a +1 from another dev even though it is a one line change. @Razzeee or @mkortstiege ?

**Comment by DaveTBlake** [comment]
@Tolrig I cross posted, but have fixed version change to meet @Montellese convention. Thanks

**Pull request merged**
