### PR TITLE
SPDX license identifier

### PR DESCRIPTION
**Pull request by hudokkow**
## Description
Clean up the mess with copyright notices and replace with an SPDX license identifier. It allows better overview of licenses, for both humans and compliance software. Done following the example of the Linux Kernel folks.

## Motivation and Context
Modernization. Replaces https://github.com/xbmc/xbmc/pull/13927

## How Has This Been Done/Tested?
1. Run [scancode](https://github.com/nexB/scancode-toolkit) on master branch `./scancode -l -n 16 ../kodi --html ../kodi_licenses.html`.
2. Identify all licenses spewed by it.
3. Group files with same license.
4. Confirm group by group, file by file if detected license is correct. Many are false positives because an expression or phrase triggers them. That's the case for **all detected *gpl-1.0-plus***, triggered by `http://www.gnu.org/copyleft/gpl.html`.
5. If license is not clear (missing text, ambiguous interpretation, etc.) try to confirm with original author/sources. That was the case with `xbmc/platform/win32/dxerr.h` and `xbmc/platform/win32/dxerr.cpp` that looked like **MS-PL** licensed files but were indeed **MIT** licensed.
6. After initial assessment, pick a license group and change notice.
7. Loop.
8. Finally, take care of the biggest group, in our case **GPL-2.0-or-later**. Patterns are easy to find and `sed` is a very good friend.
9. Select a random sample of files and have a look to see if everything is OK.

## Current licenses under `xbmc/` (as seen on [SPDX licenses list](https://spdx.org/licenses/)):

| License                                                                   | **[FSF Free/Libre](https://www.fsf.org/licensing)**     | **[OSI Approved](https://opensource.org/licenses/alphabetical)**       | **[GPLv2 Compat](https://www.gnu.org/licenses/license-list.html)**                                                                         |
| ------------------------------------------------------------------------- | :----------------: | :----------------: | :----------------------------------------------------------------------------------: |
| **[BSD-3-Clause](https://spdx.org/licenses/BSD-3-Clause.html)**           | :heavy_check_mark: | :heavy_check_mark: | **[:heavy_check_mark:](https://www.gnu.org/licenses/license-list.html#ModifiedBSD)** |
| **[BSD-4-Clause](https://spdx.org/licenses/BSD-4-Clause.html)**           | :heavy_check_mark: | :x:                | **[:x:](https://www.gnu.org/licenses/license-list.html#OriginalBSD)**      |
| **[GPL-2.0-only](https://spdx.org/licenses/GPL-2.0-only.html)**           | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:                                                                   |
| **[GPL-2.0-or-later](https://spdx.org/licenses/GPL-2.0-or-later.html)**   | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:                                                                   |
| **[LGPL-2.1-or-later](https://spdx.org/licenses/LGPL-2.1-or-later.html)** | :heavy_check_mark: | :heavy_check_mark: | **[:heavy_check_mark:](https://www.gnu.org/licenses/license-list.html#LGPLv2.1)**    |
| **[MIT](https://spdx.org/licenses/MIT.html)**                             | :heavy_check_mark: | :heavy_check_mark: | **[:heavy_check_mark:](https://www.gnu.org/licenses/license-list.html#Expat)**       |
| **[Unlicense (Public Domain)](https://spdx.org/licenses/Unlicense.html)** | :heavy_check_mark: | :question:         | **[:heavy_check_mark:](https://www.gnu.org/licenses/license-list.html#PublicDomain)**        |

Last two commits uniformize our copyright line. Instead of a gazillion variations, we now have:
```
 *  Copyright (C) 2002-2018 Team Kodi
 *  Copyright (C) 2003-2018 Team Kodi
 *  Copyright (C) 2005-2018 Team Kodi
 *  Copyright (C) 2006-2018 Team Kodi
 *  Copyright (C) 2007-2018 Team Kodi
 *  Copyright (C) 2008-2018 Team Kodi
 *  Copyright (C) 2009-2018 Team Kodi
 *  Copyright (C) 2010-2018 Team Kodi
 *  Copyright (C) 2011-2018 Team Kodi
 *  Copyright (C) 2012-2018 Team Kodi
 *  Copyright (C) 2013-2018 Team Kodi
 *  Copyright (C) 2014-2018 Team Kodi
 *  Copyright (C) 2015-2018 Team Kodi
 *  Copyright (C) 2016-2018 Team Kodi
 *  Copyright (C) 2017-2018 Team Kodi
 *  Copyright (C) 2018 Team Kodi
```

Third-party copyright lines were not touched.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Improvement (non-breaking change which improves existing functionality)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Cosmetic change (non-breaking change that doesn't touch code)
- [ ] None of the above (please explain below)

### CODE REVIEW

**Comment by natethomas** [comment]
Nice work. I can't imagine how long this took to do.

**Comment by CvH** [comment]
@hudokkow how do you "label" your *.jpg, *.png ... (media) files ? Currently (If I got this right) they are not covered by any licence at all. Shouldn't they have some Media Licence (like CC ...) and should be declared ?

**Comment by hudokkow** [comment]
@CvH, I haven't gotten around to those yet. This PR only deals with `xbmc/` dir (roughly 43% of the almost 8500 files we're tracking).

As for your question, **[REUSE Initiative](https://reuse.software/practices/2.0/)** states:

> All source files which are included in the final build of your project (verbatim, modified, partially, or in compiled form) must have copyright and license information contained within them. If it is not possible to add a header to the file, either because the file is a binary or because the format does not support comments, you must provide the information separately in one of three ways:

> You may include a textfile called FILENAME.license in which you store your regular comment header with all the necessary information to convey the license information about the file called FILENAME.


> If you have many such files, but each have the same copyright notice and license, you may instead use the DEP-5/copyright file format, and place a single copyright notice documenting those files.


> If you have a way of automatically generating an inventory of included files in SPDX format (see practice 3), you may use this and do not need to separately include a .license file or DEP-5/copyright file.


**[reuse tool](https://git.fsfe.org/reuse/reuse)** was a lint mode that does wonders to tell you what files are missing a copyright/license notice. Unfortunately I only found it **after** manually digging for all the files missing license and/or copyright notice. 😞

**Comment by garbear** [comment]
This PR is awesome. The commits are a good breakdown of our code's licenses. Thanks!

**Pull request merged**
