### PR TITLE
changed: By default enable filecache for all remote filesystems (CACH…

### PR DESCRIPTION
**Pull request by arnova**
Backport of #17043

### CODE REVIEW

**Review by DaveTBlake — APPROVED** [review]
Seeing this as a fix really, fixing defaut setting to repeated user confusion and complaint

**Comment by FernetMenta** [comment]
This kills the spotify addon: https://forum.kodi.tv/showthread.php?tid=265356&pid=3036652#pid3036652
Reverting this change makes the addon work again.

**Comment by arnova** [comment]
> This kills the spotify addon: https://forum.kodi.tv/showthread.php?tid=265356&pid=3036652#pid3036652
> Reverting this change makes the addon work again.

Seems unlikely. Do you have a debug log?

**Comment by FernetMenta** [comment]
What you consider unlikely is verified by another user: https://forum.kodi.tv/showthread.php?tid=265356&pid=3037163#pid3037163

**Comment by arnova** [comment]
> What you consider unlikely is verified by another user: https://forum.kodi.tv/showthread.php?tid=265356&pid=3037163#pid3037163

No debug log is no bug.....

**Comment by FernetMenta** [comment]
That statement is nonsense and embarrassing for this project. You can easily reproduce the issue by installing the addon and try yourself.

**Comment by arnova** [comment]
> That statement is nonsense and embarrassing for this project. You can easily reproduce the issue by installing the addon and try yourself.

Bullshit: We always ask for debug logs. I'm not going to spend my time on reproducing every single issue myself if already done by others. So please refrain from making useless statements like this.

Furthermore I'm not interested in Spotify so if you want it fixed, you know what to do.

**Comment by FernetMenta** [comment]
Fact is that you ruined working functionality in a dot release. This change is not a fix. You changed behaviour. Now you are reluctant to investigate an issue that has been confirmed by multiple users. If you were interested in correcting your mistake, you would have to replicated the behaviour in your environment anyway.

> Furthermore I'm not interested in Spotify so if you want it fixed, you know what to do.

I am sure this change has more impact than only this addon.

**Comment by arnova** [comment]
> Fact is that you ruined working functionality in a dot release. This change is not a fix. You changed behaviour. Now you are reluctant to investigate an issue that has been confirmed by multiple users. If you were interested in correcting your mistake, you would have to replicated the behaviour in your environment anyway.
> 
> > Furthermore I'm not interested in Spotify so if you want it fixed, you know what to do.
> 
> I am sure this change has more impact than only this addon.

The change IS a fix: for issues with NFS & SMB. FYI: This was discussed internally and not a solo decision. So please stop spreading nonsense if you don't know what you're talking about. Instead of directing your efforts in "trying to make your point" you could simply have provided a debug log and I'd happily would have had a look at it. Right now you're just aggravating me...

**Comment by chrisgo67** [comment]
@arnova: The fool thinks council is enmity.

**Pull request merged**
