### PR TITLE
Minor keyboard.xml improvements

### PR DESCRIPTION
**Pull request by NedScott**
Some minor adjustments to keyboard.xml

longpress on the virtual keyboard had some issues: https://github.com/xbmc/xbmc/pull/7346#discussion_r43611751

"back" behavior on some PVR keys: http://forum.kodi.tv/showthread.php?tid=242476

and some other minor improvements.

### CODE REVIEW

**Comment by hudokkow** [comment]
Thanks Ned.
@koying, @ace20022, b1 material?

**Comment by ace20022** [comment]
@NedScott thanks. I can't comment on the changes. Who should we ping?

**Comment by NedScott** [comment]
As far as who to ping, I guess anyone who can push the button :)

I've tested the map on my devices and haven't ran into any issues. This is mainly to just remove the long-press on the virtual keyboard, plus some minor additions that I didn't think were big enough to PR on their own, but the virtual keyboard changes should be seen as a fix, IMO. A "bug" in usage/behavior, rather than code, if that makes sense. 

The other ones could be argued as logical improvements/fixes, such as the PVR keys having "back" behavior, C being in-line with other context menu buttons, etc. I held back anything that seemed debatable or controversial.

**Comment by NedScott** [comment]
Thank you kindly

**Comment by ace20022** [comment]
It seems that long pressing now does only perform one "click". For example deleting multiple chars by holding backspace doesn't work anymore

**Comment by NedScott** [comment]
After some testing tt seems that if we define any key as longpress in < global > then it will disable key repeat for all other windows. I'm not sure if this is a bug of the longpress feature or something expected? It's possible to modify the keymap to overcome this limitation so that we still have the context menu on select-longpress, as well as keyrepeat on virtual keyboard, but it will be slightly "messy".

This can be tested by removing enter/return's longpress mod in < global > for keymap.xml.

**Comment by koying** [comment]
It's a choice. If you have a global long action, I had to choose whether ignoring it if there was no window-specific long action, or ignore repeats.

By instance, if you globally map "long back" to "Go to home", you naturally loose "back repeat"...

If someone can think of a smarter logic, I'm all ears

**Comment by NedScott** [comment]
Can we repeat on the long-press? That way we can just define < enter mod="longpres" >select< /enter > as well as normal < enter > for virtual keyboard. I'm not sure if I am describing it well.

**Comment by guidosarducci** [comment]
@NedScott, I've been testing the latest beta alongside Isengard and wanted to chime in regarding your improvements. I would also urge to remove longpress with the navigation keys (up/down/left/right). Text entry in the absence of a keyboard is made tolerable though tedious by having navigation keys that repeat, making all keys accessible with similar (poor) latency. However, the current "no nav repeat" behaviour optimizes a few keys but penalizes access to the remaining majority, and will make Virtual Keyboard usage very frustrating for most users. I believe this is not a good tradeoff to impose on users by default.

**Comment by NedScott** [comment]
@guidosarducci I considered that, but repeating the directional keys in the virtual keyboard really isn't practical. Pressing and holding, especially for up/down, wraps really fast on most systems and you end up on a semi-random letter.

I've used every major platform/OS that Kodi is available for, with dozens of remotes, and have always found it easier to press the directional keys a specific number of times. Key repeat has never been accurate enough to land on the letter I want, nor is it significantly faster to get from a general area to another on the virtual keyboard. When I asked others about this they felt the same. I can only conclude that most users are pressing the button a specific number of times to reach a specific letter.

It made sense to get rid of it for select and delete because those can both be used to clear the text, which does not need to be precise.

**Pull request merged**
