### PR TITLE
EGLUtils: breakup EGL init process

### PR DESCRIPTION
**Pull request by lrusak**
This will give us more flexibility in the future to allow falling back if something in the initialization fails.

needed for #14515

### CODE REVIEW

**Comment by lrusak** [comment]
@pkerling please have a look over if you get a second ⌛️

**Review by yol — APPROVED** [review]
lgtm

It would make sense logically to add the precondition check in `ChooseConfig` as part of this commit.

**Comment by pkerling** [comment]
Thanks for the ping and sorry for forgetting about this :see_no_evil:

**Comment by lrusak** [comment]
@pkerling thanks! I added the check in now

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Pull request merged**
