### PR TITLE
[depends] remove rtmp as it's included through ffmpeg or as binary addon

### PR DESCRIPTION
**Pull request by MartijnKaijser**
Just throwing it out here. Up to others to say merge or not.

the inputstream.rtmp addon builds on all platforms so we don't need this anymore

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build this please
@wsnipex ping

**Review by wsnipex — APPROVED** [review]

**Comment by mazeyx** [comment]
@MartijnKaijser we tried this about 6 months back and system info on android tv was still using it so system information page was freezing, do you remember. will give it a shot again though.

**Comment by MartijnKaijser** [comment]
Not sure what you mean cause it runs just fine

**Comment by mazeyx** [comment]
@MartijnKaijser ok ill post a debug log if it freezes again, it was on android tv as soon as you go system information page in settings it would freeze, it was related to librtmp.so being removed. can i get a krypton test build plz.

**Comment by wsnipex** [comment]
use the nightly

**Comment by MartijnKaijser** [comment]
Here's a test build
http://mirrors.kodi.tv/test-builds/android/arm/kodi-20161212-3373a35-rtmp_cleanup_krypton-armeabi-v7a.apk

**Comment by mazeyx** [comment]
@MartijnKaijser OK just ran it and tested it appears fine now. it caused problems months ago though when they tried a cleanup. i cant find the PR for reference.

**Pull request merged**
