### PR TITLE
[cmake] use normalized to lower case CORE_PLATFORM_NAME in conditionals

### PR DESCRIPTION
**Pull request by wsnipex**
replaces https://github.com/xbmc/xbmc/pull/12462

@hudokkow @lrusak @pkerling

### CODE REVIEW

**Comment by pkerling** [comment]
Is there a particular reason not to modify CORE_PLATFORM_NAME directly? Would be less confusing.

**Comment by wsnipex** [comment]
the idea is not to modify user supplied configs/values.

**Comment by pkerling** [comment]
Mh I see. Is there something we can do to "prevent" use of `CORE_PLATFORM_NAME`? It's just very tempting to accidentally use it and then get into trouble. At the very least, I think there should be a comment somewhere that says not to use it :)

**Comment by wsnipex** [comment]
valid point, added a comment

**Comment by hudokkow** [comment]
I came up with https://github.com/hudokkow/xbmc/commit/3f4e00226d79f2e4bad638f43c75c80493789869 but violates the "... not to modify user supplied configs/value" part...

I'm fine with whatever solution is agreed upon.

**Comment by lrusak** [comment]
I'm fine with this

**Review by lrusak — APPROVED** [review]

**Pull request merged**
