### PR TITLE
[Windows][Rendering] Fix HDR toggle off on file close

### PR DESCRIPTION
**Pull request by stumpalump**
## Description
This small fix will leave HDR enabled on CloseFile() unless SDR content is playing. If SDR content is playing and Autoswitch HDR is enabled in settings, then we will toggle HDR back on after CloseFile(). Kodi GUI looks great on HDR displays and we only want to toggle Windows HDR switch off when necessary (during SDR content playback).

## Motivation and context
I got tired of having to toggle HDR back on manually through Windows every time I exit Kodi.

## How has this been tested?
I played an HDR file and checked toggle afterward. I played an SDR file and checked toggle afterward.

## What is the effect on users?
Users with HDR displays will notice that they do not have to manually toggle HDR back on in Windows after exiting Kodi

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by thexai** [comment]
This is not a bugfix but a behavior change...

For many people the bug would start now because Kodi GUI is SDR and must be seen with Windows HDR off

> I got tired of having to toggle HDR back on manually through Windows every time I exit Kodi.

You can use F11 key for that (switch Windows HDR before exit Kodi). 
You can also map F11 to any remote button, etc.

> Users with HDR displays will notice that they do not have to manually toggle HDR back on in Windows after exiting Kodi

You're assuming that all the people who use HDR displays have HDR enabled on their Windows desktop all the time...

**Comment by stumpalump** [comment]
> This is not a bugfix but a behavior change...
> 
> For many people the bug would start now because Kodi GUI is SDR and must be seen with Windows HDR off
> 
> > I got tired of having to toggle HDR back on manually through Windows every time I exit Kodi.
> 
> You can use F11 key for that (switch Windows HDR before exit Kodi). You can also map F11 to any remote button, etc.
> 
> > Users with HDR displays will notice that they do not have to manually toggle HDR back on in Windows after exiting Kodi
> 
> You're assuming that all the people who use HDR displays have HDR enabled on their Windows desktop all the time...

This change checks for m_AutoSwitchHDR first and should only toggle if the user has auto switch hdr enabled. I'm not sure why you say gui must be seen with HDR off when GUI renders just fine with HDR switch on and also looks better. Do you have an HDR display to test with?

**Comment by thexai** [comment]
For same reason you can disable HDR auto-switch setting and leave HDR enabled all the time in Windows. 
If Kodi GUI looks fine for you in HDR also SDR media files should look same fine.

**Comment by stumpalump** [comment]
> For same reason you can disable HDR auto-switch setting and leave HDR enabled all the time in Windows. If Kodi GUI looks fine for you in HDR also SDR media files should look same fine.

If Windows HDR switch is enabled when Kodi starts, then why doesn't the GUI switch to SDR on start? Kodi GUI starts with HDR enabled. Why toggle to SDR only after close file? This does seem like a bug if HDR is enabled on Kodi start and does not return to HDR after file close. Kodi should leave things how it found them. If user wants to render Kodi GUI in SDR it seems F11 would work great for this.

**Comment by stumpalump** [comment]
> For same reason you can disable HDR auto-switch setting and leave HDR enabled all the time in Windows. If Kodi GUI looks fine for you in HDR also SDR media files should look same fine.
> 
> That is, users who use Windows desktop in HDR all the time are covered and just need to disable HDR switch on Kodi. Windows tone maps all SDR content to HDR (Kodi GUI and SDR videos).



> For same reason you can disable HDR auto-switch setting and leave HDR enabled all the time in Windows. If Kodi GUI looks fine for you in HDR also SDR media files should look same fine.
> 
> That is, users who use Windows desktop in HDR all the time are covered and just need to disable HDR switch on Kodi. Windows tone maps all SDR content to HDR (Kodi GUI and SDR videos).

But what if I still want Kodi to toggle HDR off for SDR content? This produces better colors for SDR content. Maybe a better change is to add a new setting for user to choose whether to render Kodi GUI in SDR or HDR (for HDR enabled displays only). Then Kodi would check setting and decide on start and closefile, but Autoswitch HDR can still be enabled

**Comment by stumpalump** [comment]
An alternative to this could be to have Kodi cache the Windows HDR switch status on start and then return to that setting on CloseFile(). I can work on that also if needed, but I have ZERO code experience and am only doing this because I have loved Kodi for over 10 years now and want to help!

**Comment by CrystalP** [comment]
Can you provide a step by step where Kodi doesn't restore the screen to the status it had when it started, or when the playback goes wrong and the corresponding debug log.

That doesn't happen to me, unless I mess with the HDR status through F11 or control panel while Kodi is running, so maybe there is something else happening with your computer.

Reacting to external HDR status change while running could be improved though, no question.

**Comment by stumpalump** [comment]
> I'm not sure I get the problem. Can you provide a step by step where Kodi doesn't restore the screen to the status it had when it started, or when the playback goes wrong and the corresponding debug log.
> 
> That doesn't happen to me, unless I mess with the HDR status through F11 or control panel while Kodi is running, so maybe there is something else happening with your computer.
> 
> Reacting to external HDR status change while running could be improved though, no question.

The code I removed is what gets called on CloseFile() and switches the screen to SDR without any regard to the HDR toggle beforehand.

So what happens is this:
1. Windows HDR is on when open Kodi. Kodi GUI gets rendered HDR and looks fine
2. Autoswitch HDR is enabled in settings.
3. HDR or SDR content is played (doesn't matter) and proper switching happens.
4. On file closed GUI switches to SDR without any regard to previous setting. Kodi GUI is now rendered SDR (why when not needed?)
5. Exit Kodi and Windows HDR switch is now OFF

**Comment by CrystalP** [comment]
> For same reason you can disable HDR auto-switch setting and leave HDR enabled all the time in Windows.
> If Kodi GUI looks fine for you in HDR also SDR media files should look same fine.
> 
> That is, users who use Windows desktop in HDR all the time are covered and just need to disable HDR switch on Kodi. Windows tone maps all SDR content to HDR (Kodi GUI and SDR videos).

You would think so :-) but actually no. While SDR media is fine, the playback of HDR is broken and the picture is completely blown out.

Now that I tested more rigorously (multiple screens have an effect) I see the switch to SDR happen when starting playback with the setting on. I wasn't expecting it but if it's meant to do that, then the screen mode should be restored after playback (or Kodi's exit at the latest).

**Comment by stumpalump** [comment]
> 
> Now that I tested more rigorously (multiple screens have an effect) I see the switch to SDR happen when starting playback with the setting on. I wasn't expecting it but if it's meant to do that, then the screen mode should be restored after playback (or Kodi's exit at the latest).

Yes exactly glad you agree. I think the better way might be to cache the setting on Kodi start and return to that after playback, as I mentioned. But I'm still learning will have to figure out how to do that! This fix works for now as it checks if stream is HDR and Autoswitch is enabled before toggle

**Comment by CrystalP** [comment]
Hello @stumpalump, would you continue this work to record the OS HDR switch state before playback in order to restore it later?

**Comment by stumpalump** [comment]
> Hello @stumpalump, would you continue this work to record the OS HDR switch state before playback in order to restore it later?

Yes I can keep working on it in next few days

**Comment by thexai** [comment]
Superseded by https://github.com/xbmc/xbmc/pull/23509

**Pull request closed without merging**
