### PR TITLE
Add ICU4C library to Kodi build

### PR DESCRIPTION
**Pull request by fbacher**
## Description

ICU libraries are needed to resolve various Unicode issues including the dreaded Turkic I problem.
Another PR(s) will depend upon this library.

I am NOT skilled in enough with the Kodi build process to wire the build in properly. I provide basic
build scripts that 1) define env vars 2) download icu 3) configure icu 4) build icu, installing 
libs and includes into (hopefully) reasonable locations 5) build Kodi.

## Motivation and context

Dependent of PR Unicode utils #21690 

## How has this been tested?

I have built and ran Kodi. This lib is not yet used.
However, I have been using it for months using the same build process.

None, not yet used.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
Why not look at how other dependencies are handled in tools/depends/target.

Basically as the PR is it's a noop. We need to be able to build dependencies for all platforms.

**Comment by fbacher** [comment]
Ok. I'll spend a few more days trying to crack it.

**Comment by fbacher** [comment]
I thought that I was making progress until I realized that configure thinks that I am cross compiling. I haven't figured out how to stop it from concluding that.

I have been building happily for months using simple scripts that I got from the kodi site (build dependencies, wayland, etc.) But now that seems inadequate for building a new lib (icu). From "Kodi's Unified Build System" Readme, I see that I'm supposed to use bootstrap, configure, etc. (It took me an embarrasing amount of time to realize where I was supposed to run these. It was only when I saw the URL was tools/depends/README.md that I figured it out).

Anyway I am running with the following:
`<pre>/bootstrap
sudo  ./configure --with-toolchain=/usr --prefix=&quot;${INSTALL_DIR}&quot; --host=x86_64-linux-gnu --with-rendersystem=gl  CFLAGS=&quot;${CFLAGS_TOOLS}&quot; CXXFLAGS=&quot;${CXXFLAGS_TOOLS}&quot; CC=&quot;${C_COMPILER}&quot; CXX=&quot;${CXX_COMPILER}&quot;
</pre>`

But if you look the output it says that cross-compile is true. I modified the arguments, finally stripping all of them out and it still says that I am cross compiling. I do have gcc and clang on my system. My CXX_COMPILER, etc. are pointing at the clang variety. I have no idea what is wrong and so far my hunt on the web for how configure/autoconf determines this has been not too enlightening.  I have attached the output of running configure/autoconfd

file:///tmp/build.log

**Review by AlwinEsch — CHANGES_REQUESTED** [review]
This changes are looks in an not acceptable way!
- As Kodi is designed for all OS, are no `bash` scripts to insert, specially not on his main folder.
- Further are the changes hardcoded to one OS (seems Linux) where breaks all other OS.
- Also should never dependency libs be done inside main "CMakeLists.txt"
  - They should be as dependency on his cmake part, e.g. `./cmake/modules/FindICU4C.cmake` and set somewhere about Linux with `PLATFORM_OPTIONAL_DEPS` 
- And the `uconfig_local.h` can not be inserted as this way, there should be ways found to make without.

**Comment by AlwinEsch** [comment]
Checked on web about `ICU4C` seems available for all OS then no `PLATFORM_OPTIONAL_DEPS` required.
Only to add a `FindICU4C.cmake`, maybe try as this (not tested):
```cmake
#.rst:
# FindICU4C
# ------------
# Finds the ICU4C libraries
#
# This will define the following variables::
#
# ICU4C_FOUND - system has ICU4C
# ICU4C_INCLUDE_DIRS - the ICU4C include directory
# ICU4C_LIBRARIES - the ICU4C libraries
#
# and the following imported targets::
#
#   ICU4C::ICU4C   - The ICU4C library

if(PKG_CONFIG_FOUND)
  pkg_check_modules(PC_ICU_I18N icu-i18n QUIET)
  pkg_check_modules(PC_ICU_IO icu-io QUIET)
  pkg_check_modules(PC_ICU_UC icu-uc QUIET)
endif()

find_path(ICU4C_INCLUDE_DIR NAMES unicode/icudataver.h icudataver.h
                               PATHS ${PC_ICU_IO_INCLUDEDIR}
                                     ${PC_ICU_IO_INCLUDE_DIRS})
find_library(ICU_I18N_LIBRARY NAMES icui18n
                              PATHS ${PC_ICU_I18N_LIBDIR})
find_library(ICU_IO_LIBRARY NAMES icuio
                            PATHS ${PC_ICU_IO_LIBDIR})
find_library(ICU_UC_LIBRARY NAMES icuuc
                            PATHS ${PC_ICU_UC_LIBDIR})
find_library(ICU_DATA_LIBRARY NAMES icudata
                              PATHS ${PC_ICU_UC_LIBDIR})

set(ICU4C_VERSION ${PC_ICU_UC_VERSION})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(ICU4C
                                  REQUIRED_VARS ICU4C_INCLUDE_DIR
                                                ICU_I18N_LIBRARY
                                                ICU_IO_LIBRARY
                                                ICU_UC_LIBRARY
                                                ICU_DATA_LIBRARY
                                  VERSION_VAR ICU4C_VERSION)

if(ICU4C_FOUND)
  set(ICU4C_LIBRARIES ${ICU_I18N_LIBRARY}
                      ${ICU_IO_LIBRARY}
                      ${ICU_UC_LIBRARY}
                      ${ICU_DATA_LIBRARY})
  set(ICU4C_INCLUDE_DIRS ${ICU4C_INCLUDE_DIR})
  set(ICU4C_DEFINITIONS -DHAVE_ICU4C=1)
endif()

mark_as_advanced(ICU4C_INCLUDE_DIR 
                 ICU_I18N_LIBRARY
                 ICU_IO_LIBRARY
                 ICU_UC_LIBRARY
                 ICU_DATA_LIBRARY)
```

if the `UNISTR_OBJECT_SIZE` not relates to library (memory overflow if used there) can maybe inside Kodi this added below his include:
```cpp
#ifdef UNISTR_OBJECT_SIZE
#undef UNISTR_OBJECT_SIZE
#define UNISTR_OBJECT_SIZE 256
#endif // UNISTR_OBJECT_SIZE
```

**Comment by fbacher** [comment]
I am very grateful for the suggestions. I apparently went about this completely the wrong way.

**Comment by fbacher** [comment]
Need advice:
Kodi will have to be able to build icu4c on all platforms because although icu4c is readily available on Linux and Windows from Unicode.org, it is not universally available as a pre-built, supported lib. 

I have managed to build vi Makefile using ffmpeg as a model (but without the cmake stuff). I get a bit lost with the  build path variables and how to properly integrate a build with Kodi. Is there a better package to use as a model?

I see that there is official CMAKE support for using (not building) ICU in a cmake project. https://cmake.org/cmake/help/latest/module/FindICU.html. I only just noticed it.

There is a generic open source cmake wrapper around icu ( https://github.com/viaduck/icu-cmake)  that downloads, configures, builds and provides a means to integrate with your project. It is not versioned, but it has been around six years and shows recent updates. Still it is not inspiring that it does not have an official release. I have managed to build using it on Linux, but I am stuck trying to figure out how to integrate with Kodi. I have used ffmpeg as the model and can build using a script driver to Make. Should I follow ffmpeg's approach and modify the main CMakeList.txt, or should I model after some other package? 

As much as I like my initial experience with the icu-cmake build wrapper, I am worried about its long-term prospects and platform support. It all depends upon the motivation to build with cmake. Otherwise it seems more prudent to build with Make and to integrate with FindICU.

What do you advise: 

- Build with Make or icu-cmake
- Integrate with Make or icu-cmake or FindICU
- What existing module should I use as a model?

**Comment by lrusak** [comment]
Just use make.

**Comment by fbacher** [comment]
I'm FINALLY able to build Kodi and icu using cmake, but more polish is needed. I have a Makefile that can build icu, but I need to work on integrating it with Kodi's build. I assume that I have to add it to a list in CMakeLists as well as add it to the parent makefiles. 

My biggest headache with using cmake is that cmake's externalproject_add kept messing up the command line and environment variables. I liked to add quotes or spaces where they did not belong. I finally gave up and had it create a temp script containing the said strings and got it to work perfectly. What a PITA.

I do have several questions:

- ICU's libs default as shared. Is that OK, or do you prefer static?
- I assume that the shared libs should be installed into the INSTALL_DIR (or whatever it is officially called) and not the BUILD_DIR. I probably have to add it to some install list somewhere in CMakeLists.

I'll be out for two weeks

**Comment by garbear** [comment]
@fbacher Good progress so far, Kodi's depends system is a massive beast and it's encouraging seeing someone take the challenge head-on.

I'm less sure from a technical standpoint, but from a historical standpoint shared libraries on the Xbox were key to the low memory available. Since then, we've moved a lot of libraries back to statically linked. I suppose the benefits of shared libs don't outweigh the costs for us currently. But certainly explore that option if you want.

**Comment by fbacher** [comment]
I am now able to build on Ubuntu 22.04 using cmake. You can choose whether to use downloaded ICU or one that is locally installed (and discoverable by pkgconfig). Do I need to be able to build via Makefile as well? Should not be a big deal to add, since it will simply call cmake with the appropriate args.

**Comment by garbear** [comment]
Nice job getting it to build. Yes, you should create/modify the Makefile in `tools/depends`. It can probably just call into CMake. Our depends system is used on all embedded platforms, so adding the Makefile is needed.

It'll take a while but you can search all the existing Makefiles for any dependencies that build in a similar manner.

When I added flatbuffers, I tested on multiple embedded platforms so that I could verify that I did the Makefile correctly. I also tested a depends build (instead of system packages) on Ubuntu. Our depends system isn't meant to be used on Ubuntu, but a depends build still works.

**Comment by garbear** [comment]
You probably have a mobile phone that supports Kodi, both android and ios use depends. macOS uses depends too.

Jenkins only builds depends when they change, and rebuilding depends adds about half an hour to the build. But feel free to use our infra to build as much as you want, that's what it's there for. Once the Europeans go to bed it's pretty much idle anyways.

**Comment by fbacher** [comment]
Closing until I can make time to get back to it and do a bit more research for Android.

**Pull request closed without merging**
