### PR TITLE
cppcheck performance fixes in network/

### PR DESCRIPTION
**Pull request by tobbi**

### CODE REVIEW

**Comment by ace20022** [comment]
jenkins build this please

**Comment by phate89** [comment]
I have a question to see if I understand well something,
ok post increment is in theory slower than pre increment but doesn't every good compiler nowadays automatically optimize it when is not needed?

**Comment by Jalle19** [comment]
AFAIK it can only be optimized for primitives.

**Comment by mkortstiege** [comment]
@tobbi could you please silent the reorder compiler warnings in EventClient? Thanks.

**Pull request merged**
