### PR TITLE
Yet more include cleanups

### PR DESCRIPTION
**Pull request by MaxKellermann**

### CODE REVIEW

**Comment by Rechi** [comment]
Can you order the includes lexicographical. I know they aren't consistent everywhere, but at least try to not mess up more then it is already.

**Comment by garbear** [comment]
Most of my code uses lexicographical order with directories before files, it doesn't really matter just try to be consistent with what is already in the file.

**Comment by MaxKellermann** [comment]
@Rechi found the code guideline describing that; I'll fix my patches and re-push.

**Comment by MaxKellermann** [comment]
Rebased and sorted includes according to code guideline.

**Comment by notspiff** [comment]
jenkins build this please

**Pull request merged**
