### PR TITLE
Swig 3.0.10

### PR DESCRIPTION
**Pull request by MartijnKaijser**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by phil65** [comment]
Is this a completely trivial update? Some stuff in 3.0 changelog is marked with  `*** POTENTIAL INCOMPATIBILITY  ***`

**Comment by MartijnKaijser** [comment]
Unlikely :) 
Hence this will need some testing. Though openelec/libreelec are already at 3.0.9 and we only use this for python file generation

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by akva2** [comment]
i have been running with swig3 through xenial repos (3.0.8) since april with no apparent issues. i think it's a completely trivial update (by pure luck).

**Pull request merged**
