### PR TITLE
EPG - Delete timer 'All' option fails to delete timer rule

### PR DESCRIPTION
**Pull request by linknetx**
## Description

In the EPG, selecting 'Delete timer' on a program with a series timer rule opens the 'Confirm delete' dialog asking 'Do you only want to delete this timer or also the timer rule that has scheduled it?' with two options 'All' or 'Only this'.

Both options have the same result and only delete the selected timer. The 'All' option fails to delete the timer rule.

This PR fixes this issue with the 'All' option now deleting the parent timer rule. 

In the original code 'ruleTag' is never returned, only 'Tag' is returned for both options.

## Motivation and Context

As above.

## How Has This Been Tested?

Compiled and tested 'All' and 'Only this' options on an EPG program with series timer rule. The 'All' option now deletes the parent timer rule as expected.

## Screenshots (if appropriate):

See comments for screenshot of the dialog referenced above

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by Rechi** [comment]
wrong revision was build
jenkins build this please

**Comment by linknetx** [comment]
Just checked, this line of code was present in 17.6 but has been omitted in 18.0

**Review by ksooo — APPROVED** [review]
Good catch. Thanks.

**Comment by MartijnKaijser** [comment]
@ksooo at least the commit message has extra text on the extra lines

**Comment by linknetx** [comment]
@ksooo what would be a more meaningful commit message to describe this?

**Comment by ksooo** [comment]
Ah, I missed the extra lines. ;-) In github web ui you just see

screenshot 2019-02-03 at 17 40 00

... which is not very meaningful...

**Comment by ksooo** [comment]
We usually do not include "Update foo.bar" in out commit mesages.

**Pull request merged**
