### PR TITLE
[Estuary] Backport Estuary fixes

### PR DESCRIPTION
**Pull request by Hitcher**
## Description

Backports:
https://github.com/xbmc/xbmc/pull/24000 Fix home categories focus position
https://github.com/xbmc/xbmc/pull/24041 Fix alignment of counter labels
https://github.com/xbmc/xbmc/pull/24024 Fix 'Shift' view for Collections

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by HitcherUK** [comment]
@garbear deleted the other fork too soon, sorry.

**Comment by lrusak** [comment]
You'll need to rebase on Nexus or be on a Nexus branch and cherry pick the commit you want.

It's a little annoying because when you do this it pings a bunch of people.

Please check the diff and commit list before opening a pull request.

**Comment by garbear** [comment]
Here's the branch:

https://github.com/HitcherUK/xbmc/commits/backport-fix-categories

Missing the actual commit.

Once you make a new commit and push it to this branch, you can target `Nexus`.

**Comment by HitcherUK** [comment]
Sorry @lrusak and thanks @garbear

**Review by garbear — APPROVED** [review]
Looks good now!

**Review by garbear — APPROVED** [review]
Leaving approval for the additional two backports, as they match upstream

**Pull request merged**
