### PR TITLE
ViderPlayerAudio: fix setting of resample mode on stream change

### PR DESCRIPTION
**Pull request by mglae**
## Description

Race: CAudioSinkAE::SetResampleMode() may be called before CAudioSinkAE::Create() and the mode set is lost.

That is no issue if m_synctype == SYNC_DISCON in CVideoPlayerAudio::SetSyncType() because it defaults to 0 but m_synctype == SYNC_RESAMPLE is lost.

~~This PR is saving the mode in CAudioSinkAE::SetResampleMode() and apply it at end of CAudioSinkAE::Create(). Using mode 0 by default seem not to cause any restriction.~~

This PR is invalidating the previous sync type after new Sink was created. Sync type will be set again.

## Motivation and context

While watching live TV I've noticed audio distortion from time to time. In PlayerDebug the rr value stuck to 1.000000.

The distortion occur when the audio stream change from 2.0 to DD 5.1. Finally the issue could be reproduced without live TV using a recording with setting "Sync playback to display" enabled.

Debug log: [kodi.omega.dd.race.log](https://github.com/xbmc/xbmc/files/11240247/kodi.omega.dd.race.log)

In the log the audio stream of the recording is created three times: 

```
# 1. Opened:
2023-04-15 12:00:14.768 T:10022    info <general>: Creating audio stream (codec id: 86016, channels: 2, sample rate: 48000, no pass-through)
2023-04-15 12:00:14.768 T:10022   debug <general>: CVideoPlayerAudio:: synctype set to 1: resample

# 2. Seek before stream change:
2023-04-15 12:00:14.768 T:10022    info <general>: Creating audio stream (codec id: 86016, channels: 2, sample rate: 48000, no pass-through)
2023-04-15 12:00:14.768 T:10022   debug <general>: CVideoPlayerAudio:: synctype set to 1: resample

# 3. Change from DD 2.0 to DD 5.1:
2023-04-15 12:00:21.487 T:10022   debug <general>: CVideoPlayerAudio:: synctype set to 1: resample
2023-04-15 12:00:22.063 T:10022    info <general>: Creating audio stream (codec id: 86019, channels: 6, sample rate: 48000, no pass-through)
```
The third time the order of calls is reversed.

## How has this been tested?

Some weeks on my LibreELEC installation in the living room.

## What is the effect on users?

Less audio issues.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fritsch** [comment]
@FernetMenta Could you comment. The is obviously a workaround, which moves responsability into the audiosink to work with a cached value, while the original design did not forsee it that way.

Can we somehow fix the calling order or is the workaround legit?

**Comment by FernetMenta** [comment]
I would rather reset m_prevsynctype, m_synctype (as done in OpenStream) before m_audioSink.Create

**Comment by fritsch** [comment]
Thanks much @FernetMenta make sense. @mglae could you do it that way?

**Comment by mglae** [comment]
Done, thanks for the feedback. Is working after a first test.

**Review by fritsch — APPROVED** [review]
m_syncType is already set by OpenStream and the logic for reconfigure is set whenever prevType is != syncType, so the code change should be fine.

**Pull request merged**
