### PR TITLE
Cleanup music ratings

### PR DESCRIPTION
**Pull request by razzeee**
This tries to do the following:
- Separate rating and userrating for music
- Give albums and songs both rating types
- Move everything to 1-10 ratings

The tricky part about this, was that albums only had scraped ratings (called "rating") and songs only had userratings. Both used the rating field of the music tag. So I tried to unravel this with this PR.

This will also have the side effect, that rating now is a float. And that some addons might think rating is a userrating. They need to be updated.

@DaveTBlake as this is music
@Montellese as it has json rpc changes
@zag2me as you might like this
Special thx to @ronie 

screenshot 2015-11-18 20 17 56
screenshot 2015-11-18 20 17 47
screenshot 2015-11-18 20 18 37
screenshot 2015-11-18 20 18 17
screenshot 2015-11-18 20 18 10

### CODE REVIEW

**Comment by zag2me** [comment]
Love it! This is a great improvement and looks like you have done it how I had hoped in terms of storing a user rating and total rating in separate fields. For info, TADB stores exactly these fields using the same scale so I can see all kinds of possibilities! Scrapers, user submission, cloud backup of ratings in the future.

I wonder if this will break skins that currently show track ratings, or if they will just show 5 stars for anything over 5...

TADB also keeps a record of the number of votes for the total rating, that might be nice to store in the future as well. I'm not sure if we already do this for imdb votes?

**Comment by ronie** [comment]
this will 'break' skins, as ListItem.StarRating has been removed 
and has to be replaced by another method to show stars.

**Comment by Razzeee** [comment]
We already store the vote count for videos yes.

**Comment by DaveTBlake** [comment]
Don't have any personal views on this as ratings are not my thing, but will try to feed back user view that I have picked up. Seeing stars rather than a number does seem popular, not sure what we would need for that. Being able to set with a minimum of clicks also important. This does seem something that needs a fair amount of user trail to make sure it gives them what they want.

**Comment by Razzeee** [comment]
Stars can be shown if we want. As long as it's not in the sortlabel I guess. @ronie for clarification. 
Not sure if we should, as media info, not has much space.

**Comment by DaveTBlake** [comment]
Small stars? For some numbers are too techie? Not sure either. 

Myself I would like that limited media info space to give composer depending on what I am playing, but not expecting anyone to agree :)

**Comment by ronie** [comment]
yup, it's up to skins whether to display the (user)rating as stars, text or both.
it may even be possible to use the stars images as a sortlabel (would need to test to make sure).

**Comment by Razzeee** [comment]
Added votes. as @zag2me asked for them.

Will squash that in the next days.

**Comment by Razzeee** [comment]
Let's see if this works on all platforms
jenkins build this please

**Comment by zag2me** [comment]
Ping @olympia for the scraper upgrade

**Comment by Razzeee** [comment]
jenkins build this please

**Comment by Razzeee** [comment]
jenkins build this please

**Comment by Razzeee** [comment]
Might also solve http://trac.kodi.tv/ticket/16201

**Comment by Razzeee** [comment]
Rebased and squashed

jenkins build this please

**Comment by DaveTBlake** [comment]
@Razzeee not sure why we have 2 steps in database version in this one PR. Can they not be combined?

**Comment by Razzeee** [comment]
They can, but I wasn't sure if somebody had the previous version running already. I'll rebase that away later.

**Comment by Razzeee** [comment]
Rebased and added an equivalent to https://github.com/xbmc/xbmc/pull/8488

**Comment by Razzeee** [comment]
jenkins build this please

**Comment by HitcherUK** [comment]
@Razzeee Fresh install and after scanning music to library nearly all user ratings are 10 even though they haven't been set yet.

**Comment by Razzeee** [comment]
Your sure your tags don't have ratings in them?

**Comment by HitcherUK** [comment]
It seems to have picked them up from NFO files even though none of them contained any user ratings. Now them problem is scraped ratings are still 0-5 so nothing gets a higher rating than 5/10.

**Comment by ronie** [comment]
> It seems to have picked them up from NFO files even though none of them contained any user ratings. 
i had this one as well, but at the time i noticed it, i couldn't reproduce it anymore.

> Now them problem is scraped ratings are still 0-5 so nothing gets a higher rating than 5/10.

confirmed. scraped album rating should be multiplied by 2 when you upgrade to k*** afaik, but it doesn't happen.

> EDIT: Another weird one - refresh info, then change user rating and you end up with this in the list -

i don't see that, but i noticed you'll loose your userrating when you refresh album info.
when you refresh, we probably ditch the entire db entry i guess.

**Comment by Razzeee** [comment]
Well scrapers need an update to 1-10 for k***
Though @hitcher was referring to that?

**Comment by ronie** [comment]
> Well scrapers need an update to 1-10 for k***

sure, but the existing ratings in the db should as well?
i guess both should be done at the same time.

**Comment by Razzeee** [comment]
Yes, they should. Is didn't happen for you? As hitcher said he started fresh and it shouldn't apply to him then.

**Comment by olympia** [comment]
I've got completely lost here. So do you expect me to ammend the scraper(s) to accomodate this? If yes, what would be needed?

**Comment by Razzeee** [comment]
@olympia 
Hey :)
It's basically just that we're able to store ratings for albums and songs now. Albums should already be possible now, but we moved from 0-5 to 0-10
So you need to set the max flag when scraping, if I didn't do anything wrong. For e.g.:
https://github.com/xbmc/repo-scrapers/blob/gotham/metadata.common.allmusic.com/allmusic.xml#L394

**Comment by MartijnKaijser** [comment]
We will still need a repo branch for 17 (which will come soon) to push the scraper to.

**Comment by zag2me** [comment]
@olympia TheAudioDB.com now supports both intScore and intScoreVotes from standard album and track methods. intScore is the average score out of 10 (to 1 decimal place), and intScoreVotes is the number of users who have submitted a score. Feel free to update any scrapers using this.

**Comment by DaveTBlake** [comment]
This change has inserted fields in types.json,  "votes", "userrating",  in the middle of the enums rather than at the end. Is this a problem for JSON backward compatibility @Montellese or @tolriq ?

**Comment by Tolriq** [comment]
Well from history (https://github.com/xbmc/xbmc/pull/2366#discussion-diff-3277085) and since then Montellese always asked to put all new values to the end.

And while the changes to types should not break anything it's still better to add at the end.

And this https://github.com/xbmc/xbmc/pull/8405/files#diff-4252ea25ea01026195fc9eeaaec2a806R1468 is backward compatibility breaking for "parameter-by-position"

**Comment by DaveTBlake** [comment]
Since I am adding some fields to the json types in my current PR, shall I move these to the end to restore the "parameter-by-position" @Razzeee , or is that just going to cause more confusion?

**Comment by Tolriq** [comment]
Well this is @Montellese call for the types.

But the breaking generated by https://github.com/xbmc/xbmc/pull/8405/files#diff-4252ea25ea01026195fc9eeaaec2a806R1468 (Rating not at correct position) should be fixed by the author :)

**Comment by DaveTBlake** [comment]
For simplicity (save two of us editing the same line) I will fix the order of fields as part of #8015 that I am hoping to merge soon.

**Pull request merged**
