### PR TITLE
[Apple] Remove GL warning [osx] add binary addon target to xcode project

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
This adds the option to have binary addon targets added to an xcode project.
This is the same feature as was introduced for darwin_embedded https://github.com/xbmc/xbmc/pull/17554 

## Motivation and Context
Parity for the apple platforms

## How Has This Been Tested?
locally with osx

Example
```
make -C tools/depends/target/cmakebuildsys CMAKE_EXTRA_ARGUMENTS="-DENABLE_XCODE_ADDONBUILD=ON -DADDONS_TO_BUILD='pvr.hdhomerun peripheral.joystick game.libretro'" GEN=Xcode
```
With the above, a binary-addon target will be added to an xcode project that will build pvr.hdhomerun, peripheral.joystick and game.libretro

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
Piggybacking 2 temp commits to try to narrow down the git blamer long execution we are seeing for apple platforms.

**Comment by ksooo** [comment]
Cool! Thanks for that!

**Review by wsnipex — APPROVED** [review]

**Comment by wsnipex** [comment]
hmm, is https://github.com/xbmc/xbmc/blob/master/CMakeLists.txt#L459-L462 no enough?

**Comment by fuzzard** [comment]
Theres a couple slight differences.
I havent found a way to easily provide the ADDONS once the target is part of the xcode project. Im sure its possible somehow, but hasnt really bothered me enough to change the approach.
The second big difference is the add_dependency to the project, so essentially you click build, and it builds everything provided from the single cmake command.

Im sure that may be something i could ifdef into where you have linked it, but not sure its worth muddying the waters personally. I can go down that route if you want i guess.

The PR change only affects the Xcode generated project. The part you link is still valid, and available to a makefile generated project for osx. ios/tvos just dont have the ability to be built from a makefile (for our purposes) any more.

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by ksooo** [comment]
@fuzzard why don't we merge this for v19?

**Comment by fuzzard** [comment]
Honestly it was a build change with low priority. My naive thoughts were a release would be done well before now.

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Review by garbear — APPROVED** [review]
Thanks, the GL warnings were minor annoyances.

**Comment by Countrygrl00** [comment]
> ## Description
> 
> This adds the option to have binary addon targets added to an xcode project.
> 
> This is the same feature as was introduced for darwin_embedded https://github.com/xbmc/xbmc/pull/17554 
> 
> 
> 
> ## Motivation and Context
> 
> Parity for the apple platforms
> 
> 
> 
> ## How Has This Been Tested?
> 
> locally with osx
> 
> 
> 
> Example
> 
> ```
> 
> make -C tools/depends/target/cmakebuildsys CMAKE_EXTRA_ARGUMENTS="-DENABLE_XCODE_ADDONBUILD=ON -DADDONS_TO_BUILD='pvr.hdhomerun peripheral.joystick game.libretro'" GEN=Xcode
> 
> ```
> 
> With the above, a binary-addon target will be added to an xcode project that will build pvr.hdhomerun, peripheral.joystick and game.libretro
> 
> 
> 
> ## Screenshots (if appropriate):
> 
> 
> 
> ## Types of change
> 
> 
> 
> - [ ] **Bug fix** (non-breaking change which fixes an issue)
> 
> - [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
> 
> - [X] **Improvement** (non-breaking change which improves existing functionality)
> 
> - [ ] **New feature** (non-breaking change which adds functionality)
> 
> - [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
> 
> - [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
> 
> - [ ] **None of the above** (please explain below)
> 
> 
> 
> ## Checklist:
> 
> 
> 
> 
> 
> - [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
> 
> - [ ] My change requires a change to the documentation, either Doxygen or wiki
> 
> - [ ] I have updated the documentation accordingly
- > []()
> - [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
> 
> - [ ] I have added tests to cover my change
> 
> - [ ] All new and existing tests passed
> 
>

**Comment by fuzzard** [comment]
windows test failure unrelated.

Will look to merge this in the next couple days just to get off the books.

**Pull request merged**
