### PR TITLE
[addons] Remove unneded dlfcn includes

### PR DESCRIPTION
**Pull request by palinek**
## Motivation and Context

It is a remnant from old days and including of
p8-platform/windows/dlfcn-win32.h prevents removal of p8-platform
dependency for addons which doesn't need it (build failure on windows
platform).

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [X] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by palinek** [comment]
In #15988 it was discussed, that `dlfcn` is not needed any more.

**Comment by Rechi** [comment]
Have you compile tested all binary add-ons for all platforms?

**Comment by palinek** [comment]
> Have you compile tested all binary add-ons for all platforms?

If strictly required. For this, of course, I would need help from someone who can setup/trigger such test build on jenkins.

**Comment by Rechi** [comment]
Yes it is required to know nothing breaks. Please check for as many platforms as possible locally and provide the results.

**Review by AlwinEsch — APPROVED** [review]
Have looked over the addons, only `game.libretro` and `inputstream.adaptive` using currently the `dlopen`, but they already include the `dlfcn.h` by self.

This is still a remnant where at that time was a DLL between Kodi and addon. But not necessary anymore.

**Comment by Rechi** [comment]
@AlwinEsch  please always set the version label, other labels and milestone before or right after merging a PR.

I hope you **compile tested** this with all add-ons on all platforms to not cause any issues.

**Pull request merged**
