### PR TITLE
changed: Improve error handling for video db export

### PR DESCRIPTION
**Pull request by arnova**
Previously when users exported their video library and they had e.g. sources that were for some reason not writable (although we assume they are), an error dialog would popup for every single item failing to export. This PR changes this behavior by allowing the user to ignore all remaining errors at the first failure.

As an alternative we could also silently ignore all errors (like is already the case with the music db) and report number of errors when done. Ideas?

### CODE REVIEW

**Comment by arnova** [comment]
@mkortstiege @MartijnKaijser : Your take on this?

**Comment by arnova** [comment]
Changed so that we report errors during export using toasts, which seems like a better/more user friendly approach. ps. Still need to squash, but left the initial commit for comparison between the 2 solutions.

jenkins build this please

**Comment by mkortstiege** [comment]
Looks good.

**Comment by arnova** [comment]
@mkortstiege : Updated for music db export. Also added a commit which fixes a small bug I tripped on.

jenkins build this please

**Comment by arnova** [comment]
If no objections, will merge this afternoon

**Pull request merged**
