### PR TITLE
[Android] pause audio playback when headphone is disconnected

### PR DESCRIPTION
**Pull request by matthuisman**
## Description

Refactoring of @oldk1331 original PR (https://github.com/xbmc/xbmc/pull/17030) to use android.intent.action.HEADSET_PLUG instead of android.media.AUDIO_BECOMING_NOISY as that was getting triggered with frame-rate switches causing unwanted pausing behavior.

Also, added in a check to make sure we can pause before trying to do so.
If not - then stop playback instead.

I used g_application.GetAppPlayer().CanPause() as PLAYBACK_STATE_CANNOT_PAUSE was always True even on content that can pause. I suspect its because its only being set in OnPlayBackStarted and CanPause() always returns False at that stage.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by matthuisman** [comment]
jenkins build this please

**Comment by matthuisman** [comment]
@oldk1331
Feel free to pull request this yourself and I will close this.
It's your feature after-all :)

**Comment by matthuisman** [comment]
havnt heard from original author, so enabling this PR

**Comment by phunkyfish** [comment]
jenkins build this please

**Comment by matthuisman** [comment]
just fixed the clang formatting

**Comment by fuzzard** [comment]
Are we aware if this has been runtime tested to function as expected with the headphone removal?

**Comment by matthuisman** [comment]
Iv tested with my phone as works as expected. Pauses vod content and stops live content

**Comment by fuzzard** [comment]
Ok, cool.

Jenkins build this please

**Review by peak3d — APPROVED** [review]

**Pull request merged**
