### PR TITLE
Replace defines

### PR DESCRIPTION
**Pull request by notspiff**
## Description
Get rid of preprocessor usage

## Motivation and context
Type safety

## How has this been tested?
It builds, and basic sanity checks passes

## What is the effect on users?
Zilch

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by garbear — APPROVED** [review]
Dost thou comprehend the wrath one has unleashed?  This is the first mass replacement with constexpr in our codebase. The plebes will sing praise of the noble Spiff for starting the movement, for he is the one who is not there. Also we're glad you are there.

**Comment by notspiff** [comment]
But not all wast good in the kingdom of the Unpreprocessed. For the unholy clang-forrmat tried to intervene through its minion bot. But our hero was strong and just and ignored the bugger.

**Comment by malvinas2** [comment]
Would `constexpr `be sufficient in this case, instead of `constexpr const` ?

**Comment by notspiff** [comment]
No, they should be immutable.

**Pull request merged**
