### PR TITLE
[keymap] remove invalid actions

### PR DESCRIPTION
**Pull request by ronie**
there's no such thing as JUMPSMS1

```
22:28:08 T:139935491103104    INFO: Loading special://xbmc/system/keymaps/universalremote.Harmony.xml
22:28:08 T:139935491103104   ERROR: Keymapping error: no such action 'jumpsms1' defined
22:28:08 T:139935491103104   ERROR: Previous line repeats 3 times.
```

@Memphiz

### CODE REVIEW

**Comment by Memphiz** [comment]
i will integrate it in the other pr that is pending because i rename those map files there - is there a replacement for jumpsms?

**Comment by Memphiz** [comment]
i wonder why jumpsms1 is not valid but the other (jumpsms2 and so on) are?

**Comment by Memphiz** [comment]
have it integrated into #9656 (made it number1 so a user who wants to alter it sees that button id 111 is valid) ... thx

**Comment by Montellese** [comment]
@Memphiz: There's probably no `jumpsms1` because on any T9 keyboard the button `1` is used for special characters like dot, comma etc. and we don't support jumping to special characters. `ABC` is on button `2` and so on.

**Pull request closed without merging**
