### PR TITLE
[favourites][listproviders] Fix select action not to show the choose …

### LINKED ISSUE #24628: Choose dialog for versions added to favorites / No Choose dialog for movies added to favorites
### Describe the bug

After adding a version to the favorites, selecting it in the Favorites screen opens the Choose dialog.

~~Opposite situation: with the setting to show versions as a subfolder off, after adding a movie with multiple versions to the favorites, selecting it browses into the version.~~

EDIT: Works as designed. If the setting is ON, a favourite for browsing the versions will be created. If it is OFF a favourite to play the default movie version will be created. But once the favourite is created, changing the setting value has no effect on the behaviour of the favourite.

## Expected Behavior

Specific version (from the folder representing the versions of a movie) added as favorite: the default select action is applied to the version, there is no Choose version dialog.

Movie with multiple versions added as favorite: Choose dialog if "Show versions as folder" is OFF, browse into the versions if "Show versions as folder" is ON. Regardless of setting, a context menu > Play should play the default version (currently always browses into versions of the movie and no context menu Play button)

## Possible Fix

Add missing "has_resolved_video_asset" property to items, but this may be more complicated since the favorite items are persisted,
I don't know if properties are serialized/deserialixed with the items.

### To Reproduce

1. Set "Show videos with multiple versions as folder" to ON
2. Go to the library
3. Browse into a movie with versions
4. Use context menu > Add to favourites on one of the versions
5. Exit library, go to Favourites screen
6. Select the version
7. The Choose dialog opens

note: context menu > play works as expected and plays the version

~~1. Set "Show videos with multiple versions as folder" to OFF
3. Go to the library
4. Use context menu > Add to favourites on a movie that has multiple versions
5. Exit library, go to Favourites screen
6. No context menu > Play button for the movie
7. Select the version
8. The versions appear as a folder~~

EDIT: Not reproducable.

### Debuglog

The debuglog can be found here: not relevant https://paste.kodi.tv/irrelevant.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: v21 current master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
…video version dialog for movies with multiple versions but to directly play the version.

Fixes #24628 

Runtime-tested on macOS, latest Kodi master.

@CrystalP please review.

### CODE REVIEW

**Comment by CrystalP** [comment]
It's true that the choose dialog doesn't show anymore for favorited specific versions but that also changed the behavior for parent movies added as favorites, which play the default version at the time they were favorited instead of popping the dialog or browsing.

It looks like when playing the favorite, the original path is not available anymore. Path and dyn path are identical. But maybe something can be done with the information captured when the favorite is created?

If it's too complicated then we have to pick between correct handling of parent movies or individual versions. Maybe also block the creation of the favorites that won't play as expected.

**Comment by ksooo** [comment]
You are right and this PR is my “offer” to deal with the problem. I do not want to put more effort into this currently. 

It’s an edge case and honestly I would like to get rid of this version choose dialog completely better done than later, because it neither fits technically into kodi architecture nor it’s ux concept.

**Comment by ksooo** [comment]
> If it's too complicated then we have to pick between correct handling of parent movies or individual versions. 

 It's not complicated, but too risky to change this shortly before RC. For reasons I don't know, for videodb items the dynpath is stored with the favourites (loosing the path), which makes it impossible to distinguish between a certain version or the parent movie.
 
> Maybe also block the creation of the favorites that won't play as expected.

 I would not go that far.

**Review by CrystalP — APPROVED** [review]
Approved, with the addition of comments explaining the limits of the fix

**Pull request merged**
