### PR TITLE
[fix][udf] Free allocated memory in the destructor.

### PR DESCRIPTION
**Pull request by ace20022**

### CODE REVIEW

**Comment by ace20022** [comment]
@MartijnKaijser does this qualify for a backport?

**Comment by MartijnKaijser** [comment]
think so if it fixes the problem. Though you would have to play a lot of blurays for it to become a problem right?

**Comment by ace20022** [comment]
> think so if it fixes the problem. Though you would have to play a lot of blurays for it to become a problem right?

IIRC 1000 (or 100) times Sintel iso leads to ~200 mb.

But your decision, I'm not very interested in the old branch.

**Comment by MartijnKaijser** [comment]
yeah just leave old behind us :)

**Comment by ace20022** [comment]
jenkins build this please

**Comment by fritsch** [comment]
If this fixes the issue and helps to save 200 MB when playing a single iso
and you consider this a fix, please backport.

It is worth it.

2015-09-13 20:56 GMT+02:00 Martijn Kaijser <notifications@github.com>:

> yeah just leave old behind us :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/xbmc/pull/8036#issuecomment-139907764>.
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by mkortstiege** [comment]
jenkins build and merge. Please backport ;)

**Comment by kfarhat** [comment]
Remove my email from your email please don't email me anything I am NOT
interested in anything

**Pull request merged**
