### PR TITLE
[cmake][win] Generate complete build dir layout for Multiconfig gen (VS)

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Currently when building on windows, all of the bundled files for a complete packaged Kodi are copied/generated at cmake project generation time, and therefore will place these files at ${CMAKE_BINARY_DIR}/

These folders include the following, plus all the shared DLL's required for kodi on windows
```
addons
media
system
userdata
```

Due to this, when Kodi is built using VS with the different Build types (eg RelwithDebInfo, Debug, Release), the executable is built and placed in $$\{CMAKE_BINARY_DIR}/\${BUILD_TYPE}/ where BUILD_TYPE is only generated/available at build time, and not cmake project generation time. Build type is an example of a difference in cmake MultiConfig Generators (eg VS/Xcode) and single config generators (eg. Makefile/Ninja) where the variable isnt available at generation for MultiConfig, but is in Single config.

Generator expressions in cmake are a very mixed bag of availability. Unfortunately for our cases, the best way i can deal with the unknown build type at generation is to create scripts that have inputs that allow the access of a generator expression value that are executed post_build/prebuild of a target. This is at build time, and therefore the multi config variables about BUILD_TYPE can be known.

## Motivation and context
Allow to build and switch between build types in VS, and still be able to execute each created build without any manual handling of relocating the executable.

If anyone has any suggestions for alternate handling, im all ears. I initially started this due to playing with windows python 3.11 build internally in kodi. The existing dll copy routines would not copy python libs/folders, as they dont exist at cmake generation time (clean build without prebuilt python). This, or something like it, are required to allow us to copy files that are created after cmake project generation.

## Note 1
There are still quirks regarding lib building. in particular currently PCRE. I wont get into this too much, but the logic around only adding internal build targets if a lib exists is very complicated (of which i dont have a solution for multi config generators). In the event you build kodi (eg as Debug), clear the build dir, generate kodi project and build as a different build type (eg Release), you will come across link issues (lib built against debug crt/whatever system libs, but app is being built against release crt/whatever system libs).
Essentially the only way around this is to either build all build types of a lib (eg Debug, Release, RelwithDebinfo, whatever else) all at once, or if you clean the build dir without building all of the types on first generation, remove the relevant libs so the ENABLE_INTERNAL_XXX flag will rebuild the lib.

## Note 2
Realistically the root issue should technically occur when using Xcode, but our packaging scripts all handle this already for Apple platforms. I didnt really want to dive into changing all of that, when we just dont come across the pitfalls that windows VS does. One day it might be nice to generalise these changes to target any MultiConfig Generator, but thats for another day, maybe.

## How has this been tested?
Build UWP/x64 windows and execute the built executable without any further modifications (eg copying the executable from $$\{CMAKE_BINARY_DIR}/Debug to ${CMAKE_BINARY_DIR})
All directories for a packaged bundle (ie Kodi NSIS installer) are now correctly located in the relevant build type dir

## What is the effect on users?
N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by enen92** [comment]
Curious, do you think this fixes the issue of libdvd.dll not being included in the installer after I removed the wrapper (https://github.com/enen92/xbmc/commit/02242fbebac45dfb3b49d30835c5675430920837)?

**Comment by fuzzard** [comment]
No idea. As long as the DLL is in the dependspath before the app target is built, it should get bundled though

**Comment by fuzzard** [comment]
Ran a job that uploaded test builds for ios/osx/win x64/win uwp x64/android aarch64.

Compared each to latest nightly. Folder structure is correct on each, all shared libs are bundled, addons are available (ios packages them), and they execute.

From my end, the PR is functionally ready for a review. Obviously no intention to merge until v21, so no rush.
I'll rebase to drop the first 2 commits (another PR), and squash the fixups

**Comment by thexai** [comment]
I'm not against this PR but I am against have Python 3.11 compiled internally. This in practice means that Jenkins is going to compile it every time just like it happens now with taglib, crossguid, flatbuffers, libdvdcss, libdvdnav, libdvdread, rapidjson...

Some dependencies are really slow to compile because CMake configure and generate steps in Windows are slow (or very slow in some cases).

It is simply not feasible to do this with ALL dependencies. We have to look for a new method, but while it doesn't exist, probably the best solution is to update the dependencies in https://github.com/xbmc/kodi-deps (just like Python 3.8.15 and OpenSSL 1.1.1q).

It's tedious but it's because of the work it takes to update the dependencies, not because the system is bad.

Perhaps the ideal solution would be to integrate the already existent `kodi-deps` scripts into the main kodi repository, i.e. convert  "download-dependencies" script to "download-and-build-dependencies" but outside of the main kodi solution/project.

Then Jenkins can build deps using same scripts at step is currently `download-dependencies.bat` (before build Kodi)

These dependencies would be packaged in the same format that exists now and placed in download folder.... from here nothing changes, Kodi can be compiled either with dependencies downloaded from mirrors or with the same format of dependencies generated in the previous step (in Jenkins). 

The main advantage is that these dependencies would only be generated when they do not exist. Like now they are only downloaded when they do not exist in the download folder. It also solves the problem of release/debug depends since this does not happen with the dependencies generated in https://github.com/xbmc/kodi-deps and the script could be practically the same.

**Comment by fuzzard** [comment]
Just want to confirm. Have tested the following scenarios.

- Buildsetup.bat - kodi.exe is executable from kodi-build.x64\Release dir
- Manual cmake generation, manual cmake build Debug/RelWithDebInfo - kodi.exe is executable from <builddir>\RelWithDebInfo and <builddir>\Debug
- Manual cmake generation, open solution in VS, Build RelWithDebInfo attached to "Local Windows Debugger" - VS executes built executable with debugger attached.

Id like to get this merged to ease some further dev work.

**Comment by thexai** [comment]
> Allow to build and switch between build types in VS, and still be able to execute each created build without any manual handling of relocating the executable.

I'm sorry but I don't understand what the problem is currently. I can at least start the build from within the Visual Studio GUI and don't need to move the generated .exe (no manual handling). And Kodi run in debug mode with all functional same that when is in Release mode and installed with installer.

> There are still quirks regarding lib building. in particular currently PCRE. I wont get into this too much, but the logic around only adding internal build targets if a lib exists is very complicated (of which i dont have a solution for multi config generators). 

Now that's a issue right now because it forces you to manually delete or move files to get things to work. But this PR does not solve it I think.

I only see two solutions: make it build every time (even if it already exists). That is, the same behavior as `taglib`. Or leave it back as it was before (pre-compiled dependency) and update in https://github.com/xbmc/kodi-deps

There is a third solution that would be to build Debug and RelWithDebInfo at the same time but only once although I don't know if it can be done or how to do it.

On the other hand, it would be desirable for `taglib` to only be built when it does not exist.... i.e. same as it is now `libnfs`

**Comment by fuzzard** [comment]
If you do not build with VS, you cannot just run the executable. That is the point. To make packaging more manageable and concise.

Look at your build dir right now. You will see a bunch of libs, an assortment of folders, mixed with cmake files and VS projects. This cleans that mess up. Everything to package a build type is in the relevant build type folder.

**Comment by thexai** [comment]
For me it's OK if we can keep debugging kodi from Visual Studio GUI and we can keep building installer with BuildSetup... ie it doesn't cause any regression. Although (for me) it is not an advantage.

> Forget the pcre issue, its not relevant to this. I'll deal with that later.

OK

**Comment by thexai** [comment]
Tested this PR and in Windows x64 all seems fine. Compared installer build before/after and contains exactly same files. Also tested CMake generated manually and opened with Visual Studio GUI and all is functional. Effectively now you can run Kodi.exe from build dir which is very good.

But UWP installer is broken (missing many files):

**Before:**

Installer-before

 **After**

Installer-after

Note that .msix files are ZIP files and can be renamed and opened with any file management program.

**Comment by fuzzard** [comment]
Cheers, i'll have a look into the msix bundling failures

**Comment by fuzzard** [comment]
Took another run at this. Packaging UWP is now functional.

Tested an x86-64 build from BuildSetup.bat, cmake generation and then VS build/execution. cmake generation and manual build via cmake. All functional.
Runtime tested a UWP-x86_64 package built, and compared existing package to latest nightly.

@thexai definitely would appreciate any testing you can do to confirm/spot anything i may have missed.

The one minor difference is the inclusion of zlibd.dll in a release package. Dont have an easy way to filter that out right now, but it doesnt change the executable at all, just adds ~80kb from memory to the package size.
I'll look at revisiting this another time, i dont really see it as a blocker at this point.

The intent for this is to hopefully lead into updating the packaging of windows builds. I want to pull the packaging OUT of BuildSetup.bat, and look at using a CPack NSIS target that can then be called from anywhere (eg in Vis Studio, or via cmake command).
This also allows us to handle shared libs/data that might be built during a build. The existing system requires things to be in place at configure time.

Currently its implemented for windows, but its actually for cmake multi config generators (ie Xcode/Visual Studio). I havent plumbed in the Xcode side of things, but this sets the groundwork for that to slot in, and also to simplify/control some of the external packaging scripts we use for apple/android as part of the cmake system rather then (some of) the external scripts.

@enen92 this should handle things like your libdvd stuff when you eventually go down that path. This all started with the goal of being able to build python for windows, and still be able to bundle the shared lib/data at build time, which this now handles.

**Comment by thexai** [comment]
I have not time to test now but if msix installer contents are the same go ahead

**Comment by fuzzard** [comment]
Did one last test-build of this. Artifacts are on mirrors test-build folder. Installed each of x86, x86_64, UWP64 and tested instaling a repo addon and playing back a media item. So its functional. I'll merge and deal with fall out as it appears.

**Comment by asavah** [comment]
This PR might have broken `ninja` builds on linux.

```
cmake -GNinja -DSOME_CMAKE_OPTIONS_HERE /path/to/src/dir
ninja

ninja: error: 'addons/skin.estuary/media/Textures.xbt', needed by 'CMakeFiles/generate-packaging', missing and no known rule to make it
```

"Classic" `make` build succeeds with the same cmake configuration. With https://github.com/xbmc/xbmc/pull/23754 applied ofcourse.

The cause might be in the removal of custom_command with DEPENDS, so now cmake doesn't know where those xbt files come from exactly.
https://github.com/xbmc/xbmc/pull/22112/files#diff-cf71f1d6edb7b976bae666a34a55fe94408e4c5df923dee17c820ec08dda8cfeL12-L18

**Comment by mackal** [comment]
> This PR might have broken `ninja` builds on linux.
> 
> ```
> cmake -GNinja -DSOME_CMAKE_OPTIONS_HERE /path/to/src/dir
> ninja
> 
> ninja: error: 'addons/skin.estuary/media/Textures.xbt', needed by 'CMakeFiles/generate-packaging', missing and no known rule to make it
> ```
> 
> "Classic" `make` build succeeds with the same cmake configuration. With #23754 applied ofcourse.
> 
> The cause might be in the removal of custom_command with DEPENDS, so now cmake doesn't know where those xbt files come from exactly. https://github.com/xbmc/xbmc/pull/22112/files#diff-cf71f1d6edb7b976bae666a34a55fe94408e4c5df923dee17c820ec08dda8cfeL12-L18

I'm also experiencing this build failure. doing a git bisect points to this commit.

**Comment by fuzzard** [comment]
Fix is in https://github.com/xbmc/xbmc/pull/23761

For future reference, its really better to open a separate issue and point to the PR that caused the regression. It allows the fix to be registered against the issue and auto close it, and makes the issue (and any fixes) more visible if others come searching.

**Pull request merged**
