### PR TITLE
[Video] Fix blank codec and incorrect channels for some PCM audio streams

### PR DESCRIPTION
**Pull request by CrystalP**
## Description

- Complete the migration to the new channel layout API in CDVDDemuxFFmpeg::AddStream: feed the channel layout provided in the codecpar structure directly into the new API av_channel_layout_describe.
Instead of attempting a conversion to the old API and back to new again, with information loss and no handling of the situation of channels >0 and 0 mask (the provided sample).

- AV_CODEC_ID_PCM_S16LE was not defined in CDemuxStreamAudio::GetStreamType(). Added the currently defined range of PCM codec ids to return "PCM". Testing as a range should be fine since the values are part of the public API. I didn't find an ffmpeg function returning all pcm formats or a is_pcm(), which would be preferable.

Testing the range of pcm id doesn't fit well in the current switch/case structure...
I could have done:
```
    default:
      if (codec >= AV_CODEC_ID_PCM_S16LE && codec <= AV_CODEC_ID_PCM_SGA)
        strInfo = "PCM ";
      else
        strInfo = "";
      break;
```
but that's doesn't look good to me either.

## Motivation and context

Sample provided by @jjd-uk showed an empty audio codec description and 0 channels in audio selection, even though it plays fine with audio.

## How has this been tested?

Tried the sample and other videos with different codecs and channel counts.

I don't have other pcm examples and don't know if the missing layout is to be expected  with that codec family.

## What is the effect on users?

Shows correct codec information for more videos.

## Screenshots (if appropriate):
before (no codec, 0 channels instead of 2)
image

after:
image
It shows " 2 channels" because of the blank layout mask of the stream.
With a standard stereo mask, it would show "stereo".

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Hitcher** [comment]
Confirmed fixes PCM audio streams.

Before:

screenshot00026

After:

screenshot00027

**Comment by neo1973** [comment]
Jenkins build this please

**Review by sundermann — APPROVED** [review]

**Comment by CrystalP** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by neo1973** [comment]
@CrystalP: The Jenkins build failures are because of warnings because of unhandled enum values in https://github.com/xbmc/xbmc/blob/65267ab3dcf7295485fd55b97e5fa0de51ac9747/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemux.cpp#L16 Adding back the `default` should silence that.

**Pull request merged**
