### PR TITLE
[cmake][addons] remove p8-platform, kodi-platform and tinyxml from depends

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description
This to allow addons to be inserted independently if needed.

Most addons don't use them, so there is no point in creating them for everyone. 

In addition, it increases construction times considerably, especially with AppVeyor, which very often gets frozen due to dependencies and then only stops after an hour.

## Motivation and Context
I will make sure before this comes in that the necessary dependencies have been added to the respective addons.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by AlwinEsch** [comment]
jenkins build this with addons please

**Review by garbear — APPROVED** [review]

**Comment by AlwinEsch** [comment]
jenkins build this with addons please

**Comment by AlwinEsch** [comment]
jenkins build this with addons please

**Comment by AlwinEsch** [comment]
jenkins build this with addons please

**Comment by AlwinEsch** [comment]
jenkins build this with addons please

**Pull request merged**
