### PR TITLE
[kodi-resource] add language resource icon

### PR DESCRIPTION
**Pull request by un1versal**
Just recently added has no icon in repo list.

This icon could be used for the other languages resource

@Montellese also related https://github.com/uNiversaI/kodi/commit/bb727f718b551aa31a8d9644e35da3a0f9661b55 for your commit https://github.com/xbmc/xbmc/commit/d96e69c818c8995aa03769d773b6996b9052d1bd now available on https://github.com/uNiversaI/revamped.themes/archive/2.3.5.zip for testing/usage.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
icon is wrong as resource could be anything

**Comment by uNiversaI** [comment]
What do you suggest then?

**Comment by notspiff** [comment]
Folder is wrong, it should be a skin-level image not the icon for the base type. See Addon.cpp, there is a table with icon association and such.

**Comment by uNiversaI** [comment]
can you both be more specific please.

**Comment by notspiff** [comment]
It should be something like DefaultAddonLanguageResource.png and shipped with the skin. You have done this before dude. It is not an icon for an addon but an icon for an addon category. Cannot be more specific.

**Comment by MartijnKaijser** [comment]
kodi.resource is an extension that will be used for languages/images/sounds and whatever.

**Comment by uNiversaI** [comment]
DefaultAddonLanguageResource.png does not exist as no one created it I added it to my theme https://github.com/uNiversaI/kodi/commit/bb727f718b551aa31a8d9644e35da3a0f9661b55 and its on added on PR https://github.com/xbmc/xbmc/pull/5350

This PR is not that. its for the addon itself

So again am at the loss here.

**Comment by MartijnKaijser** [comment]
seriously can't explain it better

**Comment by uNiversaI** [comment]
I understand the extension point portion, it has no icon for the addon nor the repo so why its wrong when nothing exists idk.  and none it is then as none has given any guidance that is understandable. you both pointing to refrences to something that does not exist.

A better explanation is showing me an example for something that exists so I can visualize it or some image you can feel explains it better.

**Comment by uNiversaI** [comment]
***this is image for resource addon*** This PR 
icons 

***this is image for the repo category*** (does not exist yet)
defaultaddonlanguage

I dont understand what is wrong about this one

**Comment by MartijnKaijser** [comment]
seriously???
kodi.resource DOES NOT ONLY MEAN LANGUAGE

**Comment by uNiversaI** [comment]
Yes I can make others for other resource types whats the problem with that?

**Comment by MartijnKaijser** [comment]
so who cares that they don't exist! I told you what it was for, end of story

**Comment by uNiversaI** [comment]
So you want a generic icon for both yes?

**Comment by Montellese** [comment]
We need a generic one for kodi.resource which is not language specific and one that is language specific (which you've already done with the folder icon).

**Comment by uNiversaI** [comment]
thx, for that CLEAR explanation.

unfortunately now I won't do either as someone is going on a hanger fit closing all my PR's

**Pull request closed without merging**
