### PR TITLE
CUDFFile: switch to using libudfread

### LINKED ISSUE #17588: Can't Open ISO
### Describe the bug
Here is a clear and concise description of what the problem is:

Hello,
I have issue for opening ISO (4k and 1080p) files from SMB share (Windows Server 2016) with latest build.

Already tested build :

- KodiSetup-20200330 : Issue
- KodiSetup-20200314 : Issue
- KodiSetup-20200311 : Issue
- KodiSetup-20200310 : Issue
- KodiSetup-20200301 : Work

Same error on other computer and on a Android tablet S5E

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

ISO is not open and kodi show error message

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
[kodi01March Build work.log](https://github.com/xbmc/xbmc/files/4408904/kodi01March.Build.work.log)
[kodi10March Build Crash.log](https://github.com/xbmc/xbmc/files/4408905/kodi10March.Build.Crash.log)
[kodi11March Build Crash.log](https://github.com/xbmc/xbmc/files/4408906/kodi11March.Build.Crash.log)
[kodi14March Build Crash.log](https://github.com/xbmc/xbmc/files/4408907/kodi14March.Build.Crash.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

error iso

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 Pro X64 19041.172 Build (Windows 10 2004/20h1)
 - Kodi version: 19.0
 - AMD Drivers : 20.3.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by lrusak**
In my naivety with #16263 I didn't realize that bluray's use a udf filesystem and subsequently broke it.

This fixes it by using libudfread from videolan as that natively supports udf 2.5 and vfs implementations.

so yay! bluray ISO's work again and work over the vfs (nfs/smb/etc).

Hopefully this covers all the cases so let's test it thoroughly now.

This fixes #17588 

This adds the new CMake options:
`ENABLE_INTERNAL_UDFREAD` to allow building libudfread with cmake
and
`ENABLE_UDFREAD` to enable udf support in general (needed for blurays)

### CODE REVIEW

**Comment by fuzzard** [comment]
Pretty minimal changes in the grand scheme of things. Get it into @MilhouseVH builds for a couple days to tease out any more corner cases i guess.

**Review by garbear — APPROVED** [review]
New code looks fine

**Comment by DaVukovic** [comment]
image

"Play Main Title" is missing from the simplified menu and I can't switch the audio track to german anymore. But the video at least is playing ;)

**Comment by wsnipex** [comment]
Please add downloading and non-depends building to the Makefile, analogous to libdvd* and dav1d

**Comment by DaVukovic** [comment]
Tested latest changes and everything seems fine to me. :+1:

**Comment by mediabrasiltv** [comment]
Windows OS need to download libudfread dependence right...
merge PR here but continue to don´t playing BDs ISO when using in windows 64 bits.

**Comment by lrusak** [comment]
> Windows OS need to download libudfread dependence right...
> merge PR here but continue to don´t playing BDs ISO when using in windows 64 bits.

I'm not a windows dev so I can only do so much 😄

**Comment by lrusak** [comment]
> Please add downloading and non-depends building to the Makefile, analogous to libdvd* and dav1d

Why do we need this non-depends way? We can just build it via cmake. Maintaining 3 different build methods seems unnecessary :confused:

**Comment by wsnipex** [comment]
Because auto downloading during building is simply not possible when packaging for most linux distros. We have it for quite a few other libs that are not easily available from distro packages or where we have our own special version.

**Comment by lrusak** [comment]
> Because auto downloading during building is simply not possible when packaging for most linux distros.

@wsnipex Why though? If the libs are built statically with the project what does it matter?

**Comment by wsnipex** [comment]
As I have already explained this on multiple times over the years, distro packaging is heavily sandboxed, you usually do not have ANY internet access during the build phase.
That means it simply is not possible to download anything during build. ALL sources have to be provided beforehand, in the source package.

**Comment by lrusak** [comment]
> As I have already explained this on multiple times over the years, distro packaging is heavily sandboxed, you usually do not have ANY internet access during the build phase.
> That means it simply is not possible to download anything during build. ALL sources have to be provided beforehand, in the source package.

so can use just use the `<PKGNAME>_URL` cmake args to specify a local tarball?

**Comment by wsnipex** [comment]
Yes, and this local tarball must be present before building the source package

**Comment by lrusak** [comment]
> Yes, and this local tarball must be present before building the source package

So you're saying that it works as is and it's just inconvenient for you to download the tarball manually? :smiling_imp:

**Comment by wsnipex** [comment]
I'm not going to change my build scripts every time someone adds a new dependency and parse random cmake modules or Makefiles for URLs. Same goes for most other packagers.
We have a system for this and it's used in all libs that are customized by us or too new for most linux distros. If you are going to bikeshed about this, I'll simply stop maintaining the PPA.

**Comment by lrusak** [comment]
> I'm not going to change my build scripts every time someone adds a new dependency and parse random cmake modules or Makefiles for URLs. Same goes for most other packagers.
> We have a system for this and it's used in all libs that are customized by us or too new for most linux distros. If you are going to bikeshed about this, I'll simply stop maintaining the PPA.

I'm simply asking as it would be nice to simplify this. Maintaining 3 different build paths isn't nice. What happens when we switch to using only cmake? Will you change your build scripts then or still expect the same behaviour?

using the cmake args is the best way forward IMO, If you need it we can keep a list somewhere of the `<PKGNAME>_URL` args to make it more obvious (any package that has `ENABLE_INTERNAL_<PKGNAME>` should have the URL option).

Otherwise we need to add something to jenkins to test this code path with PR's because asking people to go over and above after Jenkins is all green seems necessary.

I hope you understand and we can figure something out together :dancing_men:

**Comment by candrews** [comment]
> I'm not going to change my build scripts every time someone adds a new dependency and parse random cmake modules or Makefiles for URLs.

I do exactly this for Gentoo. It's really not that big of a deal. And this concern only applies to bundled dependencies anyways - which distros very much frown upon. So package the dependencies, don't use the bundled ones (never set `ENABLE_INTERNAL_*`), and there's no problem.

**Comment by wsnipex** [comment]
If the time ever comes and we really switch to cmake only, then yes, I'll change my build scripts.
But once, and not for every new dependency. If you want to come up with a new system that works, fine for me as well. In the meantime I insist on this being added.

**Comment by lrusak** [comment]
> If the time ever comes and we really switch to cmake only, then yes, I'll change my build scripts.
> But once, and not for every new dependency. If you want to come up with a new system that works, fine for me as well. In the meantime I insist on this being added.

Ok, if you need it would you mind making a commit so it works for you and I'll pick that here?

**Comment by thexai** [comment]
Tested on Windows x64 and seems all OK.

Is need to compile `libudfread.lib` as static library.

I pick from here: https://code.videolan.org/videolan/libudfread

and compiled with MSYS2:

cd ./libudfread
./bootstrap
mkdir build
cd build
../configure --host=x86_64-w64-mingw32 --enable-static --disable-shared
make

renamed `libudfread.a` to `libudfread.lib`

and copy to:
`...kodi\project\BuildDependencies\x64\lib`

and copy includes to:
`...kodi\project\BuildDependencies\x64\include\udfread`

"Play Main title" and "Show BluRay menu" options works OK  :)

**Comment by fuzzard** [comment]
Windows deps haven't been done at all unfortunately.

Feel free to look at https://github.com/xbmc/kodi-deps/ if you want to dive into how they are "meant" to be done currently.
Gist of it is a custom cmake script created to create the lib. I'll be honest, I definitely don't understand how it works.

**Comment by thexai** [comment]
Is strange because seems someone already make download package in the past  :S

https://ftp.gnome.org/mirror/xbmc.org/build-deps/win32/libudfread-1.0.0-x64-v141-20200105.7z

**Comment by fuzzard** [comment]
good find, from memory libbluray has it as a dependency, that may explain that.

**Comment by thexai** [comment]
Is already available for all savours :)

Anotación 2020-04-09 114701

**Comment by jjd-uk** [comment]
Looking at the dates on that mirror for libudfread it looks to be about the same time as @Paxxi was updating the Windows depends packages although it wan't included in the PR https://github.com/xbmc/xbmc/pull/17143

**Comment by fuzzard** [comment]
This is my gripe with windows dependencies, supposedly kodi-deps is the way to go, but its hardly ever maintained/documented. anyways, ive notified lrusak, im sure when he wakes up he'll think about doing something.

**Comment by Paxxi** [comment]
It is up to date and documented but I haven't merged it back yet https://github.com/Paxxi/kodi-deps/tree/work

**Comment by thexai** [comment]
Probably exits a minor issue:

include dir in commits is "...include/udfread"  on  cmake/modules/FindUdfread.cmake
and on existing kodi-deps packages is "...include/libudfread"

**Comment by lrusak** [comment]
ok @Paxxi what am I missing?
```
08:53:04 -- Could NOT find Udfread (missing: UDFREAD_INCLUDE_DIR) 
```

> Probably exits a minor issue:
> 
> include dir in commits is "...include/udfread" on cmake/modules/FindUdfread.cmake
> and on existing kodi-deps packages is "...include/libudfread"

Thanks, we are aware :smile: @Paxxi is repackaging them

**Comment by wsnipex** [comment]
in the meantime I've packaged libudfread for ubuntu. Available from the nightly PPA

**Comment by Paxxi** [comment]
updated packages are on the ftp now
```
libudfread-1.0.0-arm64-v141-20200410.7z
libudfread-1.0.0-win10-arm-v141-20200410.7z
libudfread-1.0.0-win10-arm64-v141-20200410.7z
libudfread-1.0.0-win10-win32-v141-20200410.7z
libudfread-1.0.0-win10-x64-v141-20200410.7z
libudfread-1.0.0-win32-v141-20200410.7z
libudfread-1.0.0-x64-v141-20200410.7z
```

**Comment by lrusak** [comment]
@Paxxi and ideas about this one?

```
11:27:55 D:\jenkins\workspace\WIN-UWP-64\project\BuildDependencies\win10-x64\include\udfread/udfread.h(46): error C2371: 'ssize_t': redefinition; different basic types (compiling source file D:\jenkins\workspace\WIN-UWP-64\xbmc\filesystem\UDFBlockInput.cpp) [D:\jenkins\workspace\WIN-UWP-64\kodi-build\libkodi.vcxproj]
11:27:55   D:\jenkins\workspace\WIN-UWP-64\xbmc\platform\win32\PlatformDefs.h(22): note: see declaration of 'ssize_t' (compiling source file D:\jenkins\workspace\WIN-UWP-64\xbmc\filesystem\UDFBlockInput.cpp)
```
not really sure what to do about that? https://github.com/xbmc/xbmc/blob/master/xbmc/platform/win32/PlatformDefs.h#L22

**Comment by Paxxi** [comment]
Yeah needs a patch, will look into it tomorrow

**Comment by thexai** [comment]
On my work folder compiles OK but I use include files from: 
https://code.videolan.org/videolan/libudfread/-/tree/master/

([include.zip](https://github.com/xbmc/xbmc/files/4463216/include.zip))

Seems some differences.

Using includes from deps package obtained same error.

**Comment by Paxxi** [comment]
Fixed, actually tried building Kodi this time and it built for x64 debug and release so should hopefully be good 😄 
```
libudfread-1.0.0-arm64-v141-20200411.7z
libudfread-1.0.0-win10-arm-v141-20200411.7z
libudfread-1.0.0-win10-arm64-v141-20200411.7z
libudfread-1.0.0-win10-win32-v141-20200411.7z
libudfread-1.0.0-win10-x64-v141-20200411.7z
libudfread-1.0.0-win32-v141-20200411.7z
libudfread-1.0.0-x64-v141-20200411.7z
```

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
Jenkins build this please

**Pull request merged**
