### PR TITLE
VideoPlayer: create new audiosink if pt stream type changes

### PR DESCRIPTION
**Pull request by fritsch**
Fixes: https://github.com/xbmc/xbmc/issues/14591

### CODE REVIEW

**Comment by fritsch** [comment]
@iz8mbw it should - yes. I am currently building a PR test-build it will be available somewhere here: http://mirrors.kodi.tv/test-builds/android/ - check for 14598 in its name, please.

**Comment by boot2k3** [comment]
Tested on LE - no changes, still DTS and no audio after switching to AC3 video
Tested on Android, no audio and PCM stream on AVR after switching from DTS video to AC3 video
For the opposite direction the same result

**Comment by fritsch** [comment]
Then bad luck :-)

Dmitry_L <notifications@github.com> schrieb am Sa., 13. Okt. 2018, 14:37:

**Comment by fritsch** [comment]
Please post your debuglog. I am currently renovating a 🏠. Means limited time. Fernet's fix looked like exactly like what we need.

**Comment by boot2k3** [comment]
[kodi.log](https://github.com/xbmc/xbmc/files/2475484/kodi.log)
this debug log is from android system

**Comment by fritsch** [comment]
Argh, please use a pastebin. My phone does odd with these.

**Comment by boot2k3** [comment]
only here:
https://paste.ee/p/CaSz5
my log exceeded Pastebin max size

**Comment by FernetMenta** [comment]
please disable all extra logging if not explicitly asked to enable it. this creates a log of log spam and makes logs hard to read.

**Comment by iz8mbw** [comment]
Yes, issue persist also with this PR

**Comment by boot2k3** [comment]
Uploaded as requested
https://pastebin.com/wFJqzYSs

**Comment by FernetMenta** [comment]
@fritsch dataType has to be considered here too: CActiveAE::CompareFormat

**Comment by fritsch** [comment]
Tested on my system with the updated commit - works fine. Testbuild for Android is currently building.

**Comment by iz8mbw** [comment]
Thanks. I'll test when at home

**Comment by fritsch** [comment]
jenkins build this please (wrong revision built?)

**Comment by iz8mbw** [comment]
Thanks, solved also on Nvidia Shield. Thank you @fritsch

**Comment by MartijnKaijser** [comment]
Can you also try TrueHD to DTS-HD? Or TrueHD to DTS:X ?

**Comment by iz8mbw** [comment]
In pass-through no. In pass-through only Dolby Digital, Dolby Digital Plus and DTS.

**Comment by iz8mbw** [comment]
Good news!

**Pull request merged**
