### PR TITLE
[guilib] DialogKeyboard: Do not register input for buttons with id >= 500

### PR DESCRIPTION
**Pull request by phil65**
Allows to add custom buttons to Keyboard dialog without sending input on each button press. (atm any custom button will add its label to the input label when clickin on it)
@ronie, @mkortstiege

### CODE REVIEW

**Comment by mkortstiege** [comment]
Looks valid. Not sure what the exact use-case is though.

**Comment by phil65** [comment]
Adding custom buttons to DialogKeyboard (examples: auto-completion toggles, option to switch to a T9 Keyboard instead of our default keyboard layout (which is a pain in the ass for remote users) )

**Comment by mkortstiege** [comment]
OK, thanks explaining. Let's wait for @ronie.

**Comment by ronie** [comment]
makes sense. +1 from my end.

**Comment by mkortstiege** [comment]
jenkins build and merge.

**Pull request merged**
