### PR TITLE
[cleanup] nuke cximage / jpegio

### PR DESCRIPTION
**Pull request by stefansaraev**
clean up after #8583

### CODE REVIEW

**Comment by stefansaraev** [comment]
let's see if jenkins is happy. jenkins build this please

**Comment by stefansaraev** [comment]
@wsnipex libjpeg-turbo is defined as dependency of pil, but was not built, any clue?

https://github.com/xbmc/xbmc/blob/master/tools/depends/target/Makefile#L98

**Comment by stefansaraev** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by stefansaraev** [comment]
I think it is time to push this. objections?
if none, will do tomorrow.

**Pull request merged**
