### PR TITLE
drop old music and video database upgrade logic for pre-Frodo

### PR DESCRIPTION
**Pull request by MartijnKaijser**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
@Montellese @mkortstiege should there be some minimum db version added to lock out upgrading the old db versions and just start fresh for those?

**Comment by Montellese** [comment]
It's already there and it's called `GetMinSchemaVersion()` but it is defined in the header files so you need to adjust those as well.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
