### PR TITLE
[addons] change CAddonInfo usage to a shared_ptr

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description
This change the on CAddon inserted CAddonInfo who was before static
included as shared_ptr.

To have as shared_ptr is a major requirement to allow several types
on one addon together.

There becomes be on next steps for e.g. CPVRClient the same CAddonInfo given
as for maybe ADDON::CInputStream if on same addon.

Further becomes in future (other requests) the CAddonInfo with this
shared_ptr stored on CAddonManager in a list.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by AlwinEsch** [comment]
https://github.com/xbmc/xbmc/pull/12283 becomes updated after them.

**Comment by AlwinEsch** [comment]
Hello all, what do you thing about them? Please ignore #12283 currently.

Is a major part to allow several instances in future together on one addon, where the CAddonInfo can no more statically used.

**Comment by ksooo** [comment]
Judging  based on what you told me on Slack (existing design not usable / not easy extensible for multiple instances): +1 for merging this.

**Comment by ksooo** [comment]
> Judging based on what you told me on Slack (existing design not usable / not easy extensible for multiple instances): +1 for merging this.

 Ooops. Wrong PR. I was refering to #12283

**Review by ksooo — APPROVED** [review]

**Pull request closed without merging**
