### PR TITLE
[lang] move addon language file handing to CLocalizeStrings

### PR DESCRIPTION
**Pull request by tamland**
Currently strings are cached in the caddon instances. Since most of these instances have a very short lifetime, this causes language files to constantly getting reloaded and destroyed. E.g every time settings are opened, or an addon that uses strings is run, it's reloaded.

This move all language file handling for addons to the global string loader so that they can be loaded only once on startup.

### CODE REVIEW

**Comment by Montellese** [comment]
I haven't looked at the changes but have you considered what happens when an addon is updated and gets new language files? Do we recognize that and remove the previously loaded strings from that addon and load the new strings when first using the updated addon?

**Comment by tamland** [comment]
Yes. See changes in AddonInstaller. It's reloaded on install/update. There's no other situations it need reloading afaik (?)

**Comment by tamland** [comment]
@alanwww1 perhaps you can have a look, if you are around?

**Comment by tamland** [comment]
jenkins build this please

**Comment by tamland** [comment]
hm, anyone know why pi doesn't understand `emplace`?
>AR      xbmc/xbmc.a
CPP     xbmc/guilib/LocalizeStrings.o
LocalizeStrings.cpp: In member function 'bool CLocalizeStrings::LoadAddonStrings(const string&, const string&, const string&)':
LocalizeStrings.cpp:297:25: error: 'class std::map<std::basic_string<char>, std::map<unsigned int, LocStr> >' has no member named 'emplace'
LocalizeStrings.cpp:298:1: warning: control reaches end of non-void function [-Wreturn-type]
make[1]: *** [LocalizeStrings.o] Error 1

**Comment by popcornmix** [comment]
Looks like emplace requires gcc 4.8. I assume the jenkins cross compiler must be older.
I normally build with this compiler: https://github.com/raspberrypi/tools/tree/master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64
which is 4.8.3 and does build this PR.

**Comment by tamland** [comment]
Jenkins log says gcc 4.8.1, so it should be available. @Memphiz any idea?

**Comment by Memphiz** [comment]
where does it say 4.8.1? (maybe for android):

memphiz@vmlinux:/home/jenkins/rbpi-dev$ tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc --version
arm-linux-gnueabihf-gcc (crosstool-NG linaro-1.13.1+bzr2458 - Linaro GCC 2012.08) 4.7.2 20120731 (prerelease)

thats the toolchain which is used for rbpi ...

**Comment by tamland** [comment]
In http://jenkins.kodi.tv/job/LINUX-RBPI/6119/consoleFull. Definitely *mentions* "4.8.1"...
Chances of upgrading that?:) (No hurry though! I can use `insert` for now)

**Comment by Memphiz** [comment]
Will do tomorrow - to which one @popcornmix?

**Comment by Memphiz** [comment]
Those mentions for gcc 4.8.1 are the host compiler on the linux system - not the crosscompiler ...

**Comment by Memphiz** [comment]
@popcornmix i have cloned 

https://github.com/raspberrypi/tools

to 

/home/jenkins/rbpi-dev/tools2

You can test this (alter the buildsteps where needed in one of your branches and tell jenkins to build for rbpi) if you want and once it is ok - i would move it over to /home/jenkins/rbpi-dev/tools and remove the old toolchain ...

**Comment by tamland** [comment]
@Memphiz Was that directed at me, because I have no idea what means. You'll have to spell it out:\

**Comment by Memphiz** [comment]
nope it was more for popcornmix who knows better where to alter the buildsteps for using the new rbpi toolchain for a test...

**Comment by Memphiz** [comment]
I am Talking about adaptiv this file from tools to tools2 and Test the New toolchain with jenkins - https://github.com/xbmc/xbmc/blob/master/tools/buildsteps/rbpi/configure-depends

Might be Able to do it on sunday maybe

**Comment by FernetMenta** [comment]
@tamland when is this ready? I would like to complete the job on boost

**Comment by tamland** [comment]
@FernetMenta just need the jenkins bump + a quick rebase and it's good to go

**Comment by tamland** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
Only addons failed

**Comment by phil65** [comment]
>> Yes. See changes in AddonInstaller. It's reloaded on install/update. There's no other situations it need reloading afaik (?)

It would be nice if it could also get reloaded when ReloadSkin builtin is triggered. (I think core language files also behave like that)

**Comment by tamland** [comment]
@phil65 Not sure what you mean here. Skins use a special range inserted into the core strings instead of the normal addon strings handing, and it does appear to reload them with the skin: https://github.com/tamland/xbmc/blob/4d69d5a9c01fcfce8d6325abad4c1a8e6ade2387/xbmc/Application.cpp#L1652

**Comment by phil65** [comment]
What i noticed during add-on development is that add-on language strings do not get updated anymore when doing "ReloadSkin". I need to restart Kodi now for this.

**Pull request merged**
