### PR TITLE
[PVR] EPG Memory optimizations/Performance improvements

### PR DESCRIPTION
**Pull request by ksooo**
## Description
This is followup to #16953, where I announced:

"There is only one last puzzle piece left for making the "4K channels with 30 days of EPG" story actually true. Currently, all EPG data (all channels, all days) are permanently kept in RAM. This must be changed.

I plan to change the current EPG implementation to always use Kodi's EPG database for storing tags delivered by the clients and to load EPG tags on demand into RAM (- with some intelligent caching, ofc).

I believe that fetching the tags on demand from the clients will not work - performance wise. Clients do not expect to fetch and return single tags."

This PR implements the abovementioned last missing puzzle piece.

@phunkyfish @Jalle19 your code review would be appreciated
## Motivation and Context

I want to make the "4K channels with 30 days of EPG each" story actually true. Currently, keeping all EPG data (all channels, all days) are permanently in RAM, kills this story - memory and performance wise, even on machines with beefy CPUs and lots of RAM.

I tesed whether fetching EPG tags directly from the pvr clients on demand and dropping EPG database completely does work. It doesn't - perfomance-wise.

## How Has This Been Tested?

Several weeks by my whole family, on Android, in our living room.
Additionally extensive tests on macOS, including profiling and the like.

## Screenshots (if appropriate):

Nothing changed, except setting "PVR -> EPG -> Store data in local database" got removed, because now the database will always be used.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [x ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ x] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x ] All new and existing tests passed

### CODE REVIEW

**Comment by ksooo** [comment]
@MilhouseVH could you include this PR in your builds and ask especially Raspberry users for some feedback?

**Review by phunkyfish — APPROVED** [review]
Well done, I couldn't even find any nitpicks ;)

Sorry it took so long to review.

**Comment by ksooo** [comment]
rebased

**Comment by ksooo** [comment]
Jenkins is happy, no negative feedback from Milhouse build users, code review passed. Let's shove it in and we will see what I actually broke. ;-)

**Comment by CiNcH83** [comment]
Crashing on startup ([trace](https://www.dropbox.com/s/hcyjicnsgf5pqaf/kodi_pvr_crash.log?dl=1)).

**Comment by CiNcH83** [comment]
Ah... [fix pending](https://github.com/xbmc/xbmc/pull/17268)...

**Pull request merged**
