### PR TITLE
[guilib][gif] Make animated gifs loadable for any kind of textures, e…

### PR DESCRIPTION
**Pull request by ace20022**
….g., posters.

While not ideal (performance etc.), this allows the users to have animated posters, banners, textures in general.

### CODE REVIEW

**Comment by ace20022** [comment]
@natethomas fyi

A use case could be: https://www.dropbox.com/s/wmesvoq8ox7e0il/cooler.flv?dl=0

**Comment by ace20022** [comment]
jenkins build this please

**Comment by HitcherUK** [comment]
Can view .flv files in Pictures/File Manager but they're not visible when trying to add them as an art type in movies.

**Comment by ace20022** [comment]
> Can view .flv files in Slideshow/File Manager but they're not visible when trying to add them as an art type in movies.

This pr only applies to gif. flv is a video container. The gif from my sample video is from http://blog.timowens.io/the-cooler-animated-movie-poster/

**Comment by HitcherUK** [comment]
My mistake, I downloaded the flv from your link above and somehow used that instead of a gif.

However, I've now used the proper gif and added that as the poster but no animation.

**Comment by ace20022** [comment]
> ... but no animation.

Which skin etc.?

**Comment by zag2me** [comment]
Awesome BIG feature this one!

Just let us know how to test?

**Comment by ace20022** [comment]
> Just let us know how to test?

just use gifs as any artwork you want...

**Comment by ace20022** [comment]
If there are no objections I'll merge it tomorrow.

**Comment by zag2me** [comment]
Please do, would love to test it out in the nightlies

**Comment by ronie** [comment]
@ace20022 i'm trying to add animated weather images to one of the weather addons,
sadly kodi won't load the gif:

`DEBUG: Gif::PrepareTemplate(): Disposal method DISPOSE_PREVIOUS encountered, but could not find a suitable frame.`

example image:
image

**Comment by HitcherUK** [comment]
@ronie I think they only work when cached as library images.

**Comment by ace20022** [comment]
@ronie I'll have a look at it when I find some time.

**Comment by ronie** [comment]
thx :-)

**Comment by ace20022** [comment]
Okay, fixed it. The first frame of the gif has a wrong disposal method set, it should skip to the previous one which ofc does not exist. Since browsers seem to handle that, we should do that too.

**Pull request merged**
