### PR TITLE
[pvr] bump add-ons to their Isengard branch

### PR DESCRIPTION
**Pull request by MartijnKaijser**
updates alll pvr add-ons to their Isengard branch with updated translations

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build addons please

**Comment by MartijnKaijser** [comment]
jenkins build addons please

**Comment by FernetMenta** [comment]
we need to bump pvr addons again as soon as the bug in pulseeight-platform is fixed. The bug results in annoying "connection lost" messages which I want to have fixed before rc

**Comment by MartijnKaijser** [comment]
Any indication on when it will be fixed?

**Comment by FernetMenta** [comment]
I sent a fix to pulse eight.

**Comment by opdenkamp** [comment]
pulse-eight says that it'll probably be checked tomorrow morning ;-)

**Pull request merged**
