### PR TITLE
remove dependency from Unrar lib to GUIWindowManager

### PR DESCRIPTION
**Pull request by FernetMenta**
speechless :)

the dependency to filesystem should go too

### CODE REVIEW

**Comment by mkortstiege** [comment]
I think that's a leftover. I can recall some busy dialog hacks in here.

**Comment by Paxxi** [comment]
Heh nice one :)

**Comment by mkortstiege** [comment]
jenkins build and merge

**Comment by Montellese** [comment]
The only usage of the filesystem dependency is a single (but looped) call to `XFILE::CFile::Exists()`.

**Comment by FernetMenta** [comment]
> The only usage of the filesystem dependency is a single (but looped) call to XFILE::CFile::Exists().

maybe this could be passed as a callback to unrar lib

**Comment by notspiff** [comment]
that's not the only usage, it also reads its archive through CFile in file.cpp. there is no callback mechanisms in rarlib. the guilib dependency was from xbox days where threading was different so you had to do the gui in the same thread as the file class.

**Pull request merged**
