### PR TITLE
Add SVG mimetype

### PR DESCRIPTION
**Pull request by sarbes**
## Description
This PR adds support for the SVG mimetype, required to properly display SVGs in all places.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by phunkyfish** [comment]
Any reason why this can't go in?

**Comment by AlwinEsch** [comment]
Seen also no problems to bring, futher is it also a official mimetype, see https://wiki.selfhtml.org/wiki/MIME-Type/%C3%9Cbersicht#I which would make it 100% correct.

Think the request was probably just forgotten.

**Review by phunkyfish — APPROVED** [review]
Looks good

**Comment by fuzzard** [comment]
Jenkins build this please

**Pull request merged**
