### PR TITLE
[AirTunes] - features

### PR DESCRIPTION
**Pull request by Memphiz**
This PR bumps libshairplay (used for AirTunes music streaming) to latest master which incorporates all the patches we carried along till now and the following features which i hereby add to Kodi:
1. don't only support jpeg coverart but also png coverart
2. Implement a subset of DACP (digital audio control protocol) for allowing kodi to control the AirTunes client (support volumeup, volumedown, next track, prev track, pause, play, stop)
3. AirTunes is basically one endless audio stream without that much metadata inside of the stream itself (it only contains frame information like samplerate and thelike). All other metadata is delivered via callbacks outside of the stream data. ATM kodi support song metadata (name, album, artist, coverart). With this bump track metadata is also provided (track duration and current playtime). This PR adds evaluation of those progress data and injects it into the player.

The 3rd point is the one where is expect some cross winds. I tried to do it as non-intrusive as i could. I guess @FernetMenta is the one to comment on the approach i took here.

For the interested i have posted testbuilds of this PR here:

http://forum.kodi.tv/showthread.php?tid=203356&pid=2000370#pid2000370

The libshairplay maintainer works on a bigger revamp of the API which gives us audio sync information (for multi room synced playback) and maybe more. This PR is ment to be the last featureset based on the old api. The 3rd point might be overworked heavily (maybe based on elupus airtunes sync branch) so that progress injection might not stay for ever...

J\* material - needs ppa bump of shairplay when the PR is approved and merged...

### CODE REVIEW

**Comment by Memphiz** [comment]
As this was in the millhouse OE test builds for some months now i tend to merge this soonish. @wsnipex are you around for the needed ppa bump?

**Comment by MilhouseVH** [comment]
OE will also need to bump the libshairplay package to 0f41ade once this PR is merged.

**Comment by Memphiz** [comment]
How do we handle those normally? OE pulls from kodi - realises it doesn't compile and digs up the change? ;)

**Comment by MilhouseVH** [comment]
Probably :)

Thought I'd mention it just as a "heads up", although probably no reason for the libshairplay package bump not to proceed this pull.

**Comment by Memphiz** [comment]
I will ping someone from OE once ppa is set ;)

**Comment by wsnipex** [comment]
PPA updated, but not tested.

**Comment by Memphiz** [comment]
@wsnipex thx a bunch jenkins build and merge

**Comment by olafhering** [comment]
I think this commit lacks a configure check to catch an old shairplay-devel.rpm package from the OS. There is one already in configure.ac, perhaps it should now check for ->audio_remote_control_id instead of ->cls?

**Comment by Memphiz** [comment]
sounds like a valid point

**Pull request merged**
