### PR TITLE
File cache improvements

### PR DESCRIPTION
**Pull request by arnova**
This PR brings a couple of improvements concerning our filecache. The most important change is the move of cache related settings in as.xml from the network-section to its own cache-section + proper (re)naming of the settings. The way it has evolved no longer made any sense (cache is not only used by network) and the names were rather cumbersome. I also added an additional caching mode ("remote") and did some cleaning/refactoring.

### CODE REVIEW

**Comment by arnova** [comment]
jenkins build this please

**Comment by arnova** [comment]
jenkins build this please

**Comment by arnova** [comment]
@MartijnKaijser : You (or any others) against the change of the as.xml settings which obviously forces users to update their as.xml ?

**Comment by MartijnKaijser** [comment]
Nope

**Comment by NedScott** [comment]
The change actually has a very good positive in making people change their as.xml file, in that it makes many "bad guides" about cache settings outdated. While not the intention, it's a nice bonus ;)

I doubt this would be supported, but IMO this should be in the GUI, where the different settings can be explained. Ironically, keeping cache settings out of the GUI has actually caused more confusion because of the rise of various configuration "wizards", which don't tell the user which settings are safe. I also think it's used enough to be justified in the GUI. However, that's outside the scope of this PR, but I mention it in hopes that the idea will be more welcomed in the future :)

Any thoughts about changing the default to cache LAN traffic by default (SMB, NFS, etc)?

**Comment by popcornmix** [comment]
> Any thoughts about changing the default to cache LAN traffic by default (SMB, NFS, etc)?

I believe that enabling the cache makes seeking a little slower, and as the cache isn't usually needed for wired ethernet that doesn't sound worthwhile. If wireless could be reliably detected it might make more sense there, but I suspect that is not something kodi can easily determine.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by arnova** [comment]
@popcornmix / @NedScott : I already mentioned in the past that I'm all for enabling cache by default for all protocols except local. As an alternative we could move buffer-mode to GUI, but I would certainly not move mem-size and read-factor to GUI. @MartijnKaijser / others: Your take on this?

@popcornmix : It could be that seeks used to be slow due to the readratefactor hurting performance but since I upped it to 10 now it shouldn't be an issue anymore. Could you test whether it's still in fact true? We could perhaps even disable the limiter by default when we use CircularCache and just let it fill as fast as possible. It's a remnant of the Xbox-days anyways where hardware was limited and cache was on hdd.

**Comment by arnova** [comment]
ps. Take into account that I believe most of our users use wireless nowadays, but perhaps I'm wrong here?

**Comment by fritsch** [comment]
A factor of 10 drives the "average read" nuts. That basically means: Don't
throttle at all. Also reading with 100 Mbit/s an e.g. 10 Mbit/s stream also
works in combination with a large enough buffer. So it might be useful to
align the cache with average bitrate and the readbufferfactor.

2016-04-28 7:18 GMT+02:00 arnova <notifications@github.com>:

> ps. Take into account that I believe most of our users use wireless
> nowadays, but perhaps I'm wrong here?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/xbmc/pull/9681#issuecomment-215312666>
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by popcornmix** [comment]
The cache does significantly increase memory usage and cpu (an extra two memcpy's on any data read from file I imagine).
I wonder if promoting this to gui settings would be useful? Then the default behaviour could be overridden by platform settings files, but it's still easy for users to switch?

**Comment by arnova** [comment]
@fritsch : Mind elaborating that? I'm not sure what you mean.

**Comment by fritsch** [comment]
How long does it need for a connection to get up to 100 MBit/s speed. How long can you download with that speed to fill a buffer of 5MB?

With a 10 Mbit/s movie - how large must the cache be to hold 10 seconds of a movie? And how long does this 100 Mbit/s need to run to fill those 10 seconds?

**Comment by fritsch** [comment]
default_read_factor
(default setting)

factor10

(Factor 10)

You see what happens? The primary peak gets much larger, afterwards the buffer is full and nothing happens anymore. So what I said: higher speed is only helpful as long as you cache it.

This was playing Lord of the Rings via wireless network.

**Comment by fritsch** [comment]
cache10largebuffer

(Factor 10 with ~ 200 MB Buffer via local network)

**Comment by fritsch** [comment]
And here a 2gb cache:
2gb cache

It's filling with full speed. But after it was full once, it just continues to fill concerning the cache fill state:
2gb cache2nd

**Comment by fritsch** [comment]
And finally to also show what tuning helps most (my wireless can do 30 MB/s while kodi just got 16). When increase the ChunkSize - in my case in NFS VFS implementation I can easily get these 30 MB/s.

So let's not optimize at the wrong position, please.

See for example: https://github.com/popcornmix/xbmc/commit/e79ab7879aa23ef81d46021973fe239035617c61 which made raw bluray via nfs possible on the PI2 back at that time. I will upload new figures with that patch applied tonight.

**Comment by fritsch** [comment]
And here with the above VFS tuning, so if it is about throughtput - our VFS needs tuning and then we can think about caching, currently we loose nearly 50% with our read chunks logic on wireless connections, while the above tuning - proposed in this thread - has literally no impact in practice.

vfstuning

**Comment by arnova** [comment]
@fritsch: Ok, I'll drop the readfactor change. We'll look into that part later on then.

**Comment by arnova** [comment]
@fritsch / @MartijnKaijser / @popcornmix : What do we do with the buffer-mode setting? Keep it in as.xml or move it to GUI?

**Comment by MartijnKaijser** [comment]
imo buffermode is something too advanced and that user shouldn't even have to deal with such a setting at all to start with. I am still of the opinion that if we need this setting we are doing something wrong

**Comment by NedScott** [comment]
It's far less advanced than many settings we already have, and something being advanced should not be a reason to keep it out of the GUI now that we have advanced and expert GUI settings levels.

Like I said before, leaving it in as.xml has actually caused more problems because users apply settings blindly or from some "wizard". The cache settings are probably the most used as.xml setting right now, and moving this one setting to the GUI will help both the users and help them use the correct setting. 

This is not one of those times when you can say that we don't need a setting because that's doing it wrong. This is exactly the time when you do use a setting.  People have different networks, different needs, and Kodi has no practical way of detecting what they need (certainly not from a cross platform standpoint). Settings are not "bad".

**Comment by MartijnKaijser** [comment]
That's your opinion.

**Comment by arnova** [comment]
@MartijnKaijser : I partially agree with you but if we don't move this this to GUI (and again note I don't have a strong opinion about whether we should), we should work torwards enabling cache by default for any non-local filesystem. As an alternative we could add an option to the dialog when adding a new source. I've already looked at his before, but the problem with that it's non-trivial, but perhaps the most viable option?

**Comment by NedScott** [comment]
@MartijnKaijser I think there is some confusion here. This is about buffermode (what to buffer: internet only, internet + LAN, nothing). This isn't about the fill rate or the cache size. The network speed can't be used to figure out what the user wishes to have cached, especially for issues such as wifi interference, which won't be detected until it's too late for video playback.

**Comment by FernetMenta** [comment]
Those settings are beyond the skills of the average user, hence no gui setting. An advanced setting is not the way to go either. Having a setting only results in some try and error game.

**Comment by arnova** [comment]
Well we don't have a proper alternative it seems, so for now we might as well stick to as.xml . Btw. I don't see how this results in an "try and error game". It's pretty clear what it does IMHO..

**Comment by FernetMenta** [comment]
> Btw. I don't see how this results in an "try and error game". It's pretty clear what it does IMHO..

if it's pretty clear, why you we need a setting. Just auto set it to the best option.

**Comment by arnova** [comment]
We can't since we don't know about the environment we're operating in, only the user knows.

**Comment by arnova** [comment]
So you're proposing to get rid of this completely now?

**Comment by NedScott** [comment]
Consider PVR settings, which are far much more advanced, but still necessary, because you cannot "auto" this kind of thing. It's not hard. It's basically asking the user if they want to:

Buffer everything

Buffer only internet

Buffer LAN + internet

Buffer nothing

How is that hard to understand? How would you automatically decide which is best for a user?


Not everyone has to agree or have the same viewpoint, but it's pretty clear that this is in both high need and high demand from the userbase. It's the same as when there was a debate about "play next video automatically", which some people thought had no place in the GUI (that feature was a "fan favorite" for that release, by the way).

Every other media player on my desktop and my tablet has cache settings, by the way. Claiming this is too advanced for users is nonsense. It's almost like this idea won't be considered out of spite, either for the user, or for myself for being involved in this discussion.

**Comment by FernetMenta** [comment]
We can detect the environment and adapt to. The problem is that up to know not much devs did care which resulted in too many settings. Some even pretend AUTO but only get mapped to some other settings. I already told you about the new ProcessInfo object. The system can measure and learn about the environment. And an expert can do this much better than an average user.

@NedScott please get lost

**Comment by NedScott** [comment]
@FernetMenta If you believe I have said something inappropriate for this discussion then I apologize. I'm still in charge of the Kodi wiki, a member of the community, a member of LibreELEC, and now an employee of WeTek. As such, I will be involved in this discussion and many more in the future. I can assure you that any communications will be relevant and appropriate for the situation.

That being said, unless you are volunteering to replace the current cache system with something better, then I don't understand your objection to what is being discussed here. It appears that the GUI setting is already too disputed, so all that is left is an improvement on the current cache settings (as.xml and defaults) that are already in place. Is there an objection to _that_?

**Comment by FernetMenta** [comment]
@NedScott I don't care who ever made the big mistake to employ you. I don't consider you as a member of the community worth talking to. Github is a dev space and you are obviously no dev. Go trolling in the forums.

**Comment by arnova** [comment]
@FernetMenta : He does have a valid question: will we include this until we have something better? I think this could take a while.... ?

**Comment by FernetMenta** [comment]
@arnova I am not against this change here. I was just saying that we should not make this dependent on settings.
btw. paplayer would need this for local content because unlike VideoPlayer it has no 8 sec demuxer queue.

**Comment by arnova** [comment]
@FernetMenta : What do you mean exactly by "this change" ? And didn't we previously always cache files for PAPlayer? Or did this get lost when we moved to DVDPlayer-codec?

**Comment by FernetMenta** [comment]
> What do you mean exactly by "this change"

this PR

> And didn't we previously always cache files for PAPlayer

Some codecs did, others didn't. Same story here: there is no one-fits-all cache with a couple of parameters that should be configured by the user. Depending on the situation there are different requirements, that even change dynamically.

Instead of giving the controls to the user, we should give them to player, the components that use it. When going rw caching requirement are totally different from that when doing normal playback.

**Comment by arnova** [comment]
@FernetMenta : We'll sort that out later on, right? Seems non-trivial.

Good to go?

**Comment by FernetMenta** [comment]
yes

**Comment by username155** [comment]
After this was merged, davs streams are no longer cached, please see this thread: http://forum.kodi.tv/showthread.php?tid=272973

**Comment by arnova** [comment]
@username155 : Spotted the issue, fix will arrive soon.

**Comment by arnova** [comment]
Fix here: https://github.com/xbmc/xbmc/pull/9795

In the meantime you could set buffermode to "2" to workaround the issue.

**Pull request merged**
