### PR TITLE
[xbmc/utils] StreamDetails: additional common aspect ratios

### PR DESCRIPTION
**Pull request by palob**
## Description
This adds new aspect ratio categories to the video stream details labels.

## Motivation and context
Currently for movies in KODI there are the following aspect ratio categories:
**1.33:1 | 1.37:1 | 1.66:1 | 1.78:1 | 1.85:1 | 2.20:1 | 2.35:1 | 2.40:1 | 2.55:1 | 2.76:1**

Those are common standard movie aspect ratios.

The following notable ones are added

- **2.00:1** aka Univisium (categorised as 1.85:1 without this commit)
    This is an aspect ratio of surging popularity (especially for serials and streaming formats) lately.

    Some examples for feature films published in this aspect ratio:

    [Vera Cruz (1954)](https://www.themoviedb.org/movie/12766-vera-cruz)
    [Invasion of the Body Snatchers (1956)](https://www.themoviedb.org/movie/11549-invasion-of-the-body-snatchers)
    [The Last Emperor (1987)](https://www.themoviedb.org/movie/746-the-last-emperor)
    [Jurassic World (2015)](https://www.themoviedb.org/movie/135397-jurassic-world)
    [20th Century Women (2016)](https://www.themoviedb.org/movie/342737-20th-century-women)
    [Café Society (2016)](https://www.themoviedb.org/movie/339397-caf-society)
    [Green Book (2018)](https://www.themoviedb.org/movie/490132-green-book)
    [Midsommar (2019)](https://www.themoviedb.org/movie/530385-midsommar)
    [Another Round (2020)](https://www.themoviedb.org/movie/580175-druk)

    Examples for series:

    [House of Cards (2013-2018)](https://www.themoviedb.org/tv/1425-house-of-cards)
    [Stranger Things (2016-)](https://www.themoviedb.org/tv/66732-stranger-things)
    [Chernobyl (2019)](https://www.themoviedb.org/tv/87108-chernobyl)
    [Mare of Easttown (2021)](https://www.themoviedb.org/tv/115004-mare-of-easttown)

- **1.19:1** aka Movietone (categorised as 1.33:1 without this commit)
   This aspect ratio was used for some early sound films because of the sound track "eating into" the 1:1.33 full frame.
   Obsoleted by the Academy ratio (1:1.37) frame but still used for some modern films (for artistic reasons).

   Some examples for feature films published in this aspect ratio:
     [Sunrise (1927)](https://www.themoviedb.org/movie/631-sunrise-a-song-of-two-humans)
     [All Quiet on the Western Front (1930)](https://www.themoviedb.org/movie/143-all-quiet-on-the-western-front)
     [City Girl (1930)](https://www.themoviedb.org/movie/34796-city-girl)
     [M (1931)](https://www.themoviedb.org/movie/832-m)
     [Vampyr (1932)](https://www.themoviedb.org/movie/779-vampyr-der-traum-des-allan-grey)
     [The Testament of Dr. Mabuse (1933)](https://www.themoviedb.org/movie/12206-das-testament-des-dr-mabuse)
     [The Lighthouse (2019)](https://www.themoviedb.org/movie/503919-the-lighthouse)

- **1.00:1** (categorised as 1.33:1 without this commit)
    There's only one feature film I know of shot in this ratio: [Mommy (2014)](https://www.themoviedb.org/movie/265177-mommy).
    However this is widely used for streaming content, social media videos to be viewed on both TV/laptop/desktop screens (landscape format) and mobile phones (portrait format).

## What is the effect on users?
Movies present in (roughly) on of the above aspect ratio will have the correct aspect ratio stream detail shown.

## Types of change
- [X] **New feature** (non-breaking change which adds functionality)

## Checklist:
- [ ] This might need some kind of updated documentation if there are themes/skins which don't display ``VideoAspectToAspectDescription`` but parse it and show icons instead. 
If such skins exist (I don't know, just have seen screenshots which suggest so) icons for the new categories will need to be added by skin creators.

### CODE REVIEW

**Comment by HitcherUK** [comment]
Looks good but could please also add the relevant media flags to Estuary and Estouchy?

Found here -
`xbmc/xbmc//addons/skin.estuary/media/flags/aspectratio/`
and here -
`xbmc/xbmc//addons/skin.estouchy/media/flagging/aspectratio/`

Thanks.

**Comment by palob** [comment]
Ah, those are the kind of icons I had in mind, thanks for the hint.
Is there any template file (SVG, XCF or something) where those PNG graphics are generated from or will I have to "frankenstein" the existing ones in a raster graphics editor? Fortunately this is possible since all needed numbers for the new labels are already present in existing icons.

I'll also add the new values to the comment in [``xbmc/xbmc/GUIInfoManager.cpp``](https://github.com/xbmc/xbmc/blob/852b98da66bdc72e8488d991d66582dff0a98c0c/xbmc/GUIInfoManager.cpp#L5813-L5823).

This is the relevant wiki page: https://kodi.wiki/view/InfoLabels#ListItem (value ``ListItem.VideoAspect ``)

**Comment by HitcherUK** [comment]
> Is there any template file (SVG, XCF or something) or a script where those PNG graphics are generated from or will I have to "frankenstein" the existing ones in a raster graphics editor?

Not that I'm aware of.

**Comment by CastagnaIT** [comment]
i think should be "Lato" font, you can download/test from here:
https://fonts.google.com/specimen/Lato?preview.text=1.37:1%201.66:1%202.55:1&preview.text_type=custom
try compare by overlapping text with the existing images with an image editor

**Comment by palob** [comment]
Thanks, will try to recreate using the font or resort to frankensteining if the hinting will look too different.
``Lato`` isn't mentioned in the respective ``Fonts.xml``s. Is this an oversight or alright since it is only present in rasterised form?

**Comment by HitcherUK** [comment]
It was probably only used for the media flags and not any of the skin labels.

**Comment by palob** [comment]
flags graphics and code comment added.

**Comment by CastagnaIT** [comment]
`Fonts.xml` is for GUI text not for images

**Comment by CastagnaIT** [comment]
i have tested i can confirm that Lato font match,
but there is some little differences one is the pixelation of text edge (anti-aliasing) that should depends from the software used

immagine

I use only Photoshop then i can explain the settings for this use case,
from the "Character window" (screenshot) the settings are:
Font Lato - regular style
44pt
Horizontal scale 95%
Bold style - simulated - then enable the first "T" square button
Text edge (in screenshot at bottom-right "Preciso") to "Sharp"

**Review by CastagnaIT — CHANGES_REQUESTED** [review]
1.19:1 the 9 appears shifted down
suggest to apply an appropriate anti-aliasing or try follow my previous phothoshop example

**Comment by CastagnaIT** [comment]
at my eyes still not good
compared with others chars do not have the appropriate anti-aliasing, is 1 px upper and
now i see that is also wider than what should be the horizontal font scale

this a correct example: [1.19.psd.zip](https://github.com/xbmc/xbmc/files/7828167/1.19.psd.zip)

**Comment by palob** [comment]
I took the existing 6 and mirrored it. So maybe smoothing is the wrong way round.

I tried to recreat the label from scratch in Inkscape. I couldn't replicate the original Font weight, the rastered result was ever so slightly lighter. On the other hand hinting/anti-aliasing was considerably smoother but I wasn't inclined to update all existing flag labels to that new standard.

**Comment by CastagnaIT** [comment]
instead manually hacking image use the font i have attached before,
I have already provided you with everything you need
you have only to open the psd and edit the text layer which i have created

**Comment by CastagnaIT** [comment]
if you give me some time I will provide you with the PNG fixed

**Comment by palob** [comment]
The thing is I don't have Photoshop and I run an OS (Linux) where it can't run natively.

**Comment by palob** [comment]
So I'll gladly take your rendition or just use a pre-existing 9.

**Comment by CastagnaIT** [comment]
Now that i have checked better you have right horizontal scaling was ok, i have found that i had the wrong font spacing
so i have prepared the fixed PNG for you: [1.19.png.zip](https://github.com/xbmc/xbmc/files/7828938/1.19.png.zip)

I attach here updated things that can be re-used in the future:
Photoshop - Character window settings:
immagine
Lato font regular, 44pt, Chars spacing 0, Bold style -simulated-, Text edge to "Sharp" ("Preciso" in the screenshot)
Base PSD layered: [AspectRatioMaster.zip](https://github.com/xbmc/xbmc/files/7828926/AspectRatioMaster.zip)
Font: [LatoFont.zip](https://github.com/xbmc/xbmc/files/7828927/LatoFont.zip)

**Comment by palob** [comment]
Thanks for your files, I used the **9** from an existing icon however. Your ``1.19.png`` has the other glyphs slightly misplaced.
All other aspect ratio PNGs are designed so the ``.`` and ``:`` keep at constant coordinates.

**Review by CastagnaIT — APPROVED** [review]
ok for me, just squash commits

**Review by Hitcher — APPROVED** [review]
Looks good. Thanks for your contribution.

**Review by enen92 — APPROVED** [review]
Would be nice if we could move the string literals to some sort of enum class to make this easier to document. Something that can be done later though

**Comment by CastagnaIT** [comment]
i have add wiki to ListItem.VideoAspect https://kodi.wiki/view/InfoLabels
if there are other wiki places let me know, i will merge in the next few days

**Comment by palob** [comment]
Thank you, I'll let you know when I stumble upon any further instances in the wiki.

**Pull request merged**
