### PR TITLE
[MUSIC] Refresh GUI when song details updated via json for currently …

### PR DESCRIPTION
**Pull request by the-black-eagle**
…ly playing item

## Description
When calling AudioLibrary.SetSongDetails using json, changing a value (eg, userrating) will not be reflected in the GUI, despite the db and associated `CMusicInfoTag()` both containing the new value(s). GUI will continue to display the original value(s) until playback is stopped and re-started.

## Motivation and context
Originally raised in [this forum thread](https://forum.kodi.tv/showthread.php?tid=371920).  Updating song details such as userrating, mood, votes etc  via json-rpc should be reflected in the GUI immediately.

## How has this been tested?

I've tested this using the OP's skin and custom script (both available in the linked thread).  Observing the appropriate variables in a debugger showed that whilst they are updated correctly, the GUI does not re-read the tag info, therefore the info on screen does not update without stopping and restarting playback. 

I looked at how the videolibrary calls the GUI to re-read the tag info when it updates and followed a similar method.

## What is the effect on users?
Means that the GUI will update ListItems etc when updating song details dynamically using the json-rpc interface.  

Albums and artists need to be added for any items that could be updated on-the-fly (genres, themes, moods etc), in a later PR.
## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by DaveTBlake** [comment]
The forum thread seems to be a faulty link @the-black-eagle I'd like to remind myself if it was a conversation I knew about once. Meanwhile at the back of my mind there is some niggle about getting a GUI/JSON notification loop when trying to update GUI, I'll see if I can remember. Have you tested this using Chorus, Kore and other API using apps? Something more than fire a JSON command at Kodi and see the GUI change, but seeing what the apps do.

JSON in theory can be used to change data that has been read from music files, but of course any such changes will be temporary as rescanning of those files will wipe it, so I've never really liked `UpdateSong` etc. methods. Since in real life it seems only ratings and maybe art gets used no one complains "Kodi lost my edits", but the methods imply a JSON populated music db could be possible and that wouldn't work well.

Otherwise a patch bump to JSON API version goes with this change (as internal fix).

**Comment by the-black-eagle** [comment]
@DaveTBlake Fixed the link.

No, I haven't tested with Kore etc because I see no way to call `SetSongDetails` from the remote on my phone.   There isn't any way, as far as I can see, to change the user rating from the remote.  Perhaps that is an oversight, given that a lot of people are likely using remotes whilst running Kodi with the screen off. 
However, Kore doesn't display the user rating anywhere so why would it have an option to change it ? 

I _have_ tested using a python script running within Kodi, with a python program running outside Kodi and using cURL to call the API directly.  All 3 methods produced the required result.

Given that a remote or API call does trigger `UpdateSongDetails` then the GUI would refresh.  This should have no adverse consequences for a remote connected solely via the API(s). 

Thanks for the heads-up regarding the API version bump.

**Comment by DaveTBlake** [comment]
I really have forgotten more than I knew ;)
In principle, regardless of what happens historically for video, the JSON units should not be notifying the GUI of anything. It should be JSON -> core -> db changes etc. -> core notifies both GUI and API things have changed. Moving towards the dream of headless Kodi, rather than the original where the old XBox UI is was where most of the work happened. I also have a vague memory of having done a fix before to get the screen to actually change (but not in JSONRPC namespace). It would be updating ratings and playcounts, allowing for resorting etc. without doing a complete slow fetch into memory of an entire song list. But things in Kodi have a habit of not always staying fixed!

>  This should have no adverse consequences for a remote connected solely via the API(s).

At some time updating the GUI would then trigger other update notifications (possibly JSON), that may not be true now I don't know. A Python script firing a single update would not care, but an app monitoring Kodi playback as well as sending commands via JSON could get into a knot if there is still too much updating and notifying  triggered from the GUI.

I was sure that Chorus could set song rating.  Yes Kore support for music is limited, but the iOS remote guys might be interested in this, and Yatse is the other of course.

**Comment by the-black-eagle** [comment]
Superseded by https://github.com/xbmc/xbmc/pull/23647

**Pull request closed without merging**
