### PR TITLE
[PVR] Fix CPVRManager ctor to instanciate timers, recordings and chan…

### PR DESCRIPTION
**Pull request by ksooo**
…nelgroups. Otherwise crashes while pvr client not connected to backend may occur.

This change has been runtime tested on macOS, latest kodi master.

@FernetMenta you reported the problem and we discussed the cause and solution on Slack.

### CODE REVIEW

**Comment by Rechi** [comment]
test suite crashes on all platforms

**Comment by ksooo** [comment]
> test suite crashes on all platforms

definitely not related to this change

**Comment by ksooo** [comment]
jenkins build this please

**Comment by Rechi** [comment]
On Windows the test suite crash is definitely related to this change.
Just tested it local with latest master with and without this PR. With the PR applied it crashes, without it doesn't crash.

**Comment by ksooo** [comment]
> With the PR applied it crashes, without it doesn't crash.

Any insights where it crashes?

**Comment by ksooo** [comment]
Third commit fixes the crash in teardown of testsuite, which actually was caused by this PR. It actually revealed an old bug.

**Review by FernetMenta — APPROVED** [review]

**Pull request merged**
