### PR TITLE
[addons][fix] Generate proj. files on Release mode

### PR DESCRIPTION
**Pull request by VelocityRa**
## Description

This is a fix that binary add-on devs have had to do manually for a while now for the build system to work.
For some reason no-one has PR'ed it yet, so I did.

It's referred to in the build guide for game.libretro [here](https://github.com/kodi-game/game.libretro#developing-on-windows), and many other binary add-ons.
Credits: @Montellese who suggested it 2 years ago [here](https://forum.kodi.tv/showthread.php?tid=173361&pid=2097898#pid2097898).

## Motivation and Context

The binary add-on build system doesn't work without this.
It was an inconvencience having to manually do it every so often.

## How Has This Been Tested?

Tried to build a binary add-on from start to finish.

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by notspiff** [comment]
what exactly breaks if you do a debug build? i agree release is a better default, but i'm curious what breaks.

**Comment by VelocityRa** [comment]
Hm, I actually just hafl-assedly tested it without the fix and it seems to work... 
Maybe it was fixed at some point, or maybe I didn't sanitize my environment well enough before trying the 'broken' way. I'm reluctant to creating a new dev env just for this, but I'll do it if you deem it necessary.

Maybe someone else can chime in? I don't actually remember what's was (is?) broken without this, I just know that it was definitely needed for stuff to work up to at least a month ago.

**Comment by notspiff** [comment]
If it works it is all good. Change the default, devs just switch in project anyways..

**Comment by VelocityRa** [comment]
Jenkins failed because `kodi-test` segfaults on x64 Linux, not sure what's wrong there. Can't find any ticket open regarding that either.

**Comment by notspiff** [comment]
Just a buggy test.

**Pull request merged**
