### PR TITLE
[cleanup][iOS] remove outdated code and silence compiler warnings

### PR DESCRIPTION
**Pull request by Rechi**
## How Has This Been Tested?
compiled

## Types of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by Memphiz** [comment]
I will have to runtime Test this ... not sure when I get to it - depends on the mood of my son ;) ... will kick a Jenkins test build already though.

**Comment by Rechi** [comment]
@Memphiz did now some runtime test myself,
1. commit: nothing to test, just removed outdated code
2. commit: Kodi still is a full screen app
3. commit: still only landscape rotation
4. commit: don't know what to test

**Comment by Memphiz** [comment]
You tested  Tvout via hdmi or airplay mirroring to a tv? Cause that is where the touchscreen controller comes into play ...

**Comment by Rechi** [comment]
> You tested Tvout via hdmi or airplay mirroring to a tv?

No, I did only do the simple checks (full screen and rotation) mentioned in my previous post. Would have tested it, if I have hardware for it.
Is that what the last commit touches?

**Comment by Memphiz** [comment]
Yep - I have to fix multi monitor on iOS first due to the changes in that area ... 

sorry i only have read the commit message of the last commit „silence deprecate warnings“ and then combined with your „don‘t know what to test“ that there are only cosmetics in there ... that’s why I asked - not noticing that this was the commit I was after ;)

So for being able to finally test this very PR - we have to get mine in and this one needs to be rebased afterwards ...

**Review by Memphiz — APPROVED** [review]
All fine - have 2 issues left on the other pr though - will try to look into that today i hope

**Pull request merged**
