### PR TITLE
[guilib] fix first letter remains visible in keyboard dialog

### PR DESCRIPTION
**Pull request by xhaggi**
Follow-up of #7532 and should fix the reported issue

> "if you delete everything you type the first letter remains visible once you start typing it goes away."
> http://forum.kodi.tv/showthread.php?tid=231092&pid=2055348#pid2055348

@MilhouseVH could you please confirm if it works?

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Hi, I've tested this and it looks good - all problems resolved (all letters can be removed, cursor appears when the dialog is opened).

I also re-tested high CPU load on the Pi1 (just in case) and that's not a problem either.

Many thanks.

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Comment by xhaggi** [comment]
@MilhouseVH now we have a new/old issue that the hint text if specified is not being shown for the keyboard dialog. could someone please confirm if this is broken?

**Comment by MilhouseVH** [comment]
Not really sure what you mean by hint text - I tried editing the title of a movie, and the existing title appeared in the keyboard dialog, with the cursor, which is correct so I don't see a problem here, unless I'm misunderstanding you!

screenshot

**Comment by HitcherUK** [comment]
Hint text is what the skin can use when there's nothing input eg 'Type name here'.

**Pull request merged**
