### PR TITLE
[network] CNetWork::IsAvailable: Remove parameter 'wait', because the…

### PR DESCRIPTION
**Pull request by ksooo**
…re is no implementation behind.

### CODE REVIEW

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Comment by L-S-D** [comment]
I remember having to wait for the network to come up before starting Kodi on a TBS-Matrix IMX6 box as it would not have connected to mysql otherwise, but might be completely unrelated :-)

**Comment by ksooo** [comment]
Even worse, is/was not implemented at all - not just on Linux.

**Comment by L-S-D** [comment]
never trust the comments, the question is, as it makes sense to wait for the network, shouldn't this be implemented?

**Comment by ksooo** [comment]
@L-S-D PR yeah! PR welcome.

**Comment by Razzeee** [comment]
I may be offtopic here, so please just ignore me if this does not apply.

I know of various problems users have/had with the Trakt addon. Especially with wlan where it tries to connect, when there is no connection available (yet). The current "fix" is a setting, where you can set a number of seconds to wait before it tries to connect.

**Comment by ksooo** [comment]
@Razzeee as your addon must be able to deal with network connection loss at any time (not just at startup) I don't see how deferring startup of the addon actually would help. You need to write addon code dealing with this special situation anyway, right?

**Comment by Razzeee** [comment]
Yeah, but how to know if we're online? Ping google? Try to send and catch if we're not getting anything? Try each 10 sec? I don't think there is a smart way right now or I might have just ignored it until now.

**Comment by ksooo** [comment]
I'm not a Python expert, but as this is a very common problem I'm pretty sure that there exists some smart Python solution for this.

Kodi does not know which add-ons need network to startup properly and delaying start-up of each and every add-on start up until network is available is certainly not a good idea. Finally, this would solve just one very special case and you still would have to handle all other cases of network trouble in your add-on.

**Comment by ksooo** [comment]
Try/catch is imo a good approach here, btw.

**Comment by ksooo** [comment]
If people feel that it is not a good idea to remove this non functional code, just tell me. Then I will close this PR, have no problem with that. 

But I'm for sure the wrong person to implement this functionality for the different platforms we have. :-)

**Comment by stefansaraev** [comment]
my 2 cents on this.

having network available at the moment CNetwork::IsAvailable fires, does NOT guarantee that it is available 200 milliseconds later. 

yes, it's sad that kodi does not (can not) deal with network not available on startup (see how bad mysql is with no network..) 

on network error. an (service) addon, if network availability is critical, should schedule a retry in xx seconds. and make sure to rate-limit so do not retry forever. then throw an error, or whatever makes sense (yes, I know this may be over-simplified example, it depends on the use-case). so should be done in kodi core. sadly, I am not qualified for doing that in kodi core.

yes. dead/non functional code should go.

**Comment by ksooo** [comment]
Full ACK to what @stefansaraev said. It's the classical problem with non-lockable resources. File.Exists() falls into the same category. You cannot rely on how long any existence/availability information you got is valid. You can only try what you actually want to do with the resource and must implement proper error handling for the cases of suddenly changing existence/availability state.

**Comment by L-S-D** [comment]
indeed, and as stefansaraev said, it should be a kodi core event in the future, as this info might be used in various places

**Comment by ksooo** [comment]
> and as stefansaraev said, it should be a kodi core event in the future

 Did he say so? I don't think so. He said said that both Kodi core and addons have to do management of non-lockable system resources on their own. And I fully agree to this (as there is no better way of doing this "right").

 A kodi core event would not be of any help here.

**Comment by stefansaraev** [comment]
> He said that both Kodi core and addons have to do management of non-lockable system resources on their own

yes. that's what I meant. there is a language barrier. english is not my primmary language. sorry about that.

**Comment by L-S-D** [comment]
Well why reinvent the wheel several times and poll the same info in different places which even does cost resources? Network is something very global, nearly as essential as the file system or the renderers, but as I have not contributed a single line of code, I really should not have an opinion about it.

**Comment by ksooo** [comment]
@L-S-D Everybody is allowed to have an opinion, regardless how many lines of code he has contributed. We really like open discussions here. If you have the feeling that we don't get what you want to tell us, please try again. For me, it is not clear how the event you're suggesting should help to improve things, honestly. Maybe you sketch some code or so...

**Comment by L-S-D** [comment]
we don't know how to do it on all platforms, so basically it seems not to be a trivial task. Some have implemented crappy workarounds like delayed start to overcome some problems, which helps if the network is just late, but won't help if the connection drops. If there would be a general interface for such things (local/internet connectivity, connection loss, quality information just to name a few), not only kodi core could use them (mysql being my favourit example) but also addons could implement better error handlers (which do need to react differently on the same (core) network event).

**Comment by t4-ravenbird** [comment]
@stefansaraev "yes, it's sad that kodi does not (can not) deal with network not available on startup (see how bad mysql is with no network..)"

wait for network availability is a core function of http://kodi.wiki/view/Wake_on_lan and can solve the startup issue with MySQL.
even if you do not need the 'wol'-part you can enable this setting to make file-access and mysql-access  start properly since a test is made that (the correct interface) network is connected before proceeding.
(of course it still does not handle the fact that network could go away again at any moment but it fixes the startup sync)

**Comment by Paxxi** [comment]
+1 for removing this. Waiting for network availability before startup should be handled by the init system and as for events, that's a separate thing that should be done in a separate pr.

**Comment by ksooo** [comment]
@Paxxi yep. Will remove this.

@L-S-D How about you coming up with a PR for the network event(s) you're proposing.

**Pull request merged**
