### PR TITLE
PVR code cleanup

### PR DESCRIPTION
**Pull request by MaxKellermann**

### CODE REVIEW

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
Thanks, @MaxKellermann

**Comment by FernetMenta** [comment]
@ksooo we are not in a merge window and this is not a fix (at least it is labelled cleanup)

**Comment by ksooo** [comment]
Ooops, sorry.

**Comment by FernetMenta** [comment]
np. I just wanted to mention it because I think more members and contributors may have missed this info

**Comment by MartijnKaijser** [comment]
I think we should allow these minor "cleanups" like includes and dead code. If it was wrong it wouldn't even compile.

**Pull request merged**
