### PR TITLE
[addons] remove old stuff

### PR DESCRIPTION
**Pull request by tamland**
Doesn't appear to be in use anymore

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Looks good for me.

**Comment by tamland** [comment]
ping @notspiff

**Comment by akva2** [comment]
only thing i'm curious about is the removal of repo installation add-ons.

we need a plug to be able to do system-level installs on linux (i.e. install deb packages) for binary add-ons. the idea was that this python forwards to the relevant package manager. i tried to do packagekit on C++ side, but it gets very ugly, very soon (you have to pull in glib and its evils).

it stalled because the python apt bindings go tits up when run in the internal python (same code works just fine in the normal interpreter). i chose to use the existing plugin API to minimize the amount of code necessary (there's already an interface there to exchange data between c++ and python).

**Comment by tamland** [comment]
Ok, so it hasn't really been used for anything yet? Because it seems largely broken atm.

**Comment by akva2** [comment]
well yeah, that's 3 years of bitrot.

**Comment by tamland** [comment]
Pretty much what happens with anything that goes unused:) I plan to write to new installer (hence killing off some old cruft) so hopefully if binary addons ever happen something better can be written.

**Comment by AchimTuran** [comment]
@notspiff
The idea is great to use Python for system level installs. Would that be possible on all platforms?

@tamland
> I plan to write to new installer (hence killing off some old cruft) so hopefully if binary addons ever happen something better can be written.

I'm really looking forward to this, because it suits perfectly to my CI approach with Travis CI and Appveyor for AudioDSP add-ons.

**Comment by akva2** [comment]
In principle yes. There is nothing linux specific in the code, but the premise were that the rest would stick to zips. It is basically a python plugin source with predefined parameters, e.g.  plugin://repo.kodi.binaddons/install?package.visualization.plastic.fantastic

-------- Opprinnelig melding --------
Fra: AchimTuran <notifications@github.com>
Dato: 24.02.2016 17:05 (GMT+01:00)
Til: xbmc/xbmc <xbmc@noreply.github.com>
Ko: Arne Morten Kvarving <Arne.Morten.Kvarving@sintef.no>
Emne: Re: [xbmc] [addons] remove old stuff (#9185)


@notspiff<https://github.com/notspiff>
The idea is great to use Python for system level installs. Would that be possible on all platforms?

@tamland<https://github.com/tamland>

I plan to write to new installer (hence killing off some old cruft) so hopefully if binary addons ever happen something better can be written.

I'm really looking forward to this, because it suits perfectly to my CI approach with Travis CI and Appveyor for AudioDSP add-ons.

**Comment by tamland** [comment]
jenkins build this please

**Pull request merged**
