### PR TITLE
X11: remove vdpau and glx

### PR DESCRIPTION
**Pull request by lrusak**
It's time.

nvidia has been a constant thorn in the side of linux for a while now. vdpau is dead. glx is dead. let's get rid of it for V19.

torvalds + linux

### CODE REVIEW

**Comment by fritsch** [comment]
There is one thing I wanted to have solved "upstream" before we do that to not punish AMD users that need VDPAU still for MPEG2, which is here: https://bugs.freedesktop.org/show_bug.cgi?id=110257

Other than that - one cannot stop future. It's a pitty and nvidia was long warned for that and did not react.

**Comment by FernetMenta** [comment]
> nvidia was long warned for that

funny :)

btw: vdpau is not dead. NVidia has just bumped it to 1.2

**Comment by pkerling** [comment]
> btw: vdpau is not dead. NVidia has just bumped it to 1.2

They seem to have resurrected it recently for exactly two commits (with the last change before that being in 2015!), adding HEVC444 support (= useless to us) ... It is still dead. Or maybe undead now? :-) Anyway, no EGL (= no Wayland, no Gbm), no VP8, no VP9, and there is no indication that that will change.

> It's time.

I'm not sure to be honest. I do agree that it will have to go at some point, but do you think it is a maintenance burden *at the present moment*? If we remove functionality, I feel that we should have a good technical reason.

**Comment by lrusak** [comment]
> > It's time.
> 
> I'm not sure to be honest. I do agree that it will have to go at some point, but do you think it is a maintenance burden _at the present moment_? If we remove functionality, I feel that we should have a good technical reason.

The technical reason is that keeping this hinders development on wayland and gbm as those platforms are not supported by vdpau. Dropping this ancient method will allow future development by forcing people to move on. By continuing to support this "just because we can" limits our future design, architecture, and development as a whole. This may seem like a stretch but I have been working in this area for a while now and without ripping the bandaid off nothing will ever change. Also by using git the history will always be there if by some miracle nvidia decides to drop the glx requirement from vdpau and moves it to egl where wayland and gbm may be able to use it (it would still require nvidia to provide gbm support in their binary blob driver). 💀

**Comment by arnova** [comment]
@lrusak : Any idea how well Nouveau + VAAPI work nowadays? If that generally works fine I see no problem in dropping VDPAU.

**Comment by lrusak** [comment]
> @lrusak : Any idea how well Nouveau + VAAPI work nowadays? If that generally works fine I see no problem in dropping VDPAU.

It works but due to no reclocking support (yet) in nouveau playback is generally stuttery.
see, https://nouveau.freedesktop.org/wiki/VideoAcceleration/

**Comment by Albinoman887** [comment]
so does this mean nvidia support will be gone for v19? that sucks. i bought a nvidiia card specifically because a xbmc dev told me to as it was the most compatibile option for linux at the time

**Comment by pkerling** [comment]
> so does this mean nvidia support will be gone for v19? that sucks. i bought a nvidiia card specifically because a xbmc dev told me to as it was the most compatibile option for linux at the time

1. This is obviously not merged yet
1. This does not mean that you will be unable to use Kodi with a NVidia GPU, it just means that you will be limited to software decoding on Linux (whether this is a problem depends a lot on your hw and use case)
1. Not sure when "at the time" is, but times do change (for better or worse)

**Comment by fritsch** [comment]
Do you remember the year? Was it before or after the German wall was
removed?

Matt Filetto <notifications@github.com> schrieb am Di., 28. Mai 2019, 11:19:

**Comment by Albinoman887** [comment]
Like 2012

**Comment by fritsch** [comment]
7 years ago ... no further comment ...

**Comment by Albinoman887** [comment]
So is AMD the best option from here on out

**Comment by lrusak** [comment]
> So is AMD the best option from here on out

or Intel if you only need an integrated GPU (dual core celeron gemini lake is just fine like Intel(R) Celeron(R) J4005 CPU @ 2.00GHz)

**Comment by Albinoman887** [comment]
I'm running an old ass e6600 core 2 duo so I guess I'll go the amd route
shortly . The main reason I got the Nvidia gpu was for the extra audio
features . At the time activeAE was still in early development and you
needed nvidia like dts true hd and lpcm . Is that still the case ? If so I
guess I'm stuck on 18 once this is merged cuz I'm an audiophile

**Comment by lrusak** [comment]
> I'm running an old ass e6600 core 2 duo so I guess I'll go the amd route shortly . The main reason I got the Nvidia gpu was for the extra audio features . At the time activeAE was still in early development and you needed nvidia like dts true hd and lpcm . Is that still the case ? If so I guess I'm stuck on 18 once this is merged cuz I'm an audiophile

HD audio works on AMD and Intel just fine. There is nothing special about nvidia there.

Github isn't for user support. Please take further questions to the forum.

**Comment by wrxtasy** [comment]
> vdpau is not dead (yet) 

LOL:

https://www.youtube.com/watch?v=jYcPBE5PXhs

**Comment by oldium** [comment]
> There is one thing I wanted to have solved "upstream" before we do that to not punish AMD users that need VDPAU still for MPEG2, which is here: https://bugs.freedesktop.org/show_bug.cgi?id=110257

Should be fixed already 😊

**Comment by mrcmunir** [comment]
This is to pull down the work of compatibility and preservation HW that his kill the original philosophy of xmbc be a good player on any type of device will kill more than millions of HW that is not updated anymore
And not being a bitch of google is not the solution
What is eliminated is finally political and not by a technical decision.
remove it going to love it ChromeOS / Android users but several users under linux are lost with you political going to it and kodi R.i.P With this.
Decisions like this hurt open source programmed obsolescence and the same as canonical policies recently and you will be accomplice of this and the community will not forget

**Comment by oldium** [comment]
@mrcmunir Do you realize that old version will still exist for old HW? New HW just should use a common modern API, nothing more. This looks like a reasonable request to HW vendors.

**Comment by mrcmunir** [comment]
@oldium It will be my last message I do not want to bother or anything like that, 
I leave my point of view and surely there will be people who think the same,  other not same think well.
I'm 32 years old at my back (when was there unstable and you had to spend more days compiling and praying that everything would work there, there were no such absurd policies of this kind) 
Remove because it does not like NVIDIA policies and Like Google going it.
I'm can use kodi 19 yes on some system but it does not like the move for Video plack future (better friendly with ChromeOs / Android but abandon several users Linux with the equal quality severals GPUS decoding with diferent API decode)
A philosophy to follow goodly Retroarch / lakka / wine devs (always add flexible support but not delete without any technical motivation) 
All software that supports google and Canonical policies will not be in any of my PCs with any versions.
The policies are better when Canonical and Google Not going force standards Linux so that's fucking shit (sorry).
Good luck to all anyway.

**Comment by fritsch** [comment]
Feel free to take over nvidia / vdpau maintenance. I only see big words and demands for your own philosopy. Step up for your values and take source code responsability.

**Comment by pasikarkkainen** [comment]
FYI: Nvidia proprietary Linux driver version 440.31 adds vdpau support for accelerated VP9 decoding:

https://www.nvidia.com/download/driverResults.aspx/153226/en-us

"Added VP9 decode support to the NVIDIA VDPAU driver. See the VDPAU Support appendix in the README for supported VP9 decoder profiles."

**Comment by lrusak** [comment]
> FYI: Nvidia proprietary Linux driver version 440.31 adds vdpau support for accelerated VP9 decoding:
> 
> https://www.nvidia.com/download/driverResults.aspx/153226/en-us
> 
> "Added VP9 decode support to the NVIDIA VDPAU driver. See the VDPAU Support appendix in the README for supported VP9 decoder profiles."

VP9 vdpau support was just merged into FFmpeg master a few days ago. There is no stable release with it yet. Even when there is Kodi will have to bump to use that ffmpeg version (or be built against it). https://git.ffmpeg.org/gitweb/ffmpeg.git/commit/1054752c563cbe978f16010ed57dfa23a41ee490

There is no change regarding the use of GLX though which is required to use vdpau.

**Comment by phunkyfish** [comment]
@lrusak do you want to progress this, close it or backburner?

**Comment by lrusak** [comment]
It's not my realm. If someone wants to continue to maintain it then I'm fine with that.

**Pull request closed without merging**
