### PR TITLE
[guilib] Enable proper disabled appearance for Slider / Settings Slider controls + Estuary/Estouchy update

### LINKED ISSUE #17992: [settings] New Settings - Slider control is not disabled by dependency and spinner control does not show format label
### Describe the bug
Here is a clear and concise description of what the problem is:

- Slider control is not disabled by dependency but shows format label
- Spinner control does not show format label but is disabled by dependency

Example setting for slider control:
```
        <setting id="timeshiftEnableLimit" type="boolean" label="30022" help="30622">
          <level>2</level>
          <default>true</default>
          <control type="toggle" />
        </setting>
        <setting id="timeshiftOnDiskLength" type="number" parent="timeshiftEnableLimit" label="30023" help="30623">
          <level>0</level>
          <default>1</default>
          <constraints>
            <minimum>0.25</minimum>
            <step>0.25</step>
            <maximum>24</maximum>
          </constraints>
          <dependencies>
            <dependency type="enable" setting="timeshiftEnableLimit">true</dependency>
          </dependencies>
          <control type="slider" format="number">
            <formatlabel>30024</formatlabel>
          </control>
        </setting>
```

```
        <setting id="timeshiftEnableLimit" type="boolean" label="30022" help="30622">
          <level>2</level>
          <default>true</default>
          <control type="toggle" />
        </setting>
        <setting id="timeshiftOnDiskLength" type="number" parent="timeshiftEnableLimit" label="30023" help="30623">
          <level>0</level>
          <default>1</default>
          <constraints>
            <minimum>0.25</minimum>
            <step>0.25</step>
            <maximum>24</maximum>
          </constraints>
          <dependencies>
            <dependency type="enable" setting="timeshiftEnableLimit">true</dependency>
          </dependencies>
          <control type="spinner" format="number">
            <formatlabel>30024</formatlabel>
          </control>
        </setting>
```

```
#. format-label: Timeshift - timeshiftOnDiskLength
msgctxt "#30024"
msgid "{0:.2f} hours"
msgstr ""
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

- Slider control is not disabled by dependency but shows format label
- Spinner control does not show format label but is disabled by dependency

## Actual Behavior

Slider control is not disabled by dependency
Spinner control does not show format label.

### To Reproduce

1. Use the provided code samples in any addon
2. Open chosen addons settings to see.

### Debuglog

The debuglog can be found here:

Will upload later today.

### Screenshots 
Here are some links or screenshots to help explain the problem:

Screenshot 2020-06-03 at 13 47 07

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CrystalP**
## Description

Added the ability for the slider and sliderex controls to render properly in a disabled state

* Defined two new control textures, used when the control is in the disabled state.
  * `texturesliderbardisabled` for the "background" 
  * `textureslidernibdisabled` for the "nib"
  For example, modification of Estuary:
```
<texturesliderbardisabled colordiffuse="disabled">buttons/slider-back.png</texturesliderbardisabled>
<textureslidernibdisabled colordiffuse="disabled">buttons/slider-nib.png</textureslidernibdisabled>
```
* The control falls back to before-PR behavior until a skin is updated with the new textures, so no immediate action needed from the skinners. The control reverts to using `textureslidebar` and `textureslidernib` even in disabled state.

* Existing code patterns were followed in `Process` / `ProcessSelector` / `Render` code of the control, and the plumbing to get the texture information extracted and passed around.
  - I'm unsure about dirty regions handling with multiple textures that appear at the same place, guidance appreciated if needed.

- Modified `xbmc/interfaces/legacy/Control.cpp` but I don't really know what it's for and how it is invoked (seems to have to do with legacy Addon / Python stuff?). Added the two new texture as optional last parameters to preserve compatibility, with same fallback on the previous textures.

* I will add the new tags to the Wiki https://kodi.wiki/view/Skinning_Manual#Slider_Control

## Motivation and context

See screenshots.
Noticed in previous PR #22756 that a slider control doesn't show properly in disabled state: a part still seems to be enabled and it looks weird.
Same thing was reported in issue #17992
It's possible ppl held back on using the slider because of that issue and it may be used more after this PR.

Explored alternatives:
* It was suggested to try and workaround this with a diffusecolor, but all it does is make the selector look disabled all the time, it's not possible to add conditions with control state in a texture definition to my knowledge. Even if there is, a skin change would still be needed.

* While adding a "disabled colordiffuse" to the texture would be enough for Estuary / Estouchy, assuming that it's also enough for all other skins seemed too much. Hence the PR's approach that adds a couple textures for complete freedom of the skinner.

## How has this been tested?

Windows, the HDR group in Settings / System / Display has a case of disabled slider - see the screenshots.
Also tested with "InputStream FFmpeg Direct" addon.
Disabling/enabling, selecting the control to change value work.
Tried the different dirty regions algorithms with visualization, no difference before/after.

I don't know how the interface defined in xbmc/interfaces/legacy/Control.cpp gets invoked so that's untested.

## What is the effect on users?

Nicer appearance / more consistent skinning of the slider

## Screenshots (if appropriate):
Before, the control looks only partially disabled:
image

After, the entire control has a proper disabled appearance:
image

And the screenshot of issue #17992 looks correct:
image

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CrystalP** [comment]
@phunkyfish @ronie @CastagnaIT @jjd-uk @thexai you commented about this problem in issue #17992 and/or PR #22756

**Review by phunkyfish — APPROVED** [review]
I've runtime tested this and it works for me similar to your screenshots. The C++ looks sane. I'm afraid I can't comment on Control.cpp, I'm far from a GUILib expert.

Will leave the skin changes for others.

**Comment by CrystalP** [comment]
I tried all dirty region algorithms to alleviate my concerns, the change made no difference in the repainting.

Any objections, should I push the button?

**Comment by CastagnaIT** [comment]
under code prospective seem good
but please update doxy here
https://github.com/xbmc/xbmc/blob/master/xbmc/guilib/GUISliderControl.dox

**Comment by CrystalP** [comment]
Done, is the Wiki page generated from the dox files?

**Comment by CrystalP** [comment]
@CastagnaIT OK with the documentation and merge? (I'll wait for Jenkins to finish re-building)

**Comment by CastagnaIT** [comment]
sorry forgot to answer yes lgtm

**Pull request merged**
