### PR TITLE
Implement filecache retry logic

### PR DESCRIPTION
**Pull request by arnova**
This PR implements retry logic for our filecache. Especially poor (wifi) connections benefit from this. Previously we would simply (silently) abort in case a single Read() failed.

With this we simply retry a read, as long as we have data in our cache. This PR also adjusts Curl's fillbuffer retry logic to properly support Read() retries. This also disables CFileCurl's internal retry logic which could cause long waits (hangs) on exit when .e.g a connection timeout occurred.

### CODE REVIEW

**Comment by arnova** [comment]
jenkins build this please

**Comment by arnova** [comment]
@Paxxi : Please review/comment

**Comment by arnova** [comment]
ping @paxxi. Anyone else against this?

**Comment by fritsch** [comment]
I don't understand all those FileCache hacks and there are many in that
code. We need to take great care that nothing will hang undefined for 5
seconds - that would be a really bad user experience and if this happens on
every end of a movie or something then we have a big problem.

So @paxxi please review.

2016-01-09 9:38 GMT+01:00 arnova <notifications@github.com>:

> ping @paxxi <https://github.com/paxxi>. Anyone else against this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/xbmc/pull/8723#issuecomment-170210180>.
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by arnova** [comment]
That's why we need to
      properly test this during alpha, so we can iron out any issues.
      The way it is now is really bad for poor (wifi) connections.
      Endusers don't understand why their video aborts while there's
      still plenty of data in the filecache....
    
    On 09/01/16 09:45, Peter Frühberger
      wrote:
    
    I don't understand all those FileCache hacks and there
      are many in that
      code. We need to take great care that nothing will hang undefined
      for 5
      seconds - that would be a really bad user experience and if this
      happens on
      every end of a movie or something then we have a big problem.
      
      So @paxxi please review.
      
      2016-01-09 9:38 GMT+01:00 arnova <notifications@github.com>:
      
      > ping @paxxi <https://github.com/paxxi>. Anyone else
      against this?
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
      <https://github.com/xbmc/xbmc/pull/8723#issuecomment-170210180>.
      >
      
      
      
      -- 
      Key-ID: 0x1A995A9B
      keyserver: pgp.mit.edu
      ==============================================================
      Fingerprint: 4606 DA19 EC2E 9A0B 0157 C81B DA07 CF63 1A99 5A9B
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Paxxi** [comment]
Sorry about the radio silence, too many notifications :)
No objections to merging as is, could use an int64_t instead of int to be more consistent with other file access methods but I don't think we're going to need a cache large enough to warrant it.

**Comment by arnova** [comment]
@Paxxi : No problem and thanks for the review. I think I'll stick to int since that's what the surrounding functions in that area use as well. I'll squash it and I think it's ready to go in then.

**Comment by arnova** [comment]
@paxxi: Mind reviewing it again. I simplified the logic somewhat. Thanks!

jenkins build this please

**Comment by arnova** [comment]
@MilhouseVH : Could you include this in your builds so it gets some proper testing before it's merged into mainline?

**Comment by MilhouseVH** [comment]
Will do, thanks.

**Comment by arnova** [comment]
@MilhouseVH : No, thank you ;-)

**Comment by MilhouseVH** [comment]
This PR is causing a range request failure when attempting to play content from Amazon Prime - see this debug log: http://pastebin.com/raw/EaW1W3np

With this PR, the request to Amazon will fail with:
```
16:16:46 39677.078125 T:1489114016   DEBUG: Curl::Debug - TEXT: HTTP server doesn't seem to support byte ranges. Cannot resume.
16:16:46 39677.078125 T:1489114016   DEBUG: Curl::Debug - TEXT: Closing connection 0
16:16:46 39677.078125 T:1489114016   ERROR: CCurlFile::FillBuffer - Failed: Requested range was not delivered by the server(33)
16:16:46 39677.078125 T:1489114016   ERROR: AddOnLog: Input Stream: Could not open / parse mpdURL (http://s3.lvlt.dash.us.aiv-cdn.net/d/1$AOAGZA014O5RE,42D4116A/videoquality$1080p/prod/4be9/73d6/2189/47ce-952c-ce46eddf5830/442612cc-c80f-4b78-9953-5f0fcd2b268f_corrected.mpd)
```

To reproduce you'll need:
* latest Kodi master
* this PR
* inputstream.mpd addon with libwidevinecmd.so (this is @fritsch's build: https://dl.dropboxusercontent.com/u/55728161/inputstream.mpd-1.0.0.zip)
* [Amazon Prime Instant add-on](https://github.com/phil65/plugin.video.prime_instant), or a [derivative](https://github.com/phil65/plugin.video.prime_instant)
* and of course an Amazon Prime account (month long test account should work)

If you live in the UK you may also need [Getflix](https://www.getflix.com.au) to access the US as the UK isn't working well at all (probably unrelated to this PR, likely an add-on issue).

I'm in the UK, but get the above curl error when accessing US or DE content (with or without Getflix) while PR8723 is included, Without PR8723, content from the US via Getflix will play normally.

**Comment by mapfau** [comment]
I came over this issue today also with inputstream with @MilhouseVH openelec:
- uncompressed filesize about 5.2mb, gzipped 832k
- after reading the file once a retry takes place at file position 5.4mb curl range value.
this is first behind the extracted filesize (???) and secondly the server does not support byte ranges.

My guess was that it is curl, but the user has installed 7.47.1 (the newest version), but good to know that it seems to be something inside kodi - I'm not keen on fixing curl code.

**Comment by arnova** [comment]
Strange I've reviewed the code once again and I can't seem to find which change is responsible for this. @MilhouseVH : You're 100% sure it's this PR causing it and not the e.g. libcurl update?

**Comment by MilhouseVH** [comment]
@arnova: Absolutely 100% sure, yes.

**Comment by MilhouseVH** [comment]
To be clear, I stopped adding this PR and the problem went away - Amazon Prime now worked.

In addition, I built master for Ubuntu x86_64 without any other changes and Amazon Prime worked. I then rebuilt with this PR and could then reproduce the range request failure.

**Comment by arnova** [comment]
@MilhouseVH : Thanks for the info. I think I understand now what's going on. I'll try to fix it today or else this weekend.

**Comment by arnova** [comment]
@MilhouseVH : Mind re-testing with the last commit from the PR applied as well? Hopefully is fixes your issue (can't test it myself unfortunately)

**Comment by MilhouseVH** [comment]
Hi @arnova - unfortunately your latest fix doesn't seem to have helped.

Here's two logs from Ubuntu x86_64 (latest master) playing the "Pilot" episode of "Lucifer" from the UK Amazon:

[With PR8723](http://sprunge.us/RTSb) - this doesn't work, no video plays. Seems to be a different error now though not sure what exactly
[Without PR8723](http://sprunge.us/dHcU) - this works, video plays normally

Hopefully you can spot where it goes wrong.

**Comment by arnova** [comment]
@MilhouseVH : Thanks for your patience. The issue still puzzles me and unfortunately I have no means to reproduce it. I added another change, mind giving it another try?

**Comment by fritsch** [comment]
@arnova I tried very hard to read through the class the last days and I think we should start from scratch :-) there are so many organically grown specialities that even debugging and fixing for specialists like you are a real issue.

**Comment by MilhouseVH** [comment]
> I added another change, mind giving it another try?

Should be able to test this tomrorow.

**Comment by arnova** [comment]
@fritsch : Ideally, perhaps yes but it has served us well all this time. And starting all over means reinventing all the special-cases, so this will probably never happen (and who "volunteers" to do this anyway?). Mote that to others CCurlFile *may* seem unreadable, but seriously: it's not THAT bad. There are areas that seem much worse than this, take e.g. everything concerning our Python implementation, it seems like a god damn nightmare to me.

@MilhouseVH : Thanks, I'll wait for your feedback.

**Comment by mapfau** [comment]
nice discussion! I agree to @fritsch because it seems that the code has growed over the time without respecting that ccurl also improved. Hopefully the underlying system (here curl implementation) supports most of the features needed by kodi.

Sure I can be wrong, but I wold take some time in the short next future to get an overview over curl features and try a cleanup.

**Comment by MilhouseVH** [comment]
Hi @arnova - sorry for the delay testing this. Unfortunately it still results in no playback. This is testing the same "Pilot" episode of Lucifer as before, but with this latest PR: http://sprunge.us/bZBJ

**Comment by arnova** [comment]
@MilhouseVH : Strange, it seems the initial problem has been fixed (look for the "Curl.... (re)try" line in the old logs), so it seems there's an additional problem. You sure you didn't rebase and/or added other stuff in the meantime that could have caused this?

**Comment by MilhouseVH** [comment]
No, it was just master + this PR.

**Comment by arnova** [comment]
Ok, then I have to some more thinking about this and figure out a way to reproduce this (unfortunately I don't have access to Amazon).

**Comment by arnova** [comment]
@MilhouseVH : Mind giving it another try? Please provide a debug log anyway, since I added some debug code to pinpoint the exact location where it fails. Note that I tried a free account for Amazon but unfortunately that doesn't work in the Netherlands due to regional restrictions :/

**Comment by mapfau** [comment]
@arnova For testing you could:

- curl the mpd file from the log
- remove the ContentProtection Header in all the AdaptationSets (its xml)
- set up an local web server (IIS / Apache)
- make a strm file with http://localhost//test.mpd

**Comment by arnova** [comment]
@mapfau : Tried that but doesn't work: http://pastebin.com/kH0CecK7

**Comment by mapfau** [comment]
16:53:18 T:140022397003776   DEBUG: Loading settings for http://rocky/test-format.mpd
-> means that URL http://rocky must be registered in the URL settings.
(addon::settings::user addons::VideoPlayer InputStream::inputstream.mpd

-> It seems that the inputstream.mpd is not activated, there is no single log line for it
pls. try activating it in the settings mentiond in the point above.

**Comment by MilhouseVH** [comment]
I would suggest trying a free [Getflix](https://www.getflix.com.au) account and see if that helps you access Amazon UK/US/DE from where you are.

Kodi master is a bit of a mess right now, playing havoc with addons etc., but with the updated version of this PR, Amazon Prime is actually playing:

http://sprunge.us/jLCi

The log is from master (5877cee682648d48db4c23fcbf7ad20cc3ad3095) with #9443, #9458 and #8723 on top.

**Comment by arnova** [comment]
@MilhouseVH : Thanks for the info. Nice to see that it finally works. I've squashed + cleaned up the code a bit. Mind including this in your builds again so it gets some more testing?

ps. Yes current master is rather broken unfortunately. I'm having major issues with it on my dev-machine: installing addons from unknown sources is broken, corrupted skin/graphics, no video playback (on my Intel HD), etc. Since this PR seems fixed now (hopefully), I can start working on looking into the other issues...

**Comment by fritsch** [comment]
Mind posting a debuglog? Especially for intel HD I currently have some 10 thousand users running master builds daily on an optimized intel flavor of OpenELEC -> no complaints at all. Most likely you are missing a new enough libva / mesa egl dependencies. But debuglog will tell us.

**Comment by arnova** [comment]
@fritsch: Log: https://www.dropbox.com/s/7l72nozc7e1zzyy/kodi.log?dl=0 . And this is what my skin looks like: https://www.dropbox.com/s/f6rri0mosxbyn0m/screenshot000.png?dl=0

@FernetMenta : Btw. I still believe that no longer having any codec info while playing video is a major loss with issues like this.

**Comment by fritsch** [comment]
Run git clean -xfd please and re bootstrap and reconfigure. This is some stalled change of TexturePacker.

Looking at the logfile now.

**Comment by fritsch** [comment]
For the VAAPI issue: 12:05:54 T:140297944962816   ERROR: failed to import VA buffer NV12 into EGL image: 12292

your mesa is much too old to run kodi. At least mesa 11.0 is required for VAAPI to work, alternatively wsnipex mesa ppa.

Your 12:05:32 T:140299012286464  NOTICE: Running on Ubuntu 14.04 LTS, kernel: Linux x86 64-bit version 3.13.0-24-generic

is not supported anymore by canonical. The deliver lts-backport packages for that OS, in your case you need the -mesa-lts-wily mesa packages

**Comment by MilhouseVH** [comment]
> Mind including this in your builds again so it gets some more testing?

Sure, but if it remains unmerged for more than a few weeks I'll drop it again, as I've learned that keeping these infrastructure-related changes hanging around in my builds does me no good...

**Comment by FernetMenta** [comment]
@arnova you can get the desired info with a simple json-rpc query. Set this bookmark in your browser and you'll get the info without doing harm to real-time processing.

```
http://localhost:8080/jsonrpc?request={"jsonrpc": "2.0", "method": "Player.GetProperties","params":{"playerid":1,"properties":["currentvideostream"]}, "id": 1}
```

**Comment by mapfau** [comment]
just a question: has anything of this development found its way to master?
Note: I haven't pulled this PR!!

Today I have this (and never saw this before):

15:39:17 T:160   DEBUG: Curl::Debug - SSL_DATA_OUT: V
15:39:17 T:160   DEBUG: Curl::Debug - HEADER_OUT: POST /WidevineLicenser/WidevineLicenser HTTP/1.1
15:39:17 T:160   DEBUG: Curl::Debug - HEADER_OUT: Host: wvguard.sky.de
**15:39:17 T:160   DEBUG: Curl::Debug - HEADER_OUT: Content-Range: bytes 0-/-1**
15:39:17 T:160   DEBUG: Curl::Debug - HEADER_OUT: User-Agent: Kodi/17.0-ALPHA1 (Windows NT 10.0; WOW64) App_Bitness/32 Version/17.0-ALPHA1-Git:Unknown
15:39:17 T:160   DEBUG: Curl::Debug - HEADER_OUT: Accept: */*
15:39:17 T:160   DEBUG: Curl::Debug - HEADER_OUT: Accept-Charset: UTF-8,*;q=0.8
15:39:17 T:160   DEBUG: Curl::Debug - HEADER_OUT: Content-Length: 2
15:39:17 T:160   DEBUG: Curl::Debug - HEADER_OUT: Content-Type: application/x-www-form-urlencoded
15:39:17 T:160   DEBUG: Curl::Debug - TEXT: upload completely sent off: 2 out of 2 bytes
15:39:17 T:160   DEBUG: Curl::Debug - TEXT: SSLv2, Unknown (23):

where dose the content-range come from? I didn't set it. I stoill have the feeling that there is something uninitialized.

**Comment by arnova** [comment]
@MilhouseVH : Sure, but in principle if no other problems popup this should be merged in a few weeks. Please ping me in case you want to drop it.

@fritsch : I'm running (XFCE) Mint 17.2, which is based on Ubuntu 14.04-LTS. I though we'd always support the last LTS version of Ubuntu? When did we drop support for it?

@FernetMenta : Thanks for the info.

@mapfau : Nothing has been merged to master yet concerning this or anything else concerning Curl. I'll have a look at your issue.

**Comment by fritsch** [comment]
@arnova Ubuntu 16.04 LTS is released in 1 months and kodi v17 most likely after it.Kodi v16 supports 14.04 just fine - but sucks VAAPI feature wise.

**Comment by mapfau** [comment]
I'll, because its reproducable on my machine

**Comment by arnova** [comment]
@mapfau : Looking over the code, I suspect a problem in libcurl itself. I don't see anything (obvious) in our code that could cause this.

**Comment by mapfau** [comment]
@arnova sorry - I passed the headers too late, it was my fault :-(

**Comment by arnova** [comment]
@mapfau : No problem :)

**Comment by arnova** [comment]
jenkins build this please

**Comment by arnova** [comment]
@MilhouseVH : No reports of problems with this? I just added an IO control option to properly handle enabling/disabling retrying inside file implementations when cache is used. The changes are pretty simple/straightforward. Please review, but I don't think they require any additional testing.

**Comment by MilhouseVH** [comment]
No further reports of any problems after your fix for Amazon. I've tested your latest changes and Amazon is still working.

**Comment by arnova** [comment]
jenkins build this please

**Comment by RubenTeixeira** [comment]
I believe this PR broke video queue on android. Behaviour is as follows:
Stream starts, video queue gets to 100% and forward buffer starts filling up, immediatly after, the video queue starts to drop until near 0%, down to a point when it starts filling up again. Then this behaviour will repeat (down,up,down,up).
I'm currently overwelmed with work so i cant post logs right now, but if no one else does in the meanwhile, tomorrow or the day after i will provide some.

**Comment by mazeyx** [comment]
not sure if it was this or one of the other commits in the last nightly kodi-20160412-6167026-master-armeabi-v7a.apk on android tv when starting a local file the audio kicks in and the screen stays black for around 5 seconds then it shows up video. reverting to kodi-20160410-25dc4bf-master-armeabi-v7a.apk fixes it.

**Comment by fritsch** [comment]
trac.kodi.tv all debuglog are mandatory

**Comment by mazeyx** [comment]
the issue i described is now resolved with the latest nightly.

**Comment by RubenTeixeira** [comment]
Same! Fixed with latest build.

**Comment by arnova** [comment]
@RubenTeixeira : Great that it's fixed but please next time don't start blaming (random) commits/PRs unless fairly sure it's the cause. And if not, use the forum instead.

**Comment by RubenTeixeira** [comment]
@arnova  i'm sorry, but from the previous build to the troubling one, the only commit related to buffering was this one.

**Pull request merged**
