### PR TITLE
[PVR] Recordings window context menu fixes

### PR DESCRIPTION
**Pull request by ksooo**
4 fixes:

1) 'Mark as watched': must not set play count to one, unconditionally, but increment it.
2) Fix duplicate context menu entries (regression introduced by non-pvr krypton context menu rework) 
3) 'Resume from ...': Fix time format to be aligned with format used for non-pvr videos
4) 'Play / Play from beginning': Fix wording to be aligned with strings used for non-pvr videos

before:
screenshot005

after:
screenshot007

@Jalle19 objections?

### CODE REVIEW

**Comment by ksooo** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
I can't image the that mark as watched button should be there if playcount != 0  (could it then would be mark as watched again). As such you always set it to one if it's watched

**Comment by ksooo** [comment]
> I can't image the that mark as watched button should be there if playcount != 0 (could it then would be mark as watched again). As such you always set it to one if it's watched

'Mark as watched' will actually not be visible if playcount > 0. Independently playcount will be increased on every 'successful' completed watch of a recording (automatically, not via context menu). This is exactly how it is implemented for non-pvr videos. I checked that.

**Comment by Jalle19** [comment]
Don't library items show Mark as unwatched if playcount > 0?

**Comment by ksooo** [comment]
So do we for pvr recordings.

**Comment by ksooo** [comment]
It did you actually mean Mark as watched?

**Comment by ksooo** [comment]
BTW, I did not change the visibility logic in this PR. So, if there is something buggy with visibility, it is not introduced by/related to this PR.

**Comment by ksooo** [comment]
@Jalle19 thus us the logic. 

<code>
      if (recording->m_playCount > 0)
        buttons.Add(CONTEXT_BUTTON_MARK_UNWATCHED, 16104); /* Mark as unwatched */
      else
        buttons.Add(CONTEXT_BUTTON_MARK_WATCHED, 16103);   /* Mark as watched */
</ code>

I don't see a problem here.

**Comment by ksooo** [comment]
@Jalle19 good to go? I would like to have this in beta 1.

**Comment by Jalle19** [comment]
Shove it in

**Pull request merged**
