### PR TITLE
Teach CCueDocument to handle per-track genres and comments

### PR DESCRIPTION
**Pull request by scbash**
## Description
Hi all.  I've had this branch in my local repo for many years (ouch, Github now informs me since 2011...), but apparently never saw fit to put it up for review.  This change adds support for per-track genres and comments in cue sheets.  Comment support is a little simplistic with the last comment on each track winning, but in my library that was good enough.  It's been long enough since I originally wrote this code I don't remember whether this particular format (per-track genres and comments) matches published standards for cue sheets or not.  This PR is primarily to test the waters and see if there is community interest in this change.  The commit messages have historical details to help me remember the evolving history of these patches, but I'm happy to reword them if the community does want to integrate them.

Note: these patches are currently against Leia, not master, as I prefer to keep my local Kodi build based on stable releases.  I can retarget the commits if master is preferred (I am one of the [potentially cursed] git-ninjas referred to in the contributing guide, so that rebase wouldn't be a problem).

## Motivation and Context
The motivation for the genre change is in my library I have several broad genres like "Instrumental" or "Vocal", and with those broad categories it is common for a single album to have some instrumental tracks and some vocal tracks.  Kodi worked very well with my tagging scheme in FLAC files, but I have two AC3 (Dolby Digital) albums stored as raw bitstreams in WAV files requiring cue sheets, and I found Kodi did not allow me to tag individual track genres.  Unfortunately the actual cue sheets I've been using are apparently locked up on a decomissioned hard drive -- I didn't realize until tonight they didn't survive the most recent NAS migration, but I think I can dig them up if there's interest.

The motivation for the comment change came from [Star Wars: A Musical Journey](https://starwars.fandom.com/wiki/Star_Wars:_A_Musical_Journey), where the disc jacket has a natural Title - Subtitle flow where the subtitle listed the original tracks being mixed in the new recording (the link shows this pretty well), so I used the comment field capture the subtitle.  IIRC at the time the default skin showed the comment field in the track info screen, so it was beneficial to correctly capture the field for each track. 

## How Has This Been Tested?
Only tested locally in my library with the two cue sheets previously mentioned, but tested from Gotham through Jarvis in my primary listening system.  All use would have been on Mac, though I forget the specific OS versions (nothing from the past two years, the Mac Mini cooked itself sometime around late 2017/early 2018).

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project (I think...?)
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by the-black-eagle** [comment]
You'll need to rebase this against master as Leia is not getting any updates now.

**Comment by DaveTBlake** [comment]
> I don't remember whether this particular format (per-track genres and comments) matches published standards for cue sheets or not. 

I think that is significant. Kodi endevours to match either standards or common community tag use where they exist. Cue sheets do have a basic standard, it is old and limited because it was (almost completely) superseded by use of formats with embedded metadata. Having Kodi use cue sheets in a bespoke way (unique to Kodi) is not the best idea IMO.

> This PR is primarily to test the waters and see if there is community interest in this change. 

The music library is my main interest in Kodi and I personally encourage users to use song per file and formats with embedded metadata. Kodi handles gapless playback and tag formats support a much wider range of data than standard cue sheets. However I know there are posts on the forum from a minority that still use cuesheets and would like more from them.

I would not block anyone that wanted to enhance cue sheet support providing it did not have a negative impact on music library use. Previous cue sheet support was poorly implemented and accidently slowed all music data access (now fixed, but left me grumpy about the whole concept). 

So @scbash  dig out the cuesheet standard, or evidence wider community use, that makes sense of what you propose, maybe check what has been said in the past on the forum, and raise against v19.

**Comment by scbash** [comment]
Thanks @the-black-eagle and @DaveTBlake.

A quick skim of Wikipedia and Hydrogenaudio's entries on CUE sheets doesn't say much about genre or comment, just that `REM` can be used for comments which are ["used by some programs to store nonstandard metadata like genre, freeDB disc ID, etc."](https://wiki.hydrogenaud.io/index.php?title=Cue_sheet).  I'll see if I can find a larger community discussion or support for this change.

Alternatively I completely agree, embedded metadata is definitely the way to go, so I should really test a recent version of Kodi with AC3 embedded in FLAC.  MANY years ago I got SlimServer to correctly bitstream AC3 from FLAC to a Dolby Digital receiver, but at the time Kodi always manipulated the samples destroying the AC3 bitstream (even with ReplayGain turned off; I remember looking at the code and finding the problem but decided against modifying it, but now I don't remember at all what the problem was...).  If that works I can dump all my CUE sheets and just use FLAC/Vorbis tags (conveniently I still have the FLAC files from the SlimServer days).

**Comment by scbash** [comment]
Looks like AC3 packaged in MP4 fulfills my needs, and supports embedded metadata, so this change is no longer necessary.  @DaveTBlake if you end up in one of those forum cue sheet conversations and need these changes, I'm happy to pull them forward and contribute them, but barring an obvious use case I'm going to close this PR for now.

Thanks for the helpful conversation!  I have some other library improvement ideas, so perhaps we'll be chatting again soon 🙂

**Pull request closed without merging**
