### PR TITLE
[win32][test] Fix linking of the test suite

### PR DESCRIPTION
**Pull request by Paxxi**
This should solve the build issues with the test suite

### CODE REVIEW

**Comment by Paxxi** [comment]
@Razzeee care to try it out?

**Comment by Razzeee** [comment]
Jenkins will let us know http://jenkins.kodi.tv/view/Helpers/job/TestMulti-All/609/

**Comment by Razzeee** [comment]
Well it did build. But it seems like the test suite didn't run. http://jenkins.kodi.tv/job/WIN-32/8860/console I'll do another build to see if jenkins was confused.

**Comment by Razzeee** [comment]
jenkins build this please

**Comment by fetzerch** [comment]
If I'm not mistaken, there's no command telling jenkins to build and test.
I manually started one for you: http://jenkins.kodi.tv/view/Windows/job/WIN-32/8891/

**Comment by Razzeee** [comment]
I know, but as appveyor failed I wanted to see if the normal project builds fine.

**Comment by Razzeee** [comment]
As this is only ment to fix the linking, not the tests exiting for some reason. I will merge this, as it does what it promisses.

**Pull request merged**
