### PR TITLE
[Android] added more program information for android tv channels

### PR DESCRIPTION
**Pull request by Maven85**
## Description
This PR adds or changes programm information for android tv channels.
Affected types are movies, shows and episodes.

**Single informations are only shown if they are available.**

**Informations for movies**
old: title, tagline
new: title, year, runtime, rating, plot

**Informations for shows**
old: title, studio
new: title, year, rating, plot

**Informations for episodes**
old: episodeTitle, showTitle, seasonNo, episodeNo
new: episodeTitle, showTitle, firstaired, seasonNo, episodeNo, runtime

## Motivation and Context
This addition makes browsing Kodi media from Android TV's home screen a richer experience.

## How Has This Been Tested?
On my Shield TV with custom kodi builds.

## Screenshots (if appropriate):
movies old
movies_old
movies new
movies_new

shows old
shows_old
shows new
shows_new

episodes old
episodes_old
episodes new
episodes_new

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Dnkhatri** [comment]
I hope this pr will be accepted  and back ported for Leia 18.5 as well

**Comment by Dnkhatri** [comment]
@peak3d Sorry to be a bother but could you please check and merge this pr.

**Review by peak3d — APPROVED** [review]
This looks fine for me

**Comment by Rechi** [comment]
@peak3d please always set the version label, other labels and milestone before or right after merging a PR.

**Pull request merged**
