### PR TITLE
[xbmc][threads] Switch from homegrown atomics to std::atomic

### PR DESCRIPTION
**Pull request by Paxxi**
standard library should be good enough now that we can switch
over to std::atomic and let the compiler people worry about making
it work on all platforms.

### CODE REVIEW

**Comment by Paxxi** [comment]
@FernetMenta what do you think?
@koying I'm touching your stuff so please take a look at it :)
jenkins build this please

**Comment by Montellese** [comment]
I've been thinking about doing this as well. Do we have any clue about the performance of `std::atomic` versus our platform-specific ASM implementations?

**Comment by Paxxi** [comment]
I haven't done any testing but reading through the implementation in VS12 they map to the intrinsics for Interlocked* and Compare*, they do have some tiny overhead though with checking the memory ordering as that can be specified but I doubt that'll matter in the real world.

**Comment by fritsch** [comment]
awesome - if that will work out :-)

**Comment by Paxxi** [comment]
this is a test from VS2015 with a release build, now my asm skills aren't great but it does look like the std atomic is a few instructions less than our asm version on windows
https://gist.github.com/Paxxi/676cef19627bc3da40f2

**Comment by FernetMenta** [comment]
at least half of this is in the part of the app that I currently change a lot: core
I agree that this changes are nice but at this time they only make my life harder because this results in lots of merge conflicts.
you could exclude core from this PR and send the changes to my repo

**Comment by Paxxi** [comment]
@FernetMenta it's not like there's any rush to get this in so we can with merging as well. Which branch are you working on that I should PR against in that case?

**Comment by fritsch** [comment]
@paxxi: https://github.com/FernetMenta/xbmc/commits/master

2015-09-11 22:40 GMT+02:00 Pär Björklund <notifications@github.com>:

> @FernetMenta <https://github.com/FernetMenta> it's not like there's any
> rush to get this in so we can with merging as well. Which branch are you
> working on that I should PR against in that case?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/xbmc/pull/8026#issuecomment-139656731>.
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by FernetMenta** [comment]
currently I am having fun with rebase on the RDS merge :) thanks for your understanding

**Comment by Rechi** [comment]
this is obsolete by #11251

**Pull request closed without merging**
