### PR TITLE
[gui] Sort include files on GUIWindowLoginScreen.* alphabetical

### PR DESCRIPTION
**Pull request by AlwinEsch**
Is one of my old changes (some months ago), no special only sort of the headers alphabetical.

Want to try the merge of them, but if problematic to changes from others can it be easily closed. Currently I make a clean up from all my branches.

### CODE REVIEW

**Comment by mkortstiege** [comment]
Objections anyone?

**Comment by Razzeee** [comment]
Personally I think alphabetical is the best way, but have we commited on that? Not sure if I mix things up, but wasn't there someone thats going for the other style?
If we go for this, we should write it down in the wiki.
http://kodi.wiki/view/Official:Code_guidelines_and_formatting_conventions

**Comment by hudokkow** [comment]
Taking the topic one step further, what's the preference? global to local or local to global include order? http://stackoverflow.com/a/2762596

**Comment by AlwinEsch** [comment]
To have the system headers first is for me the best, but the order of the others can not direct say what I like more :)

To have the local first make sense, then we are sure in headers that all needed others are included. The other with them last is for me better readable.

But I think to change it over, what making sure the header is correct and make more sense. Seeing currently on binary add-on libraries rework the headers problematic due to the two different places (public headers and internal cpp code).

**Comment by AlwinEsch** [comment]
Request is updated and also added a guideline about it to the wiki:
http://kodi.wiki/view/Official:Code_guidelines_and_formatting_conventions

jenkins build this please

**Comment by Razzeee** [comment]
Thank you. Build only failed due to some addon.

**Pull request merged**
