### PR TITLE
tvshow_view is still tvshowview in Helix

### PR DESCRIPTION
**Pull request by bellini666**
Issue introduced in 9f432dc62b8a0aae1972e8a1190c5bd870c2e6e1

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Sorry, no bug fixes for Helix any more

**Comment by MartijnKaijser** [comment]
@hackedbellini this is already corrected in our master branch?

**Comment by Montellese** [comment]
@MartijnKaijser: The error crept in in a backport from master branch. In Isengard the SQL view is called `tvshow_view` but in Helix it was `tvshowview`.

**Comment by MartijnKaijser** [comment]
right. Though so but better ask to be sure :)

**Pull request closed without merging**
