### PR TITLE
[depends] bump zlib to 1.2.11

### PR DESCRIPTION
**Pull request by Rechi**
## Description
bump zlib to version 1.2.11

## How Has This Been Tested?
compiled depends for linux and android
darwin platforms use zlib from their toolchain, so nothing to test

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by sualfred** [comment]
@Rechi 

1.2.11 breaks a lot of .png's in Leia, see:

https://forum.kodi.tv/showthread.php?tid=329375
and
https://trac.kodi.tv/ticket/17800

Example screenshots:
https://imgur.com/CcetwuC
https://imgur.com/MtcbAjq
https://imgur.com/7Su90Ze

It's working with the zlib.dll of Krypton (1.2.8).

**Comment by sualfred** [comment]
In the meantime I contacted Mark Adler of zlib to report the issue. He tested my test images and he has no problems with decomprising them. 

His reply:

> Sebastian,
> 
> I see no problem decompressing any of those with zlib 1.2.11. There may be some issue with how the DLL was built, or some other change between your v17 and v18 code.
> 
> Mark

My knowledge about this stuff is very limited so I hope you will find the issue and we don't have to jump back to the previous version.

Btw:
I've tested 3.4 and 4.0 ffmpeg to see if it's some kind of compatiblity. Same problem on both versions.

```
ERROR: ffmpeg[2810]: [png] inflate returned error -3
DEBUG: Error [-542398533] while decoding frame: Unknown error
```

**Comment by Rechi** [comment]
This is for sure not related to your issue on windows, as this PR didn't change anything for that platform.
Windows dependencies are listed at `project/BuildDependencies/scripts/0_package.target-*.list`

**Comment by sualfred** [comment]
Ah, sorry. This was the only PR I found while I was searching for zlib. 
With pointing me to the correct folder I've noticed that the x32 version is still build with 1.2.8. So it has to be something different. I'm running out of ideas how I could contribute with more investigations.

If you have any other idea ... any help is appreciated.

**Comment by sualfred** [comment]
@Rechi 

Thanks again for pointing me into the right direction. Found the problem: The included zlib.dll in the dependencies is broken and outdated. 

Please take a look at my post in the board:
https://forum.kodi.tv/showthread.php?tid=329375&pid=2727240#pid2727240

**Pull request merged**
