### PR TITLE
[addons] show repository version instead of local one in 'available updates'

### PR DESCRIPTION
**Pull request by tamland**
fixes http://trac.kodi.tv/ticket/16457

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by tamland** [comment]
jenkins build this please

**Comment by MilhouseVH** [comment]
On low powered devices this change substantially increases the time taken to enter System > Add-ons.

On an RPi2 with 5 repositories (Kodi, OpenELEC Official, OpenELEC Unofficial, popcornmix and Leopold's repositories), it now takes 4-5 seconds.

On an RPi1 with 8 repositories it's taking 15 seconds.

Not sure if the delay scales with number of repositories or the number of installed addons, but anyone with a lot of repositories and/or installed add-ons might now think their device has crashed when entering System > Add-ons (there's been one such report [on the forum](http://forum.kodi.tv/showthread.php?tid=250817&pid=2211111#pid2211111)).

**Comment by popcornmix** [comment]
I've just tried from a completely clean install (renamed ~/.kodi) and it took 24 seconds to open add-ons on a Pi 2. It did look like it had crashed.
A subsequent open takes 9 seconds.

**Comment by tamland** [comment]
Does entering 'Install from repository > All repositories' and 'Available updates' take similar amount of time? I don't have any slow device to test with; it's all instantaneous here.

**Comment by MilhouseVH** [comment]
Entering `Available updates` takes about the same amount of time as entering `System` > `Add-ons` (15 seconds the first time on RPi1, about 10 seconds on subsequent tries)

Entering `Install from repository` > `All repositories` is relatively quick on RPi1, ~5 seconds each time.

**Comment by tamland** [comment]
It's not obvious why it's so slow. I cannot reproduce, but the only difference between the current `All repositories` and `Available updates` should be that the latter additionally does one checks for each addon in repo against the local one, which would suggest the bottleneck is in the manager/factory.

If `All repositories` alone takes 5 seconds though it seems that we have major performance issues in the db level as well that I was not aware of.

We can revert for the time being as that will probably take a lot more work to fix.

**Comment by MilhouseVH** [comment]
I'd vote for a revert in the absence of any better solution.

It's a shame the addon side of things doesn't log any SQL queries as it's difficult to determine where any database related bottleneck may reside when there is no evidence of any SQL queries taking place (when debug is enabled).

**Comment by tamland** [comment]
@MilhouseVH Added a line to time it in https://github.com/tamland/xbmc/commits/getaddons_timing which should give you an idea of long the db parts takes. For me it takes ~100 ms.

I discovered that all root directories in the media windows are fetched twice for some reason, so fixing that will reduce it by half.

**Comment by MilhouseVH** [comment]
On an RPi1 with https://github.com/tamland/xbmc/commit/fcb5dbf64c86b31c2e3386b04e771a9e95492f26:

Entering `System` > `Add-ons`:
```
16:56:10 178.887115 T:1964307328   DEBUG: CAddonDatabase::GetAddons took 2981 ms
16:56:13 182.082184 T:1964307328   DEBUG: CAddonDatabase::GetAddons took 3011 ms
16:56:16 185.278687 T:1964307328   DEBUG: CAddonDatabase::GetAddons took 3011 ms
```

Entering `Install from repository` > `All repositories`:
```
16:56:31 200.747787 T:1839657888   DEBUG: CAddonDatabase::GetAddons took 4026 ms
```

Back to `Add-ons`:
```
16:56:47 216.258957 T:1964307328   DEBUG: CAddonDatabase::GetAddons took 3100 ms
```

Entering `Available updates`:
```
16:56:57 226.100723 T:1591677856   DEBUG: CAddonDatabase::GetAddons took 3962 ms
16:57:01 230.126068 T:1591677856   DEBUG: CAddonDatabase::GetAddons took 3843 ms
```

Full debug log: http://sprunge.us/TQhE

**Comment by MilhouseVH** [comment]
Running [the SQL](https://github.com/tamland/xbmc/blob/fcb5dbf64c86b31c2e3386b04e771a9e95492f26/xbmc/addons/AddonDatabase.cpp#L372-L373):
```
SELECT DISTINCT a.addonID 
FROM   addon a, addonlinkrepo b
WHERE  b.idRepo > 0 
       AND a.id = b.idAddon 
       AND NOT EXISTS (SELECT repo.id 
                       FROM repo, disabled 
                       WHERE repo.addonID=disabled.addonID 
                             AND repo.id=b.idRepo)
```
against Addons20.db at the command line on the RPi1 returns 956 rows more or less instantly (0.27s) - do you know if there are any additional WHERE clauses being added to this base `sql`?

Assuming the SQL query isn't the issue (and it doesn't appear to be) then calling `GetAddon(m_pDS->fv(0).get_asString(),addon)` 956 times must be where the delay is occurring.

I may be reading the code incorrectly, but this is what I surmise:

Each call to [GetAddon(string, addon)](https://github.com/tamland/xbmc/blob/fcb5dbf64c86b31c2e3386b04e771a9e95492f26/xbmc/addons/AddonDatabase.cpp#L263) performs one additional SQL lookup: 

```
std::string sql = PrepareSQL("select id,version from addon where addonID='%s'",id.c_str());
```
GetAddon(string, addon) ultimately calls [GetAddon(int, addon)](https://github.com/tamland/xbmc/blob/fcb5dbf64c86b31c2e3386b04e771a9e95492f26/xbmc/addons/AddonDatabase.cpp#L301) where another SQL lookup is performed. 

```
 	    std::string sql = "SELECT addon.*,"
                      "       broken.reason,"
                      "       addonextra.key, addonextra.value,"
                      "       dependencies.addon, dependencies.version, dependencies.optional"
                      "  FROM addon"
                      "    LEFT JOIN broken"
                      "      ON broken.addonID = addon.addonID"
                      "    LEFT JOIN addonextra"
                      "      ON addonextra.id = addon.id"
                      "    LEFT JOIN dependencies"
                      "      ON dependencies.id = addon.id";
```

So in order to get the version number for all 956 addons, there are now 1930 (956 * 2) additional SQL queries being performed... this doesn't sound like it's the most efficient solution.  :)

**Comment by tamland** [comment]
You're reading correct @MilhouseVH. It was definitely never *efficient*, but still, 2000 simple queries isn't that much in my book. I'd expect it to handle more than that.

**Comment by MilhouseVH** [comment]
It's not 2000 queries, it's closer to 6000 queries when entering Add-ons the first time as `GetAddons()` is being called 3 times. You mentioned the root directories were being fetched twice so maybe one of these calls can be eliminated but it's still close to 4000 queries (and a lot of other processing) for very little obvious benefit. And also bear in mind this is testing on a system with hardly any third party add-ons/repositories installed - it would be interesting to know how many rows (add-ons) are returned on @popcornmix's system.

**Comment by MilhouseVH** [comment]
The user who thought his Pi had crashed due to these delays has confirmed to me that the initial query returns 2,891 rows in 0.17s. This then translates into 2,891 * 2 * 3 => 17,346 individual queries and significant delay every time the user enters `Add-ons` (this includes navigating back up to `Add-ons` from a lower level such as `Install from repository`, `Available updates`, `My add-ons` etc., or to anywhere else that calls `GetAddons()`). This makes the `Add-ons` settings menu pretty much unusable.

Obviously I appreciate the effort from @tamland trying to improve things, but am a little bemused why such an inefficient solution is apparently acceptable. Tens of thousands of repeated individual SQL queries is absolutely not a good idea in any book IMHO, and while it may result in acceptable performance on Core i7 systems, it's going to suck badly on just about everything else.

I don't know what else to say on this, really, other than this should be reverted until such time as it can be implemented using a more efficient method. Or just disable it on low powered devices, as the problem it solves seems to be entirely cosmetic.

**Comment by MartijnKaijser** [comment]
We are in alpha stage so treat it as such. If the user is not happy he should be using "stable"  versions. Alpha are the point where we find out these problems.

**Comment by MilhouseVH** [comment]
What i said above has nothing to do with the user.

**Comment by tamland** [comment]
@MilhouseVH Not invented here. This pr merely change it from showing locals to remote, and the performance appeared to be unaffected (on my low-end i5 fyi).

I'm currently investigating why the root directory is being fetched multiple times, which should largely solve the performance issue. After that I'll look into why `GetAddons` is using so many queries and if it can be reduces.

As I already said: there's no problem revering it in the meantime, and revert again when improved. Pr it and merge away.

**Pull request merged**
