### PR TITLE
[backport][GUI][X11] Fix deadlock on dialog renderloop

### PR DESCRIPTION
**Pull request by enen92**
## Description
Backport of https://github.com/xbmc/xbmc/pull/25426 for Omega

### CODE REVIEW

**Comment by enen92** [comment]
@garbear since you were the one approving the master one, is this good to go?

**Comment by garbear** [comment]
Diff is unchanged and 1 failed test on osx-64 is unrelated

**Review by garbear — APPROVED** [review]
Diff is unchanged and 1 failed test on osx-64 is unrelated

**Comment by enen92** [comment]
Jenkins build this please

**Pull request merged**
