### PR TITLE
[PVR] CPVRClient(s)::OpenStream: Remove unused parameter bIsSwitchingChannels

### PR DESCRIPTION
**Pull request by ksooo**
Just a tiny method signature cleanup - leftover from videoplayer channels witch rework.

@Jalle19 mind doing the review?

### CODE REVIEW

**Review by Jalle19 — APPROVED** [review]

**Comment by Seattleguy6969** [comment]
$ ramdiskadm -d ramdisk1

**Comment by Seattleguy6969** [comment]
/dev/ramdisk

**Comment by fritsch** [comment]
Press Alt-TAB or fix your WM to not focus where the mouse currently points to if you cannot handle it.

**Comment by Seattleguy6969** [comment]
;{-_rn

**Comment by ksooo** [comment]
Could you please stop this nonsense? Thanks.

**Pull request merged**
