### PR TITLE
remove deprecated windows

### PR DESCRIPTION
**Pull request by ronie**
remove all (references to) deprecated windows and related code.

most of these are from the time we had separate files/library windows for music and videos,
that were wrapped under a virtual window.

needs review & testing!

@Montellese for settings change
@mkortstiege for gui stuff

@phil65 / @BigNoid / @HitcherUK for regression testing

### CODE REVIEW

**Comment by BigNoid** [comment]
It looks like the keymaps still use the deprecated values:
http://pastebin.com/ecnNsweu

**Comment by ronie** [comment]
thanx @BigNoid 
pr updated to include those changes as well.

**Comment by BigNoid** [comment]
Looks like you got em all now :)

**Comment by ronie** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
ping for merge

**Comment by mkortstiege** [comment]
Changes are looking good to me.

**Pull request merged**
