### PR TITLE
[docs][addons] sync doxygen between Kodi and addons

### LINKED ISSUE #16930: Inconsistent documentation configuration files
### Describe the bug
There are a number of doxygen configuration files in the project a.o.
- docs\doxygen\Doxyfile.doxy
- addons\kodi-addon-dev-kit\doxygen\Doxyfile

but they are not consistent, e.g.  the `ALIASES` contains in the later `cpp_class` that is missing in the first one.

## Expected Behavior
Consistent doxygen configuration files
- containing the same information
- using the same information by means of  `@include`  (see doxygen documentation chapter Configuration, http://www.doxygen.nl/manual/config.html)

## Actual Behavior
When creating doxygen output from all files when can get confusing warnings when using the wrong `ALIASES` set and has to merge both sets.

## Possible Fix
See Expected behavior

### To Reproduce
 Not relevant

### Debuglog
None

### Screenshots 
None

## Additional context or screenshots (if appropriate)
None

### Your Environment
Used Operating system:
Operating system is not really relevant
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: master / 18.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description
Cleanup some addon related doxygen parts and sync between addon doxygen and Kodi doxygen.

This related to fix an issue of Kodi.

About changed PVR is visible here https://alwinesch.github.io/group__cpp__kodi__addon__pvr___channels.html

## Motivation and context
Related to issue https://github.com/xbmc/xbmc/issues/16930

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Have added a additional patch as there was on python come some not allowed lines where breaks newer doxygen versions.

**Comment by AlwinEsch** [comment]
jenkins build this please

**Review by phunkyfish — APPROVED** [review]
Looks sane to me

**Comment by AlwinEsch** [comment]
Shit, https://codedocs.xyz/xbmc/xbmc/group__python__xbmcgui.html seems not works with this :cry:.

Have someone a idea what need be set on https://github.com/xbmc/xbmc/blob/master/.codedocs or where is a documentation about?

On https://codedocs.xyz/ is not really a documentation about or link to ask. Maybe something available for one where has access to there?

**Pull request merged**
