### PR TITLE
[tuxbox] remove internal tuxbox support

### PR DESCRIPTION
**Pull request by mkortstiege**
This removes un-maintaned and partly non-working tuxbox code from core.
Replacement for this is the eg. VUPlus pvr addon.

### CODE REVIEW

**Comment by mkortstiege** [comment]
jenkins build this please.

**Comment by hudokkow** [comment]
+1
This was on my todo list. AFAIK pvr.vuplus only supports enigma2 stbs. Users with old enigma1 stbs won't be able to use it. Anyway, they had 10 years to buy better hardware.

**Comment by topfs2** [comment]
And could stick with helix :)
+1 removing old code from me too

**Comment by mkortstiege** [comment]
jenkins build and merge

**Pull request merged**
