### PR TITLE
[pvr] CPVRRecording::GetResumePoint(): Performance: Update resume poi…

### PR DESCRIPTION
**Pull request by ksooo**
…nt from backend at most every 10 secs.

Fixes a performance problem reported in the forum: https://forum.kodi.tv/showthread.php?tid=337834

@Jalle19 good to go?

### CODE REVIEW

**Review by Jalle19 — COMMENTED** [review]
Wouldn't it be better to change so that this method doesn't get called as frequently?

**Comment by ksooo** [comment]
Definitely, but I have no clue how to do this. It's deeply barried in guilib. No idea why guilib is requesting the value that often. It's another one of the category "we need to change all the guiinfio stuff from pull to push" , but that's nothing for RC phase...

**Comment by MartijnKaijser** [comment]
In that case it should be good to add a todo note saying that rootcause needs to be "solved"

**Comment by ksooo** [comment]
@MartijnKaijser added the requested todo remark...

**Review by Jalle19 — APPROVED** [review]
Good idea with the TODO

**Pull request merged**
