### PR TITLE
[cmake] fix variables for LIBFMT, LIBSPDLOG, LIBFSTRCMP

### PR DESCRIPTION
**Pull request by howie-f**
## Description
follow up fix for https://github.com/xbmc/xbmc/pull/20864

CMAKE variables need to be `LIBFMT_ARCHIVE`, `LIBSPDLOG_ARCHIVE`, `LIBFSTRCMP_ARCHIVE`.
otherwise download of the tarballs fails since `FMT_ARCHIVE` etc. are just unset.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by wsnipex** [comment]
looks good. At least fstrcmp would need the same treatment though ;)

**Comment by howie-f** [comment]
thanks. i tested them manually now and it looks like we caught any :)

**Review by wsnipex — APPROVED** [review]

**Review by fuzzard — APPROVED** [review]

**Comment by fuzzard** [comment]
Sorry about that. Have a couple branches changing stuff in here, obviously missed some stuff

**Comment by howie-f** [comment]
all good, i learned something new today ;)

**Pull request merged**
