### PR TITLE
[pvr] Point add-ons to master instead of SHA

### PR DESCRIPTION
**Pull request by hudokkow**

### CODE REVIEW

**Comment by hudokkow** [comment]
jenkins build add-ons please

**Comment by hudokkow** [comment]
arghh, jenkins build addons please

**Comment by MartijnKaijser** [comment]
\o/ saves a lot of time
@Montellese this should be fully working now right?

**Comment by stefansaraev** [comment]
@MartijnKaijser from what I see in jenkins logs - yes. push it

**Pull request merged**
