### PR TITLE
[tools/depends][target] Bump curl 8.10.0

### LINKED ISSUE #25118: Update 21 on Android TV broke TLS ftp source, Windows works
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi 21.0 on Android TV (and Android in general) broke connectivity to FTP sources which require additional flags such as TLS, e.g. "ftp://host.com:21/files/|auth=TLS&verifypeer=false". This functionality still works on Windows. As per [support forum](https://forum.kodi.tv/showthread.php?tid=377271) multiple people face the same issue.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Remote folder is accessible and opens in file browser

## Actual Behavior

Kodi takes a few seconds to attempt connection to the remote folder, ultimately shows empty folder. No notification.

## Possible Fix

N/A

### To Reproduce

1. Add FTP sources with flags such as |auth=TLS&verifypeer=false
2. Add folder using new source
3. Attempt to open folder

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/15209595/kodi.log)
From forum user blunden:
[debug log](https://pastebin.com/YZ2J1q9t)

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android (Shield TV)
 - Kodi version: 21.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by blunden**
## Description

Bumps curl to 8.10.0.

## Motivation and context

Should fix issues with FTPES sources (https://github.com/xbmc/xbmc/issues/25118) as well as patch a few vulnerabilities. FTPES sources have been broken ever since the first Kodi Omega release and is confirmed to have been fixed in curl version 8.9.1. I simply picked the latest version.

https://forum.kodi.tv/showthread.php?tid=377271
https://forum.libreelec.tv/thread/28779-sftp-broken-in-le12/?postID=194487#post194487
https://curl.se/docs/vulnerabilities.html

## How has this been tested?

Build tested on Ubuntu 24.04. Will look into testing it on Android as well.

## What is the effect on users?

Besides fixing the issue mentioned above, it should hopefully not have many visible changes.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by thexai** [comment]
The build failures are due to "nghttp2 static" patch being no longer needed as it was included in upstream:

https://github.com/vszakats/curl/commit/86805bfcdadef588e2c325212f066122f2daf4ec

Then patch should be removed in:

https://github.com/xbmc/xbmc/tree/master/tools/depends/target/curl/01-win-nghttp2-add-name.patch

and

https://github.com/xbmc/xbmc/blob/0d165bea7389e42857a1b87110ed661bb9fbf33b/cmake/modules/FindCurl.cmake#L37-L39

**Comment by blunden** [comment]
There were build failures? It seemed to build fine locally.

I can certainly remove those if you want though. Should I update the PR with a separate commit doing that? 🙂

**Comment by thexai** [comment]
@fuzzard knows better but seems is remove file `tools/depends/target/curl/01-win-nghttp2-add-name.patch` 

and lines 

```
 set(patches "${CORE_SOURCE_DIR}/tools/depends/target/${MODULE_LC}/01-win-nghttp2-add-name.patch") 
  
 generate_patchcommand("${patches}") 
```

in xbmc/cmake/modules/FindCurl.cmake

In the same commit is enough

**Comment by thexai** [comment]
It seems fine to me now. 

Thanks!

**Comment by blunden** [comment]
Great!

I obviously hope that we can get this change backported too, if merged, since built in functionality is currently broken with the current curl version. 🙂

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by neo1973** [comment]
Hi @blunden, please create a PR against the Omega branch for the backport.

**Comment by blunden** [comment]
@neo1973 I thought you guys mostly automated the smaller backports like these?

**Comment by neo1973** [comment]
Nope, it's a manual process. Usually the person who created the initial PR also handles the backport but this isn't a requirement. So if you don't want to do it I can do it as well 🙂

**Comment by blunden** [comment]
I see. I can do it. I would assume it should cherry-pick cleanly to Omega as well.

I just wish someone would've told me that I should submit a backport too a month ago. 😄

**Comment by blunden** [comment]
@neo1973 Backport PR:

https://github.com/xbmc/xbmc/pull/25849

**Pull request merged**
