### PR TITLE
misc cmake fixes

### PR DESCRIPTION
**Pull request by stefansaraev**
## Description

as title says.

## Motivation and Context

I needed this to compile kodi for my OE fork

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by hudokkow** [comment]
lgtm. @fetzerch?
jenkins build this please

**Comment by stefansaraev** [comment]
android build errors seems related to recent PRs by @AlwinEsch - no shared libs installed anymore in lib/kodi/addons ?

**Comment by hudokkow** [comment]
jenkins build this please

**Comment by fetzerch** [comment]
looks good to me as well, thanks

**Pull request merged**
