### PR TITLE
[playlist] add b4s playlist recognition to music and tests

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Add b4s filetype recognition to music player. Add tests to test LoadData of b4s file

## Motivation and context
So it turns out deep down we can load a playlist for a long forgotten playlist type B4S. This apparently was a playlist type used by winamp long ago (before m3u). Found it looking at tinyxml usage.

This adds the ability for Music to recognise a b4s playlist using the already existing loading. I dont see a point to plumb in playlist saving to b4s in our playlist editor, so i dont test save.
Add test for loading

## How has this been tested?
Locally running kodi and kodi-test

## What is the effect on users?
Probably nothing, who even knows what a b4s file is?

## Screenshots (if appropriate):
Screenshot 2023-06-27 at 6 02 29 pm

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by enen92** [comment]
I think we have some wiki somewhere with the supported playlist types. @KarellenX maybe knows

**Comment by KarellenX** [comment]
Yes, here... https://kodi.wiki/view/Basic_playlists#Playlist_Files
I suppose b4s needs to be added to that. v21 only?

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by podlesnyak** [comment]
gh pr checkout 23450

**Pull request merged**
