### PR TITLE
fixed: add missing dependency for retroplayer messages

### PR DESCRIPTION
**Pull request by notspiff**
with internal flatbuffers we need to depend or flatc is not yet available.

### CODE REVIEW

**Review by wsnipex — APPROVED** [review]

**Review by garbear — APPROVED** [review]

**Comment by garbear** [comment]
Why `if(TARGET flatbuffers)`? I had the `add_dependencies` command before but removed it.

**Comment by notspiff** [comment]
Because target is only defined for internal flatbuffers and cmake will
complain if you add a dependency on a nonexistent target.

**Comment by bas-t** [comment]
This commit causes a build failure on Debian Stretch:
Could NOT find FlatBuffers (missing: FLATBUFFERS_FLATC_EXECUTABLE FLATBUFFERS_INCLUDE_DIR)

What do I need to install in order to build kodi?

**Comment by garbear** [comment]
Consult the Linux readme: https://github.com/xbmc/xbmc/blob/master/docs/README.Linux.md

In section 3 you'll see that `flatbuffers` is now a required package on linux. I don't believe Debian packages it, so you have several options.

In section 3.1, it gives you a command to build it yourself:

```
sudo make -C tools/depends/target/flatbuffers PREFIX=/usr/local
```

In section 3.2, it gives you a CMake flag to build flatbuffers as part of Kodi. Add this to your cmake command:

```
-DENABLE_INTERNAL_FLATBUFFERS=ON
```

**Comment by lrusak** [comment]
Just an FYI if you want to build flatbuffers yourself you can get the sources here https://github.com/google/flatbuffers

**Comment by bas-t** [comment]
Thanks.
The -DENABLE_INTERNAL_FLATBUFFERS=ON directive works just fine for me.

**Comment by M2k80** [comment]
have installed flatbuffers and flatbuffers-dev on ubuntu but cant crosscompile for android anymore

**Comment by lrusak** [comment]
@M2k80 you need to rebuild the entire depends in order to cross build. Follow the build instructions for a depends build

**Comment by M2k80** [comment]
i already did a complete rebuild but its still not working. 
i answered in this thread https://forum.kodi.tv/showthread.php?tid=332902
my error messages seems to be the same like from the user above.
i will post mine there in a few minutes.

**Comment by garbear** [comment]
This happened to a team member too, he had to rebuild a few times then it worked.

**Pull request merged**
