### PR TITLE
Don't flush ffmpeg buffers if it holds any refs on close

### LINKED ISSUE #23800: VAAPI: crash with some HEVC UHD videos
### Describe the bug
Here is a clear and concise description of what the problem is:

I came across some UHD Blu-rays that would crash Kodi during playback. It is not random, it crashes at a certain timecode. 
I can reproduce the crash on my Intel TGL and AMD RX6600 when using VAAPI hw acceleration. 

Edit: it crashes on Windows too.

[Sample video](https://www.dropbox.com/scl/fi/4j5z2vxrw96rf0p6tzq2r/vaapi-crash-hevc-4k.mkv?rlkey=9qjhokpwfhl7i63gghhthdz2x&dl=1)

### To Reproduce

1. Play my sample video on a Linux system with VAAPI. It should crash at 00:00:11.

### Debuglog

The debuglog can be found here:
[debug log](https://hastebin.com/share/yinowepiki.yaml)
[crash log](https://hastebin.com/share/akicepelub.yaml)

### Your Environment
Used Operating system:

 - [x] Linux

 - Operating system version/name: LibreELEC
 - Kodi version: current master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by smp79**
## Description

This fixes #23800 

## How has this been tested?

I tested VAAPI change for a few weeks with no issues. DXVA also runtime tested.

## Types of change

- [X ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fritsch** [comment]
Thanks. It is currently not clear if recent findings on dxva would point to a memory leak if this is removed. I am also bit sure if we should distinguish, better track the case when ffmpeg reuses the frames vs in general stopping to free them always.

**Review by thexai — APPROVED** [review]
Runtime tested Windows x64 - DXVA

Confirmed that fixes the crash and also tested for memory leaks and no issues found (tested for increment of memory usage during playback and not released memory after play/stop multiple times).

**Comment by CrystalP** [comment]
I initially runtime-tested dxva by going over the "glitch" of the sample in #23800 manually a dozen times and didn't find an obvious problem.

The crash found by OP in #23803 with same patch after running all night with very frequent decoder creation makes me pause though. It's not proof though, memory exhaustion could be from dxva or iptv, it's not very clear yet.

I'd feel better with a real stress test, like playing a test file that recreates the decoder in a tight loop all night.

**Comment by CrystalP** [comment]
Good. I did some testing as well and put the sample (shortened to 5s surrounding the problem timestamp) on playlist repeat but some sort of race killed Kodi.

After 15 minutes, crash on one computer (Intel igpu) in OnPlaybackEnded:

image

On other computer (nVidia GT1030), it took 30 minutes to fail in same place, not great. The next attempt same computer lasted 6 hours so I'm OK for that config, ffmpeg or D3D didn't leak.
Intel aborted pretty quickly (see above) so results not very conclusive.
I can try AMD.

**Comment by CrystalP** [comment]
Also good with AMD.

**Comment by fritsch** [comment]
jenkins build this please

Let's get it in for broader testing.

**Comment by fritsch** [comment]
Thanks very much!

**Pull request merged**
