### PR TITLE
FIX: ensure real filename from videodb in playlists

### PR DESCRIPTION
**Pull request by koying**
fixes issue when downloading subtitles side-by-side

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Thanks @koying, this has fixed the subtitle download issue: https://forum.kodi.tv/showthread.php?tid=298462&pid=2606809#pid2606809

Unfortunately it doesn't appear to have had any effect on the watched statuses: https://forum.kodi.tv/showthread.php?tid=298461&pid=2605996#pid2605996

**Comment by koying** [comment]
Ok, thanks for the feedback

**Comment by mlburgett** [comment]
@koying, is there any info I can gather or tests I can run, to help with the 'watched statuses' issue @MilhouseVH refers to above?

**Comment by koying** [comment]
@MilhouseVH Would you mind trying the current version, please

**Comment by MilhouseVH** [comment]
@mlburgett can you try build [#0629b](http://milhouse.libreelec.tv/builds/testing/RPi2/LibreELEC-RPi2.arm-9.0-Milhouse-20170630143747-%230629b-g1196fc5.tar) which includes the latest commit from @koying.

Note this PR continues to be be included in regular test builds, so this updated PR with the new commit will be in tonight's `#0630` build.

**Comment by mlburgett** [comment]
@MilhouseVH, I don't see any change using #0629b, all my tv->recordings continue to show 'watched' status.  Partially watched recordings do still show correct status (as they have since this first showed up)

**Comment by da-anda** [comment]
I suppose the new "DynPath" thingy could/should be use here instead of altering the actual "path" that basically acts like the file ID? @FernetMenta ?

**Comment by FernetMenta** [comment]
@da-anda nope, DynPath only get evaluated by inputstream at a time when the file gets opened for playback. 
but yes, id (path) should never be changed on a fileitem. better construct a new item insteead of chaning an existing one.

**Comment by da-anda** [comment]
@FernetMenta but if you create a new file item you will loose the identity
of the item. Shouldn't it be a goal to always keep the identity regardless
where the file is processed?

Am 20.08.2017 11:54 vorm. schrieb "Rainer Hochecker" <
notifications@github.com>:

**Comment by FernetMenta** [comment]
@da-anda what do you call the "identity of the item"?

**Comment by da-anda** [comment]
@FernetMenta well, the VFS path is basically the identiy of the fileItem, isn't it? As soon as you change the "path" property to something else you a) change the file type (your own words) and b) some things that rely on the VFS path won't work anymore (like some context menu stuff IIRC). Therefor IMO we neither should pass around stub fileItems (like we f.e. do for VideoInfoDialog which makes it impossible to implement a context menu there atm) nor alter the path.

**Comment by FernetMenta** [comment]
@da-anda right. IMO we should make those methods private like the comment in the code suggests:
https://github.com/xbmc/xbmc/blob/master/xbmc/FileItem.cpp#L1698
 Making use of SetPath is a step in the wrong direction an makes a fix harder.

**Comment by pogo1975** [comment]
i dont know if it was reported but whitout this patch if you disable play next video automaticly subtitles works well and downloading subtitles works, with this patch applied if you enable play next video automaticly subtitles works but if next video is played subs remains from the first one...

**Comment by MilhouseVH** [comment]
@koying: I don't know if this is ever going to be merged, but would you mind rebasing?

**Pull request closed without merging**
