### PR TITLE
dvdplayer: fixes for ff

### PR DESCRIPTION
**Pull request by FernetMenta**
still not perfect but much better than before

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by popcornmix** [comment]
I am finding some unexpected jumping backwards in the displayed time when in ff mode.
E.g. I was in ff x16 mode and displayed time showed 1:30, 1:40, 1:50, 2:00, 2:10, 1:40, 2:30 (I couldn't see the exact numbers, but it jumped from above two minutes to below two minutes, and you can see the elapsed bar glitch backwards a number of times).

The "demuxer seek to" and "seek ended up on time" messages look monotonic, but I suspect a stale timestamp is getting through and updating the media time to an old value.

This is on Pi2 with dvdplayer/mmal.

http://paste.ubuntu.com/10961499/

**Comment by FernetMenta** [comment]
talk is only about jumps in display time not the video, right?

**Comment by popcornmix** [comment]
It's hard to be sure when video is in ff x16, but the report is purely about the display time jumping backwards. I have no evidence that old video frames are actually displayed.

**Comment by FernetMenta** [comment]
now the time displayed is pts of displayed frame. the problem may be that after seek the displayed time is set to seek target.

**Pull request merged**
