### PR TITLE
fixed: broken rfft implementation used in audio visualizer api

### PR DESCRIPTION
**Pull request by notspiff**
this replaces it with a working version using kissfft.
- need to decide if this is how you want to supply kiss
- need project updates accordingly

### CODE REVIEW

**Comment by fritsch** [comment]
Thank you very much. If the kiss fft won't hit us with a bug - the wrapper and integration is very clear and implement cleanly!

@topfs2 that way you should be able to use our new internal fft again for your viz.

@ace20022 @mkortstiege could you PR the needed project changes?

**Comment by topfs2** [comment]
So awesome. IIRC I actually used kissfft in my viz and it works perfectly.
IMO any movement towards using a well established library rather than home
cooked gets an instant +1 from me :)
Den 1 maj 2015 9:02 fm skrev "Peter Frühberger" <notifications@github.com>:

**Comment by mkortstiege** [comment]
I won't be able to do the xcode work until monday.

**Comment by popcornmix** [comment]
I needed to add rfft.cpp to xbmc/utils/Makefile.in to get this to build. Without it I get:
```
xbmc/addons/addons.a(Visualisation.o): In function `ADDON::CVisualisation::OnAudioData(float const*, int)':
/home/dc4/xbmc_holder/xbmc/xbmc/addons/Visualisation.cpp:284: undefined reference to `RFFT::calc(float const*, float*)'
/home/dc4/xbmc_holder/xbmc/xbmc/addons/Visualisation.cpp:282: undefined reference to `RFFT::RFFT(int, bool)'
collect2: error: ld returned 1 exit status
```
E.g. https://github.com/popcornmix/xbmc/commit/78f25e480b4309f9a82373e350e39c969654ea9d

**Comment by Memphiz** [comment]
dito no xcode until monday

**Comment by FernetMenta** [comment]
I can try ...

**Comment by Memphiz** [comment]
@FernetMenta its easy - just look add the added files from this PR and add them to the xcode project - just ensure that you pick OSX, IOS and ATV2 as target so they get added to each (even if we don't build atv2 anymore we add all files for this target - just in case ...)

**Comment by FernetMenta** [comment]
@Memphiz I added kissfft.a to "internal libs"
https://github.com/FernetMenta/xbmc/commit/6715085163c5c8b00f056883b59704273f539698

is this correct?

**Comment by AchimTuran** [comment]
Is there any reason using kiss fft?
According to this: http://www.fftw.org/speed/Pentium4-2.4GHz-gcc/
fftw is much faster and also open source.
If you want to look into fftw, I use it for my LibXConvolver library and it works very well. Here are is my [implementation](https://github.com/AchimTuran/LibXConvolver/tree/master/LibXConvolverCore/LXC_fftHandles/LXC_fftwf), which shows how to use it with a wisdom file.

**Comment by popcornmix** [comment]
I believe this (https://github.com/itdaniher/kissfft) is referring to fftw when it describes an fft library that is twice as fast but 100k lines of code vs about 500 lines of code.

I think we need to decide if kissfft is fast enough before switching to a relatively huge alternative.

**Comment by topfs2** [comment]
I picked kissfft for my visualizer for precisely the reason @popcornmix stated, it was smaller :)

IMO looking into fftw feels like a seperate track, something that can be done in parrallell and might be a further improvement. But I see no reason to halt this merge as it is already cleaning up the code lots :)

**Comment by Paxxi** [comment]
You can pick 35b1ef3b64c07f87983f7855b78474394c0fb93b for VS project fixes and there's a fix for compilation there as well

**Comment by Memphiz** [comment]
@FernetMenta  grep SlingBox.a tools/darwin/Configurations - adding libraries is done via ascii editable xcconfig files. Also lib pathes and include pathes and flags are configured there. We only adapt xcode projects for adding files.

Also i somehow feel that adding a library to the lib dir in our tree is a step backwards. I thought we already moved stuff out from there to depends on purpose

**Comment by FernetMenta** [comment]
yes, this should go to depends not lib

**Comment by notspiff** [comment]
Sigh. I am abandoning this pr.

**Comment by FernetMenta** [comment]
Did I say anything wrong which pissed you off? If so apologies.

**Comment by jjd-uk** [comment]
This may help with understanding why https://github.com/notspiff/kodi-cmake/commit/960f8063815827bea419a605dd1c62b3c604ed78

**Comment by wsnipex** [comment]
if moving to depends is the issue, I'm happy to do it. Just let me know.

**Comment by fritsch** [comment]
I must say something very clear here. If PRs are closed, cause someone is asking(!), only asking a question, without knowing what has been talked about before, then this is not good at all.

The proposed code is doing the job we want. It introduces an easy to understand, thus maintainable FFT implementation, wrapped up in a nice way, which is miles ahead of what we had before.

But hey, @AchimTuran was _only_ asking a question, cause he is using it daily for writing his filters and doing signal theory. This was no bikeshedding at all.

**Comment by notspiff** [comment]
I asked and got an answer. I was done with that discussion. Not wasting time on shit already decided on. Now it all starts over. Same shit will happen in the other prs. Take the code do whatever you want but i am done.

**Comment by fritsch** [comment]
I will pick it up and PR it again. Thanks very much for doing this - as nobody cared enough to get it fixed at all.

**Pull request closed without merging**
