### PR TITLE
Bump Android SDK 34 + AGP 8.1

### PR DESCRIPTION
**Pull request by joseluismarti**
## Description
Bump Android SDK to API level 34. I've reviewed the new features and in principle no changes to the code are needed.

Upgrade Android Gradle Plugin (AGP) to the current stable version.

JDK 17 is now required to run from AGP 8.0 onwards.

It may be necessary to manually upgrade the JDK version from 11 to 17 on Android dockers, most likely version 17 will be the `default-jdk` package, otherwise use `openjdk-17-jdk`.

## How has this been tested?
Builds without issue with the upgrade to JDK 17, AGP 8 and SDK 34.

Runtime-tested on Android TV 9.

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by joseluismarti** [comment]
Depends on manually upgrading the JDK package installed on Android dockers from version 11 to 17

**Comment by fuzzard** [comment]
This will probably sit for a while. More about confirming compatibility and upgrading all Jenkins builders with jdk 17

**Comment by joseluismarti** [comment]
@fuzzard @wsnipex update to JDK 17 is pending in the Jenkins builds. I think we should do it at least for Android builders.

If we want to bump to Android SDK 34, it's necessary to update the Gradle plugin to version 8.0 and this depends on JDK 17.

**Comment by wsnipex** [comment]
android builders updated with jdk 17

**Comment by joseluismarti** [comment]
Jenkins build this please

**Comment by joseluismarti** [comment]
Sorry, if someone can add the tags, thanks

**Comment by sundermann** [comment]
Is this planned to go in for Omega?

**Comment by joseluismarti** [comment]
for v22 "P"

**Pull request merged**
