### PR TITLE
[cmake] linux: replace custom (sudo) install target, it's not allowed…

### LINKED ISSUE #16859: regression: startup action 'Play TV' is not performed on wakeup from suspend
### Describe the bug

Startup action 'Play TV' now only performed on Kodi startup.
The action is not performed on wakeup from suspend, as it was in Kodi 17.

Possible regression: https://github.com/xbmc/xbmc/pull/12548
@xhaggi
## Expected Behavior

Startup action 'Play TV' should be performed on both Kodi startup and system wakeup from suspend. Such behavior was in Kodi 17.

## Actual Behavior

Startup action 'Play TV' is only performed on Kodi startup.

### To Reproduce

1. Switch on the 'Play TV' startup action, screenshot is below.
2. Put system to suspend.
3. Wakeup the system. Note the TV is not started.

### Debuglog

http://ix.io/20CJ

### Screenshots 
Switch on the 'Play TV' startup action:

image

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: CoreELEC
 - Kodi version: Kodi (18.4 Git:e95dc442265375aa0cd75284eeaf70ad99b04862). Platform: Linux ARM 32-bit

### PR DESCRIPTION
**Pull request by wsnipex**
… anymore in cmake 3
fixes #16859

It isn't perfect, since cmake >=3 has restrictions on custom targets, but it should get the job done

@fetzerch @hudokkow @notspiff

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build addons please

**Comment by hudokkow** [comment]
Code looks good.
Seems jenkins got stuck...

jenkins build this with addons please

**Comment by wsnipex** [comment]
jenkins build this with addons please

**Comment by wsnipex** [comment]
jenkins build here: http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-All/1588/

**Pull request merged**
