### PR TITLE
[Re-Touched] update for isengard

### PR DESCRIPTION
**Pull request by ronie**
bugfixes + language update.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
wasn't it already pushed to repo?

**Comment by ronie** [comment]
can't remember, i'll double check :-)

**Comment by MartijnKaijser** [comment]
nope
12bf4b8786797a71b8f034f4481ad25009399b43
4.0.4 was last version

**Comment by ronie** [comment]
updated.

**Comment by MartijnKaijser** [comment]
might as well update master as well and then branch re-touched?

**Pull request merged**
