### PR TITLE
[JSON-RPC]Add "art" parameter to audio library Get and Set methods

### PR DESCRIPTION
**Pull request by DaveTBlake**
Add "art" parameter to audio library Get and Set methods. Both get and set any type of artwork for each media type (artists, albums and songs).

Requested numerous times, this brings the functionality inline with that of the video library. For example see  https://forum.kodi.tv/showthread.php?tid=324170
A test version is available on the mirrors

@Montellese sorry to bother you again, but this one is more straight forwards.

Interface addition, hence minor version bump to 9.1.0

### CODE REVIEW

**Comment by rmrector** [comment]
Thanks Dave! After some testing this looks good, but uncovers some troubles with the music thumb loader (which also affects skins), and I think I've narrowed it down to `CMusicThumbLoader::FillLibraryArt`.

One, album art is not grabbed for songs if the song has any of its own artwork. Two, only 'fanart' is grabbed from artists and album artists for songs and albums. Both should be simple to fix, but artist artwork needs cached like album art, which needs something like `getArtistId` and `getAlbumArtistId` on the infotag, and I'm just not sure how to get that info.

**Comment by ronie** [comment]
would like to get this one in.

tested and works ok for me.

**Comment by DaveTBlake** [comment]
Thanks for testing @ronie,  I would like it merged too. 

I have been waiting approveal from @Montellese of JSON API syntax, but I fear he is too busy with real life. It follows all the API principles he has previous set out, so after a month is the team prepared to trust my competence  and merge without that?

**Comment by ronie** [comment]
thx!

**Comment by MartijnKaijser** [comment]
@DaveTBlake you made a new best friend now since ronie wanted this since i joined the team :P

**Pull request merged**
