### PR TITLE
Set content type music

### PR DESCRIPTION
**Pull request by razzeee**
Make sure the node type is correct. Before this NODE_TYPE_NONE would be the only one showing up in getting processed by the if in `CGUIWindowMusicNav::GetDirectory`

This should lead to the content being set correctly in the music libaray.
@phil65

### CODE REVIEW

**Comment by phil65** [comment]
seems to work after a quick test. Thx! You have an idea since when this is borked? (in other words: does it need backporting?)

**Comment by Razzeee** [comment]
I would guess since https://github.com/xbmc/xbmc/commit/a6ab9685b9904df1f5c5f8ea7bef623f3cc61c89
@mkortstiege

**Comment by mkortstiege** [comment]
@Montellese please check when you get the time.

**Comment by Montellese** [comment]
Should be fine. It's always tricky to get the proper path in `GetDirectory()`:-/

**Pull request merged**
