### PR TITLE
Master imx6 stereo modes

### PR DESCRIPTION
**Pull request by mk01**

### CODE REVIEW

**Comment by fritsch** [comment]
@koying for review please

**Comment by koying** [comment]
I confirm the issue, but I can't see how this would fix it. Has it be tested? 
Very surely a rendering issue because of special rects of 3d

**Comment by fritsch** [comment]
I will test this tonight - did not find time yesterday, from the change, from the code I wondered - as I had thought of some x shift, but that part of the code is not that obvious anyways.

@koying if you are running on IMX anyways, you can be faster than me ;-)

**Comment by koying** [comment]
Yeah, don't bother, surely doesn't fix it ;) This code block is just for codecs which invert top & bottom due to being upside-down.
I'll fix it this WE, while working on MVC...

**Comment by sraue** [comment]
@fritsch @mk01 FYI only: it dont fixes https://github.com/OpenELEC/OpenELEC.tv/issues/4098

**Comment by fritsch** [comment]
@sraue Jep - that's clear from the code - I thought it fixes something else at least as it was there before - will wait for @koying or let's see if @mk01 has another idea.

**Comment by mk01** [comment]
@fritsch 

the commit is from 13.2 imx6 rendering flow. sure it can't fix anything now. :-/
;)

**Pull request closed without merging**
