### PR TITLE
fixed: store created stream in member

### PR DESCRIPTION
**Pull request by notspiff**
I think this is what is intended.

### CODE REVIEW

**Comment by FernetMenta** [comment]
that was done by  @AchimTuran and is imo long outdated and not used in current state

**Comment by notspiff** [comment]
So then we keep it broken?

**Comment by AchimTuran** [comment]
Thx for the fix. 

@fernetmenta
Can we merge this?

**Comment by AchimTuran** [comment]
@notspiff
I know you already provided this fix some time ago and I also had a fix. But somehow they never went in. Thank you again for having an eye on it and for providing this fix again.

**Pull request merged**
