### PR TITLE
[pvr] Helix: bump PVR addons

### PR DESCRIPTION
**Pull request by Jalle19**
@opdenkamp your button

@MartijnKaijser @topfs2 this includes a set of recently backported fixes for various addons

### CODE REVIEW

**Comment by opdenkamp** [comment]
jenkins build this please. i'm not touching the helix branch, that's for the RMs

**Comment by MartijnKaijser** [comment]
No problem for me

**Comment by Jalle19** [comment]
Jenkins failure most likely unrelated. Don't know about the Android error though.

**Comment by opdenkamp** [comment]
android is unrelated, something with python.
```
checking if /usr/bin/gcc static flag -static works... libpython2.6.a(pythonrun.o): In function `PyParser_ASTFromString':
/home/jenkins/workspace/Android-ARM/tools/depends/native/python26-native/x86_64-linux-gnu-native/Python/pythonrun.c:1433: undefined reference to `_PyParser_Grammar'
/home/jenkins/workspace/Android-ARM/tools/depends/native/python26-native/x86_64-linux-gnu-native/Python/pythonrun.c:1433: undefined reference to `_PyParser_Grammar'
libpython2.6.a(pythonrun.o): In function `PyParser_ASTFromFile':
/home/jenkins/workspace/Android-ARM/tools/depends/native/python26-native/x86_64-linux-gnu-native/Python/pythonrun.c:1462: undefined reference to `_PyParser_Grammar'
/home/jenkins/workspace/Android-ARM/tools/depends/native/python26-native/x86_64-linux-gnu-native/Python/pythonrun.c:1462: undefined reference to `_PyParser_Grammar'
libpython2.6.a(pythonrun.o): In function `PyParser_SimpleParseFileFlags':
/home/jenkins/workspace/Android-ARM/tools/depends/native/python26-native/x86_64-linux-gnu-native/Python/pythonrun.c:1488: undefined reference to `_PyParser_Grammar'
libpython2.6.a(pythonrun.o):/home/jenkins/workspace/Android-ARM/tools/depends/native/python26-native/x86_64-linux-gnu-native/Python/pythonrun.c:1502: more undefined references to `_PyParser_Grammar' follow
collect2: ld returned 1 exit status
make[3]: *** [python] Error 1
```

let's try again. jenkins build and merge

**Comment by Memphiz** [comment]
@karlson2k - we have a strange problem on the windows build slave.  This is what it should download as zlib package:

https://github.com/xbmc/xbmc/blob/master/project/BuildDependencies/scripts/zlib_d.txt

But jenkins somehow has this in its workspace sometimes:

zlib-vc100-1.2.5-lib.tar.bz2

I have no clue how this could happen - thats the first problem. The second problem now is that this archive wasn't properly downloaded on the slave - thats why it fails to build because it couldn't be extracted. (wiped the workspace once more in the hope that the win32 buildslave has no network issues anymore).

Could we add some sort of md5 check to identify broken downloads for windows packages?

**Comment by notspiff** [comment]
if you move win32 depends to the cmake system montellese put together that is built in... (including retries). /runs

**Comment by Karlson2k** [comment]
@Memphiz We can merge https://github.com/Karlson2k/xbmc/commit/36ebb472e88d99764dcb134c959f428f8cf907ca and repack zlib as "formed package".

**Comment by Memphiz** [comment]
@Karlson2k yes that would be good. At the and we should repack all packages i guess ;)

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by Jalle19** [comment]
Might wanna wait a while yet before merging this, we already have https://github.com/opdenkamp/xbmc-pvr-addons/pull/420 and most likely there will be something else last minute.

**Comment by scarecrow420** [comment]
yeah if we can get opdenkamp/xbmc-pvr-addons#420 in that would be great.  That is the last pvr.wmc helix issue that we are aware of.  Thanks

**Comment by sub3** [comment]
I'd also like https://github.com/opdenkamp/xbmc-pvr-addons/pull/418 to be included in 14.1. It should also be the last pvr.nextpvr change for helix.

**Comment by Jalle19** [comment]
@scarecrow420 @sub3 your changes will be included now.

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Comment by Memphiz** [comment]
@Karlson2k fyi - i am about to repackage all packages to the current package format "formed package" ...

**Comment by Karlson2k** [comment]
@Memphiz, OK, that's great.

**Pull request merged**
