### PR TITLE
tools/depends: improve download retry logic and add download target

### PR DESCRIPTION
**Pull request by lrusak**
This is an attempt to improve the download retry logic and simplify the `download-files.include`. I'm not sure if these changes are portable so we will find out from jenkins.

Basically this changes to always use the download loop for all downloads. This allows us to check the hash of the downloaded file before creating the hashfile. This allows us to print the expected hash vs the found hash in case there is a mismatch. This is helpful when updating the library.

For example:
```
make: Entering directory '/home/lukas/Documents/git/xbmc/tools/depends/target/dav1d'
download dav1d-1.0.0.tar.bz2 attempt 1
Error: failed to verify hash sum of dav1d-1.0.0.tar.bz2
Expected type   : sha512
Found value     : 86c6481e787fb6b8c28521e1efb1876d1be99f5fa5332cddab1111059b44775e05203cfc5c80a1b404ee00f35a1f5e1099e21b1f0851d77fb0101567e8b1a892
Expected value  : 26a06b572c0e4c9685743bd2d2162ac7dcd74b9324624cc3f3ef5b154c0cee7c52a04b77cdc184245d2d6ae38dfdcc4fd66001c318aa8ca001d2bf1d85d66a89
retrying..
download dav1d-1.0.0.tar.bz2 attempt 2
Error: failed to verify hash sum of dav1d-1.0.0.tar.bz2
Expected type   : sha512
Found value     : 86c6481e787fb6b8c28521e1efb1876d1be99f5fa5332cddab1111059b44775e05203cfc5c80a1b404ee00f35a1f5e1099e21b1f0851d77fb0101567e8b1a892
Expected value  : 26a06b572c0e4c9685743bd2d2162ac7dcd74b9324624cc3f3ef5b154c0cee7c52a04b77cdc184245d2d6ae38dfdcc4fd66001c318aa8ca001d2bf1d85d66a89
retrying..
download dav1d-1.0.0.tar.bz2 attempt 3
Error: failed to verify hash sum of dav1d-1.0.0.tar.bz2
Expected type   : sha512
Found value     : 86c6481e787fb6b8c28521e1efb1876d1be99f5fa5332cddab1111059b44775e05203cfc5c80a1b404ee00f35a1f5e1099e21b1f0851d77fb0101567e8b1a892
Expected value  : 26a06b572c0e4c9685743bd2d2162ac7dcd74b9324624cc3f3ef5b154c0cee7c52a04b77cdc184245d2d6ae38dfdcc4fd66001c318aa8ca001d2bf1d85d66a89
make: *** [../../download-files.include:25: /home/lukas/Documents/xbmc-depends/xbmc-tarballs/dav1d-1.0.0.tar.bz2.sha512] Error 1
```

This also makes it required to have the `sha512sum` host tool which I'm not sure is on all our builders.

This also unifies the `RETRIEVE_TOOL_FLAGS` and makes them consistent.

This also allows downloading a url that doesn't follow the regular pattern (see github). By adding a `FULL_URL` variable you can specify the full url and it will download according to our typical archiving (<libname>-<version>.<extension>).

This also adds a `download` target that allows one to download all the packages before building. Unfortunately it's just single threaded but that's ok for now.
```
$ make download

make -C native download
make[1]: Entering directory '/home/lukas/Documents/git/xbmc/tools/depends/native'
make[2]: Entering directory '/home/lukas/Documents/git/xbmc/tools/depends/native/autoconf'
download autoconf-2.71.tar.xz attempt 1
make[2]: Leaving directory '/home/lukas/Documents/git/xbmc/tools/depends/native/autoconf'
make[2]: Entering directory '/home/lukas/Documents/git/xbmc/tools/depends/native/autoconf-archive'
download autoconf-archive-2021.02.19.tar.xz attempt 1
make[2]: Leaving directory '/home/lukas/Documents/git/xbmc/tools/depends/native/autoconf-archive'
make[2]: Entering directory '/home/lukas/Documents/git/xbmc/tools/depends/native/automake'
download automake-1.16.5.tar.xz attempt 1
make[2]: Leaving directory '/home/lukas/Documents/git/xbmc/tools/depends/native/automake'
make[2]: Entering directory '/home/lukas/Documents/git/xbmc/tools/depends/native/cmake'
download cmake-3.21.3.tar.gz attempt 1
<snip>
```

### CODE REVIEW

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
why is such an intrusive change merged without proper testing?
Fyi, this also breaks ppa packaging

**Comment by fuzzard** [comment]
I'll try have a look at those failures on the weekend if @lrusak doesnt have time.

Was merged as it had been built a couple of times, and had the almighty green tick. I think its an improvement regarding the output, so i'll see what i can work out. Can you point me to the PPA failure so i can try and avoid that as well.

**Comment by lrusak** [comment]
> why is such an intrusive change merged without proper testing?
> 
> Fyi, this also breaks ppa packaging

Green means ok to merge.

Can you give more context to your problem? Seems like a posix sh vs dash problem?

**Pull request merged**
