### PR TITLE
[cmake] require OpenSSL >= 1.1.0

### PR DESCRIPTION
**Pull request by lrusak**
This bumps the minimum allowed OpenSSL version to 1.1.0 or greater.

This allows us to get rid of the `CryptThreadingInitializer` class that was used to make OpenSSL usage thread-safe.

We currently have the following versions of OpenSSL:
`1.1.0h` depends
`1.1.1d` windows depends
`1.1.0g` Ubuntu 18.04 release
`1.1.1` Ubuntu 18.04 updates
`1.0.2g` Ubuntu 16.04 updates

This would drop support for Ubuntu 16.04 LTS (which is EOL (standard support) in April 2021 anyways).

I believe we didn't even release Kodi 19.0 for Ubuntu 16.04 anyways.

refs:
1) https://curl.se/libcurl/c/threadsafe.html
2) https://www.openssl.org/docs/man1.1.0/man3/CRYPTO_THREAD_run_once.html#DESCRIPTION
3) https://www.openssl.org/blog/blog/2017/02/21/threads/
4) https://wiki.ubuntu.com/Releases
5) https://ubuntu.com/about/release-cycle

### CODE REVIEW

**Comment by yol** [comment]
What about the file in tests?

**Comment by lrusak** [comment]
> What about the file in tests?

I don't know what you're talking about 😉

**Comment by wsnipex** [comment]
https://github.com/xbmc/xbmc/blob/master/xbmc/filesystem/DllLibCurl.cpp#L115-L124 should probably be removed as well

**Comment by lrusak** [comment]
> https://github.com/xbmc/xbmc/blob/master/xbmc/filesystem/DllLibCurl.cpp#L115-L124 should probably be removed as well

good catch, I'm surprised those weren't guarded by openssl version 😕

**Review by wsnipex — APPROVED** [review]

**Review by yol — APPROVED** [review]

**Pull request merged**
