### PR TITLE
dvdplayer: fix non DVB subs after 5c0d694fa769f311bc5e14dec04c260267a…

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

@ace20022 @jspdr does this fix the issue

@Jalle19 could you test if 1080i still works with this patch?

### CODE REVIEW

**Comment by stefansaraev** [comment]
jenkins build this please

**Comment by Jalle19** [comment]
@stefansaraev did you test this? I haven't had time yet.

**Comment by stefansaraev** [comment]
@Jalle19 I did. dvb and non dvb subtitles are good here. I didnt have any issues after 5c0d694fa769f311bc5e14dec04c260267a btw.

**Comment by jpsdr** [comment]
Is there any build i can test with ?

**Comment by ace20022** [comment]
@jpsdr http://mirrors.xbmc.org/test-builds/win32/KodiSetup-20150926-6597f98-subfix.exe

**Comment by jpsdr** [comment]
Tested, sub issue is fixed. Check also all my no-regression test files, they all pass Ok.

**Comment by FernetMenta** [comment]
thanks

**Pull request merged**
