### PR TITLE
[guiinfo] Fix fallback handling for 'offset' and 'position' info labels.

### PR DESCRIPTION
**Pull request by ksooo**
Fixes a regression introduced by #18630 - details https://github.com/xbmc/xbmc/pull/18630#issuecomment-770395824 ff.

@jjd-uk could you please runtime-test?

### CODE REVIEW

**Review by phunkyfish — COMMENTED** [review]
LGTM

**Review by phunkyfish — APPROVED** [review]
Whoops, meant to approve.

**Comment by phunkyfish** [comment]
jenkins build this please

**Comment by jjd-uk** [comment]
Thanks @ksooo confirmed everything now appears to be behaving as it should.

Tested with 3 item Video and Music Playlists

image

image

When there's 1 or more items in left to play from playlist the offset labels return correctly for the **Next** item info

image

image

When there's no more items left to play from the playlist, in other words the last item in playlist is playing, then the offset labels don't return anything, so again correct behaviour so there is no **Next** item info displayed.

image

image

**Review by jjd-uk — APPROVED** [review]

**Pull request merged**
