### PR TITLE
[cmake] fix package-addon (zip) target on linux

### PR DESCRIPTION
**Pull request by wsnipex**
Zip packaging on linux is broken, probably for a long time now.

@Montellese can you please check if this is ok for win32 or if I need to special case the change in CMakeLists

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build with addons please

**Comment by Montellese** [comment]
Still seems to be working on win32.

**Comment by wsnipex** [comment]
jenkins build this please with addons

**Comment by wsnipex** [comment]
@Memphiz the jenkins job for building with addons seems broken. It didn't even build depends :)

**Comment by Memphiz** [comment]
huh? why does it look to me like it worked then?

**Comment by wsnipex** [comment]
hmmz, I looked at the output while building and it seemed to have started directly with kodi. Maybe I'm blind, sorry for the noise.

**Pull request merged**
