### PR TITLE
[backport][macos] codesign addon's binaries when they are to be cpack'd

### LINKED ISSUE #17244: Audio visualizations broken in Kodi 18.5 on macOS
### Describe the bug
Here is a clear and concise description of what the problem is:

After updating to Kodi on macOS to Leia 18.5, Spectrum and ProjectM visualizers stopped working.  I have not tried any others but suspect they are all broken.

Message boxes appear saying that starting visualization failed.

The log reveals that the system would not load the visualizers' .dylibs because the .dylibs  are completely unsigned but the Kodi process is using library validation. It is using validation because Kodi 18.5 has been signed and notarized (for which a big thanks to the Kodi team) and is using the macOS hardened runtime.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Visualization should continue to run as it  did in Kodi 18.4

## Actual Behavior

Instead of visualization running message boxes appear saying that starting visualization failed.

## Possible Fix

Sign the visualizers' .dylibs. An ad-hoc signature may be sufficient.

### To Reproduce

1.  Install Kodi 18.5 on macOS 10.14.5+ or 10.15
2. Install ProjectM visualizer
3. Play some music
4. Go to the full-screen music display.
5. Set ProjectM as the visualizer.
6. Press backspace to return to previous screen.

Step 6 may not be necessary. An error message box may show up at step 5.

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/cunerazapa.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS 10.14.6
 - Kodi version: 18.5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by kambala-decapitator**
## Motivation and Context
With code signed Kodi app (existing releases were signed and re-uploaded in #17178) it's impossible to load unsigned binary addons that are not bundled with the app. Fixes #17244.

Backport of #17269.

### CODE REVIEW

**Comment by kambala-decapitator** [comment]
WIP because Jenkins isn't yet setup to perform code signing as well as the cmake change isn't final because I don't know yet the exact command that Jenkins executes when building single addons (most probably it should be edited to pass the signing identity as a param)

**Comment by Rechi** [comment]
As always first create the master PR, once that is accepted, the backport can be reconsidered.

**Comment by kambala-decapitator** [comment]
> As always first create the master PR, once that is accepted, the backport can be reconsidered.

the situation is different here: Leia releases are already code signed and they can no longer load unsigned binary addons, while master releases aren't signed yet. That's why Leia must be fixed first. Or still create a master PR first?

**Comment by Rechi** [comment]
I know the situation, still fix the code first in master. It will be required too and getting it into master as soon as possible may reduce the number of Matrix add-ons which have to be re-released just to get them signed.
For the Leia versions you'll have to re-release every add-on anyway, so there is no reason to not follow the master backport strategy.

**Pull request closed without merging**
