### PR TITLE
disable debug in depends in Release builds

### PR DESCRIPTION
**Pull request by wsnipex**
as discussed on slack, should fix ugly asserts (e.g. in pil) in Release builds

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
Thank you for fixing this, can't really say much about the actual changes.

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
Triggered release build to test as well
http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-All/1672/

**Comment by MartijnKaijser** [comment]
@wsnipex it runs fine on aarch64

**Comment by wsnipex** [comment]
thanks for testing

**Pull request merged**
