### PR TITLE
[dx11] Fixed displaying GUI in limited color range.

### PR DESCRIPTION
**Pull request by afedchin**
This returns dx9 behavior which was broken during porting to dx11.

### CODE REVIEW

**Comment by afedchin** [comment]
jenkins build this please

**Comment by afedchin** [comment]
jenkins build this please

**Comment by afedchin** [comment]
rebased and squashed.
jenkins build this please

**Comment by mkortstiege** [comment]
Is this one good to go?

**Comment by afedchin** [comment]
Yes, has positive feedback from testers

-----Original Message-----

**Pull request merged**
