### PR TITLE
Addons API - Added dump methods for live streams

### PR DESCRIPTION
**Pull request by rkubera**
New methods for Addons API:

-GetStreamPlaylist
-OpenStream
-ReadStream
-CloseStream 

This methods are needed for live stream recording (eg. using PVR IPTVSimple addon - under development - test phase ) and deep stream buffering.

### CODE REVIEW

**Comment by fritsch** [comment]
I am fully not sure if we "are allowed" to want this at this very moment. This would "simplify" piracy a whole lot even more, cause iptv simple users with illegal content, would now also start to record this content ontop.

Technically there is absolutely nothing wrong with that change. But in the current situation we probably need "legal" advice.

@MartijnKaijser @natethomas

**Comment by FernetMenta** [comment]
> Technically there is absolutely nothing wrong with that change

I don't agree. DVDInput stream has no API designed to be exposed to addons. bye bye architecture if this goes in.

**Comment by fritsch** [comment]
@FernetMenta "Technically" was meant as: From a technical pov there is nothing wrong with wanting to have dump, read, whatever functionality. I did not review the code at all.

But yes, if we have an architecture breakage even "better" in these times :-)

**Comment by natethomas** [comment]
Well there you go. Technical problems mean we don't have to deal with the moral or legal ones. Hi five to @FernetMenta. :)

**Comment by Jalle19** [comment]
There is already Open/CloseLiveStream that addons can use to implement recording and timeshifting.

**Comment by rkubera** [comment]
@Jalle19 can you please point me to such addon which implements RTMP and chunks streams Open/CloseLiveStream?
From the "legal" perspective public or own streams can be viewed/downloaded (it may depend on country, but in Poland it is legal). Illegal is sharing streams, but this API has no methods for stream sharing. Today is not a problem to download live streams using VLC and other legal software.

Architecture will be OK if DVDInputStreams can be accessible like other components (like EPG, PVR...). DVDInputStreams are hidden under DVDPlayer and I think this is architecture issue. We can of course wait for architecture changes, but KODI will be pushed to margin.

**Comment by afedchin** [comment]
@rkubera, @Jalle19 means PVR addons.

**Comment by rkubera** [comment]
@afedchin PVR provides only interfaces for stream operations using DVDPlayer, but no interface to get streams. My API is open, not closed to PVR only. It is possible to buffer radio/video streams - allows deep time shift operations (using custom cache mode). Till now it was not possible.

**Comment by afedchin** [comment]
@rkubera currently, pvr addons can handle streams and provide data to the DVDPlayer. No need new methods for timeshift or better caching, pvr addons can do it already. Your changes flips  upside down interaction pvr addons with DVDPlayer.

**Comment by rkubera** [comment]
@afedchin tt's thue, but PVR  deliver functions like:
- SeekLiveStream
- PositionLiveStream
- ReadLiveStream 
that returns buffer to stream from phisical device.
If you operate on live streams, you need access to RTMP library (and others) to deliver this buffer. My API deliver this functionality.

**Comment by FernetMenta** [comment]
any further discussion here is useless. there is hardly any design rule not violated by this code here. please be reasonable. you export a DVDInputStream object as void pointer. an addon which uses this needs to include a lot of internal headers. almost every change to Kodi's code would break the addon, result into segfault. this has not much in common with an addon

**Comment by rkubera** [comment]
@FernetMenta  it is not true.
There is example howto use this functions:
void *stream = XBMC->OpenStream(t_currentChannel.strStreamURL.c_str()); 
char buffer[1024];
if (stream)
{
     int bytes_read = XBMC->ReadStream(stream,buffer,1024);
      while(bytes_read>=0)
       {
          ......
       }

   XBMC->CloseStream(stream);
}
No need any includes in addon.

It is identical methods like XBMC->OpenFile. XBMC->ReadFile and XBMC->CloseFile (with void pointers, see core source code).

Regards,
Radek.

**Comment by FernetMenta** [comment]
> XBMC->OpenFile. XBMC->ReadFile and XBMC->CloseFile

those are not ok either. only because those things managed it to creep in does not mean it is good

**Comment by rkubera** [comment]
Ok @FernetMenta, what kind of methods and architecture you propse?
Now everything is wrong ;)

**Comment by FernetMenta** [comment]
An API needs to be designed as such considering i.e. thread safety, reentrency, etc. Then it can be exposed for addons as an extension point with a version.

**Comment by rkubera** [comment]
@FernetMenta my methods are the same thread safety, reentrency, etc. like other methods shared by actual API. No risk increase.

From two months i'm testing my API (on two platforms) without any problems like segfault or other issues.

**Comment by fritsch** [comment]
@rkubera the point here is: kodi's architecture was designed once and has lived for many years. During these years features were added here, there and here again, a bit here a bit there together with a bit clue, more clue, a lot of clue. We need to redesign parts of it or kodi will just die ... slowly ... in that process it's not a solution to extend a nonsense API so that it even more code needs to be rewritten later on.

Though your point again is right, you don't do anything else as "all others" have done before. But as a sw developer, I think you understand, that something needs to be done. If you want to help us with that, highly welcome.

**Comment by rkubera** [comment]
Hi,
Thak you for your invite, I'd love to help in Kodi development. Now I'm working on better Kodi understanding.

Today I've created this new functionality, which I would like to share with people - this is main opensource idea.
Becouse I've spent a lot of time on this functionality, I'd like to finish this task. In next steps I'd like to help in architecture governance.

I would not want you to push, but please tell me if this code change will be accepted or not.

regards,
Radek

**Comment by fritsch** [comment]
This change won't be accepted. As I see no point in integrating API functionality via the given interface, that we perhaps could not maintain like that after the rewrite. Therefore that would need a lot of 3rd party applications to redo this functionality completely.

@FernetMenta anything to add?

**Comment by FernetMenta** [comment]
@rkubera when I was talking about thread safety and those things, I was not referring to your code but to DVDInputStream which has not been designed to be exposed to externals. Unfortunately we already have too many similar situations which results in unmaintainable code. Once a function got exposed and an issue was reported there will be another quick fix and another and so on.
You see the folder DVDInputStream is located under dvdplayer. Means that it was not meant to be used by any other component than dvdplayer.

**Comment by rkubera** [comment]
Ok, thank you all comments.

**Pull request closed without merging**
