### PR TITLE
Remove a useless join in season_view

### PR DESCRIPTION
**Pull request by phate89**
If I' not wrong in season_view you already have playcount in episode_view. No need to join again files table to get it

### CODE REVIEW

**Comment by Razzeee** [comment]
Good catch, thank you!

**Comment by MartijnKaijser** [comment]
@mkortstiege for ok as well. Still in time I guess for v16 else delay?

**Comment by phate89** [comment]
I updated the pr. There was no need to use episode_view since we need only files and episode tables so I put back the files join and replaced episode_view with episode.
Should be faster now..

**Comment by Montellese** [comment]
Should be good.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
