### PR TITLE
[Music] Smart playlists - allow song lists to be grouped into albums

### PR DESCRIPTION
**Pull request by the-black-eagle**
## Description
As per the title, this small addition allows smart playlists to group the songs from a song type playlist into their respective albums.

## Motivation and Context
Currently, the only way to achieve this functionality is by converting a smart playlist into a node and adding `<group>albums</group>` to it.  However, many users won't know that this is even possible and/or how to do it.  This addition will, for instance, allow you to list all your flac albums by using a rule of `file endswith flac` and grouping by album.  Without the grouping applied it's just a long list of songs which although correct, makes it difficult to find a specific album and play it.

## How Has This Been Tested?
Tested locally on a fresh build with various playlist rules for selecting songs.

## Screenshots (if appropriate):
file endswith flac (no grouping) - 1471 tracks
<a href="https://ibb.co/SKvY9My">screenshot161</a>

with grouping by album applied - 64 albums
<a href="https://ibb.co/jhfhXY6">screenshot162</a>
## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by DaveTBlake** [comment]
I know adding a grouping looks like a trivial change, but it will fall apart with some combinations of smart playlist rules. The way grouping is turned into SQL the music needs to be changed before this can be done, and that is part of a WIP I would be actively working on except I am busy with bug fixes. So please keep out of this bit of the sand pit :)

**Review by DaveTBlake — CHANGES_REQUESTED** [review]
I know adding a grouping looks like a trivial change, but it will fall apart with some combinations of smart playlist rules. The way grouping is turned into SQL the music needs to be changed before this can be done, and that is part of a WIP I would be actively working on except I am busy with bug fixes. So please keep out of this bit of the sand pit :)

**Comment by the-black-eagle** [comment]
No worries Dave.  I would have asked you first but didn't think a one-liner would be an issue, so sorry about that.  Would you like me to close this ?

**Comment by DaveTBlake** [comment]
Yes close please to avoid confusion. It looks so innocent, you just picked the wrong one liner :)

**Pull request closed without merging**
