### PR TITLE
make sure not to delete a CThread object while spawn thread is in pro…

### PR DESCRIPTION
**Pull request by FernetMenta**
should fix CEvent sefaults

### CODE REVIEW

**Comment by FernetMenta** [comment]
@Rechi not after https://github.com/xbmc/xbmc/pull/13721

**Comment by Rechi** [comment]
What would you do, merge this for now or bring #13721 into a good shape so it can be merged soon?

**Comment by FernetMenta** [comment]
I hope Jim finds time to finish #13721

**Comment by ksooo** [comment]
> I hope Jim finds time to finish #13721

 Seems not to be the case any time soon, according to what he wrote in #13721.

 Suffering from the segfaults fixed by this PR, I suggest to merge it now.

**Pull request merged**
