### PR TITLE
DVDVideoCodecAndroidMediaCodec: Revert c15ff2d9f6e - to accelerate dvds

### PR DESCRIPTION
**Pull request by fritsch**
Happy regression testing. Was demanded by users here: https://forum.kodi.tv/showthread.php?tid=332945&page=4

From technical pov stills and dvds are nowadays a solved problem on most platforms. Let's see how we regress.

### CODE REVIEW

**Review by peak3d — APPROVED** [review]

**Comment by MartijnKaijser** [comment]
Can the commit message be extended a bit with why?

**Comment by fritsch** [comment]
Extended commit message.

**Comment by FernetMenta** [comment]
Are you sure media codec supports drain properly? If this is not the case many dvd menus won't work. Note that there are many variants of dvd menus. Did anybody test any of them with this change?

**Comment by FernetMenta** [comment]
Are you sure media codec supports drain properly? If this is not the case many dvd menus won't work. Note that there are many variants of dvd menus. Did anybody test any of them with this change?

**Comment by FernetMenta** [comment]
Are you sure media codec supports drain properly? If this is not the case many dvd menus won't work. Note that there are many variants of dvd menus. Did anybody test any of them with this change?

**Comment by FernetMenta** [comment]
Are you sure media codec supports drain properly? If this is not the case many dvd menus won't work. Note that there are many variants of dvd menus. Did anybody test any of them with this change?

**Comment by FernetMenta** [comment]
Are you sure media codec supports drain properly? If this is not the case many dvd menus won't work. Note that there are many variants of dvd menus. Did anybody test any of them with this change?

**Comment by FernetMenta** [comment]
Are you sure media codec supports drain properly? If this is not the case many dvd menus won't work. Note that there are many variants of dvd menus. Did anybody test any of them with this change?

**Comment by FernetMenta** [comment]
Are you sure media codec supports drain properly? If this is not the case many dvd menus won't work. Note that there are many variants of dvd menus. Did anybody test any of them with this change?

**Comment by FernetMenta** [comment]
Are you sure media codec supports drain properly? If this is not the case many dvd menus won't work. Note that there are many variants of dvd menus. Did anybody test any of them with this change?

**Comment by FernetMenta** [comment]
Are you sure media codec supports drain properly? If this is not the case many dvd menus won't work. Note that there are many variants of dvd menus. Did anybody test any of them with this change?

**Comment by FernetMenta** [comment]
In order to support dvds, a codec needs properly support draining. Is this the case? Note that there are many different kinds of menus. Some have only a single frame that needs to be decoded and displayed. Has anybody tested any dvd menus with this change?

**Comment by FernetMenta** [comment]
In order to support dvds, a codec needs properly support draining. Is this the case? Note that there are many different kinds of menus. Some have only a single frame that needs to be decoded and displayed. Has anybody tested any dvd menus with this change?

**Comment by FernetMenta** [comment]
In order to support dvds, a codec needs properly support draining. Is this the case? Note that there are many different kinds of menus. Some have only a single frame that needs to be decoded and displayed. Has anybody tested any dvd menus with this change?

**Comment by MartijnKaijser** [comment]
Jenkins build this please

**Comment by fritsch** [comment]
Please wait until: https://forum.kodi.tv/showthread.php?tid=332945&pid=2784941#pid2784941 got some replies. We know that we will hit issues.

**Comment by fritsch** [comment]
Closed: https://forum.kodi.tv/showthread.php?tid=332945&pid=2785126#pid2785126

RM is right. Fixing it correctly or not at all.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by peak3d** [comment]
After internal team discussion we decided to merge this and analyze related issues if users run into them.

**Pull request merged**
