### PR TITLE
[pvr][guiinfo][guilib][estuary] PVR timeshift GUI v2.

### PR DESCRIPTION
**Pull request by ksooo**
I found some time to rework the PVR timeshift GUI. The general idea of the new ts progress is always to be able to visualise both the complete ts buffer and the complete playing epg event (if any) side by side with the same time scale. Ts progress start and end times will be calculated accordingly.
  + Start is usually ts buffer start, except if start time of playing epg event is before ts buffer start, then progres start is epg event start.
+ End is usually ts buffer end, except if end time of playing epg event is after ts buffer end, then progres end is epg event end.

Here is how it looks like for some key use cases:

screenshot000
screenshot001
screenshot002

Constructive feedback is welcome.

### CODE REVIEW

**Comment by FernetMenta** [comment]
nice

**Comment by quthla** [comment]
Looking really good. Is it possible that this gets supported by inpustream.adaptive? As at least 2 official Kodi PVR addons rely on this and it would be quite an improvement for the people using these addons.

**Comment by ksooo** [comment]
> Is it possible that this gets supported by inpustream.adaptive?

 Yes, the developer has this on his todo list. ping @peak3d

**Comment by scott967** [comment]
Seems reasonable, but what happens when the currently playing show ends and the next one starts (within the buffer bounds)?

**Comment by ksooo** [comment]
The progress bar adapts, then. Screenshot 3.

**Comment by ksooo** [comment]
In case the screenshots and my description are not clear enough, try a test build.  It's not trivial to describe (for me as I'm not a native English speaker). Getting hands on is far the best way to understand how it behaves.

**Comment by da-anda** [comment]
@ksooo I gave a testbuild a try and will keep testing it for a couple more days before I give a final feedback, but one thing I noticed so far is, that the timeshift buffer bar begins to jump during the transition from one show to the next (while being at the "live" position). I was watching the news the other day, and in the last minute of it's EPG timeframe the wite buffer bar jumped a couple times from "correct position mid stream" to "begin of show". I assume that it's a rounding issue (or something like that) which made the buffer bar think it's already in the next show while UI was still in the "old/current" show.

**Comment by ksooo** [comment]
> that the timeshift buffer bar begins to jump during the transition from one show to the next (while being at the "live" position). I was watching the news the other day, and in the last minute of it's EPG timeframe the white buffer bar jumped a couple times from "correct position mid stream" to "begin of show".

 Thanks for the feedback. Currently I'm more interested in feedback to the general concept. I will start polishing  after I (hopefully) got some positive feedback for the concept.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
@ronie could you take a look at the shin changes? 

@Jalle19 for general code review, please?

**Comment by ksooo** [comment]
@ronie: here comes the documentation for the new guiinfo labels / ints:

screenshot001

Labels:

PVR.TimeshiftProgressDuration
+ Returns the duration of the PVR timeshift progress in the format hh:mm:ss. hh: will be omitted if hours value is zero.

PVR.TimeshiftProgressDuration(format)
+ Returns the duration of the PVR timeshift progress in different formats:
Hours (hh), minutes (mm) or seconds (ss). Also supported: (hh:mm), (mm:ss)\, (hh:mm:ss), (h:mm:ss), (secs), (mins), (hours) for total time values and (m).

PVR.TimeshiftProgressStartTime
+ Returns the start time of the PVR timeshift progress in the format hh:mm:ss. hh: will be omitted if hours value is zero.

PVR.TimeshiftProgressStartTime(format)
+ Returns the start time of the PVR timeshift progress in different formats:
Hours (hh), minutes (mm) or seconds (ss). Also supported: (hh:mm), (mm:ss)\, (hh:mm:ss), (h:mm:ss), (secs), (mins), (hours) for total time values and (m).

PVR.TimeshiftProgressEndTime
+ Returns the end time of the PVR timeshift progress in the format hh:mm:ss. hh: will be omitted if hours value is zero.

PVR.TimeshiftProgressEndTime(format)
+ Returns the end time of the PVR timeshift progress in different formats:
Hours (hh), minutes (mm) or seconds (ss). Also supported: (hh:mm), (mm:ss)\, (hh:mm:ss), (h:mm:ss), (secs), (mins), (hours) for total time values and (m).

Ints:

PVR.TimeshiftProgressPlayPos
+ Returns the percentage of the current play position within the PVR timeshift progress.

PVR.TimeshiftProgressEpgStart
+ Returns the percentage of the start of the currently playing epg event within the PVR timeshift progress.

PVR.TimeshiftProgressEpgEnd
+ Returns the percentage of the end of the currently playing epg event within the PVR timeshift progress.

PVR.TimeshiftProgressBufferStart
+ Returns the percentage of the start of the timeshift buffer within the PVR timeshift progress.

PVR.TimeshiftProgressBufferEnd
+ Returns the percentage of the end of the timeshift buffer within the PVR timeshift progress.

**Review by ronie — APPROVED** [review]
skin changes look good to me.

**Review by Jalle19 — APPROVED** [review]
Couldn't find anything obviously wrong

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Comment by Rantanplan-1** [comment]
Grate!

How ever, i personaly would prefere a "per show (EPG)" aproach, rather than showing the whole Timeshift Buffer. (imho. more intuitive that way.)

So the Progressbar would still cover the current playing show rather than the whole Timeshift Buffer.

Sketch:
[img]https://i.imgur.com/gD40gz4.jpg[/img]

**Comment by ksooo** [comment]
Thanks for the feedback. You guys always provide mockups for one of three essential use cases. In your case, you also need to think how it should look like if the the ts buffer is larger than the playing epg event? 

Regarding streams with no epg: it does exactly what you want. One bar with the rd buffer progress.

**Comment by Rantanplan-1** [comment]
> you also need to think how it should look like if the the ts buffer is larger than the playing epg event

- if the start Time of the ts Buffer is lower than the Start Time of the currently playing Show (EPG) "PVR.TimeshiftStartPos" is Empty (0%)
 -_> so you wouldnt visualy see the start of the Buffer. (How ever if needed it could be shown as Infolabel) -> so everytime "PVR.TimeshiftStartPos" is Empty, you knew the Timeshift start point is in a show before the one you are currently watching._

- if the End Time of the ts Buffer is greather than the End Time of the currently playing show (EPG) "PVR.TimeshiftEndPos" is always full (100%)
 _-> so you would see a fully white Bar which would indicate that the Timeshift End Point would be somewhere in one of the next shows._

**Comment by ksooo** [comment]
Although completely valid, as the requirement for the feature was always to visualise both the complete show and the complete ts buffer, your approach disqualifies, sorry.

**Comment by ksooo** [comment]
However, I think I provided all necessary labels for your approach, so you can implement your approach in your own skin if you like.

**Comment by Rantanplan-1** [comment]
sounds Cool, will give it a try.  Thnks.

**Comment by ksooo** [comment]
@Rantanplan-1 okay, and now let's no longer use this PR to discuss other concepts. For this kind of things, the forum is the right place.

**Comment by Rantanplan-1** [comment]
Sorry,

> Currently I'm more interested in feedback for the general concept

**Comment by ksooo** [comment]
> Just How if all bars relay eighter to the ts buffer start or ts buffer end

 There is also `PVR.EpgEventProgress` which is for the currently playing epg event, if any.

**Pull request merged**
