### PR TITLE
[Estuary] Update addon browser

### PR DESCRIPTION
**Pull request by Hitcher**
## Description

This brings the addon browser more inline with the home screen so you can see there are more items when scrolling through the list.

## Motivation and Context

Requested by @Razzeee

## How Has This Been Tested?

Yes, works as intended.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Razzeee** [comment]
For everybody that doesn't know, way easier to review like this https://github.com/xbmc/xbmc/pull/14650/files?w=1

**Comment by Razzeee** [comment]
Changes look fine to my untrained (non-skinner) eyes.

**Comment by HitcherUK** [comment]
> For everybody that doesn't know, way easier to review like this

I guess it looked like it did because I used the upload file option. How can I avoid that next time?

**Comment by Rechi** [comment]
As expected this file has now windows line endings. So the PR shouldn't be merged in the current state.

If you still want to use the upload file option you have to save the file with unix line endings before uploading it or use git.

**Comment by Razzeee** [comment]
Can you squash the commits down into one commit?

**Review by ronie — APPROVED** [review]

**Comment by HitcherUK** [comment]
> Can you squash the commits down into one commit?

Squash and merge not enabled for this repository.

**Comment by Razzeee** [comment]
@HitcherUK you want to rebase your branch on top of master of this repo and squash your two commits into one.
Then force push to your branch.

**Comment by HitcherUK** [comment]
> @HitcherUK you want to rebase your branch on top of master of this repo and squash your two commits into one.
> Then force push to your branch.

I literally only use Github Desktop.

**Comment by HitcherUK** [comment]
> @HitcherUK you want to rebase your branch on top of master of this repo and squash your two commits into one.
> Then force push to your branch.

I literally only use Github Desktop.

**Comment by HitcherUK** [comment]
> @HitcherUK you want to rebase your branch on top of master of this repo and squash your two commits into one.
> Then force push to your branch.

I literally only use Github Desktop.

**Comment by Razzeee** [comment]
@HitcherUK can you do this?
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

As I fear the discussion to allow squash and merge on this repo will take some time.

**Comment by HitcherUK** [comment]
@Razzeee That's already enabled.

**Comment by HitcherUK** [comment]
@Razzeee shall I just kill this one off and start again?

**Comment by Razzeee** [comment]
sure go ahead

**Comment by HitcherUK** [comment]
Closed. New PR incoming.

**Pull request closed without merging**
