### PR TITLE
[rebrand] ffmpeg extra version xbmc -> kodi

### PR DESCRIPTION
**Pull request by un1versal**
Looking at these for entirely different reason, still none the wiser but these must go.

### CODE REVIEW

**Comment by wsnipex** [comment]
needs adjustment in https://github.com/xbmc/xbmc/blob/master/xbmc/Application.cpp#L709 as well.
Please check that kodi.log doesn't say "WARNING: unsupported ffmpeg version detected" after that.

**Comment by uNiversaI** [comment]
Done as per your suggestion. See no errors in there http://pastebin.com/8rMkt4gK

I do however have 

```
10:30:52 T:140071949105024  NOTICE: FFmpeg statically linked, version: 14.0rc3-Helix-854-g8f1c606-Kodi-2.5.2-Isengard-alpha
```

Which i've no idea how a master compile properly cleaned can spew that out, which is what prompted me to look in these files in first place, hence the none the wiser remark.

in any case this part should be good to go.

**Comment by wsnipex** [comment]
this made me curious. The issue is in FFMPEG itself, its version tool tries to read "their" git version, but it reads from kodi's git.
@FernetMenta https://github.com/xbmc/FFmpeg/blob/c5806910918eb9adc3b3a821242cc4bc7647a50f/version.sh Lines 5-25 should go, but this will ofc never be accepted upstream. Maybe they'd be ok with checking if there is a .git dir?

**Comment by uNiversaI** [comment]
Nasty :), thx for that piece of information, nice to know. Its more of a minor annoyance but I was thinking maybe that the ffmpeg version could be shown in skin info > video section at some stage, though as usual not a clew how to go about that atm.

This PR is tested and works as intended btw so over to you ;)

**Comment by uNiversaI** [comment]
rebased on master and resolved merge conflicts.

**Comment by MartijnKaijser** [comment]
fine for merge i guess?

**Comment by uNiversaI** [comment]
@wsnipex 

ffmpeg 2.6 still not right

```
NOTICE: FFmpeg statically linked, version: 2.6-kodi-2.6.0-Isengard-alpha
```
dont know where ***2.6-*** is being prepended from and for what reason. Ive noticed a couple of typos in build.sh but nothing major will fix in a bit.

**Comment by wsnipex** [comment]
its correct and as expected. see https://github.com/xbmc/FFmpeg/pull/3 for the explanation

**Pull request merged**
