### PR TITLE
Appparser

### PR DESCRIPTION
**Pull request by topfs2**
When doing #6373 it was discussed how to clean up the app parsing a bit, and make it more future proof.
And with discussion in http://forum.kodi.tv/showthread.php?tid=217922 I started the cleanup and dropped some, possibly, unnecessary parameters.

### CODE REVIEW

**Comment by topfs2** [comment]
ping @FernetMenta @Montellese to check if the idea is sane
also @sraue if you could check if OpenELEC uses any of the removed parameters (and why).

Note that this needs love for the other platforms, which I can do if we deem this a sane way to move forward with it

**Comment by stefansaraev** [comment]
@topfs2 openelec uses --debug

**Comment by topfs2** [comment]
You use it on release builds too or is it just when doing prereleases (betas and what not)?

**Comment by stefansaraev** [comment]
on release builds, too, yep. to make it easier to collect logs. we just tell our users: touch /storage/.cache/debug.openelec && sync & reboot and share their (crash)logs

**Comment by topfs2** [comment]
Cool cool, I added it back :)

**Comment by FernetMenta** [comment]
looks ok to me. I am wondering if we can make use of getopt_long here (getopt.h), or why do we do the parsing ourselves?

**Comment by topfs2** [comment]
Only reason I can think of is that we use this on all (desktop) platforms. So perhaps its not available on all? Anyways, I think moving to getopt could be done as a seperate PR

**Comment by FernetMenta** [comment]
> I think moving to getopt could be done as a seperate PR

agree

**Comment by Paxxi** [comment]
Looking good except name of class, why name new code xbmc?

**Comment by topfs2** [comment]
I just followed the naming in xbmc.CPP, with XBMC_Run but I didn't like it
either. Will move it out to a separate file and name it AppOptions or
something like that instead :)
Den 15 feb 2015 21:16 skrev "Pär Björklund" <notifications@github.com>:

**Comment by Montellese** [comment]
Looks much better than what we have now.
AFAIK `getopt()` and `getopt_long()` aren't available for win32 but maybe there's a port.

**Comment by topfs2** [comment]
Now when the code is in the correct repo, anything else or should I rebase and schedule it for next merge window?

**Comment by MartijnKaijser** [comment]
fyi: merge windows now end at 20th at midnight ;)

**Comment by topfs2** [comment]
Oh so need to fix this up tonight :)

**Comment by topfs2** [comment]
jenkins build this please

**Comment by topfs2** [comment]
@Montellese did I miss something for Win32? Thought it used the main.cpp as linux?

**Comment by Memphiz** [comment]
https://github.com/xbmc/xbmc/blob/master/xbmc/win32/XBMC_PC.cpp

**Comment by topfs2** [comment]
Wtf, why do we have ifdef windows stuff in main.cpp then :)

**Comment by topfs2** [comment]
Also why does windows use a completely different run than all other
platforms? It doesn't even seem to use xbmc_run. Would love it if a windows
dev could align this
Den 27 feb 2015 21:55 skrev "Tobias Arrskog" <topfs2@kodi.tv>:

> Wtf, why do we have ifdef windows stuff in main.cpp then :)
>

**Comment by FernetMenta** [comment]
> Would love it if a windows dev could align this

+10

**Comment by MartijnKaijser** [comment]
@Paxxi or @Karlson2k ?

**Comment by Paxxi** [comment]
yup I'll look into it tomorrow

**Comment by Karlson2k** [comment]
Good in general.
For win32 it would be nice to re-add support for `-d XX` (delay) option.

**Comment by Paxxi** [comment]
Win32 will require it's own version of DisplayVersion and DisplayHelp for two reasons. There's no console to write to so printf doesn't work and the help message will require different wording and formatting to make any sense. Probably nothing you need to worry about, just a heads up.

**Comment by topfs2** [comment]
The display help feels a bit weird in there to be honest. It makes no sense
on android or iOS either. Perhaps we should move it out to each main file?

**Comment by Paxxi** [comment]
We will need a generic way to report errors during init as well, currently we're calling printf directly in XBMC_Run so I'm thinking maybe create a helper class for displaying messages to the user. I'm thinking along these lines
```C++
class IOutputHelper
{
DisplayHelp();
DisplayMessage(std::string message);
DisplayError(std::string error);
}
```
subclass it for any platform we need and use it in main and pass that along to XBMC_Run.

**Comment by topfs2** [comment]
Just so I follow, is this because windows prompt the message as a window
and not dump to terminal?

Other than that something generic like that would be nice and probably very
welcomed for the other platforms, if we want to dump the message outside
terminals.

Your thinking to make an option to display help for example and let xbmc
run do the display and return when done?
Den 2 mar 2015 16:07 skrev "Pär Björklund" <notifications@github.com>:

**Comment by Paxxi** [comment]
Yes on windows it will open a messagebox both for errors and help. I guess it would do the same on OS X and possibly in Linux depending on how it's launched?

**Comment by topfs2** [comment]
Nah, both Linux and osx spew it out to terminal and nothing else. Both
version and help can only be triggered with command line options so it
doesn't matter if there is GUI or not. But I guess windows can trigger help
and such via GUI? Why would it though?

**Comment by Paxxi** [comment]
if you run kodi.exe --help on windows it will launch with no connection to a terminal  and this can be done from a shortcut, start screen, command prompt.

**Comment by topfs2** [comment]
Well you can do that on Linux to, but why and who uses that :)
Den 3 mar 2015 16:30 skrev "Pär Björklund" <notifications@github.com>:

**Comment by topfs2** [comment]
@Paxxi ping :) Not to pressure you but would love some code so I can start basing the headless code on this (so I can get windows headless up and going).

**Comment by Paxxi** [comment]
Oh, I was waiting for you to finish this before redoing the startup to make use of your code :) I have a working version somewhere so ill clean it up a bit and do a pr

**Pull request closed without merging**
