### PR TITLE
[Omega] 21.0 Release

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Omega 21.0

## Motivation and context
Release time

## How has this been tested?
N/A

## What is the effect on users?
Release

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by zag2me** [comment]
Is the splash screen meant to look like that?

**Comment by bacon-cheeseburger** [comment]
@zag2me Not a fan of that effect at all, and wondered the same. Would much rather prefer just a solid black background instead but not something I'll lose sleep over. Hopefully the next iteration will come with a more appealing splashscreen.

**Review by pospa874 — COMMENTED** [review]
Wasn't supposed to be commit name ` [Omega] 21.0 Release ` instead of ` [Omega] 20.0 Release `?

**Comment by matthuisman** [comment]
@pospa874 at least he got the date right this time hehe

**Comment by matthuisman** [comment]
easter present?

**Comment by Johnny1982fd** [comment]
Christmas present ?

**Pull request merged**
