### PR TITLE
[cmake] check present "CPU" variable on PrepareEnv, if empty use CMAKE_SYSTEM_PROCESSOR

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description
This is necessary to addons outside of "./tools/depends" to e.g. Mac to build because the variable "CPU" can only be given from there at the addon construction.

This is OK for cross platform addon construction like iOS or Android, but very cumbersome for building an addon to the same system (for testing purposes).

This is added:
```
if(NOT CPU)
  set(CPU ${CMAKE_SYSTEM_PROCESSOR})
endif()
```

Without comes:
```
<platform>osx-</platform>
```

With:
```
<platform>osx-x86_64</platform>
```

## How Has This Been Tested?
Addon on Mac by:
```sh
cd visualization.spectrum # Where addon source is
mkdir build
cd build
/Users/Shared/xbmc-depends/x86_64-darwin18.5.0-native/bin/cmake \
   -DADDONS_TO_BUILD=visualization.spectrum \
   -DADDON_SRC_PREFIX=../..  \
   -DCMAKE_BUILD_TYPE=Release  \
   -DCMAKE_INSTALL_PREFIX="$HOME/Library/Application Support/Kodi/addons"  \
   -DPACKAGE_ZIP=1 ../../kodi/cmake/addons
make
```
>Note: In this way, it must be present under `./Cmake/addons/addons` (the content of https://github.com/xbmc/repo-binary-addons, which will be automatically downloaded), or if added subsequently there.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by phunkyfish** [comment]
Just tested this. What a simple solution that will save so much time. Thanks!

Maybe just add a comment so everyone knows why it’s there!

**Review by wsnipex — APPROVED** [review]

**Comment by phunkyfish** [comment]
@AlwinEsch can this be backported to Leia?

**Comment by phunkyfish** [comment]
Or I can do it if you don’t have the time?

**Comment by AlwinEsch** [comment]
Better you do :smile:, my car died yesterday and need to go around to buy a new :rage:

**Comment by phunkyfish** [comment]
Sure, happy to. Sorry to hear about your car!

**Comment by Rechi** [comment]
The coorect fix would have been to set CMAKE_SYSTEM_PROCESSOR in Toolchain(_binaddons).cmake and then use that variable instead of CPU in PrepareEnv.cmake.

**Comment by phunkyfish** [comment]
So as CMAKE_SYSTEM_PROCESSOR is already set, we could have just substituted CPU with CMAKE_SYSTEM_PROCESSOR for OSX is what you are saying?

Or is there a reason is explicitly set it in Toolchain(_binaddons).cmake?

**Comment by Rechi** [comment]
CMake auto detects `CMAKE_SYSTEM_PROCESSOR` value, unless you use a toolchain file. That's the reason why it has to be set in those files.

**Comment by phunkyfish** [comment]
Ok, that makes sense. I'm not the best person to make this change due to my novice cmake skills ;)

Once the correct change is in place I'm happy to test and backport it.

**Comment by wsnipex** [comment]
the change as is is not wrong either. Both work

**Comment by Rechi** [comment]
Yes it works too, but this PR allows to build add-ons for osx native and not via 'cross-compiling'.
Because of that it should follow the standard CMake way by using `CMAKE_SYSTEM_PROCESSOR` and setting that variable if cross-compiling instead of Kodis custom CPU variable.

**Comment by phunkyfish** [comment]
Then that’s the solution we should move towards. @AlwinEsch when you have time for a follow up PR let me know.

**Pull request merged**
