### PR TITLE
[EPG] Get rid of epg container static singleton - hold it at service manager instead.

### PR DESCRIPTION
**Pull request by ksooo**
@FernetMenta mind doing the review.

### CODE REVIEW

**Review by FernetMenta — APPROVED** [review]
@ksooo looks good so far. Did you consider moving the entire egp component under pvr? I doubt that it will ever be used independently from pvr.

**Comment by ksooo** [comment]
> Did you consider moving the entire egp component under pvr? I doubt that it will ever be used independently from pvr.

Yes, I thought about this and was hoping you would suggest this. So, the idea would be to make it like clients, timers etc, accessible via CServiceBrokerr::GetPVRMananager().GetEpgContainer(). I would also move all code from xbmc/epg to xbmc/pvr/epg. Sounds like a good plan?

**Comment by FernetMenta** [comment]
Yes, sounds like a good plan.

**Comment by ksooo** [comment]
I will come up with a PR that implements the new approach, making epg a subcomponent of pvr.

**Pull request closed without merging**
