### PR TITLE
VideoPlayer fixes

### PR DESCRIPTION
**Pull request by FernetMenta**
- drop useless method HasMenu, doing more harm than any good
- fix external calls to IsInMenu

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by popcornmix** [comment]
This breaks DVD menu navigation.
E.g. with Die Hard sample, wait until "radar" menu is show.
Without this PR arrow keys navigate the menu.
After this PR arrow keys try to seek.

**Comment by FernetMenta** [comment]
@popcornmix thanks, I fixed it

jenkins build this please

**Comment by popcornmix** [comment]
Reported issue is fixed in latest version.

**Comment by phil65** [comment]
@FernetMenta: Could you ping someone from skinning section in case you remove InfoLabels / booleans?
Confuence uses VideoPlayer.HasMenu several times. Should that get cleaned up, or do we have an alternative for that boolean?
Thx!

**Comment by FernetMenta** [comment]
oh, sorry. I searched the code and must have missed this. Thought is was not used. I will bring this function back and fix the possible segfault.

**Comment by phil65** [comment]
ok, thanks!

**Pull request merged**
