### PR TITLE
fix manual album refresh

### PR DESCRIPTION
**Pull request by ronie**
## Description
allow users to always make a selection from the possible results when refreshing an album.

## Motivation and Context
in case the scraper picks up a wrong album during the initial library scan, the user should be able to correct this by doing a manual refresh of the album.

this currently will not work in some/many cases, as kodi checks the 'relevance' for each possible result. 
in case the relevance of one of the results >= 0.95, kodi will select that one and not offer the user to make a manual selection.

second, in cases were a manual selection was offered, not all possible results were listed.

## How Has This Been Tested?
tested using the metadata.generic.albums scraper.
it's not uncommon for musicbrainz to retrun many results with a score of 100 (relevance = 1.00).
in all those cases it was not possible to make a manual selection using the album refresh option.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by DaveTBlake** [comment]
Note to myself that this only effects refresh on albums that do not have mbid read from tags.

Users definitely need to be able to correct any mistakes made in the automated selection based on matching on artist and album title. Opening the selection dialog even with one possible match found gives the user the opportunity to adjust the names used in the search (via "manual" button),  nice improvement.

Some of this processing was definitely left over from a much older time, but I think we need to take care with changes to the relevence checking. There is lttle point presenting the user with a long list of possibilities if they don't also have enough info to choose the right one. 

Take for example (as in issue https://github.com/xbmc/xbmc/issues/18036) Gabrielle - Rise, the selection offered (results from v1.0.5 of the Generic Album scraper) is

Rise Release Selection
How is a user to know which release to pick?
In this case it is the one at the bottom, an album while the rest are singles. 

I know you are looking to get the scraper to prioritise albums over singles, EP etc., which will help this situation. But if showing users more results should we not also do more to differentiate them to support meaningful choice?

OTOH if user has not tagged music files with mbids (picking a release in the process) then do they really care what release they have? Artist(s) and album are not always sufficient to identify a release group e.g. an album not a single, the right tracks etc. and if there are multiple releases the scraper may was well take best guess. Much of the album info is release group based anyway, although some users do have multiple releases of the same album and Kodi hanles that (as long as they have mbid). 

How about scraper searching release group (not release) by artist and album and returning only the top (?) release from each possible release group?

**Comment by ronie** [comment]
all valid points @DaveTBlake 

> Much of the album info is release group based anyway

i checked, and basically the only difference between individual releases within a releasegroup is the release date and the record label.

> How about scraper searching release group (not release) by artist and album and returning only the top (?) release from each possible release group?

i think that would be a good idea. to get the 'top' release within a releasegroup i will select the release with the oldest release date.


> There is lttle point presenting the user with a long list of possibilities if they don't also have enough info to choose the right one.

way ahead of you, i was already working on it ;-)

how about this:
select

**Comment by DaveTBlake** [comment]
That makes a much better selection dialog @ronie :)

**Review by DaveTBlake — APPROVED** [review]
Took some getting used to seeing a dialog with only 1 artist to select on refresh, but does give opportunity for manual correction so I think this is the right things to do.

**Pull request merged**
