### PR TITLE
Expose listitem filename and path from xbmcgui.ListItem.getVideoInfoTag

### PR DESCRIPTION
**Pull request by anxdpanic**
## Description

Expose listitem filename and path from xbmcgui.ListItem.getVideoInfoTag().getFilenameAndPath() to return the same as the ListItem.FileNameAndPath infoLabel

## Motivation and Context

When working on a context menu I found this missing, and had to resort to the info label. The issue is the info label could be different than sys.listitem due to mouse movement for example. This is also the only way I'm aware of to get the query string for a plugin url in this case.

## How Has This Been Tested?

Runtime tested, printed debug strings below

```
DEBUG <general>: getInfoLabel(ListItem.FileName): ""
DEBUG <general>: getInfoLabel(ListItem.Path): "plugin://plugin.video.composite_for_plex/library/movies/"
DEBUG <general>: getInfoLabel(ListItem.FileNameAndPath): "plugin://plugin.video.composite_for_plex/library/movies/?url=http%3A//192.168.1.10%3A32400/library/metadata/7439&mode=5"

DEBUG <general>: getVideoInfoTag().getFile(): ""
DEBUG <general>: getVideoInfoTag().getPath(): "plugin://plugin.video.composite_for_plex/library/movies/"
DEBUG <general>: getVideoInfoTag().getFilenameAndPath(): "plugin://plugin.video.composite_for_plex/library/movies/?url=http%3A//192.168.1.10%3A32400/library/metadata/7439&mode=5"
```

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by garbear** [comment]
I look at the code and see nothing wrong, it's perfectly acceptable to expose more functionality to an API.

You then posted the debug output:

```
DEBUG <general>: getInfoLabel(ListItem.FileName): ""
DEBUG <general>: getInfoLabel(ListItem.Path): "plugin://plugin.video.composite_for_plex/library/movies/"
DEBUG <general>: getInfoLabel(ListItem.FileNameAndPath): "plugin://plugin.video.composite_for_plex/library/movies/?url=http%3A//192.168.1.10%3A32400/library/metadata/7439&mode=5"

DEBUG <general>: getVideoInfoTag().getFile(): ""
DEBUG <general>: getVideoInfoTag().getPath(): "plugin://plugin.video.composite_for_plex/library/movies/"
DEBUG <general>: getVideoInfoTag().getFilenameAndPath(): "plugin://plugin.video.composite_for_plex/library/movies/?url=http%3A//192.168.1.10%3A32400/library/metadata/7439&mode=5
```

I can see that there are three components to the URL:

* path - `plugin://plugin.video.composite_for_plex/library/movies/`
* file name - empty
* query - The RFC 3986 URI query string `?url=http%3A//192.168.1.10%3A32400/library/metadata/7439&mode=5`

wouldn't the name a function that produces `plugin://plugin.video.composite_for_plex/library/movies/?url=http%3A//192.168.1.10%3A32400/library/metadata/7439&mode=5` be `ListItem.URL` and `getVideoInfoTag().getURL()`? I know these don't exist but that's what I expect from the data.

**Comment by anxdpanic** [comment]
The debug output should be in the how has this been tested area, without this addition there is no getVideoInfoTag().getFilenameAndPath()
It's very easy to reproduce incorrect behavior, and can provide a log of that if required.

I didn't use something like getURL since getFilenameAndPath seems to be defined w/ swig already but not used here, and it matches the expected output of the info labels.

I can attempt to change this to getURL if required

**Comment by anxdpanic** [comment]
Sorry I missed the point first time around, that's what I get for replying before the morning coffee. =D

`ListItem.URL` and `getVideoInfoTag().getURL()` would work ofc, but I'm not sure how `getFilenameAndPath`/`getPath` should be handled in that case. Returning empty for `plugin://` urls would be a breaking change(no idea of the scope), or return the same information?

**Review by enen92 — APPROVED** [review]
Looks sane to me. Just exposes to the python API a property that is already available via the info interface. As long as both values match, I'm fine with it.

Please run doxygen in docs/ folder just to confirm that it doesn't break anything in the docs layout

**Comment by enen92** [comment]
jenkins build this please

**Comment by anxdpanic** [comment]
the doxygen addition looks to be in order

**Review by garbear — APPROVED** [review]

**Review by ronie — APPROVED** [review]
looks good to me.

**Pull request merged**
