### PR TITLE
Allow original release date for albums to be scraped

### PR DESCRIPTION
**Pull request by ronie**
## Description
Allow the original release date of an album to be scraped.

## Motivation and Context
In https://github.com/xbmc/xbmc/pull/17437 support for the original release date was added.
Since this information is available at MusicBrainz, it can be scraped.

## How Has This Been Tested?
i have tested this using the metadata.generic.albums scraper, by scraping a few albums
and verifying their original release date was added to the music database.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by DaveTBlake** [comment]
Thanks for this @ronie, I need to get it into my head that the Python scraper interface needs adding to when aritst or album fields with scrapable data are added.

**Comment by ronie** [comment]
sure, no problem.
i've added it as a separate commit

**Review by DaveTBlake — APPROVED** [review]
Thanks for this @ronie, get some greens from jenkins and merge

**Comment by DaveTBlake** [comment]
jenkins build this please

**Pull request merged**
