### PR TITLE
[Windows] Updates VC runtime to be compatible with both VS2019 and VS2017

### PR DESCRIPTION
**Pull request by thexai**
## Description
Updates VC runtime to be compatible with both VS2019 and VS2017.

## Motivation and context
Since https://github.com/xbmc/xbmc/pull/18222 was merged it is assumed that there is full compatibility with Visual Studio 2019, however the VC runtimes are not updated. Someone who compiles Kodi with VS2019 and installs it on a clean machine is not going to work because the installer only includes VS2017 runtimes. 

This PR fixes this. Also maintains backward compatibility with VS2017 because newer VC runtimes are common for VC 2015, 2017 and 2019 (https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0).

The VC runtimes is "one time" download so I think can be download directly from source and is not needed store in Kodi mirrors although this can be changed of course.

## How has this been tested?
Build and test x86 and x64

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by afedchin — APPROVED** [review]
I can't judge on this. Let @Paxxi decide

**Comment by thexai** [comment]
Related:
https://forum.kodi.tv/showthread.php?tid=362193

Seems that latest v20 nightlies needs VC runtime update even are compiled with VS2107 🤔 (doesn't make a lot of sense, but...)

**Comment by DaveTBlake** [comment]
@thexai @Paxxi any ideas why this is suddenly an issue? The original change to VS2019 was merged back in Febuary and I have not had any issues running test builds, now fresh installs of master give `VCRUNTIME140_1.DLL is missing` errors.

**Review by Paxxi — APPROVED** [review]
I don't get how the error in that thread is related to Kodi? The message box says httpd.

New depends are built with latest vs2019 so that could possibly be the cause if this is related to Kodi.

It doesn't hurt to keep up to date with vcredist even if we're not seeing any issues.

**Comment by DaveTBlake** [comment]
> I don't get how the error in that thread is related to Kodi?

@Paxxi doing a fresh install of rescent nightly and running it results in
image
Kodi will not start.

I don't get why this has suddenly happened when the VS2019 merge was in Feb. Changes on a build box?

**Comment by thexai** [comment]
This PR fix the issue because updates VC runtimes for both 2017 and 2019 and downloads it directly from Microsoft servers. In Jenkins log shows that is working fine.  Merge then?

**Comment by DaveTBlake** [comment]
@thexai I'll kick off a test build and test it before merge just to be sure.

**Comment by thexai** [comment]
> New depends are built with latest vs2019 so that could possibly be the cause if this is related to Kodi.

Then is need backport to Matrix because new depends are used in Matrix too:
https://github.com/xbmc/xbmc/commit/28ec1152536ab467a70496d8524e89b9dd899675

**Comment by DaveTBlake** [comment]
> >   New depends are built with latest vs2019 so that could possibly be the cause if this is related to Kodi.

>Then is need backport to Matrix because new depends are used in Matrix too:

I suggest we test a fresh install of Matrix nightly and see if it has an issue before backporting - if it ain't broke don't fix.

**Comment by thexai** [comment]
> if it ain't broke don't fix.

I can't quite agree with this because having the VC runtime dated 2018 is insecure and unnecessary. Note that Microsoft updates the VC runtime downloads every month (even older VC 2015 versions) with security updates. In the Kodi installer it is not necessary to update it every month but since it is included it should be kept updated regularly (every 6 months for example).

Anyway, I can test whether or not it really affects the Matrix. I have VirtualBox configured and I can easily do this type of test, also in Windows 7. I will do it later or tomorrow.

**Comment by thexai** [comment]
As this PR is done, if we want to update VC runtime regularly, it is as easy as creating a cron job or similar that deletes the download folder "../downloads/vcredist/2017-2019` every 60 days or whatever. 

Microsoft updates the download with a http redirection so https://aka.ms/vs/16/release/vc_redist.x64.exe points always to the latest update

**Review by DaveTBlake — APPROVED** [review]
Have run a fresh install of the test build and can indeed confirm that the `VCRUNTIME140_1.DLL is missing` problem is resolved by this.

**Comment by DaveTBlake** [comment]
> Anyway, I can test whether or not it really affects the Matrix. I have VirtualBox configured and I can easily do this type of test, also in Windows 7. I will do it later or tomorrow.

Great @thexai. Having installed via the test build of course my main machine now has the DLL so I can't test if it is an issue on Matrix myself. Aside from the question of keeping VC runtime regularly updated, I am curious if  having built the depends with latest vs2019 does indeed trigger a  VCRUNTIME140_1.DLL error for 19.1 too. I should have tested it before I tested this.

**Comment by Paxxi** [comment]
You can uninstall vcredist from apps and features to test the issue for matrix

**Pull request merged**
