### PR TITLE
[copyright] syncronize copyright header (if possible)

### PR DESCRIPTION
**Pull request by InuSasha**
bring it to 2015, too
@Razzeee do you review? ;)

### CODE REVIEW

**Comment by ace20022** [comment]
-1000

**Comment by un1versal** [comment]
@InuSasha this was my try https://github.com/xbmc/xbmc/pull/5453

**Comment by MartijnKaijser** [comment]
This is not needed

**Comment by MartijnKaijser** [comment]
To be more clear. The copyright header doesn't need to get updated if the file has not changed and it will cause a rebase nightmare for others

**Comment by InuSasha** [comment]
@MartijnKaijser that is a reason, i see. but if it possible to add a file with an actual header? i had to look into 6 files to find a actual on (ok not complete actual, there was a old xbmc in it).

**Comment by FernetMenta** [comment]
maybe we should add a file with a reference header

**Comment by MartijnKaijser** [comment]
Sounds good 
On that note even the two license files in root contradict each other

**Pull request closed without merging**
