### PR TITLE
EndTime: fix infinite value and some other changes

### PR DESCRIPTION
**Pull request by lrusak**
I made this PR because I noticed the cpu usage wasn't updating. Upon inspection I found that `std::numeric_limits<std::chrono::milliseconds>::max()` doesn't actually do what I want (it just reports `0`). This caused problems if the wait time of the EndTime was also `0`.

I've made the `InfiniteValue` member private and replaced it's usage in various areas with std::numeric_limits<T>::max().

I've also fixed an issue where `m_totalWaitTime` isn't initialized in the constructor.

I've also changed `system_clock` to `steady_clock`. The reason for this is here -> https://stackoverflow.com/questions/31552193/difference-between-steady-clock-vs-system-clock/31553641#31553641

@phunkyfish I notice you use `system_clock` in the add-on representation of `EndTime` You may want to update that like I've done here (for the meantime as I think we will just get rid of `EndTime` eventually).

This PR should fix all the outstanding issues and will make removing `EndTime` easier all together.

### CODE REVIEW

**Comment by a1rwulf** [comment]
LGTM

**Review by garbear — APPROVED** [review]
Without looking too deeply, I don't see any problems, and it's a good sign that tests still pass, so I'll give this a +1

**Comment by phunkyfish** [comment]
@lrusak so we no longer use a copy of the class in ffmpegdirect. Instead the a header only version called CEndTime is provided for any binary add-on to use: https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-dev-kit/include/kodi/tools/EndTime.h

Do you want to update it here too as part of this PR?

**Comment by lrusak** [comment]
> @lrusak so we no longer use a copy of the class in ffmpegdirect. Instead the a header only version called CEndTime is provided for any binary add-on to use: https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-dev-kit/include/kodi/tools/EndTime.h
> 
> Do you want to update it here too as part of this PR?

I don't really want to extend this PR any further. Can you estimate how many add-ons actually use this CEndTime class?

**Comment by phunkyfish** [comment]
> I don't really want to extend this PR any further. Can you estimate how many add-ons actually use this CEndTime class?

1

**Comment by lrusak** [comment]
> > I don't really want to extend this PR any further. Can you estimate how many add-ons actually use this CEndTime class?
> 
> 1. For the addon that uses it its a 30 second timer so I doubt the change would make any difference.

Can you point me to the add-on so i can remove it's use of CEndTime then we can just remove the add-on helper class?

**Comment by phunkyfish** [comment]
It’s ffmpegdirect. But we can’t just remove the helper function. Then we would need to rebuild/release all binary addons.

**Comment by lrusak** [comment]
> It’s ffmpegdirect. But we can’t just remove the helper function. Then we would need to rebuild/release all binary addons.
> 
> honestly I don’t think we should be worrying about this.

now is the time to do it :smile:

**Comment by phunkyfish** [comment]
> > It’s ffmpegdirect. But we can’t just remove the helper function. Then we would need to rebuild/release all binary addons.
> > honestly I don’t think we should be worrying about this.
> 
> now is the time to do it 😄

We would need to branch all binary addons  and we are still waiting on cpp 17 changes for one last addon in pvr. So not just yet.

**Pull request merged**
