### PR TITLE
[osx] - fix trac ticket 16508 - xcode cleanup

### PR DESCRIPTION
**Pull request by Memphiz**
This fixes some wrong pathes in the xcode project (leftover from the platform move) - also removes header pathes from the xcode project as we want to use thos from the xcconfig file.

### CODE REVIEW

**Comment by Memphiz** [comment]
jenkins build and merge

**Comment by MartijnKaijser** [comment]
failed...

**Comment by Memphiz** [comment]
ahh missed a spot ... this time i think jenkins build and merge

**Comment by MartijnKaijser** [comment]
now it needs a rebase ;)

**Comment by Memphiz** [comment]
see me puking ...

**Comment by Memphiz** [comment]
kicked manual builds for osx and ios only now because there was a conflict during rebase (which was clear due to my other pr got merged ...) will merge once jenkins is happy...

**Pull request merged**
