### PR TITLE
[PVR] Fix crash after selecting 'Add timer' in PVR timer window, closes Trac16539

### PR DESCRIPTION
**Pull request by ksooo**
Backport of #8960

@seo maybe you can give this a try with pvr.stalker and report back?

### CODE REVIEW

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
@stefansaraev  maybe you can give this a try with pvr.stalker and report back?

**Comment by stefansaraev** [comment]
will do tonight. thanks.

**Comment by stefansaraev** [comment]
@ksooo I tested in on master, an still crashing http://sprunge.us/MjXC

**Comment by ksooo** [comment]
@stefansaraev ooops. Better now? And please, use Jarvis + this PR. Did same mistake on master, unfortunately already merged there. Needs another PR for fix on master.

**Comment by stefansaraev** [comment]
no way I can test jarvis but I adapted your change to CGUIWindowPVRTimersBase::ActionShowTimer in master and not crash anymore. I get an okdialog instead. thanks much.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
win-32 jenkins error is unrelated

@MartijnKaijser your button

**Pull request merged**
