### PR TITLE
[VideoPlayer] Render capture fixes.

### PR DESCRIPTION
**Pull request by afedchin**
see http://trac.kodi.tv/ticket/16788
- [x] Fixes endless loop into RenderManager
- [x] Fixes asynchronous capture in RenderCaptureDX 
- [x] a bit speed up copying picture data by mem alignment.
- [x] cosmetics.

### CODE REVIEW

**Comment by afedchin** [comment]
@FernetMenta ping

**Comment by FernetMenta** [comment]
thanks
+1

**Comment by afedchin** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
@afedchin don't wonder - the jenkins request for this PR is paused as i do some performance tests atm where the slaves need to be unloaded - will unpause the pr once done ...

**Comment by afedchin** [comment]
@FernetMenta, is it ok to go?

**Pull request merged**
