### PR TITLE
[GUI] Add solid panel option to Confluence

### PR DESCRIPTION
**Pull request by Hitcher**
As requested by @da-anda on the forum - http://forum.kodi.tv/showthread.php?tid=260399

Before
screenshot010

After
screenshot013

Before
screenshot014

After
screenshot015

### CODE REVIEW

**Comment by HitcherUK** [comment]
@ronie @phil65

**Comment by ronie** [comment]
there are a few other transparent parts in confluence not covered by this PR,
for instance the side-menu and dialogs like DialogSubtitles.xml

perhaps you want to add those as well?

**Comment by phil65** [comment]
Perhaps a matter of taste, but I think it´s more elegant to add conditional fades to all those textures instead adding separate ones.

**Comment by da-anda** [comment]
ah, you went the solid panel route now. Lowering the transparency a bit would IMO have been sufficient, but that's ofc also nice. Thanks.

**Comment by da-anda** [comment]
if I had known it's as easy as replacing a single texture I would have given it a try myself. Independet of the solid approach, I think that the panels transparency in many cases causes big readability issues. So I gave it a quick try and created a texture with reduced transparency (see attached). Do you guys think we should also change the default one?

contentpanel

**Comment by ronie** [comment]
imo the panels are opaque enough to not cause any issues.
i don't think i've seen much complaints about it (if any) over the past years.

that being said, i have no problem if you want to make the current panel a bit less transparent.

**Comment by mazeyx** [comment]
being able to adjust the transparency to a users liking would be a much better approach and seems to be standard when it comes to transparency at least in programs i have seen.

**Comment by da-anda** [comment]
@ronie, I have a few fanarts on which the readability is suboptimal, likely also because the color of the text in list view is grey and not white, so when you now have a white noisy fanart text is a bit harder to read in the first few lines.
I personally never really noticed much (or ignored it), but after that user report I looked out for it and think there is room for improvement. But I'm also fine if you guys think it's good as is.

**Comment by HitcherUK** [comment]
Will just change the transparency of the default panel.

**Pull request closed without merging**
