### PR TITLE
[Win32] Fix for rotated videos.

### PR DESCRIPTION
**Pull request by afedchin**
proper fix for rotated videos. 

@da-anda @phate89 can you test this?

### CODE REVIEW

**Comment by phate89** [comment]
I tried my sample and they are still stretched horizontally. Not til the left and right edge like before but still stretched.

**Comment by afedchin** [comment]
@phate89 It's an expected result for portait videos.

**Comment by phate89** [comment]
Why a screwed up aspect ratio is expected result? If I watch a video I expect that the image is like when I recorded it. If I want to fill more black space kodi has specific options for video right?

**Comment by afedchin** [comment]
I didn't see wrong aspect. Please provide a debuglog and a screenshot.

**Comment by phate89** [comment]
Sure I forgot about it
http://xbmclogs.com/pxuudin3n
kodi playing the video:
http://www.imagebam.com/image/1e1595458209156
vlc playing the video:
http://www.imagebam.com/image/5fd999458209124
The video is 1920x1080 but when played in kodi is 1080x1080.
The sample I used is the one I put in trac

**Comment by afedchin** [comment]
As I see the aspect isn't changed. Zooming video it not related to this PR. I'm sure what you get same result on non-windows platform. @FernetMenta can you test sample on linux system?

**Comment by phate89** [comment]
You are right it's not a stretch is a zoom in... I completely missed that

**Comment by FernetMenta** [comment]
@afedchin can you point me to the sample?

**Comment by phate89** [comment]
@FernetMenta 
https://dl.dropboxusercontent.com/u/2219086/20160106_210238.mp4

**Comment by FernetMenta** [comment]
I think I see what happens. For non rotated videos our renderer takes width and with aspect ratio it calculates height. Looks like this has not changed with implementation of rotating capabilities. 
@Memphiz you implemented rotation in renderer, right?

**Comment by Memphiz** [comment]
yes - all but dxva

**Comment by Memphiz** [comment]
that was the commit for it - https://github.com/xbmc/xbmc/commit/048cd7164c6c505953f2ef2707d60f883e9d01a1 - i had no issues with wrong aspect with my test clips (basically iphone records taken with different orientation and the airplayed to kodi...)

**Comment by afedchin** [comment]
@Memphiz there isn't an issue with aspect with dxva also, video just over zoomed than @phate89 expects

**Comment by FernetMenta** [comment]
@Memphiz it's not about aspect ratio. assume the original size  is 1920x1080. Now it gets rotated by 90°. width will be 1080 and the frame gets cut in height because 1920 does not fit. The frame needs to be shrinked, that's what's missing.

**Comment by fritsch** [comment]
Can't that be accomplished by changing the dstRect accordingly, centered and with the help of aspect ratio scale the new width to the height which now needs to be smaller?

Something like we do that with ManageDisplays when SBS and TB is done?

**Comment by fritsch** [comment]
Sorry :-) Reading the code tells me, that's what actually happens, but the scaling is not taken into account.

**Comment by Memphiz** [comment]
i wonder why i never saw any cut outs in my tests then - you are sure the issue is the same for all gl an gles platforms?

**Comment by Memphiz** [comment]
i think that is what the "changeaspect" flag is for in the commit i linked - might be a bit missnamed but it should prevent any cut content...

**Comment by FernetMenta** [comment]
> you are sure the issue is the same for all gl an gles platforms?

I see it clearly on OSX. Did you test with high resolutions in 2012? What resolution did an iPhone have 4 years ago?

**Comment by Memphiz** [comment]
1080p - well i get your point i think ... there is only the rotation and fixing the aspect ratio in my code but no scaling :/

**Comment by Memphiz** [comment]
are you onto it by any chance?

**Comment by FernetMenta** [comment]
Nope, I am working on a couple of other things

**Comment by Memphiz** [comment]
Could you guys try with this applied:

https://github.com/Memphiz/xbmc/commit/1e0773dc5e730705ae985ace091986320c77aeaf

**Comment by phate89** [comment]
Tried and the fix works for me

**Comment by da-anda** [comment]
is there a test build somewhere @Memphiz ? But as I'm also on Win10 it might not help much as @phate89 already tested it there.

**Comment by afedchin** [comment]
added @Memphiz changes to this PR.

**Comment by afedchin** [comment]
jenkins build this please

**Comment by fritsch** [comment]
@afedchin wait a bit with pushing, just talked with @Memphiz he wants to add some comments to make it easier for future devs to actually see how the implementation works

**Comment by afedchin** [comment]
@fritsch I just want to check what jenkins is happy

**Comment by Memphiz** [comment]
ehrm i didn't do a pull request to your repo yet because i discussed a better approach for calculating the needed stuff ... well no biggy i guess for you to switch another commit - but i didn't want to hold off this PR with my fix (which is independend from your work).

**Comment by Memphiz** [comment]
thx to @fritsch - this should be much better to understand and would be the final pick for this PR:

https://github.com/Memphiz/xbmc/commit/7b93cd34fc0d68999acf4721b624aca412721929

Well at least if @afedchin can confirm that it still fixes the issue. Also as a special test case - start a rotated video, pause it and then go to the livetv menu - the movie should be scaled perfectly centered in the right top video preview rect (assuming confluence here ...)

**Comment by fritsch** [comment]
@Memphiz yeah - that looks good :-)

**Comment by afedchin** [comment]
I will test tomorrow.

**Comment by afedchin** [comment]
sorry for late. works good.

jenkins build this please

**Comment by Memphiz** [comment]
great :) - thx for having it in your PR :)

**Comment by afedchin** [comment]
@FernetMenta @fritsch @phate89 @Memphiz if no objections I'll merge this today evening

**Comment by fritsch** [comment]
All fine with me - thanks very much to all that helped!

**Comment by FernetMenta** [comment]
sure, go ahead

**Comment by phate89** [comment]
No problem fine with me

**Comment by phate89** [comment]
@MartijnKaijser Are you sure it's been backported? I couldn't find it under jarvis label and in the rc2 I still have the same problem I had with master before this..

**Comment by Montellese** [comment]
According to github these 3 commits are only in master and not in any other branch or tag.

**Comment by afedchin** [comment]
@MartijnKaijser was wrong. this is a more proper fix and not backported yet.

**Comment by afedchin** [comment]
I'll prepare a backport asap.

**Comment by MartijnKaijser** [comment]
oops, sorry guess i thought it was already included. Since i want to keep rc3 same as final we'll put it in the first point release. That way you can also test drive it for some time

**Pull request merged**
