### PR TITLE
[depends] add googletest & disable auto fallback to internal build

### PR DESCRIPTION
**Pull request by Rechi**
## How Has This Been Tested?
- compiled depends for Android (aarch64, arm, i686), iOS, macOS and tvOS
- build with and without internal gtest on Linux

## Types of change
- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by wsnipex** [comment]
thanks! Looking at https://github.com/xbmc/xbmc/commit/590641926816d194d16a6e1801d9b10e5e782e2c there seems to be no reason to bump min required version to 1.10. The previous internal version afaik was 1.7 or 1.8

**Comment by Rechi** [comment]
Only the pkg-config check requires >= 1.10. This isn't optimal, but the older versions are still found fine without it. I've tested it by building an older version via depends.
@wsnipex have you tested it with a debian/ubuntu version which shipps an older libgtest-dev version? Does it work?

**Comment by lrusak** [comment]
This will break normal build for people unless they have gtest installed or explicitly add `-DENABLE_TESTING=OFF` btw. So most likely this will break the freebsd build.

also I don't really understand why we need it in depends when it's only used for native platforms :shrug: The original change built gtest at compile time just like we had it when it was in tree...

**Comment by Rechi** [comment]
I already explained why the auto fallback to the internal version is wrong. One doesn't notice that a new library is required and so doesn't have the chance to use the library provided by the distribution.
Why not use the distro library instead of downloading the source, extract it, build it and install it for every (PR) build?
Same reason as for FreeBSD, why should download, extract, build and install it for every clean Kodi build instead of only doing it for a complete clean rebuild including depends?
The version used in depends (and for internal build) and the minimum required version of a library are not the same. Why was the minimum required version changed from 1.8.0 to 1.10.0 in the pkg-config check? By the way, that check is never executed on Windows.

**Comment by lrusak** [comment]
> I already explained why the auto fallback to the internal version is wrong. One doesn't notice that a new library is required and so doesn't have the chance to use the library provided by the distribution.
> Why not use the distro library instead of downloading the source, extract it, build it and install it for every (PR) build?

How is it any different then what we were doing before?

> Same reason as for FreeBSD, why should download, extract, build and install it for every clean Kodi build instead of only doing it for a complete clean rebuild including depends?

We clean build on jenkins so it would be built no matter what. Also FreeBSD doesn't use the depends build.

> The version used in depends (and for internal build) and the minimum required version of a library are not the same. Why was the minimum required version changed from 1.8.0 to 1.10.0 in the pkg-config check? By the way, that check is never executed on Windows.

because there was changes required to get it to build with 1.10.0

**Comment by Rechi** [comment]
There wasn't any internet connection required (after having built depends for depends platforms), also there weren't any extraction and installation steps.
Yes it can be currently build on Jenkins, but it's wasted time to download, extract, configure, build and install the library for every build. FreeBSD currently uses system libraries, so just install the package provide by the distribution, like it is done for all other libraries.
So 1.10.0 or newer is required? In that case the find module and the find_package call are wrong too.

**Comment by wsnipex** [comment]
Jenkins only does a clean kodi build. Depends are only rebuilt if something changed. Doing a clean build every time for depends would triple build times for no reason

**Comment by Rechi** [comment]
If you are writing this because of my comment, I meant clean Kodi build is deleting only the kodi build folder and full rebuild includes cleaning depends.
With the current situation (without this PR), removing the Kodi build directory causes a rebuild (download, extract, configure, build and install) of gtest for every build.

**Comment by lrusak** [comment]
> Jenkins only does a clean kodi build. Depends are only rebuilt if something changed. Doing a clean build every time for depends would triple build times for no reason

What a revelation.

gtest was built in tree every build before as we always do clean builds, thus why I said nothing really changed.

**Comment by Rechi** [comment]
I'm not caring about the build time, but the download, and configuration time. Also you now need an internet connection, before you didn't.

**Comment by lrusak** [comment]
> I'm not caring about the build time, but the download, and configuration time. Also you now need an internet connection, before you didn't.

this is why we provide the option to use `-D<PKGNAME>_URL=pkgname-pkgversion.tar.gz`

**Comment by Rechi** [comment]
So I should download gtest source on macOS, and allways pass this instead of adding it to depends so it is always present when configuring Kodi, like all other libraries?

**Comment by lrusak** [comment]
> So I should download gtest source on macOS, and allways pass this instead of adding it to depends so it is always present when configuring Kodi, like all other libraries?

I don't really care what you do :smile: I'm just saying that it works :wink:

**Comment by Paxxi** [comment]
This broke windows debug builds. I tries to link kodi-test with gtest instead of gtestd

**Comment by Rechi** [comment]
It worked without this PR, but with the PR moving it from lib/gtest to a dependency?
This PR did not change linking with `gtestd` for debug builds to `gtest`.

**Comment by Paxxi** [comment]
Ahh yeah maybe I got the wrong pr. Saw this one in the blame so commented here.

**Pull request merged**
