### PR TITLE
Remove customizable album format

### PR DESCRIPTION
**Pull request by razzeee**
This will get rid of the duplicates in the album list views and remove the customizable album format from our codebase.
Ping @evilhamster @DaveTBlake @jjd-uk

### CODE REVIEW

**Comment by Razzeee** [comment]
jenkins build this please

**Comment by Montellese** [comment]
Why exactly do we remove this? I'm not using it myself but I'm guessing other people are?

**Comment by DaveTBlake** [comment]
>Why exactly do we remove this? I'm not using it myself but I'm guessing other people are?

I think we should keep m_strMusicLibraryAlbumFormat. Why remove functionality and flexibility? It would be a retrograde step.

I accidentally fixed the silly "title - title" display when album view is sorted by album in #8205 anyway.

**Comment by Razzeee** [comment]
We'll because all these settings have basically backed us up against the wall and we're so confined now, that we can basically choose between bad customization vs bad ui/duplicate info.

Most skins even end up hard coding these values, confluence is one of the few, that is using it like this. So it's very likely that this setting even won't work on other skins.

**Comment by Razzeee** [comment]
Another problem is btw, that these custom formats are only used in some places and others are hardcoded in our codebase. We're caught between worlds basically.
If this is gone (or not this is just an idea for an improvement, no hard feelings) there are still three custom format strings, we need to place everywhere, if we want consistency.

**Comment by jjd-uk** [comment]
Tried to test using a Jenkins generated build but I'm getting a problem of not being able to enter the album node, I get

album

However not sure if it's this or @DaveTBlake PR8205 which was merged earlier.
Note this is on my test PC which only has a local Music source from the hard drive configured.

Debug log
http://pastebin.com/g3Sy88zK

**Comment by jjd-uk** [comment]
Just tried the nightly from this morning and that's fine, so must be this or PR8205.

**Comment by DaveTBlake** [comment]
@jjd-uk I have just compiled the current master - PR8205 merged, this one not - albums node works fine. So the issue isn't PR8205.

Perhaps it is something in cache between changes in builds. Try update library (clears the cache too) and see if the problem goes away.

**Comment by jjd-uk** [comment]
Cheers Dave, not sure what happened before, I installed the build over the top of a previous one and created a fresh source, but guess there must have been stale data from some where, nuking Userdata has cleared it up.

Having now had a look this brings us back closer to what we had in Isengard, so thanks for this improvement Razzeee. 

Unfortunately my one remaining issue is the biggest for me, and that's the duplicate track numbers still appear for "Sort by track". For me this is the primary sort criteria as it's the only one that gives a proper track order for an album, particularly if the album consists of multiple cd's, for me this means the track listing is now crippled without having duration shown.

**Comment by DaveTBlake** [comment]
>Having now had a look this brings us back closer to what we had in Isengard, so thanks for this improvement Razzeee.

The improvement so far is down to me and #8205, I fixed the silly album - album display while I was working on that code. This PR just takes away any custom formatting. I don't think it should be merged, but I don't have any control over that do I. 

I completely agree with what you say about sort by track. I want to keep custom formatting so that users have some way to counteract some of the bad format decisions that are being made.

**Comment by Razzeee** [comment]
> I completely agree with what you say about sort by track. I want to keep custom formatting so that users have some way to counteract some of the bad format decisions that are being made.

That's probably the worst way to look at it, we should go for delivering the best format there is. In the best case, the whole feature won't be needed anymore then.

To be fair, I don't care if this get's merged as most skins will ignore this anyway. We should just create a new label that has the sort order, so that skins can use them. Most skinners will find that handy and if not them then the users will.

Here is Confluence vs Arctic Zephyr for example. Notice how arctic shows more infos (hardcoded) in the list.
screenshot 2015-10-19 23 58 03

screenshot 2015-10-19 23 56 22

**Comment by DaveTBlake** [comment]
>We should just create a new label that has the sort order, so that skins can use them.

Yes, please do that!

**Comment by jjd-uk** [comment]
You say we should go for the best format, that's certainly not the case now with "Sort by track" so I'm really struggling to see your point. It worked fine as it was for 10+ years, I've seen nothing to suggest that "Sort by track" needed to change.

In case you hadn't guessed by now, my opinion is the "Sort by track" change is a serious regression in usability, this alone will stop me upgrading any of my primary systems to Jarvis as I use music that much.

Please note I like the other how the other sort criteria now work, so thank you for trying to improve to things which you have done so in places.

**Pull request closed without merging**
