### PR TITLE
Changing android ndk directory existence test

### PR DESCRIPTION
**Pull request by vadikml**
Starting ndk 11 ndk_dir/RELEASE.TXT was removed.
The new file to test is ndk_dir/source.properties according to a proposal at
http://forum.kodi.tv/showthread.php?tid=274621&pid=2337598#pid2337598

### CODE REVIEW

**Comment by Razzeee** [comment]
@koying

**Comment by koying** [comment]
You must test both, for those having an older ndk

**Comment by vadikml** [comment]
Yes, you are perfectly right.
I guess a simple 'or' between the older and newer implementation is enough
right ?

Or maybe something more complex like if ndk < 11 check for README.TXT if
ndk>=11 check for source.properties is needed ?

Vadim.

**Comment by koying** [comment]
Nah. "or" will do. That's just a simple sanity check

**Comment by vadikml** [comment]
adding "or" check for pre and post 11 ndk version and re-submitting.

**Comment by koying** [comment]
You don't need to close the PR.
You can amend your branch with the updated code, then do "force push" of it and the PR will update by itself.

**Comment by vadikml** [comment]
got it.
tnx.
in progress.

**Pull request closed without merging**
