### PR TITLE
[LanguageCodes] Add "Swiss german" for audio streams (ISO-639-2)

### LINKED ISSUE #17604: Missing audio language code "gsw"
### Describe the bug
In the file https://github.com/xbmc/xbmc/blob/master/xbmc/utils/LangCodeExpander.cpp the language code "gsw" Schweizerdeutsch | Swiss German; Alemannic; Alsatian | Schwiizerdütsch is missing. 

## Expected Behavior
If I load a multi-language MKV file - including an audio stream with "gsw" set - I would like to see "Schweizerdeutsch" or "Swiss German" as language, not "undefined".

## Actual Behavior

gsw will not be recognized as official valid code from https://de.wikipedia.org/wiki/Liste_der_ISO-639-2-Codes. KODI display such audio streams as "unknown".

## Possible Fix

Add "gsw" to https://github.com/xbmc/xbmc/blob/master/xbmc/utils/LangCodeExpander.cpp in the range lines 900-905

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 9.2.2 (Leia)
 - Kodi version: v18.6

### PR DESCRIPTION
**Pull request by howie-f**
## Description
this adds the "swiss german" language code to the language code expander, so this dialect would show up in the gui instead of "unknown".

## Motivation and Context
would close #17604

## How Has This Been Tested?
tested this change with a mkvtoolnix-edited random movie

## Types of change
- [x] **Improvement** (non-breaking change which improves existing functionality)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document

### CODE REVIEW

**Comment by howie-f** [comment]
asking @chewitt as a member of le-team: i'm not quite familiar with the workflow. can you please explain how this small fix will hit LibreELEC 9.2.2 (Leia) because the issue was reported for that release?

**Comment by chewitt** [comment]
If/once this has been merged, make a backport for Leia, and then when Kodi 18.7 ships (no specific plans or schedule) the change will be picked up when we bump Kodi for LE 9.2.3.

Is there a reason for changing the indentation in the file?

**Comment by howie-f** [comment]
ok, i see. thank you. the original commit was https://github.com/xbmc/xbmc/commit/e4f1183b24823c9326f119044274014301a71b92 which is way more relaxing. the identation change is jenkins' complaining about clang-format. tbh i just closed my eyes and applied. i think we should take the original version.

**Comment by fuzzard** [comment]
As much as the push is to update the codebase to adhere to clang-format guidelines we have adopted, in this case id almost go with the original commit.
Dont change just yet, i'll try get some more input from other team members just so you dont go back and forth.

i dont think a consensus has been reached regarding clang-format across the entire codebase, and unfortunately until it is, blocks like this that are just a 1 liner change in a large codeblock are a bit of a pain.

@Rechi would you like to weigh in on this?

**Comment by garbear** [comment]
IMO the indentation question has a path forward. Fix indent, commit as cosmetic comment. Then apply your addition as a commit on top of that. Review is facilitated, because you can review by commit and ignore the whitespace one. Code is improved, because it's one less clang format change later. And most importantly, it won't attract commenters in the PR :)

**Comment by howie-f** [comment]
now i've updated this 1-liner, i'm prepared to drop commits 3-6 ofc, but let's see

**Review by fuzzard — APPROVED** [review]
Appreciate you going above and beyond on this. Thanks.

**Comment by howie-f** [comment]
yeah it's fascinating to get the tools working properly, sometimes hard but a lot of fun, too. 🙃

**Comment by howie-f** [comment]
sporting a script to check any open pr turns out, that this is the only one affecting `xbmc/utils/LangCodeExpander.cpp` at the moment (`git diff --name-only master...`). thus i assume merging the whole thing shouldn't cause trouble. for now i'll leave it as is, but still open if some cosmetics should go ;)

**Comment by garbear** [comment]
Cosmetic split looks nice, change is easier to review and code is improved. thanks!

**Comment by fuzzard** [comment]
Cheers for the PR once again

**Comment by howie-f** [comment]
that was a great hint, thank you guys too

**Pull request merged**
