### PR TITLE
AML: S905 implementation

### PR DESCRIPTION
**Pull request by Stane1983**
This works but needs more testing (tested only on one device and one fw).
@koying

### CODE REVIEW

**Comment by koying** [comment]
Please check https://github.com/xbmc/xbmc/pull/8394
I'm all in favor of dropping this device handling if possible.

**Comment by Stane1983** [comment]
I replied there and voted no :)

**Comment by Stane1983** [comment]
This is still WIP, not working good (similar issue - top left corner if res is not 1080p which is UI fb size).

**Comment by koying** [comment]
@Stane1983 Sorry, I don't get what you mean.
Is it about this PR or the aml patch https://github.com/koying/xbmc/commit/a9555b0e3e342edf32ad26d0e95863c041c2d01f ?

**Comment by Stane1983** [comment]
@koying no, it is about aml android egl and image size that we had before on KK. Same happens now on 905 SDKs some versions (I have that version).

**Comment by MartijnKaijser** [comment]
closing as it's now obsolete

**Pull request closed without merging**
