### PR TITLE
[cmake] Fixes

### PR DESCRIPTION
**Pull request by fetzerch**

### CODE REVIEW

**Comment by fetzerch** [comment]
@popcornmix: Finally got to test with a rpi2. With these changes, I can run Kodi on a freshly installed raspbian jessie image.

**Comment by popcornmix** [comment]
@fetzerch great - I'll see if I can do the same.

**Comment by popcornmix** [comment]
It wouldn't install for me. Needed to add this: https://github.com/popcornmix/xbmc/commit/3b7d23d226330efe6e1ada739f9150f195413354
However still doesn't seem to install enough files. Launching kodi gives:
"Unable to find path to Kodi data files!"

It seems with previous build system I get a ``/opt/xbmc-dbg/arm-linux-gnueabihf/share/kodi/userdata`` directory containing ``ModeLines_template.xml`` and ``RssFeeds.xml`` but this is missing with cmake.

**Comment by popcornmix** [comment]
If I copy ``/opt/xbmc-dbg2/arm-linux-gnueabihf/share/kodi/userdata`` ``/opt/xbmc-dbg2/arm-linux-gnueabihf/share/kodi/system`` and ``/opt/xbmc-dbg2/arm-linux-gnueabihf/share/kodi/addons`` manually I can launch kodi. Are these being installed automatically for you? Did you build natively on Pi or cross compile? (I'm cross-compiling).

I assume you are running from the install directory (rather than the build directory)?

**Comment by fetzerch** [comment]
Oh, I fear I was running from the build directory. Thanks for your patience, I'll give it another try.

**Comment by fetzerch** [comment]
Found and fixed more installation related problems. On linux we can run Kodi again from the installation directory (with `KODI_HOME=$(pwd)/share/kodi bin/kodi`).

@popcornmix: Not yet tested with on the rpi. Can probably do that tomorrow evening. If you like (and kept the build artefacts), you could also quickly run cmake / make install again.

**Comment by fetzerch** [comment]
@popcornmix: Smoke test done. It does start up now also on the rasbperry pi from nfs mounted installation folder. There's likely still something wrong as I could only play sd video. But these kind of things can be handled in a different PR.

**Pull request merged**
