### PR TITLE
Android: Don't reset user set volume

### PR DESCRIPTION
**Pull request by fritsch**
Fixes: https://forum.kodi.tv/showthread.php?tid=350764

Old behaviour has more negative side effects than it tries to solve.

### CODE REVIEW

**Comment by popy2k14** [comment]
Please backport this to v18 because its an strange behaviour to force the users @ 100% of the volume.

**Comment by videvago** [comment]
This solution is not merged yet and topic is in internal discussion.

**Comment by fritsch** [comment]
@peak3d what's your take on that?

**Comment by peak3d** [comment]
If it is better as today -> go ahead and merge. For the future we should look of marriaging system volume and kodi internal volume together. However it looks from logical POV.

**Review by peak3d — APPROVED** [review]

**Comment by popy2k14** [comment]
Thanks guys!
Any chance to get an backport to official kodi v18 ?

**Comment by DaVukovic** [comment]
@popy2k14  Just curious. Do you know if there's an open bug for it?

@fritsch would be nice if you could backport this PR if it will work for Kodi 18

**Comment by fritsch** [comment]
It changes behaviour. @peak3d decides - he has the last say on Android.

**Comment by popy2k14** [comment]
> @popy2k14 Just curious. Do you know if there's an open bug for it?
> 
> @fritsch would be nice if you could backport this PR if it will work for Kodi 18

Here is the forum thread: https://forum.kodi.tv/showthread.php?tid=350764
Fritsch has provided me an v18.5 testbuild back than which worked flawlessly.
If you need it, i can provide it because it is not online anymore in the testbuild section of kodi.

**Comment by peak3d** [comment]
I'm OK with backporting, but someone has to do the PR

**Pull request merged**
