### PR TITLE
[gui] Extend settings dialog functions to show seperator with group name

### PR DESCRIPTION
**Pull request by AlwinEsch**
With this change it become possible to add a name field on the begin of a new group and with help description on other place.

This is a reduced version of request https://github.com/xbmc/xbmc/pull/6329, without skin values, this becomes separated to another.

bildschirmfoto4

bildschirmfoto5

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Has added to pictures. One with label in center and one with left. For me the center looks better :)

**Comment by ronie** [comment]
the center aligned description looks best to me as well.

**Comment by mkortstiege** [comment]
I don´t like both ;/ Ideally this should be handled as sub categories (on left). The more additional settings the messier it gets IMO. I know it´s not that trivial since i know what you´re actually adressing here.

**Comment by Montellese** [comment]
@mkortstiege: Sub-categories have several issues:
* A lot of the settings dialogs don't even support categories so there's no place to display them.
* A lot of sections in the system settings are already full and there's not even more room for extra categories.
IMO this is probably the best we can do but it could certainly use more skinning love to make it easier to distinguish the group titles from the rest of the settings. But IMO that should be completely up to the skinner and shouldn't be controlled/limited by the core implementation.

**Comment by mkortstiege** [comment]
@Montellese ok, thanks for clearing things up. I agree that it needs some skinning love.

**Comment by Montellese** [comment]
I'm all in favor of named groups.

I don't really know our skinning API that well but is a new GUI control really necessary? Wouldn't skins be able to achieve the same goal with a normal label or can a label not have a background image? Or is there another existing control that could be used to achieve the same results? @ronie care to provide some insight?

Is the group name/title focusable or will navigation jump over it?

**Comment by AlwinEsch** [comment]
Hello @Montellese, about the focusable, no it jumps over it.

I have not seen a another way to bring a image to the label, but maybe I was wrong there. What know the others?

**Comment by ronie** [comment]
why not use a separate label and the separator image (id="11") ?

that surely is preferable to introducing a now gui control.

**Comment by Montellese** [comment]
@ronie: AFAIK the idea was to give skinners the possibility to make named groups look different (different color, alignment, background image, ...) than the usual group separation. And currently there's no label control in the settings windows/dialogs.
Would it make more sense to add the possibility to specify a texture for a label control and then just use that instead of either a completely new control or a combination of the label and separator image control?

**Comment by ronie** [comment]
my preference would be to add a label to the settings windows instead of this new control.
then simply use this label combined with the separator image we already have.

skinners can use different colors/fontsizes for this label to make it stand out from the rest.

**Comment by AlwinEsch** [comment]
Hi @ronie, on begin it was as this way and was not accepted due to lack of rights for skin design.

**Comment by AlwinEsch** [comment]
Any news about this :-) ?

**Comment by ronie** [comment]
sorry, missed your previous reply :)

> Hi @ronie, on begin it was as this way and was not accepted due to lack of rights for skin design.

could you please point me to that discussion?

**Comment by AlwinEsch** [comment]
Any news about this :-) ?

**Comment by ronie** [comment]
i'm sorry but i still think introducing an entire new skin control just for this purpose is overkill.

**Comment by Montellese** [comment]
@ronie: If you think so that's fine by me. I just thought that it might be nice for skinners to have control over how these group labels/titles would look like instead of forcing the separation positions on them. I've seen quite a few skinners doing some crazy customized stuff with the settings window so I figured this would give them more possibility for a clean integration.

**Comment by AlwinEsch** [comment]
What is the status of this request, still required for audio DSP?

**Comment by AlwinEsch** [comment]
Have also added with "[gui] Allow skin to define settings group label parts" the part with extended control of the label, was planned in separate request but now added here.

**Comment by FernetMenta** [comment]
@ronie @Montellese this is required for audio DSP pr with is almost open for one year. have a look at this screen shot: https://cloud.githubusercontent.com/assets/6879739/6186546/01143884-b37b-11e4-9d15-4a77738a061d.png
those kind of dialogs can't be made with group selections like in settings. imo this is best accomplished with the proposal in this pr. in case you don't like it, please suggest an alternative. I don't want to see this discussion going on for another month.

**Comment by Montellese** [comment]
Well personally I thought it might be better to give skinners more control over the group headings but I'm not a skinner so whatever @ronie, @Hitcher, @Black09, @BigNoid think(s) is best works for me.

**Comment by BigNoid** [comment]
It would be nice to have a label control in that window that can have a texture. In normal grouplists you can use a button control and set it to disabled to achieve the same effect, but you cant do that in the pre-defined lists.
so +1

**Comment by ronie** [comment]
as mentioned before, i'm not a big fan of introducing a new gui control just for this purpose.

as for suggesting alternatives, i do like what Montellese brought up:
> Would it make more sense to add the possibility to specify a texture for a label control and then just use that instead of either a completely new control or a combination of the label and separator image control?

i'm sure that would be a welcome addition for skinners and they for sure could use it all throughout the skin instead of just inside the settings section.

**Comment by FernetMenta** [comment]
Note that addon authors are no skinners in general and this change is required for addons which extend gui. That means it has to be as simple as possible.

**Comment by ronie** [comment]
i assume we're discussing binary addons here?

python addons already have the ability to add a section heading label,
they use a regular label control for it.
hence my initial suggestion to use a normal label control for this PR as well.
it would keep things unified across the various settings screens.

**Comment by FernetMenta** [comment]
so we have a 1:1 now. what do the other skinners think?
@AlwinEsch would ronie's suggestion be feasible or not?

**Comment by AlwinEsch** [comment]
I can add it to a normal label, that's easy (was also in my mind on begin). But then is there a lot of not needed function process points for the most used control in KODI. If this accepted then I change it to there.

@FernetMenta you was faster.

**Comment by Montellese** [comment]
@FernetMenta: Does it really matter that addon authors are no skinners? The dialog should be defined in Kodi and skinned in the default skin by a skinner. Python addons currently can't make use of the settings system we use for GUI settings etc and even if they could the settings dialog would still be skinned as part of the default skin by a skinner.

To me it sounds like extending the label control with the functionality to define a texture is the best compromise. I don't really know about the performance impact but if we are concerned about that we could introduce a `texturedlabel` or something like that which is the same as a label but with a texture. In that case skinners would have to actively decide between the two control types and it wouldn't be a control type that is specific to the settings windows/dialogs.

**Comment by HitcherUK** [comment]
RE Label control with texture.

How would this work where the label uses auto-width?
What about textures using border values?
What about textures using colour diffuse?

**Pull request closed without merging**
