### PR TITLE
[pvr] return empty info label for season and episode less than 1

### PR DESCRIPTION
**Pull request by xhaggi**
Follow-up of #7222 and requested by @ronie to fix issue reported at #7209

### CODE REVIEW

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by xhaggi** [comment]
@ksooo mind taking a quick look ;)

**Comment by xhaggi** [comment]
any objections, @Jalle19 ping you too

**Comment by mkortstiege** [comment]
+1

**Pull request merged**
