### PR TITLE
[addons] add 'AvailableUpdates' window property

### PR DESCRIPTION
**Pull request by tamland**
Shows how many updates are pending. @phil65 is this what you wanted?

### CODE REVIEW

**Comment by phil65** [comment]
yup, exactly. Thx for this. Will test when I find some time.

**Comment by phil65** [comment]
Just tested this. At the moment this only seems to trigger when opening addonbrowser, right? Is there a way to trigger this earlier? (On startup and in regular intervals?)

**Comment by tamland** [comment]
I guess that's how window properties work? (you tell me). We probably need to move both this and the `Updated` one to a global infolabel if we want that then

@mkortstiege probably knows

**Comment by phil65** [comment]
hmm from a skinner's perspective this is not neccessarily how window properties work, but I agree, a global infolabel would perhaps make more sense. I guess the same would apply to the lastUpdated window property?

**Comment by mkortstiege** [comment]
Jep, sounds like it should be added to the infomanager then.

**Comment by tamland** [comment]
I'm not sure how to proceed with this. The function in question is sort of slow as it reads from db. Having an infolabel that does that every tick would be unacceptable. I'm not sure how to get the infomanager to cache, or if it supports that. @mkortstiege?

**Comment by mkortstiege** [comment]
Can't you implement it in a similar way to what i did once (9cf9efa47b1ea6e14cb4bc80636c51bd5aa6823c) for keeping track of disabled addons?

**Comment by ronie** [comment]
in case this is jarvis material: tick... tock...

**Comment by tamland** [comment]
I think I'll postpone it since it require hand writing caching. It's non-trivial to add since updating writes directly to db without going through the addon manager. Won't be needed for jarvis anyway.

**Comment by phil65** [comment]
small bump, @tamland  :)

**Comment by MartijnKaijser** [comment]
@tamland ping

**Pull request closed without merging**
