### PR TITLE
udevprovider fixes

### PR DESCRIPTION
**Pull request by stefansaraev**
crash and burn fixes. 

@sraue @samnazarko fyi. you better backport to oe/osmc isengard builds

### CODE REVIEW

**Comment by stefansaraev** [comment]
jenkins build this please

**Comment by mkortstiege** [comment]
jenkins build this please.

**Comment by stefansaraev** [comment]
aded a fix for data dvds.

**Comment by un1versal** [comment]
What would be nice additionally would be to correct the message you get on mounting a DVD

Clearly its not a harddrive I promise.
screenshot033

The unmounting one is fine however.
screenshot034

**Comment by wsnipex** [comment]
any reason to not use std::string here?

**Comment by stefansaraev** [comment]
my intention was no to rewrite the whole thing but quick fix few bugs.

**Comment by mkortstiege** [comment]
Looks good to me. Changing the strings should be done outside of this PR.

**Comment by un1versal** [comment]
> Looks good to me. Changing the strings should be done outside of this PR.

it is see https://github.com/xbmc/xbmc/pull/8335

**Comment by fritsch** [comment]
jenkins build this please

**Pull request merged**
