### PR TITLE
Rename the LICENSE.GPL file to LICENSE.txt (or LICENSE.md)

### PR DESCRIPTION
**Pull request by Hedda**
Recommend that the LICENSE.GPL file should be renamed to either LICENSE.txt (or LICENSE.md) to enable GitHub to show the license as well as to follow Git best practice.

https://help.github.com/articles/open-source-licensing/

### CODE REVIEW

**Comment by Razzeee** [comment]
I would vote for md

**Comment by akva2** [comment]
md is wrong imo, there's no markdown in there, and shouldn't be.

**Comment by Jalle19** [comment]
@akva has a point, LICENSE.txt is more appropriate

**Comment by MartijnKaijser** [comment]
there's also https://github.com/xbmc/xbmc/blob/master/copying.txt  and these documents should be fixed/erged

**Comment by Jalle19** [comment]
@Hedda can you take care of copying.txt as well? I think it can be dropped if the content is the same  as LICENSE.txt.

**Comment by Hedda** [comment]
@Jalle19 done as requested in #8970 which removes copying.txt

**Comment by Jalle19** [comment]
@MartijnKaijser I say we merge both

**Comment by Razzeee** [comment]
there are some files, which we should edit when this gets in https://github.com/xbmc/xbmc/search?p=1&q=%22LICENSE.GPL%22&type=Code&utf8=%E2%9C%93

**Comment by MartijnKaijser** [comment]
needs more work than simple rename. Closing for now

**Pull request closed without merging**
