### PR TITLE
dvdplayer: audio sync fixes

### PR DESCRIPTION
**Pull request by FernetMenta**
this should fix the long period of muted audio after seeks

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by bkuhls** [comment]
I confirm that the "long period of muted audio after seeks" is fixed now, thx!

**Comment by Memphiz** [comment]
Mhh not quiet sure what this guy meanse - but if the revisions are correct this PR could be related:

http://forum.kodi.tv/showthread.php?tid=224635

**Pull request merged**
