### PR TITLE
Fix DVD disc device playback (#20048) by fixing device url initialization

### LINKED ISSUE #20048: Kodi 19.1 won't play DVD
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi is unable to play DVDs kodi is detecting them as an incorrect image format
Detecting DVD-ROM media filesystem...
2021-08-16 17:00:55.662 T:28       INFO <general>: CD Analysis Report
2021-08-16 17:00:55.663 T:28       INFO <general>: __________________________________
                                                   
2021-08-16 17:00:55.664 T:28       INFO <general>: CD-ROM with ISO 9660 filesystem
2021-08-16 17:00:55.664 T:28       INFO <general>: ISO 9660: 0 blocks, label 
2021-08-16 17:00:55.664 T:28       INFO <general>: Tracks overall:1; Audio tracks:0; Data tracks:1
2021-08-16 17:00:55.664 T:28       INFO <general>: Using protocol iso9660://
2021-08-16 17:00:55.664 T:28       INFO <general>: Disc label: 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

 Kodi shold be able to play a DVD.

## Actual Behavior
Does does nothing when clicking on disc in menu.

### To Reproduce

1. Start Kodi
2. Put DVD in drive
3. Click the disc icon in kodi's menu

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/6993844/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [✔ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by dmahurin**
## Description
The "iso9660: rework IFile and IFileDirectory implementations" changes made on 2019-05-25 broke DVD disc device playback.

Fixes needed to restore DVD disc device playback:
 - restore the the iso9660 url host/path update
 - open the disc device filename when no file/directory given in the url

## Motivation and context
Playback of DVD disc devices (unmounted), have apparently been broken for 4 years, due to this change.

commit e846acb56897c9a6b66e08e221024366b08c0a8a
Date:   Sat May 25 11:04:19 2019 -0700
iso9660: rework IFile and IFileDirectory implementations

This led to broken DVD playback on systems without udisk/automount (such as Batocera).

## How has this been tested?
Tested with a DVD drive connected on a Linux Ubuntu 22.04 system, with all automounting disabled.
Open Kodi.  Play Disc.  It plays. This would not work without a fix.

Tested with:
Kodi Nexus and Matrix. I do not have ffmpeg 6, so not yet tested on master, though it cherry-picks cleanly and should function the same.

## What is the effect on users?
Functional DVD disc playback of DVD device, without mounting disc.

## Types of change

- [X ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by dmahurin** [comment]
The docker and iOS builds failed with :undefined reference to 'MEDIA_DETECT::CLibcdio::GetInstance()".

Does the CLibcdio call need to be wrapped in HAS_DVD_DRIVE or another define check?

**Comment by dmahurin** [comment]
The branch below has the jenkins formatting changes and the HAS_DVD_DRIVE check.
if ok, I can push to the PR, or squash back to one commit if we want that.
https://github.com/dmahurin/xbmc/tree/master-dvd-play-fix-test

**Comment by dmahurin** [comment]
A comment/question about this change for people reviewing the change, especially @lrusak :

This CURL::Parse part of this change change in xbmc/URL.cpp, is reverting the the modification of this line from the "iso9660: rework ..." change.
-  if (IsProtocol("musicdb") || IsProtocol("videodb") || IsProtocol("sources") || IsProtocol("pvr"))
+  if (IsProtocol("iso9660") || IsProtocol("musicdb") || IsProtocol("videodb") ||
+      IsProtocol("sources") || IsProtocol("pvr"))

This code fixes the urls's that cannot have hostname. For 'iso9660://VIDEO_TS/video_ts.ifo', the url parser sets hostname to 'VIDEO_TS', and file to '/video_ts.ifo'.  The updated code fixes that and makes host '' and file '/VIDEO_TS/video_ts.ifo'.

While reverting the old change does fix DVD playback, I did wonder if there was som intent for the change.

if there is no reason, then likely the addition of iso9660 should also be removed in 
URIUtils::HasParentInHostname in xbmc/utils/URIUtils.cpp (also in the "iso9660: rework ..." change).

git show e846acb56897c9a6b66e08e221024366b08c0a8a -- xbmc/utils/URIUtils.cpp

That change had not effect on DVD disc playback, but perhaps it still be removed if it has no purpose.

Reference:
commit e846acb56897c9a6b66e08e221024366b08c0a8a
Date:   Sat May 25 11:04:19 2019 -0700
iso9660: rework IFile and IFileDirectory implementations
This changes the iso9660 methods to use libiso9660++

**Comment by dmahurin** [comment]
branch rebased with master

**Comment by dmanlfc** [comment]
works well @dmahurin thanks

**Comment by enen92** [comment]
Sorry I haven't come back to this yet (some little guy is stealing all my previous screen time...). Allow me a few days to test and propose an alternative.

**Review by enen92 — CHANGES_REQUESTED** [review]
First of all, thanks for the contribution and sorry for the time taken to review this. Your change helped tracking down the issue.
Unfortunately I don't think including the cdiosupport into the iso9660 vfs implementation (for the sake of finding the drive) is a proper fix for the issue. Ideally, the device path should be propagated from the caller (supporting more than 1 drive is in my personal roadmap).
Checking internally with the team, in our vfs URL handler, we use the hostname for that kind of stuff. I've had a crack at it and came up with this: https://github.com/enen92/xbmc/commit/fb9684b1a13b64c6c773e64104f87313a00b59e6

The code isn't pretty but at least it tries to avoid "polluting" components that have been recently cleaned up/rewritten (in this case the iso9660 vfs implementation).

**Comment by dmahurin** [comment]
I will review the proposed changes in a few days.

**Comment by dmahurin** [comment]
I will review the proposed new changes in a few days that are now in PR #23531.

**Comment by enen92** [comment]
@dmahurin thanks, I'll attribute the authorship of the fixup commit (https://github.com/xbmc/xbmc/pull/23531/commits/f01e270c10a9c47bd287661385563b03e76cfb30) to you

**Comment by enen92** [comment]
@dmahurin I'd prefer to keep the implementation of the iso9660 as is and keep using the raw `iso9660://` paths for now. Kodi is multiplatform - I am not completely sure if that won't break windows...
Why don't you simply implement https://github.com/enen92/xbmc/commit/fb9684b1a13b64c6c773e64104f87313a00b59e6? That commit is pretty much similar to the one on this PR, it just avoids the include. It fixes the issue, it's backportable to nexus and can be built upon with https://github.com/xbmc/xbmc/pull/23531...

**Comment by dmahurin** [comment]
Hi @enen92,
In the interest of getting a fix in place, I pushed your initial changes, comment slightly modified.

Though I now think a real fix and cleanup is due to re-think the iso9660 "url".

It has went from
iso9660:// to
iso9660://VIDEO_TS/video_ts.ifo to 
iso9660://%2fdev%2fcdrom/VIDEO_TS/video_ts.ifo

The purpose of tacking on VIDEO_TS/video_ts.ifo was at some point (I think) to give information to later parts of processing, to indicate that this is a DVD.

But changing the url this way is a poor way to pass information and unnecessary.

My alternate change  just simplifies.  The url just becomes iso9660:///dev/sr0.
The type of disc can be determined separately without changing the url.

The alternate change was also an attempt to start unwinding some of the duct tape and band-aids that have be added over the years.

It is obvious, especially since it was not functional for several years, that current state or design of the code was not completely understood.

I was hesitant to take your quick fix (or even mine),  because it's seems like another band-aid.

Though as mentioned, getting a fix in place for dvd disc playback is important as well. 

But I recommend simplifying the iso9660 url use before building on this change.

The alternate fix did work fine for DVD's on Kodi 20, But you are correct, that likely more testing is needed, especially for thinks like  HD-DVD Bluray.

**Review by enen92 — APPROVED** [review]

**Comment by howie-f** [comment]
works like a charm, i think this should go into Nexus

**Pull request merged**
