### PR TITLE
[cleanup][fix] Fix some cppcheck warnings.

### PR DESCRIPTION
**Pull request by ace20022**

### CODE REVIEW

**Comment by ace20022** [comment]
jenkins build this please

**Comment by ace20022** [comment]
@ Linux des, e.g. @fritsch , https://github.com/ace20022/xbmc/commit/7f520b4e79df9f3fc9c74b37f7b488c6563825f1 should be Mord than enough, vor not?

**Comment by ace20022** [comment]
maybe @FernetMenta ^^ ?

**Comment by FernetMenta** [comment]
@ace20022 https://github.com/ace20022/xbmc/commit/7f520b4e79df9f3fc9c74b37f7b488c6563825f1 is Greek to me :)

**Comment by fritsch** [comment]
https://github.com/ace20022/xbmc/commit/7f520b4e79df9f3fc9c74b37f7b488c6563825f1 is fine. dest is allocated for 16 and sscanf is allowed to write up to 15 chars, as it will add a \0 at the end we need %15s as @ace20022 correctly fixed.

**Comment by fritsch** [comment]
jenkins builds this please

(did not look at the other build failure log, was too late)

**Comment by ace20022** [comment]
Nah, the questions is if 15, 127, 127 is enough. I haven't found a reliable specification of /proc/net/route .
I don't know how long the iface name can be, the others should be 8 hex for ipv4 but not sure.

**Comment by fritsch** [comment]
@ace20022 the semantics is a different thing and this is not tested by the code analyzer anyways. But yes the 127s are enough, the corresponding gnulibs are doing it the same. Code wise the 15 needs to be there to match the buffer.

**Comment by ace20022** [comment]
>@ace20022 the semantics is a different thing and this is not tested by the code analyzer anyways.

Of course I know that ;) I just wanted to save us double work. Thanks for checking the gnulibs!

What happened to the jenkins build/link? IRC it was only pvr.hts, but to be sure one more time:

jenkins build this please

**Pull request merged**
