### PR TITLE
[guilib/pictures] Add an ffmpeg based image loader

### PR DESCRIPTION
**Pull request by ace20022**
Rewrite of https://github.com/xbmc/xbmc/pull/8214

### CODE REVIEW

**Comment by ace20022** [comment]
@fritsch Could you please have a close look at it, I can't see anything any more ;)

**Comment by fritsch** [comment]
jenkins build this please

**Comment by ace20022** [comment]
If this loader is faster than the cximage one we could make it the default one or even drop cximage.

**Comment by ace20022** [comment]
@fritsch I've rewrote seeking, could you please re-check it?

jenkins build this please

**Comment by ace20022** [comment]
@fritsch I've added a comment, good to go? And thx much for the review!

jenkins build this please

**Comment by fritsch** [comment]
@ace20022 yes, fine with me. Thanks much for doing that.

Next: we replace all other Image handling that now can be done with this new code? :-)

**Comment by ace20022** [comment]
> Next: we replace all other Image handling that now can be done with this new code? :-)

I also considered this, but we need intensive performance tests before that step.

**Comment by fritsch** [comment]
How about a blind test - we just do it and see what happens :-)?

**Comment by ace20022** [comment]
Okay, but then double-blind ;-)

**Comment by stefansaraev** [comment]
after quick test with CFFmpegImage forced for everything but gif -  confluence is fully functional, and png, jpeg, tiff and bmp images work for me(tm). cximage can go ?

:runner:

**Comment by ace20022** [comment]
I've checked that too during development, but it felt slower sometimes, especially for jpgs. Large png felt faster, so maybe we should/could indeed switch the default loader, but don't rip out cximage for a moth or so.

**Pull request merged**
