### PR TITLE
fixed: show the actual set poster/fanart for sets

### PR DESCRIPTION
**Pull request by notspiff**
only show relevant art types in the Choose art dialog. @olympia

### CODE REVIEW

**Comment by olympia** [comment]
Great spiff, many thanks! (is there no good snow or what? :) )

(you remember I am unable to test now, right?)

**Comment by notspiff** [comment]
can't you just get the jenkins build artifact ?

**Comment by olympia** [comment]
I will surely disappoint you by saying I have no idea what that is, but that's reality...

**Comment by notspiff** [comment]
it would be a windows installer however it seems we do not produce those as artifacts for the auto builds.

**Comment by notspiff** [comment]
let http://jenkins.kodi.tv/view/Automation/job/BuildMulti-PR-Manually/151/ finish, then you can pick up the build at http://mirrors.kodi.tv/test-builds/windows/

**Comment by olympia** [comment]
Yes, there is still some feature to add, before this could be merged. Would be extremely nice to have this for v18. @notspiff, would you have the mood and time to code this around?

**Comment by MartijnKaijser** [comment]
@notspiff was this ready or not?

**Comment by notspiff** [comment]
No and @rmrector is on it.

**Pull request closed without merging**
