### PR TITLE
[Confluence] - use playlists for widgets instead of window properties

### PR DESCRIPTION
**Pull request by phil65**
@ronie  
This gets rid of using window properties for the widgets.
Perhaps worth discussing:
- Clickin on an album now jumps to that album in MyMusicNav.xml instead of playing it directly (playing directly is not possible I think). I dont think that this is a downside though.

In a follow-up the corresponding parts in core could be removed. Perhaps something for @xhaggi or @mkortstiege :)

### CODE REVIEW

**Comment by phil65** [comment]
...havin played with it some more, I now switched to the existing VFS paths for recentlyadded movies and episodes and added a limit=10 param. For music this doesnt work out properly though since the *all albums item will be displayed then.

**Comment by mkortstiege** [comment]
Nice. IMO the all albums item should rot in hell. That static hardcoded item is just ugly and should be removed (at last for pre-filtered listings such as recently- added/played). Since i am not using the music section I really wonder Is there a good reason we're carrying this one since ages.

**Comment by MartijnKaijser** [comment]
the "all albums" should indeed be removed from recently added and maybe as well from recently played.
@ronie you thoughts as you are one of the few actually using it ;)

**Comment by Montellese** [comment]
IMO having the "All albums" and "All seasons" etc in the library view can make sense but it's just implemented in the wrong place. Having this as part of the VFS is just wrong. Nothing returned from the VFS should depend on user settings. Anything that depends on user settings should be added after the listing has been retrieved from the VFS. Same goes with "Flatten tvshows" and other options like that. Then we wouldn't have this problem in recently added etc.

**Comment by ronie** [comment]
@phil65 i tried the exist same thing locally a few days ago and came across the same issues (albums not playing / all albums entry).

for movies / episodes this is a perfect replacement though.

as for the 'show all foo entry', that setting should be disabled by default imo.

not being able to play albums from the recently added widget is a big downside tough,
the reason i would click on a recently added album is to listen to it, not to browse it's contents.

**Comment by MartijnKaijser** [comment]
so as it stands now we could already convert movies/episodes without problems and merge that.
that leaves music to be fixed.

**Comment by phil65** [comment]
So should I revert the music part? I dont see clickin twice really as a downside in this case since this is not some button you click all day. Dependening on the type of listener it could even be the desired behaviour.  I´d much prefer to get rid of this antiquitated technique to include widgets.

**Comment by mkortstiege** [comment]
I vote for nuke the music part for now since it adds another behavior that most users will see as a regression.

**Comment by uNiversaI** [comment]
I use all of the above often and like the fact that video playback starts when selecting a movie or a episode or an album but if it took you to recently added node then we just duplicating what the navigation options already offer with the diffrece you see the Poster/Thumb and title as well.

Also for same reasons given for declining https://github.com/xbmc/xbmc/pull/4469, make me wonder if those reasons extend to this here then as well.

**Comment by phil65** [comment]
@uNiversaI The behaviour only changed for albums and for that there is no duplication of anything because you get the option to play a specific track, which was not possible previously.
Reasons from #4469 do not apply here if I´m not mistaken.

I would prefer to get rid of this properties-for-widgets stuff altogether so we can clean up core code and lead by example as a default skin by makin use of the most appropriate techniques.
I dont believe that users will see the changed behaviour as a regression.

In case this gets -1´ed I would prefer to close the PR completely instead of mixing up the widget filling techniques by only converting the video part. That would just be irritating for new skinners who take confluence as a template and doesnt help us in terms of cleaning up core code.

**Comment by uNiversaI** [comment]
Ok let me try to understand this. And Im not against cleaning up core or any other reason for this to happen.

Currently it queues and starts to play the whole album immediately. Desired yes / no? Here the answer is mostly yes.

As long as I can queue any recently added album with least amount of navigation after this patch then Im its fine. 

What happens then if a user deletes these playlists?

**Comment by phil65** [comment]
two VFS paths are "hardcoded"  and one is a playlist file inside the skin folder so we can expect that noone deletes / modifes that one.
@xhaggi, would it mean lot of work to implement the ability to override the onclick of the container listitems with a custom onclick? (-->  e. g. by adding ```<onclick>SomeBuiltIn</onclick>``` to the container control?) You and @mkortstiege  probably already looked into the same code areas for the oninfo stuff and probably know best about this. :)

**Comment by mkortstiege** [comment]
Not sure if i like that proposal. Overriding based on parent won't work here most likely. We would have to implement item overrides for dynamic content. Somehow i fear this will lead to massive inconsistencies. Ideally this happens not in core, so any addon can specify its own.

**Comment by ronie** [comment]
@phil65 mind adding the music part now that we have onclick override?

**Comment by ronie** [comment]
meh... we still need to get rid of the 'all albums' entry i guess

**Comment by InuSasha** [comment]
my version of this change: https://github.com/InuSasha/xbmc/commit/f3ecca61a03bd844918950090837e33486cb6625

But there is the problem with the "all albums", too. My solution: show it, and make it usable.
Another alternative, select 11items and hide "all albums".
But IMHO "all albums" should not in musicdb://recentlyaddedalbum, because it is semantically wrong.

**Pull request closed without merging**
