### PR TITLE
[pvr] Add related parts to music OSD

### PR DESCRIPTION
**Pull request by AlwinEsch**
With this change the for PVR channels needed buttons becomes add to music OSD, also the signal quality information come to it.

There was a change in the GUIInfoManger to handle <code>MusicPlayer.Content(LiveTV)</code> on skin and in Application.cpp also added.

### CODE REVIEW

**Comment by xhaggi** [comment]
@AlwinEsch could you please rename the commit message of the second commit and prefix it with `[confluence] ..` so it's easier for our skin devs to get track of changes to our default skin.

@ronie could you please take a look at the second commit.

**Comment by AlwinEsch** [comment]
Thanks @xhaggi, is changed.

**Comment by xhaggi** [comment]
I guess you should drop the wrongly pushed string.po

**Comment by AlwinEsch** [comment]
Sorry, is updated again ;-)

**Comment by xhaggi** [comment]
Thanks.

**Comment by ronie** [comment]
tested and work ok, thx!

**Pull request merged**
