### PR TITLE
Fix screensaver/DPMS interaction

### PR DESCRIPTION
**Pull request by yol**
## Description

Disable screensaver inhibition when DPMS is also active as screensaver inhibition might also inhibit DPMS (which we don't want inhibited in that case)

## Motivation and Context
#14833

## How Has This Been Tested?
Run on Linux/X11

### CODE REVIEW

**Comment by xekon** [comment]
Whats the trick to checking this out? Admittedly i've not used github much

I tried:

    git clone https://github.com/xbmc/xbmc.git
    cd xbmc
    git fetch origin pull/ID/head:14833

fatal: Couldn't find remote ref pull/ID/head

**Comment by Rechi** [comment]
`git fetch origin +refs/pull/14845/head:<WHATEVER>` or `curl -L https://github.com/xbmc/xbmc/pull/14845.diff | git apply`

**Comment by xekon** [comment]
Thanks Rechi, from that point forward I should be able to build according to the readme: https://github.com/xbmc/xbmc/blob/master/docs/README.Ubuntu.md

    sudo apt-get build-dep kodi

E: You must put some 'source' URIs in your sources.list

I assumed that meant that I need the other repository mentioned (even though im on 18.04 not 16.04)

    sudo add-apt-repository ppa:team-xbmc/xbmc-ppa-build-depends

but then again maybe not:

Err:23 http://ppa.launchpad.net/team-xbmc/xbmc-ppa-build-depends/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]

I can just let you guys test it if you prefer, I was just gonna test it as well.

**Comment by fritsch** [comment]
You just miss the deb-src lines in /etc/apt/sources.list  uncomment them, apt-get update and get the build-deps again

**Comment by xekon** [comment]
I am actually running 18.04 (bionic) However the ppa seems to only go up to artful (17.10)

I know you can manually add it anyway, so I added it manually to the bottom:

    sudo nano /etc/apt/sources.list
    deb http://ppa.launchpad.net/team-xbmc/xbmc-ppa-build-depends/ubuntu artful main
    deb-src http://ppa.launchpad.net/team-xbmc/xbmc-ppa-build-depends/ubuntu artful main

I think I am missing something that is maybe obvious to somebody else

    sudo apt-get update
    ...
    Get:23 http://ppa.launchpad.net/team-xbmc/xbmc-ppa-build-depends/ubuntu artful/main Sources [2,388 B]
    Get:24 http://ppa.launchpad.net/team-xbmc/xbmc-ppa-build-depends/ubuntu artful/main amd64 Packages [3,352 B]
    Get:25 http://ppa.launchpad.net/team-xbmc/xbmc-ppa-build-depends/ubuntu artful/main i386 Packages [3,360 B]
    Get:26 http://ppa.launchpad.net/team-xbmc/xbmc-ppa-build-depends/ubuntu artful/main Translation-en [2,204 B]
    ...
    sudo apt-get build-dep kodi
    Reading package lists... Done
    E: Unable to find a source package for kodi

**Comment by pkerling** [comment]
Please compile for X11 if you are not running Wayland.

The DPMS stuff is specific to X11 anyway...

**Comment by xekon** [comment]
roger that, deleted the build folder and going to rebuild.

**Comment by xekon** [comment]
Just tested, working properly now, whatever you did seems to have fixed the problem, HURRAY!

**Comment by candrews** [comment]
Tried it here and it solved my problem as well! Thanks!

**Comment by FernetMenta** [comment]
@pkerling did you test getting out of powersaving without a mouse or keyboard connected? you removed the mouse pointer warp we had in earlier versions. without this hack my system with just a lirc remote can't disable system screensaver. remotes recognized as keyboard may be able to disable screensaver.

**Comment by xekon** [comment]
@FrenetMenta the only thing I would like to add to that, is that I used the kodi dim screensaver with power saving under Kodi 17 and it worked... I am not sure what could have changed to from 17 to 18 for it to no longer work. I have experience the same thing on more than one system.

Unless there is something to worry about with how @pkerling fixed it, I would use it, because when I tested it seemed to work properly.

**Comment by FernetMenta** [comment]
I forgot that there is a gui setting to enable/disable DPMS. This change should be ok. Sorry for the noise

**Review by FernetMenta — APPROVED** [review]

**Comment by pkerling** [comment]
> did you test getting out of powersaving without a mouse or keyboard connected?

I'll give it a try and add warping back if necessary

**Comment by FernetMenta** [comment]
@pkerling forget about the warping hack, not worth the effort. all fine

**Comment by pkerling** [comment]
@FernetMenta OK - your call!

**Pull request merged**
