### PR TITLE
[settings] move to C++11

### PR DESCRIPTION
**Pull request by Montellese**
After the huge add-on settings work I figured it's finally time to move the settings related code to C++11 by
* using `nullptr` instead of `NULL`
* using the `default` keyword for ctors and dtors
* initializing member variables in the class definition
* using `enum class` instead of just `enum` where it makes sense
* using `using` instead of `typedef`

## Motivation and Context
Easier to read and maintain code

## Checklist:
- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Only win32 was happy :)

**Comment by Montellese** [comment]
Yeah already looking into it. This is the problem with doing copy & paste in VS as it doesn't cover all the files. And the VS compiler is far less strict about C++11 features than GCC ;-)

**Comment by Montellese** [comment]
Finally! Linux didn't like me using `None` as an enum value because it already seems to be defined globally as an integer :-/

**Comment by MartijnKaijser** [comment]
You mean somewhere define that ourselves?

**Comment by Montellese** [comment]
TBH I don't know and I didn't check. Just saw it in the Jenkins build logs.

**Comment by MartijnKaijser** [comment]
I guess this is quite forward and can just be merged?

**Comment by hauihau** [comment]
@Montellese, @MartijnKaijser: there was a commit in #12113  which stated that None is a libX11 macro.

**Comment by Montellese** [comment]
@hauihau thanks for the hint. That's really stupid :-/

**Pull request merged**
