### PR TITLE
keyboard layout improvements

### PR DESCRIPTION
**Pull request by Montellese**
These commits improve the keyboard layout support by
- introducing `CKeyboardLayoutManager` which loads all the keyboard layouts and keeps them in store instead of reading them again everytime the setting is changed or the virtual keyboard is opened
- splitting `keyboardlayouts.xml` into multiple XML files containing keyboard layout definitions for the same language (obviously this could also be done per keyboard layout).

With this in place the next step could be to turn keyboard layouts into resource addons that can then be added/updated independent of releases.

### CODE REVIEW

**Comment by Montellese** [comment]
@mkortstiege: Could I ask you for another Xcode sync? I have already manually removed all references to `xbmc/input/KeyboardLayoutConfiguration.h/cpp` but still need the addition of `xbmc/input/KeyboardLayoutManager.h/cpp`.

**Comment by mkortstiege** [comment]
@Montellese please pick https://github.com/mkortstiege/xbmc/commit/223e705b0008734a15bd158bc667201d2405b64e

**Comment by Montellese** [comment]
@mkortstiege: Thanks. jenkins build this please

**Comment by mkortstiege** [comment]
Is there a reason you just picked the newly added ones instead of the entire sync?

**Comment by Montellese** [comment]
I got a very weird conflict when trying to cherry-pick your commit which I had to manually resolve and there were quite a few changes which didn't have anything to do with this PR (two files didn't even exist in my tree) so I only picked the ones that made sense. Is that a problem?

**Comment by mkortstiege** [comment]
No problem. We just have to ensure we actually sync the project file at some point.

**Comment by Montellese** [comment]
Why does Xcode move around unrelated files anyway?

**Comment by mkortstiege** [comment]
I have no idea. @xhaggi do you know why xcode thinks it is a good idea to re-sort from time to time?

**Comment by Montellese** [comment]
Any objections?

**Comment by mkortstiege** [comment]
Is there a way to specify a default map for given language yet? Having to pre-sort the XMLs or sort alphabetically always triggers weird behavior.

**Comment by xhaggi** [comment]
@mkortstiege I don't know why xcode sorts some unrelated files if you don't use the sorting feature. Better you double check your changes and revert every unrelated lines ;)

**Comment by Memphiz** [comment]
as said - just take it - xcode does it from time to time - don't bother if you are sure those are basically "nops"

**Comment by Montellese** [comment]
@mkortstiege: Well if we'd extend the keyboard layout definitions with a language code we could map them to one or more languages. Then we'd have to add a "match GUI language" option to the keyboard layout setting (which might be a bit tricky since you can select multiple keyboard layouts).

**Comment by mkortstiege** [comment]
@Montellese, I was just wondering if we are actually able to avoid "wrong mapping" like we have in the language / region settings. Like eg, when you switch to german language you will get region Austria (was Belgium before last refactor :p).

So we either have to specify defaults or deal with pre-sorting within the resource files. This is by no means blocking this PR, but since it´s related i thought i might mention it.

**Comment by Montellese** [comment]
jenkins build and merge

**Comment by Montellese** [comment]
@Memphiz: Is it possible that the merge isn't performed if one of the builds is considered unstable? Or is something else broken?

**Comment by mkortstiege** [comment]
@Montellese yes, he mentioned something like this in  https://github.com/xbmc/xbmc/pull/6612#issuecomment-77893489

**Pull request merged**
