### PR TITLE
[Estuary] Add (rating) star symbols to fontset

### PR DESCRIPTION
**Pull request by jeroenpardon**
## Description
This adds unicode characters U+2605 (black star) and U+2606 (white star) to Estuary's Noto Sans font files. For this the characters were taken from the Noto Sans Symbols subset  (https://www.google.com/get/noto/#sans-zsym) and were added to the NotoSans-Regular and NotoSans-Bold font files.
This also updates the font file for Estouchy.

## Motivation and Context
Fixes a discrepancy between the Arial based fontset and the default fonts as described here: https://forum.kodi.tv/showthread.php?tid=322336 Could also come handy in other situations

## How Has This Been Tested?
Added dummy text to a custom label in Estuary using the characters described above

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by phil65 — APPROVED** [review]
Thx!

**Comment by ronie** [comment]
@jeroenpardon i can confirm the issue that's been mentioned in the forum thread.

there's something wrong with the character spacing of U+2605

you can repro by using a label like:
```<label>&#x2605;&#x2605;&#x2605;&#x2605;</label>```
this will result in four stars displayed on top of eachother (it will look like only one star is displayed).

the U+2606 character is fine though.

**Comment by ronie** [comment]
fix: https://github.com/xbmc/xbmc/pull/13060

**Comment by jeroenpardon** [comment]
Yup, something went wrong with setting the size of the glyph.

**Comment by candrews** [comment]
Was this reported to Google?

This issue should really be fixed upstream so all Noto users benefit.

**Comment by ronie** [comment]
i assume it was an error made by @jeroenpardon when copying the glyphs... but i could be wrong ofc

**Pull request merged**
