### PR TITLE
cppcheck performance fixes in osx/

### PR DESCRIPTION
**Pull request by tobbi**
Simple one.

### CODE REVIEW

**Comment by Jalle19** [comment]
jenkins build and merge

**Comment by Memphiz** [comment]
Yes simple one -  but still fat fingered.

1. I have aborted the triggered jenkins build
2. The typo was already reported by jenkins by the former run here - http://jenkins.kodi.tv/job/OSX-64/lastFailedBuild/

**Comment by tobbi** [comment]
Hah, typical. I have fixed Typo.

**Comment by Memphiz** [comment]
thx

**Pull request merged**
