### PR TITLE
[PVR][Esturay] Channelgroup manager dialog: Add support for radio channel groups

### PR DESCRIPTION
**Pull request by ksooo**
This PR adds support for radio channel groups to the PVR Channelgroups manager dialog. Stumbled over this missing feature today - could not believe that this was missing! ;-)

screenshot001
screenshot000

The changes were runtime tested an macOS on latest Kodi master.

@Jalle19 @xhaggi for core code review?
@phil65 @ronie for review of the skin changes?

### CODE REVIEW

**Review by ronie — COMMENTED** [review]
skin changes look ok to me

**Comment by xhaggi** [comment]
Looks good. Never noticed that this is missing too ;)

**Comment by stefansaraev** [comment]
nobody noticed, because nobody really uses it. nobody uses it, because for most users it is useless. and it will be useless as long it does not tell backends "hey, we've re-ordered some channels, change your channel order so next time I do pvr db reset we have the same order client-side". sorta ;)

if you ask me, this feature should be competely ripped out

**Comment by ksooo** [comment]
@stefansaraev thanks for the feedback, although it is not really helpful and motivating.

jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Comment by xhaggi** [comment]
You're right but in case your backend does not support groups your are happy to do it here. Reset the PVR database is not an option for those guys. Along with this you can hide channel groups especially the internal "All channels" group. This option is only available in Kodi.

**Pull request merged**
