### PR TITLE
[Android] ndk-build: delete Android.mk and Application.mk

### PR DESCRIPTION
**Pull request by joseluismarti**
## Description
The configuration files `Android.mk` and `Application.mk` are part of the [ndk-build](https://developer.android.com/ndk/guides/ndk-build) script used to build Android projects.

These files can be deleted as Kodi uses a customized toolchain for the project instead.

## How has this been tested?
It builds and runs fine on Android TV 9

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [X] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by joseluismarti** [comment]
@fuzzard the `Android.mk` file is not used for build, but I forgot that it's needed when using the [ndk-gdb](https://developer.android.com/ndk/guides/ndk-gdb) command for remote debugging.

Sorry, do you revert the commit or do I add this file in a new PR?

**Comment by fuzzard** [comment]
Does ndk-gdb actually work currently. I thought someone had mentioned that it no longer works since we moved to the full grade build?

**Comment by joseluismarti** [comment]
It seems to be working, it connects remotely, uploads and starts `gdbserver` and finally displays the prompt.

Previously we need to copy `jni/Android.mk` to the folder where the project is packaged.

We could clean the code that added the `gdbserver` and `gdb.setup` files to the apk. Currently it prepares these files but does not include them as they are not needed. I will make a PR with these changes.

**Comment by fuzzard** [comment]
Sounds good.

**Pull request merged**
