### PR TITLE
[droid] Define that we possibly use the microphone in Kodi

### PR DESCRIPTION
**Pull request by MartijnKaijser**
## Description
Add the fact that we can use the microphone to the manifest file

## Motivation and Context
We should inform users
https://developer.android.com/guide/topics/manifest/uses-feature-element.html

## How Has This Been Tested?
testing?

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by koying** [comment]
Assuming it is in the context of speech recog, it's not needed because *we* don't record audio: we call a system service for speech-to-text. We don't see the first bit of it being recorded.

RECORD_AUDIO is needed if we actually do recording, with https://developer.android.com/guide/topics/media/mediarecorder.html for instance.

The perm doesn't do any harm per se, ofc, but can be misleading and lead to unneeded anguish (and potentially stupid clickbait articles ;) )

**Comment by MartijnKaijser** [comment]
That was also the thing that crossed my mind :)

**Comment by Hedda** [comment]
@koying @MartijnKaijser what about Kodi (python) addons that want to use the microphone for new features such as Google Assistant and Amazon Alexa, or an karaoke addon? 

Example: https://developers.google.com/assistant/sdk/develop/python/

Would Kodi not need to declare possibly use the microphone in the manifest file for Kodi's (python) addons to be able to access and use the microphone on Android?

**Comment by koying** [comment]
An app *never* uses the microphone in the context of Assistant or Alexa.
The relevant system services do.

I don't see how a python addon could use a microphone under Android unless we create an interface for it, so it's out-of-scope for now.

**Pull request closed without merging**
