### PR TITLE
changed: forward IActionListener in Application.h

### PR DESCRIPTION
**Pull request by notspiff**
before: touch IActionListener.h -> 142 objects rebuilt
after: touch IActionListener.h -> 11 objects rebuilt

before: touch Key.h -> 209 objects rebuilt
after: touch Key.h -> 141 objects rebuilt

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by notspiff** [comment]
missing include added.

**Comment by Paxxi** [comment]
Great stuff, +1

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
