### PR TITLE
[binary addons] use correct library install paths on different linux distros

### PR DESCRIPTION
**Pull request by wsnipex**
@notspiff @Montellese for review please

Since I don't have an red hat based distro around for testing, I'm hoping for feedback from fedora/red hat/centos users.

edit: this PR takes care to install to e.g. /usr/lib64 on red hat based distros, instead of hardcoding /usr/lib

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
@Montellese ok now?

on an unrelated note: the cmake stuff needs to get rid of hardcoded "kodi" in all those paths.

**Comment by Montellese** [comment]
Looks fine now.

**Comment by MartijnKaijser** [comment]
@Montellese ok for merge?

**Comment by Montellese** [comment]
Yes

**Pull request merged**
