### PR TITLE
fix build with -DENABLE_VAAPI=no

### PR DESCRIPTION
**Pull request by stefansaraev**
ref #12089 #12090 #12091

## Description

does this need a team vote or it can be blocked by a single person?

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by hudokkow** [comment]
thx!
jenkins build this please

**Comment by FernetMenta** [comment]
this won't won't get merged into code I maintain
disabling vaapi is of no value at runtime
we also build ffmpeg with vaapi

**Review by wsnipex — APPROVED** [review]
thanks

**Comment by wsnipex** [comment]
@FernetMenta nonsense: ffmpeg builds perfectly fine without vaapi or vdpau if you disable any one of them

**Comment by FernetMenta** [comment]
for the team:
I admitted on internal slack that I am ok with this if we start working on a better solution. the process has started. special thanks to @lrusak and @fetzerch

**Comment by lrusak** [comment]
@stefansaraev are you able to push this branch again and reopen this PR? If not can you pretty please open another PR? thanks :+1:

**Pull request closed without merging**
