### PR TITLE
musicdb: cleanup detection of Singles

### PR DESCRIPTION
**Pull request by Montellese**
Right now we use the condition that an album with an empty title is considered a single and not a real album in multiple places in the code and it's not really standardized or obvious. Furthermore the decision whether an album is actually a single is not done when adding data to the database but rather when retrieving it from the database. I find that a very odd concept.

Therefore I have added a new enumeration `CAlbum::ReleaseType` which can either be `Album` or `Single` and there are methods to translate these to/from strings. Then I've added members of this type to `CAlbum` and `CMusicInfoTag` so that we can easily detect the difference. Last but not least I have added a new column `strReleaseType` to the `album` table which can either be `"album"` or `"single"`. With that we can now do more explicit checks for and distinction between albums and singles which should make the code a bit easier to understand.

Furthermore it allows to better integrate this information into JSON-RPC by providing a `releasetype` / `albumreleasetype` property for albums / songs and a `includesingles` paramter for `AudioLibrary.GetAlbums`.

There is one code place in `CMusicDatabase` which retrieves singles when retrieving all albums for an artist but doesn't retrieve singles when not retrieving the albums of a specific artist which I don't like either. IMO the caller should specify whether to retrieve albums including singles or not. But it's difficult to track down all the calls that implicitly use this logic so I didn't touch it for now.

### CODE REVIEW

**Comment by mkortstiege** [comment]
@Montellese please pick https://github.com/mkortstiege/xbmc/commit/6fd2894070760e8f8477cf861a095a4cb6c64afd for the xcode sync.

**Comment by Montellese** [comment]
@mkortstiege: Thanks. jenkins build this please

**Comment by zag2me** [comment]
Thanks! The strReleaseType field is most welcome!

**Comment by Montellese** [comment]
@zag2me It's not really much right now because what we basically do is that we store all songs that don't have an album set into the same album entry (which has an empty name and `strReleaseType` set to `single`) in the database. Ideally we would be able to group songs that belong to the same single together into a separate album but from looking at ID3 and APE tags that use case is not really supported.

Various Artists handling is even worse. What we do is that we store a localized (i.e. depending on the GUI language) entry in the artist table to which we assign albums that are considered to be from various artists. When the user changes the GUI language it will result in an additional artist entry with the localized name of the new language.
On the album level we have `bCompilation` as a flag that an album is a compilation. What I'm not sure about is whether every compilation is considered to be from various artists and vice versa or not. Furthermore a compilation is an album (and not a single) so it's probably an additional information to the one that an album is an album and not a single.

I just checked MusicBrainz and this is what they do: https://musicbrainz.org/doc/Release_Group/Type. So they also split the release into a primary type (album, single, ep, ...) and additional types (compilation, soundtrack, audiobook, ...).

Disclaimer: I'm not really knowledgeable in the whole music area, all the different types of releases, artists, album artists, etc.

**Comment by zag2me** [comment]
Yes MusicBrainz and TheAudioDB stores the release "type" information. For future reference, valid options are:

Album
Single
EP
Broadcast
AudioBook
Compilation
Demo
DJ-Mix
Interview
Live
Mixtape/Street
Remix
Soundtrack
Spokenword

**Comment by Tolriq** [comment]
@Montellese since I'm in the middle of my new database scheme, can you confirm that by default without the new param the singles won't be returned as albums ?

And with it album titles will still be empty or have the song name ?

**Comment by Montellese** [comment]
Yes singles won't be returned if `includesingles` isn't manually set to true. I didn't want to change the default behaviour.

The album title of songs are empty in the database but will be returned as the localization of "Singles" and will have the `releasetype` property set to `single`.

Do you want me to add the same `includesingles` parameter to `AudioLibrary.GetSongs` (but have it default to `true` to not change behaviour)?

**Comment by Tolriq** [comment]
@Montellese Well the option could be useful for remotes that does not do offline caches but in fact not that much for my use case that needs everything synced and available offline. (As long as they can be used for filters too)

Does requesting albumreleasetype on the songs make the query slower ?

All is about speed when dealing with music as users have often a lot of them and rpi thing is common.

One of the speed impact is the db query on low end devices, but the other slowness is json encoding too, so having to ask for a string to know is sinjgle or album make encoding slower on device, more network bandwith, more memory on remote and more cpu type to analyze a string rather a boolean.

Is it possible to have a "single" boolean on the songs as you have added the compilation one ?

This would fill the basic need at good speed, and still allow the releasetype to be used in future when there's more usage of them for all the musicbrainz and other new types.

**Comment by Montellese** [comment]
`releasetype` and `albumreleasetype` don't require any additional SQL querying so the query shouldn't get slower.

IMO adding a boolean for every release type is not really good design and will result in duplicate information in the API.

Like I said I'm not very knowledgeable in the music area but from the implementation in Kodi it looks like compilation is a different thing than the difference between "album" and "single" as a compilation is also an album and the "only" difference is that there's no album artist.

**Comment by Tolriq** [comment]
TBH neither do I, I'm still trying to understand all the difference to better fill user needs :(

Anyway if there's no slowness then string is not a problem, will just ask for a little smaller chunks to limit impacts.

But then the option to getsongs could be useful for some remotes and keeps things to same level of functions.

**Comment by Montellese** [comment]
OK I added the `includesingles` parameter to `AudioLibrary.GetSongs` as well.

**Comment by Montellese** [comment]
jenkins build this please

**Comment by Montellese** [comment]
jenkins build this please

**Comment by Montellese** [comment]
jenkins build this please

**Comment by Montellese** [comment]
@Memphiz: Is something wrong with this PR or does jenkins simply not like it? http://jenkins.kodi.tv/job/BuildMulti-PR/2652/console

**Comment by Memphiz** [comment]
dunno - jenkins build this please

**Comment by Montellese** [comment]
@Memphiz: Same problem:
```
First time build. Skipping changelog.
Run condition [Always] enabling prebuild for step [BuilderChain]
Unrecognized macro 'ghprbPullId' in 'pr${ghprbPullId}-${GIT_REVISION,length=7}'
Starting build job OSX-64.
Unrecognized macro 'ghprbPullId' in 'pr${ghprbPullId}-${GIT_REVISION,length=7}'
FATAL: null
java.lang.NullPointerException
	at hudson.plugins.git.RevisionParameterAction.<init>(RevisionParameterAction.java:72)
	at hudson.plugins.git.GitRevisionBuildParameters.getAction(GitRevisionBuildParameters.java:68)
	at com.tikal.jenkins.plugins.multijob.PhaseJobsConfig.getActions(PhaseJobsConfig.java:392)
	at com.tikal.jenkins.plugins.multijob.MultiJobBuilder.prepareActions(MultiJobBuilder.java:402)
	at com.tikal.jenkins.plugins.multijob.MultiJobBuilder.perform(MultiJobBuilder.java:108)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.Build$BuildExecution.build(Build.java:199)
	at hudson.model.Build$BuildExecution.doRun(Build.java:160)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
	at com.tikal.jenkins.plugins.multijob.MultiJobBuild$MultiJobRunnerImpl.run(MultiJobBuild.java:134)
	at hudson.model.Run.execute(Run.java:1745)
	at com.tikal.jenkins.plugins.multijob.MultiJobBuild.run(MultiJobBuild.java:73)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
```

**Comment by Montellese** [comment]
Started a manual PR build at http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-PR-Manually/94/ and that looks better.

**Comment by Memphiz** [comment]
I have no clue whats the problem but its dedicated to this PR - others work ... i am going to ignore it for now.

**Comment by Montellese** [comment]
Let's see if a rebase helps. jenkins build this please

**Comment by Montellese** [comment]
I guess jenkin either hates this PR or me. Manual build of the rebased PR started at http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-PR-Manually/95/.

**Comment by Memphiz** [comment]
Still no idea - keep doing it manually please and get rid of this PR as fast as possible ;)

**Comment by Montellese** [comment]
Any objections to this?

**Comment by mkortstiege** [comment]
Other than that I have to rebase `musicdb_xml`, nope ;)

**Pull request merged**
