### PR TITLE
[settings] use positive values for setting control ids

### PR DESCRIPTION
**Pull request by mkortstiege**
This changes the internal control ids to positive values and so enables skins to retrieve the auto-filled labels -- via Control.GetLabel(ID) -- from the category and settings fields.

Requested by @HitcherUK. @Montellese, @ronie, @phil65 for review please.

### CODE REVIEW

**Comment by ronie** [comment]
@HitcherUK mind providing a usecase for this?

**Comment by HitcherUK** [comment]
I recently made Copacetic's context menu appear as though it was using a different fonts for focused and unfocused buttons through the use of a second grouplist filled with labels + visible conditions based on `Control.GetLabel(1001)`, `Control.GetLabel(1002)`, etc.

https://raw.githubusercontent.com/HitcherUK/skin.copacetic/master/16x9/DialogContextMenu.xml

screenshot007

I then remembered this thread on the forum where someone wanted to do something similar with SettingsCategory - http://forum.kodi.tv/showthread.php?tid=244456&pid=2138071#pid2138071

Only when I tried it wouldn't work because `Control.GetLabel(-100)` doesn't work because the values are negative. This PR addresses the issue.

**Comment by ronie** [comment]
while the effect looks very nice, i doubt this is a very reliable solution.

what if a context menu contains more than 15 items? if i read your code correctly,
you've hardcoded it to 15 max.
plugins for instance can create their own context menu, with as many items as they want.
also, since we have context menu addons, users can expand the regular context menu
beyond the number of items kodi itself adds.


as for the settingscategory window, i wonder how you intent to handle the radiobuttons and spincontrols there? or even label2?


instead of adding all this overhead with visible conditions and stringcompares, would it be sufficient if we added a < focusedfont > tag (if possible) to button controls in order to achieve the same effect?

@mkortstiege i'm not bothered by changing the id's to a positive value, i'm more worried about the hackery things skinners intent to do with it.
this change was already requested once years ago and was met with a firm NO from jm.

**Comment by mkortstiege** [comment]
@ronie , jep that's what I mentioned to @HitcherUK as well ;) If Jonathan shot it down there must be a good reason. Wasn't aware of it.

**Comment by HitcherUK** [comment]
@ronie 

RE My context menu: If I find there's a need for more I'll simply add more.

RE SettingsCategory: I personally have no intention of using it there, I simply remembered that thread asking if it could be done and looked in to why it didn't work when I tested it. I haven't replied to the thread so it's no loss.

`<focusedfont>..</focusedfont>` would be a nice addition but probably not an easy one.

**Pull request closed without merging**
