### PR TITLE
changed: Curl's overflow buffer handling

### PR DESCRIPTION
**Pull request by arnova**
@mkortstiege : Please review.

### CODE REVIEW

**Comment by arnova** [comment]
jenkins build this please

**Comment by mkortstiege** [comment]
Not my department really. Maybe @Paxxi could have a look at this as well?

**Comment by Paxxi** [comment]
@arnova Both calls to memcpy should be replaced with memmove afaik. Memcpy where dst and src overlap is undefined behaviour, will need to go through it more thoroughly for rest of the review.

**Comment by arnova** [comment]
@paxxi: Yeah but memmove is slower since it uses an extra buffer and doesn't memcpy start at the bottom?

**Comment by fritsch** [comment]
If it overlaps -> no memcpy.

**Comment by arnova** [comment]
@fritsch / @paxxi: Thanks for the heads up. Just read that memmove() *may* not be that slower after all anyway. Changed it to memmove now.

**Comment by arnova** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
ignore build fail

**Comment by arnova** [comment]
@Paxxi : You're fine with this?

**Comment by Paxxi** [comment]
@arnova yup looks fine

**Pull request merged**
