### PR TITLE
[addons] add missing flag to filesystem translation from binary add-ons

### LINKED ISSUE #24869: Omega beta 3 - pvr.mediaportal.tvserver
Let me start by saying that I didn't have any problems with beta 2. Omega beta 3 gives me problems with viewing the TV.
Apparently everything works, I have the list of channels, the icons and the EPG, I can easily scroll through the entire list of my channels... but when I select one the two wheels in the center of the screen start to turn and the system remains waiting for a few seconds and then stops, as if I had pressed stop
In short, the channel display does not start.
Windows 11 x64 updated to the latest version.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/konucegupo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 pro
 - Kodi version:Omega 21 beta 3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by phunkyfish**
## Description
READ_NO_BUFFER is not translated from binary add-ons to Kodi due it being missing in the translation code.

Background: https://github.com/xbmc/xbmc/issues/24869

## Motivation and context
The flag should be translated

## How has this been tested?
By a user who found the error and spotted the omission.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by phunkyfish** [comment]
Note that really we should be comparing `addonFlags` to `ADDON_READ_NO_BUFFER` but updating filesystem.h in the addon devkit would be an API change. So I propose merging this as is, and adding the missing enum the next time a add-on API change is made. I will introduce ADDON_READ_REOPEN though as it's already part of the API.

**Comment by ksooo** [comment]
> Note that really we should be comparing addonFlags to ADDON_READ_NO_BUFFER but updating filesystem.h in the addon devkit would be an API change. So I propose merging this as is, and adding the missing enum the next time a add-on API change is made. I will introduce ADDON_READ_REOPEN though as it's already part of the API.

Please add a `@todo` so we don't forget that we want to change this later.

**Comment by phunkyfish** [comment]
> > Note that really we should be comparing addonFlags to ADDON_READ_NO_BUFFER but updating filesystem.h in the addon devkit would be an API change. So I propose merging this as is, and adding the missing enum the next time a add-on API change is made. I will introduce ADDON_READ_REOPEN though as it's already part of the API.
> 
> Please add a `@todo` so we don't forget that we want to change this later.

Done

**Comment by phunkyfish** [comment]
> For reference, the changes I wanted to make were #25158
> 
> And they also included addon devkit API update.
> 
> I ended up closing it due to lack of time and motivation.

That's a much more involved change. Makes a lot of sense to do it eventually.

**Comment by phunkyfish** [comment]
Jenkins build this please

**Review by thexai — APPROVED** [review]

**Review by ksooo — APPROVED** [review]

**Pull request merged**
