### PR TITLE
[docs/android] Wrong toolchain

### PR DESCRIPTION
**Pull request by hudokkow**
## Description

Android docs correction
## Motivation and Context

Referenced toolchain is wrong
## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by koying** [comment]
Toolchain is whatever you want, really, but the jenkins standrard is, e.g, 
```
android-toolchain-aarch64-21-r12b
```

So, the fix is not necessary, and might be misleading in some cases, so -1 from me

**Comment by hudokkow** [comment]
While doing other stuff yesterday, I tried to set up an android build env and, without this change, it gave me an error. Something like "android-linux-aarch64-4.9 is not a valid toolchain, bla, bla, bla..."

Error might be due to my lack of attention or PEBCAK.

**Comment by koying** [comment]
Ah, my mistake. Was confusing 2 "toolchain" notions ;)
Yep, this one is correct, +1

**Comment by hudokkow** [comment]
Thx.

**Pull request merged**
