### PR TITLE
[xbmc][utils] Reworked AutPtrHandle to make it a generic scopeguard

### PR DESCRIPTION
**Pull request by Paxxi**
Not sure if it's the prettiest solution but there's no way to specify the function in the template that I know of.

I wanted to avoid using a functor to make it as easy as possible to use without wrapping a close method for every place it's used.

### CODE REVIEW

**Comment by Paxxi** [comment]
@Montellese review please
jenkins build this please

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
jenkins build this please

**Comment by Paxxi** [comment]
hopefully last try
jenkins build this please

**Comment by mkortstiege** [comment]
@Montellese, @FernetMenta, @ace20022 mind having a look?

**Comment by Montellese** [comment]
Looks good to me apart from the minors. Nice work on the generalization.

**Comment by Paxxi** [comment]
ok let's test this
jenkins build this please

**Pull request merged**
