### PR TITLE
[Backport][Python] Add Python lzma module

### PR DESCRIPTION
**Pull request by matthuisman**
## Description

backport of https://github.com/xbmc/xbmc/pull/19927

would be nice to have all Python3 having the lzma library available.
Instead of just python3 on 20+, but not 19.
It is a built-in library since python 3.3

Also, the Windows kodi build on 19 has it available.
So this also makes all builds consistent 

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
Found an issue with the master version of this. Ive got a fix in #20034 , but you will need to cherry-pick https://github.com/xbmc/xbmc/pull/20034/commits/7b2d6fa8075f40432d69bf8e31add326492737b1

The fault is a potential race in depends build order (xz may get built before gettext, but is a dependency of xz)

**Review by fuzzard — CHANGES_REQUESTED** [review]
cherry-pick https://github.com/xbmc/xbmc/pull/20034/commits/7b2d6fa8075f40432d69bf8e31add326492737b1 to fix potential race with xz and gettext

**Comment by matthuisman** [comment]
done - thank you :)

**Comment by DaveTBlake** [comment]
> up to @DaveTBlake, but if fixes some addons, it might be worth it. Risk should be pretty low

I'm good for this to go in when @fuzzard is happy

**Comment by fuzzard** [comment]
Jenkins build this please

have had some apple build failures due to dependency downloads the last few days. failure was most likely one of them

**Review by fuzzard — APPROVED** [review]

**Review by garbear — APPROVED** [review]

**Comment by matthuisman** [comment]
@DaveTBlake 
This ok to go in?
 I suspect 19.2 is close so be nice to have in that

**Pull request merged**
