### PR TITLE
Don't change fileending to png

### PR DESCRIPTION
**Pull request by razzeee**
## Description

The svg should not be renamed to png

## Motivation and context

Oversight of my last PR

## What is the effect on users?

Flatpak builder got a new check and now fails with this
```
{
    "errors": [
        "non-svg-icon-in-scalable-folder"
    ],
    "info": [
        "non-svg-icon-in-scalable-folder: ['/tmp/tmp2tspvnbd/icons/hicolor/scalable/apps/tv.kodi.Kodi.png']"
    ],
    "message": "Please consult the documentation at https://docs.flathub.org/docs/for-app-authors/linter"
}
```
https://buildbot.flathub.org/#/builders/33/builds/16269

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by razzeee** [comment]
Build failures are OSX, so unrelated

**Review by garbear — APPROVED** [review]
Change follows from the description and looks correct.

**Comment by enen92** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by razzeee** [comment]
Now some part of android builds is failing (not all), which also seem unreleated

**Comment by razzeee** [comment]
Jenkins build this please

**Pull request merged**
