### PR TITLE
video/PlayerController.cpp Bug and Fix

### PR DESCRIPTION
**Pull request by drthaipham**
ACTION_INCREASE_PAR, and ACTION_DECREASE_PAR tries to clamp PixelAspectRatio to 0.5-2.0.
But it fails because of incorrect variable use.
## Description

original line 255:
 CMediaSettings::GetInstance().GetCurrentVideoSettings().m_CustomZoomAmount = 2.f;
changed to:
CMediaSettings::GetInstance().GetCurrentVideoSettings().m_CustomPixelRatio = 2.f;

original line 265:
if (CMediaSettings::GetInstance().GetCurrentVideoSettings().m_CustomZoomAmount < 0.5f)
changed to:
if (CMediaSettings::GetInstance().GetCurrentVideoSettings().m_CustomPixelRatio < 0.5f)

## Motivation and Context

With the current unpatched code, a script can set PixelAspectRatio to unlimited positive
and negative floating point value.
If INCREASE_PAR, and DECREASE_PAR works as intended, a script can set the PixelAspectRatio to 0.5 by decreasing 151 steps; then, starting from a known point, set any PixelAspectRatio desired.

## How Has This Been Tested?

compiled for Jarvis, Krypton on Android. Tested on Amazon firetv.

Virtual Box windows 7 host, Ubuntu 16.04 LTS. Compiled for Arm. Have scripts tried
to decrease PixelAspectRatio and IncreasePixelAspectRatio to out of range. The fix works.

## Types of change

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [x ] All new and existing tests passed

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@fritsch @FernetMenta ping

@drthaipham it's best to always create a separate branch from our master when doing a pull request as you now have a " merge pull"  commit that shouldn't be there. See https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md  how to do that

**Comment by FernetMenta** [comment]
looks good

**Comment by da-anda** [comment]
so you did the next step in becoming a developer for Kodi and created your first PR, great 👍 

As Martijn pointed out, it's best to use a separate branch (locally and on your personal github repo) that contains all the changes related to a specific PR. So for your upcoming second PR please use a separate branch. Using branches also allows you to work on several changes in parallel (having multiple PRs up) while still being able to do adjustments to each of them if needed. Feel free to ask further question in your forum thread, as every comment on github will send out mail notifications to a lot of people which we don't want to spam with unrelated stuff.
Thanks again for your contribution.

**Comment by drthaipham** [comment]
Thank you all. I am sorry about breaching protocol with respect to a new branch. I will make sure the next PR will comply with protocols. I am not a programmer. The last time I wrote any code Stroustrup 1st edition was current.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
