### PR TITLE
[Estuary] Update versions icon for views

### PR DESCRIPTION
**Pull request by Hitcher**
## Description

Updates all views with the new versions.png from @samfishermike.
## Motivation and context

Consistency with the icon used in video info for the versions button.
## How has this been tested?

Tested locally.
## Screenshots (if appropriate):
Old icon in views:
screenshot00000

screenshot00001

Video info:

screenshot00007

New icon in views:

screenshot00006

screenshot00002

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [x] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ksooo** [comment]
Can we just copy the versions.png file we use in the info dialog or does it need to be converted somehow (other resolution/dimensions/…)?

And what about DefaultVideoVersion.png ?

**Comment by Hitcher** [comment]
> Can we just copy the versions.png file we use in the info dialog or does it need to be converted somehow (other resolution/dimensions/…)?

Yes, the other overlays are also resized depending on where they are displayed.

> And what about DefaultVideoVersion.png ?

Missed that. Will probably need @samfishermike to provide us with a larger version.

**Comment by ksooo** [comment]
> Missed that. Will probably need @samfishermike to provide us with a larger version.

Yes, I already reached out to him internally and he wanted to work on this.

**Comment by Hitcher** [comment]
> Yes, I already reached out to him internally and he wanted to work on this.

Just found the conversion. Once he's done I can either add them to this PR or you can make another one.

**Comment by ksooo** [comment]
> Once he's done I can either add them to this PR or you can make another one.

Let's put the default png also into this PR, assuming Sam will find some time soon.

**Comment by Hitcher** [comment]
Updated icons:

screenshot00030

screenshot00025

screenshot00026

screenshot00028

screenshot00029

screenshot00027

**Comment by Hitcher** [comment]
@ksooo added all icons from @samfishermike

**Comment by jurialmunkey** [comment]
Is the extras icon used anywhere other than info dialog? I'm wondering if it being so similar in appearance to favourites icon will be a problem.

In info dialog it's fine with the text but might be confusing as an overlay. If I saw a star on a poster I'd be thinking it either means favourite or new, not that it has extras.

**Comment by ksooo** [comment]
Currently the extras png is only used in the info dialog. And for omega this will be it.

**Comment by jurialmunkey** [comment]
> Currently the extras png is only used in the info dialog. And for omega this will be it.

If it's only info then no issues from me. Good enough for now. Text makes it clear what it does. 

I just saw the [overlay icon for extras in the files](https://github.com/xbmc/xbmc/blob/7c5a90fb93ea77d673dd2f25041e0f9de854b494/addons/skin.estuary/media/overlays/extras.png) so wasn't certain. 

@Hitcher - Maybe we should remove the overlay version if it isn't going to be used? It's tiny but I'm also mindful of how easily unused texture files accumulate which then become a pain to cleanup later.

**Comment by Hitcher** [comment]
> Maybe we should remove the overlay version if it isn't going to be used? It's tiny but I'm also mindful of how easily unused texture files accumulate which then become a pain to cleanup later.

Sure, I was just future-proofing for if/when they become a thing so they didn't get lost.

**Review by jjd-uk — APPROVED** [review]
I think we can do better, but it's an improvement on what we already have so approved.

**Comment by ksooo** [comment]
> I think we can do better

Whatever "better" means and whoever "we" is in this context. :-)

**Review by ksooo — APPROVED** [review]

**Comment by jjd-uk** [comment]
While it's a lot better, it doesn't scream versions to me and we would most likely be "me". Anyway bottom of the pile for me to look at any further at the current time.

**Pull request merged**
