### PR TITLE
[cmake] support building with ninja on posix platforms

### PR DESCRIPTION
**Pull request by wsnipex**
2nd try for https://github.com/xbmc/xbmc/pull/12920

@MilhouseVH could you try this and include it in your nightlies?

### CODE REVIEW

**Comment by MilhouseVH** [comment]
This looks good now, it will be in tonight's builds. Thanks.

**Comment by Rechi** [comment]
jenkins build this please

**Comment by MilhouseVH** [comment]
Just one problem...

Testing on Ubuntu with latest kodi master (75bddb4e059c12f94238c35deaad9027fc55cd90) + PR12936:

```
neil@nm-linux:~/projects$ curl --header 'Content-Type: application/json' --data-binary '{"jsonrpc": "2.0", "method": "JSONRPC.Version", "id": "libVersion"}' 'http://localhost:8080/jsonrpc';echo
{"id":"libVersion","jsonrpc":"2.0","result":{"version":{"major":0,"minor":3,"patch":0}}}
```

The JSON version is reported as `0.3.0`

Without this PR, the JSON version reported by Kodi on Ubuntu is `8.3.0`.

**Comment by wsnipex** [comment]
should be fixed now, thanks for testing

**Comment by MilhouseVH** [comment]
It builds OK on Ubuntu (and the version is correct), but when building with LibreELEC (and ninja) I'm getting this build failure: http://sprunge.us/OWHW

**Comment by MilhouseVH** [comment]
The above build failure is fixed with this addition in LibreELEC: https://github.com/LibreELEC/LibreELEC.tv/pull/2092/commits/1264fd38adf20c6cf0ca2bc8baa6a4a79b75f93f

Ubuntu and LibreELEC have now built, and the JSON version is being returned as 8.3.0 - this PR seems to be OK now, many thanks!

**Comment by wsnipex** [comment]
added a fix for building jsonschemabuilder when c++11 is not default, so the LE workaround shouldn't be needed anymore.

**Comment by MilhouseVH** [comment]
Thanks - LE commit dropped.

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by afedchin** [comment]
win-arm-uwp build error isn't related. will be fine on next build

**Pull request merged**
