### PR TITLE
VideoPlayer: render some debug info

### PR DESCRIPTION
**Pull request by FernetMenta**
see title
@popcornmix could you test this

@phil65 @ronie player.showcodec is history

### CODE REVIEW

**Comment by popcornmix** [comment]
Yes, it works for me. (OMXPlayer currently seg-faults - AddOverlay is called with a null overlay).
I still miss the resolution and codec name (mostly for the distinction in name for software/hardware decoding).

**Comment by FernetMenta** [comment]
I am not sure if I want to have the codec name back. All static info can easily be accessed by looking into the log. Why do you want to waste resources with this?

**Comment by phil65** [comment]
@FernetMenta: the removal of player.showcodec applies to both music and video playback?

**Comment by popcornmix** [comment]
The codec (and if it is hardware accelerated) is something I check on often, and it is frequently recommended on forums when a user has issues with video not playing smoothly to use the codec info.
The resolution/aspect ratio can also be useful, especially with live TV when they can change dynamically.

**Comment by FernetMenta** [comment]
@phil65 yes
@popcornmix you could add an optional line activated by an environment variable. The old code was ugly because id added methods to interfaces just to query debug info. The info you are looking for is already in RenderManager.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by wiromare** [comment]
@FernetMenta

i was testing this just for curiosity 

when "Sync playback to display" is disabled the generated std::string vsync is empty and then
m_overlay[3] is NULL

so there is a problem (at least on windows) here in 
CDebugRenderer::SetInfo
...
m_overlayRenderer.AddOverlay(m_overlay[3], 0, 0);

maybe with these fixes can save you some time
 
https://github.com/wiromare/xbmc/commits/debug

**Comment by popcornmix** [comment]
omxplayer needed a similar crash-fix: https://github.com/popcornmix/xbmc/commit/5041d4a9f84903111fd75f224c06b4550ee6c89e
There is also an issue when stopping a video with codec info displayed means it is enabled next time and can't be disabled. See: http://forum.kodi.tv/showthread.php?tid=250817&pid=2270656#pid2270656

**Comment by FernetMenta** [comment]
@wiromare thanks, I cherry picked your VS update. I want to displayer the various info always on the same line, so I fixed the segfault differently.
@popcornmix the state is now reset when playing a new video. does it fix the issue?

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by ace20022** [comment]
> The codec (and if it is hardware accelerated) is something I check on often, and it is frequently...

+1 please re-add it

**Comment by anaconda** [comment]
I've got a seg-fault with this PR if codec info is shown when video ends:
https://clbin.com/pcz21

[This build](http://forum.kodi.tv/showthread.php?tid=250817&pid=2271855#pid2271855) includes the following commit, so it could be responsible or not:
https://github.com/popcornmix/xbmc/commit/cc953937840de3c9d691fd7ebb7a5177c9048427 // cc @popcornmix

I also see an issue with subtitle height (possibly font etc too - haven't tested, but: https://github.com/xbmc/xbmc/commit/384d12e7abee10e898fc6fb9bbd3f743c2ce7950#diff-67ddd9c6e974d01b9332694eb00e89efR45).
If codec info is shown before subtitles, subtitles ignore the configured height and use 16 (hint: https://github.com/xbmc/xbmc/commit/384d12e7abee10e898fc6fb9bbd3f743c2ce7950#diff-757e05adc9f073a54d8d631680e38824R117). If codec info is brought up after any subtitle, it'll use the configured subtitle height and it is completely unreadable.

**Comment by popcornmix** [comment]
The codec overlay gets removed frequently with this PR. Videos that have changes in resolution cause it - I suspect any renderer reconfigure causes the codec overlay to be disabled.

**Comment by FernetMenta** [comment]
> I suspect any renderer reconfigure causes the codec overlay to be disabled.

correct

**Comment by FernetMenta** [comment]
@popcornmix I disabled it there because you or @MilhouseVH mentioned that debug info did stay after stop/start of a video. I was not able to reproduce here. Feel free to propose a better solution.

**Pull request merged**
