### PR TITLE
[dialogs][guillib] CGUIDialogKaiToast now only closes the dialog if t…

### LINKED ISSUE #17441: Toast messages are too short
Toast messages are truncated & disappear before the text can be read

Estuary update bug

Recommendation:

- Increase default delay time
- Include an option in skin settings:
    `Time to display toast messages on screen (in seconds)`

Consider using [xperience1080](https://github.com/xperience1080/skin.xperience1080) skin as a design guide for toast message presentation ; the animation is also quite polished and worthy of emulation

XP update bug

### PR DESCRIPTION
**Pull request by ksooo**
CGUIDialogKaiToast now only closes the dialog if the whole toast text was displayed at least once.

Fixes #17441

No idea who could do a code review as guilib and dialogs code seems to be orphaned.

@MilhouseVH maybe you can add this PR to your testbuilds and if nobody complains for let's say a week we gonna merge this.

### CODE REVIEW

**Comment by howie-f** [comment]
cannot say much to the code, but the 1st appearing message...

screenshot002

is instantly overridden by the 2nd...

screenshot004

which stays until the message scrolled to the end

**Comment by ksooo** [comment]
@howie-f thanks for the feedback. I will have a look.

> but the 1st appearing message is instantly overridden by the 2nd...

 Not caused by my PR, this has been like this before the PR. Needs fixing, nevertheless.

> which stays until the message scrolled to the end

 This is what my PR is intended to do.

**Comment by ksooo** [comment]
@howie-f force-pushed an update. Could you retest, please?

**Comment by howie-f** [comment]
@ksooo now the 1st is scrolling to the end like it should, the 2nd then pops up for 0,01 nanoseconds and is unreadable

**Comment by MilhouseVH** [comment]
> @MilhouseVH maybe you can add this PR to your testbuilds and if nobody complains for let's say a week we gonna merge this.

Yes, however only once the issues identified by @howie-f are resolved!

**Comment by ksooo** [comment]
@howie-f another force-pushed try. I think now we have it. Could you please retest?

**Comment by howie-f** [comment]
yo. one moment please..

**Review by howie-f — APPROVED** [review]

**Comment by ksooo** [comment]
@MilhouseVH seems to work now.

**Comment by MilhouseVH** [comment]
Ok, will include in `#0427`.

**Comment by ksooo** [comment]
No negative feedback from Milhouse build testers. Merging...

**Pull request merged**
