### PR TITLE
[estuary] - drop some PVR viewtypes

### PR DESCRIPTION
**Pull request by phil65**
Drop all viewtypes from PVRGuide except the epg grid.
Core changes will be done for v18, but lets drop it for our default skin now already.

### CODE REVIEW

**Comment by phil65** [comment]
Fuck you, silly bot. :)

**Comment by ronie** [comment]
@mention-bot please tell @phil65 that @ronie approves these changes.

**Comment by Jalle19** [comment]
Requested by @xhaggi on Slack, I think everyone there agreed at the moment. @ksooo what do you think?

**Comment by xhaggi** [comment]
@ronie it would be great if you could inform our skinners that the views are deprecated and removed in v18. Better they drop it now, like we do for Estuary.

**Comment by ronie** [comment]
@xhaggi done: http://forum.kodi.tv/showthread.php?tid=291411

**Comment by xhaggi** [comment]
@ronie thanks 👍

**Comment by ksooo** [comment]
> @ksooo what do you think?

@jabbera /me thinks that first day in office after devcon sucks really hard. Despite from this i'm fine with this PR.

**Pull request merged**
