### PR TITLE
[gui] Add icon for Blu-rays.

### PR DESCRIPTION
**Pull request by ace20022**
Rebase of https://github.com/xbmc/xbmc/pull/6946. It's not optimal, especially when there are multiple drives available, but I have not time to work me in that part and refactor it.

Could someone please make the icon DefaultBluray.png? Maybe @ronie?<br /><br /><br /><br />

<p align="center">In memory of @un1versal.</p><br /><br />

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Any specific reason to not put it in v18? Does it have issues with multiple drives?

**Comment by ace20022** [comment]
> Any specific reason to not put it in v18? Does it have issues with multiple drives?

I thought it is a problem that the icon is missing. And it needs more testing, especially on non win desktop platforms.

**Comment by ronie** [comment]
here you go, click below:
defaultbluray

**Comment by ronie** [comment]
@ace20022 here's a better version:
defaultbluray

**Comment by ace20022** [comment]
The last commit only has an effect if folder stacking is disabled. For bds I want to add a thumb from the bds meta data if possible.

**Pull request merged**
