### PR TITLE
support actions video hardware accelerator

### PR DESCRIPTION
**Pull request by tiandaochu**
support Actions video hardware accelerator。

We add a micro “HAS_LIBACTSCODEC", you can enable it when run configure command by add an option like "--enable-codec=actcodec"

/cc @koying

### CODE REVIEW

**Comment by mkortstiege** [comment]
@koying mind having a look?

**Comment by koying** [comment]
Well, my vision is to not try and maintain soc specific codecs for android but to enforce mediacodec.
There is just too many soc's and too few devs ;)

So -1 for me. 
"Actions" has to improve their mediacodec support if it's problematic. Same for rockchip, himedia, ... and even aml

**Comment by MartijnKaijser** [comment]
I'd agree with @koying and stagefright implementation will die anyway right?

**Comment by koying** [comment]
Indeed, stf will die. Not even speaking of the code, here, but on the principle ;)

**Pull request closed without merging**
