### PR TITLE
[pvr] drop PVRFile

### PR DESCRIPTION
**Pull request by FernetMenta**
This drops PVRFile. It was an additional layer between VideoPlayer and PVR addons that tuned out not be be useful.

The next step is to drop InputStreamPVRManager and move those functions to InputStream. This will cut the dependency from VideoPlayer to PVRManager.

### CODE REVIEW

**Comment by ksooo** [comment]
much appreciated

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by ksooo** [comment]
@FernetMenta just discovered that there was one imo interesting use case that broke due to this PR: In Jarvis file manager one can add a source "pvr://recordings/active" (would be pvr://recordings/tv/active in Krypton, btw), then enter this virtual directory and for instance copy a recording file to some other location, for instance to insert the recording file into the video library. File copy was implemented via CPVRFile and obviously does not work anymore. Do you have an idea for an alternative implementation? I fear there is none, as all the file manager stuff relies on VFS, right?

**Comment by FernetMenta** [comment]
@ksooo those type of things may have worked somehow but very unstable. PVR was never designed to extend VFS. In some other places like thumbnail extraction we need ugly hacks to exclude PVR.
Once we have an extension point for VFS (open PR by notspiff) and @AlwinEsch has completed his work on binary addons interface, a binary addon can have multiple extension points and we can reevaluate those use cases.

**Pull request merged**
