### PR TITLE
OSX: fix fullscreen on Mojave

### PR DESCRIPTION
**Pull request by FernetMenta**

### CODE REVIEW

**Comment by ksooo** [comment]
Runtime-tested. When started in window mode, switching between window/fullscreen back and forth using cmd F now working, but still black screen on startup.

**Comment by ksooo** [comment]
Increasing the number of gl context updates to 5 did the trick for me. It's working now. 👍

**Comment by MartijnKaijser** [comment]
Ok to merge?

**Comment by FernetMenta** [comment]
I know that it works on 10.14 with XCode 10 but I have no idea about older configs. Maybe someone with an older OS can test this.

**Comment by ksooo** [comment]
> I know that it works on 10.14 with XCode 10 but I have no idea about older configs. Maybe someone with an older OS can test this.

Same here, unfortunately. Only 10.14 avail.

**Comment by garbear** [comment]
I'm on 10.12.6. I can test.

**Comment by garbear** [comment]
What am I even testing? @FernetMenta you didn't include any description, cause, explanation, nothing.

From ksooo I gather that this is a runtime issue, it only occurs when starting in window mode, and it is reproduced by pressing cmd F. Is the bug a black screen? Is the bug the inability to enter fullscreen?

I can reproduce neither. Starting in windowed mode does not show a black screen. Cmd F switches to fullscreen. I applied the fix here and observed no difference.

**Comment by Memphiz** [comment]
Also how was the 5 determined? A little comment on that code would be nice IMO. 
I tried it on El Capitan and it works but I don‘t think I did the right tests.
For testing this one would need to do an adjust refresh rate scenario with the test build. I am currently only able to test on the notebook were there is no refresh rate switching possible.
@garbear in case you can test this - simply ensure that refresh rate switching is working and Kodi UI and video are visible in fullscreen

**Review by Memphiz — APPROVED** [review]
Lets hope the best that 5 is generically correct.

Just for completeness - this PR fixes an issue when Kodi is compiled with Xcode 10 and run on Mojave 10.14. The former is not the case on jenkins atm - so not much to see.

**Pull request merged**
