### PR TITLE
[binary addons] turn PACKAGE_ZIP into a proper cmake option

### PR DESCRIPTION
**Pull request by Montellese**
This small change turns the existing `PACKAGE_ZIP` option of our binary addons buildsystem into a proper cmake build option. It doesn't change anything concerning the behaviour or result.

### CODE REVIEW

**Comment by wsnipex** [comment]
+1

**Comment by Montellese** [comment]
jenkins build and merge

**Comment by hudokkow** [comment]
Shameless off-topic but can you rebase kodi-cmake, @notspiff? It doesn't build right now (missing CMakeLists.txt on kissfft) and way behind master.

**Comment by notspiff** [comment]
Yeah been focused on other things lately. Will get back on the horse soon.

**Comment by hudokkow** [comment]
Thanks. Hope everything is OK with you. ;)

**Comment by Montellese** [comment]
@wsnipex: All binary addons failed on linux with
```
CMake Error at /home/jenkins/workspace/LINUX-64/tools/depends/target/binary-addons/x86_64-linux-gnu/build/depends/lib/kodi/addon-helpers.cmake:85 (message):
  CMAKE_INSTALL_PREFIX
  /home/jenkins/workspace/LINUX-64/tools/depends/target/binary-addons/x86_64-linux-gnu/.install
  differs from Kodi prefix
  /home/jenkins/workspace/LINUX-64/tools/depends/xbmc-depends/x86_64-linux-gnu.
  Please pass -DOVERRIDE_PATHS=1 to skip this check
Call Stack (most recent call first):
  CMakeLists.txt:26 (build_addon)
```
Any idea? All other platforms are fine.

**Comment by wsnipex** [comment]
for some strange reason it thinks the install prefix is not writeable:
-- -DCMAKE_PREFIX_PATH=/home/jenkins/workspace/LINUX-64/tools/depends/target/binary-addons/x86_64-linux-gnu/build/depends/home/jenkins/workspace/LINUX-64/tools/depends/xbmc-depends/x86_64-linux-gnu-DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>-DPACKAGE_CONFIG_PATH=/home/jenkins/workspace/LINUX-64/tools/depends/target/binary-addons/x86_64-linux-gnu/build/depends/lib/pkgconfig-DCMAKE_BUILD_TYPE=Release-DCMAKE_USER_MAKE_RULES_OVERRIDE=-DCMAKE_USER_MAKE_RULES_OVERRIDE_CXX=-DCORE_SYSTEM_NAME=linux-DBUILD_SHARED_LIBS=1-DCMAKE_C_FLAGS=-fPIC -DPIC   -DCMAKE_CXX_FLAGS=-fPIC -DPIC -g -O2 -std=gnu++11  -DCMAKE_TOOLCHAIN_FILE=/home/jenkins/workspace/LINUX-64/tools/depends/target/binary-addons/x86_64-linux-gnu/build/depends/share/Toolchain_binaddons.cmake
-- Building following addons: all
-- check_install_permissions: 1
-- NEED_SUDO: TRUE

I've seen this once in the past, but wasn't able to reproduce on a 2nd jenkins build.
lets see: jenkins build addons please

**Comment by wsnipex** [comment]
this time linux built fine, so once more not able to repro.
OSX and Win had git issues.

**Comment by notspiff** [comment]
@hudokkow rebased. History is still dirty. The rebase was a real bitch and out of patience right now.

**Comment by hudokkow** [comment]
@notspiff thanks

**Pull request merged**
