### PR TITLE
fixed: Flagging video aspect ratio was broken (partially fixes #15934)

### LINKED ISSUE #15934: After playing a movie, all the subtitles and video aspect information disappeared
### Describe the bug
Here is a clear and concise description of what the problem is:

For a MKV movie with subtitle tracks, after playing the movie (or just playing for several minutes), all the subtitles and video aspect information for the video file disappeared from streamdetails table of video database. All the subtitle stream records for the video file were deleted, the fVideoAspect field for video stream was cleared. This issue only appears in 18.2rc1, works fine in 18.1, should be a bug introduced by https://github.com/xbmc/xbmc/pull/15589

Aeon MQ8 skin has these information displayed, so it's very easy to see this bug with that skin. Because this stream detail auto update feature, I can't fix these information by using a NFO file, I think give user an option for this behavior is better. For example, Aeon MQ8 skin doesn't support to show some aspect ratio, I manually edit the NFO file to override the data, but it got override by this update, which is not what I want. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by arnova**
I don't understand why this previously worked, but at least this fixes one of the issues in #15934

### CODE REVIEW

**Comment by arnova** [comment]
@FernetMenta : Please comment. Perhaps you understand why the subtitle information is missing as well (as mentioned in the issue).

**Comment by FernetMenta** [comment]
@arnova aspect ratio is an optional field for stream details and only valid for a few containers like mkv and DVDs. If you set it like this, stream details might be incorrect because ar can change midstream for other containers.

**Comment by phunkyfish** [comment]
@arnova do you want to progress this, close it or put it on the backburner?

**Comment by arnova** [comment]
Also backburner please, also don't know how to proceed with this atm.

**Pull request closed without merging**
