### PR TITLE
[cleanup] unify method name used for singleton pattern

### PR DESCRIPTION
**Pull request by xhaggi**
This unifies the method name used for singleton design pattern by renaming all `Get()` methods to `GetInstance()`.

@Montellese as discussed at Slack, mind taking a look.

### CODE REVIEW

**Comment by Montellese** [comment]
Thanks for doing this tedious work.

**Comment by Paxxi** [comment]
Awww but get is so much shorter, can't you change it again? :)
Enough with the trolling, nice cleanup.

**Comment by xhaggi** [comment]
I've talked to @Montellese about the same and we decided to choose `GetInstance()` because there are classes where `Get()` is used to return something else.

**Comment by xhaggi** [comment]
jenkins build this please

**Comment by arnova** [comment]
Nice work. I have to agree that GetInstance() is more clear as to what it really does.

**Comment by xhaggi** [comment]
jenkins build this please (next try)

**Comment by xhaggi** [comment]
jenkins build this please (3. try, because of git checkout issues)

**Comment by xhaggi** [comment]
jenkins build and merge

**Comment by xhaggi** [comment]
jenkins build and merge

**Comment by xhaggi** [comment]
build errors are unrelated.

**Pull request merged**
