### PR TITLE
Add Korean Dubeolsik Layout and Change Korean glyphs

### PR DESCRIPTION
**Pull request by mjkim0727**
## Description
Add Korean Dubeolsik(두벌식) Layout.
arial.ttf Hangul Glyphs were changed Noto Sans CJK KR.

## Motivation and Context
changed Korean Font Glyphs and added Korean Input method

## How Has This Been Tested?
Tested on 18.9 Leia

## Screenshots (if appropriate):

Korean Dubeolsik(두벌식) Layout - tested on 18.9 Leia

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [X] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by scott967** [comment]
We currently bundle the NotoSans SIL Open Source Font V1.1 license with the Estuary fonts.  Is that sufficient for this or is an additional license file needed?

**Comment by scott967** [comment]
This might get better response if the two commits were split into their own PRs.  Maybe "Dubeolsik Layout" could be viable for 19.1?  Then consider the font change separately.

**Comment by CastagnaIT** [comment]
for information only, for Nexus
I planned the definitive removal of arial.ttf that will be replaced by the standard noto sans regular

this because this font file is already a ugly mixture of different ttf fonts, has nothing to do with arial, and since it is not updated there are also missing some gliphs

but this operation can only be done after the merge of PR #20552
therefore no new fonts will need to be added to make this layout to work (on nexus)
i suggest to postponed until the mentioned changes will be made

**Comment by scott967** [comment]
Agreed, but maybe originator could modify the PR to just provide the keyboard commit?  I still think that is a worthwhile improvement.

**Comment by scott967** [comment]
Originator @kuroehanako , are you still pursuing this?  I think for now maybe close this PR and just submit the keyboard commit for v20

**Pull request closed without merging**
