### PR TITLE
[GLES] Silence debug message for videoscreen.limitedrange

### PR DESCRIPTION
**Pull request by lrusak**
This should quell the warning on other platforms.
```
 DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
```

### CODE REVIEW

**Comment by FernetMenta** [comment]
it will result in a mess if platfoms have to add settings that are not available. where is the settings requested for platforms that don't support it?

**Comment by lrusak** [comment]
@FernetMenta because we put the settings in platform specific ones it isn't available on platforms with without the XML file.

So anywhere that gles is used and the limited setting is checked there will be this log message if the setting isn't present.

**Comment by FernetMenta** [comment]
the setting should only be queried by CWinSystemXXX::UseLimitedColor(), that can be overridden by the platforms that implement it. CWinSystemBase::UseLimitedColor should just return false

**Comment by lrusak** [comment]
That's a much better solution.

**Pull request closed without merging**
