### PR TITLE
[tools/depends][target] bump openssl 1.1.1m

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Bump Openssl 1.1.1m

## Motivation and context
dependency bumps.

redoes #20129 but fixes the android failures that @wsnipex experienced
supersedes #20141

Through bisecting openssl, found that the following 2 commits were the root case of the android failures in wnsipex's previous bump attempt. At this stage, will look to patch those 2 commits out. My understanding is the getauxval usage is only about potential runtime detection of soc capabilities, but will fall back to pre 1.1.1l behaviour without

https://github.com/openssl/openssl/commit/b2dea4d5f22ec146373324c282fb1bcecd5a7d90
https://github.com/openssl/openssl/commit/2357e6e94a46362dbf56eecfec6ffbaa8bd76a68

Have also done a "cleanup" of the openssl config.
Apple platforms have a "kodi" config file for easy setup. Easier to run this than to patch the default configurations for our build usage

Android uses the openssl android build target, rather than the generic linux one previously used.

Removed some sed usage, and now just set/utilise env vars appropriately

## How has this been tested?
osx x86_64 build/run
aarch64 android build/run

## What is the effect on users?
N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by wsnipex** [comment]
looks fine for me. I wonder if we still need "no-asm" for linux, maybe that could be restricted to non x86 or dropped completely?

**Comment by fuzzard** [comment]
The no-asm thing is an interesting one. Macos still actively needs it as strange as that sounds.

As for Linux, I didn't really see a benefit to changing it. I'm still not even sure anyone uses tools/depends for actual real world Linux build, to me it just seems a CI only thing

**Comment by wsnipex** [comment]
agreed, was just curious.

**Review by wsnipex — DISMISSED** [review]

**Comment by fuzzard** [comment]
Tested on OSX/android aarch64. Can download add-ons, install, can playback video. Can browse/playback https source.

Good to go if someone can give a review and/or any further testing

**Review by wsnipex — APPROVED** [review]

**Pull request merged**
