### PR TITLE
[tools/Depends][native] bump cmake 3.21.3

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
bump cmake to 3.21.3

## Motivation and context
Xcode 13 has a default behaviour change for its legacy build system. Cmake 3.21.0+ have added this setting to a generated project when built as a legacy build system project, which then the default behaviour for xcode 13 is to now error on the usage of the legacy build system.

Will remove BASE_URL commit when mirrors are updated with new version tarball

## How has this been tested?
locally for xcode projects

## What is the effect on users?
N/a

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by garbear** [comment]
Building depends succeeds on my Big Sur 11.6 macbook. I did notice the warning when cmake'ing kodi:

```
CMake Warning (dev) at /Users/Shared/xbmc-depends/x86_64-darwin20.6.0-native/share/cmake-3.21/Modules/ExternalProject.cmake:3487 (message):
  Policy CMP0114 is not set to NEW.  In order to support the Xcode "new build
  system", this project must be updated to set policy CMP0114 to NEW.

  Since CMake is generating for the Xcode "new build system",
  ExternalProject_Add will use policy CMP0114's NEW behavior anyway, but the
  generated build system may not match what the project intends.
Call Stack (most recent call first):
  cmake/modules/FindCrossGUID.cmake:25 (externalproject_add)
  cmake/scripts/common/Macros.cmake:354 (find_package)
  cmake/scripts/common/Macros.cmake:368 (find_package_with_ver)
  CMakeLists.txt:181 (core_require_dep)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by garbear** [comment]
While building Kodi with xcode I get:

```

Showing Recent Issues
PhaseScriptExecution Generate\ system/players/VideoPlayer/libdvdnav-x86-osx.so /Users/garrett/Documents/kodi/build/kodi.build/Debug/wrap_libdvdnav.build/Script-EEADEA9F800D119CC1B88D84.sh (in target 'wrap_libdvdnav' from project 'kodi')
    cd /Users/garrett/Documents/kodi
    /bin/sh -c /Users/garrett/Documents/kodi/build/kodi.build/Debug/wrap_libdvdnav.build/Script-EEADEA9F800D119CC1B88D84.sh

/Users/garrett/Documents/kodi/build/kodi.build/Debug/wrap_libdvdnav.build/Script-EEADEA9F800D119CC1B88D84.sh: line 6: CURRENT_VARIANT: command not found
clang: error: no such file or directory: '/Users/garrett/Documents/kodi/build/build/cores/dll-loader/exports/kodi.build/Debug/wrapper.build/Objects-/x86_64/wrapper.o'

```

**Comment by fuzzard** [comment]
Your building against the new build system then. Thats why we currently default to the legacy build system

https://github.com/xbmc/xbmc/blob/180ea4ada286e7cb7ce3a8ca924a175232b844ea/tools/depends/target/cmakebuildsys/Makefile#L19

If you dont generate your project using "make -C tools/depends/target/cmakebuildsys GEN=Xcode", and instead trigger the cmake generation manually, add "-T buildsystem=1" to your cmake stanza

**Comment by fuzzard** [comment]
if you want to build against the new system, you can revert the revert of this https://github.com/xbmc/xbmc/commit/82ec3bf97e8ad4dadd862bb80708b6a47a1b568b#diff-b47c82ed51519f95d589b09248da891a4832a6594827a854e68ff128e77e08f5

Cmake does bullshit parsing that makes the wrapper script not work in its current state. Feel free to hit me up on slack if you want the gritty details of it all.

**Comment by garbear** [comment]
Thanks, `-T buildsystem=1` fixed it

**Comment by ksooo** [comment]
I had exactly the same experience as garbear had.

I rebuilt the dep, then recreated the xcode project. Xcode did NOT use the legacy build system! Ended up with the error garbear had.

**Comment by ksooo** [comment]
> Thanks, -T buildsystem=1 fixed it

@garbear Can you post the full command line, please. Don't know where to add this.

**Comment by garbear** [comment]
After creating and entering the build dir, I run:

```
/Users/Shared/xbmc-depends/x86_64-darwin20.6.0-native/bin/cmake \
  -G Xcode \
  -T buildsystem=1 \
  -DCMAKE_TOOLCHAIN_FILE=/Users/Shared/xbmc-depends/macosx11.3_x86_64-target-debug/share/Toolchain.cmake \
  -DENABLE_CCACHE=ON \
  ..
```

**Comment by garbear** [comment]
I applied https://github.com/xbmc/xbmc/pull/20208 and `-T buildsystem=1` is no longer needed.

**Comment by fuzzard** [comment]
@wsnipex Any chance we can get tarball onto mirrors when you have time.

**Comment by wsnipex** [comment]
> @wsnipex Any chance we can get tarball onto mirrors when you have time.

uplodaded

**Pull request merged**
