### PR TITLE
[Android] MediaDrm: catch and handle exceptions

### PR DESCRIPTION
**Pull request by joseluismarti**
## Description
Bump libandroidjni to fix the crash calling MediaDrm methods, since it retrieves the result of the method without checking if it has thrown an exception. See xbmc/libandroidjni#40

Also catches and handles exceptions that may occur when invoking methods of the MediaDrm class.

Both changes fix the issue described in #22312

## Types of change
- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CastagnaIT** [comment]
thanks! i will let you know the final results

**Comment by CastagnaIT** [comment]
i see that [libandroidjni](https://github.com/xbmc/libandroidjni) dont have kodi versions branches (only Leia)
maybe somone can say if backports can be done or not on libandroidjni i dont remember

**Comment by CastagnaIT** [comment]
Perfect works great work

**Comment by joseluismarti** [comment]
>maybe somone can say if backports can be done or not on libandroidjni i dont remember

It should be possible since the changes included in the library since the last bump in Nexus are new methods and constants that would not be used

**Comment by fuzzard** [comment]
@joseluismarti can you drop the bump commit

@CastagnaIT just confirming this fixes the issue you were having in IA?

**Comment by CastagnaIT** [comment]
yes i made tons of tests with @joseluismarti on slack

**Pull request merged**
