### PR TITLE
[Python] add xbmcgui.Dialog().textviewer()

### PR DESCRIPTION
**Pull request by phil65**
Adds a textviewer method to xbmcgui.Dialog().
Now I only need someone to expose parts of the python interface to skinners, as discussed with @FernetMenta . :)

### CODE REVIEW

**Comment by dersphere** [comment]
nice, thanks :)

**Comment by jimfcarroll** [comment]
I talked to the team on IRC yesterday. This looks good to me.

**Comment by FernetMenta** [comment]
@jimfcarroll on the other PR we talked about invoking Python instead of our own primitive interpreter for some APIs like xbmcgui. Do you think this is ok in regard of performance?

**Comment by mkortstiege** [comment]
api bump?

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Pull request merged**
