### PR TITLE
[PVR] Do not mark in progress recordings as watched.

### PR DESCRIPTION
**Pull request by ksooo**
Do not automatically mark in progress recordings as watched. Makes no sense.

@Jalle19 mind taking a look.

### CODE REVIEW

**Comment by Jalle19** [comment]
It's probably fine, but why use separate logic for recordings in general?

**Comment by ksooo** [comment]
> It's probably fine, but why use separate logic for recordings in general?

How would the general logic look like?

**Comment by Jalle19** [comment]
Doesn't it behave just like for library items now, i.e. if you watch something but don't watch it completely til the end it's marked as watched but with a different icon indicating that it is in progress (this possibly depends on the skin).

**Comment by ksooo** [comment]
No, currently, if you watch a in-progress recording, and skip past the current end of the recording, it will be stopped and marked watched.

**Comment by Jalle19** [comment]
You're right, didn't think about that

**Review by Jalle19 — APPROVED** [review]

**Review by AlwinEsch — APPROVED** [review]

**Pull request merged**
