### PR TITLE
[PVR] Fix timer type PVR_TIMER_TYPE_FORBIDS_EPG_TAG_ON_CREATE handling.

### PR DESCRIPTION
**Pull request by ksooo**
Completes the partial fix, based on and superseeds #12354 

@metaron-uk @djp952 could you please runtime test.
@Jalle19 mind looking at the code change.

### CODE REVIEW

**Comment by djp952** [comment]
It all looks great to me, I had to do a quick back-port of the changes to Krypton to test, but it works fantastically here.  I shall endeavor to have a PVR that works with master branch before submitting any more PRs!

Thank you all so much, this was seriously above and beyond!  Appreciative and impressed!

**Comment by ksooo** [comment]
jenkins build this please

**Comment by metaron-uk** [comment]
I'm having problems compiling pvr.mythtv against current master (or this branch). Seems something changed in the PVR API version checking and recent builds all fail at runtime with:
Add-on 'MythTV PVR Client' is using an incompatible API version for type 'PVR'. Kodi API min version = '5.2.4', add-on API version '0.0.0'

I'm sure I can work it out eventually, but I've not found it yet. Do you know the secret?

**Comment by ksooo** [comment]
jenkins errors are unrelated.

**Pull request merged**
