### PR TITLE
[pvr] bump pvr addons to latest commit

### PR DESCRIPTION
**Pull request by ryangribble**
As discussed with @opdenkamp the previous PVR bump missed the windows build script leading to alpha builds on win32 pvr addons not starting
(see discussion here https://github.com/xbmc/xbmc/commit/919192bfedd572adced1fa84f4652677a9ade10b#commitcomment-9602423)

More recent addon changes now exist anyway so this PR pulls in the latest pvr addons commit

### CODE REVIEW

**Comment by opdenkamp** [comment]
jenkins build and merge

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by kib** [comment]
failed because 'ffmpeg not found', let us try that again.

jenkins build this please

**Comment by opdenkamp** [comment]
same thing again, osx build hosts are borked.

**Comment by Memphiz** [comment]
And instead of letting me fix it we merge it so all other PRs which are built from now on are borked to?

**Comment by opdenkamp** [comment]
hm? looked like yet another unrelated build failure. pvr add-ons don't 
touch ffmpeg anymore. removed that dep 2 years ago or so.

**Comment by Memphiz** [comment]
Luckily i have my hackbook with me and will be able to fix the permissions this evening... as of the looks only the osx build #2 has wrong permissions and i took it offline - other builds should be saved...

**Comment by Memphiz** [comment]
As a tip - search for " Error " (with the spaces and case sensitive) in the logoutput ... then you will see that it was a permission error in the pvr git repo in the tarballs dir. (which is somethingi can't really explain but it might have something to do with the fact that i had updated this slave to osx yosemite lately).

**Comment by opdenkamp** [comment]
I did, error 1 matched to a missing ffmpeg error message from configure...

**Comment by Memphiz** [comment]
Then we must have looked at different logs. In all 4 logs which failed for this PR the first Error which was not "(ignored)" is this:

http://pastebin.com/CphPdMqK

(at least when looking at the full log).

**Comment by opdenkamp** [comment]
must be, both @kib and I saw missing ffmpeg errors in different builds, 
and I got it from the full log too and it wasn't ignored

**Pull request merged**
