### PR TITLE
dvdplayer: fix mimetype after 89538103d60f64106f8ad998427c7286a3766244

### PR DESCRIPTION
**Pull request by FernetMenta**
force lookup if not explicitly suppressed.

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkind build this please

@fritsch now their interest will come back :)

**Comment by fritsch** [comment]
Yeah - thought so. I will be afk for the next week, going onto a conference without any mobile reception (like every year end of July). I pushed the WIP onto my github - so those affected can test and a improve it.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by hudokkow** [comment]
OSX failure unrelated, jenkins build this please

**Pull request merged**
