### PR TITLE
[confluence] update bookmark OSD icon

### PR DESCRIPTION
**Pull request by un1versal**
@da-anda @phil65 @ronie 

This is a follow up to https://github.com/xbmc/xbmc/pull/7342 its not really dependant on that PR but the current icon really doesnt scream bookmarks and now that it also brings up chapters it really is even less in common.

This updates that OSD icon.

This is how it would look.
Not Focus
screenshot002

Focus
screenshot000

### CODE REVIEW

**Comment by phil65** [comment]
looks fine to me. (perhaps bookmark icon a very bit smaller)

**Comment by uNiversaI** [comment]
Shaved 2 pixel From Height

screenshot000
screenshot001

**Comment by da-anda** [comment]
like it. Thanks.

**Comment by NedScott** [comment]
This is an improvement, so no objection from me. Just to throw an idea out there (*cough*bikeshedding, sorry*cough*), though, what about using a book icon? It could then cover both the concept of bookmarks and chapters. I leave this up to Universal, but just thought I would mention it.

**Comment by uNiversaI** [comment]
> This is an improvement, so no objection from me. Just to throw an idea out there (coughbikeshedding, sorrycough), though, what about using a book icon? It could then cover both the concept of bookmarks and chapters. I leave this up to Universal, but just thought I would mention it.

too little space so much potential.

**Comment by mkortstiege** [comment]
Any objections?

**Comment by ronie** [comment]
nope.

**Pull request merged**
