### PR TITLE
mmalrender: Reject unsupported render formats

### PR DESCRIPTION
**Pull request by popcornmix**
Avoids a crash when 10-bit video is played

### CODE REVIEW

**Comment by popcornmix** [comment]
jenkins build this please

**Comment by Jalle19** [comment]
Needs backport?

**Comment by popcornmix** [comment]
Yes, this would apply to Jarvis

**Comment by MartijnKaijser** [comment]
backport PR?

**Comment by popcornmix** [comment]
Backport: https://github.com/xbmc/xbmc/pull/9031

**Pull request merged**
