### PR TITLE
Remove EnableStreamAtPTS

### PR DESCRIPTION
**Pull request by ghost**
see subject

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
Win32 got stuck 
jenkins build this please

**Comment by mapfau** [comment]
inputstream addons will NOT compile!
I'll push the changes later.... JFYI...

**Comment by mapfau** [comment]
How do we want to continue here - are you waiting for inputstream changes?

**Comment by FernetMenta** [comment]
I will merge this on Aug. 1st when merge window will open

**Comment by mapfau** [comment]
ah, again forgot the freeze, sry.

**Pull request merged**
