### PR TITLE
DVD_NOPTS_VALUE: fix double representation

### PR DESCRIPTION
**Pull request by fritsch**
Thanks to @MrMc for the tipp.

### CODE REVIEW

**Comment by fritsch** [comment]
@FernetMenta see:

```
#include <stdint.h>
#include <iostream>

#define ptval 0xFFF0000000000000
#define ptvalgood (int64_t) 0xFFF0000000000000

int main ()
{

  int64_t a = ptval;
  double  b = ptval;

  int64_t c = ptvalgood;
  double  d = ptvalgood;

  std::cout.precision(20);
  std::cout << a << " " << b << " " << c << " " << d << std::endl;
  return 0;
}
```

Results in:
fritsch@t440s:~$ ./lala.out 
-4503599627370496 18442240474082181120 -4503599627370496 -4503599627370496

where b is obviously wrong, but d is correct.

**Comment by FernetMenta** [comment]
please not such a hack. there is only a single place in the code where it is compared with int64_t and this can go

**Comment by fritsch** [comment]
From a C++ pov the #define is the hack ...

**Comment by MrMC** [comment]
then remove the misleading comment if you are changing API and previous behavior...

**Comment by fritsch** [comment]
Our friends at ffmpeg do this hack:
```
libavutil/avutil.h:#define AV_NOPTS_VALUE          ((int64_t)UINT64_C(0x8000000000000000))
```

**Comment by FernetMenta** [comment]
yes because their clock is based on int64_t, ours on double

**Comment by fritsch** [comment]
https://github.com/xbmc/xbmc-antiquated/commit/82add189eadac8551e2ffe70fab2c00f514c150e <- here it comes from. The same guy that has written the famous _aligned_malloc.

It has historical reasons, cause some hw decoders just ate int64_t so there needed to be a value that could be represented by both double and int64_t. Now this possibility is not given anymore. 

If we don't want _/ need this - we can just use a const double DVD_NOPTS_VALUE and set that to whatever we want.

**Pull request closed without merging**
