### PR TITLE
[guilib] Change System.HasModalDialog to System.HasActiveModalDialog …

### PR DESCRIPTION
**Pull request by BigNoid**
…and add System.HasVisibleModalDialog

Needs Estuary to be updated. That commit will be added when v18 is open for business.
## Motivation and Context
```System.HasModalDialog``` ignored the window close animations. Similar to ```Window.IsVisible``` and ```Window.IsActive``` we can now choose to use a visible condition that either respects or ignores the window close animations of modal dialogs.

## How Has This Been Tested?
Add a control with either visibility check and open/close a modal dialog. With ```System.HasActiveModalDialog``` the control will be instantly visible on closing. With ```System.HasVisibleModalDialog``` only when the modal dialog has finished the animation.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by BigNoid** [comment]
@xhaggi mind taking a look?

**Comment by BigNoid** [comment]
jenkins build this please

**Comment by BigNoid** [comment]
@phil65 added changes for Estuary, including api bump.

@ronie Your button when you think we are ready for the GUI API bump. Also added api bump for estouchy.

jenkins build this please

**Comment by tamland** [comment]
Surely it should be trivial to keep backwards compatibility in this case?

**Comment by BigNoid** [comment]
> Surely it should be trivial to keep backwards compatibility in this case?

We've discussed this on slack a while back and came to the conclusion this bool is hardly used by skins (only estuary and nox) and a trivial change to do in skin code.  But as it's formally a breaking change I've added the API bump. 
The API bump is bound to happen sooner or later, #10926 is also a candidate for invoking an API bump.

**Comment by ronie** [comment]
since this change has such a low (almost none) impact, perhaps we should drop the api bump for now?

bumping the api will make all repo skins incompatible with master.
i'd prefer to keep them compatible for a while and do the api bump when we merge a more major breaking change.

**Comment by BigNoid** [comment]
Sure, that's also fine for me. Updated.

**Comment by ronie** [comment]
thx!

**Pull request merged**
