### PR TITLE
Fix XBMC.vcxproj.filters after #9252

### PR DESCRIPTION
**Pull request by AlwinEsch**
This fix a stupid fault from my.

Again was on another OS update my already created part for Windows shot away.

Sorry to all.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by anaconda** [comment]
TextureBundleXPR.cpp is deleted by #9296

**Comment by AlwinEsch** [comment]
Has seen it now.

Jenkins build this please again

**Comment by AlwinEsch** [comment]
jenkins build this please again

**Pull request merged**
