### PR TITLE
Android: Don't reset user set volume

### PR DESCRIPTION
**Pull request by fritsch**
Backport of #17241

### CODE REVIEW

**Review by peak3d — APPROVED** [review]

**Comment by lrusak** [comment]
jenkins build this please

**Comment by fritsch** [comment]
jenkins build this please (FreeBSD and Win32 are not related, but having it green is good anyways)

**Comment by lrusak** [comment]
jenkins build this please

**Comment by fritsch** [comment]
jenkins build this please

**Pull request merged**
