### PR TITLE
[epg] adapt the progress texture's height to the actual height of the grid

### PR DESCRIPTION
**Pull request by Jalle19**
Fixes http://trac.kodi.tv/ticket/15681

ping @xhaggi @opdenkamp

### CODE REVIEW

**Comment by xhaggi** [comment]
looks good but not run time tested

**Comment by Jalle19** [comment]
I'm not sure if this is the best place to perform the calculation (the method is run all the time) nor if using these values is the "right" way to obtain the desired height value, although based on my runtime testing it seems to do the job. Maybe @opdenkamp can weigh in?

**Comment by opdenkamp** [comment]
Not very familiar with the code in this class, sorry. I'd have to dig into it too. Only question I have is about `m_rulerHeight`. Shouldn't that be multiplied by the (number of channels - 1), cause it's between all channels?

**Comment by Jalle19** [comment]
I actually have no idea what the ruler is.

**Comment by xhaggi** [comment]
the ruler is the time line at the top of the epg grid. so no we don't need to multiplied it.

**Comment by opdenkamp** [comment]
ah, that thing :P

**Comment by xhaggi** [comment]
the naming is a mess here

**Comment by opdenkamp** [comment]
sorry, this was one of the only classes that i barely touched before merging in pvr ;-)
low end devices aren't very happy with the way this code works now, so it could definitely use some loving some time soon

**Comment by Jalle19** [comment]
@xhaggi that was my initial guess as well. Anyway, is this something we want for Isengard?

**Comment by opdenkamp** [comment]
it's a feature, and neither of us know this code very well, so I'd say no

**Comment by Jalle19** [comment]
@xhaggi @opdenkamp okay to merge?

jenkins build this please

**Comment by xhaggi** [comment]
no objections from my side

**Comment by xhaggi** [comment]
jenkins build and merge

**Pull request merged**
