### PR TITLE
make sure we really link spdlog

### PR DESCRIPTION
**Pull request by wsnipex**
## Description

Currently we use spdlog in header only mode, because the needed define to link against the lib is missing.
GCC will omit linking against the lib completely while Clang, curiously, still links against spdlog.so

Adding the define fixes GCC and seems to make no difference for Clang, both will link the lib. 

## Motivation and context

https://github.com/xbmc/xbmc/pull/17498#issuecomment-619024975

reproduced and diagnosed by @notspiff and me on slack

## How has this been tested?

compiled on linux with GCC and Clang

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by wsnipex** [comment]
interesting: this seems to change all loglevels from upper to lower case:

before:

> 2022-01-12 12:01:33.539 T:879758    INFO <general>: -----------------------------------------------------------------------
2022-01-12 12:01:33.539 T:879758    INFO <general>: Starting Kodi (20.0-ALPHA1 (19.90.101) Git:20220109-bd79584821). Platform: Linux x86 64-bit
2022-01-12 12:01:33.539 T:879758    INFO <general>: Using Release Kodi x64
2022-01-12 12:01:33.539 T:879758    INFO <general>: Kodi compiled 2022-01-09 by GCC 9.3.0 for Linux x86 64-bit version 5.4.157 (328861)
2022-01-12 12:01:33.539 T:879758    INFO <general>: Running on Ubuntu 20.04.3 LTS, kernel: Linux x86 64-bit version 5.14.0-1013-oem
2022-01-12 12:01:33.540 T:879758    INFO <general>: FFmpeg version/source: 4.3.1-Kodi
2022-01-12 12:01:33.540 T:879758    INFO <general>: Host CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz, 8 cores available
2022-01-12 12:01:33.540 T:879758    INFO <general>: special://xbmc/ is mapped to: /usr/share/kodi
2022-01-12 12:01:33.540 T:879758    INFO <general>: special://xbmcbin/ is mapped to: /usr/lib/x86_64-linux-gnu/kodi
2022-01-12 12:01:33.540 T:879758    INFO <general>: special://xbmcbinaddons/ is mapped to: /usr/lib/x86_64-linux-gnu/kodi/addon

with PR:

> 2022-01-12 09:02:20.892 T:870082    info <general>: -----------------------------------------------------------------------
2022-01-12 09:02:20.892 T:870082    info <general>: Starting Kodi (20.0-ALPHA1 (19.90.101) Git:20220112-ac3856ac59). Platform: Linux x86 64-bit
2022-01-12 09:02:20.892 T:870082    info <general>: Using Release Kodi x64
2022-01-12 09:02:20.892 T:870082    info <general>: Kodi compiled 2022-01-12 by GCC 9.3.0 for Linux x86 64-bit version 5.8.17 (329745)
2022-01-12 09:02:20.892 T:870082    info <general>: Running on Ubuntu 20.04.3 LTS, kernel: Linux x86 64-bit version 5.14.0-1013-oem
2022-01-12 09:02:20.892 T:870082    info <general>: FFmpeg version/source: 4.4-Kodi
2022-01-12 09:02:20.892 T:870082    info <general>: Host CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz, 8 cores available
2022-01-12 09:02:20.892 T:870082    info <general>: special://xbmc/ is mapped to: /home/wuff/src/xbmc/build
2022-01-12 09:02:20.892 T:870082    info <general>: special://xbmcbin/ is mapped to: /home/wuff/src/xbmc/build
2022-01-12 09:02:20.892 T:870082    info <general>: special://xbmcbinaddons/ is mapped to: /home/wuff/src/xbmc/build/addons

**Comment by lrusak** [comment]
Might be a bug with spdlog. It seems custom level names can only be used with the header only compile.

See:
https://github.com/gabime/spdlog/blob/4cfdc8c5c84f696774cb9acde2f95c9e87c11a5e/include/spdlog/common-inl.h#L19

https://github.com/gabime/spdlog/blob/4cfdc8c5c84f696774cb9acde2f95c9e87c11a5e/include/spdlog/common.h#L357

https://github.com/xbmc/xbmc/blob/d0db844f8bd64db8f3b68b89891e07b1639e5bec/xbmc/utils/log.h#L14

**Comment by fuzzard** [comment]
+1 from me.

My only comment is when ENABLE_INTERNAL_SPDLOG, there wont be PC_SPDLOG_CFLAGS filled out. The SPDLOG_DEFINITIONS set inside that internal if will also be wiped out by the set in the SPDLOG_FOUND block, therefore -DSPDLOG_COMPILED_LIB wont be set for an internal spdlog build

Not sure neatest way to handle it.

**Comment by wsnipex** [comment]
that's kinda on purpose. It doesn't make sense to use -DSPDLOG_COMPILED_LIB for internal spdlog builds, since in the end we link it statically.

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
no idea what's going on with that TestSysfsPath.SysfsPathTestLongString on linux-64.
I can't reproduce locally

**Comment by basilgello** [comment]
@wsnipex absence of this patch introduces test failures for `Testlog.Log` and `TestRegexpLog.DumpOvector` on all 32-bit arm architectures in Debian, ie armel and armhf. Plus tge mentiined tesrs should check log output against lowercase letters and not uppercase like before. This way we will unambiguosly detect the improperly linked spdlog.

**Review by basilgello — APPROVED** [review]
@wsnipex I have rebased this PR after I uploaded the Debian package of 20.0 Alpha 1 to Debian experimental and all tests passed on armel/armhf.

**Comment by wsnipex** [comment]
thanks for the rebase.

**Comment by neo1973** [comment]
Any plans to merge this soon? I'm at least the third person accidentally reinventing the same patches not knowing of this PR :laughing:

**Comment by howie-f** [comment]
jenkins build this please

**Comment by neo1973** [comment]
I think the problem is with the `${PC_SPDLOG_CFLAGS}` added to `SPDLOG_DEFINITIONS`. The spdlog.pc from the prebuild spdlog (got it from https://ftp.fau.de/xbmc/build-deps/win32/spdlog-1.5.0-x64-v141-20200320.7z):
```
prefix=C:/Program Files (x86)/spdlog
exec_prefix=${prefix}
includedir=${prefix}/include
libdir=${exec_prefix}/lib

Name: libspdlog
Description: Fast C++ logging library.
URL: https://github.com/gabime/spdlog
Version: 1.5.0
CFlags: -I${includedir} -DSPDLOG_COMPILED_LIB -DSPDLOG_WCHAR_TO_UTF8_SUPPORT -DSPDLOG_WCHAR_FILENAMES
Libs: -L${libdir} -lspdlog -pthread
Requires: 
```
We see that `prefix` has spaces but isn't in quotation marks, this result in the compiler seeing the second part of it as a separate command when adding it to the CFLAGS with `-I${includedir}`.

The prebuild spdlog should be fixed then everything should work.

**Comment by fuzzard** [comment]
Jenkins build this please

**Pull request merged**
