### PR TITLE
[Subtitles] Add missing context info to translation strings

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

Add missing context info to translation strings @ksooo

## Motivation and context

Added missing context info from follow PR #20010

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [x] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ksooo** [comment]
Cool, thanks.

With you original PR, you also changed `#21461`, which had no contetx info. Mind adding it?

**Comment by CastagnaIT** [comment]
done

**Comment by ksooo** [comment]
And one more:

```
msgctxt "#36192"
msgid "Location of subtitles on the screen."
msgid "Location of subtitles on the screen. \"Manual\" the position can be customised by using video calibration settings. \"Below/Above video\" when possible will be positioned inside the black bars (depends on video encoding). Please note that some forced positions in the subtitles cannot be changed."
msgstr ""
```

To reference settings value in the related help text, we tend to use a special syntax, which is to put the value in square brackets. Like here: https://github.com/CastagnaIT/xbmc/blob/12b047a2997579c1f05fac69ff3b2008e5de7749/addons/resource.language.en_gb/resources/strings.po#L17132

Mind changing your string to follow this guideline?

**Comment by CastagnaIT** [comment]
try to see if it is ok

**Comment by ksooo** [comment]
Nice. Thank you.

**Review by ksooo — APPROVED** [review]
Thanks.

**Pull request merged**
