### PR TITLE
[confluence] add pcm, pcm_s16le and pcm_s24le audio flags

### PR DESCRIPTION
**Pull request by un1versal**
This solves no audio flag being present when we playing wav files that contain pcm stream now that most is handled via ffmpeg and not whatever we use to have in kodi, as I remember those use to be ok back then.
- A example of such is where we use the **_audioencoder.wav**_ addon to rip a cd to wav which results in **_pcm_s16le**_ stream.
- Playing a cd directly the stream is **_pcm**_ audio and also has no flag so adding it here seems the logical thing to do. 
- When I tested and external ripper to wav the stream was **_pcm_s24le**_ and also no flag in confluence. this fixes that also.

Without PR these 3 look like screenshot below.

screenshot092 png

This is playing a externally ripped file to wav with pcm_s24le

screenshot002

This is after playing a CD

screenshot000

There maybe others that have no flags in confluence on playback but for time being these are now handled via this PR and display expected flag.

@fritsch @ronie

### CODE REVIEW

**Comment by uNiversaI** [comment]
Adding a reference to [List of formats as id by ffmpeg] (https://github.com/FFmpeg/FFmpeg/blob/d490b26fcb1b36c91099537a08d9a217d4782451/libavformat/allformats.c#L223) in case someone can spot more that are potentially common enough to justify making flags for them.

**Comment by ronie** [comment]
looks good to me. or does someone prefer a 'wav' flag instead of 'pcm' for this?

**Comment by jjd-uk** [comment]
"wav" is a container and we already have an icon for that https://github.com/uNiversaI/kodi/blob/21ad140c6c10c6a1d731a7106af83a9b252d0136/addons/skin.confluence/media/flagging/audio/wav.png

**Comment by ronie** [comment]
i know. so which one do you prefer?

**Comment by jjd-uk** [comment]
Edited previous post.

Is it possible to show both, as it'a also valid to have "DTS" in a "WAV"?

**Comment by fritsch** [comment]
You really want to see WAV next to DTS? That's not really of enduser
interest? The devs sees that in the log.

2015-03-26 17:39 GMT+01:00 jjd-uk <notifications@github.com>:

> Edited previous post.
>
> Is it possible to show both, as it'a also valid to have "DTS" in a "WAV"?
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/xbmc/pull/6823#issuecomment-86610129>.
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by jjd-uk** [comment]
Not that bothered just raising the point. So sticking with the contents in this case "PCM" is fine by me.

**Comment by uNiversaI** [comment]
Well, I decided to go with pcm cause indeed it is pcm as per codec identification of both ffmpeg and mediainfo.

the wav portion use to work previously back in xbmc days when all this was internal and not handled by ffmpeg if Im not mistaken.
Im unsure where showing the flag for container and not codec came into this in that logic.

Perhaps some internal player logic need to be adjusted to show the audio container then?

**Comment by Jalle19** [comment]
WAV might be more user-friendly, normal people don't know what PCM is.

**Pull request merged**
