### PR TITLE
[cmake] fix dependencies of iso9660++

### PR DESCRIPTION
**Pull request by Karlson2k**
Matrix backport of https://github.com/xbmc/xbmc/pull/19284

### CODE REVIEW

**Review by wsnipex — APPROVED** [review]

**Review by DaveTBlake — APPROVED** [review]

**Comment by howie-f** [comment]
since this change i get the following cmake warning (same on master).
doesn't break the build but is irritating. so a FYI
```
CMake Warning at cmake/modules/FindCdio.cmake:24 (message):
  Detected libcdio (2.0.0) and libcdio++ () version mismatch.  libcdio++ will
  not be used.
Call Stack (most recent call first):
  cmake/scripts/common/Macros.cmake:354 (find_package)
  cmake/scripts/common/Macros.cmake:368 (find_package_with_ver)
  CMakeLists.txt:175 (core_require_dep)
```
configured with:
```
-DENABLE_OPTICAL=NO -DENABLE_ISO9660PP=NO -DENABLE_BLURAY=NO
```

**Comment by wsnipex** [comment]
works as designed. You either are missing the libcdio++ headers (libcdio++-dev) on debian based system, or it's a different version from libcdio-dev, which should never happen

**Comment by wsnipex** [comment]
@Karlson2k this is exactly why I wanted cdio++ mandatory

**Comment by howie-f** [comment]
ok, no `libcdio++-dev` available on my buster distro, i can live with just ignoring the warning, thanks

**Comment by Karlson2k** [comment]
@wsnipex Actually it highlights another problem, which I discovered during the "Battle of Libcdio" :) , but decided to postpone until better times.

Currently we are trying to specify minimal required version in `pkg_check_modules()` in `cmake/modules/*.cmake`, but actually it doesn't work.
This way we only check whether `.pc` files declared the required version, but if version is below required it means that `PC_...` variables will not be declared. Just like if `PKG_CONFIG_FOUND` is `false`.
It doesn't prevent `find_lib()` to find required library in standard path as specified path is used just as a hit, in addition to the standard search paths.

We have facility that handle correctly minimal versions, it is `core_optional_dep()` / `core_require_dep()`, but currently only OpenSSL version is specified here.

I suggest to move all version requirements from `cmake/modules/*` to the correct place.

> @Karlson2k this is exactly why I wanted cdio++ mandatory

That's exactly why I wanted to leave it optional.
We shouldn't dictate our users what to do. To make solution more fool-proof, we can make some modules optional **only if requested** by user, like explicit `-DENABLE...=OFF`

**Comment by Karlson2k** [comment]
> ok, no `libcdio++-dev` available on my buster distro, i can live with just ignoring the warning, thanks

@wsnipex That is the reason why I wanted to have `libcdio+++` check in `Iso9660` module. If user explicitly disable `libiso9660` it make no sense to check for `libcdio++` and issue a warning about it.

**Pull request merged**
