### PR TITLE
fixed: Watched flag not displayed if item is also resumable (fixes #15766)

### PR DESCRIPTION
**Pull request by arnova**

### CODE REVIEW

**Comment by arnova** [comment]
@MartijnKaijser : Your button.

**Comment by arnova** [comment]
@MartijnKaijser : Also updated

**Comment by arnova** [comment]
@MartijnKaijser : Good to go, right?

**Comment by MartijnKaijser** [comment]
if it's merged and master and @ronie is ok with backport

**Comment by arnova** [comment]
@MartijnKaijser : I believe @ronie was already ok with that.

**Comment by MartijnKaijser** [comment]
related?
http://forum.kodi.tv/showthread.php?tid=235575&pid=2082883

**Comment by ronie** [comment]
will have a look

**Comment by ronie** [comment]
fixed https://github.com/xbmc/xbmc/commit/be7118372ed9ed86ad99187eff4f6f056dfde416

**Pull request merged**
