### PR TITLE
[clang-tidy] modernize-make-(shared|unique)

### PR DESCRIPTION
**Pull request by Rechi**
## Description
apply and enable `modernize-make-shared` and `modernize-make-unique clang-tidy` checks

## Motivation and context
revised alternative of #23757

## How has this been tested?
run clang-tidy and compiled for Android (aarch64), iOS, Linux (gl and gles), macOS and tvOS

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Review by ksooo — APPROVED** [review]
PVR changes look good to me.

**Review by garbear — APPROVED** [review]
LGTM, thanks

**Comment by garbear** [comment]
The change is relatively obtrusive so let's get it in once the clang formatting issues are fixed.

**Comment by garbear** [comment]
@Rechi Do you plan to apply the jenkins format patch?

**Comment by garbear** [comment]
Is this preferred over https://github.com/xbmc/xbmc/pull/23757?

**Comment by Rechi** [comment]
Applying the clang-format patch will clutter up the code. The existing code doesn't follow the current formatting style so I'll keep it as it is,

**Pull request merged**
