### PR TITLE
Lib structure changes

### PR DESCRIPTION
**Pull request by phil65**
- remove songs node from music (useless and slooow)
- move recently-added and in-progress nodes into their corresponding subfolders

@ronie @da-anda

### CODE REVIEW

**Comment by ronie** [comment]
i would like to get some input from the rest of the team about the song node removal.
personally i'm not sold on it. loading ~15.000 songs takes half a second on my end.

a big fat +1 on moving the recently added/in-progress nodes.
they always felt out of place in the root of the library.

**Comment by MartijnKaijser** [comment]
Same less than a second on my i3 with 22.3k songs.

**Comment by MilhouseVH** [comment]
7,388 songs takes 8 seconds on a RPi3, and 29 seconds on a RPi1. Neither of which I consider a major problem.

What *is* a problem is when people try to play a single file within the Songs node, as this spits out a `Playlist.OnAdd` notification for **every** song in the Songs node (ie. in my case, Kodi generates 7388 notifications to play one random song). This issue crops up fairly often in the forums with users wondering why it takes so long to start playback of a song.

Presumably dropping the Songs node might upset those who use Party Mode?

**Comment by MartijnKaijser** [comment]
Dropping song node hides the real issue which is still there so doesn't solve anything

**Comment by MilhouseVH** [comment]
Yes I know, hence the smilie, but I don't know if a real fix is possible or even likely, in which case dropping Songs should prove somewhat beneficial for this particular problem.

**Comment by MartijnKaijser** [comment]
The OnAdd should be "cached" to some extent that it results in only a couple messages instead of 7388

**Comment by phil65** [comment]
It´s not about hiding some issue, it´s about a sane default node structure. I dont consider it sane to have lists with >10.000 items displayed on a 10-foot-interface.
If there are objections, sure, I can drop that commit again ofc.

**Comment by MartijnKaijser** [comment]
There are users with over 6000 movies.

**Comment by ronie** [comment]
i think the question should be whether it's useful to have a song node or not.
speed / length of the list shouldn't be taken into account that much.

compare it to the actors node, which is equally 'slow'.
mine contains around 40.000 actors... but i do occasionally use that node
when i'm in the mood to watch a movie that features a certain actor.

finding out if/why user people use the songs node might provide us
some info on whether it's sane to remove it or not.

**Comment by zag2me** [comment]
Yep totally agree with @ronie, this needs discussion on the forum first before merging. I'll start a thread.

My personal opinion has always been that the Song node is not useful and should be removed. HTPC's should be about showing 10,000 items in a list, they should be about getting to your media in a quick a logical way. If I wanted to browse songs in some huge list i'll use my desktop computer!

You WILL get complaints from users because they are used to using it and probably don't even know they can user Artist >> Album or just Album >> Song. That of course does not mean it should block us removing it though :) Sometimes you have to take things away to improve other areas.

**Comment by MartijnKaijser** [comment]
I have 6700 artists so that node is "useless" in that regard as well.

**Comment by da-anda** [comment]
I occasinally use the songs node, but mostly only to shuffle my library. But depending on the size of your music collection the song list will be helpful or not. On my phone f.e. I use the song list more often to create playlists, but I likely would not use it on larger libraries for this. So it IMO has it's use, but surely not for everyone. But this is the case for all nodes (I never used actors node f.e.).

I'd say, keep the songs node for now and gather more information and merge the rest.

**Comment by DaveTBlake** [comment]
Please do not remove the songs node.

It is a preumption that all users have large music libraries, organised by genre and album etc. If you have a fast system, a small library, or your music is just a collection of songs then accessing just a list of the songs is both useful and useable.

**Comment by zag2me** [comment]
The discussion thread is pretty obvious people still have a need for the Songs node, so I would like it to stay as well. I'm fine with the 2nd commit though.

**Comment by phil65** [comment]
Dropped the removal to at least make bit of progress for now.

**Comment by NedScott** [comment]
I almost didn't notice the moving of the "recently added" and "in-progress" video nodes. Big improvement! I've been manually doing the same thing on my installs. Thanks for this.

**Pull request merged**
