### PR TITLE
VideoPlayer: inputstream changes, bump to 1.0.2

### PR DESCRIPTION
**Pull request by FernetMenta**
- drop check for extension
- listitemproperty "inputstreamaddon" to request a specific inputstream addon
- fix pathlist that that compared to itself

### CODE REVIEW

**Comment by FernetMenta** [comment]
@mapfau could you have a look please

**Comment by mapfau** [comment]
Just to be sure: The extension check has been removed?
If so: doesnt make it sense to remove pathlist also? And make listitemproperty "inputstreamaddon" mandatory?

**Comment by FernetMenta** [comment]
> The extension check has been removed?

yes

> doesnt make it sense to remove pathlist also?

I don't think so.

> And make listitemproperty "inputstreamaddon" mandatory?

that would remove the chance to play a .strm file

**Comment by mapfau** [comment]
Yes, I thougth also about it, but hoped that strm files support listitem vaues to be set.
Shouldn't we make strm file parser more flexible to support listItem?

**Comment by FernetMenta** [comment]
@mapfau see https://github.com/xbmc/xbmc/pull/9410/commits/397b8f203c6428020e272ae2bb9eabc427136524

pushing to a vector changes memory.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by mapfau** [comment]
> pushing to a vector changes memory.
arghhhhh, greenhorn error :-(

**Pull request merged**
