### PR TITLE
Don't create special://profile/library to enable Kodi system default nodes

### PR DESCRIPTION
**Pull request by mglae**
## Description

Remove default creation of special://profile/library

## Motivation and Context

According to the [Video Node Wiki](https://kodi.wiki/view/Video_nodes) Kodi use system default nodes from special://xbmc/system/library until custom nodes are installed in special://profile/library. This is implemented in [GetNode()](https://github.com/xbmc/xbmc/blob/18.0b3-Leia/xbmc/filesystem/LibraryDirectory.cpp#L155-L159).

But special://profile/library always is created preventing usage of system default nodes.

[Bug report](https://forum.libreelec.tv/thread/13387-kodi-userdata-library-video-nprogressshows-xml-missing-in-le8/?postID=100539#post100539)

## How Has This Been Tested?

With recent LibreELEC generic master.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by mglae** [comment]
Corrected wrong function link in first comment.

**Comment by mglae** [comment]
> please note the 'until custom nodes are installed' part.
> as long as special://profile/library is empty, the system default nodes are used.

Yes, This is implemented in [GetNode()](https://github.com/xbmc/xbmc/blob/18.0b3-Leia/xbmc/filesystem/LibraryDirectory.cpp#L155-L159) as a directory existence check.

Do you recommend to replace this simplicity with somewhat more complex?

If yes, how do we support the 'no nodes at all' case?

**Comment by ronie** [comment]
none of that all, as this isn't a kodi bug ;-)

the xonfluence skin is simply using the wrong library path here:
https://github.com/Helly1206/skin.xonfluence/blob/master/xml/IncludesMenuContentItems.xml#L1404
that should be: `library://video/tvshows/inprogressshows.xml/`

**Comment by mglae** [comment]
@ronie thank you very much.

**Pull request closed without merging**
