### PR TITLE
[PVR] Fix race condition / double-free crash in GUIWindowPVRBase

### PR DESCRIPTION
**Pull request by MaxKellermann**

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
oh, this was Jarvis branch though label K*** was attached. @MaxKellermann you did not submit this it mater first, did you? In general we first add changes to mater, than backport if needed.

**Comment by MartijnKaijser** [comment]
Oh well. @MaxKellermann please also PR to master branch

**Comment by FernetMenta** [comment]
I did so just a couple of seconds ago.

**Comment by MartijnKaijser** [comment]
Thx :)

**Pull request merged**
