### PR TITLE
[addons][inputstream] allow instance version check and fix inputstream addon way

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description
The fist commit:
**[addons] add new function "CAddonInfo::DependencyVersion(...)" (to check depends)**

By this also the "CAddon::GetDependencyVersion(..,)" is changed to, and
CBinaryAddonBase becomes it added too, to have on running instances.

The second commit:
**[addons][inputstream] fix depedency version check**

Before was the addon own version used where never match a inputstream instance
version.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Seems to be connected because of your given commit examples this way came.

**Comment by peak3d** [comment]
@candrews yes

**Review by peak3d — APPROVED** [review]
tested -> works fine, thx!

**Comment by candrews** [comment]
Confirmed also that it fixed my problem. Thank you!

**Comment by Rechi** [comment]
Why was this merged with a failed Jenkins build?

**Comment by AlwinEsch** [comment]
The test was OK, only by Win64 on end a jenkins build script failure `16:06:28 FATAL: Java heap space`

**Pull request merged**
