### PR TITLE
video: use PartyMode queue logic even if PartyMode is in music mode

### PR DESCRIPTION
**Pull request by ghost**
Queuing video now works in PARTYMODECONTEXT_MUSIC, but it goes to
the end of the list which is inconvenient. Queue videos as with
songs. Useful for e.g. "I want to watch this youtube video" without
disrupting the playlist.

### CODE REVIEW

**Comment by Montellese** [comment]
I never use(d) party mode so I can't judge if this change of behaviour is wanted by other users of party mode or not.

**Comment by unknownlamer** [comment]
Before Isengard and the patches from http://forum.kodi.tv/showthread.php?tid=216425 you couldn't  mix video into the music party mode playlist at all. If you played a video, party mode would end entirely (but the video played), and if you queued the video party mode would end after the current song and the video wouldn't play either.

Now that queuing doesn't simply kill the party mode, I think it is sensible to make video and music queue with the same behavior.  If you think this needs more input, I could create an RFC thread in the appropriate forum.

**Comment by unknownlamer** [comment]
Greetings,

I've been using this for over a year now without any issues and have kept it rebased against master. I was wondering if there was anything I needed to do to get it reviewed for inclusion (not sure if it's too late for v17?). 

Since Isengard, you have been able to queue or play a video in music partymode, but they are added at the end of the list (not into the queue), which has the side effect of skipping over all of the music already on the party mode list/queue when playing a video (a friend plays a youtube video and there goes the hour of music everyone had queued). This patch just changes behavior so that a video is added into the queue normally as an audio file would be, and playing a video only replaces the active song as playing a song from the library browser would. I think it is a sensible, minor behavioral change that makes things a bit less surprising.

**Comment by unknownlamer** [comment]
It is clear this is never going to be reviewed so I am abandoning the attempt to have it merged.

**Pull request closed without merging**
