### PR TITLE
Fix region field of xbmc.getLanguage api #22715

### PR DESCRIPTION
**Pull request by fbacher**
## Description

Implemented ModuleXbmc::getLocaleProperties to enhance  and replace ModuleXbmc::getLanguage

## Motivation and context

Some Python addons need access to Kodi's current locale: language, region , codeset, c++ locale name, etc. Some addons, dependent libraries and external services (TMDb)  need such information. ModuleXbmc::getLanguage met some of these needs, but it has some bugs and I find the api a bit awkward to extend for what is needed.

I propose that getLanguage be deprecated and replaced with ModuleXbmc::getLocaleProperties. As the name implies, an addon sends Kodi a list of property names which Kodi replies with a List (Vector) of Tuple(propertyName, propertyValue) pairs. Simple, extensible and maximizes the amount of information exchanged per call.

The fix is bigger than I like. I started to modify LangCodeExpander but was advised that this area of code was fragile and involved in multiple areas of code, not simply the UI locale. So I stole the essential elements of LangCodeExpander, updated the ISO language and region code tables and (hopefully) simplified a few things along the way so that it both gets me what I need and may also be useful in an updated LangCodeExpander.

ALL changes are contained in LocaleData, TestLocaleData and ModuleXbmc.

Some of the limitations of the existing LangCodeExpander:

- Newer languages were missing due to the aging tables example: "fil" Filipino
- A number of calls assumed that every language hand a 2-char entry (ISO639-1), but Filipino does not
- Did not create a locale name suitable for std::locale. 
- Did not allow for choice of 2 or 3 char region codes
- Could only get info for current active language. 

#22715 
## How has this been tested?

Wrote TestLocaleData to test every API that is functional in GTest environment.

I have instrumented an addon to use these apis to query the possible values with different Kodi language configurations.

Could only test with current, default en_GB locale because that is the only one that you can assume is on all test machines (and only one is present in GTest env). The tests used apis that queried all installed languages, but only one was returned.
Only tested on Linux.

Since the changes are all in new code it should not impact any other code.
## What is the effect on users?

Should not directly impact users. Only give correct info to addons. For my (unreleased) random trailers addon it will allow TMDb to download movies for the correct language/region as well as movie certifications for the country.

## Types of change

- [ x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ x] My change requires a change to the documentation, either Doxygen or wiki
- [ x] I have updated the documentation accordingly
- [x ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] I have added tests to cover my change
- [ x] All new and existing tests passed

### CODE REVIEW

**Comment by CastagnaIT** [comment]
i see that its draft PR,
however since you open it, suggest you to read our guidelines because this PR dont respect them

https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md
https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md

**Comment by fbacher** [comment]
> i see that its draft PR, however since you open it, suggest you to read our guidelines because this PR dont respect them completely
> 
> https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md

I take your points. Very sloppily written sections by me. I also jumped the gun submitting this at all. I had coded this months ago and did some preliminary testing only now to find out there is a big kink that requires some rework. 

In testing with Filipino (Talagog) the language code is 'fil' and region is 'ph'. But 'fil' is iso639-2 and there is no iso639-1 entry for it. The code assumes that every  language has an iso639-1 entry, causing nothing to be found. I assume because the code was written in 2009 and 'fil' may not yet have been added. Not sure. More research.

I did make a prototype that worked fairly well and seemed much simpler. It basically creates a big table with all of the ids that a language is known by (639-1, 639-2, etc.), along with an index of ids. It helps that this code seems to be used exclusively by ModuleXbmc so that makes it a bit easier to test.

**Comment by CastagnaIT** [comment]
In the langcodeexpander there are several workarounds and some current "weird" behaviour on some methods are intentionals,
mostly because we do not support country codes and this leads to several problems
the most serious is the incorrect language selection when video playback starts, or wrong language code description displayed in the audio/subtitles track list, or problems in to handle advancedsettings xml language codes where an user can override/add new/missing language codes

searching for a language code, by using language addons is a old hack
Ideally, language management should be completely reworked to use IETF BCP 47 in order to remove all hacks

also keep in mind that Lookup and ReverseLookup must have the same "inverted" behaviour, your WIP code currently have introduced a discrepancy

if you make a changes in to language expander you have to test whole kodi related features not only python addon,
i suggest you, if you have not done so, to look to github history and read all old PR's in order to know the reason why the current source code is as is, and also make test for each use case

**Comment by fbacher** [comment]
@CastagnaIT 

Thanks for the background. It fits in with what I have been discovering. I especially like the BCP 47 comment, which made my heart sink when I dived into this subject before. Yes, you have to deal with the standards changing, with the DVD industry switching what standard they follow, their own backwards compatibility and so on. I wouldn't be surprised if live broadcast/pvr has its own set of grief.

Looks more and more like I should leave existing code alone and perhaps create something that will fulfill getLanguage needs, which will be Locale based (ISO639/ISO3166_1) and not BCP 47. 

I will proceed much more carefully. I am sorry for the fire drill. 

Frank

**Comment by fbacher** [comment]
@CastagnaIT
I have not yet looked at the PRs.
I created private code for my needs, but realized that some BCP-47 awareness was needed. To get to know BCP-47 better I have partially implemented code that uses IANA BCP-47 data to validate and generate BCP-47 compliant language tags. It is a big job for a complete implementation. Probably, at least for getLanguage, it is enough to parse and format language tags/subtags without validation/correction (other than to prefer ISO-639-1 over 639-2T over 639-3 and perhaps a few other simple changes).

Do you see a need in Kodi for a full implementation of BCP-47 (parsing, validation, substituting preferred-values,  language matching/filtering)?

**Comment by DeltaMikeCharlie** [comment]
I'm new to Kodi and I was unaware of this PR until today.

I have also identified issues with the 'xbmc.getLanguage()' function as detailed here: [https://forum.kodi.tv/showthread.php?tid=372626](https://forum.kodi.tv/showthread.php?tid=372626)

Rather than discard/deprecate xbmc.getLanguage(), I have managed to remediate the function on my local branch and was preparing to submit a PR in the next few days.  There is still a lot of debugging/logging that I need to remove first.

Most of my remediation takes place in the CLangInfo class where the langinfo.xml file is loaded.  I added new properties to hold the ISO_639_x codes and name from the language as well as the ISO_3166-1_x codes and names from the region.

Some getter methods were also added to the class for easy access.

I also added ISO_3166-1_x code/name lookup functionality into the CLangCodeExpander class.

My new xbmc.getLanguage() simply calls the appropriate getter function and returns those values.

Results:
```
xbmc.getLanguage(xbmc.ENGLISH_NAME, True) = English (Australia)-Australia (24h)
xbmc.getLanguage(xbmc.ENGLISH_NAME, False) = English (Australia)
xbmc.getLanguage(xbmc.ISO_639_2, True) = eng-AUS
xbmc.getLanguage(xbmc.ISO_639_2, False) = eng
xbmc.getLanguage(xbmc.ISO_639_1, True) = en-AU
xbmc.getLanguage(xbmc.ISO_639_1, False) = en
xbmc.getLanguage(xbmc.ISO_NAME, False) = English
xbmc.getLanguage(xbmc.ISO_NAME, True) = English-Australia
```
Having all of the values derived from the codes and not the names means that language/region names can be presented in their native language to the end user.

As an aside, 'CLangInfo::Load' seems to be looking for a 3 character ISO_639_2 from langinfo.xml but falls back to a 2 character ISO_639_1 if required.

**Comment by fbacher** [comment]
@DeltaMikeCharlie

You may indeed have something that will solve my needs. I'll have to look further. I have still been pursuing BCP47 implementation 1) to learn more about the issues 2) I'm stubborn at times.

I apologize for my rambling response here. I wanted to respond now instead of waiting any longer. I'll try to follow up with a better response in a few days.

You may want to install and look at the 77 (or more) resource.language.* addons and make sure the code can handle them. resource.language.fil uses an iso639-2T code (fil) which has no 639-1 equivalent. LangCodeExpander.cpp does have "fil" registered for "filipino" in its g_iso639_2 table but the code seemed to ignore the iso639-2 code in favor of iso639-1.

Among the things that BCP-47 recommends is when a language code is needed, that the first matching one be used. The preference order is iso-639-1, iso-639-2T, iso-639-3, iso-639-5 + some private codes that I don't think we care about.

A few more of those resource.language addons are worth looking at and making some tests for. A few of those addons seem to have defined their locales incorrectly. 

I just noticed that Python prefers BCP-47 format locales, so that simplifies the formatting a bit, however if a Unix LANG has to be created to exec a program, then a different format will be needed (unless Python can do this).

I think good API documentation for getLanguage will help a lot. There should be no guesswork about what exactly is being returned 

If we ever get the ICU4C library in Kodi, then we could use it's BCP-47 locale functions for a robust implementation. 

Writing gtests for this is tricky. Kodi has not fully initialized its locale and language addon code when the unit tests run. The main thing you have access to is "en_GB". You could probably write a small Python addon that would configure the locale and then call getLanguage. That way you could test against every supported language. I don't think there is support for such tests in the build environment. 

Be sure to check for undesirable side effects on other code that uses CLangInfo. I count about 36 files including CLangInfo, including DVDInputStreamBluray.cpp, DVDInputStreamNavigator, VideoPlayer,  and so on. My memory is that different Video formats have the language information in formats prescribed by the container API which varies by video format and versions of standards involved. There may not be anything to worry about, but then again, there might be.

**Comment by DeltaMikeCharlie** [comment]
@fbacher - Thanks for your feedback.

I did not actually change any existing behaviour within the CLangInfo class.  I added new properties and new getter methods precisely so that the other functions would remain unchanged.  Although I do understand the need to verify that the rest of the system works as intended.

The only 'change' that I made to code was in xbmc.getLanguage() plus associated modules to add the new ENUM.

I will push the local branch that I used to create these modifications back to GitHub.  All of the debugging/logging code will still be in place, but it will give you a good idea of what I did.  After you have a look, we can then decide where to go with it from there.

I have actually already installed all of the language addons and I wrote a Python script to extract all of the language/region properties into a tab-delimited file so that I could analyse them with a spreadsheet.  As a result of that evaluation, I also discovered the 'fil' issue.

It would not take too much more work to take the existing script and then cycle through all of the languages and see what values xbmc.getLanguage() returns.

In my fix for xbmc.getLanguage(), I decided to return iso-639-2 when iso-639-1 was not available.  I contemplated returning null, but decided against it.

The way I look at BCP47 is that it has the potential to be a big job with strategic implications that need to be well thought out in a way that provides backwards compatibility for existing functions.  It may also involve a rethink on how langinfo.xml is structured.  Patching xbmc.getLanguage() was a quick tactical fix for addon developers.

**Pull request closed without merging**
