### PR TITLE
Add poster-option for recently-added movies

### PR DESCRIPTION
**Pull request by DaVukovic**
## Description

This change gives the option to use "Poster" as possible artwork for the `Window(Home).Property(key)`-infolabel

I might have set the wrong labels. Please correct them if needed. 

## Motivation and Context

Skin Confluence currently has the problem that it uses for example: 
`<thumb>$INFO[Window.Property(LatestMovie.7.Thumb)]</thumb>`
to refer to the movie artwork at the "Recently added movies"-section. With the current code it's not possible to show movie posters, only thumbs. As there's no option to use "Poster" instead of "Thumb" and fixing that would require a bunch of skin confluence re-writing, I would love to have this option available and probably other skinners can make use of it as well

## How Has This Been Tested?

Tested of Fedora with current Kodi master and an additional change at Confluence itseld. Please see:
https://github.com/xbmc/skin.confluence/pull/82

## Screenshots (if appropriate):
Before this change here and the change a Confluence, please see this forum thread: 
https://forum.kodi.tv/showthread.php?tid=356715

After the core and Confluence change:
image

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by ronie — APPROVED** [review]
looks good to me.

it's most likely due to https://github.com/xbmc/xbmc/pull/17127, as that PR stops 'Thumb' from returning a 'Poster' if available.

**Review by gade01 — APPROVED** [review]
Good idea.
Looks great.

**Comment by DaVukovic** [comment]
As @gade01 created a way better PR than mine for skin confluence ti fix the home screen widgets, this one is currently not needed any more for confluence. Still other skinners might probably benefit from it. so I leave this one open ;)

**Comment by ronie** [comment]
while the fix is still valid, perhaps it's time to remove the recently added job from core?
skins today have better ways to fill their home screen widgets with recently added items.

**Comment by DaVukovic** [comment]
Would be fine my me if we don't need that at all anymore. But I can't do that as I guess it's absolutely not enough to simply remove this file ;).

**Pull request merged**
