### PR TITLE
bump to 16.0 beta 5

### PR DESCRIPTION
**Pull request by MartijnKaijser**

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Shame this missed the mysql fix.

**Comment by MartijnKaijser** [comment]
well there are more to come

**Comment by MilhouseVH** [comment]
My bad for not understanding the process which is to bump, merge then finally tag.

**Comment by MartijnKaijser** [comment]
it's chicken/egg. First bump then tag or first tag then bump.

**Pull request merged**
