### PR TITLE
fixed: File times for vfs addons (fixes #15426)

### LINKED ISSUE #15426: Sort by date doesn't work in sftp add-on (vfs issue)
### Describe the bug
Sort by date doesn't work in the sftp add-on. When you browse an sftp location and choose sort by date, it instead sorts by filename.

## Possible Fix
I looked through the code and found that the sftp add-on is populating the timestamp of the file:
`kodi::vfs::CDirEntry entry;
[...]
entry.SetDateTime(attributes->mtime64);`

However, in VFSEntry.cpp (in kodi core), you find this code:
`static void VFSDirEntriesToCFileItemList(int num_entries,
                                         VFSDirEntry* entries,
                                         CFileItemList& items)
{
  for (int i=0;i<num_entries;++i)
  {
    CFileItemPtr item(new CFileItem());
    item->SetLabel(entries[i].label);
    item->SetPath(entries[i].path);
    item->m_dwSize = entries[i].size;
    //item->m_dateTime = entries[i].mtime;`

Note the commented out line. I don't know why this was done. I believe m_dateTime is a CDateTime which has an override for assigning a time_t value so fixing this issue should be as simple as uncommenting that line.

### To Reproduce
1. Add an sftp source
2. Browse files, select your source
3. Choose to sort by date

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by arnova**
Backport #16431

### CODE REVIEW

**Comment by ksooo** [comment]
Sorry, no API changes for Leia.

**Review by ksooo — CHANGES_REQUESTED** [review]
-1 as we do not do API changes for minor releases (means no way to get any API changes merged for Leia)

**Comment by DaveTBlake** [comment]
@ksooo the addition of an optional parameter at the end of a function call is a non-breaking change, could that not be allowed in a backport as part of a fix? It will not give API consumers any problems

**Review by Rechi — CHANGES_REQUESTED** [review]
As already mentioned in the master PR, this isn't an acceptable change for Leia.

**Comment by arnova** [comment]
@ksooo : Personally I don't mind, but I think technically there's no real API change. It's only internals that are affected.

**Comment by Rechi** [comment]
One also has to care about ABI changes. That's why you also bumped min API versions, which means you can't compile with 18.[0-3] headers for versions with this PR or the other way around.

**Comment by arnova** [comment]
> One also has to care about ABI changes. That's why you also bumped min API versions, which means you can't compile with 18.[0-3] headers for versions with this PR or the other way around.

Bumping it wasn't my idea ;-)

**Comment by ksooo** [comment]
Guys, this is all a big mess.

> I think technically there's no real API change. It's only internals that are affected.

 I now remember that somebody said that this breaking change https://github.com/xbmc/xbmc/pull/16500/files#diff-9ea3e38d3a190a40caf0db95fc00bbf3R44 does actually not break something because this struct is not used. I voted for not changing that struct then but somebody else wanted that we do it (for reasons I cannot understand, tbh), but the consequence of this change is that this PR introduces an ABI breaking change and that requires bumping. We never (!) know whether something is actually used or not!

**Pull request closed without merging**
