### PR TITLE
[cleanup] lib/libexif: dead code

### PR DESCRIPTION
**Pull request by stefansaraev**
@jmarshallnz is this ok?

### CODE REVIEW

**Comment by jmarshallnz** [comment]
Seems to only be in play if win32 and a .dll, which I presume is not how it
is used, so all good.

**Comment by MartijnKaijser** [comment]
@jmarshallnz so we don't need the jpg anymore stored on your c:\ drive ? :)

**Comment by jmarshallnz** [comment]
And here I was thinking it was a failsafe backup... :)

**Comment by stefansaraev** [comment]
oh wait, I messed up. it is a dll and is dyloaded.

**Comment by stefansaraev** [comment]
sry. now good. jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
