### PR TITLE
Helix

### PR DESCRIPTION
**Pull request by onetechgenius**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
What is this about? 

Btw I want a word with you as you are violating our trademark.

**Comment by onetechgenius** [comment]
Hello,

Good evening, working on a class project for school. I am sorry if i am bothered you. I would like to fork helix.
I do not want to over step with ignorance. I do not want to violate any trademarks.
can you suggest anything so i can avoid bothering you?

thanks

jason

**Comment by MartijnKaijser** [comment]
You may not create any software using "kodi" or "xbmc" in the name without our explicit approval. The stuff you have on your website is in clear violation. You are also listing piracy related content which is also a violation. "xbmchelper" and "kodihelper"  names are strictly forbidden. 
http://kodi.wiki/view/Official:Trademark_Policy

We insist that you remove every trace of the software you created using one of our brand names and remove the mention helper groups from and social network and websites.

**Comment by onetechgenius** [comment]
Martijin,
I am working on removing the names. I understand the privacy issues. May i ask about creating my own fork?

Is that acceptable?

What other options do i have without being shunned from doing what i thought was the idea of open source and freedom of internet. and the growth of everyone having a chance to learn and try to make something of themselves. Your work is in a realm of transition please allow me to have the same. I mean no harm.

Thank you

Jason

**Pull request closed without merging**
