### PR TITLE
[pvr][Matrix] error dialog should not appear for timer rules with neither start or end time

### PR DESCRIPTION
**Pull request by phunkyfish**
## Description

Backport of https://github.com/xbmc/xbmc/pull/19552 which fixes: https://github.com/xbmc/xbmc/issues/19548

## Motivation and Context

Should also be fixed in Matrix

## How Has This Been Tested?

On OSX, with pvr.vuplus.

User testing by @djp952 also required.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by phunkyfish** [comment]
@djp952 can you test this with your use case please?

**Comment by djp952** [comment]
Tested Matrix branch build, also looks good here, thanks again @phunkyfish !

**Review by ksooo — COMMENTED** [review]
clang-format !

**Comment by phunkyfish** [comment]
> clang-format !

Why clang format? Line length does not apply to comments.

**Comment by ksooo** [comment]
> Why clang format? Line length does not apply to comments.

 jenkins is of a different opinion. => https://jenkins.kodi.tv/job/BuildMulti-PR/18876/artifact/PR19552.diff

**Comment by phunkyfish** [comment]
Ya, sure that infinitely more readable.

**Comment by phunkyfish** [comment]
Ok, fixed now @ksooo

**Review by ksooo — APPROVED** [review]

**Pull request merged**
