### PR TITLE
Add date to the log records

### PR DESCRIPTION
**Pull request by JimmyS83**
## Description

This adds date to the existing timestamp in kodi logs. Its very usefull when using on 24/7 boxes.
## Motivation and Context

I always struggle to find correct logs quickly in troubleshooting X days back problems.
## How Has This Been Tested?

On my own boxes.
## Screenshots (if appropriate):
Before:
```
20:35:34.329 T:3887018864  NOTICE: thread end: video_thread
20:35:34.330 T:3878626160  NOTICE: deleting video codec
20:35:34.346 T:3878626160  NOTICE: Closing stream player 3
20:35:34.364 T:4087664656  NOTICE: VideoPlayer: finished waiting
```

After:
```
2019-02-07 12:17:45.687 T:4091854864  NOTICE: initialize done
2019-02-07 12:17:45.688 T:4091854864  NOTICE: Running the application...
2019-02-07 12:17:45.696 T:4091854864  NOTICE: starting zeroconf publishing
2019-02-07 12:17:45.696 T:4091854864  NOTICE: CWebServer[8080]: Started
```
## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [X] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by JimmyS83 — COMMENTED** [review]
forgot GetCurrentLocalTime() call in log.cpp, fixed. Could you please trigger build? It will pass now.

**Comment by DaVukovic** [comment]
I guess your commits need to be squashed.

**Comment by JimmyS83** [comment]
> 
> 
> I guess your commits need to be squashed.

You have right. Corrected now. Build please? :-)

**Comment by JimmyS83** [comment]
> 
> 
> Jenkins build this please

Where is my mind today? :( Fixed again.

**Comment by JimmyS83** [comment]
Replaced by https://github.com/xbmc/xbmc/pull/15457, recents changes blocked automatic build this one.

**Comment by Rechi** [comment]
The merge commit you added is the reason why it failed.
If you want to have the latest changes from the base branch in your PR branch, rebase.

**Pull request closed without merging**
