### PR TITLE
[depends] bump libandroidjni - add deprecated info

### PR DESCRIPTION
**Pull request by joseluismarti**
## Description
See xbmc/libandroidjni#33 (latest commit) 

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [X] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ksooo** [comment]
https://github.com/xbmc/libandroidjni/pull/33 contains no code changes, only comments were added to the files. I don't see the need for the libandroidjni bump suggested by this PR. We can do this with the next libandroidjni functional change.

**Comment by joseluismarti** [comment]
I wasn't planning to do it either, but @howie-f suggested it and I listened to him.

**Review by garbear — APPROVED** [review]
While the theoretical benefits of this PR are in question I'll argue that there's no harm. I wouldn't have asked for comments to be forward-ported, just because it creates noise, but now that the PR is open might as well merge.

It's kinda like Pascal's wager. Do you merge and risk eternal bliss, or close and risk eternal damnation?

**Comment by howie-f** [comment]
i just thought having a different tip in libandroidjni than kodi actually uses might be confusing. now i see having a bump in history but no functional changes in the library is also confusing 🤗. so @joseluismarti 👍 or 👎 ?

**Comment by joseluismarti** [comment]
Yes, I thought that's why you were proposing it too: that Kodi should always have the latest version of the library even if it doesn't affect functionality.

If it's decided to merge there is no problem either as it will not affect anything (only adds documentation).

**Comment by garbear** [comment]
Sounds like the consensus is to just merge. First one to hit that green button gets a cookie.

**Review by ksooo — APPROVED** [review]

**Comment by ksooo** [comment]
Here we go...

**Pull request merged**
