### PR TITLE
[udevprovider] Fix mounting raw filesystems on non partition disks and add support for 'change' udev event

### PR DESCRIPTION
**Pull request by samnazarko**
OSMC is transitioning to UDevil and we noticed that sometimes DVD insertion and removal events are not triggering properly. This patch fixes strcmp() evaluation so that PumpDriveChangeEvents() reacts to DVD changes properly. The result is that Files list wasn't updating automatically. 

We then test for udev_label. If it's empty, we can assume the disc was removed; otherwise it has been added. This to make sure we don't get both the insertion and removal toasts when something changes. 

ping @stefansaraev, as OE is using udevil for some time already.

CC @DBMandrake

### CODE REVIEW

**Comment by stefansaraev** [comment]
well. I can not test with a dvd but I just runtime tested this PR wth regular usb stick. and it seems to be acting weird.

with this pr: http://sprunge.us/jPjD 
1. I seem to be getting some extra unexpected events. 
2. I see "removed device" immediately after I plug in an usb stick (two partitions here
3. while filemanager is open, on re-insert an usb stick, it seems not to be refreshed correctly (due to extra "remove" events?) - sometimes it is not refreshed at all, sometimes only one of the two partitions  appear

without this PR: http://sprunge.us/ChPN - so you have extra log for reference. but you can test yourself.

**Comment by samnazarko** [comment]
Interesting -- does the device have a label? If not, then try setting one and seeing if the behaviour changes. This would mean that we need to be careful checking udev_label.

**Comment by stefansaraev** [comment]
nope. no labels. and I dont want to set labels.

**Comment by fritsch** [comment]
To get the original base fixed, this: http://sprunge.us/COcR should be enough. Then we need to decide about what we should do about block devices. Perhaps additionally checking isRemovable or something.

**Comment by samnazarko** [comment]
We need a better way to check things: 'change' is an annoying event that isn't handled properly in Kodi yet. 'change' is fired when a DVD is removed or inserted.

Perhaps we check for udev_label if and only if optical is set.

**Comment by stefansaraev** [comment]
you can easily test my use case. do gpt partitioning on an usb stick. create two partitions. format as follows: part1 - vfat. part2 - ext4. no labels. (that's how OE generic64 install stick look like, but without labels) :)

**Comment by fritsch** [comment]
@samnazarko yes, but we also want to fix the issue we have in the code. So to get a status we "originally" wanted. Can you try the sprunge link I sent on plain master?

Then we can elaborate what usecases are still missing and fix them?

**Comment by stefansaraev** [comment]
//cc @ksooo you fixed something in 4777a5bfcbad03d5dec29fc862e542d07003ce05 ;)

**Comment by samnazarko** [comment]
@fritsch I have tested your patch. Don't see any regressions with a DVD disc or USB flash drive. 

The missing case is that when using a DVD or optical drive, discs being changed signal 'change' events, rather than add or remove. We want Kodi to know about these. 

See http://paste.osmc.io/iyebigefur.md from @stefansaraev's suggestion to use udevadm monitor -p.. Looks like we have DISC_MEDIA_CHANGE property which may be useful here.

**Comment by stefansaraev** [comment]
@samnazarko here

https://github.com/xbmc/xbmc/compare/xbmc:master...stefansaraev:udevprovider-fix

first commit fixes a bug. one may have raw filesystem directly on the disk (no partitions, just a filesystem).

2nd commit is what you want - handle change event. check if DISK_MEDIA_CHANGE or DISK_EJECT_REQUEST is set, you may have to tweak it in case DISK_MEDIA_CHANGE/DISK_EJECT_REQUEST is not enough, but you get the idea.

**Comment by samnazarko** [comment]
@stefansaraev This works OK in my limited testing.

**Comment by stefansaraev** [comment]
nice. do you want me to send another PR or you will pick my commits ?

**Comment by samnazarko** [comment]
I removed my commit, cherry-picked yours and force pushed to my old branch. Is this OK?

**Comment by stefansaraev** [comment]
yep. looks ok. 

@davilla wrote the original code. and I dont know if he still uses this. hope he still cares to review :)

**Comment by MrMC** [comment]
oh that was so long ago :)

**Comment by stefansaraev** [comment]
ok. @samnazarko 

@fritsch was doing some tests. on ubuntu+udevil+devmon runing. and the 2nd (change event) commit is really. really bad. segfaults here and there. 

however. @fritsch told me that blurays and dvds work fine for him, without my changes (this pr, as is at the time of wriing this). so, honestly, I have no clue what your issue is now. and how this is ok in your testing...

**Comment by samnazarko** [comment]
OK, let's not PR yet, let's see what the issues are first.

@fritsch Can you change DVD and get a timely notification in Kodi without checking for 'change' events? In our findings, it takes some time, because while it is eventually picked up, we want a nice quick callback and if udev gives us that we should use it. Can you post udevadm monitor -p output for your DVD drive?

I think that regardless of whether you consider 'change' an event worthy to monitor or not, the current UDev code needs some work.

**Comment by fritsch** [comment]
With the latest PR seo sent everything is fine. When I plug in a DVD / Bluray - kodi offers me "Play Disc". When I eject the disk, the Main menu entry is gone.

I am using a default installation of udevil without any config changes. Btw. the code path that is patched here is _not_ used for dvds / blurays.

**Comment by fritsch** [comment]
Btw. do you have an issue with dvds that have a "normal" filesystem, e.g. data dvds? This I did not test - only movies.

**Comment by samnazarko** [comment]
@fritsch 

I am aware that Kodi will try and mount at a block device level for DVD / BD. In our findings, this was why it often succeeded. 

But yes -- Data DVD was problematic at times, but with my testing in this PR, I used a retail DVD (Dodgeball), from 2005. 

CC @DBMandrake

**Comment by DBMandrake** [comment]
@fritsch 

The issues we were seeing were primarily for data DVD's - Kodi detects and handles Movie DVD's (which display the "Play Disc" option) different to play data CD's / DVD's. For those, you would only see the contents of the disc in for example Video->Files.

Here, udev storage provider would not update the file list when optical data discs (CD's or DVD's) were inserted or removed, as the change event did not seem to be handled. With the udisks storage provider insertion and removal of data discs is handled correctly. (Pop up notification and files list updated dynamically)

Our patches are an attempt to get a consistent behaviour between the udisks storage provider and udev storage provider for optical disks so that we can transition to udevil without loss of functionality.

**Comment by fritsch** [comment]
Yeah - that's what I asked above. Though the initial patches were not correct. The patches @stefansaraev made as a follow up of this discussion here fix some older bugs we had and are fine as a bugfix.

We need to test and elaborate on this one: https://github.com/samnazarko/xbmc/commit/df4ccaa4991ab44e7a80c10a115b95b831f81f18 to get the use case: howto mount a data dvd working.

**Comment by samnazarko** [comment]
>We need to test and elaborate on this one: samnazarko@df4ccaa to get the use case: howto mount a data dvd working.

insert data dvd
remove data dvd

with udevadm monitor -p and debug logging enabled is sufficient? 

@fritsch -- you say the current code path does not affect the video dvds? Is this because Kodi mounts discs at block level first? If not, then do you get different udev events from insertion and removal of a disc?

**Comment by fritsch** [comment]
As said above I don't have an data dvds that are not bought movies or bought bluray movies. That's why I said - this special case needs to be implemented in a separate commit while the other two commits are bugfixes and can go in after review https://github.com/xbmc/xbmc/pull/8334

**Comment by stefansaraev** [comment]
I'll try get a dvd rom and see what I can do.

**Comment by fritsch** [comment]
Thanks much, fixed via: https://github.com/xbmc/xbmc/pull/8334

**Pull request closed without merging**
