### PR TITLE
Fix for #11564 - pictures via upnp

### PR DESCRIPTION
**Pull request by Memphiz**
This fixes the regression since dharma which is described in ticket http://trac.xbmc.org/ticket/11564. (view pictures via upnp)

Thx to elupus for giving the solution for this one.

### CODE REVIEW

**Comment by bam80** [comment]
I've updated http://trac.xbmc.org/ticket/11564 - seems the feature broken again

**Comment by bam80** [comment]
@Memphiz, @elupus - any thoughts? Can we reopen the issue at least?
Another report on this, with logs: http://forum.kodi.tv/showthread.php?tid=232517&highlight=upnp

**Comment by Memphiz** [comment]
@Montellese any idea if something in the upnp code changed? The idea for handling files with upnp:// protocol is to extract the file info from the upnp path via CUPnPDirectory::GetResource and then throw a CRedirectException to the cfile layer which then opens the resolved url via filefactory...

**Comment by Montellese** [comment]
@Memphiz: I'm not sure why pictures should work differently than videos or music?

**Comment by Memphiz** [comment]
Its odd - i got it reproduced at one point. But then i can't atm anymore. Its working for me with my upnp server and all picture folders i throw at it now. But at the beginning it somehow didn't (no file sizes and only blackscreen). I had the feeling it was something about the directory cache but was not able to dig deep enough during the session where it didn't work...

**Comment by bam80** [comment]
@Memphiz, did you manage to reproduce the bug?

**Comment by Memphiz** [comment]
no my last statement holds true ... i will not investigate any further for now due to really limited overall time.

**Comment by bam80** [comment]
then, could you recall steps you did when it suddenly start working again? So we could use photos over UPNP somehow..
And, if no one can fix the bug for now, shall we reopen [the bug on Trac](http://trac.xbmc.org/ticket/11564), or create new one?

**Comment by Memphiz** [comment]
i restarted kodi after adding the upnp picture source and then it worked. Even deleting end recreating another upnp source didn't bring the bug back then...

**Comment by bam80** [comment]
I had no luck to reproduce your behavior..
Interesting thing: if press 'i' on picture from the list to show Info - it always gives me meaningful size, but when I do the same pressing 'o' while viewing the picture - the size sometimes is 0, and sometimes right one.

**Comment by bam80** [comment]
Some progress here:
somehow, very slowly and glitchy, thumbnails gets filled for one of UPNP share, but viewing nevertheless inaccessible - black screen there

**Comment by bam80** [comment]
Since the bug was not reopened, we have created a [new one](http://trac.kodi.tv/ticket/16255)

**Comment by EricV2** [comment]
I created the UPnP as it did exist on the two test machine. I can browse the content, see the picture names, no thumbnails and it is also black.

DMS=minidlna

**Comment by mkortstiege** [comment]
Please comment on the ticket. Commenting on github spams too many team members.

**Pull request merged**
