### PR TITLE
[Estuary] Fix  - remove duplicate track info

### PR DESCRIPTION
**Pull request by jjd-uk**
## Description
Remove duplicate info for the selected track & total track count.

## Motivation and Context
Reported by @ksooo on Slack

**Image from ksooo**
image

As can be seen in highlighted areas there a 2 placed the selected track number is shown and the total track count.

The Selected track text had been introduced for the new Now Playing view in the Music Playlist window, so the 2 sets of info on left & right could be easily distinguished.

**Now Playing view**
image

However it was implemented in a too simply way that led to the duplicate info.

**FIX**

The Selected track and associated text has now been moved into the ListBoxInfoVar variable then conditions added for the variable as to whether the Music Playlist window is open or not. This means the Selected track and associated text is only ever shown in the Music Playlist views.

**After fix - Widelist music window view**
image

**After fix - Widelist music playlist window view**
image

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [x ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by jjd-uk** [comment]
@ksooo fix for the issue you raised on Slack.

**Comment by ksooo** [comment]
@jjd-uk lgtm, many thanks.

**Comment by da-anda** [comment]
I'm wondering in general what the "selected track" info is good for. The track number is visible right below it as well, so the only actual new/additional info is how many tracks the album has, and that info could probably be added in a different way. Not against the change in this PR, just curious about the usecase/usefullness.

**Comment by jjd-uk** [comment]
> I'm wondering in general what the "selected track" info is good for. The track number is visible right below it as well,

2 completely different things that may just happen to the be same. One is the position of the items in the list of things to play, the other is the album track number, if you have random selected for example then the item in position 2 is unlikely to be album track 2.

**Pull request merged**
