### PR TITLE
[win32] improvements to make-addons.bat

### PR DESCRIPTION
**Pull request by Montellese**
These three commits add a few improvements to WIN32's buildstep script `make-addons.bat` which we use to build binary addons.
- Possibility to call `make-addons.bat` and pass in the names of multiple binary addons to be built (e.g. `make-addons.bat pvr.demo pvr.vdr.vnsi`). Right now it's only possible to specify a single binary addon to be built.
- `make-addons.bat` doesn't abort anymore if building a single binary addon fails. This is only true for the actual build process. If there's a problem in our (not the binary addon's) buildsystem it will fail completely.
- Successfully built binary addons are written into `project/cmake/addons/.success` and failed ones are written into `project/cmake/addons/.failure`.

@Memphiz: Let me know if the `.success` and `.failure` file-based approach with one binary addon name/ID per line works for you on jenkins. The files are deleted with every call to `make-addons.bat` and then created when building the addons. If all addons fail to build there's no `.success` and if all addons build fine there's no `.failure` but that could be adjusted that the files always exist but are empty if that's easier for you.

### CODE REVIEW

**Comment by Montellese** [comment]
jenkins build addons please

**Comment by Montellese** [comment]
IOS failure is unrelated. WIN32 worked perfectly fine i.e. it tried to build all binary addons even though some of them failed.

**Comment by MartijnKaijser** [comment]
one of the pvr addons is broken on windows. Know issue

**Comment by Memphiz** [comment]
@Montellese this is perfectly fine. The problem is now that i don't have this granular information on the other platforms. There i can only detect if xbmc-pvr-addons as a whole failed to build or audiodecoders or viz. The question is if you can think of a solution which creates the .failure and .success files in a platform independend way somehow by using the cmake stuff?

**Comment by Montellese** [comment]
@Memphiz: I don't know if this is really possible with cmake because we use cmake to generate buildscripts which are executed by calling `make` or `nmake` or whatever. But maybe google knows a way ;-)

**Comment by Memphiz** [comment]
then instead i maybe should try to do something similar like what you do in the batch file in our depends - and combine all binary addons to one target in that move...

**Comment by Montellese** [comment]
Yeah combining all binary addons in one target would probably make sense. For development purposes a dev usually only wants to build one addon and for deployment purposes we always want to build them all. Not sure how that fits into the linux packaging which currently provides an audioencoder and a pvr package IIRC.

What I did with `make-addons.bat` is that I either take the addons passed in as arguments or I read all directories from `project/cmake/addons/addons` and use that list of addons to be built. I then call `cmake` with that list of addons and later on call `nmake` once for every addon.

One disadvantage I came across with this approach is that common dependencies like `tinyxml` and `kodi-platform` are constantly rebuilt (well actually they are only checked and installed because they have already been built).

**Comment by Memphiz** [comment]
@Montellese - here is the result btw:

http://jenkins.kodi.tv/job/BINARY-ADDONS/platform_label=win32/104/

**Comment by Montellese** [comment]
Cool.

**Comment by Memphiz** [comment]
that that i think this PR is fine :) - will now think on how to get rid of the duped groovy script for all our jobs ... (want to have it only once...)

**Comment by Montellese** [comment]
@Memphiz: Is it ok if the files don't exist if no addon has succeeded or failed?

**Comment by Memphiz** [comment]
yes thats all handled. I check for existence of those files before putting its contents to the build result

**Pull request merged**
