### PR TITLE
Fix scrollbar navigation back to list

### LINKED ISSUE #15994: Estuary settings scrollbar "traps" focus
### Describe the bug

The stock Estuary skin has a scrollbar in the "Main menu items" skin setting and if the user moves focus to this scrollbar there is no way to move the focus back to the settings other than to press "back" and exit from the skin settings.

## Expected Behavior

Should be able to move the focus back from the scrollbar to the settings.

## Actual Behavior

Focus is "trapped" by the scrollbar.

### To Reproduce

1.  Go to Settings > Interface > Skin > - Configure skin... > Main menu items
2. Move the input focus to the scrollbar
3. Focus is now "trapped", only option is to press "Back" (on keyboard/remote/mouse)

### Debuglog

I don't think it's likely to be relevant, but it's here: http://ix.io/1Hhc

### Screenshots 

Start here:
s1

Then move focus to the scrollbar, here:
s2

and now you are unable to return to the position in the first screenshot as focus is "trapped" by the scrollbar.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC RPi/X86_64 and Ubuntu x86_64.
 - Kodi version: 19 (latest master), but I've gone back through 365 days of test builds and it's the same in Kodi 18 from 16 April 2018, so not a new issue.

### PR DESCRIPTION
**Pull request by Hitcher**
## Description

Fixes a problem when focusing the scrollbar for 'Main menu items' and being unable to navigate back to the list.
## Motivation and Context

Fixes https://github.com/xbmc/xbmc/issues/15994
## How Has This Been Tested?

Yes.
## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Thanks, fix confirmed - appreciate the fast turnaround!

**Comment by ksooo** [comment]
The diff is 350 changed lines. Really? What did you actually change?

**Review by ksooo — CHANGES_REQUESTED** [review]
Oh no, you seem have to replaced all tabs by spaces (or some other whitespace change). You wanted only to insert a single line, right? => ```<onleft>610</onleft>```

Could you please redo the commit with only the real change?

**Comment by HitcherUK** [comment]
> Oh no, you seem have to replaced all tabs by spaces (or some other whitespace change). You wanted only to insert a single line, right? => `<onleft>610</onleft>`
> 
> Could you please redo the commit with only the real change?

Bloody GitHub 'drag and Drop' file option!

**Comment by HitcherUK** [comment]
I'll do it again when I've got more time.

**Pull request closed without merging**
