### PR TITLE
Fix bug for not applying VolumeAmplification setting correctly at playback: issue# 17564

### LINKED ISSUE #17564: Volume low despite settings in audio gui for Volume Amplification
### Describe the bug
Here is a clear and concise description of what the problem is:
Sometimes when launching Kodi, the volume is low, despite having Volume amplification set as default for all, (.set at 14db currently) and Audio settings in gui showing 14db.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Once the Volume Amplification is set correctly, it should always work.

### To Reproduce

Steps to recreate:
1. Launch Kodi
2. Play media (movie or tvshow)
3. Volume will be low (despite setting in gui)
4. Bring up the Audio Settings in gui, and select the Volume Amplification slider.
5. Move the slider down or up from current position, and volume will jump back up to current setting (14db) and will now be correct.
6. Select "set as default for all media" again 
7. Close media and exit Kodi
7. Start Kodi and volume will be low again, despite Volume Amplification will still be showing 14db.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/4391907/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.6 release
WIndows 10 with all latest updates

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by biner73**
## Description

Described in https://github.com/xbmc/xbmc/pull/20131. @fuzzard 

This is the PR to get into master instead of Matrix

### CODE REVIEW

**Comment by ksooo** [comment]
> Update VideoPlayerAudio.cpp

 Next time, please use a more descriptive commit message which gives a hint WHAT was changed.

**Comment by ed76** [comment]
when will this pr backported to kodi matrix?

**Comment by phunkyfish** [comment]
It is backported already. Should be included in next Matrix release.

**Comment by howie-f** [comment]
if i see it correct it was reverted in Matrix https://github.com/xbmc/xbmc/pull/20135 right?

**Comment by ed76** [comment]
phunkyfish, i dont think it is backported to matrix. can you show me the pr, maybe i have missed something? i think the plan was to test this pr some time in master and after that backport to matrix.

**Comment by phunkyfish** [comment]
Ah, sorry. I didn’t look past the Matrix PR. Is it confirmed that the issue is fixed on master?

If so maybe @biner73 could open a new PR for Matrix.

**Comment by biner73** [comment]
> Ah, sorry. I didn’t look past the Matrix PR to see the revert. Is it confirmed that the issue is fixed on master?
> 
> If so maybe @biner73 could open a new PR for Matrix.

I have tested against master since the commit, confirmed it's fixed, and haven't seen any issues. It should be good to go to Matrix, and I can open a PR, but would want to confirm with @fuzzard first.

**Comment by phunkyfish** [comment]
Please open the PR against Matrix and put backport in the title. You can ping @fuzzard in the description so he’s aware.

Remember the feedback on the first PR. Use a commit message that makes sense!

**Pull request merged**
