### PR TITLE
addons: add kodi.game.controller to system add-ons

### PR DESCRIPTION
**Pull request by garbear**
Because i saw #9373 and it looked like a good idea

Should the same be done for peripheral.joystick?

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
No cause peripherals joystick not part of Kodi tree but in binary repo.

**Comment by garbear** [comment]
With this, Kodi fails to start. Changing to `kodi.game` fixes the problem. Does cpluff not consider the .xsd extension points? (see [addons/kodi.game/](https://github.com/xbmc/xbmc/tree/master/addons/kodi.game))

**Comment by MartijnKaijser** [comment]
It needs to be a valid add-on. 
kodi.game.controller isn't a valid add-on id 

Add:
game.controller.default
kodi.game

**Comment by tamland** [comment]
@garbear You seem to have overlooked https://github.com/xbmc/xbmc/pull/8807#issuecomment-189658469 :) Those should be added.

**Comment by garbear** [comment]
yup, missed that. will apply

**Comment by garbear** [comment]
Updated. looks good?

**Comment by MilhouseVH** [comment]
Needs a quick rebase after https://github.com/xbmc/xbmc/commit/82ec441ef81d4e1f94fcd0a4b540513a664922a8

**Comment by garbear** [comment]
done

**Comment by Razzeee** [comment]
I really hope we can also do this for peripheral.joystick, as I'm currently stuck on a shield with only a shield controller. Means I can't navigate kodi, if I update to the nightly, as it seems like peripheral.joystick needs to be activated for kodi to receive input.

**Comment by MartijnKaijser** [comment]
That's not going to work as binary Addons are optional build. For Linux they are not even included in system path so adding it to the manifest would even crash kodi if user doesn't manually install the addon from PPA. 
I agree that current situation is highly unwanted as now every one with a basic controller is completely stuck. 

@montellese @garbear your thoughts please?

**Comment by Montellese** [comment]
What exactly is the problem? When I integrated android joystick API into garbear's input work I always built APKs and installed them on the Shield and the ADT-1 and I never had a problem with that.

**Comment by Razzeee** [comment]
And you used the shield controller, not the remote? If I understood @da-anda correctly, peripheral.joystick is shipped disabled. And to control the shield via controller it needs to be enabled.

**Comment by Montellese** [comment]
I tested with the shield controller, the nexus player controller and another bluetooth controller that I have and it worked fine. But I'm not sure where it is decided whether an addon is enabled or disabled by default.

**Comment by da-anda** [comment]
from my testing, the problem is that peripheral.joystick is not enabled by default, and if you have only a controller as input device, you can't control Kodi in any way. Once enabled, controllers work again. Btw, I had to restart Kodi after enabling the add-on in order to get the controller working. Same for disabling. I was testing yesterdays nightly ( 81fc042 )

**Comment by tamland** [comment]
@Montellese You probably already had it enabled in an old database from before  #9110. After that PR it would default to disable, as other addons.

**Comment by MilhouseVH** [comment]
Could addon-manifest.xml support an optional `enabled` attribute? I noticed that when shipping inputstream.mpd pre-installed, it would be disabled - having a simple mechanism to enable by default would be great.

**Comment by garbear** [comment]
peripheral.joystick isn't meant to be disabled. that’s why I asked about adding to the manifest. If loading peripheral.joystick fails for any reason, it'll be safely ignored. otherwise it should only be disabled by users who know what they're doing.

**Comment by stefansaraev** [comment]
no. peripheral.joystick is not part of default kodi install and is not critical to kodi operation, so it can't be in system manifest.

**Comment by tamland** [comment]
@garbear Why isn't part of our tree, if it's truly required? Right now it just behaves like any other 3rd party addon.

The manifest was intended to be extensible with different kind of configuration options, but we have to have a clear use first.

**Comment by garbear** [comment]
> is not critical to kodi operation

> it's truly required

Can we make up our minds? Look, joystick support is now a binary add-on. If out-of-the-box joystick support is desired (IMO it is) then peripheral.joystick needs to be shipped with Kodi and it needs to be enabled. How can we make this happen?

**Comment by stefansaraev** [comment]
first, move https://github.com/kodi-game/peripheral.joystick to kodi tree
next. remove https://github.com/xbmc/repo-binary-addons/tree/master/peripheral.joystick

that's all

**Comment by garbear** [comment]
> first, move https://github.com/kodi-game/peripheral.joystick to kodi tree

like this? 8ed8f846dc063b2943dddc2f295ce99193d7b007

**Comment by stefansaraev** [comment]
wwwel, those who dont use unified depends wont be happy :)

**Comment by garbear** [comment]
so copy/paste 8000 lines of code into the addons/ directory?

**Comment by stefansaraev** [comment]
@wsnipex what do you think ?

**Comment by Montellese** [comment]
IMO having `peripheral.joystick` as a binary addon that does not reside in the Kodi repository has the huge advantage that we can ship updates/fixes without having to update Kodi itself. This is where we should move with a lot of our code. So sooner or later we need to come up with a way to support shipping Kodi with binary addons that need to be enabled by default. So I'm not sure what people have against that.

**Comment by wsnipex** [comment]
I agree with montellese that it should stay a binary addon. But if its really wanted/needed to be shipped with kodi we have to make sure that happens on all platforms and _also_ non-unified deps builds.
So we need a means of building a list of "system binary addons"(system addons that live out of kodi tree) during or after the kodi build(NOT depends). I've always deemed it stupid to build addons as part of depends anyway...
Its absolutely doable. Cmake should be fairly straight forward, autotools might be a little more difficult.

**Comment by Razzeee** [comment]
So? What are we going to do?

**Pull request merged**
