### PR TITLE
guilib: Two minor code cleanups

### PR DESCRIPTION
**Pull request by garbear**
## Description

This PR contains two code improvements I made in guilib:

* Remove unused function
* Modernize some formatting

## Motivation and context

Desire to send improvements upstream.

## How has this been tested?

Tested in RetroPlayer builds since July.

## What is the effect on users?

* None

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Review by CrystalP — APPROVED** [review]
Cleanup and cosmetic types more than improvement I think.

**Comment by garbear** [comment]
Fair, I wouldn't say "improvement" as far as users go, but I would say that cleanups are "code improvements". But new pr title is certainly more clear, thanks

**Comment by CrystalP** [comment]
I was just going by the definitions of the PR template, not denying that they are improvements to the code :-)

**Comment by garbear** [comment]
Good point.

Build failure unrelated.

**Comment by fuzzard** [comment]
Jenkins build this please

**Pull request merged**
