### PR TITLE
[pvr] fix recordings on the timeline

### PR DESCRIPTION
**Pull request by opdenkamp**
recordings linked to epg tags didn't work correctly, because epg tags are only updated after a timeout, or when an update is forced.

this pr changes the pvr api to have a field 'iEpgEventId' in recordings (matching the unique broadcast id of epg tags), and removes the 'strRecordingId' from epg events.

added a 'play recording' entry to the epg tag info dialog and context menu if a recording is found, and changed the 'switch channel' entry to actually switch to the channel instead of trying to play a recording.

this fixes recordings playback from tvheadend (only add-on that implemented it).

pr for add-ons incoming if anyone wants to test before the add-on build pr is merged in.

### CODE REVIEW

**Comment by opdenkamp** [comment]
oh and some other random fixes are in this pr too, missing initialisers and a wrong file path used for recordings from a channel with a / in it's name

**Comment by FernetMenta** [comment]
do you have time to review #5208 ? if this is ok we could merge both at the same time. would reduce work on the addons.

**Comment by opdenkamp** [comment]
will do today or tomorrow

**Comment by opdenkamp** [comment]
@ronie I've added a temporary commit https://github.com/opdenkamp/xbmc/commit/a982bb4275a8dabfa85c1dcdba72125bf97be611 to test the newly added `PlayerControl(ResumeLiveTv)` command. Could you add some proper icon for resuming live tv on the same channel when playing a recording that's being recorded. It should only be visible when `VideoPlayer.CanResumeLiveTv` is true.

No rush because this PR can be merged without the icon, but it would be nice to have it in the skin at some point.

The other skin change from https://github.com/opdenkamp/xbmc/commit/4e4a08e5b1de48ff5bb76b578627822b4b6e3fca is optional too.

**Comment by opdenkamp** [comment]
jenkins build this please

**Comment by opdenkamp** [comment]
@Montellese android jenkins build failed because of the API change, and the add-ons not having that change in them yet. could you make add-ons failing to build non-fatal? I'm not a cmake expert ;)

**Comment by FernetMenta** [comment]
I guess we have to wait for @Memphiz to adjust jenkins

**Comment by Memphiz** [comment]
its this https://github.com/Memphiz/xbmc/commit/ff2cf4f12d7d1f817694826a108b47933b02a2dc

someone would need to add the same changes to all other platforms (the commit only covers ios because i tested it with it) - unsolved problem is that builderrors in addons can't be spotted (builds are reported green). the plan is that jenkins detects the failed build mark in the filesystem and turns the build yellow - problem is that the file.exists from groovy script always returns false ... long story short - i fear nobody wants to be a part of the jenkins fun - then you need to wait until i am able to contribute again...

**Comment by opdenkamp** [comment]
@FernetMenta @Memphiz https://github.com/xbmc/xbmc/pull/6607

**Comment by FernetMenta** [comment]
yes, I think this is what he suggested

**Comment by opdenkamp** [comment]
renamed the method to `CPVRRecording::IsBeingRecorded()` and dropped the temporary commit for confluence.

jenkins build this please and let's see if add-on failing to build doesn't break the whole build :)

**Pull request merged**
