### PR TITLE
[VideoVersion] Optimize performance especially when is used external/shared video DB

### LINKED ISSUE #24169: Severe performance degradation when is used external database (MariaDB) after video versions feature merge
### Describe the bug
Here is a clear and concise description of what the problem is:

Severe performance degradation when is used external database (MariaDB) after video versions merge: opening the main movie list takes 50 seconds with black screen in a video library with 4000 movies.

This is after merge https://github.com/xbmc/xbmc/pull/14972 when before was almost immediate.

See this video:

https://github.com/xbmc/xbmc/assets/58434170/dad827cf-e2ce-4704-9363-bd66d5abfcbc

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Similar "load" times as before, especially if video versions feature is not used.

## Actual Behavior
50 second of delay and not responsive GUI during this time. Probably in a 10,000 movies collection it would take ~2 minutes.

## Possible Fix
The root cause it is made a extra individual SQL query looking for video versions for every movie populated in list here:

https://github.com/xbmc/xbmc/blob/b4ae12fe3bdf428ed40ca7d6a55f204e23dd83e7/xbmc/video/VideoDatabase.cpp#L4266

then is made this SQL query 4000 times before present movies list:

`"SELECT idFile FROM videoversion WHERE idMedia = %i AND mediaType = '%s'"`

Possible solutions:

1. Include a new "bool" variable in movies table "hasVersions" to avoid extra queries only to determine if movie has video versions. Cons: is need modify DB structure. Pros: seems logical.
2. Retrieve all movie versions info in one single large query and determine "hasVideoVersions" flag locally. Cons: is need extra code. Pros: not requires modify current video database. 

### To Reproduce

1. Use kodi with a remote/shared video database (MariaDB, etc.) containing several thousand movies.

Same behavior is observed in Windows x64 (i7-13700K - 24 cores) and Android (Shiled). Delays do not depend on powerful of client device.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/azizakelex.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

MariaDB

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:  21.0-BETA1 (20.90.801) Git:20231129-53101ab16d

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by thexai**
## Description
[VideoVersion] Optimize performance especially when is used external/shared video DB

## Motivation and context
Fixes https://github.com/xbmc/xbmc/issues/24169

Retrieve entire `videoversion` table only takes 40 ms similar time that individual SQL query to check video versions in one movie...

Then saves 15~20 ms * num_of_movies in DB.

`HasVideoVersions()` is still used when only is need this info for one movie (or less of 15 movies).

## How has this been tested?
Runtime Windows x64 and Shield

## What is the effect on users?
Restores video DB performance same as before of video versions feature.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CrystalP** [comment]
Looks like a decent purely client approach without a db schema change, though the threshold of 15 items and throwing away the cached versions each time could be debated.

Is the DB frozen in beta?

It's not one of the approaches mentioned in Slack (push the work to the DB engine, either by denormalizing the data with a new hasversions bool in movies, or with a join or exists with versions table + index for efficient lookup).

@xodidox, is it necessary to always populate the CVideoTag.m_hasVideoVersions, or only for a few specific data flows?

@da-anda @DaveTBlake discuss here on in Slack?

**Comment by da-anda** [comment]
I am no code authority, nor do know our codebase too well, but a denormalized flag/column in the DB IMHO seems like the best and cleanest approach. I would even go as far and either use a bitmask in this flag/column to be able to check for `hasVideoVersions` and `hasVideoExtras` or two flags/columns (not sure how good sqlite and MySQL/mariaDB are with bitmask constraints)

**Comment by thexai** [comment]
Video versions requires extra query (because is in another table) similar to ratings, cast, tags, etc.

All extra queries should be optional controlled with `getDetails` variable.

This is the current design. 

The question is not whether the current design is the best (video versions in a separated table). That has already been approved and merged.

But in the CURRENT design, video versions is a extra query...

**Comment by thexai** [comment]
> we change it later (once somebody finds the time to change it).

And in a next v22 because is not allowed change DB schema during the life of a major version (AFAIK).

**Comment by CrystalP** [comment]
yes the cardinality requires a separate table, that not being questioned.

The solution with join/exists requires no code but could have a small perf impact. I could probably write it quickly but don't have a representative setup to test the performance.

The denormalized way requires extra code to maintain the bool when versions change and requires more effort and knowledge and I lack the motivation for that

**Comment by xodidox** [comment]
Thanks @thexai for the change. It looks good to me.

> is it necessary to always populate the CVideoTag.m_hasVideoVersions, or only for a few specific data flows?

It's needed for ListItem.HasVideoVersions infoLabel.

**Comment by CrystalP** [comment]
#24183 for the not-denormalized way to fix, using the db engine to do the work.
No remote db available for testing, will try setting one up.

I have no problem cancelling if approach here is preferred. It was interesting to dive a bit in the video db code.

**Comment by thexai** [comment]
Closed in favor of https://github.com/xbmc/xbmc/pull/24183

**Pull request closed without merging**
