### PR TITLE
librarynodes - fix invalid xml

### PR DESCRIPTION
**Pull request by ronie**
this used to be part of https://github.com/xbmc/xbmc/pull/11017 but was dropped for the wrong reasons.

the '&' character needs to be escaped in xml documents.

@DaveTBlake

### CODE REVIEW

**Comment by DaveTBlake** [comment]
Thanks. Not sure why my testing failed that time, but this does work and meets the xml standard (although if users create nodes without escaping the & that works too).

**Comment by ronie** [comment]
the reason it works in kodi is we've written our own function to handle these errors:
https://github.com/xbmc/xbmc/blob/master/xbmc/utils/XBMCTinyXML.cpp#L239
(imo not a good idea as it masks actual errors in the code)

**Comment by DaveTBlake** [comment]
Thanks for the explanation, and I agree masking errors is not good. I will endevour to escape & in any folder type custom node examples I give to users. May even get to update (possibly create) the wiki one day.

**Comment by ronie** [comment]
ping @Ignoble61 
just a heads-up, in case this affects your addon.

**Pull request merged**
