### PR TITLE
[guilib] oninfo for controls

### PR DESCRIPTION
**Pull request by mkortstiege**
This adds `<oninfo>` for controls. It is a rebased and slightly modified version of @Black09's https://github.com/xbmc/xbmc/pull/5229.

It will try direct mappings from keymap first. In case there's no info keymap for the specific window, it will execute the `oninfo` actions assign to the given control. If there are no actions, it will route 'ACTION_SHOW_INFO` to the window/dialog.

/cc @BigNoid, @phil65, @ronie

### CODE REVIEW

**Comment by phil65** [comment]
already tested and confirmed as working.
+2 for this. :)

**Comment by xhaggi** [comment]
@mkortstiege  why do we send a window msg in case we don't find an `oninfo` on the control? We should delegate the action to the specific window like it was before or send the action via our app messenger.

**Comment by mkortstiege** [comment]
> @mkortstiege why do we send a window msg in case we don't find an oninfo on the control? We should delegate the action to the specific window like it was before or send the action via our app messenger.

That's what it is doing. `CGUIControl::SendWindowMessage` is handing it to the window if possible.

**Comment by xhaggi** [comment]
after a second look and our quick chat at irc, I'm sure we do not need to delegate the action to the window again,  neither as a window message nor as an action because the action is passed the window first and end up in `CGUIControl::OnAction`. Changing the call order (call to the parent first) in window's OnAction should be enough.

**Comment by xhaggi** [comment]
we could also add a method OnInfo like we have for OnBack and handle it in CGUIWindow like we do for back actions. A derived window could overload this method to do the toggle handling. more clear IMO.

**Comment by BigNoid** [comment]
Nice, it also works in dialogs now, thx :)

**Comment by xhaggi** [comment]
@mkortstiege as disucced i've updated the PR. mind taking a look.

**Comment by mkortstiege** [comment]
Thanks a lot, looks way better than routing the toggles to OnMessage ;)

**Comment by xhaggi** [comment]
@BigNoid, @phil65, @ronie can someone test if everything works like expected?

**Comment by BigNoid** [comment]
Doesn't work anymore with these changes on my end. Tested in home and videoinfo dialog. Keypress is registered, but oninfo action is not executed.

**Comment by xhaggi** [comment]
ok thanks will take a look at it tomorrow

**Comment by xhaggi** [comment]
@BigNoid fixed the issue you've reported. could you please do another test.

**Comment by BigNoid** [comment]
@xhaggi Now ```oninfo``` works on for instance the home screen. But ```Info``` action doesn't work anymore in media windows. In video info dialog ```Info``` closes the dialog even though the focused list has an ```oninfo``` action defined. When I tested it first time ```oninfo``` superseded the close action (useful for running extended info script on cast list for example).

**Comment by xhaggi** [comment]
> But Info action doesn't work anymore in media windows.

what does it mean?

**Comment by BigNoid** [comment]
Works now, thx.
On a sidenote, I don't think we should keep the info toggle (pressing info again closing media dialogs) if this pr is merged. We already have back that closes the dialog and info is now possibly an action in all windows/dialogs.

**Comment by phil65** [comment]
I agree with @BigNoid, I also prefer consistency when it comes to dialog handling.

**Comment by mkortstiege** [comment]
> On a sidenote, I don't think we should keep the info toggle (pressing info again closing media dialogs) if this pr is merged. We already have back that closes the dialog and info is now possibly an action in all windows/dialogs.

Veto. I am using this on a regular basis so i would cry deeply if we're going to remove the toggle close ;/

**Comment by BigNoid** [comment]
@mkortstiege powerusers can always add that action back to the keymap

**Comment by xhaggi** [comment]
it works as we only call it if there isn't a control with an oninfo and this control holds the focus.

**Comment by xhaggi** [comment]
btw if you change the keymap to <i> = close you lose the oninfo functionality completely

**Comment by phil65** [comment]
> it works as we only call it if there isn't a control with an oninfo and this control holds the focus.

if the info button closes the dialog or opens a new one depending on focus then we should change it because that really is inconsistent UX. Either we get rid of the oninfo toggle completely or we do not allow oninfo for dialogs at all. I prefer option 1).

**Comment by xhaggi** [comment]
makes sense only what to let you know how it currently works :)

**Comment by phil65** [comment]
> makes sense only what to let you know how it currently works :)

sorry, language gap, I dont get that. ;)

**Comment by xhaggi** [comment]
after thinking about the info toggle feature again, I would say leave it as it is, because if there is no control holding an oninfo it's really handy to close e.g. the DialogVideoInfo dialog with the info key. In most of the cases we don't use a control with oninfo.

**Comment by phil65** [comment]
using < oninfo > for the core infodialogs would also lead to the impression that other info dialogs invoked by scripts, or also some PVR dialogs, can also get closed by pressing < oninfo >, which is not always the case. Please let us choose the consistency route in this case.

**Comment by xhaggi** [comment]
agree to be consistent here.

**Comment by mkortstiege** [comment]
Too bad i won't be able to use oninfo in the dialogs then. I need the toggle close.

**Comment by BigNoid** [comment]
As sort of backward compatibility we could let ```oninfo``` take precedence over keymapping. That will also help the users with custom keymaps, since they most likely still have info mapped to ```back```.

**Comment by mkortstiege** [comment]
> As sort of backward compatibility we could let oninfo take precedence over keymapping. That will also help the users with custom keymaps, since they most likely still have info mapped to back.

Not possible. Since the key is mapped to some other action than `ACTION_SWOW_INFO`. In any case keymaps must be nuked before this can be considered merge-able.

**Comment by xhaggi** [comment]
@mkortstiege could you do the necessary changes to the keymaps.

**Comment by xhaggi** [comment]
and we need to do a fixup and drop the info toggle stuff from the related dialogs

**Comment by HitcherUK** [comment]
Not sure removing the toggle is a good idea either as all other 'info' dialogs (video, system, addon, album, artist, song, plus the fullscreen video and music visualiser) open and close when pressing i. This is the exact same behaviour is found on all TV remotes.
This will be a step backwards.

**Comment by phil65** [comment]
@Hitcher you cant compare that because other TV systems do not allow to open another info dialog from an info dialog itself. For Kodi that was the case too, but this PR changes it and we have to make sure that behaviour stays consistent. Try to find a TV system where the button behaviour is based on the actual focus postion. There is none, because that should never be the case.
@da-anda opinion also welcome on this one.

**Comment by da-anda** [comment]
I'm on @HitcherUK's side, we have the behavior that the triggering button of a dialog also closes it again all over the place (EPG, OSD info, OSD menu, ...) and it feels just natural. Maybe I miss the point, but why do we need `<oninfo>`inside a info dialog - does somebody have an example for this? Endless nesting of things is not good. Once an info dialog is opened, there shouldn't be a second one triggered by it. As I see it, the problem is that some skins would like to add advanced features that require this flexibility, while removing the toggle function from default keymaps will kill usability of other skins. So IMO the problem here is that the core has a too big influence on how the UI is working while it's in the domain of the skin to define it. I'd actually like to talk about changes to our skinning engine at devcon, as I have some ideas for it in regards of splitting core and UI, remove the mentioned limitation by core and what not. For the time being it might be an idea to split up keymaps, so that core does only provide defaults (main navigation and basic functionality) while skins provide their own. This will ofc kill consistency of handling between skins, but also free skins to use different navigational concepts.

**Comment by HitcherUK** [comment]
Don't get me wrong I'm in favour of skin being able to use oninfo where we never had it before (eg home screen items or custom windows) but not at the cost of losing the close action associated with pressing it again.

**Comment by BigNoid** [comment]
I can live with either. Its just inconsistent as it is now. Not every info dialog or python dialog that mimics an info dialogs works by pressing info again (for example triggering extended info from widget on home screen). We can probably add ```<oninfo>Back</oninfo>``` now to those dialogs though.
And yeah, the usecase is extended info on actor list in video info. Right now we have to pull ridiculous navigating tricks to trigger that dialog. I really want a better solution for that.

**Comment by da-anda** [comment]
Oh, I'm also not against adding the `<oninfo>`feature of this PR, this is great, but don't like the idea of getting rid of the toggle keymaps in addition to this.
Regarding extendedinfo for actors - why depend on `<oninfo>` for this? Wouldn't `<select>` also do the trick (which would actually be better anyways for limited button remotes)?

**Comment by BigNoid** [comment]
Thats already hardcoded to a builtin feature (searching for movies in db from that actor). But ideally pressing select would let the user choose what to do, search or another action invoked by a script.

**Comment by HitcherUK** [comment]
@BigNoid Could you not use a button to move the actor list and then when it's clicked the skin has control over how to proceed?

**Comment by BigNoid** [comment]
@HitcherUK Tried that already, that really isn't ideal. It messes up the focus/unfocused animations when scrolling for example.

**Comment by phil65** [comment]
What some people probably dont really realize is that if we allow oninfo in InfoDialogs then that button inherently is NOT a toggle anymore. So if it really is that bad to loose toggle functionality then we should disallow oninfo for (Info)Dialogs completely, otherwise navigation will become completely inconsistent, and from my POV consistency is one of the main things we should strive for when it comes to UX.

**Comment by da-anda** [comment]
sure, ideally things should not get nested for consistency, but that's the responsibility of the skinner / add-on dev.
About the actors, shouldn't the select action then be overrideable instead? I think we should also investigate into that direction (in a new PR ofc)

**Comment by xhaggi** [comment]
> We can probably add <oninfo>Back</oninfo> now to those dialogs though.

it makes more sense to do that in python and not in the skin file.

Okay, so what's the decision here? Leave the toggle code as it is or remove it?

**Comment by xhaggi** [comment]
I've added the info toggle to the missing dialogs (we missed only two pvr dialogs).

**Comment by da-anda** [comment]
@xhaggi I'd say keep the toggles for now. Can also be dropped later if needed.

**Comment by phil65** [comment]
Bad decision, this will introduce a lot of inconsistency all over the place. Leaving the toggles out would give skinners themselves the possibility to decide whether toggling is needed behaviour (= "free skins to use different navigational concepts.").
Anyways, since I was one of the persons who really pushed for this PR I dont want to be the one standing in the way now. Do whatever you want with it. ;)

**Comment by da-anda** [comment]
you're deeper into all this, so if you see issues with the toggles in the keymaps, drop them, I trust your judgement. (somehow can't get my head around it atm)

**Comment by phil65** [comment]
Well what I think essentially boils down to @BigNoid´s first comment triggering this discussion:

>  I don't think we should keep the info toggle (pressing info again closing media dialogs) if this pr is merged. We already have back that closes the dialog and info is now possibly an action in all windows/dialogs

If I cannot win over a majority with arguments though then I obviously failed. So if you and @HitcherUK are not convinced by the points I made and still think that this will "kill UX" or that it is a "step backwards" then I am fine with that, even if I disagree strongly.

**Comment by HitcherUK** [comment]
I'm using a Fire TV remote so I don't even have an 'info' button anymore - I was thinking more of the forum being filled with threads complaining the 'i' button no longer closes the video info dialog.
Go for it and see what the feedback is. :+1:

**Comment by phil65** [comment]
Since this seems to be controversial, I will go for it if I get an ACK from @ronie since he also has a very good overview of the bigger picture (interaction skin / script / core). I´m not in the mood to push for changes if I have the feeling that the majority does not support them.

**Comment by ronie** [comment]
sorry, i lack the time to get into this...

**Comment by da-anda** [comment]
whatever we do, we can always revert it or do follow ups. So I'd say we should merge as is (after rebase) and go form there. Futher discussion should be done in forum.

Personally I like the toggle function which is not only there for the "i" button, but also for many other OSD things etc. So if we would like to get rid of the toggle functionality, then it would have to be removed everywhere in order to be consistent again and require "back" for everything. Otoh, when doing this, one could argue that "back" in fullscreen context should mean to back out of fullscreen mode and not just hide the OSD info or menu again.
As already mentioned, it seems that we are at a point now where skins would like to have more control over the navigational concept, which is great, but on the other hand means that global keymaps for all skins won't work anymore and we need a different solution/concept. So if we really want to go that way, it will require way bigger changes to core and skins than just removing the toggles, and we should start a thread to discuss how this could/should look like. The rough concept I have in mind would allow this and also be a move towards headless and thin clients, but ofc would be a huge task.

I just started a forum thread for it: http://forum.kodi.tv/showthread.php?tid=232144

**Comment by xhaggi** [comment]
rebased ... jenkins build this please

**Comment by NedScott** [comment]
In the end most seem to want our default (Confluence) to open something with info and close that thing with info. We can do this with the toggle and we can do this without the toggle. That seems to be glossed over in this discussion. Nothing has to change in Confluence's behavior with this PR.

I think everyone got scared because it was mentioned that "back" could always be used to back out of it, but that doesn't mean it is the only way to back out of it. Not enough emphasize is being placed on the fact that the skinner can specifically enable the "info" still being able to back out whenever it makes sense.

**Comment by HitcherUK** [comment]
Good point Ned. Any control not associated with opening another info dialog just needs to add ``<oninfo>back</oninfo>`` to close the currently opened info dialog.

**Comment by phil65** [comment]
> Good point Ned. Any control not associated with opening another info dialog just needs to add <oninfo>back</oninfo> to close the currently opened info dialog.

Well if skinners want to do that, sure... Using <oninfo>back</oninfo> and <oninfo>do something else</oninfo> inside the same dialog, depending on focus position, is far from intuitive though.

**Comment by mkortstiege** [comment]
Rebased.

**Comment by phil65** [comment]
So the consensus seems to be to only do any toggling via skinning, and not via core?

**Pull request closed without merging**
