### PR TITLE
[python] deprecate thumb/icon methods and args in favour of setArt

### PR DESCRIPTION
**Pull request by tamland**
We don't need 3 different ways to set a thumb:)

### CODE REVIEW

**Comment by stefansaraev** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
still backwards compatible for now?

**Comment by mkortstiege** [comment]
I wonder if bumping the API is enough once in a merge window.

**Comment by tamland** [comment]
>I wonder if bumping the API is enough once in a merge window.

Me too..

**Comment by tamland** [comment]
@MartijnKaijser yes it's backwards compatible and I see no reason to remove it for the foreseeable future. It's mostly to make the api clearer

**Comment by MartijnKaijser** [comment]
all fine then :)
merge away

**Comment by tamland** [comment]
If no objections I'll drop the version bump since it's already been done once today.

**Comment by mkortstiege** [comment]
> If no objections I'll drop the version bump since it's already been done once today.

+1. Maybe we should add a new label `Needs Python API Bump` or the likes so we really just handle once per window?

**Comment by MartijnKaijser** [comment]
maybe once a release do a general bump. Problem is we have several API and mixing how we handle bumping the versions might create confusion. For PVR it seems almost mandatory. I could see problems for JSON-RPC between releases if we don't bump an each change. For python it usually doesn't matter as most only update at release. Same for skins.
So i'd say if we can cluster the changes in one go it's fine to do it one time. IF they are separate and we can handle them just do it each change

**Comment by MartijnKaijser** [comment]
@tamland maybe adding a lognotice/warning that it's deprecated and they should use setArt or would that spam a lot?

**Comment by tamland** [comment]
I don't think that's necessary. It's not very important that people immediately stop using this. And it will spam *a lot*, yes. For every list item plugins create

**Comment by ronie** [comment]
you need to add thumb support to setArt as well then?

**Comment by tamland** [comment]
@ronie already supported

**Pull request merged**
