### PR TITLE
[skin.estuary] Tidy up settings layout

### PR DESCRIPTION
**Pull request by Hitcher**
My OCD made me to it.

Before -

5878a4b0-7a77-11e6-990e-01c2b317b1a9

After -

1e712f48-7a78-11e6-8649-4880f9876cbf

Moved to master as requested.

@phil65 @ronie @BigNoid @da-anda @MartijnKaijser

### CODE REVIEW

**Comment by jjd-uk** [comment]
I have something up my sleeve to get rid of System Information from in there, was waiting Devcon to discuss with the others but since you're not there I can PR it as a RFC.

**Comment by ronie** [comment]
looks good to me, much better

**Comment by phil65** [comment]
yup looks better.
Another idea would be to allow better access to eventlog by putting a shortcut there.
But for now I think this here is fine.

**Comment by jjd-uk** [comment]
Before pulling this in please take a look at whether https://github.com/xbmc/xbmc/pull/10465 might be an acceptable alternative as it includes easier access for the event log.

**Comment by MartijnKaijser** [comment]
obsolete by now :)

**Pull request closed without merging**
