### PR TITLE
[Android] SDK 30 and All files access permission

### PR DESCRIPTION
**Pull request by joseluismarti**
## Description
Android 11 and higher are greatly restricting access to external storage. Apps must make use of the more privacy-friendly APIs, such as Storage Access Framework (user sees a system picker) or the Media Store (only media files from well-defined collections).
 
Android provides a special app access called `All files access` for situations that have a core use case that requires broad access of files on a device. This permission is only allowed for few apps like antivirus, file manager, etc. We've to justify the reason while publishing the app to PlayStore.

Proposed changes:

- Target to `API level 30`.

- Declare the `MANAGE_EXTERNAL_STORAGE` permission in the manifest.

- Request and check the permission at startup, using the `ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION` intent action.

Additional testing may be required, please send feedback and any further issues. 

Also identify possible regressions due to the change in the target level.

## How has this been tested?
Tested on an AFTV with Android 9, I've made some tests with files and videos and it works as usual. As expected, this permissions change should only affect devices with API level >= 30.
 
Also tested on a device running Android 11 with several types of files on the external storage and the SD card.

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [x] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Tolriq** [comment]
For the record as mentioned a few times, a media player is not a valid use case for Google Play Review team, many many apps have tried to get it and it was ALWAYS refused.
SAF allows to do everything needed so there's no reason for them to accept this unless the Team have some special contact to push.

If this road is tried, do not build too much on it as if rejected will need to be reverted. Should be backported to 19.4 and pushed to the beta group to trigger the first round of validation and rejections. (Be prepared to talk to bots for weeks)

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
Jenkins fails with:

```
08:37:41 FAILURE: Build failed with an exception.
08:37:41 
08:37:41 * What went wrong:
08:37:41 A problem was found with the configuration of task ':xbmc:processDebugResources' (type 'LinkApplicationAndroidResourcesTask').
08:37:41   - Type 'com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask' property 'androidJarInput.androidJar' specifies file '/home/jenkins/android-tools/android-sdk-linux/platforms/android-30/android.jar' which doesn't exist.
```

**Comment by Tolriq** [comment]
Someone needs to update the Jenkins image to install the SDK 30. (BTW we are already at 32, so may worth to directly install the 3 if anyone prepare the next required jump)

**Comment by joseluismarti** [comment]
Install:
<code>
./sdkmanager --sdk_root=$(pwd)/../.. "platforms;android-30"
</code>
<code>
./sdkmanager --sdk_root=$(pwd)/../.. "build-tools;30.0.2"
</code>

**Comment by mo123** [comment]
Doesn't seem to work on AndroidTV 11 devices, only Android 11 phones.
It shows the Kodi dialog in the middle of the screen with the continue button at the bottom left of the dialog.
After you press it, it says 'Permission Denied' and Kodi exits.
No apps screen is opened to grant the app the permission.

On Android 11 phones the Continue button is in the middle of the dialog message.
After you press it, Kodi loads normally.

Will test further on more devices.

**Comment by joseluismarti** [comment]
Thanks @mo123 for testing, it seems that there is no Activity on Android TV 11 to handle this Intent:

```Exception asking for permissions No Activity found to handle Intent { act=android.settings.MANAGE_APP_ALL_FILES_ACCESS_PERMISSION dat=package:org.xbmc.kodi }```

I will investigate if I can find out how to apply for this permission :(

**Comment by a1rwulf** [comment]
@joseluismarti I've seen this for other settings too.
AndroidTV does not have special app permission settings like standard Android.

**Comment by joseluismarti** [comment]
While looking for a solution to request this permission on Android TV ...

On these devices I keep the previous permission request "Allow to access photos and media", with the **limitation** in Android 11 that only displays media files on external storages.

**Comment by mo123** [comment]
I don't know if you already looked at Nova & Just Video Player, the commits they added to support Android 11 storage?
https://github.com/nova-video-player/aos-AVP/issues/336

**Comment by lrusak** [comment]
SDK-30 should be available on the android builder now.

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by joseluismarti** [comment]
I'm sorry, I got mixed up with git rebase, how do I fix it?

**Comment by garbear** [comment]
@joseluismarti The PR has a history of commits, find the last one that isn't messed up and hard-reset to it. Then, assuming the xbmc repo is called upstream, do:

```
git pull --rebase upstream/master
```

There will be some conflicts with imports (due to https://github.com/xbmc/xbmc/pull/21259) but these should be easy to fix. When the conflicts are resolved, add the files with `git add`, then continue the rebase:

```
git rebase --continue
```

You should then end up with a single commit on master. Force push to this PR and you'll be good!

**Comment by joseluismarti** [comment]
Thanks @garbear for your help I was a bit confused.

But I made a mistake and did a ```git rebase master``` and I think if I continue I will mess it up even more, it will generate new conflicts.

I think it would be better to close the PR and **be more careful with git** next time.

As this PR was to share a possible solution, if in the end it is decided to use this permission, I will **create a new PR**.

**Comment by fuzzard** [comment]
No need to close the PR. Do what you need to get it back as intended locally, then force push to the branch and PR will continue and be fine.

**Comment by lrusak** [comment]
@joseluismarti I've reverted the PR to what I believe was the latest version. Please have a look and adjust as needed. You will likely need to fetch the remote branch as you will have local conflicts if you try pushing again.

**Comment by lrusak** [comment]
jenkins build this please

**Comment by joseluismarti** [comment]
Awesome, @lrusak makes magic!

**Comment by lrusak** [comment]
> Awesome, @lrusak makes magic!

I don't typically like to do that as I think it's a good learning opportunity for people, however, I don't want to discourage people from contributing because of the high ceiling that git introduces.

You should never need to open a new PR. There is always a way to fix it. If you need help just ask and someone can walk you through it. 😊

**Comment by yol** [comment]
jenkins build this please

**Comment by fuzzard** [comment]
We have attempted a submission to the Google Play store with the MANAGE_EXTERNAL_STORAGE permission, and have been rejected. Appeal was also rejected.

Unfortunately this is not an option going forward.

**Comment by Tolriq** [comment]
Without a Google contact this was certain. The other ways are really huge rewrites (SAF+FileDescriptors are really different), IMO the way to go if you want to keep supporting Android and be able to use the improvements, is to do as more and more apps do. Manage this under a compilation flag to allow different Android builds that can do what Android can and Play Store builds to please the ... Google review team.
With Google blocking more and more things, more and more people are aware of things like FDroid and install apps from there.

**Comment by joseluismarti** [comment]
A recent merge has added the RECORD_AUDIO permission request.
Update the PR to correctly handle the request for this new permission, it was only being requested in one case.

**Comment by fuzzard** [comment]
Can you pr that change individually in another PR.

All the rest of the changes will be in https://github.com/xbmc/xbmc/pull/21427 as our workaround for store submission.
Essentially this PR with the rest of the changes just isnt viable, so split the audio perm stuff into its own pr thanks

**Comment by joseluismarti** [comment]
ok, I will add a new PR to manage the audio permission when the workaround is merged

**Pull request closed without merging**
