### PR TITLE
[osx/windowing] - fix regression introduced in 4b9126649940de22e89619…

### PR DESCRIPTION
**Pull request by Memphiz**
…cbbe8ed5d64c5411a9 - thx to fernetmenta - fixes trac #17160

@FernetMenta was able to reproduce now - now clue why i couldn't before. Works for me with this change now. Thx for giving the hint :)

### CODE REVIEW

**Comment by FernetMenta** [comment]
thanks

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
maybe also the reason why gfx co text is always at 60 fps currently

**Comment by MartijnKaijser** [comment]
Merge?

**Comment by Memphiz** [comment]
@FernetMenta - i doubt it - the regression was only there for a couple of weeks - the 60fps thingy is older iirc...

**Comment by FernetMenta** [comment]
@Memphiz I am not saying that this is the root cause but it defi itely ruined your test build.

**Pull request merged**
