### PR TITLE
[stringutils] also capitalise after punctuation characters

### PR DESCRIPTION
**Pull request by mkortstiege**
As requested in http://forum.kodi.tv/showthread.php?tid=220249&pid=1955101#pid1955101 by @HitcherUK

### CODE REVIEW

**Comment by mkortstiege** [comment]
@Paxxi, mind checking?

**Comment by Paxxi** [comment]
ran some initial tests with this https://gist.github.com/Paxxi/4d41e589495824689265#file-capitalize and it seems to work as exected, haven't tried switching around the locales yet though

**Comment by mkortstiege** [comment]
Thanks for testing. Added your tests to the PR.

**Comment by mkortstiege** [comment]
Any objections? Would like to merge this later today.

**Comment by Paxxi** [comment]
Merge it.

**Pull request merged**
