### PR TITLE
Store frame type in demux packets

### PR DESCRIPTION
**Pull request by Jalle19**
@FernetMenta

### CODE REVIEW

**Comment by FernetMenta** [comment]
this is dead code. why do you want to add this?

**Comment by Jalle19** [comment]
This way PVR addons can trim their packet buffers to the newest I-frame. We could use this in pvr.hts when trimming the packet buffer from inactive demuxers (used when predictive tuning is enabled).

**Comment by Jalle19** [comment]
Technically this can be done without changing this struct (see https://github.com/Jalle19/pvr.hts/commit/42ac4dde5001f69326a5b80d2aff271a303e12f8), but I guess it could have other uses as well.

**Comment by FernetMenta** [comment]
ok. could you add this additional info to the comment int the code?

Note that knowing the frame type may not give any advantage. Most broadcasts don't have IDR frames. You need to convey SEI recovery point info too.

**Comment by Jalle19** [comment]
I'm not even sure if my idea works, it seems faster to just keep 512 packets in the buffer than to keep just one I-frame. Coupled with the fact that all demuxing PVR addons would have to be recompiled if this header is changed I don't think it's worth it.

**Pull request closed without merging**
