### PR TITLE
Revert AML workarounds

### PR DESCRIPTION
**Pull request by FernetMenta**
this reverts most of https://github.com/xbmc/xbmc/pull/8579

AML is broken anyway and this PR reverts the workarounds that taints the code. Note that AML is completely unusable now. I will keep it for a while but if nobody picks this up, it has to be removed from master.

### CODE REVIEW

**Comment by fritsch** [comment]
I have started to hack arround the clock just4fun some days ago ... but I still hope that those that use it, will pick it up. For those interested: check my amlogic branch.

**Comment by fritsch** [comment]
@codesnake now would be the time if you already had something read ...

**Comment by codesnake** [comment]
@fritsch I already have working decoder that works the way omxplayer works for RPi. It uses HW video and HW audio decoding. And while it's performace is better than in current AML implementation, I think it is not the way it should work, because it is almost independent of Kodi's player workflow. I'm trying to rewrite it so HW video decoder will only decode the video, but Kodi will present it, as we discussed. I think in about a week or so I have something to show and try.

**Comment by fritsch** [comment]
@codesnake v17 is still work in progress - when you are ready PR is welcome.

**Comment by codesnake** [comment]
@fritsch Sure!

**Comment by stefansaraev** [comment]
you may pick (and squash) https://github.com/stefansaraev/xbmc/commit/a2b724c096e341a843fb0abd07bed283941f030d if you want. thanks @fritsch for your work.

**Comment by FernetMenta** [comment]
@stefansaraev I added your change

jenkins build this please

**Comment by fritsch** [comment]
@stefansaraev this will survive as a temporary, but as said - it's nowhere near finished and important things are missing. It was just a sunday afternoon write up ...

For the history:
- m_player_pts is the last PTS that came from player. This does not match the PTS of the frame GetPicture wants to have
- SetDropState only sets a member, the Proess() loop needs to care for this and set the pts counter via the AMLCodec appropriately

**Comment by fritsch** [comment]
@stefansaraev something else - the raw mutexes could also have gone :-)

**Comment by stefansaraev** [comment]
@fritsch I know it will be temporary, and I wanted to be as minimal as possible.

**Pull request merged**
