### PR TITLE
Make XrandR mandatory

### PR DESCRIPTION
**Pull request by MaxKellermann**
See https://github.com/xbmc/xbmc/pull/7058

### CODE REVIEW

**Comment by FernetMenta** [comment]
the xrandr changes look good, thanks!

**Comment by MartijnKaijser** [comment]
jenkins build this please
any objections on merging this?

**Comment by MartijnKaijser** [comment]
@MaxKellermann 
it failed to build http://jenkins.kodi.tv/job/LINUX-64/4234/console

**Comment by MaxKellermann** [comment]
Does the build machine have the xrandr development files installed? Previously, that was not mandatory, which is the point of this patch.

**Comment by wsnipex** [comment]
we build with unified depends, which do not include X stuff. The rather fugly workaround is to symlink stuff from system dirs. see https://github.com/xbmc/xbmc/blob/master/tools/depends/target/Makefile#L125
xrandr and randrproto needs to be added there.

**Comment by MaxKellermann** [comment]
Rebased & pkg-config links added. Please reevaluate.

**Comment by wsnipex** [comment]
thanks, jenkins build this please

**Comment by MaxKellermann** [comment]
So this has failed again, but I have no idea why. There aren't any details in the build log. Maybe somebody else with some idea how these symlink kludges work could check it out?

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
now it works, ignore the failed addons

**Comment by wsnipex** [comment]
@Memphiz ping for the apple specific configure simplifications

**Comment by Memphiz** [comment]
@wsnipex those look fine

**Pull request merged**
