### PR TITLE
[music] Support originaldate / originalyear tags

### PR DESCRIPTION
**Pull request by mbarnes**
## Description
The [MusicBrainz Picard](https://picard.musicbrainz.org/) application places the release date of an album in its `date` tag. But a given album can have several releases over the years and most users expect to see the *original* release date of an album, which Picard places in its `originaldate` tag.

See: https://picard.musicbrainz.org/docs/mappings/

For example, a 1994 re-release of Led Zeppelin IV:
```
$ metaflac --export-tags-to - "1 - Black Dog.flac" | sort
...
DATE=1994-07-19
...
ORIGINALDATE=1971-11-08
ORIGINALYEAR=1971
```
Parse various tag formats for the *original* release date or year and prefer that over the release date, when updating the music database.

To see the changes take effect, users will need to touch all music files and then rebuild the music library.

## How Has This Been Tested?
Built Kodi locally on Linux/x86_64, tested changes against various **.flac** and **.ogg** files in my personal library, relied on [Picard documentation](https://picard.musicbrainz.org/docs/mappings/) for the rest.

## Screenshots
**Before** (re-release year shown)
before-screenshot

**After** (original year shown)
after-screenshot

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by mbarnes** [comment]
Note: I noticed Kodi mishandles "date" tags in various formats by trying to convert what are supposed to be [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) strings into integers with `atoi()`.

Since all Kodi seems to care about at present is the year, this method *happens* to work since the year is specified first in a release date string.  But since it's not *technically* correct I didn't want repeat that for "original date" tags in some formats (`TDOR` in ID3v2, for example), so I skipped them.

I had intended to revisit that issue in a separate PR, but if you'd prefer I can use the `atoi()` method for those skipped tags here.

**Comment by DaveTBlake** [comment]
Welcome Matthew, thank you for contributing to Kodi and for taking an interest in the music library in particular. 

The way date tags are handled by Kodi is something that has been discussed on the forum https://forum.kodi.tv/showthread.php?tid=313952. I have wanted to improve this for some time, as part of my ongoing plan to make use of more tag data. Unfortuntely having started to implement it my work to handle all the date tags in all the file formats has been delayed by other priorities. Perhaps you have seen it listed here https://forum.kodi.tv/showthread.php?tid=310778&pid=2558589#pid2558589 as "work in progress". 

What you have done here looks fine as far as it goes, but is limited:
a) it only includes some tags formats (not ID3 and mp3 files are very common). I would also like to see Kodi handle RELEASEDATE tag, and TDOR, TDRC and TDRL (the ID3v2.4) tags, and  process the full date from the ID3v2.3 tags
b) it forces users to use original date when present.  Many may prefer that, but it would be better to give users the choice.
c) also need to consider the ffmpeg tag factory (used rather than Taglib to read ID3 tags from some format of music files) 

You mention doing another PR, so I take that as a sign that maybe you are interested in doing more work on Kodi.  I would certainly be happy to collaborate on music library improvements.  Perhaps you would take a look at what I started dong for dates, in my repo https://github.com/DaveTBlake/xbmc/tree/OrigDateTags but does need rebasing and was far from complete.

Now the forum is back I would also be happy to discuss a best way forwards with date tags with you in greater detail there where more people can see it. Do start a thread in Music Support https://forum.kodi.tv/forumdisplay.php?fid=263

**Comment by DaveTBlake** [comment]
>To see the changes take effect, users will need to touch all music files and then rebuild the music library.

Also since #11557 there is a much easier way to see the effects than that by adding <promptfulltagscan>true</promptfulltagscan> to the <musiclibrary> section of advancesettings.xml. This will in turn be replaced by a UI change in a later PR

**Comment by mbarnes** [comment]
Hi @DaveTBlake,

> Perhaps you would take a look at what I started dong for dates, in my repo https://github.com/DaveTBlake/xbmc/tree/OrigDateTags but does need rebasing and was far from complete.

I took a look at your branch and found it rebases cleanly to the current `master` branch, and also made a couple small corrections.

https://github.com/mbarnes/xbmc/commits/OrigDateTags

You say it's far from complete, and I *am* starting to see some bits and pieces that need completed.  `Album.cpp` is missing some of the changes you made to `Song.cpp`, for example.  Nor does there appear to be any change in the UI yet, which is primarily what I'm after.  But there doesn't seem to be an overwhelming amount of work left to complete.

Perhaps you can elaborate on what else you had in mind for that branch, and I can attempt to continue it in a new pull request.  (That seems a more appropriate place to discuss code details than the forum, and I prefer GitHub's markdown syntax, frankly.)

**Comment by jjd-uk** [comment]
The problem is that if you do a PR to the XBMC repo and then it's used for a lengthy discussion, every Kodi dev will get a notification for every message which for some dev's quickly becomes annoying.

If you wish to use Github (rather than forum) to discuss code and collaborate then I'd suggest you PR to Dave's repo initially (assuming Dave is ok with that), then when it's at a final enough state for the wider Team Kodi dev review then it can be PR'd here.

**Comment by DaveTBlake** [comment]
Good suggestion @jjd-uk so I have PR my repo https://github.com/DaveTBlake/xbmc/pull/7, see you there @mbarnes

**Comment by phunkyfish** [comment]
PR closed as it appears to be obsolete. 

If the author would like it kept open please just request so on the PR. If you feel there is still merit in merging this PR you can request the label be changed to `PR Cleanup: Backburner`.

**Comment by DaveTBlake** [comment]
Superceded by https://github.com/xbmc/xbmc/pull/17437

**Pull request closed without merging**
