### PR TITLE
Fix audiobook directory for mka albums

### PR DESCRIPTION
**Pull request by the-black-eagle**
## Description
The end time of the last track in an MKA file is calculated incorrectly from `m_fctx->streams[0]->duration`.  Although this works for m4b files (MPEG-4 audiobook, generally used by Apple), it doesn't work for mka files which need the duration of the entire file `m_fctx->duration`.  This only affects the last track.  If the last track end time is zero or less, the track cannot be selected or played, it cannot be scanned into the music library and it gets named incorrectly.

Whilst looking at this I also noticed that in files view it's impossible to start playback at any track other than the first. 

## Motivation and context
Fixes an issue reported here -> https://forum.kodi.tv/showthread.php?tid=378468

The first commit fixes mka files not displaying correctly by checking if `item->GetEndOffset()` is a valid value for the last track and using either the value from the stream or the value from the file as appropriate.

The second commit fixes the playback issue in files view. The problem occurs because once the playlist is created, the logic compares the file path of the selected item to the items in the playlist.  With an mka or m4b file, all the tracks are in one file so the first track in the playlist always matches. This is fixed by comparing track and disk numbers instead for audiobook related files.

## How has this been tested?
Tested by navigating to mka albums and m4b audiobooks in files view.  Also tested scanning the same items into a fresh library.  With these fixes in place, everything works as expected.

## What is the effect on users?

Users will be able to play and scan in the last track of an mka album.  When in files view, users will be able to start playback from the correctly selected track for both mka albums and m4b audiobooks.

## Screenshots (if appropriate):
Last track is displayed first, can't be played.

Screenshot from 2024-08-18 06-39-29
 After fix.

Screenshot from 2024-08-20 08-58-40

Before fix, trying to play track 4 results in track 1 playing.
Screenshot from 2024-08-20 09-01-24

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by HomerJau** [comment]
Can this also be merged into the Omega branch along with other related merges please?

**Comment by garbear** [comment]
The change here looks very much like a fix, so I'll add it as a candidate for backport.

**Comment by VonMagnum** [comment]
Can we possibly get this backported into a KODI V20.1 nightly soon?  I'd very much like to have proper MKA selection in the current Omega stable version 20.1.  I'm the one that originally reported the problem that the-black-eagle fixed.  It's been broken for several months and showed up when Google Play suddenly did an automatic update from Nexus (which I thought I had disabled). I'm not really sure how to do a pull request, not being much of a programmer since my days building Visual Pinball VPinMame tables with scripting in MS Visual Basic.

**Comment by garbear** [comment]
@the-black-eagle Can you open the backport?

**Comment by neo1973** [comment]
@the-black-eagle: With 21.2 on the horizon, could you make a backport please?

**Comment by VonMagnum** [comment]
It's in the regular "master" nightly build (someone pointed me to it on the main forum). 

See: https://mirrors.kodi.tv/nightlies/android/arm64-v8a/master/

PA Player is now gapless with MKA as well. The only issue I see left is some (not all) MKA albums have a nonsensical track length for the final track. Since it's not wrong on all MKA albums, I would guess there's an invalid calculation if some sort for certain values, but I know not what.

**Comment by the-black-eagle** [comment]
> Since it's not wrong on all MKA albums, I would guess there's an invalid calculation if some sort for certain values, but I know not what.

Possibly its because of a missing `CUtil::ConvertSecsToMilliSecs()` for the value of compare.  That _should_ only be required for m4b files but I guess it could possibly affect mka files too.  All my test mka stuff is fine so I'd need a problematic file to check with to be 100% sure.

Regardless, that bit of code does need fixing as the last file of an m4b shows either an incorrect or non-existent length and will need backporting too, so I'll do a PR for the fix and then a backport PR against Omega.  Note that the GUIMediaWindow stuff does not need backporting as it only got broken in master.

**Comment by the-black-eagle** [comment]
@HomerJau , @VonMagnum   FYI, there is a backport to Omega at https://github.com/xbmc/xbmc/pull/26146

**Pull request merged**
