### PR TITLE
[strings] Reword remove movie from library

### LINKED ISSUE #24468: Reword Remove Movie from Library message when deleting Versions
### Describe the bug
Reword the "Remove movie from library" message when deleting versions.

I believe most users would expect the highlighted movie to be deleted rather than the entire Version collection. 
Adding the wording  "... and all its versions..." should make it clearer. See image below

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Possible Fix

VideoVersionDelete

### To Reproduce

1. 
2.
3.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by DaVukovic**
Just want to contribute a low hanging fruit:

#24468 

Description is already mentioned at the issue

### CODE REVIEW

**Comment by CrystalP** [comment]
Maybe I'm being picky, but I think the updated message should appear only for movies that have more than one version (easy to test with the tag's HasVideoVersions())
Only one version: current message is perfectly fine.

**Comment by DaVukovic** [comment]
So you mean, we might need to have a condition which checks if the specific item in the library does have multiple version and only if that's the case and one wants to remove that item from the library, then display this message?

If so, then we should simply create a new string and use that instead.

I'm totally fine with that. Even if that would mean we should close this PR and create a new one which also includes the condition. 

Might have to be done by someone else then, because I'm not familar with the "multi-version-video"-code

**Comment by CrystalP** [comment]
I mean continue using the current message for single version movies, and the new proposed message for multi-versions (a new string in the strings.po, yes).
See my first comment for the way to test for single or multi-version, let me know if that's not clear enough.
It's ok to continue on this PR, you can force-push to overwrite your original commit.

**Comment by DaVukovic** [comment]
New string added and conditions made to check if an item has multiple versions. 

Thanks for the help :+1:

**Review by CrystalP — APPROVED** [review]
Good for me, after formatting is taken care of + green build

**Comment by DaVukovic** [comment]
Fixed formatting. 

I'm not too sure, if the failed build is related to this PR. From a first look, I would say it's not related. 

If I'm mistaken, please let me know

**Comment by CrystalP** [comment]
Jenkins please build this

**Comment by CrystalP** [comment]
Jenkins please build this

**Comment by CrystalP** [comment]
For some reason this one keeps failing in Android builds... If this fails again, if you don't mind I could cherry-pick the commit into #24591, looks like I'll add another change to it anyway. Maybe it'd go green there.

**Comment by CrystalP** [comment]
Jenkins build this please

**Comment by DaVukovic** [comment]
Sorry for being not responsive. Work kept me busy in the last days.

**Pull request merged**
