### PR TITLE
[databse] Get rid of unnecessary .c_str() calls

### PR DESCRIPTION
**Pull request by Paxxi**
Remove .c_str() when calling exec and query as they take a const std::string&

### CODE REVIEW

**Comment by Paxxi** [comment]
jenkins build and merge this please

**Comment by MartijnKaijser** [comment]
@Paxxi good timing ;) Needs a rebase

**Comment by Paxxi** [comment]
jenkins build and merge this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
