### PR TITLE
[video] re-scrape season art for newly added seasons

### PR DESCRIPTION
**Pull request by mkortstiege**
This fixes the stale season artwork bug in case new artwork becomes available after initial scrape by adding a `GetArtwork()` function to the scraper, allowing us to re-fetch the art URLs for a particular item. 

It is triggered whenever a missing season art is detected after adding new episodes. Lookups are done via the unique identifier `m_strIMDBNumber' within the video info tag. It uses the scraper cache where possible to avoid another API hits.

Note:
This has to go in after the scraper changes (https://github.com/xbmc/repo-scrapers/pull/4). Once merged `metadata.tvdb.com` and `metadata.tvshows.themoviedb.org` (already chaining via GetArt) will support this. Others have to adopt this and move the actual artwork fetches to a `GetArt` chain. There's no change in behavior in case the scraper does not support this.

This is entirely based on @jmarshallnz work in PR https://github.com/xbmc/xbmc/pull/3546 and just slightly modified.

@Montellese for review please

### CODE REVIEW

**Comment by mkortstiege** [comment]
jenkins build this please in case @opdenkamp left a slot open  ;)

**Comment by mkortstiege** [comment]
Apart from the pretty limited use case as of now (could be extended to fetch other updates) this fixes a long standing issue. I really want this years old bugger in `Isengard`. Objections?

**Comment by mkortstiege** [comment]
Will merge in 24h in case there are no objections.

**Comment by Montellese** [comment]
Is it possible that we fetch artwork for all seasons (because a new one was added) and the new set of artwork doesn't contain the one we are currently using for an existing season and what would be the consequences?

**Comment by mkortstiege** [comment]
No, existing season artwork won't be replaced. This is already handled in `CVideoInfoScanner::GetSeasonThumbs()`.

**Comment by mkortstiege** [comment]
Updated and rebased. @Montellese, I've not added a explicit check for `CXBMCTinyXML::Parse()` because i think that's exactly what the `if (!doc.RootElement())` block is for.

**Comment by Montellese** [comment]
@mkortstiege: Well I think you could drop the check for `doc.RootElement()` if you add the check for `CXBMCTinyXML::Parse()`. But personally I still think checking both is the safest way because it doesn't rely on any assumptions (which might change) on the behaviour of tinyxml or our wrapper.

**Comment by mkortstiege** [comment]
@Montellese you're ok with https://github.com/mkortstiege/xbmc/commit/9c1fc1b387e34f6ecb5920e2798763944c4224a3?

**Comment by mkortstiege** [comment]
Removed last one again. IMO it's enough to check for `RootElement` like we do everywhere else.

**Comment by mkortstiege** [comment]
How to proceed here?

**Comment by Montellese** [comment]
Does/Can this break existing scrapers that support artwork?

**Comment by mkortstiege** [comment]
> Does/Can this break existing scrapers that support artwork?

Nope. The new `GetArtwork()` function is not used If not called explicitly from the infoscanner. As for the normal meta fetch run nothing will change.

**Comment by mkortstiege** [comment]
jenkins build this please

**Comment by mkortstiege** [comment]
@Montellese ok to merge as is? I really want this bugger fixed in v15.

**Comment by Montellese** [comment]
If it's backwards comaptible with existing scrapers I have no objections.

**Comment by mkortstiege** [comment]
> If it's backwards comaptible with existing scrapers I have no objections.
Great. Existing scrapers won't be able to re-fetch season art but remain 100% usable for regular scraping. Will rebase and push this and the scraper change in later today.

**Comment by mkortstiege** [comment]
jenkins build and merge

**Pull request merged**
