### PR TITLE
[guilib][vfs][imagecache] Load video chapter images into texture cache when viewed, like standard images

### LINKED ISSUE #23765: Image caching is not working correctly in latest 21.0a3
### Describe the bug

Kodi (with [PlexKodiConnect](https://github.com/croneter/PlexKodiConnect), I think this might be important due to the way it fetches art?) is basically constantly refetching art and images and never hitting the cache. I "think" that basically nothing is getting into the cache.

I suspect related to the chain of changes related to https://github.com/xbmc/xbmc/pull/23567 or https://github.com/xbmc/xbmc/pull/23134 but am unsure if all art is impacted by this or just generated thumbnails. If this is totally wrong/unrelated I will edit and remove this to avoid confusion

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

1. Open Movies or TV shows wall view
2. All images slowly pop in one at a time
3. Navigate back to Home screen
4. Re-open movies or tv shows wall view
5. All images pop in quickly because they have not changed and are in the cache

## Actual Behavior

1. Open Movies or TV shows wall view
2. All images slowly pop in one at a time
3. Navigate back to Home screen
4. Re-open movies or tv shows wall view
5. All images slowly pop in one at a time

### To Reproduce

See above

### Debuglog

N/A yet

### Screenshots
Here are some links or screenshots to help explain the problem:

N/A yet

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A yet

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Kodi version: 21.0a3 (this did not happen to me in 21.0a2 I don't think). I have reverted to 20.2 and the problem goes away

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by rmrector**
## Description
Use the new interface from #23197 to load generated chapter thumbs into the texture cache.

Image paths are still the same `chapter://nfs://xxxxx/yyyyy.mkv/2` - changing to a proper image URL would move them around in the texture cache, which I don't want to do yet.

This has a commit that fixes behavior in #23567 that does affect other special images - new generated images weren't saved to the DB.

I have prepared a branch for the last special image, PVR channel groups, but it sits on top of this one. [pvr-group-thumb-gen](https://github.com/rmrector/xbmc/tree/pvr-group-thumb-gen)

## Motivation and context
Consistent behavior:

- all images load the same way, whether they are already cached or not.
- Remote interfaces can show these images even if they haven't been viewed in Kodi GUI yet.
- Kodi doesn't have to pre-cache a potentially massive list of images when browsing folders, just in case they are viewed, saving both storage size in the cache and taking queue time for images actually displayed in the GUI.
- These special images can now be preloaded the same as other images.

Easier maintenance and development: this provides a clear interface to load more special images, which avoids the complication of designing and developing a way to preload some types of artwork.

## How has this been tested?
Real quick on Windows for now. Started dogfooding with N2.

## What is the effect on users?
None.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by thexai** [comment]
Runtime tested on Shield and this definitively restores normal thumbnails cache performance

**Comment by stumpalump** [comment]
Tested on Win11 and fixed thumbnail cache performance

**Review by thexai — APPROVED** [review]
Runtime tested for some days in Shield and no issues found.

**Comment by stumpalump** [comment]
@thexai have you noticed any problems with scanning video library after this one?

**Comment by thexai** [comment]
no

**Review by howie-f — APPROVED** [review]
haven't spotted any regression so far

**Comment by rmrector** [comment]
thanks

**Pull request merged**
