### PR TITLE
Revert "[Android] Clean exit from android_main(). Do not call exit(0)."

### LINKED ISSUE #21439: [Kodi20] Subtitles not showing after kodi restarts on android devices since recent update
### Describe the bug
Here is a clear and concise description of what the problem is:

Subtitles(smi and srt type I tested) not visible after restart kodi on android devices.
I should kill kodi app(force stop) before launch kodi to show the subtitles.
I think this is related to the recent update.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Subtitles should be showing.

## Actual Behavior

Subtitles not showing after restart.

### To Reproduce

1. Exit kodi on android devices.
2. Just run kodi again. (Do not kill kodi app before run kodi)
3. Check if subtitles visible.

tested on amazon fire stick tv 4k max and nvidia shield tv pro.

### Debuglog

The debuglog can be found here:
https://github.com/xbmc/xbmc/issues/21439#issuecomment-1134516156

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: android 9 , 11
 - Kodi version: Kodi 20 Nexus

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by thexai**
## Description
This reverts commit 086ea08740bdf8427c7ee590425f462ab701c92a.

Fixes https://github.com/xbmc/xbmc/issues/21439

## Motivation and context
I think it's clear that this commit has caused different issues and regressions. In the case the subtitles are double confirmed by different people.

Nobody likes to revert commits but this is not a reason to leave things broken longer than necessary.

For now, only this commit is reverted until we have more time to investigate the rest of the issues.

## How has this been tested?
Runtime tested Shield Pro 2019

## What is the effect on users?
Fixes https://github.com/xbmc/xbmc/issues/21439

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ksooo** [comment]
I would like to spend some more time into trying to fix the subtitles issue.

**Comment by thexai** [comment]
It's your decision and I respect it. Note that you can still do it with master branch fixed and allow Alpha2 to continue to be released in a more stable way.

**Comment by ksooo** [comment]
@thexai I'm in good hope that we find root cause and fix for both the subtitles and the stuttering issue in a timely manner. There is really no rush with Alpha 2 release, imo.

**Comment by thexai** [comment]
Those broken things are just a consequence of things related to timing and synchronization being broken by reusing `kodilib.so`.

So my point of view is that "fixing" those two things (discovered by chance) is not going to fix the root problem.

**Comment by ksooo** [comment]
> So my point of view is that "fixing" those two things (discovered by chance) is not going to fix the root problem.

 Reverting the exit(0) removal is a work around. Root cause and thus subject to fix is making libkodi.so reusable.

**Comment by ksooo** [comment]
For the records, all fixes needed for this so far were removing global static instances, which is a broken pattern anyway and subject to fix anyway. The Android "drama" helps to find and fix all those broken code pieces.

**Review by ksooo — APPROVED** [review]

**Pull request merged**
