### PR TITLE
[addons] recently updated directory

### PR DESCRIPTION
**Pull request by tamland**
This adds a new directory for showing the most recently installed updates. Useful if you have auto updates on and want to see what has updated/check the changelogs.

It also flips notifications to off by default. I don't find it very useful anymore as you can simply go to the addon browser instead if you want to know what has updated.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
With a always online kodi install you wont see notification anyway :) 
Thx

**Comment by tamland** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
@tamland this also turns of notifications for manual installed addons from repo/.zip so you have no idea if it worked or not. Perhaps do show for those cases and default off for auto updates only?

**Comment by MartijnKaijser** [comment]
@tamland can we make it sort descending by default? Now it's sorts from old to new and i'd say recent updated should always sort by newest first

**Pull request merged**
