### PR TITLE
[darwin] debugging doesn't work in Xcode with -Og flag

### PR DESCRIPTION
**Pull request by Rechi**
## Description
don't add `-Og` flag on darwin, source level debugging doesn't work with it in Xcode

## Motivation and Context
@ksooo told me

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by Rechi** [comment]
@wsnipex I know darwin isn't your area, but general change is okay?

**Comment by wsnipex** [comment]
you can make the compile_if_else above conditional on != darwin to save the useless check

**Comment by Rechi** [comment]
@wsnipex updated

**Review by wsnipex — APPROVED** [review]

**Comment by Rechi** [comment]
jenkins build and merge

**Comment by ksooo** [comment]
Thanks guys.

**Pull request merged**
