### PR TITLE
[GUI] Hide OSD close button

### PR DESCRIPTION
**Pull request by Hitcher**
when disabling mouse input

Reported on the forums -

http://forum.kodi.tv/showthread.php?tid=261042

@ronie @phil65 @da-anda

### CODE REVIEW

**Comment by ronie** [comment]
looks ok to me

**Comment by phil65** [comment]
yup.

**Comment by da-anda** [comment]
IIRC @JezzX kept it on purpose as the button can also be accessed via remote. I think I reported this to him and he said something like "users got lost and didn't know how to exit fullscreen playback". And I think we have everywhere a visible "back" button atm.

Personally I'm fine with getting rid of it if mouse is disabled. Just thought I'd mention.

**Comment by un1versal** [comment]
@HitcherUK please see forum thread for discussion.

**Pull request merged**
