### PR TITLE
[Android] Fix wake-up when sleeping with active hdmi

### LINKED ISSUE #24950: [kodi 21][androidtv]Cant play anything after wakeup
### Describe the bug
Using kodi on chromecast 4k, shutdown via android remote,  then turn on. Kodi will open with blue circle animation stuck, and only work after exit and reopen.

## Expected Behavior
Kodi should work normaly without the need to reopen.

## Actual Behavior

Kodi only works after reopen.

### To Reproduce

Using kodi on chromecast 4k, shutdown via android remote,  then turn on. Kodi will open with blue circle animation stuck, and only work after exit and reopen.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/wicagojovu ,this one is a clean install without anything but kodi log uploader
https://paste.kodi.tv/wemihamima  , this one too..

https://paste.kodi.tv/wahavucape
https://paste.kodi.tv/akurecegup
https://paste.kodi.tv/qikekacica

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 12
 - Kodi version: 21 stable

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by hugbug**
## Description

Improved logic for wake-up handling. If hdmi-unplugged-event was received after screen-off-event, we wait for hdmi-plugged-event before calling of wake-up routine. If hdmi remained active during sleep, the wake-up routine is executed directly after receiving of screen-on event (do not wait for hdmi event, which never comes in that case).

Fixes #24950.

## Motivation and context

In #24632 the call to wake-up routine was moved from event ACTION_SCREEN_ON to ACTION_HDMI_AUDIO_PLUG. That solved issue with sleep/wake-up on Fire TV.

An extra pre-caution was made for systems not supporting ACTION_HDMI_AUDIO_PLUG: on these systems the wake-up routine is executed in ACTION_SCREEN_ON as it was in older versions.

Despite of the pre-caution the change has introduced an issue on Chromecast 4k (#24950). The analysis pointed out to a behavior which we didn't take into account. The device does support ACTION_HDMI_AUDIO_PLUG and sends this event on app start but doesn't send the event when going into sleep or on wake-up. That confuses our code and prevents the wake-up routine from being executed.

### Improvement
Instead of using first incoming event ACTION_HDMI_AUDIO_PLUG as a criteria for decision when to call wake-up routine, we now doing it in a more smarter way:
- if after event ACTION_SCREEN_OFF we received event ACTION_HDMI_AUDIO_PLUG (with status "unplugged"), then during wake-up we wait for ACTION_HDMI_AUDIO_PLUG (with status "plugged").
- if event ACTION_SCREEN_OFF wasn't followed by ACTION_HDMI_AUDIO_PLUG (with status "unplugged"), then the wake-up routine is executed immediately after receiving ACTION_SCREEN_ON.

### Test 1: Fire TV
Test case to ensure the sleep/wake-up still work without issues on Fire TV (test steps copied from #24632):

Fire TV Stick 4K Max 2nd gen, connected to AVR Denon AVC-X4800H, connected to TV LG C1. Fire TV is configured to stop outputting signal on sleep. Fire TV and Kodi are configured to output all audio formats as passthrough, using Kodi IEC packer. HDMI-passthrough and HDMI-Control (CEC) are disabled on AVR.

1. Start Kodi.
2. Make sure audio passthrough is configured in Kodi settings, using Kodi IEC packer.
3. Playback a video with multichannel audio such as Dolby Digital or DTS, check on 4. AVR that the incoming signal is correct.
5. Stop video playback.
6. Switch off all devices using on/off button on Fire TV remote. If Fire TV is properly configured the AVR and TV will both switch off.
7. Wait a few seconds for sleep mode to activate.
8. Press on/off button on Fire TV remote to wake up Fire TV and switch on AVR and TV.
9. Kodi should be active.
10. Try to playback the same video.
11. Check incoming signal on AVR.
12. Go to Audio settings in Kodi. Check that Kodi IEC packer is still selected as audio passthrough device.
#### Test results
On step 10 AVR shows the same input signal as on step 3. On step 11 "Kodi IEC packer" is in the list of audio devices and it is selected as output device. Audio passthrough works correctly.

### Test 2: Chromecast 4K
@diogosena, who has reported the problem, confirmed the PR has fixed the issue for him: https://github.com/xbmc/xbmc/issues/24950#issuecomment-2046138560. 

## What is the effect on users?

Sleep/wake-up should now work correctly on Chromecast 4K.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by fritsch — APPROVED** [review]
Thanks - I feared something like that in original PR - as one cannot really rely on "proper behaving" devices. Therefore being more robust is the way to go.

**Review by thexai — APPROVED** [review]
Tested on Shield 👍

**Comment by hugbug** [comment]
Thanks.

Should I create a backport-PR for Omega-branch?

**Comment by fritsch** [comment]
Yes, please. Thanks in advance.

**Pull request merged**
