### PR TITLE
kodi-config.cmake: use CMAKE_FIND_ROOT_PATH to fix cross-compilation

### PR DESCRIPTION
**Pull request by bkuhls**
When cross-compiling, the location at build time of the libraries is
not the same as the one at run-time. The CMAKE_FIND_ROOT_PATH variable
is here to handle this difference, so use it in kodi-config.cmake.

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
(rebased and simplified for Kodi 17.0-Krypton)
Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
(rebased for Kodi 19.0-Matrix)

This patch is used in buildroot since 2015:
https://git.buildroot.net/buildroot/log/package/kodi/0004-kodi-config.cmake-use-CMAKE_FIND_ROOT_PATH-to-fix-cr.patch

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X]  I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by lrusak — APPROVED** [review]

**Review by garbear — APPROVED** [review]
Change looks correct, and that it's been needed for so long is a good sign

**Review by wsnipex — CHANGES_REQUESTED** [review]
This isn't correct for non cross builds. Either make the change for cross compiling only, or better yet, just override needed vars when building

**Comment by bkuhls** [comment]
> This isn't correct for non cross builds. Either make the change for cross compiling only, or better yet, just override needed vars when building

Added "if(CMAKE_CROSSCOMPILING)". Buildroot maintainers prefer this solution because "This will also avoid having to pass -DCMAKE_MODULE_PATH to all Kodi add-ons .mk files."
http://lists.busybox.net/pipermail/buildroot/2015-July/135025.html

**Comment by lrusak** [comment]
@bkuhls did you test using `CMAKE_FIND_ROOT_PATH` in a non cross compile environment? Is there any negative effects?

**Comment by bkuhls** [comment]
> @bkuhls did you test using `CMAKE_FIND_ROOT_PATH` in a non cross compile environment? 

No, not yet, never did a native kodi build before ;) Will test it in the next days...

**Comment by bkuhls** [comment]
> @bkuhls did you test using `CMAKE_FIND_ROOT_PATH` in a non cross compile environment? Is there any negative effects?

Tested a native build with the original version of the patch, i.e. without "if(CMAKE_CROSSCOMPILING)", for Kodi and pvr.hts master branch and it works so I pushed that patch again to this PR.
Afaics CMAKE_FIND_ROOT_PATH is unset on Debian so adding the variable to KodiConfig.cmake should not have an effect on the paths calculated. Buildroot on the contrary does set CMAKE_FIND_ROOT_PATH in https://git.buildroot.net/buildroot/tree/support/misc/toolchainfile.cmake.in#n56 for cross compiling.

**Comment by DaveTBlake** [comment]
@wsnipex what is your view of this now?
Has been lurking since Jun (sorry @bkuhls), still appropriate or superseded? Would like to make a definitive decision rather than just bumping milestones

**Comment by DaveTBlake** [comment]
Still some concerns that this may break in some corner cases, but nothing definite. Hence merging this in while still in alpha so can get wider testing

**Pull request merged**
