### PR TITLE
[subs] Some improvements and a fix for subs in archives

### PR DESCRIPTION
**Pull request by ace20022**

### CODE REVIEW

**Comment by ace20022** [comment]
Diff without cosmetics: https://github.com/xbmc/xbmc/pull/7285/files?w=1

**Comment by mkortstiege** [comment]
Not sure about dropping `URIUtils::CreateArchivePath` for zips. Is this intended? Other than that it looks good to me.

OT: I really question why we're supporting archive in archive subs ;) This is such a silly idea ..

**Comment by ace20022** [comment]
As far as I’m concerned, we could remove support for archived items completely.

**Comment by ace20022** [comment]
> Not sure about dropping URIUtils::CreateArchivePath for zips. Is this intended?

That is the mentioned fix.

**Comment by ace20022** [comment]
jenkins build this please

@MartijnKaijser 15.0?

**Comment by mkortstiege** [comment]
I see no reason to test this weird scenario. jenkins build this please.

**Comment by MartijnKaijser** [comment]
if you guys think it's safe enough.

**Pull request merged**
