### PR TITLE
[Estuary] Fix OSD Button Visibility

### PR DESCRIPTION
**Pull request by jjd-uk**
## Description
Fix - Inconsistant OSD button visibility between Live TV and Live Radio
Fix - Do not show non-functioning Rewind/Fast Forward buttons

### PVR OSD Buttons

@phunkyfish reported inconsistant button visility between Live TV and Live Radio. I wasn't able to exactly replicate what phunkyfish said he was seeing for Radio, however I've made sure that the visibility conditions for the buttons in MusicOSD.xml for Radio are now aligned as close as possible to the buttons in the correctly functioning VideoOSD.xml for Live TV.

**Live TV in timeshift**
**Previous** & **Next** buttons for navigating Timeshift buffer.
image

**Radio in timeshift before**
No **Previous** & **Next** buttons for navigating Timeshift buffer.
image

**Fixed - Radio in timeshift after**
**Next** button now visible. Using PVR.HTS with tvheadend backend I could never get **Previous** button displayed as **Player.SeekEnabled** for Radio appears to never be true (while it can be true for LiveTV) in my test setup.
image

### Rewind / Fast Forward Buttons

The player actions **PlayerControl(Rewind)** and **PlayerControl(Forward)** do not do anything when video is **Paused**. Reported on forum at https://forum.kodi.tv/showthread.php?tid=361875 and confirmed on my local setup.

**Before**
image

**After**
Hide Rewind / Fast Forward when Paused
image

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by jjd-uk** [comment]
As it affects buttons shown for PVR a ping also to @ksooo

**Comment by phunkyfish** [comment]
Thanks @jjd-uk I’ll test this later today.

**Review by phunkyfish — APPROVED** [review]
Tested and fixes the issue my side. Thanks

**Comment by jjd-uk** [comment]
@ronie ok with you?

**Comment by ronie** [comment]
i'm not able to test as i don't have a proper pvr setup, so if @phunkyfish is happy, i'm fine with it.

**Pull request merged**
