### PR TITLE
[pvr] revert re-init of PVR manager on wake

### PR DESCRIPTION
**Pull request by xhaggi**
Revert the re-init of the PVR manager on wake up introduced by #5824

### CODE REVIEW

**Comment by mcaptur** [comment]
This is creating a problem on Pi when using virtual suspend.. when pi come out of suspend kodi freezes. see http://forum.kodi.tv/showthread.php?tid=211501&pid=1877115#pid1877115

**Comment by opdenkamp** [comment]
i don't see anything freezing in that log you linked, just a lot of omxplayer spam?
please create a ticket on trac for this and link a debug log and steps to reproduce.

however, i doubt that it's got anything to do with this, since this has been the default behaviour of this code for ages, and iirc @popcornmix 's explanation of virtual suspend correctly, it's not even a real suspend.

**Comment by mcaptur** [comment]
ok thanks will do. I can repeat it at will  on 2 pi s with vu+ and tvheadend addon with any build with this code added - milhouse builds from 1st december onwards.

Did some further tests 

1) disabled vu+ addon just tvheadend addon with 7 channels enable
issue repeats itself

2) cleared  <iconpath> </iconpath> from guiisettings.. issue does not repeat (i have 1000s of icons in set)

3) reduced icons to 20 and issue does not occur though there is a bit of a slowdown..

probably code to access icons is not optimal (on pi when i set folder from gui, gui freezes for around 30 seconds..)

should i still open a ticket? or is this a pi limitation?

**Comment by opdenkamp** [comment]
well the code that checks for icons isn't nice atm, and having lots of channel icons or a slow storage will definitely make things slower. which is what i've said the last time someone played with that code :)
it can be improved by adding some form of caching of the directory listing and query that cache.

**Comment by mcaptur** [comment]
True. maybe you could change code to not check for new icons on resume from
sleep and allow the check for icons to be done manually from settings menu.

**Comment by opdenkamp** [comment]
that would be a work around that would change behaviour for everyone 
else who doesn't have issues with slow storage, so -1 on that approach.

mcaptur schreef op 3-1-2015 om 13:26:

**Pull request merged**
