### PR TITLE
Dropped libyajl 1.x 

### PR DESCRIPTION
**Pull request by topfs2**
2.x is a few years old, 1.x is only used in precise and older so seems valid to drop support for Helix.

### CODE REVIEW

**Comment by topfs2** [comment]
Do we still support it? would be nice to drop it IMO

**Comment by wsnipex** [comment]
nothing has changed, precise still only has yajl1. I'll see if I can backport it for our ppa, but other distros will have the same problem.

**Comment by topfs2** [comment]
I was more questioning if we want to support, I mean its almost 3 years
old. And the old releasea will continue to work on it just fine.
Den 31 jan 2015 17:02 skrev "Wolfgang Schupp" <notifications@github.com>:

**Comment by Paxxi** [comment]
For older platforms wouldn't it be possible to statically link yajl2 from depends and sidestep the issue?

**Comment by topfs2** [comment]
Yup, or carry this patch in packaging of the old platforms if they want to
keep it. IMO helix is good enough for precise :)
Den 31 jan 2015 20:23 skrev "Paxxi" <notifications@github.com>:

**Comment by wsnipex** [comment]
I backported yajl2 to precise for our PPAs. Untested though.

**Pull request merged**
