### PR TITLE
[Confluence] drop tvtunes support

### PR DESCRIPTION
**Pull request by ronie**
we should not endorse addons that put functionality behind a paywall.
http://kodi.wiki/view/Add-on:TvTunes#TvTunes_Theme_Library_.28Supporters_Only.29

### CODE REVIEW

**Comment by ace20022** [comment]
+1

**Comment by MartijnKaijser** [comment]
Backport?

**Comment by mkortstiege** [comment]
> Backport?

+1

**Comment by ronie** [comment]
> Backport?
> 
> +1

https://github.com/xbmc/xbmc/issues/8244

**Comment by robwebset** [comment]
Very narrow minded - how about taking part in the discussion and replying to emails?

http://forum.kodi.tv/showthread.php?tid=214287&pid=2136795#pid2136795

**Pull request merged**
