### PR TITLE
[VideoVersions] Optimize retrieval of video versions existence

### LINKED ISSUE #24169: Severe performance degradation when is used external database (MariaDB) after video versions feature merge
### Describe the bug
Here is a clear and concise description of what the problem is:

Severe performance degradation when is used external database (MariaDB) after video versions merge: opening the main movie list takes 50 seconds with black screen in a video library with 4000 movies.

This is after merge https://github.com/xbmc/xbmc/pull/14972 when before was almost immediate.

See this video:

https://github.com/xbmc/xbmc/assets/58434170/dad827cf-e2ce-4704-9363-bd66d5abfcbc

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Similar "load" times as before, especially if video versions feature is not used.

## Actual Behavior
50 second of delay and not responsive GUI during this time. Probably in a 10,000 movies collection it would take ~2 minutes.

## Possible Fix
The root cause it is made a extra individual SQL query looking for video versions for every movie populated in list here:

https://github.com/xbmc/xbmc/blob/b4ae12fe3bdf428ed40ca7d6a55f204e23dd83e7/xbmc/video/VideoDatabase.cpp#L4266

then is made this SQL query 4000 times before present movies list:

`"SELECT idFile FROM videoversion WHERE idMedia = %i AND mediaType = '%s'"`

Possible solutions:

1. Include a new "bool" variable in movies table "hasVersions" to avoid extra queries only to determine if movie has video versions. Cons: is need modify DB structure. Pros: seems logical.
2. Retrieve all movie versions info in one single large query and determine "hasVideoVersions" flag locally. Cons: is need extra code. Pros: not requires modify current video database. 

### To Reproduce

1. Use kodi with a remote/shared video database (MariaDB, etc.) containing several thousand movies.

Same behavior is observed in Windows x64 (i7-13700K - 24 cores) and Android (Shiled). Delays do not depend on powerful of client device.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/azizakelex.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

MariaDB

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:  21.0-BETA1 (20.90.801) Git:20231129-53101ab16d

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CrystalP**
## Description

Alternative to #24170 to restore the speed of the movies list after merge of video versions, using the db engine to do the work.

The problem is the retrieval of the existence of alternative movie versions, using an additional query per movie (function `HasVideoVersions()`). Large remote db are most impacted with the extra query overhead and network roundtrips.

* The PR adds a column boolean `hasVideoVersions` column to the view `movie_view`.
The column is a correlated subquery on the `videoversion` table to detect the presence of records linked to the same movie (`idMovie` + `mediaType = 'movie'`) and an `idFile` different from the movie's default version (stored as `movie.idFile`).

* Index added to videoversion to guarantee the performance.
* bump video db version to recreate the indexes

## Motivation and context

Fixes #24169.

It takes much longer to display list of movies since the merge of video versions, especially with large remote db.

## How has this been tested?

* local sqlite db: performed identically to query before merge of video versions on my slowest Windows desktop (~55ms for 1500 entries db),
Maybe slow Android with local database would show a gap?

* remote db: not available. Will try setting one up and migrating the library.
feedback in comments indicates that performance of 4000 rows external db is also the same as before merge of video versions.

## What is the effect on users?

Restore previous performance when displaying complete list of movies in library.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CrystalP** [comment]
Will ignore Jenkins suggestions for now as they would make the diff difficult to read.
Will apply suggestions at the end to the chosen option, if going ahead with this PR.

**Comment by thexai** [comment]
Thanks, this seems a better approach.

I quick tested (only commit 1) and unfortunately not works: is unable to update DB from 123 to 124:

```
2023-12-05 13:22:30.856 T:18872   debug <general>: CDatabaseManager::Initialize, updating databases...
2023-12-05 13:22:30.856 T:18872    info <general>: Running database version Addons33
2023-12-05 13:22:30.857 T:18872    info <general>: Running database version ViewModes6
2023-12-05 13:22:30.857 T:18872    info <general>: Running database version Textures13
2023-12-05 13:22:30.858 T:18872    info <general>: Running database version MyMusic83
2023-12-05 13:22:30.858 T:18872   debug <general>: dbiplus::MysqlDatabase::connect replacing configured host 192.168.50.13 with resolved host 192.168.50.13
2023-12-05 13:22:30.863 T:18872    info <general>: MYSQL: Connected to version 10.11.2-MariaDB
2023-12-05 13:22:30.865 T:18872   error <general>: Unable to open database: MyVideos124 [1049](Unknown database 'MyVideos124')
2023-12-05 13:22:30.866 T:18872   debug <general>: dbiplus::MysqlDatabase::connect replacing configured host 192.168.50.13 with resolved host 192.168.50.13
2023-12-05 13:22:30.870 T:18872    info <general>: Old database found - updating from version 123 to 124
2023-12-05 13:22:31.043 T:15748   debug <general>: CAESinkDirectSound::CheckPlayStatus: Resuming Playback
2023-12-05 13:22:31.043 T:15748 warning <general>: CWin32DirectSound::GetSpace - buffer underrun - W:7320, P:264, O:5288.
2023-12-05 13:23:13.514 T:18872   debug <general>: dbiplus::MysqlDatabase::connect replacing configured host 192.168.50.13 with resolved host 192.168.50.13
2023-12-05 13:23:13.520 T:18872    info <general>: Attempting to update the database MyVideos124 from version 123 to 124
2023-12-05 13:23:13.520 T:18872   debug <general>: Mysql Start transaction
2023-12-05 13:23:15.391 T:18872   debug <general>: Mysql commit transaction
2023-12-05 13:23:16.165 T:18872   debug <general>: Mysql Start transaction
2023-12-05 13:23:16.165 T:18872    info <general>: CVideoDatabase::CreateAnalytics - creating indices
2023-12-05 13:23:16.166 T:18872   debug <general>: Mysql execute: CREATE INDEX ix_bookmark ON bookmark (idFile, type)
2023-12-05 13:23:16.322 T:18872   debug <general>: Mysql execute: CREATE UNIQUE INDEX ix_settings ON settings ( idFile )
                                                   
2023-12-05 13:23:16.415 T:18872   debug <general>: Mysql execute: CREATE UNIQUE INDEX ix_stacktimes ON stacktimes ( idFile )
                                                   
2023-12-05 13:23:16.476 T:18872   debug <general>: Mysql execute: CREATE INDEX ix_path ON path ( strPath(255) )
2023-12-05 13:23:16.543 T:18872   debug <general>: Mysql execute: CREATE INDEX ix_path2 ON path ( idParentPath )
2023-12-05 13:23:16.618 T:18872   debug <general>: Mysql execute: CREATE INDEX ix_files ON files ( idPath, strFilename(255) )
2023-12-05 13:23:16.701 T:18872   debug <general>: Mysql execute: CREATE UNIQUE INDEX ix_movie_file_1 ON movie (idFile, idMovie)
2023-12-05 13:23:17.322 T:18872   debug <general>: Mysql execute: CREATE UNIQUE INDEX ix_movie_file_2 ON movie (idMovie, idFile)
2023-12-05 13:23:17.945 T:18872   debug <general>: Mysql execute: CREATE UNIQUE INDEX ix_tvshowlinkpath_1 ON tvshowlinkpath ( idShow, idPath )
                                                   
2023-12-05 13:23:18.050 T:18872   debug <general>: Mysql execute: CREATE UNIQUE INDEX ix_tvshowlinkpath_2 ON tvshowlinkpath ( idPath, idShow )
                                                   
2023-12-05 13:23:18.104 T:18872   debug <general>: Mysql execute: CREATE UNIQUE INDEX ix_movielinktvshow_1 ON movielinktvshow ( idShow, idMovie)
                                                   
2023-12-05 13:23:18.191 T:18872   debug <general>: Mysql execute: CREATE UNIQUE INDEX ix_movielinktvshow_2 ON movielinktvshow ( idMovie, idShow)
                                                   
2023-12-05 13:23:18.260 T:18872   debug <general>: Mysql execute: CREATE UNIQUE INDEX ix_episode_file_1 on episode (idEpisode, idFile)
2023-12-05 13:23:18.326 T:18872   debug <general>: Mysql execute: CREATE UNIQUE INDEX id_episode_file_2 on episode (idFile, idEpisode)
2023-12-05 13:23:18.340 T:18872   debug <general>: Mysql execute: CREATE INDEX ix_episode_season_episode on episode (c12, c13)
2023-12-05 13:23:18.388 T:18872   debug <general>: Mysql execute: CREATE INDEX ix_episode_bookmark on episode (c17)
2023-12-05 13:23:18.430 T:18872   debug <general>: Mysql execute: CREATE INDEX ix_episode_show1 on episode(idEpisode,idShow)
2023-12-05 13:23:18.457 T:18872   debug <general>: Mysql execute: CREATE INDEX ix_episode_show2 on episode(idShow,idEpisode)
2023-12-05 13:23:18.498 T:18872   debug <general>: Mysql execute: CREATE UNIQUE INDEX ix_musicvideo_file_1 on musicvideo (idMVideo, idFile)
2023-12-05 13:23:18.546 T:18872   debug <general>: Mysql execute: CREATE UNIQUE INDEX ix_musicvideo_file_2 on musicvideo (idFile, idMVideo)
2023-12-05 13:23:18.585 T:18872   debug <general>: Mysql execute: CREATE INDEX ixMovieBasePath ON movie ( c23(12) )
2023-12-05 13:23:19.414 T:18872   debug <general>: Mysql execute: CREATE INDEX ixMusicVideoBasePath ON musicvideo ( c14(12) )
2023-12-05 13:23:19.505 T:18872   debug <general>: Mysql execute: CREATE INDEX ixEpisodeBasePath ON episode ( c19(12) )
2023-12-05 13:23:19.584 T:18872   debug <general>: Mysql execute: CREATE INDEX ix_streamdetails ON streamdetails (idFile)
2023-12-05 13:23:19.789 T:18872   debug <general>: Mysql execute: CREATE INDEX ix_seasons ON seasons (idShow, season)
2023-12-05 13:23:19.910 T:18872   debug <general>: Mysql execute: CREATE INDEX ix_art ON art(media_id, media_type(20), type(20))
2023-12-05 13:23:20.754 T:18872   debug <general>: Mysql execute: CREATE INDEX ix_rating ON rating(media_id, media_type(20))
2023-12-05 13:23:20.955 T:18872   debug <general>: Mysql execute: CREATE INDEX ix_uniqueid1 ON uniqueid(media_id, media_type(20), type(20))
2023-12-05 13:23:21.075 T:18872   debug <general>: Mysql execute: CREATE INDEX ix_uniqueid2 ON uniqueid(media_type(20), value(20))
2023-12-05 13:23:21.218 T:18872   debug <general>: Mysql execute: CREATE UNIQUE INDEX ix_actor_1 ON actor (name(255))
2023-12-05 13:23:22.487 T:18872   debug <general>: Mysql execute: CREATE UNIQUE INDEX ix_actor_link_1 ON actor_link (actor_id, media_type(20), media_id, role(255))
2023-12-05 13:23:24.305 T:18872   debug <general>: Mysql execute: CREATE INDEX ix_actor_link_2 ON actor_link (media_id, media_type(20), actor_id)
2023-12-05 13:23:25.925 T:18872   debug <general>: Mysql execute: CREATE INDEX ix_actor_link_3 ON actor_link (media_type(20))
2023-12-05 13:23:27.275 T:18872   debug <general>: Mysql execute: CREATE INDEX ix_videoversions ON videoversion (idMedia, mediaType)
2023-12-05 13:23:27.296 T:18872   error <general>: SQL: [MyVideos124] Undefined MySQL error: Code (1071)
                                                   Query: CREATE INDEX ix_videoversions ON videoversion (idMedia, mediaType)
                                                   
2023-12-05 13:23:27.297 T:18872   error <general>: Exception updating database MyVideos124 from version 123 to 124
2023-12-05 13:23:27.297 T:18872   error <general>: Error updating database MyVideos124 from version 123 to 124
2023-12-05 13:23:27.298 T:18872   debug <general>: Mysql rollback transaction
2023-12-05 13:23:27.298 T:18872   debug <general>: dbiplus::MysqlDatabase::connect replacing configured host 192.168.50.13 with resolved host 192.168.50.13
2023-12-05 13:23:27.303 T:18872    info <general>: Old database found - updating from version 122 to 124
2023-12-05 13:23:27.306 T:18872   error <general>: SQL: Can't create database for copy: 'MyVideos122' (1007)
2023-12-05 13:23:27.306 T:18872   error <general>: Unable to copy old database MyVideos122 to new version MyVideos124
2023-12-05 13:23:27.309 T:18872    info <general>: Running database version TV44
2023-12-05 13:23:27.309 T:18872    info <general>: Running database version Epg16
2023-12-05 13:23:27.310 T:18872   debug <general>: CDatabaseManager::Initialize, updating databases... DONE
2023-12-05 13:23:27.327 T:13644   error <general>: CGUIDialogVideoVersion::CGUIDialogVideoVersion: Failed to open database
2023-12-05 13:23:27.331 T:13644    info <general>: Skipped 1 duplicate messages..
```

**Comment by thexai** [comment]
with `mediaType(20)` works:

**Comment by thexai** [comment]
4004 rows

No time difference:  

Commit 1 only  = 1440 ms
Commit 1+2+3  = 1446 ms

Coommit 1 seems best option as is more simple and for GUI infoLabel only is need bool flag anyway.

> but unsure if 100% reliable because Clean Library logic of video
> versions doesn't exist yet.

Really this is not relevant for this PR: I mean there may be bugs and uncovered/unimplemented cases (such as the logic when cleaning library with movies as part of versions, main version or not...) but this is the same with or without this PR.

I vote for commit 1 although someone more familiar with DB code should do final review.

The logics that may be missing to cover specific cases can surely be implemented later without requiring DB schema changes.

**Comment by CrystalP** [comment]
Thanks for the testing. I was going to ask for a comparison with before videoversions :-)
It's great news that there is no performance hit on the DB, and the client doesn't have any extra work.

With those results I don't see a reason to go to the more complicated denormalized approach in the future.


I added a note about version 1 in the description, I'm now confident it will be OK in the future because I found out that movie.idFile is used as the field to store the "default version", and therefore it will have to be maintained properly by a future Clean Library or chaos will happen.

I also prefer version 1 as it has the potential for the best performance, even though you'd probably need a huge database to see much difference.

**Comment by da-anda** [comment]
> With those results I don't see a reason to go to the more complicated denormalized approach in the future.

with a denormalized approach storing a bitmask value you could check against the existence of different types of "version". Like if it has extras as well, which will come in handy the second we split the extras handling from movie version handling (separate dialogs to manage those etc, which is something I wanted to do once I find some time and get a dev env going)

**Comment by the-black-eagle** [comment]
> Why would you need a bit or other flag to tell you if there's extras. Isn't the presence of an "extras" subdir good enough for versions in their own dir, or if you have multiple versions as files in the same dir (version1.mkv, version2.mkv, etc), then have matching extras subdirs (version1.extras, version2.extras, etc)..?

No, of course it isn't.  You need to store that info in the db somehow (and a bitmask flag is an ideal way) else you would need to look at the filesystem every time to determine if such a subdir existed or not.  Clearly this would be a major performance issue, whereas retrieving a single int value from the db is trivial.  Either that or you would end up doing complicated table joins to determine the same thing, again with a performance hit.

**Comment by CrystalP** [comment]
> with a denormalized approach storing a bitmask value you could check against the existence of different types of "version". Like if it has extras as well, which will come in handy the second we split the extras handling from movie version handling (separate dialogs and context menu entries to manage those etc, which is something I wanted to do once I find some time and get a dev env going)

Agreed that a bitfield would be more flexible, but it feels like premature optimization to me, with a maintenance cost to keep the denorm field updated. Perf with this PR is the same as before video versions, good enough in my book.

Denormalization is a tool to improve performance and is not meant to be the norm (pun not intended) in a relational database.

To separate hasExtras, a second correlated subquery could be added to movie_view, I'm not even sure that the index would have to be changed to include itemType to keep the performance level. I'll simulate it for my own edification.

**Comment by thexai** [comment]
I don't think anything more (or anything less) is needed in this PR. This PR is only a replacement of `HasVideoVersions` without perf. penalty.

Note that HasVideoVersions _only_ is used for bool infoLabel and this is the reason why is bool, now and before. 

Type of extras and others things are retrieved on demand (usually for one movie only) whereas `hasVideoVersions` needs to be super fast because are retrieved for all movies of DB in movies list (e.g to display different icon). This is the reason of special treatment for THIS bool only.

@CrystalP can you update the PR with commit 1 only to prepare for merge?

What is needed now is the review (of the code contained in this PR) by some dev familiarized with DB code. Speculating about other approaches or trying to include more things in this PR that have nothing to do with the original problem does not help.

**Comment by CrystalP** [comment]
Jenkins build this please

**Comment by thexai** [comment]
Although I am not a DB expert, I think this is the most correct way to implement this: views allow the data to be organized according to how they are displayed/accessed even if they come from different tables.

By not adding data directly to the movies table, redundant data are avoided and the change has little risk because it only changes the view, keeping all source data the same as it was.

Tested also in Shield. In fact DB 124 is what I am using now.

**Review by thexai — APPROVED** [review]

**Pull request merged**
