### PR TITLE
[fix] revert ba15b9fcc3 python xbmc.Monitor changes

### PR DESCRIPTION
**Pull request by Rechi**
## Description
revert #18667 (a15b9fcc3) python xbmc.Monitor changes 

## Motivation and Context
fixes crashes caused by library scans

## How Has This Been Tested?
started a library scan in Kodi successfully 

## Types of change
- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by DaveTBlake** [comment]
@CvH  are you able to test an LE build with this

**Comment by phunkyfish** [comment]
No more crash on OSX

**Comment by DaveTBlake** [comment]
Thanks for the fix @Rechi , there is positive test feedback for multiple platforms on Slack. Onwards to alpha3!

**Comment by CvH** [comment]
@DaveTBlake works like a charm, tx

**Pull request merged**
