### PR TITLE
Move all platform specific code to platform's folders.

### PR DESCRIPTION
**Pull request by afedchin**
## Description
Move all platform specific code which implements generic functionality into a platform folder.

## Motivation and Context
Currently we have a lot of specific platform's code spread-ed to the whole repository. This is a try to keep all platform specific code in one place.
As an example `Win32` platform had the following folders structure:
```
/xbmc
  |- filesystem
  |   |- win32
  |- network
  |   |- win32
  |- peripherals
  |   |- bus
  |       |- win32
  |- powermanagement
  |   |- win32
  |- storage
  |   |- win32
  |- utils
      |- win32
```
Now it has:
```
/xbmc/platform/win32
  |- filesystem
  |- network
  |- peripherals
  |- powermanagement
  |- storage
  |- utils
```

This doesn't touch `threads` for now to ensure that do not produce conflicts with @jimfcarroll's PR #13721

## How Has This Been Tested?
Don't run-time tested yet. As because this doesn't change business logic I think green light at Jenkins is enough.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Review by FernetMenta — APPROVED** [review]
great!

**Review by Memphiz — APPROVED** [review]
Nice work - thx for this digging work :)

**Comment by popcornmix** [comment]
Builds and runs on Pi, so no obvious problem here.

**Review by Rechi — APPROVED** [review]
looks good
found some win10 changes not related to this PR title, but it's fine for me if you want to keep them in this PR.

**Comment by afedchin** [comment]
thanks for reviewing.

**Pull request merged**
