### PR TITLE
splash text improvements

### PR DESCRIPTION
**Pull request by tamland**
This reduces the addon migration splash text to only show when updating addons and we know it will take time. Database migration is still always shown as it's far too many layer to go though.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by da-anda** [comment]
I was just about to ask if we could only show these messages when needed, as I noticed this odd flickering text on each startup recently. Then I found this PR :) Thanks.

**Comment by ksooo** [comment]
> I noticed this odd flickering text on each startup recently

 what @da-anda said. it's odd.

**Comment by tamland** [comment]
jenkins build this please

**Comment by tamland** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
@tamland fyi testsuite crashes since a while on OSX at the end of the building. So something you could ignore for merging (needs to be fixed of course)

**Comment by MartijnKaijser** [comment]
jenkins workspace was full..... 
jenkins build this please

**Pull request merged**
