### PR TITLE
[videoplayer] Fix vdpau crash after #13428.

### PR DESCRIPTION
**Pull request by ksooo**
As discussed. Fixes a crash introduced with #13428

### CODE REVIEW

**Comment by fritsch** [comment]
Did you check the ctor? No need for ```= {} ``` ?

**Comment by ksooo** [comment]
> Did you check the ctor? No need for = {} ?

 I "copied" the change from vaaapi.

**Comment by fritsch** [comment]
I had it there, seems fernet squashed it away. That was the question we discussed yesterdays :-) Keep it as is and merge it away :-)

**Comment by ksooo** [comment]
your button.

**Comment by fritsch** [comment]
Thx very much - currently investigating some other outtage of 46570c83 - seems it causes multi render reconfigure on playback start.

**Comment by ksooo** [comment]
thanks

**Pull request merged**
