### PR TITLE
[PVR] Dont confirm timer add

### PR DESCRIPTION
**Pull request by ksooo**
When a user adds a timer, for example using context menu on a selected EPG entry, a dialog pops up, asking for confirmation to add the timer. This makes perfect sense when deleting a timer, but for creation imo this is nonsense and I'm backed by different people in the forum. This PR removes this confirmation dialogs. :-)

The first commit just renames a member function to reflect what is actually does.

@xhaggi what do you think?

### CODE REVIEW

**Comment by xhaggi** [comment]
+1 from my side

**Comment by ksooo** [comment]
@da-anda any objections?

**Comment by da-anda** [comment]
nope

**Comment by ksooo** [comment]
jenkins build this please

**Comment by Jalle19** [comment]
+1

**Comment by mkortstiege** [comment]
jenkins build and merge

**Comment by ksooo** [comment]
Binary addons failed to build on IOS-ATV2. Definitely not related to this PR.

**Pull request merged**
