### PR TITLE
[backport][vfs][addons] fix title show of compressed package dir

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description

On requests #17066 (Matrix) and #17407 (Leia) was this changed to use the
whole item from addon, but seen now that it remove then before defined
list item title.

This Partially revert the previous change and set now only path like before.
The rest stay onchanged and work confirmed.

This much nowhere else since many places took the path when title was empty.
However, there are also places that absolutely need the title.

Backport of https://github.com/xbmc/xbmc/pull/17484

## Screenshots (if appropriate):

Bildschirmfoto von 2020-03-12 00-15-11

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by AlwinEsch** [comment]
jenkins build this please

**Pull request merged**
