### PR TITLE
[pvr] fix playback of recordings when an exact duplicate exists

### PR DESCRIPTION
**Pull request by Jalle19**
@ksooo @MartijnKaijser

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
is this going to require another RC because i want to cut Isengard to final as it is now

**Comment by ksooo** [comment]
I could live with Isengard without this fix. So, if there is the chance to get this in, fine - if not, also good. But another RC *only* for this fix is definitely not necessary.

**Comment by Jalle19** [comment]
I doubt it's sketchy enough to warrant additional testing so it's totally to you.

**Comment by ksooo** [comment]
@Jalle19 Up to me or to @MartijnKaijser?

**Comment by Jalle19** [comment]
I was referring to @MartijnKaijser. My only concern is that I haven't runtime tested yet, I can do that tomorrow on my production system.

**Comment by Jalle19** [comment]
Tested, while it works there's a pretty major regression in that the resume point for any recording is gone since the path changed.

**Comment by MartijnKaijser** [comment]
i have my doubts on including this for 15.2 and i want to release soon.

**Comment by Jalle19** [comment]
Yes, not worth risking a release over it.

**Pull request closed without merging**
