### PR TITLE
[Backport] Android default buttonmaps and generic controllers

### PR DESCRIPTION
**Pull request by garbear**
## Description

This PR backports the two primary PR fixes for Android joysticks:

* Added default buttonmaps (https://github.com/xbmc/xbmc/pull/25176)
* Added generic controller buttons/axes (https://github.com/xbmc/xbmc/pull/25177)

Due to a PR conflict, I've also included the logging improvements in https://github.com/xbmc/xbmc/pull/25174, which can only help in tracking down future input issues.

Logging has been in master since May, so it should be safe to backport. We should give master at least 3 weeks to test the other two fixes. _IOW not to be merged before 2024-07-17._

## Motivation and context

This PR backports the two "safe" fixes from the ill-fated joystick PR sent earlier this year. It should fix nearly all controllers. However, it may still affect remotes, so further testing should occur in master before this PR is merged.

## How has this been tested?

Tested on my 2017 NVidia Shield with several unmapped controllers.

## What is the effect on users?

* Fixes most controllers on Android

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Comment by garbear** [comment]
Positive result for a remote here: https://github.com/xbmc/xbmc/issues/24808#issuecomment-2196796687

**Comment by Merzavetss** [comment]
I installed the latest nightly v22 and the remote control worked! Voice input also works. But it is activated by another button on the remote control. Previously, it was tedious to press the OK key, now you need to press the context menu button.
Also, if I press the OK button while watching a movie, the image pauses instead of displaying the menu. so I can't change the audio track or subtitles

[kodi.log](https://github.com/user-attachments/files/16066879/kodi.log)

**Comment by garbear** [comment]
Thanks for the log. I see these devices:

```
Name: "Virtual"
Name: "MStar Smart TV IR Receiver"
Name: "MStar Smart TV Keypad"
Name: "virtual-search"
Name: "KIVI RC20"
Name: "XIAOMI MiMouse 2"
```

Can you see these in your log? Can you identify which one is your remote control? A debug log showing any buttons not working should let us see the problem.

**Comment by Merzavetss** [comment]
my remote control is called KIVI RC20

**Comment by garbear** [comment]
Here's the android key layout:

```
CPeripheralBusAndroid: Device discovered:
  Name: "KIVI RC20"
    ID: 5
    Controller number: 3
    Descriptor: "18acf1bcc17674..."
    Product ID: 0001
    Vendor ID: 0094
    Has microphone: false
    Is virtual: false
    Source flags: -0x7effd8ed
    Has source: SOURCE_DPAD (0x000201)
    Has source: SOURCE_GAMEPAD (0x000401)
    Has source: SOURCE_JOYSTICK (0x1000010)
    Has source: SOURCE_KEYBOARD (0x000101)
    Has source: SOURCE_MOUSE (0x002002)
    Has key: AKEYCODE_HOME (3)
    Has key: AKEYCODE_BACK (4)
    Has key: AKEYCODE_0 (7)
    Has key: AKEYCODE_1 (8)
    Has key: AKEYCODE_2 (9)
    Has key: AKEYCODE_3 (10)
    Has key: AKEYCODE_4 (11)
    Has key: AKEYCODE_5 (12)
    Has key: AKEYCODE_6 (13)
    Has key: AKEYCODE_7 (14)
    Has key: AKEYCODE_8 (15)
    Has key: AKEYCODE_9 (16)
    Has key: AKEYCODE_DPAD_UP (19)
    Has key: AKEYCODE_DPAD_DOWN (20)
    Has key: AKEYCODE_DPAD_LEFT (21)
    Has key: AKEYCODE_DPAD_RIGHT (22)
    Has key: AKEYCODE_DPAD_CENTER (23)
    Has key: AKEYCODE_VOLUME_UP (24)
    Has key: AKEYCODE_VOLUME_DOWN (25)
    Has key: AKEYCODE_POWER (26)
    Has key: AKEYCODE_PERIOD (56)
    Has key: AKEYCODE_MENU (82)
    Has key: AKEYCODE_MEDIA_PLAY_PAUSE (85)
    Has key: AKEYCODE_MEDIA_STOP (86)
    Has key: AKEYCODE_MEDIA_NEXT (87)
    Has key: AKEYCODE_MEDIA_PREVIOUS (88)
    Has key: AKEYCODE_MEDIA_REWIND (89)
    Has key: AKEYCODE_MEDIA_FAST_FORWARD (90)
    Has key: AKEYCODE_BUTTON_Z (101)
    Has key: AKEYCODE_MEDIA_PLAY (126)
    Has key: AKEYCODE_MEDIA_PAUSE (127)
    Has key: AKEYCODE_MEDIA_RECORD (130)
    Has key: AKEYCODE_NUMPAD_SUBTRACT (156)
    Has key: AKEYCODE_VOLUME_MUTE (164)
    Has key: AKEYCODE_INFO (165)
    Has key: AKEYCODE_CHANNEL_UP (166)
    Has key: AKEYCODE_CHANNEL_DOWN (167)
    Has key: AKEYCODE_GUIDE (172)
    Has key: AKEYCODE_CAPTIONS (175)
    Has key: AKEYCODE_SETTINGS (176)
    Has key: AKEYCODE_TV_INPUT (178)
    Has key: AKEYCODE_PROG_RED (183)
    Has key: AKEYCODE_PROG_GREEN (184)
    Has key: AKEYCODE_PROG_YELLOW (185)
    Has key: AKEYCODE_PROG_BLUE (186)
    Has key: AKEYCODE_BUTTON_11 (198)
    Has key: AKEYCODE_EISU (212)
    Has key: AKEYCODE_MUHENKAN (213)
    Has key: AKEYCODE_HENKAN (214)
    Has key: AKEYCODE_ASSIST (219)
    Has key: AKEYCODE_MEDIA_AUDIO_TRACK (222)
    Has key: AKEYCODE_PAIRING (225)
    Has key: AKEYCODE_LAST_CHANNEL (229)
    Has key: AKEYCODE_TV_TELETEXT (233)
    Has key: AKEYCODE_TV_INPUT_COMPOSITE_1 (247)
    Has key: AKEYCODE_TV_INPUT_COMPOSITE_2 (248)
    Has key: AKEYCODE_STEM_1 (265)
    Has key: AKEYCODE_ALL_APPS (284)
    Has axis: AMOTION_EVENT_AXIS_X (0)
      Endpoints: [0.000000, 1919.000000]
      Center: 0.000000
      Fuzz: 0.000000
    Has axis: AMOTION_EVENT_AXIS_Y (1)
      Endpoints: [0.000000, 1079.000000]
      Center: 0.000000
      Fuzz: 0.000000
    Has axis: AMOTION_EVENT_AXIS_PRESSURE (2)
      Endpoints: [0.000000, 1.000000]
      Center: 0.000000
      Fuzz: 0.000000
    Has axis: AMOTION_EVENT_AXIS_HSCROLL (10)
      Endpoints: [-1.000000, 1.000000]
      Center: 0.000000
      Fuzz: 0.000000
    Has axis: AMOTION_EVENT_AXIS_GENERIC_1 (32)
      Endpoints: [0.000000, 1.000000]
      Center: 0.000000
      Fuzz: 0.000000
CPeripheralBusAndroid: added input device
```

You can see that it looks pretty much like a controller - I'm not sure how we'd tell the difference in Kodi.

I think this is the case for a lot of remotes, so my intuition is to continue treating these remotes as controllers, and make them work as controllers identical to how they worked as remotes.

This means, for example, making the OK button open the menu instead of pausing the video. You'll notice there's other differences, such as the back button maybe now going straight home instead of back one menu. This issue I attempted to correct in https://github.com/xbmc/xbmc/pull/25178 but there was some controversy over changing the existing controller buttons. However, I think we accept that controller-remote unification will be controversial for controller users and move forward for the benefit of the codebase.

**Comment by garbear** [comment]
Positive result for shield tv 2017 controllers and toblerone remote: https://forum.kodi.tv/showthread.php?tid=376084&pid=3203304#pid3203304

**Comment by garbear** [comment]
Re-targeting to Omega 21.2

**Comment by garbear** [comment]
Another report of success: https://github.com/xbmc/xbmc/issues/25545#issuecomment-2267770951

**Comment by TPXP** [comment]
Hey there, I think this might fix the issue I'm having in https://github.com/xbmc/xbmc/issues/25669. Could you also test input with the Google TV app on tablet/phone?

Also, I'm having trouble typing accents with the app, could you test this?

**Comment by garbear** [comment]
@TPXP Thanks for your [report of success](https://github.com/xbmc/xbmc/issues/25669#issuecomment-2313354905), I'm curating these reports to evaluate if we should merge this backport.

At this point, I've gotten a bunch of reports of success, and only one vague report where I couldn't really understand what's wrong. The team's decided to merge this early in the v21.2 release cycle for more testing. If there's any problems we can always revert like last time. So here it goes!

**Pull request merged**
