### PR TITLE
[macos] codesign addon's binaries when they are to be cpack'd

### PR DESCRIPTION
**Pull request by kambala-decapitator**
## Motivation and Context
With code signed Kodi app (#17178) it's impossible to load unsigned binary addons that are not bundled with the app.

## How Has This Been Tested?
Tested building single add-on (vfs.rar) like Jenkins does as well as building an add-on as a part of Kodi build.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by phunkyfish** [comment]
Any update on this @kambala-decapitator ?

**Comment by kambala-decapitator** [comment]
This is not really required any more as Kodi is now signed with entitlements that allow loading unsigned libs. We can still do this at a later point.

**Comment by phunkyfish** [comment]
Will I close and put it on the back burner?

**Comment by kambala-decapitator** [comment]
Sure, and the backport as well.

**Pull request closed without merging**
