### PR TITLE
Bump for 18.8 final

### PR DESCRIPTION
**Pull request by DaveTBlake**
Bump for 18.8,  the end of the v18 release cycle.

### CODE REVIEW

**Comment by sopparus** [comment]
would it be possible to backport https://github.com/xbmc/xbmc/commit/6e2ba0f29b5e2d248f3e67e98eaec5e7fdfa960f before merge ?
using mariadb 10.5 with kodi-android wont work otherwise.

thanks

**Comment by bkuhls** [comment]
> would it be possible to backport [6e2ba0f](https://github.com/xbmc/xbmc/commit/6e2ba0f29b5e2d248f3e67e98eaec5e7fdfa960f) before merge ?
> using mariadb 10.5 with kodi-android wont work otherwise.

Please try this PR: https://github.com/xbmc/xbmc/pull/18171

**Comment by sopparus** [comment]
> > would it be possible to backport [6e2ba0f](https://github.com/xbmc/xbmc/commit/6e2ba0f29b5e2d248f3e67e98eaec5e7fdfa960f) before merge ?
> > using mariadb 10.5 with kodi-android wont work otherwise.
> 
> Please try this PR: #18171

I'm unable to build kodi for android but I can try if you have an apk.

thanks!

**Comment by Dnkhatri** [comment]
> > > would it be possible to backport [6e2ba0f](https://github.com/xbmc/xbmc/commit/6e2ba0f29b5e2d248f3e67e98eaec5e7fdfa960f) before merge ?
> > > using mariadb 10.5 with kodi-android wont work otherwise.
> > 
> > 
> > Please try this PR: #18171
> 
> I'm unable to build kodi for android but I can try if you have an apk.
> 
> thanks!

They are building at the moment. if you click the default details of a commit you will see a build for that pr
https://jenkins.kodi.tv/job/BuildMulti-PR/16658/

**Comment by sopparus** [comment]
Great, give me a few hours

**Comment by sopparus** [comment]
> > > > would it be possible to backport [6e2ba0f](https://github.com/xbmc/xbmc/commit/6e2ba0f29b5e2d248f3e67e98eaec5e7fdfa960f) before merge ?
> > > > using mariadb 10.5 with kodi-android wont work otherwise.
> > > 
> > > 
> > > Please try this PR: #18171
> > 
> > 
> > I'm unable to build kodi for android but I can try if you have an apk.
> > thanks!
> 
> They are building at the moment. if you click the default details of a commit you will see a build for that pr
> https://jenkins.kodi.tv/job/BuildMulti-PR/16658/

tested it and it works fine with mariadb 10.4 and 10.5. thanks alot!

**Comment by AlwinEsch** [comment]
Have added there a request for Leia https://github.com/xbmc/xbmc/pull/18193, maybe good to have on next release as the old URL no more maintained and present?

**Pull request merged**
