### PR TITLE
[pvr addons] Add pvr.filmon, sync pvr.iptvsimple and pvr.vuplus

### PR DESCRIPTION
**Pull request by hudokkow**

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build addons please

**Comment by hudokkow** [comment]
Error seems unrelated. @wsnipex, care to try again? https://github.com/xbmc/xbmc/pull/6640 is in.

**Comment by opdenkamp** [comment]
jenkins build addons please

**Comment by MartijnKaijser** [comment]
jenkins build addons please

**Comment by opdenkamp** [comment]
merging anyway because win32 will keep failing until they're all updated to the latest api

**Pull request merged**
