### PR TITLE
Output platform if Raspberry Pi was detected.

### PR DESCRIPTION
**Pull request by drwulsen**
## Description
Added information when compiling on RaspberryPi

## Motivation and Context
It clarifies to the user that the architecture was detected correctly.

## How Has This Been Tested?
Compiling on a raspberry pi3.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by wsnipex** [comment]
Please explain why this is needed. The detected platform is already output in https://github.com/xbmc/xbmc/blob/master/cmake/scripts/common/Platform.cmake#L26

**Comment by Rechi** [comment]
Most likely because of the following line.
https://github.com/xbmc/xbmc/blob/80033f206982082b2dcc6d9f376e75154b3ea047/cmake/scripts/common/ArchSetup.cmake#L98

**Comment by drwulsen** [comment]
Hi,

exactly. It's a little misleading when compiling via cmake on my gentoo-pi
that it says platform:
and not
platform: rbpi

it seems that the whole detection is disabled when using
kodi_depends_based_build which is the default on gentoo.
manually specifying dcpu or dcore_system/dcore_platform does not lead to a
succesful output. i'm not sure, if the appropriate optimizations are uses
then, as some time has passed since i compiled it and i've been working on
other things meanwhile.

thank you for your investigation and fast information!
... and please excuse if there's something weird in that PR, I'm new to
github.

Best regards and many thanks,
Walter



Rechi <notifications@github.com> schrieb am Mo., 17. Juni 2019, 13:12:

**Comment by wsnipex** [comment]
from a quick glance, the correct fix would be to use CORE_PLATFORM_NAME in https://github.com/xbmc/xbmc/blob/80033f206982082b2dcc6d9f376e75154b3ea047/cmake/scripts/common/ArchSetup.cmake#L98

**Comment by drwulsen** [comment]
Yeah, CORE_PLATFORM_NAME being set to rbpi and -DPLATFORM=raspberyy-pi does the trick.
Also specifying -DCPU=foo manually brings it back on track under gentoo.

Maybe we should close this one?

**Comment by candrews** [comment]
This should be closed...

**Comment by Rechi** [comment]
superseded by #16346

**Pull request closed without merging**
