### PR TITLE
[videolibrary]: do not set set season artwork on an empty tvshow

### PR DESCRIPTION
**Pull request by mkortstiege**
Fixes a crash introduced with 536f1c5f8b5272c17d61386a54b46ef0977ae2e1.

### CODE REVIEW

**Comment by mkortstiege** [comment]
jenkins build this please.

**Comment by mkortstiege** [comment]
@Montellese mind having a look at this one as well? Would be nice to shove this one in as soon as possible since it fixes a crash (introduced by myself :p).

**Comment by mkortstiege** [comment]
If there are no objections I'll hit the button in 24 hours.

**Comment by Montellese** [comment]
Looks good.

**Comment by mkortstiege** [comment]
Thanks. Will shove it in then ..

**Comment by uNiversaI** [comment]
And now it seems to have no selection bar when navigating into a tvshow with multiple seasons until any key is pressed.

**Comment by mkortstiege** [comment]
@uNiversaI not sure i completely understand. There´s no item selected when you enter a tvshow with multiple seasons?

**Comment by uNiversaI** [comment]
Yep, the selection bar is completely disappears (shows up for a fraction of second then gone). You know the blue bar that usually highlights the last used entry or first entry on listing. gone.

If tvshow dir is 
```
*all seasons
Season 1
Season2
etc
```
No bar.
If it is.
```
tvshowname exxsxx sometitle.ext
etc
```
Bar is visible.

only the scenario above is affected when navigating into multiple seasons tvshow.

**Comment by HitcherUK** [comment]
Do you mean the list isn't focused until you hit a button? If so, I fail to see how this commit is the cause.

**Comment by uNiversaI** [comment]
the list is focused only the blue bar disappears. the text itself on list is focused.

**Comment by mkortstiege** [comment]
Unfortunately I am not able to reproduce. For me it works like intended - the blue bar (in confluence) remains visible.

**Comment by uNiversaI** [comment]
Not where mutiple season are the case..Ill try to revert this and compiling to confirm.

Not sure if being nvidia matters here but sure something is broken.

**Comment by uNiversaI** [comment]
Well clearly not related to this PR maybe, but something did it...

Windows builds not affected Ubuntu build sure, very annoying, short of reverting the file back to stone age have no clew.

**Comment by mkortstiege** [comment]
I am running Ubuntu and I can´t reproduce. Same applies to OSX. @uNiversaI let´s continue the talk on the forums in order to not spam the others until the real issue is found.

**Comment by HitcherUK** [comment]
@uNiversaI Did you open an issue for the focus problem? Only I think I've seen it myself when opening a directory and you get the busy dialog focus is lost when busy is finished.

**Comment by uNiversaI** [comment]
No open issue, I found the problematic PR that caused it after narrowing it down to a specific day, with @mkortstiege assist we found the PR and I confirmed with tests, and as per his req I made comment there.

@hitcher see https://github.com/xbmc/xbmc/pull/5804

**Pull request merged**
