### PR TITLE
[ios] Add support for iPhoneX full resolution 

### PR DESCRIPTION
**Pull request by Memphiz**
Backport of #13066 in case we continue krypton.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Perhaps we can just merge the two PRs  and you can do a revision release just for ios?

**Comment by Memphiz** [comment]
Yes I can do that - will wait a bit and see if something more is missing (ios11.1 broke HDMI support on iOS for example which would be a good addition once I found out how to solve it ...)

**Comment by MartijnKaijser** [comment]
You could already merge these ofcourse

**Comment by Memphiz** [comment]
So no extra branch for iOS? Using krypton branch is fine with you?

**Comment by MartijnKaijser** [comment]
Sure

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
jenkins build this please

**Pull request merged**
