### PR TITLE
[addons] add first usable doxygen documentation

### PR DESCRIPTION
**Pull request by AlwinEsch**
Here comes the first usable part about the new add-on documentation system.

Currenty it use the over doxygen given parts from GUIInfoManager and all builtins

I hope the way in GUIInfoManager is acceptable, was a lot of text ;)

About the **Todo** strings, have added on position where the code was from me the text, but hope on other positions becomes it added from them who created the part.

Visible is this currently under http://alwinesch.github.io/

### CODE REVIEW

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by Razzeee** [comment]
@da-anda is that logo still okay to use?

**Comment by MartijnKaijser** [comment]
I would leave out zappy and just use Kodi logo

**Comment by da-anda** [comment]
@Razzeee well, Zappy can still be used, but I'd also prefer to only have the logo in this case.

**Comment by AlwinEsch** [comment]
Have changed the logo.

**Comment by AlwinEsch** [comment]
Also added the missing parts of Slideshow, has not seen on start that it is in other file :)

**Comment by AlwinEsch** [comment]
jenkins build this please

**Pull request merged**
