### PR TITLE
[pydocs] add missing content type "videos"

### PR DESCRIPTION
**Pull request by MartijnKaijser**
We forgot to add this to list...

### CODE REVIEW

**Comment by garbear** [comment]
"games" is now a valid content string as well

**Comment by phil65** [comment]
@garbear wouldnt it need the possibility for plugin authors to  assign a GameInfoTag to really make use of a "games" content type?

**Comment by garbear** [comment]
See the api commit in #11022

**Comment by phil65** [comment]
oh, cool. Didnt notice that. :)

**Comment by phil65** [comment]
Is "game" also a valid mediatype for listitems now?

**Comment by garbear** [comment]
Yes, along with "video", "music" and "pictures", "game" is a valid list item type I believe

**Comment by phil65** [comment]
ok, thx for info!

**Comment by Rechi** [comment]
Is this still needed?

**Comment by garbear** [comment]
@MartijnKaijser #12554

**Pull request merged**
