### PR TITLE
[cmake] Don't allow undefined symbols in shared libraries

### PR DESCRIPTION
**Pull request by fetzerch**
Prevents errors such as:
`dlopen failed: cannot locate symbol "_ZTV24CEGLNativeTypeAmlAndroid" referenced by "/data/app/org.xbmc.kodi-2/lib/arm/libkodi.so"...`

Needs to be rebased on the AML fix once that is done.

### CODE REVIEW

**Comment by fetzerch** [comment]
jenkins build this please

**Comment by akva2** [comment]
Uhm wont this break all addon binding libs?

**Comment by fetzerch** [comment]
Restricted it to android (as in autotools). For the other platforms we build executables and the linker checks the symbols anyways.

The other patch btw was needed to fix an undefined symbol error (getpwent) on a local build.

**Comment by wsnipex** [comment]
lgtm, jenkins build this please

**Comment by hudokkow** [comment]
droids don't like it:
> /home/jenkins/workspace/Android-X86/xbmc/windowing/egl/EGLNativeTypeAmlAndroid.h:27: error: undefined reference to 'vtable for CEGLNativeTypeAmlAndroid'
/home/jenkins/android-dev/android-toolchain-x86-17-r10e/bin/../lib/gcc/i686-linux-android/4.8/../../../../i686-linux-android/bin/ld: the vtable symbol may be undefined because the class is missing its key function
/home/jenkins/workspace/Android-X86/xbmc/windowing/egl/EGLWrapper.cpp:75: error: undefined reference to 'CEGLNativeTypeAmlogic::CEGLNativeTypeAmlogic()'

**Comment by MartijnKaijser** [comment]
@hudokkow that's part of my fix PR i guess

**Comment by fetzerch** [comment]
jenkins build this please

**Pull request merged**
