### PR TITLE
[BP][Android] SDK30 bump

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Backport of #21570
Backport of #20599

## Motivation and context
Playstore release

## What is the effect on users?
Playstore release

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by jobhh** [comment]
Starting in November 2022, app updates must target API level 31. So if the plan is still to release 19.5 with this pull request, there is very little time left ;)

Practically, it means this pull request should be updated to SDK 31 (and adjust for behavioral changes in Android 12), otherwise the Play Store release will be denied by Google.

**Comment by LawnMo** [comment]
> Practically, it means this pull request should be updated to SDK 31 (and adjust for behavioral changes in Android 12), otherwise the Play Store release will be denied by Google.

That's not true, fortunately, for existing apps you can bump to SDK 30 and still comply (aka. still be discoverable by all users on the play store) : 
> If your existing app’s target API level is 30 or above, then your app is compliant with this policy. 
https://support.google.com/googleplay/android-developer/answer/11926878?hl=en

It'd be nice to have Kodi updates return to the Play Store, thanks fuzzard for backporting this to 19.x, looking forward to it :)

**Comment by jobhh** [comment]
The URL you mentioned states something different:

Starting November 1, 2022 if your app doesn’t target API level 30 or above, new users with newer Android OS versions won't be able to discover or install your app on Google Play. You can request an extension if you need more time to update your app. Check your Play Console Inbox Messages for links to each of your app’s extension forms.

**Comment by LawnMo** [comment]
>  target API level 30 or above

This PR targets API/SDK30, what you quoted states the same thing : 
> # Store SDK compile version
> set(TARGET_SDK 30)
https://github.com/xbmc/xbmc/blob/0c1637280690c18ffae6498cd06f728aa5974402/cmake/platform/android/android.cmake#L5

**Comment by jobhh** [comment]
Ah true, my bad. I blame the lack of sleep :)

I meant to quote this url: https://developer.android.com/google/play/requirements/target-sdk

"Starting in November 2022, app updates must target API level 31 or above and adjust for behavioral changes in Android 12; except for Wear OS apps, which must target API level 30 or higher."

That seems like a information mismatch, right?

**Pull request closed without merging**
