### PR TITLE
[ProfileManager] Save changes when they happen

### PR DESCRIPTION
**Pull request by howie-f**
## Description
taken over from pr #17031 with friendly permission
these changes are already merged into Leia #16988

## Motivation and Context
needed here to keep Matrix and Leia in sync

## How Has This Been Tested?
Already in Leia + live-tested on Debian

## Types of change

- [X] **Improvement** (non-breaking change which improves existing functionality)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document

### CODE REVIEW

**Comment by phunkyfish** [comment]
Thanks for picking this up @howie-f

**Review by phunkyfish — APPROVED** [review]
This has been in Leia for quite some time so makes sense to bring forward.

**Comment by howie-f** [comment]
GBM + Wayland failures seem unrelated - out of disc space. feel free to squash

**Comment by phunkyfish** [comment]
We don’t squash on merge. Please squash and update the PR.

**Pull request merged**
