### PR TITLE
remove header filter

### PR DESCRIPTION
**Pull request by peak3d**
Remove filter of HEADER fields in CCurlFile 

## Description
Current curl implementation allows only a set of HEADER fields somewhen grepped from a wiki page.
This PR removes this filter and allows all HEADER's 

## Motivation and Context
During implementation of DASH content we had many issues by not being able to provide all HEADERS wich are necessary to get the required information. Some provider expect headers like Magine-Token: XYZ wich are currently ignored.

### CODE REVIEW

**Comment by wsnipex** [comment]
this reverts the decision to not blindly pass on everything addons set and opens up the security issues again.
There must be another way to do what you need

**Comment by peak3d** [comment]
Could you pls. explain the reason fo this filter? I had some discussions a while ago with someone from kodi team (don't remember who it was) and we both have not seen a use case for this.

**Comment by wsnipex** [comment]
e.g. see discussion on https://github.com/xbmc/xbmc/pull/8418

**Comment by FernetMenta** [comment]
-10000

**Comment by peak3d** [comment]
@FernetMenta I opened this PR for discussion and to let everybody know whats the reasons for it.
-10000 is not helpful :-)

Every addon can open an own HTTP server / use its own CURL instance for making things wich we try to avoid with this filter. So, the filter does IMO no sense at all because there are so many ways to do what peaple want to do. But: It means more coding for everyone.

You may know that I started inputstream.mpd with an own CURL handle, I switched to kodis implementation to benefit form the development there. So, adding this filter does not enhance any security .

Why not make a blacklist instead a whitelist? Would this be a solution? Look over the ickets with issues and blacklist the headers wich are security issues?

**Comment by FernetMenta** [comment]
A blacklist does not make sense because there is no control over this.
You could bypass the filter in case the addon is the caller but not in general.

**Comment by peak3d** [comment]
ok

**Comment by peak3d** [comment]
If necessary overruling will appear triggered from inputstream.

**Pull request closed without merging**
