### PR TITLE
[PVR] Timer settings dialog: Fix crash on ActivateWindow if dialog was not initialized properly.

### PR DESCRIPTION
**Pull request by ksooo**
Fixes crash reported here: http://forum.kodi.tv/showthread.php?tid=258708&pid=2239216#pid2239216
Closes trac#16577: http://trac.kodi.tv/ticket/16577

@Jalle19 @xhaggi good to go?

### CODE REVIEW

**Comment by xhaggi** [comment]
code looks sane

**Comment by ksooo** [comment]
jenkins build this please

**Comment by Jalle19** [comment]
Thanks. At some point we should add the code required for the user to acheive what he's trying to do, but this is a good first step.

**Comment by ksooo** [comment]
The ticket was solely about the crash. ;-) But yeah if I find some spare time I will take care of the actual feature request - in a feature PR.

**Comment by Jalle19** [comment]
Yes I know ;-)

**Pull request merged**
