### PR TITLE
[tools/depends] configure allow to provide linker name

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Allow user to set linker name using --with-linker=<name>. default without providing will fall back to ld

## Motivation and context
i noticed that currently android actually fails to set a linker name, and therefore it just goes with whatever the "system" linker is (often just called ld inside most dependencies).
The actual fault with android is the linker isnt called llvm-ld in bin tools, its just ld. remove platform_tool_prefix fixes this situation, but i know there are other linkers (eg mold, lld, gold, etc) that devs may wish to use/test with, hence the addition of the new option.

## How has this been tested?
configure with correct and incorrect linker for android/apple. make sure if linker given isnt found, we error to not fall into the "unknown" tool being used.

## What is the effect on users?
N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by garbear** [comment]
I've moved over to lld for building Kodi because ld blows up these days and depletes the RAM on low-powered systems. Should we document that lld is available for building depends?

**Comment by fuzzard** [comment]
Added docs for Android/Apple platforms. Didnt really want to do linux as i didnt see a place immediately appropriate, and in general i think linux is not intended to build using tools/depends. They should be using the enable_internal_xxx cmake options if a dependency needs to be handled separate from system.

Im not sure how much value it adds as a whole, but see what you think i guess.

**Review by garbear — APPROVED** [review]
Thanks for the documentation!

**Comment by fuzzard** [comment]
Jenkins build this please

**Pull request merged**
