### PR TITLE
[videoplayer][demuxer] Use guints instead of a consecutive numbering.

### PR DESCRIPTION
**Pull request by ace20022**
Not ready yet!

### CODE REVIEW

**Comment by FernetMenta** [comment]
As far as I can see this would generate a new guid whenever a new stream gets created. The problem with doing so is that VideoPlayer will reopen the stream players for a new stream. There are quite some cases where this is not wanted.

**Comment by ace20022** [comment]
@FernetMenta -vv please :-)

**Comment by FernetMenta** [comment]
i.e. on stream change event demuxers like ffmpeg or DemuxClient will recreate their internal structures. No need to re-open video if just an audio stream was added

Another example is NEXT_STREAM. An input stream can flush the demuxer (close/open). This does not imply that we want new ids that trigger re-open of stream players.

**Comment by FernetMenta** [comment]
@ace20022 why don't you re-write CSelectionStreams which is the root cause for many issues. This class is overcomplicated and put constraints (like no gaps) on demux streams that we often need to work around. In particular the methods CSelectionStreams::IndexOf are a good indicator that this calls has an issue.

**Comment by ace20022** [comment]
> i.e. on stream change event demuxers like ffmpeg or DemuxClient will recreate their internal structures. No need to re-open video if just an audio stream was added

I don't think that this will happen (the pvr stuff was lost on rebase).  


> Another example is NEXT_STREAM. An input stream can flush the demuxer (close/open). This does not imply that we want new ids that trigger re-open of stream players.

Have not check this one.

>@ace20022 why don't you re-write CSelectionStreams which is the root cause for many issues. This class is overcomplicated and put constraints (like no gaps) on demux streams that we often need to work around. In particular the methods CSelectionStreams::IndexOf are a good indicator that this calls has an issue.

If I'm not completely wrong (this code is some months old) gaps are allowed now. The removal of the source member however breaks "demuxers" that are opened/closed on some events and that rely on fixed stream numbers, like the vobsub demuxer.

The problem I'm trying to fix with this pr is the following. I want to add a multi source demuxer which manages a list of demuxers. Each of these manages a number of streams. For example one demuxer ```A``` opens a video file, a second one ```B``` an audio file and a third one ```C``` a subtitle file. 

- ```A``` manages 3 streams with ids ```0,1,2```
- ```B``` manages 1 streams with ids ```0```
- ```C``` manages 2 streams with ids ```0,1```

Our video player queries demux stream, e.g., using the packet's stream id, quite often. Currently there is no way to route the query to the correct demuxer.

**Comment by FernetMenta** [comment]
> I don't think that this will happen (the pvr stuff was lost on rebase).

pvr is my primary use case and the code as is in this pr would case issues

We need to get rid of iId that is the index of the array:
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemux.h#L79

Instead we identify a stream by its real id: iPhysicalId:
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemux.h#L80

We could give the demuxer an id and OR some bits with the stream id. I mean apply this counter to the demuxer id instead of stream id. This way you would have unique ids across demuxers. What do you think?

**Comment by ace20022** [comment]
>pvr is my primary use case and the code as is in this pr would case issues

I have the code for the old pvr demuxer.

I also thought about using a demuxer id, I'll check that. It's the 4 or 5 retry :-(

**Comment by ace20022** [comment]
@FernetMenta Would you prefer something like
```
struct StreamId 
{
  int deumxerId  = -1;
  int streamId = -1;
};
```
or some kind of bitmask?

**Comment by FernetMenta** [comment]
@ace20022 currently a stream has an id (int) and a physicalId (int). ffmpeg and pvr identify a stream by the physicalId and I would like to keep this. Why don't we drop CDemuxStream::iId in favour of CDemuxStream::demuxId. demuxId is set by demuxer which gets the id by the mechanism you have in this PR for CDemuxStream?

**Comment by ace20022** [comment]
Now I'm confused. I wanted to drop iId and rename physicalId to streamId and number the demuxers. 

Do you propose that we should only give actually added streams a guint? So in principal the same as this pr does? Or do you propose to give the demuxer ids and change all ```GetStream(int)``` calls to ```GetStream(int, int)```?

**Comment by FernetMenta** [comment]
> I wanted to drop iId and rename physicalId to streamId and number the demuxers

This is what I think too. I was talking about how to set the id of the demuxer and referring to the mechanism you suggested here.

**Pull request closed without merging**
