### PR TITLE
added: allow setting connection timeout for curl urls

### PR DESCRIPTION
**Pull request by notspiff**
... by using a protocol option

useful for addons grabbing stuff from sites which are slow to respond. requested here http://forum.kodi.tv/showthread.php?tid=221334

### CODE REVIEW

**Comment by Jalle19** [comment]
Will this be usable by PVR addons which use `libxbmchelper::OpenFile()` too? If so then +1.

**Comment by notspiff** [comment]
it's usable for everything that uses the VFS. a protocol option is specified like 

url|<urle_encoded_protocol_options> - i.e. append a pipe and then the options.

**Comment by Jalle19** [comment]
Sounds good.

**Comment by Memphiz** [comment]
+1 and fine by me (lets say if the API breakage guys count this as break or no break ;)).

**Comment by Jalle19** [comment]
Shouldn't the option just get ignored if e.g. an addon uses it on a Kodi build that doesn't have this code?

**Comment by notspiff** [comment]
it won't but it shouldn't harm. it's passed on as a http header if it matches no known prot option.

**Comment by Jalle19** [comment]
Not ideal, but better than failing completely.

**Comment by Jalle19** [comment]
jenkins build this please

**Comment by Jalle19** [comment]
Any objections on merging this? This change would be very useful for PVR clients that communicate with their backend using plain HTTP through `CHelper_libXBMC_addon::OpenFile/ReadFileString` - without this it is not possible to control the connection timeout (the default is 30 seconds I think).

**Comment by opdenkamp** [comment]
technically a feature, but +1 for isengard

**Comment by Jalle19** [comment]
jenkins build this please

**Comment by kib** [comment]
jenkins build this please because github went down

**Comment by kib** [comment]
@Jalle19  This is failing on trying to pull an unrelated PR - could it be rebased and force pushed ? 
(Bug in jenkins)

**Comment by kib** [comment]
@Jalle19 trying a manual build on jenkins because he is having some (unrelated) trouble.

**Pull request merged**
