### PR TITLE
[depends][cmake] Fix building with --with-sdk on OS X.

### PR DESCRIPTION
**Pull request by ghost**
The environment variable was not being set, so the specified SDK was ignored by
cmake, which would instead use its own logic to determine it.

On a pre-release version of OS X (10.11), but without the Xcode beta, it
determined the appropriate SDK was MacOSX10.11 and then failed because it
couldn't find a specific header (zlib.h), because the directory didn't actually
exist.
In that case passing --with-sdk=10.10 would have fixed it, but the environment
variable wasn't set here.

### CODE REVIEW

**Comment by Montellese** [comment]
Is `SDKROOT` available for anything else but osx/ios/atv2? This adds it for all platforms right?

**Comment by wsnipex** [comment]
pretty sure this is OSX only

**Comment by anaconda** [comment]
According to the configure.ac, `SDKROOT` is non-empty on Android with `--with-sdk-path=path` and on OS X/iOS where it queries `xcodebuild` for the path of the SDK version specified with `--with-sdk=version`.
cmake only cares about OS X/iOS though:
```
anepu:cmake-2.8.12 anaconda$ grep -nr SDKROOT .
./Modules/Platform/Darwin.cmake:110:elseif(NOT "x$ENV{SDKROOT}" STREQUAL "x" AND
./Modules/Platform/Darwin.cmake:111:        (NOT "x$ENV{SDKROOT}" MATCHES "/" OR IS_DIRECTORY "$ENV{SDKROOT}"))
./Modules/Platform/Darwin.cmake:112:  # Use the value of SDKROOT from the environment.
./Modules/Platform/Darwin.cmake:113:  set(_CMAKE_OSX_SYSROOT_DEFAULT "$ENV{SDKROOT}")
./Source/cmGlobalXCodeGenerator.cxx:3295:    buildSettings->AddAttribute("SDKROOT",
```

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by anaconda** [comment]
jenkins build this please

**Comment by stefansaraev** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
squash plz

**Comment by anaconda** [comment]
Squashed.

**Comment by wsnipex** [comment]
jenkins build and merge

**Comment by mkortstiege** [comment]
let's try again. jenkins build this please

**Comment by wsnipex** [comment]
jenkins build and merge

**Comment by anaconda** [comment]
I'm closing this in favor of #8072.

https://github.com/xbmc/xbmc/pull/8072/files#diff-dcc8affab203beaa537d9d2020732521R16 is a bit different as it ignores --with-sdk, but still makes it build on 10.11 with the 10.10 SDK:
```shell
anepu:~ anaconda$ uname -r; xcrun --show-sdk-path
15.0.0
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk
```

**Pull request closed without merging**
