### PR TITLE
[pvr.iptvsimple] Sync with v1.11.0 (API 1.9.6)

### PR DESCRIPTION
**Pull request by afedchin**
see title

### CODE REVIEW

**Comment by afedchin** [comment]
jenkins build addons please

**Comment by afedchin** [comment]
jenkins build addons please

**Comment by xhaggi** [comment]
why do you change the repo to your own?

**Comment by xhaggi** [comment]
ahh my mistake only looked at the changes not at the tmp commit ;)

**Comment by afedchin** [comment]
jenkins build addons please

**Comment by afedchin** [comment]
let's try again, jenkins build addons please

**Pull request merged**
