### PR TITLE
VideoPlayer: Change subtitle scanning order

### PR DESCRIPTION
**Pull request by joseluismarti**
## Description
When a video is started, the VideoPlayer scans for external subtitle files and then for the subtitles included in the video. If a new subtitle is added during playback, it will be added at the end of the subtitle list.

I propose to change the scanning order: first internal, then external. This way the subtitles are scanned in the same order as when adding a new one (see issue #19211)

I've added a new ```ScanExternalSubtitles()``` method with the subtitles logic of ```OpenInputStream()```. The call to this method is made once the Demux has scanned the internal subtitles.

## How Has This Been Tested?
I've made several tests with subtitles and it works correctly.

## Screenshots
List of available subtitles when playing a video for the first time:

**Current:**
current

**PR:**
new

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by arnova** [comment]
The current logic is by design and allows users to override (faulty) internal subtitles. This shouldn't be changed. I think what you're actually looking for is an option that will let Kodi remember the last selected(downloaded) subtitle.....

**Comment by TimoJJ** [comment]
I tested this patch. It works correctly with internal subtitles and a downloaded subtitle. 
But there is an issue if I have multiple external subtitles. I have a movie that has no internal subtitles and there is already an English language .srt file for it. If I now download my own language (Finnish) subtitle, somewhat similar problem happens: the correct subtitle is first shown but when I stop playback, it's not shown anymore (neither is English subtitle).

**Comment by joseluismarti** [comment]
Hi @arnova this change modifies the order, but does not affect the subtitle selection logic and users can continue to overwrite the internal subtitles.

Hi @TimoJJ I had tried a similar scenario and it worked fine, I will try it again.

**Comment by TimoJJ** [comment]
I think the movie I tried already had some text track number stored in the database since the Finnish subtitle was already once downloaded. I deleted the Finnish language subtitle, left the English language subs there and downloaded again Finnish subs and the issue happened. 
Looks like even removing the movie from the disk and cleaning library after that won't help, the same issue still happens. But when I used a different file location for the same movie (without scanning it to library), there was no problem. I loaded a second external subtitle and it was correctly shown and continued to show after stopping and restarting playback.

**Comment by joseluismarti** [comment]
@TimoJJ This patch does not completely fix the issue you've identified, because in case there's at least one external subtitle and we download a new one, in the next playback the new subtitle may be in a different position. The patch should sort the subtitle streams before saving the id and sort when starting playback.

Regarding this PR, if there's no advantage in changing the order, it's safer to keep it.

**Comment by TimoJJ** [comment]
Two external subtitles is a rare case (for me) while internal subtitles and a downloaded subtitle is very common situation causing this bug to appear every time. This fixes that issue.

Maybe another way to fix this is not store subtitle track after download and make Kodi just redetect/rescan subtitles, so that the set preferred subtitle language from options is used if such language subtitle was just added. Only after manual subtitle track selection should Kodi store the selection.

**Comment by joseluismarti** [comment]
Add more information to evaluate:

The current process that extracts the thumbnail and the stream info from the selected video and stores in the database (table streamdetails), first scans the internal subtitles and then the external subtitles.

See ```CDVDFileInfo::ExtractThumb()``` called by ```CThumbExtractor::DoWork()```

**Comment by arnova** [comment]
> Two external subtitles is a rare case (for me) while internal subtitles and a downloaded subtitle is very common situation causing this bug to appear every time. This fixes that issue.
> 
> Maybe another way to fix this is not store subtitle track after download and make Kodi just redetect/rescan subtitles, so that the set preferred subtitle language from options is used if such language subtitle was just added. Only after manual subtitle track selection should Kodi store the selection.

Well it's not that uncommon, to be honest. When someone already has an external subtitle which is in the wrong language or is not properly synced, you also want to download a new one. Now that I understand what this PR is trying to accomplish, I do think it should work properly with all the scenarios you mentioned. So it's getting close but we're not there yet.

**Pull request closed without merging**
