### PR TITLE
GLContextEGL: Fix wraparounds on 32 bit system

### PR DESCRIPTION
**Pull request by fritsch**
Fixes the issue reported here: https://forum.kodi.tv/showthread.php?tid=341425&page=3

### CODE REVIEW

**Comment by fritsch** [comment]
Thanks to @FernetMenta 

I need jenkins to test build it, as I have currently no environemnt for building kodi.

**Comment by notspiff** [comment]
style preference, but personally i'd rather qualify the constants.

**Comment by fritsch** [comment]
@notspiff yes, adding ULL would help. I used what other files do, e.g.:
```
xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAEResamplePi.cpp:  Start = ((int64_t)now.tv_sec * 1000000000L) + now.tv_nsec; \
xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAEResamplePi.cpp:  End = ((int64_t)now.tv_sec * 1000000000L) + now.tv_nsec; \
xbmc/platform/linux/OMXClock.cpp:  return( ((int64_t)now.tv_sec * 1000000000L) + now.tv_nsec );
xbmc/platform/linux/TimeUtils.cpp:  return (end.tv_sec - start.tv_sec) * UINT64_C(1000000000) + (end.tv_nsec - start.tv_nsec);
xbmc/utils/TimeUtils.cpp:  return( ((int64_t)now.tv_sec * 1000000000L) + now.tv_nsec );
```

in fact they double the L (not enough for 64 bit) at the constant and the cast before multiplication. Whatever you prefer I can do.

**Comment by notspiff** [comment]
then just keep it, to stay consistent.

**Comment by fritsch** [comment]
After thinking I decided to "also double" (while ULL would be enough) ... for consistency

**Comment by pkerling** [comment]
IMO there is no need for the explicit cast - you're not consistent with the C-style casts either way :) Also you can change the other casts for consistency ;-)

**Review by yol — APPROVED** [review]

**Comment by yasij** [comment]
You should wrap the /1000 into the original calculation to avoid scaling up and back down. You lose 10 bits of precision doing that. Multiply by seconds by 1000000 and divide nanoseconds by 1000.

**Comment by fritsch** [comment]
What do you think we loose, speaking in time (fraction of milli seconds)? And how does that relate to vblank sync units (e.g. 60 fps, 120 fps, 24 fps).

In short: we don't need this precision here at all, even if we loose up to one micro second, which is still 1/1000 of a ms, in short: if we get TVs / monitors / refreshrates with 1000 hz - we slowly start to run into an issue.

Do you see it differently?

**Comment by yasij** [comment]
Those aren't the 10 bits you're losing by doing that scaling. You're not losing fractions of milliseconds. You're losing the most significant 10 bits, not the least significant.

**Comment by yasij** [comment]
It won't matter on the 32-bit system. On a 64-bit system time_t is 64-bit. Multiplying by 10^9 is about a shift of 30 bits up. It's a problem that will hit in the future after the 2038 bug.

**Comment by fritsch** [comment]
```
uint64_t now = static_cast<uint64_t>(nowTs.tv_sec) * 1000000000ULL + nowTs.tv_nsec;
now /= 1000;
```

Your issue basically is, that 
```
clock_gettime(CLOCK_MONOTONIC, &nowTs);
```
will wrap around in 2038, which is true. So, how will the dividing by 1000 in above computation help? And what has one to do with the other?

Please send a separate PR to propse and explain the fix.

**Comment by FernetMenta** [comment]
CLOCK_MONOTONIC returns the timespan the system has been running, not epoch. I doubt that somebody will have a kodi system running that long, that the code will fail here :)

**Comment by fritsch** [comment]
Hihi :-)

```
Clock that cannot be set and represents monotonic time since some unspecified starting point.
```
Yeah - but even if it (for whatever reason would return the seconds since 1970) is with the wraparound, my question to @yasij still stands - what has this one to do with the division by 1000.

**Comment by fritsch** [comment]
And for others reading, the clock really wrapping around is: CLOCK_REALTIME

**Comment by FernetMenta** [comment]
> On Linux, that point corresponds to the number of seconds that
              the system has been running since it was booted.

http://man7.org/linux/man-pages/man2/clock_gettime.2.html

other source: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_for_real_time/7/html/reference_guide/sect-posix_clocks

**Comment by yasij** [comment]
It's not the division by 1000 by itself. It's the multiply by 1000000000 that eats the precision. You're calculating microseconds. There is no need for an intermediate step with nanoseconds calculated. Do it in one step. The generated code is better and doesn't toss away the top bits.

uint64_t now = static_cast<uint64_t>(nowTs.tv_sec) * 1000000ULL + nowTs.tv_nsec/1000;

**Comment by fritsch** [comment]
That is correct, while still not an issue for the 64 bit value until you hit an uptime of 35 years, right?

**Comment by fritsch** [comment]
Please review: https://github.com/xbmc/xbmc/pull/15746 @yasij  I have for sure missed a zero too much at a certain number.

**Pull request merged**
