### PR TITLE
[addon] webinterface shouldn't have GUI as dependency

### PR DESCRIPTION
**Pull request by MartijnKaijser**

### CODE REVIEW

**Comment by Montellese** [comment]
I never understood this. I also don't like the `xbmc.gui.webinterface` extension point name.

**Comment by MartijnKaijser** [comment]
hmm indeed that extension point is kinda weird. might as well make a better one and make them redundant and drop old in x releases

**Comment by Montellese** [comment]
Unfortunately keeping backwards compatibility is not easy without some ugly hacks.

**Comment by MartijnKaijser** [comment]
well there are only 2 or webinterfaces in repo and we can tell them to already add the new extension point name (or we push it ourselves). not as nice but effective

**Comment by Montellese** [comment]
Yeah apart from the default webinterface (which should go for the next release) there is only AWXi and Chorus (which should replace the default webinterface). But it will mean that we'll need a new webinterface addon repo which is not backwards compatible with the one used in Gotham/Helix.

**Comment by MartijnKaijser** [comment]
Why a new repo? both addons can be updated to have two extensions so they will show in gotham/helix with old extension and with new extension in I**. Any new interface wil just be pushed to the I*** branch. No new repo needed. Just the adjustment in core code for the extension change

**Comment by Montellese** [comment]
Ah yeah we can duplicate the extension point in the addon.xml and have one with `xbmc.gui.webinterface` and one with `xbmc.webinterface`. Didn't think of that.

**Comment by Montellese** [comment]
See #6396.

**Pull request merged**
