### PR TITLE
CodecScreen: Remove fps

### PR DESCRIPTION
**Pull request by fritsch**
Having enough from all those pseudos on the forum, that don't understand what fps really means ... here it goes away.

### CODE REVIEW

**Comment by FernetMenta** [comment]
hehe +1
better late than never :)

**Comment by arnova** [comment]
Isn't this still useful for debugging purposes?

**Comment by fritsch** [comment]
@arnova What exactly do you want to debug? This fps value is an incorrect value on all Bypass render arches it will show something like 7 fps ... all the time. On "standard" systems it's an incorrect value, that is ~ +-3 fps near the real value.

**Comment by afedchin** [comment]
for debugging you can use ToggleDebug

**Comment by afedchin** [comment]
but I predict shit storm from users who uses this as fps meter.

**Comment by arnova** [comment]
I see, then it's pretty useless yes.

**Comment by fritsch** [comment]
@afedchin Basically I removed it cause of the "current" shitstorm ... 

- my fps values are 24.9 but I play 23.976 fps
- my fps sticks at 7.5 fps - I had to downgrade to v14
- Kodi v15 runs slow on my system
- ...

Even the wiki entry did not help: http://kodi.wiki/view/Codecinfo <- that was most likely fernet and that ws me in order to inform users: http://kodi.wiki/view/Kodi_v15_(Isengard)_FAQ#The_.22o.22_screen_doesn.27t_show_the_video_FPS_anymore

**Comment by afedchin** [comment]
@fritsch let's see which storm is stronger :) 
+1 from me to merge this

**Comment by FernetMenta** [comment]
> Isn't this still useful for debugging purposes?

@arnova why do you think so? it turned out that I was the only person on earth who knew what exactly this value is about. how can someone use something for debugging without knowing what exactly it shows?

**Comment by uNiversaI** [comment]
The only value that should replace this is free memory since that line already displays cpu usage

**Comment by MartijnKaijser** [comment]
please backport to Isengard as well and remove from systeminfo too

**Comment by Paxxi** [comment]
+1 it's about time this goes away

**Comment by fritsch** [comment]
Updated.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
