### PR TITLE
[skin.confluence] fix overlapping mute-bug in FullscreenVideo/OSD

### PR DESCRIPTION
**Pull request by InuSasha**
Screenshots says more then words :)
(old -> new)

### CODE REVIEW

**Comment by ronie** [comment]
looks good to me.

**Comment by uNiversaI** [comment]
This use to work just fine until a week or two ago. and Im not sure the correct way is to workaround in skin.

**Comment by InuSasha** [comment]
worked for 3 days, i think it is enough for that kind of change.
The position of GUI elements, are skinning topic. Do you know a better solution???

**Comment by ronie** [comment]
> The position of GUI elements, are skinning topic.

not sure what you mean :)

**Comment by InuSasha** [comment]
sorry non-native speaker :)

IMHO, skins have the job, to place the GUI elements at there position. This PR only change the position of some elements on the GUI. no functional changes.
So i think, the skin is the only place to fix the problem.

The comment of @uNiversaI is a bit confusing me, at this point.

**Comment by ronie** [comment]
yeah, your PR is the correct way to do this.
confluence uses similar methods everywhere in the skin to slide the time label to the left when the mute icon is visible.

**Comment by uNiversaI** [comment]
> yeah, your PR is the correct way to do this.
> confluence uses similar methods everywhere in the skin to slide the time label to the left when the mute icon is visible.

Yes, but the mute icon dindt use to overlap a few days ago, so something in master caused this to break., Im willing to bet its causing http://forum.kodi.tv/showthread.php?tid=225853 also.

Im suggesting the bug was caused somewhere else, and if that is fixed, this isn't required., what idk.

**Comment by InuSasha** [comment]
This problem is actuall in stable (14.2) and in master (d1a2c33).

**Comment by ronie** [comment]
thx!

**Pull request merged**
