### PR TITLE
[pictures] SlideShowPicture: fix texels to display only filled part of t...

### PR DESCRIPTION
**Pull request by afedchin**
...exture instead of displaying whole texture.

This fixes http://trac.kodi.tv/ticket/15377

I've found this bug during working on dx11 version, just forgot to send patch.

### CODE REVIEW

**Comment by afedchin** [comment]
any objections? jenkins build this please

**Comment by MilhouseVH** [comment]
This PR doesn't seem to have had any effect on the image I have a problem with (the Sportsdevil fanart in [this](http://forum.kodi.tv/showthread.php?tid=196400&pid=1784580#pid1784580) thread) - I'm still seeing miscoloured pixels down the right hand edge.

**Comment by afedchin** [comment]
this fixed dispaying image with slide show. Your problem is another issue.

**Comment by bossanova808** [comment]
I tried (the DX11 compiled version of) this, indeed fixes the issue here.

**Comment by afedchin** [comment]
If no objections, I'll merge this evening.

**Pull request merged**
