### PR TITLE
[Helix backport]  Fix memory leak in OGGcodec

### PR DESCRIPTION
**Pull request by un1versal**
m_inited was never set to true and initialised

This is a backport of #6113

@FernetMenta for labelling etc.

### CODE REVIEW

**Comment by fritsch** [comment]
As long as we ship it, it should be working correctly.

jenkins build this please

**Comment by uNiversaI** [comment]
Ive rebased and pushed so jenkins success was lost.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by topfs2** [comment]
Looks good to me

**Pull request merged**
