### PR TITLE
Fix font loading issue with libass on windows

### PR DESCRIPTION
**Pull request by enen92**
## Description
Identical to https://github.com/xbmc/xbmc/pull/19569, this fixes libass not detecting directwrite font provider in windows. This needs to get in first in the v20 branch before a backport can be done towards Matrix

## Motivation and Context
https://forum.kodi.tv/showthread.php?tid=361545&page=2

## How Has This Been Tested?
I'll test from a testbuild generated by jenkins from this PR

### CODE REVIEW

**Comment by howie-f** [comment]
jenkins build this please

**Review by Paxxi — APPROVED** [review]

**Comment by enen92** [comment]
Test build available in http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20210413-649c2844-PR19571-merge-x64.exe

jenkins build this please

**Comment by enen92** [comment]
Tested and confirmed the issue is fixed, directwrite is properly detected! Thanks @Paxxi 
Jenkins build and merge

**Comment by enen92** [comment]
Jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by enen92** [comment]
No idea what's going wrong here with gtestresults, but it's the 4rd time the build fails. Any idea @lrusak ?

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Pull request merged**
