### PR TITLE
CHG: [droid] stop video if screen goes off

### PR DESCRIPTION
**Pull request by koying**
as the title says

### CODE REVIEW

**Review by peak3d — APPROVED** [review]

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by CiNcH83** [comment]
Are you sure about that? On Sony you can switch off the screen via ACTION MENU with audio still playing. I don't know whether this triggers the "android.intent.action.SCREEN_OFF" though. If I interpret the PR correctly, it would stop playback alltogether?

Currently this does not matter though as bringing up the ACTION MENU still stops playback anyway.

**Comment by koying** [comment]
Is it so? 
Anyway, this one only stops video, not audio only. 
It's in spmc since ages, so you can test

**Comment by CiNcH83** [comment]
Tried it out now with SPMC 16.6.0. It behaves well. When I do ACTION MENU > Picture Off on my Sony, the screen goes off, but video keeps playing, so you still hear sound. So it seems that Picture Off does not trigger the "android.intent.action.SCREEN_OFF".

**Comment by koying** [comment]
Yeah. Pretty sure anything in the Action menu relates to the "TV" subsystem, and is completely independedant from the "Android" subsystem.

**Pull request merged**
