### PR TITLE
[cmake/windowing] fix dependencies X11/XRandR/OpenGLES

### PR DESCRIPTION
**Pull request by mac-l1**
## Description

This change originates from another pull request [https://github.com/xbmc/xbmc/pull/11772](url) and @FernetMenta 's advise. It relates to kodi linux build for X11 platform that only uses OpenGLES and not OpenGL.

1. [cmake] in case of OpenGLES not only use X module but also XRandR, just as is done in case of OpenGL
2. [windowing] dont rely on implicit inclusion of <X11/Xutil.h> in <EGL/egl.h>/<EGL/eglplatform.h> but include it explicitly
3. [windowing/egl] remove native egl platform dependency when X11 platform is used in combination with OpenGLES

## Motivation and Context

Change is needed in order to fix building for kodi linux builds for X11 platform that only uses OpenGLES and not OpenGL. This is for instance the case with arm based linux systems that use the arm mali graphical processor (GPU), like the latest rockchip linux systems (rk3288 and rk3399).

## How Has This Been Tested?

The change (just a working kodi build) has been tested on latest debian linux distribution (stretch) with X11 desktop and kernel (4.4) that is open sourced and provided by rockchip. It has been tested on firefly and miqi rk3288 devices.
Tests consisted of basic kodi browsing the menus, playing h264-videos and some youtube videos using the add-on.
## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by mac-l1** [comment]
@FernetMenta as discussed before, just added a new PR. can you please review?

**Comment by FernetMenta** [comment]
thanks!
jenkins build this please

**Comment by FernetMenta** [comment]
@wsnipex @hudokkow @fetzerch ok with you?

**Comment by wsnipex** [comment]
looks good

**Pull request merged**
