### PR TITLE
Fix include auto-mounted drives remote access allowed check

### PR DESCRIPTION
**Pull request by DaveTBlake**
Include auto-mounted drives as sources when checking if remote access is allowed. These are treated as sources elsewhere in Kodi, but are not added to sources.xml. Auto-mounted drives are common Android devices e.g. USB stick/drive used, and exist by default on RPi builds e.g. SD card

This Solves https://github.com/xbmc/xbmc/issues/14726 (Chorus and Kore being unable to access images on auto-mounted removable drives) that arose after #14501 

Tested on Windows with USB stick plugged in, but would like so testing on other platforms please. @MilhouseVH  could you create a LE build with this PR? Also useful if anyone can test on Android too.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Will do.

**Comment by pkerling** [comment]
I suggest making this configurable for v19 at least. I find it surprising that Kodi automatically shares the contents of all removable drives when I enable the web interface.

**Comment by MartijnKaijser** [comment]
Imo it's unsafe to just let anything auto share and such feature should not be auto enabled

**Comment by pkerling** [comment]
@MartijnKaijser yes, but for now this PR only restores prior functionality that was broken unintentionally in the path traversal fix

**Comment by MartijnKaijser** [comment]
You mean this PR enables again unsafe behaviour

**Comment by DaveTBlake** [comment]
>You mean this PR enables again unsafe behaviour

This PR enables Chorus and Kore to continue work. The security risks are minimal, especially compared to the poor state of security that Kodi has had for years and the team happily done nothing about.

>I suggest making this configurable for v19 at least. I find it surprising that Kodi automatically shares the contents of all removable drives when I enable the web interface.

More suprizing for users that Chorus and Kore stop working if they use USB drives or SD cards. Yes source management needs a serious redesign for v19. Auto mounted sources should be managed along with the user added ones, and both need the facility to set allow/block sharing via GUI.

What I ask is that in v18 beta we don't panic to secure something that has been open for 5 years and break other things in the process. @wsnipex added some protection, bit it needs this adjustment or it causes unwanted regression.

**Comment by wsnipex** [comment]
thanks for tracking this down!  Looks good to me.
Would you mind adding a todo/doxy that we must rework this for v19?
At least adding a config option as we already discussed on slack.

**Comment by pkerling** [comment]
> Would you mind adding a todo/doxy that we must rework this for v19?

Roadmap ticket would be best, doxys will get lost in the noise and this is (or should be) high priority

**Comment by DaveTBlake** [comment]
Sure, I will add both doxy todo and roadmap ticket.

Actually this change won't need reworking, it already checks m_allowSharing for both manually added and auto-mounted sources. It is the way sources get created by `g_mediaManager.GetRemovableDrives` that needs to have allowSharing made configureable. Both auto-mounted and manual sources are created share allowed by default, and both need a GUI for users to configure this.

Where do roadmap tickets go? Just another Github issue mixed in with the rest or is there a special place?

**Comment by pkerling** [comment]
> Where do roadmap tickets go? Just another Github issue mixed in with the rest or is there a special place?

Yes, just another GH issue ;-) Use the Roadmap Suggestion template when creating the ticket. It will get added to the correct roadmap project once @MartijnKaijser has everything set up I presume.

**Comment by DaveTBlake** [comment]
Tested on RPi2 / LE running Millhouse build 20181031210236-#1031-g76ed873 (includes this PR). Added music files from USB stick to library (with artist artwork on stick) then used Chorus2 to look at music lib via web server. All art was visible as expected.

By comparison in previous builds (since PR14501 merged) art was not visible for music on USB, and weberver requests for images resulted in "CUtil::GetMatchingSource: no matching source found for ..." messages in log

**Comment by DaveTBlake** [comment]
Doxy todo comment added as requested, I think good to merge.

**Pull request merged**
