### PR TITLE
[addons] add new CAddonInfo class

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description
This add the class who becomes extended step by step to replace cpluff.

Further replace this in future the complete AddonProps structure.

Currently include it only the static functions and table who was before
on other place.

This is done on this commit and request to hold coming request smaller
and prevent parts who not direct related to changes.

As next requests comes the basic read of addon.xml and to go over there.

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Here a example how it can look on end https://github.com/FernetMenta/kodi-agile/blob/master/xbmc/addons/AddonInfo.cpp (need some cleanup ;) )

**Comment by tamland** [comment]
Do we really need a *third* addon info thing in addition to CAddon and AddonProps? 
I think it would be better if you PRed something a bit more complete here. Just converting a function to a static method and adding an empty class doesn't make any sense..

**Comment by ksooo** [comment]
I like @AlwinEsch's approach to bring in the changes step by step. For me, this makes reviewing stuff a lot easier (if not possible at all). So, for me, small incremental steps are fine.

But I'm with @tamland that without a big picture (like: "at the end new CAddonInfo is going to elminate the redundancies we have today with CAddon and AddonProps") would be very helpful.

**Review by ksooo — COMMENTED** [review]
Code-wise this looks okay to me, but I have not enough knowledge to jugde on the conceptual concerns @tamland raised.

**Comment by AlwinEsch** [comment]
Hi @tamland the AddonProps parts becomes moved to CAddonInfo and the old structure removed.

Because CAddonInfo makes much more, the name AddonProps no longer fits.

**Comment by AchimTuran** [comment]
@ksooo @AlwinEsch 
> I like @AlwinEsch's approach to bring in the changes step by step. For me, this makes reviewing stuff a lot easier (if not possible at all). So, for me, small incremental steps are fine.

That's fine for me too. No one likes to review PRs greater than 1000 additions.

**Comment by AlwinEsch** [comment]
jenkins build this please

**Pull request merged**
