### PR TITLE
[PVR] Fix handling of epg tag attributes 'cast', 'writer', 'director' and 'genre'.

### PR DESCRIPTION
**Pull request by ksooo**
EPG tag attributes 'cast', 'writer', 'director' and 'genre' each can contain multiple persons/genres. This was not handled correctly so far. Genres was handled half-way right, the others completey wrong.

@Jalle19 mind taking a look.

### CODE REVIEW

**Review by Jalle19 — APPROVED** [review]

**Comment by ksooo** [comment]
Jenkins errors are unrelated.

**Comment by DaveTBlake** [comment]
@ksooo does this not need JSON API changes too? Switching serialized items from single to array etc. probably means a breaking change to JSON

**Comment by ksooo** [comment]
> Switching serialized items from single to array

I did not change external representation. Only internal representation changed from single string to vector. External rep is still single string.

**Comment by DaveTBlake** [comment]
The change just caught my eye as I have been looking at fixing some places in music where API expects a string and is getting an array, or vica-versa. Also adding where data exists but is not exposed at all.  

I am not familiar with PVR, but I know how easy it is to overlook the JSON aspects of changes to tag handling. Might be worth a review when you have time.

**Pull request merged**
