### PR TITLE
[win32] don't react on DPI change event on Win10 >= FCU

### PR DESCRIPTION
**Pull request by afedchin**
and some cosmetics related to the fix

this also fixes issues with wrong rendering size after dpi changes and/or display switch off/on

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Jenkins build this please

**Comment by Meliox** [comment]
I am wondering whether this will affect the notorious black screen after display on/off as well? E.g. "There appears to be a defect in Windows 1709 Fall Creator's Update which results in DirectX fullscreen applications not waking up when displays are reconnected."

**Comment by MartijnKaijser** [comment]
Ask questions on the forum please

**Comment by afedchin** [comment]
> I am wondering whether this will affect the notorious black screen after display on/off as well? E.g. "There appears to be a defect in Windows 1709 Fall Creator's Update which results in DirectX fullscreen applications not waking up when displays are reconnected."

no this has no effect to the issue. and as I know this was fixed in next windows update. in any case an app must resize swapchain buffer after mode change even if size of its buffer wasn't changed.

**Comment by afedchin** [comment]
@enen92 IIRC the top left corner can be located out of the screen position and if W and H match the current resolution we should use full screen window but I'm not sure at 100% what I'm right. it was too much time ago

**Pull request merged**
