### PR TITLE
osx: adapt to changes in IDispResource

### PR DESCRIPTION
**Pull request by FernetMenta**
see title, result: non working video reference clock

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
@Memphiz ping

**Comment by Memphiz** [comment]
Looks straight forward - thx

**Comment by Memphiz** [comment]
Ios needs the same changes - right?

**Comment by FernetMenta** [comment]
I did not check ios,  but probably yes

**Pull request merged**
