### PR TITLE
AMC(surface) is not a BYPASS

### PR DESCRIPTION
**Pull request by koying**
Cut the crap about amcs being a bypass.
Also cut the crap about having to wait for vsync
## Motivation and Context

Cut the crap ;)
## Types of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Already build and tested on Android (also only affects android specific code) and no negative affects

**Comment by mazeyx** [comment]
seems to use alot of cpu again with this upto 60% from 30%. also when you backout when video is playing you dont see the video in the background anymore.

**Comment by MartijnKaijser** [comment]
I can't reproduce the CPU usage at all. Both the Nexus Player and the NVIDIA SHIELD use the same before and after. Are you sure this PR is the cause as in try nightly before this one?
Only the playing in background is correct as i never use that at all so didn't check.

**Comment by mazeyx** [comment]
@MartijnKaijser just tried the test build which fixed the background image, seems the cpu load is down to 40% from 60% now much more acceptable, yeah the nightly before yesterday was giving me 30% cpu, i guess with the logic change my bravia cpu is less powerful then both those boxes so i notice it. 40% is ok if its a bug fix, 60% was abit too high and reminded me of the old days lol thanks

**Pull request merged**
