### PR TITLE
[linux] remove imx platform

### PR DESCRIPTION
**Pull request by lrusak**
as discussed at devcon.

No maintainer has come forward for this broken method.

DRM/V4L2 is the future and we should concentrate on that instead.

### CODE REVIEW

**Comment by fritsch** [comment]
If someone wonders: https://schd.ws/hosted_files/osseu17/e2/zero-copy_video_streaming.pdf here is an example of what will be upcoming. Pure zero copy with dma_buf from decoder to rendering.

**Comment by lrusak** [comment]
Can we put a deadline on this? Say a week from now it is slated for merging?

**Comment by notspiff** [comment]
why wait?

**Comment by lrusak** [comment]
Some people may have strong opinions about this?

**Comment by notspiff** [comment]
code doesn't even build right? those strong opinions would be worthless as i see it. but anyways, not trying to make a thing out of it, just doesn't make sense to wait from my understanding.

**Comment by fritsch** [comment]
Push it. It's git, it forgets nothing.

Am 03.11.2017 15:32 schrieb "Arne Morten Kvarving" <notifications@github.com

**Comment by lrusak** [comment]
jenkins build this please

**Pull request merged**
