### PR TITLE
Fix another instance of coverity #719001

### PR DESCRIPTION
**Pull request by tobbi**
So, I seemed to have missed that one last time.

### CODE REVIEW

**Comment by mkortstiege** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
please clarify the commit message what it fixes

**Comment by tobbi** [comment]
Fixed the commit message. Not sure if you need to re-trigger a build or not.

**Comment by MartijnKaijser** [comment]
build succeeded.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
