### PR TITLE
JSON-RPC: Improve performance of retrieving movies/tvshows/episodes/musicvideos with additional details

### PR DESCRIPTION
**Pull request by Montellese**
This adds an additional parameter to our `CVideoDatabase::GetFooByNav/GetFooByWhere` methods which allows the caller to specify whether the call should also retrieve additional details like cast, tags, streamdetails etc. which require additional SQL queries to be made and processed.

Right now in JSON-RPC we first retrieve all movies/tvshows/episodes/musicvideos without these additional details and then check if the request asks for one of the additional details and if so it goes through every retrieved item and manually retrieves the additional details. Obviously this is very slow. With this change I've seen an approximate speed improvement of 25% for a JSON-RPC request retrieving movies/tvshows/episodes/musicvideos with additional details.

This doesn't change the JSON-RPC API at all, just how it works underneath.

@Tolriq: would be nice if you could test this and report back if it still works and if it really is faster.

### CODE REVIEW

**Comment by Tolriq** [comment]
@Montellese will try to test when I find time :)

After a quick reading, I did ask to update JSON definition but well it seems it was not.
Anyway the new field ratings do require additional details, not sure it's handled in your code.

And if you are on speed things up, something that would have a very high impact on remotes that do full offline sync is a VideoLibrary.GetSeasons without required tvshowid. Currently we need to send 1 query per show, this is almost as long as syncing all the episodes on large number of shows.

**Comment by phate89** [comment]
@Montellese 
I was looking into it when I added rating. This is a very good improvement.  but to expand it is it really needed to ask every detail? Right now if someone ask only one field(for example tags) the code retrieve people, rating and tags. Why not adding a way to ask only for rating, only for cast or only for ratings? Can create some problem?

**Comment by Tolriq** [comment]
@Montellese Ok so I have done some tests, all still works (But I do not use the new ratings things (And I think it needs to be added here : https://github.com/xbmc/xbmc/pull/8862/files#diff-bc14ddc0bd64f94097c9f8c3cf871345R958)

About performance, I did them on a small amount of data to be more consistent as the more data the more possible other variation impacting speed.

Anyway for movies the gain is near null, for tvshows / season / episode (global value) the gain is around 5%.

But something that is interesting and can't explain is that the timing are much more stable with this patch than before.

For example for 22 shows 400 episodes sync could take between 6 sec to 4.6 sec. Now it's very stable between 4.4 / 4.5 so this is great gain.

(Of course the timings are from withing Yatse so include all the parsing / cleaning / do tons of stuff / insert in local DB, so does not represent the Kodi time but a more global time)

Since values are more stable I will test with a much larger library and edit this post to add the result.

**Comment by Montellese** [comment]
@Tolriq: Thanks for testing and the feedback. I only tested with ~800 movies.
I've added an extra commit which fixes the retrieval of the `ratings` property and also fixes all the descriptions for the JSON property types.

@phate89: Yes obviously that would be an additional improvement but it requires a lot more work.

**Comment by Montellese** [comment]
jenkins build this please

**Comment by phate89** [comment]
@Montellese  yes sure I was planning to look into it myself.
Also (always thinking out loud) instead of querying the details movie by movie to do something like this (example for tags):
`SELECT tag.name, tag_link.media_id FROM tag INNER JOIN tag_link ON tag_link.tag_id = tag.tag_id WHERE tag_link.media_id IN (LIST_OF_ID_RETRIEVED)` 
and combining them only after to avoid a lot of query to the db? It might improve things for you?

**Comment by Tolriq** [comment]
@Montellese Done tests with 5000 episodes and then the gain is more around 10%.

I'm pretty sure gain could be more if we do not use limits but well all remotes use limits for large set sync so this represent the normal gain.

Doing full timing test on a 54 second full sync time, 14 seconds are taken to sync the seasons due to GetSeasons needing 1 call per show (147 in this test case).

I've just tested and returning all seasons is possible and easy. Would you accept a PR for that ? (This would lead to 25% speed gain :) )

**Comment by Montellese** [comment]
Yes using limits will reduce the speed gain because we still have to retrieve all items + details and then apply the limiting. The reason for this is that the result might be sorted by one of the properties that require additional details so we first have to retrieve all information, perform sorting and then apply the limits.

**Comment by Tolriq** [comment]
Well maybe there's a way to apply limit first if there's no sort applied ? (Majority of the need for large dataset is just to have the data for future use so queried without sort)

If this query then apply limit applies also to music then gain could be great there too for large song database.

Anyway thanks again for tvseasons added to this patch it's nearly 35% speed gain this is huge :)

**Pull request merged**
