### PR TITLE
[skin][estuary] Show date added metadata info also to tvshows

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

Allow to show metadata date added also to tvshows

## Motivation and Context

Give more metadata info when available

## How Has This Been Tested?

In local with latest kodi nightly

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by ronie** [comment]
unlike what the name ListItem.DateAdded might suggest, for TV Shows it actually returns the 'last updated' date.
(see: https://github.com/xbmc/xbmc/pull/5016)

as such, i'd be better to label it as 'Last updated' ($LOCALIZE[12014]).
the easiest way would be to use a $VAR for the "altlabel".
```
<variable name="DateAddedLabelVar">
	<value condition="String.IsEqual(ListItem.DBType,tvshow)">$LOCALIZE[12014]</value>
	<value>$LOCALIZE[570]</value>
</variable>
```

**Comment by CastagnaIT** [comment]
I always thought it was "added to the catalog"

so there is no metadata for "date added to the catalog"..

**Comment by CastagnaIT** [comment]
it's out of my scope of it's use
because i have the date of added, not last modified

it would take a whole code revision to change the name of the property
that at least from what i think is wrong...

something like this should be more correct:
DateAdded: shoud be the date of added to catalog
DateUpdated or DateModified: should be used for show date of updates

but at this point i will remove its use from the add-on

**Comment by CastagnaIT** [comment]
because on the documentation is described as:
`The date the currently selected item was added to the library / Date and time of an event in the EventLog window`

https://codedocs.xyz/xbmc/xbmc/modules__infolabels_boolean_conditions.html#modules_list_infolabels_booleans

**Comment by ronie** [comment]
yup, that is correct for 'files' (movies / episodes / songs),
but for 'folders' (tv shows / artists / albums) it is the last updated date.

**Comment by CastagnaIT** [comment]
the name of this property however i do not find it suitable
and the description in the documentation should be reviewed

**Pull request closed without merging**
