### PR TITLE
RetroPlayer: Fix black screen on playback

### PR DESCRIPTION
**Pull request by garbear**
If the title of this PR looks familiar, it's because RetroPlayer broke yet again with the last VP update. This fixes the blank screen that shows when playing games.

## How Has This Been Tested?
Games play with video now.

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by thejims** [comment]
I think this was pulled in on the latest build.. if so still getting black screen.
pastebin: http://sprunge.us/FEFa

**Comment by garbear** [comment]
@thejims This problem seems to be RPi specific. I've pushed a fix. I haven't tested on an RPi, but I have evidence that it fixes the problem. @MilhouseVH can you make sure the updated PR is included in your builds? thanks!

**Comment by MilhouseVH** [comment]
> @MilhouseVH can you make sure the updated PR is included in your builds?

Will do.

**Comment by thejims** [comment]
Working great on RPi3 with the latest build! Ty!

**Comment by garbear** [comment]
jenkins build and merge

**Pull request merged**
