### PR TITLE
Remove view from tvshow_view

### PR DESCRIPTION
**Pull request by razzeee**
Splitted from the discussion of https://github.com/xbmc/xbmc/pull/8574 and/or https://github.com/xbmc/xbmc/pull/8502

Cross checked this vs the old view on dev machine and it seems to line up perfectly 

PING @phate89

### CODE REVIEW

**Comment by phate89** [comment]
IT doesn't. Same problem of the query in https://github.com/xbmc/xbmc/pull/8502
If you have a tv show with more than one folder (for example lost tv shows have episodes in smb://disk1/tvshows/lost and smb://disk2/tvshows/lost) You will get wrong file counts.
All the tv shows with 2 folders in my db with this query gets wrong totalcount

**Comment by Razzeee** [comment]
Sorry, I did mean to test that usecase, but messed it up. I corrected the query and tested it against that case. Looks promising so far.
It's even a little faster in sqlite and should remove the problems mysql had. But that needs to be tested and confirmed/benchmarked.

**Comment by phate89** [comment]
First of all you need a limit 1 after the subselects because if you have more than one path per tv show the query fails. 
I benchmarked it on my E450 and this query is slower than the original one.
I've got:
This query: 410 ms
The old query: 304 ms
The query without paths (my proposal): 254 ms

**Comment by Razzeee** [comment]
Your obviously right about the limit.

Not sure why you got that benchmark result. Is that MySQL?
And if it works to delete the paths without breaking anything and adding something more complicated, it should be done that way.

**Comment by phate89** [comment]
Yes I forgot to tellit.
It's mysql with profiling enabled so that's the mysql query execution time.
In SQLite is slightly faster than the old one but slightly slower than without the path.
About the path removal I was following jmarshallnz suggestion. Drop the path and see what's broken.
I found out path was used in 2 places:
*The parentPathID was used to fill in the video info in file view but this is easily solved with a specific function
*The strpath was used to check if the path in the database exists and is linked to a tvshow (https://github.com/xbmc/xbmc/blob/17fb8a3031135131545fa8e10d2f3194420f3634/xbmc/video/windows/GUIWindowVideoBase.cpp#L725-L730).

The 2nd one is the one I don't understand. If the FileItem has a videoinfotag and that videoinfotag has and it's from a tvshow it should be safe to assume it has videoinfo without checking in the database..

**Comment by Razzeee** [comment]
Yep, should be pointless. I'm also all for let's see where it fails and fix it then.

**Pull request closed without merging**
