### PR TITLE
xbmcaddon::Settings: remove use of dynamic exceptions

### PR DESCRIPTION
**Pull request by lrusak**
#19784 causes compilation warnings such as:
```
/home/lukas/Documents/git/xbmc/xbmc/interfaces/legacy/Settings.h:87:32: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   87 |   bool getBool(const char* id) throw(XBMCAddon::WrongTypeException);
      |                                ^~~~~
```

This PR removes the dynamic exception and uses normal exception handling through `try/catch` blocks.

Having the empty `catch` block seems a bit ugly but I'm not sure if there is anything else we want to do (log it?).

You can see the changes without white space changes [HERE](https://github.com/xbmc/xbmc/pull/20268/files?w=1)

### CODE REVIEW

**Comment by neo1973** [comment]
I don't really understand what throwing and then directly catching the exception should achieve here. This is also isn't was the dynamic exception specification was doing previously as far as I understand. What the dynamic exception specification was supposed to do was propagating only the listed exceptions up the stack and for all other exceptions call `std::unexpected` which per default calls `std::terminate`. The correct thing to do in my opinion is to remove the `throw(...)` and keep the rest as is.

**Comment by Montellese** [comment]
I fully agrre with @neo1973. Explicitly throwing an exception in a try-catch block which catches that exception makes no sense at all. Furthermore the exception is an essential part of the Python interface and MUST NOT be removed or caught by Kodi core. I'm not sure if the exception specification is relevant for generating the Python API documentation. If not it can be removed. If it is relevant we need to find another way to document the exception...

**Comment by garbear** [comment]
Throwing an exception in a try-catch block can be used as an RAII alternative to `goto` statements. For example: https://github.com/kodi-game/game.libretro/blob/483feb9/src/client.cpp#L61-L133

**Comment by lrusak** [comment]
Should I add logging or can I remove the boolean check completely?

**Comment by garbear** [comment]
I would keep the boolean check and add logging. Some static analyzers will warn on unused return values, and if we're forced to check then logging seems like a logical thing to do.

**Comment by garbear** [comment]
What @Montellese says is correct. The `throw` keyword in C++ is weird. When removing it, it doesn't mean you can't throw exceptions, it means you can throw *any* exception. And in this case, throwing an exception is correct.

The presence of the throw keyword is almost always detrimental, and doesn't do what the programmer intends. It acts as an allow-list, and if an exception isn't matched, then it's expected that the programmer will implement a custom handler. If no custom handler is provided, the program will hard-terminate immediately. This is rarely desired.

**Comment by lrusak** [comment]
Sorry @Montellese it wasn't clear to me what was being asked before. It's still not really clear to me why dynamic exceptions were used but that's fine. I tried to make a test program to demonstrate what it's doing: https://godbolt.org/z/nPnTxeG65

**Comment by lrusak** [comment]
can I get an ack on this?

**Review by garbear — APPROVED** [review]
Looks correct.

**Review by Montellese — APPROVED** [review]
Looks good now. Remember to squash the commits.

**Pull request merged**
