### PR TITLE
[gui] add System.HasInfoDialog

### PR DESCRIPTION
**Pull request by phil65**
Similar to HasModalDialog, but only triggers for one of the various infodialogs.

### CODE REVIEW

**Comment by phil65** [comment]
@xhaggi

**Comment by tamland** [comment]
What is this for? Just to create different animation for some dialogs?

**Comment by phil65** [comment]
basically just syntactic sugar, i dont like to clutter skin code with stuff like "!Window.isActive(movieinformation) + !Window.isActive(addoninformation) + !Window.isActive(pictureinfo) + !Window.isActive(musicinformation) + !Window.isActive(songinformation) + !Window.IsActive(pvrguideinfo) + !Window.IsActive(pvrrecordinginfo)"

**Comment by tamland** [comment]
Then I'm not sure this is the right approach. There's no such thing as 'info dialog' internally. From a technical standpoint it just adds IsInfoDialog->true to some arbitrary set of dialogs. It would better if this information was maintain separately as those IsFoo is just a hidden type check. If possible, in the skin code (if it's purely a skin problem to know if any of those dialogs are active).

**Comment by phil65** [comment]
Well, if you dont like it then I will close this. I´m just tryin to make life for skinners a bit easier, esp. considering that in the future infodialogs can get opened from all windows.
I disagree that it is an arbitrary set. From a skinners POV infodialogs are special because those are the only dialogs which carry listitem.foo infolabels. They also have different keymap behaviour.

**Comment by xhaggi** [comment]
> If possible, in the skin code (if it's purely a skin problem to know if any of those dialogs are active).

Agree.

@phil65 Is it possible to introduce a skin variable which checks all the windows and therefore it's true and defaults to false.

```xml
<variable name="HasInfoDialogs">
  <value condition"Window.IsActive(musicinformation) | Window.IsActive(movieinformation) | Window.IsActive(addoninformation)">true</value>
  <value>false</value>
</variable>
```

can you use the `$VAR[]` expression within a conditional?

**Comment by phil65** [comment]
No, I dont think that works. We might be able to use constants by adding "visible" etc to the list in GUIIncludes (not sure if taht works), but I still feel that this is something core should provide.

It´s less work for skinners this way, leads to nicer code and probably performs better than >6 separate bool checks.

**Comment by xhaggi** [comment]
As @tamland said it is a skin specific issue, not each skin will use the same logical part.

**Comment by xhaggi** [comment]
BTW using `$VAR` as expression within a conditional would makes sense IMO.

**Comment by phil65** [comment]
With that logic we could also kick Window.IsMedia...
Trust me, this is not an uncommon scenario and even becomes more useful in the future because of the mentioned changes which allow to use infodialogs everywhere.
Using VARS for conditionals doesnt feel very natural to me I must say.

**Comment by xhaggi** [comment]
it will reduce dupe code and that's what you want to achieve with your core changes.

**Comment by phil65** [comment]
That´s only part of it, I also want to take some burden of skinners for the future so that they dont have to update their expressions if we decide to add a new infodialog for example.
I also dont see why reducing dupe code should be done by the skinners if it is also easily solvable via core.
Anyways, I´m not in the mood to argue. Closed.

**Comment by Razzeee** [comment]
> > If possible, in the skin code (if it's purely a skin problem to know if any of those dialogs are active).

> Agree.

So let's make it as hard as possible for every skin to update? It's an fixed set of views, that every skin will need to know once 17 is out/context menu refactoring is in. So some will end up with bugs, when they screw up. And if we later add/remove views, EVERYONE  will have to adopt again. It would be basically a one line change for us in core.

**Comment by xhaggi** [comment]
not sure i understand what you are talking about. please explain it in detail.

**Comment by tamland** [comment]
I won't object to having it in core as a utility function it's that useful. But it has to be implemented as such. In a less intrusive way. I.e contained in a builtin or in infomanager.

**Comment by Razzeee** [comment]
@xhaggi 
like phil said, after we merge the context menu rework, skins will need a way of knowing if they are in a info dialog. So they will all need to do ```!Window.isActive(movieinformation) + !Window.isActive(addoninformation) + !Window.isActive(pictureinfo) + !Window.isActive(musicinformation) + !Window.isActive(songinformation) + !Window.IsActive(pvrguideinfo) + !Window.IsActive(pvrrecordinginfo)```
Like he does prior to https://github.com/xbmc/skin.estuary/commit/4482abb6a77fc196e37a1600bd289f36ddff3e8b
So when we add an info dialog for games on day, each skin will have to add that everywhere, to keep working in that regard. When we handle that addition it in core, it's a very small change and will keep these conditions unchanged in every skin.

@tamland 
agreed

**Comment by xhaggi** [comment]
@Razzeee sorry don't know much about the context menu rework and why it's necessary for a skin to know if an info dialog is on top.

**Comment by phil65** [comment]
that boolean wasnt about whether an infodialog is on top, but whether an infodialog is active.
If anyone wants to come up with a different implementation, feel free to do it.

**Pull request closed without merging**
