### PR TITLE
[Backport][Android] pause audio playback when headphone is disconnected

### PR DESCRIPTION
**Pull request by oldk1331**
## Description
This is backport of #17030.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
Jenkins build this please

**Review by phunkyfish — APPROVED** [review]
LGTM

**Comment by matthuisman** [comment]
I think this may be causing pausing when switching framerates on Android.
https://github.com/peak3d/inputstream.adaptive/pull/440#issuecomment-626327538

After googling "ACTION_AUDIO_BECOMING_NOISY" I found
https://stackoverflow.com/questions/10160349/action-audio-becoming-noisy-not-being-captured

"The NOISY filter gets triggered when audio output sources change, and might cause funky stuff."

This commit I see was back-ported - is it in current Android Leia stable (playstore) Or only Leia nightly?

**Comment by fuzzard** [comment]
Leia Nightly. 18.6 was released Feb 29

**Comment by DaveTBlake** [comment]
>This commit I see was back-ported - is it in current Android Leia stable (playstore)?
Or only Leia nightly?

Leia nightly, v18.7 is not released yet (but happening soon) - see the milestone for what version a PR is merged into.

**Comment by matthuisman** [comment]
thanks guys - I read somewhere about a possible 18.6.1 hotfix for android to fix the Android 10.0 issue - so wasn't sure if that had been pushed out with some other commits (like this one) snuck in.  I'll get the user to confirm his kodi version and try other versions.

**Comment by matthuisman** [comment]
User has confirmed that pausing does not happen on 18.6 but does happen on 18.7 nightly. Is there anyway to get a build of 18.7 without this commit for him to check? 

It happens with a frame rate change on DV or HDR10 (and maybe other formats). Only if the change happens a few seconds after playback begins.

**Comment by matthuisman** [comment]
Oh. Wasnt sure Jenkins would build for me

**Comment by matthuisman** [comment]
Have made a 18.7 build without this commit and user has confirmed he no longer has the issue.

Therefore, a have made a pull request to revert
https://github.com/xbmc/xbmc/pull/17868

**Comment by phunkyfish** [comment]
Please contact the original PR author first. There may be a simple workaround where a revert is not required.

**Comment by matthuisman** [comment]
I mentioned that on the pr to  revert. Wasn't sure how close 18.7 is (sounded close).  

@oldk1331
Any thoughts how this can be changed so doesn't cause pause on frame rate switches?

**Comment by oldk1331** [comment]
Hi, how can I test this issue you mentioned?  Is there a test sample? Do I use original kodi or your fork?

**Comment by matthuisman** [comment]
To reproduce the issue - use either Leia or Matrix nightly on Android.
Set frame-rate switch time to 6 seconds.
Play content with different frame-rate - observe kodi pauses after the framerate switch

You can also get same behaviour when content is playing, going into kodi settings and changing frame-rate

**Comment by oldk1331** [comment]
I don't see these options you mentioned, where are they? And where can I find a sample with different frame-rate?

**Comment by matthuisman** [comment]
Are you using a phone? Pretty sure frame-rate is not able to be changed unless using android TV platform

**Comment by oldk1331** [comment]
Okay, this feature is not for TV anyway, adding a check for TV can workaround this bug you mentioned.  Still I wonder if people will have the same problem when they watch videos with different frame-rate on Android phones.

**Comment by matthuisman** [comment]
I couldnt test on phone as mine fixed fps. 
Maybe you could check for HDMI used?

**Comment by oldk1331** [comment]
This patch simply excludes TV, can you test it?

````
diff --git a/xbmc/platform/android/activity/XBMCApp.cpp b/xbmc/platform/android/activity/XBMCApp.cpp
index 48a26d1f1c..21df502282 100644
--- a/xbmc/platform/android/activity/XBMCApp.cpp
+++ b/xbmc/platform/android/activity/XBMCApp.cpp
@@ -1051,7 +1051,7 @@ void CXBMCApp::onReceive(CJNIIntent intent)
   }
   else if (action == "android.media.AUDIO_BECOMING_NOISY")
   {
-    if ((m_playback_state & PLAYBACK_STATE_PLAYING) && (m_playback_state & PLAYBACK_STATE_AUDIO))
+    if ((m_playback_state & PLAYBACK_STATE_PLAYING) && (m_playback_state & PLAYBACK_STATE_AUDIO) && !(getPackageManager().hasSystemFeature("android.software.leanback")))
       CApplicationMessenger::GetInstance().PostMsg(TMSG_GUI_ACTION, WINDOW_INVALID, -1,
                                                    static_cast<void*>(new CAction(ACTION_PAUSE)));
   }
````

**Comment by matthuisman** [comment]
i suspect it will work, but is it the correct thing to do?
Maybe also just do **&& !(m_hdmiSource)** instead

I'm sure some phones may allow framerate switching?
If so, the issue will still happen for them

What do you think about this (use ACTION_HEADSET_PLUG instead?)
https://stackoverflow.com/questions/10160349/action-audio-becoming-noisy-not-being-captured/14511239#14511239

**Comment by DaveTBlake** [comment]
Can I just check the details/history here
-An improvement was raised against master.
-For some reason, **despite not being a fix** but an improvement, it was backported
-There is now another PR against master to revert this improvement because it causes a regression
-There is discussion here on the backport about what functionality is required and how best to implement it.

If I can get jenkins to behave 18.7 will be released, and this PR is in it. If the "improvement" that should never have been backported does cause users a regression then they will just have to live with it. It is one reason why **improvements should not be backported**, only essential fixes.

The discussion of what to do about the regression belongs on the master PR, not here.

**Comment by matthuisman** [comment]
if 18.7 is about to be released, the original PR in Leia needs to be reverted.

Otherwise, there is going to be MANY users coming in with "why does my stream pause"
Basically any non-android mobile users using framerate switching (lots).

The regression has been confirmed by multiple users and a build with this PR (reverting) fixes it.

Sorry, PRs to revert other PRs got a bit confusing.
I haven't done a PR to revert on Master as I was advised to give the user a chance to make changes.

**Comment by DaveTBlake** [comment]
OK, so basically this really should never have been backported. Mistakes happen, and in this case revertion on Leia is the simple way to resolve it.

**Comment by matthuisman** [comment]
Yeh, I just assume it looked safe at the time.
Who would know frame-rate switching would trigger it.

Even if it sat only in Matrix, it may not have been found until Matrix stable.
All depends on enough users using the build to find these sort of bugs.

So in a way, it being back-ported helped us find it quicker...

**Comment by DaveTBlake** [comment]
>All depends on enough users using the build to find these sort of bugs.

Indeed, but that could easily become an arguement for not doing bug point releases and forcing users to try master even just to get bug fixes.  

Can you shift discussion of replacing/reworking the improvement this tried to make to the PR on master #17030 . Team members can trigger test builds if needed for user testing.

**Pull request merged**
