### PR TITLE
[PVR][Estuary]Remove duplicated EpgEventTitle from PVR lists

### PR DESCRIPTION
**Pull request by emveepee**
## Description

Remove duplicated EpgEventTitle from PVRListItemLayout

Add condition to compare the main list left side label to the EpgEventTitle so that the information is not duplicated

## Motivation and context

Reduces screen clutter an makes screens easier to read 

## How has this been tested?

Tested on Windows with pvr.nextpvr with EPG, Recording, Search and Timer lists.

## What is the effect on users?

Improved usability on screens where it is used (eg the timer screen in pvr.nextpvr)

## Screenshots (if appropriate):

Before
346304949-722bcb4e-9058-40b5-a520-d2a0bfeb986c

After
image

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [x] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by ksooo** [comment]
+1 from me for the concept. Code chat should be reviewed by @Hitcher or @jjd-uk.

**Comment by jjd-uk** [comment]
Just a quick ack to say I've seen the ping, I don't have a great deal of free time but I'll try and take a look over the weekend.

**Comment by emveepee** [comment]
@jjd-uk at your convenience.  Although it may not able to all PVR,  the NextPVR backend names timers the same as the show/movie and as shown in post #1 it gets very cluttered.  The download size is very long name will be truncated.

Attached is a sample XML file for pvr.demo to use to show as below.

[demo.zip](https://github.com/user-attachments/files/16180862/demo.zip)  

image

**Review by jjd-uk — APPROVED** [review]
LGTM

**Comment by emveepee** [comment]
@jjd-uk @ksooo I need to revert this PR it seems that the search uses the channel name and not  the label

```
	<variable name="PVRMySearchLabel1Var">
		<value condition="!String.IsEmpty(ListItem.ChannelName)">$INFO[ListItem.ChannelName]</value>
		<value>$INFO[ListItem.Label]</value>
	</variable>
```
and not the label.  

Personally I don't see why channel name is given priority when searching for a show but that is how it is designed.

**Comment by ksooo** [comment]
> I need to revert this PR

@emveepee sorry, no idea what you are talking about. Can you please say what exactly is broken from user's POV after your last PR?

**Comment by ksooo** [comment]
Now I see the problem. Yes, this happens if you make assumptions for the sub label what the main label is. As we can see, comparing always with ListItem.Label is wrong. However, no need to revert. Just come up with a follow-up PR to fix this. And please, solution is not to change the main label for search lists. This not fixing the root cause of the issue.

**Comment by emveepee** [comment]
There doesn't appear to be a trivial solution since $PARAM[label1] doesn't work in variables and I'd have to have label3 set for all the list that use it.  I can change it but I can live with the dupication.

For me I don't care about which channel it is on since I am looking for show in date order and I actually want the title to be the left side (not the search) The fact that the search could be in the description makes it even more important the title is given importance.   Here when I search for dragon (looking for house of the dragon) this is not as useful (just commenting out the channel name.

image

as this (as I said the channel icon gives me the channel at glance

image

**Comment by ksooo** [comment]
We cannot rely on the channel icon, as it is optional. As you see, things are a bit more complicated. I think we actually should revert your PR.

**Comment by emveepee** [comment]
> We cannot rely on the channel icon, as it is optional. As you see, things are a bit more complicated.

True, although I still prefer the title over the channel name since the channel is not important to me, the show is.   Kodi is full of choices there is no one sized fits all solution but I am happy to change this since the theory is wrong.  I do have a PR coming that can be used to fix this or modified to revert it if necessary.

**Comment by ksooo** [comment]
Alright, I will check whether this PR introduces another regression (see issue above). If yes, I will revert that PR (for now).

**Pull request merged**
