### PR TITLE
Fix musicbrainz resolution with python based scrapers

### PR DESCRIPTION
**Pull request by notspiff**
This fixes mbrainz resolution using python based scrapers. Previously it tried to load the py file as xml, then crashed and burned.

@ronie

### CODE REVIEW

**Comment by ronie** [comment]
thx! works as expected.

i do have some additional questions on the scraping process:
http://forum.kodi.tv/showthread.php?tid=306218
^ ping @DaveTBlake as well

**Comment by ronie** [comment]
jenkins build this please

@notspiff is that unrelated commit supposed to go in as well?

**Comment by notspiff** [comment]
it quells yet another warning introduced in the pvr code. if you insist i
can submit it separately but seemed like more hassle than it was worth.

>

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by DaveTBlake** [comment]
Late in the day I know but the `CScraper::ResolveIDToUrl` change seems an odd thing to do.

For the XML music scrapers  the "ResolveIDToUrl" function called by `CScraper::ResolveIDToUrl` is used to create the URL for that artist or album mbid, it gets put into the scraper list of albums or artists, and is subsequently used to get the details. It does not make any server requests, or validate the mbid in any way, it just does some string manipulation.

The Python music scrapers "getdetails" action, called from PythonDetails, is simply passed the mbid. So why need the Python scraper to have a "resolveid" action to put a fake album or artist into the list so that a count check avoids lookup by name etc. ?

It makes more sense to me to change `CMusicInfoScanner::DownloadAlbumInfo` and `DownloadArtistInfo` to check `preferredScraper->IsPython()` and act accordingly. Or am I missing something?

**Comment by akva2** [comment]
as i said in the description - i have gone through stupid hoops to operate within the current scraper system. it does not make sense, it's just to map to the old.

**Comment by DaveTBlake** [comment]
Fair enough :)

I have also discovered that XML music scrapers "ResolveIDToUrl" is not just string parsing. It takes the Musicbrainz *release* id that Kodi has from music file tags (strMusicBrainzAlbumID in the album table), and looks up  the Musicbrainz *release group* id that is needed to look up the album in Fanart.TV and TADB. Python scraper needs to do the same.

**Pull request merged**
