### PR TITLE
Update MusicOSD controls alignment

### PR DESCRIPTION
**Pull request by DaVukovic**
Regarding to this:

https://github.com/xbmc/xbmc/pull/9094

and saw, that the alignment wasn't correct, I guess adding those lines again might help.

### CODE REVIEW

**Comment by Razzeee** [comment]
@HitcherUK

**Comment by phil65** [comment]
If it becomes too complicated with those placeholders then it might be worth it to use separate grouplists (one left-aligned, one right-aligned) for this.

**Comment by HitcherUK** [comment]
@Razzeee Confirmed fix. OK to merge.

**Comment by Razzeee** [comment]
Thank you @1977David

**Comment by 1977David** [comment]
@Razzeee 

yw ;)

**Pull request merged**
