### PR TITLE
Disable autoscrolling while on screensaver and while opening streams.

### PR DESCRIPTION
**Pull request by mcaptur**
Taken From: anaconda anaconda@menakite.eu Date: Thu, 11 Sep 2014 21:30:43 +0200
Been used for over a year in RPi (newclock)

### CODE REVIEW

**Comment by FernetMenta** [comment]
The implementation is not very good because of circular dependencies. GUI is owned by application and should not use those crappy globals to poll application status. Instead application should instruct GUI how to behave.

**Comment by anaconda** [comment]
The reason this is only in newclock5 branch is because it was rejected upstream (#5363).

**Comment by alan-ml** [comment]
It would be great if this makes it to the next stable release, I for one will enable my screensaver once this is in.
Its not just about reducing CPU usage, but considering the number of Kodi users, this little change will save many watts worldwide.

**Comment by MartijnKaijser** [comment]
It's safe to say this patch won't get back in

**Pull request closed without merging**
