### PR TITLE
[cmake] add libplatform to kodi-platform depends

### PR DESCRIPTION
**Pull request by wsnipex**
kodi-platform needs (lib)platform since https://github.com/xbmc/kodi-platform/pull/5

In the longer run, this should probably be moved to kodi-platform itself as dependency.

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
This should fix the addons only build trigger aswell right?

**Comment by wsnipex** [comment]
no idea, didn't even know its broken

**Comment by ksooo** [comment]
@wsnipex #7060

**Comment by ksooo** [comment]
Oops, ment #7065, sorry.

**Comment by wsnipex** [comment]
guess all pvr addons need bumping.

lets try the addons trigger:
jenkins build addons please

**Comment by hudokkow** [comment]
I'm working on bumping all PVR addons. Should take me one more day.

**Comment by Montellese** [comment]
The addons trigger should work with the current binary addons and the current `kodi-platform` version but either bumping `kodi-platform` (as done by this PR) or any of the PVR addons (as done by the other PRs) will result in broken builds.

**Comment by Montellese** [comment]
Question is whether we want to bump this now or wait for Isengard to be released. It's not a fix AFAICT.

**Comment by hudokkow** [comment]
Beta2 is due in 2 days. IMO this, https://github.com/xbmc/xbmc/pull/7065 and other PVR add-on bump PR(s) should go in only after master is open for J****

**Comment by stefansaraev** [comment]
> Beta2 is due in 2 days. IMO this, #7065 and other PVR add-on bump PR(s) should go in only after master is open for J****

I disagree here.

if you wait for J***, then the cec bump / platform split was too late. but wellll it's in. that means all those pvr clients are in trouble (must revert sh** for isengard)

IMO sooner this is pulled, more time for addons to be bumped, more happier the addon devs (and distributors) are

**Comment by Montellese** [comment]
If the libCEC bump causes issues at this point in the release cycle IMO it must be reverted. We are in beta 2 and the consensus was that we don't allow any API changes starting with beta 1. Changing the way a library has to be used / integrated is an API change.

**Comment by FernetMenta** [comment]
this should go in asap. I can't build vnsi without this, means it does build with this change.
@hudokkow I am on vnsi

**Comment by hudokkow** [comment]
OK. That's 2 add-ons taken care of. I'll bump the remaining tonight or tomorrow morning at the latest.

**Comment by Montellese** [comment]
@FernetMenta: Did you try with reverting the libCEC changes?

**Comment by FernetMenta** [comment]
@Montellese it is not only the libCEC changes, it is kodi-platform as well which has a related pr merged. further, platform at pulse-eight repo already has a fix for platform I submitted because of discontinued kodi-platform. imo it is less pain going forward with this than a revert.

**Comment by Montellese** [comment]
The version of `kodi-platform` we use hasn't been bumped in 6 weeks. And `kodi-platform` isn't discontinued.

**Comment by FernetMenta** [comment]
the platform sources have been gone from kodi-platform https://github.com/xbmc/kodi-platform/commit/6cfabd8b94e769a0485fd06a7e62dcdc3bee7b29

you would need to revert a whole bunch of changes on kodo-platform repo in order to submit a fix for the platform sources which is required.

**Comment by opdenkamp** [comment]
and then you'll run into new issues because libCEC uses a different library, in both the new and old versions. this should have been done right after the cmake pr got merged in, and I warned about it back then.

will take a look at the build issues

**Comment by opdenkamp** [comment]
and re changes in the add-ons, it's just some changed paths and linking another lib, which @hudokkow was taking care of because I was stupid enough to delete the dir containing all of that before pushing.

**Comment by opdenkamp** [comment]
right so @hudokkow is updating the add-ons now, so it'll all be fixed again tonight

**Comment by hudokkow** [comment]
https://github.com/xbmc/xbmc/pull/7072

**Comment by wsnipex** [comment]
I picked https://github.com/xbmc/xbmc/pull/7072
jenkins build addons please

**Comment by ksooo** [comment]
@wsipex you also need #7065 (for pvr.hts libplatform change) in order to have a chance for a successful junkins build.

**Comment by wsnipex** [comment]
picked hts as well

**Comment by wsnipex** [comment]
jenkins build addons please

**Comment by wsnipex** [comment]
added vnsi bump and squashed the hts as well, I hope you don't mind @ksooo

jenkins build addons please

**Comment by hudokkow** [comment]
Nice. Was about to do it but you saved me some work. Thanks.

**Comment by ksooo** [comment]
@wsnipex np

**Comment by hudokkow** [comment]
iOS, OSX and Win didn't liked it.

**Comment by wsnipex** [comment]
@opdenkamp, IOS fails:
In file included from /Users/Shared/jenkins/workspace/BINARY-ADDONS/platform_label/ios/tools/depends/target/binary-addons/iphoneos8.1_armv7-target/build/depends/include/platform/util/../os.h:37:
/Users/Shared/jenkins/workspace/BINARY-ADDONS/platform_label/ios/tools/depends/target/binary-addons/iphoneos8.1_armv7-target/build/depends/include/platform/util/../posix/os-types.h:53:10: fatal error: 'IOKit/IOCFPlugIn.h' file not found
#include <IOKit/IOCFPlugIn.h>

pvr.demo, pvr.dvbviewer. pvr.njoy, pvr.vuplus fail on OSX and on Windows a whole lot fails

**Comment by hudokkow** [comment]
I was having trouble building demo, dvbviewer, njoy, vuplus and wmc yesterday night at home. Assumed it was something with my env because they built fine in an Ubuntu 14.10 VM I keep to test stuff.
This is the error I was getting -> http://pastebin.com/wNaEE625

The common thing I found is #include "kodi/util/XMLUtils.h"

**Comment by opdenkamp** [comment]
@hudokkow you're building against an old version of the kodi-platform lib

@wsnipex looks like the add-ons are missing some include dirs on those platforms for some reason, will check

**Comment by opdenkamp** [comment]
https://github.com/Pulse-Eight/platform/commit/68f841876d196ac0bfcffa6ead034ce73e397dad fixes the windows issue. will take a look at the other ones tomorrow and include it here

**Comment by opdenkamp** [comment]
@FernetMenta or @Memphiz 
```
In file included from /Users/Shared/jenkins/workspace/BINARY-ADDONS/platform_label/ios/tools/depends/target/binary-addons/iphoneos8.1_armv7-target/build/depends/include/platform/util/../os.h:37:
/Users/Shared/jenkins/workspace/BINARY-ADDONS/platform_label/ios/tools/depends/target/binary-addons/iphoneos8.1_armv7-target/build/depends/include/platform/util/../posix/os-types.h:53:10: fatal error: 'IOKit/IOCFPlugIn.h' file not found
#include <IOKit/IOCFPlugIn.h>
```
it looks like it's missing an include path when building kodi-platform, but I can't figure out what changed that's making this happen. the `-framework CoreVideo -framework IOKit` stuff is included in both libplatform and kodi-platform too.

any idea what's missing here?

**Comment by Memphiz** [comment]
Can't see anything in the build output - need to compile with VERBOSE and see what the compile flags are. If we are sure that this really is defined:

https://github.com/xbmc/kodi-platform/blob/master/CMakeLists.txt#L31

It should pass the right flags...

**Comment by opdenkamp** [comment]
yeah that framework stuff is in kodi-platform, libplatform and libCEC. but isn't that just passed to the linker? don't we have to define some include directory for the compiler?

**Comment by Memphiz** [comment]
Those should by already set via -isystem or -isomethingelseidon'tremember

**Comment by Memphiz** [comment]
-isysroot takes care that the standard things from the sdk are found

**Comment by opdenkamp** [comment]
okay, but do you know why this shows up now and not before the libs were split? I don't see any of that in the CMakeLists.txt from before the split platform PR got merged https://github.com/xbmc/kodi-platform/blob/48bdd985b843353eec5804e4dbab2dc8f2b4b13e/CMakeLists.txt

should I just add `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -isysroot")` in the darwin/ios block?

**Comment by Memphiz** [comment]
I don't know why this happens now. TBH i don't know atm where the -isysroot comes from. You can't just add it to your CMakelists.txt because it depends on the SDK used for compilation.

ATM on jenkins its set to:

-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk 

Because we build with ios 8.1 sdk for example. It is there somewhere in our cmake buildsys and somehow doesn't make it into libplatform. I hope @wsnipex knows where this comes from and how its ment to be spread into the buildsys of cmake.

**Comment by wsnipex** [comment]
https://github.com/xbmc/xbmc/blob/master/tools/depends/target/Toolchain_binaddons.cmake.in
https://github.com/xbmc/xbmc/blob/master/tools/depends/xbmc-addons.include#L2

**Comment by opdenkamp** [comment]
right thanks, will fix it up tonight and double check windows runtime. we've made really nice spaghetti build system ;)

**Comment by Memphiz** [comment]
lol - nah i think this lies in the complexity of providing/syncing/maintaining binary addons ;)

**Comment by opdenkamp** [comment]
damned binary add-ons. who needs that crap?

**Comment by wsnipex** [comment]
our rabbit hole is just way deeper then others:
autotools calling cmake, which calls other cmake and autotools again, with serveral layers of that

**Comment by opdenkamp** [comment]
aka spaghetti ;-)

**Comment by wsnipex** [comment]
sure, we should just throw out autotools

**Comment by opdenkamp** [comment]
github doesn't allow me to create a pr to your branch for some reason: https://github.com/opdenkamp/xbmc/commit/09fa0b6c37f1922e2c7bb9a0dbfd1c4ac2d28ad4

**Comment by wsnipex** [comment]
picked. jenkins build addons please

**Comment by wsnipex** [comment]
indeed, missed that.
jenkins build addons please

**Comment by wsnipex** [comment]
@opdenkamp same error as before, guess you didn't test it?

**Comment by opdenkamp** [comment]
most add-ons build now, and I can't test osx/ios. will take a look at the ones that are still failing in the evening.

**Comment by Memphiz** [comment]
I am planning to look into it this evening...

**Comment by Memphiz** [comment]
@opdenkamp those outputs are this PR with platform master (untagged 1.0.8)

https://dl.dropboxusercontent.com/u/30371861/platform-1.0.8-ios.txt
https://dl.dropboxusercontent.com/u/30371861/platform-1.0.8-osx.txt

**Comment by opdenkamp** [comment]
@wsnipex @FernetMenta I've rebuilt libCEC on Windows against the latest version of the platform lib and included the latest changes in the lib itself (latter don't affect Windows). Tested both with and without an adapter attached and no issues (tested on 8.1 64 bits): https://github.com/opdenkamp/xbmc/commit/248ef9abfe7a2b7befd43da0bca13f465e9f4a20

@Memphiz will look at the ios and osx stuff next

**Comment by opdenkamp** [comment]
@hudokkow the add-ons that failed to build now are not linking `${kodiplatform_LIBRARIES}`
e.g. https://github.com/kodi-pvr/pvr.vuplus/blob/master/CMakeLists.txt#L22
since only a couple of them use XmlUtils, only those fail to build now

**Comment by hudokkow** [comment]
I really don't like XMLUtils... ;)

I'll update tonight and re-open https://github.com/xbmc/xbmc/pull/7072

@wsnipex while I'm at it, should I update remaining add-ons to fix debian packaging like you did at https://github.com/kodi-pvr/pvr.vdr.vnsi/commit/2c0d3d19be34d076d815b5e0169c9c577425969c ?

**Comment by opdenkamp** [comment]
thanks. in this PR, libplatform needs a bump to 1.0.8 too (will create a PR) and with that, https://github.com/opdenkamp/xbmc/commit/248ef9abfe7a2b7befd43da0bca13f465e9f4a20 and the rest of this PR, everything should build and run again... :)

**Comment by wsnipex** [comment]
@hudokkow yes, that'd be great.
@opdenkamp I uploaded 1.0.8 to mirrors and bumped it

**Comment by Memphiz** [comment]
i see the light at the end of the tunnel!!! :)

**Comment by hudokkow** [comment]
Don't follow the light, @Memphiz. I highly doubt there's beer in heaven... ;) Cookies, maybe. Beer, probably not.
Completely forgot about Bayern x Barcelona so this is going to be pushed a few hours. Good luck to Bayern.

**Comment by hudokkow** [comment]
@wsnipex please pick https://github.com/hudokkow/xbmc/commit/2901acd862742cb01ebcf4ecccb888557f8325d4

**Comment by wsnipex** [comment]
thanks, picked and squashed
jenkins build addons please

**Comment by wsnipex** [comment]
meh, windows is still not happy

**Comment by opdenkamp** [comment]
yeah was just checking, looks like stdio isn't included in a header (or Windows has it elsewhere):
```
c:\jenkins\slave\workspace\binary-addons\platform_label\win32\project\cmake\addons\output\include\platform\sockets\../windows/os-socket.h(233) : error C3861: 'sprintf': identifier not found
```

**Comment by opdenkamp** [comment]
yeah it's missing, will update and tag 1.0.9

**Comment by opdenkamp** [comment]
@wsnipex https://github.com/opdenkamp/xbmc/commit/3dd6344c34ee7105cf93dee6a0519693a44c6f75

**Comment by wsnipex** [comment]
jenkins build addons please -_-

**Comment by opdenkamp** [comment]
oh ffs @hudokkow looks like some audio decoders need the same treatment :(
```
[100%] Building CXX object CMakeFiles/audiodecoder.modplug.dir/src/ModplugCodec.cpp.obj
ModplugCodec.cpp
c:\jenkins\slave\workspace\BINARY-ADDONS\platform_label\win32\project\cmake\addons\output\include\kodi/libXBMC_addon.h(35) : fatal error C1083: Cannot open include file: 'dlfcn-win32.h': No such file or directory
```

**Comment by wsnipex** [comment]
https://www.youtube.com/watch?v=s7KBIMFlRRY

**Comment by opdenkamp** [comment]
lol yeah this should have been done when kodi-platform was created so we wouldn't have had to fix up every single add-on using it ;-)

**Comment by Memphiz** [comment]
hahaha

**Comment by hudokkow** [comment]
@wsnipex please also pick https://github.com/hudokkow/xbmc/commit/ca7c200ed77b23de04a55239edb6e6efd29cc560 to solve a couple of issues with RPi

audio decoders are under @notspiff account
spiff, will you take care of the addons side and I'll update on Kodi's side?

**Comment by notspiff** [comment]
everything that needs to be taken care of has already been done (no overlap with the decoders used by upstream).

**Comment by wsnipex** [comment]
@opdenkamp this isn't an problem on the audiodecoders, but on (kodi-)platform side.
the error you see was already fixed https://github.com/notspiff/audiodecoder.nosefart/commit/dedb78b03e6298445f899c9544120d4f711240d0

**Comment by opdenkamp** [comment]
well this is what the code is doing now: https://github.com/wsnipex/xbmc/blob/platform/addons/library.xbmc.addon/libXBMC_addon.h#L35
which is sitting in the same directory as the header now, but I guess it's not been copied or updated then.

the alternative is using https://github.com/Pulse-Eight/platform/blob/master/src/windows/dlfcn-win32.h which got moved from kodi-platform to libplatform, and the line that you linked shows that it doesn't use libplatform but only kodi-platform

**Comment by Montellese** [comment]
To fix that win32 problem IIRC you need to add the "windows" subdirectory to the list of include directories of platform.

**Comment by Montellese** [comment]
Ah just saw that it's already there in platform. In that case the platform include dirs need to be added to the addons.

**Comment by wsnipex** [comment]
shouldn't this be encapsulated in kodi-platform instead of adding more depends to addons?

**Comment by opdenkamp** [comment]
unless you want to add an include directory to the compiler flags that points to `platform/windows`, these will need updating

**Comment by hudokkow** [comment]
soo... back to what I asked earlier? update add-ons?

**Comment by opdenkamp** [comment]
I'd say yes

**Comment by MartijnKaijser** [comment]
any chance of this getting in this weekend? It's kinda holding up beta or am i mistaken that this isn't needed?

**Comment by opdenkamp** [comment]
I assumed that @hudokkow was picking this up, but I can do it too on Sunday. You could merge this one now and do the 3 remaining audio decoders separately if you're in a rush, as this fixes most things already.

**Comment by hudokkow** [comment]
What needs to be done? Updating audio decoders?

**Comment by hudokkow** [comment]
jenkins build addons please

**Comment by opdenkamp** [comment]
yes, audio decoders' dlfcn includes

**Comment by hudokkow** [comment]
All green: http://jenkins.kodi.tv/job/BINARY-ADDONS/198/ using https://github.com/hudokkow/xbmc/commits/testaudio

Top commit is temp while spiff doesn't merge PRs.

**Comment by MartijnKaijser** [comment]
awesome, thx :)
now waiting for him to merge the PRs

**Comment by hudokkow** [comment]
@wsnipex please pick https://github.com/hudokkow/xbmc/commit/26d6ceef7b89ad819e51e0eafbacd632f7e10875 and we should be ready to go... finally! ;-)

**Comment by wsnipex** [comment]
jenkins build addons please

**Comment by MartijnKaijser** [comment]
jenkins build addons please

**Comment by wsnipex** [comment]
jenkins build addons please

**Comment by MartijnKaijser** [comment]
we have green light

**Comment by hudokkow** [comment]
@MartijnKaijser, from my part, the honour is yours. Beta is waiting ;-)

**Pull request merged**
