### PR TITLE
[Estuary] MusicInfo - Fix play button & navigation

### PR DESCRIPTION
**Pull request by ronie**
2 Changes:
- Show Play button for non-library items
- Fix (left) navigation to the Play button

@DaveTBlake

### CODE REVIEW

**Comment by DaveTBlake** [comment]
Thanks for this @ronie 
Play button is shown for non-library songs.
Left navigation now works fine.

Unfortunately the script to play the song doesn't work when the song isn't in the library. Is that something you can fix too? It should be possible to play the music file by file name when dbid = -1

**Comment by ronie** [comment]
thx for giving it a shot @ksooo 
i've added an additional line of code for non-library items, they should play fine now.

**Comment by ronie** [comment]
sorry... meant to ping @DaveTBlake

**Comment by DaveTBlake** [comment]
>i've added an additional line of code for non-library items, they should play fine now.
Thanks @ronie but I am missing where you have done that. What do I pull in to test?

**Comment by DaveTBlake** [comment]
OK, figured it out (with jjd's help) sorry for the noise @ronie 
Tests out fine, many thanks for this.

**Pull request merged**
