### PR TITLE
[Leia] [test] TestCPUInfo: remove useless test as we cannot guarantee that they exist

### PR DESCRIPTION
**Pull request by candrews**
## Description

Backport https://github.com/xbmc/xbmc/pull/17290 and https://github.com/xbmc/xbmc/pull/17320 to Leia

## Motivation and Context

These tests fail under some circumstances so it would be great to backport the fix for those failures to Leia.

## How Has This Been Tested?

Ran tests, they pass.

## Screenshots (if appropriate):
N/A

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by candrews** [comment]
@lrusak since you're the original author of the 2 PRs I'm backporting here, can you please take a look?

**Comment by lrusak** [comment]
Probably fine. I’m not in charge of backports though. I’m also not sure if there will be another Leia release. @DaveTBlake knows best.

**Comment by DaveTBlake** [comment]
I propose we do 18.8 as a final point release to tidy things up (Android patches for 18.7 got a bit messy and it would be nice to draw a clear line.). However some feel that doing so many point releases is sending the wrong signals, so I'll be seeking team confirmation.

As for this, as it is not something that will have any impact on normal users I'm not sure it matters if it is backported or not. Strictly it is a fix, so qualifies, and since @candrews has been enthusiastic enough to raise it then get greens fro jenkins and it can be merged.

**Comment by DaveTBlake** [comment]
jenkins build this please

**Pull request merged**
