### PR TITLE
[videodatabase] made some SQL statements more readable

### PR DESCRIPTION
**Pull request by Rechi**
replaced implicit joins with explicit joins and some 'join on' with 'join using'

### CODE REVIEW

**Comment by mkortstiege** [comment]
Looks good. @xhaggi since you're more familiar with SQL mind having a look as well?

**Comment by Montellese** [comment]
Hm looks like my comment from yesterday on a commit was lost or I didn't submit it.

When I first learned about `JOIN USING` I found it very nice because it saves a lot of obvious typing. But after using it for a while I noticed that it was causing confusion when being used with multiple `JOIN`s in the same SQL query because it's not obvious anymore which tables are being involved.

An example from this PR would be
```
SELECT path.strPath, files.strFileName FROM path INNER JOIN files USING(idPath) INNER JOIN movie USING(idFile) WHERE movie.idMovie=%i ORDER BY strFilename
```
Is the `INNER JOIN movie USING(idFile)` happening with the `path` table or the `files` table? If you know the database structure you know it can only be with the previously joined `files` table but if you don't you have no clue.

**Comment by xhaggi** [comment]
@Montellese fully agree, it's more clear if using ON instead of USING. The first commit is fine by me.

**Comment by Montellese** [comment]
@xhaggi: The first commit already contains a lot of `JOIN USING`.

**Comment by xhaggi** [comment]
uhhh sorry thought it only replaced implicit joins with explicit joins.

**Comment by Rechi** [comment]
Should I only replace implicit joins with explicit joins by using 'JOIN ... ON ...'?

**Comment by xhaggi** [comment]
sure that makes sense

**Comment by Rechi** [comment]
I have replaced USING(...) with ON ...

**Comment by Montellese** [comment]
Thanks @Rechi. jenkins build this please

**Pull request merged**
