### PR TITLE
[backport][subtitles] decode html escape characters

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

As title

## Motivation and Context

Backport of https://github.com/xbmc/xbmc/pull/17085

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by DaveTBlake** [comment]
This fixes issue #15365 for Leia

**Comment by DaveTBlake** [comment]
@peak3d I assume that you are happy for this to be applied to Leia?

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by Essam311** [comment]
@DaveTBlake Any chance for merging the PR before the release of Kodi Leia 18.7?

**Comment by CastagnaIT** [comment]
It has already been widely tested
and InputStream Adaptive is now aligned for the most part with the latest Matrix branch changes
so it can be merged quietly

**Review by phunkyfish — APPROVED** [review]
LGTM

**Comment by phunkyfish** [comment]
jenkins build this please

**Comment by phunkyfish** [comment]
Win32 build error unrelated

**Pull request merged**
