### PR TITLE
fixed: Crash caused by starting dvd media detection before windowmanager is running

### PR DESCRIPTION
**Pull request by arnova**
Regression introduced by c4369136904593ff85763199b88ac526ff6a5c78

### CODE REVIEW

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Review by howie-f — APPROVED** [review]
confirm moving DetectDVDType to stage three fixes the crash

**Comment by arnova** [comment]
ping @fuzzard

**Comment by fuzzard** [comment]
If it fixes something, go nuts

**Comment by howie-f** [comment]
thanks @arnova. was just about to start hunting it down when i saw you already made it :)
that is your button

**Pull request merged**
