### PR TITLE
LinuxRendererGL: Fix useage of glTexImage3D format was not valid

### LINKED ISSUE #15183: Black video when CMS enabled
### Describe the bug
Here is a clear and concise description of what the problem is:

When I play any video with Color Management enabled in the Settings, the video itself is entirely black. The audio and subtitles still work correctly though. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect that the video is shown correctly, with its colors corrected as needed.

## Actual Behavior

The video is entirely black.

## Possible Fix

The problem seems to be with Color Management. I used this in v17 where it worked without problems. The obvious workaround is to disable Color Management. The video is then shown again but its colors will not be corrected.

### To Reproduce

1. In Settings > System > Display, enable Color Management with an ICC profile (rest can be default)
2. Ensure that no hardware acceleration is used (since Color Management doesn't work with that) to play videos
3. Play any video. The video is now shown entirely black.

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/ucuqevilub.kodi
This debug log was created by starting Kodi (with debug logging already enabled), starting a video (to reproduce the bug) and then closing Kodi again.

### Screenshots 

No screenshots since it seems unnecessary to show a screenshot of a black screen.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Kodi was compiled using cmake with LCMS2 enabled. This worked correctly in v17/Krypton. I've tried modifying some of the Color Management settings but that didn't make a difference. I could not test this with the 3D LUT option of Color Management since I do not have a 3D LUT file.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Debian (unstable with kernel 4.19)
 - Kodi version: 18.0rc4-Leia (git tag)
 - LCMS2 version: 2.9

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by fritsch**
This fixes CMS on Linux

Fixes: https://github.com/xbmc/xbmc/issues/15183

### CODE REVIEW

**Comment by fritsch** [comment]
Thanks to @cpmw17 see https://github.com/xbmc/xbmc/issues/15183#issuecomment-570069251

@cpmw17 you use kodi Leia and want that fix as well?

**Comment by fritsch** [comment]
jenkins build this please

**Comment by cpmw167** [comment]
@fritsch I'm currently using v19, but I can confirm this fixes CMS on Leia as well (GBM and X11 - I haven't tested Wayland) and since it seems to fix CMS on Leia, it probably makes sense to push it to v18 as well.

**Comment by fritsch** [comment]
Thanks for reporting back. I will do so.

**Comment by fritsch** [comment]
jenkins build this please

**Comment by fritsch** [comment]
jenkins build this please

**Comment by fritsch** [comment]
Was built: https://jenkins.kodi.tv/job/BuildMulti-PR/14221/ (UWP failure not related)

**Pull request merged**
