### PR TITLE
Add FindGMP.cmake

### PR DESCRIPTION
**Pull request by peak3d**
See title
## Description

crosscompiling with cmake ubuntu 16.04 host / arm 32 android target fails  
## Types of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by hudokkow** [comment]
jenkins build this please

**Comment by fetzerch** [comment]
The android build works for me locally (and as well on jenkins) without that change.
Also it seems that this is not a direct dependency of Kodi.

@wsnipex: Could that be caused by `-DENABLE_INTERNAL_FFMPEG=OFF`. or any other idea?

Error was:

```
[100%] Linking CXX shared library libkodi.so
bignum.c:69: error: undefined reference to '__gmpz_com'
bignum.c:127: error: undefined reference to '__gmpz_com'
bignum.c:163: error: undefined reference to '__gmpz_import'
bignum.c:171: error: undefined reference to '__gmpz_import'
bignum.c:184: error: undefined reference to '__gmpz_import'
bignum.c:190: error: undefined reference to '__gmpz_init_set_ui'
bignum.c:191: error: undefined reference to '__gmpz_mul_2exp'
bignum-random.c:57: error: undefined reference to '__gmpz_fdiv_r_2exp'
rsa-keygen.c:111: error: undefined reference to '__gmpz_gcd'
rsa-keygen.c:139: error: undefined reference to '__gmpz_gcd'
ecc-j-to-a.c:65: error: undefined reference to '__gmpn_zero'
ecc-j-to-a.c:67: error: undefined reference to '__gmpn_zero'
ecc-j-to-a.c:74: error: undefined reference to '__gmpn_zero'
ecc-mul-g.c:63: error: undefined reference to '__gmpn_zero'
ecc-point.c:97: error: undefined reference to '__gmpz_congruent_p'
bignum-random-prime.c:203: error: undefined reference to '__gmpz_fdiv_q_2exp'
bignum-random-prime.c:227: error: undefined reference to '__gmpz_gcd'
bignum-random-prime.c:359: error: undefined reference to '__gmpz_mul_2exp'
bignum-random-prime.c:370: error: undefined reference to '__gmpz_mul_2exp'
bignum-random-prime.c:371: error: undefined reference to '__gmpz_fdiv_q'
bignum-random-prime.c:380: error: undefined reference to '__gmpz_mul_2exp'
bignum-random-prime.c:381: error: undefined reference to '__gmpz_fdiv_q'
/opt/xbmc-android/arm-linux-androideabi-android-21/include/gmp.h:1750: error: undefined reference to '__gmpn_perfect_square_p'
ecc-a-to-j.c:47: error: undefined reference to '__gmpn_copyd'
gmp-glue.c:317: error: undefined reference to '__gmp_get_memory_functions'
gmp-glue.c:327: error: undefined reference to '__gmp_get_memory_functions'
gmp-glue.c:338: error: undefined reference to '__gmp_get_memory_functions'
gmp-glue.c:349: error: undefined reference to '__gmp_get_memory_functions'
collect2: error: ld returned 1 exit status
CMakeFiles/kodi.dir/build.make:388: die Regel für Ziel „libkodi.so“ scheiterte
```

**Comment by wsnipex** [comment]
GMP is not a direct kodi dependency, but a dep of a dep(fffmpeg->gnutls->gmp), so it indeed could be affected by using external ffmpeg.
I'd need to know more about how to reproduce this error though.

**Comment by wsnipex** [comment]
I'd expect https://github.com/xbmc/xbmc/pull/10479 to fix your issue, since it properly checks for ffmpegs static lib dependencies. Can you test that?

**Comment by peak3d** [comment]
yes, will check this morning

**Comment by peak3d** [comment]
closed because solution is part of https://github.com/xbmc/xbmc/pull/10479

**Pull request closed without merging**
