### PR TITLE
[screensaver.xbmc.builtin.dim] reduce dim minimum threshold to zero

### PR DESCRIPTION
**Pull request by Hitcher**
## Description

Backport of https://github.com/xbmc/xbmc/pull/16620

### CODE REVIEW

**Comment by ksooo** [comment]
Original PR is flagged as an "improvement". Usually we only do backport issues flagged as "bug". What's the point for making an exception here?

**Comment by DaVukovic** [comment]
@ksooo well, it's just good to have for ppl who are using plasma TVs if the screen is able to go to black while 'dim' as a screensaver is in use. As we force dim to be the screensaver if a dialog is opened (because all other screensavers are using windows), I would say it's pretty nice to have that 'improvment' in Kodi 18 as well. Hence I flagged the original PR accordingly.

Not a problem at all if we decide otherwise. But I guess Kodi 18 users should benefit from that as well.

Just saying ;)

**Comment by ksooo** [comment]
> well, it's just good to have for ppl 

 Well, isn't every enhancement good for everybody? My POV: If it is not a bugfix, no backport.

**Comment by DaveTBlake** [comment]
All good @ksooo it is a fix for issue #16123

**Comment by ksooo** [comment]
@DaveTBlake I don't buy that this is a fix. See my comment in the Matrix PR.

**Comment by DaveTBlake** [comment]
Well since it resolves an issue @ksooo that sounds like a fix to me. 
Since @HitcherUK clearly felt it was worth backporting that is also good enough for me.

**Comment by arnova** [comment]
I feel like it resolves an issue too and therefor consider it a fix. But since there is no consensus, another question comes to mind: what are the chances of it causing regressions? I think that's near 0, so in that case: what's the problem backporting this?

**Comment by ksooo** [comment]
=> https://github.com/xbmc/xbmc/issues/16123#issuecomment-532344858

**Comment by ksooo** [comment]
Fix for #16123 is here: https://github.com/xbmc/xbmc/pull/16636.

But if you think this improvement should be in Leia, go ahead.

**Comment by HitcherUK** [comment]
Thanks, will close.

**Pull request closed without merging**
