### PR TITLE
Add clangd index to .gitignore

### PR DESCRIPTION
**Pull request by romanvm**
## Description

This PR adds clangd index to .gitignore

## Motivation and context

Clangd extension for VScode creates a large number of index files that need to be excluded from Git.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [x] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by fuzzard — APPROVED** [review]
Do we just do the whole .cache folder?
Either way, approve from me

**Review by garbear — APPROVED** [review]
I see no harm

**Comment by romanvm** [comment]
I have excluded the whole `.cache` folder.

**Comment by fuzzard** [comment]
feel free to backport if it annoys you on matrix

**Pull request merged**
