### PR TITLE
changed: modernize mime type map initialization

### PR DESCRIPTION
**Pull request by notspiff**

### CODE REVIEW

**Comment by ace20022** [comment]
while you're at it, can you have a look the duplicates mentioned there: https://trac.kodi.tv/ticket/17443

**Comment by notspiff** [comment]
jenkins build this please

**Comment by Rechi** [comment]
wrong revision was build
jenkins build this please

**Comment by MartijnKaijser** [comment]
Can you extend the commit message "remove some duplicates" to "remove some duplicates mime type mapping" ?  :)

**Comment by notspiff** [comment]
done.

**Pull request merged**
