### PR TITLE
[addons][PVR] PVR Addon API 9.0.0

### PR DESCRIPTION
**Pull request by ksooo**
This is an incompatible PVR Addon API change. All PVR client addons must be recompiled and re-released! I will take care of that for all the addons in kodi-pvr repo.

* Fixes crashes introduced with API 8.4.0 #25552
* Cherry picked the API changes from #24096 
* Cherry picked the API changes from #24622
* Added PVR_RECORDING::iEpisodePartNumber

Runtime-tested on macOS, latest xbmc master, with adapted local versions of pvr.hts and pvr.plutotv
 
@phunkyfish As @AlwinEsch is not around currently, I would like to ask you to review.

@DeltaMikeCharlie, @emveepee f.y.i.

### CODE REVIEW

**Comment by DeltaMikeCharlie** [comment]
@ksooo - Just for clarification.

Was it your intention to consolidate #25552, #24096 and #24622 into this PR and discard the originals?

**Comment by ksooo** [comment]
@DeltaMikeCharlie  you have read the description of this PR, haven’t you.

**Comment by ksooo** [comment]
Okay, for clarification:

> Was it your intention to consolidate https://github.com/xbmc/xbmc/pull/25552, https://github.com/xbmc/xbmc/pull/24096 and https://github.com/xbmc/xbmc/pull/24622 into this PR and discard the originals?

No, that's not the intention.

https://github.com/xbmc/xbmc/pull/25552 is already merged.

https://github.com/xbmc/xbmc/pull/24096 and https://github.com/xbmc/xbmc/pull/24622 are not obsolete. I only picked parts from these PRs for this PR, which is supposed to bring in several API changes (and not the stuff that is built on top of that changes) in one go, so that we need not so much API bumps and keep the API changes as such closely together.

**Comment by ksooo** [comment]
jenkins build this please

**Review by phunkyfish — APPROVED** [review]
Excellent, super clean. Thanks for doing this.

**Pull request merged**
