### PR TITLE
[cmake] also use pkg-config for python detection if crosscompiling

### PR DESCRIPTION
**Pull request by stefansaraev**
As title says.
## Description

It seems that using pkg-config for python detection works just fine when cross-compiling
## Motivation and Context

Without this change, I need to pass -DPYTHON_INCLUDE_DIRS=/path/to/my/crosstoolchain/usr/include/python2.7, otherwize python detection fails
## How Has This Been Tested?

Builds for me. jenkins will test it :)

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by stefansaraev** [comment]
stupid python thing. we are using shared libffi with unified builds (not python's internal ffi) and python.pc does not have -lffi in Libs.private

**Comment by stefansaraev** [comment]
shot in the dark. lets see if libffi depend can be dropped

**Comment by hudokkow** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by stefansaraev** [comment]
k. I tried, and I failed. distros can patch it out if they need to. 

note to self: never touch python again :)

sorry for the noise..

**Pull request closed without merging**
