### PR TITLE
FFMPEG: Fixes rbpi compilation

### PR DESCRIPTION
**Pull request by nsenica**
## Description
With the latest refactoring of platforms and systems, raspberry pi compilation was not getting the correct flags. This PR attempts to fix it.

## Motivation and Context
Fixing compiler flags for raspberry pi builds.
 
## How Has This Been Tested?
Compiling code.

## Types of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by wsnipex — APPROVED** [review]
thanks, looks good

**Comment by popcornmix** [comment]
It doesn't break my build, so if @wsnipex is happy then so am I.

**Comment by Rechi** [comment]
I think the change for the CMakeLists.txt should be the same as https://github.com/xbmc/xbmc/commit/853c7f6403 for the Makefile, or is there actually a good reason for the different parts?

**Comment by nsenica** [comment]
@Rechi , in practice both are equivalente, here we are just explicitly disabling those options, since it depends on the ffmpeg default config, it might be safer to explicitly doing so. If you find it important, I can add these switches to the Makefile.

About the --enable-pic, it is enabled a little down below at https://github.com/xbmc/xbmc/blob/master/tools/depends/target/ffmpeg/CMakeLists.txt#L66

**Comment by wsnipex** [comment]
@rechi ok?

**Comment by Rechi** [comment]
Fine with me.

**Pull request merged**
