### PR TITLE
set BICUBIC as default picture scaling algorithme

### PR DESCRIPTION
**Pull request by MartijnKaijser**

### CODE REVIEW

**Comment by uNiversaI** [comment]
Would be extra nice to know what algorithm is in use via logging especially since the as.xml.

**Comment by NedScott** [comment]
@uNiversaI wouldn't it show up in the log for the as.xml settings? If no as.xml settings are loaded then we can assume that this default is being used.

**Comment by uNiversaI** [comment]
Sure its still an assumption, confirmation that it actually is in use would be ideal, but no biggie.

**Comment by MartijnKaijser** [comment]
there's no confirmation for many other settings that are changed with advancedsettings

**Comment by uNiversaI** [comment]
I dont think that is right either, if someone overrides something and causes some issue or put a typo somewhere in advancedsettings and whoever is looking misses the typo then 

Or even if something breaks that setting / override thers no way of knowing anything for sure.

My as.xml was set to override to bicubic and used texturecache.py to recache everything, not once did I see bicubic entry anywhere in log and if the override was working or not its an unknown. Would have been more comfortable knowing I didn't spend all that time reaching for nothing especially since a few images looked just as bad as before.

**Pull request merged**
