### PR TITLE
[keymaps] remote.xml: map skipminus/plus to Prev/NextLetter in library view.

### PR DESCRIPTION
**Pull request by ghost**
Overrides the global mapping to SkipPrevious/SkipNext which is a no-op in
library view (so both these keys were unused).

### CODE REVIEW

**Comment by mkortstiege** [comment]
Fine by me.

**Comment by da-anda** [comment]
IMO playback related buttons should not be repurposed (play, pause, stop, skip). Also handling should be consistent accross all library views, and when thinking about music this is a no-go.

**Comment by anaconda** [comment]
Can you suggest some other button?
Should this PR just be closed?

**Comment by NedScott** [comment]
You could do mod="longpress", I suppose. That way it won't conflict with background music.

**Comment by da-anda** [comment]
I thought about using channel/page up/down buttons along with the "longpress" modifier - seems to be the most sensible way.

But IMO it would make more sense to extend the feature set of Kodi to show a A-Z list on screen.

**Comment by MartijnKaijser** [comment]
If still needed please open a new PR and reference this one.

**Pull request closed without merging**
