### PR TITLE
[interfaces][json-rpc] Add video stream selection.

### PR DESCRIPTION
**Pull request by ace20022**
@Montellese @Tolriq could you please review? The return types are the same as for the audio counterparts.

### CODE REVIEW

**Comment by Montellese** [comment]
Should be good but will need a rebase for the API version (but I have another PR pending which will also bump the version).

**Comment by Tolriq** [comment]
Can't test / review until monday but the api definition looks correct for remote usage :)

**Comment by ace20022** [comment]
@Montellese thx! Should I bump, build, merge or should I wait?

**Comment by Montellese** [comment]
I just merged my 2 PRs so you should be fine to rebase, bump, build and merge now.

**Comment by ace20022** [comment]
Cool, is 7.4.0 ok or?

**Comment by Montellese** [comment]
Sure

**Comment by ace20022** [comment]
jenkins build this please

**Comment by Tolriq** [comment]
@ace20022 finally find time to test :)

It works well but maybe you can add something for that and audio streams : if the stream name is empty return a default value that will match Kodi interface ? So that remotes / web interface can mimic Kodi without the need to invent again the wheel ?
Or maybe like some of the other api, always return a label that match Kodi interface and keep the name for real stream name when available ? That would be quite useful I think.

**Comment by ace20022** [comment]
@Tolriq Can you give an example?

**Comment by Tolriq** [comment]
image

The video stream label : English - .......

**Comment by ace20022** [comment]
mhm, that would cause problems regarding backwards compatibility. But I could add a new field "label" if that would help.

**Comment by Tolriq** [comment]
Yes a label would be perfect and match the rest of the API. It's useful to keep consistency and already provides clean strings in every languages :)

**Pull request merged**
