### PR TITLE
boost can go.

### PR DESCRIPTION
**Pull request by stefansaraev**
^^

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Yeahh, +1

**Comment by FernetMenta** [comment]
bye bye :)

**Comment by MrMC** [comment]
about time, it only took over a year :)

**Comment by afedchin** [comment]
awesome!

**Comment by stefansaraev** [comment]
jenkins build this please

**Comment by Razzeee** [comment]
what's with those thingys?
https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/legacy/AddonClass.h#L212
https://github.com/xbmc/xbmc/blob/master//xbmc/network/websocket/WebSocketV8.cpp#L194

**Comment by stefansaraev** [comment]
websocket uses own copy of boost/uuid/sha1.hpp. the other one I cant comment on

**Comment by MartijnKaijser** [comment]
@jimfcarroll ping

**Comment by MartijnKaijser** [comment]
it builds...

**Comment by FernetMenta** [comment]
success :)

**Comment by MartijnKaijser** [comment]
Now only need to know about?
https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/legacy/AddonClass.h#L212

**Comment by FernetMenta** [comment]
@MartijnKaijser this comment in AddonClass has nothing to do with internal usage of boost. This in an interface to kodi and if I interpret this correctly Jim has implemented those methods for the case some external client uses boost to access our interface.

**Comment by MartijnKaijser** [comment]
Guess we'll find out then :)

**Comment by jimfcarroll** [comment]
+1

**Pull request merged**
