### PR TITLE
[guilib] add Container.SortOrder InfoLabel

### PR DESCRIPTION
**Pull request by phil65**
Adds an InfoLabel "Container.SortOrder"
- Avoids the need for some workarounds  (using $INFO[Control.GetLabel(4)])
- bit more flexible (only returns "Ascending" / "Descending" without the "Order: " prefix)
- Consistent with Container.SortMethod InfoLabel

Also, I found some not-documented stuff when lookin through code I didnt hear off before:

Container.sortdirection(ascending/descending) [Boolean]
Container.sort(sorttype) [Boolean]
Container.listitemposition(..).xxx [InfoLabel]

The first one would allow a workaround (by using a $VAR[] for example) to do basically the same as this PR, but since I already was done when finding that I thaught setting up this PR doesnt hurt for a short discussion at least.

for the last one I found some related old forum thread, it´s in core since 6 years already :) http://forum.kodi.tv/showthread.php?tid=63144

Any opinion? The InfoLabels / Bools are probably something for the wiki? (and perhaps worth mentioning in "Skinning engine changes" thread? )

@ronie @mkortstiege

### CODE REVIEW

**Comment by mkortstiege** [comment]
In order to reduce dupe code, please combine `CONTAINER_SORT_METHOD` and `CONTAINER_SORT_ORDER` and just handle the returned label by a simple if statement. Other than this it makes sense and looks good.

As for the un-documented stuff we need to test and put it in the wiki. There might be a reason it's not there ;)

**Comment by ronie** [comment]
nice stuff, no objections from my end ofc.

i'll do some testing with the bools/infolabels you've found and will update the forum/wiki accordingly.

**Comment by MartijnKaijser** [comment]
can you add a line in strings.po where the string is used?

**Comment by phil65** [comment]
@MartijnKaijser @mkortstiege both done.

**Comment by ronie** [comment]
> Container.sort(sorttype) [Boolean]

this one is implemented incompletely, it only returns true if songs are sorted by rating.
in all other occasions it returns empty.
https://github.com/xbmc/xbmc/blob/master/xbmc/GUIInfoManager.cpp#L1118
not worth mentioning imo.

**Comment by phil65** [comment]
ok, that´s the only one I didnt test :) The other 2 seem to be workin fine.

**Comment by MartijnKaijser** [comment]
put the incomplete at the scrapping list?

**Comment by mkortstiege** [comment]
Thanks. @ronie, mind checking if `Container.Sort()` is actually used within our repositories? Feels like a rare special case that might be obsolete.

**Comment by ronie** [comment]
nope, it isn't used.

**Comment by mkortstiege** [comment]
> nope, it isn't used.

Should be just nuke it then?

**Comment by ronie** [comment]
yeah, makes little sense to keep it.

**Comment by mkortstiege** [comment]
@phil65, could you please remove the faulty/obsolete `Container.Sort` in a separate commit? Once done this is good to go.

**Comment by phil65** [comment]
@mkortstiege done.

**Comment by mkortstiege** [comment]
jenkins build and merge

**Comment by phil65** [comment]
Rebased, previous build error was unrelated. Jenkins build this please.

**Comment by Memphiz** [comment]
Who is Jenkins? jenkins build this please (case sensitive)

**Comment by phil65** [comment]
ups :)

**Comment by phil65** [comment]
@ronie bump for skin changes thread.

**Pull request merged**
