### PR TITLE
changed: remove internal librtmp support

### PR DESCRIPTION
**Pull request by notspiff**
moved to an inputstream add-on. see https://github.com/notspiff/inputstream.rtmp depends on #9945

### CODE REVIEW

**Comment by FernetMenta** [comment]
nice
jenkins build this please

**Comment by stefansaraev** [comment]
nice. what's the plan for tools/depends/target/librtmp ?

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by stefansaraev** [comment]
https://github.com/stefansaraev/xbmc/commit/89ab438f3d27ad79a70fe6abaaef1665ab2429a2

**Comment by notspiff** [comment]
squashed

**Comment by notspiff** [comment]
as for the depend; it has now moved to the add-on but i have not yet written the fluff for it be built there so lets keep it in depends for the time being.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
strange groovy, swig errors
jenkins build this please

**Pull request merged**
