### PR TITLE
[darwin] - fix compile with xcode 6.3

### PR DESCRIPTION
**Pull request by Memphiz**
As the title says. Jenkins built it fine on the relevant platforms (it still uses xcode6.1 of course):

http://jenkins.kodi.tv/job/OSX-64/4155/
http://jenkins.kodi.tv/job/OSX-32/3994/
http://jenkins.kodi.tv/job/IOS-ATV2/3758/

@FernetMenta got it :)

### CODE REVIEW

**Comment by Memphiz** [comment]
And since you reported it - you can push the button ... :)

**Comment by FernetMenta** [comment]
great!
did you try to rebuild depends? this failed on my system with 6.3

**Comment by Memphiz** [comment]
ahh no... forgot about that

**Comment by FernetMenta** [comment]
iirc it was just the testsuite of nettle. there should be a configure switch to exclude it

**Comment by Memphiz** [comment]
Ok thx - running a build from scratch now and will add the fix to this PR then :)

**Comment by Memphiz** [comment]
@FernetMenta could you test please? Tried osx and ios from scratch now and works for me...

**Comment by FernetMenta** [comment]
good job! built from scratch and it worked.

**Comment by xhaggi** [comment]
great thank you ;)

**Pull request merged**
