### PR TITLE
Create special.xml

### PR DESCRIPTION
**Pull request by luizoti**
## Description

This PR is part of PR # 19798, I tried to create the PR with the two files, but I couldn't, it was bad for the mess.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
What is the point of this?

**Comment by luizoti** [comment]
Are you talking about the Pull Request or the file? Because I tried to open a single PR, and I couldn't.

If something is wrong, I close the PRs.

**Comment by lrusak** [comment]
> Are you talking about the Pull Request or the file? Because I tried to open a single PR, and I couldn't.
> 
> 
> 
> If something is wrong, I close the PRs.

What is the point of this file? There is no explanation about what special.xml is or why it's needed.

**Comment by luizoti** [comment]
Good question, the special file was related to the pt-br layout file, but in fact I don't know, I will close the PR and test without this file and merge the Portuguese (pt-br) .xml with the Portuguese.xml.

**Pull request closed without merging**
