### PR TITLE
Fix two crash bugs

### PR DESCRIPTION
**Pull request by MaxKellermann**

### CODE REVIEW

**Comment by FernetMenta** [comment]
thanks a bunch
jenkins build this please

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
@FernetMenta this should also be backported to jarvis correct?
@MaxKellermann if yes please make PR to Jarvis branch for this.

**Comment by MaxKellermann** [comment]
Do you want me to send bug fixes to Jarvis from now on? I changed to master because I once sent an important crash bug fix to stable and you said that was not acceptable. In my own projects, I merge all incoming bug fixes only into the stable branch (and from there to unstable).

**Comment by MartijnKaijser** [comment]
bugfixes first to master and if it makes sense also to Jarvis.
Do note that master has a completely reworked videoplayer now so not all bugs apply to master/jarvis

**Pull request merged**
