### PR TITLE
 [videoplayer] GUIInfoProvider: Add subtitle info to the cache. 

### PR DESCRIPTION
**Pull request by ace20022**
Commit one will be skipped on rebase.
I'm really not sure if commit 3 (or the whole pr) is needed at all or worth the hassle.

### CODE REVIEW

**Comment by Razzeee** [comment]
> Commit one will be skipped on rebase.

means you will drop the rename commit?

**Comment by ace20022** [comment]
No, the fix... one. It belongs to another pr. Stupid gh ordering.

**Comment by Razzeee** [comment]
What's the idea behind renaming from AV to AVS?

**Comment by ace20022** [comment]
> What's the idea behind renaming from AV to AVS?

Only to reflect the fact that subtitle changes are "involved". But if that's not obvious, I should drop it and only change the (doxygen) comments.

**Comment by FernetMenta** [comment]
I would drop the 3rd commit

**Comment by Rechi** [comment]
wrong revision was build
jenkins build this please

**Review by ksooo — APPROVED** [review]
lgtm

**Comment by Razzeee** [comment]
What's the reason for this change and can addon authors figure out what caused the event?

I the subtitle info also included on AVStarted now?

**Comment by ace20022** [comment]
> What's the reason for this change

The reason is that I saw that subs info isn't cached. Imo we should even expand cache usage to guidialogs/jsonrpc etc.

>and can addon authors figure out what caused the event?
Do you mean if a,v or s stream(s) changed? The stream type is not announced if I saw it right.

**Comment by ace20022** [comment]
> I the subtitle info also included on AVStarted now?

AVStarted does not include any stream info. It's emitted when a player started playback.

**Review by FernetMenta — APPROVED** [review]

**Review by razzeee — APPROVED** [review]

**Comment by Razzeee** [comment]
Looks good to me

**Pull request merged**
