### PR TITLE
[osx] - fix broken audio devices with more then 8 unknown channels in one stream

### PR DESCRIPTION
**Pull request by Memphiz**
In CoreAudio we have to always deliver data for the number of channels in one stream even if not all channels are used. We normally fillup the unused channels with AE_CH_UNKNOWN< n >. Till now the channel enum allows for only 8 unknown channels. Since one channel can only be added once in a CAEChannelInfo  object this leads to the following issue.

User has an audio device with 12 channels in one stream. He sets Kodi to 2.0 output. This means we need to deliver data for FL,FR,< 10 unknown channels > (12 channels in sum). Because of the limit to 8 unknown channels we deliver FL,FR,< 8 unknown channels > (10 channels in sum). This leads to the fact that we deliver data for 10 channels in a sink which expects 12 channels. We have disco on all 12 channels instead of Stereo + 10 \* silence...

@FernetMenta  for review and risk judgement

@MartijnKaijser @topfs2 user with that audio device confirmed the fix. (i tag it for helix as a proposal and let fernet overrule if needed).

### CODE REVIEW

**Comment by Memphiz** [comment]
@FernetMenta @fritsch - now there is a user with audio equipment which has 32 respectively 64 channels and only fl and fr are mapped. Are we ok with increasing the number of unknown channels further or is there another approach you wanna try? (also not sure how big those devices can get - maybe the next one has 128 channels or what not)

for reference http://forum.kodi.tv/showthread.php?tid=221020

**Comment by Memphiz** [comment]
nice equipment for sure - 4000$ for mapping a stereo signal ;)

http://www.apogeedigital.com/products/symphony-io

**Comment by MartijnKaijser** [comment]
Unplug the device and use the normal audio card

**Comment by fritsch** [comment]
Sorry - in a hurry (as always) :-(

Yes, we need another solution here, we should not fillup 128 channels via the Engine. As the Sink does the enumeration and it is buffering internally anyways (ringbuffer), it should just be a matter for allocate your 128 channels :-) set all of them zero and just overwrite the portion with the data you are getting from the Engine?

If it's planar it is rather easy. If it's interleaved - it's more of intensive loop operation.

**Comment by FernetMenta** [comment]
I agree, this is very specific to this platform so we should address the issue in this sink.

**Comment by Memphiz** [comment]
Problem is that i need to do the channelmapping then on my own which defeats the purpose of having an engine imo. I also am not quiet sure if this really is platform specific. What happens if i attach this 32 channel audio equipment on linux? Is the alsa or pulseaudio driver only wanting data for the mapped channels or where is the difference?

**Comment by FernetMenta** [comment]
> What happens if i attach this 32 channel audio equipment on linux?

ALSA offers such kind of things: snd_pcm_hw_params_set_channels_max
We don't have 32 channel to map. Filling the arry with "unknown" is already a work around

> Problem is that i need to do the channelmapping then on my own which defeats the purpose of having an engine imo

only party agree. we can move generalizations into the engine if it is required by more than just one sink. you don't want to clutter the engine with platform specific work arounds, do you?

Note that the engine just mutes an unknown channel with zero. having a frame size of 32x4 is insane. have you calculated the resulting required transfer rate for this?

**Comment by Memphiz** [comment]
Ok i think i might try to refactor it in a way where i only request the mapped channels from AE and fillout the unmapped channels on my own somehow in the rendercallback from coreaudio.

**Comment by Memphiz** [comment]
Mhh and always when i tried to do something generic i come to a point where i think "this doesn't work". Just thinking about the following scenario. User has 32 audio channels. He maps channel 1 to FL and channel 32 to FR - now i want AE to map this for me. In that case i need 30 unknown channels - how to go about that? I don't want to do all the mapping in the sink because its to error prone and the engine already does it right.

I mean i can easily come up with something as long as the user maps his channels at the start of all available channels (then i can map FL, FR and fillup the rest 30 channels during rendercallback on my own). But this is an assumption i don't wanna make tbh.

**Comment by FernetMenta** [comment]
if the driver reported gaps to the application layer, I would consider it real crap and the entire system not worth more than 50c.

**Comment by fritsch** [comment]
@Memphiz if that's really the case, then there is no way arround for a datastructure mapping e.g. FL to target Pos, where target Pos >= 0 < channels :-(

that way you get FL or FR or whatever Ptrs and wirte the data you receive in DEA conform order from Audio Engine.

It sucks, but it should be doable in O(1)

**Comment by Memphiz** [comment]
@fernetmenta i don't really follow but i am pretty sure the success of Studio Equipment and Software suggests that the coreaudio System is not crap ...

**Comment by FernetMenta** [comment]
I am not saying the coreaudio system is crap. but the driver which comes with this expensive device mentioned above should take care that there are no gaps.

**Comment by FernetMenta** [comment]
thinking about this again I am not opposed to adding this to AE. That array of channels won't do any harm

**Pull request merged**
