### PR TITLE
[adsp] bye, bye libKODI_adsp.cpp

### PR DESCRIPTION
**Pull request by AlwinEsch**
Related to #10408. This remove the shared library for audio DSP.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by AlwinEsch** [comment]
jenkins build this with addons please

**Comment by AlwinEsch** [comment]
jenkins build this with addons please

**Comment by AlwinEsch** [comment]
jenkins build this with addons please again

**Comment by MartijnKaijser** [comment]
Why can't use http://jenkins.kodi.tv/view/Helpers/job/BuildMulti-All/ for testing instead of commenting each time?

**Comment by AlwinEsch** [comment]
Jenkins have always a git revision problem on them

**Pull request closed without merging**
