### PR TITLE
[SectionLoader] - remove logging in D'Tor

### PR DESCRIPTION
**Pull request by Memphiz**
Backport of #7746

### CODE REVIEW

**Comment by Memphiz** [comment]
For 15.1 please @MartijnKaijser  - doesn't need a compile test obviously ...

**Comment by Memphiz** [comment]
hold on - there are more to come as it seems somwhere deeper in the soloader *grr*

**Comment by MartijnKaijser** [comment]
@Paxxi @Memphiz should we already include this and do rest in another PR?

**Comment by Memphiz** [comment]
+1 imo - also i think that most printouts are LOGDEBUG so the thing that this one user keeps reporting those crashes might be due to having debugging turned on. But this particular log line from this PR is not interesting at all for debugging imo.

**Pull request merged**
