### PR TITLE
[Fix]Import song history match when have multiple releases of same album

### PR DESCRIPTION
**Pull request by DaveTBlake**
Fix import of song playback history to correctly match songs from when there are multiple releases of the album in the library.

Reported by  a user that was unable to import the song playback history after switching from SQLite to using a MariaDB client/server set-up, and had multiple releases of the same album. See https://forum.kodi.tv/showthread.php?tid=351921 

There was both a flaw in the matching process, which did not correctly identify the correct release
between those with mbid and the one without (when there was one), and  consequentialy a SQL error was thrown by MariaDB (rather than cope silently as SQLite did). 

This can be tested using a music library with 3 releases of the same album, 2 with mbid tags and one without. Tested on both SQLite and MySQL/MariaDB

### CODE REVIEW

**Comment by DaveTBlake** [comment]
jenkins build this please

**Comment by phunkyfish** [comment]
Appears to be DST related. PR is disable offending test here: https://github.com/xbmc/xbmc/pull/17465

**Comment by lrusak** [comment]
jenkins build this please

**Comment by DaveTBlake** [comment]
jenkins build this please

**Comment by DaveTBlake** [comment]
jenkins build this please

**Pull request merged**
