### PR TITLE
windowing: add overrides for UseLimitedColor for specific platforms

### PR DESCRIPTION
**Pull request by lrusak**
This is a better solution than #13800 

same idea, don't enforce limited colour on platforms that don't support it (or haven't been tested)

### CODE REVIEW

**Comment by a1rwulf** [comment]
Question:
Do we need the LOGDEBUG that states that the setting is missing?
The base class implementation of UseLimitedColor was changed on purpose here https://github.com/xbmc/xbmc/pull/12506/commits/479732f10334c082a1253f15814435c6a8ca9534 in order to not crash and make sure it returns false when the setting is missing.
I'd maybe prefer that instead of overriding for every platform with false.
Just my opinion.

**Comment by lrusak** [comment]
jenkins build this please

**Review by FernetMenta — APPROVED** [review]

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by Rechi** [comment]
This won't build, @lrusak broke master by merging #13828

**Comment by FernetMenta** [comment]
ok, all other platforms passed.

**Pull request merged**
