### PR TITLE
VideoPlayer: fix security issues with http options exposed to ffmpeg

### PR DESCRIPTION
**Pull request by FernetMenta**
in addition to https://github.com/xbmc/xbmc/pull/8434

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by basrieter** [comment]
With this change, is there also a new way of setting an HTTP Header for a request from a Python Add-on?

**Comment by basrieter** [comment]
Perhaps I need to be a bit more specific: I am confused by the part: 

> // we don't add blindly all options to headers anymore
      // if anybody wants to pass options to ffmpeg, explicitly prefix those
      // to be identified here

It seems as if it there is no actual prefix implemented?

**Comment by FernetMenta** [comment]
It is what the comment states. There is is "fix" because there is no bug. Feel free to elaborate on new requirements or submit a PR.

**Comment by Sorien** [comment]
@basrieter did you try something like this

```python
def addheaders(stream, referrer):
    headers = {'User-Agent': '',
               'Referer': ''}

    part = ""

    for name, desc in headers.iteritems():
        part = part + '&' + name + '=' + urllib.quote(desc)

    return stream + "|" + part[1:]

li = xbmcgui.ListItem(path=addheaders(stream['url']))
xbmcplugin.setResolvedUrl(int(sys.argv[1]), True, li)

**Comment by basrieter** [comment]
I didn't say it was a bug, really I don't. I know the reason behind this all (I think I initially raised the issue with the HttpProxy header being passed to ffmpeg). So I understand the reason for not blindly passing all headers to ffmpeg. 

However, I was just wondering what 'correct' alternative there is to pass headers to ffmpeg? Because if there is none, this change really cripples a lot of add-ons that pass specific http headers. So perhaps this PR went a bit too far? Would it not make more sense to filter out those 'Kodi-internal' headers you really don't want to pass such as the HttpProxy header and then pass the others.

**Comment by basrieter** [comment]
Would it be possible to revert things back to something like this:
```
else if (name != "auth" && name != "encoding" && name != "httpproxy")
  // all other protocol options can be added as http header.
  headers.append(it->first).append(": ").append(value).append("\r\n");
```
That way, the deprecated httproxy is no longer used but others are allowed. Or if it is better, do a lookup in an array of 'forbidden' headers defined somewhere? Because, currently, really none are passed. 

Or better, do something like what happened for the proxy now in https://github.com/xbmc/xbmc/pull/9421 ? That way, the headers are no longer passed in as URL parameters, but nicely via the proper objects? That way, weird headers are no longer in the URL and no confidential information will be present in logs or strm files?

**Comment by FernetMenta** [comment]
ffmpeg supports a defined set of options. Those can be added explicitly, if required.

**Comment by basrieter** [comment]
And where can I find this defined set of options?

**Comment by Sorien** [comment]
https://github.com/FFmpeg/FFmpeg/blob/d14993478cd9d6274f439f3200ea11c63ff8e0fa/libavformat/http.c#L127

**Comment by basrieter** [comment]
Thanks! So if I understand correctly, we should allow the 'headers' option to be passed onto the ffmpeg. And those should preferably be set via the ListItem.setProperty() instead of via the url as a dummy url parameter? So a setProperty("http.headers", "headername=value&headername2=value2")?

But then, within Kodi itself, we should also use those whenever we open urls related to ListItems? For instance, I noticed that first Kodi does some calls to get some M3u8 stream info, and then passes it on to ffmpeg. So Both Kodi and ffmpeg should use the new http.headers property?

**Comment by FernetMenta** [comment]
Kodi has many weaknesses and we can't fix all of them at once. In this particular case we look at the options allowed to be passed to ffmpeg. Since Kodi's ListItems and URL objects accept anything, we need to filter for allowed options. Those are the ones liked above and standard http request headers. All other options won't be passed on.

**Comment by basrieter** [comment]
I understand. But I am also a bit confused. One of options that ffmpeg allows is "headers":

>  { "headers", "set custom HTTP headers, can override built in default headers", OFFSET(headers), AV_OPT_TYPE_STRING, { .str = NULL }, 0, 0, D | E },

Could you explain to me, how I can pass these on at the moment?

**Comment by FernetMenta** [comment]
What exactly do you want to pass to ffmpeg?

**Comment by basrieter** [comment]
For example, in some situations would like to set the http header: 

> X-Requested-With: XMLHttpRequest
> Referrer: <url>
> Accept: text/html, */*; q=0.01
>X-Client-Token: <token value>

which are just a very basic http headers and very commonly used. All of them are not stopped because of the change made in this PR.

**Comment by FernetMenta** [comment]
the old code treated every option that was not identifies as something else as a custom header. This is a security issue and has been discontinued for this reason. Assume some FileItem is intended for a different input stream handler and gets accidentally picked up by ffmepg inputStream. In that case we would expose options not supposed to go outside to ffmpeg and the outside world.
Kodi is a addon/plugin system and has to care for such things. Standard http request headers are ok. ffmpeg options are ok. 

If you want to pass custom headers, we need a setting the user can agree on this type of thing. In addition the custom headers need some means to be identified for a particular target. Maybe something like a frefix: ffmpegCustomHeader-header123

**Comment by basrieter** [comment]
I understand your point in regards to the HTTP proxy information, those were incorrectly passed on to other components and caused a risk, because they were intended for **internal** Kodi functionality. But these standard HTTP headers should be no problem and, for example the Referrer, are very standard and very often required. So banning them all is ignore almost all of these: https://en.wikipedia.org/wiki/List_of_HTTP_header_fields

**Comment by FernetMenta** [comment]
You don't seem to listen. I said standard headers can be passed through without further checks. Non-standard headers can be passed too but require special handling like a user setting to allow those.

**Comment by basrieter** [comment]
I am trying to listen and understand, really, but apparently there is confusion (or misunderstanding) on my end. What are the list of 'standard' headers? And how do I pass them on then, still via the url after the pipe sign?

**Comment by Sorien** [comment]
what about change a way how headers are passing to something like 

`http://foo/file.m3u|headers=User-Agent:kodi;Referer:kodi.com&seekable...` 
```c
     for(std::map<std::string, std::string>::const_iterator it = protocolOptions.begin(); it != protocolOptions.end(); ++it)
     {
       std::string name = it->first; StringUtils::ToLower(name);
       const std::string &value = it->second;
 
       if (name == "seekable")
         av_dict_set(&options, "seekable", value.c_str(), 0);
       else if (name == "user-agent")
       {
          av_dict_set(&options, "user-agent", value.c_str(), 0);
          hasUserAgent = true;
       }
       else if (name == "headers") 
       {
         std::replace(value.begin(), value.end(), ";", "\r\n");
         av_dict_set(&options, "headers", value.c_str(), 0);
       }
```

**Comment by FernetMenta** [comment]
That would introduce the same crap that we had before. Again: Kodi won't blindly pass options to ffmpeg. Explicitly check for ffmpeg options, explicitly check for standard http header requests, check for explicitly prefixed options and pass those if user allows it.

**Comment by basrieter** [comment]
But still, what are the "standard http headers" because I still did not find this?

**Comment by FernetMenta** [comment]
Don't get me wrong, I am not picky about the term "standard" in this context. I am just saying that Kodi has to know what data it handles. You linked this: https://en.wikipedia.org/wiki/List_of_HTTP_header_fields. Handling the "non-standard" ones listed in this article should be ok too.
Those can be added to the if, else block. If ffmpeg supports it directly, set ffmpeg option. If not, add it to headers.

**Comment by basrieter** [comment]
Ok, that sounds like a good solution to me! What I will try to accomplish (I am not an c++ expert) is to extend the if-then-else part in DVDDemuxFFmpeg.cpp to include the headers listed in the wiki page. 

for those directly supported by ffmpeg I should add 
`av_dict_set(&options, "<name>", value.c_str(), 0);`

for the others I append them to the `headers` string. 

Out of code correct-ness: should I create to arrays containing those headers that are allowed by ffmpeg and one with the others? So the if-then-else can just check if a header value is present in one or the other array and act accordingly?

**Comment by FernetMenta** [comment]
> should I create to arrays containing those headers that are allowed by ffmpeg and one with the others

I would keep it simple in this iteration and just continue with direct checks without extra arrays.

**Comment by Sorien** [comment]
or maybe block some of them like in adobe flash https://helpx.adobe.com/flash-player/kb/actionscript-error-send-action-contains.html ?

**Comment by basrieter** [comment]
I had a quick look and it seems as if the ProtocolOptions are now completely stripped somewhere earlier in code, and as far as I could see, the

` for(std::map<std::string, std::string>::const_iterator it = protocolOptions.begin(); it != protocolOptions.end(); ++it)`

always iterates over an empty object. This is because of this commit 2f3ccf17 where the `finalFileitem` gets the redirected URL but does not append the ProtocolOptions. So eventhough my current changes would allow the setting of headers, the ProtocolOptions to extract them from are not even set, because of this. 

2f3ccf17 was done to find the actual path after redirection. Is there within Kodi a simple way to first extract the ProtocolOptions, and append them to the redirected url? Or should it just be a split on the `|` and then append?

**Comment by FernetMenta** [comment]
there is a method for addons to disable content lookup. either use this or set options on the listItem.

**Comment by basrieter** [comment]
It's not just the http headers , also `seekable` and `user-agent`, which are currently used in the current implementation of `DVDDemuxFFmpeg.cpp`. The `setContentLookup` would indeed cause this to not happen. 

The dillema I have is this: I guess using `setProperty("http.headers", "User-Agent:kodi;Referer:kodi.com&seekable...")` would be preferred. Because this can then be used by, for instance, the `DVDDemuxFFmpeg.cpp` to get the http headers. 

However, currently, the 'piped headers and protocol options' (`|referrer=<url>&etc=more`)1 are also used in the `CurlFile.cpp` to determine the http headers when opening a url within Kodi itself (not ffmpeg). And within CurlFile the ListItem properties are not available that is why they are deducted from the url. So I have a hard time getting a solution that is working in all places :(

Perhaps for now, with Krypton in a Beta phase, it would be best to live with the `setContentLookup` solution and the changes I made to accept the http headers from the wiki page?

**Comment by basrieter** [comment]
Thanks @FernetMenta for your patience and help. Cheers!

**Comment by emilsvennesson** [comment]
@basrieter @FernetMenta: Now that this has been merged, could you please explain how I pass the headers on? I need to set 'User-Agent', 'Cookie', 'Accept-Encoding' and 'Connection'.

**Comment by basrieter** [comment]
@emilsvennesson as it has always been, via a <url>|header=value&header=value&.....

**Comment by emilsvennesson** [comment]
@basrieter Do you have any idea what I am doing wrong here: http://pastebin.com/RJ1CWczQ (latest nightly)? It seems to pass on the headers to curl, but ffmpeg still ignors them. This is the same problem I've had in Krypton for quite some time now. The same request works just fine on Jarvis.

**Comment by basrieter** [comment]
@emilsvennesson you need to disable the setContentLookup() from your add-on as Kodi will use the new URL, obtained via the lookup. That new URL does not use the headers specified. If you want full control over what headers are needed, you have to make sure yourself that you are actually opening the right url.

**Comment by emilsvennesson** [comment]
@basrieter Oh, I had no idea about setContentLookup. :-) I tried it out, but it's still ignoring cookies and 'Accept-Encoding': http://pastebin.com/nDpKpsjy.

**Comment by basrieter** [comment]
Correct, the "Accept-Encoding" is not something we need to force onto ffmpeg. It is ffmpeg that decides what encoding it can accept, the the code calling it.

**Comment by emilsvennesson** [comment]
@basrieter Fair enough, but what about the cookies?

**Comment by basrieter** [comment]
Cookies cannot be set, but Kodi will use that are available in the Curl cookies. So that should go automatically.

**Comment by emilsvennesson** [comment]
@basrieter I'm not getting it to work: http://pastebin.com/FSdkFUYy. :/

See the _mediaAuth cookie; curl passes it on correctly but ffmpeg still ignores it.

**Comment by basrieter** [comment]
You can't tell ffmpeg to pass it on, rather it needs to already be present in the cookie store from curl.

**Comment by emilsvennesson** [comment]
@basrieter Well, it is (I think?):
```
11:53:26 T:17308   DEBUG: Curl::Debug - HEADER_OUT: Cookie: _alid_=Ou0gUY/rG0ehgFpAjJZMUw==; _mediaAuth=PHBrYW4+CiAgPGlzc3VlZEF0PjIwMTYtMDktMDcgMDk6NTM6MjIuMTQzIFVUQzwvaXNzdWVkQXQ+CiAgPHR0bE1zPjIxNjAyMDAwPC90dGxNcz4KICA8Y2hhbm5lbD5lc3BudTwvY2hhbm5lbD4KICA8YWlyaW5nSWQ+MDwvYWlyaW5nSWQ+CiAgPFNpZ25hdHVyZT5ZcStMb2xCTFFxemxJUHlCeGE5NGtqbG5RNXVURVhTbU54cGVUVjlBUDlGNEhSSmdiVmpnVGNHU2F2RUpDeHV2TUlwM3RTYnpib01zMWs5em5RdktHUT09PC9TaWduYXR1cmU+CiAgPGFsaWFzPjVjMDdkMDA4MmRiM2Q0MmYxNGU1N2FlMGFmMDAzNzE4NTRjMTdiZDA8L2FsaWFzPgogIDxzaWduYXR1cmVUeXBlPkpDRTwvc2lnbmF0dXJlVHlwZT4KICA8aXNTaWduZWQ+ZmFsc2U8L2lzU2lnbmVkPgo8L3BrYW4+
```

ffmpeg:
```
11:53:29 T:2404   DEBUG: ffmpeg[964]: [http] Cookie: _alid_=Ou0gUY/rG0ehgFpAjJZMUw==
```

**Comment by basrieter** [comment]
Curl needs to receive it, not send it.

**Comment by emilsvennesson** [comment]
@basrieter: So am I not allowed to send my own cookies? This is quite the deal breaker for me and completely breaks my add-on (and I can imagine it affecting a whole lot more). My add-on receives the necessary cookie from the API request (see https://github.com/emilsvennesson/kodi-espnplayer/blob/master/resources/lib/espnlib.py#L209) and needs to use this for the ffmpeg request.

**Comment by basrieter** [comment]
I understand. This PR allows basic http headers. If cookies should be included we need a new PR. I don't know what @FernetMenta thinks about allowing cookies.

**Comment by emilsvennesson** [comment]
@FernetMenta: Would you be fine with allowing cookies to be passed to ffmpeg?

**Comment by FernetMenta** [comment]
In principle yes. The problem is that some sources require the other method of requesting the cookie from the url. I'll look into it.

**Comment by basrieter** [comment]
I was think of doing the same as for the user-agent in the DVDDemuxFFmpeg.cpp:

```
else if (name == "user-agent")
{
  av_dict_set(&options, "user-agent", value.c_str(), 0);
  CLog::Log(LOGDEBUG, "CDVDDemuxFFmpeg::GetFFMpegOptionsFromInput() adding ffmpeg option 'user-agent: %s'", value.c_str());
  hasUserAgent = true;
}
  else if (name == "cookie")
{
  av_dict_set(&options, "cookies", value.c_str(), 0);
  hasCookies = true;
}
// other standard headers (see https://en.wikipedia.org/wiki/List_of_HTTP_header_fields) are appended as actual headers
```
.................
```
if (!hasCookies)
{
  std::string cookies;
  if (XFILE::CCurlFile::GetCookies(url, cookies))
    av_dict_set(&options, "cookies", cookies.c_str(), 0);
}
```
that way a user could override the standard cookie option?

**Comment by basrieter** [comment]
Something like this: https://github.com/basrieter/xbmc/commit/c8e7101a3dd2a794a95d051fe7fca557ee0c3b36

**Comment by emilsvennesson** [comment]
@basrieter @FernetMenta: I really appreciate your efforts in resolving this. I just tried the latest nightly that includes the last PR, but unfortunately it's still not behaving as Jarvis does:

http://pastebin.com/9kFeBkBM

ffmpeg[3484]: [http] Invalid cookie found, no value, path or domain specified

**Comment by emilsvennesson** [comment]
@basrieter  @FernetMenta: I did some testing using ffmpeg, and it seems like you have to specify the path when using ```'-cookies'``` instead of ```'--headers 'Cookie:'```.

This works:
```.\ffplay.exe -cookies "_mediaAuth=PHB___+ path=/;" http://ak-hls-brs-espnlhn.espn.go.com/hls/live/203628/p/espnlhn-p-4500/espnlhn-p-4500.m3u8```

this results in the same error as the one from the Kodi log:
```.\ffplay.exe -cookies "_mediaAuth=PHB___" http://ak-hls-brs-espnlhn.espn.go.com/hls/live/203628/p/espnlhn-p-4500/espnlhn-p-4500.m3u8```

This also works:
```.\ffplay.exe --headers 'Cookie: _mediaAuth=PHB___' http://ak-hls-brs-espnlhn.espn.go.com/hls/live/203628/p/espnlhn-p-4500/espnlhn-p-4500.m3u8```

After adding the path in Kodi as well, everything works again! :-) I'm unsure if this breaks compatibility between passing cookies in Jarvis and Krypton though.

Thanks a lot for resolving this. I'm sure a lot of addon developers are grateful.

**Comment by basrieter** [comment]
I think if you would pass `"name=value; Path=/; Domain=.domain.test"` will make ffmpeg understand it, but Kodi's Curl will interpret it as 3 different cookie values. 

I could make it more behave like the Curl, by changing the ffmpeg behaviour within Kodi to:

```
else if (name == "cookie")
{
  std::string cookieValue = value;
  StringUtils::TrimRight(cookieValue, ";");
  cookieValue += "; Domain=." + url.GetHostName() + "; Path=/;";
  av_dict_set(&options, "cookies", cookieValue.c_str(), 0);
  CLog::Log(LOGDEBUG, "CDVDDemuxFFmpeg::GetFFMpegOptionsFromInput() adding ffmpeg option 'cookies: %s'", cookieValue.c_str());
  hasCookies = true;
}
```
And basically create a valid formatted cookie. However, I am doubting whether this is a Kodi thing or more an ffmpeg thing?

**Comment by emilsvennesson** [comment]
@basrieter Yeah, that's what I did and it works. I agree that this is more a ffmpeg thing, but I think it would be good if passing headers to Kodi's curl and ffmpeg would work the same way.

**Comment by FernetMenta** [comment]
lets set the cookies in headers if provided this way. I will submit a PR

**Comment by basrieter** [comment]
Ok, if you want I can PR this: https://github.com/basrieter/xbmc/commit/a1f0170889d681b4e2a9d5fb3156e0ee5511aa21

**Comment by FernetMenta** [comment]
I did some cosmetics to formatting and added a change to preserve protocol options when testing for redirect:
https://github.com/xbmc/xbmc/pull/10458

**Pull request merged**
