### PR TITLE
fix subtitle positions

### PR DESCRIPTION
**Pull request by FernetMenta**

### CODE REVIEW

**Comment by BigNoid** [comment]
In my test this fixes the subtitle position for "fixed" and can be adjusted again with the video calibration.
The overlapping subtitles still are on top of each other with anything other than fixed, but as you mentioned that is the same behavior as in helix.

**Comment by FernetMenta** [comment]
did you apply both commits? with 2452f5f0e9cce945f75965184fc26a800a60b941I can set to bot-of-video and your sample plays fine

**Comment by MilhouseVH** [comment]
Does this fix [#16018](http://trac.kodi.tv/ticket/16018), also discussed in [forum](http://forum.kodi.tv/showthread.php?tid=224025&pid=2017278#pid2017278)?

**Comment by BigNoid** [comment]
Apparently I did not. Is fine with both commits applied.
This should go in Isengard as it will save a lot of comments about sub position.

**Comment by FernetMenta** [comment]
I updated the 2nd commit. Now it also fixes overlapping for TOP aligned subs.

**Comment by BigNoid** [comment]
Fixed, bottom of video and top of video parses the overlapping subtitles on two lines now. Below video and above video still parses the overlapping subtitles on the same line. Not sure if that needs to be fixed though, I would be fine with this as it is now.

**Comment by FernetMenta** [comment]
are you sure that you tested exactly the version of this pr? your video works with all available options here.

**Comment by BigNoid** [comment]
Yeah I triple checked that before commenting seeing as I made that mistake the first time :)
This is what I did:
```git clean -xffd```
```git reset --hard upstream/master```
```git fetch upstream pull/7277/head:sub_fix```
```git checkout sub_fix```
Then build xbmc installer. Did I miss something?

**Comment by FernetMenta** [comment]
what platform are you on?

**Comment by BigNoid** [comment]
windows 8.1 (x64)

**Comment by FernetMenta** [comment]
weird. I tested your sample on OSX and Win 7 with all options. no issues.

**Comment by MartijnKaijser** [comment]
i'll make a jenkins build and try on Win10 and Win7 as well

**Comment by FernetMenta** [comment]
I think you are observing a Windows issue here which is a different problem. The video provided by @BigNoid renders on OSX and Linux with black bars. On Windows there are no black bars in fs mode. On Windows in windowed mode there are black bars and the subs (below video) are rendered correctly.

@BigNoid can confirm this? Does it work in windowed mode? Do you see black bars in fs?

**Comment by FernetMenta** [comment]
correction: it is not a Windows issue, it is dependant on aspect ration of window. It works with black bars on top/bottom and fails if there are no black bars. 
above/below video makes no sense without black bars at top/bottom, right?

**Comment by BigNoid** [comment]
@FernetMenta indeed. If there are black bars it renders correctly, the sample did not have black bars on my end.

**Comment by FernetMenta** [comment]
I will provide an additional patch tomorrow which internally disables the above/below case if there are no black bars.

**Comment by BigNoid** [comment]
Works in all cases now.

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Pull request merged**
