### PR TITLE
Add cmake-variants.yaml and cmake-kits.json to gitignore

### PR DESCRIPTION
**Pull request by enen92**
## Description
I am using vscode and cmake tools as the development environment for Kodi. In cmake-tools, a `cmake-variants.yaml` has to be created to group build options. As I believe this could be a common setup (and that I'll endup PRing my configs by mistake someday), let's add them to gitignore.

Refs: 
https://vector-of-bool.github.io/docs/vscode-cmake-tools/variants.html
https://vector-of-bool.github.io/docs/vscode-cmake-tools/kits.html

## Motivation and Context
Cosmetic

### CODE REVIEW

**Comment by lrusak** [comment]
Would a better solution be to actually add a `cmake-variants.yaml` for Kodi?

**Comment by enen92** [comment]
I'd say that it highly depends on the user configuration and underlying OS (and other factors). For instance, someone developing on x11 doesn't want to see Wayland as an option.

**Comment by wsnipex** [comment]
> Would a better solution be to actually add a `cmake-variants.yaml` for Kodi?

no- this is IDE specific, but cmake presets would be nice.

**Comment by enen92** [comment]
Is this good to go? I agree cmake presets would be great but I am not the one for the job 🙃

**Review by lrusak — APPROVED** [review]

**Pull request merged**
