### PR TITLE
Various minor build fixes

### PR DESCRIPTION
**Pull request by MaxKellermann**

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Unfortunately, I can't see why Travis CI fails, because
> This log is too long to be displayed. Please reduce the verbosity of your build or download the raw log.
Is there any way around this limitation?
Funny enough, the cmake build fails as well, but this PR is not about cmake.

**Comment by hudokkow** [comment]
Click on travis build you want to examine and on the top right corner of log box you will find the "Raw log" link.
For instance, https://s3.amazonaws.com/archive.travis-ci.org/jobs/117405615/log.txt

**Comment by MaxKellermann** [comment]
Thanks @hudokkow 

However I don't understand the problem here. It looks like the unit test crash is completely unrelated to my changes. Can anybody enlighten me (again)?

**Comment by MaxKellermann** [comment]
Build of my other PR https://github.com/xbmc/xbmc/pull/9415 failed with the same unit test crash. I assume upstream is broken ATM, and no (known) regression in my PRs.

**Comment by wsnipex** [comment]
probably related to https://github.com/xbmc/xbmc/commit/c56e9ded30f84717fb6d99ffa1bc47a5bd482fc7

**Comment by MaxKellermann** [comment]
Indeed, unit test breakage due to https://github.com/xbmc/xbmc/pull/9389

**Comment by notspiff** [comment]
until merged (or denied) you can manually pick https://github.com/xbmc/xbmc/pull/9419 to test your stuff.

**Comment by MaxKellermann** [comment]
Rebased after commit f711253

**Comment by MaxKellermann** [comment]
Travis fails because https://github.com/xbmc/libdvdread/archive/master.tar.gz could not be downloaded. Not related to this PR.

**Comment by MaxKellermann** [comment]
Rebased. Let's see if the Travis failures go away.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MaxKellermann** [comment]
Rebased.

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
@wsnipex ok for merge?

**Comment by wsnipex** [comment]
yes, fine for me

**Pull request merged**
