### PR TITLE
[tools/depends] Python cleanup

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
First stage of python cleanup. Most of this stuff comes from #19246 but ive decided to try and do small bringups and get stuff in.

## Motivation and context
Taking another stab at #19246 but in a staged approach. #19246 stalled due to android and python module loading (PIL) not working. Going to piece meal things in now, and work my way towards what #19246 is meant to be.

## How has this been tested?
Build time osx. Will test android python module loading to confirm no issues there.

## What is the effect on users?
N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by garbear** [comment]
I tried building this on Ubuntu 20.04, and depends succeeded, but Kodi is failing to link:

```
[100%] Linking CXX executable kodi.bin
/usr/bin/ld.gold: error: /usr/lib/x86_64-linux-gnu/libpython3.9.a(abstract.o): requires dynamic R_X86_64_32 reloc which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: /usr/lib/x86_64-linux-gnu/libpython3.9.a(abstract.o): requires dynamic R_X86_64_32 reloc which may overflow at runtime; recompile with -fPIC
...
/home/garrett/kodi-deps/x86_64-linux-gnu-debug/lib/libcurl.a(libcurl_la-version.o):version.c:function brotli_version: error: undefined reference to 'BrotliDecoderVersion'
/home/garrett/kodi-deps/x86_64-linux-gnu-debug/lib/libcurl.a(libcurl_la-version.o):version.c:function curl_version_info: error: undefined reference to 'BrotliDecoderVersion'
/home/garrett/kodi-deps/x86_64-linux-gnu-debug/lib/libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:function brotli_close_writer: error: undefined reference to 'BrotliDecoderDestroyInstance'
/home/garrett/kodi-deps/x86_64-linux-gnu-debug/lib/libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:function brotli_init_writer: error: undefined reference to 'BrotliDecoderCreateInstance'
/home/garrett/kodi-deps/x86_64-linux-gnu-debug/lib/libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:function brotli_unencode_write: error: undefined reference to 'BrotliDecoderDestroyInstance'
/home/garrett/kodi-deps/x86_64-linux-gnu-debug/lib/libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:function brotli_unencode_write: error: undefined reference to 'BrotliDecoderDecompressStream'
/home/garrett/kodi-deps/x86_64-linux-gnu-debug/lib/libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:function brotli_unencode_write: error: undefined reference to 'BrotliDecoderGetErrorCode'
collect2: error: ld returned 1 exit status
```

**Comment by fuzzard** [comment]
And it actually works with master? I can't see how anything in this PR could cause such an issue. I'll try on a VM I guess

**Comment by garbear** [comment]
I've been working on Matrix so I think my setup wasn't suitable to build Nexus atm. I'll give this a try later.

**Review by garbear — APPROVED** [review]

**Pull request merged**
