### PR TITLE
[json-rpc][PVR] Fixes and improvements

### PR DESCRIPTION
**Pull request by ksooo**
### Commit 1:

GetItem: Expose PVR subchannel number

### Commit 2:

Requested by @Tolriq 

GetItem: Fix data format of 'director', 'writer', 'cast' for PVR channel items

Testcase:
```
curl -X POST -H "Content-Type: application/json" -d '{"id":90,"jsonrpc":"2.0","method":"Player.GetItem","params":{"properties":["cast","writer","director"],"playerid":1}}' http://kodi:kodi@localhost:8080/jsonrpc
```

Before:
```
{"id":90,"jsonrpc":"2.0","result":{"item":{"cast":"actor1,actor2,actor3","director":"director1,director2,director3","id":237,"label":"Das Erste HD","type":"channel","writer":"writer1,writer2,writer3"}}}
```

After:
```
{"id":90,"jsonrpc":"2.0","result":{"item":{"cast":[{"name":"actor1"},{"name":"actor2"},{"name":"actor3"}],"director":["director1","director2","director3"],"id":237,"label":"Das Erste HD","type":"channel","writer":["writer1","writer2","writer3"]}}}
```

### Commit 3:

Requested by @b-jesch

PVR.AddTimer: Add support to create EPG based one time reminder or EPG based reminder timer rule.

PVR.Details.Timer: Add bool field 'isreminder'

@phunkyfish @DaveTBlake might want to take a look at the code changes.

### CODE REVIEW

**Comment by basilgello** [comment]
Great job @ksooo ! Can you by chance extend your PR to expose Play Catchup or Add Catchup To Playlist or just GetCatchupUrl so in remotes like Kore or Yatse it becomes possible to play PVR catchup stream from the PVR program window?

**Comment by ksooo** [comment]
> so in remotes like Kore or Yatse it becomes possible to play PVR catchup stream from the PVR program window?

 I have no idea what needs to be added/changed for this, sorry. I would have thought that this works out of the box, no?

**Comment by Tolriq** [comment]
Thanks, Can you explain what a reminder is so I can adapt Yatse UI accordingly?

**Comment by phunkyfish** [comment]
> Thanks, Can you explain what a reminder is so I can adapt Yatse UI accordingly?

Similar in nature to a timer except it does not record. Instead it notifies the user that a programme is about to play. Easy enough to see on latest master for yourself.

**Comment by phunkyfish** [comment]
> Great job @ksooo ! Can you by chance extend your PR to expose Play Catchup or Add Catchup To Playlist or just GetCatchupUrl so in remotes like Kore or Yatse it becomes possible to play PVR catchup stream from the PVR program window?

I think what @basilgello means is the URL that would be used for `Play programme` functionality from an EPG entry. But not related to this PR I think.

**Comment by Tolriq** [comment]
As many I do not have a working PVR setup, reason why I nearly never patched PVR part of JSON myself as unable to properly test. But thanks for the explanation.

**Comment by flubshi** [comment]
It is unrelated, but since there is a good discussion about json-rpc maybe we could think about the mapping of title, episode, tv show title for recordings. I think there is an inconsistent mapping in the rpc that prevents yatse from showing episode titles.
I tried to fix it a while ago: https://github.com/xbmc/xbmc/pull/16024

**Comment by phunkyfish** [comment]
> #16024

From your closed PR this appears to be a much larger core issue and the JSON API is not the right way to fix it. So I think not related to this PR.

**Review by phunkyfish — APPROVED** [review]
Looks good to me from the PVR side, I can't speak to the JSON though.

**Comment by basilgello** [comment]
Let's discuss PVR / JSON-RPC API issues separately: https://github.com/xbmc/xbmc/issues/18642

**Pull request merged**
