### PR TITLE
boost/sha1: cleanup usage of boost/static_assert

### PR DESCRIPTION
**Pull request by stefansaraev**
less intrusive alternative of #9009

### CODE REVIEW

**Comment by FernetMenta** [comment]
/lib/boost will be history soon. no memories :)

**Comment by stefansaraev** [comment]
it is self contained header now, that does not require boost to be installed at compile time ;)

**Comment by stefansaraev** [comment]
@Montellese is this ok for you ?

**Comment by stefansaraev** [comment]
jenkins build this please

**Comment by Montellese** [comment]
As long as it compiles on all platforms sure.

**Comment by FernetMenta** [comment]
@stefansaraev I would rather move this file to websocket's folder than leaving it here in /lib. Sooner or later /lib should disappear completely. If you leave this here I won't take long until this single file get company from other extracted headers of boost. This is like cancer, you got to kill it completely.

**Comment by stefansaraev** [comment]
updated. jenkins build this please again.

**Pull request merged**
