### PR TITLE
Remove XBMC migration steps

### PR DESCRIPTION
**Pull request by sy6sy2**
## Description

Kodi is Kodi since "XBMC 14", we can assume that no one will update from XBMC 13 to Kodi 19.

This PR remove files and/or functions responsible for migrate XBMC user profile to Kodi user profile.

## Motivation and Context

Clean step to remove old things.

## How Has This Been Tested?

I tried Jenkins artefact on my jailbroken iPhone 7.
I have not tested the Linux change.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [X] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ghen2** [comment]
Same for https://github.com/xbmc/xbmc/blob/master/tools/Linux/kodi.sh.in `migrate_home()` routine?

**Comment by sy6sy2** [comment]
I guess yes.
I will update the PR

**Review by ghen2 — APPROVED** [review]

**Comment by ghen2** [comment]
There's also `migrate_to_kodi()` (and a few helpers) in https://github.com/xbmc/xbmc/blob/master/tools/darwin/runtime/preflight.

**Comment by fuzzard** [comment]
Im all for the ios side of things. Ive no idea whether its appropriate to do the linux side though.

**Comment by wsnipex** [comment]
https://github.com/xbmc/xbmc/blob/master/tools/android/packaging/xbmc/src/Splash.java.in#L629

**Pull request merged**
