### PR TITLE
pick OE patches

### PR DESCRIPTION
**Pull request by stefansaraev**
those are all in openelec already. I am unsure about ps4 patch, @lrusak originaly sent it to OE

3rd commit (rii i7 remote) was also sent to OE by lrusak, but I changed key 172 to KEY_HOMEPAGE as it should be. replaces #6495

@lrusak @sraue should I also add our ouya controller patch or it works only on OE because of the ouya kernel patch?

@MartijnKaijser you wanted more stuff upstream, here you go.

EDIT to save some spam: @Montellese for opionion on rss change.

### CODE REVIEW

**Comment by Memphiz** [comment]
looks good to me.

**Comment by mkortstiege** [comment]
+1

**Comment by lrusak** [comment]
PS4 keymap is a duplicate of #4886 

As for the Ouya controller keymap, I'm sure it would be nice to have an upstream keymap for anyone who wants to use it. I see the ouya has been dropped from android support, #6448 , but this doesn't mean that people cannot continue to use the controllers on other platforms.

**Comment by stefansaraev** [comment]
> PS4 keymap is a duplicate of #4886

right. somehow I missed it. #4886 needs rebase and I see I miss an "altname" removal from ps3 map. how should we proceed. ask @lrusak to rebase or I pick and push here and you close 4886 ?

> As for the Ouya controller keymap, I'm sure it would be nice to have an upstream keymap

k. I'll add it.

**Comment by MartijnKaijser** [comment]
i'd say update this PR and we close the other

**Comment by stefansaraev** [comment]
updated (altname dropped ans squashed to ps4 commit). added ouya

**Comment by mkortstiege** [comment]
Looks good to me. Anything left before it's ready for merging?

**Comment by stefansaraev** [comment]
I have nothing else to add.

**Pull request merged**
