### PR TITLE
Core code cleanup

### PR DESCRIPTION
**Pull request by MaxKellermann**

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Travis failure unrelated to this PR.

**Comment by MaxKellermann** [comment]
Rebased. Let's see if Travis has recovered in the meantime.

**Comment by MaxKellermann** [comment]
Rebased again.
It's been two weeks - is nobody interested in merging these commits? I have more code in my queue, and I'm waiting for this one to be merged.

**Comment by fritsch** [comment]
jenkins build this please

thanks @MaxKellermann

**Comment by fritsch** [comment]
Please someone else have a look over that stuff as it is not "my" code and then push. For me it's all fine.

**Pull request merged**
