### PR TITLE
[screensaver.xbmc.builtin.dim] reduce dim minimum threshold

### PR DESCRIPTION
**Pull request by Hitcher**
## Description

Reduces the minimum dim level from 20% to 5%.
## Motivation and Context

This is often requested on the forum.

## How Has This Been Tested?

Yes.
## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by thezoggy** [comment]
The title of this is misleading, it really should be "set dim level minimum threshold". 
Current range: 20 to 100
This would allow 5 to 100
(why limit to 5?)

**Comment by HitcherUK** [comment]
@thezoggy Anything less and just as well use black.

**Review by DaVukovic — APPROVED** [review]
lgtm, thx

**Review by ronie — APPROVED** [review]
lgtm

**Comment by Rechi** [comment]
@wsnipex please always set the version label and milestone before or right after merging a PR.

**Comment by mikesilvo164** [comment]
Thanks @HitcherUK for changing this. I've been doing it manually on fresh installs.

` Anything less and you just as well use black.`

I would agree with this but for me the black doesn't kick in if dialogs are open. Always defaults to dim and I have a plasma so would prefer it to go all black.

**Comment by HitcherUK** [comment]
> I would agree with this but for me the black doesn't kick in if dialogs are open. Always defaults to dim and I have a plasma so would prefer it to go all black.

The reason dim is used when a dialog is open is because any other screen saver (except black) actually uses a window which cannot open if there's a dialog present.

I will make another PR so the dim can go to 0 so you can use that when a dialog is open.

**Pull request merged**
