### PR TITLE
Fix reversed condition

### PR DESCRIPTION
**Pull request by notspiff**
missing a !

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Thought that I fixed it, thanks a lot and Sorry!

**Comment by AlwinEsch** [comment]
jenkins build this please

**Comment by garbear** [comment]
Alwin, you're fired!

But seriously, thanks a lot for undertaking this insanely massive project.

**Comment by akva2** [comment]
No worries alwin shit will break and then we fix it. It might be my previous pr description came off wrong. I didnt sulk that things broke, i just meant that if it was a temporary measure, it was a bad thing to have broken even for a while as i rely on that during dev, was all.

**Pull request merged**
