### PR TITLE
Some network related improvements

### PR DESCRIPTION
**Pull request by Montellese**
## Description
These are a few commits that come from my media import work and are related to networking:
* support IPv4 only UDP sockets
* implement UDP broadcasting (there was even a TODO in the code)
* support HTTP DELETE requests in `CCurlFile`

They don't have an immediate use in Kodi core but might still be useful in the future. I'd also be OK if this is not accepted but I thought before throwing it away I'm going to offer it and see if anybody else finds it useful.

## How Has This Been Tested?
Manually as part of my media import work while the Emby media importer was still written in C++ inside Kodi core.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Review by garbear — APPROVED** [review]
I didn't see any problems. It looks like broadcast is only defined for POSIX?

**Comment by Montellese** [comment]
> It looks like broadcast is only defined for POSIX?

We only have `CPosixUDPSocket` which implements `CUDPSocket`.

**Comment by Montellese** [comment]
Does anyone have an opinion on whether this should be merged into Kodi even though it isn't directly used?

**Comment by fuzzard** [comment]
@Montellese im happy to take this in if its something that your other work ends up using. i know generally we dont want "dead" code, but if its something that benefits you down the line, im sure we can carry it.

Was there anything that you needed to do further with this?

**Comment by Montellese** [comment]
@fuzzard I'm not using any of this code anymore. It comes from a time of my media import work where I had an Emby client written in C++ as part of Kodi core which required additional network functionality like UDP broadcast and HTTP DELETE. So it would alos be dead code in my media import work.

As mentioned before I'm fine if this is closed / rejected.

**Comment by fuzzard** [comment]
Ok, if theres nothing on the horizon, we'll just close for now. Feel free to open again if any of your future works requires it.

**Pull request closed without merging**
