### PR TITLE
bump ffmpeg to 4.0

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

### CODE REVIEW

**Comment by FernetMenta** [comment]
@Rechi @afedchin could you provide the necessary changes for Windows? Not sure what needs to be done there.

**Comment by afedchin** [comment]
sorry currently I have no access to PC
need bump dlls versions here https://github.com/xbmc/xbmc/blob/master/tools/buildsteps/windows/make-mingwlibs.sh#L101

**Comment by afedchin** [comment]
@FernetMenta please cherry pick this commit to fix windows buid https://github.com/afedchin/xbmc/commit/4a84459ad574c8994f1ab5504ef98632adf1ba3d

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
test suite segfault unrelated.

**Pull request merged**
