### PR TITLE
[Krypton] cmake: add FindIconv.cmake, backport of 11665

### PR DESCRIPTION
**Pull request by bkuhls**
backport of https://github.com/xbmc/xbmc/pull/11665

### CODE REVIEW

**Comment by bkuhls** [comment]
Updated patch to check for Iconv only on non-WIN32 platforms, fixes build error detected by AppVeyor.

**Comment by wsnipex** [comment]
please submit to master first

**Comment by bkuhls** [comment]
@wsnipex: Done.

**Comment by MartijnKaijser** [comment]
jenkins build this please
@wsnipex ok for you?

**Comment by wsnipex** [comment]
well, it's not in master yet, cause RPI fails/is missing there.

**Comment by MartijnKaijser** [comment]
oops i thought it was.
@bkuhls i will close this one for now until it is in master.

**Comment by bkuhls** [comment]
The current patch for master does not fail on RPI anymore.

**Comment by wsnipex** [comment]
but only because it's disable for RPI, which it shouldn't be

**Pull request closed without merging**
