### PR TITLE
[filesystem] fix condition for vfs addons in CFileDirectoryFactory

### PR DESCRIPTION
**Pull request by xhaggi**
Without this fix you can't play rared files from videos/movies/series.

@mkortstiege ping you too because we talked about that on slack.

## How Has This Been Tested?

Runtime tested on MacOS

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by mkortstiege** [comment]
Jep, looks like a c/p issue introduced while refactoring that part.

**Comment by MartijnKaijser** [comment]
Jenkins build this please

**Review by mkortstiege — APPROVED** [review]

**Comment by leanderson2006** [comment]
With this can open Rar files? Because it was not opening subtitles inside a rar file.

**Comment by xhaggi** [comment]
Don't know what you mean please use our bug tracker if you want to report a bug. https://trac.kodi.tv

**Pull request merged**
