### PR TITLE
VideoPlayer: dxva - only retain buffers for deinterlacing

### PR DESCRIPTION
**Pull request by FernetMenta**
fix http://trac.kodi.tv/ticket/17100

### CODE REVIEW

**Comment by FernetMenta** [comment]
@afedchin back-refs are only required for deinterlacing, right?

**Comment by afedchin** [comment]
right. but I can't understand how it may cause skips/drops?

**Comment by FernetMenta** [comment]
because it runs out of free buffers.

**Comment by FernetMenta** [comment]
to be more verbose: the log shows 5 render buffers. with current render and two taken by backrefs, there are only 2 left. Most of the time there is only one queued and renderManager can't skip a late frame. if latency can''t be corrected by skipping a frame, VP will ask decoder for a drop. This is more noticeable than a skip.

**Comment by FernetMenta** [comment]
@afedchin ok to merge?

**Comment by afedchin** [comment]
it's ok to merge. but I still dont' understand how it worked before v17?

**Comment by FernetMenta** [comment]
biggest difference to earlier versions is that we don't block the render thread in RM anymore. 

jenkins build this please

**Comment by afedchin** [comment]
my point of view is we just moved the blocking to another place i.e. to the render system. that's why I didn't understand why this causes the issue in v17 and doesn't do the same in v16

**Comment by FernetMenta** [comment]
we did not just move the blocking. blocking in render system requires more elasticity because the render thread can block there for longer than frametime or it may not block at all, if internal buffers are not full. This behaviour is less noticeable on Intel systems.

**Pull request merged**
