### PR TITLE
[musicdatabase] Fix incompatible MySQL queries (Backport)

### PR DESCRIPTION
**Pull request by MilhouseVH**
Backport of #8104

### CODE REVIEW

**Comment by mkortstiege** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by kib** [comment]
jenkins build this please

**Pull request merged**
