### PR TITLE
fixed: make news available when browsing add-on repositories

### PR DESCRIPTION
**Pull request by notspiff**
News was only filled for local add-ons, not from repository listings. Remedy this (i.e. put it into addons.db)

Ref http://forum.kodi.tv/showthread.php?tid=303941

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
Jenkins build this please

**Comment by phil65** [comment]
Nice, but I doubt that this really needs a backport.

**Comment by notspiff** [comment]
stupids fixed (hurra for tests!)

**Comment by MartijnKaijser** [comment]
Jenkins build this please

**Comment by notspiff** [comment]
travis failure is unrelated.

**Comment by tamland** [comment]
This should have been added to the metadata field where all other throwaway information is stored. It's pointless to upgrade and migrate database for things like this.

**Comment by tamland** [comment]
In addition, this schema change is all wrong: In CreateTables 'news' is column 6, in the migration it's column 7, and description is 6/7 depending on that. Also, `GetAddon` and `GetRepositoryContent` have not been updated with `SetChangelog`. See https://trac.kodi.tv/ticket/17582

**Pull request merged**
