### PR TITLE
[depends] curl 7.50.1

### PR DESCRIPTION
**Pull request by MartijnKaijser**
Still had this one lingering around.
I didn't update OSX as i'd better leave that up to some one who can test it.

Already runtime tested on Android

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
https://github.com/curl/curl/releases/tag/curl-7_50_1 is out

**Comment by MrMC** [comment]
and so is a PR to fix curl :)

**Comment by MartijnKaijser** [comment]
Did they already fix their broken 7.50.0?

**Comment by wsnipex** [comment]
already fixed in 7.50.1: https://github.com/curl/curl/commit/d6604524ad24daf4581efbe0020da058d2b3af84

**Comment by MartijnKaijser** [comment]
updated to 7.50.1
jenkins build this please (will do run test on droid)

**Comment by MrMC** [comment]
That PR also contains a fix to the defs we use. Including neglecting the return. This error has been in the code base for a long time.

**Comment by fritsch** [comment]
Will rebase tonight and drop the now obsolete ifdef workaround.

Am 03.08.2016 7:23 nachm. schrieb "Scott Davilla" <notifications@github.com

**Comment by MartijnKaijser** [comment]
uploading with correct filename helps
jenkins build this please

**Comment by MartijnKaijser** [comment]
jenkins build this please 
Note: need to update commit message

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Pull request merged**
