### PR TITLE
[videodb] use GetNavCommon for tags

### PR DESCRIPTION
**Pull request by mkortstiege**
Fixes tag grouping for content type tvshows in smart playlists. I had to add an extra join since we're not fetching the `tvshow_view` by default.

@Montellese for review please.

### CODE REVIEW

**Comment by Montellese** [comment]
Are you sure that the additional `JOIN` for `tvshow_view` is necessary because `episode_view` already contains an `idShow` column.

**Comment by mkortstiege** [comment]
I think it's needed when having rules based on the tvshow_views counts (like eg. totalCount).

**Comment by Montellese** [comment]
OK in the context of smart playlists that might be the case yes. I only considered the logic in `CVideoDatabase::GetNavCommon()` which does not need it. Maybe add a comment about why it's there so we don't have to remember (because we won't).

**Comment by mkortstiege** [comment]
Done. Added a one-line comment so we know why it's there.

**Comment by mkortstiege** [comment]
Squashed. jenkins build this please.

**Comment by mkortstiege** [comment]
@Montellese is this ready for Isengard or should be postpone it?

**Comment by Montellese** [comment]
If you have checked that the normal tag node and adding/removing items to/from tags still works it should be fine.

**Comment by mkortstiege** [comment]
Jep, still works as intended. jenkins build and merge.

**Pull request merged**
