### PR TITLE
VideoPlayer: OpenGL - fix HDR metadata MaxCLL

### PR DESCRIPTION
**Pull request by FernetMenta**
MaxCLL can be 0 although lightMetadata is set.

@afedchin /fyi on OpenGL this results in a white screen

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
iirc we have issue on windows with green screen with HDR. Could that be related?

**Comment by FernetMenta** [comment]
hmm, not sure. green in general means that nothing gets rendered.

**Comment by afedchin** [comment]
> iirc we have issue on windows with green screen with HDR. Could that be related?

if I understand you correctly green screen can appears if PS rendering fails. Without a debug log I can't say more.

**Comment by afedchin** [comment]
@FernetMenta if you have spare time can you add the same for windows here https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/VideoRenderers/WinRenderBuffer.cpp#L349
I'd be very grateful

**Comment by FernetMenta** [comment]
@afedchin , will do

**Review by afedchin — APPROVED** [review]
looks good. thank you

**Pull request merged**
