### PR TITLE
python: use kodi provided cert if available

### PR DESCRIPTION
**Pull request by FernetMenta**
fix ssl on systems having no OpenSLL, i.e. Pi and OSX

### CODE REVIEW

**Comment by FernetMenta** [comment]
@wsnipex @popcornmix /cc

**Comment by wsnipex** [comment]
this will override any system certs on all platforms, which is imho a no-go.
On linux I expect my /etc/ssl/certs to be used.

**Comment by FernetMenta** [comment]
> this will override any system certs on all platforms, 

why do you think so. per default we have no cert in this location, hence system provided is used

**Comment by wsnipex** [comment]
because we should install the cert per default. Or do you want to leave that to the user?

**Comment by FernetMenta** [comment]
I though we install it on systems where we don't have a system provided one. With this code change the packager can decide what cert to use. What is wrong with this?

**Comment by wsnipex** [comment]
as discussed in the other PR, there is no definitive list of platforms where a cert is always available.
e.g. I'd have expected rpi to just work, but as @popcornmix noted, it doesn't when using unified deps.

So it makes sense to always install it, but only use it if no system wide is found. Imho checking if /etc/ssl/certs exists should be enough.

**Comment by stefansaraev** [comment]
checking for /etc/ssl/certs would not be enough.
one could use SSL_CTX_set_default_verify_paths() to check out if openssl has default ca bundle / ca dir

**Comment by FernetMenta** [comment]
How can we check if our python is used? Then we would use our cert with our python. Does this make sense?

**Comment by wsnipex** [comment]
something like this should work: https://github.com/wsnipex/xbmc/commit/c97c69252b068c362278313f753a07fab5087d9b

didn't have time to really test it, since the PC I'm on atm is very slow. Cmake is completely untested

**Comment by ksooo** [comment]
@FernetMenta any opinion on what @wsnipex suggested? Currently I still need to patch my Mac build to get certain stuff running. That kinda sucks. ;-)

**Pull request closed without merging**
