### PR TITLE
FFmpeg: Bump to 2.8.6-Jarvis-rc2

### PR DESCRIPTION
**Pull request by fritsch**
Update to latest 2.8.6 version.

### CODE REVIEW

**Comment by fritsch** [comment]
jenkins build this please

**Comment by afedchin** [comment]
@fritsch can we temporary include this https://github.com/FFmpeg/FFmpeg/commit/406f30072e4ecc51c101a27a790bc3cf1a22bad4 in our branch? it should fix an issue reported on the forum http://forum.kodi.tv/showthread.php?tid=257835&pid=2226072#pid2226072

**Comment by fritsch** [comment]
@afedchin yes, every upstream patch is allowed - we can drop later! I will pick

**Comment by fritsch** [comment]
Updated!

jenkins build this please

**Comment by afedchin** [comment]
thanks

**Comment by mazeyx** [comment]
will the new ffmpeg make it into v16 jarvis?

**Comment by fritsch** [comment]
@mazeyx something special you need from it? Or just latest and greatest syndrome?

**Comment by mazeyx** [comment]
@fritsch dxva fix please. garbled output on pvr.

**Comment by fritsch** [comment]
@mazeyx It's up to the release manager, but your issue gets a +1 from me :-)

**Pull request merged**
