### PR TITLE
UI sounds addons

### PR DESCRIPTION
**Pull request by tamland**
This adds a new addon type for UI/navigation sounds which really have no business being bundled with skins.

No idea if this is the sort of thing you intended for your resource addons @Montellese but it seems to integrate very well requiring no changes to the underlying media loading logic.

### CODE REVIEW

**Comment by Montellese** [comment]
Yeah that's exactly what I intended it for.

You could have only taken three (plus the win32 and osx/ios) of the nine commits to keep this to a minimum and to make rebasing easier ;-)

I'll take a look at the changes later although navigational sounds is the first thing I turn off after installing Kodi.

**Comment by Montellese** [comment]
Looks good in general.

**Comment by ronie** [comment]
i'm afraid i fail to see the point...
what's the benefit of skins submitting there sounds as a separate addon?

it's not like skinners regularly update their soundfiles, most likely they never will.

**Comment by tamland** [comment]
@ronie The point is to be able to install/change independently of what skin you use. The first thing *I* do after installer kodi is installing some more pleasant custom sounds into the userdata folder, which would be much easier to do with addons. For one, most skins just copy paste the confluence sounds secondary, it has nothing to do with skins. Nevertheless, it's fully backwards compatible skinners for some reason want to force some sound files to only be used by one skin.

**Comment by topfs2** [comment]
+1 from me, this makes perfect sense to decouple from skins. If anything we
could investigate logic for skins to recommend sounds and let default be
suggested.
Den 27 feb 2015 19:13 skrev "tamland" <notifications@github.com>:

**Comment by wyrm65** [comment]
As a skin writer I feel I should point out a minor fly in your ointment. In my skin I use a trick to play a sound when the user tries to scroll past supplied controls on screen. The trick is to display a custom dummy screen when the user <ondirection > away from from valid controls, ie to try to go left when there is no left to go to. In the sounds section of the skin I play a sound of my choice when the dummy screen is opened.

How will this PR handle this use case, as only I know the name of the custom screen that will trigger the playing of the sound file that I have included in the sound directory?

**Comment by tamland** [comment]
@wyrm65 Nothing of relevance to this PR. Ideally that's a feature that should be added to core so there's a standard way to do that for all skins, but you are free to supply those sounds only with your skin, or ask other sound addon authors to add support for specific features in your skin.

**Comment by da-anda** [comment]
will this finally allow image packs for skins? Like a resource addon for all the studio logos? Using a different extension point though

**Comment by Montellese** [comment]
@da-anda: Yes that's one of the things I had in mind when I added the resource addon type. There could be a new addon type `resource.images` which would result in addons that simply provide some images which could then be referenced using `resource://resource.images.<addon-id>/<some-image>` from anywhere in the skin.

**Comment by tamland** [comment]
You mean `resource://<addon-id>/` right? That's what I'm using here.  Or did you change that again to include addon type?

**Comment by Montellese** [comment]
Yeah that's right, I just wanted to make it more obvious that the addon-id would start with `resource.images.`.

**Comment by tamland** [comment]
Rebased. I guess the only thing left is to decide what to do with the default. I assume people want the confluence sounds for that? And the current default setting is the special SKINDEFAULT so I'm not sure if changing that would break it or move people to the new value. Any ideas @Montellese?

**Comment by mkortstiege** [comment]
Can't we default to OFF for all skins that are not shipping their own or reference an existing resource.uisounds package. Confluence sounds should be used as fallback.

**Comment by tamland** [comment]
Nudge @Montellese. I'm a bit lost at what to do with the settings here. Is there any way to get the old value from the settings? Changing the default seems to destroy the old value immediately if was the default... What I'm trying to do is migrate people who are using the default setting such that confluence users get the new default value (`resource.uisounds.confluence`) while everything else keeps the old SKINDEFAULT. Otherwise I see no way around breaking it for people relying on skin provided sounds.

**Comment by Montellese** [comment]
@tamland: Did you specify in the setting's XML definition that you would like to perform an update? In that case the `OnSettingUpdate()` callback should (TM) be called with the old default value. Either way you can detect in there if the setting is set to the default value and if that's the case just adjust the value in case the user is using confluence.

**Comment by tamland** [comment]
@Montellese *Almost*:). It gets called with old value, but I can't see a way to check if it was default. `IsDefault` always return false. You see, I don't want to adjust the value *every* time, just the once. E.g if you change back to confluence later that should migrate this setting, right? If there's no simpler way, I guess migrating every instance of "SKINDEFAULT" to a new value should work.

**Comment by Montellese** [comment]
Well in this case you know what the old default value was right?

**Comment by tamland** [comment]
Man, I can't get this to work. The result from `OnSettingUpdate` seems to be ignore if the setting does't have `default="true"` so the update part works, despite being a bit weird. If you start with confluence it correctly change to `resource.uisounds.confluence` iff sounds are set to default. Problem now is, if you change to another skin after it is updated, it for some reason "magically" change the value *back* to `SKINDEFAULT`.. No idea why. It doesn't call `OnSettingUpdate` again or anything. Could you have a look at it @Montellese?

**Comment by tamland** [comment]
@mkortstiege could you so kindly do a xcode sync?:)

**Comment by mkortstiege** [comment]
@tamland please pick https://github.com/mkortstiege/xbmc/commit/242a60706de3730afd41b24e8f2684dca79381c5

**Comment by zag2me** [comment]
Awesome! The old HTPC software I used to manage had "Sound Themes" and "Image Themes" and it worked very well. Nice to see Kodi get them as well. Definitely agree that they should be separate from skins. You can check a few of them out here if your interested in how it works:
http://www.meedios.com/OpenMAIDOS/thelist.php?bc&ptype=theme&program=meedio&start=0&nb=50

**Comment by tamland** [comment]
jenkins build this please

**Comment by tamland** [comment]
Any native speakers/ux people want to comment on the wording? Currently a mix of navigation sounds, sound skin and sound scheme are used which I though was all weird so I just made something up. I have no idea if 'UI sounds' makes sense or which does. @da-anda ?

**Comment by da-anda** [comment]
will have a look. ping @jjd-uk as native speaker

**Comment by da-anda** [comment]
IMO it would be nice if we could group our add-on categories and have something like:

* Look and Feel
  * Userinterface (Skin)
  * Sound Themes
  * Visualizations
  * Screensaver
  * Languages

but that's independet of the name. "UI Sounds" or "Sound Themes" (or only "Themes" maybe) would be fine for me, having a little preference on "Sound Themes" though. Other opinions?

**Comment by da-anda** [comment]
@tamland - jjd-uk pointed out on IRC that we already have the label/setting "Play GUI Sounds", so maybe use "GUI Sounds" for now until we find something better. My restructure proposal can also be ignored for this PR - let's discuss it on the forums (where there should already be some structure proposal from @MartijnKaijser somewhere). So good to go from my end when category label is changed to "GUI Sounds" for now.

**Comment by jjd-uk** [comment]
Yeah for consistency I would use "GUI sounds" to fit in the "Play GUI Sounds" setting

**Comment by tamland** [comment]
Thanks guys. Changed the rest of the settings that use "scheme"/"navigation" to "GUI sounds" too.
jenkins build this please

**Comment by tamland** [comment]
jenkins build this please

**Comment by tamland** [comment]
Ping @Memphiz is the darwin build changes in the last commit ok? I just removed every reference to "sounds" I could find.
@MartijnKaijser There's already API changes merged for beta1 so I guess this one is ok too? Please clarify what's allowed and what isn't and when the freeze happens.

**Comment by Memphiz** [comment]
Yes those darwin packaging changes look fine

**Comment by MartijnKaijser** [comment]
If this doesn't break current behaviour for skins it's fine to go in

**Comment by tamland** [comment]
Other than the change of `SKINDEFAULT` to `resource.uisounds.confluence` as the default it shouldn't break skins any way, no. So, if nobody want to say this is too big and intrusive for beta it goes in

**Comment by MilhouseVH** [comment]
After this PR, if settings are queried using JSON there are two new errors that appear in kodi.log:
```
22:08:05 T:140534752474880   ERROR: GetDirectory - Error getting /home/neil/projects/kodi.git/sounds/
22:08:05 T:140534752474880   ERROR: GetDirectory - Error getting special://xbmc/sounds/
```
Prior to this PR (or with this PR reverted), there is no such error.

Obviously, the `sounds` directory no longer exists following this PR, but somewhere in the (maybe JSON) code it is still being accessed.

Tested on Ubuntu 14.10, latest master (febf2372553e79ea65aef080a8da0ae40e791b89)

Example JSON query:
```
curl -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "params": {"level": "expert"}, "method": "Settings.GetSettings", "id": "libSettings"}' http://localhost:8080/jsonrpc
```

**Comment by tamland** [comment]
@MilhouseVH I think I see the issue.  It's not json-rpc specific, but GetDirectory in the settings print this message. Same in the gui. It's expected when the directories doesn't exist, not actually an error.

**Comment by MilhouseVH** [comment]
Thanks for looking, although I guess the point is that now that the `sounds` directory has been removed, shouldn't whatever code is still looking for the non-existant `sounds` directory be updated to look elsewhere, or just stop looking? If it's not an error - and I understand why you say it's not - then it shouldn't be logged as an error. :)

**Comment by FernetMenta** [comment]
most likely the reason for http://trac.kodi.tv/ticket/15956

**Comment by Montellese** [comment]
@FernetMenta: It's certainly the reason for that error log message but probably not for no audio in videos because it only touches GUI sounds.

**Comment by FernetMenta** [comment]
@Montellese audio engine terminates and this is probably a result of this error

**Comment by tamland** [comment]
The "Error creating" error? Whatever is attempting to create that directory should probably be removed as that directory isn't used anymore.

**Comment by uNiversaI** [comment]
Im now starting to see a flood of logs from windows and Linux with errors regarding the sound directories which are a result of the upgrade from v14/v15

Linux side some log (not my log but I have this and Im on v16) http://xbmclogs.com/pafwid7ak
````
20:29:42 T:140533740615616   ERROR: GetDirectory - Error getting /usr/share/kodi/sounds/
20:29:42 T:140533740615616   ERROR: GetDirectory - Error getting special://xbmc/sounds/
20:29:42 T:140533740615616   ERROR: GetDirectory - Error getting /usr/share/kodi/sounds/
20:29:42 T:140533740615616   ERROR: GetDirectory - Error getting special://xbmc/sounds/
```

**Comment by tamland** [comment]
As already mentioned it is expected behavior and a case of bad logging in GetDirectory, not and error. The directories are read for backwards compatibility. It will be removed in the future.

**Comment by finalmakerr** [comment]
Isengard will work with resource.uisounds?
And does it support auto update from a repository?
If i update my skin to Jarvis and make that type of addon later on, will it be auto installed on new skin update or should users reinstall the skins?

**Comment by MartijnKaijser** [comment]
@finalmakerr ask on the forum

**Pull request merged**
