### PR TITLE
[Android] Move string literals to resource files

### PR DESCRIPTION
**Pull request by joseluismarti**
## Description
Declare the corresponding resource entries and replace the strings in the code with a resource usage.

Replace deprecated two-letter codes: The Hebrew ("he") language code is rewritten as "iw" and Indonesian ("id") as "in".

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by ksooo** [comment]
Can’t this be handled via Weblate, the tool we usually use to translate all our strings?

**Comment by joseluismarti** [comment]
yes, this PR extracts the strings, the next step will be to add these localized resource files to Weblate

**Comment by MartijnKaijser** [comment]
In that case I suggest to not do the Spanish translation already as it will be overwritten by weblate anyway

**Comment by joseluismarti** [comment]
> In that case I suggest to not do the Spanish translation already as it will be overwritten by weblate anyway.

Weblate will recognise that the new string keys are already incorporated in the Spanish translation file and will not overwrite them.

> For all others we use es_es, en_gb, en_us, and so on as language indicators. Can it be done in this case as well or are there limitations?

Android uses a directory for each language/locale, which includes the localised resource file:

`res/values-es-res/strings.xml`  -> Spanish (es) in Spain (ES)
`res/values-es-rar/strings.xml`  -> Spanish (es) in Argentina (AR)
...

> What happens when strings aren't translated (yet)? Fallback to English or blank?

If the language file does not exist or a key string is missing, it will use the default strings (`res/values/strings.xml`).

**Comment by gade01** [comment]
Weblate will automatically sync with the source file and add every new translation added in this PR to the other languages.

However, translations should never be added at Github.
They should be done at Weblate: https://kodi.weblate.cloud/projects/kodi-core/kodi-main-android-strings/es_es/

Otherwise it could potentially lead to merge conflicts.

**Comment by joseluismarti** [comment]
Sorry, I thought the file was not yet in Weblate. In that case you are right, it has to be done through Weblate.

**Comment by joseluismarti** [comment]
This PR has been around for a long time, it can be merged without any issues.

**Comment by joseluismarti** [comment]
This PR is complete, there are no comments pending or anything to do, if anyone wants to give it a go-ahead :+1:

**Pull request merged**
