### PR TITLE
[GUIInfo] allow infolabels in all string comparison methods

### PR DESCRIPTION
**Pull request by ronie**
## Description
currently the only string comparison method that can compare 2 infolabels, is `String.IsEqual()`.
the other methods only can compare an infolabel to a fixed string.

this change adds support for comparing 2 infolabels to the other string comparison methods:
- `String.StartsWith()`
- `String.EndsWith()`
- `String.Contains()`

## Motivation and Context
requested on the forum: https://forum.kodi.tv/showthread.php?tid=355909&pid=2964525#pid2964525

## How Has This Been Tested?
i have tested all possible combinations (and double-checked all comparisons are done case-insensitive):
```
String.IsEqual(ListItem.Label, Skin.String(test))
String.StartsWith(ListItem.Label, Skin.String(test))
String.EndsWith(ListItem.Label, Skin.String(test))
String.Contains(ListItem.Label, Skin.String(test))
String.IsEqual(ListItem.Label, Foobar)
String.StartsWith(ListItem.Label, Foobar)
String.EndsWith(ListItem.Label, Foobar))
String.Contains(ListItem.Label, Foobar)
```

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [C] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by roidy** [comment]
@ronie Could this also be added for the Integer compare methods and if possible be back ported to Kodi 19.

It odd it was only added for string compare methods and not Integers as well. I need it to be able to fade out list items that are before the focused position using:-

<animation effect="fade" start="100" end="10" time="0" condition="IsLess(ListItem.CurrentItem,Container(9000).CurrentItem)">Conditional</animation>

**Comment by enen92** [comment]
@roidy your request is already available in https://github.com/xbmc/xbmc/pull/21352 I think.
Also no new features as backport pr's, only bug fixes.

**Comment by roidy** [comment]
@enen92 Thanks, shame it can't be back ported, I really don't want my skin to be Nexus only.... What's the chances we could call the fact that Integer compares between two info labels doesn't work a bug and fix it with a back port.... ;D

**Comment by enen92** [comment]
None (:
They are new features.

**Comment by roidy** [comment]
Lol... Oh well it was worth a try. Thanks anyway 👍

**Pull request merged**
