### PR TITLE
VideoPlayer: fix DisplayAfterSeek

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

@phil65 as requested :)

### CODE REVIEW

**Comment by phil65** [comment]
Thanks. Does it need backporting?

**Comment by phil65** [comment]
Just tested, issue is fixed. Thanks.

**Comment by phil65** [comment]
jenkins build this please.

**Comment by FernetMenta** [comment]
> Thanks. Does it need backporting?

this was broken for a very long time. I won't backport it and risk other breakage.

**Comment by phil65** [comment]
ok, makes sense. (though I wonder why noone complained about this yet :) )

**Pull request merged**
