### PR TITLE
[linux][gbm] cleanup, fixes, and atomic prep

### PR DESCRIPTION
**Pull request by lrusak**
moves some of the atomic code that can be shared between atomic and legacy drm to DRMUtils

add setting nullptr to some variables

fixes headers

adjust log formatting

build and runtime tested

@Kwiboo for review

### CODE REVIEW

**Comment by lrusak** [comment]
@a1rwulf I pushed https://github.com/xbmc/xbmc/pull/13100/commits/795da24579b16d3032fd4d7f5872bfef855588c8 to fix the format issue you have on braswell.

**Comment by lrusak** [comment]
@Kwiboo I reworked the init now that I moved all the plane detection stuff. please have a look at https://github.com/xbmc/xbmc/pull/13100/commits/9b720be016ebcb6b23bb634772eda65545b8f3ab

**Comment by a1rwulf** [comment]
@lrusak thx. Looks good now!

**Comment by Kwiboo** [comment]
@lrusak looks good but please drop https://github.com/xbmc/xbmc/pull/13100/commits/d76bd4ff4b9dc00af3d04ed0fb79c1fcecaa9071 and replace with https://github.com/Kwiboo/plex-home-theater/commit/ab3e645fc99e8ddbe54a96e741b8d1452d6bed78 that fixes uneven lock/release of surface buffer and minor tearing on Rockchip

**Pull request merged**
