### PR TITLE
[backport] CGUIViewStateMusicSmartPlaylist: fix default sorting of songs over UPnP (fixes #16192)

### PR DESCRIPTION
**Pull request by Montellese**
This is the backport of #8010 for Isengard.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
@Montellese this might need some adjustments as it failed

**Comment by Montellese** [comment]
Yeah the change from `Get()` to `GetInstance()` for all singletons is causing a lot of backporting headache.

**Comment by Montellese** [comment]
Let's try again. jenkins build this please

**Comment by Montellese** [comment]
@MartijnKaijser: This time only a binary addon failed to build on OSX-32 and all other builds are fine.

**Pull request merged**
