### PR TITLE
Controller dialog: Feature groups

### PR DESCRIPTION
**Pull request by garbear**
This PR puts controller features into groups in the controller dialog, similar to how settings groups work.

feature groups

### CODE REVIEW

**Comment by da-anda** [comment]
just noticed in the screenshot that the word "configuration" is cut off in the dialogs title bar

**Comment by garbear** [comment]
that's because I resized the window. somewhere some bounding boxes aren't getting updated when the window is resized

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
@ronie @BigNoid @phil65 any objections?

**Comment by ronie** [comment]
nope.

**Comment by HitcherUK** [comment]
Why are there 2 labels with the same ID (8)?

**Comment by garbear** [comment]
An error. The labels should be: https://github.com/garbear/xbmc/blob/8824342/xbmc/games/controllers/windows/GUIControllerDefines.h

**Comment by garbear** [comment]
Problem is harmless, the first #8 is left over from a rebase. Fix is: 81b9e7f1d

Should I send the fix here or to the skin.estuary repo?

**Comment by MartijnKaijser** [comment]
@garbear master branch here

**Pull request merged**
