### PR TITLE
Patch to support again headless mode on linux (X11 & GBM) builds

### PR DESCRIPTION
**Pull request by sinopsysHK**
## Description

Aiming at providing on Leia a headless mode as it was available in previous versions, a new dedicated WinSystem has been created to prevent any windowing and rendering tasks while having all other services running.

## Motivation and Context

Provide a headless mode that enable to have a full time running instance to manage shared libraries updates (as a back-end) so that any other kodi client kick starts with up-to-date libraries.
As the broadest use of this kind of setup is with Docker, I focused mainly on X11 and GBM setups (compiled and tested both with GL renderer).
I did propagate the change on the other platforms to limit compilation breaks as much as possible but I couldn't test it.

## How Has This Been Tested?

I ran the full kodi tests without issues and additionnally launched the new built kodi in headless mode and browsed its web server, requested library updates/cleaning and check it did not crash.
I performed thoses tests on a ubuntu 18.04.1 VM running in VMWARE with win7 host.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [X] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [X] I have updated the documentation accordingly (not the wiki)
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by FernetMenta** [comment]
@lrusak you asked for my opinion. Here ist is.
If you want to run Kodi without a GUI, Kodi's GUI component has to be made optional. That is the only correct way. That approach will also result in a single build for X11 and Wayland.

This change here is a disaster from a design and architecture point of view. All gl methods still get called without a valid gl context. No need to go into the details if the approach is very wrong.

btw: if you want to run Kodi headless, you can start X11 with the dummy driver (xserver-xorg-video-dummy). That results in a much more robust configuration than this code here.

**Comment by pkerling** [comment]
@sinopsysHK Why don't you use Xvfb or xpra etc. for your use case?

Also to the extent of my knowledge we have never offered headless mode in any prior version.

**Comment by pkerling** [comment]
@FernetMenta I fully agree. With the option of running on a virtual framebuffer being there already, I do not think there is any compelling reason to include this in Kodi core despite the evident shortcomings.

@sinopsysHK Maybe other team members will have a differing opinion, but from my personal POV the chances of having this PR accepted with your current approach are slim. I am sorry for the time you have put in :( but as @FernetMenta explained this would further degrade our architecture. The correct solution is a lot more involved, I'm afraid.

**Comment by sinopsysHK** [comment]
There are many xpra options or GBM with OffScreenResolution that I tried and both work meaning process runs as expected and all services are performing properly.
On the other hand both of them have a very heavy CPU use due to all the rendering computations that are still running despite being displayd.

I agree with you that in terms of design/architecture my proposal is very dirty but I cannot rework completely the current design as it it strongly manggled between GUIComponent, Renderer, WinSystem so it would be a much bigger effort to support it in a clean modular way.

**Comment by sinopsysHK** [comment]
> @sinopsysHK Why don't you use Xvfb or xpra etc. for your use case?
> 
> Also to the extent of my knowledge we have never offered headless mode in any prior version.

My bad, it was a patch maintained aside from Kodi codebase and used in various Docker containers. But correct it has never been integrated.

**Comment by fritsch** [comment]
@sinopsisHK

thx very much for your work on this. You exactly hit the weak spot of kodi. Even internally it is very hard to convince devs to not even more tangle common code like windowing with application for short wins driving future features like headless or PIP far away. This is constant arguing of the but but but feature folks and rearchitecturing, which yeah costs a life of time.

If you find out what especially causes this high load, e.g. swap buffers not blocking perhaps we could make you a short term advanced setting to block some 100 Ms there. Not to solve sth, but to improve your usecase to win more time for the only proper approach stated above.e.g. you can use kodi and help towards the great rearchitecturing.

Thx again and also thx for your agreement in the architectural view!

**Comment by sinopsysHK** [comment]
> If you find out what especially causes this high load, e.g. swap buffers not blocking perhaps we could make you a short term advanced setting to block some 100 Ms there. Not to solve sth, but to improve your usecase to win more time for the only proper approach stated above.e.g. you can use kodi and help towards the great rearchitecturing.
> 

I guess this is in the CXBApplicationEx::Run loop : each time I interrupt in debug mode I interrupt in CGLContextEGL::SwapBuffers (currently waiting 20ms) but I cannot tell whats going on prior to that as I have limited investigation capabilities (I did not succeeded to let kodi run with xpra on my ubuntu VM).

Thank you for the proposal to extend further the sleep time but this is neither a satisfying option as it wouldn't provide the expected benefits and wouldn't serve any other purpose so it is almost as dirty as my proposed hack.

Do you have somewhere any material regarding the tentative target architecture ?

**Comment by phunkyfish** [comment]
@sinopsysHK is it ok if this is closed?

**Comment by sinopsysHK** [comment]
Yes it is ok as I understood it wasn’t agreed to add this in core repository.

**Pull request closed without merging**
