### PR TITLE
[dvdnav] Refactor, fix aspect ratio, add video codec

### PR DESCRIPTION
**Pull request by ace20022**

### CODE REVIEW

**Comment by ace20022** [comment]
@Voyager1 have you written the original implementation? Just because I have some questions.

**Comment by Voyager1** [comment]
@ace20022 - no I have only contributed to things like debugging and serialstring (for disc resume). re. your questions, I can always try :-)

**Comment by ace20022** [comment]
@Voyager1 @FernetMenta could please review? I want to delay further refactoring/cleanup.

**Comment by FernetMenta** [comment]
looks good to me. wasn't this already part of some other PR?

**Comment by ace20022** [comment]
No, and thx.

jenkins build this please

**Comment by Voyager1** [comment]
great - I tested the Spongebob example (previously uploaded for menu issues) and it now plays correctly with 4:3 AR! I'm assuming that your fix is valid. 
No comments on the other refactoring stuff, it makes sense to me.

**Comment by ace20022** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
@ace20022 the failed ones were not relevant so think you can just merge

**Pull request merged**
