### PR TITLE
[PVR] Cleanup: Factor out CPVRTimerType setting values into class CPVRIntSettingValues.

### PR DESCRIPTION
**Pull request by ksooo**
More cleanup to eliminate duplicate code.

1st commit is only clang-format to make diff of the second commit readable and Jenkins happy.

Runtime-tested on macOS, latest xbmc master.

@phunkyfish can you please review.

### CODE REVIEW

**Review by phunkyfish — APPROVED** [review]

**Comment by phunkyfish** [comment]
Jenkins doen't like this at all.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
> Jenkins doen't like this at all.

Indeed. Needed a code fix. Now only WIN-64 is not green, but that's unrelated.

**Comment by ksooo** [comment]
WIN-64 Jenkins error is unrelated.

**Pull request merged**
