### PR TITLE
[ios] - allow mapping of up to 3 finger taps

### PR DESCRIPTION
**Pull request by Memphiz**
@NedScott mind testing this one? ^^

### CODE REVIEW

**Comment by NedScott** [comment]
It works, thank you very much!

I get some funky behavior on the file manager, though. I can't seem to select/open any buttons in <myfiles>. I noticed it because I normally copy keymaps via the file manager and then restart. Maybe it's unrelated to this, so I will try to test with other nightlies and with changing just the default keymaps.

**Comment by Memphiz** [comment]
Can't think of how this could influence anything other then what it does (adding 3 finger tap detection for being able to map it ...)

**Comment by NedScott** [comment]
It's unrelated to this PR. Same issue happens in a nightly build (20150917)

I also tested with the three finger swipe builds, and those builds were fine. It doesn't look like it is related to any of the iOS touch changes. I'll do a bug report for that in a bit.

This PR itself seems to function as expected and with no issues. Thanks again for adding this :D

**Comment by Memphiz** [comment]
thx for trsting - using my ios only merge right here again (or in other words - by the power of grayskull)

**Pull request merged**
