### PR TITLE
[dxva] Added dxva hevc decoding.

### PR DESCRIPTION
**Pull request by afedchin**
WIP because something went wrong in ffmpeg. Decoding starts fine and after a couple seconds I got 

```
ffmpeg[9C0]: Assertion rpl->nb_refs <= (sizeof(pp->RefPicSetStCurrBefore) / sizeof((pp->RefPicSetStCurrBefore)[0])) failed at libavcodec/dxva2_hevc.c:186
```

ping @FernetMenta 
@MartijnKaijser can you try this on your Intel hw (I know it supports dxva hevc :))

### CODE REVIEW

**Comment by afedchin** [comment]
forgot: this basen on #6636

**Comment by FernetMenta** [comment]
we need to solve an old issue. ffmpeg sets threading context on avcodec_open2. we want to have frame threading enabled but if a hw decoder is selected in GetFormat,  switch to slice threading.

**Comment by MartijnKaijser** [comment]
want me to hold off testing until issue resolved?

**Comment by afedchin** [comment]
@FernetMenta it is a dxva related issue or all hw decoders? We can set slice threading into decoders. as an example after initializing hw context. what do you think?

@MartijnKaijser just try current branch. I need to understand it is an issue of ffmpeg xor my hw.

**Comment by FernetMenta** [comment]
@afedchin it's an issue for all hw decoder.

> We can set slice threading into decoders. as an example

does not work. threading context is allocated before get_format is called and can't be changed. according to this http://ffmpeg.org/pipermail/ffmpeg-cvslog/2013-March/062620.html it should work with frame threading. I haven't found the root cause yet.

**Comment by MartijnKaijser** [comment]
here's my log
http://xbmclogs.com/pbtvn8hzk

in master build i do get picture. with this build just a grey screen for hevc playback

**Comment by FernetMenta** [comment]
I think I have found something. I have frame threaded h264 working. Not tried hevc but should work too.

**Comment by afedchin** [comment]
@MartijnKaijser thanks. I thinks it is a ffmpeg issue bacause I got same error with LAVFilters

**Comment by FernetMenta** [comment]
are you saying that it does not work with sw decoding either? can you share the sample you are testing with?

**Comment by afedchin** [comment]
@FernetMenta I think you are missed with comments. but yes with #6654 It doesn't work with sw decoding also. I cannot share sample because of its illegal origin :)

**Comment by FernetMenta** [comment]
that is strange because 6654 should not have any influence on sw decoding.

**Comment by afedchin** [comment]
I've tried a few another samples from http://forum.doom9.org/showthread.php?t=171219. All samples works fine with 6654 and slice threading (only for hevc) also with dxva. My first sample work only with sw decoding.

**Comment by FernetMenta** [comment]
I'll send a patch to ffmpeg which fixes the deadlock for frame threading

**Comment by FernetMenta** [comment]
there was already one https://github.com/FernetMenta/FFmpeg/commit/d908ddb9cf407ac451b808e400fc3491dfcfe65d

**Comment by afedchin** [comment]
@FernetMenta this doesn't work. dxva receives a bad pointer to surface on decode. frame->data[3] points to nirvana.

**Comment by afedchin** [comment]
GetFormat is called 4 times (i suppose one per thread) and it seems what ffmpeg trys to use a surface from another context. will try again tomorrow

**Comment by afedchin** [comment]
@FernetMenta I've tested clean build with https://github.com/FernetMenta/FFmpeg/commit/d908ddb9cf407ac451b808e400fc3491dfcfe65d and 6654. Still not works. I suggest disable hevc-dxva decoder till solve issue.

**Comment by FernetMenta** [comment]
not sure what you suggest. this entire PR is about enabling HEVC for DXVA. once we have solved the issue, we can merge it.

**Comment by afedchin** [comment]
never mind. You are right :)

**Comment by FernetMenta** [comment]
I have some ideas. Maybe I have some time this evening to try those.

**Comment by FernetMenta** [comment]
to more fixes for ffmpeg make it work https://github.com/FernetMenta/FFmpeg/commits/release/2.6-xbmc

**Comment by afedchin** [comment]
I'll try it asap

**Comment by afedchin** [comment]
@FernetMenta it still not works. It calls get_format once and then produces an error repeatedly:
```
ffmpeg[1860]: [hevc] get_buffer() failed
ffmpeg[1860]: [hevc] thread_get_buffer() failed
ffmpeg[1860]: [hevc] Error parsing NAL unit #1.
```
in different threads.

Still works with slice threading.

**Comment by FernetMenta** [comment]
this looks like you dropped the first ffmpeg again. you need the top 3 patches of my branch

**Comment by afedchin** [comment]
I've built ffmpeg from your branch. Not exactly so. I've replaced hevc.c in 2.6-test release with hevc.c from your branch.

**Comment by FernetMenta** [comment]
> I've replaced hevc.c in 2.6-test release with hevc.c from your branch.

not sure what your are trying to say. 2.6-test is a tag of my branch. what exactly did you replace? why don't you just build 2.6-test?

**Comment by afedchin** [comment]
> why don't you just build 2.6-test?
because 2.6-test tag and head of 2.6-xbmc are different. at first I didn't notice the difference. I've made a clean build with 2.6-test. It was not working. Then I noticed the difference and to avoid this difference i've replaced hevc.c from 2.6-xmbc in my local env which is based on 2.6-test already. 

I'll test it again to be sure what I not lost something.

**Comment by FernetMenta** [comment]
> because 2.6-test tag and head of 2.6-xbmc are different

I corrected it. what sample do you test with?

**Comment by afedchin** [comment]
I've used _Elephants Dream-1080p @24fps-1.7Mbps_ from here http://www.libde265.org/hevc-bitstreams/elephants-dream-1080-cfg02.mkv

**Comment by FernetMenta** [comment]
this sample works here.

**Comment by afedchin** [comment]
Great! I will test again this evening.

**Comment by afedchin** [comment]
I can confirm it works. First time I've forgot to merge 6654. With 6654 all works as expected.

**Comment by FernetMenta** [comment]
all required changes got mergered. this can go in now

**Comment by afedchin** [comment]
jenkins build this please

**Comment by MartijnKaijser** [comment]
tried a build with this PR+master however all i got was grey screen. Will trigger new build and provide logs

**Comment by afedchin** [comment]
@MartijnKaijser I've tested this again with my dx11 implementation and it works. Current dx11 branch contains this. If you want you can try with dx11 also.

**Pull request merged**
