### PR TITLE
[c-pluff] Fix implicit declaration compiler warnings

### PR DESCRIPTION
**Pull request by cjmayo**
```
cmdinput_readline.c:41:13: warning: implicit declaration of function ‘strlen’ [-Wimplicit-function-declaration]
cmdinput_readline.c:41:13: warning: incompatible implicit declaration of built-in function ‘strlen’
cmdinput_readline.c:43:43: warning: implicit declaration of function ‘strncmp’ [-Wimplicit-function-declaration]
cmdinput_readline.c:49:18: warning: implicit declaration of function ‘strdup’ [-Wimplicit-function-declaration]
cmdinput_readline.c:49:18: warning: incompatible implicit declaration of built-in function ‘strdup’
cmdinput_readline.c:61:13: warning: incompatible implicit declaration of built-in function ‘strlen’
cmdinput_readline.c:69:18: warning: incompatible implicit declaration of built-in function ‘strdup’
cmdinput_readline.c:81:13: warning: incompatible implicit declaration of built-in function ‘strlen’
cmdinput_readline.c:89:18: warning: incompatible implicit declaration of built-in function ‘strdup’
cmdinput_readline.c:101:13: warning: incompatible implicit declaration of built-in function ‘strlen’
cmdinput_readline.c:116:19: warning: incompatible implicit declaration of built-in function ‘strdup’
```

## Description
Missing include.

Specific to Krypton because c-pluff changing in master: https://github.com/xbmc/xbmc/pull/10741

## How Has This Been Tested?
Compiled on Linux with GCC 5.4.0

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Razzeee** [comment]
Thank you very much!
@MartijnKaijser is this still something we want? Not sure if we're preparing another Krypton release right now.

**Comment by Rechi** [comment]
@cjmayo If this is also valid for current master please create a PR for it.
It doesn't look like #10741 will be merged soon.

**Comment by hudokkow** [comment]
#10741 won't be merged unless Alwin's addon rework doesn't make it into master (and I don't see why it wouldn't). I don't want to make his work harder.

**Comment by cjmayo** [comment]
It is relevant to master. Created #12071.

**Pull request merged**
