### PR TITLE
Settings panel needs more space

### PR DESCRIPTION
**Pull request by emveepee**
## Description
Increase the space in the Settings Panel for 9 buttons

This PR increases the space from 720 (8 x 90) to 810 (9 x 90) to all for a ninth button

## Motivation and Context

Viewing  PVR Settings in Matrix the space for a ninth button exists but it appears like there are no more options.   In Matrix the number of buttons increased to 9 when Reminders were added.

## How Has This Been Tested?

Tested on  Windows.

## Screenshots (if appropriate):

Before

image

After change

image

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ x] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by ronie — COMMENTED** [review]
i'm afraid that won't work on 16:9 screens.

pvr

**Comment by emveepee** [comment]
Ah I see thanks.  Would it be possible If moved the  Setting mode down.  The Main menu appears to allow almost 11 buttons on 16 x 9  

image

**Comment by jjd-uk** [comment]
This https://gist.github.com/jjd-uk/5d90c4db1c2c48fe6098e01d7650729a gives

image

Move `<control type="grouplist" id="3">` that provides the menu up to start 130 this was chosen as TopBar is 130 in height so this keeps menu out of the TopBar fade image. Height of menu increased as done here to 810.

Settings content and scollbar aligned to this.

BottomBar fade image is 115 in height however setting the  `<control type="radiobutton" id="20">` to `<bottom>50</bottom>` keeps the `SettingsLevelChange` sufficiently out of the heaviest amount of overlay from the image.

**Comment by ronie** [comment]
hmmm... while that would 'fix' it for now, what if someone adds another pvr category?
we can't keep on stretching the limits :-)

also, was it really needed to add this new category for just 2 settings?

**Comment by jjd-uk** [comment]
In my view the recording category & reminders category could probably be merged as they are both scheduled actions.

**Comment by emveepee** [comment]
> 
> 
> hmmm... while that would 'fix' it for now, what if someone adds another pvr category?
> we can't keep on stretching the limits :-)

I don't disagree because I did test an additional item and I saw the same gap.  The issue is the gap is there now and as someone who uses Kodi a lot in windows mode it is not easy to keep a 16x9 screen when not full screen.  Perhaps the real solution for 16x9 users is having an option to keep the ratio.   Not all Kodi users use 16x9 though so it doesn't address every problem.
 
> also, was it really needed to add this new category for just 2 settings?

The issue would be the reset to defaults, they aren't really related.

**Comment by ronie** [comment]
hope you don't mind if i take your code and run with it ;-)

closing - superseded by https://github.com/xbmc/xbmc/pull/18353

**Comment by emveepee** [comment]
> 
> 
> hope you don't mind if i take your code and run with it ;-)
> 
> closing - superseded by #18353

Of course not, I am glad you continued with the unified look.  Your change even handles future expansion beyond 9 items which my example could't show

image

**Pull request closed without merging**
