### PR TITLE
changed: Allow all internet filesystems for flags extraction except http/ftp

### PR DESCRIPTION
**Pull request by arnova**
Like the title says. It makes sftp in line with Curl-based filesystems (eg. webdav). This mainly enables file caching and thumb extraction for sftp.

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@arnova is still needed?

**Comment by arnova** [comment]
@MartijnKaijser : Yes, still needed. I've rebased it, but I don't think I can make it any "prettier" than it already is.

**Comment by mkortstiege** [comment]
@arnova what do you think about moving this to a gui settings (expert) where you can select the protocols in a multi select dialog?

**Comment by arnova** [comment]
@mkortstiege : I'd rather have this as as.xml then. But we should still have sane defaults either way. Perhaps we should just blacklist some protocols (like http and ftp) and allow the rest. I don't really see the point anymore of not allowing it for e.g. smb hosts on the internet (this maybe a remnant from the days where we didn't have (low priority) jobs to handle this.

**Comment by mkortstiege** [comment]
I have no strong opinion here since i am not using stuff remotely. Just thought that it might get "prettier" ;) IMO we should try to make it easier to maintain so i´d vote for removing the limitations where possible.

**Comment by fritsch** [comment]
From what I currently see in the forums - we have bigger issues in our VFS implementation for certain protocols. Caching might "workaround" those, but fixing the root issues is to be prefered. 

sshfs is something special of course, especially on low performance platforms where CPU usage is limited for decryption and transferring data (e.g. on the PI), but let's not hide penalties under some mb cache.

**Comment by arnova** [comment]
@frtisch: But do you agree that for thumb/flag extraction we should only exclude ftp/http, removing the rather complicated condition that currently is used?

**Comment by arnova** [comment]
@mkortstiege / @fritsch : You fine with how it is now?

jenkins build this please

**Comment by fritsch** [comment]
Yes - I am fine with it, it will help the usual suspects.

Btw. if you find time, we currently have massive VFS issues without buffering, can you have a look here:  http://forum.kodi.tv/showthread.php?tid=222061&pid=1969819#pid1969819

**Comment by arnova** [comment]
jenkins build this please

**Comment by arnova** [comment]
If not objections, will merge this afternoon

**Pull request merged**
