### PR TITLE
[project readme.md] update quick links

### PR DESCRIPTION
**Pull request by un1versal**
See title

@MartijnKaijser

### CODE REVIEW

**Comment by xhaggi** [comment]
i've moved the code conventions from the forum thread http://forum.kodi.tv/showthread.php?tid=5238 to our wiki http://kodi.wiki/view/Code_guide-lines_and_formatting_conventions .. it would be great if we update this too.

**Comment by uNiversaI** [comment]
@xhaggi done, good work on that wiki page btw and thx for letting me know.

**Comment by MartijnKaijser** [comment]
Thx

**Comment by hudokkow** [comment]
@uNiversaI, can you change the link from
http://kodi.wiki/view/Code_guide-lines_and_formatting_conventions
to
http://kodi.wiki/view/Official:Code_guidelines_and_formatting_conventions

and PR again? Wiki page was moved. Sorry about that.

**Comment by kib** [comment]
"kid"

**Comment by uNiversaI** [comment]
thats what redirects in wiki are also for but glad someone was on it.

**Pull request merged**
