### PR TITLE
Increase repo update frequency to 4 hours

### LINKED ISSUE #764: Kodi only checks for add-on updates every 24 hours
### Describe the feature ###
In a VOD-centric world, Kodi add-ons are living by the grace of the VOD content provider and the stability of the VOD infrastructure. Unfortunately, since Kodi add-ons are not first-class citizens, they are not prepared or made aware of coming changes to the VOD infrastructure.

This means that "suddenly" the Kodi add-on stops working when the VOD infrastructure undergoes changes that the Kodi add-on was not prepared for. **This immediately impacts users.** And no matter how fast add-on developers react, or how well they are improving their processes, this will always be reactive.

Many add-ons pro-actively test their add-ons at full length and are made aware of such issues as soon as they arise, and a fix is out as fast as possible. We still need to wait until the add-on is being accepted and merged in the Kodi repository, And additionally it takes up to 24 hours to get these add-ons installed on end-user systems.

24 hours mean that daily users are always affected, which is a real problem for Kodi as a reliable platform.

- Mean time to detection (MTTD) is now close to 0
- Mean time to acknowledge (MTTA) depends on add-on development team, could be within hours
- Mean time to recovery (MTTR) is a problem
  - Fixing depends on add-on development team
  - Getting it merged into Kodi repository depends on Team Kodi
  - Getting it on user systems depends on this 24h check in Kodi

We would like to see this 24 hour check in Kodi to be reduced to 4 or 6 hours so that fixes can be delivered before they impact end-users.

In most cases being able to get the fix on end-users systems by 18:00 would avoid impacting the majority of users.

### PR DESCRIPTION
**Pull request by dagwieers**
## Description
In order to get critical fixes out to users (ideally before primetime) we need to ensure that Kodi more frequently checks for updates. Once every 24 hours impacts almost every daily user.

## Motivation and Context
In a VOD-centric world, Kodi add-ons are living by the grace of the VOD content provider and the stability of the VOD infrastructure. Unfortunately, since Kodi add-ons are not first-class citizens, they are not prepared or made aware of coming changes to the VOD infrastructure.

This means that "suddenly" the Kodi add-on stops working when the VOD infrastructure undergoes changes that the Kodi add-on was not prepared for. **This immediately impacts users.** And no matter how fast add-on developers react, or how well they are improving their processes, this
will always be reactive.

Many add-ons pro-actively test their add-ons at full length and are made aware of such issues as soon as they arise, and a fix is out as fast as possible. We still need to wait until the add-on is being accepted and merged in the Kodi repository, And additionally it takes up to 24 hours to get these add-ons installed on end-user systems.

24 hours mean that all daily users are always affected, which is a real problem for Kodi as a reliable platform.

- Mean time to detection (MTTD) is now close to 0
- Mean time to acknowledge (MTTA) depends on add-on development team, could be within hours
- Mean time to recovery (MTTR) is a problem
  - Fixing depends on add-on development team
  - Getting it merged into Kodi repository depends on Team Kodi
  - Getting it on user systems depends on this 24h check in Kodi

We would like to see this 24 hour check in Kodi to be reduced to 4 or 6 hours so that fixes can be delivered before they impact end-users.

In most cases being able to get the fix on end-users systems before primetime would avoid impacting the majority of users.

This fixes add-ons/plugin.video.vrt.nu#764

This relates to various emergency fixes, impacting user experience, including:
- add-ons/plugin.video.vrt.nu#761
- add-ons/plugin.video.vrt.nu#750
- add-ons/plugin.video.vrt.nu#677
- emilsvennesson/script.module.inputstreamhelper#351
- emilsvennesson/script.module.inputstreamhelper#59
- add-ons/plugin.video.vtm.go#173
- add-ons/plugin.video.vtm.go#166

## How Has This Been Tested?
Not.

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by dagwieers** [comment]
### For international add-ons
*(Think: Netflix, HBO GO or Disney+)*
With a 24h repository update frequency, it takes 24 hours to get a fix to all end-users. Since primetime moves from timezone to timezone, getting a fix out more quickly is paramount. If we miss European primetime due to unavailability of Add-on developers, we could still save US primetime, but not if the frequency is 24 hours.

### For regional add-ons
*(Think: European broadcasting)*
If we would like to get a fix deployed to all our users before primetime (18:00?), you have to get a newly released add-on pushed *and* merged in the Kodi repository by 12:00 if the update frequency is 6h. Which is highly unlikely IMO.

*In the incidents we have experienced, new VOD infra releases happened in the morning (we have seen them at 06:00 as well as at 09:00), that gives about 3 to 5 hours to get a fix **and** push it out to users. We have been in this situation and we have been able to fix, but not able to push to users because of the 24h frequency.*

So a repository update frequency of 4h makes more sense overall IMO.

**Comment by lrusak** [comment]
So who takes the extra hit on the backend?

**Comment by dagwieers** [comment]
@lrusak Ideally the update check is a single HEAD request and a timestamp comparison.

**Comment by chewitt** [comment]
Most third-party mirrors have a sync frequency around 12-hours, with only a small number doing every-hour or every six-hours. So there needs to be a delay between staging a file and mirrors starting to sync it, and marking the file as available. If you mark it available too early our sizeable userbase can add substantial traffic to the smaller mirrror pool that has the file. If we leave them for longer (as we currently do) nearly all mirrors have the file and load is well distributed. We have no control or influence on the sync frequency of third-party mirrors and cannot have a different sync policy for some content (specific add-ons) over other files - one size must fit all. All mirrors offer services out of goodwill so we are obliged to be a good citizen and good neighbour to all the other projects being hosted for free on the same servers. If we abuse that position the number of mirrors that host us will reduce. Significantly altering the current status-quo would need Kodi to operate CDN infrastructure, either self-hosted (which we're not staffed for) or using a service (which we're not funded for). We could probably reduce the 24h interval, but not by a lot, and if the gain is not large and the reduction only found through trial and error it's probably better to stick with the current arrangement. If we were a commercial entity this would be something critical and we totally get the user-experience impact, but we're not a commercial entity and never will be. NB: I won't pitch this as an official team answer, but I've been looking at mirrors recently for another project with a near-identical use-case so I'm aware of the issues.

**Comment by dagwieers** [comment]
@chewitt LibreELEC is doing a check every 6 hours. I understand the frequency of updates is a lot lower with LibreELEC, but the size is a lot larger.

So why is LibreELEC a good citizen with a 6 hour frequency, whereas Kodi would not?

**Comment by dagwieers** [comment]
Ok, so after some digging it seems we are not actually doing a HEAD request, but we download the full addon.xml.gz file every 24 hours. That seems not very mirror-friendly indeed, and we could become a better citizen by:

- Using a HEAD request to evaluate if a download is required
- Using xz over gzip for addons.xml
  - The 928 kiB Leia addons.xml.gz becomes a 532 kiB addons.xml.xz
  - Uncompressing the gzipped file takes 180ms vs 240ms for xzipped (on RPi)

Maybe Matrix would be a good starting point for this?

**Comment by matthuisman** [comment]
I was thinking of doing this in my add-ons that may also work for you

1) Catch unexpected errors 
2) Show user a Yes / No dialog to check for updates
3) Check addon.xml to see if there is a newer version of add-on
4) Advise user there is a newer version, Yes / No to update
5) xbmc.executebuiltin('UpdateAddonRepos')   #update repos list
6) xbmc.executebuiltin('InstallAddon(my.addon.id))' #in case autoupdates is off
7) reload plugin

You could also have a button in settings.xml to call above method to allow manually checking as well.

Then in your reademe "If you have issues, go into add-on settings and click - Check for updates"

A bit easier than telling them the repo context menu method (and context menu can be hard to get too on some remotes)

Make sure UpdateAddonRepos is never called without user interaction to stop a repeating error causing a bunch of hits on kodis repos.

**Comment by dagwieers** [comment]
@matthuisman While it could offer some salvation to users, I don't think we shoudle handle this at the add-on level or expose this to users.

From a user experience POV your TV simply should keep on working. And if we have a fix available before our users even experienced an issue, it is super sad that most of them still have to go through 24 hours of unavailability before the situation recovers.

What's worse, this is a global setting for *all* repositories, so we cannot even offer an alternative repository we host ourselves to get a possible fix out.

*Mind you, I am not only concerned about VOD add-ons, we have had issues related to Widevine where people were not able to play any DRM content for up to 24 hours until a fix in the inputstreamhelper add-on was available everywhere.*

*This includes users reporting the same issues multiple times, and people asking for help on forums and fixing things themselves, if they are lucky.*

**Comment by wsnipex** [comment]
Doing this would mean we need a new mirror server.

**Comment by phunkyfish** [comment]
I’m not sure I see how do you do what you want in the absence of funding. If you require reliable systems they need to be paid for somehow. 1) pay the infrastructure cost, 2) pay the cost in people. 

Multiple 9’s never come for free and the cost always high for them. There is no avoiding that no matter what you do.

**Comment by a1rwulf** [comment]
> @chewitt LibreELEC is doing a check every 6 hours. I understand the frequency of updates is a lot lower with LibreELEC, but the size is a lot larger.
> 
> So why is LibreELEC a good citizen with a 6 hour frequency, whereas Kodi would not?

Because of the big difference in user numbers.

**Comment by michaelarnauts** [comment]
Hmm, doesn't a check for updates only download the md5 file with the checksum of the addons.xml, and then only download the actual addons.xml if it has been changed since last time?

That would mean less then a KB for check (32 bytes for the md5, and some HTTP overhead). I don't think that should be a problem?

**Comment by fuzzard** [comment]
Do some numbers, I'll assume 1million Kodi installs (extremely conservative). 
1,000,000 X 1kb =1gb traffic per day, this proposal changes to 6 requests a day, 6gb traffic. 180gb over the month instead of 30gb currently. All that just for md5 hash checks...

**Comment by michaelarnauts** [comment]
@fuzzard spread over multiple mirrors (about 20-30), that's correct. I don't see an issue with 9 GB per mirror per month extra.

What's more alarming... If the findings of @dagwieers are correct, it seems that the addon.xml file is always downloaded? Isn't that a bug then that should be fixed? This would mean 928KB per 24h per user.

1,000,000 * 928 KB = 885GB per day... If this is working fine at this moment, I guess we can safely check every 5 minutes.

**Comment by fuzzard** [comment]
There's a front end to those mirrors. I'm not across all the specifics/stats the infrastructure Kodi currently uses, but if wsnipex raises concerns, I'd believe him. A simple change for you isn't necessarily a simple change to infrastructure costs.

No idea on his thought, from what I'm told it checks hash, so not sure what he's looked at to come to that conclusion. Again not my area.

**Comment by michaelarnauts** [comment]
@fuzzard I agree with you about the costs, and the expertise. Also, it's not my expertise, and I don't know about the current mirror-setup. But I think a valid discussion is going on, and we should not stay with 24h, just because it has been decided many years ago.

Some stats. According to the mirrors, there are about 6 580 804 daily checks on Leia, 1 287 871 on Krypton and 468 210 on Jarvis. That's a nice userbase we have! (Source: http://mirrors.kodi.tv/stats?downloadstats=2020-05-26 (stats from two days ago, just so we have all the data from all timezones)

Does the current code still uses the md5-checks, or does it just download the addons.xml? There is a lot of TB to be saved there.

**Comment by phunkyfish** [comment]
I think your assumption of a saving could be false. Something will always change I imagine, hence why the full file should be downloaded.

**Comment by michaelarnauts** [comment]
> I think your assumption of a saving could be false. Something will always change I imagine, hence why the full file is downloaded (I stand to be corrected on this).

I guess you are right right.

The checksum file only changes when something is merged into the repo. Giving a quick look at the merged PR's in `repo-plugins` (and then you also have scripts, and maybe others), this is about daily. So currently, with the 24h check, most of the time, something is changed, and a new full file is fetched.

Doing a more frequent check (like 6 hours for example) will increase the hitting of the md5 file, so it will not quadruple the traffic compared to a 24h check.

This is only true for the actual check itself. The update will be downloaded eventually, so it doesn't matter if it happens sooner.

Maybe somebody with actual traffic stats could shine a light on this? I still think it won't dramatically increase traffic relative with what we have now, but it's best to do some math first.

**Comment by wsnipex** [comment]
The downloaded data doesn't make a difference for _our_ mirror director, mirrorbits only ever sends a redirect to some mirror server. Mirrorbits always has to do the same amount of work, no matter if it's HEAD or GET, no matter if you request the actual file or only it's hashsum.

Almost quadrupling the number of request to mirrorbits is simply not feasible with our current hardware, which is pretty old.
Are you offering a 8 core hosted server?

**Comment by dagwieers** [comment]
> I’m not sure I see how do you do what you want in the absence of funding. If you require reliable systems they need to be paid for somehow. 1) pay the infrastructure cost, 2) pay the cost in people.

Reliability is not exclusively a hardware problem, maybe it is in this case, but that is unclear at the moment. If the problem is at the mirrors, there are a handful of things we can improve already (and maybe we should anyway), if the problem is at mirrorbits, we need to identify the actual problem.

> Almost quadrupling the number of request to mirrorbits is simply not feasible with our current hardware, which is pretty old. Are you offering a 8 core hosted server?

If the number of HEAD requests is too high, maybe a decentralized solution is possible (e.g. DNS TXT?) to establish an update is required.

In any case from this discussion the status quo seems to be a liability as well, we better not expect Kodi to become too popular :upside_down_face:

**Comment by dagwieers** [comment]
BTW from a proxy I can see 2 requests hitting mirrorbits for each daily check:
```
1590352275.841    106 192.168.1.123 TCP_MISS/200 358 GET http://mirrors.kodi.tv/addons/leia/addons.xml.gz? - HIER_DIRECT/89.16.176.16 text/plain
1590352276.008     72 192.168.1.123 TCP_MISS/302 626 GET http://mirrors.kodi.tv/addons/leia/addons.xml.gz - HIER_DIRECT/89.16.176.16 text/html
```
Maybe that is something easy to fix that would reduce the load by a factor 2?

**Comment by michaelarnauts** [comment]
> The downloaded data doesn't make a difference for _our_ mirror director, mirrorbits only ever 
> Almost quadrupling the number of request to mirrorbits is simply not feasible with our current hardware, which is pretty old.
> Are you offering a 8 core hosted server?

Out of curiosity, what kind of hardware are we talking about and what is the current load of that machine? The mirrorbits repository indicates "Blazing fast, can reach 8K QPS on a single laptop", so maybe there are improvements that could be done to make this perform faster, or by using DNS based load balancing?

**Comment by michaelarnauts** [comment]
Also, just to understand the problem right. What is the concern? Kodi's own mirrorbits machine that might not be efficient enough, or the mirrors behind it?

**Comment by dagwieers** [comment]
If there is a risk of getting too many requests on the mirrorbits server, it could be useful to have support for Retry-After (and potentially HTTP 429) so that:

1. requests are proactively redistributed over a given time interval
2. the frequency can be influenced by the load on mirrorbits
3. it is no longer hardcoded, and repositories can decide how Kodi should behave for them

If mirrorbits cannot do this today, maybe we ought to open a discussion there as well to see what is feasible.

**Comment by da-anda** [comment]
from what I can remember we increased the time from something much lower to 24h because we had severe performance issues on our mirror redirector. At the same time we looked into alternatives and ended up with mirrorbits. In my memory this was not too long ago, maybe Krypton, but I could remember wrong, and Krypton is also a couple years old, so what do I know.
I just wanted to emphasis that the 24h had been chosen wisely back then. It's not that I would not welcome more frequent bugfix checks. The concept of matthuisman to ask the user if he would like to check for an update when an add-on crashes/fails sounds nice and could probably also be added to the core. If we are smart about it, we could only check for an update on the related repo of the add-on, which in case of Netflix, Disney+ and Prime would not affect our infrastructure. This would require though that we track/remember the repo an add-on comes from (which would be a good idea in general as we discussed some time ago in regards to version number cross-updates and has again been pointed out in the PR by matthuisman).

**Comment by matthuisman** [comment]
Funny you say that, point #15 in my ideas below from a while back had a thought about increasing repo checks or doing it on addon crashes

https://github.com/xbmc/xbmc/pull/17677#issue-403118062

**Comment by dagwieers** [comment]
>  The concept of matthuisman to ask the user if he would like to check for an update when an add-on crashes/fails sounds nice and could probably also be added to the core.

The problem here is that not every failure is an exception/crash. In fact, we went to great lengths to make sure that most failures will not result in exceptions, but are handled gracefully. And you cannot tell from an error if it is because of a backend change or a programming mistake. Is an empty listing a back-end problem, or not? Is an authentication problem caused by credentials, or a back-end change? Things are not clear-cut.

We have unit tests and integration tests to test conformity and validate results, sometimes they generate false positives (because we also check on expected content, which may change). This is what tells us when backend changes impacted expected behaviour and only by checking what is happening we know if this will impact users or not.

See https://github.com/add-ons/plugin.video.vrt.nu/actions for an overview of what we already test.

The **Status** checks test most of the common paths *every 30 minutes*.
The **CI** checks test *all* code paths on Python 2.7 and 3.5 to 3.8.
The **Kodi** checks performs an addon-checker testing for every supported Kodi release.

This framework is used by a dozen add-ons already and has proven very useful during development and back-end testing.

**Comment by matthuisman** [comment]
I guess it all depends on how the add-on is layed out.
I do this:

1) I create my own Error class that inherits from Exception
   (then can subclass this Error class for API Errors etc)
2) If something expected happens (eg. login failed), I raise this Error class with a message
    Saves all the "return False if else" bloat. 
3) I then have a try / except block over the entire route that 
    - if the Exception is inherited from Error - show an OK dialog with the error message
    - all other Exceptions show an "Unexpected Error" dialog with trace-back

It's in the Unexpected Error case above that an update could be checked for.

**Comment by matthuisman** [comment]
If you want to make the service, here is a file you can hit as many times as you like
**http://i.mjh.nz/kodi_checksums.json** 
That is updated every 5 minutes (if changes).

You'd have a service add-on like
```
CHECK_EVERY = 60*30 #30 mins
monitor = xbmc.Monitor()
last_checksum = None

while not monitor.abortRequested():
    if monitor.waitForAbort(CHECK_EVERY):
        break

    kodi_ver = xbmc.getInfoLabel("System.BuildVersion").split('.')[0])
    checksum = requests.get('http://i.mjh.nz/kodi_checksums.json').json()[kodi_ver]
    if checksum != last_checksum:
        xbmc.executebuiltin('UpdateAddonRepos')
        last_checksum = checksum
```
This also has the nice benefit of doing an update when kodi starts.
If you didn't want that, you'd need to store the last known checksum somewhere.

**Comment by dagwieers** [comment]
So anyone willing to share information on:
- The amount of requests we get daily
- The peak load and distribution of such requests
- The hardware we currently have running (so we can look at what new hardware would be needed)

@michaelarnauts already determined we have about 9 million Kodi instances getting updates daily (Jarvis, Krypton, Leia). That would mean we daily get about 18 million requests (2x GET requests).

This would mean an average 220 requests every second. mirrorbits reportedly can handle 8K QPS on a single laptop.

*So what peak loads do we get?* → Is redistributing load even necessary?
*Can we eliminate the second GET request?* → This would result in half of the load during peak
*How much margin do we currently have on peak load?* → Can we handle a surge in popularity?

**Comment by matthuisman** [comment]
So your thinking

1) Changing the GET from http://mirrors.kodi.tv/addons/leia/addons.xml.gz?sha256
   to a HEAD request on http://mirrors.kodi.tv/addons/leia/addons.xml.gz
2) Get the checksum from the Content-Sha256 response header
3) If that header is different, then we already have the redirect Location header

Reduces 3x requests to 2x.

The issue is that this would only work for Kodi repo.
Other repos addons.xml.gz won't return a Content-Sha256 header.
So the update repo code would need a case for Kodi repo and another case for other repos.

Unless there was a new flag in the addon.xml that could tell kodi the checksum is found in the header.
eg. <checksum verify="sha256" header="Content-Sha256">http://mirrors.kodi.tv/addons/leia/addons.xml.gz</checksum>

When Kodi sees a "header" attribute, it knows to just do a HEAD request to that url.
Then other repos could introduce it as well.

Kodi would then be updated to be check if <info> and <checksum> are the same URL and if yes and there is a location header in the <checksum> header data - then just GET request that url.

**Comment by yol** [comment]
> This would mean an average 200 QPS (requests every second).

You are totally ignoring the actual add-on download and the image requests. The add-on downloads require a SSL handshake, which is CPU-intensive (so one add-on DL "counts", relatively speaking, a lot more than one addon.xml request).

> mirrorbits reportedly can handle 8K QPS on a single laptop.

That mirrorbits can handle 8K QPS on a laptop does not mean your whole system including an nginx frontend and SSL termination can handle it (it cannot).

> Get the checksum from the Content-Sha256 response header
> If that header is different, then we already have the redirect Location header

HEAD gives you neither Content-Sha256 nor Location. No idea if that could be changed, but it is the status quo.

**Comment by matthuisman** [comment]
oh, you could always do a GET request on http://mirrors.kodi.tv/addons/leia/addons.xml.gz with follow redirects off.

**Comment by yol** [comment]
That should give you the info, yes. Still, that change will not allow to quadruple requests.

**Comment by yol** [comment]
> You'd have your VPS endpoint behind CF cache and return the the md5 file with a 24 hours expires header. You then use the CF API to clear the cache when it changes.

Maybe it could work if you fly under the radar, but CF does not usually allow this.

https://www.cloudflare.com/terms/

> 
> 2.8 Limitation on Serving Non-HTML Content
> 
> The Service is offered primarily as a platform to cache and serve web pages and websites. Unless explicitly included as a part of a Paid Service purchased by you, you agree to use the Service solely for the purpose of serving web pages as viewed through a web browser or other functionally equivalent applications and rendering Hypertext Markup Language (HTML) or other functional equivalents. Use of the Service for serving video (unless purchased separately as a Paid Service) or a disproportionate percentage of pictures, audio files, or other non-HTML content, is prohibited."

**Comment by dagwieers** [comment]
@matthuisman
> Changing the GET from http://mirrors.kodi.tv/addons/leia/addons.xml.gz?sha256 to a HEAD request on http://mirrors.kodi.tv/addons/leia/addons.xml.gz

That wouldn't work. A single GET to the addons.xml.gz on mirrorbits gets you both the Content-Sha256 and a Location header (for a redirect). Everything you need to figure things out!

> The issue is that this would only work for Kodi repo.

If you get the file back, perfect, you requested it, you should get it (unless you get a redirect and the checksum). Not so different from how it works now (which is a different logic for when there is a checksum, and when not)

@yol
> > This would mean an average 200 QPS (requests every second).
> 
> You are totally ignoring the actual add-on download and the image requests. The add-on downloads require a SSL handshake, which is CPU-intensive (so one add-on DL "counts", relatively speaking, a lot more than one addon.xml request).

I am not *totally ignoring*, I am only considering mirrorbits because that was stated to be the actual problem. The add-on downloads don't go through mirrorbits and the links to mirrorbits are HTTP only not HTTPS, so I doubt there is an SSL handshake happening to mirrorbits.

But mind you, we have not received concrete and specific information of the size of the problem. Everything seems to be vague, and impossible, and considers us to be idiots. Despite being idiots we proposed simple technical solutions that would help, both for the load on mirrors as well as the load (and peak load) on mirrorbits.

> > mirrorbits reportedly can handle 8K QPS on a single laptop.
> 
> That mirrorbits can handle 8K QPS on a laptop does not mean your whole system including an nginx frontend and SSL termination can handle it (it cannot).

mirrorbits doesn't do SSL termination for this AFAICT.

So please be specific. How much QPS do we handle now? What are the peaks? What is the margin we still have? What hardware are we running now?

> Still, that change will not allow to quadruple requests.

We already brought it down from 24h to 12h theoretically. And assuming peak loads are the problem, distributing requests would flatten the curve and could theoretically help in allowing more than quadrupling requests.

Thanks for being constructive.

**Comment by matthuisman** [comment]
@dagwieers 
Location and Content-Sha256 are both headers.
A HEAD request should give you both without risking downloading the entire file.
eg. If Kodi stopped using mirrors in the future - or other repos without redirects

However, yol pointed out that mirrorbits doesn't return those headers on a HEAD request for an unknown reason.  So, a GET request would need to be used.

Fine, but this information needs to be told to Kodi via the addon.xml for the repo.
To allow other repos to use it and stop specific core code just for Kodi repo.

You'd need something like
1) Tell kodi to do a GET request (as usually when looking for a header, you'd do HEAD)
2) Tell kodi the header name that contains the checksum

`<checksum verify="sha256" type="GET" header="Content-Sha256">http://mirrors.kodi.tv/addons/leia/addons.xml.gz</checksum>`

Then Kodi will need to store the headers from the checksum request and use those if the data request url is the same.

It gets quite messy.

**Comment by dagwieers** [comment]
> Location and Content-Sha256 are both headers.
> A HEAD request should give you both without risking downloading the entire file.
eg. If Kodi stopped using mirrors in the future - or other repos without redirects

@matthuisman I do not see the problem, there is hardly a difference to how it works now.

**Current behaviour**
- GET .../addons.xml.gz?sha256
  - mirrorbits: you get a SHA256 in the body
  - other: you get the file

In case of mirrorbits, you check the SHA256 with the previous SHA256, if different:
- GET .../addons.xml.gz
  - You get a 302 with the Location header
- GET .../addons.xml.gz from the new *Location*

**New behaviour**
- Get .../addons.xml.gz
  - mirrorbits: you get the Content-Sha256 and Location from the headers
  - other: you get the file

In case of mirrorbits, you check the SHA256 with the previous SHA256, if different:
- GET .../addons.xml.gz from the new Location

**Summary**
Only one request needed, no real difference in handling as it currently is. And it is *not* Kodi specific, but mirrorbits specifics, just like before.

**Comment by matthuisman** [comment]
@dagwieers 
Your new behaviour means the large addon.xml file is downloaded every check for every other repo.
Lots of repos don't have updates every 24 hours. 
And you want to decrease that frequency as well.
So you may end up getting the addon.xml 

Also, if Kodi changes to a different mirror system or remove it - they need to update core and push updates to everyone.

With your new behaviour, the `<checksum>` in addon.xml is not even used.

**Comment by dagwieers** [comment]
@matthuisman Ok, from the repository's `addon.xml` that is currently a problem. As it does have 2 references, one for checksum and one for addons.xml.gz. We would indeed need a solution for that. Or a new convention. But from an implementation perspective, it is rather trivial.

**Comment by matthuisman** [comment]
Please, read my comments.
(Im repeating below again)

The reason for the HEAD request was because if another repo wanted to use a header for the checksum and don't use a redirect. You can't GET the url as that would return the entire file.

Repo B has addons.xml.gz
They expose a HEADER on that file giving the checksum
They don't use a redirect

However, as HEAD request doesn't work with mirrorbits, we then need a way to tell Kodi what type of request to make
```
<checksum verify="sha256" type="GET" header="Content-Sha256">http://mirrors.kodi.tv/addons/leia/addons.xml.gz</checksum>

<checksum verify="sha256" type="HEAD" header="Content-Sha256">http://example.com/repo/addons.xml..gz</checksum>
```

See how it gets messy.

**Comment by yol** [comment]
@dagwieers 

> There wouldn't be more add-on downloads going to mirrorbits if the frequency is increased, you would get them faster.

> There won't be more SSL terminations if we increase the frequency, as there won't be more add-on downloads.

I did not claim either. I am only saying that this load is still there and cannot be neglected. And that comparing with stats from the mirrorbits README that do not include a lot of the (necessary) setup does not give any meaningful insight.

> considers us to be idiots

Please do not accuse me of things that I have neither said nor implied nor meant. I can understand if you feel frustrated that this PR does not go through as easy as you had hoped for, but being constructive goes for both sides.

> But mind you, we have not received concrete and specific information of the size of the problem.

I think that is mainly because it is an infrastructure issue that goes well beyond the scope of this PR. While it is by no means bad to get suggestions and input, in the end there are a lot of things to consider that will be handled by the team internally, not the least of which is how much money we are willing to spend for what exactly (it makes no sense to discuss this here; I hope you will agree). For context, hosting for mirrorbits is 100% sponsored at the moment. And of course, someone must be willing to do all the legwork necessary. We're all volunteers.

And the way it looks to me at the moment - given the proposals raised so far - is that it can only be finally solved with infra rework. I won't be the one to do the work (and I assume you won't be either), so I'm reluctant to say anything too specific. I'm just trying to offer insight into why the situation is what it is and what must be taken into account. I hope you understand - in hindsight it might have been better to say nothing at all. Maybe @wsnipex or @Rechi want to share some information about the current setup?

As the mirror server is aging, we might replace it sometime soon anyway. But nothing has been decided on that yet. It could be a good idea to put at least the infra side of this on hold until there was some progress on that front.

Finally, given the points raised by @chewitt and the fact that add-on fixes must be reviewed either way before they can be merged and finally reach users, I reckon that the benefit may not be perceived to be large enough to justify larger infra changes and the effort that comes with that. Note that I'm not saying that it is a bad idea inherently. It could certainly improve UX. And reducing the number of requests to the mirror server is good in either case, irrespective of whether we end up shortening the update interval or not.

@matthuisman 
> Only way would be a "special case" just for Kodi repo.

If implemented properly, this is not out of the question IMO. We are already special-casing the Kodi mirror setup anyway for add-on downloads. It shouldn't be too specific though, so that we would still be able to replace the mirror setup with something else if necessary without breaking updates in all existing Kodi installations.

**Comment by dagwieers** [comment]
@matthuisman You cannot reduce it to a single request unless you modify the repository metadata. It would mean we support the current behaviour _and_ the new behaviour, or we make the change in Matrix and make the new convention the new default starting with Matrix.

But it makes no sense to discuss implementation specifics if:
1. Kodi Team doesn't want this (I haven't seen a single reply supporting increasing the frequency)
2. We don't get specific information to determine that this is the actual problem (according to our calculations, this is not the problem)

It is only diffusing the discussion ATM.

If the metadata-requests are really the problem, offloading the metadata requests to a cluster of RPi4's could be the easiest solution, because mirrorbits *and* a cluster of RPI's should be able to handle 20K QPS with ease. And the existing system would be used for SSL termination and add-ons/images downloads.

**Comment by dagwieers** [comment]
>> considers us to be idiots

> Please do not accuse me of things that I have neither said nor implied nor meant. I can understand if you feel frustrated that this PR does not go through as easy as you had hoped for, but being constructive goes for both sides.

I did not expect this PR to go through easy, far from that. In fact I never expected this PR to be merged to begin with. The PR opening gives the context to why this is important, even more important today in a VOD-centric world.

The frustrations are entirely because of the negative vibes in every response, and the lack of actual numbers, without those we don't even know where exactly to look for a solution. A solution starts with acknowledging the problem and this problem has not been acknowledged. *Yes, we believe getting emergency updates to our users would help in a better experience, but...*

Mind you that the 24h frequency is hard-coded, which makes a more fine-grained solution impossible, and leaves all repositories in the same position as Kodi's repositories, where they might not even have this performance issue to begin with.

**Comment by matthuisman** [comment]
`Despite being idiots we proposed simple technical solutions that would help, both for the load on mirrors as well as the load (and peak load) on mirrorbits.`

Nothing is stopping you from creating PRs for your simple solutions.
Be great to see some code so we can understand.

**Comment by dagwieers** [comment]
> Nothing is stopping you from creating PRs for your simple solutions.
> Be great to see some code so we can understand.

@matthuisman If there is no interest in increasing the frequency anyhow, there is no point in spending the effort. If we don't know where the problem lies, or hardware is believed to be the only solution, there is no point in spending the effort. There is nothing that suggest to me that the frequency will be increased even if new hardware would be able to handle it...

**Comment by matthuisman** [comment]
But if it's so simple - then not much effort?
I'm sure the team would then look more favourably in reducing the frequency.
It's a good start at least.

**Comment by dagwieers** [comment]
@matthuisman Nope, simple in design, not necessarily in implementation.

You may have noticed the thumbs down from just the problem description. As far as I can tell, this is not perceived as a problem, but in fact the 24 frequency is perceived to be a solution.

**Comment by matthuisman** [comment]
`simple in design, not necessarily in implementation`

I think this is where you are going wrong.
You are treating it like a simple problem to fix, but not understanding the work and money to implement it.

**Comment by dagwieers** [comment]
> You are treating it like a simple problem to fix, but not understanding the work and money to implement it.

As I stated:
1. I don't think this is perceived as a problem ATM. (That is step 1)
2. The actual obstacle has not been stated, so we don't know what needs fixing. (That is step 2)

Everything else might as well be a big waste of time.

**Comment by phunkyfish** [comment]
If the frequency cannot ever be better than 12 hours due to the mirrors there may not be a viable solution to your problem at all. The closest would be doubling the frequency.

Also, I think that due to the amount of responses from the team you can assume they understand the problem you would like to solve and why.

Take into account that all the information you need won’t all reside with a single individual and it won’t exist in an infrastructure diagram somewhere so it will take time to piece it together.

**Comment by keithah** [comment]
Keep in mind, we're a volunteer organization running on donated hardware. This isn't a corporation with middle managers who's job it is to make pretty graphs and analyze data. Our goal is to have less infrastructure, not more, because we lack the resourcing to manage the infrastructure we have sometimes (shoutout to @wsnipex, @Rechi, @lrusak and everyone else whos chipped in, you guys are the real MVPs here) and actual physical equipment for this.

Infrastructure is one of our hottest topics in the team, and something we're all very highly aware we are trying to keep as minimal as possible, so you read into what a thumbs down etc meant quite abit to your statement.

Find us people willing to donate us super fast machines that we can abuse lots and lots of bandwidth on (as wsnipex said, 8core+) and that solves at least half the equation. We need to update *all the miror* infrastructure, its amazing its lasted as long as it has. Unlike VLC, we have zero ads on our download page, and never will, nor do we have a company behind us that does contracting work. It's impressive what they've achieved, and while we can aspire to be more like them, unfortunately, the reality is too far from the truth.

We're not totally against the repo update. We're against doing *anything* that will put more load on any of our mirror infrastructure. It's went down several times (a few were even an accident!) and it causes so many problems.

We have quite abit of users, moreso than whats listed above, and theres no 'easy fixes' when it comes to supporting them. This is why AWS/Azure/GCP makes so much money. :)

**Comment by dagwieers** [comment]
If we are convinced it is not possible, it is not possible.

**Pull request closed without merging**
