### PR TITLE
Do not override episodeguide and the default uniqueid type set by a scraper

### LINKED ISSUE #16979: episodeguide URL from tvshow.nfo overrides the one set by a Python scraper
## Bug report

When a TV show directory contains tvshow.nfo file with XML info and this file has `episodeguide` section as below:
```xml
<episodeguide>
  <url>http://www.thetvdb.com/api/1D62F2F90030C444/series/328634/all/en.zip</url>
</episodeguide>
```
this URL is passed to `getepisodelist` and `getepisodedetails` plugin calls to a Python scraper regardless of list item properties and plugin directory item URLs that were set by a Python scraper on previous scraping stages, e.g. getdetails.

## Expected Behavior

Kodi should respect list item and and plugin directory item properties set by a Python scraper and pass them to the subsequent plugin calls to a Python scraper.

## Actual Behavior

episodeguide URL from a NFO file is passed to `getepisodelist` and `getepisodedetails` scraper plugin actions which makes no sense, especially if this URL points to, for example, TheTVDB episode guide but the Python scraper actually works with another site (TheMovieDB, TVmaze, etc.)

## Possible Fix
?

### To Reproduce

Add tvshow.nfo file with XML content including `episodeguide` section to a TV shof directory as described above. The try to scrape this TV show with a Python scraper, e.g. TVmaze.

### Debuglog
https://paste.kodi.tv/cuburiyalu.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.04
 - Kodi version: Leia, Matrix

### PR DESCRIPTION
**Pull request by romanvm**
This fixes #16979

## Description
This PR fixes the issue when episodeguide and the default uniqueid set by a Python scraper are replaced with the ones from NFO files.

## Motivation and context
Currently Python TV screpers do not work if TV show directories contain NFO files generated from a different scrapers because `getepisodelist` and `getartwork` calls receive episodeguide and uniqueid data from NFO and not from a screaper. For example, if NFO files contain episodeguide and the default uniqueid from TMDB and you are running TVmaze Python scraper, scraping fails because TVmaze scrapsr receives IDs from TMDB and cannot find anything on TVmaze of finds wrong data. Forum discussion: https://forum.kodi.tv/showthread.php?tid=349813&pid=3048495#pid3048495

## How has this been tested?
I have build the fix and tried to scrape some TV shows with TMDB NFOs by a TVmaze scraper. The TV shows were scraperd successfully.

## What is the effect on users?
Essentially, this fix eliminates a major limitation of Python scrapers and allows to switch scrapers without the need of removing/editing NFO files (provided a Python scraper itself can extract necessary data from NFOs).

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by fuzzard — APPROVED** [review]
If you can apply the Jenkins diff, good to go imo.

Maybe test in master for a bit, but worth a backport I think

**Comment by romanvm** [comment]
Done, all is green.

**Comment by DaveTBlake** [comment]
> Maybe test in master for a bit, but worth a backport I think

Merging, but not merge backport until this has been evaluated in master

**Comment by reardonia** [comment]
This causes a significant error linking 'movie' and 'episode' table to 'uniqueid' table.  Please see #21103

**Pull request merged**
