### PR TITLE
BitstreamConverter: Add header size exception for UNSPEC62 NALUs

### LINKED ISSUE #18890: Dolby Vision files do not trigger Dolby Vision display mode on FireTV Stick 4K
## Bug report
On Kodi Matrix 19.0 Beta1, mp4 Dolby Vision files are supposed to playtback in Dolby Vision mode.

### Describe the bug
Here is a clear and concise description of what the problem is:

Dolby Vision mode is not triggered on the display when playing an mp4 Dolby Vision file.
It is a bug because the device supports Dolby Vision through multiple apps, as well as with Kodi using the Netflix addon.
Also, the debug log mentions that the DVHE decoder is being used, so something else is going wrong.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

With an mp4 Dolby Vision file on the device itself, starting playback of the file should trigger the display's Dolby Vision mode and the output video should look normal.

## Actual Behavior

When starting playback of an mp4 Dolby Vision file, the video is output in SDR mode and looks wrong.
There is no Dolby Vision mode activated.

## Possible Fix

Not sure, maybe the dvhe decoder is crashing.
With a profile 7 or 8 file, the HDR10 fallback works well.

### To Reproduce

1. Have a Dolby Vision sample (from https://kodi.wiki/view/Samples#4K_.28UltraHD.29, MP4 Dolby Vision samples) on the FireTV Stick 4K.
2. Open Kodi, go to the File Manager.
3. Browse the source where the mp4 file is located
4. Press to start playback
5. The display does not change to Dolby Vision mode.

### Debuglog

The debuglog can be found here:
A debug log with FFmpeg logging enabled on a debug build of Kodi master: https://paste.kodi.tv/sezujedeku.kodi
Using Maven's Kodi build: https://paste.kodi.tv/onupojoted.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

No screenshots necessary.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

On an NVIDIA Shield, these files work well, while on the FireTV Stick 4K, they do not.
Other than the hardware decoder, there should not be a difference in support for Dolby Vision profile 5 (the mp4 file tested here)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android, FireTV
 - Kodi version: 19.0 Matrix Beta1, armv7a

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by quietvoid**
## Description
Currently, Dolby Vision only works on Android using an NVIDIA Shield TV (and other Android TV devices).
This change adds an exception to the bitstream converted to force type 62 NALUs to use a header of size 4.

The effects of this makes the FireTV Android devices decode Dolby Vision properly, as the metadata is otherwise ignored.

## Motivation and Context
It allows playback of Dolby Vision files (those hinted as `video/dolby-vision`) with both FireTV Stick 4K (2018), and FireTV Stick 4K Max (2021).
I have not tested the FireTV Cube.

Without the change, profile 4/5 files would play in SDR, and other profiles in HDR10 only.
Fixes #18890, #17451

## How Has This Been Tested?
Tested on both FireTV Stick 4K 2018 and FireTV Stick 4K Max (2021) devices, with an LG OLED C8 TV.
Playback through files shared with DLNA, as well as PlexKodiConnect now playback properly in Dolby Vision.
Before the change, all Dolby Vision files would not trigger Dolby Vision mode on the display.

Since NALU type 62 only exists for HEVC, this should not affect any other codec.

## Types of change
- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [x] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by quietvoid** [comment]
Jenkins didn't like the unused variable, now the force push :(

**Comment by CastagnaIT** [comment]
@CiNcH83 @kszaq i moved the discussion here to not go OT on other PR.

with the case of netflx add-on the video stream Codec Tag hint is already set as `dvhe` when you choose the DV video stream,
but a possible solution should not be based on a chipset type but on the stream "characteristics"

@kszaq perhaps you could try to do a experimental APK build, with enabled by default your "workaround", only to see what happen with the Bravia tv

**Comment by CiNcH83** [comment]
[Here](https://github.com/xbmc/inputstream.adaptive/issues/557) is the problem I am experiencing with BRAVIA when playing DV via InputStream Adaptive (Netflix add-on). Correct decoder (`OMX.dolby.vision.dvhe.stn.decoder.secure`) is chosen.

**Comment by quietvoid** [comment]
IA streams aren't quite relevant to this PR :slightly_smiling_face:

If the deocder is correctly chosen, there's probably something expected from the data that's different.
But as it's encrypted I don't know it'll be traced.

I always thought IA streams would be the same behavior as regular apps (such as the Netflix app).

**Comment by cromefire** [comment]
> Tested on a FireTV Stick 4K 2018 device, with an LG OLED C8 TV.

I assume this resembles the same changes (minus the DV MKV support) made for the Dolby Vision APK posted by @fandangos on the forum. If so I can verify that this also works on different hardware, namely the Chromecast with Google TV (2020; also known as "Project Sabrina") using an Amlogic processor playing on a Panasonic HZW1004. It does crash on a lot of content, although I'm unsure whether this is down to the new MKV DV Metadata support or the Dolby Vision support (and I don't have a correct MP4 to test).

**Comment by quietvoid** [comment]
One difference with this PR is that it doesn't include the changes for files containing both HDR10+ and Dolby Vision metadata.
Though as far as I know that fix is specific to the FireTV Stick 4K.

**Comment by cromefire** [comment]
It did at least work with a file containing both (although I'd really like an option to switch it, as it seems to just go straight for the Dolby Vision, which is worse than HDR10+ for that particular file).

**Comment by quietvoid** [comment]
Is it possible to get some feedback?
So far it was mentioned that the chipset shouldn't be used to know if the workaround is necessary, but I don't see any other way.

**Comment by quietvoid** [comment]
I have changed the workaround to an exception for type 62 NALUs, after seeing that x265 also forces the NALU header size to 4.

**Review by thexai — APPROVED** [review]
It is an improvement for some specific devices only and does not do any harm to the rest since the changes are limited to Android only code.

Now that through another PR (https://github.com/xbmc/xbmc/pull/20422) it is also possible to detect if DV is supported at runtime, it will be possible in the future to introduce changes in all platforms common code to give DV support in more devices...

**Comment by thexai** [comment]
Since there is no active android developer I am going to take the liberty of merge this. I don't think it can cause any regression, anyway the changes are very localized (2 files) and it would be easy to revert in case of problems.

**Comment by quietvoid** [comment]
To summarize the improvements #19099 brought:

FireTV Stick 4K (2018): Supports Dolby Vision in MP4/MPEG-TS containers.
FireTV Stick 4K Max (2021): Supports Dolby Vision in MKV/MP4/MPEG-TS containers.

Thanks everyone involved in reviewing and testing.

**Pull request merged**
