### PR TITLE
Readmes: add libegl1-mesa-dev to dependencies

### PR DESCRIPTION
**Pull request by un1versal**
@wsnipex.... or @fernetmenta

**readme.linux** has `libgl1-mesa-dev | libgl-dev,, libglu1-mesa-dev | libglu-dev`

**readme.ubuntu** only has  `libglew-dev`

libgl-dev (is that lost in hardy) -> remove?
libglew-dev looks like it can stay -> stay?

and remove `libgl1-mesa-dev | libgl-dev,, libglu1-mesa-dev | libglu-dev` or stays as is?

### CODE REVIEW

**Comment by FernetMenta** [comment]
glew-dev can be dropped, glu-dev is required

**Comment by wsnipex** [comment]
thanks

**Comment by FernetMenta** [comment]
@wsnipex I think libglew can be purged completely now.

**Comment by un1versal** [comment]
> @wsnipex I think libglew can be purged completely now.

I did update as per your comments but left ```libgl1-mesa-dev | libgl-dev```

libgl-dev isnt available anymore am unsure which ubuntu used it last but that needs cleaning up at a later date.

**Comment by FernetMenta** [comment]
I was referring to: https://github.com/xbmc/xbmc/tree/master/tools/depends/target/libGLEW

**Pull request merged**
