### PR TITLE
[cmake/osx] Fix detecting SSE4.2 and AVX2 hardware support

### PR DESCRIPTION
**Pull request by Rechi**

### CODE REVIEW

**Comment by hudokkow** [comment]
ping @fetzerch, @Memphiz or anyone that can test this
jenkins build this please

**Comment by fetzerch** [comment]
LGTM,

Before:
```
-- Found SSE: 1
-- Found SSE2: 1
-- Found SSE3: 1
-- Found SSSE3: 1
-- Found SSE4_1: 1
-- Could not find hardware support for SSE4.2 (missing:  _SSE42_TRUE)
-- Found AVX: 1
-- Could not find hardware support for AVX2 (missing:  _AVX2_TRUE)
```

After:
```
-- Found SSE: 1
-- Found SSE2: 1
-- Found SSE3: 1
-- Found SSSE3: 1
-- Found SSE4_1: 1
-- Found SSE4_2: 1
-- Found AVX: 1
-- Found AVX2: 1
```

systl output:
```
$ /usr/sbin/sysctl -n machdep.cpu.features
FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS MMX FXSR SSE SSE2 SS HTT SSE3 PCLMULQDQ MON SSSE3 FMA CX16 SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES VMM PCID XSAVE OSXSAVE TSCTMR AVX1.0 RDRAND F16C

$ /usr/sbin/sysctl -n machdep.cpu.leaf7_features
SMEP ERMS RDWRFSGS TSC_THREAD_OFFSET BMI1 HLE AVX2 BMI2 INVPCID RTM SMAP RDSEED ADX FPU_CSDS
```

On [jenkins](http://jenkins.kodi.tv/job/OSX-64/9419/consoleFull), the cpu seems to not support avx2, so we've covered that case as well.

**Comment by Memphiz** [comment]
thx for testing @fetzerch

**Comment by hudokkow** [comment]
Thanks for your contribution, @Rechi.

**Pull request merged**
