### PR TITLE
[tools/depends] Bump python 3.11

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Ive been holding out for this, but didnt expect v20 release cycle to still be going by the time this was released, but here we are.
Huge changes to everything build python.
Massive changes to internal python
Im hoping the performance improvements most see with 3.11 will help our use case.

Definitely going to need some testing on this. Either Apple or Android platforms, give me any feedback.
We still manually create Modules/Setup, so i may have missed some modules. Theres been a lot of changes in the cpython module space.

Id like to utilise the "normal" extension build system, but currently we early return to avoid it as we have always done. One day maybe i'll get back the motivation and get this working.

I dont change any of the core code usage of cpython. Theres a bunch of changes relevant to that one day we can look to implement, but nothing im aware of thats been removed in 3.11 to make it a pressing issue. 3.12 is another story though.

## Motivation and context
Python 3.11

## How has this been tested?
Build android arm/arm64, Macos x86/arm, ios/tvos
runtime Android arm64 - tested soundcloud addon from repo, plays back audio

Anyone with an addon, shoot me logs of module failures, and i'll try get them resolved

## What is the effect on users?
N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by matthuisman** [comment]
Where can test builds be downloaded from? Happy to try out a bunch of add-ons on Android and windows

**Comment by fuzzard** [comment]
https://jenkins.kodi.tv/job/BuildMulti-PR/24205/

Artifacts in the Jenkins jobs for android arm and aarch64 will be valid for a couple days.

**Review by enen92 — APPROVED** [review]
Run time tested with a couple of addons on android, didn't get a single regression.
My PIL test addon also works (you might be interested in syncing your fork with https://github.com/enen92/plugin.image.piltest because of some changes on the xbmc API)

Thanks for this!

**Comment by wsnipex** [comment]
Very nice! quickly tested on AFTV (arm32), no issues so far.

**Comment by matthuisman** [comment]
possible to generate a win64 build artifact?

**Comment by fuzzard** [comment]
No, this does not affect windows.

**Comment by Maven85** [comment]
I get this error in several addons:

`2022-10-28 14:30:18.192 T:31657   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named '_posixsubprocess'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.tvnow.de/resources/lib/common.py", line 13, in <module>
                                                       from Crypto.Cipher import DES3
                                                   ModuleNotFoundError: No module named 'Crypto'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/data/user/0/net.kodinerds.maven.kodi20/cache/apk/assets/python3.11/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-linux-x86_64.egg/Cryptodome/Util/_raw_api.py", line 37, in <module>
                                                       from cffi import FFI
                                                   ModuleNotFoundError: No module named 'cffi'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.tvnow.de/service.py", line 10, in <module>
                                                       import resources.lib.manifestServer as manifestServer
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.tvnow.de/resources/lib/manifestServer.py", line 14, in <module>
                                                       import resources.lib.tvnow as tvnow
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.tvnow.de/resources/lib/tvnow.py", line 19, in <module>
                                                       from resources.lib.common import encode, decode, getInputstreamAddon
                                                     File "/storage/emulated/0/Android/data/net.kodinerds.maven.kodi20/files/.kodi/addons/plugin.video.tvnow.de/resources/lib/common.py", line 16, in <module>
                                                       from Cryptodome.Cipher import DES3
                                                     File "/data/user/0/net.kodinerds.maven.kodi20/cache/apk/assets/python3.11/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-linux-x86_64.egg/Cryptodome/Cipher/__init__.py", line 78, in <module>
                                                       from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
                                                     File "/data/user/0/net.kodinerds.maven.kodi20/cache/apk/assets/python3.11/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-linux-x86_64.egg/Cryptodome/Cipher/_mode_ecb.py", line 29, in <module>
                                                       from Cryptodome.Util._raw_api import (load_pycryptodome_raw_lib,
                                                     File "/data/user/0/net.kodinerds.maven.kodi20/cache/apk/assets/python3.11/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-linux-x86_64.egg/Cryptodome/Util/_raw_api.py", line 96, in <module>
                                                       from ctypes.util import find_library
                                                     File "/data/user/0/net.kodinerds.maven.kodi20/cache/apk/assets/python3.11/lib/python3.11/ctypes/util.py", line 3, in <module>
                                                       import subprocess
                                                     File "/data/user/0/net.kodinerds.maven.kodi20/cache/apk/assets/python3.11/lib/python3.11/subprocess.py", line 104, in <module>
                                                       from _posixsubprocess import fork_exec as _fork_exec
                                                   ModuleNotFoundError: No module named '_posixsubprocess'
                                                   -->End of Python script error report<--`

**Comment by fuzzard** [comment]
thanks @Maven85 

Try the latest update. Should fix _posixsubprocess. missed that in the Modules file. Let me know if theres anymore module errors

**Comment by Maven85** [comment]
@fuzzard here is another error:

`2022-10-28 22:40:33.871 T:7937    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'OSError'>
                                                   Error Contents: Cannot load native module 'Cryptodome.Cipher._raw_ecb'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.skysport.de/addon.py", line 5, in <module>
                                                       from resources.lib.startup import run
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.skysport.de/resources/lib/startup.py", line 8, in <module>
                                                       from resources.lib.credential import Credential
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.skysport.de/resources/lib/credential.py", line 6, in <module>
                                                       from Cryptodome.Cipher import DES3
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-linux-x86_64.egg/Cryptodome/Cipher/__init__.py", line 78, in <module>
                                                       from Cryptodome.Cipher._mode_ecb import _create_ecb_cipher
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-linux-x86_64.egg/Cryptodome/Cipher/_mode_ecb.py", line 34, in <module>
                                                       raw_ecb_lib = load_pycryptodome_raw_lib("Cryptodome.Cipher._raw_ecb", """
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.11/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-linux-x86_64.egg/Cryptodome/Util/_raw_api.py", line 174, in load_pycryptodome_raw_lib
                                                       raise OSError("Cannot load native module '%s'" % name)
                                                   OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb'
                                                   -->End of Python script error report<--`

**Comment by fuzzard** [comment]
God damn old libs. i knew this was gonna bite us in the ass one day. Pycryptodome isnt being packaged. I'll try and see why, but i did notice stuff like the following

```
  File "/Users/Shared/xbmc-depends/appletvos16.0_arm64-target-debug/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-macosx-12.5-arm64.egg/Cryptodome/Cipher/ARC4.py", line 149
    except ValueError, e:
           ^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

  File "/Users/Shared/xbmc-depends/appletvos16.0_arm64-target-debug/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-macosx-12.5-arm64.egg/Cryptodome/Cipher/ChaCha20.py", line 153
    except ValueError, e:
           ^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

  File "/Users/Shared/xbmc-depends/appletvos16.0_arm64-target-debug/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-macosx-12.5-arm64.egg/Cryptodome/Cipher/Salsa20.py", line 133
    except ValueError, e:
           ^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

  File "/Users/Shared/xbmc-depends/appletvos16.0_arm64-target-debug/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-macosx-12.5-arm64.egg/Cryptodome/Cipher/_mode_ccm.py", line 197
    elif self._assoc_len < (2L ** 32):
                            ^
SyntaxError: invalid decimal literal

  File "/Users/Shared/xbmc-depends/appletvos16.0_arm64-target-debug/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-macosx-12.5-arm64.egg/Cryptodome/Cipher/_mode_eax.py", line 376
    except KeyError, e:
           ^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

  File "/Users/Shared/xbmc-depends/appletvos16.0_arm64-target-debug/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-macosx-12.5-arm64.egg/Cryptodome/Cipher/_mode_gcm.py", line 527
    except KeyError, e:
           ^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

  File "/Users/Shared/xbmc-depends/appletvos16.0_arm64-target-debug/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-macosx-12.5-arm64.egg/Cryptodome/Cipher/_mode_ocb.py", line 512
    except KeyError, e:
           ^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

  File "/Users/Shared/xbmc-depends/appletvos16.0_arm64-target-debug/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-macosx-12.5-arm64.egg/Cryptodome/Cipher/_mode_openpgp.py", line 201
    except KeyError, e:
           ^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

  File "/Users/Shared/xbmc-depends/appletvos16.0_arm64-target-debug/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-macosx-12.5-arm64.egg/Cryptodome/Cipher/_mode_siv.py", line 135
    initial_value=tag_int ^ (tag_int & 0x8000000080000000L),
                                                        ^
SyntaxError: invalid hexadecimal literal

  File "/Users/Shared/xbmc-depends/appletvos16.0_arm64-target-debug/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-macosx-12.5-arm64.egg/Cryptodome/IO/PKCS8.py", line 201
    except PbesError, e:
           ^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

  File "/Users/Shared/xbmc-depends/appletvos16.0_arm64-target-debug/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-macosx-12.5-arm64.egg/Cryptodome/Math/Primality.py", line 305
    print "Unknown parameters:", kwargs.keys()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

  File "/Users/Shared/xbmc-depends/appletvos16.0_arm64-target-debug/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-macosx-12.5-arm64.egg/Cryptodome/PublicKey/DSA.py", line 234
    return map(int, [self._key[comp] for comp in 'p', 'q', 'g'])
                                                    ^
SyntaxError: invalid syntax

  File "/Users/Shared/xbmc-depends/appletvos16.0_arm64-target-debug/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-macosx-12.5-arm64.egg/Cryptodome/PublicKey/ECC.py", line 98
    _curve.p = Integer(0xffffffff00000001000000000000000000000000ffffffffffffffffffffffffL)
                                                                                        ^
SyntaxError: invalid hexadecimal literal

  File "/Users/Shared/xbmc-depends/appletvos16.0_arm64-target-debug/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-macosx-12.5-arm64.egg/Cryptodome/Signature/PKCS1_v1_5.py", line 44
    except ValueError, TypeError:
           ^^^^^^^^^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

  File "/Users/Shared/xbmc-depends/appletvos16.0_arm64-target-debug/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-macosx-12.5-arm64.egg/Cryptodome/Util/RFC1751.py", line 98
    raise ValueError, "Parity error in resulting key"
                    ^
SyntaxError: invalid syntax

  File "/Users/Shared/xbmc-depends/appletvos16.0_arm64-target-debug/lib/python3.11/site-packages/pycryptodomex-3.4.3-py3.11-macosx-12.5-arm64.egg/Cryptodome/Util/number.py", line 398
    s = pack('>I', n & 0xffffffffL) + s
                                ^
SyntaxError: invalid hexadecimal literal
```

Not sure if this occurs with the 3.9 build process, but all those errors look to be stuff that is/was changed long time ago for py3 compat in upstream pycryptodome (eg 3.12+)
I tried to deal with pyrcryptodome updates once before (https://github.com/xbmc/xbmc/pull/20654) but it required massive rework of how we actual deal with the pythonlib (static -> shared)

I know i commented in that regarding 3.11 maybe making that change not required, so i guess i'll dig into it :/

**Comment by fuzzard** [comment]
Well this got a lot bigger than i wanted.

pycryptodome appears to work for a test plugin on android aarch64. @Maven85 can you give it a whirl now. Jenkins jobs should be finished shortly (only ios to go right now).
@enen92 if you have time want to give it a whirl as well.

Im hoping PIL works as expected, so if anyone has an addon that uses that, give it a whirl and let me know.

**Comment by Maven85** [comment]
@fuzzard 
Now works without problems. Thanks!

**Comment by matthuisman** [comment]
Took it for a spin on my Android phone on a bunch of my addons. Works great :)

**Comment by fuzzard** [comment]
Thanks for the testing and feedback

**Pull request merged**
