### PR TITLE
dvdplayer: fix vfr detection: false positives

### PR DESCRIPTION
**Pull request by FernetMenta**
@jpsdr

now we have reports showing that this algorithm is not 100% reliable
http://forum.kodi.tv/showthread.php?tid=217187
http://trac.kodi.tv/ticket/15738

in all logs I noticed this long pattern of length 41.

### CODE REVIEW

**Comment by jpsdr** [comment]
It seems that it was the question i've been asking almost all the time, because i didn't have this kind of file : what's happening in case of missing/dropping frame of TV recording, the case you were, for good reasons, worried.
If it creates only higher values (frame duration higher => lower fps) it's not an issue, but if it creates lower values, it will be an issue. That's the question i was asking. We thought not.
The fact it creates a framerate value of 24.39 means that unfortunately it's not the case, we thought wrong. Now, if a high lenght of pattern is a specific caracteristic of dropped frame, and dropped frame will always create a high lenght, it will solve. But if not...
I think, for the specific detection of vfr, it could also be added to the length detection :
- to accept on memorised min/max framerates, only standard 23.976,24,25,29.97,30,50,59.97 and 60 fps values. Value should be accurate with an absolute error of less than 0.005.
-  if there is a pattern loss, if current_min and/or current_max is rejected because not a standard value, the pattern lost is not counted for trigging the threshould of vfr case. And of course, the global memorised min/max framerate is not adjusted with the current.
- If there is a pattern loss and length is >=20, same thing. This pattern loss is not counted for trigging the threshould of vfr case, and global min/max is not adjusted.
I think adding this may add to reject false detection.
I think a good... (well, personnaly i don't think vfr is a good thing, only a pain in the ass, but it's another story).. vfr file will only have pattern of standard  framerate values.

What do you think ?

**Comment by FernetMenta** [comment]
@jpsdr thanks. I changed it to consider only standard framerates for vfr. Could you please check if this still works for you?

**Comment by jpsdr** [comment]
No.... It's no use changing here, it should be like this :

        // Update min and max frame duration, only if data is valid
	tempduration = CDVDCodecUtils::NormalizeFrameduration(currentmin, &standard);
    if (m_minframeduration == DVD_NOPTS_VALUE)
    {
	  if (standard)
	    m_minframeduration = tempduration;
    }
    else
    {
      if (standard && (tempduration < m_minframeduration))
        m_minframeduration = tempduration;
    }
	
	tempduration = CDVDCodecUtils::NormalizeFrameduration(currentmax, &standard);
	if (m_maxframeduration == DVD_NOPTS_VALUE)
    {
  	  if (standard)
        m_maxframeduration = tempduration;
    }
    else
    {
      if (standard && (tempduration > m_maxframeduration))
        m_maxframeduration = tempduration;
    }

    //frameduration is not completely correct, use a common one if it's close
    return CDVDCodecUtils::NormalizeFrameduration(frameduration);

**Comment by FernetMenta** [comment]
@jpsdr thanks updated. ok now?

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by jpsdr** [comment]
It should be ok.
Unfortunately some debug information i've put at first were removed, it should have helped to track down and narrow the issue, and figure out where this 24.39 came from...

**Comment by FernetMenta** [comment]
the dubug info spammed the log so I had to remove it.

**Comment by jurrabi** [comment]
Hi there. Is this patch already on nightlies? I have many of those trouble frame-dropping videos so I'll try to test the solution tonight and let you know how it goes...

**Comment by FernetMenta** [comment]
it was merged 4 days ago. if nightly build did not fail, it's included

**Comment by jpsdr** [comment]
I'm interested by getting one or several of these videos if possible...

**Comment by TonyPh12345** [comment]
Hey, folks, I'm running Isengard 15.2, and this code is in there -- but I still see this issue.  

23.976fps videos switch to 30fps (which pushes my TV back to 60fps) .

What can I get for you that might help investigate this?

**Comment by fritsch** [comment]
1) Not spamming github
2) Open a forum thread by posting a debuglog / mediainfo of that file.

**Pull request merged**
