### PR TITLE
[windows] don't mark render buffer as loaded until UploadBuffer is ca…

### LINKED ISSUE #17521: Issues with interlaced MPEG2 with DXVA
### Describe the bug
Here is a clear and concise description of what the problem is:

When seeking forward in an interlaced MPEG2 video (1080i recorded TV show with TVHeadend) while using DXVA render, it will not seek, it just freezes and buffers. If I switch to pixel shader render, it works fine. Progressive MPEG2 recordings (720p recorded show with TVHeadend) work fine.

I don't have any issues with Kodi 18, the issues started with Kodi 19.
Another issue was opened for the same issue but was closed due to user not providing logs. Maybe he can provide his logs as well. https://github.com/xbmc/xbmc/issues/16837

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Seek forward in video without freezing

## Actual Behavior

Freeze and buffers

### To Reproduce

1. Play interlaced MPEG2 using DXVA rendering
2. Seek forward
3.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/kicinapepe.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 64-bit
 - Kodi version: Latest nightly 19.0-ALPHA1 Git:20200318-809e36a24c

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by afedchin**
…lled

try to fix #17521

### CODE REVIEW

**Comment by djp952** [comment]
Appears to solve 17521 for me, suggest considering incorporating changes from cancelled https://github.com/xbmc/xbmc/pull/17779 as NeedBuffer() still flags future frames as necessary for de-interlacing the current frame.  If that's ultimately irrelevant, no worries, just wanted to point it out in case it could cause issues down the road ....

**Comment by afedchin** [comment]
this PR just returns back pre-Matrix behavior: buffers which weren't rendered (weren't used for rendering a frame) is marked as not loaded and will not be marked as necessary by `NeedBuffer()` because they were future frames

**Comment by thexai** [comment]
Is a very minor change but is not necessary obtain  `const int numPast` value for every frame in progressive content.

Maybe can be refactor a bit `CRendererDXVA::NeedBuffer` and add to this PR as well.

From actual:

```
bool CRendererDXVA::NeedBuffer(int idx)
{
  if (m_renderBuffers[idx]->IsLoaded())
  {
    const int numPast = m_processor->PastRefs();
    if (m_renderBuffers[idx]->pictureFlags & DVP_FLAG_INTERLACED &&
        m_renderBuffers[idx]->frameIdx + numPast * 2 >= m_renderBuffers[m_iBufferIndex]->frameIdx)
      return true;
  }
  return false;
}
```
To:

```
bool CRendererDXVA::NeedBuffer(int idx)
{
  if (m_renderBuffers[idx]->IsLoaded() && m_renderBuffers[idx]->pictureFlags & DVP_FLAG_INTERLACED)
  {
    if (m_renderBuffers[idx]->frameIdx + (m_processor->PastRefs() * 2u) >=
        m_renderBuffers[m_iBufferIndex]->frameIdx)
      return true;
  }

  return false;
}
```

Is like a cosmetic only, but...

**Comment by djp952** [comment]
Speaking out of turn ...

Fixing DXVA's NeedBuffer() and this PR both fix the reported issue, but I don't see how it's better to change RendererBase and three of the Windows renderers to solve a likely logic problem that exists in only one of them and on no other platforms?

If the change is solid and should be there, great, but the Windows DXVA renderer logic is still seemingly wrong.  It doesn't need future frames for deinterlacing purposes on the current frame. If the content isn't interlaced the function always returns false regardless of IsLoaded() so future frames don't seem to matter much.

If future frames aren't actually "needed" by the DXVA renderer, the logic in https://github.com/xbmc/xbmc/pull/17779 solves the Issue without potentially affecting any other renderers on any other platforms.

You guys are the experts, of course, and my only goal is to have Matrix work for 1080i TV content, which this clearly accomplishes, but we put some real time and effort into trying to figure this out on Kodi's behalf and came up with https://github.com/xbmc/xbmc/pull/17779 as a viable, low-impact way of doing it.

I'm probably wrong, I usually am, and I'm very glad putting in some time/effort got the necessary attention from the core team, but summarily dismissing the work we tried to do is very frustrating. Doubly so since the logic that was apparently causing the problem still isn't getting cleaned up or has been explained as not flawed to begin with.

**Comment by afedchin** [comment]
> to solve a likely logic problem that exists in only one of them and on no other platforms?

which problem?

> If the change is solid and should be there, great, but the Windows DXVA renderer logic is still seemingly wrong. It doesn't need future frames for deinterlacing purposes on the current frame. If the content isn't interlaced the function always returns false regardless of IsLoaded() so future frames don't seem to matter much.

you are wrong, future frames also may be needed for de-intelacing. your hr requires 1 future and 2 past frames for best de-intelacing see our log file in #17521 
`2020-03-19 12:01:05.573 T:9652   DEBUG: DXVA::CProcessorHD::InitProcessor: selected video processor allows 1 future frames and 2 past frames.`
whats why future frame still left in buffers, because it was "loaded"


> If future frames aren't actually "needed" by the DXVA renderer, the logic in #17779 solves the Issue without potentially affecting any other renderers on any other platforms.

they are needed and it depends on a driver.

**Comment by thexai** [comment]
Tested now in Intel NUC8 (merged with my HDR fork) and all is OK.

Seems this helps too reduce a bit CPU usage. Playing 1080p content never I can see CPU as low 2% (low spikes).

Tested also Gemini Man (HDR 4K  60 fps in RGB output) 7-14% CPU usage,  very very smooth.

So aside from the fix for interlaced DXVA that works well, it seems like the changes don't cause any side effects to the rest. On the contrary, in any case it improves.

I will continue testing it on a daily basis...

**Comment by djp952** [comment]
> > to solve a likely logic problem that exists in only one of them and on no other platforms?
> 
> which problem?
> 
> > If the change is solid and should be there, great, but the Windows DXVA renderer logic is still seemingly wrong. It doesn't need future frames for deinterlacing purposes on the current frame. If the content isn't interlaced the function always returns false regardless of IsLoaded() so future frames don't seem to matter much.
> 
> you are wrong, future frames also may be needed for de-intelacing. your hw requires 1 future and 2 past frames for best de-intelacing see our log file in #17521
> `2020-03-19 12:01:05.573 T:9652 DEBUG: DXVA::CProcessorHD::InitProcessor: selected video processor allows 1 future frames and 2 past frames.`
> whats why future frame still left in buffers, because it was "loaded"
> 
> > If future frames aren't actually "needed" by the DXVA renderer, the logic in #17779 solves the Issue without potentially affecting any other renderers on any other platforms.
> 
> they are needed and it depends on a driver.

Fair enough, and good info thank you very much!  That being the case, shouldn't a CProcessorHD::ForwardRefs() then also be implemented to expose CProcessorHD::m_max_fwd_refs and taken into account during NeedBuffer()? If the required past and forward refs are both exposed, NeedBuffer() shouldn't need to be interlaced content specific either.

**Comment by afedchin** [comment]
> Fair enough, and good info thank you very much! That being the case, shouldn't a CProcessorHD::ForwardRefs() then also be implemented to expose CProcessorHD::m_max_fwd_refs and taken into account during NeedBuffer()? If the required past and forward refs are both exposed, NeedBuffer() shouldn't need to be interlaced content specific either.

past and future frames are needed only for deinterlacing, no need keep them for progressive material. also no need to process future frames in `NeedBuffer()` because there is a least one future frame before rendering. May be in future when driver will support frame rate conversion i.e. convert a video to from 24(30) to 60 fps like SPV does.

**Pull request merged**
