### PR TITLE
exclude resource:// from texture caching as these are always local ad…

### PR DESCRIPTION
**Pull request by MartijnKaijser**
…dons

### CODE REVIEW

**Comment by Montellese** [comment]
Fine with me.

**Comment by MilhouseVH** [comment]
What happens if a resource is, for instance, a progressive jpeg which may not be compatible with hardware decoding on some devices?

In the case of the RPi, progressive jpegs are software decoded to a compatible version which is then cached. Now, won't progressive jpeg resource:// items always be software decoded on the PI?

If a resource:// item is unfortunate enough to be incompatible with certain devices, it could result in a bad user experience whereas previously the user might take the hit only once until a compatible version of the image has been cached.

**Comment by MartijnKaijser** [comment]
then the devices should handle it or the one who makes the package shouldn't screw it up to start with.
we should not start caching the images we just pulled out of skin:// which were never, ever cached before. the image packs provided through our repo will also be run through texturepacker.

**Comment by MilhouseVH** [comment]
OK fair enough, I agree it would be a screw up by the package author as they should always use image formats that are 100% compatible with all devices (ie. nothing too fancy).

**Comment by popcornmix** [comment]
Can we make texturepacker convert progressive jpegs to baseline.
This can be done losslessly with [jpegtran](http://linux.die.net/man/1/jpegtran), and the result should be smaller and faster to decode (on any platoform) and makes hardware decode possible.

**Comment by MartijnKaijser** [comment]
yeah we could maybe, perhaps or something. Doesn't mean who ever else creates their own repo will do the same.

**Pull request merged**
