### PR TITLE
[discs] Fix resume in blurays (and br isos)

### PR DESCRIPTION
**Pull request by enen92**
Backport of https://github.com/xbmc/xbmc/pull/21250

### CODE REVIEW

**Review by howie-f — APPROVED** [review]
maybe let it roll for some time on master to shake out possible fallout? i dont expect any, you just never know 🤷

**Comment by enen92** [comment]
Sure, will merge later by the end of the month or so if nothing pops up :)

**Comment by enen92** [comment]
This one is pending because of https://github.com/xbmc/xbmc/issues/21285

**Comment by DaveTBlake** [comment]
Do we go with this for 19.5 @enen92 ?
I understand there are still problems with resume, but will users be better off with this anyway or is it bump to 19.6?

**Comment by enen92** [comment]
I'd say to skip this one for now, better not being able to resume than to resume to a wrong track. Looks like a few people use tvshow blurays. I plan to continue working on this for v20 however the changes needed to get this working properly are not compatible to simple backports to matrix.

**Pull request closed without merging**
