### PR TITLE
[win32] - add inapp update feature via winsparkle

### PR DESCRIPTION
**Pull request by Memphiz**
Well basically the same like #6474 just for windows. Need to upload the package once home and verify how to adapt the xml to serve both - win32 and osx at the same time. Windows version has no signing support (and so its not forced and needed of course).

Screenshots (didn't came further due to firewall restrictions):

https://dl.dropboxusercontent.com/u/30371861/sparkle/01-winsparkle-update.png
https://dl.dropboxusercontent.com/u/30371861/sparkle/02-winsparkle-update.png

### CODE REVIEW

**Comment by Memphiz** [comment]
@Montellese or @Karlson2k the package puts the winsparkle.dll to system - but when i debug it can't find it - how is this supposed to work when adding dlls? (which are not loaded manually but simply by using its .lib file). I had to copy the dll into the kodi.exe output dir for getting it to run. I think there might even be something missing for packing it correct then (no nsis here). Would be cool if one of the windows devs could pick this up and make it right. (or at least provide the guidline)

**Comment by Karlson2k** [comment]
@Memphiz Add .dll to delay loaded dll list in linker settings.
But do we want such kind of updater? Isn't it better to use updater from Kodi GUI? Some users already asked for it.
Kodi GUI is definitely better for standalone HTPC which is controlled mostly by remote control.

**Comment by topfs2** [comment]
We have a standalone flag which we could use to differentiate between kodi
GUI and sparkle GUI.

**Comment by Karlson2k** [comment]
@topfs2 How this flag will help to update Kodi itself from Kodi GUI?

**Comment by Memphiz** [comment]
The api allows to use our own gui - but this has to be implemented ... (with this minimal implementation it uses the updaters UI).

**Comment by wsoltys** [comment]
Nice work @Memphiz. When using an import lib the dll needs to be next to the binary. This can be changed if delay loading works. Additionally to the changes to the project file you need to add a hook in https://github.com/xbmc/xbmc/blob/master/xbmc/win32/Win32DelayedDllLoad.cpp.

**Comment by topfs2** [comment]
@karlson2k it doesnt do anything without implementation. What I meant is
with that flag you can know which of the two guis you should pick.

And as memphiz said, in kodi update could come later.

**Comment by Memphiz** [comment]
did the delayed load thingy

**Comment by Memphiz** [comment]
integrated into #6474

**Pull request closed without merging**
