### PR TITLE
[guiinfo/skin] fix format of GUIProgressBar and remove duplicate textures

### PR DESCRIPTION
**Pull request by howie-f**
## Description
return format of `CGUIProgressBar::GetDescription()` is fixed to `{:1.0f}` because if its current value is <10 the function would return `" 9"` (with a preceding whitespace).

this allows proper operation of integer comparisons in Integer.infos (skin side) after https://github.com/xbmc/xbmc/pull/21352
also estuary textures `p 0.png - p 9.png` in https://github.com/xbmc/xbmc/tree/master/addons/skin.estuary/media/dialogs/volume/progress can be removed now. they are only duplicates of `p0.png - p9.png`.

estuary determines the texture to load by `$INFO[Control.GetLabel(29999),dialogs/volume/progress/p,.png]` where `29999` is a hidden ProgressBar. that why both versions `pX.png` and `p X.png` were needed.

## How has this been tested?
tested estuary, the textures of DialogVolumeBar for volume range 0-9 are the same like before.
runtime tests are very welcome

## What is the effect on users?
none

## Types of change

- [X] **Improvement** (non-breaking change which improves existing functionality)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document

### CODE REVIEW

**Comment by lrusak** [comment]
I think skin changes need to go upstream?

**Comment by howie-f** [comment]
that‘s possible. i don‘t know where estuary lives upstream but i‘m sure they will tell us

**Comment by enen92** [comment]
Estuary upstream is this repo afaik

**Comment by jjd-uk** [comment]
Since Phil stopped maintaining Estuary, the main XBMC repo is now the sole upstream

**Review by enen92 — APPROVED** [review]
2 decimal places for precision in progress controls don't make much sense anyway.
nice cleanup

Regardless for the root cause of the problem we probably need to provide the info as integer as an alternative (if not already available). Doesn't make sense to be converting from a label to int in the skin you're using.

**Pull request merged**
