### PR TITLE
[Windows] Fix TexturePacker build / build in tree

### PR DESCRIPTION
**Pull request by CrystalP**
## Description

Get TexturePacker to build in tree for Windows targets (except UWP - still using downloaded deps, since UWP is not a dev/build environment and there is no need for an UWP TexturePacker)

* Added the missing required deps for x64 (were already listed for win32)
  * the packages already exist on the mirrors
  * the linker doesn't like the .pdb bundled with the libs, maybe a package rebuild would help? see linker error message later
 
* FindTexturePacker.cmake: use external (downloaded package) for UWP, internal otherwise.
This could probably be integrated better with the linux stuff later in the file instead, to use compatibility of host and target to decide on internal/external. I have very limited cmake skills and didn't want to risk breaking other platforms.

* TexturePacker CMakeLists.txt: Windows requires a couple additional files/headers to emulate libc functions

* TexturePacker: the default constructor was causing compilation problems due to GetCommandLine() returning wide characters on Windows. Since the rest of the program doesn't handle wide characters either, it seemed best to remove that constructor (which was not used by any code, TexturePacker or tests) and leave wide characters / unicode support for another PR.

Open points;
- there is an old Visual Studio solution in tree (VS2017 maybe older?). Should it be removed since cmake works now and generates current solution and project?
- similar to jsonschemabuilder, the TexturePacker is still systematically downloaded even when an internal one will be built and used. Possible to remove, but kind of complicated for the benefit.
- how to upload up to date .exe to the mirrors, for the UWP builds?

Following warnings of the linker with current mirror deps:
```
1>libpng16_static.lib(png.obj) : warning LNK4099: PDB '' was not found with 'libpng16_static.lib(png.obj)' or at ''; linking object as if no debug info
1>libpng16_static.lib(pngread.obj) : warning LNK4099: PDB '' was not found with 'libpng16_static.lib(pngread.obj)' or at ''; linking object as if no debug info
1>libpng16_static.lib(pngerror.obj) : warning LNK4099: PDB '' was not found with 'libpng16_static.lib(pngerror.obj)' or at ''; linking object as if no debug info
1>libpng16_static.lib(pngrtran.obj) : warning LNK4099: PDB '' was not found with 'libpng16_static.lib(pngrtran.obj)' or at ''; linking object as if no debug info
1>libpng16_static.lib(pngtrans.obj) : warning LNK4099: PDB '' was not found with 'libpng16_static.lib(pngtrans.obj)' or at ''; linking object as if no debug info
1>libpng16_static.lib(pngget.obj) : warning LNK4099: PDB '' was not found with 'libpng16_static.lib(pngget.obj)' or at ''; linking object as if no debug info
1>libpng16_static.lib(pngset.obj) : warning LNK4099: PDB '' was not found with 'libpng16_static.lib(pngset.obj)' or at ''; linking object as if no debug info
1>libpng16_static.lib(pngwrite.obj) : warning LNK4099: PDB '' was not found with 'libpng16_static.lib(pngwrite.obj)' or at ''; linking object as if no debug info
1>libpng16_static.lib(pngmem.obj) : warning LNK4099: PDB '' was not found with 'libpng16_static.lib(pngmem.obj)' or at ''; linking object as if no debug info
1>libpng16_static.lib(pngwutil.obj) : warning LNK4099: PDB '' was not found with 'libpng16_static.lib(pngwutil.obj)' or at ''; linking object as if no debug info
1>libpng16_static.lib(pngrio.obj) : warning LNK4099: PDB '' was not found with 'libpng16_static.lib(pngrio.obj)' or at ''; linking object as if no debug info
1>libpng16_static.lib(pngrutil.obj) : warning LNK4099: PDB '' was not found with 'libpng16_static.lib(pngrutil.obj)' or at ''; linking object as if no debug info
1>libpng16_static.lib(pngwio.obj) : warning LNK4099: PDB '' was not found with 'libpng16_static.lib(pngwio.obj)' or at ''; linking object as if no debug info
1>libpng16_static.lib(pngwtran.obj) : warning LNK4099: PDB '' was not found with 'libpng16_static.lib(pngwtran.obj)' or at ''; linking object as if no debug info
1>jpeg-static.lib(jsimd_none.obj) : warning LNK4099: PDB '' was not found with 'jpeg-static.lib(jsimd_none.obj)' or at ''; linking object as if no debug info
```

## Motivation and context

The packaged TexturePacker.exe dates back to Jan 2020 and was missing lrusak's recent improvements as well as a few older ones as well.
Attempting to build the program revealed a broken build system.

## How has this been tested?

Tried all windows / uwp architectures, and built with Visual Studio, cmake, and BuildSetup

## What is the effect on users?

Skin textures packed with the latest and greatest TexturePacker improvements.
Easy to build TexturePacker win32/x64 debug/release.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
This is wrong. Texturepacker is a build tool. Ie its run on the host, not target.

If you want to download the dependencies for texturepacker, they need to go into https://github.com/xbmc/xbmc/blob/master/project/BuildDependencies/scripts/0_package.native-win32.list and not the target lists.

Better to do this right, and build texturepacker for all platforms like we now do for flatc (build tools for flatbuffer usage in target). This would mean theres no windows_store check, as again, its a build tool built for the host. Texturepacker has no need to know about target platform.

**Comment by CrystalP** [comment]
@fuzzard I don't really know what I'm doing :-) First time dabbling a bit in cmake.

What to change to get TexturePacker to build for the host arch instead of the target arch?
(maybe it's already done that way! but I can't tell)

**Comment by CrystalP** [comment]
@fuzzard followed your suggestion and texturepacker only builds when target is win32.
0_package.native-win32.list downloads is meant for 32 bits, which is OK for exe as win64 will execute either bitness, but not OK for linking with a different bitness / arch.
I can think of ways to create 0_package.native-x64.list and have it used appropriately but cmake will still configure TexturePacker for target rather than host and I need help with that.

**Comment by fuzzard** [comment]
Superseded by #23417

**Pull request closed without merging**
