### PR TITLE
Use mmap to accelerate SQLite file accesses

### PR DESCRIPTION
**Pull request by bavison**
Here are a couple of changes that between them make SQLite searches about 41% faster in my tests on a Raspberry Pi.

They have only been tested with PR #4235 in place, and the timings were also done using SQLite version 3080301, but they may still work with the older version 3071000 (though you'll probably get at least some warnings about line offsets in the patch operation).

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
@bavison @popcornmix what's the story on this PR?

**Comment by popcornmix** [comment]
I believe this PR gives a performance benefit and has been included in OpenELEC for over a year without issue:
https://github.com/OpenELEC/OpenELEC.tv/commit/59868b5cf1980728dcc32c65831f41e2b3544cfa

I think it should be merged. @bavison can you rebase?

**Comment by mkortstiege** [comment]
@bavison, mind rebasing?

**Comment by stefansaraev** [comment]
I picked this work in #7926

**Pull request closed without merging**
