### PR TITLE
bump kodi-platform and p8-platform

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

### CODE REVIEW

**Comment by FernetMenta** [comment]
@opdenkamp @wsnipex ok?

**Comment by opdenkamp** [comment]
hashes look okay, but we may want to address https://github.com/xbmc/kodi-platform/pulls first

**Comment by FernetMenta** [comment]
all of them? could you please merge the ones you think are ok?

**Comment by opdenkamp** [comment]
merged one, commented on the rest

**Comment by FernetMenta** [comment]
thanks, hash updated

**Comment by Memphiz** [comment]
is there a plan who is fixing all the addons which fail to build now?

**Comment by MartijnKaijser** [comment]
@Memphiz PRs are pending for PVR already

**Comment by Memphiz** [comment]
ok - just wanted to know if i should do it ;)

**Pull request merged**
