### PR TITLE
[EPG] Misc. EPG window fixes

### PR DESCRIPTION
**Pull request by ksooo**
Superseeds #7421

Commits:

(1a) fix epg grid init
- fixes: infamous error message "CGUIEPGGridContainer - UpdateItems - invalid start and end time set" that was for ages in (my) kodi.log
- cause: first epg grid update gets triggered during WindowPVRGuide::OnInitWindow() already, even before first WindowPVRGuide::Update(). start and end time are not set at that early stage.
- details
  *\* illustrated call stack: http://paste.ubuntu.com/11878995/
- fix: set start and end time at epg grid control in OnInitWindow() before calling bas class

(1b) fix epg grid update
- fixes: each guide WindowPVRGuide::Update() caused (up to) 4 epg grid updates. Interestingly, all of those messages except the last had an empty item list, causing multiple and senseless epg grid data resets. Only the last update message contained the correct number of list items and caused the correct grid update
- cause: design flaws in data retrieval logic of WindowPVRGuide in interference with MediaWindow base class implementation
- details 
  *\* WindowPVRGuide::Update() first calls base class
  *\* MediaWindow::Update() calls virtual GetDirectory(). WindowPVRGuide has no own GetDirectory() implementation. MediaWindow GetDirectory() returns empty item list which overwrites current m_vecItems. Subsequent (actually unwanted and unneeded) calls to ViewControl::SetItems() pass empty m_vecItems to the epg grid.
  *\* back in WindowPVRGuide::Update, m_vecItems is finally filled correctly and past to the epg grid
- fix: retrieve data in new WindowPVRGuide::GetDirectory() implementation, making WindowPVRGuide::Update() implementation obsolete

(2) fix epg window view jumping to "now" on every epg grid update 
- fixes: epg timeline window viewport jumps to "now" on every epg data update, can happen any time, depending on the frequency and amount of epg data updates. Very annoying for instance if you just scrolled 2 days into the future to setup a timer.
- cause: the jump to now was unconditionally coded into the epg update code of the epg grid container control
- fix: remember current selection on update start, restore the selection after update. Do only change view port if selection is no longer available (e.g. because the event got removed during update)

(3) feature. use remote key "0" in the epg grid container control to jump to 'now' 
- I just found it very useful after fixing the automatic jump to now bug to have the possibility to manually jump to 'now'

(4) fix: make epg grid container control thread save
- fixes random crashes of Kodi while in EPG window
- cause: epg grid control was not threadsafe, but got called from different threads (main and python lcdproc addon in my case)
- details
  *\* calls stacks: http://paste.ubuntu.com/11878966/

(5) reduce lagging of EPG window caused by huge amount of update events in a short time frame
- cause: observed up to 200 epg grid update events in a row in about 10 secs, EPG window is almost unusable during this time
- fix: limited number of update requests actually processed by the epg grifd control to 1 per 3 secs
- 3 secs is just an empiric value that greatly improves (but not completely fixes) lagging of the UI during updates for me

### CODE REVIEW

**Comment by ksooo** [comment]
@fritsch may want to try this out (runtime test)?

**Comment by ksooo** [comment]
@xhaggi mind doing a review?

**Comment by fritsch** [comment]
Thanks very much. I will give it a test, let's see. For codereview please ask your fellow PVR colleagues.

**Comment by fritsch** [comment]
@ksooo The jumping in EPG list is gone. Looking at the code and that scoped locks all over - I think some redesign is needed of how those methodes are invoked and from where.

but that's for @xhaggi

**Comment by opdenkamp** [comment]
half the class could use a redesign indeed ;) but from the looks of it you're only protecting half the members and leave others untouched. what's the idea there?

don't have time to review atm, getting the key to my new house tomorrow morning and got some stuff to do still. also means that I probably won't be able to review much in the next few weeks

**Comment by ksooo** [comment]
@opdenkamp wish you luck and all the best with your new house.

Regarding thread safety: I should have known that I will not get through with this lazy approach. ;-) Idea should be to introcuce as less locks as possible to fix exactly the crash scenario I observed. Will (have to) rework this (obviously).

**Comment by xhaggi** [comment]
@ksooo I'll take a look at this if you've done the re-worked of the locking. I don't have much time atm and don't want to do it twice.

**Comment by xhaggi** [comment]
>(1b) fix epg grid update

While I've done the "window rewrite", I didn't thought about changing the implementation, but your approach makes much more sense. great ;)

**Comment by ksooo** [comment]
Okay, did my concurrency homework now. ;-) Fix is now shaped exactly to the crash scenario I observed, thus, number of locks greatly reduced, only data affected by the actual case are protected now. Analysis and details here:  http://paste.ubuntu.com/11884628/

**Comment by ksooo** [comment]
@xhaggi thanks for the review. Changes requested for commit 5 (lagging) are in now. Other requests are further improvements will be done in a followup PR. Any further comments or ready for the last step for now, the merge of UpdateItems() and OnMessage(MSG_GUI_LABEL_BIND) code into UpdateItems()?

**Comment by xhaggi** [comment]
> Any further comments or ready for the last step for now, the merge of UpdateItems() and OnMessage(MSG_GUI_LABEL_BIND) code into UpdateItems()?

apart from the minor with the parentheses, no ;)

**Comment by xhaggi** [comment]
great lets ask jenkins build this please

**Comment by ksooo** [comment]
@xhaggi di you want to merge this now or can I add 2 other commits ontop? First would be the refactoring of UpdateItems and surrounding code, second is the data type change you suggested to get rid of that CFileItem * casts.

**Comment by fritsch** [comment]
Please separate refactoring from fixes. That way it's easier to backport.

2015-07-16 19:51 GMT+02:00 Kai Sommerfeld <notifications@github.com>:

> @xhaggi <https://github.com/xhaggi> di you want to merge this now or can
> I add 2 other commits ontop? First would be the refactoring of UpdateItems
> and surrounding code, second is the data type change you suggested to get
> rid of that CFileItem * casts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xbmc/xbmc/pull/7509#issuecomment-122034208>.
>



-- 
                   Key-ID:     0x1A995A9B
                   keyserver: pgp.mit.edu
==============================================================
Fingerprint: 4606 DA19 EC2E 9A0B 0157  C81B DA07 CF63 1A99 5A9B

**Comment by ksooo** [comment]
@fritsch good point. Will do refactoring in another PR, though I have no plans to backport this PR.

**Comment by xhaggi** [comment]
np push your changes, i thought you are ready

**Comment by ksooo** [comment]
@xhaggi Well, after reading @fritsch's comment - I'am ready. Will do refactoring in another PR. ;-) So go ahead and merge it as it is now, if you like.

**Comment by xhaggi** [comment]
as it fixes different issues should we consider a backport as fritsch said?

**Pull request merged**
