### PR TITLE
OpenGL: boost shader performance for Lanczos3 optimized

### PR DESCRIPTION
**Pull request by FernetMenta**
See title. Allows HQ scaling on a 4k display.

Some cleanup in shader area.

### CODE REVIEW

**Comment by fritsch** [comment]
Something went wrong from the version yesterday:
image

Seems like the offsets are wrong (vertical stripes)

Performance wise: Really great. It basically uses half the sampler load and therefore needs also only half the throughput per second. Tested with gputop.

**Comment by fritsch** [comment]
@lrusak if you find an GLES < 3.1 alternative for ```textureGatherOffset```  you could adapt 1:1 - from my pov this is the source of most of the advancement we get here.

**Comment by fritsch** [comment]
Update: Dithering is broken - the shader works fine :-)

Here is a summary of the work fernetmenta did and was pleased to help testing:
image

**Comment by fritsch** [comment]
Load with new Shaderwork (Upscaling 576i50 to 3840 50p):
image

No skips, no drops.

**Comment by fritsch** [comment]
Old implementation:
image

Server drops and skips. You can see the

**Comment by fritsch** [comment]
The squash commit fixes dithering - thx much.

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by FernetMenta** [comment]
UWP-64 error unrelated

**Pull request merged**
