### PR TITLE
update requirements

### PR DESCRIPTION
**Pull request by newEntera**
## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Rechi** [comment]
@newEntera please explain why you think zip, unzip, cmake and build-essential are required

**Comment by newEntera** [comment]
@Rechi That's too complicated for me to answer. Simply make of raspberry tools asks about it and I install it and I update the requirements here. Is that an valid answer ? Do I pass the exam :) ?

**Comment by bh** [comment]
What a stupid answer for an legitimate question.

**Comment by newEntera** [comment]
Thank you for insulting me.
Legitimate question is why do you think it is a legitimate ?
 Is it legitimate to have README instructions that more steps that are not described and I put them to make it easier for me when I come back here after 5 months If I have to be selfish. But I do it for the community to make it easier to the rest of people like me.

**Comment by MartijnKaijser** [comment]
@newEntera Sorry but you were asked a question by a team member and your response was to thumbs down his question and make a smart ass remark. Goodbye

**Comment by Jalle19** [comment]
How could `cmake` not be a requirement? Don't we use cmake for everything?

**Comment by Rechi** [comment]
@Jalle19 the change is for the section which describes building with depends.
Cmake gets compiled from source in depends and the system cmake would never be used.

**Comment by Jalle19** [comment]
@Rechi okay
@newEntera what about the other dependencies, at what point did you actually need them?

**Comment by newEntera** [comment]
@Rechi 
Following xbmc/docs/README.raspberrypi cmake does not get compiled from source. Or please show me what I have missed if so, or I'm wrong and it's not included in $PATH ?
@Jalle19 following strictly xbmc/docs/README.raspberrypi on 16.04 is zip,unzip is what I have missed to succeed. It was at the point of raspberry tools. Sure out of kodi's scope but this is what you need if you want to make a build environment to compile for raspberry pi. Maybe the build environment is created other way for build for Ubuntu and Rechi is mistaken by that cmake is build from source?
While build-essential is included in 16.04 Desktop, it is not included in 16.04 minimal or 16.04 server which I used.

**Comment by Rechi** [comment]
https://github.com/xbmc/xbmc/blob/4bd402f/docs/README.raspberrypi#L40-L50 builds depends (including cmake)

**Pull request closed without merging**
