### PR TITLE
[scrapers] python3 based movie and tv show scrapers

### PR DESCRIPTION
**Pull request by pkscout**
## Description

Python based scrapers for movies and tv shows (using TMDb as the source).

## Motivation and Context

The XML based scrapers are only sort of supported, and there is a desire to move to Python scrapers as default for Matrix so we can remove the XML scrapers in version 20.

## How Has This Been Tested?

The movie scraper has been in use for over a year and tested by members of the team and community. The tv show scraper is newer but based on code from the movie scraper and the TV Maze scraper. It has been tested by team members on multiple platforms and community members from the forum.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

Documentation for both scrapers already exists, so I don't think any additional documentation is needed.

### CODE REVIEW

**Comment by DaveTBlake** [comment]
So this adds  `metadata.themoviedb.org.python` and `metadata.tvshows.themoviedb.org.python` to the main repo and makes them the default movie and tvshow scraper.

Looks fine to me @pkscout but I will run up a test build and try it just to be sure.

**Comment by DaveTBlake** [comment]
>there is a desire to move to Python scrapers as default for Matrix so we can remove the XML scrapers in version 20.

No way for you to know but the guys that maintained the XML scrapers did have the removal  of xml scrapers thrown at them without any discussion or explanation. IMO it was a pretty brutal way to treat fellow team members, and no big surpize that their active support for these scrapers has been deminished. 

I know the big question @olympia has asked is "why remove the xml scrapers"? I don't have a clear answer, perhaps others would like to explain why not only do we want to replace them with easier to maintain Python versions that are easier to adapt to remote site API changes etc., by why remove xml scraping entirely in v20? What will be gained?

@notspiff , @rmrector perhaps you have insight into this?

**Comment by olympia** [comment]
Thanks @DaveTBlake 

Hello Team,
I am wondering what "sort of supported" means?! 
I am not aware of any general issue or bug the XML scrapers are suffering from. The libcurl issue recently was addressed within a few hours once the root cause has been identified. (while I was actually out in the wild with little to no mobile coverage on a family/friends weekend trip).

Also, I am not aware of any major feature the XML scrapers are missing. 
In fact there is still no python scraper what is in feature parity with Universal Movie Scraper.

I heard that there are python scraper developer, who has stated he was only really interested in developing the scraper, but not running in on the long term. Almost every python scraper was developed by someone else. I can just hope they will all support their scrapers in the "sort of way" the XML scrapers are supported today.

Dave is asking the question (thanks again) what will be gained by removing XML scraping.
I can still ask the question, what have we gained with python scraping so far? What will be announced proudly in the v19 version announcement? How python scrapers are better, what will users notice? I guess nothing?

**Comment by rmrector** [comment]
> I can still ask the question, what have we gained with python scraping so far?

- a "filename only" scraper that doesn't have to reach out to a web server
- scrapers that don't break arbitrarily when non-material changes to API results change, such as the order of fields in JSON objects
- Python is a complete software language, so now we have a lot more flexibility when providing information for "movie X" - we can do more than "grab a long string from a website" and then "try to pull information out of the string"
- Python is a general purpose language that is known outside of Kodi - XML scrapers are not. Python is a skill useful in other places, Kodi's XML scrapers are not. A lot more people are capable of keeping Python scrapers up and running, so we don't leave the fate of "scraping" for this entire app with its many users to this very silo'd knowledge - that's not safe for a project this size.

**Comment by pkscout** [comment]
I just want to apologize for not properly understanding the background on this issue.  What I said in the PR was based on information from others that I did not verify, and I'm sorry for how I handled it. I was asked to do the Python TV show scraper and thought I was helping to fill a gap in the roadmap.  I honestly don't have strong feelings one way or the other on making these the default scrapers and will be happy to follow the lead of the rest of the team on this.

**Comment by rmrector** [comment]
@KarellenX specifically requested the movie scraper be set as the default here https://github.com/xbmc/metadata.themoviedb.org.python/issues/51

**Comment by olympia** [comment]
I am aware of the crusade against XML scrapers and I have given up on it at some point. I am now having strong feelings again, because the whole thing started to be sold that scraping was a painful and problematic part of Kodi and now, finally it is all fixed. This is a lie and offending (@pkscout apologies accepted - you couldn't know. ...but what you heard and know is a very good proof of the marketing engine of the Python pushers).

While I was aware and accept the points from @rmrector above, those are not justifying (yet) the whole story and handling how it is occurred and occurring. Sure, XML based scrapers are more fragile for changes, but in the past few years such scraper breaking change has happened on once in every year, what always have been fixed in a few hours). Sure, it will be better not having this at all, but there would have been more painful, problematic or features weak parts of Kodi to work on first.

_"We can do more than "grab a long string from a website" and then "try to pull information out of the string"_
@rmrector this could be indeed a significant benefit and should show the power over XML scraping engine. But this is not happening and I have the feeling that will not happen soon, because no one with the skills really have the desire to improve here as far as I see.

...but as I said, I have given up on this, I was not never convinced, but I don't care any more if Python scrapers will be the default ones.

**...however the other reason I am having strong feelings again is the removal of XML scraper engine. I know, I know. Having and maintaining the two together is chaining down Python scraping capabilities, but please can we get to the state first when this is a blocker for anything and until then, leave the XML scraper engine in its place?**

There are these huge efforts for theoretical possibilities, but then things are not happening. Why all these development capacity is not going into something what makes Kodi really visibly better. This has happened now with scraping (reinventing the wheel what was actually working quite well), but it is not only about scraping, this is a general issue at least in my eyes. There are all these under the hood rewrites, but very little improvements on the surface.

**Comment by DaveTBlake** [comment]
Because of  both technical strength and adaptability, and potential for more dev interest and involvement the way forwards is clearly involves scrapers written in Python. Because of that future it also makes sense to make those the default scrapers for v19. They are mature enough for that to happen, and doing so will provide us with real world feedback. Better to make that step in a controlled and considered way now, than be forced to by some change in a remote site's API or the absence of the one person supporting the xml scrapers. 

However that forwards step has also become conflated with removing the xml scrapers completely, and understandably rouses Olympia's feelings. We sometimes use too much shorthand in our conversations, and I believe that this is the case here. Having talked with Spiff I think I can now answer my own question.

There is no plan and no one is going to remove the xml scraper functionality just for the sake of it. That would be pointless. However there is _potential_ when using Python to fetch information from remote sites in batches and thus reduce the latency involved in making multiple requests. Users would be very happy to have scraping a large library happen quicker, and it would make us better consumers for the remote sites too. To do that would mean changes to the scraper interface in core, and so would impact xml scrapers too. At that point of core changes we have to decide if it is worth the extra effort to keep the xml scrapers working as well, or if they have been superseded by Python ones (which is expected).  It is far from certain that point will come in v20, it all depends if devs decide to work on such a facility,  that the API of the remote sites makes it viable (and when v20 is going to happen).

Looking forwards the long term future of xml scrapers is unlikely. It is not that we have a plan to remove them, but that we have the idea for faster batched request scraping, and implementing that could bring the end to xml scrapers.

**Review by DaveTBlake — APPROVED** [review]
Tested on a fresh install and all worked as expected, thanks @pkscout

**Pull request merged**
