### PR TITLE
reverse logic from commit abc298ca71c25ae57081aad60ba5ef0abec3a445

### PR DESCRIPTION
**Pull request by mad-max**
As discussed in the old PR #6559 the logic for Hide/Show "All Items" has been reversed

mad-max

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
rebase please ;)

**Comment by mkortstiege** [comment]
Users will update and be confronted with a different behavior due to settings name change. Please correct me if i am wrong. This is somewhat meh in case i am right. On the other side i agree that hide disabled = enabled makes no sense at all ;)

**Comment by da-anda** [comment]
@mkortstiege the setting is in GUI settings for like 4 days? Who cares if the few nightly build users have to set this setting again? Still better than having to drag a migration script along

**Comment by mkortstiege** [comment]
Oh, right. All good then.

**Comment by mad-max** [comment]
@MartijnKaijser rebased :)

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Comment by mad-max** [comment]
Linux failed, but not a file I have touched...strange...

**Comment by mkortstiege** [comment]
Unrelated jenkins hiccup.

**Pull request merged**
