### PR TITLE
Controller topology (multitap support)

### PR DESCRIPTION
**Pull request by garbear**
This PR contains the final architecture needed for the Player Manager. Whereas #13374 abstracted keyboards and #13482 abstracted mice, this PR presents an abstraction for multitaps (aka hubs).

The conclusion of the Controller Topology Project is significant because we can, for the first time, model how controllers connect to and map to each other for all of gaming history.

ps multitap

## Description
At the highest level, this PR adds a new concept to the Game API: the controller topology. A topology defines how things are connected, so this concept lets the player manager reason about how to automatically connect input devices to the console and to each other. This happens without any user effort.

To give a concrete example, SNES and Genesis consoles only have two ports, but they support up to 5 controllers with a multitap. However, multitaps break some games. We can safely default to 2 controllers, and when a new user joins, the (future) Player Manager automatically swaps player 2 with a multitap, then connects player 2 and player 3 to the multitap's ports.

Controller topologies have been expanded to support daisy-chaining as well. For example, the 3DO had a single port, and up to 8 controllers could be daisy-chained together. This will be reflected in the Player Manager where it's impossible to have a player 2 without a player 1.

Finally, a distinction is made between the *physical topology* and *logical topology*. The physical topology defines how controllers physically connect together. For example, you can plug a multitap into a multitap. The logical topology defines a subset of those connections that the emulator's logic supports; obviously no emulator allows a multitapped multitap, so even though this is physically possible, it is disallowed.

## Motivation and Context
Like all other input features, this came about while trying to automate a part of the libretro API. While awesome at what it does, the libretro API makes emulation horribly inaccessible to users who don't have any concept of what a RetroPad or a Multitap is.

## How Has This Been Tested?
Configuring multitaps requires a Player Manager, which is still in progress. For now, game console ports are hard-coded to accept the first controller specified by their topology.

Tested with controllers, keyboards and mice and various emulators on Linux and OSX.

Android requries https://github.com/fetzerch/kodi-game-scripting/pull/19 to fix game add-ons.

Game add-ons on Windows broke after https://github.com/xbmc/xbmc/pull/13140. I'd appreciate help fixing this.

## Screenshots (if appropriate):
A (theoretical) example of how depth-first controller-to-player assignment works:

hubs

## Types of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Required PRs
- [x] Libretro compatibility (https://github.com/kodi-game/game.libretro/pull/31)
- [x] Game controller database (https://github.com/kodi-game/kodi-game-controllers/pull/20)
- [x] Resource repo (https://github.com/xbmc/repo-resources/pull/47)
- [x] Binary add-on repo (https://github.com/xbmc/repo-binary-addons/pull/103)
- [x] 2048 (https://github.com/kodi-game/game.libretro.2048/pull/5)
- [x] 4DO (https://github.com/kodi-game/game.libretro.4do/pull/3)
- [x] Beetle bSNES (https://github.com/kodi-game/game.libretro.beetle-bsnes/pull/5)
- [x] Beetle Cygne (https://github.com/kodi-game/game.libretro.beetle-wswan/pull/2)
- [x] Beetle GBA (https://github.com/kodi-game/game.libretro.beetle-gba/pull/3)
- [x] Beetle Lynx (https://github.com/kodi-game/game.libretro.beetle-lynx/pull/2)
- [x] Beetle NeoPop (https://github.com/kodi-game/game.libretro.beetle-ngp/pull/2)
- [x] Beetle PC-FX (https://github.com/kodi-game/game.libretro.beetle-pcfx/pull/3)
- [x] Beetle PCE FAST (https://github.com/kodi-game/game.libretro.beetle-pce-fast/pull/4)
- [x] Beetle PSX (https://github.com/kodi-game/game.libretro.beetle-psx/pull/7)
- [x] Beetle Saturn (https://github.com/kodi-game/game.libretro.beetle-saturn/pull/4)
- [x] Beetle SGX (https://github.com/kodi-game/game.libretro.beetle-supergrafx/pull/3)
- [x] Beetle VB (https://github.com/kodi-game/game.libretro.beetle-vb/pull/2)
- [x] BlueMSX (https://github.com/kodi-game/game.libretro.bluemsx/pull/4)
- [x] bNES (https://github.com/kodi-game/game.libretro.bnes/pull/4)
- [x] bSNES Mercury Accuracy (https://github.com/kodi-game/game.libretro.bsnes-mercury-accuracy/pull/10)
- [x] bSNES Mercury Balanced (https://github.com/kodi-game/game.libretro.bsnes-mercury-balanced/pull/6)
- [x] bSNES Mercury Performance (https://github.com/kodi-game/game.libretro.bsnes-mercury-performance/pull/6)
- [x] Caprice32 (https://github.com/kodi-game/game.libretro.cap32/pull/2)
- [x] DeSmuME (https://github.com/kodi-game/game.libretro.desmume/pull/4)
- [x] Dinothawr (https://github.com/kodi-game/game.libretro.dinothawr/pull/2)
- [x] Dosbox (https://github.com/kodi-game/game.libretro.dosbox/pull/6)
- [x] FCEUmm (https://github.com/kodi-game/game.libretro.fceumm/pull/3)
- [x] Final Burn Alpha (https://github.com/kodi-game/game.libretro.fbalpha/pull/3)
- [x] Final Burn Alpha 2012 (https://github.com/kodi-game/game.libretro.fbalpha2012/pull/3)
- [x] fMSX (https://github.com/kodi-game/game.libretro.fmsx/pull/4)
- [x] FS-UAE (https://github.com/kodi-game/game.libretro.fsuae/pull/1)
- [x] Fuse (https://github.com/kodi-game/game.libretro.fuse/pull/5)
- [x] Gambatte (https://github.com/kodi-game/game.libretro.gambatte/pull/2)
- [x] Genesis Plus GX (https://github.com/kodi-game/game.libretro.genplus/pull/4)
- [x] Handy (https://github.com/kodi-game/game.libretro.handy/pull/2)
- [x] Hatari (https://github.com/kodi-game/game.libretro.hatari/pull/4)
- [x] Lutro (https://github.com/kodi-game/game.libretro.lutro/pull/3)
- [x] MAME (https://github.com/kodi-game/game.libretro.mame/pull/3)
- [x] melonDS (https://github.com/kodi-game/game.libretro.melonds/pull/2)
- [x] Meteor (https://github.com/kodi-game/game.libretro.meteor/pull/5)
- [x] mGBA (https://github.com/kodi-game/game.libretro.mgba/pull/3)
- [x] Mr.Boom (https://github.com/kodi-game/game.libretro.mrboom/pull/3)
- [x] Mupen64Plus (https://github.com/kodi-game/game.libretro.mupen64plus/pull/9)
- [x] Nestopia (https://github.com/kodi-game/game.libretro.nestopia/pull/7)
- [x] NXEngine (https://github.com/kodi-game/game.libretro.nx/pull/3)
- [x] O2EM (https://github.com/kodi-game/game.libretro.o2em/pull/2)
- [x] PCem (https://github.com/kodi-game/game.libretro.pcem/pull/2)
- [x] PCSX Rearmed (https://github.com/kodi-game/game.libretro.pcsx-rearmed/pull/10)
- [x] Picodrive (https://github.com/kodi-game/game.libretro.picodrive/pull/4)
- [x] PokeMini (https://github.com/kodi-game/game.libretro.pokemini/pull/2)
- [x] PPSSPP (https://github.com/kodi-game/game.libretro.ppsspp/pull/3)
- [x] PrBoom (https://github.com/kodi-game/game.libretro.prboom/pull/4)
- [x] Prosystem (https://github.com/kodi-game/game.libretro.prosystem/pull/2)
- [x] QuickNES (https://github.com/kodi-game/game.libretro.quicknes/pull/2)
- [x] Reicast (https://github.com/kodi-game/game.libretro.reicast/pull/5)
- [x] Rustation (https://github.com/kodi-game/game.libretro.rustation/pull/1)
- [x] SameBoy (https://github.com/kodi-game/game.libretro.sameboy/pull/1)
- [x] ScummVM (https://github.com/kodi-game/game.libretro.scummvm/pull/14)
- [x] Snes9x (https://github.com/kodi-game/game.libretro.snes9x/pull/14)
- [x] Snes9x 2002 (https://github.com/kodi-game/game.libretro.snes9x2002/pull/5)
- [x] Snes9x 2010 (https://github.com/kodi-game/game.libretro.snes9x2010/pull/8)
- [x] Stella (https://github.com/kodi-game/game.libretro.stella/pull/2)
- [x] TGB Dual (https://github.com/kodi-game/game.libretro.tgbdual/pull/2)
- [x] TyrQuake (https://github.com/kodi-game/game.libretro.tyrquake/pull/2)
- [x] UAE (https://github.com/kodi-game/game.libretro.uae/pull/1)
- [x] UAE4ARM (https://github.com/kodi-game/game.libretro.uae4arm/pull/1)
- [x] VBA-Next (https://github.com/kodi-game/game.libretro.vba-next/pull/3)
- [x] VBAM (https://github.com/kodi-game/game.libretro.vbam/pull/4)
- [x] Vecx (https://github.com/kodi-game/game.libretro.vecx/pull/3)
- [x] Vice (https://github.com/kodi-game/game.libretro.vice/pull/1)
- [x] Virtual Jaguar (https://github.com/kodi-game/game.libretro.virtualjaguar/pull/2)
- [x] Yabause (https://github.com/kodi-game/game.libretro.yabause/pull/4)

### CODE REVIEW

**Comment by Montellese** [comment]
@garbear I had a quick look at windows builds (can only test Windows 7) and on current master 42 `game.libretro.*` addons compiled fine whereas 26 failed (and `peripheral.steamcontroller` and `peripheral.xarcade`). So it doesn't look like it's completely broken or did I misunderstand something?

**Comment by Rechi** [comment]
@Montellese they (game addons not using msvc on windows) are not compile time broken, but runtime broken.

**Comment by garbear** [comment]
Reports are in, and most things still work. The following input issues with cores have been identified:

- [ ] Input not recognized in Stella (https://github.com/kodi-game/game.libretro.stella/issues/3)
- [ ] No input for Coleco in bluemsx (https://github.com/kodi-game/game.libretro.bluemsx/issues/6)
- [ ] No input in Nestopia (https://github.com/kodi-game/game.libretro.nestopia/issues/8)
- [ ] bluemsx crashes on start (https://github.com/kodi-game/game.libretro.bluemsx/issues/5)
- [ ] FCEUmm crashes on start (https://github.com/kodi-game/game.libretro.fceumm/issues/4)

These are most likely core bugs (gee, I'm shocked). In any case, I accidentally merged https://github.com/kodi-game/game.libretro/pull/31 so now I gotta get this in. I'll follow up with another PR if needed.

jenkins build this please

**Comment by garbear** [comment]
Fixes were all external to this PR. For the record, the fixes include:

* Fix Atari 2600 controller (https://github.com/kodi-game/kodi-game-controllers/pull/22)
* Fix MSX controllers (https://github.com/kodi-game/kodi-game-controllers/pull/23)
* Fix Stella (https://github.com/kodi-game/game.libretro.stella/pull/4)
* Fix blueMSX (https://github.com/kodi-game/game.libretro.bluemsx/pull/7)
* Fix fMSX (https://github.com/kodi-game/game.libretro.fmsx/pull/5)
* Fix Nestopia (https://github.com/kodi-game/game.libretro.nestopia/pull/9)
* Update FCEUmm (https://github.com/kodi-game/game.libretro.fceumm/pull/5)

**Pull request merged**
