### PR TITLE
[cmake] make sure CXX11 is also always set for addons

### PR DESCRIPTION
**Pull request by wsnipex**
## Description

set cxx11 also for addons

## Motivation and Context

fix fallout from https://github.com/xbmc/xbmc/pull/15781

## How Has This Been Tested?

only locally compiled on ubuntu 18.04, so not yet verified on affected travis builders

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Rechi** [comment]
jenkins build this please

**Comment by ksooo** [comment]
Sorry, cannot review due to lack of cmake knowledge and no idea how to runtime-test.

**Review by AlwinEsch — COMMENTED** [review]
From my side OK, but think is not enough.
By this is it only be used on the addons build way over Kodi itself.

If a addon is created independent are this values maybe not present. 
By e.g.: 
```cmake -DADDONS_TO_BUILD=visualization.waveform -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../xbmc/kodi-build/addons -DPACKAGE_ZIP=1 ../../xbmc/cmake/addons```

This generated the: `/build/build/depends/lib/kodi` folder for addon with the following files:
- AddonHelpers.cmake
- AddOptions.cmake
- KodiConfig.cmake
- PrepareEnv.cmake

Maybe are the sets done on background, but not sure if everywhere present, the other on Linux/Ubuntu where this is on `/usr/lib/kodi` is not available.

**EDIT:** Some are set on `KodiConfig.cmake` only the `CMAKE_ASM_FLAGS` not

**Comment by AlwinEsch** [comment]
Ignore a bit my comment before, think your problem is mainly dependent to the depends build where `KodiConfig.cmake` becomes not used.

**Comment by ksooo** [comment]
Is this good to go in?

**Review by AlwinEsch — APPROVED** [review]

**Pull request merged**
