### PR TITLE
[addons] fix repo addon install (<path> in addons.xml wasn't checked)

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description
This fixes a problem that binary addons could not install from the Kodi repo.

From our repo a `<path>` is added to the big addons.xml. Unfortunately, this location is currently not being processed, so it works on script addons, but not on binaries, because the OS name is not added to them.

Error related to https://github.com/xbmc/xbmc/pull/14908, https://forum.kodi.tv/showthread.php?tid=345851 and https://forum.kodi.tv/showthread.php?tid=345994

This is the first round checked by `<extension point="xbmc.addon.metadata">` whether this exists in xml and if so used

## Motivation and Context
To fix the use from repo and fault from me :smile:

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by MilhouseVH** [comment]
I've included this PR in tonight's `#0805` LibreELEC test build, however we don't yet have a binary add-on repository for the nightly test builds but hopefully will have such a repository in the next day or two.

**Comment by ksooo** [comment]
Cannot say anything about correctness of this fix, sorry.

**Comment by Rechi** [comment]
LibreELEC is affected, as it doesn't use the path attribute.

**Review by Rechi — APPROVED** [review]

**Comment by Rechi** [comment]
jenkins build this please

**Pull request merged**
