### PR TITLE
[music node] Add Artists A-Z default music node

### PR DESCRIPTION
**Pull request by zag2me**
Here is a new default node to browse music Artists by their first letter. This will help anyone with a large collection and is a pretty standard for any good music player. If successful with this one I can extend to Albums which will finally make that node useful. I copied this from my working setup so hopefully I got my first Kodi PR correct...

screenshot009

Ping @mkortstiege @night199uk @Montellese

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
doesn't work for non A-Z artists

**Comment by Paxxi** [comment]
As @MartijnKaijser  pointed out and it doesn't really scale having one xml file for every letter of every language. This needs to be done properly in core.

**Comment by zag2me** [comment]
Yep understood and I expected this. I do hope this isn't just closed and forgotten about though, its a really nice feature for anyone that browses music.

Ideally there would be some kind of "Show Index View" option in the config(or xml node source) that could be applied to specific Nodes such as Albums, Artists, TVshows, Movies ect. For example I would find this useful for Movies as well, but maybe not for TVshows.

**Comment by MartijnKaijser** [comment]
We're trying to keep open PRs to a minimum and close the ones that are not going to be merged as they currently are. So I see no point in keeping this one open. Sorry

**Comment by zag2me** [comment]
No worries, at least it promoted some discussion. Close away.

**Comment by zag2me** [comment]
@Montellese I found no way to include symbols unfortunately with a smart playlist, or reverse it so that != A-Z.

At least it wasn't documented how to do this on the WIKI. I could only find ways of creating rules that are true with the first letter. I'd be interested if you know a way.

**Comment by Razzeee** [comment]
Well I'm giving a native c++ version a try, but so far I'm failing at adding a new node to the Music Library Overview. Will keep on tinkering in the next days, but don't expect me to achieve this :X

**Comment by zag2me** [comment]
Since this PR didn't get accepted and nothing happened for 2 years, I had another look ;) It seems @marcelveldt managed to do this purely in Python! That's great, but I would love to see it ported to the Kodi core so we don't need Add-ons :/ 

https://github.com/marcelveldt/script.skin.helper.service/wiki/Alphabet-Jump

@Razzeee the code is here if you wanted to take another stab at it. 

https://github.com/marcelveldt/script.skin.helper.service/blob/master/resources/lib/plugin_content.py#L306

**Pull request closed without merging**
