### PR TITLE
[curl] use better method to stat shoutcast and friends

### PR DESCRIPTION
**Pull request by wsnipex**
follow up of https://github.com/xbmc/xbmc/pull/6376 
should fix ftp thumbs issues with curl 7.40 without breaking shoutcast.
see https://github.com/OpenELEC/OpenELEC.tv/issues/3866#issuecomment-73482469 and https://github.com/OpenELEC/OpenELEC.tv/issues/3900

Instead of relying on purposefully failing curl data writes where HEAD requests don't work, we use the curl progress callback to abort an unwanted download asap.

I'd appreciate some testing.

### CODE REVIEW

**Comment by arnova** [comment]
Looks sane. Actually a nicer approach than it ever was IMO.

**Comment by wsnipex** [comment]
Since no issues came up with @fritsch OE test builds, good to go?

**Comment by fritsch** [comment]
@wsnipex Yes, no issues for now. It's good to go  - if we find bugs later in usecases we did not yet consider, it can be ironed out.

Thanks much again

**Comment by fritsch** [comment]
jenkins build and merge

**Comment by wsnipex** [comment]
narf, why does OSX use an ancient curl version?  CURLOPT_XFERINFOFUNCTION was introduced in 7.32.0
@Memphiz ping

**Comment by Memphiz** [comment]
I hope this reason is "big enough" for you:

https://github.com/xbmc/xbmc/pull/6287

My idea to solve this is linking curl statically - wip https://github.com/Memphiz/xbmc/commits/staticcurl - still waiting for feedback from a user - but for me it didn't crash anymore ...

**Comment by Memphiz** [comment]
I also figured out that its noone from "us" who loads the system libcurl - its one of the systems frameworks we use... (nothing we can do about it)

**Comment by wsnipex** [comment]
ok, thanks Memphiz.
@Karlson2k any chance to bump curl on windows?

**Comment by Paxxi** [comment]
I'm working on new libcurl @wsnipex build is looking good but for some reason kodi fails to connect to anything with it :)

**Comment by Paxxi** [comment]
ok here it is http://delusional.nu/curl-7.40-win32.7z built with windows schannel+idn, libgrcrypt, libgpg-error, libssh2, iconv and zlib. The issue was that Kodi doesn't like async dns resolution and everything failed instantly.

**Comment by wsnipex** [comment]
@Paxxi thanks a lot :) Would you mind making a curl - bump PR? I just uploaded your build to mirrors.

**Comment by Karlson2k** [comment]
@Paxxi Are both win schannel and gcrypt required?

**Comment by Paxxi** [comment]
libssh2 can be built with either gcrypt or openssl and openssl have a weird license so we're trying to avoid it afaik. So gcrypt is used for libssh2 and schannel is used for ssl/tls in curl

**Comment by Paxxi** [comment]
I'll fix that @wsnipex , only for windows or update all platforms?

**Comment by Karlson2k** [comment]
@Paxxi Does Kodi support ssh or it's required for some other protocol, like sftp?

**Comment by Karlson2k** [comment]
@Paxxi Does Kodi support ssh or it's required for some other protocol, like sftp?

**Comment by Karlson2k** [comment]
@Paxxi Does Kodi support ssh or it's required for some other protocol, like sftp?

**Comment by Paxxi** [comment]
hmm, seems like the sftp support is actually handled separately. Shouldn't hurt to have the support in curl anyway. Should try to build with updated libssh as well but that's for another discussion.

**Comment by Karlson2k** [comment]
Less external DLLs - smaller DLL hell.
We should minimize number of additional DLLs as they are interfere with other libs.
If we can exclude libgrcrypt, libgpg-error and libssh2 from libcurl, it would be great improvement.

**Comment by Paxxi** [comment]
it's a single dll, everything is statically linked into libcurl. We could probably use a statically linked libcurl as well but I haven't investigated if we need it for anything else currently and it probably needs more validation.

**Comment by Karlson2k** [comment]
How did you do it?
Libcurl doesn't use libtool? Because libtool don't allow creating of DLLs with statically linked libs.
Anyway - smaller DLL and code is better.
And it's not an easy to build static lib with MinGW for use in VS.

**Comment by Paxxi** [comment]
I took the easy approach, made vs projects and built it :) I'm trying to get away from our mingw dependency

**Comment by wsnipex** [comment]
@Paxxi the bump is only needed for win32. Fyi, other platforms build without libssh2.
https://github.com/xbmc/xbmc/blob/master/tools/depends/target/curl/Makefile
Also, ssh/sftp is handled by libssh(1), which I recently bumped as well.

**Comment by arnova** [comment]
I would certainly INCLUDE support for libssh2. That way we can handle ssh through libcurl, which may do a better job (e.g. performance wise) than the current implementation directly through libssh which is really slow. It also has the added benefit of having to only handle changes in a single location (curlfile.cpp).

**Comment by arnova** [comment]
See http://trac.kodi.tv/ticket/14038

**Comment by wsnipex** [comment]
@Memphiz any update on the OSX curl issue?

**Comment by Memphiz** [comment]
@wsnipex not really. I tried that RTLD_LOCAL approach that notspiff mentioned but it just crashed somwhere in cec code so there is undetermined behavior. The only solution still might be static linking curl - but i never heard back from the user who i have given a test build to. Also my code feels a bit hacky :(

for reference: https://github.com/Memphiz/xbmc/commits/staticcurl

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
jenkins errors unrelated. @Memphiz mind giving this a try on OSX? In particular, testing the Radio addon.

**Comment by Memphiz** [comment]
wsnipex could you cleanout the /home/jenkins/rbpi-dev/firmware dir of rbpi builder? it has some real strange merge error:

http://jenkins.kodi.tv/job/LINUX-RBPI/3485/console (but it seems this is in the firmware repo not in ours ...)

@popcornmix ping - did you force push to the firmware repo or something like that?

**Comment by wsnipex** [comment]
I've done a hard reset on origin/master. Lets see.
jenkins build this please

**Comment by popcornmix** [comment]
@Memphiz my immediate response was no, we don't force push the firmware repo.
But I asked around and it sounds like a colleague may have force pushed a correction just after the initial commit. It shouldn't happen again...

**Comment by MartijnKaijser** [comment]
@popcornmix if you are admin (or some one else) you can ask github to disable force push. We have done this as well to prevent this.

**Comment by wsnipex** [comment]
@Memphiz looks like we need to delete the .success and .failed files at start of every build. OSX64 totally failed due to git timeout but it still shows all addons as built :)

**Comment by Memphiz** [comment]
@wsnipex yeah they are deleted on the build-addons buildstep which we obviously didn't even run due to premature errors ... cosmeitcs ...

**Comment by Memphiz** [comment]
@wsnipex tested this pr quickly just by installing the radio addon and zapping through 10 or so radio channels - no issues :)

**Comment by wsnipex** [comment]
jenkins build this please

**Pull request merged**
