### PR TITLE
[alternative] add logic to wait for the startup window to finish before showing information dialogs during startup

### PR DESCRIPTION
**Pull request by Montellese**
This is an alternative (and IMO cleaner) approach to #6666.

This is an attempt at solving the problem that when we try to show a modal dialog during startup to provide the user with some information, the dialog isn't really shown to the user most of the time because by the time the dialog becomes visible, Confluence's Startup.xml kicks in and executes a ReplaceWindow() call to go to the home window. That ReplaceWindow() call changes the active window and basically hides the modal dialog in the background.

The difference to #6666 is that this doesn't add an ugly busy loop on the window manager to know when the user interface is really ready for these dialogs but instead uses a new GUI message `GUI_MSG_UI_READY`. That message is sent out in one of these cases:
- Kodi has started without the login window and the startup window is not `CGUIWindowStartup` / `Startup.xml`
- Kodi has started with the login window, the user has logged into one of the profiles and the startup window is not `CGUIWindowStartup` / `Startup.xml`
- Kodi has started (with or without the login window) and the startup window is `CGUIWindowStartup` / `Startup.xml` and has been closed

### CODE REVIEW

**Comment by xhaggi** [comment]
looks good +1 from my side, thanks :)

**Comment by mkortstiege** [comment]
+1

**Comment by xhaggi** [comment]
@Montellese we missed the case if the startup window is a PVR window. In that case we delegate the window activation to the PVR manager. See https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/PVRManager.cpp#L518
This is done because we need to startup the PVR manager before we can activate a PVR related window. 

For J*** we need to reconsider it because IMO we should not block the window activation. A better solution could be showing the progress dialog until the PVR manager is ready and the user can cancel the progress dialog and is returned to the previous window e.g. Home.

**Comment by Montellese** [comment]
@xhaggi: I saw that PVR windows are handled special but I didn't know why and I didn't know that it was asynchronous. Could you take a look at the necessary changes since I can't really test it. I'm assuming that the message should be sent from that `if` block you linked to.

**Comment by xhaggi** [comment]
> I'm assuming that the message should be sent from that if block you linked to.

yes

> Could you take a look at the necessary changes since I can't really test it.

sure. if you want to test it by your-self you need to install the pvr.demo addon and set the startup window to a PVR related window.

**Comment by Montellese** [comment]
@xhaggi: Added handling of PVR startup window and tested it with `pvr.demo`. Could you take a look?
jenkins build this please

**Comment by xhaggi** [comment]
looks good, thanks

**Comment by MartijnKaijser** [comment]
failure unrelated

**Comment by Montellese** [comment]
OK to merge for beta?

**Comment by MartijnKaijser** [comment]
i certainly won't object fixes :)

**Comment by MilhouseVH** [comment]
Could someone confirm if [this](http://forum.kodi.tv/showthread.php?tid=224025&pid=2017639#pid2017639) from the forum is expected behaviour?

I'm not familiar with the `<locale>` settings in as.xml, or why `<language>English</language>` would be considered incorrect (and thus fail to load), which presumably is then causing the dialog to be successfully displayed thanks to the second commit in this PR.

Maybe the error isn't actually this PR, which now correctly showing dialogs at startup, but the way this `<language>` tag is being handled (and which would be silently ignored in the past)?

**Comment by Montellese** [comment]
Well first of all the logic in `CLangInfo` should be capable of detecting that `English` is the `resource.language.en_gb` language addon and not fall back to it because it couldn't find one (but I thought there was a log message for that case too).

Secondly having `<language>English</language>` in `advancedsettings.xml` will lead to a situation where `guisettings.xml` will already contain the updated value of `<language>resource.language.en_gb</language>` but it will always be overwritten by the value from `advancedsettings.xml` so the startup logic will always have to try to determine the proper language addon and setting's value.

I've taken a quick look and determined the issue and it's specific to `English` in combination with `advancedsettings.xml`. I'll provide a fix ASAP.

**Pull request merged**
