### PR TITLE
[ffmpeg] Add new audio profiles in stream codec name

### PR DESCRIPTION
**Pull request by sundermann**
## Description

Adds the new profiles for Atmos and DTS to the stream codec name.

## Motivation and context

Allow skinners to use the new audio codec types.

## How has this been tested?

macOS

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by jjd-uk** [comment]
All working here.

image

image

image

Don't suppose any knows where I can a sample of DTS:X Imax enhanced audio. I believe Disney Plus does it but I don't subscribe to that service.

**Review by jjd-uk — APPROVED** [review]

**Review by fritsch — APPROVED** [review]
Thanks very much

**Comment by Hitcher** [comment]
> Don't suppose any knows where I can a sample of DTS:X Imax enhanced audio.

Check Slack, I have a sample for you.

**Comment by Ch1llb0** [comment]
I suppose, because of lack of ffmpeg support, DTS-HD HRA based DTS:X isn't returned as a label?

**Comment by jjd-uk** [comment]
@Ch1llb0 Yes ffmpeg still doesn't support identifying DTS-HD HRA based DTS:X streams. I guess because it's not a very common format the people who added the DTS:X support didn't have anything to work with.

**Comment by Ch1llb0** [comment]
Might be. Not sure there's much more out there than a couple of German UHD BDs... So, not a big issue really. But for the sake of completeness, it would be great to also support this from ffmpeg down at some point 😅

**Pull request merged**
