### PR TITLE
[cmake] don't build and install wiimote if bluetooth is disabled

### PR DESCRIPTION
**Pull request by lrusak**
## Description

Don't build wiimote eventclient if bluetooth is disabled

## Motivation and Context

if event clients are enabled but bluetooth is not it fails to build

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
backport is ready here, https://github.com/lrusak/xbmc/commit/0a26e367ad7d9933b01b353c8edabc610721ec4d

**Comment by wsnipex** [comment]
This will probably fail if ENABLE_BLUETOOTH=Auto (default if not manually set), but not available.
So you should check for if(ENABLE_EVENTCLIENTS AND BLUETOOTH_FOUND)

**Comment by lrusak** [comment]
@wsnipex thanks, I have updated it. I also tested it without setting `ENABLE_BLUETOOTH` and setting `ENABLE_BLUETOOTH=OFF`. It works in both cases.

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by lrusak** [comment]
good to go?

**Pull request merged**
