### PR TITLE
lib: get rid of copy of libmicrohttpd

### PR DESCRIPTION
**Pull request by Montellese**
I just noticed that we still have a copy of `libmicrohttpd` in our `lib` directory even though we download and build it as part of depends and on win32 download a pre-built version so I don't know why we still have this around. Does anyone know of a platform or use case where this is still needed?

I also noticed a few other sub-directories of `lib` which seem to be handled by depends like
- libbluray
- libcec
- taglib

### CODE REVIEW

**Comment by Montellese** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
for me things in lin were ment for linux which could build stuff from there... not sure if this is even used anymore - maybe for distributions where our ppa is not applicable?

**Comment by notspiff** [comment]
No use for any of those.

**Comment by mkortstiege** [comment]
Looks good to me.

**Comment by Montellese** [comment]
@wsnipex: This isn't used for linux standalone right?

**Comment by wsnipex** [comment]
nope, linux uses system libs.

**Pull request merged**
