### PR TITLE
JSON-RPC: Ability to control skin settings

### PR DESCRIPTION
**Pull request by a1rwulf**
## Description
This patch allows basic control of skin setttings via JSON RPC.

New json commands (response is cut):

**Get all settings of the current used skin**
```
curl -s --data-binary '{"jsonrpc":"2.0","method":"Settings.GetSkinSettings","id":1}' -H 'content-type: application/json;' http://localhost:8080/jsonrpc

{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "settings": [
      {
        "id": "circle_rating",
        "type": "bool",
        "value": false
      },
      {
        "id": "WeatherFanart.ext",
        "type": "string",
        "value": ""
      },
      {
        "id": "WeatherFanart.path",
        "type": "string",
        "value": ""
      }
}
```
**Get value of a specific setting**
```
curl -s --data-binary '{"jsonrpc":"2.0","method":"Settings.GetSkinSettingValue","id":1,"params":{"setting":"autoscroll"}}' -H 'content-type: application/json;' http://localhost:8080/jsonrpc

{"id":1,"jsonrpc":"2.0","result":{"value":false}}
```

**Set value of specific setting**
```
curl -s --data-binary '{"jsonrpc":"2.0","method":"Settings.SetSkinSettingValue","id":1,"params":{"setting":"autoscroll","value":true}}' -H 'content-type: application/json;' http://localhost:8080/jsonrpc

{"id":1,"jsonrpc":"2.0","result":true}
```

There are some things that might be worth a discussion:
* Do we really want to have them as separate methods
* If not, how to we put them into the current general settings model
* Should we expose the type bool as "bool" or "boolean" (like it's called for other settings)
* etc. etc.

## Motivation and context
It's kinda strange that those settings can't be controlled via JSON.
I think people might want to change such appearance settings via JSON remote
controls too.

## How has this been tested?
Roughly tested on my dev machine Linux amd64.

Known issues atm:
* If you remove your kodi folder and start for the first time, settings are not returned (because they don't exist on first run)

## What is the effect on users?
Users can toggle skin settings remotely without using the GUI.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by Montellese — CHANGES_REQUESTED** [review]
Looks good in general apart from the issues I commented on.

One thing that came to mind is that it might be confusing for JSON-RPC clients that the available skin settings can change drastically if the user changes the skin in Kodi. Maybe we should return the add-on ID of the skin in `Settings.GetSkinSettings`?

**Review by Montellese — CHANGES_REQUESTED** [review]
Thanks for considering my comments and re-working the code. Found some small suggestion.

Concerning the `const` method returning a `std::shared_ptr<>`: While you are right that from a technical C++ point of view your implementation was correct you still return a non-const pointer to a member of your object from a `const` method giving the caller the possibility to indirectly modify your object. I know that this is done a lot because `const` and (smart) pointers is not very intuitive but personally I think that it should be avoided.

**Comment by a1rwulf** [comment]
I also changed the help text to be a bit more specific.

**Review by Montellese — APPROVED** [review]
Looks good now thanks. Looks like the open JSON-RPC related PRs for Nexus will be merged in order of creation so you'll have to wait for your slot. @DaveTBlake who is going to coordinate this?

**Comment by a1rwulf** [comment]
I'll take care of the formatting again and will wait until I get a ping to update the version number so it can get merged.
Thanks for your guidance 🙂

**Pull request merged**
