### PR TITLE
[rebrand] CAnnouncementManager || sender: use kodi instead of xbmc

### PR DESCRIPTION
**Pull request by un1versal**
These can be observed in the log and not sure if I got them all.

Two things about this.

1) No idea if altering these is harmless as is or if other changes are necessary elsewhere.
2) Wasnt sure if we could use **@APP_NAME@** or **appName** instead which seems more logical I can change that easily now. Let me know?!

If any other changes are required elsewhere please give me a hand as those may be above my ability.

in any case @topfs2 and others for labelling and review, or whoever is :speak_no_evil: "Isengard" release manager. 

@Montellese since he did  #4725 he be able to understand this for review and maybe make some insightful/educational comments for noobs like me.

### CODE REVIEW

**Comment by anaconda** [comment]
Try `cd path-to-repo-here/xbmc; grep -nr '\.Announce(' . | grep xbmc` - I found 57.
Some are checking the sender: `grep -nr sender . | grep \"xbmc\"` - this is probably completely unneeded (as far as I can see the sender is always `xbmc`), however need `kodi` in place of `xbmc`.

**Comment by wsnipex** [comment]
this should probably use the dynamic appname. But since we currently have 3! methods to get it, the whole thing needs a refactor. 
If you are up to it, I'd say add a lower case CSysInfo::GetAppNameLc to utils/SystemInfo.cpp, then use that. See CSysInfo::GetAppName usage in Application.cpp as example

**Comment by uNiversaI** [comment]
> If you are up to it, I'd say add a lower case CSysInfo::GetAppNameLc to utils/SystemInfo.cpp, then use that. See CSysInfo::GetAppName usage in Application.cpp as example

@wsnipex Im not so sure Im confident enough for part 1 but if you can help push PR it to this branch so its included here and Ill make such changes to this portion.

**Comment by wsnipex** [comment]
I don't have the time atm, so it could as well be pulled as is and refactored properly later. Afaik @Karlson2k was already working on it

**Comment by Montellese** [comment]
Yes right now xbmc or rather kodi is the only sender of notifications but theoretically this might change in the future so checking the sender is not a bad idea. It might also be that remote applications are checking the sender so this might break backwards compatibility so I'm a bit reluctant about allowing this.

**Comment by Memphiz** [comment]
me too - just a feeling in the stomack (XBMCHelper rings a bell deep somewhere in my brain)

**Comment by uNiversaI** [comment]
the sender part is only last three commits I can drop those changes and keep CAnnouncementManager or do I understand this wrong?

If this is not good, then feel free to close. its all the same to me.

**Comment by uNiversaI** [comment]
pong. shall I remove the announce changes or close this then?

**Comment by uNiversaI** [comment]
@topfs2 here is the PR to change that as mentioned in #6912

**Comment by ksooo** [comment]
Not sure whether you guys have on your list that addons might be affected by this change? 

Example: https://github.com/kodi-pvr/pvr.hts/blob/master/src/client.cpp#L259

**Comment by uNiversaI** [comment]
@ksoo personally wasnt aware, but If someone handled the addons part at same time it wouldn't become a problem then.

**Comment by ksooo** [comment]
@uNiversaI Sure. But we must coordinate and organize this. From the view of the addons, this is an incompatible API change in Kodi.

@opdenkamp strictly speaking this API change cannot be done for Isengard any more, right?

**Comment by Montellese** [comment]
I don't see any benefit right now at all. It will break addons and any remote application relying on notifications for no good reason. IMO if we ever have to make a reasonable change to the API which is backwards incompatible we can also throw this in but until then I will veto this.

**Comment by topfs2** [comment]
I agree with Montellese. Its a good change at some point but its scary to
break compat.

But for discussion would it make sense to have an array instead of a string
as sender? That way we could send both kodi and xbmc. Or kodi and a third
party. Mostly stating it as my guess is that if someone forks and bases on
us they probably want compliance to our clients.

The idea behind the sender is to consider it a namespace, much like
xbmc.foo in requests. A third party will do bar.foobar if they add a
function and if its good it might trickle down to application namespace.
Kind of like css prefixes.
Den 11 apr 2015 12:00 em skrev "Sascha Montellese" <notifications@github.com

**Comment by Montellese** [comment]
@topfs2: Changing it to an array will also break backwards compatibility. But yes if we would support notification forwarding from other sources having an array as kind of a "forwarding history" could make sense.

**Pull request closed without merging**
