### PR TITLE
[subtitle] fix subtitles archive in archive

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description

Some subtitle packages have itself as e.g. *.rar and the subtitle file
inside also as *.rar.

This checks the given extensions about and recall the function
on this again.

## Motivation and Context

Related to issue reported here https://github.com/xbmc/vfs.rar/issues/84

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by DaveTBlake** [comment]
@AlwinEsch did you not get the team email regarding release plans, milestones and merge freeze? Is this and you other recent work essential for the imminent v19 alpha release? Can it be held for the next? If it can then please change the milestone, otherwise please discuss needs and risks on Slack.

**Comment by AlwinEsch** [comment]
Not so direct arrived here or was gone down somewhere :(

**Comment by DaveTBlake** [comment]
backport tested so we may as well have in alpha1 as well.

**Comment by DaveTBlake** [comment]
jenkins build this please

**Pull request merged**
