### PR TITLE
[cleanup] Bye CryptThreading

### PR DESCRIPTION
**Pull request by hudokkow**
This code is not used anywhere?
Build tested, brief runtime test.

### CODE REVIEW

**Comment by notspiff** [comment]
This is not unused. The global ensures ctor/dtor cycle. I believe this is mostly for droid/ios and was related to usage of static libs.

**Comment by Paxxi** [comment]
Isn't this used for statically linked curl? Or is that the locking?

**Comment by arnova** [comment]
Afaik, this is indeed used by Curl for the SSL/TLS crypto-locker.

**Comment by stefansaraev** [comment]
this is to ensure thread safety with libcurl compiled against openssl < 1.1.0. openssl >= 1.1.0 / libressl / gnutls does not need it.

**Comment by wsnipex** [comment]
this has to be put on hold until openssl >= 1.1.0 is required.

**Comment by hudokkow** [comment]
No problem for me. Thanks for the info @notspiff and @stefansaraev

**Comment by Rechi** [comment]
@hudokkow xbmc/filesystem/DllLibCurl.h and xbmc/filesystem/DllLibCurl.cpp also need some cleanup

**Comment by Rechi** [comment]
@hudokkow this needs a rebase

**Comment by stefansaraev** [comment]
now that #14226 is in. should we merge this and document that openssl 1.1 is required?

**Comment by Rechi** [comment]
- Windows still has openssl 1.0.2, but that could be updated easily.
- Ubuntu 16.04 has openssl 1.0.2 (https://launchpad.net/ubuntu/+source/openssl) and just for removing CryptThreading I wouldn't drop support for that version.

**Comment by phunkyfish** [comment]
PR has merit but will labelled `PR Cleanup: Backburner` and closed for now. Would be a candidate for inclusion down the line if someone wished to take it on.

If the author would like it kept open please just request so on the PR.

**Pull request closed without merging**
