### PR TITLE
[Matrix][PVR] Fix and simplify addon connection state change handling.

### PR DESCRIPTION
**Pull request by ksooo**
Backport of #20091.

@phunkyfish mind looking at the code change?

### CODE REVIEW

**Review by phunkyfish — APPROVED** [review]
LGTM

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
WIN-64 jenkins error is unrelated.

```log
08:45:21 ------------------------------------------------------------
08:45:21 Running testsuite...
08:45:21 [==========] Running 668 tests from 91 test suites.
08:45:21 [----------] Global test environment set-up.
08:45:21 Setup of basic environment failed.
08:45:27 Clean shutdown of TestGlobalPattern1
08:45:27 /xbmc/project/BuildDependencies/msys64/usr/bin/sed: can't read f:\builds\workspace\WIN-64\gtestresults.xml: No such file or directory
08:45:27 Could Not Find f:\builds\workspace\WIN-64\gtestresults.xml
08:45:27         1 file(s) moved.
08:45:27 Done running testsuite
08:45:27 ------------------------------------------------------------
08:45:27 New run name is 'xbmc-PR20092-104293e-#17731'
08:45:27 [File exists] check if file exists [gtestresults.xml]
08:45:28 Run condition [File exists] enabling perform for step [[Archive the artifacts, Publish xUnit test result report]]
08:45:28 Archiving artifacts
08:45:28 INFO: Processing GoogleTest-1.8
08:45:28 INFO: [GoogleTest-1.8] - 1 test report file(s) were found with the pattern 'gtestresults.xml' relative to 'f:\builds\workspace\WIN-64' for the testing framework 'GoogleTest-1.8'.
08:45:28 ERROR: [flexible-publish] Publish xUnit test result report (org.jenkinsci.plugins.xunit.XUnitPublisher@3ecce66a) aborted: The result file 'f:\builds\workspace\WIN-64\gtestresults.xml' for the metric 'GoogleTest' is empty. The result file has been skipped.
08:45:28 Build step 'Flexible publish' changed build result to FAILURE
```

**Pull request merged**
