### PR TITLE
[addons] rename IsBinaryAddonCacheUp to IsAddonInterfaceUp

### PR DESCRIPTION
**Pull request by AlwinEsch**
## Description

As background to sandbox project and as the call no more relates to binary add-on cache becomes it here renamed to have more clean as name. About sandbox was it changed there and now separated to here to make them smaller and remove unrelated changes.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Jenkins build this please

**Review by ksooo — APPROVED** [review]
LGTM

**Review by garbear — APPROVED** [review]
We like smaller and removing unrelated changes.

**Comment by fuzzard** [comment]
Jenkins build this please

**Pull request merged**
