### PR TITLE
Controller fixes backport

### PR DESCRIPTION
**Pull request by garbear**
## Description

Backport of https://github.com/xbmc/xbmc/pull/15763

## How Has This Been Tested?
Builds for x11.

### CODE REVIEW

**Comment by garbear** [comment]
jenkins build this please

**Review by enen92 — APPROVED** [review]

**Comment by garbear** [comment]
@enen92 want to backport your patch?

**Comment by Rechi** [comment]
@garbear please always set the milestone before or right after merging a PR.

**Comment by enen92** [comment]
Would also be nice to set the appropriate labels (e.g. `Type:Backport` on backport PRs; `Backport:Needed on PRs that need to be backported, and `Backport:Done` once a merged PR has a proposed backport PR)

**Pull request merged**
