### PR TITLE
[aml] add rendercapture

### PR DESCRIPTION
**Pull request by stefansaraev**
this implements rendercapture for amlogic.

I could pull few defines from ge2d.h and ask amvidecap for GE2D_FORMAT_S32_ARGB, and avoid a conversion, that works for me, but reserved memory for all boxes I've seen is fb width \* height \* 3 so I am not sure it is good idea

@Memphiz for review, after this your boblight-aml client is not needed anymore. most of it is your code anyway ;)

### CODE REVIEW

**Comment by FernetMenta** [comment]
@stefansaraev I told you already on slack that this approach is dead end. this ifdeffery in in RenderCapture is EOL. Please put the code into the platform specific renderer.

**Comment by stefansaraev** [comment]
@FernetMenta then I'll be happy to wait for your rework and then adapt this ;)

**Comment by FernetMenta** [comment]
If you are interested in this feature, you need to follow my advice or you won't see it soon. You know that I am transforming VideoPlayer and I don't accept any code that goes in opposite direction.

**Comment by stefansaraev** [comment]
as said, once it is reworked, I can rebase, no need to merge this today.

**Comment by MrMC** [comment]
regardless, nice work @stefansaraev

**Comment by Memphiz** [comment]
@stefansaraev - thx - well i have to admit i didn't do that special aml client out of nowhere

https://github.com/Memphiz/xbmc/commits/amlcapture <- rhis was my first approach too (aml rendercapture) - i i remember correct - the problem i had with this was that the led colors where late - thats why i did the client. But i think your approach is the way to go and we should need to figure out why the leds are late (if this is still the case atm - rendercapture was reworked since my last try and this could have fixed it already).

**Comment by fritsch** [comment]
@Memphiz they are most likely late, cause render manager and decoder (which also renders behind he back) are not synced. So you have around 500 ms delay at least between on screen elements and output. Or did you have a "delay" in seconds (> 2) then it captures what the decoder currently has ... which might be something else ...

**Comment by Memphiz** [comment]
yeah it was around 500ms or so but i amsure i don't have that delay on osx ...

**Comment by stefansaraev** [comment]
yep. leds are around 500ms late while playing hd material (hw decoded).

**Comment by MrMC** [comment]
nah, they were late because amlcapture gets what was rendered via bypass direct to layer behind GLES. bypass was just that, the real video render is done by someone else.

The kodi renderer has no clue about it. That's why the previous amlcodec took great pains to try and keep this bypass rending sync with where internal rendering was by the master clock. Master clock is gone, fifo tracking is gone, a lot is gone and it's a wonder that amlcodec even works at all.

The previous code kept things as close as it could get, but by the time something gets captured, it's already behind what is showing on screen and what goes to LED is late.  

The new v4l based amlcodec might give better results. Depending on how it is done.

**Comment by fritsch** [comment]
Infact we wait for this v4l implementation as @codesnake is actively working on that.

**Comment by MrMC** [comment]
working on it is one thing, actually getting it into master will be a bikesheld moment :)

**Comment by fritsch** [comment]
Yeah - especially if the bitching starts right now @MrMC :-) come on, don't assume evil.

**Comment by MrMC** [comment]
I only say that because I know what adding v4l support would need :) It was me that suggested this path long ago. I saw the entire code injection of v4l by aml when I did our own kernel driver for boblight/lightpack support at pivos and thought, humm, this might work but damn what it would need.

BTW, our LEDs were never late :) We dipped into the kernel render path and snatched a copy before it was showing on the screen. Even used the aml kernel hw scaler too. Damn that thing is fast.

**Comment by fritsch** [comment]
Does that need kernel changes? Though I think with the v4l (if we get that going in a performant way at all) that should not be needed anymore.

**Comment by MrMC** [comment]
Was added to aml based kernels long ago. jellybean I think.

**Comment by codesnake** [comment]
New decoder is almost ready (co-called ION video that works via V4L), but I get bad rendering performance via GLES, but maybe I'm doing somethign wrong. In fact original @davilla's decoder is used, just rendering part was changed.  Will cleanup code a little and publish it shortly.

**Comment by stefansaraev** [comment]
after reverting #9152 leds dont seem to be that late anymore. just saying.

**Pull request closed without merging**
