### PR TITLE
ffmpeg: Bump to version 6.0.1

### LINKED ISSUE #23198: Kodi Omega Nightlys cannot play vorbis files anymore
### Describe the bug
Here is a clear and concise description of what the problem is:

I am using kodi nightlies on my shield tv
(Androidtv Arm64) and noticed that the latest nightlys refuse to play music from my library that is in vorbis format (.ogg). 

Latest working version is nightly 20230409. 
Could maybe related to the ffmpeg bump merged a day after?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Music in ogg vorbis format should play fine in paplayer. 

## Actual Behavior

Music in ogg vobis format does not play.

### To Reproduce

1. Install kodi master nightly 20230411 or newer
2. Play an ogg vorbis encoded music file with paplayer and hear nothing
3. Play same file with older nightlies and hear the music.
4. If you use the context menu option >play with >video player the file plays fine. (Only paplayer seems affected)

### Debuglog

The debuglog can be found here:

Here is a log snippet of the error thrown:

2023-04-24 12:42:25.194 T:12909    info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder vorbis
2023-04-24 12:42:25.366 T:12909   error <general>: CAudioDecoder: Unable to Init Codec while loading file /storage/7D52-DD21/Music/VNV Nation/[2023] Wait/VNV Nation - Wait - 01 Wait (single edit).ogg
2023-04-24 12:42:25.376 T:12909 warning <general>: PAPlayer::QueueNextFileEx - Failed to create the decoder

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Android TV 11 (ShieldTV 9.1.1)
 - Kodi version:
 - Kodi Master Nightly after 20230409

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by fritsch**
This fixes #23198

### CODE REVIEW

**Review by lrusak — APPROVED** [review]
Nice.

Changelog: https://git.ffmpeg.org/gitweb/ffmpeg.git/shortlog/n6.0.1

**Comment by 78andyp** [comment]
Out of interest, does this include an upstream fix for #24058?? Thanks.

**Comment by fritsch** [comment]
> Out of interest, does this include an upstream fix for #24058?? Thanks.

No sadly not, as this is no use-case for upstream it seems. We are still checking internally on how to pick it, but also get it towards upstream.

**Comment by fritsch** [comment]
jenkins build this please 

(and sorry for the wrong checksum)

**Comment by thezoggy** [comment]
odd how changelog shows 6.1 not 6.0.1
https://git.ffmpeg.org/gitweb/ffmpeg.git/blob/409b29d3f92c8f0347527c3807c473094574f163:/Changelog

**Review by neo1973 — APPROVED** [review]
I can confirm that #23198 is fixed and noticed no regressions when giving it a quick test.

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by lrusak** [comment]
I'm just going to merge this as jenkins is being a bum.

**Pull request merged**
