### PR TITLE
[Android] Fix MediaCodec freeze when early disposing stream

### PR DESCRIPTION
**Pull request by peak3d**
## Description
Send EOF Marker to MediaCodec when flushing / disposing stream

## Motivation and Context
For DVD menus timing can lead to disposing MediaCodec decoder before one frame was extracted (dequed). NVidia's mpeg2 decoder freezes completely and a system reboot is required t fix.

The issue will appear too if its tried to stop a video stream immediately after start.

## How Has This Been Tested?
NVidia shield / big bugs bunny NTSC iso, without this PR freeze after launch.

## Types of change
- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Comment by peak3d** [comment]
jenkins build this please

**Comment by HomerSp** [comment]
This has caused a regression on my Philips TV (32PFS6401) running Android 7.1.2. Basically, after a cold boot I can play *one* video fine, but after that I only get a black screen but with the audio stream working fine.
I checked logcat, and when it's not working I get a bunch of these messages:
E hwcomposer: vdp_device_swap: vdp_set_display_buf(0) ret -1, erron 1

Should also point out that, eg, youtube doesn't work either after I get the black screen in Kodi, so it seems like the media decoder is stuck somewhere? Youtube and such work fine, as long as I don't start a stream in Kodi.
I have to reboot to get video working again.

I managed to get to this commit by testing the nightly builds:
kodi-20190206-7001c652-master-armeabi-v7a.apk
is fine
kodi-20190207-fee37715-master-armeabi-v7a.apk
is not fine.

Can this possibly be reverted until another fix has been created?

**Comment by peak3d** [comment]
@HomerSp pls. test the PR, if the automated build is finished, you should find the the apk klicking on the jenkins build status

**Comment by HomerSp** [comment]
Looks like jenkins finally built it. I've just tried it and I'm afraid I still have the same problem. I will have a go at compiling it myself and see if I can figure this out.

Here are logs in case you want to have a look:

Working (using kodi-20190206-7001c652-master-armeabi-v7a.apk):
https://gist.github.com/dece330802bf273853bd429709773d2c

Not working (using kodi-20190215-3da85a4e-PR15524-merge-armeabi-v7a.apk):
https://gist.github.com/de6bd36915fec009aa96fb55b1ce6cb7

**Comment by peak3d** [comment]
If you compile by yourself pls.  comment this https://github.com/xbmc/xbmc/pull/15455/files#diff-0b42b40e98e1acc101533dfc22133bc6R1057 and try again. From MediaCodec spec it should be fine and it solves the same issue you arrive on NVIDIA shield with mpeg2 streams.

**Comment by HomerSp** [comment]
Right, I've had a look and I'm pretty sure it's caused by a buggy implementation of MediaCodec on Mediatek chips (that's what my Philips TV uses).
I tried what you said, but it seems that the AMEDIACODEC_BUFFER_FLAG_END_OF_STREAM flag is what actually causes the bug. Basically, I believe the flush command never resets the end of stream flag - which it is supposed to according to the spec. This also explains why other apps like Youtube don't work after starting the video in Kodi.

I've added a check for MTK codecs before sending the eos flag, and it works now. But I'm wondering if this would be an acceptable solution. Can't see any other way to fix this though.

Here's the MTK patch:
https://gist.github.com/67d3c5a52ab5fe577e7dd5eecde5c18d

**Comment by fritsch** [comment]
Please file a bug with your vendor (Philips) in parallel. If we started adding again vendor workarounds ... kodi's decoder would end where it was some years before.

On topic: AMediaCodec_signalEndOfInputStream <- does ti work explicitely instead?

**Comment by HomerSp** [comment]
Yeah, vendor workarounds are ugly and far from ideal - so I will definitely let Philips know of this bug.

AMediaCodec_signalEndOfInputStream was only added in API 26 (8.0) and my Philips TV is running 7.1.2, so you would need to build Kodi against API 26, and add an #if check for the API level.
So yeah, that means it would never be called on my TV. Possibly fixing this without an ugly vendor workaround.
@peak3d could you test if that works on the shield?

Not sure how adding a dependency on a later API level affects the official APK builds though. 

I suppose it could be checked for dynamically using dlsym, but that's not really ideal either.

**Comment by peak3d** [comment]
@HomerSp interestingly it works fine on AFTV with MTK chipset. I'll respect this issue when poking with driver blacklist.

**Comment by HomerSp** [comment]
You mean sending the EOS flag works fine on another device with an MTK chipset? What android version is it? My Philips tv uses mt5861, so it may be restricted to just that chipset.

**Comment by peak3d** [comment]
Running on Amazon AFTMM with Android 7.1.2 API level 25, kernel: Linux ARM 32-bit version 4.4.120+

**Comment by HomerSp** [comment]
Thanks for fixing this - vendor bugs really are quite annoying. I sent an email to Philips with the details and a link to this pull request, so hopefully they will have a look at it and fix it on system level. Though I don't have very high hopes they will.

Just for testing I added libmediandk.so from api 26 to the kodi apk, and used dlopen and dlsym to load and call the AMediaCodec_signalEndOfInputStream function dynamically - and interestingly this actually works and doesn't cause the black screen problem. Don't know if this fixes the shield problem you're seeing, but it definitely works as intended on my philips TV now. Not saying this is a viable fix, as it's quite hacky to get it working - but it is perhaps something that should be looked at in the future.
Like I said earlier, it could be loaded dynamically from the system libmediandk library - provided it's api 26 or higher. This isn't ideal either though, so perhaps the api level check is the best solution.

**Comment by peak3d** [comment]
@HomerSp I don't believe that simply using a newer ndk shared lib enables functionality on the device.
Most likely it will lead simply to a NOOP, whats working for you, too (commenting out)

Lets collect issues with the latest commit, I bet there will be a nice solution in the near future.

**Comment by HomerSp** [comment]
Well, while it's true that AMediaCodec_signalEndOfInputStream wasn't added until api 26, all of the signalEndOfInputStream functionality was actually added in api 18 (signalEndOfInputStream was added to the MediaCoded java api in api level 18). I think they just forgot, or didn't think to add it to the ndk. 
That being said, including a newer libmediandk library in the build definitely is not a solution. Just thought it was quite interesting that worked.
So yeah, I agree, let's just keep it as it is now and hope we won't run into any more issues.

**Pull request merged**
