### PR TITLE
[PVR Addons][backport] Fix XbmcStreamProperties::GetStreamData to actually return the stream found

### PR DESCRIPTION
**Pull request by janbar**

### CODE REVIEW

**Comment by janbar** [comment]
It is backport for #7525

**Comment by janbar** [comment]
Amended with an understandable message.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
@hudokkow could you please wait with the Isengard addons bumps you have in the queue until this got merged? Will do this after successful jenkins build of this PR.

**Comment by hudokkow** [comment]
No problem, see https://github.com/xbmc/xbmc/pull/7525#issuecomment-122254786

**Comment by ksooo** [comment]
Cannot see how the PI addon build jenkins error should be related to this PR...

**Comment by ksooo** [comment]
@MartijnKaijser your button, I'd say.

**Pull request merged**
