### PR TITLE
[RFC] discussion about new observable implementation

### PR DESCRIPTION
**Pull request by Paxxi**
I thought I'd start a discussion about this now that we're on track to be able to use c++11 features.

Currently we have several implementations of this pattern but they all suffer from the same issue, a centralized list of events. If this list of events isn't a good match a new implementation is needed and thus we have a few of these, OnEvent, OnAction, Observable, in settings and so on. I'm not arguing that this can replace all of them but certainly a lot of them.

Pros:
- No centralized list of events, each Observable specifies their own
- One flexible Interface that we can leverage most places
- Perfect forwarding lets us have any kind of parameter we want in event handlers, no more stuffing everything in a struct and worrying about how to map fields.
- Usage of this can let us rework lots of "upcalls" from what's basically Kodilib into GUI code. It's not free and magic but it lays the foundation to start reworking things.

Cons:
- Lots and lots of new Interface classes

This is part of my roadmap of refactoring things. Hopefully you agree that it's a good idea in general(tweaks and fixes are unavoidable ofc). If not I'll have to rethink things but no showstopper.

Since this is making use of the latest buzzwords I have tried to display usage and possible uses in TestObservable.cpp for anyone that hasn't had time to read up on this yet.

Let the discussion commence!

### CODE REVIEW

**Comment by Paxxi** [comment]
ping @Karlson2k code review/design
ping @Montellese code review/design
ping @opdenkamp I think you wrote the current Observer so you probably have some input :)

**Comment by topfs2** [comment]
The same used throughout would be awesome. However I'm not sure if observable pattern is the best approach in this giant project. It might be that we need a messaging (or actor) pattern instead. For example our GUI window messenger and application messenger, both of these needs to go somehow as they are terrible. And not sure if we can accomplish that with this pattern?

**Comment by Paxxi** [comment]
Right, I think having both is a good idea, I forgot about applicationmessenger when I wrote the post but I don't intend for this to replace messenger. We have a use for both a synchronous and asynchronous implementation and they can work together.

**Comment by topfs2** [comment]
Everything is progress. And I'm sure moving to this would help the
messaging stuff a lot. Just thought I'd bring it up :)

**Comment by opdenkamp** [comment]
@Paxxi yeah I indeed did the original one, with the same idea as this PR's description.

but it did support "async updates" back then: NotifyObservers() could notify all observers from a worker thread instead of directly, which is very useful but we've removed it again when merging in PVR, because the implementation would only work if the observable and observers didn't get destroyed (was not using shared ptrs at that point). would be very useful to get that functionality back now that we're looking at it again.

**Comment by Paxxi** [comment]
Adding an async option is an interesting idea and I think it's doable in a reasonable way. Will have to look more into this and how to go about it

**Comment by Paxxi** [comment]
I've thought some more about this and I'm thinking that it's best to keep this implementation simple and synchronous. Changing the templates from IObserver* to IObserver would allow us to use it with either share_ptr or raw pointers which can be useful.

When observing long running objects or other singletons we don't want to use a shared_ptr as removing the observer would destroy it. shared_ptr is obviously beneficial when observing shorter lived objects or by extending this for asynchronous events as well.

I haven't looked at the performance of the below example, maybe not the best on low power systems but It's fairly easy to selectively add asynchronous callbacks with the new C++11/14 futures.
```C++
int a = 10;
int b = 15;

auto temp = std::async(std::launch::async, [this, a, b] {
		this->NotifyObservers(Events::SomethingHappened(), a, b);
	});
```

**Comment by tamland** [comment]
^ Last I heard, that spawned a new thread. A few too many of those will kill performance and use a lot of memory. (You are really at the mercy of the launch::async implementation)

**Comment by Paxxi** [comment]
yeah it should @tamland but it's entirely dependent on the implementation. When I read about it windows seems to use a thread pool in the background so not t bad, linux seemed to perform well but no thread pool. The real issue with std::async would likely be iphone/android and rpi.

**Pull request closed without merging**
