### PR TITLE
Code dump

### PR DESCRIPTION
**Pull request by MaxKellermann**
This is a bunch of improvements I developed for Kodi master. Cherry-pick the commits you like, ignore those you don't like.

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Closing this PR because Paxxi told me I'm not welcome at the Kodi project, see https://github.com/xbmc/xbmc/pull/8868

**Comment by garbear** [comment]
I don't usually speak up in arguments like this, but Paxxi is a valuable team member and I would like a chance to defend his actions. Your statement is not accurate. Paxxi politely said that your attitude is not welcome, not your person or your intentions to improve Kodi. His words:

```
Thank you for the effort but we can do without your attitude in this project
```

Please read the harsh words you wrote:

```
No, that's completely wrong! You didn't read the code.
Or maybe you just don't know C++ well enough to understand the code.
```

```
All your reviews on my code today were complete bullshit.
```

```
Your review doesn't explain anything.
You say it might not be, but that's just generic blah blah.
```

```
Bullshit!
```

You seem like an experienced developer with cool interests (I'm a cyclist too). However, your personal attacks are hurtful and detrimental to our community. Please accompany any future contributions you make to Kodi or other projects with the respect that the other hard-working developers deserve.

**Comment by MaxKellermann** [comment]
No, I'm not going to reconsider my "harsh words". Everything Paxxi wrote was wrong, and he just didn't get it. He kept on posting more and more bullshit, insisting that we was right, even though all of his conclusions were based on misconceptions.

My statement about me not being welcome may appear inaccurate to you; but I was not referring to what Paxxi **wrote**, but what he **did**: he closed the PR, which is a rejection of my changes, based solely on personal grief, not for technical reasons. That is childish.

If anybody believes that my code is welcome at the Kodi project, you know where to find it. I will continue to maintain and publish my personal bug-fix fork.

**Comment by garbear** [comment]
Why would you cause a developer personal grief? I fully support the right of every team member to reject code accompanied by harassment and personal assaults, regardless of the technical merits.

**Pull request closed without merging**
