### PR TITLE
Change some Info log statements to debug

### PR DESCRIPTION
**Pull request by phunkyfish**
## Description

Noticed these appeared quite a lot in the log so and appeared to be more debug statements.

## Motivation and Context

As above

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [X] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by ksooo — APPROVED** [review]
+1

**Comment by djp952** [comment]
Thank you @phunkyfish! May I suggest this particular LOGINFO also appears to be more useful for debugging as opposed to a general message?

https://github.com/xbmc/xbmc/blob/6e731c55b741732a63598a2243bbd2e3064d9c3f/xbmc/pvr/channels/PVRChannelGroup.cpp#L519

**Comment by phunkyfish** [comment]
Added

**Comment by phunkyfish** [comment]
Jenkins build this please

**Pull request merged**
