### PR TITLE
Fix Playlist.Getitems returning empty artist array

### PR DESCRIPTION
**Pull request by DaveTBlake**
This fixes ticket http://trac.kodi.tv/ticket/16447 that Playlist.GetItems returns an empty artist field.

This bug is fall out from the addition of processing for the ARTISTS tag #7281 and the related cleanup of #8158 and needs to go into Jarvis. This restores previous functionality whereby the artist name(s) are returned to JSON as an array formed by splitting the artist desc sting (strArtist field of song table) at the separator.

I have incremented the last digit of JSON version to reflect that a bug is fixed, hope that is correct @Montellese

### CODE REVIEW

**Comment by Razzeee** [comment]
Whats about master? Don't we need it fixed there too?

**Comment by joethefox** [comment]
Tested and I can confirm that this PR restores the old behavior

**Comment by Montellese** [comment]
Thanks.

**Comment by DaveTBlake** [comment]
>Whats about master? Don't we need it fixed there too?

Yes, but there is an arguement in master to do more, that is actually query the song_artist and artist tables, and therefore be able to return the individual artists as in the library along with musicbrainz IDs and artistID etc. So I can roll out this quick fix in K***, but I would rather do the bigger change there.

**Comment by Razzeee** [comment]
I would think, let's do the quick fix and then improve via the bigger change.

**Comment by MartijnKaijser** [comment]
I'd also just include this fix in master and go from there. Of course depends on when the bigger change is "ready".

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Pull request merged**
