### PR TITLE
[cmake] Build LibZip during cmake Build

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
libzip is only used by android.
It supports cmake build system, so lets just build during core cmake build in Find modules
rename findmodule to libzip to match libname

## Motivation and context
Slowly moving tools/depends into cmake ;)

## How has this been tested?
Build aarch64 android without a tools/depends build of libzip.

## What is the effect on users?
N/A

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by Rechi** [comment]
Why move this into the Kodi build process?
This slows down a clean Kodi build (with depends already built).

**Comment by fuzzard** [comment]
Short answer is this is the path im taking to transition away from tools/depends completely. Happy to discuss and lay out my plan on slack if you are interested. Hit me up anytime.

**Comment by fuzzard** [comment]
Hows this for an alternative @Rechi 
we can do a find_package, libzip installs a libzip-config.cmake file, so using config should be suitable. If it doesnt find the package (ie its not built by tools/depends because we would no longer build it as of this PR) it'll build and continue on.

In the long run, i want to change CMAKE_INSTALL_PREFIX to be either user definable for externalproject_add calls, or to refer to DEPENDS_PATH. this would allow a user to save built libs to a folder, ala existing tools/depends for multiple runs. The only potential long term thing id want to look at is pulling from the VERSION file for a minimum version check on the find_package call, so as to not "hardcode" a version number in the find module. Not a requirement for libzip really right now.

**Review by wsnipex — APPROVED** [review]

**Pull request merged**
