### PR TITLE
[backport][cmake] do not use distutils in cmake scripts

### PR DESCRIPTION
**Pull request by hbiyik**
backport of https://github.com/xbmc/xbmc/pull/25211

### CODE REVIEW

**Review by neo1973 — APPROVED** [review]

**Comment by neo1973** [comment]
Jenkins build this please.

**Comment by CastagnaIT** [comment]
edited title, please use the same title of original PRs, it helps GIT comparations

**Comment by neo1973** [comment]
Jenkins build this please.

**Comment by vpeter4** [comment]
Why exactly is this PR needed for Omega?

Because it has issue at least with LE as I mentioned in #25275 for Piers and nothing was changed. Instead issue was bring back to Omega.

**Comment by hbiyik** [comment]
> Why exactly is this PR needed for Omega?

as the PR initially suggests "Distutils is removed since python3.12", it is end of life, meaning that it will not be used anymore and removed, only way to use it is to install a backport of EOL module. That is the reason.

> Because it has issue at least with LE as I mentioned in https://github.com/xbmc/xbmc/issues/25275 for Piers and nothing was changed. Instead issue was bring back to Omega.

Could you suggest some fix? I don't have LE environment, i am sure sysconfig should have support for your use case.

**Comment by vpeter4** [comment]
> Could you suggest some fix?

Already did: https://github.com/xbmc/xbmc/issues/25275

And used as https://github.com/LibreELEC/LibreELEC.tv/pull/9171

**Comment by neo1973** [comment]
See https://github.com/xbmc/xbmc/pull/26208. Will be backported as well.

**Comment by hbiyik** [comment]
> > Could you suggest some fix?
> 
> Already did: #25275
> 
> And used as [LibreELEC/LibreELEC.tv#9171](https://github.com/LibreELEC/LibreELEC.tv/pull/9171)

Understood thanks.

**Pull request merged**
