### PR TITLE
[PVR][addons][guiinfo][Estuary] PVR Addon API 5.7.0: New functions for EPG tags.

### PR DESCRIPTION
**Pull request by ksooo**
API changes:
============================

This PR superseeds #10363. For parts of it I took the great work done by @rbuehlma (thanks, man) as inspiration for this PR. With this PR it should be possible to implement all addon features @rbuehlma requested for pvr.zattoo. The new functionality is imo useful for other (future) add-ons as well.

1. Add API function `IsEPGTagRecordable`
================================================================
Todo  for addon maintainers: At least you have to add a function stub returning PVR_ERROR_NOT_IMPLEMENTED.

1. Add API function `IsEPGTagPlayable`
================================================================
Todo  for addon maintainers: At least you have to add a function stub returning PVR_ERROR_NOT_IMPLEMENTED. If you actually implement this function you also must implement the new API function 'GetEPGTagStreamProperties' 

2. Add API function `GetEPGTagStreamProperties`
================================================================
Todo for addon maintainers: If your addon implements 'IsEPGTagPlayable' you must implement this new API function. Functionality of the new function is similar to `GetChannelStreamProperties`.

4. Add string constant `PVR_STREAM_PROPERTY_INPUTSTREAMADDON`
================================================================
Todo for addon maintainers: none, but if you're currently using hard references to "inputstreamaddon" in your implementations of `Get*StreamProperties`you should change your code to use the new constant.

5. Remove `EPG_TAG::iChannelNumber`
==============================
Todo for addon maintainers: remove references to this field from your code (it's value was never used by Kodi, btw.)

6. Add `EPG_TAG::iUniqueChannelId`
============================
As this is a required field, every addon must be adapted to fill this field. This is pretty easy as this is done in the implementation of `GetEPGForChannel`where a `PVR_CHANNEL` instance is supplied as in parameter. Simply fill `EPG_TAG::iUniqueChannelId` with the supplied `PVR_CHANNEL::iUniqueId` value.

7. Change signature of callback function `EpgEventStateChange`
===============================================
Todo for addon maintainers: In case your addon uses this callback function (only addon known to do this is pvr.hts), remove parameter `iUniqueChannelId` from the respective call.

New functionality added to Kodi core:
============================
+ Respect return values from 'IsRecordable' for instance when creating timers from epg tags or when assembling context menus.
+ Offer the functionality to play a given epg tag from guide window's context menu and guide dialog according to addons implementation of `IsEPGTagPlayable` and `GetEPGTagStreamproperties`. Basic idea behind this feature is to be able to "replay" tv programme items which your tv provider keeps for you (for some time) after they played on live tv. 

screenshot000
screenshot002

I runtime-tested the changes with a hacked version of pvr.hts on macOS, latest Kodi master.

@rbuehlma would be great if you could do some testing with pvr.zattoo
@phil65 could you please take a look at the Estuary changes?

### CODE REVIEW

**Comment by rbuehlma** [comment]
Wow, thank you very much for this :)

I will for sure port pvr.zattoo and pvr.teleboy to this API. But as I am away this weekend, it will probably not be before monday.

**Review by Jalle19 — APPROVED** [review]
Only skimmed through it but it's probably fine

**Comment by ksooo** [comment]
rebased

**Comment by rbuehlma** [comment]
I have adapted pvr.zattoo and pvr.teleboy to this new API and it works like a charm. Thanks for picking it up.

**Comment by ksooo** [comment]
> I have adapted pvr.zattoo and pvr.teleboy to this new API and it works like a charm. Thanks for picking it up.

 Cool. Can you please double-check that you have tested against the latest version of my branch? I force-pushed some (minor) changes less than one hour ago.

**Comment by rbuehlma** [comment]
> Cool. Can you please double-check that you have tested against the latest version of my branch? I force-pushed some (minor) changes less than one hour ago.

Yeah, its still working :)

**Comment by ksooo** [comment]
@rbuelma I think its time that you open PRs against 'repo-binary-addons' for pvr.zattoo and pvr.teleboy to get them officially included in Kodi Leia builds. What do you think?

**Comment by rbuehlma** [comment]
> @rbuehlma I think it's time that you open PRs against 'repo-binary-addons' for pvr.zattoo and pvr.teleboy to get them officially included in Kodi Leia builds. What do you think?

There is at least one open issue open which I would like to first sort out:
As the addon requires access to the HTTP header to retrieve a cookie not handled by Kodi's curl implementation, I have added libcurl to the addon. This works on some platforms but at least on Android, the addon is missing the TLS functions in libcurl. I would prefer to use Kodi's curl functions but would need access to the header for this. @peak3d planned to look into this but I'm not sure if he already did.

Here is a thread about that:
https://forum.kodi.tv/showthread.php?tid=293693

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
Jenkins errors  are unrelated.

**Pull request merged**
