### PR TITLE
AudioSinks

### PR DESCRIPTION
**Pull request by fritsch**
- Add delay smoother for pulseaudio
- Change Audiotracks vector to std::deque to not have to copy the whole queue always.

### CODE REVIEW

**Comment by fritsch** [comment]
pasmooth

**Comment by fritsch** [comment]
jenkins build this please

**Comment by fritsch** [comment]
@notspiff did you have a chance to test this? Any regressions?

**Comment by notspiff** [comment]
i've been running it for a few days with no noticable effect at all. note that i don't play much videos so my "tests" are of dubious relevance.

**Comment by fritsch** [comment]
I think I will close it and bring it back, when really needed. Thanks much for testing.

**Comment by notspiff** [comment]
i just played some videos. heavy desync is observed in all of them.

**Comment by fritsch** [comment]
Good - thx very much, then it needs more work anyways! For completeness: if you remove the smoothing: All is fine again?

**Comment by notspiff** [comment]
no, it was never very good sync here, but it's noticable worse with the smoothing. there's many things that's wrong on this machine for proper video playback, including the use of a bt headset.

**Comment by fritsch** [comment]
That basically means, that our GetDelay is off a lot. Basically I also know - why. It is quite not managable that a device has let's say 3 seconds delay, while we only added 100 ms of data. Furthermore an estimation, that I currently do here, to ignore that part in the delay was a dump fix back at that time ...

If you know a better solution to cope with headsets / network sinks, I am thankful for ideas.

**Pull request closed without merging**
