### PR TITLE
Fix trac 12016, 15790

### PR DESCRIPTION
**Pull request by VioletRed**
Fix a [bug in JSON interface](http://trac.kodi.tv/ticket/15790) that caused Player.GetProperties call to return playist 1 when playing a video, regardless of what the actual playilist was (0 or 1).

### CODE REVIEW

**Comment by FernetMenta** [comment]
looks sane to me
jenkins build this please

**Comment by Montellese** [comment]
This is a tricky one and I'll have to thoroughly think about it. Kodi doesn't really properly support mixed playlists and last I looked into this there were a number of pitfalls throughout our core logic.

The general idea of JSON-RPC's playlist handling is that the `playerid` is actually the `playlistid` because it would be a PITA for clients to always ask for the `playerid` before executing commands. Therefore the `playerid` should never change while the same playlist is playing. But because our playlist handling is in such bad shape it's currently not possible to completely follow this logic.

**Comment by VioletRed** [comment]
> Kodi doesn't really properly support mixed playlists

@Montellese I know mixed playlists is not working very well on kodi. This patch is part of me trying to scratch my big itch. I really want to see a proper support for mixed playlists, and have been working on it for a few weeks. [They appear in Kodi's documentation](http://kodi.wiki/view/Smart_playlist#Types), but don't work as expected, and I would love to have them when I have guests at home :-)

This [bug report describes the problem](http://trac.kodi.tv/ticket/15790)

> The general idea of JSON-RPC's playlist handling is that the playerid is actually the playlistid because it would be a PITA for clients to always ask for the playerid before executing commands. Therefore the playerid should never change while the same playlist is playing

Clients actually do that right now. They have to ask for the playerid before executing commands, because you ask about playlist information using playerid, not playlistid, and because JSON gives them wrong information they are unable to display right information about the item currently playing, or do weird stuff in general. 

For example, if you're playing a music playlist, you have no way to know what playlist is active without calling GetActivePlayers, and then calling GetPlayerProperties on the player returned. That works fine most of the time, but if you create a mixed playlist in "playlistid:0", e.g. using Smart Playlists, and a video starts playing, GetActivePlayers will return "1" (video), and GetPlayerProperties will return "playlistid:1" (wrong), and "position:-1" (wrong). Making the client believe that no playlist is active, and there is no way for the client to realize that the information is wrong. For example, in such situation yatse would change from telling there is a playlist in partymode, to say there's no active playlist.

This patch won't fix the situation for all clients, many will ignore the playlistid returned by JSON, but this fix won't break them, and the ones that do use that information, will be able to display proper information.

**Comment by Montellese** [comment]
It probably can't get any worse than it already is. Someone has to write a completely new playlist framework and integrate it into Kodi and throw away the old one before this can be properly fixed.

You'll have to bump the JSON-RPC API version (bump the fix (third) number).

**Comment by VioletRed** [comment]
> You'll have to bump the JSON-RPC API version (bump the fix (third) number).

Done.

> It probably can't get any worse than it already is. Someone has to write a completely new playlist framework and integrate it into Kodi and throw away the old one before this can be properly fixed.

It probably doesn't need to be something that extreme. I had a discussion [with other user in the forum](http://forum.kodi.tv/showthread.php?tid=216425), and we came to the conclusion that, hopefully,  it only needs a few changes in PlayListPlayer.cpp (commit 156bc1691c35f9e30b10ac4c06a9e809d88af43c), and a few more in PlaylistDirectory to get a consistent and backwards compatible behavior.

**Comment by Montellese** [comment]
@VioletRed: It depends on what you want to be able to do. IMO we should be able to allow users to put together any number (not just two) of (virtual) playlists which can be modified while another playlist is active and then the user can decide which of the playlists should be active. None of these should be bound to any media type or any player.

**Comment by VioletRed** [comment]
> IMO we should be able to allow users to put together any number (not just two) of (virtual) playlists which can be modified while another playlist is active and then the user can decide which of the playlists should be active.

I would prefer the playlists to be named (as they are now), and hide the active playlist implementation (CPlayListPlayer) from the user. It would avoid the user any confusion between in-memory playlists, and in-disk ones. It seems easier to me to understand and implement, but maybe I'm being over optimistic.

Anyway, one step at a time. Just now I want to fix JSON-API.

**Comment by Montellese** [comment]
@Tolriq: Any chance you could give this a try with Yatse and see if it changes/breaks anything for you?
jenkins build this please

**Comment by Tolriq** [comment]
@Montellese I have broken VS when updating my PC, is it possible to have a pre built exe to put over nightly for the tests ?

If not will take me a couple of days before I have time to reinstall Windows to start fresh with a working VS.

**Comment by Tolriq** [comment]
But quickly reading the code : 

```
 case Video:
-      return PLAYLIST_VIDEO;
-
     case Audio:
-      return PLAYLIST_MUSIC;
+      return g_playlistPlayer.GetCurrentPlaylist();
```

May have impact as I know quite some cases where media are started without any playlist so lot's of chance getCurrentPlaylist will not return correct value.

Same for addons that queue media in wrong playlist.

So the default GetCurrentPlaylist should be checked about all edge case scenario and I'm not sure I know all of them :(

**Comment by Tolriq** [comment]
And last thing, but since I'm dropping Eden there's lot's of chance I use more TCP server and notification to bypass some webserver problems.

Should not the notification be updated somehow too ?

**Comment by VioletRed** [comment]
@Tolriq 

> May have impact as I know quite some cases where media are started without any playlist  so lot's of chance getCurrentPlaylist will not return correct value.

Can you explain a bit more? Any example about edge cases? The idea with this patch is that clients that expect right values should work better, and the ones that make assumptions about "player"="playlistid" should keep being broken in the same way they were before. If there is any edge case that would cause a working interaction stop working, or a broken-but-controlled one to break in an uncontrolled way, this patch has to be fixed.

**Comment by Tolriq** [comment]
As Montellese said Playlist code is a mess :) I did once try to read code and forgive :p

Anyway if GetCurrentPlaylist can return none if something is playing then it should be handled by returning the id of the current player as it's right now.

Event if it's current implementation is bad and if playlist id are said to be able to change there's no way to handle all the cases correctly from remote point of view.

So in some cases (mostly addons that can provide audio and video) when a user queue something I assume that if I can't guess the media type I add it to the current playlist if current is none then problem :)

(And same when using Files.getdirectory in file mode there's no type so I use the same trick to avoid guessing from file extensions and inventing the XBMC wheel again.

**Comment by VioletRed** [comment]
> As Montellese said Playlist code is a mess :) I did once try to read code and forgive :p

I know :-(

> Anyway if GetCurrentPlaylist can return none if something is playing then it should be handled by returning the id of the current player as it's right now. 

It would be easy to do but...

> So in some cases (mostly addons that can provide audio and video) when a user queue something I assume that if I can't guess the media type I add it to the current playlist if current is none then problem :)

... I wonder if it's not a better idea to keep the patch as it is. Consider this cases trying to insert an unknown file with yatse:

Case | Where should be inserted? | Where current would insert? | Where patch would insert?
--------|--------|-------|------
Playing a song in playlist 0 |  Playlist 0 | Playlist 0 :white_check_mark: | Playlist 0
Playing a video in playlist 1 | Playlist 1 | Playlist 1 :white_check_mark: | Playlist 1
Playing a song in playlist 1 |  Playlist 1 | Playlist 0 :negative_squared_cross_mark: | Playlist 1
Playing a video in playlist 0 | Playlist 0 | Playlist 1:negative_squared_cross_mark: |  Playlist 0
Playing a song without playlist |  Nowhere (playing will stop after finishing media) :question: | Playlist 0 | Playlist -1 (Error)
Playing a video without playlist | Nowhere (playing will stop after finishing media) :question: | Playlist 1 |  Playlist -1 (Error)

:question: Yatse won't show any playlist when player is stopped. It means that it's impossible, using Yatse, to access the playlist I created after starting a player without a playlist. Wouldn't it better to get a error message instead of queuing a lot of items and then find that you can't play them?

I will do a more detailed test (with Yatse) later and come back to you so you can decide what' works better from the client's point of view.

**Comment by Tolriq** [comment]
Well there's 2 different things.

Yatse only display a playlist when something is playing because displaying 3 playlists all time would confuse users and would require way more queries on XBMC so not efficient at all. (Not talking about future with id that changes and possible multiple playlist)

But when something is playing even if no playlist currently, adding a media to current playlist (even if no playlist is used) will have the media started after. So all works as users want, have having errors when something can work is no go for users, specially due to first point.

For addons for example, use Player.Open on it it won't be in playlist most of the time, meaning no way to queue anything ? And since no way to be sure of correct playlist before starting no way to force the usage of a playlist before play ?
Meaning no way for users to play and queue items from addons (And surely lot's of other cases)

Solution as pointed by @Montellese in a forum thread or another PR, would be to ensure that everything that plays is embedded in a Playlist. (And of course if possible a better playlist API one day)
Or to have a real working mixed playlist like id 3 that remotes can use to handle queing things without too much hassle and if currentplayer is tied to another player display this other playlist too.

Until this is the case, having a running player without playlist to queue is a major break.

Temporary fix would be just to return, as suggested before, the current player id like it is now if GetCurrentPlaylist returns none.

**Comment by VioletRed** [comment]
>  Temporary fix would be just to return, as suggested before, the current player id like it is now if GetCurrentPlaylist returns none.

Ok, changed.

> But when something is playing even if no playlist currently, adding a media to current playlist (even if no playlist is used) will have the media started after.

Gosh what a pitfall, I tested it back in Frodo and didn't work, but never took the time to test again.

> Or to have a real working mixed playlist like id 3

Why not just make playlistsid 0 and 1 refer to the same playlist? To me it seems like the easiest solution to keep backwards compatibility within a big re-work of playlists framework. It seems that it was [discussed long time ago](http://trac.kodi.tv/ticket/5516), without any conclusion.

**Comment by VioletRed** [comment]
Some cleaning of the code, and preparation to tackle http://trac.kodi.tv/ticket/12016 and http://trac.kodi.tv/ticket/15707

**Comment by VioletRed** [comment]
@Montellese, @Tolriq Any decision about this?

**Comment by Tolriq** [comment]
I still had not time to really test since still not re-installed my computer, but if it's not possible for the api to return none when there's an active player from a remote point of view this sounds ok.

For the rest I have 0 decision weight :)

**Comment by MilhouseVH** [comment]
@Tolriq: would it help if I add this to my Pi test builds?

**Comment by Tolriq** [comment]
@MilhouseVH yes this is a way too :) Thanks.

**Comment by MilhouseVH** [comment]
Added this PR in [build #0223](http://forum.kodi.tv/showthread.php?tid=211501&pid=1937244#pid1937244) for Pi1/Pi2 on OpenELEC.

**Comment by VioletRed** [comment]
@MilhouseVH Any result with the test?

@Montellese Any feedback about this or #6547?

**Comment by MilhouseVH** [comment]
@VioletRed: That would be for @Tolriq to answer.

**Comment by Tolriq** [comment]
Basic tests are ok I had no time to make all tests with all addons and strange cases.

**Comment by VioletRed** [comment]
Thanks, @Tolriq! Do have you time to compare with #6547? My tests show that #6547 works better than this one with normal cases, but there might be edge cases that I didn't consider.

**Comment by Tolriq** [comment]
Sorry no time these days :(

**Comment by VioletRed** [comment]
@Montellese I know it's really busy now, but this bug has been falling between the gaps for more than three years now (and bothering me for more than two), and it would be nice to make a decision about it. After @Tolriq's and your feedback  I've come to a solution that seems backwards compatible with existing workarounds and at the same time do fix the bug. Can we build it and try to find someone to test it?

**Comment by mkortstiege** [comment]
Triggered test builds for all platforms. Should be on the mirrors in a few hours.

**Comment by VioletRed** [comment]
@mkortstiege can't find the builds for this patch in http://mirrors.kodi.tv/test-builds

**Comment by mkortstiege** [comment]
@VioletRed should be the ones with 6799292 in filename

**Comment by Montellese** [comment]
TBH I've lost the overview over the whole player and playlist stuff and we're working on top of a broken design/system causing too many odd and unexpected situations. That's why I simply never touched the whole player/playlist stuff anymore in JSON-RPC until it could be properly fixed. If you are confident that this works and you have extensively tested it I'm fine with this.

Maybe we can ask @joethefox to also test this with his official iOS remote so we don't break anything there either?

**Comment by VioletRed** [comment]
@mkortstiege Thanks!

@Montellese I have tested it with Yatse, Chorus and my own greasemonkey script with really good results (now Yatse and chorus show the active playlist all the time, which didn't work before). @Tolriq pointed some edge situations that have been addressed so far, but having a test by a totally independent party would be nice.

**Comment by VioletRed** [comment]
Weekly ping.

I'm still confused about your concerns @Montellese. I have the feeling that you think this is a workaround about a broken design. But I don't see it like that. Making player=playlistid is not the best design idea, but it's easy to live with it. Returning the **wrong** playlistid when asked, that's a bug that should (and can) be fixed.

I'm not trying to fix the JSON interface (I don't know enough about it to even try), I'm just trying to fix an obvious bug.

**Comment by Montellese** [comment]
I would like that @joethefox (or someone else) would give this a try with the official iOS remote and maybe @SyncedSynapse with the new official Android remote. If there are no backwards incompatible changes I'm fine with this but it certainly needs a version bump of the JSON-RPC API.

@VioletRed: I believe that the current implementation of playlists and its handling in core (and because of that also in JSON-RPC) is broken by design and is too inflexible. Simply the fact that we use pre-defined audio, video and picture playlists is wrong because a playlist should be able (and is able) to contain items of different types. What makes it even worse is that it's possible to play certain items without them getting added to any playlist (but this has nothing to do with this PR). Also the fact that you can have a slideshow playing while listening to music and then as part of the slideshow there might be a video but we don't support playling video and music at the same time so one of the two items won't be able to play. It all just doesn't work out.

**Comment by joethefox** [comment]
Sure, I'll try this PR. In the specific, what is the scenario I should try?

**Comment by VioletRed** [comment]
@joethefox, Create a "mixed" smart playlist. When playing a song, execute ```Player.GetActivePlayers()``` and then ```Player.GetProperties("playlistid", "partymode", "position")``` Then do the same when playing a video from the smart playlist. 

Neither "player" nor "playlistid" should change, and position should have a valid value (i.e, not "-1").

A more detailed description in http://trac.kodi.tv/ticket/15790.

**Comment by SyncedSynapse** [comment]
Regarding the Android remote, there's nothing incompatible with this PR, and it solves the issue on mixed playlists.

Actually the Android remote wasn't handling playlists correctly (it wasn't getting the active playlist from Player.GetProperties), which i'll change for the next release.

**Comment by VioletRed** [comment]
Thanks @SyncedSynapse

**Comment by VioletRed** [comment]
@joethefox Have you had time to test this PR?

**Comment by joethefox** [comment]
@VioletRed, Here I am! Tested the PR and I can confirm that there are no regressions from the remote POV.

**Comment by Montellese** [comment]
@joethefox @SyncedSynapse: Thanks a lot for taking the time to test this.
jenkins build this please

**Comment by MartijnKaijser** [comment]
@Montellese 
go for merge?

**Pull request merged**
