### PR TITLE
[CURL] Update to version 7.61.1

### PR DESCRIPTION
**Pull request by peak3d**
## Description
Update to version 7.61.1

## Motivation and Context
CURLINFO_SPEED_DOWNLOAD does return wrong values especially if download takes shor timet.
For example loading 500kb in 0.1sec, CURLINFO_SPEED_DOWNLOAD reports 500kb/sec.

## How Has This Been Tested?
Demo MPD stream
- start with manual stream selection, choose low bitrate stream.
- switch back to Auto stream selection and grep for 'speed' in log

## Types of change
- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Comment by peak3d** [comment]
And for 1 second to 2 seconds? I'm not really interested in writing match around wrong implementations.

**Comment by fritsch** [comment]
getting exact figures when measuring < 1 second for download speeds is meeh anyways. Not sure how often they log internally.

**Comment by peak3d** [comment]
I was surprised that its quite usable if you devide size by time, even for small chunks I got timings of 0.019 seconds which leads to the expected download rate. I have lot of < 1 sec chunks ( 2 seconds stereo fragment) but all tests looked really reasonable.

**Comment by fritsch** [comment]
Then it's even more surprising that the method returns bogus values. Let me ping the curl principal author on his opinion. @badger if you had a short moment, that would be highly appreciated.

**Comment by bagder** [comment]
A dear old subject. Are you possibly using a slightly older curl? We improved the logic a bit in 7.58.0 in [this commit](https://github.com/curl/curl/commit/a8ce5efba92a87ee57ae2241a9af4083cbad9049). If it downloaded 500 bytes in 0.1 seconds, it should say the speed was 5000 bytes/sec.

**Comment by Rechi** [comment]
Thanks for the info, yes unified depends platforms (android, ios, osx) use version 7.56.1.

**Comment by peak3d** [comment]
@Rechi means? We can upgrade?

**Comment by fritsch** [comment]
Ubuntu 18.04 is using 7.58.0-2ubuntu3.2 so our paa already uses this.

Thanks for the upstream info!

**Comment by Rechi** [comment]
Split into two separate commits `[depends] bump curl to 7.61.1` and whatever you want to title the the Kodi change. The depends changes also misses a refresh of `01-pkg-config-openssl.patch` file.

**Pull request merged**
