### PR TITLE
[Webdav]: Native Exists() and Stat() functions

### PR DESCRIPTION
**Pull request by arnova**
Previously we used plain http methods for Webdav file Exists/Stat, and although it works (most of the time), it is wrong and may not work properly with all clients. This PR implements the proper native functions.

### CODE REVIEW

**Comment by arnova** [comment]
@mkortstiege : Please comment/review. Note that I needed to change CCurlFile a bit to avoid logspam.

**Comment by arnova** [comment]
jenkins build this please

**Comment by arnova** [comment]
jenkins build this please

**Comment by arnova** [comment]
jenkins build this please

**Comment by arnova** [comment]
jenkins build this please

**Comment by kib** [comment]
jenkins build this please because github was down earlier today

**Comment by arnova** [comment]
ping @mkortstiege . After some more reading it seems we might as well use the HEAD method for exists/stat, also seems a bit more efficient since less data is transferred. I think we do still want the improvements in CCurlFile.

**Comment by mkortstiege** [comment]
Looks and sounds good to me. Would like to get another +1 so we can shove this in for next beta to get some more testers on it.

**Comment by Paxxi** [comment]
I like the changes but it will be a change in behaviour so I don't think it should go in during Isengaard.

**Comment by arnova** [comment]
@Paxxi: The Curl changes are pretty safe and currently we hammer (retry) on 404 which is not nice. I'd propose the keep this PR on hold and in the meantime I'll open a new one which only has the Curl changes.

**Comment by Paxxi** [comment]
I agree @arnova you have my +1 for merging those :)

**Comment by MartijnKaijser** [comment]
jenkins build and merge

**Comment by arnova** [comment]
@MartijnKaijser : You probably misread the discussion in this PR. But this shouldn't have been merged (yet). And apparently it's causing crashes, so I think for now it would be best to revert until we've fixed the crash and we're sure there's an actual benefit from this.

**Pull request merged**
