### PR TITLE
[estouchy] replace AddonBroken with AddonLifecycleType(Desc) infolabels

### PR DESCRIPTION
**Pull request by ronie**
## Description
in https://github.com/xbmc/xbmc/pull/18286 two new infolabels (ListItem.AddonLifecycleType / ListItem.AddonLifecycleDesc) were added that replace the ListItem.AddonBroken infolabel.

this updates the Estouchy skin for that change.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Have you a screenshot about? Tested here at home and not seen anything on his GUI places.

**Comment by ronie** [comment]
@AlwinEsch thanx for testing it, there were indeed a few issues. i've fixed those now.

addoninfo

**Review by AlwinEsch — APPROVED** [review]
Looks good, thanks a lot for the work!

**Comment by AlwinEsch** [comment]
Because of the text for "Deprecated" and "Broken", it would be good to show it somehow in "skin.estuary", unfortunately this is missing there. Only the definition is available via its icon and then more difficult for the user to know why.

**Comment by AlwinEsch** [comment]
Also something needs to be improved for the auto-update field, in German it doesn't look that nice because its text field goes over the image:
Bildschirmfoto von 2020-09-17 13-02-51

**Comment by ronie** [comment]
thx, fixed:
auto

**Comment by ronie** [comment]
> Because of the text for "Deprecated" and "Broken", it would be good to show it somehow in "skin.estuary", unfortunately this is missing there. Only the definition is available via its icon and then more difficult for the user to know why.

sure, i will look into it.

**Pull request merged**
