### PR TITLE
[Matrix][tools/depends] bump flatbuffers to 1.12.0

### PR DESCRIPTION
**Pull request by ksooo**
backport of #19651 

@garbear fyi and review

### CODE REVIEW

**Comment by garbear** [comment]
thanks for backporting! I'll test next time I'm on my macbook

**Comment by DaveTBlake** [comment]
Bump to 19.2 as not tested yet, and don't want to do a version change in a point release without that.

**Comment by ksooo** [comment]
I tested it.

**Comment by DaveTBlake** [comment]
Oh, I read it that we were waiting on @garbear. 
Does this have any impact on runtime Kodi anyway, or just those that compile for themselves?

**Comment by ksooo** [comment]
> Does this have any impact on runtime Kodi

 No.

**Comment by DaveTBlake** [comment]
Fair enough, no reason to hold back then.

**Comment by emveepee** [comment]
Does this need to be updated for Windows?   Checking Jenkins I see the same as I have here

Getting flatbuffers-1.11.0-20200105.7z...

**Comment by garbear** [comment]
It's not needed to fix building, but all platforms should ideally be on the same version.

**Comment by garbear** [comment]
@lrusak did you know dav1d was behind on matrix on windows?

**Comment by garbear** [comment]
@thexai @enen92 @Paxxi any of you wanna update flatbuffers (and maybe dav1d) on windows?

**Comment by enen92** [comment]
Sorry, not the windows guy :)

**Comment by lrusak** [comment]
> @lrusak did you know dav1d was behind on matrix on windows?

I probably did at some point :upside_down_face:

**Pull request merged**
