### PR TITLE
VideoPlayer: continue normal playback if seek fails

### PR DESCRIPTION
**Pull request by FernetMenta**
in particular useful when hitting an end of timeshift buffer

### CODE REVIEW

**Comment by FernetMenta** [comment]
jenkins build this please

**Comment by Jalle19** [comment]
Did you get my e-mail about the GUI issue with this patch? This looks very similar so I wonder if the issue remains.

**Comment by FernetMenta** [comment]
nope, at least I am not aware of it. how is gui related to this?

**Comment by Jalle19** [comment]
When the play speed is changed here it is not reflected in the UI so the Paused popup can stay on screen and the play button doesn't change to a pause button.

**Pull request closed without merging**
