### PR TITLE
WinSystemXLGL: Properly return msecs for GetVblankTiming

### LINKED ISSUE #19376: Frame drop every 5 seconds or so when playing 60fps media with Kodi 18 and 19 on Linux
### Describe the bug
Here is a clear and concise description of what the problem is:

When I play 60fps media (usually recorded or live TV streams with pvr.hts, but it happens consistently with all 60fps media I have tried), I get a frame drop about every 5 seconds.  This is most noticeable on content with a ticker or content with fast camera movement like sports broadcasts.  It happens with both Kodi 18 and 19.  It may happen with older versions too, but I have not tested.  It does not happen with VLC on the same systems.  I have reproduced the issue on multiple systems, but they all contain Intel processors with integrated graphics and are running Kubuntu 20.10.  I don't have any systems with AMD or NVIDIA graphics to try.  The issue happens regardless of whether VA-API is turned on or off and regardless of whether I am playing true 60fps content or frame-doubled deinterlaced content.  It also happens regardless of whether I select the option to set the display framerate to the content framerate.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should play the media smoothly without dropping any frames.

## Actual Behavior

Kodi drops a frame about every 5 seconds.

### To Reproduce

1. Play a 60fps video stream, preferably one with consistent, smooth motion like a ticker
2. Note that a frame drops every 5 seconds or so.

### Debuglog

The debuglog can be found here: https://pastebin.ubuntu.com/p/XW5sbdMrdv/
This debug log was captured while playing the example video that I offer to upload below.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I have an example video that contains a ticker that demonstrates the problem.  If you indicate where I should upload it, I will do so.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Kubuntu 20.10, fully up-to-date
 - Kodi version: 19.0+git20210219.1315-f44fdfbf67-0+final~groovy (from the official PPA)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by fritsch**
Working towards fixing: #19376. Cudos to FernetMenta.

### CODE REVIEW

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by asavah** [comment]
@fritsch sorry to tell you but this PR makes thing worse at least X/GL amdgpu/vaapi.

With this PR applied as patch on top of current master:
https://paste.kodi.tv/oyakobirob.kodi
The log show only 1 file being played for brevity.
The effect is the same on all the sources I've tried, lots of skips, some drops, stuttering.
In the debug overlay "latency" is changing values like crazy, it's impossible to tell what value it shows (without this PR latency stays as 0.049 all the time).

For reference a debug log playing the same file without this PR applied:
https://paste.kodi.tv/orijixuxic.kodi
no skips, no drops, latency stays as 0.049

**Comment by FernetMenta** [comment]
doesn't surprise me. @fritsch applied the patch to GetFrameLatencyAdjustment instead of GetVblankTiming as shown in my diff :)

**Comment by fritsch** [comment]
Awesome :-) Updated. Thanks.

**Comment by alanswanson** [comment]
Testing this patch, it causes horrendous continual judder with either VAAPI or software decoding on a system with mesa amdgpu under X11/GL.

Maybe needs a second tester to verify it's bad but reverting it fixes or rather resumes the irregular judder every few seconds with SD broadcast interlaced MPEG2 (as most HD broadcast is progressive MPEG4 which is fine) as often reported for intel and amd under X11/GL on the forums along with a few bug reports from when it started occurring with Leia/Matrix but had been fine for Krypton. Not a CPU load issue or even dropped frames issue according to onscreen player debug info.

**Comment by mamarley** [comment]
This isn't fixing #19376 for me.  It doesn't make it any worse, but I'm still getting a frame drop every few seconds.

**Comment by fritsch** [comment]
Okay, then we need to face it. X11 and VAAPI is unmaintained. Please go back to kodi v19 or try to fix it by yourself.

**Comment by FernetMenta** [comment]
Even if it doesn't fix OP's proplem, the patch is correct. If you ignore the minors, you'll never fix the noticeable bugs.

**Comment by mamarley** [comment]
I'm already on v19.  I agree with @FernetMenta though that even if it doesn't fix my problem, it should still be pulled if it is correct.

As far as asking me to fix it myself, don't you think I already would have if I had the ability?

**Comment by fritsch** [comment]
Then let's get this in. One step into the right direction.

**Pull request merged**
