### PR TITLE
[droid] declare small screens, <3,5" screens not supported

### PR DESCRIPTION
**Pull request by MartijnKaijser**

### CODE REVIEW

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by garbear** [comment]
why not?

**Comment by MartijnKaijser** [comment]
it's simply unusable. We have no skins that even make it easy on screens <7" 
Also if you look up the "small screen" specs it also shows that those screens are low res. So any modern device that has <3,5" may fall under "normal" due to the higher resolution.

**Comment by koying** [comment]
Could you build a test apk so that I can ensure it still works on my 4.5", please.

**Comment by MartijnKaijser** [comment]
after some more research there are no "small screen" devices out there that run API17 or higher. So they are already filtered out

**Pull request closed without merging**
