### PR TITLE
[addons] libKODI_guilib.h: Refactor

### PR DESCRIPTION
**Pull request by ksooo**
@AlwinEsch what do you think about this? Removes a lot of duplicate code in libKODI_guilib.h

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Is very good and perfect for cleanup. It remove on all GUI control places the used values and does it in a parent :-).

Also easy to add on my rework and match the coming sytle: https://github.com/FernetMenta/kodi-agile/tree/master/xbmc/addons/kodi-addon-dev-kit/include/kodi/gui

**Comment by ksooo** [comment]
I take your comment as "good to merge". Okay?

**Comment by AlwinEsch** [comment]
Okay

**Comment by ksooo** [comment]
jenkins build this please.

**Pull request merged**
