### PR TITLE
[videoinfotag] Avoid overwriting valid "default" rating with invalid data on scraper parse.

### PR DESCRIPTION
**Pull request by ghost**
With online scrapers (but not with NFO files) ParseNative gets called multiple
times, so avoid adding a "default" rating every time it's called as we may have a valid one already.

See http://forum.kodi.tv/showthread.php?tid=238393&pid=2217024#pid2217024

@phate89 your opinion?

### CODE REVIEW

**Comment by phate89** [comment]
The fix it's ok. 
Maybe you could add a float variable (where we create the node one) and use `XMLUtils::GetFloat` directly to check if it exists in the else if. Not sure what's best.
Thanks for the fix btw..

**Comment by anaconda** [comment]
Up to you.
My first approach was indeed to use `GetFloat`, but then decided I didn't like it.

**Comment by phate89** [comment]
It's probably better to allocate a float variable that we might not use than do an xml parse twice..

**Comment by anaconda** [comment]
Updated.
@phate89 please merge if happy.
jenkins build this please

**Comment by phate89** [comment]
merged. Thanks @anaconda

**Pull request merged**
