### PR TITLE
guilib: do not kill plugin script if we are waiting for user input

### PR DESCRIPTION
**Pull request by FernetMenta**
see title

### CODE REVIEW

**Comment by Tolriq** [comment]
@FernetMenta do you think this is possible to reset the timer when the dialog is shown ?

Reading code, if the dialog is shown for 29sec this only leave 1 sec to get the data.

Typical use case still Youtube browsing from a remote get to search screen, enter the text. 30 sec timeout should start at that moment and not take in account the X seconds he took to enter the data.

**Comment by FernetMenta** [comment]
@Tolriq good input. I updated it, please review.

**Comment by Tolriq** [comment]
Well not at home to test and not fluent with Kodi threading / timers :)
I would have gone an easier way with your previous implementation, adding a simple boolean test in the while and updating the boolean in the loop if dialog was shown. 
Would not have generated a pure 30 sec wait after a dialog but a 30sec + 30sec - dialog duration. But was simple.

Anyway if that code works and address the issue I'm fine with it :)

**Comment by FernetMenta** [comment]
There was a case not considered by the old code that is now fixed: script terminates without calling DirectoryComplete.

**Comment by FernetMenta** [comment]
jenkins build this please

**Pull request merged**
