### PR TITLE
[webos] add key mapping for lg remote

### PR DESCRIPTION
**Pull request by wsnipex**
## Description

- bump webos-userland (includes the needed keysyms)
-  add key mapping for lg remote

## Motivation and context

make the media buttons on LG magic remotes useable

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by sundermann** [comment]
Since the back button is mapped now correctly, the fallback can be removed as well in `tools/webOS/packaging/keyboard.xml`

**Comment by wsnipex** [comment]
> Since the back button is mapped now correctly, the fallback can be removed as well in `tools/webOS/packaging/keyboard.xml`

thanks, removed

**Comment by lrusak** [comment]
Would be nice if you could split 1aa985aafaee2c610bb9bf3c0c690378430eec4f into two commits, one that formats the map, then one that adds the code changes.

**Comment by craigcarnell** [comment]
Works for me, thanks

**Comment by wsnipex** [comment]
> Would be nice if you could split [1aa985a](https://github.com/xbmc/xbmc/commit/1aa985aafaee2c610bb9bf3c0c690378430eec4f) into two commits, one that formats the map, then one that adds the code changes.

done

**Comment by wsnipex** [comment]
that formatting  jenkins suggests is just wrong, that comment was there before my change and doesn't belong to it

**Comment by garbear** [comment]
Try adding a single newline before `#if defined(TARGET_WEBOS)`. There's a 50% chance clang-format won't break the comment.

**Comment by wsnipex** [comment]
> Try adding a single newline before `#if defined(TARGET_WEBOS)`. There's a 50% chance clang-format won't format the comment.

that didn't work. I'm just going to ignore jenkins.

**Review by yol — APPROVED** [review]

**Pull request merged**
