### PR TITLE
[Cmake] Find module internal depends cleanup

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Update Find Modules that can have INTERNAL dependencies built to use a consistent layout

```
if (ENABLE_INTERNAL_MODULE)
   <do internal setup>
else ()
  <find package calls>
endif()

find_package_handle_standard_args

if (MODULE_FOUND)
  <set include/libs>
endif()
```

This reduces duplicate find_package_handle_standard_args calls, and makes the modules consistent

In addition to this, introduce a global property to use to add internal dependecies to the GLOBAL_TARGET_DEPS list.

## Motivation and context
@howie-f commented on being unable to build using ENABLE_INTERNAL_UDFREAD. This lead down a rabbit hole (with more to come) that essentially looks like UDFREAD could never actually be built with the internal call, as the target was never added to GLOBAL_TARGET_DEPS.

## How has this been tested?
Build udfread internal/external and link kodi.bin
Build internal crossguid/fmt/spdlog and link

## What is the effect on users?
N/A

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by howie-f** [comment]
libudfread builds now with this pr.. :+1: 
but fmt doesn't 
```
CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Fmt (missing: FMT_VERSION)
```
so just revert https://github.com/xbmc/xbmc/pull/21020/commits/23d660906535e7184ccc8be662b8353873f20089 to get it rolling.

after that revert building internal _crossguid_ works though jenkins seems to have issues (which may be related to the failing fmt?!)

**Comment by howie-f** [comment]
this way it works for internal udfread + fmt + crossgiud
```diff
diff --git a/cmake/modules/FindFmt.cmake b/cmake/modules/FindFmt.cmake
index 687eadc0bb..7a3e33301d 100644
--- a/cmake/modules/FindFmt.cmake
+++ b/cmake/modules/FindFmt.cmake
@@ -53,6 +53,11 @@ if(ENABLE_INTERNAL_FMT)
 else()
   find_package(FMT 6.1.2 CONFIG REQUIRED QUIET)
 
+include(FindPackageHandleStandardArgs)
+find_package_handle_standard_args(Fmt
+                                  REQUIRED_VARS FMT_LIBRARY FMT_INCLUDE_DIR FMT_VERSION
+                                  VERSION_VAR FMT_VERSION)
+
   if(PKG_CONFIG_FOUND)
     pkg_check_modules(PC_FMT libfmt QUIET)
     if(PC_FMT_VERSION AND NOT FMT_VERSION)
@@ -72,11 +77,6 @@ else()
   select_library_configurations(FMT)
 endif()
 
-include(FindPackageHandleStandardArgs)
-find_package_handle_standard_args(Fmt
-                                  REQUIRED_VARS FMT_LIBRARY FMT_INCLUDE_DIR FMT_VERSION
-                                  VERSION_VAR FMT_VERSION)
-
 if(FMT_FOUND)
   set(FMT_LIBRARIES ${FMT_LIBRARY})
   set(FMT_INCLUDE_DIRS ${FMT_INCLUDE_DIR})
```

**Comment by howie-f** [comment]
ahm, i‘m sorry guys. the diff above is crap and can be screwed. internal fmt is completely ignored with this, i should have cleared my cache before trying 🙂
so actually the only chance for me to build fmt is the mentioned revert.. otherwise there’s the missing FMT_VERSION error

**Comment by fuzzard** [comment]
It's a simple fix, I'll get it sorted today

**Comment by fuzzard** [comment]
Should be fixed now @howie-f 

Also noticed another incorrect hash variable in fmt, so fixed that as well.

**Comment by howie-f** [comment]
thanks @fuzzard. test run active.. looks promising for all internals so far

**Review by wsnipex — APPROVED** [review]
Looks good!

Side note: the ffmpeg modules isn't following the order of internal firstt, then external, but since ffmpeg is special, we can either leave it or update later

**Comment by fuzzard** [comment]
Yeah, i didnt want to screw with ffmpeg yet. Its on the list to cleanup eventually.

**Review by howie-f — APPROVED** [review]

**Pull request merged**
