### PR TITLE
[EPG] Jump to 'now' on init of EPG timeline view

### PR DESCRIPTION
**Pull request by ksooo**
Backport of #7656

### CODE REVIEW

**Comment by ksooo** [comment]
jenkins build this please my friend

**Comment by MartijnKaijser** [comment]
jenkins build this please

**Comment by ksooo** [comment]
@MartijnKajser please do not merge yet. Fix needs to be reworked.

**Comment by ksooo** [comment]
jenkins build this please do your job now

**Comment by ksooo** [comment]
Jenkins seems completely to be f****d up. The build errors are definitely not related to this PR.

**Comment by ksooo** [comment]
@MartijnKaijser things are sorted out now. No more objections. PR can go in. Your button.

**Comment by ksooo** [comment]
jenkins build this please another try

**Comment by ksooo** [comment]
Jenkins failures are not related to this PR.

**Comment by ksooo** [comment]
@MartijnKaijser General question: For Isengard, is it okay if I merge stuff myself or is this always up to you?

**Comment by MartijnKaijser** [comment]
if it's in master and others agree on backport don't wait on me.

**Pull request merged**
