### PR TITLE
Added more metadata to Android TV channels

### PR DESCRIPTION
**Pull request by spauldhaliwal**
## Description
Added ability to display more metadeta on Android TV's channels. Metadata displayed now includes plot, year, rating and runtime for movies, as well as season number, episode number and air date for episodes. Landscape art support has been added as well.

## Motivation and Context
This addition makes browsing Kodi media from Android TV's home screen a richer experience.

## How Has This Been Tested?
Changes were tested on an Nvidia Shield TV

## Screenshots (if appropriate):
https://imgur.com/TX1F0Km
https://imgur.com/TTm7mbr
https://imgur.com/lurvGq7

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
Just a heads up, you have a LOT of whitespace changes. You will be told to put them in their own commit if they are required, but from a quick glance i think a lot of it is unintentional.

Also will need to squash the commits with the same message (ie Episode Artwork Bug fix, and others) into a single commit each

**Comment by fuzzard** [comment]
In addition, you have large chunks of commented out codeblocks. If its not required, remove it, if its needed, uncomment it.

**Comment by HitcherUK** [comment]
Nice addition, thanks.

**Comment by spauldhaliwal** [comment]
@fuzzard Okay thanks! I will take a look and try to resolve these. I think in terms of white space and curly braces they were just done by Android Studio. I will take a look at the rest as well!

**Comment by spauldhaliwal** [comment]
@fuzzard Since removing white space and tweaking code style are cosmetic changes should they be in their own topic branch? Or should I just clean up this branch directly? Thanks again!

**Comment by fuzzard** [comment]
Yeah, just rebase and force push back into this branch.

**Comment by cartmandos** [comment]
@fuzzard are any more changes needed here to the code itself? it would be a shame to not pick this one up. Not wanting to take the original author's credit but would opening a new branch and pr it suffice here?

**Comment by spauldhaliwal** [comment]
@cartmandos Hello! Very sorry I never got around to making the required changes for the PR. To be frank, I'm not experienced with git and wasn't sure what "Yeah, just rebase and force push back into this branch." means exactly. I can say that the changes have been working for me without issue since I made the fork.

Unfortunately, I've been extremely busy with work lately and haven't had the chance to go over this. If all that's required is removing white space and comments, then I could probably get around to it today or tomorrow. (Though I'm still not clear on what rebase and force push means. I'm quite afraid of doing something wrong and losing the branch and changes )

**Comment by fuzzard** [comment]
Im just giving some advice based on my own past experiences.

At the moment you have 16 commits in this PR, of which multiple have the same commit message. You will need to squash them down into fewer commits. 
Usually you may want it to1 commit per major functional change, but in case of whitespace, often team kodi members will request any whitespace changes to be made in their own cosmetic commit. When i looked at this last, i think you will most likely be able to get rid of most, if not all, of your whitespace changes however. Look at the code guidelines i linked above for specifics. Any code committed is required to adhere to those guidelines.

regarding how to update this branch. have a search for some git basic tutorials that explain git rebase and squash the surplus commits using fixup or drop/edit if its not required (whitespace). I dont speak for team kodi, but in its current state i do not believe they will consider this without cleaning the commits up.
Once you have the commits cleaner (less actual commits, no duplicate commit messages, etc), then do a git push -f to force an overwrite from your local machine to the github repo. Once this is done, this PR will automatically be what you pushed to your github repo

**Comment by Dnkhatri** [comment]
Has this pull been abandoned?

**Comment by Dnkhatri** [comment]
similar pr
https://github.com/xbmc/xbmc/pull/16741

**Comment by phunkyfish** [comment]
PR closed as it appears to be obsolete. 

If the author would like it kept open please just request so on the PR. If you feel there is still merit in merging this PR you can request the label be changed to `PR Cleanup: Backburner`.

**Pull request closed without merging**
